Qt 4.8: QAbstractButton Class Reference
QAbstractButton Class Reference abstract
The QAbstractButton class is the abstract base class of button widgets, providing functionality common to buttons.
#include <qabstractbutton.h>
Public Slots
void animateClick (int msec=100)
Performs an animated click: the button is pressed immediately, and released msec milliseconds later (the default is 100 ms).
void click ()
Performs a click.
void setChecked (bool)
void setIconSize (const QSize &size)
void toggle ()
Toggles the state of a checkable button.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void clicked (bool checked=false)
This signal is emitted when the button is activated (i.e.
void pressed ()
This signal is emitted when the button is pressed down.
void released ()
This signal is emitted when the button is released.
void toggled (bool checked)
This signal is emitted whenever a checkable button changes its state.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool autoExclusive () const
bool autoRepeat () const
int autoRepeatDelay () const
int autoRepeatInterval () const
QButtonGroup * group () const
Returns the group that this button belongs to.
QIcon icon () const
QSize iconSize () const
bool isCheckable () const
bool isChecked () const
bool isDown () const
QAbstractButton (QWidget *parent=0)
Constructs an abstract button with a parent.
void setAutoExclusive (bool)
void setAutoRepeat (bool)
void setAutoRepeatDelay (int)
void setAutoRepeatInterval (int)
void setCheckable (bool)
void setDown (bool)
void setIcon (const QIcon &icon)
void setShortcut (const QKeySequence &key)
void setText (const QString &text)
QKeySequence shortcut () const
QString text () const
~QAbstractButton ()
Destroys the button.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
virtual QSize sizeHint () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *e)
Reimplemented Function
virtual void checkStateSet ()
This virtual handler is called when setChecked() was called, unless it was called from within nextCheckState().
bool event (QEvent *e)
Reimplemented Function
void focusInEvent (QFocusEvent *e)
Reimplemented Function
void focusOutEvent (QFocusEvent *e)
Reimplemented Function
virtual bool hitButton (const QPoint &pos) const
Returns true if pos is inside the clickable button rectangle; otherwise returns false.
void keyPressEvent (QKeyEvent *e)
Reimplemented Function
void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
void mousePressEvent (QMouseEvent *e)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
virtual void nextCheckState ()
This virtual handler is called when a button is clicked.
virtual void paintEvent (QPaintEvent *e)=0
Reimplemented Function
QAbstractButton (QAbstractButtonPrivate &dd, QWidget *parent=0)
void timerEvent (QTimerEvent *e)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool autoExclusive
whether auto-exclusivity is enabled
bool autoRepeat
whether autoRepeat is enabled
int autoRepeatDelay
the initial delay of auto-repetition
int autoRepeatInterval
the interval of auto-repetition
bool checkable
whether the button is checkable
bool checked
whether the button is checked
bool down
whether the button is pressed down
QIcon icon
the icon shown on the button
QSize iconSize
the icon size used for this button.
QKeySequence shortcut
the mnemonic associated with the button
QString text
the text shown on the button
Friends
class QButtonGroup
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QAbstractButton class is the abstract base class of button widgets, providing functionality common to buttons.
This class implements an abstract button. Subclasses of this class handle user actions, and specify how the button is drawn.
QAbstractButton provides support for both push buttons and checkable (toggle) buttons. Checkable buttons are implemented in the QRadioButton and QCheckBox classes. Push buttons are implemented in the QPushButton and QToolButton classes; these also provide toggle behavior if required.
Any button can display a label containing text and an icon. setText() sets the text; setIcon() sets the icon. If a button is disabled, its label is changed to give the button a "disabled" appearance.
If the button is a text button with a string containing an ampersand ('&'), QAbstractButton automatically creates a shortcut key. For example:
QPushButton *button = new QPushButton(tr("Ro&ck && Roll"), this);
The Alt+C shortcut is assigned to the button, i.e., when the user presses Alt+C the button will call animateClick(). See the QShortcut documentation for details (to display an actual ampersand, use '&&').
You can also set a custom shortcut key using the setShortcut() function. This is useful mostly for buttons that do not have any text, because they have no automatic shortcut.
button->setIcon(QIcon(":/images/print.png"));
button->setShortcut(tr("Alt+F7"));
All of the buttons provided by Qt (QPushButton, QToolButton, QCheckBox, and QRadioButton) can display both text and icons.
A button can be made the default button in a dialog are provided by QPushButton::setDefault() and QPushButton::setAutoDefault().
QAbstractButton provides most of the states used for buttons:
isDown() indicates whether the button is pressed down.
isChecked() indicates whether the button is checked. Only checkable buttons can be checked and unchecked (see below).
isEnabled() indicates whether the button can be pressed by the user.
Note
As opposed to other widgets, buttons derived from QAbstractButton accepts mouse and context menu events when disabled.
setAutoRepeat() sets whether the button will auto-repeat if the user holds it down. autoRepeatDelay and autoRepeatInterval define how auto-repetition is done.
setCheckable() sets whether the button is a toggle button or not.
The difference between isDown() and isChecked() is as follows. When the user clicks a toggle button to check it, the button is first pressed then released into the checked state. When the user clicks it again (to uncheck it), the button moves first to the pressed state, then to the unchecked state (isChecked() and isDown() are both false).
QAbstractButton provides four signals:
pressed() is emitted when the left mouse button is pressed while the mouse cursor is inside the button.
released() is emitted when the left mouse button is released.
clicked() is emitted when the button is first pressed and then released, when the shortcut key is typed, or when click() or animateClick() is called.
toggled() is emitted when the state of a toggle button changes.
To subclass QAbstractButton, you must reimplement at least paintEvent() to draw the button's outline and its text or pixmap. It is generally advisable to reimplement sizeHint() as well, and sometimes hitButton() (to determine whether a button press is within the button). For buttons with more than two states (like tri-state buttons), you will also have to reimplement checkStateSet() and nextCheckState().
See also
QButtonGroup
Definition at line 58 of file qabstractbutton.h.
Constructors and Destructors
QAbstractButton() [1/2]
QAbstractButton::QAbstractButton (QWidget * parent = 0) explicit
Constructs an abstract button with a parent.
Definition at line 592 of file qabstractbutton.cpp.
Referenced by QRadioButton::event(), QCheckBox::event(), QPushButtonPrivate::hitButton(), QToolButton::QToolButton(), and setIconSize().
     : QWidget(*new QAbstractButtonPrivate, parent, 0)
 {
     Q_D(QAbstractButton);
     d->init();
 }
~QAbstractButton()
QAbstractButton::~QAbstractButton ()
Destroys the button.
Definition at line 602 of file qabstractbutton.cpp.
 {
 #ifndef QT_NO_BUTTONGROUP
     Q_D(QAbstractButton);
     if (d->group)
         d->group->removeButton(this);
 #endif
 }
QAbstractButton() [2/2]
QAbstractButton::QAbstractButton (QAbstractButtonPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 614 of file qabstractbutton.cpp.
     : QWidget(dd, parent, 0)
 {
     Q_D(QAbstractButton);
     d->init();
 }
Functions
animateClick
void QAbstractButton::animateClick (int msec = 100) slot
Performs an animated click: the button is pressed immediately, and released msec milliseconds later (the default is 100 ms).
Calling this function again before the button was released will reset the release timer.
All signals associated with a click are emitted as appropriate.
This function does nothing if the button is disabled.
See also
click()
Definition at line 976 of file qabstractbutton.cpp.
Referenced by QAccessibleButton::doAction(), QAccessibleTabBar::doAction(), QAccessibleTitleBar::doAction(), event(), QLabel::event(), and QMessageBox::keyPressEvent().
 {
     if (!isEnabled())
         return;
     Q_D(QAbstractButton);
     if (d->checkable && focusPolicy() & Qt::ClickFocus)
         setFocus();
     setDown(true);
     repaint(); //flush paint event before invoking potentially expensive operation
     QApplication::flush();
     if (!d->animateTimer.isActive())
         d->emitPressed();
     d->animateTimer.start(msec, this);
 }
autoExclusive()
bool QAbstractButton::autoExclusive () const
Referenced by setAutoExclusive().
autoRepeat()
bool QAbstractButton::autoRepeat () const
Referenced by setAutoRepeat().
autoRepeatDelay()
int QAbstractButton::autoRepeatDelay () const
Referenced by setAutoRepeatDelay().
autoRepeatInterval()
int QAbstractButton::autoRepeatInterval () const
Referenced by setAutoRepeatInterval().
changeEvent()
void QAbstractButton::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QToolButton.
Definition at line 1320 of file qabstractbutton.cpp.
Referenced by QToolButton::changeEvent().
 {
     Q_D(QAbstractButton);
     switch (e->type()) {
     case QEvent::EnabledChange:
         if (!isEnabled())
             setDown(false);
         break;
     default:
         d->sizeHint = QSize();
         break;
     }
     QWidget::changeEvent(e);
 }
checkStateSet()
void QAbstractButton::checkStateSet () protected virtual
This virtual handler is called when setChecked() was called, unless it was called from within nextCheckState().
It allows subclasses to reset their intermediate button states.
See also
nextCheckState()
Reimplemented in QCheckBox.
Definition at line 1043 of file qabstractbutton.cpp.
Referenced by setChecked().
 {
 }
click
void QAbstractButton::click () slot
Performs a click.
All the usual signals associated with a click are emitted as appropriate. If the button is checkable, the state of the button is toggled.
This function does nothing if the button is disabled.
See also
animateClick()
Definition at line 1003 of file qabstractbutton.cpp.
Referenced by QAccessibleButton::doAction(), QMessageBox::event(), QPushButton::keyPressEvent(), QDialog::keyPressEvent(), and QAbstractButtonPrivate::moveFocus().
 {
     if (!isEnabled())
         return;
     Q_D(QAbstractButton);
     QPointer<QAbstractButton> guard(this);
     d->down = true;
     d->emitPressed();
     if (guard) {
         d->down = false;
         nextCheckState();
         if (guard)
             d->emitReleased();
         if (guard)
             d->emitClicked();
     }
 }
clicked
void QAbstractButton::clicked (bool checked = false) signal
This signal is emitted when the button is activated (i.e.
pressed down then released while the mouse cursor is inside the button), when the shortcut key is typed, or when click() or animateClick() is called. Notably, this signal is not emitted if you call setDown(), setChecked() or toggle().
If the button is checkable, checked is true if the button is checked, or false if the button is unchecked.
See also
pressed(), released(), toggled()
Referenced by QToolButton::QToolButton().
event()
bool QAbstractButton::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QToolButton, QPushButton, QCheckBox, QCommandLinkButton, and QRadioButton.
Definition at line 1074 of file qabstractbutton.cpp.
Referenced by QRadioButton::event(), QCheckBox::event(), QPushButton::event(), QToolButton::event(), QVistaBackButton::minimumSizeHint(), and QDockWidgetTitleButton::minimumSizeHint().
 {
     // as opposed to other widgets, disabled buttons accept mouse
     // events. This avoids surprising click-through scenarios
     if (!isEnabled()) {
         switch(e->type()) {
         case QEvent::TabletPress:
         case QEvent::TabletRelease:
         case QEvent::TabletMove:
         case QEvent::MouseButtonPress:
         case QEvent::MouseButtonRelease:
         case QEvent::MouseButtonDblClick:
         case QEvent::MouseMove:
         case QEvent::HoverMove:
         case QEvent::HoverEnter:
         case QEvent::HoverLeave:
         case QEvent::ContextMenu:
 #ifndef QT_NO_WHEELEVENT
         case QEvent::Wheel:
 #endif
             return true;
         default:
             break;
         }
     }
 #ifndef QT_NO_SHORTCUT
     if (e->type() == QEvent::Shortcut) {
         Q_D(QAbstractButton);
         QShortcutEvent *se = static_cast<QShortcutEvent *>(e);
         if (d->shortcutId != se->shortcutId())
             return false;
         if (!se->isAmbiguous()) {
             if (!d->animateTimer.isActive())
                 animateClick();
         } else {
             if (focusPolicy() != Qt::NoFocus)
                 setFocus(Qt::ShortcutFocusReason);
             window()->setAttribute(Qt::WA_KeyboardFocusChange);
         }
         return true;
     }
 #endif
     return QWidget::event(e);
 }
focusInEvent()
void QAbstractButton::focusInEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QPushButton.
Definition at line 1300 of file qabstractbutton.cpp.
Referenced by QPushButton::focusInEvent().
 {
     Q_D(QAbstractButton);
 #ifdef QT_KEYPAD_NAVIGATION
     if (!QApplication::keypadNavigationEnabled())
 #endif
     d->fixFocusPolicy();
     QWidget::focusInEvent(e);
 }
focusOutEvent()
void QAbstractButton::focusOutEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QPushButton.
Definition at line 1311 of file qabstractbutton.cpp.
Referenced by QPushButton::focusOutEvent().
 {
     Q_D(QAbstractButton);
     if (e->reason() != Qt::PopupFocusReason)
         d->down = false;
     QWidget::focusOutEvent(e);
 }
group()
QButtonGroup * QAbstractButton::group () const
Returns the group that this button belongs to.
If the button is not a member of any QButtonGroup, this function returns 0.
See also
QButtonGroup
Definition at line 955 of file qabstractbutton.cpp.
Referenced by QButtonGroup::addButton(), QAbstractButtonPrivate::queryButtonList(), and QButtonGroup::removeButton().
 {
     Q_D(const QAbstractButton);
     return d->group;
 }
hitButton()
bool QAbstractButton::hitButton (const QPoint & pos) const protected virtual
Returns true if pos is inside the clickable button rectangle; otherwise returns false.
By default, the clickable area is the entire widget. Subclasses may reimplement this function to provide support for clickable areas of different shapes and sizes.
Reimplemented in QToolButton, QPushButton, QCheckBox, and QRadioButton.
Definition at line 1068 of file qabstractbutton.cpp.
Referenced by QPushButton::hitButton(), QToolButton::hitButton(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
 {
     return rect().contains(pos);
 }
icon()
QIcon QAbstractButton::icon () const
Referenced by QCommandLinkButton::heightForWidth(), QPushButtonPrivate::hitButton(), QToolButton::hitButton(), QToolBoxPrivate::Page::icon(), QToolBoxButton::initStyleOption(), QToolBoxButton::minimumSizeHint(), QCommandLinkButton::paintEvent(), QDockWidgetTitleButton::paintEvent(), qt_aqua_get_known_size(), QToolButton::QToolButton(), setIcon(), QPushButton::sizeHint(), QToolBoxButton::sizeHint(), and QDockWidgetTitleButton::sizeHint().
iconSize()
QSize QAbstractButton::iconSize () const
Referenced by changeEvent(), QCommandLinkButton::heightForWidth(), QRadioButton::initStyleOption(), QPushButton::initStyleOption(), QToolButton::initStyleOption(), QCommandLinkButton::paintEvent(), qt_aqua_get_known_size(), QToolBoxButton::sizeHint(), and QDockWidgetTitleButton::sizeHint().
isCheckable()
bool QAbstractButton::isCheckable () const
Definition at line 737 of file qabstractbutton.cpp.
Referenced by AccessibleFactory::create(), QAbstractButtonPrivate::fixFocusPolicy(), and nextCheckState().
 {
     Q_D(const QAbstractButton);
     return d->checkable;
 }
isChecked()
bool QAbstractButton::isChecked () const
Definition at line 789 of file qabstractbutton.cpp.
Referenced by QButtonGroup::addButton(), QButtonGroupPrivate::detectCheckedButton(), QScriptDebuggerCodeFinderWidgetPrivate::findOptions(), nextCheckState(), QCommandLinkButton::paintEvent(), QDockWidgetTitleButton::paintEvent(), CloseButton::paintEvent(), and QAccessibleButton::state().
 {
     Q_D(const QAbstractButton);
     return d->checked;
 }
isDown()
bool QAbstractButton::isDown () const
Definition at line 820 of file qabstractbutton.cpp.
Referenced by QToolBoxButton::initStyleOption(), QCommandLinkButton::paintEvent(), QVistaBackButton::paintEvent(), QDockWidgetTitleButton::paintEvent(), CloseButton::paintEvent(), QAccessibleButton::state(), and QAccessibleTitleBar::state().
 {
     Q_D(const QAbstractButton);
     return d->down;
 }
keyPressEvent()
void QAbstractButton::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QPushButton.
Definition at line 1190 of file qabstractbutton.cpp.
Referenced by QPushButton::keyPressEvent().
 {
     Q_D(QAbstractButton);
     bool next = true;
     switch (e->key()) {
     case Qt::Key_Enter:
     case Qt::Key_Return:
         e->ignore();
         break;
     case Qt::Key_Select:
     case Qt::Key_Space:
         if (!e->isAutoRepeat()) {
             setDown(true);
             repaint(); //flush paint event before invoking potentially expensive operation
             QApplication::flush();
             d->emitPressed();
         }
         break;
     case Qt::Key_Up:
     case Qt::Key_Left:
         next = false;
         // fall through
     case Qt::Key_Right:
     case Qt::Key_Down:
 #ifdef QT_KEYPAD_NAVIGATION
         if ((QApplication::keypadNavigationEnabled()
                 && (e->key() == Qt::Key_Left || e->key() == Qt::Key_Right))
                 || (!QApplication::navigationMode() == Qt::NavigationModeKeypadDirectional
                 || (e->key() == Qt::Key_Up || e->key() == Qt::Key_Down))) {
             e->ignore();
             return;
         }
 #endif
         QWidget *pw;
         if (d->autoExclusive
 #ifndef QT_NO_BUTTONGROUP
         || d->group
 #endif
 #ifndef QT_NO_ITEMVIEWS
         || ((pw = parentWidget()) && qobject_cast<QAbstractItemView *>(pw->parentWidget()))
 #endif
         ) {
             // ### Using qobject_cast to check if the parent is a viewport of
             // QAbstractItemView is a crude hack, and should be revisited and
             // cleaned up when fixing task 194373. It's here to ensure that we
             // keep compatibility outside QAbstractItemView.
             d->moveFocus(e->key());
             if (hasFocus()) // nothing happend, propagate
                 e->ignore();
         } else {
             focusNextPrevChild(next);
         }
         break;
     case Qt::Key_Escape:
         if (d->down) {
             setDown(false);
             repaint(); //flush paint event before invoking potentially expensive operation
             QApplication::flush();
             d->emitReleased();
             break;
         }
         // fall through
     default:
         e->ignore();
     }
 }
keyReleaseEvent()
void QAbstractButton::keyReleaseEvent (QKeyEvent * e) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1258 of file qabstractbutton.cpp.
mouseMoveEvent()
void QAbstractButton::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QCheckBox, and QRadioButton.
Definition at line 1167 of file qabstractbutton.cpp.
Referenced by QVistaHelper::leftMargin(), QRadioButton::mouseMoveEvent(), and QCheckBox::mouseMoveEvent().
 {
     Q_D(QAbstractButton);
     if (!(e->buttons() & Qt::LeftButton) || !d->pressed) {
         e->ignore();
         return;
     }
     if (hitButton(e->pos()) != d->down) {
         setDown(!d->down);
         repaint(); //flush paint event before invoking potentially expensive operation
         QApplication::flush();
         if (d->down)
             d->emitPressed();
         else
             d->emitReleased();
         e->accept();
     } else if (!hitButton(e->pos())) {
         e->ignore();
     }
 }
mousePressEvent()
void QAbstractButton::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QToolButton.
Definition at line 1121 of file qabstractbutton.cpp.
Referenced by QVistaHelper::leftMargin(), and QToolButton::mousePressEvent().
 {
     Q_D(QAbstractButton);
     if (e->button() != Qt::LeftButton) {
         e->ignore();
         return;
     }
     if (hitButton(e->pos())) {
         setDown(true);
         d->pressed = true;
         repaint(); //flush paint event before invoking potentially expensive operation
         QApplication::flush();
         d->emitPressed();
         e->accept();
     } else {
         e->ignore();
     }
 }
mouseReleaseEvent()
void QAbstractButton::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QToolButton.
Definition at line 1141 of file qabstractbutton.cpp.
Referenced by QVistaHelper::leftMargin(), and QToolButton::mouseReleaseEvent().
 {
     Q_D(QAbstractButton);
     d->pressed = false;
     if (e->button() != Qt::LeftButton) {
         e->ignore();
         return;
     }
     if (!d->down) {
         e->ignore();
         return;
     }
     if (hitButton(e->pos())) {
         d->repeatTimer.stop();
         d->click();
         e->accept();
     } else {
         setDown(false);
         e->ignore();
     }
 }
nextCheckState()
void QAbstractButton::nextCheckState () protected virtual
This virtual handler is called when a button is clicked.
The default implementation calls setChecked(!isChecked()) if the button isCheckable(). It allows subclasses to implement intermediate button states.
See also
checkStateSet()
Reimplemented in QToolButton, and QCheckBox.
Definition at line 1054 of file qabstractbutton.cpp.
Referenced by click(), QCheckBox::nextCheckState(), QToolButton::nextCheckState(), QAbstractButtonPrivate::notifyChecked(), and timerEvent().
 {
     if (isCheckable())
         setChecked(!isChecked());
 }
paintEvent()
void QAbstractButton::paintEvent (QPaintEvent * e) protected pure virtual
Reimplemented Function
Reimplemented from QWidget.
Implemented in QPrevNextCalButton, QCalToolButton, QTableCornerButton, CloseButton, QDockWidgetTitleButton, QToolButton, QPushButton, QMenuBarExtension, QCheckBox, QToolBoxButton, QVistaBackButton, QCommandLinkButton, QRadioButton, and QToolBarExtension.
pressed
void QAbstractButton::pressed () signal
This signal is emitted when the button is pressed down.
See also
released(), clicked()
Referenced by QToolButtonPrivate::init(), and QPushButton::setMenu().
released
void QAbstractButton::released () signal
This signal is emitted when the button is released.
See also
pressed(), clicked(), toggled()
setAutoExclusive()
void QAbstractButton::setAutoExclusive (bool autoExclusive)
Definition at line 934 of file qabstractbutton.cpp.
 {
     Q_D(QAbstractButton);
     d->autoExclusive = autoExclusive;
 }
setAutoRepeat()
void QAbstractButton::setAutoRepeat (bool autoRepeat)
Definition at line 842 of file qabstractbutton.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), QTabBarPrivate::init(), QPrintPreviewDialogPrivate::init(), and QToolButton::QToolButton().
 {
     Q_D(QAbstractButton);
     if (d->autoRepeat == autoRepeat)
         return;
     d->autoRepeat = autoRepeat;
     if (d->autoRepeat && d->down)
         d->repeatTimer.start(d->autoRepeatDelay, this);
     else
         d->repeatTimer.stop();
 }
setAutoRepeatDelay()
void QAbstractButton::setAutoRepeatDelay (int autoRepeatDelay)
Definition at line 874 of file qabstractbutton.cpp.
Referenced by QPrintPreviewDialogPrivate::init().
 {
     Q_D(QAbstractButton);
     d->autoRepeatDelay = autoRepeatDelay;
 }
setAutoRepeatInterval()
void QAbstractButton::setAutoRepeatInterval (int autoRepeatInterval)
Definition at line 900 of file qabstractbutton.cpp.
Referenced by QPrintPreviewDialogPrivate::init().
 {
     Q_D(QAbstractButton);
     d->autoRepeatInterval = autoRepeatInterval;
 }
setCheckable()
void QAbstractButton::setCheckable (bool checkable)
Definition at line 727 of file qabstractbutton.cpp.
Referenced by QToolBarExtension::QToolBarExtension(), and QToolButton::setDefaultAction().
 {
     Q_D(QAbstractButton);
     if (d->checkable == checkable)
         return;
     d->checkable = checkable;
     d->checked = false;
 }
setChecked
void QAbstractButton::setChecked (bool checked) slot
Definition at line 754 of file qabstractbutton.cpp.
Referenced by nextCheckState(), QCheckBox::setCheckState(), QToolButton::setDefaultAction(), QToolBarLayout::setExpanded(), QPrintDialogPrivate::setPrinter(), and toggle().
 {
     Q_D(QAbstractButton);
     if (!d->checkable || d->checked == checked) {
         if (!d->blockRefresh)
             checkStateSet();
         return;
     }
     if (!checked && d->queryCheckedButton() == this) {
         // the checked button of an exclusive or autoexclusive group cannot be  unchecked
 #ifndef QT_NO_BUTTONGROUP
         if (d->group ? d->group->d_func()->exclusive : d->autoExclusive)
             return;
         if (d->group)
             d->group->d_func()->detectCheckedButton();
 #else
         if (d->autoExclusive)
             return;
 #endif
     }
     QPointer<QAbstractButton> guard(this);
     d->checked = checked;
     if (!d->blockRefresh)
         checkStateSet();
     d->refresh();
     if (guard && checked)
         d->notifyChecked();
     if (guard)
         emit toggled(checked);
 }
setDown()
void QAbstractButton::setDown (bool down)
Definition at line 807 of file qabstractbutton.cpp.
Referenced by animateClick(), changeEvent(), QAccessibleToolButton::doAction(), QToolBar::event(), QPushButton::focusOutEvent(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and QPushButton::showMenu().
 {
     Q_D(QAbstractButton);
     if (d->down == down)
         return;
     d->down = down;
     d->refresh();
     if (d->autoRepeat && d->down)
         d->repeatTimer.start(d->autoRepeatDelay, this);
     else
         d->repeatTimer.stop();
 }
setIcon()
void QAbstractButton::setIcon (const QIcon & icon)
Definition at line 676 of file qabstractbutton.cpp.
Referenced by QDialogButtonBoxPrivate::createButton(), QPushButtonPrivate::hitButton(), QToolButton::hitButton(), QBalloonTip::QBalloonTip(), QMenuBarExtension::QMenuBarExtension(), QPushButton::QPushButton(), QScriptNewBreakpointWidget::QScriptNewBreakpointWidget(), QToolButton::QToolButton(), QToolButton::setDefaultAction(), QToolBoxPrivate::Page::setIcon(), QToolBarExtension::setOrientation(), QCalendarWidgetPrivate::updateButtonIcons(), and QDockWidgetPrivate::updateButtons().
 {
     Q_D(QAbstractButton);
     d->icon = icon;
     d->sizeHint = QSize();
     update();
     updateGeometry();
 }
setIconSize
void QAbstractButton::setIconSize (const QSize & size) slot
Definition at line 1425 of file qabstractbutton.cpp.
Referenced by QToolBarLayout::createItem(), and QBalloonTip::QBalloonTip().
 {
     Q_D(QAbstractButton);
     if (d->iconSize == size)
         return;
     d->iconSize = size;
     d->sizeHint = QSize();
     updateGeometry();
     if (isVisible()) {
         update();
     }
 }
setShortcut()
void QAbstractButton::setShortcut (const QKeySequence & key)
Definition at line 700 of file qabstractbutton.cpp.
Referenced by QDialogButtonBoxPrivate::createButton(), and setText().
 {
     Q_D(QAbstractButton);
     if (d->shortcutId != 0)
         releaseShortcut(d->shortcutId);
     d->shortcut = key;
     d->shortcutId = grabShortcut(key);
 }
setText()
void QAbstractButton::setText (const QString & text)
Definition at line 641 of file qabstractbutton.cpp.
Referenced by QCalendarWidgetPrivate::_q_monthChanged(), QFileDialogPrivate::_q_updateOkButton(), QCalendarWidgetPrivate::_q_yearEditingFinished(), QPrintPropertiesDialog::addItemToOptions(), QWizardPrivate::ensureButton(), QRadioButton::event(), QCheckBox::event(), QPushButtonPrivate::hitButton(), QCheckBox::QCheckBox(), QCommandLinkButton::QCommandLinkButton(), QPushButton::QPushButton(), QRadioButton::QRadioButton(), QScriptNewBreakpointWidget::QScriptNewBreakpointWidget(), QToolButton::QToolButton(), QDialogButtonBoxPrivate::retranslateStrings(), QToolButton::setDefaultAction(), QFileDialog::setLabelText(), QToolBoxPrivate::Page::setText(), and QCalendarWidgetPrivate::updateNavigationBar().
 {
     Q_D(QAbstractButton);
     if (d->text == text)
         return;
     d->text = text;
 #ifndef QT_NO_SHORTCUT
     QKeySequence newMnemonic = QKeySequence::mnemonic(text);
     setShortcut(newMnemonic);
 #endif
     d->sizeHint = QSize();
     update();
     updateGeometry();
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::NameChanged);
 #endif
 }
shortcut()
QKeySequence QAbstractButton::shortcut () const
Referenced by setShortcut().
text()
QString QAbstractButton::text () const
Referenced by QWizardPrivate::ensureButton(), QRadioButton::event(), QCheckBox::event(), QMessageBox::event(), QMessageBoxPrivate::hideSpecial(), QPushButtonPrivate::hitButton(), QToolBoxButton::initStyleOption(), QFileDialog::labelText(), QCommandLinkButton::paintEvent(), QToolBoxButton::paintEvent(), qt_aqua_get_known_size(), QDialogButtonBoxPrivate::retranslateStrings(), QProgressDialog::setCancelButton(), setText(), QRadioButton::sizeHint(), QCheckBox::sizeHint(), QCommandLinkButton::sizeHint(), QPushButton::sizeHint(), QToolBoxButton::sizeHint(), QToolButton::sizeHint(), QAccessibleToolButton::text(), QToolBoxPrivate::Page::text(), and QVistaHelper::topPadding().
timerEvent()
void QAbstractButton::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Reimplemented in QToolButton.
Definition at line 1278 of file qabstractbutton.cpp.
Referenced by QToolButton::timerEvent().
 {
     Q_D(QAbstractButton);
     if (e->timerId() == d->repeatTimer.timerId()) {
         d->repeatTimer.start(d->autoRepeatInterval, this);
         if (d->down) {
             QPointer<QAbstractButton> guard(this);
             nextCheckState();
             if (guard)
                 d->emitReleased();
             if (guard)
                 d->emitClicked();
             if (guard)
                 d->emitPressed();
         }
     } else if (e->timerId() == d->animateTimer.timerId()) {
         d->animateTimer.stop();
         d->click();
     }
 }
toggle
void QAbstractButton::toggle () slot
Toggles the state of a checkable button.
See also
checked
Definition at line 1030 of file qabstractbutton.cpp.
 {
     Q_D(QAbstractButton);
     setChecked(!d->checked);
 }
toggled
void QAbstractButton::toggled (bool checked) signal
This signal is emitted whenever a checkable button changes its state.
checked is true if the button is checked, or false if the button is unchecked.
This may be the result of a user action, click() slot activation, or because setChecked() was called.
The states of buttons in exclusive button groups are updated before this signal is emitted. This means that slots can act on either the "off" signal or the "on" signal emitted by the buttons in the group whose states have changed.
For example, a slot that reacts to signals emitted by newly checked buttons but which ignores signals from buttons that have been unchecked can be implemented using the following pattern:
void MyWidget::reactToToggle(bool checked)
{
   if (checked) {
      // Examine the new button states.
      ...
   }
}
Button groups can be created using the QButtonGroup class, and updates to the button states monitored with the QButtonGroup::buttonClicked() signal.
See also
checked, clicked()
Referenced by setChecked().
Friends and Related Functions
QButtonGroup
friend class QButtonGroup friend
Definition at line 173 of file qabstractbutton.h.
Properties
autoExclusive
bool QAbstractButton::autoExclusive private
whether auto-exclusivity is enabled
If auto-exclusivity is enabled, checkable buttons that belong to the same parent widget behave as if they were part of the same exclusive button group. In an exclusive button group, only one button can be checked at any time; checking another button automatically unchecks the previously checked one.
The property has no effect on buttons that belong to a button group.
autoExclusive is off by default, except for radio buttons.
See also
QRadioButton
Definition at line 71 of file qabstractbutton.h.
Referenced by QAbstractButtonPrivate::queryButtonList().
autoRepeat
bool QAbstractButton::autoRepeat private
whether autoRepeat is enabled
If autoRepeat is enabled, then the pressed(), released(), and clicked() signals are emitted at regular intervals when the button is down. autoRepeat is off by default. The initial delay and the repetition interval are defined in milliseconds by autoRepeatDelay and autoRepeatInterval .
Note: If a button is pressed down by a shortcut key, then auto-repeat is enabled and timed by the system and not by this class. The pressed(), released(), and clicked() signals will be emitted like in the normal case.
Definition at line 70 of file qabstractbutton.h.
autoRepeatDelay
int QAbstractButton::autoRepeatDelay private
the initial delay of auto-repetition
Since
4.2
If autoRepeat is enabled, then autoRepeatDelay defines the initial delay in milliseconds before auto-repetition kicks in.
See also
autoRepeat, autoRepeatInterval
Definition at line 72 of file qabstractbutton.h.
autoRepeatInterval
int QAbstractButton::autoRepeatInterval private
the interval of auto-repetition
Since
4.2
If autoRepeat is enabled, then autoRepeatInterval defines the length of the auto-repetition interval in millisecons.
See also
autoRepeat, autoRepeatDelay
Definition at line 73 of file qabstractbutton.h.
checkable
QAbstractButton::checkable private
whether the button is checkable
By default, the button is not checkable.
See also
checked
Definition at line 68 of file qabstractbutton.h.
Referenced by QAbstractButtonPrivate::moveFocus(), and setCheckable().
checked
QAbstractButton::checked private
whether the button is checked
Only checkable buttons can be checked. By default, the button is unchecked.
See also
checkable
Definition at line 69 of file qabstractbutton.h.
Referenced by QAbstractButtonPrivate::moveFocus(), QAbstractButtonPrivate::queryCheckedButton(), and setChecked().
down
QAbstractButton::down private
whether the button is pressed down
If this property is true, the button is pressed down. The signals pressed() and clicked() are not emitted if you set this property to true. The default is false.
Definition at line 74 of file qabstractbutton.h.
Referenced by QPushButtonPrivate::_q_popupPressed(), QToolButtonPrivate::popupTimerDone(), and setDown().
icon
QIcon QAbstractButton::icon private
the icon shown on the button
The icon's default size is defined by the GUI style, but can be adjusted by setting the iconSize property.
Definition at line 63 of file qabstractbutton.h.
iconSize
QSize QAbstractButton::iconSize private
the icon size used for this button.
The default size is defined by the GUI style. This is a maximum size for the icons. Smaller icons will not be scaled up.
Definition at line 64 of file qabstractbutton.h.
shortcut
QKeySequence QAbstractButton::shortcut private
the mnemonic associated with the button
Definition at line 66 of file qabstractbutton.h.
Referenced by QAccessibleButton::keyBindings(), and QMessageBox::keyPressEvent().
text
QString QAbstractButton::text private
the text shown on the button
If the button has no text, the text() function will return a an empty string.
If the text contains an ampersand character ('&'), a shortcut is automatically created for it. The character that follows the '&' will be used as the shortcut key. Any previous shortcut will be overwritten, or cleared if no shortcut is defined by the text. See the QShortcut documentation for details (to display an actual ampersand, use '&&').
There is no default text.
Definition at line 62 of file qabstractbutton.h.
Referenced by QDialogButtonBoxPrivate::addButton(), QWizard::setButton(), and QAccessibleButton::text().
The documentation for this class was generated from the following files:
/src/gui/widgets/qabstractbutton.h
/src/gui/widgets/qabstractbutton.cpp