Qt 4.8: QWSSoundServerClient Class Reference
QWSSoundServerClient Class Reference
Public Slots
void sendDeviceError (int, int, int)
void sendDeviceReady (int, int)
void sendSoundCompleted (int, int)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void pause (int, int)
void play (int, int, const QString &)
void play (int, int, const QString &, int, int)
void playPriorityOnly (bool)
void playRaw (int, int, const QString &, int, int, int, int)
void resume (int, int)
void setMute (int, int, bool)
void setSilent (bool)
void setVolume (int, int, int, int)
void stop (int, int)
void stopAll (int)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QWSSoundServerClient (QWS_SOCK_BASE *s, QObject *parent)
~QWSSoundServerClient ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void tryReadCommand ()
Private Functions
void sendClientMessage (QString msg)
Static Private Functions
static int nextId ()
Properties
int left
int mCurrentID
bool priExist
int right
QPointer< QWS_SOCK_BASE > socket
Static Private Attributes
static int lastId = 0
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 116 of file qsoundqss_qws.cpp.
Constructors and Destructors
QWSSoundServerClient()
QWSSoundServerClient::QWSSoundServerClient (QWS_SOCK_BASE * s, QObject * parent)
Definition at line 160 of file qsoundqss_qws.cpp.
                                                                             :
     QObject( parent )
 {
     socket = s;
     priExist = false;
     mCurrentID = nextId();
     connect(socket,SIGNAL(readyRead()),
         this,SLOT(tryReadCommand()));
     connect(socket, SIGNAL(disconnected()), this, SLOT(deleteLater()));
 }
~QWSSoundServerClient()
QWSSoundServerClient::~QWSSoundServerClient ()
Definition at line 171 of file qsoundqss_qws.cpp.
 {
     if (priExist)
     playPriorityOnly(false);
     emit stopAll(mCurrentID);
     if (socket)
         socket->deleteLater();
 }
Functions
nextId()
static int QWSSoundServerClient::nextId () inline static private
Definition at line 154 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerClient().
 { return ++lastId; }
pause
void QWSSoundServerClient::pause (int , int) signal
Referenced by tryReadCommand().
play [1/2]
void QWSSoundServerClient::play (int , int , const QString &) signal
Referenced by tryReadCommand().
play [2/2]
void QWSSoundServerClient::play (int , int , const QString & , int , int) signal
playPriorityOnly
void QWSSoundServerClient::playPriorityOnly (bool) signal
Referenced by tryReadCommand(), and ~QWSSoundServerClient().
playRaw
void QWSSoundServerClient::playRaw (int , int , const QString & , int , int , int , int) signal
Referenced by tryReadCommand().
resume
void QWSSoundServerClient::resume (int , int) signal
Referenced by tryReadCommand().
sendClientMessage()
void QWSSoundServerClient::sendClientMessage (QString msg) private
Definition at line 244 of file qsoundqss_qws.cpp.
Referenced by sendDeviceError(), sendDeviceReady(), and sendSoundCompleted().
 {
 #ifndef QT_NO_TEXTCODEC
     QByteArray u = msg.toUtf8();
 #else
     QByteArray u = msg.toLatin1();
 #endif
     socket->write(u.data(), u.length());
     socket->flush();
 }
sendDeviceError
void QWSSoundServerClient::sendDeviceError (int gid, int sid, int err) slot
Definition at line 269 of file qsoundqss_qws.cpp.
 {
     if (gid == mCurrentID)
         sendClientMessage(QLatin1String("DEVICEERROR ")
                           + QString::number(sid) + QLatin1Char(' ')
                           + QString::number(err) + QLatin1Char('\n'));
 }
sendDeviceReady
void QWSSoundServerClient::sendDeviceReady (int gid, int sid) slot
Definition at line 262 of file qsoundqss_qws.cpp.
 {
     if (gid == mCurrentID)
         sendClientMessage(QLatin1String("DEVICEREADY ")
                           + QString::number(sid) + QLatin1Char('\n'));
 }
sendSoundCompleted
void QWSSoundServerClient::sendSoundCompleted (int gid, int sid) slot
Definition at line 255 of file qsoundqss_qws.cpp.
 {
     if (gid == mCurrentID)
         sendClientMessage(QLatin1String("SOUNDCOMPLETED ")
                           + QString::number(sid) + QLatin1Char('\n'));
 }
setMute
void QWSSoundServerClient::setMute (int , int , bool) signal
Referenced by tryReadCommand().
setSilent
void QWSSoundServerClient::setSilent (bool) signal
Referenced by tryReadCommand().
setVolume
void QWSSoundServerClient::setVolume (int , int , int , int) signal
Referenced by tryReadCommand().
stop
void QWSSoundServerClient::stop (int , int) signal
Referenced by tryReadCommand().
stopAll
void QWSSoundServerClient::stopAll (int) signal
Referenced by ~QWSSoundServerClient().
tryReadCommand
void QWSSoundServerClient::tryReadCommand () private slot
Definition at line 199 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerClient().
 {
     while ( socket->canReadLine() ) {
     QString l = QString::fromAscii(socket->readLine());
     l.truncate(l.length()-1); // chomp
     QString functionName = getStringTok(l);
     int soundid = getNumTok(l);
     if (functionName == QLatin1String("PLAY")) {
         emit play(mCurrentID, soundid, l);
     } else if (functionName == QLatin1String("PLAYEXTEND")) {
         int volume = getNumTok(l);
         int flags = getNumTok(l);
         emit play(mCurrentID, soundid, l, volume, flags);
     } else if (functionName == QLatin1String("PLAYRAW")) {
         int chs = getNumTok(l);
         int freq = getNumTok(l);
         int bitspersample = getNumTok(l);
         int flags = getNumTok(l);
         emit playRaw(mCurrentID, soundid, l, freq, chs, bitspersample, flags);
     } else if (functionName == QLatin1String("PAUSE")) {
         emit pause(mCurrentID, soundid);
     } else if (functionName == QLatin1String("STOP")) {
         emit stop(mCurrentID, soundid);
     } else if (functionName == QLatin1String("RESUME")) {
         emit resume(mCurrentID, soundid);
     } else if (functionName == QLatin1String("SETVOLUME")) {
         int left = getNumTok(l);
         int right = getNumTok(l);
         emit setVolume(mCurrentID, soundid, left, right);
     } else if (functionName == QLatin1String("MUTE")) {
         emit setMute(mCurrentID, soundid, true);
     } else if (functionName == QLatin1String("UNMUTE")) {
         emit setMute(mCurrentID, soundid, false);
     } else if (functionName == QLatin1String("PRIORITYONLY")) {
         bool sPri = soundid != 0;
         if (sPri != priExist) {
         priExist = sPri;
         emit playPriorityOnly(sPri);
         }
     } else if(functionName == QLatin1String("SILENT")) {
         emit setSilent( soundid != 0 );
     }
     }
 }
Properties
lastId
int QWSSoundServerClient::lastId = 0 static private
Definition at line 153 of file qsoundqss_qws.cpp.
left
int QWSSoundServerClient::left private
Definition at line 151 of file qsoundqss_qws.cpp.
Referenced by tryReadCommand().
mCurrentID
int QWSSoundServerClient::mCurrentID private
Definition at line 150 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerClient(), sendDeviceError(), sendDeviceReady(), sendSoundCompleted(), tryReadCommand(), and ~QWSSoundServerClient().
priExist
bool QWSSoundServerClient::priExist private
Definition at line 152 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerClient(), tryReadCommand(), and ~QWSSoundServerClient().
right
int QWSSoundServerClient::right private
Definition at line 151 of file qsoundqss_qws.cpp.
Referenced by tryReadCommand().
socket
QPointer<QWS_SOCK_BASE> QWSSoundServerClient::socket private
Definition at line 155 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerClient(), sendClientMessage(), tryReadCommand(), and ~QWSSoundServerClient().
The documentation for this class was generated from the following file:
/src/gui/embedded/qsoundqss_qws.cpp