Qt 4.8: QTemporaryFileEngine Class Reference
QTemporaryFileEngine Class Reference
Public Functions
bool close ()
Reimplemented Function
bool isReallyOpen ()
bool open (QIODevice::OpenMode flags)
Reimplemented Function
QTemporaryFileEngine (const QString &file, bool fileIsTemplate=true)
bool remove ()
Reimplemented Function
bool rename (const QString &newName)
Reimplemented Function
void setFileName (const QString &file)
Reimplemented Function
void setFileTemplate (const QString &fileTemplate)
~QTemporaryFileEngine ()
Public Functions inherited from QFSFileEngine
Iterator * beginEntryList (QDir::Filters filters, const QStringList &filterNames)
bool caseSensitive () const
Returns true for Windows, false for Unix.
bool copy (const QString &newName)
For windows, copy the file to file copyName.
Iterator * endEntryList ()
QStringList entryList (QDir::Filters filters, const QStringList &filterNames) const
bool extension (Extension extension, const ExtensionOption *option=0, ExtensionReturn *output=0)
Reimplemented Function
FileFlags fileFlags (FileFlags type) const
Reimplemented Function
QString fileName (FileName file) const
Reimplemented Function
QDateTime fileTime (FileTime time) const
Reimplemented Function
bool flush ()
Reimplemented Function
int handle () const
Reimplemented Function
bool isRelativePath () const
Reimplemented Function
bool isSequential () const
Reimplemented Function
bool link (const QString &newName)
Creates a link from the file currently specified by fileName() to newName.
bool mkdir (const QString &dirName, bool createParentDirectories) const
Reimplemented Function
bool open (QIODevice::OpenMode flags, FILE *fh)
Opens the file handle fh in openMode mode.
bool open (QIODevice::OpenMode flags, int fd)
Opens the file descriptor fd in openMode mode.
bool open (QIODevice::OpenMode flags, int fd, QFile::FileHandleFlags handleFlags)
Opens the file descriptor fd in openMode mode.
bool open (QIODevice::OpenMode flags, FILE *fh, QFile::FileHandleFlags handleFlags)
Opens the file handle fh in openMode mode.
QString owner (FileOwner) const
Reimplemented Function
uint ownerId (FileOwner) const
In Unix, if stat() is successful, the uid is returned if own is the owner.
qint64 pos () const
Reimplemented Function
QFSFileEngine ()
Constructs a QFSFileEngine.
QFSFileEngine (const QString &file)
Constructs a QFSFileEngine for the file name file.
qint64 read (char *data, qint64 maxlen)
Reimplemented Function
qint64 readLine (char *data, qint64 maxlen)
Reimplemented Function
bool rmdir (const QString &dirName, bool recurseParentDirectories) const
Reimplemented Function
bool seek (qint64)
Reimplemented Function
bool setPermissions (uint perms)
Reimplemented Function
bool setSize (qint64 size)
Reimplemented Function
qint64 size () const
Reimplemented Function
bool supportsExtension (Extension extension) const
Reimplemented Function
qint64 write (const char *data, qint64 len)
Reimplemented Function
~QFSFileEngine ()
Destructs the QFSFileEngine.
Public Functions inherited from QAbstractFileEngine
bool atEnd () const
Returns true if the current position is at the end of the file; otherwise, returns false.
QFile::FileError error () const
Returns the QFile::FileError that resulted from the last failed operation.
QString errorString () const
Returns the human-readable message appropriate to the current error reported by error().
uchar * map (qint64 offset, qint64 size, QFile::MemoryMapFlags flags)
Maps size bytes of the file into memory starting at offset.
bool unmap (uchar *ptr)
Unmaps the memory address.
virtual ~QAbstractFileEngine ()
Destroys the QAbstractFileEngine.
Public Variables
bool filePathIsTemplate
Additional Inherited Members
Public Types inherited from QAbstractFileEngine
enum Extension { AtEndExtension, FastReadLineExtension, MapExtension, UnMapExtension }
This enum describes the types of extensions that the file engine can support.
enum FileFlag {
ReadOwnerPerm = 0x4000, WriteOwnerPerm = 0x2000, ExeOwnerPerm = 0x1000, ReadUserPerm = 0x0400,
WriteUserPerm = 0x0200, ExeUserPerm = 0x0100, ReadGroupPerm = 0x0040, WriteGroupPerm = 0x0020,
ExeGroupPerm = 0x0010, ReadOtherPerm = 0x0004, WriteOtherPerm = 0x0002, ExeOtherPerm = 0x0001,
LinkType = 0x10000, FileType = 0x20000, DirectoryType = 0x40000, BundleType = 0x80000,
HiddenFlag = 0x0100000, LocalDiskFlag = 0x0200000, ExistsFlag = 0x0400000, RootFlag = 0x0800000,
Refresh = 0x1000000, PermsMask = 0x0000FFFF, TypesMask = 0x000F0000, FlagsMask = 0x0FF00000,
FileInfoAll = FlagsMask | PermsMask | TypesMask
}
The permissions and types of a file, suitable for OR'ing together.
enum FileName {
DefaultName, BaseName, PathName, AbsoluteName,
AbsolutePathName, LinkName, CanonicalName, CanonicalPathName,
BundleName, NFileNames = 9
}
These values are used to request a file name in a particular format.
enum FileOwner { OwnerUser, OwnerGroup }
enum FileTime { CreationTime, ModificationTime, AccessTime }
These are used by the fileTime() function.
typedef QAbstractFileEngineIterator Iterator
Static Public Functions inherited from QFSFileEngine
static QString currentPath (const QString &path=QString())
For Unix, returns the current working directory for the file engine.
static QFileInfoList drives ()
For Windows, returns the list of drives in the file system as a list of QFileInfo objects.
static QString homePath ()
Returns the home path of the current user.
static QString rootPath ()
Returns the root path.
static bool setCurrentPath (const QString &path)
Sets the current path (e.
static QString tempPath ()
Returns the temporary path (i.
Static Public Functions inherited from QAbstractFileEngine
static QAbstractFileEngine * create (const QString &fileName)
Creates and returns a QAbstractFileEngine suitable for processing fileName.
Protected Functions inherited from QFSFileEngine
QFSFileEngine (QFSFileEnginePrivate &dd)
Protected Functions inherited from QAbstractFileEngine
QAbstractFileEngine ()
Constructs a new QAbstractFileEngine that does not refer to any file or directory.
QAbstractFileEngine (QAbstractFileEnginePrivate &)
Constructs a QAbstractFileEngine.
void setError (QFile::FileError error, const QString &str)
Sets the error type to error, and the error string to errorString.
Protected Variables inherited from QAbstractFileEngine
QScopedPointer< QAbstractFileEnginePrivate > d_ptr
Related Functions inherited from QAbstractFileEngine
Iterator
Synonym for QAbstractFileEngineIterator.
Detailed Description
Definition at line 251 of file qtemporaryfile.cpp.
Constructors and Destructors
QTemporaryFileEngine()
QTemporaryFileEngine::QTemporaryFileEngine (const QString & file, bool fileIsTemplate = true) inline
Definition at line 255 of file qtemporaryfile.cpp.
         : QFSFileEngine(), filePathIsTemplate(fileIsTemplate)
     {
         Q_D(QFSFileEngine);
         d->fileEntry = QFileSystemEntry(file);
         if (!filePathIsTemplate)
             QFSFileEngine::setFileName(file);
     }
~QTemporaryFileEngine()
QTemporaryFileEngine::~QTemporaryFileEngine ()
Definition at line 279 of file qtemporaryfile.cpp.
Referenced by QTemporaryFileEngine().
 {
     QFSFileEngine::close();
 }
Functions
close()
bool QTemporaryFileEngine::close () virtual
Reimplemented Function
Reimplemented from QFSFileEngine.
Definition at line 428 of file qtemporaryfile.cpp.
Referenced by QTemporaryFileEngine().
 {
     // Don't close the file, just seek to the front.
     seek(0);
     setError(QFile::UnspecifiedError, QString());
     return true;
 }
isReallyOpen()
bool QTemporaryFileEngine::isReallyOpen ()
Definition at line 284 of file qtemporaryfile.cpp.
Referenced by open(), and QTemporaryFileEngine().
 {
     Q_D(QFSFileEngine);
     if (!((0 == d->fh) && (-1 == d->fd)
 #if defined (Q_OS_SYMBIAN)
                 && (0 == d->symbianFile.SubSessionHandle())
 #endif
 #if defined Q_OS_WIN
                 && (INVALID_HANDLE_VALUE == d->fileHandle)
 #endif
             ))
         return true;
     return false;
 }
open()
bool QTemporaryFileEngine::open (QIODevice::OpenMode openMode) virtual
Reimplemented Function
Reimplemented from QFSFileEngine.
Definition at line 316 of file qtemporaryfile.cpp.
Referenced by QTemporaryFileEngine().
 {
     Q_D(QFSFileEngine);
     Q_ASSERT(!isReallyOpen());
     openMode |= QIODevice::ReadWrite;
     if (!filePathIsTemplate)
         return QFSFileEngine::open(openMode);
     QString qfilename = d->fileEntry.filePath();
     // Ensure there is a placeholder mask
     uint phPos = qfilename.length();
     uint phLength = 0;
     while (phPos != 0) {
         --phPos;
         if (qfilename[phPos] == QLatin1Char('X')) {
             ++phLength;
             continue;
         }
         if (phLength >= 6
                 || qfilename[phPos] == QLatin1Char('/')) {
             ++phPos;
             break;
         }
         // start over
         phLength = 0;
     }
     if (phLength < 6)
         qfilename.append(QLatin1String(".XXXXXX"));
     // "Nativify" :-)
     QFileSystemEntry::NativePath filename = QFileSystemEngine::absoluteName(
             QFileSystemEntry(qfilename, QFileSystemEntry::FromInternalPath()))
         .nativeFilePath();
     // Find mask in native path
     phPos = filename.length();
     phLength = 0;
     while (phPos != 0) {
         --phPos;
         if (filename[phPos] == Latin1Char('X')) {
             ++phLength;
             continue;
         }
         if (phLength >= 6) {
             ++phPos;
             break;
         }
         // start over
         phLength = 0;
     }
     Q_ASSERT(phLength >= 6);
     QSystemError error;
 #if defined(Q_OS_WIN)
     NativeFileHandle &file = d->fileHandle;
 #elif defined(Q_OS_SYMBIAN)
     NativeFileHandle &file = d->symbianFile;
 #else // POSIX
     NativeFileHandle &file = d->fd;
 #endif
     if (!createFileFromTemplate(file, filename, phPos, phLength, error)) {
         setError(QFile::OpenError, error.toString());
         return false;
     }
     d->fileEntry = QFileSystemEntry(filename, QFileSystemEntry::FromNativePath());
 #if !defined(Q_OS_WIN)
     d->closeFileHandle = true;
 #endif
     filePathIsTemplate = false;
     d->openMode = openMode;
     d->lastFlushFailed = false;
     d->tried_stat = 0;
     return true;
 }
remove()
bool QTemporaryFileEngine::remove () virtual
Reimplemented Function
Reimplemented from QFSFileEngine.
Definition at line 409 of file qtemporaryfile.cpp.
 {
     Q_D(QFSFileEngine);
     // Since the QTemporaryFileEngine::close() does not really close the file,
     // we must explicitly call QFSFileEngine::close() before we remove it.
     QFSFileEngine::close();
     if (QFSFileEngine::remove()) {
         d->fileEntry.clear();
         return true;
     }
     return false;
 }
rename()
bool QTemporaryFileEngine::rename (const QString & newName) virtual
Reimplemented Function
Reimplemented from QFSFileEngine.
Definition at line 422 of file qtemporaryfile.cpp.
Referenced by QTemporaryFileEngine().
 {
     QFSFileEngine::close();
     return QFSFileEngine::rename(newName);
 }
setFileName()
void QTemporaryFileEngine::setFileName (const QString & file) virtual
Reimplemented Function
Reimplemented from QFSFileEngine.
Definition at line 302 of file qtemporaryfile.cpp.
Referenced by QTemporaryFileEngine().
 {
     // Really close the file, so we don't leak
     QFSFileEngine::close();
     QFSFileEngine::setFileName(file);
 }
setFileTemplate()
void QTemporaryFileEngine::setFileTemplate (const QString & fileTemplate)
Definition at line 309 of file qtemporaryfile.cpp.
Referenced by QTemporaryFileEngine().
 {
     Q_D(QFSFileEngine);
     if (filePathIsTemplate)
         d->fileEntry = QFileSystemEntry(fileTemplate);
 }
Properties
filePathIsTemplate
bool QTemporaryFileEngine::filePathIsTemplate
Definition at line 276 of file qtemporaryfile.cpp.
Referenced by open(), QTemporaryFileEngine(), and setFileTemplate().
The documentation for this class was generated from the following file:
/src/corelib/io/qtemporaryfile.cpp