Qt 4.8: QResourceFileEngine Class Reference
QResourceFileEngine Class Reference
#include <qresource_p.h>
Public Functions
virtual bool atEnd () const
virtual Iterator * beginEntryList (QDir::Filters filters, const QStringList &filterNames)
virtual bool caseSensitive () const
Should return true if the underlying file system is case-sensitive; otherwise return false.
virtual bool close ()
Closes the file, returning true if successful; otherwise returns false.
virtual bool copy (const QString &newName)
Copies the contents of this file to a file with the name newName.
virtual Iterator * endEntryList ()
virtual QStringList entryList (QDir::Filters filters, const QStringList &filterNames) const
Requests that a list of all the files matching the filters list based on the filterNames in the file engine's directory are returned.
bool extension (Extension extension, const ExtensionOption *option=0, ExtensionReturn *output=0)
This virtual function can be reimplemented in a QAbstractFileEngine subclass to provide support for extensions.
virtual FileFlags fileFlags (FileFlags type) const
This function should return the set of OR'd flags that are true for the file engine's file, and that are in the type's OR'd members.
virtual QString fileName (QAbstractFileEngine::FileName file) const
Return the file engine's current file name in the format specified by file.
virtual QDateTime fileTime (FileTime time) const
If time is CreationTime, return when the file was created.
virtual bool flush ()
Flushes the open file, returning true if successful; otherwise returns false.
virtual bool isRelativePath () const
Return true if the file referred to by this file engine has a relative path; otherwise return false.
virtual bool isSequential () const
Returns true if the file is a sequential access device; returns false if the file is a direct access device.
virtual bool link (const QString &newName)
Creates a link from the file currently specified by fileName() to newName.
virtual bool mkdir (const QString &dirName, bool createParentDirectories) const
Requests that the directory dirName be created.
virtual bool open (QIODevice::OpenMode flags)
Opens the file in the specified mode.
virtual QString owner (FileOwner) const
If owner is OwnerUser return the name of the user who owns the file.
virtual uint ownerId (FileOwner) const
If owner is OwnerUser return the ID of the user who owns the file.
virtual qint64 pos () const
Returns the current file position.
QResourceFileEngine (const QString &path)
virtual qint64 read (char *data, qint64 maxlen)
Reads a number of characters from the file into data.
virtual bool remove ()
Requests that the file is deleted from the file system.
virtual bool rename (const QString &newName)
Requests that the file be renamed to newName in the file system.
virtual bool rmdir (const QString &dirName, bool recurseParentDirectories) const
Requests that the directory dirName is deleted from the file system.
virtual bool seek (qint64)
Sets the file position to the given offset.
virtual void setFileName (const QString &file)
Sets the file engine's file name to file.
virtual bool setPermissions (uint perms)
Requests that the file's permissions be set to perms.
virtual bool setSize (qint64 size)
Requests that the file be set to size size.
virtual qint64 size () const
Returns the size of the file.
bool supportsExtension (Extension extension) const
This virtual function returns true if the file engine supports extension; otherwise, false is returned.
virtual qint64 write (const char *data, qint64 len)
Writes len bytes from data to the file.
~QResourceFileEngine ()
Public Functions inherited from QAbstractFileEngine
bool atEnd () const
Returns true if the current position is at the end of the file; otherwise, returns false.
QFile::FileError error () const
Returns the QFile::FileError that resulted from the last failed operation.
QString errorString () const
Returns the human-readable message appropriate to the current error reported by error().
virtual int handle () const
Returns the native file handle for this file engine.
uchar * map (qint64 offset, qint64 size, QFile::MemoryMapFlags flags)
Maps size bytes of the file into memory starting at offset.
virtual qint64 readLine (char *data, qint64 maxlen)
This function reads one line, terminated by a '
' character, from the file info data.
bool unmap (uchar *ptr)
Unmaps the memory address.
virtual ~QAbstractFileEngine ()
Destroys the QAbstractFileEngine.
Additional Inherited Members
Public Types inherited from QAbstractFileEngine
enum Extension { AtEndExtension, FastReadLineExtension, MapExtension, UnMapExtension }
This enum describes the types of extensions that the file engine can support.
enum FileFlag {
ReadOwnerPerm = 0x4000, WriteOwnerPerm = 0x2000, ExeOwnerPerm = 0x1000, ReadUserPerm = 0x0400,
WriteUserPerm = 0x0200, ExeUserPerm = 0x0100, ReadGroupPerm = 0x0040, WriteGroupPerm = 0x0020,
ExeGroupPerm = 0x0010, ReadOtherPerm = 0x0004, WriteOtherPerm = 0x0002, ExeOtherPerm = 0x0001,
LinkType = 0x10000, FileType = 0x20000, DirectoryType = 0x40000, BundleType = 0x80000,
HiddenFlag = 0x0100000, LocalDiskFlag = 0x0200000, ExistsFlag = 0x0400000, RootFlag = 0x0800000,
Refresh = 0x1000000, PermsMask = 0x0000FFFF, TypesMask = 0x000F0000, FlagsMask = 0x0FF00000,
FileInfoAll = FlagsMask | PermsMask | TypesMask
}
The permissions and types of a file, suitable for OR'ing together.
enum FileName {
DefaultName, BaseName, PathName, AbsoluteName,
AbsolutePathName, LinkName, CanonicalName, CanonicalPathName,
BundleName, NFileNames = 9
}
These values are used to request a file name in a particular format.
enum FileOwner { OwnerUser, OwnerGroup }
enum FileTime { CreationTime, ModificationTime, AccessTime }
These are used by the fileTime() function.
typedef QAbstractFileEngineIterator Iterator
Static Public Functions inherited from QAbstractFileEngine
static QAbstractFileEngine * create (const QString &fileName)
Creates and returns a QAbstractFileEngine suitable for processing fileName.
Protected Functions inherited from QAbstractFileEngine
QAbstractFileEngine ()
Constructs a new QAbstractFileEngine that does not refer to any file or directory.
QAbstractFileEngine (QAbstractFileEnginePrivate &)
Constructs a QAbstractFileEngine.
void setError (QFile::FileError error, const QString &str)
Sets the error type to error, and the error string to errorString.
Protected Variables inherited from QAbstractFileEngine
QScopedPointer< QAbstractFileEnginePrivate > d_ptr
Related Functions inherited from QAbstractFileEngine
Iterator
Synonym for QAbstractFileEngineIterator.
Detailed Description
Definition at line 61 of file qresource_p.h.
Constructors and Destructors
QResourceFileEngine()
QResourceFileEngine::QResourceFileEngine (const QString & path) explicit
Definition at line 1246 of file qresource.cpp.
                                                             :
     QAbstractFileEngine(*new QResourceFileEnginePrivate)
 {
     Q_D(QResourceFileEngine);
     d->resource.setFileName(file);
     if(d->resource.isCompressed() && d->resource.size()) {
 #ifndef QT_NO_COMPRESS
         d->uncompressed = qUncompress(d->resource.data(), d->resource.size());
 #else
         Q_ASSERT(!"QResourceFileEngine::open: Qt built without support for compression");
 #endif
     }
 }
~QResourceFileEngine()
QResourceFileEngine::~QResourceFileEngine ()
Definition at line 1260 of file qresource.cpp.
 {
 }
Functions
atEnd()
bool QResourceFileEngine::atEnd () const virtual
Definition at line 1353 of file qresource.cpp.
 {
     Q_D(const QResourceFileEngine);
     if(!d->resource.isValid())
         return true;
     return d->offset == size();
 }
beginEntryList()
QAbstractFileEngine::Iterator * QResourceFileEngine::beginEntryList (QDir::Filters filters, const QStringList & filterNames) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractFileEngine.
Definition at line 1459 of file qresource.cpp.
 {
     return new QResourceFileEngineIterator(filters, filterNames);
 }
caseSensitive()
bool QResourceFileEngine::caseSensitive () const virtual
Should return true if the underlying file system is case-sensitive; otherwise return false.
This virtual function must be reimplemented by all subclasses.
Reimplemented from QAbstractFileEngine.
Definition at line 1241 of file qresource.cpp.
 {
     return true;
 }
close()
bool QResourceFileEngine::close () virtual
Closes the file, returning true if successful; otherwise returns false.
The default implementation always returns false.
Reimplemented from QAbstractFileEngine.
Definition at line 1284 of file qresource.cpp.
 {
     Q_D(QResourceFileEngine);
     d->offset = 0;
     d->uncompressed.clear();
     return true;
 }
copy()
bool QResourceFileEngine::copy (const QString & newName) virtual
Copies the contents of this file to a file with the name newName.
Returns true on success; otherwise, false is returned.
Reimplemented from QAbstractFileEngine.
Definition at line 1322 of file qresource.cpp.
 {
     return false;
 }
endEntryList()
QAbstractFileEngine::Iterator * QResourceFileEngine::endEntryList () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractFileEngine.
Definition at line 1468 of file qresource.cpp.
 {
     return 0;
 }
entryList()
QStringList QResourceFileEngine::entryList (QDir::Filters filters, const QStringList & filterNames) const virtual
Requests that a list of all the files matching the filters list based on the filterNames in the file engine's directory are returned.
Should return an empty list if the file engine refers to a file rather than a directory, or if the directory is unreadable or does not exist or if nothing matches the specifications.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented from QAbstractFileEngine.
Definition at line 1236 of file qresource.cpp.
 {
     return QAbstractFileEngine::entryList(filters, filterNames);
 }
extension()
bool QResourceFileEngine::extension (Extension extension, const ExtensionOption * option = 0, ExtensionReturn * output = 0) virtual
This virtual function can be reimplemented in a QAbstractFileEngine subclass to provide support for extensions.
Since
4.3
The option argument is provided as input to the extension, and this function can store output results in output.
The behavior of this function is determined by extension; see the Extension documentation for details.
You can call supportsExtension() to check if an extension is supported by the file engine.
By default, no extensions are supported, and this function returns false.
See also
supportsExtension(), Extension
Reimplemented from QAbstractFileEngine.
Definition at line 1473 of file qresource.cpp.
 {
     Q_D(QResourceFileEngine);
     if (extension == MapExtension) {
         const MapExtensionOption *options = (MapExtensionOption*)(option);
         MapExtensionReturn *returnValue = static_cast<MapExtensionReturn*>(output);
         returnValue->address = d->map(options->offset, options->size, options->flags);
         return (returnValue->address != 0);
     }
     if (extension == UnMapExtension) {
         UnMapExtensionOption *options = (UnMapExtensionOption*)option;
         return d->unmap(options->address);
     }
     return false;
 }
fileFlags()
QAbstractFileEngine::FileFlags QResourceFileEngine::fileFlags (FileFlags type) const virtual
This function should return the set of OR'd flags that are true for the file engine's file, and that are in the type's OR'd members.
In your reimplementation you can use the type argument as an optimization hint and only return the OR'd set of members that are true and that match those in type; in other words you can ignore any members not mentioned in type, thus avoiding some potentially expensive lookups or system calls.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented from QAbstractFileEngine.
Definition at line 1378 of file qresource.cpp.
 {
     Q_D(const QResourceFileEngine);
     QAbstractFileEngine::FileFlags ret = 0;
     if(!d->resource.isValid())
         return ret;
     if(type & PermsMask)
         ret |= QAbstractFileEngine::FileFlags(ReadOwnerPerm|ReadUserPerm|ReadGroupPerm|ReadOtherPerm);
     if(type & TypesMask) {
         if(d->resource.isDir())
             ret |= DirectoryType;
         else
             ret |= FileType;
     }
     if(type & FlagsMask) {
         ret |= ExistsFlag;
         if(d->resource.absoluteFilePath() == QLatin1String(":/"))
             ret |= RootFlag;
     }
     return ret;
 }
fileName()
QString QResourceFileEngine::fileName (QAbstractFileEngine::FileName file) const virtual
Return the file engine's current file name in the format specified by file.
If you don't handle some FileName possibilities, return the file name set in setFileName() when an unhandled format is requested.
This virtual function must be reimplemented by all subclasses.
See also
setFileName(), FileName
Reimplemented from QAbstractFileEngine.
Definition at line 1406 of file qresource.cpp.
 {
     Q_D(const QResourceFileEngine);
     if(file == BaseName) {
     int slash = d->resource.fileName().lastIndexOf(QLatin1Char('/'));
     if (slash == -1)
         return d->resource.fileName();
     return d->resource.fileName().mid(slash + 1);
     } else if(file == PathName || file == AbsolutePathName) {
         const QString path = (file == AbsolutePathName) ? d->resource.absoluteFilePath() : d->resource.fileName();
     const int slash = path.lastIndexOf(QLatin1Char('/'));
         if (slash == -1)
             return QLatin1String(":");
         else if (slash <= 1)
             return QLatin1String(":/");
         return path.left(slash);
     } else if(file == CanonicalName || file == CanonicalPathName) {
         const QString absoluteFilePath = d->resource.absoluteFilePath();
         if(file == CanonicalPathName) {
             const int slash = absoluteFilePath.lastIndexOf(QLatin1Char('/'));
             if (slash != -1)
                 return absoluteFilePath.left(slash);
         }
         return absoluteFilePath;
     }
     return d->resource.fileName();
 }
fileTime()
QDateTime QResourceFileEngine::fileTime (FileTime time) const virtual
If time is CreationTime, return when the file was created.
If time is ModificationTime, return when the file was most recently modified. If time is AccessTime, return when the file was most recently accessed (e.g. read or written). If the time cannot be determined return QDateTime() (an invalid date time).
This virtual function must be reimplemented by all subclasses.
See also
setFileName(), QDateTime, QDateTime::isValid(), FileTime
Reimplemented from QAbstractFileEngine.
Definition at line 1451 of file qresource.cpp.
 {
     return QDateTime();
 }
flush()
bool QResourceFileEngine::flush () virtual
Flushes the open file, returning true if successful; otherwise returns false.
The default implementation always returns false.
Reimplemented from QAbstractFileEngine.
Definition at line 1292 of file qresource.cpp.
 {
     return true;
 }
isRelativePath()
bool QResourceFileEngine::isRelativePath () const virtual
Return true if the file referred to by this file engine has a relative path; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented from QAbstractFileEngine.
Definition at line 1435 of file qresource.cpp.
 {
     return false;
 }
isSequential()
bool QResourceFileEngine::isSequential () const virtual
Returns true if the file is a sequential access device; returns false if the file is a direct access device.
Operations involving size() and seek(int) are not valid on sequential devices.
Reimplemented from QAbstractFileEngine.
Definition at line 1373 of file qresource.cpp.
 {
     return false;
 }
link()
bool QResourceFileEngine::link (const QString & newName) virtual
Creates a link from the file currently specified by fileName() to newName.
What a link is depends on the underlying filesystem (be it a shortcut on Windows or a symbolic link on Unix). Returns true if successful; otherwise returns false.
Reimplemented from QAbstractFileEngine.
Definition at line 1332 of file qresource.cpp.
 {
     return false;
 }
mkdir()
bool QResourceFileEngine::mkdir (const QString & dirName, bool createParentDirectories) const virtual
Requests that the directory dirName be created.
If createParentDirectories is true, then any sub-directories in dirName that don't exist must be created. If createParentDirectories is false then any sub-directories in dirName must already exist for the function to succeed. If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName() rmdir() isRelativePath()
Reimplemented from QAbstractFileEngine.
Definition at line 1221 of file qresource.cpp.
 {
     return false;
 }
open()
bool QResourceFileEngine::open (QIODevice::OpenMode mode) virtual
Opens the file in the specified mode.
Returns true if the file was successfully opened; otherwise returns false.
The mode is an OR combination of QIODevice::OpenMode and QIODevice::HandlingMode values.
Reimplemented from QAbstractFileEngine.
Definition at line 1270 of file qresource.cpp.
 {
     Q_D(QResourceFileEngine);
     if (d->resource.fileName().isEmpty()) {
         qWarning("QResourceFileEngine::open: Missing file name");
         return false;
     }
     if(flags & QIODevice::WriteOnly)
         return false;
     if(!d->resource.isValid())
        return false;
     return true;
 }
owner()
QString QResourceFileEngine::owner (FileOwner owner) const virtual
If owner is OwnerUser return the name of the user who owns the file.
If owner is OwnerGroup return the name of the group that own the file. If you can't determine the owner return QString().
This virtual function must be reimplemented by all subclasses.
See also
ownerId() setFileName(), FileOwner
Reimplemented from QAbstractFileEngine.
Definition at line 1446 of file qresource.cpp.
 {
     return QString();
 }
ownerId()
uint QResourceFileEngine::ownerId (FileOwner owner) const virtual
If owner is OwnerUser return the ID of the user who owns the file.
If owner is OwnerGroup return the ID of the group that own the file. If you can't determine the owner return -2.
This virtual function must be reimplemented by all subclasses.
See also
owner() setFileName(), FileOwner
Reimplemented from QAbstractFileEngine.
Definition at line 1440 of file qresource.cpp.
 {
     static const uint nobodyID = (uint) -2;
     return nobodyID;
 }
pos()
qint64 QResourceFileEngine::pos () const virtual
Returns the current file position.
This is the position of the data read/write head of the file.
Reimplemented from QAbstractFileEngine.
Definition at line 1347 of file qresource.cpp.
Referenced by seek().
 {
     Q_D(const QResourceFileEngine);
     return d->offset;
 }
read()
qint64 QResourceFileEngine::read (char * data, qint64 maxlen) virtual
Reads a number of characters from the file into data.
At most maxlen characters will be read.
Returns -1 if a fatal error occurs, or 0 if there are no bytes to read.
Reimplemented from QAbstractFileEngine.
Definition at line 1297 of file qresource.cpp.
 {
     Q_D(QResourceFileEngine);
     if(len > size()-d->offset)
         len = size()-d->offset;
     if(len <= 0)
         return 0;
     if(d->resource.isCompressed())
         memcpy(data, d->uncompressed.constData()+d->offset, len);
     else
         memcpy(data, d->resource.data()+d->offset, len);
     d->offset += len;
     return len;
 }
remove()
bool QResourceFileEngine::remove () virtual
Requests that the file is deleted from the file system.
If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName() rmdir()
Reimplemented from QAbstractFileEngine.
Definition at line 1317 of file qresource.cpp.
 {
     return false;
 }
rename()
bool QResourceFileEngine::rename (const QString & newName) virtual
Requests that the file be renamed to newName in the file system.
If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName()
Reimplemented from QAbstractFileEngine.
Definition at line 1327 of file qresource.cpp.
 {
     return false;
 }
rmdir()
bool QResourceFileEngine::rmdir (const QString & dirName, bool recurseParentDirectories) const virtual
Requests that the directory dirName is deleted from the file system.
When recurseParentDirectories is true, then any empty parent-directories in dirName must also be deleted. If recurseParentDirectories is false, only the dirName leaf-node should be deleted. In most file systems a directory cannot be deleted using this function if it is non-empty. If the operation succeeds return true; otherwise return false.
This virtual function must be reimplemented by all subclasses.
See also
setFileName() remove() mkdir() isRelativePath()
Reimplemented from QAbstractFileEngine.
Definition at line 1226 of file qresource.cpp.
 {
     return false;
 }
seek()
bool QResourceFileEngine::seek (qint64 offset) virtual
Sets the file position to the given offset.
Returns true if the position was successfully set; otherwise returns false.
The offset is from the beginning of the file, unless the file is sequential.
See also
isSequential()
Reimplemented from QAbstractFileEngine.
Definition at line 1361 of file qresource.cpp.
 {
     Q_D(QResourceFileEngine);
     if(!d->resource.isValid())
         return false;
     if(d->offset > size())
         return false;
     d->offset = pos;
     return true;
 }
setFileName()
void QResourceFileEngine::setFileName (const QString & file) virtual
Sets the file engine's file name to file.
This file name is the file that the rest of the virtual functions will operate on.
This virtual function must be reimplemented by all subclasses.
See also
rename()
Reimplemented from QAbstractFileEngine.
Definition at line 1264 of file qresource.cpp.
 {
     Q_D(QResourceFileEngine);
     d->resource.setFileName(file);
 }
setPermissions()
bool QResourceFileEngine::setPermissions (uint perms) virtual
Requests that the file's permissions be set to perms.
The argument perms will be set to the OR-ed together combination of QAbstractFileEngine::FileInfo, with only the QAbstractFileEngine::PermsMask being honored. If the operations succceeds return true; otherwise return false;
This virtual function must be reimplemented by all subclasses.
See also
size()
Reimplemented from QAbstractFileEngine.
Definition at line 1401 of file qresource.cpp.
 {
     return false;
 }
setSize()
bool QResourceFileEngine::setSize (qint64 size) virtual
Requests that the file be set to size size.
If size is larger than the current file then it is filled with 0's, if smaller it is simply truncated. If the operations succceeds return true; otherwise return false;
This virtual function must be reimplemented by all subclasses.
See also
size()
Reimplemented from QAbstractFileEngine.
Definition at line 1231 of file qresource.cpp.
 {
     return false;
 }
size()
qint64 QResourceFileEngine::size () const virtual
Returns the size of the file.
Reimplemented from QAbstractFileEngine.
Definition at line 1337 of file qresource.cpp.
Referenced by atEnd(), read(), and seek().
 {
     Q_D(const QResourceFileEngine);
     if(!d->resource.isValid())
         return 0;
     if(d->resource.isCompressed())
         return d->uncompressed.size();
     return d->resource.size();
 }
supportsExtension()
bool QResourceFileEngine::supportsExtension (Extension extension) const virtual
This virtual function returns true if the file engine supports extension; otherwise, false is returned.
Since
4.3
By default, no extensions are supported.
See also
extension()
Reimplemented from QAbstractFileEngine.
Definition at line 1489 of file qresource.cpp.
 {
     return (extension == UnMapExtension || extension == MapExtension);
 }
write()
qint64 QResourceFileEngine::write (const char * data, qint64 len) virtual
Writes len bytes from data to the file.
Returns the number of characters written on success; otherwise returns -1.
Reimplemented from QAbstractFileEngine.
Definition at line 1312 of file qresource.cpp.
 {
     return -1;
 }
The documentation for this class was generated from the following files:
/src/corelib/io/qresource_p.h
/src/corelib/io/qresource.cpp