Qt 4.8: QWindowsAccessible Class Reference
QWindowsAccessible Class Reference
Public Functions
HRESULT STDMETHODCALLTYPE accDoDefaultAction (VARIANT varID)
HRESULT STDMETHODCALLTYPE accHitTest (long xLeft, long yTop, VARIANT *pvarID)
HRESULT STDMETHODCALLTYPE accLocation (long *pxLeft, long *pyTop, long *pcxWidth, long *pcyHeight, VARIANT varID)
HRESULT STDMETHODCALLTYPE accNavigate (long navDir, VARIANT varStart, VARIANT *pvarEnd)
HRESULT STDMETHODCALLTYPE accSelect (long flagsSelect, VARIANT varID)
ULONG STDMETHODCALLTYPE AddRef ()
HRESULT STDMETHODCALLTYPE ContextSensitiveHelp (BOOL fEnterMode)
HRESULT STDMETHODCALLTYPE get_accChild (VARIANT varChildID, IDispatch **ppdispChild)
HRESULT STDMETHODCALLTYPE get_accChildCount (long *pcountChildren)
HRESULT STDMETHODCALLTYPE get_accDefaultAction (VARIANT varID, BSTR *pszDefaultAction)
HRESULT STDMETHODCALLTYPE get_accDescription (VARIANT varID, BSTR *pszDescription)
HRESULT STDMETHODCALLTYPE get_accFocus (VARIANT *pvarID)
HRESULT STDMETHODCALLTYPE get_accHelp (VARIANT varID, BSTR *pszHelp)
HRESULT STDMETHODCALLTYPE get_accHelpTopic (BSTR *pszHelpFile, VARIANT varChild, long *pidTopic)
HRESULT STDMETHODCALLTYPE get_accKeyboardShortcut (VARIANT varID, BSTR *pszKeyboardShortcut)
HRESULT STDMETHODCALLTYPE get_accName (VARIANT varID, BSTR *pszName)
HRESULT STDMETHODCALLTYPE get_accParent (IDispatch **ppdispParent)
HRESULT STDMETHODCALLTYPE get_accRole (VARIANT varID, VARIANT *pvarRole)
HRESULT STDMETHODCALLTYPE get_accSelection (VARIANT *pvarChildren)
HRESULT STDMETHODCALLTYPE get_accState (VARIANT varID, VARIANT *pvarState)
HRESULT STDMETHODCALLTYPE get_accValue (VARIANT varID, BSTR *pszValue)
HRESULT STDMETHODCALLTYPE GetIDsOfNames (const _GUID &, wchar_t **, unsigned int, unsigned long, long *)
HRESULT STDMETHODCALLTYPE GetTypeInfo (unsigned int, unsigned long, ITypeInfo **)
HRESULT STDMETHODCALLTYPE GetTypeInfoCount (unsigned int *)
HRESULT STDMETHODCALLTYPE GetWindow (HWND *phwnd)
HRESULT STDMETHODCALLTYPE Invoke (long, const _GUID &, unsigned long, unsigned short, tagDISPPARAMS *, tagVARIANT *, tagEXCEPINFO *, unsigned int *)
HRESULT STDMETHODCALLTYPE put_accName (VARIANT varChild, BSTR szName)
HRESULT STDMETHODCALLTYPE put_accValue (VARIANT varChild, BSTR szValue)
HRESULT STDMETHODCALLTYPE QueryInterface (REFIID, LPVOID *)
QWindowsAccessible (QAccessibleInterface *a)
ULONG STDMETHODCALLTYPE Release ()
virtual ~QWindowsAccessible ()
Properties
QAccessibleInterface * accessible
ULONG ref
Additional Inherited Members
Private Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Private Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 648 of file qaccessible_win.cpp.
Constructors and Destructors
QWindowsAccessible()
QWindowsAccessible::QWindowsAccessible (QAccessibleInterface * a) inline
Definition at line 651 of file qaccessible_win.cpp.
         : ref(0), accessible(a)
     {
     }
~QWindowsAccessible()
virtual QWindowsAccessible::~QWindowsAccessible () inline virtual
Definition at line 656 of file qaccessible_win.cpp.
     {
         delete accessible;
     }
Functions
accDoDefaultAction()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::accDoDefaultAction (VARIANT varID)
Definition at line 1192 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     const bool res = elem.iface ? elem.iface->doAction(DefaultAction, elem.entry, QVariantList()) : false;
     return res ? S_OK : S_FALSE;
 }
accHitTest()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::accHitTest (long xLeft, long yTop, VARIANT * pvarID)
Definition at line 996 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     int control = accessible->childAt(xLeft, yTop);
     if (control == -1) {
         (*pvarID).vt = VT_EMPTY;
         return S_FALSE;
     }
     QAccessibleInterface *acc = 0;
     if (control)
         accessible->navigate(Child, control, &acc);
     if (!acc) {
         (*pvarID).vt = VT_I4;
         (*pvarID).lVal = control;
         return S_OK;
     }
     QWindowsAccessible* wacc = new QWindowsAccessible(acc);
     IDispatch *iface = 0;
     wacc->QueryInterface(IID_IDispatch, (void**)&iface);
     if (iface) {
         (*pvarID).vt = VT_DISPATCH;
         (*pvarID).pdispVal = iface;
         return S_OK;
     } else {
         delete wacc;
     }
     (*pvarID).vt = VT_EMPTY;
     return S_FALSE;
 }
accLocation()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::accLocation (long * pxLeft, long * pyTop, long * pcxWidth, long * pcyHeight, VARIANT varID)
Definition at line 1031 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QRect rect = elem.iface ? elem.iface->rect(elem.entry) : QRect();
     if (rect.isValid()) {
         *pxLeft = rect.x();
         *pyTop = rect.y();
         *pcxWidth = rect.width();
         *pcyHeight = rect.height();
     } else {
         *pxLeft = 0;
         *pyTop = 0;
         *pcxWidth = 0;
         *pcyHeight = 0;
     }
     return S_OK;
 }
accNavigate()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::accNavigate (long navDir, VARIANT varStart, VARIANT * pvarEnd)
Definition at line 1053 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     QAccessibleInterface *acc = 0;
     int control = -1;
     switch(navDir) {
     case NAVDIR_FIRSTCHILD:
         control = accessible->navigate(Child, 1, &acc);
         break;
     case NAVDIR_LASTCHILD:
         control = accessible->navigate(Child, accessible->childCount(), &acc);
         break;
     case NAVDIR_NEXT:
     case NAVDIR_PREVIOUS:
         if (!varStart.lVal){
             QAccessibleInterface *parent = 0;
             accessible->navigate(Ancestor, 1, &parent);
             if (parent) {
                 int index = parent->indexOfChild(accessible);
                 index += (navDir == NAVDIR_NEXT) ? 1 : -1;
                 if (index > 0 && index <= parent->childCount())
                     control = parent->navigate(Child, index, &acc);
                 delete parent;
             }
         } else {
             int index = varStart.lVal;
             index += (navDir == NAVDIR_NEXT) ? 1 : -1;
             if (index > 0 && index <= accessible->childCount())
                 control = accessible->navigate(Child, index, &acc);
         }
         break;
     case NAVDIR_UP:
         control = accessible->navigate(Up, varStart.lVal, &acc);
         break;
     case NAVDIR_DOWN:
         control = accessible->navigate(Down, varStart.lVal, &acc);
         break;
     case NAVDIR_LEFT:
         control = accessible->navigate(Left, varStart.lVal, &acc);
         break;
     case NAVDIR_RIGHT:
         control = accessible->navigate(Right, varStart.lVal, &acc);
         break;
     default:
         break;
     }
     if (control == -1) {
         (*pvarEnd).vt = VT_EMPTY;
         return S_FALSE;
     }
     if (!acc) {
         (*pvarEnd).vt = VT_I4;
         (*pvarEnd).lVal = control;
         return S_OK;
     }
     QWindowsAccessible* wacc = new QWindowsAccessible(acc);
     IDispatch *iface = 0;
     wacc->QueryInterface(IID_IDispatch, (void**)&iface);
     if (iface) {
         (*pvarEnd).vt = VT_DISPATCH;
         (*pvarEnd).pdispVal = iface;
         return S_OK;
     } else {
         delete wacc;
     }
     (*pvarEnd).vt = VT_EMPTY;
     return S_FALSE;
 }
accSelect()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::accSelect (long flagsSelect, VARIANT varID)
Definition at line 1353 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     bool res = false;
     AccessibleElement elem(varID.lVal, accessible);
     QAccessibleInterface *acc = elem.iface;
     if (acc) {
         const int entry = elem.entry;
         if (flagsSelect & SELFLAG_TAKEFOCUS)
             res = acc->doAction(SetFocus, entry, QVariantList());
         if (flagsSelect & SELFLAG_TAKESELECTION) {
             acc->doAction(ClearSelection, 0, QVariantList());   //### bug, 0 should be entry??
             res = acc->doAction(AddToSelection, entry, QVariantList());
         }
         if (flagsSelect & SELFLAG_EXTENDSELECTION)
             res = acc->doAction(ExtendSelection, entry, QVariantList());
         if (flagsSelect & SELFLAG_ADDSELECTION)
             res = acc->doAction(AddToSelection, entry, QVariantList());
         if (flagsSelect & SELFLAG_REMOVESELECTION)
             res = acc->doAction(RemoveSelection, entry, QVariantList());
     }
     return res ? S_OK : S_FALSE;
 }
AddRef()
ULONG STDMETHODCALLTYPE QWindowsAccessible::AddRef ()
Definition at line 743 of file qaccessible_win.cpp.
 {
     return ++ref;
 }
ContextSensitiveHelp()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::ContextSensitiveHelp (BOOL fEnterMode)
Definition at line 1470 of file qaccessible_win.cpp.
 {
     return S_OK;
 }
get_accChild()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accChild (VARIANT varChildID, IDispatch ** ppdispChild)
Definition at line 1128 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     if (varChildID.vt == VT_EMPTY)
         return E_INVALIDARG;
     int childIndex = varChildID.lVal;
     QAccessibleInterface *acc = 0;
     AccessibleElement elem(childIndex, accessible);
     if (elem.iface) {
         RelationFlag rel = elem.entry ? Child : Self;
         int index = elem.iface->navigate(rel, elem.entry, &acc);
         if (index == -1)
             return E_INVALIDARG;
     }
     if (acc) {
         QWindowsAccessible* wacc = new QWindowsAccessible(acc);
         wacc->QueryInterface(IID_IDispatch, (void**)ppdispChild);
         return S_OK;
     }
     *ppdispChild = 0;
     return S_FALSE;
 }
get_accChildCount()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accChildCount (long * pcountChildren)
Definition at line 1159 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     *pcountChildren = accessible->childCount();
     return S_OK;
 }
get_accDefaultAction()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accDefaultAction (VARIANT varID, BSTR * pszDefaultAction)
Definition at line 1203 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QString def = elem.iface ? elem.iface->actionText(DefaultAction, Name, elem.entry) : QString();
     if (def.isEmpty()) {
         *pszDefaultAction = 0;
         return S_FALSE;
     }
     *pszDefaultAction = QStringToBSTR(def);
     return S_OK;
 }
get_accDescription()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accDescription (VARIANT varID, BSTR * pszDescription)
Definition at line 1220 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QString descr = elem.text(Description);
     if (descr.size()) {
         *pszDescription = QStringToBSTR(descr);
         return S_OK;
     }
     *pszDescription = 0;
     return S_FALSE;
 }
get_accFocus()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accFocus (VARIANT * pvarID)
Definition at line 1381 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     QAccessibleInterface *acc = 0;
     int control = accessible->navigate(FocusChild, 1, &acc);
     if (control == -1) {
         (*pvarID).vt = VT_EMPTY;
         return S_FALSE;
     }
     if (!acc || control == 0) {
         (*pvarID).vt = VT_I4;
         (*pvarID).lVal = control ? control : CHILDID_SELF;
         return S_OK;
     }
     QWindowsAccessible* wacc = new QWindowsAccessible(acc);
     IDispatch *iface = 0;
     wacc->QueryInterface(IID_IDispatch, (void**)&iface);
     if (iface) {
         (*pvarID).vt = VT_DISPATCH;
         (*pvarID).pdispVal = iface;
         return S_OK;
     } else {
         delete wacc;
     }
     (*pvarID).vt = VT_EMPTY;
     return S_FALSE;
 }
get_accHelp()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accHelp (VARIANT varID, BSTR * pszHelp)
Definition at line 1237 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QString help = elem.text(Help);
     if (help.size()) {
         *pszHelp = QStringToBSTR(help);
         return S_OK;
     }
     *pszHelp = 0;
     return S_FALSE;
 }
get_accHelpTopic()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accHelpTopic (BSTR * pszHelpFile, VARIANT varChild, long * pidTopic)
Definition at line 1254 of file qaccessible_win.cpp.
 {
     return DISP_E_MEMBERNOTFOUND;
 }
get_accKeyboardShortcut()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accKeyboardShortcut (VARIANT varID, BSTR * pszKeyboardShortcut)
Definition at line 1259 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QString sc = elem.text(Accelerator);
     if (sc.size()) {
         *pszKeyboardShortcut = QStringToBSTR(sc);
         return S_OK;
     }
     *pszKeyboardShortcut = 0;
     return S_FALSE;
 }
get_accName()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accName (VARIANT varID, BSTR * pszName)
Definition at line 1276 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QString n = elem.text(Name);
     if (n.size()) {
         *pszName = QStringToBSTR(n);
         return S_OK;
     }
     *pszName = 0;
     return S_FALSE;
 }
get_accParent()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accParent (IDispatch ** ppdispParent)
Definition at line 1169 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     QAccessibleInterface *acc = 0;
     accessible->navigate(Ancestor, 1, &acc);
     if (acc) {
         QWindowsAccessible* wacc = new QWindowsAccessible(acc);
         wacc->QueryInterface(IID_IDispatch, (void**)ppdispParent);
         if (*ppdispParent)
             return S_OK;
     }
     *ppdispParent = 0;
     return S_FALSE;
 }
get_accRole()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accRole (VARIANT varID, VARIANT * pvarRole)
Definition at line 1299 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     Role role = elem.iface ? elem.iface->role(elem.entry) : NoRole;
     if (role != NoRole) {
         if (role == LayeredPane)
             role = QAccessible::Pane;
         (*pvarRole).vt = VT_I4;
         (*pvarRole).lVal = role;
     } else {
         (*pvarRole).vt = VT_EMPTY;
     }
     return S_OK;
 }
get_accSelection()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accSelection (VARIANT * pvarChildren)
Definition at line 1414 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     int cc = accessible->childCount();
     QVector<int> sel(cc);
     int selIndex = 0;
     for (int i = 1; i <= cc; ++i) {
         QAccessibleInterface *child = 0;
         int i2 = accessible->navigate(Child, i, &child);
         bool isSelected = false;
         if (child) {
             isSelected = child->state(0) & Selected;
             delete child;
             child = 0;
         } else {
             isSelected = accessible->state(i2) & Selected;
         }
         if (isSelected)
             sel[selIndex++] = i;
     }
     sel.resize(selIndex);
     if (sel.isEmpty()) {
         (*pvarChildren).vt = VT_EMPTY;
         return S_FALSE;
     }
     if (sel.size() == 1) {
         (*pvarChildren).vt = VT_I4;
         (*pvarChildren).lVal = sel[0];
         return S_OK;
     }
     IEnumVARIANT *iface = new QWindowsEnumerate(sel);
     IUnknown *uiface;
     iface->QueryInterface(IID_IUnknown, (void**)&uiface);
     (*pvarChildren).vt = VT_UNKNOWN;
     (*pvarChildren).punkVal = uiface;
     return S_OK;
 }
get_accState()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accState (VARIANT varID, VARIANT * pvarState)
Definition at line 1318 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     (*pvarState).vt = VT_I4;
     AccessibleElement elem(varID.lVal, accessible);
     (*pvarState).lVal = elem.iface ? elem.iface->state(elem.entry) : State(Normal);
     return S_OK;
 }
get_accValue()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::get_accValue (VARIANT varID, BSTR * pszValue)
Definition at line 1330 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     if (!accessible->isValid())
         return E_FAIL;
     AccessibleElement elem(varID.lVal, accessible);
     QString value = elem.text(Value);
     if (!value.isNull()) {
         *pszValue = QStringToBSTR(value);
         return S_OK;
     }
     *pszValue = 0;
     return S_FALSE;
 }
GetIDsOfNames()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::GetIDsOfNames (const _GUID & , wchar_t ** rgszNames, unsigned int, unsigned long, long * rgdispid)
Definition at line 775 of file qaccessible_win.cpp.
 {
 #if !defined(Q_CC_BOR) && !defined(Q_CC_GNU)
     // PROPERTIES:  Hierarchical
     if (_bstr_t(rgszNames[0]) == _bstr_t(L"accParent"))
         rgdispid[0] = DISPID_ACC_PARENT;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accChildCount"))
         rgdispid[0] = DISPID_ACC_CHILDCOUNT;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accChild"))
         rgdispid[0] = DISPID_ACC_CHILD;
     // PROPERTIES:  Descriptional
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accName("))
         rgdispid[0] = DISPID_ACC_NAME;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accValue"))
         rgdispid[0] = DISPID_ACC_VALUE;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accDescription"))
         rgdispid[0] = DISPID_ACC_DESCRIPTION;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accRole"))
         rgdispid[0] = DISPID_ACC_ROLE;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accState"))
         rgdispid[0] = DISPID_ACC_STATE;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accHelp"))
         rgdispid[0] = DISPID_ACC_HELP;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accHelpTopic"))
         rgdispid[0] = DISPID_ACC_HELPTOPIC;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accKeyboardShortcut"))
         rgdispid[0] = DISPID_ACC_KEYBOARDSHORTCUT;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accFocus"))
         rgdispid[0] = DISPID_ACC_FOCUS;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accSelection"))
         rgdispid[0] = DISPID_ACC_SELECTION;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accDefaultAction"))
         rgdispid[0] = DISPID_ACC_DEFAULTACTION;
     // METHODS
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accSelect"))
         rgdispid[0] = DISPID_ACC_SELECT;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accLocation"))
         rgdispid[0] = DISPID_ACC_LOCATION;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accNavigate"))
         rgdispid[0] = DISPID_ACC_NAVIGATE;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accHitTest"))
         rgdispid[0] = DISPID_ACC_HITTEST;
     else if(_bstr_t(rgszNames[0]) == _bstr_t(L"accDoDefaultAction"))
         rgdispid[0] = DISPID_ACC_DODEFAULTACTION;
     else
         return DISP_E_UNKNOWNINTERFACE;
     return S_OK;
 #else
     Q_UNUSED(rgszNames);
     Q_UNUSED(rgdispid);
     return DISP_E_MEMBERNOTFOUND;
 #endif
 }
GetTypeInfo()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::GetTypeInfo (unsigned int, unsigned long, ITypeInfo ** pptinfo)
Definition at line 768 of file qaccessible_win.cpp.
 {
     // We don't use a type library
     *pptinfo = 0;
     return S_OK;
 }
GetTypeInfoCount()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::GetTypeInfoCount (unsigned int * pctinfo)
Definition at line 761 of file qaccessible_win.cpp.
 {
     // We don't use a type library
     *pctinfo = 0;
     return S_OK;
 }
GetWindow()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::GetWindow (HWND * phwnd)
Definition at line 1456 of file qaccessible_win.cpp.
 {
     *phwnd = 0;
     if (!accessible->isValid())
         return E_UNEXPECTED;
     QObject *o = accessible->object();
     if (!o || !o->isWidgetType())
         return E_FAIL;
     *phwnd = static_cast<QWidget*>(o)->effectiveWinId();
     return S_OK;
 }
Invoke()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::Invoke (long dispIdMember, const _GUID & , unsigned long, unsigned short wFlags, tagDISPPARAMS * pDispParams, tagVARIANT * pVarResult, tagEXCEPINFO * , unsigned int *)
Definition at line 833 of file qaccessible_win.cpp.
 {
     HRESULT hr = DISP_E_MEMBERNOTFOUND;
     switch(dispIdMember)
     {
         case DISPID_ACC_PARENT:
             if (wFlags == DISPATCH_PROPERTYGET) {
                 if (!pVarResult)
                     return E_INVALIDARG;
                 hr = get_accParent(&pVarResult->pdispVal);
             } else {
                 hr = DISP_E_MEMBERNOTFOUND;
             }
             break;
         case DISPID_ACC_CHILDCOUNT:
             if (wFlags == DISPATCH_PROPERTYGET) {
                 if (!pVarResult)
                     return E_INVALIDARG;
                 hr = get_accChildCount(&pVarResult->lVal);
             } else {
                 hr = DISP_E_MEMBERNOTFOUND;
             }
             break;
         case DISPID_ACC_CHILD:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accChild(pDispParams->rgvarg[0], &pVarResult->pdispVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_NAME:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accName(pDispParams->rgvarg[0], &pVarResult->bstrVal);
             else if (wFlags == DISPATCH_PROPERTYPUT)
                 hr = put_accName(pDispParams->rgvarg[0], pVarResult->bstrVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_VALUE:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accValue(pDispParams->rgvarg[0], &pVarResult->bstrVal);
             else if (wFlags == DISPATCH_PROPERTYPUT)
                 hr = put_accValue(pDispParams->rgvarg[0], pVarResult->bstrVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_DESCRIPTION:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accDescription(pDispParams->rgvarg[0], &pVarResult->bstrVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_ROLE:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accRole(pDispParams->rgvarg[0], pVarResult);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_STATE:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accState(pDispParams->rgvarg[0], pVarResult);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_HELP:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accHelp(pDispParams->rgvarg[0], &pVarResult->bstrVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_HELPTOPIC:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accHelpTopic(&pDispParams->rgvarg[2].bstrVal, pDispParams->rgvarg[1], &pDispParams->rgvarg[0].lVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_KEYBOARDSHORTCUT:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accKeyboardShortcut(pDispParams->rgvarg[0], &pVarResult->bstrVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_FOCUS:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accFocus(pVarResult);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_SELECTION:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accSelection(pVarResult);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_DEFAULTACTION:
             if (wFlags == DISPATCH_PROPERTYGET)
                 hr = get_accDefaultAction(pDispParams->rgvarg[0], &pVarResult->bstrVal);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_SELECT:
             if (wFlags == DISPATCH_METHOD)
                 hr = accSelect(pDispParams->rgvarg[1].lVal, pDispParams->rgvarg[0]);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_LOCATION:
             if (wFlags == DISPATCH_METHOD)
                 hr = accLocation(&pDispParams->rgvarg[4].lVal, &pDispParams->rgvarg[3].lVal, &pDispParams->rgvarg[2].lVal, &pDispParams->rgvarg[1].lVal, pDispParams->rgvarg[0]);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_NAVIGATE:
             if (wFlags == DISPATCH_METHOD)
                 hr = accNavigate(pDispParams->rgvarg[1].lVal, pDispParams->rgvarg[0], pVarResult);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_HITTEST:
             if (wFlags == DISPATCH_METHOD)
                 hr = accHitTest(pDispParams->rgvarg[1].lVal, pDispParams->rgvarg[0].lVal, pVarResult);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         case DISPID_ACC_DODEFAULTACTION:
             if (wFlags == DISPATCH_METHOD)
                 hr = accDoDefaultAction(pDispParams->rgvarg[0]);
             else
                 hr = DISP_E_MEMBERNOTFOUND;
             break;
         default:
             hr = DISP_E_MEMBERNOTFOUND;
             break;
     }
     if (!SUCCEEDED(hr)) {
         return hr;
     }
     return hr;
 }
put_accName()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::put_accName (VARIANT varChild, BSTR szName)
Definition at line 1293 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     return DISP_E_MEMBERNOTFOUND;
 }
put_accValue()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::put_accValue (VARIANT varChild, BSTR szValue)
Definition at line 1347 of file qaccessible_win.cpp.
 {
     showDebug(__FUNCTION__, accessible);
     return DISP_E_MEMBERNOTFOUND;
 }
QueryInterface()
HRESULT STDMETHODCALLTYPE QWindowsAccessible::QueryInterface (REFIID id, LPVOID * iface)
Definition at line 725 of file qaccessible_win.cpp.
Referenced by accHitTest(), accNavigate(), get_accChild(), get_accFocus(), get_accParent(), and qt_createWindowsAccessible().
 {
     *iface = 0;
     if (id == IID_IUnknown)
         *iface = (IUnknown*)(IDispatch*)this;
     else if (id == IID_IDispatch)
         *iface = (IDispatch*)this;
     else if (id == IID_IAccessible)
         *iface = (IAccessible*)this;
     else if (id == IID_IOleWindow)
         *iface = (IOleWindow*)this;
     else
         return E_NOINTERFACE;
     AddRef();
     return S_OK;
 }
Release()
ULONG STDMETHODCALLTYPE QWindowsAccessible::Release ()
Definition at line 748 of file qaccessible_win.cpp.
 {
     if (!--ref) {
         delete this;
         return 0;
     }
     return ref;
 }
Properties
accessible
QAccessibleInterface* QWindowsAccessible::accessible private
Definition at line 703 of file qaccessible_win.cpp.
ref
ULONG QWindowsAccessible::ref private
Definition at line 702 of file qaccessible_win.cpp.
The documentation for this class was generated from the following file:
/src/gui/accessible/qaccessible_win.cpp