Qt 4.8: QNetworkAccessBackend Class Reference
QNetworkAccessBackend Class Reference abstract
#include <qnetworkaccessbackend_p.h>
Public Slots
void writeDownstreamData (QIODevice *data)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QVariant attribute (QNetworkRequest::Attribute code) const
virtual bool canResume () const
virtual void closeDownstreamChannel ()=0
virtual void copyFinished (QIODevice *)
virtual void downstreamReadyWrite ()
virtual void emitReadBufferFreed (qint64 size)
virtual QNetworkCacheMetaData fetchCacheMetaData (const QNetworkCacheMetaData &metaData) const
virtual void fetchSslConfiguration (QSslConfiguration &configuration) const
bool hasRawHeader (const QByteArray &headerName) const
QVariant header (QNetworkRequest::KnownHeaders header) const
virtual void ignoreSslErrors ()
virtual void ignoreSslErrors (const QList< QSslError > &errors)
bool isCachingEnabled () const
bool isSynchronous ()
virtual bool needsResetableUploadData ()
QAbstractNetworkCache * networkCache () const
virtual void open ()=0
QNetworkAccessManager::Operation operation () const
virtual bool processRequestSynchronously ()
QList< QNetworkProxy > proxyList () const
QNetworkAccessBackend ()
QByteArray rawHeader (const QByteArray &headerName) const
QList< QByteArray > rawHeaderList () const
QNetworkRequest request () const
void setAttribute (QNetworkRequest::Attribute code, const QVariant &value)
void setCachingEnabled (bool enable)
virtual void setDownstreamLimited (bool b)
void setHeader (QNetworkRequest::KnownHeaders header, const QVariant &value)
void setRawHeader (const QByteArray &headerName, const QByteArray &value)
virtual void setReadBufferSize (qint64 size)
virtual void setResumeOffset (quint64 offset)
virtual void setSslConfiguration (const QSslConfiguration &configuration)
void setSynchronous (bool sync)
void setUrl (const QUrl &url)
virtual bool start ()
Starts the backend.
QUrl url () const
virtual ~QNetworkAccessBackend ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
void authenticationRequired (QAuthenticator *auth)
void emitReplyUploadProgress (qint64 bytesSent, qint64 bytesTotal)
void error (QNetworkReply::NetworkError code, const QString &errorString)
void finished ()
void metaDataChanged ()
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *auth)
void redirectionRequested (const QUrl &destination)
void sslErrors (const QList< QSslError > &errors)
Protected Functions
QNonContiguousByteDevice * createUploadByteDevice ()
char * getDownloadBuffer (qint64)
qint64 nextDownstreamBlockSize () const
void writeDownstreamData (QByteDataBuffer &list)
void writeDownstreamDataDownloadBuffer (qint64, qint64)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables
QNetworkAccessManagerPrivate * manager
QNetworkReplyImplPrivate * reply
QSharedPointer< QNonContiguousByteDevice > uploadByteDevice
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Properties
bool synchronous
Friends
class QNetworkAccessManager
class QNetworkAccessManagerPrivate
class QNetworkReplyImplPrivate
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 79 of file qnetworkaccessbackend_p.h.
Constructors and Destructors
QNetworkAccessBackend()
QNetworkAccessBackend::QNetworkAccessBackend ()
Definition at line 145 of file qnetworkaccessbackend.cpp.
     : manager(0)
     , reply(0)
     , synchronous(false)
 {
 }
~QNetworkAccessBackend()
QNetworkAccessBackend::~QNetworkAccessBackend () virtual
Definition at line 152 of file qnetworkaccessbackend.cpp.
 {
 }
Functions
attribute()
QVariant QNetworkAccessBackend::attribute (QNetworkRequest::Attribute code) const
Definition at line 300 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     return reply->q_func()->attribute(code);
 }
authenticationRequired
void QNetworkAccessBackend::authenticationRequired (QAuthenticator * auth) protected slot
Definition at line 340 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessHttpBackend::httpAuthenticationRequired(), and QNetworkAccessHttpBackend::postRequest().
 {
     manager->authenticationRequired(this, authenticator);
 }
canResume()
virtual bool QNetworkAccessBackend::canResume () const inline virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 168 of file qnetworkaccessbackend_p.h.
 { return false; }
closeDownstreamChannel()
virtual void QNetworkAccessBackend::closeDownstreamChannel () pure virtual
Implemented in QNetworkAccessFtpBackend, QNetworkAccessHttpBackend, QNetworkAccessFileBackend, and QNetworkAccessCacheBackend.
Referenced by QNetworkReplyImplPrivate::handleNotifications().
copyFinished()
void QNetworkAccessBackend::copyFinished (QIODevice *) virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 179 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkReplyImplPrivate::handleNotifications().
 {
     // do nothing
 }
createUploadByteDevice()
QNonContiguousByteDevice * QNetworkAccessBackend::createUploadByteDevice () protected
Definition at line 113 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkAccessHttpBackend::postRequest(), and processRequestSynchronously().
 {
     if (reply->outgoingDataBuffer)
         uploadByteDevice = QSharedPointer<QNonContiguousByteDevice>(QNonContiguousByteDeviceFactory::create(reply->outgoingDataBuffer));
     else if (reply->outgoingData) {
         uploadByteDevice = QSharedPointer<QNonContiguousByteDevice>(QNonContiguousByteDeviceFactory::create(reply->outgoingData));
     } else {
         return 0;
     }
     bool bufferDisallowed =
             reply->request.attribute(QNetworkRequest::DoNotBufferUploadDataAttribute,
                           QVariant(false)) == QVariant(true);
     if (bufferDisallowed)
         uploadByteDevice->disableReset();
     // We want signal emissions only for normal asynchronous uploads
     if (!isSynchronous())
         connect(uploadByteDevice.data(), SIGNAL(readProgress(qint64,qint64)), this, SLOT(emitReplyUploadProgress(qint64,qint64)));
     return uploadByteDevice.data();
 }
downstreamReadyWrite()
void QNetworkAccessBackend::downstreamReadyWrite () virtual
Reimplemented in QNetworkAccessFtpBackend, QNetworkAccessHttpBackend, QNetworkAccessCacheBackend, and QNetworkAccessFileBackend.
Definition at line 156 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkReplyImplPrivate::handleNotifications().
 {
     // do nothing
 }
emitReadBufferFreed()
void QNetworkAccessBackend::emitReadBufferFreed (qint64 size) virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 173 of file qnetworkaccessbackend.cpp.
 {
     Q_UNUSED(size);
     // do nothing
 }
emitReplyUploadProgress
void QNetworkAccessBackend::emitReplyUploadProgress (qint64 bytesSent, qint64 bytesTotal) protected slot
Definition at line 138 of file qnetworkaccessbackend.cpp.
 {
     if (reply->isFinished)
         return;
     reply->emitUploadProgress(bytesSent, bytesTotal);
 }
error
void QNetworkAccessBackend::error (QNetworkReply::NetworkError code, const QString & errorString) protected slot
Definition at line 327 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessHttpBackend::httpError(), QNetworkAccessFileBackend::loadFileInfo(), QNetworkAccessHttpBackend::needsResetableUploadData(), QNetworkAccessCacheBackend::open(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkAccessHttpBackend::postRequest(), QNetworkAccessFileBackend::readMoreFromFile(), and QNetworkAccessFileBackend::uploadReadyReadSlot().
 {
     reply->error(code, errorString);
 }
fetchCacheMetaData()
QNetworkCacheMetaData QNetworkAccessBackend::fetchCacheMetaData (const QNetworkCacheMetaData & metaData) const virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 205 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkReplyImplPrivate::initCacheSaveDevice().
 {
     return QNetworkCacheMetaData();
 }
fetchSslConfiguration()
void QNetworkAccessBackend::fetchSslConfiguration (QSslConfiguration & configuration) const virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 195 of file qnetworkaccessbackend.cpp.
 {
     // do nothing
 }
finished
void QNetworkAccessBackend::finished () protected slot
Definition at line 322 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::copyFinished(), QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessFileBackend::loadFileInfo(), QNetworkAccessCacheBackend::open(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkAccessHttpBackend::postRequest(), QNetworkAccessFileBackend::readMoreFromFile(), QNetworkAccessHttpBackend::replyFinished(), and QNetworkAccessFileBackend::uploadReadyReadSlot().
 {
     reply->finished();
 }
getDownloadBuffer()
char * QNetworkAccessBackend::getDownloadBuffer (qint64 size) protected
Definition at line 265 of file qnetworkaccessbackend.cpp.
Referenced by processRequestSynchronously().
 {
     return reply->getDownloadBuffer(size);
 }
hasRawHeader()
bool QNetworkAccessBackend::hasRawHeader (const QByteArray & headerName) const
Definition at line 280 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::canResume(), and QNetworkAccessHttpBackend::loadFromCacheIfAllowed().
 {
     return reply->q_func()->hasRawHeader(headerName);
 }
header()
QVariant QNetworkAccessBackend::header (QNetworkRequest::KnownHeaders header) const
Definition at line 270 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::checkForRedirect(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessHttpBackend::postRequest(), and QNetworkAccessHttpBackend::replyDownloadMetaData().
 {
     return reply->q_func()->header(header);
 }
ignoreSslErrors() [1/2]
void QNetworkAccessBackend::ignoreSslErrors () virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 184 of file qnetworkaccessbackend.cpp.
 {
     // do nothing
 }
ignoreSslErrors() [2/2]
void QNetworkAccessBackend::ignoreSslErrors (const QList< QSslError > & errors) virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 189 of file qnetworkaccessbackend.cpp.
 {
     Q_UNUSED(errors);
     // do nothing
 }
isCachingEnabled()
bool QNetworkAccessBackend::isCachingEnabled () const
Definition at line 239 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::replyDownloadMetaData().
 {
     return reply->isCachingEnabled();
 }
isSynchronous()
bool QNetworkAccessBackend::isSynchronous () inline
Definition at line 159 of file qnetworkaccessbackend_p.h.
Referenced by QNetworkReplyImplPrivate::_q_startOperation(), QNetworkAccessManagerPrivate::authenticationRequired(), QNetworkAccessHttpBackend::postRequest(), QNetworkAccessManagerPrivate::proxyAuthenticationRequired(), QNetworkAccessHttpBackend::sendCacheContents(), and QNetworkReplyImplPrivate::setup().
 { return synchronous; }
metaDataChanged
void QNetworkAccessBackend::metaDataChanged () protected slot
Definition at line 345 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessFileBackend::loadFileInfo(), QNetworkAccessHttpBackend::replyDownloadMetaData(), and QNetworkAccessCacheBackend::sendCacheContents().
 {
     reply->metaDataChanged();
 }
needsResetableUploadData()
virtual bool QNetworkAccessBackend::needsResetableUploadData () inline virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 165 of file qnetworkaccessbackend_p.h.
Referenced by QNetworkReplyImplPrivate::setup().
 { return false; }
networkCache()
QAbstractNetworkCache * QNetworkAccessBackend::networkCache () const
Definition at line 227 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::invalidateCache(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkReplyImplPrivate::networkCache(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QNetworkAccessCacheBackend::sendCacheContents(), and QNetworkAccessHttpBackend::sendCacheContents().
 {
     if (!manager)
         return 0;
     return manager->networkCache;
 }
nextDownstreamBlockSize()
qint64 QNetworkAccessBackend::nextDownstreamBlockSize () const protected
Definition at line 244 of file qnetworkaccessbackend.cpp.
Referenced by processRequestSynchronously(), and QNetworkAccessFileBackend::readMoreFromFile().
 {
     return reply->nextDownstreamBlockSize();
 }
open()
virtual void QNetworkAccessBackend::open () pure virtual
Implemented in QNetworkAccessFtpBackend, QNetworkAccessHttpBackend, QNetworkAccessFileBackend, and QNetworkAccessCacheBackend.
Referenced by start().
operation()
QNetworkAccessManager::Operation QNetworkAccessBackend::operation () const
Definition at line 210 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::canResume(), QNetworkAccessCacheBackend::closeDownstreamChannel(), QNetworkAccessFileBackend::closeDownstreamChannel(), QNetworkAccessFtpBackend::closeDownstreamChannel(), QNetworkAccessFileBackend::downstreamReadyWrite(), QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessCacheBackend::open(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkAccessHttpBackend::postRequest(), and QNetworkAccessCacheBackend::sendCacheContents().
 {
     return reply->operation;
 }
processRequestSynchronously()
virtual bool QNetworkAccessBackend::processRequestSynchronously () inline virtual
Definition at line 171 of file qnetworkaccessbackend_p.h.
 { return false; }
proxyAuthenticationRequired
void QNetworkAccessBackend::proxyAuthenticationRequired (const QNetworkProxy & proxy, QAuthenticator * auth) protected slot
Definition at line 333 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     manager->proxyAuthenticationRequired(this, proxy, authenticator);
 }
proxyList()
QList< QNetworkProxy > QNetworkAccessBackend::proxyList () const
Definition at line 221 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::open(), and QNetworkAccessHttpBackend::postRequest().
 {
     return reply->proxyList;
 }
rawHeader()
QByteArray QNetworkAccessBackend::rawHeader (const QByteArray & headerName) const
Definition at line 285 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::canResume(), QNetworkAccessHttpBackend::checkForRedirect(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessHttpBackend::postRequest(), and QNetworkAccessHttpBackend::replyDownloadMetaData().
 {
     return reply->q_func()->rawHeader(headerName);
 }
rawHeaderList()
QList< QByteArray > QNetworkAccessBackend::rawHeaderList () const
Definition at line 290 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), and QNetworkAccessHttpBackend::loadFromCacheIfAllowed().
 {
     return reply->q_func()->rawHeaderList();
 }
redirectionRequested
void QNetworkAccessBackend::redirectionRequested (const QUrl & destination) protected slot
Definition at line 350 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::checkForRedirect(), and QNetworkAccessCacheBackend::sendCacheContents().
 {
     reply->redirectionRequested(target);
 }
request()
QNetworkRequest QNetworkAccessBackend::request () const
Definition at line 215 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QNetworkAccessHttpBackend::canResume(), QNetworkAccessHttpBackend::fetchSslConfiguration(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkAccessHttpBackend::needsResetableUploadData(), and QNetworkAccessHttpBackend::postRequest().
 {
     return reply->request;
 }
setAttribute()
void QNetworkAccessBackend::setAttribute (QNetworkRequest::Attribute code, const QVariant & value)
Definition at line 305 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessCacheBackend::open(), QNetworkAccessHttpBackend::postRequest(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QNetworkAccessCacheBackend::sendCacheContents(), and QNetworkAccessHttpBackend::sendCacheContents().
 {
     if (value.isValid())
         reply->attributes.insert(code, value);
     else
         reply->attributes.remove(code);
 }
setCachingEnabled()
void QNetworkAccessBackend::setCachingEnabled (bool enable)
Definition at line 234 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QNetworkAccessCacheBackend::sendCacheContents(), and QNetworkAccessHttpBackend::sendCacheContents().
 {
     reply->setCachingEnabled(enable);
 }
setDownstreamLimited()
void QNetworkAccessBackend::setDownstreamLimited (bool b) virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 161 of file qnetworkaccessbackend.cpp.
 {
     Q_UNUSED(b);
     // do nothing
 }
setHeader()
void QNetworkAccessBackend::setHeader (QNetworkRequest::KnownHeaders header, const QVariant & value)
Definition at line 275 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpRawCommandReply(), and QNetworkAccessFileBackend::loadFileInfo().
 {
     reply->setCookedHeader(header, value);
 }
setRawHeader()
void QNetworkAccessBackend::setRawHeader (const QByteArray & headerName, const QByteArray & value)
Definition at line 295 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::replyDownloadMetaData(), QNetworkAccessCacheBackend::sendCacheContents(), and QNetworkAccessHttpBackend::sendCacheContents().
 {
     reply->setRawHeader(headerName, headerValue);
 }
setReadBufferSize()
void QNetworkAccessBackend::setReadBufferSize (qint64 size) virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 167 of file qnetworkaccessbackend.cpp.
 {
     Q_UNUSED(size);
     // do nothing
 }
setResumeOffset()
virtual void QNetworkAccessBackend::setResumeOffset (quint64 offset) inline virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 169 of file qnetworkaccessbackend_p.h.
 { Q_UNUSED(offset); }
setSslConfiguration()
void QNetworkAccessBackend::setSslConfiguration (const QSslConfiguration & configuration) virtual
Reimplemented in QNetworkAccessHttpBackend.
Definition at line 200 of file qnetworkaccessbackend.cpp.
 {
     // do nothing
 }
setSynchronous()
void QNetworkAccessBackend::setSynchronous (bool sync) inline
Definition at line 160 of file qnetworkaccessbackend_p.h.
Referenced by QNetworkReplyImplPrivate::setup().
 { synchronous = sync; }
setUrl()
void QNetworkAccessBackend::setUrl (const QUrl & url)
Definition at line 317 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessFileBackend::open(), and QNetworkAccessFtpBackend::open().
 {
     reply->url = url;
 }
sslErrors
void QNetworkAccessBackend::sslErrors (const QList< QSslError > & errors) protected slot
Definition at line 355 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest(), and QNetworkAccessHttpBackend::replySslErrors().
 {
 #ifndef QT_NO_OPENSSL
     reply->sslErrors(errors);
 #else
     Q_UNUSED(errors);
 #endif
 }
start()
bool QNetworkAccessBackend::start () virtual
Starts the backend.
Returns true if the backend is started. Returns false if the backend could not be started due to an unopened or roaming session. The caller should recall this function once the session has been opened or the roaming process has finished.
Definition at line 369 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkReplyImplPrivate::_q_startOperation().
 {
 #ifndef QT_NO_BEARERMANAGEMENT
     // For bearer, check if session start is required
     QSharedPointer<QNetworkSession> networkSession(manager->getNetworkSession());
     if (networkSession) {
         // session required
         if (networkSession->isOpen() &&
             networkSession->state() == QNetworkSession::Connected) {
             // Session is already open and ready to use.
             // copy network session down to the backend
             setProperty("_q_networksession", QVariant::fromValue(networkSession));
         } else {
             // Session not ready, but can skip for loopback connections
             // This is not ideal.
             const QString host = reply->url.host();
             if (host == QLatin1String("localhost") ||
                 QHostAddress(host) == QHostAddress::LocalHost ||
                 QHostAddress(host) == QHostAddress::LocalHostIPv6) {
                 // Don't need an open session for localhost access.
             } else {
                 // need to wait for session to be opened
                 return false;
             }
         }
     }
 #endif
 #ifndef QT_NO_NETWORKPROXY
 #ifndef QT_NO_BEARERMANAGEMENT
     // Get the proxy settings from the network session (in the case of service networks,
     // the proxy settings change depending which AP was activated)
     QNetworkSession *session = networkSession.data();
     QNetworkConfiguration config;
     if (session) {
         QNetworkConfigurationManager configManager;
         // The active configuration tells us what IAP is in use
         QVariant v = session->sessionProperty(QLatin1String("ActiveConfiguration"));
         if (v.isValid())
             config = configManager.configurationFromIdentifier(qvariant_cast<QString>(v));
         // Fallback to using the configuration if no active configuration
         if (!config.isValid())
             config = session->configuration();
         // or unspecified configuration if that is no good either
         if (!config.isValid())
             config = QNetworkConfiguration();
     }
     reply->proxyList = manager->queryProxy(QNetworkProxyQuery(config, url()));
 #else // QT_NO_BEARERMANAGEMENT
     // Without bearer management, the proxy depends only on the url
     reply->proxyList = manager->queryProxy(QNetworkProxyQuery(url()));
 #endif
 #endif
     // now start the request
     open();
     return true;
 }
url()
QUrl QNetworkAccessBackend::url () const
Definition at line 312 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessHttpBackend::checkForRedirect(), QNetworkAccessFtpBackend::disconnectFromFtp(), QNetworkAccessFtpBackend::ftpDone(), QNetworkAccessHttpBackend::invalidateCache(), QNetworkAccessFileBackend::loadFileInfo(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkAccessCacheBackend::open(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkAccessHttpBackend::postRequest(), QNetworkAccessFileBackend::readMoreFromFile(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QNetworkAccessCacheBackend::sendCacheContents(), QNetworkAccessHttpBackend::sendCacheContents(), setUrl(), start(), and QNetworkAccessFileBackend::uploadReadyReadSlot().
 {
     return reply->url;
 }
writeDownstreamData() [1/2]
void QNetworkAccessBackend::writeDownstreamData (QByteDataBuffer & list) protected
Definition at line 249 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessFtpBackend::ftpReadyRead(), processRequestSynchronously(), QNetworkAccessFileBackend::readMoreFromFile(), QNetworkAccessHttpBackend::replyDownloadData(), and QNetworkAccessCacheBackend::sendCacheContents().
 {
     reply->appendDownstreamData(list);
 }
writeDownstreamData [2/2]
void QNetworkAccessBackend::writeDownstreamData (QIODevice * data) slot
Definition at line 254 of file qnetworkaccessbackend.cpp.
 {
     reply->appendDownstreamData(data);
 }
writeDownstreamDataDownloadBuffer()
void QNetworkAccessBackend::writeDownstreamDataDownloadBuffer (qint64 bytesReceived, qint64 bytesTotal) protected
Definition at line 260 of file qnetworkaccessbackend.cpp.
Referenced by processRequestSynchronously(), and QNetworkAccessHttpBackend::replyDownloadProgressSlot().
 {
     reply->appendDownstreamDataDownloadBuffer(bytesReceived, bytesTotal);
 }
Friends and Related Functions
QNetworkAccessManager
friend class QNetworkAccessManager friend
Definition at line 211 of file qnetworkaccessbackend_p.h.
QNetworkAccessManagerPrivate
friend class QNetworkAccessManagerPrivate friend
Definition at line 212 of file qnetworkaccessbackend_p.h.
QNetworkReplyImplPrivate
friend class QNetworkReplyImplPrivate friend
Definition at line 213 of file qnetworkaccessbackend_p.h.
Properties
manager
QNetworkAccessManagerPrivate* QNetworkAccessBackend::manager protected
Definition at line 207 of file qnetworkaccessbackend_p.h.
Referenced by authenticationRequired(), QNetworkAccessManager::createRequest(), QNetworkAccessManagerPrivate::findBackend(), QNetworkAccessManagerPrivate::getObjectCache(), networkCache(), QNetworkAccessHttpBackend::postRequest(), proxyAuthenticationRequired(), and start().
reply
QNetworkReplyImplPrivate* QNetworkAccessBackend::reply protected
Definition at line 208 of file qnetworkaccessbackend_p.h.
Referenced by attribute(), QNetworkAccessManagerPrivate::authenticationRequired(), QNetworkAccessManager::createRequest(), error(), finished(), getDownloadBuffer(), hasRawHeader(), header(), isCachingEnabled(), metaDataChanged(), nextDownstreamBlockSize(), operation(), QNetworkAccessManagerPrivate::proxyAuthenticationRequired(), proxyList(), rawHeader(), rawHeaderList(), redirectionRequested(), QNetworkAccessHttpBackend::replyDownloadMetaData(), request(), setAttribute(), setCachingEnabled(), setHeader(), setRawHeader(), setUrl(), sslErrors(), start(), url(), writeDownstreamData(), and writeDownstreamDataDownloadBuffer().
synchronous
bool QNetworkAccessBackend::synchronous private
Definition at line 215 of file qnetworkaccessbackend_p.h.
Referenced by isSynchronous(), and setSynchronous().
uploadByteDevice
QSharedPointer<QNonContiguousByteDevice> QNetworkAccessBackend::uploadByteDevice protected
Definition at line 186 of file qnetworkaccessbackend_p.h.
Referenced by QNetworkAccessHttpBackend::postRequest(), QNetworkAccessHttpBackend::resetUploadDataSlot(), QNetworkAccessHttpBackend::sentUploadDataSlot(), and QNetworkAccessHttpBackend::wantUploadDataSlot().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkaccessbackend_p.h
/src/network/access/qnetworkaccessbackend.cpp