Qt 4.8: QFileSystemWatcher Class Reference
QFileSystemWatcher Class Reference
The QFileSystemWatcher class provides an interface for monitoring files and directories for modifications.
#include <qfilesystemwatcher.h>
Signals
void directoryChanged (const QString &path)
This signal is emitted when the directory at a specified path, is modified (e.
void fileChanged (const QString &path)
This signal is emitted when the file at the specified path is modified, renamed or removed from disk.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addPath (const QString &file)
Adds path to the file system watcher if path exists.
void addPaths (const QStringList &files)
Adds each path in paths to the file system watcher.
QStringList directories () const
Returns a list of paths to directories that are being watched.
QStringList files () const
Returns a list of paths to files that are being watched.
QFileSystemWatcher (QObject *parent=0)
Constructs a new file system watcher object with the given parent.
QFileSystemWatcher (const QStringList &paths, QObject *parent=0)
Constructs a new file system watcher object with the given parent which monitors the specified paths list.
void removePath (const QString &file)
Removes the specified path from the file system watcher.
void removePaths (const QStringList &files)
Removes the specified paths from the file system watcher.
~QFileSystemWatcher ()
Destroys the file system watcher.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QFileSystemWatcher class provides an interface for monitoring files and directories for modifications.
Since
4.2
Note
This class or function is reentrant.
QFileSystemWatcher monitors the file system for changes to files and directories by watching a list of specified paths.
Call addPath() to watch a particular file or directory. Multiple paths can be added using the addPaths() function. Existing paths can be removed by using the removePath() and removePaths() functions.
QFileSystemWatcher examines each path added to it. Files that have been added to the QFileSystemWatcher can be accessed using the files() function, and directories using the directories() function.
The fileChanged() signal is emitted when a file has been modified, renamed or removed from disk. Similarly, the directoryChanged() signal is emitted when a directory or its contents is modified or removed. Note that QFileSystemWatcher stops monitoring files once they have been renamed or removed from disk, and directories once they have been removed from disk.
Note
On systems running a Linux kernel without inotify support, file systems that contain watched paths cannot be unmounted.
Windows CE does not support directory monitoring by default as this depends on the file system driver installed.
The act of monitoring files and directories for modifications consumes system resources. This implies there is a limit to the number of files and directories your process can monitor simultaneously. On Mac OS X 10.4 and all BSD variants, for example, an open file descriptor is required for each monitored file. Some system limits the number of open file descriptors to 256 by default. This means that addPath() and addPaths() will fail if your process tries to add more than 256 files or directories to the file system monitor. Also note that your process may have other file descriptors open in addition to the ones for files being monitored, and these other open descriptors also count in the total. Mac OS X 10.5 and up use a different backend and do not suffer from this issue.
See also
QFile, QDir
Definition at line 57 of file qfilesystemwatcher.h.
Constructors and Destructors
QFileSystemWatcher() [1/2]
QFileSystemWatcher::QFileSystemWatcher (QObject * parent = 0)
Constructs a new file system watcher object with the given parent.
Definition at line 423 of file qfilesystemwatcher.cpp.
     : QObject(*new QFileSystemWatcherPrivate, parent)
 {
     d_func()->init();
 }
QFileSystemWatcher() [2/2]
QFileSystemWatcher::QFileSystemWatcher (const QStringList & paths, QObject * parent = 0)
Constructs a new file system watcher object with the given parent which monitors the specified paths list.
Definition at line 433 of file qfilesystemwatcher.cpp.
     : QObject(*new QFileSystemWatcherPrivate, parent)
 {
     d_func()->init();
     addPaths(paths);
 }
~QFileSystemWatcher()
QFileSystemWatcher::~QFileSystemWatcher ()
Destroys the file system watcher.
Definition at line 443 of file qfilesystemwatcher.cpp.
 {
     Q_D(QFileSystemWatcher);
     if (d->native) {
         d->native->stop();
         d->native->wait();
         delete d->native;
         d->native = 0;
     }
     if (d->poller) {
         d->poller->stop();
         d->poller->wait();
         delete d->poller;
         d->poller = 0;
     }
     if (d->forced) {
         d->forced->stop();
         d->forced->wait();
         delete d->forced;
         d->forced = 0;
     }
 }
Functions
addPath()
void QFileSystemWatcher::addPath (const QString & path)
Adds path to the file system watcher if path exists.
The path is not added if it does not exist, or if it is already being monitored by the file system watcher.
If path specifies a directory, the directoryChanged() signal will be emitted when path is modified or removed from disk; otherwise the fileChanged() signal is emitted when path is modified, renamed or removed.
Note
There is a system dependent limit to the number of files and directories that can be monitored simultaneously. If this limit has been reached, path will not be added to the file system watcher, and a warning message will be printed to stderr.
See also
addPaths(), removePath()
Definition at line 483 of file qfilesystemwatcher.cpp.
Referenced by QFileInfoGatherer::getFileInfos().
 {
     if (path.isEmpty()) {
         qWarning("QFileSystemWatcher::addPath: path is empty");
         return;
     }
     addPaths(QStringList(path));
 }
addPaths()
void QFileSystemWatcher::addPaths (const QStringList & paths)
Adds each path in paths to the file system watcher.
Paths are not added if they not exist, or if they are already being monitored by the file system watcher.
If a path specifies a directory, the directoryChanged() signal will be emitted when the path is modified or removed from disk; otherwise the fileChanged() signal is emitted when the path is modified, renamed, or removed.
Note
There is a system dependent limit to the number of files and directories that can be monitored simultaneously. If this limit has been reached, the excess paths will not be added to the file system watcher, and a warning message will be printed to stderr for each path that could not be added.
See also
addPath(), removePaths()
Definition at line 510 of file qfilesystemwatcher.cpp.
Referenced by addPath(), and QFileSystemWatcher().
 {
     Q_D(QFileSystemWatcher);
     if (paths.isEmpty()) {
         qWarning("QFileSystemWatcher::addPaths: list is empty");
         return;
     }
     QStringList p = paths;
     QFileSystemWatcherEngine *engine = 0;
     if(!objectName().startsWith(QLatin1String("_qt_autotest_force_engine_"))) {
         // Normal runtime case - search intelligently for best engine
         if(d->native) {
             engine = d->native;
         } else {
             d_func()->initPollerEngine();
             engine = d->poller;
         }
     } else {
         // Autotest override case - use the explicitly selected engine only
         QString forceName = objectName().mid(26);
         if(forceName == QLatin1String("poller")) {
             qDebug() << "QFileSystemWatcher: skipping native engine, using only polling engine";
             d_func()->initPollerEngine();
             engine = d->poller;
         } else if(forceName == QLatin1String("native")) {
             qDebug() << "QFileSystemWatcher: skipping polling engine, using only native engine";
             engine = d->native;
         } else {
             qDebug() << "QFileSystemWatcher: skipping polling and native engine, using only explicit" << forceName << "engine";
             d_func()->initForcedEngine(forceName);
             engine = d->forced;
         }
     }
     if(engine)
         p = engine->addPaths(p, &d->files, &d->directories);
     if (!p.isEmpty())
         qWarning("QFileSystemWatcher: failed to add paths: %s",
                  qPrintable(p.join(QLatin1String(", "))));
 }
directories()
QStringList QFileSystemWatcher::directories () const
Returns a list of paths to directories that are being watched.
See also
files()
Definition at line 640 of file qfilesystemwatcher.cpp.
Referenced by QFileInfoGatherer::clear(), and QFileInfoGatherer::getFileInfos().
 {
     Q_D(const QFileSystemWatcher);
     return d->directories;
 }
directoryChanged
void QFileSystemWatcher::directoryChanged (const QString & path) signal
This signal is emitted when the directory at a specified path, is modified (e.
g., when a file is added, modified or deleted) or removed from disk. Note that if there are several changes during a short period of time, some of the changes might not emit this signal. However, the last change in the sequence of changes will always generate this signal.
See also
fileChanged()
fileChanged
void QFileSystemWatcher::fileChanged (const QString & path) signal
This signal is emitted when the file at the specified path is modified, renamed or removed from disk.
See also
directoryChanged()
files()
QStringList QFileSystemWatcher::files () const
Returns a list of paths to files that are being watched.
See also
directories()
Definition at line 646 of file qfilesystemwatcher.cpp.
Referenced by QFileInfoGatherer::clear(), and QFileInfoGatherer::getInfo().
 {
     Q_D(const QFileSystemWatcher);
     return d->files;
 }
removePath()
void QFileSystemWatcher::removePath (const QString & path)
Removes the specified path from the file system watcher.
See also
removePaths(), addPath()
Definition at line 560 of file qfilesystemwatcher.cpp.
Referenced by QFileInfoGatherer::removePath().
 {
     if (path.isEmpty()) {
         qWarning("QFileSystemWatcher::removePath: path is empty");
         return;
     }
     removePaths(QStringList(path));
 }
removePaths()
void QFileSystemWatcher::removePaths (const QStringList & paths)
Removes the specified paths from the file system watcher.
See also
removePath(), addPaths()
Definition at line 574 of file qfilesystemwatcher.cpp.
Referenced by QFileInfoGatherer::clear(), and removePath().
 {
     if (paths.isEmpty()) {
         qWarning("QFileSystemWatcher::removePaths: list is empty");
         return;
     }
     Q_D(QFileSystemWatcher);
     QStringList p = paths;
     if (d->native)
         p = d->native->removePaths(p, &d->files, &d->directories);
     if (d->poller)
         p = d->poller->removePaths(p, &d->files, &d->directories);
     if (d->forced)
         p = d->forced->removePaths(p, &d->files, &d->directories);
 }
The documentation for this class was generated from the following files:
/src/corelib/io/qfilesystemwatcher.h
/src/corelib/io/qfilesystemwatcher.cpp