Qt 4.8: QByteArrayMatcher Class Reference
QByteArrayMatcher Class Reference
The QByteArrayMatcher class holds a sequence of bytes that can be quickly matched in a byte array.
#include <qbytearraymatcher.h>
Classes
struct Data
Public Functions
int indexIn (const QByteArray &ba, int from=0) const
Searches the byte array ba, from byte position from (default 0, i.e.
int indexIn (const char *str, int len, int from=0) const
Searches the char string str, which has length len, from byte position from (default 0, i.e.
QByteArrayMatcher & operator= (const QByteArrayMatcher &other)
Assigns the other byte array matcher to this byte array matcher.
QByteArray pattern () const
Returns the byte array pattern that this byte array matcher will search for.
QByteArrayMatcher ()
Constructs an empty byte array matcher that won't match anything.
QByteArrayMatcher (const QByteArray &pattern)
Constructs a byte array matcher that will search for pattern.
QByteArrayMatcher (const char *pattern, int length)
Constructs a byte array matcher from pattern.
QByteArrayMatcher (const QByteArrayMatcher &other)
Copies the other byte array matcher to this byte array matcher.
void setPattern (const QByteArray &pattern)
Sets the byte array that this byte array matcher will search for to pattern.
~QByteArrayMatcher ()
Destroys the byte array matcher.
Properties
union {
uint dummy [256]
Data p
};
QByteArrayMatcherPrivate * d
QByteArray q_pattern
Detailed Description
The QByteArrayMatcher class holds a sequence of bytes that can be quickly matched in a byte array.
This class is useful when you have a sequence of bytes that you want to repeatedly match against some byte arrays (perhaps in a loop), or when you want to search for the same sequence of bytes multiple times in the same byte array. Using a matcher object and indexIn() is faster than matching a plain QByteArray with QByteArray::indexOf() if repeated matching takes place. This class offers no benefit if you are doing one-off byte array matches.
Create the QByteArrayMatcher with the QByteArray you want to search for. Then call indexIn() on the QByteArray that you want to search.
See also
QByteArray, QStringMatcher
Definition at line 55 of file qbytearraymatcher.h.
Constructors and Destructors
QByteArrayMatcher() [1/4]
QByteArrayMatcher::QByteArrayMatcher ()
Constructs an empty byte array matcher that won't match anything.
Call setPattern() to give it a pattern to match.
Definition at line 122 of file qbytearraymatcher.cpp.
     : d(0)
 {
     p.p = 0;
     p.l = 0;
     qMemSet(p.q_skiptable, 0, sizeof(p.q_skiptable));
 }
QByteArrayMatcher() [2/4]
QByteArrayMatcher::QByteArrayMatcher (const QByteArray & pattern) explicit
Constructs a byte array matcher that will search for pattern.
Call indexIn() to perform a search.
Definition at line 147 of file qbytearraymatcher.cpp.
     : d(0), q_pattern(pattern)
 {
     p.p = reinterpret_cast<const uchar *>(pattern.constData());
     p.l = pattern.size();
     bm_init_skiptable(p.p, p.l, p.q_skiptable);
 }
QByteArrayMatcher() [3/4]
QByteArrayMatcher::QByteArrayMatcher (const char * pattern, int length) explicit
Constructs a byte array matcher from pattern.
pattern has the given length. pattern must remain in scope, but the destructor does not delete pattern.
Definition at line 135 of file qbytearraymatcher.cpp.
     : d(0)
 {
     p.p = reinterpret_cast<const uchar *>(pattern);
     p.l = length;
     bm_init_skiptable(p.p, p.l, p.q_skiptable);
 }
QByteArrayMatcher() [4/4]
QByteArrayMatcher::QByteArrayMatcher (const QByteArrayMatcher & other)
Copies the other byte array matcher to this byte array matcher.
Definition at line 158 of file qbytearraymatcher.cpp.
     : d(0)
 {
     operator=(other);
 }
~QByteArrayMatcher()
QByteArrayMatcher::~QByteArrayMatcher ()
Destroys the byte array matcher.
Definition at line 167 of file qbytearraymatcher.cpp.
 {
 }
Functions
indexIn() [1/2]
int QByteArrayMatcher::indexIn (const QByteArray & ba, int from = 0) const
Searches the byte array ba, from byte position from (default 0, i.e.
from the first byte), for the byte array pattern() that was set in the constructor or in the most recent call to setPattern(). Returns the position where the pattern() matched in ba, or -1 if no match was found.
Definition at line 202 of file qbytearraymatcher.cpp.
Referenced by QByteArray::count(), QHttpNetworkReplyPrivate::parseHeader(), and QByteArray::replace().
 {
     if (from < 0)
         from = 0;
     return bm_find(reinterpret_cast<const uchar *>(ba.constData()), ba.size(), from,
                    p.p, p.l, p.q_skiptable);
 }
indexIn() [2/2]
int QByteArrayMatcher::indexIn (const char * str, int len, int from = 0) const
Searches the char string str, which has length len, from byte position from (default 0, i.e.
from the first byte), for the byte array pattern() that was set in the constructor or in the most recent call to setPattern(). Returns the position where the pattern() matched in str, or -1 if no match was found.
Definition at line 217 of file qbytearraymatcher.cpp.
 {
     if (from < 0)
         from = 0;
     return bm_find(reinterpret_cast<const uchar *>(str), len, from,
                    p.p, p.l, p.q_skiptable);
 }
operator=()
QByteArrayMatcher & QByteArrayMatcher::operator= (const QByteArrayMatcher & other)
Assigns the other byte array matcher to this byte array matcher.
Definition at line 174 of file qbytearraymatcher.cpp.
Referenced by QByteArrayMatcher().
 {
     q_pattern = other.q_pattern;
     memcpy(&p, &other.p, sizeof(p));
     return *this;
 }
pattern()
QByteArray QByteArrayMatcher::pattern () const inline
Returns the byte array pattern that this byte array matcher will search for.
See also
setPattern()
Definition at line 70 of file qbytearraymatcher.h.
Referenced by QByteArrayMatcher(), and setPattern().
     {
         if (q_pattern.isNull())
             return QByteArray(reinterpret_cast<const char*>(p.p), p.l);
         return q_pattern;
     }
setPattern()
void QByteArrayMatcher::setPattern (const QByteArray & pattern)
Sets the byte array that this byte array matcher will search for to pattern.
See also
pattern(), indexIn()
Definition at line 187 of file qbytearraymatcher.cpp.
 {
     q_pattern = pattern;
     p.p = reinterpret_cast<const uchar *>(pattern.constData());
     p.l = pattern.size();
     bm_init_skiptable(p.p, p.l, p.q_skiptable);
 }
Properties
@46
union { ... }
d
QByteArrayMatcherPrivate* QByteArrayMatcher::d private
Definition at line 78 of file qbytearraymatcher.h.
dummy
uint QByteArrayMatcher::dummy[256]
Definition at line 91 of file qbytearraymatcher.h.
p
Data QByteArrayMatcher::p
Definition at line 92 of file qbytearraymatcher.h.
Referenced by indexIn(), operator=(), QByteArrayMatcher(), and setPattern().
q_pattern
QByteArray QByteArrayMatcher::q_pattern private
Definition at line 79 of file qbytearraymatcher.h.
Referenced by operator=(), and setPattern().
The documentation for this class was generated from the following files:
/src/corelib/tools/qbytearraymatcher.h
/src/corelib/tools/qbytearraymatcher.cpp