Qt 4.8: QHash< Key, T >::const_iterator Class Reference
QHash< Key, T >::const_iterator Class Reference
The QHash::const_iterator class provides an STL-style const iterator for QHash and QMultiHash.
#include <qhash.h>
Public Types
typedef qptrdiff difference_type
typedef std::bidirectional_iterator_tag iterator_category
typedef const T * pointer
typedef const T & reference
typedef T value_type
Public Functions
const_iterator ()
Constructs an uninitialized iterator.
const_iterator (void *node)
const_iterator (const iterator &o)
Constructs a copy of other.
const Key & key () const
Returns the current item's key.
operator Node * () const
bool operator!= (const const_iterator &o) const
Returns true if other points to a different item than this iterator; otherwise returns false.
const T & operator* () const
Returns the current item's value.
const_iterator operator+ (int j) const
Returns an iterator to the item at j positions forward from this iterator.
const_iterator & operator++ ()
The prefix ++ operator (++i) advances the iterator to the next item in the hash and returns an iterator to the new current item.
const_iterator operator++ (int)
The postfix ++ operator (i++) advances the iterator to the next item in the hash and returns an iterator to the previously current item.
const_iterator & operator+= (int j)
Advances the iterator by j items.
const_iterator operator- (int j) const
Returns an iterator to the item at j positions backward from this iterator.
const_iterator & operator-- ()
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
const_iterator operator-- (int)
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
const_iterator & operator-= (int j)
Makes the iterator go back by j items.
const T * operator-> () const
Returns a pointer to the current item's value.
bool operator== (const const_iterator &o) const
Returns true if other points to the same item as this iterator; otherwise returns false.
const T & value () const
Returns the current item's value.
Private Functions
operator bool () const
Properties
QHashData::Node * i
Friends
class iterator
Detailed Description
template<class Key, class T>
class QHash< Key, T >::const_iterator
The QHash::const_iterator class provides an STL-style const iterator for QHash and QMultiHash.
QHash features both STL-style iterators and Java-style iterators. The STL-style iterators are more low-level and more cumbersome to use; on the other hand, they are slightly faster and, for developers who already know STL, have the advantage of familiarity.
QHash<Key, T>::const_iterator allows you to iterate over a QHash (or a QMultiHash). If you want to modify the QHash as you iterate over it, you must use QHash::iterator instead. It is generally good practice to use QHash::const_iterator on a non-const QHash as well, unless you need to change the QHash through the iterator. Const iterators are slightly faster, and can improve code readability.
The default QHash::const_iterator constructor creates an uninitialized iterator. You must initialize it using a QHash function like QHash::constBegin(), QHash::constEnd(), or QHash::find() before you can start iterating. Here's a typical loop that prints all the (key, value) pairs stored in a hash:
QHash<QString, int> hash;
hash.insert("January", 1);
hash.insert("February", 2);
...
hash.insert("December", 12);
QHash<QString, int>::const_iterator i;
for (i = hash.constBegin(); i != hash.constEnd(); ++i)
    cout << i.key() << ": " << i.value() << endl;
Unlike QMap, which orders its items by key, QHash stores its items in an arbitrary order. The only guarantee is that items that share the same key (because they were inserted using QHash::insertMulti()) will appear consecutively, from the most recently to the least recently inserted value.
Multiple iterators can be used on the same hash. However, be aware that any modification performed directly on the QHash has the potential of dramatically changing the order in which the items are stored in the hash, as they might cause QHash to rehash its internal data structure. If you need to keep iterators over a long period of time, we recommend that you use QMap rather than QHash.
See also
QHash::iterator, QHashIterator
Definition at line 395 of file qhash.h.
Typedefs
difference_type
template<class Key, class T> QHash< Key, T >::const_iterator::difference_type
Warning
This function is not part of the public interface.
Definition at line 402 of file qhash.h.
iterator_category
template<class Key, class T> QHash< Key, T >::const_iterator::iterator_category
Warning
This function is not part of the public interface.
Definition at line 401 of file qhash.h.
pointer
template<class Key, class T> QHash< Key, T >::const_iterator::pointer
Warning
This function is not part of the public interface.
Definition at line 404 of file qhash.h.
reference
template<class Key, class T> QHash< Key, T >::const_iterator::reference
Warning
This function is not part of the public interface.
Definition at line 405 of file qhash.h.
value_type
template<class Key, class T> QHash< Key, T >::const_iterator::value_type
Warning
This function is not part of the public interface.
Definition at line 403 of file qhash.h.
Constructors and Destructors
const_iterator() [1/3]
template<class Key, class T> QHash< Key, T >::const_iterator::const_iterator () inline
Constructs an uninitialized iterator.
Functions like key(), value(), and operator++() must not be called on an uninitialized iterator. Use operator=() to assign a value to it before using it.
See also
QHash::constBegin() QHash::constEnd()
Definition at line 409 of file qhash.h.
 : i(0) { }
const_iterator() [2/3]
template<class Key, class T> QHash< Key, T >::const_iterator::const_iterator (void * node) inline explicit
Warning
This function is not part of the public interface.
Definition at line 410 of file qhash.h.
             : i(reinterpret_cast<QHashData::Node *>(node)) { }
const_iterator() [3/3]
template<class Key, class T> QHash< Key, T >::const_iterator::const_iterator (const iterator & o) inline
Constructs a copy of other.
Definition at line 415 of file qhash.h.
         { i = o.i; }
Functions
key()
template<class Key, class T> const Key & QHash< Key, T >::const_iterator::key () const inline
Returns the current item's key.
See also
value()
Definition at line 419 of file qhash.h.
Referenced by QStateMachinePrivate::cancelAllDelayedEvents(), QMultiHash< const QGLContext *, GLProgram >::count(), QMultiHash< const QGLContext *, GLProgram >::find(), QMainWindowLayout::fixSizeInUnifiedToolbar(), QApplication::font(), operator<<(), QApplication::palette(), QDeclarativeMetaType::qmlType(), QStateMachinePrivate::restorablesToPropertyList(), QAxScriptManager::scriptNames(), QCss::StyleSelector::styleRulesForNode(), QFont::substitutions(), QGraphicsScenePrivate::touchEventHandler(), QApplicationPrivate::translateRawTouchEvent(), and QAxScriptManager::updateScript().
 { return concrete(i)->key; }
operator bool()
template<class Key, class T> QHash< Key, T >::const_iterator::operator bool () const inline private
Definition at line 459 of file qhash.h.
 { return false; }
operator Node *()
template<class Key, class T> QHash< Key, T >::const_iterator::operator Node * () const inline
Warning
This function is not part of the public interface.
Definition at line 408 of file qhash.h.
 { return concrete(i); }
operator!=()
template<class Key, class T> bool QHash< Key, T >::const_iterator::operator!= (const const_iterator & other) const inline
Returns true if other points to a different item than this iterator; otherwise returns false.
See also
operator==()
Definition at line 424 of file qhash.h.
 { return i != o.i; }
operator*()
template<class Key, class T> const T & QHash< Key, T >::const_iterator::operator* () const inline
Returns the current item's value.
Same as value().
See also
key()
Definition at line 421 of file qhash.h.
 { return concrete(i)->value; }
operator+()
template<class Key, class T> QHash::const_iterator QHash< Key, T >::const_iterator::operator+ (int j) const inline
Returns an iterator to the item at j positions forward from this iterator.
(If j is negative, the iterator goes backward.)
This operation can be slow for large j values.
See also
operator-()
Definition at line 444 of file qhash.h.
         { const_iterator r = *this; if (j > 0) while (j--) ++r; else while (j++) --r; return r; }
operator++() [1/2]
template<class Key, class T> QHash::const_iterator & QHash< Key, T >::const_iterator::operator++ () inline
The prefix ++ operator (++i) advances the iterator to the next item in the hash and returns an iterator to the new current item.
Calling this function on QHash::end() leads to undefined results.
See also
operator--()
Definition at line 426 of file qhash.h.
{
             i = QHashData::nextNode(i);
             return *this;
         }
operator++() [2/2]
template<class Key, class T> QHash::const_iterator QHash< Key, T >::const_iterator::operator++ (int) inline
The postfix ++ operator (i++) advances the iterator to the next item in the hash and returns an iterator to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 430 of file qhash.h.
{
             const_iterator r = *this;
             i = QHashData::nextNode(i);
             return r;
         }
operator+=()
template<class Key, class T> QHash::const_iterator & QHash< Key, T >::const_iterator::operator+= (int j) inline
Advances the iterator by j items.
(If j is negative, the iterator goes backward.)
This operation can be slow for large j values.
See also
operator-=(), operator+()
Definition at line 447 of file qhash.h.
 { return *this = *this + j; }
operator-()
template<class Key, class T> QHash::const_iterator QHash< Key, T >::const_iterator::operator- (int j) const inline
Returns an iterator to the item at j positions backward from this iterator.
(If j is negative, the iterator goes forward.)
This operation can be slow for large j values.
See also
operator+()
Definition at line 446 of file qhash.h.
 { return operator+(-j); }
operator--() [1/2]
template<class Key, class T> QHash::const_iterator & QHash< Key, T >::const_iterator::operator-- () inline
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
Calling this function on QHash::begin() leads to undefined results.
See also
operator++()
Definition at line 435 of file qhash.h.
{
             i = QHashData::previousNode(i);
             return *this;
         }
operator--() [2/2]
template<class Key, class T> QHash::const_iterator QHash< Key, T >::const_iterator::operator-- (int) inline
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 439 of file qhash.h.
{
             const_iterator r = *this;
             i = QHashData::previousNode(i);
             return r;
         }
operator-=()
template<class Key, class T> QHash::const_iterator & QHash< Key, T >::const_iterator::operator-= (int j) inline
Makes the iterator go back by j items.
(If j is negative, the iterator goes forward.)
This operation can be slow for large j values.
See also
operator+=(), operator-()
Definition at line 448 of file qhash.h.
 { return *this = *this - j; }
operator->()
template<class Key, class T> const T * QHash< Key, T >::const_iterator::operator-> () const inline
Returns a pointer to the current item's value.
See also
value()
Definition at line 422 of file qhash.h.
 { return &concrete(i)->value; }
operator==()
template<class Key, class T> bool QHash< Key, T >::const_iterator::operator== (const const_iterator & other) const inline
Returns true if other points to the same item as this iterator; otherwise returns false.
See also
operator!=()
Definition at line 423 of file qhash.h.
 { return i == o.i; }
value()
template<class Key, class T> const T & QHash< Key, T >::const_iterator::value () const inline
Returns the current item's value.
See also
key(), operator*()
Definition at line 420 of file qhash.h.
Referenced by QGLGlyphCache::cacheGlyphs(), QStateMachinePrivate::cancelAllDelayedEvents(), QGLGlyphCache::cleanCache(), cleanup_cmaps(), QBearerEngine::configurationsInUse(), QMultiHash< const QGLContext *, GLProgram >::count(), QMultiHash< const QGLContext *, GLProgram >::find(), QMainWindowLayout::fixSizeInUnifiedToolbar(), QDeclarativeJS::Ecma::RegExp::flagFromChar(), QApplication::font(), QAxScriptManager::functions(), QSortFilterProxyModelPrivate::index_to_iterator(), QScriptDebuggerCodeWidget::invalidateExecutionLineNumbers(), QGLGlyphCache::lookup(), QScriptEnginePrivate::mark(), operator<<(), QApplication::palette(), QScriptEnginePrivate::qobjectData(), qt_gl_choose_cmap(), qt_transparent_pixel(), QEventDispatcherMac::registeredTimers(), QStyleSheetStyle::renderRule(), QStateMachinePrivate::restorablesToPropertyList(), QFileSystemModelPrivate::QFileSystemNode::retranslateStrings(), QDomElementPrivate::save(), QAxScriptManager::scriptForFunction(), QDialogButtonBox::setStandardButtons(), QFileSystemModelPrivate::sortChildren(), QStyleSheetStyle::styleRules(), QCss::StyleSelector::styleRulesForNode(), QApplicationPrivate::translateRawTouchEvent(), QFileSystemModelPrivate::QFileSystemNode::updateIcon(), QFileSystemModelPrivate::QFileSystemNode::~QFileSystemNode(), and QScriptEnginePrivate::~QScriptEnginePrivate().
 { return concrete(i)->value; }
Friends and Related Functions
iterator
template<class Key, class T> friend class iterator friend
Definition at line 397 of file qhash.h.
Properties
i
template<class Key, class T> QHashData::Node* QHash< Key, T >::const_iterator::i private
Definition at line 398 of file qhash.h.
Referenced by QHash< Key, T >::iterator::operator!=(), QHash< Key, T >::const_iterator::operator!=(), QHash< Key, T >::iterator::operator==(), and QHash< Key, T >::const_iterator::operator==().
The documentation for this class was generated from the following files:
/src/corelib/tools/qhash.h
/src/corelib/tools/qhash.cpp