Qt 4.8: QUrlInfoPrivate Class Reference
QUrlInfoPrivate Class Reference
Public Functions
QUrlInfoPrivate ()
Public Variables
QString group
bool isDir
bool isExecutable
bool isFile
bool isReadable
bool isSymLink
bool isWritable
QDateTime lastModified
QDateTime lastRead
QString name
QString owner
int permissions
qint64 size
Detailed Description
Definition at line 52 of file qurlinfo.cpp.
Constructors and Destructors
QUrlInfoPrivate()
QUrlInfoPrivate::QUrlInfoPrivate () inline
Definition at line 55 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator=(), QUrlInfo::QUrlInfo(), QUrlInfo::setDir(), QUrlInfo::setFile(), QUrlInfo::setGroup(), QUrlInfo::setLastModified(), QUrlInfo::setLastRead(), QUrlInfo::setName(), QUrlInfo::setOwner(), QUrlInfo::setPermissions(), QUrlInfo::setReadable(), QUrlInfo::setSize(), QUrlInfo::setSymLink(), and QUrlInfo::setWritable().
                       :
         permissions(0),
         size(0),
         isDir(false),
         isFile(true),
         isSymLink(false),
         isWritable(true),
         isReadable(true),
         isExecutable(false)
     {}
Properties
group
QString QUrlInfoPrivate::group
Definition at line 69 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
isDir
bool QUrlInfoPrivate::isDir
Definition at line 74 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
isExecutable
bool QUrlInfoPrivate::isExecutable
Definition at line 79 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
isFile
bool QUrlInfoPrivate::isFile
Definition at line 75 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
isReadable
bool QUrlInfoPrivate::isReadable
Definition at line 78 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
isSymLink
bool QUrlInfoPrivate::isSymLink
Definition at line 76 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
isWritable
bool QUrlInfoPrivate::isWritable
Definition at line 77 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
lastModified
QDateTime QUrlInfoPrivate::lastModified
Definition at line 72 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
lastRead
QDateTime QUrlInfoPrivate::lastRead
Definition at line 73 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
name
QString QUrlInfoPrivate::name
Definition at line 66 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), QUrlInfo::QUrlInfo(), and QUrlInfo::setName().
owner
QString QUrlInfoPrivate::owner
Definition at line 68 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
permissions
int QUrlInfoPrivate::permissions
Definition at line 67 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), and QUrlInfo::QUrlInfo().
size
qint64 QUrlInfoPrivate::size
Definition at line 70 of file qurlinfo.cpp.
Referenced by QUrlInfo::operator==(), QUrlInfo::QUrlInfo(), and QUrlInfo::setSize().
The documentation for this class was generated from the following file:
/src/network/kernel/qurlinfo.cpp