Qt 4.8: QNetworkAccessAuthenticationManager Class Reference
QNetworkAccessAuthenticationManager Class Reference
#include <qnetworkaccessauthenticationmanager_p.h>
Public Functions
void cacheCredentials (const QUrl &url, const QAuthenticator *auth)
void cacheProxyCredentials (const QNetworkProxy &proxy, const QAuthenticator *auth)
void clearCache ()
QNetworkAuthenticationCredential fetchCachedCredentials (const QUrl &url, const QAuthenticator *auth=0)
Fetch the credential data from the credential cache.
QNetworkAuthenticationCredential fetchCachedProxyCredentials (const QNetworkProxy &proxy, const QAuthenticator *auth=0)
QNetworkAccessAuthenticationManager ()
Protected Variables
QNetworkAccessCache authenticationCache
QMutex mutex
Detailed Description
Definition at line 83 of file qnetworkaccessauthenticationmanager_p.h.
Constructors and Destructors
QNetworkAccessAuthenticationManager()
QNetworkAccessAuthenticationManager::QNetworkAccessAuthenticationManager () inline
Definition at line 86 of file qnetworkaccessauthenticationmanager_p.h.
 { };
Functions
cacheCredentials()
void QNetworkAccessAuthenticationManager::cacheCredentials (const QUrl & url, const QAuthenticator * auth)
Definition at line 228 of file qnetworkaccessauthenticationmanager.cpp.
Referenced by QHttpThreadDelegate::cacheCredentialsSlot().
 {
     Q_ASSERT(authenticator);
     QString domain = QString::fromLatin1("/"); // FIXME: make QAuthenticator return the domain
     QString realm = authenticator->realm();
     QMutexLocker mutexLocker(&mutex);
     // Set two credentials actually: one with and one without the username in the URL
     QUrl copy = url;
     copy.setUserName(authenticator->user());
     do {
         QByteArray cacheKey = authenticationKey(copy, realm);
         if (authenticationCache.hasEntry(cacheKey)) {
             QNetworkAuthenticationCache *auth =
                 static_cast<QNetworkAuthenticationCache *>(authenticationCache.requestEntryNow(cacheKey));
             auth->insert(domain, authenticator->user(), authenticator->password());
             authenticationCache.releaseEntry(cacheKey);
         } else {
             QNetworkAuthenticationCache *auth = new QNetworkAuthenticationCache;
             auth->insert(domain, authenticator->user(), authenticator->password());
             authenticationCache.addEntry(cacheKey, auth);
         }
         if (copy.userName().isEmpty()) {
             break;
         } else {
             copy.setUserName(QString());
         }
     } while (true);
 }
cacheProxyCredentials()
void QNetworkAccessAuthenticationManager::cacheProxyCredentials (const QNetworkProxy & proxy, const QAuthenticator * auth)
Definition at line 150 of file qnetworkaccessauthenticationmanager.cpp.
 {
     Q_ASSERT(authenticator);
     Q_ASSERT(p.type() != QNetworkProxy::DefaultProxy);
     Q_ASSERT(p.type() != QNetworkProxy::NoProxy);
     QMutexLocker mutexLocker(&mutex);
     QString realm = authenticator->realm();
     QNetworkProxy proxy = p;
     proxy.setUser(authenticator->user());
     // don't cache null passwords, empty password may be valid though
     if (authenticator->password().isNull())
         return;
     // Set two credentials: one with the username and one without
     do {
         // Set two credentials actually: one with and one without the realm
         do {
             QByteArray cacheKey = proxyAuthenticationKey(proxy, realm);
             if (cacheKey.isEmpty())
                 return;             // should not happen
             QNetworkAuthenticationCache *auth = new QNetworkAuthenticationCache;
             auth->insert(QString(), authenticator->user(), authenticator->password());
             authenticationCache.addEntry(cacheKey, auth); // replace the existing one, if there's any
             if (realm.isEmpty()) {
                 break;
             } else {
                 realm.clear();
             }
         } while (true);
         if (proxy.user().isEmpty())
             break;
         else
             proxy.setUser(QString());
     } while (true);
 }
clearCache()
void QNetworkAccessAuthenticationManager::clearCache ()
Definition at line 299 of file qnetworkaccessauthenticationmanager.cpp.
 {
     authenticationCache.clear();
 }
fetchCachedCredentials()
QNetworkAuthenticationCredential QNetworkAccessAuthenticationManager::fetchCachedCredentials (const QUrl & url, const QAuthenticator * authentication = 0)
Fetch the credential data from the credential cache.
If auth is 0 (as it is when called from createRequest()), this will try to look up with an empty realm. That fails in most cases for HTTP (because the realm is seldom empty for HTTP challenges). In any case, QHttpNetworkConnection never sends the credentials on the first attempt: it needs to find out what authentication methods the server supports.
For FTP, realm is always empty.
Definition at line 273 of file qnetworkaccessauthenticationmanager.cpp.
Referenced by QHttpThreadDelegate::synchronousAuthenticationRequiredSlot().
 {
     if (!url.password().isEmpty())
         return QNetworkAuthenticationCredential(); // no need to set credentials if it already has them
     QString realm;
     if (authentication)
         realm = authentication->realm();
     QByteArray cacheKey = authenticationKey(url, realm);
     QMutexLocker mutexLocker(&mutex);
     if (!authenticationCache.hasEntry(cacheKey))
         return QNetworkAuthenticationCredential();
     QNetworkAuthenticationCache *auth =
         static_cast<QNetworkAuthenticationCache *>(authenticationCache.requestEntryNow(cacheKey));
     QNetworkAuthenticationCredential *cred = auth->findClosestMatch(url.path());
     QNetworkAuthenticationCredential ret;
     if (cred)
         ret = *cred;
     authenticationCache.releaseEntry(cacheKey);
     return ret;
 }
fetchCachedProxyCredentials()
QNetworkAuthenticationCredential QNetworkAccessAuthenticationManager::fetchCachedProxyCredentials (const QNetworkProxy & proxy, const QAuthenticator * auth = 0)
Definition at line 194 of file qnetworkaccessauthenticationmanager.cpp.
Referenced by QHttpThreadDelegate::synchronousProxyAuthenticationRequiredSlot().
 {
     QNetworkProxy proxy = p;
     if (proxy.type() == QNetworkProxy::DefaultProxy) {
         proxy = QNetworkProxy::applicationProxy();
     }
     if (!proxy.password().isEmpty())
         return QNetworkAuthenticationCredential(); // no need to set credentials if it already has them
     QString realm;
     if (authenticator)
         realm = authenticator->realm();
     QMutexLocker mutexLocker(&mutex);
     QByteArray cacheKey = proxyAuthenticationKey(proxy, realm);
     if (cacheKey.isEmpty())
         return QNetworkAuthenticationCredential();
     if (!authenticationCache.hasEntry(cacheKey))
         return QNetworkAuthenticationCredential();
     QNetworkAuthenticationCache *auth =
         static_cast<QNetworkAuthenticationCache *>(authenticationCache.requestEntryNow(cacheKey));
     QNetworkAuthenticationCredential cred = *auth->findClosestMatch(QString());
     authenticationCache.releaseEntry(cacheKey);
     // proxy cache credentials always have exactly one item
     Q_ASSERT_X(!cred.isNull(), "QNetworkAccessManager",
                "Internal inconsistency: found a cache key for a proxy, but it's empty");
     return cred;
 }
Properties
authenticationCache
QNetworkAccessCache QNetworkAccessAuthenticationManager::authenticationCache protected
Definition at line 101 of file qnetworkaccessauthenticationmanager_p.h.
mutex
QMutex QNetworkAccessAuthenticationManager::mutex protected
Definition at line 102 of file qnetworkaccessauthenticationmanager_p.h.
The documentation for this class was generated from the following files:
/src/network/access/qnetworkaccessauthenticationmanager_p.h
/src/network/access/qnetworkaccessauthenticationmanager.cpp