Qt 4.8: QTextEdit Class Reference
QTextEdit Class Reference
The QTextEdit class provides a widget that is used to edit and display both plain and rich text.
#include <qtextedit.h>
Classes
class ExtraSelection
The QTextEdit::ExtraSelection structure provides a way of specifying a character format for a given selection in a document.
Public Types
enum AutoFormattingFlag { AutoNone = 0, AutoBulletList = 0x00000001, AutoAll = 0xffffffff }
enum LineWrapMode { NoWrap, WidgetWidth, FixedPixelWidth, FixedColumnWidth }
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void append (const QString &text)
Appends a new paragraph with text to the end of the text edit.
void clear ()
Deletes all the text in the text edit.
void copy ()
Copies any selected text to the clipboard.
void cut ()
Copies the selected text to the clipboard and deletes it from the text edit.
void insertHtml (const QString &text)
Convenience slot that inserts text which is assumed to be of html formatting at the current cursor position.
void insertPlainText (const QString &text)
Convenience slot that inserts text at the current cursor position.
void paste ()
Pastes the text from the clipboard into the text edit at the current cursor position.
void redo ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void scrollToAnchor (const QString &name)
Scrolls the text edit so that the anchor with the given name is visible; does nothing if the name is empty, or is already visible, or isn't found.
void selectAll ()
Selects all text.
void setAlignment (Qt::Alignment a)
Sets the alignment of the current paragraph to a.
void setCurrentFont (const QFont &f)
Sets the font of the current format to f.
void setFontFamily (const QString &fontFamily)
Sets the font family of the current format to fontFamily.
void setFontItalic (bool b)
If italic is true, sets the current format to italic; otherwise sets the current format to non-italic.
void setFontPointSize (qreal s)
Sets the point size of the current format to s.
void setFontUnderline (bool b)
If underline is true, sets the current format to underline; otherwise sets the current format to non-underline.
void setFontWeight (int w)
Sets the font weight of the current format to the given weight, where the value used is in the range defined by the QFont::Weight enum.
void setHtml (const QString &text)
void setPlainText (const QString &text)
Changes the text of the text edit to the string text.
void setText (const QString &text)
Sets the text edit's text.
void setTextBackgroundColor (const QColor &c)
Sets the text background color of the current format to c.
void setTextColor (const QColor &c)
Sets the text color of the current format to c.
void undo ()
Undoes the last operation.
void zoomIn (int range=1)
Zooms in on the text by making the base font size range points larger and recalculating all font sizes to be the new size.
void zoomOut (int range=1)
Zooms out on the text by making the base font size range points smaller and recalculating all font sizes to be the new size.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void copyAvailable (bool b)
This signal is emitted when text is selected or de-selected in the text edit.
void currentCharFormatChanged (const QTextCharFormat &format)
This signal is emitted if the current character format has changed, for example caused by a change of the cursor position.
void cursorPositionChanged ()
This signal is emitted whenever the position of the cursor changed.
void redoAvailable (bool b)
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
void selectionChanged ()
This signal is emitted whenever the selection changes.
void textChanged ()
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
void undoAvailable (bool b)
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool acceptRichText () const
Qt::Alignment alignment () const
Returns the alignment of the current paragraph.
QString anchorAt (const QPoint &pos) const
Returns the reference of the anchor at position pos, or an empty string if no anchor exists at that point.
AutoFormatting autoFormatting () const
bool canPaste () const
Returns whether text can be pasted from the clipboard into the textedit.
QMenu * createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the text edit with the right mouse button.
QMenu * createStandardContextMenu (const QPoint &position)
This function creates the standard context menu which is shown when the user clicks on the text edit with the right mouse button.
QTextCharFormat currentCharFormat () const
Returns the char format that is used when inserting new text.
QFont currentFont () const
Returns the font of the current format.
QTextCursor cursorForPosition (const QPoint &pos) const
returns a QTextCursor at position pos (in viewport coordinates).
QRect cursorRect (const QTextCursor &cursor) const
returns a rectangle (in viewport coordinates) that includes the cursor.
QRect cursorRect () const
returns a rectangle (in viewport coordinates) that includes the cursor of the text edit.
int cursorWidth () const
QTextDocument * document () const
Returns a pointer to the underlying document.
QString documentTitle () const
void ensureCursorVisible ()
Ensures that the cursor is visible by scrolling the text edit if necessary.
QList< ExtraSelection > extraSelections () const
Returns previously set extra selections.
bool find (const QString &exp, QTextDocument::FindFlags options=0)
Finds the next occurrence of the string, exp, using the given options.
QString fontFamily () const
Returns the font family of the current format.
bool fontItalic () const
Returns true if the font of the current format is italic; otherwise returns false.
qreal fontPointSize () const
Returns the point size of the font of the current format.
bool fontUnderline () const
Returns true if the font of the current format is underlined; otherwise returns false.
int fontWeight () const
Returns the font weight of the current format.
bool isReadOnly () const
bool isUndoRedoEnabled () const
int lineWrapColumnOrWidth () const
LineWrapMode lineWrapMode () const
virtual QVariant loadResource (int type, const QUrl &name)
Loads the resource specified by the given type and name.
void mergeCurrentCharFormat (const QTextCharFormat &modifier)
Merges the properties specified in modifier into the current character format by calling QTextCursor::mergeCharFormat on the editor's cursor.
void moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode=QTextCursor::MoveAnchor)
Moves the cursor by performing the given operation.
bool overwriteMode () const
void print (QPrinter *printer) const
Convenience function to print the text edit's document to the given printer.
QTextEdit (QWidget *parent=0)
Constructs an empty QTextEdit with parent parent.
QTextEdit (const QString &text, QWidget *parent=0)
Constructs a QTextEdit with parent parent.
void setAcceptRichText (bool accept)
void setAutoFormatting (AutoFormatting features)
void setCurrentCharFormat (const QTextCharFormat &format)
Sets the char format that is be used when inserting new text to format by calling QTextCursor::setCharFormat() on the editor's cursor.
void setCursorWidth (int width)
void setDocument (QTextDocument *document)
Makes document the new document of the text editor.
void setDocumentTitle (const QString &title)
void setExtraSelections (const QList< ExtraSelection > &selections)
This function allows temporarily marking certain regions in the document with a given color, specified as selections.
void setLineWrapColumnOrWidth (int w)
void setLineWrapMode (LineWrapMode mode)
void setOverwriteMode (bool overwrite)
void setReadOnly (bool ro)
void setTabChangesFocus (bool b)
void setTabStopWidth (int width)
void setTextCursor (const QTextCursor &cursor)
Sets the visible cursor.
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
void setUndoRedoEnabled (bool enable)
void setWordWrapMode (QTextOption::WrapMode policy)
bool tabChangesFocus () const
int tabStopWidth () const
QColor textBackgroundColor () const
Returns the text background color of the current format.
QColor textColor () const
Returns the text color of the current format.
QTextCursor textCursor () const
Returns a copy of the QTextCursor that represents the currently visible cursor.
Qt::TextInteractionFlags textInteractionFlags () const
QString toHtml () const
QString toPlainText () const
Returns the text of the text edit as plain text.
QTextOption::WrapMode wordWrapMode () const
the mode QTextEdit will use when wrapping text by words
virtual ~QTextEdit ()
Destructor.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
virtual bool canInsertFromMimeData (const QMimeData *source) const
This function returns true if the contents of the MIME data object, specified by source, can be decoded and inserted into the document.
virtual void changeEvent (QEvent *e)
Reimplemented Function
virtual void contextMenuEvent (QContextMenuEvent *e)
Shows the standard context menu created with createStandardContextMenu().
virtual QMimeData * createMimeDataFromSelection () const
This function returns a new MIME data object to represent the contents of the text edit's current selection.
virtual void dragEnterEvent (QDragEnterEvent *e)
Reimplemented Function
virtual void dragLeaveEvent (QDragLeaveEvent *e)
Reimplemented Function
virtual void dragMoveEvent (QDragMoveEvent *e)
Reimplemented Function
virtual void dropEvent (QDropEvent *e)
Reimplemented Function
virtual bool event (QEvent *e)
virtual void focusInEvent (QFocusEvent *e)
Reimplemented Function
virtual bool focusNextPrevChild (bool next)
Reimplemented Function
virtual void focusOutEvent (QFocusEvent *e)
Reimplemented Function
virtual void inputMethodEvent (QInputMethodEvent *)
Reimplemented Function
QVariant inputMethodQuery (Qt::InputMethodQuery property) const
This method is only relevant for input widgets.
virtual void insertFromMimeData (const QMimeData *source)
This function inserts the contents of the MIME data object, specified by source, into the text edit at the current cursor position.
virtual void keyPressEvent (QKeyEvent *e)
Reimplemented Function
virtual void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
virtual void mouseDoubleClickEvent (QMouseEvent *e)
Reimplemented Function
virtual void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
virtual void mousePressEvent (QMouseEvent *e)
Reimplemented Function
virtual void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
virtual void paintEvent (QPaintEvent *e)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QTextEdit (QTextEditPrivate &dd, QWidget *parent)
virtual void resizeEvent (QResizeEvent *e)
Reimplemented Function
virtual void scrollContentsBy (int dx, int dy)
em>Reimplemented Function
virtual void showEvent (QShowEvent *)
Reimplemented Function
virtual void timerEvent (QTimerEvent *e)
virtual void wheelEvent (QWheelEvent *e)
Reimplemented Function
Protected Functions inherited from QAbstractScrollArea
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
virtual bool viewportEvent (QEvent *)
The main event handler for the scrolling area (the viewport() widget).
Protected Functions inherited from QFrame
void drawFrame (QPainter *)
em>Reimplemented Function
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool acceptRichText
whether the text edit accepts rich text insertions by the user
AutoFormatting autoFormatting
the enabled set of auto formatting features
int cursorWidth
This property specifies the width of the cursor in pixels.
QString documentTitle
the title of the document parsed from the text.
QString html
This property provides an HTML interface to the text of the text edit.
int lineWrapColumnOrWidth
the position (in pixels or columns depending on the wrap mode) where text will be wrapped
LineWrapMode lineWrapMode
the line wrap mode
bool overwriteMode
whether text entered by the user will overwrite existing text
QString plainText
This property gets and sets the text editor's contents as plain text.
bool readOnly
whether the text edit is read-only
bool tabChangesFocus
whether Tab changes focus or is accepted as input
int tabStopWidth
the tab stop width in pixels
Qt::TextInteractionFlags textInteractionFlags
Specifies how the widget should interact with user input.
bool undoRedoEnabled
whether undo and redo are enabled
Friends
class QTextControl
class QTextDocument
class QTextEditControl
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTextEdit class provides a widget that is used to edit and display both plain and rich text.
Introduction and Concepts
QTextEdit is an advanced WYSIWYG viewer/editor supporting rich text formatting using HTML-style tags. It is optimized to handle large documents and to respond quickly to user input.
QTextEdit works on paragraphs and characters. A paragraph is a formatted string which is word-wrapped to fit into the width of the widget. By default when reading plain text, one newline signifies a paragraph. A document consists of zero or more paragraphs. The words in the paragraph are aligned in accordance with the paragraph's alignment. Paragraphs are separated by hard line breaks. Each character within a paragraph has its own attributes, for example, font and color.
QTextEdit can display images, lists and tables. If the text is too large to view within the text edit's viewport, scroll bars will appear. The text edit can load both plain text and HTML files (a subset of HTML 3.2 and 4).
If you just need to display a small piece of rich text use QLabel.
The rich text support in Qt is designed to provide a fast, portable and efficient way to add reasonable online help facilities to applications, and to provide a basis for rich text editors. If you find the HTML support insufficient for your needs you may consider the use of QtWebKit, which provides a full-featured web browser widget.
The shape of the mouse cursor on a QTextEdit is Qt::IBeamCursor by default. It can be changed through the viewport()'s cursor property.
Using QTextEdit as a Display Widget
QTextEdit can display a large HTML subset, including tables and images.
The text is set or replaced using setHtml() which deletes any existing text and replaces it with the text passed in the setHtml() call. If you call setHtml() with legacy HTML, and then call toHtml(), the text that is returned may have different markup, but will render the same. The entire text can be deleted with clear().
Text itself can be inserted using the QTextCursor class or using the convenience functions insertHtml(), insertPlainText(), append() or paste(). QTextCursor is also able to insert complex objects like tables or lists into the document, and it deals with creating selections and applying changes to selected text.
By default the text edit wraps words at whitespace to fit within the text edit widget. The setLineWrapMode() function is used to specify the kind of line wrap you want, or NoWrap if you don't want any wrapping. Call setLineWrapMode() to set a fixed pixel width FixedPixelWidth , or character column (e.g. 80 column) FixedColumnWidth with the pixels or columns specified with setLineWrapColumnOrWidth(). If you use word wrap to the widget's width WidgetWidth , you can specify whether to break on whitespace or anywhere with setWordWrapMode().
The find() function can be used to find and select a given string within the text.
If you want to limit the total number of paragraphs in a QTextEdit, as for example it is often useful in a log viewer, then you can use QTextDocument's maximumBlockCount property for that.
Read-only Key Bindings
When QTextEdit is used read-only the key bindings are limited to navigation, and text may only be selected with the mouse:
Keypresses Action
Up Moves one line up.
Down Moves one line down.
Left Moves one character to the left.
Right Moves one character to the right.
PageUp Moves one (viewport) page up.
PageDown Moves one (viewport) page down.
Home Moves to the beginning of the text.
End Moves to the end of the text.
Alt+Wheel Scrolls the page horizontally (the Wheel is the mouse wheel).
Ctrl+Wheel Zooms the text.
Ctrl+A Selects all text.
The text edit may be able to provide some meta-information. For example, the documentTitle() function will return the text from within HTML <title> tags.
Using QTextEdit as an Editor
All the information about using QTextEdit as a display widget also applies here.
The current char format's attributes are set with setFontItalic(), setFontWeight(), setFontUnderline(), setFontFamily(), setFontPointSize(), setTextColor() and setCurrentFont(). The current paragraph's alignment is set with setAlignment().
Selection of text is handled by the QTextCursor class, which provides functionality for creating selections, retrieving the text contents or deleting selections. You can retrieve the object that corresponds with the user-visible cursor using the textCursor() method. If you want to set a selection in QTextEdit just create one on a QTextCursor object and then make that cursor the visible cursor using setTextCursor(). The selection can be copied to the clipboard with copy(), or cut to the clipboard with cut(). The entire text can be selected using selectAll().
When the cursor is moved and the underlying formatting attributes change, the currentCharFormatChanged() signal is emitted to reflect the new attributes at the new cursor position.
QTextEdit holds a QTextDocument object which can be retrieved using the document() method. You can also set your own document object using setDocument(). QTextDocument emits a textChanged() signal if the text changes and it also provides a isModified() function which will return true if the text has been modified since it was either loaded or since the last call to setModified with false as argument. In addition it provides methods for undo and redo.
Drag and Drop
QTextEdit also supports custom drag and drop behavior. By default, QTextEdit will insert plain text, HTML and rich text when the user drops data of these MIME types onto a document. Reimplement canInsertFromMimeData() and insertFromMimeData() to add support for additional MIME types.
For example, to allow the user to drag and drop an image onto a QTextEdit, you could the implement these functions in the following way:
bool TextEdit::canInsertFromMimeData(const QMimeData *source) const
{
    if (source->hasImage())
        return true;
    else
        return QTextEdit::canInsertFromMimeData(source);
}
We add support for image MIME types by returning true. For all other MIME types, we use the default implementation.
void TextEdit::insertFromMimeData(const QMimeData *source)
{
    if (source->hasImage())
    {
        QImage image = qvariant_cast<QImage>(source->imageData());
        QTextCursor cursor = this->textCursor();
        QTextDocument *document = this->document();
        document->addResource(QTextDocument::ImageResource, QUrl("image"), image);
        cursor.insertImage("image");
    }
}
We unpack the image from the QVariant held by the MIME source and insert it into the document as a resource.
Editing Key Bindings
The list of key bindings which are implemented for editing:
Keypresses Action
Backspace Deletes the character to the left of the cursor.
Delete Deletes the character to the right of the cursor.
Ctrl+C Copy the selected text to the clipboard.
Ctrl+Insert Copy the selected text to the clipboard.
Ctrl+K Deletes to the end of the line.
Ctrl+V Pastes the clipboard text into text edit.
Shift+Insert Pastes the clipboard text into text edit.
Ctrl+X Deletes the selected text and copies it to the clipboard.
Shift+Delete Deletes the selected text and copies it to the clipboard.
Ctrl+Z Undoes the last operation.
Ctrl+Y Redoes the last operation.
Left Moves the cursor one character to the left.
Ctrl+Left Moves the cursor one word to the left.
Right Moves the cursor one character to the right.
Ctrl+Right Moves the cursor one word to the right.
Up Moves the cursor one line up.
Down Moves the cursor one line down.
PageUp Moves the cursor one page up.
PageDown Moves the cursor one page down.
Home Moves the cursor to the beginning of the line.
Ctrl+Home Moves the cursor to the beginning of the text.
End Moves the cursor to the end of the line.
Ctrl+End Moves the cursor to the end of the text.
Alt+Wheel Scrolls the page horizontally (the Wheel is the mouse wheel).
To select (mark) text hold down the Shift key whilst pressing one of the movement keystrokes, for example, Shift+Right will select the character to the right, and Shift+Ctrl+Right will select the word to the right, etc.
See also
QTextDocument, QTextCursor, {Application Example}, {Syntax Highlighter Example}, {Rich Text Processing}
Definition at line 70 of file qtextedit.h.
Enumerations
AutoFormattingFlag
enum QTextEdit::AutoFormattingFlag
AutoNone Don't do any automatic formatting.
AutoBulletList Automatically create bullet lists (e.g. when the user enters an asterisk ('*') in the left most column, or presses Enter in an existing list item.
AutoAll Apply all automatic formatting. Currently only automatic bullet lists are supported.
Enumerator
AutoNone
AutoBulletList
AutoAll
Definition at line 101 of file qtextedit.h.
{
         AutoNone = 0,
         AutoBulletList = 0x00000001,
         AutoAll = 0xffffffff
     };
LineWrapMode
enum QTextEdit::LineWrapMode
NoWrap
WidgetWidth
FixedPixelWidth
FixedColumnWidth
Enumerator
NoWrap
WidgetWidth
FixedPixelWidth
FixedColumnWidth
Definition at line 94 of file qtextedit.h.
                       {
         NoWrap,
         WidgetWidth,
         FixedPixelWidth,
         FixedColumnWidth
     };
Constructors and Destructors
QTextEdit() [1/3]
QTextEdit::QTextEdit (QWidget * parent = 0) explicit
Constructs an empty QTextEdit with parent parent.
Definition at line 608 of file qtextedit.cpp.
Referenced by QTextBrowser::QTextBrowser(), and QTextEdit().
     : QAbstractScrollArea(*new QTextEditPrivate, parent)
 {
     Q_D(QTextEdit);
     d->init();
 }
QTextEdit() [2/3]
QTextEdit::QTextEdit (const QString & text, QWidget * parent = 0) explicit
Constructs a QTextEdit with parent parent.
The text edit will display the text text. The text is interpreted as html.
Definition at line 629 of file qtextedit.cpp.
     : QAbstractScrollArea(*new QTextEditPrivate, parent)
 {
     Q_D(QTextEdit);
     d->init(text);
 }
~QTextEdit()
QTextEdit::~QTextEdit () virtual
Destructor.
Definition at line 654 of file qtextedit.cpp.
 {
 }
QTextEdit() [3/3]
QTextEdit::QTextEdit (QTextEditPrivate & dd, QWidget * parent) protected
Warning
This function is not part of the public interface.
Definition at line 618 of file qtextedit.cpp.
     : QAbstractScrollArea(dd, parent)
 {
     Q_D(QTextEdit);
     d->init();
 }
Functions
acceptRichText()
bool QTextEdit::acceptRichText () const
Referenced by setCursorWidth().
alignment()
Qt::Alignment QTextEdit::alignment () const
Returns the alignment of the current paragraph.
See also
setAlignment()
Definition at line 774 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().blockFormat().alignment();
 }
anchorAt()
QString QTextEdit::anchorAt (const QPoint & pos) const
Returns the reference of the anchor at position pos, or an empty string if no anchor exists at that point.
Definition at line 1901 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->anchorAt(d->mapToContents(pos));
 }
append
void QTextEdit::append (const QString & text) slot
Appends a new paragraph with text to the end of the text edit.
Note
The new paragraph appended will have the same character format and block format as the current paragraph, determined by the position of the cursor.
See also
currentCharFormat(), QTextCursor::blockFormat()
Definition at line 2729 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     const bool atBottom = isReadOnly() ?  d->verticalOffset() >= d->vbar->maximum() :
             d->control->textCursor().atEnd();
     d->control->append(text);
     if (atBottom)
         d->vbar->setValue(d->vbar->maximum());
 }
autoFormatting()
AutoFormatting QTextEdit::autoFormatting () const
Referenced by currentCharFormat().
canInsertFromMimeData()
bool QTextEdit::canInsertFromMimeData (const QMimeData * source) const protected virtual
This function returns true if the contents of the MIME data object, specified by source, can be decoded and inserted into the document.
It is called for example when during a drag operation the mouse enters this widget and it is necessary to determine whether it is possible to accept the drag and drop operation.
Reimplement this function to enable drag and drop support for additional MIME types.
Definition at line 2093 of file qtextedit.cpp.
Referenced by QTextEditControl::canInsertFromMimeData().
 {
     Q_D(const QTextEdit);
     return d->control->QTextControl::canInsertFromMimeData(source);
 }
canPaste()
bool QTextEdit::canPaste () const
Returns whether text can be pasted from the clipboard into the textedit.
Since
4.2
Definition at line 2362 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->canPaste();
 }
changeEvent()
void QTextEdit::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QFrame.
Definition at line 1782 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     QAbstractScrollArea::changeEvent(e);
     if (e->type() == QEvent::ApplicationFontChange
         || e->type() == QEvent::FontChange) {
         d->control->document()->setDefaultFont(font());
     }  else if(e->type() == QEvent::ActivationChange) {
         if (!isActiveWindow())
             d->autoScrollTimer.stop();
     } else if (e->type() == QEvent::EnabledChange) {
         e->setAccepted(isEnabled());
         d->control->setPalette(palette());
         d->sendControlEvent(e);
     } else if (e->type() == QEvent::PaletteChange) {
         d->control->setPalette(palette());
     } else if (e->type() == QEvent::LayoutDirectionChange) {
         d->sendControlEvent(e);
     }
 }
clear
void QTextEdit::clear () slot
Deletes all the text in the text edit.
Note that the undo/redo history is cleared by this function.
See also
cut() setPlainText() setHtml()
Definition at line 1050 of file qtextedit.cpp.
Referenced by timerEvent().
 {
     Q_D(QTextEdit);
     // clears and sets empty content
     d->control->clear();
 }
contextMenuEvent()
void QTextEdit::contextMenuEvent (QContextMenuEvent * event) protected virtual
Shows the standard context menu created with createStandardContextMenu().
If you do not want the text edit to have a context menu, you can set its contextMenuPolicy to Qt::NoContextMenu. If you want to customize the context menu, reimplement this function. If you want to extend the standard context menu, reimplement this function, call createStandardContextMenu() and extend the menu returned.
Information about the event is passed in the event object.
void MyTextEdit::contextMenuEvent(QContextMenuEvent *event)
{
    QMenu *menu = createStandardContextMenu();
    menu->addAction(tr("My Menu Item"));
    //...
    menu->exec(event->globalPos());
    delete menu;
}
Reimplemented from QAbstractScrollArea.
Reimplemented in QMessageBoxDetailsText::TextEdit.
Definition at line 1651 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->sendControlEvent(e);
 }
copy
void QTextEdit::copy () slot
Copies any selected text to the clipboard.
See also
copyAvailable()
Definition at line 1016 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->copy();
 }
copyAvailable
void QTextEdit::copyAvailable (bool yes) signal
This signal is emitted when text is selected or de-selected in the text edit.
When text is selected this signal will be emitted with yes set to true. If no text has been selected or if the selected text is de-selected this signal is emitted with yes set to false.
If yes is true then copy() can be used to copy the selection to the clipboard. If yes is false then copy() does nothing.
See also
selectionChanged()
createMimeDataFromSelection()
QMimeData * QTextEdit::createMimeDataFromSelection () const protected virtual
This function returns a new MIME data object to represent the contents of the text edit's current selection.
It is called when the selection needs to be encapsulated into a new QMimeData object; for example, when a drag and drop operation is started, or when data is copyied to the clipboard.
If you reimplement this function, note that the ownership of the returned QMimeData object is passed to the caller. The selection can be retrieved by using the textCursor() function.
Definition at line 2078 of file qtextedit.cpp.
Referenced by QTextEditControl::createMimeDataFromSelection().
 {
     Q_D(const QTextEdit);
     return d->control->QTextControl::createMimeDataFromSelection();
 }
createStandardContextMenu() [1/2]
QMenu * QTextEdit::createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the text edit with the right mouse button.
It is called from the default contextMenuEvent() handler. The popup menu's ownership is transferred to the caller.
We recommend that you use the createStandardContextMenu(QPoint) version instead which will enable the actions that are sensitive to where the user clicked.
Definition at line 1834 of file qtextedit.cpp.
Referenced by QMessageBoxDetailsText::TextEdit::contextMenuEvent().
 {
     Q_D(QTextEdit);
     return d->control->createStandardContextMenu(QPointF(), this);
 }
createStandardContextMenu() [2/2]
QMenu * QTextEdit::createStandardContextMenu (const QPoint & position)
This function creates the standard context menu which is shown when the user clicks on the text edit with the right mouse button.
Since
4.4 It is called from the default contextMenuEvent() handler and it takes the position of where the mouse click was. This can enable actions that are sensitive to the position where the user clicked. The popup menu's ownership is transferred to the caller.
Definition at line 1853 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     return d->control->createStandardContextMenu(position, this);
 }
currentCharFormat()
QTextCharFormat QTextEdit::currentCharFormat () const
Returns the char format that is used when inserting new text.
Definition at line 2204 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->currentCharFormat();
 }
currentCharFormatChanged
void QTextEdit::currentCharFormatChanged (const QTextCharFormat & f) signal
This signal is emitted if the current character format has changed, for example caused by a change of the cursor position.
The new format is f.
See also
setCurrentCharFormat()
currentFont()
QFont QTextEdit::currentFont () const
Returns the font of the current format.
See also
setCurrentFont() setFontFamily() setFontPointSize()
Definition at line 747 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().font();
 }
cursorForPosition()
QTextCursor QTextEdit::cursorForPosition (const QPoint & pos) const
returns a QTextCursor at position pos (in viewport coordinates).
Definition at line 1863 of file qtextedit.cpp.
Referenced by QAccessibleTextEdit::childAt().
 {
     Q_D(const QTextEdit);
     return d->control->cursorForPosition(d->mapToContents(pos));
 }
cursorPositionChanged
void QTextEdit::cursorPositionChanged () signal
This signal is emitted whenever the position of the cursor changed.
cursorRect() [1/2]
QRect QTextEdit::cursorRect (const QTextCursor & cursor) const
returns a rectangle (in viewport coordinates) that includes the cursor.
Definition at line 1873 of file qtextedit.cpp.
Referenced by QAccessibleTextEdit::scrollToSubstring().
 {
     Q_D(const QTextEdit);
     if (cursor.isNull())
         return QRect();
     QRect r = d->control->cursorRect(cursor).toRect();
     r.translate(-d->horizontalOffset(),-d->verticalOffset());
     return r;
 }
cursorRect() [2/2]
QRect QTextEdit::cursorRect () const
returns a rectangle (in viewport coordinates) that includes the cursor of the text edit.
Definition at line 1888 of file qtextedit.cpp.
Referenced by event().
 {
     Q_D(const QTextEdit);
     QRect r = d->control->cursorRect().toRect();
     r.translate(-d->horizontalOffset(),-d->verticalOffset());
     return r;
 }
cursorWidth()
int QTextEdit::cursorWidth () const
Referenced by setTabStopWidth().
cut
void QTextEdit::cut () slot
Copies the selected text to the clipboard and deletes it from the text edit.
If there is no selected text nothing happens.
See also
copy() paste()
Definition at line 1004 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->cut();
 }
document()
QTextDocument * QTextEdit::document () const
Returns a pointer to the underlying document.
See also
setDocument()
Definition at line 804 of file qtextedit.cpp.
Referenced by QAccessibleTextEdit::childCount(), keyPressEvent(), QSyntaxHighlighter::QSyntaxHighlighter(), QAccessibleTextEdit::rect(), QAccessibleTextEdit::scrollToSubstring(), and QAccessibleTextEdit::textDocument().
 {
     Q_D(const QTextEdit);
     return d->control->document();
 }
documentTitle()
QString QTextEdit::documentTitle () const inline
Definition at line 170 of file qtextedit.h.
Referenced by QTextBrowser::setSource().
     { return document()->metaInformation(QTextDocument::DocumentTitle); }
dragEnterEvent()
void QTextEdit::dragEnterEvent (QDragEnterEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1661 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->inDrag = true;
     d->sendControlEvent(e);
 }
dragLeaveEvent()
void QTextEdit::dragLeaveEvent (QDragLeaveEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1670 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->inDrag = false;
     d->autoScrollTimer.stop();
     d->sendControlEvent(e);
 }
dragMoveEvent()
void QTextEdit::dragMoveEvent (QDragMoveEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1680 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->autoScrollDragPos = e->pos();
     if (!d->autoScrollTimer.isActive())
         d->autoScrollTimer.start(100, this);
     d->sendControlEvent(e);
 }
dropEvent()
void QTextEdit::dropEvent (QDropEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1691 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->inDrag = false;
     d->autoScrollTimer.stop();
     d->sendControlEvent(e);
 }
ensureCursorVisible()
void QTextEdit::ensureCursorVisible ()
Ensures that the cursor is visible by scrolling the text edit if necessary.
Definition at line 2743 of file qtextedit.cpp.
Referenced by event(), inputMethodEvent(), mouseReleaseEvent(), and showEvent().
 {
     Q_D(QTextEdit);
     d->control->ensureCursorVisible();
 }
event()
bool QTextEdit::event (QEvent * e) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractScrollArea.
Reimplemented in QTextBrowser.
Definition at line 1071 of file qtextedit.cpp.
Referenced by QTextBrowser::event().
 {
     Q_D(QTextEdit);
 #ifndef QT_NO_CONTEXTMENU
     if (e->type() == QEvent::ContextMenu
         && static_cast<QContextMenuEvent *>(e)->reason() == QContextMenuEvent::Keyboard) {
         Q_D(QTextEdit);
         ensureCursorVisible();
         const QPoint cursorPos = cursorRect().center();
         QContextMenuEvent ce(QContextMenuEvent::Keyboard, cursorPos, d->viewport->mapToGlobal(cursorPos));
         ce.setAccepted(e->isAccepted());
         const bool result = QAbstractScrollArea::event(&ce);
         e->setAccepted(ce.isAccepted());
         return result;
     } else if (e->type() == QEvent::ShortcutOverride
                || e->type() == QEvent::ToolTip) {
         d->sendControlEvent(e);
     }
 #endif // QT_NO_CONTEXTMENU
 #ifdef QT_KEYPAD_NAVIGATION
     if (e->type() == QEvent::EnterEditFocus || e->type() == QEvent::LeaveEditFocus) {
         if (QApplication::keypadNavigationEnabled())
             d->sendControlEvent(e);
     }
 #endif
     return QAbstractScrollArea::event(e);
 }
extraSelections()
QList< QTextEdit::ExtraSelection > QTextEdit::extraSelections () const
Returns previously set extra selections.
Since
4.2
See also
setExtraSelections()
Definition at line 2062 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->extraSelections();
 }
find()
bool QTextEdit::find (const QString & exp, QTextDocument::FindFlags options = 0)
Finds the next occurrence of the string, exp, using the given options.
Use the find() overload that takes a QTextDocument::FindFlags argument.
Returns true if exp was found and changes the cursor to select the match; otherwise returns false.
Definition at line 2518 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     return d->control->find(exp, options);
 }
focusInEvent()
void QTextEdit::focusInEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1746 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (e->reason() == Qt::MouseFocusReason) {
         d->clickCausedFocus = 1;
     }
     QAbstractScrollArea::focusInEvent(e);
     d->sendControlEvent(e);
 }
focusNextPrevChild()
bool QTextEdit::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QTextBrowser.
Definition at line 1627 of file qtextedit.cpp.
Referenced by QTextBrowser::focusNextPrevChild().
 {
     Q_D(const QTextEdit);
     if (!d->tabChangesFocus && d->control->textInteractionFlags() & Qt::TextEditable)
         return false;
     return QAbstractScrollArea::focusNextPrevChild(next);
 }
focusOutEvent()
void QTextEdit::focusOutEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QTextBrowser.
Definition at line 1758 of file qtextedit.cpp.
Referenced by QTextBrowser::focusOutEvent().
 {
     Q_D(QTextEdit);
     QAbstractScrollArea::focusOutEvent(e);
     d->sendControlEvent(e);
 }
fontFamily()
QString QTextEdit::fontFamily () const
Returns the font family of the current format.
See also
setFontFamily() setCurrentFont() setFontPointSize()
Definition at line 674 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().fontFamily();
 }
fontItalic()
bool QTextEdit::fontItalic () const
Returns true if the font of the current format is italic; otherwise returns false.
See also
setFontItalic()
Definition at line 709 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().fontItalic();
 }
fontPointSize()
qreal QTextEdit::fontPointSize () const
Returns the point size of the font of the current format.
See also
setFontFamily() setCurrentFont() setFontPointSize()
Definition at line 663 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().fontPointSize();
 }
fontUnderline()
bool QTextEdit::fontUnderline () const
Returns true if the font of the current format is underlined; otherwise returns false.
See also
setFontUnderline()
Definition at line 697 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().fontUnderline();
 }
fontWeight()
int QTextEdit::fontWeight () const
Returns the font weight of the current format.
See also
setFontWeight() setCurrentFont() setFontPointSize() QFont::Weight
Definition at line 685 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().fontWeight();
 }
inputMethodEvent()
void QTextEdit::inputMethodEvent (QInputMethodEvent * e) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1703 of file qtextedit.cpp.
inputMethodQuery()
QVariant QTextEdit::inputMethodQuery (Qt::InputMethodQuery query) const protected virtual
This method is only relevant for input widgets.
It is used by the input method to query a set of properties of the widget to be able to support complex input method operations as support for surrounding text and reconversions.
query specifies which property is queried.
See also
inputMethodEvent(), QInputMethodEvent, QInputContext, inputMethodHints
Reimplemented from QWidget.
Definition at line 1728 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     QVariant v = d->control->inputMethodQuery(property);
     const QPoint offset(-d->horizontalOffset(), -d->verticalOffset());
     if (v.type() == QVariant::RectF)
         v = v.toRectF().toRect().translated(offset);
     else if (v.type() == QVariant::PointF)
         v = v.toPointF().toPoint() + offset;
     else if (v.type() == QVariant::Rect)
         v = v.toRect().translated(offset);
     else if (v.type() == QVariant::Point)
         v = v.toPoint() + offset;
     return v;
 }
insertFromMimeData()
void QTextEdit::insertFromMimeData (const QMimeData * source) protected virtual
This function inserts the contents of the MIME data object, specified by source, into the text edit at the current cursor position.
It is called whenever text is inserted as the result of a clipboard paste operation, or when the text edit accepts data from a drag and drop operation.
Reimplement this function to enable drag and drop support for additional MIME types.
Definition at line 2108 of file qtextedit.cpp.
Referenced by QTextEditControl::insertFromMimeData().
 {
     Q_D(QTextEdit);
     d->control->QTextControl::insertFromMimeData(source);
 }
insertHtml
void QTextEdit::insertHtml (const QString & text) slot
Convenience slot that inserts text which is assumed to be of html formatting at the current cursor position.
It is equivalent to:
edit->textCursor().insertHtml(fragment);
Note
When using this function with a style sheet, the style sheet will only apply to the current block in the document. In order to apply a style sheet throughout a document, use QTextDocument::setDefaultStyleSheet() instead.
Definition at line 2265 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->insertHtml(text);
 }
insertPlainText
void QTextEdit::insertPlainText (const QString & text) slot
Convenience slot that inserts text at the current cursor position.
It is equivalent to
edit->textCursor().insertText(text);
Definition at line 2245 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->insertPlainText(text);
 }
isReadOnly()
bool QTextEdit::isReadOnly () const
Definition at line 2127 of file qtextedit.cpp.
Referenced by append(), mouseReleaseEvent(), and shouldEnableInputMethod().
 {
     Q_D(const QTextEdit);
     return !(d->control->textInteractionFlags() & Qt::TextEditable);
 }
isUndoRedoEnabled()
bool QTextEdit::isUndoRedoEnabled () const inline
Definition at line 173 of file qtextedit.h.
     { return document()->isUndoRedoEnabled(); }
keyPressEvent()
void QTextEdit::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Reimplemented in QTextBrowser.
Definition at line 1210 of file qtextedit.cpp.
Referenced by QTextBrowser::keyPressEvent().
 {
     Q_D(QTextEdit);
 #ifdef QT_KEYPAD_NAVIGATION
     switch (e->key()) {
         case Qt::Key_Select:
             if (QApplication::keypadNavigationEnabled()) {
                 // code assumes linksaccessible + editable isn't meaningful
                 if (d->control->textInteractionFlags() & Qt::TextEditable) {
                     setEditFocus(!hasEditFocus());
                 } else {
                     if (!hasEditFocus())
                         setEditFocus(true);
                     else {
                         QTextCursor cursor = d->control->textCursor();
                         QTextCharFormat charFmt = cursor.charFormat();
                         if (!(d->control->textInteractionFlags() & Qt::LinksAccessibleByKeyboard)
                             || !cursor.hasSelection() || charFmt.anchorHref().isEmpty()) {
                             e->accept();
                             return;
                         }
                     }
                 }
             }
             break;
         case Qt::Key_Back:
         case Qt::Key_No:
             if (!QApplication::keypadNavigationEnabled()
                     || (QApplication::keypadNavigationEnabled() && !hasEditFocus())) {
                 e->ignore();
                 return;
             }
             break;
         default:
             if (QApplication::keypadNavigationEnabled()) {
                 if (!hasEditFocus() && !(e->modifiers() & Qt::ControlModifier)) {
                     if (e->text()[0].isPrint())
                         setEditFocus(true);
                     else {
                         e->ignore();
                         return;
                     }
                 }
             }
             break;
     }
 #endif
 #ifndef QT_NO_SHORTCUT
     Qt::TextInteractionFlags tif = d->control->textInteractionFlags();
     if (tif & Qt::TextSelectableByKeyboard){
         if (e == QKeySequence::SelectPreviousPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Up, QTextCursor::KeepAnchor);
             return;
         } else if (e ==QKeySequence::SelectNextPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Down, QTextCursor::KeepAnchor);
             return;
         }
     }
     if (tif & (Qt::TextSelectableByKeyboard | Qt::TextEditable)) {
         if (e == QKeySequence::MoveToPreviousPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Up, QTextCursor::MoveAnchor);
             return;
         } else if (e == QKeySequence::MoveToNextPage) {
             e->accept();
             d->pageUpDown(QTextCursor::Down, QTextCursor::MoveAnchor);
             return;
         }
     }
     if (!(tif & Qt::TextEditable)) {
         switch (e->key()) {
             case Qt::Key_Space:
                 e->accept();
                 if (e->modifiers() & Qt::ShiftModifier)
                     d->vbar->triggerAction(QAbstractSlider::SliderPageStepSub);
                 else
                     d->vbar->triggerAction(QAbstractSlider::SliderPageStepAdd);
                 break;
             default:
                 d->sendControlEvent(e);
                 if (!e->isAccepted() && e->modifiers() == Qt::NoModifier) {
                     if (e->key() == Qt::Key_Home) {
                         d->vbar->triggerAction(QAbstractSlider::SliderToMinimum);
                         e->accept();
                     } else if (e->key() == Qt::Key_End) {
                         d->vbar->triggerAction(QAbstractSlider::SliderToMaximum);
                         e->accept();
                     }
                 }
                 if (!e->isAccepted()) {
                     QAbstractScrollArea::keyPressEvent(e);
                 }
         }
         return;
     }
 #endif // QT_NO_SHORTCUT
     {
         QTextCursor cursor = d->control->textCursor();
         const QString text = e->text();
         if (cursor.atBlockStart()
             && (d->autoFormatting & AutoBulletList)
             && (text.length() == 1)
             && (text.at(0) == QLatin1Char('-') || text.at(0) == QLatin1Char('*'))
             && (!cursor.currentList())) {
             d->createAutoBulletList();
             e->accept();
             return;
         }
     }
     d->sendControlEvent(e);
 #ifdef QT_KEYPAD_NAVIGATION
     if (!e->isAccepted()) {
         switch (e->key()) {
             case Qt::Key_Up:
             case Qt::Key_Down:
                 if (QApplication::keypadNavigationEnabled()) {
                     // Cursor position didn't change, so we want to leave
                     // these keys to change focus.
                     e->ignore();
                     return;
                 }
                 break;
             case Qt::Key_Back:
                 if (!e->isAutoRepeat()) {
                     if (QApplication::keypadNavigationEnabled()) {
                         if (document()->isEmpty() || !(d->control->textInteractionFlags() & Qt::TextEditable)) {
                             setEditFocus(false);
                             e->accept();
                         } else if (!d->deleteAllTimer.isActive()) {
                             e->accept();
                             d->deleteAllTimer.start(750, this);
                         }
                     } else {
                         e->ignore();
                         return;
                     }
                 }
                 break;
             default: break;
         }
     }
 #endif
 }
keyReleaseEvent()
void QTextEdit::keyReleaseEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1365 of file qtextedit.cpp.
 {
 #ifdef QT_KEYPAD_NAVIGATION
     Q_D(QTextEdit);
     if (QApplication::keypadNavigationEnabled()) {
         if (!e->isAutoRepeat() && e->key() == Qt::Key_Back
             && d->deleteAllTimer.isActive()) {
             d->deleteAllTimer.stop();
             QTextCursor cursor = d->control->textCursor();
             QTextBlockFormat blockFmt = cursor.blockFormat();
             QTextList *list = cursor.currentList();
             if (list && cursor.atBlockStart()) {
                 list->remove(cursor.block());
             } else if (cursor.atBlockStart() && blockFmt.indent() > 0) {
                 blockFmt.setIndent(blockFmt.indent() - 1);
                 cursor.setBlockFormat(blockFmt);
             } else {
                 cursor.deletePreviousChar();
             }
             setTextCursor(cursor);
             e->accept();
             return;
         }
     }
 #endif
     e->ignore();
 }
lineWrapColumnOrWidth()
int QTextEdit::lineWrapColumnOrWidth () const
Referenced by QTextEditPrivate::relayoutDocument(), and setLineWrapMode().
lineWrapMode()
LineWrapMode QTextEdit::lineWrapMode () const
Referenced by setTabChangesFocus().
loadResource()
QVariant QTextEdit::loadResource (int type, const QUrl & name) virtual
Loads the resource specified by the given type and name.
This function is an extension of QTextDocument::loadResource().
See also
QTextDocument::loadResource()
Reimplemented in QTextBrowser.
Definition at line 1401 of file qtextedit.cpp.
 {
     Q_UNUSED(type);
     Q_UNUSED(name);
     return QVariant();
 }
mergeCurrentCharFormat()
void QTextEdit::mergeCurrentCharFormat (const QTextCharFormat & modifier)
Merges the properties specified in modifier into the current character format by calling QTextCursor::mergeCharFormat on the editor's cursor.
If the editor has a selection then the properties of modifier are directly applied to the selection.
See also
QTextCursor::mergeCharFormat()
Definition at line 2183 of file qtextedit.cpp.
Referenced by setCurrentFont(), setFontFamily(), setFontItalic(), setFontPointSize(), setFontUnderline(), setFontWeight(), setTextBackgroundColor(), and setTextColor().
 {
     Q_D(QTextEdit);
     d->control->mergeCurrentCharFormat(modifier);
 }
mouseDoubleClickEvent()
void QTextEdit::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1619 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->sendControlEvent(e);
 }
mouseMoveEvent()
void QTextEdit::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Reimplemented in QTextBrowser.
Definition at line 1587 of file qtextedit.cpp.
Referenced by QTextBrowser::mouseMoveEvent(), and timerEvent().
 {
     Q_D(QTextEdit);
     d->inDrag = false; // paranoia
     const QPoint pos = e->pos();
     d->sendControlEvent(e);
     if (!(e->buttons() & Qt::LeftButton))
         return;
     QRect visible = d->viewport->rect();
     if (visible.contains(pos))
         d->autoScrollTimer.stop();
     else if (!d->autoScrollTimer.isActive())
         d->autoScrollTimer.start(100, this);
 }
mousePressEvent()
void QTextEdit::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Reimplemented in QTextBrowser.
Definition at line 1575 of file qtextedit.cpp.
Referenced by QTextBrowser::mousePressEvent().
 {
     Q_D(QTextEdit);
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled() && !hasEditFocus())
         setEditFocus(true);
 #endif
     d->sendControlEvent(e);
 }
mouseReleaseEvent()
void QTextEdit::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Reimplemented in QTextBrowser.
Definition at line 1604 of file qtextedit.cpp.
Referenced by QTextBrowser::mouseReleaseEvent().
 {
     Q_D(QTextEdit);
     d->sendControlEvent(e);
     if (d->autoScrollTimer.isActive()) {
         d->autoScrollTimer.stop();
         ensureCursorVisible();
     }
     if (!isReadOnly() && rect().contains(e->pos()))
         d->handleSoftwareInputPanel(e->button(), d->clickCausedFocus);
     d->clickCausedFocus = 0;
 }
moveCursor()
void QTextEdit::moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode = QTextCursor::MoveAnchor)
Moves the cursor by performing the given operation.
Since
4.2
If mode is QTextCursor::KeepAnchor, the cursor selects the text it moves over. This is the same effect that the user achieves when they hold down the Shift key and move the cursor with the cursor keys.
See also
QTextCursor::movePosition()
Definition at line 2349 of file qtextedit.cpp.
Referenced by setText().
 {
     Q_D(QTextEdit);
     d->control->moveCursor(operation, mode);
 }
overwriteMode()
bool QTextEdit::overwriteMode () const
Referenced by anchorAt().
paintEvent()
void QTextEdit::paintEvent (QPaintEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive paint events passed in event.
It is usually unnecessary to reimplement this function in a subclass of QTextEdit.
Warning
The underlying text document must not be modified from within a reimplementation of this function.
Reimplemented from QAbstractScrollArea.
Reimplemented in QTextBrowser.
Definition at line 1539 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     QPainter p(d->viewport);
     d->paint(&p, e);
 }
paste
void QTextEdit::paste () slot
Pastes the text from the clipboard into the text edit at the current cursor position.
If there is no text in the clipboard nothing happens.
To change the behavior of this function, i.e. to modify what QTextEdit can paste and how it is being pasted, reimplement the virtual canInsertFromMimeData() and insertFromMimeData() functions.
See also
cut() copy()
Definition at line 1036 of file qtextedit.cpp.
Referenced by QAccessibleTextEdit::pasteText().
 {
     Q_D(QTextEdit);
     d->control->paste();
 }
print()
void QTextEdit::print (QPrinter * printer) const
Convenience function to print the text edit's document to the given printer.
Since
4.3 This is equivalent to calling the print method on the document directly except that this function also supports QPrinter::Selection as print range.
See also
QTextDocument::print()
Definition at line 2380 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     d->control->print(printer);
 }
redo
void QTextEdit::redo () slot
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Redoes the last operation.
Since
4.2
If there is no operation to redo, i.e. there is no redo step in the undo/redo history, nothing happens.
See also
undo()
Definition at line 962 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->redo();
 }
redoAvailable
void QTextEdit::redoAvailable (bool b) signal
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
resizeEvent()
void QTextEdit::resizeEvent (QResizeEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1410 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (d->lineWrap == NoWrap) {
         QTextDocument *doc = d->control->document();
         QVariant alignmentProperty = doc->documentLayout()->property("contentHasAlignment");
         if (!doc->pageSize().isNull()
             && alignmentProperty.type() == QVariant::Bool
             && !alignmentProperty.toBool()) {
             d->_q_adjustScrollbars();
             return;
         }
     }
     if (d->lineWrap != FixedPixelWidth
         && e->oldSize().width() != e->size().width())
         d->relayoutDocument();
     else
         d->_q_adjustScrollbars();
 }
scrollContentsBy()
void QTextEdit::scrollContentsBy (int dx, int dy) protected virtual
em>Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1718 of file qtextedit.cpp.
scrollToAnchor
void QTextEdit::scrollToAnchor (const QString & name) slot
Scrolls the text edit so that the anchor with the given name is visible; does nothing if the name is empty, or is already visible, or isn't found.
Definition at line 2277 of file qtextedit.cpp.
Referenced by showEvent().
 {
     Q_D(QTextEdit);
     if (name.isEmpty())
         return;
     if (!isVisible()) {
         d->anchorToScrollToWhenVisible = name;
         return;
     }
     QPointF p = d->control->anchorPosition(name);
     const int newPosition = qRound(p.y());
     if ( d->vbar->maximum() < newPosition )
         d->_q_adjustScrollbars();
     d->vbar->setValue(newPosition);
 }
selectAll
void QTextEdit::selectAll () slot
Selects all text.
See also
copy() cut() textCursor()
Definition at line 1063 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->selectAll();
 }
selectionChanged
void QTextEdit::selectionChanged () signal
This signal is emitted whenever the selection changes.
See also
copyAvailable()
setAcceptRichText()
void QTextEdit::setAcceptRichText (bool accept)
Definition at line 2005 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setAcceptRichText(accept);
 }
setAlignment
void QTextEdit::setAlignment (Qt::Alignment a) slot
Sets the alignment of the current paragraph to a.
Valid alignments are Qt::AlignLeft, Qt::AlignRight, Qt::AlignJustify and Qt::AlignCenter (which centers horizontally).
Definition at line 759 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     QTextBlockFormat fmt;
     fmt.setAlignment(a);
     QTextCursor cursor = d->control->textCursor();
     cursor.mergeBlockFormat(fmt);
     d->control->setTextCursor(cursor);
 }
setAutoFormatting()
void QTextEdit::setAutoFormatting (AutoFormatting features)
Definition at line 2231 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->autoFormatting = features;
 }
setCurrentCharFormat()
void QTextEdit::setCurrentCharFormat (const QTextCharFormat & format)
Sets the char format that is be used when inserting new text to format by calling QTextCursor::setCharFormat() on the editor's cursor.
If the editor has a selection then the char format is directly applied to the selection.
Definition at line 2195 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setCurrentCharFormat(format);
 }
setCurrentFont
void QTextEdit::setCurrentFont (const QFont & f) slot
Sets the font of the current format to f.
See also
currentFont() setFontPointSize() setFontFamily()
Definition at line 936 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setFont(f);
     mergeCurrentCharFormat(fmt);
 }
setCursorWidth()
void QTextEdit::setCursorWidth (int width)
Definition at line 1979 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setCursorWidth(width);
 }
setDocument()
void QTextEdit::setDocument (QTextDocument * document)
Makes document the new document of the text editor.
Note
The editor does not take ownership of the document unless it is the document's parent object. The parent object of the provided document remains the owner of the object.
The editor does not delete the current document, even if it is a child of the editor.
See also
document()
Definition at line 791 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setDocument(document);
     d->updateDefaultTextOption();
     d->relayoutDocument();
 }
setDocumentTitle()
void QTextEdit::setDocumentTitle (const QString & title) inline
Definition at line 168 of file qtextedit.h.
     { document()->setMetaInformation(QTextDocument::DocumentTitle, title); }
setExtraSelections()
void QTextEdit::setExtraSelections (const QList< ExtraSelection > & selections)
This function allows temporarily marking certain regions in the document with a given color, specified as selections.
Since
4.2 This can be useful for example in a programming editor to mark a whole line of text with a given background color to indicate the existence of a breakpoint.
See also
QTextEdit::ExtraSelection, extraSelections()
Definition at line 2047 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setExtraSelections(selections);
 }
setFontFamily
void QTextEdit::setFontFamily (const QString & fontFamily) slot
Sets the font family of the current format to fontFamily.
See also
fontFamily() setCurrentFont()
Definition at line 835 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setFontFamily(fontFamily);
     mergeCurrentCharFormat(fmt);
 }
setFontItalic
void QTextEdit::setFontItalic (bool italic) slot
If italic is true, sets the current format to italic; otherwise sets the current format to non-italic.
See also
fontItalic()
Definition at line 895 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setFontItalic(italic);
     mergeCurrentCharFormat(fmt);
 }
setFontPointSize
void QTextEdit::setFontPointSize (qreal s) slot
Sets the point size of the current format to s.
Note that if s is zero or negative, the behavior of this function is not defined.
See also
fontPointSize() setCurrentFont() setFontFamily()
Definition at line 850 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setFontPointSize(s);
     mergeCurrentCharFormat(fmt);
 }
setFontUnderline
void QTextEdit::setFontUnderline (bool underline) slot
If underline is true, sets the current format to underline; otherwise sets the current format to non-underline.
See also
fontUnderline()
Definition at line 882 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setFontUnderline(underline);
     mergeCurrentCharFormat(fmt);
 }
setFontWeight
void QTextEdit::setFontWeight (int weight) slot
Sets the font weight of the current format to the given weight, where the value used is in the range defined by the QFont::Weight enum.
See also
fontWeight(), setCurrentFont(), setFontFamily()
Definition at line 869 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setFontWeight(w);
     mergeCurrentCharFormat(fmt);
 }
setHtml
void QTextEdit::setHtml (const QString & text) slot
Definition at line 1200 of file qtextedit.cpp.
Referenced by setText().
 {
     Q_D(QTextEdit);
     d->control->setHtml(text);
     d->preferRichText = true;
 }
setLineWrapColumnOrWidth()
void QTextEdit::setLineWrapColumnOrWidth (int w)
Definition at line 2479 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->lineWrapColumnOrWidth = w;
     d->relayoutDocument();
 }
setLineWrapMode()
void QTextEdit::setLineWrapMode (LineWrapMode mode)
Definition at line 2445 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (d->lineWrap == wrap)
         return;
     d->lineWrap = wrap;
     d->updateDefaultTextOption();
     d->relayoutDocument();
 }
setOverwriteMode()
void QTextEdit::setOverwriteMode (bool overwrite)
Definition at line 1931 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setOverwriteMode(overwrite);
 }
setPlainText
void QTextEdit::setPlainText (const QString & text) slot
Changes the text of the text edit to the string text.
Any previous text is removed.
text is interpreted as plain text.
Note that the undo/redo history is cleared by this function.
See also
toPlainText()
Definition at line 1156 of file qtextedit.cpp.
Referenced by QMessageBoxDetailsText::setText(), and setText().
 {
     Q_D(QTextEdit);
     d->control->setPlainText(text);
     d->preferRichText = false;
 }
setReadOnly()
void QTextEdit::setReadOnly (bool ro)
Definition at line 2133 of file qtextedit.cpp.
Referenced by QMessageBoxDetailsText::QMessageBoxDetailsText().
 {
     Q_D(QTextEdit);
     Qt::TextInteractionFlags flags = Qt::NoTextInteraction;
     if (ro) {
         flags = Qt::TextSelectableByMouse;
 #ifndef QT_NO_TEXTBROWSER
         if (qobject_cast<QTextBrowser *>(this))
             flags |= Qt::TextBrowserInteraction;
 #endif
     } else {
         flags = Qt::TextEditorInteraction;
     }
     d->control->setTextInteractionFlags(flags);
     setAttribute(Qt::WA_InputMethodEnabled, shouldEnableInputMethod(this));
 }
setTabChangesFocus()
void QTextEdit::setTabChangesFocus (bool b)
Definition at line 2405 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->tabChangesFocus = b;
 }
setTabStopWidth()
void QTextEdit::setTabStopWidth (int width)
Definition at line 1954 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     QTextOption opt = d->control->document()->defaultTextOption();
     if (opt.tabStop() == width || width < 0)
         return;
     opt.setTabStop(width);
     d->control->document()->setDefaultTextOption(opt);
 }
setText
void QTextEdit::setText (const QString & text) slot
Sets the text edit's text.
Since
4.2
The text can be plain text or HTML and the text edit will try to guess the right format.
Use setHtml() or setPlainText() directly to avoid text edit's guessing.
See also
toPlainText(), toHtml()
Definition at line 2591 of file qtextedit.cpp.
Referenced by DetailButton::setLabel(), and QAccessibleTextEdit::setText().
 {
     Q_D(QTextEdit);
     Qt::TextFormat format = d->textFormat;
     if (d->textFormat == Qt::AutoText)
         format = Qt::mightBeRichText(text) ? Qt::RichText : Qt::PlainText;
 #ifndef QT_NO_TEXTHTMLPARSER
     if (format == Qt::RichText || format == Qt::LogText)
         setHtml(text);
     else
 #endif
         setPlainText(text);
 }
setTextBackgroundColor
void QTextEdit::setTextBackgroundColor (const QColor & c) slot
Sets the text background color of the current format to c.
Since
4.4
See also
textBackgroundColor()
Definition at line 924 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setBackground(QBrush(c));
     mergeCurrentCharFormat(fmt);
 }
setTextColor
void QTextEdit::setTextColor (const QColor & c) slot
Sets the text color of the current format to c.
See also
textColor()
Definition at line 907 of file qtextedit.cpp.
 {
     QTextCharFormat fmt;
     fmt.setForeground(QBrush(c));
     mergeCurrentCharFormat(fmt);
 }
setTextCursor()
void QTextEdit::setTextCursor (const QTextCursor & cursor)
Sets the visible cursor.
Definition at line 813 of file qtextedit.cpp.
Referenced by keyReleaseEvent(), QAccessibleTextEdit::pasteText(), and QAccessibleTextEdit::setTextCursor().
 {
     Q_D(QTextEdit);
     d->control->setTextCursor(cursor);
 }
setTextInteractionFlags()
void QTextEdit::setTextInteractionFlags (Qt::TextInteractionFlags flags)
Definition at line 2163 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->setTextInteractionFlags(flags);
 }
setUndoRedoEnabled()
void QTextEdit::setUndoRedoEnabled (bool enable) inline
Definition at line 175 of file qtextedit.h.
     { document()->setUndoRedoEnabled(enable); }
setWordWrapMode()
void QTextEdit::setWordWrapMode (QTextOption::WrapMode policy)
Definition at line 2504 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (mode == d->wordWrap)
         return;
     d->wordWrap = mode;
     d->updateDefaultTextOption();
 }
showEvent()
void QTextEdit::showEvent (QShowEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1767 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (!d->anchorToScrollToWhenVisible.isEmpty()) {
         scrollToAnchor(d->anchorToScrollToWhenVisible);
         d->anchorToScrollToWhenVisible.clear();
         d->showCursorOnInitialShow = false;
     } else if (d->showCursorOnInitialShow) {
         d->showCursorOnInitialShow = false;
         ensureCursorVisible();
     }
 }
tabChangesFocus()
bool QTextEdit::tabChangesFocus () const
Referenced by print().
tabStopWidth()
int QTextEdit::tabStopWidth () const
Referenced by setOverwriteMode().
textBackgroundColor()
QColor QTextEdit::textBackgroundColor () const
Returns the text background color of the current format.
Since
4.4
See also
setTextBackgroundColor()
Definition at line 736 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().background().color();
 }
textChanged
void QTextEdit::textChanged () signal
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
textColor()
QColor QTextEdit::textColor () const
Returns the text color of the current format.
See also
setTextColor()
Definition at line 720 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->control->textCursor().charFormat().foreground().color();
 }
textCursor()
QTextCursor QTextEdit::textCursor () const
Returns a copy of the QTextCursor that represents the currently visible cursor.
Note that changes on the returned cursor do not affect QTextEdit's cursor; use setTextCursor() to update the visible cursor.
Definition at line 824 of file qtextedit.cpp.
Referenced by QAccessibleTextEdit::invokeMethodEx(), QAccessibleTextEdit::pasteText(), and QAccessibleTextEdit::textCursor().
 {
     Q_D(const QTextEdit);
     return d->control->textCursor();
 }
textInteractionFlags()
Qt::TextInteractionFlags QTextEdit::textInteractionFlags () const
Referenced by setTextInteractionFlags().
timerEvent()
void QTextEdit::timerEvent (QTimerEvent * e) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Definition at line 1102 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (e->timerId() == d->autoScrollTimer.timerId()) {
         QRect visible = d->viewport->rect();
         QPoint pos;
         if (d->inDrag) {
             pos = d->autoScrollDragPos;
             visible.adjust(qMin(visible.width()/3,20), qMin(visible.height()/3,20),
                            -qMin(visible.width()/3,20), -qMin(visible.height()/3,20));
         } else {
             const QPoint globalPos = QCursor::pos();
             pos = d->viewport->mapFromGlobal(globalPos);
             QMouseEvent ev(QEvent::MouseMove, pos, globalPos, Qt::LeftButton, Qt::LeftButton, Qt::NoModifier);
             mouseMoveEvent(&ev);
         }
         int deltaY = qMax(pos.y() - visible.top(), visible.bottom() - pos.y()) - visible.height();
         int deltaX = qMax(pos.x() - visible.left(), visible.right() - pos.x()) - visible.width();
         int delta = qMax(deltaX, deltaY);
         if (delta >= 0) {
             if (delta < 7)
                 delta = 7;
             int timeout = 4900 / (delta * delta);
             d->autoScrollTimer.start(timeout, this);
             if (deltaY > 0)
                 d->vbar->triggerAction(pos.y() < visible.center().y() ?
                                        QAbstractSlider::SliderSingleStepSub
                                        : QAbstractSlider::SliderSingleStepAdd);
             if (deltaX > 0)
                 d->hbar->triggerAction(pos.x() < visible.center().x() ?
                                        QAbstractSlider::SliderSingleStepSub
                                        : QAbstractSlider::SliderSingleStepAdd);
         }
     }
 #ifdef QT_KEYPAD_NAVIGATION
     else if (e->timerId() == d->deleteAllTimer.timerId()) {
         d->deleteAllTimer.stop();
         clear();
     }
 #endif
 }
toHtml()
QString QTextEdit::toHtml () const inline
Definition at line 192 of file qtextedit.h.
     { return document()->toHtml(); }
toPlainText()
QString QTextEdit::toPlainText () const inline
Returns the text of the text edit as plain text.
See also
QTextEdit::setPlainText()
Definition at line 189 of file qtextedit.h.
Referenced by QMessageBoxDetailsText::text(), and QAccessibleTextEdit::text().
     { return document()->toPlainText(); }
undo
void QTextEdit::undo () slot
Undoes the last operation.
Use the non-const overload instead.
Since
4.2
If there is no operation to undo, i.e. there is no undo step in the undo/redo history, nothing happens.
See also
redo()
Definition at line 956 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     d->control->undo();
 }
undoAvailable
void QTextEdit::undoAvailable (bool b) signal
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
wheelEvent()
void QTextEdit::wheelEvent (QWheelEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 1806 of file qtextedit.cpp.
 {
     Q_D(QTextEdit);
     if (!(d->control->textInteractionFlags() & Qt::TextEditable)) {
         if (e->modifiers() & Qt::ControlModifier) {
             const int delta = e->delta();
             if (delta < 0)
                 zoomOut();
             else if (delta > 0)
                 zoomIn();
             return;
         }
     }
     QAbstractScrollArea::wheelEvent(e);
     updateMicroFocus();
 }
wordWrapMode()
QTextOption::WrapMode QTextEdit::wordWrapMode () const
the mode QTextEdit will use when wrapping text by words
By default, this property is set to QTextOption::WrapAtWordBoundaryOrAnywhere.
See also
QTextOption::WrapMode
Definition at line 2498 of file qtextedit.cpp.
 {
     Q_D(const QTextEdit);
     return d->wordWrap;
 }
zoomIn
void QTextEdit::zoomIn (int range = 1) slot
Zooms in on the text by making the base font size range points larger and recalculating all font sizes to be the new size.
This does not change the size of any images.
See also
zoomOut()
Definition at line 2307 of file qtextedit.cpp.
Referenced by wheelEvent(), and zoomOut().
 {
     QFont f = font();
     const int newSize = f.pointSize() + range;
     if (newSize <= 0)
         return;
     f.setPointSize(newSize);
     setFont(f);
 }
zoomOut
void QTextEdit::zoomOut (int range = 1) slot
Zooms out on the text by making the base font size range points smaller and recalculating all font sizes to be the new size.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This does not change the size of any images.
See also
zoomIn()
Definition at line 2331 of file qtextedit.cpp.
Referenced by wheelEvent().
 {
     zoomIn(-range);
 }
Friends and Related Functions
QTextControl
friend class QTextControl friend
Definition at line 419 of file qtextedit.h.
QTextDocument
friend class QTextDocument friend
Definition at line 418 of file qtextedit.h.
QTextEditControl
friend class QTextEditControl friend
Definition at line 417 of file qtextedit.h.
Properties
acceptRichText
bool QTextEdit::acceptRichText private
whether the text edit accepts rich text insertions by the user
Since
4.1
When this propery is set to false text edit will accept only plain text input from the user. For example through clipboard or drag and drop.
This property's default is true.
Definition at line 90 of file qtextedit.h.
autoFormatting
QTextEdit::AutoFormatting QTextEdit::autoFormatting private
the enabled set of auto formatting features
The value can be any combination of the values in the AutoFormattingFlag enum. The default is AutoNone. Choose AutoAll to enable all automatic formatting.
Currently, the only automatic formatting feature provided is AutoBulletList; future versions of Qt may offer more.
Definition at line 76 of file qtextedit.h.
cursorWidth
int QTextEdit::cursorWidth private
This property specifies the width of the cursor in pixels.
Since
4.2
The default value is 1.
Definition at line 91 of file qtextedit.h.
documentTitle
QTextEdit::documentTitle private
the title of the document parsed from the text.
By default, for a newly-created, empty document, this property contains an empty string.
Definition at line 78 of file qtextedit.h.
html
QTextEdit::html private
This property provides an HTML interface to the text of the text edit.
toHtml() returns the text of the text edit as html.
setHtml() changes the text of the text edit. Any previous text is removed and the undo/redo history is cleared. The input text is interpreted as rich text in html format.
Note
It is the responsibility of the caller to make sure that the text is correctly decoded when a QString containing HTML is created and passed to setHtml().
By default, for a newly-created, empty document, this property contains text to describe an HTML 4.0 document with no body text.
See also
{Supported HTML Subset}, plainText
Definition at line 85 of file qtextedit.h.
lineWrapColumnOrWidth
int QTextEdit::lineWrapColumnOrWidth private
the position (in pixels or columns depending on the wrap mode) where text will be wrapped
If the wrap mode is FixedPixelWidth, the value is the number of pixels from the left edge of the text edit at which text should be wrapped. If the wrap mode is FixedColumnWidth, the value is the column number (in character columns) from the left edge of the text edit at which text should be wrapped.
By default, this property contains a value of 0.
See also
lineWrapMode
Definition at line 82 of file qtextedit.h.
lineWrapMode
QTextEdit::LineWrapMode QTextEdit::lineWrapMode private
the line wrap mode
The default mode is WidgetWidth which causes words to be wrapped at the right edge of the text edit. Wrapping occurs at whitespace, keeping whole words intact. If you want wrapping to occur within words use setWordWrapMode(). If you set a wrap mode of FixedPixelWidth or FixedColumnWidth you should also call setLineWrapColumnOrWidth() with the width you want.
See also
lineWrapColumnOrWidth
Definition at line 80 of file qtextedit.h.
overwriteMode
bool QTextEdit::overwriteMode private
whether text entered by the user will overwrite existing text
Since
4.1
As with many text editors, the text editor widget can be configured to insert or overwrite existing text with new text entered by the user.
If this property is true, existing text is overwritten, character-for-character by new text; otherwise, text is inserted at the cursor position, displacing existing text.
By default, this property is false (new text does not overwrite existing text).
Definition at line 88 of file qtextedit.h.
plainText
QTextEdit::plainText private
This property gets and sets the text editor's contents as plain text.
Since
4.3
Previous contents are removed and undo/redo history is reset when the property is set.
If the text edit has another content type, it will not be replaced by plain text if you call toPlainText(). The only exception to this is the non-break space, nbsp;, that will be converted into standard space.
By default, for an editor with no contents, this property contains an empty string.
See also
html
Definition at line 87 of file qtextedit.h.
readOnly
QTextEdit::readOnly private
whether the text edit is read-only
In a read-only text edit the user can only navigate through the text and select text; modifying the text is not possible.
This property's default is false.
Definition at line 83 of file qtextedit.h.
tabChangesFocus
bool QTextEdit::tabChangesFocus private
whether Tab changes focus or is accepted as input
In some occasions text edits should not allow the user to input tabulators or change indentation using the Tab key, as this breaks the focus chain. The default is false.
Definition at line 77 of file qtextedit.h.
tabStopWidth
int QTextEdit::tabStopWidth private
the tab stop width in pixels
Since
4.1
By default, this property contains a value of 80 pixels.
Definition at line 89 of file qtextedit.h.
textInteractionFlags
Qt::TextInteractionFlags QTextEdit::textInteractionFlags private
Specifies how the widget should interact with user input.
Since
4.2
The default value depends on whether the QTextEdit is read-only or editable, and whether it is a QTextBrowser or not.
Definition at line 92 of file qtextedit.h.
undoRedoEnabled
QTextEdit::undoRedoEnabled private
whether undo and redo are enabled
Users are only able to undo or redo actions if this property is true, and if there is an action that can be undone (or redone).
Definition at line 79 of file qtextedit.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qtextedit.h
/src/gui/widgets/qtextedit.cpp