Qt 4.8: QTextFormatPrivate Class Reference
QTextFormatPrivate Class Reference
Classes
struct Property
Public Functions
void clearProperty (qint32 key)
const QFont & font () const
uint hash () const
bool hasProperty (qint32 key) const
void insertProperty (qint32 key, const QVariant &value)
bool operator== (const QTextFormatPrivate &rhs) const
QVariant property (qint32 key) const
int propertyIndex (qint32 key) const
QTextFormatPrivate ()
void resolveFont (const QFont &defaultFont)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Variables
QVector< Property > props
Public Variables inherited from QSharedData
QAtomicInt ref
Private Functions
void recalcFont () const
uint recalcHash () const
Properties
QFont fnt
bool fontDirty
bool hashDirty
uint hashValue
Friends
QDataStream & operator<< (QDataStream &, const QTextFormat &)
QDataStream & operator>> (QDataStream &, QTextFormat &)
Detailed Description
Definition at line 195 of file qtextformat.cpp.
Constructors and Destructors
QTextFormatPrivate()
QTextFormatPrivate::QTextFormatPrivate () inline
Definition at line 198 of file qtextformat.cpp.
Referenced by operator>>().
 : hashDirty(true), fontDirty(true), hashValue(0) {}
Functions
clearProperty()
void QTextFormatPrivate::clearProperty (qint32 key) inline
Definition at line 241 of file qtextformat.cpp.
Referenced by QTextFormat::clearProperty(), and QTextFormat::setObjectIndex().
     {
         for (int i = 0; i < props.count(); ++i)
             if (props.at(i).key == key) {
                 hashDirty = true;
                 if (key >= QTextFormat::FirstFontProperty && key <= QTextFormat::LastFontProperty)
                     fontDirty = true;
                 props.remove(i);
                 return;
             }
     }
font()
const QFont& QTextFormatPrivate::font () const inline
Definition at line 274 of file qtextformat.cpp.
Referenced by QTextCharFormat::font().
{
         if (fontDirty)
             recalcFont();
         return fnt;
     }
hash()
uint QTextFormatPrivate::hash () const inline
Definition at line 214 of file qtextformat.cpp.
Referenced by getHash(), hash(), operator==(), and variantHash().
     {
         if (!hashDirty)
             return hashValue;
         return recalcHash();
     }
hasProperty()
bool QTextFormatPrivate::hasProperty (qint32 key) const inline
Definition at line 269 of file qtextformat.cpp.
Referenced by QTextFormat::hasProperty(), recalcFont(), and resolveFont().
     { return propertyIndex(key) != -1; }
insertProperty()
void QTextFormatPrivate::insertProperty (qint32 key, const QVariant & value) inline
Definition at line 228 of file qtextformat.cpp.
Referenced by QTextFormat::merge(), operator>>(), QTextFormat::setObjectIndex(), and QTextFormat::setProperty().
     {
         hashDirty = true;
         if (key >= QTextFormat::FirstFontProperty && key <= QTextFormat::LastFontProperty)
             fontDirty = true;
         for (int i = 0; i < props.count(); ++i)
             if (props.at(i).key == key) {
                 props[i].value = value;
                 return;
             }
         props.append(Property(key, value));
     }
operator==()
bool QTextFormatPrivate::operator== (const QTextFormatPrivate & rhs) const inline
Definition at line 221 of file qtextformat.cpp.
{
         if (hash() != rhs.hash())
             return false;
         return props == rhs.props;
     }
property()
QVariant QTextFormatPrivate::property (qint32 key) const inline
Definition at line 261 of file qtextformat.cpp.
Referenced by QTextFormat::boolProperty(), QTextFormat::brushProperty(), QTextFormat::colorProperty(), QTextFormat::doubleProperty(), QTextFormat::intProperty(), QTextFormat::lengthProperty(), QTextFormat::lengthVectorProperty(), QTextFormat::objectIndex(), QTextFormat::penProperty(), QTextFormat::property(), resolveFont(), and QTextFormat::stringProperty().
     {
         const int idx = propertyIndex(key);
         if (idx < 0)
             return QVariant();
         return props.at(idx).value;
     }
propertyIndex()
int QTextFormatPrivate::propertyIndex (qint32 key) const inline
Definition at line 253 of file qtextformat.cpp.
Referenced by hasProperty(), and property().
     {
         for (int i = 0; i < props.count(); ++i)
             if (props.at(i).key == key)
                 return i;
         return -1;
     }
recalcFont()
void QTextFormatPrivate::recalcFont () const private
Definition at line 387 of file qtextformat.cpp.
Referenced by font(), and resolveFont().
 {
     // update cached font as well
     QFont f;
     for (int i = 0; i < props.count(); ++i) {
         switch (props.at(i).key) {
             case QTextFormat::FontFamily:
                 f.setFamily(props.at(i).value.toString());
                 break;
             case QTextFormat::FontPointSize:
                 f.setPointSizeF(props.at(i).value.toReal());
                 break;
             case  QTextFormat::FontPixelSize:
                 f.setPixelSize(props.at(i).value.toInt());
                 break;
             case QTextFormat::FontWeight: {
                 int weight = props.at(i).value.toInt();
                 if (weight == 0) weight = QFont::Normal;
                 f.setWeight(weight);
                 break; }
             case QTextFormat::FontItalic:
                 f.setItalic(props.at(i).value.toBool());
                 break;
             case QTextFormat::FontUnderline:
                 if (! hasProperty(QTextFormat::TextUnderlineStyle)) // don't use the old one if the new one is there.
                     f.setUnderline(props.at(i).value.toBool());
                 break;
             case QTextFormat::TextUnderlineStyle:
                 f.setUnderline(static_cast<QTextCharFormat::UnderlineStyle>(props.at(i).value.toInt()) == QTextCharFormat::SingleUnderline);
                 break;
             case QTextFormat::FontOverline:
                 f.setOverline(props.at(i).value.toBool());
                 break;
             case QTextFormat::FontStrikeOut:
                 f.setStrikeOut(props.at(i).value.toBool());
                 break;
             case QTextFormat::FontLetterSpacing:
                 f.setLetterSpacing(QFont::PercentageSpacing, props.at(i).value.toReal());
                 break;
             case QTextFormat::FontWordSpacing:
                 f.setWordSpacing(props.at(i).value.toReal());
                 break;
             case QTextFormat::FontCapitalization:
                 f.setCapitalization(static_cast<QFont::Capitalization> (props.at(i).value.toInt()));
                 break;
             case QTextFormat::FontFixedPitch: {
                 const bool value = props.at(i).value.toBool();
                 if (f.fixedPitch() != value)
                     f.setFixedPitch(value);
                 break; }
             case QTextFormat::FontStyleHint:
                 f.setStyleHint(static_cast<QFont::StyleHint>(props.at(i).value.toInt()), f.styleStrategy());
                 break;
             case QTextFormat::FontHintingPreference:
                 f.setHintingPreference(static_cast<QFont::HintingPreference>(props.at(i).value.toInt()));
                 break;
             case QTextFormat::FontStyleStrategy:
                 f.setStyleStrategy(static_cast<QFont::StyleStrategy>(props.at(i).value.toInt()));
                 break;
             case QTextFormat::FontKerning:
                 f.setKerning(props.at(i).value.toBool());
                 break;
             default:
                 break;
             }
     }
     fnt = f;
     fontDirty = false;
 }
recalcHash()
uint QTextFormatPrivate::recalcHash () const private
Definition at line 352 of file qtextformat.cpp.
Referenced by hash().
 {
     hashValue = 0;
     for (QVector<Property>::ConstIterator it = props.constBegin(); it != props.constEnd(); ++it)
         hashValue += (it->key << 16) + variantHash(it->value);
     hashDirty = false;
     return hashValue;
 }
resolveFont()
void QTextFormatPrivate::resolveFont (const QFont & defaultFont)
Definition at line 363 of file qtextformat.cpp.
Referenced by hasProperty(), and QTextFormatCollection::indexForFormat().
 {
     recalcFont();
     const uint oldMask = fnt.resolve();
     fnt = fnt.resolve(defaultFont);
     if (hasProperty(QTextFormat::FontSizeAdjustment)) {
         const qreal scaleFactors[7] = {qreal(0.7), qreal(0.8), qreal(1.0), qreal(1.2), qreal(1.5), qreal(2), qreal(2.4)};
         const int htmlFontSize = qBound(0, property(QTextFormat::FontSizeAdjustment).toInt() + 3 - 1, 6);
         if (defaultFont.pointSize() <= 0) {
             qreal pixelSize = scaleFactors[htmlFontSize] * defaultFont.pixelSize();
             fnt.setPixelSize(qRound(pixelSize));
         } else {
             qreal pointSize = scaleFactors[htmlFontSize] * defaultFont.pointSizeF();
             fnt.setPointSizeF(pointSize);
         }
     }
     fnt.resolve(oldMask);
 }
Friends and Related Functions
operator<<
QDataStream& operator<< (QDataStream & , const QTextFormat &) friend
Definition at line 459 of file qtextformat.cpp.
 {
     stream << fmt.format_type << fmt.properties();
     return stream;
 }
operator>>
QDataStream& operator>> (QDataStream & , QTextFormat &) friend
Definition at line 465 of file qtextformat.cpp.
 {
     QMap<qint32, QVariant> properties;
     stream >> fmt.format_type >> properties;
     // QTextFormat's default constructor doesn't allocate the private structure, so
     // we have to do this, in case fmt is a default constructed value.
     if(!fmt.d)
         fmt.d = new QTextFormatPrivate();
     for (QMap<qint32, QVariant>::ConstIterator it = properties.constBegin();
          it != properties.constEnd(); ++it)
         fmt.d->insertProperty(it.key(), it.value());
     return stream;
 }
Properties
fnt
QFont QTextFormatPrivate::fnt mutable private
Definition at line 289 of file qtextformat.cpp.
Referenced by font(), recalcFont(), and resolveFont().
fontDirty
bool QTextFormatPrivate::fontDirty mutable private
Definition at line 287 of file qtextformat.cpp.
Referenced by clearProperty(), font(), insertProperty(), and recalcFont().
hashDirty
bool QTextFormatPrivate::hashDirty mutable private
Definition at line 286 of file qtextformat.cpp.
Referenced by clearProperty(), hash(), insertProperty(), and recalcHash().
hashValue
uint QTextFormatPrivate::hashValue mutable private
Definition at line 288 of file qtextformat.cpp.
Referenced by hash(), and recalcHash().
props
QVector<Property> QTextFormatPrivate::props
Definition at line 280 of file qtextformat.cpp.
Referenced by clearProperty(), insertProperty(), QTextFormat::merge(), operator==(), QTextFormat::operator==(), QTextFormat::properties(), property(), QTextFormat::propertyCount(), propertyIndex(), recalcFont(), and recalcHash().
The documentation for this class was generated from the following file:
/src/gui/text/qtextformat.cpp