Qt 4.8: QPatternist::UntypedAtomic Class Reference
QPatternist::UntypedAtomic Class Reference
Implements the value instance of the xs:untypedAtomic type.
#include <quntypedatomic_p.h>
Public Functions
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicString
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual QString stringValue () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static UntypedAtomic::Ptr fromValue (const QString &value)
Static Public Functions inherited from QPatternist::AtomicString
static AtomicString::Ptr fromValue (const QString &value)
static AtomicString::Ptr fromValue (const QUrl &value)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
UntypedAtomic (const QString &value)
Protected Functions inherited from QPatternist::AtomicString
AtomicString (const QString &value)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Friends
class CommonValues
Additional Inherited Members
Public Types inherited from QPatternist::AtomicString
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Variables inherited from QPatternist::AtomicString
const QString m_value
Detailed Description
Implements the value instance of the xs:untypedAtomic type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 70 of file quntypedatomic_p.h.
Constructors and Destructors
UntypedAtomic()
UntypedAtomic::UntypedAtomic (const QString & value) protected
Definition at line 50 of file quntypedatomic.cpp.
Referenced by fromValue().
                                              : AtomicString(s)
 {
 }
Functions
fromValue()
UntypedAtomic::Ptr UntypedAtomic::fromValue (const QString & value) static
Creates an instance representing value.
This fromValue function takes no context argument because it doesn't need it – it casting to xs:untypedAtomic always succeeds.
Note
This function does not remove the string literal escaping allowed in XPath 2.0
Definition at line 54 of file quntypedatomic.cpp.
Referenced by QPatternist::ToUntypedAtomicCaster::castFrom(), and QPatternist::AccelTree::sequencedTypedValue().
 {
     return UntypedAtomic::Ptr(new UntypedAtomic(value));
 }
type()
ItemType::Ptr UntypedAtomic::type () const virtual
Reimplemented from QPatternist::AtomicString.
Definition at line 59 of file quntypedatomic.cpp.
 {
     return BuiltinTypes::xsUntypedAtomic;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 73 of file quntypedatomic_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/quntypedatomic_p.h
/src/xmlpatterns/data/quntypedatomic.cpp