Qt 4.8: QDeclarativeData Class Reference
QDeclarativeData Class Reference
#include <qdeclarativedata_p.h>
Public Functions
void addBoundSignal (QDeclarativeAbstractBoundSignal *signal)
QHash< int, QObject * > * attachedProperties () const
void clearBindingBit (int)
void destroyed (QObject *)
void disconnectNotifiers ()
bool hasBindingBit (int) const
bool hasExtendedData () const
void objectNameChanged (QObject *)
QDeclarativeNotifier * objectNameNotifier () const
void parentChanged (QObject *, QObject *)
QDeclarativeData ()
void removeBoundSignal (QDeclarativeAbstractBoundSignal *signal)
void setBindingBit (QObject *obj, int)
void setImplicitDestructible ()
Static Public Functions
static void destroyed (QAbstractDeclarativeData *, QObject *)
static QDeclarativeData * get (const QObject *object, bool create=false)
static void init ()
static void objectNameChanged (QAbstractDeclarativeData *, QObject *)
static void parentChanged (QAbstractDeclarativeData *, QObject *, QObject *)
Public Variables
quint32 * bindingBits
int bindingBitsSize
QDeclarativeAbstractBinding * bindings
ushort columnNumber
QDeclarativeContextData * context
QDeclarativeCompiledData * deferredComponent
unsigned int deferredIdx
quint32 dummy:28
quint32 explicitIndestructibleSet:1
QDeclarativeGuardImpl * guards
quint32 indestructible:1
ushort lineNumber
QDeclarativeData * nextContextObject
quint32 objectDataRefCount
QDeclarativeContextData * outerContext
quint32 ownContext:1
quint32 ownMemory:1
QDeclarativeData ** prevContextObject
QDeclarativePropertyCache * propertyCache
QScriptValue * scriptValue
Properties
QDeclarativeDataExtended * extendedData
Additional Inherited Members
Static Public Variables inherited from QAbstractDeclarativeData
static void(* destroyed)(QAbstractDeclarativeData *, QObject *)
static void(* objectNameChanged)(QAbstractDeclarativeData *, QObject *)
static void(* parentChanged)(QAbstractDeclarativeData *, QObject *, QObject *)
Detailed Description
Definition at line 74 of file qdeclarativedata_p.h.
Constructors and Destructors
QDeclarativeData()
QDeclarativeData::QDeclarativeData () inline
Definition at line 77 of file qdeclarativedata_p.h.
         : ownMemory(true), ownContext(false), indestructible(true), explicitIndestructibleSet(false),
           context(0), outerContext(0), bindings(0), nextContextObject(0), prevContextObject(0), bindingBitsSize(0),
           bindingBits(0), lineNumber(0), columnNumber(0), deferredComponent(0), deferredIdx(0),
           scriptValue(0), objectDataRefCount(0), propertyCache(0), guards(0), extendedData(0) {
           init();
       }
Functions
addBoundSignal()
void QDeclarativeData::addBoundSignal (QDeclarativeAbstractBoundSignal * signal)
Definition at line 1159 of file qdeclarativeengine.cpp.
 {
     if (!extendedData) extendedData = new QDeclarativeDataExtended;
     extendedData->boundSignals.append(signal);
 }
attachedProperties()
QHash< int, QObject * > * QDeclarativeData::attachedProperties () const
Definition at line 1153 of file qdeclarativeengine.cpp.
Referenced by qmlAttachedPropertiesObjectById().
 {
     if (!extendedData) extendedData = new QDeclarativeDataExtended;
     return &extendedData->attachedProperties;
 }
clearBindingBit()
void QDeclarativeData::clearBindingBit (int bit)
Definition at line 1247 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeAbstractBinding::removeFromObject().
 {
     if (bindingBitsSize > bit)
         bindingBits[bit / 32] &= ~(1 << (bit % 32));
 }
destroyed() [1/2]
void QDeclarativeData::destroyed (QAbstractDeclarativeData * d, QObject * o) static
Definition at line 566 of file qdeclarativeengine.cpp.
 {
     static_cast<QDeclarativeData *>(d)->destroyed(o);
 }
destroyed() [2/2]
void QDeclarativeData::destroyed (QObject * object)
Definition at line 1185 of file qdeclarativeengine.cpp.
 {
     if (deferredComponent)
         deferredComponent->release();
     if (nextContextObject)
         nextContextObject->prevContextObject = prevContextObject;
     if (prevContextObject)
         *prevContextObject = nextContextObject;
     QDeclarativeAbstractBinding *binding = bindings;
     while (binding) {
         QDeclarativeAbstractBinding *next = binding->m_nextBinding;
         binding->m_prevBinding = 0;
         binding->m_nextBinding = 0;
         binding->destroy(QDeclarativeAbstractBinding::KeepBindingConnected);
         binding = next;
     }
     if (bindingBits)
         free(bindingBits);
     if (propertyCache)
         propertyCache->release();
     if (ownContext && context)
         context->destroy();
     while (guards) {
         QDeclarativeGuard<QObject> *guard = static_cast<QDeclarativeGuard<QObject> *>(guards);
         *guard = (QObject *)0;
         guard->objectDestroyed(object);
     }
     if (scriptValue)
         delete scriptValue;
     if (extendedData)
         delete extendedData;
     if (ownMemory)
         delete this;
 }
disconnectNotifiers()
void QDeclarativeData::disconnectNotifiers ()
Definition at line 1171 of file qdeclarativeengine.cpp.
Referenced by QDeclarativePrivate::qdeclarativeelement_destructor().
 {
     QDeclarativeAbstractBinding *binding = bindings;
     while (binding) {
         binding->disconnect(QDeclarativeAbstractBinding::DisconnectAll);
         binding = binding->m_nextBinding;
     }
     if (extendedData) {
         Q_FOREACH (QDeclarativeAbstractBoundSignal *signal, extendedData->boundSignals)
             signal->disconnect();
     }
 }
get()
static QDeclarativeData* QDeclarativeData::get (const QObject * object, bool create = false) inline static
Definition at line 140 of file qdeclarativedata_p.h.
Referenced by QDeclarativeGuardImpl::addGuard(), QDeclarativeContextData::addObject(), QDeclarativeAbstractBinding::addToObject(), QDeclarativeComponent::beginCreate(), QDeclarativePropertyPrivate::binding(), QDeclarativeComponentPrivate::complete(), QDeclarativeConnections::connectSignals(), QDeclarativeEnginePrivate::createComponent(), QDeclarativeComponentPrivate::createObject(), QDeclarativeEnginePrivate::createQmlObject(), QDeclarativePropertyChangesPrivate::decode(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeStateChangeScript::execute(), QDeclarativeScriptActionPrivate::execute(), QDeclarativePropertyPrivate::findAliasTarget(), QDeclarativeBoundSignal::init(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeObjectScriptClass::newQObject(), ObjectData::ObjectData(), QDeclarativeEngineDebugService::objectData(), QDeclarativeEngine::objectOwnership(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeObjectScriptClass::property(), QDeclarativePropertyCache::property(), QDeclarativeObjectScriptClass::propertyNames(), QDeclarativeComponent::qmlAttachedProperties(), qmlAttachedPropertiesObjectById(), qmlExecuteDeferred(), QObject_objectName(), QDeclarativeObjectScriptClass::queryProperty(), QDeclarativeObjectMethodScriptClass::relatedMethod(), QDeclarativeAbstractBinding::removeFromObject(), QDeclarativeVME::run(), QDeclarativeVME::runDeferred(), QDeclarativePropertyPrivate::setBinding(), QDeclarativePropertyPrivate::setBindingNoEnable(), QDeclarativeOpenMetaObject::setCached(), QDeclarativeEngine::setContextForObject(), QDeclarativeEngine::setObjectOwnership(), QDeclarativeVisualDataModel::stringValue(), QDeclarativeBoundSignal::unregisterScopeObject(), ObjectData::~ObjectData(), and QDeclarativeInfo::~QDeclarativeInfo().
{
         QObjectPrivate *priv = QObjectPrivate::get(const_cast<QObject *>(object));
         if (priv->wasDeleted) {
             Q_ASSERT(!create);
             return 0;
         } else if (priv->declarativeData) {
             return static_cast<QDeclarativeData *>(priv->declarativeData);
         } else if (create) {
             priv->declarativeData = new QDeclarativeData;
             return static_cast<QDeclarativeData *>(priv->declarativeData);
         } else {
             return 0;
         }
     }
hasBindingBit()
bool QDeclarativeData::hasBindingBit (int bit) const
Definition at line 1239 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeAbstractBinding::addToObject(), QDeclarativePropertyPrivate::binding(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
 {
     if (bindingBitsSize > bit)
         return bindingBits[bit / 32] & (1 << (bit % 32));
     else
         return false;
 }
hasExtendedData()
bool QDeclarativeData::hasExtendedData () const inline
Definition at line 155 of file qdeclarativedata_p.h.
Referenced by qmlAttachedPropertiesObjectById().
 { return extendedData != 0; }
init()
static void QDeclarativeData::init () inline static
Definition at line 85 of file qdeclarativedata_p.h.
Referenced by QDeclarativeEnginePrivate::init().
{
         QAbstractDeclarativeData::destroyed = destroyed;
         QAbstractDeclarativeData::parentChanged = parentChanged;
         QAbstractDeclarativeData::objectNameChanged = objectNameChanged;
     }
objectNameChanged() [1/2]
void QDeclarativeData::objectNameChanged (QAbstractDeclarativeData * d, QObject * o) static
Definition at line 576 of file qdeclarativeengine.cpp.
 {
     static_cast<QDeclarativeData *>(d)->objectNameChanged(o);
 }
objectNameChanged() [2/2]
void QDeclarativeData::objectNameChanged (QObject *)
Definition at line 1234 of file qdeclarativeengine.cpp.
 {
     if (extendedData) objectNameNotifier()->notify();
 }
objectNameNotifier()
QDeclarativeNotifier * QDeclarativeData::objectNameNotifier () const
Definition at line 1147 of file qdeclarativeengine.cpp.
 {
     if (!extendedData) extendedData = new QDeclarativeDataExtended;
     return &extendedData->objectNameNotifier;
 }
parentChanged() [1/2]
void QDeclarativeData::parentChanged (QAbstractDeclarativeData * d, QObject * o, QObject * p) static
Definition at line 571 of file qdeclarativeengine.cpp.
 {
     static_cast<QDeclarativeData *>(d)->parentChanged(o, p);
 }
parentChanged() [2/2]
void QDeclarativeData::parentChanged (QObject * , QObject * parent)
Definition at line 1229 of file qdeclarativeengine.cpp.
 {
     if (!parent && scriptValue) { delete scriptValue; scriptValue = 0; }
 }
removeBoundSignal()
void QDeclarativeData::removeBoundSignal (QDeclarativeAbstractBoundSignal * signal)
Definition at line 1165 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeBoundSignal::unregisterScopeObject().
 {
     if (extendedData)
         extendedData->boundSignals.removeAll(signal);
 }
setBindingBit()
void QDeclarativeData::setBindingBit (QObject * obj, int bit)
Definition at line 1253 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeAbstractBinding::addToObject().
 {
     if (bindingBitsSize <= bit) {
         int props = obj->metaObject()->propertyCount();
         Q_ASSERT(bit < props);
         int arraySize = (props + 31) / 32;
         int oldArraySize = bindingBitsSize / 32;
         bindingBits = (quint32 *)q_check_ptr(realloc(bindingBits,
                                          arraySize * sizeof(quint32)));
         memset(bindingBits + oldArraySize,
                0x00,
                sizeof(quint32) * (arraySize - oldArraySize));
         bindingBitsSize = arraySize * 32;
     }
     bindingBits[bit / 32] |= (1 << (bit % 32));
 }
setImplicitDestructible()
void QDeclarativeData::setImplicitDestructible () inline
Definition at line 99 of file qdeclarativedata_p.h.
Referenced by QDeclarativeEnginePrivate::createComponent(), QDeclarativeComponentPrivate::createObject(), QDeclarativeEnginePrivate::createQmlObject(), and QDeclarativeObjectMethodScriptClass::property().
{
         if (!explicitIndestructibleSet) indestructible = false;
     }
Properties
bindingBits
quint32* QDeclarativeData::bindingBits
Definition at line 121 of file qdeclarativedata_p.h.
Referenced by fastHasBinding().
bindingBitsSize
int QDeclarativeData::bindingBitsSize
Definition at line 120 of file qdeclarativedata_p.h.
Referenced by fastHasBinding().
bindings
QDeclarativeAbstractBinding* QDeclarativeData::bindings
Definition at line 114 of file qdeclarativedata_p.h.
Referenced by QDeclarativeAbstractBinding::addToObject(), QDeclarativePropertyPrivate::binding(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
columnNumber
ushort QDeclarativeData::columnNumber
Definition at line 127 of file qdeclarativedata_p.h.
Referenced by QDeclarativeEngineDebugService::objectData(), QDeclarativeVME::run(), and QDeclarativeInfo::~QDeclarativeInfo().
context
QDeclarativeContextData* QDeclarativeData::context
Definition at line 110 of file qdeclarativedata_p.h.
Referenced by QDeclarativeContextData::addObject(), QDeclarativeComponentPrivate::complete(), QDeclarativeContextData::destroy(), QDeclarativePrivate::qdeclarativeelement_destructor(), QDeclarativeComponent::qmlAttachedProperties(), qmlExecuteDeferred(), QDeclarativeVisualDataModel::release(), QDeclarativeVME::run(), QDeclarativeVME::runDeferred(), and QDeclarativeEngine::setContextForObject().
deferredComponent
QDeclarativeCompiledData* QDeclarativeData::deferredComponent
Definition at line 129 of file qdeclarativedata_p.h.
Referenced by qmlExecuteDeferred(), and QDeclarativeVME::runDeferred().
deferredIdx
unsigned int QDeclarativeData::deferredIdx
Definition at line 130 of file qdeclarativedata_p.h.
Referenced by QDeclarativeVME::runDeferred().
dummy
quint32 QDeclarativeData::dummy
Definition at line 107 of file qdeclarativedata_p.h.
explicitIndestructibleSet
quint32 QDeclarativeData::explicitIndestructibleSet
Definition at line 106 of file qdeclarativedata_p.h.
Referenced by QDeclarativeEngine::setObjectOwnership().
extendedData
QDeclarativeDataExtended* QDeclarativeData::extendedData mutable private
Definition at line 164 of file qdeclarativedata_p.h.
guards
QDeclarativeGuardImpl* QDeclarativeData::guards
Definition at line 138 of file qdeclarativedata_p.h.
Referenced by QDeclarativeGuardImpl::addGuard().
indestructible
quint32 QDeclarativeData::indestructible
Definition at line 105 of file qdeclarativedata_p.h.
Referenced by QDeclarativeComponent::beginCreate(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectScriptClass::newQObject(), QDeclarativeEngine::objectOwnership(), QDeclarativeEngine::setObjectOwnership(), and ObjectData::~ObjectData().
lineNumber
ushort QDeclarativeData::lineNumber
Definition at line 126 of file qdeclarativedata_p.h.
Referenced by QDeclarativeConnections::connectSignals(), QDeclarativeEngineDebugService::objectData(), qmlExecuteDeferred(), QDeclarativeVME::run(), and QDeclarativeInfo::~QDeclarativeInfo().
nextContextObject
QDeclarativeData* QDeclarativeData::nextContextObject
Definition at line 117 of file qdeclarativedata_p.h.
Referenced by QDeclarativeContextData::addObject(), QDeclarativeContextData::destroy(), and QDeclarativeVME::run().
objectDataRefCount
quint32 QDeclarativeData::objectDataRefCount
Definition at line 135 of file qdeclarativedata_p.h.
Referenced by ObjectData::ObjectData(), and ObjectData::~ObjectData().
outerContext
QDeclarativeContextData* QDeclarativeData::outerContext
Definition at line 112 of file qdeclarativedata_p.h.
Referenced by QDeclarativeContextData::addObject(), QDeclarativeConnections::connectSignals(), QDeclarativeEngine::contextForObject(), QDeclarativeContextData::destroy(), QDeclarativeEngineDebugService::objectData(), qmlExecuteDeferred(), QDeclarativeVME::run(), and QDeclarativeInfo::~QDeclarativeInfo().
ownContext
quint32 QDeclarativeData::ownContext
Definition at line 104 of file qdeclarativedata_p.h.
Referenced by QDeclarativePrivate::qdeclarativeelement_destructor(), and QDeclarativeVisualDataModel::release().
ownMemory
quint32 QDeclarativeData::ownMemory
Definition at line 103 of file qdeclarativedata_p.h.
Referenced by QDeclarativeCompiledData::TypeReference::createInstance().
prevContextObject
QDeclarativeData** QDeclarativeData::prevContextObject
Definition at line 118 of file qdeclarativedata_p.h.
Referenced by QDeclarativeContextData::addObject(), QDeclarativeContextData::destroy(), and QDeclarativeVME::run().
propertyCache
QDeclarativePropertyCache* QDeclarativeData::propertyCache
Definition at line 136 of file qdeclarativedata_p.h.
Referenced by QDeclarativePropertyPrivate::binding(), QDeclarativeCompiledData::TypeReference::createInstance(), QDeclarativePropertyPrivate::findAliasTarget(), flush_vme_signal(), QDeclarativePropertyCache::property(), QDeclarativeObjectScriptClass::propertyNames(), QDeclarativeObjectScriptClass::queryProperty(), QDeclarativeObjectMethodScriptClass::relatedMethod(), QDeclarativeVME::run(), QDeclarativePropertyPrivate::setBinding(), QDeclarativePropertyPrivate::setBindingNoEnable(), QDeclarativeOpenMetaObject::setCached(), and QDeclarativeVisualDataModel::stringValue().
scriptValue
QScriptValue* QDeclarativeData::scriptValue
Definition at line 134 of file qdeclarativedata_p.h.
Referenced by QDeclarativeObjectScriptClass::newQObject().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativedata_p.h
/src/declarative/qml/qdeclarativeengine.cpp