Qt 4.8: QUIKitScreen Class Reference
QUIKitScreen Class Reference
#include <quikitscreen.h>
Public Functions
int depth () const
Reimplement in subclass to return current depth of the screen.
QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
QUIKitScreen (int screenIndex)
UIScreen * uiScreen () const
void updateInterfaceOrientation ()
~QUIKitScreen ()
Public Functions inherited from QPlatformScreen
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual void setDirty (const QRect &)
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
int m_depth
QImage::Format m_format
QRect m_geometry
int m_index
QSize m_physicalSize
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 51 of file quikitscreen.h.
Constructors and Destructors
QUIKitScreen()
QUIKitScreen::QUIKitScreen (int screenIndex)
Definition at line 51 of file quikitscreen.mm.
     : QPlatformScreen(),
       m_index(screenIndex)
 {
     NSAutoreleasePool *pool = [[NSAutoreleasePool alloc] init];
     CGRect bounds = [uiScreen() bounds];
     CGFloat scale = [uiScreen() scale];
     updateInterfaceOrientation();
     m_format = QImage::Format_ARGB32_Premultiplied;
     m_depth = 24;
     const qreal inch = 25.4;
     qreal unscaledDpi = 160.;
     int dragDistance = 12 * scale;
     if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPad) {
         unscaledDpi = 132.;
         dragDistance = 10 * scale;
     }
     m_physicalSize = QSize(qRound(bounds.size.width * inch / unscaledDpi), qRound(bounds.size.height * inch / unscaledDpi));
     qApp->setStartDragDistance(dragDistance);
     QFont font; // system font is helvetica, so that is fine already
     font.setPixelSize([UIFont systemFontSize] * scale);
     qApp->setFont(font);
     [pool release];
 }
~QUIKitScreen()
QUIKitScreen::~QUIKitScreen ()
Definition at line 81 of file quikitscreen.mm.
 {
 }
Functions
depth()
int QUIKitScreen::depth () const inline virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 58 of file quikitscreen.h.
 { return m_depth; }
format()
QImage::Format QUIKitScreen::format () const inline virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 59 of file quikitscreen.h.
 { return m_format; }
geometry()
QRect QUIKitScreen::geometry () const inline virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 57 of file quikitscreen.h.
 { return m_geometry; }
physicalSize()
QSize QUIKitScreen::physicalSize () const inline virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented from QPlatformScreen.
Definition at line 60 of file quikitscreen.h.
 { return m_physicalSize; }
uiScreen()
UIScreen * QUIKitScreen::uiScreen () const
Definition at line 85 of file quikitscreen.mm.
Referenced by QUIKitWindow::ensureNativeWindow(), physicalSize(), QUIKitScreen(), and updateInterfaceOrientation().
 {
     return [[UIScreen screens] objectAtIndex:m_index];
 }
updateInterfaceOrientation()
void QUIKitScreen::updateInterfaceOrientation ()
Definition at line 90 of file quikitscreen.mm.
Referenced by physicalSize(), and QUIKitScreen().
 {
     CGRect bounds = [uiScreen() bounds];
     CGFloat scale = [uiScreen() scale];
     switch ([[UIApplication sharedApplication] statusBarOrientation]) {
     case UIInterfaceOrientationPortrait:
     case UIInterfaceOrientationPortraitUpsideDown:
         m_geometry = QRect(bounds.origin.x * scale, bounds.origin.y * scale,
                            bounds.size.width * scale, bounds.size.height * scale);;
         break;
     case UIInterfaceOrientationLandscapeLeft:
     case UIInterfaceOrientationLandscapeRight:
         m_geometry = QRect(bounds.origin.x * scale, bounds.origin.y * scale,
                            bounds.size.height * scale, bounds.size.width * scale);
         break;
     }
     foreach (QWidget *widget, qApp->topLevelWidgets()) {
         QUIKitWindow *platformWindow = static_cast<QUIKitWindow *>(widget->platformWindow());
         if (platformWindow && platformWindow->platformScreen() == this) {
             platformWindow->updateGeometryAndOrientation();
         }
     }
 }
Properties
m_depth
int QUIKitScreen::m_depth private
Definition at line 67 of file quikitscreen.h.
Referenced by depth(), and QUIKitScreen().
m_format
QImage::Format QUIKitScreen::m_format private
Definition at line 68 of file quikitscreen.h.
Referenced by format(), and QUIKitScreen().
m_geometry
QRect QUIKitScreen::m_geometry private
Definition at line 66 of file quikitscreen.h.
Referenced by geometry(), and updateInterfaceOrientation().
m_index
int QUIKitScreen::m_index private
Definition at line 70 of file quikitscreen.h.
Referenced by uiScreen().
m_physicalSize
QSize QUIKitScreen::m_physicalSize private
Definition at line 69 of file quikitscreen.h.
Referenced by physicalSize(), and QUIKitScreen().
The documentation for this class was generated from the following files:
/src/plugins/platforms/uikit/quikitscreen.h
/src/plugins/platforms/uikit/quikitscreen.mm