Qt 4.8: QMetaEnum Class Reference
QMetaEnum Class Reference
The QMetaEnum class provides meta-data about an enumerator.
#include <qmetaobject.h>
Public Functions
const QMetaObject * enclosingMetaObject () const
bool isFlag () const
Returns true if this enumerator is used as a flag; otherwise returns false.
bool isValid () const
Returns true if this enum is valid (has a name); otherwise returns false.
const char * key (int index) const
Returns the key with the given index, or 0 if no such key exists.
int keyCount () const
Returns the number of keys.
int keysToValue (const char *keys) const
Returns the value derived from combining together the values of the keys using the OR operator, or -1 if keys is not defined.
int keyToValue (const char *key) const
Returns the integer value of the given enumeration key, or -1 if key is not defined.
const char * name () const
Returns the name of the enumerator (without the scope).
QMetaEnum ()
const char * scope () const
Returns the scope this enumerator was declared in.
int value (int index) const
Returns the value with the given index; or returns -1 if there is no such value.
const char * valueToKey (int value) const
Returns the string that is used as the name of the given enumeration value, or 0 if value is not defined.
QByteArray valueToKeys (int value) const
Returns a byte array of '|'-separated keys that represents the given value.
Properties
uint handle
const QMetaObject * mobj
Friends
struct QMetaObject
Detailed Description
The QMetaEnum class provides meta-data about an enumerator.
Use name() for the enumerator's name. The enumerator's keys (names of each enumerated item) are returned by key(); use keyCount() to find the number of keys. isFlag() returns whether the enumerator is meant to be used as a flag, meaning that its values can be combined using the OR operator.
The conversion functions keyToValue(), valueToKey(), keysToValue(), and valueToKeys() allow conversion between the integer representation of an enumeration or set value and its literal representation. The scope() function returns the class scope this enumerator was declared in.
See also
QMetaObject, QMetaMethod, QMetaProperty
Definition at line 147 of file qmetaobject.h.
Constructors and Destructors
QMetaEnum()
QMetaEnum::QMetaEnum () inline
Warning
This function is not part of the public interface.
Definition at line 150 of file qmetaobject.h.
 : mobj(0),handle(0) {}
Functions
enclosingMetaObject()
const QMetaObject * QMetaEnum::enclosingMetaObject () const inline
Warning
This function is not part of the public interface.
Definition at line 166 of file qmetaobject.h.
 { return mobj; }
isFlag()
bool QMetaEnum::isFlag () const
Returns true if this enumerator is used as a flag; otherwise returns false.
When used as flags, enumerators can be combined using the OR operator.
See also
keysToValue(), valueToKeys()
Definition at line 1935 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addEnumerator(), classIDL(), and QMetaProperty::isFlagType().
 {
     return mobj && mobj->d.data[handle + 1];
 }
isValid()
bool QMetaEnum::isValid () const inline
Returns true if this enum is valid (has a name); otherwise returns false.
See also
name()
Definition at line 168 of file qmetaobject.h.
Referenced by QScript::callQtMethod(), and QMetaObject::property().
 { return name() != 0; }
key()
const char * QMetaEnum::key (int index) const
Returns the key with the given index, or 0 if no such key exists.
See also
keyCount(), value(), valueToKey()
Definition at line 1897 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addEnumerator(), classIDL(), QScript::QMetaObjectWrapperObject::deleteProperty(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertyNames(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), QScript::QMetaObjectWrapperObject::put(), and qax_generateDocumentation().
 {
     if (!mobj)
         return 0;
     int count = mobj->d.data[handle + 2];
     int data = mobj->d.data[handle + 3];
     if (index >= 0  && index < count)
         return mobj->d.stringdata + mobj->d.data[data + 2*index];
     return 0;
 }
keyCount()
int QMetaEnum::keyCount () const
Returns the number of keys.
See also
key()
Definition at line 1884 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addEnumerator(), classIDL(), QScript::QMetaObjectWrapperObject::deleteProperty(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertyNames(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), QScript::QMetaObjectWrapperObject::put(), and qax_generateDocumentation().
 {
     if (!mobj)
         return 0;
     return mobj->d.data[handle + 2];
 }
keysToValue()
int QMetaEnum::keysToValue (const char * keys) const
Returns the value derived from combining together the values of the keys using the OR operator, or -1 if keys is not defined.
Note that the strings in keys must be '|'-separated.
See also
isFlag(), valueToKey(), valueToKeys()
Definition at line 2011 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), QMetaProperty::write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     if (!mobj)
         return -1;
     QStringList l = QString::fromLatin1(keys).split(QLatin1Char('|'));
     //#### TODO write proper code, do not use QStringList
     int value = 0;
     int count = mobj->d.data[handle + 2];
     int data = mobj->d.data[handle + 3];
     for (int li = 0; li < l.size(); ++li) {
         QString trimmed = l.at(li).trimmed();
         QByteArray qualified_key = trimmed.toLatin1();
         const char *key = qualified_key.constData();
         uint scope = 0;
         const char *s = key + qstrlen(key);
         while (s > key && *s != ':')
             --s;
         if (s > key && *(s-1)==':') {
             scope = s - key - 1;
             key += scope + 2;
         }
         int i;
         for (i = count-1; i >= 0; --i)
             if ((!scope || (qstrlen(mobj->d.stringdata) == scope && strncmp(qualified_key.constData(), mobj->d.stringdata, scope) == 0))
                  && strcmp(key, mobj->d.stringdata + mobj->d.data[data + 2*i]) == 0) {
                 value |= mobj->d.data[data + 2*i + 1];
                 break;
             }
         if (i < 0)
             value |= -1;
     }
     return value;
 }
keyToValue()
int QMetaEnum::keyToValue (const char * key) const
Returns the integer value of the given enumeration key, or -1 if key is not defined.
For flag types, use keysToValue().
See also
valueToKey(), isFlag(), keysToValue()
Definition at line 1962 of file qmetaobject.cpp.
Referenced by QScript::callQtMethod(), QAxBase::dynamicCallHelper(), QDeclarativeCompiler::evaluateEnum(), QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), QMetaProperty::write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     if (!mobj || !key)
         return -1;
     uint scope = 0;
     const char *qualified_key = key;
     const char *s = key + qstrlen(key);
     while (s > key && *s != ':')
         --s;
     if (s > key && *(s-1)==':') {
         scope = s - key - 1;
         key += scope + 2;
     }
     int count = mobj->d.data[handle + 2];
     int data = mobj->d.data[handle + 3];
     for (int i = 0; i < count; ++i)
         if ((!scope || (qstrlen(mobj->d.stringdata) == scope && strncmp(qualified_key, mobj->d.stringdata, scope) == 0))
              && strcmp(key, mobj->d.stringdata + mobj->d.data[data + 2*i]) == 0)
             return mobj->d.data[data + 2*i + 1];
     return -1;
 }
name()
const char * QMetaEnum::name () const
Returns the name of the enumerator (without the scope).
For example, the Qt::AlignmentFlag enumeration has AlignmentFlag as the name and Qt as the scope.
See also
isValid(), scope()
Definition at line 1872 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addEnumerator(), classIDL(), QDeclarativeObjectMethodScriptClass::enumType(), for(), QScript::indexOfMetaEnum(), QMetaProperty::isEnumType(), qax_generateDocumentation(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), qualifiedName(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     if (!mobj)
         return 0;
     return mobj->d.stringdata + mobj->d.data[handle];
 }
scope()
const char * QMetaEnum::scope () const
Returns the scope this enumerator was declared in.
For example, the Qt::AlignmentFlag enumeration has Qt as the scope and AlignmentFlag as the name.
See also
name()
Definition at line 1949 of file qmetaobject.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::enumType(), QScript::indexOfMetaEnum(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), qualifiedName(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     return mobj?mobj->d.stringdata : 0;
 }
value()
int QMetaEnum::value (int index) const
Returns the value with the given index; or returns -1 if there is no such value.
See also
keyCount(), key(), keyToValue()
Definition at line 1914 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addEnumerator(), classIDL(), QScript::QMetaObjectWrapperObject::getOwnPropertyDescriptor(), QScript::QMetaObjectWrapperObject::getOwnPropertySlot(), and qax_generateDocumentation().
 {
     if (!mobj)
         return 0;
     int count = mobj->d.data[handle + 2];
     int data = mobj->d.data[handle + 3];
     if (index >= 0  && index < count)
         return mobj->d.data[data + 2*index + 1];
     return -1;
 }
valueToKey()
const char * QMetaEnum::valueToKey (int value) const
Returns the string that is used as the name of the given enumeration value, or 0 if value is not defined.
For flag types, use valueToKeys().
See also
isFlag(), valueToKeys()
Definition at line 1992 of file qmetaobject.cpp.
Referenced by QScript::callQtMethod(), QAxBase::dynamicCallHelper(), QBBButtonEventNotifier::QBBButtonEventNotifier(), QmlJSDebugger::InspectorProtocol::toString(), and QGLEngineSharedShaders::~QGLEngineSharedShaders().
 {
     if (!mobj)
         return 0;
     int count = mobj->d.data[handle + 2];
     int data = mobj->d.data[handle + 3];
     for (int i = 0; i < count; ++i)
         if (value == (int)mobj->d.data[data + 2*i + 1])
             return mobj->d.stringdata + mobj->d.data[data + 2*i];
     return 0;
 }
valueToKeys()
QByteArray QMetaEnum::valueToKeys (int value) const
Returns a byte array of '|'-separated keys that represents the given value.
See also
isFlag(), valueToKey(), keysToValue()
Definition at line 2051 of file qmetaobject.cpp.
 {
     QByteArray keys;
     if (!mobj)
         return keys;
     int count = mobj->d.data[handle + 2];
     int data = mobj->d.data[handle + 3];
     int v = value;
     for(int i = 0; i < count; i++) {
         int k = mobj->d.data[data + 2*i + 1];
         if ((k != 0 && (v & k) == k ) ||  (k == value))  {
             v = v & ~k;
             if (!keys.isEmpty())
                 keys += '|';
             keys += mobj->d.stringdata + mobj->d.data[data + 2*i];
         }
     }
     return keys;
 }
Friends and Related Functions
QMetaObject
friend struct QMetaObject friend
Definition at line 172 of file qmetaobject.h.
Properties
handle
uint QMetaEnum::handle private
Definition at line 171 of file qmetaobject.h.
Referenced by QMetaObject::enumerator().
mobj
const QMetaObject* QMetaEnum::mobj private
Definition at line 170 of file qmetaobject.h.
Referenced by QMetaObject::enumerator().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qmetaobject.h
/src/corelib/kernel/qmetaobject.cpp