Qt 4.8: QUndoCommand Class Reference
QUndoCommand Class Reference
The QUndoCommand class is the base class of all commands stored on a QUndoStack.
#include <qundostack.h>
Public Functions
QString actionText () const
Returns a short text string describing what this command does; for example, "insert text".
const QUndoCommand * child (int index) const
Returns the child command at index.
int childCount () const
Returns the number of child commands in this command.
virtual int id () const
Returns the ID of this command.
virtual bool mergeWith (const QUndoCommand *other)
Attempts to merge this command with command.
QUndoCommand (QUndoCommand *parent=0)
Constructs a QUndoCommand object with parent parent.
QUndoCommand (const QString &text, QUndoCommand *parent=0)
Constructs a QUndoCommand object with the given parent and text.
virtual void redo ()
Applies a change to the document.
void setText (const QString &text)
Sets the command's text to be the text specified.
QString text () const
Returns a short text string describing what this command does; for example, "insert text".
virtual void undo ()
Reverts a change to the document.
virtual ~QUndoCommand ()
Destroys the QUndoCommand object and all child commands.
Properties
QUndoCommandPrivate * d
Friends
class QUndoStack
Detailed Description
The QUndoCommand class is the base class of all commands stored on a QUndoStack.
Since
4.2
For an overview of Qt's Undo Framework, see the Overview of Qt's Undo Framework{overview document}.
A QUndoCommand represents a single editing action on a document; for example, inserting or deleting a block of text in a text editor. QUndoCommand can apply a change to the document with redo() and undo the change with undo(). The implementations for these functions must be provided in a derived class.
class AppendText : public QUndoCommand
{
public:
    AppendText(QString *doc, const QString &text)
        : m_document(doc), m_text(text) { setText("append text"); }
    virtual void undo()
        { m_document->chop(m_text.length()); }
    virtual void redo()
        { m_document->append(m_text); }
private:
    QString *m_document;
    QString m_text;
};
A QUndoCommand has an associated text(). This is a short string describing what the command does. It is used to update the text properties of the stack's undo and redo actions; see QUndoStack::createUndoAction() and QUndoStack::createRedoAction().
QUndoCommand objects are owned by the stack they were pushed on. QUndoStack deletes a command if it has been undone and a new command is pushed. For example:
MyCommand *command1 = new MyCommand();
stack->push(command1);
MyCommand *command2 = new MyCommand();
stack->push(command2);
stack->undo();
MyCommand *command3 = new MyCommand();
stack->push(command3); // command2 gets deleted
In effect, when a command is pushed, it becomes the top-most command on the stack.
To support command compression, QUndoCommand has an id() and the virtual function mergeWith(). These functions are used by QUndoStack::push().
To support command macros, a QUndoCommand object can have any number of child commands. Undoing or redoing the parent command will cause the child commands to be undone or redone. A command can be assigned to a parent explicitly in the constructor. In this case, the command will be owned by the parent.
The parent in this case is usually an empty command, in that it doesn't provide its own implementation of undo() and redo(). Instead, it uses the base implementations of these functions, which simply call undo() or redo() on all its children. The parent should, however, have a meaningful text().
QUndoCommand *insertRed = new QUndoCommand(); // an empty command
insertRed->setText("insert red text");
new InsertText(document, idx, text, insertRed); // becomes child of insertRed
new SetColor(document, idx, text.length(), Qt::red, insertRed);
stack.push(insertRed);
Another way to create macros is to use the convenience functions QUndoStack::beginMacro() and QUndoStack::endMacro().
See also
QUndoStack
Definition at line 60 of file qundostack.h.
Constructors and Destructors
QUndoCommand() [1/2]
QUndoCommand::QUndoCommand (QUndoCommand * parent = 0) explicit
Constructs a QUndoCommand object with parent parent.
If parent is not 0, this command is appended to parent's child list. The parent command then owns this command and will delete it in its destructor.
See also
~QUndoCommand()
Definition at line 133 of file qundostack.cpp.
 {
     d = new QUndoCommandPrivate;
     if (parent != 0)
         parent->d->child_list.append(this);
 }
QUndoCommand() [2/2]
QUndoCommand::QUndoCommand (const QString & text, QUndoCommand * parent = 0) explicit
Constructs a QUndoCommand object with the given parent and text.
If parent is not 0, this command is appended to parent's child list. The parent command then owns this command and will delete it in its destructor.
See also
~QUndoCommand()
Definition at line 115 of file qundostack.cpp.
 {
     d = new QUndoCommandPrivate;
     if (parent != 0)
         parent->d->child_list.append(this);
     setText(text);
 }
~QUndoCommand()
QUndoCommand::~QUndoCommand () virtual
Destroys the QUndoCommand object and all child commands.
See also
QUndoCommand()
Definition at line 146 of file qundostack.cpp.
 {
     qDeleteAll(d->child_list);
     delete d;
 }
Functions
actionText()
QString QUndoCommand::actionText () const
Returns a short text string describing what this command does; for example, "insert text".
Since
4.8
The text is used when the text properties of the stack's undo and redo actions are updated.
See also
text(), setText(), QUndoStack::createUndoAction(), QUndoStack::createRedoAction()
Definition at line 261 of file qundostack.cpp.
 {
     return d->actionText;
 }
child()
const QUndoCommand * QUndoCommand::child (int index) const
Returns the child command at index.
Since
4.4
See also
childCount(), QUndoStack::command()
Definition at line 320 of file qundostack.cpp.
 {
     if (index < 0 || index >= d->child_list.count())
         return 0;
     return d->child_list.at(index);
 }
childCount()
int QUndoCommand::childCount () const
Returns the number of child commands in this command.
Since
4.4
See also
child()
Definition at line 304 of file qundostack.cpp.
 {
     return d->child_list.count();
 }
id()
int QUndoCommand::id () const virtual
Returns the ID of this command.
A command ID is used in command compression. It must be an integer unique to this command's class, or -1 if the command doesn't support compression.
If the command supports compression this function must be overridden in the derived class to return the correct ID. The base implementation returns -1.
QUndoStack::push() will only try to merge two commands if they have the same ID, and the ID is not -1.
See also
mergeWith(), QUndoStack::push()
Definition at line 167 of file qundostack.cpp.
Referenced by QUndoStack::push().
 {
     return -1;
 }
mergeWith()
bool QUndoCommand::mergeWith (const QUndoCommand * command) virtual
Attempts to merge this command with command.
Returns true on success; otherwise returns false.
If this function returns true, calling this command's redo() must have the same effect as redoing both this command and command. Similarly, calling this command's undo() must have the same effect as undoing command and this command.
QUndoStack will only try to merge two commands if they have the same id, and the id is not -1.
The default implementation returns false.
bool AppendText::mergeWith(const QUndoCommand *other)
{
    if (other->id() != id()) // make sure other is also an AppendText command
        return false;
    m_text += static_cast<const AppendText*>(other)->m_text;
    return true;
}
See also
id() QUndoStack::push()
Definition at line 191 of file qundostack.cpp.
Referenced by QUndoStack::push().
 {
     Q_UNUSED(command);
     return false;
 }
redo()
void QUndoCommand::redo () virtual
Applies a change to the document.
This function must be implemented in the derived class. Calling QUndoStack::push(), QUndoStack::undo() or QUndoStack::redo() from this function leads to undefined beahavior.
The default implementation calls redo() on all child commands.
See also
undo()
Definition at line 208 of file qundostack.cpp.
Referenced by QUndoStack::push(), and redo().
 {
     for (int i = 0; i < d->child_list.size(); ++i)
         d->child_list.at(i)->redo();
 }
setText()
void QUndoCommand::setText (const QString & text)
Sets the command's text to be the text specified.
The specified text should be a short user-readable string describing what this command does.
If you need to have two different strings for text() and actionText(), separate them with "\n" and pass into this function. Even if you do not use this feature for English strings during development, you can still let translators use two different strings in order to match specific languages' needs. The described feature and the function actionText() are available since Qt 4.8.
See also
text() actionText() QUndoStack::createUndoAction() QUndoStack::createRedoAction()
Definition at line 281 of file qundostack.cpp.
Referenced by QUndoStack::beginMacro(), and QUndoCommand().
 {
     int cdpos = text.indexOf(QLatin1Char('\n'));
     if (cdpos > 0) {
         d->text = text.left(cdpos);
         d->actionText = text.mid(cdpos + 1);
     } else {
         d->text = text;
         d->actionText = text;
     }
 }
text()
QString QUndoCommand::text () const
Returns a short text string describing what this command does; for example, "insert text".
The text is used for names of items in QUndoView.
See also
actionText(), setText(), QUndoStack::createUndoAction(), QUndoStack::createRedoAction()
Definition at line 241 of file qundostack.cpp.
Referenced by setText().
 {
     return d->text;
 }
undo()
void QUndoCommand::undo () virtual
Reverts a change to the document.
After undo() is called, the state of the document should be the same as before redo() was called. This function must be implemented in the derived class. Calling QUndoStack::push(), QUndoStack::undo() or QUndoStack::redo() from this function leads to undefined beahavior.
The default implementation calls undo() on all child commands in reverse order.
See also
redo()
Definition at line 226 of file qundostack.cpp.
Referenced by undo().
 {
     for (int i = d->child_list.size() - 1; i >= 0; --i)
         d->child_list.at(i)->undo();
 }
Friends and Related Functions
QUndoStack
friend class QUndoStack friend
Definition at line 84 of file qundostack.h.
Properties
d
QUndoCommandPrivate* QUndoCommand::d private
Definition at line 62 of file qundostack.h.
Referenced by actionText(), child(), childCount(), QUndoStack::push(), QUndoCommand(), redo(), setText(), text(), undo(), and ~QUndoCommand().
The documentation for this class was generated from the following files:
/src/gui/util/qundostack.h
/src/gui/util/qundostack.cpp