Qt 4.8: QPixmapData Class Reference
QPixmapData Class Reference abstract
#include <qpixmapdata_p.h>
Public Types
enum ClassId {
RasterClass, X11Class, MacClass, DirectFBClass,
OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
CustomClass = 1024
}
enum PixelType { PixmapType, BitmapType }
Public Functions
virtual QPixmap alphaChannel () const
virtual QImage * buffer ()
qint64 cacheKey () const
ClassId classId () const
int colorCount () const
virtual void copy (const QPixmapData *data, const QRect &rect)
virtual QPixmapData * createCompatiblePixmapData () const
int depth () const
virtual void fill (const QColor &color)=0
virtual bool fromData (const uchar *buffer, uint len, const char *format, Qt::ImageConversionFlags flags)
virtual bool fromFile (const QString &filename, const char *format, Qt::ImageConversionFlags flags)
virtual void fromImage (const QImage &image, Qt::ImageConversionFlags flags)=0
virtual void fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags)
virtual bool hasAlphaChannel () const =0
int height () const
bool isNull () const
virtual QBitmap mask () const
virtual int metric (QPaintDevice::PaintDeviceMetric metric) const =0
QT_DEPRECATED int numColors () const
virtual QPaintEngine * paintEngine () const =0
PixelType pixelType () const
QPixmapData (PixelType pixelType, int classId)
virtual void resize (int width, int height)=0
virtual QPixmapData * runtimeData () const
virtual bool scroll (int dx, int dy, const QRect &rect)
int serialNumber () const
virtual void setAlphaChannel (const QPixmap &alphaChannel)
virtual void setMask (const QBitmap &mask)
virtual QImage toImage () const =0
virtual QImage toImage (const QRect &rect) const
virtual QPixmap transformed (const QTransform &matrix, Qt::TransformationMode mode) const
int width () const
virtual ~QPixmapData ()
Static Public Functions
static QPixmapData * create (int w, int h, PixelType type)
Protected Functions
void setSerialNumber (int serNo)
Protected Variables
int d
int h
bool is_null
int w
Properties
int detach_no
int id
uint is_cached
QAtomicInt ref
int ser_no
PixelType type
Friends
class QExplicitlySharedDataPointer< QPixmapData >
class QGLTextureCache
class QImagePixmapCleanupHooks
class QPixmap
class QSymbianRasterPixmapData
class QX11PixmapData
Detailed Description
Definition at line 67 of file qpixmapdata_p.h.
Enumerations
ClassId
enum QPixmapData::ClassId
Enumerator
RasterClass
X11Class
MacClass
DirectFBClass
OpenGLClass
OpenVGClass
RuntimeClass
BlitterClass
CustomClass
Definition at line 83 of file qpixmapdata_p.h.
                  { RasterClass, X11Class, MacClass, DirectFBClass,
                    OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
                    CustomClass = 1024 };
PixelType
enum QPixmapData::PixelType
Enumerator
PixmapType
BitmapType
Definition at line 70 of file qpixmapdata_p.h.
                    {
         // WARNING: Do not change the first two
         // Must match QPixmap::Type
         PixmapType, BitmapType
     };
Constructors and Destructors
QPixmapData()
QPixmapData::QPixmapData (PixelType pixelType, int classId)
Definition at line 68 of file qpixmapdata.cpp.
     : w(0),
       h(0),
       d(0),
       is_null(true),
       ref(0),
       detach_no(0),
       type(pixelType),
       id(objectId),
       ser_no(0),
       is_cached(false)
 {
 }
~QPixmapData()
QPixmapData::~QPixmapData () virtual
Definition at line 82 of file qpixmapdata.cpp.
 {
     // Sometimes the pixmap cleanup hooks will be called from derrived classes, which will
     // then set is_cached to false. For example, on X11 QtOpenGL needs to delete the GLXPixmap
     // or EGL Pixmap Surface for a given pixmap _before_ the native X11 pixmap is deleted,
     // otherwise some drivers will leak the GL surface. In this case, QX11PixmapData will
     // call the cleanup hooks itself before deleting the native pixmap and set is_cached to
     // false.
     if (is_cached) {
         QImagePixmapCleanupHooks::executePixmapDataDestructionHooks(this);
         is_cached = false;
     }
 }
Functions
alphaChannel()
QPixmap QPixmapData::alphaChannel () const virtual
Reimplemented in QRuntimePixmapData, QX11PixmapData, and QMacPixmapData.
Definition at line 255 of file qpixmapdata.cpp.
Referenced by QRuntimePixmapData::alphaChannel(), and QPixmap::alphaChannel().
 {
     return QPixmap::fromImage(toImage().alphaChannel());
 }
buffer()
QImage * QPixmapData::buffer () virtual
Reimplemented in QVGPixmapData, QRuntimePixmapData, QRasterPixmapData, QDirectFBPixmapData, and QBlittablePixmapData.
Definition at line 273 of file qpixmapdata.cpp.
Referenced by QRasterPaintEngine::begin(), QRuntimePixmapData::buffer(), QVGPaintEngine::drawPixmap(), QGLPixmapData::fromData(), qt_mac_cg_context(), qt_mac_flipPixmap(), qt_mac_grabScreenRect(), and QVGPaintEnginePrivate::setBrush().
 {
     return 0;
 }
cacheKey()
qint64 QPixmapData::cacheKey () const inline
Definition at line 132 of file qpixmapdata_p.h.
Referenced by QPixmap::cacheKey(), QImagePixmapCleanupHooks::executePixmapDataDestructionHooks(), QImagePixmapCleanupHooks::executePixmapDataModificationHooks(), and QGLBlurTextureCache::pixmapDestroyed().
{
         int classKey = id;
         if (classKey >= 1024)
             classKey = -(classKey >> 10);
         return ((((qint64) classKey) << 56)
                 | (((qint64) ser_no) << 32)
                 | ((qint64) detach_no));
     }
classId()
ClassId QPixmapData::classId () const inline
Definition at line 122 of file qpixmapdata_p.h.
Referenced by QDirectFBPaintEngine::begin(), QRasterPaintEngine::begin(), QGLContextPrivate::bindTextureFromNativePixmap(), CapabilitiesToStateMask::canBlitterDrawPixmap(), CapabilitiesToStateMask::canBlitterDrawPixmapOpacity(), QPixmap::clut(), QPixmap::colorCount(), QMeeGoRasterPixmapData::copy(), QDirectFBPixmapData::copy(), QVGPixmapData::copy(), QGLPixmapData::copy(), QMeeGoGraphicsSystem::createPixmapData(), QEgl::createSurface(), QPixmap::depth(), QGLContextPrivate::destroyGlSurfaceForPixmap(), QMeeGoLivePixmapData::destroySurfaceForPixmapData(), QPixmap::detach(), QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), QVGPixmapBlurFilter::draw(), QVGCompositionHelper::drawCursorPixmap(), QDirectFBPaintEngine::drawPixmap(), QVGPaintEngine::drawPixmap(), QRasterPaintEngine::drawPixmap(), QVGPaintEngine::drawPixmapFragments(), QDirectFBPaintEngine::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QGLContextPrivate::eglSurfaceForDevice(), QDirectFBPaintEngine::fillRect(), QGLPaintDevice::getDevice(), QMeeGoLivePixmapData::getSurfaceForBackingPixmap(), QPixmap::handle(), QPixmap::hasAlpha(), QPixmapCacheEntry::QPixmapCacheEntry(), qPixmapToVGImage(), qt_directfb_surface_for_pixmap(), qt_mac_cg_context(), qt_toRasterPixmap(), qt_toX11Pixmap(), QPixmap::qwsBits(), QPixmap::qwsBytesPerLine(), QX11GLWindowSurface::scroll(), QVGPaintEnginePrivate::setBrush(), QPixmap::toWinHBITMAP(), QGLContextPrivate::unbindPixmapFromTexture(), and QMeeGoGraphicsSystem::updateEGLSharedImagePixmap().
 { return static_cast<ClassId>(id); }
colorCount()
int QPixmapData::colorCount () const inline
Definition at line 129 of file qpixmapdata_p.h.
 { return metric(QPaintDevice::PdmNumColors); }
copy()
void QPixmapData::copy (const QPixmapData * data, const QRect & rect) virtual
Reimplemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRasterPixmapData, QRuntimePixmapData, QX11GLPixmapData, QDirectFBPixmapData, QMacPixmapData, and QMeeGoRasterPixmapData.
Definition at line 154 of file qpixmapdata.cpp.
Referenced by QDirectFBPixmapData::copy(), QRuntimePixmapData::copy(), QGLPixmapData::copy(), QPixmap::copy(), and QBlittablePixmapData::paintEngine().
 {
     fromImage(data->toImage(rect), Qt::NoOpaqueDetection);
 }
create()
QPixmapData * QPixmapData::create (int w, int h, PixelType type) static
Definition at line 55 of file qpixmapdata.cpp.
Referenced by QPixmap::init(), QPixmap::load(), and QPixmap::loadFromData().
 {
     QPixmapData *data;
     QGraphicsSystem* gs = QApplicationPrivate::graphicsSystem();
     if (gs)
         data = gs->createPixmapData(static_cast<QPixmapData::PixelType>(type));
     else
         data = QGraphicsSystem::createDefaultPixmapData(static_cast<QPixmapData::PixelType>(type));
     data->resize(w, h);
     return data;
 }
createCompatiblePixmapData()
QPixmapData * QPixmapData::createCompatiblePixmapData () const virtual
Reimplemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRasterPixmapData, QRuntimePixmapData, QMacPixmapData, QMeeGoLivePixmapData, and QMeeGoPixmapData.
Definition at line 96 of file qpixmapdata.cpp.
Referenced by QPixmap::copy(), QRuntimePixmapData::createCompatiblePixmapData(), and QPixmap::fill().
 {
     QPixmapData *d;
     QGraphicsSystem *gs = QApplicationPrivate::graphicsSystem();
     if (gs)
         d = gs->createPixmapData(pixelType());
     else
         d = QGraphicsSystem::createDefaultPixmapData(pixelType());
     return d;
 }
depth()
int QPixmapData::depth () const inline
Definition at line 130 of file qpixmapdata_p.h.
Referenced by QX11PaintEngine::begin(), QX11PixmapData::canTakeQImageFromXImage(), QX11PixmapData::convertToARGB32(), QEgl::createSurface(), QPixmap::depth(), QX11PaintEngine::drawPixmap(), QX11PixmapData::fill(), qt_mac_create_iconref(), qt_mac_create_imagemask(), QRuntimePixmapData::readBackInfo(), QX11PixmapData::setMask(), setMask(), QX11PixmapData::takeQImageFromXImage(), QX11PixmapData::toImage(), and QX11PixmapData::transformed().
 { return d; }
fill()
virtual void QPixmapData::fill (const QColor & color) pure virtual
Implemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRuntimePixmapData, QRasterPixmapData, QDirectFBPixmapData, QX11GLPixmapData, QMacPixmapData, and QBlittablePixmapData.
Referenced by QRuntimePixmapData::fill(), and QPixmap::fill().
fromData()
bool QPixmapData::fromData (const uchar * buffer, uint len, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented in QGLPixmapData, QVGPixmapData, QRuntimePixmapData, QRasterPixmapData, and QDirectFBPixmapData.
Definition at line 144 of file qpixmapdata.cpp.
Referenced by QDirectFBPixmapData::fromData(), QRuntimePixmapData::fromData(), and QPixmap::loadFromData().
 {
     QByteArray a = QByteArray::fromRawData(reinterpret_cast<const char *>(buf), len);
     QBuffer b(&a);
     b.open(QIODevice::ReadOnly);
     QImage image = QImageReader(&b, format).read();
     fromImage(makeBitmapCompliantIfNeeded(this, image, flags), flags);
     return !isNull();
 }
fromFile()
bool QPixmapData::fromFile (const QString & filename, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented in QGLPixmapData, QVGPixmapData, QDirectFbBlitterPlatformPixmap, QRuntimePixmapData, and QDirectFBPixmapData.
Definition at line 134 of file qpixmapdata.cpp.
Referenced by QDirectFBPixmapData::fromFile(), QRuntimePixmapData::fromFile(), QDirectFbBlitterPlatformPixmap::fromFile(), QGLPixmapData::fromFile(), and QPixmap::load().
 {
     QImage image = QImageReader(fileName, format).read();
     if (image.isNull())
         return false;
     fromImage(makeBitmapCompliantIfNeeded(this, image, flags), flags);
     return !isNull();
 }
fromImage()
virtual void QPixmapData::fromImage (const QImage & image, Qt::ImageConversionFlags flags) pure virtual
Implemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRasterPixmapData, QMacPixmapData, QRuntimePixmapData, QDirectFBPixmapData, QBlittablePixmapData, and QMeeGoPixmapData.
Referenced by QPixmap::convertFromImage(), copy(), fromData(), fromFile(), QBitmap::fromImage(), QRuntimePixmapData::fromImage(), QPixmap::fromImage(), fromImageReader(), qt_toRasterPixmap(), qt_toX11Pixmap(), setAlphaChannel(), QRuntimeGraphicsSystem::setGraphicsSystem(), setMask(), and QPixmap::toWinHBITMAP().
fromImageReader()
void QPixmapData::fromImageReader (QImageReader * imageReader, Qt::ImageConversionFlags flags) virtual
Reimplemented in QGLPixmapData, QVGPixmapData, and QRasterPixmapData.
Definition at line 127 of file qpixmapdata.cpp.
Referenced by QPixmap::fromImageReader().
 {
     const QImage image = imageReader->read();
     fromImage(image, flags);
 }
hasAlphaChannel()
virtual bool QPixmapData::hasAlphaChannel () const pure virtual
Implemented in QGLPixmapData, QVGPixmapData, QDirectFBPixmapData, QX11PixmapData, QRuntimePixmapData, QRasterPixmapData, QMacPixmapData, and QBlittablePixmapData.
Referenced by QDirectFBPixmapData::copy(), QPixmap::hasAlpha(), QRuntimePixmapData::hasAlphaChannel(), QPixmap::hasAlphaChannel(), and mask().
height()
int QPixmapData::height () const inline
Definition at line 127 of file qpixmapdata_p.h.
Referenced by checkForAlphaPixels(), QX11PixmapData::convertToARGB32(), QX11PixmapData::fill(), QPixmap::fill(), QPixmap::height(), QMeeGoLivePixmapData::lock(), QMacPixmapData::macCreatePixels(), qt_mac_create_iconref(), QRuntimePixmapData::readBackInfo(), QPixmap::rect(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QGLPixmapData::resize(), QX11PixmapData::setMask(), QPixmap::size(), QEglProperties::toString(), and QX11PixmapData::transformed().
 { return h; }
isNull()
bool QPixmapData::isNull () const inline
Definition at line 131 of file qpixmapdata_p.h.
Referenced by QMeeGoGraphicsSystem::createPixmapData(), QRasterPixmapData::fromData(), QVGPixmapData::fromData(), fromData(), QGLPixmapData::fromData(), QVGPixmapData::fromFile(), fromFile(), QGLPixmapData::fromFile(), QPixmap::grabWindow(), QPixmap::isNull(), QRuntimePixmapData::readBackInfo(), and QX11PixmapData::transformed().
 { return is_null; }
mask()
QBitmap QPixmapData::mask () const virtual
Reimplemented in QX11PixmapData, QRuntimePixmapData, and QMacPixmapData.
Definition at line 208 of file qpixmapdata.cpp.
Referenced by QRuntimePixmapData::mask(), and QPixmap::mask().
 {
     if (!hasAlphaChannel())
         return QBitmap();
     const QImage img = toImage();
     const QImage image = (img.depth() < 32 ? img.convertToFormat(QImage::Format_ARGB32_Premultiplied) : img);
     const int w = image.width();
     const int h = image.height();
     QImage mask(w, h, QImage::Format_MonoLSB);
     if (mask.isNull()) // allocation failed
         return QBitmap();
     mask.setColorCount(2);
     mask.setColor(0, QColor(Qt::color0).rgba());
     mask.setColor(1, QColor(Qt::color1).rgba());
     const int bpl = mask.bytesPerLine();
     for (int y = 0; y < h; ++y) {
         const QRgb *src = reinterpret_cast<const QRgb*>(image.scanLine(y));
         uchar *dest = mask.scanLine(y);
         memset(dest, 0, bpl);
         for (int x = 0; x < w; ++x) {
             if (qAlpha(*src) > 0)
                 dest[x >> 3] |= qt_pixmap_bit_mask[x & 7];
             ++src;
         }
     }
     return QBitmap::fromImage(mask);
 }
metric()
virtual int QPixmapData::metric (QPaintDevice::PaintDeviceMetric metric) const pure virtual
Implemented in QVGPixmapData, QGLPixmapData, QX11PixmapData, QRasterPixmapData, QDirectFBPixmapData, QRuntimePixmapData, QMacPixmapData, and QBlittablePixmapData.
Referenced by QRuntimePixmapData::metric(), QPixmap::metric(), and QVGPixmapData::size().
numColors()
QT_DEPRECATED int QPixmapData::numColors () const inline
Definition at line 128 of file qpixmapdata_p.h.
Referenced by QMacPixmapData::fromImage().
 { return metric(QPaintDevice::PdmNumColors); }
paintEngine()
virtual QPaintEngine* QPixmapData::paintEngine () const pure virtual
Implemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRuntimePixmapData, QRasterPixmapData, QMacPixmapData, QX11GLPixmapData, QDirectFBPixmapData, and QBlittablePixmapData.
Referenced by QRuntimePixmapData::paintEngine(), and QPixmap::paintEngine().
pixelType()
PixelType QPixmapData::pixelType () const inline
Definition at line 121 of file qpixmapdata_p.h.
Referenced by QMacPixmapData::copy(), QX11PixmapData::copy(), QMeeGoPixmapData::createCompatiblePixmapData(), QMeeGoLivePixmapData::createCompatiblePixmapData(), QMacPixmapData::createCompatiblePixmapData(), QRuntimePixmapData::createCompatiblePixmapData(), QRasterPixmapData::createCompatiblePixmapData(), QX11PixmapData::createCompatiblePixmapData(), QVGPixmapData::createCompatiblePixmapData(), createCompatiblePixmapData(), QGLPixmapData::createCompatiblePixmapData(), QMeeGoGraphicsSystem::createPixmapData(), QGraphicsSystem::createPixmapData(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QGLPixmapData::fillImage(), QGLPixmapData::fromFile(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QPixmap::handle(), QPixmap::load(), QMacPixmapData::macCreatePixels(), makeBitmapCompliantIfNeeded(), QPixmap::QPixmap(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QGLPixmapData::resize(), QVGPaintEnginePrivate::setBrush(), QX11PixmapData::setMask(), and QMeeGoGraphicsSystem::wrapPixmapData().
 { return type; }
resize()
virtual void QPixmapData::resize (int width, int height) pure virtual
Implemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRasterPixmapData, QMacPixmapData, QRuntimePixmapData, QDirectFBPixmapData, and QBlittablePixmapData.
Referenced by QFontEngineXLFD::bitmapForGlyphs(), create(), QPixmap::fill(), and QRuntimePixmapData::resize().
runtimeData()
virtual QPixmapData* QPixmapData::runtimeData () const inline virtual
Reimplemented in QRuntimePixmapData.
Definition at line 149 of file qpixmapdata_p.h.
Referenced by QRuntimePixmapData::copy(), and QPixmap::pixmapData().
 { return 0; }
scroll()
bool QPixmapData::scroll (int dx, int dy, const QRect & rect) virtual
Reimplemented in QGLPixmapData, QDirectFBPixmapData, QX11PixmapData, QRasterPixmapData, QRuntimePixmapData, QX11GLPixmapData, QMacPixmapData, and QMeeGoLivePixmapData.
Definition at line 159 of file qpixmapdata.cpp.
Referenced by QRuntimePixmapData::scroll(), and QPixmap::scroll().
 {
     Q_UNUSED(dx);
     Q_UNUSED(dy);
     Q_UNUSED(rect);
     return false;
 }
serialNumber()
int QPixmapData::serialNumber () const inline
Definition at line 119 of file qpixmapdata_p.h.
Referenced by QDirectFBPixmapData::fill(), and QPixmap::serialNumber().
 { return ser_no; }
setAlphaChannel()
void QPixmapData::setAlphaChannel (const QPixmap & alphaChannel) virtual
Reimplemented in QVGPixmapData, QRuntimePixmapData, QX11PixmapData, QRasterPixmapData, and QMacPixmapData.
Definition at line 248 of file qpixmapdata.cpp.
Referenced by QRuntimePixmapData::setAlphaChannel(), and QPixmap::setAlphaChannel().
 {
     QImage image = toImage();
     image.setAlphaChannel(alphaChannel.toImage());
     fromImage(image, Qt::AutoColor);
 }
setMask()
void QPixmapData::setMask (const QBitmap & mask) virtual
Reimplemented in QX11PixmapData, QRuntimePixmapData, QRasterPixmapData, and QMacPixmapData.
Definition at line 167 of file qpixmapdata.cpp.
Referenced by QRuntimePixmapData::setMask(), and QPixmap::setMask().
 {
     if (mask.size().isEmpty()) {
         if (depth() != 1)
             fromImage(toImage().convertToFormat(QImage::Format_RGB32),
                       Qt::AutoColor);
     } else {
         QImage image = toImage();
         const int w = image.width();
         const int h = image.height();
         switch (image.depth()) {
         case 1: {
             const QImage imageMask = mask.toImage().convertToFormat(image.format());
             for (int y = 0; y < h; ++y) {
                 const uchar *mscan = imageMask.scanLine(y);
                 uchar *tscan = image.scanLine(y);
                 int bytesPerLine = image.bytesPerLine();
                 for (int i = 0; i < bytesPerLine; ++i)
                     tscan[i] &= mscan[i];
             }
             break;
         }
         default: {
             const QImage imageMask = mask.toImage().convertToFormat(QImage::Format_MonoLSB);
             image = image.convertToFormat(QImage::Format_ARGB32_Premultiplied);
             for (int y = 0; y < h; ++y) {
                 const uchar *mscan = imageMask.scanLine(y);
                 QRgb *tscan = (QRgb *)image.scanLine(y);
                 for (int x = 0; x < w; ++x) {
                     if (!(mscan[x>>3] & qt_pixmap_bit_mask[x&7]))
                         tscan[x] = 0;
                 }
             }
             break;
         }
         }
         fromImage(image, Qt::AutoColor);
     }
 }
setSerialNumber()
void QPixmapData::setSerialNumber (int serNo) protected
Definition at line 260 of file qpixmapdata.cpp.
Referenced by QX11PixmapData::convertToARGB32(), QDirectFBPixmapData::copy(), QX11PixmapData::copy(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QDirectFBPixmapData::fill(), QDirectFBPixmapData::fromDataBufferDescription(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QDirectFBPixmapData::invalidate(), QBlittablePixmapData::QBlittablePixmapData(), QDirectFBPixmapData::QDirectFBPixmapData(), QGLPixmapData::QGLPixmapData(), QRuntimePixmapData::QRuntimePixmapData(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QGLPixmapData::resize(), QDirectFBPixmapData::transformed(), QX11PixmapData::transformed(), and QVGPixmapData::updateSerial().
 {
     ser_no = serNo;
 }
toImage() [1/2]
virtual QImage QPixmapData::toImage () const pure virtual
Implemented in QGLPixmapData, QVGPixmapData, QX11PixmapData, QRuntimePixmapData, QRasterPixmapData, QMacPixmapData, QDirectFBPixmapData, QBlittablePixmapData, and QMeeGoPixmapData.
Referenced by alphaChannel(), QMeeGoRasterPixmapData::copy(), QRasterPixmapData::copy(), QX11PixmapData::copy(), copy(), QVGPixmapData::copy(), QRasterPaintEngine::drawPixmap(), mask(), setAlphaChannel(), QRuntimeGraphicsSystem::setGraphicsSystem(), setMask(), QRuntimePixmapData::toImage(), toImage(), QPixmap::toImage(), and transformed().
toImage() [2/2]
QImage QPixmapData::toImage (const QRect & rect) const virtual
Reimplemented in QX11PixmapData, and QRasterPixmapData.
Definition at line 265 of file qpixmapdata.cpp.
 {
     if (rect.contains(QRect(0, 0, w, h)))
         return toImage();
     else
         return toImage().copy(rect);
 }
transformed()
QPixmap QPixmapData::transformed (const QTransform & matrix, Qt::TransformationMode mode) const virtual
Reimplemented in QX11PixmapData, QRuntimePixmapData, and QDirectFBPixmapData.
Definition at line 242 of file qpixmapdata.cpp.
Referenced by QMacPixmapData::macCreatePixels(), QRuntimePixmapData::transformed(), and QPixmap::transformed().
 {
     return QPixmap::fromImage(toImage().transformed(matrix, mode));
 }
width()
int QPixmapData::width () const inline
Definition at line 126 of file qpixmapdata_p.h.
Referenced by checkForAlphaPixels(), QX11PixmapData::convertToARGB32(), QX11PixmapData::fill(), QPixmap::fill(), QMeeGoLivePixmapData::lock(), QMacPixmapData::macCreatePixels(), qt_mac_create_iconref(), QRuntimePixmapData::readBackInfo(), QPixmap::rect(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QGLPixmapData::resize(), QX11PixmapData::setMask(), QPixmap::size(), QEglProperties::toString(), QX11PixmapData::transformed(), and QPixmap::width().
 { return w; }
Friends and Related Functions
QExplicitlySharedDataPointer< QPixmapData >
friend class QExplicitlySharedDataPointer< QPixmapData > friend
Definition at line 165 of file qpixmapdata_p.h.
QGLTextureCache
friend class QGLTextureCache friend
Definition at line 164 of file qpixmapdata_p.h.
QImagePixmapCleanupHooks
friend class QImagePixmapCleanupHooks friend
Definition at line 163 of file qpixmapdata_p.h.
QPixmap
friend class QPixmap friend
Definition at line 160 of file qpixmapdata_p.h.
Referenced by QMeeGoLivePixmapData::QMeeGoLivePixmapData(), and QDirectFBPixmapData::transformed().
QSymbianRasterPixmapData
friend class QSymbianRasterPixmapData friend
Definition at line 162 of file qpixmapdata_p.h.
QX11PixmapData
friend class QX11PixmapData friend
Definition at line 161 of file qpixmapdata_p.h.
Referenced by QMeeGoLivePixmapData::QMeeGoLivePixmapData().
Properties
d
int QPixmapData::d protected
Definition at line 156 of file qpixmapdata_p.h.
Referenced by QX11PixmapData::bitmapFromImage(), QX11PixmapData::convertToARGB32(), QDirectFBPixmapData::copy(), QX11PixmapData::copy(), createCompatiblePixmapData(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QDirectFBPixmapData::fill(), QX11PixmapData::fill(), QGLPixmapData::fromData(), QDirectFBPixmapData::fromDataBufferDescription(), QGLPixmapData::fromFile(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QPixmap::grabWindow(), QPixmap::hasAlpha(), QX11PixmapData::hasAlphaChannel(), QVGPixmapData::idealFormat(), QDirectFBPixmapData::invalidate(), QMacPixmapData::macSetAlphaChannel(), QX11PixmapData::mask(), QMacPixmapData::metric(), QRasterPixmapData::metric(), QX11PixmapData::metric(), QGLPixmapData::metric(), QVGPixmapData::metric(), QX11PixmapData::paintEngine(), QRuntimePixmapData::readBackInfo(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QVGPixmapData::resize(), QGLPixmapData::resize(), QX11WindowSurface::setGeometry(), QX11PixmapData::setMask(), QMacPixmapData::toImage(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), QX11PixmapData::transformed(), and QX11PixmapData::x11ConvertToDefaultDepth().
detach_no
int QPixmapData::detach_no private
Definition at line 168 of file qpixmapdata_p.h.
Referenced by QPixmap::detach().
h
int QPixmapData::h protected
Definition at line 155 of file qpixmapdata_p.h.
Referenced by QMacPixmapData::alphaChannel(), QX11PixmapData::alphaChannel(), QGLPixmapData::bind(), QX11PixmapData::bitmap_to_mask(), QX11PixmapData::bitmapFromImage(), QBlittablePixmapData::blittable(), QX11PixmapData::convertToARGB32(), QMacPixmapData::copy(), QDirectFBPixmapData::copy(), QX11PixmapData::copy(), QVGPixmapData::copy(), QGLPixmapData::copy(), QGLPixmapData::copyBackFromRenderFbo(), QX11PixmapData::createBitmapFromImage(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QMeeGoPixmapData::destroyEGLSharedImage(), QGLPixmapData::ensureCreated(), QVGPixmapData::ensureReadback(), QBlittablePixmapData::fill(), QMacPixmapData::fill(), QGLPixmapData::fillImage(), QVGPixmapData::forceToImage(), QGLPixmapData::fromData(), QDirectFBPixmapData::fromDataBufferDescription(), QGLPixmapData::fromFile(), QBlittablePixmapData::fromImage(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QPixmap::fromMacCGImageRef(), QPixmap::grabWindow(), QDirectFBPixmapData::invalidate(), QVGPixmapData::isValid(), QGLPixmapData::isValid(), QMacPixmapData::macCreateCGImageRef(), QMacPixmapData::macCreatePixels(), QMacPixmapData::macGetAlphaChannel(), QMacPixmapData::macSetAlphaChannel(), QMacPixmapData::mask(), mask(), QX11PixmapData::mask_to_bitmap(), QBlittablePixmapData::metric(), QMacPixmapData::metric(), QRasterPixmapData::metric(), QX11PixmapData::metric(), QGLPixmapData::metric(), QVGPixmapData::metric(), QBlittablePixmapData::paintEngine(), QX11PixmapData::paintEngine(), qt_mac_cg_context(), QRuntimePixmapData::readBackInfo(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QVGPixmapData::resize(), QGLPixmapData::resize(), QMacPixmapData::setMask(), QRasterPixmapData::setMask(), QX11PixmapData::setMask(), setMask(), QX11GLPixmapData::size(), QDirectFBPixmapData::toImage(), QMacPixmapData::toImage(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), QVGPixmapData::toImage(), toImage(), QGLPixmapData::toImage(), QVGPixmapData::toVGImage(), QDirectFBPixmapData::transformed(), QX11PixmapData::transformed(), QMeeGoPixmapData::updateFromSoftImage(), QGLPixmapData::useFramebufferObjects(), and QX11PixmapData::x11ConvertToDefaultDepth().
id
int QPixmapData::id private
Definition at line 171 of file qpixmapdata_p.h.
Referenced by QGLPixmapData::bind().
is_cached
uint QPixmapData::is_cached private
Definition at line 173 of file qpixmapdata_p.h.
Referenced by QPixmap::detach(), QImagePixmapCleanupHooks::enableCleanupHooks(), ~QPixmapData(), and QX11PixmapData::~QX11PixmapData().
is_null
bool QPixmapData::is_null protected
Definition at line 157 of file qpixmapdata_p.h.
Referenced by QX11PixmapData::bitmapFromImage(), QX11PixmapData::convertToARGB32(), QDirectFBPixmapData::copy(), QX11PixmapData::copy(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QGLPixmapData::fromData(), QDirectFBPixmapData::fromDataBufferDescription(), QGLPixmapData::fromFile(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QDirectFBPixmapData::invalidate(), QMacPixmapData::macCreatePixels(), QRuntimePixmapData::readBackInfo(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QVGPixmapData::resize(), QGLPixmapData::resize(), QDirectFBPixmapData::transformed(), and QX11PixmapData::transformed().
ref
QAtomicInt QPixmapData::ref private
Definition at line 167 of file qpixmapdata_p.h.
Referenced by QPixmap::detach(), QPixmap::fill(), QPixmap::isDetached(), QX11PixmapData::setMask(), and QPixmap::~QPixmap().
ser_no
int QPixmapData::ser_no private
Definition at line 172 of file qpixmapdata_p.h.
Referenced by setSerialNumber().
type
PixelType QPixmapData::type private
Definition at line 170 of file qpixmapdata_p.h.
Referenced by QRuntimePixmapData::buffer(), QPixmap::depth(), QPixmap::isQBitmap(), QPixmap::load(), and QX11PixmapData::transformed().
w
int QPixmapData::w protected
Definition at line 154 of file qpixmapdata_p.h.
Referenced by QMacPixmapData::alphaChannel(), QX11PixmapData::alphaChannel(), QGLPixmapData::bind(), QX11PixmapData::bitmap_to_mask(), QX11PixmapData::bitmapFromImage(), QBlittablePixmapData::blittable(), QX11PixmapData::convertToARGB32(), QMacPixmapData::copy(), QDirectFBPixmapData::copy(), QX11PixmapData::copy(), QVGPixmapData::copy(), QGLPixmapData::copy(), QGLPixmapData::copyBackFromRenderFbo(), QX11PixmapData::createBitmapFromImage(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QGLPixmapData::ensureCreated(), QVGPixmapData::ensureReadback(), QBlittablePixmapData::fill(), QGLPixmapData::fillImage(), QVGPixmapData::forceToImage(), QGLPixmapData::fromData(), QDirectFBPixmapData::fromDataBufferDescription(), QGLPixmapData::fromFile(), QBlittablePixmapData::fromImage(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QPixmap::fromMacCGImageRef(), QPixmap::grabWindow(), QDirectFBPixmapData::invalidate(), QVGPixmapData::isValid(), QGLPixmapData::isValid(), QMacPixmapData::macCreateCGImageRef(), QMacPixmapData::macCreatePixels(), QMacPixmapData::macGetAlphaChannel(), QMacPixmapData::macSetAlphaChannel(), QMacPixmapData::mask(), mask(), QX11PixmapData::mask_to_bitmap(), QBlittablePixmapData::metric(), QMacPixmapData::metric(), QRasterPixmapData::metric(), QX11PixmapData::metric(), QGLPixmapData::metric(), QVGPixmapData::metric(), QBlittablePixmapData::paintEngine(), QX11PixmapData::paintEngine(), qt_mac_cg_context(), QRuntimePixmapData::readBackInfo(), QBlittablePixmapData::resize(), QDirectFBPixmapData::resize(), QMacPixmapData::resize(), QRasterPixmapData::resize(), QX11PixmapData::resize(), QVGPixmapData::resize(), QGLPixmapData::resize(), QMacPixmapData::setMask(), QRasterPixmapData::setMask(), QX11PixmapData::setMask(), setMask(), QX11GLPixmapData::size(), QDirectFBPixmapData::toImage(), QMacPixmapData::toImage(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), QVGPixmapData::toImage(), toImage(), QGLPixmapData::toImage(), QVGPixmapData::toVGImage(), QDirectFBPixmapData::transformed(), QX11PixmapData::transformed(), QMeeGoPixmapData::updateFromSoftImage(), QGLPixmapData::useFramebufferObjects(), and QX11PixmapData::x11ConvertToDefaultDepth().
The documentation for this class was generated from the following files:
/src/gui/image/qpixmapdata_p.h
/src/gui/image/qpixmapdata.cpp