Qt 4.8: QScriptDebuggerBackendPrivate Class Reference
QScriptDebuggerBackendPrivate Class Reference
#include <qscriptdebuggerbackend_p_p.h>
Public Functions
void agentDestroyed (QScriptDebuggerAgent *)
virtual void breakpoint (qint64 scriptId, int lineNumber, int columnNumber, int breakpointId)
The agent calls this function when a breakpoint has been triggered.
virtual void debuggerInvocationRequest (qint64 scriptId, int lineNumber, int columnNumber)
The agent calls this function when the engine has reached a "debugger" statement.
virtual bool event (QEvent *e)
virtual void exception (qint64 scriptId, const QScriptValue &exception, bool hasHandler)
The agent calls this function when an uncaught exception has occurred.
virtual void forcedReturn (qint64 scriptId, int lineNumber, int columnNumber, const QScriptValue &value)
virtual void interrupted (qint64 scriptId, int lineNumber, int columnNumber)
The agent calls this function when evaluation has been interrupted.
virtual void locationReached (qint64 scriptId, int lineNumber, int columnNumber)
The agent calls this function when it has run to a particular location.
void postEvent (QEvent *e)
QScriptDebuggerBackendPrivate ()
virtual void stepped (qint64 scriptId, int lineNumber, int columnNumber, const QScriptValue &result)
The agent calls this function when it has completed a step operation.
virtual ~QScriptDebuggerBackendPrivate ()
Static Public Functions
static QScriptValue fileName (QScriptContext *context, QScriptEngine *engine)
static QScriptValue lineNumber (QScriptContext *context, QScriptEngine *engine)
static QScriptValue qsassert (QScriptContext *context, QScriptEngine *engine)
static QScriptValue trace (QScriptContext *context, QScriptEngine *engine)
Public Variables
QScriptDebuggerAgent * agent
QScriptDebuggerCommandExecutor * commandExecutor
QObject * eventReceiver
bool ignoreExceptions
int nextScriptObjectSnapshotId
int nextScriptValueIteratorId
QScriptValue origFileNameFunction
QScriptValue origLineNumberFunction
QScriptValue origTraceFunction
int pendingEvaluateContextIndex
QString pendingEvaluateFileName
int pendingEvaluateLineNumber
QString pendingEvaluateProgram
QScriptDebuggerBackend * q_ptr
QMap< int, QScriptObjectSnapshot * > scriptObjectSnapshots
QMap< int, QScriptValueIterator * > scriptValueIterators
Detailed Description
Definition at line 76 of file qscriptdebuggerbackend_p_p.h.
Constructors and Destructors
QScriptDebuggerBackendPrivate()
QScriptDebuggerBackendPrivate::QScriptDebuggerBackendPrivate ()
Definition at line 136 of file qscriptdebuggerbackend.cpp.
     : agent(0), commandExecutor(0),
         pendingEvaluateContextIndex(-1), pendingEvaluateLineNumber(-1),
         ignoreExceptions(false),
         nextScriptValueIteratorId(0), nextScriptObjectSnapshotId(0),
         eventReceiver(0),
         q_ptr(0) // q_ptr will be set later by QScriptDebuggerBackend constructor
 {
 }
~QScriptDebuggerBackendPrivate()
QScriptDebuggerBackendPrivate::~QScriptDebuggerBackendPrivate () virtual
Definition at line 146 of file qscriptdebuggerbackend.cpp.
 {
     if (agent)
         agent->nullifyBackendPointer();
     delete commandExecutor;
     delete eventReceiver;
     qDeleteAll(scriptValueIterators);
     qDeleteAll(scriptObjectSnapshots);
 }
Functions
agentDestroyed()
void QScriptDebuggerBackendPrivate::agentDestroyed (QScriptDebuggerAgent * ag)
Definition at line 175 of file qscriptdebuggerbackend.cpp.
 {
     // Since agents are owned by the script engine, this in practice means
     // that the engine has been destroyed. Invalidate our pointer so we
     // don't crash later.
     if (agent == ag)
         agent = 0;
 }
breakpoint()
void QScriptDebuggerBackendPrivate::breakpoint (qint64 scriptId, int lineNumber, int columnNumber, int breakpointId) virtual
The agent calls this function when a breakpoint has been triggered.
Definition at line 236 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::Breakpoint,
                            scriptId, lineNumber, columnNumber);
     e.setFileName(agent->scriptData(scriptId).fileName());
     e.setBreakpointId(breakpointId);
     q->event(e);
 }
debuggerInvocationRequest()
void QScriptDebuggerBackendPrivate::debuggerInvocationRequest (qint64 scriptId, int lineNumber, int columnNumber) virtual
The agent calls this function when the engine has reached a "debugger" statement.
Definition at line 353 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::DebuggerInvocationRequest,
                            scriptId, lineNumber, columnNumber);
     e.setFileName(agent->scriptData(scriptId).fileName());
     q->event(e);
 }
event()
bool QScriptDebuggerBackendPrivate::event (QEvent * e) virtual
Reimplemented in QScriptEngineDebuggerBackendPrivate.
Definition at line 165 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerBackendEventReceiver::event(), and QScriptEngineDebuggerBackendPrivate::event().
 {
     if (e->type() == QEvent::User+1) {
         QScriptDebuggerEventEvent *de = static_cast<QScriptDebuggerEventEvent*>(e);
         q_func()->event(de->event());
         return true;
     }
     return false;
 }
exception()
void QScriptDebuggerBackendPrivate::exception (qint64 scriptId, const QScriptValue & exception, bool hasHandler) virtual
The agent calls this function when an uncaught exception has occurred.
Definition at line 253 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     if (ignoreExceptions) {
         // don't care (it's caught by us)
         return;
     }
     QScriptDebuggerEvent e(QScriptDebuggerEvent::Exception);
     e.setScriptId(scriptId);
     e.setFileName(agent->scriptData(scriptId).fileName());
     e.setMessage(exception.toString());
     e.setHasExceptionHandler(hasHandler);
     int lineNumber = -1;
     QString fileName;
     if (exception.property(QLatin1String("lineNumber")).isNumber())
         lineNumber = exception.property(QLatin1String("lineNumber")).toInt32();
     if (exception.property(QLatin1String("fileName")).isString())
         fileName = exception.property(QLatin1String("fileName")).toString();
     if (lineNumber == -1) {
         QScriptContextInfo info(q->engine()->currentContext());
         lineNumber = info.lineNumber();
         fileName = info.fileName();
     }
     if (lineNumber != -1)
         e.setLineNumber(lineNumber);
     if (!fileName.isEmpty())
         e.setFileName(fileName);
     QScriptDebuggerValue value(exception);
     e.setScriptValue(value);
     q->event(e);
 }
fileName()
QScriptValue QScriptDebuggerBackendPrivate::fileName (QScriptContext * context, QScriptEngine * engine) static
Definition at line 332 of file qscriptdebuggerbackend.cpp.
Referenced by exception(), QScriptDebuggerBackend::fileNameFunction(), and qsassert().
 {
     QScriptContextInfo info(context->parentContext());
     QString fn = info.fileName();
     if (fn.isEmpty())
         return engine->undefinedValue();
     return QScriptValue(engine, fn);
 }
forcedReturn()
void QScriptDebuggerBackendPrivate::forcedReturn (qint64 scriptId, int lineNumber, int columnNumber, const QScriptValue & value) virtual
Definition at line 363 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::ForcedReturn,
                            scriptId, lineNumber, columnNumber);
     e.setFileName(agent->scriptData(scriptId).fileName());
     e.setScriptValue(QScriptDebuggerValue(value));
     q->event(e);
 }
interrupted()
void QScriptDebuggerBackendPrivate::interrupted (qint64 scriptId, int lineNumber, int columnNumber) virtual
The agent calls this function when evaluation has been interrupted.
Definition at line 222 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::Interrupted,
                            scriptId, lineNumber, columnNumber);
     e.setFileName(agent->scriptData(scriptId).fileName());
     q->event(e);
 }
lineNumber()
QScriptValue QScriptDebuggerBackendPrivate::lineNumber (QScriptContext * context, QScriptEngine * engine) static
Definition at line 342 of file qscriptdebuggerbackend.cpp.
Referenced by exception(), and QScriptDebuggerBackend::lineNumberFunction().
 {
     QScriptContextInfo info(context->parentContext());
     return QScriptValue(engine, info.lineNumber());
 }
locationReached()
void QScriptDebuggerBackendPrivate::locationReached (qint64 scriptId, int lineNumber, int columnNumber) virtual
The agent calls this function when it has run to a particular location.
Definition at line 208 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::LocationReached,
                            scriptId, lineNumber, columnNumber);
     e.setFileName(agent->scriptData(scriptId).fileName());
     q->event(e);
 }
postEvent()
void QScriptDebuggerBackendPrivate::postEvent (QEvent * e)
Definition at line 156 of file qscriptdebuggerbackend.cpp.
 {
     if (!eventReceiver) {
         eventReceiver = new QScriptDebuggerBackendEventReceiver(this);
         eventReceiver->moveToThread(agent->engine()->thread());
     }
     QCoreApplication::postEvent(eventReceiver, e);
 }
qsassert()
QScriptValue QScriptDebuggerBackendPrivate::qsassert (QScriptContext * context, QScriptEngine * engine) static
Definition at line 306 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerBackend::assertFunction().
 {
     QScriptValue arg = context->argument(0);
     if (arg.toBoolean())
         return arg;
     QScriptContextInfo info(context->parentContext());
     QString msg;
     QString fileName = info.fileName();
     if (fileName.isEmpty())
         fileName = QString::fromLatin1("<anonymous script, id=%0>").arg(info.scriptId());
     msg.append(fileName);
     msg.append(QLatin1Char(':'));
     msg.append(QString::number(info.lineNumber()));
     msg.append(QString::fromLatin1(": Assertion failed"));
     for (int i = 1; i < context->argumentCount(); ++i) {
         if (i == 1)
             msg.append(QLatin1Char(':'));
         msg.append(QLatin1Char(' '));
         msg.append(context->argument(i).toString());
     }
     QScriptValue err = context->throwError(msg);
     err.setProperty(QString::fromLatin1("name"), QScriptValue(engine, QString::fromLatin1("AssertionError")));
     return err;
 }
stepped()
void QScriptDebuggerBackendPrivate::stepped (qint64 scriptId, int lineNumber, int columnNumber, const QScriptValue & result) virtual
The agent calls this function when it has completed a step operation.
Definition at line 188 of file qscriptdebuggerbackend.cpp.
 {
     Q_Q(QScriptDebuggerBackend);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::SteppingFinished,
                            scriptId, lineNumber, columnNumber);
     e.setFileName(agent->scriptData(scriptId).fileName());
     QScriptDebuggerValue value(result);
     e.setScriptValue(value);
     if (!result.isUndefined())
         e.setMessage(result.toString()); // for convenience -- we always need it
     q->event(e);
 }
trace()
QScriptValue QScriptDebuggerBackendPrivate::trace (QScriptContext * context, QScriptEngine * engine) static
Definition at line 287 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerBackend::traceFunction().
 {
     QScriptValue data = context->callee().data();
     QScriptDebuggerBackendPrivate *self = qscriptvalue_cast<QScriptDebuggerBackendPrivate*>(data);
     if (!self)
         return engine->undefinedValue();
     QString str;
     for (int i = 0; i < context->argumentCount(); ++i) {
         if (i > 0)
             str.append(QLatin1Char(' '));
         str.append(context->argument(i).toString());
     }
     QScriptDebuggerEvent e(QScriptDebuggerEvent::Trace);
     e.setMessage(str);
     self->q_func()->event(e);
     return engine->undefinedValue();
 }
Properties
agent
QScriptDebuggerAgent* QScriptDebuggerBackendPrivate::agent
Definition at line 111 of file qscriptdebuggerbackend_p_p.h.
Referenced by agentDestroyed(), breakpoint(), debuggerInvocationRequest(), exception(), forcedReturn(), interrupted(), locationReached(), postEvent(), stepped(), and ~QScriptDebuggerBackendPrivate().
commandExecutor
QScriptDebuggerCommandExecutor* QScriptDebuggerBackendPrivate::commandExecutor
Definition at line 112 of file qscriptdebuggerbackend_p_p.h.
Referenced by QScriptDebuggerBackend::commandExecutor(), and ~QScriptDebuggerBackendPrivate().
eventReceiver
QObject* QScriptDebuggerBackendPrivate::eventReceiver
Definition at line 126 of file qscriptdebuggerbackend_p_p.h.
Referenced by postEvent(), and ~QScriptDebuggerBackendPrivate().
ignoreExceptions
bool QScriptDebuggerBackendPrivate::ignoreExceptions
Definition at line 118 of file qscriptdebuggerbackend_p_p.h.
Referenced by exception().
nextScriptObjectSnapshotId
int QScriptDebuggerBackendPrivate::nextScriptObjectSnapshotId
Definition at line 123 of file qscriptdebuggerbackend_p_p.h.
nextScriptValueIteratorId
int QScriptDebuggerBackendPrivate::nextScriptValueIteratorId
Definition at line 120 of file qscriptdebuggerbackend_p_p.h.
origFileNameFunction
QScriptValue QScriptDebuggerBackendPrivate::origFileNameFunction
Definition at line 131 of file qscriptdebuggerbackend_p_p.h.
origLineNumberFunction
QScriptValue QScriptDebuggerBackendPrivate::origLineNumberFunction
Definition at line 132 of file qscriptdebuggerbackend_p_p.h.
origTraceFunction
QScriptValue QScriptDebuggerBackendPrivate::origTraceFunction
Definition at line 130 of file qscriptdebuggerbackend_p_p.h.
pendingEvaluateContextIndex
int QScriptDebuggerBackendPrivate::pendingEvaluateContextIndex
Definition at line 114 of file qscriptdebuggerbackend_p_p.h.
pendingEvaluateFileName
QString QScriptDebuggerBackendPrivate::pendingEvaluateFileName
Definition at line 116 of file qscriptdebuggerbackend_p_p.h.
pendingEvaluateLineNumber
int QScriptDebuggerBackendPrivate::pendingEvaluateLineNumber
Definition at line 117 of file qscriptdebuggerbackend_p_p.h.
pendingEvaluateProgram
QString QScriptDebuggerBackendPrivate::pendingEvaluateProgram
Definition at line 115 of file qscriptdebuggerbackend_p_p.h.
q_ptr
QScriptDebuggerBackend* QScriptDebuggerBackendPrivate::q_ptr
Definition at line 128 of file qscriptdebuggerbackend_p_p.h.
Referenced by QScriptDebuggerBackend::QScriptDebuggerBackend().
scriptObjectSnapshots
QMap<int, QScriptObjectSnapshot*> QScriptDebuggerBackendPrivate::scriptObjectSnapshots
Definition at line 124 of file qscriptdebuggerbackend_p_p.h.
Referenced by ~QScriptDebuggerBackendPrivate().
scriptValueIterators
QMap<int, QScriptValueIterator*> QScriptDebuggerBackendPrivate::scriptValueIterators
Definition at line 121 of file qscriptdebuggerbackend_p_p.h.
Referenced by ~QScriptDebuggerBackendPrivate().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerbackend_p_p.h
/src/scripttools/debugging/qscriptdebuggerbackend.cpp