Qt 4.8: QGraphicsProxyWidget Class Reference
QGraphicsProxyWidget Class Reference
The QGraphicsProxyWidget class provides a proxy layer for embedding a QWidget in a QGraphicsScene.
#include <qgraphicsproxywidget.h>
Public Types
enum { Type = 12 }
Public Types inherited from QGraphicsWidget
enum { Type = 11 }
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Functions
QGraphicsProxyWidget * createProxyForChildWidget (QWidget *child)
Creates a proxy widget for the given child of the widget contained in this proxy.
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Reimplemented Function
QGraphicsProxyWidget (QGraphicsItem *parent=0, Qt::WindowFlags wFlags=0)
Constructs a new QGraphicsProxy widget.
void setGeometry (const QRectF &rect)
Reimplemented Function
void setWidget (QWidget *widget)
Embeds widget into this proxy widget.
QRectF subWidgetRect (const QWidget *widget) const
Returns the rectangle for widget, which must be a descendant of widget(), or widget() itself, in this proxy item's local coordinates.
int type () const
Reimplemented Function
QWidget * widget () const
Returns a pointer to the embedded widget.
~QGraphicsProxyWidget ()
Destroys the proxy widget and any embedded widget.
Public Functions inherited from QGraphicsWidget
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to its effective preferred size hint.
bool autoFillBackground () const
QRectF boundingRect () const
Reimplemented Function
Qt::FocusPolicy focusPolicy () const
QGraphicsWidget * focusWidget () const
If this widget, a child or descendant of this widget currently has input focus, this function will return a pointer to that widget.
QFont font () const
void getContentsMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Gets the widget's contents margins.
void getWindowFrameMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Gets the widget's window frame margins.
int grabShortcut (const QKeySequence &sequence, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
bool isActiveWindow () const
Returns true if this widget's window is in the active window, or if the widget does not have a window but is in an active scene (i.e., a scene that currently has focus).
QGraphicsLayout * layout () const
Qt::LayoutDirection layoutDirection () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Reimplemented Function
virtual void paintWindowFrame (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
This virtual function is called by QGraphicsScene to draw the window frame for windows using painter, option, and widget, in local coordinates.
QPalette palette () const
QGraphicsWidget (QGraphicsItem *parent=0, Qt::WindowFlags wFlags=0)
Constructs a QGraphicsWidget instance.
QRectF rect () const
Returns the item's local rect as a QRectF.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void resize (const QSizeF &size)
void resize (qreal w, qreal h)
This convenience function is equivalent to calling resize(QSizeF(w, h)).
void setAttribute (Qt::WidgetAttribute attribute, bool on=true)
If on is true, this function enables attribute; otherwise attribute is disabled.
void setAutoFillBackground (bool enabled)
void setContentsMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the widget's contents margins to left, top, right and bottom.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFont (const QFont &font)
void setGeometry (const QRectF &rect)
This virtual function sets the geometry of the QGraphicsLayoutItem to rect, which is in parent coordinates (e.
void setGeometry (qreal x, qreal y, qreal w, qreal h)
This convenience function is equivalent to calling setGeometry(QRectF(x, y, w, h)).
void setLayout (QGraphicsLayout *layout)
Sets the layout for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setPalette (const QPalette &palette)
void setShortcutAutoRepeat (int id, bool enabled=true)
If enabled is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enabled=true)
If enabled is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setStyle (QStyle *style)
Sets the widget's style to style.
void setWindowFlags (Qt::WindowFlags wFlags)
void setWindowFrameMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the widget's window frame margins to left, top, right and bottom.
void setWindowTitle (const QString &title)
QPainterPath shape () const
Reimplemented Function
QSizeF size () const
QStyle * style () const
Returns a pointer to the widget's style.
bool testAttribute (Qt::WidgetAttribute attribute) const
Returns true if attribute is enabled for this widget; otherwise, returns false.
int type () const
Reimplemented Function
void unsetLayoutDirection ()
void unsetWindowFrameMargins ()
Resets the window frame margins to the default value, provided by the style.
Qt::WindowFlags windowFlags () const
QRectF windowFrameGeometry () const
Returns the widget's geometry in parent coordinates including any window frame.
QRectF windowFrameRect () const
Returns the widget's local rect including any window frame.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the widgets window type.
~QGraphicsWidget ()
Destroys the QGraphicsWidget instance.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QGraphicsLayoutItem
QRectF contentsRect () const
Returns the contents rect in local coordinates.
QSizeF effectiveSizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
QRectF geometry () const
Returns the item's geometry (e.
QGraphicsItem * graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
bool isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
qreal maximumHeight () const
Returns the maximum height.
QSizeF maximumSize () const
Returns the maximum size.
qreal maximumWidth () const
Returns the maximum width.
qreal minimumHeight () const
Returns the minimum height.
QSizeF minimumSize () const
Returns the minimum size.
qreal minimumWidth () const
Returns the minimum width.
bool ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
QGraphicsLayoutItem * parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
qreal preferredHeight () const
Returns the preferred height.
QSizeF preferredSize () const
Returns the preferred size.
qreal preferredWidth () const
Returns the preferred width.
QGraphicsLayoutItem (QGraphicsLayoutItem *parent=0, bool isLayout=false)
Constructs the QGraphicsLayoutItem object.
void setMaximumHeight (qreal height)
Sets the maximum height to height.
void setMaximumSize (const QSizeF &size)
Sets the maximum size to size.
void setMaximumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
void setMaximumWidth (qreal width)
Sets the maximum width to width.
void setMinimumHeight (qreal height)
Sets the minimum height to height.
void setMinimumSize (const QSizeF &size)
Sets the minimum size to size.
void setMinimumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
void setMinimumWidth (qreal width)
Sets the minimum width to width.
void setParentLayoutItem (QGraphicsLayoutItem *parent)
Sets the parent of this QGraphicsLayoutItem to parent.
void setPreferredHeight (qreal height)
Sets the preferred height to height.
void setPreferredSize (const QSizeF &size)
Sets the preferred size to size.
void setPreferredSize (qreal w, qreal h)
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
void setPreferredWidth (qreal width)
Sets the preferred width to width.
void setSizePolicy (const QSizePolicy &policy)
Sets the size policy to policy.
void setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType=QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
QSizePolicy sizePolicy () const
Returns the current size policy.
virtual ~QGraphicsLayoutItem ()
Destroys the QGraphicsLayoutItem object.
Protected Slots
QGraphicsProxyWidget * newProxyWidget (const QWidget *)
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
Reimplemented Function
void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
Reimplemented Function
void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
Reimplemented Function
void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
Reimplemented Function
void dropEvent (QGraphicsSceneDragDropEvent *event)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
bool eventFilter (QObject *object, QEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *event)
Reimplemented Function
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
void grabMouseEvent (QEvent *event)
Reimplemented Function
void hideEvent (QHideEvent *event)
Reimplemented Function
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
Reimplemented Function
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
Reimplemented Function
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
Reimplemented Function
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void keyReleaseEvent (QKeyEvent *event)
Reimplemented Function
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
Reimplemented Function
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
Reimplemented Function
void mousePressEvent (QGraphicsSceneMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Reimplemented Function
void resizeEvent (QGraphicsSceneResizeEvent *event)
Reimplemented Function
void showEvent (QShowEvent *event)
Reimplemented Function
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Reimplemented Function
void ungrabMouseEvent (QEvent *event)
Reimplemented Function
void wheelEvent (QGraphicsSceneWheelEvent *event)
Reimplemented Function
Protected Functions inherited from QGraphicsWidget
virtual void changeEvent (QEvent *event)
This event handler can be reimplemented to handle state changes.
virtual void closeEvent (QCloseEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive widget close events.
bool event (QEvent *event)
Handles the event.
void focusInEvent (QFocusEvent *event)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
virtual void grabKeyboardEvent (QEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::GrabKeyboard events.
virtual void initStyleOption (QStyleOption *option) const
Populates a style option object for this widget based on its current state, and stores the output in option.
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
QGraphicsWidget uses the base implementation of this function to catch and deliver events related to state changes in the item.
virtual void moveEvent (QGraphicsSceneMoveEvent *event)
This event handler, for GraphicsSceneMove events, is delivered after the widget has moved (e.g., its local position has changed).
virtual void polishEvent ()
This event is delivered to the item by the scene at some point after it has been constructed, but before it is shown or otherwise accessed through the scene.
virtual QVariant propertyChange (const QString &propertyName, const QVariant &value)
This virtual function is used to notify changes to any property (both dynamic properties, and registered with e.g., "size";, and value is the (proposed) new value of the property.
QGraphicsWidget (QGraphicsWidgetPrivate &, QGraphicsItem *parent, QGraphicsScene *, Qt::WindowFlags wFlags=0)
Constructs a new QGraphicsWidget, using dd as parent.
bool sceneEvent (QEvent *event)
QGraphicsWidget's implementation of sceneEvent() simply passes event to QGraphicsWidget::event().
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Reimplemented Function
virtual void ungrabKeyboardEvent (QEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::UngrabKeyboard events.
void updateGeometry ()
If this widget is currently managed by a layout, this function notifies the layout that the widget's size hints have changed and the layout may need to resize and reposition the widget accordingly.
virtual bool windowFrameEvent (QEvent *e)
This event handler, for event, receives events for the window frame if this widget is a window.
virtual Qt::WindowFrameSection windowFrameSectionAt (const QPointF &pos) const
Returns the window frame section at position pos, or Qt::NoSection if there is no window frame section at this position.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void inputMethodEvent (QInputMethodEvent *event)
This event handler, for event event, can be reimplemented to receive input method events for this item.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
This method is only relevant for input items.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
Protected Functions inherited from QGraphicsLayoutItem
QGraphicsLayoutItem (QGraphicsLayoutItemPrivate &dd)
void setGraphicsItem (QGraphicsItem *item)
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
void setOwnedByLayout (bool ownedByLayout)
Sets whether a layout should delete this item in its destructor or not.
Friends
class QGraphicsItem
class QWidget
class QWidgetPrivate
Additional Inherited Members
Public Slots inherited from QGraphicsWidget
bool close ()
Call this function to close the widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QGraphicsWidget
void geometryChanged ()
This signal gets emitted whenever the geometry is changed in setGeometry().
void layoutChanged ()
This signal gets emitted whenever the layout of the item changes.
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QGraphicsWidget
static void setTabOrder (QGraphicsWidget *first, QGraphicsWidget *second)
Moves the second widget around the ring of focus widgets so that keyboard focus moves from the first widget to the second widget when the Tab key is pressed.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Protected Variables inherited from QGraphicsLayoutItem
QScopedPointer< QGraphicsLayoutItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
The QGraphicsProxyWidget class provides a proxy layer for embedding a QWidget in a QGraphicsScene.
Since
4.4
QGraphicsProxyWidget embeds QWidget-based widgets, for example, a QPushButton, QFontComboBox, or even QFileDialog, into QGraphicsScene. It forwards events between the two objects and translates between QWidget's integer-based geometry and QGraphicsWidget's qreal-based geometry. QGraphicsProxyWidget supports all core features of QWidget, including tab focus, keyboard input, Drag & Drop, and popups. You can also embed complex widgets, e.g., widgets with subwidgets.
Example:
int main(int argc, char **argv)
{
    QApplication app(argc, argv);
    QTabWidget *tabWidget = new QTabWidget;
    QGraphicsScene scene;
    QGraphicsProxyWidget *proxy = scene.addWidget(tabWidget);
    QGraphicsView view(&scene);
    view.show();
    return app.exec();
}
QGraphicsProxyWidget takes care of automatically embedding popup children of embedded widgets through creating a child proxy for each popup. This means that when an embedded QComboBox shows its popup list, a new QGraphicsProxyWidget is created automatically, embedding the popup, and positioning it correctly. This only works if the popup is child of the embedded widget (for example QToolButton::setMenu() requires the QMenu instance to be child of the QToolButton).
Embedding a Widget with QGraphicsProxyWidget
There are two ways to embed a widget using QGraphicsProxyWidget. The most common way is to pass a widget pointer to QGraphicsScene::addWidget() together with any relevant Qt::WindowFlags . This function returns a pointer to a QGraphicsProxyWidget. You can then choose to reparent or position either the proxy, or the embedded widget itself.
For example, in the code snippet below, we embed a group box into the proxy:
QGroupBox *groupBox = new QGroupBox("Contact Details");
QLabel *numberLabel = new QLabel("Telephone number");
QLineEdit *numberEdit = new QLineEdit;
QFormLayout *layout = new QFormLayout;
layout->addRow(numberLabel, numberEdit);
groupBox->setLayout(layout);
QGraphicsScene scene;
QGraphicsProxyWidget *proxy = scene.addWidget(groupBox);
QGraphicsView view(&scene);
view.show();
The image below is the output obtained with its contents margin and contents rect labeled.
Alternatively, you can start by creating a new QGraphicsProxyWidget item, and then call setWidget() to embed a QWidget later. The widget() function returns a pointer to the embedded widget. QGraphicsProxyWidget shares ownership with QWidget, so if either of the two widgets are destroyed, the other widget will be automatically destroyed as well.
Synchronizing Widget States
QGraphicsProxyWidget keeps its state in sync with the embedded widget. For example, if the proxy is hidden or disabled, the embedded widget will be hidden or disabled as well, and vice versa. When the widget is embedded by calling addWidget(), QGraphicsProxyWidget copies the state from the widget into the proxy, and after that, the two will stay synchronized where possible. By default, when you embed a widget into a proxy, both the widget and the proxy will be visible because a QGraphicsWidget is visible when created (you do not have to call show()). If you explicitly hide the embedded widget, the proxy will also become invisible.
Example:
QGraphicsScene scene;
QLineEdit *edit = new QLineEdit;
QGraphicsProxyWidget *proxy = scene.addWidget(edit);
edit->isVisible();  // returns true
proxy->isVisible(); // also returns true
edit->hide();
edit->isVisible();  // returns false
proxy->isVisible(); // also returns false
QGraphicsProxyWidget maintains symmetry for the following states:
QWidget state QGraphicsProxyWidget state Notes
QWidget::enabled QGraphicsProxyWidget::enabled
QWidget::visible QGraphicsProxyWidget::visible The explicit state is also symmetric.
QWidget::geometry QGraphicsProxyWidget::geometry Geometry is only guaranteed to be symmetric while the embedded widget is visible.
QWidget::layoutDirection QGraphicsProxyWidget::layoutDirection
QWidget::style QGraphicsProxyWidget::style
QWidget::palette QGraphicsProxyWidget::palette
QWidget::font QGraphicsProxyWidget::font
QWidget::cursor QGraphicsProxyWidget::cursor The embedded widget overrides the proxy widget cursor. The proxy cursor changes depending on which embedded subwidget is currently under the mouse.
QWidget::sizeHint() QGraphicsProxyWidget::sizeHint() All size hint functionality from the embedded widget is forwarded by the proxy.
QWidget::getContentsMargins() QGraphicsProxyWidget::getContentsMargins() Updated once by setWidget().
QWidget::windowTitle QGraphicsProxyWidget::windowTitle Updated once by setWidget().
Note
QGraphicsScene keeps the embedded widget in a special state that prevents it from disturbing other widgets (both embedded and not embedded) while the widget is embedded. In this state, the widget may differ slightly in behavior from when it is not embedded.
Warning
This class is provided for convenience when bridging QWidgets and QGraphicsItems, it should not be used for high-performance scenarios.
See also
QGraphicsScene::addWidget(), QGraphicsWidget
Definition at line 57 of file qgraphicsproxywidget.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 73 of file qgraphicsproxywidget.h.
          {
         Type = 12
     };
Constructors and Destructors
QGraphicsProxyWidget()
QGraphicsProxyWidget::QGraphicsProxyWidget (QGraphicsItem * parent = 0, Qt::WindowFlags wFlags = 0)
Constructs a new QGraphicsProxy widget.
parent and wFlags are passed to QGraphicsItem's constructor.
Definition at line 546 of file qgraphicsproxywidget.cpp.
Referenced by newProxyWidget().
     : QGraphicsWidget(*new QGraphicsProxyWidgetPrivate, parent, 0, wFlags)
 {
     Q_D(QGraphicsProxyWidget);
     d->init();
 }
~QGraphicsProxyWidget()
QGraphicsProxyWidget::~QGraphicsProxyWidget ()
Destroys the proxy widget and any embedded widget.
Definition at line 556 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     if (d->widget) {
         QObject::disconnect(d->widget, SIGNAL(destroyed()), this, SLOT(_q_removeWidgetSlot()));
         delete d->widget;
     }
 }
Functions
contextMenuEvent()
void QGraphicsProxyWidget::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1022 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     if (!event || !d->widget || !d->widget->isVisible() || !hasFocus())
         return;
     // Find widget position and receiver.
     QPointF pos = event->pos();
     QPointer<QWidget> alienWidget = d->widget->childAt(pos.toPoint());
     QPointer<QWidget> receiver =  alienWidget ? alienWidget : d->widget;
     // Map event position from us to the receiver
     pos = d->mapToReceiver(pos, receiver);
     QPoint globalPos = receiver->mapToGlobal(pos.toPoint());
     //If the receiver by-pass the proxy its popups
     //will be top level QWidgets therefore they need
     //the screen position. mapToGlobal expect the widget to
     //have proper coordinates in regards of the windowing system
     //but it's not true because the widget is embedded.
     if (bypassGraphicsProxyWidget(receiver))
         globalPos = event->screenPos();
     // Send mouse event. ### Doesn't propagate the event.
     QContextMenuEvent contextMenuEvent(QContextMenuEvent::Reason(event->reason()),
                                        pos.toPoint(), globalPos, event->modifiers());
     QApplication::sendEvent(receiver, &contextMenuEvent);
     event->setAccepted(contextMenuEvent.isAccepted());
 }
createProxyForChildWidget()
QGraphicsProxyWidget * QGraphicsProxyWidget::createProxyForChildWidget (QWidget * child)
Creates a proxy widget for the given child of the widget contained in this proxy.
Since
4.5
This function makes it possible to acquire proxies for non top-level widgets. For instance, you can embed a dialog, and then transform only one of its widgets.
If the widget is already embedded, return the existing proxy widget.
See also
newProxyWidget(), QGraphicsScene::addWidget()
Definition at line 1529 of file qgraphicsproxywidget.cpp.
 {
     QGraphicsProxyWidget *proxy = child->graphicsProxyWidget();
     if (proxy)
         return proxy;
     if (!child->parentWidget()) {
         qWarning("QGraphicsProxyWidget::createProxyForChildWidget: top-level widget not in a QGraphicsScene");
         return 0;
     }
     QGraphicsProxyWidget *parentProxy = createProxyForChildWidget(child->parentWidget());
     if (!parentProxy)
         return 0;
     if (!QMetaObject::invokeMethod(parentProxy, "newProxyWidget",  Qt::DirectConnection,
          Q_RETURN_ARG(QGraphicsProxyWidget*, proxy), Q_ARG(const QWidget*, child)))
         return 0;
     proxy->setParent(parentProxy);
     proxy->setWidget(child);
     return proxy;
 }
dragEnterEvent()
void QGraphicsProxyWidget::dragEnterEvent (QGraphicsSceneDragDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1058 of file qgraphicsproxywidget.cpp.
 {
 #ifdef QT_NO_DRAGANDDROP
     Q_UNUSED(event);
 #else
     Q_D(QGraphicsProxyWidget);
     if (!d->widget)
         return;
     QDragEnterEvent proxyDragEnter(event->pos().toPoint(), event->dropAction(), event->mimeData(), event->buttons(), event->modifiers());
     proxyDragEnter.setAccepted(event->isAccepted());
     QApplication::sendEvent(d->widget, &proxyDragEnter);
     event->setAccepted(proxyDragEnter.isAccepted());
     if (proxyDragEnter.isAccepted())    // we discard answerRect
         event->setDropAction(proxyDragEnter.dropAction());
 #endif
 }
dragLeaveEvent()
void QGraphicsProxyWidget::dragLeaveEvent (QGraphicsSceneDragDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1078 of file qgraphicsproxywidget.cpp.
 {
     Q_UNUSED(event);
 #ifndef QT_NO_DRAGANDDROP
     Q_D(QGraphicsProxyWidget);
     if (!d->widget || !d->dragDropWidget)
         return;
     QDragLeaveEvent proxyDragLeave;
     QApplication::sendEvent(d->dragDropWidget, &proxyDragLeave);
     d->dragDropWidget = 0;
 #endif
 }
dragMoveEvent()
void QGraphicsProxyWidget::dragMoveEvent (QGraphicsSceneDragDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1094 of file qgraphicsproxywidget.cpp.
 {
 #ifdef QT_NO_DRAGANDDROP
     Q_UNUSED(event);
 #else
     Q_D(QGraphicsProxyWidget);
     if (!d->widget)
         return;
     QPointF p = event->pos();
     event->ignore();
     QPointer<QWidget> subWidget = d->widget->childAt(p.toPoint());
     QPointer<QWidget> receiver =  subWidget ? subWidget : d->widget;
     bool eventDelivered = false;
     for (; receiver; receiver = receiver->parentWidget()) {
         if (!receiver->isEnabled() || !receiver->acceptDrops())
             continue;
         // Map event position from us to the receiver
         QPoint receiverPos = d->mapToReceiver(p, receiver).toPoint();
         if (receiver != d->dragDropWidget) {
             // Try to enter before we leave
             QDragEnterEvent dragEnter(receiverPos, event->possibleActions(), event->mimeData(), event->buttons(), event->modifiers());
             dragEnter.setDropAction(event->proposedAction());
             QApplication::sendEvent(receiver, &dragEnter);
             event->setAccepted(dragEnter.isAccepted());
             event->setDropAction(dragEnter.dropAction());
             if (!event->isAccepted()) {
                 // propagate to the parent widget
                 continue;
             }
             d->lastDropAction = event->dropAction();
             if (d->dragDropWidget) {
                 QDragLeaveEvent dragLeave;
                 QApplication::sendEvent(d->dragDropWidget, &dragLeave);
             }
             d->dragDropWidget = receiver;
         }
         QDragMoveEvent dragMove(receiverPos, event->possibleActions(), event->mimeData(), event->buttons(), event->modifiers());
         event->setDropAction(d->lastDropAction);
         QApplication::sendEvent(receiver, &dragMove);
         event->setAccepted(dragMove.isAccepted());
         event->setDropAction(dragMove.dropAction());
         if (event->isAccepted())
             d->lastDropAction = event->dropAction();
         eventDelivered = true;
         break;
     }
     if (!eventDelivered) {
         if (d->dragDropWidget) {
             // Leave the last drag drop item
             QDragLeaveEvent dragLeave;
             QApplication::sendEvent(d->dragDropWidget, &dragLeave);
             d->dragDropWidget = 0;
         }
         // Propagate
         event->setDropAction(Qt::IgnoreAction);
     }
 #endif
 }
dropEvent()
void QGraphicsProxyWidget::dropEvent (QGraphicsSceneDragDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1160 of file qgraphicsproxywidget.cpp.
 {
 #ifdef QT_NO_DRAGANDDROP
     Q_UNUSED(event);
 #else
     Q_D(QGraphicsProxyWidget);
     if (d->widget && d->dragDropWidget) {
         QPoint widgetPos = d->mapToReceiver(event->pos(), d->dragDropWidget).toPoint();
         QDropEvent dropEvent(widgetPos, event->possibleActions(), event->mimeData(), event->buttons(), event->modifiers());
         QApplication::sendEvent(d->dragDropWidget, &dropEvent);
         event->setAccepted(dropEvent.isAccepted());
         d->dragDropWidget = 0;
     }
 #endif
 }
event()
bool QGraphicsProxyWidget::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 838 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     if (!d->widget)
         return QGraphicsWidget::event(event);
     switch (event->type()) {
     case QEvent::StyleChange:
         // Propagate style changes to the embedded widget.
         if (!d->styleChangeMode) {
             d->styleChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
             d->widget->setStyle(style());
             d->styleChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
         }
         break;
     case QEvent::FontChange: {
         // Propagate to widget.
         QWidgetPrivate *wd = d->widget->d_func();
         int mask = d->font.resolve() | d->inheritedFontResolveMask;
         wd->inheritedFontResolveMask = mask;
         wd->resolveFont();
         break;
     }
     case QEvent::PaletteChange: {
         // Propagate to widget.
         QWidgetPrivate *wd = d->widget->d_func();
         int mask = d->palette.resolve() | d->inheritedPaletteResolveMask;
         wd->inheritedPaletteResolveMask = mask;
         wd->resolvePalette();
         break;
     }
     case QEvent::InputMethod: {
         // Forward input method events if the focus widget enables
         // input methods.
         // ### Qt 4.5: this code must also go into a reimplementation
         // of inputMethodEvent().
         QWidget *focusWidget = d->widget->focusWidget();
         if (focusWidget && focusWidget->testAttribute(Qt::WA_InputMethodEnabled))
             QApplication::sendEvent(focusWidget, event);
         break;
     }
     case QEvent::ShortcutOverride: {
         QWidget *focusWidget = d->widget->focusWidget();
         while (focusWidget) {
             QApplication::sendEvent(focusWidget, event);
             if (event->isAccepted())
                 return true;
             focusWidget = focusWidget->parentWidget();
         }
         return false;
     }
     case QEvent::KeyPress: {
         QKeyEvent *k = static_cast<QKeyEvent *>(event);
         if (k->key() == Qt::Key_Tab || k->key() == Qt::Key_Backtab) {
             if (!(k->modifiers() & (Qt::ControlModifier | Qt::AltModifier))) {  //### Add MetaModifier?
                 QWidget *focusWidget = d->widget->focusWidget();
                 while (focusWidget) {
                     bool res = QApplication::sendEvent(focusWidget, event);
                     if ((res && event->isAccepted()) || (isWindow() && focusWidget == d->widget)) {
                         event->accept();
                         break;
                     }
                     focusWidget = focusWidget->parentWidget();
                 }
                 return true;
             }
         }
         break;
     }
 #ifndef QT_NO_TOOLTIP
     case QEvent::GraphicsSceneHelp: {
         // Propagate the help event (for tooltip) to the widget under mouse
         if (d->lastWidgetUnderMouse) {
             QGraphicsSceneHelpEvent *he = static_cast<QGraphicsSceneHelpEvent *>(event);
             QPoint pos = d->mapToReceiver(mapFromScene(he->scenePos()), d->lastWidgetUnderMouse).toPoint();
             QHelpEvent e(QEvent::ToolTip, pos, he->screenPos());
             QApplication::sendEvent(d->lastWidgetUnderMouse, &e);
             event->setAccepted(e.isAccepted());
             return e.isAccepted();
         }
         break;
     }
     case QEvent::ToolTipChange: {
         // Propagate tooltip change to the widget
         if (!d->tooltipChangeMode) {
             d->tooltipChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
             d->widget->setToolTip(toolTip());
             d->tooltipChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
         }
         break;
     }
 #endif
     default:
         break;
     }
     return QGraphicsWidget::event(event);
 }
eventFilter()
bool QGraphicsProxyWidget::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 939 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     if (object == d->widget) {
         switch (event->type()) {
         case QEvent::LayoutRequest:
             updateGeometry();
             break;
          case QEvent::Resize:
              // If the widget resizes itself, we resize the proxy too.
              // Prevent feed-back by checking the geometry change mode.
              if (!d->sizeChangeMode)
                  d->updateProxyGeometryFromWidget();
             break;
          case QEvent::Move:
              // If the widget moves itself, we move the proxy too.  Prevent
              // feed-back by checking the geometry change mode.
              if (!d->posChangeMode)
                  d->updateProxyGeometryFromWidget();
             break;
         case QEvent::Hide:
         case QEvent::Show:
             // If the widget toggles its visible state, the proxy will follow.
             if (!d->visibleChangeMode) {
                 d->visibleChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
                 setVisible(event->type() == QEvent::Show);
                 d->visibleChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
             }
             break;
         case QEvent::EnabledChange:
             // If the widget toggles its enabled state, the proxy will follow.
             if (!d->enabledChangeMode) {
                 d->enabledChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
                 setEnabled(d->widget->isEnabled());
                 d->enabledChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
             }
             break;
         case QEvent::StyleChange:
             // Propagate style changes to the proxy.
             if (!d->styleChangeMode) {
                 d->styleChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
                 setStyle(d->widget->style());
                 d->styleChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
             }
             break;
 #ifndef QT_NO_TOOLTIP
         case QEvent::ToolTipChange:
             // Propagate tooltip change to the proxy.
             if (!d->tooltipChangeMode) {
                 d->tooltipChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
                 setToolTip(d->widget->toolTip());
                 d->tooltipChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
             }
             break;
 #endif
         default:
             break;
         }
     }
     return QGraphicsWidget::eventFilter(object, event);
 }
focusInEvent()
void QGraphicsProxyWidget::focusInEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1353 of file qgraphicsproxywidget.cpp.
 {
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::focusInEvent";
 #endif
     Q_D(QGraphicsProxyWidget);
     if (d->focusFromWidgetToProxy) {
         // Prevent recursion when the proxy autogains focus through the
         // embedded widget calling setFocus(). ### Could be done with event
         // filter on FocusIn instead?
         return;
     }
     d->proxyIsGivingFocus = true;
     switch (event->reason()) {
     case Qt::TabFocusReason: {
     if (QWidget *focusChild = d->findFocusChild(0, true))
             focusChild->setFocus(event->reason());
         break;
     }
     case Qt::BacktabFocusReason:
     if (QWidget *focusChild = d->findFocusChild(0, false))
             focusChild->setFocus(event->reason());
         break;
     default:
     if (d->widget && d->widget->focusWidget()) {
         d->widget->focusWidget()->setFocus(event->reason());
         }
         break;
     }
     d->proxyIsGivingFocus = false;
 }
focusNextPrevChild()
bool QGraphicsProxyWidget::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1409 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     if (!d->widget || !d->scene)
         return QGraphicsWidget::focusNextPrevChild(next);
     Qt::FocusReason reason = next ? Qt::TabFocusReason : Qt::BacktabFocusReason;
     QWidget *lastFocusChild = d->widget->focusWidget();
     if (QWidget *newFocusChild = d->findFocusChild(lastFocusChild, next)) {
     newFocusChild->setFocus(reason);
     return true;
     }
     return QGraphicsWidget::focusNextPrevChild(next);
 }
focusOutEvent()
void QGraphicsProxyWidget::focusOutEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1392 of file qgraphicsproxywidget.cpp.
 {
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::focusOutEvent";
 #endif
     Q_D(QGraphicsProxyWidget);
     if (d->widget) {
         // We need to explicitly remove subfocus from the embedded widget's
         // focus widget.
         if (QWidget *focusWidget = d->widget->focusWidget())
             d->removeSubFocusHelper(focusWidget, event->reason());
     }
 }
grabMouseEvent()
void QGraphicsProxyWidget::grabMouseEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1224 of file qgraphicsproxywidget.cpp.
 {
     Q_UNUSED(event);
 }
hideEvent()
void QGraphicsProxyWidget::hideEvent (QHideEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1013 of file qgraphicsproxywidget.cpp.
 {
     Q_UNUSED(event);
 }
hoverEnterEvent()
void QGraphicsProxyWidget::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1180 of file qgraphicsproxywidget.cpp.
 {
     Q_UNUSED(event);
 }
hoverLeaveEvent()
void QGraphicsProxyWidget::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1188 of file qgraphicsproxywidget.cpp.
 {
     Q_UNUSED(event);
     Q_D(QGraphicsProxyWidget);
     // If hoverMove was compressed away, make sure we update properly here.
     if (d->lastWidgetUnderMouse) {
         QApplicationPrivate::dispatchEnterLeave(0, d->lastWidgetUnderMouse);
         d->lastWidgetUnderMouse = 0;
     }
 }
hoverMoveEvent()
void QGraphicsProxyWidget::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1202 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::hoverMoveEvent";
 #endif
     // Ignore events on the window frame.
     if (!d->widget || !rect().contains(event->pos())) {
         if (d->lastWidgetUnderMouse) {
             QApplicationPrivate::dispatchEnterLeave(0, d->lastWidgetUnderMouse);
             d->lastWidgetUnderMouse = 0;
         }
         return;
     }
     d->embeddedMouseGrabber = 0;
     d->sendWidgetMouseEvent(event);
 }
itemChange()
QVariant QGraphicsProxyWidget::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 788 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     switch (change) {
     case ItemPositionChange:
         // The item's position is either changed directly on the proxy, in
         // which case the position change should propagate to the widget,
         // otherwise it happens as a side effect when filtering QEvent::Move.
         if (!d->posChangeMode)
             d->posChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
         break;
     case ItemPositionHasChanged:
         // Move the internal widget if we're in widget-to-proxy
         // mode. Otherwise the widget has already moved.
         if (d->widget && d->posChangeMode != QGraphicsProxyWidgetPrivate::WidgetToProxyMode)
             d->widget->move(value.toPoint());
         if (d->posChangeMode == QGraphicsProxyWidgetPrivate::ProxyToWidgetMode)
             d->posChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
         break;
     case ItemVisibleChange:
         if (!d->visibleChangeMode)
             d->visibleChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
         break;
     case ItemVisibleHasChanged:
         if (d->widget && d->visibleChangeMode != QGraphicsProxyWidgetPrivate::WidgetToProxyMode)
             d->widget->setVisible(isVisible());
         if (d->visibleChangeMode == QGraphicsProxyWidgetPrivate::ProxyToWidgetMode)
             d->visibleChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
         break;
     case ItemEnabledChange:
         if (!d->enabledChangeMode)
             d->enabledChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
         break;
     case ItemEnabledHasChanged:
         if (d->widget && d->enabledChangeMode != QGraphicsProxyWidgetPrivate::WidgetToProxyMode)
             d->widget->setEnabled(isEnabled());
         if (d->enabledChangeMode == QGraphicsProxyWidgetPrivate::ProxyToWidgetMode)
             d->enabledChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
         break;
     default:
         break;
     }
     return QGraphicsWidget::itemChange(change, value);
 }
keyPressEvent()
void QGraphicsProxyWidget::keyPressEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1329 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::keyPressEvent";
 #endif
     d->sendWidgetKeyEvent(event);
 }
keyReleaseEvent()
void QGraphicsProxyWidget::keyReleaseEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1341 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::keyReleaseEvent";
 #endif
     d->sendWidgetKeyEvent(event);
 }
mouseDoubleClickEvent()
void QGraphicsProxyWidget::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1266 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::mouseDoubleClickEvent";
 #endif
     d->sendWidgetMouseEvent(event);
 }
mouseMoveEvent()
void QGraphicsProxyWidget::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1242 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::mouseMoveEvent";
 #endif
     d->sendWidgetMouseEvent(event);
 }
mousePressEvent()
void QGraphicsProxyWidget::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1254 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::mousePressEvent";
 #endif
     d->sendWidgetMouseEvent(event);
 }
mouseReleaseEvent()
void QGraphicsProxyWidget::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1317 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::mouseReleaseEvent";
 #endif
     d->sendWidgetMouseEvent(event);
 }
newProxyWidget
QGraphicsProxyWidget * QGraphicsProxyWidget::newProxyWidget (const QWidget * child) protected slot
Since
4.5
Creates a proxy widget for the given child of the widget contained in this proxy.
You should not call this function directly; use QGraphicsProxyWidget::createProxyForChildWidget() instead.
This function is a fake virtual slot that you can reimplement in your subclass in order to control how new proxy widgets are created. The default implementation returns a proxy created with the QGraphicsProxyWidget() constructor with this proxy widget as the parent.
See also
createProxyForChildWidget()
Definition at line 1569 of file qgraphicsproxywidget.cpp.
 {
     return new QGraphicsProxyWidget(this);
 }
paint()
void QGraphicsProxyWidget::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Reimplemented Function
Implements QGraphicsItem.
Definition at line 1479 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     Q_UNUSED(widget);
     if (!d->widget || !d->widget->isVisible())
         return;
     // Filter out repaints on the window frame.
     const QRect exposedWidgetRect = (option->exposedRect & rect()).toAlignedRect();
     if (exposedWidgetRect.isEmpty())
         return;
     // Disable QPainter's default pen being cosmetic. This allows widgets and
     // styles to follow Qt's existing defaults without getting ugly cosmetic
     // lines when scaled.
     bool restore = !(painter->renderHints() & QPainter::NonCosmeticDefaultPen);
     painter->setRenderHints(QPainter::NonCosmeticDefaultPen, true);
     d->widget->render(painter, exposedWidgetRect.topLeft(), exposedWidgetRect);
     // Restore the render hints if necessary.
     if (restore)
         painter->setRenderHints(QPainter::NonCosmeticDefaultPen, false);
 }
resizeEvent()
void QGraphicsProxyWidget::resizeEvent (QGraphicsSceneResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1466 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     if (d->widget) {
         if (d->sizeChangeMode != QGraphicsProxyWidgetPrivate::WidgetToProxyMode)
             d->widget->resize(event->newSize().toSize());
     }
     QGraphicsWidget::resizeEvent(event);
 }
setGeometry()
void QGraphicsProxyWidget::setGeometry (const QRectF & rect) virtual
Reimplemented Function
Reimplemented from QGraphicsLayoutItem.
Definition at line 770 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     bool proxyResizesWidget = !d->posChangeMode && !d->sizeChangeMode;
     if (proxyResizesWidget) {
         d->posChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
         d->sizeChangeMode = QGraphicsProxyWidgetPrivate::ProxyToWidgetMode;
     }
     QGraphicsWidget::setGeometry(rect);
     if (proxyResizesWidget) {
         d->posChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
         d->sizeChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
     }
 }
setWidget()
void QGraphicsProxyWidget::setWidget (QWidget * widget)
Embeds widget into this proxy widget.
The embedded widget must reside exclusively either inside or outside of Graphics View. You cannot embed a widget as long as it is is visible elsewhere in the UI, at the same time.
widget must be a top-level widget whose parent is 0.
When the widget is embedded, its state (e.g., visible, enabled, geometry, size hints) is copied into the proxy widget. If the embedded widget is explicitly hidden or disabled, the proxy widget will become explicitly hidden or disabled after embedding is complete. The class documentation has a full overview over the shared state.
QGraphicsProxyWidget's window flags determine whether the widget, after embedding, will be given window decorations or not.
After this function returns, QGraphicsProxyWidget will keep its state synchronized with that of widget whenever possible.
If a widget is already embedded by this proxy when this function is called, that widget will first be automatically unembedded. Passing 0 for the widget argument will only unembed the widget, and the ownership of the currently embedded widget will be passed on to the caller. Every child widget that are embedded will also be embedded and their proxy widget destroyed.
Note that widgets with the Qt::WA_PaintOnScreen widget attribute set and widgets that wrap an external application or controller cannot be embedded. Examples are QGLWidget and QAxWidget.
See also
widget()
Definition at line 597 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsScene::addWidget(), createProxyForChildWidget(), and QGraphicsProxyWidgetPrivate::setWidget_helper().
 {
     Q_D(QGraphicsProxyWidget);
     d->setWidget_helper(widget, true);
 }
showEvent()
void QGraphicsProxyWidget::showEvent (QShowEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1005 of file qgraphicsproxywidget.cpp.
 {
     Q_UNUSED(event);
 }
sizeHint()
QSizeF QGraphicsProxyWidget::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const protected virtual
Reimplemented Function
Implements QGraphicsLayoutItem.
Definition at line 1428 of file qgraphicsproxywidget.cpp.
 {
     Q_D(const QGraphicsProxyWidget);
     if (!d->widget)
         return QGraphicsWidget::sizeHint(which, constraint);
     QSizeF sh;
     switch (which) {
     case Qt::PreferredSize:
         if (QLayout *l = d->widget->layout())
             sh = l->sizeHint();
         else
             sh = d->widget->sizeHint();
         break;
     case Qt::MinimumSize:
         if (QLayout *l = d->widget->layout())
             sh = l->minimumSize();
         else
             sh = d->widget->minimumSizeHint();
         break;
     case Qt::MaximumSize:
         if (QLayout *l = d->widget->layout())
             sh = l->maximumSize();
         else
             sh = QSizeF(QWIDGETSIZE_MAX, QWIDGETSIZE_MAX);
         break;
     case Qt::MinimumDescent:
         sh = constraint;
         break;
     default:
         break;
     }
     return sh;
 }
subWidgetRect()
QRectF QGraphicsProxyWidget::subWidgetRect (const QWidget * widget) const
Returns the rectangle for widget, which must be a descendant of widget(), or widget() itself, in this proxy item's local coordinates.
If no widget is embedded, widget is 0, or widget is not a descendant of the embedded widget, this function returns an empty QRectF.
See also
widget()
Definition at line 757 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate::updateProxyGeometryFromWidget().
 {
     Q_D(const QGraphicsProxyWidget);
     if (!widget || !d->widget)
         return QRectF();
     if (d->widget == widget || d->widget->isAncestorOf(widget))
         return QRectF(widget->mapTo(d->widget, QPoint(0, 0)), widget->size());
     return QRectF();
 }
type()
int QGraphicsProxyWidget::type () const virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1507 of file qgraphicsproxywidget.cpp.
 {
     return Type;
 }
ungrabMouseEvent()
void QGraphicsProxyWidget::ungrabMouseEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsWidget.
Definition at line 1232 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
     Q_UNUSED(event);
     d->embeddedMouseGrabber = 0;
 }
wheelEvent()
void QGraphicsProxyWidget::wheelEvent (QGraphicsSceneWheelEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1279 of file qgraphicsproxywidget.cpp.
 {
     Q_D(QGraphicsProxyWidget);
 #ifdef GRAPHICSPROXYWIDGET_DEBUG
     qDebug() << "QGraphicsProxyWidget::wheelEvent";
 #endif
     if (!d->widget)
         return;
     QPointF pos = event->pos();
     QPointer<QWidget> receiver = d->widget->childAt(pos.toPoint());
     if (!receiver)
         receiver = d->widget;
     // Map event position from us to the receiver
     pos = d->mapToReceiver(pos, receiver);
     // Send mouse event.
     QWheelEvent wheelEvent(pos.toPoint(), event->screenPos(), event->delta(),
                            event->buttons(), event->modifiers(), event->orientation());
     QPointer<QWidget> focusWidget = d->widget->focusWidget();
     extern bool qt_sendSpontaneousEvent(QObject *, QEvent *);
     qt_sendSpontaneousEvent(receiver, &wheelEvent);
     event->setAccepted(wheelEvent.isAccepted());
     // ### Remove, this should be done by proper focusIn/focusOut events.
     if (focusWidget && !focusWidget->hasFocus()) {
         focusWidget->update();
         focusWidget = d->widget->focusWidget();
         if (focusWidget && focusWidget->hasFocus())
             focusWidget->update();
     }
 }
widget()
QWidget * QGraphicsProxyWidget::widget () const
Returns a pointer to the embedded widget.
See also
setWidget()
Definition at line 742 of file qgraphicsproxywidget.cpp.
Referenced by _q_paintItem(), QGraphicsScenePrivate::drawItemHelper(), QMotifStyle::event(), QMacStyle::event(), QGraphicsWidget::paintWindowFrame(), QGraphicsProxyWidgetPrivate::setWidget_helper(), and QGraphicsViewPrivate::updateInputMethodSensitivity().
 {
     Q_D(const QGraphicsProxyWidget);
     return d->widget;
 }
Friends and Related Functions
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 137 of file qgraphicsproxywidget.h.
QWidget
friend class QWidget friend
Definition at line 135 of file qgraphicsproxywidget.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 136 of file qgraphicsproxywidget.h.
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsproxywidget.h
/src/gui/graphicsview/qgraphicsproxywidget.cpp