Qt 4.8: QAudioDeviceFactory Class Reference
QAudioDeviceFactory Class Reference
#include <qaudiodevicefactory_p.h>
Static Public Functions
static QAbstractAudioDeviceInfo * audioDeviceInfo (const QString &realm, const QByteArray &handle, QAudio::Mode mode)
static QList< QAudioDeviceInfo > availableDevices (QAudio::Mode mode)
static QAbstractAudioInput * createDefaultInputDevice (QAudioFormat const &format)
static QAbstractAudioOutput * createDefaultOutputDevice (QAudioFormat const &format)
static QAbstractAudioInput * createInputDevice (QAudioDeviceInfo const &device, QAudioFormat const &format)
static QAbstractAudioInput * createNullInput ()
static QAbstractAudioOutput * createNullOutput ()
static QAbstractAudioOutput * createOutputDevice (QAudioDeviceInfo const &device, QAudioFormat const &format)
static QAudioDeviceInfo defaultInputDevice ()
static QAudioDeviceInfo defaultOutputDevice ()
Detailed Description
Definition at line 72 of file qaudiodevicefactory_p.h.
Functions
audioDeviceInfo()
QAbstractAudioDeviceInfo * QAudioDeviceFactory::audioDeviceInfo (const QString & realm, const QByteArray & handle, QAudio::Mode mode) static
Definition at line 198 of file qaudiodevicefactory.cpp.
Referenced by QAudioDeviceInfoPrivate::operator=(), and QAudioDeviceInfoPrivate::QAudioDeviceInfoPrivate().
 {
     QAbstractAudioDeviceInfo *rc = 0;
 #ifndef QT_NO_AUDIO_BACKEND
 #if (defined(Q_OS_WIN) || defined(Q_OS_MAC) || defined(HAS_ALSA) || defined(Q_OS_SYMBIAN))
     if (realm == QLatin1String("builtin"))
         return new QAudioDeviceInfoInternal(handle, mode);
 #endif
 #endif
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QAudioEngineFactoryInterface* plugin =
         qobject_cast<QAudioEngineFactoryInterface*>(loader()->instance(realm));
     if (plugin)
         rc = plugin->createDeviceInfo(handle, mode);
 #endif
     return rc == 0 ? new QNullDeviceInfo() : rc;
 }
availableDevices()
QList< QAudioDeviceInfo > QAudioDeviceFactory::availableDevices (QAudio::Mode mode) static
Definition at line 133 of file qaudiodevicefactory.cpp.
Referenced by QAudioDeviceInfo::availableDevices().
 {
     QList<QAudioDeviceInfo> devices;
 #ifndef QT_NO_AUDIO_BACKEND
 #if (defined(Q_OS_WIN) || defined(Q_OS_MAC) || defined(HAS_ALSA) || defined(Q_OS_SYMBIAN))
     foreach (const QByteArray &handle, QAudioDeviceInfoInternal::availableDevices(mode))
         devices << QAudioDeviceInfo(QLatin1String("builtin"), handle, mode);
 #endif
 #endif
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QFactoryLoader* l = loader();
     foreach (QString const& key, l->keys()) {
         QAudioEngineFactoryInterface* plugin = qobject_cast<QAudioEngineFactoryInterface*>(l->instance(key));
         if (plugin) {
             foreach (QByteArray const& handle, plugin->availableDevices(mode))
                 devices << QAudioDeviceInfo(key, handle, mode);
         }
         delete plugin;
     }
 #endif
     return devices;
 }
createDefaultInputDevice()
QAbstractAudioInput * QAudioDeviceFactory::createDefaultInputDevice (QAudioFormat const & format) static
Definition at line 218 of file qaudiodevicefactory.cpp.
Referenced by QAudioInput::QAudioInput().
 {
     return createInputDevice(defaultInputDevice(), format);
 }
createDefaultOutputDevice()
QAbstractAudioOutput * QAudioDeviceFactory::createDefaultOutputDevice (QAudioFormat const & format) static
Definition at line 223 of file qaudiodevicefactory.cpp.
Referenced by QAudioOutput::QAudioOutput().
 {
     return createOutputDevice(defaultOutputDevice(), format);
 }
createInputDevice()
QAbstractAudioInput * QAudioDeviceFactory::createInputDevice (QAudioDeviceInfo const & device, QAudioFormat const & format) static
Definition at line 228 of file qaudiodevicefactory.cpp.
Referenced by QAudioInput::QAudioInput().
 {
     if (deviceInfo.isNull())
         return new QNullInputDevice();
 #ifndef QT_NO_AUDIO_BACKEND
 #if (defined(Q_OS_WIN) || defined(Q_OS_MAC) || defined(HAS_ALSA) || defined(Q_OS_SYMBIAN))
     if (deviceInfo.realm() == QLatin1String("builtin"))
         return new QAudioInputPrivate(deviceInfo.handle(), format);
 #endif
 #endif
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QAudioEngineFactoryInterface* plugin =
         qobject_cast<QAudioEngineFactoryInterface*>(loader()->instance(deviceInfo.realm()));
     if (plugin)
         return plugin->createInput(deviceInfo.handle(), format);
 #endif
     return new QNullInputDevice();
 }
createNullInput()
static QAbstractAudioInput* QAudioDeviceFactory::createNullInput () static
createNullOutput()
static QAbstractAudioOutput* QAudioDeviceFactory::createNullOutput () static
createOutputDevice()
QAbstractAudioOutput * QAudioDeviceFactory::createOutputDevice (QAudioDeviceInfo const & device, QAudioFormat const & format) static
Definition at line 248 of file qaudiodevicefactory.cpp.
Referenced by QAudioOutput::QAudioOutput().
 {
     if (deviceInfo.isNull())
         return new QNullOutputDevice();
 #ifndef QT_NO_AUDIO_BACKEND
 #if (defined(Q_OS_WIN) || defined(Q_OS_MAC) || defined(HAS_ALSA) || defined(Q_OS_SYMBIAN))
     if (deviceInfo.realm() == QLatin1String("builtin"))
         return new QAudioOutputPrivate(deviceInfo.handle(), format);
 #endif
 #endif
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QAudioEngineFactoryInterface* plugin =
         qobject_cast<QAudioEngineFactoryInterface*>(loader()->instance(deviceInfo.realm()));
     if (plugin)
         return plugin->createOutput(deviceInfo.handle(), format);
 #endif
     return new QNullOutputDevice();
 }
defaultInputDevice()
QAudioDeviceInfo QAudioDeviceFactory::defaultInputDevice () static
Definition at line 158 of file qaudiodevicefactory.cpp.
Referenced by QAudioDeviceInfo::defaultInputDevice().
 {
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QAudioEngineFactoryInterface* plugin = qobject_cast<QAudioEngineFactoryInterface*>(loader()->instance(QLatin1String("default")));
     if (plugin) {
         QList<QByteArray> list = plugin->availableDevices(QAudio::AudioInput);
         if (list.size() > 0)
             return QAudioDeviceInfo(QLatin1String("default"), list.at(0), QAudio::AudioInput);
     }
 #endif
 #ifndef QT_NO_AUDIO_BACKEND
 #if (defined(Q_OS_WIN) || defined(Q_OS_MAC) || defined(HAS_ALSA) || defined(Q_OS_SYMBIAN))
     return QAudioDeviceInfo(QLatin1String("builtin"), QAudioDeviceInfoInternal::defaultInputDevice(), QAudio::AudioInput);
 #endif
 #endif
     return QAudioDeviceInfo();
 }
defaultOutputDevice()
QAudioDeviceInfo QAudioDeviceFactory::defaultOutputDevice () static
Definition at line 178 of file qaudiodevicefactory.cpp.
Referenced by QAudioDeviceInfo::defaultOutputDevice().
 {
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QAudioEngineFactoryInterface* plugin = qobject_cast<QAudioEngineFactoryInterface*>(loader()->instance(QLatin1String("default")));
     if (plugin) {
         QList<QByteArray> list = plugin->availableDevices(QAudio::AudioOutput);
         if (list.size() > 0)
             return QAudioDeviceInfo(QLatin1String("default"), list.at(0), QAudio::AudioOutput);
     }
 #endif
 #ifndef QT_NO_AUDIO_BACKEND
 #if (defined(Q_OS_WIN) || defined(Q_OS_MAC) || defined(HAS_ALSA) || defined(Q_OS_SYMBIAN))
     return QAudioDeviceInfo(QLatin1String("builtin"), QAudioDeviceInfoInternal::defaultOutputDevice(), QAudio::AudioOutput);
 #endif
 #endif
     return QAudioDeviceInfo();
 }
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudiodevicefactory_p.h
/src/multimedia/audio/qaudiodevicefactory.cpp