Qt 4.8: QPodList< T, Prealloc > Class Template Reference
QPodList< T, Prealloc > Class Template Reference
#include <qpodlist_p.h>
Public Functions
void insert (int idx, const T &t)
QPodList (int size=0)
void removeAll (const T &t)
void removeAt (int idx)
T takeFirst ()
Public Functions inherited from QVarLengthArray< T, Prealloc >
void append (const T &t)
void append (const T *buf, int size)
const T & at (int idx) const
iterator begin ()
const_iterator begin () const
int capacity () const
void clear ()
const_iterator constBegin () const
const T * constData () const
const_iterator constEnd () const
int count () const
T * data ()
const T * data () const
iterator end ()
const_iterator end () const
iterator erase (iterator begin, iterator end)
iterator erase (iterator pos)
void insert (int i, const T &t)
void insert (int i, int n, const T &t)
iterator insert (iterator before, int n, const T &x)
iterator insert (iterator before, const T &x)
bool isEmpty () const
QVarLengthArray< T, Prealloc > & operator+= (const T &t)
QVarLengthArray< T, Prealloc > & operator<< (const T &t)
QVarLengthArray< T, Prealloc > & operator= (const QVarLengthArray< T, Prealloc > &other)
T & operator[] (int idx)
const T & operator[] (int idx) const
void prepend (const T &t)
QVarLengthArray (int size=0)
QVarLengthArray (const QVarLengthArray< T, Prealloc > &other)
void remove (int i)
void remove (int i, int n)
void removeLast ()
void replace (int i, const T &t)
void reserve (int size)
void resize (int size)
int size () const
T value (int i) const
T value (int i, const T &defaultValue) const
~QVarLengthArray ()
Additional Inherited Members
Public Types inherited from QVarLengthArray< T, Prealloc >
typedef const T * const_iterator
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef qptrdiff difference_type
typedef T * iterator
typedef value_type * pointer
typedef value_type & reference
typedef int size_type
typedef T value_type
Detailed Description
template<typename T, int Prealloc>
class QPodList< T, Prealloc >
Definition at line 65 of file qpodlist_p.h.
Constructors and Destructors
QPodList()
template<typename T, int Prealloc> QPodList< T, Prealloc >::QPodList (int size = 0) inline explicit
Definition at line 72 of file qpodlist_p.h.
         : QVarLengthArray<T, Prealloc>(size)
     {}
Functions
insert()
template<typename T, int Prealloc> void QPodList< T, Prealloc >::insert (int idx, const T & t) inline
Definition at line 76 of file qpodlist_p.h.
Referenced by QEventDispatcherUNIX::registerSocketNotifier().
     {
         const int sz = s++;
         if (s == a)
             realloc(s, s << 1);
         ::memmove(ptr + idx + 1, ptr + idx, (sz - idx) * sizeof(T));
         ptr[idx] = t;
     }
removeAll()
template<typename T, int Prealloc> void QPodList< T, Prealloc >::removeAll (const T & t) inline
Definition at line 85 of file qpodlist_p.h.
     {
         int i = 0;
         for (int j = 0; j < s; ++j) {
             if (ptr[j] != t)
                 ptr[i++] = ptr[j];
         }
         s = i;
     }
removeAt()
template<typename T, int Prealloc> void QPodList< T, Prealloc >::removeAt (int idx) inline
Definition at line 95 of file qpodlist_p.h.
Referenced by QPodList< QSockNot *, 32 >::takeFirst(), and QEventDispatcherUNIX::unregisterSocketNotifier().
     {
         Q_ASSERT(idx >= 0 && idx < s);
         ::memmove(ptr + idx, ptr + idx + 1, (s - idx - 1) * sizeof(T));
         --s;
     }
takeFirst()
template<typename T, int Prealloc> T QPodList< T, Prealloc >::takeFirst () inline
Definition at line 102 of file qpodlist_p.h.
     {
         Q_ASSERT(s > 0);
         T tmp = ptr[0];
         removeAt(0);
         return tmp;
     }
The documentation for this class was generated from the following file:
/src/corelib/tools/qpodlist_p.h