Qt 4.8: QAbstractXmlNodeModel Class Reference
QAbstractXmlNodeModel Class Reference abstract
The QAbstractXmlNodeModel class is an abstract base class for modeling non-XML data to look like XML for QXmlQuery.
#include <qabstractxmlnodemodel.h>
Public Types
typedef QList< Ptr > List
A list of smart pointers to instances of QAbstractXmlNodeModel.
enum NodeCopySetting { InheritNamespaces = 0x1, PreserveNamespaces = 0x2 }
typedef QFlags< NodeCopySetting > NodeCopySettings
typedef QExplicitlySharedDataPointer< QAbstractXmlNodeModel > Ptr
A QExplicitlySharedDataPointer {smart pointer} to an instance of QAbstractXmlNodeModel.
enum SimpleAxis { Parent, FirstChild, PreviousSibling, NextSibling }
Four axes that each contain one node only.
Public Functions
virtual QUrl baseUri (const QXmlNodeModelIndex &ni) const =0
Returns the base URI for the node whose index is n.
virtual QXmlNodeModelIndex::DocumentOrder compareOrder (const QXmlNodeModelIndex &ni1, const QXmlNodeModelIndex &ni2) const =0
This function returns the relative document order for the nodes indexed by ni1 and ni2.
virtual void copyNodeTo (const QXmlNodeModelIndex &node, QAbstractXmlReceiver *const receiver, const NodeCopySettings &) const
virtual QUrl documentUri (const QXmlNodeModelIndex &ni) const =0
Returns the document URI of n.
virtual QXmlNodeModelIndex elementById (const QXmlName &NCName) const =0
Returns the index of the element identified as id.
virtual bool isDeepEqual (const QXmlNodeModelIndex &ni1, const QXmlNodeModelIndex &ni2) const
Determines whether ni1 is deep equal to ni2.
virtual QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< QXmlNodeModelIndex > > iterate (const QXmlNodeModelIndex &ni, QXmlNodeModelIndex::Axis axis) const
Performs navigation, starting from ni, by returning an QAbstractXmlForwardIterator that returns nodes the axis emanating from ni.
virtual QXmlNodeModelIndex::NodeKind kind (const QXmlNodeModelIndex &ni) const =0
Returns a value indicating the kind of node identified by ni.
virtual QXmlName name (const QXmlNodeModelIndex &ni) const =0
Returns the name of ni.
virtual QVector< QXmlName > namespaceBindings (const QXmlNodeModelIndex &n) const =0
Returns the in-scope namespaces of n.
virtual QXmlName::NamespaceCode namespaceForPrefix (const QXmlNodeModelIndex &ni, const QXmlName::PrefixCode prefix) const
Returns the namespace URI on ni that corresponds to prefix.
virtual QVector< QXmlNodeModelIndex > nodesByIdref (const QXmlName &NCName) const =0
Returns the elements and/or attributes that have an IDREF value equal to idref.
QAbstractXmlNodeModel ()
Default constructor.
virtual QXmlNodeModelIndex root (const QXmlNodeModelIndex &n) const =0
Returns the root node of the tree that contains the node whose index is n.
virtual void sendNamespaces (const QXmlNodeModelIndex &n, QAbstractXmlReceiver *const receiver) const
Sends the namespaces declared on n to receiver.
virtual QPatternist::ItemIteratorPtr sequencedTypedValue (const QXmlNodeModelIndex &ni) const
QSourceLocation sourceLocation (const QXmlNodeModelIndex &index) const
Returns the source location for the object with the given index or a default constructed QSourceLocation in case no location information is available.
virtual QString stringValue (const QXmlNodeModelIndex &n) const =0
Returns the string value for node n.
virtual QPatternist::ItemTypePtr type (const QXmlNodeModelIndex &ni) const
virtual QVariant typedValue (const QXmlNodeModelIndex &n) const =0
Returns the typed value for node node.
virtual ~QAbstractXmlNodeModel ()
Destructor.
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Protected Functions
virtual QVector< QXmlNodeModelIndex > attributes (const QXmlNodeModelIndex &element) const =0
Returns the attributes of element.
QXmlNodeModelIndex createIndex (qint64 data) const
Creates a node index with data as its internal data.
QXmlNodeModelIndex createIndex (void *pointer, qint64 additionalData=0) const
Creates a node index with pointer and additionalData as its internal data.
QXmlNodeModelIndex createIndex (qint64 data, qint64 additionalData) const
Creates a QXmlNodeModelIndex containing data and additionalData.
virtual QXmlNodeModelIndex nextFromSimpleAxis (SimpleAxis axis, const QXmlNodeModelIndex &origin) const =0
When QtXmlPatterns evaluate path expressions, it emulate them through a combination of calls with QSimpleXmlNodeModel::SimpleAxis values.
QAbstractXmlNodeModel (QAbstractXmlNodeModelPrivate *d)
Protected Variables
QScopedPointer< QAbstractXmlNodeModelPrivate > d_ptr
Private Functions
QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< QXmlNodeModelIndex > > mapToSequence (const QXmlNodeModelIndex &ni, const QExplicitlySharedDataPointer< QPatternist::DynamicContext > &) const
Static Private Functions
static bool isIgnorableInDeepEqual (const QXmlNodeModelIndex &n)
Friends
class QPatternist::ItemMappingIterator< QXmlNodeModelIndex, QXmlNodeModelIndex, const QAbstractXmlNodeModel *, QExplicitlySharedDataPointer< QPatternist::DynamicContext > >
class QPatternist::SequenceMappingIterator< QXmlNodeModelIndex, QXmlNodeModelIndex, const QAbstractXmlNodeModel *>
class QPatternist::XsdValidatedXmlNodeModel
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
The QAbstractXmlNodeModel class is an abstract base class for modeling non-XML data to look like XML for QXmlQuery.
Note
This class or function is threadsafe.
Since
4.4
The QAbstractXmlNodeModel specifies the interface that a node model must implement for that node model be accessible to the query engine for processing XQuery queries. A node model represents data as a structure that can be queried as if the data were XML.
The node model represented by a subclass of QAbstractXmlNodeModel is meant to be accessed by the QtXmlPatterns query engine. If the API seems a little strange in a few places, it is because the member functions are called by the query engine as it evaluates an XQuery. They aren't meant to be used programatically.
Usage
QAbstractXmlNodeModel bridges the gap between the arbitrary structure of the non-XML data to be queried and the well-defined structure of XML data understood by QXmlQuery.
Consider a chemistry application that reads the file chemistryData, which contains non-XML data that represents a chemical structure composed of molecules and atoms. The application will query this chemistry data with an XQuery it reads from file queryFile. We write a custom subclass of QAbstractXmlNodeModel (ChemistryNodeModel) that reads chemistryData and builds a data structure, perhaps composed of objects of our own classes molecule and atom. Clearly, this data structure is not XML. Our custom subclass will know how to traverse this non-XML structure and present it through the http://www.w3.org/TR/xpath-datamodel/ {XPath Data Model interface}.
The application first creates an instance of QXmlQuery and calls QXmlQuery::setQuery() to read queryFile containing the XQuery we want to run. Then it creates an instance of our custom node model class, ChemistryNodeModel, which is a subclass of QAbstractXmlNodeModel. Its constructor is called with the QXmlNamePool {name pool} obtained from our QXmlQuery, and with the chemistryFile containing the structure of molecules and atoms to be queried. The QXmlNamePool {name pool} is required because our custom node model has the member function QAbstractXmlNodeModel::name() {name()}, which returns the QXmlName {name} of any node in the model. The QXmlQuery {query} and the custom node model must use the same name pool for constructing these QXmlName {names}. The constructor would then read chemistryFile and build the custom node model structure.
To connect the query to the custom node model, we must bind a variable name used in the query to a node in the model. The variable can then be used in the query as a starting node. First, an QXmlNodeModelIndex {index} for the desired starting node is retrieved by calling QAbstractXmlNodeModel::createIndex(). Then the index is bound to a variable name, in this case queryRoot, by passing the name and the index to QXmlQuery::bindVariable(). The query can then use a variable reference $queryRoot to refer to the starting node. Note that if the QXmlQuery {query} uses multiple variable references, a call to QXmlQuery::bindVariable() is required to bind each different variable name to a node in the model.
The query is executed when the application calls one of the QXmlQuery evaluation functions. The application uses QXmlQuery::evaluateTo(QAbstractXmlReceiver *), because it then uses a QXmlSerializer {serializer} to out the query result as XML to stdout. We could have used QXmlQuery::evaluateTo(QXmlResultItems) to get a list of result items, or QXmlQuery::evaluateTo(QStringList *) if the query evaluated to a sequence of {xs:string} values.
During query execution, the engine iterates over the node model using nextFromSimpleAxis() to get the QXmlNodeModelIndex {index} of the next node to be visited. The engine can get the name of a node by calling name() with the node's QXmlNodeModelIndex {index}. stringValue(), baseUri(), documentUri() and kind() are also called as needed with a node QXmlNodeModelIndex {index}.
The example demonstrates the standard pattern for using a subclass of QAbstractXmlNodeModel in combination with QXmlQuery to perform an XQuery.
Instantiate QXmlQuery and give it the XQuery to be run;
Instantiate a subclass of QAbstractXmlNodeModel or QSimpleXmlNodeModel;
Retrieve a QXmlNodeModelIndex for the node in the model where the QXmlQuery should start the query;
Use QXmlQuery::bindVariable() to bind the QXmlNodeModelIndex to {$variable name};
Call one of the QXmlQuery evaluation functions to run the query.
Subclassing
Because the http://www.w3.org/TR/xpath-datamodel/ {XPath Data Model interface} presented by QAbstractXmlNodeModel allows QXmlQuery to operate on non-XML data as if it were XML, implementing subclasses of QAbstractXmlNodeModel can involve a significant amount of work. The QSimpleXmlNodeModel class is provided to simplify the implementation for many common use cases.
Thread Safety
Because the node model can be accessed concurrently by threads in the QtXmlPatterns module, subclasses of QAbstractXmlNodeModel must be written to be Reentrancy and Thread-Safety{thread-safe}. Classes that simplify implementing thread-safety include QReadLocker and QWriteLocker.
See the example File System Example for a demonstration.
Definition at line 271 of file qabstractxmlnodemodel.h.
Typedefs
List
QAbstractXmlNodeModel::List
A list of smart pointers to instances of QAbstractXmlNodeModel.
See also
QExplicitlySharedDataPointer
Definition at line 283 of file qabstractxmlnodemodel.h.
NodeCopySettings
QAbstractXmlNodeModel::NodeCopySettings
Warning
This function is not part of the public interface.
Definition at line 321 of file qabstractxmlnodemodel.h.
Ptr
QAbstractXmlNodeModel::Ptr
A QExplicitlySharedDataPointer {smart pointer} to an instance of QAbstractXmlNodeModel.
See also
QExplicitlySharedDataPointer
Definition at line 282 of file qabstractxmlnodemodel.h.
Enumerations
NodeCopySetting
enum QAbstractXmlNodeModel::NodeCopySetting
Warning
This function is not part of the public interface.
Controls how nodes are copied with copyNodeTo.
InheritNamespaces Copies the node with the copy-namespaces setting being inherit. If not set, no-inherit is assumed.
PreserveNamespaces Copies the node with the copy-namespaces settings being preserve. If not set, no-preserve is assumed.
Enumerator
InheritNamespaces
PreserveNamespaces
Definition at line 315 of file qabstractxmlnodemodel.h.
     {
         InheritNamespaces   = 0x1,
         PreserveNamespaces  = 0x2
     };
SimpleAxis
enum QAbstractXmlNodeModel::SimpleAxis
Four axes that each contain one node only.
Parent The parent of the context node
FirstChild The first child of the context node
PreviousSibling The previous child of the context node
NextSibling The next child of the context node
Enumerator
Parent
FirstChild
PreviousSibling
NextSibling
Definition at line 274 of file qabstractxmlnodemodel.h.
     {
         Parent,
         FirstChild,
         PreviousSibling,
         NextSibling
     };
Constructors and Destructors
QAbstractXmlNodeModel() [1/2]
QAbstractXmlNodeModel::QAbstractXmlNodeModel ()
Default constructor.
Definition at line 291 of file qabstractxmlnodemodel.cpp.
                                              : d_ptr(0)
 {
 }
~QAbstractXmlNodeModel()
QAbstractXmlNodeModel::~QAbstractXmlNodeModel () virtual
Destructor.
Definition at line 308 of file qabstractxmlnodemodel.cpp.
 {
 }
QAbstractXmlNodeModel() [2/2]
QAbstractXmlNodeModel::QAbstractXmlNodeModel (QAbstractXmlNodeModelPrivate * d) protected
Warning
This function is not part of the public interface.
Takes the d-pointer.
Definition at line 301 of file qabstractxmlnodemodel.cpp.
                                                                             : d_ptr(d)
 {
 }
Functions
attributes()
QVector< QXmlNodeModelIndex > QAbstractXmlNodeModel::attributes (const QXmlNodeModelIndex & element) const protected pure virtual
Returns the attributes of element.
The caller guarantees that element is an element in this node model.
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::attributes(), and iterate().
baseUri()
QUrl QAbstractXmlNodeModel::baseUri (const QXmlNodeModelIndex & n) const pure virtual
Returns the base URI for the node whose index is n.
The caller guarantees that n is not null and that it belongs to a node in this node model.
The base URI of a node can be extracted using the fn:base-uri() function. The base URI is typically used for resolving relative URIs that appear in the node or its children. It is conformant to just return the document URI, although that might not properly reflect the underlying data.
This function maps to the dm:base-uri accessor, which returns a base URI according to the following:
For document nodes, the base URI and the document URI are the same.
For elements, the base URI is the URI appearing in the element's xml:base attribute, if present, or it is resolved to the parent element's base URI.
Namespace nodes have no base URI.
The base URI for a processing instruction, comment, attribute, or text node is the base URI of the node's parent element.
The implementation guarantees to return a valid QUrl, or a default constructed QUrl. If a node has no base URI, as in the case where a comment has no parent, a default constructed QUrl is returned.
See also
{http://www.w3.org/TR/xpath-datamodel/#dm-base-uri}{XQuery 1.0 and XPath 2.0 Data Model (XDM), 5.2 base-uri Accessor}
Implemented in QPatternist::AccelTree, QPatternist::XsdValidatedXmlNodeModel, and QSimpleXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::baseUri().
compareOrder()
QXmlNodeModelIndex::DocumentOrder QAbstractXmlNodeModel::compareOrder (const QXmlNodeModelIndex & ni1, const QXmlNodeModelIndex & ni2) const pure virtual
This function returns the relative document order for the nodes indexed by ni1 and ni2.
It is used for the Is operator and for sorting nodes in document order.
The caller guarantees that ni1 and ni2 are not null and that both identify nodes in this node model.
If ni1 is identical to ni2, QXmlNodeModelIndex::Is is returned. If ni1 precedes ni2 in document order, QXmlNodeModelIndex::Precedes is returned. If ni1 follows ni2 in document order, QXmlNodeModelIndex::Follows is returned.
See also
{http://www.w3.org/TR/xpath-datamodel/#document-order}{XQuery 1.0 and XPath 2.0 Data Model (XDM), 2.4 Document Order}
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::compareOrder().
copyNodeTo()
void QAbstractXmlNodeModel::copyNodeTo (const QXmlNodeModelIndex & node, QAbstractXmlReceiver *const receiver, const NodeCopySettings &) const virtual
Warning
This function is not part of the public interface.
Copies node node to receiver, steered by copySettings.
The caller guarantees that node is not null, and that is belongs to this QAbstractXmlNodeModel instance.
The caller guarantees that receiver is not null.
Definition at line 1724 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdValidatedXmlNodeModel::copyNodeTo(), and QPatternist::CopyOf::evaluateToSequenceReceiver().
 {
     Q_UNUSED(node);
     Q_UNUSED(receiver);
     Q_UNUSED(copySettings);
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "This function is not expected to be called.");
 }
createIndex() [1/3]
QXmlNodeModelIndex QAbstractXmlNodeModel::createIndex (qint64 data) const inline protected
Creates a node index with data as its internal data.
data is not constrained.
Definition at line 335 of file qabstractxmlnodemodel.h.
Referenced by QPatternist::AccelTree::elementById(), QPatternist::AccelTree::iterate(), QPatternist::AncestorIterator< IncludeSelf >::next(), QPatternist::ChildIterator::next(), QPatternist::SiblingIterator< IsFollowing >::next(), QPatternist::DescendantIterator< IncludeSelf >::next(), QPatternist::FollowingIterator::next(), QPatternist::PrecedingIterator::next(), QPatternist::AttributeIterator::next(), QPatternist::AccelTree::parent(), and QPatternist::AccelTree::root().
     {
         return QXmlNodeModelIndex::create(data, this);
     }
createIndex() [2/3]
QXmlNodeModelIndex QAbstractXmlNodeModel::createIndex (void * pointer, qint64 additionalData = 0) const inline protected
Creates a node index with pointer and additionalData as its internal data.
What pointer and additionalData is, is not constrained.
Definition at line 340 of file qabstractxmlnodemodel.h.
     {
         return QXmlNodeModelIndex::create(qptrdiff(pointer), this, additionalData);
     }
createIndex() [3/3]
QXmlNodeModelIndex QAbstractXmlNodeModel::createIndex (qint64 data, qint64 additionalData) const inline protected
Creates a QXmlNodeModelIndex containing data and additionalData.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 346 of file qabstractxmlnodemodel.h.
     {
         return QXmlNodeModelIndex::create(data, this, additionalData);
     }
documentUri()
QUrl QAbstractXmlNodeModel::documentUri (const QXmlNodeModelIndex & n) const pure virtual
Returns the document URI of n.
The document URI identifies the resource which is the document. For example, the document could be a regular file, e.g., file:/, or it could be the http:// URL of the location of a file. The document URI is used for resolving URIs and to simply know where the document is.
If the node model maps to a URI in a natural way, return that URI. Otherwise, return the company or product URI. The document URI can be any URI as long as its valid and absolute.
The caller guarantees that n is not null and that it belongs to this QAbstractXmlNodeModel.
This function maps to the dm:document-uri accessor, which returns a document URI according to the following:
If n is a document node, return an absolute QUrl containing the document URI, or a default constructed QUrl. The latter signals that no document URI is available for the document node.
For all other nodes, return a default constructed QUrl.
See also
{http://www.w3.org/TR/xpath-datamodel/#dm-document-uri}{XQuery 1.0 and XPath 2.0 Data Model (XDM), 5.4 document-uri Accessor}
QUrl::isValid(), QUrl::isRelative()
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by QSimpleXmlNodeModel::baseUri(), and QPatternist::XsdValidatedXmlNodeModel::documentUri().
elementById()
QXmlNodeModelIndex QAbstractXmlNodeModel::elementById (const QXmlName & id) const pure virtual
Returns the index of the element identified as id.
XQuery's id() function calls this function.
The node index returned will be the element node whose value is of type ID and equals id, or it will be the element node that has an attribute whose typed value is of type ID and equals id. If there is no such element, a default constructed QXmlNodeModelIndex instance is returned. The implementor guarantees that if the returned node index is not null, it identifies an element.
It is not sufficient for an attribute or element to merely be called id. Its value type must also be ID. However, the reserved name xml:id is sufficient.
In id, the namespace URI and the prefix are undefined, and the local name is the ID that should be looked up.
See also
{http://www.w3.org/TR/xpath-functions/#func-id}{XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.2 fn:id}
Implemented in QPatternist::AccelTree, QPatternist::XsdValidatedXmlNodeModel, and QSimpleXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::elementById().
isDeepEqual()
bool QAbstractXmlNodeModel::isDeepEqual (const QXmlNodeModelIndex & n1, const QXmlNodeModelIndex & n2) const virtual
Determines whether ni1 is deep equal to ni2.
Warning
This function is not part of the public interface.
isDeepEqual() is defined as evaluating the expression fn:deep-equal($n1, $n2) where $n1 is ni1 and $n1 is ni2. This function is associative, meaning the same value is returned regardless of if isDeepEqual() is invoked with ni1 as first argument or second. It is guaranteed that ni1 and ni2 are nodes, as opposed to the definition of fn:deep-equal().
Returns true if ni1 is deep-equal to ni2, otherwise false
See also
{"http://www.w3.org/TR/xpath-functions/#func-deep-equal"}{XQuery 1.0 and XPath 2.0 Functions and Operators, 15.3.1 fn:deep-equal}
Reimplemented in QPatternist::XsdValidatedXmlNodeModel.
Definition at line 1071 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdValidatedXmlNodeModel::isDeepEqual().
 {
     Q_ASSERT(!n1.isNull());
     Q_ASSERT(!n2.isNull());
     const QXmlNodeModelIndex::NodeKind nk = n1.kind();
     if(nk != n2.kind())
         return false;
     if(n1.name() != n2.name())
         return false;
     switch(nk)
     {
         case QXmlNodeModelIndex::Element:
         {
             QXmlNodeModelIndexIteratorPointer atts1(n1.iterate(QXmlNodeModelIndex::AxisAttribute));
             QXmlNodeModelIndex node(atts1->next());
             const QXmlNodeModelIndex::List atts2(n2.iterate(QXmlNodeModelIndex::AxisAttribute)->toList());
             const QXmlNodeModelIndex::List::const_iterator end(atts2.constEnd());
             while(!node.isNull())
             {
                 bool equal = false;
                 for(QXmlNodeModelIndex::List::const_iterator it = atts2.constBegin(); it != end; ++it)
                 {
                     if(isDeepEqual(node, (*it)))
                         equal = true;
                 }
                 if(!equal)
                     return false;
                 node = atts1->next();
             }
             /* Fallthrough, so we check the children. */
         }
         case QXmlNodeModelIndex::Document:
         {
             QXmlNodeModelIndexIteratorPointer itn1(n1.iterate(QXmlNodeModelIndex::AxisChild));
             QXmlNodeModelIndexIteratorPointer itn2(n2.iterate(QXmlNodeModelIndex::AxisChild));
             while(true)
             {
                 QXmlNodeModelIndex no1(itn1->next());
                 QXmlNodeModelIndex no2(itn2->next());
                 while(!no1.isNull() && isIgnorableInDeepEqual(no1))
                     no1 = itn1->next();
                 while(!no2.isNull() && isIgnorableInDeepEqual(no2))
                     no2 = itn2->next();
                 if(!no1.isNull() && !no2.isNull())
                 {
                    if(!isDeepEqual(no1, no2))
                        return false;
                 }
                 else
                     return no1.isNull() && no2.isNull();
             }
             return true;
         }
         case QXmlNodeModelIndex::Attribute:
         /* Fallthrough */
         case QXmlNodeModelIndex::ProcessingInstruction:
         /* Fallthrough. */
         case QXmlNodeModelIndex::Text:
         /* Fallthrough. */
         case QXmlNodeModelIndex::Comment:
             return n1.stringValue() == n2.stringValue();
         case QXmlNodeModelIndex::Namespace:
         {
             Q_ASSERT_X(false, Q_FUNC_INFO, "Not implemented");
             return false;
         }
     }
     return false;
 }
isIgnorableInDeepEqual()
bool QAbstractXmlNodeModel::isIgnorableInDeepEqual (const QXmlNodeModelIndex & n) inline static private
Definition at line 67 of file qabstractxmlnodemodel.cpp.
Referenced by isDeepEqual().
 {
     Q_ASSERT(!n.isNull());
     const QXmlNodeModelIndex::NodeKind nk = n.kind();
     return nk == QXmlNodeModelIndex::ProcessingInstruction ||
            nk == QXmlNodeModelIndex::Comment;
 }
iterate()
QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< QXmlNodeModelIndex > > QAbstractXmlNodeModel::iterate (const QXmlNodeModelIndex & ni, QXmlNodeModelIndex::Axis axis) const virtual
Performs navigation, starting from ni, by returning an QAbstractXmlForwardIterator that returns nodes the axis emanating from ni.
Warning
This function is not part of the public interface.
The implementation returns the nodes on the axis, without duplicates and in axis order. This means that if axis is a reverse axis, which is the case for the parent, ancestor, ancestor-or-self, preceding, and preceding-sibling, the nodes are delivered in reverse document order. Otherwise the nodes are delivered in document order.
The implementor guarantees that the nodes delivered for the axes are consistent with the XPath Data Model. This just implies common sense, e.g., The child axis for a comment node can't contain any children; a document node can't be a child of an element, etc. Attributes aren't considered children of an element, but are only available on AxisAttribute.
The value past in axis is not guaranteed based on what is used in a query. QtXmlPatterns may call this function arbitrarily with any value for axis. This is because QtXmlPatterns may rewrite queries to be more efficient, using axes in different ways from the original query.
QAbstractXmlNodeModel::Axis has a good overview of the axes and what they select.
The caller guarantees that ni is not null and that it belongs to this QAbstractXmlNodeModel instance.
Implementing iterate() can involve significant work, since it requires different iterators for all the axes used. In the worst case, it could require writing as many QAbstractXmlForwardIterator subclasses as there are axes, but the number can often be reduced with clever use of lists and template classes. It is better to use or subclass QSimpleXmlNodeModel, which makes it easier to write the node navigation code without loss of efficiency or flexibility.
See also
QSimpleXmlNodeModel
QXmlNodeModelIndex::Axis
{http://www.w3.org/TR/xquery/#axes}{XQuery 1.0: An XML Query Language, 3.2.1.1 Axes}
{http://www.w3.org/TR/xpath-datamodel/}{W3CXQuery 1.0 and XPath 2.0 Data Model (XDM)}
Reimplemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Definition at line 616 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdInstanceReader::hasChildElement(), QPatternist::XsdInstanceReader::hasChildText(), QPatternist::XsdValidatedXmlNodeModel::iterate(), and QPatternist::XsdInstanceReader::text().
 {
     /* Returns iterators that track state and calls nextFromSimpleAxis()
      * iteratively. Typically, when sub-classing QSimpleXmlNodeModel,
      * you don't reimplement this function, but instead implement
      * nextFromSimpleAxis(). */
     switch(axis)
     {
         case QXmlNodeModelIndex::AxisSelf:
             return makeSingletonIterator(ni);
         case QXmlNodeModelIndex::AxisParent:
         {
             if(kind(ni) == QXmlNodeModelIndex::Document)
                 return makeEmptyIterator<QXmlNodeModelIndex>();
             else
                 return makeSingletonIterator(nextFromSimpleAxis(Parent, ni));
         }
         case QXmlNodeModelIndex::AxisNamespace:
             return makeEmptyIterator<QXmlNodeModelIndex>();
         case QXmlNodeModelIndex::AxisAncestor:
         {
             QList<QXmlNodeModelIndex> ancestors;
             QXmlNodeModelIndex ancestor = nextFromSimpleAxis(Parent, ni);
             while(!ancestor.isNull())
             {
                 ancestors.append(ancestor);
                 ancestor = nextFromSimpleAxis(Parent, ancestor);
             }
             return makeListIterator(ancestors);
         }
         case QXmlNodeModelIndex::AxisAncestorOrSelf:
         {
             QList<QXmlNodeModelIndex> ancestors;
             ancestors.append(ni);
             QXmlNodeModelIndex ancestor = nextFromSimpleAxis(Parent, ni);
             while(!ancestor.isNull())
             {
                 ancestors.append(ancestor);
                 ancestor = nextFromSimpleAxis(Parent, ancestor);
             }
             return makeListIterator(ancestors);
         }
         case QXmlNodeModelIndex::AxisPrecedingSibling:
         {
             QList<QXmlNodeModelIndex> preceding;
             QXmlNodeModelIndex sibling = nextFromSimpleAxis(PreviousSibling, ni);
             while(!sibling.isNull())
             {
                 preceding.append(sibling);
                 sibling = nextFromSimpleAxis(PreviousSibling, sibling);
             }
             return makeListIterator(preceding);
         }
         case QXmlNodeModelIndex::AxisFollowingSibling:
         {
             QList<QXmlNodeModelIndex> preceding;
             QXmlNodeModelIndex sibling = nextFromSimpleAxis(NextSibling, ni);
             while(!sibling.isNull())
             {
                 preceding.append(sibling);
                 sibling = nextFromSimpleAxis(NextSibling, sibling);
             }
             return makeListIterator(preceding);
         }
         case QXmlNodeModelIndex::AxisChildOrTop:
         {
             if(nextFromSimpleAxis(Parent, ni).isNull())
             {
                 switch(kind(ni))
                 {
                     case QXmlNodeModelIndex::Comment:
                     /* Fallthrough. */
                     case QXmlNodeModelIndex::ProcessingInstruction:
                     /* Fallthrough. */
                     case QXmlNodeModelIndex::Element:
                     /* Fallthrough. */
                     case QXmlNodeModelIndex::Text:
                         return makeSingletonIterator(ni);
                     case QXmlNodeModelIndex::Attribute:
                     /* Fallthrough. */
                     case QXmlNodeModelIndex::Document:
                     /* Fallthrough. */
                     case QXmlNodeModelIndex::Namespace:
                         /* Do nothing. */;
                 }
             }
             /* Else, fallthrough to AxisChild. */
         }
         case QXmlNodeModelIndex::AxisChild:
         {
             QList<QXmlNodeModelIndex> children;
             QXmlNodeModelIndex child = nextFromSimpleAxis(FirstChild, ni);
             while(!child.isNull())
             {
                 children.append(child);
                 child = nextFromSimpleAxis(NextSibling, child);
             }
             return makeListIterator(children);
         }
         case QXmlNodeModelIndex::AxisDescendant:
         {
             return makeSequenceMappingIterator<QXmlNodeModelIndex>(this,
                                                                    ni.iterate(QXmlNodeModelIndex::AxisChild),
                                                                    DynamicContext::Ptr());
         }
         case QXmlNodeModelIndex::AxisAttributeOrTop:
         {
             if(kind(ni) == QXmlNodeModelIndex::Attribute && nextFromSimpleAxis(Parent, ni).isNull())
                 return makeSingletonIterator(ni);
             /* Else, fallthrough to AxisAttribute. */
         }
         case QXmlNodeModelIndex::AxisAttribute:
             return makeVectorIterator(attributes(ni));
         case QXmlNodeModelIndex::AxisDescendantOrSelf:
             return mergeIterators(ni, iterate(ni, QXmlNodeModelIndex::AxisDescendant));
         case QXmlNodeModelIndex::AxisFollowing:
         /* Fallthrough. */
         case QXmlNodeModelIndex::AxisPreceding:
         {
             /* We walk up along the ancestors, and for each parent, we grab its preceding/following
              * siblings, and evaluate the descendant axis. The descendant axes gets added
              * to a list and we then merge those iterators. */
             QVector<QXmlNodeModelIndexIteratorPointer> descendantIterators;
             QXmlNodeModelIndex current(ni);
             while(!current.isNull())
             {
                 QXmlNodeModelIndex candidate(nextFromSimpleAxis(axis == QXmlNodeModelIndex::AxisPreceding ? PreviousSibling : NextSibling, current));
                 if(candidate.isNull())
                 {
                     /* current is an ancestor. We don't want it, so next iteration we
                      * will grab its preceding sibling. */
                     current = nextFromSimpleAxis(Parent, current);
                 }
                 else
                 {
                     current = candidate;
                     descendantIterators.append(iterate(current, QXmlNodeModelIndex::AxisDescendantOrSelf)->toReversed());
                 }
             }
             return makeSequenceMappingIterator<QXmlNodeModelIndex>(&mergeIterator,
                                                                    IteratorVector::Ptr(new IteratorVector(descendantIterators)),
                                                                    DynamicContext::Ptr());
         }
     }
     Q_ASSERT_X(false, Q_FUNC_INFO, "Unknown axis, internal error.");
     return makeEmptyIterator<QXmlNodeModelIndex>();
 }
kind()
QXmlNodeModelIndex::NodeKind QAbstractXmlNodeModel::kind (const QXmlNodeModelIndex & ni) const pure virtual
Returns a value indicating the kind of node identified by ni.
The caller guarantees that ni is not null and that it identifies a node in this node model. This function maps to the dm:node-kind() accessor.
See also
{http://www.w3.org/TR/xpath-datamodel/#dm-node-kind}{XQuery 1.0 and XPath 2.0 Data Model (XDM), 5.10 node-kind Accessor}
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by iterate(), QPatternist::XsdValidatedXmlNodeModel::kind(), namespaceForPrefix(), and QSimpleXmlNodeModel::stringValue().
mapToSequence()
QAbstractXmlForwardIterator< QXmlNodeModelIndex >::Ptr QAbstractXmlNodeModel::mapToSequence (const QXmlNodeModelIndex & ni, const QExplicitlySharedDataPointer< QPatternist::DynamicContext > &) const inline private
Definition at line 546 of file qabstractxmlnodemodel.cpp.
 {
     Q_ASSERT(!ni.isNull());
     /* Since we pass in this here, mapToSequence is used recursively. */
     return mergeIterators(ni, makeSequenceMappingIterator<QXmlNodeModelIndex>(this,
                                                                               ni.iterate(QXmlNodeModelIndex::AxisChild),
                                                                               DynamicContext::Ptr()));
 }
name()
QXmlName QAbstractXmlNodeModel::name (const QXmlNodeModelIndex & ni) const pure virtual
Returns the name of ni.
The caller guarantees that ni is not null and that it belongs to this QAbstractXmlNodeModel.
If a node does not have a name, e.g., comment nodes, a null QXmlName is returned. QXmlNames must be created with the instance of QXmlQuery that is being used for evaluating queries using this QAbstractXmlNodeModel.
This function maps to the dm:node-name() accessor.
If ni is a processing instruction, a QXmlName is returned with the local name as the target name and the namespace URI and prefix both empty.
See also
{http://www.w3.org/TR/xpath-datamodel/#dm-node-name}{XQuery 1.0 and XPath 2.0 Data Model (XDM), 5.11 node-name Accessor}
QXmlName
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::name().
namespaceBindings()
QVector< QXmlName > QAbstractXmlNodeModel::namespaceBindings (const QXmlNodeModelIndex & n) const pure virtual
Returns the in-scope namespaces of n.
The caller guarantees that n is not null and that it belongs to this QAbstractXmlNodeModel.
This function corresponds to the dm:namespace-nodes accessor.
The returned vector of namespace declarations includes namespaces of the ancestors of n.
The caller guarantees that n is an Element that belongs to this QAbstractXmlNodeModel.
Implemented in QPatternist::AccelTree, QPatternist::XsdValidatedXmlNodeModel, and QSimpleXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::namespaceBindings(), namespaceForPrefix(), and sendNamespaces().
namespaceForPrefix()
QXmlName::NamespaceCode QAbstractXmlNodeModel::namespaceForPrefix (const QXmlNodeModelIndex & ni, const QXmlName::PrefixCode prefix) const virtual
Returns the namespace URI on ni that corresponds to prefix.
Warning
This function is not part of the public interface.
If prefix is StandardPrefixes::empty, the namespace URI for the default namespace is returned.
The default implementation use namespaceBindings(), in a straight forward manner.
If no namespace exists for prefix, NamespaceResolver::NoBinding is returned.
The caller guarantees to only call this function for element nodes.
Reimplemented in QPatternist::XsdValidatedXmlNodeModel.
Definition at line 1034 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdValidatedXmlNodeModel::namespaceForPrefix().
 {
     Q_ASSERT(kind(ni) == QXmlNodeModelIndex::Element);
     const QVector<QXmlName> nbs(namespaceBindings(ni));
     const int len = nbs.size();
     for(int i = 0; i < len; ++i)
     {
         if(nbs.at(i).prefix() == prefix)
             return nbs.at(i).namespaceURI();
     }
     return NamespaceResolver::NoBinding;
 }
nextFromSimpleAxis()
QXmlNodeModelIndex QAbstractXmlNodeModel::nextFromSimpleAxis (SimpleAxis axis, const QXmlNodeModelIndex & origin) const protected pure virtual
When QtXmlPatterns evaluate path expressions, it emulate them through a combination of calls with QSimpleXmlNodeModel::SimpleAxis values.
Therefore, the implementation of this function must return the node, if any, that appears on the axis emanating from the origin.
If no such node is available, a default constructed QXmlNodeModelIndex is returned.
QSimpleXmlNodeModel eliminates the need to handle redundant corner cases by guaranteeing that it will never ask for:
Children or siblings for attributes.
Children for comments, processing instructions, and text nodes.
Siblings or parents for document nodes.
A typical implementation performs a switch on the value of axis:
QXmlNodeModelIndex MyTreeModel::nextFromSimpleAxis(SimpleAxis axis, const QXmlNodeModelIndex &origin) const
{
  // Convert the QXmlNodeModelIndex to a value that is specific to what we represent.
  const MyValue value = toMyValue(ni);
  switch(axis)
  {
      case Parent:
          return toNodeIndex(value.parent());
      case FirstChild:
      case PreviousSibling:
      case NextSibling:
          // and so on
  }
}
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by iterate(), and QPatternist::XsdValidatedXmlNodeModel::nextFromSimpleAxis().
nodesByIdref()
QVector< QXmlNodeModelIndex > QAbstractXmlNodeModel::nodesByIdref (const QXmlName & idref) const pure virtual
Returns the elements and/or attributes that have an IDREF value equal to idref.
XQuery's idref() function calls this function.
The implementor guarantees that the nodes identified by the returned indexes are elements or attributes.
It is not sufficient for an attribute or element to merely be called idref. It must also be of type IDREF. Elements must be typed as xs:IDREF or xs:IDREFS, or, in the case of attributes, as IDREF or IDREFS in the schema.
In idref, the namespace URI and the prefix are undefined, and the local name is the ID that should be looked up.
See also
{http://www.w3.org/TR/xpath-functions/#func-idref}{XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.3 fn:idref}
Implemented in QPatternist::AccelTree, QPatternist::XsdValidatedXmlNodeModel, and QSimpleXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::nodesByIdref().
root()
QXmlNodeModelIndex QAbstractXmlNodeModel::root (const QXmlNodeModelIndex & n) const pure virtual
Returns the root node of the tree that contains the node whose index is n.
The caller guarantees that n is not null and that it identifies a node in this node model.
If n identifies a node that is a direct child of the root, parent() would return the same QXmlNodeModelIndex returned by this function.
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::root(), and QXmlNodeModelIndex::root().
sendNamespaces()
void QAbstractXmlNodeModel::sendNamespaces (const QXmlNodeModelIndex & n, QAbstractXmlReceiver *const receiver) const virtual
Sends the namespaces declared on n to receiver.
Warning
This function is not part of the public interface.
As a consequence, no namespaces are sent unless this node is an element and has namespaces declared.
The caller guarantees that n is not null and that it belongs to this QAbstractXmlNodeModel instance.
Note that it is not the namespaces that are in scope on n, but only the namespaces that are specifically declared on n.
receiver is the receiver that this node is supposed to send its namespaces to. This is guaranteed by the caller to be a valid pointer. n is the index of the node whose namespaces are to be sent.
Definition at line 920 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdValidatedXmlNodeModel::sendNamespaces().
 {
     Q_ASSERT(receiver);
     const QVector<QXmlName> nss(namespaceBindings(n));
     /* This is by far the most common case. */
     if(nss.isEmpty())
         return;
     const int len = nss.size();
     for(int i = 0; i < len; ++i)
         receiver->namespaceBinding(nss.at(i));
 }
sequencedTypedValue()
QPatternist::ItemIteratorPtr QAbstractXmlNodeModel::sequencedTypedValue (const QXmlNodeModelIndex & ni) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Definition at line 996 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdValidatedXmlNodeModel::sequencedTypedValue().
 {
     const QVariant &candidate = typedValue(ni);
     if(candidate.isNull())
         return QPatternist::CommonValues::emptyIterator;
     else
         return makeSingletonIterator(AtomicValue::toXDM(candidate));
 }
sourceLocation()
QSourceLocation QAbstractXmlNodeModel::sourceLocation (const QXmlNodeModelIndex & index) const
Returns the source location for the object with the given index or a default constructed QSourceLocation in case no location information is available.
Since
4.6
Definition at line 1742 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::PullBridge::sourceLocation().
 {
     // TODO: make this method virtual in Qt5 to allow source location support in custom models
     if (d_ptr)
         return d_ptr->sourceLocation(index);
     else
         return QSourceLocation();
 }
stringValue()
QString QAbstractXmlNodeModel::stringValue (const QXmlNodeModelIndex & n) const pure virtual
Returns the string value for node n.
The caller guarantees that n is not null and that it belong to this QAbstractXmlNodeModel instance.
This function maps to the dm:string-value() accessor, which the specification completely specifies. Here's a summary:
For processing instructions, the string value is the data section(excluding any whitespace appearing between the name and the data).
For text nodes, the string value equals the text node.
For comments, the content of the comment
For elements, the concatenation of all text nodes that are descendants. Note, this is not only the children, but the childrens' childrens' text nodes, and so forth.
For document nodes, the concatenation of all text nodes in the document.
See also
{http://www.w3.org/TR/xpath-datamodel/#dm-string-value}{XQuery 1.0 and XPath 2.0 Data Model (XDM), 5.13 string-value Accessor}
Implemented in QPatternist::AccelTree, QPatternist::XsdValidatedXmlNodeModel, and QSimpleXmlNodeModel.
Referenced by QPatternist::XsdValidatedXmlNodeModel::stringValue().
type()
QPatternist::ItemTypePtr QAbstractXmlNodeModel::type (const QXmlNodeModelIndex & ni) const virtual
Warning
This function is not part of the public interface.
Reimplemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Definition at line 1008 of file qabstractxmlnodemodel.cpp.
Referenced by QPatternist::XsdValidatedXmlNodeModel::type().
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "This function is internal and must not be called.");
     return QPatternist::ItemTypePtr();
 }
typedValue()
QVariant QAbstractXmlNodeModel::typedValue (const QXmlNodeModelIndex & node) const pure virtual
Returns the typed value for node node.
The typed value is an atomic value, which an element or attribute contains.
The caller guarantees that node is either an element or an attribute. The implementor guarantees that the returned QVariant has a value which is supported in XQuery. It cannot be an arbitrary QVariant value. The implementor also guarantees that stringValue() returns a lexical representation of typedValue()(this is guaranteed by QSimpleXmlNodeModel::stringValue()).
If the return QVariant is a default constructed variant, it signals that node has no typed value.
Implemented in QPatternist::AccelTree, and QPatternist::XsdValidatedXmlNodeModel.
Referenced by sequencedTypedValue(), QSimpleXmlNodeModel::stringValue(), and QPatternist::XsdValidatedXmlNodeModel::typedValue().
Friends and Related Functions
QPatternist::ItemMappingIterator< QXmlNodeModelIndex, QXmlNodeModelIndex, const QAbstractXmlNodeModel *, QExplicitlySharedDataPointer< QPatternist::DynamicContext > >
friend class QPatternist::ItemMappingIterator< QXmlNodeModelIndex, QXmlNodeModelIndex, const QAbstractXmlNodeModel *, QExplicitlySharedDataPointer< QPatternist::DynamicContext > > friend
Definition at line 354 of file qabstractxmlnodemodel.h.
QPatternist::SequenceMappingIterator< QXmlNodeModelIndex, QXmlNodeModelIndex, const QAbstractXmlNodeModel *>
friend class QPatternist::SequenceMappingIterator< QXmlNodeModelIndex, QXmlNodeModelIndex, const QAbstractXmlNodeModel * > friend
Definition at line 355 of file qabstractxmlnodemodel.h.
QPatternist::XsdValidatedXmlNodeModel
friend class QPatternist::XsdValidatedXmlNodeModel friend
Definition at line 356 of file qabstractxmlnodemodel.h.
Properties
d_ptr
QScopedPointer<QAbstractXmlNodeModelPrivate> QAbstractXmlNodeModel::d_ptr protected
Definition at line 352 of file qabstractxmlnodemodel.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qabstractxmlnodemodel.h
/src/xmlpatterns/api/qabstractxmlnodemodel.cpp