Qt 4.8: QPlainTextDocumentLayout Class Reference
QPlainTextDocumentLayout Class Reference
The QPlainTextDocumentLayout class implements a plain text layout for QTextDocument.
#include <qplaintextedit.h>
Public Functions
QRectF blockBoundingRect (const QTextBlock &block) const
Reimplemented Function
int cursorWidth () const
QSizeF documentSize () const
Reimplemented Function
void draw (QPainter *, const PaintContext &)
Reimplemented Function
void ensureBlockLayout (const QTextBlock &block) const
Ensures that block has a valid layout.
QRectF frameBoundingRect (QTextFrame *) const
Reimplemented Function
int hitTest (const QPointF &, Qt::HitTestAccuracy) const
Reimplemented Function
int pageCount () const
Reimplemented Function
QPlainTextDocumentLayout (QTextDocument *document)
Constructs a plain text document layout for the text document.
void requestUpdate ()
Requests a complete update on all views.
void setCursorWidth (int width)
~QPlainTextDocumentLayout ()
Destructs a plain text document layout.
Public Functions inherited from QAbstractTextDocumentLayout
QString anchorAt (const QPointF &pos) const
Returns the reference of the anchor the given position, or an empty string if no anchor exists at that point.
QTextDocument * document () const
Returns the text document that this layout is operating on.
QTextObjectInterface * handlerForObject (int objectType) const
Returns a handler for objects of the given objectType.
QPaintDevice * paintDevice () const
Returns the paint device used to render the document's layout.
QAbstractTextDocumentLayout (QTextDocument *doc)
Creates a new text document layout for the given document.
void registerHandler (int objectType, QObject *component)
Registers the given component as a handler for items of the given objectType.
void setPaintDevice (QPaintDevice *device)
Sets the paint device used for rendering the document's layout to the given device.
~QAbstractTextDocumentLayout ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void documentChanged (int from, int, int charsAdded)
Reimplemented Function
Protected Functions inherited from QAbstractTextDocumentLayout
virtual void drawInlineObject (QPainter *painter, const QRectF &rect, QTextInlineObject object, int posInDocument, const QTextFormat &format)
This function is called to draw the inline object, object, with the given painter within the rectangle specified by rect using the specified text format.
QTextCharFormat format (int pos)
Returns the character format that is applicable at the given position.
int formatIndex (int pos)
Returns the index of the format at position pos.
virtual void positionInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat &format)
Lays out the inline object item using the given text format.
QAbstractTextDocumentLayout (QAbstractTextDocumentLayoutPrivate &, QTextDocument *)
virtual void resizeInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat &format)
Sets the size of the inline object item corresponding to the text format.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
qreal blockWidth (const QTextBlock &block)
void layoutBlock (const QTextBlock &block)
QPlainTextDocumentLayoutPrivate * priv () const
void setTextWidth (qreal newWidth)
qreal textWidth () const
Properties
int cursorWidth
This property specifies the width of the cursor in pixels.
Friends
class QPlainTextEdit
class QPlainTextEditPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractTextDocumentLayout
void documentSizeChanged (const QSizeF &newSize)
This signal is emitted when the size of the document layout changes to newSize.
void pageCountChanged (int newPages)
This signal is emitted when the number of pages in the layout changes; newPages is the updated page count.
void update (const QRectF &=QRectF(0., 0., 1000000000., 1000000000.))
This signal is emitted when the rectangle rect has been updated.
void updateBlock (const QTextBlock &block)
This signal is emitted when the specified block has been updated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPlainTextDocumentLayout class implements a plain text layout for QTextDocument.
Since
4.4
A QPlainTextDocumentLayout is required for text documents that can be display or edited in a QPlainTextEdit. See QTextDocument::setDocumentLayout().
QPlainTextDocumentLayout uses the QAbstractTextDocumentLayout API that QTextDocument requires, but redefines it partially in order to support plain text better. For instances, it does not operate on vertical pixels, but on paragraphs (called blocks) instead. The height of a document is identical to the number of paragraphs it contains. The layout also doesn't support tables or nested frames, or any sort of advanced text layout that goes beyond a list of paragraphs with syntax highlighting.
Definition at line 280 of file qplaintextedit.h.
Constructors and Destructors
QPlainTextDocumentLayout()
QPlainTextDocumentLayout::QPlainTextDocumentLayout (QTextDocument * document)
Constructs a plain text document layout for the text document.
Definition at line 142 of file qplaintextedit.cpp.
     :QAbstractTextDocumentLayout(* new QPlainTextDocumentLayoutPrivate, document) {
 }
~QPlainTextDocumentLayout()
QPlainTextDocumentLayout::~QPlainTextDocumentLayout ()
Destructs a plain text document layout.
Definition at line 148 of file qplaintextedit.cpp.
 {}
Functions
blockBoundingRect()
QRectF QPlainTextDocumentLayout::blockBoundingRect (const QTextBlock & block) const virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 198 of file qplaintextedit.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextEditControl::blockBoundingRect(), QPlainTextEdit::blockBoundingRect(), documentChanged(), QPlainTextEditControl::hitTest(), and QPlainTextEditPrivate::verticalOffset().
 {
     if (!block.isValid()) { return QRectF(); }
     QTextLayout *tl = block.layout();
     if (!tl->lineCount())
         const_cast<QPlainTextDocumentLayout*>(this)->layoutBlock(block);
     QRectF br;
     if (block.isVisible()) {
         br = QRectF(QPointF(0, 0), tl->boundingRect().bottomRight());
         if (tl->lineCount() == 1)
             br.setWidth(qMax(br.width(), tl->lineAt(0).naturalTextWidth()));
         qreal margin = document()->documentMargin();
         br.adjust(0, 0, margin, 0);
         if (!block.next().isValid())
             br.adjust(0, 0, 0, margin);
     }
     return br;
 }
blockWidth()
qreal QPlainTextDocumentLayout::blockWidth (const QTextBlock & block) private
Definition at line 429 of file qplaintextedit.cpp.
Referenced by documentChanged(), and layoutBlock().
 {
     QTextLayout *layout = block.layout();
     if (!layout->lineCount())
         return 0; // only for layouted blocks
     qreal blockWidth = 0;
     for (int i = 0; i < layout->lineCount(); ++i) {
         QTextLine line = layout->lineAt(i);
         blockWidth = qMax(line.naturalTextWidth() + 8, blockWidth);
     }
     return blockWidth;
 }
cursorWidth()
int QPlainTextDocumentLayout::cursorWidth () const
Referenced by setCursorWidth().
documentChanged()
void QPlainTextDocumentLayout::documentChanged (int from, int , int charsAdded) protected virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 295 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextDocumentLayout);
     QTextDocument *doc = document();
     int newBlockCount = doc->blockCount();
     QTextBlock changeStartBlock = doc->findBlock(from);
     QTextBlock changeEndBlock = doc->findBlock(qMax(0, from + charsAdded - 1));
     if (changeStartBlock == changeEndBlock && newBlockCount == d->blockCount) {
         QTextBlock block = changeStartBlock;
         int blockLineCount = block.layout()->lineCount();
         if (block.isValid() && blockLineCount) {
             QRectF oldBr = blockBoundingRect(block);
             layoutBlock(block);
             QRectF newBr = blockBoundingRect(block);
             if (newBr.height() == oldBr.height()) {
                 if (!d->blockUpdate)
                     emit updateBlock(block);
                 return;
             }
         }
     } else {
         QTextBlock block = changeStartBlock;
         do {
             block.clearLayout();
             if (block == changeEndBlock)
                 break;
             block = block.next();
         } while(block.isValid());
     }
     if (newBlockCount != d->blockCount) {
         int changeEnd = changeEndBlock.blockNumber();
         int blockDiff = newBlockCount - d->blockCount;
         int oldChangeEnd = changeEnd - blockDiff;
         if (d->maximumWidthBlockNumber > oldChangeEnd)
             d->maximumWidthBlockNumber += blockDiff;
         d->blockCount = newBlockCount;
         if (d->blockCount == 1)
             d->maximumWidth = blockWidth(doc->firstBlock());
         if (!d->blockDocumentSizeChanged)
             emit documentSizeChanged(documentSize());
         if (blockDiff == 1 && changeEnd == newBlockCount -1 ) {
             if (!d->blockUpdate) {
                 QTextBlock b = changeStartBlock;
                 for(;;) {
                     emit updateBlock(b);
                     if (b == changeEndBlock)
                         break;
                     b = b.next();
                 }
             }
             return;
         }
     }
     if (!d->blockUpdate)
     emit update(QRectF(0., -doc->documentMargin(), 1000000000., 1000000000.)); // optimization potential
 }
documentSize()
QSizeF QPlainTextDocumentLayout::documentSize () const virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 180 of file qplaintextedit.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), documentChanged(), and layoutBlock().
 {
     Q_D(const QPlainTextDocumentLayout);
     return QSizeF(d->maximumWidth, document()->lineCount());
 }
draw()
void QPlainTextDocumentLayout::draw (QPainter * , const PaintContext &) virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 154 of file qplaintextedit.cpp.
 {
 }
ensureBlockLayout()
void QPlainTextDocumentLayout::ensureBlockLayout (const QTextBlock & block) const
Ensures that block has a valid layout.
Definition at line 221 of file qplaintextedit.cpp.
 {
     if (!block.isValid())
         return;
     QTextLayout *tl = block.layout();
     if (!tl->lineCount())
         const_cast<QPlainTextDocumentLayout*>(this)->layoutBlock(block);
 }
frameBoundingRect()
QRectF QPlainTextDocumentLayout::frameBoundingRect (QTextFrame *) const virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 189 of file qplaintextedit.cpp.
 {
     Q_D(const QPlainTextDocumentLayout);
     return QRectF(0, 0, qMax(d->width, d->maximumWidth), qreal(INT_MAX));
 }
hitTest()
int QPlainTextDocumentLayout::hitTest (const QPointF & , Qt::HitTestAccuracy) const virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 161 of file qplaintextedit.cpp.
 {
 //     this function is used from
 //     QAbstractTextDocumentLayout::anchorAt(), but is not
 //     implementable in a plain text document layout, because the
 //     layout depends on the top block and top line which depends on
 //     the view
     return -1;
 }
layoutBlock()
void QPlainTextDocumentLayout::layoutBlock (const QTextBlock & block) private
Definition at line 362 of file qplaintextedit.cpp.
Referenced by documentChanged().
 {
     Q_D(QPlainTextDocumentLayout);
     QTextDocument *doc = document();
     qreal margin = doc->documentMargin();
     qreal blockMaximumWidth = 0;
     qreal height = 0;
     QTextLayout *tl = block.layout();
     QTextOption option = doc->defaultTextOption();
     tl->setTextOption(option);
     int extraMargin = 0;
     if (option.flags() & QTextOption::AddSpaceForLineAndParagraphSeparators) {
         QFontMetrics fm(block.charFormat().font());
         extraMargin += fm.width(QChar(0x21B5));
     }
     tl->beginLayout();
     qreal availableWidth = d->width;
     if (availableWidth <= 0) {
         availableWidth = qreal(INT_MAX); // similar to text edit with pageSize.width == 0
     }
     availableWidth -= 2*margin + extraMargin;
     while (1) {
         QTextLine line = tl->createLine();
         if (!line.isValid())
             break;
         line.setLeadingIncluded(true);
         line.setLineWidth(availableWidth);
         line.setPosition(QPointF(margin, height));
         height += line.height();
         blockMaximumWidth = qMax(blockMaximumWidth, line.naturalTextWidth() + 2*margin);
     }
     tl->endLayout();
     int previousLineCount = doc->lineCount();
     const_cast<QTextBlock&>(block).setLineCount(block.isVisible() ? tl->lineCount() : 0);
     int lineCount = doc->lineCount();
     bool emitDocumentSizeChanged = previousLineCount != lineCount;
     if (blockMaximumWidth > d->maximumWidth) {
         // new longest line
         d->maximumWidth = blockMaximumWidth;
         d->maximumWidthBlockNumber = block.blockNumber();
         emitDocumentSizeChanged = true;
     } else if (block.blockNumber() == d->maximumWidthBlockNumber && blockMaximumWidth < d->maximumWidth) {
         // longest line shrinking
         QTextBlock b = doc->firstBlock();
         d->maximumWidth = 0;
         QTextBlock maximumBlock;
         while (b.isValid()) {
             qreal blockMaximumWidth = blockWidth(b);
             if (blockMaximumWidth > d->maximumWidth) {
                 d->maximumWidth = blockMaximumWidth;
                 maximumBlock = b;
             }
             b = b.next();
         }
         if (maximumBlock.isValid()) {
             d->maximumWidthBlockNumber = maximumBlock.blockNumber();
             emitDocumentSizeChanged = true;
         }
     }
     if (emitDocumentSizeChanged && !d->blockDocumentSizeChanged)
         emit documentSizeChanged(documentSize());
 }
pageCount()
int QPlainTextDocumentLayout::pageCount () const virtual
Reimplemented Function
Implements QAbstractTextDocumentLayout.
Definition at line 174 of file qplaintextedit.cpp.
 { return 1; }
priv()
QPlainTextDocumentLayoutPrivate * QPlainTextDocumentLayout::priv () const private
Definition at line 250 of file qplaintextedit.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextEditPrivate::append(), QPlainTextEditPrivate::relayoutDocument(), and QPlainTextEdit::setDocument().
 {
     Q_D(const QPlainTextDocumentLayout);
     return const_cast<QPlainTextDocumentLayoutPrivate*>(d);
 }
requestUpdate()
void QPlainTextDocumentLayout::requestUpdate ()
Requests a complete update on all views.
Definition at line 261 of file qplaintextedit.cpp.
 {
     emit update(QRectF(0., -document()->documentMargin(), 1000000000., 1000000000.));
 }
setCursorWidth()
void QPlainTextDocumentLayout::setCursorWidth (int width)
Definition at line 238 of file qplaintextedit.cpp.
 {
     Q_D(QPlainTextDocumentLayout);
     d->cursorWidth = width;
 }
setTextWidth()
void QPlainTextDocumentLayout::setTextWidth (qreal newWidth) private
Definition at line 267 of file qplaintextedit.cpp.
Referenced by QPlainTextEditPrivate::relayoutDocument().
 {
     Q_D(QPlainTextDocumentLayout);
     d->width = d->maximumWidth = newWidth;
     d->relayout();
 }
textWidth()
qreal QPlainTextDocumentLayout::textWidth () const private
Definition at line 274 of file qplaintextedit.cpp.
Referenced by QPlainTextEditPrivate::relayoutDocument().
 {
     Q_D(const QPlainTextDocumentLayout);
     return d->width;
 }
Friends and Related Functions
QPlainTextEdit
friend class QPlainTextEdit friend
Definition at line 318 of file qplaintextedit.h.
QPlainTextEditPrivate
friend class QPlainTextEditPrivate friend
Definition at line 319 of file qplaintextedit.h.
Properties
cursorWidth
int QPlainTextDocumentLayout::cursorWidth private
This property specifies the width of the cursor in pixels.
The default value is 1.
Definition at line 284 of file qplaintextedit.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qplaintextedit.h
/src/gui/widgets/qplaintextedit.cpp