Qt 4.8: QXmlDTDHandler Class Reference
QXmlDTDHandler Class Reference abstract
The QXmlDTDHandler class provides an interface to report DTD content of XML data.
#include <qxml.h>
Public Functions
virtual QString errorString () const =0
The reader calls this function to get an error string if any of the handler functions returns false.
virtual bool notationDecl (const QString &name, const QString &publicId, const QString &systemId)=0
The reader calls this function when it has parsed a notation declaration.
virtual bool unparsedEntityDecl (const QString &name, const QString &publicId, const QString &systemId, const QString &notationName)=0
The reader calls this function when it finds an unparsed entity declaration.
virtual ~QXmlDTDHandler ()
Destroys the DTD handler.
Detailed Description
The QXmlDTDHandler class provides an interface to report DTD content of XML data.
Note
This class or function is reentrant.
Attention
Module: QtXml
If an application needs information about notations and unparsed entities, it can implement this interface and register an instance with QXmlReader::setDTDHandler().
Note that this interface includes only those DTD events that the XML recommendation requires processors to report, i.e. notation and unparsed entity declarations using notationDecl() and unparsedEntityDecl() respectively.
See also
QXmlDeclHandler, QXmlContentHandler, QXmlEntityResolver, QXmlErrorHandler, QXmlLexicalHandler, {Introduction to SAX2}
Definition at line 329 of file qxml.h.
Constructors and Destructors
~QXmlDTDHandler()
QXmlDTDHandler::~QXmlDTDHandler () inline virtual
Destroys the DTD handler.
Definition at line 332 of file qxml.h.
 {}
Functions
errorString()
QString QXmlDTDHandler::errorString () const pure virtual
The reader calls this function to get an error string if any of the handler functions returns false.
Implemented in QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseNotationDecl().
notationDecl()
bool QXmlDTDHandler::notationDecl (const QString & name, const QString & publicId, const QString & systemId) pure virtual
The reader calls this function when it has parsed a notation declaration.
The argument name is the notation name, publicId is the notation's public identifier and systemId is the notation's system identifier.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseNotationDecl().
unparsedEntityDecl()
bool QXmlDTDHandler::unparsedEntityDecl (const QString & name, const QString & publicId, const QString & systemId, const QString & notationName) pure virtual
The reader calls this function when it finds an unparsed entity declaration.
The argument name is the unparsed entity's name, publicId is the entity's public identifier, systemId is the entity's system identifier and notationName is the name of the associated notation.
If this function returns false the reader stops parsing and reports an error. The reader uses the function errorString() to get the error message.
Implemented in QDomHandler, and QXmlDefaultHandler.
Referenced by QXmlSimpleReaderPrivate::parseEntityDecl().
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp