Qt 4.8: QPatternist::DayTimeDuration Class Reference
QPatternist::DayTimeDuration Class Reference
Implements the value instance of the xs:dayTimeDuration type.
#include <qdaytimeduration_p.h>
Public Types
typedef QExplicitlySharedDataPointer< DayTimeDuration > Ptr
Public Types inherited from QPatternist::AbstractDuration
typedef QExplicitlySharedDataPointer< AbstractDuration > Ptr
typedef qint64 Value
The amount in milli seconds.
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual DayCountProperty days () const
virtual Item fromValue (const Value val) const
virtual HourProperty hours () const
virtual MinuteProperty minutes () const
virtual MonthProperty months () const
virtual MSecondProperty mseconds () const
virtual SecondProperty seconds () const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
virtual Value value () const
virtual YearProperty years () const
Public Functions inherited from QPatternist::AbstractDuration
bool isPositive () const
bool operator== (const AbstractDuration &other) const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static DayTimeDuration::Ptr fromComponents (const bool isPositive, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds)
static DayTimeDuration::Ptr fromLexical (const QString &string)
static DayTimeDuration::Ptr fromSeconds (const SecondCountProperty secs, const MSecondProperty msecs=0)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
DayTimeDuration (const bool isPositive, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds)
Protected Functions inherited from QPatternist::AbstractDuration
AbstractDuration (const bool isPos)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Properties
const DayCountProperty m_days
const HourProperty m_hours
const MinuteProperty m_minutes
const MSecondProperty m_mseconds
const SecondProperty m_seconds
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDuration
static AtomicValue::Ptr create (const CaptureTable &captTable, const QString &lexical, bool *isPositive, YearProperty *years, MonthProperty *months, DayCountProperty *days, HourProperty *hours, MinuteProperty *minutes, SecondProperty *seconds, MSecondProperty *mseconds)
static QString serializeMSeconds (const MSecondProperty mseconds)
Protected Variables inherited from QPatternist::AbstractDuration
const bool m_isPositive
Detailed Description
Implements the value instance of the xs:dayTimeDuration type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 70 of file qdaytimeduration_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<DayTimeDuration> QPatternist::DayTimeDuration::Ptr
Definition at line 74 of file qdaytimeduration_p.h.
Constructors and Destructors
DayTimeDuration()
DayTimeDuration::DayTimeDuration (const bool isPositive, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds) protected
Definition at line 52 of file qdaytimeduration.cpp.
Referenced by fromComponents(), fromLexical(), and fromSeconds().
                                                               : AbstractDuration(isPositiveP),
                                                                 m_days(daysP),
                                                                 m_hours(hoursP),
                                                                 m_minutes(minutesP),
                                                                 m_seconds(secs),
                                                                 m_mseconds(msecs)
 {
 }
Functions
days()
DayCountProperty DayTimeDuration::days () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 217 of file qdaytimeduration.cpp.
Referenced by fromLexical(), and fromSeconds().
 {
     return m_days;
 }
fromComponents()
DayTimeDuration::Ptr DayTimeDuration::fromComponents (const bool isPositive, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds) static
Definition at line 104 of file qdaytimeduration.cpp.
Referenced by QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom().
 {
     return DayTimeDuration::Ptr(new DayTimeDuration(isPositive,
                                                     days,
                                                     hours,
                                                     minutes,
                                                     seconds,
                                                     mseconds));
 }
fromLexical()
DayTimeDuration::Ptr DayTimeDuration::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 66 of file qdaytimeduration.cpp.
Referenced by QPatternist::StringToDayTimeDurationCaster::castFrom().
 {
     static const CaptureTable captureTable(
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"                         /* Any preceding whitespace. */
                 "(-)?"                          /* Any minus sign. */
                 "P"                             /* Delimiter. */
                 "(?:(\\d+)D)?"                  /* Day part. */
                 "(?:"                           /* Here starts the optional time part. */
                 "(T)"                           /* SchemaTime delimiter. */
                 "(?:(\\d+)H)?"                  /* Hour part. */
                 "(?:(\\d+)M)?"                  /* Minute part. */
                 "(?:(\\d+)(?:\\.(\\d+))?S)?"    /* Seconds & milli seconds. */
                 ")?"                            /* End of optional time part. */
                 "\\s*$"                         /* Any terminating whitespace. */))),
         /*yearP*/       -1,
         /*monthP*/      -1,
         /*dayP*/        2,
         /*tDelimiterP*/ 3,
         /*hourP*/       4,
         /*minutesP*/    5,
         /*secondsP*/    6,
         /*msecondsP*/   7);
     DayCountProperty days = 0;
     HourProperty hours = 0;
     MinuteProperty minutes = 0;
     SecondProperty sec = 0;
     MSecondProperty msec = 0;
     bool isPos;
     const DayTimeDuration::Ptr err(create(captureTable, lexical, &isPos, 0, 0, &days,
                                           &hours, &minutes, &sec, &msec));
     return err ? err : DayTimeDuration::Ptr(new DayTimeDuration(isPos, days, hours, minutes,
                                                                 sec, msec));
 }
fromSeconds()
DayTimeDuration::Ptr DayTimeDuration::fromSeconds (const SecondCountProperty secs, const MSecondProperty msecs = 0) static
Creates a DayTimeDuration that has the value expressed in seconds secs and milli seconds msecs. The signedness of secs communicates whether this DayTimeDuration is positive or negative. msecs must always be positive.
Definition at line 119 of file qdaytimeduration.cpp.
Referenced by QPatternist::AbstractDateTimeMathematician::calculate(), and fromValue().
 {
     Q_ASSERT(msecs >= 0);
     const SecondCountProperty source = qAbs(sourceSecs);
     const bool isPos = sourceSecs >= 0;
     const SecondCountProperty secs = source % 60;
     const MinuteCountProperty mins = (source / 60) % 60;
     const HourCountProperty hours = source / (60 * 60) % 24;
     const DayCountProperty days = source / (60 * 60) / 24;
     return DayTimeDuration::Ptr(new DayTimeDuration(isPos, days, hours, mins, secs, msecs));
 }
fromValue()
Item DayTimeDuration::fromValue (const Value val) const virtual
Creates a DayTimeDuration containing the value val. val is expressed in milli seconds.
If val is zero, is CommonValues::DayTimeDurationZero returned.
Implements QPatternist::AbstractDuration.
Definition at line 194 of file qdaytimeduration.cpp.
 {
     if(val == 0)
         return toItem(CommonValues::DayTimeDurationZero);
     else
         return toItem(fromSeconds(val / 1000, qAbs(val) % 1000));
 }
hours()
HourProperty DayTimeDuration::hours () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 222 of file qdaytimeduration.cpp.
Referenced by fromLexical(), and fromSeconds().
 {
     return m_hours;
 }
minutes()
MinuteProperty DayTimeDuration::minutes () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 227 of file qdaytimeduration.cpp.
Referenced by fromLexical().
 {
     return m_minutes;
 }
months()
MonthProperty DayTimeDuration::months () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 212 of file qdaytimeduration.cpp.
 {
     return 0;
 }
mseconds()
MSecondProperty DayTimeDuration::mseconds () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 237 of file qdaytimeduration.cpp.
 {
     return m_mseconds;
 }
seconds()
SecondProperty DayTimeDuration::seconds () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 232 of file qdaytimeduration.cpp.
 {
     return m_seconds;
 }
stringValue()
QString DayTimeDuration::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 133 of file qdaytimeduration.cpp.
 {
     QString retval;
     if(!m_isPositive)
         retval.append(QLatin1Char('-'));
     retval.append(QLatin1Char('P'));
     if(m_days)
     {
         retval.append(QString::number(m_days));
         retval.append(QLatin1Char('D'));
     }
     if(!m_hours && !m_minutes && !m_seconds && !m_seconds)
     {
         if(!m_days)
             return QLatin1String("PT0S");
         else
             return retval;
     }
     retval.append(QLatin1Char('T'));
     if(m_hours)
     {
         retval.append(QString::number(m_hours));
         retval.append(QLatin1Char('H'));
     }
     if(m_minutes)
     {
         retval.append(QString::number(m_minutes));
         retval.append(QLatin1Char('M'));
     }
     if(m_seconds || m_seconds)
     {
         retval.append(QString::number(m_seconds));
         if(m_mseconds)
             retval.append(serializeMSeconds(m_mseconds));
         retval.append(QLatin1Char('S'));
     }
     else if(!m_days && !m_hours && !m_minutes)
         retval.append(QLatin1String("0S"));
     return retval;
 }
type()
ItemType::Ptr DayTimeDuration::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 202 of file qdaytimeduration.cpp.
 {
     return BuiltinTypes::xsDayTimeDuration;
 }
value()
AbstractDuration::Value DayTimeDuration::value () const virtual
Returns
the value of this xs:dayTimeDuration in milli seconds.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 10.3.2.2 Calculating the value of a xs:dayTimeDuration from the lexical representation
Implements QPatternist::AbstractDuration.
Definition at line 185 of file qdaytimeduration.cpp.
 {
     return ((m_days * 24 * 60 * 60 * 1000) +
             (m_hours * 60 * 60 * 1000) +
             (m_minutes * 60 * 1000) +
             (m_seconds * 1000) +
             m_mseconds) * (m_isPositive ? 1 : -1);
 }
years()
YearProperty DayTimeDuration::years () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 207 of file qdaytimeduration.cpp.
 {
     return 0;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 132 of file qdaytimeduration_p.h.
Properties
m_days
const DayCountProperty QPatternist::DayTimeDuration::m_days private
Definition at line 142 of file qdaytimeduration_p.h.
Referenced by days(), stringValue(), and value().
m_hours
const HourProperty QPatternist::DayTimeDuration::m_hours private
Definition at line 143 of file qdaytimeduration_p.h.
Referenced by hours(), stringValue(), and value().
m_minutes
const MinuteProperty QPatternist::DayTimeDuration::m_minutes private
Definition at line 144 of file qdaytimeduration_p.h.
Referenced by minutes(), stringValue(), and value().
m_mseconds
const MSecondProperty QPatternist::DayTimeDuration::m_mseconds private
Definition at line 146 of file qdaytimeduration_p.h.
Referenced by mseconds(), stringValue(), and value().
m_seconds
const SecondProperty QPatternist::DayTimeDuration::m_seconds private
Definition at line 145 of file qdaytimeduration_p.h.
Referenced by seconds(), stringValue(), and value().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qdaytimeduration_p.h
/src/xmlpatterns/data/qdaytimeduration.cpp