Qt 4.8: QScriptContext Class Reference
QScriptContext Class Reference
The QScriptContext class represents a Qt Script function invocation.
#include <qscriptcontext.h>
Public Types
enum Error {
UnknownError, ReferenceError, SyntaxError, TypeError,
RangeError, URIError
}
This enum specifies types of error.
enum ExecutionState { NormalState, ExceptionState }
This enum specifies the frameution state of the context.
Public Functions
QScriptValue activationObject () const
Returns the activation object of this QScriptContext.
QScriptValue argument (int index) const
Returns the function argument at the given index.
int argumentCount () const
Returns the number of arguments passed to the function in this invocation.
QScriptValue argumentsObject () const
Returns the arguments object of this QScriptContext.
QStringList backtrace () const
Returns a human-readable backtrace of this QScriptContext.
QScriptValue callee () const
Returns the callee.
QScriptEngine * engine () const
Returns the QScriptEngine that this QScriptContext belongs to.
bool isCalledAsConstructor () const
Returns true if the function was called as a constructor (e.g.
QScriptContext * parentContext () const
Returns the parent context of this QScriptContext.
QScriptValue popScope ()
Removes the front object from this context's scope chain, and returns the removed object.
void pushScope (const QScriptValue &object)
Adds the given object to the front of this context's scope chain.
QScriptValue returnValue () const
QScriptValueList scopeChain () const
Returns the scope chain of this QScriptContext.
void setActivationObject (const QScriptValue &activation)
Sets the activation object of this QScriptContext to be the given activation.
void setReturnValue (const QScriptValue &result)
void setThisObject (const QScriptValue &thisObject)
Sets the `this' object associated with this QScriptContext to be thisObject.
ExecutionState state () const
Returns the frameution state of this QScriptContext.
QScriptValue thisObject () const
Returns the `this' object associated with this QScriptContext.
QScriptValue throwError (Error error, const QString &text)
Throws an error with the given text.
QScriptValue throwError (const QString &text)
Throws an error with the given text.
QScriptValue throwValue (const QScriptValue &value)
Throws an exception with the given value.
QString toString () const
Returns a string representation of this context.
~QScriptContext ()
Destroys this QScriptContext.
Private Functions
QScriptContext ()
Properties
QScriptContextPrivate * d_ptr
Detailed Description
The QScriptContext class represents a Qt Script function invocation.
Since
4.3
A QScriptContext provides access to the `this' object and arguments passed to a script function. You typically want to access this information when you're writing a native (C++) function (see QScriptEngine::newFunction()) that will be called from script code. For example, when the script code
foo(20.5, "hello", new Object())
is evaluated, a QScriptContext will be created, and the context will carry the arguments as QScriptValues; in this particular case, the arguments will be one QScriptValue containing the number 20.5, a second QScriptValue containing the string "hello", and a third QScriptValue containing a Qt Script object.
Use argumentCount() to get the number of arguments passed to the function, and argument() to get an argument at a certain index. The argumentsObject() function returns a Qt Script array object containing all the arguments; you can use the QScriptValueIterator to iterate over its elements, or pass the array on as arguments to another script function using QScriptValue::call().
Use thisObject() to get the `this' object associated with the function call, and setThisObject() to set the `this' object. If you are implementing a native "instance method", you typically fetch the thisObject() and access one or more of its properties:
QScriptValue Person_prototype_fullName(QScriptContext *context, QScriptEngine *engine)
{
    QScriptValue self = context->thisObject();
    QString result;
    result += self.property("firstName").toString();
    result += QLatin1String(" ");
    result += self.property("lastName").toString();
    return result;
}
Use isCalledAsConstructor() to determine if the function was called as a constructor (e.g. "new foo()" (as constructor) or just "foo()"). When a function is called as a constructor, the thisObject() contains the newly constructed object that the function is expected to initialize.
Use throwValue() or throwError() to throw an exception.
Use callee() to obtain the QScriptValue that represents the function being called. This can for example be used to call the function recursively.
Use parentContext() to get a pointer to the context that precedes this context in the activation stack. This is mostly useful for debugging purposes (e.g. when constructing some form of backtrace).
The activationObject() function returns the object that is used to hold the local variables associated with this function call. You can replace the activation object by calling setActivationObject(). A typical usage of these functions is when you want script code to be evaluated in the context of the parent context, e.g. to implement an include() function:
QScriptValue myInclude(QScriptContext *ctx, QScriptEngine *eng)
{
    QString fileName = ctx->argument(0).toString();
    QString contents = readTheFile(fileName);
    ctx->setActivationObject(ctx->parentContext()->activationObject());
    ctx->setThisObject(ctx->parentContext()->thisObject());
    return eng->evaluate(contents, fileName);
}
Use backtrace() to get a human-readable backtrace associated with this context. This can be useful for debugging purposes when implementing native functions. The toString() function provides a string representation of the context. (QScriptContextInfo provides more detailed debugging-related information about the QScriptContext.)
Use engine() to obtain a pointer to the QScriptEngine that this context resides in.
See also
QScriptContextInfo, QScriptEngine::newFunction(), QScriptable
Definition at line 39 of file qscriptcontext.h.
Enumerations
Error
enum QScriptContext::Error
This enum specifies types of error.
ReferenceError A reference error.
SyntaxError A syntax error.
TypeError A type error.
RangeError A range error.
URIError A URI error.
UnknownError An unknown error.
Enumerator
UnknownError
ReferenceError
SyntaxError
TypeError
RangeError
URIError
Definition at line 47 of file qscriptcontext.h.
                {
         UnknownError,
         ReferenceError,
         SyntaxError,
         TypeError,
         RangeError,
         URIError
     };
ExecutionState
enum QScriptContext::ExecutionState
This enum specifies the frameution state of the context.
NormalState The context is in a normal state.
ExceptionState The context is in an exceptional state.
Enumerator
NormalState
ExceptionState
Definition at line 42 of file qscriptcontext.h.
{
         NormalState,
         ExceptionState
     };
Constructors and Destructors
~QScriptContext()
QScriptContext::~QScriptContext ()
Destroys this QScriptContext.
Definition at line 243 of file qscriptcontext.cpp.
 {
     //QScriptContext doesn't exist,  pointer to QScriptContext are just pointer to JSC::CallFrame
     Q_ASSERT(false);
 }
QScriptContext()
QScriptContext::QScriptContext () private
Warning
This function is not part of the public interface.
Definition at line 158 of file qscriptcontext.cpp.
 {
     //QScriptContext doesn't exist,  pointer to QScriptContext are just pointer to  JSC::CallFrame
     Q_ASSERT(false);
 }
Functions
activationObject()
QScriptValue QScriptContext::activationObject () const
Returns the activation object of this QScriptContext.
The activation object provides access to the local variables associated with this context.
Note
The activation object might not be available if there is no active QScriptEngineAgent, as it might be optimized.
See also
argument(), argumentsObject()
Definition at line 450 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerBackend::doPendingEvaluate(), QScriptDebuggerCommandExecutor::execute(), QJSDebuggerAgentPrivate::getLocals(), QScriptEngine::importExtension(), popScope(), pushScope(), scopeChain(), and QScriptDeclarativeClass::scopeChainValue().
 {
     JSC::CallFrame *frame = const_cast<JSC::ExecState*>(QScriptEnginePrivate::frameForContext(this));
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     JSC::JSObject *result = 0;
     uint flags = QScriptEnginePrivate::contextFlags(frame);
     if ((flags & QScriptEnginePrivate::NativeContext) && !(flags & QScriptEnginePrivate::HasScopeContext)) {
         //For native functions, lazily create it if needed
         QScript::QScriptActivationObject *scope = new (frame) QScript::QScriptActivationObject(frame);
         frame->setScopeChain(frame->scopeChain()->copy()->push(scope));
         result = scope;
         QScriptEnginePrivate::setContextFlags(frame, flags | QScriptEnginePrivate::HasScopeContext);
     } else {
         // look in scope chain
         JSC::ScopeChainNode *node = frame->scopeChain();
         JSC::ScopeChainIterator it(node);
         for (it = node->begin(); it != node->end(); ++it) {
             if ((*it) && (*it)->isVariableObject()) {
                 result = *it;
                 break;
             }
         }
     }
     if (!result) {
         if (!parentContext())
             return engine()->globalObject();
         qWarning("QScriptContext::activationObject:  could not get activation object for frame");
         return QScriptValue();
         /*JSC::CodeBlock *codeBlock = frame->codeBlock();
         if (!codeBlock) {
             // non-Qt native function
             Q_ASSERT(true); //### this should in theorry not happen
             result = new (frame)QScript::QScriptActivationObject(frame);
         } else {
             // ### this is wrong
             JSC::FunctionBodyNode *body = static_cast<JSC::FunctionBodyNode*>(codeBlock->ownerNode());
             result = new (frame)JSC::JSActivation(frame, body);
         }*/
     }
     if (result && result->inherits(&QScript::QScriptActivationObject::info)
         && (static_cast<QScript::QScriptActivationObject*>(result)->delegate() != 0)) {
         // Return the object that property access is being delegated to
         result = static_cast<QScript::QScriptActivationObject*>(result)->delegate();
     }
     return QScript::scriptEngineFromExec(frame)->scriptValueFromJSCValue(result);
 }
argument()
QScriptValue QScriptContext::argument (int index) const
Returns the function argument at the given index.
If index >= argumentCount(), a QScriptValue of the primitive type Undefined is returned.
See also
argumentCount()
Definition at line 266 of file qscriptcontext.cpp.
Referenced by QScript::__setupPackage__(), QDeclarativeEnginePrivate::atob(), QDeclarativeEnginePrivate::btoa(), QDeclarativeObjectMethodScriptClass::callMethod(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::connect(), QDeclarativeEnginePrivate::consoleLog(), QDeclarativeEnginePrivate::createComponent(), QScriptDBusMessageConstructor::createErrorReply(), QDeclarativeEnginePrivate::createQmlObject(), QScriptDBusMessageConstructor::createReply(), QDeclarativeEnginePrivate::darker(), QDeclarativeEnginePrivate::desktopOpenUrl(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectMethodScriptClass::disconnect(), do_dbus_call(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), QDeclarativeEnginePrivate::hsla(), QDeclarativeInclude::include(), QDeclarativeEnginePrivate::isQtObject(), QDeclarativeEnginePrivate::lighter(), QDeclarativeEnginePrivate::md5(), QDeclarativeWorkerScriptEnginePrivate::onMessage(), QDeclarativeEnginePrivate::point(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlsqldatabase_executeSql_readonly(), qmlsqldatabase_item(), qmlsqldatabase_open_sync(), qmlsqldatabase_transaction_shared(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_onreadystatechange(), qmlxmlhttprequest_open(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), QScriptDebuggerBackendPrivate::qsassert(), QDeclarativeEnginePrivate::rect(), QDeclarativeScriptEngine::resolvedUrl(), QDeclarativeEnginePrivate::rgba(), QDeclarativeWorkerScriptEnginePrivate::sendMessage(), QDeclarativeEnginePrivate::size(), QDeclarativeEnginePrivate::tint(), toString(), QScriptDebuggerBackendPrivate::trace(), QDeclarativeEnginePrivate::vector3d(), and QDeclarativeInclude::worker_include().
 {
     if (index < 0)
         return QScriptValue();
     if (index >= argumentCount())
         return QScriptValue(QScriptValue::UndefinedValue);
     QScriptValue v = argumentsObject().property(index);
     return v;
 }
argumentCount()
int QScriptContext::argumentCount () const
Returns the number of arguments passed to the function in this invocation.
Note that the argument count can be different from the formal number of arguments (the length property of callee()).
See also
argument()
Definition at line 407 of file qscriptcontext.cpp.
Referenced by argument(), QDeclarativeEnginePrivate::atob(), QDeclarativeEnginePrivate::btoa(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::callPrecise(), QDeclarativeObjectMethodScriptClass::connect(), QDeclarativeEnginePrivate::consoleLog(), QDeclarativeEnginePrivate::createComponent(), QScriptDBusMessageConstructor::createErrorReply(), QDeclarativeEnginePrivate::createQmlObject(), QScriptDBusMessageConstructor::createReply(), QDeclarativeEnginePrivate::darker(), QDeclarativeEnginePrivate::desktopOpenUrl(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectMethodScriptClass::disconnect(), do_dbus_call(), QDeclarativeEnginePrivate::fontFamilies(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), QDeclarativeEnginePrivate::hsla(), QDeclarativeInclude::include(), QDeclarativeEnginePrivate::isQtObject(), QDeclarativeEnginePrivate::lighter(), QDeclarativeEnginePrivate::md5(), QDeclarativeWorkerScriptEnginePrivate::onMessage(), QDeclarativeEnginePrivate::point(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlxmlhttprequest_getAllResponseHeaders(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_onreadystatechange(), qmlxmlhttprequest_open(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), QScriptDebuggerBackendPrivate::qsassert(), QDeclarativeEnginePrivate::rect(), QDeclarativeEnginePrivate::rgba(), QDeclarativeWorkerScriptEnginePrivate::sendMessage(), QDeclarativeEnginePrivate::size(), QDeclarativeEnginePrivate::tint(), toString(), QScriptDebuggerBackendPrivate::trace(), QDeclarativeEnginePrivate::vector3d(), and QDeclarativeInclude::worker_include().
 {
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     int argc = frame->argumentCount();
     if (argc != 0)
         --argc; // -1 due to "this"
     return argc;
 }
argumentsObject()
QScriptValue QScriptContext::argumentsObject () const
Returns the arguments object of this QScriptContext.
The arguments object has properties callee (equal to callee()) and length (equal to argumentCount()), and properties 0, 1, ..., argumentCount() - 1 that provide access to the argument values. Initially, property P (0 <= P < argumentCount()) has the same value as argument(P). In the case when P is less than the number of formal parameters of the function, P shares its value with the corresponding property of the activation object (activationObject()). This means that changing this property changes the corresponding property of the activation object and vice versa.
See also
argument(), activationObject()
Definition at line 308 of file qscriptcontext.cpp.
Referenced by argument(), QScript::GlobalObject::getOwnPropertyDescriptor(), and QScript::GlobalObject::getOwnPropertySlot().
 {
     JSC::CallFrame *frame = const_cast<JSC::ExecState*>(QScriptEnginePrivate::frameForContext(this));
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     if (frame == frame->lexicalGlobalObject()->globalExec()) {
         // <global> context doesn't have arguments. return an empty object
         return QScriptEnginePrivate::get(QScript::scriptEngineFromExec(frame))->newObject();
     }
     //for a js function
     if (frame->codeBlock() && frame->callee()) {
         if (!QScriptEnginePrivate::hasValidCodeBlockRegister(frame)) {
             // We have a built-in JS host call.
             // codeBlock is needed by retrieveArguments(), but since it
             // contains junk, we would crash. Return an invalid value for now.
             return QScriptValue();
         }
         JSC::JSValue result = frame->interpreter()->retrieveArguments(frame, JSC::asFunction(frame->callee()));
         return QScript::scriptEngineFromExec(frame)->scriptValueFromJSCValue(result);
     }
     if (frame->callerFrame()->hasHostCallFrameFlag()) {
         // <eval> context doesn't have arguments. return an empty object
         return QScriptEnginePrivate::get(QScript::scriptEngineFromExec(frame))->newObject();
     }
     //for a native function
     if (!frame->optionalCalleeArguments()
         && QScriptEnginePrivate::hasValidCodeBlockRegister(frame)) { // Make sure we don't go here for host JSFunctions
         Q_ASSERT(frame->argumentCount() > 0); //we need at least 'this' otherwise we'll crash later
         JSC::Arguments* arguments = new (&frame->globalData())JSC::Arguments(frame, JSC::Arguments::NoParameters);
         frame->setCalleeArguments(arguments);
     }
     return QScript::scriptEngineFromExec(frame)->scriptValueFromJSCValue(frame->optionalCalleeArguments());
 }
backtrace()
QStringList QScriptContext::backtrace () const
Returns a human-readable backtrace of this QScriptContext.
Each line is of the form <function-name>(<arguments>)<file-name>:<line-number>.
To access individual pieces of debugging-related information (for example, to construct your own backtrace representation), use QScriptContextInfo.
See also
QScriptEngine::uncaughtExceptionBacktrace(), QScriptContextInfo, toString()
Definition at line 629 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerBackend::backtrace().
 {
     QStringList result;
     const QScriptContext *ctx = this;
     while (ctx) {
         result.append(ctx->toString());
         ctx = ctx->parentContext();
     }
     return result;
 }
callee()
QScriptValue QScriptContext::callee () const
Returns the callee.
The callee is the function object that this QScriptContext represents an invocation of.
Definition at line 280 of file qscriptcontext.cpp.
Referenced by do_dbus_call(), QScriptDebuggerCommandExecutor::execute(), and QScriptDebuggerBackendPrivate::trace().
 {
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScriptEnginePrivate *eng = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(eng);
     if (frame->callee() == eng->originalGlobalObject()) {
         // This is a pushContext()-created context; the callee is a lie.
         Q_ASSERT(QScriptEnginePrivate::contextFlags(const_cast<JSC::CallFrame*>(frame)) & QScriptEnginePrivate::NativeContext);
         return QScriptValue();
     }
     return eng->scriptValueFromJSCValue(frame->callee());
 }
engine()
QScriptEngine * QScriptContext::engine () const
Returns the QScriptEngine that this QScriptContext belongs to.
Definition at line 252 of file qscriptcontext.cpp.
Referenced by activationObject(), QDeclarativeEnginePrivate::createQmlObject(), popScope(), pushScope(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), scopeChain(), setActivationObject(), setThisObject(), thisObject(), and QScriptDeclarativeClass::Value::Value().
 {
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     return QScriptEnginePrivate::get(QScript::scriptEngineFromExec(frame));
 }
isCalledAsConstructor()
bool QScriptContext::isCalledAsConstructor () const
Returns true if the function was called as a constructor (e.g.
"new foo()"); otherwise returns false.
When a function is called as constructor, the thisObject() contains the newly constructed object to be initialized.
Note
This function is only guaranteed to work for a context corresponding to native functions.
Definition at line 355 of file qscriptcontext.cpp.
Referenced by qmlxmlhttprequest_new().
 {
     JSC::CallFrame *frame = const_cast<JSC::ExecState*>(QScriptEnginePrivate::frameForContext(this));
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     //For native functions, look up flags.
     uint flags = QScriptEnginePrivate::contextFlags(frame);
     if (flags & QScriptEnginePrivate::NativeContext)
         return flags & QScriptEnginePrivate::CalledAsConstructorContext;
     //Not a native function, try to look up in the bytecode if we where called from op_construct
     JSC::Instruction* returnPC = frame->returnPC();
     if (!returnPC)
         return false;
     JSC::CallFrame *callerFrame = QScriptEnginePrivate::frameForContext(parentContext());
     if (!callerFrame)
         return false;
     if (returnPC[-JSC::op_construct_length].u.opcode == frame->interpreter()->getOpcode(JSC::op_construct)) {
         //We are maybe called from the op_construct opcode which has 6 opperands.
         //But we need to check we are not called from op_call with 4 opperands
         //we make sure that the returnPC[-1] (thisRegister) is smaller than the returnPC[-3] (registerOffset)
         //as if it was an op_call, the returnPC[-1] would be the registerOffset, bigger than returnPC[-3] (funcRegister)
         return returnPC[-1].u.operand < returnPC[-3].u.operand;
     }
     return false;
 }
parentContext()
QScriptContext * QScriptContext::parentContext () const
Returns the parent context of this QScriptContext.
Definition at line 389 of file qscriptcontext.cpp.
Referenced by activationObject(), backtrace(), QScriptDebuggerBackend::context(), QScriptDebuggerBackendPrivate::fileName(), isCalledAsConstructor(), QScriptDebuggerBackendPrivate::lineNumber(), QJSDebuggerAgent::localsAtFrame(), QScriptEnginePrivate::mark(), QScriptEngine::popContext(), QScriptDebuggerBackendPrivate::qsassert(), QScriptDebuggerAgent::QScriptDebuggerAgent(), and toString().
 {
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     JSC::CallFrame *callerFrame = frame->callerFrame()->removeHostCallFrameFlag();
     return QScriptEnginePrivate::contextForFrame(callerFrame);
 }
popScope()
QScriptValue QScriptContext::popScope ()
Removes the front object from this context's scope chain, and returns the removed object.
Warning
This function is not part of the public interface.
Since
4.5
If the scope chain is already empty, this function returns an invalid QScriptValue.
Definition at line 790 of file qscriptcontext.cpp.
 {
     activationObject(); //ensure the creation of the normal scope for native context
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     JSC::ScopeChainNode *scope = frame->scopeChain();
     Q_ASSERT(scope != 0);
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(engine);
     QScriptValue result = engine->scriptValueFromJSCValue(scope->object);
     if (!scope->next) {
         // We cannot have a null scope chain, so just zap the object pointer.
         scope->object = 0;
     } else {
         frame->setScopeChain(scope->pop());
     }
     return result;
 }
pushScope()
void QScriptContext::pushScope (const QScriptValue & object)
Adds the given object to the front of this context's scope chain.
Warning
This function is not part of the public interface.
Since
4.5
If object is not an object, this function does nothing.
Definition at line 746 of file qscriptcontext.cpp.
Referenced by QDeclarativeContextData::addImportedScript(), QScriptDebuggerBackend::doPendingEvaluate(), QDeclarativeExpressionPrivate::evalInObjectScope(), QDeclarativeInclude::finished(), QDeclarativeInclude::include(), QDeclarativeExpressionPrivate::init(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QDeclarativeExpressionPrivate::scriptValue(), and QDeclarativeInclude::worker_include().
 {
     activationObject(); //ensure the creation of the normal scope for native context
     if (!object.isObject())
         return;
     else if (object.engine() != engine()) {
         qWarning("QScriptContext::pushScope() failed: "
                  "cannot push an object created in "
                  "a different engine");
         return;
     }
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(engine);
     JSC::JSObject *jscObject = JSC::asObject(engine->scriptValueToJSCValue(object));
     if (jscObject == engine->originalGlobalObjectProxy)
         jscObject = engine->originalGlobalObject();
     JSC::ScopeChainNode *scope = frame->scopeChain();
     Q_ASSERT(scope != 0);
     if (!scope->object) {
         // pushing to an "empty" chain
         if (!jscObject->isGlobalObject()) {
             qWarning("QScriptContext::pushScope() failed: initial object in scope chain has to be the Global Object");
             return;
         }
         scope->object = jscObject;
     }
     else
         frame->setScopeChain(scope->push(jscObject));
 }
returnValue()
QScriptValue QScriptContext::returnValue () const
Warning
This function is not part of the public interface.
Definition at line 419 of file qscriptcontext.cpp.
 {
     qWarning("QScriptContext::returnValue() not implemented");
     return QScriptValue();
 }
scopeChain()
QScriptValueList QScriptContext::scopeChain () const
Returns the scope chain of this QScriptContext.
Warning
This function is not part of the public interface.
Since
4.5
Definition at line 712 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerBackend::doPendingEvaluate(), and QScriptDebuggerCommandExecutor::execute().
 {
     activationObject(); //ensure the creation of the normal scope for native context
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(engine);
     QScriptValueList result;
     JSC::ScopeChainNode *node = frame->scopeChain();
     JSC::ScopeChainIterator it(node);
     for (it = node->begin(); it != node->end(); ++it) {
         JSC::JSObject *object = *it;
         if (!object)
             continue;
         if (object->inherits(&QScript::QScriptActivationObject::info)
             && (static_cast<QScript::QScriptActivationObject*>(object)->delegate() != 0)) {
             // Return the object that property access is being delegated to
             object = static_cast<QScript::QScriptActivationObject*>(object)->delegate();
         }
         result.append(engine->scriptValueFromJSCValue(object));
     }
     return result;
 }
setActivationObject()
void QScriptContext::setActivationObject (const QScriptValue & activation)
Sets the activation object of this QScriptContext to be the given activation.
If activation is not an object, this function does nothing.
Note
For a context corresponding to a JavaScript function, this is only guaranteed to work if there was an QScriptEngineAgent active on the engine while the function was evaluated.
Definition at line 511 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerBackend::doPendingEvaluate(), QDeclarativeInclude::finished(), QDeclarativeInclude::include(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), and QDeclarativeInclude::worker_include().
 {
     if (!activation.isObject())
         return;
     else if (activation.engine() != engine()) {
         qWarning("QScriptContext::setActivationObject() failed: "
                  "cannot set an object created in "
                  "a different engine");
         return;
     }
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(engine);
     JSC::JSObject *object = JSC::asObject(engine->scriptValueToJSCValue(activation));
     if (object == engine->originalGlobalObjectProxy)
         object = engine->originalGlobalObject();
     uint flags = QScriptEnginePrivate::contextFlags(frame);
     if ((flags & QScriptEnginePrivate::NativeContext) && !(flags & QScriptEnginePrivate::HasScopeContext)) {
         //For native functions, we create a scope node
         JSC::JSObject *scope = object;
         if (!scope->isVariableObject()) {
             // Create a QScriptActivationObject that acts as a proxy
             scope = new (frame) QScript::QScriptActivationObject(frame, scope);
         }
         frame->setScopeChain(frame->scopeChain()->copy()->push(scope));
         QScriptEnginePrivate::setContextFlags(frame, flags | QScriptEnginePrivate::HasScopeContext);
         return;
     }
     // else replace the first activation object in the scope chain
     JSC::ScopeChainNode *node = frame->scopeChain();
     while (node != 0) {
         if (node->object && node->object->isVariableObject()) {
             if (!object->isVariableObject()) {
                 if (node->object->inherits(&QScript::QScriptActivationObject::info)) {
                     static_cast<QScript::QScriptActivationObject*>(node->object)->setDelegate(object);
                 } else {
                     // Create a QScriptActivationObject that acts as a proxy
                     node->object = new (frame) QScript::QScriptActivationObject(frame, object);
                 }
             } else {
                 node->object = object;
             }
             break;
         }
         node = node->next;
     }
 }
setReturnValue()
void QScriptContext::setReturnValue (const QScriptValue & result)
Warning
This function is not part of the public interface.
Definition at line 428 of file qscriptcontext.cpp.
 {
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     JSC::CallFrame *callerFrame = frame->callerFrame();
     if (!callerFrame->codeBlock())
         return;
     Q_ASSERT_X(false, Q_FUNC_INFO, "check me");
     int dst = frame->registers()[JSC::RegisterFile::ReturnValueRegister].i(); // returnValueRegister() is private
     callerFrame[dst] = QScript::scriptEngineFromExec(frame)->scriptValueToJSCValue(result);
 }
setThisObject()
void QScriptContext::setThisObject (const QScriptValue & thisObject)
Sets the `this' object associated with this QScriptContext to be thisObject.
If thisObject is not an object, this function does nothing.
Definition at line 581 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerBackend::doPendingEvaluate(), and QScriptEngine::importExtension().
 {
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     if (!thisObject.isObject())
         return;
     if (thisObject.engine() != engine()) {
         qWarning("QScriptContext::setThisObject() failed: "
                  "cannot set an object created in "
                  "a different engine");
         return;
     }
     if (frame == frame->lexicalGlobalObject()->globalExec()) {
         engine()->setGlobalObject(thisObject);
         return;
     }
     JSC::JSValue jscThisObject = QScript::scriptEngineFromExec(frame)->scriptValueToJSCValue(thisObject);
     JSC::CodeBlock *cb = frame->codeBlock();
     if (cb != 0) {
         frame[cb->thisRegister()] = jscThisObject;
     } else {
         JSC::Register* thisRegister = QScriptEnginePrivate::thisRegisterForFrame(frame);
         thisRegister[0] = jscThisObject;
     }
 }
state()
QScriptContext::ExecutionState QScriptContext::state () const
Returns the frameution state of this QScriptContext.
Definition at line 610 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     if (frame->hadException())
         return QScriptContext::ExceptionState;
     return QScriptContext::NormalState;
 }
thisObject()
QScriptValue QScriptContext::thisObject () const
Returns the `this' object associated with this QScriptContext.
Definition at line 564 of file qscriptcontext.cpp.
Referenced by Node::attributes(), Node::childNodes(), QDeclarativeObjectMethodScriptClass::connect(), QScript::ClassObjectDelegate::construct(), QScriptDBusMessageConstructor::createErrorReply(), QScriptDBusMessageConstructor::createReply(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectMethodScriptClass::disconnect(), do_dbus_call(), Document::documentElement(), QScriptDebuggerBackend::doPendingEvaluate(), QScriptDebuggerCommandExecutor::execute(), Node::firstChild(), QJSDebuggerAgentPrivate::getLocals(), Text::isElementContentWhitespace(), Node::lastChild(), NamedNodeMap::length(), NodeList::length(), CharacterData::length(), Attr::name(), Node::nextSibling(), Node::nodeName(), Node::nodeType(), Node::nodeValue(), QDeclarativeWorkerScriptEnginePrivate::onMessage(), Attr::ownerElement(), Node::parentNode(), Node::previousSibling(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlsqldatabase_item(), qmlsqldatabase_transaction_shared(), qmlxmlhttprequest_abort(), qmlxmlhttprequest_getAllResponseHeaders(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_new(), qmlxmlhttprequest_onreadystatechange(), qmlxmlhttprequest_open(), qmlxmlhttprequest_readyState(), qmlxmlhttprequest_responseText(), qmlxmlhttprequest_responseXML(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), qmlxmlhttprequest_status(), qmlxmlhttprequest_statusText(), QDeclarativeWorkerScriptEnginePrivate::sendMessage(), QDeclarativeObjectScriptClass::tostring(), Attr::value(), Text::wholeText(), Document::xmlEncoding(), Document::xmlStandalone(), and Document::xmlVersion().
 {
     JSC::CallFrame *frame = const_cast<JSC::ExecState*>(QScriptEnginePrivate::frameForContext(this));
     QScriptEnginePrivate *engine = QScript::scriptEngineFromExec(frame);
     QScript::APIShim shim(engine);
     JSC::JSValue result = engine->thisForContext(frame);
     if (!result || result.isNull())
         result = frame->globalThisValue();
     return engine->scriptValueFromJSCValue(result);
 }
throwError() [1/2]
QScriptValue QScriptContext::throwError (Error error, const QString & text)
Throws an error with the given text.
Returns the created error object.
The text will be stored in the message property of the error object.
The error object will be initialized to contain information about the location where the error occurred; specifically, it will have properties lineNumber, fileName and stack. These properties are described in QtScript Extensions to ECMAScript.
See also
throwValue(), state()
Definition at line 193 of file qscriptcontext.cpp.
Referenced by QDeclarativeEnginePrivate::atob(), QDeclarativeEnginePrivate::btoa(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::callPrecise(), QDeclarativeEnginePrivate::createComponent(), QDeclarativeEnginePrivate::createQmlObject(), QDeclarativeEnginePrivate::darker(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeEnginePrivate::fontFamilies(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), QDeclarativeEnginePrivate::hsla(), QScriptEngine::importExtension(), QDeclarativeInclude::include(), QDeclarativeEnginePrivate::lighter(), QDeclarativeEnginePrivate::md5(), QDeclarativeEnginePrivate::point(), QScriptDebuggerBackendPrivate::qsassert(), QDeclarativeEnginePrivate::rect(), QDeclarativeEnginePrivate::rgba(), QDeclarativeGlobalScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeEnginePrivate::size(), QDeclarativeEnginePrivate::tint(), and QDeclarativeEnginePrivate::vector3d().
 {
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     JSC::ErrorType jscError = JSC::GeneralError;
     switch (error) {
     case UnknownError:
         break;
     case ReferenceError:
         jscError = JSC::ReferenceError;
         break;
     case SyntaxError:
         jscError = JSC::SyntaxError;
         break;
     case TypeError:
         jscError = JSC::TypeError;
         break;
     case RangeError:
         jscError = JSC::RangeError;
         break;
     case URIError:
         jscError = JSC::URIError;
         break;
     }
     JSC::JSObject *result = JSC::throwError(frame, jscError, text);
     return QScript::scriptEngineFromExec(frame)->scriptValueFromJSCValue(result);
 }
throwError() [2/2]
QScriptValue QScriptContext::throwError (const QString & text)
Throws an error with the given text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the created error object.
See also
throwValue(), state()
Definition at line 232 of file qscriptcontext.cpp.
 {
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     JSC::JSObject *result = JSC::throwError(frame, JSC::GeneralError, text);
     return QScript::scriptEngineFromExec(frame)->scriptValueFromJSCValue(result);
 }
throwValue()
QScriptValue QScriptContext::throwValue (const QScriptValue & value)
Throws an exception with the given value.
Returns the value thrown (the same as the argument).
See also
throwError(), state()
Definition at line 170 of file qscriptcontext.cpp.
Referenced by QScriptDebuggerAgent::enterReturnByForceMode().
 {
     JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
     QScript::APIShim shim(QScript::scriptEngineFromExec(frame));
     JSC::JSValue jscValue = QScript::scriptEngineFromExec(frame)->scriptValueToJSCValue(value);
     frame->setException(jscValue);
     return value;
 }
toString()
QString QScriptContext::toString () const
Returns a string representation of this context.
Since
4.4
This is useful for debugging.
See also
backtrace()
Definition at line 651 of file qscriptcontext.cpp.
Referenced by backtrace().
 {
     QScriptContextInfo info(this);
     QString result;
     QString functionName = info.functionName();
     if (functionName.isEmpty()) {
         if (parentContext()) {
             const JSC::CallFrame *frame = QScriptEnginePrivate::frameForContext(this);
             if (info.functionType() == QScriptContextInfo::ScriptFunction)
                 result.append(QLatin1String("<anonymous>"));
             else if(frame->callerFrame()->hasHostCallFrameFlag())
                 result.append(QLatin1String("<eval>"));
             else
                 result.append(QLatin1String("<native>"));
         } else {
             result.append(QLatin1String("<global>"));
         }
     } else {
         result.append(functionName);
     }
     QStringList parameterNames = info.functionParameterNames();
     result.append(QLatin1Char('('));
     for (int i = 0; i < argumentCount(); ++i) {
         if (i > 0)
             result.append(QLatin1String(", "));
         if (i < parameterNames.count()) {
             result.append(parameterNames.at(i));
             result.append(QLatin1String(" = "));
         }
         QScriptValue arg = argument(i);
         if (arg.isString())
             result.append(QLatin1Char('\''));
         result.append(arg.toString());
         if (arg.isString())
             result.append(QLatin1Char('\''));
     }
     result.append(QLatin1Char(')'));
     QString fileName = info.fileName();
     int lineNumber = info.lineNumber();
     result.append(QLatin1String(" at "));
     if (!fileName.isEmpty()) {
         result.append(fileName);
         result.append(QLatin1Char(':'));
     }
     result.append(QString::number(lineNumber));
     return result;
 }
Properties
d_ptr
QScriptContextPrivate* QScriptContext::d_ptr private
Definition at line 94 of file qscriptcontext.h.
The documentation for this class was generated from the following files:
/src/script/api/qscriptcontext.h
/src/script/api/qscriptcontext.cpp