Qt 4.8: QPatternist::AbstractFunctionFactory Class Reference
QPatternist::AbstractFunctionFactory Class Reference abstract
Supplies convenience code for the function factories.
#include <qabstractfunctionfactory_p.h>
Public Functions
virtual Expression::Ptr createFunctionCall (const QXmlName name, const Expression::List &arguments, const StaticContext::Ptr &context, const SourceLocationReflection *const r)
virtual FunctionSignature::Hash functionSignatures () const
Public Functions inherited from QPatternist::FunctionFactory
bool hasSignature (const FunctionSignature::Ptr &signature) const
virtual bool isAvailable (const NamePool::Ptr &np, const QXmlName name, const xsInteger arity)
virtual ~FunctionFactory ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Protected Functions
FunctionSignature::Ptr addFunction (const QXmlName::LocalNameCode localName, const FunctionSignature::Arity minArgs, const FunctionSignature::Arity maxArgs, const SequenceType::Ptr &returnType, const Expression::Properties props)
FunctionSignature::Ptr addFunction (const QXmlName::LocalNameCode &localName, const FunctionSignature::Arity minArgs, const FunctionSignature::Arity maxArgs, const SequenceType::Ptr &returnType, const Expression::ID id=Expression::IDIgnorableExpression, const Expression::Properties props=Expression::Properties(), const StandardNamespaces::ID ns=StandardNamespaces::fn)
virtual Expression::Ptr retrieveExpression (const QXmlName name, const Expression::List &args, const FunctionSignature::Ptr &sign) const =0
Protected Functions inherited from QPatternist::FunctionFactory
FunctionFactory ()
This constructor cannot be removed, because it can't be synthesized, for some reason.
virtual FunctionSignature::Ptr retrieveFunctionSignature (const NamePool::Ptr &np, const QXmlName name)=0
Static Protected Functions
static QXmlName::LocalNameCode argument (const NamePool::Ptr &np, const char *const name)
Protected Variables
FunctionSignature::Hash m_signatures
Private Functions
void verifyArity (const FunctionSignature::Ptr &sign, const StaticContext::Ptr &context, const xsInteger arity, const SourceLocationReflection *const r) const
Determines whether arity is a valid number of arguments for the function with signature sign.
Additional Inherited Members
Public Types inherited from QPatternist::FunctionFactory
typedef QList< FunctionFactory::Ptr > List
typedef QExplicitlySharedDataPointer< FunctionFactory > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Supplies convenience code for the function factories.
See also
XPath10CoreFunctions
XPath20CoreFunctions
XSLT10CoreFunctions
Author
Vincent Ricard magic.nosp@m.@mag.nosp@m.icnin.nosp@m.ja.o.nosp@m.rg
Definition at line 75 of file qabstractfunctionfactory_p.h.
Functions
addFunction() [1/2]
FunctionSignature::Ptr QPatternist::AbstractFunctionFactory::addFunction (const QXmlName::LocalNameCode localName, const FunctionSignature::Arity minArgs, const FunctionSignature::Arity maxArgs, const SequenceType::Ptr & returnType, const Expression::Properties props) inline protected
Definition at line 99 of file qabstractfunctionfactory_p.h.
Referenced by QPatternist::XPath10CoreFunctions::retrieveFunctionSignature(), QPatternist::XSLT20CoreFunctions::retrieveFunctionSignature(), and QPatternist::XPath20CoreFunctions::retrieveFunctionSignature().
         {
             return addFunction(localName,
                                minArgs,
                                maxArgs,
                                returnType,
                                Expression::IDIgnorableExpression,
                                props);
         }
addFunction() [2/2]
FunctionSignature::Ptr QPatternist::AbstractFunctionFactory::addFunction (const QXmlName::LocalNameCode & localName, const FunctionSignature::Arity minArgs, const FunctionSignature::Arity maxArgs, const SequenceType::Ptr & returnType, const Expression::ID id = Expression::IDIgnorableExpression, const Expression::Properties props = Expression::Properties(), const StandardNamespaces::ID ns = StandardNamespaces::fn) inline protected
Definition at line 113 of file qabstractfunctionfactory_p.h.
         {
             const QXmlName name(ns, localName);
             const FunctionSignature::Ptr s(new FunctionSignature(name, minArgs, maxArgs,
                                                                  returnType, props, id));
             m_signatures.insert(name, s);
             return s;
         }
argument()
static QXmlName::LocalNameCode QPatternist::AbstractFunctionFactory::argument (const NamePool::Ptr & np, const char *const name) inline static protected
Definition at line 130 of file qabstractfunctionfactory_p.h.
Referenced by QPatternist::XPath10CoreFunctions::retrieveFunctionSignature(), QPatternist::XSLT20CoreFunctions::retrieveFunctionSignature(), and QPatternist::XPath20CoreFunctions::retrieveFunctionSignature().
         {
             return np->allocateLocalName(QLatin1String(name));
         }
createFunctionCall()
Expression::Ptr AbstractFunctionFactory::createFunctionCall (const QXmlName name, const Expression::List & arguments, const StaticContext::Ptr & context, const SourceLocationReflection *const r) virtual
Creates a function call implementation.
A FunctionFactory represents a set of functions, which it is able to instantiate and to serve FunctionSignatures for. Conventionally, a FunctionFactory per namespace exists.
Note
This function should not issue any error unless it is absolutely confident that the error cannot be fixed in another way. For example, in some cases it might be that a function is available in another FunctionFactory and it would therefore be wrong to issue an error signalling that no function by that name exists, but leave that to the callee.
Parameters
name the name of the function to create. In Clark syntax, this could for example be {http://www.w3.org/2005/04/xpath-functions}lower-case
arguments the function's operands
context the usual StaticContext which supplies compile time data and reporting functionality.
r the SourceLocationReflection that identifies the callsite.
Returns
an instance of Expression which is the function implementation for name. Or, a static error was raised.
Implements QPatternist::FunctionFactory.
Definition at line 50 of file qabstractfunctionfactory.cpp.
 {
     const FunctionSignature::Ptr sign(retrieveFunctionSignature(context->namePool(), name));
     if(!sign) /* The function doesn't exist(at least not in this factory). */
         return Expression::Ptr();
     /* May throw. */
     verifyArity(sign, context, args.count(), r);
     /* Ok, the function does exist and the arity is correct. */
     return retrieveExpression(name, args, sign);
 }
functionSignatures()
FunctionSignature::Hash AbstractFunctionFactory::functionSignatures () const virtual
Implements QPatternist::FunctionFactory.
Definition at line 98 of file qabstractfunctionfactory.cpp.
Referenced by QPatternist::ConstructorFunctionsFactory::retrieveFunctionSignature(), QPatternist::XSLT20CoreFunctions::retrieveFunctionSignature(), QPatternist::XPath10CoreFunctions::retrieveFunctionSignature(), and QPatternist::XPath20CoreFunctions::retrieveFunctionSignature().
 {
     return m_signatures;
 }
retrieveExpression()
virtual Expression::Ptr QPatternist::AbstractFunctionFactory::retrieveExpression (const QXmlName name, const Expression::List & args, const FunctionSignature::Ptr & sign) const protected pure virtual
This function is responsible for creating the actual Expression, corresponding to localName and the function signature sign. It is called by createFunctionCall(), once it have been determined the function actually exists and have the correct arity.
This function will only be called for names in the fn namespace.
Implemented in QPatternist::XPath20CoreFunctions, QPatternist::ConstructorFunctionsFactory, QPatternist::XPath10CoreFunctions, and QPatternist::XSLT20CoreFunctions.
Referenced by createFunctionCall().
verifyArity()
void AbstractFunctionFactory::verifyArity (const FunctionSignature::Ptr & sign, const StaticContext::Ptr & context, const xsInteger arity, const SourceLocationReflection *const r) const private
Determines whether arity is a valid number of arguments for the function with signature sign.
If it is not, a static error with error code ReportContext::XPST0017 is issued via context.
Definition at line 67 of file qabstractfunctionfactory.cpp.
Referenced by createFunctionCall().
 {
     /* Same code in both branches, but more specific error messages in order
      * to improve usability. */
     if(s->maximumArguments() != FunctionSignature::UnlimitedArity &&
        arity > s->maximumArguments())
     {
         context->error(QtXmlPatterns::tr("%1 takes at most %n argument(s). "
                                          "%2 is therefore invalid.", 0, s->maximumArguments())
                           .arg(formatFunction(context->namePool(), s))
                           .arg(arity),
                        ReportContext::XPST0017,
                        r);
         return;
     }
     if(arity < s->minimumArguments())
     {
         context->error(QtXmlPatterns::tr("%1 requires at least %n argument(s). "
                                          "%2 is therefore invalid.", 0, s->minimumArguments())
                           .arg(formatFunction(context->namePool(), s))
                           .arg(arity),
                        ReportContext::XPST0017,
                        r);
         return;
     }
 }
Properties
m_signatures
FunctionSignature::Hash QPatternist::AbstractFunctionFactory::m_signatures protected
Definition at line 135 of file qabstractfunctionfactory_p.h.
Referenced by addFunction(), QPatternist::ConstructorFunctionsFactory::ConstructorFunctionsFactory(), and functionSignatures().
The documentation for this class was generated from the following files:
/src/xmlpatterns/functions/qabstractfunctionfactory_p.h
/src/xmlpatterns/functions/qabstractfunctionfactory.cpp