Qt 4.8: QTestXunitStreamer Class Reference
QTestXunitStreamer Class Reference
#include <qtestxunitstreamer.h>
Public Functions
void formatAfterAttributes (const QTestElement *element, QTestCharBuffer *formatted) const
void formatAttributes (const QTestElement *element, const QTestElementAttribute *attribute, QTestCharBuffer *formatted) const
void formatEnd (const QTestElement *element, QTestCharBuffer *formatted) const
void formatStart (const QTestElement *element, QTestCharBuffer *formatted) const
void output (QTestElement *element) const
void outputElements (QTestElement *element, bool isChildElement=false) const
QTestXunitStreamer ()
~QTestXunitStreamer ()
Public Functions inherited from QTestBasicStreamer
bool isTtyOutput ()
const QTestLogger * logger () const
void outputString (const char *msg) const
QTestBasicStreamer ()
void setLogger (const QTestLogger *tstLogger)
void startStreaming ()
void stopStreaming ()
virtual ~QTestBasicStreamer ()
Private Functions
void displayXunitXmlHeader () const
Static Private Functions
static void indentForElement (const QTestElement *element, char *buf, int size)
Additional Inherited Members
Protected Functions inherited from QTestBasicStreamer
virtual void formatBeforeAttributes (const QTestElement *element, QTestCharBuffer *formatted) const
virtual void outputElementAttributes (const QTestElement *element, QTestElementAttribute *attribute) const
Detailed Description
Definition at line 55 of file qtestxunitstreamer.h.
Constructors and Destructors
QTestXunitStreamer()
QTestXunitStreamer::QTestXunitStreamer ()
Definition at line 51 of file qtestxunitstreamer.cpp.
     :QTestBasicStreamer()
 {}
~QTestXunitStreamer()
QTestXunitStreamer::~QTestXunitStreamer ()
Definition at line 55 of file qtestxunitstreamer.cpp.
 {}
Functions
displayXunitXmlHeader()
void QTestXunitStreamer::displayXunitXmlHeader () const private
formatAfterAttributes()
void QTestXunitStreamer::formatAfterAttributes (const QTestElement * element, QTestCharBuffer * formatted) const virtual
Reimplemented from QTestBasicStreamer.
Definition at line 145 of file qtestxunitstreamer.cpp.
Referenced by outputElements().
 {
     if(!element || !formatted )
         return;
     // Errors are written as CDATA within system-err, comments elsewhere
     if (element->elementType() == QTest::LET_Error) {
         if (element->parentElement()->elementType() == QTest::LET_SystemError) {
             QTest::qt_asprintf(formatted, "]]>\n");
         } else {
             QTest::qt_asprintf(formatted, " -->\n");
         }
         return;
     }
     if(!element->childElements())
         QTest::qt_asprintf(formatted, "/>\n");
     else
         QTest::qt_asprintf(formatted, ">\n");
 }
formatAttributes()
void QTestXunitStreamer::formatAttributes (const QTestElement * element, const QTestElementAttribute * attribute, QTestCharBuffer * formatted) const virtual
Reimplemented from QTestBasicStreamer.
Definition at line 113 of file qtestxunitstreamer.cpp.
 {
     if(!attribute || !formatted )
         return;
     QTest::AttributeIndex attrindex = attribute->index();
     // For errors within system-err, we only want to output `message'
     if (element && element->elementType() == QTest::LET_Error
         && element->parentElement()->elementType() == QTest::LET_SystemError) {
         if (attrindex != QTest::AI_Description) return;
         QXmlTestLogger::xmlCdata(formatted, attribute->value());
         return;
     }
     char const* key = 0;
     if (attrindex == QTest::AI_Description)
         key = "message";
     else if (attrindex != QTest::AI_File && attrindex != QTest::AI_Line)
         key = attribute->name();
     if (key) {
         QTestCharBuffer quotedValue;
         QXmlTestLogger::xmlQuote(&quotedValue, attribute->value());
         QTest::qt_asprintf(formatted, " %s=\"%s\"", key, quotedValue.constData());
     } else {
         formatted->data()[0] = '\0';
     }
 }
formatEnd()
void QTestXunitStreamer::formatEnd (const QTestElement * element, QTestCharBuffer * formatted) const virtual
Reimplemented from QTestBasicStreamer.
Definition at line 97 of file qtestxunitstreamer.cpp.
Referenced by outputElements().
 {
     if (!element || !formatted )
         return;
     if (!element->childElements()){
         formatted->data()[0] = '\0';
         return;
     }
     char indent[20];
     indentForElement(element, indent, sizeof(indent));
     QTest::qt_asprintf(formatted, "%s</%s>\n", indent, element->elementName());
 }
formatStart()
void QTestXunitStreamer::formatStart (const QTestElement * element, QTestCharBuffer * formatted) const virtual
Reimplemented from QTestBasicStreamer.
Definition at line 76 of file qtestxunitstreamer.cpp.
Referenced by outputElements().
 {
     if(!element || !formatted )
         return;
     char indent[20];
     indentForElement(element, indent, sizeof(indent));
     // Errors are written as CDATA within system-err, comments elsewhere
     if (element->elementType() == QTest::LET_Error) {
         if (element->parentElement()->elementType() == QTest::LET_SystemError) {
             QTest::qt_asprintf(formatted, "<![CDATA[");
         } else {
             QTest::qt_asprintf(formatted, "%s<!--", indent);
         }
         return;
     }
     QTest::qt_asprintf(formatted, "%s<%s", indent, element->elementName());
 }
indentForElement()
void QTestXunitStreamer::indentForElement (const QTestElement * element, char * buf, int size) static private
Definition at line 58 of file qtestxunitstreamer.cpp.
Referenced by formatEnd(), and formatStart().
 {
     if (size == 0) return;
     buf[0] = 0;
     if (!element) return;
     char* endbuf = buf + size;
     element = element->parentElement();
     while (element && buf+2 < endbuf) {
         *(buf++) = ' ';
         *(buf++) = ' ';
         *buf = 0;
         element = element->parentElement();
     }
 }
output()
void QTestXunitStreamer::output (QTestElement * element) const virtual
Reimplemented from QTestBasicStreamer.
Definition at line 166 of file qtestxunitstreamer.cpp.
 {
     outputString("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n");
     QTestBasicStreamer::output(element);
 }
outputElements()
void QTestXunitStreamer::outputElements (QTestElement * element, bool isChildElement = false) const virtual
Reimplemented from QTestBasicStreamer.
Definition at line 172 of file qtestxunitstreamer.cpp.
 {
     QTestCharBuffer buf;
     bool hasChildren;
     /*
         Elements are in reverse order of occurrence, so start from the end and work
         our way backwards.
     */
     while (element && element->nextElement()) {
         element = element->nextElement();
     }
     while (element) {
         hasChildren = element->childElements();
         if(element->elementType() != QTest::LET_Benchmark){
             formatStart(element, &buf);
             outputString(buf.data());
             formatBeforeAttributes(element, &buf);
             outputString(buf.data());
             outputElementAttributes(element, element->attributes());
             formatAfterAttributes(element, &buf);
             outputString(buf.data());
             if(hasChildren)
                 outputElements(element->childElements(), true);
             formatEnd(element, &buf);
             outputString(buf.data());
         }
         element = element->previousElement();
     }
 }
The documentation for this class was generated from the following files:
/src/testlib/qtestxunitstreamer.h
/src/testlib/qtestxunitstreamer.cpp