Qt 4.8: QDataStream Class Reference
QDataStream Class Reference
The QDataStream class provides serialization of binary data to a QIODevice.
#include <qdatastream.h>
Public Types
enum ByteOrder { BigEndian = QSysInfo::BigEndian, LittleEndian = QSysInfo::LittleEndian }
The byte order used for reading/writing the data.
enum FloatingPointPrecision { SinglePrecision, DoublePrecision }
The precision of floating point numbers used for reading/writing the data.
enum Status { Ok, ReadPastEnd, ReadCorruptData, WriteFailed }
This enum describes the current status of the data stream.
enum Version {
Qt_1_0 = 1, Qt_2_0 = 2, Qt_2_1 = 3, Qt_3_0 = 4,
Qt_3_1 = 5, Qt_3_3 = 6, Qt_4_0 = 7, Qt_4_1 = Qt_4_0,
Qt_4_2 = 8, Qt_4_3 = 9, Qt_4_4 = 10, Qt_4_5 = 11,
Qt_4_6 = 12, Qt_4_7 = Qt_4_6, Qt_4_8 = Qt_4_7
}
This enum provides symbolic synonyms for the data serialization format version numbers.
Public Functions
bool atEnd () const
Returns true if the I/O device has reached the end position (end of the stream or file) or if there is no I/O device set; otherwise returns false.
ByteOrder byteOrder () const
Returns the current byte order setting – either BigEndian or LittleEndian.
QIODevice * device () const
Returns the I/O device currently set, or 0 if no device is currently set.
FloatingPointPrecision floatingPointPrecision () const
Returns the floating point precision of the data stream.
QDataStream & operator<< (qint8 i)
Writes a signed byte, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (quint8 i)
Writes an unsigned byte, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (qint16 i)
Writes a signed 16-bit integer, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (quint16 i)
Writes an unsigned 16-bit integer, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (qint32 i)
Writes a signed 32-bit integer, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (quint32 i)
Writes an unsigned integer, i, to the stream as a 32-bit unsigned integer (quint32).
QDataStream & operator<< (qint64 i)
Writes a signed 64-bit integer, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (quint64 i)
Writes an unsigned 64-bit integer, i, to the stream and returns a reference to the stream.
QDataStream & operator<< (bool i)
Writes a boolean value, i, to the stream.
QDataStream & operator<< (float f)
Writes a floating point number, f, to the stream using the standard IEEE 754 format.
QDataStream & operator<< (double f)
Writes a floating point number, f, to the stream using the standard IEEE 754 format.
QDataStream & operator<< (const char *str)
Writes the '\0'-terminated string s to the stream and returns a reference to the stream.
QDataStream & operator>> (qint8 &i)
Reads a signed byte from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (quint8 &i)
Reads an unsigned byte from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (qint16 &i)
Reads a signed 16-bit integer from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (quint16 &i)
Reads an unsigned 16-bit integer from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (qint32 &i)
Reads a signed 32-bit integer from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (quint32 &i)
Reads an unsigned 32-bit integer from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (qint64 &i)
Reads a signed 64-bit integer from the stream into i, and returns a reference to the stream.
QDataStream & operator>> (quint64 &i)
Reads an unsigned 64-bit integer from the stream, into i, and returns a reference to the stream.
QDataStream & operator>> (bool &i)
Reads a boolean value from the stream into i.
QDataStream & operator>> (float &f)
Reads a floating point number from the stream into f, using the standard IEEE 754 format.
QDataStream & operator>> (double &f)
Reads a floating point number from the stream into f, using the standard IEEE 754 format.
QDataStream & operator>> (char *&str)
Reads the '\0'-terminated string s from the stream and returns a reference to the stream.
QDataStream ()
Constructs a data stream that has no I/O device.
QDataStream (QIODevice *)
Constructs a data stream that uses the I/O device d.
QDataStream (QByteArray *, QIODevice::OpenMode flags)
Constructs a data stream that operates on a byte array, a.
QDataStream (const QByteArray &)
Constructs a read-only data stream that operates on byte array a.
QDataStream & readBytes (char *&, uint &len)
Reads the buffer s from the stream and returns a reference to the stream.
int readRawData (char *, int len)
Reads at most len bytes from the stream into s and returns the number of bytes read.
void resetStatus ()
Resets the status of the data stream.
void setByteOrder (ByteOrder)
Sets the serialization byte order to bo.
void setDevice (QIODevice *)
void QDataStream::setDevice(QIODevice *d)
void setFloatingPointPrecision (FloatingPointPrecision precision)
Sets the floating point precision of the data stream to precision.
void setStatus (Status status)
Sets the status of the data stream to the status given.
void setVersion (int)
Sets the version number of the data serialization format to v.
int skipRawData (int len)
Skips len bytes from the device.
Status status () const
Returns the status of the data stream.
void unsetDevice ()
Unsets the I/O device.
int version () const
Returns the version number of the data serialization format.
QDataStream & writeBytes (const char *, uint len)
Writes the length specifier len and the buffer s to the stream and returns a reference to the stream.
int writeRawData (const char *, int len)
Writes len bytes from s to the stream.
virtual ~QDataStream ()
Destroys the data stream.
Properties
ByteOrder byteorder
QScopedPointer< QDataStreamPrivate > d
QIODevice * dev
bool noswap
bool owndev
Status q_status
int ver
Detailed Description
The QDataStream class provides serialization of binary data to a QIODevice.
Note
This class or function is reentrant.
A data stream is a binary stream of encoded information which is 100% independent of the host computer's operating system, CPU or byte order. For example, a data stream that is written by a PC under Windows can be read by a Sun SPARC running Solaris.
You can also use a data stream to read/write raw unencoded binary data. If you want a "parsing" input stream, see QTextStream.
The QDataStream class implements the serialization of C++'s basic data types, like char, short, int, char *, etc. Serialization of more complex data is accomplished by breaking up the data into primitive units.
A data stream cooperates closely with a QIODevice. A QIODevice represents an input/output medium one can read data from and write data to. The QFile class is an example of an I/O device.
Example (write binary data to a stream):
QFile file("file.dat");
file.open(QIODevice::WriteOnly);
QDataStream out(&file);   // we will serialize the data into the file
out << QString("the answer is");   // serialize a string
out << (qint32)42;        // serialize an integer
Example (read binary data from a stream):
QFile file("file.dat");
file.open(QIODevice::ReadOnly);
QDataStream in(&file);    // read the data serialized from the file
QString str;
qint32 a;
in >> str >> a;           // extract "the answer is" and 42
Each item written to the stream is written in a predefined binary format that varies depending on the item's type. Supported Qt types include QBrush, QColor, QDateTime, QFont, QPixmap, QString, QVariant and many others. For the complete list of all Qt types supporting data streaming see Serializing Qt Data Types.
For integers it is best to always cast to a Qt integer type for writing, and to read back into the same Qt integer type. This ensures that you get integers of the size you want and insulates you from compiler and platform differences.
To take one example, a char * string is written as a 32-bit integer equal to the length of the string including the '\0' byte, followed by all the characters of the string including the '\0' byte. When reading a char * string, 4 bytes are read to create the 32-bit length value, then that many characters for the {char *} string including the '\0' terminator are read.
The initial I/O device is usually set in the constructor, but can be changed with setDevice(). If you've reached the end of the data (or if there is no I/O device set) atEnd() will return true.
Versioning
QDataStream's binary format has evolved since Qt 1.0, and is likely to continue evolving to reflect changes done in Qt. When inputting or outputting complex types, it's very important to make sure that the same version of the stream (version()) is used for reading and writing. If you need both forward and backward compatibility, you can hardcode the version number in the application:
stream.setVersion(QDataStream::Qt_4_0);
If you are producing a new binary data format, such as a file format for documents created by your application, you could use a QDataStream to write the data in a portable format. Typically, you would write a brief header containing a magic string and a version number to give yourself room for future expansion. For example:
QFile file("file.xxx");
file.open(QIODevice::WriteOnly);
QDataStream out(&file);
// Write a header with a "magic number" and a version
out << (quint32)0xA0B0C0D0;
out << (qint32)123;
out.setVersion(QDataStream::Qt_4_0);
// Write the data
out << lots_of_interesting_data;
Then read it in with:
QFile file("file.xxx");
file.open(QIODevice::ReadOnly);
QDataStream in(&file);
// Read and check the header
quint32 magic;
in >> magic;
if (magic != 0xA0B0C0D0)
    return XXX_BAD_FILE_FORMAT;
// Read the version
qint32 version;
in >> version;
if (version < 100)
    return XXX_BAD_FILE_TOO_OLD;
if (version > 123)
    return XXX_BAD_FILE_TOO_NEW;
if (version <= 110)
    in.setVersion(QDataStream::Qt_3_2);
else
    in.setVersion(QDataStream::Qt_4_0);
// Read the data
in >> lots_of_interesting_data;
if (version >= 120)
    in >> data_new_in_XXX_version_1_2;
in >> other_interesting_data;
You can select which byte order to use when serializing data. The default setting is big endian (MSB first). Changing it to little endian breaks the portability (unless the reader also changes to little endian). We recommend keeping this setting unless you have special requirements.
Reading and writing raw binary data
You may wish to read/write your own raw binary data to/from the data stream directly. Data may be read from the stream into a preallocated char * using readRawData(). Similarly data can be written to the stream using writeRawData(). Note that any encoding/decoding of the data must be done by you.
A similar pair of functions is readBytes() and writeBytes(). These differ from their raw counterparts as follows: readBytes() reads a quint32 which is taken to be the length of the data to be read, then that number of bytes is read into the preallocated char *; writeBytes() writes a quint32 containing the length of the data, followed by the data. Note that any encoding/decoding of the data (apart from the length quint32) must be done by you.
Reading and writing Qt collection classes
The Qt container classes can also be serialized to a QDataStream. These include QList, QLinkedList, QVector, QSet, QHash, and QMap. The stream operators are declared as non-members of the classes.
.
Reading and writing other Qt classes.
In addition to the overloaded stream operators documented here, any Qt classes that you might want to serialize to a QDataStream will have appropriate stream operators declared as non-member of the class:
QDataStream &operator<<(QDataStream &, const QXxx &);
QDataStream &operator>>(QDataStream &, QXxx &);
For example, here are the stream operators declared as non-members of the QImage class:
QDataStream & operator<< (QDataStream& stream, const QImage& image);
QDataStream & operator>> (QDataStream& stream, QImage& image);
To see if your favorite Qt class has similar stream operators defined, check the Related Non-Members section of the class's documentation page.
See also
QTextStream QVariant
Definition at line 71 of file qdatastream.h.
Enumerations
ByteOrder
enum QDataStream::ByteOrder
The byte order used for reading/writing the data.
BigEndian Most significant byte first (the default)
LittleEndian Least significant byte first
Enumerator
BigEndian
LittleEndian
Definition at line 96 of file qdatastream.h.
                    {
         BigEndian = QSysInfo::BigEndian,
         LittleEndian = QSysInfo::LittleEndian
     };
FloatingPointPrecision
enum QDataStream::FloatingPointPrecision
The precision of floating point numbers used for reading/writing the data.
This will only have an effect if the version of the data stream is Qt_4_6 or higher.
Warning
The floating point precision must be set to the same value on the object that writes and the object that reads the data stream.
SinglePrecision All floating point numbers in the data stream have 32-bit precision.
DoublePrecision All floating point numbers in the data stream have 64-bit precision.
See also
setFloatingPointPrecision(), floatingPointPrecision()
Enumerator
SinglePrecision
DoublePrecision
Definition at line 108 of file qdatastream.h.
{
         SinglePrecision,
         DoublePrecision
     };
Status
enum QDataStream::Status
This enum describes the current status of the data stream.
Ok The data stream is operating normally.
ReadPastEnd The data stream has read past the end of the data in the underlying device.
ReadCorruptData The data stream has read corrupt data.
WriteFailed The data stream cannot write to the underlying device.
Enumerator
Ok
ReadPastEnd
ReadCorruptData
WriteFailed
Definition at line 101 of file qdatastream.h.
                 {
         Ok,
         ReadPastEnd,
         ReadCorruptData,
         WriteFailed
     };
Version
enum QDataStream::Version
This enum provides symbolic synonyms for the data serialization format version numbers.
Qt_1_0 Version 1 (Qt 1.x)
Qt_2_0 Version 2 (Qt 2.0)
Qt_2_1 Version 3 (Qt 2.1, 2.2, 2.3)
Qt_3_0 Version 4 (Qt 3.0)
Qt_3_1 Version 5 (Qt 3.1, 3.2)
Qt_3_3 Version 6 (Qt 3.3)
Qt_4_0 Version 7 (Qt 4.0, Qt 4.1)
Qt_4_1 Version 7 (Qt 4.0, Qt 4.1)
Qt_4_2 Version 8 (Qt 4.2)
Qt_4_3 Version 9 (Qt 4.3)
Qt_4_4 Version 10 (Qt 4.4)
Qt_4_5 Version 11 (Qt 4.5)
Qt_4_6 Version 12 (Qt 4.6, Qt 4.7, Qt 4.8)
Qt_4_7 Same as Qt_4_6.
Qt_4_8 Same as Qt_4_6.
See also
setVersion(), version()
Enumerator
Qt_1_0
Qt_2_0
Qt_2_1
Qt_3_0
Qt_3_1
Qt_3_3
Qt_4_0
Qt_4_1
Qt_4_2
Qt_4_3
Qt_4_4
Qt_4_5
Qt_4_6
Qt_4_7
Qt_4_8
Definition at line 74 of file qdatastream.h.
                  {
         Qt_1_0 = 1,
         Qt_2_0 = 2,
         Qt_2_1 = 3,
         Qt_3_0 = 4,
         Qt_3_1 = 5,
         Qt_3_3 = 6,
         Qt_4_0 = 7,
         Qt_4_1 = Qt_4_0,
         Qt_4_2 = 8,
         Qt_4_3 = 9,
         Qt_4_4 = 10,
         Qt_4_5 = 11,
         Qt_4_6 = 12,
         Qt_4_7 = Qt_4_6,
         Qt_4_8 = Qt_4_7
 #if QT_VERSION >= 0x040900
 #error Add the datastream version for this Qt version
         Qt_4_9 = Qt_4_8
 #endif
     };
Constructors and Destructors
QDataStream() [1/4]
QDataStream::QDataStream ()
Constructs a data stream that has no I/O device.
See also
setDevice()
Definition at line 276 of file qdatastream.cpp.
Referenced by QDataStream().
 {
     dev = 0;
     owndev = false;
     byteorder = BigEndian;
     ver = DefaultStreamVersion;
     noswap = QSysInfo::ByteOrder == QSysInfo::BigEndian;
     q_status = Ok;
 }
QDataStream() [2/4]
QDataStream::QDataStream (QIODevice * d) explicit
Constructs a data stream that uses the I/O device d.
Warning
If you use QSocket or QSocketDevice as the I/O device d for reading data, you must make sure that enough data is available on the socket for the operation to successfully proceed; QDataStream does not have any means to handle or recover from short-reads.
See also
setDevice(), device()
Definition at line 298 of file qdatastream.cpp.
 {
     dev = d;                                // set device
     owndev = false;
     byteorder = BigEndian;                        // default byte order
     ver = DefaultStreamVersion;
     noswap = QSysInfo::ByteOrder == QSysInfo::BigEndian;
     q_status = Ok;
 }
QDataStream() [3/4]
QDataStream::QDataStream (QByteArray * a, QIODevice::OpenMode mode)
Constructs a data stream that operates on a byte array, a.
The mode describes how the device is to be used.
Alternatively, you can use QDataStream(const QByteArray &) if you just want to read from a byte array.
Since QByteArray is not a QIODevice subclass, internally a QBuffer is created to wrap the byte array.
Definition at line 346 of file qdatastream.cpp.
 {
     QBuffer *buf = new QBuffer(a);
 #ifndef QT_NO_QOBJECT
     buf->blockSignals(true);
 #endif
     buf->open(flags);
     dev = buf;
     owndev = true;
     byteorder = BigEndian;
     ver = DefaultStreamVersion;
     noswap = QSysInfo::ByteOrder == QSysInfo::BigEndian;
     q_status = Ok;
 }
QDataStream() [4/4]
QDataStream::QDataStream (const QByteArray & a)
Constructs a read-only data stream that operates on byte array a.
Use QDataStream(QByteArray*, int) if you want to write to a byte array.
Since QByteArray is not a QIODevice subclass, internally a QBuffer is created to wrap the byte array.
Definition at line 369 of file qdatastream.cpp.
 {
     QBuffer *buf = new QBuffer;
 #ifndef QT_NO_QOBJECT
     buf->blockSignals(true);
 #endif
     buf->setData(a);
     buf->open(QIODevice::ReadOnly);
     dev = buf;
     owndev = true;
     byteorder = BigEndian;
     ver = DefaultStreamVersion;
     noswap = QSysInfo::ByteOrder == QSysInfo::BigEndian;
     q_status = Ok;
 }
~QDataStream()
QDataStream::~QDataStream () virtual
Destroys the data stream.
The destructor will not affect the current I/O device, unless it is an internal I/O device (e.g. a QBuffer) processing a QByteArray passed in the constructor, in which case the internal I/O device is destroyed.
Definition at line 394 of file qdatastream.cpp.
 {
     if (owndev)
         delete dev;
 }
Functions
atEnd()
bool QDataStream::atEnd () const
Returns true if the I/O device has reached the end position (end of the stream or file) or if there is no I/O device set; otherwise returns false.
See also
QIODevice::atEnd()
Definition at line 456 of file qdatastream.cpp.
Referenced by QMainWindowLayoutState::checkFormat(), QDeclarativeGestureArea::connectSignals(), QDeclarativeConnections::connectSignals(), QAbstractItemModel::decodeData(), QAbstractTableModel::dropMimeData(), QAbstractListModel::dropMimeData(), QStandardItemModel::dropMimeData(), QPicture::exec(), QRegion::exec(), QFontDatabasePrivate::loadFromCache(), QDeclarativeEngineDebugPrivate::message(), QDeclarativeEngineDebugService::messageReceived(), operator>>(), QSvgIconEngine::read(), QPixmapIconEngine::read(), QFileDialog::restoreState(), QMainWindowLayoutState::restoreState(), and QWSInputContext::translateIMEvent().
 {
     return dev ? dev->atEnd() : true;
 }
byteOrder()
QDataStream::ByteOrder QDataStream::byteOrder () const inline
Returns the current byte order setting – either BigEndian or LittleEndian.
See also
setByteOrder()
Definition at line 209 of file qdatastream.h.
Referenced by QUuid::operator<<(), operator<<(), QUuid::operator>>(), and operator>>().
 { return byteorder; }
device()
QIODevice * QDataStream::device () const inline
Returns the I/O device currently set, or 0 if no device is currently set.
See also
setDevice()
Definition at line 206 of file qdatastream.h.
Referenced by QPicture::exec(), operator<<(), operator>>(), QPicture::play(), qt_read_dibv5(), qt_write_dib(), qt_write_dibv5(), and read_dib_body().
 { return dev; }
floatingPointPrecision()
QDataStream::FloatingPointPrecision QDataStream::floatingPointPrecision () const
Returns the floating point precision of the data stream.
Since
4.6
See also
FloatingPointPrecision setFloatingPointPrecision()
Definition at line 468 of file qdatastream.cpp.
Referenced by operator<<(), and operator>>().
 {
     return d == 0 ? QDataStream::DoublePrecision : d->floatingPointPrecision;
 }
operator<<() [1/12]
QDataStream & QDataStream::operator<< (qint8 i)
Writes a signed byte, i, to the stream and returns a reference to the stream.
Definition at line 1071 of file qdatastream.cpp.
 {
     CHECK_STREAM_WRITE_PRECOND(*this)
     if (!dev->putChar(i))
         q_status = WriteFailed;
     return *this;
 }
operator<<() [2/12]
QDataStream & QDataStream::operator<< (quint8 i) inline
Writes an unsigned byte, i, to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 230 of file qdatastream.h.
 { return *this << qint8(i); }
operator<<() [3/12]
QDataStream & QDataStream::operator<< (qint16 i)
Writes a signed 16-bit integer, i, to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1101 of file qdatastream.cpp.
 {
     CHECK_STREAM_WRITE_PRECOND(*this)
     if (!noswap) {
         i = qbswap(i);
     }
     if (dev->write((char *)&i, sizeof(qint16)) != sizeof(qint16))
         q_status = WriteFailed;
     return *this;
 }
operator<<() [4/12]
QDataStream & QDataStream::operator<< (quint16 i) inline
Writes an unsigned 16-bit integer, i, to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 233 of file qdatastream.h.
 { return *this << qint16(i); }
operator<<() [5/12]
QDataStream & QDataStream::operator<< (qint32 i)
Writes a signed 32-bit integer, i, to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1122 of file qdatastream.cpp.
 {
     CHECK_STREAM_WRITE_PRECOND(*this)
     if (!noswap) {
         i = qbswap(i);
     }
     if (dev->write((char *)&i, sizeof(qint32)) != sizeof(qint32))
         q_status = WriteFailed;
     return *this;
 }
operator<<() [6/12]
QDataStream & QDataStream::operator<< (quint32 i) inline
Writes an unsigned integer, i, to the stream as a 32-bit unsigned integer (quint32).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns a reference to the stream.
Definition at line 236 of file qdatastream.h.
 { return *this << qint32(i); }
operator<<() [7/12]
QDataStream & QDataStream::operator<< (qint64 i)
Writes a signed 64-bit integer, i, to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1154 of file qdatastream.cpp.
 {
     CHECK_STREAM_WRITE_PRECOND(*this)
     if (version() < 6) {
         quint32 i1 = i & 0xffffffff;
         quint32 i2 = i >> 32;
         *this << i2 << i1;
     } else {
         if (!noswap) {
             i = qbswap(i);
         }
         if (dev->write((char *)&i, sizeof(qint64)) != sizeof(qint64))
             q_status = WriteFailed;
     }
     return *this;
 }
operator<<() [8/12]
QDataStream & QDataStream::operator<< (quint64 i) inline
Writes an unsigned 64-bit integer, i, to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 239 of file qdatastream.h.
 { return *this << qint64(i); }
operator<<() [9/12]
QDataStream & QDataStream::operator<< (bool i)
Writes a boolean value, i, to the stream.
Returns a reference to the stream.
Definition at line 1187 of file qdatastream.cpp.
 {
     CHECK_STREAM_WRITE_PRECOND(*this)
     if (!dev->putChar(qint8(i)))
         q_status = WriteFailed;
     return *this;
 }
operator<<() [10/12]
QDataStream & QDataStream::operator<< (float f)
Writes a floating point number, f, to the stream using the standard IEEE 754 format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns a reference to the stream.
See also
setFloatingPointPrecision()
Definition at line 1207 of file qdatastream.cpp.
 {
     if (version() >= QDataStream::Qt_4_6
         && floatingPointPrecision() == QDataStream::DoublePrecision) {
         *this << double(f);
         return *this;
     }
     CHECK_STREAM_WRITE_PRECOND(*this)
     float g = f;                                // fixes float-on-stack problem
     if (!noswap) {
         union {
             float val1;
             quint32 val2;
         } x;
         x.val1 = g;
         x.val2 = qbswap(x.val2);
         if (dev->write((char *)&x.val2, sizeof(float)) != sizeof(float))
             q_status = WriteFailed;
         return *this;
     }
     if (dev->write((char *)&g, sizeof(float)) != sizeof(float))
         q_status = WriteFailed;
     return *this;
 }
operator<<() [11/12]
QDataStream & QDataStream::operator<< (double f)
Writes a floating point number, f, to the stream using the standard IEEE 754 format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns a reference to the stream.
See also
setFloatingPointPrecision()
Definition at line 1248 of file qdatastream.cpp.
 {
     if (version() >= QDataStream::Qt_4_6
         && floatingPointPrecision() == QDataStream::SinglePrecision) {
         *this << float(f);
         return *this;
     }
     CHECK_STREAM_WRITE_PRECOND(*this)
 #ifndef Q_DOUBLE_FORMAT
     if (noswap) {
         if (dev->write((char *)&f, sizeof(double)) != sizeof(double))
             q_status = WriteFailed;
     } else {
         union {
             double val1;
             quint64 val2;
         } x;
         x.val1 = f;
         x.val2 = qbswap(x.val2);
         if (dev->write((char *)&x.val2, sizeof(double)) != sizeof(double))
             q_status = WriteFailed;
     }
 #else
     union {
         double val1;
         char val2[8];
     } x;
     x.val1 = f;
     char *p = x.val2;
     char b[8];
     if (noswap) {
         b[Q_DF(0)] = *p++;
         b[Q_DF(1)] = *p++;
         b[Q_DF(2)] = *p++;
         b[Q_DF(3)] = *p++;
         b[Q_DF(4)] = *p++;
         b[Q_DF(5)] = *p++;
         b[Q_DF(6)] = *p++;
         b[Q_DF(7)] = *p;
     } else {
         b[Q_DF(7)] = *p++;
         b[Q_DF(6)] = *p++;
         b[Q_DF(5)] = *p++;
         b[Q_DF(4)] = *p++;
         b[Q_DF(3)] = *p++;
         b[Q_DF(2)] = *p++;
         b[Q_DF(1)] = *p++;
         b[Q_DF(0)] = *p;
     }
     if (dev->write(b, 8) != 8)
         q_status = WriteFailed;
 #endif
     return *this;
 }
operator<<() [12/12]
QDataStream & QDataStream::operator<< (const char * s)
Writes the '\0'-terminated string s to the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The string is serialized using writeBytes().
Definition at line 1317 of file qdatastream.cpp.
 {
     if (!s) {
         *this << (quint32)0;
         return *this;
     }
     uint len = qstrlen(s) + 1;                        // also write null terminator
     *this << (quint32)len;                        // write length specifier
     writeRawData(s, len);
     return *this;
 }
operator>>() [1/12]
QDataStream & QDataStream::operator>> (qint8 & i)
Reads a signed byte from the stream into i, and returns a reference to the stream.
Definition at line 698 of file qdatastream.cpp.
 {
     i = 0;
     CHECK_STREAM_PRECOND(*this)
     char c;
     if (!dev->getChar(&c))
         setStatus(ReadPastEnd);
     else
         i = qint8(c);
     return *this;
 }
operator>>() [2/12]
QDataStream & QDataStream::operator>> (quint8 & i) inline
Reads an unsigned byte from the stream into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 218 of file qdatastream.h.
 { return *this >> reinterpret_cast<qint8&>(i); }
operator>>() [3/12]
QDataStream & QDataStream::operator>> (qint16 & i)
Reads a signed 16-bit integer from the stream into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 732 of file qdatastream.cpp.
 {
     i = 0;
     CHECK_STREAM_PRECOND(*this)
     if (dev->read((char *)&i, 2) != 2) {
         i = 0;
         setStatus(ReadPastEnd);
     } else {
         if (!noswap) {
             i = qbswap(i);
         }
     }
     return *this;
 }
operator>>() [4/12]
QDataStream & QDataStream::operator>> (quint16 & i) inline
Reads an unsigned 16-bit integer from the stream into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 221 of file qdatastream.h.
 { return *this >> reinterpret_cast<qint16&>(i); }
operator>>() [5/12]
QDataStream & QDataStream::operator>> (qint32 & i)
Reads a signed 32-bit integer from the stream into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 769 of file qdatastream.cpp.
 {
     i = 0;
     CHECK_STREAM_PRECOND(*this)
     if (dev->read((char *)&i, 4) != 4) {
         i = 0;
         setStatus(ReadPastEnd);
     } else {
         if (!noswap) {
             i = qbswap(i);
         }
     }
     return *this;
 }
operator>>() [6/12]
QDataStream & QDataStream::operator>> (quint32 & i) inline
Reads an unsigned 32-bit integer from the stream into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 224 of file qdatastream.h.
 { return *this >> reinterpret_cast<qint32&>(i); }
operator>>() [7/12]
QDataStream & QDataStream::operator>> (qint64 & i)
Reads a signed 64-bit integer from the stream into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 805 of file qdatastream.cpp.
 {
     i = qint64(0);
     CHECK_STREAM_PRECOND(*this)
     if (version() < 6) {
         quint32 i1, i2;
         *this >> i2 >> i1;
         i = ((quint64)i1 << 32) + i2;
     } else {
         if (dev->read((char *)&i, 8) != 8) {
             i = qint64(0);
             setStatus(ReadPastEnd);
         } else {
             if (!noswap) {
                 i = qbswap(i);
             }
         }
     }
     return *this;
 }
operator>>() [8/12]
QDataStream & QDataStream::operator>> (quint64 & i) inline
Reads an unsigned 64-bit integer from the stream, into i, and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 227 of file qdatastream.h.
 { return *this >> reinterpret_cast<qint64&>(i); }
operator>>() [9/12]
QDataStream & QDataStream::operator>> (bool & i)
Reads a boolean value from the stream into i.
Returns a reference to the stream.
Definition at line 830 of file qdatastream.cpp.
 {
     qint8 v;
     *this >> v;
     i = !!v;
     return *this;
 }
operator>>() [10/12]
QDataStream & QDataStream::operator>> (float & f)
Reads a floating point number from the stream into f, using the standard IEEE 754 format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns a reference to the stream.
See also
setFloatingPointPrecision()
Definition at line 851 of file qdatastream.cpp.
 {
     if (version() >= QDataStream::Qt_4_6
         && floatingPointPrecision() == QDataStream::DoublePrecision) {
         double d;
         *this >> d;
         f = d;
         return *this;
     }
     f = 0.0f;
     CHECK_STREAM_PRECOND(*this)
     if (dev->read((char *)&f, 4) != 4) {
         f = 0.0f;
         setStatus(ReadPastEnd);
     } else {
         if (!noswap) {
             union {
                 float val1;
                 quint32 val2;
             } x;
             x.val2 = qbswap(*reinterpret_cast<quint32 *>(&f));
             f = x.val1;
         }
     }
     return *this;
 }
operator>>() [11/12]
QDataStream & QDataStream::operator>> (double & f)
Reads a floating point number from the stream into f, using the standard IEEE 754 format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns a reference to the stream.
See also
setFloatingPointPrecision()
Definition at line 896 of file qdatastream.cpp.
 {
     if (version() >= QDataStream::Qt_4_6
         && floatingPointPrecision() == QDataStream::SinglePrecision) {
         float d;
         *this >> d;
         f = d;
         return *this;
     }
     f = 0.0;
     CHECK_STREAM_PRECOND(*this)
 #ifndef Q_DOUBLE_FORMAT
     if (dev->read((char *)&f, 8) != 8) {
         f = 0.0;
         setStatus(ReadPastEnd);
     } else {
         if (!noswap) {
             union {
                 double val1;
                 quint64 val2;
             } x;
             x.val2 = qbswap(*reinterpret_cast<quint64 *>(&f));
             f = x.val1;
         }
     }
 #else
     //non-standard floating point format
     union {
         double val1;
         char val2[8];
     } x;
     char *p = x.val2;
     char b[8];
     if (dev->read(b, 8) == 8) {
         if (noswap) {
             *p++ = b[Q_DF(0)];
             *p++ = b[Q_DF(1)];
             *p++ = b[Q_DF(2)];
             *p++ = b[Q_DF(3)];
             *p++ = b[Q_DF(4)];
             *p++ = b[Q_DF(5)];
             *p++ = b[Q_DF(6)];
             *p = b[Q_DF(7)];
         } else {
             *p++ = b[Q_DF(7)];
             *p++ = b[Q_DF(6)];
             *p++ = b[Q_DF(5)];
             *p++ = b[Q_DF(4)];
             *p++ = b[Q_DF(3)];
             *p++ = b[Q_DF(2)];
             *p++ = b[Q_DF(1)];
             *p = b[Q_DF(0)];
         }
         f = x.val1;
     } else {
         setStatus(ReadPastEnd);
     }
 #endif
     return *this;
 }
operator>>() [12/12]
QDataStream & QDataStream::operator>> (char *& s)
Reads the '\0'-terminated string s from the stream and returns a reference to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Space for the string is allocated using new – the caller must destroy it with delete[].
Definition at line 972 of file qdatastream.cpp.
 {
     uint len = 0;
     return readBytes(s, len);
 }
readBytes()
QDataStream & QDataStream::readBytes (char *& s, uint & l)
Reads the buffer s from the stream and returns a reference to the stream.
The buffer s is allocated using new. Destroy it with the delete[] operator.
The l parameter is set to the length of the buffer. If the string read is empty, l is set to 0 and s is set to a null pointer.
The serialization format is a quint32 length specifier first, then l bytes of data.
See also
readRawData(), writeBytes()
Definition at line 996 of file qdatastream.cpp.
Referenced by operator>>().
 {
     s = 0;
     l = 0;
     CHECK_STREAM_PRECOND(*this)
     quint32 len;
     *this >> len;
     if (len == 0)
         return *this;
     const quint32 Step = 1024 * 1024;
     quint32 allocated = 0;
     char *prevBuf = 0;
     char *curBuf = 0;
     do {
         int blockSize = qMin(Step, len - allocated);
         prevBuf = curBuf;
         curBuf = new char[allocated + blockSize + 1];
         if (prevBuf) {
             memcpy(curBuf, prevBuf, allocated);
             delete [] prevBuf;
         }
         if (dev->read(curBuf + allocated, blockSize) != blockSize) {
             delete [] curBuf;
             setStatus(ReadPastEnd);
             return *this;
         }
         allocated += blockSize;
     } while (allocated < len);
     s = curBuf;
     s[len] = '\0';
     l = (uint)len;
     return *this;
 }
readRawData()
int QDataStream::readRawData (char * s, int len)
Reads at most len bytes from the stream into s and returns the number of bytes read.
If an error occurs, this function returns -1.
The buffer s must be preallocated. The data is not encoded.
See also
readBytes(), QIODevice::read(), writeRawData()
Definition at line 1043 of file qdatastream.cpp.
Referenced by QPicturePrivate::checkFormat(), QUuid::operator>>(), operator>>(), QByteArray::operator>>(), qExtractServerTime(), qNtlmDecodePhase2(), and QMainWindowLayoutState::restoreState().
 {
     CHECK_STREAM_PRECOND(-1)
     return dev->read(s, len);
 }
resetStatus()
void QDataStream::resetStatus ()
Resets the status of the data stream.
See also
Status status() setStatus()
Definition at line 513 of file qdatastream.cpp.
Referenced by operator>>().
 {
     q_status = Ok;
 }
setByteOrder()
void QDataStream::setByteOrder (ByteOrder bo)
Sets the serialization byte order to bo.
The bo parameter can be QDataStream::BigEndian or QDataStream::LittleEndian.
The default setting is big endian. We recommend leaving this setting unless you have special requirements.
See also
byteOrder()
Definition at line 561 of file qdatastream.cpp.
Referenced by QWindowsMimeImage::convertFromMime(), QWindowsMimeImage::convertToMime(), QRegion::exec(), qEncodeNtlmv2Response(), qExtractServerTime(), qNtlmDecodePhase2(), qNtlmPhase1(), qNtlmPhase3(), QBmpHandler::read(), QBmpHandler::readHeader(), and QBmpHandler::write().
 {
     byteorder = bo;
     if (QSysInfo::ByteOrder == QSysInfo::BigEndian)
         noswap = (byteorder == BigEndian);
     else
         noswap = (byteorder == LittleEndian);
 }
setDevice()
void QDataStream::setDevice (QIODevice * d)
void QDataStream::setDevice(QIODevice *d)
Sets the I/O device to d, which can be 0 to unset to current I/O device.
See also
device()
Definition at line 419 of file qdatastream.cpp.
Referenced by QPicturePrivate::checkFormat(), QPicture::play(), QPacket::QPacket(), and unsetDevice().
 {
     if (owndev) {
         delete dev;
         owndev = false;
     }
     dev = d;
 }
setFloatingPointPrecision()
void QDataStream::setFloatingPointPrecision (QDataStream::FloatingPointPrecision precision)
Sets the floating point precision of the data stream to precision.
If the floating point precision is DoublePrecision and the version of the data stream is Qt_4_6 or higher, all floating point numbers will be written and read with 64-bit precision. If the floating point precision is SinglePrecision and the version is Qt_4_6 or higher, all floating point numbers will be written and read with 32-bit precision.
For versions prior to Qt_4_6, the precision of floating point numbers in the data stream depends on the stream operator called.
The default is DoublePrecision.
Warning
This property must be set to the same value on the object that writes and the object that reads the data stream.
Since
4.6
Definition at line 490 of file qdatastream.cpp.
Referenced by QTraceWindowSurface::~QTraceWindowSurface().
 {
     if (d == 0)
         d.reset(new QDataStreamPrivate());
     d->floatingPointPrecision = precision;
 }
setStatus()
void QDataStream::setStatus (Status status)
Sets the status of the data stream to the status given.
Subsequent calls to setStatus() are ignored until resetStatus() is called.
See also
Status status() resetStatus()
Definition at line 526 of file qdatastream.cpp.
Referenced by QMetaObjectBuilder::deserialize(), QVariant::load(), QUuid::operator<<(), operator>>(), operator>>(), QUuid::operator>>(), QHostAddress::operator>>(), QByteArray::operator>>(), readBytes(), and QDockAreaLayout::restoreState().
 {
     if (q_status == Ok)
         q_status = status;
 }
setVersion()
void QDataStream::setVersion (int v) inline
Sets the version number of the data serialization format to v.
You don't have to set a version if you are using the current version of Qt, but for your own custom binary formats we recommend that you do; see Versioning in the Detailed Description.
To accommodate new functionality, the datastream serialization format of some Qt classes has changed in some versions of Qt. If you want to read data that was created by an earlier version of Qt, or write data that can be read by a program that was compiled with an earlier version of Qt, use this function to modify the serialization format used by QDataStream.
Qt Version QDataStream Version
Qt 4.6 12
Qt 4.5 11
Qt 4.4 10
Qt 4.3 9
Qt 4.2 8
Qt 4.0, 4.1 7
Qt 3.3 6
Qt 3.1, 3.2 5
Qt 3.0 4
Qt 2.1, 2.2, 2.3 3
Qt 2.0 2
Qt 1.x 1
The Version enum provides symbolic constants for the different versions of Qt. For example:
QDataStream out(file);
out.setVersion(QDataStream::Qt_4_0);
See also
version(), Version
Definition at line 215 of file qdatastream.h.
Referenced by QPicturePrivate::checkFormat(), QRegion::exec(), QAxServerBase::Load(), QPicture::play(), QPacket::QPacket(), QWidget::restoreGeometry(), QWidget::saveGeometry(), and QSettingsPrivate::variantToString().
 { ver = v; }
skipRawData()
int QDataStream::skipRawData (int len)
Skips len bytes from the device.
Since
4.1
Returns the number of bytes actually skipped, or -1 on error.
This is equivalent to calling readRawData() on a buffer of length len and ignoring the buffer.
See also
QIODevice::seek()
Definition at line 1381 of file qdatastream.cpp.
Referenced by qExtractServerTime().
 {
     CHECK_STREAM_PRECOND(-1)
     if (dev->isSequential()) {
         char buf[4096];
         int sumRead = 0;
         while (len > 0) {
             int blockSize = qMin(len, (int)sizeof(buf));
             int n = dev->read(buf, blockSize);
             if (n == -1)
                 return -1;
             if (n == 0)
                 return sumRead;
             sumRead += n;
             len -= blockSize;
         }
         return sumRead;
     } else {
         qint64 pos = dev->pos();
         qint64 size = dev->size();
         if (pos + len > size)
             len = size - pos;
         if (!dev->seek(pos + len))
             return -1;
         return len;
     }
 }
status()
QDataStream::Status QDataStream::status () const
Returns the status of the data stream.
See also
Status setStatus() resetStatus()
Definition at line 503 of file qdatastream.cpp.
Referenced by QMetaObjectBuilder::deserialize(), QWSKbPrivate::loadKeymap(), operator>>(), qt_read_dibv5(), qt_write_dib(), qt_write_dibv5(), read_dib_fileheader(), read_dib_infoheader(), QHeaderView::restoreState(), QMainWindow::restoreState(), QToolBarAreaLayout::restoreState(), QDockAreaLayout::restoreState(), setStatus(), and QWSInputContext::translateIMEvent().
 {
     return q_status;
 }
unsetDevice()
void QDataStream::unsetDevice ()
Unsets the I/O device.
Use setDevice(0) instead.
Definition at line 437 of file qdatastream.cpp.
 {
     setDevice(0);
 }
version()
int QDataStream::version () const inline
Returns the version number of the data serialization format.
See also
setVersion(), Version
Definition at line 212 of file qdatastream.h.
Referenced by QRegion::exec(), initializeDb(), QVariant::load(), QFontDatabasePrivate::loadFromCache(), operator<<(), operator<<(), QByteArray::operator<<(), operator>>(), operator>>(), QPalette::operator>>(), qt_mix_colors(), QSvgIconEngine::read(), QTreeWidgetItem::read(), QAxServerBase::Save(), QVariant::save(), and QSvgIconEngine::write().
 { return ver; }
writeBytes()
QDataStream & QDataStream::writeBytes (const char * s, uint len)
Writes the length specifier len and the buffer s to the stream and returns a reference to the stream.
The len is serialized as a quint32, followed by len bytes from s. Note that the data is not encoded.
See also
writeRawData(), readBytes()
Definition at line 1340 of file qdatastream.cpp.
Referenced by operator<<(), QByteArray::operator<<(), and QTraceWindowSurface::~QTraceWindowSurface().
 {
     CHECK_STREAM_WRITE_PRECOND(*this)
     *this << (quint32)len;                        // write length specifier
     if (len)
         writeRawData(s, len);
     return *this;
 }
writeRawData()
int QDataStream::writeRawData (const char * s, int len)
Writes len bytes from s to the stream.
Returns the number of bytes actually written, or -1 on error. The data is not encoded.
See also
writeBytes(), QIODevice::write(), readRawData()
Definition at line 1358 of file qdatastream.cpp.
Referenced by operator<<(), operator<<(), QUuid::operator<<(), qEncodeNtlmv2Response(), qStreamNtlmBuffer(), QTcpServerConnection::send(), QmlOstPlugin::send(), QPdfEnginePrivate::write(), writeBytes(), QPdfEnginePrivate::writeCompressed(), and QPdfEnginePrivate::xprintf().
 {
     CHECK_STREAM_WRITE_PRECOND(-1)
     int ret = dev->write(s, len);
     if (ret != len)
         q_status = WriteFailed;
     return ret;
 }
Properties
byteorder
ByteOrder QDataStream::byteorder private
Definition at line 196 of file qdatastream.h.
Referenced by QDataStream(), and setByteOrder().
d
QScopedPointer<QDataStreamPrivate> QDataStream::d private
Definition at line 191 of file qdatastream.h.
Referenced by floatingPointPrecision(), operator>>(), QDataStream(), setDevice(), and setFloatingPointPrecision().
dev
QIODevice* QDataStream::dev private
Definition at line 193 of file qdatastream.h.
Referenced by atEnd(), operator<<(), operator>>(), QDataStream(), readBytes(), readRawData(), setDevice(), skipRawData(), writeRawData(), and ~QDataStream().
noswap
bool QDataStream::noswap private
Definition at line 195 of file qdatastream.h.
Referenced by operator<<(), operator>>(), QDataStream(), and setByteOrder().
owndev
bool QDataStream::owndev private
Definition at line 194 of file qdatastream.h.
Referenced by QDataStream(), setDevice(), and ~QDataStream().
q_status
Status QDataStream::q_status private
Definition at line 198 of file qdatastream.h.
Referenced by operator<<(), QDataStream(), resetStatus(), setStatus(), status(), and writeRawData().
ver
int QDataStream::ver private
Definition at line 197 of file qdatastream.h.
Referenced by QDataStream().
The documentation for this class was generated from the following files:
/src/corelib/io/qdatastream.h
/src/corelib/io/qdatastream.cpp