Qt 4.8: QFontDialogPrivate Class Reference
QFontDialogPrivate Class Reference
#include <qfontdialog_p.h>
Public Functions
void _q_familyHighlighted (int)
void _q_macRunNativeAppModalPanel ()
void _q_sizeChanged (const QString &)
This slot is called if the user changes the font size.
void _q_sizeHighlighted (int)
void _q_styleHighlighted (int)
void _q_updateSample ()
void _q_writingSystemHighlighted (int)
bool canBeNativeDialog ()
void closeCocoaFontPanel ()
void createNSFontPanelDelegate ()
void done (int result)
QFontDialog * fontDialog ()
bool hideCocoaFontPanel ()
void init ()
void mac_nativeDialogModalHelp ()
QFontDialogPrivate ()
void retranslateStrings ()
bool setVisible_sys (bool visible)
bool showCocoaFontPanel ()
void updateFamilies ()
void updateSampleFont (const QFont &newFont)
void updateSizes ()
Updates the contents of the "font size" list box.
void updateStyles ()
Public Functions inherited from QDialogPrivate
void hideDefault ()
Hides the default button indicator.
QDialogPrivate ()
void resetModalitySetByOpen ()
void setDefault (QPushButton *)
This function is called by the push button pushButton when it becomes the default button.
void setMainDefault (QPushButton *)
This function sets the default default push button to pushButton.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QFont getFont (bool *ok, const QFont &initial, QWidget *parent, const QString &title, QFontDialog::FontDialogOptions options)
static void setFont (void *delegate, const QFont &font)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QDialogButtonBox * buttonBox
QBoxLayout * buttonLayout
QComboBox * color
void * delegate
QGroupBox * effects
QBoxLayout * effectsLayout
QString family
QLabel * familyAccel
QLineEdit * familyEdit
QFontListView * familyList
QFontDatabase fdb
QByteArray memberToDisconnectOnClose
bool nativeDialogInUse
QFontDialog::FontDialogOptions opts
QPointer< QObject > receiverToDisconnectOnClose
QGroupBox * sample
QLineEdit * sampleEdit
QBoxLayout * sampleEditLayout
QBoxLayout * sampleLayout
QFont selectedFont
int size
QLabel * sizeAccel
QLineEdit * sizeEdit
QFontListView * sizeList
bool smoothScalable
QCheckBox * strikeout
QString style
QLabel * styleAccel
QLineEdit * styleEdit
QFontListView * styleList
QCheckBox * underline
QFontDatabase::WritingSystem writingSystem
QLabel * writingSystemAccel
QComboBox * writingSystemCombo
Public Variables inherited from QDialogPrivate
bool doShowExtension
QPointer< QEventLoop > eventLoop
QWidget * extension
QPoint lastRMBPress
QPointer< QPushButton > mainDef
QSize max
QSize min
Qt::Orientation orientation
int rescode
int resetModalityTo
QSizeGrip * resizer
QSize size
bool sizeGripEnabled
bool wasModalitySet
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static bool sharedFontPanelAvailable = true
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 74 of file qfontdialog_p.h.
Constructors and Destructors
QFontDialogPrivate()
QFontDialogPrivate::QFontDialogPrivate () inline
Definition at line 79 of file qfontdialog_p.h.
         : writingSystem(QFontDatabase::Any)
     { }
Functions
_q_familyHighlighted()
void QFontDialogPrivate::_q_familyHighlighted (int i)
Warning
This function is not part of the public interface.
Definition at line 708 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     family = familyList->text(i);
     familyEdit->setText(family);
     if (q->style()->styleHint(QStyle::SH_FontDialog_SelectAssociatedText, 0, q)
             && familyList->hasFocus())
         familyEdit->selectAll();
     updateStyles();
 }
_q_macRunNativeAppModalPanel()
void QFontDialogPrivate::_q_macRunNativeAppModalPanel ()
Definition at line 653 of file qfontdialog_mac.mm.
 {
     createNSFontPanelDelegate();
     QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *del = static_cast<QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *>(delegate);
     [del runApplicationModalPanel];
 }
_q_sizeChanged()
void QFontDialogPrivate::_q_sizeChanged (const QString & s)
This slot is called if the user changes the font size.
Warning
This function is not part of the public interface.
The size is passed in the s argument as a string.
Definition at line 766 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     // no need to check if the conversion is valid, since we have an QIntValidator in the size edit
     int size = s.toInt();
     if (this->size == size)
         return;
     this->size = size;
     if (sizeList->count() != 0) {
         int i;
         for (i = 0; i < sizeList->count() - 1; i++) {
             if (sizeList->text(i).toInt() >= this->size)
                 break;
         }
         sizeList->blockSignals(true);
         sizeList->setCurrentItem(i);
         sizeList->blockSignals(false);
     }
     _q_updateSample();
 }
_q_sizeHighlighted()
void QFontDialogPrivate::_q_sizeHighlighted (int index)
Warning
This function is not part of the public interface.
Definition at line 744 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     QString s = sizeList->text(index);
     sizeEdit->setText(s);
     if (q->style()->styleHint(QStyle::SH_FontDialog_SelectAssociatedText, 0, q)
             && sizeEdit->hasFocus())
         sizeEdit->selectAll();
     size = s.toInt();
     _q_updateSample();
 }
_q_styleHighlighted()
void QFontDialogPrivate::_q_styleHighlighted (int index)
Warning
This function is not part of the public interface.
Definition at line 725 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     QString s = styleList->text(index);
     styleEdit->setText(s);
     if (q->style()->styleHint(QStyle::SH_FontDialog_SelectAssociatedText, 0, q)
             && styleList->hasFocus())
         styleEdit->selectAll();
     style = s;
     updateSizes();
 }
_q_updateSample()
void QFontDialogPrivate::_q_updateSample ()
Definition at line 672 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     // compute new font
     int pSize = sizeEdit->text().toInt();
     QFont newFont(fdb.font(familyList->currentText(), style, pSize));
     newFont.setStrikeOut(strikeout->isChecked());
     newFont.setUnderline(underline->isChecked());
     if (familyList->currentText().isEmpty())
         sampleEdit->clear();
     updateSampleFont(newFont);
 }
_q_writingSystemHighlighted()
void QFontDialogPrivate::_q_writingSystemHighlighted (int index)
Warning
This function is not part of the public interface.
Definition at line 698 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     writingSystem = QFontDatabase::WritingSystem(index);
     sampleEdit->setText(fdb.writingSystemSample(writingSystem));
     updateFamilies();
 }
canBeNativeDialog()
bool QFontDialogPrivate::canBeNativeDialog ()
Definition at line 1076 of file qfontdialog.cpp.
 {
     Q_Q(QFontDialog);
     if (nativeDialogInUse)
         return true;
     if (q->testAttribute(Qt::WA_DontShowOnScreen))
         return false;
     if (opts & QFontDialog::DontUseNativeDialog)
         return false;
     QLatin1String staticName(QFontDialog::staticMetaObject.className());
     QLatin1String dynamicName(q->metaObject()->className());
     return (staticName == dynamicName);
 }
closeCocoaFontPanel()
void QFontDialogPrivate::closeCocoaFontPanel ()
Definition at line 491 of file qfontdialog_mac.mm.
 {
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *theDelegate = static_cast<QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *>(delegate);
     NSWindow *ourPanel = [theDelegate actualPanel];
     [ourPanel close];
     if ([theDelegate isAppModal])
         [ourPanel release];
     [theDelegate cleanUpAfterMyself];
     [theDelegate release];
     this->delegate = 0;
     sharedFontPanelAvailable = true;
 }
createNSFontPanelDelegate()
void QFontDialogPrivate::createNSFontPanelDelegate ()
Definition at line 540 of file qfontdialog_mac.mm.
 {
     if (delegate)
         return;
     sharedFontPanelAvailable = false;
     QMacCocoaAutoReleasePool pool;
     bool sharedFontPanelExisted = [NSFontPanel sharedFontPanelExists];
     NSFontPanel *sharedFontPanel = [NSFontPanel sharedFontPanel];
     [sharedFontPanel setHidesOnDeactivate:false];
     // hack to ensure that QCocoaApplication's validModesForFontPanel:
     // implementation is honored
     if (!sharedFontPanelExisted) {
         [sharedFontPanel makeKeyAndOrderFront:sharedFontPanel];
         [sharedFontPanel close];
     }
     NSPanel *ourPanel = 0;
     NSView *stolenContentView = 0;
     NSButton *okButton = 0;
     NSButton *cancelButton = 0;
     CGFloat dialogExtraWidth = 0.0;
     CGFloat dialogExtraHeight = 0.0;
     // compute dialogExtra{Width,Height}
     dialogExtraWidth = 2.0 * DialogSideMargin;
     dialogExtraHeight = DialogTopMargin + ButtonTopMargin + ButtonMinHeight + ButtonBottomMargin;
     // compute initial contents rectangle
     NSRect contentRect = [sharedFontPanel contentRectForFrameRect:[sharedFontPanel frame]];
     contentRect.size.width += dialogExtraWidth;
     contentRect.size.height += dialogExtraHeight;
     // create the new panel
     ourPanel = [[NSPanel alloc] initWithContentRect:contentRect
                 styleMask:StyleMask
                     backing:NSBackingStoreBuffered
                         defer:YES];
     [ourPanel setReleasedWhenClosed:YES];
     stolenContentView = [sharedFontPanel contentView];
     // steal the font panel's contents view
     [stolenContentView retain];
     [sharedFontPanel setContentView:0];
     {
         // create a new content view and add the stolen one as a subview
         NSRect frameRect = { { 0.0, 0.0 }, { 0.0, 0.0 } };
         NSView *ourContentView = [[NSView alloc] initWithFrame:frameRect];
         [ourContentView addSubview:stolenContentView];
         // create OK and Cancel buttons and add these as subviews
         okButton = macCreateButton("&OK", ourContentView);
         cancelButton = macCreateButton("Cancel", ourContentView);
         [ourPanel setContentView:ourContentView];
         [ourPanel setDefaultButtonCell:[okButton cell]];
     }
     // create the delegate and set it
     QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *del = [[QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) alloc] initWithFontPanel:sharedFontPanel
                                              stolenContentView:stolenContentView
                                                       okButton:okButton
                                                   cancelButton:cancelButton
                                                           priv:this
                                                     extraWidth:dialogExtraWidth
                                                    extraHeight:dialogExtraHeight];
     delegate = del;
     [ourPanel setDelegate:del];
     [[NSFontManager sharedFontManager] setDelegate:del];
 #ifdef QT_MAC_USE_COCOA
     [[NSFontManager sharedFontManager] setTarget:del];
 #endif
     setFont(del, q_func()->currentFont());
     {
         // hack to get correct initial layout
         NSRect frameRect = [ourPanel frame];
         frameRect.size.width += 1.0;
         [ourPanel setFrame:frameRect display:NO];
         frameRect.size.width -= 1.0;
         frameRect.size = [del windowWillResize:ourPanel toSize:frameRect.size];
         [ourPanel setFrame:frameRect display:NO];
         [ourPanel center];
     }
     [del setSubwindowStacking];
     NSString *title = @"Select font";
     [ourPanel setTitle:title];
 }
done()
void QFontDialogPrivate::done (int result) inline
Definition at line 144 of file qfontdialog_p.h.
 { q_func()->done(result); }
fontDialog()
QFontDialog* QFontDialogPrivate::fontDialog () inline
Definition at line 145 of file qfontdialog_p.h.
 { return q_func(); }
getFont()
QFont QFontDialogPrivate::getFont (bool * ok, const QFont & initial, QWidget * parent, const QString & title, QFontDialog::FontDialogOptions options) static
Definition at line 440 of file qfontdialog.cpp.
Referenced by QFontDialog::getFont(), and QFontDialogPrivate().
 {
     QFontDialog dlg(parent);
     dlg.setOptions(options);
     dlg.setCurrentFont(initial);
     if (!title.isEmpty())
         dlg.setWindowTitle(title);
     int ret = (dlg.exec() || (options & QFontDialog::NoButtons));
     if (ok)
         *ok = !!ret;
     if (ret) {
         return dlg.selectedFont();
     } else {
         return initial;
     }
 }
hideCocoaFontPanel()
bool QFontDialogPrivate::hideCocoaFontPanel ()
Definition at line 676 of file qfontdialog_mac.mm.
 {
     if (!delegate){
         // Nothing to do. We return false to leave the question
         // open regarding whether or not to go native:
         return false;
     } else {
         closeCocoaFontPanel();
         // Even when we hide it, we are still using a
         // native dialog, so return true:
         return true;
     }
 }
init()
void QFontDialogPrivate::init ()
Definition at line 182 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
 #ifdef Q_WS_MAC
     nativeDialogInUse = false;
     delegate = 0;
 #endif
     q->setSizeGripEnabled(true);
     q->setWindowTitle(QFontDialog::tr("Select Font"));
     // grid
     familyEdit = new QLineEdit(q);
     familyEdit->setReadOnly(true);
     familyList = new QFontListView(q);
     familyEdit->setFocusProxy(familyList);
     familyAccel = new QLabel(q);
 #ifndef QT_NO_SHORTCUT
     familyAccel->setBuddy(familyList);
 #endif
     familyAccel->setIndent(2);
     styleEdit = new QLineEdit(q);
     styleEdit->setReadOnly(true);
     styleList = new QFontListView(q);
     styleEdit->setFocusProxy(styleList);
     styleAccel = new QLabel(q);
 #ifndef QT_NO_SHORTCUT
     styleAccel->setBuddy(styleList);
 #endif
     styleAccel->setIndent(2);
     sizeEdit = new QLineEdit(q);
     sizeEdit->setFocusPolicy(Qt::ClickFocus);
     QIntValidator *validator = new QIntValidator(1, 512, q);
     sizeEdit->setValidator(validator);
     sizeList = new QFontListView(q);
     sizeAccel = new QLabel(q);
 #ifndef QT_NO_SHORTCUT
     sizeAccel->setBuddy(sizeEdit);
 #endif
     sizeAccel->setIndent(2);
     // effects box
     effects = new QGroupBox(q);
     QVBoxLayout *vbox = new QVBoxLayout(effects);
     strikeout = new QCheckBox(effects);
     vbox->addWidget(strikeout);
     underline = new QCheckBox(effects);
     vbox->addWidget(underline);
     sample = new QGroupBox(q);
     QHBoxLayout *hbox = new QHBoxLayout(sample);
     sampleEdit = new QLineEdit(sample);
     sampleEdit->setSizePolicy(QSizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored));
     sampleEdit->setAlignment(Qt::AlignCenter);
     // Note that the sample text is *not* translated with tr(), as the
     // characters used depend on the charset encoding.
     sampleEdit->setText(QLatin1String("AaBbYyZz"));
     hbox->addWidget(sampleEdit);
     writingSystemCombo = new QComboBox(q);
     writingSystemAccel = new QLabel(q);
 #ifndef QT_NO_SHORTCUT
     writingSystemAccel->setBuddy(writingSystemCombo);
 #endif
     writingSystemAccel->setIndent(2);
     size = 0;
     smoothScalable = false;
     QObject::connect(writingSystemCombo, SIGNAL(activated(int)), q, SLOT(_q_writingSystemHighlighted(int)));
     QObject::connect(familyList, SIGNAL(highlighted(int)), q, SLOT(_q_familyHighlighted(int)));
     QObject::connect(styleList, SIGNAL(highlighted(int)), q, SLOT(_q_styleHighlighted(int)));
     QObject::connect(sizeList, SIGNAL(highlighted(int)), q, SLOT(_q_sizeHighlighted(int)));
     QObject::connect(sizeEdit, SIGNAL(textChanged(QString)), q, SLOT(_q_sizeChanged(QString)));
     QObject::connect(strikeout, SIGNAL(clicked()), q, SLOT(_q_updateSample()));
     QObject::connect(underline, SIGNAL(clicked()), q, SLOT(_q_updateSample()));
     for (int i = 0; i < QFontDatabase::WritingSystemsCount; ++i) {
         QFontDatabase::WritingSystem ws = QFontDatabase::WritingSystem(i);
         QString writingSystemName = QFontDatabase::writingSystemName(ws);
         if (writingSystemName.isEmpty())
             break;
         writingSystemCombo->addItem(writingSystemName);
     }
     updateFamilies();
     if (familyList->count() != 0)
         familyList->setCurrentItem(0);
     // grid layout
     QGridLayout *mainGrid = new QGridLayout(q);
     int spacing = mainGrid->spacing();
     if (spacing >= 0) {     // uniform spacing
        mainGrid->setSpacing(0);
        mainGrid->setColumnMinimumWidth(1, spacing);
        mainGrid->setColumnMinimumWidth(3, spacing);
        int margin = 0;
        mainGrid->getContentsMargins(0, 0, 0, &margin);
        mainGrid->setRowMinimumHeight(3, margin);
        mainGrid->setRowMinimumHeight(6, 2);
        mainGrid->setRowMinimumHeight(8, margin);
     }
     mainGrid->addWidget(familyAccel, 0, 0);
     mainGrid->addWidget(familyEdit, 1, 0);
     mainGrid->addWidget(familyList, 2, 0);
     mainGrid->addWidget(styleAccel, 0, 2);
     mainGrid->addWidget(styleEdit, 1, 2);
     mainGrid->addWidget(styleList, 2, 2);
     mainGrid->addWidget(sizeAccel, 0, 4);
     mainGrid->addWidget(sizeEdit, 1, 4);
     mainGrid->addWidget(sizeList, 2, 4);
     mainGrid->setColumnStretch(0, 38);
     mainGrid->setColumnStretch(2, 24);
     mainGrid->setColumnStretch(4, 10);
     mainGrid->addWidget(effects, 4, 0);
     mainGrid->addWidget(sample, 4, 2, 4, 3);
     mainGrid->addWidget(writingSystemAccel, 5, 0);
     mainGrid->addWidget(writingSystemCombo, 7, 0);
     buttonBox = new QDialogButtonBox(q);
     mainGrid->addWidget(buttonBox, 9, 0, 1, 5);
     QPushButton *button
             = static_cast<QPushButton *>(buttonBox->addButton(QDialogButtonBox::Ok));
     QObject::connect(buttonBox, SIGNAL(accepted()), q, SLOT(accept()));
     button->setDefault(true);
     buttonBox->addButton(QDialogButtonBox::Cancel);
     QObject::connect(buttonBox, SIGNAL(rejected()), q, SLOT(reject()));
 #if defined(Q_WS_WINCE)
     q->resize(180, 120);
 #elif defined(Q_WS_S60)
     q->resize(QApplication::desktop()->availableGeometry(QCursor::pos()).size());
 #else
     q->resize(500, 360);
 #endif // Q_WS_WINCE
     sizeEdit->installEventFilter(q);
     familyList->installEventFilter(q);
     styleList->installEventFilter(q);
     sizeList->installEventFilter(q);
     familyList->setFocus();
     retranslateStrings();
 }
mac_nativeDialogModalHelp()
void QFontDialogPrivate::mac_nativeDialogModalHelp () virtual
Reimplemented from QDialogPrivate.
Definition at line 633 of file qfontdialog_mac.mm.
 {
     // Copied from QFileDialogPrivate
     // Do a queued meta-call to open the native modal dialog so it opens after the new
     // event loop has started to execute (in QDialog::exec). Using a timer rather than
     // a queued meta call is intentional to ensure that the call is only delivered when
     // [NSApp run] runs (timers are handeled special in cocoa). If NSApp is not
     // running (which is the case if e.g a top-most QEventLoop has been
     // interrupted, and the second-most event loop has not yet been reactivated (regardless
     // if [NSApp run] is still on the stack)), showing a native modal dialog will fail.
     if (nativeDialogInUse) {
         Q_Q(QFontDialog);
         QTimer::singleShot(1, q, SLOT(_q_macRunNativeAppModalPanel()));
     }
 }
retranslateStrings()
void QFontDialogPrivate::retranslateStrings ()
Definition at line 787 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     familyAccel->setText(QFontDialog::tr("&Font"));
     styleAccel->setText(QFontDialog::tr("Font st&yle"));
     sizeAccel->setText(QFontDialog::tr("&Size"));
 #ifndef Q_WS_S60
     // Removed the title due to lack of screen estate in small S60 screen.
     // The effects are descriptive without a title (strikeout, underline).
     effects->setTitle(QFontDialog::tr("Effects"));
 #endif
     strikeout->setText(QFontDialog::tr("Stri&keout"));
     underline->setText(QFontDialog::tr("&Underline"));
     sample->setTitle(QFontDialog::tr("Sample"));
     writingSystemAccel->setText(QFontDialog::tr("Wr&iting System"));
 }
setFont()
void QFontDialogPrivate::setFont (void * delegate, const QFont & font) static
Definition at line 505 of file qfontdialog_mac.mm.
Referenced by QFontDialog::setCurrentFont().
 {
     QMacCocoaAutoReleasePool pool;
     QFontEngine *fe = font.d->engineForScript(QUnicodeTables::Common);
     NSFontManager *mgr = [NSFontManager sharedFontManager];
     const NSFont *nsFont = 0;
 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
     if (qstrcmp(fe->name(), "CoreText") == 0) {
         nsFont = reinterpret_cast<const NSFont *>(static_cast<QCoreTextFontEngineMulti *>(fe)->ctfont);
     } else
 #endif
     {
         int weight = 5;
         NSFontTraitMask mask = 0;
         if (font.style() == QFont::StyleItalic) {
             mask |= NSItalicFontMask;
         }
         if (font.weight() == QFont::Bold) {
             weight = 9;
             mask |= NSBoldFontMask;
         }
         NSFontManager *mgr = [NSFontManager sharedFontManager];
         QFontInfo fontInfo(font);
         nsFont = [mgr fontWithFamily:qt_mac_QStringToNSString(fontInfo.family())
             traits:mask
             weight:weight
             size:fontInfo.pointSize()];
     }
     [mgr setSelectedFont:const_cast<NSFont *>(nsFont) isMultiple:NO];
     [static_cast<QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *>(delegate) setQtFont:font];
 }
setVisible_sys()
bool QFontDialogPrivate::setVisible_sys (bool visible)
Definition at line 689 of file qfontdialog_mac.mm.
 {
     Q_Q(QFontDialog);
     if (!visible == q->isHidden())
         return false;
     return visible ? showCocoaFontPanel() : hideCocoaFontPanel();
 }
showCocoaFontPanel()
bool QFontDialogPrivate::showCocoaFontPanel ()
Definition at line 660 of file qfontdialog_mac.mm.
 {
     if (!sharedFontPanelAvailable)
         return false;
     Q_Q(QFontDialog);
     QMacCocoaAutoReleasePool pool;
     createNSFontPanelDelegate();
     QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *del = static_cast<QT_MANGLE_NAMESPACE(QCocoaFontPanelDelegate) *>(delegate);
     if (qt_mac_is_macsheet(q))
         [del showWindowModalSheet:q->parentWidget()];
     else
         [del showModelessPanel];
     return true;
 }
updateFamilies()
void QFontDialogPrivate::updateFamilies ()
Definition at line 512 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     enum match_t { MATCH_NONE = 0, MATCH_LAST_RESORT = 1, MATCH_APP = 2, MATCH_FAMILY = 3 };
     QStringList familyNames = fdb.families(writingSystem);
     familyList->model()->setStringList(familyNames);
     QString foundryName1, familyName1, foundryName2, familyName2;
     int bestFamilyMatch = -1;
     match_t bestFamilyType = MATCH_NONE;
     QFont f;
     // ##### do the right thing for a list of family names in the font.
     QFontDatabase::parseFontName(family, foundryName1, familyName1);
     QStringList::const_iterator it = familyNames.constBegin();
     int i = 0;
     for(; it != familyNames.constEnd(); ++it, ++i) {
         QFontDatabase::parseFontName(*it, foundryName2, familyName2);
         //try to match...
         if (familyName1 == familyName2) {
             bestFamilyType = MATCH_FAMILY;
             if (foundryName1 == foundryName2) {
                 bestFamilyMatch = i;
                 break;
             }
             if (bestFamilyMatch < MATCH_FAMILY)
                 bestFamilyMatch = i;
         }
         //and try some fall backs
         match_t type = MATCH_NONE;
         if (bestFamilyType <= MATCH_NONE && familyName2 == f.lastResortFamily())
             type = MATCH_LAST_RESORT;
         if (bestFamilyType <= MATCH_LAST_RESORT && familyName2 == f.family())
             type = MATCH_APP;
         // ### add fallback for writingSystem
         if (type != MATCH_NONE) {
             bestFamilyType = type;
             bestFamilyMatch = i;
         }
     }
     if (i != -1 && bestFamilyType != MATCH_NONE)
         familyList->setCurrentItem(bestFamilyMatch);
     else
         familyList->setCurrentItem(0);
     familyEdit->setText(familyList->currentText());
     if (q->style()->styleHint(QStyle::SH_FontDialog_SelectAssociatedText, 0, q)
             && familyList->hasFocus())
         familyEdit->selectAll();
     updateStyles();
 }
updateSampleFont()
void QFontDialogPrivate::updateSampleFont (const QFont & newFont)
Definition at line 686 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     if (newFont != sampleEdit->font()) {
         sampleEdit->setFont(newFont);
         emit q->currentFontChanged(newFont);
     }
 }
updateSizes()
void QFontDialogPrivate::updateSizes ()
Updates the contents of the "font size" list box.
Warning
This function is not part of the public interface. This function can be reimplemented if you have special requirements.
Definition at line 636 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     if (!familyList->currentText().isEmpty()) {
         QList<int> sizes = fdb.pointSizes(familyList->currentText(), styleList->currentText());
         int i = 0;
         int current = -1;
         QStringList str_sizes;
         for(QList<int>::const_iterator it = sizes.constBegin(); it != sizes.constEnd(); ++it) {
             str_sizes.append(QString::number(*it));
             if (current == -1 && *it >= size)
                 current = i;
             ++i;
         }
         sizeList->model()->setStringList(str_sizes);
         if (current == -1) {
             // we request a size bigger than the ones in the list, select the biggest one
             current = sizeList->count() - 1;
         }
         sizeList->setCurrentItem(current);
         sizeEdit->blockSignals(true);
         sizeEdit->setText((smoothScalable ? QString::number(size) : sizeList->currentText()));
         if (q->style()->styleHint(QStyle::SH_FontDialog_SelectAssociatedText, 0, q)
                 && sizeList->hasFocus())
             sizeEdit->selectAll();
         sizeEdit->blockSignals(false);
     } else {
         sizeEdit->clear();
     }
     _q_updateSample();
 }
updateStyles()
void QFontDialogPrivate::updateStyles ()
Definition at line 576 of file qfontdialog.cpp.
Referenced by QFontDialogPrivate().
 {
     Q_Q(QFontDialog);
     QStringList styles = fdb.styles(familyList->currentText());
     styleList->model()->setStringList(styles);
     if (styles.isEmpty()) {
         styleEdit->clear();
         smoothScalable = false;
     } else {
         if (!style.isEmpty()) {
             bool found = false;
             bool first = true;
             QString cstyle = style;
         redo:
             for (int i = 0; i < (int)styleList->count(); i++) {
                 if (cstyle == styleList->text(i)) {
                      styleList->setCurrentItem(i);
                      found = true;
                      break;
                  }
             }
             if (!found && first) {
                 if (cstyle.contains(QLatin1String("Italic"))) {
                     cstyle.replace(QLatin1String("Italic"), QLatin1String("Oblique"));
                     first = false;
                     goto redo;
                 } else if (cstyle.contains(QLatin1String("Oblique"))) {
                     cstyle.replace(QLatin1String("Oblique"), QLatin1String("Italic"));
                     first = false;
                     goto redo;
                 }
             }
             if (!found)
                 styleList->setCurrentItem(0);
         } else {
             styleList->setCurrentItem(0);
         }
         styleEdit->setText(styleList->currentText());
         if (q->style()->styleHint(QStyle::SH_FontDialog_SelectAssociatedText, 0, q)
                 && styleList->hasFocus())
             styleEdit->selectAll();
         smoothScalable = fdb.isSmoothlyScalable(familyList->currentText(), styleList->currentText());
     }
     updateSizes();
 }
Properties
buttonBox
QDialogButtonBox* QFontDialogPrivate::buttonBox
Definition at line 128 of file qfontdialog_p.h.
buttonLayout
QBoxLayout* QFontDialogPrivate::buttonLayout
Definition at line 123 of file qfontdialog_p.h.
color
QComboBox* QFontDialogPrivate::color
Definition at line 115 of file qfontdialog_p.h.
delegate
void* QFontDialogPrivate::delegate
Definition at line 147 of file qfontdialog_p.h.
effects
QGroupBox* QFontDialogPrivate::effects
Definition at line 112 of file qfontdialog_p.h.
effectsLayout
QBoxLayout* QFontDialogPrivate::effectsLayout
Definition at line 124 of file qfontdialog_p.h.
family
QString QFontDialogPrivate::family
Definition at line 131 of file qfontdialog_p.h.
familyAccel
QLabel* QFontDialogPrivate::familyAccel
Definition at line 100 of file qfontdialog_p.h.
familyEdit
QLineEdit* QFontDialogPrivate::familyEdit
Definition at line 101 of file qfontdialog_p.h.
familyList
QFontListView* QFontDialogPrivate::familyList
Definition at line 102 of file qfontdialog_p.h.
fdb
QFontDatabase QFontDialogPrivate::fdb
Definition at line 130 of file qfontdialog_p.h.
memberToDisconnectOnClose
QByteArray QFontDialogPrivate::memberToDisconnectOnClose
Definition at line 139 of file qfontdialog_p.h.
nativeDialogInUse
bool QFontDialogPrivate::nativeDialogInUse
Definition at line 149 of file qfontdialog_p.h.
opts
QFontDialog::FontDialogOptions QFontDialogPrivate::opts
Definition at line 137 of file qfontdialog_p.h.
receiverToDisconnectOnClose
QPointer<QObject> QFontDialogPrivate::receiverToDisconnectOnClose
Definition at line 138 of file qfontdialog_p.h.
sample
QGroupBox* QFontDialogPrivate::sample
Definition at line 117 of file qfontdialog_p.h.
sampleEdit
QLineEdit* QFontDialogPrivate::sampleEdit
Definition at line 118 of file qfontdialog_p.h.
sampleEditLayout
QBoxLayout* QFontDialogPrivate::sampleEditLayout
Definition at line 126 of file qfontdialog_p.h.
sampleLayout
QBoxLayout* QFontDialogPrivate::sampleLayout
Definition at line 125 of file qfontdialog_p.h.
selectedFont
QFont QFontDialogPrivate::selectedFont
Definition at line 136 of file qfontdialog_p.h.
sharedFontPanelAvailable
bool QFontDialogPrivate::sharedFontPanelAvailable = true static
Definition at line 158 of file qfontdialog_p.h.
Referenced by QFontDialog::setOptions().
size
int QFontDialogPrivate::size
Definition at line 134 of file qfontdialog_p.h.
sizeAccel
QLabel* QFontDialogPrivate::sizeAccel
Definition at line 108 of file qfontdialog_p.h.
sizeEdit
QLineEdit* QFontDialogPrivate::sizeEdit
Definition at line 109 of file qfontdialog_p.h.
sizeList
QFontListView* QFontDialogPrivate::sizeList
Definition at line 110 of file qfontdialog_p.h.
smoothScalable
bool QFontDialogPrivate::smoothScalable
Definition at line 135 of file qfontdialog_p.h.
strikeout
QCheckBox* QFontDialogPrivate::strikeout
Definition at line 113 of file qfontdialog_p.h.
style
QString QFontDialogPrivate::style
Definition at line 133 of file qfontdialog_p.h.
styleAccel
QLabel* QFontDialogPrivate::styleAccel
Definition at line 104 of file qfontdialog_p.h.
styleEdit
QLineEdit* QFontDialogPrivate::styleEdit
Definition at line 105 of file qfontdialog_p.h.
styleList
QFontListView* QFontDialogPrivate::styleList
Definition at line 106 of file qfontdialog_p.h.
underline
QCheckBox* QFontDialogPrivate::underline
Definition at line 114 of file qfontdialog_p.h.
writingSystem
QFontDatabase::WritingSystem QFontDialogPrivate::writingSystem
Definition at line 132 of file qfontdialog_p.h.
writingSystemAccel
QLabel* QFontDialogPrivate::writingSystemAccel
Definition at line 120 of file qfontdialog_p.h.
writingSystemCombo
QComboBox* QFontDialogPrivate::writingSystemCombo
Definition at line 121 of file qfontdialog_p.h.
The documentation for this class was generated from the following files:
/src/gui/dialogs/qfontdialog_p.h
/src/gui/dialogs/qfontdialog.cpp
/src/gui/dialogs/qfontdialog_mac.mm