Qt 4.8: QTextOption Class Reference
QTextOption Class Reference
The QTextOption class provides a description of general rich text properties.
#include <qtextoption.h>
Classes
class Tab
Each tab definition is represented by this struct.
Public Types
enum Flag {
ShowTabsAndSpaces = 0x1, ShowLineAndParagraphSeparators = 0x2, AddSpaceForLineAndParagraphSeparators = 0x4, SuppressColors = 0x8,
IncludeTrailingSpaces = 0x80000000
}
enum TabType { LeftTab, RightTab, CenterTab, DelimiterTab }
enum WrapMode {
NoWrap, WordWrap, ManualWrap, WrapAnywhere,
WrapAtWordBoundaryOrAnywhere
}
This enum describes how text is wrapped in a document.
Public Functions
Qt::Alignment alignment () const
Returns the text alignment defined by the option.
Flags flags () const
Returns the flags associated with the option.
QTextOption & operator= (const QTextOption &o)
Returns true if the text option is the same as the other text option; otherwise returns false.
QTextOption ()
Constructs a text option with default properties for text.
QTextOption (Qt::Alignment alignment)
Constructs a text option with the given alignment for text.
QTextOption (const QTextOption &o)
Construct a copy of the other text option.
void setAlignment (Qt::Alignment alignment)
Sets the option's text alignment to the specified alignment.
void setFlags (Flags flags)
Sets the flags associated with the option to the given flags.
void setTabArray (QList< qreal > tabStops)
Sets the tab positions for the text layout to those specified by tabStops.
void setTabs (QList< Tab > tabStops)
Sets the tab positions for the text layout to those specified by tabStops.
void setTabStop (qreal tabStop)
Sets the default distance in device units between tab stops to the value specified by tabStop.
void setTextDirection (Qt::LayoutDirection aDirection)
Sets the direction of the text layout defined by the option to the given direction.
void setUseDesignMetrics (bool b)
If enable is true then the layout will use design metrics; otherwise it will use the metrics of the paint device (which is the default behavior).
void setWrapMode (WrapMode wrap)
Sets the option's text wrap mode to the given mode.
QList< qreal > tabArray () const
Returns a list of tab positions defined for the text layout.
QList< Tab > tabs () const
Returns a list of tab positions defined for the text layout.
qreal tabStop () const
Returns the distance in device units between tab stops.
Qt::LayoutDirection textDirection () const
Returns the direction of the text layout defined by the option.
bool useDesignMetrics () const
Returns true if the layout uses design rather than device metrics; otherwise returns false.
WrapMode wrapMode () const
Returns the text wrap mode defined by the option.
~QTextOption ()
Destroys the text option.
Properties
uint align: 8
QTextOptionPrivate * d
uint design: 1
uint direction: 2
uint f
qreal tab
uint unused: 18
uint wordWrap: 4
Detailed Description
The QTextOption class provides a description of general rich text properties.
Note
This class or function is reentrant.
QTextOption is used to encapsulate common rich text properties in a single object. It contains information about text alignment, layout direction, word wrapping, and other standard properties associated with text rendering and layout.
See also
QTextEdit, QTextDocument, QTextCursor
Definition at line 59 of file qtextoption.h.
Enumerations
Flag
enum QTextOption::Flag
IncludeTrailingSpaces When this option is set, QTextLine::naturalTextWidth() and naturalTextRect() will return a value that includes the width of trailing spaces in the text; otherwise this width is excluded.
ShowTabsAndSpaces Visualize spaces with little dots, and tabs with little arrows.
ShowLineAndParagraphSeparators Visualize line and paragraph separators with appropriate symbol characters.
AddSpaceForLineAndParagraphSeparators While determining the line-break positions take into account the space added for drawing a separator character.
SuppressColors Suppress all color changes in the character formats (except the main selection).
Enumerator
ShowTabsAndSpaces
ShowLineAndParagraphSeparators
AddSpaceForLineAndParagraphSeparators
SuppressColors
IncludeTrailingSpaces
Definition at line 112 of file qtextoption.h.
               {
         ShowTabsAndSpaces = 0x1,
         ShowLineAndParagraphSeparators = 0x2,
         AddSpaceForLineAndParagraphSeparators = 0x4,
         SuppressColors = 0x8,
         IncludeTrailingSpaces = 0x80000000
     };
TabType
enum QTextOption::TabType
Since
4.4
This enum holds the different types of tabulator
LeftTab A left-tab
RightTab A right-tab
CenterTab A centered-tab
DelimiterTab A tab stopping at a certain delimiter-character
Enumerator
LeftTab
RightTab
CenterTab
DelimiterTab
Definition at line 62 of file qtextoption.h.
                  {
         LeftTab,
         RightTab,
         CenterTab,
         DelimiterTab
     };
WrapMode
enum QTextOption::WrapMode
This enum describes how text is wrapped in a document.
NoWrap Text is not wrapped at all.
WordWrap Text is wrapped at word boundaries.
ManualWrap Same as QTextOption::NoWrap
WrapAnywhere Text can be wrapped at any point on a line, even if it occurs in the middle of a word.
WrapAtWordBoundaryOrAnywhere If possible, wrapping occurs at a word boundary; otherwise it will occur at the appropriate point on the line, even in the middle of a word.
Enumerator
NoWrap
WordWrap
ManualWrap
WrapAnywhere
WrapAtWordBoundaryOrAnywhere
Definition at line 102 of file qtextoption.h.
                   {
         NoWrap,
         WordWrap,
         ManualWrap,
         WrapAnywhere,
         WrapAtWordBoundaryOrAnywhere
     };
Constructors and Destructors
QTextOption() [1/3]
QTextOption::QTextOption ()
Constructs a text option with default properties for text.
The text alignment property is set to Qt::AlignLeft. The word wrap property is set to QTextOption::WordWrap. The using of design metrics flag is set to false.
Definition at line 59 of file qtextoption.cpp.
     : align(Qt::AlignLeft),
       wordWrap(QTextOption::WordWrap),
       design(false),
       unused(0),
       f(0),
       tab(-1),
       d(0)
 {
     direction = Qt::LayoutDirectionAuto;
 }
QTextOption() [2/3]
QTextOption::QTextOption (Qt::Alignment alignment)
Constructs a text option with the given alignment for text.
The word wrap property is set to QTextOption::WordWrap. The using of design metrics flag is set to false.
Definition at line 76 of file qtextoption.cpp.
     : align(alignment),
       wordWrap(QTextOption::WordWrap),
       design(false),
       unused(0),
       f(0),
       tab(-1),
       d(0)
 {
     direction = QApplication::layoutDirection();
 }
~QTextOption()
QTextOption::~QTextOption ()
Destroys the text option.
Definition at line 91 of file qtextoption.cpp.
 {
     delete d;
 }
QTextOption() [3/3]
QTextOption::QTextOption (const QTextOption & o)
Construct a copy of the other text option.
Definition at line 104 of file qtextoption.cpp.
     : align(o.align),
       wordWrap(o.wordWrap),
       design(o.design),
       direction(o.direction),
       unused(o.unused),
       f(o.f),
       tab(o.tab),
       d(0)
 {
     if (o.d)
         d = new QTextOptionPrivate(*o.d);
 }
Functions
alignment()
Qt::Alignment QTextOption::alignment () const inline
Returns the text alignment defined by the option.
See also
setAlignment()
Definition at line 97 of file qtextoption.h.
Referenced by QTextEngine::alignLine(), QTextEngine::justify(), QTextLine::layout_helper(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), qt_format_text(), and QDeclarativeTextEditPrivate::updateDefaultTextOption().
 { return Qt::Alignment(align); }
flags()
Flags QTextOption::flags () const inline
Returns the flags associated with the option.
See also
setFlags()
Definition at line 121 of file qtextoption.h.
Referenced by QTextLine::draw(), QTextEngine::itemize(), QTextLine::layout_helper(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QTextEngine::leadingSpaceWidth(), qt_format_text(), QTextLine::textLength(), and QTextEngine::validate().
 { return Flags(f); }
operator=()
QTextOption & QTextOption::operator= (const QTextOption & o)
Returns true if the text option is the same as the other text option; otherwise returns false.
Definition at line 127 of file qtextoption.cpp.
 {
     if (this == &o)
         return *this;
     QTextOptionPrivate* dNew = 0;
     if (o.d)
         dNew = new QTextOptionPrivate(*o.d);
     delete d;
     d = dNew;
     align = o.align;
     wordWrap = o.wordWrap;
     design = o.design;
     direction = o.direction;
     unused = o.unused;
     f = o.f;
     tab = o.tab;
     return *this;
 }
setAlignment()
void QTextOption::setAlignment (Qt::Alignment alignment) inline
Sets the option's text alignment to the specified alignment.
See also
alignment()
Definition at line 148 of file qtextoption.h.
Referenced by QPainter::drawText(), QLabelPrivate::ensureTextLayouted(), QTextDocumentLayoutPrivate::layoutBlock(), qt_format_text(), QDeclarativeTextPrivate::setupTextLayout(), QDeclarativeTextEditPrivate::updateDefaultTextOption(), QDeclarativeTextPrivate::updateSize(), and QCommonStylePrivate::viewItemDrawText().
 { align = aalignment; }
setFlags()
void QTextOption::setFlags (Flags flags) inline
Sets the flags associated with the option to the given flags.
See also
flags()
Definition at line 151 of file qtextoption.h.
Referenced by QDeclarativeTextPrivate::textDocumentImage(), and QLineControl::updateDisplayText().
 { f = aflags; }
setTabArray()
void QTextOption::setTabArray (QList< qreal > tabStops)
Sets the tab positions for the text layout to those specified by tabStops.
See also
tabArray(), setTabStop(), setTabs()
Definition at line 154 of file qtextoption.cpp.
Referenced by qt_format_text().
 {
     if (!d)
         d = new QTextOptionPrivate;
     QList<QTextOption::Tab> tabs;
     QTextOption::Tab tab;
     foreach (qreal pos, tabStops) {
         tab.position = pos;
         tabs.append(tab);
     }
     d->tabStops = tabs;
 }
setTabs()
void QTextOption::setTabs (QList< Tab > tabStops)
Sets the tab positions for the text layout to those specified by tabStops.
Since
4.4
See also
tabStops()
Definition at line 177 of file qtextoption.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock().
 {
     if (!d)
         d = new QTextOptionPrivate;
     d->tabStops = tabStops;
 }
setTabStop()
void QTextOption::setTabStop (qreal tabStop) inline
Sets the default distance in device units between tab stops to the value specified by tabStop.
See also
tabStop(), setTabArray(), setTabs(), tabs()
Definition at line 154 of file qtextoption.h.
Referenced by qt_format_text(), QTextDocumentPrivate::QTextDocumentPrivate(), QPlainTextEdit::setTabStopWidth(), and QTextEdit::setTabStopWidth().
 { tab = atabStop; }
setTextDirection()
void QTextOption::setTextDirection (Qt::LayoutDirection direction) inline
Sets the direction of the text layout defined by the option to the given direction.
See also
textDirection()
Definition at line 99 of file qtextoption.h.
Referenced by QTextDocumentLayoutPrivate::drawListItem(), QPainter::drawText(), QTextDocumentLayoutPrivate::layoutBlock(), qt_format_text(), QLineControl::updateDisplayText(), and QCommonStylePrivate::viewItemDrawText().
 { this->direction = aDirection; }
setUseDesignMetrics()
void QTextOption::setUseDesignMetrics (bool enable) inline
If enable is true then the layout will use design metrics; otherwise it will use the metrics of the paint device (which is the default behavior).
See also
useDesignMetrics()
Definition at line 132 of file qtextoption.h.
 { design = b; }
setWrapMode()
void QTextOption::setWrapMode (WrapMode wrap) inline
Sets the option's text wrap mode to the given mode.
Definition at line 109 of file qtextoption.h.
Referenced by QSvgText::draw(), QPlastiqueStyle::drawComplexControl(), QLabelPrivate::ensureTextLayouted(), QTextLine::layout_helper(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutTable(), QBalloonTip::QBalloonTip(), qt_format_text(), QTextDocumentPrivate::QTextDocumentPrivate(), QDeclarativeTextPrivate::setupTextLayout(), QDeclarativeTextEditPrivate::updateDefaultTextOption(), QTextEditPrivate::updateDefaultTextOption(), QPlainTextEditPrivate::updateDefaultTextOption(), QDeclarativeTextPrivate::updateSize(), QMessageBoxPrivate::updateSize(), QCommonStylePrivate::viewItemDrawText(), and QCommonStylePrivate::viewItemSize().
 { wordWrap = wrap; }
tabArray()
QList< qreal > QTextOption::tabArray () const
Returns a list of tab positions defined for the text layout.
See also
setTabArray(), tabStop()
Definition at line 189 of file qtextoption.cpp.
Referenced by qt_format_text().
 {
     if (!d)
         return QList<qreal>();
     QList<qreal> answer;
     QList<QTextOption::Tab>::ConstIterator iter = d->tabStops.constBegin();
     while(iter != d->tabStops.constEnd()) {
         answer.append( (*iter).position);
         ++iter;
     }
     return answer;
 }
tabs()
QList< QTextOption::Tab > QTextOption::tabs () const
Returns a list of tab positions defined for the text layout.
Since
4.4
See also
tabStop(), setTabs(), setTabStop()
Definition at line 204 of file qtextoption.cpp.
Referenced by QTextEngine::calculateTabWidth(), qt_format_text(), and setTabArray().
 {
     if (!d)
         return QList<QTextOption::Tab>();
     return d->tabStops;
 }
tabStop()
qreal QTextOption::tabStop () const inline
Returns the distance in device units between tab stops.
Convenient function for the above method
See also
setTabStop(), tabArray(), setTabs(), tabs()
Definition at line 124 of file qtextoption.h.
Referenced by QTextEngine::calculateTabWidth(), qt_format_text(), QPlainTextEdit::setTabStopWidth(), and QTextEdit::setTabStopWidth().
 { return tab; }
textDirection()
Qt::LayoutDirection QTextOption::textDirection () const inline
Returns the direction of the text layout defined by the option.
See also
setTextDirection()
Definition at line 100 of file qtextoption.h.
Referenced by QTextEngine::isRightToLeft(), QTextEngine::itemize(), qt_format_text(), and QLabelPrivate::textDirection().
 { return Qt::LayoutDirection(direction); }
useDesignMetrics()
bool QTextOption::useDesignMetrics () const inline
Returns true if the layout uses design rather than device metrics; otherwise returns false.
See also
setUseDesignMetrics()
Definition at line 133 of file qtextoption.h.
 { return design; }
wrapMode()
WrapMode QTextOption::wrapMode () const inline
Returns the text wrap mode defined by the option.
See also
setWrapMode()
Definition at line 110 of file qtextoption.h.
Referenced by QTextLine::cursorToX(), QTextLine::layout_helper(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutTable(), qt_format_text(), QDeclarativeTextEditPrivate::updateDefaultTextOption(), QTextEditPrivate::updateDefaultTextOption(), and QPlainTextEditPrivate::updateDefaultTextOption().
 { return static_cast<WrapMode>(wordWrap); }
Properties
align
uint QTextOption::align private
Definition at line 136 of file qtextoption.h.
Referenced by operator=().
d
QTextOptionPrivate* QTextOption::d private
Definition at line 143 of file qtextoption.h.
Referenced by operator=(), QTextOption(), setTabArray(), setTabs(), tabArray(), tabs(), and ~QTextOption().
design
uint QTextOption::design private
Definition at line 138 of file qtextoption.h.
Referenced by operator=().
direction
uint QTextOption::direction private
Definition at line 139 of file qtextoption.h.
Referenced by operator=(), and QTextOption().
f
uint QTextOption::f private
Definition at line 141 of file qtextoption.h.
Referenced by operator=().
tab
qreal QTextOption::tab private
Definition at line 142 of file qtextoption.h.
Referenced by operator=(), and setTabArray().
unused
uint QTextOption::unused private
Definition at line 140 of file qtextoption.h.
Referenced by operator=().
wordWrap
uint QTextOption::wordWrap private
Definition at line 137 of file qtextoption.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
/src/gui/text/qtextoption.h
/src/gui/text/qtextoption.cpp