Qt 4.8: QSslSocket Class Reference
QSslSocket Class Reference
The QSslSocket class provides an SSL encrypted socket for both clients and servers.
#include <qsslsocket.h>
Public Types
enum PeerVerifyMode { VerifyNone, QueryPeer, VerifyPeer, AutoVerifyPeer }
Describes the peer verification modes for QSslSocket.
enum SslMode { UnencryptedMode, SslClientMode, SslServerMode }
Describes the connection modes available for QSslSocket.
Public Types inherited from QAbstractSocket
enum NetworkLayerProtocol { IPv4Protocol, IPv6Protocol, UnknownNetworkLayerProtocol = -1 }
This enum describes the network layer protocol values used in Qt.
enum SocketError {
ConnectionRefusedError, RemoteHostClosedError, HostNotFoundError, SocketAccessError,
SocketResourceError, SocketTimeoutError, DatagramTooLargeError, NetworkError,
AddressInUseError, SocketAddressNotAvailableError, UnsupportedSocketOperationError, UnfinishedSocketOperationError,
ProxyAuthenticationRequiredError, SslHandshakeFailedError, ProxyConnectionRefusedError, ProxyConnectionClosedError,
ProxyConnectionTimeoutError, ProxyNotFoundError, ProxyProtocolError, UnknownSocketError = -1
}
This enum describes the socket errors that can occur.
enum SocketOption { LowDelayOption, KeepAliveOption, MulticastTtlOption, MulticastLoopbackOption }
This enum represents the options that can be set on a socket.
enum SocketState {
UnconnectedState, HostLookupState, ConnectingState, ConnectedState,
BoundState, ListeningState, ClosingState
}
This enum describes the different states in which a socket can be.
enum SocketType { TcpSocket, UdpSocket, UnknownSocketType = -1 }
This enum describes the transport layer protocol.
Public Types inherited from QIODevice
enum OpenModeFlag {
NotOpen = 0x0000, ReadOnly = 0x0001, WriteOnly = 0x0002, ReadWrite = ReadOnly | WriteOnly,
Append = 0x0004, Truncate = 0x0008, Text = 0x0010, Unbuffered = 0x0020
}
This enum is used with open() to describe the mode in which a device is opened.
Public Slots
void ignoreSslErrors ()
This slot tells QSslSocket to ignore errors during QSslSocket's handshake phase and continue connecting.
void startClientEncryption ()
Starts a delayed SSL handshake for a client connection.
void startServerEncryption ()
Starts a delayed SSL handshake for a server connection.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void encrypted ()
This signal is emitted when QSslSocket enters encrypted mode.
void encryptedBytesWritten (qint64 totalBytes)
This signal is emitted when QSslSocket writes its encrypted data to the network.
void modeChanged (QSslSocket::SslMode newMode)
This signal is emitted when QSslSocket changes from QSslSocket::UnencryptedMode to either QSslSocket::SslClientMode or QSslSocket::SslServerMode .
void peerVerifyError (const QSslError &error)
QSslSocket can emit this signal several times during the SSL handshake, before encryption has been established, to indicate that an error has occurred while establishing the identity of the peer.
void sslErrors (const QList< QSslError > &errors)
QSslSocket emits this signal after the SSL handshake to indicate that one or more errors have occurred while establishing the identity of the peer.
Signals inherited from QAbstractSocket
void connected ()
This signal is emitted after connectToHost() has been called and a connection has been successfully established.
void disconnected ()
This signal is emitted when the socket has been disconnected.
void error (QAbstractSocket::SocketError)
This signal is emitted after an error occurred.
void hostFound ()
This signal is emitted after connectToHost() has been called and the host lookup has succeeded.
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void stateChanged (QAbstractSocket::SocketState)
This signal is emitted whenever QAbstractSocket's state changes.
Signals inherited from QIODevice
void aboutToClose ()
This signal is emitted when the device is about to close.
void bytesWritten (qint64 bytes)
This signal is emitted every time a payload of data has been written to the device.
void readChannelFinished ()
This signal is emitted when the input (reading) stream is closed in this device.
void readyRead ()
This signal is emitted once every time new data is available for reading from the device.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void abort ()
Aborts the current connection and resets the socket.
void addCaCertificate (const QSslCertificate &certificate)
Adds the certificate to this socket's CA certificate database.
bool addCaCertificates (const QString &path, QSsl::EncodingFormat format=QSsl::Pem, QRegExp::PatternSyntax syntax=QRegExp::FixedString)
Searches all files in the path for certificates encoded in the specified format and adds them to this socket's CA certificate database.
void addCaCertificates (const QList< QSslCertificate > &certificates)
Adds the certificates to this socket's CA certificate database.
bool atEnd () const
Reimplemented Function
qint64 bytesAvailable () const
Returns the number of decrypted bytes that are immediately available for reading.
qint64 bytesToWrite () const
Returns the number of unencrypted bytes that are waiting to be encrypted and written to the network.
QList< QSslCertificate > caCertificates () const
Returns this socket's CA certificate database.
bool canReadLine () const
Returns true if you can read one while line (terminated by a single ASCII '
' character) of decrypted characters; otherwise, false is returned.
QList< QSslCipher > ciphers () const
Returns this socket's current cryptographic cipher suite.
void close ()
Reimplemented Function
void connectToHostEncrypted (const QString &hostName, quint16 port, OpenMode mode=ReadWrite)
Starts an encrypted connection to the device hostName on port, using mode as the OpenMode .
void connectToHostEncrypted (const QString &hostName, quint16 port, const QString &sslPeerName, OpenMode mode=ReadWrite)
In addition to the original behaviour of connectToHostEncrypted, this overloaded method enables the usage of a different hostname (sslPeerName) for the certificate validation instead of the one used for the TCP connection (hostName).
qint64 encryptedBytesAvailable () const
Returns the number of encrypted bytes that are awaiting decryption.
qint64 encryptedBytesToWrite () const
Returns the number of encrypted bytes that are waiting to be written to the network.
bool flush ()
This function writes as much as possible from the internal write buffer to the underlying network socket, without blocking.
void ignoreSslErrors (const QList< QSslError > &errors)
This method tells QSslSocket to ignore only the errors given in errors.
bool isEncrypted () const
Returns true if the socket is encrypted; otherwise, false is returned.
QSslCertificate localCertificate () const
Returns the socket's local QSslCertificate {certificate}, or an empty certificate if no local certificate has been assigned.
SslMode mode () const
Returns the current mode for the socket; either UnencryptedMode, where QSslSocket behaves identially to QTcpSocket, or one of SslClientMode or SslServerMode, where the client is either negotiating or in encrypted mode.
QSslCertificate peerCertificate () const
Returns the peer's digital certificate (i.e., the immediate certificate of the host you are connected to), or a null certificate, if the peer has not assigned a certificate.
QList< QSslCertificate > peerCertificateChain () const
Returns the peer's chain of digital certificates, or an empty list of certificates.
int peerVerifyDepth () const
Returns the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, or 0 (the default) if no maximum depth has been set, indicating that the whole certificate chain should be checked.
QSslSocket::PeerVerifyMode peerVerifyMode () const
Returns the socket's verify mode.
QString peerVerifyName () const
Returns the different hostname for the certificate validation, as set by setPeerVerifyName or by connectToHostEncrypted.
QSslKey privateKey () const
Returns this socket's private key.
QSsl::SslProtocol protocol () const
Returns the socket's SSL protocol.
QSslSocket (QObject *parent=0)
Constructs a QSslSocket object.
QSslCipher sessionCipher () const
Returns the socket's cryptographic QSslCipher {cipher}, or a null cipher if the connection isn't encrypted.
void setCaCertificates (const QList< QSslCertificate > &certificates)
Sets this socket's CA certificate database to be certificates.
void setCiphers (const QList< QSslCipher > &ciphers)
Sets the cryptographic cipher suite for this socket to ciphers, which must contain a subset of the ciphers in the list returned by supportedCiphers().
void setCiphers (const QString &ciphers)
Sets the cryptographic cipher suite for this socket to ciphers, which is a colon-separated list of cipher suite names.
void setLocalCertificate (const QSslCertificate &certificate)
Sets the socket's local certificate to certificate.
void setLocalCertificate (const QString &fileName, QSsl::EncodingFormat format=QSsl::Pem)
Sets the socket's local QSslCertificate {certificate} to the first one found in file path, which is parsed according to the specified format.
void setPeerVerifyDepth (int depth)
Sets the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, to depth.
void setPeerVerifyMode (QSslSocket::PeerVerifyMode mode)
Sets the socket's verify mode to mode.
void setPeerVerifyName (const QString &hostName)
Sets a different host name, given by hostName, for the certificate validation instead of the one used for the TCP connection.
void setPrivateKey (const QSslKey &key)
Sets the socket's private QSslKey {key} to key.
void setPrivateKey (const QString &fileName, QSsl::KeyAlgorithm algorithm=QSsl::Rsa, QSsl::EncodingFormat format=QSsl::Pem, const QByteArray &passPhrase=QByteArray())
Reads the string in file fileName and decodes it using a specified algorithm and encoding format to construct an QSslKey {SSL key}.
void setProtocol (QSsl::SslProtocol protocol)
Sets the socket's SSL protocol to protocol.
void setReadBufferSize (qint64 size)
Sets the size of QSslSocket's internal read buffer to be size bytes.
bool setSocketDescriptor (int socketDescriptor, SocketState state=ConnectedState, OpenMode openMode=ReadWrite)
Initializes QSslSocket with the native socket descriptor socketDescriptor.
void setSocketOption (QAbstractSocket::SocketOption option, const QVariant &value)
Sets the given option to the value described by value.
void setSslConfiguration (const QSslConfiguration &config)
Sets the socket's SSL configuration to be the contents of configuration.
QVariant socketOption (QAbstractSocket::SocketOption option)
Returns the value of the option option.
QSslConfiguration sslConfiguration () const
Returns the socket's SSL configuration state.
QList< QSslError > sslErrors () const
Returns a list of the last SSL errors that occurred.
bool waitForBytesWritten (int msecs=30000)
Reimplemented Function
bool waitForConnected (int msecs=30000)
Waits until the socket is connected, or msecs milliseconds, whichever happens first.
bool waitForDisconnected (int msecs=30000)
Waits until the socket has disconnected or msecs milliseconds, whichever comes first.
bool waitForEncrypted (int msecs=30000)
Waits until the socket has completed the SSL handshake and has emitted encrypted(), or msecs milliseconds, whichever comes first.
bool waitForReadyRead (int msecs=30000)
Reimplemented Function
~QSslSocket ()
Destroys the QSslSocket.
Public Functions inherited from QTcpSocket
QTcpSocket (QObject *parent=0)
Creates a QTcpSocket object in state UnconnectedState.
virtual ~QTcpSocket ()
Destroys the socket, closing the connection if necessary.
Public Functions inherited from QAbstractSocket
void abort ()
Aborts the current connection and resets the socket.
void connectToHost (const QString &hostName, quint16 port, OpenMode mode=ReadWrite)
Attempts to make a connection to hostName on the given port.
void connectToHost (const QHostAddress &address, quint16 port, OpenMode mode=ReadWrite)
Attempts to make a connection to address on port port.
void disconnectFromHost ()
Attempts to close the socket.
SocketError error () const
Returns the type of error that last occurred.
bool flush ()
This function writes as much as possible from the internal write buffer to the underlying network socket, without blocking.
bool isSequential () const
Reimplemented Function
bool isValid () const
Returns true if the socket is valid and ready for use; otherwise returns false.
QHostAddress localAddress () const
Returns the host address of the local socket if available; otherwise returns QHostAddress::Null.
quint16 localPort () const
Returns the host port number (in native byte order) of the local socket if available; otherwise returns 0.
QHostAddress peerAddress () const
Returns the address of the connected peer if the socket is in ConnectedState; otherwise returns QHostAddress::Null.
QString peerName () const
Returns the name of the peer as specified by connectToHost(), or an empty QString if connectToHost() has not been called.
quint16 peerPort () const
Returns the port of the connected peer if the socket is in ConnectedState; otherwise returns 0.
QNetworkProxy proxy () const
Returns the network proxy for this socket.
QAbstractSocket (SocketType socketType, QObject *parent)
Creates a new abstract socket of type socketType.
qint64 readBufferSize () const
Returns the size of the internal read buffer.
void setProxy (const QNetworkProxy &networkProxy)
Sets the explicit network proxy for this socket to networkProxy.
void setReadBufferSize (qint64 size)
Sets the size of QAbstractSocket's internal read buffer to be size bytes.
bool setSocketDescriptor (int socketDescriptor, SocketState state=ConnectedState, OpenMode openMode=ReadWrite)
Initializes QAbstractSocket with the native socket descriptor socketDescriptor.
void setSocketOption (QAbstractSocket::SocketOption option, const QVariant &value)
Sets the given option to the value described by value.
int socketDescriptor () const
Returns the native socket descriptor of the QAbstractSocket object if this is available; otherwise returns -1.
QVariant socketOption (QAbstractSocket::SocketOption option)
Returns the value of the option option.
SocketType socketType () const
Returns the socket type (TCP, UDP, or other).
SocketState state () const
Returns the state of the socket.
bool waitForConnected (int msecs=30000)
Waits until the socket is connected, up to msecs milliseconds.
bool waitForDisconnected (int msecs=30000)
Waits until the socket has disconnected, up to msecs milliseconds.
virtual ~QAbstractSocket ()
Destroys the socket.
Public Functions inherited from QIODevice
QString errorString () const
Returns a human-readable description of the last device error that occurred.
bool getChar (char *c)
Reads one character from the device and stores it in c.
bool isOpen () const
Returns true if the device is open; otherwise returns false.
bool isReadable () const
Returns true if data can be read from the device; otherwise returns false.
bool isTextModeEnabled () const
Returns true if the Text flag is enabled; otherwise returns false.
bool isWritable () const
Returns true if data can be written to the device; otherwise returns false.
virtual bool open (OpenMode mode)
Opens the device and sets its OpenMode to mode.
OpenMode openMode () const
Returns the mode in which the device has been opened; i.e.
qint64 peek (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, without side effects (i.
QByteArray peek (qint64 maxlen)
Peeks at most maxSize bytes from the device, returning the data peeked as a QByteArray.
virtual qint64 pos () const
For random-access devices, this function returns the position that data is written to or read from.
bool putChar (char c)
Writes the character c to the device.
QIODevice ()
Constructs a QIODevice object.
QIODevice (QObject *parent)
Constructs a QIODevice object with the given parent.
qint64 read (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, and returns the number of bytes read.
QByteArray read (qint64 maxlen)
Reads at most maxSize bytes from the device, and returns the data read as a QByteArray.
QByteArray readAll ()
Reads all available data from the device, and returns it as a QByteArray.
qint64 readLine (char *data, qint64 maxlen)
This function reads a line of ASCII characters from the device, up to a maximum of maxSize - 1 bytes, stores the characters in data, and returns the number of bytes read.
QByteArray readLine (qint64 maxlen=0)
Reads a line from the device, but no more than maxSize characters, and returns the result as a QByteArray.
virtual bool reset ()
Seeks to the start of input for random-access devices.
virtual bool seek (qint64 pos)
For random-access devices, this function sets the current position to pos, returning true on success, or false if an error occurred.
void setTextModeEnabled (bool enabled)
If enabled is true, this function sets the Text flag on the device; otherwise the Text flag is removed.
virtual qint64 size () const
For open random-access devices, this function returns the size of the device.
void ungetChar (char c)
Puts the character c back into the device, and decrements the current position unless the position is 0.
qint64 write (const char *data, qint64 len)
Writes at most maxSize bytes of data from data to the device.
qint64 write (const char *data)
Writes data from a zero-terminated string of 8-bit characters to the device.
qint64 write (const QByteArray &data)
Writes the content of byteArray to the device.
virtual ~QIODevice ()
The destructor is virtual, and QIODevice is an abstract base class.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void addDefaultCaCertificate (const QSslCertificate &certificate)
Adds certificate to the default CA certificate database.
static bool addDefaultCaCertificates (const QString &path, QSsl::EncodingFormat format=QSsl::Pem, QRegExp::PatternSyntax syntax=QRegExp::FixedString)
Searches all files in the path for certificates with the specified encoding and adds them to the default CA certificate database.
static void addDefaultCaCertificates (const QList< QSslCertificate > &certificates)
Adds certificates to the default CA certificate database.
static QList< QSslCertificate > defaultCaCertificates ()
Returns the current default CA certificate database.
static QList< QSslCipher > defaultCiphers ()
Returns the default cryptographic cipher suite for all sockets in this application.
static void setDefaultCaCertificates (const QList< QSslCertificate > &certificates)
Sets the default CA certificate database to certificates.
static void setDefaultCiphers (const QList< QSslCipher > &ciphers)
Sets the default cryptographic cipher suite for all sockets in this application to ciphers, which must contain a subset of the ciphers in the list returned by supportedCiphers().
static QList< QSslCipher > supportedCiphers ()
Returns the list of cryptographic ciphers supported by this system.
static bool supportsSsl ()
Returns true if this platform supports SSL; otherwise, returns false.
static QList< QSslCertificate > systemCaCertificates ()
This function provides the CA certificate database provided by the operating system.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Slots
void connectToHostImplementation (const QString &hostName, quint16 port, OpenMode openMode)
void disconnectFromHostImplementation ()
Protected Slots inherited from QAbstractSocket
void connectToHostImplementation (const QString &hostName, quint16 port, OpenMode mode=ReadWrite)
Contains the implementation of connectToHost().
void disconnectFromHostImplementation ()
Contains the implementation of disconnectFromHost().
Protected Functions
qint64 readData (char *data, qint64 maxlen)
Reimplemented Function
qint64 writeData (const char *data, qint64 len)
Reimplemented Function
Protected Functions inherited from QTcpSocket
QTcpSocket (QTcpSocketPrivate &dd, QObject *parent=0)
Protected Functions inherited from QAbstractSocket
QAbstractSocket (SocketType socketType, QAbstractSocketPrivate &dd, QObject *parent=0)
Constructs a new abstract socket of type socketType.
qint64 readLineData (char *data, qint64 maxlen)
Reimplemented Function
void setLocalAddress (const QHostAddress &address)
Sets the address on the local side of a connection to address.
void setLocalPort (quint16 port)
Sets the port on the local side of a connection to port.
void setPeerAddress (const QHostAddress &address)
Sets the address of the remote side of the connection to address.
void setPeerName (const QString &name)
Sets the host name of the remote peer to name.
void setPeerPort (quint16 port)
Sets the port of the remote side of the connection to port.
void setSocketError (SocketError socketError)
Sets the type of error that last occurred to socketError.
void setSocketState (SocketState state)
Sets the state of the socket to state.
Protected Functions inherited from QIODevice
QIODevice (QIODevicePrivate &dd, QObject *parent=0)
void setErrorString (const QString &errorString)
Sets the human readable description of the last device error that occurred to str.
void setOpenMode (OpenMode openMode)
Sets the OpenMode of the device to openMode.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QSslSocketBackendPrivate
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSslSocket class provides an SSL encrypted socket for both clients and servers.
Since
4.3
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QSslSocket establishes a secure, encrypted TCP connection you can use for transmitting encrypted data. It can operate in both client and server mode, and it supports modern SSL protocols, including SSLv3 and TLSv1. By default, QSslSocket uses TLSv1, but you can change the SSL protocol by calling setProtocol() as long as you do it before the handshake has started.
SSL encryption operates on top of the existing TCP stream after the socket enters the ConnectedState. There are two simple ways to establish a secure connection using QSslSocket: With an immediate SSL handshake, or with a delayed SSL handshake occurring after the connection has been established in unencrypted mode.
The most common way to use QSslSocket is to construct an object and start a secure connection by calling connectToHostEncrypted(). This method starts an immediate SSL handshake once the connection has been established.
QSslSocket *socket = new QSslSocket(this);
connect(socket, SIGNAL(encrypted()), this, SLOT(ready()));
socket->connectToHostEncrypted("imap.example.com", 993);
As with a plain QTcpSocket, QSslSocket enters the HostLookupState, ConnectingState, and finally the ConnectedState, if the connection is successful. The handshake then starts automatically, and if it succeeds, the encrypted() signal is emitted to indicate the socket has entered the encrypted state and is ready for use.
Note that data can be written to the socket immediately after the return from connectToHostEncrypted() (i.e., before the encrypted() signal is emitted). The data is queued in QSslSocket until after the encrypted() signal is emitted.
An example of using the delayed SSL handshake to secure an existing connection is the case where an SSL server secures an incoming connection. Suppose you create an SSL server class as a subclass of QTcpServer. You would override QTcpServer::incomingConnection() with something like the example below, which first constructs an instance of QSslSocket and then calls setSocketDescriptor() to set the new socket's descriptor to the existing one passed in. It then initiates the SSL handshake by calling startServerEncryption().
void SslServer::incomingConnection(int socketDescriptor)
{
    QSslSocket *serverSocket = new QSslSocket;
    if (serverSocket->setSocketDescriptor(socketDescriptor)) {
        connect(serverSocket, SIGNAL(encrypted()), this, SLOT(ready()));
        serverSocket->startServerEncryption();
    } else {
        delete serverSocket;
    }
}
If an error occurs, QSslSocket emits the sslErrors() signal. In this case, if no action is taken to ignore the error(s), the connection is dropped. To continue, despite the occurrence of an error, you can call ignoreSslErrors(), either from within this slot after the error occurs, or any time after construction of the QSslSocket and before the connection is attempted. This will allow QSslSocket to ignore the errors it encounters when establishing the identity of the peer. Ignoring errors during an SSL handshake should be used with caution, since a fundamental characteristic of secure connections is that they should be established with a successful handshake.
Once encrypted, you use QSslSocket as a regular QTcpSocket. When readyRead() is emitted, you can call read(), canReadLine() and readLine(), or getChar() to read decrypted data from QSslSocket's internal buffer, and you can call write() or putChar() to write data back to the peer. QSslSocket will automatically encrypt the written data for you, and emit encryptedBytesWritten() once the data has been written to the peer.
As a convenience, QSslSocket supports QTcpSocket's blocking functions waitForConnected(), waitForReadyRead(), waitForBytesWritten(), and waitForDisconnected(). It also provides waitForEncrypted(), which will block the calling thread until an encrypted connection has been established.
QSslSocket socket;
socket.connectToHostEncrypted("http.example.com", 443);
if (!socket.waitForEncrypted()) {
    qDebug() << socket.errorString();
    return false;
}
socket.write("GET / HTTP/1.0\r\n\r\n");
while (socket.waitForReadyRead())
    qDebug() << socket.readAll().data();
QSslSocket provides an extensive, easy-to-use API for handling cryptographic ciphers, private keys, and local, peer, and Certification Authority (CA) certificates. It also provides an API for handling errors that occur during the handshake phase.
The following features can also be customized:
The socket's cryptographic cipher suite can be customized before the handshake phase with setCiphers() and setDefaultCiphers().
The socket's local certificate and private key can be customized before the handshake phase with setLocalCertificate() and setPrivateKey().
The CA certificate database can be extended and customized with addCaCertificate(), addCaCertificates(), setCaCertificates(), addDefaultCaCertificate(), addDefaultCaCertificates(), and setDefaultCaCertificates().
Note
If available, root certificates on Unix (excluding Mac OS X) will be loaded on demand from the standard certificate directories. If you do not want to load root certificates on demand, you need to call either the static function setDefaultCaCertificates() before the first SSL handshake is made in your application, (e.g. via "QSslSocket::setDefaultCaCertificates(QSslSocket::systemCaCertificates());"), or call setCaCertificates() on your QSslSocket instance prior to the SSL handshake.
For more information about ciphers and certificates, refer to QSslCipher and QSslCertificate.
This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit (qmake-variable-reference.html#target-capability{TARGET.CAPABILITY} qmake variable.
See also
QSslCertificate, QSslCipher, QSslError
Definition at line 67 of file qsslsocket.h.
Enumerations
PeerVerifyMode
enum QSslSocket::PeerVerifyMode
Describes the peer verification modes for QSslSocket.
Since
4.4
The default mode is AutoVerifyPeer, which selects an appropriate mode depending on the socket's QSocket::SslMode.
VerifyNone QSslSocket will not request a certificate from the peer. You can set this mode if you are not interested in the identity of the other side of the connection. The connection will still be encrypted, and your socket will still send its local certificate to the peer if it's requested.
QueryPeer QSslSocket will request a certificate from the peer, but does not require this certificate to be valid. This is useful when you want to display peer certificate details to the user without affecting the actual SSL handshake. This mode is the default for servers.
VerifyPeer QSslSocket will request a certificate from the peer during the SSL handshake phase, and requires that this certificate is valid. On failure, QSslSocket will emit the QSslSocket::sslErrors() signal. This mode is the default for clients.
AutoVerifyPeer QSslSocket will automatically use QueryPeer for server sockets and VerifyPeer for client sockets.
See also
QSslSocket::peerVerifyMode()
Enumerator
VerifyNone
QueryPeer
VerifyPeer
AutoVerifyPeer
Definition at line 77 of file qsslsocket.h.
{
         VerifyNone,
         QueryPeer,
         VerifyPeer,
         AutoVerifyPeer
     };
SslMode
enum QSslSocket::SslMode
Describes the connection modes available for QSslSocket.
UnencryptedMode The socket is unencrypted. Its behavior is identical to QTcpSocket.
SslClientMode The socket is a client-side SSL socket. It is either alreayd encrypted, or it is in the SSL handshake phase (see QSslSocket::isEncrypted()).
SslServerMode The socket is a server-side SSL socket. It is either already encrypted, or it is in the SSL handshake phase (see QSslSocket::isEncrypted()).
Enumerator
UnencryptedMode
SslClientMode
SslServerMode
Definition at line 71 of file qsslsocket.h.
                  {
         UnencryptedMode,
         SslClientMode,
         SslServerMode
     };
Constructors and Destructors
QSslSocket()
QSslSocket::QSslSocket (QObject * parent = 0)
Constructs a QSslSocket object.
parent is passed to QObject's constructor. The new socket's QSslCipher {cipher} suite is set to the one returned by the static method defaultCiphers().
Definition at line 350 of file qsslsocket.cpp.
     : QTcpSocket(*new QSslSocketBackendPrivate, parent)
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::QSslSocket(" << parent << "), this =" << (void *)this;
 #endif
     d->q_ptr = this;
     d->init();
 }
~QSslSocket()
QSslSocket::~QSslSocket ()
Destroys the QSslSocket.
Definition at line 364 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::~QSslSocket(), this =" << (void *)this;
 #endif
     delete d->plainSocket;
     d->plainSocket = 0;
 }
Functions
abort()
void QSslSocket::abort ()
Aborts the current connection and resets the socket.
Unlike disconnectFromHost(), this function immediately closes the socket, clearing any pending data in the write buffer.
See also
disconnectFromHost(), close()
Definition at line 893 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::abort()";
 #endif
     if (d->plainSocket)
         d->plainSocket->abort();
     close();
 }
addCaCertificate()
void QSslSocket::addCaCertificate (const QSslCertificate & certificate)
Adds the certificate to this socket's CA certificate database.
The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate.
To add multiple certificates, use addCaCertificates().
See also
caCertificates(), setCaCertificates()
Definition at line 1316 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.caCertificates += certificate;
 }
addCaCertificates() [1/2]
bool QSslSocket::addCaCertificates (const QString & path, QSsl::EncodingFormat format = QSsl::Pem, QRegExp::PatternSyntax syntax = QRegExp::FixedString)
Searches all files in the path for certificates encoded in the specified format and adds them to this socket's CA certificate database.
path can be explicit, or it can contain wildcards in the format specified by syntax. Returns true if one or more certificates are added to the socket's CA certificate database; otherwise returns false.
The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate.
For more precise control, use addCaCertificate().
See also
addCaCertificate(), QSslCertificate::fromPath()
Definition at line 1295 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     QList<QSslCertificate> certs = QSslCertificate::fromPath(path, format, syntax);
     if (certs.isEmpty())
         return false;
     d->configuration.caCertificates += certs;
     return true;
 }
addCaCertificates() [2/2]
void QSslSocket::addCaCertificates (const QList< QSslCertificate > & certificates)
Adds the certificates to this socket's CA certificate database.
The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate.
For more precise control, use addCaCertificate().
See also
caCertificates(), addDefaultCaCertificate()
Definition at line 1331 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.caCertificates += certificates;
 }
addDefaultCaCertificate()
void QSslSocket::addDefaultCaCertificate (const QSslCertificate & certificate) static
Adds certificate to the default CA certificate database.
Each SSL socket's CA certificate database is initialized to the default CA certificate database.
See also
defaultCaCertificates(), addCaCertificates()
Definition at line 1399 of file qsslsocket.cpp.
 {
     QSslSocketPrivate::addDefaultCaCertificate(certificate);
 }
addDefaultCaCertificates() [1/2]
bool QSslSocket::addDefaultCaCertificates (const QString & path, QSsl::EncodingFormat encoding = QSsl::Pem, QRegExp::PatternSyntax syntax = QRegExp::FixedString) static
Searches all files in the path for certificates with the specified encoding and adds them to the default CA certificate database.
path can be an explicit file, or it can contain wildcards in the format specified by syntax. Returns true if any CA certificates are added to the default database.
Each SSL socket's CA certificate database is initialized to the default CA certificate database.
See also
defaultCaCertificates(), addCaCertificates(), addDefaultCaCertificate()
Definition at line 1386 of file qsslsocket.cpp.
 {
     return QSslSocketPrivate::addDefaultCaCertificates(path, encoding, syntax);
 }
addDefaultCaCertificates() [2/2]
void QSslSocket::addDefaultCaCertificates (const QList< QSslCertificate > & certificates) static
Adds certificates to the default CA certificate database.
Each SSL socket's CA certificate database is initialized to the default CA certificate database.
See also
defaultCaCertificates(), addCaCertificates()
Definition at line 1411 of file qsslsocket.cpp.
 {
     QSslSocketPrivate::addDefaultCaCertificates(certificates);
 }
atEnd()
bool QSslSocket::atEnd () const virtual
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 833 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     if (d->mode == UnencryptedMode)
         return QIODevice::atEnd() && (!d->plainSocket || d->plainSocket->atEnd());
     return QIODevice::atEnd() && d->readBuffer.isEmpty();
 }
bytesAvailable()
qint64 QSslSocket::bytesAvailable () const virtual
Returns the number of decrypted bytes that are immediately available for reading.
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 731 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     if (d->mode == UnencryptedMode)
         return QIODevice::bytesAvailable() + (d->plainSocket ? d->plainSocket->bytesAvailable() : 0);
     return QIODevice::bytesAvailable() + d->readBuffer.size();
 }
bytesToWrite()
qint64 QSslSocket::bytesToWrite () const virtual
Returns the number of unencrypted bytes that are waiting to be encrypted and written to the network.
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 748 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     if (d->mode == UnencryptedMode)
         return d->plainSocket ? d->plainSocket->bytesToWrite() : 0;
     return d->writeBuffer.size();
 }
caCertificates()
QList< QSslCertificate > QSslSocket::caCertificates () const
Returns this socket's CA certificate database.
The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate. It can be moodified prior to the handshake with addCaCertificate(), addCaCertificates(), and setCaCertificates().
Note
On Unix, this method may return an empty list if the root certificates are loaded on demand.
See also
addCaCertificate(), addCaCertificates(), setCaCertificates()
Definition at line 1368 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.caCertificates;
 }
canReadLine()
bool QSslSocket::canReadLine () const virtual
Returns true if you can read one while line (terminated by a single ASCII '
' character) of decrypted characters; otherwise, false is returned.
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 800 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     if (d->mode == UnencryptedMode)
         return QIODevice::canReadLine() || (d->plainSocket && d->plainSocket->canReadLine());
     return QIODevice::canReadLine() || (!d->readBuffer.isEmpty() && d->readBuffer.canReadLine());
 }
ciphers()
QList< QSslCipher > QSslSocket::ciphers () const
Returns this socket's current cryptographic cipher suite.
This list is used during the socket's handshake phase for choosing a session cipher. The returned list of ciphers is ordered by descending preference. (i.e., the first cipher in the list is the most preferred cipher). The session cipher will be the first one in the list that is also supported by the peer.
By default, the handshake phase can choose any of the ciphers supported by this system's SSL libraries, which may vary from system to system. The list of ciphers supported by this system's SSL libraries is returned by supportedCiphers(). You can restrict the list of ciphers used for choosing the session cipher for this socket by calling setCiphers() with a subset of the supported ciphers. You can revert to using the entire set by calling setCiphers() with the list returned by supportedCiphers().
You can restrict the list of ciphers used for choosing the session cipher for all sockets by calling setDefaultCiphers() with a subset of the supported ciphers. You can revert to using the entire set by calling setCiphers() with the list returned by supportedCiphers().
See also
setCiphers(), defaultCiphers(), setDefaultCiphers(), supportedCiphers()
Definition at line 1183 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.ciphers;
 }
close()
void QSslSocket::close () virtual
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 811 of file qsslsocket.cpp.
 {
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::close()";
 #endif
     Q_D(QSslSocket);
     if (d->plainSocket)
         d->plainSocket->close();
     QTcpSocket::close();
     // must be cleared, reading/writing not possible on closed socket:
     d->readBuffer.clear();
     d->writeBuffer.clear();
     // for QTcpSocket this is already done because it uses the readBuffer/writeBuffer
     // if the QIODevice it is based on
     // ### FIXME QSslSocket should probably do similar instead of having
     // its own readBuffer/writeBuffer
 }
connectToHostEncrypted() [1/2]
void QSslSocket::connectToHostEncrypted (const QString & hostName, quint16 port, OpenMode mode = ReadWrite)
Starts an encrypted connection to the device hostName on port, using mode as the OpenMode .
This is equivalent to calling connectToHost() to establish the connection, followed by a call to startClientEncryption().
QSslSocket first enters the HostLookupState. Then, after entering either the event loop or one of the waitFor...() functions, it enters the ConnectingState, emits connected(), and then initiates the SSL client handshake. At each state change, QSslSocket emits signal stateChanged().
After initiating the SSL client handshake, if the identity of the peer can't be established, signal sslErrors() is emitted. If you want to ignore the errors and continue connecting, you must call ignoreSslErrors(), either from inside a slot function connected to the sslErrors() signal, or prior to entering encrypted mode. If ignoreSslErrors() is not called, the connection is dropped, signal disconnected() is emitted, and QSslSocket returns to the UnconnectedState.
If the SSL handshake is successful, QSslSocket emits encrypted().
QSslSocket socket;
connect(&socket, SIGNAL(encrypted()), receiver, SLOT(socketEncrypted()));
socket.connectToHostEncrypted("imap", 993);
socket->write("1 CAPABILITY\r\n");
Note: The example above shows that text can be written to the socket immediately after requesting the encrypted connection, before the encrypted() signal has been emitted. In such cases, the text is queued in the object and written to the socket after the connection is established and the encrypted() signal has been emitted.
The default for mode is ReadWrite .
If you want to create a QSslSocket on the server side of a connection, you should instead call startServerEncryption() upon receiving the incoming connection through QTcpServer.
See also
connectToHost(), startClientEncryption(), waitForConnected(), waitForEncrypted()
Definition at line 414 of file qsslsocket.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), and QHttpNetworkConnectionChannel::ensureConnection().
 {
     Q_D(QSslSocket);
     if (d->state == ConnectedState || d->state == ConnectingState) {
         qWarning("QSslSocket::connectToHostEncrypted() called when already connecting/connected");
         return;
     }
     d->init();
     d->autoStartHandshake = true;
     d->initialized = true;
     // Note: When connecting to localhost, some platforms (e.g., HP-UX and some BSDs)
     // establish the connection immediately (i.e., first attempt).
     connectToHost(hostName, port, mode);
 }
connectToHostEncrypted() [2/2]
void QSslSocket::connectToHostEncrypted (const QString & hostName, quint16 port, const QString & sslPeerName, OpenMode mode = ReadWrite)
In addition to the original behaviour of connectToHostEncrypted, this overloaded method enables the usage of a different hostname (sslPeerName) for the certificate validation instead of the one used for the TCP connection (hostName).
Since
4.6 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
connectToHostEncrypted()
Definition at line 445 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (d->state == ConnectedState || d->state == ConnectingState) {
         qWarning("QSslSocket::connectToHostEncrypted() called when already connecting/connected");
         return;
     }
     d->init();
     d->autoStartHandshake = true;
     d->initialized = true;
     d->verificationPeerName = sslPeerName;
     // Note: When connecting to localhost, some platforms (e.g., HP-UX and some BSDs)
     // establish the connection immediately (i.e., first attempt).
     connectToHost(hostName, port, mode);
 }
connectToHostImplementation
void QSslSocket::connectToHostImplementation (const QString & hostName, quint16 port, OpenMode openMode) protected slot
Warning
This function is not part of the public interface.
Definition at line 1795 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (!d->initialized)
         d->init();
     d->initialized = false;
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::connectToHostImplementation("
              << hostName << ',' << port << ',' << openMode << ')';
 #endif
     if (!d->plainSocket) {
 #ifdef QSSLSOCKET_DEBUG
         qDebug() << "\tcreating internal plain socket";
 #endif
         d->createPlainSocket(openMode);
     }
 #ifndef QT_NO_NETWORKPROXY
     d->plainSocket->setProxy(proxy());
     //copy user agent down to the plain socket (if it has been set)
     d->plainSocket->setProperty("_q_user-agent", property("_q_user-agent"));
 #endif
     QIODevice::open(openMode);
     d->plainSocket->connectToHost(hostName, port, openMode);
     d->cachedSocketDescriptor = d->plainSocket->socketDescriptor();
 }
defaultCaCertificates()
QList< QSslCertificate > QSslSocket::defaultCaCertificates () static
Returns the current default CA certificate database.
This database is originally set to your system's default CA certificate database. If no system default database is found, an empty database will be returned. You can override the default CA certificate database with your own CA certificate database using setDefaultCaCertificates().
Each SSL socket's CA certificate database is initialized to the default CA certificate database.
Note
On Unix, this method may return an empty list if the root certificates are loaded on demand.
See also
caCertificates()
Definition at line 1448 of file qsslsocket.cpp.
 {
     return QSslSocketPrivate::defaultCaCertificates();
 }
defaultCiphers()
QList< QSslCipher > QSslSocket::defaultCiphers () static
Returns the default cryptographic cipher suite for all sockets in this application.
This list is used during the socket's handshake phase when negotiating with the peer to choose a session cipher. The list is ordered by preference (i.e., the first cipher in the list is the most preferred cipher).
By default, the handshake phase can choose any of the ciphers supported by this system's SSL libraries, which may vary from system to system. The list of ciphers supported by this system's SSL libraries is returned by supportedCiphers().
See also
supportedCiphers()
Definition at line 1263 of file qsslsocket.cpp.
 {
     return QSslSocketPrivate::defaultCiphers();
 }
disconnectFromHostImplementation
void QSslSocket::disconnectFromHostImplementation () protected slot
Warning
This function is not part of the public interface.
Definition at line 1826 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::disconnectFromHostImplementation()";
 #endif
     if (!d->plainSocket)
         return;
     if (d->state == UnconnectedState)
         return;
     if (d->mode == UnencryptedMode && !d->autoStartHandshake) {
         d->plainSocket->disconnectFromHost();
         return;
     }
     if (d->state <= ConnectingState) {
         d->pendingClose = true;
         return;
     }
     // Perhaps emit closing()
     if (d->state != ClosingState) {
         d->state = ClosingState;
         emit stateChanged(d->state);
     }
     if (!d->writeBuffer.isEmpty())
         return;
     if (d->mode == UnencryptedMode) {
         d->plainSocket->disconnectFromHost();
     } else {
         d->disconnectFromHost();
     }
 }
encrypted
QSslSocket::encrypted () signal
This signal is emitted when QSslSocket enters encrypted mode.
After this signal has been emitted, QSslSocket::isEncrypted() will return true, and all further transmissions on the socket will be encrypted.
See also
QSslSocket::connectToHostEncrypted(), QSslSocket::isEncrypted()
encryptedBytesAvailable()
qint64 QSslSocket::encryptedBytesAvailable () const
Returns the number of encrypted bytes that are awaiting decryption.
Since
4.4
Normally, this function will return 0 because QSslSocket decrypts its incoming data as soon as it can.
Definition at line 766 of file qsslsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_error().
 {
     Q_D(const QSslSocket);
     if (d->mode == UnencryptedMode)
         return 0;
     return d->plainSocket->bytesAvailable();
 }
encryptedBytesToWrite()
qint64 QSslSocket::encryptedBytesToWrite () const
Returns the number of encrypted bytes that are waiting to be written to the network.
Since
4.4
Definition at line 783 of file qsslsocket.cpp.
Referenced by QHttpPrivate::postMoreData(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     Q_D(const QSslSocket);
     if (d->mode == UnencryptedMode)
         return 0;
     return d->plainSocket->bytesToWrite();
 }
encryptedBytesWritten
QSslSocket::encryptedBytesWritten (qint64 written) signal
This signal is emitted when QSslSocket writes its encrypted data to the network.
Since
4.4
The written parameter contains the number of bytes that were successfully written.
See also
QIODevice::bytesWritten()
flush()
bool QSslSocket::flush ()
This function writes as much as possible from the internal write buffer to the underlying network socket, without blocking.
If any data was written, this function returns true; otherwise false is returned.
Call this function if you need QSslSocket to start sending buffered data immediately. The number of bytes successfully written depends on the operating system. In most cases, you do not need to call this function, because QAbstractSocket will start sending data automatically once control goes back to the event loop. In the absence of an event loop, call waitForBytesWritten() instead.
See also
write(), waitForBytesWritten()
Definition at line 856 of file qsslsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_error().
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::flush()";
 #endif
     if (d->mode != UnencryptedMode)
         // encrypt any unencrypted bytes in our buffer
         d->transmit();
     return d->plainSocket ? d->plainSocket->flush() : false;
 }
ignoreSslErrors() [1/2]
void QSslSocket::ignoreSslErrors (const QList< QSslError > & errors)
This method tells QSslSocket to ignore only the errors given in errors.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.6
Note that you can set the expected certificate in the SSL error: If, for instance, you want to connect to a server that uses a self-signed certificate, consider the following snippet:
QList<QSslCertificate> cert = QSslCertificate::fromPath(QLatin1String("server-certificate.pem"));
QSslError error(QSslError::SelfSignedCertificate, cert.at(0));
QList<QSslError> expectedSslErrors;
expectedSslErrors.append(error);
QSslSocket socket;
socket.ignoreSslErrors(expectedSslErrors);
socket.connectToHostEncrypted("server.tld", 443);
Multiple calls to this function will replace the list of errors that were passed in previous calls. You can clear the list of errors you want to ignore by calling this function with an empty list.
See also
sslErrors()
Definition at line 1786 of file qsslsocket.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection(), and QHttp::ignoreSslErrors().
 {
     Q_D(QSslSocket);
     d->ignoreErrorsList = errors;
 }
ignoreSslErrors [2/2]
void QSslSocket::ignoreSslErrors () slot
This slot tells QSslSocket to ignore errors during QSslSocket's handshake phase and continue connecting.
If you want to continue with the connection even if errors occur during the handshake phase, then you must call this slot, either from a slot connected to sslErrors(), or before the handshake phase. If you don't call this slot, either in response to errors or before the handshake, the connection will be dropped after the sslErrors() signal has been emitted.
If there are no errors during the SSL handshake phase (i.e., the identity of the peer is established with no problems), QSslSocket will not emit the sslErrors() signal, and it is unnecessary to call this function.
Warning
Be sure to always let the user inspect the errors reported by the sslErrors() signal, and only call this method upon confirmation from the user that proceeding is ok. If there are unexpected errors, the connection should be aborted. Calling this method without inspecting the actual errors will most likely pose a security risk for your application. Use it with great care!
See also
sslErrors()
Definition at line 1757 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->ignoreAllSslErrors = true;
 }
isEncrypted()
bool QSslSocket::isEncrypted () const
Returns true if the socket is encrypted; otherwise, false is returned.
An encrypted socket encrypts all data that is written by calling write() or putChar() before the data is written to the network, and decrypts all incoming data as the data is received from the network, before you call read(), readLine() or getChar().
QSslSocket emits encrypted() when it enters encrypted mode.
You can call sessionCipher() to find which cryptographic cipher is used to encrypt and decrypt your data.
See also
mode()
Definition at line 563 of file qsslsocket.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest().
 {
     Q_D(const QSslSocket);
     return d->connectionEncrypted;
 }
localCertificate()
QSslCertificate QSslSocket::localCertificate () const
Returns the socket's local QSslCertificate {certificate}, or an empty certificate if no local certificate has been assigned.
See also
setLocalCertificate(), privateKey()
Definition at line 1008 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.localCertificate;
 }
mode()
QSslSocket::SslMode QSslSocket::mode () const
Returns the current mode for the socket; either UnencryptedMode, where QSslSocket behaves identially to QTcpSocket, or one of SslClientMode or SslServerMode, where the client is either negotiating or in encrypted mode.
When the mode changes, QSslSocket emits modeChanged()
See also
SslMode
Definition at line 542 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->mode;
 }
modeChanged
QSslSocket::modeChanged (QSslSocket::SslMode mode) signal
This signal is emitted when QSslSocket changes from QSslSocket::UnencryptedMode to either QSslSocket::SslClientMode or QSslSocket::SslServerMode .
mode is the new mode.
See also
QSslSocket::mode()
peerCertificate()
QSslCertificate QSslSocket::peerCertificate () const
Returns the peer's digital certificate (i.e., the immediate certificate of the host you are connected to), or a null certificate, if the peer has not assigned a certificate.
The peer certificate is checked automatically during the handshake phase, so this function is normally used to fetch the certificate for display or for connection diagnostic purposes. It contains information about the peer, including its host name, the certificate issuer, and the peer's public key.
Because the peer certificate is set during the handshake phase, it is safe to access the peer certificate from a slot connected to the sslErrors() signal or the encrypted() signal.
If a null certificate is returned, it can mean the SSL handshake failed, or it can mean the host you are connected to doesn't have a certificate, or it can mean there is no connection.
If you want to check the peer's complete chain of certificates, use peerCertificateChain() to get them all at once.
See also
peerCertificateChain()
Definition at line 1039 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.peerCertificate;
 }
peerCertificateChain()
QList< QSslCertificate > QSslSocket::peerCertificateChain () const
Returns the peer's chain of digital certificates, or an empty list of certificates.
Peer certificates are checked automatically during the handshake phase. This function is normally used to fetch certificates for display, or for performing connection diagnostics. Certificates contain information about the peer and the certificate issuers, including host name, issuer names, and issuer public keys.
The peer certificates are set in QSslSocket during the handshake phase, so it is safe to call this function from a slot connected to the sslErrors() signal or the encrypted() signal.
If an empty list is returned, it can mean the SSL handshake failed, or it can mean the host you are connected to doesn't have a certificate, or it can mean there is no connection.
If you want to get only the peer's immediate certificate, use peerCertificate().
See also
peerCertificate()
Definition at line 1068 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.peerCertificateChain;
 }
peerVerifyDepth()
int QSslSocket::peerVerifyDepth () const
Returns the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, or 0 (the default) if no maximum depth has been set, indicating that the whole certificate chain should be checked.
Since
4.4
The certificates are checked in issuing order, starting with the peer's own certificate, then its issuer's certificate, and so on.
See also
setPeerVerifyDepth(), peerVerifyMode()
Definition at line 656 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.peerVerifyDepth;
 }
peerVerifyError
void QSslSocket::peerVerifyError (const QSslError & error) signal
QSslSocket can emit this signal several times during the SSL handshake, before encryption has been established, to indicate that an error has occurred while establishing the identity of the peer.
Since
4.4
The error is usually an indication that QSslSocket is unable to securely identify the peer.
This signal provides you with an early indication when something's wrong. By connecting to this signal, you can manually choose to tear down the connection from inside the connected slot before the handshake has completed. If no action is taken, QSslSocket will proceed to emitting QSslSocket::sslErrors().
See also
sslErrors()
peerVerifyMode()
QSslSocket::PeerVerifyMode QSslSocket::peerVerifyMode () const
Returns the socket's verify mode.
Since
4.4
This mode mode decides whether QSslSocket should request a certificate from the peer (i.e., the client requests a certificate from the server, or a server requesting a certificate from the client), and whether it should require that this certificate is valid.
The default mode is AutoVerifyPeer, which tells QSslSocket to use VerifyPeer for clients and QueryPeer for servers.
See also
setPeerVerifyMode(), peerVerifyDepth(), mode()
Definition at line 608 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.peerVerifyMode;
 }
peerVerifyName()
QString QSslSocket::peerVerifyName () const
Returns the different hostname for the certificate validation, as set by setPeerVerifyName or by connectToHostEncrypted.
Since
4.8
See also
setPeerVerifyName(), connectToHostEncrypted()
Definition at line 699 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->verificationPeerName;
 }
privateKey()
QSslKey QSslSocket::privateKey () const
Returns this socket's private key.
See also
setPrivateKey(), localCertificate()
Definition at line 1152 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.privateKey;
 }
protocol()
QSsl::SslProtocol QSslSocket::protocol () const
Returns the socket's SSL protocol.
By default, QSsl::SecureProtocols is used.
See also
setProtocol()
Definition at line 574 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->configuration.protocol;
 }
readData()
qint64 QSslSocket::readData (char * data, qint64 maxlen) protected virtual
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 1864 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     qint64 readBytes = 0;
     if (d->mode == UnencryptedMode && !d->autoStartHandshake) {
         readBytes = d->plainSocket->read(data, maxlen);
     } else {
         do {
             const char *readPtr = d->readBuffer.readPointer();
             int bytesToRead = qMin<int>(maxlen - readBytes, d->readBuffer.nextDataBlockSize());
             ::memcpy(data + readBytes, readPtr, bytesToRead);
             readBytes += bytesToRead;
             d->readBuffer.free(bytesToRead);
         } while (!d->readBuffer.isEmpty() && readBytes < maxlen);
     }
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::readData(" << (void *)data << ',' << maxlen << ") ==" << readBytes;
 #endif
     // possibly trigger another transmit() to decrypt more data from the socket
     if (d->readBuffer.isEmpty() && d->plainSocket->bytesAvailable())
         QMetaObject::invokeMethod(this, "_q_flushReadBuffer", Qt::QueuedConnection);
     return readBytes;
 }
sessionCipher()
QSslCipher QSslSocket::sessionCipher () const
Returns the socket's cryptographic QSslCipher {cipher}, or a null cipher if the connection isn't encrypted.
The socket's cipher for the session is set during the handshake phase. The cipher is used to encrypt and decrypt data transmitted through the socket.
QSslSocket also provides functions for setting the ordered list of ciphers from which the handshake phase will eventually select the session cipher. This ordered list must be in place before the handshake phase begins.
See also
ciphers(), setCiphers(), setDefaultCiphers(), defaultCiphers(), supportedCiphers()
Definition at line 1088 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->sessionCipher();
 }
setCaCertificates()
void QSslSocket::setCaCertificates (const QList< QSslCertificate > & certificates)
Sets this socket's CA certificate database to be certificates.
The certificate database must be set prior to the SSL handshake. The CA certificate database is used by the socket during the handshake phase to validate the peer's certificate.
The CA certificate database can be reset to the current default CA certificate database by calling this function with the list of CA certificates returned by defaultCaCertificates().
See also
defaultCaCertificates()
Definition at line 1349 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.caCertificates = certificates;
     d->allowRootCertOnDemandLoading = false;
 }
setCiphers() [1/2]
void QSslSocket::setCiphers (const QList< QSslCipher > & ciphers)
Sets the cryptographic cipher suite for this socket to ciphers, which must contain a subset of the ciphers in the list returned by supportedCiphers().
Restricting the cipher suite must be done before the handshake phase, where the session cipher is chosen.
See also
ciphers(), setDefaultCiphers(), supportedCiphers()
Definition at line 1199 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.ciphers = ciphers;
 }
setCiphers() [2/2]
void QSslSocket::setCiphers (const QString & ciphers)
Sets the cryptographic cipher suite for this socket to ciphers, which is a colon-separated list of cipher suite names.
The ciphers are listed in order of preference, starting with the most preferred cipher. For example:
QSslSocket socket;
socket.setCiphers("DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:AES256-SHA");
Each cipher name in ciphers must be the name of a cipher in the list returned by supportedCiphers(). Restricting the cipher suite must be done before the handshake phase, where the session cipher is chosen.
See also
ciphers(), setDefaultCiphers(), supportedCiphers()
Definition at line 1219 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.ciphers.clear();
     foreach (const QString &cipherName, ciphers.split(QLatin1String(":"),QString::SkipEmptyParts)) {
         for (int i = 0; i < 3; ++i) {
             // ### Crude
             QSslCipher cipher(cipherName, QSsl::SslProtocol(i));
             if (!cipher.isNull())
                 d->configuration.ciphers << cipher;
         }
     }
 }
setDefaultCaCertificates()
void QSslSocket::setDefaultCaCertificates (const QList< QSslCertificate > & certificates) static
Sets the default CA certificate database to certificates.
The default CA certificate database is originally set to your system's default CA certificate database. You can override the default CA certificate database with your own CA certificate database using this function.
Each SSL socket's CA certificate database is initialized to the default CA certificate database.
See also
addDefaultCaCertificate()
Definition at line 1428 of file qsslsocket.cpp.
 {
     QSslSocketPrivate::setDefaultCaCertificates(certificates);
 }
setDefaultCiphers()
void QSslSocket::setDefaultCiphers (const QList< QSslCipher > & ciphers) static
Sets the default cryptographic cipher suite for all sockets in this application to ciphers, which must contain a subset of the ciphers in the list returned by supportedCiphers().
Restricting the default cipher suite only affects SSL sockets that perform their handshake phase after the default cipher suite has been changed.
See also
setCiphers(), defaultCiphers(), supportedCiphers()
Definition at line 1244 of file qsslsocket.cpp.
 {
     QSslSocketPrivate::setDefaultCiphers(ciphers);
 }
setLocalCertificate() [1/2]
void QSslSocket::setLocalCertificate (const QSslCertificate & certificate)
Sets the socket's local certificate to certificate.
The local certificate is necessary if you need to confirm your identity to the peer. It is used together with the private key; if you set the local certificate, you must also set the private key.
The local certificate and private key are always necessary for server sockets, but are also rarely used by client sockets if the server requires the client to authenticate.
See also
localCertificate(), setPrivateKey()
Definition at line 977 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.localCertificate = certificate;
 }
setLocalCertificate() [2/2]
void QSslSocket::setLocalCertificate (const QString & path, QSsl::EncodingFormat format = QSsl::Pem)
Sets the socket's local QSslCertificate {certificate} to the first one found in file path, which is parsed according to the specified format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 993 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     QFile file(path);
     if (file.open(QIODevice::ReadOnly | QIODevice::Text))
         d->configuration.localCertificate = QSslCertificate(file.readAll(), format);
 }
setPeerVerifyDepth()
void QSslSocket::setPeerVerifyDepth (int depth)
Sets the maximum number of certificates in the peer's certificate chain to be checked during the SSL handshake phase, to depth.
Since
4.4
Setting a depth of 0 means that no maximum depth is set, indicating that the whole certificate chain should be checked.
The certificates are checked in issuing order, starting with the peer's own certificate, then its issuer's certificate, and so on.
See also
peerVerifyDepth(), setPeerVerifyMode()
Definition at line 678 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (depth < 0) {
         qWarning("QSslSocket::setPeerVerifyDepth: cannot set negative depth of %d", depth);
         return;
     }
     d->configuration.peerVerifyDepth = depth;
 }
setPeerVerifyMode()
void QSslSocket::setPeerVerifyMode (QSslSocket::PeerVerifyMode mode)
Sets the socket's verify mode to mode.
Since
4.4
This mode decides whether QSslSocket should request a certificate from the peer (i.e., the client requests a certificate from the server, or a server requesting a certificate from the client), and whether it should require that this certificate is valid.
The default mode is AutoVerifyPeer, which tells QSslSocket to use VerifyPeer for clients and QueryPeer for servers.
Setting this mode after encryption has started has no effect on the current connection.
See also
peerVerifyMode(), setPeerVerifyDepth(), mode()
Definition at line 634 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.peerVerifyMode = mode;
 }
setPeerVerifyName()
void QSslSocket::setPeerVerifyName (const QString & hostName)
Sets a different host name, given by hostName, for the certificate validation instead of the one used for the TCP connection.
Since
4.8
See also
connectToHostEncrypted()
Definition at line 716 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->verificationPeerName = hostName;
 }
setPrivateKey() [1/2]
void QSslSocket::setPrivateKey (const QSslKey & key)
Sets the socket's private QSslKey {key} to key.
The private key and the local QSslCertificate {certificate} are used by clients and servers that must prove their identity to SSL peers.
Both the key and the local certificate are required if you are creating an SSL server socket. If you are creating an SSL client socket, the key and local certificate are required if your client must identify itself to an SSL server.
See also
privateKey(), setLocalCertificate()
Definition at line 1107 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.privateKey = key;
 }
setPrivateKey() [2/2]
void QSslSocket::setPrivateKey (const QString & fileName, QSsl::KeyAlgorithm algorithm = QSsl::Rsa, QSsl::EncodingFormat format = QSsl::Pem, const QByteArray & passPhrase = QByteArray())
Reads the string in file fileName and decodes it using a specified algorithm and encoding format to construct an QSslKey {SSL key}.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the encoded key is encrypted, passPhrase is used to decrypt it.
The socket's private key is set to the constructed key. The private key and the local QSslCertificate {certificate} are used by clients and servers that must prove their identity to SSL peers.
Both the key and the local certificate are required if you are creating an SSL server socket. If you are creating an SSL client socket, the key and local certificate are required if your client must identify itself to an SSL server.
See also
privateKey(), setLocalCertificate()
Definition at line 1136 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     QFile file(fileName);
     if (file.open(QIODevice::ReadOnly)) {
         d->configuration.privateKey = QSslKey(file.readAll(), algorithm,
                                               format, QSsl::PrivateKey, passPhrase);
     }
 }
setProtocol()
void QSslSocket::setProtocol (QSsl::SslProtocol protocol)
Sets the socket's SSL protocol to protocol.
This will affect the next initiated handshake; calling this function on an already-encrypted socket will not affect the socket's protocol.
Definition at line 585 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.protocol = protocol;
 }
setReadBufferSize()
void QSslSocket::setReadBufferSize (qint64 size)
Sets the size of QSslSocket's internal read buffer to be size bytes.
Since
4.4
Definition at line 877 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->readBufferMaxSize = size;
     if (d->plainSocket)
         d->plainSocket->setReadBufferSize(size);
 }
setSocketDescriptor()
bool QSslSocket::setSocketDescriptor (int socketDescriptor, SocketState state = ConnectedState, OpenMode openMode = ReadWrite)
Initializes QSslSocket with the native socket descriptor socketDescriptor.
Returns true if socketDescriptor is accepted as a valid socket descriptor; otherwise returns false. The socket is opened in the mode specified by openMode, and enters the socket state specified by state.
Note: It is not possible to initialize two sockets with the same native socket descriptor.
See also
socketDescriptor()
Definition at line 476 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::setSocketDescriptor(" << socketDescriptor << ','
              << state << ',' << openMode << ')';
 #endif
     if (!d->plainSocket)
         d->createPlainSocket(openMode);
     bool retVal = d->plainSocket->setSocketDescriptor(socketDescriptor, state, openMode);
     d->cachedSocketDescriptor = d->plainSocket->socketDescriptor();
     setSocketError(d->plainSocket->error());
     setSocketState(state);
     setOpenMode(openMode);
     setLocalPort(d->plainSocket->localPort());
     setLocalAddress(d->plainSocket->localAddress());
     setPeerPort(d->plainSocket->peerPort());
     setPeerAddress(d->plainSocket->peerAddress());
     setPeerName(d->plainSocket->peerName());
     return retVal;
 }
setSocketOption()
void QSslSocket::setSocketOption (QAbstractSocket::SocketOption option, const QVariant & value)
Sets the given option to the value described by value.
Since
4.6
See also
socketOption()
Definition at line 507 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (d->plainSocket)
         d->plainSocket->setSocketOption(option, value);
 }
setSslConfiguration()
void QSslSocket::setSslConfiguration (const QSslConfiguration & configuration)
Sets the socket's SSL configuration to be the contents of configuration.
Since
4.4
This function sets the local certificate, the ciphers, the private key and the CA certificates to those stored in configuration.
It is not possible to set the SSL-state related fields.
See also
setLocalCertificate(), setPrivateKey(), setCaCertificates(), setCiphers()
Definition at line 946 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     d->configuration.localCertificate = configuration.localCertificate();
     d->configuration.privateKey = configuration.privateKey();
     d->configuration.ciphers = configuration.ciphers();
     d->configuration.caCertificates = configuration.caCertificates();
     d->configuration.peerVerifyDepth = configuration.peerVerifyDepth();
     d->configuration.peerVerifyMode = configuration.peerVerifyMode();
     d->configuration.protocol = configuration.protocol();
     d->configuration.sslOptions = configuration.d->sslOptions;
     // if the CA certificates were set explicitly (either via
     // QSslConfiguration::setCaCertificates() or QSslSocket::setCaCertificates(),
     // we cannot load the certificates on demand
     if (!configuration.d->allowRootCertOnDemandLoading)
         d->allowRootCertOnDemandLoading = false;
 }
socketOption()
QVariant QSslSocket::socketOption (QAbstractSocket::SocketOption option)
Returns the value of the option option.
Since
4.6
See also
setSocketOption()
Definition at line 523 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (d->plainSocket)
         return d->plainSocket->socketOption(option);
     else
         return QVariant();
 }
sslConfiguration()
QSslConfiguration QSslSocket::sslConfiguration () const
Returns the socket's SSL configuration state.
Since
4.4
The default SSL configuration of a socket is to use the default ciphers, default CA certificates, no local private key or certificate.
The SSL configuration also contains fields that can change with time without notice.
See also
localCertificate(), peerCertificate(), peerCertificateChain(), sessionCipher(), privateKey(), ciphers(), caCertificates()
Definition at line 920 of file qsslsocket.cpp.
Referenced by QHttpNetworkReply::sslConfiguration().
 {
     Q_D(const QSslSocket);
     // create a deep copy of our configuration
     QSslConfigurationPrivate *copy = new QSslConfigurationPrivate(d->configuration);
     copy->ref = 0;              // the QSslConfiguration constructor refs up
     copy->sessionCipher = d->sessionCipher();
     return QSslConfiguration(copy);
 }
sslErrors() [1/2]
QList< QSslError > QSslSocket::sslErrors () const
Returns a list of the last SSL errors that occurred.
This is the same list as QSslSocket passes via the sslErrors() signal. If the connection has been encrypted with no errors, this function will return an empty list.
See also
connectToHostEncrypted()
Definition at line 1653 of file qsslsocket.cpp.
 {
     Q_D(const QSslSocket);
     return d->sslErrors;
 }
sslErrors [2/2]
void QSslSocket::sslErrors (const QList< QSslError > & errors) signal
QSslSocket emits this signal after the SSL handshake to indicate that one or more errors have occurred while establishing the identity of the peer.
The errors are usually an indication that QSslSocket is unable to securely identify the peer. Unless any action is taken, the connection will be dropped after this signal has been emitted.
If you want to continue connecting despite the errors that have occurred, you must call QSslSocket::ignoreSslErrors() from inside a slot connected to this signal. If you need to access the error list at a later point, you can call sslErrors() (without arguments).
errors contains one or more errors that prevent QSslSocket from verifying the identity of the peer.
Note: You cannot use Qt::QueuedConnection when connecting to this signal, or calling QSslSocket::ignoreSslErrors() will have no effect.
See also
peerVerifyError()
startClientEncryption
void QSslSocket::startClientEncryption () slot
Starts a delayed SSL handshake for a client connection.
This function can be called when the socket is in the ConnectedState but still in the UnencryptedMode . If it is not yet connected, or if it is already encrypted, this function has no effect.
Clients that implement STARTTLS functionality often make use of delayed SSL handshakes. Most other clients can avoid calling this function directly by using connectToHostEncrypted() instead, which automatically performs the handshake.
See also
connectToHostEncrypted(), startServerEncryption()
Definition at line 1682 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (d->mode != UnencryptedMode) {
         qWarning("QSslSocket::startClientEncryption: cannot start handshake on non-plain connection");
         return;
     }
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::startClientEncryption()";
 #endif
     d->mode = SslClientMode;
     emit modeChanged(d->mode);
     d->startClientEncryption();
 }
startServerEncryption
void QSslSocket::startServerEncryption () slot
Starts a delayed SSL handshake for a server connection.
This function can be called when the socket is in the ConnectedState but still in UnencryptedMode . If it is not connected or it is already encrypted, the function has no effect.
For server sockets, calling this function is the only way to initiate the SSL handshake. Most servers will call this function immediately upon receiving a connection, or as a result of having received a protocol-specific command to enter SSL mode (e.g, the server may respond to receiving the string "STARTTLS\r\n" by calling this function).
The most common way to implement an SSL server is to create a subclass of QTcpServer and reimplement QTcpServer::incomingConnection(). The returned socket descriptor is then passed to QSslSocket::setSocketDescriptor().
See also
connectToHostEncrypted(), startClientEncryption()
Definition at line 1717 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (d->mode != UnencryptedMode) {
         qWarning("QSslSocket::startServerEncryption: cannot start handshake on non-plain connection");
         return;
     }
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::startServerEncryption()";
 #endif
     d->mode = SslServerMode;
     emit modeChanged(d->mode);
     d->startServerEncryption();
 }
supportedCiphers()
QList< QSslCipher > QSslSocket::supportedCiphers () static
Returns the list of cryptographic ciphers supported by this system.
This list is set by the system's SSL libraries and may vary from system to system.
See also
defaultCiphers(), ciphers(), setCiphers()
Definition at line 1275 of file qsslsocket.cpp.
Referenced by QSslCipher::QSslCipher().
 {
     return QSslSocketPrivate::supportedCiphers();
 }
supportsSsl()
bool QSslSocket::supportsSsl () static
Returns true if this platform supports SSL; otherwise, returns false.
If the platform doesn't support SSL, the socket will fail in the connection phase.
Definition at line 1664 of file qsslsocket.cpp.
Referenced by QSslKeyPrivate::clear(), QSslKeyPrivate::decodePem(), QSslCertificatePrivate::QSslCertificate_from_X509(), QHttpPrivate::setSock(), and QSslKey::toPem().
 {
     return QSslSocketPrivate::supportsSsl();
 }
systemCaCertificates()
QList< QSslCertificate > QSslSocket::systemCaCertificates () static
This function provides the CA certificate database provided by the operating system.
The CA certificate database returned by this function is used to initialize the database returned by defaultCaCertificates(). You can replace that database with your own with setDefaultCaCertificates().
See also
caCertificates(), defaultCaCertificates(), setDefaultCaCertificates()
Definition at line 1462 of file qsslsocket.cpp.
 {
     // we are calling ensureInitialized() in the method below
     return QSslSocketPrivate::systemCaCertificates();
 }
waitForBytesWritten()
bool QSslSocket::waitForBytesWritten (int msecs = 30000) virtual
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 1582 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (!d->plainSocket)
         return false;
     if (d->mode == UnencryptedMode)
         return d->plainSocket->waitForBytesWritten(msecs);
     QElapsedTimer stopWatch;
     stopWatch.start();
     if (!d->connectionEncrypted) {
         // Wait until we've entered encrypted mode, or until a failure occurs.
         if (!waitForEncrypted(msecs))
             return false;
     }
     if (!d->writeBuffer.isEmpty()) {
         // empty our cleartext write buffer first
         d->transmit();
     }
     return d->plainSocket->waitForBytesWritten(qt_timeout_value(msecs, stopWatch.elapsed()));
 }
waitForConnected()
bool QSslSocket::waitForConnected (int msecs = 30000)
Waits until the socket is connected, or msecs milliseconds, whichever happens first.
If the connection has been established, this function returns true; otherwise it returns false.
See also
QAbstractSocket::waitForConnected()
Definition at line 1475 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (!d->plainSocket)
         return false;
     bool retVal = d->plainSocket->waitForConnected(msecs);
     if (!retVal) {
         setSocketState(d->plainSocket->state());
         setSocketError(d->plainSocket->error());
         setErrorString(d->plainSocket->errorString());
     }
     return retVal;
 }
waitForDisconnected()
bool QSslSocket::waitForDisconnected (int msecs = 30000)
Waits until the socket has disconnected or msecs milliseconds, whichever comes first.
If the connection has been disconnected, this function returns true; otherwise it returns false.
See also
QAbstractSocket::waitForDisconnected()
Definition at line 1613 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     // require calling connectToHost() before waitForDisconnected()
     if (state() == UnconnectedState) {
         qWarning("QSslSocket::waitForDisconnected() is not allowed in UnconnectedState");
         return false;
     }
     if (!d->plainSocket)
         return false;
     if (d->mode == UnencryptedMode)
         return d->plainSocket->waitForDisconnected(msecs);
     QElapsedTimer stopWatch;
     stopWatch.start();
     if (!d->connectionEncrypted) {
         // Wait until we've entered encrypted mode, or until a failure occurs.
         if (!waitForEncrypted(msecs))
             return false;
     }
     bool retVal = d->plainSocket->waitForDisconnected(qt_timeout_value(msecs, stopWatch.elapsed()));
     if (!retVal) {
         setSocketState(d->plainSocket->state());
         setSocketError(d->plainSocket->error());
         setErrorString(d->plainSocket->errorString());
     }
     return retVal;
 }
waitForEncrypted()
bool QSslSocket::waitForEncrypted (int msecs = 30000)
Waits until the socket has completed the SSL handshake and has emitted encrypted(), or msecs milliseconds, whichever comes first.
If encrypted() has been emitted, this function returns true; otherwise (e.g., the socket is disconnected, or the SSL handshake fails), false is returned.
The following example waits up to one second for the socket to be encrypted:
socket->connectToHostEncrypted("imap", 993);
if (socket->waitForEncrypted(1000))
    qDebug("Encrypted!");
If msecs is -1, this function will not time out.
See also
startClientEncryption(), startServerEncryption(), encrypted(), isEncrypted()
Definition at line 1505 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (!d->plainSocket || d->connectionEncrypted)
         return false;
     if (d->mode == UnencryptedMode && !d->autoStartHandshake)
         return false;
     QElapsedTimer stopWatch;
     stopWatch.start();
     if (d->plainSocket->state() != QAbstractSocket::ConnectedState) {
         // Wait until we've entered connected state.
         if (!d->plainSocket->waitForConnected(msecs))
             return false;
     }
     while (!d->connectionEncrypted) {
         // Start the handshake, if this hasn't been started yet.
         if (d->mode == UnencryptedMode)
             startClientEncryption();
         // Loop, waiting until the connection has been encrypted or an error
         // occurs.
         if (!d->plainSocket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed())))
             return false;
     }
     return d->connectionEncrypted;
 }
waitForReadyRead()
bool QSslSocket::waitForReadyRead (int msecs = 30000) virtual
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 1537 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
     if (!d->plainSocket)
         return false;
     if (d->mode == UnencryptedMode && !d->autoStartHandshake)
         return d->plainSocket->waitForReadyRead(msecs);
     // This function must return true if and only if readyRead() *was* emitted.
     // So we initialize "readyReadEmitted" to false and check if it was set to true.
     // waitForReadyRead() could be called recursively, so we can't use the same variable
     // (the inner waitForReadyRead() may fail, but the outer one still succeeded)
     bool readyReadEmitted = false;
     bool *previousReadyReadEmittedPointer = d->readyReadEmittedPointer;
     d->readyReadEmittedPointer = &readyReadEmitted;
     QElapsedTimer stopWatch;
     stopWatch.start();
     if (!d->connectionEncrypted) {
         // Wait until we've entered encrypted mode, or until a failure occurs.
         if (!waitForEncrypted(msecs)) {
             d->readyReadEmittedPointer = previousReadyReadEmittedPointer;
             return false;
         }
     }
     if (!d->writeBuffer.isEmpty()) {
         // empty our cleartext write buffer first
         d->transmit();
     }
     // test readyReadEmitted first because either operation above
     // (waitForEncrypted or transmit) may have set it
     while (!readyReadEmitted &&
            d->plainSocket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
     }
     d->readyReadEmittedPointer = previousReadyReadEmittedPointer;
     return readyReadEmitted;
 }
writeData()
qint64 QSslSocket::writeData (const char * data, qint64 len) protected virtual
Reimplemented Function
Reimplemented from QAbstractSocket.
Definition at line 1894 of file qsslsocket.cpp.
 {
     Q_D(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::writeData(" << (void *)data << ',' << len << ')';
 #endif
     if (d->mode == UnencryptedMode && !d->autoStartHandshake)
         return d->plainSocket->write(data, len);
     char *writePtr = d->writeBuffer.reserve(len);
     ::memcpy(writePtr, data, len);
     // make sure we flush to the plain socket's buffer
     QMetaObject::invokeMethod(this, "_q_flushWriteBuffer", Qt::QueuedConnection);
     return len;
 }
Friends and Related Functions
QSslSocketBackendPrivate
friend class QSslSocketBackendPrivate friend
Definition at line 214 of file qsslsocket.h.
The documentation for this class was generated from the following files:
/src/network/ssl/qsslsocket.h
/src/network/ssl/qsslsocket.cpp