Qt 4.8: QList< T > Class Template Reference
QList< T > Class Template Reference
The QList class is a template class that provides lists.
#include <qdatastream.h>
Classes
class const_iterator
The QList::const_iterator class provides an STL-style const iterator for QList and QQueue.
class iterator
The QList::iterator class provides an STL-style non-const iterator for QList and QQueue.
struct Node
Public Types
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for const T &.
typedef const_iterator ConstIterator
Qt-style synonym for QList::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QList::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef T value_type
Typedef for T.
Public Functions
void append (const T &t)
Inserts value at the end of the list.
void append (const QList< T > &t)
Appends the items of the value list to this list.
const T & at (int i) const
Returns the item at index position i in the list.
T & back ()
This function is provided for STL compatibility.
const T & back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the list.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all items from the list.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the list.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
QBool contains (const T &t) const
Returns true if the list contains an occurrence of value; otherwise returns false.
int count (const T &t) const
Returns the number of occurrences of value in the list.
int count () const
Returns the number of items in the list.
void detach ()
void detachShared ()
This prevents needless mallocs, and makes QList more exception safe in case of cleanup work done in destructors on empty lists.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const T &t) const
Returns true if this list is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator pos)
Removes the item associated with the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
iterator erase (iterator first, iterator last)
Removes all the items from begin up to (but not including) end.
T & first ()
Returns a reference to the first item in the list.
const T & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & front ()
This function is provided for STL compatibility.
const T & front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const T &t, int from=0) const
Returns the index position of the first occurrence of value in the list, searching forward from index position from.
void insert (int i, const T &t)
Inserts value at index position i in the list.
iterator insert (iterator before, const T &t)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the list contains no items; otherwise returns false.
bool isSharedWith (const QList< T > &other) const
T & last ()
Returns a reference to the last item in the list.
const T & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const T &t, int from=-1) const
Returns the index position of the last occurrence of value in the list, searching backward from index position from.
int length () const
This function is identical to count().
QList< T > mid (int pos, int length=-1) const
Returns a list whose elements are copied from this list, starting at position pos.
void move (int from, int to)
Moves the item at index position from to index position to.
bool operator!= (const QList< T > &l) const
Returns true if other is not equal to this list; otherwise returns false.
QList< T > operator+ (const QList< T > &l) const
Returns a list that contains all the items in this list followed by all the items in the other list.
QList< T > & operator+= (const QList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< T > & operator+= (const T &t)
Appends value to the list.
QList< T > & operator<< (const QList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< T > & operator<< (const T &t)
Appends value to the list.
QList< T > & operator= (const QList< T > &l)
Assigns other to this list and returns a reference to this list.
bool operator== (const QList< T > &l) const
Returns true if other is equal to this list; otherwise returns false.
const T & operator[] (int i) const
Same as at().
T & operator[] (int i)
Returns the item at index position i as a modifiable reference.
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const T &t)
Inserts value at the beginning of the list.
void push_back (const T &t)
This function is provided for STL compatibility.
void push_front (const T &t)
This function is provided for STL compatibility.
QList ()
Constructs an empty list.
QList (const QList< T > &l)
Constructs a copy of other.
int removeAll (const T &t)
Removes all occurrences of value in the list and returns the number of entries removed.
void removeAt (int i)
Removes the item at index position i.
void removeFirst ()
Removes the first item in the list.
void removeLast ()
Removes the last item in the list.
bool removeOne (const T &t)
Removes the first occurrence of value in the list and returns true on success; otherwise returns false.
void replace (int i, const T &t)
Replaces the item at index position i with value.
void reserve (int size)
Reserve space for alloc elements.
void setSharable (bool sharable)
int size () const
Returns the number of items in the list.
bool startsWith (const T &t) const
Returns true if this list is not empty and its first item is equal to value; otherwise returns false.
void swap (QList< T > &other)
Swaps list other with this list.
void swap (int i, int j)
Exchange the item at index position i with the item at index position j.
T takeAt (int i)
Removes the item at index position i and returns it.
T takeFirst ()
Removes the first item in the list and returns it.
T takeLast ()
Removes the last item in the list and returns it.
QSet< T > toSet () const
Returns a QSet object with the data contained in this QList.
std::list< T > toStdList () const
Returns a std::list object with the data contained in this QList.
QVector< T > toVector () const
Returns a QVector object with the data contained in this QList.
T value (int i) const
Returns the value at index position i in the list.
T value (int i, const T &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QList ()
Destroys the list.
Static Public Functions
static QList< T > fromSet (const QSet< T > &set)
Returns a QList object with the data contained in set.
static QList< T > fromStdList (const std::list< T > &list)
Returns a QList object with the data contained in list.
static QList< T > fromVector (const QVector< T > &vector)
Returns a QList object with the data contained in vector.
Private Functions
void detach_helper (int alloc)
void detach_helper ()
Node * detach_helper_grow (int i, int n)
void free (QListData::Data *d)
void node_construct (Node *n, const T &t)
void node_copy (Node *from, Node *to, Node *src)
void node_destruct (Node *n)
void node_destruct (Node *from, Node *to)
Properties
union {
QListData::Data * d
QListData p
};
Friends
class const_iterator
class iterator
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QList< T > &list)
Writes the list list to stream out.
QDataStream & operator>> (QDataStream &in, QList< T > &list)
Reads a list from stream in into list.
Detailed Description
template<typename T>
class QList< T >
The QList class is a template class that provides lists.
Note
This class or function is reentrant.
QList<T> is one of Qt's generic container classes. It stores a list of values and provides fast index-based access as well as fast insertions and removals.
QList<T>, QLinkedList<T>, and QVector<T> provide similar functionality. Here's an overview:
For most purposes, QList is the right class to use. Its index-based API is more convenient than QLinkedList's iterator-based API, and it is usually faster than QVector because of the way it stores its items in memory. It also expands to less code in your executable.
If you need a real linked list, with guarantees of constant time insertions in the middle of the list and iterators to items rather than indexes, use QLinkedList.
If you want the items to occupy adjacent memory positions, use QVector.
Internally, QList<T> is represented as an array of pointers to items of type T. If T is itself a pointer type or a basic type that is no larger than a pointer, or if T is one of Qt's shared classes, then QList<T> stores the items directly in the pointer array. For lists under a thousand items, this array representation allows for very fast insertions in the middle, and it allows index-based access. Furthermore, operations like prepend() and append() are very fast, because QList preallocates memory at both ends of its internal array. (See Algorithmic Complexity for details.) Note, however, that for unshared list items that are larger than a pointer, each append or insert of a new item requires allocating the new item on the heap, and this per item allocation might make QVector a better choice in cases that do lots of appending or inserting, since QVector allocates memory for its items in a single heap allocation.
Note that the internal array only ever gets bigger over the life of the list. It never shrinks. The internal array is deallocated by the destructor, by clear(), and by the assignment operator, when one list is assigned to another.
Here's an example of a QList that stores integers and a QList that stores QDate values:
QList<int> integerList;
QList<QDate> dateList;
Qt includes a QStringList class that inherits QList<QString> and adds a convenience function QStringList::join(). (QString::split() creates QStringLists from strings.)
QList stores a list of items. The default constructor creates an empty list. To insert items into the list, you can use operator<<():
QList<QString> list;
list << "one" << "two" << "three";
// list: ["one", "two", "three"]
QList provides these basic functions to add, move, and remove items: insert(), replace(), removeAt(), move(), and swap(). In addition, it provides the following convenience functions: append(), prepend(), removeFirst(), and removeLast().
QList uses 0-based indexes, just like C++ arrays. To access the item at a particular index position, you can use operator[](). On non-const lists, operator[]() returns a reference to the item and can be used on the left side of an assignment:
if (list[0] == "Bob")
    list[0] = "Robert";
Because QList is implemented as an array of pointers, this operation is very fast (constant time). For read-only access, an alternative syntax is to use at():
for (int i = 0; i < list.size(); ++i) {
    if (list.at(i) == "Jane")
        cout << "Found Jane at position " << i << endl;
}
at() can be faster than operator[](), because it never causes a deep copy to occur.
A common requirement is to remove an item from a list and do something with it. For this, QList provides takeAt(), takeFirst(), and takeLast(). Here's a loop that removes the items from a list one at a time and calls delete on them:
QList<QWidget *> list;
...
while (!list.isEmpty())
    delete list.takeFirst();
Inserting and removing items at either ends of the list is very fast (constant time in most cases), because QList preallocates extra space on both sides of its internal buffer to allow for fast growth at both ends of the list.
If you want to find all occurrences of a particular value in a list, use indexOf() or lastIndexOf(). The former searches forward starting from a given index position, the latter searches backward. Both return the index of a matching item if they find it; otherwise, they return -1. For example:
int i = list.indexOf("Jane");
if (i != -1)
    cout << "First occurrence of Jane is at position " << i << endl;
If you simply want to check whether a list contains a particular value, use contains(). If you want to find out how many times a particular value occurs in the list, use count(). If you want to replace all occurrences of a particular value with another, use replace().
QList's value type must be an assignable data type. This covers most data types that are commonly used, but the compiler won't let you, for example, store a QWidget as a value; instead, store a QWidget *. A few functions have additional requirements; for example, indexOf() and lastIndexOf() expect the value type to support operator==(). These requirements are documented on a per-function basis.
Like the other container classes, QList provides Java-style iterators (QListIterator and QMutableListIterator) and STL-style iterators (QList::const_iterator and QList::iterator). In practice, these are rarely used, because you can use indexes into the QList. QList is implemented in such a way that direct index-based access is just as fast as using iterators.
QList does not support inserting, prepending, appending or replacing with references to its own values. Doing so will cause your application to abort with an error message.
To make QList as efficient as possible, its member functions don't validate their input before using it. Except for isEmpty(), member functions always assume the list is not empty. Member functions that take index values as parameters always assume their index value parameters are in the valid range. This means QList member functions can fail. If you define QT_NO_DEBUG when you compile, failures will not be detected. If you don't define QT_NO_DEBUG, failures will be detected using Q_ASSERT() or Q_ASSERT_X() with an appropriate message.
To avoid failures when your list can be empty, call isEmpty() before calling other member functions. If you must pass an index value that might not be in the valid range, check that it is less than the value returned by size() but not less than 0.
See also
QListIterator, QMutableListIterator, QLinkedList, QVector
Definition at line 62 of file qdatastream.h.
Typedefs
const_pointer
template<typename T> QList< T >::const_pointer
Typedef for const T *.
Provided for STL compatibility.
Definition at line 308 of file qlist.h.
const_reference
template<typename T> QList< T >::const_reference
Typedef for const T &.
Provided for STL compatibility.
Definition at line 310 of file qlist.h.
ConstIterator
template<typename T> QList< T >::ConstIterator
Qt-style synonym for QList::const_iterator.
Definition at line 279 of file qlist.h.
difference_type
template<typename T> QList< T >::difference_type
Typedef for ptrdiff_t.
Provided for STL compatibility.
Definition at line 311 of file qlist.h.
Iterator
template<typename T> QList< T >::Iterator
Qt-style synonym for QList::iterator.
Definition at line 278 of file qlist.h.
pointer
template<typename T> QList< T >::pointer
Typedef for T *.
Provided for STL compatibility.
Definition at line 307 of file qlist.h.
reference
template<typename T> QList< T >::reference
Typedef for T &.
Provided for STL compatibility.
Definition at line 309 of file qlist.h.
size_type
template<typename T> QList< T >::size_type
Typedef for int.
Provided for STL compatibility.
Definition at line 305 of file qlist.h.
value_type
template<typename T> QList< T >::value_type
Typedef for T.
Provided for STL compatibility.
Definition at line 306 of file qlist.h.
Constructors and Destructors
QList() [1/2]
template<typename T> QList< T >::QList () inline
Constructs an empty list.
Definition at line 121 of file qlist.h.
 : d(&QListData::shared_null) { d->ref.ref(); }
QList() [2/2]
template<typename T> QList< T >::QList (const QList< T > & other) inline
Constructs a copy of other.
This operation takes constant time, because QList is implicitly shared. This makes returning a QList from a function very fast. If a shared instance is modified, it will be copied (copy-on-write), and that takes linear time.
See also
operator=()
Definition at line 122 of file qlist.h.
 : d(l.d) { d->ref.ref(); if (!d->sharable) detach_helper(); }
~QList()
template<typename T > Q_OUTOFLINE_TEMPLATE QList< T >::~QList ()
Destroys the list.
References to the values in the list and all iterators of this list become invalid.
Definition at line 729 of file qlist.h.
 {
     if (!d->ref.deref())
         free(d);
 }
Functions
append() [1/2]
template<typename T> Q_OUTOFLINE_TEMPLATE void QList< T >::append (const T & value)
Inserts value at the end of the list.
Example:
QList<QString> list;
list.append("one");
list.append("two");
list.append("three");
// list: ["one", "two", "three"]
This is the same as list.insert(size(), value).
This operation is typically very fast (constant time), because QList preallocates extra space on both sides of its internal buffer to allow for fast growth at both ends of the list.
See also
operator<<(), prepend(), insert()
Definition at line 507 of file qlist.h.
Referenced by QMenuPrivate::_q_actionTriggered(), QFileDialogPrivate::_q_autoCompleteFileName(), QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QFileSystemModelPrivate::_q_directoryChanged(), QFileSystemModelPrivate::_q_fileSystemChanged(), QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QWSServerPrivate::_q_newConnection(), QProcessPrivate::_q_notified(), QScriptDebuggerLocalsWidgetPrivate::_q_onCompletionTaskFinished(), QScriptDebuggerConsoleWidgetPrivate::_q_onCompletionTaskFinished(), QFileDialogPrivate::_q_pathChanged(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), QFileDialogPrivate::_q_selectionChanged(), QStateMachinePrivate::_q_start(), QNetworkReplyImplPrivate::_q_startOperation(), QFileDialogPrivate::_q_useNameFilter(), QHostInfoLookupManager::abortLookup(), QAccessibleAbstractScrollArea::accessibleChildren(), QMultiInputContext::actions(), QGestureEvent::activeGestures(), QDeclarativeImportsPrivate::add(), QMenuPrivate::QMacMenuPrivate::addAction(), QXmlQueryPrivate::addAdditionalNamespaceBinding(), QGraphicsAnchorLayoutPrivate::addAnchorMaybeParallel(), QPatternist::XsdAnnotated::addAnnotation(), QPatternist::XsdAnnotation::addApplicationInformation(), QPatternist::XsdComplexType::addAssertion(), QPatternist::XsdAttributeGroup::addAttributeUse(), QPatternist::XsdComplexType::addAttributeUse(), QDeclarativeData::addBoundSignal(), QDialogButtonBoxPrivate::addButton(), QSvgStructureNode::addChild(), QGraphicsItemPrivate::addChild(), QDeclarativeJS::Engine::addComment(), QMultiScreenCursor::addCursor(), QFileDialogPrivate::addDefaultSuffixToFiles(), QDeclarativeDataBlob::addDependency(), QDockAreaLayout::addDockWidget(), QPatternist::XsdAnnotation::addDocumentation(), QJSDebugService::addEngine(), QDeclarativeEngineDebugService::addEngine(), QDeclarativeState::addEntriesToRevertList(), QScriptDebuggerScriptsModel::addExtraScriptInfo(), QPatternist::XsdIdentityConstraint::addField(), QFutureSynchronizer< T >::addFuture(), QFontSubset::addGlyph(), QPatternist::XsdElement::addIdentityConstraint(), QImagePixmapCleanupHooks::addImageHook(), QDeclarativeContextData::addImportedScript(), QDeclarativeXmlQueryEngine::addIndexToRangeList(), QPatternist::GenericDynamicContext::addNodeModel(), QBBScreen::addOverlayWindow(), QInotifyFileSystemWatcherEngine::addPaths(), QKqueueFileSystemWatcherEngine::addPaths(), QDnotifyFileSystemWatcherEngine::addPaths(), QWindowsFileSystemWatcherEngine::addPaths(), QFSEventsFileSystemWatcherEngine::addPaths(), QPollingFileSystemWatcherEngine::addPaths(), QImagePixmapCleanupHooks::addPixmapDataDestructionHook(), QImagePixmapCleanupHooks::addPixmapDataModificationHook(), QHttpPrivate::addRequest(), QPatternist::XsdValidatingInstanceReader::addSchema(), QConnmanEngine::addServiceConfiguration(), QStateMachinePrivate::addStatesToEnter(), QWidgetBackingStore::addStaticWidget(), QMultiScreen::addSubScreen(), QPrinterPrivate::addToManualSetList(), QBasicUnixFontDatabase::addTTFile(), QFontDatabasePrivate::addTTFile(), QUrlModel::addUrls(), FlatListModel::addValue(), QDeclarativeInspectorService::addView(), QFileSystemModelPrivate::addVisibleFiles(), QFbScreen::addWindow(), QWindowsMimeList::addWindowsMime(), QAxServerBase::Advise(), QApplication::alert(), QMacPasteboardMime::all(), QPMCache::allPixmaps(), QHttpHeader::allValues(), QSqlIndex::append(), QByteDataBuffer::append(), QCoreApplicationPrivate::appendApplicationPathToLibraryPaths(), QPatternist::FunctionSignature::appendArgument(), QMdiAreaPrivate::appendChild(), QGraphicsItemPrivate::appendGraphicsTransform(), appendSeparator(), QSvgNode::appendStyleProperty(), QPSQLDriverPrivate::appendTables(), QStateMachinePrivate::applyProperties(), QMainWindowLayout::applyState(), QDeclarativeParser::Variant::asStringList(), astNodeToStringList(), QIcdEngine::asyncUpdateConfigurationsSlot(), QAudioDeviceInfoInternal::availableDevices(), QPrinterInfo::availablePrinters(), QScriptContext::backtrace(), QJSDebuggerAgent::backtrace(), QDeclarativeComponentPrivate::begin(), QOCIResultPrivate::bindValue(), QWindowSurface::buffer(), QDeclarativeEngineDebugService::buildStatesList(), QDialogButtonBox::buttons(), QMenuPrivate::calcCausedStack(), QTextureGlyphCache::calculateSubPixelPositionCount(), Maemo::DBusDispatcher::callAsynchronous(), QGestureEvent::canceledGestures(), QScriptObjectSnapshot::capture(), QWorkspace::cascade(), QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::CallTargetDescription::checkCallsiteCircularity(), QPatternist::XsdTypeChecker::checkConstrainingFacetsList(), NestedListModel::checkRoles(), QPatternist::checkVariableCircularity(), childKeysOrGroups(), QAInterface::children(), QDeclarativeVisualItemModelPrivate::children_append(), childWidgets(), classIDL(), QFontEngineQPF::cleanUpAfterClientCrash(), QColumnViewPrivate::closeColumns(), QPdfBaseEnginePrivate::closePrintDevice(), collectGroupRef(), QAccessibleTable2Cell::columnHeaderCells(), QColumnView::columnWidths(), QInputDialog::comboBoxItems(), QScriptDebuggerConsoleCommandManager::commandsInGroup(), QApplication::commitData(), QDeclarativeCompiler::compileTree(), QDeclarativeCompiler::completeComponentBuild(), QScriptCompletionTaskPrivate::completeScriptExpression(), QScriptDebuggerConsoleCommandManager::completions(), QPatternist::XsdSchema::complexTypes(), Graph< AnchorVertex, AnchorData >::connections(), QFutureInterfaceBasePrivate::connectOutputInterface(), QPatternist::Expression::constantPropagate(), convert(), QMacPasteboardMimeAny::convertFromMime(), QMacPasteboardMimeTypeName::convertFromMime(), QMacPasteboardMimePlainText::convertFromMime(), QMacPasteboardMimeUnicodeText::convertFromMime(), QMacPasteboardMimeHTMLText::convertFromMime(), QWindowsMimeURI::convertFromMime(), QMacPasteboardMimeTiff::convertFromMime(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), convertPath(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), Maemo::convertValue(), QPatternist::Validate::create(), QGraphicsAnchorLayoutPrivate::createCenterAnchors(), QBBIntegration::createDisplay(), QGraphicsScene::createItemGroup(), QScriptDebuggerConsolePrivate::createJob(), QWaylandDisplay::createNewScreen(), QDirectFBScreenPrivate::createPixmapData(), QPatternist::createReturnOrderBy(), QPatternist::createRootExpression(), QHeaderViewPrivate::createSectionSpan(), QTextTablePrivate::createTable(), QAxServerBase::DAdvise(), QScriptDebuggerLocalsModel::data(), QDeclarativePackagePrivate::data_append(), QDeclarativeEngineDebugPrivate::decode(), QDBusConnectionPrivate::deliverCall(), QGestureManager::deliverEvents(), QApplicationPrivate::dispatchEnterLeave(), QWaylandDisplay::displayHandleGlobal(), do_dbus_call(), QNetworkSessionPrivateImpl::do_open(), QScriptDebuggerBackend::doPendingEvaluate(), QDeclarativeXmlQueryEngine::doQuery(), QTextDocumentLayoutPrivate::drawFrame(), QPaintBufferEngine::drawStaticTextItem(), QFSFileEngine::drives(), QListWidget::dropEvent(), QTableWidget::dropEvent(), QTreeWidget::dropEvent(), QDeclarativeDomObject::dynamicProperties(), effectiveState(), QItemSelectionModel::emitSelectionChanged(), QClipboardWatcher::empty(), QQueue< QHostInfoRunnable *>::enqueue(), QDeclarativeVisualDataModelPrivate::ensureRoles(), QDir::entryInfoList(), QDir::entryList(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::epsilonClosure(), QPatternist::GeneralComparison::evaluateEBV(), QPatternist::CardinalityVerifier::evaluateSequence(), QPatternist::Path::evaluateSequence(), QPatternist::InScopePrefixesFN::evaluateSequence(), QXmlQuery::evaluateTo(), QScriptDebuggerCodeView::event(), QDB2Result::exec(), QScriptDebuggerCommandExecutor::execute(), QStateMachinePrivate::exitStates(), expandObject(), QPatternist::NodeSortExpression::expectedOperandTypes(), QPatternist::XSLTSimpleContentConstructor::expectedOperandTypes(), QPatternist::FunctionCall::expectedOperandTypes(), QPatternist::CurrentItemStore::expectedOperandTypes(), QPatternist::DynamicContextStore::expectedOperandTypes(), QPatternist::NamespaceConstructor::expectedOperandTypes(), QPatternist::EBVExtractor::expectedOperandTypes(), QPatternist::InstanceOf::expectedOperandTypes(), QPatternist::NodeComparison::expectedOperandTypes(), QPatternist::AndExpression::expectedOperandTypes(), QPatternist::AttributeNameValidator::expectedOperandTypes(), QPatternist::ComputedNamespaceConstructor::expectedOperandTypes(), QPatternist::CardinalityVerifier::expectedOperandTypes(), QPatternist::ItemVerifier::expectedOperandTypes(), QPatternist::IfThenClause::expectedOperandTypes(), QPatternist::StaticCompatibilityStore::expectedOperandTypes(), QPatternist::CollationChecker::expectedOperandTypes(), QPatternist::NCNameConstructor::expectedOperandTypes(), QPatternist::QNameConstructor::expectedOperandTypes(), QPatternist::StaticBaseURIStore::expectedOperandTypes(), QPatternist::CommentConstructor::expectedOperandTypes(), QPatternist::DocumentConstructor::expectedOperandTypes(), QPatternist::SimpleContentConstructor::expectedOperandTypes(), QPatternist::TextNodeConstructor::expectedOperandTypes(), QPatternist::AxisStep::expectedOperandTypes(), QPatternist::Atomizer::expectedOperandTypes(), QPatternist::ReturnOrderBy::expectedOperandTypes(), QPatternist::AttributeConstructor::expectedOperandTypes(), QPatternist::QuantifiedExpression::expectedOperandTypes(), QPatternist::ProcessingInstructionConstructor::expectedOperandTypes(), QPatternist::RangeExpression::expectedOperandTypes(), QPatternist::ArithmeticExpression::expectedOperandTypes(), QPatternist::ForClause::expectedOperandTypes(), QPatternist::FirstItemPredicate::expectedOperandTypes(), QPatternist::CombineNodes::expectedOperandTypes(), QPatternist::ElementConstructor::expectedOperandTypes(), QPatternist::ArgumentConverter::expectedOperandTypes(), QPatternist::LetClause::expectedOperandTypes(), QPatternist::ExpressionSequence::expectedOperandTypes(), QPatternist::CastableAs::expectedOperandTypes(), QPatternist::UntypedAtomicConverter::expectedOperandTypes(), QPatternist::GeneralComparison::expectedOperandTypes(), QPatternist::ValueComparison::expectedOperandTypes(), QPatternist::TemplateInvoker::expectedOperandTypes(), QPatternist::CopyOf::expectedOperandTypes(), QPatternist::CastAs::expectedOperandTypes(), QPatternist::TruthPredicate::expectedOperandTypes(), QPatternist::UserFunctionCallsite::expectedOperandTypes(), QPatternist::TreatAs::expectedOperandTypes(), QPatternist::GenericPredicate::expectedOperandTypes(), QPatternist::Path::expectedOperandTypes(), QPatternist::EvaluationCache< IsForGlobal >::expectedOperandTypes(), QPatternist::OrderBy::expectedOperandTypes(), QTextControl::extraSelections(), QFontDatabase::families(), QWSSoundServerPrivate::feedDevice(), QNlaThread::fetchConfigurations(), QZipReader::fileInfoList(), QCompletionEngine::filter(), filterProxyListByCapabilities(), QPatternist::TagValidationHandler::finalize(), find_translation(), findChildrenHelper(), QIconLoader::findIconHelper(), QListWidget::findItems(), QTableWidget::findItems(), QTreeWidget::findItems(), QStandardItemModel::findItems(), QGLEngineSharedShaders::findProgramInCache(), findSnapshotIdsRecursively(), QTextDocumentPrivate::finishEdit(), QDeclarativeListModel::flatten(), QDropEvent::format(), QMimeSourceWrapper::formats(), QXlibClipboardMime::formats_sys(), QInternalMimeData::formatsHelper(), QScanThread::foundNetwork(), QHostInfoAgent::fromName(), QScript::functionConnect(), QScriptDebuggerAgent::functionEntry(), QDockAreaLayoutInfo::gapIndex(), QDeclarativeCompiler::genContextCache(), generateGlyphTables(), generateName(), Maemo::IAPConf::getAll(), QConnmanEngine::getConfigurations(), QFileInfoGatherer::getFileInfos(), getNamedAttribute(), QDeclarativeXmlQueryEngine::getValuesOfKeyRoles(), Maemo::getVariantFromDBusMessage(), QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), QScriptToolTipJob::handleResponse(), handleSelectedRowsAttribute(), handleSplittersAttribute(), QBBScreenEventHandler::handleTouchEvent(), QWindowSystemInterface::handleTouchEvent(), QStateMachinePrivate::handleTransitionSignal(), handleVisibleRowsAttribute(), QStatePrivate::historyStates(), QGuiPlatformPlugin::iconThemeSearchPaths(), imageReadMimeFormats(), imageWriteMimeFormats(), QTextHtmlImporter::import(), indexesFromRange(), QPatternist::OptimizationPasses::Coordinator::init(), QDirPrivate::initFileLists(), initFontSubst(), QStateMachinePrivate::initializeAnimation(), QDirectFbIntegration::initializeScreen(), QSslSocketBackendPrivate::initSslContext(), QSettingsPrivate::iniUnescapedStringList(), QPictureIO::inputFormats(), QTextControlPrivate::inputMethodEvent(), QTextDocumentPrivate::insert_frame(), QGraphicsWidget::insertAction(), QWidget::insertAction(), QTreeWidgetItem::insertChildren(), QTreeModel::insertColumns(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertItem(), QToolBarAreaLayout::insertItem(), QComboBox::insertItems(), QFont::insertSubstitution(), QFont::insertSubstitutions(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QPatternist::Expression::invokeOptimizers(), isServerProcess(), QDeclarativeGridView::itemsInserted(), QDeclarativeListView::itemsInserted(), QAbstractXmlNodeModel::iterate(), QAccessibleMenuItem::keyBindings(), QKeySequence::keyBindings(), QDB2DriverPlugin::keys(), QOCIDriverPlugin::keys(), QODBCDriverPlugin::keys(), QPSQLDriverPlugin::keys(), QSymSQLDriverPlugin::keys(), QTDSDriverPlugin::keys(), QHttpHeader::keys(), QMap< int, QFrameInfo >::keys(), QHash< QExplicitlySharedDataPointer, QHash >::keys(), QObject::killTimer(), QInputContextFactory::languages(), QUrlModel::layoutChanged(), libraryPathList(), QCoreApplication::libraryPaths(), QDeclarativeVMEMetaObject::list_append(), QResourcePrivate::load(), Document::load(), QLibraryPrivate::load_sys(), QFontDatabasePrivate::loadFromCache(), loadWin(), QFontDatabase::loadXlfd(), FAREnforcer::logAuthAttempt(), QFSFileEnginePrivate::longFileName(), lookup(), QHostInfoLookupManager::lookupFinished(), macQuoteString(), QIdentityProxyModel::mapSelectionFromSource(), QIdentityProxyModel::mapSelectionToSource(), QIdentityProxyModel::match(), QAbstractItemModel::match(), QLocale::matchingLocales(), mdiAreaNavigate(), QItemSelection::merge(), mergeIndexes(), MetaObjectGenerator::metaObject(), QXlibMime::mimeAtomsForFormat(), QProxyModel::mimeData(), QUrlModel::mimeData(), QXlibMime::mimeFormatsForAtom(), QPatternist::NamespaceSupport::namespaceBindings(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::newConnection(), QPatternist::CachingIterator::next(), QPatternist::DistinctIterator::next(), QSvgStyleSelector::nodeIds(), QApplication::notify(), QWSPcMouseHandlerPrivate::notify(), QDBusXmlParser::object(), QWaylandClipboard::offer(), QApplicationPrivate::openPopup(), QPatternist::SingleContainer::operands(), QPatternist::TripleContainer::operands(), QPatternist::PairContainer::operands(), QPatternist::OperandsIterator::OperandsIterator(), QDeclarativeStatePrivate::operations_append(), QDBusMessage::operator<<(), operator>>(), QPictureIO::outputFormats(), QScript::QtFunction::overloadedIndexes(), QGraphicsSimpleTextItem::paint(), QDeclarativeStyledTextPrivate::parse(), QScriptXmlParser::parse(), QHttpHeader::parse(), QPatternist::XsdSchemaParser::parseAll(), parseAnimateColorNode(), QPatternist::XsdSchemaParser::parseChoice(), QPPDOptionsModel::parseChoices(), QNetworkManagerEngine::parseConnection(), QDateTimeParser::parseFormat(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPPDOptionsModel::parseGroups(), QHttpNetworkReplyPrivate::parseHeader(), QAuthenticatorPrivate::parseHttpResponse(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QCss::Parser::parseMedium(), QPPDOptionsModel::parseOptions(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSequence(), parseServerList(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QCss::Parser::parseSimpleSelector(), QPatternist::XsdSchemaParser::parseUnion(), QAbstractItemModel::persistentIndexList(), QMdiAreaPrivate::place(), QWorkspacePrivate::place(), QFontDatabase::pointSizes(), QCoreTextFontDatabase::populateFontDatabase(), QTextDocumentLayoutPrivate::positionFloat(), QStateMachinePrivate::postExternalEvent(), QStateMachinePrivate::postInternalEvent(), QXmlNamespaceSupport::prefixes(), QLineControl::processInputMethodEvent(), QJSDebugService::processMessage(), QDeclarativeDebugTrace::processMessage(), QStateMachinePrivate::properAncestors(), QDeclarativePropertyMapMetaObject::propertyCreated(), QBBButtonEventNotifier::QBBButtonEventNotifier(), QCocoaIntegration::QCocoaIntegration(), qDBusAddTimeout(), qDBusParametersForMethod(), QDeclarativeGridScaledImage::QDeclarativeGridScaledImage(), QEglFSIntegration::QEglFSIntegration(), qExtractSecurityPolicyFromString(), QGLEngineSharedShaders::QGLEngineSharedShaders(), QGtkStylePrivate::QGtkStylePrivate(), QIconTheme::QIconTheme(), QTest::qInvokeTestMethodDataEntry(), QLinuxFbIntegration::QLinuxFbIntegration(), QMinimalIntegration::QMinimalIntegration(), QMultiInputContext::QMultiInputContext(), QObject::QObject(), QScript::qobjectProtoFuncFindChildren(), QOpenKODEIntegration::QOpenKODEIntegration(), QPlatformCursor::QPlatformCursor(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QScriptDebuggerLocalsModelNode::QScriptDebuggerLocalsModelNode(), QScriptEngineAgent::QScriptEngineAgent(), QSQLiteResult::QSQLiteResult(), qt_client_enqueue(), qt_determine_writing_systems_from_truetype_bits(), qt_format_text(), qt_getLprPrinters(), qt_grab_cursor(), qt_init(), qt_perhapsAddPrinter(), qt_server_enqueue(), qt_strip_filters(), qt_try_modal(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QMainWindowLayout::qtmacToolbarDelegate(), qToStringList(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QSystemConfigurationProxyFactory::queryProxy(), QWin32PrintEnginePrivate::queryResolutions(), QUndoCommand::QUndoCommand(), QVFbIntegration::QVFbIntegration(), QVNCIntegration::QVNCIntegration(), QWindowsXPStyle::QWindowsXPStyle(), qWinRequestConfig(), qwsEventSourceDispatch(), QXlibIntegration::QXlibIntegration(), QUnixSocket::read(), readArrayBuffer(), MetaObjectGenerator::readEventInfo(), QWinSettingsPrivate::readKey(), QPngHandlerPrivate::readPngTexts(), QPacketProtocolPrivate::readyToRead(), QMdiAreaPrivate::rearrange(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QActionPrivate::redoGrabAlternate(), registerAutoParentFunction(), QCopChannel::registerChannel(), QDeclarativeEnginePrivate::registerFinalizedParserStatusObject(), registerFont(), registerInterface(), QDBusConnectionPrivate::registerServiceNoLock(), QGraphicsScenePrivate::registerTopLevelItem(), registerType(), QMacWindowFader::registerWindowToFade(), QScript::QObjectData::registerWrapper(), QFileSystemModel::remove(), removeDuplicateProxies(), QSidebar::removeEntry(), QCoreApplication::removeLibraryPath(), QFSEventsFileSystemWatcherEngine::removePaths(), QHeaderViewPrivate::removeSectionsFromSpans(), QGraphicsAnchorLayoutPrivate::replaceVertex(), QStyleSheetStyle::repolish(), QDeclarativeDirParser::reportError(), QCompletionModel::resetModel(), QHeaderViewPrivate::resizeSections(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QStateMachinePrivate::restorablesToPropertyList(), QMainWindowLayoutState::restoreState(), QDockAreaLayoutInfo::restoreState(), QToolBarAreaLayout::restoreState(), QFutureInterface< T >::results(), QMacPasteboard::retrieveData(), QMimeDataPrivate::retrieveTypedData(), QDeclarativeCompiler::rewriteBinding(), QAccessibleTable2Cell::rowHeaderCells(), QScanThread::run(), QSplitter::saveState(), QTextDocumentPrivate::scan_frames(), QNativeWifiEngine::scanComplete(), QScriptDebuggerPrivate::scheduleJob(), QScriptContext::scopeChain(), scriptValueToMessage(), QWidgetPrivate::scroll_sys(), QString::section(), QmlJSDebugger::LiveSingleSelectionManipulator::select(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), QTreeViewPrivate::select(), QColumnView::selectAll(), QAbstractItemViewPrivate::selectAll(), QListViewPrivate::selectAll(), QAccessibleTable2::selectedCells(), QAccessibleTable2::selectedColumns(), QItemSelectionModel::selectedColumns(), QAccessibleItemView::selectedColumns(), QFileDialog::selectedFiles(), QTableView::selectedIndexes(), QTreeView::selectedIndexes(), QListWidget::selectedItems(), QTableWidget::selectedItems(), QTreeWidget::selectedItems(), QmlJSDebugger::LiveSelectionTool::selectedItemsChanged(), QTableWidget::selectedRanges(), QAccessibleTable2::selectedRows(), QItemSelectionModel::selectedRows(), QAccessibleItemView::selectedRows(), QSqlRelationalTableModel::selectStatement(), QPacketProtocol::send(), NestedListModel::set(), QApplication::setActiveWindow(), QCoreApplication::setApplicationVersion(), QTreeModel::setColumnCount(), QDeclarativeListModelParser::setCustomData(), QTreeWidgetItem::setData(), QCalendarDateValidator::setFormat(), QHttpNetworkHeaderPrivate::setHeaderField(), QFileDialogComboBox::setHistory(), QFormLayoutPrivate::setItem(), ModelNode::setListValue(), QWSServer::setMaxWindowRect(), QWaylandClipboard::setMimeData(), QMacPasteboard::setMimeData(), QObjectPrivate::setParent_helper(), FlatListModel::setProperty(), QVideoSurfaceFormat::setProperty(), NestedListModel::setProperty(), QObject::setProperty(), QApplicationPrivate::setScreenTransformation(), QTableView::setSelection(), QTextOption::setTabArray(), QTextBlockFormat::setTabPositions(), QAbstractTransition::setTargetState(), QUrlModel::setUrl(), QMimeData::setUrls(), QSidebar::showContextMenu(), QFileDialogComboBox::showPopup(), QPatternist::XsdSchema::simpleTypes(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QSplitter::sizes(), sm_setProperty(), QFontDatabase::smoothSizes(), QStringListModel::sort(), QFileSystemModel::sort(), QListModel::sort(), QTableModel::sort(), QFileSystemModelPrivate::sortChildren(), QDirPrivate::sortFileList(), QDockAreaLayoutInfo::split(), QItemSelection::split(), QByteArray::split(), QString::split(), QFSCompleter::splitPath(), splitSpaceSemicolon(), QScriptDebuggerScriptedConsoleCommandJob::start(), QMacStylePrivate::startAnimate(), QWindowsVistaStylePrivate::startAnimation(), QWSWindow::startEmbed(), QPluginLoader::staticInstances(), QSortFilterProxyModelPrivate::store_persistent_indexes(), QScriptEnginePrivate::stringListFromArray(), QSettingsPrivate::stringListToVariantList(), QFontDatabase::styles(), subControlLayout(), QFont::substitutions(), QPatternist::XsdParticleChecker::subsumes(), QMdiAreaPrivate::subWindowList(), QPrinterInfo::supportedPaperSizes(), supportedPredefinedActions(), QMacPrintEnginePrivate::supportedResolutions(), QApplication::syncX(), QSslSocketPrivate::systemCaCertificates(), QDockAreaLayoutInfo::tab(), QTextOption::tabArray(), tabBarGetTabs(), QDB2Driver::tables(), QSQLiteDriver::tables(), QOCIDriver::tables(), QSQLite2Driver::tables(), QTDSDriver::tables(), QMYSQLDriver::tables(), QODBCDriver::tables(), QPSQLDriver::tables(), QTextBlockFormat::tabPositions(), QStandardItem::takeRow(), QPatternist::TemplateInvoker::TemplateInvoker(), QIconLoader::themeSearchPaths(), QStyleSheetStyle::titleBarLayout(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), tokenUntil(), QAbstractXmlForwardIterator< OutputType >::toList(), QSet< typename TokenLookupClass::NodeName >::toList(), QVector< QPoint >::toList(), toList(), toList< long >(), QApplication::topLevelWidgets(), topLevelWidgets(), QDBusDemarshaller::toStringListUnchecked(), QFontSubset::toTruetype(), QApplicationPrivate::translateTouchEvent(), translateWSAError(), QPatternist::ResolveURIFN::typeCheck(), QPatternist::FunctionCall::typeCheck(), QPatternist::DocumentFN::typeCheck(), QPatternist::Expression::typeCheckOperands(), QSystemLocalePrivate::uiLanguages(), QScriptEngine::uncaughtExceptionBacktrace(), QFileSystemEngine::uncListSharesOnServer(), QMap< int, QFrameInfo >::uniqueKeys(), QHash< QExplicitlySharedDataPointer, QHash >::uniqueKeys(), QNetworkConfigurationManagerPrivate::updateConfigurations(), QScriptEdit::updateExtraSelections(), QAudioDeviceInfoInternal::updateLists(), QDesktopWidgetPrivate::updateScreenList(), QFontDialogPrivate::updateSizes(), QMimeData::urls(), QUrlModel::urls(), QPatternist::TagValidationHandler::validate(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QMap< int, QFrameInfo >::values(), QHash< QExplicitlySharedDataPointer, QHash >::values(), Maemo::IAPConfPrivate::valueToVariant(), QScriptEnginePrivate::variantListFromArray(), QSettingsPrivate::variantListToStringList(), QPatternist::TypeChecker::verifyType(), QIconLoaderEngine::virtual_hook(), QMenuBarPrivate::wceCreateMenuBar(), QAbstractScrollAreaScrollBarContainer::widgets(), QWorkspace::windowList(), QWSDisplay::windowList(), QWSServer::windowList(), QHostInfoLookupManager::work(), QtIcoHandler::write(), QFontDatabase::writingSystems(), x11EventSourceDispatch(), QX11Data::xdndMimeAtomsForFormat(), QX11Data::xdndMimeFormatsForAtom(), xdndObtainData(), QPatternist::FunctionFactoryCollection::xslt20Factory(), QPatternist::yyparse(), and QDeclarativePixmapReader::~QDeclarativePixmapReader().
 {
     if (d->ref != 1) {
         Node *n = detach_helper_grow(INT_MAX, 1);
         QT_TRY {
             node_construct(n, t);
         } QT_CATCH(...) {
             --d->end;
             QT_RETHROW;
         }
     } else {
         if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) {
             Node *n = reinterpret_cast<Node *>(p.append());
             QT_TRY {
                 node_construct(n, t);
             } QT_CATCH(...) {
                 --d->end;
                 QT_RETHROW;
             }
         } else {
             Node *n, copy;
             node_construct(&copy, t); // t might be a reference to an object in the array
             QT_TRY {
                 n = reinterpret_cast<Node *>(p.append());;
             } QT_CATCH(...) {
                 node_destruct(&copy);
                 QT_RETHROW;
             }
             *n = copy;
         }
     }
 }
append() [2/2]
template<typename T> void QList< T >::append (const QList< T > & value) inline
Appends the items of the value list to this list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
See also
operator<<(), operator+=()
Definition at line 841 of file qlist.h.
 {
     *this += t;
 }
at()
template<typename T > const T & QList< T >::at (int i) const inline
Returns the item at index position i in the list.
i must be a valid index position in the list (i.e., 0 <= i < size()).
This function is very fast (constant time).
See also
value(), operator[]()
Definition at line 468 of file qlist.h.
Referenced by QScript::__setupPackage__(), QFileDialogPrivate::_q_autoCompleteFileName(), QMdiAreaPrivate::_q_closeTab(), QMdiAreaPrivate::_q_currentTabChanged(), QFileDialogPrivate::_q_deleteCurrent(), QFileSystemModelPrivate::_q_directoryChanged(), QGraphicsScenePrivate::_q_emitUpdated(), QFileSystemModelPrivate::_q_fileSystemChanged(), QMenuBarPrivate::_q_internalShortcutActivated(), QDeclarativeVisualDataModel::_q_itemsChanged(), QFileDialogPrivate::_q_navigateBackward(), QFileDialogPrivate::_q_navigateForward(), QWSServerPrivate::_q_newConnection(), QProcessPrivate::_q_notified(), _q_parseDosDir(), _q_parseUnixDir(), QUnixPrintWidgetPrivate::_q_printerChanged(), QGraphicsScenePrivate::_q_processDirtyItems(), QObjectPrivate::_q_reregisterTimers(), _q_resolveEntryAndCreateLegacyEngine_recursive(), QFileDialogPrivate::_q_selectionChanged(), QTreeWidgetPrivate::_q_selectionChanged(), QGroupBoxPrivate::_q_setChildrenEnabled(), QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex(), QFontComboBoxPrivate::_q_updateModel(), QFileDialogPrivate::_q_updateOkButton(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QFileDialogPrivate::_q_useNameFilter(), QHostInfoLookupManager::abortLookup(), QFileDialog::accept(), QGLFramebufferObjectPool::acquire(), QMenuBarPrivate::actionAt(), QMenuPrivate::actionAt(), QmlJSDebugger::QDeclarativeInspectorPlugin::activate(), QDBusConnectionPrivate::activateCall(), QInternal::activateCallbacks(), QMenuPrivate::activateCausedStack(), QWidgetPrivate::activateChildLayoutsRecursively(), QMdiAreaPrivate::activateHighlightedWindow(), QMenuPrivate::QMacMenuPrivate::addAction(), QGraphicsWidget::addActions(), QWidget::addActions(), QDialogButtonBoxPrivate::addButtonsToLayout(), QScriptDebuggerLocalsModelPrivate::addChildren(), QFileDialogPrivate::addDefaultSuffixToFiles(), QFontDatabasePrivate::addFont(), addFontToDatabase(), QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsScene::addItem(), QPrintPropertiesDialog::addItemToOptions(), QFSEventsFileSystemWatcherEngine::addPaths(), QTextEngine::addRequiredBoundaries(), QStateMachinePrivate::addStatesToEnter(), QGraphicsItemGroup::addToGroup(), QScriptDebuggerLocalsModelPrivate::addTopLevelObject(), QState::addTransition(), QUrlModel::addUrls(), QFileSystemModelPrivate::addVisibleFiles(), QTextCursorPrivate::adjustCursor(), QDialog::adjustPosition(), QDeclarativeTimeLinePrivate::advance(), QSequentialAnimationGroupPrivate::advanceForwards(), QApplication::alert(), alert_widget(), QWindowsMime::allFormatsForMime(), allKeys(), QWindowsMime::allMimesForFormats(), QSequentialAnimationGroupPrivate::animationActualTotalDuration(), QPatternist::Expression::announceFocusType(), QCopChannel::answer(), QSignalSpy::appendArgs(), Maemo::appendVariantToDBusMessage(), QDeclarativeState::apply(), QToolBarAreaLayout::apply(), QTextHtmlParser::applyAttributes(), QStateMachinePrivate::applyProperties(), QDBusPendingReplyData::argumentAt(), QCoreApplication::arguments(), QScriptEnginePrivate::arrayFromStringList(), QScriptEnginePrivate::arrayFromVariantList(), QDeclarativeMetaType::attachedPropertiesFuncById(), QTextHtmlStyleSelector::attribute(), QHttpNetworkReplyPrivate::authenticationMethod(), QTextCodec::availableCodecs(), QScriptEngine::availableExtensions(), QTextCodec::availableMibs(), bindFont(), QMultiScreen::blank(), QMultiScreen::blit(), QCss::Declaration::brushValues(), buddyString(), QDeclarativeCompiler::buildDynamicMeta(), QCss::StyleSheet::buildIndexes(), buildMatchRule(), QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativeEngineDebugService::buildObjectList(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildSignal(), QDeclarativeBindingCompilerPrivate::buildSignalTable(), QDeclarativeEngineDebugService::buildStatesList(), QPatternist::XsdStateMachineBuilder::buildTerm(), QDialogButtonBox::buttonRole(), QDialogButtonBox::buttons(), QPacketProtocolPrivate::bytesWritten(), QGLGlyphCache::cacheGlyphs(), QMenuBarPrivate::calcActionRects(), QPrintPreviewWidgetPrivate::calcCurrentPage(), QDeclarativeContents::calcHeight(), QGraphicsAnchorLayoutPrivate::calculateGraphs(), QGraphicsAnchorLayoutPrivate::calculateNonTrunk(), QTextureGlyphCache::calculateSubPixelPositionCount(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QDeclarativeContents::calcWidth(), QScriptValue::call(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::callPrecise(), QScript::callQtMethod(), QGraphicsScenePrivate::cancelGesturesForChildren(), QWindowsMimeURI::canConvertFromMime(), QAbstractItemViewPrivate::canDecode(), QUrlModel::canDrop(), QApplicationPrivate::canQuit(), QByteDataBuffer::canReadLine(), QScriptObjectSnapshot::capture(), QKeyMapper::changeKeyboard(), QAbstractItemModel::changePersistentIndexList(), QMultiInputContext::changeSlave(), QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdSchemaChecker::checkBasicComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkCircularInheritances(), QColumnViewPrivate::checkColumnCreation(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdTypeChecker::checkConstrainingFacetsBinary(), QPatternist::XsdTypeChecker::checkConstrainingFacetsBoolean(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDateTime(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDouble(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDuration(), QPatternist::XsdTypeChecker::checkConstrainingFacetsList(), QPatternist::XsdTypeChecker::checkConstrainingFacetsNotation(), QPatternist::XsdTypeChecker::checkConstrainingFacetsQName(), QPatternist::XsdTypeChecker::checkConstrainingFacetsSignedInteger(), QPatternist::XsdTypeChecker::checkConstrainingFacetsString(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnion(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnsignedInteger(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaChecker::checkInheritanceRestrictions(), NestedListModel::checkRoles(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), QUndoCommand::child(), QAccessibleWidget::childAt(), QAccessibleAbstractScrollArea::childAt(), QAccessibleApplication::childAt(), QDeclarativeItem::childAt(), QAccessibleMainWindow::childAt(), QWidgetPrivate::childAtRecursiveHelper(), QAccessibleItemRow::childIndex(), QDirModelPrivate::children(), QDeclarativeVisualItemModelPrivate::children_at(), QGraphicsItemPrivate::children_at(), children_at_helper(), QGraphicsItemPrivate::children_clear(), children_clear_helper(), QTreeWidgetItem::childrenCheckState(), childWidgets(), QRingBuffer< T >::chop(), QGLGlyphCache::cleanCache(), QGLGlyphCache::cleanupContext(), QWSServerPrivate::cleanupFonts(), QListModel::clear(), QTreeModel::clear(), QToolBar::clear(), QGraphicsSceneIndex::clear(), QPMCache::clear(), QResourcePrivate::clear(), ModelNode::clear(), QTextDocumentPrivate::clearFrame(), QStateMachinePrivate::clearHistory(), QAbstractItemViewPrivate::clearOrRemove(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QZipWriter::close(), QAxServerBase::Close(), QWidgetPrivate::close_helper(), QApplication::closeAllWindows(), QUnifiedTimer::closestPauseAnimationTimeToFinish(), QTextCodec::codecForName(), QSplitterPrivate::collapsible(), collectAllElements(), collectGroupRef(), QCss::Declaration::colorValues(), QItemSelectionModel::columnIntersectsSelection(), QTreeViewPrivate::columnRanges(), QApplication::commitData(), QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compile(), QDeclarativeCompiler::compile(), QDeclarativeCompiler::compileAlias(), QDeclarativePropertyChangesParser::compileList(), QPatternist::Template::compileParameters(), QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::compileTree(), QDeclarativeTransitionManager::complete(), QDeclarativeContents::complete(), QDeclarativeComponentPrivate::complete(), QDeclarativeCompiler::completeComponentBuild(), QScriptDebuggerConsoleCommandManager::completions(), QPatternist::XsdSchema::complexTypes(), QPatternist::TemplateInvoker::compress(), QPatternist::ReplaceFN::compress(), QPatternist::PatternPlatform::compress(), QCoreApplication::compressEvent(), QGraphicsItemPrivate::TransformData::computedFullTransform(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QLinuxFbIntegration::connect(), QDirectFBScreen::connect(), QNetworkManagerEngine::connectionFromId(), QMetaObject::connectSlotsByName(), QGraphicsAnchorLayoutPrivate::constraintsFromPaths(), QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints(), QScriptValue::construct(), QDeclarativeContextPrivate::context_at(), QDeclarativeContextPrivate::context_count(), QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected(), convert(), QWindowsMime::converterFromMime(), QWindowsMime::converterToMime(), QWindowsMimeURI::convertFromMime(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), convertPath(), QWindowsMimeURI::convertToMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), convertToRelative(), QShortcutMap::correctContext(), QShortcutMap::correctGraphicsWidgetContext(), QXIMInputContext::create_xim(), createArrayBuffer(), QDeclarativeBinding::createBinding(), QDeclarativeEnginePrivate::createCache(), QOleDropSource::createCursors(), createForName(), QEventDispatcherWin32::createInternalHwnd(), QGraphicsScene::createItemGroup(), QScriptDebuggerConsolePrivate::createJob(), QAxServerBase::createMenu(), QShortcutMap::createNewSequences(), QDeclarativeComponentPrivate::createObject(), QAxServerBase::createPopup(), QMainWindow::createPopupMenu(), MetaObjectGenerator::createPrototype(), QDeclarativeEnginePrivate::createQmlObject(), createReadHandlerHelper(), QWidgetPrivate::createRecursively(), QPatternist::createReturnOrderBy(), QHeaderViewPrivate::createSectionSpan(), QLocale::createSeparatedList(), QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), QMultiScreen::createSurface(), createSvgNode(), QWidgetPrivate::createWinId(), QPatternist::XsdValidatingInstanceReader::createXQuery(), QResourceFileEngineIterator::currentFileName(), QFontListView::currentText(), QStringListModel::data(), QDeclarativeXmlListModel::data(), QListModel::data(), ControlList::data(), QTreeWidgetItem::data(), NestedListModel::data(), QDeclarativePackagePrivate::data_at(), QDeclarativeFlickablePrivate::data_at(), QUrlModel::dataChanged(), QKeySequencePrivate::decodeString(), QPatternist::Expression::deepProperties(), QMenuBar::defaultAction(), QAudioDeviceFactory::defaultInputDevice(), QAudioDeviceFactory::defaultOutputDevice(), QScriptDebuggerAgent::deleteBreakpoint(), deleteChildGroups(), QObjectPrivate::deleteChildren(), QScriptDebuggerLocalsModelPrivate::deleteObjectSnapshots(), QDBusConnectionPrivate::deliverCall(), QWidget::destroy(), QMessageBoxPrivate::detectEscapeButton(), QGraphicsItem::deviceTransform(), QMultiScreen::disconnect(), QNativeWifiEngine::disconnectFromId(), QApplicationPrivate::dispatchEnterLeave(), QGraphicsScenePrivate::dispatchHoverEvent(), DllCanUnloadNow(), QAccessibleApplication::doAction(), QColumnViewPrivate::doLayout(), QDeclarativeXmlQueryEngine::doQuery(), QIcdEngine::doRequestUpdate(), QDragManager::drag(), QAbstractItemViewPrivate::draggablePaintPairs(), QListViewPrivate::draggablePaintPairs(), QGraphicsScenePrivate::draw(), QPainterPrivate::draw_helper(), QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::drawFrame(), QGraphicsScenePrivate::drawItems(), QGraphicsScene::drawItems(), QX11PaintEngine::drawPath(), QListWidget::dropEvent(), QTableWidget::dropEvent(), QTreeWidget::dropEvent(), QAbstractItemModel::dropMimeData(), QAbstractTableModel::dropMimeData(), QAbstractListModel::dropMimeData(), QDeclarativeCompiledData::dump(), ModelNode::dump(), QPatternist::XsdSchemaDebugger::dumpSchema(), QDeclarativeCompiler::dumpStats(), QPatternist::XsdSchemaDebugger::dumpType(), dumpwarning(), QAxBase::dynamicCallHelper(), effectiveState(), effectiveTotalRangeMinimum(), QTextHtmlExporter::emitFragment(), QItemSelectionModel::emitSelectionChanged(), QClipboardWatcher::empty(), QWidgetPrivate::enforceNativeChildren(), QResourcePrivate::ensureChildren(), QSslSocketPrivate::ensureCiphersAndCertsLoaded(), QResourcePrivate::ensureInitialized(), QWidget::ensurePolished(), QDeclarativeVisualDataModelPrivate::ensureRoles(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QGraphicsScenePrivate::enterModal(), QApplicationPrivate::enterModal(), QStateMachinePrivate::enterStates(), QIconLoaderEngine::entryForSize(), QGraphicsSceneBspTreeIndexPrivate::estimateItems(), QGraphicsSceneIndex::estimateTopLevelItems(), QPatternist::UnparsedTextAvailableFN::evaluateEBV(), QPatternist::DeepEqualFN::evaluateEBV(), QPatternist::IndexOfFN::evaluateSequence(), QPatternist::InsertBeforeFN::evaluateSequence(), QPatternist::SubsequenceFN::evaluateSequence(), QPatternist::FunctionAvailableFN::evaluateSingleton(), QPatternist::UnparsedTextFN::evaluateSingleton(), QPatternist::ContainsFN::evaluateSingleton(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::ReturnOrderBy::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::StartsWithFN::evaluateSingleton(), QPatternist::CompareFN::evaluateSingleton(), QPatternist::StringJoinFN::evaluateSingleton(), QPatternist::EndsWithFN::evaluateSingleton(), QPatternist::SubstringFN::evaluateSingleton(), QPatternist::SubstringBeforeFN::evaluateSingleton(), QPatternist::SubstringAfterFN::evaluateSingleton(), QPatternist::RoundHalfToEvenFN::evaluateSingleton(), QPatternist::LangFN::evaluateSingleton(), QPatternist::TranslateFN::evaluateSingleton(), QDeclarativeListModelWorkerAgent::event(), QDialogButtonBox::event(), QDeclarativePinchArea::event(), QMessageBox::event(), QApplication::event(), QWidget::event(), QWindowsStyle::eventFilter(), QMacStylePrivate::eventFilter(), QSqlResult::execBatch(), QOCICols::execBatch(), QScriptDebuggerCommandExecutor::execute(), QScript::QObjectConnectionManager::execute(), QStateMachinePrivate::executeTransitionContent(), QStateMachinePrivate::exitStates(), QToolBarLayout::expandedSize(), QItemSelectionModelPrivate::expandSelection(), QDockAreaLayoutInfo::expansive(), QDeclarativeGlobalScriptClass::explicitSetProperty(), QMultiScreen::exposeRegion(), QDirectFBScreen::exposeRegion(), QScreen::exposeRegion(), QScriptDebuggerAgent::extension(), familyList(), QWSSoundServerPrivate::feedDevice(), QFileInfoGatherer::fetchExtendedInformation(), QZipReader::fileData(), fillList(), QX11PaintEnginePrivate::fillPath(), QHttpNetworkConnectionPrivate::fillPipeline(), QIconModeViewBase::filterDropEvent(), QPatternist::TagValidationHandler::finalize(), find_child(), QDeclarativeImportedNamespace::find_helper(), find_translation(), QHttpNetworkReplyPrivate::findChallenge(), QScriptDebuggerLocalsModelNode::findChild(), findChildFrame(), QX11Data::findClientWindow(), QFontDatabase::findFont(), QDeclarativeCompiledBindingsPrivate::findgeneric(), QIconLoader::findIconHelper(), QListWidget::findItems(), QTableWidget::findItems(), QTreeWidget::findItems(), QStandardItemModel::findItems(), QStateMachinePrivate::findLCA(), findMenuBar(), QDBusConnectionPrivate::findMetaObject(), QGLEngineSharedShaders::findProgramInCache(), QScriptObjectSnapshot::findProperty(), findRealWindow(), QDockAreaLayoutInfo::findSeparator(), findSlot(), findSnapshotIdsRecursively(), QToolBarAreaLayout::findToolBar(), findWindowThatShouldDisplayMenubar(), QScript::QObjectData::findWrapper(), QTextDocumentLayoutPrivate::findY(), QAbstractButtonPrivate::fixFocusPolicy(), QListModel::flags(), QTextDocumentLayoutPrivate::floatMargins(), QEventDispatcherMac::flush(), QMenuBarPrivate::focusFirstAction(), QGLGlyphCache::fontEngineDestroyed(), QMimeDataWrapper::format(), QDropEvent::format(), QTextEngine::format(), QInternalMimeData::formats(), QXlibClipboardMime::formats_sys(), QInternalMimeData::formatsHelper(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTransitive(), QPaintBuffer::frameEndIndex(), QPaintBuffer::frameStartIndex(), QRingBuffer< T >::free(), QRawFont::fromFont(), QHostInfoAgent::fromName(), QDeclarativeCustomParserNodePrivate::fromProperty(), QDate::fromString(), QDateTime::fromString(), QScript::functionConnect(), QDockAreaLayoutInfo::gapIndex(), QToolBarAreaLayoutInfo::gapIndex(), QDockAreaLayout::gapRect(), QDeclarativeStatePrivate::generateActionList(), generateGlyphTables(), generateInterfaceXml(), generateName(), QFbScreen::generateRects(), QGestureEvent::gesture(), QGraphicsScenePrivate::gestureTargetsAtHotSpots(), NestedListModel::get(), getAllActionNames(), getBounds(), QConnmanEngine::getConfigurations(), getFamiliesAndSignatures(), getFcPattern(), QFileInfoGatherer::getFileInfos(), getGlyphData(), QGraphicsAnchorLayoutPrivate::getGraphParts(), QNetworkManagerEngine::getInterfaceFromId(), QMenuPrivate::getLastVisibleAction(), QDBusConnectionPrivate::getNameOwnerNoCache(), getNetWmState(), QMenuBarPrivate::getNextAction(), QWidgetPrivate::getOpaqueChildren(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::DeclarativeObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), QPrinter::getPageMargins(), getPrimaryScreen(), QGLProgramCache::getProgram(), getScreen(), QToolBarAreaLayout::getStyleOptionInfo(), getVariables(), QApplicationPrivate::globalEventProcessor(), QTextLine::glyphs(), QMultiScreen::haltUpdates(), handleChildrenAttribute(), QWSTtyKbPrivate::handleConsoleSwitch(), QDBusConnectionPrivate::handleSignal(), QStateMachinePrivate::handleTransitionSignal(), QTextHtmlStyleSelector::hasAttributes(), hasCircularSubstitutionGroup(), QPatternist::XsdSchemaChecker::hasConstraintIDAttributeUse(), QPatternist::XsdSchemaChecker::hasDuplicatedAttributeUses(), hasDuplicatedElementsInternal(), QInternalMimeData::hasFormat(), QInternalMimeData::hasFormatHelper(), hasIDAttributeUse(), QNetworkManagerEngine::hasIdentifier(), QPatternist::XsdSchemaChecker::hasMultipleIDAttributeUses(), QXlibIntegration::hasOpenGL(), QGraphicsScene::helpEvent(), QWSWindow::hide(), QWidgetPrivate::hideChildren(), QDialogPrivate::hideDefault(), QMessageBoxPrivate::hideSpecial(), QTextDocumentLayoutPrivate::hitTest(), QMainWindowLayout::hover(), QGuiPlatformPlugin::iconThemeSearchPaths(), if(), imageReadMimeFormats(), imageWriteMimeFormats(), QDeclarativeImportsPrivate::importExtension(), QScriptEngine::importExtension(), QScriptDebuggerLocalsModel::index(), QTreeModel::index(), QListModel::index(), QDirModel::index(), QPPDOptionsModel::index(), QTextEngine::indexAdditionalFormats(), QDeclarativeCompiledData::indexForFloat(), QDeclarativeCompiledData::indexForInt(), QToolBarLayout::indexOf(), QDeclarativeVisualItemModelPrivate::indexOf(), QDockAreaLayoutInfo::indexOf(), QToolBarAreaLayout::indexOf(), QRingBuffer< T >::indexOf(), indexOfDescendant(), indexOfMutating(), QDockAreaLayoutInfo::indexOfPlaceHolder(), QStatusBarPrivate::indexToLastNonPermanentWidget(), QDockAreaLayoutInfo::info(), QSettingsPrivate::iniEscapedStringList(), QScriptDebuggerLocalsModel::init(), QDeclarativeExpressionPrivate::init(), init_plugins(), QSignalSpy::initArgs(), QMultiScreen::initDevice(), QImageReaderPrivate::initHandler(), QMacPrintEnginePrivate::initialize(), initializeDb(), QDirectFbIntegration::initializeDirectFB(), QTextHtmlParserNode::initializeProperties(), QDeclarativePropertyPrivate::initProperty(), QSslSocketBackendPrivate::initSslContext(), QTextControlPrivate::inputMethodEvent(), QListModel::insert(), QTextDocumentPrivate::insert_frame(), QGraphicsWidget::insertActions(), QWidget::insertActions(), QTreeWidgetItem::insertChild(), QTreeWidgetItem::insertChildren(), QStandardItemPrivate::insertColumns(), QTreeModel::insertColumns(), QDockAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertItem(), QComboBox::insertItems(), QStandardItemPrivate::insertRows(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QFactoryLoader::instance(), QGraphicsItemPrivate::invalidateChildGraphicsEffectsRecursively(), QGraphicsItemPrivate::invalidateDepthRecursively(), QAxServerBase::Invoke(), QWidgetPrivate::isBackgroundInherited(), QApplicationPrivate::isBlockedByModal(), QGraphicsItem::isBlockedByModalPanel(), QMenu::isEmpty(), QStateMachinePrivate::isInFinalState(), QMultiScreen::isInterlaced(), QLibrary::isLibrary(), QWidgetPrivate::isOverlapped(), QLibraryPrivate::isPlugin(), QDateTimeEditPrivate::isSeparatorKey(), isServerProcess(), QPatternist::XsdSchemaHelper::isSimpleDerivationOk(), isSubstGroupHeadOf(), QPatternist::XsdSchemaHelper::isValidAttributeUsesExtension(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), QDBusUtil::isValidBusName(), QDBusUtil::isValidInterfaceName(), QDBusUtil::isValidObjectPath(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdTypeChecker::isValidString(), QDBusUtil::isValidUniqueConnectionName(), QToolBarAreaLayout::item(), QToolBarLayout::itemAt(), QDockAreaLayoutInfo::itemAt(), QToolBarAreaLayout::itemAt(), QListModel::itemData(), QDockAreaLayoutInfo::itemRect(), QToolBarAreaLayoutInfo::itemRect(), QGraphicsSceneBspTree::items(), QGraphicsSceneIndexPrivate::items_helper(), QDeclarativeGridView::itemsInserted(), QDeclarativeListView::itemsInserted(), QDeclarativeRepeater::itemsMoved(), QTreeView::keyboardSearch(), QDialog::keyPressEvent(), QMessageBox::keyPressEvent(), QDecorationFactory::keys(), QGenericPluginFactory::keys(), QMouseDriverFactory::keys(), QScreenDriverFactory::keys(), QKbdDriverFactory::keys(), QFactoryLoader::keys(), QTextCodecPlugin::keys(), QMetaEnum::keysToValue(), QObject::killTimer(), lastIndexOfMutating(), QMdiAreaPrivate::lastWindowAboutToBeDestroyed(), launchWebBrowser(), QToolBarLayout::layoutActions(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutCell(), QUrlModel::layoutChanged(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), QGraphicsScenePrivate::leaveModal(), QApplicationPrivate::leaveModal(), QCss::ValueExtractor::lengthValues(), QTextFormat::lengthVectorProperty(), libGreaterThan(), QGraphicsItemAnimationPrivate::linearValueForStep(), QSystemLibrary::load(), QResourcePrivate::load(), QLibraryPrivate::load_sys(), QFontEngineMultiXLFD::loadEngine(), QFontEngineMultiWin::loadEngine(), QFontEngineMultiQPA::loadEngine(), QFontEngineMultiQWS::loadEngine(), loadFromDatabase(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), loadWin(), QFontDatabase::loadXlfd(), QLibraryInfo::location(), longestCommonPrefix(), QWSWindow::lower(), macList(), make_win_eventUPP(), QResourceRoot::mappingRootSubdir(), QAbstractProxyModel::mapSelectionFromSource(), QAbstractProxyModel::mapSelectionToSource(), QGraphicsScenePrivate::markDirty(), markFrames(), QDockAreaLayoutInfo::maximumSize(), mdiAreaNavigate(), QMultiScreen::memoryNeeded(), QPatternist::XsdSchemaMerger::merge(), QItemSelection::merge(), QMenuPrivate::QMacMenuPrivate::merged(), mergeIndexes(), QDeclarativeEngineDebugService::messageReceived(), messageToScriptValue(), QMacPrintEngine::metric(), QProxyModel::mimeData(), QUrlModel::mimeData(), QListModel::mimeData(), QTreeModel::mimeData(), QSortFilterProxyModel::mimeData(), QTableModel::mimeData(), QAbstractItemModel::mimeData(), QTreeWidget::mimeData(), QStandardItemModel::mimeData(), QDockAreaLayoutInfo::minimumSize(), QToolBarAreaLayoutInfo::minimumSize(), QGraphicsItem::mouseMoveEvent(), QGraphicsScenePrivate::mousePressEventHandler(), QMultiScreenCursor::move(), QTreeView::moveCursor(), QAbstractButtonPrivate::moveFocus(), QWidgetBackingStore::moveStaticWidgets(), QToolBarAreaLayoutInfo::moveToolBar(), QBBIntegration::moveToScreen(), QVNCIntegration::moveToScreen(), QObjectPrivate::moveToThread_helper(), multicastMembershipHelper(), namedPrototype(), QNativeSocketEnginePrivate::nativeMulticastInterface(), QNativeSocketEnginePrivate::nativeSetMulticastInterface(), QAccessibleWidget::navigate(), QAccessibleAbstractScrollArea::navigate(), QAccessibleApplication::navigate(), QAccessibleItemRow::navigate(), QAccessibleMdiArea::navigate(), QAccessibleWorkspace::navigate(), QAccessibleMainWindow::navigate(), QNetworkManagerEngine::newAccessPoint(), QWSServerPrivate::newMouseHandler(), QPatternist::CachingIterator::next(), QDockAreaLayoutInfo::next(), Node::nextSibling(), QMdiAreaPrivate::nextVisibleSubWindow(), QFileSystemModelPrivate::node(), QApplication::notify(), QWhatsThisPrivate::notifyToplevels(), QDBusConnection::objectRegisteredAt(), QMultiScreen::onCard(), QAxClientSite::OnPosRectChange(), QWSServer::openKeyboard(), QWSServer::openMouse(), QDeclarativeStatePrivate::operations_at(), operator<<(), QVideoSurfaceFormatPrivate::operator==(), QDockAreaLayoutInfo::paintSeparators(), QWidgetPrivate::paintSiblingsRecursive(), QPatternist::Template::parametersAsHash(), QAxMetaObject::paramType(), QScriptXmlParser::parse(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), parseBrushValue(), parseColorValue(), QNetworkManagerEngine::parseConnection(), QNetworkCookie::parseCookies(), parseCSStoXMLAttrs(), parseDateString(), parseGeometry(), QPatternist::XsdSchemaParser::parseGlobalElement(), parseIp4(), parseIp6(), QPatternist::XsdSchemaParser::parseLocalElement(), QDeclarativeBindingCompilerPrivate::parseMethod(), QDBusMetaObjectGenerator::parseMethods(), QDeclarativeBindingCompilerPrivate::parseName(), QBBNavigatorEventNotifier::parsePPS(), QBBButtonEventNotifier::parsePPS(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::ReplaceFN::parseReplacement(), QPatternist::XsdSchemaParser::parseSchema(), parseServerList(), QDBusMetaObjectGenerator::parseSignals(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QHostAddress::parseSubnet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QFileSystemModelPrivate::passNameFilters(), QPatternist::PatternPlatform::pattern(), QRingBuffer< T >::peek(), QMacWindowFader::performFade(), QDockAreaLayoutInfo::plug(), populate_database(), QToolButtonPrivate::popupTimerDone(), QScriptDebuggerAgent::positionChange(), QDeclarativeGridViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::positionViewAtIndex(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), QDeclarativeEngineDebugService::prepareDeferredObjects(), QDBusConnectionPrivate::prepareHook(), QDBusConnectionPrivate::prepareReply(), QDeclarativeBasePositioner::prePositioning(), QDockAreaLayoutInfo::prev(), Node::previousSibling(), QPainterReplayer::process(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QWSServer::processKeyEvent(), QFtpPI::processReply(), QDeclarativeBindingCompiler::program(), QTreeWidgetItemPrivate::propagateDisabled(), QWidgetPrivate::propagatePaletteChange(), QDeclarativeDomObject::properties(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), QMacPrintEngine::property(), QVideoSurfaceFormat::property(), QDeclarativeDomObject::property(), NamedNodeMapClass::property(), NodeListClass::property(), prototype(), QGraphicsSceneBspTreeIndexPrivate::purgeRemovedItems(), q_createNativeChildrenAndSetParent(), Q_GLOBAL_STATIC_WITH_ARGS(), qax_generateDocumentation(), qAxFactory(), QTest::qCompare(), qDBusGenerateMetaObjectXml(), qDBusInterfaceFromMetaObject(), qDBusPropertyGet(), qDBusPropertyGetAll(), qDBusPropertySet(), qDBusReplyFill(), qDBusReplyToScriptValue(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), QDirIteratorPrivate::QDirIteratorPrivate(), QDirPrivate::QDirPrivate(), QTest::qExec(), qGeomCalc(), QTest::qMedian(), QDeclarativeTypeData::qmldirForUrl(), QMultiInputContext::QMultiInputContext(), QScript::qobjectProtoFuncFindChildren(), QOpenKODEWindow::QOpenKODEWindow(), QTest::qPrintDataTags(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QTest::qSignalDumperCallback(), QSslSocketBackendPrivate::QSslCipher_from_SSL_CIPHER(), qstring_to_xtp(), QtPrivate::QStringList_contains(), QtPrivate::QStringList_filter(), QtPrivate::QStringList_join(), QtPrivate::QStringList_removeDuplicates(), qt_cleanup(), qt_create_commandline(), qt_custom_file_engine_handler_create(), qt_defaultDpiX(), qt_defaultDpiY(), QObject::qt_find_obj_child(), qt_get_screen(), qt_getDefaultFromHomePrinters(), qt_getLprPrinters(), qt_grab_cursor(), qt_mac_activate_action(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), qt_mac_get_accel(), qt_mac_get_widget_rgn(), qt_mac_menu_event(), qt_mac_menu_merge_action(), qt_mac_set_modal_state(), qt_mac_should_disable_menu(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), QAxServerBase::qt_metacall(), qt_painter_removePaintDevice(), qt_parseEtcLpMember(), qt_parseEtcLpPrinters(), qt_parseSpoolInterface(), qt_perhapsAddPrinter(), qt_qFindChild_helper(), qt_qFindChildren_helper(), qt_set_windows_updateScrollBar(), qt_wce_get_quit_action(), qt_win_selected_filter(), qt_x11_recreateNativeWidgetsRecursive(), QTestEventList::QTestEventList(), qTopLevelDomain(), qToStringList(), QTreeWidgetItem::QTreeWidgetItem(), QAbstractButtonPrivate::queryButtonList(), QAbstractButtonPrivate::queryCheckedButton(), QWin32PrintEnginePrivate::queryDefault(), NamedNodeMapClass::queryProperty(), queuedConnectionTypes(), QVariantToVARIANT(), QVFbIntegration::QVFbIntegration(), QWaylandSelection::QWaylandSelection(), QWindowsXPStyle::QWindowsXPStyle(), QWSDirectPainterSurface::QWSDirectPainterSurface(), QXIMInputContext::QXIMInputContext(), QWSWindow::raise(), QPacketProtocol::read(), QTreeWidgetItem::read(), read_xpm_body(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QHttpMultiPartIODevice::readData(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), MetaObjectGenerator::readEventInterface(), MetaObjectGenerator::readFuncsInfo(), QPngHandlerPrivate::readPngImage(), QRingBuffer< T >::readPointerAtPosition(), QPatternist::XsdSchemaParser::readXPathAttribute(), QPatternist::XsdSchemaParser::readXPathExpression(), QScriptDebuggerLocalsModelPrivate::reallySyncIndex(), realMaxSize(), realMinSize(), QMdi::RegularTiler::rearrange(), QMdi::SimpleCascader::rearrange(), QMdi::IconTiler::rearrange(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QMenuPrivate::QWceMenuPrivate::rebuild(), QPanGestureRecognizer::recognize(), QPinchGestureRecognizer::recognize(), QSwipeGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), QTapAndHoldGestureRecognizer::recognize(), QAccessibleAbstractScrollArea::rect(), QCss::Declaration::rectValue(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QPainter::redirected(), QUndoCommand::redo(), QActionPrivate::redoGrabAlternate(), QGraphicsAnchorLayoutPrivate::refreshAllSizeHints(), QDBusConnection::registerObject(), QDBusConnectionInterface::registerService(), QStateMachinePrivate::registerTransitions(), QAccessibleWidget::relationTo(), QAccessibleApplication::relationTo(), QDir::relativeFilePath(), QDBusAdaptorConnector::relay(), QListModel::remove(), QDeclarativeTimeLine::remove(), QFileSystemModel::remove(), NestedListModel::remove(), QToolBarAreaLayout::remove(), QMacSettingsPrivate::remove(), QWinSettingsPrivate::remove(), QTextFramePrivate::remove_me(), QNetworkManagerEngine::removeAccessPoint(), QDialogButtonBox::removeButton(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), QWidgetBackingStore::removeDirtyWidget(), removeDuplicateProxies(), QSidebar::removeEntry(), QObject::removeEventFilter(), QGraphicsItemGroup::removeFromGroup(), removeInvisibleWidgetsFromList(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsSceneBspTree::removeItems(), QFSEventsFileSystemWatcherEngine::removePaths(), QCoreApplicationPrivate::removePostedEvent(), QCoreApplication::removePostedEvents(), QCoreApplicationPrivate::removePostedTimerEvent(), QHeaderViewPrivate::removeSectionsFromSpans(), QHeaderViewPrivate::removeSpans(), QToolBarAreaLayoutInfo::removeToolBarBreak(), QFileSystemModelPrivate::removeVisibleFile(), QGraphicsScene::render(), QAbstractItemViewPrivate::renderToPixmap(), MetaObjectGenerator::replacePrototype(), QPaintEngineExPrivate::replayClipOperations(), QRingBuffer< T >::reserve(), QGraphicsScenePrivate::resetDirtyItem(), QGraphicsSceneBspTreeIndexPrivate::resetIndex(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroups(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::XsdSchemaResolver::resolveTermReferences(), QDeclarativeItemPrivate::resources_at(), QDeclarativeItemPrivate::resources_clear(), QMultiScreen::restore(), QPainter::restoreRedirected(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedConstraints(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph(), QFileDialog::restoreState(), QMainWindowLayoutState::restoreState(), QDockAreaLayoutInfo::restoreState(), QToolBarAreaLayout::restoreState(), QGraphicsAnchorLayoutPrivate::restoreVertices(), QWSPcMouseHandlerPrivate::resume(), QMultiScreen::resumeUpdates(), QFileDialogPrivate::retranslateStrings(), QInternalMimeData::retrieveData(), QMacPasteboard::retrieveData(), QMimeDataPrivate::retrieveTypedData(), QSequentialAnimationGroupPrivate::rewindForwards(), QAccessibleWidget::role(), QItemSelectionModel::rowIntersectsSelection(), QDeclarativeVME::run(), QBenchmarkValgrindUtils::runCallgrindSubProcess(), QDeclarativeVME::runDeferred(), sanityCheck(), QMultiScreen::save(), QDeclarativeParentChange::saveCurrentValues(), QCUPSSupport::saveOptions(), QDockAreaLayoutInfo::saveState(), QToolBarAreaLayout::saveState(), QGraphicsItem::sceneEvent(), QDeclarativePinchArea::sceneEventFilter(), QWidgetPrivate::screenGeometry(), QScriptDebuggerScriptsModel::scriptFunctionInfoFromIndex(), QDeclarativeEnginePrivate::scriptValueFromVariant(), QWidgetPrivate::scroll_sys(), QWidgetPrivate::scrollChildren(), QMenuPrivate::scrollMenu(), QString::section(), QColumnView::selectAll(), QItemSelectionModel::selectedColumns(), QAccessibleItemView::selectedColumns(), QAbstractItemViewPrivate::selectedDraggableIndexes(), QFileDialog::selectedFiles(), QTableView::selectedIndexes(), QListView::selectedIndexes(), QTreeView::selectedIndexes(), QListWidget::selectedItems(), QTableWidget::selectedItems(), QTreeWidget::selectedItems(), QTableWidget::selectedRanges(), QItemSelectionModel::selectedRows(), QAccessibleItemView::selectedRows(), QItemSelectionModel::selection(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QStateMachinePrivate::selectTransitions(), send_targets_selection(), QFutureInterfaceBasePrivate::sendCallOut(), QActionPrivate::sendDataChanged(), QWSServer::sendIMEvent(), QCopChannel::sendLocally(), QJSDebugService::sendMessages(), QDeclarativeDebugTrace::sendMessages(), QWidgetPrivate::sendPendingMoveAndResizeEvents(), QCoreApplicationPrivate::sendPostedEvents(), sendResizeEvents(), QXlibClipboard::sendTargetsSelection(), QGraphicsScenePrivate::sendTouchBeginEvent(), QDockAreaLayoutInfo::separatorMove(), QDockAreaLayoutInfo::separatorRect(), QDockAreaLayoutInfo::separatorRegion(), Graph< AnchorVertex, AnchorData >::serializeToDot(), NestedListModel::set(), QWorkspaceChild::setActive(), QWSWindow::setActiveWindow(), QApplication::setActiveWindow(), QGraphicsScene::setActiveWindow(), QWizard::setButtonLayout(), QColumnView::setColumnWidths(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), QListModel::setData(), QTreeWidgetItem::setData(), QDialogPrivate::setDefault(), QMultiScreen::setDirty(), QPPDOptionsEditor::setEditorData(), QWidgetPrivate::setEnabled_helper(), QTextControl::setExtraSelections(), QMenuPrivate::setFirstActionActive(), QTreeWidgetItem::setFlags(), QGraphicsScenePrivate::setFocusItemHelper(), QOpenKODEWindow::setGeometry(), QRuntimeGraphicsSystem::setGraphicsSystem(), QTreeWidget::setHeaderLabels(), QTableWidget::setHorizontalHeaderLabels(), QStandardItemModel::setHorizontalHeaderLabels(), QDeclarativeItemPrivate::setImplicitLayoutMirror(), QGraphicsItem::setInputMethodHints(), QGraphicsScene::setItemIndexMethod(), QApplication::setLayoutDirection(), QGraphicsWidgetPrivate::setLayoutDirection_helper(), QWidgetPrivate::setLayoutDirection_helper(), QWidgetPrivate::setLocale_helper(), QMenuPrivate::setMacMenuEnabled(), setMaxWindowRect(), QWSServer::setMaxWindowRect(), QApplicationPrivate::setMaxWindowRect(), QDeclarativeEngineDebugService::setMethodBody(), QMacPasteboard::setMimeData(), QWidgetPrivate::setModal_sys(), QWidgetResizeHandler::setMouseCursor(), QFileSystemModel::setNameFilters(), QMenuBar::setNativeMenuBar(), QObject::setObjectName(), QPatternist::TripleContainer::setOperands(), QWSOnScreenSurface::setPermanentState(), QStyleSheetStyle::setProperties(), QVideoSurfaceFormat::setProperty(), NestedListModel::setProperty(), setScreenTransformation(), QApplicationPrivate::setScreenTransformation(), QMenu::setSeparatorsCollapsible(), QActionPrivate::setShortcutEnabled(), QDeclarativePropertyPrivate::setSignalExpression(), QDeclarativeFontLoader::setSource(), QPatternist::UserFunctionCallsite::setSource(), QWidgetPrivate::setStyle_helper(), QWidget::setTabOrder(), QAbstractTransition::setTargetStates(), QAccessibleAbstractScrollArea::setText(), QObjectPrivate::setThreadData_helper(), QGraphicsItem::setTransformations(), QWidgetPrivate::setUpdatesEnabled_helper(), QScriptExtensionPlugin::setupPackage(), QMimeData::setUrls(), QTableWidget::setVerticalHeaderLabels(), QStandardItemModel::setVerticalHeaderLabels(), QWidgetPrivate::setWindowIcon_helper(), QMultiScreen::sharedRamSize(), shiftConstraints(), QWSWindow::show(), QWidget::show(), QWidgetPrivate::showChildren(), QMultiScreen::shutdownDevice(), QDeclarativePropertyPrivate::signalExpression(), QPatternist::XsdSchema::simpleTypes(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QDockAreaLayoutInfo::sizeHint(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), QCss::ValueExtractor::sizeValue(), QDockAreaLayoutItem::skip(), QToolBarAreaLayoutLine::skip(), QMultiInputContext::slave(), sm_performSaveYourself(), socketNotifierSourceCheck(), socketNotifierSourceDispatch(), QMultiScreen::solidFill(), QGraphicsAnchorLayoutPrivate::solveMinMax(), QGraphicsAnchorLayoutPrivate::solvePreferred(), QStringListModel::sort(), QFileSystemModel::sort(), QListModel::sort(), QFileSystemModelPrivate::sortChildren(), QDirPrivate::sortFileList(), QTreeModel::sortItems(), QDockAreaLayoutInfo::split(), QFSCompleter::splitPath(), QGraphicsItem::stackBefore(), QScriptCompletionTask::start(), QProcessPrivate::startDetached(), QSslSocketBackendPrivate::startHandshake(), QProcessPrivate::startProcess(), QAccessibleAbstractScrollArea::state(), QAccessibleMdiArea::state(), QAccessibleWorkspace::state(), QNetworkSessionPrivateImpl::stateChange(), QWidgetBackingStore::staticContents(), QXmlQueryPrivate::staticContext(), QPatternist::SumFN::staticType(), QPatternist::SubsequenceFN::staticType(), QSettingsPrivate::stringListToVariantList(), QApplication::style(), QCss::StyleSelector::styleRulesForNode(), QScreen::subScreenIndexAt(), QPatternist::XsdParticleChecker::subsumes(), QWidgetPrivate::subtractOpaqueSiblings(), QMdiAreaPrivate::subWindowList(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QPrinter::supportedPaperSources(), QPrinter::supportedResolutions(), QWSPcMouseHandlerPrivate::suspend(), QWidgetBackingStore::sync(), QApplication::syncX(), QSslSocketPrivate::systemCaCertificates(), QDockAreaLayoutInfo::tab(), QMainWindow::tabifiedDockWidgets(), QListModel::take(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), QDeclarativeCompiler::testQualifiedEnumAssignment(), QAccessibleMenu::text(), QAccessibleAbstractScrollArea::text(), QClipboard::text(), QFontListView::text(), QImage::textLanguages(), QImage::textList(), QMacStylePrivate::timerEvent(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), QPainterPath::toFillPolygon(), QPainterPath::toFillPolygons(), QToolBarAreaLayout::toolBarBreak(), topLevelWidgets(), QScriptContext::toString(), NestedListModel::toString(), QFontSubset::toTruetype(), QGraphicsScenePrivate::touchEventHandler(), QDeclarativeItemPrivate::transform_at(), QDeclarativeTransitionManager::transition(), QDeclarativePropertyAction::transition(), QDeclarativePropertyAnimation::transition(), QDeclarativeParentAnimation::transition(), QETWidget::translateMouseEvent(), QApplicationPrivate::translateRawTouchEvent(), translateWSAError(), QMeeGoGraphicsSystem::triggerSwitchCallbacks(), QFontSubset::type1AddedGlyphs(), QPatternist::DeepEqualFN::typeCheck(), QPatternist::ElementConstructor::typeCheck(), QPatternist::IndexOfFN::typeCheck(), QPatternist::DocumentFN::typeCheck(), QPatternist::SumFN::typeCheck(), QFileDialogPrivate::typedFiles(), QAxServerBase::Unadvise(), uncShareExists(), QUndoCommand::undo(), QGraphicsScenePrivate::ungrabKeyboard(), QGraphicsScenePrivate::ungrabMouse(), QDockAreaLayoutInfo::unplug(), QToolBarAreaLayout::unplug(), QMainWindowLayout::unplug(), QStateMachinePrivate::unregisterAllTransitions(), QDBusConnection::unregisterObject(), QResource::unregisterResource(), QDBusConnectionInterface::unregisterService(), QFactoryLoader::update(), QAxServerBase::update(), QSortFilterProxyModelPrivate::update_persistent_indexes(), QWSServerPrivate::update_regions(), update_toolbar_style(), QNetworkManagerEngine::updateAccessPoint(), QMenuPrivate::updateActionRects(), QGraphicsAnchorLayoutPrivate::updateAnchorSizes(), QUnifiedTimer::updateAnimationsTime(), QDeclarativeStateGroupPrivate::updateAutoState(), QBBButtonEventNotifier::updateButtonStates(), QFactoryLoader::updateDir(), QAbstractItemView::updateEditorGeometries(), QGraphicsWidgetPrivate::updateFont(), QWidgetPrivate::updateFont(), QToolBarLayout::updateGeomArray(), QMenuBarPrivate::updateGeometries(), QMainWindowLayout::updateHIToolBarStatus(), QGraphicsScenePrivate::updateInputMethodSensitivityInViews(), ModelNode::updateListIndexes(), QWidgetBackingStore::updateLists(), QGraphicsItem::updateMicroFocus(), QGraphicsItemPrivate::updatePaintedViewBoundingRects(), QGraphicsWidgetPrivate::updatePalette(), QDesktopWidgetPrivate::updateScreenList(), QDockAreaLayoutInfo::updateSeparatorWidgets(), QWidgetBackingStore::updateStaticContentsSize(), QDockAreaLayoutInfo::updateTabBar(), updateWidgets(), QMimeData::urls(), QDockAreaLayoutInfo::usedSeparatorWidgets(), QDockAreaLayoutInfo::usedTabBars(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::TagValidationHandler::validate(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdValidatingInstanceReader::validateIdentityConstraint(), QDeclarativeEngineDebugService::valueContents(), QPatternist::XsdTypeChecker::valuesAreEqual(), QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue(), Maemo::IAPConfPrivate::variantToValue(), QIconLoaderEngine::virtual_hook(), QGraphicsSceneFindItemBspTreeVisitor::visit(), QColumnView::visualRegionForSelection(), QTableView::visualRegionForSelection(), QListView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), QHeaderView::visualRegionForSelection(), waitForPopup(), QMenuBar::wceCommands(), QMenuBarPrivate::wceEmitSignals(), QMenuBar::wceRefresh(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), QWorkspace::windowList(), QWSDisplay::windowList(), QWSServer::windowList(), WinMain(), QHostInfoLookupManager::work(), QDeclarativePropertyPrivate::write(), QUnixSocketPrivate::writeActivated(), writingSystemForFont(), QPatternist::yyparse(), NodeImpl::~NodeImpl(), QAxServerBase::~QAxServerBase(), QDeclarativeCompiledData::~QDeclarativeCompiledData(), QDeclarativeContents::~QDeclarativeContents(), QDeclarativeMetaTypeData::~QDeclarativeMetaTypeData(), QDeclarativeTypeData::~QDeclarativeTypeData(), QFSFileEngine::~QFSFileEngine(), QGraphicsItem::~QGraphicsItem(), QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate(), QSingleDesktopWidget::~QSingleDesktopWidget(), QThreadData::~QThreadData(), QTreeWidgetItem::~QTreeWidgetItem(), and QWaylandWindow::~QWaylandWindow().
 { Q_ASSERT_X(i >= 0 && i < p.size(), "QList<T>::at", "index out of range");
  return reinterpret_cast<Node *>(p.at(i))->t(); }
back() [1/2]
template<typename T> T & QList< T >::back () inline
This function is provided for STL compatibility.
It is equivalent to last(). The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
Definition at line 300 of file qlist.h.
Referenced by QMdiAreaPrivate::nextVisibleSubWindow().
 { return last(); }
back() [2/2]
template<typename T> const T & QList< T >::back () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 301 of file qlist.h.
 { return last(); }
begin() [1/2]
template<typename T> QList::iterator QList< T >::begin () inline
Returns an STL-style iterator pointing to the first item in the list.
See also
constBegin(), end()
Definition at line 267 of file qlist.h.
Referenced by QFileSystemModelPrivate::_q_directoryChanged(), QScriptDebuggerConsoleWidgetPrivate::_q_onCompletionTaskFinished(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QDeclarativeImportsPrivate::add(), QDeclarativeTimeLinePrivate::advance(), QCopChannel::answer(), QSyntaxHighlighterPrivate::applyFormatChanges(), QStateMachinePrivate::applyProperties(), QTextEngine::calculateTabWidth(), QWorkspace::cascade(), QRingBuffer< T >::clear(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QTreeViewPrivate::columnRanges(), QPatternist::UnlimitedContainer::compressOperands(), convertFlags(), QNetworkCookieJar::cookiesForUrl(), createInterfaces(), QCopChannel::detach(), QSvgG::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), QAbstractItemModel::encodeData(), QThreadPoolPrivate::enqueueTask(), QGraphicsItemPrivate::ensureSequentialSiblingIndex(), QGraphicsScenePrivate::ensureSequentialTopLevelSiblingIndexes(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QGraphicsScenePrivate::ensureSortedTopLevelItems(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), fallbackFamilies(), findAllLibCrypto(), findAllLibSsl(), QMdi::MinOverlapPlacer::getCandidatePlacements(), QListModel::insert(), QGraphicsItemAnimationPrivate::insertUniquePair(), interfaceListing(), QSimplexConstraint::invert(), QAxScript::load(), QAxScriptManager::load(), QScript::QObjectData::mark(), QItemSelection::merge(), QDirModel::mimeData(), QFileSystemModel::mimeData(), QBBWindow::offset(), QHttpHeader::parse(), QWorkspacePrivate::place(), postProcess(), QDeclarativeBasePositioner::prePositioning(), QTDSDriver::primaryIndex(), QXmlSimpleReaderPrivate::processElementEmptyTag(), QDeclarativeDomObjectPrivate::properties(), qax_startServer(), qax_stopServer(), QClassFactory::QClassFactory(), qDBusRemoveTimeout(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), qGetODBCVersion(), qSplitTableQualifier(), QtPrivate::QStringList_removeDuplicates(), QApplicationPrivate::qt_mac_apply_settings(), qt_mac_send_posted_gl_updates(), qt_mac_update_child_gl_widgets(), qt_mac_update_intersected_gl_widgets(), qt_wce_delete_action_list(), qt_win_extract_filter(), qt_win_filter(), qt_win_get_save_file_name(), rasterFallbacksMask(), MetaObjectGenerator::readClassInfo(), QHttpNetworkReplyPrivate::removeAutoDecompressHeader(), QWindowsFileSystemWatcherEngine::removePaths(), QCoreApplication::removePostedEvents(), QDeclarativeImportsPrivate::resolvedUri(), QSvgHandler::resolveGradients(), QAxScriptManager::scriptFileFilter(), QTreeViewPrivate::select(), QAbstractItemView::selectedIndexes(), QCoreApplicationPrivate::sendPostedEvents(), QAxBase::setControl(), QBBWindow::setGeometry(), QHttpNetworkHeaderPrivate::setHeaderField(), QMacPasteboard::setMimeData(), QBBWindow::setScreen(), QPrintDialogPrivate::setTabs(), QSimplex::simplifyConstraints(), sm_setProperty(), QStringListModel::sort(), QFileSystemModelPrivate::sortChildren(), QGraphicsSceneBspTreeIndexPrivate::sortItems(), QThreadPoolPrivate::stealRunnable(), QTextBlockFormat::tabPositions(), MetaObjectGenerator::tryCache(), QPatternist::ExpressionSequence::typeCheck(), QTableModel::updateRowIndexes(), QBBWindow::updateVisibility(), QBBWindow::updateZorder(), QTextOdfWriter::writeAll(), QTextOdfWriter::writeBlockFormat(), writeTypesEnum(), QApplicationPrivate::x11_apply_settings(), QMenuBarPrivate::QMacMenuBarPrivate::~QMacMenuBarPrivate(), and QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate().
 { detach(); return reinterpret_cast<Node *>(p.begin()); }
begin() [2/2]
template<typename T> QList::const_iterator QList< T >::begin () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 268 of file qlist.h.
 { return reinterpret_cast<Node *>(p.begin()); }
clear()
template<typename T > Q_OUTOFLINE_TEMPLATE void QList< T >::clear ()
Removes all items from the list.
See also
removeAll()
Definition at line 764 of file qlist.h.
Referenced by QGraphicsScenePrivate::_q_emitUpdated(), QStateMachinePrivate::_q_start(), QFtpPrivate::_q_startNextCommand(), QAbstractSocketPrivate::_q_testConnection(), QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex(), QUnixSocket::abort(), QFtpPI::abort(), QPacketProtocolPrivate::aboutToClose(), QDBusConnectionPrivate::activateCall(), Maemo::IcdPrivate::addrinfo(), QTextHtmlImporter::appendBlock(), QTextHtmlImporter::appendNodeText(), QDeclarativeState::apply(), QSyntaxHighlighterPrivate::applyFormatChanges(), QDeclarativeComponentPrivate::begin(), QDeclarativeComponentPrivate::beginDeferred(), QDeclarativeEngineDebugService::buildStatesList(), QGraphicsAnchorLayoutPrivate::calculateGraphs(), QDeclarativeTransitionManager::cancel(), QStatePrivate::childStates(), QmlJSDebugger::LiveRubberBandSelectionManipulator::clear(), QmlJSDebugger::LiveSingleSelectionManipulator::clear(), QPacketProtocol::clear(), QListModel::clear(), QTreeModel::clear(), FlatListModel::clear(), QDeclarativeScriptParser::clear(), QTestEventList::clear(), QDockAreaLayoutInfo::clear(), QByteDataBuffer::clear(), QTextDocumentPrivate::clear(), QToolBarAreaLayoutInfo::clear(), QHostInfoLookupManager::clear(), QResourcePrivate::clear(), ModelNode::clear(), QCalendarDateValidator::clear(), QWaylandMimeData::clearAll(), QSimplex::clearDataStructures(), QDirPrivate::clearFileLists(), QTextDocumentPrivate::clearFrame(), QFutureSynchronizer< T >::clearFutures(), QStateMachinePrivate::clearHistory(), QHttpNetworkReplyPrivate::clearHttpLayerInformation(), QFtpPI::clearPendingCommands(), Maemo::IcdPrivate::clearState(), QPSQLDriver::close(), QWSPcMouseHandlerPrivate::closeDevices(), QDeclarativeCompiler::compile(), QDeclarativeTransitionManager::complete(), QDeclarativeComponentPrivate::complete(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QSslSocketPrivate::createPlainSocket(), QWaylandClipboard::createSelectionOffer(), QDeclarativePackagePrivate::data_clear(), QObjectPrivate::deleteChildren(), QScriptDebuggerLocalsModelPrivate::depopulate(), QBBIntegration::destroyDisplays(), QmlJSDebugger::LiveSingleSelectionManipulator::end(), QmlJSDebugger::LiveRubberBandSelectionManipulator::end(), QWindowSurface::endPaint(), QGLWindowSurface::endPaint(), QStateMachinePrivate::exitStates(), QNlaThread::fetchConfigurations(), QDeclarativeXMLHttpRequest::fillHeadersList(), QItemSelectionModelPrivate::finalize(), QMdi::MinOverlapPlacer::findMaxOverlappers(), QIcdEngine::finishAsyncConfigurationUpdate(), QNetworkReplyImplPrivate::finished(), QFbScreen::generateRects(), QScanThread::getConfigurations(), QNlaThread::getConfigurations(), QNetworkReplyImplPrivate::handleNotifications(), QMainWindowLayout::hover(), QSslSocketPrivate::init(), QPainterState::init(), initializeDb(), QSslSocketBackendPrivate::initSslContext(), QSettingsPrivate::iniUnescapedStringList(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutCell(), QUrlModel::layoutChanged(), QDeclarativeVMEMetaObject::list_clear(), QDeclarativeDomDocument::load(), QResourcePrivate::load(), QTreeModel::mimeData(), QDeclarativeStatePrivate::operations_clear(), operator>>(), QDeclarativeDirParser::parse(), parseServerList(), QTextHtmlParser::parseTag(), QCompleter::pathFromIndex(), QMacWindowFader::performFade(), QDeclarativeGridViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::positionViewAtIndex(), prepareEngineForMatch(), QGraphicsSceneBspTreeIndexPrivate::purgeRemovedItems(), qDBusParametersForMethod(), qt_cleanup(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), qt_wce_delete_action_list(), QMainWindowLayout::qtmacToolbarDelegate(), QTreeWidgetItem::read(), QActionPrivate::redoGrabAlternate(), registerFont(), QTextFramePrivate::remove_me(), QGraphicsScene::render(), QThreadPoolPrivate::reset(), QDeclarativeCompiler::reset(), QGraphicsSceneBspTreeIndexPrivate::resetIndex(), QGraphicsAnchorLayoutPrivate::restoreVertices(), Maemo::IcdPrivate::scan(), QmlJSDebugger::LiveSelectionTool::selectedItemsChanged(), QJSDebugService::sendMessages(), QDeclarativeDebugTrace::sendMessages(), QSimplex::setConstraints(), QFutureSynchronizer< T >::setFuture(), ModelNode::setListValue(), QUrlModel::setUrls(), QStringListModel::sort(), QFileSystemModelPrivate::sortChildren(), QSslSocketBackendPrivate::startHandshake(), Maemo::IcdPrivate::state(), Maemo::IcdPrivate::statistics(), QTreeWidgetItem::takeChildren(), QPatternist::ParserContext::templateParametersHandled(), QUnifiedTimer::timerEvent(), QStatePrivate::transitions(), QDockAreaLayoutInfo::unnest(), QmlJSDebugger::LiveSingleSelectionManipulator::update(), QFactoryLoader::updateDir(), QAudioDeviceInfoInternal::updateLists(), QFontDialogPrivate::updateStyles(), QIconEngineV2::virtual_hook(), QPixmapIconEngine::virtual_hook(), QIconLoaderEngine::virtual_hook(), QHostInfoLookupManager::work(), QDBusServer::~QDBusServer(), QDeclarativePixmapReader::~QDeclarativePixmapReader(), QGLEngineSharedShaders::~QGLEngineSharedShaders(), QTextDocumentPrivate::~QTextDocumentPrivate(), QTreeWidgetItem::~QTreeWidgetItem(), QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate(), and QWSServerPrivate::~QWSServerPrivate().
 {
     *this = QList<T>();
 }
constBegin()
template<typename T> QList::const_iterator QList< T >::constBegin () const inline
Returns a const STL-style iterator pointing to the first item in the list.
See also
begin(), constEnd()
Definition at line 269 of file qlist.h.
Referenced by QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QWindowsFileSystemWatcherEngine::addPaths(), QMacPasteboardMime::all(), QCopChannel::answer(), QDBusMarshaller::append(), QCoreApplication::applicationFilePath(), QSvgStyle::apply(), QApplicationPrivate::applyX11SpecificCommandLineArguments(), QPatternist::MultiItemType::atomizedType(), QPatternist::UserFunctionCallsite::bindVariables(), boundingRectOfFloatsInSelection(), QPatternist::CallTargetDescription::checkCallsiteCircularity(), QHttpPartPrivate::checkHeaderCreated(), QPatternist::checkVariableCircularity(), QStatePrivate::childStates(), QAbstractItemViewPrivate::clearOrRemove(), QPdfBaseEnginePrivate::closePrintDevice(), QPatternist::ExpressionSequence::compress(), QApplication::compressEvent(), QPatternist::VariableDeclaration::contains(), QHttpNetworkHeaderPrivate::contentLength(), QMacPasteboardMime::convertor(), QPatternist::FunctionFactoryCollection::createFunctionCall(), QVNCIntegration::createPlatformWindow(), debugVariantList(), QPatternist::Template::dependencies(), QPatternist::MultiItemType::displayName(), QPatternist::FunctionSignature::displayName(), QSvgSwitch::draw(), QSqlDatabase::drivers(), QDirModel::dropMimeData(), QFileSystemModel::dropMimeData(), QPatternist::GeneralComparison::evaluateEBV(), QPatternist::ConcatFN::evaluateSingleton(), QPatternist::ExpressionSequence::evaluateToSequenceReceiver(), QPatternist::FunctionCall::expectedOperandTypes(), familyList(), QIconModeViewBase::filterStartDrag(), findChildObject(), QFontDatabase::findFont(), QMacPasteboardMime::flavorToMime(), fontFile(), QProcessEnvironmentPrivate::fromList(), QPatternist::FunctionFactoryCollection::functionSignatures(), generateSubObjectXml(), QFileInfoGatherer::getFileInfos(), QWindowSystemInterface::handleTouchEvent(), QHttpNetworkRequestPrivate::header(), QHttpNetworkHeaderPrivate::headerFieldValues(), QStatePrivate::historyStates(), QFont::insertSubstitutions(), QNetworkInterfaceManager::interfaceFromIndex(), QNetworkInterfaceManager::interfaceFromName(), QAxServerBase::internalCreate(), QPatternist::Expression::invokeOptimizers(), QPatternist::MultiItemType::isAtomicType(), QPatternist::FunctionFactoryCollection::isAvailable(), QItemSelectionModel::isColumnSelected(), QPatternist::MultiItemType::isNodeType(), QItemSelectionModel::isRowSelected(), QPatternist::MultiItemType::itemMatches(), QCoreApplication::libraryPaths(), QDBusMessagePrivate::makeLocal(), QIdentityProxyModel::mapSelectionFromSource(), QIdentityProxyModel::mapSelectionToSource(), QIdentityProxyModel::match(), QDir::match(), mergeKeySets(), QDBusInterfacePrivate::metacall(), QPatternist::DistinctIterator::next(), QPatternist::UnlimitedContainer::operandsUnionType(), operator<<(), parseAnimateColorNode(), QAuthenticatorPrivate::parseHttpResponse(), QDBusAdaptorConnector::polish(), QSvgStructureNode::previousSiblingNode(), QPatternist::ExpressionSequence::properties(), QPatternist::Template::properties(), qDBusFindAdaptorConnector(), qDBusParametersForMethod(), QFileDialogPrivate::qt_mac_filedialog_filter_proc(), qt_mac_make_filters_list(), QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate(), QFactoryLoader::refreshAll(), registerFont(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QSvgStyle::revert(), QNetworkAccessHttpBackend::sendCacheContents(), QWinSettingsPrivate::set(), QApplication::setFont(), QApplicationPrivate::setPalette_helper(), QApplication::setStyle(), QTextBlockFormat::setTabPositions(), QApplication::setWindowIcon(), QPatternist::LiteralSequence::staticType(), QTextOption::tabArray(), QDBusMessagePrivate::toDBusMessage(), QApplication::topLevelWidgets(), QStatePrivate::transitions(), QPatternist::CallTemplate::typeCheck(), QPatternist::Expression::typeCheckOperands(), QFontDialogPrivate::updateFamilies(), QBBScreen::updateHierarchy(), QFontDialogPrivate::updateSizes(), QSettingsPrivate::variantListToStringList(), QApplicationPrivate::x11_apply_settings(), QPatternist::MultiItemType::xdtSuperType(), QPatternist::MultiItemType::xdtTypeMatches(), QFbWindow::~QFbWindow(), and QTextCodecCleanup::~QTextCodecCleanup().
 { return reinterpret_cast<Node *>(p.begin()); }
constEnd()
template<typename T> QList::const_iterator QList< T >::constEnd () const inline
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
See also
constBegin(), end()
Definition at line 272 of file qlist.h.
Referenced by QItemSelectionModelPrivate::_q_layoutAboutToBeChanged(), QWindowsFileSystemWatcherEngine::addPaths(), QMacPasteboardMime::all(), QCopChannel::answer(), QDBusMarshaller::append(), QCoreApplication::applicationFilePath(), QSvgStyle::apply(), QApplicationPrivate::applyX11SpecificCommandLineArguments(), QPatternist::UserFunctionCallsite::bindVariables(), boundingRectOfFloatsInSelection(), QPatternist::CallTargetDescription::checkCallsiteCircularity(), QHttpPartPrivate::checkHeaderCreated(), QPatternist::checkVariableCircularity(), QStatePrivate::childStates(), QAbstractItemViewPrivate::clearOrRemove(), QPdfBaseEnginePrivate::closePrintDevice(), QPatternist::ExpressionSequence::compress(), QApplication::compressEvent(), QPatternist::VariableDeclaration::contains(), QHttpNetworkHeaderPrivate::contentLength(), QMacPasteboardMime::convertor(), QPatternist::FunctionFactoryCollection::createFunctionCall(), QVNCIntegration::createPlatformWindow(), debugVariantList(), QPatternist::Template::dependencies(), QPatternist::FunctionSignature::displayName(), QSvgSwitch::draw(), QSqlDatabase::drivers(), QDirModel::dropMimeData(), QFileSystemModel::dropMimeData(), QPatternist::GeneralComparison::evaluateEBV(), QPatternist::ConcatFN::evaluateSingleton(), QPatternist::ExpressionSequence::evaluateToSequenceReceiver(), QPatternist::FunctionCall::expectedOperandTypes(), familyList(), QNetworkAccessHttpBackend::fetchCacheMetaData(), QIconModeViewBase::filterStartDrag(), findChildObject(), QFontDatabase::findFont(), QMacPasteboardMime::flavorToMime(), fontFile(), QProcessEnvironmentPrivate::fromList(), QPatternist::FunctionFactoryCollection::functionSignatures(), generateSubObjectXml(), QFileInfoGatherer::getFileInfos(), QWindowSystemInterface::handleTouchEvent(), QNetworkRequest::hasRawHeader(), QHttpNetworkRequestPrivate::header(), QHttpNetworkHeaderPrivate::headerFieldValues(), QStatePrivate::historyStates(), QFont::insertSubstitutions(), QNetworkInterfaceManager::interfaceFromIndex(), QNetworkInterfaceManager::interfaceFromName(), QAxServerBase::internalCreate(), QPatternist::Expression::invokeOptimizers(), QPatternist::FunctionFactoryCollection::isAvailable(), QItemSelectionModel::isColumnSelected(), QItemSelectionModel::isRowSelected(), QCoreApplication::libraryPaths(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QDBusMessagePrivate::makeLocal(), QIdentityProxyModel::mapSelectionFromSource(), QIdentityProxyModel::mapSelectionToSource(), QIdentityProxyModel::match(), QDir::match(), mergeKeySets(), QDBusInterfacePrivate::metacall(), QPatternist::DistinctIterator::next(), QPatternist::UnlimitedContainer::operandsUnionType(), operator<<(), parseAnimateColorNode(), QAuthenticatorPrivate::parseHttpResponse(), QDBusAdaptorConnector::polish(), QSvgStructureNode::previousSiblingNode(), QPatternist::ExpressionSequence::properties(), QPatternist::Template::properties(), qDBusFindAdaptorConnector(), qDBusParametersForMethod(), QFileDialogPrivate::qt_mac_filedialog_filter_proc(), qt_mac_make_filters_list(), QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate(), QNetworkRequest::rawHeader(), QFactoryLoader::refreshAll(), registerFont(), QItemSelectionModelPrivate::remove(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QSvgStyle::revert(), QNetworkAccessHttpBackend::sendCacheContents(), QWinSettingsPrivate::set(), QApplication::setFont(), QApplicationPrivate::setPalette_helper(), QApplication::setStyle(), QTextBlockFormat::setTabPositions(), QPrintDialogPrivate::setTabs(), QApplication::setWindowIcon(), QPatternist::LiteralSequence::staticType(), QTextOption::tabArray(), QDBusMessagePrivate::toDBusMessage(), QApplication::topLevelWidgets(), QStatePrivate::transitions(), QCoreApplication::translate(), QPatternist::CallTemplate::typeCheck(), QPatternist::Expression::typeCheckOperands(), QFontDialogPrivate::updateFamilies(), QBBScreen::updateHierarchy(), QFontDialogPrivate::updateSizes(), QSettingsPrivate::variantListToStringList(), QApplicationPrivate::x11_apply_settings(), QFbWindow::~QFbWindow(), and QTextCodecCleanup::~QTextCodecCleanup().
 { return reinterpret_cast<Node *>(p.end()); }
contains()
template<typename T> Q_OUTOFLINE_TEMPLATE QBool QList< T >::contains (const T & value) const
Returns true if the list contains an occurrence of value; otherwise returns false.
This function requires the value type to have an implementation of operator==().
See also
indexOf(), count()
Definition at line 880 of file qlist.h.
Referenced by QFileDialogPrivate::_q_autoCompleteFileName(), QHostInfoLookupManager::abortLookup(), QDeclarativeDataBlob::addDependency(), QJSDebugService::addEngine(), QDeclarativeEngineDebugService::addEngine(), QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsScenePrivate::addPopup(), QWidgetBackingStore::addStaticWidget(), QMacStylePrivate::addWidget(), QBBScreen::addWindow(), QmlJSDebugger::LiveSelectionTool::alreadySelected(), QMacStylePrivate::animatable(), QTextCodec::availableCodecs(), QTextCodec::availableMibs(), QNetworkReplyImplPrivate::backendNotify(), QDBusAbstractInterface::callWithArgumentList(), QDeclarativeDataBlob::cancelAllWaitingFor(), classIDL(), QFontEngineQPF::cleanUpAfterClientCrash(), QApplication::commitData(), compressHelper(), convertTypes(), QListWidget::dropEvent(), QTreeWidget::dropEvent(), QAbstractItemViewPrivate::droppingOnItself(), QMacStylePrivate::eventFilter(), findEncoding(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTransitive(), QHostInfoAgent::fromName(), QGLXContext::getProcAddress(), QGraphicsScenePrivate::grabKeyboard(), QGraphicsScenePrivate::grabMouse(), QEgl::hasExtension(), QWindowsStylePrivate::hasSeenAlt(), QMenuPrivate::hideMenu(), QPictureIO::inputFormats(), QTextTable::insertColumns(), QMdiAreaPrivate::internalRaise(), QScanThread::isKnownSsid(), QFontDatabase::loadXlfd(), QXlibMime::mimeAtomForFormat(), QAbstractButtonPrivate::moveFocus(), QVNCIntegration::moveToScreen(), QAudioDeviceInfo::nearestFormat(), QDeclarativePixmapReader::networkRequestDone(), QDeclarativeDataBlob::notifyAllWaitingOnMe(), QDeclarativeDataBlob::notifyComplete(), QDeclarativeEngineDebugService::objectCreated(), QPictureIO::outputFormats(), QNetworkManagerEngine::parseConnection(), QAuthenticatorPrivate::parseDigestAuthenticationChallenge(), QFontDatabase::pointSizes(), QTextDocumentLayoutPrivate::positionFloat(), QNetworkAccessHttpBackend::postRequest(), prototype(), q_hasEglExtension(), QGLXContext::QGLXContext(), QItemSelection::QItemSelection(), qt_grab_cursor(), MetaObjectGenerator::readEventInfo(), QStateMachinePrivate::registerEventTransition(), QAccessibleApplication::relationTo(), QAccessibleGroupBox::relationTo(), QDeclarativeEngineDebugService::remEngine(), QNetworkManagerEngine::removeAccessPoint(), QTextTable::removeColumns(), QBBIntegration::removeDisplay(), QJSDebugService::removeEngine(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsScenePrivate::removePopup(), QTextTable::removeRows(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedAnchor(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph(), QmlJSDebugger::LiveSingleSelectionManipulator::select(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), QTableViewPrivate::selectColumn(), QTableViewPrivate::selectRow(), QWin32PrintEngine::setProperty(), QmlJSDebugger::QDeclarativeViewInspectorPrivate::setSelectedItemsForTools(), QMessageBox::setStandardButtons(), QUrlModel::setUrl(), QFileDialogComboBox::showPopup(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QFontDatabase::smoothSizes(), QWindowsStylePrivate::startAnimation(), QSslSocketBackendPrivate::startHandshake(), QPatternist::XsdParticleChecker::subsumes(), QMdiAreaPrivate::subWindowList(), QMacPrintEnginePrivate::supportedResolutions(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), QmlJSDebugger::AbstractLiveEditTool::topSelectedItemIsMovable(), QDeclarativeTransitionManager::transition(), translateWSAError(), QGestureManager::unregisterGestureRecognizer(), QDesktopWidgetPrivate::updateScreenList(), MetaObjectGenerator::usertypeToString(), QMainWindowLayout::usesHIToolBar(), QHostInfoLookupManager::wasAborted(), QDeclarativeBehavior::write(), writingSystemForFont(), QFontDatabase::writingSystems(), and QX11Data::xdndMimeAtomForFormat().
 {
     Node *b = reinterpret_cast<Node *>(p.begin());
     Node *i = reinterpret_cast<Node *>(p.end());
     while (i-- != b)
         if (i->t() == t)
             return QBool(true);
     return QBool(false);
 }
count() [1/2]
template<typename T> Q_OUTOFLINE_TEMPLATE int QList< T >::count (const T & value) const
Returns the number of occurrences of value in the list.
This function requires the value type to have an implementation of operator==().
See also
contains(), indexOf()
Definition at line 891 of file qlist.h.
Referenced by QScript::__setupPackage__(), QFileDialogPrivate::_q_autoCompleteFileName(), QAbstractSocketPrivate::_q_connectToNextAddress(), QMdiAreaPrivate::_q_currentTabChanged(), QFileDialogPrivate::_q_deleteCurrent(), QFileSystemModelPrivate::_q_directoryChanged(), QFileSystemModelPrivate::_q_fileSystemChanged(), QDeclarativeVisualDataModel::_q_itemsChanged(), QFileDialogPrivate::_q_pathChanged(), QUnixPrintWidgetPrivate::_q_printerChanged(), _q_resolveEntryAndCreateLegacyEngine_recursive(), QFileDialogPrivate::_q_selectionChanged(), QTreeWidgetPrivate::_q_selectionChanged(), QFontComboBoxPrivate::_q_updateModel(), QFileDialogPrivate::_q_updateOkButton(), QFileDialogPrivate::_q_useNameFilter(), QFileDialog::accept(), QDBusConnectionPrivate::activateCall(), QThreadPoolPrivate::activeThreadCount(), QGraphicsWidget::addActions(), QWidget::addActions(), QGraphicsAnchorLayoutPrivate::addAnchorMaybeParallel(), QDialogButtonBoxPrivate::addButtonsToLayout(), QTreeWidgetItem::addChild(), QTreeWidgetItem::addChildren(), QDockAreaLayout::addDockWidget(), QFontDatabasePrivate::addFont(), addFontToDatabase(), QPrintPropertiesDialog::addItemToOptions(), QHttpPrivate::addRequest(), QUrlModel::addUrls(), QFileSystemModelPrivate::addVisibleFiles(), QDeclarativeTimeLinePrivate::advance(), QAxServerBase::Advise(), alert_widget(), allCombinations(), QPatternist::Expression::announceFocusType(), QSignalSpy::appendArgs(), QMdiAreaPrivate::appendChild(), QDeclarativeState::apply(), QToolBarAreaLayout::apply(), QSvgAnimateColor::apply(), QTextHtmlParser::applyAttributes(), QCoreApplication::arguments(), QIcdEngine::asyncUpdateConfigurationsSlot(), QScriptEngine::availableExtensions(), QTreeModel::beginRemoveItems(), QCss::Declaration::brushValues(), QDeclarativeCompiler::buildDynamicMeta(), buildMatchRule(), QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativeEngineDebugService::buildObjectList(), QDeclarativeBindingCompilerPrivate::buildSignalTable(), QDeclarativeEngineDebugService::buildStatesList(), QPatternist::XsdStateMachineBuilder::buildTerm(), QDialogButtonBox::buttonRole(), QDialogButtonBox::buttons(), QMenuBarPrivate::calcActionRects(), QDeclarativeContents::calcHeight(), QGraphicsAnchorLayoutPrivate::calculateGraphs(), QGraphicsAnchorLayoutPrivate::calculateNonTrunk(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QDeclarativeContents::calcWidth(), QDeclarativeObjectMethodScriptClass::callOverloaded(), QDeclarativeObjectMethodScriptClass::callPrecise(), QScript::callQtMethod(), QDeclarativeTransitionManager::cancel(), QDeclarativeDataBlob::cancelAllWaitingFor(), QAbstractItemViewPrivate::canDecode(), QUrlModel::canDrop(), QAbstractItemModel::changePersistentIndexList(), QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkAttributeUseConstraints(), QPatternist::XsdSchemaChecker::checkBasicCircularInheritances(), QPatternist::XsdSchemaChecker::checkBasicComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkBasicSimpleTypeConstraints(), QPatternist::XsdSchemaChecker::checkCircularInheritances(), QColumnViewPrivate::checkColumnCreation(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdTypeChecker::checkConstrainingFacetsBinary(), QPatternist::XsdTypeChecker::checkConstrainingFacetsBoolean(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDateTime(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDouble(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDuration(), QPatternist::XsdTypeChecker::checkConstrainingFacetsList(), QPatternist::XsdTypeChecker::checkConstrainingFacetsNotation(), QPatternist::XsdTypeChecker::checkConstrainingFacetsQName(), QPatternist::XsdTypeChecker::checkConstrainingFacetsSignedInteger(), QPatternist::XsdTypeChecker::checkConstrainingFacetsString(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnion(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnsignedInteger(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaChecker::checkInheritanceRestrictions(), NestedListModel::checkRoles(), QPatternist::XsdSchemaChecker::checkSimpleDerivationRestrictions(), QPatternist::XsdSchemaChecker::checkSimpleTypeConstraints(), ShaderEffectItem::checkViewportUpdateMode(), QUndoCommand::child(), QAccessibleAbstractScrollArea::childAt(), QAccessibleApplication::childAt(), QDeclarativeItem::childAt(), QAccessibleMenu::childCount(), QUndoCommand::childCount(), QAccessibleAbstractScrollArea::childCount(), QAccessibleMenuBar::childCount(), QAccessibleApplication::childCount(), QAccessibleItemRow::childCount(), QAccessibleWorkspace::childCount(), QAccessibleMainWindow::childCount(), QAccessibleItemRow::childIndex(), QDirModelPrivate::children(), QGraphicsItemPrivate::children_at(), children_at_helper(), QGraphicsItemPrivate::children_clear(), children_clear_helper(), QDeclarativeVisualItemModelPrivate::children_count(), QGraphicsItemPrivate::children_count(), children_count_helper(), QTreeWidgetItem::childrenCheckState(), QWSServerPrivate::cleanupFonts(), QListModel::clear(), QDeclarativeCompiledData::clear(), QDialogButtonBox::clear(), ModelNode::clear(), QTextDocumentPrivate::clearFrame(), QAxServerBase::Close(), collectAllElements(), collectGroupRef(), QItemSelectionModel::columnIntersectsSelection(), QTreeViewPrivate::columnRanges(), QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compile(), QDeclarativeCompiler::compile(), QDeclarativeCompiler::compileAlias(), QDeclarativePropertyChangesParser::compileList(), QPatternist::Template::compileParameters(), QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::compileTree(), QDeclarativeTransitionManager::complete(), QDeclarativeContents::complete(), QDeclarativeComponentPrivate::complete(), QDeclarativeCompiler::completeComponentBuild(), QPatternist::XsdSchema::complexTypes(), QPatternist::NormalizeUnicodeFN::compress(), QPatternist::UnlimitedContainer::compressOperands(), QNetworkManagerEngine::connectionFromId(), QIcdEngine::connectionStateSignalsSlot(), QMetaObject::connectSlotsByName(), QPatternist::Expression::constantPropagate(), QScriptDebuggerBackend::contextCount(), QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeAny::convertToMime(), QMacPasteboardMimePlainText::convertToMime(), QMacPasteboardMimeUnicodeText::convertToMime(), QMacPasteboardMimeHTMLText::convertToMime(), QMacPasteboardMimeTiff::convertToMime(), FlatListModel::count(), QToolBarLayout::count(), QZipReader::count(), QDir::count(), NestedListModel::count(), QDeclarativeEnginePrivate::createCache(), QPatternist::AbstractFunctionFactory::createFunctionCall(), QEventDispatcherWin32::createInternalHwnd(), QAxServerBase::createMenu(), QDeclarativeVisualDataModelPrivate::createMetaData(), QShortcutMap::createNewSequences(), QDeclarativeComponentPrivate::createObject(), QAxServerBase::createPopup(), MetaObjectGenerator::createPrototype(), QDeclarativeEnginePrivate::createQmlObject(), createSvgNode(), QPatternist::XsdValidatingInstanceReader::createXQuery(), QToolBarAreaLayout::currentGapIndex(), QAxServerBase::DAdvise(), FlatListModel::data(), QListModel::data(), QTreeWidgetItem::data(), NestedListModel::data(), QDeclarativeFlickablePrivate::data_at(), QDeclarativeFlickablePrivate::data_clear(), QDeclarativePackagePrivate::data_count(), QDeclarativeFlickablePrivate::data_count(), QUrlModel::dataChanged(), QPatternist::Expression::deepProperties(), QDockAreaLayoutInfo::deleteAllLayoutItems(), QToolBarAreaLayout::deleteAllLayoutItems(), QObjectPrivate::deleteChildren(), QDBusConnectionPrivate::deliverCall(), QScriptDebuggerLocalsModelPrivate::depopulate(), QMessageBoxPrivate::detectEscapeButton(), DllCanUnloadNow(), QDeclarativeXmlQueryEngine::doQuery(), QDeclarativeXmlQueryEngine::doSubQueryJob(), QAbstractItemViewPrivate::draggablePaintPairs(), QListViewPrivate::draggablePaintPairs(), QStyleSheetStyle::drawComplexControl(), QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::drawFrame(), QListWidget::dropEvent(), QTableWidget::dropEvent(), QTreeWidget::dropEvent(), QListModel::dropMimeData(), ModelNode::dump(), QDeclarativeCompiledData::dumpInstructions(), QPatternist::XsdSchemaDebugger::dumpSchema(), QDeclarativeCompiler::dumpStats(), QPatternist::XsdSchemaDebugger::dumpType(), dumpwarning(), QAxBase::dynamicCallHelper(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), QFileDialogPrivate::emitFilesSelected(), QTextHtmlExporter::emitFragment(), QItemSelectionModel::emitSelectionChanged(), QClipboardWatcher::empty(), QSslSocketPrivate::ensureCiphersAndCertsLoaded(), QDeclarativeVisualDataModelPrivate::ensureRoles(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QGraphicsScenePrivate::enterModal(), QApplicationPrivate::enterModal(), QApplicationPrivate::enterModal_sys(), QIconLoaderEngine::entryForSize(), QPatternist::UnparsedTextAvailableFN::evaluateEBV(), QPatternist::SubsequenceFN::evaluateSequence(), QPatternist::FunctionAvailableFN::evaluateSingleton(), QPatternist::UnparsedTextFN::evaluateSingleton(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::SubstringFN::evaluateSingleton(), QPatternist::RoundHalfToEvenFN::evaluateSingleton(), QPatternist::SumFN::evaluateSingleton(), QPatternist::NormalizeUnicodeFN::evaluateSingleton(), QDeclarativeListModelWorkerAgent::event(), QDockWidget::event(), QDeclarativePinchArea::event(), QSqlResult::execBatch(), QScript::QObjectConnectionManager::execute(), QImagePixmapCleanupHooks::executePixmapDataDestructionHooks(), QImagePixmapCleanupHooks::executePixmapDataModificationHooks(), QToolBarLayout::expandedSize(), QItemSelectionModelPrivate::expandSelection(), QDeclarativeGlobalScriptClass::explicitSetProperty(), QPatternist::ExpressionSequence::ExpressionSequence(), QHttpNetworkConnectionPrivate::fillPipeline(), QIconModeViewBase::filterDropEvent(), QIconModeViewBase::filterStartDrag(), QPatternist::TagValidationHandler::finalize(), QDeclarativeImportsPrivate::find(), QX11Data::findClientWindow(), findMenuBar(), QGLEngineSharedShaders::findProgramInCache(), QDBusConnectionPrivate::findSlot(), findSlot(), findSnapshotIdsRecursively(), QToolBarAreaLayout::findToolBar(), QLineControl::finishChange(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutInfo::fitLayout(), QAbstractButtonPrivate::fixFocusPolicy(), QListModel::flags(), QDeclarativeListModel::flatten(), QMenuBarPrivate::focusFirstAction(), QXlibClipboardMime::formats_sys(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTransitive(), QRingBuffer< T >::free(), QHostInfoAgent::fromName(), QDeclarativeCustomParserNodePrivate::fromProperty(), QDate::fromString(), QDateTime::fromString(), QToolBarAreaLayoutInfo::gapIndex(), QDockAreaLayout::gapRect(), QDeclarativeCompiler::genComponent(), QDeclarativeCompiler::genContextCache(), QDeclarativeStatePrivate::generateActionList(), generateInterfaceXml(), QDeclarativeCompiler::genObject(), QDeclarativeCompiler::genObjectBody(), FlatListModel::get(), getAllActionNames(), QConnmanEngine::getConfigurations(), getFamiliesAndSignatures(), QFileInfoGatherer::getFileInfos(), QGraphicsAnchorLayoutPrivate::getGraphParts(), QMenuPrivate::getLastVisibleAction(), QMenuBarPrivate::getNextAction(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::DeclarativeObjectDelegate::getOwnPropertyNames(), QScript::QObjectDelegate::getOwnPropertySlot(), QToolBarAreaLayout::getStyleOptionInfo(), QDeclarativeXmlQueryEngine::getValuesOfKeyRoles(), getVariables(), handleChildrenAttribute(), QStateMachinePrivate::handleTransitionSignal(), hasCircularSubstitutionGroup(), QPatternist::XsdSchemaChecker::hasConstraintIDAttributeUse(), QPatternist::XsdSchemaChecker::hasDuplicatedAttributeUses(), hasDuplicatedElementsInternal(), hasIDAttributeUse(), QNetworkManagerEngine::hasIdentifier(), QPatternist::XsdSchemaChecker::hasMultipleIDAttributeUses(), QWidgetPrivate::hide_sys(), QGuiPlatformPlugin::iconThemeSearchPaths(), QScriptEngine::importExtension(), QScriptDebuggerLocalsModel::index(), QTreeModel::index(), QListModel::index(), QDirModel::index(), QTextEngine::indexAdditionalFormats(), QDeclarativeCompiledData::indexForByteArray(), QDeclarativeCompiledData::indexForFloat(), QDeclarativeCompiledData::indexForInt(), QDeclarativeCompiledData::indexForLocation(), QDeclarativeCompiledData::indexForString(), QDeclarativeCompiledData::indexForUrl(), QToolBarLayout::indexOf(), QDeclarativeVisualItemModelPrivate::indexOf(), QToolBarAreaLayout::indexOf(), QDockAreaLayoutInfo::info(), QDockAreaLayout::info(), QFontDialogPrivate::init(), init_plugins(), QSignalSpy::initArgs(), QMultiScreen::initDevice(), QMacPrintEnginePrivate::initialize(), initializeDb(), QTextHtmlParserNode::initializeProperties(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), QDeclarativePropertyPrivate::initProperty(), QSslSocketBackendPrivate::initSslContext(), QListModel::insert(), FlatListModel::insert(), QToolBarLayout::insertAction(), QGraphicsWidget::insertActions(), QWidget::insertActions(), QTreeWidgetItem::insertChild(), QTreeWidgetItem::insertChildren(), QStandardItem::insertColumn(), QStandardItemPrivate::insertColumns(), QTreeModel::insertColumns(), FlatListModel::insertedNode(), QDockAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayout::insertGap(), QToolBarAreaLayoutInfo::insertItem(), QComboBox::insertItems(), QStandardItem::insertRow(), QStandardItemPrivate::insertRows(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QFactoryLoader::instance(), QAxServerBase::internalActivate(), QAxServerBase::Invoke(), QGraphicsItem::isBlockedByModalPanel(), QMenu::isEmpty(), QLibrary::isLibrary(), QSslConfiguration::isNull(), QLibraryPrivate::isPlugin(), QPatternist::XsdSchemaHelper::isSimpleDerivationOk(), isSubstGroupHeadOf(), QPatternist::XsdParticleChecker::isUPAConformXsdAll(), QPatternist::XsdSchemaHelper::isValidAttributeUsesExtension(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), QDBusUtil::isValidBusName(), QDBusUtil::isValidInterfaceName(), QDBusUtil::isValidObjectPath(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdTypeChecker::isValidString(), QDBusUtil::isValidUniqueConnectionName(), QDockAreaLayoutInfo::item(), QToolBarAreaLayout::item(), QDeclarativeVisualItemModelPrivate::itemAppended(), QToolBarLayout::itemAt(), QDockAreaLayoutInfo::itemAt(), QToolBarAreaLayout::itemAt(), QListModel::itemData(), QDockAreaLayoutInfo::itemRect(), QToolBarAreaLayoutInfo::itemRect(), QDeclarativeGridView::itemsInserted(), QDeclarativeListView::itemsInserted(), QDeclarativePathView::itemsMoved(), QTreeView::keyboardSearch(), QMessageBox::keyPressEvent(), QFactoryLoader::keys(), QTextCodecPlugin::keys(), QMdiAreaPrivate::lastWindowAboutToBeDestroyed(), QToolBarLayout::layoutActions(), QUrlModel::layoutChanged(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutTable(), QGraphicsScenePrivate::leaveModal(), QApplicationPrivate::leaveModal(), QApplicationPrivate::leaveModal_sys(), NamedNodeMap::length(), NodeList::length(), libGreaterThan(), QSystemLibrary::load(), QMenuBarPrivate::macMenu(), QMenuPrivate::macMenu(), macValue(), make_win_eventUPP(), QAbstractItemModel::match(), mdiAreaNavigate(), QPatternist::XsdSchemaMerger::merge(), QItemSelection::merge(), mergeIndexes(), QDeclarativeEngineDebugService::messageReceived(), messageToScriptValue(), QProxyModel::mimeData(), QUrlModel::mimeData(), QListModel::mimeData(), QTreeModel::mimeData(), QSortFilterProxyModel::mimeData(), QTableModel::mimeData(), QAbstractItemModel::mimeData(), QTreeWidget::mimeData(), QStandardItemModel::mimeData(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::minimumSize(), QListModel::move(), QTreeView::moveCursor(), QAbstractButtonPrivate::moveFocus(), QToolBarAreaLayoutInfo::moveToolBar(), multicastMembershipHelper(), QPatternist::MultiItemType::MultiItemType(), namedPrototype(), QNativeSocketEnginePrivate::nativeMulticastInterface(), QNativeSocketEnginePrivate::nativeSetMulticastInterface(), QAccessibleWidget::navigate(), QAccessibleAbstractScrollArea::navigate(), QAccessibleApplication::navigate(), QAccessibleMdiArea::navigate(), QAccessibleWorkspace::navigate(), QAccessibleMainWindow::navigate(), QNetworkManagerEngine::newAccessPoint(), QPatternist::CachingIterator::next(), Node::nextSibling(), QFileSystemModelPrivate::node(), QApplication::notify(), QDeclarativeDataBlob::notifyAllWaitingOnMe(), QWhatsThisPrivate::notifyToplevels(), QAxMetaObject::numParameter(), QDBusConnection::objectRegisteredAt(), QAxClientSite::OnPosRectChange(), QDeclarativeStatePrivate::operations_count(), operator<<(), QVideoSurfaceFormatPrivate::operator==(), QPacketProtocol::packetsAvailable(), QDockAreaLayoutInfo::paintSeparators(), QPatternist::Template::parametersAsHash(), QAxMetaObject::paramType(), QDeclarativeScriptParser::parse(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), parseBrushValue(), parseColorValue(), QNetworkManagerEngine::parseConnection(), parseCookieHeader(), parseCSStoXMLAttrs(), QPatternist::XsdSchemaParser::parseGlobalElement(), parseIp4(), parseIp6(), QHttpRequestHeader::parseLine(), QPatternist::XsdSchemaParser::parseLocalElement(), QDeclarativeBindingCompilerPrivate::parseMethod(), QDBusMetaObjectGenerator::parseMethods(), QDeclarativeBindingCompilerPrivate::parseName(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSchema(), parseServerList(), QDBusMetaObjectGenerator::parseSignals(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QHostAddress::parseSubnet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QCompleter::pathFromIndex(), QMacWindowFader::performFade(), QDockAreaLayoutInfo::plug(), populate_database(), QDeclarativeGridViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::positionViewAtIndex(), QDeclarativeEngineDebugService::prepareDeferredObjects(), QDBusConnectionPrivate::prepareHook(), QDBusConnectionPrivate::prepareReply(), QDeclarativeBasePositioner::prePositioning(), Node::previousSibling(), QFtpPI::processReply(), QTreeWidgetItemPrivate::propagateDisabled(), QDeclarativeDomObject::properties(), QDeclarativeObjectMethodScriptClass::property(), QVideoSurfaceFormat::property(), QDeclarativeDomObject::property(), prototype(), Q_GLOBAL_STATIC_WITH_ARGS(), qax_generateDocumentation(), qax_startServer(), qAxFactory(), QTest::qCompare(), qDBusGenerateMetaObjectXml(), qDBusInterfaceFromMetaObject(), qDBusPropertyGet(), qDBusPropertyGetAll(), qDBusPropertySet(), qDBusReplyFill(), qDBusReplyToScriptValue(), QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), QDeclarativeListModel::QDeclarativeListModel(), QTest::qExec(), qExtractSecurityPolicyFromString(), qGetODBCVersion(), QTest::qMedian(), QDeclarativeMetaType::qmlComponents(), QDeclarativeTypeData::qmldirForUrl(), QTest::qPrintDataTags(), QScriptContextInfoPrivate::QScriptContextInfoPrivate(), QTest::qSignalDumperCallback(), qSplitTableQualifier(), QApplicationPrivate::qt_mac_apply_settings(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), QAxServerBase::qt_metacall(), qt_strip_filters(), QTestEventList::QTestEventList(), qTopLevelDomain(), qToStringList(), QTreeWidgetItem::QTreeWidgetItem(), QAbstractButtonPrivate::queryButtonList(), QAbstractButtonPrivate::queryCheckedButton(), QDeclarativeXmlListModel::queryCompleted(), NamedNodeMapClass::queryProperty(), NodeListClass::queryProperty(), queuedConnectionTypes(), QPatternist::XSLTTokenizer::queueSorting(), QVariantToVARIANT(), QWindowsXPStyle::QWindowsXPStyle(), QXIMInputContext::QXIMInputContext(), QPacketProtocol::read(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QHttpMultiPartIODevice::readData(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), MetaObjectGenerator::readEventInterface(), MetaObjectGenerator::readFuncsInfo(), QTcpServerPrivate::readNotification(), QPatternist::XsdSchemaParser::readXPathAttribute(), QPatternist::XsdSchemaParser::readXPathExpression(), QScriptDebuggerLocalsModelPrivate::reallySyncIndex(), QMdiAreaPrivate::rearrange(), QAccessibleAbstractScrollArea::rect(), QCss::Declaration::rectValue(), QActionPrivate::redoGrabAlternate(), QGraphicsAnchorLayoutPrivate::refreshAllSizeHints(), registerAutoParentFunction(), registerInterface(), QDBusConnection::registerObject(), registerType(), QAccessibleWidget::relationTo(), QAccessibleApplication::relationTo(), QDBusAdaptorConnector::relay(), QDeclarativeTimeLine::remove(), QDockAreaLayoutInfo::remove(), QFileSystemModel::remove(), QToolBarAreaLayout::remove(), QNetworkManagerEngine::removeAccessPoint(), QDialogButtonBox::removeButton(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), QWidgetBackingStore::removeDirtyWidget(), FlatListModel::removedNode(), removeDuplicateProxies(), QSidebar::removeEntry(), QObject::removeEventFilter(), removeInvisibleWidgetsFromList(), QHeaderViewPrivate::removeSectionsFromSpans(), QHeaderViewPrivate::removeSpans(), QToolBarAreaLayoutInfo::removeToolBar(), QToolBarAreaLayoutInfo::removeToolBarBreak(), QAbstractItemViewPrivate::renderToPixmap(), MetaObjectGenerator::replacePrototype(), QGraphicsAnchorLayoutPrivate::replaceVertex(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveEnumerationFacetValues(), QPatternist::XsdSchemaResolver::resolveKeyReferences(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroups(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::XsdSchemaResolver::resolveTermReferences(), QDeclarativeTypeData::resolveTypes(), QDeclarativeItemPrivate::resources_at(), QDeclarativeItemPrivate::resources_clear(), QDeclarativeItemPrivate::resources_count(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedConstraints(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph(), QFileDialog::restoreState(), QDockAreaLayoutInfo::restoreState(), QToolBarAreaLayout::restoreState(), QGraphicsAnchorLayoutPrivate::restoreVertices(), QFileDialogPrivate::retranslateStrings(), QSequentialAnimationGroupPrivate::rewindForwards(), QDeclarativeCompiler::rewriteBinding(), QAccessibleWidget::role(), NestedListModel::roles(), QStringListModel::rowCount(), QScriptDebuggerLocalsModel::rowCount(), QFileSystemModel::rowCount(), QListModel::rowCount(), ControlList::rowCount(), QPPDOptionsModel::rowCount(), QCompletionModel::rowCount(), QItemSelectionModel::rowIntersectsSelection(), QDeclarativeVME::run(), QDeclarativeParentChange::saveCurrentValues(), QCUPSSupport::saveOptions(), QDockAreaLayoutInfo::saveState(), QToolBarAreaLayout::saveState(), QDeclarativePinchArea::sceneEventFilter(), QDeclarativeEnginePrivate::scriptValueFromVariant(), QMenuPrivate::scrollMenu(), QString::section(), QColumnView::selectAll(), QAccessibleTable2::selectedCellCount(), QAccessibleTable2::selectedColumnCount(), QAccessibleItemView::selectedColumnCount(), QItemSelectionModel::selectedColumns(), QAccessibleItemView::selectedColumns(), QAbstractItemViewPrivate::selectedDraggableIndexes(), QFileDialog::selectedFiles(), QTableView::selectedIndexes(), QListView::selectedIndexes(), QTreeView::selectedIndexes(), QListWidget::selectedItems(), QTableWidget::selectedItems(), QTreeWidget::selectedItems(), QTableWidget::selectedRanges(), QAccessibleTable2::selectedRowCount(), QAccessibleItemView::selectedRowCount(), QItemSelectionModel::selectedRows(), QAccessibleItemView::selectedRows(), QItemSelectionModel::selection(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QFutureInterfaceBasePrivate::sendCallOut(), QFutureInterfaceBasePrivate::sendCallOuts(), QWSServer::sendIMEvent(), QJSDebugService::sendMessages(), QDeclarativeDebugTrace::sendMessages(), QGraphicsScenePrivate::sendTouchBeginEvent(), QDockAreaLayout::separatorMove(), QDockAreaLayoutInfo::separatorRect(), QDockAreaLayout::separatorRect(), QDockAreaLayoutInfo::separatorRegion(), Graph< AnchorVertex, AnchorData >::serializeToDot(), FlatListModel::set(), NestedListModel::set(), QWizard::setButtonLayout(), QColumnView::setColumnWidths(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), QDeclarativeListModelParser::setCustomData(), QListModel::setData(), QTreeWidgetItem::setData(), QPPDOptionsEditor::setEditorData(), QTextControl::setExtraSelections(), QMenuPrivate::setFirstActionActive(), QTreeWidgetItem::setFlags(), QTreeWidget::setHeaderLabels(), QTableWidget::setHorizontalHeaderLabels(), QStandardItemModel::setHorizontalHeaderLabels(), QDeclarativeItemPrivate::setImplicitLayoutMirror(), QGraphicsItem::setInputMethodHints(), QMenuPrivate::setMacMenuEnabled(), QDeclarativeEngineDebugService::setMethodBody(), QMacPasteboard::setMimeData(), QFileDialog::setNameFilters(), QFileSystemModel::setNameFilters(), ModelNode::setObjectValue(), QPatternist::TripleContainer::setOperands(), QPatternist::SingleContainer::setOperands(), QPatternist::PairContainer::setOperands(), QStyleSheetStyle::setProperties(), FlatListModel::setProperty(), QVideoSurfaceFormat::setProperty(), NestedListModel::setProperty(), QActionPrivate::setShortcutEnabled(), QDeclarativePropertyPrivate::setSignalExpression(), QDockAreaLayoutInfo::setTabBarShape(), QAccessibleAbstractScrollArea::setText(), QScriptExtensionPlugin::setupPackage(), QTableWidget::setVerticalHeaderLabels(), QStandardItemModel::setVerticalHeaderLabels(), shiftConstraints(), QSidebar::showContextMenu(), QFileDialogComboBox::showPopup(), QDeclarativePropertyPrivate::signalExpression(), QPatternist::ErrorFN::signature(), QPatternist::XsdSchema::simpleTypes(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QStyleSheetStyle::sizeFromContents(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutInfo::sizeHint(), QDockAreaLayoutItem::skip(), QToolBarAreaLayoutLine::skip(), sm_setProperty(), socketNotifierSourceCheck(), socketNotifierSourceDispatch(), QStringListModel::sort(), QFileSystemModel::sort(), QListModel::sort(), QFileSystemModelPrivate::sortChildren(), QTreeModel::sortItems(), QCss::Selector::specificity(), QDirPrivate::splitFilters(), QFSCompleter::splitPath(), QAbstractItemView::startDrag(), QSslSocketBackendPrivate::startHandshake(), QAccessibleAbstractScrollArea::state(), QAccessibleMdiArea::state(), QAccessibleWorkspace::state(), QWidgetBackingStore::staticContents(), QXmlQueryPrivate::staticContext(), QPluginLoader::staticInstances(), QPatternist::SumFN::staticType(), QPatternist::SubsequenceFN::staticType(), QSettingsPrivate::stringListToVariantList(), QCss::StyleSelector::styleRulesForNode(), QStyleSheetStyle::subControlRect(), QScreen::subScreenIndexAt(), QPatternist::XsdParticleChecker::subsumes(), QMdiAreaPrivate::subWindowList(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QSslSocketPrivate::systemCaCertificates(), QSystemTrayIconSys::sysTrayTracker(), QMainWindow::tabifiedDockWidgets(), QListModel::take(), QToolBarLayout::takeAt(), QDockAreaLayoutInfo::takeAt(), QToolBarAreaLayout::takeAt(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), QPatternist::ParserContext::templateParametersHandled(), QDeclarativeCompiler::testQualifiedEnumAssignment(), QAccessibleAbstractScrollArea::text(), QStyleSheetStyle::titleBarLayout(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), QToolBarAreaLayout::toolBarBreak(), topLevelWidgets(), QScriptContext::toString(), NestedListModel::toString(), QGraphicsScenePrivate::touchEventHandler(), QDeclarativeTransitionManager::transition(), QDeclarativeScriptAction::transition(), QDeclarativePropertyAction::transition(), QDeclarativePropertyAnimation::transition(), QDeclarativeParentAnimation::transition(), QDeclarativeAnchorAnimation::transition(), QWSInputContext::translateIMEvent(), QApplicationPrivate::translateRawTouchEvent(), QGraphicsViewPrivate::translateTouchEvent(), QFileSystemModelPrivate::translateVisibleLocation(), translateWSAError(), QThreadPoolPrivate::tryStart(), QPatternist::ResolveURIFN::typeCheck(), QPatternist::FunctionCall::typeCheck(), QPatternist::ElementConstructor::typeCheck(), QPatternist::DocumentFN::typeCheck(), QPatternist::SumFN::typeCheck(), QPatternist::OrderBy::typeCheck(), QAxServerBase::Unadvise(), uncShareExists(), QDockAreaLayoutInfo::unnest(), QDockAreaLayoutInfo::unplug(), QToolBarAreaLayout::unplug(), QDBusConnection::unregisterObject(), QFactoryLoader::update(), QAxServerBase::update(), QSortFilterProxyModelPrivate::update_persistent_indexes(), QNetworkManagerEngine::updateAccessPoint(), QMenuPrivate::updateActionRects(), QGraphicsAnchorLayoutPrivate::updateAnchorSizes(), QUnifiedTimer::updateAnimationsTime(), QDeclarativeStateGroupPrivate::updateAutoState(), QFactoryLoader::updateDir(), QAbstractItemView::updateEditorGeometries(), QToolBarLayout::updateGeomArray(), QMenuBarPrivate::updateGeometries(), ModelNode::updateListIndexes(), QGraphicsItem::updateMicroFocus(), QDockAreaLayoutInfo::updateSeparatorWidgets(), QDockAreaLayoutInfo::updateTabBar(), QGraphicsScenePrivate::updateTouchPointsForItem(), QApplicationPrivate::updateTouchPointsForWidget(), QPatternist::VariableDeclaration::usedByMany(), QDockAreaLayoutInfo::usedSeparatorWidgets(), QDockAreaLayoutInfo::usedTabBars(), QAccessibleWidget::userActionCount(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::TagValidationHandler::validate(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdValidatingInstanceReader::validateIdentityConstraint(), QTabBarPrivate::validIndex(), NestedListModel::valueForNode(), QPatternist::XsdTypeChecker::valuesAreEqual(), QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue(), QColumnView::visualRegionForSelection(), QTableView::visualRegionForSelection(), QListView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), QHeaderView::visualRegionForSelection(), QFutureSynchronizer< T >::waitForFinished(), waitForPopup(), QWSDisplay::windowList(), WinMain(), QDeclarativePropertyPrivate::write(), ICOReader::write(), QUnixSocketPrivate::writeActivated(), writingSystemForFont(), QApplicationPrivate::x11_apply_settings(), QPatternist::yyparse(), NodeImpl::~NodeImpl(), QAuServer::~QAuServer(), QAxServerBase::~QAxServerBase(), QDeclarativeCompiledData::~QDeclarativeCompiledData(), QDeclarativeContents::~QDeclarativeContents(), QDeclarativeMetaTypeData::~QDeclarativeMetaTypeData(), QDeclarativeTypeData::~QDeclarativeTypeData(), QFSFileEngine::~QFSFileEngine(), and QTreeWidgetItem::~QTreeWidgetItem().
 {
     int c = 0;
     Node *b = reinterpret_cast<Node *>(p.begin());
     Node *i = reinterpret_cast<Node *>(p.end());
     while (i-- != b)
         if (i->t() == t)
             ++c;
     return c;
 }
count() [2/2]
template<typename T> int QList< T >::count () const inline
Returns the number of items in the list.
This is effectively the same as size().
Definition at line 280 of file qlist.h.
 { return p.size(); }
detach()
template<typename T> void QList< T >::detach () inline
Warning
This function is not part of the public interface.
Definition at line 139 of file qlist.h.
 { if (d->ref != 1) detach_helper(); }
detach_helper() [1/2]
template<typename T > Q_OUTOFLINE_TEMPLATE void QList< T >::detach_helper (int alloc) private
Definition at line 706 of file qlist.h.
 {
     Node *n = reinterpret_cast<Node *>(p.begin());
     QListData::Data *x = p.detach(alloc);
     QT_TRY {
         node_copy(reinterpret_cast<Node *>(p.begin()), reinterpret_cast<Node *>(p.end()), n);
     } QT_CATCH(...) {
         qFree(d);
         d = x;
         QT_RETHROW;
     }
     if (!x->ref.deref())
         free(x);
 }
detach_helper() [2/2]
template<typename T > Q_OUTOFLINE_TEMPLATE void QList< T >::detach_helper () private
Definition at line 723 of file qlist.h.
 {
     detach_helper(d->alloc);
 }
detach_helper_grow()
template<typename T > Q_OUTOFLINE_TEMPLATE QList< T >::Node * QList< T >::detach_helper_grow (int i, int n) private
Definition at line 676 of file qlist.h.
 {
     Node *n = reinterpret_cast<Node *>(p.begin());
     QListData::Data *x = p.detach_grow(&i, c);
     QT_TRY {
         node_copy(reinterpret_cast<Node *>(p.begin()),
                   reinterpret_cast<Node *>(p.begin() + i), n);
     } QT_CATCH(...) {
         qFree(d);
         d = x;
         QT_RETHROW;
     }
     QT_TRY {
         node_copy(reinterpret_cast<Node *>(p.begin() + i + c),
                   reinterpret_cast<Node *>(p.end()), n + i);
     } QT_CATCH(...) {
         node_destruct(reinterpret_cast<Node *>(p.begin()),
                       reinterpret_cast<Node *>(p.begin() + i));
         qFree(d);
         d = x;
         QT_RETHROW;
     }
     if (!x->ref.deref())
         free(x);
     return reinterpret_cast<Node *>(p.begin() + i);
 }
detachShared()
template<typename T> void QList< T >::detachShared () inline
This prevents needless mallocs, and makes QList more exception safe in case of cleanup work done in destructors on empty lists.
Warning
This function is not part of the public interface.
like detach(), but does nothing if we're shared_null.
Definition at line 141 of file qlist.h.
     {
         // The "this->" qualification is needed for GCCE.
         if (d->ref != 1 && this->d != &QListData::shared_null)
             detach_helper();
     }
empty()
template<typename T> bool QList< T >::empty () const inline
This function is provided for STL compatibility.
It is equivalent to isEmpty() and returns true if the list is empty.
Definition at line 304 of file qlist.h.
Referenced by QCoreApplication::applicationFilePath(), QMdi::MinOverlapPlacer::findBestPlacement(), QBenchmarkValgrindUtils::getNewestFileName(), QWSServer::mouseHandler(), QSslSocketBackendPrivate::startHandshake(), and QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate().
 { return isEmpty(); }
end() [1/2]
template<typename T> QList::iterator QList< T >::end () inline
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
See also
begin(), constEnd()
Definition at line 270 of file qlist.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QFileSystemModelPrivate::_q_directoryChanged(), QScriptDebuggerConsoleWidgetPrivate::_q_onCompletionTaskFinished(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QDeclarativeImportsPrivate::add(), QDeclarativeTimeLinePrivate::advance(), QCopChannel::answer(), QSyntaxHighlighterPrivate::applyFormatChanges(), QStateMachinePrivate::applyProperties(), QTextEngine::calculateTabWidth(), QWorkspace::cascade(), QRingBuffer< T >::clear(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QTreeViewPrivate::columnRanges(), QPatternist::UnlimitedContainer::compressOperands(), convertFlags(), QNetworkCookieJar::cookiesForUrl(), createInterfaces(), QCopChannel::detach(), QSvgG::draw(), QSvgTinyDocument::draw(), QSvgSwitch::draw(), QAbstractItemModel::encodeData(), QThreadPoolPrivate::enqueueTask(), QGraphicsItemPrivate::ensureSequentialSiblingIndex(), QGraphicsScenePrivate::ensureSequentialTopLevelSiblingIndexes(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QGraphicsScenePrivate::ensureSortedTopLevelItems(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), fallbackFamilies(), findAllLibCrypto(), findAllLibSsl(), QMdi::MinOverlapPlacer::getCandidatePlacements(), QListModel::insert(), QGraphicsItemAnimationPrivate::insertUniquePair(), interfaceListing(), QSimplexConstraint::invert(), QAxScript::load(), QAxScriptManager::load(), QScript::QObjectData::mark(), QItemSelection::merge(), QDirModel::mimeData(), QFileSystemModel::mimeData(), QBBWindow::offset(), QHttpHeader::parse(), QWorkspacePrivate::place(), postProcess(), QDeclarativeBasePositioner::prePositioning(), QTDSDriver::primaryIndex(), QXmlSimpleReaderPrivate::processElementEmptyTag(), QDeclarativeDomObjectPrivate::properties(), qax_startServer(), qax_stopServer(), QAxConnection::QAxConnection(), QClassFactory::QClassFactory(), qDBusRemoveTimeout(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), qGetODBCVersion(), qSplitTableQualifier(), QtPrivate::QStringList_removeDuplicates(), QApplicationPrivate::qt_mac_apply_settings(), qt_mac_send_posted_gl_updates(), qt_mac_update_child_gl_widgets(), qt_mac_update_intersected_gl_widgets(), qt_wce_delete_action_list(), qt_win_extract_filter(), qt_win_filter(), qt_win_get_save_file_name(), MetaObjectGenerator::readClassInfo(), QHttpNetworkReplyPrivate::removeAutoDecompressHeader(), QWindowsFileSystemWatcherEngine::removePaths(), QCoreApplication::removePostedEvents(), QDeclarativeImportsPrivate::resolvedUri(), QSvgHandler::resolveGradients(), QAxScriptManager::scriptFileFilter(), QTreeViewPrivate::select(), QAbstractItemView::selectedIndexes(), QAxBase::setControl(), QBBWindow::setGeometry(), QHttpNetworkHeaderPrivate::setHeaderField(), QMacPasteboard::setMimeData(), QBBWindow::setScreen(), QSimplex::simplifyConstraints(), sm_setProperty(), QStringListModel::sort(), QFileSystemModelPrivate::sortChildren(), QGraphicsSceneBspTreeIndexPrivate::sortItems(), QThreadPoolPrivate::stealRunnable(), QTextBlockFormat::tabPositions(), MetaObjectGenerator::tryCache(), QPatternist::ExpressionSequence::typeCheck(), QTableModel::updateRowIndexes(), QBBWindow::updateVisibility(), QBBWindow::updateZorder(), QTextOdfWriter::writeAll(), QTextOdfWriter::writeBlockFormat(), writeTypesEnum(), QApplicationPrivate::x11_apply_settings(), QMenuBarPrivate::QMacMenuBarPrivate::~QMacMenuBarPrivate(), and QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate().
 { detach(); return reinterpret_cast<Node *>(p.end()); }
end() [2/2]
template<typename T> const_iterator QList< T >::end () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 271 of file qlist.h.
 { return reinterpret_cast<Node *>(p.end()); }
endsWith()
template<typename T> bool QList< T >::endsWith (const T & value) const inline
Returns true if this list is not empty and its last item is equal to value; otherwise returns false.
Since
4.5
See also
isEmpty(), contains()
Definition at line 289 of file qlist.h.
Referenced by QFSCompleter::splitPath().
 { return !isEmpty() && last() == t; }
erase() [1/2]
template<typename T > QList< T >::iterator QList< T >::erase (iterator pos) inline
Removes the item associated with the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
See also
insert(), removeAt()
Definition at line 464 of file qlist.h.
Referenced by QItemSelectionModelPrivate::_q_columnsAboutToBeInserted(), QItemSelectionModelPrivate::_q_rowsAboutToBeInserted(), QCopChannel::answer(), QSyntaxHighlighterPrivate::applyFormatChanges(), QStateMachinePrivate::applyProperties(), QRingBuffer< T >::clear(), QCopChannel::detach(), fallbackFamilies(), QItemSelection::merge(), qDBusRemoveTimeout(), QtPrivate::QStringList_removeDuplicates(), rasterFallbacksMask(), QHttpNetworkReplyPrivate::removeAutoDecompressHeader(), QList< QPostEvent >::removeOne(), QCoreApplication::removePostedEvents(), QAbstractItemView::selectedIndexes(), QCoreApplicationPrivate::sendPostedEvents(), QHttpNetworkHeaderPrivate::setHeaderField(), QSimplex::simplifyConstraints(), and QThreadPoolPrivate::stealRunnable().
 { node_destruct(it.i);
  return reinterpret_cast<Node *>(p.erase(reinterpret_cast<void**>(it.i))); }
erase() [2/2]
template<typename T> QList::iterator QList< T >::erase (iterator begin, iterator end)
Removes all the items from begin up to (but not including) end.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns an iterator to the same item that end referred to before the call.
first() [1/2]
template<typename T> T & QList< T >::first () inline
Returns a reference to the first item in the list.
The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
See also
last(), isEmpty()
Definition at line 282 of file qlist.h.
Referenced by QCompleterPrivate::_q_completionSelected(), QFtpPrivate::_q_startNextCommand(), QHttpPrivate::_q_startNextRequest(), QFileDialogPrivate::_q_updateOkButton(), QFileDialog::accept(), QApplication::activeModalWidget(), QButtonGroup::addButton(), Maemo::IcdPrivate::addrinfo(), QCoreApplication::applicationFilePath(), QGlobalNetworkProxy::applicationProxy(), QHttpPartPrivate::checkHeaderCreated(), QSimplex::clearDataStructures(), QGraphicsScenePrivate::clearKeyboardGrabber(), QGraphicsScenePrivate::clearMouseGrabber(), QPdfBaseEnginePrivate::closePrintDevice(), QDateTimeEditPrivate::closestSection(), comparableType(), QDeclarativeCompiler::compile(), QPatternist::ComparesCaseAware::compress(), QPatternist::ReturnOrderBy::compress(), QPatternist::CountFN::compress(), QPatternist::FirstItemPredicate::compress(), QPatternist::StringJoinFN::compress(), QPatternist::Existence< Id >::compress(), QPatternist::NormalizeUnicodeFN::compress(), QPatternist::Expression::constantPropagate(), QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints(), QHttpNetworkHeaderPrivate::contentLength(), QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeAny::convertToMime(), QMacPasteboardMimePlainText::convertToMime(), QMacPasteboardMimeUnicodeText::convertToMime(), QMacPasteboardMimeHTMLText::convertToMime(), QMacPasteboardMimeTiff::convertToMime(), QPatternist::createDirAttributeValue(), QHeaderViewPrivate::createSectionSpan(), QScriptDebuggerScriptsModel::data(), QAudioDeviceInfoInternal::defaultInputDevice(), QAudioDeviceInfoInternal::defaultOutputDevice(), QMessageBoxPrivate::detectEscapeButton(), QMainWindowLayout::dockWidgetArea(), QFbScreen::doRedraw(), QFileDialogPrivate::emitFilesSelected(), QPatternist::ElementAvailableFN::evaluateEBV(), QPatternist::UnparsedTextAvailableFN::evaluateEBV(), QPatternist::DeepEqualFN::evaluateEBV(), QPatternist::ReturnOrderBy::evaluateEBV(), QPatternist::BooleanFN::evaluateEBV(), QPatternist::NotFN::evaluateEBV(), QPatternist::Existence< Id >::evaluateEBV(), QPatternist::StringToCodepointsFN::evaluateSequence(), QPatternist::IndexOfFN::evaluateSequence(), QPatternist::TokenizeFN::evaluateSequence(), QPatternist::InScopePrefixesFN::evaluateSequence(), QPatternist::DistinctValuesFN::evaluateSequence(), QPatternist::InsertBeforeFN::evaluateSequence(), QPatternist::RemoveFN::evaluateSequence(), QPatternist::ReverseFN::evaluateSequence(), QPatternist::SubsequenceFN::evaluateSequence(), QPatternist::ResolveURIFN::evaluateSingleton(), QPatternist::DateTimeFN::evaluateSingleton(), QPatternist::SystemPropertyFN::evaluateSingleton(), QPatternist::FunctionAvailableFN::evaluateSingleton(), QPatternist::GenerateIDFN::evaluateSingleton(), QPatternist::TypeAvailableFN::evaluateSingleton(), QPatternist::UnparsedTextFN::evaluateSingleton(), QPatternist::ContainsFN::evaluateSingleton(), QPatternist::NodeNameFN::evaluateSingleton(), QPatternist::CodepointEqualFN::evaluateSingleton(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::NameFN::evaluateSingleton(), QPatternist::FloorFN::evaluateSingleton(), QPatternist::MatchesFN::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::CodepointsToStringFN::evaluateSingleton(), QPatternist::ReturnOrderBy::evaluateSingleton(), QPatternist::CountFN::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::StartsWithFN::evaluateSingleton(), QPatternist::NilledFN::evaluateSingleton(), QPatternist::CompareFN::evaluateSingleton(), QPatternist::LocalNameFN::evaluateSingleton(), QPatternist::AbsFN::evaluateSingleton(), QPatternist::ResolveQNameFN::evaluateSingleton(), QPatternist::ReplaceFN::evaluateSingleton(), QPatternist::StringJoinFN::evaluateSingleton(), QPatternist::EndsWithFN::evaluateSingleton(), QPatternist::StringFN::evaluateSingleton(), QPatternist::NamespaceURIFN::evaluateSingleton(), QPatternist::RoundFN::evaluateSingleton(), QPatternist::PrefixFromQNameFN::evaluateSingleton(), QPatternist::SubstringFN::evaluateSingleton(), QPatternist::SubstringBeforeFN::evaluateSingleton(), QPatternist::BaseURIFN::evaluateSingleton(), QPatternist::CeilingFN::evaluateSingleton(), QPatternist::LocalNameFromQNameFN::evaluateSingleton(), QPatternist::NumberFN::evaluateSingleton(), QPatternist::AvgFN::evaluateSingleton(), QPatternist::StringLengthFN::evaluateSingleton(), QPatternist::SubstringAfterFN::evaluateSingleton(), QPatternist::DocumentURIFN::evaluateSingleton(), QPatternist::NamespaceURIFromQNameFN::evaluateSingleton(), QPatternist::RoundHalfToEvenFN::evaluateSingleton(), QPatternist::NormalizeSpaceFN::evaluateSingleton(), QPatternist::NamespaceURIForPrefixFN::evaluateSingleton(), QPatternist::SumFN::evaluateSingleton(), QPatternist::LangFN::evaluateSingleton(), QPatternist::NormalizeUnicodeFN::evaluateSingleton(), QPatternist::RootFN::evaluateSingleton(), QPatternist::UpperCaseFN::evaluateSingleton(), QPatternist::LowerCaseFN::evaluateSingleton(), QPatternist::TranslateFN::evaluateSingleton(), QPatternist::EncodeString::evaluateSingleton(), QPatternist::RemoveFN::evaluateSingleton(), QWidget::event(), QPatternist::findAxisStep(), QComboBox::findData(), QHttpPrivate::finishedWithError(), QHttpPrivate::finishedWithSuccess(), Node::firstChild(), QMainWindowLayoutState::gapRect(), Maemo::get_addrinfo_all_result(), get_network_interface(), QIcdEngine::getIcdInitialState(), QQueue< QHostInfoRunnable *>::head(), QHttpNetworkRequestPrivate::header(), QHttpNetworkHeaderPrivate::headerFieldValues(), QmlJSDebugger::LiveSelectionTool::hoverMoveEvent(), QDirModel::index(), QDockAreaLayoutInfo::info(), QDockAreaLayout::info(), QSslCertificatePrivate::init(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), QDockAreaLayoutInfo::insertGap(), QMainWindowLayoutState::insertGap(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayout::insertGap(), QDockAreaLayout::insertGap(), QPatternist::Expression::invokeOptimizers(), QGraphicsItem::isBlockedByModalPanel(), QPatternist::ValueComparison::isCaseInsensitiveCompare(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QMainWindowLayoutState::item(), QDockAreaLayoutInfo::item(), QDockAreaLayout::item(), QGraphicsScene::itemAt(), QGraphicsView::itemAt(), QMainWindowLayoutState::itemRect(), QDockAreaLayoutInfo::itemRect(), QToolBarAreaLayout::itemRect(), QDockAreaLayout::itemRect(), QWSServer::keyboardHandler(), QDialogButtonBoxPrivate::layoutButtons(), QGraphicsItemAnimationPrivate::linearValueForStep(), macValue(), QDeclarativeOpenMetaObject::metaCall(), QDeclarativeType::metaObject(), QXlibMime::mimeDataForAtom(), QWSServer::mouseHandler(), QmlJSDebugger::QDeclarativeViewInspector::mouseMoveEvent(), QGraphicsScenePrivate::mousePressEventHandler(), multicastMembershipHelper(), QRingBuffer< T >::nextDataBlockSize(), QFileSystemModelPrivate::node(), QAudioDeviceInfoInternal::open(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), QPatternist::UnlimitedContainer::operandsUnionType(), QAuthenticatorPrivate::parseHttpResponse(), QDockAreaLayoutInfo::plug(), QMainWindowLayoutState::plug(), QDockAreaLayout::plug(), QBBIntegration::primaryDisplay(), QFtpPI::processReply(), QKeySequence::QKeySequence(), qt_init(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), qt_tildeExpansion(), QDeclarativeXmlListModel::queryCompleted(), QVNCIntegration::QVNCIntegration(), QNetworkHeadersPrivate::rawHeadersKeys(), QByteDataBuffer::read(), QRingBuffer< T >::readPointer(), QDockAreaLayoutInfo::remove(), QMainWindowLayoutState::remove(), QDockAreaLayout::remove(), QHttpNetworkReplyPrivate::removeAutoDecompressHeader(), QNetworkAccessHttpBackend::replyDownloadMetaData(), QPatternist::XsdSchemaResolver::resolveSubstitutionGroupAffiliations(), QDeclarativeTypeData::resolveTypes(), QPatternist::ConstructorFunctionsFactory::retrieveExpression(), QPatternist::XPath20CoreFunctions::retrieveExpression(), Maemo::IcdPrivate::scan(), QDateTimeEditPrivate::sectionAt(), QFileDialog::selectNameFilter(), QGraphicsScenePrivate::sendTouchBeginEvent(), QMainWindowPrivate::separatorCursor(), QDockAreaLayoutInfo::separatorRect(), QDockAreaLayout::separatorRect(), server(), QSimplex::setConstraints(), QHttpNetworkHeaderPrivate::setHeaderField(), QPatternist::TripleContainer::setOperands(), QPatternist::SingleContainer::setOperands(), QPatternist::PairContainer::setOperands(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QByteDataBuffer::sizeNextBlock(), QProcess::start(), QProcess::startDetached(), QSslSocketBackendPrivate::startHandshake(), QFtpPI::startNextCmd(), Maemo::IcdPrivate::state(), QPatternist::FunctionCall::staticType(), QPatternist::ReturnOrderBy::staticType(), QPatternist::Aggregator::staticType(), QPatternist::AvgFN::staticType(), QPatternist::SumFN::staticType(), QPatternist::RootFN::staticType(), QPatternist::DistinctValuesFN::staticType(), QPatternist::InsertBeforeFN::staticType(), QPatternist::RemoveFN::staticType(), QPatternist::ReverseFN::staticType(), QPatternist::SubsequenceFN::staticType(), Maemo::IcdPrivate::statistics(), QJSDebugService::statusChanged(), QThreadPoolPrivate::stealRunnable(), QSvgNode::styleProperty(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QAudioDeviceInfoInternal::testSettings(), timerSourceCheckHelper(), QPainterPath::toFillPolygon(), QmlJSDebugger::LiveRubberBandSelectionManipulator::topFormEditorItem(), QThreadPoolPrivate::tryToStartMoreThreads(), QPatternist::DeepEqualFN::typeCheck(), QPatternist::FunctionCall::typeCheck(), QPatternist::StringFN::typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::IndexOfFN::typeCheck(), QPatternist::DocumentFN::typeCheck(), QPatternist::AvgFN::typeCheck(), QPatternist::NumberFN::typeCheck(), QPatternist::DocFN::typeCheck(), QPatternist::SumFN::typeCheck(), QPatternist::DistinctValuesFN::typeCheck(), QPatternist::ReverseFN::typeCheck(), QDockAreaLayoutInfo::unnest(), QDockAreaLayoutInfo::unplug(), QMainWindowLayoutState::unplug(), QDockAreaLayout::unplug(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QPatternist::TypeChecker::verifyType(), QGraphicsScene::wheelEvent(), QPatternist::XsdSchemaHelper::wildcardUnion(), QX11Data::xdndMimeDataForAtom(), QPatternist::yyparse(), QGraphicsItem::~QGraphicsItem(), QWindowsMimeList::~QWindowsMimeList(), and QWSWindow::~QWSWindow().
 { Q_ASSERT(!isEmpty()); return *begin(); }
first() [2/2]
template<typename T> const T & QList< T >::first () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 283 of file qlist.h.
 { Q_ASSERT(!isEmpty()); return at(0); }
free()
template<typename T > Q_OUTOFLINE_TEMPLATE void QList< T >::free (QListData::Data * d) private
Definition at line 755 of file qlist.h.
 {
     node_destruct(reinterpret_cast<Node *>(data->array + data->begin),
                   reinterpret_cast<Node *>(data->array + data->end));
     qFree(data);
 }
fromSet()
template<typename T> QList< T > QList< T >::fromSet (const QSet< T > & set) static
Returns a QList object with the data contained in set.
The order of the elements in the QList is undefined.
Example:
QSet<int> set;
set << 20 << 30 << 40 << ... << 70;
QList<int> list = QList<int>::fromSet(set);
qSort(list);
See also
fromVector(), toSet(), QSet::toList(), qSort()
Definition at line 325 of file qset.h.
 {
     return set.toList();
 }
fromStdList()
template<typename T> QList< T > QList< T >::fromStdList (const std::list< T > & list) inline static
Returns a QList object with the data contained in list.
The order of the elements in the QList is the same as in list.
Example:
std::list<double> stdlist;
list.push_back(1.2);
list.push_back(0.5);
list.push_back(3.14);
QList<double> list = QList<double>::fromStdList(stdlist);
See also
toStdList(), QVector::fromStdVector()
Definition at line 345 of file qlist.h.
     { QList<T> tmp; qCopy(list.begin(), list.end(), std::back_inserter(tmp)); return tmp; }
fromVector()
template<typename T> QList< T > QList< T >::fromVector (const QVector< T > & vector) static
Returns a QList object with the data contained in vector.
Example:
QVector<double> vect;
vect << 20.0 << 30.0 << 40.0 << 50.0;
QList<double> list = QVector<T>::fromVector(vect);
// list: [20.0, 30.0, 40.0, 50.0]
See also
fromSet(), toVector(), QVector::toList()
Definition at line 795 of file qvector.h.
 {
     return vector.toList();
 }
front() [1/2]
template<typename T> T & QList< T >::front () inline
This function is provided for STL compatibility.
It is equivalent to first(). The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
Definition at line 298 of file qlist.h.
Referenced by QHeaderViewPrivate::resizeSections().
 { return first(); }
front() [2/2]
template<typename T> const T & QList< T >::front () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 299 of file qlist.h.
 { return first(); }
indexOf()
template<typename T> Q_OUTOFLINE_TEMPLATE int QList< T >::indexOf (const T & value, int from = 0) const
Returns the index position of the first occurrence of value in the list, searching forward from index position from.
Returns -1 if no item matched.
Example:
QList<QString> list;
list << "A" << "B" << "C" << "B" << "A";
list.indexOf("B");          // returns 1
list.indexOf("B", 1);       // returns 1
list.indexOf("B", 2);       // returns 3
list.indexOf("X");          // returns -1
This function requires the value type to have an implementation of operator==().
Note that QList uses 0-based indexes, just like C++ arrays. Negative indexes are not supported with the exception of the value mentioned above.
See also
lastIndexOf(), contains()
Definition at line 847 of file qlist.h.
Referenced by QMenuBarPrivate::_q_actionHovered(), QFileDialogPrivate::_q_showHeader(), QMenuBarPrivate::actionRect(), QMenuPrivate::actionRect(), QMenuBarPrivate::QMacMenuBarPrivate::addAction(), QMenuBarPrivate::QWceMenuBarPrivate::addAction(), QMenuPrivate::QMacMenuPrivate::addAction(), QMenuPrivate::QWceMenuPrivate::addAction(), QFontSubset::addGlyph(), QMdiAreaPrivate::appendChild(), QAccessibleMenu::childAt(), QGraphicsScene::createItemGroup(), QGLWindowSurface::deleted(), QFutureInterfaceBasePrivate::disconnectOutputInterface(), QMainWindowLayout::dockWidgetArea(), QMdiAreaPrivate::emitWindowActivated(), QFontSubset::getReverseMap(), QMdiAreaPrivate::highlightNextSubWindow(), QDeclarativeCompiledData::indexForByteArray(), QDeclarativeCompiledData::indexForString(), QDeclarativeCompiledData::indexForUrl(), QScriptDebuggerLocalsModelPrivate::indexFromNode(), QAccessibleWidget::indexOfChild(), QAccessibleMenu::indexOfChild(), QAccessibleAbstractScrollArea::indexOfChild(), QAccessibleMenuBar::indexOfChild(), QAccessibleApplication::indexOfChild(), QAccessibleItemRow::indexOfChild(), QAccessibleWorkspace::indexOfChild(), QAccessibleMainWindow::indexOfChild(), QImageReaderPrivate::initHandler(), QFbScreen::lower(), QWidget::lower(), QUnicodeControlCharacterMenu::menuActionTriggered(), QAccessibleItemRow::navigate(), QMdiAreaPrivate::nextVisibleSubWindow(), QStringList::operator<<(), QVideoSurfaceFormatPrivate::operator==(), QMainWindowLayout::plug(), QObject::property(), QMainWindowLayout::qtmacToolbarDelegate(), QTreeWidgetItem::QTreeWidgetItem(), QFbScreen::raise(), QWidget::raise(), read_xpm_body(), QMdiAreaPrivate::rearrange(), QObjectCleanupHandler::remove(), QListModel::remove(), QTextFramePrivate::remove_me(), QGraphicsScenePrivate::removePopup(), QObjectPrivate::setParent_helper(), QObject::setProperty(), QMdiAreaPrivate::setViewMode(), QWidget::stackUnder(), QStateMachinePrivate::stateEntryLessThan(), QStateMachinePrivate::stateExitLessThan(), QWidgetPrivate::subtractOpaqueSiblings(), QGraphicsScenePrivate::ungrabMouse(), QUnifiedTimer::unregisterAnimation(), QMenuBarPrivate::wceDestroyMenuBar(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), and QTreeWidgetItem::~QTreeWidgetItem().
 {
     if (from < 0)
         from = qMax(from + p.size(), 0);
     if (from < p.size()) {
         Node *n = reinterpret_cast<Node *>(p.at(from -1));
         Node *e = reinterpret_cast<Node *>(p.end());
         while (++n != e)
             if (n->t() == t)
                 return int(n - reinterpret_cast<Node *>(p.begin()));
     }
     return -1;
 }
insert() [1/2]
template<typename T> void QList< T >::insert (int i, const T & value) inline
Inserts value at index position i in the list.
If i is 0, the value is prepended to the list. If i is size(), the value is appended to the list.
Example:
QList<QString> list;
list << "alpha" << "beta" << "delta";
list.insert(2, "gamma");
// list: ["alpha", "beta", "gamma", "delta"]
See also
append(), prepend(), replace(), removeAt()
Definition at line 575 of file qlist.h.
Referenced by QObjectCleanupHandler::add(), QMenuBarPrivate::QMacMenuBarPrivate::addAction(), QMenuBarPrivate::QWceMenuBarPrivate::addAction(), QMenuPrivate::QMacMenuPrivate::addAction(), QMenuPrivate::QWceMenuPrivate::addAction(), QPollingFileSystemWatcherEngine::addPaths(), QTreeWidgetItem::clone(), QTextCodec::codecForName(), QNetworkCookieJar::cookiesForUrl(), QDeclarativeXmlQueryEngine::doSubQueryJob(), QThreadPoolPrivate::enqueueTask(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QApplicationPrivate::enterModal_sys(), find_translation(), QGLEngineSharedShaders::findProgramInCache(), QListModel::insert(), FlatListModel::insert(), NestedListModel::insert(), QTextDocumentPrivate::insert_frame(), QToolBarLayout::insertAction(), QTreeWidgetItem::insertChild(), QTreeWidgetItem::insertChildren(), QStandardItemPrivate::insertColumns(), FlatListModel::insertedNode(), QDockAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertItem(), QStringListModel::insertRows(), QListModel::insertRows(), QStandardItemPrivate::insertRows(), QTreeModel::insertRows(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QNetworkManagerEngine::interfacePropertiesChanged(), QGraphicsItem::mouseReleaseEvent(), qt_try_modal(), QtWndProc(), QApplication::qwsSetCustomColors(), QTextFramePrivate::remove_me(), QFileSystemModel::setData(), QDockAreaLayoutInfo::split(), and QApplication::x11EventFilter().
 {
     if (d->ref != 1) {
         Node *n = detach_helper_grow(i, 1);
         QT_TRY {
             node_construct(n, t);
         } QT_CATCH(...) {
             p.remove(i);
             QT_RETHROW;
         }
     } else {
         if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) {
             Node *n = reinterpret_cast<Node *>(p.insert(i));
             QT_TRY {
                 node_construct(n, t);
             } QT_CATCH(...) {
                 p.remove(i);
                 QT_RETHROW;
             }
         } else {
             Node *n, copy;
             node_construct(&copy, t); // t might be a reference to an object in the array
             QT_TRY {
                 n = reinterpret_cast<Node *>(p.insert(i));;
             } QT_CATCH(...) {
                 node_destruct(&copy);
                 QT_RETHROW;
             }
             *n = copy;
         }
     }
 }
insert() [2/2]
template<typename T> QList< T >::iterator QList< T >::insert (iterator before, const T & value) inline
Inserts value in front of the item pointed to by the iterator before.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns an iterator pointing at the inserted item. Note that the iterator passed to the function will be invalid after the call; the returned iterator should be used instead.
Definition at line 451 of file qlist.h.
 {
     int iBefore = int(before.i - reinterpret_cast<Node *>(p.begin()));
     Node *n = reinterpret_cast<Node *>(p.insert(iBefore));
     QT_TRY {
         node_construct(n, t);
     } QT_CATCH(...) {
         p.remove(iBefore);
         QT_RETHROW;
     }
     return n;
 }
isDetached()
template<typename T> bool QList< T >::isDetached () const inline
Warning
This function is not part of the public interface.
Definition at line 148 of file qlist.h.
 { return d->ref == 1; }
isEmpty()
template<typename T> bool QList< T >::isEmpty () const inline
Returns true if the list contains no items; otherwise returns false.
See also
size()
Definition at line 152 of file qlist.h.
Referenced by QAbstractSocketPrivate::_q_abortConnectionAttempt(), QCompleterPrivate::_q_completionSelected(), QAbstractSocketPrivate::_q_connectToNextAddress(), QGraphicsScenePrivate::_q_emitUpdated(), QFileDialogPrivate::_q_navigateBackward(), QFileDialogPrivate::_q_navigateForward(), QWSServerPrivate::_q_newConnection(), QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved(), QStateMachinePrivate::_q_start(), QHttpPrivate::_q_startNextRequest(), QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex(), QFontComboBoxPrivate::_q_updateModel(), QFileDialogPrivate::_q_updateOkButton(), QFontDialogPrivate::_q_updateSample(), QFileDialog::accept(), QmlJSDebugger::QDeclarativeInspectorPlugin::activate(), QMdiAreaPrivate::activateWindow(), QApplication::activeModalWidget(), QApplication::activePopupWidget(), actualMenuItemVisibility(), QDeclarativeImportsPrivate::add(), QFontDatabasePrivate::addAppFont(), QButtonGroup::addButton(), QSslSocket::addCaCertificates(), QScriptDebuggerLocalsModelPrivate::addChildren(), QSslSocketPrivate::addDefaultCaCertificates(), QDockAreaLayout::addDockWidget(), QJSDebugService::addEngine(), QFontDatabasePrivate::addFont(), QDeclarativeXmlQueryEngine::addIndexToRangeList(), QLocalServerPrivate::addListener(), QFileSystemWatcher::addPaths(), QDir::addResourceSearchPath(), Maemo::IcdPrivate::addrinfo(), QStateMachinePrivate::addStatesToEnter(), QFontDatabasePrivate::addTTFile(), QmlJSDebugger::LiveSelectionTool::alreadySelected(), QTextHtmlImporter::appendBlock(), QTextHtmlImporter::appendNodeText(), Maemo::appendVariantToDBusMessage(), QSyntaxHighlighterPrivate::applyFormatChanges(), QStateMachinePrivate::applyProperties(), astNodeToStringList(), QScriptEngine::availableExtensions(), QCss::StyleSelector::basicSelectorMatches(), QCss::StyleSheet::buildIndexes(), buildMatchRule(), QDeclarativeCompiler::buildObject(), buildParameterNames(), QPatternist::XsdStateMachineBuilder::buildTerm(), QPacketProtocolPrivate::bytesWritten(), QPatternist::CachingIterator::CachingIterator(), QDeclarativeContents::calcHeight(), QGraphicsAnchorLayoutPrivate::calculateGraphs(), QTextureGlyphCache::calculateSubPixelPositionCount(), QTextEngine::calculateTabWidth(), QGraphicsAnchorLayoutPrivate::calculateTrunk(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QDeclarativeContents::calcWidth(), QDBusAbstractInterface::callWithArgumentList(), QBuiltInMimes::canConvertToMime(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QWidgetPrivate::childAt_helper(), QGraphicsItemPrivate::childrenBoundingRectHelper(), cleanup_mimes(), QFontEngineQPF::cleanUpAfterClientCrash(), QGestureManager::cleanupGesturesForRemovedRecognizer(), QObjectCleanupHandler::clear(), QWSSignalHandler::clear(), QMenu::clear(), QGraphicsScenePrivate::clearKeyboardGrabber(), QGraphicsScenePrivate::clearMouseGrabber(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QUnixSocket::close(), QColumnViewPrivate::closeColumns(), QGraphicsItemPrivate::TransformData::computedFullTransform(), QQnxScreen::connect(), Maemo::constantVariantList(), QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints(), QMainWindowLayoutState::contains(), QWindowsMimeURI::convertFromMime(), QWindowsMimeURI::convertToMime(), QShortcutMap::correctContext(), QDeclarativeType::create(), QPatternist::Template::createContext(), QPatternist::createDirAttributeValue(), QGraphicsScene::createItemGroup(), QScriptDebuggerConsolePrivate::createJob(), QDirectFBScreenPrivate::createPixmapData(), QNetworkAccessManager::createRequest(), QHeaderViewPrivate::createSectionSpan(), QDBusConnectionPrivate::customEvent(), QKeySequencePrivate::decodeString(), QBoxLayoutPrivate::deleteAll(), QScriptDebuggerAgent::deleteBreakpoint(), QScriptDebuggerLocalsModelPrivate::depopulate(), QStateMachinePrivate::dequeueExternalEvent(), QStateMachinePrivate::dequeueInternalEvent(), QMainWindowLayout::dockWidgetArea(), QColumnViewPrivate::doLayout(), QScriptDebuggerBackend::doPendingEvaluate(), QGenericEngine::doRequestUpdate(), QIcdEngine::doRequestUpdate(), QDeclarativeXmlQueryEngine::doSubQueryJob(), QSvgSwitch::draw(), QGraphicsScenePrivate::draw(), QStyleSheetStyle::drawComplexControl(), QGraphicsScenePrivate::drawSubtreeRecursive(), QWidgetPrivate::drawWidget(), QAbstractItemModel::dropMimeData(), QAbstractTableModel::dropMimeData(), QAbstractListModel::dropMimeData(), QGraphicsItemPrivate::effectiveBoundingRect(), effectiveState(), effectiveTotalRangeMinimum(), QItemSelectionModel::emitSelectionChanged(), QResourcePrivate::ensureChildren(), QResourcePrivate::ensureInitialized(), QIconLoaderEngine::ensureLoaded(), QStateMachinePrivate::enterStates(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::epsilonClosure(), QGraphicsSceneBspTreeIndexPrivate::estimateItems(), QScriptDebuggerCodeView::event(), QObject::event(), QDialogButtonBox::event(), QCompleter::eventFilter(), QScriptDebuggerCommandExecutor::execute(), QStateMachinePrivate::exitStates(), expandObject(), QItemSelectionModelPrivate::expandSelection(), QHttpNetworkConnectionPrivate::fillPipeline(), QItemSelectionModelPrivate::finalize(), find_child(), QDeclarativeImportedNamespace::find_helper(), QPatternist::findAxisStep(), QComboBox::findData(), QIconLoader::findIconHelper(), QStateMachinePrivate::findLCA(), QGraphicsAnchorLayoutPrivate::findPaths(), QDockAreaLayoutInfo::findSeparator(), QDockAreaLayout::findSeparator(), findSnapshotIdsRecursively(), QHttpPrivate::finishedWithError(), QHttpPrivate::finishedWithSuccess(), Node::firstChild(), QUnixSocket::flush(), fontPath(), QDropEvent::format(), QBuiltInMimes::formatsForMime(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTransitive(), QHostInfoAgent::fromName(), QIcon::fromTheme(), QScript::functionConnect(), QMainWindowLayoutState::gapIndex(), QToolBarAreaLayout::gapIndex(), QDockAreaLayout::gapIndex(), Maemo::get_addrinfo_all_result(), Maemo::get_scan_result(), Maemo::get_statistics_all_result(), getFamiliesAndSignatures(), QFileInfoGatherer::getFileInfos(), QIcdEngine::getIcdInitialState(), QNetworkManagerEngine::getInterfaceFromId(), getScreen(), QGraphicsScenePrivate::grabKeyboard(), QGraphicsScenePrivate::grabMouse(), QNetworkReplyImplPrivate::handleNotifications(), QDBusConnectionPrivate::handleSignal(), QTextHtmlStyleSelector::hasAttributes(), QScriptDebuggerLocalsModel::hasChildren(), QPaintEngineExPrivate::hasClipOperations(), hasDuplicatedElementsInternal(), QDeclarativeDirParser::hasError(), QIconLoaderEngine::hasIcon(), QItemSelectionModel::hasSelection(), QWidgetBackingStore::hasStaticContents(), QHttpNetworkHeaderPrivate::headerField(), headerValue(), QmlJSDebugger::BoundingRectHighlighter::highlight(), QmlJSDebugger::QDeclarativeViewInspectorPrivate::highlight(), QMainWindowLayout::hover(), QmlJSDebugger::LiveSelectionTool::hoverMoveEvent(), QListModel::index(), QDirModel::index(), QSequentialAnimationGroupPrivate::indexForCurrentTime(), QMainWindowLayoutState::indexOf(), QDockAreaLayoutInfo::indexOf(), QDockAreaLayout::indexOf(), QAccessibleWorkspace::indexOfChild(), QDockAreaLayoutInfo::indexOfPlaceHolder(), QDockAreaLayout::indexOfPlaceHolder(), QDockAreaLayout::info(), QSettingsPrivate::iniEscapedStringList(), QSslCertificatePrivate::init(), QWindowsSystemProxy::init(), QMacPrintEnginePrivate::initialize(), QDeclarativePropertyPrivate::initProperty(), QSslSocketBackendPrivate::initSslContext(), QTreeWidgetItem::insertChildren(), QStandardItemPrivate::insertColumns(), QDockAreaLayoutInfo::insertGap(), QMainWindowLayoutState::insertGap(), QDockAreaLayout::insertGap(), QToolBarAreaLayoutInfo::insertItem(), QComboBox::insertItems(), QStandardItemPrivate::insertRows(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QNetworkManagerEngine::interfacePropertiesChanged(), QPatternist::Expression::invokeOptimizers(), QGraphicsItem::isBlockedByModalPanel(), QObjectCleanupHandler::isEmpty(), QDeclarativeCompiler::isError(), QDeclarativeType::isExtendedType(), QStateMachinePrivate::isExternalEventQueueEmpty(), QStateMachinePrivate::isInternalEventQueueEmpty(), QStateMachinePrivate::isPreempted(), isServerProcess(), QScriptDebuggerLocalsModelPrivate::isTopLevelNode(), QPatternist::VariableDeclaration::isUsed(), QUnixSocketMessage::isValid(), QTest::isValidSlot(), QDockAreaLayoutInfo::item(), QDockAreaLayout::item(), QGraphicsScene::itemAt(), QGraphicsView::itemAt(), QDockAreaLayoutInfo::itemRect(), QDockAreaLayout::itemRect(), QDockAreaLayout::keepSize(), QWaylandClipboard::keyboardFocus(), QObject::killTimer(), Node::lastChild(), QDialogButtonBoxPrivate::layoutButtons(), QTextDocumentLayoutPrivate::layoutFlow(), QApplicationPrivate::leaveModal_sys(), QGraphicsItemAnimationPrivate::linearValueForStep(), QDeclarativePropertyCache::Data::load(), QResourcePrivate::load(), loadEngine(), macQueryInternal(), QGraphicsScenePrivate::markDirty(), QDirIteratorPrivate::matchesFilters(), QScriptDebuggerPrivate::maybeStartNewJob(), mdiAreaNavigate(), QItemSelection::merge(), QDeclarativeType::metaObject(), QWaylandClipboard::mimeData(), QAbstractItemModel::mimeData(), QmlJSDebugger::QDeclarativeViewInspector::mouseMoveEvent(), QGraphicsScenePrivate::mousePressEventHandler(), multicastMembershipHelper(), QAccessibleMdiArea::navigate(), QAccessibleWorkspace::navigate(), QCoreWlanEngine::networksChanged(), QNlaEngine::networksChanged(), QPatternist::XSLTTokenizer::nextToken(), QMdiAreaPrivate::nextVisibleSubWindow(), QFileSystemModelPrivate::node(), QApplication::notify(), QDeclarativeDataBlob::notifyComplete(), QList< QPostEvent >::operator+=(), QPatternist::OptimizationPass::OptimizationPass(), QGraphicsView::paintEvent(), QDeclarativeScriptParser::parse(), QHttpHeader::parse(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QHostAddress::parseSubnet(), QPatternist::XsdSchemaParser::parseUnion(), QFileSystemModelPrivate::passNameFilters(), QNetworkConfigurationManagerPrivate::performAsyncConfigurationUpdate(), QDockAreaLayoutInfo::plug(), QDockAreaLayout::plug(), QMainWindowLayout::plug(), Maemo::prepareDBusCall(), QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QDeclarativeXmlQueryEngine::processJobs(), QGlobalNetworkProxy::proxyForQuery(), QUndoStack::push(), qDBusGenerateMetaObjectXml(), qDBusInterfaceFromMetaObject(), QDirModel::QDirModel(), QDirPrivate::QDirPrivate(), QIconTheme::QIconTheme(), qstring_to_xtp(), qt_call_post_routines(), qt_defaultDpiX(), qt_defaultDpiY(), qt_grab_cursor(), qt_init(), QApplicationPrivate::qt_mac_apply_settings(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), qt_mac_update_intersected_gl_widgets(), QDeclarativeBoundSignal::qt_metacall(), qt_parseEtcLpMember(), qt_parseEtcLpPrinters(), qt_parseSpoolInterface(), qt_try_modal(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), qTopLevelDomain(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QtWndProc(), QNetworkAccessManagerPrivate::queryProxy(), Maemo::NetworkProxyFactory::queryProxy(), QPatternist::XSLTTokenizer::queueVariableDeclaration(), qWinProcessConfigRequests(), qwsEventSourceCheck(), qwsEventSourceDispatch(), qwsEventSourcePrepare(), QApplication::qwsSetCustomColors(), rasterFallbacksMask(), QUnixSocket::read(), QWSDisplay::Data::readMore(), QWSClient::readMoreCommand(), QRingBuffer< T >::readPointer(), QRingBuffer< T >::readPointerAtPosition(), QMdi::RegularTiler::rearrange(), QMdi::SimpleCascader::rearrange(), QMdi::IconTiler::rearrange(), QMdiAreaPrivate::rearrange(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QActionPrivate::redoGrabAlternate(), registerFont(), QNetworkAccessCache::releaseEntry(), QDockAreaLayoutInfo::remove(), QMainWindowLayoutState::remove(), QToolBarAreaLayout::remove(), QDockAreaLayout::remove(), removeInvisibleWidgetsFromList(), QWSServer::removeKeyboardFilter(), QFileSystemWatcher::removePaths(), QPollingFileSystemWatcherEngine::removePaths(), QGraphicsScenePrivate::removePopup(), QToolBarAreaLayoutInfo::removeToolBar(), QAbstractItemViewPrivate::renderToPixmap(), QNetworkAccessHttpBackend::replySslErrors(), QTextEngine::resolveAdditionalFormats(), QPatternist::XsdSchemaParser::resolveComplexContentType(), QTextHtmlParser::resolveStyleSheetImports(), QDeclarativeTypeData::resolveTypes(), QUnifiedTimer::restartAnimationTimer(), QDockAreaLayout::restoreDockWidget(), QMainWindowLayoutState::restoreState(), QWaylandClipboard::retrieveData(), QMacPasteboard::retrieveData(), QThreadPoolThread::run(), Maemo::IcdPrivate::scan(), QNativeWifiEngine::scanComplete(), QScriptDebuggerAgent::scriptLoad(), QScriptDebuggerAgent::scriptUnload(), QMdiAreaPrivate::scrollBarPolicyChanged(), QString::section(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), QListViewPrivate::selectAll(), QFileDialog::selectedFiles(), QFileDialog::selectNameFilter(), QSqlRelationalTableModel::selectStatement(), QFutureInterfaceBasePrivate::sendCallOut(), QFutureInterfaceBasePrivate::sendCallOuts(), QFtpPI::sendCommands(), QDockAreaLayoutInfo::separatorRect(), QDockAreaLayout::separatorRect(), QDeclarativeListModel::set(), QDeclarativeListModelWorkerAgent::set(), QTextLayout::setAdditionalFormats(), QSimplex::setConstraints(), QToolBarLayout::setExpanded(), QWidgetPrivate::setLayoutDirection_helper(), QWidgetPrivate::setLocale_helper(), QWSServer::setMaxWindowRect(), QWaylandClipboard::setMimeData(), QFileDialog::setNameFilters(), QObject::setObjectName(), QDeclarativeListModel::setProperty(), QDeclarativeListModelWorkerAgent::setProperty(), setScreenTransformation(), QApplicationPrivate::setScreenTransformation(), QTreeWidget::setSelectionModel(), QAction::setShortcuts(), QStyleSheetStyle::sizeFromContents(), QByteDataBuffer::sizeNextBlock(), sm_performSaveYourself(), QDockAreaLayout::splitDockWidget(), QFSCompleter::splitPath(), QHttpThreadDelegate::sslErrorsSlot(), QProcess::start(), QMacStylePrivate::startAnimationTimer(), QProcess::startDetached(), QThreadPoolPrivate::startFrontRunnable(), QSslSocketBackendPrivate::startHandshake(), QFtpPI::startNextCmd(), QProcessPrivate::startProcess(), Maemo::IcdPrivate::state(), QAccessibleMdiArea::state(), QAccessibleWorkspace::state(), QWidgetBackingStore::staticContents(), QPatternist::FunctionCall::staticType(), QPatternist::RootFN::staticType(), Maemo::IcdPrivate::statistics(), QJSDebugService::statusChanged(), QThreadPoolPrivate::stealRunnable(), QWindowsStylePrivate::stopAnimation(), QSvgNode::styleProperty(), QStyleSheetStyle::subControlRect(), QPatternist::XsdParticleChecker::subsumes(), QWidgetPrivate::subtractOpaqueChildren(), QWidgetPrivate::subtractOpaqueSiblings(), QMdiAreaPrivate::subWindowList(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QSystemTrayIconSys::sysTrayTracker(), QDockAreaLayout::tabifyDockWidget(), QTDSDriver::tables(), QODBCDriver::tables(), QToolBarAreaLayout::takeAt(), QIconLoader::themeSearchPaths(), QMainWindowLayout::timerEvent(), QUnifiedTimer::timerEvent(), QMacStylePrivate::timerEvent(), timerSourceCheckHelper(), QStyleSheetStyle::titleBarLayout(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), QPainterPath::toFillPolygon(), QPainterPath::toFillPolygons(), QmlJSDebugger::LiveRubberBandSelectionManipulator::topFormEditorItem(), QBBScreen::topMostChildWindow(), QDeclarativeTransitionManager::transition(), QDeclarativePropertyAction::transition(), QDeclarativePropertyAnimation::transition(), QDeclarativeDataBlob::tryDone(), QThreadPoolPrivate::tryStart(), QThreadPoolPrivate::tryToStartMoreThreads(), QPatternist::Expression::typeCheckOperands(), QLocale::uiLanguages(), QGraphicsScenePrivate::ungrabKeyboard(), QGraphicsScenePrivate::ungrabMouse(), QDockAreaLayoutInfo::unplug(), QDockAreaLayout::unplug(), QMainWindowLayout::unplug(), QUnifiedTimer::unregisterAnimation(), QPSQLDriver::unsubscribeFromNotificationImplementation(), QMdiAreaPrivate::updateActiveWindow(), QNlaThread::updateConfigurations(), QFactoryLoader::updateDir(), QMainWindowLayout::updateGapIndicator(), QFontDialogPrivate::updateSizes(), QDeclarativeInspectorService::updateStatus(), QFontDialogPrivate::updateStyles(), Maemo::variantToSignature(), variantToString(), QTableView::visualRegionForSelection(), QTreeView::visualRegionForSelection(), QUnixSocket::waitForBytesWritten(), QThreadPoolPrivate::waitForDone(), QLocalServerPrivate::waitForNewConnection(), QPacketProtocol::waitForReadyRead(), QWaylandDisplay::waitForScreens(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), QGraphicsScene::wheelEvent(), QApplication::winFocus(), QHostInfoLookupManager::work(), writingSystemForFont(), QApplicationPrivate::x11_apply_settings(), QApplication::x11EventFilter(), x11EventSourceCheck(), x11EventSourceDispatch(), x11EventSourcePrepare(), QPatternist::yyparse(), QAbstractFileEngineHandler::~QAbstractFileEngineHandler(), QCoreWlanEngine::~QCoreWlanEngine(), QDeclarativeDataBlob::~QDeclarativeDataBlob(), QGraphicsItem::~QGraphicsItem(), QIconLoaderEngine::~QIconLoaderEngine(), QObject::~QObject(), QScriptEnginePrivate::~QScriptEnginePrivate(), QToolBarLayout::~QToolBarLayout(), QTreeWidgetItem::~QTreeWidgetItem(), QWindowsFileSystemWatcherEngine::~QWindowsFileSystemWatcherEngine(), and QWSWindow::~QWSWindow().
 { return p.isEmpty(); }
isSharedWith()
template<typename T> bool QList< T >::isSharedWith (const QList< T > & other) const inline
Warning
This function is not part of the public interface.
Definition at line 150 of file qlist.h.
 { return d == other.d; }
last() [1/2]
template<typename T> T & QList< T >::last () inline
Returns a reference to the last item in the list.
The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
See also
first(), isEmpty()
Definition at line 284 of file qlist.h.
Referenced by QApplication::activePopupWidget(), QDeclarativeXmlQueryEngine::addIndexToRangeList(), QStateMachinePrivate::applyProperties(), QSequentialAnimationGroupPrivate::atEnd(), QGLWindowSurface::buffer(), QColumnViewPrivate::closeColumns(), QApplicationPrivate::closePopup(), QDateTimeEditPrivate::closestSection(), QScriptCompletionTaskPrivate::completeScriptExpression(), QPatternist::NormalizeUnicodeFN::compress(), QDeclarativeEngineDebugPrivate::decode(), QPatternist::NormalizeUnicodeFN::determineNormalizationForm(), QDeclarativeXmlQueryEngine::doQuery(), QPatternist::RemoveFN::evaluateSequence(), QPatternist::SubsequenceFN::evaluateSequence(), QPatternist::ResolveURIFN::evaluateSingleton(), QPatternist::DateTimeFN::evaluateSingleton(), QPatternist::CodepointEqualFN::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::ResolveQNameFN::evaluateSingleton(), QPatternist::NamespaceURIForPrefixFN::evaluateSingleton(), QPatternist::SumFN::evaluateSingleton(), QPatternist::RemoveFN::evaluateSingleton(), QDockWidget::event(), QScriptDebuggerCommandExecutor::execute(), QGLEngineSharedShaders::findProgramInCache(), QDockAreaLayout::gapRect(), QGraphicsScenePrivate::grabKeyboard(), QGraphicsScenePrivate::grabMouse(), QDeclarativePropertyPrivate::initProperty(), QToolBarAreaLayoutInfo::insertItem(), QToolBarAreaLayout::insertItem(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QDeclarativeVisualItemModelPrivate::itemAppended(), Node::lastChild(), QGraphicsItemAnimationPrivate::linearValueForStep(), FAREnforcer::logAuthAttempt(), longestCommonPrefix(), QWaylandClipboard::mimeData(), QGraphicsScenePrivate::mousePressEventHandler(), QDBusConnection::objectRegisteredAt(), QHttpHeader::parse(), parseServerList(), QHostAddress::parseSubnet(), QUndoStack::push(), qt_try_modal(), QDBusConnection::registerObject(), QDockAreaLayoutInfo::restoreState(), QDateTimeEditPrivate::sectionAt(), QGraphicsScenePrivate::sendMouseEvent(), QDockAreaLayout::separatorMove(), ModelNode::setObjectValue(), QPatternist::PairContainer::setOperands(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), sm_setProperty(), QDockAreaLayout::splitDockWidget(), QFSCompleter::splitPath(), QPatternist::InsertBeforeFN::staticType(), QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber(), QDockAreaLayout::tabifyDockWidget(), QBBScreen::topMostChildWindow(), QPatternist::FunctionCall::typeCheck(), QPatternist::Expression::typeCheckOperands(), QGraphicsScenePrivate::ungrabKeyboard(), QGraphicsScenePrivate::ungrabMouse(), QGtkStyleUpdateScheduler::updateTheme(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), and writingSystemForFont().
 { Q_ASSERT(!isEmpty()); return *(--end()); }
last() [2/2]
template<typename T> const T & QList< T >::last () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 285 of file qlist.h.
 { Q_ASSERT(!isEmpty()); return at(count() - 1); }
lastIndexOf()
template<typename T> Q_OUTOFLINE_TEMPLATE int QList< T >::lastIndexOf (const T & value, int from = -1) const
Returns the index position of the last occurrence of value in the list, searching backward from index position from.
If from is -1 (the default), the search starts at the last item. Returns -1 if no item matched.
Example:
QList<QString> list;
list << "A" << "B" << "C" << "B" << "A";
list.lastIndexOf("B");      // returns 3
list.lastIndexOf("B", 3);   // returns 3
list.lastIndexOf("B", 2);   // returns 1
list.lastIndexOf("X");      // returns -1
This function requires the value type to have an implementation of operator==().
Note that QList uses 0-based indexes, just like C++ arrays. Negative indexes are not supported with the exception of the value mentioned above.
See also
indexOf()
Definition at line 862 of file qlist.h.
Referenced by QTreeModel::index(), QListModel::index(), QStringList::operator<<(), QRuntimeGraphicsSystem::removePixmapData(), QRuntimeGraphicsSystem::removeWindowSurface(), and QGraphicsScenePrivate::ungrabKeyboard().
 {
     if (from < 0)
         from += p.size();
     else if (from >= p.size())
         from = p.size()-1;
     if (from >= 0) {
         Node *b = reinterpret_cast<Node *>(p.begin());
         Node *n = reinterpret_cast<Node *>(p.at(from + 1));
         while (n-- != b) {
             if (n->t() == t)
                 return n - b;
         }
     }
     return -1;
 }
length()
template<typename T> int QList< T >::length () const inline
This function is identical to count().
Since
4.5
See also
count()
Definition at line 281 of file qlist.h.
Referenced by QHostInfoLookupManager::abortLookup(), QSyntaxHighlighterPrivate::applyFormatChanges(), QByteDataBuffer::bufferCount(), QByteDataBuffer::canReadLine(), QDeclarativeCompiler::completeComponentBuild(), QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected(), QNetworkCookieJar::cookiesForUrl(), QDeclarativeEnginePrivate::createQmlObject(), QFbScreen::doRedraw(), QFbScreen::generateRects(), QHttpNetworkRequestPrivate::header(), QmlJSDebugger::ZoomTool::nextZoomScale(), qt_win_get_save_file_name(), QVFbIntegration::QVFbIntegration(), QRingBuffer< T >::readPointerAtPosition(), QDeclarativeCompiler::rewriteBinding(), QmlJSDebugger::AbstractViewInspector::sendCurrentObjects(), sm_setProperty(), QDesktopWidgetPrivate::updateScreenList(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), and QHostInfoLookupManager::work().
 { return p.size(); } // Same as count()
mid()
template<typename T > Q_OUTOFLINE_TEMPLATE QList< T > QList< T >::mid (int pos, int length = -1) const
Returns a list whose elements are copied from this list, starting at position pos.
If length is -1 (the default), all elements from pos are copied; otherwise length elements (or all remaining elements if there are less than length elements) are copied.
Definition at line 637 of file qlist.h.
Referenced by QScriptDebuggerLocalsModel::data(), QMainWindowLayoutState::gapRect(), QScriptToolTipJob::handleResponse(), QDockAreaLayoutInfo::info(), QDockAreaLayout::info(), QDockAreaLayoutInfo::insertGap(), QMainWindowLayoutState::insertGap(), QToolBarAreaLayout::insertGap(), QDockAreaLayout::insertGap(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QMainWindowLayoutState::item(), QDockAreaLayoutInfo::item(), QDockAreaLayout::item(), QMainWindowLayoutState::itemRect(), QDockAreaLayoutInfo::itemRect(), QToolBarAreaLayout::itemRect(), QDockAreaLayout::itemRect(), QScriptScriptData::lines(), QDockAreaLayoutInfo::plug(), QMainWindowLayoutState::plug(), QDockAreaLayout::plug(), qExtractSecurityPolicyFromString(), QDockAreaLayoutInfo::remove(), QMainWindowLayoutState::remove(), QDockAreaLayout::remove(), QDockAreaLayoutInfo::separatorRect(), QDockAreaLayout::separatorRect(), QDockAreaLayoutInfo::unplug(), QMainWindowLayoutState::unplug(), and QDockAreaLayout::unplug().
 {
     if (alength < 0 || pos + alength > size())
         alength = size() - pos;
     if (pos == 0 && alength == size())
         return *this;
     QList<T> cpy;
     if (alength <= 0)
         return cpy;
     cpy.reserve(alength);
     cpy.d->end = alength;
     QT_TRY {
         cpy.node_copy(reinterpret_cast<Node *>(cpy.p.begin()),
                       reinterpret_cast<Node *>(cpy.p.end()),
                       reinterpret_cast<Node *>(p.begin() + pos));
     } QT_CATCH(...) {
         // restore the old end
         cpy.d->end = 0;
         QT_RETHROW;
     }
     return cpy;
 }
move()
template<typename T > void QList< T >::move (int from, int to) inline
Moves the item at index position from to index position to.
Example:
QList<QString> list;
list << "A" << "B" << "C" << "D" << "E" << "F";
list.move(1, 4);
// list: ["A", "C", "D", "E", "B", "F"]
This is the same as insert({to}, takeAt({from})).This function assumes that both from and to are at least 0 but less than size(). To avoid failure, test that both from and to are at least 0 and less than size().
See also
swap(), insert(), takeAt()
Definition at line 628 of file qlist.h.
Referenced by QMdiAreaPrivate::_q_moveTab(), QMdiAreaPrivate::emitWindowActivated(), QGLEngineSharedShaders::findProgramInCache(), imageReadMimeFormats(), imageWriteMimeFormats(), QFbScreen::lower(), QWidget::lower(), QListModel::move(), QFbScreen::raise(), QWidget::raise(), QMdiAreaPrivate::rearrange(), QGraphicsItem::stackBefore(), and QWidget::stackUnder().
 {
     Q_ASSERT_X(from >= 0 && from < p.size() && to >= 0 && to < p.size(),
                "QList<T>::move", "index out of range");
     detach();
     p.move(from, to);
 }
node_construct()
template<typename T> Q_INLINE_TEMPLATE void QList< T >::node_construct (Node * n, const T & t) private
Definition at line 370 of file qlist.h.
 {
     if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) n->v = new T(t);
     else if (QTypeInfo<T>::isComplex) new (n) T(t);
 #if (defined(__GNUC__) || defined(__INTEL_COMPILER) || defined(__IBMCPP__)) && !defined(__OPTIMIZE__)
     // This violates pointer aliasing rules, but it is known to be safe (and silent)
     // in unoptimized GCC builds (-fno-strict-aliasing). The other compilers which
     // set the same define are assumed to be safe.
     else *reinterpret_cast<T*>(n) = t;
 #else
     // This is always safe, but penaltizes unoptimized builds a lot.
     else ::memcpy(n, &t, sizeof(T));
 #endif
 }
node_copy()
template<typename T > Q_INLINE_TEMPLATE void QList< T >::node_copy (Node * from, Node * to, Node * src) private
Definition at line 393 of file qlist.h.
Referenced by QList< QPostEvent >::mid().
 {
     Node *current = from;
     if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) {
         QT_TRY {
             while(current != to) {
                 current->v = new T(*reinterpret_cast<T*>(src->v));
                 ++current;
                 ++src;
             }
         } QT_CATCH(...) {
             while (current-- != from)
                 delete reinterpret_cast<T*>(current->v);
             QT_RETHROW;
         }
     } else if (QTypeInfo<T>::isComplex) {
         QT_TRY {
             while(current != to) {
                 new (current) T(*reinterpret_cast<T*>(src));
                 ++current;
                 ++src;
             }
         } QT_CATCH(...) {
             while (current-- != from)
                 (reinterpret_cast<T*>(current))->~T();
             QT_RETHROW;
         }
     } else {
         if (src != from && to - from > 0)
             memcpy(from, src, (to - from) * sizeof(Node *));
     }
 }
node_destruct() [1/2]
template<typename T > Q_INLINE_TEMPLATE void QList< T >::node_destruct (Node * n) private
Definition at line 386 of file qlist.h.
 {
     if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) delete reinterpret_cast<T*>(n->v);
     else if (QTypeInfo<T>::isComplex) reinterpret_cast<T*>(n)->~T();
 }
node_destruct() [2/2]
template<typename T > Q_INLINE_TEMPLATE void QList< T >::node_destruct (Node * from, Node * to) private
Definition at line 428 of file qlist.h.
 {
     if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic)
         while(from != to) --to, delete reinterpret_cast<T*>(to->v);
     else if (QTypeInfo<T>::isComplex)
         while (from != to) --to, reinterpret_cast<T*>(to)->~T();
 }
operator!=()
template<typename T> bool QList< T >::operator!= (const QList< T > & other) const inline
Returns true if other is not equal to this list; otherwise returns false.
Two lists are considered equal if they contain the same values in the same order.
This function requires the value type to have an implementation of operator==().
See also
operator==()
Definition at line 135 of file qlist.h.
 { return !(*this == l); }
operator+()
template<typename T> QList< T > QList< T >::operator+ (const QList< T > & other) const inline
Returns a list that contains all the items in this list followed by all the items in the other list.
See also
operator+=()
Definition at line 329 of file qlist.h.
     { QList n = *this; n += l; return n; }
operator+=() [1/2]
template<typename T> Q_OUTOFLINE_TEMPLATE QList< T > & QList< T >::operator+= (const QList< T > & other)
Appends the items of the other list to this list and returns a reference to this list.
See also
operator+(), append()
Definition at line 818 of file qlist.h.
 {
     if (!l.isEmpty()) {
         if (isEmpty()) {
             *this = l;
         } else {
             Node *n = (d->ref != 1)
                       ? detach_helper_grow(INT_MAX, l.size())
                       : reinterpret_cast<Node *>(p.append2(l.p));
             QT_TRY {
                 node_copy(n, reinterpret_cast<Node *>(p.end()),
                           reinterpret_cast<Node *>(l.p.begin()));
             } QT_CATCH(...) {
                 // restore the old end
                 d->end -= int(reinterpret_cast<Node *>(p.end()) - n);
                 QT_RETHROW;
             }
         }
     }
     return *this;
 }
operator+=() [2/2]
template<typename T> void QList< T >::operator+= (const T & value) inline
Appends value to the list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
append(), operator<<()
Definition at line 331 of file qlist.h.
     { append(t); return *this; }
operator<<() [1/2]
template<typename T> QList< T > & QList< T >::operator<< (const QList< T > & other) inline
Appends the items of the other list to this list and returns a reference to this list.
See also
operator+=(), append()
Definition at line 335 of file qlist.h.
     { *this += l; return *this; }
operator<<() [2/2]
template<typename T> void QList< T >::operator<< (const T & value) inline
Appends value to the list.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 333 of file qlist.h.
Referenced by QItemSelection::QItemSelection().
     { append(t); return *this; }
operator=()
template<typename T> Q_INLINE_TEMPLATE QList< T > & QList< T >::operator= (const QList< T > & l)
Assigns other to this list and returns a reference to this list.
Definition at line 437 of file qlist.h.
 {
     if (d != l.d) {
         QListData::Data *o = l.d;
         o->ref.ref();
         if (!d->ref.deref())
             free(d);
         d = o;
         if (!d->sharable)
             detach_helper();
     }
     return *this;
 }
operator==()
template<typename T> Q_OUTOFLINE_TEMPLATE bool QList< T >::operator== (const QList< T > & other) const
Returns true if other is equal to this list; otherwise returns false.
Two lists are considered equal if they contain the same values in the same order.
This function requires the value type to have an implementation of operator==().
See also
operator!=()
Definition at line 736 of file qlist.h.
 {
     if (p.size() != l.p.size())
         return false;
     if (d == l.d)
         return true;
     Node *i = reinterpret_cast<Node *>(p.end());
     Node *b = reinterpret_cast<Node *>(p.begin());
     Node *li = reinterpret_cast<Node *>(l.p.end());
     while (i != b) {
         --i; --li;
         if (!(i->t() == li->t()))
             return false;
     }
     return true;
 }
operator[]() [1/2]
template<typename T > const T & QList< T >::operator[] (int i) const inline
Same as at().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 472 of file qlist.h.
 { Q_ASSERT_X(i >= 0 && i < p.size(), "QList<T>::operator[]", "index out of range");
  return reinterpret_cast<Node *>(p.at(i))->t(); }
operator[]() [2/2]
template<typename T > T & QList< T >::operator[] (int i) inline
Returns the item at index position i as a modifiable reference.
i must be a valid index position in the list (i.e., 0 <= i < size()).
This function is very fast (constant time).
See also
at(), value()
Definition at line 476 of file qlist.h.
 { Q_ASSERT_X(i >= 0 && i < p.size(), "QList<T>::operator[]", "index out of range");
   detach(); return reinterpret_cast<Node *>(p.at(i))->t(); }
pop_back()
template<typename T> void QList< T >::pop_back () inline
This function is provided for STL compatibility.
It is equivalent to removeLast(). The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
Definition at line 303 of file qlist.h.
 { removeLast(); }
pop_front()
template<typename T> void QList< T >::pop_front () inline
This function is provided for STL compatibility.
It is equivalent to removeFirst(). The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
Definition at line 302 of file qlist.h.
Referenced by QDirModel::index(), QFileSystemModelPrivate::node(), QFtpPI::processReply(), QFileDialog::restoreState(), and QFtpPI::startNextCmd().
 { removeFirst(); }
prepend()
template<typename T> void QList< T >::prepend (const T & value) inline
Inserts value at the beginning of the list.
Example:
QList<QString> list;
list.prepend("one");
list.prepend("two");
list.prepend("three");
// list: ["three", "two", "one"]
This is the same as list.insert(0, value).
This operation is usually very fast (constant time), because QList preallocates extra space on both sides of its internal buffer to allow for fast growth at both ends of the list.
See also
append(), insert()
Definition at line 541 of file qlist.h.
Referenced by QAccessibleObjectPrivate::actionList(), QDeclarativeImportsPrivate::add(), QDeclarativeImportDatabase::addImportPath(), QWSServer::addKeyboardFilter(), QDeclarativeImportDatabase::addPluginPath(), QFbScreen::addWindow(), QTextCursorPrivate::adjustCursor(), allCombinations(), QMdiAreaPrivate::appendChild(), QDBusAbstractInterface::asyncCall(), QDBusAbstractInterface::call(), QScriptCompletionTaskPrivate::completeScriptExpression(), QGraphicsItem::deviceTransform(), QApplicationPrivate::dispatchEnterLeave(), QGraphicsScenePrivate::dispatchHoverEvent(), QDeclarativeTypeData::done(), QStateMachinePrivate::enterStates(), QScriptDebuggerCodeView::event(), QStateMachinePrivate::exitStates(), QIconLoader::findIconHelper(), QDockAreaLayoutInfo::findSeparator(), QDockAreaLayout::findSeparator(), findSnapshotIdsRecursively(), QHostInfoAgent::fromName(), QDockAreaLayoutInfo::gapIndex(), QMainWindowLayoutState::gapIndex(), QToolBarAreaLayout::gapIndex(), QDockAreaLayout::gapIndex(), QJSDebuggerAgentPrivate::getLocals(), QGuiPlatformPlugin::iconThemeSearchPaths(), QDirModel::index(), QMainWindowLayoutState::indexOf(), QDockAreaLayoutInfo::indexOf(), QToolBarAreaLayout::indexOf(), QDockAreaLayout::indexOf(), QDockAreaLayoutInfo::indexOfPlaceHolder(), QDockAreaLayout::indexOfPlaceHolder(), QObject::installEventFilter(), QCoreApplication::installTranslator(), QStateMachinePrivate::isPreempted(), QKeySequence::keyBindings(), QScreenDriverFactory::keys(), QLibraryPrivate::load_sys(), QFileSystemModelPrivate::node(), QDeclarativeDirParser::parse(), parseServerList(), QCompleter::pathFromIndex(), QByteDataBuffer::prepend(), QGraphicsItemPrivate::prependGraphicsTransform(), QFtpPI::processReply(), QAuServer::QAuServer(), QByteDataBuffer::read(), registerComponent(), QAxScriptManager::registerEngine(), QFileSystemModel::remove(), QDeclarativeImportDatabase::resolvePlugin(), QStateMachinePrivate::selectTransitions(), QWSServer::setKeyboardHandler(), QWSServer::setMouseHandler(), QFileDialogComboBox::showPopup(), QMdiAreaPrivate::subWindowList(), QWidgetBackingStore::sync(), QStandardItem::takeColumn(), QAbstractXmlForwardIterator< OutputType >::toReversed(), QRingBuffer< T >::ungetChar(), QGraphicsSceneInsertItemBspTreeVisitor::visit(), QGraphicsSceneFindItemBspTreeVisitor::visit(), QHostInfoLookupManager::work(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     if (d->ref != 1) {
         Node *n = detach_helper_grow(0, 1);
         QT_TRY {
             node_construct(n, t);
         } QT_CATCH(...) {
             ++d->begin;
             QT_RETHROW;
         }
     } else {
         if (QTypeInfo<T>::isLarge || QTypeInfo<T>::isStatic) {
             Node *n = reinterpret_cast<Node *>(p.prepend());
             QT_TRY {
                 node_construct(n, t);
             } QT_CATCH(...) {
                 ++d->begin;
                 QT_RETHROW;
             }
         } else {
             Node *n, copy;
             node_construct(&copy, t); // t might be a reference to an object in the array
             QT_TRY {
                 n = reinterpret_cast<Node *>(p.prepend());;
             } QT_CATCH(...) {
                 node_destruct(&copy);
                 QT_RETHROW;
             }
             *n = copy;
         }
     }
 }
push_back()
template<typename T> void QList< T >::push_back (const T & value) inline
This function is provided for STL compatibility.
It is equivalent to append(value).
Definition at line 296 of file qlist.h.
Referenced by QBBScreen::addWindow(), operator>>(), qstring_to_xtp(), QBBWindow::raise(), QBBScreen::raiseWindow(), QBBInputContext::setComposingText(), QBBWindow::setParent(), QPixmapIconEngine::virtual_hook(), and QApplication::winFocus().
 { append(t); }
push_front()
template<typename T> void QList< T >::push_front (const T & value) inline
This function is provided for STL compatibility.
It is equivalent to prepend(value).
Definition at line 297 of file qlist.h.
Referenced by QBBScreen::addWindow(), QBBWindow::lower(), and QBBScreen::lowerWindow().
 { prepend(t); }
removeAll()
template<typename T> Q_OUTOFLINE_TEMPLATE int QList< T >::removeAll (const T & value)
Removes all occurrences of value in the list and returns the number of entries removed.
Example:
QList<QString> list;
list << "sun" << "cloud" << "sun" << "rain";
list.removeAll("sun");
// list: ["cloud", "rain"]
This function requires the value type to have an implementation of operator==().
See also
removeOne(), removeAt(), takeAt(), replace()
Definition at line 770 of file qlist.h.
Referenced by QFileDialogPrivate::_q_autoCompleteFileName(), QFileSystemWatcherPrivate::_q_directoryChanged(), QFileSystemWatcherPrivate::_q_fileChanged(), QWidgetActionPrivate::_q_widgetDestroyed(), QApplicationPrivate::closePopup(), QGenericEngine::doRequestUpdate(), QMacStylePrivate::eventFilter(), QObject::installEventFilter(), QApplicationPrivate::leaveModal_sys(), QBBWindow::lower(), QAudioDeviceInfo::nearestFormat(), QCoreWlanEngine::networksChanged(), QNlaEngine::networksChanged(), QHttpHeader::parse(), QPatternist::XsdSchemaParser::parseRedefine(), qRemovePostRoutine(), qt_grab_cursor(), qt_try_modal(), QtWndProc(), QApplication::qwsSetCustomColors(), QBBWindow::raise(), QDeclarativeEngineDebugService::remEngine(), QItemSelectionModelPrivate::remove(), QGraphicsWidget::removeAction(), QMenuBarPrivate::QMacMenuBarPrivate::removeAction(), QMenuBarPrivate::QWceMenuBarPrivate::removeAction(), QMenuPrivate::QMacMenuPrivate::removeAction(), QMenuPrivate::QWceMenuPrivate::removeAction(), QWidget::removeAction(), QNetworkManagerEngine::removeConnection(), QBBIntegration::removeDisplay(), QJSDebugService::removeEngine(), QBBWindow::removeFromParent(), QImagePixmapCleanupHooks::removeImageHook(), QGraphicsScenePrivate::removeItemHelper(), QBBScreen::removeOverlayWindow(), QInotifyFileSystemWatcherEngine::removePaths(), QKqueueFileSystemWatcherEngine::removePaths(), QDnotifyFileSystemWatcherEngine::removePaths(), QWindowsFileSystemWatcherEngine::removePaths(), QFSEventsFileSystemWatcherEngine::removePaths(), QPollingFileSystemWatcherEngine::removePaths(), QImagePixmapCleanupHooks::removePixmapDataDestructionHook(), QImagePixmapCleanupHooks::removePixmapDataModificationHook(), QWidgetBackingStore::removeStaticWidget(), QMultiScreen::removeSubScreen(), QCoreApplication::removeTranslator(), QDeclarativeInspectorService::removeView(), QGraphicsScenePrivate::removeView(), QBBScreen::removeWindow(), QWindowsMimeList::removeWindowsMime(), QNativeWifiEngine::scanComplete(), QmlJSDebugger::LiveSingleSelectionManipulator::select(), QGraphicsTransformPrivate::setItem(), QWSServer::setKeyboardHandler(), QWSServer::setMouseHandler(), QMacStylePrivate::stopAnimate(), QWindowsStylePrivate::stopAnimation(), QWSWindow::stopEmbed(), QOCIDriver::tables(), QDBusConnectionPrivate::unregisterServiceNoLock(), QPSQLDriver::unsubscribeFromNotificationImplementation(), QGraphicsSceneRemoveItemBspTreeVisitor::visit(), QHostInfoLookupManager::work(), writingSystemForFont(), QApplication::x11EventFilter(), QAuServer::~QAuServer(), QGraphicsWidget::~QGraphicsWidget(), QWidget::~QWidget(), and QWSWindow::~QWSWindow().
 {
     int index = indexOf(_t);
     if (index == -1)
         return 0;
     const T t = _t;
     detach();
     Node *i = reinterpret_cast<Node *>(p.at(index));
     Node *e = reinterpret_cast<Node *>(p.end());
     Node *n = i;
     node_destruct(i);
     while (++i != e) {
         if (i->t() == t)
             node_destruct(i);
         else
             *n++ = *i;
     }
     int removedCount = e - n;
     d->end -= removedCount;
     return removedCount;
 }
removeAt()
template<typename T > void QList< T >::removeAt (int i) inline
Removes the item at index position i.
i must be a valid index position in the list (i.e., 0 <= i < size()).
See also
takeAt(), removeFirst(), removeLast(), removeOne()
Definition at line 480 of file qlist.h.
Referenced by QDeclarativeEngineDebugService::buildObjectList(), QRingBuffer< T >::chop(), QGLEngineSharedShaders::cleanupCustomStage(), QVNCScreen::connect(), QScriptDebuggerAgent::deleteBreakpoint(), QGLWindowSurface::deleted(), QFutureInterfaceBasePrivate::disconnectOutputInterface(), QIcdEngine::doRequestUpdate(), QItemSelectionModel::emitSelectionChanged(), QWindowsStyle::eventFilter(), QRingBuffer< T >::free(), handleRowsAttribute(), handleVisibleRowsAttribute(), QTextDocumentPrivate::insert_frame(), markFrames(), QItemSelection::merge(), QWidgetBackingStore::moveStaticWidgets(), QApplication::notify(), QPatternist::XsdSchemaParser::parseRedefine(), qExtractSecurityPolicyFromString(), QDeclarativeMetaType::qmlComponents(), QMultiInputContext::QMultiInputContext(), qt_painter_removePaintDevice(), QMainWindowLayout::qtmacToolbarDelegate(), QAbstractButtonPrivate::queryButtonList(), QWSPcMouseHandlerPrivate::QWSPcMouseHandlerPrivate(), QWSTslibMouseHandlerPrivate::QWSTslibMouseHandlerPrivate(), QObjectCleanupHandler::remove(), FlatListModel::remove(), QListModel::remove(), QDeclarativeTimeLine::remove(), QDockAreaLayoutInfo::remove(), NestedListModel::remove(), QToolBarAreaLayout::remove(), QTextFramePrivate::remove_me(), QGraphicsItemPrivate::removeChild(), removeInvisibleWidgetsFromList(), QMetaEnumBuilder::removeKey(), QFileSystemModelPrivate::removeNode(), QRuntimeGraphicsSystem::removePixmapData(), QStringListModel::removeRows(), QToolBarAreaLayoutInfo::removeToolBar(), QToolBarAreaLayoutInfo::removeToolBarBreak(), QFileSystemModelPrivate::removeVisibleFile(), QRuntimeGraphicsSystem::removeWindowSurface(), QPainter::restoreRedirected(), QAbstractItemViewPrivate::selectedDraggableIndexes(), QListView::selectedIndexes(), QItemSelectionModel::selection(), QFileSystemModel::setData(), QObjectPrivate::setParent_helper(), QVideoSurfaceFormat::setProperty(), QObject::setProperty(), QToolBarAreaLayout::takeAt(), QMacStylePrivate::timerEvent(), QDeclarativeTransitionManager::transition(), QAxServerBase::Unadvise(), QDockAreaLayoutInfo::unnest(), QUnifiedTimer::unregisterAnimation(), QGraphicsScenePrivate::unregisterTopLevelItem(), QMenuBarPrivate::wceDestroyMenuBar(), and QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate().
 { if(i >= 0 && i < p.size()) { detach();
  node_destruct(reinterpret_cast<Node *>(p.at(i))); p.remove(i); } }
removeFirst()
template<typename T> void QList< T >::removeFirst () inline
Removes the first item in the list.
Calling this function is equivalent to calling removeAt(0). The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
See also
removeAt(), takeFirst()
Definition at line 286 of file qlist.h.
Referenced by QPacketProtocolPrivate::bytesWritten(), QHttpPrivate::finishedWithSuccess(), QDBusUtil::isValidObjectPath(), QDialogButtonBoxPrivate::layoutButtons(), QPacketProtocol::read(), QRingBuffer< T >::read(), QHeaderViewPrivate::resizeSections(), QFSCompleter::splitPath(), QProcess::start(), QProcess::startDetached(), QThreadPoolPrivate::tryToStartMoreThreads(), and QFactoryLoader::updateDir().
 { Q_ASSERT(!isEmpty()); erase(begin()); }
removeLast()
template<typename T> void QList< T >::removeLast () inline
Removes the last item in the list.
Calling this function is equivalent to calling removeAt(size() - 1). The list must not be empty. If the list can be empty, call isEmpty() before calling this function.
See also
removeAt(), takeLast()
Definition at line 287 of file qlist.h.
Referenced by QFileDialogPrivate::_q_pathChanged(), QPatternist::NormalizeUnicodeFN::compress(), QGLEngineSharedShaders::findProgramInCache(), QScriptDebuggerAgent::functionExit(), QDBusConnection::objectRegisteredAt(), QHostAddress::parseSubnet(), QDBusConnection::registerObject(), and QFSCompleter::splitPath().
 { Q_ASSERT(!isEmpty()); erase(--end()); }
removeOne()
template<typename T> Q_OUTOFLINE_TEMPLATE bool QList< T >::removeOne (const T & value)
Removes the first occurrence of value in the list and returns true on success; otherwise returns false.
Since
4.4
Example:
QList<QString> list;
list << "sun" << "cloud" << "sun" << "rain";
list.removeOne("sun");
// list: ["cloud", ,"sun", "rain"]
This function requires the value type to have an implementation of operator==().
See also
removeAll(), removeAt(), takeAt(), replace()
Definition at line 796 of file qlist.h.
Referenced by QmlJSDebugger::QDeclarativeViewInspectorPrivate::_q_removeFromSelection(), QGLFramebufferObjectPool::acquire(), QScriptEnginePrivate::agentDeleted(), QIcdEngine::asyncUpdateConfigurationsSlot(), QDeclarativeDataBlob::cancelAllWaitingFor(), QIcdEngine::doRequestUpdate(), QmlJSDebugger::QDeclarativeViewInspectorPrivate::filterForSelection(), QNetworkManagerEngine::interfacePropertiesChanged(), QHostInfoLookupManager::lookupFinished(), QDeclarativeDataBlob::notifyComplete(), QDeclarativePackagePrivate::DataGuard::objectDestroyed(), QDeclarativeStatePrivate::OperationGuard::objectDestroyed(), Maemo::pendingCallFunction(), QNetworkAccessHttpBackend::postRequest(), QNetworkManagerEngine::removeAccessPoint(), QGraphicsItemPrivate::removeChild(), QConnmanEngine::removeConfiguration(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), QFbScreen::removeWindow(), QThreadPoolThread::run(), QGraphicsItem::setFocusProxy(), QUnifiedTimer::unregisterAnimation(), QUnifiedTimer::unregisterRunningAnimation(), QWaylandClipboard::unregisterSelection(), QGraphicsScenePrivate::unregisterTopLevelItem(), QAbstractFileEngineHandler::~QAbstractFileEngineHandler(), QGtkStylePrivate::~QGtkStylePrivate(), and QSQLiteResult::~QSQLiteResult().
 {
     int index = indexOf(_t);
     if (index != -1) {
         removeAt(index);
         return true;
     }
     return false;
 }
replace()
template<typename T> void QList< T >::replace (int i, const T & value) inline
Replaces the item at index position i with value.
i must be a valid index position in the list (i.e., 0 <= i < size()).
See also
operator[](), removeAt()
Definition at line 609 of file qlist.h.
Referenced by QFileDialogPrivate::_q_selectionChanged(), QMultiInputContext::changeSlave(), FlatListModel::get(), QStandardItemPrivate::insertColumns(), QStandardItemPrivate::insertRows(), QMultiInputContext::QMultiInputContext(), QStringListModel::setData(), QTreeModel::sortItems(), QPatternist::AddingAggregate::typeCheck(), and QPatternist::AvgFN::typeCheck().
 {
     Q_ASSERT_X(i >= 0 && i < p.size(), "QList<T>::replace", "index out of range");
     detach();
     reinterpret_cast<Node *>(p.at(i))->t() = t;
 }
reserve()
template<typename T > Q_OUTOFLINE_TEMPLATE void QList< T >::reserve (int alloc)
Reserve space for alloc elements.
If alloc is smaller than the current size of the list, nothing will happen.
Use this function to avoid repetetive reallocation of QList's internal data if you can predict how many elements will be appended. Note that the reservation applies only to the internal pointer array.
Since
4.7
Definition at line 496 of file qlist.h.
Referenced by QDeclarativeListModel::flatten(), QProcessEnvironmentPrivate::keys(), QMap< int, QFrameInfo >::keys(), QHash< QExplicitlySharedDataPointer, QHash >::keys(), macQuoteString(), QLocale::matchingLocales(), QList< QPostEvent >::mid(), operator>>(), QDeclarativeListModel::QDeclarativeListModel(), QTreeWidget::selectedItems(), QProcessEnvironmentPrivate::toList(), QSet< typename TokenLookupClass::NodeName >::toList(), QVector< QPoint >::toList(), QSystemLocalePrivate::uiLanguages(), QMap< int, QFrameInfo >::uniqueKeys(), QHash< QExplicitlySharedDataPointer, QHash >::uniqueKeys(), QMap< int, QFrameInfo >::values(), and QHash< QExplicitlySharedDataPointer, QHash >::values().
 {
     if (d->alloc < alloc) {
         if (d->ref != 1)
             detach_helper(alloc);
         else
             p.realloc(alloc);
     }
 }
setSharable()
template<typename T> void QList< T >::setSharable (bool sharable) inline
Warning
This function is not part of the public interface.
Definition at line 149 of file qlist.h.
 { if (!sharable) detach(); d->sharable = sharable; }
size()
template<typename T> int QList< T >::size () const inline
Returns the number of items in the list.
See also
isEmpty(), count()
Definition at line 137 of file qlist.h.
Referenced by QMdiAreaPrivate::_q_currentTabChanged(), QFileSystemModelPrivate::_q_directoryChanged(), QGraphicsScenePrivate::_q_emitUpdated(), QFileDialogPrivate::_q_navigateForward(), QWSServerPrivate::_q_newConnection(), QProcessPrivate::_q_notified(), _q_parseDosDir(), _q_parseUnixDir(), QFileDialogPrivate::_q_pathChanged(), QGraphicsScenePrivate::_q_processDirtyItems(), QObjectPrivate::_q_reregisterTimers(), QGroupBoxPrivate::_q_setChildrenEnabled(), QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex(), QFontComboBoxPrivate::_q_updateModel(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QFileDialogPrivate::_q_useNameFilter(), QGLFramebufferObjectPool::acquire(), QMenuBarPrivate::actionAt(), QInternal::activateCallbacks(), QMenuPrivate::activateCausedStack(), QWidgetPrivate::activateChildLayoutsRecursively(), QMdiAreaPrivate::activateHighlightedWindow(), QMenuBarPrivate::QMacMenuBarPrivate::addAction(), QMenuBarPrivate::QWceMenuBarPrivate::addAction(), QMenuPrivate::QMacMenuPrivate::addAction(), QMenuPrivate::QWceMenuPrivate::addAction(), QGraphicsItemPrivate::addChild(), QScriptDebuggerLocalsModelPrivate::addChildren(), QFileDialogPrivate::addDefaultSuffixToFiles(), QFontSubset::addGlyph(), QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsScene::addItem(), QMetaEnumBuilder::addKey(), QLocalServerPrivate::addListener(), QFSEventsFileSystemWatcherEngine::addPaths(), QGraphicsScenePrivate::addPopup(), QTextEngine::addRequiredBoundaries(), QStateMachinePrivate::addStatesToEnter(), QGraphicsItemGroup::addToGroup(), QPrinterPrivate::addToManualSetList(), QScriptDebuggerLocalsModelPrivate::addTopLevelObject(), QState::addTransition(), QTextCursorPrivate::adjustCursor(), QDialog::adjustPosition(), QSequentialAnimationGroupPrivate::advanceForwards(), QApplication::alert(), QWindowsMime::allFormatsForMime(), allKeys(), QWindowsMime::allMimesForFormats(), QSequentialAnimationGroupPrivate::animationActualTotalDuration(), QCopChannel::answer(), QMdiAreaPrivate::appendChild(), Maemo::appendVariantToDBusMessage(), QDockAreaLayoutInfo::apply(), QStateMachinePrivate::applyProperties(), QScriptEnginePrivate::arrayFromStringList(), QScriptEnginePrivate::arrayFromVariantList(), QHttpNetworkReplyPrivate::authenticationMethod(), QTextCodec::availableCodecs(), QAudioDeviceInfoInternal::availableDevices(), QScriptEngine::availableExtensions(), QTextCodec::availableMibs(), QNetworkReplyImplPrivate::backendNotify(), bindFont(), QMultiScreen::blank(), QMultiScreen::blit(), buddyString(), buildMetaObject(), QDeclarativeEngineDebugService::buildObjectDump(), QGLGlyphCache::cacheGlyphs(), QPrintPreviewWidgetPrivate::calcCurrentPage(), QTextureGlyphCache::calculateSubPixelPositionCount(), QTextEngine::calculateTabWidth(), QScriptValue::call(), QScript::callQtMethod(), QGraphicsScenePrivate::cancelGesturesForChildren(), QWindowsMimeURI::canConvertFromMime(), QApplicationPrivate::canQuit(), QScriptObjectSnapshot::capture(), QSslCertificatePrivate::certificatesFromDer(), QSslCertificatePrivate::certificatesFromPem(), QKeyMapper::changeKeyboard(), QMultiInputContext::changeSlave(), QAccessibleWidget::childAt(), QAccessibleMainWindow::childAt(), QWidgetPrivate::childAtRecursiveHelper(), QAccessibleWidget::childCount(), childWidgets(), QGLGlyphCache::cleanCache(), QGLGlyphCache::cleanupContext(), QGLEngineSharedShaders::cleanupCustomStage(), QMenuBar::clear(), QToolBar::clear(), QMenu::clear(), QGraphicsSceneIndex::clear(), QPMCache::clear(), QResourcePrivate::clear(), QSimplex::clearDataStructures(), QStateMachinePrivate::clearHistory(), QAbstractItemViewPrivate::clearOrRemove(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QZipWriter::close(), QWidgetPrivate::close_helper(), QApplication::closeAllWindows(), QPdfBaseEnginePrivate::closePrintDevice(), QUnifiedTimer::closestPauseAnimationTimeToFinish(), QTextCodec::codecForName(), QSplitterPrivate::collapsible(), QSimplex::collectResults(), QApplication::commitData(), QScriptDebuggerConsoleCommandManager::completions(), QPatternist::ComparesCaseAware::compress(), QCoreApplication::compressEvent(), QGraphicsItemPrivate::TransformData::computedFullTransform(), QVFbScreen::connect(), QDirectFBScreen::connect(), QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints(), QScriptValue::construct(), convert(), QWindowsMime::converterFromMime(), QWindowsMime::converterToMime(), QWindowsMimeURI::convertFromMime(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), convertPath(), QWindowsMimeURI::convertToMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), QMacPasteboardMimeVCard::convertToMime(), convertToRelative(), QShortcutMap::correctContext(), QShortcutMap::correctGraphicsWidgetContext(), QXIMInputContext::create_xim(), createArrayBuffer(), QOleDropSource::createCursors(), QPatternist::createDirAttributeValue(), createForName(), QGraphicsScene::createItemGroup(), QScriptDebuggerConsolePrivate::createJob(), QMainWindow::createPopupMenu(), createReadHandlerHelper(), QWidgetPrivate::createRecursively(), QPatternist::createReturnOrderBy(), QLocale::createSeparatedList(), QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), QMultiScreen::createSurface(), QWidgetPrivate::createWinId(), QResourceFileEngineIterator::currentFileName(), QStringListModel::data(), QScriptDebuggerLocalsModel::data(), QDeclarativeXmlListModel::data(), QKeySequencePrivate::decodeString(), QMenuBar::defaultAction(), QAudioDeviceFactory::defaultInputDevice(), QAudioDeviceInfoInternal::defaultInputDevice(), QAudioDeviceFactory::defaultOutputDevice(), QAudioDeviceInfoInternal::defaultOutputDevice(), QScriptDebuggerAgent::deleteBreakpoint(), deleteChildGroups(), QScriptDebuggerLocalsModelPrivate::deleteObjectSnapshots(), QMetaObjectBuilder::deserialize(), QWidget::destroy(), determineScreenSize(), QGraphicsItem::deviceTransform(), QMultiScreen::disconnect(), QApplicationPrivate::dispatchEnterLeave(), QGraphicsScenePrivate::dispatchHoverEvent(), QColumnViewPrivate::doLayout(), QDeclarativeGrid::doPositioning(), QFbScreen::doRedraw(), QIcdEngine::doRequestUpdate(), QDeclarativeXmlQueryEngine::doSubQueryJob(), QDragManager::drag(), QGraphicsScenePrivate::draw(), QPainterPrivate::draw_helper(), QGraphicsScenePrivate::drawItems(), QGraphicsScene::drawItems(), QX11PaintEngine::drawPath(), QWidgetPrivate::drawWidget(), effectiveState(), QClipboardWatcher::empty(), QWidgetPrivate::enforceNativeChildren(), QResourcePrivate::ensureChildren(), QResourcePrivate::ensureInitialized(), QIconLoaderEngine::ensureLoaded(), QWidget::ensurePolished(), QGraphicsItemPrivate::ensureSequentialSiblingIndex(), QGraphicsScenePrivate::ensureSequentialTopLevelSiblingIndexes(), QStateMachinePrivate::enterStates(), QDeclarativeDirParser::errors(), QGraphicsSceneBspTreeIndexPrivate::estimateItems(), QGraphicsSceneIndex::estimateTopLevelItems(), QPatternist::ReturnOrderBy::evaluateSingleton(), QMessageBox::event(), QApplication::event(), QWidget::event(), QWindowsStyle::eventFilter(), QMacStylePrivate::eventFilter(), QPSQLDriverPrivate::exec(), QScriptDebuggerCommandExecutor::execute(), QStateMachinePrivate::executeTransitionContent(), QStateMachinePrivate::exitStates(), QDockAreaLayoutInfo::expansive(), QMultiScreen::exposeRegion(), QDirectFBScreen::exposeRegion(), familyList(), QWSSoundServerPrivate::feedDevice(), QZipReader::fileData(), QZipReader::fileInfoList(), fillList(), QX11PaintEnginePrivate::fillPath(), find_child(), find_translation(), QMenuBarPrivate::QMacMenuBarPrivate::findAction(), QMenuBarPrivate::QWceMenuBarPrivate::findAction(), QMenuPrivate::QMacMenuPrivate::findAction(), QMenuPrivate::QWceMenuPrivate::findAction(), QHttpNetworkReplyPrivate::findChallenge(), QScriptDebuggerLocalsModelNode::findChild(), findChildFrame(), findChildrenHelper(), QFontDatabase::findFont(), QIconLoader::findIconHelper(), QListWidget::findItems(), QTableWidget::findItems(), QTreeWidget::findItems(), QStandardItemModel::findItems(), QStateMachinePrivate::findLCA(), QGLEngineSharedShaders::findProgramInCache(), QScriptObjectSnapshot::findProperty(), findRealWindow(), QDockAreaLayoutInfo::findSeparator(), findWindowThatShouldDisplayMenubar(), QScript::QObjectData::findWrapper(), QTextDocumentLayoutPrivate::findY(), QDockAreaLayoutInfo::fitItems(), QTextDocumentLayoutPrivate::floatMargins(), QEventDispatcherMac::flush(), QGLGlyphCache::fontEngineDestroyed(), QMimeDataWrapper::format(), QDropEvent::format(), QTextEngine::format(), QInternalMimeData::formats(), QMacPasteboard::formats(), QXlibClipboardMime::formats_sys(), QInternalMimeData::formatsHelper(), QPaintBuffer::frameEndIndex(), QRawFont::fromFont(), QScript::functionConnect(), QDockAreaLayoutInfo::gapIndex(), generateGlyphTables(), generateName(), QGestureEvent::gesture(), QGraphicsScenePrivate::gestureTargetsAtHotSpots(), Maemo::get_addrinfo_all_result(), getBounds(), getFcPattern(), getGlyphData(), getNetWmState(), QWidgetPrivate::getOpaqueChildren(), QScript::QObjectDelegate::getOwnPropertyNames(), getPrimaryScreen(), QGLProgramCache::getProgram(), QApplicationPrivate::globalEventProcessor(), QTextLine::glyphs(), QXlibIntegration::grabWindow(), QMultiScreen::haltUpdates(), QWSTtyKbPrivate::handleConsoleSwitch(), QScriptToolTipJob::handleResponse(), QDBusConnectionPrivate::handleSignal(), QWindowSystemInterface::handleTouchEvent(), QInternalMimeData::hasFormat(), QInternalMimeData::hasFormatHelper(), QToolButtonPrivate::hasMenu(), QResourceFileEngineIterator::hasNext(), QGraphicsScene::helpEvent(), QWSWindow::hide(), QWidgetPrivate::hideChildren(), QDialogPrivate::hideDefault(), QMessageBoxPrivate::hideSpecial(), QMdiAreaPrivate::highlightNextSubWindow(), QGLWindowSurface::hijackWindow(), QTextDocumentLayoutPrivate::hitTest(), QMainWindowLayout::hover(), QGuiPlatformPlugin::iconThemeSearchPaths(), if(), imageReadMimeFormats(), imageWriteMimeFormats(), QDeclarativeImportsPrivate::importExtension(), QScriptEngine::importExtension(), QSequentialAnimationGroupPrivate::indexForCurrentTime(), QDockAreaLayoutInfo::indexOf(), QRingBuffer< T >::indexOf(), indexOfDescendant(), indexOfMutating(), QDockAreaLayoutInfo::indexOfPlaceHolder(), QStatusBarPrivate::indexToLastNonPermanentWidget(), QSettingsPrivate::iniEscapedStringList(), QScriptDebuggerLocalsModel::init(), QImageReaderPrivate::initHandler(), QDirectFbIntegration::initializeDirectFB(), QApplication::inputContext(), QTextControlPrivate::inputMethodEvent(), QTextDocumentPrivate::insert_frame(), QMdiAreaPrivate::internalRaise(), QGraphicsItemPrivate::invalidateChildGraphicsEffectsRecursively(), QGraphicsItemPrivate::invalidateDepthRecursively(), QWidgetPrivate::isBackgroundInherited(), QApplicationPrivate::isBlockedByModal(), QSqlIndex::isDescending(), QStateMachinePrivate::isInFinalState(), QMultiScreen::isInterlaced(), QWidgetPrivate::isOverlapped(), isServerProcess(), QGraphicsSceneBspTree::items(), QGraphicsSceneIndexPrivate::items_helper(), kdeColor(), QMetaEnumBuilder::key(), QMetaEnumBuilder::keyCount(), QDialog::keyPressEvent(), QDecorationFactory::keys(), QMouseDriverFactory::keys(), QScreenDriverFactory::keys(), QGenericPluginFactory::keys(), QKbdDriverFactory::keys(), QTextCodecPlugin::keys(), QMetaEnum::keysToValue(), QObject::killTimer(), lastIndexOfMutating(), QTextDocumentLayoutPrivate::layoutBlock(), QDialogButtonBoxPrivate::layoutButtons(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFrame(), QTextFormat::lengthVectorProperty(), QGraphicsItemAnimationPrivate::linearValueForStep(), QPatternist::LiteralSequence::LiteralSequence(), QResourcePrivate::load(), QLibraryPrivate::load_sys(), loadFromDatabase(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), loadWin(), QFontDatabase::loadXlfd(), QLibraryInfo::location(), longestCommonPrefix(), QWSWindow::lower(), QFbScreen::lower(), QWidget::lower(), macList(), QResourceRoot::mappingRootSubdir(), QAbstractProxyModel::mapSelectionFromSource(), QAbstractProxyModel::mapSelectionToSource(), QGraphicsScenePrivate::markDirty(), markFrames(), QDockAreaLayoutInfo::maximumSize(), QMultiScreen::memoryNeeded(), QMenuPrivate::QMacMenuPrivate::merged(), QDockAreaLayoutInfo::minimumSize(), QGraphicsItem::mouseMoveEvent(), QGraphicsScenePrivate::mousePressEventHandler(), QWidgetBackingStore::moveStaticWidgets(), QVNCIntegration::moveToScreen(), QObjectPrivate::moveToThread_helper(), QAccessibleWidget::navigate(), QWSServerPrivate::newMouseHandler(), QDockAreaLayoutInfo::next(), QMdiAreaPrivate::nextVisibleSubWindow(), QFontSubset::nGlyphs(), QApplication::notify(), QMultiScreen::onCard(), QWSServer::openKeyboard(), QWSServer::openMouse(), QList< QPostEvent >::operator+=(), QGraphicsView::paintEvent(), QScriptXmlParser::parse(), QNetworkCookie::parseCookies(), parseGeometry(), QBBNavigatorEventNotifier::parsePPS(), QBBButtonEventNotifier::parsePPS(), QFileSystemModelPrivate::passNameFilters(), QRingBuffer< T >::peek(), QToolButtonPrivate::popupTimerDone(), QScriptDebuggerAgent::positionChange(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), QPainterReplayer::process(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QWSServer::processKeyEvent(), QMacPasteboard::promiseKeeper(), QWidgetPrivate::propagatePaletteChange(), QGraphicsSceneBspTreeIndexPrivate::purgeRemovedItems(), q_createNativeChildrenAndSetParent(), QDirIteratorPrivate::QDirIteratorPrivate(), QDirPrivate::QDirPrivate(), qGlobalPostedEventsCount(), QIconTheme::QIconTheme(), QKeySequence::QKeySequence(), QMultiInputContext::QMultiInputContext(), QScript::qobjectProtoFuncFindChildren(), qOpenGLVersionFlagsFromString(), QTest::qPrintDataTags(), QSslSocketBackendPrivate::QSslCipher_from_SSL_CIPHER(), qstring_to_xtp(), QtPrivate::QStringList_contains(), QtPrivate::QStringList_filter(), QtPrivate::QStringList_join(), QtPrivate::QStringList_removeDuplicates(), QtPrivate::QStringList_replaceInStrings(), qt_cleanup(), qt_create_commandline(), qt_custom_file_engine_handler_create(), QObject::qt_find_obj_child(), qt_get_screen(), qt_getDefaultFromHomePrinters(), qt_getLprPrinters(), qt_grab_cursor(), qt_mac_activate_action(), qt_mac_get_accel(), qt_mac_get_widget_rgn(), qt_mac_menu_event(), qt_mac_menu_merge_action(), qt_mac_QStringListToNSMutableArrayVoid(), qt_mac_set_modal_state(), qt_mac_should_disable_menu(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), qt_painter_removePaintDevice(), qt_parseEtcLpMember(), qt_parseEtcLpPrinters(), qt_parseSpoolInterface(), qt_perhapsAddPrinter(), qt_qFindChild_helper(), qt_qFindChildren_helper(), qt_set_windows_updateScrollBar(), qt_wce_get_quit_action(), qt_x11_recreateNativeWidgetsRecursive(), QWin32PrintEnginePrivate::queryDefault(), QWSDirectPainterSurface::QWSDirectPainterSurface(), QApplication::qwsSetCustomColors(), QWSWindow::raise(), QWidget::raise(), read_xpm_body(), QPngHandlerPrivate::readPngImage(), QRingBuffer< T >::readPointerAtPosition(), realMaxSize(), realMinSize(), QMdi::RegularTiler::rearrange(), QMdi::SimpleCascader::rearrange(), QMdi::IconTiler::rearrange(), QMdiAreaPrivate::rearrange(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QMenuPrivate::QWceMenuPrivate::rebuild(), QPanGestureRecognizer::recognize(), QPinchGestureRecognizer::recognize(), QSwipeGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), QTapAndHoldGestureRecognizer::recognize(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QPainter::redirected(), QUndoCommand::redo(), QGraphicsScenePrivate::registerTopLevelItem(), QStateMachinePrivate::registerTransitions(), QDir::relativeFilePath(), QMacSettingsPrivate::remove(), QWinSettingsPrivate::remove(), QTextFramePrivate::remove_me(), QGraphicsAnchorLayoutPrivate::removeCenterConstraints(), QGraphicsItemPrivate::removeChild(), QGraphicsItemGroup::removeFromGroup(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsSceneBspTree::removeItems(), QMetaEnumBuilder::removeKey(), QFSEventsFileSystemWatcherEngine::removePaths(), QGraphicsScenePrivate::removePopup(), QCoreApplicationPrivate::removePostedEvent(), QCoreApplication::removePostedEvents(), QCoreApplicationPrivate::removePostedTimerEvent(), QGraphicsScene::render(), QPaintEngineExPrivate::replayClipOperations(), QMacPinchGestureRecognizer::reset(), QGraphicsScenePrivate::resetDirtyItem(), QGraphicsSceneBspTreeIndexPrivate::resetIndex(), QCompletionModel::resetModel(), QSequentialAnimationGroupPrivate::restart(), QMultiScreen::restore(), QPainter::restoreRedirected(), QMainWindowLayoutState::restoreState(), QWSPcMouseHandlerPrivate::resume(), QNetworkReplyImplPrivate::resumeNotificationHandling(), QMultiScreen::resumeUpdates(), QInternalMimeData::retrieveData(), QMacPasteboard::retrieveData(), QMimeDataPrivate::retrieveTypedData(), QPatternist::ReturnOrderBy::ReturnOrderBy(), QSequentialAnimationGroupPrivate::rewindForwards(), QScriptDebuggerScriptsModel::rowCount(), QBenchmarkValgrindUtils::runCallgrindSubProcess(), sanityCheck(), QMultiScreen::save(), Maemo::IcdPrivate::scan(), QGraphicsItem::sceneEvent(), screenForDevice(), QWidgetPrivate::screenGeometry(), QWidgetPrivate::scroll_sys(), QWidgetPrivate::scrollChildren(), QMenuPrivate::scrollMenu(), QString::section(), QStateMachinePrivate::selectTransitions(), send_targets_selection(), QActionPrivate::sendDataChanged(), QCopChannel::sendLocally(), QWidgetPrivate::sendPendingMoveAndResizeEvents(), QCoreApplicationPrivate::sendPostedEvents(), sendResizeEvents(), QXlibClipboard::sendTargetsSelection(), QMainWindowPrivate::separatorCursor(), QDockAreaLayoutInfo::separatorMove(), QWorkspaceChild::setActive(), QWSWindow::setActiveWindow(), QApplication::setActiveWindow(), QGraphicsScene::setActiveWindow(), QSimplex::setConstraints(), QStringListModel::setData(), QDialogPrivate::setDefault(), QSqlIndex::setDescending(), QMultiScreen::setDirty(), QWidgetPrivate::setEnabled_helper(), QGraphicsScenePrivate::setFocusItemHelper(), QRuntimeGraphicsSystem::setGraphicsSystem(), QGraphicsScene::setItemIndexMethod(), QApplication::setLayoutDirection(), QGraphicsWidgetPrivate::setLayoutDirection_helper(), QWidgetPrivate::setLayoutDirection_helper(), QWidgetPrivate::setLocale_helper(), setMaxWindowRect(), QWSServer::setMaxWindowRect(), QApplicationPrivate::setMaxWindowRect(), QMacPasteboard::setMimeData(), QWidgetPrivate::setModal_sys(), QWidgetResizeHandler::setMouseCursor(), QFileSystemModel::setNameFilters(), QMenuBar::setNativeMenuBar(), QObject::setObjectName(), QPrinter::setPrinterName(), setScreenTransformation(), QApplicationPrivate::setScreenTransformation(), QMenu::setSeparatorsCollapsible(), QPatternist::UserFunctionCallsite::setSource(), QWidgetPrivate::setStyle_helper(), QWidget::setTabOrder(), QAbstractTransition::setTargetStates(), QObjectPrivate::setThreadData_helper(), QGraphicsItem::setTransformations(), QWidgetPrivate::setUpdatesEnabled_helper(), QMimeData::setUrls(), QWidgetPrivate::setWindowIcon_helper(), QMultiScreen::sharedRamSize(), QWSWindow::show(), QWidget::show(), QWidgetPrivate::showChildren(), QMultiScreen::shutdownDevice(), QDockAreaLayoutInfo::sizeHint(), QMultiScreen::solidFill(), QGraphicsAnchorLayoutPrivate::solveMinMax(), QGraphicsAnchorLayoutPrivate::solvePreferred(), QSimplex::solver(), QDirPrivate::sortFileList(), QFSCompleter::splitPath(), QGraphicsItem::stackBefore(), QCommonStyle::standardIconImplementation(), QScriptCompletionTask::start(), QWindowsVistaStylePrivate::startAnimation(), QProcessPrivate::startDetached(), QSslSocketBackendPrivate::startHandshake(), QProcessPrivate::startProcess(), Maemo::IcdPrivate::state(), QPatternist::LiteralSequence::staticType(), QWindowsVistaStylePrivate::stopAnimation(), QSettingsPrivate::stringToVariant(), QApplication::style(), QWidgetPrivate::subtractOpaqueSiblings(), QMdiAreaTabBar::subWindowFromIndex(), QMdiAreaPrivate::subWindowList(), QPrinter::supportedPaperSources(), QPrinter::supportedResolutions(), QWSPcMouseHandlerPrivate::suspend(), QWidgetBackingStore::sync(), QApplication::syncX(), QClipboard::text(), QImage::textLanguages(), QImage::textList(), QWindowsVistaStylePrivate::timerEvent(), QMacStylePrivate::timerEvent(), QPainterPath::toFillPolygon(), QPainterPath::toFillPolygons(), QPlatformScreen::topLevelAt(), QFbScreen::topLevelAt(), QFontSubset::toType1(), QDeclarativeItemPrivate::transform_count(), QDeclarativeTransitionManager::transition(), QDeclarativeParentAnimation::transition(), QETWidget::translateMouseEvent(), QETWidget::translateXinputEvent(), QMeeGoGraphicsSystem::triggerSwitchCallbacks(), QFontSubset::type1AddedGlyphs(), QFileDialogPrivate::typedFiles(), QUndoCommand::undo(), QStateMachinePrivate::unregisterAllTransitions(), QResource::unregisterResource(), QGraphicsScenePrivate::unregisterTopLevelItem(), QWSServerPrivate::update_regions(), update_toolbar_style(), QMdiAreaPrivate::updateActiveWindow(), QGraphicsWidgetPrivate::updateFont(), QWidgetPrivate::updateFont(), QGLWindowSurface::updateGeometry(), QMainWindowLayout::updateHIToolBarStatus(), QGraphicsScenePrivate::updateInputMethodSensitivityInViews(), QWidgetBackingStore::updateLists(), QGraphicsItemPrivate::updatePaintedViewBoundingRects(), QGraphicsWidgetPrivate::updatePalette(), QGraphicsView::updateScene(), QDesktopWidgetPrivate::updateScreenList(), QWidgetBackingStore::updateStaticContentsSize(), updateWidgets(), QMimeData::urls(), QMetaEnumBuilder::value(), QDeclarativeEngineDebugService::valueContents(), Maemo::IAPConfPrivate::variantToValue(), QIconLoaderEngine::virtual_hook(), QGraphicsSceneFindItemBspTreeVisitor::visit(), QMenuBar::wceCommands(), QMenuBarPrivate::wceEmitSignals(), QMenuBar::wceRefresh(), QWorkspace::windowList(), QWSServer::windowList(), QHostInfoLookupManager::work(), QUnixSocketPrivate::writeActivated(), QIBaseResultPrivate::writeArray(), writeIncludeFile(), QConfFileSettingsPrivate::writeIniFile(), QApplicationPrivate::x11_apply_settings(), QApplication::x11ProcessEvent(), QBBWindow::~QBBWindow(), QGraphicsItem::~QGraphicsItem(), QIconLoaderEngine::~QIconLoaderEngine(), QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate(), QSingleDesktopWidget::~QSingleDesktopWidget(), QThreadData::~QThreadData(), QWaylandWindow::~QWaylandWindow(), QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate(), and QWindowsMimeList::~QWindowsMimeList().
 { return p.size(); }
startsWith()
template<typename T> bool QList< T >::startsWith (const T & value) const inline
Returns true if this list is not empty and its first item is equal to value; otherwise returns false.
Since
4.5
See also
isEmpty(), contains()
Definition at line 288 of file qlist.h.
 { return !isEmpty() && first() == t; }
swap() [1/2]
template<typename T> void QList< T >::swap (QList< T > & other) inline
Swaps list other with this list.
Since
4.8
This operation is very fast and never fails.
Definition at line 129 of file qlist.h.
Referenced by QImageReaderPrivate::initHandler(), QCoreApplication::removePostedEvents(), and QQueue< QHostInfoRunnable *>::swap().
 { qSwap(d, other.d); }
swap() [2/2]
template<typename T> void QList< T >::swap (int i, int j) inline
Exchange the item at index position i with the item at index position j.
This function assumes that both i and j are at least 0 but less than size(). To avoid failure, test that both i and j are at least 0 and less than size().
Example:
QList<QString> list;
list << "A" << "B" << "C" << "D" << "E" << "F";
list.swap(1, 4);
// list: ["A", "E", "C", "D", "B", "F"]
See also
move()
Definition at line 617 of file qlist.h.
 {
     Q_ASSERT_X(i >= 0 && i < p.size() && j >= 0 && j < p.size(),
                 "QList<T>::swap", "index out of range");
     detach();
     void *t = d->array[d->begin + i];
     d->array[d->begin + i] = d->array[d->begin + j];
     d->array[d->begin + j] = t;
 }
takeAt()
template<typename T > T QList< T >::takeAt (int i) inline
Removes the item at index position i and returns it.
i must be a valid index position in the list (i.e., 0 <= i < size()).
If you don't use the return value, removeAt() is more efficient.
See also
removeAt(), takeFirst(), takeLast()
Definition at line 484 of file qlist.h.
Referenced by QHostInfoLookupManager::abortLookup(), allCombinations(), QDialogButtonBox::clear(), QListModel::ensureSorted(), QTreeModel::ensureSorted(), QHttpNetworkConnectionPrivate::fillPipeline(), QDialogButtonBox::removeButton(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), QGraphicsAnchorLayoutPrivate::removeCenterConstraints(), QScriptDebuggerLocalsModelPrivate::removeChild(), FlatListModel::removedNode(), QWSServer::removeKeyboardFilter(), QListModel::removeRows(), QTreeModel::removeRows(), QDockAreaLayoutInfo::restoreState(), QToolBarAreaLayout::restoreState(), QWindowsVistaStylePrivate::stopAnimation(), QListModel::take(), QToolBarLayout::takeAt(), QToolBarAreaLayout::takeAt(), QTreeWidgetItem::takeChild(), QWindowsVistaStylePrivate::timerEvent(), and QTreeWidgetItem::~QTreeWidgetItem().
 { Q_ASSERT_X(i >= 0 && i < p.size(), "QList<T>::take", "index out of range");
  detach(); Node *n = reinterpret_cast<Node *>(p.at(i)); T t = n->t(); node_destruct(n);
  p.remove(i); return t; }
takeFirst()
template<typename T > T QList< T >::takeFirst () inline
Removes the first item in the list and returns it.
This is the same as takeAt(0). This function assumes the list is not empty. To avoid failure, call isEmpty() before calling this function.
This operation takes constant time.
If you don't use the return value, removeFirst() is more efficient.
See also
takeLast(), takeAt(), removeFirst()
Definition at line 489 of file qlist.h.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex(), QIcdEngine::asyncUpdateConfigurationsSlot(), cleanup_mimes(), QObjectCleanupHandler::clear(), QPlatformIntegrationFactory::create(), QDBusConnectionPrivate::customEvent(), QBoxLayoutPrivate::deleteAll(), QQueue< QHostInfoRunnable *>::dequeue(), QStateMachinePrivate::dequeueExternalEvent(), QStateMachinePrivate::dequeueInternalEvent(), QGenericEngine::doRequestUpdate(), QTreeWidget::dropEvent(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::epsilonClosure(), QDB2Result::exec(), findSnapshotIdsRecursively(), QHttpPrivate::finishedWithError(), QNetworkManagerEngine::interfacePropertiesChanged(), FAREnforcer::logAuthAttempt(), QScriptDebuggerPrivate::maybeStartNewJob(), QCoreWlanEngine::networksChanged(), QNlaEngine::networksChanged(), Maemo::prepareDBusCall(), qOraOutValue(), qt_call_post_routines(), qwsEventSourceDispatch(), QByteDataBuffer::read(), QRingBuffer< T >::read(), QWSDisplay::Data::readMore(), QWSClient::readMoreCommand(), QThreadPoolThread::run(), Maemo::IcdPrivate::scan(), QNativeWifiEngine::scanComplete(), QAction::setShortcuts(), QThreadPoolPrivate::startFrontRunnable(), QPatternist::XsdParticleChecker::subsumes(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), QThreadPoolPrivate::tryStart(), QNlaThread::updateConfigurations(), QGLWindowSurface::updateGeometry(), x11EventSourceDispatch(), QCoreWlanEngine::~QCoreWlanEngine(), QMenuPrivate::QMacMenuPrivate::~QMacMenuPrivate(), QScriptEnginePrivate::~QScriptEnginePrivate(), and QToolBarLayout::~QToolBarLayout().
 { T t = first(); removeFirst(); return t; }
takeLast()
template<typename T > T QList< T >::takeLast () inline
Removes the last item in the list and returns it.
This is the same as takeAt(size() - 1). This function assumes the list is not empty. To avoid failure, call isEmpty() before calling this function.
This operation takes constant time.
If you don't use the return value, removeLast() is more efficient.
See also
takeFirst(), takeAt(), removeLast()
Definition at line 492 of file qlist.h.
Referenced by QScriptEngine::availableExtensions(), QDeclarativeDataBlob::cancelAllWaitingFor(), QWSSignalHandler::clear(), QColumnViewPrivate::closeColumns(), convertPath(), QScriptDebuggerBackend::doPendingEvaluate(), QIconLoaderEngine::ensureLoaded(), QDeclarativePathView::itemsMoved(), QDeclarativeDataBlob::notifyAllWaitingOnMe(), QDeclarativeXmlQueryEngine::processJobs(), qWinProcessConfigRequests(), MetaObjectGenerator::readFuncsInfo(), QGraphicsScenePrivate::removePopup(), QApplicationPrivate::setScreenTransformation(), QGraphicsScenePrivate::ungrabKeyboard(), QGraphicsScenePrivate::ungrabMouse(), QDesktopWidgetPrivate::updateScreenList(), QApplication::winFocus(), and QIconLoaderEngine::~QIconLoaderEngine().
 { T t = last(); removeLast(); return t; }
toSet()
template<typename T > Q_OUTOFLINE_TEMPLATE QSet< T > QList< T >::toSet () const
Returns a QSet object with the data contained in this QList.
Since QSet doesn't allow duplicates, the resulting QSet might be smaller than the original list was.
Example:
QStringList list;
list << "Julia" << "Mike" << "Mike" << "Julia" << "Julia";
QSet<QString> set = list.toSet();
set.contains("Julia");  // returns true
set.contains("Mike");   // returns true
set.size();             // returns 2
See also
toVector(), fromSet(), QSet::fromList()
Definition at line 309 of file qset.h.
Referenced by QPatternist::XsdInstanceReader::attributeNames(), QScriptObjectSnapshot::capture(), QSet< typename TokenLookupClass::NodeName >::fromList(), QScriptXmlParser::parse(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), and QmlJSDebugger::LiveRubberBandSelectionManipulator::select().
 {
     QSet<T> result;
     result.reserve(size());
     for (int i = 0; i < size(); ++i)
         result.insert(at(i));
     return result;
 }
toStdList()
template<typename T> std::list< T > QList< T >::toStdList () const inline
Returns a std::list object with the data contained in this QList.
Example:
QList<double> list;
list << 1.2 << 0.5 << 3.14;
std::list<double> stdlist = list.toStdList();
See also
fromStdList(), QVector::toStdVector()
Definition at line 347 of file qlist.h.
     { std::list<T> tmp; qCopy(constBegin(), constEnd(), std::back_inserter(tmp)); return tmp; }
toVector()
template<typename T > Q_OUTOFLINE_TEMPLATE QVector< T > QList< T >::toVector () const
Returns a QVector object with the data contained in this QList.
Example:
QStringList list;
list << "Sven" << "Kim" << "Ola";
QVector<QString> vect = list.toVector();
// vect: ["Sven", "Kim", "Ola"]
See also
toSet(), fromVector(), QVector::fromList()
Definition at line 780 of file qvector.h.
Referenced by QVector< QPoint >::fromList(), and QPatternist::ListIterator< QXmlNodeModelIndexIteratorPointer, QVector< QXmlNodeModelIndexIteratorPointer > >::toVector().
 {
     QVector<T> result(size());
     for (int i = 0; i < size(); ++i)
         result[i] = at(i);
     return result;
 }
value() [1/2]
template<typename T > Q_OUTOFLINE_TEMPLATE T QList< T >::value (int i) const
Returns the value at index position i in the list.
If the index i is out of bounds, the function returns a default-constructed value. If you are certain that the index is going to be within bounds, you can use at() instead, which is slightly faster.
See also
at(), operator[]()
Definition at line 661 of file qlist.h.
Referenced by QFileDialogPrivate::_q_pathChanged(), QAccessibleMenu::actionText(), QAccessibleWidget::actionText(), QAccessibleMenuBar::actionText(), QTextCharFormat::anchorName(), QListModel::at(), QGLGlyphCache::cleanCache(), QAbstractItemViewPrivate::clearOrRemove(), QScreen::compose(), QPatternist::PatternPlatform::compress(), QPatternist::SubsequenceFN::compress(), QPrinterInfo::defaultPrinter(), QAccessibleMenu::doAction(), QAccessibleMenuBar::doAction(), FlatListModel::get(), QFileDialog::getExistingDirectory(), QInputDialog::getItem(), QFileDialog::getOpenFileName(), QFileDialog::getSaveFileName(), QScriptDebuggerShowLineJob::handleResponse(), QNetworkManagerEngine::interfacePropertiesChanged(), QAccessibleTextEdit::invokeMethodEx(), QAccessibleLineEdit::invokeMethodEx(), QTextTableCell::lastPosition(), QInputDialogPrivate::listViewText(), QGraphicsScenePrivate::mousePressEventHandler(), QPatternist::PatternPlatform::pattern(), QObject::property(), QIconTheme::QIconTheme(), qt_getLprPrinters(), QFileDialogPrivate::qt_mac_filedialog_event_proc(), QIcdEngine::requestUpdate(), QTableView::selectionChanged(), QListView::selectionChanged(), QTreeView::selectionChanged(), QSplitterPrivate::setSizes_helper(), QMessageBoxPrivate::showOldMessageBox(), QScriptCompletionTask::start(), QSslSocketBackendPrivate::startHandshake(), QAccessibleMenuBar::state(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::toDFA(), and QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate().
 {
     if (i < 0 || i >= p.size()) {
         return T();
     }
     return reinterpret_cast<Node *>(p.at(i))->t();
 }
value() [2/2]
template<typename T> Q_OUTOFLINE_TEMPLATE T QList< T >::value (int i, const T & defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 670 of file qlist.h.
 {
     return ((i < 0 || i >= p.size()) ? defaultValue : reinterpret_cast<Node *>(p.at(i))->t());
 }
Friends and Related Functions
const_iterator
template<typename T> friend class const_iterator friend
Definition at line 264 of file qlist.h.
Referenced by QPatternist::checkVariableCircularity().
iterator
template<typename T> friend class iterator friend
Definition at line 226 of file qlist.h.
operator<<()
template<typename T> QDataStream & operator<< (QDataStream & out, const QList< T > & list) related
Writes the list list to stream out.
This function requires the value type to implement operator<<().
See also
Format of the QDataStream operators
Definition at line 261 of file qdatastream.h.
 {
     s << quint32(l.size());
     for (int i = 0; i < l.size(); ++i)
         s << l.at(i);
     return s;
 }
operator>>()
template<typename T> QDataStream & operator>> (QDataStream & in, QList< T > & list) related
Reads a list from stream in into list.
This function requires the value type to implement operator>>().
See also
Format of the QDataStream operators
Definition at line 243 of file qdatastream.h.
 {
     l.clear();
     quint32 c;
     s >> c;
     l.reserve(c);
     for(quint32 i = 0; i < c; ++i)
     {
         T t;
         s >> t;
         l.append(t);
         if (s.atEnd())
             break;
     }
     return s;
 }
Properties
@60
union { ... }
d
template<typename T> QListData::Data* QList< T >::d
Definition at line 118 of file qlist.h.
Referenced by QList< QPostEvent >::isSharedWith(), QMetaEnum::keysToValue(), QList< QPostEvent >::mid(), QList< QPostEvent >::operator=(), QList< QPostEvent >::operator==(), QMetaMethod::parameterNames(), QMetaMethod::parameterTypes(), QList< QPostEvent >::swap(), and QMetaEnum::valueToKeys().
p
template<typename T> QListData QList< T >::p
Definition at line 118 of file qlist.h.
Referenced by QList< QPostEvent >::mid(), QList< QPostEvent >::operator+=(), and QList< QPostEvent >::operator==().
The documentation for this class was generated from the following files:
/src/corelib/io/qdatastream.h
/src/corelib/tools/qlist.h
/src/corelib/tools/qlist.cpp
/src/corelib/tools/qset.h
/src/corelib/tools/qvector.h