Qt 4.8: QWSInputContext Class Reference
QWSInputContext Class Reference
#include <qwsinputcontext_p.h>
Public Functions
QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
QString language ()
This function must be implemented in any subclasses to return a language code (e.
void mouseHandler (int x, QMouseEvent *event)
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
QWSInputContext (QObject *parent=0)
void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
void setFocusWidget (QWidget *w)
Sets the widget that has an input focus for this input context.
void update ()
This virtual function is called when a state in the focus widget has changed.
void widgetDestroyed (QWidget *w)
This virtual function is called when the specified widget is destroyed.
~QWSInputContext ()
Public Functions inherited from QInputContext
virtual QList< QAction * > actions ()
This is a preliminary interface for Qt 4.
virtual bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
QWidget * focusWidget () const
Returns the widget that has an input focus for this input context.
virtual QFont font () const
Returns the font of the current input widget.
QInputContext (QObject *parent=0)
Constructs an input context with the given parent.
void sendEvent (const QInputMethodEvent &event)
Sends an input method event specified by event to the current focus widget.
QTextFormat standardFormat (StandardFormat s) const
Returns a QTextFormat object that specifies the format for component s.
virtual bool x11FilterEvent (QWidget *keywidget, XEvent *event)
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
virtual ~QInputContext ()
Destroys the input context.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QWidget * activeWidget ()
static bool translateIMEvent (QWidget *w, const QWSIMEvent *e)
static bool translateIMInitEvent (const QWSIMInitEvent *e)
static bool translateIMQueryEvent (QWidget *w, const QWSIMQueryEvent *e)
static void updateImeStatus (QWidget *w, bool hasFocus)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Additional Inherited Members
Public Types inherited from QInputContext
enum StandardFormat { PreeditFormat, SelectionFormat }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qwsinputcontext_p.h.
Constructors and Destructors
QWSInputContext()
QWSInputContext::QWSInputContext (QObject * parent = 0) explicit
Definition at line 63 of file qwsinputcontext_qws.cpp.
     :QInputContext(parent)
 {
 }
~QWSInputContext()
QWSInputContext::~QWSInputContext () inline
Definition at line 71 of file qwsinputcontext_p.h.
 {}
Functions
activeWidget()
QWidget * QWSInputContext::activeWidget () static
Definition at line 139 of file qwsinputcontext_qws.cpp.
Referenced by language().
 {
     return QT_PREPEND_NAMESPACE(activeWidget);
 }
identifierName()
QString QWSInputContext::identifierName () inline virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 74 of file qwsinputcontext_p.h.
 { return QString(); }
isComposing()
bool QWSInputContext::isComposing () const virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 145 of file qwsinputcontext_qws.cpp.
Referenced by language().
 {
     return QT_PREPEND_NAMESPACE(activeWidget) != 0;
 }
language()
QString QWSInputContext::language () inline virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
Definition at line 75 of file qwsinputcontext_p.h.
 { return QString(); }
mouseHandler()
void QWSInputContext::mouseHandler (int x, QMouseEvent * event) virtual
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
You can use the function to implement mouse-oriented user interface such as text selection or popup menu for candidate selection.
The x parameter is the offset within the string that was sent with the InputMethodCompose event. The alteration boundary of x is ensured as character boundary of preedit string accurately.
The event parameter is the event that was sent to the editor widget. The event type is QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QEvent::MouseButtonDblClick or QEvent::MouseMove. The event's button and state indicate the kind of operation that was performed.
Reimplemented from QInputContext.
Definition at line 133 of file qwsinputcontext_qws.cpp.
Referenced by language().
 {
     if (event->type() == QEvent::MouseButtonPress || event->type() == QEvent::MouseButtonRelease)
         QPaintDevice::qwsDisplay()->sendIMMouseEvent( x, event->type() == QEvent::MouseButtonPress );
 }
reset()
void QWSInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
Definition at line 68 of file qwsinputcontext_qws.cpp.
Referenced by language().
 {
     QPaintDevice::qwsDisplay()->resetIM();
 }
setFocusWidget()
void QWSInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
Definition at line 74 of file qwsinputcontext_qws.cpp.
Referenced by language().
 {
     QWidget *oldFocus = focusWidget();
     if (oldFocus == w)
         return;
     if (w) {
         QWSInputContext::updateImeStatus(w, true);
     } else {
         if (oldFocus)
             QWSInputContext::updateImeStatus(oldFocus, false);
     }
     if (oldFocus) {
         QWidget *tlw = oldFocus->window();
         int winid = tlw->internalWinId();
         int widgetid = oldFocus->internalWinId();
         QPaintDevice::qwsDisplay()->sendIMUpdate(QWSInputMethod::FocusOut, winid, widgetid);
     }
     QInputContext::setFocusWidget(w);
     if (!w)
         return;
     QWidget *tlw = w->window();
     int winid = tlw->winId();
     int widgetid = w->winId();
     QPaintDevice::qwsDisplay()->sendIMUpdate(QWSInputMethod::FocusIn, winid, widgetid);
     //setfocus ???
     update();
 }
translateIMEvent()
bool QWSInputContext::translateIMEvent (QWidget * w, const QWSIMEvent * e) static
Definition at line 176 of file qwsinputcontext_qws.cpp.
Referenced by language(), and QApplication::qwsProcessEvent().
 {
     QDataStream stream(e->streamingData);
     QString preedit;
     QString commit;
     stream >> preedit;
     stream >> commit;
     if (preedit.isEmpty() && QT_PREPEND_NAMESPACE(activeWidget))
         w = QT_PREPEND_NAMESPACE(activeWidget);
     QInputContext *qic = w->inputContext();
     if (!qic)
         return false;
     QList<QInputMethodEvent::Attribute> attrs;
     while (!stream.atEnd()) {
         int type = -1;
         int start = -1;
         int length = -1;
         QVariant data;
         stream >> type >> start >> length >> data;
         if (stream.status() != QDataStream::Ok) {
             qWarning("corrupted QWSIMEvent");
             //qic->reset(); //???
             return false;
         }
         if (type == QInputMethodEvent::TextFormat)
             data = qic->standardFormat(static_cast<QInputContext::StandardFormat>(data.toInt()));
         attrs << QInputMethodEvent::Attribute(static_cast<QInputMethodEvent::AttributeType>(type), start, length, data);
     }
 #ifdef EXTRA_DEBUG
     qDebug() << "preedit" << preedit << "len" << preedit.length() <<"commit" << commit << "len" << commit.length()
              << "n attr" << attrs.count();
 #endif
     if (preedit.isEmpty())
         QT_PREPEND_NAMESPACE(activeWidget) = 0;
     else
         QT_PREPEND_NAMESPACE(activeWidget) = w;
     QInputMethodEvent ime(preedit, attrs);
     if (!commit.isEmpty() || e->simpleData.replaceLength > 0)
         ime.setCommitString(commit, e->simpleData.replaceFrom, e->simpleData.replaceLength);
     extern bool qt_sendSpontaneousEvent(QObject *, QEvent *); //qapplication_qws.cpp
     qt_sendSpontaneousEvent(w, &ime);
     return true;
 }
translateIMInitEvent()
bool QWSInputContext::translateIMInitEvent (const QWSIMInitEvent * e) static
Definition at line 169 of file qwsinputcontext_qws.cpp.
Referenced by language(), and QApplication::qwsProcessEvent().
 {
     Q_UNUSED(e);
     qDebug("### QWSInputContext::translateIMInitEvent not implemented ###");
     return false;
 }
translateIMQueryEvent()
bool QWSInputContext::translateIMQueryEvent (QWidget * w, const QWSIMQueryEvent * e) static
Definition at line 150 of file qwsinputcontext_qws.cpp.
Referenced by language(), and QApplication::qwsProcessEvent().
 {
     Qt::InputMethodQuery type = static_cast<Qt::InputMethodQuery>(e->simpleData.property);
     QVariant result = w->inputMethodQuery(type);
     QWidget *tlw = w->window();
     int winId = tlw->winId();
     if ( type == Qt::ImMicroFocus ) {
         // translate to relative to tlw
         QRect mf = result.toRect();
         mf.moveTopLeft(w->mapTo(tlw,mf.topLeft()));
         result = mf;
     }
     QPaintDevice::qwsDisplay()->sendIMResponse(winId, e->simpleData.property, result);
     return false;
 }
update()
void QWSInputContext::update () virtual
This virtual function is called when a state in the focus widget has changed.
QInputContext can then use QWidget::inputMethodQuery() to query the new state of the widget.
Reimplemented from QInputContext.
Definition at line 119 of file qwsinputcontext_qws.cpp.
Referenced by language(), and setFocusWidget().
 {
     QWidget *w = focusWidget();
     if (!w)
         return;
     QWidget *tlw = w->window();
     int winid = tlw->winId();
     int widgetid = w->winId();
     QPaintDevice::qwsDisplay()->sendIMUpdate(QWSInputMethod::Update, winid, widgetid);
 }
updateImeStatus()
void QWSInputContext::updateImeStatus (QWidget * w, bool hasFocus) static
Definition at line 234 of file qwsinputcontext_qws.cpp.
Referenced by language(), and setFocusWidget().
 {
     Q_UNUSED(hasFocus);
     if (!w || !qt_qws_inputMethodStatusChanged)
         return;
     qt_qws_inputMethodStatusChanged(w);
 }
widgetDestroyed()
void QWSInputContext::widgetDestroyed (QWidget * widget) virtual
This virtual function is called when the specified widget is destroyed.
The widget is a widget on which this input context is installed.
Reimplemented from QInputContext.
Definition at line 112 of file qwsinputcontext_qws.cpp.
Referenced by language().
 {
     if (w == QT_PREPEND_NAMESPACE(activeWidget))
         QT_PREPEND_NAMESPACE(activeWidget) = 0;
     QInputContext::widgetDestroyed(w);
 }
The documentation for this class was generated from the following files:
/src/gui/inputmethod/qwsinputcontext_p.h
/src/gui/inputmethod/qwsinputcontext_qws.cpp