Qt 4.8: QFileDialogPrivate Class Reference
QFileDialogPrivate Class Reference
#include <qfiledialog_p.h>
Classes
struct QtMacFilterName
struct QtMacNavFilterInfo
Public Functions
void _q_autoCompleteFileName (const QString &)
void _q_createDirectory ()
Creates a new directory, first asking the user for a suitable name.
void _q_currentChanged (const QModelIndex &index)
void _q_deleteCurrent ()
Deletes the currently selected item in the dialog.
void _q_enterDirectory (const QModelIndex &index)
This is called when the user double clicks on a file with the corresponding model item index.
void _q_fileRenamed (const QString &path, const QString oldName, const QString newName)
void _q_goHome ()
void _q_goToDirectory (const QString &)
Changes the file dialog's current directory to the one specified by path.
void _q_goToUrl (const QUrl &url)
void _q_macRunNativeAppModalPanel ()
void _q_navigateBackward ()
Navigates to the last directory viewed in the dialog.
void _q_navigateForward ()
Navigates to the last directory viewed in the dialog.
void _q_navigateToParent ()
Navigates to the parent directory of the currently displayed directory in the dialog.
void _q_pathChanged (const QString &)
void _q_renameCurrent ()
void _q_rowsInserted (const QModelIndex &parent)
When parent is root and rows have been inserted when none was there before then select the first one.
void _q_selectionChanged ()
This is called when the model index corresponding to the current file is changed from index to current.
void _q_showContextMenu (const QPoint &position)
void _q_showDetailsView ()
void _q_showHeader (QAction *)
void _q_showHidden ()
Includes hidden files and directories in the items displayed in the dialog.
void _q_showListView ()
void _q_updateOkButton ()
void _q_useNameFilter (int index)
Sets the current name filter to be nameFilter and update the qFileDialogUi->fileNameEdit when in AcceptSave mode with the new extension.
QStringList addDefaultSuffixToFiles (const QStringList filesToFix) const
QString basename (const QString &path) const
bool canBeNativeDialog ()
void createMenuActions ()
Create actions which will be used in the right click.
void createNavServicesDialog ()
void createNSOpenSavePanelDelegate ()
void createToolButtons ()
void createWidgets ()
QAbstractItemView * currentView () const
void deleteNativeDialog_sys ()
QDialog::DialogCode dialogResultCode_sys ()
QString directory_sys () const
void emitFilesSelected (const QStringList &files)
QDir::Filters filterForMode (QDir::Filters filters) const
QString getEnvironmentVariable (const QString &string)
bool hideCarbonNavServicesDialog ()
void init (const QString &directory=QString(), const QString &nameFilter=QString(), const QString &caption=QString())
bool itemViewKeyboardEvent (QKeyEvent *event)
QLineEdit * lineEdit () const
void mac_nativeDialogModalHelp ()
QModelIndex mapFromSource (const QModelIndex &index) const
QModelIndex mapToSource (const QModelIndex &index) const
int maxNameLength (const QString &path)
QFileDialogPrivate ()
void QNSOpenSavePanelDelegate_directoryEntered (const QString &newDir)
void QNSOpenSavePanelDelegate_filterSelected (int menuIndex)
void QNSOpenSavePanelDelegate_panelClosed (bool accepted)
void QNSOpenSavePanelDelegate_selectionChanged (const QString &newPath)
bool removeDirectory (const QString &path)
void retranslateStrings ()
void retranslateWindowTitle ()
QModelIndex rootIndex () const
QString rootPath () const
QModelIndex select (const QModelIndex &index) const
QStringList selectedFiles_sys () const
QString selectedNameFilter_sys () const
void selectFile_sys (const QString &filename)
void selectNameFilter_sys (const QString &filter)
void setDirectory_sys (const QString &directory)
void setFilter_sys ()
void setLastVisitedDirectory (const QString &dir)
void setNameFilters_sys (const QStringList &filters)
void setRootIndex (const QModelIndex &index) const
bool setVisible_sys (bool visible)
bool showCarbonNavServicesDialog ()
QStringList typedFiles () const
~QFileDialogPrivate ()
Public Functions inherited from QDialogPrivate
void hideDefault ()
Hides the default button indicator.
QDialogPrivate ()
void resetModalitySetByOpen ()
void setDefault (QPushButton *)
This function is called by the push button pushButton when it becomes the default button.
void setMainDefault (QPushButton *)
This function sets the default default push button to pushButton.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QString initialSelection (const QString &path)
static void qt_mac_filedialog_event_proc (const NavEventCallbackMessage msg, NavCBRecPtr p, NavCallBackUserData data)
static Boolean qt_mac_filedialog_filter_proc (AEDesc *theItem, void *info, void *data, NavFilterModes)
static QString toInternal (const QString &path)
static QString workingDirectory (const QString &path)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QString acceptLabel
QFileDialog::AcceptMode acceptMode
QFSCompleter * completer
bool confirmOverwrite
QStringList currentHistory
int currentHistoryLocation
bool defaultFileTypes
QString defaultSuffix
QAction * deleteAction
QFileDialog::FileMode fileMode
bool fileNameLabelExplicitlySat
struct QFileDialogPrivate::QtMacNavFilterInfo filterInfo
QString mCurrentLocation
QString mCurrentSelection
QStringList mCurrentSelectionList
void * mDelegate
NavDialogRef mDialog
bool mDialogClosed
bool mDialogStarted
QByteArray memberToDisconnectOnClose
QFileSystemModel * model
QStringList nameFilters
bool nativeDialogInUse
QAction * newFolderAction
QFileDialog::Options opts
QAbstractProxyModel * proxyModel
QScopedPointer< Ui_QFileDialog > qFileDialogUi
QPointer< QObject > receiverToDisconnectOnClose
QAction * renameAction
QString setWindowTitle
QAction * showHiddenAction
QByteArray signalToDisconnectOnClose
bool useDefaultCaption
QStringList watching
Public Variables inherited from QDialogPrivate
bool doShowExtension
QPointer< QEventLoop > eventLoop
QWidget * extension
QPoint lastRMBPress
QPointer< QPushButton > mainDef
QSize max
QSize min
Qt::Orientation orientation
int rescode
int resetModalityTo
QSizeGrip * resizer
QSize size
bool sizeGripEnabled
bool wasModalitySet
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 112 of file qfiledialog_p.h.
Constructors and Destructors
QFileDialogPrivate()
QFileDialogPrivate::QFileDialogPrivate ()
Definition at line 554 of file qfiledialog.cpp.
     :
 #ifndef QT_NO_PROXYMODEL
         proxyModel(0),
 #endif
         model(0),
         fileMode(QFileDialog::AnyFile),
         acceptMode(QFileDialog::AcceptOpen),
         currentHistoryLocation(-1),
         renameAction(0),
         deleteAction(0),
         showHiddenAction(0),
         useDefaultCaption(true),
         defaultFileTypes(true),
         fileNameLabelExplicitlySat(false),
         nativeDialogInUse(false),
 #ifdef Q_WS_MAC
         mDelegate(0),
 #ifndef QT_MAC_USE_COCOA
         mDialog(0),
         mDialogStarted(false),
         mDialogClosed(true),
 #endif
 #endif
         qFileDialogUi(0)
 {
 }
~QFileDialogPrivate()
QFileDialogPrivate::~QFileDialogPrivate ()
Definition at line 582 of file qfiledialog.cpp.
 {
 }
Functions
_q_autoCompleteFileName()
void QFileDialogPrivate::_q_autoCompleteFileName (const QString & text)
Definition at line 2982 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     if (text.startsWith(QLatin1String("//")) || text.startsWith(QLatin1Char('\\'))) {
         qFileDialogUi->listView->selectionModel()->clearSelection();
         return;
     }
     QStringList multipleFiles = typedFiles();
     if (multipleFiles.count() > 0) {
         QModelIndexList oldFiles = qFileDialogUi->listView->selectionModel()->selectedRows();
         QModelIndexList newFiles;
         for (int i = 0; i < multipleFiles.count(); ++i) {
             QModelIndex idx = model->index(multipleFiles.at(i));
             if (oldFiles.contains(idx))
                 oldFiles.removeAll(idx);
             else
                 newFiles.append(idx);
         }
         for (int i = 0; i < newFiles.count(); ++i)
             select(newFiles.at(i));
         if (lineEdit()->hasFocus())
             for (int i = 0; i < oldFiles.count(); ++i)
                 qFileDialogUi->listView->selectionModel()->select(oldFiles.at(i),
                     QItemSelectionModel::Toggle | QItemSelectionModel::Rows);
     }
 }
_q_createDirectory()
void QFileDialogPrivate::_q_createDirectory ()
Creates a new directory, first asking the user for a suitable name.
Warning
This function is not part of the public interface.
Definition at line 2817 of file qfiledialog.cpp.
Referenced by createMenuActions(), and createToolButtons().
 {
     Q_Q(QFileDialog);
     qFileDialogUi->listView->clearSelection();
     QString newFolderString = QFileDialog::tr("New Folder");
     QString folderName = newFolderString;
     QString prefix = q->directory().absolutePath() + QDir::separator();
     if (QFile::exists(prefix + folderName)) {
         qlonglong suffix = 2;
         while (QFile::exists(prefix + folderName)) {
             folderName = newFolderString + QString::number(suffix++);
         }
     }
     QModelIndex parent = rootIndex();
     QModelIndex index = model->mkdir(parent, folderName);
     if (!index.isValid())
         return;
     index = select(index);
     if (index.isValid()) {
         qFileDialogUi->treeView->setCurrentIndex(index);
         currentView()->edit(index);
     }
 }
_q_currentChanged()
void QFileDialogPrivate::_q_currentChanged (const QModelIndex & index)
Warning
This function is not part of the public interface.
Definition at line 3110 of file qfiledialog.cpp.
Referenced by createWidgets(), and QFileDialog::setProxyModel().
 {
     _q_updateOkButton();
     emit q_func()->currentChanged(index.data(QFileSystemModel::FilePathRole).toString());
 }
_q_deleteCurrent()
void QFileDialogPrivate::_q_deleteCurrent ()
Deletes the currently selected item in the dialog.
Warning
This function is not part of the public interface.
Definition at line 2930 of file qfiledialog.cpp.
Referenced by createMenuActions(), and createWidgets().
 {
     if (model->isReadOnly())
         return;
     QModelIndexList list = qFileDialogUi->listView->selectionModel()->selectedRows();
     for (int i = list.count() - 1; i >= 0; --i) {
         QModelIndex index = list.at(i);
         if (index == qFileDialogUi->listView->rootIndex())
             continue;
         index = mapToSource(index.sibling(index.row(), 0));
         if (!index.isValid())
             continue;
     QString fileName = index.data(QFileSystemModel::FileNameRole).toString();
     QString filePath = index.data(QFileSystemModel::FilePathRole).toString();
     bool isDir = model->isDir(index);
     QFile::Permissions p(index.parent().data(QFileSystemModel::FilePermissions).toInt());
 #ifndef QT_NO_MESSAGEBOX
     Q_Q(QFileDialog);
     if (!(p & QFile::WriteUser) && (QMessageBox::warning(q_func(), q_func()->windowTitle(),
                                 QFileDialog::tr("'%1' is write protected.\nDo you want to delete it anyway?")
                                 .arg(fileName),
                                  QMessageBox::Yes | QMessageBox::No, QMessageBox::No) == QMessageBox::No))
         return;
     else if (QMessageBox::warning(q_func(), q_func()->windowTitle(),
                                   QFileDialog::tr("Are sure you want to delete '%1'?")
                                   .arg(fileName),
                                   QMessageBox::Yes | QMessageBox::No, QMessageBox::No) == QMessageBox::No)
         return;
 #else
     if (!(p & QFile::WriteUser))
         return;
 #endif // QT_NO_MESSAGEBOX
         // the event loop has run, we can NOT reuse index because the model might have removed it.
         if (isDir) {
             if (!removeDirectory(filePath)) {
 #ifndef QT_NO_MESSAGEBOX
             QMessageBox::warning(q, q->windowTitle(),
                                 QFileDialog::tr("Could not delete directory."));
 #endif
             }
         } else {
             model->remove(index);
         }
     }
 }
_q_enterDirectory()
void QFileDialogPrivate::_q_enterDirectory (const QModelIndex & index)
This is called when the user double clicks on a file with the corresponding model item index.
Warning
This function is not part of the public interface.
Definition at line 3125 of file qfiledialog.cpp.
Referenced by _q_goToDirectory(), _q_goToUrl(), and createWidgets().
 {
     Q_Q(QFileDialog);
     // My Computer or a directory
     QModelIndex sourceIndex = index.model() == proxyModel ? mapToSource(index) : index;
     QString path = sourceIndex.data(QFileSystemModel::FilePathRole).toString();
     if (path.isEmpty() || model->isDir(sourceIndex)) {
         q->setDirectory(path);
         emit q->directoryEntered(path);
         if (fileMode == QFileDialog::Directory
                 || fileMode == QFileDialog::DirectoryOnly) {
             // ### find out why you have to do both of these.
             lineEdit()->setText(QString());
             lineEdit()->clear();
         }
     } else {
         // Do not accept when shift-clicking to multi-select a file in environments with single-click-activation (KDE)
         if (!q->style()->styleHint(QStyle::SH_ItemView_ActivateItemOnSingleClick)
             || q->fileMode() != QFileDialog::ExistingFiles || !(QApplication::keyboardModifiers() & Qt::CTRL)) {
             q->accept();
         }
     }
 }
_q_fileRenamed()
void QFileDialogPrivate::_q_fileRenamed (const QString & path, const QString oldName, const QString newName)
Definition at line 3306 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     if (fileMode == QFileDialog::Directory || fileMode == QFileDialog::DirectoryOnly) {
         if (path == rootPath() && lineEdit()->text() == oldName)
             lineEdit()->setText(newName);
     }
 }
_q_goHome()
void QFileDialogPrivate::_q_goHome ()
Definition at line 2719 of file qfiledialog.cpp.
Referenced by createMenuActions().
 {
     Q_Q(QFileDialog);
     q->setDirectory(QDir::homePath());
 }
_q_goToDirectory()
void QFileDialogPrivate::_q_goToDirectory (const QString & path)
Changes the file dialog's current directory to the one specified by path.
Warning
This function is not part of the public interface.
Definition at line 3158 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
  #ifndef QT_NO_MESSAGEBOX
     Q_Q(QFileDialog);
 #endif
     QModelIndex index = qFileDialogUi->lookInCombo->model()->index(qFileDialogUi->lookInCombo->currentIndex(),
                                                     qFileDialogUi->lookInCombo->modelColumn(),
                                                     qFileDialogUi->lookInCombo->rootModelIndex());
     QString path2 = path;
     if (!index.isValid())
         index = mapFromSource(model->index(getEnvironmentVariable(path)));
     else {
         path2 = index.data(UrlRole).toUrl().toLocalFile();
         index = mapFromSource(model->index(path2));
     }
     QDir dir(path2);
     if (!dir.exists())
         dir = getEnvironmentVariable(path2);
     if (dir.exists() || path2.isEmpty() || path2 == model->myComputer().toString()) {
         _q_enterDirectory(index);
 #ifndef QT_NO_MESSAGEBOX
     } else {
         QString message = QFileDialog::tr("%1\nDirectory not found.\nPlease verify the "
                                           "correct directory name was given.");
         QMessageBox::warning(q, q->windowTitle(), message.arg(path2));
 #endif // QT_NO_MESSAGEBOX
     }
 }
_q_goToUrl()
void QFileDialogPrivate::_q_goToUrl (const QUrl & url)
Warning
This function is not part of the public interface. set the directory to url
Definition at line 821 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     //The shortcut in the side bar may have a parent that is not fetched yet (e.g. an hidden file)
     //so we force the fetching
     QFileSystemModelPrivate::QFileSystemNode *node = model->d_func()->node(url.toLocalFile(), true);
     QModelIndex idx =  model->d_func()->index(node);
     _q_enterDirectory(idx);
 }
_q_macRunNativeAppModalPanel()
void QFileDialogPrivate::_q_macRunNativeAppModalPanel ()
Definition at line 1175 of file qfiledialog_mac.mm.
 {
     QBoolBlocker nativeDialogOnTop(QApplicationPrivate::native_modal_dialog_active);
 #ifndef QT_MAC_USE_COCOA
     NavDialogRun(mDialog);
 #else
     Q_Q(QFileDialog);
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     [delegate runApplicationModalPanel];
     dialogResultCode_sys() == QDialog::Accepted ? q->accept() : q->reject();
 #endif
 }
_q_navigateBackward()
void QFileDialogPrivate::_q_navigateBackward ()
Navigates to the last directory viewed in the dialog.
Warning
This function is not part of the public interface.
Definition at line 2757 of file qfiledialog.cpp.
Referenced by createToolButtons(), and itemViewKeyboardEvent().
 {
     Q_Q(QFileDialog);
     if (!currentHistory.isEmpty() && currentHistoryLocation > 0) {
         --currentHistoryLocation;
         QString previousHistory = currentHistory.at(currentHistoryLocation);
         q->setDirectory(previousHistory);
     }
 }
_q_navigateForward()
void QFileDialogPrivate::_q_navigateForward ()
Navigates to the last directory viewed in the dialog.
Warning
This function is not part of the public interface.
Definition at line 2775 of file qfiledialog.cpp.
Referenced by createToolButtons().
 {
     Q_Q(QFileDialog);
     if (!currentHistory.isEmpty() && currentHistoryLocation < currentHistory.size() - 1) {
         ++currentHistoryLocation;
         QString nextHistory = currentHistory.at(currentHistoryLocation);
         q->setDirectory(nextHistory);
     }
 }
_q_navigateToParent()
void QFileDialogPrivate::_q_navigateToParent ()
Navigates to the parent directory of the currently displayed directory in the dialog.
Warning
This function is not part of the public interface.
Definition at line 2794 of file qfiledialog.cpp.
Referenced by createMenuActions(), createToolButtons(), and itemViewKeyboardEvent().
 {
     Q_Q(QFileDialog);
     QDir dir(model->rootDirectory());
     QString newDirectory;
     if (dir.isRoot()) {
         newDirectory = model->myComputer().toString();
     } else {
         dir.cdUp();
         newDirectory = dir.absolutePath();
     }
     q->setDirectory(newDirectory);
     emit q->directoryEntered(newDirectory);
 }
_q_pathChanged()
void QFileDialogPrivate::_q_pathChanged (const QString & newPath)
Warning
This function is not part of the public interface.
Update history with new path, buttons, and combo
Definition at line 2730 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     Q_Q(QFileDialog);
     QDir dir(model->rootDirectory());
     qFileDialogUi->toParentButton->setEnabled(dir.exists());
     qFileDialogUi->sidebar->selectUrl(QUrl::fromLocalFile(newPath));
     q->setHistory(qFileDialogUi->lookInCombo->history());
     if (currentHistoryLocation < 0 || currentHistory.value(currentHistoryLocation) != QDir::toNativeSeparators(newPath)) {
         while (currentHistoryLocation >= 0 && currentHistoryLocation + 1 < currentHistory.count()) {
             currentHistory.removeLast();
         }
         currentHistory.append(QDir::toNativeSeparators(newPath));
         ++currentHistoryLocation;
     }
     qFileDialogUi->forwardButton->setEnabled(currentHistory.size() - currentHistoryLocation > 1);
     qFileDialogUi->backButton->setEnabled(currentHistoryLocation > 0);
 }
_q_renameCurrent()
void QFileDialogPrivate::_q_renameCurrent ()
Warning
This function is not part of the public interface.
Definition at line 2905 of file qfiledialog.cpp.
Referenced by createMenuActions().
 {
     Q_Q(QFileDialog);
     QModelIndex index = qFileDialogUi->listView->currentIndex();
     index = index.sibling(index.row(), 0);
     if (q->viewMode() == QFileDialog::List)
         qFileDialogUi->listView->edit(index);
     else
         qFileDialogUi->treeView->edit(index);
 }
_q_rowsInserted()
void QFileDialogPrivate::_q_rowsInserted (const QModelIndex & parent)
When parent is root and rows have been inserted when none was there before then select the first one.
Warning
This function is not part of the public interface.
Definition at line 3296 of file qfiledialog.cpp.
Referenced by createWidgets(), and QFileDialog::setProxyModel().
 {
     if (!qFileDialogUi->treeView
         || parent != qFileDialogUi->treeView->rootIndex()
         || !qFileDialogUi->treeView->selectionModel()
         || qFileDialogUi->treeView->selectionModel()->hasSelection()
         || qFileDialogUi->treeView->model()->rowCount(parent) == 0)
         return;
 }
_q_selectionChanged()
void QFileDialogPrivate::_q_selectionChanged ()
This is called when the model index corresponding to the current file is changed from index to current.
Warning
This function is not part of the public interface.
Definition at line 3245 of file qfiledialog.cpp.
Referenced by createWidgets(), and QFileDialog::setProxyModel().
 {
     QModelIndexList indexes = qFileDialogUi->listView->selectionModel()->selectedRows();
     bool stripDirs = (fileMode != QFileDialog::DirectoryOnly && fileMode != QFileDialog::Directory);
     QStringList allFiles;
     for (int i = 0; i < indexes.count(); ++i) {
         if (stripDirs && model->isDir(mapToSource(indexes.at(i))))
             continue;
         allFiles.append(indexes.at(i).data().toString());
     }
     if (allFiles.count() > 1)
         for (int i = 0; i < allFiles.count(); ++i) {
             allFiles.replace(i, QString(QLatin1Char('"') + allFiles.at(i) + QLatin1Char('"')));
     }
     QString finalFiles = allFiles.join(QLatin1String(" "));
     if (!finalFiles.isEmpty() && !lineEdit()->hasFocus() && lineEdit()->isVisible())
         lineEdit()->setText(finalFiles);
     else
         _q_updateOkButton();
 }
_q_showContextMenu()
void QFileDialogPrivate::_q_showContextMenu (const QPoint & position)
Warning
This function is not part of the public interface.
Show the context menu for the file/dir under position
Definition at line 2869 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
 #ifdef QT_NO_MENU
     Q_UNUSED(position);
 #else
     Q_Q(QFileDialog);
     QAbstractItemView *view = 0;
     if (q->viewMode() == QFileDialog::Detail)
         view = qFileDialogUi->treeView;
     else
         view = qFileDialogUi->listView;
     QModelIndex index = view->indexAt(position);
     index = mapToSource(index.sibling(index.row(), 0));
     QMenu menu(view);
     if (index.isValid()) {
         // file context menu
         QFile::Permissions p(index.parent().data(QFileSystemModel::FilePermissions).toInt());
         renameAction->setEnabled(p & QFile::WriteUser);
         menu.addAction(renameAction);
         deleteAction->setEnabled(p & QFile::WriteUser);
         menu.addAction(deleteAction);
         menu.addSeparator();
     }
     menu.addAction(showHiddenAction);
     if (qFileDialogUi->newFolderButton->isVisible()) {
         newFolderAction->setEnabled(qFileDialogUi->newFolderButton->isEnabled());
         menu.addAction(newFolderAction);
     }
     menu.exec(view->viewport()->mapToGlobal(position));
 #endif // QT_NO_MENU
 }
_q_showDetailsView()
void QFileDialogPrivate::_q_showDetailsView ()
Definition at line 2854 of file qfiledialog.cpp.
Referenced by createToolButtons().
 {
     qFileDialogUi->listModeButton->setDown(false);
     qFileDialogUi->detailModeButton->setDown(true);
     qFileDialogUi->listView->hide();
     qFileDialogUi->treeView->show();
     qFileDialogUi->stackedWidget->setCurrentWidget(qFileDialogUi->treeView->parentWidget());
     qFileDialogUi->treeView->doItemsLayout();
 }
_q_showHeader()
void QFileDialogPrivate::_q_showHeader (QAction * action)
Definition at line 2536 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     Q_Q(QFileDialog);
     QActionGroup *actionGroup = qobject_cast<QActionGroup*>(q->sender());
     qFileDialogUi->treeView->header()->setSectionHidden(actionGroup->actions().indexOf(action) + 1, !action->isChecked());
 }
_q_showHidden()
void QFileDialogPrivate::_q_showHidden ()
Includes hidden files and directories in the items displayed in the dialog.
Warning
This function is not part of the public interface.
Definition at line 3276 of file qfiledialog.cpp.
Referenced by createMenuActions().
 {
     Q_Q(QFileDialog);
     QDir::Filters dirFilters = q->filter();
     if (showHiddenAction->isChecked())
         dirFilters |= QDir::Hidden;
     else
         dirFilters &= ~QDir::Hidden;
     q->setFilter(dirFilters);
 }
_q_showListView()
void QFileDialogPrivate::_q_showListView ()
Definition at line 2844 of file qfiledialog.cpp.
Referenced by createToolButtons().
 {
     qFileDialogUi->listModeButton->setDown(true);
     qFileDialogUi->detailModeButton->setDown(false);
     qFileDialogUi->treeView->hide();
     qFileDialogUi->listView->show();
     qFileDialogUi->stackedWidget->setCurrentWidget(qFileDialogUi->listView->parentWidget());
     qFileDialogUi->listView->doItemsLayout();
 }
_q_updateOkButton()
void QFileDialogPrivate::_q_updateOkButton ()
Warning
This function is not part of the public interface.
Definition at line 3012 of file qfiledialog.cpp.
Referenced by _q_currentChanged(), _q_selectionChanged(), createWidgets(), and init().
 {
     Q_Q(QFileDialog);
     QPushButton *button =  qFileDialogUi->buttonBox->button((acceptMode == QFileDialog::AcceptOpen)
                     ? QDialogButtonBox::Open : QDialogButtonBox::Save);
     if (!button)
         return;
     bool enableButton = true;
     bool isOpenDirectory = false;
     QStringList files = q->selectedFiles();
     QString lineEditText = lineEdit()->text();
     if (lineEditText.startsWith(QLatin1String("//")) || lineEditText.startsWith(QLatin1Char('\\'))) {
         button->setEnabled(true);
         if (acceptMode == QFileDialog::AcceptSave)
             button->setText(acceptLabel);
         return;
     }
     if (files.isEmpty()) {
         enableButton = false;
     } else if (lineEditText == QLatin1String("..")) {
         isOpenDirectory = true;
     } else {
         switch (fileMode) {
         case QFileDialog::DirectoryOnly:
         case QFileDialog::Directory: {
             QString fn = files.first();
             QModelIndex idx = model->index(fn);
             if (!idx.isValid())
                 idx = model->index(getEnvironmentVariable(fn));
             if (!idx.isValid() || !model->isDir(idx))
                 enableButton = false;
             break;
         }
         case QFileDialog::AnyFile: {
             QString fn = files.first();
             QFileInfo info(fn);
             QModelIndex idx = model->index(fn);
             QString fileDir;
             QString fileName;
             if (info.isDir()) {
                 fileDir = info.canonicalFilePath();
             } else {
                 fileDir = fn.mid(0, fn.lastIndexOf(QLatin1Char('/')));
                 fileName = fn.mid(fileDir.length() + 1);
             }
             if (lineEditText.contains(QLatin1String(".."))) {
                 fileDir = info.canonicalFilePath();
                 fileName = info.fileName();
             }
             if (fileDir == q->directory().canonicalPath() && fileName.isEmpty()) {
                 enableButton = false;
                 break;
             }
             if (idx.isValid() && model->isDir(idx)) {
                 isOpenDirectory = true;
                 enableButton = true;
                 break;
             }
             if (!idx.isValid()) {
                 int maxLength = maxNameLength(fileDir);
                 enableButton = maxLength < 0 || fileName.length() <= maxLength;
             }
             break;
         }
         case QFileDialog::ExistingFile:
         case QFileDialog::ExistingFiles:
             for (int i = 0; i < files.count(); ++i) {
                 QModelIndex idx = model->index(files.at(i));
                 if (!idx.isValid())
                     idx = model->index(getEnvironmentVariable(files.at(i)));
                 if (!idx.isValid()) {
                     enableButton = false;
                     break;
                 }
                 if (idx.isValid() && model->isDir(idx)) {
                     isOpenDirectory = true;
                     break;
                 }
             }
             break;
         default:
             break;
         }
     }
     button->setEnabled(enableButton);
     if (acceptMode == QFileDialog::AcceptSave)
         button->setText(isOpenDirectory ? QFileDialog::tr("&Open") : acceptLabel);
 }
_q_useNameFilter()
void QFileDialogPrivate::_q_useNameFilter (int index)
Sets the current name filter to be nameFilter and update the qFileDialogUi->fileNameEdit when in AcceptSave mode with the new extension.
Warning
This function is not part of the public interface.
Definition at line 3208 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     if (index == nameFilters.size()) {
         QAbstractItemModel *comboModel = qFileDialogUi->fileTypeCombo->model();
         nameFilters.append(comboModel->index(comboModel->rowCount() - 1, 0).data().toString());
     }
     QString nameFilter = nameFilters.at(index);
     QStringList newNameFilters = qt_clean_filter_list(nameFilter);
     if (acceptMode == QFileDialog::AcceptSave) {
         QString newNameFilterExtension;
         if (newNameFilters.count() > 0)
             newNameFilterExtension = QFileInfo(newNameFilters.at(0)).suffix();
         QString fileName = lineEdit()->text();
         const QString fileNameExtension = QFileInfo(fileName).suffix();
         if (!fileNameExtension.isEmpty() && !newNameFilterExtension.isEmpty()) {
             const int fileNameExtensionLength = fileNameExtension.count();
             fileName.replace(fileName.count() - fileNameExtensionLength,
                              fileNameExtensionLength, newNameFilterExtension);
             qFileDialogUi->listView->clearSelection();
             lineEdit()->setText(fileName);
         }
     }
     model->setNameFilters(newNameFilters);
 }
addDefaultSuffixToFiles()
QStringList QFileDialogPrivate::addDefaultSuffixToFiles (const QStringList filesToFix) const
Definition at line 1019 of file qfiledialog.cpp.
Referenced by typedFiles().
 {
     QStringList files;
     for (int i=0; i<filesToFix.size(); ++i) {
         QString name = toInternal(filesToFix.at(i));
         QFileInfo info(name);
         // if the filename has no suffix, add the default suffix
         if (!defaultSuffix.isEmpty() && !info.isDir() && name.lastIndexOf(QLatin1Char('.')) == -1)
             name += QLatin1Char('.') + defaultSuffix;
         if (info.isAbsolute()) {
             files.append(name);
         } else {
             // at this point the path should only have Qt path separators.
             // This check is needed since we might be at the root directory
             // and on Windows it already ends with slash.
             QString path = rootPath();
             if (!path.endsWith(QLatin1Char('/')))
                 path += QLatin1Char('/');
             path += name;
             files.append(path);
         }
     }
     return files;
 }
basename()
QString QFileDialogPrivate::basename (const QString & path) const inline
Definition at line 162 of file qfiledialog_p.h.
     {
         int separator = QDir::toNativeSeparators(path).lastIndexOf(QDir::separator());
         if (separator != -1)
             return path.mid(separator + 1);
         return path;
     }
canBeNativeDialog()
bool QFileDialogPrivate::canBeNativeDialog ()
Definition at line 650 of file qfiledialog.cpp.
 {
     Q_Q(QFileDialog);
     if (nativeDialogInUse)
         return true;
     if (q->testAttribute(Qt::WA_DontShowOnScreen))
         return false;
     if (opts & QFileDialog::DontUseNativeDialog)
         return false;
     QLatin1String staticName(QFileDialog::staticMetaObject.className());
     QLatin1String dynamicName(q->metaObject()->className());
     return (staticName == dynamicName);
 }
createMenuActions()
void QFileDialogPrivate::createMenuActions ()
Create actions which will be used in the right click.
Warning
This function is not part of the public interface.
Definition at line 2678 of file qfiledialog.cpp.
Referenced by init().
 {
     Q_Q(QFileDialog);
     QAction *goHomeAction =  new QAction(q);
 #ifndef QT_NO_SHORTCUT
     goHomeAction->setShortcut(Qt::CTRL + Qt::Key_H + Qt::SHIFT);
 #endif
     QObject::connect(goHomeAction, SIGNAL(triggered()), q, SLOT(_q_goHome()));
     q->addAction(goHomeAction);
     // ### TODO add Desktop & Computer actions
     QAction *goToParent =  new QAction(q);
     goToParent->setObjectName(QLatin1String("qt_goto_parent_action"));
 #ifndef QT_NO_SHORTCUT
     goToParent->setShortcut(Qt::CTRL + Qt::UpArrow);
 #endif
     QObject::connect(goToParent, SIGNAL(triggered()), q, SLOT(_q_navigateToParent()));
     q->addAction(goToParent);
     renameAction = new QAction(q);
     renameAction->setEnabled(false);
     renameAction->setObjectName(QLatin1String("qt_rename_action"));
     QObject::connect(renameAction, SIGNAL(triggered()), q, SLOT(_q_renameCurrent()));
     deleteAction = new QAction(q);
     deleteAction->setEnabled(false);
     deleteAction->setObjectName(QLatin1String("qt_delete_action"));
     QObject::connect(deleteAction, SIGNAL(triggered()), q, SLOT(_q_deleteCurrent()));
     showHiddenAction = new QAction(q);
     showHiddenAction->setObjectName(QLatin1String("qt_show_hidden_action"));
     showHiddenAction->setCheckable(true);
     QObject::connect(showHiddenAction, SIGNAL(triggered()), q, SLOT(_q_showHidden()));
     newFolderAction = new QAction(q);
     newFolderAction->setObjectName(QLatin1String("qt_new_folder_action"));
     QObject::connect(newFolderAction, SIGNAL(triggered()), q, SLOT(_q_createDirectory()));
 }
createNavServicesDialog()
void QFileDialogPrivate::createNavServicesDialog ()
Definition at line 998 of file qfiledialog_mac.mm.
 {
     Q_Q(QFileDialog);
     if (mDialog)
         deleteNativeDialog_sys();
     NavDialogCreationOptions navOptions;
     NavGetDefaultDialogCreationOptions(&navOptions);
     // Translate QFileDialog settings into NavDialog options:
     if (qt_mac_is_macsheet(q)) {
         navOptions.modality = kWindowModalityWindowModal;
         navOptions.parentWindow = qt_mac_window_for(q->parentWidget());
     } else if (q->windowModality() ==  Qt::ApplicationModal)
         navOptions.modality = kWindowModalityAppModal;
     else
         navOptions.modality = kWindowModalityNone;
     navOptions.optionFlags |= kNavSupportPackages;
     if (q->testOption(QFileDialog::DontConfirmOverwrite))
         navOptions.optionFlags |= kNavDontConfirmReplacement;
     if (fileMode != QFileDialog::ExistingFiles)
         navOptions.optionFlags &= ~kNavAllowMultipleFiles;
     navOptions.windowTitle = QCFString::toCFStringRef(q->windowTitle());
     navOptions.location.h = -1;
     navOptions.location.v = -1;
     QWidget *parent = q->parentWidget();
     if (parent && parent->isVisible()) {
         WindowClass wclass;
         GetWindowClass(qt_mac_window_for(parent), &wclass);
         parent = parent->window();
         QString s = parent->windowTitle();
         navOptions.clientName = QCFString::toCFStringRef(s);
     }
     filterInfo.currentSelection = 0;
     filterInfo.filters = qt_mac_make_filters_list(nameFilters.join(QLatin1String(";;")), q->isNameFilterDetailsVisible());
     QCFType<CFArrayRef> filterArray;
     if (filterInfo.filters.size() > 1) {
         int i = 0;
         CFStringRef *cfstringArray = static_cast<CFStringRef *>(malloc(sizeof(CFStringRef)
                                                                    * filterInfo.filters.size()));
         for (i = 0; i < filterInfo.filters.size(); ++i) {
             cfstringArray[i] = QCFString::toCFStringRef(filterInfo.filters.at(i).description);
         }
         filterArray = CFArrayCreate(kCFAllocatorDefault,
                         reinterpret_cast<const void **>(cfstringArray), filterInfo.filters.size(),
                         &kCFTypeArrayCallBacks);
         navOptions.popupExtension = filterArray;
         free(cfstringArray);
     }
     if (q->acceptMode() == QFileDialog::AcceptSave) {
         if (NavCreatePutFileDialog(&navOptions, 'cute', kNavGenericSignature,
                     QFileDialogPrivate::qt_mac_filedialog_event_proc, this, &mDialog)) {
             qDebug("Shouldn't happen %s:%d", __FILE__, __LINE__);
             return;
         }
     } else if (fileMode == QFileDialog::DirectoryOnly || fileMode == QFileDialog::Directory) {
         if (NavCreateChooseFolderDialog(&navOptions,
                     QFileDialogPrivate::qt_mac_filedialog_event_proc, 0, this, &mDialog)) {
             qDebug("Shouldn't happen %s:%d", __FILE__, __LINE__);
             return;
         }
     } else {
         if (NavCreateGetFileDialog(&navOptions, 0,
                     QFileDialogPrivate::qt_mac_filedialog_event_proc, 0,
                     QFileDialogPrivate::qt_mac_filedialog_filter_proc, this, &mDialog)) {
             qDebug("Shouldn't happen %s:%d", __FILE__, __LINE__);
             return;
         }
     }
     // Set start-up directory:
     if (mCurrentLocation.isEmpty())
         mCurrentLocation = rootPath();
     FSRef fsRef;
     if (qt_mac_create_fsref(mCurrentLocation, &fsRef) == noErr) {
         AEDesc desc;
         if (AECreateDesc(typeFSRef, &fsRef, sizeof(FSRef), &desc) == noErr)
             NavCustomControl(mDialog, kNavCtlSetLocation, (void*)&desc);
     }
 }
createNSOpenSavePanelDelegate()
void QFileDialogPrivate::createNSOpenSavePanelDelegate ()
Referenced by hideCarbonNavServicesDialog().
createToolButtons()
void QFileDialogPrivate::createToolButtons ()
Warning
This function is not part of the public interface.
Create tool buttons, set properties and connections
Definition at line 2629 of file qfiledialog.cpp.
Referenced by createWidgets().
 {
     Q_Q(QFileDialog);
     qFileDialogUi->backButton->setIcon(q->style()->standardIcon(QStyle::SP_ArrowBack, 0, q));
     qFileDialogUi->backButton->setAutoRaise(true);
     qFileDialogUi->backButton->setEnabled(false);
     QObject::connect(qFileDialogUi->backButton, SIGNAL(clicked()), q, SLOT(_q_navigateBackward()));
     qFileDialogUi->forwardButton->setIcon(q->style()->standardIcon(QStyle::SP_ArrowForward, 0, q));
     qFileDialogUi->forwardButton->setAutoRaise(true);
     qFileDialogUi->forwardButton->setEnabled(false);
     QObject::connect(qFileDialogUi->forwardButton, SIGNAL(clicked()), q, SLOT(_q_navigateForward()));
     qFileDialogUi->toParentButton->setIcon(q->style()->standardIcon(QStyle::SP_FileDialogToParent, 0, q));
     qFileDialogUi->toParentButton->setAutoRaise(true);
     qFileDialogUi->toParentButton->setEnabled(false);
     QObject::connect(qFileDialogUi->toParentButton, SIGNAL(clicked()), q, SLOT(_q_navigateToParent()));
     qFileDialogUi->listModeButton->setIcon(q->style()->standardIcon(QStyle::SP_FileDialogListView, 0, q));
     qFileDialogUi->listModeButton->setAutoRaise(true);
     qFileDialogUi->listModeButton->setDown(true);
     QObject::connect(qFileDialogUi->listModeButton, SIGNAL(clicked()), q, SLOT(_q_showListView()));
     qFileDialogUi->detailModeButton->setIcon(q->style()->standardIcon(QStyle::SP_FileDialogDetailedView, 0, q));
     qFileDialogUi->detailModeButton->setAutoRaise(true);
     QObject::connect(qFileDialogUi->detailModeButton, SIGNAL(clicked()), q, SLOT(_q_showDetailsView()));
     QSize toolSize(qFileDialogUi->fileNameEdit->sizeHint().height(), qFileDialogUi->fileNameEdit->sizeHint().height());
     qFileDialogUi->backButton->setFixedSize(toolSize);
     qFileDialogUi->listModeButton->setFixedSize(toolSize);
     qFileDialogUi->detailModeButton->setFixedSize(toolSize);
     qFileDialogUi->forwardButton->setFixedSize(toolSize);
     qFileDialogUi->toParentButton->setFixedSize(toolSize);
     qFileDialogUi->newFolderButton->setIcon(q->style()->standardIcon(QStyle::SP_FileDialogNewFolder, 0, q));
     qFileDialogUi->newFolderButton->setFixedSize(toolSize);
     qFileDialogUi->newFolderButton->setAutoRaise(true);
     qFileDialogUi->newFolderButton->setEnabled(false);
     QObject::connect(qFileDialogUi->newFolderButton, SIGNAL(clicked()), q, SLOT(_q_createDirectory()));
 }
createWidgets()
void QFileDialogPrivate::createWidgets ()
Warning
This function is not part of the public interface.
Create the widgets, set properties and connections
Definition at line 2410 of file qfiledialog.cpp.
Referenced by init().
 {
     Q_Q(QFileDialog);
     model = new QFileSystemModel(q);
     model->setObjectName(QLatin1String("qt_filesystem_model"));
 #ifdef Q_WS_MAC
     model->setNameFilterDisables(true);
 #else
     model->setNameFilterDisables(false);
 #endif
     model->d_func()->disableRecursiveSort = true;
     QFileDialog::connect(model, SIGNAL(fileRenamed(QString,QString,QString)), q, SLOT(_q_fileRenamed(QString,QString,QString)));
     QFileDialog::connect(model, SIGNAL(rootPathChanged(QString)),
             q, SLOT(_q_pathChanged(QString)));
     QFileDialog::connect(model, SIGNAL(rowsInserted(QModelIndex,int,int)),
             q, SLOT(_q_rowsInserted(QModelIndex)));
     model->setReadOnly(false);
     qFileDialogUi.reset(new Ui_QFileDialog());
     qFileDialogUi->setupUi(q);
     QList<QUrl> initialBookmarks;
     initialBookmarks << QUrl::fromLocalFile(QLatin1String(""))
                      << QUrl::fromLocalFile(QDir::homePath());
     qFileDialogUi->sidebar->init(model, initialBookmarks);
     QFileDialog::connect(qFileDialogUi->sidebar, SIGNAL(goToUrl(QUrl)),
                          q, SLOT(_q_goToUrl(QUrl)));
     QObject::connect(qFileDialogUi->buttonBox, SIGNAL(accepted()), q, SLOT(accept()));
     QObject::connect(qFileDialogUi->buttonBox, SIGNAL(rejected()), q, SLOT(reject()));
     qFileDialogUi->lookInCombo->init(this);
     QObject::connect(qFileDialogUi->lookInCombo, SIGNAL(activated(QString)), q, SLOT(_q_goToDirectory(QString)));
     qFileDialogUi->lookInCombo->setInsertPolicy(QComboBox::NoInsert);
     qFileDialogUi->lookInCombo->setDuplicatesEnabled(false);
     // filename
     qFileDialogUi->fileNameEdit->init(this);
 #ifndef QT_NO_SHORTCUT
     qFileDialogUi->fileNameLabel->setBuddy(qFileDialogUi->fileNameEdit);
 #endif
 #ifndef QT_NO_FSCOMPLETER
     completer = new QFSCompleter(model, q);
     qFileDialogUi->fileNameEdit->setCompleter(completer);
 #endif // QT_NO_FSCOMPLETER
     QObject::connect(qFileDialogUi->fileNameEdit, SIGNAL(textChanged(QString)),
             q, SLOT(_q_autoCompleteFileName(QString)));
     QObject::connect(qFileDialogUi->fileNameEdit, SIGNAL(textChanged(QString)),
                      q, SLOT(_q_updateOkButton()));
     QObject::connect(qFileDialogUi->fileNameEdit, SIGNAL(returnPressed()), q, SLOT(accept()));
     // filetype
     qFileDialogUi->fileTypeCombo->setDuplicatesEnabled(false);
     qFileDialogUi->fileTypeCombo->setSizeAdjustPolicy(QComboBox::AdjustToMinimumContentsLength);
     qFileDialogUi->fileTypeCombo->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);
     QObject::connect(qFileDialogUi->fileTypeCombo, SIGNAL(activated(int)),
                      q, SLOT(_q_useNameFilter(int)));
     QObject::connect(qFileDialogUi->fileTypeCombo, SIGNAL(activated(QString)),
                      q, SIGNAL(filterSelected(QString)));
     qFileDialogUi->listView->init(this);
     qFileDialogUi->listView->setModel(model);
     QObject::connect(qFileDialogUi->listView, SIGNAL(activated(QModelIndex)),
                      q, SLOT(_q_enterDirectory(QModelIndex)));
     QObject::connect(qFileDialogUi->listView, SIGNAL(customContextMenuRequested(QPoint)),
                     q, SLOT(_q_showContextMenu(QPoint)));
 #ifndef QT_NO_SHORTCUT
     QShortcut *shortcut = new QShortcut(qFileDialogUi->listView);
     shortcut->setKey(QKeySequence(QLatin1String("Delete")));
     QObject::connect(shortcut, SIGNAL(activated()), q, SLOT(_q_deleteCurrent()));
 #endif
     qFileDialogUi->treeView->init(this);
     qFileDialogUi->treeView->setModel(model);
     QHeaderView *treeHeader = qFileDialogUi->treeView->header();
     QFontMetrics fm(q->font());
     treeHeader->resizeSection(0, fm.width(QLatin1String("wwwwwwwwwwwwwwwwwwwwwwwwww")));
     treeHeader->resizeSection(1, fm.width(QLatin1String("128.88 GB")));
     treeHeader->resizeSection(2, fm.width(QLatin1String("mp3Folder")));
     treeHeader->resizeSection(3, fm.width(QLatin1String("10/29/81 02:02PM")));
     treeHeader->setContextMenuPolicy(Qt::ActionsContextMenu);
     QActionGroup *showActionGroup = new QActionGroup(q);
     showActionGroup->setExclusive(false);
     QObject::connect(showActionGroup, SIGNAL(triggered(QAction*)),
                      q, SLOT(_q_showHeader(QAction*)));;
     QAbstractItemModel *abstractModel = model;
 #ifndef QT_NO_PROXYMODEL
     if (proxyModel)
         abstractModel = proxyModel;
 #endif
     for (int i = 1; i < abstractModel->columnCount(QModelIndex()); ++i) {
         QAction *showHeader = new QAction(showActionGroup);
         showHeader->setCheckable(true);
         showHeader->setChecked(true);
         treeHeader->addAction(showHeader);
     }
     QScopedPointer<QItemSelectionModel> selModel(qFileDialogUi->treeView->selectionModel());
     qFileDialogUi->treeView->setSelectionModel(qFileDialogUi->listView->selectionModel());
     QObject::connect(qFileDialogUi->treeView, SIGNAL(activated(QModelIndex)),
                      q, SLOT(_q_enterDirectory(QModelIndex)));
     QObject::connect(qFileDialogUi->treeView, SIGNAL(customContextMenuRequested(QPoint)),
                      q, SLOT(_q_showContextMenu(QPoint)));
 #ifndef QT_NO_SHORTCUT
     shortcut = new QShortcut(qFileDialogUi->treeView);
     shortcut->setKey(QKeySequence(QLatin1String("Delete")));
     QObject::connect(shortcut, SIGNAL(activated()), q, SLOT(_q_deleteCurrent()));
 #endif
     // Selections
     QItemSelectionModel *selections = qFileDialogUi->listView->selectionModel();
     QObject::connect(selections, SIGNAL(selectionChanged(QItemSelection,QItemSelection)),
                      q, SLOT(_q_selectionChanged()));
     QObject::connect(selections, SIGNAL(currentChanged(QModelIndex,QModelIndex)),
                      q, SLOT(_q_currentChanged(QModelIndex)));
     qFileDialogUi->splitter->setStretchFactor(qFileDialogUi->splitter->indexOf(qFileDialogUi->splitter->widget(1)), QSizePolicy::Expanding);
     createToolButtons();
 }
currentView()
QAbstractItemView * QFileDialogPrivate::currentView () const
Definition at line 1508 of file qfiledialog.cpp.
Referenced by _q_createDirectory(), and QFileDialogLineEdit::keyPressEvent().
{
     if (!qFileDialogUi->stackedWidget)
         return 0;
     if (qFileDialogUi->stackedWidget->currentWidget() == qFileDialogUi->listView->parent())
         return qFileDialogUi->listView;
     return qFileDialogUi->treeView;
 }
deleteNativeDialog_sys()
void QFileDialogPrivate::deleteNativeDialog_sys ()
Definition at line 758 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     if (mDialog)
         NavDialogDispose(mDialog);
     mDialog = 0;
     mDialogStarted = false;
 #else
     QMacCocoaAutoReleasePool pool;
     [reinterpret_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate) release];
     mDelegate = 0;
 #endif
     nativeDialogInUse = false;
 }
dialogResultCode_sys()
QDialog::DialogCode QFileDialogPrivate::dialogResultCode_sys ()
Definition at line 1189 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     NavUserAction result = NavDialogGetUserAction(mDialog);
     if (result == kNavUserActionCancel || result == kNavUserActionNone)
         return QDialog::Rejected;
     else
         return QDialog::Accepted;
 #else
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     return [delegate dialogResultCode];
 #endif
 }
directory_sys()
QString QFileDialogPrivate::directory_sys () const
Definition at line 630 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     return mCurrentLocation;
 #else
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     return qt_mac_NSStringToQString([delegate->mSavePanel directory]);
 #endif
 }
emitFilesSelected()
void QFileDialogPrivate::emitFilesSelected (const QStringList & files)
Definition at line 642 of file qfiledialog.cpp.
 {
     Q_Q(QFileDialog);
     emit q->filesSelected(files);
     if (files.count() == 1)
         emit q->fileSelected(files.first());
 }
filterForMode()
QDir::Filters QFileDialogPrivate::filterForMode (QDir::Filters filters) const inline
Definition at line 170 of file qfiledialog_p.h.
     {
         if (fileMode == QFileDialog::DirectoryOnly) {
             filters |= QDir::Drives | QDir::AllDirs | QDir::Dirs;
             filters &= ~QDir::Files;
         } else {
             filters |= QDir::Drives | QDir::AllDirs | QDir::Files | QDir::Dirs;
         }
         return filters;
     }
getEnvironmentVariable()
QString QFileDialogPrivate::getEnvironmentVariable (const QString & string)
Definition at line 3348 of file qfiledialog.cpp.
Referenced by _q_goToDirectory(), and _q_updateOkButton().
 {
 #ifdef Q_OS_UNIX
     if (string.size() > 1 && string.startsWith(QLatin1Char('$'))) {
         return QString::fromLocal8Bit(getenv(string.mid(1).toLatin1().constData()));
     }
 #else
     if (string.size() > 2 && string.startsWith(QLatin1Char('%')) && string.endsWith(QLatin1Char('%'))) {
         return QString::fromLocal8Bit(qgetenv(string.mid(1, string.size() - 2).toLatin1().constData()));
     }
 #endif
     return string;
 }
hideCarbonNavServicesDialog()
bool QFileDialogPrivate::hideCarbonNavServicesDialog ()
Definition at line 1096 of file qfiledialog_mac.mm.
 {
     if (!mDialogClosed){
         mDialogClosed = true;
         NavCustomControl(mDialog, kNavCtlCancel, 0);
     }
     return true;
 }
init()
void QFileDialogPrivate::init (const QString & directory = QString(), const QString & nameFilter = QString(), const QString & caption = QString())
Warning
This function is not part of the public interface.
Create widgets, layout and set default values
Definition at line 2365 of file qfiledialog.cpp.
 {
     Q_Q(QFileDialog);
     if (!caption.isEmpty()) {
         useDefaultCaption = false;
         setWindowTitle = caption;
         q->setWindowTitle(caption);
     }
     createWidgets();
     createMenuActions();
     retranslateStrings();
     q->setFileMode(fileMode);
 #ifndef QT_NO_SETTINGS
     QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
     settings.beginGroup(QLatin1String("Qt"));
     if (!directory.isEmpty())
         setLastVisitedDirectory(workingDirectory(directory));
     q->restoreState(settings.value(QLatin1String("filedialog")).toByteArray());
 #endif
 #if defined(Q_EMBEDDED_SMALLSCREEN)
     qFileDialogUi->lookInLabel->setVisible(false);
     qFileDialogUi->fileNameLabel->setVisible(false);
     qFileDialogUi->fileTypeLabel->setVisible(false);
     qFileDialogUi->sidebar->hide();
 #endif
     // Default case
     if (!nameFilter.isEmpty())
         q->setNameFilter(nameFilter);
     q->setAcceptMode(QFileDialog::AcceptOpen);
     q->setDirectory(workingDirectory(directory));
     q->selectFile(initialSelection(directory));
     _q_updateOkButton();
     q->resize(q->sizeHint());
 }
initialSelection()
QString QFileDialogPrivate::initialSelection (const QString & path) static
Definition at line 2225 of file qfiledialog.cpp.
Referenced by QFileDialog::getOpenFileName(), QFileDialog::getOpenFileNames(), QFileDialog::getSaveFileName(), and init().
 {
     if (!path.isEmpty()) {
         QFileInfo info(path);
         if (!info.isDir())
             return info.fileName();
     }
     return QString();
 }
itemViewKeyboardEvent()
bool QFileDialogPrivate::itemViewKeyboardEvent (QKeyEvent * event)
Warning
This function is not part of the public interface.
For the list and tree view watch keys to goto parent and back in the history
returns true if handled
Definition at line 3321 of file qfiledialog.cpp.
Referenced by QFileDialogListView::keyPressEvent(), and QFileDialogTreeView::keyPressEvent().
{
     Q_Q(QFileDialog);
     switch (event->key()) {
     case Qt::Key_Backspace:
         _q_navigateToParent();
         return true;
     case Qt::Key_Back:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled())
             return false;
 #endif
     case Qt::Key_Left:
         if (event->key() == Qt::Key_Back || event->modifiers() == Qt::AltModifier) {
             _q_navigateBackward();
             return true;
         }
         break;
     case Qt::Key_Escape:
         q->hide();
         return true;
     default:
         break;
     }
     return false;
 }
lineEdit()
QLineEdit * QFileDialogPrivate::lineEdit () const
Definition at line 1516 of file qfiledialog.cpp.
Referenced by _q_autoCompleteFileName(), _q_enterDirectory(), _q_fileRenamed(), _q_selectionChanged(), _q_updateOkButton(), _q_useNameFilter(), and typedFiles().
{
     return (QLineEdit*)qFileDialogUi->fileNameEdit;
 }
mac_nativeDialogModalHelp()
void QFileDialogPrivate::mac_nativeDialogModalHelp () virtual
Reimplemented from QDialogPrivate.
Definition at line 1160 of file qfiledialog_mac.mm.
 {
     // Do a queued meta-call to open the native modal dialog so it opens after the new
     // event loop has started to execute (in QDialog::exec). Using a timer rather than
     // a queued meta call is intentional to ensure that the call is only delivered when
     // [NSApp run] runs (timers are handeled special in cocoa). If NSApp is not
     // running (which is the case if e.g a top-most QEventLoop has been
     // interrupted, and the second-most event loop has not yet been reactivated (regardless
     // if [NSApp run] is still on the stack)), showing a native modal dialog will fail.
     if (nativeDialogInUse){
         Q_Q(QFileDialog);
         QTimer::singleShot(1, q, SLOT(_q_macRunNativeAppModalPanel()));
     }
 }
mapFromSource()
QModelIndex QFileDialogPrivate::mapFromSource (const QModelIndex & index) const inline
Definition at line 396 of file qfiledialog_p.h.
Referenced by _q_goToDirectory(), select(), and setRootIndex().
{
 #ifdef QT_NO_PROXYMODEL
     return index;
 #else
     return proxyModel ? proxyModel->mapFromSource(index) : index;
 #endif
 }
mapToSource()
QModelIndex QFileDialogPrivate::mapToSource (const QModelIndex & index) const inline
Definition at line 389 of file qfiledialog_p.h.
Referenced by _q_deleteCurrent(), _q_enterDirectory(), _q_selectionChanged(), _q_showContextMenu(), and rootIndex().
{
 #ifdef QT_NO_PROXYMODEL
     return index;
 #else
     return proxyModel ? proxyModel->mapToSource(index) : index;
 #endif
 }
maxNameLength()
int QFileDialogPrivate::maxNameLength (const QString & path) inline
Definition at line 142 of file qfiledialog_p.h.
Referenced by _q_updateOkButton(), and QFileDialog::accept().
{
 #if defined(Q_OS_UNIX)
         return ::pathconf(QFile::encodeName(path).data(), _PC_NAME_MAX);
 #elif defined(Q_OS_WIN)
 #ifndef Q_OS_WINCE
         DWORD maxLength;
         QString drive = path.left(3);
         if (::GetVolumeInformation(reinterpret_cast<const wchar_t *>(drive.utf16()), NULL, 0, NULL, &maxLength, NULL, NULL, 0) == FALSE)
             return -1;
         return maxLength;
 #else
         Q_UNUSED(path);
         return MAX_PATH;
 #endif //Q_OS_WINCE
 #else
         Q_UNUSED(path);
 #endif
         return -1;
     }
QNSOpenSavePanelDelegate_directoryEntered()
void QFileDialogPrivate::QNSOpenSavePanelDelegate_directoryEntered (const QString & newDir)
Definition at line 598 of file qfiledialog_mac.mm.
 {
     setLastVisitedDirectory(newDir);
     emit q_func()->directoryEntered(newDir);
 }
QNSOpenSavePanelDelegate_filterSelected()
void QFileDialogPrivate::QNSOpenSavePanelDelegate_filterSelected (int menuIndex)
Definition at line 604 of file qfiledialog_mac.mm.
 {
     emit q_func()->filterSelected(nameFilters.at(menuIndex));
 }
QNSOpenSavePanelDelegate_panelClosed()
void QFileDialogPrivate::QNSOpenSavePanelDelegate_panelClosed (bool accepted)
Definition at line 590 of file qfiledialog_mac.mm.
 {
     if (accepted)
         q_func()->accept();
     else
         q_func()->reject();
 }
QNSOpenSavePanelDelegate_selectionChanged()
void QFileDialogPrivate::QNSOpenSavePanelDelegate_selectionChanged (const QString & newPath)
Definition at line 585 of file qfiledialog_mac.mm.
 {
     emit q_func()->currentChanged(newPath);
 }
qt_mac_filedialog_event_proc()
void QFileDialogPrivate::qt_mac_filedialog_event_proc (const NavEventCallbackMessage msg, NavCBRecPtr p, NavCallBackUserData data) static
Definition at line 842 of file qfiledialog_mac.mm.
Referenced by createNavServicesDialog().
 {
     QFileDialogPrivate *fileDialogPrivate = static_cast<QFileDialogPrivate *>(data);
     switch(msg) {
     case kNavCBPopupMenuSelect: {
         NavMenuItemSpec *s = static_cast<NavMenuItemSpec *>(p->eventData.eventDataParms.param);
         if (int(s->menuType) != fileDialogPrivate->filterInfo.currentSelection) {
             fileDialogPrivate->filterInfo.currentSelection = s->menuType;
             emit fileDialogPrivate->q_func()->filterSelected(fileDialogPrivate->nameFilters.at(s->menuType));
         }
         if (fileDialogPrivate->acceptMode == QFileDialog::AcceptSave) {
             QString base = QCFString::toQString(NavDialogGetSaveFileName(p->context));
             QFileInfo fi(base);
             base = fi.completeBaseName();
             const QtMacFilterName &fn = fileDialogPrivate->filterInfo.filters.at(
                                                        fileDialogPrivate->filterInfo.currentSelection);
             QStringList reg = fn.regexp.split(QLatin1String(";"), QString::SkipEmptyParts);
             if (reg.count()) {
                 QString r = reg.first();
                 r  = r.right(r.length()-1);      // Strip the *
                 base += r;                        //"." + QString::number(s->menuType);
             }
             NavDialogSetSaveFileName(p->context, QCFString::toCFStringRef(base));
         }
 #ifdef DEBUG_FILEDIALOG_FILTERS
         qDebug("QFileDialogPrivate::qt_mac_filedialog_event_proc:%d - Selected a filter: %ld", __LINE__, s->menuType);
 #endif
         break; }
     case kNavCBStart:{
         fileDialogPrivate->mDialogStarted = true;
         // Set selected file:
         QModelIndexList indexes = fileDialogPrivate->qFileDialogUi->listView->selectionModel()->selectedRows();
         QString selected;
         if (!indexes.isEmpty())
             selected = indexes.at(0).data(QFileSystemModel::FilePathRole).toString();
         else
             selected = fileDialogPrivate->typedFiles().value(0);
         fileDialogPrivate->selectFile_sys(selected);
         fileDialogPrivate->selectNameFilter_sys(fileDialogPrivate->qFileDialogUi->fileTypeCombo->currentText());
         break; }
     case kNavCBSelectEntry:{
         // Event: Current selection has changed.
         QStringList prevSelectionList = fileDialogPrivate->mCurrentSelectionList;
         fileDialogPrivate->mCurrentSelectionList.clear();
         QString fileNameToEmit;
         AEDescList *descList = (AEDescList *)p->eventData.eventDataParms.param;
         // Get the number of files selected:
         UInt8 strBuffer[1024];
         long count;
         OSErr err = AECountItems(descList, &count);
         if (err != noErr || !count)
             break;
         for (long index=1; index<=count; ++index) {
             FSRef ref;
             err = AEGetNthPtr(descList, index, typeFSRef, 0, 0, &ref, sizeof(ref), 0);
             if (err != noErr)
                 break;
             FSRefMakePath(&ref, strBuffer, 1024);
             QString selected = QString::fromUtf8((const char *)strBuffer);
             fileDialogPrivate->mCurrentSelectionList << selected;
             if (!prevSelectionList.contains(selected))
                 fileNameToEmit = selected;
         }
         if (!fileNameToEmit.isEmpty() && fileNameToEmit != fileDialogPrivate->mCurrentSelection)
             emit fileDialogPrivate->q_func()->currentChanged(fileNameToEmit);
         fileDialogPrivate->mCurrentSelection = fileNameToEmit;
         break; }
     case kNavCBShowDesktop:
     case kNavCBNewLocation:{
         // Event: Current directory has changed.
         AEDesc *desc = (AEDesc *)p->eventData.eventDataParms.param;
         FSRef ref;
         AEGetDescData(desc, &ref, sizeof(ref));
         UInt8 *strBuffer = (UInt8 *)malloc(1024);
         FSRefMakePath(&ref, strBuffer, 1024);
         QString newLocation = QString::fromUtf8((const char *)strBuffer);
         free(strBuffer);
         if (fileDialogPrivate->mCurrentLocation != newLocation){
             fileDialogPrivate->mCurrentLocation = newLocation;
             QFileDialog::FileMode mode = fileDialogPrivate->fileMode;
             if (mode == QFileDialog::AnyFile || mode == QFileDialog::ExistingFile
                     || mode == QFileDialog::ExistingFiles){
                 // When changing directory, the current selection is cleared if
                 // we are supposed to be selecting files only:
                 if (!fileDialogPrivate->mCurrentSelection.isEmpty()){
                     fileDialogPrivate->mCurrentSelectionList.clear();
                     fileDialogPrivate->mCurrentSelection.clear();
                     emit fileDialogPrivate->q_func()->currentChanged(fileDialogPrivate->mCurrentSelection);
                 }
             }
             fileDialogPrivate->setLastVisitedDirectory(newLocation);
             emit fileDialogPrivate->q_func()->directoryEntered(newLocation);
         }
         break; }
     case kNavCBAccept:
         fileDialogPrivate->mDialogClosed = true;
         fileDialogPrivate->q_func()->accept();
         break;
     case kNavCBCancel:
         fileDialogPrivate->mDialogClosed = true;
         fileDialogPrivate->q_func()->reject();
         break;
     }
 }
qt_mac_filedialog_filter_proc()
Boolean QFileDialogPrivate::qt_mac_filedialog_filter_proc (AEDesc * theItem, void * info, void * data, NavFilterModes) static
Definition at line 795 of file qfiledialog_mac.mm.
Referenced by createNavServicesDialog().
 {
     QFileDialogPrivate *fileDialogPrivate = static_cast<QFileDialogPrivate *>(data);
     if (!fileDialogPrivate || fileDialogPrivate->filterInfo.filters.isEmpty()
         || (fileDialogPrivate->filterInfo.currentSelection < 0
                 && fileDialogPrivate->filterInfo.currentSelection
                         >= fileDialogPrivate->filterInfo.filters.size()))
         return true;
     NavFileOrFolderInfo *theInfo = static_cast<NavFileOrFolderInfo *>(info);
     QString file;
     QString path;
     const QtMacFilterName &fn
            = fileDialogPrivate->filterInfo.filters.at(fileDialogPrivate->filterInfo.currentSelection);
     if (theItem->descriptorType == typeFSRef) {
         FSRef ref;
         AEGetDescData(theItem, &ref, sizeof(ref));
         UInt8 str_buffer[1024];
         FSRefMakePath(&ref, str_buffer, 1024);
         path = QString::fromUtf8(reinterpret_cast<const char *>(str_buffer));
         int slsh = path.lastIndexOf(QLatin1Char('/'));
         if (slsh != -1)
             file = path.right(path.length() - slsh - 1);
         else
             file = path;
     }
     QStringList reg = fn.regexp.split(QLatin1String(";"));
     for (QStringList::const_iterator it = reg.constBegin(); it != reg.constEnd(); ++it) {
         QRegExp rg(*it, Qt::CaseInsensitive, QRegExp::Wildcard);
 #ifdef DEBUG_FILEDIALOG_FILTERS
         qDebug("QFileDialogPrivate::qt_mac_filedialog_filter_proc:%d, asked to filter.. %s (%s)", __LINE__,
                 qPrintable(file), qPrintable(*it));
 #endif
         if (rg.exactMatch(file))
             return true;
     }
     if (theInfo->isFolder) {
         if ([[NSWorkspace sharedWorkspace] isFilePackageAtPath:qt_mac_QStringToNSString(path)])
             return false;
         return true;
     }
     return false;
 }
removeDirectory()
bool QFileDialogPrivate::removeDirectory (const QString & path)
Definition at line 2916 of file qfiledialog.cpp.
Referenced by _q_deleteCurrent().
 {
     QModelIndex modelIndex = model->index(path);
     return model->remove(modelIndex);
 }
retranslateStrings()
void QFileDialogPrivate::retranslateStrings ()
Definition at line 607 of file qfiledialog.cpp.
Referenced by init().
 {
     Q_Q(QFileDialog);
     /* WIDGETS */
     if (defaultFileTypes)
         q->setNameFilter(QFileDialog::tr("All Files (*)"));
     QList<QAction*> actions = qFileDialogUi->treeView->header()->actions();
     QAbstractItemModel *abstractModel = model;
 #ifndef QT_NO_PROXYMODEL
     if (proxyModel)
         abstractModel = proxyModel;
 #endif
     int total = qMin(abstractModel->columnCount(QModelIndex()), actions.count() + 1);
     for (int i = 1; i < total; ++i) {
         actions.at(i - 1)->setText(QFileDialog::tr("Show ") + abstractModel->headerData(i, Qt::Horizontal, Qt::DisplayRole).toString());
     }
     /* MENU ACTIONS */
     renameAction->setText(QFileDialog::tr("&Rename"));
     deleteAction->setText(QFileDialog::tr("&Delete"));
     showHiddenAction->setText(QFileDialog::tr("Show &hidden files"));
     newFolderAction->setText(QFileDialog::tr("&New Folder"));
     qFileDialogUi->retranslateUi(q);
     if (!fileNameLabelExplicitlySat){
         if (fileMode == QFileDialog::DirectoryOnly || fileMode == QFileDialog::Directory) {
             q->setLabelText(QFileDialog::FileName, QFileDialog::tr("Directory:"));
         } else {
             q->setLabelText(QFileDialog::FileName, QFileDialog::tr("File &name:"));
         }
         fileNameLabelExplicitlySat = false;
     }
 }
retranslateWindowTitle()
void QFileDialogPrivate::retranslateWindowTitle ()
Definition at line 586 of file qfiledialog.cpp.
 {
     Q_Q(QFileDialog);
     if (!useDefaultCaption || setWindowTitle != q->windowTitle())
         return;
     if (acceptMode == QFileDialog::AcceptOpen) {
         if (fileMode == QFileDialog::DirectoryOnly || fileMode == QFileDialog::Directory)
             q->setWindowTitle(QFileDialog::tr("Find Directory"));
         else
             q->setWindowTitle(QFileDialog::tr("Open"));
     } else
         q->setWindowTitle(QFileDialog::tr("Save As"));
     setWindowTitle = q->windowTitle();
 }
rootIndex()
QModelIndex QFileDialogPrivate::rootIndex () const inline
Definition at line 1504 of file qfiledialog.cpp.
Referenced by _q_createDirectory().
{
     return mapToSource(qFileDialogUi->listView->rootIndex());
 }
rootPath()
QString QFileDialogPrivate::rootPath () const inline
Definition at line 404 of file qfiledialog_p.h.
Referenced by _q_fileRenamed(), and addDefaultSuffixToFiles().
{
     return model->rootPath();
 }
select()
QModelIndex QFileDialogPrivate::select (const QModelIndex & index) const inline
Definition at line 1533 of file qfiledialog.cpp.
Referenced by _q_autoCompleteFileName(), and _q_createDirectory().
{
     Q_ASSERT(index.isValid() ? index.model() == model : true);
     QModelIndex idx = mapFromSource(index);
     if (idx.isValid() && !qFileDialogUi->listView->selectionModel()->isSelected(idx))
         qFileDialogUi->listView->selectionModel()->select(idx,
             QItemSelectionModel::Select | QItemSelectionModel::Rows);
     return idx;
 }
selectedFiles_sys()
QStringList QFileDialogPrivate::selectedFiles_sys () const
Definition at line 682 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     if (q_func()->acceptMode() == QFileDialog::AcceptOpen){
         return mCurrentSelectionList;
     } else {
         return QStringList() << mCurrentLocation + QLatin1Char('/')
                                 + QCFString::toQString(NavDialogGetSaveFileName(mDialog));
     }
 #else
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     return [delegate selectedFiles];
 #endif
 }
selectedNameFilter_sys()
QString QFileDialogPrivate::selectedNameFilter_sys () const
Definition at line 746 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     int index = filterInfo.currentSelection;
 #else
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     int index = [delegate->mPopUpButton indexOfSelectedItem];
 #endif
     return index != -1 ? nameFilters.at(index) : QString();
 }
selectFile_sys()
void QFileDialogPrivate::selectFile_sys (const QString & filename)
Definition at line 641 of file qfiledialog_mac.mm.
Referenced by qt_mac_filedialog_event_proc(), and rootPath().
 {
     QString filePath = filename;
     if (QDir::isRelativePath(filePath))
         filePath = QFileInfo(directory_sys(), filePath).filePath();
 #ifndef QT_MAC_USE_COCOA
     // Update the selection list immidiatly, so
     // subsequent calls to selectedFiles() gets correct:
     mCurrentSelectionList.clear();
     mCurrentSelectionList << filename;
     if (mCurrentSelection != filename){
         mCurrentSelection = filename;
         emit q_func()->currentChanged(mCurrentSelection);
     }
     AEDescList descList;
     if (AECreateList(0, 0, false, &descList) != noErr)
         return;
     FSRef fsRef;
     if (qt_mac_create_fsref(filePath, &fsRef) == noErr) {
         AEDesc desc;
         if (AECreateDesc(typeFSRef, &fsRef, sizeof(FSRef), &desc) == noErr){
             if (AEPutDesc(&descList, 0, &desc) == noErr)
                 NavCustomControl(mDialog, kNavCtlSetSelection, (void*)&descList);
         }
     }
     // Type the file name into the save dialog's text field:
     UInt8 *strBuffer = (UInt8 *)malloc(1024);
     qt_mac_to_pascal_string(QFileInfo(filename).fileName(), strBuffer);
     NavCustomControl(mDialog, kNavCtlSetEditFileName, strBuffer);
     free(strBuffer);
 #else
     // There seems to no way to select a file once the dialog is running.
     // So do the next best thing, set the file's directory:
     setDirectory_sys(QFileInfo(filePath).absolutePath());
 #endif
 }
selectNameFilter_sys()
void QFileDialogPrivate::selectNameFilter_sys (const QString & filter)
Definition at line 728 of file qfiledialog_mac.mm.
Referenced by qt_mac_filedialog_event_proc(), and rootPath().
 {
     int index = nameFilters.indexOf(filter);
     if (index != -1) {
 #ifndef QT_MAC_USE_COCOA
         NavMenuItemSpec navSpec;
         bzero(&navSpec, sizeof(NavMenuItemSpec));
         navSpec.menuType = index;
         NavCustomControl(mDialog, kNavCtlSelectCustomType, &navSpec);
 #else
         QMacCocoaAutoReleasePool pool;
         QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
         [delegate->mPopUpButton selectItemAtIndex:index];
         [delegate filterChanged:nil];
 #endif
     }
 }
setDirectory_sys()
void QFileDialogPrivate::setDirectory_sys (const QString & directory)
Definition at line 609 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     if (directory == mCurrentLocation)
         return;
     mCurrentLocation = directory;
     emit q_func()->directoryEntered(mCurrentLocation);
     FSRef fsRef;
     if (qt_mac_create_fsref(directory, &fsRef) == noErr) {
         AEDesc desc;
         if (AECreateDesc(typeFSRef, &fsRef, sizeof(FSRef), &desc) == noErr)
             NavCustomControl(mDialog, kNavCtlSetLocation, (void*)&desc);
     }
 #else
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     [delegate->mSavePanel setDirectory:qt_mac_QStringToNSString(directory)];
 #endif
 }
setFilter_sys()
void QFileDialogPrivate::setFilter_sys ()
Definition at line 710 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
 #else
     Q_Q(QFileDialog);
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     *(delegate->mQDirFilter) = model->filter();
     delegate->mFileMode = fileMode;
     [delegate->mSavePanel setTitle:qt_mac_QStringToNSString(q->windowTitle())];
     [delegate->mSavePanel setPrompt:[delegate strip:acceptLabel]];
     if (fileNameLabelExplicitlySat)
         [delegate->mSavePanel setNameFieldLabel:[delegate strip:qFileDialogUi->fileNameLabel->text()]];
     [delegate updateProperties];
 #endif
 }
setLastVisitedDirectory()
void QFileDialogPrivate::setLastVisitedDirectory (const QString & dir)
Definition at line 602 of file qfiledialog.cpp.
Referenced by init(), and qt_mac_filedialog_event_proc().
 {
     *lastVisitedDir() = dir;
 }
setNameFilters_sys()
void QFileDialogPrivate::setNameFilters_sys (const QStringList & filters)
Definition at line 698 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
 #ifndef QT_MAC_USE_COCOA
     Q_UNUSED(filters);
 #else
     QMacCocoaAutoReleasePool pool;
     QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *delegate = static_cast<QT_MANGLE_NAMESPACE(QNSOpenSavePanelDelegate) *>(mDelegate);
     bool hideDetails = q_func()->testOption(QFileDialog::HideNameFilterDetails);
     [delegate setNameFilters:filters hideDetails:hideDetails];
 #endif
 }
setRootIndex()
void QFileDialogPrivate::setRootIndex (const QModelIndex & index) const inline
Definition at line 1523 of file qfiledialog.cpp.
{
     Q_ASSERT(index.isValid() ? index.model() == model : true);
     QModelIndex idx = mapFromSource(index);
     qFileDialogUi->treeView->setRootIndex(idx);
     qFileDialogUi->listView->setRootIndex(idx);
 }
setVisible_sys()
bool QFileDialogPrivate::setVisible_sys (bool visible)
Definition at line 773 of file qfiledialog_mac.mm.
Referenced by rootPath().
 {
     Q_Q(QFileDialog);
     if (!visible == q->isHidden())
         return false;
     if (q->windowFlags() & Qt::WindowStaysOnTopHint) {
         // The native file dialog tries all it can to stay
         // on the NSModalPanel level. And it might also show
         // its own "create directory" dialog that we cannot control.
         // So we need to use the non-native version in this case...
         return false;
     }
 #ifndef QT_MAC_USE_COCOA
     return visible ? showCarbonNavServicesDialog() : hideCarbonNavServicesDialog();
 #else
     return visible ? showCocoaFilePanel() : hideCocoaFilePanel();
 #endif
 }
showCarbonNavServicesDialog()
bool QFileDialogPrivate::showCarbonNavServicesDialog ()
Definition at line 1084 of file qfiledialog_mac.mm.
 {
     Q_Q(QFileDialog);
     if (q->acceptMode() == QFileDialog::AcceptSave && q->windowModality() == Qt::NonModal)
         return false; // cannot do native no-modal save dialogs.
     createNavServicesDialog();
     mDialogClosed = false;
     if (q->windowModality() != Qt::ApplicationModal)
         NavDialogRun(mDialog);
     return true;
 }
toInternal()
static QString QFileDialogPrivate::toInternal (const QString & path) inline static
Definition at line 183 of file qfiledialog_p.h.
Referenced by addDefaultSuffixToFiles(), and typedFiles().
     {
 #if defined(Q_FS_FAT) || defined(Q_OS_OS2EMX) || defined(Q_OS_SYMBIAN)
         QString n(path);
         for (int i = 0; i < (int)n.length(); ++i)
             if (n[i] == QLatin1Char('\\')) n[i] = QLatin1Char('/');
 #if defined(Q_OS_WINCE)
         if ((n.size() > 1) && (n.startsWith(QLatin1String("//"))))
             n = n.mid(1);
 #endif
         return n;
 #else // the compile should optimize away this
         return path;
 #endif
     }
typedFiles()
QStringList QFileDialogPrivate::typedFiles () const
Returns the text in the line edit which can be one or more file names
Definition at line 980 of file qfiledialog.cpp.
Referenced by _q_autoCompleteFileName(), and qt_mac_filedialog_event_proc().
 {
 #ifdef Q_OS_UNIX
     Q_Q(const QFileDialog);
 #endif
     QStringList files;
     QString editText = lineEdit()->text();
     if (!editText.contains(QLatin1Char('"'))) {
 #ifdef Q_OS_UNIX
         const QString prefix = q->directory().absolutePath() + QDir::separator();
         if (QFile::exists(prefix + editText))
             files << editText;
         else
             files << qt_tildeExpansion(editText);
 #else
         files << editText;
 #endif
     } else {
         // " is used to separate files like so: "file1" "file2" "file3" ...
         // ### need escape character for filenames with quotes (")
         QStringList tokens = editText.split(QLatin1Char('\"'));
         for (int i=0; i<tokens.size(); ++i) {
             if ((i % 2) == 0)
                 continue; // Every even token is a separator
 #ifdef Q_OS_UNIX
             const QString token = tokens.at(i);
             const QString prefix = q->directory().absolutePath() + QDir::separator();
             if (QFile::exists(prefix + token))
                 files << token;
             else
                 files << qt_tildeExpansion(token);
 #else
             files << toInternal(tokens.at(i));
 #endif
         }
     }
     return addDefaultSuffixToFiles(files);
 }
workingDirectory()
QString QFileDialogPrivate::workingDirectory (const QString & path) static
Definition at line 2205 of file qfiledialog.cpp.
Referenced by QFileDialog::getExistingDirectory(), QFileDialog::getOpenFileName(), QFileDialog::getOpenFileNames(), QFileDialog::getSaveFileName(), and init().
 {
     if (!path.isEmpty()) {
         QString directory = _qt_get_directory(path);
         if (!directory.isEmpty())
             return directory;
     }
     QString directory = _qt_get_directory(*lastVisitedDir());
     if (!directory.isEmpty())
         return directory;
     return QDir::currentPath();
 }
Properties
acceptLabel
QString QFileDialogPrivate::acceptLabel
Definition at line 323 of file qfiledialog_p.h.
Referenced by _q_updateOkButton().
acceptMode
QFileDialog::AcceptMode QFileDialogPrivate::acceptMode
Definition at line 242 of file qfiledialog_p.h.
Referenced by _q_updateOkButton(), _q_useNameFilter(), QFileDialog::accept(), QFileDialog::labelText(), qt_mac_filedialog_event_proc(), retranslateWindowTitle(), and QFileDialog::setLabelText().
completer
QFSCompleter* QFileDialogPrivate::completer
Definition at line 238 of file qfiledialog_p.h.
Referenced by createWidgets().
confirmOverwrite
bool QFileDialogPrivate::confirmOverwrite
Definition at line 243 of file qfiledialog_p.h.
Referenced by QFileDialog::accept().
currentHistory
QStringList QFileDialogPrivate::currentHistory
Definition at line 247 of file qfiledialog_p.h.
Referenced by _q_navigateBackward(), _q_navigateForward(), _q_pathChanged(), and QFileDialog::history().
currentHistoryLocation
int QFileDialogPrivate::currentHistoryLocation
Definition at line 248 of file qfiledialog_p.h.
Referenced by _q_navigateBackward(), _q_navigateForward(), and _q_pathChanged().
defaultFileTypes
bool QFileDialogPrivate::defaultFileTypes
Definition at line 256 of file qfiledialog_p.h.
Referenced by retranslateStrings().
defaultSuffix
QString QFileDialogPrivate::defaultSuffix
Definition at line 244 of file qfiledialog_p.h.
Referenced by addDefaultSuffixToFiles().
deleteAction
QAction* QFileDialogPrivate::deleteAction
Definition at line 251 of file qfiledialog_p.h.
Referenced by _q_showContextMenu(), createMenuActions(), and retranslateStrings().
fileMode
QFileDialog::FileMode QFileDialogPrivate::fileMode
Definition at line 241 of file qfiledialog_p.h.
Referenced by _q_enterDirectory(), _q_fileRenamed(), _q_selectionChanged(), _q_updateOkButton(), init(), QFileDialog::open(), qt_mac_filedialog_event_proc(), retranslateStrings(), and retranslateWindowTitle().
fileNameLabelExplicitlySat
bool QFileDialogPrivate::fileNameLabelExplicitlySat
Definition at line 257 of file qfiledialog_p.h.
Referenced by retranslateStrings().
filterInfo
struct QFileDialogPrivate::QtMacNavFilterInfo QFileDialogPrivate::filterInfo
Referenced by qt_mac_filedialog_event_proc(), and qt_mac_filedialog_filter_proc().
mCurrentLocation
QString QFileDialogPrivate::mCurrentLocation
Definition at line 286 of file qfiledialog_p.h.
Referenced by qt_mac_filedialog_event_proc().
mCurrentSelection
QString QFileDialogPrivate::mCurrentSelection
Definition at line 287 of file qfiledialog_p.h.
Referenced by qt_mac_filedialog_event_proc().
mCurrentSelectionList
QStringList QFileDialogPrivate::mCurrentSelectionList
Definition at line 288 of file qfiledialog_p.h.
Referenced by qt_mac_filedialog_event_proc().
mDelegate
void* QFileDialogPrivate::mDelegate
Definition at line 281 of file qfiledialog_p.h.
mDialog
NavDialogRef QFileDialogPrivate::mDialog
Definition at line 283 of file qfiledialog_p.h.
mDialogClosed
bool QFileDialogPrivate::mDialogClosed
Definition at line 285 of file qfiledialog_p.h.
Referenced by qt_mac_filedialog_event_proc().
mDialogStarted
bool QFileDialogPrivate::mDialogStarted
Definition at line 284 of file qfiledialog_p.h.
Referenced by qt_mac_filedialog_event_proc().
memberToDisconnectOnClose
QByteArray QFileDialogPrivate::memberToDisconnectOnClose
Definition at line 326 of file qfiledialog_p.h.
model
QFileSystemModel* QFileDialogPrivate::model
Definition at line 235 of file qfiledialog_p.h.
Referenced by _q_autoCompleteFileName(), _q_createDirectory(), _q_deleteCurrent(), _q_enterDirectory(), _q_goToDirectory(), _q_goToUrl(), _q_navigateToParent(), _q_pathChanged(), _q_selectionChanged(), _q_updateOkButton(), _q_useNameFilter(), createWidgets(), removeDirectory(), retranslateStrings(), select(), setRootIndex(), and QFileDialogComboBox::showPopup().
nameFilters
QStringList QFileDialogPrivate::nameFilters
Definition at line 258 of file qfiledialog_p.h.
Referenced by _q_useNameFilter(), QFileDialog::filters(), and qt_mac_filedialog_event_proc().
nativeDialogInUse
bool QFileDialogPrivate::nativeDialogInUse
Definition at line 261 of file qfiledialog_p.h.
Referenced by canBeNativeDialog().
newFolderAction
QAction* QFileDialogPrivate::newFolderAction
Definition at line 253 of file qfiledialog_p.h.
Referenced by _q_showContextMenu(), createMenuActions(), and retranslateStrings().
opts
QFileDialog::Options QFileDialogPrivate::opts
Definition at line 329 of file qfiledialog_p.h.
Referenced by canBeNativeDialog().
proxyModel
QAbstractProxyModel* QFileDialogPrivate::proxyModel
Definition at line 230 of file qfiledialog_p.h.
Referenced by _q_enterDirectory(), createWidgets(), retranslateStrings(), and QFileDialog::setProxyModel().
qFileDialogUi
QScopedPointer<Ui_QFileDialog> QFileDialogPrivate::qFileDialogUi
Definition at line 321 of file qfiledialog_p.h.
Referenced by _q_autoCompleteFileName(), _q_createDirectory(), _q_deleteCurrent(), _q_goToDirectory(), _q_pathChanged(), _q_renameCurrent(), _q_rowsInserted(), _q_selectionChanged(), _q_showContextMenu(), _q_showDetailsView(), _q_showHeader(), _q_showListView(), _q_updateOkButton(), _q_useNameFilter(), createToolButtons(), createWidgets(), currentView(), init(), lineEdit(), qt_mac_filedialog_event_proc(), retranslateStrings(), rootIndex(), select(), and setRootIndex().
receiverToDisconnectOnClose
QPointer<QObject> QFileDialogPrivate::receiverToDisconnectOnClose
Definition at line 325 of file qfiledialog_p.h.
renameAction
QAction* QFileDialogPrivate::renameAction
Definition at line 250 of file qfiledialog_p.h.
Referenced by _q_showContextMenu(), createMenuActions(), and retranslateStrings().
setWindowTitle
QString QFileDialogPrivate::setWindowTitle
Definition at line 245 of file qfiledialog_p.h.
Referenced by init(), and retranslateWindowTitle().
showHiddenAction
QAction* QFileDialogPrivate::showHiddenAction
Definition at line 252 of file qfiledialog_p.h.
Referenced by _q_showContextMenu(), _q_showHidden(), createMenuActions(), and retranslateStrings().
signalToDisconnectOnClose
QByteArray QFileDialogPrivate::signalToDisconnectOnClose
Definition at line 327 of file qfiledialog_p.h.
useDefaultCaption
bool QFileDialogPrivate::useDefaultCaption
Definition at line 255 of file qfiledialog_p.h.
Referenced by init(), and retranslateWindowTitle().
watching
QStringList QFileDialogPrivate::watching
Definition at line 234 of file qfiledialog_p.h.
The documentation for this class was generated from the following files:
/src/gui/dialogs/qfiledialog_p.h
/src/gui/dialogs/qfiledialog.cpp
/src/gui/dialogs/qfiledialog_mac.mm