Qt 4.8: QTextCursor Class Reference
QTextCursor Class Reference
The QTextCursor class offers an API to access and modify QTextDocuments.
#include <qtextcursor.h>
Public Types
enum MoveMode { MoveAnchor, KeepAnchor }
If the anchor() is kept where it is and the position() is moved, the text in between will be selected.
enum MoveOperation {
NoMove, Start, Up, StartOfLine,
StartOfBlock, StartOfWord, PreviousBlock, PreviousCharacter,
PreviousWord, Left, WordLeft, End,
Down, EndOfLine, EndOfWord, EndOfBlock,
NextBlock, NextCharacter, NextWord, Right,
WordRight, NextCell, PreviousCell, NextRow,
PreviousRow
}
enum SelectionType { WordUnderCursor, LineUnderCursor, BlockUnderCursor, Document }
This enum describes the types of selection that can be applied with the select() function.
Public Functions
int anchor () const
Returns the anchor position; this is the same as position() unless there is a selection in which case position() marks one end of the selection and anchor() marks the other end.
bool atBlockEnd () const
Returns true if the cursor is at the end of a block; otherwise returns false.
bool atBlockStart () const
Returns true if the cursor is at the start of a block; otherwise returns false.
bool atEnd () const
Returns true if the cursor is at the end of the document; otherwise returns false.
bool atStart () const
Returns true if the cursor is at the start of the document; otherwise returns false.
void beginEditBlock ()
Indicates the start of a block of editing operations on the document that should appear as a single operation from an undo/redo point of view.
QTextBlock block () const
Returns the block that contains the cursor.
QTextCharFormat blockCharFormat () const
Returns the block character format of the block the cursor is in.
QTextBlockFormat blockFormat () const
Returns the block format of the block the cursor is in.
int blockNumber () const
Returns the number of the block the cursor is in, or 0 if the cursor is invalid.
QTextCharFormat charFormat () const
Returns the format of the character immediately before the cursor position().
void clearSelection ()
Clears the current selection by setting the anchor to the cursor position.
int columnNumber () const
Returns the position of the cursor within its containing line.
QTextList * createList (const QTextListFormat &format)
Creates and returns a new list with the given format, and makes the current paragraph the cursor is in the first list item.
QTextList * createList (QTextListFormat::Style style)
Creates and returns a new list with the given style, making the cursor's current paragraph the first list item.
QTextFrame * currentFrame () const
Returns a pointer to the current frame.
QTextList * currentList () const
Returns the current list if the cursor position() is inside a block that is part of a list; otherwise returns 0.
QTextTable * currentTable () const
Returns a pointer to the current table if the cursor position() is inside a block that is part of a table; otherwise returns 0.
void deleteChar ()
If there is no selected text, deletes the character at the current cursor position; otherwise deletes the selected text.
void deletePreviousChar ()
If there is no selected text, deletes the character before the current cursor position; otherwise deletes the selected text.
QTextDocument * document () const
Returns the document this cursor is associated with.
void endEditBlock ()
Indicates the end of a block of editing operations on the document that should appear as a single operation from an undo/redo point of view.
bool hasComplexSelection () const
Returns true if the cursor contains a selection that is not simply a range from selectionStart() to selectionEnd(); otherwise returns false.
bool hasSelection () const
Returns true if the cursor contains a selection; otherwise returns false.
void insertBlock ()
Inserts a new empty block at the cursor position() with the current blockFormat() and charFormat().
void insertBlock (const QTextBlockFormat &format)
Inserts a new empty block at the cursor position() with block format format and the current charFormat() as block char format.
void insertBlock (const QTextBlockFormat &format, const QTextCharFormat &charFormat)
Inserts a new empty block at the cursor position() with block format format and charFormat as block char format.
void insertFragment (const QTextDocumentFragment &fragment)
Inserts the text fragment at the current position().
QTextFrame * insertFrame (const QTextFrameFormat &format)
Inserts a frame with the given format at the current cursor position(), moves the cursor position() inside the frame, and returns the frame.
void insertHtml (const QString &html)
Inserts the text html at the current position().
void insertImage (const QTextImageFormat &format, QTextFrameFormat::Position alignment)
Inserts the image defined by the given format at the cursor's current position with the specified alignment.
void insertImage (const QTextImageFormat &format)
Inserts the image defined by format at the current position().
void insertImage (const QString &name)
Convenience method for inserting the image with the given name at the current position().
void insertImage (const QImage &image, const QString &name=QString())
Convenience function for inserting the given image with an optional name at the current position().
QTextList * insertList (const QTextListFormat &format)
Inserts a new block at the current position and makes it the first list item of a newly created list with the given format.
QTextList * insertList (QTextListFormat::Style style)
Inserts a new block at the current position and makes it the first list item of a newly created list with the given style.
QTextTable * insertTable (int rows, int cols, const QTextTableFormat &format)
Creates a new table with the given number of rows and columns in the specified format, inserts it at the current cursor position() in the document, and returns the table object.
QTextTable * insertTable (int rows, int cols)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Creates a new table with the given number of rows and columns, inserts it at the current cursor position() in the document, and returns the table object.
void insertText (const QString &text)
Inserts text at the current position, using the current character format.
void insertText (const QString &text, const QTextCharFormat &format)
Inserts text at the current position with the given format.
bool isCopyOf (const QTextCursor &other) const
Returns true if this cursor and other are copies of each other, i.e.
bool isNull () const
Returns true if the cursor is null; otherwise returns false.
void joinPreviousEditBlock ()
Like beginEditBlock() indicates the start of a block of editing operations that should appear as a single operation for undo/redo.
bool keepPositionOnInsert () const
Returns whether the cursor should keep its current position when text gets inserted at the position of the cursor.
void mergeBlockCharFormat (const QTextCharFormat &modifier)
Modifies the block char format of the current block (or all blocks that are contained in the selection) with the block format specified by modifier.
void mergeBlockFormat (const QTextBlockFormat &modifier)
Modifies the block format of the current block (or all blocks that are contained in the selection) with the block format specified by modifier.
void mergeCharFormat (const QTextCharFormat &modifier)
Merges the cursor's current character format with the properties described by format modifier.
bool movePosition (MoveOperation op, MoveMode=MoveAnchor, int n=1)
Moves the cursor by performing the given operation n times, using the specified mode, and returns true if all operations were completed successfully; otherwise returns false.
bool operator!= (const QTextCursor &rhs) const
Returns true if the other cursor is at a different position in the document as this cursor; otherwise returns false.
bool operator< (const QTextCursor &rhs) const
Returns true if the other cursor is positioned later in the document than this cursor; otherwise returns false.
bool operator<= (const QTextCursor &rhs) const
Returns true if the other cursor is positioned later or at the same position in the document as this cursor; otherwise returns false.
QTextCursor & operator= (const QTextCursor &other)
Makes a copy of cursor and assigns it to this QTextCursor.
bool operator== (const QTextCursor &rhs) const
Returns true if the other cursor is at the same position in the document as this cursor; otherwise returns false.
bool operator> (const QTextCursor &rhs) const
Returns true if the other cursor is positioned earlier in the document than this cursor; otherwise returns false.
bool operator>= (const QTextCursor &rhs) const
Returns true if the other cursor is positioned earlier or at the same position in the document as this cursor; otherwise returns false.
int position () const
Returns the absolute position of the cursor within the document.
int positionInBlock () const
Returns the relative position of the cursor within the block.
QTextCursor ()
Constructs a null cursor.
QTextCursor (QTextDocument *document)
Constructs a cursor pointing to the beginning of the document.
QTextCursor (QTextDocumentPrivate *p, int pos)
QTextCursor (QTextFrame *frame)
Constructs a cursor pointing to the beginning of the frame.
QTextCursor (const QTextBlock &block)
Constructs a cursor pointing to the beginning of the block.
QTextCursor (QTextCursorPrivate *d)
QTextCursor (const QTextCursor &cursor)
Constructs a new cursor that is a copy of cursor.
void removeSelectedText ()
If there is a selection, its content is deleted; otherwise does nothing.
void select (SelectionType selection)
Selects text in the document according to the given selection.
void selectedTableCells (int *firstRow, int *numRows, int *firstColumn, int *numColumns) const
If the selection spans over table cells, firstRow is populated with the number of the first row in the selection, firstColumn with the number of the first column in the selection, and numRows and numColumns with the number of rows and columns in the selection.
QString selectedText () const
Returns the current selection's text (which may be empty).
QTextDocumentFragment selection () const
Returns the current selection (which may be empty) with all its formatting information.
int selectionEnd () const
Returns the end of the selection or position() if the cursor doesn't have a selection.
int selectionStart () const
Returns the start of the selection or position() if the cursor doesn't have a selection.
void setBlockCharFormat (const QTextCharFormat &format)
Sets the block char format of the current block (or all blocks that are contained in the selection) to format.
void setBlockFormat (const QTextBlockFormat &format)
Sets the block format of the current block (or all blocks that are contained in the selection) to format.
void setCharFormat (const QTextCharFormat &format)
Sets the cursor's current character format to the given format.
void setKeepPositionOnInsert (bool b)
Defines whether the cursor should keep its current position when text gets inserted at the current position of the cursor.
void setPosition (int pos, MoveMode mode=MoveAnchor)
Moves the cursor to the absolute position in the document specified by pos using a MoveMode specified by m.
void setVerticalMovementX (int x)
Sets the visual x position for vertical cursor movements to x.
void setVisualNavigation (bool b)
Sets visual navigation to b.
int verticalMovementX () const
Returns the visual x position for vertical cursor movements.
bool visualNavigation () const
Returns true if the cursor does visual navigation; otherwise returns false.
~QTextCursor ()
Destroys the QTextCursor.
Properties
QSharedDataPointer< QTextCursorPrivate > d
Friends
class QTextControlPrivate
class QTextCopyHelper
class QTextDocumentFragmentPrivate
Detailed Description
The QTextCursor class offers an API to access and modify QTextDocuments.
Note
This class or function is reentrant.
Text cursors are objects that are used to access and modify the contents and underlying structure of text documents via a programming interface that mimics the behavior of a cursor in a text editor. QTextCursor contains information about both the cursor's position within a QTextDocument and any selection that it has made.
QTextCursor is modeled on the way a text cursor behaves in a text editor, providing a programmatic means of performing standard actions through the user interface. A document can be thought of as a single string of characters. The cursor's current position() then is always either between two consecutive characters in the string, or else before the very first character or after the very last character in the string. Documents can also contain tables, lists, images, and other objects in addition to text but, from the developer's point of view, the document can be treated as one long string. Some portions of that string can be considered to lie within particular blocks (e.g. paragraphs), or within a table's cell, or a list's item, or other structural elements. When we refer to "current character" we mean the character immediately before the cursor position() in the document. Similarly, the "current block" is the block that contains the cursor position().
A QTextCursor also has an anchor() position. The text that is between the anchor() and the position() is the selection. If anchor() == position() there is no selection.
The cursor position can be changed programmatically using setPosition() and movePosition(); the latter can also be used to select text. For selections see selectionStart(), selectionEnd(), hasSelection(), clearSelection(), and removeSelectedText().
If the position() is at the start of a block atBlockStart() returns true; and if it is at the end of a block atBlockEnd() returns true. The format of the current character is returned by charFormat(), and the format of the current block is returned by blockFormat().
Formatting can be applied to the current text document using the setCharFormat(), mergeCharFormat(), setBlockFormat() and mergeBlockFormat() functions. The 'set' functions will replace the cursor's current character or block format, while the 'merge' functions add the given format properties to the cursor's current format. If the cursor has a selection the given format is applied to the current selection. Note that when only parts of a block is selected the block format is applied to the entire block. The text at the current character position can be turned into a list using createList().
Deletions can be achieved using deleteChar(), deletePreviousChar(), and removeSelectedText().
Text strings can be inserted into the document with the insertText() function, blocks (representing new paragraphs) can be inserted with insertBlock().
Existing fragments of text can be inserted with insertFragment() but, if you want to insert pieces of text in various formats, it is usually still easier to use insertText() and supply a character format.
Various types of higher-level structure can also be inserted into the document with the cursor:
Lists are ordered sequences of block elements that are decorated with bullet points or symbols. These are inserted in a specified format with insertList().
Tables are inserted with the insertTable() function, and can be given an optional format. These contain an array of cells that can be traversed using the cursor.
Inline images are inserted with insertImage(). The image to be used can be specified in an image format, or by name.
Frames are inserted by calling insertFrame() with a specified format.
Actions can be grouped (i.e. treated as a single action for undo/redo) using beginEditBlock() and endEditBlock().
Cursor movements are limited to valid cursor positions. In Latin writing this is between any two consecutive characters in the text, before the first character, or after the last character. In some other writing systems cursor movements are limited to "clusters" (e.g. a syllable in Devanagari, or a base letter plus diacritics). Functions such as movePosition() and deleteChar() limit cursor movement to these valid positions.
See also
Rich Text Processing
Definition at line 70 of file qtextcursor.h.
Enumerations
MoveMode
enum QTextCursor::MoveMode
If the anchor() is kept where it is and the position() is moved, the text in between will be selected.
MoveAnchor Moves the anchor to the same position as the cursor itself.
KeepAnchor Keeps the anchor where it is.
Enumerator
MoveAnchor
KeepAnchor
Definition at line 85 of file qtextcursor.h.
                   {
         MoveAnchor,
         KeepAnchor
     };
MoveOperation
enum QTextCursor::MoveOperation
NoMove Keep the cursor where it is
Start Move to the start of the document.
StartOfLine Move to the start of the current line.
StartOfBlock Move to the start of the current block.
StartOfWord Move to the start of the current word.
PreviousBlock Move to the start of the previous block.
PreviousCharacter Move to the previous character.
PreviousWord Move to the beginning of the previous word.
Up Move up one line.
Left Move left one character.
WordLeft Move left one word.
End Move to the end of the document.
EndOfLine Move to the end of the current line.
EndOfWord Move to the end of the current word.
EndOfBlock Move to the end of the current block.
NextBlock Move to the beginning of the next block.
NextCharacter Move to the next character.
NextWord Move to the next word.
Down Move down one line.
Right Move right one character.
WordRight Move right one word.
NextCell Move to the beginning of the next table cell inside the current table. If the current cell is the last cell in the row, the cursor will move to the first cell in the next row.
PreviousCell Move to the beginning of the previous table cell inside the current table. If the current cell is the first cell in the row, the cursor will move to the last cell in the previous row.
NextRow Move to the first new cell of the next row in the current table.
PreviousRow Move to the last cell of the previous row in the current table.
See also
movePosition()
Enumerator
NoMove
Start
Up
StartOfLine
StartOfBlock
StartOfWord
PreviousBlock
PreviousCharacter
PreviousWord
Left
WordLeft
End
Down
EndOfLine
EndOfWord
EndOfBlock
NextBlock
NextCharacter
NextWord
Right
WordRight
NextCell
PreviousCell
NextRow
PreviousRow
Definition at line 99 of file qtextcursor.h.
{
         NoMove,
         Start,
         Up,
         StartOfLine,
         StartOfBlock,
         StartOfWord,
         PreviousBlock,
         PreviousCharacter,
         PreviousWord,
         Left,
         WordLeft,
         End,
         Down,
         EndOfLine,
         EndOfWord,
         EndOfBlock,
         NextBlock,
         NextCharacter,
         NextWord,
         Right,
         WordRight,
         NextCell,
         PreviousCell,
         NextRow,
         PreviousRow
     };
SelectionType
enum QTextCursor::SelectionType
This enum describes the types of selection that can be applied with the select() function.
Document Selects the entire document.
BlockUnderCursor Selects the block of text under the cursor.
LineUnderCursor Selects the line of text under the cursor.
WordUnderCursor Selects the word under the cursor. If the cursor is not positioned within a string of selectable characters, no text is selected.
Enumerator
WordUnderCursor
LineUnderCursor
BlockUnderCursor
Document
Definition at line 144 of file qtextcursor.h.
{
         WordUnderCursor,
         LineUnderCursor,
         BlockUnderCursor,
         Document
     };
Constructors and Destructors
QTextCursor() [1/7]
QTextCursor::QTextCursor ()
Constructs a null cursor.
Definition at line 1069 of file qtextcursor.cpp.
     : d(0)
 {
 }
QTextCursor() [2/7]
QTextCursor::QTextCursor (QTextDocument * document) explicit
Constructs a cursor pointing to the beginning of the document.
Definition at line 1077 of file qtextcursor.cpp.
     : d(new QTextCursorPrivate(document->docHandle()))
 {
 }
QTextCursor() [3/7]
QTextCursor::QTextCursor (QTextDocumentPrivate * p, int pos)
Warning
This function is not part of the public interface.
Definition at line 1105 of file qtextcursor.cpp.
     : d(new QTextCursorPrivate(p))
 {
     d->adjusted_anchor = d->anchor = d->position = pos;
     d->setX();
 }
QTextCursor() [4/7]
QTextCursor::QTextCursor (QTextFrame * frame) explicit
Constructs a cursor pointing to the beginning of the frame.
Definition at line 1085 of file qtextcursor.cpp.
     : d(new QTextCursorPrivate(frame->document()->docHandle()))
 {
     d->adjusted_anchor = d->anchor = d->position = frame->firstPosition();
 }
QTextCursor() [5/7]
QTextCursor::QTextCursor (const QTextBlock & block) explicit
Constructs a cursor pointing to the beginning of the block.
Definition at line 1095 of file qtextcursor.cpp.
     : d(new QTextCursorPrivate(block.docHandle()))
 {
     d->adjusted_anchor = d->anchor = d->position = block.position();
 }
QTextCursor() [6/7]
QTextCursor::QTextCursor (QTextCursorPrivate * d) explicit
Warning
This function is not part of the public interface.
Definition at line 1116 of file qtextcursor.cpp.
 {
     Q_ASSERT(d);
     this->d = d;
 }
QTextCursor() [7/7]
QTextCursor::QTextCursor (const QTextCursor & cursor)
Constructs a new cursor that is a copy of cursor.
Definition at line 1125 of file qtextcursor.cpp.
 {
     d = cursor.d;
 }
~QTextCursor()
QTextCursor::~QTextCursor ()
Destroys the QTextCursor.
Definition at line 1145 of file qtextcursor.cpp.
 {
 }
Functions
anchor()
int QTextCursor::anchor () const
Returns the anchor position; this is the same as position() unless there is a selection in which case position() marks one end of the selection and anchor() marks the other end.
Just like the cursor position, the anchor position is between characters.
See also
position() setPosition() movePosition() selectionStart() selectionEnd()
Definition at line 1230 of file qtextcursor.cpp.
Referenced by QTextBrowserPrivate::createHistoryEntry(), QTextControlPrivate::cursorMoveKeyEvent(), QDeclarativeTextEdit::moveCursorSelection(), QTextControlPrivate::repaintOldAndNewSelection(), QDeclarativeTextEdit::setCursorPosition(), QTextControl::setExtraSelections(), and setPosition().
 {
     if (!d || !d->priv)
         return -1;
     return d->anchor;
 }
atBlockEnd()
bool QTextCursor::atBlockEnd () const
Returns true if the cursor is at the end of a block; otherwise returns false.
See also
atBlockStart(), atEnd()
Definition at line 2008 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return false;
     return d->position == d->block().position() + d->block().length() - 1;
 }
atBlockStart()
bool QTextCursor::atBlockStart () const
Returns true if the cursor is at the start of a block; otherwise returns false.
See also
atBlockEnd(), atStart()
Definition at line 1994 of file qtextcursor.cpp.
Referenced by QTextEdit::keyPressEvent(), QPlainTextEdit::keyReleaseEvent(), and QTextEdit::keyReleaseEvent().
 {
     if (!d || !d->priv)
         return false;
     return d->position == d->block().position();
 }
atEnd()
bool QTextCursor::atEnd () const
Returns true if the cursor is at the end of the document; otherwise returns false.
Since
4.6
See also
atStart(), atBlockEnd()
Definition at line 2041 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return false;
     return d->position == d->priv->length() - 1;
 }
atStart()
bool QTextCursor::atStart () const
Returns true if the cursor is at the start of the document; otherwise returns false.
See also
atBlockStart(), atEnd()
Definition at line 2022 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return false;
     return d->position == 0;
 }
beginEditBlock()
void QTextCursor::beginEditBlock ()
Indicates the start of a block of editing operations on the document that should appear as a single operation from an undo/redo point of view.
For example:
QTextCursor cursor(textDocument);
cursor.beginEditBlock();
cursor.insertText("Hello");
cursor.insertText("World");
cursor.endEditBlock();
textDocument->undo();
The call to undo() will cause both insertions to be undone, causing both "World" and "Hello" to be removed.
It is possible to nest calls to beginEditBlock and endEditBlock. The top-most pair will determine the scope of the undo/redo operation.
See also
endEditBlock()
Definition at line 2552 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::append(), QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextControlPrivate::dropEvent(), QTextHtmlImporter::import(), QSyntaxHighlighterPrivate::rehighlight(), QDeclarativeTextEdit::select(), QTextControlPrivate::setContent(), QSyntaxHighlighter::setDocument(), QDeclarativeTextEditPrivate::updateSelection(), and QDeclarativeJS::TextWriter::write_helper().
 {
     if (!d || !d->priv)
         return;
     if (d->priv->editBlock == 0) // we are the initial edit block, store current cursor position for undo
         d->priv->editBlockCursorPosition = d->position;
     d->priv->beginEditBlock();
 }
block()
QTextBlock QTextCursor::block () const
Returns the block that contains the cursor.
Definition at line 1812 of file qtextcursor.cpp.
Referenced by charFormat(), QAccessibleTextEdit::childAt(), columnNumber(), currentTextLine(), QTextControlPrivate::cursorMoveKeyEvent(), QScriptDebuggerCodeView::event(), QTextControlPrivate::extendWordwiseSelection(), QScriptEdit::extraAreaMouseEvent(), QTextControlPrivate::indent(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), QTextTable::mergeCells(), QDeclarativeTextEdit::positionAt(), QTextHtmlImporter::processBlockNode(), select(), and QTextEdit::setText().
 {
     if (!d || !d->priv)
         return QTextBlock();
     return d->block();
 }
blockCharFormat()
QTextCharFormat QTextCursor::blockCharFormat () const
Returns the block character format of the block the cursor is in.
The block char format is the format used when inserting text at the beginning of an empty block.
See also
setBlockCharFormat()
Definition at line 1869 of file qtextcursor.cpp.
Referenced by QTextDocumentPrivate::ensureMaximumBlockCount(), and QTextHtmlImporter::processBlockNode().
 {
     if (!d || !d->priv)
         return QTextCharFormat();
     return d->block().charFormat();
 }
blockFormat()
QTextBlockFormat QTextCursor::blockFormat () const
Returns the block format of the block the cursor is in.
See also
setBlockFormat() charFormat()
Definition at line 1824 of file qtextcursor.cpp.
Referenced by QTextHtmlImporter::appendNodeText(), QAccessibleTextWidget::attributes(), QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), currentList(), QTextHtmlImporter::import(), QTextControlPrivate::indent(), insertBlock(), insertText(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), QTextControlPrivate::outdent(), and QTextHtmlImporter::processBlockNode().
 {
     if (!d || !d->priv)
         return QTextBlockFormat();
     return d->block().blockFormat();
 }
blockNumber()
int QTextCursor::blockNumber () const
Returns the number of the block the cursor is in, or 0 if the cursor is invalid.
Since
4.2
Note that this function only makes sense in documents without complex objects such as tables or frames.
Definition at line 2623 of file qtextcursor.cpp.
Referenced by QScriptEdit::currentLineNumber(), QScriptDebuggerCodeView::event(), and QScriptEdit::extraAreaMouseEvent().
 {
     if (!d || !d->priv)
         return 0;
     return d->block().blockNumber();
 }
charFormat()
QTextCharFormat QTextCursor::charFormat () const
Returns the format of the character immediately before the cursor position().
If the cursor is positioned at the beginning of a text block that is not empty then the format of the character immediately after the cursor is returned.
See also
insertText(), blockFormat()
Definition at line 1914 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControlPrivate::anchorForCursor(), QTextHtmlImporter::appendNodeText(), QAccessibleTextWidget::attributes(), QTextDocumentLayoutPrivate::drawListItem(), QTextDocumentFragmentPrivate::insert(), insertBlock(), insertText(), QTextBrowser::keyPressEvent(), QPlainTextEdit::keyPressEvent(), QTextEdit::keyPressEvent(), mergeCharFormat(), QTextControlPrivate::setContent(), and QTextControlPrivate::updateCurrentCharFormat().
 {
     if (!d || !d->priv)
         return QTextCharFormat();
     int idx = d->currentCharFormat;
     if (idx == -1) {
         QTextBlock block = d->block();
         int pos;
         if (d->position == block.position()
             && block.length() > 1)
             pos = d->position;
         else
             pos = d->position - 1;
         if (pos == -1) {
             idx = d->priv->blockCharFormatIndex(d->priv->blockMap().firstNode());
         } else {
             Q_ASSERT(pos >= 0 && pos < d->priv->length());
             QTextDocumentPrivate::FragmentIterator it = d->priv->find(pos);
             Q_ASSERT(!it.atEnd());
             idx = it.value()->format;
         }
     }
     QTextCharFormat cfmt = d->priv->formatCollection()->charFormat(idx);
     cfmt.clearProperty(QTextFormat::ObjectIndex);
     Q_ASSERT(cfmt.isValid());
     return cfmt;
 }
clearSelection()
void QTextCursor::clearSelection ()
Clears the current selection by setting the anchor to the cursor position.
Note that it does not delete the text of the selection.
See also
removeSelectedText() hasSelection()
Definition at line 1677 of file qtextcursor.cpp.
Referenced by QDeclarativeTextEdit::deselect(), QLabel::focusOutEvent(), QAccessibleTextWidget::removeSelection(), select(), QTextBrowserPrivate::setSource(), and QScriptEdit::updateExtraSelections().
 {
     if (!d)
         return;
     d->adjusted_anchor = d->anchor = d->position;
     d->currentCharFormat = -1;
 }
columnNumber()
int QTextCursor::columnNumber () const
Returns the position of the cursor within its containing line.
Since
4.2
Note that this is the column number relative to a wrapped line, not relative to the block (i.e. the paragraph).
You probably want to call positionInBlock() instead.
See also
positionInBlock()
Definition at line 2646 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return 0;
     QTextBlock block = d->block();
     if (!block.isValid())
         return 0;
     const QTextLayout *layout = d->blockLayout(block);
     const int relativePos = d->position - block.position();
     if (layout->lineCount() == 0)
         return relativePos;
     QTextLine line = layout->lineForTextPosition(relativePos);
     if (!line.isValid())
         return 0;
     return relativePos - line.textStart();
 }
createList() [1/2]
QTextList * QTextCursor::createList (const QTextListFormat & format)
Creates and returns a new list with the given format, and makes the current paragraph the cursor is in the first list item.
See also
insertList() currentList()
Definition at line 2142 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), createList(), QTextControlPrivate::indent(), insertList(), and QTextHtmlImporter::processBlockNode().
 {
     if (!d || !d->priv)
         return 0;
     QTextList *list = static_cast<QTextList *>(d->priv->createObject(format));
     QTextBlockFormat modifier;
     modifier.setObjectIndex(list->objectIndex());
     mergeBlockFormat(modifier);
     return list;
 }
createList() [2/2]
QTextList * QTextCursor::createList (QTextListFormat::Style style)
Creates and returns a new list with the given style, making the cursor's current paragraph the first list item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The style to be used is defined by the QTextListFormat::Style enum.
See also
insertList() currentList()
Definition at line 2167 of file qtextcursor.cpp.
 {
     QTextListFormat fmt;
     fmt.setStyle(style);
     return createList(fmt);
 }
currentFrame()
QTextFrame * QTextCursor::currentFrame () const
Returns a pointer to the current frame.
Returns 0 if the cursor is invalid.
See also
insertFrame()
Definition at line 2277 of file qtextcursor.cpp.
Referenced by boundingRectOfFloatsInSelection(), QTextControlPrivate::repaintOldAndNewSelection(), QTextHtmlImporter::scanTable(), and QTextControl::selectionRect().
 {
     if(!d || !d->priv)
         return 0;
     return d->priv->frameAt(d->position);
 }
currentList()
QTextList * QTextCursor::currentList () const
Returns the current list if the cursor position() is inside a block that is part of a list; otherwise returns 0.
See also
insertList() createList()
Definition at line 2180 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::indent(), QTextEdit::keyPressEvent(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), and QTextControlPrivate::outdent().
 {
     if (!d || !d->priv)
         return 0;
     QTextBlockFormat b = blockFormat();
     QTextObject *o = d->priv->objectForFormat(b);
     return qobject_cast<QTextList *>(o);
 }
currentTable()
QTextTable * QTextCursor::currentTable () const
Returns a pointer to the current table if the cursor position() is inside a block that is part of a table; otherwise returns 0.
See also
insertTable()
Definition at line 2240 of file qtextcursor.cpp.
Referenced by QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawFrame(), QTextControlPrivate::gotoNextTableCell(), QTextControlPrivate::gotoPreviousTableCell(), and QTextControl::selectionRect().
 {
     if(!d || !d->priv)
         return 0;
     QTextFrame *frame = d->priv->frameAt(d->position);
     while (frame) {
         QTextTable *table = qobject_cast<QTextTable *>(frame);
         if (table)
             return table;
         frame = frame->parentFrame();
     }
     return 0;
 }
deleteChar()
void QTextCursor::deleteChar ()
If there is no selected text, deletes the character at the current cursor position; otherwise deletes the selected text.
See also
deletePreviousChar() hasSelection() clearSelection()
Definition at line 1530 of file qtextcursor.cpp.
Referenced by QLabelPrivate::ensureTextPopulated(), QTextControlPrivate::keyPressEvent(), and QTextEdit::setText().
 {
     if (!d || !d->priv)
         return;
     if (d->position != d->anchor) {
         removeSelectedText();
         return;
     }
     if (!d->canDelete(d->position))
         return;
     d->adjusted_anchor = d->anchor =
                          d->priv->nextCursorPosition(d->anchor, QTextLayout::SkipCharacters);
     d->remove();
     d->setX();
 }
deletePreviousChar()
void QTextCursor::deletePreviousChar ()
If there is no selected text, deletes the character before the current cursor position; otherwise deletes the selected text.
See also
deleteChar() hasSelection() clearSelection()
Definition at line 1554 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::keyPressEvent(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), and QTextEdit::setText().
 {
     if (!d || !d->priv)
         return;
     if (d->position != d->anchor) {
         removeSelectedText();
         return;
     }
     if (d->anchor < 1 || !d->canDelete(d->anchor-1))
         return;
     d->anchor--;
     QTextDocumentPrivate::FragmentIterator fragIt = d->priv->find(d->anchor);
     const QTextFragmentData * const frag = fragIt.value();
     int fpos = fragIt.position();
     QChar uc = d->priv->buffer().at(d->anchor - fpos + frag->stringPosition);
     if (d->anchor > fpos && uc.isLowSurrogate()) {
         // second half of a surrogate, check if we have the first half as well,
         // if yes delete both at once
         uc = d->priv->buffer().at(d->anchor - 1 - fpos + frag->stringPosition);
         if (uc.isHighSurrogate())
             --d->anchor;
     }
     d->adjusted_anchor = d->anchor;
     d->remove();
     d->setX();
 }
document()
QTextDocument * QTextCursor::document () const
Returns the document this cursor is associated with.
Since
4.5
Definition at line 2675 of file qtextcursor.cpp.
Referenced by QLabelPrivate::ensureTextPopulated().
 {
     if (d->priv)
         return d->priv->document();
     return 0; // document went away
 }
endEditBlock()
void QTextCursor::endEditBlock ()
Indicates the end of a block of editing operations on the document that should appear as a single operation from an undo/redo point of view.
See also
beginEditBlock()
Definition at line 2593 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::append(), QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextControlPrivate::dropEvent(), QTextHtmlImporter::import(), QSyntaxHighlighterPrivate::rehighlight(), QDeclarativeTextEdit::select(), QTextControlPrivate::setContent(), QSyntaxHighlighter::setDocument(), QDeclarativeTextEditPrivate::updateSelection(), and QDeclarativeJS::TextWriter::write_helper().
 {
     if (!d || !d->priv)
         return;
     d->priv->endEditBlock();
 }
hasComplexSelection()
bool QTextCursor::hasComplexSelection () const
Returns true if the cursor contains a selection that is not simply a range from selectionStart() to selectionEnd(); otherwise returns false.
Complex selections are ones that span at least two cells in a table; their extent is specified by selectedTableCells().
Definition at line 1640 of file qtextcursor.cpp.
Referenced by QTextCopyHelper::copy(), QTextTable::mergeCells(), QTextControlPrivate::repaintOldAndNewSelection(), and QTextControl::selectionRect().
 {
     if (!d)
         return false;
     return d->complexSelectionTable() != 0;
 }
hasSelection()
bool QTextCursor::hasSelection () const
Returns true if the cursor contains a selection; otherwise returns false.
Definition at line 1627 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::_q_deleteSelected(), QTextControlPrivate::anchorForCursor(), QAccessibleTextEdit::copyText(), QTextBrowserPrivate::createHistoryEntry(), QAccessibleTextEdit::cutText(), QTextDocumentLayoutPrivate::drawBlock(), QLabel::focusOutEvent(), QTextBrowser::keyPressEvent(), QPlainTextEdit::keyPressEvent(), QTextEdit::keyPressEvent(), QPlainTextEdit::paintEvent(), QTextDocumentFragment::QTextDocumentFragment(), QTextDocumentFragmentPrivate::QTextDocumentFragmentPrivate(), QTextControlPrivate::repaintOldAndNewSelection(), QAccessibleTextWidget::selection(), QTextControlPrivate::selectionChanged(), QAccessibleTextWidget::selectionCount(), QTextControl::selectionRect(), and QTextControlPrivate::setClipboardSelection().
 {
     return !!d && d->position != d->anchor;
 }
insertBlock() [1/3]
void QTextCursor::insertBlock ()
Inserts a new empty block at the cursor position() with the current blockFormat() and charFormat().
See also
setBlockFormat()
Definition at line 2055 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::append(), QTextHtmlImporter::appendBlock(), insertBlock(), insertList(), QTextTable::mergeCells(), and QTextEdit::setText().
 {
     insertBlock(blockFormat());
 }
insertBlock() [2/3]
void QTextCursor::insertBlock (const QTextBlockFormat & format)
Inserts a new empty block at the cursor position() with block format format and the current charFormat() as block char format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setBlockFormat()
Definition at line 2071 of file qtextcursor.cpp.
 {
     QTextCharFormat charFmt = charFormat();
     charFmt.clearProperty(QTextFormat::ObjectType);
     insertBlock(format, charFmt);
 }
insertBlock() [3/3]
void QTextCursor::insertBlock (const QTextBlockFormat & format, const QTextCharFormat & charFormat)
Inserts a new empty block at the cursor position() with block format format and charFormat as block char format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setBlockFormat()
Definition at line 2090 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return;
     QTextCharFormat charFormat = _charFormat;
     charFormat.clearProperty(QTextFormat::ObjectIndex);
     d->priv->beginEditBlock();
     d->remove();
     d->insertBlock(format, charFormat);
     d->priv->endEditBlock();
     d->setX();
 }
insertFragment()
void QTextCursor::insertFragment (const QTextDocumentFragment & fragment)
Inserts the text fragment at the current position().
Definition at line 2289 of file qtextcursor.cpp.
Referenced by QTextDocument::clone(), insertHtml(), and QTextControl::print().
 {
     if (!d || !d->priv || fragment.isEmpty())
         return;
     d->priv->beginEditBlock();
     d->remove();
     fragment.d->insert(*this);
     d->priv->endEditBlock();
     if (fragment.d && fragment.d->doc)
         d->priv->mergeCachedResources(fragment.d->doc->docHandle());
 }
insertFrame()
QTextFrame * QTextCursor::insertFrame (const QTextFrameFormat & format)
Inserts a frame with the given format at the current cursor position(), moves the cursor position() inside the frame, and returns the frame.
If the cursor holds a selection, the whole selection is moved inside the frame.
See also
hasSelection()
Definition at line 2264 of file qtextcursor.cpp.
Referenced by QTextHtmlImporter::scanTable().
 {
     if (!d || !d->priv)
         return 0;
     return d->priv->insertFrame(selectionStart(), selectionEnd(), format);
 }
insertHtml()
void QTextCursor::insertHtml (const QString & html)
Inserts the text html at the current position().
Since
4.2 The text is interpreted as HTML.
Note
When using this function with a style sheet, the style sheet will only apply to the current block in the document. In order to apply a style sheet throughout a document, use QTextDocument::setDefaultStyleSheet() instead.
Definition at line 2319 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::append().
 {
     if (!d || !d->priv)
         return;
     QTextDocumentFragment fragment = QTextDocumentFragment::fromHtml(html, d->priv->document());
     insertFragment(fragment);
 }
insertImage() [1/4]
void QTextCursor::insertImage (const QTextImageFormat & format, QTextFrameFormat::Position alignment)
Inserts the image defined by the given format at the cursor's current position with the specified alignment.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.2
See also
position()
Definition at line 2341 of file qtextcursor.cpp.
Referenced by insertImage(), and QTextHtmlImporter::processSpecialNodes().
 {
     if (!d || !d->priv)
         return;
     QTextFrameFormat ffmt;
     ffmt.setPosition(alignment);
     QTextObject *obj = d->priv->createObject(ffmt);
     QTextImageFormat fmt = format;
     fmt.setObjectIndex(obj->objectIndex());
     d->priv->beginEditBlock();
     d->remove();
     const int idx = d->priv->formatCollection()->indexForFormat(fmt);
     d->priv->insert(d->position, QString(QChar(QChar::ObjectReplacementCharacter)), idx);
     d->priv->endEditBlock();
 }
insertImage() [2/4]
void QTextCursor::insertImage (const QTextImageFormat & format)
Inserts the image defined by format at the current position().
Definition at line 2363 of file qtextcursor.cpp.
 {
     insertText(QString(QChar::ObjectReplacementCharacter), format);
 }
insertImage() [3/4]
void QTextCursor::insertImage (const QString & name)
Convenience method for inserting the image with the given name at the current position().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QImage img = ...
textDocument->addResource(QTextDocument::ImageResource, QUrl("myimage"), img);
cursor.insertImage("myimage");
Definition at line 2379 of file qtextcursor.cpp.
 {
     QTextImageFormat format;
     format.setName(name);
     insertImage(format);
 }
insertImage() [4/4]
void QTextCursor::insertImage (const QImage & image, const QString & name = QString())
Convenience function for inserting the given image with an optional name at the current position().
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2396 of file qtextcursor.cpp.
 {
     if (image.isNull()) {
         qWarning("QTextCursor::insertImage: attempt to add an invalid image");
         return;
     }
     QString imageName = name;
     if (name.isEmpty())
         imageName = QString::number(image.serialNumber());
     d->priv->document()->addResource(QTextDocument::ImageResource, QUrl(imageName), image);
     QTextImageFormat format;
     format.setName(imageName);
     insertImage(format);
 }
insertList() [1/2]
QTextList * QTextCursor::insertList (const QTextListFormat & format)
Inserts a new block at the current position and makes it the first list item of a newly created list with the given format.
Returns the created list.
See also
currentList() createList() insertBlock()
Definition at line 2112 of file qtextcursor.cpp.
 {
     insertBlock();
     return createList(format);
 }
insertList() [2/2]
QTextList * QTextCursor::insertList (QTextListFormat::Style style)
Inserts a new block at the current position and makes it the first list item of a newly created list with the given style.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the created list.
See also
currentList(), createList(), insertBlock()
Definition at line 2130 of file qtextcursor.cpp.
 {
     insertBlock();
     return createList(style);
 }
insertTable() [1/2]
QTextTable * QTextCursor::insertTable (int rows, int columns, const QTextTableFormat & format)
Creates a new table with the given number of rows and columns in the specified format, inserts it at the current cursor position() in the document, and returns the table object.
The cursor is moved to the beginning of the first cell.
There must be at least one row and one column in the table.
See also
currentTable()
Definition at line 2220 of file qtextcursor.cpp.
Referenced by insertTable(), and QTextHtmlImporter::scanTable().
 {
     if(!d || !d->priv || rows == 0 || cols == 0)
         return 0;
     int pos = d->position;
     QTextTable *t = QTextTablePrivate::createTable(d->priv, d->position, rows, cols, format);
     d->setPosition(pos+1);
     // ##### what should we do if we have a selection?
     d->anchor = d->position;
     d->adjusted_anchor = d->anchor;
     return t;
 }
insertTable() [2/2]
QTextTable * QTextCursor::insertTable (int rows, int columns)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Creates a new table with the given number of rows and columns, inserts it at the current cursor position() in the document, and returns the table object.
The cursor is moved to the beginning of the first cell.
There must be at least one row and one column in the table.
See also
currentTable()
Definition at line 2203 of file qtextcursor.cpp.
 {
     return insertTable(rows, cols, QTextTableFormat());
 }
insertText() [1/2]
void QTextCursor::insertText (const QString & text)
Inserts text at the current position, using the current character format.
If there is a selection, the selection is deleted and replaced by text, for example:
cursor.clearSelection();
cursor.movePosition(QTextCursor::NextWord, QTextCursor::KeepAnchor);
cursor.insertText("Hello World");
This clears any existing selection, selects the word at the cursor (i.e. from position() forward), and replaces the selection with the phrase "Hello World".
Any ASCII linefeed characters (\n) in the inserted text are transformed into unicode block separators, corresponding to insertBlock() calls.
See also
charFormat() hasSelection()
Definition at line 1439 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::append(), QTextHtmlImporter::appendNodeText(), QDeclarativeJS::TextWriter::doReplace(), QTextDocumentFragment::fromPlainText(), QTextControlPrivate::inputMethodEvent(), insertImage(), QAccessibleTextWidget::insertText(), QTextTable::mergeCells(), QTextDocument::QTextDocument(), QAccessibleTextWidget::replaceText(), QTextDocument::setPlainText(), and QAccessibleTextEdit::setText().
 {
     QTextCharFormat fmt = charFormat();
     fmt.clearProperty(QTextFormat::ObjectType);
     insertText(text, fmt);
 }
insertText() [2/2]
void QTextCursor::insertText (const QString & text, const QTextCharFormat & format)
Inserts text at the current position with the given format.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1455 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return;
     Q_ASSERT(_format.isValid());
     QTextCharFormat format = _format;
     format.clearProperty(QTextFormat::ObjectIndex);
     bool hasEditBlock = false;
     if (d->anchor != d->position) {
         hasEditBlock = true;
         d->priv->beginEditBlock();
         d->remove();
     }
     if (!text.isEmpty()) {
         QTextFormatCollection *formats = d->priv->formatCollection();
         int formatIdx = formats->indexForFormat(format);
         Q_ASSERT(formats->format(formatIdx).isCharFormat());
         QTextBlockFormat blockFmt = blockFormat();
         int textStart = d->priv->text.length();
         int blockStart = 0;
         d->priv->text += text;
         int textEnd = d->priv->text.length();
         for (int i = 0; i < text.length(); ++i) {
             QChar ch = text.at(i);
             const int blockEnd = i;
             if (ch == QLatin1Char('\r')
                 && (i + 1) < text.length()
                 && text.at(i + 1) == QLatin1Char('\n')) {
                 ++i;
                 ch = text.at(i);
             }
             if (ch == QLatin1Char('\n')
                 || ch == QChar::ParagraphSeparator
                 || ch == QTextBeginningOfFrame
                 || ch == QTextEndOfFrame
                 || ch == QLatin1Char('\r')) {
                 if (!hasEditBlock) {
                     hasEditBlock = true;
                     d->priv->beginEditBlock();
                 }
                 if (blockEnd > blockStart)
                     d->priv->insert(d->position, textStart + blockStart, blockEnd - blockStart, formatIdx);
                 d->insertBlock(blockFmt, format);
                 blockStart = i + 1;
             }
         }
         if (textStart + blockStart < textEnd)
             d->priv->insert(d->position, textStart + blockStart, textEnd - textStart - blockStart, formatIdx);
     }
     if (hasEditBlock)
         d->priv->endEditBlock();
     d->setX();
 }
isCopyOf()
bool QTextCursor::isCopyOf (const QTextCursor & other) const
Returns true if this cursor and other are copies of each other, i.e.
one of them was created as a copy of the other and neither has moved since. This is much stricter than equality.
See also
operator=() operator==()
Definition at line 2608 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::_q_emitCursorPosChanged().
 {
     return d == other.d;
 }
isNull()
bool QTextCursor::isNull () const
Returns true if the cursor is null; otherwise returns false.
A null cursor is created by the default constructor.
Definition at line 1153 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::cursorMoveKeyEvent(), QTextControl::cursorRect(), QPlainTextEdit::cursorRect(), QTextEdit::cursorRect(), QTextControlPrivate::cursorRectPlusUnicodeDirectionMarkers(), QTextControl::find(), QTextDocument::find(), QTextDocumentFragmentPrivate::insert(), and QTextControlPrivate::repaintOldAndNewSelection().
 {
     return !d || !d->priv;
 }
joinPreviousEditBlock()
void QTextCursor::joinPreviousEditBlock ()
Like beginEditBlock() indicates the start of a block of editing operations that should appear as a single operation for undo/redo.
However unlike beginEditBlock() it does not start a new block but reverses the previous call to endEditBlock() and therefore makes following operations part of the previous edit block created.
For example:
QTextCursor cursor(textDocument);
cursor.beginEditBlock();
cursor.insertText("Hello");
cursor.insertText("World");
cursor.endEditBlock();
...
cursor.joinPreviousEditBlock();
cursor.insertText("Hey");
cursor.endEditBlock();
textDocument->undo();
The call to undo() will cause all three insertions to be undone.
See also
beginEditBlock(), endEditBlock()
Definition at line 2577 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return;
     d->priv->joinPreviousEditBlock();
 }
keepPositionOnInsert()
bool QTextCursor::keepPositionOnInsert () const
Returns whether the cursor should keep its current position when text gets inserted at the position of the cursor.
Since
4.7
The default is false;
See also
setKeepPositionOnInsert()
Definition at line 1391 of file qtextcursor.cpp.
 {
     return d ? d->keepPositionOnInsert : false;
 }
mergeBlockCharFormat()
void QTextCursor::mergeBlockCharFormat (const QTextCharFormat & modifier)
Modifies the block char format of the current block (or all blocks that are contained in the selection) with the block format specified by modifier.
See also
setBlockCharFormat()
Definition at line 1898 of file qtextcursor.cpp.
Referenced by QTextHtmlImporter::processBlockNode().
 {
     if (!d || !d->priv)
         return;
     d->setBlockCharFormat(modifier, QTextDocumentPrivate::MergeFormat);
 }
mergeBlockFormat()
void QTextCursor::mergeBlockFormat (const QTextBlockFormat & modifier)
Modifies the block format of the current block (or all blocks that are contained in the selection) with the block format specified by modifier.
See also
setBlockFormat(), blockFormat()
Definition at line 1853 of file qtextcursor.cpp.
Referenced by createList(), QSplashScreen::drawContents(), QTextControlPrivate::indent(), QTextControlPrivate::outdent(), QTextHtmlImporter::processBlockNode(), QTextHtmlImporter::processSpecialNodes(), and QTextEdit::setAlignment().
 {
     if (!d || !d->priv)
         return;
     d->setBlockFormat(modifier, QTextDocumentPrivate::MergeFormat);
 }
mergeCharFormat()
void QTextCursor::mergeCharFormat (const QTextCharFormat & modifier)
Merges the cursor's current character format with the properties described by format modifier.
If the cursor has a selection, this function applies all the properties set in modifier to all the character formats that are part of the selection.
See also
hasSelection(), setCharFormat()
Definition at line 1974 of file qtextcursor.cpp.
Referenced by QTextHtmlImporter::processSpecialNodes().
 {
     if (!d || !d->priv)
         return;
     if (d->position == d->anchor) {
         QTextCharFormat format = charFormat();
         format.merge(modifier);
         d->currentCharFormat = d->priv->formatCollection()->indexForFormat(format);
         return;
     }
     d->setCharFormat(modifier, QTextDocumentPrivate::MergeFormat);
 }
movePosition()
bool QTextCursor::movePosition (MoveOperation operation, MoveMode mode = MoveAnchor, int n = 1)
Moves the cursor by performing the given operation n times, using the specified mode, and returns true if all operations were completed successfully; otherwise returns false.
For example, if this function is repeatedly used to seek to the end of the next word, it will eventually fail when the end of the document is reached.
By default, the move operation is performed once (n = 1).
If mode is KeepAnchor, the cursor selects the text it moves over. This is the same effect that the user achieves when they hold down the Shift key and move the cursor with the cursor keys.
See also
setVisualNavigation()
Definition at line 1258 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControlPrivate::anchorForCursor(), QPlainTextEditPrivate::append(), QTextControlPrivate::append(), QAccessibleTextWidget::characterCount(), QTextControlPrivate::cursorMoveKeyEvent(), QTextDocumentPrivate::ensureMaximumBlockCount(), QLabelPrivate::ensureTextPopulated(), QTextControlPrivate::extendBlockwiseSelection(), QTextControlPrivate::extendWordwiseSelection(), QScriptDebuggerCodeView::find(), QTextDocumentFragmentPrivate::insert(), QDeclarativeTextEdit::moveCursorSelection(), QTextEditPrivate::pageUpDown(), QPlainTextEditPrivate::pageUpDown(), QTextHtmlImporter::processSpecialNodes(), QTextDocumentFragment::QTextDocumentFragment(), QSyntaxHighlighterPrivate::rehighlight(), select(), and QTextEdit::setText().
 {
     if (!d || !d->priv)
         return false;
     switch (op) {
     case Start:
     case StartOfLine:
     case End:
     case EndOfLine:
         n = 1;
         break;
     default: break;
     }
     int previousPosition = d->position;
     for (; n > 0; --n) {
         if (!d->movePosition(op, mode))
             return false;
     }
     if (d->visualNavigation && !d->block().isVisible()) {
         QTextBlock b = d->block();
         if (previousPosition < d->position) {
             while (!b.next().isVisible())
                 b = b.next();
             d->setPosition(b.position() + b.length() - 1);
         } else {
             while (!b.previous().isVisible())
                 b = b.previous();
             d->setPosition(b.position());
         }
         if (mode == QTextCursor::MoveAnchor)
             d->anchor = d->position;
         while (d->movePosition(op, mode)
                && !d->block().isVisible())
             ;
     }
     return true;
 }
operator!=()
bool QTextCursor::operator!= (const QTextCursor & rhs) const
Returns true if the other cursor is at a different position in the document as this cursor; otherwise returns false.
Definition at line 2420 of file qtextcursor.cpp.
 {
     return !operator==(rhs);
 }
operator<()
bool QTextCursor::operator< (const QTextCursor & rhs) const
Returns true if the other cursor is positioned later in the document than this cursor; otherwise returns false.
Definition at line 2434 of file qtextcursor.cpp.
 {
     if (!d)
         return !!rhs.d;
     if (!rhs.d)
         return false;
     Q_ASSERT_X(d->priv == rhs.d->priv, "QTextCursor::operator<", "cannot compare cursors attached to different documents");
     return d->position < rhs.d->position;
 }
operator<=()
bool QTextCursor::operator<= (const QTextCursor & rhs) const
Returns true if the other cursor is positioned later or at the same position in the document as this cursor; otherwise returns false.
Definition at line 2457 of file qtextcursor.cpp.
 {
     if (!d)
         return true;
     if (!rhs.d)
         return false;
     Q_ASSERT_X(d->priv == rhs.d->priv, "QTextCursor::operator<=", "cannot compare cursors attached to different documents");
     return d->position <= rhs.d->position;
 }
operator=()
QTextCursor & QTextCursor::operator= (const QTextCursor & cursor)
Makes a copy of cursor and assigns it to this QTextCursor.
Note that QTextCursor is an Implicitly Shared Classes{implicitly shared} class.
Definition at line 1136 of file qtextcursor.cpp.
 {
     d = cursor.d;
     return *this;
 }
operator==()
bool QTextCursor::operator== (const QTextCursor & rhs) const
Returns true if the other cursor is at the same position in the document as this cursor; otherwise returns false.
Definition at line 2479 of file qtextcursor.cpp.
Referenced by operator!=().
 {
     if (!d)
         return !rhs.d;
     if (!rhs.d)
         return false;
     return d->position == rhs.d->position && d->priv == rhs.d->priv;
 }
operator>()
bool QTextCursor::operator> (const QTextCursor & rhs) const
Returns true if the other cursor is positioned earlier in the document than this cursor; otherwise returns false.
Definition at line 2522 of file qtextcursor.cpp.
 {
     if (!d)
         return false;
     if (!rhs.d)
         return true;
     Q_ASSERT_X(d->priv == rhs.d->priv, "QTextCursor::operator>", "cannot compare cursors attached to different documents");
     return d->position > rhs.d->position;
 }
operator>=()
bool QTextCursor::operator>= (const QTextCursor & rhs) const
Returns true if the other cursor is positioned earlier or at the same position in the document as this cursor; otherwise returns false.
Definition at line 2500 of file qtextcursor.cpp.
 {
     if (!d)
         return false;
     if (!rhs.d)
         return true;
     Q_ASSERT_X(d->priv == rhs.d->priv, "QTextCursor::operator>=", "cannot compare cursors attached to different documents");
     return d->position >= rhs.d->position;
 }
position()
int QTextCursor::position () const
Returns the absolute position of the cursor within the document.
The cursor is positioned between characters.
See also
setPosition() movePosition() anchor() positionInBlock()
Definition at line 1196 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControlPrivate::anchorForCursor(), QTextHtmlImporter::appendNodeText(), QTextTable::cellAt(), QAccessibleTextWidget::characterCount(), QTextBrowserPrivate::createHistoryEntry(), currentTextLine(), QTextControlPrivate::cursorMoveKeyEvent(), QAccessibleTextWidget::cursorPosition(), QTextControl::cursorRect(), QTextControlPrivate::cursorRectPlusUnicodeDirectionMarkers(), QTextDocumentLayoutPrivate::drawBlock(), QLabelPrivate::ensureTextPopulated(), QScriptDebuggerCodeView::event(), QTextControlPrivate::extendBlockwiseSelection(), QTextControlPrivate::extendWordwiseSelection(), findInBlock(), QTextControlPrivate::inputMethodEvent(), QAccessibleTextEdit::invokeMethodEx(), QTextControlPrivate::mouseMoveEvent(), QTextControlPrivate::mousePressEvent(), QTextControlPrivate::mouseReleaseEvent(), QDeclarativeTextEdit::moveCursorSelection(), movePosition(), QPlainTextEdit::paintEvent(), QDeclarativeTextEdit::positionAt(), QTextHtmlImporter::processBlockNode(), QTextCopyHelper::QTextCopyHelper(), QSyntaxHighlighterPrivate::rehighlight(), QTextControlPrivate::repaintOldAndNewSelection(), QTextHtmlImporter::scanTable(), QDeclarativeTextEdit::setCursorPosition(), QTextControl::setExtraSelections(), QTextEdit::setText(), and QTextControl::setTextCursor().
 {
     if (!d || !d->priv)
         return -1;
     return d->position;
 }
positionInBlock()
int QTextCursor::positionInBlock () const
Returns the relative position of the cursor within the block.
Since
4.7
The cursor is positioned between characters.
This is equivalent to position() - block().position().
See also
position()
Definition at line 1215 of file qtextcursor.cpp.
 {
     if (!d || !d->priv)
         return 0;
     return d->position - d->block().position();
 }
removeSelectedText()
void QTextCursor::removeSelectedText ()
If there is a selection, its content is deleted; otherwise does nothing.
See also
hasSelection()
Definition at line 1691 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::_q_deleteSelected(), QPlainTextEditPrivate::append(), deleteChar(), deletePreviousChar(), QAccessibleTextWidget::deleteText(), QTextDocumentPrivate::ensureMaximumBlockCount(), QAccessibleTextWidget::replaceText(), and QTextControlPrivate::startDrag().
 {
     if (!d || !d->priv || d->position == d->anchor)
         return;
     d->priv->beginEditBlock();
     d->remove();
     d->priv->endEditBlock();
     d->setX();
 }
select()
void QTextCursor::select (SelectionType selection)
Selects text in the document according to the given selection.
Definition at line 1588 of file qtextcursor.cpp.
Referenced by QSplashScreen::drawContents(), QDeclarativeTextEdit::selectWord(), QTextControlPrivate::setContent(), and QAccessibleTextEdit::setText().
 {
     if (!d || !d->priv)
         return;
     clearSelection();
     const QTextBlock block = d->block();
     switch (selection) {
         case LineUnderCursor:
             movePosition(StartOfLine);
             movePosition(EndOfLine, KeepAnchor);
             break;
         case WordUnderCursor:
             movePosition(StartOfWord);
             movePosition(EndOfWord, KeepAnchor);
             break;
         case BlockUnderCursor:
             if (block.length() == 1) // no content
                 break;
             movePosition(StartOfBlock);
             // also select the paragraph separator
             if (movePosition(PreviousBlock)) {
                 movePosition(EndOfBlock);
                 movePosition(NextBlock, KeepAnchor);
             }
             movePosition(EndOfBlock, KeepAnchor);
             break;
         case Document:
             movePosition(Start);
             movePosition(End, KeepAnchor);
             break;
     }
 }
selectedTableCells()
void QTextCursor::selectedTableCells (int * firstRow, int * numRows, int * firstColumn, int * numColumns) const
If the selection spans over table cells, firstRow is populated with the number of the first row in the selection, firstColumn with the number of the first column in the selection, and numRows and numColumns with the number of rows and columns in the selection.
If the selection does not span any table cells the results are harmless but undefined.
Definition at line 1656 of file qtextcursor.cpp.
Referenced by QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawFrame(), QTextTable::mergeCells(), and selectedText().
 {
     *firstRow = -1;
     *firstColumn = -1;
     *numRows = -1;
     *numColumns = -1;
     if (!d || d->position == d->anchor)
         return;
     d->selectedTableCells(firstRow, numRows, firstColumn, numColumns);
 }
selectedText()
QString QTextCursor::selectedText () const
Returns the current selection's text (which may be empty).
This only returns the text, with no rich text formatting information. If you want a document fragment (i.e. formatted rich text) use selection() instead.
Note
If the selection obtained from an editor spans a line break, the text will contain a Unicode U+2029 paragraph separator character instead of a newline
character. Use QString::replace() to replace these characters with newlines.
Definition at line 1753 of file qtextcursor.cpp.
Referenced by QDeclarativeJS::TextWriter::doMove(), QLabelPrivate::ensureTextPopulated(), and QAccessibleTextWidget::text().
 {
     if (!d || !d->priv || d->position == d->anchor)
         return QString();
     const QString docText = d->priv->buffer();
     QString text;
     QTextTable *table = d->complexSelectionTable();
     if (table) {
         int row_start, col_start, num_rows, num_cols;
         selectedTableCells(&row_start, &num_rows, &col_start, &num_cols);
         Q_ASSERT(row_start != -1);
         for (int r = row_start; r < row_start + num_rows; ++r) {
             for (int c = col_start; c < col_start + num_cols; ++c) {
                 QTextTableCell cell = table->cellAt(r, c);
                 int rspan = cell.rowSpan();
                 int cspan = cell.columnSpan();
                 if (rspan != 1) {
                     int cr = cell.row();
                     if (cr != r)
                         continue;
                 }
                 if (cspan != 1) {
                     int cc = cell.column();
                     if (cc != c)
                         continue;
                 }
                 getText(text, d->priv, docText, cell.firstPosition(), cell.lastPosition());
             }
         }
     } else {
         getText(text, d->priv, docText, selectionStart(), selectionEnd());
     }
     return text;
 }
selection()
QTextDocumentFragment QTextCursor::selection () const
Returns the current selection (which may be empty) with all its formatting information.
If you just want the selected text (i.e. plain text) use selectedText() instead.
Note
Unlike QTextDocumentFragment::toPlainText(), selectedText() may include special unicode characters such as QChar::ParagraphSeparator.
See also
QTextDocumentFragment::toPlainText()
Definition at line 1804 of file qtextcursor.cpp.
 {
     return QTextDocumentFragment(*this);
 }
selectionEnd()
int QTextCursor::selectionEnd () const
Returns the end of the selection or position() if the cursor doesn't have a selection.
See also
selectionStart() position() anchor()
Definition at line 1721 of file qtextcursor.cpp.
Referenced by boundingRectOfFloatsInSelection(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentPrivate::ensureMaximumBlockCount(), QTextControlPrivate::extendBlockwiseSelection(), QTextControlPrivate::extendWordwiseSelection(), QTextDocument::find(), QTextControl::findNextPrevAnchor(), insertFrame(), QPlainTextEdit::paintEvent(), selectedText(), QAccessibleTextWidget::selection(), QTextControl::selectionRect(), QTextControl::setFocusToAnchor(), and QDeclarativeTextEditPrivate::updateSelection().
 {
     if (!d || !d->priv)
         return -1;
     return qMax(d->position, d->adjusted_anchor);
 }
selectionStart()
int QTextCursor::selectionStart () const
Returns the start of the selection or position() if the cursor doesn't have a selection.
See also
selectionEnd() position() anchor()
Definition at line 1708 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControlPrivate::anchorForCursor(), boundingRectOfFloatsInSelection(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentPrivate::ensureMaximumBlockCount(), QTextControlPrivate::extendBlockwiseSelection(), QTextControlPrivate::extendWordwiseSelection(), QTextDocument::find(), QTextControl::findNextPrevAnchor(), insertFrame(), QPlainTextEdit::paintEvent(), selectedText(), QAccessibleTextWidget::selection(), QTextControl::selectionRect(), QTextControl::setFocusToAnchor(), and QDeclarativeTextEditPrivate::updateSelection().
 {
     if (!d || !d->priv)
         return -1;
     return qMin(d->position, d->adjusted_anchor);
 }
setBlockCharFormat()
void QTextCursor::setBlockCharFormat (const QTextCharFormat & format)
Sets the block char format of the current block (or all blocks that are contained in the selection) to format.
See also
blockCharFormat()
Definition at line 1883 of file qtextcursor.cpp.
Referenced by QTextDocumentPrivate::ensureMaximumBlockCount(), and QTextHtmlImporter::processBlockNode().
 {
     if (!d || !d->priv)
         return;
     d->setBlockCharFormat(format, QTextDocumentPrivate::SetFormatAndPreserveObjectIndices);
 }
setBlockFormat()
void QTextCursor::setBlockFormat (const QTextBlockFormat & format)
Sets the block format of the current block (or all blocks that are contained in the selection) to format.
See also
blockFormat(), mergeBlockFormat()
Definition at line 1838 of file qtextcursor.cpp.
Referenced by QTextHtmlImporter::appendNodeText(), QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextHtmlImporter::import(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), and QTextHtmlImporter::processBlockNode().
 {
     if (!d || !d->priv)
         return;
     d->setBlockFormat(format, QTextDocumentPrivate::SetFormat);
 }
setCharFormat()
void QTextCursor::setCharFormat (const QTextCharFormat & format)
Sets the cursor's current character format to the given format.
If the cursor has a selection, the given format is applied to the current selection.
See also
hasSelection(), mergeCharFormat()
Definition at line 1955 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::append(), and QTextControlPrivate::setContent().
 {
     if (!d || !d->priv)
         return;
     if (d->position == d->anchor) {
         d->currentCharFormat = d->priv->formatCollection()->indexForFormat(format);
         return;
     }
     d->setCharFormat(format, QTextDocumentPrivate::SetFormatAndPreserveObjectIndices);
 }
setKeepPositionOnInsert()
void QTextCursor::setKeepPositionOnInsert (bool b)
Defines whether the cursor should keep its current position when text gets inserted at the current position of the cursor.
Since
4.7
If b is true, the cursor keeps its current position when text gets inserted at the positing of the cursor. If b is false, the cursor moves along with the inserted text.
The default is false.
Note that a cursor always moves when text is inserted before the current position of the cursor, and it always keeps its position when text is inserted after the current position of the cursor.
See also
keepPositionOnInsert()
Definition at line 1415 of file qtextcursor.cpp.
 {
     if (d)
         d->keepPositionOnInsert = b;
 }
setPosition()
void QTextCursor::setPosition (int pos, MoveMode m = MoveAnchor)
Moves the cursor to the absolute position in the document specified by pos using a MoveMode specified by m.
The cursor is positioned between characters.
See also
position() movePosition() anchor()
Definition at line 1165 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControlPrivate::anchorForCursor(), QAccessibleTextWidget::attributes(), QTextControl::cursorForPosition(), QDeclarativeJS::TextWriter::doMove(), QDeclarativeJS::TextWriter::doReplace(), QTextControlPrivate::extendBlockwiseSelection(), QTextControlPrivate::extendWordwiseSelection(), QScriptEdit::extraAreaMouseEvent(), findInBlock(), QTextControl::findNextPrevAnchor(), QTextControlPrivate::inputMethodEvent(), QAccessibleTextWidget::insertText(), QDeclarativeTextEdit::moveCursorSelection(), QAccessibleTextEdit::pasteText(), QDeclarativeTextEdit::positionToRectangle(), QTextHtmlImporter::processBlockNode(), QTextDocument::redo(), QTextControlPrivate::repaintOldAndNewSelection(), QTextBrowserPrivate::restoreHistoryEntry(), QTextHtmlImporter::scanTable(), QAccessibleTextEdit::scrollToSubstring(), QDeclarativeTextEdit::select(), QAccessibleTextWidget::setCursorPosition(), QTextControlPrivate::setCursorPosition(), QDeclarativeTextEdit::setCursorPosition(), QAccessibleTextWidget::setSelection(), QLabel::setSelection(), QAccessibleTextWidget::text(), QAccessibleTextWidget::textCursorForRange(), QTextDocument::undo(), and QDeclarativeTextEditPrivate::updateSelection().
 {
     if (!d || !d->priv)
         return;
     if (pos < 0 || pos >= d->priv->length()) {
         qWarning("QTextCursor::setPosition: Position '%d' out of range", pos);
         return;
     }
     d->setPosition(pos);
     if (m == MoveAnchor) {
         d->anchor = pos;
         d->adjusted_anchor = pos;
     } else { // keep anchor
         QTextCursor::MoveOperation op;
         if (pos < d->anchor)
             op = QTextCursor::Left;
         else
             op = QTextCursor::Right;
         d->adjustCursor(op);
     }
     d->setX();
 }
setVerticalMovementX()
void QTextCursor::setVerticalMovementX (int x)
Sets the visual x position for vertical cursor movements to x.
Since
4.7
The vertical movement x position is cleared automatically when the cursor moves horizontally, and kept unchanged when the cursor moves vertically. The mechanism allows the cursor to move up and down on a visually straight line with proportional fonts, and to gently "jump" over short lines.
A value of -1 indicates no predefined x position. It will then be set automatically the next time the cursor moves up or down.
See also
verticalMovementX()
Definition at line 1355 of file qtextcursor.cpp.
 {
     if (d)
         d->x = x;
 }
setVisualNavigation()
void QTextCursor::setVisualNavigation (bool b)
Sets visual navigation to b.
Since
4.4
Visual navigation means skipping over hidden text pragraphs. The default is false.
See also
visualNavigation(), movePosition()
Definition at line 1331 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::cursorMoveKeyEvent(), and QPlainTextEditPrivate::pageUpDown().
 {
     if (d)
         d->visualNavigation = b;
 }
verticalMovementX()
int QTextCursor::verticalMovementX () const
Returns the visual x position for vertical cursor movements.
Since
4.7
A value of -1 indicates no predefined x position. It will then be set automatically the next time the cursor moves up or down.
See also
setVerticalMovementX()
Definition at line 1373 of file qtextcursor.cpp.
 {
     return d ? d->x : -1;
 }
visualNavigation()
bool QTextCursor::visualNavigation () const
Returns true if the cursor does visual navigation; otherwise returns false.
Since
4.4
Visual navigation means skipping over hidden text pragraphs. The default is false.
See also
setVisualNavigation(), movePosition()
Definition at line 1313 of file qtextcursor.cpp.
Referenced by QTextControlPrivate::cursorMoveKeyEvent().
 {
     return d ? d->visualNavigation : false;
 }
Friends and Related Functions
QTextControlPrivate
friend class QTextControlPrivate friend
Definition at line 233 of file qtextcursor.h.
QTextCopyHelper
friend class QTextCopyHelper friend
Definition at line 232 of file qtextcursor.h.
QTextDocumentFragmentPrivate
friend class QTextDocumentFragmentPrivate friend
Definition at line 231 of file qtextcursor.h.
Properties
d
QSharedDataPointer<QTextCursorPrivate> QTextCursor::d private
Definition at line 230 of file qtextcursor.h.
Referenced by anchor(), atBlockEnd(), atBlockStart(), atEnd(), atStart(), beginEditBlock(), block(), blockCharFormat(), blockFormat(), blockNumber(), charFormat(), clearSelection(), columnNumber(), createList(), currentFrame(), currentList(), currentTable(), deleteChar(), deletePreviousChar(), document(), endEditBlock(), hasComplexSelection(), hasSelection(), QTextDocumentFragmentPrivate::insert(), insertBlock(), insertFragment(), insertFrame(), insertHtml(), insertImage(), insertTable(), insertText(), isCopyOf(), isNull(), joinPreviousEditBlock(), keepPositionOnInsert(), mergeBlockCharFormat(), mergeBlockFormat(), mergeCharFormat(), movePosition(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), position(), positionInBlock(), QTextCopyHelper::QTextCopyHelper(), QTextCursor(), QTextDocumentFragmentPrivate::QTextDocumentFragmentPrivate(), removeSelectedText(), select(), selectedTableCells(), selectedText(), selectionEnd(), selectionStart(), setBlockCharFormat(), setBlockFormat(), setCharFormat(), setKeepPositionOnInsert(), setPosition(), setVerticalMovementX(), setVisualNavigation(), verticalMovementX(), and visualNavigation().
The documentation for this class was generated from the following files:
/src/gui/text/qtextcursor.h
/src/gui/text/qtextcursor.cpp