Qt 4.8: QTextFrame::iterator Class Reference
QTextFrame::iterator Class Reference
The iterator class provides an iterator for reading the contents of a QTextFrame.
#include <qtextobject.h>
Public Functions
bool atEnd () const
Returns true if the current item is the last item in the text frame.
QTextBlock currentBlock () const
Returns the current block the iterator points to.
QTextFrame * currentFrame () const
Returns the current frame pointed to by the iterator, or 0 if the iterator currently points to a block.
iterator ()
Constructs an invalid iterator.
iterator (const iterator &o)
Copy constructor.
bool operator!= (const iterator &o) const
Retuns true if the iterator is different from the other iterator; otherwise returns false.
iterator & operator++ ()
Moves the iterator to the next frame or block.
iterator operator++ (int)
The postfix ++ operator (i++) advances the iterator to the next item in the text frame, and returns an iterator to the old item.
iterator & operator-- ()
Moves the iterator to the previous frame or block.
iterator operator-- (int)
The postfix – operator (i–) makes the preceding item in the current frame, and returns an iterator to the old item.
iterator & operator= (const iterator &o)
Assigns other to this iterator and returns a reference to this iterator.
bool operator== (const iterator &o) const
Retuns true if the iterator is the same as the other iterator; otherwise returns false.
QTextFrame * parentFrame () const
Returns the parent frame of the current frame.
Private Functions
iterator (QTextFrame *frame, int block, int begin, int end)
Properties
int b
int cb
QTextFrame * cf
int e
QTextFrame * f
Friends
class QTextDocumentLayoutPrivate
class QTextFrame
class QTextTableCell
Detailed Description
The iterator class provides an iterator for reading the contents of a QTextFrame.
Note
This class or function is reentrant.
A frame consists of an arbitrary sequence of QTextBlock and child QTextFrame. This class provides a way to iterate over the child objects of a frame, and read their contents. It does not provide a way to modify the contents of the frame.
Definition at line 144 of file qtextobject.h.
Constructors and Destructors
iterator() [1/3]
QTextFrame::iterator::iterator (QTextFrame * frame, int block, int begin, int end) private
Warning
This function is not part of the public interface.
Definition at line 695 of file qtextobject.cpp.
 {
     f = frame;
     b = begin;
     e = end;
     cf = 0;
     cb = block;
 }
iterator() [2/3]
QTextFrame::iterator::iterator ()
Constructs an invalid iterator.
Definition at line 683 of file qtextobject.cpp.
 {
     f = 0;
     b = 0;
     e = 0;
     cf = 0;
     cb = 0;
 }
iterator() [3/3]
QTextFrame::iterator::iterator (const iterator & other)
Copy constructor.
Constructs a copy of the other iterator.
Definition at line 707 of file qtextobject.cpp.
 {
     f = other.f;
     b = other.b;
     e = other.e;
     cf = other.cf;
     cb = other.cb;
 }
Functions
atEnd()
bool QTextFrame::iterator::atEnd () const inline
Returns true if the current item is the last item in the text frame.
Definition at line 165 of file qtextobject.h.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextHtmlExporter::emitFrame(), flowPosition(), QTextDocumentLayoutPrivate::hitTest(), isEmptyBlockBeforeTable(), QTextDocumentLayoutPrivate::layoutFlow(), and QTextOdfWriter::writeFrame().
 { return !cf && cb == e; }
currentBlock()
QTextBlock QTextFrame::iterator::currentBlock () const
Returns the current block the iterator points to.
If the iterator points to a child frame, the returned block is invalid.
See also
currentFrame()
Definition at line 747 of file qtextobject.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextHtmlExporter::emitFrame(), flowPosition(), QTextDocumentLayoutPrivate::hitTest(), isEmptyBlockBeforeTable(), QTextDocumentLayoutPrivate::layoutFlow(), and QTextOdfWriter::writeFrame().
 {
     if (!f)
         return QTextBlock();
     return QTextBlock(f->docHandle(), cb);
 }
currentFrame()
QTextFrame * QTextFrame::iterator::currentFrame () const
Returns the current frame pointed to by the iterator, or 0 if the iterator currently points to a block.
See also
currentBlock()
Definition at line 736 of file qtextobject.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextHtmlExporter::emitFrame(), flowPosition(), QTextDocumentLayoutPrivate::hitTest(), isEmptyBlockBeforeTable(), QTextDocumentLayoutPrivate::layoutFlow(), and QTextOdfWriter::writeFrame().
 {
     return cf;
 }
operator!=()
bool QTextFrame::iterator::operator!= (const iterator & o) const inline
Retuns true if the iterator is different from the other iterator; otherwise returns false.
Definition at line 168 of file qtextobject.h.
 { return f != o.f || cf != o.cf || cb != o.cb; }
operator++() [1/2]
QTextFrame::iterator & QTextFrame::iterator::operator++ ()
Moves the iterator to the next frame or block.
See also
currentBlock() currentFrame()
Definition at line 759 of file qtextobject.cpp.
 {
     const QTextDocumentPrivate *priv = f->docHandle();
     const QTextDocumentPrivate::BlockMap &map = priv->blockMap();
     if (cf) {
         int end = cf->lastPosition() + 1;
         cb = map.findNode(end);
         cf = 0;
     } else if (cb) {
         cb = map.next(cb);
         if (cb == e)
             return *this;
         if (!f->d_func()->childFrames.isEmpty()) {
             int pos = map.position(cb);
             // check if we entered a frame
             QTextDocumentPrivate::FragmentIterator frag = priv->find(pos-1);
             if (priv->buffer().at(frag->stringPosition) != QChar::ParagraphSeparator) {
                 QTextFrame *nf = qobject_cast<QTextFrame *>(priv->objectForFormat(frag->format));
                 if (nf) {
                     if (priv->buffer().at(frag->stringPosition) == QTextBeginningOfFrame && nf != f) {
                         cf = nf;
                         cb = 0;
                     } else {
                         Q_ASSERT(priv->buffer().at(frag->stringPosition) != QTextEndOfFrame);
                     }
                 }
             }
         }
     }
     return *this;
 }
operator++() [2/2]
QTextFrame::iterator QTextFrame::iterator::operator++ (int) inline
The postfix ++ operator (i++) advances the iterator to the next item in the text frame, and returns an iterator to the old item.
Definition at line 170 of file qtextobject.h.
Referenced by operator++().
 { iterator tmp = *this; operator++(); return tmp; }
operator--() [1/2]
QTextFrame::iterator & QTextFrame::iterator::operator-- ()
Moves the iterator to the previous frame or block.
See also
currentBlock() currentFrame()
Definition at line 797 of file qtextobject.cpp.
 {
     const QTextDocumentPrivate *priv = f->docHandle();
     const QTextDocumentPrivate::BlockMap &map = priv->blockMap();
     if (cf) {
         int start = cf->firstPosition() - 1;
         cb = map.findNode(start);
         cf = 0;
     } else {
         if (cb == b)
             goto end;
         if (cb != e) {
             int pos = map.position(cb);
             // check if we have to enter a frame
             QTextDocumentPrivate::FragmentIterator frag = priv->find(pos-1);
             if (priv->buffer().at(frag->stringPosition) != QChar::ParagraphSeparator) {
                 QTextFrame *pf = qobject_cast<QTextFrame *>(priv->objectForFormat(frag->format));
                 if (pf) {
                     if (priv->buffer().at(frag->stringPosition) == QTextBeginningOfFrame) {
                         Q_ASSERT(pf == f);
                     } else if (priv->buffer().at(frag->stringPosition) == QTextEndOfFrame) {
                         Q_ASSERT(pf != f);
                         cf = pf;
                         cb = 0;
                         goto end;
                     }
                 }
             }
         }
         cb = map.previous(cb);
     }
  end:
     return *this;
 }
operator--() [2/2]
QTextFrame::iterator QTextFrame::iterator::operator-- (int) inline
The postfix – operator (i–) makes the preceding item in the current frame, and returns an iterator to the old item.
Definition at line 172 of file qtextobject.h.
Referenced by operator--().
 { iterator tmp = *this; operator--(); return tmp; }
operator=()
QTextFrame::iterator & QTextFrame::iterator::operator= (const iterator & o)
Assigns other to this iterator and returns a reference to this iterator.
Definition at line 720 of file qtextobject.cpp.
 {
     f = other.f;
     b = other.b;
     e = other.e;
     cf = other.cf;
     cb = other.cb;
     return *this;
 }
operator==()
bool QTextFrame::iterator::operator== (const iterator & o) const inline
Retuns true if the iterator is the same as the other iterator; otherwise returns false.
Definition at line 167 of file qtextobject.h.
 { return f == o.f && cf == o.cf && cb == o.cb; }
parentFrame()
QTextFrame * QTextFrame::iterator::parentFrame () const inline
Returns the parent frame of the current frame.
See also
currentFrame() QTextFrame::parentFrame()
Definition at line 160 of file qtextobject.h.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextHtmlExporter::emitFrame(), QTextDocumentLayoutPrivate::hitTest(), and QTextDocumentLayoutPrivate::layoutFlow().
 { return f; }
Friends and Related Functions
QTextDocumentLayoutPrivate
friend class QTextDocumentLayoutPrivate friend
Definition at line 153 of file qtextobject.h.
QTextFrame
friend class QTextFrame friend
Definition at line 151 of file qtextobject.h.
QTextTableCell
friend class QTextTableCell friend
Definition at line 152 of file qtextobject.h.
Properties
b
int QTextFrame::iterator::b private
Definition at line 146 of file qtextobject.h.
Referenced by iterator(), and operator=().
cb
int QTextFrame::iterator::cb private
Definition at line 149 of file qtextobject.h.
Referenced by QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), iterator(), operator!=(), operator=(), and operator==().
cf
QTextFrame* QTextFrame::iterator::cf private
Definition at line 148 of file qtextobject.h.
Referenced by QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), iterator(), operator!=(), operator=(), and operator==().
e
int QTextFrame::iterator::e private
Definition at line 147 of file qtextobject.h.
Referenced by iterator(), and operator=().
f
QTextFrame* QTextFrame::iterator::f private
Definition at line 145 of file qtextobject.h.
Referenced by iterator(), operator!=(), operator=(), and operator==().
The documentation for this class was generated from the following files:
/src/gui/text/qtextobject.h
/src/gui/text/qtextobject.cpp