Qt 4.8: QTestElement Class Reference
QTestElement Class Reference
#include <qtestelement.h>
Public Functions
bool addLogElement (QTestElement *element)
QTestElement * childElements () const
const QTestElement * parentElement () const
QTestElement (int type=-1)
void setParent (const QTestElement *p)
~QTestElement ()
Public Functions inherited from QTestCoreElement< QTestElement >
void addAttribute (const QTest::AttributeIndex index, const char *value)
const QTestElementAttribute * attribute (QTest::AttributeIndex index) const
const char * attributeName (QTest::AttributeIndex index) const
QTestElementAttribute * attributes () const
const char * attributeValue (QTest::AttributeIndex index) const
const char * elementName () const
QTest::LogElementType elementType () const
QTestCoreElement (int type=-1)
virtual ~QTestCoreElement ()
Public Functions inherited from QTestCoreList< QTestElement >
void addToList (QTestElement **list)
int count (QTestElement *list)
int count ()
QTestElement * nextElement ()
QTestElement * previousElement ()
QTestCoreList ()
virtual ~QTestCoreList ()
Properties
QTestElement * listOfChildren
const QTestElement * parent
Detailed Description
Definition at line 53 of file qtestelement.h.
Constructors and Destructors
QTestElement()
QTestElement::QTestElement (int type = -1)
Definition at line 46 of file qtestelement.cpp.
     :QTestCoreElement<QTestElement>(type),
     listOfChildren(0),
     parent(0)
 {
 }
~QTestElement()
QTestElement::~QTestElement ()
Definition at line 53 of file qtestelement.cpp.
 {
     delete listOfChildren;
 }
Functions
addLogElement()
bool QTestElement::addLogElement (QTestElement * element)
Definition at line 58 of file qtestelement.cpp.
Referenced by QTestLogger::addBenchmarkResult(), QTestLogger::addIncident(), QTestLogger::addMessage(), and QTestLogger::stopLogging().
 {
     if(!element)
         return false;
     if(element->elementType() != QTest::LET_Undefined){
         element->addToList(&listOfChildren);
         element->setParent(this);
         return true;
     }
     return false;
 }
childElements()
QTestElement * QTestElement::childElements () const
Definition at line 72 of file qtestelement.cpp.
Referenced by QTestXunitStreamer::formatAfterAttributes(), QTestLightXmlStreamer::formatBeforeAttributes(), QTestXunitStreamer::formatEnd(), QTestXmlStreamer::formatEnd(), QTestLightXmlStreamer::formatEnd(), QTestXunitStreamer::outputElements(), and QTestBasicStreamer::outputElements().
 {
     return listOfChildren;
 }
parentElement()
const QTestElement * QTestElement::parentElement () const
Definition at line 77 of file qtestelement.cpp.
Referenced by QTestXunitStreamer::formatAfterAttributes(), QTestXunitStreamer::formatAttributes(), QTestXunitStreamer::formatStart(), and QTestXunitStreamer::indentForElement().
 {
     return parent;
 }
setParent()
void QTestElement::setParent (const QTestElement * p)
Definition at line 82 of file qtestelement.cpp.
Referenced by addLogElement(), and QTestLogger::stopLogging().
 {
     parent = p;
 }
Properties
listOfChildren
QTestElement* QTestElement::listOfChildren private
Definition at line 66 of file qtestelement.h.
Referenced by addLogElement(), childElements(), and ~QTestElement().
parent
const QTestElement* QTestElement::parent private
Definition at line 67 of file qtestelement.h.
Referenced by parentElement(), and setParent().
The documentation for this class was generated from the following files:
/src/testlib/qtestelement.h
/src/testlib/qtestelement.cpp