Qt 4.8: QDeclarativePinchEvent Class Reference
QDeclarativePinchEvent Class Reference
#include <qdeclarativepincharea_p.h>
Public Functions
bool accepted () const
qreal angle () const
QPointF center () const
QPointF point1 () const
QPointF point2 () const
int pointCount () const
qreal previousAngle () const
QPointF previousCenter () const
qreal previousScale () const
QDeclarativePinchEvent (QPointF c, qreal s, qreal a, qreal r)
qreal rotation () const
qreal scale () const
void setAccepted (bool a)
void setPoint1 (QPointF p)
void setPoint2 (QPointF p)
void setPointCount (int count)
void setPreviousAngle (qreal a)
void setPreviousCenter (QPointF c)
void setPreviousScale (qreal s)
void setStartCenter (QPointF c)
void setStartPoint1 (QPointF p)
void setStartPoint2 (QPointF p)
QPointF startCenter () const
QPointF startPoint1 () const
QPointF startPoint2 () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool accepted
qreal angle
QPointF center
bool m_accepted
qreal m_angle
QPointF m_center
qreal m_lastAngle
QPointF m_lastCenter
qreal m_lastScale
QPointF m_point1
QPointF m_point2
int m_pointCount
qreal m_rotation
qreal m_scale
QPointF m_startCenter
QPointF m_startPoint1
QPointF m_startPoint2
QPointF point1
QPointF point2
int pointCount
qreal previousAngle
QPointF previousCenter
qreal previousScale
qreal rotation
qreal scale
QPointF startCenter
QPointF startPoint1
QPointF startPoint2
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 190 of file qdeclarativepincharea_p.h.
Constructors and Destructors
QDeclarativePinchEvent()
QDeclarativePinchEvent::QDeclarativePinchEvent (QPointF c, qreal s, qreal a, qreal r) inline
Definition at line 210 of file qdeclarativepincharea_p.h.
         : QObject(), m_center(c), m_scale(s), m_angle(a), m_rotation(r)
         , m_pointCount(0), m_accepted(true) {}
Functions
accepted()
bool QDeclarativePinchEvent::accepted () const inline
Definition at line 237 of file qdeclarativepincharea_p.h.
 { return m_accepted; }
angle()
qreal QDeclarativePinchEvent::angle () const inline
Definition at line 222 of file qdeclarativepincharea_p.h.
 { return m_angle; }
center()
QPointF QDeclarativePinchEvent::center () const inline
Definition at line 214 of file qdeclarativepincharea_p.h.
 { return m_center; }
point1()
QPointF QDeclarativePinchEvent::point1 () const inline
Definition at line 226 of file qdeclarativepincharea_p.h.
 { return m_point1; }
point2()
QPointF QDeclarativePinchEvent::point2 () const inline
Definition at line 230 of file qdeclarativepincharea_p.h.
 { return m_point2; }
pointCount()
int QDeclarativePinchEvent::pointCount () const inline
Definition at line 234 of file qdeclarativepincharea_p.h.
 { return m_pointCount; }
previousAngle()
qreal QDeclarativePinchEvent::previousAngle () const inline
Definition at line 223 of file qdeclarativepincharea_p.h.
 { return m_lastAngle; }
previousCenter()
QPointF QDeclarativePinchEvent::previousCenter () const inline
Definition at line 217 of file qdeclarativepincharea_p.h.
 { return m_lastCenter; }
previousScale()
qreal QDeclarativePinchEvent::previousScale () const inline
Definition at line 220 of file qdeclarativepincharea_p.h.
 { return m_lastScale; }
rotation()
qreal QDeclarativePinchEvent::rotation () const inline
Definition at line 225 of file qdeclarativepincharea_p.h.
 { return m_rotation; }
scale()
qreal QDeclarativePinchEvent::scale () const inline
Definition at line 219 of file qdeclarativepincharea_p.h.
 { return m_scale; }
setAccepted()
void QDeclarativePinchEvent::setAccepted (bool a) inline
Definition at line 238 of file qdeclarativepincharea_p.h.
 { m_accepted = a; }
setPoint1()
void QDeclarativePinchEvent::setPoint1 (QPointF p) inline
Definition at line 227 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_point1 = p; }
setPoint2()
void QDeclarativePinchEvent::setPoint2 (QPointF p) inline
Definition at line 231 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_point2 = p; }
setPointCount()
void QDeclarativePinchEvent::setPointCount (int count) inline
Definition at line 235 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_pointCount = count; }
setPreviousAngle()
void QDeclarativePinchEvent::setPreviousAngle (qreal a) inline
Definition at line 224 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_lastAngle = a; }
setPreviousCenter()
void QDeclarativePinchEvent::setPreviousCenter (QPointF c) inline
Definition at line 218 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_lastCenter = c; }
setPreviousScale()
void QDeclarativePinchEvent::setPreviousScale (qreal s) inline
Definition at line 221 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_lastScale = s; }
setStartCenter()
void QDeclarativePinchEvent::setStartCenter (QPointF c) inline
Definition at line 216 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_startCenter = c; }
setStartPoint1()
void QDeclarativePinchEvent::setStartPoint1 (QPointF p) inline
Definition at line 229 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_startPoint1 = p; }
setStartPoint2()
void QDeclarativePinchEvent::setStartPoint2 (QPointF p) inline
Definition at line 233 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { m_startPoint2 = p; }
startCenter()
QPointF QDeclarativePinchEvent::startCenter () const inline
Definition at line 215 of file qdeclarativepincharea_p.h.
 { return m_startCenter; }
startPoint1()
QPointF QDeclarativePinchEvent::startPoint1 () const inline
Definition at line 228 of file qdeclarativepincharea_p.h.
 { return m_startPoint1; }
startPoint2()
QPointF QDeclarativePinchEvent::startPoint2 () const inline
Definition at line 232 of file qdeclarativepincharea_p.h.
 { return m_startPoint2; }
Properties
accepted
bool QDeclarativePinchEvent::accepted private
Definition at line 207 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
angle
qreal QDeclarativePinchEvent::angle private
Definition at line 199 of file qdeclarativepincharea_p.h.
center
QPointF QDeclarativePinchEvent::center private
Definition at line 194 of file qdeclarativepincharea_p.h.
m_accepted
bool QDeclarativePinchEvent::m_accepted private
Definition at line 254 of file qdeclarativepincharea_p.h.
m_angle
qreal QDeclarativePinchEvent::m_angle private
Definition at line 246 of file qdeclarativepincharea_p.h.
m_center
QPointF QDeclarativePinchEvent::m_center private
Definition at line 241 of file qdeclarativepincharea_p.h.
m_lastAngle
qreal QDeclarativePinchEvent::m_lastAngle private
Definition at line 247 of file qdeclarativepincharea_p.h.
m_lastCenter
QPointF QDeclarativePinchEvent::m_lastCenter private
Definition at line 243 of file qdeclarativepincharea_p.h.
m_lastScale
qreal QDeclarativePinchEvent::m_lastScale private
Definition at line 245 of file qdeclarativepincharea_p.h.
m_point1
QPointF QDeclarativePinchEvent::m_point1 private
Definition at line 249 of file qdeclarativepincharea_p.h.
m_point2
QPointF QDeclarativePinchEvent::m_point2 private
Definition at line 250 of file qdeclarativepincharea_p.h.
m_pointCount
int QDeclarativePinchEvent::m_pointCount private
Definition at line 253 of file qdeclarativepincharea_p.h.
m_rotation
qreal QDeclarativePinchEvent::m_rotation private
Definition at line 248 of file qdeclarativepincharea_p.h.
m_scale
qreal QDeclarativePinchEvent::m_scale private
Definition at line 244 of file qdeclarativepincharea_p.h.
m_startCenter
QPointF QDeclarativePinchEvent::m_startCenter private
Definition at line 242 of file qdeclarativepincharea_p.h.
m_startPoint1
QPointF QDeclarativePinchEvent::m_startPoint1 private
Definition at line 251 of file qdeclarativepincharea_p.h.
m_startPoint2
QPointF QDeclarativePinchEvent::m_startPoint2 private
Definition at line 252 of file qdeclarativepincharea_p.h.
point1
QPointF QDeclarativePinchEvent::point1 private
Definition at line 202 of file qdeclarativepincharea_p.h.
point2
QPointF QDeclarativePinchEvent::point2 private
Definition at line 204 of file qdeclarativepincharea_p.h.
pointCount
int QDeclarativePinchEvent::pointCount private
Definition at line 206 of file qdeclarativepincharea_p.h.
previousAngle
qreal QDeclarativePinchEvent::previousAngle private
Definition at line 200 of file qdeclarativepincharea_p.h.
previousCenter
QPointF QDeclarativePinchEvent::previousCenter private
Definition at line 196 of file qdeclarativepincharea_p.h.
previousScale
qreal QDeclarativePinchEvent::previousScale private
Definition at line 198 of file qdeclarativepincharea_p.h.
rotation
qreal QDeclarativePinchEvent::rotation private
Definition at line 201 of file qdeclarativepincharea_p.h.
scale
qreal QDeclarativePinchEvent::scale private
Definition at line 197 of file qdeclarativepincharea_p.h.
startCenter
QPointF QDeclarativePinchEvent::startCenter private
Definition at line 195 of file qdeclarativepincharea_p.h.
startPoint1
QPointF QDeclarativePinchEvent::startPoint1 private
Definition at line 203 of file qdeclarativepincharea_p.h.
startPoint2
QPointF QDeclarativePinchEvent::startPoint2 private
Definition at line 205 of file qdeclarativepincharea_p.h.
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativepincharea_p.h