Qt 4.8: QFtpPI Class Reference
QFtpPI Class Reference
Signals
void connectState (int)
void error (int, const QString &)
void finished (const QString &)
void rawFtpReply (int, const QString &)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void abort ()
void clearPendingCommands ()
void connectToHost (const QString &host, quint16 port)
QString currentCommand () const
QFtpPI (QObject *parent=0)
bool sendCommand (const QString &cmd)
bool sendCommands (const QStringList &cmds)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QFtpDTP dtp
bool rawCommand
bool transferConnectionExtended
Private Types
enum AbortState { None, AbortStarted, WaitForAbortToFinish }
enum State {
Begin, Idle, Waiting, Success,
Failure
}
Private Slots
void connected ()
void connectionClosed ()
void delayedCloseFinished ()
void dtpConnectState (int)
void error (QAbstractSocket::SocketError)
void hostFound ()
void readyRead ()
Private Functions
bool processReply ()
bool startNextCmd ()
Properties
AbortState abortState
QByteArray bytesFromSocket
QTcpSocket commandSocket
QString currentCmd
QStringList pendingCommands
char replyCode [3]
QString replyText
State state
bool waitForDtpToClose
bool waitForDtpToConnect
Friends
class QFtpDTP
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 152 of file qftp.cpp.
Enumerations
AbortState
enum QFtpPI::AbortState private
Enumerator
None
AbortStarted
WaitForAbortToFinish
Definition at line 203 of file qftp.cpp.
                     {
         None,
         AbortStarted,
         WaitForAbortToFinish
     };
State
enum QFtpPI::State private
Enumerator
Begin
Idle
Waiting
Success
Failure
Definition at line 195 of file qftp.cpp.
                {
         Begin,
         Idle,
         Waiting,
         Success,
         Failure
     };
Constructors and Destructors
QFtpPI()
QFtpPI::QFtpPI (QObject * parent = 0)
Definition at line 822 of file qftp.cpp.
                               :
     QObject(parent),
     rawCommand(false),
     transferConnectionExtended(true),
     dtp(this),
     commandSocket(0),
     state(Begin), abortState(None),
     currentCmd(QString()),
     waitForDtpToConnect(false),
     waitForDtpToClose(false)
 {
     commandSocket.setObjectName(QLatin1String("QFtpPI_socket"));
     connect(&commandSocket, SIGNAL(hostFound()),
             SLOT(hostFound()));
     connect(&commandSocket, SIGNAL(connected()),
             SLOT(connected()));
     connect(&commandSocket, SIGNAL(disconnected()),
             SLOT(connectionClosed()));
     connect(&commandSocket, SIGNAL(readyRead()),
             SLOT(readyRead()));
     connect(&commandSocket, SIGNAL(error(QAbstractSocket::SocketError)),
             SLOT(error(QAbstractSocket::SocketError)));
     connect(&dtp, SIGNAL(connectState(int)),
              SLOT(dtpConnectState(int)));
 }
Functions
abort()
void QFtpPI::abort ()
Definition at line 891 of file qftp.cpp.
 {
     pendingCommands.clear();
     if (abortState != None)
         // ABOR already sent
         return;
     if (currentCmd.isEmpty())
         return; //no command in progress
     if (currentCmd.startsWith(QLatin1String("STOR "))) {
         abortState = AbortStarted;
 #if defined(QFTPPI_DEBUG)
         qDebug("QFtpPI send: ABOR");
 #endif
         commandSocket.write("ABOR\r\n", 6);
         dtp.abortConnection();
     } else {
         //Deviation from RFC 959:
         //Most FTP servers do not support ABOR, or require the telnet
         //IP & synch sequence (TCP urgent data) which is not supported by QTcpSocket.
         //Following what most FTP clients do, just reset the data connection and wait for 426
         abortState = WaitForAbortToFinish;
         dtp.abortConnection();
     }
 }
clearPendingCommands()
void QFtpPI::clearPendingCommands ()
Definition at line 883 of file qftp.cpp.
 {
     pendingCommands.clear();
     dtp.abortConnection();
     currentCmd.clear();
     state = Idle;
 }
connected
void QFtpPI::connected () private slot
Definition at line 925 of file qftp.cpp.
Referenced by QFtpPI().
 {
     state = Begin;
 #if defined(QFTPPI_DEBUG)
 //    qDebug("QFtpPI state: %d [connected()]", state);
 #endif
     // try to improve performance by setting TCP_NODELAY
     commandSocket.setSocketOption(QAbstractSocket::LowDelayOption, 1);
     emit connectState(QFtp::Connected);
 }
connectionClosed
void QFtpPI::connectionClosed () private slot
Definition at line 937 of file qftp.cpp.
Referenced by QFtpPI().
 {
     commandSocket.close();
     emit connectState(QFtp::Unconnected);
 }
connectState
void QFtpPI::connectState (int) signal
Referenced by connected(), connectionClosed(), connectToHost(), delayedCloseFinished(), error(), hostFound(), processReply(), and QFtpPI().
connectToHost()
void QFtpPI::connectToHost (const QString & host, quint16 port)
Definition at line 849 of file qftp.cpp.
 {
     emit connectState(QFtp::HostLookup);
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the socket & DTP
     commandSocket.setProperty("_q_networksession", property("_q_networksession"));
     dtp.setProperty("_q_networksession", property("_q_networksession"));
 #endif
     commandSocket.connectToHost(host, port);
 }
currentCommand()
QString QFtpPI::currentCommand () const inline
Definition at line 168 of file qftp.cpp.
Referenced by QFtpDTP::socketReadyRead().
         { return currentCmd; }
delayedCloseFinished
void QFtpPI::delayedCloseFinished () private slot
Definition at line 943 of file qftp.cpp.
 {
     emit connectState(QFtp::Unconnected);
 }
dtpConnectState
void QFtpPI::dtpConnectState (int s) private slot
Definition at line 1263 of file qftp.cpp.
Referenced by QFtpPI().
 {
     switch (s) {
         case QFtpDTP::CsClosed:
             if (waitForDtpToClose) {
                 // there is an unprocessed reply
                 if (processReply())
                     replyText = QLatin1String("");
                 else
                     return;
             }
             waitForDtpToClose = false;
             readyRead();
             return;
         case QFtpDTP::CsConnected:
             waitForDtpToConnect = false;
             startNextCmd();
             return;
         case QFtpDTP::CsHostNotFound:
         case QFtpDTP::CsConnectionRefused:
             emit error(QFtp::ConnectionRefused,
                         QFtp::tr("Connection refused for data connection"));
             startNextCmd();
             return;
         default:
             return;
     }
 }
error [1/2]
void QFtpPI::error (int , const QString &) signal
Referenced by dtpConnectState(), error(), processReply(), QFtpPI(), and sendCommands().
error [2/2]
void QFtpPI::error (QAbstractSocket::SocketError e) private slot
Definition at line 948 of file qftp.cpp.
 {
     if (e == QTcpSocket::HostNotFoundError) {
         emit connectState(QFtp::Unconnected);
         emit error(QFtp::HostNotFound,
                     QFtp::tr("Host %1 not found").arg(commandSocket.peerName()));
     } else if (e == QTcpSocket::ConnectionRefusedError) {
         emit connectState(QFtp::Unconnected);
         emit error(QFtp::ConnectionRefused,
                     QFtp::tr("Connection refused to host %1").arg(commandSocket.peerName()));
     } else if (e == QTcpSocket::SocketTimeoutError) {
         emit connectState(QFtp::Unconnected);
         emit error(QFtp::ConnectionRefused,
                    QFtp::tr("Connection timed out to host %1").arg(commandSocket.peerName()));
     }
 }
finished
void QFtpPI::finished (const QString &) signal
Referenced by processReply(), and startNextCmd().
hostFound
void QFtpPI::hostFound () private slot
Definition at line 920 of file qftp.cpp.
Referenced by QFtpPI().
 {
     emit connectState(QFtp::Connecting);
 }
processReply()
bool QFtpPI::processReply () private
Definition at line 1022 of file qftp.cpp.
Referenced by dtpConnectState(), and readyRead().
 {
 #if defined(QFTPPI_DEBUG)
 //    qDebug("QFtpPI state: %d [processReply() begin]", state);
     if (replyText.length() < 400)
         qDebug("QFtpPI recv: %d %s", 100*replyCode[0]+10*replyCode[1]+replyCode[2], replyText.toLatin1().constData());
     else
         qDebug("QFtpPI recv: %d (text skipped)", 100*replyCode[0]+10*replyCode[1]+replyCode[2]);
 #endif
     int replyCodeInt = 100*replyCode[0] + 10*replyCode[1] + replyCode[2];
     // process 226 replies ("Closing Data Connection") only when the data
     // connection is really closed to avoid short reads of the DTP
     if (replyCodeInt == 226 || (replyCodeInt == 250 && currentCmd.startsWith(QLatin1String("RETR")))) {
         if (dtp.state() != QTcpSocket::UnconnectedState) {
             waitForDtpToClose = true;
             return false;
         }
     }
     switch (abortState) {
         case AbortStarted:
             abortState = WaitForAbortToFinish;
             break;
         case WaitForAbortToFinish:
             abortState = None;
             return true;
         default:
             break;
     }
     // get new state
     static const State table[5] = {
         /* 1yz   2yz      3yz   4yz      5yz */
         Waiting, Success, Idle, Failure, Failure
     };
     switch (state) {
         case Begin:
             if (replyCode[0] == 1) {
                 return true;
             } else if (replyCode[0] == 2) {
                 state = Idle;
                 emit finished(QFtp::tr("Connected to host %1").arg(commandSocket.peerName()));
                 break;
             }
             // reply codes not starting with 1 or 2 are not handled.
             return true;
         case Waiting:
             if (static_cast<signed char>(replyCode[0]) < 0 || replyCode[0] > 5)
                 state = Failure;
             else
 #if defined(Q_OS_IRIX) && defined(Q_CC_GNU)
             {
                 // work around a crash on 64 bit gcc IRIX
                 State *t = (State *) table;
                 state = t[replyCode[0] - 1];
             }
 #else
             if (replyCodeInt == 202)
                 state = Failure;
             else
                 state = table[replyCode[0] - 1];
 #endif
             break;
         default:
             // ignore unrequested message
             return true;
     }
 #if defined(QFTPPI_DEBUG)
 //    qDebug("QFtpPI state: %d [processReply() intermediate]", state);
 #endif
     // special actions on certain replies
     emit rawFtpReply(replyCodeInt, replyText);
     if (rawCommand) {
         rawCommand = false;
     } else if (replyCodeInt == 227) {
         // 227 Entering Passive Mode (h1,h2,h3,h4,p1,p2)
         // rfc959 does not define this response precisely, and gives
         // both examples where the parenthesis are used, and where
         // they are missing. We need to scan for the address and host
         // info.
         QRegExp addrPortPattern(QLatin1String("(\\d+),(\\d+),(\\d+),(\\d+),(\\d+),(\\d+)"));
         if (addrPortPattern.indexIn(replyText) == -1) {
 #if defined(QFTPPI_DEBUG)
             qDebug("QFtp: bad 227 response -- address and port information missing");
 #endif
             // this error should be reported
         } else {
             QStringList lst = addrPortPattern.capturedTexts();
             QString host = lst[1] + QLatin1Char('.') + lst[2] + QLatin1Char('.') + lst[3] + QLatin1Char('.') + lst[4];
             quint16 port = (lst[5].toUInt() << 8) + lst[6].toUInt();
             waitForDtpToConnect = true;
             dtp.connectToHost(host, port);
         }
     } else if (replyCodeInt == 229) {
         // 229 Extended Passive mode OK (|||10982|)
         int portPos = replyText.indexOf(QLatin1Char('('));
         if (portPos == -1) {
 #if defined(QFTPPI_DEBUG)
             qDebug("QFtp: bad 229 response -- port information missing");
 #endif
             // this error should be reported
         } else {
             ++portPos;
             QChar delimiter = replyText.at(portPos);
             QStringList epsvParameters = replyText.mid(portPos).split(delimiter);
             waitForDtpToConnect = true;
             dtp.connectToHost(commandSocket.peerAddress().toString(),
                               epsvParameters.at(3).toInt());
         }
     } else if (replyCodeInt == 230) {
         if (currentCmd.startsWith(QLatin1String("USER ")) && pendingCommands.count()>0 &&
             pendingCommands.first().startsWith(QLatin1String("PASS "))) {
             // no need to send the PASS -- we are already logged in
             pendingCommands.pop_front();
         }
         // 230 User logged in, proceed.
         emit connectState(QFtp::LoggedIn);
     } else if (replyCodeInt == 213) {
         // 213 File status.
         if (currentCmd.startsWith(QLatin1String("SIZE ")))
             dtp.setBytesTotal(replyText.simplified().toLongLong());
     } else if (replyCode[0]==1 && currentCmd.startsWith(QLatin1String("STOR "))) {
         dtp.waitForConnection();
         dtp.writeData();
     }
     // react on new state
     switch (state) {
         case Begin:
             // should never happen
             break;
         case Success:
             // success handling
             state = Idle;
             // no break!
         case Idle:
             if (dtp.hasError()) {
                 emit error(QFtp::UnknownError, dtp.errorMessage());
                 dtp.clearError();
             }
             startNextCmd();
             break;
         case Waiting:
             // do nothing
             break;
         case Failure:
             // If the EPSV or EPRT commands fail, replace them with
             // the old PASV and PORT instead and try again.
             if (currentCmd.startsWith(QLatin1String("EPSV"))) {
                 transferConnectionExtended = false;
                 pendingCommands.prepend(QLatin1String("PASV\r\n"));
             } else if (currentCmd.startsWith(QLatin1String("EPRT"))) {
                 transferConnectionExtended = false;
                 pendingCommands.prepend(QLatin1String("PORT\r\n"));
             } else {
                 emit error(QFtp::UnknownError, replyText);
             }
             if (state != Waiting) {
                 state = Idle;
                 startNextCmd();
             }
             break;
     }
 #if defined(QFTPPI_DEBUG)
 //    qDebug("QFtpPI state: %d [processReply() end]", state);
 #endif
     return true;
 }
rawFtpReply
void QFtpPI::rawFtpReply (int , const QString &) signal
Referenced by processReply().
readyRead
void QFtpPI::readyRead () private slot
Definition at line 965 of file qftp.cpp.
Referenced by dtpConnectState(), and QFtpPI().
 {
     if (waitForDtpToClose)
         return;
     while (commandSocket.canReadLine()) {
         // read line with respect to line continuation
         QString line = QString::fromAscii(commandSocket.readLine());
         if (replyText.isEmpty()) {
             if (line.length() < 3) {
                 // protocol error
                 return;
             }
             const int lowerLimit[3] = {1,0,0};
             const int upperLimit[3] = {5,5,9};
             for (int i=0; i<3; i++) {
                 replyCode[i] = line[i].digitValue();
                 if (replyCode[i]<lowerLimit[i] || replyCode[i]>upperLimit[i]) {
                     // protocol error
                     return;
                 }
             }
         }
         QString endOfMultiLine;
         endOfMultiLine[0] = '0' + replyCode[0];
         endOfMultiLine[1] = '0' + replyCode[1];
         endOfMultiLine[2] = '0' + replyCode[2];
         endOfMultiLine[3] = QLatin1Char(' ');
         QString lineCont(endOfMultiLine);
         lineCont[3] = QLatin1Char('-');
         QString lineLeft4 = line.left(4);
         while (lineLeft4 != endOfMultiLine) {
             if (lineLeft4 == lineCont)
                 replyText += line.mid(4); // strip 'xyz-'
             else
                 replyText += line;
             if (!commandSocket.canReadLine())
                 return;
             line = QString::fromAscii(commandSocket.readLine());
             lineLeft4 = line.left(4);
         }
         replyText += line.mid(4); // strip reply code 'xyz '
         if (replyText.endsWith(QLatin1String("\r\n")))
             replyText.chop(2);
         if (processReply())
             replyText = QLatin1String("");
     }
 }
sendCommand()
bool QFtpPI::sendCommand (const QString & cmd) inline
Definition at line 162 of file qftp.cpp.
         { return sendCommands(QStringList(cmd)); }
sendCommands()
bool QFtpPI::sendCommands (const QStringList & cmds)
Definition at line 868 of file qftp.cpp.
 {
     if (!pendingCommands.isEmpty())
         return false;
     if (commandSocket.state() != QTcpSocket::ConnectedState || state!=Idle) {
         emit error(QFtp::NotConnected, QFtp::tr("Not connected"));
         return true; // there are no pending commands
     }
     pendingCommands = cmds;
     startNextCmd();
     return true;
 }
startNextCmd()
bool QFtpPI::startNextCmd () private
Definition at line 1200 of file qftp.cpp.
Referenced by dtpConnectState(), processReply(), and sendCommands().
 {
     if (waitForDtpToConnect)
         // don't process any new commands until we are connected
         return true;
 #if defined(QFTPPI_DEBUG)
     if (state != Idle)
         qDebug("QFtpPI startNextCmd: Internal error! QFtpPI called in non-Idle state %d", state);
 #endif
     if (pendingCommands.isEmpty()) {
         currentCmd.clear();
         emit finished(replyText);
         return false;
     }
     currentCmd = pendingCommands.first();
     // PORT and PASV are edited in-place, depending on whether we
     // should try the extended transfer connection commands EPRT and
     // EPSV. The PORT command also triggers setting up a listener, and
     // the address/port arguments are edited in.
     QHostAddress address = commandSocket.localAddress();
     if (currentCmd.startsWith(QLatin1String("PORT"))) {
         if ((address.protocol() == QTcpSocket::IPv6Protocol) && transferConnectionExtended) {
             int port = dtp.setupListener(address);
             currentCmd = QLatin1String("EPRT |");
             currentCmd += (address.protocol() == QTcpSocket::IPv4Protocol) ? QLatin1Char('1') : QLatin1Char('2');
             currentCmd += QLatin1Char('|') + address.toString() + QLatin1Char('|') + QString::number(port);
             currentCmd += QLatin1Char('|');
         } else if (address.protocol() == QTcpSocket::IPv4Protocol) {
             int port = dtp.setupListener(address);
             QString portArg;
             quint32 ip = address.toIPv4Address();
             portArg += QString::number((ip & 0xff000000) >> 24);
             portArg += QLatin1Char(',') + QString::number((ip & 0xff0000) >> 16);
             portArg += QLatin1Char(',') + QString::number((ip & 0xff00) >> 8);
             portArg += QLatin1Char(',') + QString::number(ip & 0xff);
             portArg += QLatin1Char(',') + QString::number((port & 0xff00) >> 8);
             portArg += QLatin1Char(',') + QString::number(port & 0xff);
             currentCmd = QLatin1String("PORT ");
             currentCmd += portArg;
         } else {
             // No IPv6 connection can be set up with the PORT
             // command.
             return false;
         }
         currentCmd += QLatin1String("\r\n");
     } else if (currentCmd.startsWith(QLatin1String("PASV"))) {
         if ((address.protocol() == QTcpSocket::IPv6Protocol) && transferConnectionExtended)
             currentCmd = QLatin1String("EPSV\r\n");
     }
     pendingCommands.pop_front();
 #if defined(QFTPPI_DEBUG)
     qDebug("QFtpPI send: %s", currentCmd.left(currentCmd.length()-2).toLatin1().constData());
 #endif
     state = Waiting;
     commandSocket.write(currentCmd.toLatin1());
     return true;
 }
Friends and Related Functions
QFtpDTP
friend class QFtpDTP friend
Definition at line 225 of file qftp.cpp.
Properties
abortState
AbortState QFtpPI::abortState private
Definition at line 216 of file qftp.cpp.
Referenced by abort(), processReply(), and QFtpDTP::socketReadyRead().
bytesFromSocket
QByteArray QFtpPI::bytesFromSocket private
Definition at line 223 of file qftp.cpp.
commandSocket
QTcpSocket QFtpPI::commandSocket private
Definition at line 212 of file qftp.cpp.
Referenced by abort(), connected(), connectionClosed(), connectToHost(), error(), processReply(), QFtpPI(), readyRead(), sendCommands(), and startNextCmd().
currentCmd
QString QFtpPI::currentCmd private
Definition at line 218 of file qftp.cpp.
Referenced by abort(), clearPendingCommands(), processReply(), and startNextCmd().
dtp
QFtpDTP QFtpPI::dtp
Definition at line 174 of file qftp.cpp.
Referenced by abort(), clearPendingCommands(), connectToHost(), processReply(), QFtpPI(), and startNextCmd().
pendingCommands
QStringList QFtpPI::pendingCommands private
Definition at line 217 of file qftp.cpp.
Referenced by abort(), clearPendingCommands(), processReply(), sendCommands(), and startNextCmd().
rawCommand
bool QFtpPI::rawCommand
Definition at line 171 of file qftp.cpp.
Referenced by processReply().
replyCode
char QFtpPI::replyCode[3] private
Definition at line 214 of file qftp.cpp.
Referenced by processReply(), and readyRead().
replyText
QString QFtpPI::replyText private
Definition at line 213 of file qftp.cpp.
Referenced by dtpConnectState(), processReply(), readyRead(), and startNextCmd().
state
State QFtpPI::state private
Definition at line 215 of file qftp.cpp.
Referenced by clearPendingCommands(), connected(), processReply(), sendCommands(), and startNextCmd().
transferConnectionExtended
bool QFtpPI::transferConnectionExtended
Definition at line 172 of file qftp.cpp.
Referenced by processReply(), and startNextCmd().
waitForDtpToClose
bool QFtpPI::waitForDtpToClose private
Definition at line 221 of file qftp.cpp.
Referenced by dtpConnectState(), processReply(), and readyRead().
waitForDtpToConnect
bool QFtpPI::waitForDtpToConnect private
Definition at line 220 of file qftp.cpp.
Referenced by dtpConnectState(), processReply(), and startNextCmd().
The documentation for this class was generated from the following file:
/src/network/access/qftp.cpp