Qt 4.8: QSettingsPrivate Class Reference
QSettingsPrivate Class Reference abstract
#include <qsettings_p.h>
Public Types
enum {
F_Application = 0x0, F_Organization = 0x1, F_User = 0x0, F_System = 0x2,
NumConfFiles = 4
}
enum ChildSpec { AllKeys, ChildKeys, ChildGroups }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
QString actualKey (const QString &key) const
void beginGroupOrArray (const QSettingsGroup &group)
virtual QStringList children (const QString &prefix, ChildSpec spec) const =0
virtual void clear ()=0
virtual QString fileName () const =0
virtual void flush ()=0
virtual bool get (const QString &key, QVariant *value) const =0
virtual bool isWritable () const =0
QSettingsPrivate (QSettings::Format format)
QSettingsPrivate (QSettings::Format format, QSettings::Scope scope, const QString &organization, const QString &application)
virtual void remove (const QString &key)=0
void requestUpdate ()
virtual void set (const QString &key, const QVariant &value)=0
void setStatus (QSettings::Status status) const
virtual void sync ()=0
void update ()
virtual ~QSettingsPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QSettingsPrivate * create (QSettings::Format format, QSettings::Scope scope, const QString &organization, const QString &application)
static QSettingsPrivate * create (const QString &fileName, QSettings::Format format)
static void iniEscapedKey (const QString &key, QByteArray &result)
static void iniEscapedString (const QString &str, QByteArray &result, QTextCodec *codec)
static void iniEscapedStringList (const QStringList &strs, QByteArray &result, QTextCodec *codec)
static bool iniUnescapedKey (const QByteArray &key, int from, int to, QString &result)
static bool iniUnescapedStringList (const QByteArray &str, int from, int to, QString &stringResult, QStringList &stringListResult, QTextCodec *codec)
static QString normalizedKey (const QString &key)
static void processChild (QString key, ChildSpec spec, QMap< QString, QString > &result)
static QStringList splitArgs (const QString &s, int idx)
static QVariant stringListToVariantList (const QStringList &l)
static QVariant stringToVariant (const QString &s)
static QStringList variantListToStringList (const QVariantList &l)
static QString variantToString (const QVariant &v)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QString applicationName
QSettings::Format format
QTextCodec * iniCodec
QString organizationName
QSettings::Scope scope
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Protected Variables
bool fallbacks
QString groupPrefix
QStack< QSettingsGroup > groupStack
bool pendingChanges
int spec
QSettings::Status status
Detailed Description
Definition at line 182 of file qsettings_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
F_Application
F_Organization
F_User
F_System
NumConfFiles
Definition at line 245 of file qsettings_p.h.
          {
 #if !defined(Q_OS_BLACKBERRY)
         F_Application = 0x0,
         F_Organization = 0x1,
         F_User = 0x0,
         F_System = 0x2,
         NumConfFiles = 4
 #else
         SandboxConfFile = 0,
         NumConfFiles = 1
 #endif
     };
ChildSpec
enum QSettingsPrivate::ChildSpec
Enumerator
AllKeys
ChildKeys
ChildGroups
Definition at line 202 of file qsettings_p.h.
 { AllKeys, ChildKeys, ChildGroups };
Constructors and Destructors
QSettingsPrivate() [1/2]
QSettingsPrivate::QSettingsPrivate (QSettings::Format format)
Definition at line 302 of file qsettings.cpp.
     : format(format), scope(QSettings::UserScope /* nothing better to put */), iniCodec(0), spec(0), fallbacks(true),
       pendingChanges(false), status(QSettings::NoError)
 {
 }
QSettingsPrivate() [2/2]
QSettingsPrivate::QSettingsPrivate (QSettings::Format format, QSettings::Scope scope, const QString & organization, const QString & application)
Definition at line 308 of file qsettings.cpp.
     : format(format), scope(scope), organizationName(organization), applicationName(application),
       iniCodec(0), spec(0), fallbacks(true), pendingChanges(false), status(QSettings::NoError)
 {
 }
~QSettingsPrivate()
QSettingsPrivate::~QSettingsPrivate () virtual
Definition at line 315 of file qsettings.cpp.
 {
 }
Functions
actualKey()
QString QSettingsPrivate::actualKey (const QString & key) const
Definition at line 319 of file qsettings.cpp.
 {
     QString n = normalizedKey(key);
     Q_ASSERT_X(!n.isEmpty(), "QSettings", "empty key");
     n.prepend(groupPrefix);
     return n;
 }
beginGroupOrArray()
void QSettingsPrivate::beginGroupOrArray (const QSettingsGroup & group)
Definition at line 396 of file qsettings.cpp.
Referenced by create().
 {
     groupStack.push(group);
     if (!group.name().isEmpty()) {
         groupPrefix += group.name();
         groupPrefix += QLatin1Char('/');
     }
 }
children()
virtual QStringList QSettingsPrivate::children (const QString & prefix, ChildSpec spec) const pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
clear()
virtual void QSettingsPrivate::clear () pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
create() [1/2]
QSettingsPrivate * QSettingsPrivate::create (QSettings::Format format, QSettings::Scope scope, const QString & organization, const QString & application) static
Definition at line 601 of file qsettings_mac.cpp.
Referenced by QWinSettingsPrivate::isWritable(), normalizedKey(), QSettings::QSettings(), and QSettings::registerFormat().
 {
 #ifndef QT_BOOTSTRAPPED
     static bool useAppLocalStorage = false;
     static bool initialized = false;
     if (!initialized) {
         bool inSandbox = false;
 #if __MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_6
         // If we are running on at least 10.7.0 and have the com.apple.security.app-sandbox
         // entitlement, we are in a sandbox
         SInt32 version = 0;
         Gestalt(gestaltSystemVersion, &version);
         SecCodeRef secCodeSelf;
         if (version >= 0x1070 && SecCodeCopySelf(kSecCSDefaultFlags, &secCodeSelf) == errSecSuccess) {
             SecRequirementRef sandboxReq;
             CFStringRef entitlement = CFSTR("entitlement [\"com.apple.security.app-sandbox\"]");
             if (SecRequirementCreateWithString(entitlement, kSecCSDefaultFlags, &sandboxReq) == errSecSuccess) {
                 if (SecCodeCheckValidity(secCodeSelf, kSecCSDefaultFlags, sandboxReq) == errSecSuccess)
                     inSandbox = true;
                 CFRelease(sandboxReq);
             }
             CFRelease(secCodeSelf);
         }
 #endif
         bool forAppStore = false;
         if (!inSandbox) {
             CFTypeRef val = CFBundleGetValueForInfoDictionaryKey(CFBundleGetMainBundle(), CFSTR("ForAppStore"));
             forAppStore = (val &&
                            CFGetTypeID(val) == CFStringGetTypeID() &&
                            CFStringCompare(CFStringRef(val), CFSTR("yes"), kCFCompareCaseInsensitive) == 0);
         }
         useAppLocalStorage = inSandbox || forAppStore;
         initialized = true;
     }
     if (useAppLocalStorage) {
         // Ensure that the global and app-local settings go to the same file, since that's
         // what we really want
         if (organization == QLatin1String("Trolltech") ||
                 organization.isEmpty() ||
                 (organization == qApp->organizationDomain() && application == qApp->applicationName()) ||
                 (organization == qApp->organizationName()) && application == qApp->applicationName())
         {
             CFStringRef bundleIdentifier = CFBundleGetIdentifier(CFBundleGetMainBundle());
             if (!bundleIdentifier) {
                 qWarning("QSettingsPrivate::create: You must set the bundle identifier when using ForAppStore");
             } else {
                 QSettingsPrivate* settings = new QMacSettingsPrivate(bundleIdentifier);
                 if (organization == QLatin1String("Trolltech"))
                     settings->beginGroupOrArray(QSettingsGroup("QtLibrarySettings"));
                 return settings;
             }
         }
    }
 #endif
     if (format == QSettings::NativeFormat) {
         return new QMacSettingsPrivate(scope, organization, application);
     } else {
         return new QConfFileSettingsPrivate(format, scope, organization, application);
     }
 }
create() [2/2]
QSettingsPrivate * QSettingsPrivate::create (const QString & fileName, QSettings::Format format) static
Definition at line 837 of file qsettings_win.cpp.
 {
     if (format == QSettings::NativeFormat) {
         return new QWinSettingsPrivate(fileName);
     } else {
         return new QConfFileSettingsPrivate(fileName, format);
     }
 }
fileName()
virtual QString QSettingsPrivate::fileName () const pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
Referenced by normalizedKey().
flush()
virtual void QSettingsPrivate::flush () pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
Referenced by update().
get()
virtual bool QSettingsPrivate::get (const QString & key, QVariant * value) const pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
iniEscapedKey()
void QSettingsPrivate::iniEscapedKey (const QString & key, QByteArray & result) static
Definition at line 596 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::writeIniFile().
 {
     result.reserve(result.length() + key.length() * 3 / 2);
     for (int i = 0; i < key.size(); ++i) {
         uint ch = key.at(i).unicode();
         if (ch == '/') {
             result += '\\';
         } else if ((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9')
                 || ch == '_' || ch == '-' || ch == '.') {
             result += (char)ch;
         } else if (ch <= 0xFF) {
             result += '%';
             result += hexDigits[ch / 16];
             result += hexDigits[ch % 16];
         } else {
             result += "%U";
             QByteArray hexCode;
             for (int i = 0; i < 4; ++i) {
                 hexCode.prepend(hexDigits[ch % 16]);
                 ch >>= 4;
             }
             result += hexCode;
         }
     }
 }
iniEscapedString()
void QSettingsPrivate::iniEscapedString (const QString & str, QByteArray & result, QTextCodec * codec) static
Definition at line 679 of file qsettings.cpp.
Referenced by iniEscapedStringList(), and QConfFileSettingsPrivate::writeIniFile().
 {
     bool needsQuotes = false;
     bool escapeNextIfDigit = false;
     int i;
     int startPos = result.size();
     result.reserve(startPos + str.size() * 3 / 2);
     for (i = 0; i < str.size(); ++i) {
         uint ch = str.at(i).unicode();
         if (ch == ';' || ch == ',' || ch == '=')
             needsQuotes = true;
         if (escapeNextIfDigit
                 && ((ch >= '0' && ch <= '9')
                     || (ch >= 'a' && ch <= 'f')
                     || (ch >= 'A' && ch <= 'F'))) {
             result += "\\x";
             result += QByteArray::number(ch, 16);
             continue;
         }
         escapeNextIfDigit = false;
         switch (ch) {
         case '\0':
             result += "\\0";
             escapeNextIfDigit = true;
             break;
         case '\a':
             result += "\\a";
             break;
         case '\b':
             result += "\\b";
             break;
         case '\f':
             result += "\\f";
             break;
         case '\n':
             result += "\\n";
             break;
         case '\r':
             result += "\\r";
             break;
         case '\t':
             result += "\\t";
             break;
         case '\v':
             result += "\\v";
             break;
         case '"':
         case '\\':
             result += '\\';
             result += (char)ch;
             break;
         default:
             if (ch <= 0x1F || (ch >= 0x7F && !codec)) {
                 result += "\\x";
                 result += QByteArray::number(ch, 16);
                 escapeNextIfDigit = true;
 #ifndef QT_NO_TEXTCODEC
             } else if (codec) {
                 // slow
                 result += codec->fromUnicode(str.at(i));
 #endif
             } else {
                 result += (char)ch;
             }
         }
     }
     if (needsQuotes
             || (startPos < result.size() && (result.at(startPos) == ' '
                                                 || result.at(result.size() - 1) == ' '))) {
         result.insert(startPos, '"');
         result += '"';
     }
 }
iniEscapedStringList()
void QSettingsPrivate::iniEscapedStringList (const QStringList & strs, QByteArray & result, QTextCodec * codec) static
Definition at line 766 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::writeIniFile().
 {
     if (strs.isEmpty()) {
         /*
             We need to distinguish between empty lists and one-item
             lists that contain an empty string. Ideally, we'd have a
             @EmptyList() symbol but that would break compatibility
             with Qt 4.0. @Invalid() stands for QVariant(), and
             QVariant().toStringList() returns an empty QStringList,
             so we're in good shape.
             ### Qt 5: Use a nicer syntax, e.g. @List, for variant lists
         */
         result += "@Invalid()";
     } else {
         for (int i = 0; i < strs.size(); ++i) {
             if (i != 0)
                 result += ", ";
             iniEscapedString(strs.at(i), result, codec);
         }
     }
 }
iniUnescapedKey()
bool QSettingsPrivate::iniUnescapedKey (const QByteArray & key, int from, int to, QString & result) static
Definition at line 623 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::readIniFile(), and QConfFileSettingsPrivate::readIniSection().
 {
     bool lowercaseOnly = true;
     int i = from;
     result.reserve(result.length() + (to - from));
     while (i < to) {
         int ch = (uchar)key.at(i);
         if (ch == '\\') {
             result += QLatin1Char('/');
             ++i;
             continue;
         }
         if (ch != '%' || i == to - 1) {
             if (uint(ch - 'A') <= 'Z' - 'A') // only for ASCII
                 lowercaseOnly = false;
             result += QLatin1Char(ch);
             ++i;
             continue;
         }
         int numDigits = 2;
         int firstDigitPos = i + 1;
         ch = key.at(i + 1);
         if (ch == 'U') {
             ++firstDigitPos;
             numDigits = 4;
         }
         if (firstDigitPos + numDigits > to) {
             result += QLatin1Char('%');
             // ### missing U
             ++i;
             continue;
         }
         bool ok;
         ch = key.mid(firstDigitPos, numDigits).toInt(&ok, 16);
         if (!ok) {
             result += QLatin1Char('%');
             // ### missing U
             ++i;
             continue;
         }
         QChar qch(ch);
         if (qch.isUpper())
             lowercaseOnly = false;
         result += qch;
         i = firstDigitPos + numDigits;
     }
     return lowercaseOnly;
 }
iniUnescapedStringList()
bool QSettingsPrivate::iniUnescapedStringList (const QByteArray & str, int from, int to, QString & stringResult, QStringList & stringListResult, QTextCodec * codec) static
Definition at line 789 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::readIniSection().
 {
 #ifdef QT_NO_TEXTCODE
     Q_UNUSED(codec);
 #endif
     static const char escapeCodes[][2] =
     {
         { 'a', '\a' },
         { 'b', '\b' },
         { 'f', '\f' },
         { 'n', '\n' },
         { 'r', '\r' },
         { 't', '\t' },
         { 'v', '\v' },
         { '"', '"' },
         { '?', '?' },
         { '\'', '\'' },
         { '\\', '\\' }
     };
     static const int numEscapeCodes = sizeof(escapeCodes) / sizeof(escapeCodes[0]);
     bool isStringList = false;
     bool inQuotedString = false;
     bool currentValueIsQuoted = false;
     int escapeVal = 0;
     int i = from;
     char ch;
 StSkipSpaces:
     while (i < to && ((ch = str.at(i)) == ' ' || ch == '\t'))
         ++i;
     // fallthrough
 StNormal:
     while (i < to) {
         switch (str.at(i)) {
         case '\\':
             ++i;
             if (i >= to)
                 goto end;
             ch = str.at(i++);
             for (int j = 0; j < numEscapeCodes; ++j) {
                 if (ch == escapeCodes[j][0]) {
                     stringResult += QLatin1Char(escapeCodes[j][1]);
                     goto StNormal;
                 }
             }
             if (ch == 'x') {
                 escapeVal = 0;
                 if (i >= to)
                     goto end;
                 ch = str.at(i);
                 if ((ch >= '0' && ch <= '9') || (ch >= 'A' && ch <= 'F') || (ch >= 'a' && ch <= 'f'))
                     goto StHexEscape;
             } else if (ch >= '0' && ch <= '7') {
                 escapeVal = ch - '0';
                 goto StOctEscape;
             } else if (ch == '\n' || ch == '\r') {
                 if (i < to) {
                     char ch2 = str.at(i);
                     // \n, \r, \r\n, and \n\r are legitimate line terminators in INI files
                     if ((ch2 == '\n' || ch2 == '\r') && ch2 != ch)
                         ++i;
                 }
             } else {
                 // the character is skipped
             }
             break;
         case '"':
             ++i;
             currentValueIsQuoted = true;
             inQuotedString = !inQuotedString;
             if (!inQuotedString)
                 goto StSkipSpaces;
             break;
         case ',':
             if (!inQuotedString) {
                 if (!currentValueIsQuoted)
                     iniChopTrailingSpaces(stringResult);
                 if (!isStringList) {
                     isStringList = true;
                     stringListResult.clear();
                     stringResult.squeeze();
                 }
                 stringListResult.append(stringResult);
                 stringResult.clear();
                 currentValueIsQuoted = false;
                 ++i;
                 goto StSkipSpaces;
             }
             // fallthrough
         default: {
             int j = i + 1;
             while (j < to) {
                 ch = str.at(j);
                 if (ch == '\\' || ch == '"' || ch == ',')
                     break;
                 ++j;
             }
 #ifndef QT_NO_TEXTCODEC
             if (codec) {
                 stringResult += codec->toUnicode(str.constData() + i, j - i);
             } else
 #endif
             {
                 int n = stringResult.size();
                 stringResult.resize(n + (j - i));
                 QChar *resultData = stringResult.data() + n;
                 for (int k = i; k < j; ++k)
                     *resultData++ = QLatin1Char(str.at(k));
             }
             i = j;
         }
         }
     }
     goto end;
 StHexEscape:
     if (i >= to) {
         stringResult += QChar(escapeVal);
         goto end;
     }
     ch = str.at(i);
     if (ch >= 'a')
         ch -= 'a' - 'A';
     if ((ch >= '0' && ch <= '9') || (ch >= 'A' && ch <= 'F')) {
         escapeVal <<= 4;
         escapeVal += strchr(hexDigits, ch) - hexDigits;
         ++i;
         goto StHexEscape;
     } else {
         stringResult += QChar(escapeVal);
         goto StNormal;
     }
 StOctEscape:
     if (i >= to) {
         stringResult += QChar(escapeVal);
         goto end;
     }
     ch = str.at(i);
     if (ch >= '0' && ch <= '7') {
         escapeVal <<= 3;
         escapeVal += ch - '0';
         ++i;
         goto StOctEscape;
     } else {
         stringResult += QChar(escapeVal);
         goto StNormal;
     }
 end:
     if (!currentValueIsQuoted)
         iniChopTrailingSpaces(stringResult);
     if (isStringList)
         stringListResult.append(stringResult);
     return isStringList;
 }
isWritable()
virtual bool QSettingsPrivate::isWritable () const pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
normalizedKey()
QString QSettingsPrivate::normalizedKey (const QString & key) static
Definition at line 338 of file qsettings.cpp.
Referenced by actualKey().
 {
     QString result = key;
     int i = 0;
     while (i < result.size()) {
         while (result.at(i) == QLatin1Char('/')) {
             result.remove(i, 1);
             if (i == result.size())
                 goto after_loop;
         }
         while (result.at(i) != QLatin1Char('/')) {
             ++i;
             if (i == result.size())
                 return result;
         }
         ++i; // leave the slash alone
     }
 after_loop:
     if (!result.isEmpty())
         result.truncate(i - 1); // remove the trailing slash
     return result;
 }
processChild()
void QSettingsPrivate::processChild (QString key, ChildSpec spec, QMap< QString, QString > & result) static
Definition at line 380 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::children(), and QMacSettingsPrivate::children().
 {
     if (spec != AllKeys) {
         int slashPos = key.indexOf(QLatin1Char('/'));
         if (slashPos == -1) {
             if (spec != ChildKeys)
                 return;
         } else {
             if (spec != ChildGroups)
                 return;
             key.truncate(slashPos);
         }
     }
     result.insert(key, QString());
 }
remove()
virtual void QSettingsPrivate::remove (const QString & key) pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
requestUpdate()
void QSettingsPrivate::requestUpdate ()
Definition at line 422 of file qsettings.cpp.
 {
     if (!pendingChanges) {
         pendingChanges = true;
 #ifndef QT_NO_QOBJECT
         Q_Q(QSettings);
         QCoreApplication::postEvent(q, new QEvent(QEvent::UpdateRequest));
 #else
         update();
 #endif
     }
 }
set()
virtual void QSettingsPrivate::set (const QString & key, const QVariant & value) pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
setStatus()
void QSettingsPrivate::setStatus (QSettings::Status status) const
Definition at line 410 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::ensureAllSectionsParsed(), QConfFileSettingsPrivate::ensureSectionParsed(), QConfFileSettingsPrivate::initAccess(), QConfFileSettingsPrivate::QConfFileSettingsPrivate(), QMacSettingsPrivate::QMacSettingsPrivate(), QWinSettingsPrivate::QWinSettingsPrivate(), QWinSettingsPrivate::remove(), QWinSettingsPrivate::set(), QMacSettingsPrivate::sync(), and QConfFileSettingsPrivate::syncConfFile().
 {
     if (status == QSettings::NoError || this->status == QSettings::NoError)
         this->status = status;
 }
splitArgs()
QStringList QSettingsPrivate::splitArgs (const QString & s, int idx) static
Definition at line 957 of file qsettings.cpp.
Referenced by stringToVariant().
 {
     int l = s.length();
     Q_ASSERT(l > 0);
     Q_ASSERT(s.at(idx) == QLatin1Char('('));
     Q_ASSERT(s.at(l - 1) == QLatin1Char(')'));
     QStringList result;
     QString item;
     for (++idx; idx < l; ++idx) {
         QChar c = s.at(idx);
         if (c == QLatin1Char(')')) {
             Q_ASSERT(idx == l - 1);
             result.append(item);
         } else if (c == QLatin1Char(' ')) {
             result.append(item);
             item.clear();
         } else {
             item.append(c);
         }
     }
     return result;
 }
stringListToVariantList()
QVariant QSettingsPrivate::stringListToVariantList (const QStringList & l) static
Definition at line 444 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate::readIniSection(), and QWinSettingsPrivate::readKey().
 {
     QStringList outStringList = l;
     for (int i = 0; i < outStringList.count(); ++i) {
         const QString &str = outStringList.at(i);
         if (str.startsWith(QLatin1Char('@'))) {
             if (str.length() >= 2 && str.at(1) == QLatin1Char('@')) {
                 outStringList[i].remove(0, 1);
             } else {
                 QVariantList variantList;
                 for (int j = 0; j < l.count(); ++j)
                     variantList.append(stringToVariant(l.at(j)));
                 return variantList;
             }
         }
     }
     return outStringList;
 }
stringToVariant()
QVariant QSettingsPrivate::stringToVariant (const QString & s) static
Definition at line 551 of file qsettings.cpp.
Referenced by qtValue(), QConfFileSettingsPrivate::readIniSection(), QWinSettingsPrivate::readKey(), and stringListToVariantList().
 {
     if (s.startsWith(QLatin1Char('@'))) {
         if (s.endsWith(QLatin1Char(')'))) {
             if (s.startsWith(QLatin1String("@ByteArray("))) {
                 return QVariant(s.toLatin1().mid(11, s.size() - 12));
             } else if (s.startsWith(QLatin1String("@Variant("))) {
 #ifndef QT_NO_DATASTREAM
                 QByteArray a(s.toLatin1().mid(9));
                 QDataStream stream(&a, QIODevice::ReadOnly);
                 stream.setVersion(QDataStream::Qt_4_0);
                 QVariant result;
                 stream >> result;
                 return result;
 #else
                 Q_ASSERT(!"QSettings: Cannot load custom types without QDataStream support");
 #endif
 #ifndef QT_NO_GEOM_VARIANT
             } else if (s.startsWith(QLatin1String("@Rect("))) {
                 QStringList args = QSettingsPrivate::splitArgs(s, 5);
                 if (args.size() == 4)
                     return QVariant(QRect(args[0].toInt(), args[1].toInt(), args[2].toInt(), args[3].toInt()));
             } else if (s.startsWith(QLatin1String("@Size("))) {
                 QStringList args = QSettingsPrivate::splitArgs(s, 5);
                 if (args.size() == 2)
                     return QVariant(QSize(args[0].toInt(), args[1].toInt()));
             } else if (s.startsWith(QLatin1String("@Point("))) {
                 QStringList args = QSettingsPrivate::splitArgs(s, 6);
                 if (args.size() == 2)
                     return QVariant(QPoint(args[0].toInt(), args[1].toInt()));
 #endif
             } else if (s == QLatin1String("@Invalid()")) {
                 return QVariant();
             }
         }
         if (s.startsWith(QLatin1String("@@")))
             return QVariant(s.mid(1));
     }
     return QVariant(s);
 }
sync()
virtual void QSettingsPrivate::sync () pure virtual
Implemented in QWinSettingsPrivate, QMacSettingsPrivate, and QConfFileSettingsPrivate.
Referenced by QConfFileSettingsPrivate::initAccess().
update()
void QSettingsPrivate::update ()
Definition at line 416 of file qsettings.cpp.
Referenced by requestUpdate().
 {
     flush();
     pendingChanges = false;
 }
variantListToStringList()
QStringList QSettingsPrivate::variantListToStringList (const QVariantList & l) static
Definition at line 435 of file qsettings.cpp.
Referenced by QWinSettingsPrivate::set(), and QConfFileSettingsPrivate::writeIniFile().
 {
     QStringList result;
     QVariantList::const_iterator it = l.constBegin();
     for (; it != l.constEnd(); ++it)
         result.append(variantToString(*it));
     return result;
 }
variantToString()
QString QSettingsPrivate::variantToString (const QVariant & v) static
Definition at line 464 of file qsettings.cpp.
Referenced by macValue(), QWinSettingsPrivate::set(), variantListToStringList(), and QConfFileSettingsPrivate::writeIniFile().
 {
     QString result;
     switch (v.type()) {
         case QVariant::Invalid:
             result = QLatin1String("@Invalid()");
             break;
         case QVariant::ByteArray: {
             QByteArray a = v.toByteArray();
             result = QLatin1String("@ByteArray(");
             result += QString::fromLatin1(a.constData(), a.size());
             result += QLatin1Char(')');
             break;
         }
         case QVariant::String:
         case QVariant::LongLong:
         case QVariant::ULongLong:
         case QVariant::Int:
         case QVariant::UInt:
         case QVariant::Bool:
         case QVariant::Double:
         case QVariant::KeySequence: {
             result = v.toString();
             if (result.startsWith(QLatin1Char('@')))
                 result.prepend(QLatin1Char('@'));
             break;
         }
 #ifndef QT_NO_GEOM_VARIANT
         case QVariant::Rect: {
             QRect r = qvariant_cast<QRect>(v);
             result += QLatin1String("@Rect(");
             result += QString::number(r.x());
             result += QLatin1Char(' ');
             result += QString::number(r.y());
             result += QLatin1Char(' ');
             result += QString::number(r.width());
             result += QLatin1Char(' ');
             result += QString::number(r.height());
             result += QLatin1Char(')');
             break;
         }
         case QVariant::Size: {
             QSize s = qvariant_cast<QSize>(v);
             result += QLatin1String("@Size(");
             result += QString::number(s.width());
             result += QLatin1Char(' ');
             result += QString::number(s.height());
             result += QLatin1Char(')');
             break;
         }
         case QVariant::Point: {
             QPoint p = qvariant_cast<QPoint>(v);
             result += QLatin1String("@Point(");
             result += QString::number(p.x());
             result += QLatin1Char(' ');
             result += QString::number(p.y());
             result += QLatin1Char(')');
             break;
         }
 #endif // !QT_NO_GEOM_VARIANT
         default: {
 #ifndef QT_NO_DATASTREAM
             QByteArray a;
             {
                 QDataStream s(&a, QIODevice::WriteOnly);
                 s.setVersion(QDataStream::Qt_4_0);
                 s << v;
             }
             result = QLatin1String("@Variant(");
             result += QString::fromLatin1(a.constData(), a.size());
             result += QLatin1Char(')');
 #else
             Q_ASSERT(!"QSettings: Cannot save custom types without QDataStream support");
 #endif
             break;
         }
     }
     return result;
 }
Properties
applicationName
QString QSettingsPrivate::applicationName
Definition at line 261 of file qsettings_p.h.
fallbacks
bool QSettingsPrivate::fallbacks protected
Definition at line 268 of file qsettings_p.h.
Referenced by QConfFileSettingsPrivate::children(), QMacSettingsPrivate::children(), QWinSettingsPrivate::children(), QConfFileSettingsPrivate::get(), QMacSettingsPrivate::get(), and QWinSettingsPrivate::get().
format
QSettings::Format QSettingsPrivate::format
Definition at line 258 of file qsettings_p.h.
Referenced by QSettings::registerFormat().
groupPrefix
QString QSettingsPrivate::groupPrefix protected
Definition at line 266 of file qsettings_p.h.
Referenced by actualKey(), and beginGroupOrArray().
groupStack
QStack<QSettingsGroup> QSettingsPrivate::groupStack protected
Definition at line 265 of file qsettings_p.h.
Referenced by beginGroupOrArray().
iniCodec
QTextCodec* QSettingsPrivate::iniCodec
Definition at line 262 of file qsettings_p.h.
Referenced by QConfFileSettingsPrivate::ensureAllSectionsParsed(), QConfFileSettingsPrivate::ensureSectionParsed(), and QConfFileSettingsPrivate::writeIniFile().
organizationName
QString QSettingsPrivate::organizationName
Definition at line 260 of file qsettings_p.h.
pendingChanges
bool QSettingsPrivate::pendingChanges protected
Definition at line 269 of file qsettings_p.h.
Referenced by requestUpdate(), and update().
scope
QSettings::Scope QSettingsPrivate::scope
Definition at line 259 of file qsettings_p.h.
Referenced by QWinSettingsPrivate::isWritable(), and normalizedKey().
spec
int QSettingsPrivate::spec protected
Definition at line 267 of file qsettings_p.h.
Referenced by QConfFileSettingsPrivate::children(), QMacSettingsPrivate::children(), QConfFileSettingsPrivate::clear(), QConfFileSettingsPrivate::fileName(), QMacSettingsPrivate::fileName(), QConfFileSettingsPrivate::initAccess(), QConfFileSettingsPrivate::isWritable(), QConfFileSettingsPrivate::QConfFileSettingsPrivate(), QMacSettingsPrivate::QMacSettingsPrivate(), QConfFileSettingsPrivate::remove(), and QConfFileSettingsPrivate::set().
status
QSettings::Status QSettingsPrivate::status mutable protected
Definition at line 270 of file qsettings_p.h.
Referenced by QMacSettingsPrivate::isWritable(), setStatus(), and QMacSettingsPrivate::sync().
The documentation for this class was generated from the following files:
/src/corelib/io/qsettings_p.h
/src/corelib/io/qsettings.cpp
/src/corelib/io/qsettings_mac.cpp
/src/corelib/io/qsettings_win.cpp