Qt 4.8: QAccessibleTable2 Class Reference
QAccessibleTable2 Class Reference
#include <itemviews.h>
Public Functions
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
virtual QAccessibleInterface * caption () const
virtual QAccessibleTable2CellInterface * cellAt (int row, int column) const
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
virtual int columnCount () const
virtual QString columnDescription (int column) const
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
int indexOfChild (const QAccessibleInterface *) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethodEx (Method, int, const QVariantList &)
virtual bool isColumnSelected (int column) const
virtual bool isRowSelected (int row) const
virtual QAccessible2::TableModelChange modelChange () const
int navigate (RelationFlag relation, int index, QAccessibleInterface **iface) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QAccessibleTable2 (QWidget *w)
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
virtual int rowCount () const
virtual QString rowDescription (int row) const
virtual bool selectColumn (int column)
virtual int selectedCellCount () const
virtual QList< QAccessibleTable2CellInterface * > selectedCells () const
virtual int selectedColumnCount () const
virtual QList< int > selectedColumns () const
virtual int selectedRowCount () const
virtual QList< int > selectedRows () const
virtual bool selectRow (int row)
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
virtual QAccessibleInterface * summary () const
QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
virtual bool unselectColumn (int column)
virtual bool unselectRow (int row)
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
QAbstractItemView * view () const
virtual ~QAccessibleTable2 ()
Public Functions inherited from QAccessibleTable2Interface
QAccessible2Interface * qAccessibleTable2CastHelper ()
Public Functions inherited from QAccessible2Interface
virtual ~QAccessible2Interface ()
Public Functions inherited from QAccessibleObjectEx
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Protected Functions
QAccessibleTable2Cell * cell (const QModelIndex &index) const
QAccessible::Role cellRole () const
virtual void columnsInserted (const QModelIndex &parent, int first, int last)
virtual void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
virtual void columnsRemoved (const QModelIndex &parent, int first, int last)
QHeaderView * horizontalHeader () const
virtual void modelReset ()
virtual void rowsInserted (const QModelIndex &parent, int first, int last)
virtual void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
virtual void rowsRemoved (const QModelIndex &parent, int first, int last)
QHeaderView * verticalHeader () const
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Protected Variables
QAccessible2::TableModelChange lastChange
Private Functions
QAccessibleInterface * childFromLogical (int logicalIndex) const
int logicalIndex (const QModelIndex &index) const
Properties
QAccessible::Role m_role
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 63 of file itemviews.h.
Constructors and Destructors
QAccessibleTable2()
QAccessibleTable2::QAccessibleTable2 (QWidget * w) explicit
Definition at line 123 of file itemviews.cpp.
     : QAccessibleObjectEx(w)
 {
     Q_ASSERT(view());
     if (qobject_cast<const QTableView*>(view())) {
         m_role = QAccessible::Table;
     } else if (qobject_cast<const QTreeView*>(view())) {
         m_role = QAccessible::Tree;
     } else if (qobject_cast<const QListView*>(view())) {
         m_role = QAccessible::List;
     } else {
         // is this our best guess?
         m_role = QAccessible::Table;
     }
 }
~QAccessibleTable2()
QAccessibleTable2::~QAccessibleTable2 () virtual
Definition at line 140 of file itemviews.cpp.
 {
 }
Functions
actionText()
QString QAccessibleTable2::actionText (int action, Text t, int child) const virtual
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
See also
text(), userActionCount()
Reimplemented from QAccessibleObjectEx.
Definition at line 523 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::indexOfChild(), and QAccessibleTable2HeaderCell::indexOfChild().
 {
     return QString();
 }
caption()
QAccessibleInterface * QAccessibleTable2::caption () const virtual
Implements QAccessibleTable2Interface.
Definition at line 250 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     return 0;
 }
cell()
QAccessibleTable2Cell * QAccessibleTable2::cell (const QModelIndex & index) const inline protected
Definition at line 229 of file itemviews.cpp.
Referenced by cellAt(), indexOfChild(), QAccessibleTree::indexOfChild(), QAccessibleTree::navigate(), and selectedCells().
 {
     if (index.isValid())
         return new QAccessibleTable2Cell(view(), index, cellRole());
     return 0;
 }
cellAt()
QAccessibleTable2CellInterface * QAccessibleTable2::cellAt (int row, int column) const virtual
Implements QAccessibleTable2Interface.
Reimplemented in QAccessibleTree.
Definition at line 236 of file itemviews.cpp.
Referenced by invokeMethodEx(), and QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->model())
         return 0;
     Q_ASSERT(role(0) != QAccessible::Tree);
     QModelIndex index = view()->model()->index(row, column, view()->rootIndex());
     //Q_ASSERT(index.isValid());
     if (!index.isValid()) {
         qWarning() << "QAccessibleTable2::cellAt: invalid index: " << index << " for " << view();
         return 0;
     }
     return cell(index);
 }
cellRole()
QAccessible::Role QAccessibleTable2::cellRole () const inline protected
Definition at line 128 of file itemviews.h.
Referenced by cell(), QAccessibleTree::cellAt(), and childFromLogical().
{
         switch (m_role) {
         case QAccessible::List:
             return QAccessible::ListItem;
         case QAccessible::Table:
             return QAccessible::Cell;
         case QAccessible::Tree:
             return QAccessible::TreeItem;
         default:
             Q_ASSERT(0);
         }
         return QAccessible::NoRole;
     }
childAt()
int QAccessibleTable2::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Implements QAccessibleInterface.
Reimplemented in QAccessibleTree.
Definition at line 421 of file itemviews.cpp.
Referenced by QAccessibleTree::~QAccessibleTree().
 {
     QPoint viewportOffset = view()->viewport()->mapTo(view(), QPoint(0,0));
     QPoint indexPosition = view()->mapFromGlobal(QPoint(x, y) - viewportOffset);
     // FIXME: if indexPosition < 0 in one coordinate, return header
     QModelIndex index = view()->indexAt(indexPosition);
     if (index.isValid()) {
         return logicalIndex(index);
     }
     return -1;
 }
childCount()
int QAccessibleTable2::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Implements QAccessibleInterface.
Reimplemented in QAccessibleTree.
Definition at line 434 of file itemviews.cpp.
Referenced by QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->model())
         return 0;
     int vHeader = verticalHeader() ? 1 : 0;
     int hHeader = horizontalHeader() ? 1 : 0;
     return (view()->model()->rowCount()+hHeader) * (view()->model()->columnCount()+vHeader);
 }
childFromLogical()
QAccessibleInterface * QAccessibleTable2::childFromLogical (int logicalIndex) const private
Definition at line 85 of file itemviews.cpp.
Referenced by cellRole(), and navigate().
 {
     if (!view()->model())
         return 0;
     logicalIndex--; // one based counting ftw
     int vHeader = verticalHeader() ? 1 : 0;
     int hHeader = horizontalHeader() ? 1 : 0;
     int columns = view()->model()->columnCount() + vHeader;
     int row = logicalIndex / columns;
     int column = logicalIndex % columns;
     if (vHeader) {
         if (column == 0) {
             if (row == 0) {
                 return new QAccessibleTable2CornerButton(view());
             }
             return new QAccessibleTable2HeaderCell(view(), row-1, Qt::Vertical);
         }
         --column;
     }
     if (hHeader) {
         if (row == 0) {
             return new QAccessibleTable2HeaderCell(view(), column, Qt::Horizontal);
         }
         --row;
     }
     QModelIndex index = view()->model()->index(row, column, view()->rootIndex());
     if (!index.isValid()) {
         qWarning() << "QAccessibleTable2::childFromLogical: Invalid index at: " << row << column;
         return 0;
     }
     return new QAccessibleTable2Cell(view(), index, cellRole());
 }
columnCount()
int QAccessibleTable2::columnCount () const virtual
Implements QAccessibleTable2Interface.
Definition at line 262 of file itemviews.cpp.
Referenced by QAccessibleTree::childAt(), invokeMethodEx(), and QAccessibleTree::navigate().
 {
     if (!view()->model())
         return 0;
     return view()->model()->columnCount();
 }
columnDescription()
QString QAccessibleTable2::columnDescription (int column) const virtual
Implements QAccessibleTable2Interface.
Definition at line 255 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->model())
         return QString();
     return view()->model()->headerData(column, Qt::Horizontal).toString();
 }
columnsInserted()
void QAccessibleTable2::columnsInserted (const QModelIndex & parent, int first, int last) protected virtual
Implements QAccessibleTable2Interface.
Definition at line 193 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     lastChange.firstRow = 0;
     lastChange.lastRow = 0;
     lastChange.firstColumn = first;
     lastChange.lastColumn = last;
     lastChange.type = QAccessible2::TableModelChangeInsert;
 }
columnsMoved()
void QAccessibleTable2::columnsMoved (const QModelIndex & parent, int start, int end, const QModelIndex & destination, int column) protected virtual
Implements QAccessibleTable2Interface.
Definition at line 220 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     lastChange.firstRow = 0;
     lastChange.lastRow = 0;
     lastChange.firstColumn = 0;
     lastChange.lastColumn = 0;
     lastChange.type = QAccessible2::TableModelChangeUpdate;
 }
columnsRemoved()
void QAccessibleTable2::columnsRemoved (const QModelIndex & parent, int first, int last) protected virtual
Implements QAccessibleTable2Interface.
Definition at line 202 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     lastChange.firstRow = 0;
     lastChange.lastRow = 0;
     lastChange.firstColumn = first;
     lastChange.lastColumn = last;
     lastChange.type = QAccessible2::TableModelChangeDelete;
 }
doAction()
bool QAccessibleTable2::doAction (int action, int child, const QVariantList & params) virtual
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
Returns true if the action could be executed; otherwise returns false.
action can be a predefined or a custom action.
See also
userActionCount(), actionText()
Reimplemented from QAccessibleObjectEx.
Definition at line 527 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::indexOfChild(), and QAccessibleTable2HeaderCell::indexOfChild().
 {
     return false;
 }
horizontalHeader()
QHeaderView * QAccessibleTable2::horizontalHeader () const protected
Definition at line 144 of file itemviews.cpp.
Referenced by cellRole(), QAccessibleTree::childAt(), childCount(), QAccessibleTree::childCount(), childFromLogical(), QAccessibleTree::indexOfChild(), QAccessibleTable2Cell::indexOfChild(), logicalIndex(), and QAccessibleTree::navigate().
 {
     QHeaderView *header = 0;
     if (false) {
 #ifndef QT_NO_TABLEVIEW
     } else if (const QTableView *tv = qobject_cast<const QTableView*>(view())) {
         header = tv->horizontalHeader();
 #endif
 #ifndef QT_NO_TREEVIEW
     } else if (const QTreeView *tv = qobject_cast<const QTreeView*>(view())) {
         header = tv->header();
 #endif
     }
     return header;
 }
indexOfChild()
int QAccessibleTable2::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Implements QAccessibleInterface.
Reimplemented in QAccessibleTree.
Definition at line 443 of file itemviews.cpp.
Referenced by QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->model())
         return -1;
     Q_ASSERT(iface->role(0) != QAccessible::TreeItem); // should be handled by tree class
     if (iface->role(0) == QAccessible::Cell || iface->role(0) == QAccessible::ListItem) {
         const QAccessibleTable2Cell* cell = static_cast<const QAccessibleTable2Cell*>(iface);
         return logicalIndex(cell->m_index);
     } else if (iface->role(0) == QAccessible::ColumnHeader){
         const QAccessibleTable2HeaderCell* cell = static_cast<const QAccessibleTable2HeaderCell*>(iface);
         return cell->index + (verticalHeader() ? 1 : 0) + 1;
     } else if (iface->role(0) == QAccessible::RowHeader){
         const QAccessibleTable2HeaderCell* cell = static_cast<const QAccessibleTable2HeaderCell*>(iface);
         return (cell->index+1) * (view()->model()->columnCount()+1)  + 1;
     } else if (iface->role(0) == QAccessible::Pane) {
         return 1; // corner button
     } else {
         qWarning() << "WARNING QAccessibleTable2::indexOfChild Fix my children..."
                    << iface->role(0) << iface->text(QAccessible::Name, 0);
     }
     // FIXME: we are in denial of our children. this should stop.
     return -1;
 }
invokeMethodEx()
QVariant QAccessibleTable2::invokeMethodEx (Method , int , const QVariantList &) inline virtual
Implements QAccessibleInterfaceEx.
Definition at line 88 of file itemviews.h.
 { return QVariant(); }
isColumnSelected()
bool QAccessibleTable2::isColumnSelected (int column) const virtual
Implements QAccessibleTable2Interface.
Definition at line 342 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->selectionModel())
         return false;
     return view()->selectionModel()->isColumnSelected(column, QModelIndex());
 }
isRowSelected()
bool QAccessibleTable2::isRowSelected (int row) const virtual
Implements QAccessibleTable2Interface.
Reimplemented in QAccessibleTree.
Definition at line 349 of file itemviews.cpp.
Referenced by invokeMethodEx(), and QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->selectionModel())
         return false;
     return view()->selectionModel()->isRowSelected(row, QModelIndex());
 }
logicalIndex()
int QAccessibleTable2::logicalIndex (const QModelIndex & index) const inline private
Definition at line 75 of file itemviews.cpp.
Referenced by cellRole(), childAt(), and indexOfChild().
 {
     if (!view()->model() || !index.isValid())
         return -1;
     int vHeader = verticalHeader() ? 1 : 0;
     int hHeader = horizontalHeader() ? 1 : 0;
     // row * number columns + column + 1 for one based counting
     return (index.row() + hHeader)*(index.model()->columnCount() + vHeader) + (index.column() + vHeader) + 1;
 }
modelChange()
QAccessible2::TableModelChange QAccessibleTable2::modelChange () const virtual
Implements QAccessibleTable2Interface.
Definition at line 400 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     QAccessible2::TableModelChange change;
     // FIXME
     return change;
 }
modelReset()
void QAccessibleTable2::modelReset () protected virtual
Implements QAccessibleTable2Interface.
Definition at line 172 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {}
navigate()
int QAccessibleTable2::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Implements QAccessibleInterface.
Reimplemented in QAccessibleTree.
Definition at line 484 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::indexOfChild(), QAccessibleTable2HeaderCell::indexOfChild(), QAccessibleTree::navigate(), and QAccessibleTree::~QAccessibleTree().
 {
     *iface = 0;
     if ((index < 0) || (!view()->model()))
         return -1;
     switch (relation) {
     case Ancestor: {
         if (index == 1 && view()->parent()) {
             *iface = QAccessible::queryAccessibleInterface(view()->parent());
             if (*iface)
                 return 0;
         }
         break;
     }
     case QAccessible::Child: {
         Q_ASSERT(index > 0);
         *iface = childFromLogical(index);
         if (*iface) {
             return 0;
         }
         break;
     }
     default:
         break;
     }
     return -1;
 }
rect()
QRect QAccessibleTable2::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Reimplemented from QAccessibleObjectEx.
Definition at line 475 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::object(), and QAccessibleTable2HeaderCell::object().
 {
     Q_ASSERT(!child);
     if (!view()->isVisible())
         return QRect();
     QPoint pos = view()->mapToGlobal(QPoint(0, 0));
     return QRect(pos.x(), pos.y(), view()->width(), view()->height());
 }
relationTo()
QAccessible::Relation QAccessibleTable2::relationTo (int child, const QAccessibleInterface * other, int otherChild) const virtual
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
If child is 0 the object's own relation is returned.
The returned value indicates the relation of the called object to the other object, e.g. if this object is a child of other the return value will be Child.
The return value is a combination of the bit flags in the QAccessible::Relation enumeration.
All objects provide this information.
See also
indexOfChild(), navigate()
Implements QAccessibleInterface.
Reimplemented in QAccessibleTree.
Definition at line 513 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::indexOfChild(), QAccessibleTable2HeaderCell::indexOfChild(), and QAccessibleTree::~QAccessibleTree().
 {
     return QAccessible::Unrelated;
 }
role()
QAccessible::Role QAccessibleTable2::role (int child) const virtual
Returns the role of the object, or of the object's child if child is not 0.
The role of an object is usually static.
All accessible objects have a role.
See also
text(), state()
Implements QAccessibleInterface.
Definition at line 407 of file itemviews.cpp.
Referenced by cellAt(), QAccessibleTable2Cell::object(), and QAccessibleTable2HeaderCell::object().
 {
     Q_ASSERT(child >= 0);
     if (child > 0)
         return QAccessible::Cell;
     return m_role;
 }
rowCount()
int QAccessibleTable2::rowCount () const virtual
Implements QAccessibleTable2Interface.
Reimplemented in QAccessibleTree.
Definition at line 269 of file itemviews.cpp.
Referenced by childCount(), invokeMethodEx(), and QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->model())
         return 0;
     return view()->model()->rowCount();
 }
rowDescription()
QString QAccessibleTable2::rowDescription (int row) const virtual
Implements QAccessibleTable2Interface.
Reimplemented in QAccessibleTree.
Definition at line 297 of file itemviews.cpp.
Referenced by invokeMethodEx(), and QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->model())
         return QString();
     return view()->model()->headerData(row, Qt::Vertical).toString();
 }
rowsInserted()
void QAccessibleTable2::rowsInserted (const QModelIndex & parent, int first, int last) protected virtual
Implements QAccessibleTable2Interface.
Definition at line 175 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     lastChange.firstRow = first;
     lastChange.lastRow = last;
     lastChange.firstColumn = 0;
     lastChange.lastColumn = 0;
     lastChange.type = QAccessible2::TableModelChangeInsert;
 }
rowsMoved()
void QAccessibleTable2::rowsMoved (const QModelIndex & parent, int start, int end, const QModelIndex & destination, int row) protected virtual
Implements QAccessibleTable2Interface.
Definition at line 211 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     lastChange.firstRow = 0;
     lastChange.lastRow = 0;
     lastChange.firstColumn = 0;
     lastChange.lastColumn = 0;
     lastChange.type = QAccessible2::TableModelChangeUpdate;
 }
rowsRemoved()
void QAccessibleTable2::rowsRemoved (const QModelIndex & parent, int first, int last) protected virtual
Implements QAccessibleTable2Interface.
Definition at line 184 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     lastChange.firstRow = first;
     lastChange.lastRow = last;
     lastChange.firstColumn = 0;
     lastChange.lastColumn = 0;
     lastChange.type = QAccessible2::TableModelChangeDelete;
 }
selectColumn()
bool QAccessibleTable2::selectColumn (int column) virtual
Implements QAccessibleTable2Interface.
Definition at line 367 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->model() || !view()->selectionModel())
         return false;
     QModelIndex index = view()->model()->index(0, column, view()->rootIndex());
     if (!index.isValid() || view()->selectionMode() & QAbstractItemView::NoSelection)
         return false;
     view()->selectionModel()->select(index, QItemSelectionModel::Select);
     return true;
 }
selectedCellCount()
int QAccessibleTable2::selectedCellCount () const virtual
Implements QAccessibleTable2Interface.
Definition at line 276 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->selectionModel())
         return 0;
     return view()->selectionModel()->selectedIndexes().count();
 }
selectedCells()
QList< QAccessibleTable2CellInterface * > QAccessibleTable2::selectedCells () const virtual
Implements QAccessibleTable2Interface.
Definition at line 304 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     QList<QAccessibleTable2CellInterface*> cells;
     if (!view()->selectionModel())
         return cells;
     Q_FOREACH (const QModelIndex &index, view()->selectionModel()->selectedIndexes()) {
         cells.append(cell(index));
     }
     return cells;
 }
selectedColumnCount()
int QAccessibleTable2::selectedColumnCount () const virtual
Implements QAccessibleTable2Interface.
Definition at line 283 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->selectionModel())
         return 0;
     return view()->selectionModel()->selectedColumns().count();
 }
selectedColumns()
QList< int > QAccessibleTable2::selectedColumns () const virtual
Implements QAccessibleTable2Interface.
Definition at line 315 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     QList<int> columns;
     if (!view()->selectionModel())
         return columns;
     Q_FOREACH (const QModelIndex &index, view()->selectionModel()->selectedColumns()) {
         columns.append(index.column());
     }
     return columns;
 }
selectedRowCount()
int QAccessibleTable2::selectedRowCount () const virtual
Implements QAccessibleTable2Interface.
Definition at line 290 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->selectionModel())
         return 0;
     return view()->selectionModel()->selectedRows().count();
 }
selectedRows()
QList< int > QAccessibleTable2::selectedRows () const virtual
Implements QAccessibleTable2Interface.
Definition at line 326 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->selectionModel())
         return QList<int>();
     QList<int> rows;
     Q_FOREACH (const QModelIndex &index, view()->selectionModel()->selectedRows()) {
         rows.append(index.row());
     }
     return rows;
 }
selectRow()
bool QAccessibleTable2::selectRow (int row) virtual
Implements QAccessibleTable2Interface.
Reimplemented in QAccessibleTree.
Definition at line 356 of file itemviews.cpp.
Referenced by invokeMethodEx(), and QAccessibleTree::~QAccessibleTree().
 {
     if (!view()->model() || !view()->selectionModel())
         return false;
     QModelIndex index = view()->model()->index(row, 0, view()->rootIndex());
     if (!index.isValid() || view()->selectionMode() & QAbstractItemView::NoSelection)
         return false;
     view()->selectionModel()->select(index, QItemSelectionModel::Select);
     return true;
 }
state()
QAccessible::State QAccessibleTable2::state (int child) const virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Implements QAccessibleInterface.
Definition at line 415 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::object(), and QAccessibleTable2HeaderCell::object().
 {
     Q_ASSERT(child == 0);
     return QAccessible::Normal | HasInvokeExtension;
 }
summary()
QAccessibleInterface * QAccessibleTable2::summary () const virtual
Implements QAccessibleTable2Interface.
Definition at line 337 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     return 0;
 }
text()
QString QAccessibleTable2::text (Text t, int child) const virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Implements QAccessibleInterface.
Definition at line 467 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::indexOfChild(), and QAccessibleTable2HeaderCell::indexOfChild().
 {
     Q_ASSERT(child == 0);
     if (t == QAccessible::Description)
         return view()->accessibleDescription();
     return view()->accessibleName();
 }
unselectColumn()
bool QAccessibleTable2::unselectColumn (int column) virtual
Implements QAccessibleTable2Interface.
Definition at line 389 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->model() || !view()->selectionModel())
         return false;
     QModelIndex index = view()->model()->index(0, column, view()->rootIndex());
     if (!index.isValid() || view()->selectionMode() & QAbstractItemView::NoSelection)
         return false;
     view()->selectionModel()->select(index, QItemSelectionModel::Columns & QItemSelectionModel::Deselect);
     return true;
 }
unselectRow()
bool QAccessibleTable2::unselectRow (int row) virtual
Implements QAccessibleTable2Interface.
Definition at line 378 of file itemviews.cpp.
Referenced by invokeMethodEx().
 {
     if (!view()->model() || !view()->selectionModel())
         return false;
     QModelIndex index = view()->model()->index(row, 0, view()->rootIndex());
     if (!index.isValid() || view()->selectionMode() & QAbstractItemView::NoSelection)
         return false;
     view()->selectionModel()->select(index, QItemSelectionModel::Deselect);
     return true;
 }
userActionCount()
int QAccessibleTable2::userActionCount (int child) const virtual
Returns the number of custom actions of the object, or of the object's child if child is not 0.
The Action type enumerates predefined actions: these are not included in the returned value.
See also
actionText(), doAction()
Reimplemented from QAccessibleObjectEx.
Definition at line 519 of file itemviews.cpp.
Referenced by QAccessibleTable2Cell::indexOfChild(), and QAccessibleTable2HeaderCell::indexOfChild().
 {
     return 0;
 }
verticalHeader()
QHeaderView * QAccessibleTable2::verticalHeader () const protected
Definition at line 160 of file itemviews.cpp.
Referenced by cellRole(), childCount(), childFromLogical(), indexOfChild(), QAccessibleTable2Cell::indexOfChild(), and logicalIndex().
 {
     QHeaderView *header = 0;
     if (false) {
 #ifndef QT_NO_TABLEVIEW
     } else if (const QTableView *tv = qobject_cast<const QTableView*>(view())) {
         header = tv->verticalHeader();
 #endif
     }
     return header;
 }
view()
QAbstractItemView * QAccessibleTable2::view () const
Definition at line 70 of file itemviews.cpp.
Referenced by cell(), cellAt(), QAccessibleTree::cellAt(), childAt(), QAccessibleTree::childAt(), childCount(), QAccessibleTree::childCount(), childFromLogical(), columnCount(), columnDescription(), horizontalHeader(), QAccessibleTree::indexFromLogical(), indexOfChild(), QAccessibleTree::indexOfChild(), invokeMethodEx(), isColumnSelected(), isRowSelected(), QAccessibleTree::isRowSelected(), logicalIndex(), navigate(), QAccessibleTree::navigate(), QAccessibleTable2CornerButton::navigate(), QAccessibleTable2(), rect(), rowCount(), QAccessibleTree::rowCount(), rowDescription(), selectColumn(), selectedCellCount(), selectedCells(), selectedColumnCount(), selectedColumns(), selectedRowCount(), selectedRows(), selectRow(), QAccessibleTree::selectRow(), text(), unselectColumn(), unselectRow(), and verticalHeader().
 {
     return qobject_cast<QAbstractItemView*>(object());
 }
Properties
lastChange
QAccessible2::TableModelChange QAccessibleTable2::lastChange protected
Definition at line 126 of file itemviews.h.
Referenced by columnsInserted(), columnsMoved(), columnsRemoved(), rowsInserted(), rowsMoved(), and rowsRemoved().
m_role
QAccessible::Role QAccessibleTable2::m_role private
Definition at line 149 of file itemviews.h.
Referenced by cellRole(), QAccessibleTable2(), and role().
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/itemviews.h
/src/plugins/accessible/widgets/itemviews.cpp