Qt 4.8: QTestEvent Class Reference
QTestEvent Class Reference abstract
#include <qtestevent.h>
Public Functions
virtual QTestEvent * clone () const =0
virtual void simulate (QWidget *w)=0
virtual ~QTestEvent ()
Detailed Description
Definition at line 67 of file qtestevent.h.
Constructors and Destructors
~QTestEvent()
virtual QTestEvent::~QTestEvent () inline virtual
Definition at line 73 of file qtestevent.h.
 {}
Functions
clone()
virtual QTestEvent* QTestEvent::clone () const pure virtual
Implemented in QTestDelayEvent.
Referenced by QTestEventList::QTestEventList(), and ~QTestEvent().
simulate()
virtual void QTestEvent::simulate (QWidget * w) pure virtual
Implemented in QTestDelayEvent.
Referenced by ~QTestEvent().
The documentation for this class was generated from the following file:
/src/testlib/qtestevent.h