Qt 4.8: QLocalSocket Class Reference
QLocalSocket Class Reference
The QLocalSocket class provides a local socket.
#include <qlocalsocket.h>
Public Types
enum LocalSocketError {
ConnectionRefusedError = QAbstractSocket::ConnectionRefusedError, PeerClosedError = QAbstractSocket::RemoteHostClosedError, ServerNotFoundError = QAbstractSocket::HostNotFoundError, SocketAccessError = QAbstractSocket::SocketAccessError,
SocketResourceError = QAbstractSocket::SocketResourceError, SocketTimeoutError = QAbstractSocket::SocketTimeoutError, DatagramTooLargeError = QAbstractSocket::DatagramTooLargeError, ConnectionError = QAbstractSocket::NetworkError,
UnsupportedSocketOperationError = QAbstractSocket::UnsupportedSocketOperationError, UnknownSocketError = QAbstractSocket::UnknownSocketError
}
The LocalServerError enumeration represents the errors that can occur.
enum LocalSocketState { UnconnectedState = QAbstractSocket::UnconnectedState, ConnectingState = QAbstractSocket::ConnectingState, ConnectedState = QAbstractSocket::ConnectedState, ClosingState = QAbstractSocket::ClosingState }
This enum describes the different states in which a socket can be.
Public Types inherited from QIODevice
enum OpenModeFlag {
NotOpen = 0x0000, ReadOnly = 0x0001, WriteOnly = 0x0002, ReadWrite = ReadOnly | WriteOnly,
Append = 0x0004, Truncate = 0x0008, Text = 0x0010, Unbuffered = 0x0020
}
This enum is used with open() to describe the mode in which a device is opened.
Signals
void connected ()
This signal is emitted after connectToServer() has been called and a connection has been successfully established.
void disconnected ()
This signal is emitted when the socket has been disconnected.
void error (QLocalSocket::LocalSocketError socketError)
This signal is emitted after an error occurred.
void stateChanged (QLocalSocket::LocalSocketState socketState)
This signal is emitted whenever QLocalSocket's state changes.
Signals inherited from QIODevice
void aboutToClose ()
This signal is emitted when the device is about to close.
void bytesWritten (qint64 bytes)
This signal is emitted every time a payload of data has been written to the device.
void readChannelFinished ()
This signal is emitted when the input (reading) stream is closed in this device.
void readyRead ()
This signal is emitted once every time new data is available for reading from the device.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void abort ()
Aborts the current connection and resets the socket.
virtual qint64 bytesAvailable () const
Reimplemented Function
virtual qint64 bytesToWrite () const
Reimplemented Function
virtual bool canReadLine () const
Reimplemented Function
virtual void close ()
Reimplemented Function
void connectToServer (const QString &name, OpenMode openMode=ReadWrite)
Attempts to make a connection to name.
void disconnectFromServer ()
Attempts to close the socket.
LocalSocketError error () const
Returns the type of error that last occurred.
bool flush ()
This function writes as much as possible from the internal write buffer to the socket, without blocking.
QString fullServerName () const
Returns the server path that the socket is connected to.
virtual bool isSequential () const
Reimplemented Function
bool isValid () const
Returns true if the socket is valid and ready for use; otherwise returns false.
QLocalSocket (QObject *parent=0)
Creates a new local socket.
qint64 readBufferSize () const
Returns the size of the internal read buffer.
QString serverName () const
Returns the name of the peer as specified by connectToServer(), or an empty QString if connectToServer() has not been called or it failed.
void setReadBufferSize (qint64 size)
Sets the size of QLocalSocket's internal read buffer to be size bytes.
bool setSocketDescriptor (quintptr socketDescriptor, LocalSocketState socketState=ConnectedState, OpenMode openMode=ReadWrite)
quintptr socketDescriptor () const
Returns the native socket descriptor of the QLocalSocket object if this is available; otherwise returns -1.
LocalSocketState state () const
Returns the state of the socket.
bool waitForBytesWritten (int msecs=30000)
Reimplemented Function
bool waitForConnected (int msecs=30000)
Waits until the socket is connected, up to msecs milliseconds.
bool waitForDisconnected (int msecs=30000)
Waits until the socket has disconnected, up to msecs milliseconds.
bool waitForReadyRead (int msecs=30000)
This function blocks until data is available for reading and the QIODevice::readyRead() signal has been emitted.
~QLocalSocket ()
Destroys the socket, closing the connection if necessary.
Public Functions inherited from QIODevice
virtual bool atEnd () const
Returns true if the current read and write position is at the end of the device (i.e.
QString errorString () const
Returns a human-readable description of the last device error that occurred.
bool getChar (char *c)
Reads one character from the device and stores it in c.
bool isOpen () const
Returns true if the device is open; otherwise returns false.
bool isReadable () const
Returns true if data can be read from the device; otherwise returns false.
bool isTextModeEnabled () const
Returns true if the Text flag is enabled; otherwise returns false.
bool isWritable () const
Returns true if data can be written to the device; otherwise returns false.
virtual bool open (OpenMode mode)
Opens the device and sets its OpenMode to mode.
OpenMode openMode () const
Returns the mode in which the device has been opened; i.e.
qint64 peek (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, without side effects (i.
QByteArray peek (qint64 maxlen)
Peeks at most maxSize bytes from the device, returning the data peeked as a QByteArray.
virtual qint64 pos () const
For random-access devices, this function returns the position that data is written to or read from.
bool putChar (char c)
Writes the character c to the device.
QIODevice ()
Constructs a QIODevice object.
QIODevice (QObject *parent)
Constructs a QIODevice object with the given parent.
qint64 read (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, and returns the number of bytes read.
QByteArray read (qint64 maxlen)
Reads at most maxSize bytes from the device, and returns the data read as a QByteArray.
QByteArray readAll ()
Reads all available data from the device, and returns it as a QByteArray.
qint64 readLine (char *data, qint64 maxlen)
This function reads a line of ASCII characters from the device, up to a maximum of maxSize - 1 bytes, stores the characters in data, and returns the number of bytes read.
QByteArray readLine (qint64 maxlen=0)
Reads a line from the device, but no more than maxSize characters, and returns the result as a QByteArray.
virtual bool reset ()
Seeks to the start of input for random-access devices.
virtual bool seek (qint64 pos)
For random-access devices, this function sets the current position to pos, returning true on success, or false if an error occurred.
void setTextModeEnabled (bool enabled)
If enabled is true, this function sets the Text flag on the device; otherwise the Text flag is removed.
virtual qint64 size () const
For open random-access devices, this function returns the size of the device.
void ungetChar (char c)
Puts the character c back into the device, and decrements the current position unless the position is 0.
qint64 write (const char *data, qint64 len)
Writes at most maxSize bytes of data from data to the device.
qint64 write (const char *data)
Writes data from a zero-terminated string of 8-bit characters to the device.
qint64 write (const QByteArray &data)
Writes the content of byteArray to the device.
virtual ~QIODevice ()
The destructor is virtual, and QIODevice is an abstract base class.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual qint64 readData (char *, qint64)
Reimplemented Function
virtual qint64 writeData (const char *, qint64)
Reimplemented Function
Protected Functions inherited from QIODevice
QIODevice (QIODevicePrivate &dd, QObject *parent=0)
virtual qint64 readLineData (char *data, qint64 maxlen)
Reads up to maxSize characters into data and returns the number of characters read.
void setErrorString (const QString &errorString)
Sets the human readable description of the last device error that occurred to str.
void setOpenMode (OpenMode openMode)
Sets the OpenMode of the device to openMode.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QLocalSocket class provides a local socket.
Since
4.4
On Windows this is a named pipe and on Unix this is a local domain socket.
If an error occurs, socketError() returns the type of error, and errorString() can be called to get a human readable description of what happened.
Although QLocalSocket is designed for use with an event loop, it's possible to use it without one. In that case, you must use waitForConnected(), waitForReadyRead(), waitForBytesWritten(), and waitForDisconnected() which blocks until the operation is complete or the timeout expires.
Note that this feature is not supported on versions of Windows earlier than Windows XP.
See also
QLocalServer
Definition at line 58 of file qlocalsocket.h.
Enumerations
LocalSocketError
enum QLocalSocket::LocalSocketError
The LocalServerError enumeration represents the errors that can occur.
The most recent error can be retrieved through a call to QLocalSocket::error() .
ConnectionRefusedError The connection was refused by the peer (or timed out).
PeerClosedError The remote socket closed the connection. Note that the client socket (i.e., this socket) will be closed after the remote close notification has been sent.
ServerNotFoundError The local socket name was not found.
SocketAccessError The socket operation failed because the application lacked the required privileges.
SocketResourceError The local system ran out of resources (e.g., too many sockets).
SocketTimeoutError The socket operation timed out.
DatagramTooLargeError The datagram was larger than the operating system's limit (which can be as low as 8192 bytes).
ConnectionError An error occurred with the connection.
UnsupportedSocketOperationError The requested socket operation is not supported by the local operating system.
UnknownSocketError An unidentified error occurred.
Enumerator
ConnectionRefusedError
PeerClosedError
ServerNotFoundError
SocketAccessError
SocketResourceError
SocketTimeoutError
DatagramTooLargeError
ConnectionError
UnsupportedSocketOperationError
UnknownSocketError
Definition at line 64 of file qlocalsocket.h.
     {
         ConnectionRefusedError = QAbstractSocket::ConnectionRefusedError,
         PeerClosedError = QAbstractSocket::RemoteHostClosedError,
         ServerNotFoundError = QAbstractSocket::HostNotFoundError,
         SocketAccessError = QAbstractSocket::SocketAccessError,
         SocketResourceError = QAbstractSocket::SocketResourceError,
         SocketTimeoutError = QAbstractSocket::SocketTimeoutError,
         DatagramTooLargeError = QAbstractSocket::DatagramTooLargeError,
         ConnectionError = QAbstractSocket::NetworkError,
         UnsupportedSocketOperationError = QAbstractSocket::UnsupportedSocketOperationError,
         UnknownSocketError = QAbstractSocket::UnknownSocketError
     };
LocalSocketState
enum QLocalSocket::LocalSocketState
This enum describes the different states in which a socket can be.
See also
QLocalSocket::state()
UnconnectedState The socket is not connected.
ConnectingState The socket has started establishing a connection.
ConnectedState A connection is established.
ClosingState The socket is about to close (data may still be waiting to be written).
Enumerator
UnconnectedState
ConnectingState
ConnectedState
ClosingState
Definition at line 78 of file qlocalsocket.h.
     {
         UnconnectedState = QAbstractSocket::UnconnectedState,
         ConnectingState = QAbstractSocket::ConnectingState,
         ConnectedState = QAbstractSocket::ConnectedState,
         ClosingState = QAbstractSocket::ClosingState
     };
Constructors and Destructors
QLocalSocket()
QLocalSocket::QLocalSocket (QObject * parent = 0)
Creates a new local socket.
The parent argument is passed to QObject's constructor.
Definition at line 390 of file qlocalsocket.cpp.
     : QIODevice(*new QLocalSocketPrivate, parent)
 {
     Q_D(QLocalSocket);
     d->init();
 }
~QLocalSocket()
QLocalSocket::~QLocalSocket ()
Destroys the socket, closing the connection if necessary.
Definition at line 400 of file qlocalsocket.cpp.
 {
     close();
 #if !defined(Q_OS_WIN) && !defined(QT_LOCALSOCKET_TCP)
     Q_D(QLocalSocket);
     d->unixSocket.setParent(0);
 #endif
 }
Functions
abort()
void QLocalSocket::abort ()
Aborts the current connection and resets the socket.
Unlike disconnectFromServer(), this function immediately closes the socket, clearing any pending data in the write buffer.
See also
disconnectFromServer(), close()
Definition at line 308 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::completeAsyncRead().
 {
     Q_D(QLocalSocket);
     d->tcpSocket->abort();
 }
bytesAvailable()
qint64 QLocalSocket::bytesAvailable () const virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 314 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed().
 {
     Q_D(const QLocalSocket);
     return QIODevice::bytesAvailable() + d->tcpSocket->bytesAvailable();
 }
bytesToWrite()
qint64 QLocalSocket::bytesToWrite () const virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 320 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed().
 {
     Q_D(const QLocalSocket);
     return d->tcpSocket->bytesToWrite();
 }
canReadLine()
bool QLocalSocket::canReadLine () const virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 326 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed().
 {
     Q_D(const QLocalSocket);
     return QIODevice::canReadLine() || d->tcpSocket->canReadLine();
 }
close()
void QLocalSocket::close () virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 332 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed(), and ~QLocalSocket().
 {
     Q_D(QLocalSocket);
     d->tcpSocket->close();
     d->serverName.clear();
     d->fullServerName.clear();
     QIODevice::close();
 }
connected
void QLocalSocket::connected () signal
This signal is emitted after connectToServer() has been called and a connection has been successfully established.
See also
connectToServer(), disconnected()
connectToServer()
void QLocalSocket::connectToServer (const QString & name, OpenMode openMode = ReadWrite)
Attempts to make a connection to name.
The socket is opened in the given openMode and first enters ConnectingState. It then attempts to connect to the address or addresses returned by the lookup. Finally, if a connection is established, QLocalSocket enters ConnectedState and emits connected().
At any point, the socket can emit error() to signal that an error occurred.
See also state(), serverName(), and waitForConnected().
Definition at line 214 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::destroyPipeHandles().
 {
     Q_D(QLocalSocket);
     if (state() == ConnectedState
         || state() == ConnectingState)
         return;
     d->errorString.clear();
     d->state = ConnectingState;
     emit stateChanged(d->state);
     if (name.isEmpty()) {
         d->errorOccurred(ServerNotFoundError,
                          QLatin1String("QLocalSocket::connectToServer"));
         return;
     }
     d->serverName = name;
     const QLatin1String prefix("QLocalServer/");
     if (name.startsWith(prefix))
         d->fullServerName = name;
     else
         d->fullServerName = prefix + name;
     QSettings settings(QLatin1String("Trolltech"), QLatin1String("Qt"));
     bool ok;
     const quint16 port = settings.value(d->fullServerName).toUInt(&ok);
     if (!ok) {
         d->errorOccurred(ServerNotFoundError,
                          QLatin1String("QLocalSocket::connectToServer"));
         return;
     }
     d->tcpSocket->connectToHost(QHostAddress::LocalHost, port, openMode);
     QIODevice::open(openMode);
 }
disconnected
void QLocalSocket::disconnected () signal
This signal is emitted when the socket has been disconnected.
See also
connectToServer(), disconnectFromServer(), abort(), connected()
disconnectFromServer()
void QLocalSocket::disconnectFromServer ()
Attempts to close the socket.
If there is pending data waiting to be written, QLocalSocket will enter ClosingState and wait until all data has been written. Eventually, it will enter UnconnectedState and emit the disconnectedFromServer() signal.
See also
connectToServer()
Definition at line 353 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed().
 {
     Q_D(QLocalSocket);
     d->tcpSocket->disconnectFromHost();
 }
error() [1/2]
QLocalSocket::LocalSocketError QLocalSocket::error () const
Returns the type of error that last occurred.
See also
state(), errorString()
Definition at line 359 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed().
 {
     Q_D(const QLocalSocket);
     switch (d->tcpSocket->error()) {
     case QAbstractSocket::ConnectionRefusedError:
         return QLocalSocket::ConnectionRefusedError;
     case QAbstractSocket::RemoteHostClosedError:
         return QLocalSocket::PeerClosedError;
     case QAbstractSocket::HostNotFoundError:
         return QLocalSocket::ServerNotFoundError;
     case QAbstractSocket::SocketAccessError:
         return QLocalSocket::SocketAccessError;
     case QAbstractSocket::SocketResourceError:
         return QLocalSocket::SocketResourceError;
     case QAbstractSocket::SocketTimeoutError:
         return QLocalSocket::SocketTimeoutError;
     case QAbstractSocket::DatagramTooLargeError:
         return QLocalSocket::DatagramTooLargeError;
     case QAbstractSocket::NetworkError:
         return QLocalSocket::ConnectionError;
     case QAbstractSocket::UnsupportedSocketOperationError:
         return QLocalSocket::UnsupportedSocketOperationError;
     case QAbstractSocket::UnknownSocketError:
         return QLocalSocket::UnknownSocketError;
     default:
 #if defined QLOCALSOCKET_DEBUG
         qWarning() << "QLocalSocket error not handled:" << d->tcpSocket->error();
 #endif
         break;
     }
     return UnknownSocketError;
 }
error [2/2]
void QLocalSocket::error (QLocalSocket::LocalSocketError socketError) signal
This signal is emitted after an error occurred.
The socketError parameter describes the type of error that occurred.
QLocalSocket::LocalSocketError is not a registered metatype, so for queued connections, you will have to register it with Q_DECLARE_METATYPE() and qRegisterMetaType().
See also
error(), errorString(), {Creating Custom Qt Types}
flush()
bool QLocalSocket::flush ()
This function writes as much as possible from the internal write buffer to the socket, without blocking.
If any data was written, this function returns true; otherwise false is returned.
Call this function if you need QLocalSocket to start sending buffered data immediately. The number of bytes successfully written depends on the operating system. In most cases, you do not need to call this function, because QLocalSocket will start sending data automatically once control goes back to the event loop. In the absence of an event loop, call waitForBytesWritten() instead.
See also
write(), waitForBytesWritten()
Definition at line 347 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed().
 {
     Q_D(QLocalSocket);
     return d->tcpSocket->flush();
 }
fullServerName()
QString QLocalSocket::fullServerName () const
Returns the server path that the socket is connected to.
Note
The return value of this function is platform specific.
See also
connectToServer(), serverName()
Definition at line 429 of file qlocalsocket.cpp.
 {
     Q_D(const QLocalSocket);
     return d->fullServerName;
 }
isSequential()
bool QLocalSocket::isSequential () const virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 448 of file qlocalsocket.cpp.
 {
     return true;
 }
isValid()
bool QLocalSocket::isValid () const
Returns true if the socket is valid and ready for use; otherwise returns false.
Note
The socket's state must be ConnectedState before reading and writing can occur.
See also
state(), connectToServer()
Definition at line 392 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(const QLocalSocket);
     return d->tcpSocket->isValid();
 }
readBufferSize()
qint64 QLocalSocket::readBufferSize () const
Returns the size of the internal read buffer.
This limits the amount of data that the client can receive before you call read() or readAll(). A read buffer size of 0 (the default) means that the buffer has no size limit, ensuring that no data is lost.
See also
setReadBufferSize(), read()
Definition at line 398 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(const QLocalSocket);
     return d->tcpSocket->readBufferSize();
 }
readData()
qint64 QLocalSocket::readData (char * data, qint64 c) protected virtual
Reimplemented Function
Implements QIODevice.
Definition at line 296 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::destroyPipeHandles().
 {
     Q_D(QLocalSocket);
     return d->tcpSocket->readData(data, c);
 }
serverName()
QString QLocalSocket::serverName () const
Returns the name of the peer as specified by connectToServer(), or an empty QString if connectToServer() has not been called or it failed.
See also
connectToServer(), fullServerName()
Definition at line 416 of file qlocalsocket.cpp.
 {
     Q_D(const QLocalSocket);
     return d->serverName;
 }
setReadBufferSize()
void QLocalSocket::setReadBufferSize (qint64 size)
Sets the size of QLocalSocket's internal read buffer to be size bytes.
If the buffer size is limited to a certain size, QLocalSocket won't buffer more than this size of data. Exceptionally, a buffer size of 0 means that the read buffer is unlimited and all incoming data is buffered. This is the default.
This option is useful if you only read the data at certain points in time (e.g., in a real-time streaming application) or if you want to protect your socket against receiving too much data, which may eventually cause your application to run out of memory.
See also
readBufferSize(), read()
Definition at line 404 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(QLocalSocket);
     d->tcpSocket->setReadBufferSize(size);
 }
setSocketDescriptor()
bool QLocalSocket::setSocketDescriptor (quintptr socketDescriptor, LocalSocketState socketState = ConnectedState, OpenMode openMode = ReadWrite)
Definition at line 250 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_pipeClosed(), and QLocalServer::incomingConnection().
 {
     Q_D(QLocalSocket);
     QAbstractSocket::SocketState newSocketState = QAbstractSocket::UnconnectedState;
     switch (socketState) {
     case ConnectingState:
         newSocketState = QAbstractSocket::ConnectingState;
         break;
     case ConnectedState:
         newSocketState = QAbstractSocket::ConnectedState;
         break;
     case ClosingState:
         newSocketState = QAbstractSocket::ClosingState;
         break;
     case UnconnectedState:
         newSocketState = QAbstractSocket::UnconnectedState;
         break;
     }
     QIODevice::open(openMode);
     d->state = socketState;
     // Is our parent a localServer? Then it wants us to use its remote socket.
     QLocalServer* localServer = qobject_cast<QLocalServer*>( parent() );
     if (localServer) {
         foreach (QObject* child, localServer->children()) {
             QTcpSocket* childTcpSocket = qobject_cast<QTcpSocket*>(child);
             if (childTcpSocket && childTcpSocket->socketDescriptor() == socketDescriptor) {
                 d->setSocket( static_cast<QLocalUnixSocket*>(childTcpSocket) );
                 return true;
             }
         }
     }
     // We couldn't find the socket in the children list of our server.
     // So it might be that the user wants to set a socket descriptor.
     return d->tcpSocket->setSocketDescriptor(socketDescriptor,
                                              newSocketState, openMode);
 }
socketDescriptor()
quintptr QLocalSocket::socketDescriptor () const
Returns the native socket descriptor of the QLocalSocket object if this is available; otherwise returns -1.
The socket descriptor is not available when QLocalSocket is in UnconnectedState.
See also
setSocketDescriptor()
Definition at line 290 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(const QLocalSocket);
     return d->tcpSocket->socketDescriptor();
 }
state()
QLocalSocket::LocalSocketState QLocalSocket::state () const
Returns the state of the socket.
See also
error()
Definition at line 440 of file qlocalsocket.cpp.
 {
     Q_D(const QLocalSocket);
     return d->state;
 }
stateChanged
void QLocalSocket::stateChanged (QLocalSocket::LocalSocketState socketState) signal
This signal is emitted whenever QLocalSocket's state changes.
The socketState parameter is the new state.
QLocalSocket::SocketState is not a registered metatype, so for queued connections, you will have to register it with Q_DECLARE_METATYPE() and qRegisterMetaType().
See also
state(), {Creating Custom Qt Types}
waitForBytesWritten()
bool QLocalSocket::waitForBytesWritten (int msecs = 30000) virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 341 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(QLocalSocket);
     return d->tcpSocket->waitForBytesWritten(msecs);
 }
waitForConnected()
bool QLocalSocket::waitForConnected (int msecs = 30000)
Waits until the socket is connected, up to msecs milliseconds.
If the connection has been established, this function returns true; otherwise it returns false. In the case where it returns false, you can call error() to determine the cause of the error.
The following example waits up to one second for a connection to be established:
socket->connectToServer("market");
if (socket->waitForConnected(1000))
    qDebug("Connected!");
If msecs is -1, this function will not time out.
See also
connectToServer(), connected()
Definition at line 410 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(QLocalSocket);
     if (state() != ConnectingState)
         return (state() == ConnectedState);
     return d->tcpSocket->waitForConnected(msec);
 }
waitForDisconnected()
bool QLocalSocket::waitForDisconnected (int msecs = 30000)
Waits until the socket has disconnected, up to msecs milliseconds.
If the connection has been disconnected, this function returns true; otherwise it returns false. In the case where it returns false, you can call error() to determine the cause of the error.
The following example waits up to one second for a connection to be closed:
socket->disconnectFromServer();
if (socket->waitForDisconnected(1000))
    qDebug("Disconnected!");
If msecs is -1, this function will not time out.
See also
disconnectFromServer(), close()
Definition at line 419 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(QLocalSocket);
     if (state() == UnconnectedState) {
         qWarning() << "QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState";
         return false;
     }
     return (d->tcpSocket->waitForDisconnected(msecs));
 }
waitForReadyRead()
bool QLocalSocket::waitForReadyRead (int msecs = 30000) virtual
This function blocks until data is available for reading and the QIODevice::readyRead() signal has been emitted.
The function will timeout after msecs milliseconds; the default timeout is 30000 milliseconds.
The function returns true if data is available for reading; otherwise it returns false (if an error occurred or the operation timed out).
See also
waitForBytesWritten()
Reimplemented from QIODevice.
Definition at line 429 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::_q_emitReadyRead().
 {
     Q_D(QLocalSocket);
     if (state() == QLocalSocket::UnconnectedState)
         return false;
     return (d->tcpSocket->waitForReadyRead(msecs));
 }
writeData()
qint64 QLocalSocket::writeData (const char * data, qint64 c) protected virtual
Reimplemented Function
Implements QIODevice.
Definition at line 302 of file qlocalsocket_tcp.cpp.
Referenced by QLocalSocketPrivate::completeAsyncRead().
 {
     Q_D(QLocalSocket);
     return d->tcpSocket->writeData(data, c);
 }
The documentation for this class was generated from the following files:
/src/network/socket/qlocalsocket.h
/src/network/socket/qlocalsocket.cpp
/src/network/socket/qlocalsocket_tcp.cpp
/src/network/socket/qlocalsocket_unix.cpp
/src/network/socket/qlocalsocket_win.cpp