Qt 4.8: QAbstractTestLogger Class Reference
QAbstractTestLogger Class Reference abstract
#include <qabstracttestlogger_p.h>
Public Types
enum IncidentTypes { Pass, XFail, Fail, XPass }
enum MessageTypes {
Warn, QWarning, QDebug, QSystem,
QFatal, Skip, Info
}
Public Functions
virtual void addBenchmarkResult (const QBenchmarkResult &result)=0
virtual void addIncident (IncidentTypes type, const char *description, const char *file=0, int line=0)=0
virtual void addMessage (MessageTypes type, const char *message, const char *file=0, int line=0)=0
virtual void enterTestFunction (const char *function)=0
virtual void leaveTestFunction ()=0
QAbstractTestLogger ()
virtual void registerRandomSeed (unsigned int seed)=0
virtual void startLogging ()
virtual void stopLogging ()
virtual ~QAbstractTestLogger ()
Static Public Functions
static bool isTtyOutput ()
static void outputString (const char *msg)
Detailed Description
Definition at line 62 of file qabstracttestlogger_p.h.
Enumerations
IncidentTypes
enum QAbstractTestLogger::IncidentTypes
Enumerator
Pass
XFail
Fail
XPass
Definition at line 65 of file qabstracttestlogger_p.h.
{
         Pass,
         XFail,
         Fail,
         XPass
     };
MessageTypes
enum QAbstractTestLogger::MessageTypes
Enumerator
Warn
QWarning
QDebug
QSystem
QFatal
Skip
Info
Definition at line 72 of file qabstracttestlogger_p.h.
                       {
         Warn,
         QWarning,
         QDebug,
         QSystem,
         QFatal,
         Skip,
         Info
     };
Constructors and Destructors
QAbstractTestLogger()
QAbstractTestLogger::QAbstractTestLogger () inline
Definition at line 82 of file qabstracttestlogger_p.h.
 {}
~QAbstractTestLogger()
virtual QAbstractTestLogger::~QAbstractTestLogger () inline virtual
Definition at line 83 of file qabstracttestlogger_p.h.
 {}
Functions
addBenchmarkResult()
virtual void QAbstractTestLogger::addBenchmarkResult (const QBenchmarkResult & result) pure virtual
Implemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Referenced by QTestLog::addBenchmarkResult(), and ~QAbstractTestLogger().
addIncident()
virtual void QAbstractTestLogger::addIncident (IncidentTypes type, const char * description, const char * file = 0, int line = 0) pure virtual
Implemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Referenced by QTestLog::addFail(), QTestLog::addPass(), QTestLog::addXFail(), QTestLog::addXPass(), and ~QAbstractTestLogger().
addMessage()
virtual void QAbstractTestLogger::addMessage (MessageTypes type, const char * message, const char * file = 0, int line = 0) pure virtual
Implemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Referenced by QTestLog::addSkip(), QTestLog::info(), QTest::messageHandler(), QTestLog::printUnhandledIgnoreMessages(), QTestLog::warn(), and ~QAbstractTestLogger().
enterTestFunction()
virtual void QAbstractTestLogger::enterTestFunction (const char * function) pure virtual
Implemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Referenced by QTestLog::enterTestFunction(), and ~QAbstractTestLogger().
isTtyOutput()
bool QAbstractTestLogger::isTtyOutput () static
Definition at line 71 of file qabstracttestlogger.cpp.
Referenced by ~QAbstractTestLogger().
 {
     QTEST_ASSERT(QTest::stream);
 #if defined(Q_OS_WIN) || defined(Q_OS_INTEGRITY)
     return true;
 #else
     static bool ttyoutput = isatty(fileno(QTest::stream));
     return ttyoutput;
 #endif
 }
leaveTestFunction()
virtual void QAbstractTestLogger::leaveTestFunction () pure virtual
Implemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Referenced by QTestLog::leaveTestFunction(), and ~QAbstractTestLogger().
outputString()
void QAbstractTestLogger::outputString (const char * msg) static
Definition at line 63 of file qabstracttestlogger.cpp.
Referenced by QXmlTestLogger::addBenchmarkResult(), QXmlTestLogger::addIncident(), QXmlTestLogger::addMessage(), QXmlTestLogger::enterTestFunction(), QXmlTestLogger::leaveTestFunction(), QTest::outputMessage(), QXmlTestLogger::startLogging(), QXmlTestLogger::stopLogging(), and ~QAbstractTestLogger().
 {
     QTEST_ASSERT(QTest::stream);
     ::fputs(msg, QTest::stream);
     ::fflush(QTest::stream);
 }
registerRandomSeed()
virtual void QAbstractTestLogger::registerRandomSeed (unsigned int seed) pure virtual
Implemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Referenced by QTestLog::startLogging(), and ~QAbstractTestLogger().
startLogging()
void QAbstractTestLogger::startLogging () virtual
Reimplemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Definition at line 84 of file qabstracttestlogger.cpp.
Referenced by QPlainTestLogger::startLogging(), QXmlTestLogger::startLogging(), QTestLog::startLogging(), and ~QAbstractTestLogger().
 {
     QTEST_ASSERT(!QTest::stream);
     const char *out = QTestLog::outputFileName();
     if (!out) {
         QTest::stream = stdout;
         return;
     }
 #if defined(_MSC_VER) && _MSC_VER >= 1400 && !defined(Q_OS_WINCE)
     if (::fopen_s(&QTest::stream, out, "wt")) {
 #else
     QTest::stream = ::fopen(out, "wt");
     if (!QTest::stream) {
 #endif
         printf("Unable to open file for logging: %s", out);
         ::exit(1);
     }
 }
stopLogging()
void QAbstractTestLogger::stopLogging () virtual
Reimplemented in QTestLogger, QXmlTestLogger, and QPlainTestLogger.
Definition at line 104 of file qabstracttestlogger.cpp.
Referenced by QPlainTestLogger::stopLogging(), QXmlTestLogger::stopLogging(), QTestLog::stopLogging(), and ~QAbstractTestLogger().
 {
     QTEST_ASSERT(QTest::stream);
     if (QTest::stream != stdout) {
         fclose(QTest::stream);
     } else {
 #ifdef Q_OS_SYMBIAN
         // Convenience sleep for Symbian and TRK. Without this sleep depending on the timing the
         // user would not see the complete output because it is still pending in any of the buffers
         // before arriving via the USB port on the development PC
         User::AfterHighRes(2*1000*1000);
 #endif
     }
     QTest::stream = 0;
 }
The documentation for this class was generated from the following files:
/src/testlib/qabstracttestlogger_p.h
/src/testlib/qabstracttestlogger.cpp