Qt 4.8: QAbstractAudioInput Class Reference
QAbstractAudioInput Class Reference abstract
The QAbstractAudioInput class provides access for QAudioInput to access the audio device provided by the plugin.
#include <qaudioengine.h>
Signals
void notify ()
This signal is emitted when x ms of audio data has been processed the interval set by setNotifyInterval(x).
void stateChanged (QAudio::State)
This signal is emitted when the device state has changed.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual int bufferSize () const =0
Returns the audio buffer size in milliseconds.
virtual int bytesReady () const =0
Returns the amount of audio data available to read in bytes.
virtual qint64 elapsedUSecs () const =0
Returns the milliseconds since start() was called, including time in Idle and suspend states.
virtual QAudio::Error error () const =0
Returns the error state.
virtual QAudioFormat format () const =0
Returns the QAudioFormat being used.
virtual int notifyInterval () const =0
Returns the notify interval in milliseconds.
virtual int periodSize () const =0
Returns the period size in bytes.
virtual qint64 processedUSecs () const =0
Returns the amount of audio data processed since start() was called in milliseconds.
virtual void reset ()=0
Drops all audio data in the buffers, resets buffers to zero.
virtual void resume ()=0
Resumes processing audio data after a suspend().
virtual void setBufferSize (int value)=0
Sets the audio buffer size to value in milliseconds.
virtual void setNotifyInterval (int milliSeconds)=0
Sets the interval for notify() signal to be emitted.
virtual QIODevice * start (QIODevice *device)=0
Uses the device as the QIODevice to transfer data.
virtual QAudio::State state () const =0
Returns the state of audio processing.
virtual void stop ()=0
Stops the audio input.
virtual void suspend ()=0
Stops processing audio data, preserving buffered audio data.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractAudioInput class provides access for QAudioInput to access the audio device provided by the plugin.
Warning
This function is not part of the public interface.
QAudioDeviceInput keeps an instance of QAbstractAudioInput and routes calls to functions of the same name to QAbstractAudioInput. This means that it is QAbstractAudioInput that implements the audio functionality. For a description of the functionality, see the QAudioInput class description.
See also
QAudioInput
Definition at line 100 of file qaudioengine.h.
Functions
bufferSize()
int QAbstractAudioInput::bufferSize () const pure virtual
Returns the audio buffer size in milliseconds.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::bufferSize().
bytesReady()
int QAbstractAudioInput::bytesReady () const pure virtual
Returns the amount of audio data available to read in bytes.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::bytesReady().
elapsedUSecs()
qint64 QAbstractAudioInput::elapsedUSecs () const pure virtual
Returns the milliseconds since start() was called, including time in Idle and suspend states.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::elapsedUSecs().
error()
QAudio::Error QAbstractAudioInput::error () const pure virtual
Returns the error state.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::error().
format()
QAudioFormat QAbstractAudioInput::format () const pure virtual
Returns the QAudioFormat being used.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::format().
notify
QAbstractAudioInput::notify () signal
This signal is emitted when x ms of audio data has been processed the interval set by setNotifyInterval(x).
Referenced by QAudioInputPrivate::deviceReady(), and QAudioInputPrivate::feedback().
notifyInterval()
int QAbstractAudioInput::notifyInterval () const pure virtual
Returns the notify interval in milliseconds.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::notifyInterval().
periodSize()
int QAbstractAudioInput::periodSize () const pure virtual
Returns the period size in bytes.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::periodSize().
processedUSecs()
qint64 QAbstractAudioInput::processedUSecs () const pure virtual
Returns the amount of audio data processed since start() was called in milliseconds.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::processedUSecs().
reset()
void QAbstractAudioInput::reset () pure virtual
Drops all audio data in the buffers, resets buffers to zero.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::reset().
resume()
void QAbstractAudioInput::resume () pure virtual
Resumes processing audio data after a suspend().
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::resume().
setBufferSize()
void QAbstractAudioInput::setBufferSize (int value) pure virtual
Sets the audio buffer size to value in milliseconds.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::setBufferSize().
setNotifyInterval()
void QAbstractAudioInput::setNotifyInterval (int ms) pure virtual
Sets the interval for notify() signal to be emitted.
This is based on the ms of audio data processed not on actual real-time. The resolution of the timer is platform specific.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::setNotifyInterval().
start()
QIODevice * QAbstractAudioInput::start (QIODevice * device) pure virtual
Uses the device as the QIODevice to transfer data.
If device is null then the class creates an internal QIODevice. Returns a pointer to the QIODevice being used to handle the data transfer. This QIODevice can be used to read() audio data directly. Passing a QIODevice allows the data to be transferred without any extra code.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::start().
state()
QAudio::State QAbstractAudioInput::state () const pure virtual
Returns the state of audio processing.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::state().
stateChanged
QAbstractAudioInput::stateChanged (QAudio::State state) signal
This signal is emitted when the device state has changed.
Referenced by QAudioInputPrivate::deviceReady(), QAudioInputPrivate::freeBlocks(), QAudioInputPrivate::open(), QAudioInputPrivate::read(), QAudioInputPrivate::resume(), QAudioInputPrivate::start(), QAudioInputPrivate::stop(), and QAudioInputPrivate::suspend().
stop()
void QAbstractAudioInput::stop () pure virtual
Stops the audio input.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::stop().
suspend()
void QAbstractAudioInput::suspend () pure virtual
Stops processing audio data, preserving buffered audio data.
Implemented in QAudioInputPrivate, QNullInputDevice, QAudioInputPrivate, and QAudioInputPrivate.
Referenced by QAudioInput::suspend().
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudioengine.h
/src/multimedia/audio/qaudioengine.cpp