Qt 4.8: QTextTableFormat Class Reference
QTextTableFormat Class Reference
The QTextTableFormat class provides formatting information for tables in a QTextDocument.
#include <qtextformat.h>
Public Functions
Qt::Alignment alignment () const
Returns the table's alignment.
qreal cellPadding () const
Returns the table's cell padding.
qreal cellSpacing () const
Returns the table's cell spacing.
void clearColumnWidthConstraints ()
Clears the column width constraints for the table.
int columns () const
Returns the number of columns specified by the table format.
QVector< QTextLength > columnWidthConstraints () const
Returns a list of constraints used by this table format to control the appearance of columns in a table.
int headerRowCount () const
Returns the number of rows in the table that define the header.
bool isValid () const
Returns true if this table format is valid; otherwise returns false.
QTextTableFormat ()
Constructs a new table format object.
void setAlignment (Qt::Alignment alignment)
Sets the table's alignment.
void setCellPadding (qreal padding)
Sets the cell padding for the table.
void setCellSpacing (qreal spacing)
Sets the cell spacing for the table.
void setColumns (int columns)
Sets the number of columns required by the table format.
void setColumnWidthConstraints (const QVector< QTextLength > &constraints)
Sets the column width constraints for the table.
void setHeaderRowCount (int count)
Declares the first count rows of the table as table header.
Public Functions inherited from QTextFrameFormat
qreal border () const
Returns the width of the border in pixels.
QBrush borderBrush () const
Returns the brush used for the frame's border.
BorderStyle borderStyle () const
Returns the style of the frame's border.
qreal bottomMargin () const
Returns the width of the frame's bottom margin in pixels.
QTextLength height () const
Returns the height of the frame's border rectangle.
bool isValid () const
Returns true if the format description is valid; otherwise returns false.
qreal leftMargin () const
Returns the width of the frame's left margin in pixels.
qreal margin () const
Returns the width of the frame's external margin in pixels.
qreal padding () const
Returns the width of the frame's internal padding in pixels.
PageBreakFlags pageBreakPolicy () const
Returns the currently set page break policy for the frame/table.
Position position () const
Returns the positioning policy for frames with this frame format.
QTextFrameFormat ()
Constructs a text frame format object with the default properties.
qreal rightMargin () const
Returns the width of the frame's right margin in pixels.
void setBorder (qreal border)
Sets the width (in pixels) of the frame's border.
void setBorderBrush (const QBrush &brush)
Sets the brush used for the frame's border.
void setBorderStyle (BorderStyle style)
Sets the style of the frame's border.
void setBottomMargin (qreal margin)
Sets the frame's bottom margin in pixels.
void setHeight (qreal height)
Sets the frame's height.
void setHeight (const QTextLength &height)
Sets the frame's height.
void setLeftMargin (qreal margin)
Sets the frame's left margin in pixels.
void setMargin (qreal margin)
Sets the frame's margin in pixels.
void setPadding (qreal padding)
Sets the width of the frame's internal padding in pixels.
void setPageBreakPolicy (PageBreakFlags flags)
Sets the page break policy for the frame/table to policy.
void setPosition (Position f)
Sets the policy for positioning frames with this frame format.
void setRightMargin (qreal margin)
Sets the frame's right margin in pixels.
void setTopMargin (qreal margin)
Sets the frame's top margin in pixels.
void setWidth (qreal width)
Convenience method that sets the width of the frame's border rectangle's width to the specified fixed width.
void setWidth (const QTextLength &length)
Sets the frame's border rectangle's width.
qreal topMargin () const
Returns the width of the frame's top margin in pixels.
QTextLength width () const
Returns the width of the frame's border rectangle.
Public Functions inherited from QTextFormat
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Protected Functions
QTextTableFormat (const QTextFormat &fmt)
Creates a new table format with the same attributes as the given text format.
Protected Functions inherited from QTextFrameFormat
QTextFrameFormat (const QTextFormat &fmt)
Creates a new frame format with the same attributes as the given text format.
Friends
class QTextFormat
Additional Inherited Members
Public Types inherited from QTextFrameFormat
enum BorderStyle {
BorderStyle_None, BorderStyle_Dotted, BorderStyle_Dashed, BorderStyle_Solid,
BorderStyle_Double, BorderStyle_DotDash, BorderStyle_DotDotDash, BorderStyle_Groove,
BorderStyle_Ridge, BorderStyle_Inset, BorderStyle_Outset
}
This enum describes different border styles for the text frame.
enum Position { InFlow, FloatLeft, FloatRight }
This enum describes how a frame is located relative to the surrounding text.
Public Types inherited from QTextFormat
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Detailed Description
The QTextTableFormat class provides formatting information for tables in a QTextDocument.
Note
This class or function is reentrant.
A table is a group of cells ordered into rows and columns. Each table contains at least one row and one column. Each cell contains a block. Tables in rich text documents are formatted using the properties defined in this class.
Tables are horizontally justified within their parent frame according to the table's alignment. This can be read with the alignment() function and set with setAlignment().
Cells within the table are separated by cell spacing. The number of pixels between cells is set with setCellSpacing() and read with cellSpacing(). The contents of each cell is surrounded by cell padding. The number of pixels between each cell edge and its contents is set with setCellPadding() and read with cellPadding().
The table's background color can be read with the background() function, and can be specified with setBackground(). The background color of each cell can be set independently, and will control the color of the cell within the padded area.
The table format also provides a way to constrain the widths of the columns in the table. Columns can be assigned a fixed width, a variable width, or a percentage of the available width (see QTextLength). The columns() function returns the number of columns with constraints, and the columnWidthConstraints() function returns the constraints defined for the table. These quantities can also be set by calling setColumnWidthConstraints() with a vector containing new constraints. If no constraints are required, clearColumnWidthConstraints() can be used to remove them.
See also
QTextTable QTextTableCell QTextLength
Definition at line 842 of file qtextformat.h.
Constructors and Destructors
QTextTableFormat() [1/2]
QTextTableFormat::QTextTableFormat ()
Constructs a new table format object.
Definition at line 3262 of file qtextformat.cpp.
  : QTextFrameFormat()
 {
     setObjectType(TableObject);
     setCellSpacing(2);
     setBorder(1);
 }
QTextTableFormat() [2/2]
QTextTableFormat::QTextTableFormat (const QTextFormat & other) explicit protected
Creates a new table format with the same attributes as the given text format.
Warning
This function is not part of the public interface.
Definition at line 3280 of file qtextformat.cpp.
  : QTextFrameFormat(fmt)
 {
 }
Functions
alignment()
Qt::Alignment QTextTableFormat::alignment () const inline
Returns the table's alignment.
See also
setAlignment()
Definition at line 872 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTable(), and QTextDocumentLayoutPrivate::layoutFlow().
     { return QFlag(intProperty(BlockAlignment)); }
cellPadding()
qreal QTextTableFormat::cellPadding () const inline
Returns the table's cell padding.
This describes the distance between the border of a cell and its contents.
Definition at line 867 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTable(), and QTextDocumentLayoutPrivate::layoutTable().
     { return doubleProperty(TableCellPadding); }
cellSpacing()
qreal QTextTableFormat::cellSpacing () const inline
Returns the table's cell spacing.
This describes the distance between adjacent cells.
Definition at line 862 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTable(), and QTextDocumentLayoutPrivate::layoutTable().
     { return doubleProperty(TableCellSpacing); }
clearColumnWidthConstraints()
void QTextTableFormat::clearColumnWidthConstraints () inline
Clears the column width constraints for the table.
See also
columnWidthConstraints() setColumnWidthConstraints()
Definition at line 859 of file qtextformat.h.
Referenced by QTextCopyHelper::copy().
     { clearProperty(TableColumnWidthConstraints); }
columns()
int QTextTableFormat::columns () const inline
Returns the number of columns specified by the table format.
Definition at line 849 of file qtextformat.h.
Referenced by QTextTable::insertColumns(), and QTextTable::removeColumns().
     { int cols = intProperty(TableColumns); if (cols == 0) cols = 1; return cols; }
columnWidthConstraints()
QVector< QTextLength > QTextTableFormat::columnWidthConstraints () const inline
Returns a list of constraints used by this table format to control the appearance of columns in a table.
See also
setColumnWidthConstraints()
Definition at line 856 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTable(), QTextTable::insertColumns(), QTextDocumentLayoutPrivate::layoutTable(), and QTextTable::removeColumns().
     { return lengthVectorProperty(TableColumnWidthConstraints); }
headerRowCount()
int QTextTableFormat::headerRowCount () const inline
Returns the number of rows in the table that define the header.
Since
4.2
See also
setHeaderRowCount()
Definition at line 877 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), and QTextDocumentLayoutPrivate::layoutTable().
     { return intProperty(TableHeaderRowCount); }
isValid()
bool QTextTableFormat::isValid () const inline
Returns true if this table format is valid; otherwise returns false.
Definition at line 847 of file qtextformat.h.
 { return isTableFormat(); }
setAlignment()
void QTextTableFormat::setAlignment (Qt::Alignment alignment) inline
Sets the table's alignment.
See also
alignment()
Definition at line 895 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(BlockAlignment, int(aalignment)); }
setCellPadding()
void QTextTableFormat::setCellPadding (qreal padding) inline
Sets the cell padding for the table.
This determines the distance between the border of a cell and its contents.
Definition at line 892 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(TableCellPadding, apadding); }
setCellSpacing()
void QTextTableFormat::setCellSpacing (qreal spacing) inline
Sets the cell spacing for the table.
This determines the distance between adjacent cells.
Definition at line 864 of file qtextformat.h.
Referenced by QTextTableFormat(), and QTextHtmlImporter::scanTable().
     { setProperty(TableCellSpacing, spacing); }
setColumns()
void QTextTableFormat::setColumns (int columns) inline
Sets the number of columns required by the table format.
Warning
This function is not part of the public interface.
See also
columns()
Definition at line 885 of file qtextformat.h.
Referenced by QTextCopyHelper::copy(), QTextTablePrivate::createTable(), QTextTable::insertColumns(), QTextTable::removeColumns(), QTextHtmlImporter::scanTable(), and QTextTable::setFormat().
 {
     if (acolumns == 1)
         acolumns = 0;
     setProperty(TableColumns, acolumns);
 }
setColumnWidthConstraints()
void QTextTableFormat::setColumnWidthConstraints (const QVector< QTextLength > & constraints) inline
Sets the column width constraints for the table.
See also
columnWidthConstraints() clearColumnWidthConstraints()
Definition at line 853 of file qtextformat.h.
Referenced by QTextTable::insertColumns(), QTextTable::removeColumns(), and QTextHtmlImporter::scanTable().
     { setProperty(TableColumnWidthConstraints, constraints); }
setHeaderRowCount()
void QTextTableFormat::setHeaderRowCount (int count) inline
Declares the first count rows of the table as table header.
Since
4.2
The table header rows get repeated when a table is broken across a page boundary.
Definition at line 875 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
     { setProperty(TableHeaderRowCount, count); }
Friends and Related Functions
QTextFormat
friend class QTextFormat friend
Definition at line 882 of file qtextformat.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp