Qt 4.8: QWSDirectPainterSurface Class Reference
QWSDirectPainterSurface Class Reference
#include <qwindowsurface_qws_p.h>
Public Functions
void beginPaint (const QRegion &)
This function is called before painting onto the surface begins, with the region in which the painting will occur.
void flush (QWidget *, const QRegion &, const QPoint &)
Flushes the given region from the specified widget onto the screen.
bool hasPendingRegionEvents () const
QImage image () const
Implement this function to return an image of the top-level window.
bool isValid () const
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
QString key () const
Implement this function to return a string that uniquely identifies the class of this surface.
bool lock (int timeout=-1)
QPaintDevice * paintDevice ()
Implement this function to return the appropriate paint device.
QByteArray permanentState () const
Implement this function to return the data required for creating a server-side representation of the surface.
QWSDirectPainterSurface (bool isClient=false, QDirectPainter::SurfaceFlag flags=QDirectPainter::NonReserved)
QRegion region () const
QScreen * screen () const
void setGeometry (const QRect &rect)
Sets the currently allocated area to be the given rect.
void setLocking (bool b)
void setPermanentState (const QByteArray &)
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
void setRegion (const QRegion &region)
void setReserved ()
void unlock ()
WId windowId () const
~QWSDirectPainterSurface ()
Public Functions inherited from QWSWindowSurface
const QRegion clipRegion () const
Returns the region currently visible on the screen.
virtual void endPaint (const QRegion &)
This function is called after painting onto the surface has ended, with the region in which the painting was performed.
bool isBuffered () const
Returns true if the QWSWindowSurface::Buffered is set; otherwise returns false.
bool isOpaque () const
Returns true if the QWSWindowSurface::Opaque is set; otherwise returns false.
bool isRegionReserved () const
Returns true if the QWSWindowSurface::RegionReserved is set; otherwise returns false.
virtual bool move (const QPoint &offset)
Move the surface with the given offset.
virtual QRegion move (const QPoint &offset, const QRegion &newClip)
Move the surface with the given offset.
virtual QPoint painterOffset () const
Returns the offset to be used when painting.
QWSWindowSurface ()
Constructs an empty surface.
QWSWindowSurface (QWidget *widget)
Constructs an empty surface for the given top-level widget.
virtual void releaseSurface ()
void setClipRegion (const QRegion &)
Sets the region currently visible on the screen to be the given clip region.
virtual void setGeometry (const QRect &rect, const QRegion &mask)
virtual void setTransientState (const QByteArray &state)
SurfaceFlags surfaceFlags () const
Returns the surface flags describing the contents of this surface.
virtual QByteArray transientState () const
int winId () const
~QWSWindowSurface ()
Public Functions inherited from QWindowSurface
virtual QImage * buffer (const QWidget *widget)
Returns a QImage pointer which represents the actual buffer the widget is drawn into or 0 if this is unavailable.
virtual WindowSurfaceFeatures features () const
QRect geometry () const
Returns the currently allocated area on the screen.
virtual QPixmap grabWidget (const QWidget *widget, const QRect &rectangle=QRect()) const
Returns a QPixmap generated from the part of the backing store corresponding to widget.
bool hasFeature (WindowSurfaceFeature feature) const
virtual QPoint offset (const QWidget *widget) const
Returns the offset of widget in the coordinates of this window surface.
QWindowSurface (QWidget *window, bool setDefaultSurface=true)
Constructs an empty surface for the given top-level window.
QRect rect (const QWidget *widget) const
Returns the rectangle for widget in the coordinates of this window surface.
virtual bool scroll (const QRegion &area, int dx, int dy)
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
void setStaticContents (const QRegion &region)
QRegion staticContents () const
QWidget * window () const
Returns a pointer to the top-level window associated with this surface.
virtual ~QWindowSurface ()
Destroys this surface.
Properties
QScreen * _screen
bool doLocking
bool flushingRegionEvents
bool synchronous
QMutex threadLock
Friends
void qt_directpainter_region (QDirectPainter *, const QRegion &, int)
Additional Inherited Members
Public Types inherited from QWSWindowSurface
enum SurfaceFlag { RegionReserved = 0x1, Buffered = 0x2, Opaque = 0x4 }
This enum is used to describe the window surface's contents.
Public Types inherited from QWindowSurface
enum WindowSurfaceFeature { PartialUpdates = 0x00000001, PreservedContents = 0x00000002, StaticContents = 0x00000004, AllFeatures = 0xffffffff }
Protected Functions inherited from QWSWindowSurface
void setSurfaceFlags (SurfaceFlags type)
Sets the surface flags describing the contents of this surface, to be the given flags.
void setWinId (int id)
Protected Functions inherited from QWindowSurface
bool hasStaticContents () const
Detailed Description
Definition at line 300 of file qwindowsurface_qws_p.h.
Constructors and Destructors
QWSDirectPainterSurface()
QWSDirectPainterSurface::QWSDirectPainterSurface (bool isClient = false, QDirectPainter::SurfaceFlag flags = QDirectPainter::NonReserved)
Definition at line 1368 of file qwindowsurface_qws.cpp.
     : QWSWindowSurface(), flushingRegionEvents(false), doLocking(false)
 {
     setSurfaceFlags(Opaque);
     synchronous = (flags == QDirectPainter::ReservedSynchronous);
     if (isClient) {
         setWinId(QWidget::qwsDisplay()->takeId());
         QWidget::qwsDisplay()->nameRegion(winId(),
                                           QLatin1String("QDirectPainter reserved space"),
                                           QLatin1String("reserved"));
     } else {
         setWinId(0);
     }
     _screen = QScreen::instance();
     if (!_screen->base()) {
         QList<QScreen*> subScreens = _screen->subScreens();
         if (subScreens.size() < 1)
             _screen = 0;
         else
             _screen = subScreens.at(0);
     }
 }
~QWSDirectPainterSurface()
QWSDirectPainterSurface::~QWSDirectPainterSurface ()
Definition at line 1393 of file qwindowsurface_qws.cpp.
 {
     if (winId() && QWSDisplay::instance()) // make sure not in QApplication destructor
         QWidget::qwsDisplay()->destroyRegion(winId());
 }
Functions
beginPaint()
void QWSDirectPainterSurface::beginPaint (const QRegion & region) virtual
This function is called before painting onto the surface begins, with the region in which the painting will occur.
See also
endPaint(), paintDevice()
Reimplemented from QWSWindowSurface.
Definition at line 1429 of file qwindowsurface_qws.cpp.
 {
     QWSWindowSurface::beginPaint(region);
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (!synchronous) {
         flushingRegionEvents = true;
         QWSDisplay::instance()->d->waitForRegionEvents(winId(), doLocking);
         flushingRegionEvents = false;
     }
 #endif
 }
flush()
void QWSDirectPainterSurface::flush (QWidget * widget, const QRegion & region, const QPoint & offset) virtual
Flushes the given region from the specified widget onto the screen.
Note that the offset parameter is currently unused.
Reimplemented from QWSWindowSurface.
Definition at line 1409 of file qwindowsurface_qws.cpp.
 {
     QWSDisplay::instance()->repaintRegion(winId(), 0, true, r);
 }
hasPendingRegionEvents()
bool QWSDirectPainterSurface::hasPendingRegionEvents () const
Definition at line 1441 of file qwindowsurface_qws.cpp.
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (synchronous)
         return false;
     return QWSDisplay::instance()->d->hasPendingRegionEvents();
 #else
     return false;
 #endif
 }
image()
QImage QWSDirectPainterSurface::image () const inline virtual
Implement this function to return an image of the top-level window.
See also
geometry()
Implements QWSWindowSurface.
Definition at line 323 of file qwindowsurface_qws_p.h.
 { return QImage(); }
isValid()
bool QWSDirectPainterSurface::isValid () const inline virtual
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
Since
4.3
See also
window(), key()
Implements QWSWindowSurface.
Definition at line 316 of file qwindowsurface_qws_p.h.
 { return false; }
key()
QString QWSDirectPainterSurface::key () const inline virtual
Implement this function to return a string that uniquely identifies the class of this surface.
See also
window(), isValid()
Implements QWSWindowSurface.
Definition at line 318 of file qwindowsurface_qws_p.h.
Referenced by setRegion().
 { return QLatin1String("DirectPainter"); }
lock()
bool QWSDirectPainterSurface::lock (int timeout = -1) virtual
Reimplemented from QWSWindowSurface.
Definition at line 1453 of file qwindowsurface_qws.cpp.
 {
 #ifndef QT_NO_THREAD
     threadLock.lock();
 #endif
     Q_UNUSED(timeout);
     if (doLocking)
         QWSDisplay::grab(true);
     return true;
 }
paintDevice()
QPaintDevice* QWSDirectPainterSurface::paintDevice () inline virtual
Implement this function to return the appropriate paint device.
Implements QWSWindowSurface.
Definition at line 324 of file qwindowsurface_qws_p.h.
 { return 0; }
permanentState()
QByteArray QWSDirectPainterSurface::permanentState () const virtual
Implement this function to return the data required for creating a server-side representation of the surface.
Since
4.3
See also
attach()
Reimplemented from QWSWindowSurface.
Definition at line 1414 of file qwindowsurface_qws.cpp.
Referenced by setRegion().
 {
     QByteArray res;
     if (isRegionReserved())
         res.append( 'r');
     return res;
 }
region()
QRegion QWSDirectPainterSurface::region () const inline
Definition at line 312 of file qwindowsurface_qws_p.h.
 { return clipRegion(); }
screen()
QScreen* QWSDirectPainterSurface::screen () const inline
Definition at line 329 of file qwindowsurface_qws_p.h.
Referenced by qt_directpainter_region().
 { return _screen; }
setGeometry()
void QWSDirectPainterSurface::setGeometry (const QRect & rect) inline virtual
Sets the currently allocated area to be the given rect.
This function is called whenever area covered by the top-level window changes.
See also
geometry()
Reimplemented from QWSWindowSurface.
Definition at line 309 of file qwindowsurface_qws_p.h.
Referenced by QDirectPainterPrivate::~QDirectPainterPrivate().
 { setRegion(rect); }
setLocking()
void QWSDirectPainterSurface::setLocking (bool b) inline
Definition at line 335 of file qwindowsurface_qws_p.h.
 { doLocking = b; }
setPermanentState()
void QWSDirectPainterSurface::setPermanentState (const QByteArray & data) virtual
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
Since
4.3
Return true if successful; otherwise return false.
See also
data()
Reimplemented from QWSWindowSurface.
Definition at line 1422 of file qwindowsurface_qws.cpp.
 {
     if (ba.size() > 0 && ba.at(0) == 'r')
         setReserved();
     setSurfaceFlags(surfaceFlags() | Opaque);
 }
setRegion()
void QWSDirectPainterSurface::setRegion (const QRegion & region)
Definition at line 1399 of file qwindowsurface_qws.cpp.
 {
     const int id = winId();
     QWidget::qwsDisplay()->requestRegion(id, key(), permanentState(), region);
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (synchronous)
         QWSDisplay::instance()->d->waitForRegionAck(id);
 #endif
 }
setReserved()
void QWSDirectPainterSurface::setReserved () inline
Definition at line 307 of file qwindowsurface_qws_p.h.
Referenced by setPermanentState().
 { setSurfaceFlags(RegionReserved); }
unlock()
void QWSDirectPainterSurface::unlock () virtual
Reimplemented from QWSWindowSurface.
Definition at line 1464 of file qwindowsurface_qws.cpp.
 {
     if (doLocking)
         QWSDisplay::ungrab();
 #ifndef QT_NO_THREAD
     threadLock.unlock();
 #endif
 }
windowId()
WId QWSDirectPainterSurface::windowId () const inline
Definition at line 327 of file qwindowsurface_qws_p.h.
Referenced by QDirectPainterPrivate::~QDirectPainterPrivate().
 { return static_cast<WId>(winId()); }
Friends and Related Functions
qt_directpainter_region
void qt_directpainter_region (QDirectPainter * , const QRegion & , int) friend
Definition at line 223 of file qdirectpainter_qws.cpp.
 {
     QDirectPainterPrivate *d = dp->d_func();
     QRegion r = alloc;
     QScreen *screen = d->surface->screen();
     if (screen->isTransformed()) {
         const QSize screenSize(screen->width(), screen->height());
         r = screen->mapToDevice(r, screenSize);
     }
     if (type == QWSRegionEvent::Allocation) {
         d->surface->setClipRegion(alloc);
         d->seenRegion = true;
         if (dp != QDirectPainterPrivate::staticPainter) {
             if (!d->surface->flushingRegionEvents) // recursion guard
                 dp->regionChanged(r);
         }
     }
 }
Properties
_screen
QScreen* QWSDirectPainterSurface::_screen private
Definition at line 340 of file qwindowsurface_qws_p.h.
Referenced by QWSDirectPainterSurface().
doLocking
bool QWSDirectPainterSurface::doLocking private
Definition at line 348 of file qwindowsurface_qws_p.h.
Referenced by beginPaint(), lock(), and unlock().
flushingRegionEvents
bool QWSDirectPainterSurface::flushingRegionEvents private
Definition at line 346 of file qwindowsurface_qws_p.h.
Referenced by beginPaint(), and qt_directpainter_region().
synchronous
bool QWSDirectPainterSurface::synchronous private
Definition at line 347 of file qwindowsurface_qws_p.h.
Referenced by beginPaint(), hasPendingRegionEvents(), QWSDirectPainterSurface(), and setRegion().
threadLock
QMutex QWSDirectPainterSurface::threadLock private
Definition at line 342 of file qwindowsurface_qws_p.h.
Referenced by lock(), and unlock().
The documentation for this class was generated from the following files:
/src/gui/painting/qwindowsurface_qws_p.h
/src/gui/painting/qwindowsurface_qws.cpp