Qt 4.8: QTextImageFormat Class Reference
QTextImageFormat Class Reference
The QTextImageFormat class provides formatting information for images in a QTextDocument.
#include <qtextformat.h>
Public Functions
qreal height () const
Returns the height of the rectangle occupied by the image.
bool isValid () const
Returns true if this image format is valid; otherwise returns false.
QString name () const
Returns the name of the image.
QTextImageFormat ()
Creates a new image format object.
void setHeight (qreal height)
Sets the height of the rectangle occupied by the image.
void setName (const QString &name)
Sets the name of the image.
void setWidth (qreal width)
Sets the width of the rectangle occupied by the image.
qreal width () const
Returns the width of the rectangle occupied by the image.
Public Functions inherited from QTextCharFormat
QString anchorHref () const
Returns the text format's hypertext link, or an empty string if none has been set.
QString anchorName () const
This function is deprecated.
QStringList anchorNames () const
Returns the anchor names associated with this text format, or an empty string list if none has been set.
QFont font () const
Returns the font for this character format.
QFont::Capitalization fontCapitalization () const
Returns the current capitalization type of the font.
QString fontFamily () const
Returns the text format's font family.
bool fontFixedPitch () const
Returns true if the text format's font is fixed pitch; otherwise returns false.
QFont::HintingPreference fontHintingPreference () const
Returns the hinting preference set for this text format.
bool fontItalic () const
Returns true if the text format's font is italic; otherwise returns false.
bool fontKerning () const
Returns true if the font kerning is enabled.
qreal fontLetterSpacing () const
Returns the current letter spacing percentage.
bool fontOverline () const
Returns true if the text format's font is overlined; otherwise returns false.
qreal fontPointSize () const
Returns the font size used to display text in this format.
bool fontStrikeOut () const
Returns true if the text format's font is struck out (has a horizontal line drawn through it); otherwise returns false.
QFont::StyleHint fontStyleHint () const
Returns the font style hint.
QFont::StyleStrategy fontStyleStrategy () const
Returns the current font style strategy.
bool fontUnderline () const
Returns true if the text format's font is underlined; otherwise returns false.
int fontWeight () const
Returns the text format's font weight.
qreal fontWordSpacing () const
Returns the current word spacing value.
bool isAnchor () const
Returns true if the text is formatted as an anchor; otherwise returns false.
bool isValid () const
Returns true if this character format is valid; otherwise returns false.
QTextCharFormat ()
Constructs a new character format object.
void setAnchor (bool anchor)
If anchor is true, text with this format represents an anchor, and is formatted in the appropriate way; otherwise the text is formatted normally.
void setAnchorHref (const QString &value)
Sets the hypertext link for the text format to the given value.
void setAnchorName (const QString &name)
This function is deprecated.
void setAnchorNames (const QStringList &names)
Sets the text format's anchor names.
void setFont (const QFont &font)
Sets the text format's font.
void setFontCapitalization (QFont::Capitalization capitalization)
Sets the capitalization of the text that apppears in this font to capitalization.
void setFontFamily (const QString &family)
Sets the text format's font family.
void setFontFixedPitch (bool fixedPitch)
If fixedPitch is true, sets the text format's font to be fixed pitch; otherwise a non-fixed pitch font is used.
void setFontHintingPreference (QFont::HintingPreference hintingPreference)
Sets the hinting preference of the text format's font to be hintingPreference.
void setFontItalic (bool italic)
If italic is true, sets the text format's font to be italic; otherwise the font will be non-italic.
void setFontKerning (bool enable)
Enables kerning for this font if enable is true; otherwise disables it.
void setFontLetterSpacing (qreal spacing)
Sets the letter spacing of this format to the given spacing, in percent.
void setFontOverline (bool overline)
If overline is true, sets the text format's font to be overlined; otherwise the font is displayed non-overlined.
void setFontPointSize (qreal size)
Sets the text format's font size.
void setFontStrikeOut (bool strikeOut)
If strikeOut is true, sets the text format's font with strike-out enabled (with a horizontal line through it); otherwise it is displayed without strikeout.
void setFontStyleHint (QFont::StyleHint hint, QFont::StyleStrategy strategy=QFont::PreferDefault)
Sets the font style hint and strategy.
void setFontStyleStrategy (QFont::StyleStrategy strategy)
Sets the font style strategy.
void setFontUnderline (bool underline)
If underline is true, sets the text format's font to be underlined; otherwise it is displayed non-underlined.
void setFontWeight (int weight)
Sets the text format's font weight to weight.
void setFontWordSpacing (qreal spacing)
Sets the word spacing of this format to the given spacing, in pixels.
void setTableCellColumnSpan (int tableCellColumnSpan)
If this character format is applied to characters in a table cell, the cell will span tableCellColumnSpan columns.
void setTableCellRowSpan (int tableCellRowSpan)
If this character format is applied to characters in a table cell, the cell will span tableCellRowSpan rows.
void setTextOutline (const QPen &pen)
Sets the pen used to draw the outlines of characters to the given pen.
void setToolTip (const QString &tip)
Sets the tool tip for a fragment of text to the given text.
void setUnderlineColor (const QColor &color)
Sets the underline color used for the characters with this format to the color specified.
void setUnderlineStyle (UnderlineStyle style)
Sets the style of underlining the text to style.
void setVerticalAlignment (VerticalAlignment alignment)
Sets the vertical alignment used for the characters with this format to the alignment specified.
int tableCellColumnSpan () const
If this character format is applied to characters in a table cell, this function returns the number of columns spanned by the text (this may be 1); otherwise it returns 1.
int tableCellRowSpan () const
If this character format is applied to characters in a table cell, this function returns the number of rows spanned by the text (this may be 1); otherwise it returns 1.
QPen textOutline () const
Returns the pen used to draw the outlines of characters in this format.
QString toolTip () const
Returns the tool tip that is displayed for a fragment of text.
QColor underlineColor () const
Returns the color used to underline the characters with this format.
UnderlineStyle underlineStyle () const
Returns the style of underlining the text.
VerticalAlignment verticalAlignment () const
Returns the vertical alignment used for characters with this format.
Public Functions inherited from QTextFormat
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Protected Functions
QTextImageFormat (const QTextFormat &format)
Creates a new image format with the same attributes as the given text format.
Protected Functions inherited from QTextCharFormat
QTextCharFormat (const QTextFormat &fmt)
Creates a new character format with the same attributes as the given text format.
Friends
class QTextFormat
Additional Inherited Members
Public Types inherited from QTextCharFormat
enum UnderlineStyle {
NoUnderline, SingleUnderline, DashUnderline, DotLine,
DashDotLine, DashDotDotLine, WaveUnderline, SpellCheckUnderline
}
This enum describes the different ways drawing underlined text.
enum VerticalAlignment {
AlignNormal = 0, AlignSuperScript, AlignSubScript, AlignMiddle,
AlignTop, AlignBottom, AlignBaseline
}
This enum describes the ways that adjacent characters can be vertically aligned.
Public Types inherited from QTextFormat
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Detailed Description
The QTextImageFormat class provides formatting information for images in a QTextDocument.
Note
This class or function is reentrant.
Inline images are represented by an object replacement character (0xFFFC in Unicode) which has an associated QTextImageFormat. The image format specifies a name with setName() that is used to locate the image. The size of the rectangle that the image will occupy is specified using setWidth() and setHeight().
Images can be supplied in any format for which Qt has an image reader, so SVG drawings can be included alongside PNG, TIFF and other bitmap formats.
See also
QImage, QImageReader
Definition at line 694 of file qtextformat.h.
Constructors and Destructors
QTextImageFormat() [1/2]
QTextImageFormat::QTextImageFormat ()
Creates a new image format object.
Definition at line 3507 of file qtextformat.cpp.
 : QTextCharFormat() { setObjectType(ImageObject); }
QTextImageFormat() [2/2]
QTextImageFormat::QTextImageFormat (const QTextFormat & other) explicit protected
Creates a new image format with the same attributes as the given text format.
Warning
This function is not part of the public interface.
Definition at line 3519 of file qtextformat.cpp.
  : QTextCharFormat(fmt)
 {
 }
Functions
height()
qreal QTextImageFormat::height () const inline
Returns the height of the rectangle occupied by the image.
See also
width() setHeight()
Definition at line 710 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitFragment(), getImageSize(), getPixmapSize(), and QTextOdfWriter::writeInlineCharacter().
     { return doubleProperty(ImageHeight); }
isValid()
bool QTextImageFormat::isValid () const inline
Returns true if this image format is valid; otherwise returns false.
Definition at line 699 of file qtextformat.h.
 { return isImageFormat(); }
name()
QString QTextImageFormat::name () const inline
Returns the name of the image.
The name refers to an entry in the application's resources file.
See also
setName()
Definition at line 702 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitFragment(), getImage(), getPixmap(), and QTextOdfWriter::writeInlineCharacter().
     { return stringProperty(ImageName); }
setHeight()
void QTextImageFormat::setHeight (qreal height) inline
Sets the height of the rectangle occupied by the image.
See also
height() setWidth()
Definition at line 724 of file qtextformat.h.
Referenced by QTextHtmlImporter::processSpecialNodes().
 { setProperty(ImageHeight, aheight); }
setName()
void QTextImageFormat::setName (const QString & name) inline
Sets the name of the image.
The name is used to locate the image in the application's resources.
See also
name()
Definition at line 718 of file qtextformat.h.
Referenced by QTextCursor::insertImage(), and QTextHtmlImporter::processSpecialNodes().
 { setProperty(ImageName, aname); }
setWidth()
void QTextImageFormat::setWidth (qreal width) inline
Sets the width of the rectangle occupied by the image.
See also
width() setHeight()
Definition at line 721 of file qtextformat.h.
Referenced by QTextHtmlImporter::processSpecialNodes().
 { setProperty(ImageWidth, awidth); }
width()
qreal QTextImageFormat::width () const inline
Returns the width of the rectangle occupied by the image.
See also
height() setWidth()
Definition at line 706 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitFragment(), getImageSize(), getPixmapSize(), and QTextOdfWriter::writeInlineCharacter().
     { return doubleProperty(ImageWidth); }
Friends and Related Functions
QTextFormat
friend class QTextFormat friend
Definition at line 715 of file qtextformat.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp