Qt 4.8: QScopedSharedPointer< T > Class Template Reference
QScopedSharedPointer< T > Class Template Reference
#include <qscopedpointer_p.h>
Public Functions
void assign (T *other)
void detach ()
bool operator!= (const QScopedSharedPointer< T > &other) const
bool operator== (const QScopedSharedPointer< T > &other) const
QScopedSharedPointer (T *p=0)
Public Functions inherited from QCustomScopedPointer< T, QScopedPointerSharedDeleter< T > >
T *& data_ptr ()
bool operator!= (const QCustomScopedPointer< T, QScopedPointerSharedDeleter< T > > &other) const
bool operator== (const QCustomScopedPointer< T, QScopedPointerSharedDeleter< T > > &other) const
QCustomScopedPointer (T *p=0)
Public Functions inherited from QScopedPointer< T, QScopedPointerSharedDeleter< T > >
T * data () const
Returns the value of the pointer referenced by this object.
bool isNull () const
Returns true if this object is holding a pointer that is null.
operator bool () const
Returns true if this object is not null.
bool operator! () const
Returns true if the pointer referenced by this object is null, otherwise returns false.
T & operator* () const
Provides access to the scoped pointer's object.
T * operator-> () const
Provides access to the scoped pointer's object.
QScopedPointer (T *p=0)
Constructs this QScopedPointer instance and sets its pointer to p.
void reset (T *other=0)
Deletes the existing object it is pointing to if any, and sets its pointer to other.
void swap (QScopedPointer< T, QScopedPointerSharedDeleter< T > > &other)
Swap this pointer with other.
T * take ()
Returns the value of the pointer referenced by this object.
~QScopedPointer ()
Destroys this QScopedPointer object.
Additional Inherited Members
Public Types inherited from QScopedPointer< T, QScopedPointerSharedDeleter< T > >
typedef T * pointer
Protected Variables inherited from QScopedPointer< T, QScopedPointerSharedDeleter< T > >
T * d
Detailed Description
template<typename T>
class QScopedSharedPointer< T >
Definition at line 109 of file qscopedpointer_p.h.
Constructors and Destructors
QScopedSharedPointer()
template<typename T> QScopedSharedPointer< T >::QScopedSharedPointer (T * p = 0) inline explicit
Definition at line 112 of file qscopedpointer_p.h.
         : QCustomScopedPointer<T, QScopedPointerSharedDeleter<T> >(p)
     {
     }
Functions
assign()
template<typename T> void QScopedSharedPointer< T >::assign (T * other) inline
Definition at line 122 of file qscopedpointer_p.h.
Referenced by QScriptValueProperty::operator=(), QScriptDebuggerValueProperty::operator=(), QScriptDebuggerConsoleCommandGroupData::operator=(), QScriptScriptData::operator=(), and QScriptDebuggerValue::operator=().
     {
         if (this->d == other)
             return;
         if (other)
             other->ref.ref();
         T *oldD = this->d;
         this->d = other;
         QScopedPointerSharedDeleter<T>::cleanup(oldD);
     }
detach()
template<typename T> void QScopedSharedPointer< T >::detach () inline
Definition at line 117 of file qscopedpointer_p.h.
     {
         qAtomicDetach(this->d);
     }
operator!=()
template<typename T> bool QScopedSharedPointer< T >::operator!= (const QScopedSharedPointer< T > & other) const inline
Definition at line 138 of file qscopedpointer_p.h.
     {
         return this->d != other.d;
     }
operator==()
template<typename T> bool QScopedSharedPointer< T >::operator== (const QScopedSharedPointer< T > & other) const inline
Definition at line 133 of file qscopedpointer_p.h.
     {
         return this->d == other.d;
     }
The documentation for this class was generated from the following file:
/src/corelib/tools/qscopedpointer_p.h