Qt 4.8: QTextLayout Class Reference
QTextLayout Class Reference
The QTextLayout class is used to lay out and render text.
#include <qtextlayout.h>
Classes
class FormatRange
The QTextLayout::FormatRange structure is used to apply extra formatting information for a specified area in the text layout's content.
Public Types
enum CursorMode { SkipCharacters, SkipWords }
Public Functions
QList< FormatRange > additionalFormats () const
Returns the list of additional formats supported by the text layout.
void beginLayout ()
Begins the layout process.
QRectF boundingRect () const
The smallest rectangle that contains all the lines in the layout.
bool cacheEnabled () const
Returns true if the complete layout information is cached; otherwise returns false.
void clearAdditionalFormats ()
Clears the list of additional formats supported by the text layout.
void clearLayout ()
Clears the line information in the layout.
QTextLine createLine ()
Returns a new text line to be laid out if there is text to be inserted into the layout; otherwise returns an invalid text line.
Qt::CursorMoveStyle cursorMoveStyle () const
The cursor movement style of this QTextLayout.
void draw (QPainter *p, const QPointF &pos, const QVector< FormatRange > &selections=QVector< FormatRange >(), const QRectF &clip=QRectF()) const
Draws the whole layout on the painter p at the position specified by pos.
void drawCursor (QPainter *p, const QPointF &pos, int cursorPosition) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws a text cursor with the current pen at the given position using the painter specified.
void drawCursor (QPainter *p, const QPointF &pos, int cursorPosition, int width) const
Draws a text cursor with the current pen and the specified width at the given position using the painter specified.
void endLayout ()
Ends the layout process.
QTextEngine * engine () const
QFont font () const
Returns the current font that is used for the layout, or a default font if none is set.
QList< QGlyphRun > glyphRuns () const
Returns the glyph indexes and positions for all glyphs in this QTextLayout.
bool isValidCursorPosition (int pos) const
/ Returns true if position pos is a valid cursor position.
int leftCursorPosition (int oldPos) const
Returns the cursor position to the left of oldPos, next to it.
QTextLine lineAt (int i) const
Returns the {i}-th line of text in this text layout.
int lineCount () const
Returns the number of lines in this text layout.
QTextLine lineForTextPosition (int pos) const
Returns the line that contains the cursor position specified by pos.
qreal maximumWidth () const
The maximum width the layout could expand to; this is essentially the width of the entire text.
qreal minimumWidth () const
The minimum width the layout needs.
int nextCursorPosition (int oldPos, CursorMode mode=SkipCharacters) const
Returns the next valid cursor position after oldPos that respects the given cursor mode.
QPointF position () const
The global position of the layout.
int preeditAreaPosition () const
Returns the position of the area in the text layout that will be processed before editing occurs.
QString preeditAreaText () const
Returns the text that is inserted in the layout before editing occurs.
int previousCursorPosition (int oldPos, CursorMode mode=SkipCharacters) const
Returns the first valid cursor position before oldPos that respects the given cursor mode.
QTextLayout ()
Constructs an empty text layout.
QTextLayout (const QString &text)
Constructs a text layout to lay out the given text.
QTextLayout (const QString &text, const QFont &font, QPaintDevice *paintdevice=0)
Constructs a text layout to lay out the given text with the specified font.
QTextLayout (const QTextBlock &b)
Constructs a text layout to lay out the given block.
int rightCursorPosition (int oldPos) const
Returns the cursor position to the right of oldPos, next to it.
void setAdditionalFormats (const QList< FormatRange > &overrides)
Sets the additional formats supported by the text layout to formatList.
void setCacheEnabled (bool enable)
Enables caching of the complete layout information if enable is true; otherwise disables layout caching.
void setCursorMoveStyle (Qt::CursorMoveStyle style)
Set the cursor movement style.
void setFlags (int flags)
void setFont (const QFont &f)
Sets the layout's font to the given font.
void setPosition (const QPointF &p)
Moves the text layout to point p.
void setPreeditArea (int position, const QString &text)
Sets the position and text of the area in the layout that is processed before editing occurs.
void setText (const QString &string)
Sets the layout's text to the given string.
void setTextOption (const QTextOption &option)
Sets the text option structure that controls the layout process to the given option.
QString text () const
Returns the layout's text.
QTextOption textOption () const
Returns the current text option used to control the layout process.
~QTextLayout ()
Destructs the layout.
Private Functions
QTextLayout (QTextEngine *e)
Properties
QTextEngine * d
Friends
class QGraphicsSimpleTextItem
class QGraphicsSimpleTextItemPrivate
class QPainter
class QPSPrinter
void qt_format_text (const QFont &font, const QRectF &_r, int tf, const QTextOption *, const QString &str, QRectF *brect, int tabstops, int *tabarray, int tabarraylen, QPainter *painter)
Detailed Description
The QTextLayout class is used to lay out and render text.
Note
This class or function is reentrant.
It offers many features expected from a modern text layout engine, including Unicode compliant rendering, line breaking and handling of cursor positioning. It can also produce and render device independent layout, something that is important for WYSIWYG applications.
The class has a rather low level API and unless you intend to implement your own text rendering for some specialized widget, you probably won't need to use it directly.
QTextLayout can be used with both plain and rich text.
QTextLayout can be used to create a sequence of QTextLine instances with given widths and can position them independently on the screen. Once the layout is done, these lines can be drawn on a paint device.
The text to be laid out can be provided in the constructor or set with setText().
The layout can be seen as a sequence of QTextLine objects; use createLine() to create a QTextLine instance, and lineAt() or lineForTextPosition() to retrieve created lines.
Here is a code snippet that demonstrates the layout phase:
int leading = fontMetrics.leading();
qreal height = 0;
textLayout.beginLayout();
while (1) {
    QTextLine line = textLayout.createLine();
    if (!line.isValid())
        break;
    line.setLineWidth(lineWidth);
    height += leading;
    line.setPosition(QPointF(0, height));
    height += line.height();
}
textLayout.endLayout();
The text can then be rendered by calling the layout's draw() function:
QPainter painter(this);
textLayout.draw(&painter, QPoint(0, 0));
For a given position in the text you can find a valid cursor position with isValidCursorPosition(), nextCursorPosition(), and previousCursorPosition().
The QTextLayout itself can be positioned with setPosition(); it has a boundingRect(), and a minimumWidth() and a maximumWidth().
See also
QStaticText
Definition at line 105 of file qtextlayout.h.
Enumerations
CursorMode
enum QTextLayout::CursorMode
SkipCharacters
SkipWords
Enumerator
SkipCharacters
SkipWords
Definition at line 153 of file qtextlayout.h.
                     {
         SkipCharacters,
         SkipWords
     };
Constructors and Destructors
QTextLayout() [1/5]
QTextLayout::QTextLayout ()
Constructs an empty text layout.
See also
setText()
Definition at line 344 of file qtextlayout.cpp.
 { d = new QTextEngine(); }
QTextLayout() [2/5]
QTextLayout::QTextLayout (const QString & text)
Constructs a text layout to lay out the given text.
Definition at line 350 of file qtextlayout.cpp.
 {
     d = new QTextEngine();
     d->text = text;
 }
QTextLayout() [3/5]
QTextLayout::QTextLayout (const QString & text, const QFont & font, QPaintDevice * paintdevice = 0)
Constructs a text layout to lay out the given text with the specified font.
All the metric and layout calculations will be done in terms of the paint device, paintdevice. If paintdevice is 0 the calculations will be done in screen metrics.
Definition at line 364 of file qtextlayout.cpp.
 {
     QFont f(font);
     if (paintdevice)
         f = QFont(font, paintdevice);
     d = new QTextEngine((text.isNull() ? (const QString&)QString::fromLatin1("") : text), f.d.data());
 }
QTextLayout() [4/5]
QTextLayout::QTextLayout (const QTextBlock & block)
Constructs a text layout to lay out the given block.
Warning
This function is not part of the public interface.
Definition at line 379 of file qtextlayout.cpp.
 {
     d = new QTextEngine();
     d->block = block;
 }
~QTextLayout()
QTextLayout::~QTextLayout ()
Destructs the layout.
Definition at line 388 of file qtextlayout.cpp.
 {
     if (!d->stackEngine)
         delete d;
 }
QTextLayout() [5/5]
QTextLayout::QTextLayout (QTextEngine * e) inline private
Definition at line 183 of file qtextlayout.h.
 : d(e) {}
Functions
additionalFormats()
QList< QTextLayout::FormatRange > QTextLayout::additionalFormats () const
Returns the list of additional formats supported by the text layout.
See also
setAdditionalFormats(), clearAdditionalFormats()
Definition at line 551 of file qtextlayout.cpp.
Referenced by QSyntaxHighlighterPrivate::applyFormatChanges().
 {
     QList<FormatRange> formats;
     if (!d->specialData)
         return formats;
     formats = d->specialData->addFormats;
     if (d->specialData->addFormatIndices.isEmpty())
         return formats;
     const QTextFormatCollection *collection = d->formats();
     for (int i = 0; i < d->specialData->addFormatIndices.count(); ++i)
         formats[i].format = collection->charFormat(d->specialData->addFormatIndices.at(i));
     return formats;
 }
beginLayout()
void QTextLayout::beginLayout ()
Begins the layout process.
See also
endLayout()
Definition at line 645 of file qtextlayout.cpp.
Referenced by QPainterPath::addText(), QDeclarativeTextLayout::beginLayout(), QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), QRawFont::fromFont(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QStaticTextPrivate::paintText(), qt_format_text(), setupTextLayout(), QLineControl::updateDisplayText(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
 #ifndef QT_NO_DEBUG
     if (d->layoutData && d->layoutData->layoutState == QTextEngine::InLayout) {
         qWarning("QTextLayout::beginLayout: Called while already doing layout");
         return;
     }
 #endif
     d->invalidate();
     d->clearLineData();
     d->itemize();
     d->layoutData->layoutState = QTextEngine::InLayout;
 }
boundingRect()
QRectF QTextLayout::boundingRect () const
The smallest rectangle that contains all the lines in the layout.
Definition at line 934 of file qtextlayout.cpp.
Referenced by QTextDocumentLayout::blockBoundingRect(), QPlainTextDocumentLayout::blockBoundingRect(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), and QStaticTextPrivate::paintText().
 {
     if (d->lines.isEmpty())
         return QRectF();
     QFixed xmax, ymax;
     QFixed xmin = d->lines.at(0).x;
     QFixed ymin = d->lines.at(0).y;
     for (int i = 0; i < d->lines.size(); ++i) {
         const QScriptLine &si = d->lines[i];
         xmin = qMin(xmin, si.x);
         ymin = qMin(ymin, si.y);
         QFixed lineWidth = si.width < QFIXED_MAX ? qMax(si.width, si.textWidth) : si.textWidth;
         xmax = qMax(xmax, si.x+lineWidth);
         // ### shouldn't the ascent be used in ymin???
         ymax = qMax(ymax, si.y+si.height());
     }
     return QRectF(xmin.toReal(), ymin.toReal(), (xmax-xmin).toReal(), (ymax-ymin).toReal());
 }
cacheEnabled()
bool QTextLayout::cacheEnabled () const
Returns true if the complete layout information is cached; otherwise returns false.
See also
setCacheEnabled()
Definition at line 601 of file qtextlayout.cpp.
 {
     return d->cacheGlyphs;
 }
clearAdditionalFormats()
void QTextLayout::clearAdditionalFormats ()
Clears the list of additional formats supported by the text layout.
See also
additionalFormats(), setAdditionalFormats()
Definition at line 575 of file qtextlayout.cpp.
 {
     setAdditionalFormats(QList<FormatRange>());
 }
clearLayout()
void QTextLayout::clearLayout ()
Clears the line information in the layout.
Since
4.4
After having called this function, lineCount() returns 0.
Definition at line 690 of file qtextlayout.cpp.
Referenced by QDeclarativeTextLayout::clearLayout(), QTextBlock::clearLayout(), and QPlainTextDocumentLayoutPrivate::relayout().
 {
     d->clearLineData();
 }
createLine()
QTextLine QTextLayout::createLine ()
Returns a new text line to be laid out if there is text to be inserted into the layout; otherwise returns an invalid text line.
The text layout creates a new line object that starts after the last line in the layout, or at the beginning if the layout is empty. The layout maintains an internal cursor, and each line is filled with text from the cursor position onwards when the QTextLine::setLineWidth() function is called.
Once QTextLine::setLineWidth() is called, a new line can be created and filled with text. Repeating this process will lay out the whole block of text contained in the QTextLayout. If there is no text left to be inserted into the layout, the QTextLine returned will not be valid (isValid() will return false).
Definition at line 842 of file qtextlayout.cpp.
Referenced by QPainterPath::addText(), QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), QRawFont::fromFont(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QStaticTextPrivate::paintText(), qt_format_text(), setupTextLayout(), QLineControl::updateDisplayText(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
 #ifndef QT_NO_DEBUG
     if (!d->layoutData || d->layoutData->layoutState == QTextEngine::LayoutEmpty) {
         qWarning("QTextLayout::createLine: Called without layouting");
         return QTextLine();
     }
 #endif
     if (d->layoutData->layoutState == QTextEngine::LayoutFailed)
         return QTextLine();
     int l = d->lines.size();
     if (l && d->lines.at(l-1).length < 0) {
         QTextLine(l-1, d).setNumColumns(INT_MAX);
     }
     int from = l > 0 ? d->lines.at(l-1).from + d->lines.at(l-1).length + d->lines.at(l-1).trailingSpaces : 0;
     int strlen = d->layoutData->string.length();
     if (l && from >= strlen) {
         if (!d->lines.at(l-1).length || d->layoutData->string.at(strlen - 1) != QChar::LineSeparator)
             return QTextLine();
     }
     QScriptLine line;
     line.from = from;
     line.length = -1;
     line.justified = false;
     line.gridfitted = false;
     d->lines.append(line);
     return QTextLine(l, d);
 }
cursorMoveStyle()
Qt::CursorMoveStyle QTextLayout::cursorMoveStyle () const
The cursor movement style of this QTextLayout.
Since
4.8
The default is Qt::LogicalMoveStyle.
See also
setCursorMoveStyle()
Definition at line 635 of file qtextlayout.cpp.
 {
     return d->visualMovement ? Qt::VisualMoveStyle : Qt::LogicalMoveStyle;
 }
draw()
void QTextLayout::draw (QPainter * p, const QPointF & pos, const QVector< FormatRange > & selections = QVector<FormatRange>(), const QRectF & clip = QRectF()) const
Draws the whole layout on the painter p at the position specified by pos.
The rendered layout includes the given selections and is clipped within the rectangle specified by clip.
Definition at line 1074 of file qtextlayout.cpp.
Referenced by QDeclarativeTextLayout::draw(), QSvgText::draw(), QLineControl::draw(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawListItem(), QGraphicsSimpleTextItem::paint(), QPlainTextEdit::paintEvent(), QStaticTextPrivate::paintText(), and QDeclarativeTextLayout::prepare().
 {
     if (d->lines.isEmpty())
         return;
     if (!d->layoutData)
         d->itemize();
     QPointF position = pos + d->position;
     QFixed clipy = (INT_MIN/256);
     QFixed clipe = (INT_MAX/256);
     if (clip.isValid()) {
         clipy = QFixed::fromReal(clip.y() - position.y());
         clipe = clipy + QFixed::fromReal(clip.height());
     }
     int firstLine = 0;
     int lastLine = d->lines.size();
     for (int i = 0; i < d->lines.size(); ++i) {
         QTextLine l(i, d);
         const QScriptLine &sl = d->lines[i];
         if (sl.y > clipe) {
             lastLine = i;
             break;
         }
         if ((sl.y + sl.height()) < clipy) {
             firstLine = i;
             continue;
         }
     }
     QPainterPath excludedRegion;
     QPainterPath textDoneRegion;
     for (int i = 0; i < selections.size(); ++i) {
         FormatRange selection = selections.at(i);
         const QBrush bg = selection.format.background();
         QPainterPath region;
         region.setFillRule(Qt::WindingFill);
         for (int line = firstLine; line < lastLine; ++line) {
             const QScriptLine &sl = d->lines[line];
             QTextLine tl(line, d);
             QRectF lineRect(tl.naturalTextRect());
             lineRect.translate(position);
             lineRect.adjust(0, 0, d->leadingSpaceWidth(sl).toReal(), 0);
             bool isLastLineInBlock = (line == d->lines.size()-1);
             int sl_length = sl.length + (isLastLineInBlock? 1 : 0); // the infamous newline
             if (sl.from > selection.start + selection.length || sl.from + sl_length <= selection.start)
                 continue; // no actual intersection
             const bool selectionStartInLine = sl.from <= selection.start;
             const bool selectionEndInLine = selection.start + selection.length < sl.from + sl_length;
             if (sl.length && (selectionStartInLine || selectionEndInLine)) {
                 addSelectedRegionsToPath(d, line, position, &selection, &region, clipIfValid(lineRect, clip));
             } else {
                 region.addRect(clipIfValid(lineRect, clip));
             }
             if (selection.format.boolProperty(QTextFormat::FullWidthSelection)) {
                 QRectF fullLineRect(tl.rect());
                 fullLineRect.translate(position);
                 fullLineRect.setRight(QFIXED_MAX);
                 if (!selectionEndInLine)
                     region.addRect(clipIfValid(QRectF(lineRect.topRight(), fullLineRect.bottomRight()), clip));
                 if (!selectionStartInLine)
                     region.addRect(clipIfValid(QRectF(fullLineRect.topLeft(), lineRect.bottomLeft()), clip));
             } else if (!selectionEndInLine
                 && isLastLineInBlock
                 &&!(d->option.flags() & QTextOption::ShowLineAndParagraphSeparators)) {
                 region.addRect(clipIfValid(QRectF(lineRect.right(), lineRect.top(),
                                                   lineRect.height()/4, lineRect.height()), clip));
             }
         }
         {
             const QPen oldPen = p->pen();
             const QBrush oldBrush = p->brush();
             p->setPen(selection.format.penProperty(QTextFormat::OutlinePen));
             p->setBrush(selection.format.brushProperty(QTextFormat::BackgroundBrush));
             p->drawPath(region);
             p->setPen(oldPen);
             p->setBrush(oldBrush);
         }
         bool hasText = (selection.format.foreground().style() != Qt::NoBrush);
         bool hasBackground= (selection.format.background().style() != Qt::NoBrush);
         if (hasBackground) {
             selection.format.setProperty(ObjectSelectionBrush, selection.format.property(QTextFormat::BackgroundBrush));
             // don't just clear the property, set an empty brush that overrides a potential
             // background brush specified in the text
             selection.format.setProperty(QTextFormat::BackgroundBrush, QBrush());
             selection.format.clearProperty(QTextFormat::OutlinePen);
         }
         selection.format.setProperty(SuppressText, !hasText);
         if (hasText && !hasBackground && !(textDoneRegion & region).isEmpty())
             continue;
         p->save();
         p->setClipPath(region, Qt::IntersectClip);
         for (int line = firstLine; line < lastLine; ++line) {
             QTextLine l(line, d);
             l.draw(p, position, &selection);
         }
         p->restore();
         if (hasText) {
             textDoneRegion += region;
         } else {
             if (hasBackground)
                 textDoneRegion -= region;
         }
         excludedRegion += region;
     }
     QPainterPath needsTextButNoBackground = excludedRegion - textDoneRegion;
     if (!needsTextButNoBackground.isEmpty()){
         p->save();
         p->setClipPath(needsTextButNoBackground, Qt::IntersectClip);
         FormatRange selection;
         selection.start = 0;
         selection.length = INT_MAX;
         selection.format.setProperty(SuppressBackground, true);
         for (int line = firstLine; line < lastLine; ++line) {
             QTextLine l(line, d);
             l.draw(p, position, &selection);
         }
         p->restore();
     }
     if (!excludedRegion.isEmpty()) {
         p->save();
         QPainterPath path;
         QRectF br = boundingRect().translated(position);
         br.setRight(QFIXED_MAX);
         if (!clip.isNull())
             br = br.intersected(clip);
         path.addRect(br);
         path -= excludedRegion;
         p->setClipPath(path, Qt::IntersectClip);
     }
     for (int i = firstLine; i < lastLine; ++i) {
         QTextLine l(i, d);
         l.draw(p, position);
     }
     if (!excludedRegion.isEmpty())
         p->restore();
     if (!d->cacheGlyphs)
         d->freeMemory();
 }
drawCursor() [1/2]
void QTextLayout::drawCursor (QPainter * painter, const QPointF & position, int cursorPosition) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws a text cursor with the current pen at the given position using the painter specified.
The corresponding position within the text is specified by cursorPosition.
Definition at line 1252 of file qtextlayout.cpp.
Referenced by QLineControl::draw(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawFrame(), and QPlainTextEdit::paintEvent().
 {
     drawCursor(p, pos, cursorPosition, 1);
 }
drawCursor() [2/2]
void QTextLayout::drawCursor (QPainter * painter, const QPointF & position, int cursorPosition, int width) const
Draws a text cursor with the current pen and the specified width at the given position using the painter specified.
The corresponding position within the text is specified by cursorPosition.
Definition at line 1264 of file qtextlayout.cpp.
 {
     if (d->lines.isEmpty())
         return;
     if (!d->layoutData)
         d->itemize();
     QPointF position = pos + d->position;
     cursorPosition = qBound(0, cursorPosition, d->layoutData->string.length());
     int line = d->lineNumberForTextPosition(cursorPosition);
     if (line < 0)
         line = 0;
     if (line >= d->lines.size())
         return;
     QTextLine l(line, d);
     const QScriptLine &sl = d->lines[line];
     qreal x = position.x() + l.cursorToX(cursorPosition);
     int itm;
     if (d->visualCursorMovement()) {
         if (cursorPosition == sl.from + sl.length)
             cursorPosition--;
         itm = d->findItem(cursorPosition);
     } else
         itm = d->findItem(cursorPosition - 1);
     QFixed base = sl.base();
     QFixed descent = sl.descent;
     bool rightToLeft = d->isRightToLeft();
     if (itm >= 0) {
         const QScriptItem &si = d->layoutData->items.at(itm);
         if (si.ascent > 0)
             base = si.ascent;
         if (si.descent > 0)
             descent = si.descent;
         rightToLeft = si.analysis.bidiLevel % 2;
     }
     qreal y = position.y() + (sl.y + sl.base() - base).toReal();
     bool toggleAntialiasing = !(p->renderHints() & QPainter::Antialiasing)
                               && (p->transform().type() > QTransform::TxTranslate);
     if (toggleAntialiasing)
         p->setRenderHint(QPainter::Antialiasing);
 #if defined(QT_MAC_USE_COCOA)
     // Always draw the cursor aligned to pixel boundary.
     x = qRound(x);
 #endif
     p->fillRect(QRectF(x, y, qreal(width), (base + descent + 1).toReal()), p->pen().brush());
     if (toggleAntialiasing)
         p->setRenderHint(QPainter::Antialiasing, false);
     if (d->layoutData->hasBidi) {
         const int arrow_extent = 4;
         int sign = rightToLeft ? -1 : 1;
         p->drawLine(QLineF(x, y, x + (sign * arrow_extent/2), y + arrow_extent/2));
         p->drawLine(QLineF(x, y+arrow_extent, x + (sign * arrow_extent/2), y + arrow_extent/2));
     }
     return;
 }
endLayout()
void QTextLayout::endLayout ()
Ends the layout process.
See also
beginLayout()
Definition at line 664 of file qtextlayout.cpp.
Referenced by QPainterPath::addText(), QCommandLinkButtonPrivate::descriptionHeight(), QItemDelegatePrivate::doTextLayout(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), QRawFont::fromFont(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QStaticTextPrivate::paintText(), qt_format_text(), setupTextLayout(), QLineControl::updateDisplayText(), QCommonStylePrivate::viewItemSize(), and viewItemTextLayout().
 {
 #ifndef QT_NO_DEBUG
     if (!d->layoutData || d->layoutData->layoutState == QTextEngine::LayoutEmpty) {
         qWarning("QTextLayout::endLayout: Called without beginLayout()");
         return;
     }
 #endif
     int l = d->lines.size();
     if (l && d->lines.at(l-1).length < 0) {
         QTextLine(l-1, d).setNumColumns(INT_MAX);
     }
     d->layoutData->layoutState = QTextEngine::LayoutEmpty;
     if (!d->cacheGlyphs)
         d->freeMemory();
 }
engine()
QTextEngine * QTextLayout::engine () const inline
Warning
This function is not part of the public interface.
Returns the text engine used to render the text layout.
Definition at line 180 of file qtextlayout.h.
Referenced by QPainterPath::addText(), QTextBlockData::invalidate(), QTextCursorPrivate::movePosition(), and qt_format_text().
 { return d; }
font()
QFont QTextLayout::font () const
Returns the current font that is used for the layout, or a default font if none is set.
See also
setFont()
Definition at line 412 of file qtextlayout.cpp.
Referenced by QDeclarativeTextLayout::prepare(), and QTextControlPrivate::rectForPosition().
 {
     return d->font();
 }
glyphRuns()
QList< QGlyphRun > QTextLayout::glyphRuns () const
Returns the glyph indexes and positions for all glyphs in this QTextLayout.
This is an expensive function, and should not be called in a time sensitive context.
Since
4.8
See also
draw(), QPainter::drawGlyphRun()
Definition at line 1059 of file qtextlayout.cpp.
Referenced by QRawFont::fromFont().
 {
     QList<QGlyphRun> glyphs;
     for (int i=0; i<d->lines.size(); ++i)
         glyphs += QTextLine(i, d).glyphs(-1, -1);
     return glyphs;
 }
isValidCursorPosition()
bool QTextLayout::isValidCursorPosition (int pos) const
/ Returns true if position pos is a valid cursor position.
In a Unicode context some positions in the text are not valid cursor positions, because the position is inside a Unicode surrogate or a grapheme cluster.
A grapheme cluster is a sequence of two or more Unicode characters that form one indivisible entity on the screen. For example the latin character `' can be represented in Unicode by two characters, `A' (0x41), and the combining diaresis (0x308). A text cursor can only validly be positioned before or after these two characters, never between them since that wouldn't make sense. In indic languages every syllable forms a grapheme cluster.
Definition at line 818 of file qtextlayout.cpp.
 {
     const HB_CharAttributes *attributes = d->attributes();
     if (!attributes || pos < 0 || pos > (int)d->layoutData->string.length())
         return false;
     return attributes[pos].charStop;
 }
leftCursorPosition()
int QTextLayout::leftCursorPosition (int oldPos) const
Returns the cursor position to the left of oldPos, next to it.
Since
4.8
The position is dependent on the visual position of characters, after bi-directional reordering.
See also
rightCursorPosition(), previousCursorPosition()
Definition at line 796 of file qtextlayout.cpp.
Referenced by QTextDocumentPrivate::leftCursorPosition().
 {
     int newPos = d->positionAfterVisualMovement(oldPos, QTextCursor::Left);
 //    qDebug("%d -> %d", oldPos, newPos);
     return newPos;
 }
lineAt()
QTextLine QTextLayout::lineAt (int i) const
Returns the {i}-th line of text in this text layout.
See also
lineCount(), lineForTextPosition()
Definition at line 889 of file qtextlayout.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextDocumentLayout::blockBoundingRect(), QPlainTextDocumentLayout::blockWidth(), QLineControl::cursorRect(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), flowPosition(), QTextFragment::glyphRuns(), QPlainTextEditControl::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QTextCursorPrivate::movePosition(), QPlainTextEditPrivate::pageUpDown(), QTextDocumentLayout::positionInlineObject(), qt_format_text(), setupTextLayout(), QPlainTextEditPrivate::verticalOffset(), QCommonStylePrivate::viewItemDrawText(), and QLineControl::xToPos().
 {
     return QTextLine(i, d);
 }
lineCount()
int QTextLayout::lineCount () const
Returns the number of lines in this text layout.
See also
lineAt()
Definition at line 879 of file qtextlayout.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextDocumentLayout::blockBoundingRect(), QTextCursorPrivate::blockLayout(), QPlainTextDocumentLayout::blockWidth(), QTextCursor::columnNumber(), QTextControlPrivate::cursorMoveKeyEvent(), QPlainTextDocumentLayout::documentChanged(), QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), QPlainTextDocumentLayout::ensureBlockLayout(), flowPosition(), QTextFragment::glyphRuns(), QPlainTextEditControl::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QTextCursorPrivate::movePosition(), QPlainTextEditPrivate::pageUpDown(), QTextDocumentLayout::positionInlineObject(), qt_format_text(), QTextControl::selectionRect(), setupTextLayout(), QDeclarativeTextEdit::updateTotalLines(), and QCommonStylePrivate::viewItemDrawText().
 {
     return d->lines.size();
 }
lineForTextPosition()
QTextLine QTextLayout::lineForTextPosition (int pos) const
Returns the line that contains the cursor position specified by pos.
See also
isValidCursorPosition(), lineAt()
Definition at line 899 of file qtextlayout.cpp.
Referenced by QAccessibleTextWidget::characterRect(), QTextCursor::columnNumber(), currentTextLine(), QTextDocumentLayoutPrivate::drawBlock(), QTextCursorPrivate::movePosition(), QPlainTextEdit::paintEvent(), QTextControlPrivate::rectForPosition(), QTextControl::selectionRect(), and QTextCursorPrivate::setX().
 {
     int lineNum = d->lineNumberForTextPosition(pos);
     return lineNum >= 0 ? lineAt(lineNum) : QTextLine();
 }
maximumWidth()
qreal QTextLayout::maximumWidth () const
The maximum width the layout could expand to; this is essentially the width of the entire text.
Warning
This function only returns a valid value after the layout has been done.
See also
minimumWidth()
Definition at line 978 of file qtextlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock().
 {
     return d->maxWidth.toReal();
 }
minimumWidth()
qreal QTextLayout::minimumWidth () const
The minimum width the layout needs.
This is the width of the layout's smallest non-breakable substring.
Warning
This function only returns a valid value after the layout has been done.
See also
maximumWidth()
Definition at line 964 of file qtextlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock().
 {
     return d->minWidth.toReal();
 }
nextCursorPosition()
int QTextLayout::nextCursorPosition (int oldPos, CursorMode mode = SkipCharacters) const
Returns the next valid cursor position after oldPos that respects the given cursor mode.
Returns value of oldPos, if oldPos is not a valid cursor position.
See also
isValidCursorPosition(), previousCursorPosition()
Definition at line 702 of file qtextlayout.cpp.
Referenced by QLineControl::del(), QTextDocumentPrivate::nextCursorPosition(), and QLineControl::selectWordAtPos().
 {
     const HB_CharAttributes *attributes = d->attributes();
     int len = d->block.isValid() ? d->block.length() - 1
                                  : d->layoutData->string.length();
     Q_ASSERT(len <= d->layoutData->string.length());
     if (!attributes || oldPos < 0 || oldPos >= len)
         return oldPos;
     if (mode == SkipCharacters) {
         oldPos++;
         while (oldPos < len && !attributes[oldPos].charStop)
             oldPos++;
     } else {
         if (oldPos < len && d->atWordSeparator(oldPos)) {
             oldPos++;
             while (oldPos < len && d->atWordSeparator(oldPos))
                 oldPos++;
         } else {
             while (oldPos < len && !d->atSpace(oldPos) && !d->atWordSeparator(oldPos))
                 oldPos++;
         }
         while (oldPos < len && d->atSpace(oldPos))
             oldPos++;
     }
     return oldPos;
 }
position()
QPointF QTextLayout::position () const
The global position of the layout.
Since
4.2
This is independent of the bounding rectangle and of the layout process.
See also
setPosition()
Definition at line 916 of file qtextlayout.cpp.
Referenced by QTextDocumentLayout::blockBoundingRect(), QAccessibleTextWidget::characterRect(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawListItem(), flowPosition(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutBlock(), and QTextDocumentLayoutPrivate::layoutFlow().
 {
     return d->position;
 }
preeditAreaPosition()
int QTextLayout::preeditAreaPosition () const
Returns the position of the area in the text layout that will be processed before editing occurs.
See also
preeditAreaText()
Definition at line 500 of file qtextlayout.cpp.
Referenced by QSyntaxHighlighterPrivate::applyFormatChanges(), QTextDocumentLayoutPrivate::drawBlock(), QPlainTextEdit::paintEvent(), and QTextControlPrivate::rectForPosition().
 {
     return d->specialData ? d->specialData->preeditPosition : -1;
 }
preeditAreaText()
QString QTextLayout::preeditAreaText () const
Returns the text that is inserted in the layout before editing occurs.
See also
preeditAreaPosition()
Definition at line 510 of file qtextlayout.cpp.
Referenced by QSyntaxHighlighterPrivate::applyFormatChanges(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayout::hitTest(), QPlainTextEdit::paintEvent(), QDeclarativeTextEdit::positionAt(), QTextControlPrivate::rectForPosition(), and QTextControlPrivate::sendMouseEventToInputContext().
 {
     return d->specialData ? d->specialData->preeditText : QString();
 }
previousCursorPosition()
int QTextLayout::previousCursorPosition (int oldPos, CursorMode mode = SkipCharacters) const
Returns the first valid cursor position before oldPos that respects the given cursor mode.
Returns value of oldPos, if oldPos is not a valid cursor position.
See also
isValidCursorPosition(), nextCursorPosition()
Definition at line 738 of file qtextlayout.cpp.
Referenced by QTextDocumentPrivate::previousCursorPosition(), and QLineControl::selectWordAtPos().
 {
     const HB_CharAttributes *attributes = d->attributes();
     if (!attributes || oldPos <= 0 || oldPos > d->layoutData->string.length())
         return oldPos;
     if (mode == SkipCharacters) {
         oldPos--;
         while (oldPos && !attributes[oldPos].charStop)
             oldPos--;
     } else {
         while (oldPos && d->atSpace(oldPos-1))
             oldPos--;
         if (oldPos && d->atWordSeparator(oldPos-1)) {
             oldPos--;
             while (oldPos && d->atWordSeparator(oldPos-1))
                 oldPos--;
         } else {
             while (oldPos && !d->atSpace(oldPos-1) && !d->atWordSeparator(oldPos-1))
                 oldPos--;
         }
     }
     return oldPos;
 }
rightCursorPosition()
int QTextLayout::rightCursorPosition (int oldPos) const
Returns the cursor position to the right of oldPos, next to it.
Since
4.8
The position is dependent on the visual position of characters, after bi-directional reordering.
See also
leftCursorPosition(), nextCursorPosition()
Definition at line 777 of file qtextlayout.cpp.
Referenced by QTextDocumentPrivate::rightCursorPosition().
 {
     int newPos = d->positionAfterVisualMovement(oldPos, QTextCursor::Right);
 //    qDebug("%d -> %d", oldPos, newPos);
     return newPos;
 }
setAdditionalFormats()
void QTextLayout::setAdditionalFormats (const QList< FormatRange > & formatList)
Sets the additional formats supported by the text layout to formatList.
See also
additionalFormats(), clearAdditionalFormats()
Definition at line 521 of file qtextlayout.cpp.
Referenced by QSyntaxHighlighterPrivate::applyFormatChanges(), QSvgText::draw(), QTextControlPrivate::inputMethodEvent(), QGraphicsSimpleTextItem::paint(), and QLineControl::processInputMethodEvent().
 {
     if (formatList.isEmpty()) {
         if (!d->specialData)
             return;
         if (d->specialData->preeditText.isEmpty()) {
             delete d->specialData;
             d->specialData = 0;
         } else {
             d->specialData->addFormats = formatList;
             d->specialData->addFormatIndices.clear();
         }
     } else {
         if (!d->specialData) {
             d->specialData = new QTextEngine::SpecialData;
             d->specialData->preeditPosition = -1;
         }
         d->specialData->addFormats = formatList;
         d->indexAdditionalFormats();
     }
     if (d->block.docHandle())
         d->block.docHandle()->documentChange(d->block.position(), d->block.length());
     d->resetFontEngineCache();
 }
setCacheEnabled()
void QTextLayout::setCacheEnabled (bool enable)
Enables caching of the complete layout information if enable is true; otherwise disables layout caching.
Usually QTextLayout throws most of the layouting information away after a call to endLayout() to reduce memory consumption. If you however want to draw the laid out text directly afterwards enabling caching might speed up drawing significantly.
See also
cacheEnabled()
Definition at line 590 of file qtextlayout.cpp.
Referenced by QPainterPath::addText(), QTextDocumentLayoutPrivate::drawListItem(), qt_format_text(), and setupTextLayout().
 {
     d->cacheGlyphs = enable;
 }
setCursorMoveStyle()
void QTextLayout::setCursorMoveStyle (Qt::CursorMoveStyle style)
Set the cursor movement style.
Since
4.8
If the QTextLayout is backed by a document, you can ignore this and use the option in QTextDocument, this option is for widgets like QLineEdit or custom widgets without a QTextDocument. Default value is Qt::LogicalMoveStyle.
See also
cursorMoveStyle()
Definition at line 619 of file qtextlayout.cpp.
 {
     d->visualMovement = style == Qt::VisualMoveStyle ? true : false;
 }
setFlags()
void QTextLayout::setFlags (int flags)
Warning
This function is not part of the public interface.
Definition at line 987 of file qtextlayout.cpp.
 {
     if (flags & Qt::TextJustificationForced) {
         d->option.setAlignment(Qt::AlignJustify);
         d->forceJustification = true;
     }
     if (flags & (Qt::TextForceLeftToRight|Qt::TextForceRightToLeft)) {
         d->ignoreBidi = true;
         d->option.setTextDirection((flags & Qt::TextForceLeftToRight) ? Qt::LeftToRight : Qt::RightToLeft);
     }
 }
setFont()
void QTextLayout::setFont (const QFont & font)
Sets the layout's font to the given font.
The layout is invalidated and must be laid out again.
See also
font()
Definition at line 400 of file qtextlayout.cpp.
Referenced by QCommandLinkButtonPrivate::descriptionHeight(), QStaticTextPrivate::paintText(), QCommonStylePrivate::viewItemDrawText(), and QCommonStylePrivate::viewItemSize().
 {
     d->fnt = font;
     d->resetFontEngineCache();
 }
setPosition()
void QTextLayout::setPosition (const QPointF & p)
Moves the text layout to point p.
See also
position()
Definition at line 926 of file qtextlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawListItem(), QTextDocumentLayoutPrivate::layoutBlock(), and QTextDocumentLayoutPrivate::layoutFlow().
 {
     d->position = p;
 }
setPreeditArea()
void QTextLayout::setPreeditArea (int position, const QString & text)
Sets the position and text of the area in the layout that is processed before editing occurs.
See also
preeditAreaPosition(), preeditAreaText()
Definition at line 470 of file qtextlayout.cpp.
Referenced by QTextControlPrivate::inputMethodEvent().
 {
     if (text.isEmpty()) {
         if (!d->specialData)
             return;
         if (d->specialData->addFormats.isEmpty()) {
             delete d->specialData;
             d->specialData = 0;
         } else {
             d->specialData->preeditText = QString();
             d->specialData->preeditPosition = -1;
         }
     } else {
         if (!d->specialData)
             d->specialData = new QTextEngine::SpecialData;
         d->specialData->preeditPosition = position;
         d->specialData->preeditText = text;
     }
     d->invalidate();
     d->clearLineData();
     if (d->block.docHandle())
         d->block.docHandle()->documentChange(d->block.position(), d->block.length());
 }
setText()
void QTextLayout::setText (const QString & string)
Sets the layout's text to the given string.
The layout is invalidated and must be laid out again.
Notice that when using this QTextLayout as part of a QTextDocument this method will have no effect.
See also
text()
Definition at line 426 of file qtextlayout.cpp.
Referenced by QStaticTextPrivate::paintText(), QLineControl::updateDisplayText(), QCommonStylePrivate::viewItemDrawText(), and QCommonStylePrivate::viewItemSize().
 {
     d->invalidate();
     d->clearLineData();
     d->text = string;
 }
setTextOption()
void QTextLayout::setTextOption (const QTextOption & option)
Sets the text option structure that controls the layout process to the given option.
See also
textOption()
Definition at line 449 of file qtextlayout.cpp.
Referenced by QSvgText::draw(), QTextDocumentLayoutPrivate::drawListItem(), QPlainTextDocumentLayout::layoutBlock(), QTextDocumentLayoutPrivate::layoutBlock(), QStaticTextPrivate::paintText(), QLineControl::updateDisplayText(), QCommonStylePrivate::viewItemDrawText(), and QCommonStylePrivate::viewItemSize().
 {
     d->option = option;
 }
text()
QString QTextLayout::text () const
Returns the layout's text.
See also
setText()
Definition at line 438 of file qtextlayout.cpp.
Referenced by QGraphicsSimpleTextItem::paint(), QLineControl::updateDisplayText(), and QCommonStylePrivate::viewItemDrawText().
 {
     return d->text;
 }
textOption()
QTextOption QTextLayout::textOption () const
Returns the current text option used to control the layout process.
See also
setTextOption()
Definition at line 459 of file qtextlayout.cpp.
Referenced by QSvgText::draw(), and QTextDocumentLayoutPrivate::layoutFlow().
 {
     return d->option;
 }
Friends and Related Functions
QGraphicsSimpleTextItem
friend class QGraphicsSimpleTextItem friend
Definition at line 189 of file qtextlayout.h.
QGraphicsSimpleTextItemPrivate
friend class QGraphicsSimpleTextItemPrivate friend
Definition at line 188 of file qtextlayout.h.
QPainter
friend class QPainter friend
Definition at line 186 of file qtextlayout.h.
QPSPrinter
friend class QPSPrinter friend
Definition at line 187 of file qtextlayout.h.
qt_format_text
void qt_format_text (const QFont & font, const QRectF & _r, int tf, const QTextOption * opt, const QString & str, QRectF * brect, int tabstops, int * tabarray, int tabarraylen, QPainter * painter) friend
Definition at line 8458 of file qpainter.cpp.
 {
     Q_ASSERT( !((tf & ~Qt::TextDontPrint)!=0 && option!=0) ); // we either have an option or flags
     if (option) {
         tf |= option->alignment();
         if (option->wrapMode() != QTextOption::NoWrap)
             tf |= Qt::TextWordWrap;
         if (option->flags() & QTextOption::IncludeTrailingSpaces)
             tf |= Qt::TextIncludeTrailingSpaces;
         if (option->tabStop() >= 0 || !option->tabArray().isEmpty())
             tf |= Qt::TextExpandTabs;
     }
     // we need to copy r here to protect against the case (&r == brect).
     QRectF r(_r);
     bool dontclip  = (tf & Qt::TextDontClip);
     bool wordwrap  = (tf & Qt::TextWordWrap) || (tf & Qt::TextWrapAnywhere);
     bool singleline = (tf & Qt::TextSingleLine);
     bool showmnemonic = (tf & Qt::TextShowMnemonic);
     bool hidemnmemonic = (tf & Qt::TextHideMnemonic);
     Qt::LayoutDirection layout_direction;
     if (tf & Qt::TextForceLeftToRight)
         layout_direction = Qt::LeftToRight;
     else if (tf & Qt::TextForceRightToLeft)
         layout_direction = Qt::RightToLeft;
     else if (option)
         layout_direction = option->textDirection();
     else if (painter)
         layout_direction = painter->layoutDirection();
     else
         layout_direction = Qt::LeftToRight;
     tf = QStyle::visualAlignment(layout_direction, QFlag(tf));
     bool isRightToLeft = layout_direction == Qt::RightToLeft;
     bool expandtabs = ((tf & Qt::TextExpandTabs) &&
                         (((tf & Qt::AlignLeft) && !isRightToLeft) ||
                           ((tf & Qt::AlignRight) && isRightToLeft)));
     if (!painter)
         tf |= Qt::TextDontPrint;
     uint maxUnderlines = 0;
     int numUnderlines = 0;
     QVarLengthArray<int, 32> underlinePositions(1);
     QFontMetricsF fm(fnt);
     QString text = str;
     int offset = 0;
 start_lengthVariant:
     bool hasMoreLengthVariants = false;
     // compatible behaviour to the old implementation. Replace
     // tabs by spaces
     int old_offset = offset;
     for (; offset < text.length(); offset++) {
         QChar chr = text.at(offset);
         if (chr == QLatin1Char('\r') || (singleline && chr == QLatin1Char('\n'))) {
             text[offset] = QLatin1Char(' ');
         } else if (chr == QLatin1Char('\n')) {
             text[offset] = QChar::LineSeparator;
         } else if (chr == QLatin1Char('&')) {
             ++maxUnderlines;
         } else if (chr == QLatin1Char('\t')) {
             if (!expandtabs) {
                 text[offset] = QLatin1Char(' ');
             } else if (!tabarraylen && !tabstops) {
                 tabstops = qRound(fm.width(QLatin1Char('x'))*8);
             }
         } else if (chr == QChar(ushort(0x9c))) {
             // string with multiple length variants
             hasMoreLengthVariants = true;
             break;
         }
     }
     int length = offset - old_offset;
     if ((hidemnmemonic || showmnemonic) && maxUnderlines > 0) {
         underlinePositions.resize(maxUnderlines + 1);
         QChar *cout = text.data() + old_offset;
         QChar *cin = cout;
         int l = length;
         while (l) {
             if (*cin == QLatin1Char('&')) {
                 ++cin;
                 --length;
                 --l;
                 if (!l)
                     break;
                 if (*cin != QLatin1Char('&') && !hidemnmemonic)
                     underlinePositions[numUnderlines++] = cout - text.data() - old_offset;
             }
             *cout = *cin;
             ++cout;
             ++cin;
             --l;
         }
     }
     // no need to do extra work for underlines if we don't paint
     if (tf & Qt::TextDontPrint)
         numUnderlines = 0;
     underlinePositions[numUnderlines] = -1;
     qreal height = 0;
     qreal width = 0;
     QString finalText = text.mid(old_offset, length);
     QStackTextEngine engine(finalText, fnt);
     if (option) {
         engine.option = *option;
     }
     if (engine.option.tabStop() < 0 && tabstops > 0)
         engine.option.setTabStop(tabstops);
     if (engine.option.tabs().isEmpty() && ta) {
         QList<qreal> tabs;
         for (int i = 0; i < tabarraylen; i++)
             tabs.append(qreal(ta[i]));
         engine.option.setTabArray(tabs);
     }
     engine.option.setTextDirection(layout_direction);
     if (tf & Qt::AlignJustify)
         engine.option.setAlignment(Qt::AlignJustify);
     else
         engine.option.setAlignment(Qt::AlignLeft); // do not do alignment twice
     if (!option && (tf & Qt::TextWrapAnywhere))
         engine.option.setWrapMode(QTextOption::WrapAnywhere);
     if (tf & Qt::TextJustificationForced)
         engine.forceJustification = true;
     QTextLayout textLayout(&engine);
     textLayout.setCacheEnabled(true);
     textLayout.engine()->underlinePositions = underlinePositions.data();
     if (finalText.isEmpty()) {
         height = fm.height();
         width = 0;
         tf |= Qt::TextDontPrint;
     } else {
         qreal lineWidth = 0x01000000;
         if (wordwrap || (tf & Qt::TextJustificationForced))
             lineWidth = qMax<qreal>(0, r.width());
         if(!wordwrap)
             tf |= Qt::TextIncludeTrailingSpaces;
         textLayout.engine()->ignoreBidi = bool(tf & Qt::TextDontPrint);
         textLayout.beginLayout();
         qreal leading = fm.leading();
         height = -leading;
         while (1) {
             QTextLine l = textLayout.createLine();
             if (!l.isValid())
                 break;
             l.setLineWidth(lineWidth);
             height += leading;
             l.setPosition(QPointF(0., height));
             height += l.height();
             width = qMax(width, l.naturalTextWidth());
             if (!dontclip && !brect && height >= r.height())
                 break;
         }
         textLayout.endLayout();
     }
     qreal yoff = 0;
     qreal xoff = 0;
     if (tf & Qt::AlignBottom) {
         yoff = r.height() - height;
     } else if (tf & Qt::AlignVCenter) {
         yoff = (r.height() - height)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m22();
                 if (scale != 0)
                     yoff = -qRound(-yoff * scale) / scale;
             }
         }
     }
     if (tf & Qt::AlignRight) {
         xoff = r.width() - width;
     } else if (tf & Qt::AlignHCenter) {
         xoff = (r.width() - width)/2;
         if (painter) {
             QTransform::TransformationType type = painter->transform().type();
             if (type <= QTransform::TxScale) {
                 // do the rounding manually to work around inconsistencies
                 // in the paint engines when drawing on floating point offsets
                 const qreal scale = painter->transform().m11();
                 if (scale != 0)
                     xoff = qRound(xoff * scale) / scale;
             }
         }
     }
     QRectF bounds = QRectF(r.x() + xoff, r.y() + yoff, width, height);
     if (hasMoreLengthVariants && !(tf & Qt::TextLongestVariant) && !r.contains(bounds)) {
         offset++;
         goto start_lengthVariant;
     }
     if (brect)
         *brect = bounds;
     if (!(tf & Qt::TextDontPrint)) {
         bool restore = false;
         if (!dontclip && !r.contains(bounds)) {
             restore = true;
             painter->save();
             painter->setClipRect(r, Qt::IntersectClip);
         }
         for (int i = 0; i < textLayout.lineCount(); i++) {
             QTextLine line = textLayout.lineAt(i);
             qreal advance = line.horizontalAdvance();
             xoff = 0;
             if (tf & Qt::AlignRight) {
                 QTextEngine *eng = textLayout.engine();
                 xoff = r.width() - advance -
                     eng->leadingSpaceWidth(eng->lines[line.lineNumber()]).toReal();
             }
             else if (tf & Qt::AlignHCenter)
                 xoff = (r.width() - advance) / 2;
             line.draw(painter, QPointF(r.x() + xoff, r.y() + yoff));
         }
         if (restore) {
             painter->restore();
         }
     }
 }
Properties
d
QTextEngine* QTextLayout::d private
Definition at line 193 of file qtextlayout.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextlayout.h
/src/gui/text/qtextlayout.cpp