Qt 4.8: QPatternist::XsdSchemaDebugger Class Reference
QPatternist::XsdSchemaDebugger Class Reference
#include <qxsdschemadebugger_p.h>
Public Functions
void dumpAttribute (const XsdAttribute::Ptr &attribute)
void dumpElement (const XsdElement::Ptr &element)
void dumpInheritance (const SchemaType::Ptr &type, int level=0)
void dumpParticle (const XsdParticle::Ptr &particle, int level=0)
void dumpSchema (const XsdSchema::Ptr &schema)
void dumpType (const SchemaType::Ptr &type)
void dumpWildcard (const XsdWildcard::Ptr &wildcard)
XsdSchemaDebugger (const NamePool::Ptr &namePool)
Properties
const NamePool::Ptr m_namePool
Detailed Description
A helper class to print out the structure of a compiled schema.
Definition at line 66 of file qxsdschemadebugger_p.h.
Constructors and Destructors
XsdSchemaDebugger()
XsdSchemaDebugger::XsdSchemaDebugger (const NamePool::Ptr & namePool)
Creates a new schema debugger.
Parameters
namePool The name pool that the schema uses.
Definition at line 48 of file qxsdschemadebugger.cpp.
     : m_namePool(namePool)
 {
 }
Functions
dumpAttribute()
void XsdSchemaDebugger::dumpAttribute (const XsdAttribute::Ptr & attribute)
Dumps the structure of the given attribute.
Definition at line 177 of file qxsdschemadebugger.cpp.
Referenced by dumpSchema().
 {
     qDebug() << "Name:" << attribute->displayName(m_namePool);
     qDebug() << "Type:" << attribute->type()->displayName(m_namePool);
 }
dumpElement()
void XsdSchemaDebugger::dumpElement (const XsdElement::Ptr & element)
Dumps the structure of the given element.
Definition at line 160 of file qxsdschemadebugger.cpp.
Referenced by dumpSchema().
 {
     QStringList disallowedSubstGroup;
     if (element->disallowedSubstitutions() & XsdElement::RestrictionConstraint)
         disallowedSubstGroup << QLatin1String("restriction");
     if (element->disallowedSubstitutions() & XsdElement::ExtensionConstraint)
         disallowedSubstGroup << QLatin1String("extension");
     if (element->disallowedSubstitutions() & XsdElement::SubstitutionConstraint)
         disallowedSubstGroup << QLatin1String("substitution");
     qDebug() << "Name:" << element->displayName(m_namePool);
     qDebug() << "IsAbstract:" << (element->isAbstract() ? "yes" : "no");
     qDebug() << "Type:" << element->type()->displayName(m_namePool);
     qDebug() << "DisallowedSubstitutionGroups:" << disallowedSubstGroup.join(QLatin1String("' "));
 }
dumpInheritance()
void XsdSchemaDebugger::dumpInheritance (const SchemaType::Ptr & type, int level = 0)
Dumps the inheritance path of the given type.
Parameters
type The type to dump.
level The level of indention.
Definition at line 80 of file qxsdschemadebugger.cpp.
Referenced by dumpType().
 {
     QString prefix; prefix.fill(QLatin1Char(' '), level);
     qDebug("%s-->%s", qPrintable(prefix), qPrintable(type->displayName(m_namePool)));
     if (type->wxsSuperType())
         dumpInheritance(type->wxsSuperType(), ++level);
 }
dumpParticle()
void XsdSchemaDebugger::dumpParticle (const XsdParticle::Ptr & particle, int level = 0)
Dumps the structure of the given particle.
Parameters
particle The particle to dump.
level The level of indention.
Definition at line 53 of file qxsdschemadebugger.cpp.
Referenced by dumpType().
 {
     QString prefix; prefix.fill(QLatin1Char(' '), level);
     qDebug("%s min=%s max=%s", qPrintable(prefix), qPrintable(QString::number(particle->minimumOccurs())),
                                qPrintable(particle->maximumOccursUnbounded() ? QLatin1String("unbounded") : QString::number(particle->maximumOccurs())));
     if (particle->term()->isElement()) {
         qDebug("%selement (%s)", qPrintable(prefix), qPrintable(XsdElement::Ptr(particle->term())->displayName(m_namePool)));
     } else if (particle->term()->isModelGroup()) {
         const XsdModelGroup::Ptr group(particle->term());
         if (group->compositor() == XsdModelGroup::SequenceCompositor) {
             qDebug("%ssequence", qPrintable(prefix));
         } else if (group->compositor() == XsdModelGroup::AllCompositor) {
             qDebug("%sall", qPrintable(prefix));
         } else if (group->compositor() == XsdModelGroup::ChoiceCompositor) {
             qDebug("%schoice", qPrintable(prefix));
         }
         for (int i = 0; i < group->particles().count(); ++i)
             dumpParticle(group->particles().at(i), level + 5);
     } else if (particle->term()->isWildcard()) {
         XsdWildcard::Ptr wildcard(particle->term());
         qDebug("%swildcard (process=%d)", qPrintable(prefix), wildcard->processContents());
     }
 }
dumpSchema()
void XsdSchemaDebugger::dumpSchema (const XsdSchema::Ptr & schema)
Dumps the structure of the complete schema.
Definition at line 183 of file qxsdschemadebugger.cpp.
 {
     qDebug() << "------------------------------ Schema -------------------------------";
     // elements
     {
         qDebug() << "Global Elements:";
         const XsdElement::List elements = schema->elements();
         for (int i = 0; i < elements.count(); ++i) {
             dumpElement(elements.at(i));
         }
     }
     // attributes
     {
         qDebug() << "Global Attributes:";
         const XsdAttribute::List attributes = schema->attributes();
         for (int i = 0; i < attributes.count(); ++i) {
             dumpAttribute(attributes.at(i));
         }
     }
     // types
     {
         qDebug() << "Global Types:";
         const SchemaType::List types = schema->types();
         for (int i = 0; i < types.count(); ++i) {
             dumpType(types.at(i));
         }
     }
     // anonymous types
     {
         qDebug() << "Anonymous Types:";
         const SchemaType::List types = schema->anonymousTypes();
         for (int i = 0; i < types.count(); ++i) {
             dumpType(types.at(i));
         }
     }
     qDebug() << "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++";
 }
dumpType()
void XsdSchemaDebugger::dumpType (const SchemaType::Ptr & type)
Dumps the structure of the given type.
Definition at line 107 of file qxsdschemadebugger.cpp.
Referenced by dumpSchema().
 {
     if (type->isComplexType()) {
         const XsdComplexType::Ptr complexType(type);
         qDebug("\n+++ Complex Type +++");
         qDebug("Name: %s (abstract: %s)", qPrintable(complexType->displayName(m_namePool)), complexType->isAbstract() ? "yes" : "no");
         if (complexType->wxsSuperType())
             qDebug("  base type: %s", qPrintable(complexType->wxsSuperType()->displayName(m_namePool)));
         else
             qDebug("  base type: (none)");
         if (complexType->contentType()->variety() == XsdComplexType::ContentType::Empty)
             qDebug("  content type: empty");
         if (complexType->contentType()->variety() == XsdComplexType::ContentType::Simple)
             qDebug("  content type: simple");
         if (complexType->contentType()->variety() == XsdComplexType::ContentType::ElementOnly)
             qDebug("  content type: element-only");
         if (complexType->contentType()->variety() == XsdComplexType::ContentType::Mixed)
             qDebug("  content type: mixed");
         if (complexType->contentType()->variety() == XsdComplexType::ContentType::Simple) {
             if (complexType->contentType()->simpleType())
                 qDebug("  simple type: %s", qPrintable(complexType->contentType()->simpleType()->displayName(m_namePool)));
             else
                 qDebug("  simple type: (none)");
         }
         const XsdAttributeUse::List uses = complexType->attributeUses();
         qDebug("   %d attributes", uses.count());
         for (int i = 0; i < uses.count(); ++i) {
             qDebug("      attr: %s", qPrintable(uses.at(i)->attribute()->displayName(m_namePool)));
         }
         qDebug("   has attribute wildcard: %s", complexType->attributeWildcard() ? "yes" : "no");
         if (complexType->attributeWildcard()) {
             dumpWildcard(complexType->attributeWildcard());
         }
         if (complexType->contentType()->particle()) {
             dumpParticle(complexType->contentType()->particle(), 5);
         }
     } else {
         qDebug("\n+++ Simple Type +++");
         qDebug("Name: %s", qPrintable(type->displayName(m_namePool)));
         if (type->isDefinedBySchema()) {
             const XsdSimpleType::Ptr simpleType(type);
             if (simpleType->primitiveType())
                 qDebug("  primitive type: %s", qPrintable(simpleType->primitiveType()->displayName(m_namePool)));
             else
                 qDebug("  primitive type: (none)");
         }
         dumpInheritance(type, 0);
     }
 }
dumpWildcard()
void XsdSchemaDebugger::dumpWildcard (const XsdWildcard::Ptr & wildcard)
Dumps the structure of the given wildcard.
Definition at line 88 of file qxsdschemadebugger.cpp.
Referenced by dumpType().
 {
     QVector<QString> varietyNames;
     varietyNames.append(QLatin1String("Any"));
     varietyNames.append(QLatin1String("Enumeration"));
     varietyNames.append(QLatin1String("Not"));
     QVector<QString> processContentsNames;
     processContentsNames.append(QLatin1String("Strict"));
     processContentsNames.append(QLatin1String("Lax"));
     processContentsNames.append(QLatin1String("Skip"));
     qDebug("      processContents: %s", qPrintable(processContentsNames.at((int)wildcard->processContents())));
     const XsdWildcard::NamespaceConstraint::Ptr constraint = wildcard->namespaceConstraint();
     qDebug("      variety: %s", qPrintable(varietyNames.at((int)constraint->variety())));
     if (constraint->variety() != XsdWildcard::NamespaceConstraint::Any)
         qDebug() << "      namespaces:" << constraint->namespaces();
 }
Properties
m_namePool
const NamePool::Ptr QPatternist::XsdSchemaDebugger::m_namePool private
Definition at line 118 of file qxsdschemadebugger_p.h.
Referenced by dumpAttribute(), dumpElement(), dumpInheritance(), dumpParticle(), and dumpType().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdschemadebugger_p.h
/src/xmlpatterns/schema/qxsdschemadebugger.cpp