Qt 4.8: QAbstractSocketEngineReceiver Class Reference
QAbstractSocketEngineReceiver Class Reference abstract
#include <qabstractsocketengine_p.h>
Public Functions
virtual void connectionNotification ()=0
virtual void exceptionNotification ()=0
virtual void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)=0
virtual void readNotification ()=0
virtual void writeNotification ()=0
virtual ~QAbstractSocketEngineReceiver ()
Detailed Description
Definition at line 69 of file qabstractsocketengine_p.h.
Constructors and Destructors
~QAbstractSocketEngineReceiver()
virtual QAbstractSocketEngineReceiver::~QAbstractSocketEngineReceiver () inline virtual
Definition at line 71 of file qabstractsocketengine_p.h.
 {}
Functions
connectionNotification()
virtual void QAbstractSocketEngineReceiver::connectionNotification () pure virtual
Implemented in QTcpServerPrivate, and QAbstractSocketPrivate.
Referenced by ~QAbstractSocketEngineReceiver().
exceptionNotification()
virtual void QAbstractSocketEngineReceiver::exceptionNotification () pure virtual
Implemented in QTcpServerPrivate, and QAbstractSocketPrivate.
Referenced by ~QAbstractSocketEngineReceiver().
proxyAuthenticationRequired()
virtual void QAbstractSocketEngineReceiver::proxyAuthenticationRequired (const QNetworkProxy & proxy, QAuthenticator * authenticator) pure virtual
Implemented in QTcpServerPrivate, and QAbstractSocketPrivate.
Referenced by ~QAbstractSocketEngineReceiver().
readNotification()
virtual void QAbstractSocketEngineReceiver::readNotification () pure virtual
Implemented in QTcpServerPrivate, and QAbstractSocketPrivate.
Referenced by ~QAbstractSocketEngineReceiver().
writeNotification()
virtual void QAbstractSocketEngineReceiver::writeNotification () pure virtual
Implemented in QTcpServerPrivate, and QAbstractSocketPrivate.
Referenced by ~QAbstractSocketEngineReceiver().
The documentation for this class was generated from the following file:
/src/network/socket/qabstractsocketengine_p.h