Qt 4.8: QGraphicsProxyWidgetPrivate Class Reference
QGraphicsProxyWidgetPrivate Class Reference
#include <qgraphicsproxywidget_p.h>
Public Types
enum ChangeMode { NoMode, ProxyToWidgetMode, WidgetToProxyMode }
Public Types inherited from QGraphicsWidgetPrivate
enum { Left, Top, Right, Bottom }
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Public Functions
void _q_removeWidgetSlot ()
void embedSubWindow (QWidget *)
Embeds subWin as a subwindow of this proxy widget.
QWidget * findFocusChild (QWidget *child, bool next) const
void init ()
QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
Reimplemented from QGraphicsItemPrivate.
bool isProxyWidget () const
QPointF mapToReceiver (const QPointF &pos, const QWidget *receiver) const
QGraphicsProxyWidgetPrivate ()
void removeSubFocusHelper (QWidget *widget, Qt::FocusReason reason)
void sendWidgetKeyEvent (QKeyEvent *event)
void sendWidgetMouseEvent (QGraphicsSceneMouseEvent *event)
void sendWidgetMouseEvent (QGraphicsSceneHoverEvent *event)
void setWidget_helper (QWidget *widget, bool autoShow)
void unembedSubWindow (QWidget *)
Removes ("unembeds") subWin and deletes the proxy holder item.
void updateProxyGeometryFromWidget ()
void updateProxyInputMethodAcceptanceFromWidget ()
void updateWidgetGeometryFromProxy ()
Public Functions inherited from QGraphicsWidgetPrivate
void _q_relayout ()
void adjustWindowFlags (Qt::WindowFlags *wFlags)
int attributeToBitIndex (Qt::WidgetAttribute att) const
void ensureMargins () const
Ensures that margins is allocated.
void ensureWindowData ()
Ensures that windowData is allocated.
void ensureWindowFrameMargins () const
Ensures that windowFrameMargins is allocated.
void fixFocusChainBeforeReparenting (QGraphicsWidget *newParent, QGraphicsScene *oldScene, QGraphicsScene *newScene=0)
bool hasDecoration () const
qreal height () const
void init (QGraphicsItem *parentItem, Qt::WindowFlags wFlags)
void initStyleOptionTitleBar (QStyleOptionTitleBar *option)
QFont naturalWidgetFont () const
QPalette naturalWidgetPalette () const
QGraphicsWidgetPrivate ()
void resetHeight ()
void resetWidth ()
void resolveFont (uint inheritedMask)
void resolveLayoutDirection ()
void resolvePalette (uint inheritedMask)
void setAttribute (Qt::WidgetAttribute att, bool value)
void setFont_helper (const QFont &font)
void setGeometryFromSetPos ()
void setHeight (qreal)
void setLayout_helper (QGraphicsLayout *l)
void setLayoutDirection_helper (Qt::LayoutDirection direction)
void setPalette_helper (const QPalette &palette)
void setWidth (qreal)
bool testAttribute (Qt::WidgetAttribute att) const
qreal titleBarHeight (const QStyleOptionTitleBar &options) const
void updateFont (const QFont &font)
void updatePalette (const QPalette &palette)
qreal width () const
void windowFrameHoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void windowFrameHoverMoveEvent (QGraphicsSceneHoverEvent *event)
void windowFrameMouseMoveEvent (QGraphicsSceneMouseEvent *event)
void windowFrameMousePressEvent (QGraphicsSceneMouseEvent *event)
void windowFrameMouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual ~QGraphicsWidgetPrivate ()
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
virtual void transformChanged ()
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Public Variables
QWidget * dragDropWidget
QPointer< QWidget > embeddedMouseGrabber
quint32 enabledChangeMode: 2
quint32 focusFromWidgetToProxy: 1
Qt::DropAction lastDropAction
QPointer< QWidget > lastWidgetUnderMouse
quint32 paletteChangeMode: 2
quint32 posChangeMode: 2
quint32 proxyIsGivingFocus: 1
quint32 sizeChangeMode: 2
quint32 styleChangeMode: 2
quint32 tooltipChangeMode: 2
quint32 visibleChangeMode: 2
QPointer< QWidget > widget
Public Variables inherited from QGraphicsWidgetPrivate
QList< QAction * > actions
quint32 attributes: 10
quint32 autoFillBackground: 1
QGraphicsWidget * focusNext
Qt::FocusPolicy focusPolicy
QGraphicsWidget * focusPrev
QFont font
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
quint32 inSetGeometry: 1
quint32 inSetPos: 1
QGraphicsLayout * layout
qreal * margins
quint32 padding: 2
QPalette palette
quint32 polished: 1
quint32 refCountInvokeRelayout: 16
bool setWindowFrameMargins
struct QGraphicsWidgetPrivate::WindowData * windowData
Qt::WindowFlags windowFlags
qreal * windowFrameMargins
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Additional Inherited Members
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Detailed Description
Definition at line 63 of file qgraphicsproxywidget_p.h.
Enumerations
ChangeMode
enum QGraphicsProxyWidgetPrivate::ChangeMode
Enumerator
NoMode
ProxyToWidgetMode
WidgetToProxyMode
Definition at line 110 of file qgraphicsproxywidget_p.h.
                     {
         NoMode,
         ProxyToWidgetMode,
         WidgetToProxyMode
     };
Constructors and Destructors
QGraphicsProxyWidgetPrivate()
QGraphicsProxyWidgetPrivate::QGraphicsProxyWidgetPrivate () inline
Definition at line 67 of file qgraphicsproxywidget_p.h.
         : dragDropWidget(0),
           posChangeMode(NoMode),
           sizeChangeMode(NoMode),
           visibleChangeMode(NoMode),
           enabledChangeMode(NoMode),
           styleChangeMode(NoMode),
           paletteChangeMode(NoMode),
           tooltipChangeMode(NoMode),
           focusFromWidgetToProxy(0)
     { }
Functions
_q_removeWidgetSlot()
void QGraphicsProxyWidgetPrivate::_q_removeWidgetSlot ()
Warning
This function is not part of the public interface.
Definition at line 413 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     Q_Q(QGraphicsProxyWidget);
     widget = 0;
     delete q;
 }
embedSubWindow()
void QGraphicsProxyWidgetPrivate::embedSubWindow (QWidget * subWin)
Embeds subWin as a subwindow of this proxy widget.
Warning
This function is not part of the public interface.
subWin must be a top-level widget and a descendant of the widget managed by this proxy. A separate subproxy will be created as a child of this proxy widget to manage subWin.
Definition at line 487 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     QWExtra *extra;
     if (!((extra = subWin->d_func()->extra) && extra->proxyWidget)) {
         QGraphicsProxyWidget *subProxy = new QGraphicsProxyWidget(q_func(), subWin->windowFlags());
         subProxy->d_func()->setWidget_helper(subWin, false);
     }
 }
findFocusChild()
QWidget * QGraphicsProxyWidgetPrivate::findFocusChild (QWidget * child, bool next) const
Warning
This function is not part of the public interface. Some of the logic is shared with QApplicationPrivate::focusNextPrevChild_helper
Definition at line 381 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     if (!widget)
         return 0;
     // Run around the focus chain until we find a widget that can take tab focus.
     if (!child) {
     child = next ? (QWidget *)widget : widget->d_func()->focus_prev;
     } else {
         child = next ? child->d_func()->focus_next : child->d_func()->focus_prev;
         if ((next && child == widget) || (!next && child == widget->d_func()->focus_prev)) {
              return 0;
         }
     }
     QWidget *oldChild = child;
     uint focus_flag = qt_tab_all_widgets ? Qt::TabFocus : Qt::StrongFocus;
     do {
         if (child->isEnabled()
         && child->isVisibleTo(widget)
             && ((child->focusPolicy() & focus_flag) == focus_flag)
             && !(child->d_func()->extra && child->d_func()->extra->focus_proxy)) {
             return child;
         }
         child = next ? child->d_func()->focus_next : child->d_func()->focus_prev;
     } while (child != oldChild && !(next && child == widget) && !(!next && child == widget->d_func()->focus_prev));
     return 0;
 }
init()
void QGraphicsProxyWidgetPrivate::init ()
Warning
This function is not part of the public interface.
Definition at line 195 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     Q_Q(QGraphicsProxyWidget);
     q->setFocusPolicy(Qt::WheelFocus);
     q->setAcceptDrops(true);
 }
inputMethodQueryHelper()
QVariant QGraphicsProxyWidgetPrivate::inputMethodQueryHelper (Qt::InputMethodQuery query) const virtual
Reimplemented from QGraphicsItemPrivate.
Warning
This function is not part of the public interface.
Qt 5: Move impl to
reimplementation QGraphicsProxyWidget::inputMethodQuery().
Reimplemented from QGraphicsItemPrivate.
Definition at line 347 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     Q_Q(const QGraphicsProxyWidget);
     if (!widget || !q->hasFocus())
         return QVariant();
     QWidget *focusWidget = widget->focusWidget();
     if (!focusWidget)
         focusWidget = widget;
     QVariant v = focusWidget->inputMethodQuery(query);
     QPointF focusWidgetPos = q->subWidgetRect(focusWidget).topLeft();
     switch (v.type()) {
     case QVariant::RectF:
         v = v.toRectF().translated(focusWidgetPos);
         break;
     case QVariant::PointF:
         v = v.toPointF() + focusWidgetPos;
         break;
     case QVariant::Rect:
         v = v.toRect().translated(focusWidgetPos.toPoint());
         break;
     case QVariant::Point:
         v = v.toPoint() + focusWidgetPos.toPoint();
         break;
     default:
         break;
     }
     return v;
 }
isProxyWidget()
bool QGraphicsProxyWidgetPrivate::isProxyWidget () const virtual
Warning
This function is not part of the public interface.
Tells us if it is a proxy widget
Reimplemented from QGraphicsItemPrivate.
Definition at line 522 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     return true;
 }
mapToReceiver()
QPointF QGraphicsProxyWidgetPrivate::mapToReceiver (const QPointF & pos, const QWidget * receiver) const
Warning
This function is not part of the public interface.
Definition at line 530 of file qgraphicsproxywidget.cpp.
Referenced by sendWidgetMouseEvent().
 {
     QPointF p = pos;
     // Map event position from us to the receiver, preserving its
     // precision (don't use QWidget::mapFrom here).
     while (receiver && receiver != widget) {
         p -= QPointF(receiver->pos());
         receiver = receiver->parentWidget();
     }
     return p;
 }
removeSubFocusHelper()
void QGraphicsProxyWidgetPrivate::removeSubFocusHelper (QWidget * widget, Qt::FocusReason reason)
Warning
This function is not part of the public interface.
Definition at line 329 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     QFocusEvent event(QEvent::FocusOut, reason);
     QPointer<QWidget> widgetGuard = widget;
     QApplication::sendEvent(widget, &event);
     if (widgetGuard && event.isAccepted())
         QApplication::sendEvent(widget->style(), &event);
 }
sendWidgetKeyEvent()
void QGraphicsProxyWidgetPrivate::sendWidgetKeyEvent (QKeyEvent * event)
Definition at line 307 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     Q_Q(QGraphicsProxyWidget);
     if (!event || !widget || !widget->isVisible())
         return;
     QPointer<QWidget> receiver = widget->focusWidget();
     if (!receiver)
         receiver = widget;
     Q_ASSERT(receiver);
     do {
         bool res = QApplication::sendEvent(receiver, event);
         if ((res && event->isAccepted()) || (q->isWindow() && receiver == widget))
             break;
         receiver = receiver->parentWidget();
     } while (receiver);
 }
sendWidgetMouseEvent() [1/2]
void QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent (QGraphicsSceneMouseEvent * event)
Warning
This function is not part of the public interface.
Definition at line 220 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate(), and sendWidgetMouseEvent().
 {
     if (!event || !widget || !widget->isVisible())
         return;
     Q_Q(QGraphicsProxyWidget);
     // Find widget position and receiver.
     QPointF pos = event->pos();
     QPointer<QWidget> alienWidget = widget->childAt(pos.toPoint());
     QPointer<QWidget> receiver =  alienWidget ? alienWidget : widget;
     if (QWidgetPrivate::nearestGraphicsProxyWidget(receiver) != q)
         return; //another proxywidget will handle the events
     // Translate QGraphicsSceneMouse events to QMouseEvents.
     QEvent::Type type = QEvent::None;
     switch (event->type()) {
     case QEvent::GraphicsSceneMousePress:
         type = QEvent::MouseButtonPress;
         if (!embeddedMouseGrabber)
             embeddedMouseGrabber = receiver;
         else
             receiver = embeddedMouseGrabber;
         break;
     case QEvent::GraphicsSceneMouseRelease:
         type = QEvent::MouseButtonRelease;
         if (embeddedMouseGrabber)
             receiver = embeddedMouseGrabber;
         break;
     case QEvent::GraphicsSceneMouseDoubleClick:
         type = QEvent::MouseButtonDblClick;
         if (!embeddedMouseGrabber)
             embeddedMouseGrabber = receiver;
         else
             receiver = embeddedMouseGrabber;
         break;
     case QEvent::GraphicsSceneMouseMove:
         type = QEvent::MouseMove;
         if (embeddedMouseGrabber)
             receiver = embeddedMouseGrabber;
         break;
     default:
         Q_ASSERT_X(false, "QGraphicsProxyWidget", "internal error");
         break;
     }
     if (!lastWidgetUnderMouse) {
         QApplicationPrivate::dispatchEnterLeave(embeddedMouseGrabber ? embeddedMouseGrabber : receiver, 0);
         lastWidgetUnderMouse = receiver;
     }
     // Map event position from us to the receiver
     pos = mapToReceiver(pos, receiver);
     // Send mouse event.
     QMouseEvent *mouseEvent = QMouseEvent::createExtendedMouseEvent(type, pos,
                                                                     receiver->mapToGlobal(pos.toPoint()), event->button(),
                                                                     event->buttons(), event->modifiers());
     QWidget *embeddedMouseGrabberPtr = (QWidget *)embeddedMouseGrabber;
     QApplicationPrivate::sendMouseEvent(receiver, mouseEvent, alienWidget, widget,
                                         &embeddedMouseGrabberPtr, lastWidgetUnderMouse, event->spontaneous());
     embeddedMouseGrabber = embeddedMouseGrabberPtr;
     // Handle enter/leave events when last button is released from mouse
     // grabber child widget.
     if (embeddedMouseGrabber && type == QEvent::MouseButtonRelease && !event->buttons()) {
         Q_Q(QGraphicsProxyWidget);
         if (q->rect().contains(event->pos()) && q->acceptsHoverEvents())
             lastWidgetUnderMouse = alienWidget ? alienWidget : widget;
         else // released on the frame our outside the item, or doesn't accept hover events.
             lastWidgetUnderMouse = 0;
         QApplicationPrivate::dispatchEnterLeave(lastWidgetUnderMouse, embeddedMouseGrabber);
         embeddedMouseGrabber = 0;
 #ifndef QT_NO_CURSOR
         // ### Restore the cursor, don't override it.
         if (!lastWidgetUnderMouse)
             q->unsetCursor();
 #endif
     }
     event->setAccepted(mouseEvent->isAccepted());
     delete mouseEvent;
 }
sendWidgetMouseEvent() [2/2]
void QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent (QGraphicsSceneHoverEvent * event)
Warning
This function is not part of the public interface.
Definition at line 205 of file qgraphicsproxywidget.cpp.
 {
     QGraphicsSceneMouseEvent mouseEvent(QEvent::GraphicsSceneMouseMove);
     mouseEvent.setPos(event->pos());
     mouseEvent.setScreenPos(event->screenPos());
     mouseEvent.setButton(Qt::NoButton);
     mouseEvent.setButtons(0);
     mouseEvent.setModifiers(event->modifiers());
     sendWidgetMouseEvent(&mouseEvent);
     event->setAccepted(mouseEvent.isAccepted());
 }
setWidget_helper()
void QGraphicsProxyWidgetPrivate::setWidget_helper (QWidget * widget, bool autoShow)
Definition at line 603 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     Q_Q(QGraphicsProxyWidget);
     if (newWidget == widget)
         return;
     if (widget) {
         QObject::disconnect(widget, SIGNAL(destroyed()), q, SLOT(_q_removeWidgetSlot()));
         widget->removeEventFilter(q);
         widget->setAttribute(Qt::WA_DontShowOnScreen, false);
         widget->d_func()->extra->proxyWidget = 0;
         resolveFont(inheritedFontResolveMask);
         resolvePalette(inheritedPaletteResolveMask);
         widget->update();
         foreach (QGraphicsItem *child, q->childItems()) {
             if (child->d_ptr->isProxyWidget()) {
                 QGraphicsProxyWidget *childProxy = static_cast<QGraphicsProxyWidget *>(child);
                 QWidget * parent = childProxy->widget();
                 while (parent->parentWidget() != 0) {
                     if (parent == widget)
                         break;
                     parent = parent->parentWidget();
                 }
                 if (!childProxy->widget() || parent != widget)
                     continue;
                 childProxy->setWidget(0);
                 delete childProxy;
             }
         }
         widget = 0;
 #ifndef QT_NO_CURSOR
         q->unsetCursor();
 #endif
         q->setAcceptHoverEvents(false);
         if (!newWidget)
             q->update();
     }
     if (!newWidget)
         return;
     if (!newWidget->isWindow()) {
         QWExtra *extra = newWidget->parentWidget()->d_func()->extra;
         if (!extra || !extra->proxyWidget)  {
             qWarning("QGraphicsProxyWidget::setWidget: cannot embed widget %p "
                      "which is not a toplevel widget, and is not a child of an embedded widget", newWidget);
             return;
         }
     }
     // Register this proxy within the widget's private.
     // ### This is a bit backdoorish
     QWExtra *extra = newWidget->d_func()->extra;
     if (!extra) {
         newWidget->d_func()->createExtra();
         extra = newWidget->d_func()->extra;
     }
     QGraphicsProxyWidget **proxyWidget = &extra->proxyWidget;
     if (*proxyWidget) {
         if (*proxyWidget != q) {
             qWarning("QGraphicsProxyWidget::setWidget: cannot embed widget %p"
                         "; already embedded", newWidget);
         }
         return;
     }
     *proxyWidget = q;
     newWidget->setAttribute(Qt::WA_DontShowOnScreen);
     newWidget->ensurePolished();
     // Do not wait for this widget to close before the app closes ###
     // shouldn't this widget inherit the attribute?
     newWidget->setAttribute(Qt::WA_QuitOnClose, false);
     q->setAcceptHoverEvents(true);
     if (newWidget->testAttribute(Qt::WA_NoSystemBackground))
         q->setAttribute(Qt::WA_NoSystemBackground);
     if (newWidget->testAttribute(Qt::WA_OpaquePaintEvent))
         q->setAttribute(Qt::WA_OpaquePaintEvent);
     widget = newWidget;
     // Changes only go from the widget to the proxy.
     enabledChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
     visibleChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
     posChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
     sizeChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
     if ((autoShow && !newWidget->testAttribute(Qt::WA_WState_ExplicitShowHide)) || !newWidget->testAttribute(Qt::WA_WState_Hidden)) {
         newWidget->show();
     }
     // Copy the state from the widget onto the proxy.
 #ifndef QT_NO_CURSOR
     if (newWidget->testAttribute(Qt::WA_SetCursor))
         q->setCursor(widget->cursor());
 #endif
     q->setEnabled(newWidget->isEnabled());
     q->setVisible(newWidget->isVisible());
     q->setLayoutDirection(newWidget->layoutDirection());
     if (newWidget->testAttribute(Qt::WA_SetStyle))
         q->setStyle(widget->style());
     resolveFont(inheritedFontResolveMask);
     resolvePalette(inheritedPaletteResolveMask);
     if (!newWidget->testAttribute(Qt::WA_Resized))
         newWidget->adjustSize();
     int left, top, right, bottom;
     newWidget->getContentsMargins(&left, &top, &right, &bottom);
     q->setContentsMargins(left, top, right, bottom);
     q->setWindowTitle(newWidget->windowTitle());
     // size policies and constraints..
     q->setSizePolicy(newWidget->sizePolicy());
     QSize sz = newWidget->minimumSize();
     q->setMinimumSize(sz.isNull() ? QSizeF() : QSizeF(sz));
     sz = newWidget->maximumSize();
     q->setMaximumSize(sz.isNull() ? QSizeF() : QSizeF(sz));
     updateProxyGeometryFromWidget();
     updateProxyInputMethodAcceptanceFromWidget();
     // Hook up the event filter to keep the state up to date.
     newWidget->installEventFilter(q);
     QObject::connect(newWidget, SIGNAL(destroyed()), q, SLOT(_q_removeWidgetSlot()));
     // Changes no longer go only from the widget to the proxy.
     enabledChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
     visibleChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
     posChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
     sizeChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
 }
unembedSubWindow()
void QGraphicsProxyWidgetPrivate::unembedSubWindow (QWidget * subWin)
Removes ("unembeds") subWin and deletes the proxy holder item.
Warning
This function is not part of the public interface.
This can happen when QWidget::setParent() reparents the embedded window out of "embedded space".
Definition at line 506 of file qgraphicsproxywidget.cpp.
Referenced by QGraphicsProxyWidgetPrivate().
 {
     foreach (QGraphicsItem *child, children) {
         if (child->isWidget()) {
             if (QGraphicsProxyWidget *proxy = qobject_cast<QGraphicsProxyWidget *>(static_cast<QGraphicsWidget *>(child))) {
                 if (proxy->widget() == subWin) {
                     proxy->setWidget(0);
                     scene->removeItem(proxy);
                     delete proxy;
                     return;
                 }
             }
         }
     }
 }
updateProxyGeometryFromWidget()
void QGraphicsProxyWidgetPrivate::updateProxyGeometryFromWidget ()
Warning
This function is not part of the public interface.
Definition at line 430 of file qgraphicsproxywidget.cpp.
 {
     Q_Q(QGraphicsProxyWidget);
     if (!widget)
         return;
     QRectF widgetGeometry = widget->geometry();
     QWidget *parentWidget = widget->parentWidget();
     if (widget->isWindow()) {
         QGraphicsProxyWidget *proxyParent = 0;
         if (parentWidget && (proxyParent = qobject_cast<QGraphicsProxyWidget *>(q->parentWidget()))) {
             // Nested window proxy (e.g., combobox popup), map widget to the
             // parent widget's global coordinates, and map that to the parent
             // proxy's child coordinates.
             widgetGeometry.moveTo(proxyParent->subWidgetRect(parentWidget).topLeft()
                                   + parentWidget->mapFromGlobal(widget->pos()));
         }
     }
     // Adjust to size hint if the widget has never been resized.
     if (!widget->size().isValid())
         widgetGeometry.setSize(widget->sizeHint());
     // Assign new geometry.
     posChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
     sizeChangeMode = QGraphicsProxyWidgetPrivate::WidgetToProxyMode;
     q->setGeometry(widgetGeometry);
     posChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
     sizeChangeMode = QGraphicsProxyWidgetPrivate::NoMode;
 }
updateProxyInputMethodAcceptanceFromWidget()
void QGraphicsProxyWidgetPrivate::updateProxyInputMethodAcceptanceFromWidget ()
Warning
This function is not part of the public interface.
Definition at line 464 of file qgraphicsproxywidget.cpp.
 {
     Q_Q(QGraphicsProxyWidget);
     if (!widget)
         return;
     QWidget *focusWidget = widget->focusWidget();
     if (!focusWidget)
         focusWidget = widget;
     q->setFlag(QGraphicsItem::ItemAcceptsInputMethod,
                focusWidget->testAttribute(Qt::WA_InputMethodEnabled));
 }
updateWidgetGeometryFromProxy()
void QGraphicsProxyWidgetPrivate::updateWidgetGeometryFromProxy ()
Warning
This function is not part of the public interface.
Definition at line 423 of file qgraphicsproxywidget.cpp.
 {
 }
Properties
dragDropWidget
QWidget* QGraphicsProxyWidgetPrivate::dragDropWidget
Definition at line 100 of file qgraphicsproxywidget_p.h.
embeddedMouseGrabber
QPointer<QWidget> QGraphicsProxyWidgetPrivate::embeddedMouseGrabber
Definition at line 99 of file qgraphicsproxywidget_p.h.
Referenced by sendWidgetMouseEvent().
enabledChangeMode
quint32 QGraphicsProxyWidgetPrivate::enabledChangeMode
Definition at line 118 of file qgraphicsproxywidget_p.h.
focusFromWidgetToProxy
quint32 QGraphicsProxyWidgetPrivate::focusFromWidgetToProxy
Definition at line 122 of file qgraphicsproxywidget_p.h.
lastDropAction
Qt::DropAction QGraphicsProxyWidgetPrivate::lastDropAction
Definition at line 101 of file qgraphicsproxywidget_p.h.
lastWidgetUnderMouse
QPointer<QWidget> QGraphicsProxyWidgetPrivate::lastWidgetUnderMouse
Definition at line 98 of file qgraphicsproxywidget_p.h.
Referenced by sendWidgetMouseEvent().
paletteChangeMode
quint32 QGraphicsProxyWidgetPrivate::paletteChangeMode
Definition at line 120 of file qgraphicsproxywidget_p.h.
posChangeMode
quint32 QGraphicsProxyWidgetPrivate::posChangeMode
Definition at line 115 of file qgraphicsproxywidget_p.h.
Referenced by updateProxyGeometryFromWidget().
proxyIsGivingFocus
quint32 QGraphicsProxyWidgetPrivate::proxyIsGivingFocus
Definition at line 123 of file qgraphicsproxywidget_p.h.
sizeChangeMode
quint32 QGraphicsProxyWidgetPrivate::sizeChangeMode
Definition at line 116 of file qgraphicsproxywidget_p.h.
Referenced by updateProxyGeometryFromWidget().
styleChangeMode
quint32 QGraphicsProxyWidgetPrivate::styleChangeMode
Definition at line 119 of file qgraphicsproxywidget_p.h.
tooltipChangeMode
quint32 QGraphicsProxyWidgetPrivate::tooltipChangeMode
Definition at line 121 of file qgraphicsproxywidget_p.h.
visibleChangeMode
quint32 QGraphicsProxyWidgetPrivate::visibleChangeMode
Definition at line 117 of file qgraphicsproxywidget_p.h.
widget
QPointer<QWidget> QGraphicsProxyWidgetPrivate::widget
Definition at line 97 of file qgraphicsproxywidget_p.h.
Referenced by _q_removeWidgetSlot(), findFocusChild(), inputMethodQueryHelper(), mapToReceiver(), QGraphicsProxyWidgetPrivate(), removeSubFocusHelper(), sendWidgetKeyEvent(), sendWidgetMouseEvent(), updateProxyGeometryFromWidget(), and updateProxyInputMethodAcceptanceFromWidget().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsproxywidget_p.h
/src/gui/graphicsview/qgraphicsproxywidget.cpp