Qt 4.8: QFactoryLoader Class Reference
QFactoryLoader Class Reference
#include <qfactoryloader_p.h>
Public Functions
QObject * instance (const QString &key) const
QStringList keys () const
QLibraryPrivate * library (const QString &key) const
QFactoryLoader (const char *iid, const QString &suffix=QString(), Qt::CaseSensitivity=Qt::CaseSensitive)
void update ()
void updateDir (const QString &pluginDir, QSettings &settings)
~QFactoryLoader ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void refreshAll ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qfactoryloader_p.h.
Constructors and Destructors
QFactoryLoader()
QFactoryLoader::QFactoryLoader (const char * iid, const QString & suffix = QString(), Qt::CaseSensitivity cs = Qt::CaseSensitive)
Definition at line 108 of file qfactoryloader.cpp.
     : QObject(*new QFactoryLoaderPrivate)
 {
     moveToThread(QCoreApplicationPrivate::mainThread());
     Q_D(QFactoryLoader);
     d->iid = iid;
     d->cs = cs;
     d->suffix = suffix;
     QMutexLocker locker(qt_factoryloader_mutex());
     update();
     qt_factory_loaders()->append(this);
 #ifdef Q_OS_SYMBIAN
     // kick off Symbian plugin watcher for updates
     qt_symbian_system_plugin_watcher();
 #endif
 }
~QFactoryLoader()
QFactoryLoader::~QFactoryLoader ()
Definition at line 244 of file qfactoryloader.cpp.
 {
     QMutexLocker locker(qt_factoryloader_mutex());
     qt_factory_loaders()->removeAll(this);
 }
Functions
instance()
QObject * QFactoryLoader::instance (const QString & key) const
Definition at line 263 of file qfactoryloader.cpp.
Referenced by QAudioDeviceFactory::availableDevices(), createForName(), createReadHandlerHelper(), if(), Q_GLOBAL_STATIC_WITH_ARGS(), qt_guiPlatformMenuBarFactory(), qt_guiPlatformPlugin(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QNetworkConfigurationManagerPrivate::updateConfigurations(), and updateDir().
 {
     Q_D(const QFactoryLoader);
     QMutexLocker locker(&d->mutex);
     QObjectList instances = QPluginLoader::staticInstances();
     for (int i = 0; i < instances.count(); ++i)
         if (QFactoryInterface *factory = qobject_cast<QFactoryInterface*>(instances.at(i)))
             if (instances.at(i)->qt_metacast(d->iid) && factory->keys().contains(key, Qt::CaseInsensitive))
                 return instances.at(i);
     QString lowered = d->cs ? key : key.toLower();
     if (QLibraryPrivate* library = d->keyMap.value(lowered)) {
         if (library->instance || library->loadPlugin()) {
             if (QObject *obj = library->instance()) {
                 if (obj && !obj->parent())
                     obj->moveToThread(QCoreApplicationPrivate::mainThread());
                 return obj;
             }
         }
     }
     return 0;
 }
keys()
QStringList QFactoryLoader::keys () const
Definition at line 250 of file qfactoryloader.cpp.
Referenced by QTextCodec::availableCodecs(), QAudioDeviceFactory::availableDevices(), QTextCodec::availableMibs(), createForName(), createReadHandlerHelper(), QIconLoader::ensureInitialized(), Q_GLOBAL_STATIC_WITH_ARGS(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QNetworkConfigurationManagerPrivate::updateConfigurations(), and updateDir().
 {
     Q_D(const QFactoryLoader);
     QMutexLocker locker(&d->mutex);
     QStringList keys = d->keyList;
     QObjectList instances = QPluginLoader::staticInstances();
     for (int i = 0; i < instances.count(); ++i)
         if (QFactoryInterface *factory = qobject_cast<QFactoryInterface*>(instances.at(i)))
             if (instances.at(i)->qt_metacast(d->iid))
                 keys += factory->keys();
     return keys;
 }
library()
QLibraryPrivate * QFactoryLoader::library (const QString & key) const
Definition at line 287 of file qfactoryloader.cpp.
Referenced by instance(), and updateDir().
 {
     Q_D(const QFactoryLoader);
     return d->keyMap.value(d->cs ? key : key.toLower());
 }
refreshAll()
void QFactoryLoader::refreshAll () static
Definition at line 294 of file qfactoryloader.cpp.
Referenced by QCoreApplication::addLibraryPath(), QCoreApplication::QCoreApplication(), QCoreApplication::removeLibraryPath(), and QCoreApplication::setLibraryPaths().
 {
     QMutexLocker locker(qt_factoryloader_mutex());
     QList<QFactoryLoader *> *loaders = qt_factory_loaders();
     for (QList<QFactoryLoader *>::const_iterator it = loaders->constBegin();
          it != loaders->constEnd(); ++it) {
         (*it)->update();
     }
 }
update()
void QFactoryLoader::update ()
Definition at line 221 of file qfactoryloader.cpp.
Referenced by QFactoryLoader(), and QWidget::setContentsMargins().
 {
 #ifdef QT_SHARED
     Q_D(QFactoryLoader);
     QStringList paths = QCoreApplication::libraryPaths();
     QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
     for (int i = 0; i < paths.count(); ++i) {
         const QString &pluginDir = paths.at(i);
         // Already loaded, skip it...
         if (d->loadedPaths.contains(pluginDir))
             continue;
         d->loadedPaths << pluginDir;
         updateDir(pluginDir, settings);
     }
 #else
     Q_D(QFactoryLoader);
     if (qt_debug_component()) {
         qDebug() << "QFactoryLoader::QFactoryLoader() ignoring" << d->iid
                  << "since plugins are disabled in static builds";
     }
 #endif
 }
updateDir()
void QFactoryLoader::updateDir (const QString & pluginDir, QSettings & settings)
Definition at line 130 of file qfactoryloader.cpp.
Referenced by update().
 {
     Q_D(QFactoryLoader);
     QString path = pluginDir + d->suffix;
     if (!QDir(path).exists(QLatin1String(".")))
         return;
     QStringList plugins = QDir(path).entryList(QDir::Files);
     QLibraryPrivate *library = 0;
     for (int j = 0; j < plugins.count(); ++j) {
         QString fileName = QDir::cleanPath(path + QLatin1Char('/') + plugins.at(j));
         if (qt_debug_component()) {
             qDebug() << "QFactoryLoader::QFactoryLoader() looking at" << fileName;
         }
         library = QLibraryPrivate::findOrCreate(QFileInfo(fileName).canonicalFilePath());
         if (!library->isPlugin(&settings)) {
             if (qt_debug_component()) {
                 qDebug() << library->errorString;
                 qDebug() << "         not a plugin";
             }
             library->release();
             continue;
         }
         QString regkey = QString::fromLatin1("Qt Factory Cache %1.%2/%3:/%4")
                          .arg((QT_VERSION & 0xff0000) >> 16)
                          .arg((QT_VERSION & 0xff00) >> 8)
                          .arg(QLatin1String(d->iid))
                          .arg(fileName);
         QStringList reg, keys;
         reg = settings.value(regkey).toStringList();
         if (reg.count() && library->lastModified == reg[0]) {
             keys = reg;
             keys.removeFirst();
         } else {
             if (!library->loadPlugin()) {
                 if (qt_debug_component()) {
                     qDebug() << library->errorString;
                     qDebug() << "           could not load";
                 }
                 library->release();
                 continue;
             }
             QObject *instance = library->instance();
             if (!instance) {
                 library->release();
                 // ignore plugins that have a valid signature but cannot be loaded.
                 continue;
             }
             QFactoryInterface *factory = qobject_cast<QFactoryInterface*>(instance);
             if (instance && factory && instance->qt_metacast(d->iid))
                 keys = factory->keys();
             if (keys.isEmpty())
                 library->unload();
             reg.clear();
             reg << library->lastModified;
             reg += keys;
             settings.setValue(regkey, reg);
         }
         if (qt_debug_component()) {
             qDebug() << "keys" << keys;
         }
         if (keys.isEmpty()) {
             library->release();
             continue;
         }
         int keysUsed = 0;
         for (int k = 0; k < keys.count(); ++k) {
             // first come first serve, unless the first
             // library was built with a future Qt version,
             // whereas the new one has a Qt version that fits
             // better
             QString key = keys.at(k);
             if (!d->cs)
                 key = key.toLower();
             QLibraryPrivate *previous = d->keyMap.value(key);
             if (!previous || (previous->qt_version > QT_VERSION && library->qt_version <= QT_VERSION)) {
                 d->keyMap[key] = library;
                 d->keyList += keys.at(k);
                 keysUsed++;
             }
         }
         if (keysUsed)
             d->libraryList += library;
         else
             library->release();
     }
 }
The documentation for this class was generated from the following files:
/src/corelib/plugin/qfactoryloader_p.h
/src/corelib/plugin/qfactoryloader.cpp