Qt 4.8: QGLSharedResourceGuard Class Reference
QGLSharedResourceGuard Class Reference
#include <qgl_p.h>
Public Functions
const QGLContext * context () const
GLuint id () const
QGLSharedResourceGuard (const QGLContext *context)
QGLSharedResourceGuard (const QGLContext *context, GLuint id)
void setId (GLuint id)
~QGLSharedResourceGuard ()
void setContext (const QGLContext *context)
Properties
QGLContextGroup * m_group
GLuint m_id
QGLSharedResourceGuard * m_next
QGLSharedResourceGuard * m_prev
Friends
class QGLContextGroup
Detailed Description
Definition at line 858 of file qgl_p.h.
Constructors and Destructors
QGLSharedResourceGuard() [1/2]
QGLSharedResourceGuard::QGLSharedResourceGuard (const QGLContext * context) inline
Definition at line 861 of file qgl_p.h.
         : m_group(0), m_id(0), m_next(0), m_prev(0)
     {
         setContext(context);
     }
QGLSharedResourceGuard() [2/2]
QGLSharedResourceGuard::QGLSharedResourceGuard (const QGLContext * context, GLuint id) inline
Definition at line 866 of file qgl_p.h.
         : m_group(0), m_id(id), m_next(0), m_prev(0)
     {
         setContext(context);
     }
~QGLSharedResourceGuard()
QGLSharedResourceGuard::~QGLSharedResourceGuard ()
Definition at line 5977 of file qgl.cpp.
 {
     if (m_group)
         m_group->removeGuard(this);
 }
Functions
context()
const QGLContext* QGLSharedResourceGuard::context () const inline
Definition at line 873 of file qgl_p.h.
Referenced by QGLShaderPrivate::create(), QGLEngineSharedShaders::findProgramInCache(), and QGLShaderPrivate::~QGLShaderPrivate().
     {
         return m_group ? m_group->context() : 0;
     }
id()
GLuint QGLSharedResourceGuard::id () const inline
Definition at line 880 of file qgl_p.h.
Referenced by QGLShaderPrivate::compile(), QGLShaderPrivate::deleteShader(), QGLFramebufferObjectPrivate::fbo(), and QGLShaderPrivate::~QGLShaderPrivate().
     {
         return m_id;
     }
setContext()
void QGLSharedResourceGuard::setContext (const QGLContext * context)
Definition at line 5983 of file qgl.cpp.
 {
     if (m_group)
         m_group->removeGuard(this);
     if (context) {
         m_group = QGLContextPrivate::contextGroup(context);
         m_group->addGuard(this);
     } else {
         m_group = 0;
     }
 }
setId()
void QGLSharedResourceGuard::setId (GLuint id) inline
Definition at line 885 of file qgl_p.h.
Referenced by QGLShaderPrivate::create(), and QGLShaderPrivate::deleteShader().
     {
         m_id = id;
     }
Friends and Related Functions
QGLContextGroup
friend class QGLContextGroup friend
Definition at line 896 of file qgl_p.h.
Properties
m_group
QGLContextGroup* QGLSharedResourceGuard::m_group private
Definition at line 891 of file qgl_p.h.
m_id
GLuint QGLSharedResourceGuard::m_id private
Definition at line 892 of file qgl_p.h.
m_next
QGLSharedResourceGuard* QGLSharedResourceGuard::m_next private
Definition at line 893 of file qgl_p.h.
m_prev
QGLSharedResourceGuard* QGLSharedResourceGuard::m_prev private
Definition at line 894 of file qgl_p.h.
The documentation for this class was generated from the following files:
/src/opengl/qgl_p.h
/src/opengl/qgl.cpp