Qt 4.8: QTestCoreList< T > Class Template Reference
QTestCoreList< T > Class Template Reference
#include <qtestcorelist.h>
Public Functions
void addToList (T **list)
int count (T *list)
int count ()
T * nextElement ()
T * previousElement ()
QTestCoreList ()
virtual ~QTestCoreList ()
Properties
T * next
T * prev
Detailed Description
template<class T>
class QTestCoreList< T >
Definition at line 54 of file qtestcorelist.h.
Constructors and Destructors
QTestCoreList()
template<class T > QTestCoreList< T >::QTestCoreList ()
Definition at line 72 of file qtestcorelist.h.
 :next(0)
 ,prev(0)
 {
 }
~QTestCoreList()
template<class T > QTestCoreList< T >::~QTestCoreList () virtual
Definition at line 79 of file qtestcorelist.h.
 {
     if (prev) {
         prev->next = 0;
     }
     delete prev;
     if (next) {
         next->prev = 0;
     }
     delete next;
 }
Functions
addToList()
template<class T> void QTestCoreList< T >::addToList (T ** list)
Definition at line 93 of file qtestcorelist.h.
Referenced by QTestCoreElement< QTestElement >::addAttribute(), QTestElement::addLogElement(), and QTestLogger::enterTestFunction().
 {
     if (next)
         next->addToList(list);
     else {
         next = *list;
         if (next)
             next->prev = static_cast<T*>(this);
     }
     *list = static_cast<T*>(this);
 }
count() [1/2]
template<class T> int QTestCoreList< T >::count (T * list)
count() [2/2]
template<class T> int QTestCoreList< T >::count ()
Definition at line 119 of file qtestcorelist.h.
 {
     int numOfElements = 0;
     T *it = next;
     while(it){
         ++numOfElements;
         it = it->nextElement();
     }
     return numOfElements;
 }
nextElement()
template<class T > T * QTestCoreList< T >::nextElement ()
Definition at line 107 of file qtestcorelist.h.
Referenced by QTestCoreElement< QTestElement >::attribute(), QTestXmlStreamer::formatEnd(), QTestBasicStreamer::outputElementAttributes(), QTestXunitStreamer::outputElements(), QTestBasicStreamer::outputElements(), and QTestLogger::stopLogging().
 {
     return next;
 }
previousElement()
template<class T > T * QTestCoreList< T >::previousElement ()
Definition at line 113 of file qtestcorelist.h.
Referenced by QTestXunitStreamer::outputElements(), and QTestBasicStreamer::outputElements().
 {
     return prev;
 }
Properties
next
template<class T> T* QTestCoreList< T >::next private
Definition at line 67 of file qtestcorelist.h.
Referenced by QTestCoreList< ElementType >::addToList(), QTestCoreList< ElementType >::count(), QTestCoreList< ElementType >::nextElement(), and QTestCoreList< ElementType >::~QTestCoreList().
prev
template<class T> T* QTestCoreList< T >::prev private
Definition at line 68 of file qtestcorelist.h.
Referenced by QTestCoreList< ElementType >::previousElement(), and QTestCoreList< ElementType >::~QTestCoreList().
The documentation for this class was generated from the following file:
/src/testlib/qtestcorelist.h