Qt 4.8: QXlibMime Class Reference
QXlibMime Class Reference
#include <qxlibmime.h>
Public Functions
QXlibMime ()
~QXlibMime ()
Public Functions inherited from QInternalMimeData
QStringList formats () const
Returns a list of formats supported by the object.
bool hasFormat (const QString &mimeType) const
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
QInternalMimeData ()
~QInternalMimeData ()
Public Functions inherited from QMimeData
void clear ()
Removes all the MIME type and data entries in the object.
QVariant colorData () const
Returns a color if the data stored in the object represents a color (MIME type application/x-color); otherwise returns a null variant.
QByteArray data (const QString &mimetype) const
Returns the data stored in the object in the format described by the MIME type specified by mimeType.
bool hasColor () const
Returns true if the object can return a color (MIME type application/x-color); otherwise returns false.
bool hasHtml () const
Returns true if the object can return HTML (MIME type text/html); otherwise returns false.
bool hasImage () const
Returns true if the object can return an image; otherwise returns false.
bool hasText () const
Returns true if the object can return plain text (MIME type text/plain); otherwise returns false.
bool hasUrls () const
Returns true if the object can return a list of urls; otherwise returns false.
QString html () const
Returns a string if the data stored in the object is HTML (MIME type text/html); otherwise returns an empty string.
QVariant imageData () const
Returns a QVariant storing a QImage if the object can return an image; otherwise returns a null variant.
QMimeData ()
Constructs a new MIME data object with no data in it.
void removeFormat (const QString &mimetype)
Removes the data entry for mimeType in the object.
void setColorData (const QVariant &color)
Sets the color data in the object to the given color.
void setData (const QString &mimetype, const QByteArray &data)
Sets the data associated with the MIME type given by mimeType to the specified data.
void setHtml (const QString &html)
Sets html as the HTML (MIME type text/html) used to represent the data.
void setImageData (const QVariant &image)
Sets the data in the object to the given image.
void setText (const QString &text)
Sets text as the plain text (MIME type text/plain) used to represent the data.
void setUrls (const QList< QUrl > &urls)
Sets the URLs stored in the MIME data object to those specified by urls.
QString text () const
Returns a plain text (MIME type text/plain) representation of the data.
QList< QUrl > urls () const
Returns a list of URLs contained within the MIME data object.
~QMimeData ()
Destroys the MIME data object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static Atom mimeAtomForFormat (Display *display, const QString &format, QVariant::Type requestedType, const QList< Atom > &atoms, QByteArray *requestedEncoding)
static QList< Atom > mimeAtomsForFormat (Display *display, const QString &format)
static QString mimeAtomToString (Display *display, Atom a)
static QVariant mimeConvertToFormat (Display *display, Atom a, const QByteArray &data, const QString &format, QVariant::Type requestedType, const QByteArray &encoding)
static bool mimeDataForAtom (Display *display, Atom a, QMimeData *mimeData, QByteArray *data, Atom *atomFormat, int *dataFormat)
static QStringList mimeFormatsForAtom (Display *display, Atom a)
static Atom mimeStringToAtom (Display *display, const QString &mimeType)
Static Public Functions inherited from QInternalMimeData
static bool canReadData (const QString &mimeType)
static QStringList formatsHelper (const QMimeData *data)
static bool hasFormatHelper (const QString &mimeType, const QMimeData *data)
static QByteArray renderDataHelper (const QString &mimeType, const QMimeData *data)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QInternalMimeData
virtual QStringList formats_sys () const =0
virtual bool hasFormat_sys (const QString &mimeType) const =0
QVariant retrieveData (const QString &mimeType, QVariant::Type type) const
Returns a variant with the given type containing data for the MIME type specified by mimeType.
virtual QVariant retrieveData_sys (const QString &mimeType, QVariant::Type type) const =0
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 52 of file qxlibmime.h.
Constructors and Destructors
QXlibMime()
QXlibMime::QXlibMime ()
Definition at line 51 of file qxlibmime.cpp.
     : QInternalMimeData()
 { }
~QXlibMime()
QXlibMime::~QXlibMime ()
Definition at line 55 of file qxlibmime.cpp.
 {}
Functions
mimeAtomForFormat()
Atom QXlibMime::mimeAtomForFormat (Display * display, const QString & format, QVariant::Type requestedType, const QList< Atom > & atoms, QByteArray * requestedEncoding) static
Definition at line 269 of file qxlibmime.cpp.
 {
     requestedEncoding->clear();
     // find matches for string types
     if (format == QLatin1String("text/plain")) {
         if (atoms.contains(QXlibStatic::atom(QXlibStatic::UTF8_STRING)))
             return QXlibStatic::atom(QXlibStatic::UTF8_STRING);
         if (atoms.contains(QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT)))
             return QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT);
         if (atoms.contains(QXlibStatic::atom(QXlibStatic::TEXT)))
             return QXlibStatic::atom(QXlibStatic::TEXT);
         if (atoms.contains(XA_STRING))
             return XA_STRING;
     }
     // find matches for uri types
     if (format == QLatin1String("text/uri-list")) {
         Atom a = mimeStringToAtom(display,format);
         if (a && atoms.contains(a))
             return a;
         a = mimeStringToAtom(display,QLatin1String("text/x-moz-url"));
         if (a && atoms.contains(a))
             return a;
     }
     // find match for image
     if (format == QLatin1String("image/ppm")) {
         if (atoms.contains(XA_PIXMAP))
             return XA_PIXMAP;
     }
     // for string/text requests try to use a format with a well-defined charset
     // first to avoid encoding problems
     if (requestedType == QVariant::String
         && format.startsWith(QLatin1String("text/"))
         && !format.contains(QLatin1String("charset="))) {
         QString formatWithCharset = format;
         formatWithCharset.append(QLatin1String(";charset=utf-8"));
         Atom a = mimeStringToAtom(display,formatWithCharset);
         if (a && atoms.contains(a)) {
             *requestedEncoding = "utf-8";
             return a;
         }
     }
     Atom a = mimeStringToAtom(display,format);
     if (a && atoms.contains(a))
         return a;
     return 0;
 }
mimeAtomsForFormat()
QList< Atom > QXlibMime::mimeAtomsForFormat (Display * display, const QString & format) static
Definition at line 168 of file qxlibmime.cpp.
Referenced by QXlibClipboard::sendTargetsSelection().
 {
     QList<Atom> atoms;
     atoms.append(mimeStringToAtom(display, format));
     // special cases for strings
     if (format == QLatin1String("text/plain")) {
         atoms.append(QXlibStatic::atom(QXlibStatic::UTF8_STRING));
         atoms.append(XA_STRING);
         atoms.append(QXlibStatic::atom(QXlibStatic::TEXT));
         atoms.append(QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT));
     }
     // special cases for uris
     if (format == QLatin1String("text/uri-list")) {
         atoms.append(mimeStringToAtom(display,QLatin1String("text/x-moz-url")));
     }
     //special cases for images
     if (format == QLatin1String("image/ppm"))
         atoms.append(XA_PIXMAP);
     if (format == QLatin1String("image/pbm"))
         atoms.append(XA_BITMAP);
     return atoms;
 }
mimeAtomToString()
QString QXlibMime::mimeAtomToString (Display * display, Atom a) static
Definition at line 62 of file qxlibmime.cpp.
Referenced by mimeConvertToFormat(), mimeDataForAtom(), mimeFormatsForAtom(), and QXlibClipboard::sendSelection().
 {
     if (!a) return 0;
     if (a == XA_STRING || a == QXlibStatic::atom(QXlibStatic::UTF8_STRING)) {
         return "text/plain"; // some Xdnd clients are dumb
     }
     char *atom = XGetAtomName(display, a);
     QString result = QString::fromLatin1(atom);
     XFree(atom);
     return result;
 }
mimeConvertToFormat()
QVariant QXlibMime::mimeConvertToFormat (Display * display, Atom a, const QByteArray & data, const QString & format, QVariant::Type requestedType, const QByteArray & encoding) static
Definition at line 195 of file qxlibmime.cpp.
 {
     QString atomName = mimeAtomToString(display,a);
     if (atomName == format)
         return data;
     if (!encoding.isEmpty()
         && atomName == format + QLatin1String(";charset=") + QString::fromLatin1(encoding)) {
         if (requestedType == QVariant::String) {
             QTextCodec *codec = QTextCodec::codecForName(encoding);
             if (codec)
                 return codec->toUnicode(data);
         }
         return data;
     }
     // special cases for string types
     if (format == QLatin1String("text/plain")) {
         if (a == QXlibStatic::atom(QXlibStatic::UTF8_STRING))
             return QString::fromUtf8(data);
         if (a == XA_STRING)
             return QString::fromLatin1(data);
         if (a == QXlibStatic::atom(QXlibStatic::TEXT)
                 || a == QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT))
             // #### might be wrong for COMPUND_TEXT
             return QString::fromLocal8Bit(data, data.size());
     }
     // special case for uri types
     if (format == QLatin1String("text/uri-list")) {
         if (atomName == QLatin1String("text/x-moz-url")) {
             // we expect this as utf16 <url><space><title>
             // the first part is a url that should only contain ascci char
             // so it should be safe to check that the second char is 0
             // to verify that it is utf16
             if (data.size() > 1 && data.at(1) == 0)
                 return QString::fromRawData((const QChar *)data.constData(),
                                 data.size() / 2).split(QLatin1Char('\n')).first().toLatin1();
         }
     }
     // special cas for images
     if (format == QLatin1String("image/ppm")) {
         if (a == XA_PIXMAP && data.size() == sizeof(Pixmap)) {
             Pixmap xpm = *((Pixmap*)data.data());
             if (!xpm)
                 return QByteArray();
             Window root;
             int x;
             int y;
             uint width;
             uint height;
             uint border_width;
             uint depth;
             XGetGeometry(display, xpm, &root, &x, &y, &width, &height, &border_width, &depth);
             XImage *ximg = XGetImage(display,xpm,x,y,width,height,AllPlanes,depth==1 ? XYPixmap : ZPixmap);
             QImage qimg = QXlibStatic::qimageFromXImage(ximg);
             XDestroyImage(ximg);
             QImageWriter imageWriter;
             imageWriter.setFormat("PPMRAW");
             QBuffer buf;
             buf.open(QIODevice::WriteOnly);
             imageWriter.setDevice(&buf);
             imageWriter.write(qimg);
             return buf.buffer();
         }
     }
     return QVariant();
 }
mimeDataForAtom()
bool QXlibMime::mimeDataForAtom (Display * display, Atom a, QMimeData * mimeData, QByteArray * data, Atom * atomFormat, int * dataFormat) static
Definition at line 107 of file qxlibmime.cpp.
Referenced by QXlibClipboard::sendSelection().
 {
     bool ret = false;
     *atomFormat = a;
     *dataFormat = 8;
     QString atomName = mimeAtomToString(display, a);
     if (QInternalMimeData::hasFormatHelper(atomName, mimeData)) {
         *data = QInternalMimeData::renderDataHelper(atomName, mimeData);
         if (atomName == QLatin1String("application/x-color"))
             *dataFormat = 16;
         ret = true;
     } else {
         if ((a == QXlibStatic::atom(QXlibStatic::UTF8_STRING)
              || a == XA_STRING
              || a == QXlibStatic::atom(QXlibStatic::TEXT)
              || a == QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT))
             && QInternalMimeData::hasFormatHelper(QLatin1String("text/plain"), mimeData)) {
             if (a == QXlibStatic::atom(QXlibStatic::UTF8_STRING)){
                 *data = QInternalMimeData::renderDataHelper(QLatin1String("text/plain"), mimeData);
                 ret = true;
             } else if (a == XA_STRING) {
                 *data = QString::fromUtf8(QInternalMimeData::renderDataHelper(
                         QLatin1String("text/plain"), mimeData)).toLocal8Bit();
                 ret = true;
             } else if (a == QXlibStatic::atom(QXlibStatic::TEXT)
                        || a == QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT)) {
                 // the ICCCM states that TEXT and COMPOUND_TEXT are in the
                 // encoding of choice, so we choose the encoding of the locale
                 QByteArray strData = QString::fromUtf8(QInternalMimeData::renderDataHelper(
                                      QLatin1String("text/plain"), mimeData)).toLocal8Bit();
                 char *list[] = { strData.data(), NULL };
                 XICCEncodingStyle style = (a == QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT))
                                         ? XCompoundTextStyle : XStdICCTextStyle;
                 XTextProperty textprop;
                 if (list[0] != NULL
                     && XmbTextListToTextProperty(display, list, 1, style,
                                                  &textprop) == Success) {
                     *atomFormat = textprop.encoding;
                     *dataFormat = textprop.format;
                     *data = QByteArray((const char *) textprop.value, textprop.nitems * textprop.format / 8);
                     ret = true;
                     XFree(textprop.value);
                 }
             }
         } else if (atomName == QLatin1String("text/x-moz-url") &&
                    QInternalMimeData::hasFormatHelper(QLatin1String("text/uri-list"), mimeData)) {
             QByteArray uri = QInternalMimeData::renderDataHelper(
                              QLatin1String("text/uri-list"), mimeData).split('\n').first();
             QString mozUri = QString::fromLatin1(uri, uri.size());
             mozUri += QLatin1Char('\n');
             *data = QByteArray(reinterpret_cast<const char *>(mozUri.utf16()), mozUri.length() * 2);
             ret = true;
         } else if ((a == XA_PIXMAP || a == XA_BITMAP) && mimeData->hasImage()) {
             ret = true;
         }
     }
     return ret && data != 0;
 }
mimeFormatsForAtom()
QStringList QXlibMime::mimeFormatsForAtom (Display * display, Atom a) static
Definition at line 82 of file qxlibmime.cpp.
Referenced by QXlibClipboardMime::formats_sys().
 {
     QStringList formats;
     if (a) {
         QString atomName = mimeAtomToString(display, a);
         formats.append(atomName);
         // special cases for string type
         if (a == QXlibStatic::atom(QXlibStatic::UTF8_STRING)
                 || a == XA_STRING
                 || a == QXlibStatic::atom(QXlibStatic::TEXT)
                 || a == QXlibStatic::atom(QXlibStatic::COMPOUND_TEXT))
             formats.append(QLatin1String("text/plain"));
         // special cases for uris
         if (atomName == QLatin1String("text/x-moz-url"))
             formats.append(QLatin1String("text/uri-list"));
         // special case for images
         if (a == XA_PIXMAP)
             formats.append(QLatin1String("image/ppm"));
     }
     return formats;
 }
mimeStringToAtom()
Atom QXlibMime::mimeStringToAtom (Display * display, const QString & mimeType) static
Definition at line 75 of file qxlibmime.cpp.
Referenced by mimeAtomForFormat(), and mimeAtomsForFormat().
 {
     if (mimeType.isEmpty())
         return 0;
     return XInternAtom(display, mimeType.toLatin1().constData(), False);
 }
The documentation for this class was generated from the following files:
/src/plugins/platforms/xlib/qxlibmime.h
/src/plugins/platforms/xlib/qxlibmime.cpp