Qt 4.8: QTextDocumentWriter Class Reference
QTextDocumentWriter Class Reference
The QTextDocumentWriter class provides a format-independent interface for writing a QTextDocument to files or other devices.
#include <qtextdocumentwriter.h>
Public Functions
QTextCodec * codec () const
Returns the codec that is currently assigned to the writer.
QIODevice * device () const
Returns the device currently assigned, or 0 if no device has been assigned.
QString fileName () const
If the currently assigned device is a QFile, or if setFileName() has been called, this function returns the name of the file to be written to.
QByteArray format () const
Returns the format used for writing documents.
QTextDocumentWriter ()
Constructs an empty QTextDocumentWriter object.
QTextDocumentWriter (QIODevice *device, const QByteArray &format)
Constructs a QTextDocumentWriter object to write to the given device in the document format specified by format.
QTextDocumentWriter (const QString &fileName, const QByteArray &format=QByteArray())
Constructs an QTextDocumentWriter object that will write to a file with the name fileName, using the document format specified by format.
void setCodec (QTextCodec *codec)
Sets the codec for this stream to codec.
void setDevice (QIODevice *device)
Sets the writer's device to the device specified.
void setFileName (const QString &fileName)
Sets the name of the file to be written to fileName.
void setFormat (const QByteArray &format)
Sets the format used to write documents to the format specified.
bool write (const QTextDocument *document)
Writes the given document to the assigned device or file and returns true if successful; otherwise returns false.
bool write (const QTextDocumentFragment &fragment)
Writes the document fragment specified by fragment to the assigned device or file and returns true if successful; otherwise returns false.
~QTextDocumentWriter ()
Destroys the QTextDocumentWriter object.
Static Public Functions
static QList< QByteArray > supportedDocumentFormats ()
Returns the list of document formats supported by QTextDocumentWriter.
Properties
QTextDocumentWriterPrivate * d
Detailed Description
The QTextDocumentWriter class provides a format-independent interface for writing a QTextDocument to files or other devices.
Since
4.5
To write a document, construct a QTextDocumentWriter object with either a file name or a device object, and specify the document format to be written. You can construct a writer and set the format using setFormat() later.
Call write() to write the document to the device. If the document is successfully written, this function returns true. However, if an error occurs when writing the document, it will return false.
Call supportedDocumentFormats() for a list of formats that QTextDocumentWriter can write.
Since the capabilities of the supported output formats vary considerably, the writer simply outputs the appropriate subset of objects for each format. This typically includes the formatted text and images contained in a document.
Definition at line 58 of file qtextdocumentwriter.h.
Constructors and Destructors
QTextDocumentWriter() [1/3]
QTextDocumentWriter::QTextDocumentWriter ()
Constructs an empty QTextDocumentWriter object.
Before writing, you must call setFormat() to set a document format, then setDevice() or setFileName().
Definition at line 121 of file qtextdocumentwriter.cpp.
     : d(new QTextDocumentWriterPrivate(this))
 {
 }
QTextDocumentWriter() [2/3]
QTextDocumentWriter::QTextDocumentWriter (QIODevice * device, const QByteArray & format)
Constructs a QTextDocumentWriter object to write to the given device in the document format specified by format.
Definition at line 130 of file qtextdocumentwriter.cpp.
     : d(new QTextDocumentWriterPrivate(this))
 {
     d->device = device;
     d->format = format;
 }
QTextDocumentWriter() [3/3]
QTextDocumentWriter::QTextDocumentWriter (const QString & fileName, const QByteArray & format = QByteArray())
Constructs an QTextDocumentWriter object that will write to a file with the name fileName, using the document format specified by format.
If format is not provided, QTextDocumentWriter will detect the document format by inspecting the extension of fileName.
Definition at line 143 of file qtextdocumentwriter.cpp.
     : d(new QTextDocumentWriterPrivate(this))
 {
     QFile *file = new QFile(fileName);
     d->device = file;
     d->deleteDevice = true;
     d->format = format;
 }
~QTextDocumentWriter()
QTextDocumentWriter::~QTextDocumentWriter ()
Destroys the QTextDocumentWriter object.
Definition at line 155 of file qtextdocumentwriter.cpp.
 {
     if (d->deleteDevice)
         delete d->device;
     delete d;
 }
Functions
codec()
QTextCodec * QTextDocumentWriter::codec () const
Returns the codec that is currently assigned to the writer.
Definition at line 338 of file qtextdocumentwriter.cpp.
Referenced by setCodec().
 {
     return d->codec;
 }
device()
QIODevice * QTextDocumentWriter::device () const
Returns the device currently assigned, or 0 if no device has been assigned.
Definition at line 215 of file qtextdocumentwriter.cpp.
Referenced by QTextDocumentWriter(), and setDevice().
 {
     return d->device;
 }
fileName()
QString QTextDocumentWriter::fileName () const
If the currently assigned device is a QFile, or if setFileName() has been called, this function returns the name of the file to be written to.
In all other cases, it returns an empty string.
See also
setFileName(), setDevice()
Definition at line 239 of file qtextdocumentwriter.cpp.
 {
     QFile *file = qobject_cast<QFile *>(d->device);
     return file ? file->fileName() : QString();
 }
format()
QByteArray QTextDocumentWriter::format () const
Returns the format used for writing documents.
See also
setFormat()
Definition at line 183 of file qtextdocumentwriter.cpp.
Referenced by QTextDocumentWriter(), and setFormat().
 {
     return d->format;
 }
setCodec()
void QTextDocumentWriter::setCodec (QTextCodec * codec)
Sets the codec for this stream to codec.
The codec is used for encoding any data that is written. By default, QTextDocumentWriter uses UTF-8.
Definition at line 325 of file qtextdocumentwriter.cpp.
 {
     if (codec == 0)
         codec = QTextCodec::codecForName("UTF-8");
     Q_ASSERT(codec);
     d->codec = codec;
 }
setDevice()
void QTextDocumentWriter::setDevice (QIODevice * device)
Sets the writer's device to the device specified.
If a device has already been set, the old device is removed but otherwise left unchanged.
If the device is not already open, QTextDocumentWriter will attempt to open the device in QIODevice::WriteOnly mode by calling open().
Note
This will not work for certain devices, such as QProcess, QTcpSocket and QUdpSocket, where some configuration is required before the device can be opened.
See also
device(), setFileName()
Definition at line 202 of file qtextdocumentwriter.cpp.
Referenced by setFileName().
 {
     if (d->device && d->deleteDevice)
         delete d->device;
     d->device = device;
     d->deleteDevice = false;
 }
setFileName()
void QTextDocumentWriter::setFileName (const QString & fileName)
Sets the name of the file to be written to fileName.
Internally, QTextDocumentWriter will create a QFile and open it in QIODevice::WriteOnly mode, and use this file when writing the document.
See also
fileName(), setDevice()
Definition at line 226 of file qtextdocumentwriter.cpp.
 {
     setDevice(new QFile(fileName));
     d->deleteDevice = true;
 }
setFormat()
void QTextDocumentWriter::setFormat (const QByteArray & format)
Sets the format used to write documents to the format specified.
format is a case insensitive text string. For example:
        QTextDocumentWriter writer;
        writer.setFormat("odf"); // same as writer.setFormat("ODF");
You can call supportedDocumentFormats() for the full list of formats QTextDocumentWriter supports.
See also
format()
Definition at line 173 of file qtextdocumentwriter.cpp.
 {
     d->format = format;
 }
supportedDocumentFormats()
QList< QByteArray > QTextDocumentWriter::supportedDocumentFormats () static
Returns the list of document formats supported by QTextDocumentWriter.
By default, Qt can write the following formats:
Format Description
plaintext Plain text
HTML HyperText Markup Language
ODF OpenDocument Format
See also
setFormat()
Definition at line 358 of file qtextdocumentwriter.cpp.
 {
     QList<QByteArray> answer;
     answer << "plaintext";
 #ifndef QT_NO_TEXTHTMLPARSER
     answer << "HTML";
 #endif
 #ifndef QT_NO_TEXTODFWRITER
     answer << "ODF";
 #endif // QT_NO_TEXTODFWRITER
     qSort(answer);
     return answer;
 }
write() [1/2]
bool QTextDocumentWriter::write (const QTextDocument * document)
Writes the given document to the assigned device or file and returns true if successful; otherwise returns false.
Definition at line 249 of file qtextdocumentwriter.cpp.
Referenced by QTextEditMimeData::setup(), and write().
 {
     QByteArray suffix;
     if (d->device && d->format.isEmpty()) {
         // if there's no format, see if device is a file, and if so, find
         // the file suffix
         if (QFile *file = qobject_cast<QFile *>(d->device))
             suffix = QFileInfo(file->fileName()).suffix().toLower().toLatin1();
     }
     QByteArray format = !d->format.isEmpty() ? d->format.toLower() : suffix;
 #ifndef QT_NO_TEXTODFWRITER
     if (format == "odf" || format == "opendocumentformat" || format == "odt") {
         QTextOdfWriter writer(*document, d->device);
 #ifndef QT_NO_TEXTCODEC
         writer.setCodec(d->codec);
 #endif
         return writer.writeAll();
     }
 #endif // QT_NO_TEXTODFWRITER
 #ifndef QT_NO_TEXTHTMLPARSER
     if (format == "html" || format == "htm") {
         if (!d->device->isWritable() && ! d->device->open(QIODevice::WriteOnly)) {
             qWarning() << "QTextDocumentWriter::write: the device can not be opened for writing";
             return false;
         }
         QTextStream ts(d->device);
 #ifndef QT_NO_TEXTCODEC
         ts.setCodec(d->codec);
         ts << document->toHtml(d->codec->name());
 #endif
         d->device->close();
         return true;
     }
 #endif
     if (format == "txt" || format == "plaintext") {
         if (!d->device->isWritable() && ! d->device->open(QIODevice::WriteOnly)) {
             qWarning() << "QTextDocumentWriter::write: the device can not be opened for writing";
             return false;
         }
         QTextStream ts(d->device);
 #ifndef QT_NO_TEXTCODEC
         ts.setCodec(d->codec);
 #endif
         ts << document->toPlainText();
         d->device->close();
         return true;
     }
     return false;
 }
write() [2/2]
bool QTextDocumentWriter::write (const QTextDocumentFragment & fragment)
Writes the document fragment specified by fragment to the assigned device or file and returns true if successful; otherwise returns false.
Definition at line 308 of file qtextdocumentwriter.cpp.
 {
     if (fragment.d == 0)
         return false; // invalid fragment.
     QTextDocument *doc = fragment.d->doc;
     if (doc)
         return write(doc);
     return false;
 }
Properties
d
QTextDocumentWriterPrivate* QTextDocumentWriter::d private
Definition at line 86 of file qtextdocumentwriter.h.
Referenced by codec(), device(), fileName(), format(), QTextDocumentWriter(), setCodec(), setDevice(), setFileName(), setFormat(), write(), and ~QTextDocumentWriter().
The documentation for this class was generated from the following files:
/src/gui/text/qtextdocumentwriter.h
/src/gui/text/qtextdocumentwriter.cpp