Qt 4.8: QItemEditorFactory Class Reference
QItemEditorFactory Class Reference
The QItemEditorFactory class provides widgets for editing item data in views and delegates.
#include <qitemeditorfactory.h>
Public Functions
virtual QWidget * createEditor (QVariant::Type type, QWidget *parent) const
Creates an editor widget with the given parent for the specified type of data, and returns it as a QWidget.
QItemEditorFactory ()
Constructs a new item editor factory.
void registerEditor (QVariant::Type type, QItemEditorCreatorBase *creator)
Registers an item editor creator specified by creator for the given type of data.
virtual QByteArray valuePropertyName (QVariant::Type type) const
Returns the property name used to access data for the given type of data.
virtual ~QItemEditorFactory ()
Destroys the item editor factory.
Static Public Functions
static const QItemEditorFactory * defaultFactory ()
Returns the default item editor factory.
static void setDefaultFactory (QItemEditorFactory *factory)
Sets the default item editor factory to the given factory.
Properties
QHash< QVariant::Type, QItemEditorCreatorBase * > creatorMap
Detailed Description
The QItemEditorFactory class provides widgets for editing item data in views and delegates.
Since
4.2
When editing data in an item view, editors are created and displayed by a delegate. QItemDelegate, which is the delegate by default installed on Qt's item views, uses a QItemEditorFactory to create editors for it. A default unique instance provided by QItemEditorFactory is used by all item delegates. If you set a new default factory with setDefaultFactory(), the new factory will be used by existing and new delegates.
A factory keeps a collection of QItemEditorCreatorBase instances, which are specialized editors that produce editors for one particular QVariant data type (All Qt models store their data in QVariant).
Standard Editing Widgets
The standard factory implementation provides editors for a variety of data types. These are created whenever a delegate needs to provide an editor for data supplied by a model. The following table shows the relationship between types and the standard editors provided.
Type Editor Widget
bool QComboBox
double QDoubleSpinBox
int QSpinBox
unsigned int
QDate QDateEdit
QDateTime QDateTimeEdit
QPixmap QLabel
QString QLineEdit
QTime QTimeEdit
Additional editors can be registered with the registerEditor() function.
See also
QItemDelegate, {Model/View Programming}, {Color Editor Factory Example}
Definition at line 100 of file qitemeditorfactory.h.
Constructors and Destructors
QItemEditorFactory()
QItemEditorFactory::QItemEditorFactory () inline
Constructs a new item editor factory.
Definition at line 103 of file qitemeditorfactory.h.
 {}
~QItemEditorFactory()
QItemEditorFactory::~QItemEditorFactory () virtual
Destroys the item editor factory.
Definition at line 165 of file qitemeditorfactory.cpp.
 {
     //we make sure we delete all the QItemEditorCreatorBase
     //this has to be done only once, hence the QSet
     QSet<QItemEditorCreatorBase*> set = creatorMap.values().toSet();
     qDeleteAll(set);
 }
Functions
createEditor()
QWidget * QItemEditorFactory::createEditor (QVariant::Type type, QWidget * parent) const virtual
Creates an editor widget with the given parent for the specified type of data, and returns it as a QWidget.
See also
registerEditor()
Reimplemented in QDefaultItemEditorFactory.
Definition at line 139 of file qitemeditorfactory.cpp.
Referenced by QItemDelegate::createEditor(), and createEditor().
 {
     QItemEditorCreatorBase *creator = creatorMap.value(type, 0);
     if (!creator) {
         const QItemEditorFactory *dfactory = defaultFactory();
         return dfactory == this ? 0 : dfactory->createEditor(type, parent);
     }
     return creator->createWidget(parent);
 }
defaultFactory()
const QItemEditorFactory * QItemEditorFactory::defaultFactory () static
Returns the default item editor factory.
See also
setDefaultFactory()
Definition at line 306 of file qitemeditorfactory.cpp.
Referenced by QItemDelegate::createEditor(), QItemDelegatePrivate::editorFactory(), and QStyledItemDelegatePrivate::editorFactory().
 {
     static const QDefaultItemEditorFactory factory;
     if (q_default_factory)
         return q_default_factory;
     return &factory;
 }
registerEditor()
void QItemEditorFactory::registerEditor (QVariant::Type type, QItemEditorCreatorBase * creator)
Registers an item editor creator specified by creator for the given type of data.
Note: The factory takes ownership of the item editor creator and will destroy it if a new creator for the same type is registered later.
See also
createEditor()
Definition at line 181 of file qitemeditorfactory.cpp.
 {
     QHash<QVariant::Type, QItemEditorCreatorBase *>::iterator it = creatorMap.find(type);
     if (it != creatorMap.end()) {
         QItemEditorCreatorBase *oldCreator = it.value();
         Q_ASSERT(oldCreator);
         creatorMap.erase(it);
         if (!creatorMap.values().contains(oldCreator))
             delete oldCreator; // if it is no more in use we can delete it
     }
     creatorMap[type] = creator;
 }
setDefaultFactory()
void QItemEditorFactory::setDefaultFactory (QItemEditorFactory * factory) static
Sets the default item editor factory to the given factory.
Both new and existing delegates will use the new factory.
See also
defaultFactory()
Definition at line 320 of file qitemeditorfactory.cpp.
 {
     static const QDefaultFactoryCleaner cleaner;
     delete q_default_factory;
     q_default_factory = factory;
 }
valuePropertyName()
QByteArray QItemEditorFactory::valuePropertyName (QVariant::Type type) const virtual
Returns the property name used to access data for the given type of data.
Reimplemented in QDefaultItemEditorFactory.
Definition at line 152 of file qitemeditorfactory.cpp.
Referenced by valuePropertyName().
 {
     QItemEditorCreatorBase *creator = creatorMap.value(type, 0);
     if (!creator) {
         const QItemEditorFactory *dfactory = defaultFactory();
         return dfactory == this ? QByteArray() : dfactory->valuePropertyName(type);
     }
     return creator->valuePropertyName();
 }
Properties
creatorMap
QHash<QVariant::Type, QItemEditorCreatorBase *> QItemEditorFactory::creatorMap private
Definition at line 115 of file qitemeditorfactory.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qitemeditorfactory.h
/src/gui/itemviews/qitemeditorfactory.cpp