Qt 4.8: QTextFrame Class Reference
QTextFrame Class Reference
The QTextFrame class represents a frame in a QTextDocument.
#include <qtextobject.h>
Classes
class iterator
The iterator class provides an iterator for reading the contents of a QTextFrame.
Public Types
typedef iterator Iterator
Qt-style synonym for QTextFrame::iterator.
Public Functions
iterator begin () const
Returns an iterator pointing to the first document element inside the frame.
QList< QTextFrame * > childFrames () const
Returns a (possibly empty) list of the frame's child frames.
iterator end () const
Returns an iterator pointing to the position past the last document element inside the frame.
QTextCursor firstCursorPosition () const
Returns the first cursor position inside the frame.
int firstPosition () const
Returns the first document position inside the frame.
QTextFrameFormat frameFormat () const
Returns the frame's format.
QTextCursor lastCursorPosition () const
Returns the last cursor position inside the frame.
int lastPosition () const
Returns the last document position inside the frame.
QTextFrameLayoutData * layoutData () const
QTextFrame * parentFrame () const
Returns the frame's parent frame.
QTextFrame (QTextDocument *doc)
Creates a new empty frame for the text document.
void setFrameFormat (const QTextFrameFormat &format)
Sets the frame's format.
void setLayoutData (QTextFrameLayoutData *data)
~QTextFrame ()
Destroys the frame, and removes it from the document's layout.
Public Functions inherited from QTextObject
QTextDocumentPrivate * docHandle () const
QTextDocument * document () const
Returns the document this object belongs to.
QTextFormat format () const
Returns the text object's format.
int formatIndex () const
Returns the index of the object's format in the document's internal list of formats.
int objectIndex () const
Returns the object index of this object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QTextFrame (QTextFramePrivate &p, QTextDocument *doc)
Protected Functions inherited from QTextObject
QTextObject (QTextDocument *doc)
Creates a new QTextObject for the given document.
QTextObject (QTextObjectPrivate &p, QTextDocument *doc)
void setFormat (const QTextFormat &format)
Sets the text object's format.
~QTextObject ()
Destroys the text object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class iterator
class QTextDocumentPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextFrame class represents a frame in a QTextDocument.
Note
This class or function is reentrant.
Text frames provide structure for the text in a document. They are used as generic containers for other document elements. Frames are usually created by using QTextCursor::insertFrame().
Warning
This function is not part of the public interface. Each frame in a document consists of a frame start character, QChar(0xFDD0), followed by the frame's contents, followed by a frame end character, QChar(0xFDD1). The character formats of the start and end character contain a reference to the frame object's objectIndex.
Frames can be used to create hierarchical structures in rich text documents. Each document has a root frame (QTextDocument::rootFrame()), and each frame beneath the root frame has a parent frame and a (possibly empty) list of child frames. The parent frame can be found with parentFrame(), and the childFrames() function provides a list of child frames.
Each frame contains at least one text block to enable text cursors to insert new document elements within. As a result, the QTextFrame::iterator class is used to traverse both the blocks and child frames within a given frame. The first and last child elements in the frame can be found with begin() and end().
A frame also has a format (specified using QTextFrameFormat) which can be set with setFormat() and read with format().
Text cursors can be obtained that point to the first and last valid cursor positions within a frame; use the firstCursorPosition() and lastCursorPosition() functions for this. The frame's extent in the document can be found with firstPosition() and lastPosition().
You can iterate over a frame's contents using the QTextFrame::iterator class: this provides read-only access to its internal list of text blocks and child frames.
See also
QTextCursor QTextDocument
Definition at line 122 of file qtextobject.h.
Typedefs
Iterator
QTextFrame::Iterator
Qt-style synonym for QTextFrame::iterator.
Definition at line 177 of file qtextobject.h.
Constructors and Destructors
QTextFrame() [1/2]
QTextFrame::QTextFrame (QTextDocument * doc) explicit
Creates a new empty frame for the text document.
Definition at line 442 of file qtextobject.cpp.
     : QTextObject(*new QTextFramePrivate(doc), doc)
 {
 }
~QTextFrame()
QTextFrame::~QTextFrame ()
Destroys the frame, and removes it from the document's layout.
Definition at line 451 of file qtextobject.cpp.
 {
     Q_D(QTextFrame);
     delete d->layoutData;
 }
QTextFrame() [2/2]
QTextFrame::QTextFrame (QTextFramePrivate & p, QTextDocument * doc) protected
Warning
This function is not part of the public interface.
Definition at line 460 of file qtextobject.cpp.
     : QTextObject(p, doc)
 {
 }
Functions
begin()
QTextFrame::iterator QTextFrame::begin () const
Returns an iterator pointing to the first document element inside the frame.
Please see the document STL-style-Iterators for more information.
See also
end()
Definition at line 659 of file qtextobject.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFrame(), QTextHtmlExporter::emitTextFrame(), firstChildPos(), QTextDocumentLayoutPrivate::frameIteratorForYPosition(), QTextDocumentLayoutPrivate::hitTest(), QTextFrame::iterator::iterator(), QTextDocumentLayoutPrivate::layoutFrame(), QTextHtmlExporter::toHtml(), and QTextOdfWriter::writeFrame().
 {
     const QTextDocumentPrivate *priv = docHandle();
     int b = priv->blockMap().findNode(firstPosition());
     int e = priv->blockMap().findNode(lastPosition()+1);
     return iterator(const_cast<QTextFrame *>(this), b, b, e);
 }
childFrames()
QList< QTextFrame * > QTextFrame::childFrames () const
Returns a (possibly empty) list of the frame's child frames.
See also
parentFrame()
Definition at line 470 of file qtextobject.cpp.
Referenced by boundingRectOfFloatsInSelection(), QTextDocumentPrivate::clearFrame(), findChildFrame(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentPrivate::insert_frame(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), markFrames(), QTextFramePrivate::remove_me(), and QTextDocumentPrivate::scan_frames().
 {
     Q_D(const QTextFrame);
     return d->childFrames;
 }
end()
QTextFrame::iterator QTextFrame::end () const
Returns an iterator pointing to the position past the last document element inside the frame.
Please see the document STL-Style Iterators for more information.
See also
begin()
Definition at line 672 of file qtextobject.cpp.
Referenced by QTextFrame::iterator::iterator(), QTextFrame::iterator::operator++(), QTextFrame::iterator::operator--(), QTextBlock::text(), and QTextBlock::textDirection().
 {
     const QTextDocumentPrivate *priv = docHandle();
     int b = priv->blockMap().findNode(firstPosition());
     int e = priv->blockMap().findNode(lastPosition()+1);
     return iterator(const_cast<QTextFrame *>(this), e, b, e);
 }
firstCursorPosition()
QTextCursor QTextFrame::firstCursorPosition () const
Returns the first cursor position inside the frame.
See also
lastCursorPosition() firstPosition() lastPosition()
Definition at line 494 of file qtextobject.cpp.
 {
     Q_D(const QTextFrame);
     return QTextCursor(d->pieceTable, firstPosition());
 }
firstPosition()
int QTextFrame::firstPosition () const
Returns the first document position inside the frame.
See also
lastPosition() firstCursorPosition() lastCursorPosition()
Definition at line 516 of file qtextobject.cpp.
Referenced by QTextCursorPrivate::adjustCursor(), begin(), QTextDocumentPrivate::changeObjectFormat(), QTextDocumentLayoutPrivate::drawFlow(), end(), firstCursorPosition(), firstFramePosLessThanCursorPos(), QTextDocumentLayoutPrivate::frameBoundingRectInternal(), QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), QTextDocumentLayoutPrivate::frameIteratorForYPosition(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentPrivate::insert_frame(), isEmptyBlockBeforeTable(), isFrameFromInlineObject(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutTable(), markFrames(), QTextCursorPrivate::movePosition(), QTextDocumentLayout::positionInlineObject(), QTextCursor::QTextCursor(), QTextTable::removeColumns(), QTextDocumentPrivate::removeFrame(), and QTextTable::removeRows().
 {
     Q_D(const QTextFrame);
     if (!d->fragment_start)
         return 0;
     return d->pieceTable->fragmentMap().position(d->fragment_start) + 1;
 }
frameFormat()
QTextFrameFormat QTextFrame::frameFormat () const inline
Returns the frame's format.
See also
setFrameFormat()
Definition at line 131 of file qtextobject.h.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QTextHtmlExporter::emitTextFrame(), QLabelPrivate::ensureTextLayouted(), QTextDocumentLayoutPrivate::floatMargins(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::positionFloat(), QTextHtmlImporter::processSpecialNodes(), QTextDocumentLayout::resizeInlineObject(), QTextDocument::setDocumentMargin(), and QTextHtmlExporter::toHtml().
 { return QTextObject::format().toFrameFormat(); }
lastCursorPosition()
QTextCursor QTextFrame::lastCursorPosition () const
Returns the last cursor position inside the frame.
See also
firstCursorPosition() firstPosition() lastPosition()
Definition at line 505 of file qtextobject.cpp.
Referenced by QTextHtmlImporter::closeTag().
 {
     Q_D(const QTextFrame);
     return QTextCursor(d->pieceTable, lastPosition());
 }
lastPosition()
int QTextFrame::lastPosition () const
Returns the last document position inside the frame.
See also
firstPosition() firstCursorPosition() lastCursorPosition()
Definition at line 529 of file qtextobject.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), QTextCursorPrivate::adjustCursor(), begin(), QTextDocumentPrivate::changeObjectFormat(), QTextCopyHelper::copy(), cursorPosLessThanLastFramePos(), end(), findChildFrame(), QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), QTextDocumentLayout::hitTest(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentPrivate::insert_frame(), isEmptyBlockAfterTable(), isFrameFromInlineObject(), isLineSeparatorBlockAfterTable(), lastCursorPosition(), markFrames(), QTextCursorPrivate::movePosition(), QTextDocumentLayout::positionInlineObject(), and QTextDocumentPrivate::removeFrame().
 {
     Q_D(const QTextFrame);
     if (!d->fragment_end)
         return d->pieceTable->length() - 1;
     return d->pieceTable->fragmentMap().position(d->fragment_end);
 }
layoutData()
QTextFrameLayoutData * QTextFrame::layoutData () const
Warning
This function is not part of the public interface.
Definition at line 540 of file qtextobject.cpp.
Referenced by data().
 {
     Q_D(const QTextFrame);
     return d->layoutData;
 }
parentFrame()
QTextFrame * QTextFrame::parentFrame () const
Returns the frame's parent frame.
If the frame is the root frame of a document, this will return 0.
See also
childFrames() QTextDocument::rootFrame()
Definition at line 482 of file qtextobject.cpp.
Referenced by QTextCursorPrivate::adjustCursor(), QTextDocumentLayout::blockBoundingRect(), QTextDocumentPrivate::clearFrame(), QTextCursor::currentTable(), QTextDocumentLayoutPrivate::drawFlow(), QTextDocumentLayoutPrivate::drawFrameDecoration(), QTextHtmlExporter::emitTextFrame(), QTextDocumentLayoutPrivate::frameBoundingRectInternal(), QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), QTextDocumentPrivate::insert_frame(), isAncestorFrame(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentPrivate::move(), QTextDocumentLayoutPrivate::positionFloat(), QTextFramePrivate::remove_me(), QTextDocumentPrivate::removeFrame(), and QTextDocumentPrivate::scan_frames().
 {
     Q_D(const QTextFrame);
     return d->parentFrame;
 }
setFrameFormat()
void QTextFrame::setFrameFormat (const QTextFrameFormat & format) inline
Sets the frame's format.
See also
frameFormat()
Definition at line 191 of file qtextobject.h.
Referenced by QTextDocument::clone(), QLabelPrivate::ensureTextLayouted(), QTextHtmlImporter::processSpecialNodes(), QTextHtmlImporter::scanTable(), and QTextDocument::setDocumentMargin().
 { QTextObject::setFormat(aformat); }
setLayoutData()
void QTextFrame::setLayoutData (QTextFrameLayoutData * data)
Warning
This function is not part of the public interface.
Definition at line 549 of file qtextobject.cpp.
Referenced by createData().
 {
     Q_D(QTextFrame);
     delete d->layoutData;
     d->layoutData = data;
 }
Friends and Related Functions
iterator
friend class iterator friend
Definition at line 175 of file qtextobject.h.
Referenced by QTextTableCell::begin(), begin(), QTextBlock::begin(), QTextTableCell::end(), end(), and QTextBlock::end().
QTextDocumentPrivate
friend class QTextDocumentPrivate friend
Definition at line 185 of file qtextobject.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextobject.h
/src/gui/text/qtextobject.cpp