Qt 4.8: QTransformedScreen Class Reference
QTransformedScreen Class Reference
The QTransformedScreen class implements a screen driver for a transformed screen.
#include <qscreentransformed_qws.h>
Public Types
enum Transformation { None, Rot90, Rot180, Rot270 }
This enum describes the various rotations a transformed screen can have.
Public Types inherited from QScreen
enum ClassId {
LinuxFBClass, TransformedClass, VNCClass, MultiClass,
VFbClass, DirectFBClass, SvgalibClass, ProxyClass,
GLClass, IntfbClass, CustomClass = 1024
}
This enum defines the class identifiers for the known screen subclasses.
enum PixelType { NormalPixel, BGRPixel }
This enum describes the pixel storage format of the screen, i.
Public Functions
void blit (const QImage &img, const QPoint &topLeft, const QRegion &region)
Reimplemented Function
bool connect (const QString &displaySpec)
Reimplemented Function
void exposeRegion (QRegion region, int changing)
Reimplemented Function
bool isTransformed () const
Reimplemented Function
QSize mapFromDevice (const QSize &s) const
Reimplemented Function
QPoint mapFromDevice (const QPoint &, const QSize &) const
Reimplemented Function
QRect mapFromDevice (const QRect &, const QSize &) const
Reimplemented Function
QRegion mapFromDevice (const QRegion &, const QSize &) const
Reimplemented Function
QSize mapToDevice (const QSize &s) const
Reimplemented Function
QPoint mapToDevice (const QPoint &, const QSize &) const
Reimplemented Function
QRect mapToDevice (const QRect &, const QSize &) const
Reimplemented Function
QRegion mapToDevice (const QRegion &, const QSize &) const
Reimplemented Function
QTransformedScreen (int display_id)
Constructs a QTransformedScreen object.
QRegion region () const
Reimplemented Function
void setDirty (const QRect &)
Reimplemented Function
void setTransformation (Transformation t)
Rotates this screen object according to the specified transformation.
void solidFill (const QColor &color, const QRegion &region)
Reimplemented Function
Transformation transformation () const
Returns the currently set rotation.
int transformOrientation () const
Reimplemented Function
~QTransformedScreen ()
Destroys the QTransformedScreen object.
Public Functions inherited from QProxyScreen
void blank (bool on)
Reimplemented Function
QWSWindowSurface * createSurface (QWidget *widget) const
Reimplemented Function
QWSWindowSurface * createSurface (const QString &key) const
Reimplemented Function
void disconnect ()
Reimplemented Function
void haltUpdates ()
bool initDevice ()
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
bool isInterlaced () const
Reimplemented Function
int memoryNeeded (const QString &)
bool onCard (const unsigned char *) const
Reimplemented Function
bool onCard (const unsigned char *, ulong &out_offset) const
Reimplemented Function
QProxyScreen (int display_id, ClassId=ProxyClass)
Constructs a proxy screen with the given displayId and classId.
void restore ()
Reimplemented Function
void resumeUpdates ()
void save ()
Reimplemented Function
QScreen * screen () const
Returns the real screen used by the proxy screen.
void setMode (int width, int height, int depth)
Reimplemented Function
void setScreen (QScreen *screen)
Sets the real screen to be used by the proxy screen.
int sharedRamSize (void *)
void shutdownDevice ()
Reimplemented Function
QList< QScreen * > subScreens () const
Reimplemented Function
bool supportsDepth (int) const
Reimplemented Function
~QProxyScreen ()
Destroys the proxy screen.
Public Functions inherited from QScreen
virtual int alloc (unsigned int, unsigned int, unsigned int)
Returns the index in the screen's palette which is the closest match to the given RGB value (red, green, blue).
uchar * base () const
Returns a pointer to the beginning of the framebuffer.
void blit (QWSWindow *bs, const QRegion &clip)
virtual uchar * cache (int)
ClassId classId () const
Returns the class identifier for the screen object.
QRgb * clut ()
Returns a pointer to the screen's color lookup table (i.
int colorCount ()
Returns the number of entries in the screen's color lookup table (i.
int depth () const
Returns the depth of the framebuffer, in bits per pixel.
int deviceHeight () const
Returns the full height of the framebuffer device in pixels.
int deviceWidth () const
Returns the physical width of the framebuffer device in pixels.
QGraphicsSystem * graphicsSystem () const
int height () const
Returns the logical height of the framebuffer in pixels.
int linestep () const
Returns the length of each scanline of the framebuffer in bytes.
virtual QImage mapFromDevice (const QImage &) const
Maps the given image from the framebuffer coordinate system to the coordinate space used by the application.
virtual QImage mapToDevice (const QImage &) const
Maps the given image from the coordinate space used by the application to the framebuffer coordinate system.
QT_DEPRECATED int numCols ()
QPoint offset () const
Returns the logical offset of the screen, i.
int physicalHeight () const
Returns the physical height of the screen in millimeters.
int physicalWidth () const
Returns the physical width of the screen in millimeters.
QImage::Format pixelFormat () const
Returns the pixel format of the screen, or QImage::Format_Invalid if the pixel format is not a supported image format.
PixelType pixelType () const
Returns the pixel storage format of the screen.
QPixmapDataFactory * pixmapDataFactory () const
virtual int pixmapDepth () const
Returns the preferred depth for pixmaps, in bits per pixel.
virtual int pixmapLinestepAlignment ()
Returns the value (in bits) to which individual scanlines of pixmaps held in the graphics card's memory, should be aligned.
virtual int pixmapOffsetAlignment ()
Returns the value (in bits) to which the start address of pixmaps held in the graphics card's memory, should be aligned.
QScreen (int display_id, ClassId classId)
Constructs a new screen driver.
QScreen (int display_id)
Constructs a new screen driver.
int screenSize () const
Returns the size of the screen in bytes.
virtual void set (unsigned int, unsigned int, unsigned int, unsigned int)
void setOffset (const QPoint &p)
int subScreenIndexAt (const QPoint &p) const
Returns the index of the subscreen at the given position; returns -1 if no screen is found.
int totalSize () const
Returns the size of the available graphics card memory (including the screen) in bytes.
virtual void uncache (uchar *)
int width () const
Returns the logical width of the framebuffer in pixels.
virtual ~QScreen ()
Destroys this screen driver.
Properties
QTransformedScreenPrivate * d_ptr
Friends
class QTransformedScreenPrivate
Additional Inherited Members
Static Public Functions inherited from QScreen
static QScreen * instance ()
Returns a pointer to the application's QScreen instance.
Protected Functions inherited from QScreen
void setGraphicsSystem (QGraphicsSystem *system)
void setPixelFormat (QImage::Format format)
Sets the screen's pixel format to format.
void setPixmapDataFactory (QPixmapDataFactory *factory)
Protected Variables inherited from QScreen
int d
the pixel depth
uchar * data
points to the first visible pixel in the frame buffer.
int dh
the device height
int displayId
int dw
the device width
QPoolEntry * entries
int * entryp
bool grayscale
the gray scale screen mode flag
int h
the logical height of the screen.
unsigned int * lowest
int lstep
the number of bytes representing a line in the frame buffer.
int mapsize
the total number of bytes in the frame buffer
int physHeight
the physical height of the screen in millimeters.
int physWidth
the physical width of the screen in millimeters.
PixelType pixeltype
set to BGRPixel
QRgb screenclut [256]
the color table
int screencols
the number of entries in the color table
int size
the number of bytes in the visible region of the frame buffer
int w
the logical width of the screen.
Static Protected Variables inherited from QScreen
static ClearCacheFunc clearCacheFunc = 0
Related Functions inherited from QScreen
void setTransformation (int transformation, int screenNo)
Here it is.
Detailed Description
The QTransformedScreen class implements a screen driver for a transformed screen.
Warning
This function is not part of the public interface.
Note that this class is only available in Qt for Embedded Linux. Custom screen drivers can be added by subclassing the QScreenDriverPlugin class, using the QScreenDriverFactory class to dynamically load the driver into the application, but there should only be one screen object per application.
Use the QScreen::isTransformed() function to determine if a screen is transformed. The QTransformedScreen class itself provides means of rotating the screen with its setTransformation() function; the transformation() function returns the currently set rotation in terms of the Transformation enum (which describes the various available rotation settings). Alternatively, QTransformedScreen provides an implementation of the QScreen::transformOrientation() function, returning the current rotation as an integer value.
See also
QScreen, QScreenDriverPlugin, {Running Applications}
Definition at line 57 of file qscreentransformed_qws.h.
Enumerations
Transformation
enum QTransformedScreen::Transformation
This enum describes the various rotations a transformed screen can have.
None No rotation
Rot90 90 degrees rotation
Rot180 180 degrees rotation
Rot270 270 degrees rotation
Enumerator
None
Rot90
Rot180
Rot270
Definition at line 63 of file qscreentransformed_qws.h.
 { None, Rot90, Rot180, Rot270 };
Constructors and Destructors
QTransformedScreen()
QTransformedScreen::QTransformedScreen (int displayId) explicit
Constructs a QTransformedScreen object.
The displayId argument identifies the Qt for Embedded Linux server to connect to.
Definition at line 161 of file qscreentransformed_qws.cpp.
     : QProxyScreen(displayId, QScreen::TransformedClass)
 {
     d_ptr = new QTransformedScreenPrivate(this);
     d_ptr->transformation = None;
 #ifdef QT_REGION_DEBUG
     qDebug() << "QTransformedScreen::QTransformedScreen";
 #endif
 }
~QTransformedScreen()
QTransformedScreen::~QTransformedScreen ()
Destroys the QTransformedScreen object.
Definition at line 181 of file qscreentransformed_qws.cpp.
 {
     delete d_ptr;
 }
Functions
blit()
void QTransformedScreen::blit (const QImage & img, const QPoint & topLeft, const QRegion & region) virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 368 of file qscreentransformed_qws.cpp.
 {
     const Transformation trans = d_ptr->transformation;
     if (trans == None) {
         QProxyScreen::blit(image, topLeft, region);
         return;
     }
     const QVector<QRect> rects = region.rects();
     const QRect bound = QRect(0, 0, QScreen::w, QScreen::h)
                         & QRect(topLeft, image.size());
     BlitFunc func = 0;
 #ifdef QT_QWS_DEPTH_GENERIC
     if (d_ptr->doGenericColors && depth() == 16) {
         if (image.depth() == 16)
             SET_BLIT_FUNC(qrgb_generic16, quint16, trans, func);
         else
             SET_BLIT_FUNC(qrgb_generic16, quint32, trans, func);
     } else
 #endif
     switch (depth()) {
 #ifdef QT_QWS_DEPTH_32
     case 32:
 #ifdef QT_QWS_DEPTH_16
         if (image.depth() == 16)
             SET_BLIT_FUNC(quint32, quint16, trans, func);
         else
 #endif
             SET_BLIT_FUNC(quint32, quint32, trans, func);
         break;
 #endif
 #if defined(QT_QWS_DEPTH_24) || defined(QT_QWS_DEPTH18)
     case 24:
     case 18:
         SET_BLIT_FUNC(quint24, quint24, trans, func);
         break;
 #endif
 #if defined(QT_QWS_DEPTH_16) || defined(QT_QWS_DEPTH_15) || defined(QT_QWS_DEPTH_12)
     case 16:
 #if defined QT_QWS_ROTATE_BGR
         if (pixelType() == BGRPixel && image.depth() == 16) {
             SET_BLIT_FUNC(qbgr565, quint16, trans, func);
             break;
         } //fall-through here!!!
 #endif
     case 15:
 #if defined QT_QWS_ROTATE_BGR
         if (pixelType() == BGRPixel && image.format() == QImage::Format_RGB555) {
             SET_BLIT_FUNC(qbgr555, qrgb555, trans, func);
             break;
         } //fall-through here!!!
 #endif
     case 12:
         if (image.depth() == 16)
             SET_BLIT_FUNC(quint16, quint16, trans, func);
         else
             SET_BLIT_FUNC(quint16, quint32, trans, func);
         break;
 #endif
 #ifdef QT_QWS_DEPTH_8
     case 8:
         if (image.format() == QImage::Format_RGB444)
             SET_BLIT_FUNC(quint8, qrgb444, trans, func);
         else if (image.depth() == 16)
             SET_BLIT_FUNC(quint8, quint16, trans, func);
         else
             SET_BLIT_FUNC(quint8, quint32, trans, func);
         break;
 #endif
     default:
         return;
     }
     if (!func)
         return;
     QWSDisplay::grab();
     for (int i = 0; i < rects.size(); ++i) {
         const QRect r = rects.at(i) & bound;
         QPoint dst;
         switch (trans) {
         case Rot90:
             dst = mapToDevice(r.topRight(), QSize(w, h));
             break;
         case Rot180:
             dst = mapToDevice(r.bottomRight(), QSize(w, h));
             break;
         case Rot270:
             dst = mapToDevice(r.bottomLeft(), QSize(w, h));
             break;
         default:
             break;
         }
         func(this, image, r.translated(-topLeft), dst);
     }
     QWSDisplay::ungrab();
 }
connect()
bool QTransformedScreen::connect (const QString & displaySpec) virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 211 of file qscreentransformed_qws.cpp.
 {
     QString dspec = displaySpec.trimmed();
     if (dspec.startsWith(QLatin1String("Transformed:"), Qt::CaseInsensitive))
         dspec = dspec.mid(QString::fromLatin1("Transformed:").size());
     else if (!dspec.compare(QLatin1String("Transformed"), Qt::CaseInsensitive))
         dspec = QString();
     const QString displayIdSpec = QString::fromLatin1(" :%1").arg(displayId);
     if (dspec.endsWith(displayIdSpec))
         dspec = dspec.left(dspec.size() - displayIdSpec.size());
     d_ptr->transformation = filterTransformation(dspec);
     QString driver = dspec;
     int colon = driver.indexOf(QLatin1Char(':'));
     if (colon >= 0)
         driver.truncate(colon);
     if (!QScreenDriverFactory::keys().contains(driver, Qt::CaseInsensitive))
         if (!dspec.isEmpty())
             dspec.prepend(QLatin1Char(':'));
     const int id = getDisplayId(dspec);
     QScreen *s = qt_get_screen(id, dspec.toLatin1().constData());
     setScreen(s);
 #ifdef QT_QWS_DEPTH_GENERIC
     d_ptr->doGenericColors = dspec.contains(QLatin1String("genericcolors"));
 #endif
     d_ptr->configure();
     // XXX
     qt_screen = this;
     return true;
 }
exposeRegion()
void QTransformedScreen::exposeRegion (QRegion region, int changing) virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 271 of file qscreentransformed_qws.cpp.
 {
     if (!data || d_ptr->transformation == None) {
         QProxyScreen::exposeRegion(region, changing);
         return;
     }
     QScreen::exposeRegion(region, changing);
 }
isTransformed()
bool QTransformedScreen::isTransformed () const inline virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 83 of file qscreentransformed_qws.h.
 { return transformation() != None; }
mapFromDevice() [1/4]
QSize QTransformedScreen::mapFromDevice (const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 504 of file qscreentransformed_qws.cpp.
Referenced by region(), and setTransformation().
 {
     switch (d_ptr->transformation) {
     case None:
     case Rot180:
         break;
     case Rot90:
     case Rot270:
         return QSize(s.height(), s.width());
         break;
     }
     return s;
 }
mapFromDevice() [2/4]
QPoint QTransformedScreen::mapFromDevice (const QPoint & p, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 548 of file qscreentransformed_qws.cpp.
 {
     QPoint rp(p);
     switch (d_ptr->transformation) {
     case None:
         break;
     case Rot90:
         rp.setX(s.height() - p.y() - 1);
         rp.setY(p.x());
         break;
     case Rot180:
         rp.setX(s.width() - p.x() - 1);
         rp.setY(s.height() - p.y() - 1);
         break;
     case Rot270:
         rp.setX(p.y());
         rp.setY(s.width() - p.x() - 1);
         break;
     }
     return rp;
 }
mapFromDevice() [3/4]
QRect QTransformedScreen::mapFromDevice (const QRect & r, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 605 of file qscreentransformed_qws.cpp.
 {
     if (r.isNull())
         return QRect();
     QRect tr;
     switch (d_ptr->transformation) {
     case None:
         tr = r;
         break;
     case Rot90:
         tr.setCoords(s.height() - r.y() - 1, r.x(),
                      s.height() - r.bottom() - 1, r.right());
         break;
     case Rot180:
         tr.setCoords(s.width() - r.x() - 1, s.height() - r.y() - 1,
                      s.width() - r.right() - 1, s.height() - r.bottom() - 1);
         break;
     case Rot270:
         tr.setCoords(r.y(), s.width() - r.x() - 1,
                      r.bottom(), s.width() - r.right() - 1);
         break;
     }
     return correctNormalized(tr);
 }
mapFromDevice() [4/4]
QRegion QTransformedScreen::mapFromDevice (const QRegion & rgn, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 686 of file qscreentransformed_qws.cpp.
 {
     if (d_ptr->transformation == None)
         return QProxyScreen::mapFromDevice(rgn, s);
 #ifdef QT_REGION_DEBUG
     qDebug() << "fromDevice: realRegion count:  " << rgn.rects().size() << " isEmpty? " << rgn.isEmpty() << "  bounds:" << rgn.boundingRect();
 #endif
     QRect tr;
     QRegion trgn;
     QVector<QRect> a = rgn.rects();
     const QRect *r = a.data();
     int w = s.width();
     int h = s.height();
     int size = a.size();
     switch (d_ptr->transformation) {
     case None:
         break;
     case Rot90:
         for (int i = 0; i < size; i++, r++) {
             tr.setCoords(h - r->y() - 1, r->x(),
                          h - r->bottom() - 1, r->right());
             trgn |= correctNormalized(tr);
         }
         break;
     case Rot180:
         for (int i = 0; i < size; i++, r++) {
             tr.setCoords(w - r->x() - 1, h - r->y() - 1,
                          w - r->right() - 1, h - r->bottom() - 1);
             trgn |= correctNormalized(tr);
         }
         break;
     case Rot270:
         for (int i = 0; i < size; i++, r++) {
             tr.setCoords(r->y(), w - r->x() - 1,
                          r->bottom(), w - r->right() - 1);
             trgn |= correctNormalized(tr);
         }
         break;
     }
 #ifdef QT_REGION_DEBUG
     qDebug() << "fromDevice: transRegion count: " << trgn.rects().size() << " isEmpty? " << trgn.isEmpty() << "  bounds:" << trgn.boundingRect();
 #endif
     return trgn;
 }
mapToDevice() [1/4]
QSize QTransformedScreen::mapToDevice (const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 487 of file qscreentransformed_qws.cpp.
Referenced by blit(), setDirty(), and solidFill().
 {
     switch (d_ptr->transformation) {
     case None:
     case Rot180:
         break;
     case Rot90:
     case Rot270:
         return QSize(s.height(), s.width());
         break;
     }
     return s;
 }
mapToDevice() [2/4]
QPoint QTransformedScreen::mapToDevice (const QPoint & p, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 521 of file qscreentransformed_qws.cpp.
 {
     QPoint rp(p);
     switch (d_ptr->transformation) {
     case None:
         break;
     case Rot90:
         rp.setX(p.y());
         rp.setY(s.width() - p.x() - 1);
         break;
     case Rot180:
         rp.setX(s.width() - p.x() - 1);
         rp.setY(s.height() - p.y() - 1);
         break;
     case Rot270:
         rp.setX(s.height() - p.y() - 1);
         rp.setY(p.x());
         break;
     }
     return rp;
 }
mapToDevice() [3/4]
QRect QTransformedScreen::mapToDevice (const QRect & r, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 575 of file qscreentransformed_qws.cpp.
 {
     if (r.isNull())
         return QRect();
     QRect tr;
     switch (d_ptr->transformation) {
     case None:
         tr = r;
         break;
     case Rot90:
         tr.setCoords(r.y(), s.width() - r.x() - 1,
                      r.bottom(), s.width() - r.right() - 1);
         break;
     case Rot180:
         tr.setCoords(s.width() - r.x() - 1, s.height() - r.y() - 1,
                      s.width() - r.right() - 1, s.height() - r.bottom() - 1);
         break;
     case Rot270:
         tr.setCoords(s.height() - r.y() - 1, r.x(),
                      s.height() - r.bottom() - 1, r.right());
         break;
     }
     return correctNormalized(tr);
 }
mapToDevice() [4/4]
QRegion QTransformedScreen::mapToDevice (const QRegion & rgn, const QSize & s) const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 635 of file qscreentransformed_qws.cpp.
 {
     if (d_ptr->transformation == None)
         return QProxyScreen::mapToDevice(rgn, s);
 #ifdef QT_REGION_DEBUG
     qDebug() << "mapToDevice size" << s << "rgn:  " << rgn;
 #endif
     QRect tr;
     QRegion trgn;
     QVector<QRect> a = rgn.rects();
     const QRect *r = a.data();
     int w = s.width();
     int h = s.height();
     int size = a.size();
     switch (d_ptr->transformation) {
     case None:
         break;
     case Rot90:
         for (int i = 0; i < size; i++, r++) {
             tr.setCoords(r->y(), w - r->x() - 1,
                          r->bottom(), w - r->right() - 1);
             trgn |= correctNormalized(tr);
         }
         break;
     case Rot180:
         for (int i = 0; i < size; i++, r++) {
             tr.setCoords(w - r->x() - 1, h - r->y() - 1,
                          w - r->right() - 1, h - r->bottom() - 1);
             trgn |= correctNormalized(tr);
         }
         break;
     case Rot270:
         for (int i = 0; i < size; i++, r++) {
             tr.setCoords(h - r->y() - 1, r->x(),
                          h - r->bottom() - 1, r->right());
             trgn |= correctNormalized(tr);
         }
         break;
     }
 #ifdef QT_REGION_DEBUG
     qDebug() << "mapToDevice trgn:  " << trgn;
 #endif
     return trgn;
 }
region()
QRegion QTransformedScreen::region () const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 746 of file qscreentransformed_qws.cpp.
 {
     QRegion deviceRegion = QProxyScreen::region();
     return mapFromDevice(deviceRegion, QSize(deviceWidth(), deviceHeight()));
 }
setDirty()
void QTransformedScreen::setDirty (const QRect & rect) virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 737 of file qscreentransformed_qws.cpp.
 {
     const QRect r = mapToDevice(rect, QSize(width(), height()));
     QProxyScreen::setDirty(r);
 }
setTransformation()
void QTransformedScreen::setTransformation (Transformation transformation)
Rotates this screen object according to the specified transformation.
See also
transformation()
Definition at line 285 of file qscreentransformed_qws.cpp.
Referenced by qws_setScreenTransformation().
 {
     d_ptr->transformation = transformation;
     QSize size = mapFromDevice(QSize(dw, dh));
     w = size.width();
     h = size.height();
     const QScreen *s = screen();
     size = mapFromDevice(QSize(s->physicalWidth(), s->physicalHeight()));
     physWidth = size.width();
     physHeight = size.height();
 #ifdef QT_REGION_DEBUG
     qDebug() << "QTransformedScreen::setTransformation" << transformation
              << "size" << w << h << "dev size" << dw << dh;
 #endif
 }
solidFill()
void QTransformedScreen::solidFill (const QColor & color, const QRegion & region) virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 472 of file qscreentransformed_qws.cpp.
 {
     const QRegion tr = mapToDevice(region, QSize(w,h));
     Q_ASSERT(tr.boundingRect() == mapToDevice(region.boundingRect(), QSize(w,h)));
 #ifdef QT_REGION_DEBUG
     qDebug() << "QTransformedScreen::solidFill region" << region << "transformed" << tr;
 #endif
     QProxyScreen::solidFill(color, tr);
 }
transformation()
QTransformedScreen::Transformation QTransformedScreen::transformation () const
Returns the currently set rotation.
See also
setTransformation(), QScreen::transformOrientation()
Definition at line 255 of file qscreentransformed_qws.cpp.
Referenced by QTransformedScreenPrivate::configure(), and setTransformation().
 {
     return d_ptr->transformation;
 }
transformOrientation()
int QTransformedScreen::transformOrientation () const virtual
Reimplemented Function
Reimplemented from QProxyScreen.
Definition at line 263 of file qscreentransformed_qws.cpp.
 {
     return (int)d_ptr->transformation;
 }
Friends and Related Functions
QTransformedScreenPrivate
friend class QTransformedScreenPrivate friend
Definition at line 93 of file qscreentransformed_qws.h.
Referenced by QTransformedScreen().
Properties
d_ptr
QTransformedScreenPrivate* QTransformedScreen::d_ptr private
Definition at line 94 of file qscreentransformed_qws.h.
Referenced by blit(), connect(), exposeRegion(), mapFromDevice(), mapToDevice(), QTransformedScreen(), setTransformation(), transformation(), transformOrientation(), and ~QTransformedScreen().
The documentation for this class was generated from the following files:
/src/gui/embedded/qscreentransformed_qws.h
/src/gui/embedded/qscreentransformed_qws.cpp