Qt 4.8: QPatternist::Boolean Class Reference
QPatternist::Boolean Class Reference
Implements the value instance of the xs:boolean type.
#include <qboolean_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
bool value () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static bool evaluateEBV (const Item::Iterator::Ptr &e, const QExplicitlySharedDataPointer< DynamicContext > &)
static bool evaluateEBV (const Item &first, const Item::Iterator::Ptr &e, const QExplicitlySharedDataPointer< DynamicContext > &)
static bool evaluateEBV (const Item &item, const QExplicitlySharedDataPointer< DynamicContext > &context)
static AtomicValue::Ptr fromLexical (const QString &val)
static Boolean::Ptr fromValue (const bool value)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
Boolean (const bool value)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Properties
const bool m_value
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Implements the value instance of the xs:boolean type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qboolean_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::Boolean::Ptr
Definition at line 72 of file qboolean_p.h.
Constructors and Destructors
Boolean()
Boolean::Boolean (const bool value) protected
Definition at line 99 of file qboolean.cpp.
                                  : m_value(value)
 {
 }
Functions
evaluateEBV() [1/4]
bool Boolean::evaluateEBV (const Item::Iterator::Ptr & e, const QExplicitlySharedDataPointer< DynamicContext > & context) static
Returns
the boolean value this Boolean represents
Definition at line 55 of file qboolean.cpp.
Referenced by evaluateEBV(), QPatternist::RangeVariableReference::evaluateEBV(), QPatternist::Literal::evaluateEBV(), QPatternist::ExternalVariableLoader::evaluateEBV(), QPatternist::Expression::evaluateEBV(), and QPatternist::GenericPredicate::mapToItem().
 {
     return evaluateEBV(it->next(), it, context);
 }
evaluateEBV() [2/4]
bool Boolean::evaluateEBV (const Item & first, const Item::Iterator::Ptr & e, const QExplicitlySharedDataPointer< DynamicContext > & context) static
Definition at line 61 of file qboolean.cpp.
 {
     Q_ASSERT(it);
     Q_ASSERT(context);
     if(!first)
         return false;
     else if(first.isNode())
         return true;
     const Item second(it->next());
     if(second)
     {
         Q_ASSERT(context);
         context->error(QtXmlPatterns::tr("Effective Boolean Value cannot be calculated for a sequence "
                                          "containing two or more atomic values."),
                           ReportContext::FORG0006,
                           QSourceLocation());
         return false;
     }
     else
         return first.as<AtomicValue>()->evaluateEBV(context);
 }
evaluateEBV() [3/4]
bool Boolean::evaluateEBV (const Item & item, const QExplicitlySharedDataPointer< DynamicContext > & context) static
Definition at line 88 of file qboolean.cpp.
 {
     if(!item)
         return false;
     else if(item.isNode())
         return true;
     else
         return item.as<AtomicValue>()->evaluateEBV(context);
 }
evaluateEBV() [4/4]
bool Boolean::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const virtual
Get the Effective Boolean Value of this boolean value. For xs:boolean, this is simply the value.
Reimplemented from QPatternist::AtomicValue.
Definition at line 110 of file qboolean.cpp.
 {
     return m_value;
 }
fromLexical()
AtomicValue::Ptr Boolean::fromLexical (const QString & val) static
Creates a boolean value from a lexical representation. "true" and "1" becomes true, while "false" and "0" becomes false.
Definition at line 120 of file qboolean.cpp.
Referenced by QPatternist::StringToBooleanCaster::castFrom(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), and QPatternist::XsdValidatingInstanceReader::validateElement().
 {
     const QString val(lexical.trimmed()); /* Apply the whitespace facet. */
     if(val == QLatin1String("true") || val == QChar(QLatin1Char('1')))
         return CommonValues::BooleanTrue;
     else if(val == QLatin1String("false") || val == QChar(QLatin1Char('0')))
         return CommonValues::BooleanFalse;
     else
         return ValidationError::createError();
 }
fromValue()
Boolean::Ptr Boolean::fromValue (const bool value) static
Returns
a Boolean object instantiating value. Use True() or False() if you already know what value you need.
Definition at line 115 of file qboolean.cpp.
Referenced by QPatternist::FunctionAvailableFN::evaluateSingleton(), QPatternist::TypeAvailableFN::evaluateSingleton(), QPatternist::ContainsFN::evaluateSingleton(), QPatternist::CodepointEqualFN::evaluateSingleton(), QPatternist::MatchesFN::evaluateSingleton(), QPatternist::ValueComparison::evaluateSingleton(), QPatternist::StartsWithFN::evaluateSingleton(), QPatternist::EndsWithFN::evaluateSingleton(), QPatternist::ExternalVariableLoader::evaluateSingleton(), QPatternist::Expression::evaluateSingleton(), and QPatternist::AtomicValue::toXDM().
 {
     return value ? CommonValues::BooleanTrue : CommonValues::BooleanFalse;
 }
stringValue()
QString Boolean::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 103 of file qboolean.cpp.
 {
     return m_value
             ? CommonValues::TrueString->stringValue()
             : CommonValues::FalseString->stringValue();
 }
type()
ItemType::Ptr Boolean::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 132 of file qboolean.cpp.
 {
     return BuiltinTypes::xsBoolean;
 }
value()
bool QPatternist::Boolean::value () const inline
Definition at line 109 of file qboolean_p.h.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QPatternist::AtomicValue::toQt(), and QPatternist::XsdValidatingInstanceReader::validateElement().
         {
             return m_value;
         }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 115 of file qboolean_p.h.
Properties
m_value
const bool QPatternist::Boolean::m_value private
Definition at line 119 of file qboolean_p.h.
Referenced by evaluateEBV(), and stringValue().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qboolean_p.h
/src/xmlpatterns/data/qboolean.cpp