Qt 4.8: QDeclarativeDomValue Class Reference
QDeclarativeDomValue Class Reference
The QDeclarativeDomValue class represents a generic Qml value.
#include <qdeclarativedom_p.h>
Public Types
enum Type {
Invalid, Literal, PropertyBinding, ValueSource,
ValueInterceptor, Object, List
}
The type of the QDeclarativeDomValue node.
Public Functions
bool isBinding () const
Returns true if this is a property binding value, otherwise false.
bool isInvalid () const
Returns true if this is an invalid value, otherwise false.
bool isList () const
Returns true if this is a list value, otherwise false.
bool isLiteral () const
Returns true if this is a literal value, otherwise false.
bool isObject () const
Returns true if this is an object value, otherwise false.
bool isValueInterceptor () const
Returns true if this is a value interceptor value, otherwise false.
bool isValueSource () const
Returns true if this is a value source value, otherwise false.
int length () const
Returns the length in the input data from where the property value started u
pto the end of it, or -1 if the value is invalid.
QDeclarativeDomValue & operator= (const QDeclarativeDomValue &)
Assign other to this QDeclarativeDomValue.
int position () const
Returns the position in the input data where the property value startd, or -1 if the value is invalid.
QDeclarativeDomValue ()
Construct an invalid QDeclarativeDomValue.
QDeclarativeDomValue (const QDeclarativeDomValue &)
Create a copy of other QDeclarativeDomValue.
QDeclarativeDomValueBinding toBinding () const
Returns a QDeclarativeDomValueBinding if this value is a property binding type, otherwise returns an invalid QDeclarativeDomValueBinding.
QDeclarativeDomList toList () const
Returns a QDeclarativeDomList if this value is a list type, otherwise returns an invalid QDeclarativeDomList.
QDeclarativeDomValueLiteral toLiteral () const
Returns a QDeclarativeDomValueLiteral if this value is a literal type, otherwise returns an invalid QDeclarativeDomValueLiteral.
QDeclarativeDomObject toObject () const
Returns a QDeclarativeDomObject if this value is an object assignment type, otherwise returns an invalid QDeclarativeDomObject.
QDeclarativeDomValueValueInterceptor toValueInterceptor () const
Returns a QDeclarativeDomValueValueInterceptor if this value is a property value interceptor type, otherwise returns an invalid QDeclarativeDomValueValueInterceptor.
QDeclarativeDomValueValueSource toValueSource () const
Returns a QDeclarativeDomValueValueSource if this value is a property value source type, otherwise returns an invalid QDeclarativeDomValueValueSource.
Type type () const
Returns the type of this QDeclarativeDomValue.
~QDeclarativeDomValue ()
Destroy the QDeclarativeDomValue.
Properties
QSharedDataPointer< QDeclarativeDomValuePrivate > d
Friends
class QDeclarativeDomList
class QDeclarativeDomProperty
Detailed Description
The QDeclarativeDomValue class represents a generic Qml value.
Warning
This function is not part of the public interface.
QDeclarativeDomValue's can be assigned to QML \link QDeclarativeDomProperty \endlink{properties}.  In
QML, properties can be assigned various different values, including basic
literals, property bindings, property value sources, objects and lists of
values.  The QDeclarativeDomValue class allows a programmer to determine the specific
value type being assigned and access more detailed information through a
corresponding value type class.
For example, in the following example,
Text {
    text: "Hello World!"
    y: Other.y
}
The text property is being assigned a literal, and the y property a property binding. To output the values assigned to the text and y properties in the above example from C++,
QDeclarativeDomDocument document;
QDeclarativeDomObject root = document.rootObject();
QDeclarativeDomProperty text = root.property("text");
if (text.value().isLiteral()) {
    QDeclarativeDomValueLiteral literal = text.value().toLiteral();
    qDebug() << literal.literal();
}
QDeclarativeDomProperty y = root.property("y");
if (y.value().isBinding()) {
    QDeclarativeDomValueBinding binding = y.value().toBinding();
    qDebug() << binding.binding();
}
Definition at line 273 of file qdeclarativedom_p.h.
Enumerations
Type
enum QDeclarativeDomValue::Type
The type of the QDeclarativeDomValue node.
Invalid The QDeclarativeDomValue is invalid.
Literal The QDeclarativeDomValue is a literal value assignment. Use QDeclarativeDomValue::toLiteral() to access the type instance.
PropertyBinding The QDeclarativeDomValue is a property binding. Use QDeclarativeDomValue::toBinding() to access the type instance.
ValueSource The QDeclarativeDomValue is a property value source. Use QDeclarativeDomValue::toValueSource() to access the type instance.
ValueInterceptor The QDeclarativeDomValue is a property value interceptor. Use QDeclarativeDomValue::toValueInterceptor() to access the type instance.
Object The QDeclarativeDomValue is an object assignment. Use QDeclarativeDomValue::toObject() to access the type instnace.
List The QDeclarativeDomValue is a list of other values. Use QDeclarativeDomValue::toList() to access the type instance.
Enumerator
Invalid
Literal
PropertyBinding
ValueSource
ValueInterceptor
Object
List
Definition at line 276 of file qdeclarativedom_p.h.
               {
         Invalid,
         Literal,
         PropertyBinding,
         ValueSource,
         ValueInterceptor,
         Object,
         List
     };
Constructors and Destructors
QDeclarativeDomValue() [1/2]
QDeclarativeDomValue::QDeclarativeDomValue ()
Construct an invalid QDeclarativeDomValue.
Definition at line 1315 of file qdeclarativedom.cpp.
 : d(new QDeclarativeDomValuePrivate)
 {
 }
QDeclarativeDomValue() [2/2]
QDeclarativeDomValue::QDeclarativeDomValue (const QDeclarativeDomValue & other)
Create a copy of other QDeclarativeDomValue.
Definition at line 1323 of file qdeclarativedom.cpp.
 : d(other.d)
 {
 }
~QDeclarativeDomValue()
QDeclarativeDomValue::~QDeclarativeDomValue ()
Destroy the QDeclarativeDomValue.
Definition at line 1331 of file qdeclarativedom.cpp.
 {
 }
Functions
isBinding()
bool QDeclarativeDomValue::isBinding () const
Returns true if this is a property binding value, otherwise false.
Definition at line 1417 of file qdeclarativedom.cpp.
 {
     return type() == PropertyBinding;
 }
isInvalid()
bool QDeclarativeDomValue::isInvalid () const
Returns true if this is an invalid value, otherwise false.
Definition at line 1401 of file qdeclarativedom.cpp.
 {
     return type() == Invalid;
 }
isList()
bool QDeclarativeDomValue::isList () const
Returns true if this is a list value, otherwise false.
Definition at line 1449 of file qdeclarativedom.cpp.
 {
     return type() == List;
 }
isLiteral()
bool QDeclarativeDomValue::isLiteral () const
Returns true if this is a literal value, otherwise false.
Definition at line 1409 of file qdeclarativedom.cpp.
 {
     return type() == Literal;
 }
isObject()
bool QDeclarativeDomValue::isObject () const
Returns true if this is an object value, otherwise false.
Definition at line 1441 of file qdeclarativedom.cpp.
 {
     return type() == Object;
 }
isValueInterceptor()
bool QDeclarativeDomValue::isValueInterceptor () const
Returns true if this is a value interceptor value, otherwise false.
Definition at line 1433 of file qdeclarativedom.cpp.
 {
     return type() == ValueInterceptor;
 }
isValueSource()
bool QDeclarativeDomValue::isValueSource () const
Returns true if this is a value source value, otherwise false.
Definition at line 1425 of file qdeclarativedom.cpp.
 {
     return type() == ValueSource;
 }
length()
int QDeclarativeDomValue::length () const
Returns the length in the input data from where the property value started u
pto the end of it, or -1 if the value is invalid.
Definition at line 1565 of file qdeclarativedom.cpp.
 {
     if (type() == Invalid)
         return -1;
     else
         return d->value->location.range.length;
 }
operator=()
QDeclarativeDomValue & QDeclarativeDomValue::operator= (const QDeclarativeDomValue & other)
Assign other to this QDeclarativeDomValue.
Definition at line 1338 of file qdeclarativedom.cpp.
 {
     d = other.d;
     return *this;
 }
position()
int QDeclarativeDomValue::position () const
Returns the position in the input data where the property value startd, or -1 if the value is invalid.
Definition at line 1553 of file qdeclarativedom.cpp.
 {
     if (type() == Invalid)
         return -1;
     else
         return d->value->location.range.offset;
 }
toBinding()
QDeclarativeDomValueBinding QDeclarativeDomValue::toBinding () const
Returns a QDeclarativeDomValueBinding if this value is a property binding type, otherwise returns an invalid QDeclarativeDomValueBinding.
See also
QDeclarativeDomValue::type()
Definition at line 1476 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomValueBinding rv;
     if (type() == PropertyBinding) {
         rv.d->value = d->value;
         rv.d->value->addref();
     }
     return rv;
 }
toList()
QDeclarativeDomList QDeclarativeDomValue::toList () const
Returns a QDeclarativeDomList if this value is a list type, otherwise returns an invalid QDeclarativeDomList.
See also
QDeclarativeDomValue::type()
Definition at line 1540 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomList rv;
     if (type() == List) {
         rv.d = d;
     }
     return rv;
 }
toLiteral()
QDeclarativeDomValueLiteral QDeclarativeDomValue::toLiteral () const
Returns a QDeclarativeDomValueLiteral if this value is a literal type, otherwise returns an invalid QDeclarativeDomValueLiteral.
See also
QDeclarativeDomValue::type()
Definition at line 1460 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomValueLiteral rv;
     if (type() == Literal) {
         rv.d->value = d->value;
         rv.d->value->addref();
     }
     return rv;
 }
toObject()
QDeclarativeDomObject QDeclarativeDomValue::toObject () const
Returns a QDeclarativeDomObject if this value is an object assignment type, otherwise returns an invalid QDeclarativeDomObject.
See also
QDeclarativeDomValue::type()
Definition at line 1524 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomObject rv;
     if (type() == Object) {
         rv.d->object = d->value->object;
         rv.d->object->addref();
     }
     return rv;
 }
toValueInterceptor()
QDeclarativeDomValueValueInterceptor QDeclarativeDomValue::toValueInterceptor () const
Returns a QDeclarativeDomValueValueInterceptor if this value is a property value interceptor type, otherwise returns an invalid QDeclarativeDomValueValueInterceptor.
See also
QDeclarativeDomValue::type()
Definition at line 1508 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomValueValueInterceptor rv;
     if (type() == ValueInterceptor) {
         rv.d->value = d->value;
         rv.d->value->addref();
     }
     return rv;
 }
toValueSource()
QDeclarativeDomValueValueSource QDeclarativeDomValue::toValueSource () const
Returns a QDeclarativeDomValueValueSource if this value is a property value source type, otherwise returns an invalid QDeclarativeDomValueValueSource.
See also
QDeclarativeDomValue::type()
Definition at line 1492 of file qdeclarativedom.cpp.
 {
     QDeclarativeDomValueValueSource rv;
     if (type() == ValueSource) {
         rv.d->value = d->value;
         rv.d->value->addref();
     }
     return rv;
 }
type()
QDeclarativeDomValue::Type QDeclarativeDomValue::type () const
Returns the type of this QDeclarativeDomValue.
Definition at line 1364 of file qdeclarativedom.cpp.
Referenced by isBinding(), isInvalid(), isList(), isLiteral(), isObject(), isValueInterceptor(), isValueSource(), length(), position(), toBinding(), toList(), toLiteral(), toObject(), toValueInterceptor(), and toValueSource().
 {
     if (d->property)
         if (QDeclarativeMetaType::isList(d->property->type) ||
            (d->property && (d->property->values.count() + d->property->onValues.count()) > 1))
             return List;
     QDeclarativeParser::Value *value = d->value;
     if (!value && !d->property)
         return Invalid;
     switch(value->type) {
     case QDeclarativeParser::Value::Unknown:
         return Invalid;
     case QDeclarativeParser::Value::Literal:
         return Literal;
     case QDeclarativeParser::Value::PropertyBinding:
         return PropertyBinding;
     case QDeclarativeParser::Value::ValueSource:
         return ValueSource;
     case QDeclarativeParser::Value::ValueInterceptor:
         return ValueInterceptor;
     case QDeclarativeParser::Value::CreatedObject:
         return Object;
     case QDeclarativeParser::Value::SignalObject:
         return Invalid;
     case QDeclarativeParser::Value::SignalExpression:
         return Literal;
     case QDeclarativeParser::Value::Id:
         return Literal;
     }
     return Invalid;
 }
Friends and Related Functions
QDeclarativeDomList
friend class QDeclarativeDomList friend
Definition at line 313 of file qdeclarativedom_p.h.
QDeclarativeDomProperty
friend class QDeclarativeDomProperty friend
Definition at line 312 of file qdeclarativedom_p.h.
Properties
d
QSharedDataPointer<QDeclarativeDomValuePrivate> QDeclarativeDomValue::d private
Definition at line 314 of file qdeclarativedom_p.h.
Referenced by length(), operator=(), position(), toBinding(), toList(), toLiteral(), toObject(), toValueInterceptor(), toValueSource(), type(), QDeclarativeDomProperty::value(), and QDeclarativeDomList::values().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativedom_p.h
/src/declarative/qml/qdeclarativedom.cpp