Qt 4.8: QSupportedWritingSystems Class Reference
QSupportedWritingSystems Class Reference
The QSupportedWritingSystems class is used when registering fonts with the internal Qt fontdatabase.
#include <qplatformfontdatabase_qpa.h>
Public Functions
QSupportedWritingSystems & operator= (const QSupportedWritingSystems &other)
Assigns the other supported writing systems object to this object.
QSupportedWritingSystems ()
QSupportedWritingSystems (const QSupportedWritingSystems &other)
void setSupported (QFontDatabase::WritingSystem, bool supported=true)
Sets the supported state of the writing system given by writingSystem to the value specified by support.
bool supported (QFontDatabase::WritingSystem) const
Returns true if the writing system given by writingSystem is supported; otherwise returns false.
~QSupportedWritingSystems ()
Destroys the object.
Private Functions
void detach ()
Properties
QWritingSystemsPrivate * d
Friends
Q_GUI_EXPORT bool operator!= (const QSupportedWritingSystems &, const QSupportedWritingSystems &)
Q_GUI_EXPORT bool operator== (const QSupportedWritingSystems &, const QSupportedWritingSystems &)
Detailed Description
The QSupportedWritingSystems class is used when registering fonts with the internal Qt fontdatabase.
Since
4.8
Its to provide an easy to use interface for indicating what writing systems a specific font supports.
Definition at line 60 of file qplatformfontdatabase_qpa.h.
Constructors and Destructors
QSupportedWritingSystems() [1/2]
QSupportedWritingSystems::QSupportedWritingSystems ()
Definition at line 152 of file qplatformfontdatabase_qpa.cpp.
 {
     d = new QWritingSystemsPrivate;
 }
QSupportedWritingSystems() [2/2]
QSupportedWritingSystems::QSupportedWritingSystems (const QSupportedWritingSystems & other)
Definition at line 157 of file qplatformfontdatabase_qpa.cpp.
 {
     d = other.d;
     d->ref.ref();
 }
~QSupportedWritingSystems()
QSupportedWritingSystems::~QSupportedWritingSystems ()
Destroys the object.
Definition at line 180 of file qplatformfontdatabase_qpa.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
detach()
void QSupportedWritingSystems::detach () private
Definition at line 186 of file qplatformfontdatabase_qpa.cpp.
 {
     if (d->ref != 1) {
         QWritingSystemsPrivate *newd = new QWritingSystemsPrivate(d);
         if (!d->ref.deref())
             delete d;
         d = newd;
     }
 }
operator=()
QSupportedWritingSystems & QSupportedWritingSystems::operator= (const QSupportedWritingSystems & other)
Assigns the other supported writing systems object to this object.
Definition at line 166 of file qplatformfontdatabase_qpa.cpp.
 {
     if (d != other.d) {
         other.d->ref.ref();
         if (!d->ref.deref())
             delete d;
         d = other.d;
     }
     return *this;
 }
setSupported()
void QSupportedWritingSystems::setSupported (QFontDatabase::WritingSystem writingSystem, bool support = true)
Sets the supported state of the writing system given by writingSystem to the value specified by support.
A value of true indicates that the writing system is supported; a value of false indicates that it is unsupported.
See also
supported()
Definition at line 204 of file qplatformfontdatabase_qpa.cpp.
Referenced by QBasicUnixFontDatabase::addTTFile(), determineWritingSystemsFromTrueTypeBits(), QFontconfigDatabase::populateFontDatabase(), QCoreTextFontDatabase::populateFontDatabase(), and QPlatformFontDatabase::registerQPF2Font().
 {
     detach();
     d->vector[writingSystem] = support;
 }
supported()
bool QSupportedWritingSystems::supported (QFontDatabase::WritingSystem writingSystem) const
Returns true if the writing system given by writingSystem is supported; otherwise returns false.
See also
setSupported()
Definition at line 216 of file qplatformfontdatabase_qpa.cpp.
Referenced by QFontconfigDatabase::populateFontDatabase(), and qt_registerFont().
 {
     return d->vector.at(writingSystem);
 }
Friends and Related Functions
operator!=
Q_GUI_EXPORT bool operator!= (const QSupportedWritingSystems & , const QSupportedWritingSystems &) friend
operator==
Q_GUI_EXPORT bool operator== (const QSupportedWritingSystems & , const QSupportedWritingSystems &) friend
Properties
d
QWritingSystemsPrivate* QSupportedWritingSystems::d private
Definition at line 75 of file qplatformfontdatabase_qpa.h.
Referenced by operator=(), and QSupportedWritingSystems().
The documentation for this class was generated from the following files:
/src/gui/text/qplatformfontdatabase_qpa.h
/src/gui/text/qplatformfontdatabase_qpa.cpp