Qt 4.8: QLineEdit Class Reference
QLineEdit Class Reference
The QLineEdit widget is a one-line text editor.
#include <qlineedit.h>
Public Types
enum EchoMode { Normal, NoEcho, Password, PasswordEchoOnEdit }
This enum type describes how a line edit should display its contents.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void clear ()
Clears the contents of the line edit.
void copy () const
Copies the selected text to the clipboard, if there is any, and if echoMode() is Normal .
void cut ()
Copies the selected text to the clipboard and deletes it, if there is any, and if echoMode() is Normal .
void paste ()
Inserts the clipboard's text at the cursor position, deleting any selected text, providing the line edit is not read-only.
void redo ()
Redoes the last operation if redo is available.
void selectAll ()
Selects all the text (i.e.
void setText (const QString &)
void undo ()
Undoes the last operation if undo is available.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void cursorPositionChanged (int, int)
This signal is emitted whenever the cursor moves.
void editingFinished ()
This signal is emitted when the Return or Enter key is pressed or the line edit loses focus.
void returnPressed ()
This signal is emitted when the Return or Enter key is pressed.
void selectionChanged ()
This signal is emitted whenever the selection changes.
void textChanged (const QString &)
This signal is emitted whenever the text changes.
void textEdited (const QString &)
This signal is emitted whenever the text is edited.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::Alignment alignment () const
void backspace ()
If no text is selected, deletes the character to the left of the text cursor and moves the cursor one position to the left.
QCompleter * completer () const
Returns the current QCompleter that provides completions.
QMenu * createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the line edit with the right mouse button.
void cursorBackward (bool mark, int steps=1)
Moves the cursor back steps characters.
void cursorForward (bool mark, int steps=1)
Moves the cursor forward steps characters.
Qt::CursorMoveStyle cursorMoveStyle () const
int cursorPosition () const
int cursorPositionAt (const QPoint &pos)
Returns the cursor position under the point pos.
void cursorWordBackward (bool mark)
Moves the cursor one word backward.
void cursorWordForward (bool mark)
Moves the cursor one word forward.
void del ()
If no text is selected, deletes the character to the right of the text cursor.
void deselect ()
Deselects any selected text.
QString displayText () const
bool dragEnabled () const
EchoMode echoMode () const
void end (bool mark)
Moves the text cursor to the end of the line unless it is already there.
bool event (QEvent *)
Reimplemented Function
void getTextMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's text margins for left, top, right, and bottom.
bool hasAcceptableInput () const
bool hasFrame () const
bool hasSelectedText () const
void home (bool mark)
Moves the text cursor to the beginning of the line unless it is already there.
QString inputMask () const
QVariant inputMethodQuery (Qt::InputMethodQuery) const
em>Reimplemented Function
void insert (const QString &)
Deletes any selected text, inserts newText, and validates the result.
bool isModified () const
bool isReadOnly () const
bool isRedoAvailable () const
bool isUndoAvailable () const
int maxLength () const
QSize minimumSizeHint () const
Returns a minimum size for the line edit.
QString placeholderText () const
QLineEdit (QWidget *parent=0)
Constructs a line edit with no text.
QLineEdit (const QString &, QWidget *parent=0)
Constructs a line edit containing the text contents.
QString selectedText () const
int selectionStart () const
selectionStart() returns the index of the first selected character in the line edit or -1 if no text is selected.
void setAlignment (Qt::Alignment flag)
void setCompleter (QCompleter *completer)
Sets this line edit to provide auto completions from the completer, c.
void setCursorMoveStyle (Qt::CursorMoveStyle style)
Sets the movement style for the cursor in the line edit to the given style.
void setCursorPosition (int)
void setDragEnabled (bool b)
void setEchoMode (EchoMode)
void setFrame (bool)
void setInputMask (const QString &inputMask)
void setMaxLength (int)
void setModified (bool)
void setPlaceholderText (const QString &)
void setReadOnly (bool)
void setSelection (int, int)
Selects text from position start and for length characters.
void setTextMargins (int left, int top, int right, int bottom)
Sets the margins around the text inside the frame to have the sizes left, top, right, and bottom.
void setTextMargins (const QMargins &margins)
Sets the margins around the text inside the frame.
void setValidator (const QValidator *)
Sets this line edit to only accept input that the validator, v, will accept.
QSize sizeHint () const
Returns a recommended size for the widget.
QString text () const
QMargins textMargins () const
Returns the widget's text margins.
const QValidator * validator () const
Returns a pointer to the current input validator, or 0 if no validator has been set.
~QLineEdit ()
Destroys the line edit.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *)
Shows the standard context menu created with createStandardContextMenu().
QRect cursorRect () const
Returns a rectangle that includes the lineedit cursor.
void dragEnterEvent (QDragEnterEvent *)
em>Reimplemented Function
void dragLeaveEvent (QDragLeaveEvent *e)
em>Reimplemented Function
void dragMoveEvent (QDragMoveEvent *e)
em>Reimplemented Function
void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
void focusInEvent (QFocusEvent *)
em>Reimplemented Function
void focusOutEvent (QFocusEvent *)
em>Reimplemented Function
void initStyleOption (QStyleOptionFrame *option) const
Initialize option with the values from this QLineEdit.
void inputMethodEvent (QInputMethodEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
Converts the given key press event into a line edit action.
void mouseDoubleClickEvent (QMouseEvent *)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *)
Reimplemented Function
void mousePressEvent (QMouseEvent *)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *)
Reimplemented Function
void paintEvent (QPaintEvent *)
em>Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool acceptableInput
whether the input satisfies the inputMask and the validator.
Qt::Alignment alignment
the alignment of the line edit
Qt::CursorMoveStyle cursorMoveStyle
the movement style of cursor in this line edit
int cursorPosition
the current cursor position for this line edit
QString displayText
the displayed text
bool dragEnabled
whether the lineedit starts a drag if the user presses and moves the mouse on some selected text
EchoMode echoMode
the line edit's echo mode
bool frame
whether the line edit draws itself with a frame
bool hasSelectedText
whether there is any text selected
QString inputMask
The validation input mask.
int maxLength
the maximum permitted length of the text
bool modified
whether the line edit's contents has been modified by the user
QString placeholderText
the line edit's placeholder text
bool readOnly
whether the line edit is read only.
bool redoAvailable
whether redo is available
QString selectedText
the selected text
QString text
the line edit's text
bool undoAvailable
whether undo is available
Friends
class QAbstractSpinBox
class QAccessibleLineEdit
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QLineEdit widget is a one-line text editor.
A line edit allows the user to enter and edit a single line of plain text with a useful collection of editing functions, including undo and redo, cut and paste, and drag and drop.
By changing the echoMode() of a line edit, it can also be used as a "write-only" field, for inputs such as passwords.
The length of the text can be constrained to maxLength(). The text can be arbitrarily constrained using a validator() or an inputMask(), or both. When switching between a validator and an input mask on the same line edit, it is best to clear the validator or input mask to prevent undefined behavior.
A related class is QTextEdit which allows multi-line, rich text editing.
You can change the text with setText() or insert(). The text is retrieved with text(); the displayed text (which may be different, see EchoMode) is retrieved with displayText(). Text can be selected with setSelection() or selectAll(), and the selection can be cut(), copy()ied and paste()d. The text can be aligned with setAlignment().
When the text changes the textChanged() signal is emitted; when the text changes other than by calling setText() the textEdited() signal is emitted; when the cursor is moved the cursorPositionChanged() signal is emitted; and when the Return or Enter key is pressed the returnPressed() signal is emitted.
When editing is finished, either because the line edit lost focus or Return/Enter is pressed the editingFinished() signal is emitted.
Note that if there is a validator set on the line edit, the returnPressed()/editingFinished() signals will only be emitted if the validator returns QValidator::Acceptable.
By default, QLineEdits have a frame as specified by the Windows and Motif style guides; you can turn it off by calling setFrame(false).
The default key bindings are described below. The line edit also provides a context menu (usually invoked by a right mouse click) that presents some of these editing options.
Keypress Action
Left Arrow Moves the cursor one character to the left.
Shift+Left Arrow Moves and selects text one character to the left.
Right Arrow Moves the cursor one character to the right.
Shift+Right Arrow Moves and selects text one character to the right.
Home Moves the cursor to the beginning of the line.
End Moves the cursor to the end of the line.
Backspace Deletes the character to the left of the cursor.
Ctrl+Backspace Deletes the word to the left of the cursor.
Delete Deletes the character to the right of the cursor.
Ctrl+Delete Deletes the word to the right of the cursor.
Ctrl+A Select all.
Ctrl+C Copies the selected text to the clipboard.
Ctrl+Insert Copies the selected text to the clipboard.
Ctrl+K Deletes to the end of the line.
Ctrl+V Pastes the clipboard text into line edit.
Shift+Insert Pastes the clipboard text into line edit.
Ctrl+X Deletes the selected text and copies it to the clipboard.
Shift+Delete Deletes the selected text and copies it to the clipboard.
Ctrl+Z Undoes the last operation.
Ctrl+Y Redoes the last undone operation.
Any other key sequence that represents a valid character, will cause the character to be inserted into the line edit.
Screenshot of a Macintosh style line edit
A line edit shown in the Macintosh Style Widget Gallery{Macintosh widget style}.
Screenshot of a Windows XP style line edit
A line edit shown in the Windows XP Style Widget Gallery{Windows XP widget style}.
Screenshot of a Plastique style line edit
A line edit shown in the Plastique Style Widget Gallery{Plastique widget style}.
See also
QTextEdit, QLabel, QComboBox, {fowler}{GUI Design Handbook: Field, Entry}, {Line Edits Example}
Definition at line 66 of file qlineedit.h.
Enumerations
EchoMode
enum QLineEdit::EchoMode
This enum type describes how a line edit should display its contents.
Normal Display characters as they are entered. This is the default.
NoEcho Do not display anything. This may be appropriate for passwords where even the length of the password should be kept secret.
Password Display asterisks instead of the characters actually entered.
PasswordEchoOnEdit Display characters as they are entered while editing otherwise display asterisks.
See also
setEchoMode() echoMode()
Enumerator
Normal
NoEcho
Password
PasswordEchoOnEdit
Definition at line 113 of file qlineedit.h.
 { Normal, NoEcho, Password, PasswordEchoOnEdit };
Constructors and Destructors
QLineEdit() [1/2]
QLineEdit::QLineEdit (QWidget * parent = 0) explicit
Constructs a line edit with no text.
The maximum text length is set to 32767 characters.
The parent argument is sent to the QWidget constructor.
See also
setText(), setMaxLength()
Definition at line 280 of file qlineedit.cpp.
Referenced by QLineEdit().
     : QWidget(*new QLineEditPrivate, parent,0)
 {
     Q_D(QLineEdit);
     d->init(QString());
 }
QLineEdit() [2/2]
QLineEdit::QLineEdit (const QString & contents, QWidget * parent = 0) explicit
Constructs a line edit containing the text contents.
The cursor position is set to the end of the line and the maximum text length to 32767 characters.
The parent and argument is sent to the QWidget constructor.
See also
text(), setMaxLength()
Definition at line 298 of file qlineedit.cpp.
     : QWidget(*new QLineEditPrivate, parent, 0)
 {
     Q_D(QLineEdit);
     d->init(contents);
 }
~QLineEdit()
QLineEdit::~QLineEdit ()
Destroys the line edit.
Definition at line 372 of file qlineedit.cpp.
 {
 }
Functions
alignment()
Qt::Alignment QLineEdit::alignment () const
Referenced by cursorPositionAt(), and setAlignment().
backspace()
void QLineEdit::backspace ()
If no text is selected, deletes the character to the left of the text cursor and moves the cursor one position to the left.
If any text is selected, the cursor is moved to the beginning of the selected text and the selected text is deleted.
See also
del()
Definition at line 896 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->backspace();
 }
changeEvent()
void QLineEdit::changeEvent (QEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2299 of file qlineedit.cpp.
Referenced by QExpandingLineEdit::changeEvent().
 {
     Q_D(QLineEdit);
     switch(ev->type())
     {
     case QEvent::ActivationChange:
         if (!palette().isEqual(QPalette::Active, QPalette::Inactive))
             update();
         break;
     case QEvent::FontChange:
         d->control->setFont(font());
         break;
     case QEvent::StyleChange:
         {
             QStyleOptionFrameV2 opt;
             initStyleOption(&opt);
             d->control->setPasswordCharacter(style()->styleHint(QStyle::SH_LineEdit_PasswordCharacter, &opt, this));
         }
         update();
         break;
     default:
         break;
     }
     QWidget::changeEvent(ev);
 }
clear
void QLineEdit::clear () slot
Clears the contents of the line edit.
See also
setText(), insert()
Definition at line 1443 of file qlineedit.cpp.
Referenced by QFileDialogPrivate::_q_enterDirectory(), inputMethodEvent(), and QScriptNewBreakpointWidget::onOkClicked().
 {
     Q_D(QLineEdit);
     resetInputContext();
     d->control->clear();
 }
completer()
QCompleter * QLineEdit::completer () const
Returns the current QCompleter that provides completions.
Since
4.2
Definition at line 686 of file qlineedit.cpp.
Referenced by QComboBoxPrivate::matchFlags().
 {
     Q_D(const QLineEdit);
     return d->control->completer();
 }
contextMenuEvent()
void QLineEdit::contextMenuEvent (QContextMenuEvent * event) protected virtual
Shows the standard context menu created with createStandardContextMenu().
If you do not want the line edit to have a context menu, you can set its contextMenuPolicy to Qt::NoContextMenu. If you want to customize the context menu, reimplement this function. If you want to extend the standard context menu, reimplement this function, call createStandardContextMenu() and extend the menu returned.
void LineEdit::contextMenuEvent(QContextMenuEvent *event)
{
    QMenu *menu = createStandardContextMenu();
    menu->addAction(tr("My Menu Item"));
    //...
    menu->exec(event->globalPos());
    delete menu;
}
The event parameter is used to obtain the position where the mouse cursor was when the event was generated.
See also
setContextMenuPolicy()
Reimplemented from QWidget.
Definition at line 2205 of file qlineedit.cpp.
 {
     if (QMenu *menu = createStandardContextMenu()) {
         menu->setAttribute(Qt::WA_DeleteOnClose);
         menu->popup(event->globalPos());
     }
 }
copy
void QLineEdit::copy () const slot
Copies the selected text to the clipboard, if there is any, and if echoMode() is Normal .
See also
cut() paste()
Definition at line 1541 of file qlineedit.cpp.
Referenced by createStandardContextMenu(), and cut().
 {
     Q_D(const QLineEdit);
     d->control->copy();
 }
createStandardContextMenu()
QMenu * QLineEdit::createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the line edit with the right mouse button.
It is called from the default contextMenuEvent() handler. The popup menu's ownership is transferred to the caller.
Definition at line 2223 of file qlineedit.cpp.
Referenced by contextMenuEvent().
 {
     Q_D(QLineEdit);
     QMenu *popup = new QMenu(this);
     popup->setObjectName(QLatin1String("qt_edit_menu"));
     QAction *action = 0;
     if (!isReadOnly()) {
         action = popup->addAction(QLineEdit::tr("&Undo") + ACCEL_KEY(QKeySequence::Undo));
         action->setEnabled(d->control->isUndoAvailable());
         connect(action, SIGNAL(triggered()), SLOT(undo()));
         action = popup->addAction(QLineEdit::tr("&Redo") + ACCEL_KEY(QKeySequence::Redo));
         action->setEnabled(d->control->isRedoAvailable());
         connect(action, SIGNAL(triggered()), SLOT(redo()));
         popup->addSeparator();
     }
 #ifndef QT_NO_CLIPBOARD
     if (!isReadOnly()) {
         action = popup->addAction(QLineEdit::tr("Cu&t") + ACCEL_KEY(QKeySequence::Cut));
         action->setEnabled(!d->control->isReadOnly() && d->control->hasSelectedText()
                 && d->control->echoMode() == QLineEdit::Normal);
         connect(action, SIGNAL(triggered()), SLOT(cut()));
     }
     action = popup->addAction(QLineEdit::tr("&Copy") + ACCEL_KEY(QKeySequence::Copy));
     action->setEnabled(d->control->hasSelectedText()
             && d->control->echoMode() == QLineEdit::Normal);
     connect(action, SIGNAL(triggered()), SLOT(copy()));
     if (!isReadOnly()) {
         action = popup->addAction(QLineEdit::tr("&Paste") + ACCEL_KEY(QKeySequence::Paste));
         action->setEnabled(!d->control->isReadOnly() && !QApplication::clipboard()->text().isEmpty());
         connect(action, SIGNAL(triggered()), SLOT(paste()));
     }
 #endif
     if (!isReadOnly()) {
         action = popup->addAction(QLineEdit::tr("Delete"));
         action->setEnabled(!d->control->isReadOnly() && !d->control->text().isEmpty() && d->control->hasSelectedText());
         connect(action, SIGNAL(triggered()), d->control, SLOT(_q_deleteSelected()));
     }
     if (!popup->isEmpty())
         popup->addSeparator();
     action = popup->addAction(QLineEdit::tr("Select All") + ACCEL_KEY(QKeySequence::SelectAll));
     action->setEnabled(!d->control->text().isEmpty() && !d->control->allSelected());
     d->selectAllAction = action;
     connect(action, SIGNAL(triggered()), SLOT(selectAll()));
 #if !defined(QT_NO_IM)
     QInputContext *qic = inputContext();
     if (qic) {
         QList<QAction *> imActions = qic->actions();
         for (int i = 0; i < imActions.size(); ++i)
             popup->addAction(imActions.at(i));
     }
 #endif
 #if defined(Q_WS_WIN) || defined(Q_WS_X11)
     if (!d->control->isReadOnly() && qt_use_rtl_extensions) {
 #else
     if (!d->control->isReadOnly()) {
 #endif
         popup->addSeparator();
         QUnicodeControlCharacterMenu *ctrlCharacterMenu = new QUnicodeControlCharacterMenu(this, popup);
         popup->addMenu(ctrlCharacterMenu);
     }
     return popup;
 }
cursorBackward()
void QLineEdit::cursorBackward (bool mark, int steps = 1)
Moves the cursor back steps characters.
If mark is true each character moved over is added to the selection; if mark is false the selection is cleared.
See also
cursorForward()
Definition at line 857 of file qlineedit.cpp.
 {
     cursorForward(mark, -steps);
 }
cursorForward()
void QLineEdit::cursorForward (bool mark, int steps = 1)
Moves the cursor forward steps characters.
If mark is true each character moved over is added to the selection; if mark is false the selection is cleared.
See also
cursorBackward()
Definition at line 843 of file qlineedit.cpp.
Referenced by cursorBackward().
 {
     Q_D(QLineEdit);
     d->control->cursorForward(mark, steps);
 }
cursorMoveStyle()
Qt::CursorMoveStyle QLineEdit::cursorMoveStyle () const
Referenced by setDragEnabled().
cursorPosition()
int QLineEdit::cursorPosition () const
Referenced by minimumSizeHint().
cursorPositionAt()
int QLineEdit::cursorPositionAt (const QPoint & pos)
Returns the cursor position under the point pos.
Definition at line 768 of file qlineedit.cpp.
Referenced by QAccessibleLineEdit::offsetAtPoint().
 {
     Q_D(QLineEdit);
     return d->xToPos(pos.x());
 }
cursorPositionChanged
void QLineEdit::cursorPositionChanged (int old, int new) signal
This signal is emitted whenever the cursor moves.
The previous position is given by old, and the new position by new.
See also
setCursorPosition(), cursorPosition()
cursorRect()
QRect QLineEdit::cursorRect () const protected
Returns a rectangle that includes the lineedit cursor.
Since
4.4
Definition at line 1825 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     return d->cursorRect();
 }
cursorWordBackward()
void QLineEdit::cursorWordBackward (bool mark)
Moves the cursor one word backward.
If mark is true, the word is also selected.
See also
cursorWordForward()
Definition at line 881 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->cursorWordBackward(mark);
 }
cursorWordForward()
void QLineEdit::cursorWordForward (bool mark)
Moves the cursor one word forward.
If mark is true, the word is also selected.
See also
cursorWordBackward()
Definition at line 868 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->cursorWordForward(mark);
 }
cut
void QLineEdit::cut () slot
Copies the selected text to the clipboard and deletes it, if there is any, and if echoMode() is Normal .
If the current validator disallows deleting the selected text, cut() will copy without deleting.
See also
copy() paste() setValidator()
Definition at line 1525 of file qlineedit.cpp.
Referenced by createStandardContextMenu().
 {
     if (hasSelectedText()) {
         copy();
         del();
     }
 }
del()
void QLineEdit::del ()
If no text is selected, deletes the character to the right of the text cursor.
If any text is selected, the cursor is moved to the beginning of the selected text and the selected text is deleted.
See also
backspace()
Definition at line 910 of file qlineedit.cpp.
Referenced by cut().
 {
     Q_D(QLineEdit);
     d->control->del();
 }
deselect()
void QLineEdit::deselect ()
Deselects any selected text.
See also
setSelection() selectAll()
Definition at line 1417 of file qlineedit.cpp.
Referenced by QComboBoxPrivate::_q_returnPressed(), dropEvent(), focusOutEvent(), mouseReleaseEvent(), and QAccessibleLineEdit::removeSelection().
 {
     Q_D(QLineEdit);
     d->control->deselect();
 }
displayText()
QString QLineEdit::displayText () const
Referenced by QExpandingLineEdit::resizeToContents(), and setPlaceholderText().
dragEnabled()
bool QLineEdit::dragEnabled () const
Referenced by isRedoAvailable().
dragEnterEvent()
void QLineEdit::dragEnterEvent (QDragEnterEvent * e) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 2135 of file qlineedit.cpp.
dragLeaveEvent()
void QLineEdit::dragLeaveEvent (QDragLeaveEvent * e) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 2141 of file qlineedit.cpp.
dragMoveEvent()
void QLineEdit::dragMoveEvent (QDragMoveEvent * e) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 2123 of file qlineedit.cpp.
Referenced by dragEnterEvent().
dropEvent()
void QLineEdit::dropEvent (QDropEvent * event) protected virtual
This event handler is called when the drag is dropped on this widget.
The event is passed in the event parameter.
See the Drag-and-drop documentation for an overview of how to provide drag-and-drop in your application.
See also
QDrag, QDropEvent
Reimplemented from QWidget.
Definition at line 2151 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     QString str = e->mimeData()->text();
     if (!str.isNull() && !d->control->isReadOnly()) {
         if (e->source() == this && e->dropAction() == Qt::CopyAction)
             deselect();
         int cursorPos = d->xToPos(e->pos().x());
         int selStart = cursorPos;
         int oldSelStart = d->control->selectionStart();
         int oldSelEnd = d->control->selectionEnd();
         d->control->moveCursor(cursorPos, false);
         d->cursorVisible = false;
         e->acceptProposedAction();
         insert(str);
         if (e->source() == this) {
             if (e->dropAction() == Qt::MoveAction) {
                 if (selStart > oldSelStart && selStart <= oldSelEnd)
                     setSelection(oldSelStart, str.length());
                 else if (selStart > oldSelEnd)
                     setSelection(selStart - str.length(), str.length());
                 else
                     setSelection(selStart, str.length());
             } else {
                 setSelection(selStart, str.length());
             }
         }
     } else {
         e->ignore();
         update();
     }
 }
echoMode()
EchoMode QLineEdit::echoMode () const
Referenced by inputMethodEvent(), and setFrame().
editingFinished
void QLineEdit::editingFinished () signal
This signal is emitted when the Return or Enter key is pressed or the line edit loses focus.
Note that if there is a validator() or inputMask() set on the line edit and enter/return is pressed, the editingFinished() signal will only be emitted if the input follows the inputMask() and the validator() returns QValidator::Acceptable.
Referenced by event(), and focusOutEvent().
end()
void QLineEdit::end (bool mark)
Moves the text cursor to the end of the line unless it is already there.
If mark is true, text is selected towards the last position; otherwise, any selected text is unselected if the cursor is moved.
See also
home()
Definition at line 940 of file qlineedit.cpp.
Referenced by QComboBoxPrivate::_q_returnPressed(), event(), and selectionStart().
 {
     Q_D(QLineEdit);
     d->control->end(mark);
 }
event()
bool QLineEdit::event (QEvent * e) virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1568 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (e->type() == QEvent::Timer) {
         // should be timerEvent, is here for binary compatibility
         int timerId = ((QTimerEvent*)e)->timerId();
         if (false) {
 #ifndef QT_NO_DRAGANDDROP
         } else if (timerId == d->dndTimer.timerId()) {
             d->drag();
 #endif
         }
         else if (timerId == d->tripleClickTimer.timerId())
             d->tripleClickTimer.stop();
     } else if (e->type() == QEvent::ContextMenu) {
 #ifndef QT_NO_IM
         if (d->control->composeMode())
             return true;
 #endif
         //d->separate();
     } else if (e->type() == QEvent::WindowActivate) {
         QTimer::singleShot(0, this, SLOT(_q_handleWindowActivate()));
     }else if(e->type() == QEvent::ShortcutOverride){
         d->control->processEvent(e);
     } else if (e->type() == QEvent::KeyRelease) {
         d->control->setCursorBlinkPeriod(QApplication::cursorFlashTime());
     } else if (e->type() == QEvent::Show) {
         //In order to get the cursor blinking if QComboBox::setEditable is called when the combobox has focus
         if (hasFocus()) {
             d->control->setCursorBlinkPeriod(QApplication::cursorFlashTime());
             QStyleOptionFrameV2 opt;
             initStyleOption(&opt);
             if ((!hasSelectedText() && d->control->preeditAreaText().isEmpty())
                 || style()->styleHint(QStyle::SH_BlinkCursorWhenTextSelected, &opt, this))
                 d->setCursorVisible(true);
         }
     }
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled()) {
         if (e->type() == QEvent::EnterEditFocus) {
             end(false);
             d->setCursorVisible(true);
             d->control->setCursorBlinkPeriod(QApplication::cursorFlashTime());
         } else if (e->type() == QEvent::LeaveEditFocus) {
             d->setCursorVisible(false);
             d->control->setCursorBlinkPeriod(0);
             if (d->control->hasAcceptableInput() || d->control->fixup())
                 emit editingFinished();
         }
     }
 #endif
     return QWidget::event(e);
 }
focusInEvent()
void QLineEdit::focusInEvent (QFocusEvent * e) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1900 of file qlineedit.cpp.
focusOutEvent()
void QLineEdit::focusOutEvent (QFocusEvent * e) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1949 of file qlineedit.cpp.
getTextMargins()
void QLineEdit::getTextMargins (int * left, int * top, int * right, int * bottom) const
Returns the widget's text margins for left, top, right, and bottom.
Since
4.5
See also
setTextMargins()
Definition at line 1290 of file qlineedit.cpp.
Referenced by QAccessibleLineEdit::characterRect(), and QExpandingLineEdit::updateMinimumWidth().
 {
     Q_D(const QLineEdit);
     if (left)
         *left = d->leftTextMargin;
     if (top)
         *top = d->topTextMargin;
     if (right)
         *right = d->rightTextMargin;
     if (bottom)
         *bottom = d->bottomTextMargin;
 }
hasAcceptableInput()
bool QLineEdit::hasAcceptableInput () const
Definition at line 1246 of file qlineedit.cpp.
Referenced by cursorPositionAt(), focusOutEvent(), and QScriptNewBreakpointWidget::onTextChanged().
 {
     Q_D(const QLineEdit);
     return d->control->hasAcceptableInput();
 }
hasFrame()
bool QLineEdit::hasFrame () const
Definition at line 507 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     return d->frame;
 }
hasSelectedText()
bool QLineEdit::hasSelectedText () const
Referenced by cut(), event(), focusInEvent(), and setModified().
home()
void QLineEdit::home (bool mark)
Moves the text cursor to the beginning of the line unless it is already there.
If mark is true, text is selected towards the first position; otherwise, any selected text is unselected if the cursor is moved.
See also
end()
Definition at line 925 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->home(mark);
 }
initStyleOption()
void QLineEdit::initStyleOption (QStyleOptionFrame * option) const protected
Initialize option with the values from this QLineEdit.
This method is useful for subclasses when they need a QStyleOptionFrame or QStyleOptionFrameV2, but don't want to fill in all the information themselves. This function will check the version of the QStyleOptionFrame and fill in the additional values for a QStyleOptionFrameV2.
See also
QStyleOption::initFrom()
Definition at line 104 of file qlineedit.cpp.
Referenced by changeEvent(), event(), focusInEvent(), minimumSizeHint(), paintEvent(), setSelection(), sizeHint(), and QExpandingLineEdit::updateMinimumWidth().
 {
     if (!option)
         return;
     Q_D(const QLineEdit);
     option->initFrom(this);
     option->rect = contentsRect();
     option->lineWidth = d->frame ? style()->pixelMetric(QStyle::PM_DefaultFrameWidth, option, this)
                                  : 0;
     option->midLineWidth = 0;
     option->state |= QStyle::State_Sunken;
     if (d->control->isReadOnly())
         option->state |= QStyle::State_ReadOnly;
 #ifdef QT_KEYPAD_NAVIGATION
     if (hasEditFocus())
         option->state |= QStyle::State_HasEditFocus;
 #endif
     if (QStyleOptionFrameV2 *optionV2 = qstyleoption_cast<QStyleOptionFrameV2 *>(option))
         optionV2->features = QStyleOptionFrameV2::None;
 }
inputMask()
QString QLineEdit::inputMask () const
Referenced by QLineEdit(), and textMargins().
inputMethodEvent()
void QLineEdit::inputMethodEvent (QInputMethodEvent * e) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1833 of file qlineedit.cpp.
inputMethodQuery()
QVariant QLineEdit::inputMethodQuery (Qt::InputMethodQuery property) const virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1869 of file qlineedit.cpp.
insert()
void QLineEdit::insert (const QString & newText)
Deletes any selected text, inserts newText, and validates the result.
If it is valid, it sets it as the new contents of the line edit.
See also
setText(), clear()
Definition at line 1431 of file qlineedit.cpp.
Referenced by dropEvent(), and mouseReleaseEvent().
 {
 //     q->resetInputContext(); //#### FIX ME IN QT
     Q_D(QLineEdit);
     d->control->insert(newText);
 }
isModified()
bool QLineEdit::isModified () const
Definition at line 968 of file qlineedit.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), QPrintDialogPrivate::_q_printerOrFileSelected(), and selectionStart().
 {
     Q_D(const QLineEdit);
     return d->control->isModified();
 }
isReadOnly()
bool QLineEdit::isReadOnly () const
Definition at line 1493 of file qlineedit.cpp.
Referenced by createStandardContextMenu(), keyPressEvent(), mouseReleaseEvent(), and QAccessibleLineEdit::state().
 {
     Q_D(const QLineEdit);
     return d->control->isReadOnly();
 }
isRedoAvailable()
bool QLineEdit::isRedoAvailable () const
Definition at line 1156 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     return d->control->isRedoAvailable();
 }
isUndoAvailable()
bool QLineEdit::isUndoAvailable () const
Definition at line 1137 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     return d->control->isUndoAvailable();
 }
keyPressEvent()
void QLineEdit::keyPressEvent (QKeyEvent * event) protected virtual
Converts the given key press event into a line edit action.
If Return or Enter is pressed and the current text is valid (or can be made valid by the validator), the signal returnPressed() is emitted.
The default key bindings are listed in the class's detailed description.
Reimplemented from QWidget.
Definition at line 1764 of file qlineedit.cpp.
Referenced by QFileDialogLineEdit::keyPressEvent().
 {
     Q_D(QLineEdit);
     #ifdef QT_KEYPAD_NAVIGATION
     bool select = false;
     switch (event->key()) {
         case Qt::Key_Select:
             if (QApplication::keypadNavigationEnabled()) {
                 if (hasEditFocus()) {
                     setEditFocus(false);
                     if (d->control->completer() && d->control->completer()->popup()->isVisible())
                         d->control->completer()->popup()->hide();
                     select = true;
                 }
             }
             break;
         case Qt::Key_Back:
         case Qt::Key_No:
             if (!QApplication::keypadNavigationEnabled() || !hasEditFocus()) {
                 event->ignore();
                 return;
             }
             break;
         default:
             if (QApplication::keypadNavigationEnabled()) {
                 if (!hasEditFocus() && !(event->modifiers() & Qt::ControlModifier)) {
                     if (!event->text().isEmpty() && event->text().at(0).isPrint()
                         && !isReadOnly())
                         setEditFocus(true);
                     else {
                         event->ignore();
                         return;
                     }
                 }
             }
     }
     if (QApplication::keypadNavigationEnabled() && !select && !hasEditFocus()) {
         setEditFocus(true);
         if (event->key() == Qt::Key_Select)
             return; // Just start. No action.
     }
 #endif
     d->control->processKeyEvent(event);
     if (event->isAccepted()) {
         if (layoutDirection() != d->control->layoutDirection())
             setLayoutDirection(d->control->layoutDirection());
         d->control->setCursorBlinkPeriod(0);
     }
 }
maxLength()
int QLineEdit::maxLength () const
Referenced by inputMethodQuery(), and setPlaceholderText().
minimumSizeHint()
QSize QLineEdit::minimumSizeHint () const virtual
Returns a minimum size for the line edit.
The width returned is enough for at least one character.
Reimplemented from QWidget.
Definition at line 725 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     ensurePolished();
     QFontMetrics fm = fontMetrics();
     int h = fm.height() + qMax(2*d->verticalMargin, fm.leading())
             + d->topmargin + d->bottommargin;
     int w = fm.maxWidth() + d->leftmargin + d->rightmargin;
     QStyleOptionFrameV2 opt;
     initStyleOption(&opt);
     return (style()->sizeFromContents(QStyle::CT_LineEdit, &opt, QSize(w, h).
                                       expandedTo(QApplication::globalStrut()), this));
 }
mouseDoubleClickEvent()
void QLineEdit::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1715 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (d->sendMouseEventToInputContext(e))
         return;
     if (e->button() == Qt::LeftButton) {
         d->control->selectWordAtPos(d->xToPos(e->pos().x()));
         d->tripleClickTimer.start(QApplication::doubleClickInterval(), this);
         d->tripleClick = e->pos();
     }
 }
mouseMoveEvent()
void QLineEdit::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1662 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (d->sendMouseEventToInputContext(e))
         return;
     if (e->buttons() & Qt::LeftButton) {
 #ifndef QT_NO_DRAGANDDROP
         if (d->dndTimer.isActive()) {
             if ((d->dndPos - e->pos()).manhattanLength() > QApplication::startDragDistance())
                 d->drag();
         } else
 #endif
         {
             d->control->moveCursor(d->xToPos(e->pos().x()), true);
         }
     }
 }
mousePressEvent()
void QLineEdit::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1625 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (d->sendMouseEventToInputContext(e))
         return;
     if (e->button() == Qt::RightButton)
         return;
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
         setEditFocus(true);
         // Get the completion list to pop up.
         if (d->control->completer())
             d->control->completer()->complete();
     }
 #endif
     if (d->tripleClickTimer.isActive() && (e->pos() - d->tripleClick).manhattanLength() <
          QApplication::startDragDistance()) {
         selectAll();
         return;
     }
     bool mark = e->modifiers() & Qt::ShiftModifier;
     int cursor = d->xToPos(e->pos().x());
 #ifndef QT_NO_DRAGANDDROP
     if (!mark && d->dragEnabled && d->control->echoMode() == Normal &&
          e->button() == Qt::LeftButton && d->control->inSelection(e->pos().x())) {
         d->dndPos = e->pos();
         if (!d->dndTimer.isActive())
             d->dndTimer.start(QApplication::startDragTime(), this);
     } else
 #endif
     {
         d->control->moveCursor(cursor, mark);
     }
 }
mouseReleaseEvent()
void QLineEdit::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1683 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (d->sendMouseEventToInputContext(e))
         return;
 #ifndef QT_NO_DRAGANDDROP
     if (e->button() == Qt::LeftButton) {
         if (d->dndTimer.isActive()) {
             d->dndTimer.stop();
             deselect();
             return;
         }
     }
 #endif
 #ifndef QT_NO_CLIPBOARD
     if (QApplication::clipboard()->supportsSelection()) {
         if (e->button() == Qt::LeftButton) {
             d->control->copy(QClipboard::Selection);
         } else if (!d->control->isReadOnly() && e->button() == Qt::MidButton) {
             deselect();
             insert(QApplication::clipboard()->text(QClipboard::Selection));
         }
     }
 #endif
     if (!isReadOnly() && rect().contains(e->pos()))
         d->handleSoftwareInputPanel(e->button(), d->clickCausedFocus);
     d->clickCausedFocus = 0;
 }
paintEvent()
void QLineEdit::paintEvent (QPaintEvent *) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1994 of file qlineedit.cpp.
paste
void QLineEdit::paste () slot
Inserts the clipboard's text at the cursor position, deleting any selected text, providing the line edit is not read-only.
If the end result would not be acceptable to the current validator, nothing happens.
See also
copy() cut()
Definition at line 1558 of file qlineedit.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QLineEdit);
     d->control->paste();
 }
placeholderText()
QString QLineEdit::placeholderText () const
Referenced by setPlaceholderText(), and setText().
redo
void QLineEdit::redo () slot
Redoes the last operation if redo is available.
Definition at line 1467 of file qlineedit.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QLineEdit);
     resetInputContext();
     d->control->redo();
 }
returnPressed
void QLineEdit::returnPressed () signal
This signal is emitted when the Return or Enter key is pressed.
Note that if there is a validator() or inputMask() set on the line edit, the returnPressed() signal will only be emitted if the input follows the inputMask() and the validator() returns QValidator::Acceptable.
selectAll
void QLineEdit::selectAll () slot
Selects all the text (i.e.
highlights it) and moves the cursor to the end. This is useful when a default value has been inserted because if the user types before clicking on the widget, the selected text will be deleted.
See also
setSelection() deselect()
Definition at line 1405 of file qlineedit.cpp.
Referenced by QComboBoxPrivate::_q_itemSelected(), QPrintDialogPrivate::_q_printerOrFileSelected(), createStandardContextMenu(), focusInEvent(), mousePressEvent(), and QDateTimeEditPrivate::setSelected().
 {
     Q_D(QLineEdit);
     d->control->selectAll();
 }
selectedText()
QString QLineEdit::selectedText () const
Referenced by inputMethodQuery(), selectionStart(), and setModified().
selectionChanged
void QLineEdit::selectionChanged () signal
This signal is emitted whenever the selection changes.
See also
hasSelectedText(), selectedText()
selectionStart()
int QLineEdit::selectionStart () const
selectionStart() returns the index of the first selected character in the line edit or -1 if no text is selected.
See also
selectedText()
Definition at line 1039 of file qlineedit.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QAbstractSpinBoxPrivate::_q_editorCursorPositionChanged(), and QAccessibleLineEdit::selection().
 {
     Q_D(const QLineEdit);
     return d->control->selectionStart();
 }
setAlignment()
void QLineEdit::setAlignment (Qt::Alignment flag)
Definition at line 827 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->alignment = alignment;
     update();
 }
setCompleter()
void QLineEdit::setCompleter (QCompleter * c)
Sets this line edit to provide auto completions from the completer, c.
Since
4.2
The completion mode is set using QCompleter::setCompletionMode().
To use a QCompleter with a QValidator or QLineEdit::inputMask, you need to ensure that the model provided to QCompleter contains valid entries. You can use the QSortFilterProxyModel to ensure that the QCompleter's model contains only valid entries.
If c == 0, setCompleter() removes the current completer, effectively disabling auto completion.
See also
QCompleter
Definition at line 654 of file qlineedit.cpp.
Referenced by QScriptNewBreakpointWidget::setCompleter().
 {
     Q_D(QLineEdit);
     if (c == d->control->completer())
         return;
     if (d->control->completer()) {
         disconnect(d->control->completer(), 0, this, 0);
         d->control->completer()->setWidget(0);
         if (d->control->completer()->parent() == this)
             delete d->control->completer();
     }
     d->control->setCompleter(c);
     if (!c)
         return;
     if (c->widget() == 0)
         c->setWidget(this);
     if (hasFocus()) {
         QObject::connect(d->control->completer(), SIGNAL(activated(QString)),
                          this, SLOT(setText(QString)));
         QObject::connect(d->control->completer(), SIGNAL(highlighted(QString)),
                          this, SLOT(_q_completionHighlighted(QString)));
     }
 }
setCursorMoveStyle()
void QLineEdit::setCursorMoveStyle (Qt::CursorMoveStyle style)
Sets the movement style for the cursor in the line edit to the given style.
Since
4.8
Definition at line 1228 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->setCursorMoveStyle(style);
 }
setCursorPosition()
void QLineEdit::setCursorPosition (int pos)
Definition at line 758 of file qlineedit.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QAbstractSpinBoxPrivate::_q_editorCursorPositionChanged(), QPrintDialogPrivate::_q_printerOrFileSelected(), QDateTimeEditPrivate::clearSection(), QAbstractSpinBoxPrivate::interpret(), QAccessibleLineEdit::scrollToSubstring(), QAccessibleLineEdit::setCursorPosition(), QDateTimeEditPrivate::updateEdit(), and QAbstractSpinBoxPrivate::updateEdit().
 {
     Q_D(QLineEdit);
     d->control->setCursorPosition(pos);
 }
setDragEnabled()
void QLineEdit::setDragEnabled (bool b)
Definition at line 1179 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->dragEnabled = b;
 }
setEchoMode()
void QLineEdit::setEchoMode (EchoMode mode)
Definition at line 575 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (mode == (EchoMode)d->control->echoMode())
         return;
     Qt::InputMethodHints imHints = inputMethodHints();
     if (mode == Password || mode == NoEcho) {
         imHints |= Qt::ImhHiddenText;
     } else {
         imHints &= ~Qt::ImhHiddenText;
     }
     if (mode != Normal) {
         imHints |= (Qt::ImhNoAutoUppercase | Qt::ImhNoPredictiveText);
     } else {
         imHints &= ~(Qt::ImhNoAutoUppercase | Qt::ImhNoPredictiveText);
     }
     setInputMethodHints(imHints);
     d->control->setEchoMode(mode);
     update();
 #ifdef Q_WS_MAC
     if (hasFocus())
         qt_mac_secure_keyboard(mode == Password || mode == NoEcho);
 #endif
 }
setFrame()
void QLineEdit::setFrame (bool enable)
Definition at line 514 of file qlineedit.cpp.
Referenced by QDefaultItemEditorFactory::createEditor().
 {
     Q_D(QLineEdit);
     d->frame = enable;
     update();
     updateGeometry();
 }
setInputMask()
void QLineEdit::setInputMask (const QString & inputMask)
Definition at line 1390 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->setInputMask(inputMask);
 }
setMaxLength()
void QLineEdit::setMaxLength (int maxLength)
Definition at line 491 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     d->control->setMaxLength(maxLength);
 }
setModified()
void QLineEdit::setModified (bool modified)
Definition at line 974 of file qlineedit.cpp.
Referenced by QPrintDialogPrivate::_q_printerOrFileSelected(), selectionStart(), and QPrintDialogPrivate::setPrinter().
 {
     Q_D(QLineEdit);
     d->control->setModified(modified);
 }
setPlaceholderText()
void QLineEdit::setPlaceholderText (const QString & placeholderText)
Definition at line 430 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (d->placeholderText != placeholderText) {
         d->placeholderText = placeholderText;
         if (!hasFocus())
             update();
     }
 }
setReadOnly()
void QLineEdit::setReadOnly (bool enable)
Definition at line 1499 of file qlineedit.cpp.
 {
     Q_D(QLineEdit);
     if (d->control->isReadOnly() != enable) {
         d->control->setReadOnly(enable);
         setAttribute(Qt::WA_MacShowFocusRect, !enable);
         setAttribute(Qt::WA_InputMethodEnabled, d->shouldEnableInputMethod());
 #ifndef QT_NO_CURSOR
         setCursor(enable ? Qt::ArrowCursor : Qt::IBeamCursor);
 #endif
         update();
     }
 }
setSelection()
void QLineEdit::setSelection (int start, int length)
Selects text from position start and for length characters.
Negative lengths are allowed.
See also
deselect() selectAll() selectedText()
Definition at line 1106 of file qlineedit.cpp.
Referenced by QAbstractSpinBoxPrivate::_q_editorCursorPositionChanged(), cursorPositionAt(), dropEvent(), QDateTimeEditPrivate::setSelected(), QAccessibleLineEdit::setSelection(), QDateTimeEditPrivate::updateEdit(), and QAbstractSpinBoxPrivate::updateEdit().
 {
     Q_D(QLineEdit);
     if (start < 0 || start > (int)d->control->text().length()) {
         qWarning("QLineEdit::setSelection: Invalid start position (%d)", start);
         return;
     }
     d->control->setSelection(start, length);
     if (d->control->hasSelectedText()){
         QStyleOptionFrameV2 opt;
         initStyleOption(&opt);
         if (!style()->styleHint(QStyle::SH_BlinkCursorWhenTextSelected, &opt, this))
             d->setCursorVisible(false);
     }
 }
setText
void QLineEdit::setText (const QString & text) slot
Definition at line 401 of file qlineedit.cpp.
Referenced by QComboBoxPrivate::_q_dataChanged(), QFileDialogPrivate::_q_enterDirectory(), QFileDialogPrivate::_q_fileRenamed(), QComboBoxPrivate::_q_itemSelected(), QComboBoxPrivate::_q_modelReset(), QPrintDialogPrivate::_q_printerOrFileSelected(), QComboBoxPrivate::_q_rowsRemoved(), QFileDialogPrivate::_q_selectionChanged(), QFileDialogPrivate::_q_useNameFilter(), QDateTimeEditPrivate::clearSection(), cursorPositionAt(), focusInEvent(), setCompleter(), QComboBoxPrivate::setCurrentIndex(), QInputDialogPrivate::setInputWidget(), QComboBox::setLineEdit(), QPrintDialogPrivate::setPrinter(), QAccessibleLineEdit::setText(), QDateTimeEditPrivate::updateEdit(), and QAbstractSpinBoxPrivate::updateEdit().
 {
     Q_D(QLineEdit);
     d->control->setText(text);
 }
setTextMargins() [1/2]
void QLineEdit::setTextMargins (int left, int top, int right, int bottom)
Sets the margins around the text inside the frame to have the sizes left, top, right, and bottom.
Since
4.5
See also getTextMargins().
Definition at line 1259 of file qlineedit.cpp.
Referenced by setTextMargins().
 {
     Q_D(QLineEdit);
     d->leftTextMargin = left;
     d->topTextMargin = top;
     d->rightTextMargin = right;
     d->bottomTextMargin = bottom;
     updateGeometry();
     update();
 }
setTextMargins() [2/2]
void QLineEdit::setTextMargins (const QMargins & margins)
Sets the margins around the text inside the frame.
Since
4.6
See also textMargins().
Definition at line 1279 of file qlineedit.cpp.
 {
     setTextMargins(margins.left(), margins.top(), margins.right(), margins.bottom());
 }
setValidator()
void QLineEdit::setValidator (const QValidator * v)
Sets this line edit to only accept input that the validator, v, will accept.
This allows you to place any arbitrary constraints on the text which may be entered.
If v == 0, setValidator() removes the current input validator. The initial setting is to have no input validator (i.e. any input is accepted up to maxLength()).
See also
validator() QIntValidator QDoubleValidator QRegExpValidator
Definition at line 627 of file qlineedit.cpp.
Referenced by QAbstractSpinBoxPrivate::init(), and QScriptNewBreakpointWidget::QScriptNewBreakpointWidget().
 {
     Q_D(QLineEdit);
     d->control->setValidator(v);
 }
sizeHint()
QSize QLineEdit::sizeHint () const virtual
Returns a recommended size for the widget.
The width returned, in pixels, is usually enough for about 15 to 20 characters.
Reimplemented from QWidget.
Definition at line 701 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     ensurePolished();
     QFontMetrics fm(font());
     int h = qMax(fm.height(), 14) + 2*d->verticalMargin
             + d->topTextMargin + d->bottomTextMargin
             + d->topmargin + d->bottommargin;
     int w = fm.width(QLatin1Char('x')) * 17 + 2*d->horizontalMargin
             + d->leftTextMargin + d->rightTextMargin
             + d->leftmargin + d->rightmargin; // "some"
     QStyleOptionFrameV2 opt;
     initStyleOption(&opt);
     return (style()->sizeFromContents(QStyle::CT_LineEdit, &opt, QSize(w, h).
                                       expandedTo(QApplication::globalStrut()), this));
 }
text()
QString QLineEdit::text () const
Referenced by cursorPositionAt(), inputMethodQuery(), mouseReleaseEvent(), and ~QLineEdit().
textChanged
void QLineEdit::textChanged (const QString & text) signal
This signal is emitted whenever the text changes.
The text argument is the new text.
Unlike textEdited(), this signal is also emitted when the text is changed programmatically, for example, by calling setText().
Referenced by QExpandingLineEdit::QExpandingLineEdit().
textEdited
void QLineEdit::textEdited (const QString & text) signal
This signal is emitted whenever the text is edited.
The text argument is the new text.
Unlike textChanged(), this signal is not emitted when the text is changed programmatically, for example, by calling setText().
textMargins()
QMargins QLineEdit::textMargins () const
Returns the widget's text margins.
Since
4.6
See also
setTextMargins()
Definition at line 1312 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     return QMargins(d->leftTextMargin, d->topTextMargin, d->rightTextMargin, d->bottomTextMargin);
 }
undo
void QLineEdit::undo () slot
Undoes the last operation if undo is available.
Deselects any current selection, and updates the selection start to the current cursor position.
Definition at line 1456 of file qlineedit.cpp.
Referenced by createStandardContextMenu().
 {
     Q_D(QLineEdit);
     resetInputContext();
     d->control->undo();
 }
validator()
const QValidator * QLineEdit::validator () const
Returns a pointer to the current input validator, or 0 if no validator has been set.
See also
setValidator()
Definition at line 609 of file qlineedit.cpp.
 {
     Q_D(const QLineEdit);
     return d->control->validator();
 }
Friends and Related Functions
QAbstractSpinBox
friend class QAbstractSpinBox friend
Definition at line 275 of file qlineedit.h.
QAccessibleLineEdit
friend class QAccessibleLineEdit friend
Definition at line 276 of file qlineedit.h.
Properties
acceptableInput
QLineEdit::acceptableInput private
whether the input satisfies the inputMask and the validator.
By default, this property is true.
See also
setInputMask(), setValidator()
Definition at line 86 of file qlineedit.h.
alignment
Qt::Alignment QLineEdit::alignment private
the alignment of the line edit
Both horizontal and vertical alignment is allowed here, Qt::AlignJustify will map to Qt::AlignLeft.
By default, this property contains a combination of Qt::AlignLeft and Qt::AlignVCenter.
See also
Qt::Alignment
Definition at line 78 of file qlineedit.h.
cursorMoveStyle
Qt::CursorMoveStyle QLineEdit::cursorMoveStyle private
the movement style of cursor in this line edit
Returns the movement style for the cursor in the line edit.
Since
4.8
When this property is set to Qt::VisualMoveStyle, the line edit will use visual movement style. Pressing the left arrow key will always cause the cursor to move left, regardless of the text's writing direction. The same behavior applies to right arrow key.
When the property is Qt::LogicalMoveStyle (the default), within a LTR text block, increase cursor position when pressing left arrow key, decrease cursor position when pressing the right arrow key. If the text block is right to left, the opposite behavior applies.
Since
4.8
Definition at line 88 of file qlineedit.h.
cursorPosition
int QLineEdit::cursorPosition private
the current cursor position for this line edit
Setting the cursor position causes a repaint when appropriate.
By default, this property contains a value of 0.
Definition at line 77 of file qlineedit.h.
Referenced by QAbstractSpinBoxPrivate::_q_editorTextChanged(), QDateTimeEditPrivate::clearSection(), QScriptDebuggerLocalsWidgetPrivate::complete(), QDateTimeEditPrivate::cursorPosition(), QAccessibleLineEdit::cursorPosition(), QDateTimeEditPrivate::interpret(), QAbstractSpinBoxPrivate::interpret(), QDateTimeEditPrivate::stepBy(), QDateTimeEditPrivate::updateCache(), and QAbstractSpinBoxPrivate::updateEdit().
displayText
QString QLineEdit::displayText private
the displayed text
If echoMode is Normal this returns the same as text(); if EchoMode is Password or PasswordEchoOnEdit it returns a string of asterisks text().length() characters long, e.g. "******"; if EchoMode is NoEcho returns an empty string, "".
By default, this property contains an empty string.
See also
setEchoMode() text() EchoMode
Definition at line 76 of file qlineedit.h.
Referenced by QAbstractSpinBoxPrivate::interpret(), QAbstractSpinBox::setButtonSymbols(), and QAbstractSpinBoxPrivate::updateEdit().
dragEnabled
bool QLineEdit::dragEnabled private
whether the lineedit starts a drag if the user presses and moves the mouse on some selected text
Dragging is disabled by default.
Definition at line 82 of file qlineedit.h.
echoMode
QLineEdit::EchoMode QLineEdit::echoMode private
the line edit's echo mode
The echo mode determines how the text entered in the line edit is displayed (or echoed) to the user.
The most common setting is Normal , in which the text entered by the user is displayed verbatim, but QLineEdit also supports modes that allow the entered text to be suppressed or obscured: these include NoEcho , Password and PasswordEchoOnEdit .
The widget's display and the ability to copy or drag the text is affected by this setting.
By default, this property is set to Normal .
See also
EchoMode displayText()
Definition at line 75 of file qlineedit.h.
Referenced by QAccessibleLineEdit::state().
frame
bool QLineEdit::frame private
whether the line edit draws itself with a frame
Use hasFrame() instead.
If enabled (the default) the line edit draws itself inside a frame, otherwise the line edit draws itself without any frame.
Definition at line 74 of file qlineedit.h.
hasSelectedText
bool QLineEdit::hasSelectedText private
whether there is any text selected
hasSelectedText() returns true if some or all of the text has been selected by the user; otherwise returns false.
By default, this property is false.
See also
selectedText()
Definition at line 80 of file qlineedit.h.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QAbstractSpinBoxPrivate::_q_editorCursorPositionChanged(), QAccessibleLineEdit::selectionCount(), and QAccessibleLineEdit::state().
inputMask
QString QLineEdit::inputMask private
The validation input mask.
If no mask is set, inputMask() returns an empty string.
Sets the QLineEdit's validation mask. Validators can be used instead of, or in conjunction with masks; see setValidator().
Unset the mask and return to normal QLineEdit operation by passing an empty string ("") or just calling setInputMask() with no arguments.
The table below shows the characters that can be used in an input mask. A space character, the default character for a blank, is needed for cases where a character is permitted but not required.
Character Meaning
A ASCII alphabetic character required. A-Z, a-z.
a ASCII alphabetic character permitted but not required.
N ASCII alphanumeric character required. A-Z, a-z, 0-9.
n ASCII alphanumeric character permitted but not required.
X Any character required.
x Any character permitted but not required.
9 ASCII digit required. 0-9.
0 ASCII digit permitted but not required.
D ASCII digit required. 1-9.
d ASCII digit permitted but not required (1-9).
# ASCII digit or plus/minus sign permitted but not required.
H Hexadecimal character required. A-F, a-f, 0-9.
h Hexadecimal character permitted but not required.
B Binary character required. 0-1.
b Binary character permitted but not required.
> All following alphabetic characters are uppercased.
< All following alphabetic characters are lowercased.
! Switch off case conversion.
\ Use \ to escape the special characters listed above to use them as separators.
The mask consists of a string of mask characters and separators, optionally followed by a semicolon and the character used for blanks. The blank characters are always removed from the text after editing.
Examples:
Mask Notes
000.000.000.000;_ IP address; blanks are _.
HH:HH:HH:HH:HH:HH;_ MAC address
0000-00-00 ISO Date; blanks are space
>AAAAA-AAAAA-AAAAA-AAAAA-AAAAA;# License number; blanks are - and all (alphabetic) characters are converted to uppercase.
To get range control (e.g., for an IP address) use masks together with validators.
See also
maxLength
Definition at line 71 of file qlineedit.h.
maxLength
int QLineEdit::maxLength private
the maximum permitted length of the text
If the text is too long, it is truncated at the limit.
If truncation occurs any selected text will be unselected, the cursor position is set to 0 and the first part of the string is shown.
If the line edit has an input mask, the mask defines the maximum string length.
By default, this property contains a value of 32767.
See also
inputMask
Definition at line 73 of file qlineedit.h.
modified
QLineEdit::modified private
whether the line edit's contents has been modified by the user
The modified flag is never read by QLineEdit; it has a default value of false and is changed to true whenever the user changes the line edit's contents.
This is useful for things that need to provide a default value but do not start out knowing what the default should be (perhaps it depends on other fields on the form). Start the line edit without the best default, and when the default is known, if modified() returns false (the user hasn't entered any text), insert the default value.
Calling setText() resets the modified flag to false.
Definition at line 79 of file qlineedit.h.
placeholderText
QString QLineEdit::placeholderText private
the line edit's placeholder text
Since
4.7
Setting this property makes the line edit display a grayed-out placeholder text as long as the text() is empty and the widget doesn't have focus.
By default, this property contains an empty string.
See also
text()
Definition at line 87 of file qlineedit.h.
readOnly
QLineEdit::readOnly private
whether the line edit is read only.
In read-only mode, the user can still copy the text to the clipboard, or drag and drop the text (if echoMode() is Normal), but cannot edit it.
QLineEdit does not show a cursor in read-only mode.
By default, this property is false.
See also
setEnabled()
Definition at line 83 of file qlineedit.h.
redoAvailable
QLineEdit::redoAvailable private
whether redo is available
Redo becomes available once the user has performed one or more undo operations on text in the line edit.
By default, this property is false.
Definition at line 85 of file qlineedit.h.
selectedText
QString QLineEdit::selectedText private
the selected text
If there is no selected text this property's value is an empty string.
By default, this property contains an empty string.
See also
hasSelectedText()
Definition at line 81 of file qlineedit.h.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QAbstractSpinBoxPrivate::_q_editorCursorPositionChanged(), QAccessibleLineEdit::selection(), QDateTimeEditPrivate::updateEdit(), and QAbstractSpinBoxPrivate::updateEdit().
text
QString QLineEdit::text private
the line edit's text
Setting this property clears the selection, clears the undo/redo history, moves the cursor to the end of the line and resets the modified property to false. The text is not validated when inserted with setText().
The text is truncated to maxLength() length.
By default, this property contains an empty string.
See also
insert(), clear()
Definition at line 72 of file qlineedit.h.
Referenced by QComboBoxPrivate::_q_editingFinished(), QAbstractSpinBoxPrivate::_q_editorCursorPositionChanged(), QScriptDebuggerCodeFinderWidgetPrivate::_q_next(), QPrintDialogPrivate::_q_okClicked(), QScriptDebuggerCodeFinderWidgetPrivate::_q_previous(), QPrintDialogPrivate::_q_printerOrFileSelected(), QComboBoxPrivate::_q_returnPressed(), QScriptDebuggerCodeFinderWidgetPrivate::_q_updateButtons(), QFileDialogPrivate::_q_updateOkButton(), QFileDialogPrivate::_q_useNameFilter(), QAccessibleLineEdit::characterCount(), QDateTimeEditPrivate::clearSection(), QScriptDebuggerLocalsWidgetPrivate::complete(), QDateTimeEditPrivate::displayText(), QScriptDebuggerLocalsItemDelegate::eventFilter(), QScriptNewBreakpointWidget::onOkClicked(), QComboBoxPrivate::setCurrentIndex(), QPrintDialogPrivate::setPrinter(), QAccessibleLineEdit::text(), QAccessibleComboBox::text(), QFileDialogPrivate::typedFiles(), and QAbstractSpinBoxPrivate::updateEdit().
undoAvailable
QLineEdit::undoAvailable private
whether undo is available
Undo becomes available once the user has modified the text in the line edit.
By default, this property is false.
Definition at line 84 of file qlineedit.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qlineedit.h
/src/gui/widgets/qlineedit.cpp