Qt 4.8: QConnmanServiceInterface Class Reference
QConnmanServiceInterface Class Reference
#include <qconnmanservice_linux_p.h>
Signals
void propertyChanged (const QString &, const QDBusVariant &value)
void propertyChangedContext (const QString &, const QString &, const QDBusVariant &)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void connect ()
void disconnect ()
QString getAPN ()
QStringList getDomains ()
QString getDuplex ()
QString getError ()
QVariantMap getEthernet ()
QString getInterface ()
QVariantMap getIPv4 ()
QVariantMap getIPv4Configuration ()
QString getMacAddress ()
QString getMCC ()
QString getMethod ()
QString getMNC ()
QString getMode ()
quint16 getMtu ()
QString getName ()
QStringList getNameservers ()
QString getPassphrase ()
QVariantMap getProperties ()
QVariantMap getProxy ()
QString getSecurity ()
QStringList getServices ()
quint8 getSignalStrength ()
quint16 getSpeed ()
QString getState ()
QString getType ()
bool isAutoConnect ()
bool isFavorite ()
bool isImmutable ()
bool isOfflineMode ()
bool isPassphraseRequired ()
bool isRoaming ()
bool isSetupRequired ()
QConnmanServiceInterface (const QString &dbusPathName, QObject *parent=0)
void remove ()
~QConnmanServiceInterface ()
Public Functions inherited from QDBusAbstractInterface
QDBusPendingCall asyncCall (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusPendingCall asyncCallWithArgumentList (const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
QDBusMessage call (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage call (QDBus::CallMode mode, const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage callWithArgumentList (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member, const char *errorSlot)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member)
This function is deprecated.
QDBusConnection connection () const
Returns the connection this interface is assocated with.
QString interface () const
Returns the name of this interface.
bool isValid () const
Returns true if this is a valid reference to a remote object.
QDBusError lastError () const
Returns the error the last operation produced, or an invalid error if the last operation did not produce an error.
QString path () const
Returns the object path that this interface is associated with.
QString service () const
Returns the name of the service this interface is associated with.
void setTimeout (int timeout)
Sets the timeout in milliseconds for all future DBus calls to timeout.
int timeout () const
Returns the current value of the timeout in milliseconds.
virtual ~QDBusAbstractInterface ()
Releases this object's resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void connectNotify (const char *signal)
Catch signal connections.
void disconnectNotify (const char *signal)
Catch signal disconnections.
QVariant getProperty (const QString &)
Protected Functions inherited from QDBusAbstractInterface
QDBusMessage internalConstCall (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args=QList< QVariant >()) const
QVariant internalPropGet (const char *propname) const
Get the value of the property propname.
void internalPropSet (const char *propname, const QVariant &value)
Set the value of the property propname to value.
QDBusAbstractInterface (const QString &service, const QString &path, const char *interface, const QDBusConnection &connection, QObject *parent)
This is the constructor called from static classes derived from QDBusAbstractInterface (i.
QDBusAbstractInterface (QDBusAbstractInterfacePrivate &, QObject *parent)
This is the constructor called from QDBusInterface::QDBusInterface.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 193 of file qconnmanservice_linux_p.h.
Constructors and Destructors
QConnmanServiceInterface()
QConnmanServiceInterface::QConnmanServiceInterface (const QString & dbusPathName, QObject * parent = 0)
Definition at line 435 of file qconnmanservice_linux.cpp.
     : QDBusAbstractInterface(QLatin1String(CONNMAN_SERVICE),
                              dbusPathName,
                              CONNMAN_SERVICE_INTERFACE,
                              QDBusConnection::systemBus(), parent)
 {
 }
~QConnmanServiceInterface()
QConnmanServiceInterface::~QConnmanServiceInterface ()
Definition at line 443 of file qconnmanservice_linux.cpp.
 {
 }
Functions
connect()
void QConnmanServiceInterface::connect ()
Definition at line 498 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::connectToId().
 {
     this->asyncCall(QLatin1String("Connect"));
 }
connectNotify()
void QConnmanServiceInterface::connectNotify (const char * signal) protected virtual
Catch signal connections.
Warning
This function is not part of the public interface.
Reimplemented from QDBusAbstractInterface.
Definition at line 447 of file qconnmanservice_linux.cpp.
 {
     if (QLatin1String(signal) == SIGNAL(propertyChanged(QString,QDBusVariant))) {
         dbusConnection.connect(QLatin1String(CONNMAN_SERVICE),
                                this->path(),
                                QLatin1String(CONNMAN_SERVICE_INTERFACE),
                                QLatin1String("PropertyChanged"),
                                this,SIGNAL(propertyChanged(QString,QDBusVariant)));
     }
     if (QLatin1String(signal) == SIGNAL(propertyChangedContext(QString,QString,QDBusVariant))) {
         QConnmanDBusHelper *helper;
         helper = new QConnmanDBusHelper(this);
         dbusConnection.connect(QLatin1String(CONNMAN_SERVICE),
                                this->path(),
                                QLatin1String(CONNMAN_SERVICE_INTERFACE),
                                QLatin1String("PropertyChanged"),
                                helper,SLOT(propertyChanged(QString,QDBusVariant)));
         QObject::connect(helper,SIGNAL(propertyChangedContext(const QString &,const QString &,const QDBusVariant &)),
                 this,SIGNAL(propertyChangedContext(const QString &,const QString &,const QDBusVariant &)), Qt::UniqueConnection);
     }
 }
disconnect()
void QConnmanServiceInterface::disconnect ()
Definition at line 503 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::disconnectFromId().
 {
     QDBusReply<QVariantMap> reply = this->call(QLatin1String("Disconnect"));
 }
disconnectNotify()
void QConnmanServiceInterface::disconnectNotify (const char * signal) protected virtual
Catch signal disconnections.
Warning
This function is not part of the public interface.
Reimplemented from QDBusAbstractInterface.
Definition at line 471 of file qconnmanservice_linux.cpp.
 {
     if (QLatin1String(signal) == SIGNAL(propertyChanged(QString,QVariant))) {
     }
 }
getAPN()
QString QConnmanServiceInterface::getAPN ()
Definition at line 595 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::addServiceConfiguration().
 {
     QVariant var = getProperty("APN");
     return qdbus_cast<QString>(var);
 }
getDomains()
QStringList QConnmanServiceInterface::getDomains ()
Definition at line 625 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Domains");
     return qdbus_cast<QStringList>(var);
 }
getDuplex()
QString QConnmanServiceInterface::getDuplex ()
Definition at line 732 of file qconnmanservice_linux.cpp.
 {
     QVariant var;
     QVariantMap map = getEthernet();
     QMapIterator<QString,QVariant> it(map);
     while(it.hasNext()) {
         it.next();
         if(it.key() == "Duplex") {
             return it.value().toString();
         }
     }
     return QString();
 }
getError()
QString QConnmanServiceInterface::getError ()
Definition at line 523 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Error");
     return qdbus_cast<QString>(var);
 }
getEthernet()
QVariantMap QConnmanServiceInterface::getEthernet ()
Definition at line 649 of file qconnmanservice_linux.cpp.
Referenced by getDuplex(), getInterface(), getMacAddress(), getMethod(), getMtu(), and getSpeed().
 {
     QVariant var = getProperty("Ethernet");
     return qdbus_cast<QVariantMap >(var);
 }
getInterface()
QString QConnmanServiceInterface::getInterface ()
Definition at line 669 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::addServiceConfiguration().
 {
     QVariant var;
     QVariantMap map = getEthernet();
     QMapIterator<QString,QVariant> it(map);
     while(it.hasNext()) {
         it.next();
         if(it.key() == "Interface") {
             return it.value().toString();
         }
     }
     return QString();
 }
getIPv4()
QVariantMap QConnmanServiceInterface::getIPv4 ()
Definition at line 631 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("IPv4");
     return qdbus_cast<QVariantMap >(var);
 }
getIPv4Configuration()
QVariantMap QConnmanServiceInterface::getIPv4Configuration ()
Definition at line 637 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("IPv4.Configuration");
     return qdbus_cast<QVariantMap >(var);
 }
getMacAddress()
QString QConnmanServiceInterface::getMacAddress ()
Definition at line 685 of file qconnmanservice_linux.cpp.
 {
     QVariant var;
     QVariantMap map = getEthernet();
     QMapIterator<QString,QVariant> it(map);
     while(it.hasNext()) {
         it.next();
         if(it.key() == "Address") {
             return it.value().toString();
         }
     }
     return QString();
 }
getMCC()
QString QConnmanServiceInterface::getMCC ()
Definition at line 601 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("MCC");
     return qdbus_cast<QString>(var);
 }
getMethod()
QString QConnmanServiceInterface::getMethod ()
Definition at line 655 of file qconnmanservice_linux.cpp.
 {
     QVariant var;
     QVariantMap map = getEthernet();
     QMapIterator<QString,QVariant> it(map);
     while(it.hasNext()) {
         it.next();
         if(it.key() == "Method") {
             return it.value().toString();
         }
     }
  return QString();
 }
getMNC()
QString QConnmanServiceInterface::getMNC ()
Definition at line 607 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("MNC");
     return qdbus_cast<QString>(var);
 }
getMode()
QString QConnmanServiceInterface::getMode ()
Definition at line 541 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Mode");
     return qdbus_cast<QString>(var);
 }
getMtu()
quint16 QConnmanServiceInterface::getMtu ()
Definition at line 700 of file qconnmanservice_linux.cpp.
 {
     quint16 mtu=0;
     QVariant var;
     QVariantMap map = getEthernet();
     QMapIterator<QString,QVariant> it(map);
     while(it.hasNext()) {
         it.next();
         if(it.key() == "MTU") {
             return it.value().toUInt();
         }
     }
     return mtu;
 }
getName()
QString QConnmanServiceInterface::getName ()
Definition at line 529 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::addServiceConfiguration(), and QConnmanEngine::configurationChange().
 {
     QVariant var = getProperty("Name");
     return qdbus_cast<QString>(var);
 }
getNameservers()
QStringList QConnmanServiceInterface::getNameservers ()
Definition at line 619 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("NameServers");
     return qdbus_cast<QStringList>(var);
 }
getPassphrase()
QString QConnmanServiceInterface::getPassphrase ()
Definition at line 553 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Passphrase");
     return qdbus_cast<QString>(var);
 }
getProperties()
QVariantMap QConnmanServiceInterface::getProperties ()
Definition at line 478 of file qconnmanservice_linux.cpp.
Referenced by getProperty().
 {
     if(this->isValid()) {
         QDBusReply<QVariantMap> reply =  this->call(QLatin1String("GetProperties"));
         return reply.value();
     }
     else
         return QVariantMap();
 }
getProperty()
QVariant QConnmanServiceInterface::getProperty (const QString & property) protected
Definition at line 488 of file qconnmanservice_linux.cpp.
Referenced by getAPN(), getDomains(), getError(), getEthernet(), getIPv4(), getIPv4Configuration(), getMCC(), getMNC(), getMode(), getName(), getNameservers(), getPassphrase(), getProxy(), getSecurity(), getServices(), getSignalStrength(), getState(), getType(), isAutoConnect(), isFavorite(), isImmutable(), isOfflineMode(), isPassphraseRequired(), isRoaming(), and isSetupRequired().
 {
     QVariant var;
     QVariantMap map = getProperties();
     if (map.contains(property)) {
         var = map.value(property);
     }
     return var;
 }
getProxy()
QVariantMap QConnmanServiceInterface::getProxy ()
Definition at line 643 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Proxy");
     return qdbus_cast<QVariantMap >(var);
 }
getSecurity()
QString QConnmanServiceInterface::getSecurity ()
Definition at line 547 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::addServiceConfiguration().
 {
     QVariant var = getProperty("Security");
     return qdbus_cast<QString>(var);
 }
getServices()
QStringList QConnmanServiceInterface::getServices ()
Definition at line 754 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Services");
     return qdbus_cast<QStringList>(var);
 }
getSignalStrength()
quint8 QConnmanServiceInterface::getSignalStrength ()
Definition at line 565 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Strength");
     return qdbus_cast<quint8>(var);
 }
getSpeed()
quint16 QConnmanServiceInterface::getSpeed ()
Definition at line 716 of file qconnmanservice_linux.cpp.
 {
     quint16 speed=0;
     QVariant var;
     QVariantMap map = getEthernet();
     QMapIterator<QString,QVariant> it(map);
     while(it.hasNext()) {
         it.next();
         if(it.key() == "Speed") {
             return it.value().toUInt();
         }
     }
     return speed;
 }
getState()
QString QConnmanServiceInterface::getState ()
Definition at line 517 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::getStateForService(), and QConnmanEngine::sessionStateForId().
 {
     QVariant var = getProperty("State");
     return qdbus_cast<QString>(var);
 }
getType()
QString QConnmanServiceInterface::getType ()
Definition at line 535 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::addServiceConfiguration(), QConnmanEngine::connectToId(), QConnmanEngine::disconnectFromId(), and QConnmanEngine::getStateForService().
 {
     QVariant var = getProperty("Type");
     return qdbus_cast<QString>(var);
 }
isAutoConnect()
bool QConnmanServiceInterface::isAutoConnect ()
Definition at line 583 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("AutoConnect");
     return qdbus_cast<bool>(var);
 }
isFavorite()
bool QConnmanServiceInterface::isFavorite ()
Definition at line 571 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::getStateForService(), and QConnmanEngine::sessionStateForId().
 {
     QVariant var = getProperty("Favorite");
     return qdbus_cast<bool>(var);
 }
isImmutable()
bool QConnmanServiceInterface::isImmutable ()
Definition at line 577 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Immutable");
     return qdbus_cast<bool>(var);
 }
isOfflineMode()
bool QConnmanServiceInterface::isOfflineMode ()
Definition at line 748 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("OfflineMode");
     return qdbus_cast<bool>(var);
 }
isPassphraseRequired()
bool QConnmanServiceInterface::isPassphraseRequired ()
Definition at line 559 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("PassphraseRequired");
     return qdbus_cast<bool>(var);
 }
isRoaming()
bool QConnmanServiceInterface::isRoaming ()
Definition at line 613 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Roaming");
     return qdbus_cast<bool>(var);
 }
isSetupRequired()
bool QConnmanServiceInterface::isSetupRequired ()
Definition at line 589 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::getStateForService().
 {
     QVariant var = getProperty("SetupRequired");
     return qdbus_cast<bool>(var);
 }
propertyChanged
void QConnmanServiceInterface::propertyChanged (const QString & , const QDBusVariant & value) signal
Referenced by connectNotify(), and disconnectNotify().
propertyChangedContext
void QConnmanServiceInterface::propertyChangedContext (const QString & , const QString & , const QDBusVariant &) signal
Referenced by connectNotify().
remove()
void QConnmanServiceInterface::remove ()
Definition at line 508 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QVariantMap> reply = this->call(QLatin1String("Remove"));
 }
The documentation for this class was generated from the following files:
/src/plugins/bearer/connman/qconnmanservice_linux_p.h
/src/plugins/bearer/connman/qconnmanservice_linux.cpp