Qt 4.8: QTextFormatCollection Class Reference
QTextFormatCollection Class Reference
#include <qtextformat_p.h>
Public Types
typedef QVector< QTextFormat > FormatVector
Public Functions
QTextBlockFormat blockFormat (int index) const
QTextCharFormat charFormat (int index) const
int createObjectIndex (const QTextFormat &f)
QFont defaultFont () const
QTextFormat format (int idx) const
bool hasFormatCached (const QTextFormat &format) const
QTextImageFormat imageFormat (int index) const
int indexForFormat (const QTextFormat &f)
QTextListFormat listFormat (int index) const
int numFormats () const
QTextFormat objectFormat (int objectIndex) const
int objectFormatIndex (int objectIndex) const
QTextFormatCollection & operator= (const QTextFormatCollection &rhs)
QTextFormatCollection ()
QTextFormatCollection (const QTextFormatCollection &rhs)
void setDefaultFont (const QFont &f)
void setObjectFormat (int objectIndex, const QTextFormat &format)
void setObjectFormatIndex (int objectIndex, int formatIndex)
QTextTableFormat tableFormat (int index) const
~QTextFormatCollection ()
Public Variables
FormatVector formats
QMultiHash< uint, int > hashes
QVector< qint32 > objFormats
Properties
QFont defaultFnt
Detailed Description
Definition at line 62 of file qtextformat_p.h.
Typedefs
FormatVector
typedef QVector<QTextFormat> QTextFormatCollection::FormatVector
Definition at line 96 of file qtextformat_p.h.
Constructors and Destructors
QTextFormatCollection() [1/2]
QTextFormatCollection::QTextFormatCollection () inline
Definition at line 65 of file qtextformat_p.h.
 {}
~QTextFormatCollection()
QTextFormatCollection::~QTextFormatCollection ()
Definition at line 3865 of file qtextformat.cpp.
 {
 }
QTextFormatCollection() [2/2]
QTextFormatCollection::QTextFormatCollection (const QTextFormatCollection & rhs)
Definition at line 3852 of file qtextformat.cpp.
 {
     formats = rhs.formats;
     objFormats = rhs.objFormats;
 }
Functions
blockFormat()
QTextBlockFormat QTextFormatCollection::blockFormat (int index) const inline
Definition at line 83 of file qtextformat_p.h.
Referenced by QTextDocumentPrivate::setBlockFormat(), and QTextDocumentPrivate::undoRedo().
     { return format(index).toBlockFormat(); }
charFormat()
QTextCharFormat QTextFormatCollection::charFormat (int index) const inline
Definition at line 85 of file qtextformat_p.h.
Referenced by QTextLayout::additionalFormats(), QAbstractTextDocumentLayout::anchorAt(), QPlainTextEdit::anchorAt(), QTextCursorPrivate::canDelete(), QTextCursor::charFormat(), QTextTableCell::format(), QAbstractTextDocumentLayout::format(), QTextEngine::format(), QTextDocumentPrivate::insertBlock(), QTextTable::insertColumns(), QTextTable::insertRows(), QTextTable::mergeCells(), QTextTable::removeColumns(), QTextTable::removeRows(), QTextDocumentPrivate::undoRedo(), and QTextTablePrivate::update().
     { return format(index).toCharFormat(); }
createObjectIndex()
int QTextFormatCollection::createObjectIndex (const QTextFormat & f)
Definition at line 3937 of file qtextformat.cpp.
Referenced by QTextCopyHelper::convertFormatIndex(), QTextCopyHelper::copy(), and QTextDocumentPrivate::createObject().
 {
     const int objectIndex = objFormats.size();
     objFormats.append(indexForFormat(f));
     return objectIndex;
 }
defaultFont()
QFont QTextFormatCollection::defaultFont () const inline
Definition at line 102 of file qtextformat_p.h.
 { return defaultFnt; }
format()
QTextFormat QTextFormatCollection::format (int idx) const
Definition at line 3944 of file qtextformat.cpp.
Referenced by QTextCopyHelper::appendFragment(), QTextCopyHelper::convertFormat(), QTextCopyHelper::convertFormatIndex(), QTextInlineObject::format(), QTextEngine::format(), QTextDocumentPrivate::insert(), QTextDocumentPrivate::insert_block(), QTextCursorPrivate::insertBlock(), QTextDocumentPrivate::insertBlock(), QTextCursor::insertText(), QTextLine::layout_helper(), QTextDocumentPrivate::objectForFormat(), QTextDocumentPrivate::setCharFormat(), and QTextEngine::shape().
 {
     if (idx < 0 || idx >= formats.count())
         return QTextFormat();
     return formats.at(idx);
 }
hasFormatCached()
bool QTextFormatCollection::hasFormatCached (const QTextFormat & format) const
Definition at line 3899 of file qtextformat.cpp.
 {
     uint hash = getHash(format.d, format.format_type);
     QMultiHash<uint, int>::const_iterator i = hashes.find(hash);
     while (i != hashes.end() && i.key() == hash) {
         if (formats.value(i.value()) == format) {
             return true;
         }
         ++i;
     }
     return false;
 }
imageFormat()
QTextImageFormat QTextFormatCollection::imageFormat (int index) const inline
Definition at line 91 of file qtextformat_p.h.
     { return format(index).toImageFormat(); }
indexForFormat()
int QTextFormatCollection::indexForFormat (const QTextFormat & f)
Definition at line 3869 of file qtextformat.cpp.
Referenced by QTextCopyHelper::convertFormatIndex(), QTextTablePrivate::createTable(), QTextEngine::indexAdditionalFormats(), QTextDocumentPrivate::init(), QTextCursorPrivate::insertBlock(), QTextTable::insertColumns(), QTextDocumentPrivate::insertFrame(), QTextCursor::insertImage(), QTextTable::insertRows(), QTextCursor::insertText(), QTextCursor::mergeCharFormat(), QTextEngine::resolveAdditionalFormats(), QTextDocumentPrivate::setBlockFormat(), QTextCursor::setCharFormat(), QTextDocumentPrivate::setCharFormat(), and QTextTable::splitCell().
 {
     uint hash = getHash(format.d, format.format_type);
     QMultiHash<uint, int>::const_iterator i = hashes.find(hash);
     while (i != hashes.end() && i.key() == hash) {
         if (formats.value(i.value()) == format) {
             return i.value();
         }
         ++i;
     }
     int idx = formats.size();
     formats.append(format);
     QT_TRY{
         QTextFormat &f = formats.last();
         if (!f.d)
             f.d = new QTextFormatPrivate;
         f.d->resolveFont(defaultFnt);
         if (!hashes.contains(hash, idx))
             hashes.insert(hash, idx);
     } QT_CATCH(...) {
         formats.pop_back();
         QT_RETHROW;
     }
     return idx;
 }
listFormat()
QTextListFormat QTextFormatCollection::listFormat (int index) const inline
Definition at line 87 of file qtextformat_p.h.
     { return format(index).toListFormat(); }
numFormats()
int QTextFormatCollection::numFormats () const inline
Definition at line 94 of file qtextformat_p.h.
 { return formats.count(); }
objectFormat()
QTextFormat QTextFormatCollection::objectFormat (int objectIndex) const
Definition at line 3912 of file qtextformat.cpp.
Referenced by QTextCopyHelper::convertFormatIndex(), and QTextDocumentPrivate::objectForIndex().
 {
     if (objectIndex == -1)
         return QTextFormat();
     return format(objFormats.at(objectIndex));
 }
objectFormatIndex()
int QTextFormatCollection::objectFormatIndex (int objectIndex) const
Definition at line 3925 of file qtextformat.cpp.
Referenced by QTextDocumentPrivate::changeObjectFormat(), and QTextDocumentPrivate::undoRedo().
 {
     if (objectIndex == -1)
         return -1;
     return objFormats.at(objectIndex);
 }
operator=()
QTextFormatCollection & QTextFormatCollection::operator= (const QTextFormatCollection & rhs)
Definition at line 3858 of file qtextformat.cpp.
 {
     formats = rhs.formats;
     objFormats = rhs.objFormats;
     return *this;
 }
setDefaultFont()
void QTextFormatCollection::setDefaultFont (const QFont & f)
Definition at line 3952 of file qtextformat.cpp.
 {
     defaultFnt = f;
     for (int i = 0; i < formats.count(); ++i)
         if (formats[i].d)
             formats[i].d->resolveFont(defaultFnt);
 }
setObjectFormat()
void QTextFormatCollection::setObjectFormat (int objectIndex, const QTextFormat & format)
Definition at line 3919 of file qtextformat.cpp.
 {
     const int formatIndex = indexForFormat(f);
     objFormats[objectIndex] = formatIndex;
 }
setObjectFormatIndex()
void QTextFormatCollection::setObjectFormatIndex (int objectIndex, int formatIndex)
Definition at line 3932 of file qtextformat.cpp.
Referenced by QTextDocumentPrivate::changeObjectFormat().
 {
     objFormats[objectIndex] = formatIndex;
 }
tableFormat()
QTextTableFormat QTextFormatCollection::tableFormat (int index) const inline
Definition at line 89 of file qtextformat_p.h.
     { return format(index).toTableFormat(); }
Properties
defaultFnt
QFont QTextFormatCollection::defaultFnt private
Definition at line 106 of file qtextformat_p.h.
formats
FormatVector QTextFormatCollection::formats
Definition at line 98 of file qtextformat_p.h.
Referenced by operator=(), and QTextFormatCollection().
hashes
QMultiHash<uint,int> QTextFormatCollection::hashes
Definition at line 100 of file qtextformat_p.h.
objFormats
QVector<qint32> QTextFormatCollection::objFormats
Definition at line 99 of file qtextformat_p.h.
Referenced by operator=(), and QTextFormatCollection().
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat_p.h
/src/gui/text/qtextformat.cpp