Qt 4.8: QXlibDisplay Class Reference
QXlibDisplay Class Reference
#include <qxlibdisplay.h>
Public Functions
QString displayName () const
void flush () const
Display * nativeDisplay () const
QXlibDisplay (Display *display)
void sync () const
~QXlibDisplay ()
Properties
Display * mDisplay
QString mDisplayName
Detailed Description
Definition at line 47 of file qxlibdisplay.h.
Constructors and Destructors
QXlibDisplay()
QXlibDisplay::QXlibDisplay (Display * display)
Definition at line 44 of file qxlibdisplay.cpp.
     : mDisplay(display)
 {
     if (!mDisplay) {
         qFatal("Cannot connect to X server");
     }
     mDisplayName = QString::fromLocal8Bit(DisplayString(mDisplay));
 }
~QXlibDisplay()
QXlibDisplay::~QXlibDisplay ()
Definition at line 53 of file qxlibdisplay.cpp.
 {
     XCloseDisplay(mDisplay);
 }
Functions
displayName()
QString QXlibDisplay::displayName () const
Definition at line 58 of file qxlibdisplay.cpp.
Referenced by QTestLiteStaticInfoPrivate::initializeAllAtoms().
 {
      { return mDisplayName; }
 }
flush()
void QXlibDisplay::flush () const
Definition at line 75 of file qxlibdisplay.cpp.
Referenced by QXlibClipboard::clipboardReadIncrementalProperty(), QXlibClipboard::clipboardReadProperty(), QXlibWindow::setCursor(), and QXlibScreen::waitForClipboardEvent().
 {
     XFlush(mDisplay);
 }
nativeDisplay()
Display * QXlibDisplay::nativeDisplay () const
Definition at line 65 of file qxlibdisplay.cpp.
Referenced by QXlibScreen::blackPixel(), QXlibKeyboard::changeLayout(), QXlibWindow::createGC(), QXlibWindow::doSizeHints(), QXlibClipboardMime::empty(), QXlibScreen::eventDispatcher(), QXlibWindowSurface::flush(), QXlibClipboardMime::formats_sys(), QXlibWindow::getMWMHints(), QXlibWindow::getNetWmState(), QXlibScreen::grabWindow(), QXlibIntegration::hasOpenGL(), QTestLiteStaticInfoPrivate::initializeAllAtoms(), QTestLiteStaticInfoPrivate::initializeSupportedAtoms(), QXlibWindow::lower(), QXlibClipboard::owner(), QGLXContext::QGLXContext(), QXlibScreen::QXlibScreen(), QXlibWindow::QXlibWindow(), QXlibWindow::raise(), QXlibWindow::requestActivateWindow(), QXlibClipboard::requestor(), QXlibWindowSurface::resizeShmImage(), QTestLiteStaticInfoPrivate::resolveXFixes(), QXlibScreen::rootWindow(), QXlibWindow::setCursor(), QXlibWindow::setGeometry(), QXlibClipboard::setMimeData(), QXlibWindow::setMWMHints(), QXlibClipboard::setOwner(), QXlibWindow::setParent(), QXlibClipboard::setRequestor(), QXlibWindow::setVisible(), QXlibWindow::setWindowFlags(), QXlibWindow::setWindowTitle(), QXlibScreen::waitForClipboardEvent(), QXlibScreen::whitePixel(), and QXlibWindow::~QXlibWindow().
 {
     return mDisplay;
 }
sync()
void QXlibDisplay::sync () const
Definition at line 70 of file qxlibdisplay.cpp.
Referenced by QXlibWindowSurface::flush(), and QXlibClipboard::getDataInFormat().
 {
     XSync(mDisplay, False);
 }
Properties
mDisplay
Display* QXlibDisplay::mDisplay private
Definition at line 59 of file qxlibdisplay.h.
Referenced by flush(), nativeDisplay(), QXlibDisplay(), sync(), and ~QXlibDisplay().
mDisplayName
QString QXlibDisplay::mDisplayName private
Definition at line 60 of file qxlibdisplay.h.
Referenced by displayName(), and QXlibDisplay().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xlib/qxlibdisplay.h
/src/plugins/platforms/xlib/qxlibdisplay.cpp