Qt 4.8: QSslCipher Class Reference
QSslCipher Class Reference
The QSslCipher class represents an SSL cryptographic cipher.
#include <qsslcipher.h>
Public Functions
QString authenticationMethod () const
Returns the cipher's authentication method as a QString.
QString encryptionMethod () const
Returns the cipher's encryption method as a QString.
bool isNull () const
Returns true if this is a null cipher; otherwise returns false.
QString keyExchangeMethod () const
Returns the cipher's key exchange method as a QString.
QString name () const
Returns the name of the cipher, or an empty QString if this is a null cipher.
bool operator!= (const QSslCipher &other) const
Returns true if this cipher is not the same as other; otherwise, false is returned.
QSslCipher & operator= (const QSslCipher &other)
Copies the contents of other into this cipher, making the two ciphers identical.
bool operator== (const QSslCipher &other) const
Returns true if this cipher is the same as other; otherwise, false is returned.
QSsl::SslProtocol protocol () const
Returns the cipher's protocol type, or QSsl::UnknownProtocol if QSslCipher is unable to determine the protocol (protocolString() may contain more information).
QString protocolString () const
Returns the cipher's protocol as a QString.
QSslCipher ()
Constructs an empty QSslCipher object.
QSslCipher (const QString &name, QSsl::SslProtocol protocol)
Constructs a QSslCipher object for the cipher determined by name and protocol.
QSslCipher (const QSslCipher &other)
Constructs an identical copy of the other cipher.
int supportedBits () const
Returns the number of bits supported by the cipher.
int usedBits () const
Returns the number of bits used by the cipher.
~QSslCipher ()
Destroys the QSslCipher object.
Properties
QScopedPointer< QSslCipherPrivate > d
Friends
class QSslSocketBackendPrivate
Detailed Description
The QSslCipher class represents an SSL cryptographic cipher.
Since
4.3
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QSslCipher stores information about one cryptographic cipher. It is most commonly used with QSslSocket, either for configuring which ciphers the socket can use, or for displaying the socket's ciphers to the user.
See also
QSslSocket, QSslKey
Definition at line 59 of file qsslcipher.h.
Constructors and Destructors
QSslCipher() [1/3]
QSslCipher::QSslCipher ()
Constructs an empty QSslCipher object.
Definition at line 77 of file qsslcipher.cpp.
     : d(new QSslCipherPrivate)
 {
 }
QSslCipher() [2/3]
QSslCipher::QSslCipher (const QString & name, QSsl::SslProtocol protocol)
Constructs a QSslCipher object for the cipher determined by name and protocol.
The constructor accepts only supported ciphers (i.e., the name and protocol must identify a cipher in the list of ciphers returned by QSslSocket::supportedCiphers()).
You can call isNull() after construction to check if name and protocol correctly identified a supported cipher.
Definition at line 92 of file qsslcipher.cpp.
     : d(new QSslCipherPrivate)
 {
     foreach (const QSslCipher &cipher, QSslSocket::supportedCiphers()) {
         if (cipher.name() == name && cipher.protocol() == protocol) {
             *this = cipher;
             return;
         }
     }
 }
QSslCipher() [3/3]
QSslCipher::QSslCipher (const QSslCipher & other)
Constructs an identical copy of the other cipher.
Definition at line 106 of file qsslcipher.cpp.
     : d(new QSslCipherPrivate)
 {
     *d.data() = *other.d.data();
 }
~QSslCipher()
QSslCipher::~QSslCipher ()
Destroys the QSslCipher object.
Definition at line 115 of file qsslcipher.cpp.
 {
 }
Functions
authenticationMethod()
QString QSslCipher::authenticationMethod () const
Returns the cipher's authentication method as a QString.
Definition at line 198 of file qsslcipher.cpp.
 {
     return d->authenticationMethod;
 }
encryptionMethod()
QString QSslCipher::encryptionMethod () const
Returns the cipher's encryption method as a QString.
Definition at line 206 of file qsslcipher.cpp.
 {
     return d->encryptionMethod;
 }
isNull()
bool QSslCipher::isNull () const
Returns true if this is a null cipher; otherwise returns false.
Definition at line 151 of file qsslcipher.cpp.
Referenced by QSslSocketPrivate::resetDefaultCiphers(), and QSslSocket::setCiphers().
 {
     return d->isNull;
 }
keyExchangeMethod()
QString QSslCipher::keyExchangeMethod () const
Returns the cipher's key exchange method as a QString.
Definition at line 190 of file qsslcipher.cpp.
 {
     return d->keyExchangeMethod;
 }
name()
QString QSslCipher::name () const
Returns the name of the cipher, or an empty QString if this is a null cipher.
See also
isNull()
Definition at line 162 of file qsslcipher.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext(), operator<<(), QSslCipher(), and QSslSocketPrivate::resetDefaultCiphers().
 {
     return d->name;
 }
operator!=()
bool QSslCipher::operator!= (const QSslCipher & other) const inline
Returns true if this cipher is not the same as other; otherwise, false is returned.
Definition at line 68 of file qsslcipher.h.
 { return !operator==(other); }
operator=()
QSslCipher & QSslCipher::operator= (const QSslCipher & other)
Copies the contents of other into this cipher, making the two ciphers identical.
Definition at line 123 of file qsslcipher.cpp.
 {
     *d.data() = *other.d.data();
     return *this;
 }
operator==()
bool QSslCipher::operator== (const QSslCipher & other) const
Returns true if this cipher is the same as other; otherwise, false is returned.
Definition at line 133 of file qsslcipher.cpp.
 {
     return d->name == other.d->name && d->protocol == other.d->protocol;
 }
protocol()
QSsl::SslProtocol QSslCipher::protocol () const
Returns the cipher's protocol type, or QSsl::UnknownProtocol if QSslCipher is unable to determine the protocol (protocolString() may contain more information).
See also
protocolString()
Definition at line 228 of file qsslcipher.cpp.
Referenced by QSslCipher().
 {
     return d->protocol;
 }
protocolString()
QString QSslCipher::protocolString () const
Returns the cipher's protocol as a QString.
See also
protocol()
Definition at line 216 of file qsslcipher.cpp.
Referenced by operator<<().
 {
     return d->protocolString;
 }
supportedBits()
int QSslCipher::supportedBits () const
Returns the number of bits supported by the cipher.
See also
usedBits()
Definition at line 172 of file qsslcipher.cpp.
 {
     return d->supportedBits;
 }
usedBits()
int QSslCipher::usedBits () const
Returns the number of bits used by the cipher.
See also
supportedBits()
Definition at line 182 of file qsslcipher.cpp.
Referenced by operator<<().
 {
     return d->bits;
 }
Friends and Related Functions
QSslSocketBackendPrivate
friend class QSslSocketBackendPrivate friend
Definition at line 83 of file qsslcipher.h.
Properties
d
QScopedPointer<QSslCipherPrivate> QSslCipher::d private
Definition at line 82 of file qsslcipher.h.
Referenced by authenticationMethod(), encryptionMethod(), isNull(), keyExchangeMethod(), name(), operator=(), operator==(), protocol(), protocolString(), QSslCipher(), QSslSocketBackendPrivate::QSslCipher_from_SSL_CIPHER(), supportedBits(), and usedBits().
The documentation for this class was generated from the following files:
/src/network/ssl/qsslcipher.h
/src/network/ssl/qsslcipher.cpp