Qt 4.8: QPatternist::NamedSchemaComponent Class Reference
QPatternist::NamedSchemaComponent Class Reference
Base class for all named components that can appear in a W3C XML Schema.
#include <qnamedschemacomponent_p.h>
Public Types
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
QXmlName m_name
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Base class for all named components that can appear in a W3C XML Schema.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 71 of file qnamedschemacomponent_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<NamedSchemaComponent> QPatternist::NamedSchemaComponent::Ptr
Definition at line 74 of file qnamedschemacomponent_p.h.
Enumerations
BlockingConstraint
enum QPatternist::NamedSchemaComponent::BlockingConstraint
Describes the blocking constraints that are given by the 'block' attributes.
Enumerator
RestrictionConstraint
ExtensionConstraint
SubstitutionConstraint
Definition at line 79 of file qnamedschemacomponent_p.h.
             {
                 RestrictionConstraint = 1,
                 ExtensionConstraint = 2,
                 SubstitutionConstraint = 4
             };
Constructors and Destructors
NamedSchemaComponent()
NamedSchemaComponent::NamedSchemaComponent ()
Creates a new named schema component.
Definition at line 48 of file qnamedschemacomponent.cpp.
 {
 }
~NamedSchemaComponent()
NamedSchemaComponent::~NamedSchemaComponent () virtual
Destroys the named schema component.
Definition at line 52 of file qnamedschemacomponent.cpp.
 {
 }
Functions
displayName()
QString NamedSchemaComponent::displayName (const NamePool::Ptr & namePool) const virtual
Returns the display name of the schema component.
Parameters
namePool The name pool the name belongs to.
Reimplemented in QPatternist::XsdComplexType, QPatternist::XsdUserSchemaType< TSuperClass >, QPatternist::XsdUserSchemaType< AnyType >, QPatternist::XsdUserSchemaType< AnySimpleType >, and QPatternist::XsdSimpleType.
Definition at line 66 of file qnamedschemacomponent.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaChecker::checkComplexTypeConstraints(), QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaChecker::checkElementConstraints(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaResolver::checkRedefinedAttributeGroups(), QPatternist::XsdSchemaResolver::checkRedefinedGroups(), derivedTermValid(), QPatternist::XsdSchemaDebugger::dumpAttribute(), QPatternist::XsdSchemaDebugger::dumpElement(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveKeyReferences(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::transitionTypeToString(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint(), QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint(), and QPatternist::XsdValidatingInstanceReader::validateUniqueIdentityConstraint().
 {
     return np->displayName(m_name);
 }
name()
QXmlName NamedSchemaComponent::name (const NamePool::Ptr & namePool) const virtual
Returns the name of the schema component.
Parameters
namePool The name pool the name belongs to.
Reimplemented in QPatternist::XsdUserSchemaType< TSuperClass >, QPatternist::XsdUserSchemaType< AnyType >, and QPatternist::XsdUserSchemaType< AnySimpleType >.
Definition at line 61 of file qnamedschemacomponent.cpp.
Referenced by QPatternist::XsdSchema::addAttribute(), QPatternist::XsdSchemaParser::addAttribute(), QPatternist::XsdSchema::addAttributeGroup(), QPatternist::XsdSchemaParser::addAttributeGroup(), QPatternist::XsdSchema::addElement(), QPatternist::XsdSchemaParser::addElement(), QPatternist::XsdSchema::addElementGroup(), QPatternist::XsdSchemaParser::addElementGroup(), QPatternist::XsdSchema::addIdentityConstraint(), QPatternist::XsdSchemaParser::addIdentityConstraint(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), derivedTermValid(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::inputEqualsTransition(), isSubstGroupHeadOf(), QPatternist::XsdSchemaMerger::merge(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveTermReference(), setName(), QPatternist::XsdSchemaHelper::substitutionGroupOkTransitive(), termMatches(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint(), QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint(), and QPatternist::XsdValidatingInstanceReader::validateUniqueIdentityConstraint().
 {
     return m_name;
 }
setName()
void NamedSchemaComponent::setName (const QXmlName & name)
Sets the name of the schema component.
Definition at line 56 of file qnamedschemacomponent.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseUnique(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_name = name;
 }
Properties
m_name
QXmlName QPatternist::NamedSchemaComponent::m_name private
Definition at line 117 of file qnamedschemacomponent_p.h.
Referenced by displayName(), name(), and setName().
The documentation for this class was generated from the following files:
/src/xmlpatterns/type/qnamedschemacomponent_p.h
/src/xmlpatterns/type/qnamedschemacomponent.cpp