Qt 4.8: QPaintEngine Class Reference
QPaintEngine Class Reference abstract
The QPaintEngine class provides an abstract definition of how QPainter draws to a given device on a given platform.
#include <qpaintengine.h>
Public Types
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Functions
virtual bool begin (QPaintDevice *pdev)=0
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
virtual void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)=0
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
virtual void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
virtual void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
virtual void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
virtual bool end ()=0
Reimplement this function to finish painting on the current paint device.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual Type type () const =0
Reimplement this function to return the paint engine Type.
virtual void updateState (const QPaintEngineState &state)=0
Reimplement this function to update the state of a paint engine.
virtual ~QPaintEngine ()
Destroys the paint engine.
Protected Functions
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Private Functions
bool autoDestruct () const
void setAutoDestruct (bool autoDestr)
Friends
class QFontEngineBox
class QFontEngineFT
class QFontEngineMac
class QFontEngineQPF
class QFontEngineQPF1
class QFontEngineWin
class QMacCGContext
class QMacPrintEngine
class QMacPrintEnginePrivate
class QPainter
class QPainterPrivate
class QPainterReplayer
class QPreviewPaintEngine
class QProxyFontEngine
class QPSPrintEngine
class QtopiaPrintEngine
class QtopiaPrintEnginePrivate
class QWidget
class QWidgetPrivate
class QWin32PaintEngine
class QWin32PaintEnginePrivate
class QX11GLPixmapData
Detailed Description
The QPaintEngine class provides an abstract definition of how QPainter draws to a given device on a given platform.
Qt 4.0 provides several premade implementations of QPaintEngine for the different painter backends we support. We provide one paint engine for each window system and painting framework we support. This includes X11 on Unix/Linux and CoreGraphics on Mac OS X. In addition we provide QPaintEngine implementations for OpenGL (accessible through QGLWidget) and PostScript (accessible through QPSPrinter on X11). Additionally there is a raster-based paint engine that is a fallback for when an engine does not support a certain capability.
If one wants to use QPainter to draw to a different backend, one must subclass QPaintEngine and reimplement all its virtual functions. The QPaintEngine implementation is then made available by subclassing QPaintDevice and reimplementing the virtual function QPaintDevice::paintEngine().
QPaintEngine is created and owned by the QPaintDevice that created it.
The big advantage of the QPaintEngine approach opposed to Qt 3's QPainter/QPaintDevice::cmd() approach is that it is now possible to adapt to multiple technologies on each platform and take advantage of each to the fullest.
See also
QPainter, QPaintDevice::paintEngine(), {Paint System}
Definition at line 90 of file qpaintengine.h.
Enumerations
DirtyFlag
enum QPaintEngine::DirtyFlag
QPaintEngine::updateState().
DirtyPen The pen is dirty and needs to be updated.
DirtyBrush The brush is dirty and needs to be updated.
DirtyBrushOrigin The brush origin is dirty and needs to updated.
DirtyFont The font is dirty and needs to be updated.
DirtyBackground The background is dirty and needs to be updated.
DirtyBackgroundMode The background mode is dirty and needs to be updated.
DirtyTransform The transform is dirty and needs to be updated.
DirtyClipRegion The clip region is dirty and needs to be updated.
DirtyClipPath The clip path is dirty and needs to be updated.
DirtyHints The render hints is dirty and needs to be updated.
DirtyCompositionMode The composition mode is dirty and needs to be updated.
DirtyClipEnabled Whether clipping is enabled or not is dirty and needs to be updated.
DirtyOpacity The constant opacity has changed and needs to be updated as part of the state change in
AllDirty Convenience enum used internally.
These types are used by QPainter to trigger lazy updates of the various states in the QPaintEngine using QPaintEngine::updateState().
A paint engine must update every dirty state.
Enumerator
DirtyPen
DirtyBrush
DirtyBrushOrigin
DirtyFont
DirtyBackground
DirtyBackgroundMode
DirtyTransform
DirtyClipRegion
DirtyClipPath
DirtyHints
DirtyCompositionMode
DirtyClipEnabled
DirtyOpacity
AllDirty
Definition at line 125 of file qpaintengine.h.
                    {
         DirtyPen                = 0x0001,
         DirtyBrush              = 0x0002,
         DirtyBrushOrigin        = 0x0004,
         DirtyFont               = 0x0008,
         DirtyBackground         = 0x0010,
         DirtyBackgroundMode     = 0x0020,
         DirtyTransform          = 0x0040,
         DirtyClipRegion         = 0x0080,
         DirtyClipPath           = 0x0100,
         DirtyHints              = 0x0200,
         DirtyCompositionMode    = 0x0400,
         DirtyClipEnabled        = 0x0800,
         DirtyOpacity            = 0x1000,
         AllDirty                = 0xffff
     };
PaintEngineFeature
enum QPaintEngine::PaintEngineFeature
This enum is used to describe the features or capabilities that the paint engine has.
If a feature is not supported by the engine, QPainter will do a best effort to emulate that feature through other means and pass on an alpha blended QImage to the engine with the emulated results. Some features cannot be emulated: AlphaBlend and PorterDuff.
AlphaBlend The engine can alpha blend primitives.
Antialiasing The engine can use antialising to improve the appearance of rendered primitives.
BlendModes The engine supports blending modes.
BrushStroke The engine supports drawing strokes that contain brushes as fills, not just solid colors (e.g. a dashed gradient line of width 2).
ConicalGradientFill The engine supports conical gradient fills.
ConstantOpacity The engine supports the feature provided by QPainter::setOpacity().
LinearGradientFill The engine supports linear gradient fills.
MaskedBrush The engine is capable of rendering brushes that has a texture with an alpha channel or a mask.
ObjectBoundingModeGradients The engine has native support for gradients with coordinate mode QGradient::ObjectBoundingMode. Otherwise, if QPaintEngine::PatternTransform is supported, object bounding mode gradients are converted to gradients with coordinate mode QGradient::LogicalMode and a brush transform for the coordinate mapping.
PainterPaths The engine has path support.
PaintOutsidePaintEvent The engine is capable of painting outside of paint events.
PatternBrush The engine is capable of rendering brushes with the brush patterns specified in Qt::BrushStyle.
PatternTransform The engine has support for transforming brush patterns.
PerspectiveTransform The engine has support for performing perspective transformations on primitives.
PixmapTransform The engine can transform pixmaps, including rotation and shearing.
PorterDuff The engine supports Porter-Duff operations
PrimitiveTransform The engine has support for transforming drawing primitives.
RadialGradientFill The engine supports radial gradient fills.
RasterOpModes The engine supports bitwise raster operations.
AllFeatures All of the above features. This enum value is usually used as a bit mask.
Enumerator
PrimitiveTransform
PatternTransform
PixmapTransform
PatternBrush
LinearGradientFill
RadialGradientFill
ConicalGradientFill
AlphaBlend
PorterDuff
PainterPaths
Antialiasing
BrushStroke
ConstantOpacity
MaskedBrush
PerspectiveTransform
BlendModes
ObjectBoundingModeGradients
RasterOpModes
PaintOutsidePaintEvent
AllFeatures
Definition at line 94 of file qpaintengine.h.
{
         PrimitiveTransform          = 0x00000001, // Can transform primitives brushes
         PatternTransform            = 0x00000002, // Can transform pattern brushes
         PixmapTransform             = 0x00000004, // Can transform pixmaps
         PatternBrush                = 0x00000008, // Can fill with pixmaps and standard patterns
         LinearGradientFill          = 0x00000010, // Can fill gradient areas
         RadialGradientFill          = 0x00000020, // Can render radial gradients
         ConicalGradientFill         = 0x00000040, // Can render conical gradients
         AlphaBlend                  = 0x00000080, // Can do source over alpha blend
         PorterDuff                  = 0x00000100, // Can do general porter duff compositions
         PainterPaths                = 0x00000200, // Can fill, outline and clip paths
         Antialiasing                = 0x00000400, // Can antialias lines
         BrushStroke                 = 0x00000800, // Can render brush based pens
         ConstantOpacity             = 0x00001000, // Can render at constant opacity
         MaskedBrush                 = 0x00002000, // Can fill with textures that has an alpha channel or mask
         PerspectiveTransform        = 0x00004000, // Can do perspective transformations
         BlendModes                  = 0x00008000, // Can do extended Porter&Duff composition
         ObjectBoundingModeGradients = 0x00010000, // Can do object bounding mode gradients
         RasterOpModes               = 0x00020000, // Can do logical raster operations
         PaintOutsidePaintEvent      = 0x20000000, // Engine is capable of painting outside paint events
         /*                          0x10000000, // Used for emulating
                                     QGradient::StretchToDevice,
                                     defined in qpainter.cpp
                                     0x40000000, // Used internally for emulating opaque backgrounds
         */
         AllFeatures               = 0xffffffff  // For convenience
     };
PolygonDrawMode
enum QPaintEngine::PolygonDrawMode
OddEvenMode The polygon should be drawn using OddEven fill rule.
WindingMode The polygon should be drawn using Winding fill rule.
ConvexMode The polygon is a convex polygon and can be drawn using specialized algorithms where available.
PolylineMode Only the outline of the polygon should be drawn.
Enumerator
OddEvenMode
WindingMode
ConvexMode
PolylineMode
Definition at line 144 of file qpaintengine.h.
{
         OddEvenMode,
         WindingMode,
         ConvexMode,
         PolylineMode
     };
Type
enum QPaintEngine::Type
X11
Windows
MacPrinter
CoreGraphics Mac OS X's Quartz2D (CoreGraphics)
QuickDraw Mac OS X's QuickDraw
QWindowSystem Qt for Embedded Linux
PostScript
OpenGL
Picture QPicture format
SVG Scalable Vector Graphics XML format
Raster
Direct3D Windows only, Direct3D based engine
Pdf Portable Document Format
OpenVG
User First user type ID
MaxUser Last user type ID
OpenGL2
PaintBuffer
Blitter
Enumerator
X11
Windows
QuickDraw
CoreGraphics
MacPrinter
QWindowSystem
PostScript
OpenGL
Picture
SVG
Raster
Direct3D
Pdf
OpenVG
OpenGL2
PaintBuffer
Blitter
User
MaxUser
Definition at line 201 of file qpaintengine.h.
               {
         X11,
         Windows,
         QuickDraw, CoreGraphics, MacPrinter,
         QWindowSystem,
         PostScript,
         OpenGL,
         Picture,
         SVG,
         Raster,
         Direct3D,
         Pdf,
         OpenVG,
         OpenGL2,
         PaintBuffer,
         Blitter,
         User = 50,    // first user type id
         MaxUser = 100 // last user type id
     };
Constructors and Destructors
QPaintEngine() [1/2]
QPaintEngine::QPaintEngine (PaintEngineFeatures features = 0) explicit
Creates a paint engine with the featureset specified by caps.
Definition at line 758 of file qpaintengine.cpp.
     : state(0),
       gccaps(caps),
       active(0),
       selfDestruct(false),
       extended(false),
       d_ptr(new QPaintEnginePrivate)
 {
     d_ptr->q_ptr = this;
 }
~QPaintEngine()
QPaintEngine::~QPaintEngine () virtual
Destroys the paint engine.
Definition at line 787 of file qpaintengine.cpp.
 {
 }
QPaintEngine() [2/2]
QPaintEngine::QPaintEngine (QPaintEnginePrivate & dptr, PaintEngineFeatures caps = 0) protected
Warning
This function is not part of the public interface.
Definition at line 773 of file qpaintengine.cpp.
     : state(0),
       gccaps(caps),
       active(0),
       selfDestruct(false),
       extended(false),
       d_ptr(&dptr)
 {
     d_ptr->q_ptr = this;
 }
Functions
autoDestruct()
bool QPaintEngine::autoDestruct () const inline private
Definition at line 250 of file qpaintengine.h.
Referenced by QWidgetPrivate::drawWidget().
 { return selfDestruct; }
begin()
bool QPaintEngine::begin (QPaintDevice * pdev) pure virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implemented in QOnScreenRasterPaintEngine, QPaintBufferEngine, QPdfBaseEngine, QSvgPaintEngine, QRasterPaintEngine, QGL2PaintEngineEx, QPdfEngine, QVGPaintEngine, QX11PaintEngine, QOpenGLPaintEngine, QMacPrintEngine, QPSPrintEngine, QtopiaPrintEngine, QWin32PrintEngine, QCoreGraphicsPaintEngine, QPicturePaintEngine, QPreviewPaintEngine, QEmulationPaintEngine, QAlphaPaintEngine, QDirectFBPaintEngine, QVolatileImagePaintEngine, and QBlitterPaintEngine.
Referenced by QVGPaintEngine::type().
clearDirty()
void QPaintEngine::clearDirty (DirtyFlags df) inline
Warning
This function is not part of the public interface.
Definition at line 354 of file qpaintengine.h.
Referenced by QPainterPrivate::updateStateImpl().
 {
     Q_ASSERT(state);
     state->dirtyFlags &= ~static_cast<uint>(df);
 }
coordinateOffset()
QPoint QPaintEngine::coordinateOffset () const virtual
Returns the offset from the painters origo to the engines origo.
Warning
This function is not part of the public interface.
This value is used by QPainter for engines who have internal double buffering.
This function only makes sense when the engine is active.
Reimplemented in QOnScreenRasterPaintEngine, and QRasterPaintEngine.
Definition at line 1021 of file qpaintengine.cpp.
Referenced by QPainterPrivate::attachPainterPrivate().
 {
     return QPoint();
 }
drawEllipse() [1/2]
void QPaintEngine::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented in QPaintBufferEngine, QPaintEngineEx, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QX11PaintEngine, QMacPrintEngine, QCoreGraphicsPaintEngine, QDirectFBPaintEngine, QPicturePaintEngine, and QBlitterPaintEngine.
Definition at line 551 of file qpaintengine.cpp.
Referenced by QX11PaintEngine::drawEllipse(), and QCoreGraphicsPaintEngine::drawEllipse().
 {
     QPainterPath path;
     path.addEllipse(rect);
     if (hasFeature(PainterPaths)) {
         drawPath(path);
     } else {
         QPolygonF polygon = path.toFillPolygon();
         drawPolygon(polygon.data(), polygon.size(), ConvexMode);
     }
 }
drawEllipse() [2/2]
void QPaintEngine::drawEllipse (const QRect & r) virtual
The default implementation of this function calls the floating point version of this function.
Reimplemented in QPaintBufferEngine, QPaintEngineEx, QVGPaintEngine, QCoreGraphicsPaintEngine, and QX11PaintEngine.
Definition at line 567 of file qpaintengine.cpp.
 {
     drawEllipse(QRectF(rect));
 }
drawImage()
void QPaintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented in QPaintBufferEngine, QPaintEngineEx, QRasterPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QGL2PaintEngineEx, QX11PaintEngine, QMacPrintEngine, QCoreGraphicsPaintEngine, QPicturePaintEngine, QPdfEngine, QBlitterPaintEngine, QPSPrintEngine, QEmulationPaintEngine, and QDirectFBPaintEngine.
Definition at line 670 of file qpaintengine.cpp.
Referenced by QPainterPrivate::draw_helper(), and QX11PaintEngine::drawImage().
 {
     QRectF baseSize(0, 0, image.width(), image.height());
     QImage im = image;
     if (baseSize != sr)
         im = im.copy(qFloor(sr.x()), qFloor(sr.y()),
                      qCeil(sr.width()), qCeil(sr.height()));
     QPixmap pm = QPixmap::fromImage(im, flags);
     drawPixmap(r, pm, QRectF(QPointF(0, 0), pm.size()));
 }
drawLines() [1/2]
void QPaintEngine::drawLines (const QLine * lines, int lineCount) virtual
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QPaintEngineEx, QOpenGLPaintEngine, QCoreGraphicsPaintEngine, QVGPaintEngine, QX11PaintEngine, and QDirectFBPaintEngine.
Definition at line 867 of file qpaintengine.cpp.
Referenced by QCoreGraphicsPaintEngine::drawLines().
 {
     struct PointF {
         qreal x;
         qreal y;
     };
     struct LineF {
         PointF p1;
         PointF p2;
     };
     Q_ASSERT(sizeof(PointF) == sizeof(QPointF));
     Q_ASSERT(sizeof(LineF) == sizeof(QLineF));
     LineF fl[256];
     while (lineCount) {
         int i = 0;
         while (i < lineCount && i < 256) {
             fl[i].p1.x = lines[i].x1();
             fl[i].p1.y = lines[i].y1();
             fl[i].p2.x = lines[i].x2();
             fl[i].p2.y = lines[i].y2();
             ++i;
         }
         drawLines((QLineF *)(void *)fl, i);
         lines += i;
         lineCount -= i;
     }
 }
drawLines() [2/2]
void QPaintEngine::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented in QPaintBufferEngine, QPdfBaseEngine, QRasterPaintEngine, QPaintEngineEx, QOpenGLPaintEngine, QVGPaintEngine, QMacPrintEngine, QX11PaintEngine, QCoreGraphicsPaintEngine, and QDirectFBPaintEngine.
Definition at line 842 of file qpaintengine.cpp.
 {
     for (int i=0; i<lineCount; ++i) {
         QPointF pts[2] = { lines[i].p1(), lines[i].p2() };
         if (pts[0] == pts[1]) {
             if (state->pen().capStyle() != Qt::FlatCap)
                 drawPoints(pts, 1);
             continue;
         }
         drawPolygon(pts, 2, PolylineMode);
     }
 }
drawPath()
void QPaintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented in QPaintBufferEngine, QPdfBaseEngine, QPaintEngineEx, QSvgPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QX11PaintEngine, QMacPrintEngine, QCoreGraphicsPaintEngine, QPicturePaintEngine, QDirectFBPaintEngine, QWin32PrintEngine, QPreviewPaintEngine, and QAlphaPaintEngine.
Definition at line 803 of file qpaintengine.cpp.
Referenced by drawRects(), and QPainterPrivate::drawStretchedGradient().
 {
     if (hasFeature(PainterPaths)) {
         qWarning("QPaintEngine::drawPath: Must be implemented when feature PainterPaths is set");
     }
 }
drawPixmap()
void QPaintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) pure virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implemented in QPaintBufferEngine, QPaintEngineEx, QRasterPaintEngine, QSvgPaintEngine, QVGPaintEngine, QGL2PaintEngineEx, QOpenGLPaintEngine, QX11PaintEngine, QMacPrintEngine, QPicturePaintEngine, QCoreGraphicsPaintEngine, QPdfEngine, QWin32PrintEngine, QPSPrintEngine, QPreviewPaintEngine, QDirectFBPaintEngine, QtopiaPrintEngine, QEmulationPaintEngine, QAlphaPaintEngine, QBlitterPaintEngine, and QVolatileImagePaintEngine.
Referenced by qt_draw_tile().
drawPoints() [1/2]
void QPaintEngine::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QPdfBaseEngine, QPaintEngineEx, QVGPaintEngine, QOpenGLPaintEngine, QX11PaintEngine, QMacPrintEngine, QBlitterPaintEngine, QCoreGraphicsPaintEngine, and QDirectFBPaintEngine.
Definition at line 479 of file qpaintengine.cpp.
Referenced by drawLines(), QCoreGraphicsPaintEngine::drawPoints(), and QOpenGLPaintEngine::drawPoints().
 {
     QPainter *p = painter();
     if (!p)
         return;
     qreal penWidth = p->pen().widthF();
     if (penWidth == 0)
         penWidth = 1;
     bool ellipses = p->pen().capStyle() == Qt::RoundCap;
     p->save();
     QTransform transform;
     if (p->pen().isCosmetic()) {
         transform = p->transform();
         p->setTransform(QTransform());
     }
     p->setBrush(p->pen().brush());
     p->setPen(Qt::NoPen);
     for (int i=0; i<pointCount; ++i) {
         QPointF pos = transform.map(points[i]);
         QRectF rect(pos.x() - penWidth / 2, pos.y() - penWidth / 2, penWidth, penWidth);
         if (ellipses)
             p->drawEllipse(rect);
         else
             p->drawRect(rect);
     }
     p->restore();
 }
drawPoints() [2/2]
void QPaintEngine::drawPoints (const QPoint * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
The default implementation converts the first pointCount QPoints in points to QPointFs and calls the floating point version of drawPoints.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QPaintEngineEx, QVGPaintEngine, QOpenGLPaintEngine, QCoreGraphicsPaintEngine, QX11PaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 523 of file qpaintengine.cpp.
 {
     Q_ASSERT(sizeof(QT_PointF) == sizeof(QPointF));
     QT_PointF fp[256];
     while (pointCount) {
         int i = 0;
         while (i < pointCount && i < 256) {
             fp[i].x = points[i].x();
             fp[i].y = points[i].y();
             ++i;
         }
         drawPoints((QPointF *)(void *)fp, i);
         points += i;
         pointCount -= i;
     }
 }
drawPolygon() [1/2]
void QPaintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented in QPaintBufferEngine, QPdfBaseEngine, QPaintEngineEx, QSvgPaintEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QX11PaintEngine, QMacPrintEngine, QCoreGraphicsPaintEngine, QPicturePaintEngine, QDirectFBPaintEngine, QWin32PrintEngine, QBlitterPaintEngine, QPreviewPaintEngine, and QAlphaPaintEngine.
Definition at line 360 of file qpaintengine.cpp.
Referenced by drawLines(), QX11PaintEngine::drawPolygon(), QCoreGraphicsPaintEngine::drawPolygon(), and drawRects().
 {
     Q_ASSERT_X(qt_polygon_recursion != this, "QPaintEngine::drawPolygon",
                "At least one drawPolygon function must be implemented");
     qt_polygon_recursion = this;
     Q_ASSERT(sizeof(QT_Point) == sizeof(QPoint));
     QVarLengthArray<QT_Point> p(pointCount);
     for (int i = 0; i < pointCount; ++i) {
         p[i].x = qRound(points[i].x());
         p[i].y = qRound(points[i].y());
     }
     drawPolygon((QPoint *)p.data(), pointCount, mode);
     qt_polygon_recursion = 0;
 }
drawPolygon() [2/2]
void QPaintEngine::drawPolygon (const QPoint * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented in QPaintBufferEngine, QPaintEngineEx, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QCoreGraphicsPaintEngine, QX11PaintEngine, QDirectFBPaintEngine, and QBlitterPaintEngine.
Definition at line 390 of file qpaintengine.cpp.
 {
     Q_ASSERT_X(qt_polygon_recursion != this, "QPaintEngine::drawPolygon",
                "At least one drawPolygon function must be implemented");
     qt_polygon_recursion = this;
     Q_ASSERT(sizeof(QT_PointF) == sizeof(QPointF));
     QVarLengthArray<QT_PointF> p(pointCount);
     for (int i=0; i<pointCount; ++i) {
         p[i].x = points[i].x();
         p[i].y = points[i].y();
     }
     drawPolygon((QPointF *)p.data(), pointCount, mode);
     qt_polygon_recursion = 0;
 }
drawRects() [1/2]
void QPaintEngine::drawRects (const QRect * rects, int rectCount) virtual
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QPaintEngineEx, QOpenGLPaintEngine, QCoreGraphicsPaintEngine, QVGPaintEngine, QX11PaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 906 of file qpaintengine.cpp.
Referenced by QX11PaintEngine::drawRects(), QCoreGraphicsPaintEngine::drawRects(), and QPdfBaseEngine::drawRects().
 {
     struct RectF {
         qreal x;
         qreal y;
         qreal w;
         qreal h;
     };
     Q_ASSERT(sizeof(RectF) == sizeof(QRectF));
     RectF fr[256];
     while (rectCount) {
         int i = 0;
         while (i < rectCount && i < 256) {
             fr[i].x = rects[i].x();
             fr[i].y = rects[i].y();
             fr[i].w = rects[i].width();
             fr[i].h = rects[i].height();
             ++i;
         }
         drawRects((QRectF *)(void *)fr, i);
         rects += i;
         rectCount -= i;
     }
 }
drawRects() [2/2]
void QPaintEngine::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented in QPaintBufferEngine, QPdfBaseEngine, QRasterPaintEngine, QPaintEngineEx, QOpenGLPaintEngine, QVGPaintEngine, QMacPrintEngine, QX11PaintEngine, QCoreGraphicsPaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 936 of file qpaintengine.cpp.
 {
     if (hasFeature(PainterPaths) &&
         !state->penNeedsResolving() &&
         !state->brushNeedsResolving()) {
         for (int i=0; i<rectCount; ++i) {
             QPainterPath path;
             path.addRect(rects[i]);
             if (path.isEmpty())
                 continue;
             drawPath(path);
         }
     } else {
         for (int i=0; i<rectCount; ++i) {
             QRectF rf = rects[i];
             QPointF pts[4] = { QPointF(rf.x(), rf.y()),
                                QPointF(rf.x() + rf.width(), rf.y()),
                                QPointF(rf.x() + rf.width(), rf.y() + rf.height()),
                                QPointF(rf.x(), rf.y() + rf.height()) };
             drawPolygon(pts, 4, ConvexMode);
         }
     }
 }
drawTextItem()
void QPaintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented in QPaintBufferEngine, QPdfBaseEngine, QRasterPaintEngine, QSvgPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QGL2PaintEngineEx, QX11PaintEngine, QMacPrintEngine, QPicturePaintEngine, QCoreGraphicsPaintEngine, QDirectFBPaintEngine, QBlitterPaintEngine, QWin32PrintEngine, QtopiaPrintEngine, QEmulationPaintEngine, QAlphaPaintEngine, and QPreviewPaintEngine.
Definition at line 816 of file qpaintengine.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QX11PaintEngine::drawFreetype(), QEmulationPaintEngine::drawTextItem(), QWin32PrintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), QPicturePaintEngine::drawTextItem(), QGL2PaintEngineEx::drawTextItem(), QOpenGLPaintEngine::drawTextItem(), QVGPaintEngine::drawTextItem(), QRasterPaintEngine::drawTextItem(), QPdfBaseEngine::drawTextItem(), QX11PaintEngine::drawXLFD(), and QVGPaintEngine::type().
 {
     const QTextItemInt &ti = static_cast<const QTextItemInt &>(textItem);
     QPainterPath path;
 #ifndef Q_WS_MAC
     path.setFillRule(Qt::WindingFill);
 #endif
     if (ti.glyphs.numGlyphs)
         ti.fontEngine->addOutlineToPath(0, 0, ti.glyphs, &path, ti.flags);
     if (!path.isEmpty()) {
         painter()->save();
         painter()->setRenderHint(QPainter::Antialiasing,
                                  bool((painter()->renderHints() & QPainter::TextAntialiasing)
                                       && !(painter()->font().styleStrategy() & QFont::NoAntialias)));
         painter()->translate(p.x(), p.y());
         painter()->fillPath(path, state->pen().brush());
         painter()->restore();
     }
 }
drawTiledPixmap()
void QPaintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented in QPaintBufferEngine, QPaintEngineEx, QRasterPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QX11PaintEngine, QMacPrintEngine, QPicturePaintEngine, QCoreGraphicsPaintEngine, QPdfEngine, QBlitterPaintEngine, QWin32PrintEngine, QPSPrintEngine, QPreviewPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, and QAlphaPaintEngine.
Definition at line 632 of file qpaintengine.cpp.
Referenced by QWin32PrintEngine::drawTiledPixmap().
 {
     int sw = pixmap.width();
     int sh = pixmap.height();
     if (sw*sh < 8192 && sw*sh < 16*rect.width()*rect.height()) {
         int tw = sw, th = sh;
         while (tw*th < 32678 && tw < rect.width()/2)
             tw *= 2;
         while (tw*th < 32678 && th < rect.height()/2)
             th *= 2;
         QPixmap tile;
         if (pixmap.depth() == 1) {
             tile = QBitmap(tw, th);
         } else {
             tile = QPixmap(tw, th);
             if (pixmap.hasAlphaChannel())
                 tile.fill(Qt::transparent);
         }
         qt_fill_tile(&tile, pixmap);
         qt_draw_tile(this, rect.x(), rect.y(), rect.width(), rect.height(), tile, p.x(), p.y());
     } else {
         qt_draw_tile(this, rect.x(), rect.y(), rect.width(), rect.height(), pixmap, p.x(), p.y());
     }
 }
end()
bool QPaintEngine::end () pure virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implemented in QOnScreenRasterPaintEngine, QPaintBufferEngine, QPdfBaseEngine, QSvgPaintEngine, QRasterPaintEngine, QGL2PaintEngineEx, QPdfEngine, QVGPaintEngine, QX11PaintEngine, QOpenGLPaintEngine, QMacPrintEngine, QPSPrintEngine, QtopiaPrintEngine, QWin32PrintEngine, QCoreGraphicsPaintEngine, QPicturePaintEngine, QPreviewPaintEngine, QEmulationPaintEngine, QAlphaPaintEngine, QDirectFBPaintEngine, QVolatileImagePaintEngine, and QBlitterPaintEngine.
Referenced by QVGPaintEngine::type().
fix_neg_rect()
void QPaintEngine::fix_neg_rect (int * x, int * y, int * w, int * h) inline
Warning
This function is not part of the public interface.
Definition at line 332 of file qpaintengine.h.
 {
     if (*w < 0) {
         *w = -*w;
         *x -= *w - 1;
     }
     if (*h < 0) {
         *h = -*h;
         *y -= *h - 1;
     }
 }
getDC()
HDC QPaintEngine::getDC () const virtual
Empty default implementation.
Warning
This function is not part of the public interface.
Reimplemented in QRasterPaintEngine, and QWin32PrintEngine.
Definition at line 988 of file qpaintengine.cpp.
Referenced by QWindowsXPStylePrivate::drawBackground(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QVistaHelper::drawTitleBar(), XPThemeData::mask(), and QVistaBackButton::paintEvent().
 {
     return 0;
 }
hasFeature()
bool QPaintEngine::hasFeature (PaintEngineFeatures feature) const inline
Returns true if the paint engine supports the specified feature; otherwise returns false.
Definition at line 229 of file qpaintengine.h.
Referenced by QPainterPrivate::attachPainterPrivate(), QPainterPrivate::draw_helper(), QCommonStyle::drawComplexControl(), drawPath(), drawRects(), QPainterPrivate::drawStretchedGradient(), QDecorationStyled::paint(), QDecorationDefault::paint(), QDecorationDefault::paintButton(), and QPainterPrivate::updateEmulationSpecifier().
 { return (gccaps & feature) != 0; }
isActive()
bool QPaintEngine::isActive () const inline
Returns true if the paint engine is actively drawing; otherwise returns false.
See also
setActive()
Definition at line 154 of file qpaintengine.h.
Referenced by QCoreGraphicsPaintEngine::begin(), QCoreGraphicsPaintEngine::drawEllipse(), QCoreGraphicsPaintEngine::drawImage(), QCoreGraphicsPaintEngine::drawLines(), QCoreGraphicsPaintEngine::drawPath(), QCoreGraphicsPaintEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawPoints(), QCoreGraphicsPaintEngine::drawPolygon(), QCoreGraphicsPaintEngine::drawRects(), QCoreGraphicsPaintEngine::drawTiledPixmap(), QGL2PaintEngineEx::ensureActive(), QX11PaintEngine::handle(), QWin32PrintEngine::newPage(), QPdfEngine::newPage(), QGLFramebufferObject::paintEngine(), QWidget::paintEngine(), QVolatileImage::paintingActive(), QPixmapCacheEntry::QPixmapCacheEntry(), qt_x11_get_brush_gc(), qt_x11_get_pen_gc(), QWin32PrintEngine::setProperty(), setSystemRect(), QRasterPixmapData::toImage(), QGLPixmapData::toImage(), QCoreGraphicsPaintEngine::updateBrush(), QCoreGraphicsPaintEngine::updateClipPath(), QCoreGraphicsPaintEngine::updateClipRegion(), QCoreGraphicsPaintEngine::updateFont(), QCoreGraphicsPaintEngine::updateMatrix(), and QCoreGraphicsPaintEngine::updatePen().
 { return active; }
isExtended()
bool QPaintEngine::isExtended () const inline
Returns true if the paint engine is a QPaintEngineEx derivative.
Warning
This function is not part of the public interface.
Definition at line 234 of file qpaintengine.h.
Referenced by QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), QPaintEngineExReplayer::process(), QPaintBuffer::processCommands(), and syncState().
 { return extended; }
paintDevice()
QPaintDevice * QPaintEngine::paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
Definition at line 973 of file qpaintengine.cpp.
Referenced by QPainterPrivate::attachPainterPrivate(), QVGPaintEngine::clearRect(), QVGPaintEngine::clip(), QVGPaintEngine::clipEnabledChanged(), QVGPaintEngine::defaultClipRegion(), QPixmapConvolutionFilter::draw(), QBlitterPaintEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawTextItem(), QVGPaintEngine::isDefaultClipRect(), QVGPaintEngine::isDefaultClipRegion(), QVGPaintEnginePrivate::modifyMask(), QGLFramebufferObject::paintEngine(), QMacCGContext::QMacCGContext(), QWidget::render(), QRasterPixmapData::toImage(), QGLPixmapData::toImage(), QVGPaintEngine::transformChanged(), and QVGPaintEngine::updateScissor().
 {
     return d_func()->pdev;
 }
painter()
QPainter * QPaintEngine::painter () const
Returns the paint engine's painter.
Definition at line 794 of file qpaintengine.cpp.
Referenced by QPaintBufferEngine::begin(), QFontEngineBox::boundingBox(), QGL2PaintEngineEx::clipEnabledChanged(), QPaintEnginePrivate::drawBoxTextItem(), QX11PaintEngine::drawFreetype(), QEmulationPaintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), drawTextItem(), QPSPrintEngine::drawTiledPixmap(), QPaintBufferEngine::end(), QEmulationPaintEngine::fill(), QVGPaintEngine::fill(), QX11PaintEnginePrivate::fillPolygon_dev(), QAlphaPaintEngine::flushAndInit(), QPreviewPaintEngine::newPage(), QMacPrintEnginePrivate::newPage_helper(), QPaintBufferEngine::penChanged(), QPainterReplayer::process(), QPaintEngineExReplayer::process(), QPainterReplayer::processCommands(), QPainterReplayer::setupTransform(), QEmulationPaintEngine::stroke(), QPaintBufferPrivate::updateBoundingRect(), QPdfBaseEngine::updateClipPath(), QCoreGraphicsPaintEngine::updateState(), QWin32PrintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), QPicturePaintEngine::writeCmdLength(), and QVGPixmapConvolutionFilter::~QVGPixmapConvolutionFilter().
 {
     return state ? state->painter() : 0;
 }
releaseDC()
void QPaintEngine::releaseDC (HDC hdc) const virtual
Empty default implementation.
Warning
This function is not part of the public interface.
Reimplemented in QRasterPaintEngine, and QWin32PrintEngine.
Definition at line 1003 of file qpaintengine.cpp.
Referenced by XPThemeData::mask().
 {
 }
setActive()
void QPaintEngine::setActive (bool state) inline
Sets the active state of the paint engine to state.
See also
isActive()
Definition at line 155 of file qpaintengine.h.
Referenced by QPicturePaintEngine::begin(), QCoreGraphicsPaintEngine::begin(), QPSPrintEngine::begin(), QMacPrintEngine::begin(), QPdfEngine::begin(), QRasterPaintEngine::begin(), QPicturePaintEngine::end(), QCoreGraphicsPaintEngine::end(), QPSPrintEngine::end(), and QPdfEngine::end().
 { active = newState; }
setAutoDestruct()
void QPaintEngine::setAutoDestruct (bool autoDestr) inline private
Definition at line 249 of file qpaintengine.h.
Referenced by QWidget::paintEngine().
 { selfDestruct = autoDestr; }
setDirty()
void QPaintEngine::setDirty (DirtyFlags df) inline
Warning
This function is not part of the public interface.
Definition at line 349 of file qpaintengine.h.
Referenced by QCoreGraphicsPaintEngine::begin(), QX11PaintEngine::begin(), QRasterPaintEngine::begin(), QPreviewPaintEngine::newPage(), and QPainterPrivate::updateStateImpl().
{
     Q_ASSERT(state);
     state->dirtyFlags |= df;
 }
setPaintDevice()
void QPaintEngine::setPaintDevice (QPaintDevice * device)
Warning
This function is not part of the public interface. Sets the paintdevice that this engine operates on to device
Definition at line 964 of file qpaintengine.cpp.
 {
     d_func()->pdev = device;
 }
setSystemClip()
void QPaintEngine::setSystemClip (const QRegion & region)
Sets the system clip for this engine.
Warning
This function is not part of the public interface.
The system clip defines the basis area that the engine has to draw in. All clips that are set will be be an intersection with the system clip.
Reset the systemclip to no clip by setting an empty region.
Definition at line 1038 of file qpaintengine.cpp.
Referenced by QX11PaintEngine::begin(), QX11PaintEngine::end(), make_widget_eventUPP(), QSystemTrayIconSys::paintEvent(), QPainterReplayer::process(), QWidgetBackingStore::removeDirtyWidget(), and QWidgetBackingStore::showYellowThing().
 {
     Q_D(QPaintEngine);
     d->systemClip = region;
     // Be backward compatible and only call d->systemStateChanged()
     // if we currently have a system transform/viewport set.
     if (d->hasSystemTransform || d->hasSystemViewport) {
         d->transformSystemClip();
         d->systemStateChanged();
     }
 }
setSystemRect()
void QPaintEngine::setSystemRect (const QRect & rect)
Sets the target rect for drawing within the backing store.
Warning
This function is not part of the public interface.
This function should ONLY be used by the backing store.
Definition at line 1075 of file qpaintengine.cpp.
 {
     if (isActive()) {
         qWarning("QPaintEngine::setSystemRect: Should not be changed while engine is active");
         return;
     }
     d_func()->systemRect = rect;
 }
syncState()
void QPaintEngine::syncState ()
Updates all dirty states in this engine.
Warning
This function is not part of the public interface.
This function should ONLY be used when drawing with native handles directly and immediate sync from QPainters state to the native state is required.
Definition at line 335 of file qpaintengine.cpp.
Referenced by QMacStyle::drawComplexControl(), QPreviewPaintEngine::newPage(), QMacPrintEnginePrivate::newPage_helper(), and QMacCGContext::QMacCGContext().
 {
     Q_ASSERT(state);
     updateState(*state);
     if (isExtended())
         static_cast<QPaintEngineEx *>(this)->sync();
 }
systemClip()
QRegion QPaintEngine::systemClip () const
Returns the system clip.
Warning
This function is not part of the public interface.
The system clip is read only while the painter is active. An empty region indicates that system clip is not in use.
Definition at line 1061 of file qpaintengine.cpp.
Referenced by QGL2PaintEngineEx::begin(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QWidgetPrivate::drawWidget(), QDeclarativePaintedItem::paint(), QSystemTrayIconSys::paintEvent(), QPainterReplayer::process(), QMacCGContext::QMacCGContext(), QWidgetBackingStore::removeDirtyWidget(), QGL2PaintEngineExPrivate::systemStateChanged(), QX11PaintEngine::updateBrush(), QOpenGLPaintEngine::updateClipRegion(), QX11PaintEngine::updateClipRegion_dev(), QGL2PaintEngineExPrivate::updateClipScissorTest(), and QX11PaintEngine::updatePen().
 {
     return d_func()->systemClip;
 }
systemRect()
QRect QPaintEngine::systemRect () const
Retrieves the rect for drawing within the backing store.
Warning
This function is not part of the public interface.
This function should ONLY be used by the backing store.
Definition at line 1093 of file qpaintengine.cpp.
Referenced by QWidgetPrivate::drawWidget().
 {
     return d_func()->systemRect;
 }
testDirty()
bool QPaintEngine::testDirty (DirtyFlags df) inline
Warning
This function is not part of the public interface.
Definition at line 344 of file qpaintengine.h.
{
     Q_ASSERT(state);
     return ((state->dirtyFlags & df) != 0);
 }
type()
Type QPaintEngine::type () const pure virtual
Reimplement this function to return the paint engine Type.
Implemented in QPaintBufferEngine, QRasterPaintEngine, QSvgPaintEngine, QOpenGLPaintEngine, QGL2PaintEngineEx, QX11PaintEngine, QPicturePaintEngine, QCoreGraphicsPaintEngine, QPdfEngine, QWin32PrintEngine, QPSPrintEngine, QPreviewPaintEngine, QVGPaintEngine, QMacPrintEngine, QtopiaPrintEngine, QEmulationPaintEngine, and QBlitterPaintEngine.
Referenced by QGL2PaintEngineExPrivate::cleanupVectorPath(), QGLPixmapData::copy(), QDeclarativeTextLayout::draw(), QGraphicsBlurEffect::draw(), QGraphicsDropShadowEffect::draw(), drawTextItemDecoration(), qDrawBorderPixmap(), QMacCGContext::QMacCGContext(), QNativeImage::QNativeImage(), QPrinter::QPrinter(), qt_x11_get_brush_gc(), qt_x11_get_pen_gc(), QGLCustomShaderStage::removeFromPainter(), QWidgetPrivate::repaint_sys(), QGLCustomShaderStage::setOnPainter(), QNativeImage::systemFormat(), and QEmulationPaintEngine::type().
updateState()
void QPaintEngine::updateState (const QPaintEngineState & state) pure virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implemented in QPaintEngineEx, QPdfBaseEngine, QSvgPaintEngine, QOpenGLPaintEngine, QMacPrintEngine, QX11PaintEngine, QtopiaPrintEngine, QCoreGraphicsPaintEngine, QWin32PrintEngine, QPicturePaintEngine, QPreviewPaintEngine, and QAlphaPaintEngine.
Referenced by QPainterPrivate::updateStateImpl().
Friends and Related Functions
QFontEngineBox
friend class QFontEngineBox friend
Definition at line 254 of file qpaintengine.h.
QFontEngineFT
friend class QFontEngineFT friend
Definition at line 258 of file qpaintengine.h.
QFontEngineMac
friend class QFontEngineMac friend
Definition at line 255 of file qpaintengine.h.
QFontEngineQPF
friend class QFontEngineQPF friend
Definition at line 264 of file qpaintengine.h.
QFontEngineQPF1
friend class QFontEngineQPF1 friend
Definition at line 261 of file qpaintengine.h.
QFontEngineWin
friend class QFontEngineWin friend
Definition at line 256 of file qpaintengine.h.
QMacCGContext
friend class QMacCGContext friend
Definition at line 283 of file qpaintengine.h.
QMacPrintEngine
friend class QMacPrintEngine friend
Definition at line 267 of file qpaintengine.h.
QMacPrintEnginePrivate
friend class QMacPrintEnginePrivate friend
Definition at line 268 of file qpaintengine.h.
QPainter
friend class QPainter friend
Definition at line 277 of file qpaintengine.h.
Referenced by QPreviewPaintEngine::begin(), QAlphaPaintEngine::flushAndInit(), and QPreviewPaintEngine::newPage().
QPainterPrivate
friend class QPainterPrivate friend
Definition at line 278 of file qpaintengine.h.
QPainterReplayer
friend class QPainterReplayer friend
Definition at line 253 of file qpaintengine.h.
QPreviewPaintEngine
friend class QPreviewPaintEngine friend
Definition at line 284 of file qpaintengine.h.
QProxyFontEngine
friend class QProxyFontEngine friend
Definition at line 272 of file qpaintengine.h.
QPSPrintEngine
friend class QPSPrintEngine friend
Definition at line 266 of file qpaintengine.h.
QtopiaPrintEngine
friend class QtopiaPrintEngine friend
Definition at line 270 of file qpaintengine.h.
QtopiaPrintEnginePrivate
friend class QtopiaPrintEnginePrivate friend
Definition at line 271 of file qpaintengine.h.
QWidget
friend class QWidget friend
Definition at line 279 of file qpaintengine.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 280 of file qpaintengine.h.
QWin32PaintEngine
friend class QWin32PaintEngine friend
Definition at line 281 of file qpaintengine.h.
QWin32PaintEnginePrivate
friend class QWin32PaintEnginePrivate friend
Definition at line 282 of file qpaintengine.h.
QX11GLPixmapData
friend class QX11GLPixmapData friend
Definition at line 285 of file qpaintengine.h.
Properties
active
uint QPaintEngine::active protected
Definition at line 242 of file qpaintengine.h.
d_ptr
QScopedPointer<QPaintEnginePrivate> QPaintEngine::d_ptr protected
Definition at line 246 of file qpaintengine.h.
Referenced by QPaintBuffer::beginNewFrame(), QPicture::data_ptr(), QPaintBuffer::numFrames(), QPainterReplayer::process(), and QPaintEngine().
extended
uint QPaintEngine::extended protected
Definition at line 244 of file qpaintengine.h.
Referenced by QPaintEngineEx::QPaintEngineEx().
gccaps
PaintEngineFeatures QPaintEngine::gccaps protected
Definition at line 240 of file qpaintengine.h.
Referenced by QDirectFBPaintEngine::begin(), QAlphaPaintEngine::begin(), QAlphaPaintEngine::flushAndInit(), QRasterPaintEngine::init(), QMacPrintEnginePrivate::initialize(), and QCoreGraphicsPaintEngine::updateBrush().
selfDestruct
uint QPaintEngine::selfDestruct protected
Definition at line 243 of file qpaintengine.h.
state
QPaintEngineState* QPaintEngine::state protected
Definition at line 239 of file qpaintengine.h.
Referenced by QtopiaPrintEngine::begin(), QMacPrintEngine::begin(), QProxyFontEngine::canRender(), QWin32PrintEnginePrivate::doReinit(), QFontEngineQPF::draw(), QFontEngineQPF1::draw(), QCoreGraphicsPaintEngine::drawEllipse(), QCoreGraphicsPaintEngine::drawImage(), QCoreGraphicsPaintEngine::drawLines(), drawLines(), QCoreGraphicsPaintEngine::drawPath(), QCoreGraphicsPaintEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawPoints(), QCoreGraphicsPaintEngine::drawPolygon(), QCoreGraphicsPaintEngine::drawRects(), drawRects(), QWin32PrintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), drawTextItem(), QCoreGraphicsPaintEngine::drawTiledPixmap(), QMacPrintEnginePrivate::initialize(), QPreviewPaintEngine::newPage(), QMacPrintEnginePrivate::newPage_helper(), painter(), QEmulationPaintEngine::QEmulationPaintEngine(), QEmulationPaintEngine::setState(), QPaintEngineEx::setState(), QEmulationPaintEngine::state(), QPaintEngineEx::state(), syncState(), QtopiaPrintEngine::type(), QMacPrintEngine::type(), QPainterPrivate::updateState(), and QPainterPrivate::updateStateImpl().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine.h
/src/gui/painting/qpaintengine.cpp