Qt 4.8: QmlJSDebugger::LiveSelectionIndicator Class Reference
QmlJSDebugger::LiveSelectionIndicator Class Reference
#include <liveselectionindicator.h>
Public Functions
void clear ()
void hide ()
LiveSelectionIndicator (QDeclarativeViewInspector *viewInspector, QGraphicsObject *layerItem)
void setItems (const QList< QWeakPointer< QGraphicsObject > > &itemList)
void show ()
~LiveSelectionIndicator ()
Properties
QHash< QGraphicsItem *, QGraphicsRectItem * > m_indicatorShapeHash
QWeakPointer< QGraphicsObject > m_layerItem
QDeclarativeViewInspector * m_view
Detailed Description
Definition at line 59 of file liveselectionindicator.h.
Constructors and Destructors
LiveSelectionIndicator()
QmlJSDebugger::LiveSelectionIndicator::LiveSelectionIndicator (QDeclarativeViewInspector * viewInspector, QGraphicsObject * layerItem)
Definition at line 54 of file liveselectionindicator.cpp.
     : m_layerItem(layerItem)
     , m_view(viewInspector)
 {
 }
~LiveSelectionIndicator()
QmlJSDebugger::LiveSelectionIndicator::~LiveSelectionIndicator ()
Definition at line 61 of file liveselectionindicator.cpp.
 {
     clear();
 }
Functions
clear()
void QmlJSDebugger::LiveSelectionIndicator::clear (void)
Definition at line 78 of file liveselectionindicator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::clear(), setItems(), and ~LiveSelectionIndicator().
 {
     if (!m_layerItem.isNull()) {
         QGraphicsScene *scene = m_layerItem.data()->scene();
         foreach (QGraphicsRectItem *item, m_indicatorShapeHash) {
             scene->removeItem(item);
             delete item;
         }
     }
     m_indicatorShapeHash.clear();
 }
hide()
void QmlJSDebugger::LiveSelectionIndicator::hide ()
Definition at line 72 of file liveselectionindicator.cpp.
 {
     foreach (QGraphicsRectItem *item, m_indicatorShapeHash)
         item->hide();
 }
setItems()
void QmlJSDebugger::LiveSelectionIndicator::setItems (const QList< QWeakPointer< QGraphicsObject > > & itemList)
Definition at line 92 of file liveselectionindicator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::repaintBoundingRects(), and QmlJSDebugger::LiveSelectionTool::selectedItemsChanged().
 {
     clear();
     foreach (const QWeakPointer<QGraphicsObject> &object, itemList) {
         if (object.isNull())
             continue;
         QGraphicsItem *item = object.data();
         if (!m_indicatorShapeHash.contains(item)) {
             QGraphicsRectItem *selectionIndicator = new QGraphicsRectItem(m_layerItem.data());
             m_indicatorShapeHash.insert(item, selectionIndicator);
             const QRectF boundingRect = m_view->adjustToScreenBoundaries(item->mapRectToScene(item->boundingRect()));
             const QRectF boundingRectInLayerItemSpace = m_layerItem.data()->mapRectFromScene(boundingRect);
             selectionIndicator->setData(Constants::EditorItemDataKey, true);
             selectionIndicator->setFlag(QGraphicsItem::ItemIsSelectable, false);
             selectionIndicator->setRect(boundingRectInLayerItemSpace);
             selectionIndicator->setPen(QColor(108, 141, 221));
         }
     }
 }
show()
void QmlJSDebugger::LiveSelectionIndicator::show ()
Definition at line 66 of file liveselectionindicator.cpp.
 {
     foreach (QGraphicsRectItem *item, m_indicatorShapeHash)
         item->show();
 }
Properties
m_indicatorShapeHash
QHash<QGraphicsItem*, QGraphicsRectItem *> QmlJSDebugger::LiveSelectionIndicator::m_indicatorShapeHash private
Definition at line 73 of file liveselectionindicator.h.
Referenced by clear(), hide(), setItems(), and show().
m_layerItem
QWeakPointer<QGraphicsObject> QmlJSDebugger::LiveSelectionIndicator::m_layerItem private
Definition at line 74 of file liveselectionindicator.h.
Referenced by clear(), and setItems().
m_view
QDeclarativeViewInspector* QmlJSDebugger::LiveSelectionIndicator::m_view private
Definition at line 75 of file liveselectionindicator.h.
Referenced by setItems().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/liveselectionindicator.h
/src/plugins/qmltooling/qmldbg_inspector/editor/liveselectionindicator.cpp