Qt 4.8: QGraphicsLinearLayout Class Reference
QGraphicsLinearLayout Class Reference
The QGraphicsLinearLayout class provides a horizontal or vertical layout for managing widgets in Graphics View.
#include <qgraphicslinearlayout.h>
Public Functions
void addItem (QGraphicsLayoutItem *item)
This convenience function is equivalent to calling insertItem(-1, item).
void addStretch (int stretch=1)
This convenience function is equivalent to calling insertStretch(-1, stretch).
Qt::Alignment alignment (QGraphicsLayoutItem *item) const
Returns the alignment for item.
int count () const
Reimplemented Function
void dump (int indent=0) const
void insertItem (int index, QGraphicsLayoutItem *item)
Inserts item into the layout at index, or before any item that is currently at index.
void insertStretch (int index, int stretch=1)
Inserts a stretch of stretch at index, or before any item that is currently at index.
void invalidate ()
Reimplemented Function
QGraphicsLayoutItem * itemAt (int index) const
When iterating from 0 and up, it will return the items in the visual arranged order.
qreal itemSpacing (int index) const
Returns the spacing after item at index.
Qt::Orientation orientation () const
Returns the layout orientation.
QGraphicsLinearLayout (QGraphicsLayoutItem *parent=0)
Constructs a QGraphicsLinearLayout instance using Qt::Horizontal orientation.
QGraphicsLinearLayout (Qt::Orientation orientation, QGraphicsLayoutItem *parent=0)
Constructs a QGraphicsLinearLayout instance.
void removeAt (int index)
Removes the item at index without destroying it.
void removeItem (QGraphicsLayoutItem *item)
Removes item from the layout without destroying it.
void setAlignment (QGraphicsLayoutItem *item, Qt::Alignment alignment)
Sets the alignment of item to alignment.
void setGeometry (const QRectF &rect)
Reimplemented Function
void setItemSpacing (int index, qreal spacing)
Sets the spacing after item at index to spacing.
void setOrientation (Qt::Orientation orientation)
Change the layout orientation to orientation.
void setSpacing (qreal spacing)
Sets the layout's spacing to spacing.
void setStretchFactor (QGraphicsLayoutItem *item, int stretch)
Sets the stretch factor for item to stretch.
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Reimplemented Function
qreal spacing () const
Returns the layout's spacing.
int stretchFactor (QGraphicsLayoutItem *item) const
Returns the stretch factor for item.
virtual ~QGraphicsLinearLayout ()
Destroys the QGraphicsLinearLayout object.
Public Functions inherited from QGraphicsLayout
void activate ()
Activates the layout, causing all items in the layout to be immediately rearranged.
void getContentsMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Reimplemented Function
bool isActivated () const
Returns true if the layout is currently being activated; otherwise, returns false.
QGraphicsLayout (QGraphicsLayoutItem *parent=0)
Contructs a QGraphicsLayout object.
void setContentsMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the contents margins to left, top, right and bottom.
virtual void updateGeometry ()
Reimplemented Function
virtual void widgetEvent (QEvent *e)
This virtual event handler receives all events for the managed widget.
~QGraphicsLayout ()
Destroys the QGraphicsLayout object.
Public Functions inherited from QGraphicsLayoutItem
QRectF contentsRect () const
Returns the contents rect in local coordinates.
QSizeF effectiveSizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
QRectF geometry () const
Returns the item's geometry (e.
QGraphicsItem * graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
bool isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
qreal maximumHeight () const
Returns the maximum height.
QSizeF maximumSize () const
Returns the maximum size.
qreal maximumWidth () const
Returns the maximum width.
qreal minimumHeight () const
Returns the minimum height.
QSizeF minimumSize () const
Returns the minimum size.
qreal minimumWidth () const
Returns the minimum width.
bool ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
QGraphicsLayoutItem * parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
qreal preferredHeight () const
Returns the preferred height.
QSizeF preferredSize () const
Returns the preferred size.
qreal preferredWidth () const
Returns the preferred width.
QGraphicsLayoutItem (QGraphicsLayoutItem *parent=0, bool isLayout=false)
Constructs the QGraphicsLayoutItem object.
void setMaximumHeight (qreal height)
Sets the maximum height to height.
void setMaximumSize (const QSizeF &size)
Sets the maximum size to size.
void setMaximumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
void setMaximumWidth (qreal width)
Sets the maximum width to width.
void setMinimumHeight (qreal height)
Sets the minimum height to height.
void setMinimumSize (const QSizeF &size)
Sets the minimum size to size.
void setMinimumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
void setMinimumWidth (qreal width)
Sets the minimum width to width.
void setParentLayoutItem (QGraphicsLayoutItem *parent)
Sets the parent of this QGraphicsLayoutItem to parent.
void setPreferredHeight (qreal height)
Sets the preferred height to height.
void setPreferredSize (const QSizeF &size)
Sets the preferred size to size.
void setPreferredSize (qreal w, qreal h)
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
void setPreferredWidth (qreal width)
Sets the preferred width to width.
void setSizePolicy (const QSizePolicy &policy)
Sets the size policy to policy.
void setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType=QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
QSizePolicy sizePolicy () const
Returns the current size policy.
virtual ~QGraphicsLayoutItem ()
Destroys the QGraphicsLayoutItem object.
Additional Inherited Members
Static Public Functions inherited from QGraphicsLayout
static bool instantInvalidatePropagation ()
static void setInstantInvalidatePropagation (bool enable)
Protected Functions inherited from QGraphicsLayout
void addChildLayoutItem (QGraphicsLayoutItem *layoutItem)
This function is a convenience function provided for custom layouts, and will go through all items in the layout and reparent their graphics items to the closest QGraphicsWidget ancestor of the layout.
QGraphicsLayout (QGraphicsLayoutPrivate &, QGraphicsLayoutItem *)
Protected Functions inherited from QGraphicsLayoutItem
QGraphicsLayoutItem (QGraphicsLayoutItemPrivate &dd)
void setGraphicsItem (QGraphicsItem *item)
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
void setOwnedByLayout (bool ownedByLayout)
Sets whether a layout should delete this item in its destructor or not.
Protected Variables inherited from QGraphicsLayoutItem
QScopedPointer< QGraphicsLayoutItemPrivate > d_ptr
Detailed Description
The QGraphicsLinearLayout class provides a horizontal or vertical layout for managing widgets in Graphics View.
Since
4.4
The default orientation for a linear layout is Qt::Horizontal. You can choose a vertical orientation either by calling setOrientation(), or by passing Qt::Vertical to QGraphicsLinearLayout's constructor.
The most common way to use QGraphicsLinearLayout is to construct an object on the heap with no parent, add widgets and layouts by calling addItem(), and finally assign the layout to a widget by calling QGraphicsWidget::setLayout().
QGraphicsScene scene;
QGraphicsWidget *textEdit = scene.addWidget(new QTextEdit);
QGraphicsWidget *pushButton = scene.addWidget(new QPushButton);
QGraphicsLinearLayout *layout = new QGraphicsLinearLayout;
layout->addItem(textEdit);
layout->addItem(pushButton);
QGraphicsWidget *form = new QGraphicsWidget;
form->setLayout(layout);
scene.addItem(form);
You can add widgets, layouts, stretches (addStretch(), insertStretch() or setStretchFactor()), and spacings (setItemSpacing()) to a linear layout. The layout takes ownership of the items. In some cases when the layout item also inherits from QGraphicsItem (such as QGraphicsWidget) there will be a ambiguity in ownership because the layout item belongs to two ownership hierarchies. See the documentation of QGraphicsLayoutItem::setOwnedByLayout() how to handle this. You can access each item in the layout by calling count() and itemAt(). Calling removeAt() or removeItem() will remove an item from the layout, without destroying it.
Size Hints and Size Policies in QGraphicsLinearLayout
QGraphicsLinearLayout respects each item's size hints and size policies, and when the layout contains more space than the items can fill, each item is arranged according to the layout's alignment for that item. You can set an alignment for each item by calling setAlignment(), and check the alignment for any item by calling alignment(). By default, items are aligned to the top left.
Spacing within QGraphicsLinearLayout
Between the items, the layout distributes some space. The actual amount of space depends on the managed widget's current style, but the common spacing is 4. You can also set your own spacing by calling setSpacing(), and get the current spacing value by calling spacing(). If you want to configure individual spacing for your items, you can call setItemSpacing().
Stretch Factor in QGraphicsLinearLayout
You can assign a stretch factor to each item to control how much space it will get compared to the other items. By default, two identical widgets arranged in a linear layout will have the same size, but if the first widget has a stretch factor of 1 and the second widget has a stretch factor of 2, the first widget will get 1/3 of the available space, and the second will get 2/3.
QGraphicsLinearLayout calculates the distribution of sizes by adding up the stretch factors of all items, and then dividing the available space accordingly. The default stretch factor is 0 for all items; a factor of 0 means the item does not have any defined stretch factor; effectively this is the same as setting the stretch factor to 1. The stretch factor only applies to the available space in the lengthwise direction of the layout (following its orientation). If you want to control both the item's horizontal and vertical stretch, you can use QGraphicsGridLayout instead.
QGraphicsLinearLayout Compared to Other Layouts
QGraphicsLinearLayout is very similar to QVBoxLayout and QHBoxLayout, but in contrast to these classes, it is used to manage QGraphicsWidget and QGraphicsLayout instead of QWidget and QLayout.
See also
QGraphicsGridLayout, QGraphicsWidget
Definition at line 58 of file qgraphicslinearlayout.h.
Constructors and Destructors
QGraphicsLinearLayout() [1/2]
QGraphicsLinearLayout::QGraphicsLinearLayout (QGraphicsLayoutItem * parent = 0)
Constructs a QGraphicsLinearLayout instance using Qt::Horizontal orientation.
parent is passed to QGraphicsLayout's constructor.
Definition at line 200 of file qgraphicslinearlayout.cpp.
     : QGraphicsLayout(*new QGraphicsLinearLayoutPrivate(Qt::Horizontal), parent)
 {
 }
QGraphicsLinearLayout() [2/2]
QGraphicsLinearLayout::QGraphicsLinearLayout (Qt::Orientation orientation, QGraphicsLayoutItem * parent = 0)
Constructs a QGraphicsLinearLayout instance.
You can pass the orientation for the layout, either horizontal or vertical, and parent is passed to QGraphicsLayout's constructor.
Definition at line 191 of file qgraphicslinearlayout.cpp.
     : QGraphicsLayout(*new QGraphicsLinearLayoutPrivate(orientation), parent)
 {
 }
~QGraphicsLinearLayout()
QGraphicsLinearLayout::~QGraphicsLinearLayout () virtual
Destroys the QGraphicsLinearLayout object.
Definition at line 208 of file qgraphicslinearlayout.cpp.
 {
     for (int i = count() - 1; i >= 0; --i) {
         QGraphicsLayoutItem *item = itemAt(i);
         // The following lines can be removed, but this removes the item
         // from the layout more efficiently than the implementation of
         // ~QGraphicsLayoutItem.
         removeAt(i);
         if (item) {
             item->setParentLayoutItem(0);
             if (item->ownedByLayout())
                 delete item;
         }
     }
 }
Functions
addItem()
void QGraphicsLinearLayout::addItem (QGraphicsLayoutItem * item) inline
This convenience function is equivalent to calling insertItem(-1, item).
Definition at line 68 of file qgraphicslinearlayout.h.
 { insertItem(-1, item); }
addStretch()
void QGraphicsLinearLayout::addStretch (int stretch = 1) inline
This convenience function is equivalent to calling insertStretch(-1, stretch).
Definition at line 69 of file qgraphicslinearlayout.h.
 { insertStretch(-1, stretch); }
alignment()
Qt::Alignment QGraphicsLinearLayout::alignment (QGraphicsLayoutItem * item) const
Returns the alignment for item.
The default alignment is Qt::AlignTop | Qt::AlignLeft.
The alignment decides how the item is positioned within its assigned space in the case where there's more space available in the layout than the widgets can occupy.
See also
setAlignment()
Definition at line 459 of file qgraphicslinearlayout.cpp.
Referenced by setAlignment().
 {
     Q_D(const QGraphicsLinearLayout);
     return d->engine.alignment(item);
 }
count()
int QGraphicsLinearLayout::count () const virtual
Reimplemented Function
Implements QGraphicsLayout.
Definition at line 475 of file qgraphicslinearlayout.cpp.
Referenced by ~QGraphicsLinearLayout().
 {
     Q_D(const QGraphicsLinearLayout);
     return d->engine.itemCount();
 }
dump()
void QGraphicsLinearLayout::dump (int indent = 0) const
Warning
This function is not part of the public interface.
Definition at line 557 of file qgraphicslinearlayout.cpp.
Referenced by setGeometry().
 {
 #ifdef QT_DEBUG
     if (qt_graphicsLayoutDebug()) {
         Q_D(const QGraphicsLinearLayout);
         qDebug("%*s%s layout", indent, "",
                d->orientation == Qt::Horizontal ? "Horizontal" : "Vertical");
         d->engine.dump(indent + 1);
     }
 #else
     Q_UNUSED(indent);
 #endif
 }
insertItem()
void QGraphicsLinearLayout::insertItem (int index, QGraphicsLayoutItem * item)
Inserts item into the layout at index, or before any item that is currently at index.
See also
addItem(), itemAt(), insertStretch(), setItemSpacing()
Definition at line 273 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     if (!item) {
         qWarning("QGraphicsLinearLayout::insertItem: cannot insert null item");
         return;
     }
     if (item == this) {
         qWarning("QGraphicsLinearLayout::insertItem: cannot insert itself");
         return;
     }
     d->addChildLayoutItem(item);
     Q_ASSERT(item);
     d->fixIndex(&index);
     d->engine.insertRow(index, d->orientation);
     new QGridLayoutItem(&d->engine, item, d->gridRow(index), d->gridColumn(index), 1, 1, 0, index);
     invalidate();
 }
insertStretch()
void QGraphicsLinearLayout::insertStretch (int index, int stretch = 1)
Inserts a stretch of stretch at index, or before any item that is currently at index.
See also
addStretch(), setStretchFactor(), setItemSpacing(), insertItem()
Definition at line 299 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     d->fixIndex(&index);
     d->engine.insertRow(index, d->orientation);
     d->engine.setRowStretchFactor(index, stretch, d->orientation);
     invalidate();
 }
invalidate()
void QGraphicsLinearLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QGraphicsLayout.
Definition at line 547 of file qgraphicslinearlayout.cpp.
Referenced by insertItem(), insertStretch(), removeAt(), removeItem(), setAlignment(), setItemSpacing(), setOrientation(), setSpacing(), and setStretchFactor().
 {
     Q_D(QGraphicsLinearLayout);
     d->engine.invalidate();
     QGraphicsLayout::invalidate();
 }
itemAt()
QGraphicsLayoutItem * QGraphicsLinearLayout::itemAt (int index) const virtual
When iterating from 0 and up, it will return the items in the visual arranged order.
Reimplemented Function
Implements QGraphicsLayout.
Definition at line 488 of file qgraphicslinearlayout.cpp.
Referenced by ~QGraphicsLinearLayout().
 {
     Q_D(const QGraphicsLinearLayout);
     if (index < 0 || index >= d->engine.itemCount()) {
         qWarning("QGraphicsLinearLayout::itemAt: invalid index %d", index);
         return 0;
     }
     QGraphicsLayoutItem *item = 0;
     if (QGridLayoutItem *gridItem = d->engine.itemAt(index))
         item = gridItem->layoutItem();
     return item;
 }
itemSpacing()
qreal QGraphicsLinearLayout::itemSpacing (int index) const
Returns the spacing after item at index.
Definition at line 388 of file qgraphicslinearlayout.cpp.
 {
     Q_D(const QGraphicsLinearLayout);
     return d->engine.rowSpacing(index, d->orientation);
 }
orientation()
Qt::Orientation QGraphicsLinearLayout::orientation () const
Returns the layout orientation.
See also
setOrientation()
Definition at line 244 of file qgraphicslinearlayout.cpp.
Referenced by setOrientation().
 {
     Q_D(const QGraphicsLinearLayout);
     return d->orientation;
 }
removeAt()
void QGraphicsLinearLayout::removeAt (int index) virtual
Removes the item at index without destroying it.
Ownership of the item is transferred to the caller.
See also
removeItem(), insertItem()
Implements QGraphicsLayout.
Definition at line 331 of file qgraphicslinearlayout.cpp.
Referenced by ~QGraphicsLinearLayout().
 {
     Q_D(QGraphicsLinearLayout);
     if (index < 0 || index >= d->engine.itemCount()) {
         qWarning("QGraphicsLinearLayout::removeAt: invalid index %d", index);
         return;
     }
     if (QGridLayoutItem *gridItem = d->engine.itemAt(index)) {
         if (QGraphicsLayoutItem *layoutItem = gridItem->layoutItem())
             layoutItem->setParentLayoutItem(0);
         d->removeGridItem(gridItem);
         delete gridItem;
         invalidate();
     }
 }
removeItem()
void QGraphicsLinearLayout::removeItem (QGraphicsLayoutItem * item)
Removes item from the layout without destroying it.
Ownership of item is transferred to the caller.
See also
removeAt(), insertItem()
Definition at line 314 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     if (QGridLayoutItem *gridItem = d->engine.findLayoutItem(item)) {
         item->setParentLayoutItem(0);
         d->removeGridItem(gridItem);
         delete gridItem;
         invalidate();
     }
 }
setAlignment()
void QGraphicsLinearLayout::setAlignment (QGraphicsLayoutItem * item, Qt::Alignment alignment)
Sets the alignment of item to alignment.
If item's alignment changes, the layout is automatically invalidated.
See also
alignment(), invalidate()
Definition at line 440 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     if (this->alignment(item) == alignment)
         return;
     d->engine.setAlignment(item, alignment);
     invalidate();
 }
setGeometry()
void QGraphicsLinearLayout::setGeometry (const QRectF & rect) virtual
Reimplemented Function
Reimplemented from QGraphicsLayoutItem.
Definition at line 504 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     QGraphicsLayout::setGeometry(rect);
     QRectF effectiveRect = geometry();
     qreal left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     Qt::LayoutDirection visualDir = d->visualDirection();
     d->engine.setVisualDirection(visualDir);
     if (visualDir == Qt::RightToLeft)
         qSwap(left, right);
     effectiveRect.adjust(+left, +top, -right, -bottom);
 #ifdef QT_DEBUG
     if (qt_graphicsLayoutDebug()) {
         static int counter = 0;
         qDebug() << counter++ << "QGraphicsLinearLayout::setGeometry - " << rect;
         dump(1);
     }
 #endif
     d->engine.setGeometries(d->styleInfo(), effectiveRect);
 #ifdef QT_DEBUG
     if (qt_graphicsLayoutDebug()) {
         qDebug() << "post dump";
         dump(1);
     }
 #endif
 }
setItemSpacing()
void QGraphicsLinearLayout::setItemSpacing (int index, qreal spacing)
Sets the spacing after item at index to spacing.
Definition at line 379 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     d->engine.setRowSpacing(index, spacing, d->orientation);
     invalidate();
 }
setOrientation()
void QGraphicsLinearLayout::setOrientation (Qt::Orientation orientation)
Change the layout orientation to orientation.
Changing the layout orientation will automatically invalidate the layout.
See also
orientation()
Definition at line 230 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     if (orientation != d->orientation) {
         d->engine.transpose();
         d->orientation = orientation;
         invalidate();
     }
 }
setSpacing()
void QGraphicsLinearLayout::setSpacing (qreal spacing)
Sets the layout's spacing to spacing.
Spacing refers to the vertical and horizontal distances between items.
See also
setItemSpacing(), setStretchFactor(), QGraphicsGridLayout::setSpacing()
Definition at line 353 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     if (spacing < 0) {
         qWarning("QGraphicsLinearLayout::setSpacing: invalid spacing %g", spacing);
         return;
     }
     d->engine.setSpacing(spacing, Qt::Horizontal | Qt::Vertical);
     invalidate();
 }
setStretchFactor()
void QGraphicsLinearLayout::setStretchFactor (QGraphicsLayoutItem * item, int stretch)
Sets the stretch factor for item to stretch.
If an item's stretch factor changes, this function will invalidate the layout.
Setting stretch to 0 removes the stretch factor from the item, and is effectively equivalent to setting stretch to 1.
See also
stretchFactor()
Definition at line 403 of file qgraphicslinearlayout.cpp.
 {
     Q_D(QGraphicsLinearLayout);
     if (!item) {
         qWarning("QGraphicsLinearLayout::setStretchFactor: cannot assign"
                  " a stretch factor to a null item");
         return;
     }
     if (stretchFactor(item) == stretch)
         return;
     d->engine.setStretchFactor(item, stretch, d->orientation);
     invalidate();
 }
sizeHint()
QSizeF QGraphicsLinearLayout::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const virtual
Reimplemented Function
Implements QGraphicsLayoutItem.
Definition at line 535 of file qgraphicslinearlayout.cpp.
 {
     Q_D(const QGraphicsLinearLayout);
     qreal left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     const QSizeF extraMargins(left + right, top + bottom);
     return d->engine.sizeHint(d->styleInfo(), which , constraint - extraMargins) + extraMargins;
 }
spacing()
qreal QGraphicsLinearLayout::spacing () const
Returns the layout's spacing.
Spacing refers to the vertical and horizontal distances between items.
See also
setSpacing()
Definition at line 370 of file qgraphicslinearlayout.cpp.
 {
     Q_D(const QGraphicsLinearLayout);
     return d->engine.spacing(d->styleInfo(), d->orientation);
 }
stretchFactor()
int QGraphicsLinearLayout::stretchFactor (QGraphicsLayoutItem * item) const
Returns the stretch factor for item.
The default stretch factor is 0, meaning that the item has no assigned stretch factor.
See also
setStretchFactor()
Definition at line 423 of file qgraphicslinearlayout.cpp.
Referenced by setStretchFactor().
 {
     Q_D(const QGraphicsLinearLayout);
     if (!item) {
         qWarning("QGraphicsLinearLayout::setStretchFactor: cannot return"
                  " a stretch factor for a null item");
         return 0;
     }
     return d->engine.stretchFactor(item, d->orientation);
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicslinearlayout.h
/src/gui/graphicsview/qgraphicslinearlayout.cpp