Qt 4.8: QPolygonF Class Reference
QPolygonF Class Reference
The QPolygonF class provides a vector of points using floating point precision.
#include <qpolygon.h>
Public Functions
QRectF boundingRect () const
Returns the bounding rectangle of the polygon, or QRectF(0,0,0,0) if the polygon is empty.
bool containsPoint (const QPointF &pt, Qt::FillRule fillRule) const
Returns true if the given point is inside the polygon according to the specified fillRule; otherwise returns false.
QPolygonF intersected (const QPolygonF &r) const
Returns a polygon which is the intersection of this polygon and r.
bool isClosed () const
Returns true if the polygon is closed; otherwise returns false.
QPolygonF ()
Constructs a polygon with no points.
QPolygonF (int size)
Constructs a polygon of the given size.
QPolygonF (const QPolygonF &a)
Constructs a copy of the given polygon.
QPolygonF (const QVector< QPointF > &v)
Constructs a polygon containing the specified points.
QPolygonF (const QRectF &r)
Constructs a closed polygon from the specified rectangle.
QPolygonF (const QPolygon &a)
Constructs a float based polygon from the specified integer based polygon.
QPolygonF subtracted (const QPolygonF &r) const
Returns a polygon which is r subtracted from this polygon.
void swap (QPolygonF &other)
Swaps polygon other with this polygon.
QPolygon toPolygon () const
Creates and returns a QPolygon by converting each QPointF to a QPoint.
void translate (qreal dx, qreal dy)
Translates all points in the polygon by ({dx}, {dy}).
void translate (const QPointF &offset)
Translate all points in the polygon by the given offset.
QPolygonF translated (qreal dx, qreal dy) const
Returns a copy of the polygon that is translated by ({dx}, {dy}).
QPolygonF translated (const QPointF &offset) const
Returns a copy of the polygon that is translated by the given offset.
QPolygonF united (const QPolygonF &r) const
Returns a polygon which is the union of this polygon and r.
~QPolygonF ()
Destroys the polygon.
Public Functions inherited from QVector< QPointF >
void append (const QPointF &t)
Inserts value at the end of the vector.
const QPointF & at (int i) const
Returns the item at index position i in the vector.
reference back ()
This function is provided for STL compatibility.
const_reference back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the vector.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int capacity () const
Returns the maximum number of items that can be stored in the vector without forcing a reallocation.
void clear ()
Removes all the elements from the vector and releases the memory used by the vector.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the vector.
const QPointF * constData () const
Returns a const pointer to the data stored in the vector.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the vector.
bool contains (const QPointF &t) const
Returns true if the vector contains an occurrence of value; otherwise returns false.
int count (const QPointF &t) const
Returns the number of occurrences of value in the vector.
int count () const
Same as size().
QPointF * data ()
Returns a pointer to the data stored in the vector.
const QPointF * data () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void detach ()
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the vector.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const QPointF &t) const
Returns true if this vector is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator begin, iterator end)
Removes all the items from begin up to (but not including) end.
iterator erase (iterator pos)
Removes the item pointed to by the iterator pos from the vector, and returns an iterator to the next item in the vector (which may be end()).
QVector< QPointF > & fill (const QPointF &t, int size=-1)
Assigns value to all items in the vector.
QPointF & first ()
Returns a reference to the first item in the vector.
const QPointF & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QPointF & front ()
This function is provided for STL compatibility.
const_reference front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const QPointF &t, int from=0) const
Returns the index position of the first occurrence of value in the vector, searching forward from index position from.
void insert (int i, const QPointF &t)
Inserts value at index position i in the vector.
void insert (int i, int n, const QPointF &t)
Inserts count copies of value at index position i in the vector.
iterator insert (iterator before, int n, const QPointF &x)
Inserts count copies of value in front of the item pointed to by the iterator before.
iterator insert (iterator before, const QPointF &x)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the vector has size 0; otherwise returns false.
bool isSharedWith (const QVector< QPointF > &other) const
QPointF & last ()
Returns a reference to the last item in the vector.
const QPointF & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const QPointF &t, int from=-1) const
Returns the index position of the last occurrence of the value value in the vector, searching backward from index position from.
QVector< QPointF > mid (int pos, int length=-1) const
Returns a vector whose elements are copied from this vector, starting at position pos.
bool operator!= (const QVector< QPointF > &v) const
Returns true if other is not equal to this vector; otherwise returns false.
QVector< QPointF > operator+ (const QVector< QPointF > &l) const
Returns a vector that contains all the items in this vector followed by all the items in the other vector.
QVector< QPointF > & operator+= (const QVector< QPointF > &l)
Appends the items of the other vector to this vector and returns a reference to this vector.
QVector< QPointF > & operator+= (const QPointF &t)
Appends value to the vector.
QVector< QPointF > & operator<< (const QVector< QPointF > &l)
Appends other to the vector and returns a reference to the vector.
QVector< QPointF > & operator<< (const QPointF &t)
Appends value to the vector and returns a reference to this vector.
QVector< QPointF > & operator= (const QVector< QPointF > &v)
Assigns other to this vector and returns a reference to this vector.
bool operator== (const QVector< QPointF > &v) const
Returns true if other is equal to this vector; otherwise returns false.
QPointF & operator[] (int i)
Returns the item at index position i as a modifiable reference.
const QPointF & operator[] (int i) const
Same as at(i).
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const QPointF &t)
Inserts value at the beginning of the vector.
void push_back (const QPointF &t)
This function is provided for STL compatibility.
void push_front (const QPointF &t)
This function is provided for STL compatibility.
QVector ()
Constructs an empty vector.
QVector (int size)
Constructs a vector with an initial size of size elements.
QVector (int size, const QPointF &t)
Constructs a vector with an initial size of size elements.
QVector (const QVector< QPointF > &v)
Constructs a copy of other.
void remove (int i)
Removes the element at index position i.
void remove (int i, int n)
Removes count elements from the middle of the vector, starting at index position i.
void replace (int i, const QPointF &t)
Replaces the item at index position i with value.
void reserve (int size)
Attempts to allocate memory for at least size elements.
void resize (int size)
Sets the size of the vector to size.
void setSharable (bool sharable)
int size () const
Returns the number of items in the vector.
void squeeze ()
Releases any memory not required to store the items.
bool startsWith (const QPointF &t) const
Returns true if this vector is not empty and its first item is equal to value; otherwise returns false.
void swap (QVector< QPointF > &other)
Swaps vector other with this vector.
QList< QPointF > toList () const
Returns a QList object with the data contained in this QVector.
std::vector< QPointF > toStdVector () const
Returns a std::vector object with the data contained in this QVector.
QPointF value (int i) const
Returns the value at index position i in the vector.
QPointF value (int i, const QPointF &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QVector ()
Destroys the vector.
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QPolygonF &polygon)
Writes the given polygon to the given stream, and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QPolygonF &polygon)
Reads a polygon from the given stream into the given polygon, and returns a reference to the stream.
Related Functions inherited from QVector< QPointF >
QDataStream & operator<< (QDataStream &out, const QVector< QPointF > &vector)
Writes the vector vector to stream out.
QDataStream & operator>> (QDataStream &in, QVector< QPointF > &vector)
Reads a vector from stream in into vector.
Additional Inherited Members
Public Types inherited from QVector< QPointF >
typedef const QPointF * const_iterator
The QVector::const_iterator typedef provides an STL-style const iterator for QVector and QStack.
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for T &.
typedef const_iterator ConstIterator
Qt-style synonym for QVector::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef QPointF * iterator
The QVector::iterator typedef provides an STL-style non-const iterator for QVector and QStack.
typedef iterator Iterator
Qt-style synonym for QVector::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef QPointF value_type
Typedef for T.
Static Public Functions inherited from QVector< QPointF >
static QVector< QPointF > fromList (const QList< QPointF > &list)
Returns a QVector object with the data contained in list.
static QVector< QPointF > fromStdVector (const std::vector< QPointF > &vector)
Returns a QVector object with the data contained in vector.
Public Variables inherited from QVector< QPointF >
QVectorData * d
Data * p
Detailed Description
The QPolygonF class provides a vector of points using floating point precision.
Note
This class or function is reentrant.
A QPolygonF is a QVector<QPointF>. The easiest way to add points to a QPolygonF is to use its streaming operator, as illustrated below:
        QPolygonF polygon;
        polygon << QPointF(10.4, 20.5) << QPointF(20.2, 30.2);
In addition to the functions provided by QVector, QPolygonF provides the boundingRect() and translate() functions for geometry operations. Use the QMatrix::map() function for more general transformations of QPolygonFs.
QPolygonF also provides the isClosed() function to determine whether a polygon's start and end points are the same, and the toPolygon() function returning an integer precision copy of this polygon.
The QPolygonF class is Implicit Data Sharing.
See also
QVector, QPolygon, QLineF
Definition at line 134 of file qpolygon.h.
Constructors and Destructors
QPolygonF() [1/6]
QPolygonF::QPolygonF () inline
Constructs a polygon with no points.
See also
QVector::isEmpty()
Definition at line 137 of file qpolygon.h.
 {}
~QPolygonF()
QPolygonF::~QPolygonF () inline
Destroys the polygon.
Definition at line 138 of file qpolygon.h.
 {}
QPolygonF() [2/6]
QPolygonF::QPolygonF (int size) inline
Constructs a polygon of the given size.
Creates an empty polygon if size == 0.
See also
QVector::isEmpty()
Definition at line 165 of file qpolygon.h.
 : QVector<QPointF>(asize) {}
QPolygonF() [3/6]
QPolygonF::QPolygonF (const QPolygonF & a) inline
Constructs a copy of the given polygon.
Definition at line 140 of file qpolygon.h.
 : QVector<QPointF>(a) {}
QPolygonF() [4/6]
QPolygonF::QPolygonF (const QVector< QPointF > & v) inline
Constructs a polygon containing the specified points.
Definition at line 141 of file qpolygon.h.
 : QVector<QPointF>(v) {}
QPolygonF() [5/6]
QPolygonF::QPolygonF (const QRectF & rectangle)
Constructs a closed polygon from the specified rectangle.
The polygon contains the four vertices of the rectangle in clockwise order starting and ending with the top-left vertex.
See also
isClosed()
Definition at line 626 of file qpolygon.cpp.
 {
     reserve(5);
     append(QPointF(r.x(), r.y()));
     append(QPointF(r.x() + r.width(), r.y()));
     append(QPointF(r.x() + r.width(), r.y() + r.height()));
     append(QPointF(r.x(), r.y() + r.height()));
     append(QPointF(r.x(), r.y()));
 }
QPolygonF() [6/6]
QPolygonF::QPolygonF (const QPolygon & polygon)
Constructs a float based polygon from the specified integer based polygon.
See also
toPolygon()
Definition at line 648 of file qpolygon.cpp.
 {
     reserve(a.size());
     for (int i=0; i<a.size(); ++i)
         append(a.at(i));
 }
Functions
boundingRect()
QRectF QPolygonF::boundingRect () const
Returns the bounding rectangle of the polygon, or QRectF(0,0,0,0) if the polygon is empty.
See also
QVector::isEmpty()
Definition at line 742 of file qpolygon.cpp.
Referenced by QGLPathMaskGenerator::computeScreenRect(), QPicturePaintEngine::drawPolygon(), QGraphicsSceneIndex::items(), QMacPixmapData::macCreatePixels(), QGraphicsViewPrivate::mapToScene(), QAccessibleDial::rect(), QGraphicsView::render(), QPainterPath::toFillPolygons(), QX11PixmapData::transformed(), and QImage::transformed().
 {
     if (isEmpty())
         return QRectF(0, 0, 0, 0);
     register const QPointF *pd = constData();
     qreal minx, maxx, miny, maxy;
     minx = maxx = pd->x();
     miny = maxy = pd->y();
     ++pd;
     for (int i = 1; i < size(); ++i) {
         if (pd->x() < minx)
             minx = pd->x();
         else if (pd->x() > maxx)
             maxx = pd->x();
         if (pd->y() < miny)
             miny = pd->y();
         else if (pd->y() > maxy)
             maxy = pd->y();
         ++pd;
     }
     return QRectF(minx,miny, maxx - minx, maxy - miny);
 }
containsPoint()
bool QPolygonF::containsPoint (const QPointF & point, Qt::FillRule fillRule) const
Returns true if the given point is inside the polygon according to the specified fillRule; otherwise returns false.
Since
4.3
Definition at line 940 of file qpolygon.cpp.
 {
     if (isEmpty())
         return false;
     int winding_number = 0;
     QPointF last_pt = at(0);
     QPointF last_start = at(0);
     for (int i = 1; i < size(); ++i) {
         const QPointF &e = at(i);
         qt_polygon_isect_line(last_pt, e, pt, &winding_number);
         last_pt = e;
     }
     // implicitly close last subpath
     if (last_pt != last_start)
         qt_polygon_isect_line(last_pt, last_start, pt, &winding_number);
     return (fillRule == Qt::WindingFill
             ? (winding_number != 0)
             : ((winding_number % 2) != 0));
 }
intersected()
QPolygonF QPolygonF::intersected (const QPolygonF & r) const
Returns a polygon which is the intersection of this polygon and r.
Since
4.3
Set operations on polygons will treat the polygons as areas. Non-closed polygons will be treated as implicitly closed.
Definition at line 1096 of file qpolygon.cpp.
 {
     QPainterPath subject; subject.addPolygon(*this);
     QPainterPath clip; clip.addPolygon(r);
     return subject.intersected(clip).toFillPolygon();
 }
isClosed()
bool QPolygonF::isClosed () const inline
Returns true if the polygon is closed; otherwise returns false.
A polygon is said to be closed if its start point and end point are equal.
See also
QVector::first(), QVector::last()
Definition at line 154 of file qpolygon.h.
Referenced by QPainterPath::toFillPolygon(), and QPainterPath::toFillPolygons().
 { return !isEmpty() && first() == last(); }
subtracted()
QPolygonF QPolygonF::subtracted (const QPolygonF & r) const
Returns a polygon which is r subtracted from this polygon.
Since
4.3
Set operations on polygons will treat the polygons as areas. Non-closed polygons will be treated as implicitly closed.
Definition at line 1117 of file qpolygon.cpp.
 {
     QPainterPath subject; subject.addPolygon(*this);
     QPainterPath clip; clip.addPolygon(r);
     return subject.subtracted(clip).toFillPolygon();
 }
swap()
void QPolygonF::swap (QPolygonF & other) inline
Swaps polygon other with this polygon.
Since
4.8
This operation is very fast and never fails.
Definition at line 144 of file qpolygon.h.
 { QVector<QPointF>::swap(other); } // prevent QVector<QPointF><->QPolygonF swaps
toPolygon()
QPolygon QPolygonF::toPolygon () const
Creates and returns a QPolygon by converting each QPointF to a QPoint.
See also
QPointF::toPoint()
Definition at line 772 of file qpolygon.cpp.
Referenced by QOpenGLPaintEngine::clip(), clipTransformIsSimple(), QPolygon::intersected(), QMatrix::map(), QTransform::map(), QPolygon::subtracted(), QX11PaintEnginePrivate::systemStateChanged(), QPolygon::united(), QCoreGraphicsPaintEngine::updateClipPath(), QX11PaintEngine::updateState(), and QOpenGLPaintEngine::updateState().
 {
     QPolygon a;
     a.reserve(size());
     for (int i=0; i<size(); ++i)
         a.append(at(i).toPoint());
     return a;
 }
translate() [1/2]
void QPolygonF::translate (qreal dx, qreal dy) inline
Translates all points in the polygon by ({dx}, {dy}).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
translated()
Definition at line 179 of file qpolygon.h.
Referenced by translated().
 { translate(QPointF(dx, dy)); }
translate() [2/2]
void QPolygonF::translate (const QPointF & offset)
Translate all points in the polygon by the given offset.
See also
translated()
Definition at line 671 of file qpolygon.cpp.
 {
     if (offset.isNull())
         return;
     register QPointF *p = data();
     register int i = size();
     while (i--) {
         *p += offset;
         ++p;
     }
 }
translated() [1/2]
QPolygonF QPolygonF::translated (qreal dx, qreal dy) const inline
Returns a copy of the polygon that is translated by ({dx}, {dy}).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.6
See also
translate()
Definition at line 182 of file qpolygon.h.
Referenced by QTransform::map(), QGraphicsItem::mapFromParent(), QGraphicsItem::mapFromScene(), QGraphicsItem::mapToParent(), and QGraphicsItem::mapToScene().
 { return translated(QPointF(dx, dy)); }
translated() [2/2]
QPolygonF QPolygonF::translated (const QPointF & offset) const
Returns a copy of the polygon that is translated by the given offset.
Since
4.6
See also
translate()
Definition at line 702 of file qpolygon.cpp.
 {
     QPolygonF copy(*this);
     copy.translate(offset);
     return copy;
 }
united()
QPolygonF QPolygonF::united (const QPolygonF & r) const
Returns a polygon which is the union of this polygon and r.
Since
4.3
Set operations on polygons will treat the polygons as areas. Non-closed polygons will be treated as implicitly closed.
See also
intersected(), subtracted()
Definition at line 1075 of file qpolygon.cpp.
 {
     QPainterPath subject; subject.addPolygon(*this);
     QPainterPath clip; clip.addPolygon(r);
     return subject.united(clip).toFillPolygon();
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QPolygonF & polygon) related
Writes the given polygon to the given stream, and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 871 of file qpolygon.cpp.
Referenced by QPolygonF().
 {
     quint32 len = a.size();
     uint i;
     s << len;
     for (i = 0; i < len; ++i)
         s << a.at(i);
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QPolygonF & polygon) related
Reads a polygon from the given stream into the given polygon, and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 895 of file qpolygon.cpp.
Referenced by QPolygonF().
 {
     quint32 len;
     uint i;
     s >> len;
     a.reserve(a.size() + (int)len);
     QPointF p;
     for (i = 0; i < len; ++i) {
         s >> p;
         a.insert(i, p);
     }
     return s;
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpolygon.h
/src/gui/painting/qpolygon.cpp