Qt 4.8: QXmlInputSource Class Reference
QXmlInputSource Class Reference
The QXmlInputSource class provides the input data for the QXmlReader subclasses.
#include <qxml.h>
Public Functions
virtual QString data () const
Returns the data the input source contains or an empty string if the input source does not contain any data.
virtual void fetchData ()
This function reads more data from the device that was set during construction.
virtual QChar next ()
Returns the next character of the input source.
QXmlInputSource ()
Constructs an input source which contains no data.
QXmlInputSource (QIODevice *dev)
Constructs an input source and gets the data from device dev.
virtual void reset ()
This function sets the position used by next() to the beginning of the data returned by data().
virtual void setData (const QString &dat)
Sets the data of the input source to dat.
virtual void setData (const QByteArray &dat)
The data dat is passed through the correct text-codec, before it is set.
virtual ~QXmlInputSource ()
Destructor.
Static Public Variables
static const ushort EndOfData = 0xfffe
static const ushort EndOfDocument = 0xffff
Protected Functions
virtual QString fromRawData (const QByteArray &data, bool beginning=false)
This function reads the XML file from data and tries to recognize the encoding.
Private Functions
void init ()
Properties
QXmlInputSourcePrivate * d
Detailed Description
The QXmlInputSource class provides the input data for the QXmlReader subclasses.
Note
This class or function is reentrant.
Attention
Module: QtXml
All subclasses of QXmlReader read the input XML document from this class.
This class recognizes the encoding of the data by reading the encoding declaration in the XML file if it finds one, and reading the data using the corresponding encoding. If it does not find an encoding declaration, then it assumes that the data is either in UTF-8 or UTF-16, depending on whether it can find a byte-order mark.
There are two ways to populate the input source with data: you can construct it with a QIODevice* so that the input source reads the data from that device. Or you can set the data explicitly with one of the setData() functions.
Usually you either construct a QXmlInputSource that works on a QIODevice* or you construct an empty QXmlInputSource and set the data with setData(). There are only rare occasions where you would want to mix both methods.
The QXmlReader subclasses use the next() function to read the input character by character. If you want to start from the beginning again, use reset().
The functions data() and fetchData() are useful if you want to do something with the data other than parsing, e.g. displaying the raw XML file. The benefit of using the QXmlInputClass in such cases is that it tries to use the correct encoding.
See also
QXmlReader QXmlSimpleReader
Definition at line 158 of file qxml.h.
Constructors and Destructors
QXmlInputSource() [1/2]
QXmlInputSource::QXmlInputSource ()
Constructs an input source which contains no data.
See also
setData()
Definition at line 1370 of file qxml.cpp.
Referenced by QXmlInputSource().
 {
     init();
 }
QXmlInputSource() [2/2]
QXmlInputSource::QXmlInputSource (QIODevice * dev)
Constructs an input source and gets the data from device dev.
If dev is not open, it is opened in read-only mode. If dev is 0 or it is not possible to read from the device, the input source will contain no data.
See also
setData() fetchData() QIODevice
Definition at line 1383 of file qxml.cpp.
 {
     init();
     d->inputDevice = dev;
     if (dev->isOpen())
         d->inputDevice->setTextModeEnabled(false);
 }
~QXmlInputSource()
QXmlInputSource::~QXmlInputSource () virtual
Destructor.
Definition at line 1417 of file qxml.cpp.
 {
     // ### Qt 5: close the input device. See task 153111
 #ifndef QT_NO_TEXTCODEC
     delete d->encMapper;
 #endif
     delete d;
 }
Functions
data()
QString QXmlInputSource::data () const virtual
Returns the data the input source contains or an empty string if the input source does not contain any data.
See also
setData() QXmlInputSource() fetchData()
Definition at line 1491 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parsePEReference(), and QXmlSimpleReaderPrivate::processReference().
 {
     if (d->nextReturnedEndOfData) {
         QXmlInputSource *that = const_cast<QXmlInputSource*>(this);
         that->d->nextReturnedEndOfData = false;
         that->fetchData();
     }
     return d->str;
 }
fetchData()
void QXmlInputSource::fetchData () virtual
This function reads more data from the device that was set during construction.
If the input source already contained data, this function deletes that data first.
This object contains no data after a call to this function if the object was constructed without a device to read data from or if this function was not able to get more data from the device.
There are two occasions where a fetch is done implicitly by another function call: during construction (so that the object starts out with some initial data where available), and during a call to next() (if the data had run out).
You don't normally need to use this function if you use next().
See also
data() next() QXmlInputSource()
Definition at line 1551 of file qxml.cpp.
Referenced by data(), and QXmlSimpleReaderPrivate::processReference().
 {
     enum
     {
         BufferSize = 1024
     };
     QByteArray rawData;
     if (d->inputDevice || d->inputStream) {
         QIODevice *device = d->inputDevice ? d->inputDevice : d->inputStream->device();
         if (!device) {
             if (d->inputStream && d->inputStream->string()) {
                 QString *s = d->inputStream->string();
                 rawData = QByteArray((const char *) s->constData(), s->size() * sizeof(QChar));
             }
         } else if (device->isOpen() || device->open(QIODevice::ReadOnly)) {
             rawData.resize(BufferSize);
             qint64 size = device->read(rawData.data(), BufferSize);
             if (size != -1) {
                 // We don't want to give fromRawData() less than four bytes if we can avoid it.
                 while (size < 4) {
                     if (!device->waitForReadyRead(-1))
                         break;
                     int ret = device->read(rawData.data() + size, BufferSize - size);
                     if (ret <= 0)
                         break;
                     size += ret;
                 }
             }
             rawData.resize(qMax(qint64(0), size));
         }
         /* We do this inside the "if (d->inputDevice ..." scope
          * because if we're not using a stream or device, that is,
          * the user set a QString manually, we don't want to set
          * d->str. */
         setData(fromRawData(rawData));
     }
 }
fromRawData()
QString QXmlInputSource::fromRawData (const QByteArray & data, bool beginning = false) protected virtual
This function reads the XML file from data and tries to recognize the encoding.
It converts the raw data data into a QString and returns it. It tries its best to get the correct encoding for the XML file.
If beginning is true, this function assumes that the data starts at the beginning of a new XML document and looks for an encoding declaration. If beginning is false, it converts the raw data using the encoding determined from prior calls.
Definition at line 1650 of file qxml.cpp.
 {
 #ifdef QT_NO_TEXTCODEC
     Q_UNUSED(beginning);
     return QString::fromAscii(data.constData(), data.size());
 #else
     if (data.size() == 0)
         return QString();
     if (beginning) {
         delete d->encMapper;
         d->encMapper = 0;
     }
     int mib = 106; // UTF-8
     // This is the initial UTF codec we will read the encoding declaration with
     if (d->encMapper == 0) {
         d->encodingDeclBytes.clear();
         d->encodingDeclChars.clear();
         d->lookingForEncodingDecl = true;
         // look for byte order mark and read the first 5 characters
         if (data.size() >= 4) {
             uchar ch1 = data.at(0);
             uchar ch2 = data.at(1);
             uchar ch3 = data.at(2);
             uchar ch4 = data.at(3);
             if ((ch1 == 0 && ch2 == 0 && ch3 == 0xfe && ch4 == 0xff) ||
                 (ch1 == 0xff && ch2 == 0xfe && ch3 == 0 && ch4 == 0))
                 mib = 1017; // UTF-32 with byte order mark
             else if (ch1 == 0x3c && ch2 == 0x00 && ch3 == 0x00 && ch4 == 0x00)
                 mib = 1019; // UTF-32LE
             else if (ch1 == 0x00 && ch2 == 0x00 && ch3 == 0x00 && ch4 == 0x3c)
                 mib = 1018; // UTF-32BE
         }
         if (mib == 106 && data.size() >= 2) {
             uchar ch1 = data.at(0);
             uchar ch2 = data.at(1);
             if ((ch1 == 0xfe && ch2 == 0xff) || (ch1 == 0xff && ch2 == 0xfe))
                 mib = 1015; // UTF-16 with byte order mark
             else if (ch1 == 0x3c && ch2 == 0x00)
                 mib = 1014; // UTF-16LE
             else if (ch1 == 0x00 && ch2 == 0x3c)
                 mib = 1013; // UTF-16BE
         }
         QTextCodec *codec = QTextCodec::codecForMib(mib);
         Q_ASSERT(codec);
         d->encMapper = codec->makeDecoder();
     }
     QString input = d->encMapper->toUnicode(data, data.size());
     if (d->lookingForEncodingDecl) {
         d->encodingDeclChars += input;
         bool needMoreText;
         QString encoding = extractEncodingDecl(d->encodingDeclChars, &needMoreText);
         if (!encoding.isEmpty()) {
             if (QTextCodec *codec = QTextCodec::codecForName(encoding.toLatin1())) {
                 /* If the encoding is the same, we don't have to do toUnicode() all over again. */
                 if(codec->mibEnum() != mib) {
                     delete d->encMapper;
                     d->encMapper = codec->makeDecoder();
                     /* The variable input can potentially be large, so we deallocate
                      * it before calling toUnicode() in order to avoid having two
                      * large QStrings in memory simultaneously. */
                     input.clear();
                     // prime the decoder with the data so far
                     d->encMapper->toUnicode(d->encodingDeclBytes, d->encodingDeclBytes.size());
                     // now feed it the new data
                     input = d->encMapper->toUnicode(data, data.size());
                 }
             }
         }
         d->encodingDeclBytes += data;
         d->lookingForEncodingDecl = needMoreText;
     }
     return input;
 #endif
 }
init()
void QXmlInputSource::init () private
Definition at line 1342 of file qxml.cpp.
 {
     d = new QXmlInputSourcePrivate;
     QT_TRY {
         d->inputDevice = 0;
         d->inputStream = 0;
         setData(QString());
 #ifndef QT_NO_TEXTCODEC
         d->encMapper = 0;
 #endif
         d->nextReturnedEndOfData = true; // first call to next() will call fetchData()
         d->encodingDeclBytes.clear();
         d->encodingDeclChars.clear();
         d->lookingForEncodingDecl = true;
     } QT_CATCH(...) {
         delete(d);
         QT_RETHROW;
     }
 }
next()
QChar QXmlInputSource::next () virtual
Returns the next character of the input source.
If this function reaches the end of available data, it returns QXmlInputSource::EndOfData. If you call next() after that, it tries to fetch more data by calling fetchData(). If the fetchData() call results in new data, this function returns the first character of that data; otherwise it returns QXmlInputSource::EndOfDocument.
Readers, such as QXmlSimpleReader, will assume that the end of the XML document has been reached if the this function returns QXmlInputSource::EndOfDocument, and will check that the supplied input is well-formed. Therefore, when reimplementing this function, it is important to ensure that this behavior is duplicated.
See also
reset() fetchData() QXmlSimpleReader::parse() QXmlSimpleReader::parseContinue()
Definition at line 1444 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::next().
 {
     if (d->pos >= d->length) {
         if (d->nextReturnedEndOfData) {
             d->nextReturnedEndOfData = false;
             fetchData();
             if (d->pos >= d->length) {
                 return EndOfDocument;
             }
             return next();
         }
         d->nextReturnedEndOfData = true;
         return EndOfData;
     }
     // QXmlInputSource has no way to signal encoding errors. The best we can do
     // is return EndOfDocument. We do *not* return EndOfData, because the reader
     // will then just call this function again to get the next char.
     QChar c = d->unicode[d->pos++];
     if (c.unicode() == EndOfData)
         c = EndOfDocument;
     return c;
 }
reset()
void QXmlInputSource::reset () virtual
This function sets the position used by next() to the beginning of the data returned by data().
This is useful if you want to use the input source for more than one parse.
Note
In the case that the underlying data source is a QIODevice, the current position in the device is not automatically set to the start of input. Call QIODevice::seek(0) on the device to do this.
See also
next()
Definition at line 1479 of file qxml.cpp.
 {
     d->nextReturnedEndOfData = false;
     d->pos = 0;
 }
setData() [1/2]
void QXmlInputSource::setData (const QString & dat) virtual
Sets the data of the input source to dat.
If the input source already contains data, this function deletes that data first.
See also
data()
Definition at line 1509 of file qxml.cpp.
Referenced by QDomDocument::setContent().
 {
     d->str = dat;
     d->unicode = dat.unicode();
     d->pos = 0;
     d->length = d->str.length();
     d->nextReturnedEndOfData = false;
 }
setData() [2/2]
void QXmlInputSource::setData (const QByteArray & dat) virtual
The data dat is passed through the correct text-codec, before it is set.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1527 of file qxml.cpp.
 {
     setData(fromRawData(dat));
 }
Properties
d
QXmlInputSourcePrivate* QXmlInputSource::d private
Definition at line 185 of file qxml.h.
Referenced by data().
EndOfData
const ushort QXmlInputSource::EndOfData = 0xfffe static
Definition at line 172 of file qxml.h.
Referenced by QXmlAttributes::append(), and QXmlSimpleReaderPrivate::initData().
EndOfDocument
const ushort QXmlInputSource::EndOfDocument = 0xffff static
Definition at line 173 of file qxml.h.
Referenced by QXmlAttributes::append().
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp