Qt 4.8: QCompletionEngine Class Reference
QCompletionEngine Class Reference abstract
#include <qcompleter_p.h>
Public Types
typedef QMap< QModelIndex, CacheItem > Cache
typedef QMap< QString, QMatchData > CacheItem
Public Functions
void filter (const QStringList &parts)
virtual QMatchData filter (const QString &, const QModelIndex &, int)=0
QMatchData filterHistory ()
virtual void filterOnDemand (int)
bool lookupCache (QString part, const QModelIndex &parent, QMatchData *m)
int matchCount () const
bool matchHint (QString, const QModelIndex &, QMatchData *)
QCompletionEngine (QCompleterPrivate *c)
void saveInCache (QString, const QModelIndex &, const QMatchData &)
virtual ~QCompletionEngine ()
Public Variables
QCompleterPrivate * c
Cache cache
int cost
QMatchData curMatch
QModelIndex curParent
QStringList curParts
int curRow
QMatchData historyMatch
Detailed Description
Definition at line 141 of file qcompleter_p.h.
Typedefs
Cache
typedef QMap<QModelIndex, CacheItem> QCompletionEngine::Cache
Definition at line 145 of file qcompleter_p.h.
CacheItem
typedef QMap<QString, QMatchData> QCompletionEngine::CacheItem
Definition at line 144 of file qcompleter_p.h.
Constructors and Destructors
QCompletionEngine()
QCompletionEngine::QCompletionEngine (QCompleterPrivate * c) inline
Definition at line 147 of file qcompleter_p.h.
 : c(c), curRow(-1), cost(0) { }
~QCompletionEngine()
virtual QCompletionEngine::~QCompletionEngine () inline virtual
Definition at line 148 of file qcompleter_p.h.
 { }
Functions
filter() [1/2]
void QCompletionEngine::filter (const QStringList & parts)
Definition at line 438 of file qcompleter.cpp.
Referenced by QCompletionModel::filter().
 {
     const QAbstractItemModel *model = c->proxy->sourceModel();
     curParts = parts;
     if (curParts.isEmpty())
         curParts.append(QString());
     curRow = -1;
     curParent = QModelIndex();
     curMatch = QMatchData();
     historyMatch = filterHistory();
     if (!model)
         return;
     QModelIndex parent;
     for (int i = 0; i < curParts.count() - 1; i++) {
         QString part = curParts[i];
         int emi = filter(part, parent, -1).exactMatchIndex;
         if (emi == -1)
             return;
         parent = model->index(emi, c->column, parent);
     }
     // Note that we set the curParent to a valid parent, even if we have no matches
     // When filtering is disabled, we show all the items under this parent
     curParent = parent;
     if (curParts.last().isEmpty())
         curMatch = QMatchData(QIndexMapper(0, model->rowCount(curParent) - 1), -1, false);
     else
         curMatch = filter(curParts.last(), curParent, 1); // build at least one
     curRow = curMatch.isValid() ? 0 : -1;
 }
filter() [2/2]
virtual QMatchData QCompletionEngine::filter (const QString & , const QModelIndex & , int) pure virtual
Implemented in QUnsortedModelEngine, and QSortedModelEngine.
filterHistory()
QMatchData QCompletionEngine::filterHistory ()
Definition at line 472 of file qcompleter.cpp.
 {
     QAbstractItemModel *source = c->proxy->sourceModel();
     if (curParts.count() <= 1 || c->proxy->showAll || !source)
         return QMatchData();
     bool isDirModel = false;
     bool isFsModel = false;
     Q_UNUSED(isDirModel)
     Q_UNUSED(isFsModel)
 #ifndef QT_NO_DIRMODEL
     isDirModel = (qobject_cast<QDirModel *>(source) != 0);
 #endif
 #ifndef QT_NO_FILESYSTEMMODEL
     isFsModel = (qobject_cast<QFileSystemModel *>(source) != 0);
 #endif
     QVector<int> v;
     QIndexMapper im(v);
     QMatchData m(im, -1, true);
     for (int i = 0; i < source->rowCount(); i++) {
         QString str = source->index(i, c->column).data().toString();
         if (str.startsWith(c->prefix, c->cs)
 #if (!defined(Q_OS_WIN) || defined(Q_OS_WINCE)) && !defined(Q_OS_SYMBIAN)
             && ((!isFsModel && !isDirModel) || QDir::toNativeSeparators(str) != QDir::separator())
 #endif
             )
             m.indices.append(i);
     }
     return m;
 }
filterOnDemand()
virtual void QCompletionEngine::filterOnDemand (int) inline virtual
Reimplemented in QUnsortedModelEngine.
Definition at line 158 of file qcompleter_p.h.
Referenced by QCompletionModel::completionCount(), QCompletionModel::index(), QCompletionModel::mapFromSource(), and QCompletionModel::setCurrentRow().
 { }
lookupCache()
bool QCompletionEngine::lookupCache (QString part, const QModelIndex & parent, QMatchData * m)
Definition at line 523 of file qcompleter.cpp.
 {
    if (c->cs == Qt::CaseInsensitive)
         part = part.toLower();
    const CacheItem& map = cache[parent];
    if (!map.contains(part))
        return false;
    *m = map[part];
    return true;
 }
matchCount()
int QCompletionEngine::matchCount () const inline
Definition at line 161 of file qcompleter_p.h.
Referenced by QCompleterPrivate::_q_complete(), QCompletionModel::completionCount(), QCompletionModel::currentIndex(), QCompletionModel::hasChildren(), QCompletionModel::index(), QCompletionModel::mapFromSource(), QCompletionModel::mapToSource(), QCompletionModel::rowCount(), and QCompletionModel::setCurrentRow().
 { return curMatch.indices.count() + historyMatch.indices.count(); }
matchHint()
bool QCompletionEngine::matchHint (QString part, const QModelIndex & parent, QMatchData * hint)
Definition at line 504 of file qcompleter.cpp.
 {
     if (c->cs == Qt::CaseInsensitive)
         part = part.toLower();
     const CacheItem& map = cache[parent];
     QString key = part;
     while (!key.isEmpty()) {
         key.chop(1);
         if (map.contains(key)) {
             *hint = map[key];
             return true;
         }
     }
     return false;
 }
saveInCache()
void QCompletionEngine::saveInCache (QString part, const QModelIndex & parent, const QMatchData & m)
Definition at line 535 of file qcompleter.cpp.
 {
     QMatchData old = cache[parent].take(part);
     cost = cost + m.indices.cost() - old.indices.cost();
     if (cost * sizeof(int) > 1024 * 1024) {
         QMap<QModelIndex, CacheItem>::iterator it1 = cache.begin();
         while (it1 != cache.end()) {
             CacheItem& ci = it1.value();
             int sz = ci.count()/2;
             QMap<QString, QMatchData>::iterator it2 = ci.begin();
             int i = 0;
             while (it2 != ci.end() && i < sz) {
                 cost -= it2.value().indices.cost();
                 it2 = ci.erase(it2);
                 i++;
             }
             if (ci.count() == 0) {
               it1 = cache.erase(it1);
             } else {
               ++it1;
             }
         }
     }
     if (c->cs == Qt::CaseInsensitive)
         part = part.toLower();
     cache[parent][part] = m;
 }
Properties
c
QCompleterPrivate* QCompletionEngine::c
Definition at line 164 of file qcompleter_p.h.
cache
Cache QCompletionEngine::cache
Definition at line 169 of file qcompleter_p.h.
Referenced by QCompletionModel::invalidate().
cost
int QCompletionEngine::cost
Definition at line 170 of file qcompleter_p.h.
curMatch
QMatchData QCompletionEngine::curMatch
Definition at line 163 of file qcompleter_p.h.
Referenced by QCompletionModel::currentIndex(), QCompletionModel::mapFromSource(), and QCompletionModel::mapToSource().
curParent
QModelIndex QCompletionEngine::curParent
Definition at line 166 of file qcompleter_p.h.
Referenced by QCompletionModel::filter(), QCompletionModel::index(), QCompletionModel::mapFromSource(), QCompletionModel::mapToSource(), and QCompletionModel::rowCount().
curParts
QStringList QCompletionEngine::curParts
Definition at line 165 of file qcompleter_p.h.
Referenced by QCompletionModel::invalidate(), and QCompletionModel::rowCount().
curRow
int QCompletionEngine::curRow
Definition at line 167 of file qcompleter_p.h.
Referenced by QCompletionModel::currentIndex(), and QCompletionModel::setCurrentRow().
historyMatch
QMatchData QCompletionEngine::historyMatch
Definition at line 163 of file qcompleter_p.h.
Referenced by QCompletionModel::index(), QCompletionModel::mapFromSource(), and QCompletionModel::mapToSource().
The documentation for this class was generated from the following files:
/src/gui/util/qcompleter_p.h
/src/gui/util/qcompleter.cpp