Qt 4.8: QImage Class Reference
QImage Class Reference
The QImage class provides a hardware-independent image representation that allows direct access to the pixel data, and can be used as a paint device.
#include <qimage.h>
Public Types
typedef QImageData * DataPtr
enum Format {
Format_Invalid, Format_Mono, Format_MonoLSB, Format_Indexed8,
Format_RGB32, Format_ARGB32, Format_ARGB32_Premultiplied, Format_RGB16,
Format_ARGB8565_Premultiplied, Format_RGB666, Format_ARGB6666_Premultiplied, Format_RGB555,
Format_ARGB8555_Premultiplied, Format_RGB888, Format_RGB444, Format_ARGB4444_Premultiplied
}
The following image formats are available in Qt.
enum InvertMode { InvertRgb, InvertRgba }
This enum type is used to describe how pixel values should be inverted in the invertPixels() function.
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Functions
bool allGray () const
Returns true if all the colors in the image are shades of gray (i.e.
QImage alphaChannel () const
Returns the alpha channel of the image as a new grayscale QImage in which each pixel's red, green, and blue values are given the alpha value of the original image.
int bitPlaneCount () const
Returns the number of bit planes in the image.
uchar * bits ()
Returns a pointer to the first pixel data.
const uchar * bits () const
Note that QImage uses Implicit Data Sharing {implicit data sharing}, but this function does not perform a deep copy of the shared pixel data, because the returned data is const.
int byteCount () const
Returns the number of bytes occupied by the image data.
int bytesPerLine () const
Returns the number of bytes per image scanline.
qint64 cacheKey () const
Returns a number that identifies the contents of this QImage object.
QRgb color (int i) const
Returns the color in the color table at index i.
int colorCount () const
Returns the size of the color table for the image.
QVector< QRgb > colorTable () const
Returns a list of the colors contained in the image's color table, or an empty list if the image does not have a color table.
const uchar * constBits () const
Returns a pointer to the first pixel data.
const uchar * constScanLine (int) const
Returns a pointer to the pixel data at the scanline with index i.
QImage convertToFormat (Format f, Qt::ImageConversionFlags flags=Qt::AutoColor) const Q_REQUIRED_RESULT
Returns a copy of the image in the given format.
QImage convertToFormat (Format f, const QVector< QRgb > &colorTable, Qt::ImageConversionFlags flags=Qt::AutoColor) const Q_REQUIRED_RESULT
Returns a copy of the image converted to the given format, using the specified colorTable.
QImage copy (const QRect &rect=QRect()) const
Returns a sub-area of the image as a new image.
QImage copy (int x, int y, int w, int h) const
The returned image is copied from the position (x, y) in this image, and will always have the given width and height.
QImage createAlphaMask (Qt::ImageConversionFlags flags=Qt::AutoColor) const
Builds and returns a 1-bpp mask from the alpha buffer in this image.
QImage createHeuristicMask (bool clipTight=true) const
Creates and returns a 1-bpp heuristic mask for this image.
QImage createMaskFromColor (QRgb color, Qt::MaskMode mode=Qt::MaskInColor) const
Creates and returns a mask for this image based on the given color value.
DataPtr & data_ptr ()
int depth () const
Returns the depth of the image.
void detach ()
If multiple images share common data, this image makes a copy of the data and detaches itself from the sharing mechanism, making sure that this image is the only one referring to the data.
int devType () const
int dotsPerMeterX () const
Returns the number of pixels that fit horizontally in a physical meter.
int dotsPerMeterY () const
Returns the number of pixels that fit vertically in a physical meter.
void fill (uint pixel)
Fills the entire image with the given pixelValue.
void fill (const QColor &color)
Fills the entire image with the given color.
void fill (Qt::GlobalColor color)
Fills the image with the given color, described as a standard global color.
Format format () const
Returns the format of the image.
bool hasAlphaChannel () const
Returns true if the image has a format that respects the alpha channel, otherwise returns false.
int height () const
Returns the height of the image.
void invertPixels (InvertMode=InvertRgb)
Inverts all pixel values in the image.
bool isDetached () const
Returns true if the image is detached; otherwise returns false.
bool isGrayscale () const
For 32-bit images, this function is equivalent to allGray().
bool isNull () const
Returns true if it is a null image, otherwise returns false.
bool load (QIODevice *device, const char *format)
This function reads a QImage from the given device.
bool load (const QString &fileName, const char *format=0)
Loads an image from the file with the given fileName.
bool loadFromData (const uchar *buf, int len, const char *format=0)
Loads an image from the first len bytes of the given binary data.
bool loadFromData (const QByteArray &data, const char *aformat=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Loads an image from the given QByteArray data.
QImage mirrored (bool horizontally=false, bool vertically=true) const
Returns a mirror of the image, mirrored in the horizontal and/or the vertical direction depending on whether horizontal and vertical are set to true or false.
QT_DEPRECATED int numBytes () const
Returns the number of bytes occupied by the image data.
QT_DEPRECATED int numColors () const
Returns the size of the color table for the image.
QPoint offset () const
Returns the number of pixels by which the image is intended to be offset by when positioning relative to other images.
operator QVariant () const
Returns the image as a QVariant.
bool operator!= (const QImage &) const
Returns true if this image and the given image have different contents; otherwise returns false.
QImage & operator= (const QImage &)
Assigns a shallow copy of the given image to this image and returns a reference to this image.
bool operator== (const QImage &) const
Returns true if this image and the given image have the same contents; otherwise returns false.
QPaintEngine * paintEngine () const
Used by QPainter to retrieve a paint engine for the image.
QRgb pixel (int x, int y) const
Returns the color of the pixel at coordinates (x, y).
QRgb pixel (const QPoint &pt) const
Returns the color of the pixel at the given position.
int pixelIndex (int x, int y) const
Returns the pixel index at (x, y).
int pixelIndex (const QPoint &pt) const
Returns the pixel index at the given position.
QImage ()
Constructs a null image.
QImage (const QSize &size, Format format)
Constructs an image with the given size and format.
QImage (int width, int height, Format format)
Constructs an image with the given width, height and format.
QImage (uchar *data, int width, int height, Format format)
Constructs an image with the given width, height and format, that uses an existing memory buffer, data.
QImage (const uchar *data, int width, int height, Format format)
Constructs an image with the given width, height and format, that uses an existing read-only memory buffer, data.
QImage (uchar *data, int width, int height, int bytesPerLine, Format format)
Constructs an image with the given width, height and format, that uses an existing memory buffer, data.
QImage (const uchar *data, int width, int height, int bytesPerLine, Format format)
Constructs an image with the given width, height and format, that uses an existing memory buffer, data.
QImage (const char *const xpm[])
Constructs an image from the given xpm image.
QImage (const QString &fileName, const char *format=0)
Constructs an image and tries to load the image from the file with the given fileName.
QImage (const char *fileName, const char *format=0)
Constructs an image and tries to load the image from the file with the given fileName.
QImage (const QImage &)
Constructs a shallow copy of the given image.
QRect rect () const
Returns the enclosing rectangle (0, 0, width(), height()) of the image.
QImage rgbSwapped () const
Returns a QImage in which the values of the red and blue components of all pixels have been swapped, effectively converting an RGB image to an BGR image.
bool save (const QString &fileName, const char *format=0, int quality=-1) const
Saves the image to the file with the given fileName, using the given image file format and quality factor.
bool save (QIODevice *device, const char *format=0, int quality=-1) const
This function writes a QImage to the given device.
QImage scaled (int w, int h, Qt::AspectRatioMode aspectMode=Qt::IgnoreAspectRatio, Qt::TransformationMode mode=Qt::FastTransformation) const
QImage scaled (const QSize &s, Qt::AspectRatioMode aspectMode=Qt::IgnoreAspectRatio, Qt::TransformationMode mode=Qt::FastTransformation) const
QImage scaledToHeight (int h, Qt::TransformationMode mode=Qt::FastTransformation) const
Returns a scaled copy of the image.
QImage scaledToWidth (int w, Qt::TransformationMode mode=Qt::FastTransformation) const
Returns a scaled copy of the image.
uchar * scanLine (int)
Returns a pointer to the pixel data at the scanline with index i.
const uchar * scanLine (int) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int serialNumber () const
Returns a number that identifies the contents of this QImage object.
void setAlphaChannel (const QImage &alphaChannel)
Sets the alpha channel of this image to the given alphaChannel.
void setColor (int i, QRgb c)
Sets the color at the given index in the color table, to the given to colorValue.
void setColorCount (int)
Resizes the color table to contain colorCount entries.
void setColorTable (const QVector< QRgb > colors)
Sets the color table used to translate color indexes to QRgb values, to the specified colors.
void setDotsPerMeterX (int)
Sets the number of pixels that fit horizontally in a physical meter, to x.
void setDotsPerMeterY (int)
Sets the number of pixels that fit vertically in a physical meter, to y.
QT_DEPRECATED void setNumColors (int)
Resizes the color table to contain numColors entries.
void setOffset (const QPoint &)
Sets the number of pixels by which the image is intended to be offset by when positioning relative to other images, to offset.
void setPixel (int x, int y, uint index_or_rgb)
Sets the pixel index or color at (x, y) to index_or_rgb.
void setPixel (const QPoint &pt, uint index_or_rgb)
Sets the pixel index or color at the given position to index_or_rgb.
void setText (const QString &key, const QString &value)
Sets the image text to the given text and associate it with the given key.
QT_DEPRECATED void setText (const char *key, const char *lang, const QString &)
QSize size () const
Returns the size of the image, i.
void swap (QImage &other)
Swaps image other with this image.
QString text (const QString &key=QString()) const
Returns the image text associated with the given key.
QT_DEPRECATED QString text (const char *key, const char *lang=0) const
QT_DEPRECATED QString text (const QImageTextKeyLang &) const
Returns the text recorded for the given keywordAndLanguage.
QStringList textKeys () const
Returns the text keys for this image.
QT_DEPRECATED QStringList textLanguages () const
Returns the language identifiers for which some texts are recorded.
QT_DEPRECATED QList< QImageTextKeyLang > textList () const
Returns a list of QImageTextKeyLang objects that enumerate all the texts key/language pairs set for this image.
QImage transformed (const QMatrix &matrix, Qt::TransformationMode mode=Qt::FastTransformation) const
Returns a copy of the image that is transformed using the given transformation matrix and transformation mode.
QImage transformed (const QTransform &matrix, Qt::TransformationMode mode=Qt::FastTransformation) const
Returns a copy of the image that is transformed using the given transformation matrix and transformation mode.
bool valid (int x, int y) const
Returns true if QPoint(x, y) is a valid coordinate pair within the image; otherwise returns false.
bool valid (const QPoint &pt) const
Returns true if pos is a valid coordinate pair within the image; otherwise returns false.
int width () const
Returns the width of the image.
~QImage ()
Destroys the image and cleans up.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static QImage fromData (const uchar *data, int size, const char *format=0)
Constructs a QImage from the first size bytes of the given binary data.
static QImage fromData (const QByteArray &data, const char *format=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Loads an image from the given QByteArray data.
static QMatrix trueMatrix (const QMatrix &, int w, int h)
Returns the actual matrix used for transforming an image with the given width, height and matrix.
static QTransform trueMatrix (const QTransform &, int w, int h)
Returns the actual matrix used for transforming an image with the given width, height and matrix.
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
virtual int metric (PaintDeviceMetric metric) const
Returns the size for the specified metric on the device.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
QImageData * d
Friends
class QBlittablePixmapData
class QPixmapCacheEntry
class QRasterPixmapData
const QVector< QRgb > * qt_image_colortable (const QImage &image)
Q_GUI_EXPORT qint64 qt_image_id (const QImage &image)
class QWSOnScreenSurface
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QImage &image)
Writes the given image to the given stream as a PNG image, or as a BMP image if the stream's version is 1.
QDataStream & operator>> (QDataStream &stream, QImage &image)
Reads an image from the given stream and stores it in the given image.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Additional Inherited Members
Protected Variables inherited from QPaintDevice
ushort painters
Detailed Description
The QImage class provides a hardware-independent image representation that allows direct access to the pixel data, and can be used as a paint device.
Note
This class or function is reentrant.
Qt provides four classes for handling image data: QImage, QPixmap, QBitmap and QPicture. QImage is designed and optimized for I/O, and for direct pixel access and manipulation, while QPixmap is designed and optimized for showing images on screen. QBitmap is only a convenience class that inherits QPixmap, ensuring a depth of 1. Finally, the QPicture class is a paint device that records and replays QPainter commands.
Because QImage is a QPaintDevice subclass, QPainter can be used to draw directly onto images. When using QPainter on a QImage, the painting can be performed in another thread than the current GUI thread.
The QImage class supports several image formats described by the Format enum. These include monochrome, 8-bit, 32-bit and alpha-blended images which are available in all versions of Qt 4.x.
QImage provides a collection of functions that can be used to obtain a variety of information about the image. There are also several functions that enables transformation of the image.
QImage objects can be passed around by value since the QImage class uses Implicit Data Sharing{implicit data sharing}. QImage objects can also be streamed and compared.
Note
If you would like to load QImage objects in a static build of Qt, refer to the How To Create Qt Plugins::Static Plugins{Plugin HowTo}.
Warning
Painting on a QImage with the format QImage::Format_Indexed8 is not supported.
Reading and Writing Image Files
QImage provides several ways of loading an image file: The file can be loaded when constructing the QImage object, or by using the load() or loadFromData() functions later on. QImage also provides the static fromData() function, constructing a QImage from the given data. When loading an image, the file name can either refer to an actual file on disk or to one of the application's embedded resources. See The Qt Resource System overview for details on how to embed images and other resource files in the application's executable.
Simply call the save() function to save a QImage object.
The complete list of supported file formats are available through the QImageReader::supportedImageFormats() and QImageWriter::supportedImageFormats() functions. New file formats can be added as plugins. By default, Qt supports the following formats:
Format Description Qt's support
BMP Windows Bitmap Read/write
GIF Graphic Interchange Format (optional) Read
JPG Joint Photographic Experts Group Read/write
JPEG Joint Photographic Experts Group Read/write
PNG Portable Network Graphics Read/write
PBM Portable Bitmap Read
PGM Portable Graymap Read
PPM Portable Pixmap Read/write
TIFF Tagged Image File Format Read/write
XBM X11 Bitmap Read/write
XPM X11 Pixmap Read/write
Image Information
QImage provides a collection of functions that can be used to obtain a variety of information about the image:
Available Functions
Geometry
The size(), width(), height(), dotsPerMeterX(), and dotsPerMeterY() functions provide information about the image size and aspect ratio.
The rect() function returns the image's enclosing rectangle. The valid() function tells if a given pair of coordinates is within this rectangle. The offset() function returns the number of pixels by which the image is intended to be offset by when positioned relative to other images, which also can be manipulated using the setOffset() function.
Colors
The color of a pixel can be retrieved by passing its coordinates to the pixel() function. The pixel() function returns the color as a QRgb value indepedent of the image's format.
In case of monochrome and 8-bit images, the colorCount() and colorTable() functions provide information about the color components used to store the image data: The colorTable() function returns the image's entire color table. To obtain a single entry, use the pixelIndex() function to retrieve the pixel index for a given pair of coordinates, then use the color() function to retrieve the color. Note that if you create an 8-bit image manually, you have to set a valid color table on the image as well.
The hasAlphaChannel() function tells if the image's format respects the alpha channel, or not. The allGray() and isGrayscale() functions tell whether an image's colors are all shades of gray.
See also the Pixel Manipulation and Image Transformations sections.
Text
The text() function returns the image text associated with the given text key. An image's text keys can be retrieved using the textKeys() function. Use the setText() function to alter an image's text.
Low-level information
The depth() function returns the depth of the image. The supported depths are 1 (monochrome), 8, 16, 24 and 32 bits. The bitPlaneCount() function tells how many of those bits that are used. For more information see the Image Formats section.
The format(), bytesPerLine(), and byteCount() functions provide low-level information about the data stored in the image.
The cacheKey() function returns a number that uniquely identifies the contents of this QImage object.
Pixel Manipulation
The functions used to manipulate an image's pixels depend on the image format. The reason is that monochrome and 8-bit images are index-based and use a color lookup table, while 32-bit images store ARGB values directly. For more information on image formats, see the Image Formats section.
In case of a 32-bit image, the setPixel() function can be used to alter the color of the pixel at the given coordinates to any other color specified as an ARGB quadruplet. To make a suitable QRgb value, use the qRgb() (adding a default alpha component to the given RGB values, i.e. creating an opaque color) or qRgba() function. For example:
32-bit
QImage image(3, 3, QImage::Format_RGB32);
QRgb value;
value = qRgb(189, 149, 39); // 0xffbd9527
image.setPixel(1, 1, value);
value = qRgb(122, 163, 39); // 0xff7aa327
image.setPixel(0, 1, value);
image.setPixel(1, 0, value);
value = qRgb(237, 187, 51); // 0xffedba31
image.setPixel(2, 1, value);
In case of a 8-bit and monchrome images, the pixel value is only an index from the image's color table. So the setPixel() function can only be used to alter the color of the pixel at the given coordinates to a predefined color from the image's color table, i.e. it can only change the pixel's index value. To alter or add a color to an image's color table, use the setColor() function.
An entry in the color table is an ARGB quadruplet encoded as an QRgb value. Use the qRgb() and qRgba() functions to make a suitable QRgb value for use with the setColor() function. For example:
8-bit
QImage image(3, 3, QImage::Format_Indexed8);
QRgb value;
value = qRgb(122, 163, 39); // 0xff7aa327
image.setColor(0, value);
value = qRgb(237, 187, 51); // 0xffedba31
image.setColor(1, value);
value = qRgb(189, 149, 39); // 0xffbd9527
image.setColor(2, value);
image.setPixel(0, 1, 0);
image.setPixel(1, 0, 0);
image.setPixel(1, 1, 2);
image.setPixel(2, 1, 1);
QImage also provide the scanLine() function which returns a pointer to the pixel data at the scanline with the given index, and the bits() function which returns a pointer to the first pixel data (this is equivalent to scanLine(0)).
Image Formats
Each pixel stored in a QImage is represented by an integer. The size of the integer varies depending on the format. QImage supports several image formats described by the Format enum.
Monochrome images are stored using 1-bit indexes into a color table with at most two colors. There are two different types of monochrome images: big endian (MSB first) or little endian (LSB first) bit order.
8-bit images are stored using 8-bit indexes into a color table, i.e. they have a single byte per pixel. The color table is a QVector<QRgb>, and the QRgb typedef is equivalent to an unsigned int containing an ARGB quadruplet on the format 0xAARRGGBB.
32-bit images have no color table; instead, each pixel contains an QRgb value. There are three different types of 32-bit images storing RGB (i.e. 0xffRRGGBB), ARGB and premultiplied ARGB values respectively. In the premultiplied format the red, green, and blue channels are multiplied by the alpha component divided by 255.
An image's format can be retrieved using the format() function. Use the convertToFormat() functions to convert an image into another format. The allGray() and isGrayscale() functions tell whether a color image can safely be converted to a grayscale image.
Image Transformations
QImage supports a number of functions for creating a new image that is a transformed version of the original: The createAlphaMask() function builds and returns a 1-bpp mask from the alpha buffer in this image, and the createHeuristicMask() function creates and returns a 1-bpp heuristic mask for this image. The latter function works by selecting a color from one of the corners, then chipping away pixels of that color starting at all the edges.
The mirrored() function returns a mirror of the image in the desired direction, the scaled() returns a copy of the image scaled to a rectangle of the desired measures, and the rgbSwapped() function constructs a BGR image from a RGB image.
The scaledToWidth() and scaledToHeight() functions return scaled copies of the image.
The transformed() function returns a copy of the image that is transformed with the given transformation matrix and transformation mode: Internally, the transformation matrix is adjusted to compensate for unwanted translation, i.e. transformed() returns the smallest image containing all transformed points of the original image. The static trueMatrix() function returns the actual matrix used for transforming the image.
There are also functions for changing attributes of an image in-place:
Function Description
setDotsPerMeterX() Defines the aspect ratio by setting the number of pixels that fit horizontally in a physical meter.
setDotsPerMeterY() Defines the aspect ratio by setting the number of pixels that fit vertically in a physical meter.
fill() Fills the entire image with the given pixel value.
invertPixels() Inverts all pixel values in the image using the given InvertMode value.
setColorTable() Sets the color table used to translate color indexes. Only monochrome and 8-bit formats.
setColorCount()
Resizes the color table. Only monochrome and 8-bit formats.
Legal Information
For smooth scaling, the transformed() functions use code based on smooth scaling algorithm by Daniel M. Duley.
Copyright (C) 2004, 2005 Daniel M. Duley
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
See also
QImageReader, QImageWriter, QPixmap, QSvgRenderer, {Image Composition Example}, {Image Viewer Example}, {Scribble Example}, {Pixelator Example}
Definition at line 87 of file qimage.h.
Typedefs
DataPtr
QImage::DataPtr
Warning
This function is not part of the public interface.
Definition at line 345 of file qimage.h.
Enumerations
Format
enum QImage::Format
The following image formats are available in Qt.
Values greater than QImage::Format_RGB16 were added in Qt 4.4. See the notes after the table.
Format_Invalid The image is invalid.
Format_Mono The image is stored using 1-bit per pixel. Bytes are packed with the most significant bit (MSB) first.
Format_MonoLSB The image is stored using 1-bit per pixel. Bytes are packed with the less significant bit (LSB) first.
Format_Indexed8 The image is stored using 8-bit indexes into a colormap.
Format_RGB32 The image is stored using a 32-bit RGB format (0xffRRGGBB).
Format_ARGB32 The image is stored using a 32-bit ARGB format (0xAARRGGBB).
Format_ARGB32_Premultiplied The image is stored using a premultiplied 32-bit ARGB format (0xAARRGGBB), i.e. the red, green, and blue channels are multiplied by the alpha component divided by 255. (If RR, GG, or BB has a higher value than the alpha channel, the results are undefined.) Certain operations (such as image composition using alpha blending) are faster using premultiplied ARGB32 than with plain ARGB32.
Format_RGB16 The image is stored using a 16-bit RGB format (5-6-5).
Format_ARGB8565_Premultiplied The image is stored using a premultiplied 24-bit ARGB format (8-5-6-5).
Format_RGB666 The image is stored using a 24-bit RGB format (6-6-6). The unused most significant bits is always zero.
Format_ARGB6666_Premultiplied The image is stored using a premultiplied 24-bit ARGB format (6-6-6-6).
Format_RGB555 The image is stored using a 16-bit RGB format (5-5-5). The unused most significant bit is always zero.
Format_ARGB8555_Premultiplied The image is stored using a premultiplied 24-bit ARGB format (8-5-5-5).
Format_RGB888 The image is stored using a 24-bit RGB format (8-8-8).
Format_RGB444 The image is stored using a 16-bit RGB format (4-4-4). The unused bits are always zero.
Format_ARGB4444_Premultiplied The image is stored using a premultiplied 16-bit ARGB format (4-4-4-4).
Note
Drawing into a QImage with QImage::Format_Indexed8 is not supported.
Do not render into ARGB32 images using QPainter. Using QImage::Format_ARGB32_Premultiplied is significantly faster.
See also
format(), convertToFormat()
Enumerator
Format_Invalid
Format_Mono
Format_MonoLSB
Format_Indexed8
Format_RGB32
Format_ARGB32
Format_ARGB32_Premultiplied
Format_RGB16
Format_ARGB8565_Premultiplied
Format_RGB666
Format_ARGB6666_Premultiplied
Format_RGB555
Format_ARGB8555_Premultiplied
Format_RGB888
Format_RGB444
Format_ARGB4444_Premultiplied
Definition at line 91 of file qimage.h.
                 {
         Format_Invalid,
         Format_Mono,
         Format_MonoLSB,
         Format_Indexed8,
         Format_RGB32,
         Format_ARGB32,
         Format_ARGB32_Premultiplied,
         Format_RGB16,
         Format_ARGB8565_Premultiplied,
         Format_RGB666,
         Format_ARGB6666_Premultiplied,
         Format_RGB555,
         Format_ARGB8555_Premultiplied,
         Format_RGB888,
         Format_RGB444,
         Format_ARGB4444_Premultiplied,
 #if 0
         // reserved for future use
         Format_RGB15,
         Format_Grayscale16,
         Format_Grayscale8,
         Format_Grayscale4,
         Format_Grayscale4LSB,
         Format_Grayscale2,
         Format_Grayscale2LSB
 #endif
 #ifndef qdoc
         NImageFormats
 #endif
     };
InvertMode
enum QImage::InvertMode
This enum type is used to describe how pixel values should be inverted in the invertPixels() function.
InvertRgb Invert only the RGB values and leave the alpha channel unchanged.
InvertRgba Invert all channels, including the alpha channel.
See also
invertPixels()
Enumerator
InvertRgb
InvertRgba
Definition at line 90 of file qimage.h.
 { InvertRgb, InvertRgba };
Constructors and Destructors
QImage() [1/11]
QImage::QImage ()
Constructs a null image.
See also
isNull()
Definition at line 798 of file qimage.cpp.
Referenced by alphaChannel(), convertToFormat(), copy(), createAlphaMask(), createHeuristicMask(), createMaskFromColor(), mirrored(), operator>>(), QImage(), rgbSwapped(), scaled(), scaledToHeight(), scaledToWidth(), setPixel(), and transformed().
     : QPaintDevice()
 {
     d = 0;
 }
QImage() [2/11]
QImage::QImage (const QSize & size, Format format)
Constructs an image with the given size and format.
A null image is returned if memory cannot be allocated.
Warning
This will create a QImage with uninitialized data. Call fill() to fill the image with an appropriate pixel value before drawing onto it with QPainter.
Definition at line 829 of file qimage.cpp.
     : QPaintDevice()
 {
     d = QImageData::create(size, format, 0);
 }
QImage() [3/11]
QImage::QImage (int width, int height, Format format)
Constructs an image with the given width, height and format.
A null image will be returned if memory cannot be allocated.
Warning
This will create a QImage with uninitialized data. Call fill() to fill the image with an appropriate pixel value before drawing onto it with QPainter.
Definition at line 814 of file qimage.cpp.
     : QPaintDevice()
 {
     d = QImageData::create(QSize(width, height), format, 0);
 }
QImage() [4/11]
QImage::QImage (uchar * data, int width, int height, Format format)
Constructs an image with the given width, height and format, that uses an existing memory buffer, data.
The width and height must be specified in pixels, data must be 32-bit aligned, and each scanline of data in the image must also be 32-bit aligned.
The buffer must remain valid throughout the life of the QImage. The image does not delete the buffer at destruction.
If format is an indexed color format, the image color table is initially empty and must be sufficiently expanded with setColorCount() or setColorTable() before the image is used.
Definition at line 896 of file qimage.cpp.
     : QPaintDevice()
 {
     d = QImageData::create(data, width, height, 0, format, false);
 }
QImage() [5/11]
QImage::QImage (const uchar * data, int width, int height, Format format)
Constructs an image with the given width, height and format, that uses an existing read-only memory buffer, data.
The width and height must be specified in pixels, data must be 32-bit aligned, and each scanline of data in the image must also be 32-bit aligned.
The buffer must remain valid throughout the life of the QImage and all copies that have not been modified or otherwise detached from the original buffer. The image does not delete the buffer at destruction.
If format is an indexed color format, the image color table is initially empty and must be sufficiently expanded with setColorCount() or setColorTable() before the image is used.
Unlike the similar QImage constructor that takes a non-const data buffer, this version will never alter the contents of the buffer. For example, calling QImage::bits() will return a deep copy of the image, rather than the buffer passed to the constructor. This allows for the efficiency of constructing a QImage from raw data, without the possibility of the raw data being changed.
Definition at line 925 of file qimage.cpp.
     : QPaintDevice()
 {
     d = QImageData::create(const_cast<uchar*>(data), width, height, 0, format, true);
 }
QImage() [6/11]
QImage::QImage (uchar * data, int width, int height, int bytesPerLine, Format format)
Constructs an image with the given width, height and format, that uses an existing memory buffer, data.
The width and height must be specified in pixels. bytesPerLine specifies the number of bytes per line (stride).
The buffer must remain valid throughout the life of the QImage. The image does not delete the buffer at destruction.
If format is an indexed color format, the image color table is initially empty and must be sufficiently expanded with setColorCount() or setColorTable() before the image is used.
Definition at line 944 of file qimage.cpp.
     :QPaintDevice()
 {
     d = QImageData::create(data, width, height, bytesPerLine, format, false);
 }
QImage() [7/11]
QImage::QImage (const uchar * data, int width, int height, int bytesPerLine, Format format)
Constructs an image with the given width, height and format, that uses an existing memory buffer, data.
The width and height must be specified in pixels. bytesPerLine specifies the number of bytes per line (stride).
The buffer must remain valid throughout the life of the QImage. The image does not delete the buffer at destruction.
If format is an indexed color format, the image color table is initially empty and must be sufficiently expanded with setColorCount() or setColorTable() before the image is used.
Unlike the similar QImage constructor that takes a non-const data buffer, this version will never alter the contents of the buffer. For example, calling QImage::bits() will return a deep copy of the image, rather than the buffer passed to the constructor. This allows for the efficiency of constructing a QImage from raw data, without the possibility of the raw data being changed.
Definition at line 972 of file qimage.cpp.
     :QPaintDevice()
 {
     d = QImageData::create(const_cast<uchar*>(data), width, height, bytesPerLine, format, true);
 }
QImage() [8/11]
QImage::QImage (const char *const xpm[]) explicit
Constructs an image from the given xpm image.
Make sure that the image is a valid XPM image. Errors are silently ignored.
Note that it's possible to squeeze the XPM variable a little bit by using an unusual declaration:
static const char * const start_xpm[] = {
    "16 15 8 1",
    "a c #cec6bd",
....
The extra const makes the entire definition read-only, which is slightly more efficient (e.g., when the code is in a shared library) and able to be stored in ROM with the application.
Definition at line 1057 of file qimage.cpp.
     : QPaintDevice()
 {
     d = 0;
     if (!xpm)
         return;
     if (!qt_read_xpm_image_or_array(0, xpm, *this))
         // Issue: Warning because the constructor may be ambigious
         qWarning("QImage::QImage(), XPM is not supported");
 }
QImage() [9/11]
QImage::QImage (const QString & fileName, const char * format = 0) explicit
Constructs an image and tries to load the image from the file with the given fileName.
The loader attempts to read the image using the specified format. If the format is not specified (which is the default), the loader probes the file for a header to guess the file format.
If the loading of the image failed, this object is a null image.
The file name can either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed images and other resource files in the application's executable.
See also
isNull(), Reading and Writing Image Files
Definition at line 996 of file qimage.cpp.
     : QPaintDevice()
 {
     d = 0;
     load(fileName, format);
 }
QImage() [10/11]
QImage::QImage (const char * fileName, const char * format = 0) explicit
Constructs an image and tries to load the image from the file with the given fileName.
The loader attempts to read the image using the specified format. If the format is not specified (which is the default), the loader probes the file for a header to guess the file format.
If the loading of the image failed, this object is a null image.
The file name can either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed images and other resource files in the application's executable.
You can disable this constructor by defining QT_NO_CAST_FROM_ASCII when you compile your applications. This can be useful, for example, if you want to ensure that all user-visible strings go through QObject::tr().
See also
QString::fromAscii(), isNull(), {QImage::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 1027 of file qimage.cpp.
     : QPaintDevice()
 {
     // ### Qt 5: if you remove the QImage(const QByteArray &) QT3_SUPPORT
     // constructor, remove this constructor as well. The constructor here
     // exists so that QImage("foo.png") compiles without ambiguity.
     d = 0;
     load(QString::fromAscii(fileName), format);
 }
QImage() [11/11]
QImage::QImage (const QImage & image)
Constructs a shallow copy of the given image.
For more information about shallow copies, see the Implicit Data Sharing documentation.
See also
copy()
Definition at line 1097 of file qimage.cpp.
     : QPaintDevice()
 {
     if (image.paintingActive()) {
         d = 0;
         operator=(image.copy());
     } else {
         d = image.d;
         if (d)
             d->ref.ref();
     }
 }
~QImage()
QImage::~QImage ()
Destroys the image and cleans up.
Definition at line 1289 of file qimage.cpp.
 {
     if (d && !d->ref.deref())
         delete d;
 }
Functions
allGray()
bool QImage::allGray () const
Returns true if all the colors in the image are shades of gray (i.e.
their red, green and blue components are equal); otherwise false.
Note that this function is slow for images without color table.
See also
isGrayscale()
Definition at line 4435 of file qimage.cpp.
Referenced by QPSPrintEnginePrivate::drawImage(), and isGrayscale().
 {
     if (!d)
         return true;
     if (d->depth == 32) {
         int p = width()*height();
         const QRgb* b = (const QRgb*)bits();
         while (p--)
             if (!qIsGray(*b++))
                 return false;
     } else if (d->depth == 16) {
         int p = width()*height();
         const ushort* b = (const ushort *)bits();
         while (p--)
             if (!qIsGray(qt_colorConvert<quint32, quint16>(*b++, 0)))
                 return false;
     } else if (d->format == QImage::Format_RGB888) {
         int p = width()*height();
         const qrgb888* b = (const qrgb888 *)bits();
         while (p--)
             if (!qIsGray(qt_colorConvert<quint32, qrgb888>(*b++, 0)))
                 return false;
     } else {
         if (d->colortable.isEmpty())
             return true;
         for (int i = 0; i < colorCount(); i++)
             if (!qIsGray(d->colortable.at(i)))
                 return false;
     }
     return true;
 }
alphaChannel()
QImage QImage::alphaChannel () const
Returns the alpha channel of the image as a new grayscale QImage in which each pixel's red, green, and blue values are given the alpha value of the original image.
The color depth of the returned image is 8-bit.
You can see an example of use of this function in QPixmap's QPixmap::alphaChannel(), which works in the same way as this function on QPixmaps.
Most usecases for this function can be replaced with QPainter and using composition modes.
Warning
This is an expensive function.
See also
setAlphaChannel(), hasAlphaChannel(), {QPixmap::Pixmap Information}{Pixmap}, {QImage::Image Transformations}{Image Transformations}
Definition at line 6430 of file qimage.cpp.
Referenced by QX11PixmapData::alphaChannel(), QPixmapColorizeFilter::draw(), QImageTextureGlyphCache::fillTexture(), and QGLPixmapDropShadowFilter::processGL().
 {
     if (!d)
         return QImage();
     int w = d->width;
     int h = d->height;
     QImage image(w, h, Format_Indexed8);
     QIMAGE_SANITYCHECK_MEMORY(image);
     image.setColorCount(256);
     // set up gray scale table.
     for (int i=0; i<256; ++i)
         image.setColor(i, qRgb(i, i, i));
     if (!hasAlphaChannel()) {
         image.fill(255);
         return image;
     }
     if (d->format == Format_Indexed8) {
         const uchar *src_data = d->data;
         uchar *dest_data = image.d->data;
         for (int y=0; y<h; ++y) {
             const uchar *src = src_data;
             uchar *dest = dest_data;
             for (int x=0; x<w; ++x) {
                 *dest = qAlpha(d->colortable.at(*src));
                 ++dest;
                 ++src;
             }
             src_data += d->bytes_per_line;
             dest_data += image.d->bytes_per_line;
         }
     } else {
         QImage alpha32 = *this;
         if (d->format != Format_ARGB32 && d->format != Format_ARGB32_Premultiplied)
             alpha32 = convertToFormat(Format_ARGB32);
         QIMAGE_SANITYCHECK_MEMORY(alpha32);
         const uchar *src_data = alpha32.d->data;
         uchar *dest_data = image.d->data;
         for (int y=0; y<h; ++y) {
             const QRgb *src = (const QRgb *) src_data;
             uchar *dest = dest_data;
             for (int x=0; x<w; ++x) {
                 *dest = qAlpha(*src);
                 ++dest;
                 ++src;
             }
             src_data += alpha32.d->bytes_per_line;
             dest_data += image.d->bytes_per_line;
         }
     }
     return image;
 }
bitPlaneCount()
int QImage::bitPlaneCount () const
Returns the number of bit planes in the image.
Since
4.7
The number of bit planes is the number of bits of color and transparency information for each pixel. This is different from (i.e. smaller than) the depth when the image format contains unused bits.
See also
depth(), format(), {QImage::Image Formats}{Image Formats}
Definition at line 6523 of file qimage.cpp.
 {
     if (!d)
         return 0;
     int bpc = 0;
     switch (d->format) {
     case QImage::Format_Invalid:
         break;
     case QImage::Format_RGB32:
         bpc = 24;
         break;
     case QImage::Format_RGB666:
         bpc = 18;
         break;
     case QImage::Format_RGB555:
         bpc = 15;
         break;
     case QImage::Format_ARGB8555_Premultiplied:
         bpc = 23;
         break;
     case QImage::Format_RGB444:
         bpc = 12;
         break;
     default:
         bpc = qt_depthForFormat(d->format);
         break;
     }
     return bpc;
 }
bits() [1/2]
uchar * QImage::bits ()
Returns a pointer to the first pixel data.
This is equivalent to scanLine(0).
Note that QImage uses Implicit Data Sharing {implicit data sharing}. This function performs a deep copy of the shared pixel data, thus ensuring that this QImage is the only one using the current return value.
See also
scanLine(), byteCount(), constBits()
Definition at line 1946 of file qimage.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QFontEngineXLFD::addOutlineToPath(), allGray(), QAlphaWidget::alphaBlend(), QProxyFontEngine::alphaMapForGlyph(), QFontEngineFT::alphaRGBMapForGlyph(), QVNCScreen::base(), QGLPixmapData::bind(), QVolatileImage::bits(), QAhiScreen::blit(), QProxyFontEngine::canRender(), checkForAlphaPixels(), copy(), QVolatileImage::copyFrom(), QX11PixmapData::createBitmapFromImage(), QXlibCursor::createCursorBitmap(), QDirectFBScreen::createDFBSurface(), createMaskFromColor(), QGIFFormat::decode(), QWSDisplay::defineCursor(), QGIFFormat::disposePrevious(), QRasterPaintEngine::drawCachedGlyphs(), QRasterPaintEngine::drawImage(), QRasterPaintEnginePrivate::drawImage(), QRasterPaintEngine::drawTextItem(), QGLPixmapData::ensureCreated(), expblur(), QGLTextureGlyphCache::fillTexture(), QBlittablePixmapData::fromImage(), QX11PixmapData::fromImage(), QGtkPainter::getIcon(), grayscale(), QFontEngineMac::imageForGlyph(), QMeeGoPixmapData::imageToEGLSharedImage(), QBBBuffer::invalidateInCache(), QFontEngineQPF::loadGlyph(), operator==(), QRasterBuffer::prepare(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QTestLiteStaticInfoPrivate::qimageFromXImage(), QMacCGContext::QMacCGContext(), qt_mac_cg_context(), qt_mac_create_iconref(), qt_mac_image_to_cgimage(), qt_read_dibv5(), qt_x11_drawImage(), QVNCDirtyMap::QVNCDirtyMap(), QPixmap::qwsBits(), QTiffHandler::read(), read_dib_body(), QPngHandlerPrivate::readPngImage(), rotate_right_mirror_horizontal(), rotate_right_mirror_vertical(), rotated270(), rotated90(), QAhiScreenCursor::set(), QMacStyle::styleHint(), QWaylandReadbackGlxContext::swapBuffers(), QWaylandReadbackEglContext::swapBuffers(), swapPixel01(), QNativeImage::systemFormat(), QX11PixmapData::takeQImageFromXImage(), transformed(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     if (!d)
         return 0;
     detach();
     // In case detach ran out of memory...
     if (!d)
         return 0;
     return d->data;
 }
bits() [2/2]
const uchar * QImage::bits () const
Note that QImage uses Implicit Data Sharing {implicit data sharing}, but this function does not perform a deep copy of the shared pixel data, because the returned data is const.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1969 of file qimage.cpp.
 {
     return d ? d->data : 0;
 }
byteCount()
int QImage::byteCount () const
Returns the number of bytes occupied by the image data.
Since
4.6
See also
bytesPerLine(), bits(), {QImage::Image Information}{Image Information}
Definition at line 1800 of file qimage.cpp.
Referenced by QVolatileImage::byteCount(), QDirectFBScreen::createDFBSurface(), QGIFFormat::decode(), QVGPaintEngine::drawImage(), QBlittablePixmapData::fromImage(), QX11PixmapData::fromImage(), QFontEngineQPF::loadGlyph(), qstring_to_xtp(), qt_mac_createCGImageFromQImage(), QItemDelegate::selected(), swapPixel01(), transformed(), and QWaylandShmBuffer::~QWaylandShmBuffer().
 {
     return d ? d->nbytes : 0;
 }
bytesPerLine()
int QImage::bytesPerLine () const
Returns the number of bytes per image scanline.
This is equivalent to byteCount() / height().
See also
scanLine()
Definition at line 1812 of file qimage.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QFontEngineXLFD::addOutlineToPath(), QAlphaWidget::alphaBlend(), QProxyFontEngine::alphaMapForGlyph(), QAhiScreen::blit(), blit180(), blit270(), blit90(), blit_template(), QWindowSurface::buffer(), QVolatileImage::bytesPerLine(), QProxyFontEngine::canRender(), checkForAlphaPixels(), convolute(), copy(), QVolatileImage::copyFrom(), QX11PixmapData::createBitmapFromImage(), QXlibCursor::createCursorBitmap(), QDirectFBScreen::createDFBSurface(), createMaskFromColor(), QGIFFormat::decode(), QWSDisplay::defineCursor(), QRasterPaintEngine::drawCachedGlyphs(), QVGCompositionHelper::drawCursorPixmap(), QPSPrintEnginePrivate::drawImage(), QVGPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QRasterPaintEnginePrivate::drawImage(), drawImageTiled(), QRasterPaintEngine::drawTextItem(), expblur(), QGLTextureGlyphCache::fillTexture(), QXlibWindowSurface::flush(), QRasterWindowSurface::flush(), QVGFontEngineCleaner::fontEngineDestroyed(), QBlittablePixmapData::fromImage(), QMacPixmapData::fromImage(), QWindowSurface::grabWidget(), QVNCIntegration::grabWindow(), QFontEngineMac::imageForGlyph(), QMeeGoPixmapData::imageToEGLSharedImage(), QBBBuffer::invalidateInCache(), QVNCScreen::linestep(), QFontEngineQPF::loadGlyph(), QPixmapData::mask(), QRasterBuffer::prepare(), QRasterWindowSurface::prepareBuffer(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), QImageScale::qimageCalcScaleInfo(), QMacCGContext::QMacCGContext(), qSmoothScaleImage(), qt_halfScaled(), qt_mac_cg_context(), qt_mac_create_iconref(), qt_mac_createCGImageFromQImage(), qt_mac_image_to_cgimage(), qt_mac_read_fontsmoothing_settings(), qt_read_dibv5(), qt_scrollRectInImage(), qt_write_dib(), qt_x11_drawImage(), QVNCDirtyMap::QVNCDirtyMap(), QPixmap::qwsBytesPerLine(), ICOReader::read16_24_32BMP(), ICOReader::read1BitBMP(), ICOReader::read8BitBMP(), read_dib_body(), QPngHandlerPrivate::readPngImage(), rotated270(), rotated90(), QAhiScreenCursor::set(), QRasterPixmapData::setMask(), QPixmapData::setMask(), QMacStyle::styleHint(), QNativeImage::systemFormat(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), toVGImage(), toVGImageSubRect(), QPixmap::toWinHICON(), transformed(), QBmpHandler::write(), QRfbRawEncoder::write(), QRfbHextileEncoder< SRC >::write(), and write_pbm_image().
 {
     return (d && d->height) ? d->nbytes / d->height : 0;
 }
cacheKey()
qint64 QImage::cacheKey () const
Returns a number that identifies the contents of this QImage object.
Distinct QImage objects can only have the same key if they refer to the same contents.
The key will change when the image is altered.
Definition at line 6282 of file qimage.cpp.
Referenced by detach(), QPdfEngine::drawImage(), QTextHtmlExporter::emitBackgroundAttribute(), QDirectFBScreen::exposeRegion(), QDirectFBPaintEnginePrivate::getSurface(), operator<<(), and qt_image_id().
 {
     if (!d)
         return 0;
     else
         return (((qint64) d->ser_no) << 32) | ((qint64) d->detach_no);
 }
color()
QRgb QImage::color (int i) const
Returns the color in the color table at index i.
The first color is at index 0.
The colors in an image's color table are specified as ARGB quadruplets (QRgb). Use the qAlpha(), qRed(), qGreen(), and qBlue() functions to get the color value components.
See also
setColor(), pixelIndex(), {QImage::Pixel Manipulation}{Pixel Manipulation}
Definition at line 1829 of file qimage.cpp.
Referenced by compressHelper(), create32BitCursor(), QX11PixmapData::createBitmapFromImage(), QRasterPixmapData::fill(), QVGPixmapData::fill(), QMacPixmapData::fromImage(), QBitmap::fromImage(), QX11PixmapData::fromImage(), get_index(), QDirectFBScreen::getSurfaceDescription(), makeBitmapCompliantIfNeeded(), read_dib_body(), QGtkStyle::standardPixmap(), swapPixel01(), write_pbm_image(), write_xbm_image(), and QPNGImageWriter::writeImage().
 {
     Q_ASSERT(i < colorCount());
     return d ? d->colortable.at(i) : QRgb(uint(-1));
 }
colorCount()
int QImage::colorCount () const
Returns the size of the color table for the image.
Since
4.6
Notice that colorCount() returns 0 for 32-bpp images because these images do not use color tables, but instead encode pixel values as ARGB quadruplets.
See also
setColorCount(), {QImage::Image Information}{Image Information}
Definition at line 1656 of file qimage.cpp.
Referenced by allGray(), color(), QPixmap::colorCount(), create32BitCursor(), QDirectFBScreen::createDFBSurface(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), get_index(), QDirectFBScreen::getSurfaceDescription(), isGrayscale(), QDirectFBPaintDevice::metric(), QImage(), qt_write_dib(), QPngHandlerPrivate::readPngImage(), rotated270(), rotated90(), setColorCount(), swapPixel01(), QBmpHandler::write(), write_jpeg_image(), write_pbm_image(), and QPNGImageWriter::writeImage().
 {
     return d ? d->colortable.size() : 0;
 }
colorTable()
QVector< QRgb > QImage::colorTable () const
Returns a list of the colors contained in the image's color table, or an empty list if the image does not have a color table.
See also
setColorTable(), colorCount(), color()
Definition at line 1770 of file qimage.cpp.
Referenced by QPdfEnginePrivate::addImage(), QFontEngine::alphaRGBMapForGlyph(), QPixmap::clut(), convert_Indexed8_to_X32(), convert_Mono_to_X32(), fix_color_table(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QRasterBuffer::prepare(), QGLPixmapDropShadowFilter::processGL(), qt_write_dib(), rotated270(), rotated90(), QTiffHandler::write(), write_jpeg_image(), and write_pbm_image().
 {
     return d ? d->colortable : QVector<QRgb>();
 }
constBits()
const uchar * QImage::constBits () const
Returns a pointer to the first pixel data.
Note that QImage uses Implicit Data Sharing {implicit data sharing}, but this function does not perform a deep copy of the shared pixel data, because the returned data is const.
See also
bits(), constScanLine()
Since
4.7
Definition at line 1985 of file qimage.cpp.
Referenced by QVolatileImage::constBits(), QVGCompositionHelper::drawCursorPixmap(), QVGPaintEngine::drawImage(), drawImageTiled(), QGLTextureGlyphCache::fillTexture(), QVGFontEngineCleaner::fontEngineDestroyed(), toVGImage(), toVGImageSubRect(), and QWaylandShmBuffer::~QWaylandShmBuffer().
 {
     return d ? d->data : 0;
 }
constScanLine()
const uchar * QImage::constScanLine (int i) const
Returns a pointer to the pixel data at the scanline with index i.
The first scanline is at index 0.
The scanline data is aligned on a 32-bit boundary.
Note that QImage uses Implicit Data Sharing {implicit data sharing}, but this function does not perform a deep copy of the shared pixel data, because the returned data is const.
See also
scanLine(), constBits()
Since
4.7
Definition at line 1926 of file qimage.cpp.
Referenced by colorizeBitmap(), rgbSwapped(), write_jpeg_image(), and QPNGImageWriter::writeImage().
 {
     if (!d)
         return 0;
     Q_ASSERT(i >= 0 && i < height());
     return d->data + i * d->bytes_per_line;
 }
convertToFormat() [1/2]
QImage QImage::convertToFormat (Format format, Qt::ImageConversionFlags flags = Qt::AutoColor) const
Returns a copy of the image in the given format.
The specified image conversion flags control how the image data is handled during the conversion process.
See also
{QImage::Image Format}{Image Format}
Definition at line 3966 of file qimage.cpp.
Referenced by QPdfEnginePrivate::addImage(), QFontEngineXLFD::addOutlineToPath(), alphaChannel(), QFontEngineXLFD::alphaMapForGlyph(), QFontEngine::alphaMapForGlyph(), QFontEngineDirectWrite::alphaRGBMapForGlyph(), QFontEngineWin::alphaRGBMapForGlyph(), QAhiScreen::blit(), QRasterBuffer::colorizeBitmap(), colorizeBitmap(), QWindowsMimeImage::convertFromMime(), convertToFormat(), convolute(), create32BitCursor(), createAlphaMask(), QX11PixmapData::createBitmapFromImage(), QXlibCursor::createCursorBitmap(), QDirectFBScreen::createDFBSurface(), createHeuristicMask(), createImageNode(), QPixmap::createMaskFromColor(), QRasterPixmapData::createPixmapForImage(), QVGPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), darkenPixmap(), QWSDisplay::defineCursor(), QPixmapColorizeFilter::draw(), QVGCompositionHelper::drawCursorPixmap(), QPSPrintEnginePrivate::drawImage(), QPSPrintEngine::drawImageInternal(), QGLPixmapData::ensureCreated(), QVolatileImageData::ensureFormat(), QGLTextureGlyphCache::fillTexture(), QImageTextureGlyphCache::fillTexture(), QVGFontEngineCleaner::fontEngineDestroyed(), QBlittablePixmapData::fromImage(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QBitmap::fromImage(), QX11PixmapData::fromImage(), QWindowsMobileStyle::generatedIconPixmap(), QCommonStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), QFontEngineQPF::loadGlyph(), makeBitmapCompliantIfNeeded(), QPixmapData::mask(), operator>>(), QCursor::QCursor(), qstring_to_xtp(), qt_blurImage(), qt_createIconMask(), qt_halfScaled(), qt_mac_createCGImageFromQImage(), qt_write_dib(), qt_write_dibv5(), QItemDelegate::selected(), QVNCCursor::sendClientCursor(), QAhiScreenCursor::set(), QScreenCursor::set(), QDirectFBScreenCursor::set(), setAlphaChannel(), QRasterPixmapData::setMask(), QPixmapData::setMask(), QCursor::setPos(), smoothScaled(), QCommonStyle::standardPixmap(), toVGImage(), toVGImageSubRect(), QPixmap::toWinHBITMAP(), QTiffHandler::write(), QBmpHandler::write(), QVNCClientCursor::write(), ICOReader::write(), write_jpeg_image(), write_pbm_image(), write_xbm_image(), write_xpm_image(), QMngHandlerPrivate::writeImage(), QPNGImageWriter::writeImage(), and QX11Data::xdndMimeDataForAtom().
 {
     if (!d || d->format == format)
         return *this;
     if (format == Format_Invalid || d->format == Format_Invalid)
         return QImage();
     const Image_Converter *converterPtr = &converter_map[d->format][format];
     Image_Converter converter = *converterPtr;
     if (converter) {
         QImage image(d->width, d->height, format);
         QIMAGE_SANITYCHECK_MEMORY(image);
         image.setDotsPerMeterY(dotsPerMeterY());
         image.setDotsPerMeterX(dotsPerMeterX());
 #if !defined(QT_NO_IMAGE_TEXT)
         image.d->text = d->text;
 #endif // !QT_NO_IMAGE_TEXT
         converter(image.d, d, flags);
         return image;
     }
     Q_ASSERT(format != QImage::Format_ARGB32);
     Q_ASSERT(d->format != QImage::Format_ARGB32);
     QImage image = convertToFormat(Format_ARGB32, flags);
     return image.convertToFormat(format, flags);
 }
convertToFormat() [2/2]
QImage QImage::convertToFormat (Format format, const QVector< QRgb > & colorTable, Qt::ImageConversionFlags flags = Qt::AutoColor) const
Returns a copy of the image converted to the given format, using the specified colorTable.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Conversion from 32 bit to 8 bit indexed is a slow operation and will use a straightforward nearest color approach, with no dithering.
Definition at line 4095 of file qimage.cpp.
 {
     if (d->format == format)
         return *this;
     if (format <= QImage::Format_Indexed8 && depth() == 32) {
         return convertWithPalette(*this, format, colorTable);
     }
     const Image_Converter *converterPtr = &converter_map[d->format][format];
     Image_Converter converter = *converterPtr;
     if (!converter)
         return QImage();
     QImage image(d->width, d->height, format);
     QIMAGE_SANITYCHECK_MEMORY(image);
 #if !defined(QT_NO_IMAGE_TEXT)
         image.d->text = d->text;
 #endif // !QT_NO_IMAGE_TEXT
     converter(image.d, d, flags);
     return image;
 }
copy() [1/2]
QImage QImage::copy (const QRect & rectangle = QRect()) const
Returns a sub-area of the image as a new image.
The returned image is copied from the position ({rectangle}.x(), {rectangle}.y()) in this image, and will always have the size of the given rectangle.
In areas beyond this image, pixels are set to 0. For 32-bit RGB images, this means black; for 32-bit ARGB images, this means transparent black; for 8-bit images, this means the color with index 0 in the color table which can be anything; for 1-bit images, this means Qt::color0.
If the given rectangle is a null rectangle the entire image is copied.
See also
QImage()
Definition at line 1410 of file qimage.cpp.
Referenced by QGLWindowSurface::buffer(), QMeeGoRasterPixmapData::copy(), QRasterPixmapData::copy(), QX11PixmapData::copy(), create32BitCursor(), QWSCursor::createDropShadow(), detach(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QPSPrintEngine::drawImage(), QPdfEngine::drawImage(), QPaintEngine::drawImage(), QXlibScreen::grabWindow(), operator=(), QImage(), QTestLiteStaticInfoPrivate::qimageFromXImage(), qpaintbuffer_storable_image(), qt_x11_drawImage(), QVNCDirtyMap::QVNCDirtyMap(), QImageReader::read(), rgbSwapped(), QAlphaWidget::run(), QBlittablePixmapData::toImage(), QDirectFBPixmapData::toImage(), QRasterPixmapData::toImage(), QVolatileImage::toImage(), QPixmapData::toImage(), QX11PixmapData::toImage(), QGLPixmapData::toImage(), QTiffHandler::write(), QRfbRawEncoder::write(), QRfbHextileEncoder< SRC >::write(), write_jpeg_image(), and QPNGImageWriter::writeImage().
 {
     if (!d)
         return QImage();
     if (r.isNull()) {
         QImage image(d->width, d->height, d->format);
         if (image.isNull())
             return image;
         // Qt for Embedded Linux can create images with non-default bpl
         // make sure we don't crash.
         if (image.d->nbytes != d->nbytes) {
             int bpl = qMin(bytesPerLine(), image.bytesPerLine());
             for (int i = 0; i < height(); i++)
                 memcpy(image.scanLine(i), scanLine(i), bpl);
         } else
             memcpy(image.bits(), bits(), d->nbytes);
         image.d->colortable = d->colortable;
         image.d->dpmx = d->dpmx;
         image.d->dpmy = d->dpmy;
         image.d->offset = d->offset;
         image.d->has_alpha_clut = d->has_alpha_clut;
 #ifndef QT_NO_IMAGE_TEXT
         image.d->text = d->text;
 #endif
         return image;
     }
     int x = r.x();
     int y = r.y();
     int w = r.width();
     int h = r.height();
     int dx = 0;
     int dy = 0;
     if (w <= 0 || h <= 0)
         return QImage();
     QImage image(w, h, d->format);
     if (image.isNull())
         return image;
     if (x < 0 || y < 0 || x + w > d->width || y + h > d->height) {
         // bitBlt will not cover entire image - clear it.
         image.fill(0);
         if (x < 0) {
             dx = -x;
             x = 0;
         }
         if (y < 0) {
             dy = -y;
             y = 0;
         }
     }
     image.d->colortable = d->colortable;
     int pixels_to_copy = qMax(w - dx, 0);
     if (x > d->width)
         pixels_to_copy = 0;
     else if (pixels_to_copy > d->width - x)
         pixels_to_copy = d->width - x;
     int lines_to_copy = qMax(h - dy, 0);
     if (y > d->height)
         lines_to_copy = 0;
     else if (lines_to_copy > d->height - y)
         lines_to_copy = d->height - y;
     bool byteAligned = true;
     if (d->format == Format_Mono || d->format == Format_MonoLSB)
         byteAligned = !(dx & 7) && !(x & 7) && !(pixels_to_copy & 7);
     if (byteAligned) {
         const uchar *src = d->data + ((x * d->depth) >> 3) + y * d->bytes_per_line;
         uchar *dest = image.d->data + ((dx * d->depth) >> 3) + dy * image.d->bytes_per_line;
         const int bytes_to_copy = (pixels_to_copy * d->depth) >> 3;
         for (int i = 0; i < lines_to_copy; ++i) {
             memcpy(dest, src, bytes_to_copy);
             src += d->bytes_per_line;
             dest += image.d->bytes_per_line;
         }
     } else if (d->format == Format_Mono) {
         const uchar *src = d->data + y * d->bytes_per_line;
         uchar *dest = image.d->data + dy * image.d->bytes_per_line;
         for (int i = 0; i < lines_to_copy; ++i) {
             for (int j = 0; j < pixels_to_copy; ++j) {
                 if (src[(x + j) >> 3] & (0x80 >> ((x + j) & 7)))
                     dest[(dx + j) >> 3] |= (0x80 >> ((dx + j) & 7));
                 else
                     dest[(dx + j) >> 3] &= ~(0x80 >> ((dx + j) & 7));
             }
             src += d->bytes_per_line;
             dest += image.d->bytes_per_line;
         }
     } else { // Format_MonoLSB
         Q_ASSERT(d->format == Format_MonoLSB);
         const uchar *src = d->data + y * d->bytes_per_line;
         uchar *dest = image.d->data + dy * image.d->bytes_per_line;
         for (int i = 0; i < lines_to_copy; ++i) {
             for (int j = 0; j < pixels_to_copy; ++j) {
                 if (src[(x + j) >> 3] & (0x1 << ((x + j) & 7)))
                     dest[(dx + j) >> 3] |= (0x1 << ((dx + j) & 7));
                 else
                     dest[(dx + j) >> 3] &= ~(0x1 << ((dx + j) & 7));
             }
             src += d->bytes_per_line;
             dest += image.d->bytes_per_line;
         }
     }
     image.d->dpmx = dotsPerMeterX();
     image.d->dpmy = dotsPerMeterY();
     image.d->offset = offset();
     image.d->has_alpha_clut = d->has_alpha_clut;
 #ifndef QT_NO_IMAGE_TEXT
     image.d->text = d->text;
 #endif
     return image;
 }
copy() [2/2]
QImage QImage::copy (int x, int y, int width, int height) const inline
The returned image is copied from the position (x, y) in this image, and will always have the given width and height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
In areas beyond this image, pixels are set to 0.
Definition at line 160 of file qimage.h.
         { return copy(QRect(x, y, w, h)); }
createAlphaMask()
QImage QImage::createAlphaMask (Qt::ImageConversionFlags flags = Qt::AutoColor) const
Builds and returns a 1-bpp mask from the alpha buffer in this image.
Returns a null image if the image's format is QImage::Format_RGB32.
The flags argument is a bitwise-OR of the Qt::ImageConversionFlags, and controls the conversion process. Passing 0 for flags sets all the default options.
The returned image has little-endian bit order (i.e. the image's format is QImage::Format_MonoLSB), which you can convert to big-endian (QImage::Format_Mono) using the convertToFormat() function.
See also
createHeuristicMask(), {QImage::Image Transformations}{Image Transformations}
Definition at line 4720 of file qimage.cpp.
Referenced by createAlphaMask(), QPSPrintEngine::drawImageInternal(), QX11PixmapData::fromImage(), QFileSystemModel::headerData(), QCursor::QCursor(), QVNCCursor::sendClientCursor(), QVNCClientCursor::write(), and ICOReader::write().
 {
     if (!d || d->format == QImage::Format_RGB32)
         return QImage();
     if (d->depth == 1) {
         // A monochrome pixmap, with alpha channels on those two colors.
         // Pretty unlikely, so use less efficient solution.
         return convertToFormat(Format_Indexed8, flags).createAlphaMask(flags);
     }
     QImage mask(d->width, d->height, Format_MonoLSB);
     if (!mask.isNull())
         dither_to_Mono(mask.d, d, flags, true);
     return mask;
 }
createHeuristicMask()
QImage QImage::createHeuristicMask (bool clipTight = true) const
Creates and returns a 1-bpp heuristic mask for this image.
The function works by selecting a color from one of the corners, then chipping away pixels of that color starting at all the edges. The four corners vote for which color is to be masked away. In case of a draw (this generally means that this function is not applicable to the image), the result is arbitrary.
The returned image has little-endian bit order (i.e. the image's format is QImage::Format_MonoLSB), which you can convert to big-endian (QImage::Format_Mono) using the convertToFormat() function.
If clipTight is true (the default) the mask is just large enough to cover the pixels; otherwise, the mask is larger than the data pixels.
Note that this function disregards the alpha buffer.
See also
createAlphaMask(), {QImage::Image Transformations}{Image Transformations}
Definition at line 4762 of file qimage.cpp.
Referenced by createHeuristicMask().
 {
     if (!d)
         return QImage();
     if (d->depth != 32) {
         QImage img32 = convertToFormat(Format_RGB32);
         return img32.createHeuristicMask(clipTight);
     }
 #define PIX(x,y)  (*((QRgb*)scanLine(y)+x) & 0x00ffffff)
     int w = width();
     int h = height();
     QImage m(w, h, Format_MonoLSB);
     QIMAGE_SANITYCHECK_MEMORY(m);
     m.setColorCount(2);
     m.setColor(0, QColor(Qt::color0).rgba());
     m.setColor(1, QColor(Qt::color1).rgba());
     m.fill(0xff);
     QRgb background = PIX(0,0);
     if (background != PIX(w-1,0) &&
          background != PIX(0,h-1) &&
          background != PIX(w-1,h-1)) {
         background = PIX(w-1,0);
         if (background != PIX(w-1,h-1) &&
              background != PIX(0,h-1) &&
              PIX(0,h-1) == PIX(w-1,h-1)) {
             background = PIX(w-1,h-1);
         }
     }
     int x,y;
     bool done = false;
     uchar *ypp, *ypc, *ypn;
     while(!done) {
         done = true;
         ypn = m.scanLine(0);
         ypc = 0;
         for (y = 0; y < h; y++) {
             ypp = ypc;
             ypc = ypn;
             ypn = (y == h-1) ? 0 : m.scanLine(y+1);
             QRgb *p = (QRgb *)scanLine(y);
             for (x = 0; x < w; x++) {
                 // slowness here - it's possible to do six of these tests
                 // together in one go. oh well.
                 if ((x == 0 || y == 0 || x == w-1 || y == h-1 ||
                        !(*(ypc + ((x-1) >> 3)) & (1 << ((x-1) & 7))) ||
                        !(*(ypc + ((x+1) >> 3)) & (1 << ((x+1) & 7))) ||
                        !(*(ypp + (x     >> 3)) & (1 << (x     & 7))) ||
                        !(*(ypn + (x     >> 3)) & (1 << (x     & 7)))) &&
                      (       (*(ypc + (x     >> 3)) & (1 << (x     & 7)))) &&
                      ((*p & 0x00ffffff) == background)) {
                     done = false;
                     *(ypc + (x >> 3)) &= ~(1 << (x & 7));
                 }
                 p++;
             }
         }
     }
     if (!clipTight) {
         ypn = m.scanLine(0);
         ypc = 0;
         for (y = 0; y < h; y++) {
             ypp = ypc;
             ypc = ypn;
             ypn = (y == h-1) ? 0 : m.scanLine(y+1);
             QRgb *p = (QRgb *)scanLine(y);
             for (x = 0; x < w; x++) {
                 if ((*p & 0x00ffffff) != background) {
                     if (x > 0)
                         *(ypc + ((x-1) >> 3)) |= (1 << ((x-1) & 7));
                     if (x < w-1)
                         *(ypc + ((x+1) >> 3)) |= (1 << ((x+1) & 7));
                     if (y > 0)
                         *(ypp + (x >> 3)) |= (1 << (x & 7));
                     if (y < h-1)
                         *(ypn + (x >> 3)) |= (1 << (x & 7));
                 }
                 p++;
             }
         }
     }
 #undef PIX
     return m;
 }
createMaskFromColor()
QImage QImage::createMaskFromColor (QRgb color, Qt::MaskMode mode = Qt::MaskInColor) const
Creates and returns a mask for this image based on the given color value.
If the mode is MaskInColor (the default value), all pixels matching color will be opaque pixels in the mask. If mode is MaskOutColor, all pixels matching the given color will be transparent.
See also
createAlphaMask(), createHeuristicMask()
Definition at line 4865 of file qimage.cpp.
Referenced by QPixmap::createMaskFromColor().
 {
     if (!d)
         return QImage();
     QImage maskImage(size(), QImage::Format_MonoLSB);
     QIMAGE_SANITYCHECK_MEMORY(maskImage);
     maskImage.fill(0);
     uchar *s = maskImage.bits();
     if (depth() == 32) {
         for (int h = 0; h < d->height; h++) {
             const uint *sl = (uint *) scanLine(h);
             for (int w = 0; w < d->width; w++) {
                 if (sl[w] == color)
                     *(s + (w >> 3)) |= (1 << (w & 7));
             }
             s += maskImage.bytesPerLine();
         }
     } else {
         for (int h = 0; h < d->height; h++) {
             for (int w = 0; w < d->width; w++) {
                 if ((uint) pixel(w, h) == color)
                     *(s + (w >> 3)) |= (1 << (w & 7));
             }
             s += maskImage.bytesPerLine();
         }
     }
     if  (mode == Qt::MaskOutColor)
         maskImage.invertPixels();
     return maskImage;
 }
data_ptr()
DataPtr & QImage::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 346 of file qimage.h.
Referenced by QMeeGoGraphicsSystem::createPixmapData(), QVGPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QVGPixmapData::idealFormat(), QMeeGoGraphicsSystem::pixmapDataFromEGLSharedImage(), and QX11PixmapData::takeQImageFromXImage().
 { return d; }
depth()
int QImage::depth () const
Returns the depth of the image.
The image depth is the number of bits used to store a single pixel, also called bits per pixel (bpp).
The supported depths are 1, 8, 16, 24 and 32.
See also
bitPlaneCount(), convertToFormat(), {QImage::Image Formats}{Image Formats}, {QImage::Image Information}{Image Information}
Definition at line 1620 of file qimage.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QPdfEnginePrivate::addImage(), QAlphaWidget::alphaBlend(), QFontEngine::alphaMapForGlyph(), QFontEngineDirectWrite::alphaRGBMapForGlyph(), QFontEngineWin::alphaRGBMapForGlyph(), QPainter::begin(), QTransformedScreen::blit(), QWindowSurface::buffer(), QVGPaintEngine::canVgWritePixels(), QRasterBuffer::colorizeBitmap(), compressHelper(), convert_indexed8_to_ARGB_PM_inplace(), convert_indexed8_to_RGB16_inplace(), convert_indexed8_to_RGB_inplace(), convert_RGB_to_RGB16_inplace(), convertToFormat(), QImageData::create(), QDirectFBScreen::createDFBSurface(), createMaskFromColor(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QVolatileImage::depth(), QRasterPaintEngine::drawBitmap(), QRasterPaintEngine::drawCachedGlyphs(), QX11PaintEngine::drawImage(), QVGPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QRasterPaintEnginePrivate::drawImage(), QPSPrintEnginePrivate::drawImageHelper(), QPSPrintEngine::drawImageInternal(), drawImageTiled(), QRasterPaintEngine::drawPixmap(), QRasterPaintEngine::drawTextItem(), QRasterPaintEngine::drawTiledPixmap(), expblur(), QRasterPixmapData::fill(), QGLPixmapData::fill(), QImageTextureGlyphCache::fillTexture(), QRasterWindowSurface::flush(), format(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QWindowSurface::grabWidget(), QVNCIntegration::grabWindow(), QDirectFBPixmapData::hasAlphaChannel(), QVGPixmapData::idealFormat(), invertPixels(), is_brush_transparent(), isGrayscale(), QFontEngineQPF::loadGlyph(), QPixmapData::mask(), mirrored(), QRasterBuffer::prepare(), QRasterWindowSurface::prepareBuffer(), QImage(), qt_blurrow(), qt_mac_createCGImageFromQImage(), qt_mac_image_to_cgimage(), qt_scrollRectInImage(), qt_toRasterPixmap(), qt_toX11Pixmap(), qt_write_dib(), qt_x11_drawImage(), QVNCDirtyMap::QVNCDirtyMap(), read_xpm_body(), QPngHandlerPrivate::readPngImage(), QRasterPixmapData::resize(), QVNCCursor::sendClientCursor(), setColor(), QRasterPixmapData::setMask(), QPixmapData::setMask(), smoothScaled(), swapPixel01(), transformed(), QBmpHandler::write(), QVNCClientCursor::write(), QRfbRawEncoder::write(), QRfbHextileEncoder< SRC >::write(), write_pbm_image(), write_xpm_image(), and QPNGImageWriter::writeImage().
 {
     return d ? d->depth : 0;
 }
detach()
void QImage::detach ()
If multiple images share common data, this image makes a copy of the data and detaches itself from the sharing mechanism, making sure that this image is the only one referring to the data.
Warning
This function is not part of the public interface.
Nothing is done if there is just a single reference.
See also
copy(), isDetached(), {Implicit Data Sharing}
Definition at line 1359 of file qimage.cpp.
Referenced by bits(), colorCount(), QRasterPixmapData::createPixmapForImage(), QVGPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QGIFFormat::decode(), QPixmap::detach(), QRasterPixmapData::fill(), fill(), format(), QWindowSurface::grabWidget(), invertPixels(), QVolatileImageData::QVolatileImageData(), scanLine(), setAlphaChannel(), setColor(), setColorCount(), setColorTable(), setDotsPerMeterX(), setDotsPerMeterY(), setOffset(), setText(), and write_pbm_image().
 {
     if (d) {
         if (d->is_cached && d->ref == 1)
             QImagePixmapCleanupHooks::executeImageHooks(cacheKey());
         if (d->ref != 1 || d->ro_data)
             *this = copy();
         if (d)
             ++d->detach_no;
     }
 }
devType()
int QImage::devType () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 1332 of file qimage.cpp.
 {
     return QInternal::Image;
 }
dotsPerMeterX()
int QImage::dotsPerMeterX () const
Returns the number of pixels that fit horizontally in a physical meter.
Together with dotsPerMeterY(), this number defines the intended scale and aspect ratio of the image.
See also
setDotsPerMeterX(), {QImage::Image Information}{Image Information}
Definition at line 5615 of file qimage.cpp.
Referenced by convertToFormat(), copy(), qt_write_dib(), setPixel(), transformed(), QTiffHandler::write(), write_jpeg_image(), and QPNGImageWriter::writeImage().
 {
     return d ? qRound(d->dpmx) : 0;
 }
dotsPerMeterY()
int QImage::dotsPerMeterY () const
Returns the number of pixels that fit vertically in a physical meter.
Together with dotsPerMeterX(), this number defines the intended scale and aspect ratio of the image.
See also
setDotsPerMeterY(), {QImage::Image Information}{Image Information}
Definition at line 5628 of file qimage.cpp.
Referenced by convertToFormat(), copy(), qt_write_dib(), setPixel(), transformed(), QTiffHandler::write(), write_jpeg_image(), and QPNGImageWriter::writeImage().
 {
     return d ? qRound(d->dpmy) : 0;
 }
fill() [1/3]
void QImage::fill (uint pixelValue)
Fills the entire image with the given pixelValue.
If the depth of this image is 1, only the lowest bit is used. If you say fill(0), fill(2), etc., the image is filled with 0s. If you say fill(1), fill(3), etc., the image is filled with 1s. If the depth is 8, the lowest 8 bits are used and if the depth is 16 the lowest 16 bits are used.
Note: QImage::pixel() returns the color of the pixel at the given coordinates while QColor::pixel() returns the pixel value of the underlying window system (essentially an index value), so normally you will want to use QImage::pixel() to use a color from an existing image or QColor::rgb() to use a specific color.
See also
depth(), {QImage::Image Transformations}{Image Transformations}
Definition at line 2032 of file qimage.cpp.
Referenced by alphaChannel(), QFontEngine::alphaMapForGlyph(), QFontEngineBox::alphaMapForGlyph(), alphaMapFromPath(), QGLPixmapData::bind(), copy(), create32BitCursor(), createHeuristicMask(), createMaskFromColor(), QPixmapDropShadowFilter::draw(), QPainterPrivate::draw_helper(), QAlphaPaintEnginePrivate::drawAlphaImage(), QWindowsVistaStyle::drawControl(), drawEllipse_midpoint_i(), QFontEngineWin::drawGDIGlyph(), QWindowsStyle::drawPrimitive(), QBlittablePixmapData::fill(), QRasterPixmapData::fill(), QX11PixmapData::fill(), QVolatileImage::fill(), QGLPixmapData::fill(), fill(), QGLPixmapData::fillImage(), QX11PaintEnginePrivate::fillPolygon_dev(), QFileSystemModel::headerData(), QFontEngineMac::imageForGlyph(), QFontEngineDirectWrite::imageForGlyph(), QGLPixmapData::paintEngine(), QSvgIconEngine::pixmap(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), QMngHandlerPrivate::processHeader(), qt_mac_read_fontsmoothing_settings(), qt_patternForAlpha(), QSvgIOHandler::read(), QWSYellowSurface::setPermanentState(), QMacPixmapData::toImage(), toVGImageWithOpacity(), toVGImageWithOpacitySubRect(), and ICOReader::write().
 {
     if (!d)
         return;
     detach();
     // In case detach() ran out of memory
     if (!d)
         return;
     if (d->depth == 1 || d->depth == 8) {
         int w = d->width;
         if (d->depth == 1) {
             if (pixel & 1)
                 pixel = 0xffffffff;
             else
                 pixel = 0;
             w = (w + 7) / 8;
         } else {
             pixel &= 0xff;
         }
         qt_rectfill<quint8>(d->data, pixel, 0, 0,
                             w, d->height, d->bytes_per_line);
         return;
     } else if (d->depth == 16) {
         qt_rectfill<quint16>(reinterpret_cast<quint16*>(d->data), pixel,
                              0, 0, d->width, d->height, d->bytes_per_line);
         return;
     } else if (d->depth == 24) {
         qt_rectfill<quint24>(reinterpret_cast<quint24*>(d->data), pixel,
                              0, 0, d->width, d->height, d->bytes_per_line);
         return;
     }
     if (d->format == Format_RGB32)
         pixel |= 0xff000000;
     qt_rectfill<uint>(reinterpret_cast<uint*>(d->data), pixel,
                       0, 0, d->width, d->height, d->bytes_per_line);
 }
fill() [2/3]
void QImage::fill (const QColor & color)
Fills the entire image with the given color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the depth of the image is 1, the image will be filled with 1 if color equals Qt::color1; it will otherwise be filled with 0.
If the depth of the image is 8, the image will be filled with the index corresponding the color in the color table if present; it will otherwise be filled with 0.
Since
4.8
Definition at line 2114 of file qimage.cpp.
 {
     if (!d)
         return;
     detach();
     // In case we run out of memory
     if (!d)
         return;
     if (d->depth == 32) {
         uint pixel = color.rgba();
         if (d->format == QImage::Format_ARGB32_Premultiplied)
             pixel = PREMUL(pixel);
         fill((uint) pixel);
     } else if (d->depth == 16 && d->format == QImage::Format_RGB16) {
         qrgb565 p(color.rgba());
         fill((uint) p.rawValue());
     } else if (d->depth == 1) {
         if (color == Qt::color1)
             fill((uint) 1);
         else
             fill((uint) 0);
     } else if (d->depth == 8) {
         uint pixel = 0;
         for (int i=0; i<d->colortable.size(); ++i) {
             if (color.rgba() == d->colortable.at(i)) {
                 pixel = i;
                 break;
             }
         }
         fill(pixel);
     } else {
         QPainter p(this);
         p.setCompositionMode(QPainter::CompositionMode_Source);
         p.fillRect(rect(), color);
     }
 }
fill() [3/3]
void QImage::fill (Qt::GlobalColor color)
Fills the image with the given color, described as a standard global color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.8
Definition at line 2087 of file qimage.cpp.
 {
     fill(QColor(color));
 }
format()
QImage::Format QImage::format () const
Returns the format of the image.
See also
{QImage::Image Formats}{Image Formats}
Definition at line 2305 of file qimage.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QPdfEnginePrivate::addImage(), QFontEngineWin::alphaMapForGlyph(), QPainter::begin(), QRasterWindowSurface::beginPaint(), QAhiScreen::blit(), QTransformedScreen::blit(), blit_template(), QWindowSurface::buffer(), QProxyFontEngine::canRender(), QVGPaintEngine::canVgWritePixels(), checkForAlphaPixels(), compressHelper(), QWindowsMimeImage::convertFromMime(), QImageData::convertInPlace(), convertToFormat(), convertWithPalette(), convolute(), QImageData::create(), QDirectFBScreen::createDFBSurface(), createImageNode(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QPixmapColorizeFilter::draw(), QRasterPaintEngine::drawBitmap(), QDirectFBPaintEngine::drawImage(), QPSPrintEnginePrivate::drawImage(), QX11PaintEngine::drawImage(), QVGPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QPSPrintEngine::drawImageInternal(), drawImageTiled(), QVolatileImageData::ensureFormat(), ensureValidImage(), expblur(), QDirectFBScreen::exposeRegion(), QRasterPixmapData::fill(), QGLTextureGlyphCache::fillTexture(), QRasterWindowSurface::flush(), QVGFontEngineCleaner::fontEngineDestroyed(), QVolatileImage::format(), QBlittablePixmapData::fromImage(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QDirectFBPaintEnginePrivate::getSurface(), QWindowSurface::grabWidget(), QVNCIntegration::grabWindow(), QWSMemorySurface::isValid(), QFontEngineQPF::loadGlyph(), mirrored(), QWSLocalMemSurface::permanentState(), QWSSharedMemSurface::permanentState(), QMeeGoGraphicsSystem::pixmapDataFromEGLSharedImage(), QRasterBuffer::prepare(), qSmoothScaleImage(), qt_bitmapToRegion(), qt_blurImage(), qt_blurrow(), qt_halfScaled(), qt_mac_createCGImageFromQImage(), qt_read_dibv5(), qt_write_dib(), qt_write_dibv5(), qt_x11_drawImage(), QTiffHandler::read(), read_dib_body(), read_pbm_body(), read_xbm_body(), read_xpm_body(), QPngHandlerPrivate::readPngImage(), QMeeGoPixmapData::registerSharedImage(), rotate_right_mirror_horizontal(), rotate_right_mirror_vertical(), rotated270(), rotated90(), QAhiScreenCursor::set(), QRasterPixmapData::setMask(), QPixmapData::setMask(), setPixel(), setup_qt(), smoothScaled(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), toVGImage(), toVGImageSubRect(), transformed(), QTiffHandler::write(), QBmpHandler::write(), write_jpeg_image(), write_pbm_image(), write_xbm_image(), write_xpm_image(), and QPNGImageWriter::writeImage().
 {
     return d ? d->format : Format_Invalid;
 }
fromData() [1/2]
QImage QImage::fromData (const uchar * data, int size, const char * format = 0) static
Constructs a QImage from the first size bytes of the given binary data.
The loader attempts to read the image using the specified format. If format is not specified (which is the default), the loader probes the file for a header to guess the file format. binary data. The loader attempts to read the image, either using the optional image format specified or by determining the image format from the data.
If format is not specified (which is the default), the loader probes the file for a header to determine the file format. If format is specified, it must be one of the values returned by QImageReader::supportedImageFormats().
If the loading of the image fails, the image returned will be a null image.
See also
load(), save(), {QImage::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 5313 of file qimage.cpp.
Referenced by createImageNode(), fromData(), ICOReader::iconAt(), loadFromData(), and QInternalMimeData::retrieveData().
 {
     QByteArray a = QByteArray::fromRawData(reinterpret_cast<const char *>(data), size);
     QBuffer b;
     b.setData(a);
     b.open(QIODevice::ReadOnly);
     return QImageReader(&b, format).read();
 }
fromData() [2/2]
QImage QImage::fromData (const QByteArray & data, const char * format = 0) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Loads an image from the given QByteArray data.
Definition at line 258 of file qimage.h.
         { return fromData(reinterpret_cast<const uchar *>(data.constData()), data.size(), format); }
hasAlphaChannel()
bool QImage::hasAlphaChannel () const
Returns true if the image has a format that respects the alpha channel, otherwise returns false.
See also
{QImage::Image Information}{Image Information}
Definition at line 6495 of file qimage.cpp.
Referenced by alphaChannel(), QXcbWindowSurface::beginPaint(), QXlibWindowSurface::beginPaint(), QWindowsMimeImage::canConvertFromMime(), QRasterPaintEnginePrivate::canUseFastImageBlending(), QVGPaintEngine::canVgWritePixels(), checkForAlphaPixels(), QRasterPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), QPixmapColorizeFilter::draw(), QDirectFBPaintEngine::drawImage(), QAlphaPaintEngine::drawImage(), QGL2PaintEngineEx::drawImage(), QPSPrintEngine::drawImageInternal(), QRasterPixmapData::fill(), QWindowsMimeImage::formatsForMime(), QMeeGoPixmapData::fromEGLSharedImage(), QBlittablePixmapData::fromImage(), QMacPixmapData::fromImage(), QBlittablePixmapData::hasAlphaChannel(), QVolatileImage::hasAlphaChannel(), QRasterPixmapData::hasAlphaChannel(), QDirectFBPixmapData::hasAlphaChannel(), QVGPixmapData::idealFormat(), QMeeGoPixmapData::imageToEGLSharedImage(), QSpanData::initTexture(), QBrush::isOpaque(), smoothScaled(), transformed(), QPainterPrivate::updateEmulationSpecifier(), QVNCClientCursor::write(), and QPNGImageWriter::writeImage().
 {
     return d && (d->format == Format_ARGB32_Premultiplied
                  || d->format == Format_ARGB32
                  || d->format == Format_ARGB8565_Premultiplied
                  || d->format == Format_ARGB8555_Premultiplied
                  || d->format == Format_ARGB6666_Premultiplied
                  || d->format == Format_ARGB4444_Premultiplied
                  || (d->has_alpha_clut && (d->format == Format_Indexed8
                                            || d->format == Format_Mono
                                            || d->format == Format_MonoLSB)));
 }
height()
int QImage::height () const
Returns the height of the image.
See also
{QImage::Image Information}{Image Information}
Definition at line 1572 of file qimage.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QPdfEnginePrivate::addBrushPattern(), QPdfEnginePrivate::addImage(), QFontEngineXLFD::addOutlineToPath(), allGray(), QAlphaWidget::alphaBlend(), QProxyFontEngine::alphaMapForGlyph(), QFontEngineMac::alphaMapForGlyph(), QFontEngineDirectWrite::alphaMapForGlyph(), QFontEngineXLFD::alphaMapForGlyph(), QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QFontEngine::alphaRGBMapForGlyph(), QX11PixmapData::bitmapFromImage(), QAhiScreen::blit(), QProxyFontEngine::canRender(), checkForAlphaPixels(), colorCount(), colorizeBitmap(), compressHelper(), constScanLine(), QMacPasteboardMimeTiff::convertFromMime(), convertWithPalette(), convolute(), copy(), QImageData::create(), create32BitCursor(), QX11PixmapData::createBitmapFromImage(), QDirectFBScreen::createDFBSurface(), createHeuristicMask(), QVGPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), darkenPixmap(), QGIFFormat::decode(), QRasterPaintEngine::drawBitmap(), QCleanlooksStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QVGCompositionHelper::drawCursorPixmap(), QPdfEngine::drawImage(), QCoreGraphicsPaintEngine::drawImage(), QPSPrintEnginePrivate::drawImage(), QGL2PaintEngineEx::drawImage(), QOpenGLPaintEngine::drawImage(), QVGPaintEngine::drawImage(), QPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QRasterPaintEnginePrivate::drawImage(), QPainter::drawImage(), QPSPrintEnginePrivate::drawImageHelper(), QPSPrintEngine::drawImageInternal(), drawImageTiled(), QPdfEngine::drawPixmap(), QPlastiqueStyle::drawPrimitive(), QRasterPaintEngine::drawTextItem(), QOpenGLPaintEngine::drawTiledPixmap(), expblur(), QRasterPixmapData::fill(), QGLTextureGlyphCache::fillTexture(), QImageTextureGlyphCache::fillTexture(), QXlibWindowSurface::flush(), QRasterBuffer::flushToARGBImage(), QVGFontEngineCleaner::fontEngineDestroyed(), format(), QBlittablePixmapData::fromImage(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QWindowsMobileStyle::generatedIconPixmap(), QCommonStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), getImageSize(), QVNCIntegration::grabWindow(), grayscale(), QVolatileImage::height(), QNativeImage::height(), ICOReader::iconAt(), QFontEngineMac::imageForGlyph(), QMeeGoPixmapData::imageToEGLSharedImage(), QBBBuffer::invalidateInCache(), QFontEngineQPF::loadGlyph(), QPixmapData::mask(), operator==(), QWSLocalMemSurface::permanentState(), QWSSharedMemSurface::permanentState(), pixel(), pixelIndex(), QRasterBuffer::prepare(), QRasterWindowSurface::prepareBuffer(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), qGamma_correct_back_to_linear_cs(), qgl_byteSwapImage(), QImageScale::qimageCalcScaleInfo(), QTestLiteStaticInfoPrivate::qimageFromXImage(), QMacCGContext::QMacCGContext(), qSmoothScaleImage(), qstring_to_xtp(), QSvgImage::QSvgImage(), qt_bitmapToRegion(), qt_blurImage(), qt_createIconMask(), qt_halfScaled(), qt_mac_cg_context(), qt_mac_createCGImageFromQImage(), qt_mac_image_to_cgimage(), qt_scrollRectInImage(), qt_write_dib(), qt_write_dibv5(), ICOReader::read1BitBMP(), rotate_right_mirror_horizontal(), rotate_right_mirror_vertical(), rotated270(), rotated90(), scaled(), scaledToHeight(), scanLine(), QItemDelegate::selected(), QVNCCursor::sendClientCursor(), QAhiScreenCursor::set(), QRasterPixmapData::setMask(), QPixmapData::setMask(), setPixel(), QMacStyle::styleHint(), QX11PixmapData::takeQImageFromXImage(), toVGImage(), QPixmap::toWinHBITMAP(), transformed(), QMeeGoPixmapData::updateFromSoftImage(), QTiffHandler::write(), QBmpHandler::write(), QVNCClientCursor::write(), ICOReader::write(), write_jpeg_image(), write_pbm_image(), write_xbm_image(), write_xpm_image(), QMngHandlerPrivate::writeImage(), QPNGImageWriter::writeImage(), and QTextOdfWriter::writeInlineCharacter().
 {
     return d ? d->height : 0;
 }
invertPixels()
void QImage::invertPixels (InvertMode mode = InvertRgb)
Inverts all pixel values in the image.
Use the invertPixels() function that takes a QImage::InvertMode parameter instead.
The given invert mode only have a meaning when the image's depth is 32. The default mode is InvertRgb, which leaves the alpha channel unchanged. If the mode is InvertRgba, the alpha bits are also inverted.
Inverting an 8-bit image means to replace all pixels using color index i with a pixel using color index 255 minus i. The same is the case for a 1-bit image. Note that the color table is not changed.
See also
{QImage::Image Transformations}{Image Transformations}
Definition at line 2179 of file qimage.cpp.
Referenced by QX11PixmapData::createBitmapFromImage(), createMaskFromColor(), QImageTextureGlyphCache::fillTexture(), QBitmap::fromImage(), makeBitmapCompliantIfNeeded(), qt_createIconMask(), and toVGImage().
 {
     if (!d)
         return;
     detach();
     // In case detach() ran out of memory
     if (!d)
         return;
     if (depth() != 32) {
         // number of used bytes pr line
         int bpl = (d->width * d->depth + 7) / 8;
         int pad = d->bytes_per_line - bpl;
         uchar *sl = d->data;
         for (int y=0; y<d->height; ++y) {
             for (int x=0; x<bpl; ++x)
                 *sl++ ^= 0xff;
             sl += pad;
         }
     } else {
         quint32 *p = (quint32*)d->data;
         quint32 *end = (quint32*)(d->data + d->nbytes);
         uint xorbits = (mode == InvertRgba) ? 0xffffffff : 0x00ffffff;
         while (p < end)
             *p++ ^= xorbits;
     }
 }
isDetached()
bool QImage::isDetached () const
Returns true if the image is detached; otherwise returns false.
Warning
This function is not part of the public interface.
See also
detach(), {Implicit Data Sharing}
Definition at line 6301 of file qimage.cpp.
 {
     return d && d->ref == 1;
 }
isGrayscale()
bool QImage::isGrayscale () const
For 32-bit images, this function is equivalent to allGray().
For 8-bpp images, this function returns true if color(i) is QRgb(i, i, i) for all indexes of the color table; otherwise returns false.
See also
allGray(), {QImage::Image Formats}{Image Formats}
Definition at line 4477 of file qimage.cpp.
Referenced by setAlphaChannel().
 {
     if (!d)
         return false;
     switch (depth()) {
     case 32:
     case 24:
     case 16:
         return allGray();
     case 8: {
         for (int i = 0; i < colorCount(); i++)
             if (d->colortable.at(i) != qRgb(i,i,i))
                 return false;
         return true;
         }
     }
     return false;
 }
isNull()
bool QImage::isNull () const
Returns true if it is a null image, otherwise returns false.
A null image has all parameters set to zero and no allocated data.
Definition at line 1542 of file qimage.cpp.
Referenced by QPdfEnginePrivate::addImage(), QFontEngineXLFD::addOutlineToPath(), QPainter::begin(), QScreen::blit(), QDirectFBPixmapData::buffer(), QGLWindowSurface::buffer(), QWindowsMimeImage::canConvertFromMime(), QProxyFontEngine::canRender(), QPixmap::convertFromImage(), QWindowsMimeImage::convertFromMime(), copy(), QVolatileImage::copyFrom(), createAlphaMask(), QDirectFBScreen::createDFBSurface(), createImageNode(), createPixmapDataSync(), QVGPixmapData::createPixmapForImage(), QGIFFormat::decode(), QPdfEngine::drawImage(), QCoreGraphicsPaintEngine::drawImage(), QPSPrintEnginePrivate::drawImage(), QVGPaintEngine::drawImage(), QPainter::drawImage(), QPSPrintEnginePrivate::drawImageHelper(), QCleanlooksStyle::drawPrimitive(), QOpenGLPaintEngine::drawTiledPixmap(), QGLPixmapData::ensureCreated(), ensureValidImage(), QScreen::exposeRegion(), QRasterPixmapData::fill(), QGLPixmapData::fill(), QXlibWindowSurface::flush(), QVGFontEngineCleaner::fontEngineDestroyed(), QWindowsMimeImage::formatsForMime(), QRasterPixmapData::fromData(), QVGPixmapData::fromData(), QGLPixmapData::fromData(), QMeeGoPixmapData::fromEGLSharedImage(), QVGPixmapData::fromFile(), QPixmapData::fromFile(), QGLPixmapData::fromFile(), QBitmap::fromImage(), QVGPixmapData::fromImage(), QPixmap::fromImage(), QRasterPixmapData::fromImageReader(), QVGPixmapData::fromImageReader(), QGLPixmapData::fromImageReader(), QPixmap::fromWinHBITMAP(), QPixmap::fromWinHICON(), getImage(), getImageSize(), getPixmap(), QWindowSurface::grabWidget(), ICOReader::iconAt(), QTextCursor::insertImage(), QVolatileImage::isNull(), QWSMemorySurface::isValid(), QWSOnScreenSurface::isValid(), load(), loadFromData(), QTextDocument::loadResource(), QPixmapData::mask(), QDirectFBPaintDevice::metric(), operator<<(), operator>>(), QDeclarativePixmapReader::processJob(), QPixmap::QPixmap(), QPixmapCacheEntry::QPixmapCacheEntry(), qSmoothScaleImage(), qt_read_dibv5(), QTiffHandler::read(), QtIcoHandler::read(), QTgaHandler::read(), read_dib_body(), read_pbm_body(), read_xbm_body(), read_xpm_body(), QPngHandlerPrivate::readPngImage(), QRasterPixmapData::resize(), rgbSwapped(), QAlphaWidget::run(), save(), QMeeGoLivePixmapData::scroll(), QXcbWindowSurface::scroll(), QXlibWindowSurface::scroll(), QRasterPixmapData::scroll(), QVNCCursor::sendClientCursor(), QAhiScreenCursor::set(), QDirectFBScreenCursor::set(), setAlphaChannel(), QWSServer::setBackground(), setPixel(), QBrush::setTextureImage(), setup_qt(), QMacPixmapData::toImage(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), QGLPixmapData::toImage(), QPixmap::toWinHICON(), QVNCClientCursor::write(), and QTextOdfWriter::writeInlineCharacter().
 {
     return !d;
 }
load() [1/2]
bool QImage::load (QIODevice * device, const char * format)
This function reads a QImage from the given device.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This can, for example, be used to load an image directly into a QByteArray.
Definition at line 5251 of file qimage.cpp.
Referenced by getImage(), getPixmap(), QImage(), and QTextOdfWriter::writeInlineCharacter().
 {
     QImage image = QImageReader(device, format).read();
     if(!image.isNull()) {
         operator=(image);
         return true;
     }
     return false;
 }
load() [2/2]
bool QImage::load (const QString & fileName, const char * format = 0)
Loads an image from the file with the given fileName.
Returns true if the image was successfully loaded; otherwise returns false.
The loader attempts to read the image using the specified format, e.g., PNG or JPG. If format is not specified (which is the default), the loader probes the file for a header to guess the file format.
The file name can either refer to an actual file on disk or to one of the application's embedded resources. See the Resource System overview for details on how to embed images and other resource files in the application's executable.
See also
Reading and Writing Image Files
Definition at line 5228 of file qimage.cpp.
 {
     if (fileName.isEmpty())
         return false;
     QImage image = QImageReader(fileName, format).read();
     if (!image.isNull()) {
         operator=(image);
         return true;
     }
     return false;
 }
loadFromData() [1/2]
bool QImage::loadFromData (const uchar * data, int len, const char * format = 0)
Loads an image from the first len bytes of the given binary data.
Returns true if the image was successfully loaded; otherwise returns false.
The loader attempts to read the image using the specified format, e.g., PNG or JPG. If format is not specified (which is the default), the loader probes the file for a header to guess the file format.
See also
{QImage::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 5275 of file qimage.cpp.
Referenced by QTextHtmlParserNode::applyBackgroundImage(), QWindowsMimeImage::convertToMime(), getImage(), QTextDocument::loadResource(), and QTextOdfWriter::writeInlineCharacter().
 {
     QImage image = fromData(data, len, format);
     if (!image.isNull()) {
         operator=(image);
         return true;
     }
     return false;
 }
loadFromData() [2/2]
bool QImage::loadFromData (const QByteArray & data, const char * aformat = 0) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Loads an image from the given QByteArray data.
Definition at line 251 of file qimage.h.
         { return loadFromData(reinterpret_cast<const uchar *>(data.constData()), data.size(), aformat); }
metric()
int QImage::metric (PaintDeviceMetric metric) const protected virtual
Returns the size for the specified metric on the device.
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 5995 of file qimage.cpp.
 {
     if (!d)
         return 0;
     switch (metric) {
     case PdmWidth:
         return d->width;
         break;
     case PdmHeight:
         return d->height;
         break;
     case PdmWidthMM:
         return qRound(d->width * 1000 / d->dpmx);
         break;
     case PdmHeightMM:
         return qRound(d->height * 1000 / d->dpmy);
         break;
     case PdmNumColors:
         return d->colortable.size();
         break;
     case PdmDepth:
         return d->depth;
         break;
     case PdmDpiX:
         return qRound(d->dpmx * 0.0254);
         break;
     case PdmDpiY:
         return qRound(d->dpmy * 0.0254);
         break;
     case PdmPhysicalDpiX:
         return qRound(d->dpmx * 0.0254);
         break;
     case PdmPhysicalDpiY:
         return qRound(d->dpmy * 0.0254);
         break;
     default:
         qWarning("QImage::metric(): Unhandled metric type %d", metric);
         break;
     }
     return 0;
 }
mirrored()
QImage QImage::mirrored (bool horizontal = false, bool vertical = true) const
Returns a mirror of the image, mirrored in the horizontal and/or the vertical direction depending on whether horizontal and vertical are set to true or false.
Note that the original image is not changed.
See also
{QImage::Image Transformations}{Image Transformations}
Definition at line 4922 of file qimage.cpp.
Referenced by QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QGLPixmapData::ensureCreated(), QWindowsMobileStylePrivate::QWindowsMobileStylePrivate(), QTiffHandler::read(), rotated180(), QCommonStyle::standardPixmap(), QWaylandReadbackEglContext::swapBuffers(), QWaylandReadbackGlxContext::swapBuffers(), and transformed().
 {
     if (!d)
         return QImage();
     if ((d->width <= 1 && d->height <= 1) || (!horizontal && !vertical))
         return *this;
     int w = d->width;
     int h = d->height;
     // Create result image, copy colormap
     QImage result(d->width, d->height, d->format);
     QIMAGE_SANITYCHECK_MEMORY(result);
     // check if we ran out of of memory..
     if (!result.d)
         return QImage();
     result.d->colortable = d->colortable;
     result.d->has_alpha_clut = d->has_alpha_clut;
     if (depth() == 1)
         w = (w+7)/8;
     int dxi = horizontal ? -1 : 1;
     int dxs = horizontal ? w-1 : 0;
     int dyi = vertical ? -1 : 1;
     int dy = vertical ? h-1: 0;
     // 1 bit, 8 bit
     if (d->depth == 1 || d->depth == 8) {
         for (int sy = 0; sy < h; sy++, dy += dyi) {
             quint8* ssl = (quint8*)(d->data + sy*d->bytes_per_line);
             quint8* dsl = (quint8*)(result.d->data + dy*result.d->bytes_per_line);
             int dx = dxs;
             for (int sx = 0; sx < w; sx++, dx += dxi)
                 dsl[dx] = ssl[sx];
         }
     }
     // 16 bit
     else if (d->depth == 16) {
         for (int sy = 0; sy < h; sy++, dy += dyi) {
             quint16* ssl = (quint16*)(d->data + sy*d->bytes_per_line);
             quint16* dsl = (quint16*)(result.d->data + dy*result.d->bytes_per_line);
             int dx = dxs;
             for (int sx = 0; sx < w; sx++, dx += dxi)
                 dsl[dx] = ssl[sx];
         }
     }
     // 24 bit
     else if (d->depth == 24) {
         for (int sy = 0; sy < h; sy++, dy += dyi) {
             quint24* ssl = (quint24*)(d->data + sy*d->bytes_per_line);
             quint24* dsl = (quint24*)(result.d->data + dy*result.d->bytes_per_line);
             int dx = dxs;
             for (int sx = 0; sx < w; sx++, dx += dxi)
                 dsl[dx] = ssl[sx];
         }
     }
     // 32 bit
     else if (d->depth == 32) {
         for (int sy = 0; sy < h; sy++, dy += dyi) {
             quint32* ssl = (quint32*)(d->data + sy*d->bytes_per_line);
             quint32* dsl = (quint32*)(result.d->data + dy*result.d->bytes_per_line);
             int dx = dxs;
             for (int sx = 0; sx < w; sx++, dx += dxi)
                 dsl[dx] = ssl[sx];
         }
     }
     // special handling of 1 bit images for horizontal mirroring
     if (horizontal && d->depth == 1) {
         int shift = width() % 8;
         for (int y = h-1; y >= 0; y--) {
             quint8* a0 = (quint8*)(result.d->data + y*d->bytes_per_line);
             // Swap bytes
             quint8* a = a0+dxs;
             while (a >= a0) {
                 *a = bitflip[*a];
                 a--;
             }
             // Shift bits if unaligned
             if (shift != 0) {
                 a = a0+dxs;
                 quint8 c = 0;
                 if (format() == Format_MonoLSB) {
                     while (a >= a0) {
                         quint8 nc = *a << shift;
                         *a = (*a >> (8-shift)) | c;
                         --a;
                         c = nc;
                     }
                 } else {
                     while (a >= a0) {
                         quint8 nc = *a >> shift;
                         *a = (*a << (8-shift)) | c;
                         --a;
                         c = nc;
                     }
                 }
             }
         }
     }
     return result;
 }
numBytes()
int QImage::numBytes () const
Returns the number of bytes occupied by the image data.
See also
byteCount()
Definition at line 1785 of file qimage.cpp.
 {
     return d ? d->nbytes : 0;
 }
numColors()
int QImage::numColors () const
Returns the size of the color table for the image.
See also
setColorCount()
Definition at line 1636 of file qimage.cpp.
Referenced by convert_RGB_to_Indexed8(), format(), QMacPixmapData::fromImage(), and QImage().
 {
     return d ? d->colortable.size() : 0;
 }
offset()
QPoint QImage::offset () const
Returns the number of pixels by which the image is intended to be offset by when positioning relative to other images.
See also
setOffset(), {QImage::Image Information}{Image Information}
Definition at line 5688 of file qimage.cpp.
Referenced by copy(), and QPNGImageWriter::writeImage().
 {
     return d ? d->offset : QPoint();
 }
operator QVariant()
QImage::operator QVariant () const
Returns the image as a QVariant.
Definition at line 1340 of file qimage.cpp.
 {
     return QVariant(QVariant::Image, this);
 }
operator!=()
bool QImage::operator!= (const QImage & image) const
Returns true if this image and the given image have different contents; otherwise returns false.
The comparison can be slow, unless there is some obvious difference, such as different widths, in which case the function will return quickly.
See also
operator=()
Definition at line 5599 of file qimage.cpp.
 {
     return !(*this == i);
 }
operator=()
QImage & QImage::operator= (const QImage & image)
Assigns a shallow copy of the given image to this image and returns a reference to this image.
For more information about shallow copies, see the Implicit Data Sharing documentation.
See also
copy(), QImage()
Definition at line 1304 of file qimage.cpp.
Referenced by load(), loadFromData(), and QImage().
 {
     if (image.paintingActive()) {
         operator=(image.copy());
     } else {
         if (image.d)
             image.d->ref.ref();
         if (d && !d->ref.deref())
             delete d;
         d = image.d;
     }
     return *this;
 }
operator==()
bool QImage::operator== (const QImage & image) const
Returns true if this image and the given image have the same contents; otherwise returns false.
The comparison can be slow, unless there is some obvious difference (e.g. different size or format), in which case the function will return quickly.
See also
operator=()
Definition at line 5531 of file qimage.cpp.
 {
     // same object, or shared?
     if (i.d == d)
         return true;
     if (!i.d || !d)
         return false;
     // obviously different stuff?
     if (i.d->height != d->height || i.d->width != d->width || i.d->format != d->format)
         return false;
     if (d->format != Format_RGB32) {
         if (d->format >= Format_ARGB32) { // all bits defined
             const int n = d->width * d->depth / 8;
             if (n == d->bytes_per_line && n == i.d->bytes_per_line) {
                 if (memcmp(bits(), i.bits(), d->nbytes))
                     return false;
             } else {
                 for (int y = 0; y < d->height; ++y) {
                     if (memcmp(scanLine(y), i.scanLine(y), n))
                         return false;
                 }
             }
         } else {
             const int w = width();
             const int h = height();
             const QVector<QRgb> &colortable = d->colortable;
             const QVector<QRgb> &icolortable = i.d->colortable;
             for (int y=0; y<h; ++y) {
                 for (int x=0; x<w; ++x) {
                     if (colortable[pixelIndex(x, y)] != icolortable[i.pixelIndex(x, y)])
                         return false;
                 }
             }
         }
     } else {
         //alpha channel undefined, so we must mask it out
         for(int l = 0; l < d->height; l++) {
             int w = d->width;
             const uint *p1 = reinterpret_cast<const uint*>(scanLine(l));
             const uint *p2 = reinterpret_cast<const uint*>(i.scanLine(l));
             while (w--) {
                 if ((*p1++ & 0x00ffffff) != (*p2++ & 0x00ffffff))
                     return false;
             }
         }
     }
     return true;
 }
paintEngine()
QPaintEngine * QImage::paintEngine () const virtual
Used by QPainter to retrieve a paint engine for the image.
Warning
This function is not part of the public interface.
Implements QPaintDevice.
Definition at line 5970 of file qimage.cpp.
Referenced by QRasterPixmapData::paintEngine(), QGLPixmapData::paintEngine(), QNativeImage::QNativeImage(), and QNativeImage::systemFormat().
 {
     if (!d)
         return 0;
     if (!d->paintEngine) {
 #ifdef Q_OS_SYMBIAN
         d->paintEngine = new QSymbianRasterPaintEngine(const_cast<QImage *>(this));
 #else
         d->paintEngine = new QRasterPaintEngine(const_cast<QImage *>(this));
 #endif
     }
     return d->paintEngine;
 }
pixel() [1/2]
QRgb QImage::pixel (int x, int y) const
Returns the color of the pixel at coordinates (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4240 of file qimage.cpp.
Referenced by createMaskFromColor(), darkenPixmap(), QRasterPaintEngine::drawImage(), fill(), QWindowsMobileStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), qcolorForThemeTextColor(), rotated270(), and rotated90().
 {
     if (!d || x < 0 || x >= d->width || y < 0 || y >= height()) {
         qWarning("QImage::pixel: coordinate (%d,%d) out of range", x, y);
         return 12345;
     }
     const uchar * s = scanLine(y);
     switch(d->format) {
     case Format_Mono:
         return d->colortable.at((*(s + (x >> 3)) >> (7- (x & 7))) & 1);
     case Format_MonoLSB:
         return d->colortable.at((*(s + (x >> 3)) >> (x & 7)) & 1);
     case Format_Indexed8:
         return d->colortable.at((int)s[x]);
     case Format_ARGB8565_Premultiplied:
         return qt_colorConvert<quint32, qargb8565>(reinterpret_cast<const qargb8565*>(s)[x], 0);
     case Format_RGB666:
         return qt_colorConvert<quint32, qrgb666>(reinterpret_cast<const qrgb666*>(s)[x], 0);
     case Format_ARGB6666_Premultiplied:
         return qt_colorConvert<quint32, qargb6666>(reinterpret_cast<const qargb6666*>(s)[x], 0);
     case Format_RGB555:
         return qt_colorConvert<quint32, qrgb555>(reinterpret_cast<const qrgb555*>(s)[x], 0);
     case Format_ARGB8555_Premultiplied:
         return qt_colorConvert<quint32, qargb8555>(reinterpret_cast<const qargb8555*>(s)[x], 0);
     case Format_RGB888:
         return qt_colorConvert<quint32, qrgb888>(reinterpret_cast<const qrgb888*>(s)[x], 0);
     case Format_RGB444:
         return qt_colorConvert<quint32, qrgb444>(reinterpret_cast<const qrgb444*>(s)[x], 0);
     case Format_ARGB4444_Premultiplied:
         return qt_colorConvert<quint32, qargb4444>(reinterpret_cast<const qargb4444*>(s)[x], 0);
     case Format_RGB16:
         return qt_colorConvert<quint32, quint16>(reinterpret_cast<const quint16*>(s)[x], 0);
     default:
         return ((QRgb*)s)[x];
     }
 }
pixel() [2/2]
Q_GUI_EXPORT_INLINE QRgb QImage::pixel (const QPoint & position) const
Returns the color of the pixel at the given position.
If the position is not valid, the results are undefined.
Warning
This function is expensive when used for massive pixel manipulations.
See also
setPixel(), valid(), {QImage::Pixel Manipulation}{Pixel Manipulation}
Definition at line 356 of file qimage.h.
 { return pixel(pt.x(), pt.y()); }
pixelIndex() [1/2]
int QImage::pixelIndex (int x, int y) const
Returns the pixel index at (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4194 of file qimage.cpp.
Referenced by QWSCursor::createDropShadow(), operator==(), rotated270(), and rotated90().
 {
     if (!d || x < 0 || x >= d->width || y < 0 || y >= height()) {
         qWarning("QImage::pixelIndex: coordinate (%d,%d) out of range", x, y);
         return -12345;
     }
     const uchar * s = scanLine(y);
     switch(d->format) {
     case Format_Mono:
         return (*(s + (x >> 3)) >> (7- (x & 7))) & 1;
     case Format_MonoLSB:
         return (*(s + (x >> 3)) >> (x & 7)) & 1;
     case Format_Indexed8:
         return (int)s[x];
     default:
         qWarning("QImage::pixelIndex: Not applicable for %d-bpp images (no palette)", d->depth);
     }
     return 0;
 }
pixelIndex() [2/2]
Q_GUI_EXPORT_INLINE int QImage::pixelIndex (const QPoint & position) const
Returns the pixel index at the given position.
If position is not valid, or if the image is not a paletted image (depth() > 8), the results are undefined.
See also
valid(), depth(), {QImage::Pixel Manipulation}{Pixel Manipulation}
Definition at line 355 of file qimage.h.
 { return pixelIndex(pt.x(), pt.y());}
rect()
QRect QImage::rect () const
Returns the enclosing rectangle (0, 0, width(), height()) of the image.
See also
{QImage::Image Information}{Image Information}
Definition at line 1603 of file qimage.cpp.
Referenced by convolute(), QPixmapColorizeFilter::draw(), QWindowsVistaStyle::drawControl(), QDirectFBPaintEngine::drawImage(), QBlitterPaintEngine::drawImage(), QPdfEngine::drawImage(), QRasterPaintEngine::drawImage(), QPaintEngineEx::drawImage(), QPainter::drawImage(), QTextImageHandler::drawObject(), fill(), QRasterWindowSurface::flush(), QPlatformSoftwareCursor::getCurrentRect(), grayscale(), QGLPixmapDropShadowFilter::processGL(), QBBBuffer::rect(), and trueMatrix().
 {
     return d ? QRect(0, 0, d->width, d->height) : QRect();
 }
rgbSwapped()
QImage QImage::rgbSwapped () const
Returns a QImage in which the values of the red and blue components of all pixels have been swapped, effectively converting an RGB image to an BGR image.
The original QImage is not changed.
See also
{QImage::Image Transformations}{Image Transformations}
Definition at line 5052 of file qimage.cpp.
 {
     if (isNull())
         return *this;
     QImage res;
     switch (d->format) {
     case Format_Invalid:
     case NImageFormats:
         Q_ASSERT(false);
         break;
     case Format_Mono:
     case Format_MonoLSB:
     case Format_Indexed8:
         res = copy();
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < res.d->colortable.size(); i++) {
             QRgb c = res.d->colortable.at(i);
             res.d->colortable[i] = QRgb(((c << 16) & 0xff0000) | ((c >> 16) & 0xff) | (c & 0xff00ff00));
         }
         break;
     case Format_RGB32:
     case Format_ARGB32:
     case Format_ARGB32_Premultiplied:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             uint *q = (uint*)res.scanLine(i);
             uint *p = (uint*)constScanLine(i);
             uint *end = p + d->width;
             while (p < end) {
                 *q = ((*p << 16) & 0xff0000) | ((*p >> 16) & 0xff) | (*p & 0xff00ff00);
                 p++;
                 q++;
             }
         }
         break;
     case Format_RGB16:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             ushort *q = (ushort*)res.scanLine(i);
             const ushort *p = (const ushort*)constScanLine(i);
             const ushort *end = p + d->width;
             while (p < end) {
                 *q = ((*p << 11) & 0xf800) | ((*p >> 11) & 0x1f) | (*p & 0x07e0);
                 p++;
                 q++;
             }
         }
         break;
     case Format_ARGB8565_Premultiplied:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             const quint8 *p = constScanLine(i);
             quint8 *q = res.scanLine(i);
             const quint8 *end = p + d->width * sizeof(qargb8565);
             while (p < end) {
                 q[0] = p[0];
                 q[1] = (p[1] & 0xe0) | (p[2] >> 3);
                 q[2] = (p[2] & 0x07) | (p[1] << 3);
                 p += sizeof(qargb8565);
                 q += sizeof(qargb8565);
             }
         }
         break;
     case Format_RGB666:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             qrgb666 *q = reinterpret_cast<qrgb666*>(res.scanLine(i));
             const qrgb666 *p = reinterpret_cast<const qrgb666*>(constScanLine(i));
             const qrgb666 *end = p + d->width;
             while (p < end) {
                 const QRgb rgb = quint32(*p++);
                 *q++ = qRgb(qBlue(rgb), qGreen(rgb), qRed(rgb));
             }
         }
         break;
     case Format_ARGB6666_Premultiplied:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             const quint8 *p = constScanLine(i);
             const quint8 *end = p + d->width * sizeof(qargb6666);
             quint8 *q = res.scanLine(i);
             while (p < end) {
                 q[0] = (p[1] >> 4) | ((p[2] & 0x3) << 4) | (p[0] & 0xc0);
                 q[1] = (p[1] & 0xf) | (p[0] << 4);
                 q[2] = (p[2] & 0xfc) | ((p[0] >> 4) & 0x3);
                 p += sizeof(qargb6666);
                 q += sizeof(qargb6666);
             }
         }
         break;
     case Format_RGB555:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             quint16 *q = (quint16*)res.scanLine(i);
             const quint16 *p = (const quint16*)constScanLine(i);
             const quint16 *end = p + d->width;
             while (p < end) {
                 *q = ((*p << 10) & 0x7c00) | ((*p >> 10) & 0x1f) | (*p & 0x3e0);
                 p++;
                 q++;
             }
         }
         break;
     case Format_ARGB8555_Premultiplied:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             const quint8 *p = constScanLine(i);
             quint8 *q = res.scanLine(i);
             const quint8 *end = p + d->width * sizeof(qargb8555);
             while (p < end) {
                 q[0] = p[0];
                 q[1] = (p[1] & 0xe0) | (p[2] >> 2);
                 q[2] = (p[2] & 0x03) | ((p[1] << 2) & 0x7f);
                 p += sizeof(qargb8555);
                 q += sizeof(qargb8555);
             }
         }
         break;
     case Format_RGB888:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             quint8 *q = res.scanLine(i);
             const quint8 *p = constScanLine(i);
             const quint8 *end = p + d->width * sizeof(qrgb888);
             while (p < end) {
                 q[0] = p[2];
                 q[1] = p[1];
                 q[2] = p[0];
                 q += sizeof(qrgb888);
                 p += sizeof(qrgb888);
             }
         }
         break;
     case Format_RGB444:
     case Format_ARGB4444_Premultiplied:
         res = QImage(d->width, d->height, d->format);
         QIMAGE_SANITYCHECK_MEMORY(res);
         for (int i = 0; i < d->height; i++) {
             quint16 *q = reinterpret_cast<quint16*>(res.scanLine(i));
             const quint16 *p = reinterpret_cast<const quint16*>(constScanLine(i));
             const quint16 *end = p + d->width;
             while (p < end) {
                 *q = (*p & 0xf0f0) | ((*p & 0x0f) << 8) | ((*p & 0xf00) >> 8);
                 p++;
                 q++;
             }
         }
         break;
     }
     return res;
 }
save() [1/2]
bool QImage::save (const QString & fileName, const char * format = 0, int quality = -1) const
Saves the image to the file with the given fileName, using the given image file format and quality factor.
If format is 0, QImage will attempt to guess the format by looking at fileName's suffix.
The quality factor must be in the range 0 to 100 or -1. Specify 0 to obtain small compressed files, 100 for large uncompressed files, and -1 (the default) to use the default settings.
Returns true if the image was successfully saved; otherwise returns false.
See also
{QImage::Reading and Writing Image Files}{Reading and Writing Image Files}
Definition at line 5346 of file qimage.cpp.
Referenced by drawEllipse_midpoint_i(), QSvgPaintEngine::drawImage(), QMimeDataWrapper::encodedData(), QMinimalWindowSurface::flush(), QInternalMimeData::renderDataHelper(), and xdndObtainData().
 {
     if (isNull())
         return false;
     QImageWriter writer(fileName, format);
     return d->doImageIO(this, &writer, quality);
 }
save() [2/2]
bool QImage::save (QIODevice * device, const char * format = 0, int quality = -1) const
This function writes a QImage to the given device.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This can, for example, be used to save an image directly into a QByteArray:
        QImage image;
        QByteArray ba;
        QBuffer buffer(&ba);
        buffer.open(QIODevice::WriteOnly);
        image.save(&buffer, "PNG"); // writes image into ba in PNG format
Definition at line 5368 of file qimage.cpp.
 {
     if (isNull())
         return false;                                // nothing to save
     QImageWriter writer(device, format);
     return d->doImageIO(this, &writer, quality);
 }
scaled() [1/2]
QImage QImage::scaled (int w, int h, Qt::AspectRatioMode aspectMode = Qt::IgnoreAspectRatio, Qt::TransformationMode mode = Qt::FastTransformation) const inline
Definition at line 232 of file qimage.h.
Referenced by QGL2PaintEngineEx::drawImage(), QOpenGLPaintEngine::drawImage(), QPSPrintEngine::drawImageInternal(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QOpenGLPaintEngine::drawTiledPixmap(), QMoviePrivate::next(), qt_mac_create_iconref(), QImageReader::read(), and ICOReader::write().
         { return scaled(QSize(w, h), aspectMode, mode); }
scaled() [2/2]
QImage QImage::scaled (const QSize & s, Qt::AspectRatioMode aspectMode = Qt::IgnoreAspectRatio, Qt::TransformationMode mode = Qt::FastTransformation) const
Definition at line 4577 of file qimage.cpp.
 {
     if (!d) {
         qWarning("QImage::scaled: Image is a null image");
         return QImage();
     }
     if (s.isEmpty())
         return QImage();
     QSize newSize = size();
     newSize.scale(s, aspectMode);
     newSize.rwidth() = qMax(newSize.width(), 1);
     newSize.rheight() = qMax(newSize.height(), 1);
     if (newSize == size())
         return *this;
     QTransform wm = QTransform::fromScale((qreal)newSize.width() / width(), (qreal)newSize.height() / height());
     QImage img = transformed(wm, mode);
     return img;
 }
scaledToHeight()
QImage QImage::scaledToHeight (int height, Qt::TransformationMode mode = Qt::FastTransformation) const
Returns a scaled copy of the image.
The returned image is scaled to the given height using the specified transformation mode.
This function automatically calculates the width of the image so that the ratio of the image is preserved.
If the given height is 0 or negative, a null image is returned.
See also
{QImage::Image Transformations}{Image Transformations}
Definition at line 4646 of file qimage.cpp.
 {
     if (!d) {
         qWarning("QImage::scaleHeight: Image is a null image");
         return QImage();
     }
     if (h <= 0)
         return QImage();
     qreal factor = (qreal) h / height();
     QTransform wm = QTransform::fromScale(factor, factor);
     return transformed(wm, mode);
 }
scaledToWidth()
QImage QImage::scaledToWidth (int width, Qt::TransformationMode mode = Qt::FastTransformation) const
Returns a scaled copy of the image.
The returned image is scaled to the given width using the specified transformation mode.
This function automatically calculates the height of the image so that its aspect ratio is preserved.
If the given width is 0 or negative, a null image is returned.
See also
{QImage::Image Transformations}{Image Transformations}
Definition at line 4615 of file qimage.cpp.
 {
     if (!d) {
         qWarning("QImage::scaleWidth: Image is a null image");
         return QImage();
     }
     if (w <= 0)
         return QImage();
     qreal factor = (qreal) w / width();
     QTransform wm = QTransform::fromScale(factor, factor);
     return transformed(wm, mode);
 }
scanLine() [1/2]
uchar * QImage::scanLine (int i)
Returns a pointer to the pixel data at the scanline with index i.
The first scanline is at index 0.
The scanline data is aligned on a 32-bit boundary.
Warning
If you are accessing 32-bpp image data, cast the returned pointer to QRgb* (QRgb has a 32-bit size) and use it to read/write the pixel value. You cannot use the uchar* pointer directly, because the pixel format depends on the byte order on the underlying platform. Use qRed(), qGreen(), qBlue(), and qAlpha() to access the pixels.
See also
bytesPerLine(), bits(), {QImage::Pixel Manipulation}{Pixel Manipulation}, constScanLine()
Definition at line 1886 of file qimage.cpp.
Referenced by QPdfEnginePrivate::addImage(), QFontEngineMac::alphaMapForGlyph(), QFontEngineDirectWrite::alphaMapForGlyph(), QFontEngineXLFD::alphaMapForGlyph(), QFontEngineQPF::alphaMapForGlyph(), QFontEngine::alphaMapForGlyph(), QFontEngineQPF1::alphaMapForGlyph(), alphaMapFromPath(), QFontEngineWin::alphaRGBMapForGlyph(), QFontEngine::alphaRGBMapForGlyph(), blit180(), blit270(), blit90(), blit_template(), QWindowSurface::buffer(), QRasterBuffer::colorizeBitmap(), colorizeBitmap(), compressHelper(), convertWithPalette(), convolute(), copy(), create32BitCursor(), QX11PixmapData::createBitmapFromImage(), QDirectFBScreen::createDFBSurface(), createHeuristicMask(), createMaskFromColor(), QGIFFormat::disposePrevious(), QRasterPaintEngine::drawBitmap(), QMacStylePrivate::drawColorlessButton(), QPSPrintEnginePrivate::drawImage(), QGIFFormat::fillRect(), QGLTextureGlyphCache::fillTexture(), QImageTextureGlyphCache::fillTexture(), QXlibWindowSurface::flush(), QRasterWindowSurface::flush(), QRasterBuffer::flushToARGBImage(), QBitmap::fromData(), QX11PixmapData::fromImage(), QPixmap::fromWinHBITMAP(), QPixmap::fromWinHICON(), QCommonStyle::generatedIconPixmap(), QWindowSurface::grabWidget(), QVNCIntegration::grabWindow(), grayscale(), QFontEngineDirectWrite::imageForGlyph(), QPixmapData::mask(), mygetcanvasline(), operator==(), QColorLuminancePicker::paintEvent(), pixel(), pixelIndex(), qGamma_correct_back_to_linear_cs(), qgl_byteSwapImage(), QImageScale::qimageCalcScaleInfo(), QTestLiteStaticInfoPrivate::qimageFromXImage(), qSmoothScaleImage(), qstring_to_xtp(), qt_bitmapToRegion(), qt_blurrow(), qt_createIconMask(), qt_write_dib(), qt_write_dibv5(), qt_x11_drawImage(), QVNCDirtyMap::QVNCDirtyMap(), QTiffHandler::read(), ICOReader::read16_24_32BMP(), ICOReader::read1BitBMP(), ICOReader::read4BitBMP(), ICOReader::read8BitBMP(), read_pbm_body(), read_xbm_body(), read_xpm_body(), QColorPicker::resizeEvent(), rgbSwapped(), QVNCCursor::sendClientCursor(), QRasterPixmapData::setMask(), QPixmapData::setMask(), setPixel(), QCursor::setPos(), QX11PixmapData::takeQImageFromXImage(), QMacPixmapData::toImage(), QRasterPixmapData::toImage(), QX11PixmapData::toImage(), QPixmap::toWinHBITMAP(), QPixmap::toWinHICON(), QTiffHandler::write(), QVNCClientCursor::write(), QRfbRawEncoder::write(), QRfbHextileEncoder< SRC >::write(), write_pbm_image(), write_xbm_image(), and write_xpm_image().
 {
     if (!d)
         return 0;
     detach();
     // In case detach() ran out of memory
     if (!d)
         return 0;
     return d->data + i * d->bytes_per_line;
 }
scanLine() [2/2]
const uchar * QImage::scanLine (int i) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1903 of file qimage.cpp.
 {
     if (!d)
         return 0;
     Q_ASSERT(i >= 0 && i < height());
     return d->data + i * d->bytes_per_line;
 }
serialNumber()
int QImage::serialNumber () const
Returns a number that identifies the contents of this QImage object.
Use cacheKey() instead.
Warning
The serial number doesn't necessarily change when the image is altered. This means that it may be dangerous to use it as a cache key.
See also
operator==()
Definition at line 6267 of file qimage.cpp.
Referenced by QRasterPixmapData::createPixmapForImage(), QTextCursor::insertImage(), QRasterPixmapData::resize(), and QAhiScreenCursor::set().
 {
     if (!d)
         return 0;
     else
         return d->ser_no;
 }
setAlphaChannel()
void QImage::setAlphaChannel (const QImage & alphaChannel)
Sets the alpha channel of this image to the given alphaChannel.
If alphaChannel is an 8 bit grayscale image, the intensity values are written into this buffer directly. Otherwise, alphaChannel is converted to 32 bit and the intensity of the RGB pixel values is used.
Note that the image will be converted to the Format_ARGB32_Premultiplied format if the function succeeds.
Use one of the composition modes in QPainter::CompositionMode instead.
Warning
This function is expensive.
See also
alphaChannel(), {QImage::Image Transformations}{Image Transformations}, {QImage::Image Formats}{Image Formats}
Definition at line 6329 of file qimage.cpp.
Referenced by QPixmapColorizeFilter::draw(), QFileSystemModel::headerData(), ICOReader::iconAt(), QRasterPixmapData::setAlphaChannel(), QX11PixmapData::setAlphaChannel(), QVolatileImage::setAlphaChannel(), and QPixmapData::setAlphaChannel().
 {
     if (!d)
         return;
     int w = d->width;
     int h = d->height;
     if (w != alphaChannel.d->width || h != alphaChannel.d->height) {
         qWarning("QImage::setAlphaChannel: "
                  "Alpha channel must have same dimensions as the target image");
         return;
     }
     if (d->paintEngine && d->paintEngine->isActive()) {
         qWarning("QImage::setAlphaChannel: "
                  "Unable to set alpha channel while image is being painted on");
         return;
     }
     if (d->format == QImage::Format_ARGB32_Premultiplied)
         detach();
     else
         *this = convertToFormat(QImage::Format_ARGB32_Premultiplied);
     if (isNull())
         return;
     // Slight optimization since alphachannels are returned as 8-bit grays.
     if (alphaChannel.d->depth == 8 && alphaChannel.isGrayscale()) {
         const uchar *src_data = alphaChannel.d->data;
         const uchar *dest_data = d->data;
         for (int y=0; y<h; ++y) {
             const uchar *src = src_data;
             QRgb *dest = (QRgb *)dest_data;
             for (int x=0; x<w; ++x) {
                 int alpha = *src;
                 int destAlpha = qt_div_255(alpha * qAlpha(*dest));
                 *dest = ((destAlpha << 24)
                          | (qt_div_255(qRed(*dest) * alpha) << 16)
                          | (qt_div_255(qGreen(*dest) * alpha) << 8)
                          | (qt_div_255(qBlue(*dest) * alpha)));
                 ++dest;
                 ++src;
             }
             src_data += alphaChannel.d->bytes_per_line;
             dest_data += d->bytes_per_line;
         }
     } else {
         const QImage sourceImage = alphaChannel.convertToFormat(QImage::Format_RGB32);
         if (sourceImage.isNull()) {
             qWarning("QImage::setAlphaChannel: out of memory");
             return;
         }
         const uchar *src_data = sourceImage.d->data;
         const uchar *dest_data = d->data;
         for (int y=0; y<h; ++y) {
             const QRgb *src = (const QRgb *) src_data;
             QRgb *dest = (QRgb *) dest_data;
             for (int x=0; x<w; ++x) {
                 int alpha = qGray(*src);
                 int destAlpha = qt_div_255(alpha * qAlpha(*dest));
                 *dest = ((destAlpha << 24)
                          | (qt_div_255(qRed(*dest) * alpha) << 16)
                          | (qt_div_255(qGreen(*dest) * alpha) << 8)
                          | (qt_div_255(qBlue(*dest) * alpha)));
                 ++dest;
                 ++src;
             }
             src_data += sourceImage.d->bytes_per_line;
             dest_data += d->bytes_per_line;
         }
     }
 }
setColor()
void QImage::setColor (int index, QRgb colorValue)
Sets the color at the given index in the color table, to the given to colorValue.
The color value is an ARGB quadruplet.
If index is outside the current size of the color table, it is expanded with setColorCount().
See also
color(), colorCount(), setColorTable(), {QImage::Pixel Manipulation}{Pixel Manipulation}
Definition at line 1850 of file qimage.cpp.
Referenced by alphaChannel(), QFontEngineQPF::alphaMapForGlyph(), QFontEngineQPF1::alphaMapForGlyph(), QX11PixmapData::createBitmapFromImage(), QWSCursor::createDropShadow(), createHeuristicMask(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawScrollbarGroove(), ensureValidImage(), QGLPixmapData::fillImage(), QBitmap::fromData(), QBitmap::fromImage(), QMacPixmapData::fromImage(), get_index(), makeBitmapCompliantIfNeeded(), QPixmapData::mask(), read_dib_body(), read_pbm_body(), read_xbm_body(), read_xpm_body(), ICOReader::readColorTable(), QRasterPixmapData::resize(), setup_qt(), QWindowsMobileStyle::standardPixmap(), QMotifStyle::standardPixmap(), QGtkStyle::standardPixmap(), swapPixel01(), QMacPixmapData::toImage(), and QX11PixmapData::toImage().
 {
     if (!d)
         return;
     if (i < 0 || d->depth > 8 || i >= 1<<d->depth) {
         qWarning("QImage::setColor: Index out of bound %d", i);
         return;
     }
     detach();
     // In case detach() run out of memory
     if (!d)
         return;
     if (i >= d->colortable.size())
         setColorCount(i+1);
     d->colortable[i] = c;
     d->has_alpha_clut |= (qAlpha(c) != 255);
 }
setColorCount()
void QImage::setColorCount (int colorCount)
Resizes the color table to contain colorCount entries.
Since
4.6
If the color table is expanded, all the extra colors will be set to transparent (i.e qRgba(0, 0, 0, 0)).
When the image is used, the color table must be large enough to have entries for all the pixel/index values present in the image, otherwise the results are undefined.
See also
colorCount(), colorTable(), setColor(), {QImage::Image Transformations}{Image Transformations}
Definition at line 2275 of file qimage.cpp.
Referenced by alphaChannel(), createHeuristicMask(), ensureValidImage(), QGLPixmapData::fillImage(), QX11PixmapData::fromImage(), get_index(), ICOReader::iconAt(), QPixmapData::mask(), QImage(), read_dib_body(), read_pbm_body(), read_xbm_body(), read_xpm_body(), ICOReader::readColorTable(), QRasterPixmapData::resize(), setColor(), setNumColors(), setup_qt(), QMacPixmapData::toImage(), and QX11PixmapData::toImage().
 {
     if (!d) {
         qWarning("QImage::setColorCount: null image");
         return;
     }
     detach();
     // In case detach() ran out of memory
     if (!d)
         return;
     if (colorCount == d->colortable.size())
         return;
     if (colorCount <= 0) {                        // use no color table
         d->colortable = QVector<QRgb>();
         return;
     }
     int nc = d->colortable.size();
     d->colortable.resize(colorCount);
     for (int i = nc; i < colorCount; ++i)
         d->colortable[i] = 0;
 }
setColorTable()
void QImage::setColorTable (const QVector< QRgb > colors)
Sets the color table used to translate color indexes to QRgb values, to the specified colors.
When the image is used, the color table must be large enough to have entries for all the pixel/index values present in the image, otherwise the results are undefined.
See also
colorTable(), setColor(), {QImage::Image Transformations}{Image Transformations}
Definition at line 1744 of file qimage.cpp.
Referenced by QProxyFontEngine::alphaMapForGlyph(), QFontEngineXLFD::alphaMapForGlyph(), QFontEngineBox::alphaMapForGlyph(), QGLPixmapDropShadowFilter::processGL(), and QTiffHandler::read().
 {
     if (!d)
         return;
     detach();
     // In case detach() ran out of memory
     if (!d)
         return;
     d->colortable = colors;
     d->has_alpha_clut = false;
     for (int i = 0; i < d->colortable.size(); ++i) {
         if (qAlpha(d->colortable.at(i)) != 255) {
             d->has_alpha_clut = true;
             break;
         }
     }
 }
setDotsPerMeterX()
void QImage::setDotsPerMeterX (int x)
Sets the number of pixels that fit horizontally in a physical meter, to x.
Together with dotsPerMeterY(), this number defines the intended scale and aspect ratio of the image, and determines the scale at which QPainter will draw graphics on the image. It does not change the scale or aspect ratio of the image when it is rendered on other paint devices.
See also
dotsPerMeterX(), {QImage::Image Information}{Image Information}
Definition at line 5645 of file qimage.cpp.
Referenced by convertToFormat(), qt_read_dibv5(), QTiffHandler::read(), read_dib_body(), QPngHandlerPrivate::readPngImage(), setImageMetrics(), and setPixel().
 {
     if (!d || !x)
         return;
     detach();
     if (d)
         d->dpmx = x;
 }
setDotsPerMeterY()
void QImage::setDotsPerMeterY (int y)
Sets the number of pixels that fit vertically in a physical meter, to y.
Together with dotsPerMeterX(), this number defines the intended scale and aspect ratio of the image, and determines the scale at which QPainter will draw graphics on the image. It does not change the scale or aspect ratio of the image when it is rendered on other paint devices.
See also
dotsPerMeterY(), {QImage::Image Information}{Image Information}
Definition at line 5667 of file qimage.cpp.
Referenced by convertToFormat(), qt_read_dibv5(), QTiffHandler::read(), read_dib_body(), QPngHandlerPrivate::readPngImage(), setImageMetrics(), and setPixel().
 {
     if (!d || !y)
         return;
     detach();
     if (d)
         d->dpmy = y;
 }
setNumColors()
void QImage::setNumColors (int numColors)
Resizes the color table to contain numColors entries.
See also
setColorCount()
Definition at line 2252 of file qimage.cpp.
 {
     setColorCount(numColors);
 }
setOffset()
void QImage::setOffset (const QPoint & offset)
Sets the number of pixels by which the image is intended to be offset by when positioning relative to other images, to offset.
See also
offset(), {QImage::Image Information}{Image Information}
Definition at line 5705 of file qimage.cpp.
Referenced by QPngHandlerPrivate::readPngImage().
 {
     if (!d)
         return;
     detach();
     if (d)
         d->offset = p;
 }
setPixel() [1/2]
void QImage::setPixel (int x, int y, uint index_or_rgb)
Sets the pixel index or color at (x, y) to index_or_rgb.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4311 of file qimage.cpp.
Referenced by QGLGlyphCache::allocTexture(), QFontEngineBox::alphaMapForGlyph(), QRasterBuffer::bufferImage(), QWSCursor::createDropShadow(), darkenPixmap(), drawEllipse_midpoint_i(), QWindowsMobileStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), qt_patternForAlpha(), and QTgaFile::readImage().
 {
     if (!d || x < 0 || x >= width() || y < 0 || y >= height()) {
         qWarning("QImage::setPixel: coordinate (%d,%d) out of range", x, y);
         return;
     }
     // detach is called from within scanLine
     uchar * s = scanLine(y);
     if (!s) {
         qWarning("setPixel: Out of memory");
         return;
     }
     const quint32p p = quint32p::fromRawData(index_or_rgb);
     switch(d->format) {
     case Format_Mono:
     case Format_MonoLSB:
         if (index_or_rgb > 1) {
             qWarning("QImage::setPixel: Index %d out of range", index_or_rgb);
         } else if (format() == Format_MonoLSB) {
             if (index_or_rgb==0)
                 *(s + (x >> 3)) &= ~(1 << (x & 7));
             else
                 *(s + (x >> 3)) |= (1 << (x & 7));
         } else {
             if (index_or_rgb==0)
                 *(s + (x >> 3)) &= ~(1 << (7-(x & 7)));
             else
                 *(s + (x >> 3)) |= (1 << (7-(x & 7)));
         }
         break;
     case Format_Indexed8:
         if (index_or_rgb >= (uint)d->colortable.size()) {
             qWarning("QImage::setPixel: Index %d out of range", index_or_rgb);
             return;
         }
         s[x] = index_or_rgb;
         break;
     case Format_RGB32:
         //make sure alpha is 255, we depend on it in qdrawhelper for cases
         // when image is set as a texture pattern on a qbrush
         ((uint *)s)[x] = uint(255 << 24) | index_or_rgb;
         break;
     case Format_ARGB32:
     case Format_ARGB32_Premultiplied:
         ((uint *)s)[x] = index_or_rgb;
         break;
     case Format_RGB16:
         ((quint16 *)s)[x] = qt_colorConvert<quint16, quint32p>(p, 0);
         break;
     case Format_ARGB8565_Premultiplied:
         ((qargb8565*)s)[x] = qt_colorConvert<qargb8565, quint32p>(p, 0);
         break;
     case Format_RGB666:
         ((qrgb666*)s)[x] = qt_colorConvert<qrgb666, quint32p>(p, 0);
         break;
     case Format_ARGB6666_Premultiplied:
         ((qargb6666*)s)[x] = qt_colorConvert<qargb6666, quint32p>(p, 0);
         break;
     case Format_RGB555:
         ((qrgb555*)s)[x] = qt_colorConvert<qrgb555, quint32p>(p, 0);
         break;
     case Format_ARGB8555_Premultiplied:
         ((qargb8555*)s)[x] = qt_colorConvert<qargb8555, quint32p>(p, 0);
         break;
     case Format_RGB888:
         ((qrgb888*)s)[x] = qt_colorConvert<qrgb888, quint32p>(p, 0);
         break;
     case Format_RGB444:
         ((qrgb444*)s)[x] = qt_colorConvert<qrgb444, quint32p>(p, 0);
         break;
     case Format_ARGB4444_Premultiplied:
         ((qargb4444*)s)[x] = qt_colorConvert<qargb4444, quint32p>(p, 0);
         break;
     case Format_Invalid:
     case NImageFormats:
         Q_ASSERT(false);
     }
 }
setPixel() [2/2]
Q_GUI_EXPORT_INLINE void QImage::setPixel (const QPoint & position, uint index_or_rgb)
Sets the pixel index or color at the given position to index_or_rgb.
If the image's format is either monochrome or 8-bit, the given index_or_rgb value must be an index in the image's color table, otherwise the parameter must be a QRgb value.
If position is not a valid coordinate pair in the image, or if index_or_rgb >= colorCount() in the case of monochrome and 8-bit images, the result is undefined.
Warning
This function is expensive due to the call of the internal detach() function called within; if performance is a concern, we recommend the use of QImage::scanLine() to access pixel data directly.
See also
pixel(), {QImage::Pixel Manipulation}{Pixel Manipulation}
Definition at line 357 of file qimage.h.
 { setPixel(pt.x(), pt.y(), index_or_rgb); }
setText() [1/2]
void QImage::setText (const QString & key, const QString & text)
Sets the image text to the given text and associate it with the given key.
If you just want to store a single text block (i.e., a "comment" or just a description), you can either pass an empty key, or use a generic key like "Description".
The image text is embedded into the image data when you call save() or QImageWriter::write().
Not all image formats support embedded text. You can find out if a specific image or format supports embedding text by using QImageWriter::supportsOption(). We give an example:
    QImageWriter writer;
    writer.setFormat("png");
    if (writer.supportsOption(QImageIOHandler::Description))
        qDebug() << "Png supports embedded text";
You can use QImageWriter::supportedImageFormats() to find out which image formats are available to you.
See also
text(), textKeys()
Definition at line 5780 of file qimage.cpp.
Referenced by QPngHandlerPrivate::readPngImage().
 {
     if (!d)
         return;
     detach();
     if (d)
         d->text.insert(key, value);
 }
setText() [2/2]
void QImage::setText (const char * key, const char * language, const QString & text)
Sets the image text to the given text and associate it with the given key. The text is recorded in the specified language, or in a default language if language is 0.
Use setText() instead.
The language the text is recorded in is no longer relevant since the text is always set using QString and UTF-8 representation.
Warning
This function is not part of the public interface. Records string for the keyword key. The key should be a portable keyword recognizable by other software - some suggested values can be found in the PNG specification. s can be any text. lang should specify the language code (see RFC 1766) or 0.
Definition at line 5920 of file qimage.cpp.
 {
     if (!d)
         return;
     detach();
     // In case detach() ran out of memory
     if (!d)
         return;
     QString k = QString::fromAscii(key);
     if (lang && *lang)
         k += QLatin1Char('/') + QString::fromAscii(lang);
     d->text.insert(k, s);
 }
size()
QSize QImage::size () const
Returns the size of the image, i.
e. its width() and height().
\sa {QImage#Image Information}{Image Information}
Definition at line 1587 of file qimage.cpp.
Referenced by blendCursor(), QTransformedScreen::blit(), QScreen::blit(), QWindowSurface::buffer(), colorizeBitmap(), QPaintBuffer::commandDescription(), convertWithPalette(), createMaskFromColor(), QGLPixmapData::createPixmapForImage(), QPixmapColorizeFilter::draw(), QDirectFBPaintEngine::drawImage(), QBlitterPaintEngine::drawImage(), QGL2PaintEngineEx::drawImage(), QVGPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QPaintEngineEx::drawImage(), QPaintBufferEngine::drawImage(), QCleanlooksStyle::drawPrimitive(), ensureValidImage(), QWindowSurface::grabWidget(), grayscale(), QStyledItemDelegate::initStyleOption(), QGLPixmapData::paintEngine(), QGLPixmapDropShadowFilter::processGL(), QImage(), qt_read_dibv5(), QTiffHandler::read(), read_dib_body(), read_pbm_body(), read_xbm_body(), read_xpm_body(), readImage(), QMinimalWindowSurface::resize(), QFbWindowSurface::resize(), scaled(), QVNCCursor::sendClientCursor(), QProxyScreenCursor::set(), QScreenCursor::set(), QDirectFBScreenCursor::set(), QWSLocalMemSurface::setGeometry(), QWSSharedMemSurface::setGeometry(), setup_qt(), QWaylandShmBuffer::size(), toVGImageWithOpacity(), QGL2PaintEngineExPrivate::updateBrushTexture(), and QVNCClientCursor::write().
 {
     return d ? QSize(d->width, d->height) : QSize(0, 0);
 }
swap()
void QImage::swap (QImage & other) inline
Swaps image other with this image.
Since
4.8
This operation is very fast and never fails.
Definition at line 147 of file qimage.h.
 { qSwap(d, other.d); }
text() [1/3]
QString QImage::text (const QString & key = QString()) const
Returns the image text associated with the given key.
If the specified key is an empty string, the whole image text is returned, with each key-text pair separated by a newline.
See also
setText(), textKeys()
Definition at line 5736 of file qimage.cpp.
Referenced by convertWithPalette(), and set_text().
 {
     if (!d)
         return QString();
     if (!key.isEmpty())
         return d->text.value(key);
     QString tmp;
     foreach (const QString &key, d->text.keys()) {
         if (!tmp.isEmpty())
             tmp += QLatin1String("\n\n");
         tmp += key + QLatin1String(": ") + d->text.value(key).simplified();
     }
     return tmp;
 }
text() [2/3]
QString QImage::text (const char * key, const char * language = 0) const
Returns the text recorded for the given key in the given language, or in a default language if language is 0.
Use text() instead.
The language the text is recorded in is no longer relevant since the text is always set using QString and UTF-8 representation.
Definition at line 5802 of file qimage.cpp.
 {
     if (!d)
         return QString();
     QString k = QString::fromAscii(key);
     if (lang && *lang)
         k += QLatin1Char('/') + QString::fromAscii(lang);
     return d->text.value(k);
 }
text() [3/3]
QString QImage::text (const QImageTextKeyLang & keywordAndLanguage) const
Returns the text recorded for the given keywordAndLanguage.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Use text() instead.
The language the text is recorded in is no longer relevant since the text is always set using QString and UTF-8 representation.
Definition at line 5827 of file qimage.cpp.
 {
     if (!d)
         return QString();
     QString k = QString::fromAscii(kl.key);
     if (!kl.lang.isEmpty())
         k += QLatin1Char('/') + QString::fromAscii(kl.lang);
     return d->text.value(k);
 }
textKeys()
QStringList QImage::textKeys () const
Returns the text keys for this image.
You can use these keys with text() to list the image text for a certain key.
See also
text()
Definition at line 5724 of file qimage.cpp.
Referenced by set_text(), textLanguages(), and textList().
 {
     return d ? QStringList(d->text.keys()) : QStringList();
 }
textLanguages()
QStringList QImage::textLanguages () const
Returns the language identifiers for which some texts are recorded.
Note that if you want to iterate over the list, you should iterate over a copy.
The language the text is recorded in is no longer relevant since the text is always set using QString and UTF-8 representation.
Definition at line 5850 of file qimage.cpp.
 {
     if (!d)
         return QStringList();
     QStringList keys = textKeys();
     QStringList languages;
     for (int i = 0; i < keys.size(); ++i) {
         int index = keys.at(i).indexOf(QLatin1Char('/'));
         if (index > 0)
             languages += keys.at(i).mid(index+1);
     }
     return languages;
 }
textList()
QList< QImageTextKeyLang > QImage::textList () const
Returns a list of QImageTextKeyLang objects that enumerate all the texts key/language pairs set for this image.
Use textKeys() instead.
The language the text is recorded in is no longer relevant since the text is always set using QString and UTF-8 representation.
Definition at line 5879 of file qimage.cpp.
 {
     QList<QImageTextKeyLang> imageTextKeys;
     if (!d)
         return imageTextKeys;
     QStringList keys = textKeys();
     for (int i = 0; i < keys.size(); ++i) {
         int index = keys.at(i).indexOf(QLatin1Char('/'));
         if (index > 0) {
             QImageTextKeyLang tkl;
             tkl.key = keys.at(i).left(index).toAscii();
             tkl.lang = keys.at(i).mid(index+1).toAscii();
             imageTextKeys += tkl;
         }
     }
     return imageTextKeys;
 }
transformed() [1/2]
QImage QImage::transformed (const QMatrix & matrix, Qt::TransformationMode mode = Qt::FastTransformation) const
Returns a copy of the image that is transformed using the given transformation matrix and transformation mode.
The transformation matrix is internally adjusted to compensate for unwanted translation; i.e. the image produced is the smallest image that contains all the transformed points of the original image. Use the trueMatrix() function to retrieve the actual matrix used for transforming an image.
See also
trueMatrix(), {QImage::Image Transformations}{Image Transformations}
Definition at line 4698 of file qimage.cpp.
Referenced by QFontEngine::alphaMapForGlyph(), QFontEngineMac::alphaRGBMapForGlyph(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QTiffHandler::read(), scaled(), scaledToHeight(), scaledToWidth(), QDirectFBPixmapData::transformed(), and QX11PixmapData::transformed().
 {
     return transformed(QTransform(matrix), mode);
 }
transformed() [2/2]
QImage QImage::transformed (const QTransform & matrix, Qt::TransformationMode mode = Qt::FastTransformation) const
Returns a copy of the image that is transformed using the given transformation matrix and transformation mode.
The transformation matrix is internally adjusted to compensate for unwanted translation; i.e. the image produced is the smallest image that contains all the transformed points of the original image. Use the trueMatrix() function to retrieve the actual matrix used for transforming an image.
Unlike the other overload, this function can be used to perform perspective transformations on images.
See also
trueMatrix(), {QImage::Image Transformations}{Image Transformations}
Definition at line 6757 of file qimage.cpp.
 {
     if (!d)
         return QImage();
     // source image data
     int ws = width();
     int hs = height();
     // target image data
     int wd;
     int hd;
     // compute size of target image
     QTransform mat = trueMatrix(matrix, ws, hs);
     bool complex_xform = false;
     bool scale_xform = false;
     if (mat.type() <= QTransform::TxScale) {
         if (mat.type() == QTransform::TxNone) // identity matrix
             return *this;
         else if (mat.m11() == -1. && mat.m22() == -1.)
             return rotated180(*this);
         if (mode == Qt::FastTransformation) {
             hd = qRound(qAbs(mat.m22()) * hs);
             wd = qRound(qAbs(mat.m11()) * ws);
         } else {
             hd = int(qAbs(mat.m22()) * hs + 0.9999);
             wd = int(qAbs(mat.m11()) * ws + 0.9999);
         }
         scale_xform = true;
     } else {
         if (mat.type() <= QTransform::TxRotate && mat.m11() == 0 && mat.m22() == 0) {
             if (mat.m12() == 1. && mat.m21() == -1.)
                 return rotated90(*this);
             else if (mat.m12() == -1. && mat.m21() == 1.)
                 return rotated270(*this);
         }
         QPolygonF a(QRectF(0, 0, ws, hs));
         a = mat.map(a);
         QRect r = a.boundingRect().toAlignedRect();
         wd = r.width();
         hd = r.height();
         complex_xform = true;
     }
     if (wd == 0 || hd == 0)
         return QImage();
     // Make use of the optimized algorithm when we're scaling
     if (scale_xform && mode == Qt::SmoothTransformation) {
         if (mat.m11() < 0.0F && mat.m22() < 0.0F) { // horizontal/vertical flip
             return smoothScaled(mirrored(true, true), wd, hd);
         } else if (mat.m11() < 0.0F) { // horizontal flip
             return smoothScaled(mirrored(true, false), wd, hd);
         } else if (mat.m22() < 0.0F) { // vertical flip
             return smoothScaled(mirrored(false, true), wd, hd);
         } else { // no flipping
             return smoothScaled(*this, wd, hd);
         }
     }
     int bpp = depth();
     int sbpl = bytesPerLine();
     const uchar *sptr = bits();
     QImage::Format target_format = d->format;
     if (complex_xform || mode == Qt::SmoothTransformation) {
         if (d->format < QImage::Format_RGB32 || !hasAlphaChannel()) {
             switch(d->format) {
             case QImage::Format_RGB16:
                 target_format = Format_ARGB8565_Premultiplied;
                 break;
             case QImage::Format_RGB555:
                 target_format = Format_ARGB8555_Premultiplied;
                 break;
             case QImage::Format_RGB666:
                 target_format = Format_ARGB6666_Premultiplied;
                 break;
             case QImage::Format_RGB444:
                 target_format = Format_ARGB4444_Premultiplied;
                 break;
             default:
                 target_format = Format_ARGB32_Premultiplied;
                 break;
             }
         }
     }
     QImage dImage(wd, hd, target_format);
     QIMAGE_SANITYCHECK_MEMORY(dImage);
     if (target_format == QImage::Format_MonoLSB
         || target_format == QImage::Format_Mono
         || target_format == QImage::Format_Indexed8) {
         dImage.d->colortable = d->colortable;
         dImage.d->has_alpha_clut = d->has_alpha_clut | complex_xform;
     }
     dImage.d->dpmx = dotsPerMeterX();
     dImage.d->dpmy = dotsPerMeterY();
     switch (bpp) {
         // initizialize the data
         case 8:
             if (dImage.d->colortable.size() < 256) {
                 // colors are left in the color table, so pick that one as transparent
                 dImage.d->colortable.append(0x0);
                 memset(dImage.bits(), dImage.d->colortable.size() - 1, dImage.byteCount());
             } else {
                 memset(dImage.bits(), 0, dImage.byteCount());
             }
             break;
         case 1:
         case 16:
         case 24:
         case 32:
             memset(dImage.bits(), 0x00, dImage.byteCount());
             break;
     }
     if (target_format >= QImage::Format_RGB32) {
         QPainter p(&dImage);
         if (mode == Qt::SmoothTransformation) {
             p.setRenderHint(QPainter::Antialiasing);
             p.setRenderHint(QPainter::SmoothPixmapTransform);
         }
         p.setTransform(mat);
         p.drawImage(QPoint(0, 0), *this);
     } else {
         bool invertible;
         mat = mat.inverted(&invertible);                // invert matrix
         if (!invertible)        // error, return null image
             return QImage();
         // create target image (some of the code is from QImage::copy())
         int type = format() == Format_Mono ? QT_XFORM_TYPE_MSBFIRST : QT_XFORM_TYPE_LSBFIRST;
         int dbpl = dImage.bytesPerLine();
         qt_xForm_helper(mat, 0, type, bpp, dImage.bits(), dbpl, 0, hd, sptr, sbpl, ws, hs);
     }
     return dImage;
 }
trueMatrix() [1/2]
QMatrix QImage::trueMatrix (const QMatrix & matrix, int width, int height) static
Returns the actual matrix used for transforming an image with the given width, height and matrix.
When transforming an image using the transformed() function, the transformation matrix is internally adjusted to compensate for unwanted translation, i.e. transformed() returns the smallest image containing all transformed points of the original image. This function returns the modified matrix, which maps points correctly from the original image into the new image.
See also
transformed(), {QImage::Image Transformations}{Image Transformations}
Definition at line 4680 of file qimage.cpp.
Referenced by transformed(), and QPixmap::trueMatrix().
 {
     return trueMatrix(QTransform(matrix), w, h).toAffine();
 }
trueMatrix() [2/2]
QTransform QImage::trueMatrix (const QTransform & matrix, int width, int height) static
Returns the actual matrix used for transforming an image with the given width, height and matrix.
When transforming an image using the transformed() function, the transformation matrix is internally adjusted to compensate for unwanted translation, i.e. transformed() returns the smallest image containing all transformed points of the original image. This function returns the modified matrix, which maps points correctly from the original image into the new image.
Unlike the other overload, this function creates transformation matrices that can be used to perform perspective transformations on images.
See also
transformed(), {QImage::Image Transformations}{Image Transformations}
Definition at line 6927 of file qimage.cpp.
 {
     const QRectF rect(0, 0, w, h);
     const QRect mapped = matrix.mapRect(rect).toAlignedRect();
     const QPoint delta = mapped.topLeft();
     return matrix * QTransform().translate(-delta.x(), -delta.y());
 }
valid() [1/2]
bool QImage::valid (int x, int y) const
Returns true if QPoint(x, y) is a valid coordinate pair within the image; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4165 of file qimage.cpp.
 {
     return d
         && x >= 0 && x < d->width
         && y >= 0 && y < d->height;
 }
valid() [2/2]
Q_GUI_EXPORT_INLINE bool QImage::valid (const QPoint & pos) const
Returns true if pos is a valid coordinate pair within the image; otherwise returns false.
See also
rect(), QRect::contains()
Definition at line 354 of file qimage.h.
 { return valid(pt.x(), pt.y()); }
width()
int QImage::width () const
Returns the width of the image.
See also
{QImage::Image Information}{Image Information}
Definition at line 1557 of file qimage.cpp.
Referenced by QFontEngine::addBitmapFontToPath(), QPdfEnginePrivate::addBrushPattern(), QPdfEnginePrivate::addImage(), QFontEngineXLFD::addOutlineToPath(), allGray(), QAlphaWidget::alphaBlend(), QFontEngineMac::alphaMapForGlyph(), QFontEngineDirectWrite::alphaMapForGlyph(), QFontEngineXLFD::alphaMapForGlyph(), QFontEngine::alphaMapForGlyph(), alphaMapFromPath(), QFontEngine::alphaRGBMapForGlyph(), QX11PixmapData::bitmapFromImage(), QAhiScreen::blit(), QGLGlyphCache::cacheGlyphs(), QProxyFontEngine::canRender(), checkForAlphaPixels(), colorizeBitmap(), compressHelper(), convert_indexed8_to_ARGB_PM_inplace(), convert_indexed8_to_RGB16_inplace(), convert_indexed8_to_RGB_inplace(), QMacPasteboardMimeTiff::convertFromMime(), convertWithPalette(), convolute(), QImageData::create(), create32BitCursor(), QX11PixmapData::createBitmapFromImage(), QDirectFBScreen::createDFBSurface(), createHeuristicMask(), QVGPixmapData::createPixmapForImage(), QGLPixmapData::createPixmapForImage(), darkenPixmap(), QGIFFormat::decode(), QRasterPaintEngine::drawBitmap(), QCleanlooksStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QVGCompositionHelper::drawCursorPixmap(), QPdfEngine::drawImage(), QCoreGraphicsPaintEngine::drawImage(), QPSPrintEnginePrivate::drawImage(), QGL2PaintEngineEx::drawImage(), QOpenGLPaintEngine::drawImage(), QVGPaintEngine::drawImage(), QPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QRasterPaintEnginePrivate::drawImage(), QPainter::drawImage(), QPSPrintEnginePrivate::drawImageHelper(), QPSPrintEngine::drawImageInternal(), drawImageTiled(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QPdfEngine::drawPixmap(), QPlastiqueStyle::drawPrimitive(), QRasterPaintEngine::drawTextItem(), QOpenGLPaintEngine::drawTiledPixmap(), expblur(), QRasterPixmapData::fill(), QGLTextureGlyphCache::fillTexture(), QImageTextureGlyphCache::fillTexture(), QXlibWindowSurface::flush(), QRasterBuffer::flushToARGBImage(), QVGFontEngineCleaner::fontEngineDestroyed(), format(), QBlittablePixmapData::fromImage(), QDirectFBPixmapData::fromImage(), QMacPixmapData::fromImage(), QX11PixmapData::fromImage(), QWindowsMobileStyle::generatedIconPixmap(), QCommonStyle::generatedIconPixmap(), QMacStyle::generatedIconPixmap(), getImageSize(), QVNCIntegration::grabWindow(), grayscale(), ICOReader::iconAt(), QFontEngineMac::imageForGlyph(), QMeeGoPixmapData::imageToEGLSharedImage(), QFontEngineQPF::loadGlyph(), QPixmapData::mask(), mirrored(), operator==(), QWSLocalMemSurface::permanentState(), QWSSharedMemSurface::permanentState(), QRasterBuffer::prepare(), QRasterWindowSurface::prepareBuffer(), QGLPixmapBlurFilter::processGL(), QGLPixmapDropShadowFilter::processGL(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), qGamma_correct_back_to_linear_cs(), qgl_byteSwapImage(), QImageScale::qimageCalcScaleInfo(), QTestLiteStaticInfoPrivate::qimageFromXImage(), QMacCGContext::QMacCGContext(), qSmoothScaleImage(), qstring_to_xtp(), QSvgImage::QSvgImage(), qt_bitmapToRegion(), qt_blurImage(), qt_blurrow(), qt_createIconMask(), qt_halfScaled(), qt_mac_cg_context(), qt_mac_createCGImageFromQImage(), qt_mac_image_to_cgimage(), qt_scrollRectInImage(), qt_write_dib(), qt_write_dibv5(), rotate_right_mirror_horizontal(), rotate_right_mirror_vertical(), rotated270(), rotated90(), scaled(), scaledToWidth(), QItemDelegate::selected(), QVNCCursor::sendClientCursor(), QAhiScreenCursor::set(), QRasterPixmapData::setMask(), QPixmapData::setMask(), setPixel(), QMacStyle::styleHint(), QX11PixmapData::takeQImageFromXImage(), toVGImage(), QPixmap::toWinHBITMAP(), transformed(), QMeeGoPixmapData::updateFromSoftImage(), QVolatileImage::width(), QNativeImage::width(), QTiffHandler::write(), QBmpHandler::write(), QVNCClientCursor::write(), ICOReader::write(), write_jpeg_image(), write_pbm_image(), write_xbm_image(), write_xpm_image(), QMngHandlerPrivate::writeImage(), QPNGImageWriter::writeImage(), and QTextOdfWriter::writeInlineCharacter().
 {
     return d ? d->width : 0;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QImage & image) related
Writes the given image to the given stream as a PNG image, or as a BMP image if the stream's version is 1.
Note that writing the stream to a file will not produce a valid image file.
See also
QImage::save(), {Serializing Qt Data Types}
Definition at line 5406 of file qimage.cpp.
 {
     if (s.version() >= 5) {
         if (image.isNull()) {
             s << (qint32) 0; // null image marker
             return s;
         } else {
             s << (qint32) 1;
             // continue ...
         }
     }
     QImageWriter writer(s.device(), s.version() == 1 ? "bmp" : "png");
     writer.write(image);
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QImage & image) related
Reads an image from the given stream and stores it in the given image.
See also
QImage::load(), {Serializing Qt Data Types}
Definition at line 5435 of file qimage.cpp.
 {
     if (s.version() >= 5) {
         qint32 nullMarker;
         s >> nullMarker;
         if (!nullMarker) {
             image = QImage(); // null image
             return s;
         }
     }
     image = QImageReader(s.device(), 0).read();
     return s;
 }
QBlittablePixmapData
friend class QBlittablePixmapData friend
Definition at line 339 of file qimage.h.
QPixmapCacheEntry
friend class QPixmapCacheEntry friend
Definition at line 340 of file qimage.h.
QRasterPixmapData
friend class QRasterPixmapData friend
Definition at line 338 of file qimage.h.
qt_image_colortable
const QVector<QRgb>* qt_image_colortable (const QImage & image) friend
Definition at line 122 of file qimage.cpp.
 {
     return &image.d->colortable;
 }
qt_image_id
Q_GUI_EXPORT qint64 qt_image_id (const QImage & image) friend
Definition at line 117 of file qimage.cpp.
 {
     return image.cacheKey();
 }
QWSOnScreenSurface
friend class QWSOnScreenSurface friend
Definition at line 335 of file qimage.h.
Properties
d
QImageData* QImage::d private
Definition at line 336 of file qimage.h.
Referenced by allGray(), alphaChannel(), bits(), byteCount(), bytesPerLine(), color(), colorCount(), colorTable(), constBits(), constScanLine(), convert_RGB_to_Indexed8(), convertToFormat(), copy(), QImageData::create(), createAlphaMask(), createHeuristicMask(), createMaskFromColor(), QRasterPixmapData::createPixmapForImage(), depth(), detach(), dither_to_Mono(), QRasterPixmapData::fill(), fill(), format(), height(), invertPixels(), isGrayscale(), isNull(), QRasterPixmapData::metric(), mirrored(), numBytes(), numColors(), operator=(), operator==(), operator>>(), pixel(), pixelIndex(), QImage(), QPixmapCacheEntry::QPixmapCacheEntry(), qt_image_colortable(), rect(), rgbSwapped(), save(), scaled(), scaledToHeight(), scaledToWidth(), scanLine(), setAlphaChannel(), setColor(), setColorCount(), setColorTable(), setPixel(), size(), swap(), transformed(), valid(), width(), and ~QImage().
The documentation for this class was generated from the following files:
/src/gui/image/qimage.h
/src/gui/image/qimage.cpp