Qt 4.8: QFontMetricsF Class Reference
QFontMetricsF Class Reference
The QFontMetricsF class provides font metrics information.
#include <qfontmetrics.h>
Public Functions
qreal ascent () const
Returns the ascent of the font.
qreal averageCharWidth () const
Returns the average width of glyphs in the font.
QRectF boundingRect (const QString &string) const
Returns the bounding rectangle of the characters in the string specified by text.
QRectF boundingRect (QChar) const
Returns the bounding rectangle of the character ch relative to the left-most point on the base line.
QRectF boundingRect (const QRectF &r, int flags, const QString &string, int tabstops=0, int *tabarray=0) const
Returns the bounding rectangle of the characters in the given text.
qreal descent () const
Returns the descent of the font.
QString elidedText (const QString &text, Qt::TextElideMode mode, qreal width, int flags=0) const
If the string text is wider than width, returns an elided version of the string (i.
qreal height () const
Returns the height of the font.
bool inFont (QChar) const
Returns true if character ch is a valid character in the font; otherwise returns false.
bool inFontUcs4 (uint ucs4) const
Returns true if the character given by ch, encoded in UCS-4/UTF-32, is a valid character in the font; otherwise returns false.
qreal leading () const
Returns the leading of the font.
qreal leftBearing (QChar) const
Returns the left bearing of character ch in the font.
qreal lineSpacing () const
Returns the distance from one base line to the next.
qreal lineWidth () const
Returns the width of the underline and strikeout lines, adjusted for the point size of the font.
qreal maxWidth () const
Returns the width of the widest character in the font.
qreal minLeftBearing () const
Returns the minimum left bearing of the font.
qreal minRightBearing () const
Returns the minimum right bearing of the font.
bool operator!= (const QFontMetricsF &other)
Returns true if the font metrics are not equal to the other font metrics; otherwise returns false.
bool operator!= (const QFontMetricsF &other) const
Returns true if the font metrics are not equal to the other font metrics; otherwise returns false.
QFontMetricsF & operator= (const QFontMetricsF &)
Assigns the font metrics fm to this font metrics object.
QFontMetricsF & operator= (const QFontMetrics &)
Assigns other to this object.
bool operator== (const QFontMetricsF &other)
Returns true if the font metrics are equal to the other font metrics; otherwise returns false.
bool operator== (const QFontMetricsF &other) const
Returns true if the font metrics are equal to the other font metrics; otherwise returns false.
qreal overlinePos () const
Returns the distance from the base line to where an overline should be drawn.
QFontMetricsF (const QFont &)
Constructs a font metrics object for font.
QFontMetricsF (const QFont &, QPaintDevice *pd)
Constructs a font metrics object for font and paintdevice.
QFontMetricsF (const QFontMetrics &)
Constructs a font metrics object with floating point precision from the given fontMetrics object.
QFontMetricsF (const QFontMetricsF &)
Constructs a copy of fm.
qreal rightBearing (QChar) const
Returns the right bearing of character ch in the font.
QSizeF size (int flags, const QString &str, int tabstops=0, int *tabarray=0) const
Returns the size in pixels of the characters in the given text.
qreal strikeOutPos () const
Returns the distance from the base line to where the strikeout line should be drawn.
QRectF tightBoundingRect (const QString &text) const
Returns a tight bounding rectangle around the characters in the string specified by text.
qreal underlinePos () const
Returns the distance from the base line to where an underscore should be drawn.
qreal width (const QString &string) const
Returns the width in pixels of the characters in the given text.
qreal width (QChar) const
Returns the logical width of character ch in pixels.
qreal xHeight () const
Returns the 'x' height of the font.
~QFontMetricsF ()
Destroys the font metrics object and frees all allocated resources.
Properties
QExplicitlySharedDataPointer< QFontPrivate > d
Detailed Description
The QFontMetricsF class provides font metrics information.
Note
This class or function is reentrant.
QFontMetricsF functions calculate the size of characters and strings for a given font. You can construct a QFontMetricsF object with an existing QFont to obtain metrics for that font. If the font is changed later, the font metrics object is not updated.
Once created, the object provides functions to access the individual metrics of the font, its characters, and for strings rendered in the font.
There are several functions that operate on the font: ascent(), descent(), height(), leading() and lineSpacing() return the basic size properties of the font. The underlinePos(), overlinePos(), strikeOutPos() and lineWidth() functions, return the properties of the line that underlines, overlines or strikes out the characters. These functions are all fast.
There are also some functions that operate on the set of glyphs in the font: minLeftBearing(), minRightBearing() and maxWidth(). These are by necessity slow, and we recommend avoiding them if possible.
For each character, you can get its width(), leftBearing() and rightBearing() and find out whether it is in the font using inFont(). You can also treat the character as a string, and use the string functions on it.
The string functions include width(), to return the width of a string in pixels (or points, for a printer), boundingRect(), to return a rectangle large enough to contain the rendered string, and size(), to return the size of that rectangle.
Example:
QFont font("times", 24);
QFontMetricsF fm(font);
qreal pixelsWide = fm.width("What's the width of this text?");
qreal pixelsHigh = fm.height();
See also
QFont QFontInfo QFontDatabase
Definition at line 145 of file qfontmetrics.h.
Constructors and Destructors
QFontMetricsF() [1/4]
QFontMetricsF::QFontMetricsF (const QFont & font)
Constructs a font metrics object for font.
The font metrics will be compatible with the paintdevice used to create font.
The font metrics object holds the information for the font that is passed in the constructor at the time it is created, and is not updated if the font's attributes are changed later.
Use QFontMetricsF(const QFont &, QPaintDevice *) to get the font metrics that are compatible with a certain paint device.
Definition at line 1102 of file qfontmetrics.cpp.
     : d(font.d.data())
 {
 }
QFontMetricsF() [2/4]
QFontMetricsF::QFontMetricsF (const QFont & font, QPaintDevice * paintdevice)
Constructs a font metrics object for font and paintdevice.
The font metrics will be compatible with the paintdevice passed. If the paintdevice is 0, the metrics will be screen-compatible, ie. the metrics you get if you use the font for drawing text on a widgets or pixmaps, not on a QPicture or QPrinter.
The font metrics object holds the information for the font that is passed in the constructor at the time it is created, and is not updated if the font's attributes are changed later.
Definition at line 1120 of file qfontmetrics.cpp.
 {
     int dpi = paintdevice ? paintdevice->logicalDpiY() : qt_defaultDpi();
 #ifdef Q_WS_X11
     const QX11Info *info = qt_x11Info(paintdevice);
     int screen = info ? info->screen() : 0;
 #else
     const int screen = 0;
 #endif
     if (font.d->dpi != dpi || font.d->screen != screen ) {
         d = new QFontPrivate(*font.d);
         d->dpi = dpi;
         d->screen = screen;
     } else {
         d = font.d.data();
     }
 }
QFontMetricsF() [3/4]
QFontMetricsF::QFontMetricsF (const QFontMetrics & fontMetrics)
Constructs a font metrics object with floating point precision from the given fontMetrics object.
Since
4.2
Definition at line 1070 of file qfontmetrics.cpp.
     : d(fontMetrics.d.data())
 {
 }
QFontMetricsF() [4/4]
QFontMetricsF::QFontMetricsF (const QFontMetricsF & fm)
Constructs a copy of fm.
Definition at line 1142 of file qfontmetrics.cpp.
     : d(fm.d.data())
 {
 }
~QFontMetricsF()
QFontMetricsF::~QFontMetricsF ()
Destroys the font metrics object and frees all allocated resources.
Definition at line 1151 of file qfontmetrics.cpp.
 {
 }
Functions
ascent()
qreal QFontMetricsF::ascent () const
Returns the ascent of the font.
The ascent of a font is the distance from the baseline to the highest position characters extend to. In practice, some font designers break this rule, e.g. when they put more than one accent on top of a character, or to accommodate an unusual character in an exotic language, so it is possible (though rare) that this value will be too small.
See also
descent()
Definition at line 1231 of file qfontmetrics.cpp.
Referenced by overlinePos(), QFontFamilyDelegate::paint(), and strikeOutPos().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->ascent().toReal();
 }
averageCharWidth()
qreal QFontMetricsF::averageCharWidth () const
Returns the average width of glyphs in the font.
Since
4.2
Definition at line 1366 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->averageCharWidth().toReal();
 }
boundingRect() [1/3]
QRectF QFontMetricsF::boundingRect (const QString & text) const
Returns the bounding rectangle of the characters in the string specified by text.
The bounding rectangle always covers at least the set of pixels the text would cover if drawn at (0, 0).
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts, and that the width of the returned rectangle might be different than what the width() method returns.
If you want to know the advance width of the string (to layout a set of strings next to each other), use width() instead.
Newline characters are processed as normal characters, not as linebreaks.
The height of the bounding rectangle is at least as large as the value returned height().
See also
width(), height(), QPainter::boundingRect()
Definition at line 1568 of file qfontmetrics.cpp.
Referenced by size().
 {
     int len = text.length();
     if (len == 0)
         return QRectF();
     QStackTextEngine layout(text, d.data());
     layout.ignoreBidi = true;
     layout.itemize();
     glyph_metrics_t gm = layout.boundingBox(0, len);
     return QRectF(gm.x.toReal(), gm.y.toReal(),
                   gm.width.toReal(), gm.height.toReal());
 }
boundingRect() [2/3]
QRectF QFontMetricsF::boundingRect (QChar ch) const
Returns the bounding rectangle of the character ch relative to the left-most point on the base line.
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts, and that the text output may cover all pixels in the bounding rectangle.
Note that the rectangle usually extends both above and below the base line.
See also
width()
Definition at line 1595 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<10> glyphs;
     int nglyphs = 9;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     glyph_metrics_t gm = engine->boundingBox(glyphs.glyphs[0]);
     return QRectF(gm.x.toReal(), gm.y.toReal(), gm.width.toReal(), gm.height.toReal());
 }
boundingRect() [3/3]
QRectF QFontMetricsF::boundingRect (const QRectF & rect, int flags, const QString & text, int tabStops = 0, int * tabArray = 0) const
Returns the bounding rectangle of the characters in the given text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This is the set of pixels the text would cover if drawn when constrained to the bounding rectangle specified by rect.
The flags argument is the bitwise OR of the following flags:
Qt::AlignLeft aligns to the left border, except for Arabic and Hebrew where it aligns to the right.
Qt::AlignRight aligns to the right border, except for Arabic and Hebrew where it aligns to the left.
Qt::AlignJustify produces justified text.
Qt::AlignHCenter aligns horizontally centered.
Qt::AlignTop aligns to the top border.
Qt::AlignBottom aligns to the bottom border.
Qt::AlignVCenter aligns vertically centered
Qt::AlignCenter (== Qt::AlignHCenter | Qt::AlignVCenter)
Qt::TextSingleLine ignores newline characters in the text.
Qt::TextExpandTabs expands tabs (see below)
Qt::TextShowMnemonic interprets "&x" as x; i.e., underlined.
Qt::TextWordWrap breaks the text to fit the rectangle.
Qt::Horizontal alignment defaults to Qt::AlignLeft and vertical alignment defaults to Qt::AlignTop.
If several of the horizontal or several of the vertical alignment flags are set, the resulting alignment is undefined.
These flags are defined in Qt::AlignmentFlag.
If Qt::TextExpandTabs is set in flags, the following behavior is used to interpret tab characters in the text:
If tabArray is non-null, it specifies a 0-terminated sequence of pixel-positions for tabs in the text.
If tabStops is non-zero, it is used as the tab spacing (in pixels).
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts.
Newline characters are processed as line breaks.
Despite the different actual character heights, the heights of the bounding rectangles of "Yes" and "yes" are the same.
The bounding rectangle returned by this function is somewhat larger than that calculated by the simpler boundingRect() function. This function uses the maximum left and right font bearings as is necessary for multi-line text to align correctly. Also, fontHeight() and lineSpacing() are used to calculate the height, rather than individual character heights.
See also
width(), QPainter::boundingRect(), Qt::Alignment
Definition at line 1676 of file qfontmetrics.cpp.
 {
     int tabArrayLen = 0;
     if (tabArray)
         while (tabArray[tabArrayLen])
             tabArrayLen++;
     QRectF rb;
     qt_format_text(QFont(d.data()), rect, flags | Qt::TextDontPrint, text, &rb, tabStops, tabArray,
                    tabArrayLen, 0);
     return rb;
 }
descent()
qreal QFontMetricsF::descent () const
Returns the descent of the font.
The descent is the distance from the base line to the lowest point characters extend to. (Note that this is different from X, which adds 1 pixel.) In practice, some font designers break this rule, e.g. to accommodate an unusual character in an exotic language, so it is possible (though rare) that this value will be too small.
See also
ascent()
Definition at line 1250 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->descent().toReal();
 }
elidedText()
QString QFontMetricsF::elidedText (const QString & text, Qt::TextElideMode mode, qreal width, int flags = 0) const
If the string text is wider than width, returns an elided version of the string (i.
Since
4.2
e., a string with "..." in it). Otherwise, returns the original string.
The mode parameter specifies whether the text is elided on the left (e.g., "...tech"), in the middle (e.g., "Tr...ch"), or on the right (e.g., "Trol...").
The width is specified in pixels, not characters.
The flags argument is optional and currently only supports Qt::TextShowMnemonic as value.
Definition at line 1779 of file qfontmetrics.cpp.
 {
     QString _text = text;
     if (!(flags & Qt::TextLongestVariant)) {
         int posA = 0;
         int posB = _text.indexOf(QLatin1Char('\x9c'));
         while (posB >= 0) {
             QString portion = _text.mid(posA, posB - posA);
             if (size(flags, portion).width() <= width)
                 return portion;
             posA = posB + 1;
             posB = _text.indexOf(QLatin1Char('\x9c'), posA);
         }
         _text = _text.mid(posA);
     }
     QStackTextEngine engine(_text, QFont(d.data()));
     return engine.elidedText(mode, QFixed::fromReal(width), flags);
 }
height()
qreal QFontMetricsF::height () const
Returns the height of the font.
This is always equal to ascent()+descent()+1 (the 1 is for the base line).
See also
leading(), lineSpacing()
Definition at line 1265 of file qfontmetrics.cpp.
Referenced by qt_format_text(), and QMacStyle::subControlRect().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return (engine->ascent() + engine->descent() + 1).toReal();
 }
inFont()
bool QFontMetricsF::inFont (QChar ch) const
Returns true if character ch is a valid character in the font; otherwise returns false.
Definition at line 1377 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return false;
     return engine->canRender(&ch, 1);
 }
inFontUcs4()
bool QFontMetricsF::inFontUcs4 (uint ch) const
Returns true if the character given by ch, encoded in UCS-4/UTF-32, is a valid character in the font; otherwise returns false.
Since
4.8
Definition at line 1397 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ucs4);
     QFontEngine *engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return false;
     QString utf16 = QString::fromUcs4(&ucs4, 1);
     return engine->canRender(utf16.data(), utf16.length());
 }
leading()
qreal QFontMetricsF::leading () const
Returns the leading of the font.
This is the natural inter-line spacing.
See also
height(), lineSpacing()
Definition at line 1280 of file qfontmetrics.cpp.
Referenced by QStaticTextPrivate::paintText(), and qt_format_text().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->leading().toReal();
 }
leftBearing()
qreal QFontMetricsF::leftBearing (QChar ch) const
Returns the left bearing of character ch in the font.
The left bearing is the right-ward distance of the left-most pixel of the character from the logical origin of the character. This value is negative if the pixels of the character extend to the left of the logical origin.
See width(QChar) for a graphical description of this metric.
See also
rightBearing(), minLeftBearing(), width()
Definition at line 1420 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return 0;
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<10> glyphs;
     int nglyphs = 9;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     // ### can nglyphs != 1 happen at all? Not currently I think
     qreal lb;
     engine->getGlyphBearings(glyphs.glyphs[0], &lb);
     return lb;
 }
lineSpacing()
qreal QFontMetricsF::lineSpacing () const
Returns the distance from one base line to the next.
This value is always equal to leading()+height().
See also
height(), leading()
Definition at line 1294 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return (engine->leading() + engine->ascent() + engine->descent() + 1).toReal();
 }
lineWidth()
qreal QFontMetricsF::lineWidth () const
Returns the width of the underline and strikeout lines, adjusted for the point size of the font.
See also
underlinePos(), overlinePos(), strikeOutPos()
Definition at line 1839 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->lineThickness().toReal();
 }
maxWidth()
qreal QFontMetricsF::maxWidth () const
Returns the width of the widest character in the font.
Definition at line 1338 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->maxCharWidth();
 }
minLeftBearing()
qreal QFontMetricsF::minLeftBearing () const
Returns the minimum left bearing of the font.
This is the smallest leftBearing(char) of all characters in the font.
Note that this function can be very slow if the font is large.
See also
minRightBearing(), leftBearing()
Definition at line 1311 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->minLeftBearing();
 }
minRightBearing()
qreal QFontMetricsF::minRightBearing () const
Returns the minimum right bearing of the font.
This is the smallest rightBearing(char) of all characters in the font.
Note that this function can be very slow if the font is large.
See also
minLeftBearing(), rightBearing()
Definition at line 1328 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->minRightBearing();
 }
operator!=() [1/2]
bool QFontMetricsF::operator!= (const QFontMetricsF & other) inline
Returns true if the font metrics are not equal to the other font metrics; otherwise returns false.
See also
operator==()
Definition at line 197 of file qfontmetrics.h.
 { return !operator==(other); } // 5.0 - remove me
operator!=() [2/2]
bool QFontMetricsF::operator!= (const QFontMetricsF & other) const inline
Returns true if the font metrics are not equal to the other font metrics; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
operator==()
Definition at line 198 of file qfontmetrics.h.
 { return !operator==(other); }
operator=() [1/2]
QFontMetricsF & QFontMetricsF::operator= (const QFontMetricsF & fm)
Assigns the font metrics fm to this font metrics object.
Definition at line 1158 of file qfontmetrics.cpp.
 {
     d = fm.d.data();
     return *this;
 }
operator=() [2/2]
QFontMetricsF & QFontMetricsF::operator= (const QFontMetrics & other)
Assigns other to this object.
Since
4.2
Definition at line 1083 of file qfontmetrics.cpp.
 {
     d = other.d.data();
     return *this;
 }
operator==() [1/2]
bool QFontMetricsF::operator== (const QFontMetricsF & other)
Returns true if the font metrics are equal to the other font metrics; otherwise returns false.
Two font metrics are considered equal if they were constructed from the same QFont and the paint devices they were constructed for are considered to be compatible.
Definition at line 1189 of file qfontmetrics.cpp.
 {
     return d == other.d;
 }
operator==() [2/2]
bool QFontMetricsF::operator== (const QFontMetricsF & other) const
Returns true if the font metrics are equal to the other font metrics; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Two font metrics are considered equal if they were constructed from the same QFont and the paint devices they were constructed for are considered to be compatible.
Definition at line 1176 of file qfontmetrics.cpp.
 {
     return d == other.d;
 }
overlinePos()
qreal QFontMetricsF::overlinePos () const
Returns the distance from the base line to where an overline should be drawn.
See also
underlinePos(), strikeOutPos(), lineWidth()
Definition at line 1817 of file qfontmetrics.cpp.
 {
     return ascent() + 1;
 }
rightBearing()
qreal QFontMetricsF::rightBearing (QChar ch) const
Returns the right bearing of character ch in the font.
The right bearing is the left-ward distance of the right-most pixel of the character from the logical origin of a subsequent character. This value is negative if the pixels of the character extend to the right of the width() of the character.
See width() for a graphical description of this metric.
See also
leftBearing(), minRightBearing(), width()
Definition at line 1455 of file qfontmetrics.cpp.
 {
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     if (engine->type() == QFontEngine::Box)
         return 0;
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<10> glyphs;
     int nglyphs = 9;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     // ### can nglyphs != 1 happen at all? Not currently I think
     qreal rb;
     engine->getGlyphBearings(glyphs.glyphs[0], 0, &rb);
     return rb;
 }
size()
QSizeF QFontMetricsF::size (int flags, const QString & text, int tabStops = 0, int * tabArray = 0) const
Returns the size in pixels of the characters in the given text.
The flags argument is the bitwise OR of the following flags:
Qt::TextSingleLine ignores newline characters.
Qt::TextExpandTabs expands tabs (see below)
Qt::TextShowMnemonic interprets "&x" as x; i.e., underlined.
Qt::TextWordBreak breaks the text to fit the rectangle.
These flags are defined in Qt::TextFlags.
If Qt::TextExpandTabs is set in flags, the following behavior is used to interpret tab characters in the text:
If tabArray is non-null, it specifies a 0-terminated sequence of pixel-positions for tabs in the text.
If tabStops is non-zero, it is used as the tab spacing (in pixels).
Newline characters are processed as line breaks.
Note: Despite the different actual character heights, the heights of the bounding rectangles of "Yes" and "yes" are the same.
See also
boundingRect()
Definition at line 1718 of file qfontmetrics.cpp.
Referenced by elidedText(), and QMacStyle::subControlRect().
 {
     return boundingRect(QRectF(), flags | Qt::TextLongestVariant, text, tabStops, tabArray).size();
 }
strikeOutPos()
qreal QFontMetricsF::strikeOutPos () const
Returns the distance from the base line to where the strikeout line should be drawn.
See also
underlinePos(), overlinePos(), lineWidth()
Definition at line 1828 of file qfontmetrics.cpp.
 {
     return ascent() / 3.;
 }
tightBoundingRect()
QRectF QFontMetricsF::tightBoundingRect (const QString & text) const
Returns a tight bounding rectangle around the characters in the string specified by text.
Since
4.3
The bounding rectangle always covers at least the set of pixels the text would cover if drawn at (0, 0).
Note that the bounding rectangle may extend to the left of (0, 0), e.g. for italicized fonts, and that the width of the returned rectangle might be different than what the width() method returns.
If you want to know the advance width of the string (to layout a set of strings next to each other), use width() instead.
Newline characters are processed as normal characters, not as linebreaks.
Warning
Calling this method is very slow on Windows.
See also
width(), height(), boundingRect()
Definition at line 1748 of file qfontmetrics.cpp.
Referenced by QFontFamilyDelegate::paint().
 {
     if (text.length() == 0)
         return QRect();
     QStackTextEngine layout(text, d.data());
     layout.ignoreBidi = true;
     layout.itemize();
     glyph_metrics_t gm = layout.tightBoundingBox(0, text.length());
     return QRectF(gm.x.toReal(), gm.y.toReal(), gm.width.toReal(), gm.height.toReal());
 }
underlinePos()
qreal QFontMetricsF::underlinePos () const
Returns the distance from the base line to where an underscore should be drawn.
See also
overlinePos(), strikeOutPos(), lineWidth()
Definition at line 1804 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->underlinePosition().toReal();
 }
width() [1/2]
qreal QFontMetricsF::width (const QString & text) const
Returns the width in pixels of the characters in the given text.
Note that this value is not equal to the width returned by boundingRect().width() because boundingRect() returns a rectangle describing the pixels this string will cover whereas width() returns the distance to where the next string should be drawn.
See also
boundingRect()
Definition at line 1489 of file qfontmetrics.cpp.
Referenced by elidedText(), and qt_format_text().
 {
     int pos = text.indexOf(QLatin1Char('\x9c'));
     int len = (pos != -1) ? pos : text.length();
     QStackTextEngine layout(text, d.data());
     layout.ignoreBidi = true;
     layout.itemize();
     return layout.width(0, len).toReal();
 }
width() [2/2]
qreal QFontMetricsF::width (QChar ch) const
Returns the logical width of character ch in pixels.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Bearings
This is a distance appropriate for drawing a subsequent character after ch.
Some of the metrics are described in the image to the right. The central dark rectangles cover the logical width() of each character. The outer pale rectangles cover the leftBearing() and rightBearing() of each character. Notice that the bearings of "f" in this particular font are both negative, while the bearings of "o" are both positive.
Warning
This function will produce incorrect results for Arabic characters or non-spacing marks in the middle of a string, as the glyph shaping and positioning of marks that happens when processing strings cannot be taken into account. When implementing an interactive text control, use QTextLayout instead.
See also
boundingRect()
Definition at line 1527 of file qfontmetrics.cpp.
 {
     if (QChar::category(ch.unicode()) == QChar::Mark_NonSpacing)
         return 0.;
     const int script = QUnicodeTables::script(ch);
     QFontEngine *engine;
     if (d->capital == QFont::SmallCaps && ch.isLower())
         engine = d->smallCapsFontPrivate()->engineForScript(script);
     else
         engine = d->engineForScript(script);
     Q_ASSERT(engine != 0);
     d->alterCharForCapitalization(ch);
     QGlyphLayoutArray<8> glyphs;
     int nglyphs = 7;
     engine->stringToCMap(&ch, 1, &glyphs, &nglyphs, 0);
     return glyphs.advances_x[0].toReal();
 }
xHeight()
qreal QFontMetricsF::xHeight () const
Returns the 'x' height of the font.
This is often but not always the same as the height of the character 'x'.
Definition at line 1349 of file qfontmetrics.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     if (d->capital == QFont::SmallCaps)
         return d->smallCapsFontPrivate()->engineForScript(QUnicodeTables::Common)->ascent().toReal();
     return engine->xHeight().toReal();
 }
Properties
d
QExplicitlySharedDataPointer<QFontPrivate> QFontMetricsF::d private
Definition at line 201 of file qfontmetrics.h.
Referenced by ascent(), averageCharWidth(), boundingRect(), descent(), elidedText(), height(), inFont(), inFontUcs4(), leading(), leftBearing(), lineSpacing(), lineWidth(), maxWidth(), minLeftBearing(), minRightBearing(), operator=(), operator==(), QFontMetricsF(), rightBearing(), tightBoundingRect(), underlinePos(), width(), and xHeight().
The documentation for this class was generated from the following files:
/src/gui/text/qfontmetrics.h
/src/gui/text/qfontmetrics.cpp