Qt 4.8: QDeclarativeDataLoader Class Reference
QDeclarativeDataLoader Class Reference
The QDeclarativeDataLoader class abstracts loading files and their dependencies over the network.
#include <qdeclarativetypeloader_p.h>
Public Functions
QDeclarativeEngine * engine () const
Return the QDeclarativeEngine associated with this loader.
void load (QDeclarativeDataBlob *)
Load the provided blob from the network or filesystem.
void loadWithStaticData (QDeclarativeDataBlob *, const QByteArray &)
Load the provided blob with data.
QDeclarativeDataLoader (QDeclarativeEngine *)
Create a new QDeclarativeDataLoader for engine.
~QDeclarativeDataLoader ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Types
typedef QHash< QNetworkReply *, QDeclarativeDataBlob * > NetworkReplies
Private Slots
void networkReplyFinished ()
void networkReplyProgress (qint64, qint64)
Private Functions
void networkReplyFinished (QNetworkReply *)
void networkReplyProgress (QNetworkReply *, qint64, qint64)
void setData (QDeclarativeDataBlob *, const QByteArray &)
Properties
QDeclarativeEngine * m_engine
NetworkReplies m_networkReplies
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDeclarativeDataLoader class abstracts loading files and their dependencies over the network.
Warning
This function is not part of the public interface.
The QDeclarativeDataLoader class is provided for the exclusive use of the QDeclarativeTypeLoader class.
Clients create QDeclarativeDataBlob instances and submit them to the QDeclarativeDataLoader class through the QDeclarativeDataLoader::load() or QDeclarativeDataLoader::loadWithStaticData() methods. The loader then fetches the data over the network or from the local file system in an efficient way. QDeclarativeDataBlob is an abstract class, so should always be specialized.
Once data is received, the QDeclarativeDataBlob::dataReceived() method is invoked on the blob. The derived class should use this callback to process the received data. Processing of the data can result in an error being set (QDeclarativeDataBlob::setError()), or one or more dependencies being created (QDeclarativeDataBlob::addDependency()). Dependencies are other QDeclarativeDataBlob's that are required before processing can fully complete.
To complete processing, the QDeclarativeDataBlob::done() callback is invoked. done() is called when one of these three preconditions are met.
The QDeclarativeDataBlob has no dependencies.
The QDeclarativeDataBlob has an error set.
All the QDeclarativeDataBlob's dependencies are themselves "done()".
Thus QDeclarativeDataBlob::done() will always eventually be called, even if the blob has an error set.
Definition at line 157 of file qdeclarativetypeloader_p.h.
Typedefs
NetworkReplies
typedef QHash<QNetworkReply *, QDeclarativeDataBlob *> QDeclarativeDataLoader::NetworkReplies private
Definition at line 179 of file qdeclarativetypeloader_p.h.
Constructors and Destructors
QDeclarativeDataLoader()
QDeclarativeDataLoader::QDeclarativeDataLoader (QDeclarativeEngine * engine)
Create a new QDeclarativeDataLoader for engine.
Definition at line 506 of file qdeclarativetypeloader.cpp.
 : m_engine(engine)
 {
 }
~QDeclarativeDataLoader()
QDeclarativeDataLoader::~QDeclarativeDataLoader ()
Warning
This function is not part of the public interface.
Definition at line 512 of file qdeclarativetypeloader.cpp.
 {
     for (NetworkReplies::Iterator iter = m_networkReplies.begin(); iter != m_networkReplies.end(); ++iter)
         (*iter)->release();
 }
Functions
engine()
QDeclarativeEngine * QDeclarativeDataLoader::engine () const
Return the QDeclarativeEngine associated with this loader.
Definition at line 654 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::resolveTypes().
 {
     return m_engine;
 }
load()
void QDeclarativeDataLoader::load (QDeclarativeDataBlob * blob)
Load the provided blob from the network or filesystem.
Definition at line 521 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeLoader::get(), QDeclarativeTypeLoader::getQmldir(), and QDeclarativeTypeLoader::getScript().
 {
     Q_ASSERT(blob->status() == QDeclarativeDataBlob::Null);
     Q_ASSERT(blob->m_manager == 0);
     blob->m_status = QDeclarativeDataBlob::Loading;
     if (blob->m_url.isEmpty()) {
         QDeclarativeError error;
         error.setDescription(QLatin1String("Invalid null URL"));
         blob->setError(error);
         return;
     }
     QString lf = QDeclarativeEnginePrivate::urlToLocalFileOrQrc(blob->m_url);
     if (!lf.isEmpty()) {
         if (!QDeclarative_isFileCaseCorrect(lf)) {
             QDeclarativeError error;
             error.setUrl(blob->m_url);
             error.setDescription(QLatin1String("File name case mismatch"));
             blob->setError(error);
             return;
         }
         QFile file(lf);
         if (file.open(QFile::ReadOnly)) {
             QByteArray data = file.readAll();
             blob->m_progress = 1.;
             blob->downloadProgressChanged(1.);
             setData(blob, data);
         } else {
             blob->networkError(QNetworkReply::ContentNotFoundError);
         }
     } else {
         blob->m_manager = this;
         QNetworkReply *reply = m_engine->networkAccessManager()->get(QNetworkRequest(blob->m_url));
         m_networkReplies.insert(reply, blob);
         blob->addref();
         if (reply->isFinished()) {
             // Short-circuit synchronous replies.
             qint64 size = reply->size();
             networkReplyProgress(reply, size, size);
             networkReplyFinished(reply);
         } else {
             QObject::connect(reply, SIGNAL(downloadProgress(qint64,qint64)),
                              this, SLOT(networkReplyProgress(qint64,qint64)));
             QObject::connect(reply, SIGNAL(finished()),
                              this, SLOT(networkReplyFinished()));
         }
     }
 }
loadWithStaticData()
void QDeclarativeDataLoader::loadWithStaticData (QDeclarativeDataBlob * blob, const QByteArray & data)
Load the provided blob with data.
The blob's URL is not used by the data loader in this case.
Definition at line 641 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeLoader::get().
 {
     Q_ASSERT(blob->status() == QDeclarativeDataBlob::Null);
     Q_ASSERT(blob->m_manager == 0);
     blob->m_status = QDeclarativeDataBlob::Loading;
     setData(blob, data);
 }
networkReplyFinished [1/2]
void QDeclarativeDataLoader::networkReplyFinished () private slot
Definition at line 614 of file qdeclarativetypeloader.cpp.
Referenced by load(), and networkReplyFinished().
 {
     QNetworkReply *reply = static_cast<QNetworkReply *>(sender());
     networkReplyFinished(reply);
 }
networkReplyFinished() [2/2]
void QDeclarativeDataLoader::networkReplyFinished (QNetworkReply * reply) private
Definition at line 581 of file qdeclarativetypeloader.cpp.
 {
     reply->deleteLater();
     QDeclarativeDataBlob *blob = m_networkReplies.take(reply);
     Q_ASSERT(blob);
     blob->m_redirectCount++;
     if (blob->m_redirectCount < DATALOADER_MAXIMUM_REDIRECT_RECURSION) {
         QVariant redirect = reply->attribute(QNetworkRequest::RedirectionTargetAttribute);
         if (redirect.isValid()) {
             QUrl url = reply->url().resolved(redirect.toUrl());
             blob->m_finalUrl = url;
             QNetworkReply *reply = m_engine->networkAccessManager()->get(QNetworkRequest(url));
             QObject::connect(reply, SIGNAL(finished()), this, SLOT(networkReplyFinished()));
             m_networkReplies.insert(reply, blob);
             return;
         }
     }
     if (reply->error()) {
         blob->networkError(reply->error());
     } else {
         QByteArray data = reply->readAll();
         setData(blob, data);
     }
     blob->release();
 }
networkReplyProgress [1/2]
void QDeclarativeDataLoader::networkReplyProgress (qint64 bytesReceived, qint64 bytesTotal) private slot
Definition at line 632 of file qdeclarativetypeloader.cpp.
Referenced by load().
 {
     QNetworkReply *reply = static_cast<QNetworkReply *>(sender());
     networkReplyProgress(reply, bytesReceived, bytesTotal);
 }
networkReplyProgress() [2/2]
void QDeclarativeDataLoader::networkReplyProgress (QNetworkReply * reply, qint64 bytesReceived, qint64 bytesTotal) private
Definition at line 620 of file qdeclarativetypeloader.cpp.
 {
     QDeclarativeDataBlob *blob = m_networkReplies.value(reply);
     Q_ASSERT(blob);
     if (bytesTotal != 0) {
         blob->m_progress = bytesReceived / bytesTotal;
         blob->downloadProgressChanged(blob->m_progress);
     }
 }
setData()
void QDeclarativeDataLoader::setData (QDeclarativeDataBlob * blob, const QByteArray & data) private
Definition at line 659 of file qdeclarativetypeloader.cpp.
Referenced by load(), loadWithStaticData(), and networkReplyFinished().
 {
     blob->m_inCallback = true;
     blob->dataReceived(data);
     if (!blob->isError() && !blob->isWaiting())
         blob->allDependenciesDone();
     if (blob->status() != QDeclarativeDataBlob::Error)
         blob->m_status = QDeclarativeDataBlob::WaitingForDependencies;
     blob->m_inCallback = false;
     blob->tryDone();
 }
Properties
m_engine
QDeclarativeEngine* QDeclarativeDataLoader::m_engine private
Definition at line 178 of file qdeclarativetypeloader_p.h.
Referenced by engine(), load(), and networkReplyFinished().
m_networkReplies
NetworkReplies QDeclarativeDataLoader::m_networkReplies private
Definition at line 180 of file qdeclarativetypeloader_p.h.
Referenced by load(), networkReplyFinished(), networkReplyProgress(), and ~QDeclarativeDataLoader().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativetypeloader_p.h
/src/declarative/qml/qdeclarativetypeloader.cpp