Qt 4.8: QDateTimeEditPrivate Class Reference
QDateTimeEditPrivate Class Reference
#include <qdatetimeedit_p.h>
Public Functions
virtual void _q_editorCursorPositionChanged (int oldpos, int newpos)
void _q_resetButton ()
int absoluteIndex (QDateTimeEdit::Section s, int index) const
int absoluteIndex (const SectionNode &s) const
bool calendarPopupEnabled () const
virtual void clearCache () const
void clearSection (int index)
Clears the text of section s.
int closestSection (int index, bool forward) const
Returns the closest section of index index.
int cursorPosition () const
virtual QString displayText () const
void emitSignals (EmitPolicy ep, const QVariant &old)
QString getAmPmText (AmPm ap, Case cs) const
virtual QDateTime getMaximum () const
virtual QDateTime getMinimum () const
virtual QVariant getZeroVariant () const
Convenience function to get a variant of the right type.
void init (const QVariant &var)
void initCalendarPopup (QCalendarWidget *cw=0)
virtual void interpret (EmitPolicy ep)
Interprets text and emits signals.
bool isSeparatorKey (const QKeyEvent *k) const
virtual QLocale locale () const
virtual QStyle::SubControl newHoverControl (const QPoint &pos)
Returns the hover control at pos.
int nextPrevSection (int index, bool forward) const
Returns a copy of the section that is before or after current, depending on forward.
void positionCalendarPopup ()
QDateTimeEditPrivate ()
void readLocaleSettings ()
int sectionAt (int pos) const
Returns the section at index index or NoSection if there are no sections there.
virtual void setRange (const QVariant &min, const QVariant &max)
Convenience function to set min/max values.
void setSelected (int index, bool forward=false)
Selects the section s.
QDateTime stepBy (int index, int steps, bool test=false) const
Internal function called by QDateTimeEdit::stepBy().
void syncCalendarWidget ()
QString textFromValue (const QVariant &f) const
void updateArrow (QStyle::StateFlag state)
void updateCache (const QVariant &val, const QString &str) const
void updateEdit ()
Updates the line edit to reflect the current value of the spin box.
virtual void updateEditFieldGeometry ()
void updateTimeSpec ()
QDateTime validateAndInterpret (QString &input, int &, QValidator::State &state, bool fixup=false) const
QVariant valueFromText (const QString &f) const
This function's name is slightly confusing; it is not to be confused with QAbstractSpinBox::valueFromText().
QString valueToText (const QVariant &var) const
Public Functions inherited from QAbstractSpinBoxPrivate
void _q_editorTextChanged (const QString &)
Slot connected to the line edit's textChanged(const QString &) signal.
virtual QVariant bound (const QVariant &val, const QVariant &old=QVariant(), int steps=0) const
Bounds val to be within minimum and maximum.
void init ()
Initialises the QAbstractSpinBoxPrivate object.
QAbstractSpinBoxPrivate ()
void reset ()
Resets the state of the spinbox.
void setValue (const QVariant &val, EmitPolicy ep, bool updateEdit=true)
Sets the value of the spin box to val.
bool specialValue () const
Returns true if a specialValueText has been set and the current value is minimum.
QString stripped (const QString &text, int *pos=0) const
Strips any prefix/suffix from text.
bool updateHoverControl (const QPoint &pos)
Updates the old and new hover control.
void updateState (bool up, bool fromKeyboard=false)
Updates the state of the spinbox.
~QAbstractSpinBoxPrivate ()
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Functions inherited from QDateTimeParser
int absoluteMax (int index, const QDateTime &value=QDateTime()) const
\
int absoluteMin (int index) const
FieldInfo fieldInfo (int index) const
int findAmPm (QString &str1, int index, int *used=0) const
int findDay (const QString &str1, int intDaystart, int sectionIndex, QString *dayName=0, int *used=0) const
int findMonth (const QString &str1, int monthstart, int sectionIndex, QString *monthName=0, int *used=0) const
bool fromString (const QString &text, QDate *date, QTime *time) const
int getDigit (const QDateTime &dt, int index) const
Gets the digit from a datetime.
int maxChange (int s) const
Max number of units that can be changed by this section.
StateNode parse (QString &input, int &cursorPosition, const QDateTime &currentValue, bool fixup) const
bool parseFormat (const QString &format)
int parseSection (const QDateTime &currentValue, int sectionIndex, QString &txt, int &cursorPosition, int index, QDateTimeParser::State &state, int *used=0) const
bool potentialValue (const QString &str, int min, int max, int index, const QDateTime &currentValue, int insert) const
QDateTimeParser (QVariant::Type t, Context ctx)
QString sectionFormat (int index) const
QString sectionFormat (Section s, int count) const
int sectionMaxSize (int index) const
int sectionMaxSize (Section s, int count) const
QString sectionName (int s) const
For debugging.
const SectionNode & sectionNode (int index) const
Returns the sectionNode for the Section s.
int sectionPos (int index) const
Returns the starting position for section s.
int sectionPos (const SectionNode &sn) const
int sectionSize (int index) const
Returns the size of section s.
QString sectionText (int sectionIndex) const
QString sectionText (const QString &text, int sectionIndex, int index) const
Returns the text of section s.
Section sectionType (int index) const
bool setDigit (QDateTime &t, int index, int newval) const
Sets a digit in a datetime.
bool skipToNextSection (int section, const QDateTime &current, const QString &sectionText) const
QString stateName (int s) const
For debugging.
virtual ~QDateTimeParser ()
Static Public Functions
static QDateTimeEdit::Sections convertSections (QDateTimeParser::Sections s)
static QDateTimeEdit::Section convertToPublic (QDateTimeParser::Section s)
Static Public Functions inherited from QAbstractSpinBoxPrivate
static QVariant variantBound (const QVariant &min, const QVariant &value, const QVariant &max)
static int variantCompare (const QVariant &arg1, const QVariant &arg2)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QStyle::StateFlag arrowState
bool cacheGuard
bool calendarPopup
QVariant conflictGuard
QString defaultDateFormat
QString defaultDateTimeFormat
QString defaultTimeFormat
bool formatExplicitlySet
bool hasHadFocus
QCalendarPopup * monthCalendar
QDateTimeEdit::Sections sections
QString unreversedFormat
Public Variables inherited from QAbstractSpinBoxPrivate
uint accelerate: 1
int acceleration
uint buttonState
QAbstractSpinBox::ButtonSymbols buttonSymbols
QSize cachedMinimumSizeHint
QSize cachedSizeHint
QValidator::State cachedState
QString cachedText
QVariant cachedValue
uint cleared: 1
QAbstractSpinBox::CorrectionMode correctionMode
QLineEdit * edit
int effectiveSpinRepeatRate
uint frame: 1
QStyle::SubControl hoverControl
QRect hoverRect
uint ignoreCursorPositionChanged: 1
uint ignoreUpdateEdit: 1
uint keyboardTracking: 1
QVariant maximum
QVariant minimum
uint pendingEmit: 1
QString prefix
uint readOnly: 1
QVariant singleStep
QString specialValueText
int spinClickThresholdTimerId
int spinClickThresholdTimerInterval
int spinClickTimerId
int spinClickTimerInterval
QString suffix
QVariant::Type type
QSpinBoxValidator * validator
QVariant value
uint wrapping: 1
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Public Variables inherited from QDateTimeParser
int cachedDay
Context context
int currentSectionIndex
QLocale defaultLocale
Sections display
QString displayFormat
SectionNode first
bool fixday
SectionNode last
SectionNode none
QVariant::Type parserType
SectionNode popup
QVector< SectionNode > sectionNodes
QStringList separators
Qt::TimeSpec spec
QString text
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Types inherited from QDateTimeParser
enum {
Neither = -1, AM = 0, PM = 1, PossibleAM = 2,
PossiblePM = 3, PossibleBoth = 4
}
enum AmPm { AmText, PmText }
enum Case { UpperCase, LowerCase }
enum Context { FromString, DateTimeEdit }
enum FieldInfoFlag { Numeric = 0x01, FixedWidth = 0x02, AllowPartial = 0x04, Fraction = 0x08 }
enum Section {
NoSection = 0x00000, AmPmSection = 0x00001, MSecSection = 0x00002, SecondSection = 0x00004,
MinuteSection = 0x00008, Hour12Section = 0x00010, Hour24Section = 0x00020, TimeSectionMask = (AmPmSection|MSecSection|SecondSection|MinuteSection|Hour12Section|Hour24Section),
Internal = 0x10000, DaySection = 0x00100, MonthSection = 0x00200, YearSection = 0x00400,
YearSection2Digits = 0x00800, DayOfWeekSection = 0x01000, DateSectionMask = (DaySection|MonthSection|YearSection|YearSection2Digits|DayOfWeekSection), FirstSection = 0x02000|Internal,
LastSection = 0x04000|Internal, CalendarPopupSection = 0x08000|Internal, NoSectionIndex = -1, FirstSectionIndex = -2,
LastSectionIndex = -3, CalendarPopupIndex = -4
}
enum State { Invalid, Intermediate, Acceptable }
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 73 of file qdatetimeedit_p.h.
Constructors and Destructors
QDateTimeEditPrivate()
QDateTimeEditPrivate::QDateTimeEditPrivate ()
Warning
This function is not part of the public interface. Constructs a QDateTimeEditPrivate object
Definition at line 1708 of file qdatetimeedit.cpp.
     : QDateTimeParser(QVariant::DateTime, QDateTimeParser::DateTimeEdit)
 {
     hasHadFocus = false;
     formatExplicitlySet = false;
     cacheGuard = false;
     fixday = true;
     type = QVariant::DateTime;
     sections = 0;
     cachedDay = -1;
     currentSectionIndex = FirstSectionIndex;
     first.type = FirstSection;
     last.type = LastSection;
     none.type = NoSection;
     first.pos = 0;
     last.pos = -1;
     none.pos = -1;
     sections = 0;
     calendarPopup = false;
     minimum = QDATETIMEEDIT_COMPAT_DATETIME_MIN;
     maximum = QDATETIMEEDIT_DATETIME_MAX;
     arrowState = QStyle::State_None;
     monthCalendar = 0;
     readLocaleSettings();
 #ifdef QT_KEYPAD_NAVIGATION
     focusOnButton = false;
 #endif
 }
Functions
_q_editorCursorPositionChanged()
void QDateTimeEditPrivate::_q_editorCursorPositionChanged (int oldpos, int newpos) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2234 of file qdatetimeedit.cpp.
 {
     if (ignoreCursorPositionChanged || specialValue())
         return;
     const QString oldText = displayText();
     updateCache(value, oldText);
     const bool allowChange = !edit->hasSelectedText();
     const bool forward = oldpos <= newpos;
     ignoreCursorPositionChanged = true;
     int s = sectionAt(newpos);
     if (s == NoSectionIndex && forward && newpos > 0) {
         s = sectionAt(newpos - 1);
     }
     int c = newpos;
     const int selstart = edit->selectionStart();
     const int selSection = sectionAt(selstart);
     const int l = selSection != -1 ? sectionSize(selSection) : 0;
     if (s == NoSectionIndex) {
         if (l > 0 && selstart == sectionPos(selSection) && edit->selectedText().size() == l) {
             s = selSection;
             if (allowChange)
                 setSelected(selSection, true);
             c = -1;
         } else {
             int closest = closestSection(newpos, forward);
             c = sectionPos(closest) + (forward ? 0 : qMax<int>(0, sectionSize(closest)));
             if (allowChange) {
                 edit->setCursorPosition(c);
                 QDTEDEBUG << c;
             }
             s = closest;
         }
     }
     if (allowChange && currentSectionIndex != s) {
         interpret(EmitIfChanged);
     }
     if (c == -1) {
         setSelected(s, true);
     } else if (!edit->hasSelectedText()) {
         if (oldpos < newpos) {
             edit->setCursorPosition(displayText().size() - (oldText.size() - c));
         } else {
             edit->setCursorPosition(c);
         }
     }
     QDTEDEBUG << "currentSectionIndex is set to" << sectionName(sectionType(s))
               << oldpos << newpos
               << "was" << sectionName(sectionType(currentSectionIndex));
     currentSectionIndex = s;
     Q_ASSERT_X(currentSectionIndex < sectionNodes.size(),
                "QDateTimeEditPrivate::_q_editorCursorPositionChanged()",
                qPrintable(QString::fromAscii("Internal error (%1 %2)").
                           arg(currentSectionIndex).
                           arg(sectionNodes.size())));
     ignoreCursorPositionChanged = false;
 }
_q_resetButton()
void QDateTimeEditPrivate::_q_resetButton ()
Definition at line 2493 of file qdatetimeedit.cpp.
Referenced by cursorPosition(), and initCalendarPopup().
 {
     updateArrow(QStyle::State_None);
 }
absoluteIndex() [1/2]
int QDateTimeEditPrivate::absoluteIndex (QDateTimeEdit::Section s, int index) const
Definition at line 2397 of file qdatetimeedit.cpp.
Referenced by displayText().
 {
     for (int i=0; i<sectionNodes.size(); ++i) {
         if (convertToPublic(sectionNodes.at(i).type) == s && index-- == 0) {
             return i;
         }
     }
     return NoSectionIndex;
 }
absoluteIndex() [2/2]
int QDateTimeEditPrivate::absoluteIndex (const SectionNode & s) const
Definition at line 2407 of file qdatetimeedit.cpp.
 {
     return sectionNodes.indexOf(s);
 }
calendarPopupEnabled()
bool QDateTimeEditPrivate::calendarPopupEnabled () const
Definition at line 2631 of file qdatetimeedit.cpp.
Referenced by cursorPosition(), newHoverControl(), and updateEditFieldGeometry().
 {
     return (calendarPopup && (sections & (DateSectionMask)));
 }
clearCache()
void QDateTimeEditPrivate::clearCache () const virtual
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2428 of file qdatetimeedit.cpp.
Referenced by validateAndInterpret().
 {
     QAbstractSpinBoxPrivate::clearCache();
     cachedDay = -1;
 }
clearSection()
void QDateTimeEditPrivate::clearSection (int index)
Clears the text of section s.
Warning
This function is not part of the public interface.
Definition at line 1925 of file qdatetimeedit.cpp.
 {
     const QLatin1Char space(' ');
     int cursorPos = edit->cursorPosition();
     bool blocked = edit->blockSignals(true);
     QString t = edit->text();
     const int pos = sectionPos(index);
     if (pos == -1) {
         qWarning("QDateTimeEdit: Internal error (%s:%d)", __FILE__, __LINE__);
         return;
     }
     const int size = sectionSize(index);
     t.replace(pos, size, QString().fill(space, size));
     edit->setText(t);
     edit->setCursorPosition(cursorPos);
     QDTEDEBUG << cursorPos;
     edit->blockSignals(blocked);
 }
closestSection()
int QDateTimeEditPrivate::closestSection (int pos, bool forward) const
Returns the closest section of index index.
Warning
This function is not part of the public interface.
Searches forward for a section if forward is true. Otherwise searches backwards.
Definition at line 1859 of file qdatetimeedit.cpp.
Referenced by _q_editorCursorPositionChanged(), and displayText().
 {
     Q_ASSERT(pos >= 0);
     if (pos < separators.first().size()) {
         return forward ? 0 : FirstSectionIndex;
     } else if (displayText().size() - pos < separators.last().size() + 1) {
         return forward ? LastSectionIndex : sectionNodes.size() - 1;
     }
     updateCache(value, displayText());
     for (int i=0; i<sectionNodes.size(); ++i) {
         const int tmp = sectionPos(sectionNodes.at(i));
         if (pos < tmp + sectionSize(i)) {
             if (pos < tmp && !forward) {
                 return i-1;
             }
             return i;
         } else if (i == sectionNodes.size() - 1 && pos > tmp) {
             return i;
         }
     }
     qWarning("QDateTimeEdit: Internal Error: closestSection returned NoSection");
     return NoSectionIndex;
 }
convertSections()
QDateTimeEdit::Sections QDateTimeEditPrivate::convertSections (QDateTimeParser::Sections s) static
Definition at line 2334 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     QDateTimeEdit::Sections ret = 0;
     if (s & QDateTimeParser::MSecSection)
         ret |= QDateTimeEdit::MSecSection;
     if (s & QDateTimeParser::SecondSection)
         ret |= QDateTimeEdit::SecondSection;
     if (s & QDateTimeParser::MinuteSection)
         ret |= QDateTimeEdit::MinuteSection;
     if (s & (QDateTimeParser::Hour24Section|QDateTimeParser::Hour12Section))
         ret |= QDateTimeEdit::HourSection;
     if (s & QDateTimeParser::AmPmSection)
         ret |= QDateTimeEdit::AmPmSection;
     if (s & (QDateTimeParser::DaySection|QDateTimeParser::DayOfWeekSection))
         ret |= QDateTimeEdit::DaySection;
     if (s & QDateTimeParser::MonthSection)
         ret |= QDateTimeEdit::MonthSection;
     if (s & (QDateTimeParser::YearSection|QDateTimeParser::YearSection2Digits))
         ret |= QDateTimeEdit::YearSection;
     return ret;
 }
convertToPublic()
QDateTimeEdit::Section QDateTimeEditPrivate::convertToPublic (QDateTimeParser::Section s) static
Definition at line 2313 of file qdatetimeedit.cpp.
Referenced by absoluteIndex(), and cursorPosition().
 {
     switch (s & ~Internal) {
     case AmPmSection: return QDateTimeEdit::AmPmSection;
     case MSecSection: return QDateTimeEdit::MSecSection;
     case SecondSection: return QDateTimeEdit::SecondSection;
     case MinuteSection: return QDateTimeEdit::MinuteSection;
     case DayOfWeekSection:
     case DaySection: return QDateTimeEdit::DaySection;
     case MonthSection: return QDateTimeEdit::MonthSection;
     case YearSection2Digits:
     case YearSection: return QDateTimeEdit::YearSection;
     case Hour12Section:
     case Hour24Section: return QDateTimeEdit::HourSection;
     case FirstSection:
     case NoSection:
     case LastSection: break;
     }
     return QDateTimeEdit::NoSection;
 }
cursorPosition()
int QDateTimeEditPrivate::cursorPosition () const inline virtual
Reimplemented from QDateTimeParser.
Definition at line 111 of file qdatetimeedit_p.h.
 { return edit ? edit->cursorPosition() : -1; }
displayText()
virtual QString QDateTimeEditPrivate::displayText () const inline virtual
Reimplemented from QDateTimeParser.
Definition at line 92 of file qdatetimeedit_p.h.
Referenced by _q_editorCursorPositionChanged(), closestSection(), emitSignals(), interpret(), sectionAt(), setSelected(), stepBy(), and updateEdit().
 { return edit->text(); } // this is from QDateTimeParser
emitSignals()
void QDateTimeEditPrivate::emitSignals (EmitPolicy ep, const QVariant & old) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2205 of file qdatetimeedit.cpp.
 {
     Q_Q(QDateTimeEdit);
     if (ep == NeverEmit) {
         return;
     }
     pendingEmit = false;
     const bool dodate = value.toDate().isValid() && (sections & DateSectionMask);
     const bool datechanged = (ep == AlwaysEmit || old.toDate() != value.toDate());
     const bool dotime = value.toTime().isValid() && (sections & TimeSectionMask);
     const bool timechanged = (ep == AlwaysEmit || old.toTime() != value.toTime());
     updateCache(value, displayText());
     syncCalendarWidget();
     if (datechanged || timechanged)
         emit q->dateTimeChanged(value.toDateTime());
     if (dodate && datechanged)
         emit q->dateChanged(value.toDate());
     if (dotime && timechanged)
         emit q->timeChanged(value.toTime());
 }
getAmPmText()
QString QDateTimeEditPrivate::getAmPmText (AmPm ap, Case cs) const virtual
Reimplemented from QDateTimeParser.
Definition at line 2388 of file qdatetimeedit.cpp.
Referenced by valueToText().
 {
     if (ap == AmText) {
         return (cs == UpperCase ? QDateTimeEdit::tr("AM") : QDateTimeEdit::tr("am"));
     } else {
         return (cs == UpperCase ? QDateTimeEdit::tr("PM") : QDateTimeEdit::tr("pm"));
     }
 }
getMaximum()
virtual QDateTime QDateTimeEditPrivate::getMaximum () const inline virtual
Reimplemented from QDateTimeParser.
Definition at line 107 of file qdatetimeedit_p.h.
 { return maximum.toDateTime(); }
getMinimum()
virtual QDateTime QDateTimeEditPrivate::getMinimum () const inline virtual
Reimplemented from QDateTimeParser.
Definition at line 106 of file qdatetimeedit_p.h.
 { return minimum.toDateTime(); }
getZeroVariant()
QVariant QDateTimeEditPrivate::getZeroVariant () const virtual
Convenience function to get a variant of the right type.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2554 of file qdatetimeedit.cpp.
Referenced by cursorPosition(), and validateAndInterpret().
 {
     Q_ASSERT(type == QVariant::DateTime);
     return QDateTime(QDATETIMEEDIT_DATE_INITIAL, QTime(), spec);
 }
init()
void QDateTimeEditPrivate::init (const QVariant & var)
Definition at line 2458 of file qdatetimeedit.cpp.
 {
     Q_Q(QDateTimeEdit);
     switch (var.type()) {
     case QVariant::Date:
         value = QDateTime(var.toDate(), QDATETIMEEDIT_TIME_MIN);
         q->setDisplayFormat(defaultDateFormat);
         if (sectionNodes.isEmpty()) // ### safeguard for broken locale
             q->setDisplayFormat(QLatin1String("dd/MM/yyyy"));
         break;
     case QVariant::DateTime:
         value = var;
         q->setDisplayFormat(defaultDateTimeFormat);
         if (sectionNodes.isEmpty()) // ### safeguard for broken locale
             q->setDisplayFormat(QLatin1String("dd/MM/yyyy hh:mm:ss"));
         break;
     case QVariant::Time:
         value = QDateTime(QDATETIMEEDIT_DATE_INITIAL, var.toTime());
         q->setDisplayFormat(defaultTimeFormat);
         if (sectionNodes.isEmpty()) // ### safeguard for broken locale
             q->setDisplayFormat(QLatin1String("hh:mm:ss"));
         break;
     default:
         Q_ASSERT_X(0, "QDateTimeEditPrivate::init", "Internal error");
         break;
     }
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled())
         q->setCalendarPopup(true);
 #endif
     updateTimeSpec();
     q->setInputMethodHints(Qt::ImhPreferNumbers);
     setLayoutItemMargins(QStyle::SE_DateTimeEditLayoutItem);
 }
initCalendarPopup()
void QDateTimeEditPrivate::initCalendarPopup (QCalendarWidget * cw = 0)
Definition at line 2581 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     Q_Q(QDateTimeEdit);
     if (!monthCalendar) {
         monthCalendar = new QCalendarPopup(q, cw);
         monthCalendar->setObjectName(QLatin1String("qt_datetimedit_calendar"));
         QObject::connect(monthCalendar, SIGNAL(newDateSelected(QDate)), q, SLOT(setDate(QDate)));
         QObject::connect(monthCalendar, SIGNAL(hidingCalendar(QDate)), q, SLOT(setDate(QDate)));
         QObject::connect(monthCalendar, SIGNAL(activated(QDate)), q, SLOT(setDate(QDate)));
         QObject::connect(monthCalendar, SIGNAL(activated(QDate)), monthCalendar, SLOT(close()));
         QObject::connect(monthCalendar, SIGNAL(resetButton()), q, SLOT(_q_resetButton()));
     } else if (cw) {
         monthCalendar->setCalendarWidget(cw);
     }
     syncCalendarWidget();
 }
interpret()
void QDateTimeEditPrivate::interpret (EmitPolicy ep) virtual
Interprets text and emits signals.
Warning
This function is not part of the public interface.
Called when the spinbox needs to interpret the text on the lineedit.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2412 of file qdatetimeedit.cpp.
Referenced by _q_editorCursorPositionChanged().
 {
     Q_Q(QDateTimeEdit);
     QString tmp = displayText();
     int pos = edit->cursorPosition();
     const QValidator::State state = q->validate(tmp, pos);
     if (state != QValidator::Acceptable
         && correctionMode == QAbstractSpinBox::CorrectToPreviousValue
         && (state == QValidator::Invalid || !(fieldInfo(currentSectionIndex) & AllowPartial))) {
         setValue(value, ep);
         updateTimeSpec();
     } else {
         QAbstractSpinBoxPrivate::interpret(ep);
     }
 }
isSeparatorKey()
bool QDateTimeEditPrivate::isSeparatorKey (const QKeyEvent * k) const
Definition at line 2567 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     if (!ke->text().isEmpty() && currentSectionIndex + 1 < sectionNodes.size() && currentSectionIndex >= 0) {
         if (fieldInfo(currentSectionIndex) & Numeric) {
             if (ke->text().at(0).isNumber())
                 return false;
         } else if (ke->text().at(0).isLetterOrNumber()) {
             return false;
         }
         return separators.at(currentSectionIndex + 1).contains(ke->text());
     }
     return false;
 }
locale()
virtual QLocale QDateTimeEditPrivate::locale () const inline virtual
Reimplemented from QDateTimeParser.
Definition at line 108 of file qdatetimeedit_p.h.
 { return q_func()->locale(); }
newHoverControl()
QStyle::SubControl QDateTimeEditPrivate::newHoverControl (const QPoint & pos) virtual
Returns the hover control at pos.
Warning
This function is not part of the public interface.
This will update the hoverRect and hoverControl.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2522 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     if (!calendarPopupEnabled())
         return QAbstractSpinBoxPrivate::newHoverControl(pos);
     Q_Q(QDateTimeEdit);
     QStyleOptionComboBox optCombo;
     optCombo.init(q);
     optCombo.editable = true;
     optCombo.subControls = QStyle::SC_All;
     hoverControl = q->style()->hitTestComplexControl(QStyle::CC_ComboBox, &optCombo, pos, q);
     return hoverControl;
 }
nextPrevSection()
int QDateTimeEditPrivate::nextPrevSection (int current, bool forward) const
Returns a copy of the section that is before or after current, depending on forward.
Warning
This function is not part of the public interface.
Definition at line 1892 of file qdatetimeedit.cpp.
Referenced by displayText().
 {
     Q_Q(const QDateTimeEdit);
     if (q->isRightToLeft())
         forward = !forward;
     switch (current) {
     case FirstSectionIndex: return forward ? 0 : FirstSectionIndex;
     case LastSectionIndex: return (forward ? LastSectionIndex : sectionNodes.size() - 1);
     case NoSectionIndex: return FirstSectionIndex;
     default: break;
     }
     Q_ASSERT(current >= 0 && current < sectionNodes.size());
     current += (forward ? 1 : -1);
     if (current >= sectionNodes.size()) {
         return LastSectionIndex;
     } else if (current < 0) {
         return FirstSectionIndex;
     }
     return current;
 }
positionCalendarPopup()
void QDateTimeEditPrivate::positionCalendarPopup ()
Definition at line 2598 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     Q_Q(QDateTimeEdit);
     QPoint pos = (q->layoutDirection() == Qt::RightToLeft) ? q->rect().bottomRight() : q->rect().bottomLeft();
     QPoint pos2 = (q->layoutDirection() == Qt::RightToLeft) ? q->rect().topRight() : q->rect().topLeft();
     pos = q->mapToGlobal(pos);
     pos2 = q->mapToGlobal(pos2);
     QSize size = monthCalendar->sizeHint();
     QRect screen = QApplication::desktop()->availableGeometry(pos);
     //handle popup falling "off screen"
     if (q->layoutDirection() == Qt::RightToLeft) {
         pos.setX(pos.x()-size.width());
         pos2.setX(pos2.x()-size.width());
         if (pos.x() < screen.left())
             pos.setX(qMax(pos.x(), screen.left()));
         else if (pos.x()+size.width() > screen.right())
             pos.setX(qMax(pos.x()-size.width(), screen.right()-size.width()));
     } else {
         if (pos.x()+size.width() > screen.right())
             pos.setX(screen.right()-size.width());
         pos.setX(qMax(pos.x(), screen.left()));
     }
     if (pos.y() + size.height() > screen.bottom())
         pos.setY(pos2.y() - size.height());
     else if (pos.y() < screen.top())
         pos.setY(screen.top());
     if (pos.y() < screen.top())
         pos.setY(screen.top());
     if (pos.y()+size.height() > screen.bottom())
         pos.setY(screen.bottom()-size.height());
     monthCalendar->move(pos);
 }
readLocaleSettings()
void QDateTimeEditPrivate::readLocaleSettings ()
Warning
This function is not part of the public interface.
Try to get the format from the local settings
Definition at line 2305 of file qdatetimeedit.cpp.
Referenced by QDateTimeEditPrivate().
 {
     const QLocale loc;
     defaultTimeFormat = loc.timeFormat(QLocale::ShortFormat);
     defaultDateFormat = loc.dateFormat(QLocale::ShortFormat);
     defaultDateTimeFormat = loc.dateTimeFormat(QLocale::ShortFormat);
 }
sectionAt()
int QDateTimeEditPrivate::sectionAt (int pos) const
Returns the section at index index or NoSection if there are no sections there.
Warning
This function is not part of the public interface.
Definition at line 1828 of file qdatetimeedit.cpp.
Referenced by _q_editorCursorPositionChanged(), and displayText().
 {
     if (pos < separators.first().size()) {
         return (pos == 0 ? FirstSectionIndex : NoSectionIndex);
     } else if (displayText().size() - pos < separators.last().size() + 1) {
         if (separators.last().size() == 0) {
             return sectionNodes.count() - 1;
         }
         return (pos == displayText().size() ? LastSectionIndex : NoSectionIndex);
     }
     updateCache(value, displayText());
     for (int i=0; i<sectionNodes.size(); ++i) {
         const int tmp = sectionPos(i);
         if (pos < tmp + sectionSize(i)) {
             return (pos < tmp ? -1 : i);
         }
     }
     return -1;
 }
setRange()
void QDateTimeEditPrivate::setRange (const QVariant & min, const QVariant & max) virtual
Convenience function to set min/max values.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2560 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     QAbstractSpinBoxPrivate::setRange(min, max);
     syncCalendarWidget();
 }
setSelected()
void QDateTimeEditPrivate::setSelected (int sectionIndex, bool forward = false)
Selects the section s.
Warning
This function is not part of the public interface.
If forward is false selects backwards.
Definition at line 1796 of file qdatetimeedit.cpp.
Referenced by _q_editorCursorPositionChanged(), and displayText().
 {
     if (specialValue()
 #ifdef QT_KEYPAD_NAVIGATION
         || (QApplication::keypadNavigationEnabled() && !edit->hasEditFocus())
 #endif
         ) {
         edit->selectAll();
     } else {
         const SectionNode &node = sectionNode(sectionIndex);
         if (node.type == NoSection || node.type == LastSection || node.type == FirstSection)
             return;
         updateCache(value, displayText());
         const int size = sectionSize(sectionIndex);
         if (forward) {
             edit->setSelection(sectionPos(node), size);
         } else {
             edit->setSelection(sectionPos(node) + size, -size);
         }
     }
 }
stepBy()
QDateTime QDateTimeEditPrivate::stepBy (int sectionIndex, int steps, bool test = false) const
Internal function called by QDateTimeEdit::stepBy().
Warning
This function is not part of the public interface.
Also takes a Section for which section to step on and a bool test for whether or not to modify the internal cachedDay variable. This is necessary because the function is called from the const function QDateTimeEdit::stepEnabled() as well as QDateTimeEdit::stepBy().
Definition at line 2068 of file qdatetimeedit.cpp.
Referenced by displayText().
 {
     Q_Q(const QDateTimeEdit);
     QDateTime v = value.toDateTime();
     QString str = displayText();
     int pos = edit->cursorPosition();
     const SectionNode sn = sectionNode(sectionIndex);
     int val;
     // to make sure it behaves reasonably when typing something and then stepping in non-tracking mode
     if (!test && pendingEmit) {
         if (q->validate(str, pos) != QValidator::Acceptable) {
             v = value.toDateTime();
         } else {
             v = q->dateTimeFromText(str);
         }
         val = getDigit(v, sectionIndex);
     } else {
         val = getDigit(v, sectionIndex);
     }
     val += steps;
     const int min = absoluteMin(sectionIndex);
     const int max = absoluteMax(sectionIndex, value.toDateTime());
     if (val < min) {
         val = (wrapping ? max - (min - val) + 1 : min);
     } else if (val > max) {
         val = (wrapping ? min + val - max - 1 : max);
     }
     const int oldDay = v.date().day();
     setDigit(v, sectionIndex, val);
     // if this sets year or month it will make
     // sure that days are lowered if needed.
     const QDateTime minimumDateTime = minimum.toDateTime();
     const QDateTime maximumDateTime = maximum.toDateTime();
     // changing one section should only modify that section, if possible
     if (sn.type != AmPmSection && (v < minimumDateTime || v > maximumDateTime)) {
         const int localmin = getDigit(minimumDateTime, sectionIndex);
         const int localmax = getDigit(maximumDateTime, sectionIndex);
         if (wrapping) {
             // just because we hit the roof in one direction, it
             // doesn't mean that we hit the floor in the other
             if (steps > 0) {
                 setDigit(v, sectionIndex, min);
                 if (!(sn.type & (DaySection|DayOfWeekSection)) && sections & DateSectionMask) {
                     const int daysInMonth = v.date().daysInMonth();
                     if (v.date().day() < oldDay && v.date().day() < daysInMonth) {
                         const int adds = qMin(oldDay, daysInMonth);
                         v = v.addDays(adds - v.date().day());
                     }
                 }
                 if (v < minimumDateTime) {
                     setDigit(v, sectionIndex, localmin);
                     if (v < minimumDateTime)
                         setDigit(v, sectionIndex, localmin + 1);
                 }
             } else {
                 setDigit(v, sectionIndex, max);
                 if (!(sn.type & (DaySection|DayOfWeekSection)) && sections & DateSectionMask) {
                     const int daysInMonth = v.date().daysInMonth();
                     if (v.date().day() < oldDay && v.date().day() < daysInMonth) {
                         const int adds = qMin(oldDay, daysInMonth);
                         v = v.addDays(adds - v.date().day());
                     }
                 }
                 if (v > maximumDateTime) {
                     setDigit(v, sectionIndex, localmax);
                     if (v > maximumDateTime)
                         setDigit(v, sectionIndex, localmax - 1);
                 }
             }
         } else {
             setDigit(v, sectionIndex, (steps > 0 ? localmax : localmin));
         }
     }
     if (!test && oldDay != v.date().day() && !(sn.type & (DaySection|DayOfWeekSection))) {
         // this should not happen when called from stepEnabled
         cachedDay = qMax<int>(oldDay, cachedDay);
     }
     if (v < minimumDateTime) {
         if (wrapping) {
             QDateTime t = v;
             setDigit(t, sectionIndex, steps < 0 ? max : min);
             bool mincmp = (t >= minimumDateTime);
             bool maxcmp = (t <= maximumDateTime);
             if (!mincmp || !maxcmp) {
                 setDigit(t, sectionIndex, getDigit(steps < 0
                                                    ? maximumDateTime
                                                    : minimumDateTime, sectionIndex));
                 mincmp = (t >= minimumDateTime);
                 maxcmp = (t <= maximumDateTime);
             }
             if (mincmp && maxcmp) {
                 v = t;
             }
         } else {
             v = value.toDateTime();
         }
     } else if (v > maximumDateTime) {
         if (wrapping) {
             QDateTime t = v;
             setDigit(t, sectionIndex, steps > 0 ? min : max);
             bool mincmp = (t >= minimumDateTime);
             bool maxcmp = (t <= maximumDateTime);
             if (!mincmp || !maxcmp) {
                 setDigit(t, sectionIndex, getDigit(steps > 0 ?
                                                    minimumDateTime :
                                                    maximumDateTime, sectionIndex));
                 mincmp = (t >= minimumDateTime);
                 maxcmp = (t <= maximumDateTime);
             }
             if (mincmp && maxcmp) {
                 v = t;
             }
         } else {
             v = value.toDateTime();
         }
     }
     const QDateTime ret = bound(v, value, steps).toDateTime().toTimeSpec(spec);
     return ret;
 }
syncCalendarWidget()
void QDateTimeEditPrivate::syncCalendarWidget ()
Definition at line 2636 of file qdatetimeedit.cpp.
Referenced by cursorPosition(), emitSignals(), initCalendarPopup(), and setRange().
 {
     Q_Q(QDateTimeEdit);
     if (monthCalendar) {
         const bool sb = monthCalendar->blockSignals(true);
         monthCalendar->setDateRange(q->minimumDate(), q->maximumDate());
         monthCalendar->setDate(q->date());
         monthCalendar->blockSignals(sb);
     }
 }
textFromValue()
QString QDateTimeEditPrivate::textFromValue (const QVariant & f) const virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2032 of file qdatetimeedit.cpp.
Referenced by updateEdit(), validateAndInterpret(), and valueToText().
 {
     Q_Q(const QDateTimeEdit);
     return q->textFromDateTime(f.toDateTime());
 }
updateArrow()
void QDateTimeEditPrivate::updateArrow (QStyle::StateFlag state)
Definition at line 2498 of file qdatetimeedit.cpp.
Referenced by _q_resetButton(), and cursorPosition().
 {
     Q_Q(QDateTimeEdit);
     if (arrowState == state)
         return;
     arrowState = state;
     if (arrowState != QStyle::State_None)
         buttonState |= Mouse;
     else {
         buttonState = 0;
         hoverControl = QStyle::SC_ComboBoxFrame;
     }
     q->update();
 }
updateCache()
void QDateTimeEditPrivate::updateCache (const QVariant & val, const QString & str) const
Warning
This function is not part of the public interface.
updates the cached values
Definition at line 1952 of file qdatetimeedit.cpp.
Referenced by _q_editorCursorPositionChanged(), closestSection(), displayText(), emitSignals(), sectionAt(), setSelected(), and validateAndInterpret().
 {
     if (val != cachedValue || str != cachedText || cacheGuard) {
         cacheGuard = true;
         QString copy = str;
         int unused = edit->cursorPosition();
         QValidator::State unusedState;
         validateAndInterpret(copy, unused, unusedState);
         cacheGuard = false;
     }
 }
updateEdit()
void QDateTimeEditPrivate::updateEdit () virtual
Updates the line edit to reflect the current value of the spin box.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 1755 of file qdatetimeedit.cpp.
Referenced by displayText().
 {
     const QString newText = (specialValue() ? specialValueText : textFromValue(value));
     if (newText == displayText())
         return;
     int selsize = edit->selectedText().size();
     const bool sb = edit->blockSignals(true);
     edit->setText(newText);
     if (!specialValue()
 #ifdef QT_KEYPAD_NAVIGATION
         && !(QApplication::keypadNavigationEnabled() && !edit->hasEditFocus())
 #endif
             ) {
         int cursor = sectionPos(currentSectionIndex);
         QDTEDEBUG << "cursor is " << cursor << currentSectionIndex;
         cursor = qBound(0, cursor, displayText().size());
         QDTEDEBUG << cursor;
         if (selsize > 0) {
             edit->setSelection(cursor, selsize);
             QDTEDEBUG << cursor << selsize;
         } else {
             edit->setCursorPosition(cursor);
             QDTEDEBUG << cursor;
         }
     }
     edit->blockSignals(sb);
 }
updateEditFieldGeometry()
void QDateTimeEditPrivate::updateEditFieldGeometry () virtual
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2537 of file qdatetimeedit.cpp.
Referenced by cursorPosition().
 {
     if (!calendarPopupEnabled()) {
         QAbstractSpinBoxPrivate::updateEditFieldGeometry();
         return;
     }
     Q_Q(QDateTimeEdit);
     QStyleOptionComboBox optCombo;
     optCombo.init(q);
     optCombo.editable = true;
     optCombo.subControls = QStyle::SC_ComboBoxEditField;
     edit->setGeometry(q->style()->subControlRect(QStyle::CC_ComboBox, &optCombo,
                                                  QStyle::SC_ComboBoxEditField, q));
 }
updateTimeSpec()
void QDateTimeEditPrivate::updateTimeSpec ()
Definition at line 1739 of file qdatetimeedit.cpp.
Referenced by displayText(), init(), and interpret().
 {
     minimum = minimum.toDateTime().toTimeSpec(spec);
     maximum = maximum.toDateTime().toTimeSpec(spec);
     value = value.toDateTime().toTimeSpec(spec);
     // time zone changes can lead to 00:00:00 becomes 01:00:00 and 23:59:59 becomes 00:59:59 (invalid range)
     const bool dateShown = (sections & QDateTimeEdit::DateSections_Mask);
     if (!dateShown) {
         if (minimum.toTime() >= maximum.toTime()){
             minimum = QDateTime(value.toDate(), QDATETIMEEDIT_TIME_MIN, spec);
             maximum = QDateTime(value.toDate(), QDATETIMEEDIT_TIME_MAX, spec);
         }
     }
 }
validateAndInterpret()
QDateTime QDateTimeEditPrivate::validateAndInterpret (QString & input, int & position, QValidator::State & state, bool fixup = false) const
Warning
This function is not part of the public interface.
parses and validates input
Definition at line 1970 of file qdatetimeedit.cpp.
Referenced by updateCache().
 {
     if (input.isEmpty()) {
         if (sectionNodes.size() == 1 || !specialValueText.isEmpty()) {
             state = QValidator::Intermediate;
         } else {
             state = QValidator::Invalid;
         }
         return getZeroVariant().toDateTime();
     } else if (cachedText == input && !fixup) {
         state = cachedState;
         return cachedValue.toDateTime();
     } else if (!specialValueText.isEmpty()) {
         bool changeCase = false;
         const int max = qMin(specialValueText.size(), input.size());
         int i;
         for (i=0; i<max; ++i) {
             const QChar ic = input.at(i);
             const QChar sc = specialValueText.at(i);
             if (ic != sc) {
                 if (sc.toLower() == ic.toLower()) {
                     changeCase = true;
                 } else {
                     break;
                 }
             }
         }
         if (i == max) {
             state = specialValueText.size() == input.size() ? QValidator::Acceptable : QValidator::Intermediate;
             if (changeCase) {
                 input = specialValueText.left(max);
             }
             return minimum.toDateTime();
         }
     }
     StateNode tmp = parse(input, position, value.toDateTime(), fixup);
     input = tmp.input;
     state = QValidator::State(int(tmp.state));
     if (state == QValidator::Acceptable) {
         if (tmp.conflicts && conflictGuard != tmp.value) {
             conflictGuard = tmp.value;
             clearCache();
             input = textFromValue(tmp.value);
             updateCache(tmp.value, input);
             conflictGuard.clear();
         } else {
             cachedText = input;
             cachedState = state;
             cachedValue = tmp.value;
         }
     } else {
         clearCache();
     }
     return (tmp.value.isNull() ? getZeroVariant().toDateTime() : tmp.value);
 }
valueFromText()
QVariant QDateTimeEditPrivate::valueFromText (const QString & f) const virtual
This function's name is slightly confusing; it is not to be confused with QAbstractSpinBox::valueFromText().
Warning
This function is not part of the public interface.
Reimplemented from QAbstractSpinBoxPrivate.
Definition at line 2048 of file qdatetimeedit.cpp.
 {
     Q_Q(const QDateTimeEdit);
     return q->dateTimeFromText(f).toTimeSpec(spec);
 }
valueToText()
QString QDateTimeEditPrivate::valueToText (const QVariant & var) const inline
Definition at line 109 of file qdatetimeedit_p.h.
 { return textFromValue(var); }
Properties
arrowState
QStyle::StateFlag QDateTimeEditPrivate::arrowState
Definition at line 137 of file qdatetimeedit_p.h.
Referenced by QDateTimeEditPrivate(), and updateArrow().
cacheGuard
bool QDateTimeEditPrivate::cacheGuard mutable
Definition at line 132 of file qdatetimeedit_p.h.
Referenced by QDateTimeEditPrivate(), and updateCache().
calendarPopup
bool QDateTimeEditPrivate::calendarPopup
Definition at line 136 of file qdatetimeedit_p.h.
Referenced by calendarPopupEnabled(), and QDateTimeEditPrivate().
conflictGuard
QVariant QDateTimeEditPrivate::conflictGuard mutable
Definition at line 135 of file qdatetimeedit_p.h.
Referenced by validateAndInterpret().
defaultDateFormat
QString QDateTimeEditPrivate::defaultDateFormat
Definition at line 134 of file qdatetimeedit_p.h.
Referenced by init(), and readLocaleSettings().
defaultDateTimeFormat
QString QDateTimeEditPrivate::defaultDateTimeFormat
Definition at line 134 of file qdatetimeedit_p.h.
Referenced by init(), and readLocaleSettings().
defaultTimeFormat
QString QDateTimeEditPrivate::defaultTimeFormat
Definition at line 134 of file qdatetimeedit_p.h.
Referenced by init(), and readLocaleSettings().
formatExplicitlySet
bool QDateTimeEditPrivate::formatExplicitlySet
Definition at line 136 of file qdatetimeedit_p.h.
Referenced by QDateTimeEditPrivate().
hasHadFocus
bool QDateTimeEditPrivate::hasHadFocus
Definition at line 136 of file qdatetimeedit_p.h.
Referenced by QDateTimeEditPrivate().
monthCalendar
QCalendarPopup* QDateTimeEditPrivate::monthCalendar
Definition at line 138 of file qdatetimeedit_p.h.
Referenced by initCalendarPopup(), positionCalendarPopup(), QDateTimeEditPrivate(), and syncCalendarWidget().
sections
QDateTimeEdit::Sections QDateTimeEditPrivate::sections
Definition at line 131 of file qdatetimeedit_p.h.
Referenced by calendarPopupEnabled(), emitSignals(), QDateTimeEditPrivate(), stepBy(), and updateTimeSpec().
unreversedFormat
QString QDateTimeEditPrivate::unreversedFormat
Definition at line 134 of file qdatetimeedit_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qdatetimeedit_p.h
/src/gui/widgets/qdatetimeedit.cpp