Qt 4.8: QEucJpCodec Class Reference
QEucJpCodec Class Reference
#include <qeucjpcodec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
QEucJpCodec ()
Constructs a QEucJpCodec.
~QEucJpCodec ()
Destroys the codec.
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Protected Variables
const QJpUnicodeConv * conv
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
Note
This class or function is reentrant.
Warning
This function is not part of the public interface.
Definition at line 82 of file qeucjpcodec.h.
Constructors and Destructors
QEucJpCodec()
QEucJpCodec::QEucJpCodec ()
Constructs a QEucJpCodec.
Definition at line 93 of file qeucjpcodec.cpp.
Referenced by mibEnum().
                          : conv(QJpUnicodeConv::newConverter(QJpUnicodeConv::Default))
 {
 }
~QEucJpCodec()
QEucJpCodec::~QEucJpCodec ()
Destroys the codec.
Definition at line 100 of file qeucjpcodec.cpp.
Referenced by mibEnum().
 {
     delete (QJpUnicodeConv*)conv;
     conv = 0;
 }
Functions
_aliases()
static QList<QByteArray> QEucJpCodec::_aliases () inline static
Definition at line 85 of file qeucjpcodec.h.
Referenced by JPTextCodecs::aliases(), aliases(), and JPTextCodecs::createForName().
 { return QList<QByteArray>(); }
_mibEnum()
int QEucJpCodec::_mibEnum () static
Definition at line 250 of file qeucjpcodec.cpp.
Referenced by _aliases(), JPTextCodecs::createForMib(), mibEnum(), and JPTextCodecs::mibEnums().
 {
     return 18;
 }
_name()
QByteArray QEucJpCodec::_name () static
Definition at line 255 of file qeucjpcodec.cpp.
Referenced by JPTextCodecs::createForName(), name(), and JPTextCodecs::names().
 {
     return "EUC-JP";
 }
aliases()
QList<QByteArray> QEucJpCodec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QTextCodec.
Definition at line 89 of file qeucjpcodec.h.
 { return _aliases(); }
convertFromUnicode()
QByteArray QEucJpCodec::convertFromUnicode (const QChar * input, int number, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first number of characters from the input array from Unicode to the encoding of the subclass, and returns the result in a QByteArray.
state can be 0 in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 106 of file qeucjpcodec.cpp.
Referenced by mibEnum().
 {
     char replacement = '?';
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = 0;
     }
     int invalid = 0;
     int rlen = 3*len + 1;
     QByteArray rstr;
     rstr.resize(rlen);
     uchar* cursor = (uchar*)rstr.data();
     for (int i = 0; i < len; i++) {
         QChar ch = uc[i];
         uint j;
         if (ch.unicode() < 0x80) {
             // ASCII
             *cursor++ = ch.cell();
         } else if ((j = conv->unicodeToJisx0201(ch.row(), ch.cell())) != 0) {
             if (j < 0x80) {
                 // JIS X 0201 Latin ?
                 *cursor++ = j;
             } else {
                 // JIS X 0201 Kana
                 *cursor++ = Ss2;
                 *cursor++ = j;
             }
         } else if ((j = conv->unicodeToJisx0208(ch.row(), ch.cell())) != 0) {
             // JIS X 0208
             *cursor++ = (j >> 8)   | 0x80;
             *cursor++ = (j & 0xff) | 0x80;
         } else if ((j = conv->unicodeToJisx0212(ch.row(), ch.cell())) != 0) {
             // JIS X 0212
             *cursor++ = Ss3;
             *cursor++ = (j >> 8)   | 0x80;
             *cursor++ = (j & 0xff) | 0x80;
         } else {
             // Error
             *cursor++ = replacement;
             ++invalid;
         }
     }
     rstr.resize(cursor - (uchar*)rstr.constData());
     if (state) {
         state->invalidChars += invalid;
     }
     return rstr;
 }
convertToUnicode()
QString QEucJpCodec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 158 of file qeucjpcodec.cpp.
Referenced by mibEnum().
 {
     uchar buf[2] = {0, 0};
     int nbuf = 0;
     QChar replacement = QChar::ReplacementCharacter;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = QChar::Null;
         nbuf = state->remainingChars;
         buf[0] = state->state_data[0];
         buf[1] = state->state_data[1];
     }
     int invalid = 0;
     QString result;
     for (int i=0; i<len; i++) {
         uchar ch = chars[i];
         switch (nbuf) {
         case 0:
             if (ch < 0x80) {
                 // ASCII
                 result += QLatin1Char(ch);
             } else if (ch == Ss2 || ch == Ss3) {
                 // JIS X 0201 Kana or JIS X 0212
                 buf[0] = ch;
                 nbuf = 1;
             } else if (IsEucChar(ch)) {
                 // JIS X 0208
                 buf[0] = ch;
                 nbuf = 1;
             } else {
                 // Invalid
                 result += replacement;
                 ++invalid;
             }
             break;
         case 1:
             if (buf[0] == Ss2) {
                 // JIS X 0201 Kana
                 if (IsKana(ch)) {
                     uint u = conv->jisx0201ToUnicode(ch);
                     result += QValidChar(u);
                 } else {
                     result += replacement;
                     ++invalid;
                 }
                 nbuf = 0;
             } else if (buf[0] == Ss3) {
                 // JIS X 0212-1990
                 if (IsEucChar(ch)) {
                     buf[1] = ch;
                     nbuf = 2;
                 } else {
                     // Error
                     result += replacement;
                     ++invalid;
                     nbuf = 0;
                 }
             } else {
                 // JIS X 0208-1990
                 if (IsEucChar(ch)) {
                     uint u = conv->jisx0208ToUnicode(buf[0] & 0x7f, ch & 0x7f);
                     result += QValidChar(u);
                 } else {
                     // Error
                     result += replacement;
                     ++invalid;
                 }
                 nbuf = 0;
             }
             break;
         case 2:
             // JIS X 0212
             if (IsEucChar(ch)) {
                 uint u = conv->jisx0212ToUnicode(buf[1] & 0x7f, ch & 0x7f);
                 result += QValidChar(u);
             } else {
                 result += replacement;
                 ++invalid;
             }
             nbuf = 0;
         }
     }
     if (state) {
         state->remainingChars = nbuf;
         state->state_data[0] = buf[0];
         state->state_data[1] = buf[1];
         state->invalidChars += invalid;
     }
     return result;
 }
mibEnum()
int QEucJpCodec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Definition at line 90 of file qeucjpcodec.h.
 { return _mibEnum(); }
name()
QByteArray QEucJpCodec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Definition at line 88 of file qeucjpcodec.h.
 { return _name(); }
Properties
conv
const QJpUnicodeConv* QEucJpCodec::conv protected
Definition at line 99 of file qeucjpcodec.h.
Referenced by convertFromUnicode(), convertToUnicode(), and ~QEucJpCodec().
The documentation for this class was generated from the following files:
/src/plugins/codecs/jp/qeucjpcodec.h
/src/plugins/codecs/jp/qeucjpcodec.cpp