Qt 4.8: QFileInfoGatherer Class Reference
QFileInfoGatherer Class Reference
#include <qfileinfogatherer_p.h>
Public Slots
void fetchExtendedInformation (const QString &path, const QStringList &files)
Fetch extended information for all files in path.
QFileIconProvider * iconProvider () const
void list (const QString &directoryPath)
bool resolveSymlinks () const
void setIconProvider (QFileIconProvider *provider)
void setResolveSymlinks (bool enable)
void updateFile (const QString &path)
Fetch extended information for all filePath.
Public Slots inherited from QThread
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void directoryLoaded (const QString &path)
void nameResolved (const QString &fileName, const QString &resolvedName) const
void newListOfFiles (const QString &directory, const QStringList &listOfFiles) const
void updates (const QString &directory, const QList< QPair< QString, QFileInfo > > &updates)
Signals inherited from QThread
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void clear ()
QExtendedInformation getInfo (const QFileInfo &info) const
QFileInfoGatherer (QObject *parent=0)
Creates thread.
void removePath (const QString &path)
~QFileInfoGatherer ()
Destroys thread.
Public Functions inherited from QThread
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void getFileInfos (const QString &path, const QStringList &files)
void run ()
The starting point for the thread.
Protected Functions inherited from QThread
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void fetch (const QFileInfo &info, QElapsedTimer &base, bool &firstTime, QList< QPair< QString, QFileInfo > > &updatedFiles, const QString &path)
QString translateDriveName (const QFileInfo &drive) const
Properties
volatile bool abort
QWaitCondition condition
QFileIconProvider defaultProvider
QStack< QStringList > files
QFileIconProvider * m_iconProvider
bool m_resolveSymlinks
QMutex mutex
QStack< QString > path
QFileSystemWatcher * watcher
Additional Inherited Members
Public Types inherited from QThread
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Static Public Functions inherited from QThread
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QThread
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 155 of file qfileinfogatherer_p.h.
Constructors and Destructors
QFileInfoGatherer()
QFileInfoGatherer::QFileInfoGatherer (QObject * parent = 0)
Creates thread.
Definition at line 74 of file qfileinfogatherer.cpp.
     : QThread(parent), abort(false),
 #ifndef QT_NO_FILESYSTEMWATCHER
       watcher(0),
 #endif
       m_resolveSymlinks(false), m_iconProvider(&defaultProvider)
 {
 #ifdef Q_OS_WIN
     m_resolveSymlinks = true;
 #elif !defined(Q_OS_INTEGRITY) && !defined(Q_OS_VXWORKS)
     userId = getuid();
     groupId = getgid();
 #endif
 #ifndef QT_NO_FILESYSTEMWATCHER
     watcher = new QFileSystemWatcher(this);
     connect(watcher, SIGNAL(directoryChanged(QString)), this, SLOT(list(QString)));
     connect(watcher, SIGNAL(fileChanged(QString)), this, SLOT(updateFile(QString)));
 #endif
     start(LowPriority);
 }
~QFileInfoGatherer()
QFileInfoGatherer::~QFileInfoGatherer ()
Destroys thread.
Definition at line 98 of file qfileinfogatherer.cpp.
 {
     QMutexLocker locker(&mutex);
     abort = true;
     condition.wakeOne();
     locker.unlock();
     wait();
 }
Functions
clear()
void QFileInfoGatherer::clear ()
Definition at line 170 of file qfileinfogatherer.cpp.
 {
 #ifndef QT_NO_FILESYSTEMWATCHER
     QMutexLocker locker(&mutex);
     watcher->removePaths(watcher->files());
     watcher->removePaths(watcher->directories());
 #endif
 }
directoryLoaded
void QFileInfoGatherer::directoryLoaded (const QString & path) signal
Referenced by getFileInfos().
fetch()
void QFileInfoGatherer::fetch (const QFileInfo & info, QElapsedTimer & base, bool & firstTime, QList< QPair< QString, QFileInfo > > & updatedFiles, const QString & path) private
Definition at line 341 of file qfileinfogatherer.cpp.
Referenced by getFileInfos().
{
     updatedFiles.append(QPair<QString, QFileInfo>(fileInfo.fileName(), fileInfo));
     QElapsedTimer current;
     current.start();
     if ((firstTime && updatedFiles.count() > 100) || base.msecsTo(current) > 1000) {
         emit updates(path, updatedFiles);
         updatedFiles.clear();
         base = current;
         firstTime = false;
     }
 }
fetchExtendedInformation
void QFileInfoGatherer::fetchExtendedInformation (const QString & path, const QStringList & files) slot
Fetch extended information for all files in path.
See also
updateFile(), update(), resolvedName()
Definition at line 137 of file qfileinfogatherer.cpp.
Referenced by list(), and updateFile().
 {
     QMutexLocker locker(&mutex);
     // See if we already have this dir/file in our que
     int loc = this->path.lastIndexOf(path);
     while (loc > 0)  {
         if (this->files.at(loc) == files) {
             return;
         }
         loc = this->path.lastIndexOf(path, loc - 1);
     }
     this->path.push(path);
     this->files.push(files);
     condition.wakeAll();
 }
getFileInfos()
void QFileInfoGatherer::getFileInfos (const QString & path, const QStringList & files) protected
Definition at line 279 of file qfileinfogatherer.cpp.
Referenced by run().
 {
 #ifndef QT_NO_FILESYSTEMWATCHER
     if (files.isEmpty()
         && !watcher->directories().contains(path)
         && !path.isEmpty()
         && !path.startsWith(QLatin1String("//")) /*don't watch UNC path*/) {
         watcher->addPath(path);
     }
 #endif
     // List drives
     if (path.isEmpty()) {
 #ifdef QT_BUILD_INTERNAL
         fetchedRoot = true;
 #endif
         QFileInfoList infoList;
         if (files.isEmpty()) {
             infoList = QDir::drives();
         } else {
             for (int i = 0; i < files.count(); ++i)
                 infoList << QFileInfo(files.at(i));
         }
         for (int i = infoList.count() - 1; i >= 0; --i) {
             QString driveName = translateDriveName(infoList.at(i));
             QList<QPair<QString,QFileInfo> > updatedFiles;
             updatedFiles.append(QPair<QString,QFileInfo>(driveName, infoList.at(i)));
             emit updates(path, updatedFiles);
         }
         return;
     }
     QElapsedTimer base;
     base.start();
     QFileInfo fileInfo;
     bool firstTime = true;
     QList<QPair<QString, QFileInfo> > updatedFiles;
     QStringList filesToCheck = files;
     QString itPath = QDir::fromNativeSeparators(files.isEmpty() ? path : QLatin1String(""));
     QDirIterator dirIt(itPath, QDir::AllEntries | QDir::System | QDir::Hidden);
     QStringList allFiles;
     while(!abort && dirIt.hasNext()) {
         dirIt.next();
         fileInfo = dirIt.fileInfo();
         allFiles.append(fileInfo.fileName());
     fetch(fileInfo, base, firstTime, updatedFiles, path);
     }
     if (!allFiles.isEmpty())
         emit newListOfFiles(path, allFiles);
     QStringList::const_iterator filesIt = filesToCheck.constBegin();
     while(!abort && filesIt != filesToCheck.constEnd()) {
         fileInfo.setFile(path + QDir::separator() + *filesIt);
         ++filesIt;
         fetch(fileInfo, base, firstTime, updatedFiles, path);
     }
     if (!updatedFiles.isEmpty())
         emit updates(path, updatedFiles);
     emit directoryLoaded(path);
 }
getInfo()
QExtendedInformation QFileInfoGatherer::getInfo (const QFileInfo & info) const
Definition at line 230 of file qfileinfogatherer.cpp.
 {
     QExtendedInformation info(fileInfo);
     info.icon = m_iconProvider->icon(fileInfo);
     info.displayType = m_iconProvider->type(fileInfo);
 #ifndef QT_NO_FILESYSTEMWATCHER
     // ### Not ready to listen all modifications
     #if 0
         // Enable the next two commented out lines to get updates when the file sizes change...
         if (!fileInfo.exists() && !fileInfo.isSymLink()) {
             info.size = -1;
             //watcher->removePath(fileInfo.absoluteFilePath());
         } else {
             if (!fileInfo.absoluteFilePath().isEmpty() && fileInfo.exists() && fileInfo.isReadable()
                 && !watcher->files().contains(fileInfo.absoluteFilePath())) {
                 //watcher->addPath(fileInfo.absoluteFilePath());
             }
         }
     #endif
 #endif
     if (m_resolveSymlinks && info.isSymLink(/* ignoreNtfsSymLinks = */ true)) {
         QFileInfo resolvedInfo(fileInfo.symLinkTarget());
         resolvedInfo = resolvedInfo.canonicalFilePath();
         if (resolvedInfo.exists()) {
             emit nameResolved(fileInfo.filePath(), resolvedInfo.fileName());
         }
     }
     return info;
 }
iconProvider
QFileIconProvider * QFileInfoGatherer::iconProvider () const slot
Definition at line 127 of file qfileinfogatherer.cpp.
 {
     return m_iconProvider;
 }
list
void QFileInfoGatherer::list (const QString & directoryPath) slot
Definition at line 197 of file qfileinfogatherer.cpp.
Referenced by QFileInfoGatherer(), and run().
 {
     fetchExtendedInformation(directoryPath, QStringList());
 }
nameResolved
void QFileInfoGatherer::nameResolved (const QString & fileName, const QString & resolvedName) const signal
Referenced by getInfo().
newListOfFiles
void QFileInfoGatherer::newListOfFiles (const QString & directory, const QStringList & listOfFiles) const signal
Referenced by getFileInfos().
removePath()
void QFileInfoGatherer::removePath (const QString & path)
Definition at line 184 of file qfileinfogatherer.cpp.
Referenced by QFileSystemModel::remove(), and QFileSystemModel::rmdir().
 {
 #ifndef QT_NO_FILESYSTEMWATCHER
     QMutexLocker locker(&mutex);
     watcher->removePath(path);
 #endif
 }
resolveSymlinks
bool QFileInfoGatherer::resolveSymlinks () const slot
Definition at line 116 of file qfileinfogatherer.cpp.
 {
     return m_resolveSymlinks;
 }
run()
void QFileInfoGatherer::run (void) protected virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented from QThread.
Definition at line 205 of file qfileinfogatherer.cpp.
 {
     forever {
         bool updateFiles = false;
         QMutexLocker locker(&mutex);
         if (abort) {
             return;
         }
         if (this->path.isEmpty())
             condition.wait(&mutex);
         QString path;
         QStringList list;
         if (!this->path.isEmpty()) {
             path = this->path.first();
             list = this->files.first();
             this->path.pop_front();
             this->files.pop_front();
             updateFiles = true;
         }
         locker.unlock();
         if (updateFiles)
             getFileInfos(path, list);
     }
 }
setIconProvider
void QFileInfoGatherer::setIconProvider (QFileIconProvider * provider) slot
Definition at line 121 of file qfileinfogatherer.cpp.
 {
     QMutexLocker locker(&mutex);
     m_iconProvider = provider;
 }
setResolveSymlinks
void QFileInfoGatherer::setResolveSymlinks (bool enable) slot
Definition at line 107 of file qfileinfogatherer.cpp.
 {
     Q_UNUSED(enable);
 #ifdef Q_OS_WIN
     QMutexLocker locker(&mutex);
     m_resolveSymlinks = enable;
 #endif
 }
translateDriveName()
QString QFileInfoGatherer::translateDriveName (const QFileInfo & drive) const private
Definition at line 261 of file qfileinfogatherer.cpp.
Referenced by getFileInfos().
 {
     QString driveName = drive.absoluteFilePath();
 #if defined(Q_OS_WIN) && !defined(Q_OS_WINCE)
     if (driveName.startsWith(QLatin1Char('/'))) // UNC host
         return drive.fileName();
 #endif
 #if (defined(Q_OS_WIN) && !defined(Q_OS_WINCE)) || defined(Q_OS_SYMBIAN)
     if (driveName.endsWith(QLatin1Char('/')))
         driveName.chop(1);
 #endif
     return driveName;
 }
updateFile
void QFileInfoGatherer::updateFile (const QString & filePath) slot
Fetch extended information for all filePath.
See also
fetchExtendedInformation()
Definition at line 158 of file qfileinfogatherer.cpp.
Referenced by QFileInfoGatherer().
 {
     QString dir = filePath.mid(0, filePath.lastIndexOf(QDir::separator()));
     QString fileName = filePath.mid(dir.length() + 1);
     fetchExtendedInformation(dir, QStringList(fileName));
 }
updates
void QFileInfoGatherer::updates (const QString & directory, const QList< QPair< QString, QFileInfo > > & updates) signal
Referenced by fetch(), and getFileInfos().
Properties
abort
volatile bool QFileInfoGatherer::abort private
Definition at line 192 of file qfileinfogatherer_p.h.
Referenced by getFileInfos(), run(), and ~QFileInfoGatherer().
condition
QWaitCondition QFileInfoGatherer::condition private
Definition at line 191 of file qfileinfogatherer_p.h.
Referenced by fetchExtendedInformation(), run(), and ~QFileInfoGatherer().
defaultProvider
QFileIconProvider QFileInfoGatherer::defaultProvider private
Definition at line 202 of file qfileinfogatherer_p.h.
files
QStack<QStringList> QFileInfoGatherer::files private
Definition at line 195 of file qfileinfogatherer_p.h.
Referenced by fetchExtendedInformation(), getFileInfos(), and run().
m_iconProvider
QFileIconProvider* QFileInfoGatherer::m_iconProvider private
Definition at line 201 of file qfileinfogatherer_p.h.
Referenced by getInfo(), iconProvider(), and setIconProvider().
m_resolveSymlinks
bool QFileInfoGatherer::m_resolveSymlinks private
Definition at line 200 of file qfileinfogatherer_p.h.
Referenced by getInfo(), QFileInfoGatherer(), resolveSymlinks(), and setResolveSymlinks().
mutex
QMutex QFileInfoGatherer::mutex private
Definition at line 190 of file qfileinfogatherer_p.h.
Referenced by clear(), fetchExtendedInformation(), removePath(), run(), setIconProvider(), setResolveSymlinks(), and ~QFileInfoGatherer().
path
QStack<QString> QFileInfoGatherer::path private
Definition at line 194 of file qfileinfogatherer_p.h.
Referenced by getFileInfos(), and run().
watcher
QFileSystemWatcher* QFileInfoGatherer::watcher private
Definition at line 198 of file qfileinfogatherer_p.h.
Referenced by clear(), getFileInfos(), getInfo(), QFileInfoGatherer(), and removePath().
The documentation for this class was generated from the following files:
/src/gui/dialogs/qfileinfogatherer_p.h
/src/gui/dialogs/qfileinfogatherer.cpp