Qt 4.8: QPaintEngineState Class Reference
QPaintEngineState Class Reference
The QPaintEngineState class provides information about the active paint engine's current state.
#include <qpaintengine.h>
Public Functions
QBrush backgroundBrush () const
Returns the background brush in the current paint engine state.
Qt::BGMode backgroundMode () const
Returns the background mode in the current paint engine state.
QBrush brush () const
Returns the brush in the current paint engine state.
bool brushNeedsResolving () const
Returns whether the coordinate of the fill have been specified as bounded by the current rendering operation and have to be resolved (about the currently rendered primitive).
QPointF brushOrigin () const
Returns the brush origin in the current paint engine state.
Qt::ClipOperation clipOperation () const
Returns the clip operation in the current paint engine state.
QPainterPath clipPath () const
Returns the clip path in the current paint engine state.
QRegion clipRegion () const
Returns the clip region in the current paint engine state.
QPainter::CompositionMode compositionMode () const
Returns the composition mode in the current paint engine state.
QFont font () const
Returns the font in the current paint engine state.
bool isClipEnabled () const
Returns whether clipping is enabled or not in the current paint engine state.
QMatrix matrix () const
Returns the matrix in the current paint engine state.
qreal opacity () const
Returns the opacity in the current paint engine state.
QPainter * painter () const
Returns a pointer to the painter currently updating the paint engine.
QPen pen () const
Returns the pen in the current paint engine state.
bool penNeedsResolving () const
Returns whether the coordinate of the stroke have been specified as bounded by the current rendering operation and have to be resolved (about the currently rendered primitive).
QPainter::RenderHints renderHints () const
Returns the render hints in the current paint engine state.
QPaintEngine::DirtyFlags state () const
Returns a combination of flags identifying the set of properties that need to be updated when updating the paint engine's state (i.
QTransform transform () const
Returns the matrix in the current paint engine state.
Protected Variables
QPaintEngine::DirtyFlags dirtyFlags
Friends
class QMacPrintEnginePrivate
class QPaintEngine
class QPainter
class QPainterPrivate
class QRasterPaintEngine
class QWidget
Detailed Description
The QPaintEngineState class provides information about the active paint engine's current state.
Since
4.1
Note
This class or function is reentrant.
QPaintEngineState records which properties that have changed since the last time the paint engine was updated, as well as their current value.
Which properties that have changed can at any time be retrieved using the state() function. This function returns an instance of the QPaintEngine::DirtyFlags type which stores an OR combination of QPaintEngine::DirtyFlag values. The QPaintEngine::DirtyFlag enum defines whether a property has changed since the last update or not.
If a property is marked with a dirty flag, its current value can be retrieved using the corresponding get function:
Property Flag Current Property Value
QPaintEngine::DirtyBackground backgroundBrush()
QPaintEngine::DirtyBackgroundMode backgroundMode()
QPaintEngine::DirtyBrush brush()
QPaintEngine::DirtyBrushOrigin brushOrigin()
QPaintEngine::DirtyClipRegion or QPaintEngine::DirtyClipPath clipOperation()
QPaintEngine::DirtyClipPath clipPath()
QPaintEngine::DirtyClipRegion clipRegion()
QPaintEngine::DirtyCompositionMode compositionMode()
QPaintEngine::DirtyFont font()
QPaintEngine::DirtyTransform transform()
QPaintEngine::DirtyClipEnabled isClipEnabled()
QPaintEngine::DirtyPen pen()
QPaintEngine::DirtyHints renderHints()
The QPaintEngineState class also provide the painter() function which returns a pointer to the painter that is currently updating the paint engine.
An instance of this class, representing the current state of the active paint engine, is passed as argument to the QPaintEngine::updateState() function. The only situation in which you will have to use this class directly is when implementing your own paint engine.
See also
QPaintEngine
Definition at line 289 of file qpaintengine.h.
Functions
backgroundBrush()
QBrush QPaintEngineState::backgroundBrush () const
Returns the background brush in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyBackground flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9301 of file qpainter.cpp.
Referenced by QPicturePaintEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->bgBrush;
 }
backgroundMode()
Qt::BGMode QPaintEngineState::backgroundMode () const
Returns the background mode in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyBackgroundMode flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9316 of file qpainter.cpp.
Referenced by QPicturePaintEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->bgMode;
 }
brush()
QBrush QPaintEngineState::brush () const
Returns the brush in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyBrush flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9273 of file qpainter.cpp.
Referenced by QRasterPaintEngine::fill(), QRasterPaintEngine::fillRect(), QGL2PaintEngineExPrivate::fillStencilWithVertexArray(), QRasterPaintEngine::state(), QRasterPaintEngine::updateBrush(), QAlphaPaintEngine::updateState(), QPicturePaintEngine::updateState(), QWin32PrintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), QSvgPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->brush;
 }
brushNeedsResolving()
bool QPaintEngineState::brushNeedsResolving () const
Returns whether the coordinate of the fill have been specified as bounded by the current rendering operation and have to be resolved (about the currently rendered primitive).
Since
4.3
Definition at line 9411 of file qpainter.cpp.
Referenced by QPaintEngine::drawRects().
 {
     const QBrush &brush = static_cast<const QPainterState *>(this)->brush;
     return needsResolving(brush);
 }
brushOrigin()
QPointF QPaintEngineState::brushOrigin () const
Returns the brush origin in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyBrushOrigin flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9287 of file qpainter.cpp.
Referenced by QPainterState::init(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->brushOrigin;
 }
clipOperation()
Qt::ClipOperation QPaintEngineState::clipOperation () const
Returns the clip operation in the current paint engine state.
This variable should only be used when the state() returns a combination which includes either the QPaintEngine::DirtyClipPath or the QPaintEngine::DirtyClipRegion flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9396 of file qpainter.cpp.
Referenced by QPainterState::init(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QWin32PrintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->clipOperation;
 }
clipPath()
QPainterPath QPaintEngineState::clipPath () const
Returns the clip path in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyClipPath flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9457 of file qpainter.cpp.
Referenced by QPainterState::init(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QWin32PrintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->clipPath;
 }
clipRegion()
QRegion QPaintEngineState::clipRegion () const
Returns the clip region in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyClipRegion flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9443 of file qpainter.cpp.
Referenced by QPainterState::init(), QClipData::initialize(), QOpenGLPaintEngineState::QOpenGLPaintEngineState(), QRasterPaintEngine::setClipRectInDeviceCoords(), QClipData::setClipRegion(), QPicturePaintEngine::updateState(), QWin32PrintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->clipRegion;
 }
compositionMode()
QPainter::CompositionMode QPaintEngineState::compositionMode () const
Returns the composition mode in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyCompositionMode flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9503 of file qpainter.cpp.
Referenced by QCoreGraphicsPaintEngine::drawEllipse(), QCoreGraphicsPaintEngine::drawImage(), QCoreGraphicsPaintEngine::drawLines(), QCoreGraphicsPaintEngine::drawPath(), QCoreGraphicsPaintEngine::drawPixmap(), QCoreGraphicsPaintEngine::drawPoints(), QCoreGraphicsPaintEngine::drawPolygon(), QCoreGraphicsPaintEngine::drawRects(), QCoreGraphicsPaintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTiledPixmap(), QRasterBuffer::init(), QDirectFBPaintEngine::setState(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), and QOpenGLPaintEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->composition_mode;
 }
font()
QFont QPaintEngineState::font () const
Returns the font in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyFont flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9331 of file qpainter.cpp.
Referenced by QPainterState::init(), QOpenGLPaintEngine::state(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QSvgPaintEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->font;
 }
isClipEnabled()
bool QPaintEngineState::isClipEnabled () const
Returns whether clipping is enabled or not in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyClipEnabled flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9473 of file qpainter.cpp.
Referenced by QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QWin32PrintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->clipEnabled;
 }
matrix()
QMatrix QPaintEngineState::matrix () const
Returns the matrix in the current paint engine state.
Since
4.2
Note
It is advisable to use transform() instead of this function to preserve the properties of perspective transformations.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyTransform flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9355 of file qpainter.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QRasterPaintEngine::drawTextItem(), QPainterState::init(), QSpanData::setupMatrix(), QPainter::setWorldTransform(), QOpenGLPaintEngine::state(), QRasterPaintEngine::state(), QRasterPaintEngine::updateOutlineMapper(), and QSvgPaintEngine::updateState().
 {
     const QPainterState *st = static_cast<const QPainterState *>(this);
     return st->matrix.toAffine();
 }
opacity()
qreal QPaintEngineState::opacity () const
Returns the opacity in the current paint engine state.
Since
4.2
Definition at line 9529 of file qpainter.cpp.
Referenced by QGradientCache::addCacheElement(), QPainter::drawPixmapFragments(), QGradientCache::generateGradientColorTable(), QPainterState::init(), QGradientCache::maxCacheSize(), QAlphaPaintEngine::updateState(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), QSvgPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->opacity;
 }
painter()
QPainter * QPaintEngineState::painter () const
Returns a pointer to the painter currently updating the paint engine.
Definition at line 9514 of file qpainter.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QPainterState::init(), QPaintEngine::painter(), and QPainterPrivate::updateStateImpl().
 {
     return static_cast<const QPainterState *>(this)->painter;
 }
pen()
QPen QPaintEngineState::pen () const
Returns the pen in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyPen flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9259 of file qpainter.cpp.
Referenced by QPaintEngine::drawLines(), QWin32PrintEngine::drawTextItem(), QPaintEngine::drawTextItem(), QStaticTextPrivate::get(), QPainterState::init(), penNeedsResolving(), QGL2PaintEngineExPrivate::QGL2PaintEngineExPrivate(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), QOpenGLPaintEngine::state(), QRasterPaintEngine::state(), QRasterPaintEngine::updatePen(), QAlphaPaintEngine::updateState(), QPicturePaintEngine::updateState(), QWin32PrintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), QSvgPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->pen;
 }
penNeedsResolving()
bool QPaintEngineState::penNeedsResolving () const
Returns whether the coordinate of the stroke have been specified as bounded by the current rendering operation and have to be resolved (about the currently rendered primitive).
Since
4.3
Definition at line 9428 of file qpainter.cpp.
Referenced by QPaintEngine::drawRects().
 {
     const QPen &pen = static_cast<const QPainterState *>(this)->pen;
     return needsResolving(pen.brush());
 }
renderHints()
QPainter::RenderHints QPaintEngineState::renderHints () const
Returns the render hints in the current paint engine state.
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyHints flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9488 of file qpainter.cpp.
Referenced by QCoreGraphicsPaintEngine::drawPoints(), QCoreGraphicsPaintEngine::drawTextItem(), QPainterState::init(), QPicturePaintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), and QOpenGLPaintEngine::updateState().
 {
     return static_cast<const QPainterState *>(this)->renderHints;
 }
state()
QPaintEngine::DirtyFlags QPaintEngineState::state () const inline
Returns a combination of flags identifying the set of properties that need to be updated when updating the paint engine's state (i.
e. during a call to the QPaintEngine::updateState() function).
\sa QPaintEngine::updateState()
Definition at line 292 of file qpaintengine.h.
Referenced by QRasterPaintEngine::alphaPenBlt(), QRasterPaintEngine::brushChanged(), QRasterPaintEnginePrivate::brushMatrix(), QRasterPaintEngine::brushOriginChanged(), QRasterPaintEnginePrivate::canUseFastImageBlending(), QRasterPaintEngine::clip(), QRasterPaintEngine::clipEnabledChanged(), QRasterPaintEngine::compositionModeChanged(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QRasterPaintEngine::drawCachedGlyphs(), QRasterPaintEngine::drawEllipse(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawLines(), QRasterPaintEngine::drawPixmap(), QRasterPaintEngine::drawPoints(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::drawRects(), QRasterPaintEngine::drawTextItem(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::ensureBrush(), QRasterPaintEngine::ensurePen(), QRasterPaintEngine::ensureState(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), QRasterPaintEngine::fillPolygon(), QRasterPaintEngine::fillRect(), QStaticTextPrivate::get(), QRasterPaintEnginePrivate::getPenFunc(), QRasterPaintEnginePrivate::initializeRasterizer(), QRasterPaintEnginePrivate::isUnclipped(), QRasterPaintEngine::opacityChanged(), QRasterPaintEngine::penChanged(), QRasterPaintEnginePrivate::rasterize(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), QRasterPaintEnginePrivate::recalculateFastImages(), QRasterPaintEngine::renderHintsChanged(), QRasterPaintEngine::setClipRectInDeviceCoords(), QOpenGLPaintEngine::state(), QRasterPaintEngine::stroke(), QGL2PaintEngineExPrivate::stroke(), QRasterPaintEngine::supportsTransformations(), QRasterPaintEngine::transformChanged(), QRasterPaintEngine::updateBrush(), QPainterPrivate::updateEmulationSpecifier(), QRasterPaintEngine::updateOutlineMapper(), QRasterPaintEngine::updatePen(), QAlphaPaintEngine::updateState(), QPicturePaintEngine::updateState(), QWin32PrintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), QSvgPaintEngine::updateState(), QPdfBaseEngine::updateState(), QPainterPrivate::updateState(), and QRasterPaintEngine::updateState().
 { return dirtyFlags; }
transform()
QTransform QPaintEngineState::transform () const
Returns the matrix in the current paint engine state.
Since
4.3
This variable should only be used when the state() returns a combination which includes the QPaintEngine::DirtyTransform flag.
See also
state(), QPaintEngine::updateState()
Definition at line 9377 of file qpainter.cpp.
Referenced by QProxyFontEngine::canRender(), QVGPaintEngine::clipEnabledChanged(), QFontEngineQPF::draw(), QFontEngineQPF1::draw(), QPainter::drawPixmapFragments(), QDirectFBPaintEngine::setState(), QGL2PaintEngineEx::stroke(), QVGPaintEngine::transformChanged(), QAlphaPaintEngine::updateState(), QPicturePaintEngine::updateState(), QWin32PrintEngine::updateState(), QCoreGraphicsPaintEngine::updateState(), QX11PaintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 {
     const QPainterState *st = static_cast<const QPainterState *>(this);
     return st->matrix;
 }
Friends and Related Functions
QMacPrintEnginePrivate
friend class QMacPrintEnginePrivate friend
Definition at line 323 of file qpaintengine.h.
QPaintEngine
friend class QPaintEngine friend
Definition at line 318 of file qpaintengine.h.
QPainter
friend class QPainter friend
Definition at line 321 of file qpaintengine.h.
QPainterPrivate
friend class QPainterPrivate friend
Definition at line 322 of file qpaintengine.h.
QRasterPaintEngine
friend class QRasterPaintEngine friend
Definition at line 319 of file qpaintengine.h.
Referenced by QRasterPaintEngine::type().
QWidget
friend class QWidget friend
Definition at line 320 of file qpaintengine.h.
Properties
dirtyFlags
QPaintEngine::DirtyFlags QPaintEngineState::dirtyFlags protected
Definition at line 325 of file qpaintengine.h.
Referenced by QPainterPrivate::draw_helper(), QPainterState::init(), QMacPrintEnginePrivate::newPage_helper(), QPainterState::QPainterState(), QPainter::restore(), QPainterPrivate::updateMatrix(), QPainterPrivate::updateState(), and QPainterPrivate::updateStateImpl().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine.h
/src/gui/painting/qpainter.cpp