Qt 4.8: QX11PaintEngine Class Reference
QX11PaintEngine Class Reference
#include <qpaintengine_x11_p.h>
Public Functions
bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
void drawImage (const QRectF &r, const QImage &img, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
virtual Qt::HANDLE handle () const
QX11PaintEngine ()
QPainter::RenderHints supportedRenderHints () const
Type type () const
Reimplement this function to return the paint engine Type.
void updateBrush (const QBrush &brush, const QPointF &pt)
void updateClipRegion_dev (const QRegion &region, Qt::ClipOperation op)
void updateFont (const QFont &font)
void updateMatrix (const QTransform &matrix)
void updatePen (const QPen &pen)
void updateRenderHints (QPainter::RenderHints hints)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
~QX11PaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Protected Functions
void drawFreetype (const QPointF &p, const QTextItemInt &si)
void drawXLFD (const QPointF &p, const QTextItemInt &si)
QX11PaintEngine (QX11PaintEnginePrivate &dptr)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Friends
class QFontEngineBox
class QPixmap
Q_GUI_EXPORT GC qt_x11_get_brush_gc (QPainter *)
Returns the X11 specific brush GC for the painter p.
Q_GUI_EXPORT GC qt_x11_get_pen_gc (QPainter *)
Returns the X11 specific pen GC for the painter p.
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 77 of file qpaintengine_x11_p.h.
Constructors and Destructors
QX11PaintEngine() [1/2]
QX11PaintEngine::QX11PaintEngine ()
Definition at line 461 of file qpaintengine_x11.cpp.
     : QPaintEngine(*(new QX11PaintEnginePrivate), qt_decide_features())
 {
     d_func()->init();
 }
~QX11PaintEngine()
QX11PaintEngine::~QX11PaintEngine ()
Definition at line 473 of file qpaintengine_x11.cpp.
 {
 #ifndef QT_NO_XRENDER
     Q_D(QX11PaintEngine);
     delete d->tessellator;
 #endif
 }
QX11PaintEngine() [2/2]
QX11PaintEngine::QX11PaintEngine (QX11PaintEnginePrivate & dptr) protected
Definition at line 467 of file qpaintengine_x11.cpp.
     : QPaintEngine(dptr, qt_decide_features())
 {
     d_func()->init();
 }
Functions
begin()
bool QX11PaintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Definition at line 481 of file qpaintengine_x11.cpp.
 {
     Q_D(QX11PaintEngine);
     d->xinfo = qt_x11Info(pdev);
     QWidget *w = d->pdev->devType() == QInternal::Widget ? static_cast<QWidget *>(d->pdev) : 0;
     const bool isAlienWidget = w && !w->internalWinId() && w->testAttribute(Qt::WA_WState_Created);
 #ifndef QT_NO_XRENDER
     if (w) {
         if (isAlienWidget)
             d->picture = (::Picture)w->nativeParentWidget()->x11PictureHandle();
         else
             d->picture = (::Picture)w->x11PictureHandle();
     } else if (pdev->devType() == QInternal::Pixmap) {
         const QPixmap *pm = static_cast<const QPixmap *>(pdev);
         QX11PixmapData *data = static_cast<QX11PixmapData*>(pm->data.data());
         if (X11->use_xrender && data->depth() != 32 && data->x11_mask)
             data->convertToARGB32();
         d->picture = (::Picture)static_cast<const QPixmap *>(pdev)->x11PictureHandle();
     }
 #else
     d->picture = 0;
 #endif
     d->hd = !isAlienWidget ? qt_x11Handle(pdev) : qt_x11Handle(w->nativeParentWidget());
     Q_ASSERT(d->xinfo != 0);
     d->dpy = d->xinfo->display(); // get display variable
     d->scrn = d->xinfo->screen(); // get screen variable
     d->crgn = QRegion();
     d->gc = XCreateGC(d->dpy, d->hd, 0, 0);
     d->gc_brush = XCreateGC(d->dpy, d->hd, 0, 0);
     d->has_alpha_brush = false;
     d->has_alpha_pen = false;
     d->has_clipping = false;
     d->has_complex_xform = false;
     d->has_scaling_xform = false;
     d->has_non_scaling_xform = true;
     d->xform_scale = 1;
     d->has_custom_pen = false;
     d->matrix = QTransform();
     d->pdev_depth = d->pdev->depth();
     d->render_hints = 0;
     d->txop = QTransform::TxNone;
     d->use_path_fallback = false;
 #if !defined(QT_NO_XRENDER)
     d->composition_mode = PictOpOver;
 #endif
     d->xlibMaxLinePoints = 32762; // a safe number used to avoid, call to XMaxRequestSize(d->dpy) - 3;
     d->opacity = 1;
     // Set up the polygon clipper. Note: This will only work in
     // polyline mode as long as we have a buffer zone, since a
     // polyline may be clipped into several non-connected polylines.
     const int BUFFERZONE = 1000;
     QRect devClipRect(-BUFFERZONE, -BUFFERZONE,
                       pdev->width() + 2*BUFFERZONE, pdev->height() + 2*BUFFERZONE);
     d->polygonClipper.setBoundingRect(devClipRect);
     if (isAlienWidget) {
         // Set system clip for alien widgets painting outside the paint event.
         // This is not a problem with native windows since the windowing system
         // will handle the clip.
         QWidgetPrivate *wd = w->d_func();
         QRegion widgetClip(wd->clipRect());
         wd->clipToEffectiveMask(widgetClip);
         wd->subtractOpaqueSiblings(widgetClip);
         widgetClip.translate(w->mapTo(w->nativeParentWidget(), QPoint()));
         setSystemClip(widgetClip);
     }
     QPixmap::x11SetDefaultScreen(d->xinfo->screen());
     if (w && w->testAttribute(Qt::WA_PaintUnclipped)) {  // paint direct on device
     updatePen(QPen(Qt::black));
     updateBrush(QBrush(Qt::white), QPoint());
         XSetSubwindowMode(d->dpy, d->gc, IncludeInferiors);
         XSetSubwindowMode(d->dpy, d->gc_brush, IncludeInferiors);
 #ifndef QT_NO_XRENDER
         XRenderPictureAttributes attrs;
         attrs.subwindow_mode = IncludeInferiors;
         XRenderChangePicture(d->dpy, d->picture, CPSubwindowMode, &attrs);
 #endif
     }
     setDirty(QPaintEngine::DirtyClipRegion);
     setDirty(QPaintEngine::DirtyPen);
     setDirty(QPaintEngine::DirtyBrush);
     setDirty(QPaintEngine::DirtyBackground);
     return true;
 }
drawEllipse() [1/2]
void QX11PaintEngine::drawEllipse (const QRect & r) virtual
The default implementation of this function calls the floating point version of this function.
Reimplemented from QPaintEngine.
Definition at line 1463 of file qpaintengine_x11.cpp.
Referenced by drawEllipse().
 {
     if (rect.isEmpty()) {
         drawRects(&rect, 1);
         return;
     }
     Q_D(QX11PaintEngine);
     QRect devclip(SHRT_MIN, SHRT_MIN, SHRT_MAX*2 - 1, SHRT_MAX*2 - 1);
     QRect r(rect);
     if (d->txop < QTransform::TxRotate) {
         r = d->matrix.mapRect(rect);
     } else if (d->txop == QTransform::TxRotate && rect.width() == rect.height()) {
         QPainterPath path;
         path.addEllipse(rect);
         r = d->matrix.map(path).boundingRect().toRect();
     }
     if (d->has_alpha_brush || d->has_alpha_pen || d->has_custom_pen || (d->render_hints & QPainter::Antialiasing)
         || d->has_alpha_texture || devclip.intersected(r) != r
         || (d->has_complex_xform
             && !(d->has_non_scaling_xform && rect.width() == rect.height())))
     {
         QPainterPath path;
         path.addEllipse(rect);
         drawPath(path);
         return;
     }
     int x = r.x();
     int y = r.y();
     int w = r.width();
     int h = r.height();
     if (w < 1 || h < 1)
         return;
     if (w == 1 && h == 1) {
         XDrawPoint(d->dpy, d->hd, d->has_pen ? d->gc : d->gc_brush, x, y);
         return;
     }
     d->setupAdaptedOrigin(rect.topLeft());
     if (d->has_brush) {             // draw filled ellipse
         XFillArc(d->dpy, d->hd, d->gc_brush, x, y, w, h, 0, 360*64);
         if (!d->has_pen)            // make smoother outline
             XDrawArc(d->dpy, d->hd, d->gc_brush, x, y, w-1, h-1, 0, 360*64);
     }
     if (d->has_pen)                // draw outline
         XDrawArc(d->dpy, d->hd, d->gc, x, y, w, h, 0, 360*64);
     d->resetAdaptedOrigin();
 }
drawEllipse() [2/2]
void QX11PaintEngine::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented from QPaintEngine.
Definition at line 1454 of file qpaintengine_x11.cpp.
 {
     QRect aligned = rect.toAlignedRect();
     if (aligned == rect)
         drawEllipse(aligned);
     else
         QPaintEngine::drawEllipse(rect);
 }
drawFreetype()
void QX11PaintEngine::drawFreetype (const QPointF & p, const QTextItemInt & si) protected
Definition at line 2362 of file qpaintengine_x11.cpp.
Referenced by drawTextItem().
 {
     Q_D(QX11PaintEngine);
     if (!ti.glyphs.numGlyphs)
         return;
     QFontEngineX11FT *ft = static_cast<QFontEngineX11FT *>(ti.fontEngine);
     if (!d->cpen.isSolid()) {
         QPaintEngine::drawTextItem(p, ti);
         return;
     }
     const bool xrenderPath = (X11->use_xrender
                               && !(d->pdev->devType() == QInternal::Pixmap
                                    && static_cast<const QPixmap *>(d->pdev)->data->pixelType() == QPixmapData::BitmapType));
     QVarLengthArray<QFixedPoint> positions;
     QVarLengthArray<glyph_t> glyphs;
     QTransform matrix;
     if (xrenderPath)
         matrix = d->matrix;
     matrix.translate(p.x(), p.y());
     ft->getGlyphPositions(ti.glyphs, matrix, ti.flags, glyphs, positions);
     if (glyphs.count() == 0)
         return;
 #ifndef QT_NO_XRENDER
     QFontEngineFT::QGlyphSet *set = ft->defaultGlyphs();
     if (d->txop >= QTransform::TxScale && xrenderPath)
         set = ft->loadTransformedGlyphSet(d->matrix);
     if (!set || set->outline_drawing
         || !ft->loadGlyphs(set, glyphs.constData(), glyphs.size(), positions.constData(), QFontEngineFT::Format_Render))
     {
         QPaintEngine::drawTextItem(p, ti);
         return;
     }
     if (xrenderPath) {
         GlyphSet glyphSet = set->id;
         const QColor &pen = d->cpen.color();
         ::Picture src = X11->getSolidFill(d->scrn, pen);
         XRenderPictFormat *maskFormat = 0;
         if (ft->xglyph_format != PictStandardA1)
             maskFormat = XRenderFindStandardFormat(X11->display, ft->xglyph_format);
         enum { t_min = SHRT_MIN, t_max = SHRT_MAX };
         int i = 0;
         for (; i < glyphs.size()
                  && (positions[i].x < t_min || positions[i].x > t_max
                      || positions[i].y < t_min || positions[i].y > t_max);
              ++i)
             ;
         if (i >= glyphs.size())
             return;
         ++i;
         QFixed xp = positions[i - 1].x;
         QFixed yp = positions[i - 1].y;
         QFixed offs = QFixed::fromReal(aliasedCoordinateDelta);
         XGlyphElt32 elt;
         elt.glyphset = glyphSet;
         elt.chars = &glyphs[i - 1];
         elt.nchars = 1;
         elt.xOff = qRound(xp + offs);
         elt.yOff = qRound(yp + offs);
         for (; i < glyphs.size(); ++i) {
             if (positions[i].x < t_min || positions[i].x > t_max
                 || positions[i].y < t_min || positions[i].y > t_max) {
                 break;
             }
             QFontEngineFT::Glyph *g = ft->cachedGlyph(glyphs[i - 1]);
             if (g
                 && positions[i].x == xp + g->advance
                 && positions[i].y == yp
                 && elt.nchars < 253 // don't draw more than 253 characters as some X servers
                                     // hang with it
                 ) {
                 elt.nchars++;
                 xp += g->advance;
             } else {
                 xp = positions[i].x;
                 yp = positions[i].y;
                 XRenderCompositeText32(X11->display, PictOpOver, src, d->picture,
                                        maskFormat, 0, 0, 0, 0,
                                        &elt, 1);
                 elt.chars = &glyphs[i];
                 elt.nchars = 1;
                 elt.xOff = qRound(xp + offs);
                 elt.yOff = qRound(yp + offs);
             }
         }
         XRenderCompositeText32(X11->display, PictOpOver, src, d->picture,
                                maskFormat, 0, 0, 0, 0,
                                &elt, 1);
         return;
     }
 #endif
     QPainterPath path = path_for_glyphs(glyphs, positions, ft);
     if (path.elementCount() <= 1)
         return;
     Q_ASSERT((path.elementCount() % 5) == 0);
     if (d->txop >= QTransform::TxScale) {
         painter()->save();
         painter()->setBrush(d->cpen.brush());
         painter()->setPen(Qt::NoPen);
         painter()->drawPath(path);
         painter()->restore();
         return;
     }
     const int rectcount = 256;
     XRectangle rects[rectcount];
     int num_rects = 0;
     QPoint delta(qRound(d->matrix.dx()), qRound(d->matrix.dy()));
     QRect clip(d->polygonClipper.boundingRect());
     for (int i=0; i < path.elementCount(); i+=5) {
         int x = qRound(path.elementAt(i).x);
         int y = qRound(path.elementAt(i).y);
         int w = qRound(path.elementAt(i+1).x) - x;
         int h = qRound(path.elementAt(i+2).y) - y;
         QRect rect = QRect(x + delta.x(), y + delta.y(), w, h);
         rect = rect.intersected(clip);
         if (rect.isEmpty())
             continue;
         rects[num_rects].x = short(rect.x());
         rects[num_rects].y = short(rect.y());
         rects[num_rects].width = ushort(rect.width());
         rects[num_rects].height = ushort(rect.height());
         ++num_rects;
         if (num_rects == rectcount) {
             XFillRectangles(d->dpy, d->hd, d->gc, rects, num_rects);
             num_rects = 0;
         }
     }
     if (num_rects > 0)
         XFillRectangles(d->dpy, d->hd, d->gc, rects, num_rects);
 }
drawImage()
void QX11PaintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Definition at line 1893 of file qpaintengine_x11.cpp.
 {
     Q_D(QX11PaintEngine);
     if (image.format() == QImage::Format_RGB32
         && d->pdev_depth >= 24 && image.depth() == 32
         && r.size() == sr.size())
     {
         int sx = qRound(sr.x());
         int sy = qRound(sr.y());
         int x = qRound(r.x());
         int y = qRound(r.y());
         int w = qRound(r.width());
         int h = qRound(r.height());
         qt_x11_drawImage(QRect(sx, sy, w, h), QPoint(x, y), image, d->hd, d->gc, d->dpy,
                          (Visual *)d->xinfo->visual(), d->pdev_depth);
     } else {
         QPaintEngine::drawImage(r, image, sr, flags);
     }
 }
drawLines() [1/2]
void QX11PaintEngine::drawLines (const QLine * lines, int lineCount) virtual
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngine.
Definition at line 676 of file qpaintengine_x11.cpp.
 {
     Q_ASSERT(lines);
     Q_ASSERT(lineCount);
     Q_D(QX11PaintEngine);
     if (d->has_alpha_brush
         || d->has_alpha_pen
         || d->has_custom_pen
         || (d->cpen.widthF() > 0 && d->has_complex_xform
             && !d->has_non_scaling_xform)
         || (d->render_hints & QPainter::Antialiasing)) {
         for (int i = 0; i < lineCount; ++i) {
             QPainterPath path(lines[i].p1());
             path.lineTo(lines[i].p2());
             drawPath(path);
         }
         return;
     }
     if (d->has_pen) {
         for (int i = 0; i < lineCount; ++i) {
             QLineF linef;
             if (d->txop == QTransform::TxNone) {
                 linef = lines[i];
             } else {
                 linef = d->matrix.map(QLineF(lines[i]));
             }
             if (clipLine(&linef, d->polygonClipper.boundingRect())) {
                 int x1 = qRound(linef.x1() + aliasedCoordinateDelta);
                 int y1 = qRound(linef.y1() + aliasedCoordinateDelta);
                 int x2 = qRound(linef.x2() + aliasedCoordinateDelta);
                 int y2 = qRound(linef.y2() + aliasedCoordinateDelta);
                 XDrawLine(d->dpy, d->hd, d->gc, x1, y1, x2, y2);
             }
         }
     }
 }
drawLines() [2/2]
void QX11PaintEngine::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 715 of file qpaintengine_x11.cpp.
 {
     Q_ASSERT(lines);
     Q_ASSERT(lineCount);
     Q_D(QX11PaintEngine);
     if (d->has_alpha_brush
         || d->has_alpha_pen
         || d->has_custom_pen
         || (d->cpen.widthF() > 0 && d->has_complex_xform
             && !d->has_non_scaling_xform)
         || (d->render_hints & QPainter::Antialiasing)) {
         for (int i = 0; i < lineCount; ++i) {
             QPainterPath path(lines[i].p1());
             path.lineTo(lines[i].p2());
             drawPath(path);
         }
         return;
     }
     if (d->has_pen) {
         for (int i = 0; i < lineCount; ++i) {
             QLineF linef = d->matrix.map(lines[i]);
             if (clipLine(&linef, d->polygonClipper.boundingRect())) {
                 int x1 = qRound(linef.x1() + aliasedCoordinateDelta);
                 int y1 = qRound(linef.y1() + aliasedCoordinateDelta);
                 int x2 = qRound(linef.x2() + aliasedCoordinateDelta);
                 int y2 = qRound(linef.y2() + aliasedCoordinateDelta);
                 XDrawLine(d->dpy, d->hd, d->gc, x1, y1, x2, y2);
             }
         }
     }
 }
drawPath()
void QX11PaintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngine.
Definition at line 1778 of file qpaintengine_x11.cpp.
Referenced by drawEllipse(), drawLines(), drawPoints(), drawPolygon(), and drawRects().
 {
     Q_D(QX11PaintEngine);
     if (path.isEmpty())
         return;
     if (d->has_brush)
         d->fillPath(path, QX11PaintEnginePrivate::BrushGC, true);
     if (d->has_pen
         && ((X11->use_xrender && (d->has_alpha_pen || (d->render_hints & QPainter::Antialiasing)))
             || (!d->cpen.isCosmetic() && d->txop > QTransform::TxTranslate
                 && !d->has_non_scaling_xform)
             || (d->cpen.style() == Qt::CustomDashLine))) {
         QPainterPathStroker stroker;
         if (d->cpen.style() == Qt::CustomDashLine) {
             stroker.setDashPattern(d->cpen.dashPattern());
             stroker.setDashOffset(d->cpen.dashOffset());
         } else {
             stroker.setDashPattern(d->cpen.style());
         }
         stroker.setCapStyle(d->cpen.capStyle());
         stroker.setJoinStyle(d->cpen.joinStyle());
         QPainterPath stroke;
         qreal width = d->cpen.widthF();
         QPolygonF poly;
         QRectF deviceRect(0, 0, d->pdev->width(), d->pdev->height());
         // necessary to get aliased alphablended primitives to be drawn correctly
         if (d->cpen.isCosmetic() || d->has_scaling_xform) {
             if (d->cpen.isCosmetic())
                 stroker.setWidth(width == 0 ? 1 : width);
             else
                 stroker.setWidth(width * d->xform_scale);
             stroker.d_ptr->stroker.setClipRect(deviceRect);
             stroke = stroker.createStroke(path * d->matrix);
             if (stroke.isEmpty())
                 return;
             stroke.setFillRule(Qt::WindingFill);
             d->fillPath(stroke, QX11PaintEnginePrivate::PenGC, false);
         } else {
             stroker.setWidth(width);
             stroker.d_ptr->stroker.setClipRect(d->matrix.inverted().mapRect(deviceRect));
             stroke = stroker.createStroke(path);
             if (stroke.isEmpty())
                 return;
             stroke.setFillRule(Qt::WindingFill);
             d->fillPath(stroke, QX11PaintEnginePrivate::PenGC, true);
         }
     } else if (d->has_pen) {
         // if we have a cosmetic pen - use XDrawLine() for speed
         QList<QPolygonF> polys = path.toSubpathPolygons(d->matrix);
         for (int i = 0; i < polys.size(); ++i)
             d->strokePolygon_dev(polys.at(i).data(), polys.at(i).size(), false);
     }
 }
drawPixmap()
void QX11PaintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Definition at line 1915 of file qpaintengine_x11.cpp.
 {
     Q_D(QX11PaintEngine);
     QRectF sr = _sr;
     int x = qRound(r.x());
     int y = qRound(r.y());
     int sx = qRound(sr.x());
     int sy = qRound(sr.y());
     int sw = qRound(sr.width());
     int sh = qRound(sr.height());
     QPixmap pixmap = qt_toX11Pixmap(px);
     if(pixmap.isNull())
         return;
     if ((d->xinfo && d->xinfo->screen() != pixmap.x11Info().screen())
         || (pixmap.x11Info().screen() != DefaultScreen(X11->display))) {
         QPixmap* p = const_cast<QPixmap *>(&pixmap);
         p->x11SetScreen(d->xinfo ? d->xinfo->screen() : DefaultScreen(X11->display));
     }
     QPixmap::x11SetDefaultScreen(pixmap.x11Info().screen());
 #ifndef QT_NO_XRENDER
     ::Picture src_pict = static_cast<QX11PixmapData*>(pixmap.data.data())->picture;
     if (src_pict && d->picture) {
         const int pDepth = pixmap.depth();
         if (pDepth == 1 && (d->has_alpha_pen)) {
             qt_render_bitmap(d->dpy, d->scrn, src_pict, d->picture,
                              sx, sy, x, y, sw, sh, d->cpen);
             return;
         } else if (pDepth != 1 && (pDepth == 32 || pDepth != d->pdev_depth)) {
             XRenderComposite(d->dpy, d->composition_mode,
                              src_pict, 0, d->picture, sx, sy, 0, 0, x, y, sw, sh);
             return;
         }
     }
 #endif
     bool mono_src = pixmap.depth() == 1;
     bool mono_dst = d->pdev_depth == 1;
     bool restore_clip = false;
     if (static_cast<QX11PixmapData*>(pixmap.data.data())->x11_mask) { // pixmap has a mask
         QBitmap comb(sw, sh);
         GC cgc = XCreateGC(d->dpy, comb.handle(), 0, 0);
         XSetForeground(d->dpy, cgc, 0);
         XFillRectangle(d->dpy, comb.handle(), cgc, 0, 0, sw, sh);
         XSetBackground(d->dpy, cgc, 0);
         XSetForeground(d->dpy, cgc, 1);
         if (!d->crgn.isEmpty()) {
             int num;
             XRectangle *rects = (XRectangle *)qt_getClipRects(d->crgn, num);
             XSetClipRectangles(d->dpy, cgc, -x, -y, rects, num, Unsorted);
         } else if (d->has_clipping) {
             XSetClipRectangles(d->dpy, cgc, 0, 0, 0, 0, Unsorted);
         }
         XSetFillStyle(d->dpy, cgc, FillOpaqueStippled);
         XSetTSOrigin(d->dpy, cgc, -sx, -sy);
         XSetStipple(d->dpy, cgc,
                     static_cast<QX11PixmapData*>(pixmap.data.data())->x11_mask);
         XFillRectangle(d->dpy, comb.handle(), cgc, 0, 0, sw, sh);
         XFreeGC(d->dpy, cgc);
         XSetClipOrigin(d->dpy, d->gc, x, y);
         XSetClipMask(d->dpy, d->gc, comb.handle());
         restore_clip = true;
     }
     if (mono_src) {
         if (!d->crgn.isEmpty()) {
             Pixmap comb = XCreatePixmap(d->dpy, d->hd, sw, sh, 1);
             GC cgc = XCreateGC(d->dpy, comb, 0, 0);
             XSetForeground(d->dpy, cgc, 0);
             XFillRectangle(d->dpy, comb, cgc, 0, 0, sw, sh);
             int num;
             XRectangle *rects = (XRectangle *)qt_getClipRects(d->crgn, num);
             XSetClipRectangles(d->dpy, cgc, -x, -y, rects, num, Unsorted);
             XCopyArea(d->dpy, pixmap.handle(), comb, cgc, sx, sy, sw, sh, 0, 0);
             XFreeGC(d->dpy, cgc);
             XSetClipMask(d->dpy, d->gc, comb);
             XSetClipOrigin(d->dpy, d->gc, x, y);
             XFreePixmap(d->dpy, comb);
         } else {
             XSetClipMask(d->dpy, d->gc, pixmap.handle());
             XSetClipOrigin(d->dpy, d->gc, x - sx, y - sy);
         }
         if (mono_dst) {
             XSetForeground(d->dpy, d->gc, qGray(d->cpen.color().rgb()) > 127 ? 0 : 1);
         } else {
             QColormap cmap = QColormap::instance(d->scrn);
             XSetForeground(d->dpy, d->gc, cmap.pixel(d->cpen.color()));
         }
         XFillRectangle(d->dpy, d->hd, d->gc, x, y, sw, sh);
         restore_clip = true;
     } else if (mono_dst && !mono_src) {
         QBitmap bitmap(pixmap);
         XCopyArea(d->dpy, bitmap.handle(), d->hd, d->gc, sx, sy, sw, sh, x, y);
     } else {
         XCopyArea(d->dpy, pixmap.handle(), d->hd, d->gc, sx, sy, sw, sh, x, y);
     }
     if (d->pdev->devType() == QInternal::Pixmap) {
         const QPixmap *px = static_cast<const QPixmap*>(d->pdev);
         Pixmap src_mask = static_cast<QX11PixmapData*>(pixmap.data.data())->x11_mask;
         Pixmap dst_mask = static_cast<QX11PixmapData*>(px->data.data())->x11_mask;
         if (dst_mask) {
             GC cgc = XCreateGC(d->dpy, dst_mask, 0, 0);
             if (src_mask) { // copy src mask into dst mask
                 XCopyArea(d->dpy, src_mask, dst_mask, cgc, sx, sy, sw, sh, x, y);
             } else { // no src mask, but make sure the area copied is opaque in dest
                 XSetBackground(d->dpy, cgc, 0);
                 XSetForeground(d->dpy, cgc, 1);
                 XFillRectangle(d->dpy, dst_mask, cgc, x, y, sw, sh);
             }
             XFreeGC(d->dpy, cgc);
         }
     }
     if (restore_clip) {
         XSetClipOrigin(d->dpy, d->gc, 0, 0);
         int num;
         XRectangle *rects = (XRectangle *)qt_getClipRects(d->crgn, num);
         if (num == 0)
             XSetClipMask(d->dpy, d->gc, XNone);
         else
             XSetClipRectangles(d->dpy, d->gc, 0, 0, rects, num, Unsorted);
     }
 }
drawPoints() [1/2]
void QX11PaintEngine::drawPoints (const QPoint * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
The default implementation converts the first pointCount QPoints in points to QPointFs and calls the floating point version of drawPoints.
Reimplemented from QPaintEngine.
Definition at line 952 of file qpaintengine_x11.cpp.
 {
     Q_ASSERT(points);
     Q_ASSERT(pointCount);
     Q_D(QX11PaintEngine);
     if (!d->has_pen)
         return;
     // use the same test here as in drawPath to ensure that we don't use the path fallback
     // and end up in XDrawLines for pens with width <= 1
     if (d->cpen.widthF() > 1.0f
         || (X11->use_xrender && (d->has_alpha_pen || (d->render_hints & QPainter::Antialiasing)))
         || (!d->cpen.isCosmetic() && d->txop > QTransform::TxTranslate))
     {
         Qt::PenCapStyle capStyle = d->cpen.capStyle();
         if (capStyle == Qt::FlatCap) {
             setCapStyle(CapProjecting, d->gc);
             d->cpen.setCapStyle(Qt::SquareCap);
         }
         const QPoint *end = points + pointCount;
         while (points < end) {
             QPainterPath path;
             path.moveTo(*points);
             path.lineTo(points->x()+.005, points->y());
             drawPath(path);
             ++points;
         }
         if (capStyle == Qt::FlatCap) {
             setCapStyle(CapButt, d->gc);
             d->cpen.setCapStyle(capStyle);
         }
         return;
     }
     static const int BUF_SIZE = 1024;
     XPoint xPoints[BUF_SIZE];
     int i = 0, j = 0;
     while (i < pointCount) {
         while (i < pointCount && j < BUF_SIZE) {
             const QPoint &xformed = d->matrix.map(points[i]);
             int x = xformed.x();
             int y = xformed.y();
             if (x >= SHRT_MIN && y >= SHRT_MIN && x < SHRT_MAX && y < SHRT_MAX) {
                 xPoints[j].x = x;
                 xPoints[j].y = y;
                 ++j;
             }
             ++i;
         }
         if (j)
             XDrawPoints(d->dpy, d->hd, d->gc, xPoints, j, CoordModeOrigin);
         j = 0;
     }
 }
drawPoints() [2/2]
void QX11PaintEngine::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented from QPaintEngine.
Definition at line 1010 of file qpaintengine_x11.cpp.
 {
     Q_ASSERT(points);
     Q_ASSERT(pointCount);
     Q_D(QX11PaintEngine);
     if (!d->has_pen)
         return;
     // use the same test here as in drawPath to ensure that we don't use the path fallback
     // and end up in XDrawLines for pens with width <= 1
     if (d->cpen.widthF() > 1.0f
         || (X11->use_xrender && (d->has_alpha_pen || (d->render_hints & QPainter::Antialiasing)))
         || (!d->cpen.isCosmetic() && d->txop > QTransform::TxTranslate))
     {
         Qt::PenCapStyle capStyle = d->cpen.capStyle();
         if (capStyle == Qt::FlatCap) {
             setCapStyle(CapProjecting, d->gc);
             d->cpen.setCapStyle(Qt::SquareCap);
         }
         const QPointF *end = points + pointCount;
         while (points < end) {
             QPainterPath path;
             path.moveTo(*points);
             path.lineTo(points->x() + 0.005, points->y());
             drawPath(path);
             ++points;
         }
         if (capStyle == Qt::FlatCap) {
             setCapStyle(CapButt, d->gc);
             d->cpen.setCapStyle(capStyle);
         }
         return;
     }
     static const int BUF_SIZE = 1024;
     XPoint xPoints[BUF_SIZE];
     int i = 0, j = 0;
     while (i < pointCount) {
         while (i < pointCount && j < BUF_SIZE) {
             const QPointF &xformed = d->matrix.map(points[i]);
             int x = qFloor(xformed.x());
             int y = qFloor(xformed.y());
             if (x >= SHRT_MIN && y >= SHRT_MIN && x < SHRT_MAX && y < SHRT_MAX) {
                 xPoints[j].x = x;
                 xPoints[j].y = y;
                 ++j;
             }
             ++i;
         }
         if (j)
             XDrawPoints(d->dpy, d->hd, d->gc, xPoints, j, CoordModeOrigin);
         j = 0;
     }
 }
drawPolygon() [1/2]
void QX11PaintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Definition at line 1720 of file qpaintengine_x11.cpp.
 {
     Q_D(QX11PaintEngine);
     if (d->use_path_fallback) {
         QPainterPath path(polygonPoints[0]);
         for (int i = 1; i < pointCount; ++i)
             path.lineTo(polygonPoints[i]);
         if (mode == PolylineMode) {
             QBrush oldBrush = d->cbrush;
             d->cbrush = QBrush(Qt::NoBrush);
             path.setFillRule(Qt::WindingFill);
             drawPath(path);
             d->cbrush = oldBrush;
         } else {
             path.setFillRule(mode == OddEvenMode ? Qt::OddEvenFill : Qt::WindingFill);
             path.closeSubpath();
             drawPath(path);
         }
         return;
     }
     if (mode != PolylineMode && d->has_brush)
         d->fillPolygon_translated(polygonPoints, pointCount, QX11PaintEnginePrivate::BrushGC, mode);
     if (d->has_pen)
         d->strokePolygon_translated(polygonPoints, pointCount, mode != PolylineMode);
 }
drawPolygon() [2/2]
void QX11PaintEngine::drawPolygon (const QPoint * points, int pointCount, PolygonDrawMode mode) inline virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Definition at line 109 of file qpaintengine_x11_p.h.
         { QPaintEngine::drawPolygon(points, pointCount, mode); }
drawRects() [1/2]
void QX11PaintEngine::drawRects (const QRect * rects, int rectCount) virtual
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngine.
Definition at line 825 of file qpaintengine_x11.cpp.
Referenced by drawEllipse().
 {
     Q_D(QX11PaintEngine);
     Q_ASSERT(rects);
     Q_ASSERT(rectCount);
     if (d->has_alpha_pen
         || d->has_complex_xform
         || d->has_custom_pen
         || (d->render_hints & QPainter::Antialiasing))
     {
         for (int i = 0; i < rectCount; ++i) {
             QPainterPath path;
             path.addRect(rects[i]);
             drawPath(path);
         }
         return;
     }
     QRect clip(d->polygonClipper.boundingRect());
     QPoint offset(qRound(d->matrix.dx()), qRound(d->matrix.dy()));
 #if !defined(QT_NO_XRENDER)
     ::Picture pict = d->picture;
     if (X11->use_xrender && pict && d->has_brush && d->pdev_depth != 1
         && (d->has_texture || d->has_alpha_brush || complexPictOp(d->composition_mode)))
     {
         XRenderColor xc;
         if (!d->has_texture && !d->has_pattern)
             xc = X11->preMultiply(d->cbrush.color());
         for (int i = 0; i < rectCount; ++i) {
             QRect r(rects[i]);
             if (d->txop == QTransform::TxTranslate)
                 r.translate(offset);
             if (r.width() == 0 || r.height() == 0) {
                 if (d->has_pen) {
                     const QLine l = clipStraightLine(clip, QLine(r.left(), r.top(), r.left() + r.width(), r.top() + r.height()));
                     XDrawLine(d->dpy, d->hd, d->gc, l.p1().x(), l.p1().y(), l.p2().x(), l.p2().y());
                 }
                 continue;
             }
             r = r.intersected(clip);
             if (r.isEmpty())
                 continue;
             if (d->has_texture || d->has_pattern) {
                 XRenderComposite(d->dpy, d->composition_mode, d->current_brush, 0, pict,
                                  qRound(r.x() - d->bg_origin.x()), qRound(r.y() - d->bg_origin.y()),
                                  0, 0, r.x(), r.y(), r.width(), r.height());
             } else {
                 XRenderFillRectangle(d->dpy, d->composition_mode, pict, &xc, r.x(), r.y(), r.width(), r.height());
             }
             if (d->has_pen)
                 XDrawRectangle(d->dpy, d->hd, d->gc, r.x(), r.y(), r.width(), r.height());
         }
     } else
 #endif // !QT_NO_XRENDER
     {
         if (d->has_brush && d->has_pen) {
             for (int i = 0; i < rectCount; ++i) {
                 QRect r(rects[i]);
                 if (d->txop == QTransform::TxTranslate)
                     r.translate(offset);
                 if (r.width() == 0 || r.height() == 0) {
                     const QLine l = clipStraightLine(clip, QLine(r.left(), r.top(), r.left() + r.width(), r.top() + r.height()));
                     XDrawLine(d->dpy, d->hd, d->gc, l.p1().x(), l.p1().y(), l.p2().x(), l.p2().y());
                     continue;
                 }
                 r = r.intersected(clip);
                 if (r.isEmpty())
                     continue;
                 d->setupAdaptedOrigin(r.topLeft());
                 XFillRectangle(d->dpy, d->hd, d->gc_brush, r.x(), r.y(), r.width(), r.height());
                 XDrawRectangle(d->dpy, d->hd, d->gc, r.x(), r.y(), r.width(), r.height());
             }
             d->resetAdaptedOrigin();
         } else {
             QVarLengthArray<XRectangle> xrects(rectCount);
             int numClipped = rectCount;
             for (int i = 0; i < rectCount; ++i) {
                 QRect r(rects[i]);
                 if (d->txop == QTransform::TxTranslate)
                     r.translate(offset);
                 if (r.width() == 0 || r.height() == 0) {
                     --numClipped;
                     if (d->has_pen) {
                         const QLine l = clipStraightLine(clip, QLine(r.left(), r.top(), r.left() + r.width(), r.top() + r.height()));
                         XDrawLine(d->dpy, d->hd, d->gc, l.p1().x(), l.p1().y(), l.p2().x(), l.p2().y());
                     }
                     continue;
                 }
                 r = r.intersected(clip);
                 if (r.isEmpty()) {
                     --numClipped;
                     continue;
                 }
                 xrects[i].x = short(r.x());
                 xrects[i].y = short(r.y());
                 xrects[i].width = ushort(r.width());
                 xrects[i].height = ushort(r.height());
             }
             if (numClipped) {
                 d->setupAdaptedOrigin(rects[0].topLeft());
                 if (d->has_brush)
                     XFillRectangles(d->dpy, d->hd, d->gc_brush, xrects.data(), numClipped);
                 else if (d->has_pen)
                     XDrawRectangles(d->dpy, d->hd, d->gc, xrects.data(), numClipped);
                 d->resetAdaptedOrigin();
             }
         }
     }
 }
drawRects() [2/2]
void QX11PaintEngine::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 768 of file qpaintengine_x11.cpp.
 {
     Q_D(QX11PaintEngine);
     Q_ASSERT(rects);
     Q_ASSERT(rectCount);
     if (rectCount != 1
         || d->has_pen
         || d->has_alpha_brush
         || d->has_complex_xform
         || d->has_custom_pen
         || d->cbrush.style() != Qt::SolidPattern
 #if !defined(QT_NO_XRENDER)
         || complexPictOp(d->composition_mode)
 #endif
        )
     {
         QPaintEngine::drawRects(rects, rectCount);
         return;
     }
     QPoint alignedOffset;
     if (d->txop == QTransform::TxTranslate) {
         QPointF offset(d->matrix.dx(), d->matrix.dy());
         alignedOffset = offset.toPoint();
         if (offset != QPointF(alignedOffset)) {
             QPaintEngine::drawRects(rects, rectCount);
             return;
         }
     }
     const QRectF& r = rects[0];
     QRect alignedRect = r.toAlignedRect();
     if (r != QRectF(alignedRect)) {
         QPaintEngine::drawRects(rects, rectCount);
         return;
     }
     alignedRect.translate(alignedOffset);
     QRect clip(d->polygonClipper.boundingRect());
     alignedRect = alignedRect.intersected(clip);
     if (alignedRect.isEmpty())
         return;
     // simple-case:
     //   the rectangle is pixel-aligned
     //   the fill brush is just a solid non-alpha color
     //   the painter transform is only integer translation
     // ignore: antialiasing and just XFillRectangles directly
     XRectangle xrect;
     xrect.x = short(alignedRect.x());
     xrect.y = short(alignedRect.y());
     xrect.width = ushort(alignedRect.width());
     xrect.height = ushort(alignedRect.height());
     XFillRectangles(d->dpy, d->hd, d->gc_brush, &xrect, 1);
 }
drawTextItem()
void QX11PaintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Definition at line 2253 of file qpaintengine_x11.cpp.
 {
     const QTextItemInt &ti = static_cast<const QTextItemInt &>(textItem);
     switch(ti.fontEngine->type()) {
     case QFontEngine::TestFontEngine:
     case QFontEngine::Box:
         d_func()->drawBoxTextItem(p, ti);
         break;
     case QFontEngine::XLFD:
         drawXLFD(p, ti);
         break;
 #ifndef QT_NO_FONTCONFIG
     case QFontEngine::Freetype:
         drawFreetype(p, ti);
         break;
 #endif
     default:
         Q_ASSERT(false);
     }
 }
drawTiledPixmap()
void QX11PaintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngine.
Definition at line 2119 of file qpaintengine_x11.cpp.
 {
     int x = qRound(r.x());
     int y = qRound(r.y());
     int w = qRound(r.width());
     int h = qRound(r.height());
     int sx = qRound(p.x());
     int sy = qRound(p.y());
     bool mono_src = pixmap.depth() == 1;
     Q_D(QX11PaintEngine);
     if ((d->xinfo && d->xinfo->screen() != pixmap.x11Info().screen())
         || (pixmap.x11Info().screen() != DefaultScreen(X11->display))) {
         QPixmap* p = const_cast<QPixmap *>(&pixmap);
         p->x11SetScreen(d->xinfo ? d->xinfo->screen() : DefaultScreen(X11->display));
     }
     QPixmap::x11SetDefaultScreen(pixmap.x11Info().screen());
 #ifndef QT_NO_XRENDER
     if (X11->use_xrender && d->picture && pixmap.x11PictureHandle()) {
 #if 0
         // ### Qt 5: enable this
         XRenderPictureAttributes attrs;
         attrs.repeat = true;
         XRenderChangePicture(d->dpy, pixmap.x11PictureHandle(), CPRepeat, &attrs);
         if (mono_src) {
             qt_render_bitmap(d->dpy, d->scrn, pixmap.x11PictureHandle(), d->picture,
                              sx, sy, x, y, w, h, d->cpen);
         } else {
             XRenderComposite(d->dpy, d->composition_mode,
                              pixmap.x11PictureHandle(), XNone, d->picture,
                              sx, sy, 0, 0, x, y, w, h);
         }
 #else
         const int numTiles = (w / pixmap.width()) * (h / pixmap.height());
         if (numTiles < 100) {
             // this is essentially qt_draw_tile(), inlined for
             // the XRenderComposite call
             int yPos, xPos, drawH, drawW, yOff, xOff;
             yPos = y;
             yOff = sy;
             while(yPos < y + h) {
                 drawH = pixmap.height() - yOff;    // Cropping first row
                 if (yPos + drawH > y + h)        // Cropping last row
                     drawH = y + h - yPos;
                 xPos = x;
                 xOff = sx;
                 while(xPos < x + w) {
                     drawW = pixmap.width() - xOff; // Cropping first column
                     if (xPos + drawW > x + w)    // Cropping last column
                         drawW = x + w - xPos;
                     if (mono_src) {
                         qt_render_bitmap(d->dpy, d->scrn, pixmap.x11PictureHandle(), d->picture,
                                          xOff, yOff, xPos, yPos, drawW, drawH, d->cpen);
                     } else {
                         XRenderComposite(d->dpy, d->composition_mode,
                                          pixmap.x11PictureHandle(), XNone, d->picture,
                                          xOff, yOff, 0, 0, xPos, yPos, drawW, drawH);
                     }
                     xPos += drawW;
                     xOff = 0;
                 }
                 yPos += drawH;
                 yOff = 0;
             }
         } else {
             w = qMin(w, d->pdev->width() - x);
             h = qMin(h, d->pdev->height() - y);
             if (w <= 0 || h <= 0)
                 return;
             const int pw = w + sx;
             const int ph = h + sy;
             QPixmap pm(pw, ph);
             if (pixmap.hasAlpha() || mono_src)
                 pm.fill(Qt::transparent);
             const int mode = pixmap.hasAlpha() ? PictOpOver : PictOpSrc;
             const ::Picture pmPicture = pm.x11PictureHandle();
             // first tile
             XRenderComposite(d->dpy, mode,
                              pixmap.x11PictureHandle(), XNone, pmPicture,
                              0, 0, 0, 0, 0, 0, qMin(pw, pixmap.width()), qMin(ph, pixmap.height()));
             // first row of tiles
             int xPos = pixmap.width();
             const int sh = qMin(ph, pixmap.height());
             while (xPos < pw) {
                 const int sw = qMin(xPos, pw - xPos);
                 XRenderComposite(d->dpy, mode,
                                  pmPicture, XNone, pmPicture,
                                  0, 0, 0, 0, xPos, 0, sw, sh);
                 xPos *= 2;
             }
             // remaining rows
             int yPos = pixmap.height();
             const int sw = pw;
             while (yPos < ph) {
                 const int sh = qMin(yPos, ph - yPos);
                 XRenderComposite(d->dpy, mode,
                                  pmPicture, XNone, pmPicture,
                                  0, 0, 0, 0, 0, yPos, sw, sh);
                 yPos *= 2;
             }
             // composite
             if (mono_src)
                 qt_render_bitmap(d->dpy, d->scrn, pmPicture, d->picture,
                                  sx, sy, x, y, w, h, d->cpen);
             else
                 XRenderComposite(d->dpy, d->composition_mode,
                                  pmPicture, XNone, d->picture,
                                  sx, sy, 0, 0, x, y, w, h);
         }
 #endif
     } else
 #endif // !QT_NO_XRENDER
         if (pixmap.depth() > 1 && !static_cast<QX11PixmapData*>(pixmap.data.data())->x11_mask) {
             XSetTile(d->dpy, d->gc, pixmap.handle());
             XSetFillStyle(d->dpy, d->gc, FillTiled);
             XSetTSOrigin(d->dpy, d->gc, x-sx, y-sy);
             XFillRectangle(d->dpy, d->hd, d->gc, x, y, w, h);
             XSetTSOrigin(d->dpy, d->gc, 0, 0);
             XSetFillStyle(d->dpy, d->gc, FillSolid);
         } else {
             qt_draw_tile(this, x, y, w, h, pixmap, sx, sy);
         }
 }
drawXLFD()
void QX11PaintEngine::drawXLFD (const QPointF & p, const QTextItemInt & si) protected
Definition at line 2275 of file qpaintengine_x11.cpp.
Referenced by drawTextItem().
 {
     Q_D(QX11PaintEngine);
     if (d->txop > QTransform::TxTranslate) {
         // XServer or font don't support server side transformations, need to do it by hand
         QPaintEngine::drawTextItem(p, ti);
         return;
     }
     if (!ti.glyphs.numGlyphs)
         return;
     QVarLengthArray<QFixedPoint> positions;
     QVarLengthArray<glyph_t> glyphs;
     QTransform matrix = d->matrix;
     matrix.translate(p.x(), p.y());
     ti.fontEngine->getGlyphPositions(ti.glyphs, matrix, ti.flags, glyphs, positions);
     if (glyphs.size() == 0)
         return;
     QFontEngineXLFD *xlfd = static_cast<QFontEngineXLFD *>(ti.fontEngine);
     Qt::HANDLE font_id = xlfd->fontStruct()->fid;
     XSetFont(d->dpy, d->gc, font_id);
     const QFixed offs = QFixed::fromReal(aliasedCoordinateDelta);
     for (int i = 0; i < glyphs.size(); i++) {
         int xp = qRound(positions[i].x + offs);
         int yp = qRound(positions[i].y + offs);
         if (xp < SHRT_MAX && xp > SHRT_MIN &&  yp > SHRT_MIN && yp < SHRT_MAX) {
             XChar2b ch;
             ch.byte1 = glyphs[i] >> 8;
             ch.byte2 = glyphs[i] & 0xff;
             XDrawString16(d->dpy, d->hd, d->gc, xp, yp, &ch, 1);
         }
     }
 }
end()
bool QX11PaintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Definition at line 573 of file qpaintengine_x11.cpp.
Referenced by drawPoints(), and qt_x11_drawImage().
 {
     Q_D(QX11PaintEngine);
 #if !defined(QT_NO_XRENDER)
     if (d->picture) {
         // reset clipping/subwindow mode on our render picture
     XRenderPictureAttributes attrs;
     attrs.subwindow_mode = ClipByChildren;
         attrs.clip_mask = XNone;
     XRenderChangePicture(d->dpy, d->picture, CPClipMask|CPSubwindowMode, &attrs);
     }
 #endif
     if (d->gc_brush && d->pdev->painters < 2) {
         XFreeGC(d->dpy, d->gc_brush);
         d->gc_brush = 0;
     }
     if (d->gc && d->pdev->painters < 2) {
         XFreeGC(d->dpy, d->gc);
         d->gc = 0;
     }
     // Restore system clip for alien widgets painting outside the paint event.
     if (d->pdev->devType() == QInternal::Widget && !static_cast<QWidget *>(d->pdev)->internalWinId())
         setSystemClip(QRegion());
     return true;
 }
handle()
Qt::HANDLE QX11PaintEngine::handle () const virtual
Definition at line 2108 of file qpaintengine_x11.cpp.
Referenced by qt_mac_qd_context().
 {
     Q_D(const QX11PaintEngine);
     Q_ASSERT(isActive());
     Q_ASSERT(d->hd);
     return d->hd;
 }
supportedRenderHints()
QPainter::RenderHints QX11PaintEngine::supportedRenderHints () const
Definition at line 1069 of file qpaintengine_x11.cpp.
 {
 #if !defined(QT_NO_XRENDER)
     if (X11->use_xrender)
         return QPainter::Antialiasing;
 #endif
     return QFlag(0);
 }
type()
Type QX11PaintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 120 of file qpaintengine_x11_p.h.
 { return QPaintEngine::X11; }
updateBrush()
void QX11PaintEngine::updateBrush (const QBrush & brush, const QPointF & pt)
Definition at line 1323 of file qpaintengine_x11.cpp.
Referenced by begin(), and updateState().
 {
     Q_D(QX11PaintEngine);
     d->cbrush = brush;
     d->bg_origin = origin;
     d->adapted_brush_origin = false;
 #if !defined(QT_NO_XRENDER)
     d->current_brush = 0;
 #endif
     if (d->opacity < 1.0) {
         QColor c = d->cbrush.color();
         c.setAlpha(qRound(c.alpha()*d->opacity));
         d->cbrush.setColor(c);
     }
     int s  = FillSolid;
     int  bs = d->cbrush.style();
     d->has_brush = (bs != Qt::NoBrush);
     d->has_pattern = bs >= Qt::Dense1Pattern && bs <= Qt::DiagCrossPattern;
     d->has_texture = bs == Qt::TexturePattern;
     d->has_alpha_brush = brush.color().alpha() != 255;
     d->has_alpha_texture = d->has_texture && d->cbrush.texture().hasAlphaChannel();
     ulong mask = GCForeground | GCBackground | GCGraphicsExposures
                  | GCLineStyle | GCCapStyle | GCJoinStyle | GCFillStyle;
     XGCValues vals;
     vals.graphics_exposures = false;
     if (d->pdev_depth == 1) {
         vals.foreground = qGray(d->cbrush.color().rgb()) > 127 ? 0 : 1;
         vals.background = qGray(QColor(Qt::transparent).rgb()) > 127 ? 0 : 1;
     } else if (X11->use_xrender && d->pdev->devType() == QInternal::Pixmap
                && d->pdev_depth == 32) {
         vals.foreground = d->cbrush.color().rgba();
         vals.background = QColor(Qt::transparent).rgba();
     } else {
         QColormap cmap = QColormap::instance(d->scrn);
         vals.foreground = cmap.pixel(d->cbrush.color());
         vals.background = cmap.pixel(QColor(Qt::transparent));
         if (!X11->use_xrender && d->has_brush && !d->has_pattern && !brush.isOpaque()) {
             QPixmap pattern = qt_patternForAlpha(brush.color().alpha(), d->scrn);
             mask |= GCStipple;
             vals.stipple = pattern.handle();
             s = FillStippled;
             d->adapted_brush_origin = true;
         }
     }
     vals.cap_style = CapButt;
     vals.join_style = JoinMiter;
     vals.line_style = LineSolid;
     if (d->has_pattern || d->has_texture) {
         if (bs == Qt::TexturePattern) {
             d->brush_pm = qt_toX11Pixmap(d->cbrush.texture());
 #if !defined(QT_NO_XRENDER)
             if (X11->use_xrender) {
                 XRenderPictureAttributes attrs;
                 attrs.repeat = true;
                 XRenderChangePicture(d->dpy, d->brush_pm.x11PictureHandle(), CPRepeat, &attrs);
                 QX11PixmapData *data = static_cast<QX11PixmapData*>(d->brush_pm.data.data());
                 if (data->mask_picture)
                     XRenderChangePicture(d->dpy, data->mask_picture, CPRepeat, &attrs);
             }
 #endif
         } else {
             d->brush_pm = qt_toX11Pixmap(qt_pixmapForBrush(bs, true));
         }
         d->brush_pm.x11SetScreen(d->scrn);
         if (d->brush_pm.depth() == 1) {
             mask |= GCStipple;
             vals.stipple = d->brush_pm.handle();
             s = FillStippled;
 #if !defined(QT_NO_XRENDER)
             if (X11->use_xrender) {
                 d->bitmap_texture = QPixmap(d->brush_pm.size());
                 d->bitmap_texture.fill(Qt::transparent);
                 d->bitmap_texture = qt_toX11Pixmap(d->bitmap_texture);
                 d->bitmap_texture.x11SetScreen(d->scrn);
                 ::Picture src  = X11->getSolidFill(d->scrn, d->cbrush.color());
                 XRenderComposite(d->dpy, PictOpSrc, src, d->brush_pm.x11PictureHandle(),
                                  d->bitmap_texture.x11PictureHandle(),
                                  0, 0, d->brush_pm.width(), d->brush_pm.height(),
                                  0, 0, d->brush_pm.width(), d->brush_pm.height());
                 XRenderPictureAttributes attrs;
                 attrs.repeat = true;
                 XRenderChangePicture(d->dpy, d->bitmap_texture.x11PictureHandle(), CPRepeat, &attrs);
                 d->current_brush = d->bitmap_texture.x11PictureHandle();
             }
 #endif
         } else {
             mask |= GCTile;
 #ifndef QT_NO_XRENDER
             if (d->pdev_depth == 32 && d->brush_pm.depth() != 32) {
                 d->brush_pm.detach();
                 QX11PixmapData *brushData = static_cast<QX11PixmapData*>(d->brush_pm.data.data());
                 brushData->convertToARGB32();
             }
 #endif
             vals.tile = (d->brush_pm.depth() == d->pdev_depth
                          ? d->brush_pm.handle()
                          : static_cast<QX11PixmapData*>(d->brush_pm.data.data())->x11ConvertToDefaultDepth());
             s = FillTiled;
 #if !defined(QT_NO_XRENDER)
             d->current_brush = d->cbrush.texture().x11PictureHandle();
 #endif
         }
         mask |= GCTileStipXOrigin | GCTileStipYOrigin;
         vals.ts_x_origin = qRound(origin.x());
         vals.ts_y_origin = qRound(origin.y());
     }
 #if !defined(QT_NO_XRENDER)
     else if (d->has_alpha_brush) {
         d->current_brush = X11->getSolidFill(d->scrn, d->cbrush.color());
     }
 #endif
     vals.fill_style = s;
     XChangeGC(d->dpy, d->gc_brush, mask, &vals);
     if (!d->has_clipping) {
         QRegion sysClip = systemClip();
         if (!sysClip.isEmpty())
             x11SetClipRegion(d->dpy, d->gc_brush, 0, d->picture, sysClip);
         else
             x11ClearClipRegion(d->dpy, d->gc_brush, 0, d->picture);
     }
 }
updateClipRegion_dev()
void QX11PaintEngine::updateClipRegion_dev (const QRegion & region, Qt::ClipOperation op)
Definition at line 2064 of file qpaintengine_x11.cpp.
Referenced by updateState().
 {
     Q_D(QX11PaintEngine);
     QRegion sysClip = systemClip();
     if (op == Qt::NoClip) {
         d->has_clipping = false;
         d->crgn = sysClip;
         if (!sysClip.isEmpty()) {
             x11SetClipRegion(d->dpy, d->gc, d->gc_brush, d->picture, sysClip);
         } else {
             x11ClearClipRegion(d->dpy, d->gc, d->gc_brush, d->picture);
         }
         return;
     }
     switch (op) {
     case Qt::IntersectClip:
         if (d->has_clipping) {
             d->crgn &= clipRegion;
             break;
         }
         // fall through
     case Qt::ReplaceClip:
         if (!sysClip.isEmpty())
             d->crgn = clipRegion.intersected(sysClip);
         else
             d->crgn = clipRegion;
         break;
     case Qt::UniteClip:
         d->crgn |= clipRegion;
         if (!sysClip.isEmpty())
             d->crgn = d->crgn.intersected(sysClip);
         break;
     default:
         break;
     }
     d->has_clipping = true;
     x11SetClipRegion(d->dpy, d->gc, d->gc_brush, d->picture, d->crgn);
 }
updateFont()
void QX11PaintEngine::updateFont (const QFont & font)
Definition at line 2104 of file qpaintengine_x11.cpp.
Referenced by updateState().
 {
 }
updateMatrix()
void QX11PaintEngine::updateMatrix (const QTransform & matrix)
Definition at line 2047 of file qpaintengine_x11.cpp.
Referenced by updateState().
 {
     Q_D(QX11PaintEngine);
     d->txop = mtx.type();
     d->matrix = mtx;
     d->has_complex_xform = (d->txop > QTransform::TxTranslate);
     extern bool qt_scaleForTransform(const QTransform &transform, qreal *scale);
     bool scaling = qt_scaleForTransform(d->matrix, &d->xform_scale);
     d->has_scaling_xform = scaling && d->xform_scale != 1.0;
     d->has_non_scaling_xform = scaling && d->xform_scale == 1.0;
 }
updatePen()
void QX11PaintEngine::updatePen (const QPen & pen)
Definition at line 1184 of file qpaintengine_x11.cpp.
Referenced by begin(), and updateState().
 {
     Q_D(QX11PaintEngine);
     d->cpen = pen;
     int cp = CapButt;
     int jn = JoinMiter;
     int ps = pen.style();
     if (d->opacity < 1.0) {
         QColor c = d->cpen.color();
         c.setAlpha(qRound(c.alpha()*d->opacity));
         d->cpen.setColor(c);
     }
     d->has_pen = (ps != Qt::NoPen);
     d->has_alpha_pen = (pen.color().alpha() != 255);
     switch (pen.capStyle()) {
     case Qt::SquareCap:
         cp = CapProjecting;
         break;
     case Qt::RoundCap:
         cp = CapRound;
         break;
     case Qt::FlatCap:
     default:
         cp = CapButt;
         break;
     }
     switch (pen.joinStyle()) {
     case Qt::BevelJoin:
         jn = JoinBevel;
         break;
     case Qt::RoundJoin:
         jn = JoinRound;
         break;
     case Qt::MiterJoin:
     default:
         jn = JoinMiter;
         break;
     }
     d->adapted_pen_origin = false;
     char dashes[10];                            // custom pen dashes
     int dash_len = 0;                           // length of dash list
     int xStyle = LineSolid;
     /*
       We are emulating Windows here.  Windows treats cpen.width() == 1
       (or 0) as a very special case.  The fudge variable unifies this
       case with the general case.
     */
     qreal pen_width = pen.widthF();
     int scale =  qRound(pen_width < 1 ? 1 : pen_width);
     int space = (pen_width < 1 && pen_width > 0 ? 1 : (2 * scale));
     int dot = 1 * scale;
     int dash = 4 * scale;
     d->has_custom_pen = false;
     switch (ps) {
     case Qt::NoPen:
     case Qt::SolidLine:
         xStyle = LineSolid;
     break;
     case Qt::DashLine:
     dashes[0] = dash;
     dashes[1] = space;
     dash_len = 2;
         xStyle = LineOnOffDash;
     break;
     case Qt::DotLine:
     dashes[0] = dot;
     dashes[1] = space;
     dash_len = 2;
         xStyle = LineOnOffDash;
     break;
     case Qt::DashDotLine:
     dashes[0] = dash;
     dashes[1] = space;
     dashes[2] = dot;
     dashes[3] = space;
     dash_len = 4;
         xStyle = LineOnOffDash;
     break;
     case Qt::DashDotDotLine:
     dashes[0] = dash;
     dashes[1] = space;
     dashes[2] = dot;
     dashes[3] = space;
     dashes[4] = dot;
     dashes[5] = space;
     dash_len = 6;
         xStyle = LineOnOffDash;
         break;
     case Qt::CustomDashLine:
         d->has_custom_pen = true;
         break;
     }
     ulong mask = GCForeground | GCBackground | GCGraphicsExposures | GCLineWidth
                  | GCCapStyle | GCJoinStyle | GCLineStyle;
     XGCValues vals;
     vals.graphics_exposures = false;
     if (d->pdev_depth == 1) {
         vals.foreground = qGray(pen.color().rgb()) > 127 ? 0 : 1;
         vals.background = qGray(QColor(Qt::transparent).rgb()) > 127 ? 0 : 1;
     } else if (d->pdev->devType() == QInternal::Pixmap && d->pdev_depth == 32
         && X11->use_xrender) {
         vals.foreground = pen.color().rgba();
         vals.background = QColor(Qt::transparent).rgba();
     } else {
         QColormap cmap = QColormap::instance(d->scrn);
         vals.foreground = cmap.pixel(pen.color());
         vals.background = cmap.pixel(QColor(Qt::transparent));
     }
     vals.line_width = qRound(pen.widthF());
     vals.cap_style = cp;
     vals.join_style = jn;
     vals.line_style = xStyle;
     XChangeGC(d->dpy, d->gc, mask, &vals);
     if (dash_len) { // make dash list
         XSetDashes(d->dpy, d->gc, 0, dashes, dash_len);
     }
     if (!d->has_clipping) { // if clipping is set the paintevent clip region is merged with the clip region
         QRegion sysClip = systemClip();
         if (!sysClip.isEmpty())
             x11SetClipRegion(d->dpy, d->gc, 0, d->picture, sysClip);
         else
             x11ClearClipRegion(d->dpy, d->gc, 0, d->picture);
     }
 }
updateRenderHints()
void QX11PaintEngine::updateRenderHints (QPainter::RenderHints hints)
Definition at line 1170 of file qpaintengine_x11.cpp.
Referenced by updateState().
 {
     Q_D(QX11PaintEngine);
     d->render_hints = hints;
 #if !defined(QT_NO_XRENDER)
     if (X11->use_xrender && d->picture) {
         XRenderPictureAttributes attrs;
         attrs.poly_edge = (hints & QPainter::Antialiasing) ? PolyEdgeSmooth : PolyEdgeSharp;
         XRenderChangePicture(d->dpy, d->picture, CPPolyEdge, &attrs);
     }
 #endif
 }
updateState()
void QX11PaintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Definition at line 1078 of file qpaintengine_x11.cpp.
Referenced by QPaintEngine::syncState().
 {
     Q_D(QX11PaintEngine);
     QPaintEngine::DirtyFlags flags = state.state();
     if (flags & DirtyOpacity) {
         d->opacity = state.opacity();
         // Force update pen/brush as to get proper alpha colors propagated
         flags |= DirtyPen;
         flags |= DirtyBrush;
     }
     if (flags & DirtyTransform) updateMatrix(state.transform());
     if (flags & DirtyPen) updatePen(state.pen());
     if (flags & (DirtyBrush | DirtyBrushOrigin)) updateBrush(state.brush(), state.brushOrigin());
     if (flags & DirtyFont) updateFont(state.font());
     if (state.state() & DirtyClipEnabled) {
         if (state.isClipEnabled()) {
             QPolygonF clip_poly_dev(d->matrix.map(painter()->clipPath().toFillPolygon()));
             QPolygonF clipped_poly_dev;
             d->clipPolygon_dev(clip_poly_dev, &clipped_poly_dev);
             updateClipRegion_dev(QRegion(clipped_poly_dev.toPolygon()), Qt::ReplaceClip);
         } else {
             updateClipRegion_dev(QRegion(), Qt::NoClip);
         }
     }
     if (flags & DirtyClipPath) {
         QPolygonF clip_poly_dev(d->matrix.map(state.clipPath().toFillPolygon()));
         QPolygonF clipped_poly_dev;
         d->clipPolygon_dev(clip_poly_dev, &clipped_poly_dev);
         updateClipRegion_dev(QRegion(clipped_poly_dev.toPolygon(), state.clipPath().fillRule()),
                              state.clipOperation());
     } else if (flags & DirtyClipRegion) {
         extern QPainterPath qt_regionToPath(const QRegion &region);
         QPainterPath clip_path = qt_regionToPath(state.clipRegion());
         QPolygonF clip_poly_dev(d->matrix.map(clip_path.toFillPolygon()));
         QPolygonF clipped_poly_dev;
         d->clipPolygon_dev(clip_poly_dev, &clipped_poly_dev);
         updateClipRegion_dev(QRegion(clipped_poly_dev.toPolygon()), state.clipOperation());
     }
     if (flags & DirtyHints) updateRenderHints(state.renderHints());
     if (flags & DirtyCompositionMode) {
         int function = GXcopy;
         if (state.compositionMode() >= QPainter::RasterOp_SourceOrDestination) {
             switch (state.compositionMode()) {
             case QPainter::RasterOp_SourceOrDestination:
                 function = GXor;
                 break;
             case QPainter::RasterOp_SourceAndDestination:
                 function = GXand;
                 break;
             case QPainter::RasterOp_SourceXorDestination:
                 function = GXxor;
                 break;
             case QPainter::RasterOp_NotSourceAndNotDestination:
                 function = GXnor;
                 break;
             case QPainter::RasterOp_NotSourceOrNotDestination:
                 function = GXnand;
                 break;
             case QPainter::RasterOp_NotSourceXorDestination:
                 function = GXequiv;
                 break;
             case QPainter::RasterOp_NotSource:
                 function = GXcopyInverted;
                 break;
             case QPainter::RasterOp_SourceAndNotDestination:
                 function = GXandReverse;
                 break;
             case QPainter::RasterOp_NotSourceAndDestination:
                 function = GXandInverted;
                 break;
             default:
                 function = GXcopy;
             }
         }
 #if !defined(QT_NO_XRENDER)
         else {
             d->composition_mode =
             qpainterOpToXrender(state.compositionMode());
         }
 #endif
         XSetFunction(X11->display, d->gc, function);
         XSetFunction(X11->display, d->gc_brush, function);
     }
     d->decidePathFallback();
     d->decideCoordAdjust();
 }
Friends and Related Functions
QFontEngineBox
friend class QFontEngineBox friend
Definition at line 133 of file qpaintengine_x11_p.h.
QPixmap
friend class QPixmap friend
Definition at line 132 of file qpaintengine_x11_p.h.
Referenced by updateBrush().
qt_x11_get_brush_gc
Q_GUI_EXPORT GC qt_x11_get_brush_gc (QPainter * p) friend
Returns the X11 specific brush GC for the painter p.
Note that QPainter::begin() must be called before this function returns a valid GC.
Definition at line 115 of file qpaintengine_x11.cpp.
 {
     if (p && p->paintEngine()
         && p->paintEngine()->isActive()
         && p->paintEngine()->type() == QPaintEngine::X11) {
         return static_cast<QX11PaintEngine *>(p->paintEngine())->d_func()->gc_brush;
     }
     return 0;
 }
qt_x11_get_pen_gc
Q_GUI_EXPORT GC qt_x11_get_pen_gc (QPainter * p) friend
Returns the X11 specific pen GC for the painter p.
Note that QPainter::begin() must be called before this function returns a valid GC.
Definition at line 100 of file qpaintengine_x11.cpp.
 {
     if (p && p->paintEngine()
         && p->paintEngine()->isActive()
         && p->paintEngine()->type() == QPaintEngine::X11) {
         return static_cast<QX11PaintEngine *>(p->paintEngine())->d_func()->gc;
     }
     return 0;
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine_x11_p.h
/src/gui/painting/qpaintengine_x11.cpp