Qt 4.8: QChar Class Reference
QChar Class Reference
The QChar class provides a 16-bit Unicode character.
#include <qchar.h>
Public Types
enum Category {
NoCategory, Mark_NonSpacing, Mark_SpacingCombining, Mark_Enclosing,
Number_DecimalDigit, Number_Letter, Number_Other, Separator_Space,
Separator_Line, Separator_Paragraph, Other_Control, Other_Format,
Other_Surrogate, Other_PrivateUse, Other_NotAssigned, Letter_Uppercase,
Letter_Lowercase, Letter_Titlecase, Letter_Modifier, Letter_Other,
Punctuation_Connector, Punctuation_Dash, Punctuation_Open, Punctuation_Close,
Punctuation_InitialQuote, Punctuation_FinalQuote, Punctuation_Other, Symbol_Math,
Symbol_Currency, Symbol_Modifier, Symbol_Other, Punctuation_Dask = Punctuation_Dash
}
This enum maps the Unicode character categories.
enum CombiningClass {
Combining_BelowLeftAttached = 200, Combining_BelowAttached = 202, Combining_BelowRightAttached = 204, Combining_LeftAttached = 208,
Combining_RightAttached = 210, Combining_AboveLeftAttached = 212, Combining_AboveAttached = 214, Combining_AboveRightAttached = 216,
Combining_BelowLeft = 218, Combining_Below = 220, Combining_BelowRight = 222, Combining_Left = 224,
Combining_Right = 226, Combining_AboveLeft = 228, Combining_Above = 230, Combining_AboveRight = 232,
Combining_DoubleBelow = 233, Combining_DoubleAbove = 234, Combining_IotaSubscript = 240
}
This enum type defines names for some of the Unicode combining classes.
enum Decomposition {
NoDecomposition, Canonical, Font, NoBreak,
Initial, Medial, Final, Isolated,
Circle, Super, Sub, Vertical,
Wide, Narrow, Small, Square,
Compat, Fraction
}
This enum type defines the Unicode decomposition attributes.
enum Direction {
DirL, DirR, DirEN, DirES,
DirET, DirAN, DirCS, DirB,
DirS, DirWS, DirON, DirLRE,
DirLRO, DirAL, DirRLE, DirRLO,
DirPDF, DirNSM, DirBN
}
This enum type defines the Unicode direction attributes.
enum Joining { OtherJoining, Dual, Right, Center }
This enum type defines the Unicode joining attributes.
enum SpecialCharacter {
Null = 0x0000, Nbsp = 0x00a0, ReplacementCharacter = 0xfffd, ObjectReplacementCharacter = 0xfffc,
ByteOrderMark = 0xfeff, ByteOrderSwapped = 0xfffe, ParagraphSeparator = 0x2029, LineSeparator = 0x2028
}
enum UnicodeVersion {
Unicode_Unassigned, Unicode_1_1, Unicode_2_0, Unicode_2_1_2,
Unicode_3_0, Unicode_3_1, Unicode_3_2, Unicode_4_0,
Unicode_4_1, Unicode_5_0
}
Specifies which version of the [Unicode standard](http://www.
Public Functions
Category category () const
Returns the character's category.
uchar cell () const
Returns the cell (least significant byte) of the Unicode character.
unsigned char combiningClass () const
Returns the combining class for the character as defined in the Unicode standard.
QString decomposition () const
Decomposes a character into its parts.
Decomposition decompositionTag () const
Returns the tag defining the composition of the character.
int digitValue () const
Returns the numeric value of the digit, or -1 if the character is not a digit.
Direction direction () const
Returns the character's direction.
bool hasMirrored () const
Returns true if the character should be reversed if the text direction is reversed; otherwise returns false.
bool isDigit () const
Returns true if the character is a decimal digit (Number_DecimalDigit); otherwise returns false.
bool isHighSurrogate () const
Returns true if the QChar is the high part of a utf16 surrogate (ie.
bool isLetter () const
Returns true if the character is a letter (Letter_* categories); otherwise returns false.
bool isLetterOrNumber () const
Returns true if the character is a letter or number (Letter_* or Number_* categories); otherwise returns false.
bool isLower () const
Returns true if the character is a lowercase letter, i.
bool isLowSurrogate () const
Returns true if the QChar is the low part of a utf16 surrogate (ie.
bool isMark () const
Returns true if the character is a mark (Mark_* categories); otherwise returns false.
bool isNull () const
Returns true if the character is the Unicode character 0x0000 ('\0'); otherwise returns false.
bool isNumber () const
Returns true if the character is a number (Number_* categories, not just 0-9); otherwise returns false.
bool isPrint () const
Returns true if the character is a printable character; otherwise returns false.
bool isPunct () const
Returns true if the character is a punctuation mark (Punctuation_* categories); otherwise returns false.
bool isSpace () const
Returns true if the character is a separator character (Separator_* categories); otherwise returns false.
bool isSymbol () const
Returns true if the character is a symbol (Symbol_* categories); otherwise returns false.
bool isTitleCase () const
Returns true if the character is a titlecase letter, i.
bool isUpper () const
Returns true if the character is an uppercase letter, i.
Joining joining () const
Returns information about the joining properties of the character (needed for certain languages such as Arabic).
QChar mirroredChar () const
Returns the mirrored character if this character is a mirrored character; otherwise returns the character itself.
QChar ()
Constructs a null QChar ('\0').
QT_ASCII_CAST_WARN_CONSTRUCTOR QChar (char c)
Constructs a QChar corresponding to ASCII/Latin-1 character ch.
QT_ASCII_CAST_WARN_CONSTRUCTOR QChar (uchar c)
Constructs a QChar corresponding to ASCII/Latin-1 character ch.
QChar (QLatin1Char ch)
Constructs a QChar corresponding to ASCII/Latin-1 character ch.
QChar (uchar c, uchar r)
Constructs a QChar for Unicode cell cell in row row.
QChar (ushort rc)
Constructs a QChar for the character with Unicode code point code.
QChar (short rc)
Constructs a QChar for the character with Unicode code point code.
QChar (uint rc)
Constructs a QChar for the character with Unicode code point code.
QChar (int rc)
Constructs a QChar for the character with Unicode code point code.
QChar (SpecialCharacter sc)
Constructs a QChar for the predefined character value ch.
uchar row () const
Returns the row (most significant byte) of the Unicode character.
void setCell (uchar cell)
void setRow (uchar row)
char toAscii () const
Returns the character value of the QChar obtained using the current codec used to read C strings, or 0 if the character is not representable using this codec.
QChar toCaseFolded () const
Returns the case folded equivalent of the character.
char toLatin1 () const
Returns the Latin-1 character equivalent to the QChar, or 0.
QChar toLower () const
Returns the lowercase equivalent if the character is uppercase or titlecase; otherwise returns the character itself.
QChar toTitleCase () const
Returns the title case equivalent if the character is lowercase or uppercase; otherwise returns the character itself.
QChar toUpper () const
Returns the uppercase equivalent if the character is lowercase or titlecase; otherwise returns the character itself.
ushort unicode () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
ushort & unicode ()
Returns a reference to the numeric Unicode value of the QChar.
UnicodeVersion unicodeVersion () const
Returns the Unicode version that introduced this character.
Static Public Functions
static Category QT_FASTCALL category (uint ucs4)
Returns the category of the UCS-4-encoded character specified by ucs4.
static Category QT_FASTCALL category (ushort ucs2)
Returns the category of the UCS-2-encoded character specified by ucs2.
static unsigned char QT_FASTCALL combiningClass (uint ucs4)
Returns the combining class for the UCS-4-encoded character specified by ucs4, as defined in the Unicode standard.
static unsigned char QT_FASTCALL combiningClass (ushort ucs2)
Returns the combining class for the UCS-2-encoded character specified by ucs2, as defined in the Unicode standard.
static UnicodeVersion QT_FASTCALL currentUnicodeVersion ()
Returns the most recent supported Unicode version.
static QString QT_FASTCALL decomposition (uint ucs4)
Decomposes the UCS-4-encoded character specified by ucs4 into its constituent parts.
static Decomposition QT_FASTCALL decompositionTag (uint ucs4)
Returns the tag defining the composition of the UCS-4-encoded character specified by ucs4.
static int QT_FASTCALL digitValue (uint ucs4)
Returns the numeric value of the digit specified by the UCS-4-encoded character, ucs4, or -1 if the character is not a digit.
static int QT_FASTCALL digitValue (ushort ucs2)
Returns the numeric value of the digit, specified by the UCS-2-encoded character, ucs2, or -1 if the character is not a digit.
static Direction QT_FASTCALL direction (uint ucs4)
Returns the direction of the UCS-4-encoded character specified by ucs4.
static Direction QT_FASTCALL direction (ushort ucs2)
Returns the direction of the UCS-2-encoded character specified by ucs2.
static QChar fromAscii (char c)
Converts the ASCII character c to its equivalent QChar.
static QChar fromLatin1 (char c)
Converts the Latin-1 character c to its equivalent QChar.
static ushort highSurrogate (uint ucs4)
Returns the high surrogate value of a ucs4 code point.
static bool isHighSurrogate (uint ucs4)
Returns true if the UCS-4-encoded character specified by ucs4 is the high part of a utf16 surrogate (ie.
static bool isLowSurrogate (uint ucs4)
Returns true if the UCS-4-encoded character specified by ucs4 is the low part of a utf16 surrogate (ie.
static Joining QT_FASTCALL joining (uint ucs4)
Returns information about the joining properties of the UCS-4-encoded character specified by ucs4 (needed for certain languages such as Arabic).
static Joining QT_FASTCALL joining (ushort ucs2)
Returns information about the joining properties of the UCS-2-encoded character specified by ucs2 (needed for certain languages such as Arabic).
static ushort lowSurrogate (uint ucs4)
Returns the low surrogate value of a ucs4 code point.
static uint QT_FASTCALL mirroredChar (uint ucs4)
Returns the mirrored character if the UCS-4-encoded character specified by ucs4 is a mirrored character; otherwise returns the character itself.
static ushort QT_FASTCALL mirroredChar (ushort ucs2)
Returns the mirrored character if the UCS-2-encoded character specified by ucs2 is a mirrored character; otherwise returns the character itself.
static bool requiresSurrogates (uint ucs4)
Returns true if the UCS-4-encoded character specified by ucs4 can be split into the high and low parts of a utf16 surrogate (ie.
static uint surrogateToUcs4 (ushort high, ushort low)
Converts a UTF16 surrogate pair with the given high and low values to its UCS-4 code point.
static uint surrogateToUcs4 (QChar high, QChar low)
Converts a utf16 surrogate pair (high, low) to its ucs4 code point.
static uint QT_FASTCALL toCaseFolded (uint ucs4)
Returns the case folded equivalent of the UCS-4-encoded character specified by ucs4.
static ushort QT_FASTCALL toCaseFolded (ushort ucs2)
Returns the case folded equivalent of the UCS-2-encoded character specified by ucs2.
static uint QT_FASTCALL toLower (uint ucs4)
Returns the lowercase equivalent of the UCS-4-encoded character specified by ucs4 if the character is uppercase or titlecase; otherwise returns the character itself.
static ushort QT_FASTCALL toLower (ushort ucs2)
Returns the lowercase equivalent of the UCS-2-encoded character specified by ucs2 if the character is uppercase or titlecase; otherwise returns the character itself.
static uint QT_FASTCALL toTitleCase (uint ucs4)
Returns the title case equivalent of the UCS-4-encoded character specified by ucs4 if the character is lowercase or uppercase; otherwise returns the character itself.
static ushort QT_FASTCALL toTitleCase (ushort ucs2)
Returns the title case equivalent of the UCS-2-encoded character specified by ucs2 if the character is lowercase or uppercase; otherwise returns the character itself.
static uint QT_FASTCALL toUpper (uint ucs4)
Returns the uppercase equivalent of the UCS-4-encoded character specified by ucs4 if the character is lowercase or titlecase; otherwise returns the character itself.
static ushort QT_FASTCALL toUpper (ushort ucs2)
Returns the uppercase equivalent of the UCS-2-encoded character specified by ucs2 if the character is lowercase or titlecase; otherwise returns the character itself.
static UnicodeVersion QT_FASTCALL unicodeVersion (uint ucs4)
Returns the Unicode version that introduced the character specified in its UCS-4-encoded form as ucs4.
static UnicodeVersion QT_FASTCALL unicodeVersion (ushort ucs2)
Returns the Unicode version that introduced the character specified in its UCS-2-encoded form as ucs2.
Properties
ushort ucs
Related Functions
(Note that these are not member functions.)
int operator!= (QChar c1, QChar c2)
Returns true if c1 and c2 are not the same Unicode character; otherwise returns false.
int operator< (QChar c1, QChar c2)
Returns true if the numeric Unicode value of c1 is less than that of c2; otherwise returns false.
QDataStream & operator<< (QDataStream &out, const QChar &chr)
Writes the char chr to the stream out.
int operator<= (QChar c1, QChar c2)
Returns true if the numeric Unicode value of c1 is less than or equal to that of c2; otherwise returns false.
bool operator== (QChar c1, QChar c2)
Returns true if c1 and c2 are the same Unicode character; otherwise returns false.
int operator> (QChar c1, QChar c2)
Returns true if the numeric Unicode value of c1 is greater than that of c2; otherwise returns false.
int operator>= (QChar c1, QChar c2)
Returns true if the numeric Unicode value of c1 is greater than or equal to that of c2; otherwise returns false.
QDataStream & operator>> (QDataStream &in, QChar &chr)
Reads a char from the stream in into char chr.
Detailed Description
The QChar class provides a 16-bit Unicode character.
Note
This class or function is reentrant.
In Qt, Unicode characters are 16-bit entities without any markup or structure. This class represents such an entity. It is lightweight, so it can be used everywhere. Most compilers treat it like a unsigned short.
QChar provides a full complement of testing/classification functions, converting to and from other formats, converting from composed to decomposed Unicode, and trying to compare and case-convert if you ask it to.
The classification functions include functions like those in the standard C++ header <cctype> (formerly <ctype.h>), but operating on the full range of Unicode characters. They all return true if the character is a certain type of character; otherwise they return false. These classification functions are isNull() (returns true if the character is '\0'), isPrint() (true if the character is any sort of printable character, including whitespace), isPunct() (any sort of punctation), isMark() (Unicode Mark), isLetter() (a letter), isNumber() (any sort of numeric character, not just 0-9), isLetterOrNumber(), and isDigit() (decimal digits). All of these are wrappers around category() which return the Unicode-defined category of each character.
QChar also provides direction(), which indicates the "natural" writing direction of this character. The joining() function indicates how the character joins with its neighbors (needed mostly for Arabic) and finally hasMirrored(), which indicates whether the character needs to be mirrored when it is printed in its "unnatural" writing direction.
Composed Unicode characters (like) can be converted to decomposed Unicode ("a" followed by "ring above") by using decomposition().
In Unicode, comparison is not necessarily possible and case conversion is very difficult at best. Unicode, covering the "entire" world, also includes most of the world's case and sorting problems. operator==() and friends will do comparison based purely on the numeric Unicode value (code point) of the characters, and toUpper() and toLower() will do case changes when the character has a well-defined uppercase/lowercase equivalent. For locale-dependent comparisons, use QString::localeAwareCompare().
The conversion functions include unicode() (to a scalar), toLatin1() (to scalar, but converts all non-Latin-1 characters to 0), row() (gives the Unicode row), cell() (gives the Unicode cell), digitValue() (gives the integer value of any of the numerous digit characters), and a host of constructors.
QChar provides constructors and cast operators that make it easy to convert to and from traditional 8-bit chars. If you defined QT_NO_CAST_FROM_ASCII and QT_NO_CAST_TO_ASCII, as explained in the QString documentation, you will need to explicitly call fromAscii() or fromLatin1(), or use QLatin1Char, to construct a QChar from an 8-bit char, and you will need to call toAscii() or toLatin1() to get the 8-bit value back.
See also
QString, Unicode, QLatin1Char
Definition at line 72 of file qchar.h.
Enumerations
Category
enum QChar::Category
This enum maps the Unicode character categories.
The following characters are normative in Unicode:
Mark_NonSpacing Unicode class name Mn
Mark_SpacingCombining Unicode class name Mc
Mark_Enclosing Unicode class name Me
Number_DecimalDigit Unicode class name Nd
Number_Letter Unicode class name Nl
Number_Other Unicode class name No
Separator_Space Unicode class name Zs
Separator_Line Unicode class name Zl
Separator_Paragraph Unicode class name Zp
Other_Control Unicode class name Cc
Other_Format Unicode class name Cf
Other_Surrogate Unicode class name Cs
Other_PrivateUse Unicode class name Co
Other_NotAssigned Unicode class name Cn
The following categories are informative in Unicode:
Letter_Uppercase Unicode class name Lu
Letter_Lowercase Unicode class name Ll
Letter_Titlecase Unicode class name Lt
Letter_Modifier Unicode class name Lm
Letter_Other Unicode class name Lo
Punctuation_Connector Unicode class name Pc
Punctuation_Dash Unicode class name Pd
Punctuation_Open Unicode class name Ps
Punctuation_Close Unicode class name Pe
Punctuation_InitialQuote Unicode class name Pi
Punctuation_FinalQuote Unicode class name Pf
Punctuation_Other Unicode class name Po
Symbol_Math Unicode class name Sm
Symbol_Currency Unicode class name Sc
Symbol_Modifier Unicode class name Sk
Symbol_Other Unicode class name So
NoCategory Qt cannot find an appropriate category for the character.
Punctuation_Dask
See also
category()
Enumerator
NoCategory
Mark_NonSpacing
Mark_SpacingCombining
Mark_Enclosing
Number_DecimalDigit
Number_Letter
Number_Other
Separator_Space
Separator_Line
Separator_Paragraph
Other_Control
Other_Format
Other_Surrogate
Other_PrivateUse
Other_NotAssigned
Letter_Uppercase
Letter_Lowercase
Letter_Titlecase
Letter_Modifier
Letter_Other
Punctuation_Connector
Punctuation_Dash
Punctuation_Open
Punctuation_Close
Punctuation_InitialQuote
Punctuation_FinalQuote
Punctuation_Other
Symbol_Math
Symbol_Currency
Symbol_Modifier
Symbol_Other
Punctuation_Dask
Definition at line 106 of file qchar.h.
     {
         NoCategory,    // ### Qt 5: replace with Other_NotAssigned
         Mark_NonSpacing,          //   Mn
         Mark_SpacingCombining,    //   Mc
         Mark_Enclosing,           //   Me
         Number_DecimalDigit,      //   Nd
         Number_Letter,            //   Nl
         Number_Other,             //   No
         Separator_Space,          //   Zs
         Separator_Line,           //   Zl
         Separator_Paragraph,      //   Zp
         Other_Control,            //   Cc
         Other_Format,             //   Cf
         Other_Surrogate,          //   Cs
         Other_PrivateUse,         //   Co
         Other_NotAssigned,        //   Cn
         Letter_Uppercase,         //   Lu
         Letter_Lowercase,         //   Ll
         Letter_Titlecase,         //   Lt
         Letter_Modifier,          //   Lm
         Letter_Other,             //   Lo
         Punctuation_Connector,    //   Pc
         Punctuation_Dash,         //   Pd
         Punctuation_Open,         //   Ps
         Punctuation_Close,        //   Pe
         Punctuation_InitialQuote, //   Pi
         Punctuation_FinalQuote,   //   Pf
         Punctuation_Other,        //   Po
         Symbol_Math,              //   Sm
         Symbol_Currency,          //   Sc
         Symbol_Modifier,          //   Sk
         Symbol_Other,             //   So
         Punctuation_Dask = Punctuation_Dash // ### Qt 5: remove
     };
CombiningClass
enum QChar::CombiningClass
This enum type defines names for some of the Unicode combining classes.
Warning
This function is not part of the public interface.
See the Unicode Standard for a description of the values.
Combining_Above
Combining_AboveAttached
Combining_AboveLeft
Combining_AboveLeftAttached
Combining_AboveRight
Combining_AboveRightAttached
Combining_Below
Combining_BelowAttached
Combining_BelowLeft
Combining_BelowLeftAttached
Combining_BelowRight
Combining_BelowRightAttached
Combining_DoubleAbove
Combining_DoubleBelow
Combining_IotaSubscript
Combining_Left
Combining_LeftAttached
Combining_Right
Combining_RightAttached
Enumerator
Combining_BelowLeftAttached
Combining_BelowAttached
Combining_BelowRightAttached
Combining_LeftAttached
Combining_RightAttached
Combining_AboveLeftAttached
Combining_AboveAttached
Combining_AboveRightAttached
Combining_BelowLeft
Combining_Below
Combining_BelowRight
Combining_Left
Combining_Right
Combining_AboveLeft
Combining_Above
Combining_AboveRight
Combining_DoubleBelow
Combining_DoubleAbove
Combining_IotaSubscript
Definition at line 187 of file qchar.h.
     {
         Combining_BelowLeftAttached       = 200,
         Combining_BelowAttached           = 202,
         Combining_BelowRightAttached      = 204,
         Combining_LeftAttached            = 208,
         Combining_RightAttached           = 210,
         Combining_AboveLeftAttached       = 212,
         Combining_AboveAttached           = 214,
         Combining_AboveRightAttached      = 216,
         Combining_BelowLeft               = 218,
         Combining_Below                   = 220,
         Combining_BelowRight              = 222,
         Combining_Left                    = 224,
         Combining_Right                   = 226,
         Combining_AboveLeft               = 228,
         Combining_Above                   = 230,
         Combining_AboveRight              = 232,
         Combining_DoubleBelow             = 233,
         Combining_DoubleAbove             = 234,
         Combining_IotaSubscript           = 240
     };
Decomposition
enum QChar::Decomposition
This enum type defines the Unicode decomposition attributes.
See the Unicode Standard for a description of the values.
NoDecomposition
Canonical
Circle
Compat
Final
Font
Fraction
Initial
Isolated
Medial
Narrow
NoBreak
Small
Square
Sub
Super
Vertical
Wide
Single
See also
decomposition()
Enumerator
NoDecomposition
Canonical
Font
NoBreak
Initial
Medial
Final
Isolated
Circle
Super
Sub
Vertical
Wide
Narrow
Small
Square
Compat
Fraction
Definition at line 156 of file qchar.h.
     {
         NoDecomposition,
         Canonical,
         Font,
         NoBreak,
         Initial,
         Medial,
         Final,
         Isolated,
         Circle,
         Super,
         Sub,
         Vertical,
         Wide,
         Narrow,
         Small,
         Square,
         Compat,
         Fraction
 #ifdef QT3_SUPPORT
         , Single = NoDecomposition
 #endif
     };
Direction
enum QChar::Direction
This enum type defines the Unicode direction attributes.
See the Unicode Standard for a description of the values.
In order to conform to C/C++ naming conventions "Dir" is prepended to the codes used in the Unicode Standard.
DirAL
DirAN
DirB
DirBN
DirCS
DirEN
DirES
DirET
DirL
DirLRE
DirLRO
DirNSM
DirON
DirPDF
DirR
DirRLE
DirRLO
DirS
DirWS
See also
direction()
Enumerator
DirL
DirR
DirEN
DirES
DirET
DirAN
DirCS
DirB
DirS
DirWS
DirON
DirLRE
DirLRO
DirAL
DirRLE
DirRLO
DirPDF
DirNSM
DirBN
Definition at line 150 of file qchar.h.
     {
         DirL, DirR, DirEN, DirES, DirET, DirAN, DirCS, DirB, DirS, DirWS, DirON,
         DirLRE, DirLRO, DirAL, DirRLE, DirRLO, DirPDF, DirNSM, DirBN
     };
Joining
enum QChar::Joining
This enum type defines the Unicode joining attributes.
See the Unicode Standard for a description of the values.
Center
Dual
OtherJoining
Right
See also
joining()
Enumerator
OtherJoining
Dual
Right
Center
Definition at line 182 of file qchar.h.
     {
         OtherJoining, Dual, Right, Center
     };
SpecialCharacter
enum QChar::SpecialCharacter
Null A QChar with this value isNull().
Nbsp Non-breaking space.
ReplacementCharacter The character shown when a font has no glyph for a certain codepoint. A special question mark character is often used. Codecs use this codepoint when input data cannot be represented in Unicode.
ObjectReplacementCharacter Used to represent an object such as an image when such objects cannot be presented.
ByteOrderMark
ByteOrderSwapped
ParagraphSeparator
LineSeparator
null
replacement
byteOrderMark
byteOrderSwapped
nbsp
Enumerator
Null
Nbsp
ReplacementCharacter
ObjectReplacementCharacter
ByteOrderMark
ByteOrderSwapped
ParagraphSeparator
LineSeparator
Definition at line 85 of file qchar.h.
{
         Null = 0x0000,
         Nbsp = 0x00a0,
         ReplacementCharacter = 0xfffd,
         ObjectReplacementCharacter = 0xfffc,
         ByteOrderMark = 0xfeff,
         ByteOrderSwapped = 0xfffe,
 #ifdef QT3_SUPPORT
         null = Null,
         replacement = ReplacementCharacter,
         byteOrderMark = ByteOrderMark,
         byteOrderSwapped = ByteOrderSwapped,
         nbsp = Nbsp,
 #endif
         ParagraphSeparator = 0x2029,
         LineSeparator = 0x2028
     };
UnicodeVersion
enum QChar::UnicodeVersion
Specifies which version of the [Unicode standard](http://www.
unicode.org/) introduced a certain character.
Unicode_1_1 Version 1.1
Unicode_2_0 Version 2.0
Unicode_2_1_2 Version 2.1.2
Unicode_3_0 Version 3.0
Unicode_3_1 Version 3.1
Unicode_3_2 Version 3.2
Unicode_4_0 Version 4.0
Unicode_4_1 Version 4.1
Unicode_5_0 Version 5.0
Unicode_Unassigned The value is not assigned to any character in version 5.0 of Unicode.
See also
unicodeVersion()
Enumerator
Unicode_Unassigned
Unicode_1_1
Unicode_2_0
Unicode_2_1_2
Unicode_3_0
Unicode_3_1
Unicode_3_2
Unicode_4_0
Unicode_4_1
Unicode_5_0
Definition at line 212 of file qchar.h.
{
         Unicode_Unassigned,    // ### Qt 5: assign with some constantly big value
         Unicode_1_1,
         Unicode_2_0,
         Unicode_2_1_2,
         Unicode_3_0,
         Unicode_3_1,
         Unicode_3_2,
         Unicode_4_0,
         Unicode_4_1,
         Unicode_5_0
     };
Constructors and Destructors
QChar() [1/10]
QChar::QChar () inline
Constructs a null QChar ('\0').
See also
isNull()
Definition at line 371 of file qchar.h.
Referenced by canonicalOrderHelper(), composeHelper(), decomposeHelper(), foldCase(), fromAscii(), and fromLatin1().
 : ucs(0) {}
QChar() [2/10]
QChar::QChar (char c)
Constructs a QChar corresponding to ASCII/Latin-1 character ch.
Definition at line 477 of file qchar.cpp.
 {
 #ifndef QT_NO_CODEC_FOR_C_STRINGS
     if (QTextCodec::codecForCStrings())
         // #####
         ucs =  QTextCodec::codecForCStrings()->toUnicode(&ch, 1).at(0).unicode();
     else
 #endif
         ucs = uchar(ch);
 }
QChar() [3/10]
QChar::QChar (uchar c)
Constructs a QChar corresponding to ASCII/Latin-1 character ch.
Definition at line 491 of file qchar.cpp.
 {
 #ifndef QT_NO_CODEC_FOR_C_STRINGS
     if (QTextCodec::codecForCStrings()) {
         // #####
         char c = char(ch);
         ucs =  QTextCodec::codecForCStrings()->toUnicode(&c, 1).at(0).unicode();
     } else
 #endif
         ucs = ch;
 }
QChar() [4/10]
QChar::QChar (QLatin1Char ch) inline
Constructs a QChar corresponding to ASCII/Latin-1 character ch.
Definition at line 385 of file qchar.h.
 : ucs(ch.unicode()) {}
QChar() [5/10]
QChar::QChar (uchar cell, uchar row) inline
Constructs a QChar for Unicode cell cell in row row.
See also
cell(), row()
Definition at line 380 of file qchar.h.
 : ucs(ushort((r << 8) | c)){}
QChar() [6/10]
QChar::QChar (ushort rc) inline
Constructs a QChar for the character with Unicode code point code.
Definition at line 81 of file qchar.h.
 : ucs(rc){}
QChar() [7/10]
QChar::QChar (short rc) inline
Constructs a QChar for the character with Unicode code point code.
Definition at line 381 of file qchar.h.
 : ucs(ushort(rc)){}
QChar() [8/10]
QChar::QChar (uint rc) inline
Constructs a QChar for the character with Unicode code point code.
Definition at line 382 of file qchar.h.
 : ucs(ushort(rc & 0xffff)){}
QChar() [9/10]
QChar::QChar (int rc) inline
Constructs a QChar for the character with Unicode code point code.
Definition at line 383 of file qchar.h.
 : ucs(ushort(rc & 0xffff)){}
QChar() [10/10]
QChar::QChar (SpecialCharacter sc) inline
Constructs a QChar for the predefined character value ch.
Definition at line 384 of file qchar.h.
 : ucs(ushort(s)) {}
Functions
category() [1/3]
QChar::Category QChar::category () const
Returns the character's category.
Definition at line 853 of file qchar.cpp.
Referenced by arabicGroup(), QCharRef::category(), QFontMetrics::charWidth(), fastDetermineNameChar(), QDateTimeParser::findAmPm(), HB_GetUnicodeCharCategory(), heuristicSetGlyphAttributes(), QRegExpCharClass::in(), isDigit(), isLetter(), isLetterOrNumber(), isMark(), QPatternist::XQueryTokenizer::isNCNameBody(), QPatternist::XQueryTokenizer::isNCNameStart(), isNumber(), isPrint(), isPunct(), isSpace(), isSymbol(), QScriptDeclarativeClass::startsWithUpper(), QFontEngineMulti::stringToCMap(), QFontMetrics::width(), and QFontMetricsF::width().
 {
     return (QChar::Category) qGetProp(ucs)->category;
 }
category() [2/3]
QChar::Category QChar::category (uint ucs4) static
Returns the category of the UCS-4-encoded character specified by ucs4.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
Definition at line 866 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return QChar::NoCategory;
     return (QChar::Category) qGetProp(ucs4)->category;
 }
category() [3/3]
QChar::Category QChar::category (ushort ucs2) static
Returns the category of the UCS-2-encoded character specified by ucs2.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 880 of file qchar.cpp.
 {
     return (QChar::Category) qGetProp(ucs2)->category;
 }
cell()
uchar QChar::cell () const inline
Returns the cell (least significant byte) of the Unicode character.
See also
row()
Definition at line 283 of file qchar.h.
Referenced by QCharRef::cell(), QUtf16::convertFromUnicode(), QGbkCodec::convertFromUnicode(), QFontJis0208Codec::convertFromUnicode(), QEucJpCodec::convertFromUnicode(), QJisCodec::convertFromUnicode(), QSjisCodec::convertFromUnicode(), QGb2312Codec::convertFromUnicode(), QTsciiCodec::convertFromUnicode(), QFontBig5Codec::convertFromUnicode(), QFontBig5hkscsCodec::convertFromUnicode(), QFontKsc5601Codec::convertFromUnicode(), QFontGb18030_0Codec::convertFromUnicode(), heuristicSetGlyphAttributes(), QKeyMapperPrivate::isADeadKey(), QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::parseReference(), set_text(), and QPatternist::XQueryTokenizer::tokenizeNumberLiteral().
 { return uchar(ucs & 0xff); }
combiningClass() [1/3]
unsigned char QChar::combiningClass () const
Returns the combining class for the character as defined in the Unicode standard.
This is mainly useful as a positioning hint for marks attached to a base character.
The Qt text rendering engine uses this information to correctly position non-spacing marks around a base character.
Definition at line 1153 of file qchar.cpp.
Referenced by QCharRef::combiningClass(), and HB_GetUnicodeCharCombiningClass().
 {
     return (unsigned char) qGetProp(ucs)->combiningClass;
 }
combiningClass() [2/3]
unsigned char QChar::combiningClass (uint ucs4) static
Returns the combining class for the UCS-4-encoded character specified by ucs4, as defined in the Unicode standard.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1166 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return 0;
     return (unsigned char) qGetProp(ucs4)->combiningClass;
 }
combiningClass() [3/3]
unsigned char QChar::combiningClass (ushort ucs2) static
Returns the combining class for the UCS-2-encoded character specified by ucs2, as defined in the Unicode standard.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1181 of file qchar.cpp.
 {
     return (unsigned char) qGetProp(ucs2)->combiningClass;
 }
currentUnicodeVersion()
QChar::UnicodeVersion QChar::currentUnicodeVersion () static
Returns the most recent supported Unicode version.
Since
4.8
Definition at line 1230 of file qchar.cpp.
 {
     return UNICODE_DATA_VERSION;
 }
decomposition() [1/2]
QString QChar::decomposition () const
Decomposes a character into its parts.
Returns an empty string if no decomposition exists.
Definition at line 1096 of file qchar.cpp.
Referenced by QCharRef::decomposition(), and decompositionHelper().
 {
     return decomposition(ucs);
 }
decomposition() [2/2]
QString QChar::decomposition (uint ucs4) static
Decomposes the UCS-4-encoded character specified by ucs4 into its constituent parts.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Returns an empty string if no decomposition exists.
Definition at line 1109 of file qchar.cpp.
 {
     unsigned short buffer[3];
     int length;
     int tag;
     const unsigned short *d = decompositionHelper(ucs4, &length, &tag, buffer);
     return QString::fromUtf16(d, length);
 }
decompositionTag() [1/2]
QChar::Decomposition QChar::decompositionTag () const
Returns the tag defining the composition of the character.
Returns QChar::Single if no decomposition exists.
Definition at line 1122 of file qchar.cpp.
Referenced by QCharRef::decompositionTag().
 {
     return decompositionTag(ucs);
 }
decompositionTag() [2/2]
QChar::Decomposition QChar::decompositionTag (uint ucs4) static
Returns the tag defining the composition of the UCS-4-encoded character specified by ucs4.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Returns QChar::Single if no decomposition exists.
Definition at line 1135 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return QChar::NoDecomposition;
     const unsigned short index = GET_DECOMPOSITION_INDEX(ucs4);
     if (index == 0xffff)
         return QChar::NoDecomposition;
     return (QChar::Decomposition)(uc_decomposition_map[index] & 0xff);
 }
digitValue() [1/3]
int QChar::digitValue () const
Returns the numeric value of the digit, or -1 if the character is not a digit.
Definition at line 817 of file qchar.cpp.
Referenced by QCharRef::digitValue(), findArgEscapes(), QTextStreamPrivate::getNumber(), QLineControl::isValidInput(), QFileSystemModelPrivate::naturalCompare(), qt_mac_get_key(), QString::replace(), and replaceArgEscapes().
 {
     return qGetProp(ucs)->digitValue;
 }
digitValue() [2/3]
int QChar::digitValue (uint ucs4) static
Returns the numeric value of the digit specified by the UCS-4-encoded character, ucs4, or -1 if the character is not a digit.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 843 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return 0;
     return qGetProp(ucs4)->digitValue;
 }
digitValue() [3/3]
int QChar::digitValue (ushort ucs2) static
Returns the numeric value of the digit, specified by the UCS-2-encoded character, ucs2, or -1 if the character is not a digit.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 830 of file qchar.cpp.
 {
     return qGetProp(ucs2)->digitValue;
 }
direction() [1/3]
QChar::Direction QChar::direction () const
Returns the character's direction.
Definition at line 889 of file qchar.cpp.
Referenced by bidiItemize(), QCharRef::direction(), isStringRightToLeft(), skipBoundryNeutrals(), and QTextBlock::textDirection().
 {
     return (QChar::Direction) qGetProp(ucs)->direction;
 }
direction() [2/3]
QChar::Direction QChar::direction (uint ucs4) static
Returns the direction of the UCS-4-encoded character specified by ucs4.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 901 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return QChar::DirL;
     return (QChar::Direction) qGetProp(ucs4)->direction;
 }
direction() [3/3]
QChar::Direction QChar::direction (ushort ucs2) static
Returns the direction of the UCS-2-encoded character specified by ucs2.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 915 of file qchar.cpp.
 {
     return (QChar::Direction) qGetProp(ucs2)->direction;
 }
fromAscii()
QChar QChar::fromAscii (char c) static
Converts the ASCII character c to its equivalent QChar.
This is mainly useful for non-internationalized software.
An alternative is to use QLatin1Char.
See also
fromLatin1(), unicode(), QTextCodec::codecForCStrings()
Definition at line 1521 of file qchar.cpp.
Referenced by convert(), QAbstractConcatenable::convertFromAscii(), QString::isNull(), operator+(), QString::operator+=(), QTextStream::operator<<(), QString::operator=(), QCharRef::operator=(), and QHttpNetworkConnectionPrivate::prepareRequest().
 {
 #ifndef QT_NO_CODEC_FOR_C_STRINGS
     if (QTextCodec::codecForCStrings())
         // #####
         return QTextCodec::codecForCStrings()->toUnicode(&c, 1).at(0).unicode();
 #endif
     return QChar(ushort((uchar)c));
 }
fromLatin1()
QChar QChar::fromLatin1 (char c) inline static
Converts the Latin-1 character c to its equivalent QChar.
This is mainly useful for non-internationalized software.
See also
fromAscii(), unicode(), QTextCodec::codecForCStrings()
Definition at line 378 of file qchar.h.
Referenced by QPatternist::AbstractDateTime::create(), QPatternist::Cardinality::displayName(), QMessageBoxPrivate::hideSpecial(), QAxBase::initializeRemote(), QLocalePrivate::longLongToString(), QPatternist::AbstractDateTime::parseZoneOffset(), qt_wce_insert_action(), qt_wce_rename_menu_item(), QPatternist::XSLTTokenizer::queueSimpleContentConstructor(), QSqlRelationalTableModel::selectStatement(), QTest::sendKeyEvent(), QPatternist::NamePool::toClarkName(), and QLocalePrivate::unsLongLongToString().
 { return QChar(ushort(uchar(c))); }
hasMirrored()
bool QChar::hasMirrored () const
Returns true if the character should be reversed if the text direction is reversed; otherwise returns false.
Same as (ch.mirroredChar() != ch).
See also
mirroredChar()
Definition at line 968 of file qchar.cpp.
Referenced by QCharRef::hasMirrored().
 {
     return qGetProp(ucs)->mirrorDiff != 0;
 }
highSurrogate()
static ushort QChar::highSurrogate (uint ucs4) inline static
Returns the high surrogate value of a ucs4 code point.
The returned result is undefined if ucs4 is smaller than 0x10000.
Definition at line 303 of file qchar.h.
Referenced by canonicalOrderHelper(), QUtf8::convertToUnicode(), QUtf32::convertToUnicode(), QKeySequencePrivate::encodeString(), QTextHtmlParser::parseEntity(), qt_string_normalize(), QFontEngineWin::recalcAdvances(), QRawFont::supportsCharacter(), and QPatternist::XQueryTokenizer::tokenizeCharacterReference().
{
         return ushort((ucs4>>10) + 0xd7c0);
     }
isDigit()
bool QChar::isDigit () const
Returns true if the character is a decimal digit (Number_DecimalDigit); otherwise returns false.
Definition at line 699 of file qchar.cpp.
Referenced by QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QCharRef::isDigit(), QPatternist::DerivedString< TypeToken >::isNameChar(), QFileSystemModelPrivate::naturalCompare(), qt_mac_get_key(), and totalDigitsForDecimal().
 {
     return (qGetProp(ucs)->category == Number_DecimalDigit);
 }
isHighSurrogate() [1/2]
bool QChar::isHighSurrogate () const inline
Returns true if the QChar is the high part of a utf16 surrogate (ie.
if its code point is between 0xd800 and 0xdbff, inclusive).
Definition at line 276 of file qchar.h.
Referenced by atsuPostLayoutCallback(), QLineControl::backspace(), canonicalOrderHelper(), composeHelper(), QUtf8::convertFromUnicode(), QTextCursor::deletePreviousChar(), foldCase(), mapToLowerCase(), QFontEngineMulti::stringToCMap(), QString::toLower(), toUcs4_helper(), and QString::toUpper().
{
         return ((ucs & 0xfc00) == 0xd800);
     }
isHighSurrogate() [2/2]
static bool QChar::isHighSurrogate (uint ucs4) inline static
Returns true if the UCS-4-encoded character specified by ucs4 is the high part of a utf16 surrogate (ie.
Since
4.7
if its code point is between 0xd800 and 0xdbff, inclusive).
Definition at line 288 of file qchar.h.
{
         return ((ucs4 & 0xfffffc00) == 0xd800);
     }
isLetter()
bool QChar::isLetter () const
Returns true if the character is a letter (Letter_* categories); otherwise returns false.
Definition at line 653 of file qchar.cpp.
Referenced by QDeclarativeCompiler::checkValidId(), QScriptSyntaxHighlighter::highlightBlock(), QKeyMapperPrivate::isADeadKey(), isDirPath(), QFileSystemEntry::isDriveRoot(), QCharRef::isLetter(), QPatternist::DerivedString< TypeToken >::isNameChar(), isSignalPropertyName(), QLineControl::isValidInput(), QTranslator::load(), QFSFileEnginePrivate::longFileName(), QFileSystemEngine::nativeAbsoluteFilePath(), qt_mac_get_key(), QScriptDebuggerCodeView::setBreakpointEnabled(), QDirPrivate::setPath(), and QGtkStylePrivate::setupGtkFileChooser().
 {
     const int test = FLAG(Letter_Uppercase) |
                      FLAG(Letter_Lowercase) |
                      FLAG(Letter_Titlecase) |
                      FLAG(Letter_Modifier) |
                      FLAG(Letter_Other);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isLetterOrNumber()
bool QChar::isLetterOrNumber () const
Returns true if the character is a letter or number (Letter_* or Number_* categories); otherwise returns false.
Definition at line 681 of file qchar.cpp.
Referenced by QDir::addResourceSearchPath(), QDeclarativeCompiler::checkValidId(), findInBlock(), QDeclarativeJS::Lexer::isIdentLetter(), QCharRef::isLetterOrNumber(), QDateTimeEditPrivate::isSeparatorKey(), QLineControl::isValidInput(), and isWord().
 {
     const int test = FLAG(Letter_Uppercase) |
                      FLAG(Letter_Lowercase) |
                      FLAG(Letter_Titlecase) |
                      FLAG(Letter_Modifier) |
                      FLAG(Letter_Other) |
                      FLAG(Number_DecimalDigit) |
                      FLAG(Number_Letter) |
                      FLAG(Number_Other);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isLower()
bool QChar::isLower () const inline
Returns true if the character is a lowercase letter, i.
e. category() is Letter_Lowercase.
See also
isUpper(), toLower(), toUpper()
Definition at line 272 of file qchar.h.
Referenced by QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFontMetrics::charWidth(), QDeclarativeCompiler::checkValidId(), QCharRef::isLower(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFileSystemModelPrivate::naturalCompare(), qtKey2CocoaKey(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QFontMetrics::width(), and QFontMetricsF::width().
 { return category() == Letter_Lowercase; }
isLowSurrogate() [1/2]
bool QChar::isLowSurrogate () const inline
Returns true if the QChar is the low part of a utf16 surrogate (ie.
if its code point is between 0xdc00 and 0xdfff, inclusive).
Definition at line 279 of file qchar.h.
Referenced by atsuPostLayoutCallback(), QLineControl::backspace(), canonicalOrderHelper(), composeHelper(), containsProhibitedOuptut(), QUtf8::convertFromUnicode(), QTextCursor::deletePreviousChar(), foldCase(), QFontEngineMulti::stringToCMap(), QString::toLower(), toUcs4_helper(), and QString::toUpper().
{
         return ((ucs & 0xfc00) == 0xdc00);
     }
isLowSurrogate() [2/2]
static bool QChar::isLowSurrogate (uint ucs4) inline static
Returns true if the UCS-4-encoded character specified by ucs4 is the low part of a utf16 surrogate (ie.
Since
4.7
if its code point is between 0xdc00 and 0xdfff, inclusive).
Definition at line 291 of file qchar.h.
{
         return ((ucs4 & 0xfffffc00) == 0xdc00);
     }
isMark()
bool QChar::isMark () const
Returns true if the character is a mark (Mark_* categories); otherwise returns false.
See QChar::Category for more information regarding marks.
Definition at line 625 of file qchar.cpp.
Referenced by QCharRef::isMark(), and isWord().
 {
     const int test = FLAG(Mark_NonSpacing) |
                      FLAG(Mark_SpacingCombining) |
                      FLAG(Mark_Enclosing);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isNull()
bool QChar::isNull () const inline
Returns true if the character is the Unicode character 0x0000 ('\0'); otherwise returns false.
Definition at line 262 of file qchar.h.
Referenced by QFontJis0208Codec::convertFromUnicode(), QFontKsc5601Codec::convertFromUnicode(), QKeySequencePrivate::encodeString(), QLineControl::findInMask(), QKeyMapperPrivate::isADeadKey(), QCharRef::isNull(), keySequenceToKeyEqivalent(), QFileSystemModelPrivate::naturalCompare(), QDeclarativeStyledTextPrivate::parse(), QDeclarativeStyledTextPrivate::parseAttribute(), QDeclarativeStyledTextPrivate::parseCloseTag(), QDeclarativeStyledTextPrivate::parseEntity(), QTextHtmlParser::parseEntity(), QDeclarativeStyledTextPrivate::parseFontAttributes(), QDeclarativeStyledTextPrivate::parseTag(), QDeclarativeStyledTextPrivate::parseValue(), qt_splitLocaleName(), QDateTimeParser::sectionFormat(), QDeclarativeStyledTextPrivate::skipSpace(), QPatternist::XQueryTokenizer::tokenizeCharacterReference(), QKeyMapperPrivate::translateKeyEvent(), and QSystemLocalePrivate::zeroDigit().
 { return ucs == 0; }
isNumber()
bool QChar::isNumber () const
Returns true if the character is a number (Number_* categories, not just 0-9); otherwise returns false.
See also
isDigit()
Definition at line 669 of file qchar.cpp.
Referenced by QScriptCompletionTaskPrivate::completeScriptExpression(), QScriptDebuggerCodeView::event(), QCharRef::isNumber(), QDateTimeEditPrivate::isSeparatorKey(), and QLineControl::isValidInput().
 {
     const int test = FLAG(Number_DecimalDigit) |
                      FLAG(Number_Letter) |
                      FLAG(Number_Other);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isPrint()
bool QChar::isPrint () const
Returns true if the character is a printable character; otherwise returns false.
This is any character not of category Cc or Cn.
Note that this gives no indication of whether the character is available in a particular font.
Definition at line 598 of file qchar.cpp.
Referenced by QCharRef::isPrint(), QLineControl::isValidInput(), QTextControlPrivate::keyPressEvent(), QKeySequence::mnemonic(), QLineControl::processKeyEvent(), and QDoubleSpinBoxPrivate::validateAndInterpret().
 {
     const int test = FLAG(Other_Control) |
                      FLAG(Other_NotAssigned);
     return !(FLAG(qGetProp(ucs)->category) & test);
 }
isPunct()
bool QChar::isPunct () const
Returns true if the character is a punctuation mark (Punctuation_* categories); otherwise returns false.
Definition at line 637 of file qchar.cpp.
Referenced by QCharRef::isPunct().
 {
     const int test = FLAG(Punctuation_Connector) |
                      FLAG(Punctuation_Dash) |
                      FLAG(Punctuation_Open) |
                      FLAG(Punctuation_Close) |
                      FLAG(Punctuation_InitialQuote) |
                      FLAG(Punctuation_FinalQuote) |
                      FLAG(Punctuation_Other);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isSpace()
bool QChar::isSpace () const
Returns true if the character is a separator character (Separator_* categories); otherwise returns false.
Definition at line 609 of file qchar.cpp.
Referenced by QTextHtmlImporter::appendNodeText(), QDateTimeParser::findDay(), QSqlDriver::formatValue(), QTextHtmlParserNode::hasOnlyWhitespace(), QCharRef::isSpace(), QPatternist::ProcessingInstructionConstructor::leftTrimmed(), Qt::mightBeRichText(), QFileSystemModelPrivate::naturalCompare(), QTextHtmlParser::newNode(), QPatternist::XQueryTokenizer::nextToken(), operator<<(), QDeclarativeDirParser::parse(), QDeclarativeStyledTextPrivate::parseCloseTag(), parseCombinedArgString(), QTextHtmlParser::parseEntity(), parseFontName(), parseNumbersArray(), parseNumbersList(), parsePathDataFast(), parsePercentageList(), QDateTimeParser::parseSection(), QDeclarativeStyledTextPrivate::parseTag(), parseTransformationMatrix(), QTextHtmlParser::parseWord(), QTextHtmlImporter::processSpecialNodes(), qt_set_x11_resources(), QTextStreamPrivate::scan(), QString::simplified(), QDeclarativeStyledTextPrivate::skipSpace(), QString::trimmed(), QDoubleSpinBoxPrivate::validateAndInterpret(), and QXmlStreamWriterPrivate::writeEscaped().
 {
     if(ucs >= 9 && ucs <=13)
         return true;
     const int test = FLAG(Separator_Space) |
                      FLAG(Separator_Line) |
                      FLAG(Separator_Paragraph);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isSymbol()
bool QChar::isSymbol () const
Returns true if the character is a symbol (Symbol_* categories); otherwise returns false.
Definition at line 709 of file qchar.cpp.
Referenced by qt_mac_get_key().
 {
     const int test = FLAG(Symbol_Math) |
                      FLAG(Symbol_Currency) |
                      FLAG(Symbol_Modifier) |
                      FLAG(Symbol_Other);
     return FLAG(qGetProp(ucs)->category) & test;
 }
isTitleCase()
bool QChar::isTitleCase () const inline
Returns true if the character is a titlecase letter, i.
Since
4.3
e. category() is Letter_Titlecase.
See also
isLower(), toUpper(), toLower(), toTitleCase()
Definition at line 274 of file qchar.h.
Referenced by QCharRef::isTitleCase().
 { return category() == Letter_Titlecase; }
isUpper()
bool QChar::isUpper () const inline
Returns true if the character is an uppercase letter, i.
e. category() is Letter_Uppercase.
See also
isLower(), toUpper(), toLower()
Definition at line 273 of file qchar.h.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::checkDynamicMeta(), QDeclarativeConnectionsParser::compile(), QDeclarativeScriptParser::extractMetaData(), getFmtString(), QScriptSyntaxHighlighter::highlightWord(), QDeclarativePropertyPrivate::initProperty(), QSettingsPrivate::iniUnescapedKey(), isSignalPropertyName(), QCharRef::isUpper(), QDeclarativeBindingCompilerPrivate::parseName(), qDBusGenerateMetaObjectXml(), and qDBusInterfaceFromMetaObject().
 { return category() == Letter_Uppercase; }
joining() [1/3]
QChar::Joining QChar::joining () const
Returns information about the joining properties of the character (needed for certain languages such as Arabic).
Definition at line 924 of file qchar.cpp.
Referenced by QCharRef::joining().
 {
     return (QChar::Joining) qGetProp(ucs)->joining;
 }
joining() [2/3]
QChar::Joining QChar::joining (uint ucs4) static
Returns information about the joining properties of the UCS-4-encoded character specified by ucs4 (needed for certain languages such as Arabic).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 938 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return QChar::OtherJoining;
     return (QChar::Joining) qGetProp(ucs4)->joining;
 }
joining() [3/3]
QChar::Joining QChar::joining (ushort ucs2) static
Returns information about the joining properties of the UCS-2-encoded character specified by ucs2 (needed for certain languages such as Arabic).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 954 of file qchar.cpp.
 {
     return (QChar::Joining) qGetProp(ucs2)->joining;
 }
lowSurrogate()
static ushort QChar::lowSurrogate (uint ucs4) inline static
Returns the low surrogate value of a ucs4 code point.
The returned result is undefined if ucs4 is smaller than 0x10000.
Definition at line 306 of file qchar.h.
Referenced by canonicalOrderHelper(), QUtf8::convertToUnicode(), QUtf32::convertToUnicode(), QKeySequencePrivate::encodeString(), QTextHtmlParser::parseEntity(), qt_string_normalize(), QFontEngineWin::recalcAdvances(), QRawFont::supportsCharacter(), and QPatternist::XQueryTokenizer::tokenizeCharacterReference().
{
         return ushort(ucs4%0x400 + 0xdc00);
     }
mirroredChar() [1/3]
QChar QChar::mirroredChar () const
Returns the mirrored character if this character is a mirrored character; otherwise returns the character itself.
See also
hasMirrored()
Definition at line 1016 of file qchar.cpp.
Referenced by QFontEngineWin::getGlyphIndexes(), HB_GetMirroredChar(), QCharRef::mirroredChar(), QFontEngineDirectWrite::stringToCMap(), QFontEngineXLFD::stringToCMap(), QFontEngineQPA::stringToCMap(), QFontEngineQPF::stringToCMap(), QFontEngineFT::stringToCMap(), and QFontEngineQPF1::stringToCMap().
 {
     return ucs + qGetProp(ucs)->mirrorDiff;
 }
mirroredChar() [2/3]
uint QChar::mirroredChar (uint ucs4) static
Returns the mirrored character if the UCS-4-encoded character specified by ucs4 is a mirrored character; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
hasMirrored()
Definition at line 1031 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return ucs4;
     return ucs4 + qGetProp(ucs4)->mirrorDiff;
 }
mirroredChar() [3/3]
ushort QChar::mirroredChar (ushort ucs2) static
Returns the mirrored character if the UCS-2-encoded character specified by ucs2 is a mirrored character; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
hasMirrored()
Definition at line 1048 of file qchar.cpp.
 {
     return ucs2 + qGetProp(ucs2)->mirrorDiff;
 }
requiresSurrogates()
static bool QChar::requiresSurrogates (uint ucs4) inline static
Returns true if the UCS-4-encoded character specified by ucs4 can be split into the high and low parts of a utf16 surrogate (ie.
Since
4.7
if its code point is greater than or equals to 0x10000).
Definition at line 294 of file qchar.h.
Referenced by canonicalOrderHelper(), decomposeHelper(), QKeySequencePrivate::encodeString(), QTextHtmlParser::parseEntity(), qt_string_normalize(), and QRawFont::supportsCharacter().
{
         return (ucs4 >= 0x10000);
     }
row()
uchar QChar::row () const inline
Returns the row (most significant byte) of the Unicode character.
See also
cell()
Definition at line 284 of file qchar.h.
Referenced by QUtf16::convertFromUnicode(), QGbkCodec::convertFromUnicode(), QFontJis0208Codec::convertFromUnicode(), QEucJpCodec::convertFromUnicode(), QJisCodec::convertFromUnicode(), QSjisCodec::convertFromUnicode(), QGb2312Codec::convertFromUnicode(), QTsciiCodec::convertFromUnicode(), QFontBig5Codec::convertFromUnicode(), QFontBig5hkscsCodec::convertFromUnicode(), QFontKsc5601Codec::convertFromUnicode(), QFontGb18030_0Codec::convertFromUnicode(), QKeyMapperPrivate::isADeadKey(), QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::parseReference(), QCharRef::row(), set_text(), and QPatternist::XQueryTokenizer::tokenizeNumberLiteral().
 { return uchar((ucs>>8)&0xff); }
setCell()
void QChar::setCell (uchar cell) inline
Warning
This function is not part of the public interface.
Definition at line 387 of file qchar.h.
Referenced by QUtf16::convertToUnicode(), and QCharRef::setCell().
 { ucs = ushort((ucs & 0xff00) + acell); }
setRow()
void QChar::setRow (uchar row) inline
Warning
This function is not part of the public interface.
Definition at line 389 of file qchar.h.
Referenced by QUtf16::convertToUnicode(), and QCharRef::setRow().
 { ucs = ushort((ushort(arow)<<8) + (ucs&0xff)); }
surrogateToUcs4() [1/2]
static uint QChar::surrogateToUcs4 (ushort high, ushort low) inline static
Converts a UTF16 surrogate pair with the given high and low values to its UCS-4 code point.
Definition at line 297 of file qchar.h.
Referenced by canonicalOrderHelper(), composeHelper(), containsProhibitedOuptut(), QGb18030Codec::convertFromUnicode(), QUtf8::convertFromUnicode(), QUtf32::convertFromUnicode(), decomposeHelper(), foldCase(), getChar(), mapToLowerCase(), qt_nameprep(), QString::toLower(), toUcs4_helper(), and QString::toUpper().
{
         return (uint(high)<<10) + low - 0x35fdc00;
     }
surrogateToUcs4() [2/2]
static uint QChar::surrogateToUcs4 (QChar high, QChar low) inline static
Converts a utf16 surrogate pair (high, low) to its ucs4 code point.
Definition at line 300 of file qchar.h.
{
         return (uint(high.ucs)<<10) + low.ucs - 0x35fdc00;
     }
toAscii()
char QChar::toAscii () const
Returns the character value of the QChar obtained using the current codec used to read C strings, or 0 if the character is not representable using this codec.
The default codec handles Latin-1 encoded text, but this can be changed to assist developers writing source code using other encodings.
The main purpose of this function is to preserve ASCII characters used in C strings. This is mainly useful for developers of non-internationalized software.
See also
toLatin1(), unicode(), QTextCodec::codecForCStrings()
Definition at line 1490 of file qchar.cpp.
Referenced by QPatternist::XQueryTokenizer::aheadEquals(), Maemo::appendVariantToDBusMessage(), QAbstractConcatenable::convertToAscii(), driveSpec(), fromHex(), QScriptSyntaxHighlighter::highlightBlock(), QPatternist::XQueryTokenizer::peekAhead(), QPatternist::XQueryTokenizer::peekCurrent(), QPatternist::XQueryTokenizer::peekForColonColon(), QCharRef::row(), QCharRef::toAscii(), toCaseFolded(), and QCharRef::unicode().
 {
 #ifndef QT_NO_CODEC_FOR_C_STRINGS
     if (QTextCodec::codecForCStrings())
         // #####
         return QTextCodec::codecForCStrings()->fromUnicode(QString(*this)).at(0);
 #endif
     return ucs > 0xff ? 0 : char(ucs);
 }
toCaseFolded() [1/3]
QChar QChar::toCaseFolded () const
Returns the case folded equivalent of the character.
For most Unicode characters this is the same as toLowerCase().
Definition at line 1406 of file qchar.cpp.
Referenced by QString::replace().
 {
     return ucs + qGetProp(ucs)->caseFoldDiff;
 }
toCaseFolded() [2/3]
uint QChar::toCaseFolded (uint ucs4) static
Returns the case folded equivalent of the UCS-4-encoded character specified by ucs4.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. For most Unicode characters this is the same as toLowerCase().
Definition at line 1419 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return ucs4;
     return ucs4 + qGetProp(ucs4)->caseFoldDiff;
 }
toCaseFolded() [3/3]
ushort QChar::toCaseFolded (ushort ucs2) static
Returns the case folded equivalent of the UCS-2-encoded character specified by ucs2.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. For most Unicode characters this is the same as toLowerCase().
Definition at line 1434 of file qchar.cpp.
 {
     return ucs2 + qGetProp(ucs2)->caseFoldDiff;
 }
toLatin1()
char QChar::toLatin1 () const inline
Returns the Latin-1 character equivalent to the QChar, or 0.
This is mainly useful for non-internationalized software.
See also
toAscii(), unicode(), QTextCodec::codecForCStrings()
Definition at line 376 of file qchar.h.
Referenced by _q_parseUnixDir(), QTextEngine::atWordSeparator(), QLocalePrivate::codeToScript(), QLocalePrivate::digitToCLocale(), QAxBase::dynamicCallHelper(), QRegExp::escape(), QTextStreamPrivate::getReal(), QTest::keyClicks(), QFSFileEnginePrivate::longFileName(), QLocalePrivate::numberToCLocale(), QTextStream::operator>>(), QDateTimeParser::parseFormat(), parsePathDataFast(), QCss::Scanner::preprocess(), QChar(), qt_get_named_rgb(), qt_mac_get_key(), QCharRef::row(), toDouble(), QCharRef::toLatin1(), QKeyMapperPrivate::translateKeyEvent(), and QCharRef::unicode().
 { return ucs > 0xff ? '\0' : char(ucs); }
toLower() [1/3]
QChar QChar::toLower () const
Returns the lowercase equivalent if the character is uppercase or titlecase; otherwise returns the character itself.
Definition at line 1239 of file qchar.cpp.
Referenced by QFontPrivate::alterCharForCapitalization(), QLocalePrivate::codeToScript(), comify(), QDateTimeParser::findAmPm(), QRegExpEngine::getEscape(), QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), hasValidSignal(), QDeclarativePropertyPrivate::initProperty(), QKeyMapperPrivate::isADeadKey(), keySequenceToKeyEqivalent(), QRegExpMatchState::matchHere(), QFileSystemModelPrivate::naturalCompare(), QLocalePrivate::numberToCLocale(), QTextHtmlParser::parseEntity(), QOpenKODEWindow::processKeyEvents(), QDeclarative_isFileCaseCorrect(), QByteArray::qstricmp(), QByteArray::qstrnicmp(), QGtkStylePrivate::setupGtkFileChooser(), QTextEngine::shapeTextMac(), QTextEngine::shapeTextWithCE(), QTextEngine::shapeTextWithHarfbuzz(), timeFormatContainsAP(), QByteArray::toLower(), QCharRef::toLower(), QCharRef::unicode(), and QDateTimeEditPrivate::validateAndInterpret().
 {
     const QUnicodeTables::Properties *p = qGetProp(ucs);
     if (!p->lowerCaseSpecial)
         return ucs + p->lowerCaseDiff;
     return ucs;
 }
toLower() [2/3]
uint QChar::toLower (uint ucs4) static
Returns the lowercase equivalent of the UCS-4-encoded character specified by ucs4 if the character is uppercase or titlecase; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1256 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return ucs4;
     const QUnicodeTables::Properties *p = qGetProp(ucs4);
     if (!p->lowerCaseSpecial)
         return ucs4 + p->lowerCaseDiff;
     return ucs4;
 }
toLower() [3/3]
ushort QChar::toLower (ushort ucs2) static
Returns the lowercase equivalent of the UCS-2-encoded character specified by ucs2 if the character is uppercase or titlecase; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1275 of file qchar.cpp.
 {
     const QUnicodeTables::Properties *p = qGetProp(ucs2);
     if (!p->lowerCaseSpecial)
         return ucs2 + p->lowerCaseDiff;
     return ucs2;
 }
toTitleCase() [1/3]
QChar QChar::toTitleCase () const
Returns the title case equivalent if the character is lowercase or uppercase; otherwise returns the character itself.
Definition at line 1335 of file qchar.cpp.
Referenced by QCharRef::toTitleCase().
 {
     const QUnicodeTables::Properties *p = qGetProp(ucs);
     if (!p->titleCaseSpecial)
         return ucs + p->titleCaseDiff;
     return ucs;
 }
toTitleCase() [2/3]
uint QChar::toTitleCase (uint ucs4) static
Returns the title case equivalent of the UCS-4-encoded character specified by ucs4 if the character is lowercase or uppercase; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1352 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return ucs4;
     const QUnicodeTables::Properties *p = qGetProp(ucs4);
     if (!p->titleCaseSpecial)
         return ucs4 + p->titleCaseDiff;
     return ucs4;
 }
toTitleCase() [3/3]
ushort QChar::toTitleCase (ushort ucs2) static
Returns the title case equivalent of the UCS-2-encoded character specified by ucs2 if the character is lowercase or uppercase; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1371 of file qchar.cpp.
 {
     const QUnicodeTables::Properties *p = qGetProp(ucs2);
     if (!p->titleCaseSpecial)
         return ucs2 + p->titleCaseDiff;
     return ucs2;
 }
toUpper() [1/3]
QChar QChar::toUpper () const
Returns the uppercase equivalent if the character is lowercase or titlecase; otherwise returns the character itself.
Definition at line 1287 of file qchar.cpp.
Referenced by QFontPrivate::alterCharForCapitalization(), QCoreApplication::applicationDirPath(), QLocalePrivate::codeToScript(), QKeySequencePrivate::encodeString(), QDateTimeParser::findAmPm(), getFmtString(), hasUnquotedAP(), isDirPath(), QMenu::keyPressEvent(), QFSFileEnginePrivate::longFileName(), QKeySequence::mnemonic(), QDeclarativeProperty::name(), QFileSystemEngine::nativeAbsoluteFilePath(), QFileSystemModelPrivate::node(), parseFontName(), qt_mac_get_key(), qtKey2CocoaKey(), QGtkStylePrivate::setupGtkFileChooser(), QTextEngine::shapeTextMac(), QTextEngine::shapeTextWithCE(), QTextEngine::shapeTextWithHarfbuzz(), toKeyOrUnicode(), QByteArray::toUpper(), QCharRef::toUpper(), QXlibKeyboard::translateKeySym(), QXcbKeyboard::translateKeySym(), translateKeySym(), tryDriveUNCFallback(), and QCharRef::unicode().
 {
     const QUnicodeTables::Properties *p = qGetProp(ucs);
     if (!p->upperCaseSpecial)
         return ucs + p->upperCaseDiff;
     return ucs;
 }
toUpper() [2/3]
uint QChar::toUpper (uint ucs4) static
Returns the uppercase equivalent of the UCS-4-encoded character specified by ucs4 if the character is lowercase or titlecase; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1304 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return ucs4;
     const QUnicodeTables::Properties *p = qGetProp(ucs4);
     if (!p->upperCaseSpecial)
         return ucs4 + p->upperCaseDiff;
     return ucs4;
 }
toUpper() [3/3]
ushort QChar::toUpper (ushort ucs2) static
Returns the uppercase equivalent of the UCS-2-encoded character specified by ucs2 if the character is lowercase or titlecase; otherwise returns the character itself.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1323 of file qchar.cpp.
 {
     const QUnicodeTables::Properties *p = qGetProp(ucs2);
     if (!p->upperCaseSpecial)
         return ucs2 + p->upperCaseDiff;
     return ucs2;
 }
unicode() [1/2]
ushort QChar::unicode () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 251 of file qchar.h.
Referenced by QString::append(), QXmlSimpleReaderPrivate::atEnd(), QPatternist::XQueryTokenizer::attributeAsRaw(), canonicalOrderHelper(), QFontEngineWin::canRender(), QFontEngineQPF1::canRender(), QFontMetrics::charWidth(), comify(), composeHelper(), QFontJis0201Codec::convertFromUnicode(), QGb18030Codec::convertFromUnicode(), QBig5Codec::convertFromUnicode(), QFontLaoCodec::convertFromUnicode(), QUtf8::convertFromUnicode(), QIsciiCodec::convertFromUnicode(), QSimpleTextCodec::convertFromUnicode(), QIconvCodec::convertFromUnicode(), QBig5hkscsCodec::convertFromUnicode(), QUtf32::convertFromUnicode(), QGbkCodec::convertFromUnicode(), QLatin15Codec::convertFromUnicode(), QFontJis0208Codec::convertFromUnicode(), QEucKrCodec::convertFromUnicode(), QEucJpCodec::convertFromUnicode(), QGb2312Codec::convertFromUnicode(), QFontBig5Codec::convertFromUnicode(), QCP949Codec::convertFromUnicode(), QFontGb2312Codec::convertFromUnicode(), QFontBig5hkscsCodec::convertFromUnicode(), QFontKsc5601Codec::convertFromUnicode(), QFontGbkCodec::convertFromUnicode(), QAbstractConcatenable::convertToAscii(), QAbstractConcatenable::convertToLatin1(), QUtf16::convertToUnicode(), QLatin15Codec::convertToUnicode(), QRegExpEngine::createState(), QLocalePrivate::dateTimeToString(), QPatternist::CompressedWhitespace::decompress(), QLocalePrivate::digitToCLocale(), QLocalePrivate::doubleToString(), QWin32PrintEngine::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), QString::endsWith(), QStringRef::endsWith(), equal(), QPatternist::escape(), escapedKey(), escapedString(), extractEncodingDecl(), fastDetermineNameChar(), findArgEscapes(), findChar(), findGraphicsFactory(), findGroupFactory(), findStyleFactoryMethod(), findStyleUtilFactoryMethod(), findUtilFactory(), fixedXmlName(), fromAscii(), QPatternist::HexBinary::fromHex(), QXmlStreamReaderPrivate::getChar(), QRegExpEngine::getChar(), getChar(), QXmlStreamReaderPrivate::getChar_helper(), QRegExpEngine::getEscape(), getEscape(), getMessage(), QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), heuristicSetGlyphAttributes(), QRegExpCharClass::in(), QSettingsPrivate::iniEscapedKey(), QSettingsPrivate::iniEscapedString(), QString::insert(), is_S(), QXmlUtils::isChar(), QXmlUtils::isNameChar(), QPatternist::XQueryTokenizer::isNCNameBody(), QXmlUtils::isPublicID(), isSupportedSvgFeature(), isValidCharacter(), isValidCharacterNoDash(), QLineControl::isValidInput(), isValidNumber(), QTextEngine::itemize(), QMenu::keyPressEvent(), keySequenceToKeyEqivalent(), QCssScanner_Generated::lex(), QUnicodeTables::lineBreakClass(), macToQtFormat(), mapToLowerCase(), QRegExpMatchState::match(), QKeySequence::mnemonic(), QScriptEnginePrivate::newRegExp(), QPatternist::ToCodepointsIterator::next(), QXmlInputSource::next(), QXmlSimpleReaderPrivate::next(), nextDotDelimiter(), QPatternist::XQueryTokenizer::nextToken(), QPatternist::XQueryTokenizer::normalizeEOL(), QLocalePrivate::numberToCLocale(), operator!=(), QString::operator+=(), operator<(), operator<<(), operator<<(), operator<=(), QCharRef::operator=(), operator==(), operator>(), operator>=(), operator>>(), QXmlStreamReaderPrivate::parse(), parse_locale_tag(), parseCoreNode(), parseFont(), QLineControl::parseInputMask(), parseNumbersArray(), parseNumbersList(), parsePathDataFast(), QXmlStreamReaderPrivate::peekChar(), QKeyMapper::possibleKeys(), QXmlStreamReaderPrivate::putChar(), QXmlStreamReaderPrivate::putReplacement(), QXmlStreamReaderPrivate::putReplacementInAttributeValue(), QXmlStreamReaderPrivate::putString(), QXmlStreamReaderPrivate::putStringLiteral(), QChar(), qHash(), qIsAlnum(), QString::QString(), QSvgAttributes::QSvgAttributes(), qt_ACE_do(), qt_check_std3rules(), qt_keyrelease_scanner(), qt_last_index_of(), qt_mac_get_key(), qt_nameprep(), qt_readEscapedFormatString(), qt_string_count(), qt_string_normalize(), qtKey2CocoaKey(), qtkeyForMacSymbol(), qulltoa(), QXmlUtils::rangeContains(), QString::remove(), QString::replace(), replaceArgEscapes(), resolveColor(), QCharRef::row(), QUnicodeTables::script(), QUrlPrivate::setAuthority(), QDirPrivate::setPath(), QTextEngine::shapeTextMac(), QTextEngine::shapeTextWithCE(), QString::startsWith(), QStringRef::startsWith(), stringContainsNullChar(), QFontEngineXLFD::stringToCMap(), QSystemLocalePrivate::substituteDigits(), QTextBlock::textDirection(), timeFormatContainsAP(), toDouble(), QPatternist::CompressedWhitespace::toIdentifier(), toKeyOrUnicode(), QTextDocument::toPlainText(), toPunycodeHelper(), QTest::toString(), QFontEngineXLFD::toUnicode(), QXlibKeyboard::translateKeySym(), QXcbKeyboard::translateKeySym(), translateKeySym(), tryDriveUNCFallback(), ucstrncmp(), QCharRef::unicode(), QLineControl::updateDisplayText(), QKeyMapperPrivate::updateKeyMap(), QLocalePrivate::updateSystemPrivate(), wc2rx(), QFontMetrics::width(), QFontMetricsF::width(), QSystemLocalePrivate::winToQtFormat(), QTextOdfWriter::writeBlock(), QXmlStreamWriterPrivate::writeEscaped(), and xpmHash().
 { return ucs; }
unicode() [2/2]
ushort & QChar::unicode () inline
Returns a reference to the numeric Unicode value of the QChar.
Definition at line 256 of file qchar.h.
 { return ucs; }
unicodeVersion() [1/3]
QChar::UnicodeVersion QChar::unicodeVersion () const
Returns the Unicode version that introduced this character.
Definition at line 1189 of file qchar.cpp.
Referenced by decomposeHelper(), qt_nameprep(), and QCharRef::unicodeVersion().
 {
     return (QChar::UnicodeVersion) qGetProp(ucs)->unicodeVersion;
 }
unicodeVersion() [2/3]
QChar::UnicodeVersion QChar::unicodeVersion (uint ucs4) static
Returns the Unicode version that introduced the character specified in its UCS-4-encoded form as ucs4.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1202 of file qchar.cpp.
 {
     if (ucs4 > UNICODE_LAST_CODEPOINT)
         return QChar::Unicode_Unassigned;
     return (QChar::UnicodeVersion) qGetProp(ucs4)->unicodeVersion;
 }
unicodeVersion() [3/3]
QChar::UnicodeVersion QChar::unicodeVersion (ushort ucs2) static
Returns the Unicode version that introduced the character specified in its UCS-2-encoded form as ucs2.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1217 of file qchar.cpp.
 {
     return (QChar::UnicodeVersion) qGetProp(ucs2)->unicodeVersion;
 }
Friends and Related Functions
operator!=()
int operator!= (QChar c1, QChar c2) related
Returns true if c1 and c2 are not the same Unicode character; otherwise returns false.
Definition at line 393 of file qchar.h.
 { return c1.unicode() != c2.unicode(); }
operator<()
int operator< (QChar c1, QChar c2) related
Returns true if the numeric Unicode value of c1 is less than that of c2; otherwise returns false.
Definition at line 396 of file qchar.h.
 { return c1.unicode() < c2.unicode(); }
operator<<()
QDataStream & operator<< (QDataStream & out, const QChar & chr) related
Writes the char chr to the stream out.
See also
{Serializing Qt Data Types}
Definition at line 1542 of file qchar.cpp.
Referenced by operator>().
 {
     out << quint16(chr.unicode());
     return out;
 }
operator<=()
int operator<= (QChar c1, QChar c2) related
Returns true if the numeric Unicode value of c1 is less than or equal to that of c2; otherwise returns false.
Definition at line 394 of file qchar.h.
 { return c1.unicode() <= c2.unicode(); }
operator==()
bool operator== (QChar c1, QChar c2) related
Returns true if c1 and c2 are the same Unicode character; otherwise returns false.
Definition at line 392 of file qchar.h.
 { return c1.unicode() == c2.unicode(); }
operator>()
int operator> (QChar c1, QChar c2) related
Returns true if the numeric Unicode value of c1 is greater than that of c2; otherwise returns false.
Definition at line 397 of file qchar.h.
 { return c1.unicode() > c2.unicode(); }
operator>=()
int operator>= (QChar c1, QChar c2) related
Returns true if the numeric Unicode value of c1 is greater than or equal to that of c2; otherwise returns false.
Definition at line 395 of file qchar.h.
 { return c1.unicode() >= c2.unicode(); }
operator>>()
QDataStream & operator>> (QDataStream & in, QChar & chr) related
Reads a char from the stream in into char chr.
See also
{Serializing Qt Data Types}
Definition at line 1558 of file qchar.cpp.
Referenced by operator>().
 {
     quint16 u;
     in >> u;
     chr.unicode() = ushort(u);
     return in;
 }
Properties
ucs
ushort QChar::ucs private
Definition at line 362 of file qchar.h.
Referenced by category(), combiningClass(), decomposition(), decompositionTag(), digitValue(), direction(), hasMirrored(), isDigit(), isLetter(), isLetterOrNumber(), isMark(), isNumber(), isPrint(), isPunct(), isSpace(), isSymbol(), joining(), mirroredChar(), QChar(), setCell(), setRow(), surrogateToUcs4(), toAscii(), toCaseFolded(), toLatin1(), toLower(), toTitleCase(), toUpper(), and unicodeVersion().
The documentation for this class was generated from the following files:
/src/corelib/tools/qchar.h
/src/corelib/tools/qchar.cpp