Qt 4.8: QPatternist::CardinalityVerifier Class Reference
QPatternist::CardinalityVerifier Class Reference
Verifies that the sequence an Expression evaluates to conforms to a Cardinality.
#include <qcardinalityverifier_p.h>
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual const SourceLocationReflection * actualReflection () const
Returns this.
CardinalityVerifier (const Expression::Ptr &operand, const Cardinality &card, const ReportContext::ErrorCode code)
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual Item evaluateSingleton (const DynamicContext::Ptr &) const
virtual SequenceType::List expectedOperandTypes () const
ID id () const
virtual SequenceType::Ptr staticType () const
Public Functions inherited from QPatternist::SingleContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &operands)
Public Functions inherited from QPatternist::Expression
virtual void announceFocusType (const ItemType::Ptr &itemType)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
virtual Properties properties () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Static Public Functions
static Expression::Ptr verifyCardinality (const Expression::Ptr &operand, const Cardinality &card, const StaticContext::Ptr &context, const ReportContext::ErrorCode code=ReportContext::XPTY0004)
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Static Private Functions
static QString wrongCardinality (const Cardinality &req, const Cardinality &got=Cardinality::empty())
Properties
const bool m_allowsMany
const ReportContext::ErrorCode m_errorCode
const Cardinality m_reqCard
Additional Inherited Members
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::SingleContainer
SingleContainer (const Expression::Ptr &operand)
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Protected Variables inherited from QPatternist::SingleContainer
Expression::Ptr m_operand
Detailed Description
Verifies that the sequence an Expression evaluates to conforms to a Cardinality.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.2 Functions That Test the Cardinality of Sequences
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 72 of file qcardinalityverifier_p.h.
Constructors and Destructors
CardinalityVerifier()
CardinalityVerifier::CardinalityVerifier (const Expression::Ptr & operand, const Cardinality & card, const ReportContext::ErrorCode code)
Definition at line 86 of file qcardinalityverifier.cpp.
Referenced by verifyCardinality().
                                          : SingleContainer(operand),
                                            m_reqCard(card),
                                            m_allowsMany(operand->staticType()->cardinality().allowsMany()),
                                            m_errorCode(code)
 {
     Q_ASSERT_X(m_reqCard != Cardinality::zeroOrMore(), Q_FUNC_INFO,
                "It makes no sense to use CardinalityVerifier for cardinality zero-or-more.");
 }
Functions
accept()
ExpressionVisitorResult::Ptr CardinalityVerifier::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Definition at line 214 of file qcardinalityverifier.cpp.
 {
     return visitor->visit(this);
 }
actualReflection()
const SourceLocationReflection * CardinalityVerifier::actualReflection () const virtual
Returns this.
Reimplemented from QPatternist::Expression.
Definition at line 189 of file qcardinalityverifier.cpp.
 {
     return m_operand->actualReflection();
 }
compress()
Expression::Ptr CardinalityVerifier::compress (const StaticContext::Ptr & context) virtual
If the static cardinality of the operand is within the required cardinality, the operand is returned as is, since results will always be valid and hence is not a CardinalityVerifier necessary.
Reimplemented from QPatternist::Expression.
Definition at line 194 of file qcardinalityverifier.cpp.
 {
     if(m_reqCard.isMatch(m_operand->staticType()->cardinality()))
         return m_operand->compress(context);
     else
         return SingleContainer::compress(context);
 }
evaluateSequence()
Item::Iterator::Ptr CardinalityVerifier::evaluateSequence (const DynamicContext::Ptr & context) const virtual
Evaluate this Expression by iterating over it. This is a central function for evaluating expressions.
Expressions must always always return a valid QAbstractXmlForwardIterator and may never return 0. If an empty result is of interest to be returned, the EmptyIterator should be returned.
The default implementation returns a SingletonIterator over the item returned from evaluateSingleton().
Note
This function may raise an exception when calling, not only when QAbstractXmlForwardIterator::next() is called on the return value. This is because in some cases evaluateSingleton() is called directly.
Reimplemented from QPatternist::Expression.
Definition at line 98 of file qcardinalityverifier.cpp.
 {
     const Item::Iterator::Ptr it(m_operand->evaluateSequence(context));
     const Item next(it->next());
     if(next)
     {
         const Item next2(it->next());
         if(next2)
         {
             if(m_reqCard.allowsMany())
             {
                 Item::List start;
                 start.append(next);
                 start.append(next2);
                 return Item::Iterator::Ptr(new InsertionIterator(it, 1, makeListIterator(start)));
             }
             else
             {
                 context->error(wrongCardinality(m_reqCard, Cardinality::twoOrMore()), m_errorCode, this);
                 return CommonValues::emptyIterator;
             }
         }
         else
         {
             /* We might be instantiated for the empty sequence. */
             if(m_reqCard.isEmpty())
             {
                 context->error(wrongCardinality(m_reqCard, Cardinality::twoOrMore()), m_errorCode, this);
                 return CommonValues::emptyIterator;
             }
             else
                 return makeSingletonIterator(next);
         }
     }
     else
     {
         if(m_reqCard.allowsEmpty())
             return CommonValues::emptyIterator;
         else
         {
             context->error(wrongCardinality(m_reqCard, Cardinality::twoOrMore()), m_errorCode, this);
             return CommonValues::emptyIterator;
         }
     }
 }
evaluateSingleton()
Item CardinalityVerifier::evaluateSingleton (const DynamicContext::Ptr & context) const virtual
Reimplemented from QPatternist::Expression.
Definition at line 147 of file qcardinalityverifier.cpp.
 {
     if(m_allowsMany)
     {
         const Item::Iterator::Ptr it(m_operand->evaluateSequence(context));
         const Item item(it->next());
         if(item)
         {
             if(it->next())
             {
                 context->error(wrongCardinality(m_reqCard, Cardinality::twoOrMore()),
                                m_errorCode, this);
                 return Item();
             }
             else
                 return item;
         }
         else if(m_reqCard.allowsEmpty())
             return Item();
         else
         {
             context->error(wrongCardinality(m_reqCard), m_errorCode, this);
             return Item();
         }
     }
     else
     {
         const Item item(m_operand->evaluateSingleton(context));
         if(item)
             return item;
         else if(m_reqCard.allowsEmpty())
             return Item();
         else
         {
             context->error(wrongCardinality(m_reqCard), m_errorCode, this);
             return Item();
         }
     }
 }
expectedOperandTypes()
SequenceType::List CardinalityVerifier::expectedOperandTypes () const virtual
Returns a list of Sequence Types, describing the type of each of the expression's operands. Hence, this function has a relationship to the operands() function:
- The lengths of the lists returned by expectedOperandTypes()
and operands() should always be equal in length, since one
cannot describe the type of a non-existent operand(and all
operands must have type information).
- A significant difference between the two functions is that while
the type of objects in the list returned by operands() may vary
between compilations/static context, simply because the particular
Expression is part of different XPath expressions, the
types in the list returned by expectedOperandTypes is always the same
since the function/operator signature never changes.
This function should not be confused with staticType(), which returns the static type of the expression itself, not its operands. The function call is an expression where this is clear: the type of the return value is not the same as the arguments' types. The static type of the operands supplied to the expression can be determined via the staticType() function of the instances returned by operands().
If the expression has no operands, an empty list should be returned.
Implements QPatternist::Expression.
Definition at line 202 of file qcardinalityverifier.cpp.
 {
     SequenceType::List result;
     result.append(CommonSequenceTypes::ZeroOrMoreItems);
     return result;
 }
id()
Expression::ID CardinalityVerifier::id () const virtual
This property, which has no setter, returns an enum value that uniquely identifies this Expression. Patternist makes no use of C++'s dynamic_cast feature, but uses this polymorphic function instead.
Returns
always IgnorableExpression.
Reimplemented from QPatternist::Expression.
Definition at line 219 of file qcardinalityverifier.cpp.
 {
     return IDCardinalityVerifier;
 }
staticType()
SequenceType::Ptr CardinalityVerifier::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Definition at line 209 of file qcardinalityverifier.cpp.
 {
     return makeGenericSequenceType(m_operand->staticType()->itemType(), m_reqCard);
 }
verifyCardinality()
Expression::Ptr CardinalityVerifier::verifyCardinality (const Expression::Ptr & operand, const Cardinality & card, const StaticContext::Ptr & context, const ReportContext::ErrorCode code = ReportContext::XPTY0004) static
A utility function for determining whether the static type of an Expression matches a cardinality. More specifically, this function performs the cardinality verification part of the Function Conversion Rules.
Definition at line 62 of file qcardinalityverifier.cpp.
Referenced by QPatternist::TypeChecker::applyFunctionConversion(), and QPatternist::ExpressionSequence::typeCheck().
 {
     const Cardinality opCard(operand->staticType()->cardinality());
     if(requiredCard.isMatch(opCard))
         return operand;
     else if(requiredCard.canMatch(opCard))
         return Expression::Ptr(new CardinalityVerifier(operand, requiredCard, code));
     else if(context->compatModeEnabled() &&
             !opCard.isEmpty())
     {
         return GenericPredicate::createFirstItem(operand);
     }
     else
     {
         /* Sequences within this cardinality can never match. */
         context->error(wrongCardinality(requiredCard, opCard), code, operand.data());
         return operand;
     }
 }
wrongCardinality()
QString CardinalityVerifier::wrongCardinality (const Cardinality & req, const Cardinality & got = Cardinality::empty()) inline static private
Centralizes a message string in order to increase consistency and reduce work for translators.
Definition at line 55 of file qcardinalityverifier.cpp.
Referenced by evaluateSequence(), evaluateSingleton(), and verifyCardinality().
 {
     return QtXmlPatterns::tr("Required cardinality is %1; got cardinality %2.")
                 .arg(formatType(req), formatType(got));
 }
Properties
m_allowsMany
const bool QPatternist::CardinalityVerifier::m_allowsMany private
Definition at line 119 of file qcardinalityverifier_p.h.
Referenced by evaluateSingleton().
m_errorCode
const ReportContext::ErrorCode QPatternist::CardinalityVerifier::m_errorCode private
Definition at line 120 of file qcardinalityverifier_p.h.
Referenced by evaluateSequence(), and evaluateSingleton().
m_reqCard
const Cardinality QPatternist::CardinalityVerifier::m_reqCard private
Definition at line 118 of file qcardinalityverifier_p.h.
Referenced by CardinalityVerifier(), compress(), evaluateSequence(), evaluateSingleton(), and staticType().
The documentation for this class was generated from the following files:
/src/xmlpatterns/janitors/qcardinalityverifier_p.h
/src/xmlpatterns/janitors/qcardinalityverifier.cpp