Qt 4.8: QCommonListViewBase Class Reference
QCommonListViewBase Class Reference abstract
#include <qlistview_p.h>
Public Functions
virtual void appendHiddenRow (int row)
QSize cachedItemSize () const
virtual void clear ()=0
QRect clipRect () const
int column () const
virtual void dataChanged (const QModelIndex &, const QModelIndex &)=0
QAbstractItemDelegate * delegate (const QModelIndex &idx) const
virtual bool doBatchedItemLayout (const QListViewLayoutInfo &info, int max)=0
virtual bool filterDragLeaveEvent (QDragLeaveEvent *)
virtual bool filterDragMoveEvent (QDragMoveEvent *)
virtual bool filterDropEvent (QDropEvent *)
virtual bool filterStartDrag (Qt::DropActions)
QListView::Flow flow () const
QSize gridSize () const
int hiddenCount () const
virtual int horizontalOffset () const
QScrollBar * horizontalScrollBar () const
QListView::ScrollMode horizontalScrollMode () const
virtual int horizontalScrollToValue (int index, QListView::ScrollHint hint, bool leftOf, bool rightOf, const QRect &area, const QRect &rect) const
virtual QListViewItem indexToListViewItem (const QModelIndex &index) const =0
virtual QVector< QModelIndex > intersectingSet (const QRect &area) const =0
bool isHidden (int row) const
bool isRightToLeft () const
bool isWrapping () const
virtual int itemIndex (const QListViewItem &item) const =0
QSize itemSize (const QStyleOptionViewItemV2 &opt, const QModelIndex &idx) const
virtual QRect mapToViewport (const QRect &rect) const
QModelIndex modelIndex (int row) const
QListView::Movement movement () const
QPoint offset () const
void paintDragDrop (QPainter *painter)
QPoint pressedPosition () const
QCommonListViewBase (QListView *q, QListViewPrivate *d)
virtual void removeHiddenRow (int row)
int rowCount () const
virtual void scrollContentsBy (int dx, int dy, bool scrollElasticBand)
virtual void setPositionForIndex (const QPoint &, const QModelIndex &)
virtual void setRowCount (int)=0
int spacing () const
bool uniformItemSizes () const
virtual void updateHorizontalScrollBar (const QSize &step)
virtual void updateVerticalScrollBar (const QSize &step)
virtual int verticalOffset () const
QScrollBar * verticalScrollBar () const
QListView::ScrollMode verticalScrollMode () const
virtual int verticalScrollToValue (int index, QListView::ScrollHint hint, bool above, bool below, const QRect &area, const QRect &rect) const
QRect viewItemRect (const QListViewItem &item) const
QStyleOptionViewItemV4 viewOptions () const
QWidget * viewport () const
virtual ~QCommonListViewBase ()
Public Variables
int batchSavedDeltaSeg
int batchStartRow
QSize contentsSize
QListViewPrivate * dd
QListView * qq
Detailed Description
Definition at line 120 of file qlistview_p.h.
Constructors and Destructors
QCommonListViewBase()
QCommonListViewBase::QCommonListViewBase (QListView * q, QListViewPrivate * d) inline
Definition at line 123 of file qlistview_p.h.
 : dd(d), qq(q), batchStartRow(0), batchSavedDeltaSeg(0) {}
~QCommonListViewBase()
virtual QCommonListViewBase::~QCommonListViewBase () inline virtual
Definition at line 124 of file qlistview_p.h.
 {}
Functions
appendHiddenRow()
void QCommonListViewBase::appendHiddenRow (int row) virtual
Reimplemented in QIconModeViewBase.
Definition at line 1913 of file qlistview.cpp.
Referenced by QIconModeViewBase::appendHiddenRow().
 {
     dd->hiddenRows.insert(dd->model->index(row, 0, qq->rootIndex()));
 }
cachedItemSize()
QSize QCommonListViewBase::cachedItemSize () const inline
Definition at line 472 of file qlistview_p.h.
 { return dd->cachedItemSize; }
clear()
virtual void QCommonListViewBase::clear () pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
Referenced by QListViewPrivate::clear().
clipRect()
QRect QCommonListViewBase::clipRect () const inline
Definition at line 470 of file qlistview_p.h.
 { return dd->clipRect(); }
column()
int QCommonListViewBase::column () const inline
Definition at line 457 of file qlistview_p.h.
 { return dd->column; }
dataChanged()
virtual void QCommonListViewBase::dataChanged (const QModelIndex & , const QModelIndex &) pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
delegate()
QAbstractItemDelegate * QCommonListViewBase::delegate (const QModelIndex & idx) const inline
Definition at line 477 of file qlistview_p.h.
     { return dd->delegateForIndex(idx); }
doBatchedItemLayout()
virtual bool QCommonListViewBase::doBatchedItemLayout (const QListViewLayoutInfo & info, int max) pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
Referenced by QListViewPrivate::doItemsLayout().
filterDragLeaveEvent()
virtual bool QCommonListViewBase::filterDragLeaveEvent (QDragLeaveEvent *) inline virtual
Reimplemented in QIconModeViewBase.
Definition at line 152 of file qlistview_p.h.
Referenced by QIconModeViewBase::filterDragLeaveEvent().
 { return false; }
filterDragMoveEvent()
virtual bool QCommonListViewBase::filterDragMoveEvent (QDragMoveEvent *) inline virtual
Reimplemented in QIconModeViewBase.
Definition at line 151 of file qlistview_p.h.
 { return false; }
filterDropEvent()
virtual bool QCommonListViewBase::filterDropEvent (QDropEvent *) inline virtual
Reimplemented in QIconModeViewBase.
Definition at line 153 of file qlistview_p.h.
 { return false; }
filterStartDrag()
virtual bool QCommonListViewBase::filterStartDrag (Qt::DropActions) inline virtual
Reimplemented in QIconModeViewBase.
Definition at line 154 of file qlistview_p.h.
 { return false; }
flow()
QListView::Flow QCommonListViewBase::flow () const inline
Definition at line 451 of file qlistview_p.h.
 { return dd->flow; }
gridSize()
QSize QCommonListViewBase::gridSize () const inline
Definition at line 450 of file qlistview_p.h.
 { return dd->gridSize(); }
hiddenCount()
int QCommonListViewBase::hiddenCount () const inline
Definition at line 481 of file qlistview_p.h.
 { return dd->hiddenRows.count(); }
horizontalOffset()
int QCommonListViewBase::horizontalOffset () const virtual
Reimplemented in QListModeViewBase.
Definition at line 1965 of file qlistview.cpp.
Referenced by QListModeViewBase::horizontalOffset().
 {
     return (isRightToLeft() ? horizontalScrollBar()->maximum() - horizontalScrollBar()->value() : horizontalScrollBar()->value());
 }
horizontalScrollBar()
QScrollBar * QCommonListViewBase::horizontalScrollBar () const inline
Definition at line 460 of file qlistview_p.h.
 { return qq->horizontalScrollBar(); }
horizontalScrollMode()
QListView::ScrollMode QCommonListViewBase::horizontalScrollMode () const inline
Definition at line 462 of file qlistview_p.h.
 { return qq->horizontalScrollMode(); }
horizontalScrollToValue()
int QCommonListViewBase::horizontalScrollToValue (int index, QListView::ScrollHint hint, bool leftOf, bool rightOf, const QRect & area, const QRect & rect) const virtual
Reimplemented in QListModeViewBase.
Definition at line 1970 of file qlistview.cpp.
Referenced by QListModeViewBase::horizontalScrollToValue().
 {
     int horizontalValue = horizontalScrollBar()->value();
     if (isRightToLeft()) {
         if (hint == QListView::PositionAtCenter) {
             horizontalValue += ((area.width() - rect.width()) / 2) - rect.left();
         } else {
             if (leftOf)
                 horizontalValue -= rect.left();
             else if (rightOf)
                 horizontalValue += qMin(rect.left(), area.width() - rect.right());
         }
     } else {
         if (hint == QListView::PositionAtCenter) {
             horizontalValue += rect.left() - ((area.width()- rect.width()) / 2);
         } else {
             if (leftOf)
                 horizontalValue += rect.left();
             else if (rightOf)
                 horizontalValue += qMin(rect.left(), rect.right() - area.width());
         }
     }
     return horizontalValue;
 }
indexToListViewItem()
virtual QListViewItem QCommonListViewBase::indexToListViewItem (const QModelIndex & index) const pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
Referenced by QListViewPrivate::indexToListViewItem().
intersectingSet()
virtual QVector<QModelIndex> QCommonListViewBase::intersectingSet (const QRect & area) const pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
isHidden()
bool QCommonListViewBase::isHidden (int row) const inline
Definition at line 480 of file qlistview_p.h.
 { return dd->isHidden(row); }
isRightToLeft()
bool QCommonListViewBase::isRightToLeft () const inline
Definition at line 483 of file qlistview_p.h.
 { return qq->isRightToLeft(); }
isWrapping()
bool QCommonListViewBase::isWrapping () const inline
Definition at line 449 of file qlistview_p.h.
 { return dd->isWrapping(); }
itemIndex()
virtual int QCommonListViewBase::itemIndex (const QListViewItem & item) const pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
itemSize()
QSize QCommonListViewBase::itemSize (const QStyleOptionViewItemV2 & opt, const QModelIndex & idx) const inline
Definition at line 474 of file qlistview_p.h.
     { return dd->itemSize(opt, idx); }
mapToViewport()
virtual QRect QCommonListViewBase::mapToViewport (const QRect & rect) const inline virtual
Reimplemented in QListModeViewBase.
Definition at line 140 of file qlistview_p.h.
Referenced by QListViewPrivate::mapToViewport().
 {return rect;}
modelIndex()
QModelIndex QCommonListViewBase::modelIndex (int row) const inline
Definition at line 464 of file qlistview_p.h.
     { return dd->model->index(row, dd->column, dd->root); }
movement()
QListView::Movement QCommonListViewBase::movement () const inline
Definition at line 452 of file qlistview_p.h.
 { return dd->movement; }
offset()
QPoint QCommonListViewBase::offset () const inline
Definition at line 454 of file qlistview_p.h.
 { return dd->offset(); }
paintDragDrop()
void QCommonListViewBase::paintDragDrop (QPainter * painter)
Definition at line 1924 of file qlistview.cpp.
 {
     // FIXME: Until the we can provide a proper drop indicator
     // in IconMode, it makes no sense to show it
     dd->paintDropIndicator(painter);
 }
pressedPosition()
QPoint QCommonListViewBase::pressedPosition () const inline
Definition at line 455 of file qlistview_p.h.
 { return dd->pressedPosition; }
removeHiddenRow()
void QCommonListViewBase::removeHiddenRow (int row) virtual
Reimplemented in QIconModeViewBase.
Definition at line 1918 of file qlistview.cpp.
Referenced by QIconModeViewBase::removeHiddenRow().
 {
     dd->hiddenRows.remove(dd->model->index(row, 0, qq->rootIndex()));
 }
rowCount()
int QCommonListViewBase::rowCount () const inline
Definition at line 466 of file qlistview_p.h.
 { return dd->model->rowCount(dd->root); }
scrollContentsBy()
void QCommonListViewBase::scrollContentsBy (int dx, int dy, bool scrollElasticBand) virtual
Reimplemented in QIconModeViewBase, and QListModeViewBase.
Definition at line 1946 of file qlistview.cpp.
Referenced by QListModeViewBase::scrollContentsBy(), and QIconModeViewBase::scrollContentsBy().
 {
     dd->scrollContentsBy(isRightToLeft() ? -dx : dx, dy);
 }
setPositionForIndex()
virtual void QCommonListViewBase::setPositionForIndex (const QPoint & , const QModelIndex &) inline virtual
Reimplemented in QIconModeViewBase.
Definition at line 147 of file qlistview_p.h.
 { }
setRowCount()
virtual void QCommonListViewBase::setRowCount (int) pure virtual
Implemented in QIconModeViewBase, and QListModeViewBase.
Referenced by QListViewPrivate::prepareItemsLayout().
spacing()
int QCommonListViewBase::spacing () const inline
Definition at line 448 of file qlistview_p.h.
 { return dd->spacing(); }
uniformItemSizes()
bool QCommonListViewBase::uniformItemSizes () const inline
Definition at line 456 of file qlistview_p.h.
 { return dd->uniformItemSizes; }
updateHorizontalScrollBar()
void QCommonListViewBase::updateHorizontalScrollBar (const QSize & step) virtual
Reimplemented in QListModeViewBase.
Definition at line 1932 of file qlistview.cpp.
Referenced by QListModeViewBase::updateHorizontalScrollBar().
 {
     horizontalScrollBar()->setSingleStep(step.width() + spacing());
     horizontalScrollBar()->setPageStep(viewport()->width());
     horizontalScrollBar()->setRange(0, contentsSize.width() - viewport()->width());
 }
updateVerticalScrollBar()
void QCommonListViewBase::updateVerticalScrollBar (const QSize & step) virtual
Reimplemented in QListModeViewBase.
Definition at line 1939 of file qlistview.cpp.
Referenced by QListModeViewBase::updateVerticalScrollBar().
 {
     verticalScrollBar()->setSingleStep(step.height() + spacing());
     verticalScrollBar()->setPageStep(viewport()->height());
     verticalScrollBar()->setRange(0, contentsSize.height() - viewport()->height());
 }
verticalOffset()
virtual int QCommonListViewBase::verticalOffset () const inline virtual
Reimplemented in QListModeViewBase.
Definition at line 142 of file qlistview_p.h.
Referenced by QListModeViewBase::verticalOffset().
 { return verticalScrollBar()->value(); }
verticalScrollBar()
QScrollBar * QCommonListViewBase::verticalScrollBar () const inline
Definition at line 459 of file qlistview_p.h.
 { return qq->verticalScrollBar(); }
verticalScrollMode()
QListView::ScrollMode QCommonListViewBase::verticalScrollMode () const inline
Definition at line 461 of file qlistview_p.h.
 { return qq->verticalScrollMode(); }
verticalScrollToValue()
int QCommonListViewBase::verticalScrollToValue (int index, QListView::ScrollHint hint, bool above, bool below, const QRect & area, const QRect & rect) const virtual
Reimplemented in QListModeViewBase.
Definition at line 1951 of file qlistview.cpp.
Referenced by QListModeViewBase::verticalScrollToValue().
 {
     int verticalValue = verticalScrollBar()->value();
     QRect adjusted = rect.adjusted(-spacing(), -spacing(), spacing(), spacing());
     if (hint == QListView::PositionAtTop || above)
         verticalValue += adjusted.top();
     else if (hint == QListView::PositionAtBottom || below)
         verticalValue += qMin(adjusted.top(), adjusted.bottom() - area.height() + 1);
     else if (hint == QListView::PositionAtCenter)
         verticalValue += adjusted.top() - ((area.height() - adjusted.height()) / 2);
     return verticalValue;
 }
viewItemRect()
QRect QCommonListViewBase::viewItemRect (const QListViewItem & item) const inline
Definition at line 473 of file qlistview_p.h.
 { return dd->viewItemRect(item); }
viewOptions()
QStyleOptionViewItemV4 QCommonListViewBase::viewOptions () const inline
Definition at line 468 of file qlistview_p.h.
 { return dd->viewOptionsV4(); }
viewport()
QWidget * QCommonListViewBase::viewport () const inline
Definition at line 469 of file qlistview_p.h.
 { return dd->viewport; }
Properties
batchSavedDeltaSeg
int QCommonListViewBase::batchSavedDeltaSeg
Definition at line 196 of file qlistview_p.h.
batchStartRow
int QCommonListViewBase::batchStartRow
Definition at line 195 of file qlistview_p.h.
contentsSize
QSize QCommonListViewBase::contentsSize
Definition at line 194 of file qlistview_p.h.
dd
QListViewPrivate* QCommonListViewBase::dd
Definition at line 192 of file qlistview_p.h.
Referenced by QIconModeViewBase::addLeaf().
qq
QListView* QCommonListViewBase::qq
Definition at line 193 of file qlistview_p.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qlistview_p.h
/src/gui/itemviews/qlistview.cpp