Qt 4.8: QDeclarativeBinding Class Reference
QDeclarativeBinding Class Reference
#include <qdeclarativebinding_p.h>
Public Types
enum EvaluateFlag { RequiresThisObject = 0x01 }
typedef int Identifier
Public Types inherited from QDeclarativeAbstractBinding
enum DestroyMode { DisconnectBinding, KeepBindingConnected }
enum DisconnectMode { DisconnectOne, DisconnectAll }
typedef QWeakPointer< QDeclarativeAbstractBinding > Pointer
enum Type { PropertyBinding, ValueTypeProxy }
Public Slots
void update ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
virtual void disconnect (DisconnectMode disconnectMode)
bool enabled () const
EvaluateFlags evaluateFlags () const
virtual QString expression () const
QDeclarativeProperty property () const
QDeclarativeBinding (const QString &, QObject *, QDeclarativeContext *, QObject *parent=0)
QDeclarativeBinding (const QString &, QObject *, QDeclarativeContextData *, QObject *parent=0)
QDeclarativeBinding (void *, QDeclarativeRefCount *, QObject *, QDeclarativeContextData *, const QString &, int, QObject *parent)
QDeclarativeBinding (const QScriptValue &, QObject *, QDeclarativeContextData *, QObject *parent=0)
virtual void setEnabled (bool, QDeclarativePropertyPrivate::WriteFlags flags)
void setEvaluateFlags (EvaluateFlags flags)
void setTarget (const QDeclarativeProperty &)
virtual void update (QDeclarativePropertyPrivate::WriteFlags flags)
Public Functions inherited from QDeclarativeExpression
void clearError ()
Clear any expression errors.
QDeclarativeContext * context () const
Returns the QDeclarativeContext this expression is associated with, or 0 if there is no association or the QDeclarativeContext has been destroyed.
QDeclarativeEngine * engine () const
Returns the QDeclarativeEngine this expression is associated with, or 0 if there is no association or the QDeclarativeEngine has been destroyed.
QDeclarativeError error () const
Return any error from the last call to evaluate().
QVariant evaluate (bool *valueIsUndefined=0)
Evaulates the expression, returning the result of the evaluation, or an invalid QVariant if the expression is invalid or has an error.
QString expression () const
Returns the expression string.
bool hasError () const
Returns true if the last call to evaluate() resulted in an error, otherwise false.
int lineNumber () const
Returns the source file line number for this expression.
bool notifyOnValueChanged () const
Returns true if the valueChanged() signal is emitted when the expression's evaluated value changes.
QDeclarativeExpression ()
Create an invalid QDeclarativeExpression.
QDeclarativeExpression (QDeclarativeContext *, QObject *, const QString &, QObject *=0)
Create a QDeclarativeExpression object that is a child of parent.
QObject * scopeObject () const
Returns the expression's scope object, if provided, otherwise 0.
void setExpression (const QString &)
Set the expression to expression.
void setNotifyOnValueChanged (bool)
Sets whether the valueChanged() signal is emitted when the expression's evaluated value changes.
void setSourceLocation (const QString &fileName, int line)
Set the location of this expression to line of url.
QString sourceFile () const
Returns the source file URL for this expression.
virtual ~QDeclarativeExpression ()
Destroy the QDeclarativeExpression instance.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeAbstractBinding
void addToObject (QObject *, int)
Add this binding to object.
virtual Type bindingType () const
virtual void destroy (DestroyMode mode=DisconnectBinding)
Destroy the binding.
QObject * object () const
int propertyIndex () const
QDeclarativeAbstractBinding ()
void removeFromObject ()
Remove the binding from the object.
void setEnabled (bool e)
void update ()
Static Public Functions
static QDeclarativeBinding * createBinding (Identifier, QObject *, QDeclarativeContext *, const QString &, int, QObject *parent=0)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QDeclarativeAbstractBinding
static Pointer getPointer (QDeclarativeAbstractBinding *p)
Static Public Variables
static Identifier Invalid = -1
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions
void emitValueChanged ()
~QDeclarativeBinding ()
Protected Functions inherited from QDeclarativeExpression
QDeclarativeExpression (QDeclarativeContextData *, QObject *, const QString &, QDeclarativeExpressionPrivate &dd)
QDeclarativeExpression (QDeclarativeContextData *, QObject *, const QScriptValue &, QDeclarativeExpressionPrivate &dd)
QDeclarativeExpression (QDeclarativeContextData *, void *, QDeclarativeRefCount *rc, QObject *me, const QString &, int, QDeclarativeExpressionPrivate &dd)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QDeclarativeAbstractBinding
void clear ()
virtual ~QDeclarativeAbstractBinding ()
Additional Inherited Members
Signals inherited from QDeclarativeExpression
void valueChanged ()
Emitted each time the expression value changes from the last time it was evaluated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 176 of file qdeclarativebinding_p.h.
Typedefs
Identifier
typedef int QDeclarativeBinding::Identifier
Definition at line 203 of file qdeclarativebinding_p.h.
Enumerations
EvaluateFlag
enum QDeclarativeBinding::EvaluateFlag
Enumerator
RequiresThisObject
Definition at line 180 of file qdeclarativebinding_p.h.
 { RequiresThisObject = 0x01 };
Constructors and Destructors
QDeclarativeBinding() [1/4]
QDeclarativeBinding::QDeclarativeBinding (const QString & str, QObject * obj, QDeclarativeContext * ctxt, QObject * parent = 0)
Definition at line 267 of file qdeclarativebinding.cpp.
Referenced by createBinding().
 : QDeclarativeExpression(QDeclarativeContextData::get(ctxt), obj, str, *new QDeclarativeBindingPrivate)
 {
     setParent(parent);
     setNotifyOnValueChanged(true);
 }
QDeclarativeBinding() [2/4]
QDeclarativeBinding::QDeclarativeBinding (const QString & str, QObject * obj, QDeclarativeContextData * ctxt, QObject * parent = 0)
Definition at line 275 of file qdeclarativebinding.cpp.
 : QDeclarativeExpression(ctxt, obj, str, *new QDeclarativeBindingPrivate)
 {
     setParent(parent);
     setNotifyOnValueChanged(true);
 }
QDeclarativeBinding() [3/4]
QDeclarativeBinding::QDeclarativeBinding (void * data, QDeclarativeRefCount * rc, QObject * obj, QDeclarativeContextData * ctxt, const QString & url, int lineNumber, QObject * parent)
Definition at line 233 of file qdeclarativebinding.cpp.
 : QDeclarativeExpression(ctxt, data, rc, obj, url, lineNumber, *new QDeclarativeBindingPrivate)
 {
     setParent(parent);
     setNotifyOnValueChanged(true);
 }
QDeclarativeBinding() [4/4]
QDeclarativeBinding::QDeclarativeBinding (const QScriptValue & func, QObject * obj, QDeclarativeContextData * ctxt, QObject * parent = 0)
Definition at line 283 of file qdeclarativebinding.cpp.
 : QDeclarativeExpression(ctxt, obj, func, *new QDeclarativeBindingPrivate)
 {
     setParent(parent);
     setNotifyOnValueChanged(true);
 }
~QDeclarativeBinding()
QDeclarativeBinding::~QDeclarativeBinding () protected
Definition at line 290 of file qdeclarativebinding.cpp.
 {
 }
Functions
createBinding()
QDeclarativeBinding * QDeclarativeBinding::createBinding (Identifier id, QObject * obj, QDeclarativeContext * ctxt, const QString & url, int lineNumber, QObject * parent = 0) static
Definition at line 243 of file qdeclarativebinding.cpp.
Referenced by QDeclarativePropertyChanges::actions().
 {
     if (id < 0)
         return 0;
     Q_ASSERT(ctxt);
     QDeclarativeContextData *ctxtdata = QDeclarativeContextData::get(ctxt);
     QDeclarativeEnginePrivate *engine = QDeclarativeEnginePrivate::get(ctxtdata->engine);
     QDeclarativeCompiledData *cdata = 0;
     QDeclarativeTypeData *typeData = 0;
     if (!ctxtdata->url.isEmpty()) {
         typeData = engine->typeLoader.get(ctxtdata->url);
         cdata = typeData->compiledData();
     }
     QDeclarativeBinding *rv = cdata ? new QDeclarativeBinding((void*)cdata->datas.at(id).constData(), cdata, obj, ctxtdata, url, lineNumber, parent) : 0;
     if (cdata)
         cdata->release();
     if (typeData)
         typeData->release();
     return rv;
 }
disconnect()
void QDeclarativeBinding::disconnect (DisconnectMode disconnectMode) virtual
Implements QDeclarativeAbstractBinding.
Definition at line 494 of file qdeclarativebinding.cpp.
 {
     Q_UNUSED(disconnectMode);
     setNotifyOnValueChanged(false);
 }
emitValueChanged()
void QDeclarativeBinding::emitValueChanged () protected
enabled()
bool QDeclarativeBinding::enabled () const
Definition at line 482 of file qdeclarativebinding.cpp.
 {
     Q_D(const QDeclarativeBinding);
     return d->enabled;
 }
evaluateFlags()
QDeclarativeBinding::EvaluateFlags QDeclarativeBinding::evaluateFlags () const
Definition at line 314 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeValueTypeScriptClass::setProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     Q_D(const QDeclarativeBinding);
     return QDeclarativeBinding::EvaluateFlags(static_cast<int>(d->evaluateFlags()));
 }
expression()
QString QDeclarativeBinding::expression () const virtual
Reimplemented from QDeclarativeAbstractBinding.
Definition at line 489 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeBindingProfiler::QDeclarativeBindingProfiler(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), and QDeclarativeStateGroupPrivate::updateAutoState().
 {
     return QDeclarativeExpression::expression();
 }
property()
QDeclarativeProperty QDeclarativeBinding::property () const
Definition at line 302 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeParentChange::actions().
 {
    Q_D(const QDeclarativeBinding);
    return d->property;
 }
setEnabled()
void QDeclarativeBinding::setEnabled (bool e, QDeclarativePropertyPrivate::WriteFlags flags) virtual
Implements QDeclarativeAbstractBinding.
Definition at line 472 of file qdeclarativebinding.cpp.
 {
     Q_D(QDeclarativeBinding);
     d->enabled = e;
     setNotifyOnValueChanged(e);
     if (e)
         update(flags);
 }
setEvaluateFlags()
void QDeclarativeBinding::setEvaluateFlags (EvaluateFlags flags)
Definition at line 308 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeValueTypeScriptClass::setProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     Q_D(QDeclarativeBinding);
     d->setEvaluateFlags(QDeclarativeQtScriptExpression::EvaluateFlags(static_cast<int>(flags)));
 }
setTarget()
void QDeclarativeBinding::setTarget (const QDeclarativeProperty & prop)
Definition at line 294 of file qdeclarativebinding.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativeParentChange::actions(), QDeclarativePropertyChanges::changeExpression(), QDeclarativeEngineDebugService::setBinding(), QDeclarativeValueTypeScriptClass::setProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     Q_D(QDeclarativeBinding);
     d->property = prop;
     update();
 }
update() [1/2]
void QDeclarativeBinding::update (QDeclarativePropertyPrivate::WriteFlags flags) virtual
Implements QDeclarativeAbstractBinding.
Definition at line 336 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeEngineDebugService::setBinding().
 {
     Q_D(QDeclarativeBinding);
     if (!d->enabled || !d->context() || !d->context()->isValid())
         return;
     if (!d->updating) {
         QDeclarativeBindingProfiler prof(this);
         d->updating = true;
         bool wasDeleted = false;
         d->deleted = &wasDeleted;
         if (d->property.propertyType() == qMetaTypeId<QDeclarativeBinding *>()) {
             int idx = d->property.index();
             Q_ASSERT(idx != -1);
             QDeclarativeBinding *t = this;
             int status = -1;
             void *a[] = { &t, 0, &status, &flags };
             QMetaObject::metacall(d->property.object(),
                                   QMetaObject::WriteProperty,
                                   idx, a);
             if (wasDeleted)
                 return;
         } else {
             QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(d->context()->engine);
             bool isUndefined = false;
             QVariant value;
             QScriptValue scriptValue = d->scriptValue(0, &isUndefined);
             if (wasDeleted)
                 return;
             if (d->property.propertyTypeCategory() == QDeclarativeProperty::List) {
                 value = ep->scriptValueToVariant(scriptValue, qMetaTypeId<QList<QObject *> >());
             } else if (scriptValue.isNull() &&
                        d->property.propertyTypeCategory() == QDeclarativeProperty::Object) {
                 value = QVariant::fromValue((QObject *)0);
             } else {
                 value = ep->scriptValueToVariant(scriptValue, d->property.propertyType());
                 if (value.userType() == QMetaType::QObjectStar && !qvariant_cast<QObject*>(value)) {
                     // If the object is null, we extract the predicted type.  While this isn't
                     // 100% reliable, in many cases it gives us better error messages if we
                     // assign this null-object to an incompatible property
                     int type = ep->objectClass->objectType(scriptValue);
                     QObject *o = 0;
                     value = QVariant(type, (void *)&o);
                 }
             }
             if (d->error.isValid()) {
             } else if (isUndefined && d->property.isResettable()) {
                 d->property.reset();
             } else if (isUndefined && d->property.propertyType() == qMetaTypeId<QVariant>()) {
                 QDeclarativePropertyPrivate::write(d->property, QVariant(), flags);
             } else if (isUndefined) {
                 QUrl url = QUrl(d->url);
                 int line = d->line;
                 if (url.isEmpty()) url = QUrl(QLatin1String("<Unknown File>"));
                 d->error.setUrl(url);
                 d->error.setLine(line);
                 d->error.setColumn(-1);
                 d->error.setDescription(QLatin1String("Unable to assign [undefined] to ") +
                                         QLatin1String(QMetaType::typeName(d->property.propertyType())) +
                                         QLatin1String(" ") + d->property.name());
             } else if (!scriptValue.isRegExp() && scriptValue.isFunction()) {
                 QUrl url = QUrl(d->url);
                 int line = d->line;
                 if (url.isEmpty()) url = QUrl(QLatin1String("<Unknown File>"));
                 d->error.setUrl(url);
                 d->error.setLine(line);
                 d->error.setColumn(-1);
                 d->error.setDescription(QLatin1String("Unable to assign a function to a property."));
             } else if (d->property.object() &&
                        !QDeclarativePropertyPrivate::write(d->property, value, flags)) {
                 if (wasDeleted)
                     return;
                 QUrl url = QUrl(d->url);
                 int line = d->line;
                 if (url.isEmpty()) url = QUrl(QLatin1String("<Unknown File>"));
                 const char *valueType = 0;
                 if (value.userType() == QVariant::Invalid) valueType = "null";
                 else valueType = QMetaType::typeName(value.userType());
                 d->error.setUrl(url);
                 d->error.setLine(line);
                 d->error.setColumn(-1);
                 d->error.setDescription(QLatin1String("Unable to assign ") +
                                         QLatin1String(valueType) +
                                         QLatin1String(" to ") +
                                         QLatin1String(QMetaType::typeName(d->property.propertyType())));
             }
             if (wasDeleted)
                 return;
             if (d->error.isValid()) {
                if (!d->addError(ep)) ep->warning(this->error());
             } else {
                 d->removeError();
             }
         }
         d->updating = false;
         d->deleted = 0;
     } else {
         qmlInfo(d->property.object()) << tr("Binding loop detected for property \"%1\"").arg(d->property.name());
     }
 }
update [2/2]
void QDeclarativeBinding::update () inline slot
Definition at line 208 of file qdeclarativebinding_p.h.
Referenced by setEnabled(), setTarget(), and update().
 { update(QDeclarativePropertyPrivate::DontRemoveBinding); }
Properties
Invalid
QDeclarativeBinding::Identifier QDeclarativeBinding::Invalid = -1 static
Definition at line 204 of file qdeclarativebinding_p.h.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativePropertyChanges::changeExpression(), QDeclarativePropertyChangesPrivate::decode(), and QDeclarativeAbstractBinding::setEnabled().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativebinding_p.h
/src/declarative/qml/qdeclarativebinding.cpp