Qt 4.8: QPatternist::GenericPredicate Class Reference
QPatternist::GenericPredicate Class Reference
A predicate that can handle all kinds of predicates and is therefore not very efficient, but can cope with all the tricky scenarios.
#include <qgenericpredicate_p.h>
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual QString description () const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
virtual SequenceType::List expectedOperandTypes () const
virtual ID id () const
Item mapToItem (const Item &subject, const DynamicContext::Ptr &) const
virtual Properties properties () const
virtual SequenceType::Ptr staticType () const
Public Functions inherited from QPatternist::PairContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &operands)
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Static Public Functions
static Expression::Ptr create (const Expression::Ptr &sourceExpression, const Expression::Ptr &predicateExpression, const StaticContext::Ptr &context, const QSourceLocation &location)
static Expression::Ptr createFirstItem (const Expression::Ptr &sourceExpression)
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Protected Functions
GenericPredicate (const Expression::Ptr &sourceExpression, const Expression::Ptr &predicate)
virtual ItemType::Ptr newFocusType () const
Protected Functions inherited from QPatternist::PairContainer
PairContainer (const Expression::Ptr &operand1, const Expression::Ptr &operand2)
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Private Types
typedef QExplicitlySharedDataPointer< const GenericPredicate > ConstPtr
Additional Inherited Members
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Variables inherited from QPatternist::PairContainer
Expression::Ptr m_operand1
Expression::Ptr m_operand2
Detailed Description
A predicate that can handle all kinds of predicates and is therefore not very efficient, but can cope with all the tricky scenarios.
See also
FirstItemPredicate
TruthPredicate
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 72 of file qgenericpredicate_p.h.
Typedefs
ConstPtr
typedef QExplicitlySharedDataPointer<const GenericPredicate> QPatternist::GenericPredicate::ConstPtr private
Definition at line 140 of file qgenericpredicate_p.h.
Constructors and Destructors
GenericPredicate()
GenericPredicate::GenericPredicate (const Expression::Ptr & sourceExpression, const Expression::Ptr & predicate) protected
Creates a GenericPredicate which filters the items from the sourceExpression through predicate.
This constructor is protected. The proper way to create predicates is via the static create() function.
Definition at line 60 of file qgenericpredicate.cpp.
Referenced by create().
                                                                    : PairContainer(sourceExpression,
                                                                                      predicate)
 {
 }
Functions
accept()
ExpressionVisitorResult::Ptr GenericPredicate::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Reimplemented in QPatternist::TruthPredicate.
Definition at line 193 of file qgenericpredicate.cpp.
 {
     return visitor->visit(this);
 }
create()
Expression::Ptr GenericPredicate::create (const Expression::Ptr & sourceExpression, const Expression::Ptr & predicateExpression, const StaticContext::Ptr & context, const QSourceLocation & location) static
Creates a predicate expression that filters the items gained from evaluating sourceExpression through the filter predicateExpression.
This function performs type analyzis on the passed expressions, and may return more specialized expressions depending on the analyzis.
If predicateExpression is an invalid predicate, an error is issued via the context.
Definition at line 66 of file qgenericpredicate.cpp.
Referenced by QPatternist::createIdPatternPath(), QPatternist::createPatternPath(), and QPatternist::yyparse().
 {
     Q_ASSERT(sourceExpression);
     Q_ASSERT(predicateExpression);
     Q_ASSERT(context);
     const ItemType::Ptr type(predicateExpression->staticType()->itemType());
     if(predicateExpression->is(IDIntegerValue) &&
        predicateExpression->as<Literal>()->item().as<Numeric>()->toInteger() == 1)
     { /* Handle [1] */
         return createFirstItem(sourceExpression);
     }
     else if(BuiltinTypes::numeric->xdtTypeMatches(type))
     { /* A numeric predicate, other than [1]. */
         /* TODO at somepoint we'll return a specialized expr here, NumericPredicate or so.
          * Dependency analysis is a bit tricky, since the contained expression can depend on
          * some loop component. */
         return Expression::Ptr(new GenericPredicate(sourceExpression, predicateExpression));
     }
     else if(*CommonSequenceTypes::Empty == *type)
     {
         return EmptySequence::create(predicateExpression.data(), context);
     }
     else if(*BuiltinTypes::item == *type ||
             *BuiltinTypes::xsAnyAtomicType == *type)
     {
         /* The type couldn't be narrowed at compile time, so we use
          * a generic predicate. This check is before the CommonSequenceTypes::EBV check,
          * because the latter matches these types as well. */
         return Expression::Ptr(new GenericPredicate(sourceExpression, predicateExpression));
     }
     else if(CommonSequenceTypes::EBV->itemType()->xdtTypeMatches(type))
     {
         return Expression::Ptr(new TruthPredicate(sourceExpression, predicateExpression));
     }
     else
     {
         context->error(QtXmlPatterns::tr("A value of type %1 cannot be a "
                                          "predicate. A predicate must have "
                                          "either a numeric type or an "
                                          "Effective Boolean Value type.")
                        .arg(formatType(context->namePool(),
                                        sourceExpression->staticType())),
                        ReportContext::FORG0006, location);
         return Expression::Ptr(); /* Silence compiler warning. */
     }
 }
createFirstItem()
Expression::Ptr GenericPredicate::createFirstItem (const Expression::Ptr & sourceExpression) static
Definition at line 117 of file qgenericpredicate.cpp.
Referenced by create(), QPatternist::CardinalityVerifier::verifyCardinality(), and QPatternist::yyparse().
 {
     return Expression::Ptr(new FirstItemPredicate(sourceExpression));
 }
description()
QString GenericPredicate::description () const virtual
Reimplementation of SourceLocationReflection::description().
Reimplemented from QPatternist::Expression.
Definition at line 208 of file qgenericpredicate.cpp.
 {
     return QLatin1String("predicate");
 }
evaluateSequence()
Item::Iterator::Ptr GenericPredicate::evaluateSequence (const DynamicContext::Ptr & context) const virtual
Creates a source iterator which is passed to the ItemMappingIterator and the Focus. The ItemMappingIterator modifies it with its QAbstractXmlForwardIterator::next() calls, and since the Focus references the same QAbstractXmlForwardIterator, the focus is automatically moved.
Reimplemented from QPatternist::Expression.
Definition at line 159 of file qgenericpredicate.cpp.
 {
     const Item::Iterator::Ptr focus(m_operand1->evaluateSequence(context));
     const DynamicContext::Ptr newContext(context->createFocus());
     newContext->setFocusIterator(focus);
     return makeItemMappingIterator<Item>(ConstPtr(this),
                                          focus,
                                          newContext);
 }
evaluateSingleton()
Item GenericPredicate::evaluateSingleton (const DynamicContext::Ptr & context) const virtual
Doesn't return the first item from calling evaluateSequence(), but does the mapping manually. This avoid allocating an ItemMappingIterator.
Reimplemented from QPatternist::Expression.
Definition at line 170 of file qgenericpredicate.cpp.
 {
     const Item::Iterator::Ptr focus(m_operand1->evaluateSequence(context));
     const DynamicContext::Ptr newContext(context->createFocus());
     newContext->setFocusIterator(focus);
     return mapToItem(focus->next(), newContext);
 }
expectedOperandTypes()
SequenceType::List GenericPredicate::expectedOperandTypes () const virtual
Returns a list of Sequence Types, describing the type of each of the expression's operands. Hence, this function has a relationship to the operands() function:
- The lengths of the lists returned by expectedOperandTypes()
and operands() should always be equal in length, since one
cannot describe the type of a non-existent operand(and all
operands must have type information).
- A significant difference between the two functions is that while
the type of objects in the list returned by operands() may vary
between compilations/static context, simply because the particular
Expression is part of different XPath expressions, the
types in the list returned by expectedOperandTypes is always the same
since the function/operator signature never changes.
This function should not be confused with staticType(), which returns the static type of the expression itself, not its operands. The function call is an expression where this is clear: the type of the return value is not the same as the arguments' types. The static type of the operands supplied to the expression can be determined via the staticType() function of the instances returned by operands().
If the expression has no operands, an empty list should be returned.
Implements QPatternist::Expression.
Reimplemented in QPatternist::TruthPredicate.
Definition at line 178 of file qgenericpredicate.cpp.
 {
     SequenceType::List result;
     result.append(CommonSequenceTypes::ZeroOrMoreItems);
     result.append(CommonSequenceTypes::ZeroOrMoreItems);
     return result;
 }
id()
Expression::ID GenericPredicate::id () const virtual
This property, which has no setter, returns an enum value that uniquely identifies this Expression. Patternist makes no use of C++'s dynamic_cast feature, but uses this polymorphic function instead.
Returns
always IgnorableExpression.
Reimplemented from QPatternist::Expression.
Definition at line 213 of file qgenericpredicate.cpp.
 {
     return IDGenericPredicate;
 }
mapToItem()
Item GenericPredicate::mapToItem (const Item & subject, const DynamicContext::Ptr & context) const inline
Definition at line 123 of file qgenericpredicate.cpp.
Referenced by evaluateSingleton().
 {
     const Item::Iterator::Ptr it(m_operand2->evaluateSequence(context));
     const Item pcateItem(it->next());
     if(!pcateItem)
         return Item(); /* The predicate evaluated to the empty sequence */
     else if(pcateItem.isNode())
         return item;
     /* Ok, now it must be an AtomicValue */
     else if(BuiltinTypes::numeric->xdtTypeMatches(pcateItem.type()))
     { /* It's a positional predicate. */
         if(it->next())
         {
             context->error(QtXmlPatterns::tr("A positional predicate must "
                                              "evaluate to a single numeric "
                                              "value."),
                               ReportContext::FORG0006, this);
             return Item();
         }
         if(Double::isEqual(static_cast<xsDouble>(context->contextPosition()),
                            pcateItem.as<Numeric>()->toDouble()))
         {
             return item;
         }
         else
             return Item();
     }
     else if(Boolean::evaluateEBV(pcateItem, it, context)) /* It's a truth predicate. */
         return item;
     else
         return Item();
 }
newFocusType()
ItemType::Ptr GenericPredicate::newFocusType () const protected virtual
Returns
the ItemType of the first operand's staticType().
Reimplemented from QPatternist::Expression.
Definition at line 198 of file qgenericpredicate.cpp.
 {
     return m_operand1->staticType()->itemType();
 }
properties()
Expression::Properties GenericPredicate::properties () const virtual
Returns
always CreatesFocusForLast.
Reimplemented from QPatternist::Expression.
Definition at line 203 of file qgenericpredicate.cpp.
 {
     return CreatesFocusForLast;
 }
staticType()
SequenceType::Ptr GenericPredicate::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Definition at line 186 of file qgenericpredicate.cpp.
 {
     const SequenceType::Ptr type(m_operand1->staticType());
     return makeGenericSequenceType(type->itemType(),
                                    type->cardinality() | Cardinality::zeroOrOne());
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qgenericpredicate_p.h
/src/xmlpatterns/expr/qgenericpredicate.cpp