Qt 4.8: QDebug Class Reference
QDebug Class Reference
The QDebug class provides an output stream for debugging information.
#include <qdebug.h>
Classes
struct Stream
Public Functions
QDebug & maybeSpace ()
Writes a space character to the debug stream, depending on the last character sent to the stream, and returns a reference to the stream.
QDebug & nospace ()
Clears the stream's internal flag that records whether the last character was a space and returns a reference to the stream.
QDebug & operator<< (QChar t)
Writes the character, t, to the stream and returns a reference to the stream.
QDebug & operator<< (QBool t)
Writes the boolean value, t, to the stream and returns a reference to the stream.
QDebug & operator<< (bool t)
Writes the boolean value, t, to the stream and returns a reference to the stream.
QDebug & operator<< (char t)
Writes the character, t, to the stream and returns a reference to the stream.
QDebug & operator<< (signed short t)
Writes the signed short integer, i, to the stream and returns a reference to the stream.
QDebug & operator<< (unsigned short t)
Writes then unsigned short integer, i, to the stream and returns a reference to the stream.
QDebug & operator<< (signed int t)
Writes the signed integer, i, to the stream and returns a reference to the stream.
QDebug & operator<< (unsigned int t)
Writes then unsigned integer, i, to the stream and returns a reference to the stream.
QDebug & operator<< (signed long t)
Writes the signed long integer, l, to the stream and returns a reference to the stream.
QDebug & operator<< (unsigned long t)
Writes then unsigned long integer, l, to the stream and returns a reference to the stream.
QDebug & operator<< (qint64 t)
Writes the signed 64-bit integer, i, to the stream and returns a reference to the stream.
QDebug & operator<< (quint64 t)
Writes then unsigned 64-bit integer, i, to the stream and returns a reference to the stream.
QDebug & operator<< (float t)
Writes the 32-bit floating point number, f, to the stream and returns a reference to the stream.
QDebug & operator<< (double t)
Writes the 64-bit floating point number, f, to the stream and returns a reference to the stream.
QDebug & operator<< (const char *t)
Writes the '\0'-terminated string, s, to the stream and returns a reference to the stream.
QDebug & operator<< (const QString &t)
Writes the string, s, to the stream and returns a reference to the stream.
QDebug & operator<< (const QStringRef &t)
Writes the string reference, s, to the stream and returns a reference to the stream.
QDebug & operator<< (const QLatin1String &t)
Writes the Latin1-encoded string, s, to the stream and returns a reference to the stream.
QDebug & operator<< (const QByteArray &t)
Writes the byte array, b, to the stream and returns a reference to the stream.
QDebug & operator<< (const void *t)
Writes a pointer, p, to the stream and returns a reference to the stream.
QDebug & operator<< (QTextStreamFunction f)
QDebug & operator<< (QTextStreamManipulator m)
QDebug & operator= (const QDebug &other)
Assigns the other debug stream to this stream and returns a reference to this stream.
QDebug (QIODevice *device)
Constructs a debug stream that writes to the given device.
QDebug (QString *string)
Constructs a debug stream that writes to the given string.
QDebug (QtMsgType t)
Constructs a debug stream that writes to the handler for the message type specified by type.
QDebug (const QDebug &o)
Constructs a copy of the other debug stream.
QDebug & space ()
Writes a space character to the debug stream and returns a reference to the stream.
~QDebug ()
Flushes any pending data to be written and destroys the debug stream.
Properties
struct QDebug::Stream * stream
Detailed Description
The QDebug class provides an output stream for debugging information.
QDebug is used whenever the developer needs to write out debugging or tracing information to a device, file, string or console.
Basic Use
In the common case, it is useful to call the qDebug() function to obtain a default QDebug object to use for writing debugging information.
    qDebug() << "Date:" << QDate::currentDate();
    qDebug() << "Types:" << QString("String") << QChar('x') << QRect(0, 10, 50, 40);
    qDebug() << "Custom coordinate type:" << coordinate;
This constructs a QDebug object using the constructor that accepts a QtMsgType value of QtDebugMsg. Similarly, the qWarning(), qCritical() and qFatal() functions also return QDebug objects for the corresponding message types.
The class also provides several constructors for other situations, including a constructor that accepts a QFile or any other QIODevice subclass that is used to write debugging information to files and other devices. The constructor that accepts a QString is used to write to a string for display or serialization.
Writing Custom Types to a Stream
Many standard types can be written to QDebug objects, and Qt provides support for most Qt value types. To add support for custom types, you need to implement a streaming operator, as in the following example:
QDebug operator<<(QDebug dbg, const Coordinate &c)
{
    dbg.nospace() << "(" << c.x() << ", " << c.y() << ")";
    return dbg.space();
}
This is described in the Debugging Techniques and Creating Custom Qt Types::Making the Type Printable{Creating Custom Qt Types} documents.
Definition at line 62 of file qdebug.h.
Constructors and Destructors
QDebug() [1/4]
QDebug::QDebug (QIODevice * device) inline
Constructs a debug stream that writes to the given device.
Definition at line 76 of file qdebug.h.
 : stream(new Stream(device)) {}
QDebug() [2/4]
QDebug::QDebug (QString * string) inline
Constructs a debug stream that writes to the given string.
Definition at line 77 of file qdebug.h.
 : stream(new Stream(string)) {}
QDebug() [3/4]
QDebug::QDebug (QtMsgType t) inline
Constructs a debug stream that writes to the handler for the message type specified by type.
Definition at line 78 of file qdebug.h.
 : stream(new Stream(t)) {}
QDebug() [4/4]
QDebug::QDebug (const QDebug & o) inline
Constructs a copy of the other debug stream.
Definition at line 79 of file qdebug.h.
 :stream(o.stream) { ++stream->ref; }
~QDebug()
QDebug::~QDebug () inline
Flushes any pending data to be written and destroys the debug stream.
Definition at line 81 of file qdebug.h.
                      {
         if (!--stream->ref) {
             if(stream->message_output) {
                 QT_TRY {
                     qt_message_output(stream->type, stream->buffer.toLocal8Bit().data());
                 } QT_CATCH(std::bad_alloc&) { /* We're out of memory - give up. */ }
             }
             delete stream;
         }
     }
Functions
maybeSpace()
QDebug & QDebug::maybeSpace () inline
Writes a space character to the debug stream, depending on the last character sent to the stream, and returns a reference to the stream.
If the last character was a space character, this function writes a space character to the stream; otherwise, no characters are written to the stream.
See also
space(), nospace()
Definition at line 93 of file qdebug.h.
Referenced by operator<<().
 { if (stream->space) stream->ts << ' '; return *this; }
nospace()
QDebug & QDebug::nospace () inline
Clears the stream's internal flag that records whether the last character was a space and returns a reference to the stream.
See also
space(), maybeSpace()
Definition at line 92 of file qdebug.h.
Referenced by debugVariantList(), flagsDebug(), operator<<(), QDeclarativeInfo::QDeclarativeInfo(), and streamDebug().
 { stream->space = false; return *this; }
operator<<() [1/22]
QDebug & QDebug::operator<< (QChar t) inline
Writes the character, t, to the stream and returns a reference to the stream.
Definition at line 95 of file qdebug.h.
Referenced by QDeclarativeInfo::operator<<().
 { stream->ts << '\'' << t << '\''; return maybeSpace(); }
operator<<() [2/22]
QDebug & QDebug::operator<< (QBool t) inline
Writes the boolean value, t, to the stream and returns a reference to the stream.
Warning
This function is not part of the public interface.
Definition at line 96 of file qdebug.h.
 { stream->ts << (bool(t != 0) ? "true" : "false"); return maybeSpace(); }
operator<<() [3/22]
QDebug & QDebug::operator<< (bool t) inline
Writes the boolean value, t, to the stream and returns a reference to the stream.
Definition at line 97 of file qdebug.h.
 { stream->ts << (t ? "true" : "false"); return maybeSpace(); }
operator<<() [4/22]
QDebug & QDebug::operator<< (char t) inline
Writes the character, t, to the stream and returns a reference to the stream.
Definition at line 98 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [5/22]
QDebug & QDebug::operator<< (signed short t) inline
Writes the signed short integer, i, to the stream and returns a reference to the stream.
Definition at line 99 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [6/22]
QDebug & QDebug::operator<< (unsigned short t) inline
Writes then unsigned short integer, i, to the stream and returns a reference to the stream.
Definition at line 100 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [7/22]
QDebug & QDebug::operator<< (signed int t) inline
Writes the signed integer, i, to the stream and returns a reference to the stream.
Definition at line 101 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [8/22]
QDebug & QDebug::operator<< (unsigned int t) inline
Writes then unsigned integer, i, to the stream and returns a reference to the stream.
Definition at line 102 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [9/22]
QDebug & QDebug::operator<< (signed long t) inline
Writes the signed long integer, l, to the stream and returns a reference to the stream.
Definition at line 103 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [10/22]
QDebug & QDebug::operator<< (unsigned long t) inline
Writes then unsigned long integer, l, to the stream and returns a reference to the stream.
Definition at line 104 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [11/22]
QDebug & QDebug::operator<< (qint64 t) inline
Writes the signed 64-bit integer, i, to the stream and returns a reference to the stream.
Definition at line 105 of file qdebug.h.
         { stream->ts << QString::number(t); return maybeSpace(); }
operator<<() [12/22]
QDebug & QDebug::operator<< (quint64 t) inline
Writes then unsigned 64-bit integer, i, to the stream and returns a reference to the stream.
Definition at line 107 of file qdebug.h.
         { stream->ts << QString::number(t); return maybeSpace(); }
operator<<() [13/22]
QDebug & QDebug::operator<< (float t) inline
Writes the 32-bit floating point number, f, to the stream and returns a reference to the stream.
Definition at line 109 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [14/22]
QDebug & QDebug::operator<< (double t) inline
Writes the 64-bit floating point number, f, to the stream and returns a reference to the stream.
Definition at line 110 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [15/22]
QDebug & QDebug::operator<< (const char * t) inline
Writes the '\0'-terminated string, s, to the stream and returns a reference to the stream.
Definition at line 111 of file qdebug.h.
 { stream->ts << QString::fromAscii(t); return maybeSpace(); }
operator<<() [16/22]
QDebug & QDebug::operator<< (const QString & t) inline
Writes the string, s, to the stream and returns a reference to the stream.
Definition at line 112 of file qdebug.h.
 { stream->ts << '\"' << t  << '\"'; return maybeSpace(); }
operator<<() [17/22]
QDebug & QDebug::operator<< (const QStringRef & t) inline
Writes the string reference, s, to the stream and returns a reference to the stream.
Definition at line 113 of file qdebug.h.
Referenced by operator<<().
 { return operator<<(t.toString()); }
operator<<() [18/22]
QDebug & QDebug::operator<< (const QLatin1String & t) inline
Writes the Latin1-encoded string, s, to the stream and returns a reference to the stream.
Definition at line 114 of file qdebug.h.
 { stream->ts << '\"'  << t.latin1() << '\"'; return maybeSpace(); }
operator<<() [19/22]
QDebug & QDebug::operator<< (const QByteArray & t) inline
Writes the byte array, b, to the stream and returns a reference to the stream.
Definition at line 115 of file qdebug.h.
 { stream->ts  << '\"' << t << '\"'; return maybeSpace(); }
operator<<() [20/22]
QDebug & QDebug::operator<< (const void * t) inline
Writes a pointer, p, to the stream and returns a reference to the stream.
Definition at line 116 of file qdebug.h.
 { stream->ts << t; return maybeSpace(); }
operator<<() [21/22]
QDebug & QDebug::operator<< (QTextStreamFunction f) inline
Warning
This function is not part of the public interface.
Definition at line 117 of file qdebug.h.
{
         stream->ts << f;
         return *this;
     }
operator<<() [22/22]
QDebug & QDebug::operator<< (QTextStreamManipulator m) inline
Warning
This function is not part of the public interface.
Definition at line 122 of file qdebug.h.
     { stream->ts << m; return *this; }
operator=()
QDebug & QDebug::operator= (const QDebug & other) inline
Assigns the other debug stream to this stream and returns a reference to this stream.
Definition at line 146 of file qdebug.h.
 {
     if (this != &other) {
         QDebug copy(other);
         qSwap(stream, copy.stream);
     }
     return *this;
 }
space()
QDebug & QDebug::space () inline
Writes a space character to the debug stream and returns a reference to the stream.
The stream will record that the last character sent to the stream was a space.
See also
nospace(), maybeSpace()
Definition at line 91 of file qdebug.h.
Referenced by operator<<().
 { stream->space = true; stream->ts << ' '; return *this; }
Properties
stream
struct QDebug::Stream * QDebug::stream private
Referenced by operator=().
The documentation for this class was generated from the following files:
/src/corelib/io/qdebug.h
/src/corelib/io/qdebug.cpp