Qt 4.8: QPatternist::Item Class Reference
QPatternist::Item Class Reference
Represents an item in the XPath 2.0 Data Model.
#include <qitem_p.h>
Public Types
typedef QPatternist::EmptyIterator< Item > EmptyIterator
typedef QAbstractXmlForwardIterator< Item > Iterator
typedef QList< Item > List
typedef QPatternist::SingletonIterator< Item > SingletonIterator
typedef QVector< Item > Vector
Public Functions
template<typename TCastTarget >
TCastTarget * as () const
const AtomicValue * asAtomicValue () const
const QXmlNodeModelIndex & asNode () const
bool isAtomicValue () const
Determines whether this item is an atomic value, or a node.
bool isNode () const
Determines whether this item is an atomic value, or a node.
bool isNull () const
Item ()
Item (const QXmlNodeModelIndex &n)
Item (const Item &other)
Item (const AtomicValue::Ptr &a)
Item (const AtomicValue *const a)
operator bool () const
Item & operator= (const Item &other)
void reset ()
Item::Iterator::Ptr sequencedTypedValue () const
Returns the typed value of this item.
QString stringValue () const
Returns the string value of this Item.
QExplicitlySharedDataPointer< ItemType > type () const
Returns the ItemType this Item is of.
~Item ()
Static Public Functions
static Item fromPublic (const QXmlItem &i)
static QXmlItem toPublic (const Item &i)
Properties
union {
const AtomicValue * atomicValue
NodeIndexStorage node
};
Friends
class ::QXmlItem
Detailed Description
Represents an item in the XPath 2.0 Data Model.
There exists two types of items: nodes and atomic values.
The XQuery 1.0 and XPath 2.0 Data Model and XML Path Language (XPath) 2.0 specification makes a very strong distinction between a sequence of items and an atomized sequence.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 182 of file qitem_p.h.
Typedefs
EmptyIterator
typedef QPatternist::EmptyIterator<Item> QPatternist::Item::EmptyIterator
Definition at line 203 of file qitem_p.h.
Iterator
typedef QAbstractXmlForwardIterator<Item> QPatternist::Item::Iterator
A smart pointer wrapping an Item instance.
Definition at line 190 of file qitem_p.h.
List
typedef QList<Item> QPatternist::Item::List
A list of Item instances, each wrapped in a smart pointer.
Definition at line 195 of file qitem_p.h.
SingletonIterator
typedef QPatternist::SingletonIterator<Item> QPatternist::Item::SingletonIterator
Definition at line 202 of file qitem_p.h.
Vector
typedef QVector<Item> QPatternist::Item::Vector
A vector of Item instances, each wrapped in a smart pointer.
Definition at line 200 of file qitem_p.h.
Constructors and Destructors
Item() [1/5]
QPatternist::Item::Item () inline
Default constructor.
Definition at line 208 of file qitem_p.h.
Referenced by sequencedTypedValue().
         {
             node.reset();
         }
Item() [2/5]
QPatternist::Item::Item (const QXmlNodeModelIndex & n) inline
Definition at line 213 of file qitem_p.h.
                                                  : node(n.m_storage)
         {
         }
Item() [3/5]
QPatternist::Item::Item (const Item & other) inline
Definition at line 217 of file qitem_p.h.
                                        : node(other.node)
         {
             Q_ASSERT_X(sizeof(QXmlNodeModelIndex) >= sizeof(AtomicValue), Q_FUNC_INFO,
                        "Since we're only copying the node member, it must be the largest.");
             if(isAtomicValue())
                 atomicValue->ref.ref();
         }
Item() [4/5]
QPatternist::Item::Item (const AtomicValue::Ptr & a) inline
Definition at line 225 of file qitem_p.h.
         {
             node.reset();
             if(a)
             {
                 atomicValue = a.data();
                 atomicValue->ref.ref();
                 /* Signal that we're housing an atomic value. */
                 node.model = reinterpret_cast<const QAbstractXmlNodeModel *>(~0);
             }
         }
Item() [5/5]
QPatternist::Item::Item (const AtomicValue *const a) inline
Definition at line 238 of file qitem_p.h.
         {
             /* Note, the implementation is a copy of the constructor above. */
             node.reset();
             if(a)
             {
                 atomicValue = a;
                 atomicValue->ref.ref();
                 /* Signal that we're housing an atomic value. */
                 node.model = reinterpret_cast<const QAbstractXmlNodeModel *>(~0);
             }
         }
~Item()
QPatternist::Item::~Item () inline
Definition at line 252 of file qitem_p.h.
         {
             if(isAtomicValue() && !atomicValue->ref.deref())
                 delete atomicValue;
         }
Functions
as()
template<typename TCastTarget > TCastTarget* QPatternist::Item::as () const inline
Definition at line 278 of file qitem_p.h.
Referenced by QPatternist::ComparingAggregator< oper, result >::applyNumericPromotion(), QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), QPatternist::DurationNumericMathematician::calculate(), QPatternist::DurationDurationMathematician::calculate(), QPatternist::DateTimeDurationMathematician::calculate(), QPatternist::AbstractDateTimeMathematician::calculate(), QPatternist::HexBinaryToBase64BinaryCaster::castFrom(), QPatternist::Base64BinaryToHexBinaryCaster::castFrom(), QPatternist::NumericToBooleanCaster::castFrom(), QPatternist::BooleanToDecimalCaster::castFrom(), QPatternist::BooleanToIntegerCaster::castFrom(), QPatternist::AbstractDateTimeToGYearCaster::castFrom(), QPatternist::AbstractDateTimeToGYearMonthCaster::castFrom(), QPatternist::AbstractDateTimeToGMonthCaster::castFrom(), QPatternist::AbstractDateTimeToGMonthDayCaster::castFrom(), QPatternist::AbstractDateTimeToGDayCaster::castFrom(), QPatternist::AbstractDateTimeToDateTimeCaster::castFrom(), QPatternist::AbstractDateTimeToDateCaster::castFrom(), QPatternist::AbstractDateTimeToTimeCaster::castFrom(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::AbstractDurationToYearMonthDurationCaster::castFrom(), QPatternist::CastAs::castToQName(), QPatternist::BooleanComparator::compare(), QPatternist::AbstractFloatComparator::compare(), QPatternist::DecimalComparator::compare(), QPatternist::IntegerComparator::compare(), QPatternist::AbstractDateTimeComparator::compare(), QPatternist::AbstractDurationComparator::compare(), QPatternist::BinaryDataComparator::equals(), QPatternist::BooleanComparator::equals(), QPatternist::AbstractFloatComparator::equals(), QPatternist::DecimalComparator::equals(), QPatternist::IntegerComparator::equals(), QPatternist::QNameComparator::equals(), QPatternist::AbstractDateTimeComparator::equals(), QPatternist::AbstractDurationComparator::equals(), QPatternist::Boolean::evaluateEBV(), QPatternist::CastableAs::evaluateEBV(), QPatternist::InsertBeforeFN::evaluateSequence(), QPatternist::RemoveFN::evaluateSequence(), QPatternist::SubsequenceFN::evaluateSequence(), QPatternist::FunctionAvailableFN::evaluateSingleton(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::UnaryExpression::evaluateSingleton(), QPatternist::PrefixFromQNameFN::evaluateSingleton(), QPatternist::SubstringFN::evaluateSingleton(), QPatternist::LocalNameFromQNameFN::evaluateSingleton(), QPatternist::NumberFN::evaluateSingleton(), QPatternist::NamespaceURIFromQNameFN::evaluateSingleton(), QPatternist::RoundHalfToEvenFN::evaluateSingleton(), QPatternist::RemoveFN::evaluateSingleton(), qLess< Item::List >::isNaN(), QPatternist::OrderBy::mapToSequence(), and qLess< Item::List >::operator()().
         {
 #if defined(Patternist_DEBUG) && !defined(Q_CC_XLC)
 /* At least on aix-xlc-64, the compiler cries when it sees dynamic_cast. */
             Q_ASSERT_X(atomicValue == 0 || dynamic_cast<const TCastTarget *>(atomicValue),
                        Q_FUNC_INFO,
                        "The cast is invalid. This class does not inherit the cast target.");
 #endif
             return const_cast<TCastTarget *>(static_cast<const TCastTarget *>(atomicValue));
         }
asAtomicValue()
const AtomicValue* QPatternist::Item::asAtomicValue () const inline
Definition at line 373 of file qitem_p.h.
Referenced by fromPublic(), QAbstractXmlReceiver::item(), and QXmlItem::QXmlItem().
         {
             Q_ASSERT(isAtomicValue());
             return atomicValue;
         }
asNode()
const QXmlNodeModelIndex& QPatternist::Item::asNode () const inline
Definition at line 379 of file qitem_p.h.
Referenced by QPatternist::AxisStep::evaluateSequence(), QPatternist::UnparsedEntityPublicIDFN::evaluateSingleton(), QPatternist::UnparsedEntityURIFN::evaluateSingleton(), QPatternist::GenerateIDFN::evaluateSingleton(), QPatternist::AxisStep::evaluateSingleton(), QPatternist::ParentNodeAxis::evaluateSingleton(), QPatternist::LangFN::evaluateSingleton(), QPatternist::RootFN::evaluateSingleton(), QPatternist::BuiltinNodeType< kind >::itemMatches(), QPatternist::XSLTNodeTest::itemMatches(), QPatternist::LocalNameTest::itemMatches(), QPatternist::NamespaceNameTest::itemMatches(), QPatternist::QNameTest::itemMatches(), QPatternist::NodeSortExpression::lessThanUsingNodeModel(), QPatternist::ExceptIterator::next(), QPatternist::UnionIterator::next(), QPatternist::IntersectIterator::next(), QPatternist::DeduplicateIterator::next(), QPatternist::XSLTSimpleContentConstructor::processItem(), QAbstractXmlReceiver::sendAsNode(), QPatternist::QAbstractXmlReceiver::sendAsNode(), and sequencedTypedValue().
         {
             Q_ASSERT_X(isNode() || isNull(), Q_FUNC_INFO,
                        "This item isn't a valid QXmlNodeModelIndex.");
             Q_ASSERT_X(sizeof(QXmlNodeModelIndex) == sizeof(QPatternist::NodeIndexStorage), Q_FUNC_INFO,
                        "If this doesn't hold, something is wrong.");
             return reinterpret_cast<const QXmlNodeModelIndex &>(node);
         }
fromPublic()
static Item QPatternist::Item::fromPublic (const QXmlItem & i) inline static
Definition at line 408 of file qitem_p.h.
Referenced by QXmlQueryPrivate::dynamicContext(), QXmlItem::isNode(), and QPatternist::VariableLoader::itemForName().
         {
             const Item it(i.m_node);
             if(it.isAtomicValue())
                 it.asAtomicValue()->ref.ref();
             return it;
         }
isAtomicValue()
bool QPatternist::Item::isAtomicValue () const inline
Determines whether this item is an atomic value, or a node.
If this Item is null, false is returned.
See also
isNode()
Returns
true if it is an atomic value, otherwise false.
Definition at line 335 of file qitem_p.h.
Referenced by QPatternist::Path::evaluateSequence(), fromPublic(), QPatternist::Literal::id(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::issueCastError(), QXmlFormatter::item(), QXmlSerializer::item(), QPatternist::AccelTreeBuilder< true >::item(), QPatternist::Literal::Literal(), QPatternist::ArgumentConverter::mapToSequence(), QPatternist::PullBridge::next(), operator=(), and sequencedTypedValue().
         {
             /* Setting node.model to ~0, signals that it's an atomic value. */
             return node.model == reinterpret_cast<QAbstractXmlNodeModel *>(~0);
         }
isNode()
bool QPatternist::Item::isNode () const inline
Determines whether this item is an atomic value, or a node.
If this Item is null, false is returned.
See also
isAtomicValue()
Returns
true if this item is a node, otherwise false.
Definition at line 349 of file qitem_p.h.
Referenced by QPatternist::Boolean::evaluateEBV(), QXmlItem::isNode(), QAbstractXmlReceiver::item(), QXmlSerializer::item(), QPatternist::DocumentContentValidator::item(), QPatternist::OutputValidator::item(), QPatternist::NumericType::itemMatches(), QPatternist::AnyNodeType::itemMatches(), QPatternist::BuiltinNodeType< kind >::itemMatches(), QPatternist::XSLTNodeTest::itemMatches(), QPatternist::NamespaceNameTest::itemMatches(), QPatternist::QNameTest::itemMatches(), QPatternist::LocalNameTest::itemMatches(), QPatternist::EBVType::itemMatches(), QPatternist::AtomicType::itemMatches(), QPatternist::NodeSortExpression::lessThanUsingNodeModel(), QPatternist::PullBridge::next(), QPatternist::XSLTSimpleContentConstructor::processItem(), QAbstractXmlReceiver::sendAsNode(), and QPatternist::QAbstractXmlReceiver::sendAsNode().
         {
             //return !isAtomicValue();
             return node.model && node.model != reinterpret_cast<QAbstractXmlNodeModel *>(~0);
         }
isNull()
bool QPatternist::Item::isNull () const inline
Definition at line 394 of file qitem_p.h.
         {
             return !node.model;
         }
operator bool()
QPatternist::Item::operator bool () const inline
Definition at line 389 of file qitem_p.h.
         {
             return node.model;
         }
operator=()
Item& QPatternist::Item::operator= (const Item & other) inline
Definition at line 258 of file qitem_p.h.
         {
             Q_ASSERT_X(sizeof(QXmlNodeModelIndex) >= sizeof(AtomicValue *), Q_FUNC_INFO,
                        "If this doesn't hold, we won't copy all data.");
             if(other.isAtomicValue())
                 other.atomicValue->ref.ref();
             if(isAtomicValue())
             {
                 if(!atomicValue->ref.deref())
                     delete atomicValue;
             }
             node = other.node;
             return *this;
         }
reset()
void QPatternist::Item::reset () inline
Definition at line 399 of file qitem_p.h.
Referenced by QPatternist::UnionIterator::next(), QPatternist::ToCodepointsIterator::next(), QPatternist::SubsequenceIterator::next(), QPatternist::RemovalIterator::next(), QPatternist::InsertionIterator::next(), QPatternist::IndexOfIterator::next(), QPatternist::DistinctIterator::next(), and QPatternist::RangeIterator::next().
         {
             /* Delete the atomicValue if necessary*/
             if(isAtomicValue() && !atomicValue->ref.deref())
                 delete atomicValue;
             node.reset();
         }
sequencedTypedValue()
Item::Iterator::Ptr Item::sequencedTypedValue () const
Returns the typed value of this item.
Conceptually, this functions corresponds to the dm:typed-value accessor. Here are examples of what the typed value of an Item is:
The typed value of an atomic value is always the atomic value itself.
A comment node has always a typed value of type xs:string
For attribute and element nodes, the typed value can be arbitrary. For example, an element can have a sequence of xs:dateTime instances.
Returns
the typed value of this item
See also
XQuery 1.0 and XPath 2.0 Data Model, 5.15 typed-value Accessor
Definition at line 50 of file qitem.cpp.
Referenced by QPatternist::ArgumentConverter::mapToSequence(), QPatternist::Atomizer::mapToSequence(), and QPatternist::XSLTSimpleContentConstructor::processItem().
 {
     if(isAtomicValue())
         return makeSingletonIterator(Item(atomicValue));
     else
         return asNode().sequencedTypedValue();
 }
stringValue()
QString QPatternist::Item::stringValue () const inline
Returns the string value of this Item.
In the case of a node, it is the node value corresponding to the particular node type. For atomic values, it is equivalent to the value cast as xs:string.
Conceptually, this functions corresponds to the dm:string-value accessor.
See also
XQuery 1.0 and XPath 2.0 Data Model, 5.13 string-value Accessor
Returns
the string value.
Definition at line 302 of file qitem_p.h.
Referenced by QPatternist::ToStringCaster< DerivedType >::castFrom(), QPatternist::StringToAbstractFloatCaster< isDouble >::castFrom(), QPatternist::ToUntypedAtomicCaster::castFrom(), QPatternist::ToAnyURICaster::castFrom(), QPatternist::StringToBase64BinaryCaster::castFrom(), QPatternist::StringToHexBinaryCaster::castFrom(), QPatternist::StringToBooleanCaster::castFrom(), QPatternist::StringToDecimalCaster::castFrom(), QPatternist::StringToIntegerCaster::castFrom(), QPatternist::StringToGYearCaster::castFrom(), QPatternist::StringToGDayCaster::castFrom(), QPatternist::StringToGMonthCaster::castFrom(), QPatternist::StringToGYearMonthCaster::castFrom(), QPatternist::StringToGMonthDayCaster::castFrom(), QPatternist::StringToDateTimeCaster::castFrom(), QPatternist::StringToTimeCaster::castFrom(), QPatternist::StringToDateCaster::castFrom(), QPatternist::StringToDurationCaster::castFrom(), QPatternist::StringToDayTimeDurationCaster::castFrom(), QPatternist::StringToYearMonthDurationCaster::castFrom(), QPatternist::StringToDerivedIntegerCaster< type >::castFrom(), QPatternist::AnyToDerivedStringCaster< type >::castFrom(), QPatternist::StringComparator::compare(), QPatternist::CaseInsensitiveStringComparator::compare(), QPatternist::PatternPlatform::compress(), QPatternist::Literal::description(), QPatternist::NormalizeUnicodeFN::determineNormalizationForm(), QPatternist::StringComparator::equals(), QPatternist::CaseInsensitiveStringComparator::equals(), QPatternist::ResolveURIFN::evaluateSingleton(), QPatternist::SystemPropertyFN::evaluateSingleton(), QPatternist::FunctionAvailableFN::evaluateSingleton(), QPatternist::TypeAvailableFN::evaluateSingleton(), QPatternist::NCNameConstructor::evaluateSingleton(), QPatternist::QNameConstructor::evaluateSingleton(), QPatternist::ErrorFN::evaluateSingleton(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::ConcatFN::evaluateSingleton(), QPatternist::TranslateFN::evaluateSingleton(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::issueCastError(), QXmlFormatter::item(), QXmlSerializer::item(), QPatternist::AccelTreeBuilder< true >::item(), QPatternist::TraceCallback::mapToItem(), QPatternist::ReplaceFN::parseReplacement(), QPatternist::PatternPlatform::pattern(), QPatternist::XSLTSimpleContentConstructor::processItem(), QPatternist::AttributeConstructor::processValue(), QAbstractXmlReceiver::sendAsNode(), QPatternist::QAbstractXmlReceiver::sendAsNode(), QPatternist::DocFN::typeCheck(), and QPatternist::ItemVerifier::verifyItem().
         {
             if(isAtomicValue())
                 return atomicValue->stringValue();
             else
                 return asNode().stringValue();
         }
toPublic()
static QXmlItem QPatternist::Item::toPublic (const Item & i) inline static
Definition at line 417 of file qitem_p.h.
Referenced by QXmlResultItems::next().
         {
             return QXmlItem(i);
         }
type()
QExplicitlySharedDataPointer<ItemType> QPatternist::Item::type () const inline
Returns the ItemType this Item is of.
For example, if this Item is an XML node, more specifically a text node, text() is returned. That is, BuiltinTypes::text. However, if this Item is an atomic value of type xs:long that is what's returned, BuiltinTypes::xsLong.
Returns
the type of this Item.
Definition at line 365 of file qitem_p.h.
Referenced by QPatternist::ComparingAggregator< oper, result >::applyNumericPromotion(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::cast(), QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), QPatternist::NumericToDerivedIntegerCaster< type >::castFrom(), QPatternist::ComparisonPlatform< IndexOfIterator, false >::detailedFlexibleCompare(), QPatternist::ComparisonPlatform< IndexOfIterator, false >::flexibleCompare(), QPatternist::Literal::id(), qLess< Item::List >::isNaN(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::issueCastError(), QPatternist::AtomicType::itemMatches(), QPatternist::ArgumentConverter::mapToSequence(), and QPatternist::Literal::staticType().
         {
             if(isAtomicValue())
                 return atomicValue->type();
             else
                 return asNode().type();
         }
Friends and Related Functions
::QXmlItem
friend class :: QXmlItem friend
Definition at line 184 of file qitem_p.h.
Properties
@379
union { ... }
atomicValue
const AtomicValue* QPatternist::Item::atomicValue
Definition at line 426 of file qitem_p.h.
Referenced by operator=(), and sequencedTypedValue().
node
NodeIndexStorage QPatternist::Item::node
Definition at line 425 of file qitem_p.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qitem_p.h
/src/xmlpatterns/data/qitem.cpp