Qt 4.8: QToolBarAreaLayout Class Reference
QToolBarAreaLayout Class Reference
#include <qtoolbararealayout_p.h>
Public Types
enum { ToolBarStateMarker = 0xfe, ToolBarStateMarkerEx = 0xfc }
Public Functions
QLayoutItem * addToolBar (QInternal::DockPosition pos, QToolBar *toolBar)
void addToolBarBreak (QInternal::DockPosition pos)
void apply (bool animate)
void clear ()
QList< int > currentGapIndex () const
void deleteAllLayoutItems ()
QInternal::DockPosition findToolBar (QToolBar *toolBar) const
QRect fitLayout ()
QList< int > gapIndex (const QPoint &pos) const
void getStyleOptionInfo (QStyleOptionToolBar *option, QToolBar *toolBar) const
QList< int > indexOf (QWidget *toolBar) const
bool insertGap (const QList< int > &path, QLayoutItem *item)
void insertItem (QInternal::DockPosition pos, QLayoutItem *item)
void insertItem (QToolBar *before, QLayoutItem *item)
QLayoutItem * insertToolBar (QToolBar *before, QToolBar *toolBar)
void insertToolBarBreak (QToolBar *before)
bool isEmpty () const
QToolBarAreaLayoutItem * item (const QList< int > &path)
QLayoutItem * itemAt (int *x, int index) const
QRect itemRect (const QList< int > &path) const
QSize minimumSize (const QSize &centerMin) const
void moveToolBar (QToolBar *toolbar, int pos)
QLayoutItem * plug (const QList< int > &path)
QToolBarAreaLayout (const QMainWindow *win)
QRect rectHint (const QRect &r) const
void remove (const QList< int > &path)
void remove (QLayoutItem *item)
void removeToolBar (QToolBar *toolBar)
void removeToolBarBreak (QToolBar *before)
bool restoreState (QDataStream &stream, const QList< QToolBar *> &toolBars, uchar tmarker, bool pre43, bool testing=false)
void saveState (QDataStream &stream) const
QSize sizeHint (const QSize &center) const
QLayoutItem * takeAt (int *x, int index)
bool toolBarBreak (QToolBar *toolBar) const
QLayoutItem * unplug (const QList< int > &path, QToolBarAreaLayout *other)
Public Variables
QToolBarAreaLayoutInfo docks [4]
const QMainWindow * mainWindow
QRect rect
bool visible
Detailed Description
Definition at line 186 of file qtoolbararealayout_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
ToolBarStateMarker
ToolBarStateMarkerEx
Definition at line 189 of file qtoolbararealayout_p.h.
          { // sentinel values used to validate state data
         ToolBarStateMarker = 0xfe,
         ToolBarStateMarkerEx = 0xfc
     };
Constructors and Destructors
QToolBarAreaLayout()
QToolBarAreaLayout::QToolBarAreaLayout (const QMainWindow * win)
Definition at line 625 of file qtoolbararealayout.cpp.
                                                              : mainWindow(win), visible(true)
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QInternal::DockPosition pos = static_cast<QInternal::DockPosition>(i);
         docks[i] = QToolBarAreaLayoutInfo(pos);
     }
 }
Functions
addToolBar()
QLayoutItem * QToolBarAreaLayout::addToolBar (QInternal::DockPosition pos, QToolBar * toolBar)
Definition at line 825 of file qtoolbararealayout.cpp.
 {
     return docks[pos].insertToolBar(0, toolBar);
 }
addToolBarBreak()
void QToolBarAreaLayout::addToolBarBreak (QInternal::DockPosition pos)
Definition at line 846 of file qtoolbararealayout.cpp.
 {
     docks[pos].insertToolBarBreak(0);
 }
apply()
void QToolBarAreaLayout::apply (bool animate)
Definition at line 876 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::apply(), and QToolBarLayout::setExpanded().
 {
     QMainWindowLayout *layout = qt_mainwindow_layout(mainWindow);
     Q_ASSERT(layout != 0);
     Qt::LayoutDirection dir = mainWindow->layoutDirection();
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             if (line.skip())
                 continue;
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 const QToolBarAreaLayoutItem &item = line.toolBarItems.at(k);
                 if (item.skip() || item.gap)
                     continue;
                 QRect geo;
                 if (visible) {
                     if (line.o == Qt::Horizontal) {
                         geo.setTop(line.rect.top());
                         geo.setBottom(line.rect.bottom());
                         geo.setLeft(line.rect.left() + item.pos);
                         geo.setRight(line.rect.left() + item.pos + item.size - 1);
                     } else {
                         geo.setLeft(line.rect.left());
                         geo.setRight(line.rect.right());
                         geo.setTop(line.rect.top() + item.pos);
                         geo.setBottom(line.rect.top() + item.pos + item.size - 1);
                     }
                 }
                 QWidget *widget = item.widgetItem->widget();
                 if (QToolBar *toolBar = qobject_cast<QToolBar*>(widget)) {
                     QToolBarLayout *tbl = qobject_cast<QToolBarLayout*>(toolBar->layout());
                     if (tbl->expanded) {
                         QPoint tr = geo.topRight();
                         QSize size = tbl->expandedSize(geo.size());
                         geo.setSize(size);
                         geo.moveTopRight(tr);
                         if (geo.bottom() > rect.bottom())
                             geo.moveBottom(rect.bottom());
                         if (geo.right() > rect.right())
                             geo.moveRight(rect.right());
                         if (geo.left() < 0)
                             geo.moveLeft(0);
                         if (geo.top() < 0)
                             geo.moveTop(0);
                     }
                 }
                 if (visible && dock.o == Qt::Horizontal)
                     geo = QStyle::visualRect(dir, line.rect, geo);
                 layout->widgetAnimator.animate(widget, geo, animate);
             }
         }
     }
 }
clear()
void QToolBarAreaLayout::clear ()
Definition at line 1102 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::clear().
 {
     for (int i = 0; i < QInternal::DockCount; ++i)
         docks[i].clear();
     rect = QRect();
 }
currentGapIndex()
QList< int > QToolBarAreaLayout::currentGapIndex () const
Definition at line 1048 of file qtoolbararealayout.cpp.
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines[j];
             for (int k = 0; k < line.toolBarItems.count(); k++) {
                 if (line.toolBarItems[k].gap) {
                     QList<int> result;
                     result << i << j << k;
                     return result;
                 }
             }
         }
     }
     return QList<int>();
 }
deleteAllLayoutItems()
void QToolBarAreaLayout::deleteAllLayoutItems ()
Definition at line 772 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::deleteAllLayoutItems().
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             QToolBarAreaLayoutLine &line = dock.lines[j];
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 QToolBarAreaLayoutItem &item = line.toolBarItems[k];
                 if (!item.gap)
                     delete item.widgetItem;
                 item.widgetItem = 0;
             }
         }
     }
 }
findToolBar()
QInternal::DockPosition QToolBarAreaLayout::findToolBar (QToolBar * toolBar) const
Definition at line 790 of file qtoolbararealayout.cpp.
Referenced by insertItem(), insertToolBar(), insertToolBarBreak(), moveToolBar(), removeToolBar(), and removeToolBarBreak().
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 if (line.toolBarItems.at(k).widgetItem->widget() == toolBar)
                     return static_cast<QInternal::DockPosition>(i);
             }
         }
     }
     return QInternal::DockCount;
 }
fitLayout()
QRect QToolBarAreaLayout::fitLayout ()
Definition at line 633 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::fitLayout().
 {
     if (!visible)
         return rect;
     QSize left_hint = docks[QInternal::LeftDock].sizeHint();
     QSize right_hint = docks[QInternal::RightDock].sizeHint();
     QSize top_hint = docks[QInternal::TopDock].sizeHint();
     QSize bottom_hint = docks[QInternal::BottomDock].sizeHint();
     QRect center = rect.adjusted(left_hint.width(), top_hint.height(),
                                     -right_hint.width(), -bottom_hint.height());
     docks[QInternal::TopDock].rect = QRect(rect.left(), rect.top(),
                                 rect.width(), top_hint.height());
     docks[QInternal::LeftDock].rect = QRect(rect.left(), center.top(),
                                 left_hint.width(), center.height());
     docks[QInternal::RightDock].rect = QRect(center.right() + 1, center.top(),
                                     right_hint.width(), center.height());
     docks[QInternal::BottomDock].rect = QRect(rect.left(), center.bottom() + 1,
                                     rect.width(), bottom_hint.height());
     if (!mainWindow->unifiedTitleAndToolBarOnMac()) {
         docks[QInternal::TopDock].fitLayout();
     }
     docks[QInternal::LeftDock].fitLayout();
     docks[QInternal::RightDock].fitLayout();
     docks[QInternal::BottomDock].fitLayout();
     return center;
 }
gapIndex()
QList< int > QToolBarAreaLayout::gapIndex (const QPoint & pos) const
Definition at line 1029 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::gapIndex().
 {
     Qt::LayoutDirection dir = mainWindow->layoutDirection();
     int minDistance = 80; // when a dock area is empty, how "wide" is it?
     QList<int> ret; //return value
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QPoint p = pos;
         if (docks[i].o == Qt::Horizontal)
             p = QStyle::visualPos(dir, docks[i].rect, p);
         QList<int> result = docks[i].gapIndex(p, &minDistance);
         if (!result.isEmpty()) {
             result.prepend(i);
             ret = result;
         }
     }
     return ret;
 }
getStyleOptionInfo()
void QToolBarAreaLayout::getStyleOptionInfo (QStyleOptionToolBar * option, QToolBar * toolBar) const
Definition at line 957 of file qtoolbararealayout.cpp.
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 if (line.toolBarItems.at(k).widgetItem->widget() == toolBar) {
                     if (line.toolBarItems.count() == 1)
                         option->positionWithinLine = QStyleOptionToolBar::OnlyOne;
                     else if (k == 0)
                         option->positionWithinLine = QStyleOptionToolBar::Beginning;
                     else if (k == line.toolBarItems.count() - 1)
                         option->positionWithinLine = QStyleOptionToolBar::End;
                     else
                         option->positionWithinLine = QStyleOptionToolBar::Middle;
                     if (dock.lines.count() == 1)
                         option->positionOfLine = QStyleOptionToolBar::OnlyOne;
                     else if (j == 0)
                         option->positionOfLine = QStyleOptionToolBar::Beginning;
                     else if (j == dock.lines.count() - 1)
                         option->positionOfLine = QStyleOptionToolBar::End;
                     else
                         option->positionOfLine = QStyleOptionToolBar::Middle;
                     return;
                 }
             }
         }
     }
 }
indexOf()
QList< int > QToolBarAreaLayout::indexOf (QWidget * toolBar) const
Definition at line 992 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::contains(), QMainWindowLayoutState::indexOf(), and QMainWindowLayoutState::restoreState().
 {
     QList<int> result;
     bool found = false;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 const QToolBarAreaLayoutItem &item = line.toolBarItems.at(k);
                 if (!item.gap && item.widgetItem->widget() == toolBar) {
                     found = true;
                     result.prepend(k);
                     break;
                 }
             }
             if (found) {
                 result.prepend(j);
                 break;
             }
         }
         if (found) {
             result.prepend(i);
             break;
         }
     }
     return result;
 }
insertGap()
bool QToolBarAreaLayout::insertGap (const QList< int > & path, QLayoutItem * item)
Definition at line 1068 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::insertGap().
 {
     Q_ASSERT(path.count() == 3);
     const int i = path.first();
     Q_ASSERT(i >= 0 && i < QInternal::DockCount);
     return docks[i].insertGap(path.mid(1), item);
 }
insertItem() [1/2]
void QToolBarAreaLayout::insertItem (QInternal::DockPosition pos, QLayoutItem * item)
Definition at line 860 of file qtoolbararealayout.cpp.
 {
     if (docks[pos].lines.isEmpty())
         docks[pos].lines.append(QToolBarAreaLayoutLine(docks[pos].o));
     docks[pos].lines.last().toolBarItems.append(item);
 }
insertItem() [2/2]
void QToolBarAreaLayout::insertItem (QToolBar * before, QLayoutItem * item)
Definition at line 867 of file qtoolbararealayout.cpp.
 {
     QInternal::DockPosition pos = findToolBar(before);
     if (pos == QInternal::DockCount)
         return;
     docks[pos].insertItem(before, item);
 }
insertToolBar()
QLayoutItem * QToolBarAreaLayout::insertToolBar (QToolBar * before, QToolBar * toolBar)
Definition at line 808 of file qtoolbararealayout.cpp.
 {
     QInternal::DockPosition pos = findToolBar(before);
     if (pos == QInternal::DockCount)
         return 0;
     return docks[pos].insertToolBar(before, toolBar);
 }
insertToolBarBreak()
void QToolBarAreaLayout::insertToolBarBreak (QToolBar * before)
Definition at line 830 of file qtoolbararealayout.cpp.
 {
     QInternal::DockPosition pos = findToolBar(before);
     if (pos == QInternal::DockCount)
         return;
     docks[pos].insertToolBarBreak(before);
 }
isEmpty()
bool QToolBarAreaLayout::isEmpty () const
Definition at line 1388 of file qtoolbararealayout.cpp.
Referenced by QToolBar::~QToolBar().
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         if (!docks[i].lines.isEmpty())
             return false;
     }
     return true;
 }
item()
QToolBarAreaLayoutItem * QToolBarAreaLayout::item (const QList< int > & path)
Definition at line 1109 of file qtoolbararealayout.cpp.
Referenced by apply(), deleteAllLayoutItems(), indexOf(), insertGap(), QMainWindowLayoutState::item(), plug(), restoreState(), saveState(), and unplug().
 {
     Q_ASSERT(path.count() == 3);
     if (path.at(0) < 0 || path.at(0) >= QInternal::DockCount)
         return 0;
     QToolBarAreaLayoutInfo &info = docks[path.at(0)];
     if (path.at(1) < 0 || path.at(1) >= info.lines.count())
         return 0;
     QToolBarAreaLayoutLine &line = info.lines[path.at(1)];
     if (path.at(2) < 0 || path.at(2) >= line.toolBarItems.count())
         return 0;
     return &(line.toolBarItems[path.at(2)]);
 }
itemAt()
QLayoutItem * QToolBarAreaLayout::itemAt (int * x, int index) const
Definition at line 728 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::itemAt().
 {
     Q_ASSERT(x != 0);
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 if ((*x)++ == index)
                     return line.toolBarItems.at(k).widgetItem;
             }
         }
     }
     return 0;
 }
itemRect()
QRect QToolBarAreaLayout::itemRect (const QList< int > & path) const
Definition at line 1124 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::gapRect(), and QMainWindowLayoutState::itemRect().
 {
     const int i = path.first();
     QRect r = docks[i].itemRect(path.mid(1));
     if (docks[i].o == Qt::Horizontal)
         r = QStyle::visualRect(mainWindow->layoutDirection(),
                                 docks[i].rect, r);
     return r;
 }
minimumSize()
QSize QToolBarAreaLayout::minimumSize (const QSize & centerMin) const
Definition at line 665 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::minimumSize().
 {
     if (!visible)
         return centerMin;
     QSize result = centerMin;
     QSize left_min = docks[QInternal::LeftDock].minimumSize();
     QSize right_min = docks[QInternal::RightDock].minimumSize();
     QSize top_min = docks[QInternal::TopDock].minimumSize();
     QSize bottom_min = docks[QInternal::BottomDock].minimumSize();
     result.setWidth(qMax(top_min.width(), result.width()));
     result.setWidth(qMax(bottom_min.width(), result.width()));
     result.setHeight(qMax(left_min.height(), result.height()));
     result.setHeight(qMax(right_min.height(), result.height()));
     result.rwidth() += left_min.width() + right_min.width();
     result.rheight() += top_min.height() + bottom_min.height();
     return result;
 }
moveToolBar()
void QToolBarAreaLayout::moveToolBar (QToolBar * toolbar, int pos)
Definition at line 851 of file qtoolbararealayout.cpp.
 {
     QInternal::DockPosition pos = findToolBar(toolbar);
     if (pos == QInternal::DockCount)
         return;
     docks[pos].moveToolBar(toolbar, p);
 }
plug()
QLayoutItem * QToolBarAreaLayout::plug (const QList< int > & path)
Definition at line 1135 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::plug().
 {
     QToolBarAreaLayoutItem *item = this->item(path);
     if (!item) {
         qWarning() << Q_FUNC_INFO << "No item at" << path;
         return 0;
     }
     Q_ASSERT(item->gap);
     Q_ASSERT(item->widgetItem != 0);
     item->gap = false;
     return item->widgetItem;
 }
rectHint()
QRect QToolBarAreaLayout::rectHint (const QRect & r) const
Definition at line 711 of file qtoolbararealayout.cpp.
 {
     int coef = visible ? 1 : -1;
     QRect result = r;
     QSize left_hint = docks[QInternal::LeftDock].sizeHint();
     QSize right_hint = docks[QInternal::RightDock].sizeHint();
     QSize top_hint = docks[QInternal::TopDock].sizeHint();
     QSize bottom_hint = docks[QInternal::BottomDock].sizeHint();
     result.adjust(-left_hint.width()*coef, -top_hint.height()*coef,
                     right_hint.width()*coef, bottom_hint.height()*coef);
     return result;
 }
remove() [1/2]
void QToolBarAreaLayout::remove (const QList< int > & path)
Definition at line 1076 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::remove().
 {
     Q_ASSERT(path.count() == 3);
     docks[path.at(0)].lines[path.at(1)].toolBarItems.removeAt(path.at(2));
 }
remove() [2/2]
void QToolBarAreaLayout::remove (QLayoutItem * item)
Definition at line 1082 of file qtoolbararealayout.cpp.
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             QToolBarAreaLayoutLine &line = dock.lines[j];
             for (int k = 0; k < line.toolBarItems.count(); k++) {
                 if (line.toolBarItems[k].widgetItem == item) {
                     line.toolBarItems.removeAt(k);
                     if (line.toolBarItems.isEmpty())
                         dock.lines.removeAt(j);
                     return;
                 }
             }
         }
     }
 }
removeToolBar()
void QToolBarAreaLayout::removeToolBar (QToolBar * toolBar)
Definition at line 817 of file qtoolbararealayout.cpp.
 {
     QInternal::DockPosition pos = findToolBar(toolBar);
     if (pos == QInternal::DockCount)
         return;
     docks[pos].removeToolBar(toolBar);
 }
removeToolBarBreak()
void QToolBarAreaLayout::removeToolBarBreak (QToolBar * before)
Definition at line 838 of file qtoolbararealayout.cpp.
 {
     QInternal::DockPosition pos = findToolBar(before);
     if (pos == QInternal::DockCount)
         return;
     docks[pos].removeToolBarBreak(before);
 }
restoreState()
bool QToolBarAreaLayout::restoreState (QDataStream & stream, const QList< QToolBar *> & toolBars, uchar tmarker, bool pre43, bool testing = false)
Definition at line 1310 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::checkFormat(), and QMainWindowLayoutState::restoreState().
 {
     QList<QToolBar*> toolBars = _toolBars;
     int lines;
     stream >> lines;
     if (!testing)
     testing = mainWindow->unifiedTitleAndToolBarOnMac();
     for (int j = 0; j < lines; ++j) {
         int pos;
         stream >> pos;
         if (pos < 0 || pos >= QInternal::DockCount)
             return false;
         int cnt;
         stream >> cnt;
         QToolBarAreaLayoutInfo &dock = docks[pos];
         const bool applyingLayout = !testing && !(pos == QInternal::TopDock && mainWindow->unifiedTitleAndToolBarOnMac());
         QToolBarAreaLayoutLine line(dock.o);
         for (int k = 0; k < cnt; ++k) {
             QToolBarAreaLayoutItem item;
             QString objectName;
             stream >> objectName;
             uchar shown;
             stream >> shown;
             item.pos = getInt(stream, dock.o, pre43);
             item.size = getInt(stream, dock.o, pre43);
             /*
                4.3.0 added floating toolbars, but failed to add the ability to restore them.
                We need to store there geometry (four ints). We cannot change the format in a
                patch release (4.3.1) by adding ToolBarStateMarkerEx2 to signal extra data. So
                for now we'll pack it in the two legacy ints we no longer used in Qt4.3.0.
                In 4.4, we should add ToolBarStateMarkerEx2 and fix this properly.
             */
             QRect rect;
             bool floating = false;
             uint geom0, geom1;
             geom0 = getInt(stream, dock.o, pre43);
             if (tmarker == ToolBarStateMarkerEx) {
                 geom1 = getInt(stream, dock.o, pre43);
                 rect = unpackRect(geom0, geom1, &floating);
             }
             QToolBar *toolBar = 0;
             for (int x = 0; x < toolBars.count(); ++x) {
                 if (toolBars.at(x)->objectName() == objectName) {
                     toolBar = toolBars.takeAt(x);
                     break;
                 }
             }
             if (toolBar == 0) {
                 continue;
             }
             if (applyingLayout) {
                 item.widgetItem = new QWidgetItemV2(toolBar);
                 toolBar->setOrientation(floating ? ((shown & 2) ? Qt::Vertical : Qt::Horizontal) : dock.o);
                 toolBar->setVisible(shown & 1);
                 toolBar->d_func()->setWindowState(floating, true, rect);
                 item.preferredSize = item.size;
                 line.toolBarItems.append(item);
             }
         }
         if (applyingLayout) {
             dock.lines.append(line);
         }
     }
     return stream.status() == QDataStream::Ok;
 }
saveState()
void QToolBarAreaLayout::saveState (QDataStream & stream) const
Definition at line 1247 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::saveState().
 {
     // save toolbar state
     stream << (uchar) ToolBarStateMarkerEx;
     int lineCount = 0;
     for (int i = 0; i < QInternal::DockCount; ++i)
         lineCount += docks[i].lines.count();
     stream << lineCount;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             stream << i << line.toolBarItems.count();
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 const QToolBarAreaLayoutItem &item = line.toolBarItems.at(k);
                 QWidget *widget = const_cast<QLayoutItem*>(item.widgetItem)->widget();
                 QString objectName = widget->objectName();
                 if (objectName.isEmpty()) {
                     qWarning("QMainWindow::saveState(): 'objectName' not set for QToolBar %p '%s'",
                                 widget, widget->windowTitle().toLocal8Bit().constData());
                 }
                 stream << objectName;
                 // we store information as:
                 // 1st bit: 1 if shown
                 // 2nd bit: 1 if orientation is vertical (default is horizontal)
                 uchar shownOrientation = (uchar)!widget->isHidden();
                 if (QToolBar * tb= qobject_cast<QToolBar*>(widget)) {
                     if (tb->orientation() == Qt::Vertical)
                         shownOrientation |= 2;
                 }
                 stream << shownOrientation;
                 stream << item.pos;
                 //we store the preferred size. If the use rdidn't resize the toolbars it will be -1
                 stream << item.preferredSize;
                 uint geom0, geom1;
                 packRect(&geom0, &geom1, widget->geometry(), widget->isWindow());
                 stream << geom0 << geom1;
             }
         }
     }
 }
sizeHint()
QSize QToolBarAreaLayout::sizeHint (const QSize & center) const
Definition at line 688 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::sizeHint().
 {
     if (!visible)
         return centerHint;
     QSize result = centerHint;
     QSize left_hint = docks[QInternal::LeftDock].sizeHint();
     QSize right_hint = docks[QInternal::RightDock].sizeHint();
     QSize top_hint = docks[QInternal::TopDock].sizeHint();
     QSize bottom_hint = docks[QInternal::BottomDock].sizeHint();
     result.setWidth(qMax(top_hint.width(), result.width()));
     result.setWidth(qMax(bottom_hint.width(), result.width()));
     result.setHeight(qMax(left_hint.height(), result.height()));
     result.setHeight(qMax(right_hint.height(), result.height()));
     result.rwidth() += left_hint.width() + right_hint.width();
     result.rheight() += top_hint.height() + bottom_hint.height();
     return result;
 }
takeAt()
QLayoutItem * QToolBarAreaLayout::takeAt (int * x, int index)
Definition at line 748 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::takeAt().
 {
     Q_ASSERT(x != 0);
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             QToolBarAreaLayoutLine &line = dock.lines[j];
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 if ((*x)++ == index) {
                     QLayoutItem *result = line.toolBarItems.takeAt(k).widgetItem;
                     if (line.toolBarItems.isEmpty())
                         dock.lines.removeAt(j);
                     return result;
                 }
             }
         }
     }
     return 0;
 }
toolBarBreak()
bool QToolBarAreaLayout::toolBarBreak (QToolBar * toolBar) const
Definition at line 939 of file qtoolbararealayout.cpp.
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QToolBarAreaLayoutInfo &dock = docks[i];
         for (int j = 0; j < dock.lines.count(); ++j) {
             const QToolBarAreaLayoutLine &line = dock.lines.at(j);
             for (int k = 0; k < line.toolBarItems.count(); ++k) {
                 if (line.toolBarItems.at(k).widgetItem->widget() == toolBar)
                     return j > 0 && k == 0;
             }
         }
     }
     return false;
 }
unplug()
QLayoutItem * QToolBarAreaLayout::unplug (const QList< int > & path, QToolBarAreaLayout * other)
Definition at line 1148 of file qtoolbararealayout.cpp.
Referenced by QMainWindowLayoutState::unplug().
 {
     //other needs to be update as well
     Q_ASSERT(path.count() == 3);
     QToolBarAreaLayoutItem *item = this->item(path);
     Q_ASSERT(item);
     //update the leading space here
     QToolBarAreaLayoutInfo &info = docks[path.at(0)];
     QToolBarAreaLayoutLine &line = info.lines[path.at(1)];
     if (item->size != pick(line.o, item->realSizeHint())) {
         //the item doesn't have its default size
         //so we'll give this to the next item
         int newExtraSpace = 0;
         //let's iterate over the siblings of the current item that pare placed before it
         //we need to find just the one before
         for (int i = path.at(2) - 1; i >= 0; --i) {
             QToolBarAreaLayoutItem &previous = line.toolBarItems[i];
             if (!previous.skip()) {
                 //we need to check if it has a previous element and a next one
                 //the previous will get its size changed
                 for (int j = path.at(2) + 1; j < line.toolBarItems.count(); ++j) {
                     const QToolBarAreaLayoutItem &next = line.toolBarItems.at(j);
                     if (!next.skip()) {
                         newExtraSpace = next.pos - previous.pos - pick(line.o, previous.sizeHint());
                         previous.resize(line.o, next.pos - previous.pos);
                         break;
                     }
                 }
                 break;
             }
         }
         if (other) {
             QToolBarAreaLayoutInfo &info = other->docks[path.at(0)];
             QToolBarAreaLayoutLine &line = info.lines[path.at(1)];
             for (int i = path.at(2) - 1; i >= 0; --i) {
                 QToolBarAreaLayoutItem &previous = line.toolBarItems[i];
                 if (!previous.skip()) {
                     previous.resize(line.o, pick(line.o, previous.sizeHint()) + newExtraSpace);
                     break;
                 }
             }
         }
     }
     Q_ASSERT(!item->gap);
     item->gap = true;
     return item->widgetItem;
 }
Properties
docks
QToolBarAreaLayoutInfo QToolBarAreaLayout::docks[4]
Definition at line 196 of file qtoolbararealayout_p.h.
Referenced by addToolBar(), addToolBarBreak(), apply(), clear(), currentGapIndex(), deleteAllLayoutItems(), findToolBar(), fitLayout(), gapIndex(), getStyleOptionInfo(), indexOf(), insertGap(), insertItem(), insertToolBar(), insertToolBarBreak(), isEmpty(), item(), itemAt(), itemRect(), minimumSize(), moveToolBar(), QToolBarAreaLayout(), rectHint(), remove(), removeToolBar(), removeToolBarBreak(), QMainWindowLayoutState::restoreState(), restoreState(), saveState(), sizeHint(), takeAt(), toolBarBreak(), and unplug().
mainWindow
const QMainWindow* QToolBarAreaLayout::mainWindow
Definition at line 195 of file qtoolbararealayout_p.h.
Referenced by apply(), fitLayout(), gapIndex(), itemRect(), and restoreState().
rect
QRect QToolBarAreaLayout::rect
Definition at line 194 of file qtoolbararealayout_p.h.
Referenced by apply(), clear(), QMainWindowLayoutState::fitLayout(), fitLayout(), gapIndex(), and restoreState().
visible
bool QToolBarAreaLayout::visible
Definition at line 197 of file qtoolbararealayout_p.h.
Referenced by apply(), fitLayout(), minimumSize(), rectHint(), and sizeHint().
The documentation for this class was generated from the following files:
/src/gui/widgets/qtoolbararealayout_p.h
/src/gui/widgets/qtoolbararealayout.cpp