Qt 4.8: QPatternist::XsdXPathExpression Class Reference
QPatternist::XsdXPathExpression Class Reference
XML Schema Processing
Represents a XSD assertion object.
#include <qxsdxpathexpression_p.h>
Public Types
typedef QList< XsdXPathExpression::Ptr > List
typedef QExplicitlySharedDataPointer< XsdXPathExpression > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
AnyURI::Ptr baseURI () const
AnyURI::Ptr defaultNamespace () const
QString expression () const
QList< QXmlName > namespaceBindings () const
void setBaseURI (const AnyURI::Ptr &uri)
void setDefaultNamespace (const AnyURI::Ptr &defaultNamespace)
void setExpression (const QString &expression)
void setNamespaceBindings (const QList< QXmlName > &bindings)
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
AnyURI::Ptr m_baseURI
AnyURI::Ptr m_defaultNamespace
QString m_expression
QList< QXmlName > m_namespaceBindings
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD assertion object.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
See also
XPathExpression Definition
Definition at line 74 of file qxsdxpathexpression_p.h.
Typedefs
List
typedef QList<XsdXPathExpression::Ptr> QPatternist::XsdXPathExpression::List
Definition at line 78 of file qxsdxpathexpression_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdXPathExpression> QPatternist::XsdXPathExpression::Ptr
Definition at line 77 of file qxsdxpathexpression_p.h.
Functions
baseURI()
AnyURI::Ptr XsdXPathExpression::baseURI () const
Returns the base uri of the XPath expression.
Definition at line 73 of file qxsdxpathexpression.cpp.
 {
     return m_baseURI;
 }
defaultNamespace()
AnyURI::Ptr XsdXPathExpression::defaultNamespace () const
Returns the default namespace of the XPath expression.
Definition at line 63 of file qxsdxpathexpression.cpp.
 {
     return m_defaultNamespace;
 }
expression()
QString XsdXPathExpression::expression () const
Returns the expression string of the XPath expression.
Definition at line 83 of file qxsdxpathexpression.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::selectNodeSets(), and setExpression().
 {
     return m_expression;
 }
namespaceBindings()
QList< QXmlName > XsdXPathExpression::namespaceBindings () const
Returns the list of namespace bindings of the XPath expression.
Definition at line 53 of file qxsdxpathexpression.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::selectNodeSets().
 {
     return m_namespaceBindings;
 }
setBaseURI()
void XsdXPathExpression::setBaseURI (const AnyURI::Ptr & uri)
Sets the base uri of the XPath expression.
See also
Base URI Definition
Definition at line 68 of file qxsdxpathexpression.cpp.
 {
     m_baseURI = uri;
 }
setDefaultNamespace()
void XsdXPathExpression::setDefaultNamespace (const AnyURI::Ptr & defaultNamespace)
Sets the default namespace of the XPath expression.
See also
Default Namespace Definition
Definition at line 58 of file qxsdxpathexpression.cpp.
Referenced by QPatternist::XsdSchemaParser::readXPathExpression().
 {
     m_defaultNamespace = defaultNs;
 }
setExpression()
void XsdXPathExpression::setExpression (const QString & expression)
Sets the expression string of the XPath expression.
See also
Expression Definition
Definition at line 78 of file qxsdxpathexpression.cpp.
Referenced by QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseField(), and QPatternist::XsdSchemaParser::parseSelector().
 {
     m_expression = expression;
 }
setNamespaceBindings()
void XsdXPathExpression::setNamespaceBindings (const QList< QXmlName > & bindings)
Sets the list of namespace bindings of the XPath expression.
See also
Namespace Bindings Definition
Note
We can't use a QSet<QXmlName> here, as the hash method does not take the prefix in account, so we loose entries.
Definition at line 48 of file qxsdxpathexpression.cpp.
Referenced by QPatternist::XsdSchemaParser::readXPathExpression().
 {
     m_namespaceBindings = set;
 }
Properties
m_baseURI
AnyURI::Ptr QPatternist::XsdXPathExpression::m_baseURI private
Definition at line 134 of file qxsdxpathexpression_p.h.
Referenced by baseURI(), and setBaseURI().
m_defaultNamespace
AnyURI::Ptr QPatternist::XsdXPathExpression::m_defaultNamespace private
Definition at line 133 of file qxsdxpathexpression_p.h.
Referenced by defaultNamespace(), and setDefaultNamespace().
m_expression
QString QPatternist::XsdXPathExpression::m_expression private
Definition at line 135 of file qxsdxpathexpression_p.h.
Referenced by expression(), and setExpression().
m_namespaceBindings
QList<QXmlName> QPatternist::XsdXPathExpression::m_namespaceBindings private
Definition at line 132 of file qxsdxpathexpression_p.h.
Referenced by namespaceBindings(), and setNamespaceBindings().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdxpathexpression_p.h
/src/xmlpatterns/schema/qxsdxpathexpression.cpp