Qt 4.8: QtHDC Class Reference
QtHDC Class Reference
Public Functions
HDC hdc () const
QtHDC ()
~QtHDC ()
Properties
HDC _hdc
Detailed Description
Definition at line 95 of file qfontengine_win.cpp.
Constructors and Destructors
QtHDC()
QtHDC::QtHDC () inline
Definition at line 99 of file qfontengine_win.cpp.
Referenced by shared_dc().
     {
         HDC displayDC = GetDC(0);
         _hdc = CreateCompatibleDC(displayDC);
         ReleaseDC(0, displayDC);
     }
~QtHDC()
QtHDC::~QtHDC () inline
Definition at line 105 of file qfontengine_win.cpp.
     {
         if (_hdc)
             DeleteDC(_hdc);
     }
Functions
hdc()
HDC QtHDC::hdc () const inline
Definition at line 110 of file qfontengine_win.cpp.
Referenced by QFontEngineWin::drawGDIGlyph(), and shared_dc().
     {
         return _hdc;
     }
Properties
_hdc
HDC QtHDC::_hdc private
Definition at line 97 of file qfontengine_win.cpp.
Referenced by hdc().
The documentation for this class was generated from the following file:
/src/gui/text/qfontengine_win.cpp