Qt 4.8: QMdiSubWindow Class Reference
QMdiSubWindow Class Reference
The QMdiSubWindow class provides a subwindow class for QMdiArea.
#include <qmdisubwindow.h>
Public Types
enum SubWindowOption { AllowOutsideAreaHorizontally = 0x1, AllowOutsideAreaVertically = 0x2, RubberBandResize = 0x4, RubberBandMove = 0x8 }
This enum describes options that customize the behavior of QMdiSubWindow.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void showShaded ()
Calling this function makes the subwindow enter the shaded mode.
void showSystemMenu ()
Shows the system menu below the system menu icon in the title bar.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void aboutToActivate ()
QMdiSubWindow emits this signal immediately before it is activated.
void windowStateChanged (Qt::WindowStates oldState, Qt::WindowStates newState)
QMdiSubWindow emits this signal after the window state changes.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool isShaded () const
Returns true if this window is shaded; otherwise returns false.
int keyboardPageStep () const
int keyboardSingleStep () const
QWidget * maximizedButtonsWidget () const
QWidget * maximizedSystemMenuIconWidget () const
QMdiArea * mdiArea () const
Returns the area containing this sub-window, or 0 if there is none.
QSize minimumSizeHint () const
Reimplemented Function
QMdiSubWindow (QWidget *parent=0, Qt::WindowFlags flags=0)
Constructs a new QMdiSubWindow widget.
void setKeyboardPageStep (int step)
void setKeyboardSingleStep (int step)
void setOption (SubWindowOption option, bool on=true)
If on is true, option is enabled on the subwindow; otherwise it is disabled.
void setSystemMenu (QMenu *systemMenu)
Sets systemMenu as the current system menu for this subwindow.
void setWidget (QWidget *widget)
Sets widget as the internal widget of this subwindow.
QSize sizeHint () const
Reimplemented Function
QMenu * systemMenu () const
Returns a pointer to the current system menu, or zero if no system menu is set.
bool testOption (SubWindowOption) const
Returns true if option is enabled; otherwise returns false.
QWidget * widget () const
Returns the current internal widget.
~QMdiSubWindow ()
Destroys the subwindow.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *changeEvent)
Reimplemented Function
void childEvent (QChildEvent *childEvent)
Reimplemented Function
void closeEvent (QCloseEvent *closeEvent)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *contextMenuEvent)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
bool eventFilter (QObject *object, QEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *focusInEvent)
Reimplemented Function
void focusOutEvent (QFocusEvent *focusOutEvent)
Reimplemented Function
void hideEvent (QHideEvent *hideEvent)
Reimplemented Function
void keyPressEvent (QKeyEvent *keyEvent)
Reimplemented Function
void leaveEvent (QEvent *leaveEvent)
Reimplemented Function
void mouseDoubleClickEvent (QMouseEvent *mouseEvent)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *mouseEvent)
Reimplemented Function
void mousePressEvent (QMouseEvent *mouseEvent)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *mouseEvent)
Reimplemented Function
void moveEvent (QMoveEvent *moveEvent)
Reimplemented Function
void paintEvent (QPaintEvent *paintEvent)
Reimplemented Function
void resizeEvent (QResizeEvent *resizeEvent)
Reimplemented Function
void showEvent (QShowEvent *showEvent)
Reimplemented Function
void timerEvent (QTimerEvent *timerEvent)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
int keyboardPageStep
sets how far a widget should move or resize when using the keyboard page keys.
int keyboardSingleStep
sets how far a widget should move or resize when using the keyboard arrow keys.
Friends
class QMdi::ControlContainer
class QMdiAreaPrivate
class QMdiAreaTabBar
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QMdiSubWindow class provides a subwindow class for QMdiArea.
Since
4.3
QMdiSubWindow represents a top-level window in a QMdiArea, and consists of a title bar with window decorations, an internal widget, and (depending on the current style) a window frame and a size grip. QMdiSubWindow has its own layout, which consists of the title bar and a center area for the internal widget.
The most common way to construct a QMdiSubWindow is to call QMdiArea::addSubWindow() with the internal widget as the argument. You can also create a subwindow yourself, and set an internal widget by calling setWidget().
You use the same API when programming with subwindows as with regular top-level windows (e.g., you can call functions such as show(), hide(), showMaximized(), and setWindowTitle()).
Subwindow Handling
QMdiSubWindow also supports behavior specific to subwindows in an MDI area.
By default, each QMdiSubWindow is visible inside the MDI area viewport when moved around, but it is also possible to specify transparent window movement and resizing behavior, where only the outline of a subwindow is updated during these operations. The setOption() function is used to enable this behavior.
The isShaded() function detects whether the subwindow is currently shaded (i.e., the window is collapsed so that only the title bar is visible). To enter shaded mode, call showShaded(). QMdiSubWindow emits the windowStateChanged() signal whenever the window state has changed (e.g., when the window becomes minimized, or is restored). It also emits aboutToActivate() before it is activated.
In keyboard-interactive mode, the windows are moved and resized with the keyboard. You can enter this mode through the system menu of the window. The keyboardSingleStep and keyboardPageStep properties control the distance the widget is moved or resized for each keypress event. When shift is pressed down page step is used; otherwise single step is used.
You can also change the active window with the keyboard. By pressing the control and tab keys at the same time, the next (using the current QMdiArea::WindowOrder) subwindow will be activated. By pressing control, shift, and tab, you will activate the previous window. This is equivalent to calling QMdiArea::activateNextSubWindow() and QMdiArea::activatePreviousSubWindow(). Note that these shortcuts overrides global shortcuts, but not the QMdiArea shortcuts.
See also
QMdiArea
Definition at line 60 of file qmdisubwindow.h.
Enumerations
SubWindowOption
enum QMdiSubWindow::SubWindowOption
This enum describes options that customize the behavior of QMdiSubWindow.
AllowOutsideAreaHorizontally
AllowOutsideAreaVertically
RubberBandResize If you enable this option, a rubber band control is used to represent the subwindow's outline, and the user resizes this instead of the subwindow itself. As a result, the subwindow maintains its original position and size until the resize operation has been completed, at which time it will receive a single QResizeEvent. By default, this option is disabled.
RubberBandMove If you enable this option, a rubber band control is used to represent the subwindow's outline, and the user moves this instead of the subwindow itself. As a result, the subwindow remains in its original position until the move operation has completed, at which time a QMoveEvent is sent to the window. By default, this option is disabled.
Enumerator
AllowOutsideAreaHorizontally
AllowOutsideAreaVertically
RubberBandResize
RubberBandMove
Definition at line 66 of file qmdisubwindow.h.
{
         AllowOutsideAreaHorizontally = 0x1, // internal
         AllowOutsideAreaVertically = 0x2, // internal
         RubberBandResize = 0x4,
         RubberBandMove = 0x8
     };
Constructors and Destructors
QMdiSubWindow()
QMdiSubWindow::QMdiSubWindow (QWidget * parent = 0, Qt::WindowFlags flags = 0)
Constructs a new QMdiSubWindow widget.
The parent and flags arguments are passed to QWidget's constructor.
Instead of using addSubWindow(), it is also simply possible to use setParent() when you add the subwindow to a QMdiArea.
Note that only QMdiSubWindow can be set as children of QMdiArea; you cannot, for instance, write:
QMdiArea mdiArea; QTextEdit editor(&mdiArea); // invalid child widget
See also
QMdiArea::addSubWindow()
Definition at line 2258 of file qmdisubwindow.cpp.
     : QWidget(*new QMdiSubWindowPrivate, parent, 0)
 {
     Q_D(QMdiSubWindow);
 #ifndef QT_NO_MENU
     d->createSystemMenu();
     addActions(d->systemMenu->actions());
 #endif
     d->setWindowFlags(flags);
     setBackgroundRole(QPalette::Window);
     setAutoFillBackground(true);
     setMouseTracking(true);
     setLayout(new QVBoxLayout);
     setFocusPolicy(Qt::StrongFocus);
     layout()->setMargin(0);
     d->updateGeometryConstraints();
     setAttribute(Qt::WA_Resized, false);
     d->titleBarPalette = d->desktopPalette();
     d->font = QApplication::font("QWorkspaceTitleBar");
     // We don't want the menu icon by default on mac.
 #ifndef Q_WS_MAC
     if (windowIcon().isNull())
         d->menuIcon = style()->standardIcon(QStyle::SP_TitleBarMenuButton, 0, this);
     else
         d->menuIcon = windowIcon();
 #endif
     connect(qApp, SIGNAL(focusChanged(QWidget*,QWidget*)),
             this, SLOT(_q_processFocusChanged(QWidget*,QWidget*)));
 }
~QMdiSubWindow()
QMdiSubWindow::~QMdiSubWindow ()
Destroys the subwindow.
See also
QMdiArea::removeSubWindow()
Definition at line 2293 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
 #ifndef QT_NO_MENUBAR
     d->removeButtonsFromMenuBar();
 #endif
     d->setActive(false);
 }
Functions
aboutToActivate
QMdiSubWindow::aboutToActivate () signal
QMdiSubWindow emits this signal immediately before it is activated.
After the subwindow has been activated, the QMdiArea that manages the subwindow will also emit the QMdiArea::subWindowActivated() signal.
See also
QMdiArea::subWindowActivated()
changeEvent()
void QMdiSubWindow::changeEvent (QEvent * changeEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2994 of file qmdisubwindow.cpp.
Referenced by eventFilter().
 {
     if (!parent()) {
         QWidget::changeEvent(changeEvent);
         return;
     }
     if (changeEvent->type() != QEvent::WindowStateChange) {
         QWidget::changeEvent(changeEvent);
         return;
     }
     QWindowStateChangeEvent *event = static_cast<QWindowStateChangeEvent *>(changeEvent);
     if (event->isOverride()) {
         event->ignore();
         return;
     }
     Qt::WindowStates oldState = event->oldState();
     Qt::WindowStates newState = windowState();
     if (oldState == newState) {
         changeEvent->ignore();
         return;
     }
     // QWidget ensures that the widget is visible _after_ setWindowState(),
     // but we need to ensure that the widget is visible _before_
     // setWindowState() returns.
     Q_D(QMdiSubWindow);
     if (!isVisible()) {
         d->ensureWindowState(Qt::WindowNoState);
         setVisible(true);
     }
     if (!d->oldGeometry.isValid())
         d->oldGeometry = geometry();
     if ((oldState & Qt::WindowActive) && (newState & Qt::WindowActive))
         d->currentOperation = QMdiSubWindowPrivate::None;
     if (!(oldState & Qt::WindowMinimized) && (newState & Qt::WindowMinimized))
         d->setMinimizeMode();
     else if (!(oldState & Qt::WindowMaximized) && (newState & Qt::WindowMaximized))
         d->setMaximizeMode();
     else if (!(newState & (Qt::WindowMaximized | Qt::WindowMinimized)))
         d->setNormalMode();
     if (d->isActive)
         d->ensureWindowState(Qt::WindowActive);
     if (d->activationEnabled)
         emit windowStateChanged(oldState, windowState());
 }
childEvent()
void QMdiSubWindow::childEvent (QChildEvent * childEvent) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 3492 of file qmdisubwindow.cpp.
 {
     if (childEvent->type() != QEvent::ChildPolished)
         return;
 #ifndef QT_NO_SIZEGRIP
     if (QSizeGrip *sizeGrip = qobject_cast<QSizeGrip *>(childEvent->child()))
         d_func()->setSizeGrip(sizeGrip);
 #endif
 }
closeEvent()
void QMdiSubWindow::closeEvent (QCloseEvent * closeEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3050 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     bool acceptClose = true;
     if (d->baseWidget)
         acceptClose = d->baseWidget->close();
     if (!acceptClose) {
         closeEvent->ignore();
         return;
     }
 #ifndef QT_NO_MENUBAR
     d->removeButtonsFromMenuBar();
 #endif
     d->setActive(false);
     if (parentWidget() && testAttribute(Qt::WA_DeleteOnClose)) {
         QChildEvent childRemoved(QEvent::ChildRemoved, this);
         QApplication::sendEvent(parentWidget(), &childRemoved);
     }
     closeEvent->accept();
 }
contextMenuEvent()
void QMdiSubWindow::contextMenuEvent (QContextMenuEvent * contextMenuEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3456 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (!d->systemMenu) {
         contextMenuEvent->ignore();
         return;
     }
     if (d->hoveredSubControl == QStyle::SC_TitleBarSysMenu
             || d->getRegion(QMdiSubWindowPrivate::Move).contains(contextMenuEvent->pos())) {
         d->systemMenu->exec(contextMenuEvent->globalPos());
     } else {
         contextMenuEvent->ignore();
     }
 }
event()
bool QMdiSubWindow::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2812 of file qmdisubwindow.cpp.
Referenced by changeEvent(), and eventFilter().
 {
     Q_D(QMdiSubWindow);
     switch (event->type()) {
     case QEvent::StyleChange: {
         bool wasShaded = isShaded();
         bool wasMinimized = isMinimized();
         bool wasMaximized = isMaximized();
         // Don't emit subWindowActivated, the app doesn't have to know about our hacks
         const QScopedValueRollback<bool> activationEnabledSaver(d->activationEnabled);
         d->activationEnabled = false;
         ensurePolished();
         setContentsMargins(0, 0, 0, 0);
         if (wasMinimized || wasMaximized || wasShaded)
             showNormal();
         d->updateGeometryConstraints();
         resize(d->internalMinimumSize.expandedTo(size()));
         d->updateMask();
         d->updateDirtyRegions();
         if (wasShaded)
             showShaded();
         else if (wasMinimized)
             showMinimized();
         else if (wasMaximized)
             showMaximized();
         break;
     }
     case QEvent::ParentAboutToChange:
         d->setActive(false);
         break;
     case QEvent::ParentChange: {
         bool wasResized = testAttribute(Qt::WA_Resized);
 #ifndef QT_NO_MENUBAR
         d->removeButtonsFromMenuBar();
 #endif
         d->currentOperation = QMdiSubWindowPrivate::None;
         d->activeSubControl = QStyle::SC_None;
         d->hoveredSubControl = QStyle::SC_None;
 #ifndef QT_NO_RUBBERBAND
         if (d->isInRubberBandMode)
             d->leaveRubberBandMode();
 #endif
         d->isShadeMode = false;
         d->isMaximizeMode = false;
         d->isWidgetHiddenByUs = false;
         if (!parent()) {
 #if !defined(QT_NO_SIZEGRIP) && defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
             if (qobject_cast<QMacStyle *>(style()))
                 delete d->sizeGrip;
 #endif
             setOption(RubberBandResize, false);
             setOption(RubberBandMove, false);
         } else {
             d->setWindowFlags(windowFlags());
         }
         setContentsMargins(0, 0, 0, 0);
         d->updateGeometryConstraints();
         d->updateCursor();
         d->updateMask();
         d->updateDirtyRegions();
         d->updateActions();
         if (!wasResized && testAttribute(Qt::WA_Resized))
             setAttribute(Qt::WA_Resized, false);
         break;
     }
     case QEvent::WindowActivate:
         if (d->ignoreNextActivationEvent) {
             d->ignoreNextActivationEvent = false;
             break;
         }
         d->isExplicitlyDeactivated = false;
         d->setActive(true);
         break;
     case QEvent::WindowDeactivate:
         if (d->ignoreNextActivationEvent) {
             d->ignoreNextActivationEvent = false;
             break;
         }
         d->isExplicitlyDeactivated = true;
         d->setActive(false);
         break;
     case QEvent::WindowTitleChange:
         if (!d->ignoreWindowTitleChange)
             d->updateWindowTitle(false);
         d->updateInternalWindowTitle();
         break;
     case QEvent::ModifiedChange:
         if (!windowTitle().contains(QLatin1String("[*]")))
             break;
 #ifndef QT_NO_MENUBAR
         if (maximizedButtonsWidget() && d->controlContainer->menuBar() && d->controlContainer->menuBar()
                 ->cornerWidget(Qt::TopRightCorner) == maximizedButtonsWidget()) {
             window()->setWindowModified(isWindowModified());
         }
 #endif // QT_NO_MENUBAR
         d->updateInternalWindowTitle();
         break;
     case QEvent::LayoutDirectionChange:
         d->updateDirtyRegions();
         break;
     case QEvent::LayoutRequest:
         d->updateGeometryConstraints();
         break;
     case QEvent::WindowIconChange:
         d->menuIcon = windowIcon();
         if (d->menuIcon.isNull())
             d->menuIcon = style()->standardIcon(QStyle::SP_TitleBarMenuButton, 0, this);
         if (d->controlContainer)
             d->controlContainer->updateWindowIcon(d->menuIcon);
         if (!maximizedSystemMenuIconWidget())
             update(0, 0, width(), d->titleBarHeight());
         break;
     case QEvent::PaletteChange:
         d->titleBarPalette = d->desktopPalette();
         break;
     case QEvent::FontChange:
         d->font = font();
         break;
 #ifndef QT_NO_TOOLTIP
     case QEvent::ToolTip:
         showToolTip(static_cast<QHelpEvent *>(event), this, d->titleBarOptions(),
                     QStyle::CC_TitleBar, d->hoveredSubControl);
         break;
 #endif
     default:
         break;
     }
     return QWidget::event(event);
 }
eventFilter()
bool QMdiSubWindow::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2705 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (!object)
         return QWidget::eventFilter(object, event);
 #ifndef QT_NO_MENU
     // System menu events.
     if (d->systemMenu && d->systemMenu == object) {
         if (event->type() == QEvent::MouseButtonDblClick) {
             close();
         } else if (event->type() == QEvent::MouseMove) {
             QMouseEvent *mouseEvent = static_cast<QMouseEvent *>(event);
             d->hoveredSubControl = d->getSubControl(mapFromGlobal(mouseEvent->globalPos()));
         } else if (event->type() == QEvent::Hide) {
             d->systemMenu->removeEventFilter(this);
             d->activeSubControl = QStyle::SC_None;
             update(QRegion(0, 0, width(), d->titleBarHeight()));
         }
         return QWidget::eventFilter(object, event);
     }
 #endif
 #ifndef QT_NO_SIZEGRIP
     if (object != d->baseWidget && parent() && qobject_cast<QSizeGrip *>(object)) {
         if (event->type() != QEvent::MouseButtonPress || !testOption(QMdiSubWindow::RubberBandResize))
             return QWidget::eventFilter(object, event);
         const QMouseEvent *mouseEvent = static_cast<QMouseEvent *>(event);
         d->mousePressPosition = parentWidget()->mapFromGlobal(mouseEvent->globalPos());
         d->oldGeometry = geometry();
         d->currentOperation = isLeftToRight() ? QMdiSubWindowPrivate::BottomRightResize
                                               : QMdiSubWindowPrivate::BottomLeftResize;
 #ifndef QT_NO_RUBBERBAND
         d->enterRubberBandMode();
 #endif
         return true;
     }
 #endif
     if (object != d->baseWidget && event->type() != QEvent::WindowTitleChange)
         return QWidget::eventFilter(object, event);
     switch (event->type()) {
     case QEvent::Show:
         d->setActive(true);
         break;
     case QEvent::ShowToParent:
         if (!d->isWidgetHiddenByUs)
             show();
         break;
     case QEvent::WindowStateChange: {
         QWindowStateChangeEvent *changeEvent = static_cast<QWindowStateChangeEvent*>(event);
         if (changeEvent->isOverride())
             break;
         Qt::WindowStates oldState = changeEvent->oldState();
         Qt::WindowStates newState = d->baseWidget->windowState();
         if (!(oldState & Qt::WindowMinimized) && (newState & Qt::WindowMinimized))
             showMinimized();
         else if (!(oldState & Qt::WindowMaximized) && (newState & Qt::WindowMaximized))
             showMaximized();
         else if (!(newState & (Qt::WindowMaximized | Qt::WindowMinimized)))
             showNormal();
         break;
     }
     case QEvent::Enter:
         d->currentOperation = QMdiSubWindowPrivate::None;
         d->updateCursor();
         break;
     case QEvent::LayoutRequest:
         d->updateGeometryConstraints();
         break;
     case QEvent::WindowTitleChange:
         if (d->ignoreWindowTitleChange)
             break;
         if (object == d->baseWidget) {
             d->updateWindowTitle(true);
             d->lastChildWindowTitle = d->baseWidget->windowTitle();
 #ifndef QT_NO_MENUBAR
         } else if (maximizedButtonsWidget() && d->controlContainer->menuBar() && d->controlContainer->menuBar()
                    ->cornerWidget(Qt::TopRightCorner) == maximizedButtonsWidget()) {
             d->originalTitle = QString::null;
             if (d->baseWidget && d->baseWidget->windowTitle() == windowTitle())
                 d->updateWindowTitle(true);
             else
                 d->updateWindowTitle(false);
 #endif
         }
         break;
     case QEvent::ModifiedChange: {
         if (object != d->baseWidget)
             break;
         bool windowModified = d->baseWidget->isWindowModified();
         if (!windowModified && d->baseWidget->windowTitle() != windowTitle())
             break;
         if (windowTitle().contains(QLatin1String("[*]")))
             setWindowModified(windowModified);
         break;
     }
     default:
         break;
     }
     return QWidget::eventFilter(object, event);
 }
focusInEvent()
void QMdiSubWindow::focusInEvent (QFocusEvent * focusInEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3476 of file qmdisubwindow.cpp.
 {
     d_func()->focusInReason = focusInEvent->reason();
 }
focusOutEvent()
void QMdiSubWindow::focusOutEvent (QFocusEvent * focusOutEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3484 of file qmdisubwindow.cpp.
 {
     // To avoid update() in QWidget::focusOutEvent.
 }
hideEvent()
void QMdiSubWindow::hideEvent (QHideEvent * hideEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2984 of file qmdisubwindow.cpp.
 {
 #ifndef QT_NO_MENUBAR
     d_func()->removeButtonsFromMenuBar();
 #endif
 }
isShaded()
bool QMdiSubWindow::isShaded () const
Returns true if this window is shaded; otherwise returns false.
A window is shaded if it is collapsed so that only the title bar is visible.
Definition at line 2409 of file qmdisubwindow.cpp.
Referenced by QMdiAreaPrivate::_q_deactivateAllWindows(), event(), minimumSizeHint(), mouseDoubleClickEvent(), QMdiAreaPrivate::rearrange(), and showShaded().
 {
     return d_func()->isShadeMode;
 }
keyboardPageStep()
int QMdiSubWindow::keyboardPageStep () const
Referenced by setKeyboardSingleStep().
keyboardSingleStep()
int QMdiSubWindow::keyboardSingleStep () const
Referenced by testOption().
keyPressEvent()
void QMdiSubWindow::keyPressEvent (QKeyEvent * keyEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3373 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (!d->isInInteractiveMode || !parent()) {
         keyEvent->ignore();
         return;
     }
     QPoint delta;
     switch (keyEvent->key()) {
     case Qt::Key_Right:
         if (keyEvent->modifiers() & Qt::ShiftModifier)
             delta = QPoint(d->keyboardPageStep, 0);
         else
             delta = QPoint(d->keyboardSingleStep, 0);
         break;
     case Qt::Key_Up:
         if (keyEvent->modifiers() & Qt::ShiftModifier)
             delta = QPoint(0, -d->keyboardPageStep);
         else
             delta = QPoint(0, -d->keyboardSingleStep);
         break;
     case Qt::Key_Left:
         if (keyEvent->modifiers() & Qt::ShiftModifier)
             delta = QPoint(-d->keyboardPageStep, 0);
         else
             delta = QPoint(-d->keyboardSingleStep, 0);
         break;
     case Qt::Key_Down:
         if (keyEvent->modifiers() & Qt::ShiftModifier)
             delta = QPoint(0, d->keyboardPageStep);
         else
             delta = QPoint(0, d->keyboardSingleStep);
         break;
     case Qt::Key_Escape:
     case Qt::Key_Return:
     case Qt::Key_Enter:
         d->leaveInteractiveMode();
         return;
     default:
         keyEvent->ignore();
         return;
     }
 #ifndef QT_NO_CURSOR
     QPoint newPosition = parentWidget()->mapFromGlobal(cursor().pos() + delta);
     QRect oldGeometry =
 #ifndef QT_NO_RUBBERBAND
         d->isInRubberBandMode ? d->rubberBand->geometry() :
 #endif
         geometry();
     d->setNewGeometry(newPosition);
     QRect currentGeometry =
 #ifndef QT_NO_RUBBERBAND
         d->isInRubberBandMode ? d->rubberBand->geometry() :
 #endif
         geometry();
     if (currentGeometry == oldGeometry)
         return;
     // Update cursor position
     QPoint actualDelta;
     if (d->isMoveOperation()) {
         actualDelta = QPoint(currentGeometry.x() - oldGeometry.x(),
                              currentGeometry.y() - oldGeometry.y());
     } else {
         int dx = isLeftToRight() ? currentGeometry.width() - oldGeometry.width()
                                  : currentGeometry.x() - oldGeometry.x();
         actualDelta = QPoint(dx, currentGeometry.height() - oldGeometry.height());
     }
     // Adjust in case we weren't able to move as long as wanted.
     if (actualDelta != delta)
         newPosition += (actualDelta - delta);
     cursor().setPos(parentWidget()->mapToGlobal(newPosition));
 #endif
 }
leaveEvent()
void QMdiSubWindow::leaveEvent (QEvent * leaveEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3074 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (d->hoveredSubControl != QStyle::SC_None) {
         d->hoveredSubControl = QStyle::SC_None;
         update(QRegion(0, 0, width(), d->titleBarHeight()));
     }
 }
maximizedButtonsWidget()
QWidget * QMdiSubWindow::maximizedButtonsWidget () const
Warning
This function is not part of the public interface.
Definition at line 2380 of file qmdisubwindow.cpp.
Referenced by event(), eventFilter(), and showEvent().
 {
     Q_D(const QMdiSubWindow);
     if (isVisible() && d->controlContainer && isMaximized() && !d->drawTitleBarWhenMaximized()
         && !isChildOfTabbedQMdiArea(this)) {
         return d->controlContainer->controllerWidget();
     }
     return 0;
 }
maximizedSystemMenuIconWidget()
QWidget * QMdiSubWindow::maximizedSystemMenuIconWidget () const
Warning
This function is not part of the public interface.
Definition at line 2393 of file qmdisubwindow.cpp.
Referenced by event(), and showSystemMenu().
 {
     Q_D(const QMdiSubWindow);
     if (isVisible() && d->controlContainer && isMaximized() && !d->drawTitleBarWhenMaximized()
         && !isChildOfTabbedQMdiArea(this)) {
         return d->controlContainer->systemMenuLabel();
     }
     return 0;
 }
mdiArea()
QMdiArea * QMdiSubWindow::mdiArea () const
Returns the area containing this sub-window, or 0 if there is none.
Since
4.4
See also
QMdiArea::addSubWindow()
Definition at line 2597 of file qmdisubwindow.cpp.
Referenced by isChildOfTabbedQMdiArea().
 {
     QWidget *parent = parentWidget();
     while (parent) {
         if (QMdiArea *area = qobject_cast<QMdiArea *>(parent)) {
             if (area->viewport() == parentWidget())
                 return area;
         }
         parent = parent->parentWidget();
     }
     return 0;
 }
minimumSizeHint()
QSize QMdiSubWindow::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3519 of file qmdisubwindow.cpp.
Referenced by QMdiArea::minimumSizeHint(), and sizeHint().
 {
     Q_D(const QMdiSubWindow);
     if (isVisible())
         ensurePolished();
     // Minimized window.
     if (parent() && isMinimized() && !isShaded())
         return d->iconSize();
     // Calculate window decoration.
     int margin, minWidth;
     d->sizeParameters(&margin, &minWidth);
     int decorationHeight = margin + d->titleBarHeight();
     int minHeight = decorationHeight;
     // Shaded window.
     if (parent() && isShaded())
         return QSize(qMax(minWidth, width()), d->titleBarHeight());
     // Content
     if (layout()) {
         QSize minLayoutSize = layout()->minimumSize();
         if (minLayoutSize.isValid()) {
             minWidth = qMax(minWidth, minLayoutSize.width() + 2 * margin);
             minHeight += minLayoutSize.height();
         }
     } else if (d->baseWidget && d->baseWidget->isVisible()) {
         QSize minBaseWidgetSize = d->baseWidget->minimumSizeHint();
         if (minBaseWidgetSize.isValid()) {
             minWidth = qMax(minWidth, minBaseWidgetSize.width() + 2 * margin);
             minHeight += minBaseWidgetSize.height();
         }
     }
 #ifndef QT_NO_SIZEGRIP
     // SizeGrip
     int sizeGripHeight = 0;
     if (d->sizeGrip && d->sizeGrip->isVisibleTo(const_cast<QMdiSubWindow *>(this)))
         sizeGripHeight = d->sizeGrip->height();
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     else if (parent() && qobject_cast<QMacStyle *>(style()) && !d->sizeGrip)
         sizeGripHeight = style()->pixelMetric(QStyle::PM_SizeGripSize, 0, this);
 #endif
     minHeight = qMax(minHeight, decorationHeight + sizeGripHeight);
 #endif
     return QSize(minWidth, minHeight).expandedTo(QApplication::globalStrut());
 }
mouseDoubleClickEvent()
void QMdiSubWindow::mouseDoubleClickEvent (QMouseEvent * mouseEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3246 of file qmdisubwindow.cpp.
 {
     if (!parent()) {
         QWidget::mouseDoubleClickEvent(mouseEvent);
         return;
     }
     if (mouseEvent->button() != Qt::LeftButton) {
         mouseEvent->ignore();
         return;
     }
     Q_D(QMdiSubWindow);
     if (!d->isMoveOperation()) {
 #ifndef QT_NO_MENU
         if (d->hoveredSubControl == QStyle::SC_TitleBarSysMenu)
             close();
 #endif
         return;
     }
     Qt::WindowFlags flags = windowFlags();
     if (isMinimized()) {
         if ((isShaded() && (flags & Qt::WindowShadeButtonHint))
             || (flags & Qt::WindowMinimizeButtonHint)) {
             showNormal();
         }
         return;
     }
     if (isMaximized()) {
        if (flags & Qt::WindowMaximizeButtonHint)
            showNormal();
        return;
     }
     if (flags & Qt::WindowShadeButtonHint)
         showShaded();
     else if (flags & Qt::WindowMaximizeButtonHint)
         showMaximized();
 }
mouseMoveEvent()
void QMdiSubWindow::mouseMoveEvent (QMouseEvent * mouseEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3328 of file qmdisubwindow.cpp.
 {
     if (!parent()) {
         QWidget::mouseMoveEvent(mouseEvent);
         return;
     }
     Q_D(QMdiSubWindow);
     // No update needed if we're in a move/resize operation.
     if (!d->isMoveOperation() && !d->isResizeOperation()) {
         // Find previous and current hover region.
         const QStyleOptionTitleBar options = d->titleBarOptions();
         QStyle::SubControl oldHover = d->hoveredSubControl;
         d->hoveredSubControl = d->getSubControl(mouseEvent->pos());
         QRegion hoverRegion;
         if (isHoverControl(oldHover) && oldHover != d->hoveredSubControl)
             hoverRegion += style()->subControlRect(QStyle::CC_TitleBar, &options, oldHover, this);
         if (isHoverControl(d->hoveredSubControl) && d->hoveredSubControl != oldHover) {
             hoverRegion += style()->subControlRect(QStyle::CC_TitleBar, &options,
                     d->hoveredSubControl, this);
         }
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
         if (qobject_cast<QMacStyle *>(style()) && !hoverRegion.isEmpty())
             hoverRegion += QRegion(0, 0, width(), d->titleBarHeight(options));
 #endif
         if (!hoverRegion.isEmpty())
             update(hoverRegion);
     }
     if ((mouseEvent->buttons() & Qt::LeftButton) || d->isInInteractiveMode) {
         if ((d->isResizeOperation() && d->resizeEnabled) || (d->isMoveOperation() && d->moveEnabled))
             d->setNewGeometry(mapToParent(mouseEvent->pos()));
         return;
     }
     // Do not resize/move if not allowed.
     d->currentOperation = d->getOperation(mouseEvent->pos());
     if ((d->isResizeOperation() && !d->resizeEnabled) || (d->isMoveOperation() && !d->moveEnabled))
         d->currentOperation = QMdiSubWindowPrivate::None;
     d->updateCursor();
 }
mousePressEvent()
void QMdiSubWindow::mousePressEvent (QMouseEvent * mouseEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3200 of file qmdisubwindow.cpp.
 {
     if (!parent()) {
         QWidget::mousePressEvent(mouseEvent);
         return;
     }
     Q_D(QMdiSubWindow);
     if (d->isInInteractiveMode)
         d->leaveInteractiveMode();
 #ifndef QT_NO_RUBBERBAND
     if (d->isInRubberBandMode)
         d->leaveRubberBandMode();
 #endif
     if (mouseEvent->button() != Qt::LeftButton) {
         mouseEvent->ignore();
         return;
     }
     if (d->currentOperation != QMdiSubWindowPrivate::None) {
         d->updateCursor();
         d->mousePressPosition = mapToParent(mouseEvent->pos());
         if (d->resizeEnabled || d->moveEnabled)
             d->oldGeometry = geometry();
 #ifndef QT_NO_RUBBERBAND
         if ((testOption(QMdiSubWindow::RubberBandResize) && d->isResizeOperation())
             || (testOption(QMdiSubWindow::RubberBandMove) && d->isMoveOperation())) {
             d->enterRubberBandMode();
         }
 #endif
         return;
     }
     d->activeSubControl = d->hoveredSubControl;
 #ifndef QT_NO_MENU
     if (d->activeSubControl == QStyle::SC_TitleBarSysMenu)
         showSystemMenu();
     else
 #endif
     update(QRegion(0, 0, width(), d->titleBarHeight()));
 }
mouseReleaseEvent()
void QMdiSubWindow::mouseReleaseEvent (QMouseEvent * mouseEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3291 of file qmdisubwindow.cpp.
 {
     if (!parent()) {
         QWidget::mouseReleaseEvent(mouseEvent);
         return;
     }
     if (mouseEvent->button() != Qt::LeftButton) {
         mouseEvent->ignore();
         return;
     }
     Q_D(QMdiSubWindow);
     if (d->currentOperation != QMdiSubWindowPrivate::None) {
 #ifndef QT_NO_RUBBERBAND
         if (d->isInRubberBandMode && !d->isInInteractiveMode)
             d->leaveRubberBandMode();
 #endif
         if (d->resizeEnabled || d->moveEnabled)
             d->oldGeometry = geometry();
     }
     d->currentOperation = d->getOperation(mouseEvent->pos());
     d->updateCursor();
     d->hoveredSubControl = d->getSubControl(mouseEvent->pos());
     if (d->activeSubControl != QStyle::SC_None
             && d->activeSubControl == d->hoveredSubControl) {
         d->processClickedSubControl();
     }
     d->activeSubControl = QStyle::SC_None;
     update(QRegion(0, 0, width(), d->titleBarHeight()));
 }
moveEvent()
void QMdiSubWindow::moveEvent (QMoveEvent * moveEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3131 of file qmdisubwindow.cpp.
 {
     if (!parent()) {
         QWidget::moveEvent(moveEvent);
         return;
     }
     Q_D(QMdiSubWindow);
     if (d->isMaximizeMode)
         d->ensureWindowState(Qt::WindowMaximized);
 }
paintEvent()
void QMdiSubWindow::paintEvent (QPaintEvent * paintEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3146 of file qmdisubwindow.cpp.
 {
     if (!parent() || (windowFlags() & Qt::FramelessWindowHint)) {
         QWidget::paintEvent(paintEvent);
         return;
     }
     Q_D(QMdiSubWindow);
     if (isMaximized() && !d->drawTitleBarWhenMaximized())
         return;
     if (d->resizeTimerId != -1) {
         // Only update the style option rect and the window title.
         int border = d->hasBorder(d->cachedStyleOptions) ? 4 : 0;
         int titleBarHeight = d->titleBarHeight(d->cachedStyleOptions);
         titleBarHeight -= isMinimized() ? 2 * border : border;
         d->cachedStyleOptions.rect = QRect(border, border, width() - 2 * border, titleBarHeight);
         if (!d->windowTitle.isEmpty()) {
             int width = style()->subControlRect(QStyle::CC_TitleBar, &d->cachedStyleOptions,
                                                 QStyle::SC_TitleBarLabel, this).width();
             d->cachedStyleOptions.text = d->cachedStyleOptions.fontMetrics
                                          .elidedText(d->windowTitle, Qt::ElideRight, width);
         }
     } else {
         // Force full update.
         d->cachedStyleOptions = d->titleBarOptions();
     }
     QStylePainter painter(this);
     if (!d->windowTitle.isEmpty())
         painter.setFont(d->font);
     painter.drawComplexControl(QStyle::CC_TitleBar, d->cachedStyleOptions);
     if (isMinimized() && !d->hasBorder(d->cachedStyleOptions))
         return;
     QStyleOptionFrame frameOptions;
     frameOptions.initFrom(this);
     frameOptions.lineWidth = style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, this);
     if (d->isActive)
         frameOptions.state |= QStyle::State_Active;
     else
         frameOptions.state &= ~QStyle::State_Active;
     // ### Ensure that we do not require setting the cliprect for 4.4
     if (!isMinimized() && !d->hasBorder(d->cachedStyleOptions))
         painter.setClipRect(rect().adjusted(0, d->titleBarHeight(d->cachedStyleOptions), 0, 0));
     if (!isMinimized() || d->hasBorder(d->cachedStyleOptions))
         painter.drawPrimitive(QStyle::PE_FrameWindow, frameOptions);
 }
resizeEvent()
void QMdiSubWindow::resizeEvent (QResizeEvent * resizeEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3086 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
 #ifndef QT_NO_SIZEGRIP
     if (d->sizeGrip) {
         d->sizeGrip->move(isLeftToRight() ? width() - d->sizeGrip->width() : 0,
                           height() - d->sizeGrip->height());
     }
 #endif
     if (!parent()) {
         QWidget::resizeEvent(resizeEvent);
         return;
     }
     if (d->isMaximizeMode)
         d->ensureWindowState(Qt::WindowMaximized);
     d->updateMask();
     if (!isVisible())
         return;
     if (d->resizeTimerId <= 0)
         d->cachedStyleOptions = d->titleBarOptions();
     else
         killTimer(d->resizeTimerId);
     d->resizeTimerId = startTimer(200);
 }
setKeyboardPageStep()
void QMdiSubWindow::setKeyboardPageStep (int step)
Definition at line 2496 of file qmdisubwindow.cpp.
 {
     // Haven't done any boundary check here since negative step only
     // means inverted behavior, which is OK if the user want it.
     // A step equal to zero means "do nothing".
     d_func()->keyboardPageStep = step;
 }
setKeyboardSingleStep()
void QMdiSubWindow::setKeyboardSingleStep (int step)
Definition at line 2466 of file qmdisubwindow.cpp.
 {
     // Haven't done any boundary check here since negative step only
     // means inverted behavior, which is OK if the user want it.
     // A step equal to zero means "do nothing".
     d_func()->keyboardSingleStep = step;
 }
setOption()
void QMdiSubWindow::setOption (SubWindowOption option, bool on = true)
If on is true, option is enabled on the subwindow; otherwise it is disabled.
See SubWindowOption for the effect of each option.
See also
SubWindowOption, testOption()
Definition at line 2420 of file qmdisubwindow.cpp.
Referenced by QMdiAreaPrivate::appendChild(), event(), and QMdiAreaPrivate::scrollBarPolicyChanged().
 {
     Q_D(QMdiSubWindow);
     if (on && !(d->options & option))
         d->options |= option;
     else if (!on && (d->options & option))
         d->options &= ~option;
 #ifndef QT_NO_RUBBERBAND
     if ((option & (RubberBandResize | RubberBandMove)) && !on && d->isInRubberBandMode)
         d->leaveRubberBandMode();
 #endif
 }
setSystemMenu()
void QMdiSubWindow::setSystemMenu (QMenu * systemMenu)
Sets systemMenu as the current system menu for this subwindow.
By default, each QMdiSubWindow has a standard system menu.
QActions for the system menu created by QMdiSubWindow will automatically be updated depending on the current window state; e.g., the minimize action will be disabled after the window is minimized.
QActions added by the user are not updated by QMdiSubWindow.
QMdiSubWindow takes ownership of systemMenu; you do not have to delete it. Any existing menus will be deleted.
See also
systemMenu(), showSystemMenu()
Definition at line 2522 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (systemMenu && systemMenu == d->systemMenu) {
         qWarning("QMdiSubWindow::setSystemMenu: system menu is already set");
         return;
     }
     if (d->systemMenu) {
         delete d->systemMenu;
         d->systemMenu = 0;
     }
     if (!systemMenu)
         return;
     if (systemMenu->parent() != this)
         systemMenu->setParent(this);
     d->systemMenu = systemMenu;
 }
setWidget()
void QMdiSubWindow::setWidget (QWidget * widget)
Sets widget as the internal widget of this subwindow.
The internal widget is displayed in the center of the subwindow beneath the title bar.
QMdiSubWindow takes temporary ownership of widget; you do not have to delete it. Any existing internal widget will be removed and reparented to the root window.
See also
widget()
Definition at line 2313 of file qmdisubwindow.cpp.
Referenced by QMdiArea::addSubWindow(), and QMdiArea::removeSubWindow().
 {
     Q_D(QMdiSubWindow);
     if (!widget) {
         d->removeBaseWidget();
         return;
     }
     if (widget == d->baseWidget) {
         qWarning("QMdiSubWindow::setWidget: widget is already set");
         return;
     }
     bool wasResized = testAttribute(Qt::WA_Resized);
     d->removeBaseWidget();
     if (QLayout *layout = this->layout())
         layout->addWidget(widget);
     else
         widget->setParent(this);
 #ifndef QT_NO_SIZEGRIP
     QSizeGrip *sizeGrip = widget->findChild<QSizeGrip *>();
     if (sizeGrip)
         sizeGrip->installEventFilter(this);
     if (d->sizeGrip)
         d->sizeGrip->raise();
 #endif
     d->baseWidget = widget;
     d->baseWidget->installEventFilter(this);
     d->ignoreWindowTitleChange = true;
     bool isWindowModified = this->isWindowModified();
     if (windowTitle().isEmpty()) {
         d->updateWindowTitle(true);
         isWindowModified = d->baseWidget->isWindowModified();
     }
     if (!this->isWindowModified() && isWindowModified
             && windowTitle().contains(QLatin1String("[*]"))) {
         setWindowModified(isWindowModified);
     }
     d->lastChildWindowTitle = d->baseWidget->windowTitle();
     d->ignoreWindowTitleChange = false;
     if (windowIcon().isNull() && !d->baseWidget->windowIcon().isNull())
         setWindowIcon(d->baseWidget->windowIcon());
     d->updateGeometryConstraints();
     if (!wasResized && testAttribute(Qt::WA_Resized))
         setAttribute(Qt::WA_Resized, false);
 }
showEvent()
void QMdiSubWindow::showEvent (QShowEvent * showEvent) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2946 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (!parent()) {
         QWidget::showEvent(showEvent);
         return;
     }
 #if !defined(QT_NO_SIZEGRIP) && defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     if (qobject_cast<QMacStyle *>(style()) && !d->sizeGrip
             && !(windowFlags() & Qt::FramelessWindowHint)) {
         d->setSizeGrip(new QSizeGrip(0));
         Q_ASSERT(d->sizeGrip);
         if (isMinimized())
             d->setSizeGripVisible(false);
         else
             d->setSizeGripVisible(true);
         resize(size().expandedTo(d->internalMinimumSize));
     }
 #endif
     d->updateDirtyRegions();
     // Show buttons in the menu bar if they're already not there.
     // We want to do this when QMdiSubWindow becomes visible after being hidden.
 #ifndef QT_NO_MENUBAR
     if (d->controlContainer) {
         if (QMenuBar *menuBar = d->menuBar()) {
             if (menuBar->cornerWidget(Qt::TopRightCorner) != maximizedButtonsWidget())
                 d->showButtonsInMenuBar(menuBar);
         }
     }
 #endif
     d->setActive(true);
 }
showShaded
void QMdiSubWindow::showShaded () slot
Calling this function makes the subwindow enter the shaded mode.
When the subwindow is shaded, only the title bar is visible.
Although shading is not supported by all styles, this function will still show the subwindow as shaded, regardless of whether support for shading is available. However, when used with styles without shading support, the user will be unable to return from shaded mode through the user interface (e.g., through a shade button in the title bar).
See also
isShaded()
Definition at line 2623 of file qmdisubwindow.cpp.
Referenced by event(), and mouseDoubleClickEvent().
 {
     if (!parent())
         return;
     Q_D(QMdiSubWindow);
     // setMinimizeMode uses this function.
     if (!d->isShadeRequestFromMinimizeMode && isShaded())
         return;
     d->isMaximizeMode = false;
     QWidget *currentFocusWidget = QApplication::focusWidget();
     if (!d->restoreFocusWidget && isAncestorOf(currentFocusWidget))
         d->restoreFocusWidget = currentFocusWidget;
     if (!d->isShadeRequestFromMinimizeMode) {
         d->isShadeMode = true;
         d->ensureWindowState(Qt::WindowMinimized);
     }
 #ifndef QT_NO_MENUBAR
     d->removeButtonsFromMenuBar();
 #endif
     // showMinimized() will reset Qt::WindowActive, which makes sense
     // for top level widgets, but in MDI it makes sense to have an
     // active window which is minimized.
     if (hasFocus() || isAncestorOf(currentFocusWidget))
         d->ensureWindowState(Qt::WindowActive);
 #ifndef QT_NO_SIZEGRIP
     d->setSizeGripVisible(false);
 #endif
     if (!d->restoreSize.isValid() || d->isShadeMode) {
         d->oldGeometry = geometry();
         d->restoreSize.setWidth(d->oldGeometry.width());
         d->restoreSize.setHeight(d->oldGeometry.height());
     }
     // Hide the window before we change the geometry to avoid multiple resize
     // events and wrong window state.
     const bool wasVisible = isVisible();
     if (wasVisible)
         setVisible(false);
     d->updateGeometryConstraints();
     // Update minimum size to internalMinimumSize if set by user.
     if (!minimumSize().isNull()) {
         d->userMinimumSize = minimumSize();
         setMinimumSize(d->internalMinimumSize);
     }
     resize(d->internalMinimumSize);
     // Hide the internal widget if not already hidden by the user.
     if (d->baseWidget && !d->baseWidget->isHidden()) {
         d->baseWidget->hide();
         d->isWidgetHiddenByUs = true;
     }
     if (wasVisible)
         setVisible(true);
     d->setFocusWidget();
     d->resizeEnabled = false;
     d->moveEnabled = true;
     d->updateDirtyRegions();
     d->updateMask();
 #ifndef QT_NO_ACTION
     d->setEnabled(QMdiSubWindowPrivate::MinimizeAction, false);
     d->setEnabled(QMdiSubWindowPrivate::ResizeAction, d->resizeEnabled);
     d->setEnabled(QMdiSubWindowPrivate::MaximizeAction, true);
     d->setEnabled(QMdiSubWindowPrivate::RestoreAction, true);
     d->setEnabled(QMdiSubWindowPrivate::MoveAction, d->moveEnabled);
 #endif
 }
showSystemMenu
void QMdiSubWindow::showSystemMenu () slot
Shows the system menu below the system menu icon in the title bar.
See also
setSystemMenu(), systemMenu()
Definition at line 2560 of file qmdisubwindow.cpp.
Referenced by mousePressEvent().
 {
     Q_D(QMdiSubWindow);
     if (!d->systemMenu)
         return;
     QPoint globalPopupPos;
     if (QWidget *icon = maximizedSystemMenuIconWidget()) {
         if (isLeftToRight())
             globalPopupPos = icon->mapToGlobal(QPoint(0, icon->y() + icon->height()));
         else
             globalPopupPos = icon->mapToGlobal(QPoint(icon->width(), icon->y() + icon->height()));
     } else {
         if (isLeftToRight())
             globalPopupPos = mapToGlobal(contentsRect().topLeft());
         else // + QPoint(1, 0) because topRight() == QPoint(left() + width() -1, top())
             globalPopupPos = mapToGlobal(contentsRect().topRight()) + QPoint(1, 0);
     }
     // Adjust x() with -menuwidth in reverse mode.
     if (isRightToLeft())
         globalPopupPos -= QPoint(d->systemMenu->sizeHint().width(), 0);
     d->systemMenu->installEventFilter(this);
     d->systemMenu->popup(globalPopupPos);
 }
sizeHint()
QSize QMdiSubWindow::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3505 of file qmdisubwindow.cpp.
Referenced by QMdiAreaPrivate::appendChild(), QMdiArea::showEvent(), and QMdiArea::sizeHint().
 {
     Q_D(const QMdiSubWindow);
     int margin, minWidth;
     d->sizeParameters(&margin, &minWidth);
     QSize size(2 * margin, d->titleBarHeight() + margin);
     if (d->baseWidget && d->baseWidget->sizeHint().isValid())
         size += d->baseWidget->sizeHint();
     return size.expandedTo(minimumSizeHint());
 }
systemMenu()
QMenu * QMdiSubWindow::systemMenu () const
Returns a pointer to the current system menu, or zero if no system menu is set.
QMdiSubWindow provides a default system menu, but you can also set the menu with setSystemMenu().
See also
setSystemMenu(), showSystemMenu()
Definition at line 2550 of file qmdisubwindow.cpp.
Referenced by setSystemMenu().
 {
     return d_func()->systemMenu;
 }
testOption()
bool QMdiSubWindow::testOption (SubWindowOption option) const
Returns true if option is enabled; otherwise returns false.
See also
SubWindowOption, setOption()
Definition at line 2439 of file qmdisubwindow.cpp.
Referenced by eventFilter(), and mousePressEvent().
 {
     return d_func()->options & option;
 }
timerEvent()
void QMdiSubWindow::timerEvent (QTimerEvent * timerEvent) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 3118 of file qmdisubwindow.cpp.
 {
     Q_D(QMdiSubWindow);
     if (timerEvent->timerId() == d->resizeTimerId) {
         killTimer(d->resizeTimerId);
         d->resizeTimerId = -1;
         d->updateDirtyRegions();
     }
 }
widget()
QWidget * QMdiSubWindow::widget () const
Returns the current internal widget.
See also
setWidget()
Definition at line 2371 of file qmdisubwindow.cpp.
Referenced by QAccessibleMdiSubWindow::indexOfChild(), QAccessibleMdiSubWindow::navigate(), QMdiArea::removeSubWindow(), and setWidget().
 {
     return d_func()->baseWidget;
 }
windowStateChanged
QMdiSubWindow::windowStateChanged (Qt::WindowStates oldState, Qt::WindowStates newState) signal
QMdiSubWindow emits this signal after the window state changes.
oldState is the window state before it changed, and newState is the new, current state.
Referenced by changeEvent().
Friends and Related Functions
QMdi::ControlContainer
friend class QMdi::ControlContainer friend
Definition at line 148 of file qmdisubwindow.h.
QMdiAreaPrivate
friend class QMdiAreaPrivate friend
Definition at line 144 of file qmdisubwindow.h.
QMdiAreaTabBar
friend class QMdiAreaTabBar friend
Definition at line 146 of file qmdisubwindow.h.
Properties
keyboardPageStep
int QMdiSubWindow::keyboardPageStep private
sets how far a widget should move or resize when using the keyboard page keys.
When in keyboard-interactive mode, you can use the arrow and page keys to either move or resize the window. This property controls the page keys. The common way to enter keyboard interactive mode is to enter the subwindow menu, and select either "resize" or "move".
The default keyboard page step value is 20 pixels.
See also
keyboardSingleStep
Definition at line 64 of file qmdisubwindow.h.
keyboardSingleStep
int QMdiSubWindow::keyboardSingleStep private
sets how far a widget should move or resize when using the keyboard arrow keys.
When in keyboard-interactive mode, you can use the arrow and page keys to either move or resize the window. This property controls the arrow keys. The common way to enter keyboard interactive mode is to enter the subwindow menu, and select either "resize" or "move".
The default keyboard single step value is 5 pixels.
See also
keyboardPageStep
Definition at line 63 of file qmdisubwindow.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qmdisubwindow.h
/src/gui/widgets/qmdisubwindow.cpp