Qt 4.8: QAccessibleTextEdit Class Reference
QAccessibleTextEdit Class Reference
The QAccessibleTextEdit class implements the QAccessibleInterface for richtext editors.
#include <qaccessiblewidgets.h>
Public Functions
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
void copyText (int startOffset, int endOffset)
void cutText (int startOffset, int endOffset)
QVariant invokeMethodEx (QAccessible::Method method, int child, const QVariantList &params)
void pasteText (int offset)
QAccessibleTextEdit (QWidget *o)
Constructs a QAccessibleTextEdit object for a widget.
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Role role (int child) const
Reimplemented Function
void scrollToSubstring (int startIndex, int endIndex)
void setAttributes (int startOffset, int endOffset, const QString &attributes)
void setText (Text t, int control, const QString &text)
Reimplemented Function
QString text (Text t, int child) const
Reimplemented Function
Public Functions inherited from QAccessibleTextWidget
void addSelection (int startOffset, int endOffset)
QString attributes (int offset, int *startOffset, int *endOffset)
int characterCount ()
QRect characterRect (int offset, QAccessible2::CoordinateType coordType)
int cursorPosition ()
void deleteText (int startOffset, int endOffset)
void insertText (int offset, const QString &text)
int offsetAtPoint (const QPoint &point, QAccessible2::CoordinateType coordType)
QAccessibleTextWidget (QWidget *o, Role r=EditableText, const QString &name=QString())
void removeSelection (int selectionIndex)
void replaceText (int startOffset, int endOffset, const QString &text)
void selection (int selectionIndex, int *startOffset, int *endOffset)
int selectionCount ()
void setCursorPosition (int position)
void setSelection (int selectionIndex, int startOffset, int endOffset)
QString text (int startOffset, int endOffset)
QString textAfterOffset (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset)
QString textAtOffset (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset)
QString textBeforeOffset (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset)
Public Functions inherited from QAccessibleWidgetEx
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
int navigate (RelationFlag rel, int entry, QAccessibleInterface **target) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleObjectEx
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Public Functions inherited from QAccessibleTextInterface
QAccessible2Interface * qAccessibleTextCastHelper ()
virtual ~QAccessibleTextInterface ()
Public Functions inherited from QAccessible2Interface
virtual ~QAccessible2Interface ()
Public Functions inherited from QAccessibleEditableTextInterface
QAccessible2Interface * qAccessibleEditableTextCastHelper ()
virtual ~QAccessibleEditableTextInterface ()
Protected Functions
QPoint scrollBarPosition () const
void setTextCursor (const QTextCursor &textCursor)
QTextCursor textCursor () const
QTextDocument * textDocument () const
QTextEdit * textEdit () const
Returns the text edit.
QWidget * viewport () const
Protected Functions inherited from QAccessibleTextWidget
QPair< int, int > getBoundaries (int offset, QAccessible2::BoundaryType boundaryType)
QTextCursor textCursorForRange (int startOffset, int endOffset) const
Protected Functions inherited from QAccessibleWidgetEx
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Properties
int childOffset
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
The QAccessibleTextEdit class implements the QAccessibleInterface for richtext editors.
Warning
This function is not part of the public interface.
Definition at line 143 of file qaccessiblewidgets.h.
Constructors and Destructors
QAccessibleTextEdit()
QAccessibleTextEdit::QAccessibleTextEdit (QWidget * o) explicit
Constructs a QAccessibleTextEdit object for a widget.
Definition at line 308 of file qaccessiblewidgets.cpp.
 : QAccessibleTextWidget(o, EditableText)
 {
     Q_ASSERT(widget()->inherits("QTextEdit"));
     childOffset = QAccessibleWidgetEx::childCount();
 }
Functions
childAt()
int QAccessibleTextEdit::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Reimplemented from QAccessibleWidgetEx.
Definition at line 369 of file qaccessiblewidgets.cpp.
 {
     QTextEdit *edit = textEdit();
     if (!edit->isVisible())
         return -1;
     QPoint point = edit->viewport()->mapFromGlobal(QPoint(x, y));
     QTextBlock block = edit->cursorForPosition(point).block();
     if (block.isValid())
         return qTextBlockPosition(block) + childOffset;
     return QAccessibleWidgetEx::childAt(x, y);
 }
childCount()
int QAccessibleTextEdit::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Reimplemented from QAccessibleWidgetEx.
Definition at line 450 of file qaccessiblewidgets.cpp.
 {
     return childOffset + textEdit()->document()->blockCount();
 }
copyText()
void QAccessibleTextEdit::copyText (int startOffset, int endOffset) virtual
Reimplemented from QAccessibleTextWidget.
Definition at line 1826 of file qaccessiblewidgets.cpp.
 {
 #ifndef QT_NO_CLIPBOARD
     QTextCursor previousCursor = textEdit()->textCursor();
     QTextCursor cursor = textCursorForRange(startOffset, endOffset);
     if (!cursor.hasSelection())
         return;
     textEdit()->setTextCursor(cursor);
     textEdit()->copy();
     textEdit()->setTextCursor(previousCursor);
 #endif
 }
cutText()
void QAccessibleTextEdit::cutText (int startOffset, int endOffset) virtual
Reimplemented from QAccessibleTextWidget.
Definition at line 1841 of file qaccessiblewidgets.cpp.
 {
 #ifndef QT_NO_CLIPBOARD
     QTextCursor cursor = textCursorForRange(startOffset, endOffset);
     if (!cursor.hasSelection())
         return;
     textEdit()->setTextCursor(cursor);
     textEdit()->cut();
 #endif
 }
invokeMethodEx()
QVariant QAccessibleTextEdit::invokeMethodEx (QAccessible::Method method, int child, const QVariantList & params) virtual
Reimplemented from QAccessibleWidgetEx.
Definition at line 427 of file qaccessiblewidgets.cpp.
 {
     if (child)
         return QVariant();
     switch (method) {
     case ListSupportedMethods: {
         QSet<QAccessible::Method> set;
         set << ListSupportedMethods << SetCursorPosition << GetCursorPosition;
         return QVariant::fromValue(set | qvariant_cast<QSet<QAccessible::Method> >(
                     QAccessibleWidgetEx::invokeMethodEx(method, child, params)));
     }
     case SetCursorPosition:
         setCursorPosition(params.value(0).toInt());
         return true;
     case GetCursorPosition:
         return textEdit()->textCursor().position();
     default:
         return QAccessibleWidgetEx::invokeMethodEx(method, child, params);
     }
 }
pasteText()
void QAccessibleTextEdit::pasteText (int offset) virtual
Reimplemented from QAccessibleTextWidget.
Definition at line 1854 of file qaccessiblewidgets.cpp.
 {
     QTextEdit *edit = textEdit();
     QTextCursor oldCursor = edit->textCursor();
     QTextCursor newCursor = oldCursor;
     newCursor.setPosition(offset);
     edit->setTextCursor(newCursor);
 #ifndef QT_NO_CLIPBOARD
     edit->paste();
 #endif
     edit->setTextCursor(oldCursor);
 }
rect()
QRect QAccessibleTextEdit::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Reimplemented from QAccessibleWidgetEx.
Definition at line 349 of file qaccessiblewidgets.cpp.
 {
     if (child <= childOffset)
         return QAccessibleWidgetEx::rect(child);
      QTextEdit *edit = textEdit();
      QTextBlock block = qTextBlockAt(edit->document(), child - childOffset - 1);
      if (!block.isValid())
          return QRect();
      QRect rect = edit->document()->documentLayout()->blockBoundingRect(block).toRect();
      rect.translate(-edit->horizontalScrollBar()->value(), -edit->verticalScrollBar()->value());
      rect = edit->viewport()->rect().intersect(rect);
      if (rect.isEmpty())
          return QRect();
      return rect.translated(edit->viewport()->mapToGlobal(QPoint(0, 0)));
 }
role()
QAccessible::Role QAccessibleTextEdit::role (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleTextBrowser.
Definition at line 420 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleTextBrowser::role().
 {
     if (child > childOffset)
         return EditableText;
     return QAccessibleWidgetEx::role(child);
 }
scrollBarPosition()
QPoint QAccessibleTextEdit::scrollBarPosition () const protected virtual
Reimplemented from QAccessibleTextWidget.
Definition at line 341 of file qaccessiblewidgets.cpp.
 {
     QPoint result;
     result.setX(textEdit()->horizontalScrollBar() ? textEdit()->horizontalScrollBar()->sliderPosition() : 0);
     result.setY(textEdit()->verticalScrollBar() ? textEdit()->verticalScrollBar()->sliderPosition() : 0);
     return result;
 }
scrollToSubstring()
void QAccessibleTextEdit::scrollToSubstring (int startIndex, int endIndex) virtual
Implements QAccessibleTextInterface.
Definition at line 1807 of file qaccessiblewidgets.cpp.
 {
     QTextEdit *edit = textEdit();
     QTextCursor cursor(edit->document());
     cursor.setPosition(startIndex);
     QRect r = edit->cursorRect(cursor);
     cursor.setPosition(endIndex);
     r.setBottomRight(edit->cursorRect(cursor).bottomRight());
     r.moveTo(r.x() + edit->horizontalScrollBar()->value(),
              r.y() + edit->verticalScrollBar()->value());
     // E V I L, but ensureVisible is not public
     if (!QMetaObject::invokeMethod(edit, "_q_ensureVisible", Q_ARG(QRectF, r)))
         qWarning("AccessibleTextEdit::scrollToSubstring failed!");
 }
setAttributes()
void QAccessibleTextEdit::setAttributes (int startOffset, int endOffset, const QString & attributes) virtual
Reimplemented from QAccessibleTextWidget.
Definition at line 1869 of file qaccessiblewidgets.cpp.
 {
     // TODO
     Q_UNUSED(startOffset);
     Q_UNUSED(endOffset);
     Q_UNUSED(attributes);
 }
setText()
void QAccessibleTextEdit::setText (Text t, int control, const QString & text) virtual
Reimplemented Function
Reimplemented from QAccessibleObjectEx.
Definition at line 397 of file qaccessiblewidgets.cpp.
 {
     if (t != Value || (child > 0 && child <= childOffset)) {
         QAccessibleWidgetEx::setText(t, child, text);
         return;
     }
     if (textEdit()->isReadOnly())
         return;
     if (!child) {
         textEdit()->setText(text);
         return;
     }
     QTextBlock block = qTextBlockAt(textEdit()->document(), child - childOffset - 1);
     if (!block.isValid())
         return;
     QTextCursor cursor(block);
     cursor.select(QTextCursor::BlockUnderCursor);
     cursor.insertText(text);
 }
setTextCursor()
void QAccessibleTextEdit::setTextCursor (const QTextCursor & textCursor) protected virtual
Implements QAccessibleTextWidget.
Definition at line 331 of file qaccessiblewidgets.cpp.
 {
     textEdit()->setTextCursor(textCursor);
 }
text()
QString QAccessibleTextEdit::text (Text t, int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 384 of file qaccessiblewidgets.cpp.
 {
     if (t == Value) {
         if (child > childOffset)
             return qTextBlockAt(textEdit()->document(), child - childOffset - 1).text();
         if (!child)
             return textEdit()->toPlainText();
     }
     return QAccessibleWidgetEx::text(t, child);
 }
textCursor()
QTextCursor QAccessibleTextEdit::textCursor () const protected virtual
Implements QAccessibleTextWidget.
Definition at line 321 of file qaccessiblewidgets.cpp.
 {
     return textEdit()->textCursor();
 }
textDocument()
QTextDocument * QAccessibleTextEdit::textDocument () const protected virtual
Implements QAccessibleTextWidget.
Definition at line 326 of file qaccessiblewidgets.cpp.
 {
     return textEdit()->document();
 }
textEdit()
QTextEdit * QAccessibleTextEdit::textEdit () const protected
Returns the text edit.
Definition at line 316 of file qaccessiblewidgets.cpp.
Referenced by childAt(), childCount(), invokeMethodEx(), rect(), scrollBarPosition(), setText(), setTextCursor(), text(), textCursor(), textDocument(), and viewport().
 {
     return static_cast<QTextEdit *>(widget());
 }
viewport()
QWidget * QAccessibleTextEdit::viewport () const protected virtual
Implements QAccessibleTextWidget.
Definition at line 336 of file qaccessiblewidgets.cpp.
 {
     return textEdit()->viewport();
 }
Properties
childOffset
int QAccessibleTextEdit::childOffset private
Definition at line 178 of file qaccessiblewidgets.h.
Referenced by childAt(), childCount(), QAccessibleTextEdit(), rect(), role(), setText(), and text().
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/qaccessiblewidgets.h
/src/plugins/accessible/widgets/qaccessiblewidgets.cpp