Qt 4.8: QAxHostWidget Class Reference
QAxHostWidget Class Reference
Public Functions
QAxClientSite * clientSite () const
QSize minimumSizeHint () const
Q_OBJECT_CHECK QAxHostWidget (QWidget *parent, QAxClientSite *ax)
int qt_metacall (QMetaObject::Call, int isignal, void **argv)
void * qt_metacast (const char *clname)
QSize sizeHint () const
~QAxHostWidget ()
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
bool event (QEvent *e)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
bool eventFilter (QObject *o, QEvent *e)
Filters events if this object has been installed as an event filter for the watched object.
void focusInEvent (QFocusEvent *e)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
void focusOutEvent (QFocusEvent *e)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
QPaintEngine * paintEngine () const
void paintEvent (QPaintEvent *e)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
void resizeEvent (QResizeEvent *e)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
void showEvent (QShowEvent *e)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
bool winEvent (MSG *msg, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void resizeObject ()
Properties
QAxClientSite * axhost
bool hasFocus
int setFocusTimer
Friends
class QAxClientSite
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 106 of file qaxwidget.cpp.
Constructors and Destructors
QAxHostWidget()
QAxHostWidget::QAxHostWidget (QWidget * parent, QAxClientSite * ax)
Definition at line 1625 of file qaxwidget.cpp.
 : QWidget(parent), setFocusTimer(0), hasFocus(false), axhost(ax)
 {
     setAttribute(Qt::WA_NoBackground);
     setAttribute(Qt::WA_NoSystemBackground);
     setAttribute(Qt::WA_OpaquePaintEvent);
     setAttribute(Qt::WA_PaintOnScreen);
     setObjectName(parent->objectName() + QLatin1String(" - QAxHostWidget"));
 }
~QAxHostWidget()
QAxHostWidget::~QAxHostWidget ()
Definition at line 1636 of file qaxwidget.cpp.
 {
     if (axhost)
         axhost->reset(this);
 }
Functions
clientSite()
QAxClientSite* QAxHostWidget::clientSite () const inline
Definition at line 120 of file qaxwidget.cpp.
Referenced by axc_FilterProc().
     {
         return axhost;
     }
event()
bool QAxHostWidget::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 1722 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     switch (e->type()) {
     case QEvent::Timer:
         if (axhost && ((QTimerEvent*)e)->timerId() == setFocusTimer) {
             killTimer(setFocusTimer);
             setFocusTimer = 0;
             RECT rcPos = { x(), y(), x()+size().width(), y()+size().height() };
             axhost->m_spOleObject->DoVerb(OLEIVERB_UIACTIVATE, 0, (IOleClientSite*)axhost, 0, winId(), &rcPos);
             if (axhost->m_spActiveView)
                 axhost->m_spActiveView->UIActivate(TRUE);
         }
         break;
     case QEvent::WindowBlocked:
         if (IsWindowEnabled(winId())) {
             EnableWindow(winId(), false);
             if (axhost && axhost->m_spInPlaceActiveObject) {
                 axhost->inPlaceModelessEnabled = false;
                 axhost->m_spInPlaceActiveObject->EnableModeless(false);
             }
         }
         break;
     case QEvent::WindowUnblocked:
         if (!IsWindowEnabled(winId())) {
             EnableWindow(winId(), true);
             if (axhost && axhost->m_spInPlaceActiveObject) {
                 axhost->inPlaceModelessEnabled = true;
                 axhost->m_spInPlaceActiveObject->EnableModeless(true);
             }
         }
         break;
     default:
         break;
     }
     return QWidget::event(e);
 }
eventFilter()
bool QAxHostWidget::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 1760 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     // focus goes to Qt while ActiveX still has it - deactivate
     QWidget *newFocus = qobject_cast<QWidget*>(o);
     if (e->type() == QEvent::FocusIn && hasFocus
         && newFocus && newFocus->window() == window()) {
         if (axhost && axhost->m_spInPlaceActiveObject && axhost->m_spInPlaceObject)
             axhost->m_spInPlaceObject->UIDeactivate();
         qApp->removeEventFilter(this);
     }
     return QWidget::eventFilter(o, e);
 }
focusInEvent()
void QAxHostWidget::focusInEvent (QFocusEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
The event is passed in the event parameter
A widget normally must setFocusPolicy() to something other than Qt::NoFocus in order to receive focus events. (Note that the application programmer can call setFocus() on any widget, even those that do not normally accept focus.)
The default implementation updates the widget (except for windows that do not specify a focusPolicy()).
See also
focusOutEvent(), setFocusPolicy(), keyPressEvent(), keyReleaseEvent(), event(), QFocusEvent
Reimplemented from QWidget.
Definition at line 1774 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     QWidget::focusInEvent(e);
     if (!axhost || !axhost->m_spOleObject)
         return;
     // this is called by QWidget::setFocus which calls ::SetFocus on "this",
     // so we have to UIActivate the control after all that had happend.
     AX_DEBUG(Setting focus on in-place object);
     setFocusTimer = startTimer(0);
 }
focusOutEvent()
void QAxHostWidget::focusOutEvent (QFocusEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
The events is passed in the event parameter.
A widget normally must setFocusPolicy() to something other than Qt::NoFocus in order to receive focus events. (Note that the application programmer can call setFocus() on any widget, even those that do not normally accept focus.)
The default implementation updates the widget (except for windows that do not specify a focusPolicy()).
See also
focusInEvent(), setFocusPolicy(), keyPressEvent(), keyReleaseEvent(), event(), QFocusEvent
Reimplemented from QWidget.
Definition at line 1787 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     QWidget::focusOutEvent(e);
     if (setFocusTimer) {
         killTimer(setFocusTimer);
         setFocusTimer = 0;
     }
     if (e->reason() == Qt::PopupFocusReason || e->reason() == Qt::MenuBarFocusReason)
         return;
     if (!axhost || !axhost->m_spInPlaceActiveObject || !axhost->m_spInPlaceObject)
         return;
     AX_DEBUG(Deactivating in-place object);
     axhost->m_spInPlaceObject->UIDeactivate();
 }
minimumSizeHint()
QSize QAxHostWidget::minimumSizeHint () const virtual
Reimplemented from QWidget.
Definition at line 1662 of file qaxwidget.cpp.
Referenced by QAxClientSite::sizeHint().
 {
     QSize size;
     if (axhost)
         size = axhost->minimumSizeHint();
     if (size.isValid())
         return size;
     return QWidget::minimumSizeHint();
 }
paintEngine()
QPaintEngine* QAxHostWidget::paintEngine () const inline protected virtual
Implements QPaintDevice.
Definition at line 134 of file qaxwidget.cpp.
     {
         return 0;
     }
paintEvent()
void QAxHostWidget::paintEvent (QPaintEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive paint events passed in event.
A paint event is a request to repaint all or part of a widget. It can happen for one of the following reasons:
repaint() or update() was invoked,
the widget was obscured and has now been uncovered, or
many other reasons.
Many widgets can simply repaint their entire surface when asked to, but some slow widgets need to optimize by painting only the requested region: QPaintEvent::region(). This speed optimization does not change the result, as painting is clipped to that region during event processing. QListView and QTableView do this, for example.
Qt also tries to speed up painting by merging multiple paint events into one. When update() is called several times or the window system sends several paint events, Qt merges these events into one event with a larger region (see QRegion::united()). The repaint() function does not permit this optimization, so we suggest using update() whenever possible.
When the paint event occurs, the update region has normally been erased, so you are painting on the widget's background.
The background can be set using setBackgroundRole() and setPalette().
Since Qt 4.0, QWidget automatically double-buffers its painting, so there is no need to write double-buffering code in paintEvent() to avoid flicker.
Note for the X11 platform: It is possible to toggle global double buffering by calling qt_x11_set_global_double_buffer(). For example,
...
extern void qt_x11_set_global_double_buffer(bool);
qt_x11_set_global_double_buffer(false);
...
Note
Generally, you should refrain from calling update() or repaint() inside a paintEvent(). For example, calling update() or repaint() on children inside a paintevent() results in undefined behavior; the child may or may not get a paint event.
Warning
If you are using a custom paint engine without Qt's backingstore, Qt::WA_PaintOnScreen must be set. Otherwise, QWidget::paintEngine() will never be called; the backingstore will be used instead.
See also
event(), repaint(), update(), QPainter, QPixmap, QPaintEvent, {Analog Clock Example}
Reimplemented from QWidget.
Definition at line 1805 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     if (!QPainter::redirected(this))
         return;
     IViewObject *view = 0;
     if (axhost)
         axhost->widget->queryInterface(IID_IViewObject, (void**)&view);
     if (!view)
         return;
     // somebody tries to grab us!
     QPixmap pm(size());
     pm.fill();
     HBITMAP hBmp = pm.toWinHBITMAP();
     HDC hBmp_hdc = CreateCompatibleDC(qt_win_display_dc());
     HGDIOBJ old_hBmp = SelectObject(hBmp_hdc, hBmp);
     RECTL bounds;
     bounds.left = 0;
     bounds.right = pm.width();
     bounds.top = 0;
     bounds.bottom = pm.height();
     view->Draw(DVASPECT_CONTENT, -1, 0, 0, 0, hBmp_hdc, &bounds, 0, 0 /*fptr*/, 0);
     view->Release();
     QPainter painter(this);
     painter.drawPixmap(0, 0, QPixmap::fromWinHBITMAP(hBmp));
     SelectObject(hBmp_hdc, old_hBmp);
     DeleteObject(hBmp);
     DeleteDC(hBmp_hdc);
 }
qt_metacall()
int QAxHostWidget::qt_metacall (QMetaObject::Call call, int isignal, void ** argv)
Definition at line 1642 of file qaxwidget.cpp.
Referenced by QAxClientSite::translateKeyEvent().
 {
     if (axhost)
         return axhost->qt_metacall(call, isignal, argv);
     return -1;
 }
qt_metacast()
void * QAxHostWidget::qt_metacast (const char * clname)
Definition at line 1649 of file qaxwidget.cpp.
 {
     if (!clname) return 0;
     if (!qstrcmp(clname,"QAxHostWidget"))
         return static_cast<void*>(const_cast< QAxHostWidget*>(this));
     return QWidget::qt_metacast(clname);
 }
resizeEvent()
void QAxHostWidget::resizeEvent (QResizeEvent *) protected virtual
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
When resizeEvent() is called, the widget already has its new geometry. The old size is accessible through QResizeEvent::oldSize().
The widget will be erased and receive a paint event immediately after processing the resize event. No drawing need be (or should be) done inside this handler.
See also
moveEvent(), event(), resize(), QResizeEvent, paintEvent(), {Scribble Example}
Reimplemented from QWidget.
Definition at line 1698 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     resizeObject();
 }
resizeObject()
void QAxHostWidget::resizeObject () private
Definition at line 1672 of file qaxwidget.cpp.
Referenced by paintEngine(), resizeEvent(), and showEvent().
 {
     if (!axhost)
         return;
     // document server - talk to view?
     if (axhost->m_spActiveView) {
         RECT rect;
         GetClientRect(winId(), &rect);
         axhost->m_spActiveView->SetRect(&rect);
         return;
     }
     SIZEL hmSize;
     hmSize.cx = MAP_PIX_TO_LOGHIM(width(), logicalDpiX());
     hmSize.cy = MAP_PIX_TO_LOGHIM(height(), logicalDpiY());
     if (axhost->m_spOleObject)
         axhost->m_spOleObject->SetExtent(DVASPECT_CONTENT, &hmSize);
     if (axhost->m_spInPlaceObject) {
         RECT rcPos = { x(), y(), x()+width(), y()+height() };
         axhost->m_spInPlaceObject->SetObjectRects(&rcPos, &rcPos);
     }
 }
showEvent()
void QAxHostWidget::showEvent (QShowEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
Non-spontaneous show events are sent to widgets immediately before they are shown. The spontaneous show events of windows are delivered afterwards.
Note: A widget receives spontaneous show and hide events when its mapping status is changed by the window system, e.g. a spontaneous hide event when the user minimizes the window, and a spontaneous show event when the window is restored again. After receiving a spontaneous hide event, a widget is still considered visible in the sense of isVisible().
See also
visible, event(), QShowEvent
Reimplemented from QWidget.
Definition at line 1703 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     resizeObject();
 }
sizeHint()
QSize QAxHostWidget::sizeHint () const virtual
Reimplemented from QWidget.
Definition at line 1657 of file qaxwidget.cpp.
 {
     return axhost ? axhost->sizeHint() : QWidget::sizeHint();
 }
winEvent()
bool QAxHostWidget::winEvent (MSG * message, long * result) protected virtual
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
In your reimplementation of this function, if you want to stop the event being handled by Qt, return true and set result to the value that the window procedure should return. If you return false, this native event is passed back to Qt, which translates the event into a Qt event and sends it to the widget.
Warning
This function is not portable.
See also
QApplication::winEventFilter()
Reimplemented from QWidget.
Definition at line 1708 of file qaxwidget.cpp.
Referenced by clientSite().
 {
     if (axhost && axhost->inPlaceObjectWindowless) {
         Q_ASSERT(axhost->m_spInPlaceObject);
         IOleInPlaceObjectWindowless *windowless = (IOleInPlaceObjectWindowless*)axhost->m_spInPlaceObject;
         Q_ASSERT(windowless);
         LRESULT lres;
         HRESULT hres = windowless->OnWindowMessage(msg->message, msg->wParam, msg->lParam, &lres);
         if (hres == S_OK)
             return true;
     }
     return QWidget::winEvent(msg, result);
 }
Friends and Related Functions
QAxClientSite
friend class QAxClientSite friend
Definition at line 108 of file qaxwidget.cpp.
Properties
axhost
QAxClientSite* QAxHostWidget::axhost private
Definition at line 144 of file qaxwidget.cpp.
Referenced by clientSite(), event(), eventFilter(), focusInEvent(), focusOutEvent(), minimumSizeHint(), paintEvent(), qt_metacall(), resizeObject(), sizeHint(), winEvent(), QAxClientSite::~QAxClientSite(), and ~QAxHostWidget().
hasFocus
bool QAxHostWidget::hasFocus private
Definition at line 143 of file qaxwidget.cpp.
Referenced by QAxClientSite::OnFocus(), and QAxClientSite::OnUIDeactivate().
setFocusTimer
int QAxHostWidget::setFocusTimer private
Definition at line 142 of file qaxwidget.cpp.
Referenced by event(), focusInEvent(), and focusOutEvent().
The documentation for this class was generated from the following file:
/src/activeqt/container/qaxwidget.cpp