Qt 4.8: QCryptographicHash Class Reference
QCryptographicHash Class Reference
The QCryptographicHash class provides a way to generate cryptographic hashes.
#include <qcryptographichash.h>
Public Types
enum Algorithm { Md4, Md5, Sha1 }
Public Functions
void addData (const char *data, int length)
Adds the first length chars of data to the cryptographic hash.
void addData (const QByteArray &data)
QCryptographicHash (Algorithm method)
Constructs an object that can be used to create a cryptographic hash from data using method.
void reset ()
Resets the object.
QByteArray result () const
Returns the final hash value.
~QCryptographicHash ()
Destroys the object.
Static Public Functions
static QByteArray hash (const QByteArray &data, Algorithm method)
Returns the hash of data using method.
Properties
QCryptographicHashPrivate * d
Detailed Description
The QCryptographicHash class provides a way to generate cryptographic hashes.
Since
4.3
Note
This class or function is reentrant.
QCryptographicHash can be used to generate cryptographic hashes of binary or text data.
Currently MD4, MD5, and SHA-1 are supported.
Definition at line 55 of file qcryptographichash.h.
Enumerations
Algorithm
enum QCryptographicHash::Algorithm
Md4 Generate an MD4 hash sum
Md5 Generate an MD5 hash sum
Sha1 Generate an SHA1 hash sum
Enumerator
Md4
Md5
Sha1
Definition at line 58 of file qcryptographichash.h.
                    {
         Md4,
         Md5,
         Sha1
     };
Constructors and Destructors
QCryptographicHash()
QCryptographicHash::QCryptographicHash (Algorithm method)
Constructs an object that can be used to create a cryptographic hash from data using method.
Definition at line 98 of file qcryptographichash.cpp.
     : d(new QCryptographicHashPrivate)
 {
     d->method = method;
     reset();
 }
~QCryptographicHash()
QCryptographicHash::~QCryptographicHash ()
Destroys the object.
Definition at line 108 of file qcryptographichash.cpp.
 {
     delete d;
 }
Functions
addData() [1/2]
void QCryptographicHash::addData (const char * data, int length)
Adds the first length chars of data to the cryptographic hash.
Definition at line 136 of file qcryptographichash.cpp.
Referenced by addData(), digestMd5ResponseHelper(), hash(), qCreatev2Hash(), qEncodeHmacMd5(), qmlsqldatabase_open_sync(), qStringFromUcs2Le(), and QNetworkDiskCachePrivate::uniqueFileName().
 {
     switch (d->method) {
     case Md4:
         md4_update(&d->md4Context, (const unsigned char *)data, length);
         break;
     case Md5:
         MD5Update(&d->md5Context, (const unsigned char *)data, length);
         break;
     case Sha1:
         sha1Update(&d->sha1Context, (const unsigned char *)data, length);
         break;
     }
     d->result.clear();
 }
addData() [2/2]
void QCryptographicHash::addData (const QByteArray & data)
Definition at line 155 of file qcryptographichash.cpp.
 {
     addData(data.constData(), data.length());
 }
hash()
QByteArray QCryptographicHash::hash (const QByteArray & data, Algorithm method) static
Returns the hash of data using method.
Definition at line 196 of file qcryptographichash.cpp.
Referenced by QSslCertificate::digest(), QSharedMemoryPrivate::makePlatformSafeKey(), QDeclarativeEnginePrivate::md5(), and QAuthenticatorPrivate::QAuthenticatorPrivate().
 {
     QCryptographicHash hash(method);
     hash.addData(data);
     return hash.result();
 }
reset()
void QCryptographicHash::reset ()
Resets the object.
Definition at line 116 of file qcryptographichash.cpp.
Referenced by digestMd5ResponseHelper(), QCryptographicHash(), and qEncodeHmacMd5().
 {
     switch (d->method) {
     case Md4:
         md4_init(&d->md4Context);
         break;
     case Md5:
         MD5Init(&d->md5Context);
         break;
     case Sha1:
         sha1InitState(&d->sha1Context);
         break;
     }
     d->result.clear();
 }
result()
QByteArray QCryptographicHash::result () const
Returns the final hash value.
See also
QByteArray::toHex()
Definition at line 165 of file qcryptographichash.cpp.
Referenced by digestMd5ResponseHelper(), hash(), qCreatev2Hash(), qEncodeHmacMd5(), qmlsqldatabase_open_sync(), qStringFromUcs2Le(), and QNetworkDiskCachePrivate::uniqueFileName().
 {
     if (!d->result.isEmpty())
         return d->result;
     switch (d->method) {
     case Md4: {
         md4_context copy = d->md4Context;
         d->result.resize(MD4_RESULTLEN);
         md4_final(&copy, (unsigned char *)d->result.data());
         break;
     }
     case Md5: {
         MD5Context copy = d->md5Context;
         d->result.resize(16);
         MD5Final(&copy, (unsigned char *)d->result.data());
         break;
     }
     case Sha1: {
         Sha1State copy = d->sha1Context;
         d->result.resize(20);
         sha1FinalizeState(&copy);
         sha1ToHash(&copy, (unsigned char *)d->result.data());
     }
     }
     return d->result;
 }
Properties
d
QCryptographicHashPrivate* QCryptographicHash::d private
Definition at line 77 of file qcryptographichash.h.
Referenced by addData(), QCryptographicHash(), reset(), result(), and ~QCryptographicHash().
The documentation for this class was generated from the following files:
/src/corelib/tools/qcryptographichash.h
/src/corelib/tools/qcryptographichash.cpp