Qt 4.8: QDeclarativeDrag Class Reference
QDeclarativeDrag Class Reference
#include <qdeclarativemousearea_p.h>
Public Types
enum Axis { XAxis =0x01, YAxis =0x02, XandYAxis =0x03 }
Signals
void activeChanged ()
void axisChanged ()
void filterChildrenChanged ()
void maximumXChanged ()
void maximumYChanged ()
void minimumXChanged ()
void minimumYChanged ()
void targetChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool active () const
Axis axis () const
bool filterChildren () const
QDeclarativeDrag (QObject *parent=0)
void resetTarget ()
void setActive (bool)
void setAxis (Axis)
void setFilterChildren (bool)
void setTarget (QGraphicsObject *)
void setXmax (qreal)
void setXmin (qreal)
void setYmax (qreal)
void setYmin (qreal)
QGraphicsObject * target () const
qreal xmax () const
qreal xmin () const
qreal ymax () const
qreal ymin () const
~QDeclarativeDrag ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool _active: 1
Axis _axis
bool _filterChildren: 1
QGraphicsObject * _target
qreal _xmax
qreal _xmin
qreal _ymax
qreal _ymin
bool active
Axis axis
bool filterChildren
qreal maximumX
qreal maximumY
qreal minimumX
qreal minimumY
QGraphicsObject * target
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file qdeclarativemousearea_p.h.
Enumerations
Axis
enum QDeclarativeDrag::Axis
Enumerator
XAxis
YAxis
XandYAxis
Definition at line 76 of file qdeclarativemousearea_p.h.
 { XAxis=0x01, YAxis=0x02, XandYAxis=0x03 };
Constructors and Destructors
QDeclarativeDrag()
QDeclarativeDrag::QDeclarativeDrag (QObject * parent = 0)
Definition at line 54 of file qdeclarativemousearea.cpp.
 : QObject(parent), _target(0), _axis(XandYAxis), _xmin(-FLT_MAX), _xmax(FLT_MAX), _ymin(-FLT_MAX), _ymax(FLT_MAX),
 _active(false), _filterChildren(false)
 {
 }
~QDeclarativeDrag()
QDeclarativeDrag::~QDeclarativeDrag ()
Definition at line 60 of file qdeclarativemousearea.cpp.
 {
 }
Functions
active()
bool QDeclarativeDrag::active () const
Referenced by setYmax().
activeChanged
void QDeclarativeDrag::activeChanged () signal
Referenced by setActive().
axis()
Axis QDeclarativeDrag::axis () const
Referenced by resetTarget().
axisChanged
void QDeclarativeDrag::axisChanged () signal
Referenced by setAxis().
filterChildren()
bool QDeclarativeDrag::filterChildren () const
Referenced by setActive().
filterChildrenChanged
void QDeclarativeDrag::filterChildrenChanged () signal
Referenced by setFilterChildren().
maximumXChanged
void QDeclarativeDrag::maximumXChanged () signal
Referenced by setXmax().
maximumYChanged
void QDeclarativeDrag::maximumYChanged () signal
Referenced by setYmax().
minimumXChanged
void QDeclarativeDrag::minimumXChanged () signal
Referenced by setXmin().
minimumYChanged
void QDeclarativeDrag::minimumYChanged () signal
Referenced by setYmin().
resetTarget()
void QDeclarativeDrag::resetTarget ()
Definition at line 77 of file qdeclarativemousearea.cpp.
 {
     if (!_target)
         return;
     _target = 0;
     emit targetChanged();
 }
setActive()
void QDeclarativeDrag::setActive (bool drag)
Definition at line 155 of file qdeclarativemousearea.cpp.
 {
     if (_active == drag)
         return;
     _active = drag;
     emit activeChanged();
 }
setAxis()
void QDeclarativeDrag::setAxis (QDeclarativeDrag::Axis a)
Definition at line 90 of file qdeclarativemousearea.cpp.
 {
     if (_axis == a)
         return;
     _axis = a;
     emit axisChanged();
 }
setFilterChildren()
void QDeclarativeDrag::setFilterChildren (bool filter)
Definition at line 168 of file qdeclarativemousearea.cpp.
 {
     if (_filterChildren == filter)
         return;
     _filterChildren = filter;
     emit filterChildrenChanged();
 }
setTarget()
void QDeclarativeDrag::setTarget (QGraphicsObject * t)
Definition at line 69 of file qdeclarativemousearea.cpp.
 {
     if (_target == t)
         return;
     _target = t;
     emit targetChanged();
 }
setXmax()
void QDeclarativeDrag::setXmax (qreal m)
Definition at line 116 of file qdeclarativemousearea.cpp.
 {
     if (_xmax == m)
         return;
     _xmax = m;
     emit maximumXChanged();
 }
setXmin()
void QDeclarativeDrag::setXmin (qreal m)
Definition at line 103 of file qdeclarativemousearea.cpp.
 {
     if (_xmin == m)
         return;
     _xmin = m;
     emit minimumXChanged();
 }
setYmax()
void QDeclarativeDrag::setYmax (qreal m)
Definition at line 142 of file qdeclarativemousearea.cpp.
 {
     if (_ymax == m)
         return;
     _ymax = m;
     emit maximumYChanged();
 }
setYmin()
void QDeclarativeDrag::setYmin (qreal m)
Definition at line 129 of file qdeclarativemousearea.cpp.
 {
     if (_ymin == m)
         return;
     _ymin = m;
     emit minimumYChanged();
 }
target()
QGraphicsObject* QDeclarativeDrag::target () const
Referenced by ~QDeclarativeDrag().
targetChanged
void QDeclarativeDrag::targetChanged () signal
Referenced by resetTarget(), and setTarget().
xmax()
qreal QDeclarativeDrag::xmax () const
Definition at line 111 of file qdeclarativemousearea.cpp.
 {
     return _xmax;
 }
xmin()
qreal QDeclarativeDrag::xmin () const
Definition at line 98 of file qdeclarativemousearea.cpp.
 {
     return _xmin;
 }
ymax()
qreal QDeclarativeDrag::ymax () const
Definition at line 137 of file qdeclarativemousearea.cpp.
 {
     return _ymax;
 }
ymin()
qreal QDeclarativeDrag::ymin () const
Definition at line 124 of file qdeclarativemousearea.cpp.
 {
     return _ymin;
 }
Properties
_active
bool QDeclarativeDrag::_active private
Definition at line 112 of file qdeclarativemousearea_p.h.
Referenced by setActive(), and setYmax().
_axis
Axis QDeclarativeDrag::_axis private
Definition at line 107 of file qdeclarativemousearea_p.h.
Referenced by resetTarget(), and setAxis().
_filterChildren
bool QDeclarativeDrag::_filterChildren private
Definition at line 113 of file qdeclarativemousearea_p.h.
Referenced by setActive(), and setFilterChildren().
_target
QGraphicsObject* QDeclarativeDrag::_target private
Definition at line 106 of file qdeclarativemousearea_p.h.
Referenced by resetTarget(), setTarget(), and ~QDeclarativeDrag().
_xmax
qreal QDeclarativeDrag::_xmax private
Definition at line 109 of file qdeclarativemousearea_p.h.
Referenced by setXmax(), and xmax().
_xmin
qreal QDeclarativeDrag::_xmin private
Definition at line 108 of file qdeclarativemousearea_p.h.
Referenced by setXmin(), and xmin().
_ymax
qreal QDeclarativeDrag::_ymax private
Definition at line 111 of file qdeclarativemousearea_p.h.
Referenced by setYmax(), and ymax().
_ymin
qreal QDeclarativeDrag::_ymin private
Definition at line 110 of file qdeclarativemousearea_p.h.
Referenced by setYmin(), and ymin().
active
bool QDeclarativeDrag::active private
Definition at line 64 of file qdeclarativemousearea_p.h.
axis
QDeclarativeDrag::Axis QDeclarativeDrag::axis private
Definition at line 59 of file qdeclarativemousearea_p.h.
Referenced by QDeclarativeMouseArea::mouseMoveEvent().
filterChildren
bool QDeclarativeDrag::filterChildren private
Definition at line 65 of file qdeclarativemousearea_p.h.
maximumX
qreal QDeclarativeDrag::maximumX private
Definition at line 61 of file qdeclarativemousearea_p.h.
maximumY
qreal QDeclarativeDrag::maximumY private
Definition at line 63 of file qdeclarativemousearea_p.h.
minimumX
qreal QDeclarativeDrag::minimumX private
Definition at line 60 of file qdeclarativemousearea_p.h.
minimumY
qreal QDeclarativeDrag::minimumY private
Definition at line 62 of file qdeclarativemousearea_p.h.
target
QGraphicsObject * QDeclarativeDrag::target private
Definition at line 58 of file qdeclarativemousearea_p.h.
Referenced by QDeclarativeMouseArea::mouseMoveEvent().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativemousearea_p.h
/src/declarative/graphicsitems/qdeclarativemousearea.cpp