Qt 4.8: QGlyphRun Class Reference
QGlyphRun Class Reference
The QGlyphRun class provides direct access to the internal glyphs in a font.
#include <qglyphrun.h>
Public Functions
void clear ()
Clears all data in the QGlyphRun object.
QVector< quint32 > glyphIndexes () const
Returns the glyph indexes for this QGlyphRun object.
bool operator!= (const QGlyphRun &other) const
Compares other to this QGlyphRun object.
QGlyphRun & operator= (const QGlyphRun &other)
Assigns other to this QGlyphRun object.
bool operator== (const QGlyphRun &other) const
Compares other to this QGlyphRun object.
bool overline () const
Returns true if this QGlyphRun should be painted with an overline decoration.
QVector< QPointF > positions () const
Returns the position of the edge of the baseline for each glyph in this set of glyph indexes.
QGlyphRun ()
Constructs an empty QGlyphRun object.
QGlyphRun (const QGlyphRun &other)
Constructs a QGlyphRun object which is a copy of other.
QRawFont rawFont () const
Returns the font selected for this QGlyphRun object.
void setGlyphIndexes (const QVector< quint32 > &glyphIndexes)
Set the glyph indexes for this QGlyphRun object to glyphIndexes.
void setOverline (bool overline)
Indicates that this QGlyphRun should be painted with an overline decoration if overline is true.
void setPositions (const QVector< QPointF > &positions)
Sets the positions of the edge of the baseline for each glyph in this set of glyph indexes to positions.
void setRawData (const quint32 *glyphIndexArray, const QPointF *glyphPositionArray, int size)
Sets the glyph indexes and positions of this QGlyphRun to use the first size elements in the arrays glyphIndexArray and glyphPositionArray.
void setRawFont (const QRawFont &rawFont)
Sets the font specified by rawFont to be the font used to look up the glyph indexes.
void setStrikeOut (bool strikeOut)
Indicates that this QGlyphRun should be painted with an strike out decoration if strikeOut is true.
void setUnderline (bool underline)
Indicates that this QGlyphRun should be painted with an underline decoration if underline is true.
bool strikeOut () const
Returns true if this QGlyphRun should be painted with a strike out decoration.
bool underline () const
Returns true if this QGlyphRun should be painted with an underline decoration.
~QGlyphRun ()
Destroys the QGlyphRun.
Private Functions
void detach ()
QGlyphRun operator+ (const QGlyphRun &other) const
QGlyphRun & operator+= (const QGlyphRun &other)
Properties
QExplicitlySharedDataPointer< QGlyphRunPrivate > d
Friends
class QGlyphRunPrivate
class QTextLine
Detailed Description
The QGlyphRun class provides direct access to the internal glyphs in a font.
Since
4.8
When Qt displays a string of text encoded in Unicode, it will first convert the Unicode points into a list of glyph indexes and a list of positions based on one or more fonts. The Unicode representation of the text and the QFont object will in this case serve as a convenient abstraction that hides the details of what actually takes place when displaying the text on-screen. For instance, by the time the text actually reaches the screen, it may be represented by a set of fonts in addition to the one specified by the user, e.g. in case the originally selected font did not support all the writing systems contained in the text.
Under certain circumstances, it can be useful as an application developer to have more low-level control over which glyphs in a specific font are drawn to the screen. This could for instance be the case in applications that use an external font engine and text shaper together with Qt. QGlyphRun provides an interface to the raw data needed to get text on the screen. It contains a list of glyph indexes, a position for each glyph and a font.
It is the user's responsibility to ensure that the selected font actually contains the provided glyph indexes.
QTextLayout::glyphRuns() or QTextFragment::glyphRuns() can be used to convert unicode encoded text into a list of QGlyphRun objects, and QPainter::drawGlyphRun() can be used to draw the glyphs.
Note
Please note that QRawFont is considered local to the thread in which it is constructed. This in turn means that a new QRawFont will have to be created and set on the QGlyphRun if it is moved to a different thread. If the QGlyphRun contains a reference to a QRawFont from a different thread than the current, it will not be possible to draw the glyphs using a QPainter, as the QRawFont is considered invalid and inaccessible in this case.
Definition at line 59 of file qglyphrun.h.
Constructors and Destructors
QGlyphRun() [1/2]
QGlyphRun::QGlyphRun ()
Constructs an empty QGlyphRun object.
Definition at line 94 of file qglyphrun.cpp.
                      : d(new QGlyphRunPrivate)
 {
 }
QGlyphRun() [2/2]
QGlyphRun::QGlyphRun (const QGlyphRun & other)
Constructs a QGlyphRun object which is a copy of other.
Definition at line 101 of file qglyphrun.cpp.
 {
     d = other.d;
 }
~QGlyphRun()
QGlyphRun::~QGlyphRun ()
Destroys the QGlyphRun.
Definition at line 109 of file qglyphrun.cpp.
 {
     // Required for QExplicitlySharedDataPointer
 }
Functions
clear()
void QGlyphRun::clear ()
Clears all data in the QGlyphRun object.
Definition at line 255 of file qglyphrun.cpp.
 {
     detach();
     d->rawFont = QRawFont();
     d->strikeOut = false;
     d->overline = false;
     d->underline = false;
     setPositions(QVector<QPointF>());
     setGlyphIndexes(QVector<quint32>());
 }
detach()
void QGlyphRun::detach () private
Warning
This function is not part of the public interface.
Definition at line 117 of file qglyphrun.cpp.
Referenced by clear(), setGlyphIndexes(), setOverline(), setPositions(), setRawData(), setRawFont(), setStrikeOut(), and setUnderline().
 {
     if (d->ref != 1)
         d.detach();
 }
glyphIndexes()
QVector< quint32 > QGlyphRun::glyphIndexes () const
Returns the glyph indexes for this QGlyphRun object.
See also
setGlyphIndexes(), setPositions()
Definition at line 202 of file qglyphrun.cpp.
Referenced by QTextLine::glyphs(), and setGlyphIndexes().
 {
     if (d->glyphIndexes.constData() == d->glyphIndexData) {
         return d->glyphIndexes;
     } else {
         QVector<quint32> indexes(d->glyphIndexDataSize);
         qMemCopy(indexes.data(), d->glyphIndexData, d->glyphIndexDataSize * sizeof(quint32));
         return indexes;
     }
 }
operator!=()
bool QGlyphRun::operator!= (const QGlyphRun & other) const inline
Compares other to this QGlyphRun object.
Returns true if any of the list of glyph indexes, the list of positions or the font are different, otherwise returns false.
Definition at line 84 of file qglyphrun.h.
     { return !operator==(other); }
operator+()
QGlyphRun QGlyphRun::operator+ (const QGlyphRun & other) const private
operator+=()
QGlyphRun& QGlyphRun::operator+= (const QGlyphRun & other) private
operator=()
QGlyphRun & QGlyphRun::operator= (const QGlyphRun & other)
Assigns other to this QGlyphRun object.
Definition at line 126 of file qglyphrun.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QGlyphRun::operator== (const QGlyphRun & other) const
Compares other to this QGlyphRun object.
Returns true if the list of glyph indexes, the list of positions and the font are all equal, otherwise returns false.
Definition at line 136 of file qglyphrun.cpp.
 {
     if (d == other.d)
         return true;
     if ((d->glyphIndexDataSize != other.d->glyphIndexDataSize)
      || (d->glyphPositionDataSize != other.d->glyphPositionDataSize)) {
         return false;
     }
     if (d->glyphIndexData != other.d->glyphIndexData) {
         for (int i = 0; i < d->glyphIndexDataSize; ++i) {
             if (d->glyphIndexData[i] != other.d->glyphIndexData[i])
                return false;
         }
     }
     if (d->glyphPositionData != other.d->glyphPositionData) {
         for (int i = 0; i < d->glyphPositionDataSize; ++i) {
             if (d->glyphPositionData[i] != other.d->glyphPositionData[i])
                return false;
         }
     }
     return (d->overline == other.d->overline
             && d->underline == other.d->underline
             && d->strikeOut == other.d->strikeOut
             && d->rawFont == other.d->rawFont);
 }
overline()
bool QGlyphRun::overline () const
Returns true if this QGlyphRun should be painted with an overline decoration.
See also
setOverline()
Definition at line 292 of file qglyphrun.cpp.
Referenced by QPainter::drawGlyphRun(), and setOverline().
 {
     return d->overline;
 }
positions()
QVector< QPointF > QGlyphRun::positions () const
Returns the position of the edge of the baseline for each glyph in this set of glyph indexes.
Definition at line 228 of file qglyphrun.cpp.
Referenced by QTextLine::glyphs(), and setPositions().
 {
     if (d->glyphPositions.constData() == d->glyphPositionData) {
         return d->glyphPositions;
     } else {
         QVector<QPointF> glyphPositions(d->glyphPositionDataSize);
         qMemCopy(glyphPositions.data(), d->glyphPositionData,
                  d->glyphPositionDataSize * sizeof(QPointF));
         return glyphPositions;
     }
 }
rawFont()
QRawFont QGlyphRun::rawFont () const
Returns the font selected for this QGlyphRun object.
See also
setRawFont()
Definition at line 180 of file qglyphrun.cpp.
Referenced by QPainter::drawGlyphRun(), QRawFont::fromFont(), and setRawFont().
 {
     return d->rawFont;
 }
setGlyphIndexes()
void QGlyphRun::setGlyphIndexes (const QVector< quint32 > & glyphIndexes)
Set the glyph indexes for this QGlyphRun object to glyphIndexes.
The glyph indexes must be valid for the selected font.
Definition at line 217 of file qglyphrun.cpp.
Referenced by clear(), QTextLine::glyphs(), and QPainterReplayer::process().
 {
     detach();
     d->glyphIndexes = glyphIndexes; // Keep a reference to the QVector to avoid copying
     d->glyphIndexData = glyphIndexes.constData();
     d->glyphIndexDataSize = glyphIndexes.size();
 }
setOverline()
void QGlyphRun::setOverline (bool overline)
Indicates that this QGlyphRun should be painted with an overline decoration if overline is true.
Otherwise the QGlyphRun should be painted with no overline decoration.
See also
overline()
Definition at line 303 of file qglyphrun.cpp.
Referenced by QTextLine::glyphs().
 {
     if (d->overline == overline)
         return;
     detach();
     d->overline = overline;
 }
setPositions()
void QGlyphRun::setPositions (const QVector< QPointF > & positions)
Sets the positions of the edge of the baseline for each glyph in this set of glyph indexes to positions.
Definition at line 244 of file qglyphrun.cpp.
Referenced by clear(), QTextLine::glyphs(), and QPainterReplayer::process().
 {
     detach();
     d->glyphPositions = positions; // Keep a reference to the vector to avoid copying
     d->glyphPositionData = positions.constData();
     d->glyphPositionDataSize = positions.size();
 }
setRawData()
void QGlyphRun::setRawData (const quint32 * glyphIndexArray, const QPointF * glyphPositionArray, int size)
Sets the glyph indexes and positions of this QGlyphRun to use the first size elements in the arrays glyphIndexArray and glyphPositionArray.
The data is not copied. The caller must guarantee that the arrays are not deleted as long as this QGlyphRun and any copies of it exists.
See also
setGlyphIndexes(), setPositions()
Definition at line 275 of file qglyphrun.cpp.
 {
     detach();
     d->glyphIndexes.clear();
     d->glyphPositions.clear();
     d->glyphIndexData = glyphIndexArray;
     d->glyphPositionData = glyphPositionArray;
     d->glyphIndexDataSize = d->glyphPositionDataSize = size;
 }
setRawFont()
void QGlyphRun::setRawFont (const QRawFont & rawFont)
Sets the font specified by rawFont to be the font used to look up the glyph indexes.
See also
rawFont(), setGlyphIndexes()
Definition at line 191 of file qglyphrun.cpp.
Referenced by QTextLine::glyphs(), and QPainterReplayer::process().
 {
     detach();
     d->rawFont = rawFont;
 }
setStrikeOut()
void QGlyphRun::setStrikeOut (bool strikeOut)
Indicates that this QGlyphRun should be painted with an strike out decoration if strikeOut is true.
Otherwise the QGlyphRun should be painted with no strike out decoration.
See also
strikeOut()
Definition at line 353 of file qglyphrun.cpp.
Referenced by QTextLine::glyphs().
 {
     if (d->strikeOut == strikeOut)
         return;
     detach();
     d->strikeOut = strikeOut;
 }
setUnderline()
void QGlyphRun::setUnderline (bool underline)
Indicates that this QGlyphRun should be painted with an underline decoration if underline is true.
Otherwise the QGlyphRun should be painted with no underline decoration.
See also
underline()
Definition at line 328 of file qglyphrun.cpp.
Referenced by QTextLine::glyphs().
 {
     if (d->underline == underline)
         return;
     detach();
     d->underline = underline;
 }
strikeOut()
bool QGlyphRun::strikeOut () const
Returns true if this QGlyphRun should be painted with a strike out decoration.
See also
setStrikeOut()
Definition at line 342 of file qglyphrun.cpp.
Referenced by QPainter::drawGlyphRun(), and setStrikeOut().
 {
     return d->strikeOut;
 }
underline()
bool QGlyphRun::underline () const
Returns true if this QGlyphRun should be painted with an underline decoration.
See also
setUnderline()
Definition at line 317 of file qglyphrun.cpp.
Referenced by QPainter::drawGlyphRun(), and setUnderline().
 {
     return d->underline;
 }
Friends and Related Functions
QGlyphRunPrivate
friend class QGlyphRunPrivate friend
Definition at line 97 of file qglyphrun.h.
QTextLine
friend class QTextLine friend
Definition at line 98 of file qglyphrun.h.
Properties
d
QExplicitlySharedDataPointer<QGlyphRunPrivate> QGlyphRun::d private
Definition at line 104 of file qglyphrun.h.
Referenced by clear(), detach(), glyphIndexes(), operator=(), operator==(), overline(), positions(), QGlyphRun(), rawFont(), setGlyphIndexes(), setOverline(), setPositions(), setRawData(), setRawFont(), setStrikeOut(), setUnderline(), strikeOut(), and underline().
The documentation for this class was generated from the following files:
/src/gui/text/qglyphrun.h
/src/gui/text/qglyphrun.cpp