Qt 4.8: QGraphicsGridLayout Class Reference
QGraphicsGridLayout Class Reference
The QGraphicsGridLayout class provides a grid layout for managing widgets in Graphics View.
#include <qgraphicsgridlayout.h>
Public Functions
void addItem (QGraphicsLayoutItem *item, int row, int column, int rowSpan, int columnSpan, Qt::Alignment alignment=0)
Adds item to the grid on row and column.
void addItem (QGraphicsLayoutItem *item, int row, int column, Qt::Alignment alignment=0)
Adds item to the grid on row and column.
Qt::Alignment alignment (QGraphicsLayoutItem *item) const
Returns the alignment for item.
Qt::Alignment columnAlignment (int column) const
Returns the alignment for column.
int columnCount () const
Returns the number of columns in the grid layout.
qreal columnMaximumWidth (int column) const
Returns the maximum width for column.
qreal columnMinimumWidth (int column) const
Returns the minimum width for column.
qreal columnPreferredWidth (int column) const
Returns the preferred width for column.
qreal columnSpacing (int column) const
Returns the column spacing for column.
int columnStretchFactor (int column) const
Returns the stretch factor for column.
int count () const
Returns the number of layout items in this grid layout.
qreal horizontalSpacing () const
Returns the default horizontal spacing for the grid layout.
void invalidate ()
Reimplemented Function
QGraphicsLayoutItem * itemAt (int row, int column) const
Returns a pointer to the layout item at (row, column).
QGraphicsLayoutItem * itemAt (int index) const
Returns the layout item at index, or 0 if there is no layout item at this index.
QGraphicsGridLayout (QGraphicsLayoutItem *parent=0)
Constructs a QGraphicsGridLayout instance.
void removeAt (int index)
Removes the layout item at index without destroying it.
void removeItem (QGraphicsLayoutItem *item)
Removes the layout item item without destroying it.
Qt::Alignment rowAlignment (int row) const
Returns the alignment of row.
int rowCount () const
Returns the number of rows in the grid layout.
qreal rowMaximumHeight (int row) const
Returns the maximum height for row, row.
qreal rowMinimumHeight (int row) const
Returns the minimum height for row, row.
qreal rowPreferredHeight (int row) const
Returns the preferred height for row, row.
qreal rowSpacing (int row) const
Returns the row spacing for row.
int rowStretchFactor (int row) const
Returns the stretch factor for row.
void setAlignment (QGraphicsLayoutItem *item, Qt::Alignment alignment)
Sets the alignment for item to alignment.
void setColumnAlignment (int column, Qt::Alignment alignment)
Sets the alignment for column to alignment.
void setColumnFixedWidth (int column, qreal width)
Sets the fixed width of column to width.
void setColumnMaximumWidth (int column, qreal width)
Sets the maximum width of column to width.
void setColumnMinimumWidth (int column, qreal width)
Sets the minimum width for column to width.
void setColumnPreferredWidth (int column, qreal width)
Sets the preferred width for column to width.
void setColumnSpacing (int column, qreal spacing)
Sets the spacing for column to spacing.
void setColumnStretchFactor (int column, int stretch)
Sets the stretch factor for column to stretch.
void setGeometry (const QRectF &rect)
Sets the bounding geometry of the grid layout to rect.
void setHorizontalSpacing (qreal spacing)
Sets the default horizontal spacing for the grid layout to spacing.
void setRowAlignment (int row, Qt::Alignment alignment)
Sets the alignment of row to alignment.
void setRowFixedHeight (int row, qreal height)
Sets the fixed height for row, row, to height.
void setRowMaximumHeight (int row, qreal height)
Sets the maximum height for row, row, to height.
void setRowMinimumHeight (int row, qreal height)
Sets the minimum height for row, row, to height.
void setRowPreferredHeight (int row, qreal height)
Sets the preferred height for row, row, to height.
void setRowSpacing (int row, qreal spacing)
Sets the spacing for row to spacing.
void setRowStretchFactor (int row, int stretch)
Sets the stretch factor for row to stretch.
void setSpacing (qreal spacing)
Sets the grid layout's default spacing, both vertical and horizontal, to spacing.
void setVerticalSpacing (qreal spacing)
Sets the default vertical spacing for the grid layout to spacing.
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Reimplemented Function
qreal verticalSpacing () const
Returns the default vertical spacing for the grid layout.
virtual ~QGraphicsGridLayout ()
Destroys the QGraphicsGridLayout object.
Public Functions inherited from QGraphicsLayout
void activate ()
Activates the layout, causing all items in the layout to be immediately rearranged.
void getContentsMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Reimplemented Function
bool isActivated () const
Returns true if the layout is currently being activated; otherwise, returns false.
QGraphicsLayout (QGraphicsLayoutItem *parent=0)
Contructs a QGraphicsLayout object.
void setContentsMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the contents margins to left, top, right and bottom.
virtual void updateGeometry ()
Reimplemented Function
virtual void widgetEvent (QEvent *e)
This virtual event handler receives all events for the managed widget.
~QGraphicsLayout ()
Destroys the QGraphicsLayout object.
Public Functions inherited from QGraphicsLayoutItem
QRectF contentsRect () const
Returns the contents rect in local coordinates.
QSizeF effectiveSizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
QRectF geometry () const
Returns the item's geometry (e.
QGraphicsItem * graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
bool isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
qreal maximumHeight () const
Returns the maximum height.
QSizeF maximumSize () const
Returns the maximum size.
qreal maximumWidth () const
Returns the maximum width.
qreal minimumHeight () const
Returns the minimum height.
QSizeF minimumSize () const
Returns the minimum size.
qreal minimumWidth () const
Returns the minimum width.
bool ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
QGraphicsLayoutItem * parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
qreal preferredHeight () const
Returns the preferred height.
QSizeF preferredSize () const
Returns the preferred size.
qreal preferredWidth () const
Returns the preferred width.
QGraphicsLayoutItem (QGraphicsLayoutItem *parent=0, bool isLayout=false)
Constructs the QGraphicsLayoutItem object.
void setMaximumHeight (qreal height)
Sets the maximum height to height.
void setMaximumSize (const QSizeF &size)
Sets the maximum size to size.
void setMaximumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
void setMaximumWidth (qreal width)
Sets the maximum width to width.
void setMinimumHeight (qreal height)
Sets the minimum height to height.
void setMinimumSize (const QSizeF &size)
Sets the minimum size to size.
void setMinimumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
void setMinimumWidth (qreal width)
Sets the minimum width to width.
void setParentLayoutItem (QGraphicsLayoutItem *parent)
Sets the parent of this QGraphicsLayoutItem to parent.
void setPreferredHeight (qreal height)
Sets the preferred height to height.
void setPreferredSize (const QSizeF &size)
Sets the preferred size to size.
void setPreferredSize (qreal w, qreal h)
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
void setPreferredWidth (qreal width)
Sets the preferred width to width.
void setSizePolicy (const QSizePolicy &policy)
Sets the size policy to policy.
void setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType=QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
QSizePolicy sizePolicy () const
Returns the current size policy.
virtual ~QGraphicsLayoutItem ()
Destroys the QGraphicsLayoutItem object.
Additional Inherited Members
Static Public Functions inherited from QGraphicsLayout
static bool instantInvalidatePropagation ()
static void setInstantInvalidatePropagation (bool enable)
Protected Functions inherited from QGraphicsLayout
void addChildLayoutItem (QGraphicsLayoutItem *layoutItem)
This function is a convenience function provided for custom layouts, and will go through all items in the layout and reparent their graphics items to the closest QGraphicsWidget ancestor of the layout.
QGraphicsLayout (QGraphicsLayoutPrivate &, QGraphicsLayoutItem *)
Protected Functions inherited from QGraphicsLayoutItem
QGraphicsLayoutItem (QGraphicsLayoutItemPrivate &dd)
void setGraphicsItem (QGraphicsItem *item)
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
void setOwnedByLayout (bool ownedByLayout)
Sets whether a layout should delete this item in its destructor or not.
Protected Variables inherited from QGraphicsLayoutItem
QScopedPointer< QGraphicsLayoutItemPrivate > d_ptr
Detailed Description
The QGraphicsGridLayout class provides a grid layout for managing widgets in Graphics View.
Since
4.4
The most common way to use QGraphicsGridLayout is to construct an object on the heap with no parent, add widgets and layouts by calling addItem(), and finally assign the layout to a widget by calling QGraphicsWidget::setLayout(). QGraphicsGridLayout automatically computes the dimensions of the grid as you add items.
QGraphicsScene scene;
QGraphicsWidget *textEdit = scene.addWidget(new QTextEdit);
QGraphicsWidget *pushButton = scene.addWidget(new QPushButton);
QGraphicsGridLayout *layout = new QGraphicsGridLayout;
layout->addItem(textEdit, 0, 0);
layout->addItem(pushButton, 0, 1);
QGraphicsWidget *form = new QGraphicsWidget;
form->setLayout(layout);
scene.addItem(form);
The layout takes ownership of the items. In some cases when the layout item also inherits from QGraphicsItem (such as QGraphicsWidget) there will be a ambiguity in ownership because the layout item belongs to two ownership hierarchies. See the documentation of QGraphicsLayoutItem::setOwnedByLayout() how to handle this. You can access each item in the layout by calling count() and itemAt(). Calling removeAt() will remove an item from the layout, without destroying it.
Size Hints and Size Policies in QGraphicsGridLayout
QGraphicsGridLayout respects each item's size hints and size policies, and when a cell in the grid has more space than the items can fill, each item is arranged according to the layout's alignment for that item. You can set an alignment for each item by calling setAlignment(), and check the alignment for any item by calling alignment(). You can also set the alignment for an entire row or column by calling setRowAlignment() and setColumnAlignment() respectively. By default, items are aligned to the top left.
See also
QGraphicsLinearLayout, QGraphicsWidget
Definition at line 58 of file qgraphicsgridlayout.h.
Constructors and Destructors
QGraphicsGridLayout()
QGraphicsGridLayout::QGraphicsGridLayout (QGraphicsLayoutItem * parent = 0)
Constructs a QGraphicsGridLayout instance.
parent is passed to QGraphicsLayout's constructor.
Definition at line 124 of file qgraphicsgridlayout.cpp.
     : QGraphicsLayout(*new QGraphicsGridLayoutPrivate(), parent)
 {
 }
~QGraphicsGridLayout()
QGraphicsGridLayout::~QGraphicsGridLayout () virtual
Destroys the QGraphicsGridLayout object.
Definition at line 132 of file qgraphicsgridlayout.cpp.
 {
     for (int i = count() - 1; i >= 0; --i) {
         QGraphicsLayoutItem *item = itemAt(i);
         // The following lines can be removed, but this removes the item
         // from the layout more efficiently than the implementation of
         // ~QGraphicsLayoutItem.
         removeAt(i);
         if (item) {
             item->setParentLayoutItem(0);
             if (item->ownedByLayout())
                 delete item;
         }
     }
 }
Functions
addItem() [1/2]
void QGraphicsGridLayout::addItem (QGraphicsLayoutItem * item, int row, int column, int rowSpan, int columnSpan, Qt::Alignment alignment = 0)
Adds item to the grid on row and column.
You can specify a rowSpan and columnSpan and an optional alignment.
Definition at line 152 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     if (row < 0 || column < 0) {
         qWarning("QGraphicsGridLayout::addItem: invalid row/column: %d",
                  row < 0 ? row : column);
         return;
     }
     if (columnSpan < 1 || rowSpan < 1) {
         qWarning("QGraphicsGridLayout::addItem: invalid row span/column span: %d",
                  rowSpan < 1 ? rowSpan : columnSpan);
         return;
     }
     if (!item) {
         qWarning("QGraphicsGridLayout::addItem: cannot add null item");
         return;
     }
     if (item == this) {
         qWarning("QGraphicsGridLayout::addItem: cannot insert itself");
         return;
     }
     d->addChildLayoutItem(item);
     new QGridLayoutItem(&d->engine, item, row, column, rowSpan, columnSpan, alignment);
     invalidate();
 }
addItem() [2/2]
void QGraphicsGridLayout::addItem (QGraphicsLayoutItem * item, int row, int column, Qt::Alignment alignment = 0) inline
Adds item to the grid on row and column.
You can specify an optional alignment for item.
Definition at line 134 of file qgraphicsgridlayout.h.
 { addItem(aitem, arow, acolumn, 1, 1, aalignment); }
alignment()
Qt::Alignment QGraphicsGridLayout::alignment (QGraphicsLayoutItem * item) const
Returns the alignment for item.
Definition at line 502 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.alignment(item);
 }
columnAlignment()
Qt::Alignment QGraphicsGridLayout::columnAlignment (int column) const
Returns the alignment for column.
Definition at line 483 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowAlignment(column, Qt::Horizontal);
 }
columnCount()
int QGraphicsGridLayout::columnCount () const
Returns the number of columns in the grid layout.
This is always one more than the index of the last column that is occupied by a layout item (empty columns are counted except for those at the end).
Definition at line 524 of file qgraphicsgridlayout.cpp.
Referenced by itemAt().
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.effectiveLastRow(Qt::Horizontal) + 1;
 }
columnMaximumWidth()
qreal QGraphicsGridLayout::columnMaximumWidth (int column) const
Returns the maximum width for column.
Definition at line 434 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSizeHint(Qt::MaximumSize, column, Qt::Horizontal);
 }
columnMinimumWidth()
qreal QGraphicsGridLayout::columnMinimumWidth (int column) const
Returns the minimum width for column.
Definition at line 396 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSizeHint(Qt::MinimumSize, column, Qt::Horizontal);
 }
columnPreferredWidth()
qreal QGraphicsGridLayout::columnPreferredWidth (int column) const
Returns the preferred width for column.
Definition at line 415 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSizeHint(Qt::PreferredSize, column, Qt::Horizontal);
 }
columnSpacing()
qreal QGraphicsGridLayout::columnSpacing (int column) const
Returns the column spacing for column.
Definition at line 271 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSpacing(column, Qt::Horizontal);
 }
columnStretchFactor()
int QGraphicsGridLayout::columnStretchFactor (int column) const
Returns the stretch factor for column.
Definition at line 309 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowStretchFactor(column, Qt::Horizontal);
 }
count()
int QGraphicsGridLayout::count () const virtual
Returns the number of layout items in this grid layout.
Implements QGraphicsLayout.
Definition at line 548 of file qgraphicsgridlayout.cpp.
Referenced by ~QGraphicsGridLayout().
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.itemCount();
 }
horizontalSpacing()
qreal QGraphicsGridLayout::horizontalSpacing () const
Returns the default horizontal spacing for the grid layout.
Definition at line 201 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.spacing(d->styleInfo(), Qt::Horizontal);
 }
invalidate()
void QGraphicsGridLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QGraphicsLayout.
Definition at line 625 of file qgraphicsgridlayout.cpp.
Referenced by addItem(), removeAt(), setAlignment(), setColumnAlignment(), setColumnFixedWidth(), setColumnMaximumWidth(), setColumnMinimumWidth(), setColumnPreferredWidth(), setColumnSpacing(), setColumnStretchFactor(), setHorizontalSpacing(), setRowAlignment(), setRowFixedHeight(), setRowMaximumHeight(), setRowMinimumHeight(), setRowPreferredHeight(), setRowSpacing(), setRowStretchFactor(), setSpacing(), and setVerticalSpacing().
 {
     Q_D(QGraphicsGridLayout);
     d->engine.invalidate();
     QGraphicsLayout::invalidate();
 }
itemAt() [1/2]
QGraphicsLayoutItem * QGraphicsGridLayout::itemAt (int row, int column) const
Returns a pointer to the layout item at (row, column).
Definition at line 533 of file qgraphicsgridlayout.cpp.
Referenced by ~QGraphicsGridLayout().
 {
     Q_D(const QGraphicsGridLayout);
     if (row < 0 || row >= rowCount() || column < 0 || column >= columnCount()) {
         qWarning("QGraphicsGridLayout::itemAt: invalid row, column %d, %d", row, column);
         return 0;
     }
     if (QGridLayoutItem *item = d->engine.itemAt(row, column))
         return item->layoutItem();
     return 0;
 }
itemAt() [2/2]
QGraphicsLayoutItem * QGraphicsGridLayout::itemAt (int index) const virtual
Returns the layout item at index, or 0 if there is no layout item at this index.
Implements QGraphicsLayout.
Definition at line 558 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     if (index < 0 || index >= d->engine.itemCount()) {
         qWarning("QGraphicsGridLayout::itemAt: invalid index %d", index);
         return 0;
     }
     QGraphicsLayoutItem *item = 0;
     if (QGridLayoutItem *gridItem = d->engine.itemAt(index))
         item = gridItem->layoutItem();
     return item;
 }
removeAt()
void QGraphicsGridLayout::removeAt (int index) virtual
Removes the layout item at index without destroying it.
Ownership of the item is transferred to the caller.
See also
addItem()
Implements QGraphicsLayout.
Definition at line 577 of file qgraphicsgridlayout.cpp.
Referenced by removeItem(), and ~QGraphicsGridLayout().
 {
     Q_D(QGraphicsGridLayout);
     if (index < 0 || index >= d->engine.itemCount()) {
         qWarning("QGraphicsGridLayout::removeAt: invalid index %d", index);
         return;
     }
     if (QGridLayoutItem *gridItem = d->engine.itemAt(index)) {
         if (QGraphicsLayoutItem *layoutItem = gridItem->layoutItem())
             layoutItem->setParentLayoutItem(0);
         d->engine.removeItem(gridItem);
         // recalculate rowInfo.count if we remove an item that is on the right/bottommost row
         for (int j = 0; j < NOrientations; ++j) {
             // 0: Hor, 1: Ver
             const Qt::Orientation orient = (j == 0 ? Qt::Horizontal : Qt::Vertical);
             const int oldCount = d->engine.rowCount(orient);
             if (gridItem->lastRow(orient) == oldCount - 1) {
                 const int newCount = d->engine.effectiveLastRow(orient) + 1;
                 d->engine.removeRows(newCount, oldCount - newCount, orient);
             }
         }
         delete gridItem;
         invalidate();
     }
 }
removeItem()
void QGraphicsGridLayout::removeItem (QGraphicsLayoutItem * item)
Removes the layout item item without destroying it.
Since
4.8
Ownership of the item is transferred to the caller.
See also
addItem()
Definition at line 616 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     int index = d->engine.indexOf(item);
     removeAt(index);
 }
rowAlignment()
Qt::Alignment QGraphicsGridLayout::rowAlignment (int row) const
Returns the alignment of row.
Definition at line 464 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowAlignment(row, Qt::Vertical);
 }
rowCount()
int QGraphicsGridLayout::rowCount () const
Returns the number of rows in the grid layout.
This is always one more than the index of the last row that is occupied by a layout item (empty rows are counted except for those at the end).
Definition at line 513 of file qgraphicsgridlayout.cpp.
Referenced by itemAt().
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.effectiveLastRow(Qt::Vertical) + 1;
 }
rowMaximumHeight()
qreal QGraphicsGridLayout::rowMaximumHeight (int row) const
Returns the maximum height for row, row.
Definition at line 366 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSizeHint(Qt::MaximumSize, row, Qt::Vertical);
 }
rowMinimumHeight()
qreal QGraphicsGridLayout::rowMinimumHeight (int row) const
Returns the minimum height for row, row.
Definition at line 328 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSizeHint(Qt::MinimumSize, row, Qt::Vertical);
 }
rowPreferredHeight()
qreal QGraphicsGridLayout::rowPreferredHeight (int row) const
Returns the preferred height for row, row.
Definition at line 347 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSizeHint(Qt::PreferredSize, row, Qt::Vertical);
 }
rowSpacing()
qreal QGraphicsGridLayout::rowSpacing (int row) const
Returns the row spacing for row.
Definition at line 252 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowSpacing(row, Qt::Vertical);
 }
rowStretchFactor()
int QGraphicsGridLayout::rowStretchFactor (int row) const
Returns the stretch factor for row.
Definition at line 290 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.rowStretchFactor(row, Qt::Vertical);
 }
setAlignment()
void QGraphicsGridLayout::setAlignment (QGraphicsLayoutItem * item, Qt::Alignment alignment)
Sets the alignment for item to alignment.
Definition at line 492 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setAlignment(item, alignment);
     invalidate();
 }
setColumnAlignment()
void QGraphicsGridLayout::setColumnAlignment (int column, Qt::Alignment alignment)
Sets the alignment for column to alignment.
Definition at line 473 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowAlignment(column, alignment, Qt::Horizontal);
     invalidate();
 }
setColumnFixedWidth()
void QGraphicsGridLayout::setColumnFixedWidth (int column, qreal width)
Sets the fixed width of column to width.
Definition at line 443 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::MinimumSize, column, width, Qt::Horizontal);
     d->engine.setRowSizeHint(Qt::MaximumSize, column, width, Qt::Horizontal);
     invalidate();
 }
setColumnMaximumWidth()
void QGraphicsGridLayout::setColumnMaximumWidth (int column, qreal width)
Sets the maximum width of column to width.
Definition at line 424 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::MaximumSize, column, width, Qt::Horizontal);
     invalidate();
 }
setColumnMinimumWidth()
void QGraphicsGridLayout::setColumnMinimumWidth (int column, qreal width)
Sets the minimum width for column to width.
Definition at line 386 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::MinimumSize, column, width, Qt::Horizontal);
     invalidate();
 }
setColumnPreferredWidth()
void QGraphicsGridLayout::setColumnPreferredWidth (int column, qreal width)
Sets the preferred width for column to width.
Definition at line 405 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::PreferredSize, column, width, Qt::Horizontal);
     invalidate();
 }
setColumnSpacing()
void QGraphicsGridLayout::setColumnSpacing (int column, qreal spacing)
Sets the spacing for column to spacing.
Definition at line 261 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSpacing(column, spacing, Qt::Horizontal);
     invalidate();
 }
setColumnStretchFactor()
void QGraphicsGridLayout::setColumnStretchFactor (int column, int stretch)
Sets the stretch factor for column to stretch.
Definition at line 299 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowStretchFactor(column, stretch, Qt::Horizontal);
     invalidate();
 }
setGeometry()
void QGraphicsGridLayout::setGeometry (const QRectF & rect) virtual
Sets the bounding geometry of the grid layout to rect.
Reimplemented from QGraphicsLayoutItem.
Definition at line 644 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     QGraphicsLayout::setGeometry(rect);
     QRectF effectiveRect = geometry();
     qreal left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     Qt::LayoutDirection visualDir = d->visualDirection();
     d->engine.setVisualDirection(visualDir);
     if (visualDir == Qt::RightToLeft)
         qSwap(left, right);
     effectiveRect.adjust(+left, +top, -right, -bottom);
     d->engine.setGeometries(d->styleInfo(), effectiveRect);
 #ifdef QT_DEBUG
     if (qt_graphicsLayoutDebug()) {
         static int counter = 0;
         qDebug("==== BEGIN DUMP OF QGraphicsGridLayout (%d)====", counter++);
         d->dump(1);
         qDebug("==== END DUMP OF QGraphicsGridLayout ====");
     }
 #endif
 }
setHorizontalSpacing()
void QGraphicsGridLayout::setHorizontalSpacing (qreal spacing)
Sets the default horizontal spacing for the grid layout to spacing.
Definition at line 191 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setSpacing(spacing, Qt::Horizontal);
     invalidate();
 }
setRowAlignment()
void QGraphicsGridLayout::setRowAlignment (int row, Qt::Alignment alignment)
Sets the alignment of row to alignment.
Definition at line 454 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowAlignment(row, alignment, Qt::Vertical);
     invalidate();
 }
setRowFixedHeight()
void QGraphicsGridLayout::setRowFixedHeight (int row, qreal height)
Sets the fixed height for row, row, to height.
Definition at line 375 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::MinimumSize, row, height, Qt::Vertical);
     d->engine.setRowSizeHint(Qt::MaximumSize, row, height, Qt::Vertical);
     invalidate();
 }
setRowMaximumHeight()
void QGraphicsGridLayout::setRowMaximumHeight (int row, qreal height)
Sets the maximum height for row, row, to height.
Definition at line 356 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::MaximumSize, row, height, Qt::Vertical);
     invalidate();
 }
setRowMinimumHeight()
void QGraphicsGridLayout::setRowMinimumHeight (int row, qreal height)
Sets the minimum height for row, row, to height.
Definition at line 318 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::MinimumSize, row, height, Qt::Vertical);
     invalidate();
 }
setRowPreferredHeight()
void QGraphicsGridLayout::setRowPreferredHeight (int row, qreal height)
Sets the preferred height for row, row, to height.
Definition at line 337 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSizeHint(Qt::PreferredSize, row, height, Qt::Vertical);
     invalidate();
 }
setRowSpacing()
void QGraphicsGridLayout::setRowSpacing (int row, qreal spacing)
Sets the spacing for row to spacing.
Definition at line 242 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowSpacing(row, spacing, Qt::Vertical);
     invalidate();
 }
setRowStretchFactor()
void QGraphicsGridLayout::setRowStretchFactor (int row, int stretch)
Sets the stretch factor for row to stretch.
Definition at line 280 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setRowStretchFactor(row, stretch, Qt::Vertical);
     invalidate();
 }
setSpacing()
void QGraphicsGridLayout::setSpacing (qreal spacing)
Sets the grid layout's default spacing, both vertical and horizontal, to spacing.
See also
rowSpacing(), columnSpacing()
Definition at line 232 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setSpacing(spacing, Qt::Horizontal | Qt::Vertical);
     invalidate();
 }
setVerticalSpacing()
void QGraphicsGridLayout::setVerticalSpacing (qreal spacing)
Sets the default vertical spacing for the grid layout to spacing.
Definition at line 210 of file qgraphicsgridlayout.cpp.
 {
     Q_D(QGraphicsGridLayout);
     d->engine.setSpacing(spacing, Qt::Vertical);
     invalidate();
 }
sizeHint()
QSizeF QGraphicsGridLayout::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const virtual
Reimplemented Function
Implements QGraphicsLayoutItem.
Definition at line 670 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     qreal left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     const QSizeF extraMargins(left + right, top + bottom);
     return d->engine.sizeHint(d->styleInfo(), which , constraint - extraMargins) + extraMargins;
 }
verticalSpacing()
qreal QGraphicsGridLayout::verticalSpacing () const
Returns the default vertical spacing for the grid layout.
Definition at line 220 of file qgraphicsgridlayout.cpp.
 {
     Q_D(const QGraphicsGridLayout);
     return d->engine.spacing(d->styleInfo(), Qt::Vertical);
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsgridlayout.h
/src/gui/graphicsview/qgraphicsgridlayout.cpp