Qt 4.8: QScriptDebuggerBackend Class Reference
QScriptDebuggerBackend Class Reference abstract
The QScriptDebuggerBackend class is the base class of debugger back-ends.
#include <qscriptdebuggerbackend_p.h>
Public Functions
QScriptValue assertFunction () const
void attachTo (QScriptEngine *engine)
Attaches this backend to the given engine.
QStringList backtrace () const
Returns a backtrace of the current execution.
QScriptBreakpointData breakpointData (int id) const
Returns the data associated with the breakpoint identified by the given id.
QScriptBreakpointMap breakpoints () const
Returns this backend's breakpoints.
QScriptDebuggerCommandExecutor * commandExecutor () const
QScriptContext * context (int index) const
Returns the context for the frame with the given index.
int contextCount () const
Returns the number of contexts (frames).
QList< qint64 > contextIds () const
QScriptContextsDelta contextsCheckpoint ()
void continueEvalution ()
Continues script evaluation.
void deleteAllBreakpoints ()
Deletes all breakpoints.
bool deleteBreakpoint (int id)
Deletes the breakpoint identified by the given id.
void deleteScriptObjectSnapshot (int id)
void deleteScriptValueIterator (int id)
void detach ()
Detaches this backend from the current script engine.
void doPendingEvaluate (bool postEvent)
Executes the pending evaluate, if any.
QScriptEngine * engine () const
Returns the script engine that this backend is attached to, or 0 if the backend is not attached to an engine.
void evaluate (int contextIndex, const QString &program, const QString &fileName, int lineNumber)
Evaluates the given program.
QScriptValue fileNameFunction () const
bool ignoreExceptions () const
void interruptEvaluation ()
Interrupts script evaluation.
QScriptValue lineNumberFunction () const
int newScriptObjectSnapshot ()
int newScriptValueIterator (const QScriptValue &object)
QScriptDebuggerBackend ()
Creates a QScriptDebuggerBackend object.
qint64 resolveScript (const QString &fileName) const
virtual void resume ()=0
This function is called when control should be returned back to the back-end, i.
void returnToCaller (int contextIndex, const QScriptValue &value)
void runToLocation (const QString &fileName, int lineNumber)
Continues evaluation until the location defined by the given fileName and lineNumber is reached.
void runToLocation (qint64 scriptId, int lineNumber)
Continues evaluation until the location defined by the given scriptId and lineNumber is reached.
QScriptScriptData scriptData (qint64 id) const
Returns the data for the script identified by the given id.
QScriptObjectSnapshot * scriptObjectSnapshot (int id) const
QScriptScriptMap scripts () const
Returns the scripts that this backend knows about.
void scriptsCheckpoint ()
Makes a checkpoint of the currently loaded scripts.
QScriptScriptsDelta scriptsDelta () const
Returns the difference between the latest scripts checkpoint and the previous checkpoint.
QScriptValueIterator * scriptValueIterator (int id) const
int setBreakpoint (const QScriptBreakpointData &data)
Sets a breakpoint defined by the given data, and returns a unique identifier for the new breakpoint.
bool setBreakpointData (int id, const QScriptBreakpointData &data)
Sets the data associated with the breakpoint identified by the given id.
void setCommandExecutor (QScriptDebuggerCommandExecutor *executor)
void setIgnoreExceptions (bool ignore)
void stepInto (int count=1)
Steps into the next script statement.
void stepOut ()
Steps out of the current script function.
void stepOver (int count=1)
Steps over the next script statement.
QScriptValue traceFunction () const
Returns a trace function.
virtual ~QScriptDebuggerBackend ()
Destroys this QScriptDebuggerBackend.
Protected Functions
virtual void event (const QScriptDebuggerEvent &event)=0
This function is called when the back-end has generated the given event.
QScriptDebuggerBackend (QScriptDebuggerBackendPrivate &dd)
Protected Variables
QScopedPointer< QScriptDebuggerBackendPrivate > d_ptr
Detailed Description
The QScriptDebuggerBackend class is the base class of debugger back-ends.
Since
4.5
Warning
This function is not part of the public interface.
QScriptDebuggerBackend builds on the QScriptDebuggerAgent class.
This class is usually used together with the QScriptDebuggerFrontend class, in order to form a (front-end, back-end) pair.
Call attachTo() to attach to a QScriptEngine object. Call detach() to detach from the current engine.
Call stepInto() to step into the next script statement; call stepOver() to step over the next script statement; and call stepOut() to step out of the currently executing script function. An event() will be generated when the stepping is completed.
Call runToLocation() to execute script statements until a certain location has been reached. An event() will be generated when the location has been reached.
Call interruptEvaluation() to request that evaluation should be interrupted. An event() will be generated upon the next script statement that is reached.
Call continueEvalution() to allow script evaluation to continue.
Call setBreakpoint() to set a breakpoint. A breakpoint event() will be generated when a breakpoint is hit. Call deleteBreakpoint() to delete a breakpoint. Call modifyBreakpoint() to change the state of an existing breakpoint.
Call contextCount() to obtain the number of active contexts (frames). Call context() to obtain a pointer to a QScriptContext.
Subclassing
When subclassing QScriptDebuggerBackend, you must implement the pure virtual event() function. This function typically forwards the event to a QScriptDebuggerFrontend object. For most type of events, event() should block until the back-end is instructed to resume execution (e.g. until continueEvalution() is called). You must implement resume(), which is responsible for making event() return.
See also
QScriptDebuggerFrontend, QScriptDebuggerEvent
Definition at line 78 of file qscriptdebuggerbackend_p.h.
Constructors and Destructors
QScriptDebuggerBackend() [1/2]
QScriptDebuggerBackend::QScriptDebuggerBackend ()
Creates a QScriptDebuggerBackend object.
Definition at line 378 of file qscriptdebuggerbackend.cpp.
     : d_ptr(new QScriptDebuggerBackendPrivate)
 {
     d_ptr->q_ptr = this;
 }
~QScriptDebuggerBackend()
QScriptDebuggerBackend::~QScriptDebuggerBackend () virtual
Destroys this QScriptDebuggerBackend.
Definition at line 387 of file qscriptdebuggerbackend.cpp.
 {
     detach();
 }
QScriptDebuggerBackend() [2/2]
QScriptDebuggerBackend::QScriptDebuggerBackend (QScriptDebuggerBackendPrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 395 of file qscriptdebuggerbackend.cpp.
     : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
 }
Functions
assertFunction()
QScriptValue QScriptDebuggerBackend::assertFunction () const
Definition at line 928 of file qscriptdebuggerbackend.cpp.
 {
     if (!engine())
         return QScriptValue();
     QScriptValue fun = engine()->newFunction(QScriptDebuggerBackendPrivate::qsassert);
     return fun;
 }
attachTo()
void QScriptDebuggerBackend::attachTo (QScriptEngine * engine)
Attaches this backend to the given engine.
The backend automatically detaches from the old engine, if any.
This function installs its own agent on the engine using QScriptEngine::setAgent(); any existing agent will be replaced.
See also
detach(). engine()
Definition at line 410 of file qscriptdebuggerbackend.cpp.
 {
     Q_D(QScriptDebuggerBackend);
     detach();
     d->agent = new QScriptDebuggerAgent(d, engine);
     QScriptValue global = engine->globalObject();
     d->origTraceFunction = global.property(QString::fromLatin1("print"));
     global.setProperty(QString::fromLatin1("print"), traceFunction());
 //    global.setProperty(QString::fromLatin1("qAssert"), assertFunction());
     d->origFileNameFunction = global.property(QString::fromLatin1("__FILE__"));
     global.setProperty(QString::fromLatin1("__FILE__"), fileNameFunction(),
                        QScriptValue::PropertyGetter | QScriptValue::ReadOnly);
     d->origLineNumberFunction = global.property(QString::fromLatin1("__LINE__"));
     global.setProperty(QString::fromLatin1("__LINE__"), lineNumberFunction(),
                        QScriptValue::PropertyGetter | QScriptValue::ReadOnly);
     engine->setAgent(d->agent);
 }
backtrace()
QStringList QScriptDebuggerBackend::backtrace () const
Returns a backtrace of the current execution.
Definition at line 834 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     if (!engine())
         return QStringList();
     return engine()->currentContext()->backtrace();
 }
breakpointData()
QScriptBreakpointData QScriptDebuggerBackend::breakpointData (int id) const
Returns the data associated with the breakpoint identified by the given id.
Definition at line 708 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return QScriptBreakpointData();
     return d->agent->breakpointData(id);
 }
breakpoints()
QScriptBreakpointMap QScriptDebuggerBackend::breakpoints () const
Returns this backend's breakpoints.
See also
setBreakpoint()
Definition at line 733 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return QScriptBreakpointMap();
     return d->agent->breakpoints();
 }
commandExecutor()
QScriptDebuggerCommandExecutor * QScriptDebuggerBackend::commandExecutor () const
Definition at line 952 of file qscriptdebuggerbackend.cpp.
 {
     Q_D(const QScriptDebuggerBackend);
     if (d->commandExecutor)
         return d->commandExecutor;
     QScriptDebuggerBackendPrivate *dd = const_cast<QScriptDebuggerBackendPrivate*>(d);
     dd->commandExecutor = new QScriptDebuggerCommandExecutor();
     return dd->commandExecutor;
 }
context()
QScriptContext * QScriptDebuggerBackend::context (int index) const
Returns the context for the frame with the given index.
Definition at line 817 of file qscriptdebuggerbackend.cpp.
Referenced by doPendingEvaluate(), and QScriptDebuggerCommandExecutor::execute().
 {
     if (index < 0)
         return 0;
     QScriptContext *ctx = engine()->currentContext();
     while (ctx) {
         if (index == 0)
             return ctx;
         ctx = ctx->parentContext();
         --index;
     }
     return 0;
 }
contextCount()
int QScriptDebuggerBackend::contextCount () const
Returns the number of contexts (frames).
Definition at line 807 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     if (!engine())
         return 0;
     return contextIds().count();
 }
contextIds()
QList< qint64 > QScriptDebuggerBackend::contextIds () const
Definition at line 841 of file qscriptdebuggerbackend.cpp.
Referenced by contextCount(), and QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return QList<qint64>();
     return d->agent->contextIds();
 }
contextsCheckpoint()
QScriptContextsDelta QScriptDebuggerBackend::contextsCheckpoint ()
Definition at line 849 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (!d->agent)
         return QScriptContextsDelta();
     return d->agent->contextsCheckpoint();
 }
continueEvalution()
void QScriptDebuggerBackend::continueEvalution ()
Continues script evaluation.
Evaluation will proceed without interruption until either 1) an uncaught exception occurs, 2) a breakpoint is triggered, or 3) interruptEvaluation() is called. In each case, a proper event() will be generated.
Definition at line 527 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterContinueMode();
         resume();
     }
 }
deleteAllBreakpoints()
void QScriptDebuggerBackend::deleteAllBreakpoints ()
Deletes all breakpoints.
Definition at line 697 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent)
         d->agent->deleteAllBreakpoints();
 }
deleteBreakpoint()
bool QScriptDebuggerBackend::deleteBreakpoint (int id)
Deletes the breakpoint identified by the given id.
Returns true if the breakpoint was deleted (i.e. the id was valid), otherwise returns false.
See also
setBreakpoint()
Definition at line 686 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (!d->agent)
         return false;
     return d->agent->deleteBreakpoint(id);
 }
deleteScriptObjectSnapshot()
void QScriptDebuggerBackend::deleteScriptObjectSnapshot (int id)
Definition at line 872 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     QScriptObjectSnapshot *snap = d->scriptObjectSnapshots.take(id);
     delete snap;
 }
deleteScriptValueIterator()
void QScriptDebuggerBackend::deleteScriptValueIterator (int id)
Definition at line 894 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     QScriptValueIterator *it = d->scriptValueIterators.take(id);
     delete it;
 }
detach()
void QScriptDebuggerBackend::detach ()
Detaches this backend from the current script engine.
The backend's state (including breakpoints and information on loaded scripts) will be invalidated.
See also
attach()
Definition at line 435 of file qscriptdebuggerbackend.cpp.
Referenced by attachTo(), and ~QScriptDebuggerBackend().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         QScriptEngine *eng = d->agent->engine();
         if (eng && eng->agent() == d->agent) {
             eng->setAgent(0);
             QScriptValue global = eng->globalObject();
             global.setProperty(QString::fromLatin1("print"), d->origTraceFunction);
             d->origTraceFunction = QScriptValue();
 //            global.setProperty(QString::fromLatin1("qAssert"), QScriptValue());
             global.setProperty(QString::fromLatin1("__FILE__"), QScriptValue(),
                                QScriptValue::PropertyGetter);
             global.setProperty(QString::fromLatin1("__FILE__"), d->origFileNameFunction);
             d->origFileNameFunction = QScriptValue();
             global.setProperty(QString::fromLatin1("__LINE__"), QScriptValue(),
                                QScriptValue::PropertyGetter);
             global.setProperty(QString::fromLatin1("__LINE__"), d->origLineNumberFunction);
             d->origLineNumberFunction = QScriptValue();
             d->agent->nullifyBackendPointer();
             d->agent = 0; // agent is owned by engine
         }
     }
     d->pendingEvaluateLineNumber = -1;
     d->ignoreExceptions = false;
     d->nextScriptValueIteratorId = 0;
     qDeleteAll(d->scriptValueIterators);
     d->scriptValueIterators.clear();
     qDeleteAll(d->scriptObjectSnapshots);
     d->scriptObjectSnapshots.clear();
 }
doPendingEvaluate()
void QScriptDebuggerBackend::doPendingEvaluate (bool postEvent)
Executes the pending evaluate, if any.
Definition at line 605 of file qscriptdebuggerbackend.cpp.
Referenced by evaluate(), and QScriptEngineDebuggerBackend::event().
 {
     Q_D(QScriptDebuggerBackend);
     QString program = d->pendingEvaluateProgram;
     if (program.isEmpty())
         return;
     int contextIndex = d->pendingEvaluateContextIndex;
     QScriptContext *ctx = context(contextIndex);
     Q_ASSERT(ctx != 0);
     QString fileName = d->pendingEvaluateFileName;
     int lineNumber = d->pendingEvaluateLineNumber;
     d->pendingEvaluateProgram = QString();
     d->pendingEvaluateFileName = QString();
     d->pendingEvaluateLineNumber = -1;
     d->pendingEvaluateContextIndex = -1;
     // push a new context and initialize its scope chain etc.
     {
         QScriptContext *evalContext = engine()->pushContext();
         QScriptValueList scopeChain = ctx->scopeChain();
         if (scopeChain.isEmpty())
             scopeChain.append(engine()->globalObject());
         while (!scopeChain.isEmpty())
             evalContext->pushScope(scopeChain.takeLast());
         evalContext->setActivationObject(ctx->activationObject());
         evalContext->setThisObject(ctx->thisObject());
     }
     d->agent->enterContinueMode();
     // set a flag so that any exception that happens in
     // the evaluate() is not sent to the debugger
     d->ignoreExceptions = true;
     bool hadException = engine()->hasUncaughtException();
     QScriptValue ret = engine()->evaluate(program, fileName, lineNumber);
     d->ignoreExceptions = false;
     if (!hadException && engine()->hasUncaughtException())
         engine()->clearExceptions();
     engine()->popContext();
     QScriptDebuggerValue retret(ret);
     QScriptDebuggerEvent e(QScriptDebuggerEvent::InlineEvalFinished);
     e.setScriptValue(retret);
     if (!ret.isUndefined())
         e.setMessage(ret.toString()); // for convenience -- we always need it
     e.setNestedEvaluate(engine()->isEvaluating());
     if (postEvent) {
         QScriptDebuggerEventEvent *de = new QScriptDebuggerEventEvent(e);
         d->postEvent(de);
     } else {
         event(e);
     }
 }
engine()
QScriptEngine * QScriptDebuggerBackend::engine () const
Returns the script engine that this backend is attached to, or 0 if the backend is not attached to an engine.
See also
attachTo()
Definition at line 474 of file qscriptdebuggerbackend.cpp.
Referenced by assertFunction(), backtrace(), context(), contextCount(), doPendingEvaluate(), evaluate(), QScriptDebuggerCommandExecutor::execute(), fileNameFunction(), lineNumberFunction(), and traceFunction().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return 0;
     return d->agent->engine();
 }
evaluate()
void QScriptDebuggerBackend::evaluate (int contextIndex, const QString & program, const QString & fileName, int lineNumber)
Evaluates the given program.
When evaluation is complete, an event() is generated.
Definition at line 588 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     d->pendingEvaluateContextIndex = contextIndex;
     d->pendingEvaluateProgram = program;
     d->pendingEvaluateFileName = fileName;
     d->pendingEvaluateLineNumber = lineNumber;
     if (!engine()->isEvaluating())
         doPendingEvaluate(/*postEvent=*/true);
     else
         resume();
 }
event()
void QScriptDebuggerBackend::event (const QScriptDebuggerEvent & event) protected pure virtual
This function is called when the back-end has generated the given event.
Subclasses must reimplement this function to handle the event. Typically the event is forwarded to a QScriptDebuggerFrontend, which will in turn forward it to its QScriptDebuggerClient. The client may then query the front-end for information about the execution state, and call e.g. continueEvalution() to resume execution. This function should block until resume() is called.
See also
resume()
Implemented in QScriptEngineDebuggerBackend.
Referenced by doPendingEvaluate().
fileNameFunction()
QScriptValue QScriptDebuggerBackend::fileNameFunction () const
Definition at line 936 of file qscriptdebuggerbackend.cpp.
Referenced by attachTo().
 {
     if (!engine())
         return QScriptValue();
     QScriptValue fun = engine()->newFunction(QScriptDebuggerBackendPrivate::fileName);
     return fun;
 }
ignoreExceptions()
bool QScriptDebuggerBackend::ignoreExceptions () const
Definition at line 901 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     return d->ignoreExceptions;
 }
interruptEvaluation()
void QScriptDebuggerBackend::interruptEvaluation ()
Interrupts script evaluation.
When the next script statement is reached, an event() will be generated.
Definition at line 540 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent)
         d->agent->enterInterruptMode();
 }
lineNumberFunction()
QScriptValue QScriptDebuggerBackend::lineNumberFunction () const
Definition at line 944 of file qscriptdebuggerbackend.cpp.
Referenced by attachTo().
 {
     if (!engine())
         return QScriptValue();
     QScriptValue fun = engine()->newFunction(QScriptDebuggerBackendPrivate::lineNumber);
     return fun;
 }
newScriptObjectSnapshot()
int QScriptDebuggerBackend::newScriptObjectSnapshot ()
Definition at line 857 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     int id = d->nextScriptObjectSnapshotId;
     ++d->nextScriptObjectSnapshotId;
     d->scriptObjectSnapshots[id] = new QScriptObjectSnapshot();
     return id;
 }
newScriptValueIterator()
int QScriptDebuggerBackend::newScriptValueIterator (const QScriptValue & object)
Definition at line 879 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     int id = d->nextScriptValueIteratorId;
     ++d->nextScriptValueIteratorId;
     d->scriptValueIterators[id] = new QScriptValueIterator(object);
     return id;
 }
resolveScript()
qint64 QScriptDebuggerBackend::resolveScript (const QString & fileName) const
Definition at line 796 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return -1;
     return d->agent->resolveScript(fileName);
 }
resume()
void QScriptDebuggerBackend::resume () pure virtual
This function is called when control should be returned back to the back-end, i.
e. when script evaluation should be resumed after an event has been delivered.
Subclasses must reimplement this function to make event() return.
See also
event()
Implemented in QScriptEngineDebuggerBackend.
Referenced by continueEvalution(), evaluate(), QScriptDebuggerCommandExecutor::execute(), returnToCaller(), runToLocation(), stepInto(), stepOut(), and stepOver().
returnToCaller()
void QScriptDebuggerBackend::returnToCaller (int contextIndex, const QScriptValue & value)
Definition at line 575 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterReturnByForceMode(contextIndex, value);
         resume();
     }
 }
runToLocation() [1/2]
void QScriptDebuggerBackend::runToLocation (const QString & fileName, int lineNumber)
Continues evaluation until the location defined by the given fileName and lineNumber is reached.
When the location is reached, an event() will be generated.
Definition at line 552 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterRunToLocationMode(fileName, lineNumber);
         resume();
     }
 }
runToLocation() [2/2]
void QScriptDebuggerBackend::runToLocation (qint64 scriptId, int lineNumber)
Continues evaluation until the location defined by the given scriptId and lineNumber is reached.
When the location is reached, an event() will be generated.
Definition at line 566 of file qscriptdebuggerbackend.cpp.
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterRunToLocationMode(scriptId, lineNumber);
         resume();
     }
 }
scriptData()
QScriptScriptData QScriptDebuggerBackend::scriptData (qint64 id) const
Returns the data for the script identified by the given id.
See also
scripts()
Definition at line 759 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return QScriptScriptData();
     return d->agent->scriptData(id);
 }
scriptObjectSnapshot()
QScriptObjectSnapshot * QScriptDebuggerBackend::scriptObjectSnapshot (int id) const
Definition at line 866 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     return d->scriptObjectSnapshots.value(id);
 }
scripts()
QScriptScriptMap QScriptDebuggerBackend::scripts () const
Returns the scripts that this backend knows about.
See also
scriptData()
Definition at line 746 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return QScriptScriptMap();
     return d->agent->scripts();
 }
scriptsCheckpoint()
void QScriptDebuggerBackend::scriptsCheckpoint ()
Makes a checkpoint of the currently loaded scripts.
See also
scriptsDelta()
Definition at line 772 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent)
         d->agent->scriptsCheckpoint();
 }
scriptsDelta()
QScriptScriptsDelta QScriptDebuggerBackend::scriptsDelta () const
Returns the difference between the latest scripts checkpoint and the previous checkpoint.
The first item in the pair is a list containing the identifiers of the scripts that were added. The second item in the pair is a list containing the identifiers of the scripts that were removed.
See also
scriptsCheckpoint()
Definition at line 788 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!d->agent)
         return QPair<QList<qint64>, QList<qint64> >();
     return d->agent->scriptsDelta();
 }
scriptValueIterator()
QScriptValueIterator * QScriptDebuggerBackend::scriptValueIterator (int id) const
Definition at line 888 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerBackend);
     return d->scriptValueIterators.value(id);
 }
setBreakpoint()
int QScriptDebuggerBackend::setBreakpoint (const QScriptBreakpointData & data)
Sets a breakpoint defined by the given data, and returns a unique identifier for the new breakpoint.
If the conditions of the breakpoint is satisfied at some point during script evaluation, a breakpoint event() will be generated.
See also
deleteBreakpoint(), breakpoints()
Definition at line 669 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (!d->agent)
         return -1;
     if (!data.isValid())
         return -1;
     return d->agent->setBreakpoint(data);
 }
setBreakpointData()
bool QScriptDebuggerBackend::setBreakpointData (int id, const QScriptBreakpointData & data)
Sets the data associated with the breakpoint identified by the given id.
Definition at line 720 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent)
         return d->agent->setBreakpointData(id, data);
     return false;
 }
setCommandExecutor()
void QScriptDebuggerBackend::setCommandExecutor (QScriptDebuggerCommandExecutor * executor)
Definition at line 962 of file qscriptdebuggerbackend.cpp.
 {
     Q_D(QScriptDebuggerBackend);
     d->commandExecutor = executor;
 }
setIgnoreExceptions()
void QScriptDebuggerBackend::setIgnoreExceptions (bool ignore)
Definition at line 907 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     d->ignoreExceptions = ignore;
 }
stepInto()
void QScriptDebuggerBackend::stepInto (int count = 1)
Steps into the next script statement.
When stepping is complete, an event() will be generated.
Definition at line 486 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterStepIntoMode(count);
         resume();
     }
 }
stepOut()
void QScriptDebuggerBackend::stepOut ()
Steps out of the current script function.
When stepping is complete, an event() will be generated.
Definition at line 512 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterStepOutMode();
         resume();
     }
 }
stepOver()
void QScriptDebuggerBackend::stepOver (int count = 1)
Steps over the next script statement.
When stepping is complete, an event() will be generated.
Definition at line 499 of file qscriptdebuggerbackend.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerBackend);
     if (d->agent) {
         d->agent->enterStepOverMode(count);
         resume();
     }
 }
traceFunction()
QScriptValue QScriptDebuggerBackend::traceFunction () const
Returns a trace function.
The trace function has similar semantics to the built-in print() function; however, instead of writing text to standard output, it generates a trace event containing the text.
Definition at line 918 of file qscriptdebuggerbackend.cpp.
Referenced by attachTo().
 {
     Q_D(const QScriptDebuggerBackend);
     if (!engine())
         return QScriptValue();
     QScriptValue fun = engine()->newFunction(QScriptDebuggerBackendPrivate::trace);
     fun.setData(qScriptValueFromValue(engine(), const_cast<QScriptDebuggerBackendPrivate*>(d)));
     return fun;
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerBackendPrivate> QScriptDebuggerBackend::d_ptr protected
Definition at line 147 of file qscriptdebuggerbackend_p.h.
Referenced by QScriptDebuggerBackend().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerbackend_p.h
/src/scripttools/debugging/qscriptdebuggerbackend.cpp