Qt 4.8: QTabBar Class Reference
QTabBar Class Reference
The QTabBar class provides a tab bar, e.g.
#include <qtabbar.h>
Public Types
enum ButtonPosition { LeftSide, RightSide }
This enum type lists the location of the widget on a tab.
enum SelectionBehavior { SelectLeftTab, SelectRightTab, SelectPreviousTab }
This enum type lists the behavior of QTabBar when a tab is removed and the tab being removed is also the current tab.
enum Shape {
RoundedNorth, RoundedSouth, RoundedWest, RoundedEast,
TriangularNorth, TriangularSouth, TriangularWest, TriangularEast
}
This enum type lists the built-in shapes supported by QTabBar.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void setCurrentIndex (int index)
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentChanged (int index)
This signal is emitted when the tab bar's current tab changes.
void tabCloseRequested (int index)
This signal is emitted when the close button on a tab is clicked.
void tabMoved (int from, int to)
This signal is emitted when the tab has moved the tab at index position from to index position to.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int addTab (const QString &text)
Adds a new tab with text text.
int addTab (const QIcon &icon, const QString &text)
Adds a new tab with icon icon and text text.
int count () const
int currentIndex () const
bool documentMode () const
bool drawBase () const
Qt::TextElideMode elideMode () const
bool expanding () const
QSize iconSize () const
int insertTab (int index, const QString &text)
Inserts a new tab with text text at position index.
int insertTab (int index, const QIcon &icon, const QString &text)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Inserts a new tab with icon icon and text text at position index.
bool isMovable () const
bool isTabEnabled (int index) const
Returns true if the tab at position index is enabled; otherwise returns false.
QSize minimumSizeHint () const
void moveTab (int from, int to)
Moves the item at index position from to index position to.
QTabBar (QWidget *parent=0)
Creates a new tab bar with the given parent.
void removeTab (int index)
Removes the tab at position index.
SelectionBehavior selectionBehaviorOnRemove () const
void setDocumentMode (bool set)
void setDrawBase (bool drawTheBase)
void setElideMode (Qt::TextElideMode)
void setExpanding (bool enabled)
void setIconSize (const QSize &size)
void setMovable (bool movable)
void setSelectionBehaviorOnRemove (SelectionBehavior behavior)
void setShape (Shape shape)
void setTabButton (int index, ButtonPosition position, QWidget *widget)
Sets widget on the tab index.
void setTabData (int index, const QVariant &data)
Sets the data of the tab at position index to data.
void setTabEnabled (int index, bool)
If enabled is true then the tab at position index is enabled; otherwise the item at position index is disabled.
void setTabIcon (int index, const QIcon &icon)
Sets the icon of the tab at position index to icon.
void setTabsClosable (bool closable)
void setTabText (int index, const QString &text)
Sets the text of the tab at position index to text.
void setTabTextColor (int index, const QColor &color)
Sets the color of the text in the tab with the given index to the specified color.
void setTabToolTip (int index, const QString &tip)
Sets the tool tip of the tab at position index to tip.
void setTabWhatsThis (int index, const QString &text)
Sets the What's This help text of the tab at position index to text.
void setUsesScrollButtons (bool useButtons)
Shape shape () const
QSize sizeHint () const
em>Reimplemented Function
int tabAt (const QPoint &pos) const
QWidget * tabButton (int index, ButtonPosition position) const
Returns the widget set a tab index and position or 0 if one is not set.
QVariant tabData (int index) const
Returns the data of the tab at position index, or a null variant if index is out of range.
QIcon tabIcon (int index) const
Returns the icon of the tab at position index, or a null icon if index is out of range.
QRect tabRect (int index) const
Returns the visual rectangle of the tab at position index, or a null rectangle if index is out of range.
bool tabsClosable () const
QString tabText (int index) const
Returns the text of the tab at position index, or an empty string if index is out of range.
QColor tabTextColor (int index) const
Returns the text color of the tab with the given index, or a invalid color if index is out of range.
QString tabToolTip (int index) const
Returns the tool tip of the tab at position index, or an empty string if index is out of range.
QString tabWhatsThis (int index) const
Returns the What's This help text of the tab at position index, or an empty string if index is out of range.
bool usesScrollButtons () const
~QTabBar ()
Destroys the tab bar.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
bool event (QEvent *)
em>Reimplemented Function
void hideEvent (QHideEvent *)
em>Reimplemented Function
void initStyleOption (QStyleOptionTab *option, int tabIndex) const
Initialize option with the values from the tab at tabIndex.
void keyPressEvent (QKeyEvent *)
em>Reimplemented Function
void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
void mousePressEvent (QMouseEvent *)
em>Reimplemented Function
void mouseReleaseEvent (QMouseEvent *)
em>Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
void resizeEvent (QResizeEvent *)
em>Reimplemented Function
void showEvent (QShowEvent *)
em>Reimplemented Function
virtual void tabInserted (int index)
This virtual handler is called after a new tab was added or inserted at position index.
virtual void tabLayoutChange ()
This virtual handler is called whenever the tab layout changes.
virtual void tabRemoved (int index)
This virtual handler is called after a tab was removed from position index.
virtual QSize tabSizeHint (int index) const
Returns the size hint for the tab at position index.
void wheelEvent (QWheelEvent *event)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
int count
the number of tabs in the tab bar
int currentIndex
the index of the tab bar's visible tab
bool documentMode
Whether or not the tab bar is rendered in a mode suitable for the main window.
bool drawBase
defines whether or not tab bar should draw its base.
Qt::TextElideMode elideMode
how to elide text in the tab bar
bool expanding
When expanding is true QTabBar will expand the tabs to use the empty space.
QSize iconSize
The size for icons in the tab bar.
bool movable
This property holds whether the user can move the tabs within the tabbar area.
SelectionBehavior selectionBehaviorOnRemove
What tab should be set as current when removeTab is called if the removed tab is also the current tab.
Shape shape
the shape of the tabs in the tab bar
bool tabsClosable
Whether or not a tab bar should place close buttons on each tab.
bool usesScrollButtons
Whether or not a tab bar should use buttons to scroll tabs when it has many tabs.
Friends
class QAccessibleTabBar
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTabBar class provides a tab bar, e.g.
for use in tabbed dialogs.
QTabBar is straightforward to use; it draws the tabs using one of the predefined shapes, and emits a signal when a tab is selected. It can be subclassed to tailor the look and feel. Qt also provides a ready-made QTabWidget.
Each tab has a tabText(), an optional tabIcon(), an optional tabToolTip(), optional tabWhatsThis() and optional tabData(). The tabs's attributes can be changed with setTabText(), setTabIcon(), setTabToolTip(), setTabWhatsThis and setTabData(). Each tabs can be enabled or disabled individually with setTabEnabled().
Each tab can display text in a distinct color. The current text color for a tab can be found with the tabTextColor() function. Set the text color for a particular tab with setTabTextColor().
Tabs are added using addTab(), or inserted at particular positions using insertTab(). The total number of tabs is given by count(). Tabs can be removed from the tab bar with removeTab(). Combining removeTab() and insertTab() allows you to move tabs to different positions.
The shape property defines the tabs' appearance. The choice of shape is a matter of taste, although tab dialogs (for preferences and similar) invariably use RoundedNorth . Tab controls in windows other than dialogs almost always use either RoundedSouth or TriangularSouth . Many spreadsheets and other tab controls in which all the pages are essentially similar use TriangularSouth , whereas RoundedSouth is used mostly when the pages are different (e.g. a multi-page tool palette). The default in QTabBar is RoundedNorth .
The most important part of QTabBar's API is the currentChanged() signal. This is emitted whenever the current tab changes (even at startup, when the current tab changes from 'none'). There is also a slot, setCurrentIndex(), which can be used to select a tab programmatically. The function currentIndex() returns the index of the current tab, count holds the number of tabs.
QTabBar creates automatic mnemonic keys in the manner of QAbstractButton; e.g. if a tab's label is "\&Graphics", Alt+G becomes a shortcut key for switching to that tab.
The following virtual functions may need to be reimplemented in order to tailor the look and feel or store extra data with each tab:
tabSizeHint() calcuates the size of a tab.
tabInserted() notifies that a new tab was added.
tabRemoved() notifies that a tab was removed.
tabLayoutChange() notifies that the tabs have been re-laid out.
paintEvent() paints all tabs.
For subclasses, you might also need the tabRect() functions which returns the visual geometry of a single tab.
Screenshot of a Plastique style tab bar
A tab bar shown in the Plastique widget style.
Screenshot of a truncated Plastique tab bar
A truncated tab bar shown in the Plastique widget style.
See also
QTabWidget
Definition at line 59 of file qtabbar.h.
Enumerations
ButtonPosition
enum QTabBar::ButtonPosition
This enum type lists the location of the widget on a tab.
Since
4.5
LeftSide Left side of the tab.
RightSide Right side of the tab.
Enumerator
LeftSide
RightSide
Definition at line 89 of file qtabbar.h.
{
         LeftSide,
         RightSide
     };
SelectionBehavior
enum QTabBar::SelectionBehavior
This enum type lists the behavior of QTabBar when a tab is removed and the tab being removed is also the current tab.
Since
4.5
SelectLeftTab Select the tab to the left of the one being removed.
SelectRightTab Select the tab to the right of the one being removed.
SelectPreviousTab Select the previously selected tab.
Enumerator
SelectLeftTab
SelectRightTab
SelectPreviousTab
Definition at line 94 of file qtabbar.h.
{
         SelectLeftTab,
         SelectRightTab,
         SelectPreviousTab
     };
Shape
enum QTabBar::Shape
This enum type lists the built-in shapes supported by QTabBar.
Treat these as hints as some styles may not render some of the shapes. However, position should be honored.
RoundedNorth The normal rounded look above the pages
RoundedSouth The normal rounded look below the pages
RoundedWest The normal rounded look on the left side of the pages
RoundedEast The normal rounded look on the right side the pages
TriangularNorth Triangular tabs above the pages.
TriangularSouth Triangular tabs similar to those used in the Excel spreadsheet, for example
TriangularWest Triangular tabs on the left of the pages.
TriangularEast Triangular tabs on the right of the pages.
RoundedAbove
RoundedBelow
TriangularAbove
TriangularBelow
Enumerator
RoundedNorth
RoundedSouth
RoundedWest
RoundedEast
TriangularNorth
TriangularSouth
TriangularWest
TriangularEast
Definition at line 81 of file qtabbar.h.
                { RoundedNorth, RoundedSouth, RoundedWest, RoundedEast,
                  TriangularNorth, TriangularSouth, TriangularWest, TriangularEast
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
                 , RoundedAbove = RoundedNorth, RoundedBelow = RoundedSouth,
                 TriangularAbove = TriangularNorth, TriangularBelow = TriangularSouth
 #endif
     };
Constructors and Destructors
QTabBar()
QTabBar::QTabBar (QWidget * parent = 0) explicit
Creates a new tab bar with the given parent.
Definition at line 746 of file qtabbar.cpp.
     :QWidget(*new QTabBarPrivate, parent, 0)
 {
     Q_D(QTabBar);
     d->init();
 }
~QTabBar()
QTabBar::~QTabBar ()
Destroys the tab bar.
Definition at line 757 of file qtabbar.cpp.
 {
 }
Functions
addTab() [1/2]
int QTabBar::addTab (const QString & text)
Adds a new tab with text text.
Returns the new tab's index.
Definition at line 819 of file qtabbar.cpp.
Referenced by QMdiAreaPrivate::appendChild(), and QMdiAreaPrivate::setViewMode().
 {
     return insertTab(-1, text);
 }
addTab() [2/2]
int QTabBar::addTab (const QIcon & icon, const QString & text)
Adds a new tab with icon icon and text text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns the new tab's index.
Definition at line 833 of file qtabbar.cpp.
 {
     return insertTab(-1, icon, text);
 }
changeEvent()
void QTabBar::changeEvent (QEvent * event) protected virtual
This event handler can be reimplemented to handle state changes.
The state being changed in this event can be retrieved through the event supplied.
Change events include: QEvent::ToolBarChange, QEvent::ActivationChange, QEvent::EnabledChange, QEvent::FontChange, QEvent::StyleChange, QEvent::PaletteChange, QEvent::WindowTitleChange, QEvent::IconTextChange, QEvent::ModifiedChange, QEvent::MouseTrackingChange, QEvent::ParentChange, QEvent::WindowStateChange, QEvent::LanguageChange, QEvent::LocaleChange, QEvent::LayoutDirectionChange.
Reimplemented from QWidget.
Definition at line 2040 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (event->type() == QEvent::StyleChange) {
         if (!d->elideModeSetByUser)
             d->elideMode = Qt::TextElideMode(style()->styleHint(QStyle::SH_TabBar_ElideMode, 0, this));
         if (!d->useScrollButtonsSetByUser)
             d->useScrollButtons = !style()->styleHint(QStyle::SH_TabBar_PreferNoArrows, 0, this);
         d->refresh();
     } else if (event->type() == QEvent::FontChange) {
         d->refresh();
     }
     QWidget::changeEvent(event);
 }
count()
int QTabBar::count () const
Referenced by setCurrentIndex(), and setIconSize().
currentChanged
void QTabBar::currentChanged (int index) signal
This signal is emitted when the tab bar's current tab changes.
The new current has the given index, or -1 if there isn't a new one (for example, if there are no tab in the QTabBar)
Referenced by QMainWindowLayout::getTabBar(), removeTab(), and setCurrentIndex().
currentIndex()
int QTabBar::currentIndex () const
Referenced by QMdiAreaPrivate::emitWindowActivated(), insertTab(), removeTab(), QTabBarPrivate::setCurrentNextEnabledIndex(), and tabAt().
documentMode()
bool QTabBar::documentMode () const
Referenced by setMovable().
drawBase()
bool QTabBar::drawBase () const
Referenced by setDrawBase().
elideMode()
Qt::TextElideMode QTabBar::elideMode () const
Referenced by changeEvent(), and QTabBarPrivate::minimumTabSizeHint().
event()
bool QTabBar::event (QEvent * event) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1490 of file qtabbar.cpp.
Referenced by QMainWindowTabBar::event().
expanding()
bool QTabBar::expanding () const
Referenced by setSelectionBehaviorOnRemove().
hideEvent()
void QTabBar::hideEvent (QHideEvent *) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1482 of file qtabbar.cpp.
iconSize()
QSize QTabBar::iconSize () const
Referenced by setCurrentIndex(), and tabSizeHint().
initStyleOption()
void QTabBar::initStyleOption (QStyleOptionTab * option, int tabIndex) const protected
Initialize option with the values from the tab at tabIndex.
This method is useful for subclasses when they need a QStyleOptionTab, QStyleOptionTabV2, or QStyleOptionTabV3 but don't want to fill in all the information themselves. This function will check the version of the QStyleOptionTab and fill in the additional values for a QStyleOptionTabV2 and QStyleOptionTabV3.
See also
QStyleOption::initFrom() QTabWidget::initStyleOption()
Definition at line 130 of file qtabbar.cpp.
Referenced by insertTab(), paintEvent(), and tabSizeHint().
 {
     Q_D(const QTabBar);
     int totalTabs = d->tabList.size();
     if (!option || (tabIndex < 0 || tabIndex >= totalTabs))
         return;
     const QTabBarPrivate::Tab &tab = d->tabList.at(tabIndex);
     option->initFrom(this);
     option->state &= ~(QStyle::State_HasFocus | QStyle::State_MouseOver);
     option->rect = tabRect(tabIndex);
     bool isCurrent = tabIndex == d->currentIndex;
     option->row = 0;
     if (tabIndex == d->pressedIndex)
         option->state |= QStyle::State_Sunken;
     if (isCurrent)
         option->state |= QStyle::State_Selected;
     if (isCurrent && hasFocus())
         option->state |= QStyle::State_HasFocus;
     if (!tab.enabled)
         option->state &= ~QStyle::State_Enabled;
     if (isActiveWindow())
         option->state |= QStyle::State_Active;
     if (!d->dragInProgress && option->rect == d->hoverRect)
         option->state |= QStyle::State_MouseOver;
     option->shape = d->shape;
     option->text = tab.text;
     if (tab.textColor.isValid())
         option->palette.setColor(foregroundRole(), tab.textColor);
     option->icon = tab.icon;
     if (QStyleOptionTabV2 *optionV2 = qstyleoption_cast<QStyleOptionTabV2 *>(option))
         optionV2->iconSize = iconSize();  // Will get the default value then.
     if (QStyleOptionTabV3 *optionV3 = qstyleoption_cast<QStyleOptionTabV3 *>(option)) {
         optionV3->leftButtonSize = tab.leftWidget ? tab.leftWidget->size() : QSize();
         optionV3->rightButtonSize = tab.rightWidget ? tab.rightWidget->size() : QSize();
         optionV3->documentMode = d->documentMode;
     }
     if (tabIndex > 0 && tabIndex - 1 == d->currentIndex)
         option->selectedPosition = QStyleOptionTab::PreviousIsSelected;
     else if (tabIndex + 1 < totalTabs && tabIndex + 1 == d->currentIndex)
         option->selectedPosition = QStyleOptionTab::NextIsSelected;
     else
         option->selectedPosition = QStyleOptionTab::NotAdjacent;
     bool paintBeginning = (tabIndex == 0) || (d->dragInProgress && tabIndex == d->pressedIndex + 1);
     bool paintEnd = (tabIndex == totalTabs - 1) || (d->dragInProgress && tabIndex == d->pressedIndex - 1);
     if (paintBeginning) {
         if (paintEnd)
             option->position = QStyleOptionTab::OnlyOneTab;
         else
             option->position = QStyleOptionTab::Beginning;
     } else if (paintEnd) {
         option->position = QStyleOptionTab::End;
     } else {
         option->position = QStyleOptionTab::Middle;
     }
 #ifndef QT_NO_TABWIDGET
     if (const QTabWidget *tw = qobject_cast<const QTabWidget *>(parentWidget())) {
         if (tw->cornerWidget(Qt::TopLeftCorner) || tw->cornerWidget(Qt::BottomLeftCorner))
             option->cornerWidgets |= QStyleOptionTab::LeftCornerWidget;
         if (tw->cornerWidget(Qt::TopRightCorner) || tw->cornerWidget(Qt::BottomRightCorner))
             option->cornerWidgets |= QStyleOptionTab::RightCornerWidget;
     }
 #endif
     QRect textRect = style()->subElementRect(QStyle::SE_TabBarTabText, option, this);
     option->text = fontMetrics().elidedText(option->text, d->elideMode, textRect.width(),
                         Qt::TextShowMnemonic);
 }
insertTab() [1/2]
int QTabBar::insertTab (int index, const QString & text)
Inserts a new tab with text text at position index.
If index is out of range, the new tab is appened. Returns the new tab's index.
Definition at line 843 of file qtabbar.cpp.
Referenced by addTab(), and QDockAreaLayoutInfo::updateTabBar().
 {
     return insertTab(index, QIcon(), text);
 }
insertTab() [2/2]
int QTabBar::insertTab (int index, const QIcon & icon, const QString & text)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Inserts a new tab with icon icon and text text at position index.
If index is out of range, the new tab is appended. Returns the new tab's index.
If the QTabBar was empty before this function is called, the inserted tab becomes the current tab.
Inserting a new tab at an index less than or equal to the current index will increment the current index, but keep the current tab.
Definition at line 860 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (!d->validIndex(index)) {
         index = d->tabList.count();
         d->tabList.append(QTabBarPrivate::Tab(icon, text));
     } else {
         d->tabList.insert(index, QTabBarPrivate::Tab(icon, text));
     }
 #ifndef QT_NO_SHORTCUT
     d->tabList[index].shortcutId = grabShortcut(QKeySequence::mnemonic(text));
 #endif
     d->refresh();
     if (d->tabList.count() == 1)
         setCurrentIndex(index);
     else if (index <= d->currentIndex)
         ++d->currentIndex;
     if (d->closeButtonOnTabs) {
         QStyleOptionTabV3 opt;
         initStyleOption(&opt, index);
         ButtonPosition closeSide = (ButtonPosition)style()->styleHint(QStyle::SH_TabBar_CloseButtonPosition, 0, this);
         QAbstractButton *closeButton = new CloseButton(this);
         connect(closeButton, SIGNAL(clicked()), this, SLOT(_q_closeTab()));
         setTabButton(index, closeSide, closeButton);
     }
     for (int i = 0; i < d->tabList.count(); ++i) {
         if (d->tabList[i].lastTab >= index)
             ++d->tabList[i].lastTab;
     }
     tabInserted(index);
     return index;
 }
isMovable()
bool QTabBar::isMovable () const
Definition at line 2293 of file qtabbar.cpp.
Referenced by QTabWidget::isMovable().
 {
     Q_D(const QTabBar);
     return d->movable;
 }
isTabEnabled()
bool QTabBar::isTabEnabled (int index) const
Returns true if the tab at position index is enabled; otherwise returns false.
Definition at line 977 of file qtabbar.cpp.
Referenced by QAccessibleTabBar::state().
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->enabled;
     return false;
 }
keyPressEvent()
void QTabBar::keyPressEvent (QKeyEvent * event) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 2004 of file qtabbar.cpp.
minimumSizeHint()
QSize QTabBar::minimumSizeHint () const virtual
Reimplemented from QWidget.
Definition at line 1331 of file qtabbar.cpp.
Referenced by QDockAreaLayoutInfo::tabBarMinimumSize().
 {
     Q_D(const QTabBar);
     if (d->layoutDirty)
         const_cast<QTabBarPrivate*>(d)->layoutTabs();
     if (!d->useScrollButtons) {
         QRect r;
         for (int i = 0; i < d->tabList.count(); ++i)
             r = r.united(d->tabList.at(i).minRect);
         return r.size().expandedTo(QApplication::globalStrut());
     }
     if (verticalTabs(d->shape))
         return QSize(sizeHint().width(), d->rightB->sizeHint().height() * 2 + 75);
     else
         return QSize(d->rightB->sizeHint().width() * 2 + 75, sizeHint().height());
 }
mouseMoveEvent()
void QTabBar::mouseMoveEvent (QMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
If mouse tracking is switched off, mouse move events only occur if a mouse button is pressed while the mouse is being moved. If mouse tracking is switched on, mouse move events occur even if no mouse button is pressed.
QMouseEvent::pos() reports the position of the mouse cursor, relative to this widget. For press and release events, the position is usually the same as the position of the last mouse move event, but it might be different if the user's hand shakes. This is a feature of the underlying window system, not Qt.
If you want to show a tooltip immediately, while the mouse is moving (e.g., to get the mouse coordinates with QMouseEvent::pos() and show them as a tooltip), you must first enable mouse tracking as described above. Then, to ensure that the tooltip is updated immediately, you must call QToolTip::showText() instead of setToolTip() in your implementation of mouseMoveEvent().
See also
setMouseTracking(), mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), event(), QMouseEvent, {Scribble Example}
Reimplemented from QWidget.
Definition at line 1810 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (d->movable) {
         // Be safe!
         if (d->pressedIndex != -1
             && event->buttons() == Qt::NoButton)
             d->moveTabFinished(d->pressedIndex);
         // Start drag
         if (!d->dragInProgress && d->pressedIndex != -1) {
             if ((event->pos() - d->dragStartPosition).manhattanLength() > QApplication::startDragDistance()) {
                 d->dragInProgress = true;
                 d->setupMovableTab();
             }
         }
         int offset = (event->pos() - d->dragStartPosition).manhattanLength();
         if (event->buttons() == Qt::LeftButton
             && offset > QApplication::startDragDistance()
             && d->validIndex(d->pressedIndex)) {
             bool vertical = verticalTabs(d->shape);
             int dragDistance;
             if (vertical) {
                 dragDistance = (event->pos().y() - d->dragStartPosition.y());
             } else {
                 dragDistance = (event->pos().x() - d->dragStartPosition.x());
             }
             d->tabList[d->pressedIndex].dragOffset = dragDistance;
             QRect startingRect = tabRect(d->pressedIndex);
             if (vertical)
                 startingRect.moveTop(startingRect.y() + dragDistance);
             else
                 startingRect.moveLeft(startingRect.x() + dragDistance);
             int overIndex;
             if (dragDistance < 0)
                 overIndex = tabAt(startingRect.topLeft());
             else
                 overIndex = tabAt(startingRect.topRight());
             if (overIndex != d->pressedIndex && overIndex != -1) {
                 int offset = 1;
                 if (isRightToLeft() && !vertical)
                     offset *= -1;
                 if (dragDistance < 0) {
                     dragDistance *= -1;
                     offset *= -1;
                 }
                 for (int i = d->pressedIndex;
                      offset > 0 ? i < overIndex : i > overIndex;
                      i += offset) {
                     QRect overIndexRect = tabRect(overIndex);
                     int needsToBeOver = (vertical ? overIndexRect.height() : overIndexRect.width()) / 2;
                     if (dragDistance > needsToBeOver)
                         d->slide(i + offset, d->pressedIndex);
                 }
             }
             // Buttons needs to follow the dragged tab
             d->layoutTab(d->pressedIndex);
             update();
         }
 #ifdef Q_WS_MAC
     } else if (!d->documentMode && event->buttons() == Qt::LeftButton && d->previousPressedIndex != -1) {
         int newPressedIndex = d->indexAtPos(event->pos());
         if (d->pressedIndex == -1 && d->previousPressedIndex == newPressedIndex) {
             d->pressedIndex = d->previousPressedIndex;
             update(tabRect(d->pressedIndex));
         } else if(d->pressedIndex != newPressedIndex) {
             d->pressedIndex = -1;
             update(tabRect(d->previousPressedIndex));
         }
 #endif
     }
     if (event->buttons() != Qt::LeftButton) {
         event->ignore();
         return;
     }
     QStyleOptionTabBarBaseV2 optTabBase;
     optTabBase.init(this);
     optTabBase.documentMode = d->documentMode;
 }
mousePressEvent()
void QTabBar::mousePressEvent (QMouseEvent * event) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1779 of file qtabbar.cpp.
Referenced by QMdiAreaTabBar::mousePressEvent().
mouseReleaseEvent()
void QTabBar::mouseReleaseEvent (QMouseEvent * event) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1970 of file qtabbar.cpp.
moveTab()
void QTabBar::moveTab (int from, int to)
Moves the item at index position from to index position to.
Since
4.5
See also
tabMoved(), tabLayoutChange()
Definition at line 1672 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (from == to
         || !d->validIndex(from)
         || !d->validIndex(to))
         return;
     bool vertical = verticalTabs(d->shape);
     int oldPressedPosition = 0;
     if (d->pressedIndex != -1) {
         // Record the position of the pressed tab before reordering the tabs.
         oldPressedPosition = vertical ? d->tabList[d->pressedIndex].rect.y()
                              : d->tabList[d->pressedIndex].rect.x();
     }
     // Update the locations of the tabs first
     int start = qMin(from, to);
     int end = qMax(from, to);
     int width = vertical ? d->tabList[from].rect.height() : d->tabList[from].rect.width();
     if (from < to)
         width *= -1;
     bool rtl = isRightToLeft();
     for (int i = start; i <= end; ++i) {
         if (i == from)
             continue;
         if (vertical)
             d->tabList[i].rect.moveTop(d->tabList[i].rect.y() + width);
         else
             d->tabList[i].rect.moveLeft(d->tabList[i].rect.x() + width);
         int direction = -1;
         if (rtl && !vertical)
             direction *= -1;
         if (d->tabList[i].dragOffset != 0)
             d->tabList[i].dragOffset += (direction * width);
     }
     if (vertical) {
         if (from < to)
             d->tabList[from].rect.moveTop(d->tabList[to].rect.bottom() + 1);
         else
             d->tabList[from].rect.moveTop(d->tabList[to].rect.top() - width);
     } else {
         if (from < to)
             d->tabList[from].rect.moveLeft(d->tabList[to].rect.right() + 1);
         else
             d->tabList[from].rect.moveLeft(d->tabList[to].rect.left() - width);
     }
     // Move the actual data structures
     d->tabList.move(from, to);
     // update lastTab locations
     for (int i = 0; i < d->tabList.count(); ++i)
         d->tabList[i].lastTab = d->calculateNewPosition(from, to, d->tabList[i].lastTab);
     // update external variables
     d->currentIndex = d->calculateNewPosition(from, to, d->currentIndex);
     // If we are in the middle of a drag update the dragStartPosition
     if (d->pressedIndex != -1) {
         d->pressedIndex = d->calculateNewPosition(from, to, d->pressedIndex);
         int newPressedPosition = vertical ? d->tabList[d->pressedIndex].rect.top() : d->tabList[d->pressedIndex].rect.left();
         int diff = oldPressedPosition - newPressedPosition;
         if (isRightToLeft() && !vertical)
             diff *= -1;
         if (vertical)
             d->dragStartPosition.setY(d->dragStartPosition.y() - diff);
         else
             d->dragStartPosition.setX(d->dragStartPosition.x() - diff);
     }
     d->layoutWidgets(start);
     update();
     emit tabMoved(from, to);
     emit tabLayoutChange();
 }
paintEvent()
void QTabBar::paintEvent (QPaintEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive paint events passed in event.
A paint event is a request to repaint all or part of a widget. It can happen for one of the following reasons:
repaint() or update() was invoked,
the widget was obscured and has now been uncovered, or
many other reasons.
Many widgets can simply repaint their entire surface when asked to, but some slow widgets need to optimize by painting only the requested region: QPaintEvent::region(). This speed optimization does not change the result, as painting is clipped to that region during event processing. QListView and QTableView do this, for example.
Qt also tries to speed up painting by merging multiple paint events into one. When update() is called several times or the window system sends several paint events, Qt merges these events into one event with a larger region (see QRegion::united()). The repaint() function does not permit this optimization, so we suggest using update() whenever possible.
When the paint event occurs, the update region has normally been erased, so you are painting on the widget's background.
The background can be set using setBackgroundRole() and setPalette().
Since Qt 4.0, QWidget automatically double-buffers its painting, so there is no need to write double-buffering code in paintEvent() to avoid flicker.
Note for the X11 platform: It is possible to toggle global double buffering by calling qt_x11_set_global_double_buffer(). For example,
...
extern void qt_x11_set_global_double_buffer(bool);
qt_x11_set_global_double_buffer(false);
...
Note
Generally, you should refrain from calling update() or repaint() inside a paintEvent(). For example, calling update() or repaint() on children inside a paintevent() results in undefined behavior; the child may or may not get a paint event.
Warning
If you are using a custom paint engine without Qt's backingstore, Qt::WA_PaintOnScreen must be set. Otherwise, QWidget::paintEngine() will never be called; the backingstore will be used instead.
See also
event(), repaint(), update(), QPainter, QPixmap, QPaintEvent, {Analog Clock Example}
Reimplemented from QWidget.
Definition at line 1568 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     QStyleOptionTabBarBaseV2 optTabBase;
     QTabBarPrivate::initStyleBaseOption(&optTabBase, this, size());
     QStylePainter p(this);
     int selected = -1;
     int cut = -1;
     bool rtl = optTabBase.direction == Qt::RightToLeft;
     bool vertical = verticalTabs(d->shape);
     QStyleOptionTab cutTab;
     selected = d->currentIndex;
     if (d->dragInProgress)
         selected = d->pressedIndex;
     for (int i = 0; i < d->tabList.count(); ++i)
          optTabBase.tabBarRect |= tabRect(i);
     optTabBase.selectedTabRect = tabRect(selected);
     if (d->drawBase)
         p.drawPrimitive(QStyle::PE_FrameTabBarBase, optTabBase);
     for (int i = 0; i < d->tabList.count(); ++i) {
         QStyleOptionTabV3 tab;
         initStyleOption(&tab, i);
         if (d->paintWithOffsets && d->tabList[i].dragOffset != 0) {
             if (vertical) {
                 tab.rect.moveTop(tab.rect.y() + d->tabList[i].dragOffset);
             } else {
                 tab.rect.moveLeft(tab.rect.x() + d->tabList[i].dragOffset);
             }
         }
         if (!(tab.state & QStyle::State_Enabled)) {
             tab.palette.setCurrentColorGroup(QPalette::Disabled);
         }
         // If this tab is partially obscured, make a note of it so that we can pass the information
         // along when we draw the tear.
         if (((!vertical && (!rtl && tab.rect.left() < 0)) || (rtl && tab.rect.right() > width()))
             || (vertical && tab.rect.top() < 0)) {
             cut = i;
             cutTab = tab;
         }
         // Don't bother drawing a tab if the entire tab is outside of the visible tab bar.
         if ((!vertical && (tab.rect.right() < 0 || tab.rect.left() > width()))
             || (vertical && (tab.rect.bottom() < 0 || tab.rect.top() > height())))
             continue;
         optTabBase.tabBarRect |= tab.rect;
         if (i == selected)
             continue;
         p.drawControl(QStyle::CE_TabBarTab, tab);
     }
     // Draw the selected tab last to get it "on top"
     if (selected >= 0) {
         QStyleOptionTabV3 tab;
         initStyleOption(&tab, selected);
         if (d->paintWithOffsets && d->tabList[selected].dragOffset != 0) {
             if (vertical)
                 tab.rect.moveTop(tab.rect.y() + d->tabList[selected].dragOffset);
             else
                 tab.rect.moveLeft(tab.rect.x() + d->tabList[selected].dragOffset);
         }
         if (!d->dragInProgress)
             p.drawControl(QStyle::CE_TabBarTab, tab);
         else {
             int taboverlap = style()->pixelMetric(QStyle::PM_TabBarTabOverlap, 0, this);
             d->movingTab->setGeometry(tab.rect.adjusted(-taboverlap, 0, taboverlap, 0));
         }
     }
     // Only draw the tear indicator if necessary. Most of the time we don't need too.
     if (d->leftB->isVisible() && cut >= 0) {
         cutTab.rect = rect();
         cutTab.rect = style()->subElementRect(QStyle::SE_TabBarTearIndicator, &cutTab, this);
         p.drawPrimitive(QStyle::PE_IndicatorTabTear, cutTab);
     }
 }
removeTab()
void QTabBar::removeTab (int index)
Removes the tab at position index.
See also
SelectionBehavior
Definition at line 902 of file qtabbar.cpp.
Referenced by QMainWindowLayout::applyState(), QMdiAreaPrivate::updateActiveWindow(), and QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(QTabBar);
     if (d->validIndex(index)) {
 #ifndef QT_NO_SHORTCUT
         releaseShortcut(d->tabList.at(index).shortcutId);
 #endif
         if (d->tabList[index].leftWidget) {
             d->tabList[index].leftWidget->hide();
             d->tabList[index].leftWidget->deleteLater();
             d->tabList[index].leftWidget = 0;
         }
         if (d->tabList[index].rightWidget) {
             d->tabList[index].rightWidget->hide();
             d->tabList[index].rightWidget->deleteLater();
             d->tabList[index].rightWidget = 0;
         }
         int newIndex = d->tabList[index].lastTab;
         d->tabList.removeAt(index);
         for (int i = 0; i < d->tabList.count(); ++i) {
             if (d->tabList[i].lastTab == index)
                 d->tabList[i].lastTab = -1;
             if (d->tabList[i].lastTab > index)
                 --d->tabList[i].lastTab;
         }
         if (index == d->currentIndex) {
             // The current tab is going away, in order to make sure
             // we emit that "current has changed", we need to reset this
             // around.
             d->currentIndex = -1;
             if (d->tabList.size() > 0) {
                 switch(d->selectionBehaviorOnRemove) {
                 case SelectPreviousTab:
                     if (newIndex > index)
                         newIndex--;
                     if (d->validIndex(newIndex))
                         break;
                     // else fallthrough
                 case SelectRightTab:
                     newIndex = index;
                     if (newIndex >= d->tabList.size())
                         newIndex = d->tabList.size() - 1;
                     break;
                 case SelectLeftTab:
                     newIndex = index - 1;
                     if (newIndex < 0)
                         newIndex = 0;
                     break;
                 default:
                     break;
                 }
                 if (d->validIndex(newIndex)) {
                     // don't loose newIndex's old through setCurrentIndex
                     int bump = d->tabList[newIndex].lastTab;
                     setCurrentIndex(newIndex);
                     d->tabList[newIndex].lastTab = bump;
                 }
             } else {
                 emit currentChanged(-1);
             }
         } else if (index < d->currentIndex) {
             setCurrentIndex(d->currentIndex - 1);
         }
         d->refresh();
         tabRemoved(index);
     }
 }
resizeEvent()
void QTabBar::resizeEvent (QResizeEvent *) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1556 of file qtabbar.cpp.
selectionBehaviorOnRemove()
SelectionBehavior QTabBar::selectionBehaviorOnRemove () const
Referenced by setTabsClosable().
setCurrentIndex
void QTabBar::setCurrentIndex (int index) slot
Definition at line 1238 of file qtabbar.cpp.
Referenced by QAccessibleTabBar::doAction(), QMdiAreaPrivate::emitWindowActivated(), event(), insertTab(), mousePressEvent(), mouseReleaseEvent(), removeTab(), QDockAreaLayoutInfo::setCurrentTabId(), QAccessibleTabBar::setSelected(), setTabEnabled(), QMdiAreaPrivate::setViewMode(), and showEvent().
 {
     Q_D(QTabBar);
     if (d->dragInProgress && d->pressedIndex != -1)
         return;
     int oldIndex = d->currentIndex;
     if (d->validIndex(index) && d->currentIndex != index) {
         d->currentIndex = index;
         update();
         d->makeVisible(index);
         d->tabList[index].lastTab = oldIndex;
         if (oldIndex >= 0 && oldIndex < count())
             d->layoutTab(oldIndex);
         d->layoutTab(index);
 #ifndef QT_NO_ACCESSIBILITY
         if (QAccessible::isActive()) {
             QAccessible::updateAccessibility(this, oldIndex + 1, QAccessible::Selection);
             QAccessible::updateAccessibility(this, index + 1, QAccessible::Focus);
             QAccessible::updateAccessibility(this, index + 1, QAccessible::Selection);
         }
 #endif
 #ifdef QT3_SUPPORT
         emit selected(index);
 #endif
         emit currentChanged(index);
     }
 }
setDocumentMode()
void QTabBar::setDocumentMode (bool set)
Definition at line 2325 of file qtabbar.cpp.
Referenced by QMainWindowLayout::getTabBar(), QMdiAreaPrivate::refreshTabBar(), QMainWindowLayout::setDocumentMode(), and QMdiAreaPrivate::setViewMode().
 {
     Q_D(QTabBar);
     d->documentMode = enabled;
     d->updateMacBorderMetrics();
 }
setDrawBase()
void QTabBar::setDrawBase (bool drawTheBase)
Definition at line 800 of file qtabbar.cpp.
Referenced by QMainWindowLayout::getTabBar(), QTabWidgetPrivate::init(), and QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(QTabBar);
     if (d->drawBase == drawBase)
         return;
     d->drawBase = drawBase;
     update();
 }
setElideMode()
void QTabBar::setElideMode (Qt::TextElideMode mode)
Definition at line 2077 of file qtabbar.cpp.
Referenced by QMainWindowLayout::getTabBar().
 {
     Q_D(QTabBar);
     d->elideMode = mode;
     d->elideModeSetByUser = true;
     d->refresh();
 }
setExpanding()
void QTabBar::setExpanding (bool enabled)
Definition at line 2271 of file qtabbar.cpp.
Referenced by QMainWindowTabBar::QMainWindowTabBar(), and QTabWidget::setTabBar().
 {
     Q_D(QTabBar);
     if (d->expanding == enabled)
         return;
     d->expanding = enabled;
     d->layoutTabs();
 }
setIconSize()
void QTabBar::setIconSize (const QSize & size)
Definition at line 1291 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     d->iconSize = size;
     d->layoutDirty = true;
     update();
     updateGeometry();
 }
setMovable()
void QTabBar::setMovable (bool movable)
Definition at line 2299 of file qtabbar.cpp.
Referenced by QMdiAreaPrivate::refreshTabBar(), QTabWidget::setMovable(), and QMdiAreaPrivate::setViewMode().
 {
     Q_D(QTabBar);
     d->movable = movable;
 }
setSelectionBehaviorOnRemove()
void QTabBar::setSelectionBehaviorOnRemove (QTabBar::SelectionBehavior behavior)
Definition at line 2246 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     d->selectionBehaviorOnRemove = behavior;
 }
setShape()
void QTabBar::setShape (Shape shape)
Definition at line 778 of file qtabbar.cpp.
Referenced by QMdiAreaPrivate::refreshTabBar(), QDockAreaLayoutInfo::setTabBarShape(), QMdiAreaPrivate::setViewMode(), and QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(QTabBar);
     if (d->shape == shape)
         return;
     d->shape = shape;
     d->refresh();
 }
setTabButton()
void QTabBar::setTabButton (int index, ButtonPosition position, QWidget * widget)
Sets widget on the tab index.
The widget is placed on the left or right hand side depending upon the position.
Since
4.5
Any previously set widget in position is hidden.
The tab bar will take ownership of the widget and so all widgets set here will be deleted by the tab bar when it is destroyed unless you separately reparent the widget after setting some other widget (or 0).
See also
tabsClosable()
Definition at line 2346 of file qtabbar.cpp.
Referenced by insertTab(), and setTabsClosable().
 {
     Q_D(QTabBar);
     if (index < 0 || index >= d->tabList.count())
         return;
     if (widget) {
         widget->setParent(this);
         // make sure our left and right widgets stay on top
         widget->lower();
         widget->show();
     }
     if (position == LeftSide) {
         if (d->tabList[index].leftWidget)
             d->tabList[index].leftWidget->hide();
         d->tabList[index].leftWidget = widget;
     } else {
         if (d->tabList[index].rightWidget)
             d->tabList[index].rightWidget->hide();
         d->tabList[index].rightWidget = widget;
     }
     d->layoutTabs();
     d->refresh();
     update();
 }
setTabData()
void QTabBar::setTabData (int index, const QVariant & data)
Sets the data of the tab at position index to data.
Definition at line 1156 of file qtabbar.cpp.
Referenced by QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index))
         tab->data = data;
 }
setTabEnabled()
void QTabBar::setTabEnabled (int index, bool enabled)
If enabled is true then the tab at position index is enabled; otherwise the item at position index is disabled.
Definition at line 989 of file qtabbar.cpp.
Referenced by QMdiAreaPrivate::_q_currentTabChanged().
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index)) {
         tab->enabled = enabled;
 #ifndef QT_NO_SHORTCUT
         setShortcutEnabled(tab->shortcutId, enabled);
 #endif
         update();
         if (!enabled && index == d->currentIndex)
             setCurrentIndex(d->validIndex(index+1)?index+1:0);
         else if (enabled && !d->validIndex(d->currentIndex))
             setCurrentIndex(index);
     }
 }
setTabIcon()
void QTabBar::setTabIcon (int index, const QIcon & icon)
Sets the icon of the tab at position index to icon.
Definition at line 1080 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index)) {
         bool simpleIconChange = (!icon.isNull() && !tab->icon.isNull());
         tab->icon = icon;
         if (simpleIconChange)
             update(tabRect(index));
         else
             d->refresh();
     }
 }
setTabsClosable()
void QTabBar::setTabsClosable (bool closable)
Definition at line 2158 of file qtabbar.cpp.
Referenced by QMdiAreaPrivate::refreshTabBar(), QTabWidget::setTabsClosable(), and QMdiAreaPrivate::setViewMode().
 {
     Q_D(QTabBar);
     if (d->closeButtonOnTabs == closable)
         return;
     d->closeButtonOnTabs = closable;
     ButtonPosition closeSide = (ButtonPosition)style()->styleHint(QStyle::SH_TabBar_CloseButtonPosition, 0, this);
     if (!closable) {
         for (int i = 0; i < d->tabList.count(); ++i) {
             if (closeSide == LeftSide && d->tabList[i].leftWidget) {
                 d->tabList[i].leftWidget->deleteLater();
                 d->tabList[i].leftWidget = 0;
             }
             if (closeSide == RightSide && d->tabList[i].rightWidget) {
                 d->tabList[i].rightWidget->deleteLater();
                 d->tabList[i].rightWidget = 0;
             }
         }
     } else {
         bool newButtons = false;
         for (int i = 0; i < d->tabList.count(); ++i) {
             if (tabButton(i, closeSide))
                 continue;
             newButtons = true;
             QAbstractButton *closeButton = new CloseButton(this);
             connect(closeButton, SIGNAL(clicked()), this, SLOT(_q_closeTab()));
             setTabButton(i, closeSide, closeButton);
         }
         if (newButtons)
             d->layoutTabs();
     }
     update();
 }
setTabText()
void QTabBar::setTabText (int index, const QString & text)
Sets the text of the tab at position index to text.
Definition at line 1021 of file qtabbar.cpp.
Referenced by QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index)) {
         tab->text = text;
 #ifndef QT_NO_SHORTCUT
         releaseShortcut(tab->shortcutId);
         tab->shortcutId = grabShortcut(QKeySequence::mnemonic(text));
         setShortcutEnabled(tab->shortcutId, tab->enabled);
 #endif
         d->refresh();
     }
 }
setTabTextColor()
void QTabBar::setTabTextColor (int index, const QColor & color)
Sets the color of the text in the tab with the given index to the specified color.
If an invalid color is specified, the tab will use the QTabBar foreground role instead.
See also
tabTextColor()
Definition at line 1056 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index)) {
         tab->textColor = color;
         update(tabRect(index));
     }
 }
setTabToolTip()
void QTabBar::setTabToolTip (int index, const QString & tip)
Sets the tool tip of the tab at position index to tip.
Definition at line 1097 of file qtabbar.cpp.
Referenced by QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index))
         tab->toolTip = tip;
 }
setTabWhatsThis()
void QTabBar::setTabWhatsThis (int index, const QString & text)
Sets the What's This help text of the tab at position index to text.
Since
4.1
Definition at line 1127 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     if (QTabBarPrivate::Tab *tab = d->at(index))
         tab->whatsThis = text;
 }
setUsesScrollButtons()
void QTabBar::setUsesScrollButtons (bool useButtons)
Definition at line 2106 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     d->useScrollButtonsSetByUser = true;
     if (d->useScrollButtons == useButtons)
         return;
     d->useScrollButtons = useButtons;
     d->refresh();
 }
shape()
Shape QTabBar::shape () const
Referenced by QMainWindowTabBar::event(), setShape(), QTabBarPrivate::slide(), QMdiAreaPrivate::updateTabBarGeometry(), and ~QTabBar().
showEvent()
void QTabBar::showEvent (QShowEvent *) protected virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1470 of file qtabbar.cpp.
sizeHint()
QSize QTabBar::sizeHint () const virtual
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 1317 of file qtabbar.cpp.
Referenced by QMainWindowTabBar::event(), minimumSizeHint(), QDockAreaLayoutInfo::tabBarSizeHint(), and QMdiAreaPrivate::updateTabBarGeometry().
tabAt()
int QTabBar::tabAt (const QPoint & position) const
Since
4.3 Returns the index of the tab that covers position or -1 if no tab covers position;
Definition at line 1203 of file qtabbar.cpp.
Referenced by event(), and mouseMoveEvent().
 {
     Q_D(const QTabBar);
     if (d->validIndex(d->currentIndex)
         && tabRect(d->currentIndex).contains(position)) {
         return d->currentIndex;
     }
     const int max = d->tabList.size();
     for (int i = 0; i < max; ++i) {
         if (tabRect(i).contains(position)) {
             return i;
         }
     }
     return -1;
 }
tabButton()
QWidget * QTabBar::tabButton (int index, ButtonPosition position) const
Returns the widget set a tab index and position or 0 if one is not set.
Definition at line 2375 of file qtabbar.cpp.
Referenced by setTabsClosable().
 {
     Q_D(const QTabBar);
     if (index < 0 || index >= d->tabList.count())
         return 0;
     if (position == LeftSide)
         return d->tabList.at(index).leftWidget;
     else
         return d->tabList.at(index).rightWidget;
 }
tabCloseRequested
void QTabBar::tabCloseRequested (int index) signal
This signal is emitted when the close button on a tab is clicked.
Since
4.5
The index is the index that should be removed.
See also
setTabsClosable()
Referenced by QAccessibleTabBar::doAction().
tabData()
QVariant QTabBar::tabData (int index) const
Returns the data of the tab at position index, or a null variant if index is out of range.
Definition at line 1167 of file qtabbar.cpp.
Referenced by QDockAreaLayoutInfo::currentTabId(), QDockAreaLayoutInfo::setCurrentTabId(), and QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->data;
     return QVariant();
 }
tabIcon()
QIcon QTabBar::tabIcon (int index) const
Returns the icon of the tab at position index, or a null icon if index is out of range.
Definition at line 1069 of file qtabbar.cpp.
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->icon;
     return QIcon();
 }
tabInserted()
void QTabBar::tabInserted (int index) protected virtual
This virtual handler is called after a new tab was added or inserted at position index.
See also
tabRemoved()
Definition at line 1442 of file qtabbar.cpp.
Referenced by insertTab().
 {
     Q_UNUSED(index)
 }
tabLayoutChange()
void QTabBar::tabLayoutChange () protected virtual
This virtual handler is called whenever the tab layout changes.
See also
tabRect()em>Reimplemented Function
Definition at line 1463 of file qtabbar.cpp.
Referenced by moveTab().
tabMoved
void QTabBar::tabMoved (int from, int to) signal
This signal is emitted when the tab has moved the tab at index position from to index position to.
Since
4.5
note: QTabWidget will automatically move the page when this signal is emitted from its tab bar.
See also
moveTab()
Referenced by moveTab().
tabRect()
QRect QTabBar::tabRect (int index) const
Returns the visual rectangle of the tab at position index, or a null rectangle if index is out of range.
Definition at line 1179 of file qtabbar.cpp.
Referenced by event(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), paintEvent(), QAccessibleTabBar::rect(), setTabIcon(), setTabTextColor(), and tabAt().
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index)) {
         if (d->layoutDirty)
             const_cast<QTabBarPrivate*>(d)->layoutTabs();
         QRect r = tab->rect;
         if (verticalTabs(d->shape))
             r.translate(0, -d->scrollOffset);
         else
             r.translate(-d->scrollOffset, 0);
         if (!verticalTabs(d->shape))
             r = QStyle::visualRect(layoutDirection(), rect(), r);
         return r;
     }
     return QRect();
 }
tabRemoved()
void QTabBar::tabRemoved (int index) protected virtual
This virtual handler is called after a tab was removed from position index.
See also
tabInserted()
Definition at line 1453 of file qtabbar.cpp.
Referenced by removeTab().
 {
     Q_UNUSED(index)
 }
tabsClosable()
bool QTabBar::tabsClosable () const
Referenced by setUsesScrollButtons().
tabSizeHint()
QSize QTabBar::tabSizeHint (int index) const protected virtual
Returns the size hint for the tab at position index.
Definition at line 1388 of file qtabbar.cpp.
 {
     //Note: this must match with the computations in QCommonStylePrivate::tabLayout
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index)) {
         QStyleOptionTabV3 opt;
         initStyleOption(&opt, index);
         opt.text = d->tabList.at(index).text;
         QSize iconSize = tab->icon.isNull() ? QSize(0, 0) : opt.iconSize;
         int hframe = style()->pixelMetric(QStyle::PM_TabBarTabHSpace, &opt, this);
         int vframe = style()->pixelMetric(QStyle::PM_TabBarTabVSpace, &opt, this);
         const QFontMetrics fm = fontMetrics();
         int maxWidgetHeight = qMax(opt.leftButtonSize.height(), opt.rightButtonSize.height());
         int maxWidgetWidth = qMax(opt.leftButtonSize.width(), opt.rightButtonSize.width());
         int widgetWidth = 0;
         int widgetHeight = 0;
         int padding = 0;
         if (!opt.leftButtonSize.isEmpty()) {
             padding += 4;
             widgetWidth += opt.leftButtonSize.width();
             widgetHeight += opt.leftButtonSize.height();
         }
         if (!opt.rightButtonSize.isEmpty()) {
             padding += 4;
             widgetWidth += opt.rightButtonSize.width();
             widgetHeight += opt.rightButtonSize.height();
         }
         if (!opt.icon.isNull())
             padding += 4;
         QSize csz;
         if (verticalTabs(d->shape)) {
             csz = QSize( qMax(maxWidgetWidth, qMax(fm.height(), iconSize.height())) + vframe,
                     fm.size(Qt::TextShowMnemonic, tab->text).width() + iconSize.width() + hframe + widgetHeight + padding);
         } else {
             csz = QSize(fm.size(Qt::TextShowMnemonic, tab->text).width() + iconSize.width() + hframe
                   + widgetWidth + padding,
                   qMax(maxWidgetHeight, qMax(fm.height(), iconSize.height())) + vframe);
         }
         QSize retSize = style()->sizeFromContents(QStyle::CT_TabBarTab, &opt, csz, this);
         return retSize;
     }
     return QSize();
 }
tabText()
QString QTabBar::tabText (int index) const
Returns the text of the tab at position index, or an empty string if index is out of range.
Definition at line 1010 of file qtabbar.cpp.
Referenced by QDockAreaLayoutInfo::updateTabBar().
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->text;
     return QString();
 }
tabTextColor()
QColor QTabBar::tabTextColor (int index) const
Returns the text color of the tab with the given index, or a invalid color if index is out of range.
See also
setTabTextColor()
Definition at line 1041 of file qtabbar.cpp.
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->textColor;
     return QColor();
 }
tabToolTip()
QString QTabBar::tabToolTip (int index) const
Returns the tool tip of the tab at position index, or an empty string if index is out of range.
Definition at line 1108 of file qtabbar.cpp.
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->toolTip;
     return QString();
 }
tabWhatsThis()
QString QTabBar::tabWhatsThis (int index) const
Returns the What's This help text of the tab at position index, or an empty string if index is out of range.
Since
4.1
Definition at line 1143 of file qtabbar.cpp.
 {
     Q_D(const QTabBar);
     if (const QTabBarPrivate::Tab *tab = d->at(index))
         return tab->whatsThis;
     return QString();
 }
usesScrollButtons()
bool QTabBar::usesScrollButtons () const
Referenced by setElideMode().
wheelEvent()
void QTabBar::wheelEvent (QWheelEvent * event) protected virtual
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
If you reimplement this handler, it is very important that you ignore() the event if you do not handle it, so that the widget's parent can interpret it.
The default implementation ignores the event.
See also
QWheelEvent::ignore(), QWheelEvent::accept(), event(), QWheelEvent
Reimplemented from QWidget.
Definition at line 2018 of file qtabbar.cpp.
 {
     Q_D(QTabBar);
     int offset = event->delta() > 0 ? -1 : 1;
     d->setCurrentNextEnabledIndex(offset);
     QWidget::wheelEvent(event);
 }
Friends and Related Functions
QAccessibleTabBar
friend class QAccessibleTabBar friend
Definition at line 212 of file qtabbar.h.
Properties
count
int QTabBar::count private
the number of tabs in the tab bar
em>Reimplemented Function
Definition at line 66 of file qtabbar.h.
Referenced by QMainWindowLayout::applyState(), QAccessibleTabBar::childCount(), QDockAreaLayoutInfo::setCurrentTabId(), QAccessibleTabBar::state(), QAccessibleTabBar::text(), and QDockAreaLayoutInfo::updateTabBar().
currentIndex
int QTabBar::currentIndex private
the index of the tab bar's visible tab
The current index is -1 if there is no current tab.
Definition at line 65 of file qtabbar.h.
Referenced by QDockAreaLayoutInfo::currentTabId(), QAccessibleTabBar::selection(), and QAccessibleTabBar::state().
documentMode
bool QTabBar::documentMode private
Whether or not the tab bar is rendered in a mode suitable for the main window.
Since
4.5
This property is used as a hint for styles to draw the tabs in a different way then they would normally look in a tab widget. On Mac OS X this will look similar to the tabs in Safari or Leopard's Terminal.app.
See also
QTabWidget::documentMode
Definition at line 75 of file qtabbar.h.
Referenced by QTabBarPrivate::initStyleBaseOption().
drawBase
bool QTabBar::drawBase private
defines whether or not tab bar should draw its base.
If true then QTabBar draws a base in relation to the styles overlab. Otherwise only the tabs are drawn.
See also
QStyle::pixelMetric() QStyle::PM_TabBarBaseOverlap QStyleOptionTabBarBaseV2
Definition at line 67 of file qtabbar.h.
elideMode
Qt::TextElideMode QTabBar::elideMode private
how to elide text in the tab bar
Since
4.2
This property controls how items are elided when there is not enough space to show them for a given tab bar size.
By default the value is style dependent.
See also
QTabWidget::elideMode usesScrollButtons QStyle::SH_TabBar_ElideMode
Definition at line 69 of file qtabbar.h.
expanding
bool QTabBar::expanding private
When expanding is true QTabBar will expand the tabs to use the empty space.
Since
4.5
By default the value is true.
See also
QTabWidget::documentMode
Definition at line 73 of file qtabbar.h.
iconSize
QSize QTabBar::iconSize private
The size for icons in the tab bar.
Since
4.1
The default value is style-dependent. iconSize is a maximum size; icons that are smaller are not scaled up.
See also
QTabWidget::iconSize
Definition at line 68 of file qtabbar.h.
movable
QTabBar::movable private
This property holds whether the user can move the tabs within the tabbar area.
Since
4.5
By default, this property is false;
Definition at line 74 of file qtabbar.h.
Referenced by QTabBarPrivate::moveTabFinished(), and setMovable().
selectionBehaviorOnRemove
QTabBar::SelectionBehavior QTabBar::selectionBehaviorOnRemove private
What tab should be set as current when removeTab is called if the removed tab is also the current tab.
Since
4.5
By default the value is SelectRightTab.
See also
removeTab()
Definition at line 72 of file qtabbar.h.
shape
QTabBar::Shape QTabBar::shape private
the shape of the tabs in the tab bar
Possible values for this property are described by the Shape enum.
Definition at line 64 of file qtabbar.h.
Referenced by QTabBarPrivate::initStyleBaseOption().
tabsClosable
bool QTabBar::tabsClosable private
Whether or not a tab bar should place close buttons on each tab.
Since
4.5
When tabsClosable is set to true a close button will appear on the tab on either the left or right hand side depending upon the style. When the button is clicked the tab the signal tabCloseRequested will be emitted.
By default the value is false.
See also
setTabButton(), tabRemoved()
Definition at line 71 of file qtabbar.h.
Referenced by QAccessibleTabBar::actionText(), QTabWidget::setTabPosition(), and QAccessibleTabBar::userActionCount().
usesScrollButtons
bool QTabBar::usesScrollButtons private
Whether or not a tab bar should use buttons to scroll tabs when it has many tabs.
Since
4.2
When there are too many tabs in a tab bar for its size, the tab bar can either choose to expand its size or to add buttons that allow you to scroll through the tabs.
By default the value is style dependant.
See also
elideMode QTabWidget::usesScrollButtons QStyle::SH_TabBar_PreferNoArrows
Definition at line 70 of file qtabbar.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qtabbar.h
/src/gui/widgets/qtabbar.cpp