Qt 4.8: QCss::StyleSelector Class Reference
QCss::StyleSelector Class Reference abstract
#include <qcssparser_p.h>
Classes
union NodePtr
Public Functions
virtual QString attribute (NodePtr node, const QString &name) const =0
QVector< Declaration > declarationsForNode (NodePtr node, const char *extraPseudo=0)
virtual NodePtr duplicateNode (NodePtr node) const =0
virtual void freeNode (NodePtr node) const =0
virtual bool hasAttributes (NodePtr node) const =0
virtual bool isNullNode (NodePtr node) const =0
virtual QStringList nodeIds (NodePtr node) const
virtual bool nodeNameEquals (NodePtr node, const QString &nodeName) const
virtual QStringList nodeNames (NodePtr node) const =0
virtual NodePtr parentNode (NodePtr node) const =0
virtual NodePtr previousSiblingNode (NodePtr node) const =0
QVector< StyleRule > styleRulesForNode (NodePtr node)
StyleSelector ()
virtual ~StyleSelector ()
Public Variables
QString medium
Qt::CaseSensitivity nameCaseSensitivity
QVector< StyleSheet > styleSheets
Private Functions
bool basicSelectorMatches (const BasicSelector &rule, NodePtr node)
void matchRule (NodePtr node, const StyleRule &rules, StyleSheetOrigin origin, int depth, QMap< uint, StyleRule > *weightedRules)
bool selectorMatches (const Selector &rule, NodePtr node)
Detailed Description
Definition at line 650 of file qcssparser_p.h.
Constructors and Destructors
StyleSelector()
QCss::StyleSelector::StyleSelector () inline
Definition at line 653 of file qcssparser_p.h.
 : nameCaseSensitivity(Qt::CaseSensitive)  {}
~StyleSelector()
StyleSelector::~StyleSelector () virtual
Definition at line 1790 of file qcssparser.cpp.
 {
 }
Functions
attribute()
virtual QString QCss::StyleSelector::attribute (NodePtr node, const QString & name) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
basicSelectorMatches()
bool StyleSelector::basicSelectorMatches (const BasicSelector & rule, NodePtr node) private
Definition at line 1859 of file qcssparser.cpp.
 {
     if (!sel.attributeSelectors.isEmpty()) {
         if (!hasAttributes(node))
             return false;
         for (int i = 0; i < sel.attributeSelectors.count(); ++i) {
             const QCss::AttributeSelector &a = sel.attributeSelectors.at(i);
             const QString attrValue = attribute(node, a.name);
             if (attrValue.isNull())
                 return false;
             if (a.valueMatchCriterium == QCss::AttributeSelector::MatchContains) {
                 QStringList lst = attrValue.split(QLatin1Char(' '));
                 if (!lst.contains(a.value))
                     return false;
             } else if (
                 (a.valueMatchCriterium == QCss::AttributeSelector::MatchEqual
                  && attrValue != a.value)
                 ||
                 (a.valueMatchCriterium == QCss::AttributeSelector::MatchBeginsWith
                  && !attrValue.startsWith(a.value))
                )
                 return false;
         }
     }
     if (!sel.elementName.isEmpty()
         && !nodeNameEquals(node, sel.elementName))
             return false;
     if (!sel.ids.isEmpty()
         && sel.ids != nodeIds(node))
             return false;
     return true;
 }
declarationsForNode()
QVector< Declaration > StyleSelector::declarationsForNode (NodePtr node, const char * extraPseudo = 0)
Definition at line 1982 of file qcssparser.cpp.
Referenced by cssStyleLookup(), QTextHtmlParser::declarationsForNode(), and parseStopNode().
 {
     QVector<Declaration> decls;
     QVector<StyleRule> rules = styleRulesForNode(node);
     for (int i = 0; i < rules.count(); i++) {
         const Selector& selector = rules.at(i).selectors.at(0);
         const QString pseudoElement = selector.pseudoElement();
         if (extraPseudo && pseudoElement == QLatin1String(extraPseudo)) {
             decls += rules.at(i).declarations;
             continue;
         }
         if (!pseudoElement.isEmpty()) // skip rules with pseudo elements
             continue;
         quint64 pseudoClass = selector.pseudoClass();
         if (pseudoClass == PseudoClass_Enabled || pseudoClass == PseudoClass_Unspecified)
             decls += rules.at(i).declarations;
     }
     return decls;
 }
duplicateNode()
virtual NodePtr QCss::StyleSelector::duplicateNode (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
freeNode()
virtual void QCss::StyleSelector::freeNode (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
hasAttributes()
virtual bool QCss::StyleSelector::hasAttributes (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
isNullNode()
virtual bool QCss::StyleSelector::isNullNode (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
matchRule()
void StyleSelector::matchRule (NodePtr node, const StyleRule & rules, StyleSheetOrigin origin, int depth, QMap< uint, StyleRule > * weightedRules) private
Definition at line 1899 of file qcssparser.cpp.
 {
     for (int j = 0; j < rule.selectors.count(); ++j) {
         const Selector& selector = rule.selectors.at(j);
         if (selectorMatches(selector, node)) {
             uint weight = rule.order
                         + selector.specificity() *0x100
                         + (uint(origin) + depth)*0x100000;
             StyleRule newRule = rule;
             if(rule.selectors.count() > 1) {
                 newRule.selectors.resize(1);
                 newRule.selectors[0] = selector;
             }
             //We might have rules with the same weight if they came from a rule with several selectors
             weightedRules->insertMulti(weight, newRule);
         }
     }
 }
nodeIds()
QStringList StyleSelector::nodeIds (NodePtr node) const virtual
Reimplemented in QStyleSheetStyleSelector, and QSvgStyleSelector.
Definition at line 1799 of file qcssparser.cpp.
 {
     return QStringList(attribute(node, QLatin1String("id")));
 }
nodeNameEquals()
bool StyleSelector::nodeNameEquals (NodePtr node, const QString & nodeName) const virtual
Reimplemented in QStyleSheetStyleSelector, and QSvgStyleSelector.
Definition at line 1794 of file qcssparser.cpp.
 {
     return nodeNames(node).contains(nodeName, nameCaseSensitivity);
 }
nodeNames()
virtual QStringList QCss::StyleSelector::nodeNames (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
parentNode()
virtual NodePtr QCss::StyleSelector::parentNode (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
previousSiblingNode()
virtual NodePtr QCss::StyleSelector::previousSiblingNode (NodePtr node) const pure virtual
Implemented in QTextHtmlStyleSelector, QStyleSheetStyleSelector, and QSvgStyleSelector.
selectorMatches()
bool StyleSelector::selectorMatches (const Selector & rule, NodePtr node) private
Definition at line 1804 of file qcssparser.cpp.
 {
     if (selector.basicSelectors.isEmpty())
         return false;
     if (selector.basicSelectors.at(0).relationToNext == BasicSelector::NoRelation) {
         if (selector.basicSelectors.count() != 1)
             return false;
         return basicSelectorMatches(selector.basicSelectors.at(0), node);
     }
     if (selector.basicSelectors.count() <= 1)
         return false;
     int i = selector.basicSelectors.count() - 1;
     node = duplicateNode(node);
     bool match = true;
     BasicSelector sel = selector.basicSelectors.at(i);
     do {
         match = basicSelectorMatches(sel, node);
         if (!match) {
             if (sel.relationToNext == BasicSelector::MatchNextSelectorIfParent
                 || i == selector.basicSelectors.count() - 1) // first element must always match!
                 break;
         }
         if (match || sel.relationToNext != BasicSelector::MatchNextSelectorIfAncestor)
             --i;
         if (i < 0)
             break;
         sel = selector.basicSelectors.at(i);
         if (sel.relationToNext == BasicSelector::MatchNextSelectorIfAncestor
             || sel.relationToNext == BasicSelector::MatchNextSelectorIfParent) {
             NodePtr nextParent = parentNode(node);
             freeNode(node);
             node = nextParent;
        } else if (sel.relationToNext == BasicSelector::MatchNextSelectorIfPreceeds) {
             NodePtr previousSibling = previousSiblingNode(node);
             freeNode(node);
             node = previousSibling;
        }
         if (isNullNode(node)) {
             match = false;
             break;
         }
    } while (i >= 0 && (match || sel.relationToNext == BasicSelector::MatchNextSelectorIfAncestor));
     freeNode(node);
     return match;
 }
styleRulesForNode()
QVector< StyleRule > StyleSelector::styleRulesForNode (NodePtr node)
Definition at line 1921 of file qcssparser.cpp.
 {
     QVector<StyleRule> rules;
     if (styleSheets.isEmpty())
         return rules;
     QMap<uint, StyleRule> weightedRules; // (spec, rule) that will be sorted below
     //prune using indexed stylesheet
     for (int sheetIdx = 0; sheetIdx < styleSheets.count(); ++sheetIdx) {
         const StyleSheet &styleSheet = styleSheets.at(sheetIdx);
         for (int i = 0; i < styleSheet.styleRules.count(); ++i) {
             matchRule(node, styleSheet.styleRules.at(i), styleSheet.origin, styleSheet.depth, &weightedRules);
         }
         if (!styleSheet.idIndex.isEmpty()) {
             QStringList ids = nodeIds(node);
             for (int i = 0; i < ids.count(); i++) {
                 const QString &key = ids.at(i);
                 QMultiHash<QString, StyleRule>::const_iterator it = styleSheet.idIndex.constFind(key);
                 while (it != styleSheet.idIndex.constEnd() && it.key() == key) {
                     matchRule(node, it.value(), styleSheet.origin, styleSheet.depth, &weightedRules);
                     ++it;
                 }
             }
         }
         if (!styleSheet.nameIndex.isEmpty()) {
             QStringList names = nodeNames(node);
             for (int i = 0; i < names.count(); i++) {
                 QString name = names.at(i);
                 if (nameCaseSensitivity == Qt::CaseInsensitive)
                     name = name.toLower();
                 QMultiHash<QString, StyleRule>::const_iterator it = styleSheet.nameIndex.constFind(name);
                 while (it != styleSheet.nameIndex.constEnd() && it.key() == name) {
                     matchRule(node, it.value(), styleSheet.origin, styleSheet.depth, &weightedRules);
                     ++it;
                 }
             }
         }
         if (!medium.isEmpty()) {
             for (int i = 0; i < styleSheet.mediaRules.count(); ++i) {
                 if (styleSheet.mediaRules.at(i).media.contains(medium, Qt::CaseInsensitive)) {
                     for (int j = 0; j < styleSheet.mediaRules.at(i).styleRules.count(); ++j) {
                         matchRule(node, styleSheet.mediaRules.at(i).styleRules.at(j), styleSheet.origin,
                                styleSheet.depth, &weightedRules);
                     }
                 }
             }
         }
     }
     rules.reserve(weightedRules.count());
     QMap<uint, StyleRule>::const_iterator it = weightedRules.constBegin();
     for ( ; it != weightedRules.constEnd() ; ++it)
         rules += *it;
     return rules;
 }
Properties
medium
QString QCss::StyleSelector::medium
Definition at line 676 of file qcssparser_p.h.
Referenced by QTextHtmlParser::declarationsForNode().
nameCaseSensitivity
Qt::CaseSensitivity QCss::StyleSelector::nameCaseSensitivity
Definition at line 677 of file qcssparser_p.h.
styleSheets
QVector<StyleSheet> QCss::StyleSelector::styleSheets
Definition at line 675 of file qcssparser_p.h.
Referenced by QSvgHandler::characters(), QTextHtmlParser::declarationsForNode(), and QSvgHandler::processingInstruction().
The documentation for this class was generated from the following files:
/src/gui/text/qcssparser_p.h
/src/gui/text/qcssparser.cpp