Qt 4.8: QDirectFbConvenience Class Reference
QDirectFbConvenience Class Reference
#include <qdirectfbconvenience.h>
Static Public Functions
static int colorDepthForSurface (const DFBSurfacePixelFormat format)
static IDirectFBDisplayLayer * dfbDisplayLayer (int display=DLID_PRIMARY)
static IDirectFB * dfbInterface ()
static IDirectFBSurface * dfbSurfaceForPlatformPixmap (QPixmapData *)
static QEvent::Type eventType (DFBWindowEventType type)
static QImage::Format imageFormatFromSurfaceFormat (const DFBSurfacePixelFormat format, const DFBSurfaceCapabilities caps)
static Qt::KeyboardModifiers keyboardModifiers (DFBInputDeviceModifierMask mask)
static QDirectFbKeyMap * keyMap ()
static Qt::MouseButton mouseButton (DFBInputDeviceButtonIdentifier identifier)
static Qt::MouseButtons mouseButtons (DFBInputDeviceButtonMask mask)
static bool pixelFomatHasAlpha (const DFBSurfacePixelFormat format)
Static Private Attributes
static QDirectFbKeyMap * dfbKeymap = 0
Friends
class QDirectFbIntegration
Detailed Description
Definition at line 64 of file qdirectfbconvenience.h.
Functions
colorDepthForSurface()
int QDirectFbConvenience::colorDepthForSurface (const DFBSurfacePixelFormat format) static
Definition at line 109 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbScreen::QDirectFbScreen().
 {
     return ((0x1f << 7) & format) >> 7;
 }
dfbDisplayLayer()
IDirectFBDisplayLayer * QDirectFbConvenience::dfbDisplayLayer (int display = DLID_PRIMARY) static
Definition at line 66 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbInput::handleMouseEvents().
 {
     IDirectFBDisplayLayer *layer;
     DFBResult result = QDirectFbConvenience::dfbInterface()->GetDisplayLayer(QDirectFbConvenience::dfbInterface(),display,&layer);
     if (result != DFB_OK)
         DirectFBErrorFatal("QDirectFbConvenience: "
                            "Unable to get primary display layer!", result);
     return layer;
 }
dfbInterface()
IDirectFB * QDirectFbConvenience::dfbInterface () static
Definition at line 53 of file qdirectfbconvenience.cpp.
Referenced by dfbDisplayLayer(), QDirectFbBlitterPlatformPixmap::fromDataBufferDescription(), QDirectFbIntegration::initializeDirectFB(), QDirectFbBlitter::QDirectFbBlitter(), and QDirectFbWindow::setVisible().
 {
     static IDirectFB *dfb = 0;
     if (!dfb) {
         DFBResult result = DirectFBCreate(&dfb);
         if (result != DFB_OK) {
             DirectFBErrorFatal("QDirectFBConvenience: error creating DirectFB interface", result);
             return 0;
         }
     }
     return dfb;
 }
dfbSurfaceForPlatformPixmap()
IDirectFBSurface * QDirectFbConvenience::dfbSurfaceForPlatformPixmap (QPixmapData * handle) static
This is borrowing the reference of the QDirectFbBlitter. You may not store this pointer as a class member but must only use it locally.
Definition at line 118 of file qdirectfbconvenience.cpp.
Referenced by QDirectFBCursor::changeCursor().
 {
     QBlittablePixmapData *blittablePmData = static_cast<QBlittablePixmapData *>(handle);
     if (blittablePmData) {
         QBlittable *blittable = blittablePmData->blittable();
         QDirectFbBlitter *dfbBlitter = static_cast<QDirectFbBlitter *>(blittable);
         return dfbBlitter->m_surface.data();
     }
     return 0;
 }
eventType()
QEvent::Type QDirectFbConvenience::eventType (DFBWindowEventType type) static
Definition at line 181 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbInput::handleKeyEvents().
 {
     switch(type) {
     case DWET_BUTTONDOWN:
         return QEvent::MouseButtonPress;
     case DWET_BUTTONUP:
         return QEvent::MouseButtonRelease;
     case DWET_MOTION:
         return QEvent::MouseMove;
     case DWET_WHEEL:
         return QEvent::Wheel;
     case DWET_KEYDOWN:
         return QEvent::KeyPress;
     case DWET_KEYUP:
         return QEvent::KeyRelease;
     default:
         return QEvent::None;
     }
 }
imageFormatFromSurfaceFormat()
QImage::Format QDirectFbConvenience::imageFormatFromSurfaceFormat (const DFBSurfacePixelFormat format, const DFBSurfaceCapabilities caps) static
Definition at line 76 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbBlitter::doLock(), and QDirectFbScreen::QDirectFbScreen().
 {
     switch (format) {
     case DSPF_LUT8:
         return QImage::Format_Indexed8;
     case DSPF_RGB24:
         return QImage::Format_RGB888;
     case DSPF_ARGB4444:
         return QImage::Format_ARGB4444_Premultiplied;
     case DSPF_RGB444:
         return QImage::Format_RGB444;
     case DSPF_RGB555:
     case DSPF_ARGB1555:
         return QImage::Format_RGB555;
     case DSPF_RGB16:
         return QImage::Format_RGB16;
     case DSPF_ARGB6666:
         return QImage::Format_ARGB6666_Premultiplied;
     case DSPF_RGB18:
         return QImage::Format_RGB666;
     case DSPF_RGB32:
         return QImage::Format_RGB32;
     case DSPF_ARGB: {
             if (caps & DSCAPS_PREMULTIPLIED)
                     return QImage::Format_ARGB32_Premultiplied;
             else return QImage::Format_ARGB32; }
     default:
         break;
     }
     return QImage::Format_Invalid;
 }
keyboardModifiers()
Qt::KeyboardModifiers QDirectFbConvenience::keyboardModifiers (DFBInputDeviceModifierMask mask) static
Definition at line 159 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbInput::handleKeyEvents().
 {
     Qt::KeyboardModifiers modifiers = Qt::NoModifier;
     if (mask & DIMM_SHIFT) {
         modifiers |= Qt::ShiftModifier;
     }
     if (mask & DIMM_ALT) {
         modifiers |= Qt::AltModifier;
     }
     if (mask & DIMM_ALTGR) {
         modifiers |= Qt::MetaModifier;
     }
     if (mask & DIMM_CONTROL) {
         modifiers |= Qt::ControlModifier;
     }
     if (mask & DIMM_META) {
         modifiers | Qt::MetaModifier;
     }
     return modifiers;
 }
keyMap()
QDirectFbKeyMap * QDirectFbConvenience::keyMap () static
Definition at line 201 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbInput::handleKeyEvents().
 {
     if (!dfbKeymap)
         dfbKeymap = new QDirectFbKeyMap();
     return dfbKeymap;
 }
mouseButton()
Qt::MouseButton QDirectFbConvenience::mouseButton (DFBInputDeviceButtonIdentifier identifier) static
Definition at line 129 of file qdirectfbconvenience.cpp.
 {
     switch (identifier){
     case DIBI_LEFT:
         return Qt::LeftButton;
     case DIBI_MIDDLE:
         return Qt::MidButton;
     case DIBI_RIGHT:
         return Qt::RightButton;
     default:
         return Qt::NoButton;
     }
 }
mouseButtons()
Qt::MouseButtons QDirectFbConvenience::mouseButtons (DFBInputDeviceButtonMask mask) static
Definition at line 143 of file qdirectfbconvenience.cpp.
Referenced by QDirectFbInput::handleMouseEvents().
 {
     Qt::MouseButtons buttons = Qt::NoButton;
     if (mask & DIBM_LEFT) {
         buttons |= Qt::LeftButton;
     }
     if (mask & DIBM_MIDDLE) {
         buttons |= Qt::MidButton;
     }
     if (mask & DIBM_RIGHT) {
         buttons |= Qt::RightButton;
     }
     return buttons;
 }
pixelFomatHasAlpha()
static bool QDirectFbConvenience::pixelFomatHasAlpha (const DFBSurfacePixelFormat format) inline static
Definition at line 68 of file qdirectfbconvenience.h.
 { return (1 << 16) & format; }
Friends and Related Functions
QDirectFbIntegration
friend class QDirectFbIntegration friend
Definition at line 86 of file qdirectfbconvenience.h.
Properties
dfbKeymap
QDirectFbKeyMap * QDirectFbConvenience::dfbKeymap = 0 static private
Definition at line 85 of file qdirectfbconvenience.h.
Referenced by eventType(), and keyMap().
The documentation for this class was generated from the following files:
/src/plugins/platforms/directfb/qdirectfbconvenience.h
/src/plugins/platforms/directfb/qdirectfbconvenience.cpp