Qt 4.8: QCacheItem Class Reference
QCacheItem Class Reference
#include <qnetworkdiskcache_p.h>
Public Functions
bool canCompress () const
We compress small text and JavaScript files.
QCacheItem ()
bool read (QFile *device, bool readData)
Returns false if the file is a cache file, but is an older version and should be removed otherwise true.
void reset ()
qint64 size () const
void writeCompressedData (QFile *device) const
void writeHeader (QFile *device) const
~QCacheItem ()
Public Variables
QBuffer data
QTemporaryFile * file
QNetworkCacheMetaData metaData
Detailed Description
Definition at line 68 of file qnetworkdiskcache_p.h.
Constructors and Destructors
QCacheItem()
QCacheItem::QCacheItem () inline
Definition at line 71 of file qnetworkdiskcache_p.h.
                  : file(0)
     {
     }
~QCacheItem()
QCacheItem::~QCacheItem () inline
Definition at line 74 of file qnetworkdiskcache_p.h.
     {
         reset();
     }
Functions
canCompress()
bool QCacheItem::canCompress () const
We compress small text and JavaScript files.
Definition at line 638 of file qnetworkdiskcache.cpp.
Referenced by QNetworkDiskCache::prepare(), and reset().
 {
     bool sizeOk = false;
     bool typeOk = false;
     foreach (QNetworkCacheMetaData::RawHeader header, metaData.rawHeaders()) {
         if (header.first.toLower() == "content-length") {
             qint64 size = header.second.toLongLong();
             if (size > MAX_COMPRESSION_SIZE)
                 return false;
             else
                 sizeOk = true;
         }
         if (header.first.toLower() == "content-type") {
             QByteArray type = header.second;
             if (type.startsWith("text/")
                     || (type.startsWith("application/")
                         && (type.endsWith("javascript") || type.endsWith("ecmascript"))))
                 typeOk = true;
             else
                 return false;
         }
         if (sizeOk && typeOk)
             return true;
     }
     return false;
 }
read()
bool QCacheItem::read (QFile * device, bool readData)
Returns false if the file is a cache file, but is an older version and should be removed otherwise true.
Definition at line 694 of file qnetworkdiskcache.cpp.
Referenced by reset().
 {
     reset();
     QDataStream in(device);
     qint32 marker;
     qint32 v;
     in >> marker;
     in >> v;
     if (marker != CacheMagic)
         return true;
     // If the cache magic is correct, but the version is not we should remove it
     if (v != CurrentCacheVersion)
         return false;
     bool compressed;
     QByteArray dataBA;
     in >> metaData;
     in >> compressed;
     if (readData && compressed) {
         in >> dataBA;
         data.setData(qUncompress(dataBA));
         data.open(QBuffer::ReadOnly);
     }
     // quick and dirty check if metadata's URL field and the file's name are in synch
     QString expectedFilename = QNetworkDiskCachePrivate::uniqueFileName(metaData.url());
     if (!device->fileName().endsWith(expectedFilename))
         return false;
     return metaData.isValid();
 }
reset()
void QCacheItem::reset () inline
Definition at line 85 of file qnetworkdiskcache_p.h.
Referenced by ~QCacheItem().
{
         metaData = QNetworkCacheMetaData();
         data.close();
         delete file;
         file = 0;
     }
size()
qint64 QCacheItem::size () const inline
Definition at line 82 of file qnetworkdiskcache_p.h.
Referenced by QNetworkDiskCachePrivate::storeItem().
         { return file ? file->size() : data.size(); }
writeCompressedData()
void QCacheItem::writeCompressedData (QFile * device) const
Definition at line 683 of file qnetworkdiskcache.cpp.
Referenced by reset(), and QNetworkDiskCachePrivate::storeItem().
 {
     QDataStream out(device);
     out << qCompress(data.data());
 }
writeHeader()
void QCacheItem::writeHeader (QFile * device) const
Definition at line 672 of file qnetworkdiskcache.cpp.
Referenced by QNetworkDiskCache::prepare(), reset(), and QNetworkDiskCachePrivate::storeItem().
 {
     QDataStream out(device);
     out << qint32(CacheMagic);
     out << qint32(CurrentCacheVersion);
     out << metaData;
     bool compressed = canCompress();
     out << compressed;
 }
Properties
data
QBuffer QCacheItem::data
Definition at line 80 of file qnetworkdiskcache_p.h.
Referenced by QNetworkDiskCache::prepare(), QNetworkDiskCachePrivate::QNetworkDiskCachePrivate(), and QNetworkDiskCachePrivate::storeItem().
file
QTemporaryFile* QCacheItem::file
Definition at line 81 of file qnetworkdiskcache_p.h.
Referenced by QNetworkDiskCache::prepare(), QNetworkDiskCachePrivate::QNetworkDiskCachePrivate(), reset(), and QNetworkDiskCachePrivate::storeItem().
metaData
QNetworkCacheMetaData QCacheItem::metaData
Definition at line 79 of file qnetworkdiskcache_p.h.
Referenced by QNetworkDiskCache::prepare(), QNetworkDiskCache::remove(), and QNetworkDiskCachePrivate::storeItem().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkdiskcache_p.h
/src/network/access/qnetworkdiskcache.cpp