Qt 4.8: QGenericMatrix< N, M, T > Class Template Reference
QGenericMatrix< N, M, T > Class Template Reference
The QGenericMatrix class is a template class that represents a NxM transformation matrix with N columns and M rows.
#include <qgenericmatrix.h>
Public Functions
const T * constData () const
Returns a constant pointer to the raw data of this matrix.
void copyDataTo (T *values) const
Retrieves the N * M items in this matrix and copies them to values in row-major order.
T * data ()
Returns a pointer to the raw data of this matrix.
const T * data () const
Returns a constant pointer to the raw data of this matrix.
void fill (T value)
Fills all elements of this matrix with value.
bool isIdentity () const
Returns true if this matrix is the identity; false otherwise.
bool operator!= (const QGenericMatrix< N, M, T > &other) const
Returns true if this matrix is not identical to other; false otherwise.
const T & operator() (int row, int column) const
Returns a constant reference to the element at position (row, column) in this matrix.
T & operator() (int row, int column)
Returns a reference to the element at position (row, column) in this matrix so that the element can be assigned to.
QGenericMatrix< N, M, T > & operator*= (T factor)
Multiplies all elements of this matrix by factor.
QGenericMatrix< N, M, T > & operator+= (const QGenericMatrix< N, M, T > &other)
Adds the contents of other to this matrix.
QGenericMatrix< N, M, T > & operator-= (const QGenericMatrix< N, M, T > &other)
Subtracts the contents of other from this matrix.
QGenericMatrix< N, M, T > & operator/= (T divisor)
Divides all elements of this matrix by divisor.
bool operator== (const QGenericMatrix< N, M, T > &other) const
Returns true if this matrix is identical to other; false otherwise.
QGenericMatrix ()
QGenericMatrix (const QGenericMatrix< N, M, T > &other)
Constructs a copy of other.
QGenericMatrix (const T *values)
Constructs a matrix from the given N * M floating-point values.
void setToIdentity ()
Sets this matrix to the identity.
QGenericMatrix< M, N, T > transposed () const
Returns this matrix, transposed about its diagonal.
Private Functions
QGenericMatrix (int)
Properties
T m [N][M]
Friends
template<int NN, int M1, int M2, typename TT >
QGenericMatrix< M1, M2, TT > operator* (const QGenericMatrix< NN, M2, TT > &m1, const QGenericMatrix< M1, NN, TT > &m2)
template<int NN, int MM, typename TT >
QGenericMatrix< NN, MM, TT > operator* (TT factor, const QGenericMatrix< NN, MM, TT > &matrix)
template<int NN, int MM, typename TT >
QGenericMatrix< NN, MM, TT > operator* (const QGenericMatrix< NN, MM, TT > &matrix, TT factor)
template<int NN, int MM, typename TT >
QGenericMatrix< NN, MM, TT > operator+ (const QGenericMatrix< NN, MM, TT > &m1, const QGenericMatrix< NN, MM, TT > &m2)
template<int NN, int MM, typename TT >
QGenericMatrix< NN, MM, TT > operator- (const QGenericMatrix< NN, MM, TT > &m1, const QGenericMatrix< NN, MM, TT > &m2)
template<int NN, int MM, typename TT >
QGenericMatrix< NN, MM, TT > operator- (const QGenericMatrix< NN, MM, TT > &matrix)
template<int NN, int MM, typename TT >
QGenericMatrix< NN, MM, TT > operator/ (const QGenericMatrix< NN, MM, TT > &matrix, TT divisor)
template<int NN, int MM, typename TT >
class QGenericMatrix
Constructs a NxM identity matrix.
Related Functions
(Note that these are not member functions.)
QGenericMatrix< M1, M2, T > operator* (const QGenericMatrix< N, M2, T > &m1, const QGenericMatrix< M1, N, T > &m2)
QGenericMatrix< N, M, T > operator* (T factor, const QGenericMatrix< N, M, T > &matrix)
QGenericMatrix< N, M, T > operator* (const QGenericMatrix< N, M, T > &matrix, T factor)
QGenericMatrix< N, M, T > operator+ (const QGenericMatrix< N, M, T > &m1, const QGenericMatrix< N, M, T > &m2)
Returns the sum of m1 and m2.
QGenericMatrix< N, M, T > operator- (const QGenericMatrix< N, M, T > &m1, const QGenericMatrix< N, M, T > &m2)
Returns the difference of m1 and m2.
QGenericMatrix< N, M, T > operator- (const QGenericMatrix< N, M, T > &matrix)
Returns the negation of matrix.
QGenericMatrix< N, M, T > operator/ (const QGenericMatrix< N, M, T > &matrix, T divisor)
Returns the result of dividing all elements of matrix by divisor.
QDataStream & operator<< (QDataStream &stream, const QGenericMatrix< N, M, T > &matrix)
Writes the given matrix to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QGenericMatrix< N, M, T > &matrix)
Reads a NxM matrix from the given stream into the given matrix and returns a reference to the stream.
QMatrix2x2
The QMatrix2x2 type defines a convenient instantiation of the QGenericMatrix template for 2 columns, 2 rows, and qreal as the element type.
QMatrix2x3
The QMatrix2x3 type defines a convenient instantiation of the QGenericMatrix template for 2 columns, 3 rows, and qreal as the element type.
QMatrix2x4
The QMatrix2x4 type defines a convenient instantiation of the QGenericMatrix template for 2 columns, 4 rows, and qreal as the element type.
QMatrix3x2
The QMatrix3x2 type defines a convenient instantiation of the QGenericMatrix template for 3 columns, 2 rows, and qreal as the element type.
QMatrix3x3
The QMatrix3x3 type defines a convenient instantiation of the QGenericMatrix template for 3 columns, 3 rows, and qreal as the element type.
QMatrix3x4
The QMatrix3x4 type defines a convenient instantiation of the QGenericMatrix template for 3 columns, 4 rows, and qreal as the element type.
QMatrix4x2
The QMatrix4x2 type defines a convenient instantiation of the QGenericMatrix template for 4 columns, 2 rows, and qreal as the element type.
QMatrix4x3
The QMatrix4x3 type defines a convenient instantiation of the QGenericMatrix template for 4 columns, 3 rows, and qreal as the element type.
Detailed Description
template<int N, int M, typename T>
class QGenericMatrix< N, M, T >
The QGenericMatrix class is a template class that represents a NxM transformation matrix with N columns and M rows.
Since
4.6
The QGenericMatrix template has three parameters:
N Number of columns.
M Number of rows.
T Element type that is visible to users of the class.
See also
QMatrix4x4
Definition at line 56 of file qgenericmatrix.h.
Constructors and Destructors
QGenericMatrix() [1/4]
template<int N, int M, typename T > Q_INLINE_TEMPLATE QGenericMatrix< N, M, T >::QGenericMatrix ()
Definition at line 115 of file qgenericmatrix.h.
 {
     setToIdentity();
 }
QGenericMatrix() [2/4]
template<int N, int M, typename T > Q_INLINE_TEMPLATE QGenericMatrix< N, M, T >::QGenericMatrix (const QGenericMatrix< N, M, T > & other)
Constructs a copy of other.
Definition at line 121 of file qgenericmatrix.h.
 {
     for (int col = 0; col < N; ++col)
         for (int row = 0; row < M; ++row)
             m[col][row] = other.m[col][row];
 }
QGenericMatrix() [3/4]
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE QGenericMatrix< N, M, T >::QGenericMatrix (const T * values) explicit
Constructs a matrix from the given N * M floating-point values.
The contents of the array values is assumed to be in row-major order.
See also
copyDataTo()
Definition at line 129 of file qgenericmatrix.h.
 {
     for (int col = 0; col < N; ++col)
         for (int row = 0; row < M; ++row)
             m[col][row] = values[row * N + col];
 }
QGenericMatrix() [4/4]
template<int N, int M, typename T> QGenericMatrix< N, M, T >::QGenericMatrix (int) inline private
Definition at line 106 of file qgenericmatrix.h.
 {}       // Construct without initializing identity matrix.
Functions
constData()
template<int N, int M, typename T> const T * QGenericMatrix< N, M, T >::constData () const inline
Returns a constant pointer to the raw data of this matrix.
See also
data()
Definition at line 84 of file qgenericmatrix.h.
Referenced by qGenericMatrixToMatrix4x4(), and QMatrix4x4::QMatrix4x4().
 { return *m; }
copyDataTo()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE void QGenericMatrix< N, M, T >::copyDataTo (T * values) const
Retrieves the N * M items in this matrix and copies them to values in row-major order.
Definition at line 332 of file qgenericmatrix.h.
 {
     for (int col = 0; col < N; ++col)
         for (int row = 0; row < M; ++row)
             values[row * N + col] = T(m[col][row]);
 }
data() [1/2]
template<int N, int M, typename T> T * QGenericMatrix< N, M, T >::data () inline
Returns a pointer to the raw data of this matrix.
See also
constData()
Definition at line 82 of file qgenericmatrix.h.
Referenced by QMatrix4x4::normalMatrix(), qGenericMatrixFromMatrix4x4(), and QMatrix4x4::toGenericMatrix().
 { return *m; }
data() [2/2]
template<int N, int M, typename T> const T * QGenericMatrix< N, M, T >::data () const inline
Returns a constant pointer to the raw data of this matrix.
See also
constData()
Definition at line 83 of file qgenericmatrix.h.
 { return *m; }
fill()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE void QGenericMatrix< N, M, T >::fill (T value)
Fills all elements of this matrix with value.
Definition at line 181 of file qgenericmatrix.h.
 {
     for (int col = 0; col < N; ++col)
         for (int row = 0; row < M; ++row)
             m[col][row] = value;
 }
isIdentity()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE bool QGenericMatrix< N, M, T >::isIdentity () const
Returns true if this matrix is the identity; false otherwise.
See also
setToIdentity()
Definition at line 151 of file qgenericmatrix.h.
 {
     for (int col = 0; col < N; ++col) {
         for (int row = 0; row < M; ++row) {
             if (row == col) {
                 if (m[col][row] != 1.0f)
                     return false;
             } else {
                 if (m[col][row] != 0.0f)
                     return false;
             }
         }
     }
     return true;
 }
operator!=()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE bool QGenericMatrix< N, M, T >::operator!= (const QGenericMatrix< N, M, T > & other) const
Returns true if this matrix is not identical to other; false otherwise.
Definition at line 237 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col) {
             if (m[col][row] != other.m[col][row])
                 return true;
         }
     return false;
 }
operator()() [1/2]
template<int N, int M, typename T > Q_INLINE_TEMPLATE const T & QGenericMatrix< N, M, T >::operator() (int row, int column) const
Returns a constant reference to the element at position (row, column) in this matrix.
Definition at line 137 of file qgenericmatrix.h.
 {
     Q_ASSERT(row >= 0 && row < M && column >= 0 && column < N);
     return m[column][row];
 }
operator()() [2/2]
template<int N, int M, typename T > Q_INLINE_TEMPLATE T & QGenericMatrix< N, M, T >::operator() (int row, int column)
Returns a reference to the element at position (row, column) in this matrix so that the element can be assigned to.
Definition at line 144 of file qgenericmatrix.h.
 {
     Q_ASSERT(row >= 0 && row < M && column >= 0 && column < N);
     return m[column][row];
 }
operator*=()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE QGenericMatrix< N, M, T > & QGenericMatrix< N, M, T >::operator*= (T factor)
Multiplies all elements of this matrix by factor.
Definition at line 217 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             m[col][row] *= factor;
     return *this;
 }
operator+=()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE QGenericMatrix< N, M, T > & QGenericMatrix< N, M, T >::operator+= (const QGenericMatrix< N, M, T > & other)
Adds the contents of other to this matrix.
Definition at line 199 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             m[col][row] += other.m[col][row];
     return *this;
 }
operator-=()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE QGenericMatrix< N, M, T > & QGenericMatrix< N, M, T >::operator-= (const QGenericMatrix< N, M, T > & other)
Subtracts the contents of other from this matrix.
Definition at line 208 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             m[col][row] -= other.m[col][row];
     return *this;
 }
operator/=()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE QGenericMatrix< N, M, T > & QGenericMatrix< N, M, T >::operator/= (T divisor)
Divides all elements of this matrix by divisor.
Definition at line 248 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             m[col][row] /= divisor;
     return *this;
 }
operator==()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE bool QGenericMatrix< N, M, T >::operator== (const QGenericMatrix< N, M, T > & other) const
Returns true if this matrix is identical to other; false otherwise.
Definition at line 226 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)  {
             if (m[col][row] != other.m[col][row])
                 return false;
         }
     return true;
 }
setToIdentity()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE void QGenericMatrix< N, M, T >::setToIdentity ()
Sets this matrix to the identity.
See also
isIdentity()
Definition at line 168 of file qgenericmatrix.h.
Referenced by QGenericMatrix< N, M, T >::QGenericMatrix().
 {
     for (int col = 0; col < N; ++col) {
         for (int row = 0; row < M; ++row) {
             if (row == col)
                 m[col][row] = 1.0f;
             else
                 m[col][row] = 0.0f;
         }
     }
 }
transposed()
template<int N, int M, typename T > Q_OUTOFLINE_TEMPLATE QGenericMatrix< M, N, T > QGenericMatrix< N, M, T >::transposed () const
Returns this matrix, transposed about its diagonal.
Definition at line 189 of file qgenericmatrix.h.
 {
     QGenericMatrix<M, N, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[row][col] = m[col][row];
     return result;
 }
Friends and Related Functions
operator* [1/6]
template<int N, int M, typename T> template<int NN, int M1, int M2, typename TT > QGenericMatrix<M1, M2, TT> operator* (const QGenericMatrix< NN, M2, TT > & m1, const QGenericMatrix< M1, NN, TT > & m2) friend
Referenced by QGenericMatrix< N, M, T >::constData().
operator* [2/6]
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix<NN, MM, TT> operator* (TT factor, const QGenericMatrix< NN, MM, TT > & matrix) friend
operator* [3/6]
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix<NN, MM, TT> operator* (const QGenericMatrix< NN, MM, TT > & matrix, TT factor) friend
operator*() [4/6]
template<int N, int M, typename T> QGenericMatrix< M1, M2, T > operator* (const QGenericMatrix< N, M2, T > & m1, const QGenericMatrix< M1, N, T > & m2) related
Returns the product of the NxM2 matrix m1 and the M1xN matrix m2 to produce a M1xM2 matrix result.
Definition at line 277 of file qgenericmatrix.h.
 {
     QGenericMatrix<M1, M2, T> result(1);
     for (int row = 0; row < M2; ++row) {
         for (int col = 0; col < M1; ++col) {
             T sum(0.0f);
             for (int j = 0; j < N; ++j)
                 sum += m1.m[j][row] * m2.m[col][j];
             result.m[col][row] = sum;
         }
     }
     return result;
 }
operator*() [5/6]
template<int N, int M, typename T> QGenericMatrix< N, M, T > operator* (T factor, const QGenericMatrix< N, M, T > & matrix) related
Returns the result of multiplying all elements of matrix by factor.
Definition at line 302 of file qgenericmatrix.h.
 {
     QGenericMatrix<N, M, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[col][row] = matrix.m[col][row] * factor;
     return result;
 }
operator*() [6/6]
template<int N, int M, typename T> QGenericMatrix< N, M, T > operator* (const QGenericMatrix< N, M, T > & matrix, T factor) related
Returns the result of multiplying all elements of matrix by factor.
Definition at line 312 of file qgenericmatrix.h.
 {
     QGenericMatrix<N, M, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[col][row] = matrix.m[col][row] * factor;
     return result;
 }
operator+ [1/2]
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix<NN, MM, TT> operator+ (const QGenericMatrix< NN, MM, TT > & m1, const QGenericMatrix< NN, MM, TT > & m2) friend
Referenced by QGenericMatrix< N, M, T >::constData().
operator+() [2/2]
template<int N, int M, typename T> QGenericMatrix< N, M, T > operator+ (const QGenericMatrix< N, M, T > & m1, const QGenericMatrix< N, M, T > & m2) related
Returns the sum of m1 and m2.
Definition at line 257 of file qgenericmatrix.h.
 {
     QGenericMatrix<N, M, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[col][row] = m1.m[col][row] + m2.m[col][row];
     return result;
 }
operator- [1/4]
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix<NN, MM, TT> operator- (const QGenericMatrix< NN, MM, TT > & m1, const QGenericMatrix< NN, MM, TT > & m2) friend
Referenced by QGenericMatrix< N, M, T >::constData().
operator- [2/4]
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix<NN, MM, TT> operator- (const QGenericMatrix< NN, MM, TT > & matrix) friend
operator-() [3/4]
template<int N, int M, typename T> QGenericMatrix< N, M, T > operator- (const QGenericMatrix< N, M, T > & m1, const QGenericMatrix< N, M, T > & m2) related
Returns the difference of m1 and m2.
Definition at line 267 of file qgenericmatrix.h.
 {
     QGenericMatrix<N, M, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[col][row] = m1.m[col][row] - m2.m[col][row];
     return result;
 }
operator-() [4/4]
template<int N, int M, typename T> QGenericMatrix< N, M, T > operator- (const QGenericMatrix< N, M, T > & matrix) related
Returns the negation of matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 292 of file qgenericmatrix.h.
 {
     QGenericMatrix<N, M, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[col][row] = -matrix.m[col][row];
     return result;
 }
operator/ [1/2]
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix<NN, MM, TT> operator/ (const QGenericMatrix< NN, MM, TT > & matrix, TT divisor) friend
Referenced by QGenericMatrix< N, M, T >::constData().
operator/() [2/2]
template<int N, int M, typename T> QGenericMatrix< N, M, T > operator/ (const QGenericMatrix< N, M, T > & matrix, T divisor) related
Returns the result of dividing all elements of matrix by divisor.
Definition at line 322 of file qgenericmatrix.h.
 {
     QGenericMatrix<N, M, T> result(1);
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             result.m[col][row] = matrix.m[col][row] / divisor;
     return result;
 }
operator<<()
template<int N, int M, typename T> QDataStream & operator<< (QDataStream & stream, const QGenericMatrix< N, M, T > & matrix) related
Writes the given matrix to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 371 of file qgenericmatrix.h.
 {
     for (int row = 0; row < M; ++row)
         for (int col = 0; col < N; ++col)
             stream << double(matrix(row, col));
     return stream;
 }
operator>>()
template<int N, int M, typename T> QDataStream & operator>> (QDataStream & stream, QGenericMatrix< N, M, T > & matrix) related
Reads a NxM matrix from the given stream into the given matrix and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 380 of file qgenericmatrix.h.
 {
     double x;
     for (int row = 0; row < M; ++row) {
         for (int col = 0; col < N; ++col) {
             stream >> x;
             matrix(row, col) = T(x);
         }
     }
     return stream;
 }
QGenericMatrix
template<int N, int M, typename T> template<int NN, int MM, typename TT > QGenericMatrix< N, M, T >::QGenericMatrix friend
Constructs a NxM identity matrix.
Definition at line 110 of file qgenericmatrix.h.
QMatrix2x2()
template<int N, int M, typename T> QMatrix2x2 related
The QMatrix2x2 type defines a convenient instantiation of the QGenericMatrix template for 2 columns, 2 rows, and qreal as the element type.
QMatrix2x3()
template<int N, int M, typename T> QMatrix2x3 related
The QMatrix2x3 type defines a convenient instantiation of the QGenericMatrix template for 2 columns, 3 rows, and qreal as the element type.
QMatrix2x4()
template<int N, int M, typename T> QMatrix2x4 related
The QMatrix2x4 type defines a convenient instantiation of the QGenericMatrix template for 2 columns, 4 rows, and qreal as the element type.
QMatrix3x2()
template<int N, int M, typename T> QMatrix3x2 related
The QMatrix3x2 type defines a convenient instantiation of the QGenericMatrix template for 3 columns, 2 rows, and qreal as the element type.
QMatrix3x3()
template<int N, int M, typename T> QMatrix3x3 related
The QMatrix3x3 type defines a convenient instantiation of the QGenericMatrix template for 3 columns, 3 rows, and qreal as the element type.
QMatrix3x4()
template<int N, int M, typename T> QMatrix3x4 related
The QMatrix3x4 type defines a convenient instantiation of the QGenericMatrix template for 3 columns, 4 rows, and qreal as the element type.
QMatrix4x2()
template<int N, int M, typename T> QMatrix4x2 related
The QMatrix4x2 type defines a convenient instantiation of the QGenericMatrix template for 4 columns, 2 rows, and qreal as the element type.
QMatrix4x3()
template<int N, int M, typename T> QMatrix4x3 related
The QMatrix4x3 type defines a convenient instantiation of the QGenericMatrix template for 4 columns, 3 rows, and qreal as the element type.
Properties
m
template<int N, int M, typename T> T QGenericMatrix< N, M, T >::m[N][M] private
Definition at line 104 of file qgenericmatrix.h.
Referenced by QGenericMatrix< N, M, T >::constData(), QGenericMatrix< N, M, T >::copyDataTo(), QGenericMatrix< N, M, T >::data(), QGenericMatrix< N, M, T >::fill(), QGenericMatrix< N, M, T >::isIdentity(), QGenericMatrix< N, M, T >::operator!=(), QGenericMatrix< N, M, T >::operator()(), operator*(), QGenericMatrix< N, M, T >::operator*=(), operator+(), QGenericMatrix< N, M, T >::operator+=(), operator-(), QGenericMatrix< N, M, T >::operator-=(), operator/(), QGenericMatrix< N, M, T >::operator/=(), operator<<(), QGenericMatrix< N, M, T >::operator==(), QGenericMatrix< N, M, T >::QGenericMatrix(), QGenericMatrix< N, M, T >::setToIdentity(), and QGenericMatrix< N, M, T >::transposed().
The documentation for this class was generated from the following files:
/src/gui/math3d/qgenericmatrix.h
/src/gui/math3d/qgenericmatrix.cpp