Qt 4.8: QPatternist::XsdAttribute Class Reference
QPatternist::XsdAttribute Class Reference
XML Schema Processing
Represents a XSD attribute object.
#include <qxsdattribute_p.h>
Classes
class Scope
Describes the scope of an attribute.
class ValueConstraint
Describes the value constraint of an attribute.
Public Types
typedef QList< XsdAttribute::Ptr > List
typedef QExplicitlySharedDataPointer< XsdAttribute > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
Scope::Ptr scope () const
void setScope (const Scope::Ptr &scope)
void setType (const AnySimpleType::Ptr &type)
void setValueConstraint (const ValueConstraint::Ptr &constraint)
AnySimpleType::Ptr type () const
ValueConstraint::Ptr valueConstraint () const
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
Scope::Ptr m_scope
AnySimpleType::Ptr m_type
ValueConstraint::Ptr m_valueConstraint
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD attribute object.
This class represents the attribute object of a XML schema as described here.
It contains information from either a top-level attribute declaration (as child of a schema object) or of a local attribute declaration (as child of complexType or attributeGroup object without a 'ref' attribute).
All other occurrences of the attribute object are represented by the XsdAttributeUse class.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 83 of file qxsdattribute_p.h.
Typedefs
List
typedef QList<XsdAttribute::Ptr> QPatternist::XsdAttribute::List
Definition at line 87 of file qxsdattribute_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdAttribute> QPatternist::XsdAttribute::Ptr
Definition at line 86 of file qxsdattribute_p.h.
Functions
scope()
XsdAttribute::Scope::Ptr XsdAttribute::scope () const
Returns the scope of the attribute.
Definition at line 115 of file qxsdattribute.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseLocalAttribute(), and setScope().
 {
     return m_scope;
 }
setScope()
void XsdAttribute::setScope (const Scope::Ptr & scope)
Sets the scope of the attribute.
See also
Scope Definition
Definition at line 110 of file qxsdattribute.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), and QPatternist::XsdSchemaParser::parseLocalAttribute().
 {
     m_scope = scope;
 }
setType()
void XsdAttribute::setType (const AnySimpleType::Ptr & type)
Sets the simple type definition of the attribute.
See also
Simple Type Definition
Definition at line 100 of file qxsdattribute.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseLocalAttribute(), and QPatternist::XsdSchemaResolver::resolveAttributeTypes().
 {
     m_type = type;
 }
setValueConstraint()
void XsdAttribute::setValueConstraint (const ValueConstraint::Ptr & constraint)
Sets the value constraint of the attribute.
See also
Value Constraint Definition
Definition at line 120 of file qxsdattribute.cpp.
Referenced by QPatternist::XsdSchemaParser::parseGlobalAttribute(), and QPatternist::XsdSchemaParser::parseLocalAttribute().
 {
     m_valueConstraint = constraint;
 }
type()
AnySimpleType::Ptr XsdAttribute::type () const
Returns the simple type definition of the attribute.
Definition at line 105 of file qxsdattribute.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaDebugger::dumpAttribute(), setType(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), and QPatternist::XsdValidatingInstanceReader::validateElementComplexType().
 {
     return m_type;
 }
valueConstraint()
XsdAttribute::ValueConstraint::Ptr XsdAttribute::valueConstraint () const
Returns the value constraint of the attribute.
Definition at line 125 of file qxsdattribute.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkAttributeConstraints(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), and QPatternist::XsdValidatingInstanceReader::validateAttribute().
 {
     return m_valueConstraint;
 }
Properties
m_scope
Scope::Ptr QPatternist::XsdAttribute::m_scope private
Definition at line 237 of file qxsdattribute_p.h.
Referenced by scope(), and setScope().
m_type
AnySimpleType::Ptr QPatternist::XsdAttribute::m_type private
Definition at line 236 of file qxsdattribute_p.h.
Referenced by setType(), and type().
m_valueConstraint
ValueConstraint::Ptr QPatternist::XsdAttribute::m_valueConstraint private
Definition at line 238 of file qxsdattribute_p.h.
Referenced by setValueConstraint(), and valueConstraint().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdattribute_p.h
/src/xmlpatterns/schema/qxsdattribute.cpp