Qt 4.8: QImageTextureGlyphCache Class Reference
QImageTextureGlyphCache Class Reference
#include <qtextureglyphcache_p.h>
Public Functions
virtual void createTextureData (int width, int height)
virtual void fillTexture (const Coord &c, glyph_t glyph, QFixed subPixelPosition)
virtual int glyphMargin () const
const QImage & image () const
QImageTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform &matrix)
virtual void resizeTextureData (int width, int height)
Public Functions inherited from QTextureGlyphCache
void createCache (int width, int height)
void fillInPendingGlyphs ()
virtual int glyphPadding () const
bool isNull () const
virtual int maxTextureHeight () const
virtual int maxTextureWidth () const
bool populate (QFontEngine *fontEngine, int numGlyphs, const glyph_t *glyphs, const QFixedPoint *positions)
QTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform &matrix)
void resizeCache (int width, int height)
QFixed subPixelPositionForX (QFixed x) const
QImage textureMapForGlyph (glyph_t g, QFixed subPixelPosition) const
virtual ~QTextureGlyphCache ()
Public Functions inherited from QFontEngineGlyphCache
Type cacheType () const
QFontEngineGlyphCache (const QTransform &matrix, Type type)
virtual ~QFontEngineGlyphCache ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
QImage m_image
Additional Inherited Members
Public Types inherited from QFontEngineGlyphCache
enum Type { Raster_RGBMask, Raster_A8, Raster_Mono }
Public Variables inherited from QTextureGlyphCache
QHash< GlyphAndSubPixelPosition, Coord > coords
Public Variables inherited from QFontEngineGlyphCache
QTransform m_transform
QFontEngineGlyphCache::Type m_type
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QTextureGlyphCache
int calculateSubPixelPositionCount (glyph_t) const
Protected Variables inherited from QTextureGlyphCache
QFontEngine * m_current_fontengine
int m_currentRowHeight
int m_cx
int m_cy
int m_h
QHash< GlyphAndSubPixelPosition, Coord > m_pendingGlyphs
int m_subPixelPositionCount
int m_w
Detailed Description
Definition at line 171 of file qtextureglyphcache_p.h.
Constructors and Destructors
QImageTextureGlyphCache()
QImageTextureGlyphCache::QImageTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform & matrix) inline
Definition at line 174 of file qtextureglyphcache_p.h.
         : QTextureGlyphCache(type, matrix) { }
Functions
createTextureData()
void QImageTextureGlyphCache::createTextureData (int width, int height) virtual
Implements QTextureGlyphCache.
Reimplemented in QGLTextureGlyphCache.
Definition at line 347 of file qtextureglyphcache.cpp.
Referenced by QGLTextureGlyphCache::createTextureData().
 {
     switch (m_type) {
     case QFontEngineGlyphCache::Raster_Mono:
         m_image = QImage(width, height, QImage::Format_Mono);
         break;
     case QFontEngineGlyphCache::Raster_A8: {
         m_image = QImage(width, height, QImage::Format_Indexed8);
         m_image.fill(0);
         QVector<QRgb> colors(256);
         QRgb *it = colors.data();
         for (int i=0; i<256; ++i, ++it)
             *it = 0xff000000 | i | (i<<8) | (i<<16);
         m_image.setColorTable(colors);
         break;   }
     case QFontEngineGlyphCache::Raster_RGBMask:
         m_image = QImage(width, height, QImage::Format_RGB32);
         break;
     }
 }
fillTexture()
void QImageTextureGlyphCache::fillTexture (const Coord & c, glyph_t glyph, QFixed subPixelPosition) virtual
Implements QTextureGlyphCache.
Reimplemented in QGLTextureGlyphCache.
Definition at line 377 of file qtextureglyphcache.cpp.
Referenced by QGLTextureGlyphCache::fillTexture().
 {
     QImage mask = textureMapForGlyph(g, subPixelPosition);
 #ifdef CACHE_DEBUG
     printf("fillTexture of %dx%d at %d,%d in the cache of %dx%d\n", c.w, c.h, c.x, c.y, m_image.width(), m_image.height());
     if (mask.width() > c.w || mask.height() > c.h) {
         printf("   ERROR; mask is bigger than reserved space! %dx%d instead of %dx%d\n", mask.width(), mask.height(), c.w,c.h);
         return;
     }
 #endif
     if (m_type == QFontEngineGlyphCache::Raster_RGBMask) {
         QImage ref(m_image.bits() + (c.x * 4 + c.y * m_image.bytesPerLine()),
                    qMax(mask.width(), c.w), qMax(mask.height(), c.h), m_image.bytesPerLine(),
                    m_image.format());
         QPainter p(&ref);
         p.setCompositionMode(QPainter::CompositionMode_Source);
         p.fillRect(0, 0, c.w, c.h, QColor(0,0,0,0)); // TODO optimize this
         p.drawImage(0, 0, mask);
         p.end();
     } else if (m_type == QFontEngineGlyphCache::Raster_Mono) {
         if (mask.depth() > 1) {
             // TODO optimize this
             mask = mask.alphaChannel();
             mask.invertPixels();
             mask = mask.convertToFormat(QImage::Format_Mono);
         }
         int mw = qMin(mask.width(), c.w);
         int mh = qMin(mask.height(), c.h);
         uchar *d = m_image.bits();
         int dbpl = m_image.bytesPerLine();
         for (int y = 0; y < c.h; ++y) {
             uchar *dest = d + (c.y + y) *dbpl + c.x/8;
             if (y < mh) {
                 uchar *src = mask.scanLine(y);
                 for (int x = 0; x < c.w/8; ++x) {
                     if (x < (mw+7)/8)
                         dest[x] = src[x];
                     else
                         dest[x] = 0;
                 }
             } else {
                 for (int x = 0; x < c.w/8; ++x)
                     dest[x] = 0;
             }
         }
     } else { // A8
         int mw = qMin(mask.width(), c.w);
         int mh = qMin(mask.height(), c.h);
         uchar *d = m_image.bits();
         int dbpl = m_image.bytesPerLine();
         if (mask.depth() == 1) {
             for (int y = 0; y < c.h; ++y) {
                 uchar *dest = d + (c.y + y) *dbpl + c.x;
                 if (y < mh) {
                     uchar *src = (uchar *) mask.scanLine(y);
                     for (int x = 0; x < c.w; ++x) {
                         if (x < mw)
                             dest[x] = (src[x >> 3] & (1 << (7 - (x & 7)))) > 0 ? 255 : 0;
                     }
                 }
             }
         } else if (mask.depth() == 8) {
             for (int y = 0; y < c.h; ++y) {
                 uchar *dest = d + (c.y + y) *dbpl + c.x;
                 if (y < mh) {
                     uchar *src = (uchar *) mask.scanLine(y);
                     for (int x = 0; x < c.w; ++x) {
                         if (x < mw)
                             dest[x] = src[x];
                     }
                 }
             }
         }
     }
 #ifdef CACHE_DEBUG
 //     QPainter p(&m_image);
 //     p.drawLine(
     QPoint base(c.x + glyphMargin(), c.y + glyphMargin() + c.baseLineY-1);
     if (m_image.rect().contains(base))
         m_image.setPixel(base, 255);
     m_image.save(QString::fromLatin1("cache-%1.png").arg(qint64(this)));
 #endif
 }
glyphMargin()
int QImageTextureGlyphCache::glyphMargin () const virtual
Reimplemented from QTextureGlyphCache.
Definition at line 368 of file qtextureglyphcache.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and QRasterPaintEngine::drawCachedGlyphs().
 {
 #if (defined(Q_WS_MAC) && defined(QT_MAC_USE_COCOA)) || defined(Q_WS_X11)
     return 0;
 #else
     return m_type == QFontEngineGlyphCache::Raster_RGBMask ? 2 : 0;
 #endif
 }
image()
const QImage& QImageTextureGlyphCache::image () const inline
Definition at line 181 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::createTextureData(), QRasterPaintEngine::drawCachedGlyphs(), QGLTextureGlyphCache::fillTexture(), and QGLTextureGlyphCache::resizeTextureData().
 { return m_image; }
resizeTextureData()
void QImageTextureGlyphCache::resizeTextureData (int width, int height) virtual
Implements QTextureGlyphCache.
Reimplemented in QGLTextureGlyphCache.
Definition at line 342 of file qtextureglyphcache.cpp.
Referenced by QGLTextureGlyphCache::resizeTextureData().
 {
     m_image = m_image.copy(0, 0, width, height);
 }
Properties
m_image
QImage QImageTextureGlyphCache::m_image private
Definition at line 184 of file qtextureglyphcache_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qtextureglyphcache_p.h
/src/gui/painting/qtextureglyphcache.cpp