Qt 4.8: QDeclarativeType Class Reference
QDeclarativeType Class Reference
#include <qdeclarativemetatype_p.h>
Public Types
typedef void(* CreateFunc) (void *)
Public Functions
QDeclarativeAttachedPropertiesFunc attachedPropertiesFunction () const
int attachedPropertiesId () const
const QMetaObject * attachedPropertiesType () const
bool availableInVersion (int vmajor, int vminor) const
bool availableInVersion (const QByteArray &module, int vmajor, int vminor) const
const QMetaObject * baseMetaObject () const
bool containsRevisionedAttributes () const
QObject * create () const
void create (QObject **, void **, size_t) const
CreateFunc createFunction () const
int createSize () const
QDeclarativeCustomParser * customParser () const
QVariant fromObject (QObject *) const
int index () const
const char * interfaceIId () const
bool isCreatable () const
bool isExtendedType () const
bool isInterface () const
int majorVersion () const
const QMetaObject * metaObject () const
int metaObjectRevision () const
int minorVersion () const
QByteArray module () const
QString noCreationReason () const
int parserStatusCast () const
int propertyValueInterceptorCast () const
int propertyValueSourceCast () const
int qListTypeId () const
QByteArray qmlTypeName () const
int typeId () const
QByteArray typeName () const
Private Functions
QDeclarativeType (int, const QDeclarativePrivate::RegisterInterface &)
QDeclarativeType (int, const QDeclarativePrivate::RegisterType &)
QDeclarativeType * superType () const
~QDeclarativeType ()
Properties
QDeclarativeTypePrivate * d
Friends
struct QDeclarativeMetaTypeData
class QDeclarativeTypePrivate
int registerComponent (const QDeclarativePrivate::RegisterComponent &)
int registerInterface (const QDeclarativePrivate::RegisterInterface &)
int registerType (const QDeclarativePrivate::RegisterType &)
Detailed Description
Definition at line 114 of file qdeclarativemetatype_p.h.
Typedefs
CreateFunc
typedef void(* QDeclarativeType::CreateFunc) (void *)
Definition at line 130 of file qdeclarativemetatype_p.h.
Constructors and Destructors
QDeclarativeType() [1/2]
QDeclarativeType::QDeclarativeType (int index, const QDeclarativePrivate::RegisterInterface & interface) private
Definition at line 193 of file qdeclarativemetatype.cpp.
Referenced by registerInterface(), and registerType().
 : d(new QDeclarativeTypePrivate)
 {
     d->m_isInterface = true;
     d->m_iid = interface.iid;
     d->m_typeId = interface.typeId;
     d->m_listId = interface.listId;
     d->m_newFunc = 0;
     d->m_index = index;
     d->m_isSetup = true;
     d->m_version_maj = 0;
     d->m_version_min = 0;
 }
QDeclarativeType() [2/2]
QDeclarativeType::QDeclarativeType (int index, const QDeclarativePrivate::RegisterType & type) private
Definition at line 207 of file qdeclarativemetatype.cpp.
 : d(new QDeclarativeTypePrivate)
 {
     QByteArray name = type.uri;
     if (type.uri) name += '/';
     name += type.elementName;
     d->m_module = type.uri;
     d->m_name = name;
     d->m_version_maj = type.versionMajor;
     d->m_version_min = type.versionMinor;
     if (type.version >= 1) // revisions added in version 1
         d->m_revision = type.revision;
     d->m_typeId = type.typeId;
     d->m_listId = type.listId;
     d->m_allocationSize = type.objectSize;
     d->m_newFunc = type.create;
     d->m_noCreationReason = type.noCreationReason;
     d->m_baseMetaObject = type.metaObject;
     d->m_attachedPropertiesFunc = type.attachedPropertiesFunction;
     d->m_attachedPropertiesType = type.attachedPropertiesMetaObject;
     if (d->m_attachedPropertiesType) {
         QHash<const QMetaObject *, int>::Iterator iter = d->m_attachedPropertyIds.find(d->m_baseMetaObject);
         if (iter == d->m_attachedPropertyIds.end())
             iter = d->m_attachedPropertyIds.insert(d->m_baseMetaObject, index);
         d->m_attachedPropertiesId = *iter;
     } else {
         d->m_attachedPropertiesId = -1;
     }
     d->m_parserStatusCast = type.parserStatusCast;
     d->m_propertyValueSourceCast = type.valueSourceCast;
     d->m_propertyValueInterceptorCast = type.valueInterceptorCast;
     d->m_extFunc = type.extensionObjectCreate;
     d->m_index = index;
     d->m_customParser = type.customParser;
     if (type.extensionMetaObject)
         d->m_extMetaObject = type.extensionMetaObject;
 }
~QDeclarativeType()
QDeclarativeType::~QDeclarativeType () private
Definition at line 247 of file qdeclarativemetatype.cpp.
 {
     delete d->m_customParser;
     delete d;
 }
Functions
attachedPropertiesFunction()
QDeclarativeAttachedPropertiesFunc QDeclarativeType::attachedPropertiesFunction () const
Definition at line 544 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeMetaType::attachedPropertiesFuncById(), QDeclarativeMetaType::attachedPropertiesFuncId(), QDeclarativeCompiler::buildProperty(), and QDeclarativeCompiler::buildPropertyInNamespace().
 {
     return d->m_attachedPropertiesFunc;
 }
attachedPropertiesId()
int QDeclarativeType::attachedPropertiesId () const
Definition at line 559 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeMetaType::attachedPropertiesFuncId(), QDeclarativeCompiler::buildProperty(), QDeclarativeBindingCompilerPrivate::parseName(), and QDeclarativeTypeNameScriptClass::queryProperty().
 {
     return d->m_attachedPropertiesId;
 }
attachedPropertiesType()
const QMetaObject * QDeclarativeType::attachedPropertiesType () const
Definition at line 549 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildPropertyInNamespace(), and QDeclarativeBindingCompilerPrivate::parseName().
 {
     return d->m_attachedPropertiesType;
 }
availableInVersion() [1/2]
bool QDeclarativeType::availableInVersion (int vmajor, int vminor) const
Definition at line 268 of file qdeclarativemetatype.cpp.
Referenced by cacheForNamespace(), and QDeclarativeMetaType::qmlType().
 {
     return vmajor > d->m_version_maj || (vmajor == d->m_version_maj && vminor >= d->m_version_min);
 }
availableInVersion() [2/2]
bool QDeclarativeType::availableInVersion (const QByteArray & module, int vmajor, int vminor) const
Definition at line 273 of file qdeclarativemetatype.cpp.
 {
     return module == d->m_module && (vmajor > d->m_version_maj || (vmajor == d->m_version_maj && vminor >= d->m_version_min));
 }
baseMetaObject()
const QMetaObject * QDeclarativeType::baseMetaObject () const
Definition at line 527 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeListReferencePrivate::init(), QDeclarativeListReference::QDeclarativeListReference(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativePropertyPrivate::rawMetaObjectForType(), QDeclarativeEnginePrivate::rawMetaObjectForType(), registerType(), and QDeclarativePropertyPrivate::write().
 {
     return d->m_baseMetaObject;
 }
containsRevisionedAttributes()
bool QDeclarativeType::containsRevisionedAttributes () const
Definition at line 532 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::cache(), and QDeclarativeCompiler::compile().
 {
     d->init();
     return d->m_containsRevisionedAttributes;
 }
create() [1/2]
QObject * QDeclarativeType::create () const
Definition at line 442 of file qdeclarativemetatype.cpp.
 {
     d->init();
     QObject *rv = (QObject *)operator new(d->m_allocationSize);
     d->m_newFunc(rv);
     if (rv && !d->m_metaObjects.isEmpty())
         (void)new QDeclarativeProxyMetaObject(rv, &d->m_metaObjects);
     return rv;
 }
create() [2/2]
void QDeclarativeType::create (QObject ** out, void ** memory, size_t additionalMemory) const
Definition at line 455 of file qdeclarativemetatype.cpp.
 {
     d->init();
     QObject *rv = (QObject *)operator new(d->m_allocationSize + additionalMemory);
     d->m_newFunc(rv);
     if (rv && !d->m_metaObjects.isEmpty())
         (void)new QDeclarativeProxyMetaObject(rv, &d->m_metaObjects);
     *out = rv;
     *memory = ((char *)rv) + d->m_allocationSize;
 }
createFunction()
QDeclarativeType::CreateFunc QDeclarativeType::createFunction () const
Definition at line 474 of file qdeclarativemetatype.cpp.
 {
     return d->m_newFunc;
 }
createSize()
int QDeclarativeType::createSize () const
Definition at line 484 of file qdeclarativemetatype.cpp.
 {
     return d->m_allocationSize;
 }
customParser()
QDeclarativeCustomParser * QDeclarativeType::customParser () const
Definition at line 469 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeVME::run().
 {
     return d->m_customParser;
 }
fromObject()
QVariant QDeclarativeType::fromObject (QObject *) const
index()
int QDeclarativeType::index () const
Definition at line 584 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildPropertyInNamespace(), QDeclarativeType(), registerInterface(), and registerType().
 {
     return d->m_index;
 }
interfaceIId()
const char * QDeclarativeType::interfaceIId () const
Definition at line 579 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeMetaType::interfaceIId().
 {
     return d->m_iid;
 }
isCreatable()
bool QDeclarativeType::isCreatable () const
Definition at line 489 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::compile().
 {
     return d->m_newFunc != 0;
 }
isExtendedType()
bool QDeclarativeType::isExtendedType () const
Definition at line 494 of file qdeclarativemetatype.cpp.
 {
     d->init();
     return !d->m_metaObjects.isEmpty();
 }
isInterface()
bool QDeclarativeType::isInterface () const
Definition at line 501 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeMetaType::interfaceIId().
 {
     return d->m_isInterface;
 }
majorVersion()
int QDeclarativeType::majorVersion () const
Definition at line 258 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::createCache().
 {
     return d->m_version_maj;
 }
metaObject()
const QMetaObject * QDeclarativeType::metaObject () const
Definition at line 516 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::cache(), QDeclarativeEnginePrivate::createCache(), QDeclarativeMetaType::defaultMethod(), QDeclarativeMetaType::defaultProperty(), QDeclarativeCompiler::evaluateEnum(), QDeclarativeEnginePrivate::metaObjectForType(), QDeclarativeMetaType::qmlType(), QDeclarativeCompiler::resolveType(), and QDeclarativeCompiler::testQualifiedEnumAssignment().
 {
     d->init();
     if (d->m_metaObjects.isEmpty())
         return d->m_baseMetaObject;
     else
         return d->m_metaObjects.first().metaObject;
 }
metaObjectRevision()
int QDeclarativeType::metaObjectRevision () const
Definition at line 539 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::createCache().
 {
     return d->m_revision;
 }
minorVersion()
int QDeclarativeType::minorVersion () const
Definition at line 263 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeEnginePrivate::createCache().
 {
     return d->m_version_min;
 }
module()
QByteArray QDeclarativeType::module () const
Definition at line 253 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildSignal(), and QDeclarativeEnginePrivate::createCache().
 {
     return d->m_module;
 }
noCreationReason()
QString QDeclarativeType::noCreationReason () const
Definition at line 479 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::compile().
 {
     return d->m_noCreationReason;
 }
parserStatusCast()
int QDeclarativeType::parserStatusCast () const
Definition at line 564 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildObject().
 {
     return d->m_parserStatusCast;
 }
propertyValueInterceptorCast()
int QDeclarativeType::propertyValueInterceptorCast () const
Definition at line 574 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::genPropertyAssignment().
 {
     return d->m_propertyValueInterceptorCast;
 }
propertyValueSourceCast()
int QDeclarativeType::propertyValueSourceCast () const
Definition at line 569 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::genPropertyAssignment().
 {
     return d->m_propertyValueSourceCast;
 }
qListTypeId()
int QDeclarativeType::qListTypeId () const
Definition at line 511 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeMetaType::listType(), registerInterface(), and registerType().
 {
     return d->m_listId;
 }
qmlTypeName()
QByteArray QDeclarativeType::qmlTypeName () const
Definition at line 437 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildObject(), cacheForNamespace(), QDeclarativeEnginePrivate::createCache(), qmlExecuteDeferred(), registerInterface(), registerType(), QDeclarativeCompiler::testQualifiedEnumAssignment(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     return d->m_name;
 }
superType()
QDeclarativeType * QDeclarativeType::superType () const private
Definition at line 279 of file qdeclarativemetatype.cpp.
 {
     if (!d->m_haveSuperType) {
         const QMetaObject *mo = d->m_baseMetaObject->superClass();
         while (mo && !d->m_superType) {
             d->m_superType = QDeclarativeMetaType::qmlType(mo, d->m_module, d->m_version_maj, d->m_version_min);
             mo = mo->superClass();
         }
         d->m_haveSuperType = true;
     }
     return d->m_superType;
 }
typeId()
int QDeclarativeType::typeId () const
Definition at line 506 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeMetaType::interfaceIId(), QDeclarativeMetaType::listType(), QDeclarativeMetaType::qmlType(), registerInterface(), and registerType().
 {
     return d->m_typeId;
 }
typeName()
QByteArray QDeclarativeType::typeName () const
Definition at line 429 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta().
 {
     if (d->m_baseMetaObject)
         return d->m_baseMetaObject->className();
     else
         return QByteArray();
 }
Friends and Related Functions
QDeclarativeMetaTypeData
friend struct QDeclarativeMetaTypeData friend
Definition at line 164 of file qdeclarativemetatype_p.h.
QDeclarativeTypePrivate
friend class QDeclarativeTypePrivate friend
Definition at line 163 of file qdeclarativemetatype_p.h.
registerComponent
int registerComponent (const QDeclarativePrivate::RegisterComponent & data) friend
Definition at line 679 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativePrivate::qmlregister().
 {
     if (data.typeName) {
         for (int ii = 0; data.typeName[ii]; ++ii) {
             if (!isalnum(data.typeName[ii])) {
                 qWarning("qmlRegisterType(): Invalid QML type name \"%s\"", data.typeName);
                 return 0;
             }
         }
     } else {
         qWarning("qmlRegisterType(): No QML type name for \"%s\"", data.url.toString().toLatin1().constData());
         return 0;
     }
     QWriteLocker lock(registeredComponentDataLock());
     QString path;
     // Relative paths are relative to application working directory
     if (data.url.isRelative() || data.url.scheme() == QLatin1String("file")) // Workaround QTBUG-11929
         path = QUrl::fromLocalFile(QDir::currentPath()+QLatin1String("/")).resolved(data.url).toString();
     else
         path = data.url.toString();
     QDeclarativeRegisteredComponentData *d = registeredComponentData();
     QDeclarativeDirParser::Component comp(
         QString::fromUtf8(data.typeName),
         path,
         data.majorVersion,
         data.minorVersion
     );
     QDeclarativeDirComponents* comps = d->registeredComponents.value(QByteArray(data.uri), 0);
     if (!comps)
         d->registeredComponents.insert(QByteArray(data.uri), comps = new QDeclarativeDirComponents);
     // Types added later should take precedence, like registerType
     comps->prepend(comp);
     return 1;
 }
registerInterface
int registerInterface (const QDeclarativePrivate::RegisterInterface & interface) friend
Definition at line 599 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativePrivate::qmlregister().
 {
     if (interface.version > 0)
         qFatal("qmlRegisterType(): Cannot mix incompatible QML versions.");
     QWriteLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     int index = data->types.count();
     QDeclarativeType *type = new QDeclarativeType(index, interface);
     data->types.append(type);
     data->idToType.insert(type->typeId(), type);
     data->idToType.insert(type->qListTypeId(), type);
     // XXX No insertMulti, so no multi-version interfaces?
     if (!type->qmlTypeName().isEmpty())
         data->nameToType.insert(type->qmlTypeName(), type);
     if (data->interfaces.size() <= interface.typeId)
         data->interfaces.resize(interface.typeId + 16);
     if (data->lists.size() <= interface.listId)
         data->lists.resize(interface.listId + 16);
     data->interfaces.setBit(interface.typeId, true);
     data->lists.setBit(interface.listId, true);
     return index;
 }
registerType
int registerType (const QDeclarativePrivate::RegisterType & type) friend
Definition at line 628 of file qdeclarativemetatype.cpp.
Referenced by QDeclarativePrivate::qmlregister().
 {
     if (type.elementName) {
         for (int ii = 0; type.elementName[ii]; ++ii) {
             if (!isalnum(type.elementName[ii])) {
                 qWarning("qmlRegisterType(): Invalid QML element name \"%s\"", type.elementName);
                 return -1;
             }
         }
     }
     QWriteLocker lock(metaTypeDataLock());
     QDeclarativeMetaTypeData *data = metaTypeData();
     int index = data->types.count();
     QDeclarativeType *dtype = new QDeclarativeType(index, type);
     data->types.append(dtype);
     data->idToType.insert(dtype->typeId(), dtype);
     if (dtype->qListTypeId()) data->idToType.insert(dtype->qListTypeId(), dtype);
     if (!dtype->qmlTypeName().isEmpty())
         data->nameToType.insertMulti(dtype->qmlTypeName(), dtype);
     data->metaObjectToType.insertMulti(dtype->baseMetaObject(), dtype);
     if (data->objects.size() <= type.typeId)
         data->objects.resize(type.typeId + 16);
     if (data->lists.size() <= type.listId)
         data->lists.resize(type.listId + 16);
     data->objects.setBit(type.typeId, true);
     if (type.listId) data->lists.setBit(type.listId, true);
     if (type.uri) {
         QByteArray mod(type.uri);
         QDeclarativeMetaTypeData::ModuleInfoHash::Iterator it = data->modules.find(mod);
         if (it == data->modules.end()) {
             // New module
             data->modules.insert(mod, QDeclarativeMetaTypeData::ModuleInfo(type.versionMajor,type.versionMinor));
         } else if ((*it).vmajor_max < type.versionMajor || ((*it).vmajor_max == type.versionMajor && (*it).vminor_max < type.versionMinor)) {
             // Newer module
             data->modules.insert(mod, QDeclarativeMetaTypeData::ModuleInfo((*it).vmajor_min, (*it).vminor_min, type.versionMajor, type.versionMinor));
         } else if ((*it).vmajor_min > type.versionMajor || ((*it).vmajor_min == type.versionMajor && (*it).vminor_min > type.versionMinor)) {
             // Older module
             data->modules.insert(mod, QDeclarativeMetaTypeData::ModuleInfo(type.versionMajor, type.versionMinor, (*it).vmajor_min, (*it).vminor_min));
         }
     }
     return index;
 }
Properties
d
QDeclarativeTypePrivate* QDeclarativeType::d private
Definition at line 172 of file qdeclarativemetatype_p.h.
Referenced by attachedPropertiesFunction(), attachedPropertiesId(), attachedPropertiesType(), availableInVersion(), baseMetaObject(), containsRevisionedAttributes(), create(), createFunction(), createSize(), customParser(), index(), QDeclarativeTypePrivate::init(), interfaceIId(), isCreatable(), isExtendedType(), isInterface(), majorVersion(), metaObject(), metaObjectRevision(), minorVersion(), module(), noCreationReason(), parserStatusCast(), propertyValueInterceptorCast(), propertyValueSourceCast(), QDeclarativeType(), qListTypeId(), qmlTypeName(), registerComponent(), superType(), typeId(), typeName(), and ~QDeclarativeType().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativemetatype_p.h
/src/declarative/qml/qdeclarativemetatype.cpp