Qt 4.8: QTabWidget Class Reference
QTabWidget Class Reference
The QTabWidget class provides a stack of tabbed widgets.
#include <qtabwidget.h>
Public Types
enum TabPosition { North, South, West, East }
This enum type defines where QTabWidget draws the tab row:
enum TabShape { Rounded, Triangular }
This enum type defines the shape of the tabs:
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void setCurrentIndex (int index)
void setCurrentWidget (QWidget *widget)
Makes widget the current widget.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentChanged (int index)
This signal is emitted whenever the current page index changes.
void tabCloseRequested (int index)
This signal is emitted when the close button on a tab is clicked.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int addTab (QWidget *widget, const QString &)
Adds a tab with the given page and label to the tab widget, and returns the index of the tab in the tab bar.
int addTab (QWidget *widget, const QIcon &icon, const QString &label)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Adds a tab with the given page, icon, and label to the tab widget, and returns the index of the tab in the tab bar.
void clear ()
Removes all the pages, but does not delete them.
QWidget * cornerWidget (Qt::Corner corner=Qt::TopRightCorner) const
Returns the widget shown in the corner of the tab widget or 0.
int count () const
int currentIndex () const
QWidget * currentWidget () const
Returns a pointer to the page currently being displayed by the tab dialog.
bool documentMode () const
Qt::TextElideMode elideMode () const
int heightForWidth (int width) const
Reimplemented Function
QSize iconSize () const
int indexOf (QWidget *widget) const
Returns the index position of the page occupied by the widget w, or -1 if the widget cannot be found.
int insertTab (int index, QWidget *widget, const QString &)
Inserts a tab with the given label and page into the tab widget at the specified index, and returns the index of the inserted tab in the tab bar.
int insertTab (int index, QWidget *widget, const QIcon &icon, const QString &label)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Inserts a tab with the given label, page, and icon into the tab widget at the specified index, and returns the index of the inserted tab in the tab bar.
bool isMovable () const
bool isTabEnabled (int index) const
Returns true if the page at position index is enabled; otherwise returns false.
QSize minimumSizeHint () const
Returns a suitable minimum size for the tab widget.
QTabWidget (QWidget *parent=0)
Constructs a tabbed widget with parent parent.
void removeTab (int index)
Removes the tab at position index from this stack of widgets.
void setCornerWidget (QWidget *w, Qt::Corner corner=Qt::TopRightCorner)
Sets the given widget to be shown in the specified corner of the tab widget.
void setDocumentMode (bool set)
void setElideMode (Qt::TextElideMode)
void setIconSize (const QSize &size)
void setMovable (bool movable)
void setTabEnabled (int index, bool)
If enable is true, the page at position index is enabled; otherwise the page at position index is disabled.
void setTabIcon (int index, const QIcon &icon)
Sets the icon for the tab at position index.
void setTabPosition (TabPosition)
void setTabsClosable (bool closeable)
void setTabShape (TabShape s)
void setTabText (int index, const QString &)
Defines a new label for the page at position index's tab.
void setTabToolTip (int index, const QString &tip)
Sets the tab tool tip for the page at position index to tip.
void setTabWhatsThis (int index, const QString &text)
Sets the What's This help text for the page at position index to text.
void setUsesScrollButtons (bool useButtons)
QSize sizeHint () const
Reimplemented Function
QIcon tabIcon (int index) const
Returns the icon for the tab on the page at position index.
TabPosition tabPosition () const
bool tabsClosable () const
TabShape tabShape () const
QString tabText (int index) const
Returns the label text for the tab on the page at position index.
QString tabToolTip (int index) const
Returns the tab tool tip for the page at position index or an empty string if no tool tip has been set.
QString tabWhatsThis (int index) const
Returns the What's This help text for the page at position index, or an empty string if no help text has been set.
bool usesScrollButtons () const
QWidget * widget (int index) const
Returns the tab page at index position index or 0 if the index is out of range.
~QTabWidget ()
Destroys the tabbed widget.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
Reimplemented Function
bool event (QEvent *)
Reimplemented Function
void initStyleOption (QStyleOptionTabWidgetFrame *option) const
Initialize option with the values from this QTabWidget.
void keyPressEvent (QKeyEvent *)
Reimplemented Function
void paintEvent (QPaintEvent *)
Paints the tab widget's tab bar in response to the paint event.
void resizeEvent (QResizeEvent *)
Reimplemented Function
void setTabBar (QTabBar *)
Replaces the dialog's QTabBar heading with the tab bar tb.
void showEvent (QShowEvent *)
Reimplemented Function
QTabBar * tabBar () const
Returns the current QTabBar.
virtual void tabInserted (int index)
This virtual handler is called after a new tab was added or inserted at position index.
virtual void tabRemoved (int index)
This virtual handler is called after a tab was removed from position index.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void setUpLayout (bool=false)
Properties
int count
the number of tabs in the tab bar
int currentIndex
the index position of the current tab page
bool documentMode
Whether or not the tab widget is rendered in a mode suitable for document pages.
Qt::TextElideMode elideMode
how to elide text in the tab bar
QSize iconSize
The size for icons in the tab bar.
bool movable
This property holds whether the user can move the tabs within the tabbar area.
TabPosition tabPosition
the position of the tabs in this tab widget
bool tabsClosable
whether close buttons are automatically added to each tab.
TabShape tabShape
the shape of the tabs in this tab widget
bool usesScrollButtons
Whether or not a tab bar should use buttons to scroll tabs when it has many tabs.
Friends
class Q3TabDialog
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTabWidget class provides a stack of tabbed widgets.
A tab widget provides a tab bar (see QTabBar) and a "page area" that is used to display pages related to each tab. By default, the tab bar is shown above the page area, but different configurations are available (see TabPosition). Each tab is associated with a different widget (called a page). Only the current page is shown in the page area; all the other pages are hidden. The user can show a different page by clicking on its tab or by pressing its Alt+letter shortcut if it has one.
The normal way to use QTabWidget is to do the following:
Create a QTabWidget.
Create a QWidget for each of the pages in the tab dialog, but do not specify parent widgets for them.
Insert child widgets into the page widget, using layouts to position them as normal.
Call addTab() or insertTab() to put the page widgets into the tab widget, giving each tab a suitable label with an optional keyboard shortcut.
The position of the tabs is defined by tabPosition , their shape by tabShape .
The signal currentChanged() is emitted when the user selects a page.
The current page index is available as currentIndex(), the current page widget with currentWidget(). You can retrieve a pointer to a page widget with a given index using widget(), and can find the index position of a widget with indexOf(). Use setCurrentWidget() or setCurrentIndex() to show a particular page.
You can change a tab's text and icon using setTabText() or setTabIcon(). A tab and its associated page can be removed with removeTab().
Each tab is either enabled or disabled at any given time (see setTabEnabled()). If a tab is enabled, the tab text is drawn normally and the user can select that tab. If it is disabled, the tab is drawn in a different way and the user cannot select that tab. Note that even if a tab is disabled, the page can still be visible, for example if all of the tabs happen to be disabled.
Tab widgets can be a very good way to split up a complex dialog. An alternative is to use a QStackedWidget for which you provide some means of navigating between pages, for example, a QToolBar or a QListWidget.
Most of the functionality in QTabWidget is provided by a QTabBar (at the top, providing the tabs) and a QStackedWidget (most of the area, organizing the individual pages).
Screenshot of a Windows XP style tab widget
Screenshot of a Macintosh style tab widget
Screenshot of a Plastique style tab widget
A Windows XP style tab widget. A Macintosh style tab widget. A Plastique style tab widget.
See also
QTabBar, QStackedWidget, QToolBox, {Tab Dialog Example}
Definition at line 60 of file qtabwidget.h.
Enumerations
TabPosition
enum QTabWidget::TabPosition
This enum type defines where QTabWidget draws the tab row:
North The tabs are drawn above the pages.
South The tabs are drawn below the pages.
West The tabs are drawn to the left of the pages.
East The tabs are drawn to the right of the pages.
Bottom
Top
Enumerator
North
South
West
East
Definition at line 112 of file qtabwidget.h.
                      { North, South, West, East
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         , Top = North, Bottom = South
 #endif
     };
TabShape
enum QTabWidget::TabShape
This enum type defines the shape of the tabs:
Rounded The tabs are drawn with a rounded look.
This is the default shape.
Triangular The tabs are drawn with a triangular look.
Enumerator
Rounded
Triangular
Definition at line 126 of file qtabwidget.h.
 { Rounded, Triangular };
Constructors and Destructors
QTabWidget()
QTabWidget::QTabWidget (QWidget * parent = 0) explicit
Constructs a tabbed widget with parent parent.
Definition at line 359 of file qtabwidget.cpp.
     : QWidget(*new QTabWidgetPrivate, parent, 0)
 {
     Q_D(QTabWidget);
     d->init();
 }
~QTabWidget()
QTabWidget::~QTabWidget ()
Destroys the tabbed widget.
Definition at line 383 of file qtabwidget.cpp.
 {
 }
Functions
addTab() [1/2]
int QTabWidget::addTab (QWidget * page, const QString & label)
Adds a tab with the given page and label to the tab widget, and returns the index of the tab in the tab bar.
If the tab's label contains an ampersand, the letter following the ampersand is used as a shortcut for the tab, e.g. if the label is "Bro\&wse" then Alt+W becomes a shortcut which will move the focus to this tab.
Note
If you call addTab() after show(), the layout system will try to adjust to the changes in its widgets hierarchy and may cause flicker. To prevent this, you can set the QWidget::updatesEnabled property to false prior to changes; remember to set the property to true when the changes are done, making the widget receive paint events again.
See also
insertTab()
Definition at line 407 of file qtabwidget.cpp.
 {
     return insertTab(-1, child, label);
 }
addTab() [2/2]
int QTabWidget::addTab (QWidget * page, const QIcon & icon, const QString & label)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Adds a tab with the given page, icon, and label to the tab widget, and returns the index of the tab in the tab bar.
This function is the same as addTab(), but with an additional icon.
Definition at line 423 of file qtabwidget.cpp.
 {
     return insertTab(-1, child, icon, label);
 }
changeEvent()
void QTabWidget::changeEvent (QEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1114 of file qtabwidget.cpp.
 {
     if (ev->type() == QEvent::StyleChange
 #ifdef Q_WS_MAC
             || ev->type() == QEvent::MacSizeChange
 #endif
             )
         setUpLayout();
     QWidget::changeEvent(ev);
 }
clear()
void QTabWidget::clear ()
Removes all the pages, but does not delete them.
Calling this function is equivalent to calling removeTab() until the tab widget is empty.
Definition at line 1419 of file qtabwidget.cpp.
 {
     // ### optimize by introduce QStackedLayout::clear()
     while (count())
         removeTab(0);
 }
cornerWidget()
QWidget * QTabWidget::cornerWidget (Qt::Corner corner = Qt::TopRightCorner) const
Returns the widget shown in the corner of the tab widget or 0.
Definition at line 623 of file qtabwidget.cpp.
Referenced by paintEvent().
 {
     Q_D(const QTabWidget);
     if (corner & Qt::TopRightCorner)
         return d->rightCornerWidget;
     return d->leftCornerWidget;
 }
count()
int QTabWidget::count () const
Referenced by QTabWidgetPrivate::_q_showTab(), clear(), keyPressEvent(), and widget().
currentChanged
void QTabWidget::currentChanged (int index) signal
This signal is emitted whenever the current page index changes.
Use currentChanged(int) instead.
The parameter is the new current page index position, or -1 if there isn't a new one (for example, if there are no widgets in the QTabWidget)
See also
currentWidget() currentIndex
Referenced by setTabBar().
currentIndex()
int QTabWidget::currentIndex () const
Referenced by keyPressEvent(), and setCurrentWidget().
currentWidget()
QWidget * QTabWidget::currentWidget () const
Returns a pointer to the page currently being displayed by the tab dialog.
The tab dialog does its best to make sure that this value is never 0 (but if you try hard enough, it can be).
See also
currentIndex(), setCurrentWidget()
Definition at line 652 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     return d->stack->currentWidget();
 }
documentMode()
bool QTabWidget::documentMode () const
Referenced by paintEvent(), setTabBar(), and setUsesScrollButtons().
elideMode()
Qt::TextElideMode QTabWidget::elideMode () const
Referenced by setIconSize().
event()
bool QTabWidget::event (QEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1104 of file qtabwidget.cpp.
 {
     if (ev->type() == QEvent::LayoutRequest)
         setUpLayout();
     return QWidget::event(ev);
 }
heightForWidth()
int QTabWidget::heightForWidth (int width) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QWidget.
Definition at line 917 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     QStyleOptionTabWidgetFrameV2 opt;
     initStyleOption(&opt);
     opt.state = QStyle::State_None;
     QSize zero(0,0);
     const QSize padding = style()->sizeFromContents(QStyle::CT_TabWidget, &opt, zero, this)
                                   .expandedTo(QApplication::globalStrut());
     QSize lc(0, 0), rc(0, 0);
     if (d->leftCornerWidget)
         lc = d->leftCornerWidget->sizeHint();
     if(d->rightCornerWidget)
         rc = d->rightCornerWidget->sizeHint();
     if (!d->dirty) {
         QTabWidget *that = (QTabWidget*)this;
         that->setUpLayout(true);
     }
     QSize t(d->tabs->sizeHint());
     if(usesScrollButtons())
         t = t.boundedTo(QSize(200,200));
     else
         t = t.boundedTo(QApplication::desktop()->size());
     const bool tabIsHorizontal = (d->pos == North || d->pos == South);
     const int contentsWidth = width - padding.width();
     int stackWidth = contentsWidth;
     if (!tabIsHorizontal)
         stackWidth -= qMax(t.width(), qMax(lc.width(), rc.width()));
     int stackHeight = d->stack->heightForWidth(stackWidth);
     QSize s(stackWidth, stackHeight);
     QSize contentSize = basicSize(tabIsHorizontal, lc, rc, s, t);
     return (contentSize + padding).expandedTo(QApplication::globalStrut()).height();
 }
iconSize()
QSize QTabWidget::iconSize () const
Referenced by paintEvent().
indexOf()
int QTabWidget::indexOf (QWidget * widget) const
Returns the index position of the page occupied by the widget w, or -1 if the widget cannot be found.
Definition at line 701 of file qtabwidget.cpp.
Referenced by setCurrentWidget().
 {
     Q_D(const QTabWidget);
     return d->stack->indexOf(w);
 }
initStyleOption()
void QTabWidget::initStyleOption (QStyleOptionTabWidgetFrame * option) const protected
Initialize option with the values from this QTabWidget.
This method is useful for subclasses when they need a QStyleOptionTabWidgetFrame, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom() QTabBar::initStyleOption()
Definition at line 284 of file qtabwidget.cpp.
Referenced by heightForWidth(), minimumSizeHint(), paintEvent(), setUpLayout(), and sizeHint().
 {
     if (!option)
         return;
     Q_D(const QTabWidget);
     option->initFrom(this);
     if (documentMode())
         option->lineWidth = 0;
     else
         option->lineWidth = style()->pixelMetric(QStyle::PM_DefaultFrameWidth, 0, this);
     int exth = style()->pixelMetric(QStyle::PM_TabBarBaseHeight, 0, this);
     QSize t(0, d->stack->frameWidth());
     if (d->tabs->isVisibleTo(const_cast<QTabWidget *>(this))) {
         t = d->tabs->sizeHint();
         if (documentMode()) {
             if (tabPosition() == East || tabPosition() == West) {
                 t.setHeight(height());
             } else {
                 t.setWidth(width());
             }
         }
     }
     if (d->rightCornerWidget) {
         const QSize rightCornerSizeHint = d->rightCornerWidget->sizeHint();
         const QSize bounds(rightCornerSizeHint.width(), t.height() - exth);
         option->rightCornerWidgetSize = rightCornerSizeHint.boundedTo(bounds);
     } else {
         option->rightCornerWidgetSize = QSize(0, 0);
     }
     if (d->leftCornerWidget) {
         const QSize leftCornerSizeHint = d->leftCornerWidget->sizeHint();
         const QSize bounds(leftCornerSizeHint.width(), t.height() - exth);
         option->leftCornerWidgetSize = leftCornerSizeHint.boundedTo(bounds);
     } else {
         option->leftCornerWidgetSize = QSize(0, 0);
     }
     switch (d->pos) {
     case QTabWidget::North:
         option->shape = d->shape == QTabWidget::Rounded ? QTabBar::RoundedNorth
                                                         : QTabBar::TriangularNorth;
         break;
     case QTabWidget::South:
         option->shape = d->shape == QTabWidget::Rounded ? QTabBar::RoundedSouth
                                                         : QTabBar::TriangularSouth;
         break;
     case QTabWidget::West:
         option->shape = d->shape == QTabWidget::Rounded ? QTabBar::RoundedWest
                                                         : QTabBar::TriangularWest;
         break;
     case QTabWidget::East:
         option->shape = d->shape == QTabWidget::Rounded ? QTabBar::RoundedEast
                                                         : QTabBar::TriangularEast;
         break;
     }
     option->tabBarSize = t;
     if (QStyleOptionTabWidgetFrameV2 *tabframe = qstyleoption_cast<QStyleOptionTabWidgetFrameV2*>(option)) {
         QRect tbRect = tabBar()->geometry();
         QRect selectedTabRect = tabBar()->tabRect(tabBar()->currentIndex());
         tabframe->tabBarRect = tbRect;
         selectedTabRect.moveTopLeft(selectedTabRect.topLeft() + tbRect.topLeft());
         tabframe->selectedTabRect = selectedTabRect;
     }
 }
insertTab() [1/2]
int QTabWidget::insertTab (int index, QWidget * page, const QString & label)
Inserts a tab with the given label and page into the tab widget at the specified index, and returns the index of the inserted tab in the tab bar.
The label is displayed in the tab and may vary in appearance depending on the configuration of the tab widget.
If the tab's label contains an ampersand, the letter following the ampersand is used as a shortcut for the tab, e.g. if the label is "Bro\&wse" then Alt+W becomes a shortcut which will move the focus to this tab.
If index is out of range, the tab is simply appended. Otherwise it is inserted at the specified position.
If the QTabWidget was empty before this function is called, the new page becomes the current page. Inserting a new tab at an index less than or equal to the current index will increment the current index, but keep the current page.
Note
If you call insertTab() after show(), the layout system will try to adjust to the changes in its widgets hierarchy and may cause flicker. To prevent this, you can set the QWidget::updatesEnabled property to false prior to changes; remember to set the property to true when the changes are done, making the widget receive paint events again.
See also
addTab()
Definition at line 461 of file qtabwidget.cpp.
Referenced by addTab().
 {
     return insertTab(index, w, QIcon(), label);
 }
insertTab() [2/2]
int QTabWidget::insertTab (int index, QWidget * page, const QIcon & icon, const QString & label)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Inserts a tab with the given label, page, and icon into the tab widget at the specified index, and returns the index of the inserted tab in the tab bar.
This function is the same as insertTab(), but with an additional icon.
Definition at line 478 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     if(!w)
         return -1;
     index = d->stack->insertWidget(index, w);
     d->tabs->insertTab(index, icon, label);
     setUpLayout();
     tabInserted(index);
     return index;
 }
isMovable()
bool QTabWidget::isMovable () const
Definition at line 1063 of file qtabwidget.cpp.
 {
     return tabBar()->isMovable();
 }
isTabEnabled()
bool QTabWidget::isTabEnabled (int index) const
Returns true if the page at position index is enabled; otherwise returns false.
Use isTabEnabled(tabWidget->indexOf(widget)) instead.
See also
setTabEnabled(), QWidget::isEnabled()
Definition at line 552 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     return d->tabs->isTabEnabled(index);
 }
keyPressEvent()
void QTabWidget::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1129 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     if (((e->key() == Qt::Key_Tab || e->key() == Qt::Key_Backtab) &&
           count() > 1 && e->modifiers() & Qt::ControlModifier)
 #ifdef QT_KEYPAD_NAVIGATION
           || QApplication::keypadNavigationEnabled() && (e->key() == Qt::Key_Left || e->key() == Qt::Key_Right) && count() > 1
 #endif
        ) {
         int pageCount = d->tabs->count();
         int page = currentIndex();
         int dx = (e->key() == Qt::Key_Backtab || e->modifiers() & Qt::ShiftModifier) ? -1 : 1;
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && (e->key() == Qt::Key_Left || e->key() == Qt::Key_Right))
             dx = e->key() == (isRightToLeft() ? Qt::Key_Right : Qt::Key_Left) ? -1 : 1;
 #endif
         for (int pass = 0; pass < pageCount; ++pass) {
             page+=dx;
             if (page < 0
 #ifdef QT_KEYPAD_NAVIGATION
                 && !e->isAutoRepeat()
 #endif
                ) {
                 page = count() - 1;
             } else if (page >= pageCount
 #ifdef QT_KEYPAD_NAVIGATION
                        && !e->isAutoRepeat()
 #endif
                       ) {
                 page = 0;
             }
             if (d->tabs->isTabEnabled(page)) {
                 setCurrentIndex(page);
                 break;
             }
         }
         if (!QApplication::focusWidget())
             d->tabs->setFocus();
     } else {
         e->ignore();
     }
 }
minimumSizeHint()
QSize QTabWidget::minimumSizeHint () const virtual
Returns a suitable minimum size for the tab widget.
Reimplemented Function
Reimplemented from QWidget.
Definition at line 887 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     QSize lc(0, 0), rc(0, 0);
     if(d->leftCornerWidget)
         lc = d->leftCornerWidget->minimumSizeHint();
     if(d->rightCornerWidget)
         rc = d->rightCornerWidget->minimumSizeHint();
     if (!d->dirty) {
         QTabWidget *that = (QTabWidget*)this;
         that->setUpLayout(true);
     }
     QSize s(d->stack->minimumSizeHint());
     QSize t(d->tabs->minimumSizeHint());
     QSize sz = basicSize(d->pos == North || d->pos == South, lc, rc, s, t);
     QStyleOptionTabWidgetFrameV2 opt;
     initStyleOption(&opt);
     opt.palette = palette();
     opt.state = QStyle::State_None;
     return style()->sizeFromContents(QStyle::CT_TabWidget, &opt, sz, this)
                     .expandedTo(QApplication::globalStrut());
 }
paintEvent()
void QTabWidget::paintEvent (QPaintEvent * event) protected virtual
Paints the tab widget's tab bar in response to the paint event.
Reimplemented from QWidget.
Definition at line 1281 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     if (documentMode()) {
         QStylePainter p(this, tabBar());
         if (QWidget *w = cornerWidget(Qt::TopLeftCorner)) {
             QStyleOptionTabBarBaseV2 opt;
             QTabBarPrivate::initStyleBaseOption(&opt, tabBar(), w->size());
             opt.rect.moveLeft(w->x() + opt.rect.x());
             opt.rect.moveTop(w->y() + opt.rect.y());
             p.drawPrimitive(QStyle::PE_FrameTabBarBase, opt);
         }
         if (QWidget *w = cornerWidget(Qt::TopRightCorner)) {
             QStyleOptionTabBarBaseV2 opt;
             QTabBarPrivate::initStyleBaseOption(&opt, tabBar(), w->size());
             opt.rect.moveLeft(w->x() + opt.rect.x());
             opt.rect.moveTop(w->y() + opt.rect.y());
             p.drawPrimitive(QStyle::PE_FrameTabBarBase, opt);
         }
         return;
     }
     QStylePainter p(this);
     QStyleOptionTabWidgetFrameV2 opt;
     initStyleOption(&opt);
     opt.rect = d->panelRect;
     p.drawPrimitive(QStyle::PE_FrameTabWidget, opt);
 }
removeTab()
void QTabWidget::removeTab (int index)
Removes the tab at position index from this stack of widgets.
The page widget itself is not deleted.
See also
addTab(), insertTab()
Definition at line 637 of file qtabwidget.cpp.
Referenced by clear().
 {
     Q_D(QTabWidget);
     if (QWidget *w = d->stack->widget(index))
         d->stack->removeWidget(w);
 }
resizeEvent()
void QTabWidget::resizeEvent (QResizeEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 711 of file qtabwidget.cpp.
 {
     QWidget::resizeEvent(e);
     setUpLayout();
 }
setCornerWidget()
void QTabWidget::setCornerWidget (QWidget * widget, Qt::Corner corner = Qt::TopRightCorner)
Sets the given widget to be shown in the specified corner of the tab widget.
The geometry of the widget is determined based on the widget's sizeHint() and the style().
Only the horizontal element of the corner will be used.
Passing 0 shows no widget in the corner.
Any previously set corner widget is hidden.
All widgets set here will be deleted by the tab widget when it is destroyed unless you separately reparent the widget after setting some other corner widget (or 0).
Note: Corner widgets are designed for North and South tab positions; other orientations are known to not work properly.
See also
cornerWidget(), setTabPosition()
Definition at line 602 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     if (widget && widget->parentWidget() != this)
         widget->setParent(this);
     if (corner & Qt::TopRightCorner) {
         if (d->rightCornerWidget)
             d->rightCornerWidget->hide();
         d->rightCornerWidget = widget;
     } else {
         if (d->leftCornerWidget)
             d->leftCornerWidget->hide();
         d->leftCornerWidget = widget;
     }
     setUpLayout();
 }
setCurrentIndex
void QTabWidget::setCurrentIndex (int index) slot
Definition at line 690 of file qtabwidget.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QTabWidget);
     d->tabs->setCurrentIndex(index);
 }
setCurrentWidget
void QTabWidget::setCurrentWidget (QWidget * widget) slot
Makes widget the current widget.
The widget used must be a page in this tab widget.
See also
addTab(), setCurrentIndex(), currentWidget()
Definition at line 664 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     d->tabs->setCurrentIndex(indexOf(widget));
 }
setDocumentMode()
void QTabWidget::setDocumentMode (bool set)
Definition at line 1406 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     d->tabs->setDocumentMode(enabled);
     d->tabs->setExpanding(!enabled);
     d->tabs->setDrawBase(enabled);
     setUpLayout();
 }
setElideMode()
void QTabWidget::setElideMode (Qt::TextElideMode mode)
Definition at line 1354 of file qtabwidget.cpp.
 {
     d_func()->tabs->setElideMode(mode);
 }
setIconSize()
void QTabWidget::setIconSize (const QSize & size)
Definition at line 1329 of file qtabwidget.cpp.
 {
     d_func()->tabs->setIconSize(size);
 }
setMovable()
void QTabWidget::setMovable (bool movable)
Definition at line 1068 of file qtabwidget.cpp.
 {
     tabBar()->setMovable(movable);
 }
setTabBar()
void QTabWidget::setTabBar (QTabBar * tb) protected
Replaces the dialog's QTabBar heading with the tab bar tb.
Note that this must be called before any tabs have been added, or the behavior is undefined.
See also
tabBar()
Definition at line 724 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     Q_ASSERT(tb);
     if (tb->parentWidget() != this) {
         tb->setParent(this);
         tb->show();
     }
     delete d->tabs;
     d->tabs = tb;
     setFocusProxy(d->tabs);
     connect(d->tabs, SIGNAL(currentChanged(int)),
             this, SLOT(_q_showTab(int)));
     connect(d->tabs, SIGNAL(tabMoved(int,int)),
             this, SLOT(_q_tabMoved(int,int)));
     if (d->tabs->tabsClosable())
         connect(d->tabs, SIGNAL(tabCloseRequested(int)),
                 this, SIGNAL(tabCloseRequested(int)));
     tb->setExpanding(!documentMode());
     setUpLayout();
 }
setTabEnabled()
void QTabWidget::setTabEnabled (int index, bool enable)
If enable is true, the page at position index is enabled; otherwise the page at position index is disabled.
Use setTabEnabled(tabWidget->indexOf(widget), b) instead.
The page's tab is redrawn appropriately.
QTabWidget uses QWidget::setEnabled() internally, rather than keeping a separate flag.
Note that even a disabled tab/page may be visible. If the page is visible already, QTabWidget will not hide it; if all the pages are disabled, QTabWidget will show one of them.
See also
isTabEnabled(), QWidget::setEnabled()
Definition at line 572 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     d->tabs->setTabEnabled(index, enable);
     if (QWidget *widget = d->stack->widget(index))
         widget->setEnabled(enable);
 }
setTabIcon()
void QTabWidget::setTabIcon (int index, const QIcon & icon)
Sets the icon for the tab at position index.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 529 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     d->tabs->setTabIcon(index, icon);
     setUpLayout();
 }
setTabPosition()
void QTabWidget::setTabPosition (TabPosition pos)
Definition at line 1010 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     if (d->pos == pos)
         return;
     d->pos = pos;
     d->updateTabBarPosition();
 }
setTabsClosable()
void QTabWidget::setTabsClosable (bool closeable)
Definition at line 1035 of file qtabwidget.cpp.
 {
     if (tabsClosable() == closeable)
         return;
     tabBar()->setTabsClosable(closeable);
     if (closeable)
         connect(tabBar(), SIGNAL(tabCloseRequested(int)),
                 this, SIGNAL(tabCloseRequested(int)));
     else
         disconnect(tabBar(), SIGNAL(tabCloseRequested(int)),
                   this, SIGNAL(tabCloseRequested(int)));
     setUpLayout();
 }
setTabShape()
void QTabWidget::setTabShape (TabShape s)
Definition at line 1092 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     if (d->shape == s)
         return;
     d->shape = s;
     d->updateTabBarPosition();
 }
setTabText()
void QTabWidget::setTabText (int index, const QString & label)
Defines a new label for the page at position index's tab.
If the provided text contains an ampersand character ('&'), a shortcut is automatically created for it. The character that follows the '&' will be used as the shortcut key. Any previous shortcut will be overwritten, or cleared if no shortcut is defined by the text. See the QShortcut documentation for details (to display an actual ampersand, use '&&').
Definition at line 504 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     d->tabs->setTabText(index, label);
     setUpLayout();
 }
setTabToolTip()
void QTabWidget::setTabToolTip (int index, const QString & tip)
Sets the tab tool tip for the page at position index to tip.
Use setTabToolTip(tabWidget->indexOf(widget), tip) instead.
See also
tabToolTip()
Definition at line 1203 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     d->tabs->setTabToolTip(index, tip);
 }
setTabWhatsThis()
void QTabWidget::setTabWhatsThis (int index, const QString & text)
Sets the What's This help text for the page at position index to text.
Since
4.1
Definition at line 1232 of file qtabwidget.cpp.
 {
     Q_D(QTabWidget);
     d->tabs->setTabWhatsThis(index, text);
 }
setUpLayout()
void QTabWidget::setUpLayout (bool onlyCheck = false) private
Definition at line 798 of file qtabwidget.cpp.
Referenced by changeEvent(), event(), heightForWidth(), insertTab(), minimumSizeHint(), resizeEvent(), setCornerWidget(), setDocumentMode(), setTabBar(), setTabIcon(), setTabsClosable(), setTabText(), showEvent(), and sizeHint().
 {
     Q_D(QTabWidget);
     if (onlyCheck && !d->dirty)
         return; // nothing to do
     QStyleOptionTabWidgetFrameV2 option;
     initStyleOption(&option);
     // this must be done immediately, because QWidgetItem relies on it (even if !isVisible())
     d->setLayoutItemMargins(QStyle::SE_TabWidgetLayoutItem, &option);
     if (!isVisible()) {
         d->dirty = true;
         return; // we'll do it later
     }
     QRect tabRect = style()->subElementRect(QStyle::SE_TabWidgetTabBar, &option, this);
     d->panelRect = style()->subElementRect(QStyle::SE_TabWidgetTabPane, &option, this);
     QRect contentsRect = style()->subElementRect(QStyle::SE_TabWidgetTabContents, &option, this);
     QRect leftCornerRect = style()->subElementRect(QStyle::SE_TabWidgetLeftCorner, &option, this);
     QRect rightCornerRect = style()->subElementRect(QStyle::SE_TabWidgetRightCorner, &option, this);
     d->tabs->setGeometry(tabRect);
     d->stack->setGeometry(contentsRect);
     if (d->leftCornerWidget)
         d->leftCornerWidget->setGeometry(leftCornerRect);
     if (d->rightCornerWidget)
         d->rightCornerWidget->setGeometry(rightCornerRect);
     if (!onlyCheck)
         update();
     updateGeometry();
 }
setUsesScrollButtons()
void QTabWidget::setUsesScrollButtons (bool useButtons)
Definition at line 1380 of file qtabwidget.cpp.
 {
     d_func()->tabs->setUsesScrollButtons(useButtons);
 }
showEvent()
void QTabWidget::showEvent (QShowEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 961 of file qtabwidget.cpp.
 {
     setUpLayout();
 }
sizeHint()
QSize QTabWidget::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 849 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     QSize lc(0, 0), rc(0, 0);
     QStyleOptionTabWidgetFrameV2 opt;
     initStyleOption(&opt);
     opt.state = QStyle::State_None;
     if (d->leftCornerWidget)
         lc = d->leftCornerWidget->sizeHint();
     if(d->rightCornerWidget)
         rc = d->rightCornerWidget->sizeHint();
     if (!d->dirty) {
         QTabWidget *that = (QTabWidget*)this;
         that->setUpLayout(true);
     }
     QSize s(d->stack->sizeHint());
     QSize t(d->tabs->sizeHint());
     if(usesScrollButtons())
         t = t.boundedTo(QSize(200,200));
     else
         t = t.boundedTo(QApplication::desktop()->size());
     QSize sz = basicSize(d->pos == North || d->pos == South, lc, rc, s, t);
     return style()->sizeFromContents(QStyle::CT_TabWidget, &opt, sz, this)
                     .expandedTo(QApplication::globalStrut());
 }
tabBar()
QTabBar * QTabWidget::tabBar () const protected
Returns the current QTabBar.
See also
setTabBar()
Definition at line 753 of file qtabwidget.cpp.
Referenced by isMovable(), paintEvent(), setMovable(), setTabPosition(), and setTabsClosable().
 {
     Q_D(const QTabWidget);
     return d->tabs;
 }
tabCloseRequested
void QTabWidget::tabCloseRequested (int index) signal
This signal is emitted when the close button on a tab is clicked.
Since
4.5
The index is the index that should be removed.
See also
setTabsClosable()
Referenced by setTabBar(), and setTabsClosable().
tabIcon()
QIcon QTabWidget::tabIcon (int index) const
Returns the icon for the tab on the page at position index.
Definition at line 540 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     return d->tabs->tabIcon(index);
 }
tabInserted()
void QTabWidget::tabInserted (int index) protected virtual
This virtual handler is called after a new tab was added or inserted at position index.
See also
tabRemoved()
Definition at line 1260 of file qtabwidget.cpp.
Referenced by insertTab().
 {
     Q_UNUSED(index)
 }
tabPosition()
TabPosition QTabWidget::tabPosition () const
Referenced by QTabWidgetPrivate::updateTabBarPosition().
tabRemoved()
void QTabWidget::tabRemoved (int index) protected virtual
This virtual handler is called after a tab was removed from position index.
See also
tabInserted()
Definition at line 1271 of file qtabwidget.cpp.
 {
     Q_UNUSED(index)
 }
tabsClosable()
bool QTabWidget::tabsClosable () const
Referenced by setTabPosition(), and setTabsClosable().
tabShape()
TabShape QTabWidget::tabShape () const
Referenced by setMovable().
tabText()
QString QTabWidget::tabText (int index) const
Returns the label text for the tab on the page at position index.
Definition at line 515 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     return d->tabs->tabText(index);
 }
tabToolTip()
QString QTabWidget::tabToolTip (int index) const
Returns the tab tool tip for the page at position index or an empty string if no tool tip has been set.
Use tabToolTip(tabWidget->indexOf(widget)) instead.
See also
setTabToolTip()
Definition at line 1215 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     return d->tabs->tabToolTip(index);
 }
tabWhatsThis()
QString QTabWidget::tabWhatsThis (int index) const
Returns the What's This help text for the page at position index, or an empty string if no help text has been set.
Since
4.1
Definition at line 1247 of file qtabwidget.cpp.
 {
     Q_D(const QTabWidget);
     return d->tabs->tabWhatsThis(index);
 }
usesScrollButtons()
bool QTabWidget::usesScrollButtons () const
Referenced by heightForWidth(), setElideMode(), and sizeHint().
widget()
QWidget * QTabWidget::widget (int index) const
Returns the tab page at index position index or 0 if the index is out of range.
Definition at line 1176 of file qtabwidget.cpp.
Referenced by setCornerWidget(), and setTabEnabled().
 {
     Q_D(const QTabWidget);
     return d->stack->widget(index);
 }
Friends and Related Functions
Q3TabDialog
friend class Q3TabDialog friend
Definition at line 244 of file qtabwidget.h.
Properties
count
int QTabWidget::count private
the number of tabs in the tab bar
By default, this property contains a value of 0.
Definition at line 67 of file qtabwidget.h.
currentIndex
int QTabWidget::currentIndex private
the index position of the current tab page
The current index is -1 if there is no current widget.
By default, this property contains a value of -1 because there are initially no tabs in the widget.
Definition at line 66 of file qtabwidget.h.
documentMode
bool QTabWidget::documentMode private
Whether or not the tab widget is rendered in a mode suitable for document pages.
This is the same as document mode on Mac OS X.
Since
4.5
When this property is set the tab widget frame is not rendered. This mode is useful for showing document-type pages where the page covers most of the tab widget area.
See also
elideMode, QTabBar::documentMode, QTabBar::usesScrollButtons, QStyle::SH_TabBar_PreferNoArrows
Definition at line 71 of file qtabwidget.h.
elideMode
Qt::TextElideMode QTabWidget::elideMode private
how to elide text in the tab bar
Since
4.2
This property controls how items are elided when there is not enough space to show them for a given tab bar size.
By default the value is style dependant.
See also
QTabBar::elideMode usesScrollButtons QStyle::SH_TabBar_ElideMode
Definition at line 69 of file qtabwidget.h.
iconSize
QSize QTabWidget::iconSize private
The size for icons in the tab bar.
Since
4.2
The default value is style-dependent. This is the maximum size that the icons will have. Icons are not scaled up if they are of smaller size.
See also
QTabBar::iconSize
Definition at line 68 of file qtabwidget.h.
movable
QTabWidget::movable private
This property holds whether the user can move the tabs within the tabbar area.
Since
4.5
By default, this property is false;
Definition at line 73 of file qtabwidget.h.
tabPosition
QTabWidget::TabPosition QTabWidget::tabPosition private
the position of the tabs in this tab widget
Possible values for this property are described by the TabPosition enum.
By default, this property is set to North .
See also
TabPosition
Definition at line 64 of file qtabwidget.h.
tabsClosable
bool QTabWidget::tabsClosable private
whether close buttons are automatically added to each tab.
Since
4.5
See also
QTabBar::tabsClosable()
Definition at line 72 of file qtabwidget.h.
tabShape
QTabWidget::TabShape QTabWidget::tabShape private
the shape of the tabs in this tab widget
Possible values for this property are QTabWidget::Rounded (default) or QTabWidget::Triangular.
See also
TabShape
Definition at line 65 of file qtabwidget.h.
usesScrollButtons
bool QTabWidget::usesScrollButtons private
Whether or not a tab bar should use buttons to scroll tabs when it has many tabs.
Since
4.2
When there are too many tabs in a tab bar for its size, the tab bar can either choose to expand its size or to add buttons that allow you to scroll through the tabs.
By default the value is style dependant.
See also
elideMode QTabBar::usesScrollButtons QStyle::SH_TabBar_PreferNoArrows
Definition at line 70 of file qtabwidget.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qtabwidget.h
/src/gui/widgets/qtabwidget.cpp