Qt 4.8: QGLColormap Class Reference
QGLColormap Class Reference
The QGLColormap class is used for installing custom colormaps into a QGLWidget.
#include <qglcolormap.h>
Classes
struct QGLColormapData
Public Functions
void detach ()
Detaches this QGLColormap from the shared block.
QColor entryColor (int idx) const
Returns the QRgb value in the colorcell with index idx.
QRgb entryRgb (int idx) const
Returns the QRgb value in the colorcell with index idx.
int find (QRgb color) const
Returns the index of the color color.
int findNearest (QRgb color) const
Returns the index of the color that is the closest match to color color.
bool isEmpty () const
Returns true if the colormap is empty or it is not in use by a QGLWidget; otherwise returns false.
QGLColormap & operator= (const QGLColormap &)
Assign a shallow copy of map to this QGLColormap.
QGLColormap ()
Construct a QGLColormap.
QGLColormap (const QGLColormap &)
Construct a shallow copy of map.
void setEntries (int count, const QRgb *colors, int base=0)
Set an array of cells in this colormap.
void setEntry (int idx, QRgb color)
Set cell at index idx in the colormap to color color.
void setEntry (int idx, const QColor &color)
Set the cell with index idx in the colormap to color color.
int size () const
Returns the number of colorcells in the colormap.
~QGLColormap ()
Dereferences the QGLColormap and deletes it if this was the last reference to it.
Protected Functions
Qt::HANDLE handle ()
Returns the handle for this color map.
void setHandle (Qt::HANDLE ahandle)
Sets the handle for this color map to handle.
Private Functions
void detach_helper ()
Static Private Functions
static void cleanup (QGLColormapData *x)
Properties
QGLColormapData * d
Static Private Attributes
static struct QGLColormapData shared_null = { Q_BASIC_ATOMIC_INITIALIZER(1), 0, 0 }
Friends
class QGLWidget
class QGLWidgetPrivate
Detailed Description
The QGLColormap class is used for installing custom colormaps into a QGLWidget.
OpenGL
QGLColormap provides a platform independent way of specifying and installing indexed colormaps for a QGLWidget. QGLColormap is especially useful when using the OpenGL color-index mode.
Under X11 you must use an X server that supports either a PseudoColor or DirectColor visual class. If your X server currently only provides a GrayScale, TrueColor, StaticColor or StaticGray visual, you will not be able to allocate colorcells for writing. If this is the case, try setting your X server to 8 bit mode. It should then provide you with at least a PseudoColor visual. Note that you may experience colormap flashing if your X server is running in 8 bit mode.
The size() of the colormap is always set to 256 colors. Note that under Windows you can also install colormaps in child widgets.
This class uses implicit sharing as a memory and speed optimization.
Example of use:
#include <QApplication>
#include <QGLColormap>
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    MySuperGLWidget widget;     // a QGLWidget in color-index mode
    QGLColormap colormap;
    // This will fill the colormap with colors ranging from
    // black to white.
    const int size = 256;
    for (int i = 0; i < size; ++i)
        colormap.setEntry(i, qRgb(i, i, i));
    widget.setColormap(colormap);
    widget.show();
    return app.exec();
}
See also
QGLWidget::setColormap(), QGLWidget::colormap()
Definition at line 54 of file qglcolormap.h.
Constructors and Destructors
QGLColormap() [1/2]
QGLColormap::QGLColormap ()
Construct a QGLColormap.
Definition at line 111 of file qglcolormap.cpp.
     : d(&shared_null)
 {
     d->ref.ref();
 }
QGLColormap() [2/2]
QGLColormap::QGLColormap (const QGLColormap & map)
Construct a shallow copy of map.
Definition at line 121 of file qglcolormap.cpp.
     : d(map.d)
 {
     d->ref.ref();
 }
~QGLColormap()
QGLColormap::~QGLColormap ()
Dereferences the QGLColormap and deletes it if this was the last reference to it.
Definition at line 131 of file qglcolormap.cpp.
 {
     if (!d->ref.deref())
         cleanup(d);
 }
Functions
cleanup()
void QGLColormap::cleanup (QGLColormap::QGLColormapData * x) static private
Definition at line 137 of file qglcolormap.cpp.
Referenced by detach_helper(), operator=(), and ~QGLColormap().
 {
     delete x->cells;
     x->cells = 0;
     delete x;
 }
detach()
void QGLColormap::detach () inline
Detaches this QGLColormap from the shared block.
Warning
This function is not part of the public interface.
Definition at line 95 of file qglcolormap.h.
Referenced by setEntries(), and setEntry().
 {
     if (d->ref != 1)
         detach_helper();
 }
detach_helper()
void QGLColormap::detach_helper () private
Definition at line 166 of file qglcolormap.cpp.
 {
     QGLColormapData *x = new QGLColormapData;
     x->ref = 1;
     x->cmapHandle = 0;
     x->cells = 0;
     if (d->cells) {
         x->cells = new QVector<QRgb>(256);
         *x->cells = *d->cells;
     }
     if (!d->ref.deref())
         cleanup(d);
     d = x;
 }
entryColor()
QColor QGLColormap::entryColor (int idx) const
Returns the QRgb value in the colorcell with index idx.
Definition at line 237 of file qglcolormap.cpp.
 {
     if (d == &shared_null || !d->cells)
         return QColor();
     else
         return QColor(d->cells->at(idx));
 }
entryRgb()
QRgb QGLColormap::entryRgb (int idx) const
Returns the QRgb value in the colorcell with index idx.
Definition at line 213 of file qglcolormap.cpp.
Referenced by qStoreColors().
 {
     if (d == &shared_null || !d->cells)
         return 0;
     else
         return d->cells->at(idx);
 }
find()
int QGLColormap::find (QRgb color) const
Returns the index of the color color.
If color is not in the map, -1 is returned.
Definition at line 276 of file qglcolormap.cpp.
Referenced by findNearest().
 {
     if (d->cells)
         return d->cells->indexOf(color);
     return -1;
 }
findNearest()
int QGLColormap::findNearest (QRgb color) const
Returns the index of the color that is the closest match to color color.
Definition at line 287 of file qglcolormap.cpp.
 {
     int idx = find(color);
     if (idx >= 0)
         return idx;
     int mapSize = size();
     int mindist = 200000;
     int r = qRed(color);
     int g = qGreen(color);
     int b = qBlue(color);
     int rx, gx, bx, dist;
     for (int i = 0; i < mapSize; ++i) {
         QRgb ci = d->cells->at(i);
         rx = r - qRed(ci);
         gx = g - qGreen(ci);
         bx = b - qBlue(ci);
         dist = rx * rx + gx * gx + bx * bx;        // calculate distance
         if (dist < mindist) {                // minimal?
             mindist = dist;
             idx = i;
         }
     }
     return idx;
 }
handle()
Qt::HANDLE QGLColormap::handle () inline protected
Returns the handle for this color map.
Warning
This function is not part of the public interface.
Definition at line 76 of file qglcolormap.h.
 { return d ? d->cmapHandle : 0; }
isEmpty()
bool QGLColormap::isEmpty () const
Returns true if the colormap is empty or it is not in use by a QGLWidget; otherwise returns false.
A colormap with no color values set is considered to be empty. For historical reasons, a colormap that has color values set but which is not in use by a QGLWidget is also considered empty.
Compare size() with zero to determine if the colormap is empty regardless of whether it is in use by a QGLWidget or not.
See also
size()
Definition at line 258 of file qglcolormap.cpp.
 {
     return d == &shared_null || d->cells == 0 || d->cells->size() == 0 || d->cmapHandle == 0;
 }
operator=()
QGLColormap & QGLColormap::operator= (const QGLColormap & map)
Assign a shallow copy of map to this QGLColormap.
Definition at line 147 of file qglcolormap.cpp.
 {
     map.d->ref.ref();
     if (!d->ref.deref())
         cleanup(d);
     d = map.d;
     return *this;
 }
setEntries()
void QGLColormap::setEntries (int count, const QRgb * colors, int base = 0)
Set an array of cells in this colormap.
count is the number of colors that should be set, colors is the array of colors, and base is the starting index. The first element in colors is set at base in the colormap.
Definition at line 198 of file qglcolormap.cpp.
Referenced by QGLContextPrivate::updateFormatVersion().
 {
     detach();
     if (!d->cells)
         d->cells = new QVector<QRgb>(256);
     Q_ASSERT_X(colors && base >= 0 && (base + count) <= d->cells->size(), "QGLColormap::setEntries",
                "preconditions not met");
     for (int i = 0; i < count; ++i)
         setEntry(base + i, colors[i]);
 }
setEntry() [1/2]
void QGLColormap::setEntry (int idx, QRgb color)
Set cell at index idx in the colormap to color color.
Definition at line 184 of file qglcolormap.cpp.
Referenced by setEntries(), and setEntry().
 {
     detach();
     if (!d->cells)
         d->cells = new QVector<QRgb>(256);
     d->cells->replace(idx, color);
 }
setEntry() [2/2]
void QGLColormap::setEntry (int idx, const QColor & color)
Set the cell with index idx in the colormap to color color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 229 of file qglcolormap.cpp.
 {
     setEntry(idx, color.rgb());
 }
setHandle()
void QGLColormap::setHandle (Qt::HANDLE handle) inline protected
Sets the handle for this color map to handle.
Warning
This function is not part of the public interface.
Definition at line 77 of file qglcolormap.h.
 { d->cmapHandle = ahandle; }
size()
int QGLColormap::size () const
Returns the number of colorcells in the colormap.
Definition at line 267 of file qglcolormap.cpp.
Referenced by findNearest(), qStoreColors(), and QGLWidgetPrivate::updateColormap().
 {
     return d->cells ? d->cells->size() : 0;
 }
Friends and Related Functions
QGLWidget
friend class QGLWidget friend
Definition at line 91 of file qglcolormap.h.
QGLWidgetPrivate
friend class QGLWidgetPrivate friend
Definition at line 92 of file qglcolormap.h.
Properties
d
QGLColormapData* QGLColormap::d private
Definition at line 86 of file qglcolormap.h.
Referenced by detach_helper(), entryColor(), entryRgb(), find(), findNearest(), isEmpty(), operator=(), QGLColormap(), setEntries(), setEntry(), size(), and ~QGLColormap().
shared_null
QGLColormap::QGLColormapData QGLColormap::shared_null = { Q_BASIC_ATOMIC_INITIALIZER(1), 0, 0 } static private
Definition at line 87 of file qglcolormap.h.
Referenced by entryColor(), entryRgb(), and isEmpty().
The documentation for this class was generated from the following files:
/src/opengl/qglcolormap.h
/src/opengl/qglcolormap.cpp