Qt 4.8: QPatternist::AtomicMathematician Class Reference
QPatternist::AtomicMathematician Class Reference abstract
Base class for classes that performs arithmetic operations between atomic values.
#include <qatomicmathematician_p.h>
Public Types
enum Operator {
Div = 1, IDiv = 2, Substract = 4, Mod = 8,
Multiply = 16, Add = 32
}
typedef QFlags< Operator > Operators
typedef QExplicitlySharedDataPointer< AtomicMathematician > Ptr
Public Types inherited from QPatternist::AtomicTypeVisitorResult
typedef QExplicitlySharedDataPointer< AtomicTypeVisitorResult > Ptr
Public Functions
virtual Item calculate (const Item &operand1, const Operator op, const Item &operand2, const QExplicitlySharedDataPointer< DynamicContext > &context) const =0
virtual ~AtomicMathematician ()
Public Functions inherited from QPatternist::AtomicTypeVisitorResult
AtomicTypeVisitorResult ()
virtual ~AtomicTypeVisitorResult ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static QString displayName (const AtomicMathematician::Operator op)
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Base class for classes that performs arithmetic operations between atomic values.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 73 of file qatomicmathematician_p.h.
Typedefs
Operators
typedef QFlags<Operator> QPatternist::AtomicMathematician::Operators
Definition at line 119 of file qatomicmathematician_p.h.
Ptr
typedef QExplicitlySharedDataPointer<AtomicMathematician> QPatternist::AtomicMathematician::Ptr
Definition at line 78 of file qatomicmathematician_p.h.
Enumerations
Operator
enum QPatternist::AtomicMathematician::Operator
Enumerator
Div
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.2.4 op:numeric-divide
IDiv
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.2.5 op:numeric-integer-divide
Substract
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.2.2 op:numeric-subtract
Mod
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.2.6 op:numeric-mod
Multiply
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.2.3 op:numeric-multiply
Add
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.2.1 op:numeric-add
Definition at line 80 of file qatomicmathematician_p.h.
         {
             Div         = 1,
             IDiv        = 2,
             Substract   = 4,
             Mod         = 8,
             Multiply    = 16,
             Add         = 32
         };
Constructors and Destructors
~AtomicMathematician()
AtomicMathematician::~AtomicMathematician () virtual
Definition at line 48 of file qatomicmathematician.cpp.
 {
 }
Functions
calculate()
virtual Item QPatternist::AtomicMathematician::calculate (const Item & operand1, const Operator op, const Item & operand2, const QExplicitlySharedDataPointer< DynamicContext > & context) const pure virtual
Implemented in QPatternist::AbstractDateTimeMathematician, QPatternist::DateTimeDurationMathematician, QPatternist::OperandSwitcherMathematician, QPatternist::DurationDurationMathematician, QPatternist::DurationDurationDivisor, QPatternist::DurationNumericMathematician, QPatternist::IntegerMathematician, QPatternist::DecimalMathematician, and QPatternist::AbstractFloatMathematician< isDouble >.
Referenced by QPatternist::OperandSwitcherMathematician::calculate(), and QPatternist::ArithmeticExpression::flexiblyCalculate().
displayName()
QString AtomicMathematician::displayName (const AtomicMathematician::Operator op) static
Definition at line 52 of file qatomicmathematician.cpp.
Referenced by QPatternist::ArithmeticExpression::fetchMathematician().
 {
     switch(op)
     {
         case AtomicMathematician::Div:
             return QLatin1String("div");
         case AtomicMathematician::IDiv:
             return QLatin1String("idiv");
         case AtomicMathematician::Substract:
             return QLatin1String("-");
         case AtomicMathematician::Mod:
             return QLatin1String("mod");
         case AtomicMathematician::Multiply:
             return QLatin1String("*");
         case AtomicMathematician::Add:
             return QLatin1String("+");
     }
     return QString(); /* Silence GCC warning. */
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qatomicmathematician_p.h
/src/xmlpatterns/data/qatomicmathematician.cpp