Qt 4.8: QDeclarativeStyledTextPrivate Class Reference
QDeclarativeStyledTextPrivate Class Reference
Public Functions
void parse ()
QPair< QStringRef, QStringRef > parseAttribute (const QChar *&ch, const QString &textIn)
bool parseCloseTag (const QChar *&ch, const QString &textIn)
void parseEntity (const QChar *&ch, const QString &textIn, QString &textOut)
bool parseFontAttributes (const QChar *&ch, const QString &textIn, QTextCharFormat &format)
bool parseTag (const QChar *&ch, const QString &textIn, QString &textOut, QTextCharFormat &format)
QStringRef parseValue (const QChar *&ch, const QString &textIn)
QDeclarativeStyledTextPrivate (const QString &t, QTextLayout &l)
void skipSpace (const QChar *&ch)
Public Variables
QFont baseFont
QTextLayout & layout
QString text
Static Public Variables
static const QChar ampersand
static const QChar doubleQuote
static const QChar equals
static const QChar greaterThan
static const QChar lessThan
static const QChar singleQuote
static const QChar slash
Detailed Description
Definition at line 63 of file qdeclarativestyledtext.cpp.
Constructors and Destructors
QDeclarativeStyledTextPrivate()
QDeclarativeStyledTextPrivate::QDeclarativeStyledTextPrivate (const QString & t, QTextLayout & l) inline
Definition at line 66 of file qdeclarativestyledtext.cpp.
 : text(t), layout(l), baseFont(layout.font()) {}
Functions
parse()
void QDeclarativeStyledTextPrivate::parse ()
Definition at line 120 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledText::parse(), and QDeclarativeStyledTextPrivate().
 {
     QList<QTextLayout::FormatRange> ranges;
     QStack<QTextCharFormat> formatStack;
     QString drawText;
     drawText.reserve(text.count());
     int textStart = 0;
     int textLength = 0;
     int rangeStart = 0;
     const QChar *ch = text.constData();
     while (!ch->isNull()) {
         if (*ch == lessThan) {
             if (textLength)
                 drawText.append(QStringRef(&text, textStart, textLength));
             if (rangeStart != drawText.length() && formatStack.count()) {
                 QTextLayout::FormatRange formatRange;
                 formatRange.format = formatStack.top();
                 formatRange.start = rangeStart;
                 formatRange.length = drawText.length() - rangeStart;
                 ranges.append(formatRange);
             }
             rangeStart = drawText.length();
             ++ch;
             if (*ch == slash) {
                 ++ch;
                 if (parseCloseTag(ch, text)) {
                     if (formatStack.count())
                         formatStack.pop();
                 }
             } else {
                 QTextCharFormat format;
                 if (formatStack.count())
                     format = formatStack.top();
                 if (parseTag(ch, text, drawText, format))
                     formatStack.push(format);
             }
             textStart = ch - text.constData() + 1;
             textLength = 0;
         } else if (*ch == ampersand) {
             ++ch;
             drawText.append(QStringRef(&text, textStart, textLength));
             parseEntity(ch, text, drawText);
             textStart = ch - text.constData() + 1;
             textLength = 0;
         } else {
             ++textLength;
         }
         if (!ch->isNull())
             ++ch;
     }
     if (textLength)
         drawText.append(QStringRef(&text, textStart, textLength));
     if (rangeStart != drawText.length() && formatStack.count()) {
         QTextLayout::FormatRange formatRange;
         formatRange.format = formatStack.top();
         formatRange.start = rangeStart;
         formatRange.length = drawText.length() - rangeStart;
         ranges.append(formatRange);
     }
     layout.setText(drawText);
     layout.setAdditionalFormats(ranges);
 }
parseAttribute()
QPair< QStringRef, QStringRef > QDeclarativeStyledTextPrivate::parseAttribute (const QChar *& ch, const QString & textIn)
Definition at line 299 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledTextPrivate().
 {
     skipSpace(ch);
     int attrStart = ch - textIn.constData();
     int attrLength = 0;
     while (!ch->isNull()) {
         if (*ch == greaterThan) {
             break;
         } else if (*ch == equals) {
             ++ch;
             if (*ch != singleQuote && *ch != doubleQuote) {
                 while (*ch != greaterThan && !ch->isNull())
                     ++ch;
                 break;
             }
             ++ch;
             if (!attrLength)
                 break;
             QStringRef attr(&textIn, attrStart, attrLength);
             QStringRef val = parseValue(ch, textIn);
             if (!val.isEmpty())
                 return QPair<QStringRef,QStringRef>(attr,val);
             break;
         } else {
             ++attrLength;
         }
         ++ch;
     }
     return QPair<QStringRef,QStringRef>();
 }
parseCloseTag()
bool QDeclarativeStyledTextPrivate::parseCloseTag (const QChar *& ch, const QString & textIn)
Definition at line 224 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledTextPrivate().
 {
     skipSpace(ch);
     int tagStart = ch - textIn.constData();
     int tagLength = 0;
     while (!ch->isNull()) {
         if (*ch == greaterThan) {
             QStringRef tag(&textIn, tagStart, tagLength);
             const QChar char0 = tag.at(0);
             if (char0 == QLatin1Char('b')) {
                 if (tagLength == 1)
                     return true;
                 else if (tag.at(1) == QLatin1Char('r') && tagLength == 2)
                     return true;
             } else if (char0 == QLatin1Char('i')) {
                 if (tagLength == 1)
                     return true;
             } else if (tag == QLatin1String("font")) {
                 return true;
             }
             return false;
         } else if (!ch->isSpace()){
             tagLength++;
         }
         ++ch;
     }
     return false;
 }
parseEntity()
void QDeclarativeStyledTextPrivate::parseEntity (const QChar *& ch, const QString & textIn, QString & textOut)
Definition at line 255 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledTextPrivate().
 {
     int entityStart = ch - textIn.constData();
     int entityLength = 0;
     while (!ch->isNull()) {
         if (*ch == QLatin1Char(';')) {
             QStringRef entity(&textIn, entityStart, entityLength);
             if (entity == QLatin1String("gt"))
                 textOut += QChar(62);
             else if (entity == QLatin1String("lt"))
                 textOut += QChar(60);
             else if (entity == QLatin1String("amp"))
                 textOut += QChar(38);
             return;
         }
         ++entityLength;
         ++ch;
     }
 }
parseFontAttributes()
bool QDeclarativeStyledTextPrivate::parseFontAttributes (const QChar *& ch, const QString & textIn, QTextCharFormat & format)
Definition at line 275 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledTextPrivate().
 {
     bool valid = false;
     QPair<QStringRef,QStringRef> attr;
     do {
         attr = parseAttribute(ch, textIn);
         if (attr.first == QLatin1String("color")) {
             valid = true;
             format.setForeground(QColor(attr.second.toString()));
         } else if (attr.first == QLatin1String("size")) {
             valid = true;
             int size = attr.second.toString().toInt();
             if (attr.second.at(0) == QLatin1Char('-') || attr.second.at(0) == QLatin1Char('+'))
                 size += 3;
             if (size >= 1 && size <= 7) {
                 static const qreal scaling[] = { 0.7, 0.8, 1.0, 1.2, 1.5, 2.0, 2.4 };
                 format.setFontPointSize(baseFont.pointSize() * scaling[size-1]);
             }
         }
     } while (!ch->isNull() && !attr.first.isEmpty());
     return valid;
 }
parseTag()
bool QDeclarativeStyledTextPrivate::parseTag (const QChar *& ch, const QString & textIn, QString & textOut, QTextCharFormat & format)
Definition at line 186 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledTextPrivate().
 {
     skipSpace(ch);
     int tagStart = ch - textIn.constData();
     int tagLength = 0;
     while (!ch->isNull()) {
         if (*ch == greaterThan) {
             QStringRef tag(&textIn, tagStart, tagLength);
             const QChar char0 = tag.at(0);
             if (char0 == QLatin1Char('b')) {
                 if (tagLength == 1)
                     format.setFontWeight(QFont::Bold);
                 else if (tagLength == 2 && tag.at(1) == QLatin1Char('r')) {
                     textOut.append(QChar(QChar::LineSeparator));
                     return false;
                 }
             } else if (char0 == QLatin1Char('i')) {
                 if (tagLength == 1)
                     format.setFontItalic(true);
             }
             return true;
         } else if (ch->isSpace()) {
             // may have params.
             QStringRef tag(&textIn, tagStart, tagLength);
             if (tag == QLatin1String("font"))
                 return parseFontAttributes(ch, textIn, format);
             if (*ch == greaterThan || ch->isNull())
                 continue;
         } else if (*ch != slash){
             tagLength++;
         }
         ++ch;
     }
     return false;
 }
parseValue()
QStringRef QDeclarativeStyledTextPrivate::parseValue (const QChar *& ch, const QString & textIn)
Definition at line 332 of file qdeclarativestyledtext.cpp.
Referenced by QDeclarativeStyledTextPrivate().
 {
     int valStart = ch - textIn.constData();
     int valLength = 0;
     while (*ch != singleQuote && *ch != doubleQuote && !ch->isNull()) {
         ++valLength;
         ++ch;
     }
     if (ch->isNull())
         return QStringRef();
     ++ch; // skip quote
     return QStringRef(&textIn, valStart, valLength);
 }
skipSpace()
void QDeclarativeStyledTextPrivate::skipSpace (const QChar *& ch) inline
Definition at line 76 of file qdeclarativestyledtext.cpp.
{
         while (ch->isSpace() && !ch->isNull())
             ++ch;
     }
Properties
ampersand
const QChar QDeclarativeStyledTextPrivate::ampersand static
Definition at line 91 of file qdeclarativestyledtext.cpp.
baseFont
QFont QDeclarativeStyledTextPrivate::baseFont
Definition at line 83 of file qdeclarativestyledtext.cpp.
doubleQuote
const QChar QDeclarativeStyledTextPrivate::doubleQuote static
Definition at line 89 of file qdeclarativestyledtext.cpp.
equals
const QChar QDeclarativeStyledTextPrivate::equals static
Definition at line 87 of file qdeclarativestyledtext.cpp.
greaterThan
const QChar QDeclarativeStyledTextPrivate::greaterThan static
Definition at line 86 of file qdeclarativestyledtext.cpp.
layout
QTextLayout& QDeclarativeStyledTextPrivate::layout
Definition at line 82 of file qdeclarativestyledtext.cpp.
lessThan
const QChar QDeclarativeStyledTextPrivate::lessThan static
Definition at line 85 of file qdeclarativestyledtext.cpp.
singleQuote
const QChar QDeclarativeStyledTextPrivate::singleQuote static
Definition at line 88 of file qdeclarativestyledtext.cpp.
slash
const QChar QDeclarativeStyledTextPrivate::slash static
Definition at line 90 of file qdeclarativestyledtext.cpp.
text
QString QDeclarativeStyledTextPrivate::text
Definition at line 81 of file qdeclarativestyledtext.cpp.
The documentation for this class was generated from the following file:
/src/declarative/util/qdeclarativestyledtext.cpp