Qt 4.8: QHttpRequestHeader Class Reference
QHttpRequestHeader Class Reference
The QHttpRequestHeader class contains request header information for HTTP.
#include <qhttp.h>
Public Functions
int majorVersion () const
Returns the major protocol-version of the HTTP request header.
QString method () const
Returns the method of the HTTP request header.
int minorVersion () const
Returns the minor protocol-version of the HTTP request header.
QHttpRequestHeader & operator= (const QHttpRequestHeader &header)
Copies the content of header into this QHttpRequestHeader.
QString path () const
Returns the request-URI of the HTTP request header.
QHttpRequestHeader ()
Constructs an empty HTTP request header.
QHttpRequestHeader (const QString &method, const QString &path, int majorVer=1, int minorVer=1)
Constructs a HTTP request header for the method method, the request-URI path and the protocol-version majorVer and minorVer.
QHttpRequestHeader (const QHttpRequestHeader &header)
Constructs a copy of header.
QHttpRequestHeader (const QString &str)
Constructs a HTTP request header from the string str.
void setRequest (const QString &method, const QString &path, int majorVer=1, int minorVer=1)
This function sets the request method to method, the request-URI to path and the protocol-version to majorVer and minorVer.
QString toString () const
Reimplemented Function
Public Functions inherited from QHttpHeader
void addValue (const QString &key, const QString &value)
Adds a new entry with the key and value.
QStringList allValues (const QString &key) const
Returns all the entries with the given key.
uint contentLength () const
Returns the value of the special HTTP header field content-length.
QString contentType () const
Returns the value of the special HTTP header field content-type.
bool hasContentLength () const
Returns true if the header has an entry for the special HTTP header field content-length; otherwise returns false.
bool hasContentType () const
Returns true if the header has an entry for the special HTTP header field content-type; otherwise returns false.
bool hasKey (const QString &key) const
Returns true if the HTTP header has an entry with the given key; otherwise returns false.
bool isValid () const
Returns true if the HTTP header is valid; otherwise returns false.
QStringList keys () const
Returns a list of the keys in the HTTP header.
QHttpHeader & operator= (const QHttpHeader &h)
Assigns h and returns a reference to this http header.
QHttpHeader ()
Constructs an empty HTTP header.
QHttpHeader (const QHttpHeader &header)
Constructs a copy of header.
QHttpHeader (const QString &str)
Constructs a HTTP header for str.
void removeAllValues (const QString &key)
Removes all the entries with the key key from the HTTP header.
void removeValue (const QString &key)
Removes the entry with the key key from the HTTP header.
void setContentLength (int len)
Sets the value of the special HTTP header field content-length to len.
void setContentType (const QString &type)
Sets the value of the special HTTP header field content-type to type.
void setValue (const QString &key, const QString &value)
Sets the value of the entry with the key to value.
void setValues (const QList< QPair< QString, QString > > &values)
Sets the header entries to be the list of key value pairs in values.
QString value (const QString &key) const
Returns the first value for the entry with the given key.
QList< QPair< QString, QString > > values () const
Returns all the entries in the header.
virtual ~QHttpHeader ()
Destructor.
Protected Functions
bool parseLine (const QString &line, int number)
Protected Functions inherited from QHttpHeader
bool parse (const QString &str)
Parses the HTTP header string str for header fields and adds the keys/values it finds.
QHttpHeader (QHttpHeaderPrivate &dd, const QString &str=QString())
QHttpHeader (QHttpHeaderPrivate &dd, const QHttpHeader &header)
void setValid (bool)
Additional Inherited Members
Protected Variables inherited from QHttpHeader
QScopedPointer< QHttpHeaderPrivate > d_ptr
Detailed Description
The QHttpRequestHeader class contains request header information for HTTP.
Attention
Module: QtNetwork
This class is used in the QHttp class to report the header information if the client requests something from the server.
HTTP requests have a method which describes the request's action. The most common requests are "GET" and "POST". In addition to the request method the header also includes a request-URI to specify the location for the method to use.
The method, request-URI and protocol-version can be set using a constructor or later using setRequest(). The values can be obtained using method(), path(), majorVersion() and minorVersion().
Note that the request-URI must be in the format expected by the HTTP server. That is, all reserved characters must be encoded in HH (where HH are two hexadecimal digits). See QUrl::toPercentEncoding() for more information.
Important inherited functions: setValue() and value().
See also
QHttpResponseHeader QHttp
Definition at line 147 of file qhttp.h.
Constructors and Destructors
QHttpRequestHeader() [1/4]
QHttpRequestHeader::QHttpRequestHeader ()
Constructs an empty HTTP request header.
Definition at line 1279 of file qhttp.cpp.
     : QHttpHeader(*new QHttpRequestHeaderPrivate)
 {
     setValid(false);
 }
QHttpRequestHeader() [2/4]
QHttpRequestHeader::QHttpRequestHeader (const QString & method, const QString & path, int majorVer = 1, int minorVer = 1)
Constructs a HTTP request header for the method method, the request-URI path and the protocol-version majorVer and minorVer.
The path argument must be properly encoded for an HTTP request.
Definition at line 1291 of file qhttp.cpp.
     : QHttpHeader(*new QHttpRequestHeaderPrivate)
 {
     Q_D(QHttpRequestHeader);
     d->m = method;
     d->p = path;
     d->majVer = majorVer;
     d->minVer = minorVer;
 }
QHttpRequestHeader() [3/4]
QHttpRequestHeader::QHttpRequestHeader (const QHttpRequestHeader & header)
Constructs a copy of header.
Definition at line 1304 of file qhttp.cpp.
     : QHttpHeader(*new QHttpRequestHeaderPrivate, header)
 {
     Q_D(QHttpRequestHeader);
     d->m = header.d_func()->m;
     d->p = header.d_func()->p;
     d->majVer = header.d_func()->majVer;
     d->minVer = header.d_func()->minVer;
 }
QHttpRequestHeader() [4/4]
QHttpRequestHeader::QHttpRequestHeader (const QString & str)
Constructs a HTTP request header from the string str.
The str should consist of one or more "\r\n" delimited lines; the first line should be the request-line (format: method, space, request-URI, space HTTP-version); each of the remaining lines should have the format key, colon, space, value.
Definition at line 1335 of file qhttp.cpp.
     : QHttpHeader(*new QHttpRequestHeaderPrivate)
 {
     parse(str);
 }
Functions
majorVersion()
int QHttpRequestHeader::majorVersion () const virtual
Returns the major protocol-version of the HTTP request header.
See also
minorVersion() method() path() setRequest()
Implements QHttpHeader.
Definition at line 1386 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), and QHttpPrivate::addRequest().
 {
     Q_D(const QHttpRequestHeader);
     return d->majVer;
 }
method()
QString QHttpRequestHeader::method () const
Returns the method of the HTTP request header.
See also
path() majorVersion() minorVersion() setRequest()
Definition at line 1364 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QHttpPrivate::addRequest(), QHttpRequestHeader(), and setRequest().
 {
     Q_D(const QHttpRequestHeader);
     return d->m;
 }
minorVersion()
int QHttpRequestHeader::minorVersion () const virtual
Returns the minor protocol-version of the HTTP request header.
See also
majorVersion() method() path() setRequest()
Implements QHttpHeader.
Definition at line 1397 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), and QHttpPrivate::addRequest().
 {
     Q_D(const QHttpRequestHeader);
     return d->minVer;
 }
operator=()
QHttpRequestHeader & QHttpRequestHeader::operator= (const QHttpRequestHeader & header)
Copies the content of header into this QHttpRequestHeader.
Definition at line 1317 of file qhttp.cpp.
 {
     Q_D(QHttpRequestHeader);
     QHttpHeader::operator=(header);
     d->m = header.d_func()->m;
     d->p = header.d_func()->p;
     d->majVer = header.d_func()->majVer;
     d->minVer = header.d_func()->minVer;
     return *this;
 }
parseLine()
bool QHttpRequestHeader::parseLine (const QString & line, int number) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QHttpHeader.
Definition at line 1405 of file qhttp.cpp.
 {
     Q_D(QHttpRequestHeader);
     if (number != 0)
         return QHttpHeader::parseLine(line, number);
     QStringList lst = line.simplified().split(QLatin1String(" "));
     if (lst.count() > 0) {
         d->m = lst[0];
         if (lst.count() > 1) {
             d->p = lst[1];
             if (lst.count() > 2) {
                 QString v = lst[2];
                 if (v.length() >= 8 && v.left(5) == QLatin1String("HTTP/") &&
                     v[5].isDigit() && v[6] == QLatin1Char('.') && v[7].isDigit()) {
                     d->majVer = v[5].toLatin1() - '0';
                     d->minVer = v[7].toLatin1() - '0';
                     return true;
                 }
             }
         }
     }
     return false;
 }
path()
QString QHttpRequestHeader::path () const
Returns the request-URI of the HTTP request header.
See also
method() majorVersion() minorVersion() setRequest()
Definition at line 1375 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QHttpPrivate::addRequest(), QHttpRequestHeader(), and setRequest().
 {
     Q_D(const QHttpRequestHeader);
     return d->p;
 }
setRequest()
void QHttpRequestHeader::setRequest (const QString & method, const QString & path, int majorVer = 1, int minorVer = 1)
This function sets the request method to method, the request-URI to path and the protocol-version to majorVer and minorVer.
The path argument must be properly encoded for an HTTP request.
See also
method() path() majorVersion() minorVersion()
Definition at line 1349 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), and QHttpPrivate::addRequest().
 {
     Q_D(QHttpRequestHeader);
     setValid(true);
     d->m = method;
     d->p = path;
     d->majVer = majorVer;
     d->minVer = minorVer;
 }
toString()
QString QHttpRequestHeader::toString () const virtual
Reimplemented Function
Reimplemented from QHttpHeader.
Definition at line 1433 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotConnected().
 {
     Q_D(const QHttpRequestHeader);
     QString first(QLatin1String("%1 %2"));
     QString last(QLatin1String(" HTTP/%3.%4\r\n%5\r\n"));
     return first.arg(d->m).arg(d->p) +
         last.arg(d->majVer).arg(d->minVer).arg(QHttpHeader::toString());
 }
The documentation for this class was generated from the following files:
/src/network/access/qhttp.h
/src/network/access/qhttp.cpp