Qt 4.8: QGraphicsView Class Reference
QGraphicsView Class Reference
The QGraphicsView class provides a widget for displaying the contents of a QGraphicsScene.
#include <qgraphicsview.h>
Public Types
enum CacheModeFlag { CacheNone = 0x0, CacheBackground = 0x1 }
This enum describes the flags that you can set for a QGraphicsView's cache mode.
enum DragMode { NoDrag, ScrollHandDrag, RubberBandDrag }
This enum describes the default action for the view when pressing and dragging the mouse over the viewport.
enum OptimizationFlag { DontClipPainter = 0x1, DontSavePainterState = 0x2, DontAdjustForAntialiasing = 0x4, IndirectPainting = 0x8 }
This enum describes flags that you can enable to improve rendering performance in QGraphicsView.
enum ViewportAnchor { NoAnchor, AnchorViewCenter, AnchorUnderMouse }
This enums describe the possible anchors that QGraphicsView can use when the user resizes the view or when the view is transformed.
enum ViewportUpdateMode {
FullViewportUpdate, MinimalViewportUpdate, SmartViewportUpdate, NoViewportUpdate,
BoundingRectViewportUpdate
}
This enum describes how QGraphicsView updates its viewport when the scene contents change or are exposed.
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void invalidateScene (const QRectF &rect=QRectF(), QGraphicsScene::SceneLayers layers=QGraphicsScene::AllLayers)
Invalidates and schedules a redraw of layers inside rect.
void updateScene (const QList< QRectF > &rects)
Schedules an update of the scene rectangles rects.
void updateSceneRect (const QRectF &rect)
Notifies QGraphicsView that the scene's scene rect has changed.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
Qt::Alignment alignment () const
QBrush backgroundBrush () const
CacheMode cacheMode () const
void centerOn (const QPointF &pos)
Scrolls the contents of the viewport to ensure that the scene coordinate pos, is centered in the view.
void centerOn (qreal x, qreal y)
This function is provided for convenience.
void centerOn (const QGraphicsItem *item)
Scrolls the contents of the viewport to ensure that item is centered in the view.
DragMode dragMode () const
void ensureVisible (const QRectF &rect, int xmargin=50, int ymargin=50)
Scrolls the contents of the viewport so that the scene rectangle rect is visible, with margins specified in pixels by xmargin and ymargin.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This function is provided for convenience.
void ensureVisible (const QGraphicsItem *item, int xmargin=50, int ymargin=50)
Scrolls the contents of the viewport so that the center of item item is visible, with margins specified in pixels by xmargin and ymargin.
void fitInView (const QRectF &rect, Qt::AspectRatioMode aspectRadioMode=Qt::IgnoreAspectRatio)
Scales the view matrix and scrolls the scroll bars to ensure that the scene rectangle rect fits inside the viewport.
void fitInView (qreal x, qreal y, qreal w, qreal h, Qt::AspectRatioMode aspectRadioMode=Qt::IgnoreAspectRatio)
void fitInView (const QGraphicsItem *item, Qt::AspectRatioMode aspectRadioMode=Qt::IgnoreAspectRatio)
Ensures that item fits tightly inside the view, scaling the view according to aspectRatioMode.
QBrush foregroundBrush () const
QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
bool isInteractive () const
bool isTransformed () const
Returns true if the view is transformed (i.
QGraphicsItem * itemAt (const QPoint &pos) const
Returns the item at position pos, which is in viewport coordinates.
QGraphicsItem * itemAt (int x, int y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This function is provided for convenience.
QList< QGraphicsItem * > items () const
Returns a list of all the items in the associated scene, in descending stacking order (i.e., the first item in the returned list is the uppermost item).
QList< QGraphicsItem * > items (const QPoint &pos) const
Returns a list of all the items at the position pos in the view.
QList< QGraphicsItem * > items (int x, int y) const
This function is provided for convenience.
QList< QGraphicsItem * > items (const QRect &rect, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with rect.
QList< QGraphicsItem * > items (int x, int y, int w, int h, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
QList< QGraphicsItem * > items (const QPolygon &polygon, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with polygon.
QList< QGraphicsItem * > items (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with path.
QPoint mapFromScene (const QPointF &point) const
Returns the scene coordinate point to viewport coordinates.
QPolygon mapFromScene (const QRectF &rect) const
Returns the scene rectangle rect to a viewport coordinate polygon.
QPolygon mapFromScene (const QPolygonF &polygon) const
Returns the scene coordinate polygon polygon to a viewport coordinate polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Returns the scene coordinate painter path path to a viewport coordinate painter path.
QPoint mapFromScene (qreal x, qreal y) const
This function is provided for convenience.
QPolygon mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This function is provided for convenience.
QPointF mapToScene (const QPoint &point) const
Returns the viewport coordinate point mapped to scene coordinates.
QPolygonF mapToScene (const QRect &rect) const
Returns the viewport rectangle rect mapped to a scene coordinate polygon.
QPolygonF mapToScene (const QPolygon &polygon) const
Returns the viewport polygon polygon mapped to a scene coordinate polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Returns the viewport painter path path mapped to a scene coordinate painter path.
QPointF mapToScene (int x, int y) const
This function is provided for convenience.
QPolygonF mapToScene (int x, int y, int w, int h) const
This function is provided for convenience.
QMatrix matrix () const
Returns the current transformation matrix for the view.
OptimizationFlags optimizationFlags () const
QGraphicsView (QWidget *parent=0)
Constructs a QGraphicsView.
QGraphicsView (QGraphicsScene *scene, QWidget *parent=0)
Constructs a QGraphicsView and sets the visualized scene to scene.
void render (QPainter *painter, const QRectF &target=QRectF(), const QRect &source=QRect(), Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio)
Renders the source rect, which is in view coordinates, from the scene into target, which is in paint device coordinates, using painter.
QPainter::RenderHints renderHints () const
void resetCachedContent ()
Resets any cached content.
void resetMatrix ()
Resets the view transformation matrix to the identity matrix.
void resetTransform ()
Resets the view transformation to the identity matrix.
ViewportAnchor resizeAnchor () const
void rotate (qreal angle)
Rotates the current view transformation angle degrees clockwise.
Qt::ItemSelectionMode rubberBandSelectionMode () const
void scale (qreal sx, qreal sy)
Scales the current view transformation by (sx, sy).
QGraphicsScene * scene () const
Returns a pointer to the scene that is currently visualized in the view.
QRectF sceneRect () const
void setAlignment (Qt::Alignment alignment)
void setBackgroundBrush (const QBrush &brush)
void setCacheMode (CacheMode mode)
void setDragMode (DragMode mode)
void setForegroundBrush (const QBrush &brush)
void setInteractive (bool allowed)
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the view's current transformation matrix to matrix.
void setOptimizationFlag (OptimizationFlag flag, bool enabled=true)
Enables flag if enabled is true; otherwise disables flag.
void setOptimizationFlags (OptimizationFlags flags)
void setRenderHint (QPainter::RenderHint hint, bool enabled=true)
If enabled is true, the render hint hint is enabled; otherwise it is disabled.
void setRenderHints (QPainter::RenderHints hints)
void setResizeAnchor (ViewportAnchor anchor)
void setRubberBandSelectionMode (Qt::ItemSelectionMode mode)
void setScene (QGraphicsScene *scene)
Sets the current scene to scene.
void setSceneRect (const QRectF &rect)
void setSceneRect (qreal x, qreal y, qreal w, qreal h)
void setTransform (const QTransform &matrix, bool combine=false)
Sets the view's current transformation matrix to matrix.
void setTransformationAnchor (ViewportAnchor anchor)
void setViewportUpdateMode (ViewportUpdateMode mode)
void shear (qreal sh, qreal sv)
Shears the current view transformation by (sh, sv).
QSize sizeHint () const
Reimplemented Function
QTransform transform () const
Returns the current transformation matrix for the view.
ViewportAnchor transformationAnchor () const
void translate (qreal dx, qreal dy)
Translates the current view transformation by (dx, dy).
QTransform viewportTransform () const
Returns a matrix that maps viewport coordinates to scene coordinates.
ViewportUpdateMode viewportUpdateMode () const
~QGraphicsView ()
Destructs the QGraphicsView object.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void setupViewport (QWidget *widget)
This slot is called by QAbstractScrollArea after setViewport() has been called.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void contextMenuEvent (QContextMenuEvent *event)
Reimplemented Function
void dragEnterEvent (QDragEnterEvent *event)
Reimplemented Function
void dragLeaveEvent (QDragLeaveEvent *event)
Reimplemented Function
void dragMoveEvent (QDragMoveEvent *event)
Reimplemented Function
virtual void drawBackground (QPainter *painter, const QRectF &rect)
Draws the background of the scene using painter, before any items and the foreground are drawn.
virtual void drawForeground (QPainter *painter, const QRectF &rect)
Draws the foreground of the scene using painter, after the background and all items are drawn.
virtual void drawItems (QPainter *painter, int numItems, QGraphicsItem *items[], const QStyleOptionGraphicsItem options[])
Draws the items items in the scene using painter, after the background and before the foreground are drawn.
void dropEvent (QDropEvent *event)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *event)
Reimplemented Function
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void keyReleaseEvent (QKeyEvent *event)
Reimplemented Function
void mouseDoubleClickEvent (QMouseEvent *event)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
void paintEvent (QPaintEvent *event)
Reimplemented Function
QGraphicsView (QGraphicsViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
Reimplemented Function
void showEvent (QShowEvent *event)
Reimplemented Function
bool viewportEvent (QEvent *event)
Reimplemented Function
void wheelEvent (QWheelEvent *event)
Reimplemented Function
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
Qt::Alignment alignment
the alignment of the scene in the view when the whole scene is visible.
QBrush backgroundBrush
the background brush of the scene.
CacheMode cacheMode
which parts of the view are cached
DragMode dragMode
the behavior for dragging the mouse over the scene while the left mouse button is pressed.
QBrush foregroundBrush
the foreground brush of the scene.
bool interactive
whether the view allowed scene interaction.
OptimizationFlags optimizationFlags
flags that can be used to tune QGraphicsView's performance.
QPainter::RenderHints renderHints
the default render hints for the view
ViewportAnchor resizeAnchor
how the view should position the scene when the view is resized.
Qt::ItemSelectionMode rubberBandSelectionMode
the behavior for selecting items with a rubber band selection rectangle.
QRectF sceneRect
the area of the scene visualized by this view.
ViewportAnchor transformationAnchor
how the view should position the scene during transformations.
ViewportUpdateMode viewportUpdateMode
how the viewport should update its contents.
Friends
class QGraphicsItemPrivate
class QGraphicsScene
class QGraphicsScenePrivate
class QGraphicsSceneWidget
Additional Inherited Members
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QGraphicsView class provides a widget for displaying the contents of a QGraphicsScene.
Since
4.2
QGraphicsView visualizes the contents of a QGraphicsScene in a scrollable viewport. To create a scene with geometrical items, see QGraphicsScene's documentation. QGraphicsView is part of the Graphics View Framework.
To visualize a scene, you start by constructing a QGraphicsView object, passing the address of the scene you want to visualize to QGraphicsView's constructor. Alternatively, you can call setScene() to set the scene at a later point. After you call show(), the view will by default scroll to the center of the scene and display any items that are visible at this point. For example:
QGraphicsScene scene;
scene.addText("Hello, world!");
QGraphicsView view(&scene);
view.show();
You can explicitly scroll to any position on the scene by using the scroll bars, or by calling centerOn(). By passing a point to centerOn(), QGraphicsView will scroll its viewport to ensure that the point is centered in the view. An overload is provided for scrolling to a QGraphicsItem, in which case QGraphicsView will see to that the center of the item is centered in the view. If all you want is to ensure that a certain area is visible, (but not necessarily centered,) you can call ensureVisible() instead.
QGraphicsView can be used to visualize a whole scene, or only parts of it. The visualized area is by default detected automatically when the view is displayed for the first time (by calling QGraphicsScene::itemsBoundingRect()). To set the visualized area rectangle yourself, you can call setSceneRect(). This will adjust the scroll bars' ranges appropriately. Note that although the scene supports a virtually unlimited size, the range of the scroll bars will never exceed the range of an integer (INT_MIN, INT_MAX).
QGraphicsView visualizes the scene by calling render(). By default, the items are drawn onto the viewport by using a regular QPainter, and using default render hints. To change the default render hints that QGraphicsView passes to QPainter when painting items, you can call setRenderHints().
By default, QGraphicsView provides a regular QWidget for the viewport widget. You can access this widget by calling viewport(), or you can replace it by calling setViewport(). To render using OpenGL, simply call setViewport(new QGLWidget). QGraphicsView takes ownership of the viewport widget.
QGraphicsView supports affine transformations, using QTransform. You can either pass a matrix to setTransform(), or you can call one of the convenience functions rotate(), scale(), translate() or shear(). The most two common transformations are scaling, which is used to implement zooming, and rotation. QGraphicsView keeps the center of the view fixed during a transformation. Because of the scene alignment (setAligment()), translating the view will have no visual impact.
You can interact with the items on the scene by using the mouse and keyboard. QGraphicsView translates the mouse and key events into scene events, (events that inherit QGraphicsSceneEvent,), and forward them to the visualized scene. In the end, it's the individual item that handles the events and reacts to them. For example, if you click on a selectable item, the item will typically let the scene know that it has been selected, and it will also redraw itself to display a selection rectangle. Similiary, if you click and drag the mouse to move a movable item, it's the item that handles the mouse moves and moves itself. Item interaction is enabled by default, and you can toggle it by calling setInteractive().
You can also provide your own custom scene interaction, by creating a subclass of QGraphicsView, and reimplementing the mouse and key event handlers. To simplify how you programmatically interact with items in the view, QGraphicsView provides the mapping functions mapToScene() and mapFromScene(), and the item accessors items() and itemAt(). These functions allow you to map points, rectangles, polygons and paths between view coordinates and scene coordinates, and to find items on the scene using view coordinates.
See also
QGraphicsScene, QGraphicsItem, QGraphicsSceneEvent
Definition at line 64 of file qgraphicsview.h.
Enumerations
CacheModeFlag
enum QGraphicsView::CacheModeFlag
This enum describes the flags that you can set for a QGraphicsView's cache mode.
CacheNone All painting is done directly onto the viewport.
CacheBackground The background is cached. This affects both custom backgrounds, and backgrounds based on the backgroundBrush property. When this flag is enabled, QGraphicsView will allocate one pixmap with the full size of the viewport.
See also
cacheMode
Enumerator
CacheNone
CacheBackground
Definition at line 92 of file qgraphicsview.h.
{
         CacheNone = 0x0,
         CacheBackground = 0x1
     };
DragMode
enum QGraphicsView::DragMode
This enum describes the default action for the view when pressing and dragging the mouse over the viewport.
NoDrag Nothing happens; the mouse event is ignored.
ScrollHandDrag The cursor changes into a pointing hand, and dragging the mouse around will scroll the scrolbars. This mode works both in interactive and non-interactive mode.
RubberBandDrag A rubber band will appear. Dragging the mouse will set the rubber band geometry, and all items covered by the rubber band are selected. This mode is disabled for non-interactive views.
See also
dragMode, QGraphicsScene::setSelectionArea()
Enumerator
NoDrag
ScrollHandDrag
RubberBandDrag
Definition at line 98 of file qgraphicsview.h.
                   {
         NoDrag,
         ScrollHandDrag,
         RubberBandDrag
     };
OptimizationFlag
enum QGraphicsView::OptimizationFlag
This enum describes flags that you can enable to improve rendering performance in QGraphicsView.
Since
4.3
By default, none of these flags are set. Note that setting a flag usually imposes a side effect, and this effect can vary between paint devices and platforms.
DontClipPainter This value is obsolete and has no effect.
DontSavePainterState When rendering, QGraphicsView protects the painter state (see QPainter::save()) when rendering the background or foreground, and when rendering each item. This allows you to leave the painter in an altered state (i.e., you can call QPainter::setPen() or QPainter::setBrush() without restoring the state after painting). However, if the items consistently do restore the state, you should enable this flag to prevent QGraphicsView from doing the same.
DontAdjustForAntialiasing Disables QGraphicsView's antialiasing auto-adjustment of exposed areas. Items that render antialiased lines on the boundaries of their QGraphicsItem::boundingRect() can end up rendering parts of the line outside. To prevent rendering artifacts, QGraphicsView expands all exposed regions by 2 pixels in all directions. If you enable this flag, QGraphicsView will no longer perform these adjustments, minimizing the areas that require redrawing, which improves performance. A common side effect is that items that do draw with antialiasing can leave painting traces behind on the scene as they are moved.
IndirectPainting Since Qt 4.6, restore the old painting algorithm that calls QGraphicsView::drawItems() and QGraphicsScene::drawItems(). To be used only for compatibility with old code.
Enumerator
DontClipPainter
DontSavePainterState
DontAdjustForAntialiasing
IndirectPainting
Definition at line 112 of file qgraphicsview.h.
{
         DontClipPainter = 0x1, // obsolete
         DontSavePainterState = 0x2,
         DontAdjustForAntialiasing = 0x4,
         IndirectPainting = 0x8
     };
ViewportAnchor
enum QGraphicsView::ViewportAnchor
This enums describe the possible anchors that QGraphicsView can use when the user resizes the view or when the view is transformed.
NoAnchor No anchor, i.e. the view leaves the scene's position unchanged.
AnchorViewCenter The scene point at the center of the view is used as the anchor.
AnchorUnderMouse The point under the mouse is used as the anchor.
See also
resizeAnchor, transformationAnchor
Enumerator
NoAnchor
AnchorViewCenter
AnchorUnderMouse
Definition at line 86 of file qgraphicsview.h.
{
         NoAnchor,
         AnchorViewCenter,
         AnchorUnderMouse
     };
ViewportUpdateMode
enum QGraphicsView::ViewportUpdateMode
This enum describes how QGraphicsView updates its viewport when the scene contents change or are exposed.
Since
4.3
FullViewportUpdate When any visible part of the scene changes or is reexposed, QGraphicsView will update the entire viewport. This approach is fastest when QGraphicsView spends more time figuring out what to draw than it would spend drawing (e.g., when very many small items are repeatedly updated). This is the preferred update mode for viewports that do not support partial updates, such as QGLWidget, and for viewports that need to disable scroll optimization.
MinimalViewportUpdate QGraphicsView will determine the minimal viewport region that requires a redraw, minimizing the time spent drawing by avoiding a redraw of areas that have not changed. This is QGraphicsView's default mode. Although this approach provides the best performance in general, if there are many small visible changes on the scene, QGraphicsView might end up spending more time finding the minimal approach than it will spend drawing.
SmartViewportUpdate QGraphicsView will attempt to find an optimal update mode by analyzing the areas that require a redraw.
BoundingRectViewportUpdate The bounding rectangle of all changes in the viewport will be redrawn. This mode has the advantage that QGraphicsView searches only one region for changes, minimizing time spent determining what needs redrawing. The disadvantage is that areas that have not changed also need to be redrawn.
NoViewportUpdate QGraphicsView will never update its viewport when the scene changes; the user is expected to control all updates. This mode disables all (potentially slow) item visibility testing in QGraphicsView, and is suitable for scenes that either require a fixed frame rate, or where the viewport is otherwise updated externally.
See also
viewportUpdateMode
Enumerator
FullViewportUpdate
MinimalViewportUpdate
SmartViewportUpdate
NoViewportUpdate
BoundingRectViewportUpdate
Definition at line 104 of file qgraphicsview.h.
{
         FullViewportUpdate,
         MinimalViewportUpdate,
         SmartViewportUpdate,
         NoViewportUpdate,
         BoundingRectViewportUpdate
     };
Constructors and Destructors
QGraphicsView() [1/3]
QGraphicsView::QGraphicsView (QWidget * parent = 0)
Constructs a QGraphicsView.
parent is passed to QWidget's constructor.
Definition at line 1141 of file qgraphicsview.cpp.
     : QAbstractScrollArea(*new QGraphicsViewPrivate, parent)
 {
     setViewport(0);
     setAcceptDrops(true);
     setBackgroundRole(QPalette::Base);
     // Investigate leaving these disabled by default.
     setAttribute(Qt::WA_InputMethodEnabled);
     viewport()->setAttribute(Qt::WA_InputMethodEnabled);
 }
QGraphicsView() [2/3]
QGraphicsView::QGraphicsView (QGraphicsScene * scene, QWidget * parent = 0)
Constructs a QGraphicsView and sets the visualized scene to scene.
parent is passed to QWidget's constructor.
Definition at line 1156 of file qgraphicsview.cpp.
     : QAbstractScrollArea(*new QGraphicsViewPrivate, parent)
 {
     setScene(scene);
     setViewport(0);
     setAcceptDrops(true);
     setBackgroundRole(QPalette::Base);
     // Investigate leaving these disabled by default.
     setAttribute(Qt::WA_InputMethodEnabled);
     viewport()->setAttribute(Qt::WA_InputMethodEnabled);
 }
~QGraphicsView()
QGraphicsView::~QGraphicsView ()
Destructs the QGraphicsView object.
Definition at line 1185 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (d->scene)
         d->scene->d_func()->views.removeAll(this);
     delete d->lastDragDropEvent;
 }
QGraphicsView() [3/3]
QGraphicsView::QGraphicsView (QGraphicsViewPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 1171 of file qgraphicsview.cpp.
   : QAbstractScrollArea(dd, parent)
 {
     setViewport(0);
     setAcceptDrops(true);
     setBackgroundRole(QPalette::Base);
     // Investigate leaving these disabled by default.
     setAttribute(Qt::WA_InputMethodEnabled);
     viewport()->setAttribute(Qt::WA_InputMethodEnabled);
 }
Functions
alignment()
Qt::Alignment QGraphicsView::alignment () const
Referenced by setAlignment(), and setRenderHint().
backgroundBrush()
QBrush QGraphicsView::backgroundBrush () const
Referenced by inputMethodQuery(), and QmlJSDebugger::ColorPickerTool::pickColor().
cacheMode()
CacheMode QGraphicsView::cacheMode () const
Referenced by setRubberBandSelectionMode().
centerOn() [1/3]
void QGraphicsView::centerOn (const QPointF & pos)
Scrolls the contents of the viewport to ensure that the scene coordinate pos, is centered in the view.
Because pos is a floating point coordinate, and the scroll bars operate on integer coordinates, the centering is only an approximation.
Note
If the item is close to or outside the border, it will be visible in the view, but not centered.
See also
ensureVisible()
Definition at line 1880 of file qgraphicsview.cpp.
Referenced by centerOn(), and fitInView().
 {
     Q_D(QGraphicsView);
     qreal width = viewport()->width();
     qreal height = viewport()->height();
     QPointF viewPoint = d->matrix.map(pos);
     QPointF oldCenterPoint = pos;
     if (!d->leftIndent) {
         if (isRightToLeft()) {
             qint64 horizontal = 0;
             horizontal += horizontalScrollBar()->minimum();
             horizontal += horizontalScrollBar()->maximum();
             horizontal -= int(viewPoint.x() - width / qreal(2.0));
             horizontalScrollBar()->setValue(horizontal);
         } else {
             horizontalScrollBar()->setValue(int(viewPoint.x() - width / qreal(2.0)));
         }
     }
     if (!d->topIndent)
         verticalScrollBar()->setValue(int(viewPoint.y() - height / qreal(2.0)));
     d->lastCenterPoint = oldCenterPoint;
 }
centerOn() [2/3]
void QGraphicsView::centerOn (qreal x, qreal y) inline
This function is provided for convenience.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
It's equivalent to calling centerOn(QPointF(x, y)).
Definition at line 289 of file qgraphicsview.h.
 { centerOn(QPointF(ax, ay)); }
centerOn() [3/3]
void QGraphicsView::centerOn (const QGraphicsItem * item)
Scrolls the contents of the viewport to ensure that item is centered in the view.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
ensureVisible()
Definition at line 1926 of file qgraphicsview.cpp.
 {
     centerOn(item->sceneBoundingRect().center());
 }
contextMenuEvent()
void QGraphicsView::contextMenuEvent (QContextMenuEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2981 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     d->mousePressViewPoint = event->pos();
     d->mousePressScenePoint = mapToScene(d->mousePressViewPoint);
     d->mousePressScreenPoint = event->globalPos();
     d->lastMouseMoveScenePoint = d->mousePressScenePoint;
     d->lastMouseMoveScreenPoint = d->mousePressScreenPoint;
     QGraphicsSceneContextMenuEvent contextEvent(QEvent::GraphicsSceneContextMenu);
     contextEvent.setWidget(viewport());
     contextEvent.setScenePos(d->mousePressScenePoint);
     contextEvent.setScreenPos(d->mousePressScreenPoint);
     contextEvent.setModifiers(event->modifiers());
     contextEvent.setReason((QGraphicsSceneContextMenuEvent::Reason)(event->reason()));
     contextEvent.setAccepted(event->isAccepted());
     QApplication::sendEvent(d->scene, &contextEvent);
     event->setAccepted(contextEvent.isAccepted());
 }
dragEnterEvent()
void QGraphicsView::dragEnterEvent (QDragEnterEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3038 of file qgraphicsview.cpp.
 {
 #ifndef QT_NO_DRAGANDDROP
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     // Disable replaying of mouse move events.
     d->useLastMouseEvent = false;
     // Generate a scene event.
     QGraphicsSceneDragDropEvent sceneEvent(QEvent::GraphicsSceneDragEnter);
     d->populateSceneDragDropEvent(&sceneEvent, event);
     // Store it for later use.
     d->storeDragDropEvent(&sceneEvent);
     // Send it to the scene.
     QApplication::sendEvent(d->scene, &sceneEvent);
     // Accept the originating event if the scene accepted the scene event.
     if (sceneEvent.isAccepted()) {
         event->setAccepted(true);
         event->setDropAction(sceneEvent.dropAction());
     }
 #else
     Q_UNUSED(event)
 #endif
 }
dragLeaveEvent()
void QGraphicsView::dragLeaveEvent (QDragLeaveEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3071 of file qgraphicsview.cpp.
 {
 #ifndef QT_NO_DRAGANDDROP
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     if (!d->lastDragDropEvent) {
         qWarning("QGraphicsView::dragLeaveEvent: drag leave received before drag enter");
         return;
     }
     // Generate a scene event.
     QGraphicsSceneDragDropEvent sceneEvent(QEvent::GraphicsSceneDragLeave);
     sceneEvent.setScenePos(d->lastDragDropEvent->scenePos());
     sceneEvent.setScreenPos(d->lastDragDropEvent->screenPos());
     sceneEvent.setButtons(d->lastDragDropEvent->buttons());
     sceneEvent.setModifiers(d->lastDragDropEvent->modifiers());
     sceneEvent.setPossibleActions(d->lastDragDropEvent->possibleActions());
     sceneEvent.setProposedAction(d->lastDragDropEvent->proposedAction());
     sceneEvent.setDropAction(d->lastDragDropEvent->dropAction());
     sceneEvent.setMimeData(d->lastDragDropEvent->mimeData());
     sceneEvent.setWidget(d->lastDragDropEvent->widget());
     sceneEvent.setSource(d->lastDragDropEvent->source());
     delete d->lastDragDropEvent;
     d->lastDragDropEvent = 0;
     // Send it to the scene.
     QApplication::sendEvent(d->scene, &sceneEvent);
     // Accept the originating event if the scene accepted the scene event.
     if (sceneEvent.isAccepted())
         event->setAccepted(true);
 #else
     Q_UNUSED(event)
 #endif
 }
dragMode()
DragMode QGraphicsView::dragMode () const
Referenced by setOptimizationFlag().
dragMoveEvent()
void QGraphicsView::dragMoveEvent (QDragMoveEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3111 of file qgraphicsview.cpp.
 {
 #ifndef QT_NO_DRAGANDDROP
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     // Generate a scene event.
     QGraphicsSceneDragDropEvent sceneEvent(QEvent::GraphicsSceneDragMove);
     d->populateSceneDragDropEvent(&sceneEvent, event);
     // Store it for later use.
     d->storeDragDropEvent(&sceneEvent);
     // Send it to the scene.
     QApplication::sendEvent(d->scene, &sceneEvent);
     // Ignore the originating event if the scene ignored the scene event.
     event->setAccepted(sceneEvent.isAccepted());
     if (sceneEvent.isAccepted())
         event->setDropAction(sceneEvent.dropAction());
 #else
     Q_UNUSED(event)
 #endif
 }
drawBackground()
void QGraphicsView::drawBackground (QPainter * painter, const QRectF & rect) protected virtual
Draws the background of the scene using painter, before any items and the foreground are drawn.
Reimplement this function to provide a custom background for this view.
If all you want is to define a color, texture or gradient for the background, you can call setBackgroundBrush() instead.
All painting is done in scene coordinates. rect is the exposed rectangle.
The default implementation fills rect using the view's backgroundBrush. If no such brush is defined (the default), the scene's drawBackground() function is called instead.
See also
drawForeground(), QGraphicsScene::drawBackground()
Definition at line 3783 of file qgraphicsview.cpp.
Referenced by paintEvent(), and render().
 {
     Q_D(QGraphicsView);
     if (d->scene && d->backgroundBrush.style() == Qt::NoBrush) {
         d->scene->drawBackground(painter, rect);
         return;
     }
     painter->fillRect(rect, d->backgroundBrush);
 }
drawForeground()
void QGraphicsView::drawForeground (QPainter * painter, const QRectF & rect) protected virtual
Draws the foreground of the scene using painter, after the background and all items are drawn.
Reimplement this function to provide a custom foreground for this view.
If all you want is to define a color, texture or gradient for the foreground, you can call setForegroundBrush() instead.
All painting is done in scene coordinates. rect is the exposed rectangle.
The default implementation fills rect using the view's foregroundBrush. If no such brush is defined (the default), the scene's drawForeground() function is called instead.
See also
drawBackground(), QGraphicsScene::drawForeground()
Definition at line 3811 of file qgraphicsview.cpp.
Referenced by paintEvent(), and render().
 {
     Q_D(QGraphicsView);
     if (d->scene && d->foregroundBrush.style() == Qt::NoBrush) {
         d->scene->drawForeground(painter, rect);
         return;
     }
     painter->fillRect(rect, d->foregroundBrush);
 }
drawItems()
void QGraphicsView::drawItems (QPainter * painter, int numItems, QGraphicsItem * items[], const QStyleOptionGraphicsItem options[]) protected virtual
Draws the items items in the scene using painter, after the background and before the foreground are drawn.
numItems is the number of items in items and options in options. options is a list of styleoptions; one for each item. Reimplement this function to provide custom item drawing for this view.
The default implementation calls the scene's drawItems() function.
Since Qt 4.6, this function is not called anymore unless the QGraphicsView::IndirectPainting flag is given as an Optimization flag.
See also
drawForeground(), drawBackground(), QGraphicsScene::drawItems()
Definition at line 3842 of file qgraphicsview.cpp.
Referenced by paintEvent(), and render().
 {
     Q_D(QGraphicsView);
     if (d->scene) {
         QWidget *widget = painter->device() == viewport() ? viewport() : 0;
         d->scene->drawItems(painter, numItems, items, options, widget);
     }
 }
dropEvent()
void QGraphicsView::dropEvent (QDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3008 of file qgraphicsview.cpp.
 {
 #ifndef QT_NO_DRAGANDDROP
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     // Generate a scene event.
     QGraphicsSceneDragDropEvent sceneEvent(QEvent::GraphicsSceneDrop);
     d->populateSceneDragDropEvent(&sceneEvent, event);
     // Send it to the scene.
     QApplication::sendEvent(d->scene, &sceneEvent);
     // Accept the originating event if the scene accepted the scene event.
     event->setAccepted(sceneEvent.isAccepted());
     if (sceneEvent.isAccepted())
         event->setDropAction(sceneEvent.dropAction());
     delete d->lastDragDropEvent;
     d->lastDragDropEvent = 0;
 #else
     Q_UNUSED(event)
 #endif
 }
ensureVisible() [1/3]
void QGraphicsView::ensureVisible (const QRectF & rect, int xmargin = 50, int ymargin = 50)
Scrolls the contents of the viewport so that the scene rectangle rect is visible, with margins specified in pixels by xmargin and ymargin.
If the specified rect cannot be reached, the contents are scrolled to the nearest valid position. The default value for both margins is 50 pixels.
See also
centerOn()
Definition at line 1940 of file qgraphicsview.cpp.
Referenced by ensureVisible(), and QGraphicsItem::ensureVisible().
 {
     Q_D(QGraphicsView);
     qreal width = viewport()->width();
     qreal height = viewport()->height();
     QRectF viewRect = d->matrix.mapRect(rect);
     qreal left = d->horizontalScroll();
     qreal right = left + width;
     qreal top = d->verticalScroll();
     qreal bottom = top + height;
     if (viewRect.left() <= left + xmargin) {
         // need to scroll from the left
         if (!d->leftIndent)
             horizontalScrollBar()->setValue(int(viewRect.left() - xmargin - qreal(0.5)));
     }
     if (viewRect.right() >= right - xmargin) {
         // need to scroll from the right
         if (!d->leftIndent)
             horizontalScrollBar()->setValue(int(viewRect.right() - width + xmargin + qreal(0.5)));
     }
     if (viewRect.top() <= top + ymargin) {
         // need to scroll from the top
         if (!d->topIndent)
             verticalScrollBar()->setValue(int(viewRect.top() - ymargin - qreal(0.5)));
     }
     if (viewRect.bottom() >= bottom - ymargin) {
         // need to scroll from the bottom
         if (!d->topIndent)
             verticalScrollBar()->setValue(int(viewRect.bottom() - height + ymargin + qreal(0.5)));
     }
 }
ensureVisible() [2/3]
void QGraphicsView::ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin = 50, int ymargin = 50) inline
This function is provided for convenience.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
It's equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin).
Definition at line 291 of file qgraphicsview.h.
 { ensureVisible(QRectF(ax, ay, aw, ah), xmargin, ymargin); }
ensureVisible() [3/3]
void QGraphicsView::ensureVisible (const QGraphicsItem * item, int xmargin = 50, int ymargin = 50)
Scrolls the contents of the viewport so that the center of item item is visible, with margins specified in pixels by xmargin and ymargin.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the specified point cannot be reached, the contents are scrolled to the nearest valid position. The default value for both margins is 50 pixels.
See also
centerOn()
Definition at line 1999 of file qgraphicsview.cpp.
 {
     ensureVisible(item->sceneBoundingRect(), xmargin, ymargin);
 }
event()
bool QGraphicsView::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2813 of file qgraphicsview.cpp.
Referenced by viewportEvent().
 {
     Q_D(QGraphicsView);
     if (d->sceneInteractionAllowed) {
         switch (event->type()) {
         case QEvent::ShortcutOverride:
             if (d->scene)
                 return QApplication::sendEvent(d->scene, event);
             break;
         case QEvent::KeyPress:
             if (d->scene) {
                 QKeyEvent *k = static_cast<QKeyEvent *>(event);
                 if (k->key() == Qt::Key_Tab || k->key() == Qt::Key_Backtab) {
                     // Send the key events to the scene. This will invoke the
                     // scene's tab focus handling, and if the event is
                     // accepted, we return (prevent further event delivery),
                     // and the base implementation will call QGraphicsView's
                     // focusNextPrevChild() function. If the event is ignored,
                     // we fall back to standard tab focus handling.
                     QApplication::sendEvent(d->scene, event);
                     if (event->isAccepted())
                         return true;
                     // Ensure the event doesn't propagate just because the
                     // scene ignored it. If the event propagates, then tab
                     // handling will be called twice (this and parent).
                     event->accept();
                 }
             }
             break;
         default:
             break;
         }
     }
     return QAbstractScrollArea::event(event);
 }
fitInView() [1/3]
void QGraphicsView::fitInView (const QRectF & rect, Qt::AspectRatioMode aspectRatioMode = Qt::IgnoreAspectRatio)
Scales the view matrix and scrolls the scroll bars to ensure that the scene rectangle rect fits inside the viewport.
rect must be inside the scene rect; otherwise, fitInView() cannot guarantee that the whole rect is visible.
This function keeps the view's rotation, translation, or shear. The view is scaled according to aspectRatioMode. rect will be centered in the view if it does not fit tightly.
It's common to call fitInView() from inside a reimplementation of resizeEvent(), to ensure that the whole scene, or parts of the scene, scales automatically to fit the new size of the viewport as the view is resized. Note though, that calling fitInView() from inside resizeEvent() can lead to unwanted resize recursion, if the new transformation toggles the automatic state of the scrollbars. You can toggle the scrollbar policies to always on or always off to prevent this (see horizontalScrollBarPolicy() and verticalScrollBarPolicy()).
If rect is empty, or if the viewport is too small, this function will do nothing.
See also
setTransform(), ensureVisible(), centerOn()
Definition at line 2028 of file qgraphicsview.cpp.
Referenced by fitInView().
 {
     Q_D(QGraphicsView);
     if (!d->scene || rect.isNull())
         return;
     // Reset the view scale to 1:1.
     QRectF unity = d->matrix.mapRect(QRectF(0, 0, 1, 1));
     if (unity.isEmpty())
         return;
     scale(1 / unity.width(), 1 / unity.height());
     // Find the ideal x / y scaling ratio to fit \a rect in the view.
     int margin = 2;
     QRectF viewRect = viewport()->rect().adjusted(margin, margin, -margin, -margin);
     if (viewRect.isEmpty())
         return;
     QRectF sceneRect = d->matrix.mapRect(rect);
     if (sceneRect.isEmpty())
         return;
     qreal xratio = viewRect.width() / sceneRect.width();
     qreal yratio = viewRect.height() / sceneRect.height();
     // Respect the aspect ratio mode.
     switch (aspectRatioMode) {
     case Qt::KeepAspectRatio:
         xratio = yratio = qMin(xratio, yratio);
         break;
     case Qt::KeepAspectRatioByExpanding:
         xratio = yratio = qMax(xratio, yratio);
         break;
     case Qt::IgnoreAspectRatio:
         break;
     }
     // Scale and center on the center of \a rect.
     scale(xratio, yratio);
     centerOn(rect.center());
 }
fitInView() [2/3]
void QGraphicsView::fitInView (qreal x, qreal y, qreal w, qreal h, Qt::AspectRatioMode aspectRadioMode = Qt::IgnoreAspectRatio) inline
Definition at line 293 of file qgraphicsview.h.
 { fitInView(QRectF(ax, ay, w, h), mode); }
fitInView() [3/3]
void QGraphicsView::fitInView (const QGraphicsItem * item, Qt::AspectRatioMode aspectRatioMode = Qt::IgnoreAspectRatio)
Ensures that item fits tightly inside the view, scaling the view according to aspectRatioMode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
ensureVisible(), centerOn()
Definition at line 2094 of file qgraphicsview.cpp.
 {
     QPainterPath path = item->isClipped() ? item->clipPath() : item->shape();
     if (item->d_ptr->hasTranslateOnlySceneTransform()) {
         path.translate(item->d_ptr->sceneTransform.dx(), item->d_ptr->sceneTransform.dy());
         fitInView(path.boundingRect(), aspectRatioMode);
     } else {
         fitInView(item->d_ptr->sceneTransform.map(path).boundingRect(), aspectRatioMode);
     }
 }
focusInEvent()
void QGraphicsView::focusInEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3140 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->updateInputMethodSensitivity();
     QAbstractScrollArea::focusInEvent(event);
     if (d->scene)
         QApplication::sendEvent(d->scene, event);
     // Pass focus on if the scene cannot accept focus.
     if (!d->scene || !event->isAccepted())
         QAbstractScrollArea::focusInEvent(event);
 }
focusNextPrevChild()
bool QGraphicsView::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3155 of file qgraphicsview.cpp.
 {
     return QAbstractScrollArea::focusNextPrevChild(next);
 }
focusOutEvent()
void QGraphicsView::focusOutEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3163 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     QAbstractScrollArea::focusOutEvent(event);
     if (d->scene)
         QApplication::sendEvent(d->scene, event);
 }
foregroundBrush()
QBrush QGraphicsView::foregroundBrush () const
Referenced by setBackgroundBrush().
inputMethodEvent()
void QGraphicsView::inputMethodEvent (QInputMethodEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3759 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (d->scene)
         QApplication::sendEvent(d->scene, event);
 }
inputMethodQuery()
QVariant QGraphicsView::inputMethodQuery (Qt::InputMethodQuery query) const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2590 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return QVariant();
     QVariant value = d->scene->inputMethodQuery(query);
     if (value.type() == QVariant::RectF)
         value = d->mapRectFromScene(value.toRectF());
     else if (value.type() == QVariant::PointF)
         value = mapFromScene(value.toPointF());
     else if (value.type() == QVariant::Rect)
         value = d->mapRectFromScene(value.toRect()).toRect();
     else if (value.type() == QVariant::Point)
         value = mapFromScene(value.toPoint());
     return value;
 }
invalidateScene
void QGraphicsView::invalidateScene (const QRectF & rect = QRectF(), QGraphicsScene::SceneLayers layers = QGraphicsScene::AllLayers) slot
Invalidates and schedules a redraw of layers inside rect.
rect is in scene coordinates. Any cached content for layers inside rect is unconditionally invalidated and redrawn.
You can call this function to notify QGraphicsView of changes to the background or the foreground of the scene. It is commonly used for scenes with tile-based backgrounds to notify changes when QGraphicsView has enabled background caching.
Note that QGraphicsView currently supports background caching only (see QGraphicsView::CacheBackground). This function is equivalent to calling update() if any layer but QGraphicsScene::BackgroundLayer is passed.
See also
QGraphicsScene::invalidate(), update()
Definition at line 1601 of file qgraphicsview.cpp.
Referenced by QGraphicsScene::invalidate().
 {
     Q_D(QGraphicsView);
     if ((layers & QGraphicsScene::BackgroundLayer) && !d->mustResizeBackgroundPixmap) {
         QRect viewRect = mapFromScene(rect).boundingRect();
         if (viewport()->rect().intersects(viewRect)) {
             // The updated background area is exposed; schedule this area for
             // redrawing.
             d->backgroundPixmapExposed += viewRect;
             if (d->scene)
                 d->scene->update(rect);
         }
     }
 }
isInteractive()
bool QGraphicsView::isInteractive () const
Definition at line 1629 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     return d->sceneInteractionAllowed;
 }
isTransformed()
bool QGraphicsView::isTransformed () const
Returns true if the view is transformed (i.
Since
4.6
e., a non-identity transform has been assigned, or the scrollbars are adjusted).
See also
setTransform(), horizontalScrollBar(), verticalScrollBar()
Definition at line 3888 of file qgraphicsview.cpp.
Referenced by QGraphicsScenePrivate::itemsAtPosition(), paintEvent(), QGraphicsScene::update(), and updateHelper().
 {
     Q_D(const QGraphicsView);
     return !d->identityMatrix || d->horizontalScroll() || d->verticalScroll();
 }
itemAt() [1/2]
QGraphicsItem * QGraphicsView::itemAt (const QPoint & pos) const
Returns the item at position pos, which is in viewport coordinates.
If there are several items at this position, this function returns the topmost item.
Example:
void CustomView::mousePressEvent(QMouseEvent *event)
{
    if (QGraphicsItem *item = itemAt(event->pos())) {
        qDebug() << "You clicked on item" << item;
    } else {
        qDebug() << "You didn't click on an item.";
    }
}
See also
items(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 2368 of file qgraphicsview.cpp.
Referenced by QGraphicsItem::unsetCursor().
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return 0;
     QList<QGraphicsItem *> itemsAtPos = items(pos);
     return itemsAtPos.isEmpty() ? 0 : itemsAtPos.first();
 }
itemAt() [2/2]
QGraphicsItem * QGraphicsView::itemAt (int x, int y) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This function is provided for convenience.
It's equivalent to calling itemAt(QPoint(x, y)).
Definition at line 299 of file qgraphicsview.h.
 { return itemAt(QPoint(ax, ay)); }
items() [1/7]
QList< QGraphicsItem * > QGraphicsView::items () const
Returns a list of all the items in the associated scene, in descending stacking order (i.e., the first item in the returned list is the uppermost item).
See also
QGraphicsScene::items(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 2219 of file qgraphicsview.cpp.
Referenced by itemAt(), QGraphicsScenePrivate::itemsAtPosition(), and QGraphicsItem::setCursor().
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return QList<QGraphicsItem *>();
     return d->scene->items();
 }
items() [2/7]
QList< QGraphicsItem * > QGraphicsView::items (const QPoint & pos) const
Returns a list of all the items at the position pos in the view.
The items are listed in descending stacking order (i.e., the first item in the list is the uppermost item, and the last item is the lowermost item). pos is in viewport coordinates.
This function is most commonly called from within mouse event handlers in a subclass in QGraphicsView. pos is in untransformed viewport coordinates, just like QMouseEvent::pos().
void CustomView::mousePressEvent(QMouseEvent *event)
{
    qDebug() << "There are" << items(event->pos()).size()
             << "items at position" << mapToScene(event->pos());
}
See also
QGraphicsScene::items(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 2241 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return QList<QGraphicsItem *>();
     // ### Unify these two, and use the items(QPointF) version in
     // QGraphicsScene instead. The scene items function could use the viewport
     // transform to map the point to a rect/polygon.
     if ((d->identityMatrix || d->matrix.type() <= QTransform::TxScale)) {
         // Use the rect version
         QTransform xinv = viewportTransform().inverted();
         return d->scene->items(xinv.mapRect(QRectF(pos.x(), pos.y(), 1, 1)),
                                Qt::IntersectsItemShape,
                                Qt::DescendingOrder,
                                viewportTransform());
     }
     // Use the polygon version
     return d->scene->items(mapToScene(pos.x(), pos.y(), 1, 1),
                            Qt::IntersectsItemShape,
                            Qt::DescendingOrder,
                            viewportTransform());
 }
items() [3/7]
QList< QGraphicsItem * > QGraphicsView::items (int x, int y) const inline
This function is provided for convenience.
It's equivalent to calling items(QPoint(x, y)).
Definition at line 295 of file qgraphicsview.h.
 { return items(QPoint(ax, ay)); }
items() [4/7]
QList< QGraphicsItem * > QGraphicsView::items (const QRect & rect, Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with rect.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
rect is in viewport coordinates.
The default value for mode is Qt::IntersectsItemShape; all items whose exact shape intersects with or is contained by rect are returned.
The items are sorted in descending stacking order (i.e., the first item in the returned list is the uppermost item).
See also
itemAt(), items(), mapToScene(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 2292 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return QList<QGraphicsItem *>();
     return d->scene->items(mapToScene(rect), mode, Qt::DescendingOrder, viewportTransform());
 }
items() [5/7]
QList< QGraphicsItem * > QGraphicsView::items (int x, int y, int w, int h, Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const inline
Since
4.3
This convenience function is equivalent to calling items(QRectF(x, y, w, h), mode).
Definition at line 297 of file qgraphicsview.h.
 { return items(QRect(ax, ay, w, h), mode); }
items() [6/7]
QList< QGraphicsItem * > QGraphicsView::items (const QPolygon & polygon, Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with polygon.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
polygon is in viewport coordinates.
The default value for mode is Qt::IntersectsItemShape; all items whose exact shape intersects with or is contained by polygon are returned.
The items are sorted by descending stacking order (i.e., the first item in the returned list is the uppermost item).
See also
itemAt(), items(), mapToScene(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 2326 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return QList<QGraphicsItem *>();
     return d->scene->items(mapToScene(polygon), mode, Qt::DescendingOrder, viewportTransform());
 }
items() [7/7]
QList< QGraphicsItem * > QGraphicsView::items (const QPainterPath & path, Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with path.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
path is in viewport coordinates.
The default value for mode is Qt::IntersectsItemShape; all items whose exact shape intersects with or is contained by path are returned.
See also
itemAt(), items(), mapToScene(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 2349 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (!d->scene)
         return QList<QGraphicsItem *>();
     return d->scene->items(mapToScene(path), mode, Qt::DescendingOrder, viewportTransform());
 }
keyPressEvent()
void QGraphicsView::keyPressEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3174 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed) {
         QAbstractScrollArea::keyPressEvent(event);
         return;
     }
     QApplication::sendEvent(d->scene, event);
     if (!event->isAccepted())
         QAbstractScrollArea::keyPressEvent(event);
 }
keyReleaseEvent()
void QGraphicsView::keyReleaseEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3189 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     QApplication::sendEvent(d->scene, event);
     if (!event->isAccepted())
         QAbstractScrollArea::keyReleaseEvent(event);
 }
mapFromScene() [1/6]
QPoint QGraphicsView::mapFromScene (const QPointF & point) const
Returns the scene coordinate point to viewport coordinates.
See also
mapToScene()
Definition at line 2491 of file qgraphicsview.cpp.
Referenced by QGraphicsItemPrivate::genericMapFromScene(), inputMethodQuery(), invalidateScene(), and mapFromScene().
 {
     Q_D(const QGraphicsView);
     QPointF p = d->identityMatrix ? point : d->matrix.map(point);
     p.rx() -= d->horizontalScroll();
     p.ry() -= d->verticalScroll();
     return p.toPoint();
 }
mapFromScene() [2/6]
QPolygon QGraphicsView::mapFromScene (const QRectF & rect) const
Returns the scene rectangle rect to a viewport coordinate polygon.
See also
mapToScene()
Definition at line 2516 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     QPointF tl;
     QPointF tr;
     QPointF br;
     QPointF bl;
     if (!d->identityMatrix) {
         const QTransform &x = d->matrix;
         tl = x.map(rect.topLeft());
         tr = x.map(rect.topRight());
         br = x.map(rect.bottomRight());
         bl = x.map(rect.bottomLeft());
     } else {
         tl = rect.topLeft();
         tr = rect.topRight();
         br = rect.bottomRight();
         bl = rect.bottomLeft();
     }
     QPointF scrollOffset(d->horizontalScroll(), d->verticalScroll());
     tl -= scrollOffset;
     tr -= scrollOffset;
     br -= scrollOffset;
     bl -= scrollOffset;
     QPolygon poly(4);
     poly[0] = tl.toPoint();
     poly[1] = tr.toPoint();
     poly[2] = br.toPoint();
     poly[3] = bl.toPoint();
     return poly;
 }
mapFromScene() [3/6]
QPolygon QGraphicsView::mapFromScene (const QPolygonF & polygon) const
Returns the scene coordinate polygon polygon to a viewport coordinate polygon.
See also
mapToScene()
Definition at line 2565 of file qgraphicsview.cpp.
 {
     QPolygon poly;
     foreach (const QPointF &point, polygon)
         poly << mapFromScene(point);
     return poly;
 }
mapFromScene() [4/6]
QPainterPath QGraphicsView::mapFromScene (const QPainterPath & path) const
Returns the scene coordinate painter path path to a viewport coordinate painter path.
See also
mapToScene()
Definition at line 2579 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     QTransform matrix = d->matrix;
     matrix *= QTransform::fromTranslate(-d->horizontalScroll(), -d->verticalScroll());
     return matrix.map(path);
 }
mapFromScene() [5/6]
QPoint QGraphicsView::mapFromScene (qreal x, qreal y) const inline
This function is provided for convenience.
It's equivalent to calling mapFromScene(QPointF(x, y)).
Definition at line 305 of file qgraphicsview.h.
 { return mapFromScene(QPointF(ax, ay)); }
mapFromScene() [6/6]
QPolygon QGraphicsView::mapFromScene (qreal x, qreal y, qreal w, qreal h) const inline
This function is provided for convenience.
It's equivalent to calling mapFromScene(QRectF(x, y, w, h)).
Definition at line 307 of file qgraphicsview.h.
 { return mapFromScene(QRectF(ax, ay, w, h)); }
mapToScene() [1/6]
QPointF QGraphicsView::mapToScene (const QPoint & point) const
Returns the viewport coordinate point mapped to scene coordinates.
Note: It can be useful to map the whole rectangle covered by the pixel at point instead of the point itself. To do this, you can call mapToScene(QRect(point, QSize(2, 2))).
See also
mapFromScene()
Definition at line 2394 of file qgraphicsview.cpp.
Referenced by contextMenuEvent(), QGraphicsItem::isUnderMouse(), items(), QGraphicsScenePrivate::leaveScene(), QGestureEvent::mapToGraphicsScene(), mapToScene(), mouseDoubleClickEvent(), QmlJSDebugger::ZoomTool::mouseMoveEvent(), mouseMoveEvent(), QmlJSDebugger::ZoomTool::mousePressEvent(), mousePressEvent(), QmlJSDebugger::ZoomTool::mouseReleaseEvent(), mouseReleaseEvent(), paintEvent(), render(), QWidgetPrivate::screenGeometry(), QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem(), viewportEvent(), and wheelEvent().
 {
     Q_D(const QGraphicsView);
     QPointF p = point;
     p.rx() += d->horizontalScroll();
     p.ry() += d->verticalScroll();
     return d->identityMatrix ? p : d->matrix.inverted().map(p);
 }
mapToScene() [2/6]
QPolygonF QGraphicsView::mapToScene (const QRect & rect) const
Returns the viewport rectangle rect mapped to a scene coordinate polygon.
See also
mapFromScene()
Definition at line 2419 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (!rect.isValid())
         return QPolygonF();
     QPointF scrollOffset(d->horizontalScroll(), d->verticalScroll());
     QRect r = rect.adjusted(0, 0, 1, 1);
     QPointF tl = scrollOffset + r.topLeft();
     QPointF tr = scrollOffset + r.topRight();
     QPointF br = scrollOffset + r.bottomRight();
     QPointF bl = scrollOffset + r.bottomLeft();
     QPolygonF poly(4);
     if (!d->identityMatrix) {
         QTransform x = d->matrix.inverted();
         poly[0] = x.map(tl);
         poly[1] = x.map(tr);
         poly[2] = x.map(br);
         poly[3] = x.map(bl);
     } else {
         poly[0] = tl;
         poly[1] = tr;
         poly[2] = br;
         poly[3] = bl;
     }
     return poly;
 }
mapToScene() [3/6]
QPolygonF QGraphicsView::mapToScene (const QPolygon & polygon) const
Returns the viewport polygon polygon mapped to a scene coordinate polygon.
See also
mapFromScene()
Definition at line 2464 of file qgraphicsview.cpp.
 {
     QPolygonF poly;
     foreach (const QPoint &point, polygon)
         poly << mapToScene(point);
     return poly;
 }
mapToScene() [4/6]
QPainterPath QGraphicsView::mapToScene (const QPainterPath & path) const
Returns the viewport painter path path mapped to a scene coordinate painter path.
See also
mapFromScene()
Definition at line 2478 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     QTransform matrix = QTransform::fromTranslate(d->horizontalScroll(), d->verticalScroll());
     matrix *= d->matrix.inverted();
     return matrix.map(path);
 }
mapToScene() [5/6]
QPointF QGraphicsView::mapToScene (int x, int y) const inline
This function is provided for convenience.
It's equivalent to calling mapToScene(QPoint(x, y)).
Definition at line 301 of file qgraphicsview.h.
 { return mapToScene(QPoint(ax, ay)); }
mapToScene() [6/6]
QPolygonF QGraphicsView::mapToScene (int x, int y, int w, int h) const inline
This function is provided for convenience.
It's equivalent to calling mapToScene(QRect(x, y, w, h)).
Definition at line 303 of file qgraphicsview.h.
 { return mapToScene(QRect(ax, ay, w, h)); }
matrix()
QMatrix QGraphicsView::matrix () const
Returns the current transformation matrix for the view.
If no current transformation is set, the identity matrix is returned.
See also
setMatrix(), transform(), rotate(), scale(), shear(), translate()
Definition at line 1769 of file qgraphicsview.cpp.
Referenced by mapFromScene(), mapToScene(), QGraphicsViewPrivate::mapToScene(), rotate(), scale(), setTransform(), shear(), and translate().
 {
     Q_D(const QGraphicsView);
     return d->matrix.toAffine();
 }
mouseDoubleClickEvent()
void QGraphicsView::mouseDoubleClickEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3202 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed)
         return;
     d->storeMouseEvent(event);
     d->mousePressViewPoint = event->pos();
     d->mousePressScenePoint = mapToScene(d->mousePressViewPoint);
     d->mousePressScreenPoint = event->globalPos();
     d->lastMouseMoveScenePoint = d->mousePressScenePoint;
     d->lastMouseMoveScreenPoint = d->mousePressScreenPoint;
     d->mousePressButton = event->button();
     QGraphicsSceneMouseEvent mouseEvent(QEvent::GraphicsSceneMouseDoubleClick);
     mouseEvent.setWidget(viewport());
     mouseEvent.setButtonDownScenePos(d->mousePressButton, d->mousePressScenePoint);
     mouseEvent.setButtonDownScreenPos(d->mousePressButton, d->mousePressScreenPoint);
     mouseEvent.setScenePos(mapToScene(d->mousePressViewPoint));
     mouseEvent.setScreenPos(d->mousePressScreenPoint);
     mouseEvent.setLastScenePos(d->lastMouseMoveScenePoint);
     mouseEvent.setLastScreenPos(d->lastMouseMoveScreenPoint);
     mouseEvent.setButtons(event->buttons());
     mouseEvent.setButtons(event->buttons());
     mouseEvent.setAccepted(false);
     mouseEvent.setButton(event->button());
     mouseEvent.setModifiers(event->modifiers());
     if (event->spontaneous())
         qt_sendSpontaneousEvent(d->scene, &mouseEvent);
     else
         QApplication::sendEvent(d->scene, &mouseEvent);
 }
mouseMoveEvent()
void QGraphicsView::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3316 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
 #ifndef QT_NO_RUBBERBAND
     if (d->dragMode == QGraphicsView::RubberBandDrag && d->sceneInteractionAllowed) {
         d->storeMouseEvent(event);
         if (d->rubberBanding) {
             // Check for enough drag distance
             if ((d->mousePressViewPoint - event->pos()).manhattanLength()
                 < QApplication::startDragDistance()) {
                 return;
             }
             // Update old rubberband
             if (d->viewportUpdateMode != QGraphicsView::NoViewportUpdate && !d->rubberBandRect.isEmpty()) {
                 if (d->viewportUpdateMode != FullViewportUpdate)
                     viewport()->update(d->rubberBandRegion(viewport(), d->rubberBandRect));
                 else
                     d->updateAll();
             }
             // Stop rubber banding if the user has let go of all buttons (even
             // if we didn't get the release events).
             if (!event->buttons()) {
                 d->rubberBanding = false;
                 d->rubberBandRect = QRect();
                 return;
             }
             // Update rubberband position
             const QPoint &mp = d->mousePressViewPoint;
             QPoint ep = event->pos();
             d->rubberBandRect = QRect(qMin(mp.x(), ep.x()), qMin(mp.y(), ep.y()),
                                       qAbs(mp.x() - ep.x()) + 1, qAbs(mp.y() - ep.y()) + 1);
             // Update new rubberband
             if (d->viewportUpdateMode != QGraphicsView::NoViewportUpdate){
                 if (d->viewportUpdateMode != FullViewportUpdate)
                     viewport()->update(d->rubberBandRegion(viewport(), d->rubberBandRect));
                 else
                     d->updateAll();
             }
             // Set the new selection area
             QPainterPath selectionArea;
             selectionArea.addPolygon(mapToScene(d->rubberBandRect));
             selectionArea.closeSubpath();
             if (d->scene)
                 d->scene->setSelectionArea(selectionArea, d->rubberBandSelectionMode,
                                            viewportTransform());
             return;
         }
     } else
 #endif // QT_NO_RUBBERBAND
     if (d->dragMode == QGraphicsView::ScrollHandDrag) {
         if (d->handScrolling) {
             QScrollBar *hBar = horizontalScrollBar();
             QScrollBar *vBar = verticalScrollBar();
             QPoint delta = event->pos() - d->lastMouseEvent.pos();
             hBar->setValue(hBar->value() + (isRightToLeft() ? delta.x() : -delta.x()));
             vBar->setValue(vBar->value() - delta.y());
             // Detect how much we've scrolled to disambiguate scrolling from
             // clicking.
             ++d->handScrollMotions;
         }
     }
     d->mouseMoveEventHandler(event);
 }
mousePressEvent()
void QGraphicsView::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3238 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     // Store this event for replaying, finding deltas, and for
     // scroll-dragging; even in non-interactive mode, scroll hand dragging is
     // allowed, so we store the event at the very top of this function.
     d->storeMouseEvent(event);
     d->lastMouseEvent.setAccepted(false);
     if (d->sceneInteractionAllowed) {
         // Store some of the event's button-down data.
         d->mousePressViewPoint = event->pos();
         d->mousePressScenePoint = mapToScene(d->mousePressViewPoint);
         d->mousePressScreenPoint = event->globalPos();
         d->lastMouseMoveScenePoint = d->mousePressScenePoint;
         d->lastMouseMoveScreenPoint = d->mousePressScreenPoint;
         d->mousePressButton = event->button();
         if (d->scene) {
             // Convert and deliver the mouse event to the scene.
             QGraphicsSceneMouseEvent mouseEvent(QEvent::GraphicsSceneMousePress);
             mouseEvent.setWidget(viewport());
             mouseEvent.setButtonDownScenePos(d->mousePressButton, d->mousePressScenePoint);
             mouseEvent.setButtonDownScreenPos(d->mousePressButton, d->mousePressScreenPoint);
             mouseEvent.setScenePos(d->mousePressScenePoint);
             mouseEvent.setScreenPos(d->mousePressScreenPoint);
             mouseEvent.setLastScenePos(d->lastMouseMoveScenePoint);
             mouseEvent.setLastScreenPos(d->lastMouseMoveScreenPoint);
             mouseEvent.setButtons(event->buttons());
             mouseEvent.setButton(event->button());
             mouseEvent.setModifiers(event->modifiers());
             mouseEvent.setAccepted(false);
             if (event->spontaneous())
                 qt_sendSpontaneousEvent(d->scene, &mouseEvent);
             else
                 QApplication::sendEvent(d->scene, &mouseEvent);
             // Update the original mouse event accepted state.
             bool isAccepted = mouseEvent.isAccepted();
             event->setAccepted(isAccepted);
             // Update the last mouse event accepted state.
             d->lastMouseEvent.setAccepted(isAccepted);
             if (isAccepted)
                 return;
         }
     }
 #ifndef QT_NO_RUBBERBAND
     if (d->dragMode == QGraphicsView::RubberBandDrag && !d->rubberBanding) {
         if (d->sceneInteractionAllowed) {
             // Rubberbanding is only allowed in interactive mode.
             event->accept();
             d->rubberBanding = true;
             d->rubberBandRect = QRect();
             if (d->scene) {
                 // Initiating a rubber band always clears the selection.
                 d->scene->clearSelection();
             }
         }
     } else
 #endif
         if (d->dragMode == QGraphicsView::ScrollHandDrag && event->button() == Qt::LeftButton) {
             // Left-button press in scroll hand mode initiates hand scrolling.
             event->accept();
             d->handScrolling = true;
             d->handScrollMotions = 0;
 #ifndef QT_NO_CURSOR
             viewport()->setCursor(Qt::ClosedHandCursor);
 #endif
         }
 }
mouseReleaseEvent()
void QGraphicsView::mouseReleaseEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3390 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
 #ifndef QT_NO_RUBBERBAND
     if (d->dragMode == QGraphicsView::RubberBandDrag && d->sceneInteractionAllowed && !event->buttons()) {
         if (d->rubberBanding) {
             if (d->viewportUpdateMode != QGraphicsView::NoViewportUpdate){
                 if (d->viewportUpdateMode != FullViewportUpdate)
                     viewport()->update(d->rubberBandRegion(viewport(), d->rubberBandRect));
                 else
                     d->updateAll();
             }
             d->rubberBanding = false;
             d->rubberBandRect = QRect();
         }
     } else
 #endif
     if (d->dragMode == QGraphicsView::ScrollHandDrag && event->button() == Qt::LeftButton) {
 #ifndef QT_NO_CURSOR
         // Restore the open hand cursor. ### There might be items
         // under the mouse that have a valid cursor at this time, so
         // we could repeat the steps from mouseMoveEvent().
         viewport()->setCursor(Qt::OpenHandCursor);
 #endif
         d->handScrolling = false;
         if (d->scene && d->sceneInteractionAllowed && !d->lastMouseEvent.isAccepted() && d->handScrollMotions <= 6) {
             // If we've detected very little motion during the hand drag, and
             // no item accepted the last event, we'll interpret that as a
             // click to the scene, and reset the selection.
             d->scene->clearSelection();
         }
     }
     d->storeMouseEvent(event);
     if (!d->sceneInteractionAllowed)
         return;
     if (!d->scene)
         return;
     QGraphicsSceneMouseEvent mouseEvent(QEvent::GraphicsSceneMouseRelease);
     mouseEvent.setWidget(viewport());
     mouseEvent.setButtonDownScenePos(d->mousePressButton, d->mousePressScenePoint);
     mouseEvent.setButtonDownScreenPos(d->mousePressButton, d->mousePressScreenPoint);
     mouseEvent.setScenePos(mapToScene(event->pos()));
     mouseEvent.setScreenPos(event->globalPos());
     mouseEvent.setLastScenePos(d->lastMouseMoveScenePoint);
     mouseEvent.setLastScreenPos(d->lastMouseMoveScreenPoint);
     mouseEvent.setButtons(event->buttons());
     mouseEvent.setButton(event->button());
     mouseEvent.setModifiers(event->modifiers());
     mouseEvent.setAccepted(false);
     if (event->spontaneous())
         qt_sendSpontaneousEvent(d->scene, &mouseEvent);
     else
         QApplication::sendEvent(d->scene, &mouseEvent);
     // Update the last mouse event selected state.
     d->lastMouseEvent.setAccepted(mouseEvent.isAccepted());
 #ifndef QT_NO_CURSOR
     if (mouseEvent.isAccepted() && mouseEvent.buttons() == 0 && viewport()->testAttribute(Qt::WA_SetCursor)) {
         // The last mouse release on the viewport will trigger clearing the cursor.
         d->_q_unsetViewportCursor();
     }
 #endif
 }
optimizationFlags()
OptimizationFlags QGraphicsView::optimizationFlags () const
Referenced by setViewportUpdateMode().
paintEvent()
void QGraphicsView::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3494 of file qgraphicsview.cpp.
Referenced by QDeclarativeView::paintEvent().
 {
     Q_D(QGraphicsView);
     if (!d->scene) {
         QAbstractScrollArea::paintEvent(event);
         return;
     }
     // Set up painter state protection.
     d->scene->d_func()->painterStateProtection = !(d->optimizationFlags & DontSavePainterState);
     // Determine the exposed region
     d->exposedRegion = event->region();
     QRectF exposedSceneRect = mapToScene(d->exposedRegion.boundingRect()).boundingRect();
     // Set up the painter
     QPainter painter(viewport());
 #ifndef QT_NO_RUBBERBAND
     if (d->rubberBanding && !d->rubberBandRect.isEmpty())
         painter.save();
 #endif
     // Set up render hints
     painter.setRenderHints(painter.renderHints(), false);
     painter.setRenderHints(d->renderHints, true);
     // Set up viewport transform
     const bool viewTransformed = isTransformed();
     if (viewTransformed)
         painter.setWorldTransform(viewportTransform());
     const QTransform viewTransform = painter.worldTransform();
     // Draw background
     if ((d->cacheMode & CacheBackground)
 #ifdef Q_WS_X11
         && X11->use_xrender
 #endif
         ) {
         // Recreate the background pixmap, and flag the whole background as
         // exposed.
         if (d->mustResizeBackgroundPixmap) {
             d->backgroundPixmap = QPixmap(viewport()->size());
             QBrush bgBrush = viewport()->palette().brush(viewport()->backgroundRole());
             if (!bgBrush.isOpaque())
                 d->backgroundPixmap.fill(Qt::transparent);
             QPainter p(&d->backgroundPixmap);
             p.fillRect(0, 0, d->backgroundPixmap.width(), d->backgroundPixmap.height(), bgBrush);
             d->backgroundPixmapExposed = QRegion(viewport()->rect());
             d->mustResizeBackgroundPixmap = false;
         }
         // Redraw exposed areas
         if (!d->backgroundPixmapExposed.isEmpty()) {
             QPainter backgroundPainter(&d->backgroundPixmap);
             backgroundPainter.setClipRegion(d->backgroundPixmapExposed, Qt::ReplaceClip);
             if (viewTransformed)
                 backgroundPainter.setTransform(viewTransform);
             QRectF backgroundExposedSceneRect = mapToScene(d->backgroundPixmapExposed.boundingRect()).boundingRect();
             drawBackground(&backgroundPainter, backgroundExposedSceneRect);
             d->backgroundPixmapExposed = QRegion();
         }
         // Blit the background from the background pixmap
         if (viewTransformed) {
             painter.setWorldTransform(QTransform());
             painter.drawPixmap(QPoint(), d->backgroundPixmap);
             painter.setWorldTransform(viewTransform);
         } else {
             painter.drawPixmap(QPoint(), d->backgroundPixmap);
         }
     } else {
         if (!(d->optimizationFlags & DontSavePainterState))
             painter.save();
         drawBackground(&painter, exposedSceneRect);
         if (!(d->optimizationFlags & DontSavePainterState))
             painter.restore();
     }
     // Items
     if (!(d->optimizationFlags & IndirectPainting)) {
         const quint32 oldRectAdjust = d->scene->d_func()->rectAdjust;
         if (d->optimizationFlags & QGraphicsView::DontAdjustForAntialiasing)
             d->scene->d_func()->rectAdjust = 1;
         else
             d->scene->d_func()->rectAdjust = 2;
         d->scene->d_func()->drawItems(&painter, viewTransformed ? &viewTransform : 0,
                                       &d->exposedRegion, viewport());
         d->scene->d_func()->rectAdjust = oldRectAdjust;
         // Make sure the painter's world transform is restored correctly when
         // drawing without painter state protection (DontSavePainterState).
         // We only change the worldTransform() so there's no need to do a full-blown
         // save() and restore(). Also note that we don't have to do this in case of
         // IndirectPainting (the else branch), because in that case we always save()
         // and restore() in QGraphicsScene::drawItems().
         if (!d->scene->d_func()->painterStateProtection)
             painter.setOpacity(1.0);
         painter.setWorldTransform(viewTransform);
     } else {
         // Make sure we don't have unpolished items before we draw
         if (!d->scene->d_func()->unpolishedItems.isEmpty())
             d->scene->d_func()->_q_polishItems();
         // We reset updateAll here (after we've issued polish events)
         // so that we can discard update requests coming from polishEvent().
         d->scene->d_func()->updateAll = false;
         // Find all exposed items
         bool allItems = false;
         QList<QGraphicsItem *> itemList = d->findItems(d->exposedRegion, &allItems, viewTransform);
         if (!itemList.isEmpty()) {
             // Generate the style options.
             const int numItems = itemList.size();
             QGraphicsItem **itemArray = &itemList[0]; // Relies on QList internals, but is perfectly valid.
             QStyleOptionGraphicsItem *styleOptionArray = d->allocStyleOptionsArray(numItems);
             QTransform transform(Qt::Uninitialized);
             for (int i = 0; i < numItems; ++i) {
                 QGraphicsItem *item = itemArray[i];
                 QGraphicsItemPrivate *itemd = item->d_ptr.data();
                 itemd->initStyleOption(&styleOptionArray[i], viewTransform, d->exposedRegion, allItems);
                 // Cache the item's area in view coordinates.
                 // Note that we have to do this here in case the base class implementation
                 // (QGraphicsScene::drawItems) is not called. If it is, we'll do this
                 // operation twice, but that's the price one has to pay for using indirect
                 // painting :-/.
                 const QRectF brect = adjustedItemEffectiveBoundingRect(item);
                 if (!itemd->itemIsUntransformable()) {
                     transform = item->sceneTransform();
                     if (viewTransformed)
                         transform *= viewTransform;
                 } else {
                     transform = item->deviceTransform(viewTransform);
                 }
                 itemd->paintedViewBoundingRects.insert(d->viewport, transform.mapRect(brect).toRect());
             }
             // Draw the items.
             drawItems(&painter, numItems, itemArray, styleOptionArray);
             d->freeStyleOptionsArray(styleOptionArray);
         }
     }
     // Foreground
     drawForeground(&painter, exposedSceneRect);
 #ifndef QT_NO_RUBBERBAND
     // Rubberband
     if (d->rubberBanding && !d->rubberBandRect.isEmpty()) {
         painter.restore();
         QStyleOptionRubberBand option;
         option.initFrom(viewport());
         option.rect = d->rubberBandRect;
         option.shape = QRubberBand::Rectangle;
         QStyleHintReturnMask mask;
         if (viewport()->style()->styleHint(QStyle::SH_RubberBand_Mask, &option, viewport(), &mask)) {
             // painter clipping for masked rubberbands
             painter.setClipRegion(mask.region, Qt::IntersectClip);
         }
         viewport()->style()->drawControl(QStyle::CE_RubberBand, &option, &painter, viewport());
     }
 #endif
     painter.end();
     // Restore painter state protection.
     d->scene->d_func()->painterStateProtection = true;
 }
render()
void QGraphicsView::render (QPainter * painter, const QRectF & target = QRectF(), const QRect & source = QRect(), Qt::AspectRatioMode aspectRatioMode = Qt::KeepAspectRatio)
Renders the source rect, which is in view coordinates, from the scene into target, which is in paint device coordinates, using painter.
This function is useful for capturing the contents of the view onto a paint device, such as a QImage (e.g., to take a screenshot), or for printing to QPrinter. For example:
QGraphicsScene scene;
scene.addItem(...
...
QGraphicsView view(&scene);
view.show();
...
QPrinter printer(QPrinter::HighResolution);
printer.setPageSize(QPrinter::A4);
QPainter painter(&printer);
// print, fitting the viewport contents into a full page
view.render(&painter);
// print the upper half of the viewport into the lower.
// half of the page.
QRect viewport = view.viewport()->rect();
view.render(&painter,
            QRectF(0, printer.height() / 2,
                   printer.width(), printer.height() / 2),
            viewport.adjusted(0, 0, 0, -viewport.height() / 2));
If source is a null rect, this function will use viewport()->rect() to determine what to draw. If target is a null rect, the full dimensions of painter's paint device (e.g., for a QPrinter, the page size) will be used.
The source rect contents will be transformed according to aspectRatioMode to fit into the target rect. By default, the aspect ratio is kept, and source is scaled to fit in target.
See also
QGraphicsScene::render()
Definition at line 2125 of file qgraphicsview.cpp.
Referenced by QmlJSDebugger::ColorPickerTool::pickColor().
 {
     // ### Switch to using the recursive rendering algorithm instead.
     Q_D(QGraphicsView);
     if (!d->scene || !(painter && painter->isActive()))
         return;
     // Default source rect = viewport rect
     QRect sourceRect = source;
     if (source.isNull())
         sourceRect = viewport()->rect();
     // Default target rect = device rect
     QRectF targetRect = target;
     if (target.isNull()) {
         if (painter->device()->devType() == QInternal::Picture)
             targetRect = sourceRect;
         else
             targetRect.setRect(0, 0, painter->device()->width(), painter->device()->height());
     }
     // Find the ideal x / y scaling ratio to fit \a source into \a target.
     qreal xratio = targetRect.width() / sourceRect.width();
     qreal yratio = targetRect.height() / sourceRect.height();
     // Scale according to the aspect ratio mode.
     switch (aspectRatioMode) {
     case Qt::KeepAspectRatio:
         xratio = yratio = qMin(xratio, yratio);
         break;
     case Qt::KeepAspectRatioByExpanding:
         xratio = yratio = qMax(xratio, yratio);
         break;
     case Qt::IgnoreAspectRatio:
         break;
     }
     // Find all items to draw, and reverse the list (we want to draw
     // in reverse order).
     QPolygonF sourceScenePoly = mapToScene(sourceRect.adjusted(-1, -1, 1, 1));
     QList<QGraphicsItem *> itemList = d->scene->items(sourceScenePoly,
                                                       Qt::IntersectsItemBoundingRect);
     QGraphicsItem **itemArray = new QGraphicsItem *[itemList.size()];
     int numItems = itemList.size();
     for (int i = 0; i < numItems; ++i)
         itemArray[numItems - i - 1] = itemList.at(i);
     itemList.clear();
     // Setup painter matrix.
     QTransform moveMatrix = QTransform::fromTranslate(-d->horizontalScroll(), -d->verticalScroll());
     QTransform painterMatrix = d->matrix * moveMatrix;
     painterMatrix *= QTransform()
                      .translate(targetRect.left(), targetRect.top())
                      .scale(xratio, yratio)
                      .translate(-sourceRect.left(), -sourceRect.top());
     // Generate the style options
     QStyleOptionGraphicsItem *styleOptionArray = d->allocStyleOptionsArray(numItems);
     for (int i = 0; i < numItems; ++i)
         itemArray[i]->d_ptr->initStyleOption(&styleOptionArray[i], painterMatrix, targetRect.toRect());
     painter->save();
     // Clip in device coordinates to avoid QRegion transformations.
     painter->setClipRect(targetRect);
     QPainterPath path;
     path.addPolygon(sourceScenePoly);
     path.closeSubpath();
     painter->setClipPath(painterMatrix.map(path), Qt::IntersectClip);
     // Transform the painter.
     painter->setTransform(painterMatrix, true);
     // Render the scene.
     QRectF sourceSceneRect = sourceScenePoly.boundingRect();
     drawBackground(painter, sourceSceneRect);
     drawItems(painter, numItems, itemArray, styleOptionArray);
     drawForeground(painter, sourceSceneRect);
     delete [] itemArray;
     d->freeStyleOptionsArray(styleOptionArray);
     painter->restore();
 }
renderHints()
QPainter::RenderHints QGraphicsView::renderHints () const
Referenced by sizeHint().
resetCachedContent()
void QGraphicsView::resetCachedContent ()
Resets any cached content.
Calling this function will clear QGraphicsView's cache. If the current cache mode is CacheNone , this function does nothing.
This function is called automatically for you when the backgroundBrush or QGraphicsScene::backgroundBrush properties change; you only need to call this function if you have reimplemented QGraphicsScene::drawBackground() or QGraphicsView::drawBackground() to draw a custom background, and need to trigger a full redraw.
See also
cacheMode()
Definition at line 1566 of file qgraphicsview.cpp.
Referenced by QGraphicsScene::setBackgroundBrush(), and setCacheMode().
 {
     Q_D(QGraphicsView);
     if (d->cacheMode == CacheNone)
         return;
     if (d->cacheMode & CacheBackground) {
         // Background caching is enabled.
         d->mustResizeBackgroundPixmap = true;
         d->updateAll();
     } else if (d->mustResizeBackgroundPixmap) {
         // Background caching is disabled.
         // Cleanup, free some resources.
         d->mustResizeBackgroundPixmap = false;
         d->backgroundPixmap = QPixmap();
         d->backgroundPixmapExposed = QRegion();
     }
 }
resetMatrix()
void QGraphicsView::resetMatrix ()
Resets the view transformation matrix to the identity matrix.
See also
resetTransform()
Definition at line 1811 of file qgraphicsview.cpp.
 {
     resetTransform();
 }
resetTransform()
void QGraphicsView::resetTransform ()
Resets the view transformation to the identity matrix.
See also
transform(), setTransform()
Definition at line 3953 of file qgraphicsview.cpp.
Referenced by resetMatrix().
 {
     setTransform(QTransform());
 }
resizeAnchor()
ViewportAnchor QGraphicsView::resizeAnchor () const
Referenced by setTransformationAnchor().
resizeEvent()
void QGraphicsView::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3663 of file qgraphicsview.cpp.
Referenced by QDeclarativeView::resizeEvent().
 {
     Q_D(QGraphicsView);
     // Save the last center point - the resize may scroll the view, which
     // changes the center point.
     QPointF oldLastCenterPoint = d->lastCenterPoint;
     QAbstractScrollArea::resizeEvent(event);
     d->recalculateContentSize();
     // Restore the center point again.
     if (d->resizeAnchor == NoAnchor && !d->keepLastCenterPoint) {
         d->updateLastCenterPoint();
     } else {
         d->lastCenterPoint = oldLastCenterPoint;
     }
     d->centerView(d->resizeAnchor);
     d->keepLastCenterPoint = false;
     if (d->cacheMode & CacheBackground) {
         // Invalidate the background pixmap
         d->mustResizeBackgroundPixmap = true;
     }
 }
rotate()
void QGraphicsView::rotate (qreal angle)
Rotates the current view transformation angle degrees clockwise.
See also
setTransform(), transform(), scale(), shear(), translate()
Definition at line 1821 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     QTransform matrix = d->matrix;
     matrix.rotate(angle);
     setTransform(matrix);
 }
rubberBandSelectionMode()
Qt::ItemSelectionMode QGraphicsView::rubberBandSelectionMode () const
Referenced by setDragMode().
scale()
void QGraphicsView::scale (qreal sx, qreal sy)
Scales the current view transformation by (sx, sy).
See also
setTransform(), transform(), rotate(), shear(), translate()
Definition at line 1834 of file qgraphicsview.cpp.
Referenced by fitInView(), and render().
 {
     Q_D(QGraphicsView);
     QTransform matrix = d->matrix;
     matrix.scale(sx, sy);
     setTransform(matrix);
 }
scene()
QGraphicsScene * QGraphicsView::scene () const
Returns a pointer to the scene that is currently visualized in the view.
If no scene is currently visualized, 0 is returned.
See also
setScene()
Definition at line 1646 of file qgraphicsview.cpp.
Referenced by QDeclarativeView::paintEvent(), QmlJSDebugger::QDeclarativeViewInspector::QDeclarativeViewInspector(), QmlJSDebugger::AbstractLiveEditTool::scene(), QDeclarativeTextInputPrivate::sendMouseEventToInputContext(), and QDeclarativeView::setRootObject().
 {
     Q_D(const QGraphicsView);
     return d->scene;
 }
sceneRect()
QRectF QGraphicsView::sceneRect () const
Referenced by fitInView(), setScene(), and sizeHint().
scrollContentsBy()
void QGraphicsView::scrollContentsBy (int dx, int dy) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 3691 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->dirtyScroll = true;
     if (d->transforming)
         return;
     if (isRightToLeft())
         dx = -dx;
     if (d->viewportUpdateMode != QGraphicsView::NoViewportUpdate) {
         if (d->viewportUpdateMode != QGraphicsView::FullViewportUpdate) {
             if (d->accelerateScrolling) {
 #ifndef QT_NO_RUBBERBAND
                 // Update new and old rubberband regions
                 if (!d->rubberBandRect.isEmpty()) {
                     QRegion rubberBandRegion(d->rubberBandRegion(viewport(), d->rubberBandRect));
                     rubberBandRegion += rubberBandRegion.translated(-dx, -dy);
                     viewport()->update(rubberBandRegion);
                 }
 #endif
                 d->dirtyScrollOffset.rx() += dx;
                 d->dirtyScrollOffset.ry() += dy;
                 d->dirtyRegion.translate(dx, dy);
                 viewport()->scroll(dx, dy);
             } else {
                 d->updateAll();
             }
         } else {
             d->updateAll();
         }
     }
     d->updateLastCenterPoint();
     if ((d->cacheMode & CacheBackground)
 #ifdef Q_WS_X11
         && X11->use_xrender
 #endif
         ) {
         // Scroll the background pixmap
         QRegion exposed;
         if (!d->backgroundPixmap.isNull())
             d->backgroundPixmap.scroll(dx, dy, d->backgroundPixmap.rect(), &exposed);
         // Invalidate the background pixmap
         d->backgroundPixmapExposed.translate(dx, dy);
         d->backgroundPixmapExposed += exposed;
     }
     // Always replay on scroll.
     if (d->sceneInteractionAllowed)
         d->replayLastMouseEvent();
 }
setAlignment()
void QGraphicsView::setAlignment (Qt::Alignment alignment)
Definition at line 1277 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (d->alignment != alignment) {
         d->alignment = alignment;
         d->recalculateContentSize();
     }
 }
setBackgroundBrush()
void QGraphicsView::setBackgroundBrush (const QBrush & brush)
Definition at line 2629 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->backgroundBrush = brush;
     d->updateAll();
     if (d->cacheMode & CacheBackground) {
         // Invalidate the background pixmap
         d->mustResizeBackgroundPixmap = true;
     }
 }
setCacheMode()
void QGraphicsView::setCacheMode (CacheMode mode)
Definition at line 1544 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (mode == d->cacheMode)
         return;
     d->cacheMode = mode;
     resetCachedContent();
 }
setDragMode()
void QGraphicsView::setDragMode (DragMode mode)
Definition at line 1458 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (d->dragMode == mode)
         return;
 #ifndef QT_NO_CURSOR
     if (d->dragMode == ScrollHandDrag)
         viewport()->unsetCursor();
 #endif
     // If dragMode is unset while dragging, e.g. via a keyEvent, we
     // don't unset the handScrolling state. When enabling scrolling
     // again the mouseMoveEvent will automatically start scrolling,
     // without a mousePress
     if (d->dragMode == ScrollHandDrag && mode == NoDrag && d->handScrolling)
         d->handScrolling = false;
     d->dragMode = mode;
 #ifndef QT_NO_CURSOR
     if (d->dragMode == ScrollHandDrag) {
         // Forget the stored viewport cursor when we enter scroll hand drag mode.
         d->hasStoredOriginalCursor = false;
         viewport()->setCursor(Qt::OpenHandCursor);
     }
 #endif
 }
setForegroundBrush()
void QGraphicsView::setForegroundBrush (const QBrush & brush)
Definition at line 2662 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->foregroundBrush = brush;
     d->updateAll();
 }
setInteractive()
void QGraphicsView::setInteractive (bool allowed)
Definition at line 1634 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->sceneInteractionAllowed = allowed;
 }
setMatrix()
void QGraphicsView::setMatrix (const QMatrix & matrix, bool combine = false)
Sets the view's current transformation matrix to matrix.
If combine is true, then matrix is combined with the current matrix; otherwise, matrix replaces the current matrix. combine is false by default.
The transformation matrix tranforms the scene into view coordinates. Using the default transformation, provided by the identity matrix, one pixel in the view represents one unit in the scene (e.g., a 10x10 rectangular item is drawn using 10x10 pixels in the view). If a 2x2 scaling matrix is applied, the scene will be drawn in 1:2 (e.g., a 10x10 rectangular item is then drawn using 20x20 pixels in the view).
Example:
QGraphicsScene scene;
scene.addText("GraphicsView rotated clockwise");
QGraphicsView view(&scene);
view.rotate(90); // the text is rendered with a 90 degree clockwise rotation
view.show();
To simplify interation with items using a transformed view, QGraphicsView provides mapTo... and mapFrom... functions that can translate between scene and view coordinates. For example, you can call mapToScene() to map a view coordinate to a floating point scene coordinate, or mapFromScene() to map from floating point scene coordinates to view coordinates.
See also
matrix(), setTransform(), rotate(), scale(), shear(), translate()
Definition at line 1801 of file qgraphicsview.cpp.
 {
     setTransform(QTransform(matrix), combine);
 }
setOptimizationFlag()
void QGraphicsView::setOptimizationFlag (OptimizationFlag flag, bool enabled = true)
Enables flag if enabled is true; otherwise disables flag.
See also
optimizationFlags
Definition at line 1427 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (enabled)
         d->optimizationFlags |= flag;
     else
         d->optimizationFlags &= ~flag;
 }
setOptimizationFlags()
void QGraphicsView::setOptimizationFlags (OptimizationFlags flags)
Definition at line 1416 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->optimizationFlags = flags;
 }
setRenderHint()
void QGraphicsView::setRenderHint (QPainter::RenderHint hint, bool enabled = true)
If enabled is true, the render hint hint is enabled; otherwise it is disabled.
See also
renderHints
Definition at line 1245 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     QPainter::RenderHints oldHints = d->renderHints;
     if (enabled)
         d->renderHints |= hint;
     else
         d->renderHints &= ~hint;
     if (oldHints != d->renderHints)
         d->updateAll();
 }
setRenderHints()
void QGraphicsView::setRenderHints (QPainter::RenderHints hints)
Definition at line 1230 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (hints == d->renderHints)
         return;
     d->renderHints = hints;
     d->updateAll();
 }
setResizeAnchor()
void QGraphicsView::setResizeAnchor (ViewportAnchor anchor)
Definition at line 1347 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->resizeAnchor = anchor;
     // Ensure mouse tracking is enabled in the case we are using AnchorUnderMouse
     // in order to have up-to-date information for centering the view.
     if (d->resizeAnchor == AnchorUnderMouse)
         d->viewport->setMouseTracking(true);
 }
setRubberBandSelectionMode()
void QGraphicsView::setRubberBandSelectionMode (Qt::ItemSelectionMode mode)
Definition at line 1509 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->rubberBandSelectionMode = mode;
 }
setScene()
void QGraphicsView::setScene (QGraphicsScene * scene)
Sets the current scene to scene.
If scene is already being viewed, this function does nothing.
When a scene is set on a view, the QGraphicsScene::changed() signal is automatically connected to this view's updateScene() slot, and the view's scroll bars are adjusted to fit the size of the scene.
Definition at line 1660 of file qgraphicsview.cpp.
Referenced by QGraphicsView().
 {
     Q_D(QGraphicsView);
     if (d->scene == scene)
         return;
     // Always update the viewport when the scene changes.
     d->updateAll();
     // Remove the previously assigned scene.
     if (d->scene) {
         disconnect(d->scene, SIGNAL(changed(QList<QRectF>)),
                    this, SLOT(updateScene(QList<QRectF>)));
         disconnect(d->scene, SIGNAL(sceneRectChanged(QRectF)),
                    this, SLOT(updateSceneRect(QRectF)));
         d->scene->d_func()->removeView(this);
         d->connectedToScene = false;
         if (isActiveWindow() && isVisible()) {
             QEvent windowDeactivate(QEvent::WindowDeactivate);
             QApplication::sendEvent(d->scene, &windowDeactivate);
         }
         if(hasFocus())
             d->scene->clearFocus();
     }
     // Assign the new scene and update the contents (scrollbars, etc.)).
     if ((d->scene = scene)) {
         connect(d->scene, SIGNAL(sceneRectChanged(QRectF)),
                 this, SLOT(updateSceneRect(QRectF)));
         d->updateSceneSlotReimplementedChecked = false;
         d->scene->d_func()->addView(this);
         d->recalculateContentSize();
         d->lastCenterPoint = sceneRect().center();
         d->keepLastCenterPoint = true;
         // We are only interested in mouse tracking if items accept
         // hover events or use non-default cursors.
         if (!d->scene->d_func()->allItemsIgnoreHoverEvents
             || !d->scene->d_func()->allItemsUseDefaultCursor) {
             d->viewport->setMouseTracking(true);
         }
         // enable touch events if any items is interested in them
         if (!d->scene->d_func()->allItemsIgnoreTouchEvents)
             d->viewport->setAttribute(Qt::WA_AcceptTouchEvents);
         if (isActiveWindow() && isVisible()) {
             QEvent windowActivate(QEvent::WindowActivate);
             QApplication::sendEvent(d->scene, &windowActivate);
         }
     } else {
         d->recalculateContentSize();
     }
     d->updateInputMethodSensitivity();
     if (d->scene && hasFocus())
         d->scene->setFocus();
 }
setSceneRect() [1/2]
void QGraphicsView::setSceneRect (const QRectF & rect)
Definition at line 1755 of file qgraphicsview.cpp.
Referenced by QmlJSDebugger::ZoomTool::mouseReleaseEvent(), QDeclarativeView::resizeEvent(), and QmlJSDebugger::ZoomTool::scaleView().
 {
     Q_D(QGraphicsView);
     d->hasSceneRect = !rect.isNull();
     d->sceneRect = rect;
     d->recalculateContentSize();
 }
setSceneRect() [2/2]
void QGraphicsView::setSceneRect (qreal x, qreal y, qreal w, qreal h) inline
Definition at line 287 of file qgraphicsview.h.
 { setSceneRect(QRectF(ax, ay, aw, ah)); }
setTransform()
void QGraphicsView::setTransform (const QTransform & matrix, bool combine = false)
Sets the view's current transformation matrix to matrix.
If combine is true, then matrix is combined with the current matrix; otherwise, matrix replaces the current matrix. combine is false by default.
The transformation matrix tranforms the scene into view coordinates. Using the default transformation, provided by the identity matrix, one pixel in the view represents one unit in the scene (e.g., a 10x10 rectangular item is drawn using 10x10 pixels in the view). If a 2x2 scaling matrix is applied, the scene will be drawn in 1:2 (e.g., a 10x10 rectangular item is then drawn using 20x20 pixels in the view).
Example:
QGraphicsScene scene;
scene.addText("GraphicsView rotated clockwise");
QGraphicsView view(&scene);
view.rotate(90); // the text is rendered with a 90 degree clockwise rotation
view.show();
To simplify interation with items using a transformed view, QGraphicsView provides mapTo... and mapFrom... functions that can translate between scene and view coordinates. For example, you can call mapToScene() to map a view coordiate to a floating point scene coordinate, or mapFromScene() to map from floating point scene coordinates to view coordinates.
See also
transform(), rotate(), scale(), shear(), translate()
Definition at line 3920 of file qgraphicsview.cpp.
Referenced by QmlJSDebugger::ZoomTool::mouseReleaseEvent(), resetTransform(), rotate(), scale(), QmlJSDebugger::ZoomTool::scaleView(), setMatrix(), shear(), and translate().
 {
     Q_D(QGraphicsView);
     QTransform oldMatrix = d->matrix;
     if (!combine)
         d->matrix = matrix;
     else
         d->matrix = matrix * d->matrix;
     if (oldMatrix == d->matrix)
         return;
     d->identityMatrix = d->matrix.isIdentity();
     d->transforming = true;
     if (d->scene) {
         d->recalculateContentSize();
         d->centerView(d->transformationAnchor);
     } else {
         d->updateLastCenterPoint();
     }
     if (d->sceneInteractionAllowed)
         d->replayLastMouseEvent();
     d->transforming = false;
     // Any matrix operation requires a full update.
     d->updateAll();
 }
setTransformationAnchor()
void QGraphicsView::setTransformationAnchor (ViewportAnchor anchor)
Definition at line 1312 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->transformationAnchor = anchor;
     // Ensure mouse tracking is enabled in the case we are using AnchorUnderMouse
     // in order to have up-to-date information for centering the view.
     if (d->transformationAnchor == AnchorUnderMouse)
         d->viewport->setMouseTracking(true);
 }
setupViewport
void QGraphicsView::setupViewport (QWidget * widget) protected slot
This slot is called by QAbstractScrollArea after setViewport() has been called.
Reimplement this function in a subclass of QGraphicsView to initialize the new viewport widget before it is used.
See also
setViewport()
Definition at line 2766 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!widget) {
         qWarning("QGraphicsView::setupViewport: cannot initialize null widget");
         return;
     }
     const bool isGLWidget = widget->inherits("QGLWidget");
     d->accelerateScrolling = !(isGLWidget);
     widget->setFocusPolicy(Qt::StrongFocus);
     if (!isGLWidget) {
         // autoFillBackground enables scroll acceleration.
         widget->setAutoFillBackground(true);
     }
     // We are only interested in mouse tracking if items
     // accept hover events or use non-default cursors or if
     // AnchorUnderMouse is used as transformation or resize anchor.
     if ((d->scene && (!d->scene->d_func()->allItemsIgnoreHoverEvents
                      || !d->scene->d_func()->allItemsUseDefaultCursor))
         || d->transformationAnchor == AnchorUnderMouse
         || d->resizeAnchor == AnchorUnderMouse) {
         widget->setMouseTracking(true);
     }
     // enable touch events if any items is interested in them
     if (d->scene && !d->scene->d_func()->allItemsIgnoreTouchEvents)
         widget->setAttribute(Qt::WA_AcceptTouchEvents);
 #ifndef QT_NO_GESTURES
     if (d->scene) {
         foreach (Qt::GestureType gesture, d->scene->d_func()->grabbedGestures.keys())
             widget->grabGesture(gesture);
     }
 #endif
     widget->setAcceptDrops(acceptDrops());
 }
setViewportUpdateMode()
void QGraphicsView::setViewportUpdateMode (ViewportUpdateMode mode)
Definition at line 1384 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->viewportUpdateMode = mode;
 }
shear()
void QGraphicsView::shear (qreal sh, qreal sv)
Shears the current view transformation by (sh, sv).
See also
setTransform(), transform(), rotate(), scale(), translate()
Definition at line 1847 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     QTransform matrix = d->matrix;
     matrix.shear(sh, sv);
     setTransform(matrix);
 }
showEvent()
void QGraphicsView::showEvent (QShowEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3748 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     d->recalculateContentSize();
     d->centerView(d->transformationAnchor);
     QAbstractScrollArea::showEvent(event);
 }
sizeHint()
QSize QGraphicsView::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1196 of file qgraphicsview.cpp.
 {
     Q_D(const QGraphicsView);
     if (d->scene) {
         QSizeF baseSize = d->matrix.mapRect(sceneRect()).size();
         baseSize += QSizeF(d->frameWidth * 2, d->frameWidth * 2);
         return baseSize.boundedTo((3 * QApplication::desktop()->size()) / 4).toSize();
     }
     return QAbstractScrollArea::sizeHint();
 }
transform()
QTransform QGraphicsView::transform () const
Returns the current transformation matrix for the view.
If no current transformation is set, the identity matrix is returned.
See also
setTransform(), rotate(), scale(), shear(), translate()
Definition at line 3859 of file qgraphicsview.cpp.
Referenced by paintEvent(), and updateScene().
 {
     Q_D(const QGraphicsView);
     return d->matrix;
 }
transformationAnchor()
ViewportAnchor QGraphicsView::transformationAnchor () const
Referenced by setAlignment().
translate()
void QGraphicsView::translate (qreal dx, qreal dy)
Translates the current view transformation by (dx, dy).
See also
setTransform(), transform(), rotate(), shear()
Definition at line 1860 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     QTransform matrix = d->matrix;
     matrix.translate(dx, dy);
     setTransform(matrix);
 }
updateScene
void QGraphicsView::updateScene (const QList< QRectF > & rects) slot
Schedules an update of the scene rectangles rects.
See also
QGraphicsScene::changed()
Definition at line 2674 of file qgraphicsview.cpp.
Referenced by setScene(), and viewportEvent().
 {
     // ### Note: Since 4.5, this slot is only called if the user explicitly
     // establishes a connection between the scene and the view, as the scene
     // and view are no longer connected. We need to keep it working (basically
     // leave it as it is), but the new delivery path is through
     // QGraphicsScenePrivate::itemUpdate().
     Q_D(QGraphicsView);
     if (d->fullUpdatePending || d->viewportUpdateMode == QGraphicsView::NoViewportUpdate)
         return;
     // Extract and reset dirty scene rect info.
     QVector<QRect> dirtyViewportRects;
     const QVector<QRect> &dirtyRects = d->dirtyRegion.rects();
     for (int i = 0; i < dirtyRects.size(); ++i)
         dirtyViewportRects += dirtyRects.at(i);
     d->dirtyRegion = QRegion();
     d->dirtyBoundingRect = QRect();
     bool fullUpdate = !d->accelerateScrolling || d->viewportUpdateMode == QGraphicsView::FullViewportUpdate;
     bool boundingRectUpdate = (d->viewportUpdateMode == QGraphicsView::BoundingRectViewportUpdate)
                               || (d->viewportUpdateMode == QGraphicsView::SmartViewportUpdate
                                   && ((dirtyViewportRects.size() + rects.size()) >= QGRAPHICSVIEW_REGION_RECT_THRESHOLD));
     QRegion updateRegion;
     QRect boundingRect;
     QRect viewportRect = viewport()->rect();
     bool redraw = false;
     QTransform transform = viewportTransform();
     // Convert scene rects to viewport rects.
     foreach (const QRectF &rect, rects) {
         QRect xrect = transform.mapRect(rect).toAlignedRect();
         if (!(d->optimizationFlags & DontAdjustForAntialiasing))
             xrect.adjust(-2, -2, 2, 2);
         else
             xrect.adjust(-1, -1, 1, 1);
         if (!viewportRect.intersects(xrect))
             continue;
         dirtyViewportRects << xrect;
     }
     foreach (const QRect &rect, dirtyViewportRects) {
         // Add the exposed rect to the update region. In rect update
         // mode, we only count the bounding rect of items.
         if (!boundingRectUpdate) {
             updateRegion += rect;
         } else {
             boundingRect |= rect;
         }
         redraw = true;
         if (fullUpdate) {
             // If fullUpdate is true and we found a visible dirty rect,
             // we're done.
             break;
         }
     }
     if (!redraw)
         return;
     if (fullUpdate)
         viewport()->update();
     else if (boundingRectUpdate)
         viewport()->update(boundingRect);
     else
         viewport()->update(updateRegion);
 }
updateSceneRect
void QGraphicsView::updateSceneRect (const QRectF & rect) slot
Notifies QGraphicsView that the scene's scene rect has changed.
rect is the new scene rect. If the view already has an explicitly set scene rect, this function does nothing.
See also
sceneRect, QGraphicsScene::sceneRectChanged()
Definition at line 2750 of file qgraphicsview.cpp.
Referenced by setScene().
 {
     Q_D(QGraphicsView);
     if (!d->hasSceneRect) {
         d->sceneRect = rect;
         d->recalculateContentSize();
     }
 }
viewportEvent()
bool QGraphicsView::viewportEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 2854 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!d->scene)
         return QAbstractScrollArea::viewportEvent(event);
     switch (event->type()) {
     case QEvent::Enter:
         QApplication::sendEvent(d->scene, event);
         break;
     case QEvent::WindowActivate:
         QApplication::sendEvent(d->scene, event);
         break;
     case QEvent::WindowDeactivate:
         // ### This is a temporary fix for until we get proper mouse
         // grab events. mouseGrabberItem should be set to 0 if we lose
         // the mouse grab.
         // Remove all popups when the scene loses focus.
         if (!d->scene->d_func()->popupWidgets.isEmpty())
             d->scene->d_func()->removePopup(d->scene->d_func()->popupWidgets.first());
         QApplication::sendEvent(d->scene, event);
         break;
     case QEvent::Show:
         if (d->scene && isActiveWindow()) {
             QEvent windowActivate(QEvent::WindowActivate);
             QApplication::sendEvent(d->scene, &windowActivate);
         }
         break;
     case QEvent::Hide:
         // spontaneous event will generate a WindowDeactivate.
         if (!event->spontaneous() && d->scene && isActiveWindow()) {
             QEvent windowDeactivate(QEvent::WindowDeactivate);
             QApplication::sendEvent(d->scene, &windowDeactivate);
         }
         break;
     case QEvent::Leave:
         // ### This is a temporary fix for until we get proper mouse grab
         // events. activeMouseGrabberItem should be set to 0 if we lose the
         // mouse grab.
         if ((QApplication::activePopupWidget() && QApplication::activePopupWidget() != window())
             || (QApplication::activeModalWidget() && QApplication::activeModalWidget() != window())
             || (QApplication::activeWindow() != window())) {
             if (!d->scene->d_func()->popupWidgets.isEmpty())
                 d->scene->d_func()->removePopup(d->scene->d_func()->popupWidgets.first());
         }
         d->useLastMouseEvent = false;
         // a hack to pass a viewport pointer to the scene inside the leave event
         Q_ASSERT(event->d == 0);
         event->d = reinterpret_cast<QEventPrivate *>(viewport());
         QApplication::sendEvent(d->scene, event);
         break;
 #ifndef QT_NO_TOOLTIP
     case QEvent::ToolTip: {
         QHelpEvent *toolTip = static_cast<QHelpEvent *>(event);
         QGraphicsSceneHelpEvent helpEvent(QEvent::GraphicsSceneHelp);
         helpEvent.setWidget(viewport());
         helpEvent.setScreenPos(toolTip->globalPos());
         helpEvent.setScenePos(mapToScene(toolTip->pos()));
         QApplication::sendEvent(d->scene, &helpEvent);
         toolTip->setAccepted(helpEvent.isAccepted());
         return true;
     }
 #endif
     case QEvent::Paint:
         // Reset full update
         d->fullUpdatePending = false;
         d->dirtyScrollOffset = QPoint();
         if (d->scene) {
             // Check if this view reimplements the updateScene slot; if it
             // does, we can't do direct update delivery and have to fall back
             // to connecting the changed signal.
             if (!d->updateSceneSlotReimplementedChecked) {
                 d->updateSceneSlotReimplementedChecked = true;
                 const QMetaObject *mo = metaObject();
                 if (mo != &QGraphicsView::staticMetaObject) {
                     if (mo->indexOfSlot("updateScene(QList<QRectF>)")
                         != QGraphicsView::staticMetaObject.indexOfSlot("updateScene(QList<QRectF>)")) {
                         connect(d->scene, SIGNAL(changed(QList<QRectF>)),
                                 this, SLOT(updateScene(QList<QRectF>)));
                     }
                 }
             }
         }
         break;
     case QEvent::TouchBegin:
     case QEvent::TouchUpdate:
     case QEvent::TouchEnd:
     {
         if (!isEnabled())
             return false;
         if (d->scene && d->sceneInteractionAllowed) {
             // Convert and deliver the touch event to the scene.
             QTouchEvent *touchEvent = static_cast<QTouchEvent *>(event);
             touchEvent->setWidget(viewport());
             QGraphicsViewPrivate::translateTouchEvent(d, touchEvent);
             (void) QApplication::sendEvent(d->scene, touchEvent);
         }
         return true;
     }
 #ifndef QT_NO_GESTURES
     case QEvent::Gesture:
     case QEvent::GestureOverride:
     {
         if (!isEnabled())
             return false;
         if (d->scene && d->sceneInteractionAllowed) {
             QGestureEvent *gestureEvent = static_cast<QGestureEvent *>(event);
             gestureEvent->setWidget(viewport());
             (void) QApplication::sendEvent(d->scene, gestureEvent);
         }
         return true;
     }
 #endif // QT_NO_GESTURES
     default:
         break;
     }
     return QAbstractScrollArea::viewportEvent(event);
 }
viewportTransform()
QTransform QGraphicsView::viewportTransform () const
Returns a matrix that maps viewport coordinates to scene coordinates.
See also
mapToScene(), mapFromScene()
Definition at line 3870 of file qgraphicsview.cpp.
Referenced by QGraphicsItemPrivate::genericMapFromScene(), QGraphicsScenePrivate::gestureEventHandler(), items(), QGraphicsScenePrivate::itemsAtPosition(), mouseMoveEvent(), QGraphicsItem::mouseMoveEvent(), paintEvent(), QGraphicsScene::update(), updateHelper(), and updateScene().
 {
     Q_D(const QGraphicsView);
     QTransform moveMatrix = QTransform::fromTranslate(-d->horizontalScroll(), -d->verticalScroll());
     return d->identityMatrix ? moveMatrix : d->matrix * moveMatrix;
 }
viewportUpdateMode()
ViewportUpdateMode QGraphicsView::viewportUpdateMode () const
Referenced by setResizeAnchor().
wheelEvent()
void QGraphicsView::wheelEvent (QWheelEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3465 of file qgraphicsview.cpp.
 {
     Q_D(QGraphicsView);
     if (!d->scene || !d->sceneInteractionAllowed) {
         QAbstractScrollArea::wheelEvent(event);
         return;
     }
     event->ignore();
     QGraphicsSceneWheelEvent wheelEvent(QEvent::GraphicsSceneWheel);
     wheelEvent.setWidget(viewport());
     wheelEvent.setScenePos(mapToScene(event->pos()));
     wheelEvent.setScreenPos(event->globalPos());
     wheelEvent.setButtons(event->buttons());
     wheelEvent.setModifiers(event->modifiers());
     wheelEvent.setDelta(event->delta());
     wheelEvent.setOrientation(event->orientation());
     wheelEvent.setAccepted(false);
     QApplication::sendEvent(d->scene, &wheelEvent);
     event->setAccepted(wheelEvent.isAccepted());
     if (!event->isAccepted())
         QAbstractScrollArea::wheelEvent(event);
 }
Friends and Related Functions
QGraphicsItemPrivate
friend class QGraphicsItemPrivate friend
Definition at line 281 of file qgraphicsview.h.
QGraphicsScene
friend class QGraphicsScene friend
Definition at line 279 of file qgraphicsview.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 280 of file qgraphicsview.h.
QGraphicsSceneWidget
friend class QGraphicsSceneWidget friend
Definition at line 278 of file qgraphicsview.h.
Properties
alignment
Qt::Alignment QGraphicsView::alignment private
the alignment of the scene in the view when the whole scene is visible.
If the whole scene is visible in the view, (i.e., there are no visible scroll bars,) the view's alignment will decide where the scene will be rendered in the view. For example, if the alignment is Qt::AlignCenter, which is default, the scene will be centered in the view, and if the alignment is (Qt::AlignLeft | Qt::AlignTop), the scene will be rendered in the top-left corner of the view.
Definition at line 73 of file qgraphicsview.h.
backgroundBrush
QBrush QGraphicsView::backgroundBrush private
the background brush of the scene.
This property sets the background brush for the scene in this view. It is used to override the scene's own background, and defines the behavior of drawBackground(). To provide custom background drawing for this view, you can reimplement drawBackground() instead.
By default, this property contains a brush with the Qt::NoBrush pattern.
See also
QGraphicsScene::backgroundBrush, foregroundBrush
Definition at line 69 of file qgraphicsview.h.
cacheMode
QGraphicsView::CacheMode QGraphicsView::cacheMode private
which parts of the view are cached
QGraphicsView can cache pre-rendered content in a QPixmap, which is then drawn onto the viewport. The purpose of such caching is to speed up the total rendering time for areas that are slow to render. Texture, gradient and alpha blended backgrounds, for example, can be notibly slow to render; especially with a transformed view. The CacheBackground flag enables caching of the view's background. For example:
QGraphicsView view;
view.setBackgroundBrush(QImage(":/images/backgroundtile.png"));
view.setCacheMode(QGraphicsView::CacheBackground);
The cache is invalidated every time the view is transformed. However, when scrolling, only partial invalidation is required.
By default, nothing is cached.
See also
resetCachedContent(), QPixmapCache
Definition at line 76 of file qgraphicsview.h.
dragMode
QGraphicsView::DragMode QGraphicsView::dragMode private
the behavior for dragging the mouse over the scene while the left mouse button is pressed.
This property defines what should happen when the user clicks on the scene background and drags the mouse (e.g., scrolling the viewport contents using a pointing hand cursor, or selecting multiple items with a rubber band). The default value, NoDrag, does nothing.
This behavior only affects mouse clicks that are not handled by any item. You can define a custom behavior by creating a subclass of QGraphicsView and reimplementing mouseMoveEvent().
Definition at line 75 of file qgraphicsview.h.
foregroundBrush
QBrush QGraphicsView::foregroundBrush private
the foreground brush of the scene.
This property sets the foreground brush for the scene in this view. It is used to override the scene's own foreground, and defines the behavior of drawForeground(). To provide custom foreground drawing for this view, you can reimplement drawForeground() instead.
By default, this property contains a brush with the Qt::NoBrush pattern.
See also
QGraphicsScene::foregroundBrush, backgroundBrush
Definition at line 70 of file qgraphicsview.h.
interactive
QGraphicsView::interactive private
whether the view allowed scene interaction.
If enabled, this view is set to allow scene interaction. Otherwise, this view will not allow interaction, and any mouse or key events are ignored (i.e., it will act as a read-only view).
By default, this property is true.
Definition at line 71 of file qgraphicsview.h.
optimizationFlags
QGraphicsView::OptimizationFlags QGraphicsView::optimizationFlags private
flags that can be used to tune QGraphicsView's performance.
Since
4.3
QGraphicsView uses clipping, extra bounding rect adjustments, and certain other aids to improve rendering quality and performance for the common case graphics scene. However, depending on the target platform, the scene, and the viewport in use, some of these operations can degrade performance.
The effect varies from flag to flag; see the OptimizationFlags documentation for details.
By default, no optimization flags are enabled.
See also
setOptimizationFlag()
Definition at line 83 of file qgraphicsview.h.
Referenced by QGraphicsScene::drawItems().
renderHints
QPainter::RenderHints QGraphicsView::renderHints private
the default render hints for the view
These hints are used to initialize QPainter before each visible item is drawn. QPainter uses render hints to toggle rendering features such as antialiasing and smooth pixmap transformation.
QPainter::TextAntialiasing is enabled by default.
Example:
QGraphicsScene scene;
scene.addRect(QRectF(-10, -10, 20, 20));
QGraphicsView view(&scene);
view.setRenderHints(QPainter::Antialiasing | QPainter::SmoothPixmapTransform);
view.show();
Definition at line 74 of file qgraphicsview.h.
resizeAnchor
QGraphicsView::ViewportAnchor QGraphicsView::resizeAnchor private
how the view should position the scene when the view is resized.
QGraphicsView uses this property to decide how to position the scene in the viewport when the viewport widget's size changes. The default behavior, NoAnchor, leaves the scene's position unchanged during a resize; the top-left corner of the view will appear to be anchored while resizing.
Note that the effect of this property is noticeable when only a part of the scene is visible (i.e., when there are scroll bars). Otherwise, if the whole scene fits in the view, QGraphicsScene uses the view alignment to position the scene in the view.
See also
alignment, transformationAnchor, Qt::WNorthWestGravity
Definition at line 78 of file qgraphicsview.h.
rubberBandSelectionMode
Qt::ItemSelectionMode QGraphicsView::rubberBandSelectionMode private
the behavior for selecting items with a rubber band selection rectangle.
Since
4.3
This property defines how items are selected when using the RubberBandDrag drag mode.
The default value is Qt::IntersectsItemShape; all items whose shape intersects with or is contained by the rubber band are selected.
See also
dragMode, items()
Definition at line 81 of file qgraphicsview.h.
sceneRect
QRectF QGraphicsView::sceneRect private
the area of the scene visualized by this view.
The scene rectangle defines the extent of the scene, and in the view's case, this means the area of the scene that you can navigate using the scroll bars.
If unset, or if a null QRectF is set, this property has the same value as QGraphicsScene::sceneRect, and it changes with QGraphicsScene::sceneRect. Otherwise, the view's scene rect is unaffected by the scene.
Note that, although the scene supports a virtually unlimited size, the range of the scroll bars will never exceed the range of an integer (INT_MIN, INT_MAX). When the scene is larger than the scroll bars' values, you can choose to use translate() to navigate the scene instead.
By default, this property contains a rectangle at the origin with zero width and height.
See also
QGraphicsScene::sceneRect
Definition at line 72 of file qgraphicsview.h.
transformationAnchor
QGraphicsView::ViewportAnchor QGraphicsView::transformationAnchor private
how the view should position the scene during transformations.
QGraphicsView uses this property to decide how to position the scene in the viewport when the transformation matrix changes, and the coordinate system of the view is transformed. The default behavior, AnchorViewCenter, ensures that the scene point at the center of the view remains unchanged during transformations (e.g., when rotating, the scene will appear to rotate around the center of the view).
Note that the effect of this property is noticeable when only a part of the scene is visible (i.e., when there are scroll bars). Otherwise, if the whole scene fits in the view, QGraphicsScene uses the view alignment to position the scene in the view.
See also
alignment, resizeAnchor
Definition at line 77 of file qgraphicsview.h.
viewportUpdateMode
QGraphicsView::ViewportUpdateMode QGraphicsView::viewportUpdateMode private
how the viewport should update its contents.
Since
4.3
QGraphicsView uses this property to decide how to update areas of the scene that have been reexposed or changed. Usually you do not need to modify this property, but there are some cases where doing so can improve rendering performance. See the ViewportUpdateMode documentation for specific details.
The default value is MinimalViewportUpdate, where QGraphicsView will update as small an area of the viewport as possible when the contents change.
See also
ViewportUpdateMode, cacheMode
Definition at line 79 of file qgraphicsview.h.
Referenced by QGLGraphicsSystem::createWindowSurface().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsview.h
/src/gui/graphicsview/qgraphicsview.cpp