Qt 4.8: QStyleFactory Class Reference
QStyleFactory Class Reference
The QStyleFactory class creates QStyle objects.
#include <qstylefactory.h>
Static Public Functions
static QStyle * create (const QString &)
static QStringList keys ()
Returns the list of valid keys, i.e.
Detailed Description
The QStyleFactory class creates QStyle objects.
The QStyle class is an abstract base class that encapsulates the look and feel of a GUI. QStyleFactory creates a QStyle object using the create() function and a key identifying the style. The styles are either built-in or dynamically loaded from a style plugin (see QStylePlugin).
The valid keys can be retrieved using the keys() function. Typically they include "windows", "motif", "cde", "plastique" and "cleanlooks". Depending on the platform, "windowsxp", "windowsvista" and "macintosh" may be available. Note that keys are case insensitive.
See also
QStyle
Definition at line 55 of file qstylefactory.h.
Functions
create()
static QStyle* QStyleFactory::create (const QString &) static
Referenced by QProxyStylePrivate::ensureBaseStyle(), QWidgetPrivate::inheritStyle(), QApplicationPrivate::qt_mac_apply_settings(), QApplication::setStyle(), and QApplication::style().
keys()
QStringList QStyleFactory::keys () static
Returns the list of valid keys, i.e.
the keys this factory can create styles for.
See also
create()
Definition at line 210 of file qstylefactory.cpp.
Referenced by QKde::kdeStyle(), QApplication::style(), and QGuiPlatformPlugin::styleName().
 {
 #if !defined(QT_NO_LIBRARY) && !defined(QT_NO_SETTINGS)
     QStringList list = loader()->keys();
 #else
     QStringList list;
 #endif
 #ifndef QT_NO_STYLE_WINDOWS
     if (!list.contains(QLatin1String("Windows")))
         list << QLatin1String("Windows");
 #endif
 #ifndef QT_NO_STYLE_WINDOWSCE
     if (!list.contains(QLatin1String("WindowsCE")))
         list << QLatin1String("WindowsCE");
 #endif
 #ifndef QT_NO_STYLE_WINDOWSMOBILE
     if (!list.contains(QLatin1String("WindowsMobile")))
         list << QLatin1String("WindowsMobile");
 #endif
 #ifndef QT_NO_STYLE_WINDOWSXP
     if (!list.contains(QLatin1String("WindowsXP")) &&
         (QSysInfo::WindowsVersion >= QSysInfo::WV_XP && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)))
         list << QLatin1String("WindowsXP");
 #endif
 #ifndef QT_NO_STYLE_WINDOWSVISTA
     if (!list.contains(QLatin1String("WindowsVista")) &&
         (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)))
         list << QLatin1String("WindowsVista");
 #endif
 #ifndef QT_NO_STYLE_MOTIF
     if (!list.contains(QLatin1String("Motif")))
         list << QLatin1String("Motif");
 #endif
 #ifndef QT_NO_STYLE_CDE
     if (!list.contains(QLatin1String("CDE")))
         list << QLatin1String("CDE");
 #endif
 #ifndef QT_NO_STYLE_S60
     if (!list.contains(QLatin1String("S60")))
         list << QLatin1String("S60");
 #endif
 #ifndef QT_NO_STYLE_PLASTIQUE
     if (!list.contains(QLatin1String("Plastique")))
         list << QLatin1String("Plastique");
 #endif
 #ifndef QT_NO_STYLE_GTK
     if (!list.contains(QLatin1String("GTK+")))
         list << QLatin1String("GTK+");
 #endif
 #ifndef QT_NO_STYLE_CLEANLOOKS
     if (!list.contains(QLatin1String("Cleanlooks")))
         list << QLatin1String("Cleanlooks");
 #endif
 #ifndef QT_NO_STYLE_MAC
     QString mstyle = QLatin1String("Macintosh");
 # ifdef Q_WS_MAC
     mstyle += QLatin1String(" (aqua)");
 # endif
     if (!list.contains(mstyle))
         list << mstyle;
 #endif
     return list;
 }
The documentation for this class was generated from the following files:
/src/gui/styles/qstylefactory.h
/src/gui/styles/qstylefactory.cpp