Qt 4.8: QDeclarativeStateGroup Class Reference
QDeclarativeStateGroup Class Reference
#include <qdeclarativestategroup_p.h>
Signals
void stateChanged (const QString &)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void classBegin ()
Invoked after class creation, but before any properties have been set.
virtual void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
QDeclarativeState * findState (const QString &name) const
QDeclarativeStateGroup (QObject *=0)
void setState (const QString &)
QString state () const
QList< QDeclarativeState * > states () const
QDeclarativeListProperty< QDeclarativeState > statesProperty ()
QDeclarativeListProperty< QDeclarativeTransition > transitionsProperty ()
virtual ~QDeclarativeStateGroup ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Private Functions
void removeState (QDeclarativeState *state)
bool updateAutoState ()
Returns true if the state was changed, otherwise false.
Properties
QString state
QDeclarativeListProperty< QDeclarativeState > states
QDeclarativeListProperty< QDeclarativeTransition > transitions
Friends
class QDeclarativeState
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 54 of file qdeclarativestategroup_p.h.
Constructors and Destructors
QDeclarativeStateGroup()
QDeclarativeStateGroup::QDeclarativeStateGroup (QObject * parent = 0)
Definition at line 127 of file qdeclarativestategroup.cpp.
     : QObject(*(new QDeclarativeStateGroupPrivate), parent)
 {
 }
~QDeclarativeStateGroup()
QDeclarativeStateGroup::~QDeclarativeStateGroup () virtual
Definition at line 132 of file qdeclarativestategroup.cpp.
 {
     Q_D(const QDeclarativeStateGroup);
     for (int i = 0; i < d->states.count(); ++i)
         d->states.at(i)->setStateGroup(0);
 }
Functions
classBegin()
void QDeclarativeStateGroup::classBegin () virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 307 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeItemPrivate::_states().
 {
     Q_D(QDeclarativeStateGroup);
     d->componentComplete = false;
 }
componentComplete()
void QDeclarativeStateGroup::componentComplete () virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 313 of file qdeclarativestategroup.cpp.
Referenced by QDeclarativeStateGroupPrivate::setCurrentStateInternal(), and QDeclarativeStateGroupPrivate::updateAutoState().
 {
     Q_D(QDeclarativeStateGroup);
     d->componentComplete = true;
     for (int ii = 0; ii < d->states.count(); ++ii) {
         QDeclarativeState *state = d->states.at(ii);
         if (!state->isNamed())
             state->setName(QLatin1String("anonymousState") % QString::number(++d->unnamedCount));
     }
     if (d->updateAutoState()) {
         return;
     } else if (!d->currentState.isEmpty()) {
         QString cs = d->currentState;
         d->currentState.clear();
         d->setCurrentStateInternal(cs, true);
     }
 }
findState()
QDeclarativeState * QDeclarativeStateGroup::findState (const QString & name) const
Definition at line 494 of file qdeclarativestategroup.cpp.
 {
     Q_D(const QDeclarativeStateGroup);
     for (int i = 0; i < d->states.count(); ++i) {
         QDeclarativeState *state = d->states.at(i);
         if (state->name() == name)
             return state;
     }
     return 0;
 }
removeState()
void QDeclarativeStateGroup::removeState (QDeclarativeState * state) private
Definition at line 506 of file qdeclarativestategroup.cpp.
 {
     Q_D(QDeclarativeStateGroup);
     d->states.removeOne(state);
 }
setState()
void QDeclarativeStateGroup::setState (const QString & state)
Definition at line 298 of file qdeclarativestategroup.cpp.
 {
     Q_D(QDeclarativeStateGroup);
     if (d->currentState == state)
         return;
     d->setCurrentStateInternal(state);
 }
state()
QString QDeclarativeStateGroup::state () const
Referenced by QDeclarativeStateGroupPrivate::clear_transitions(), componentComplete(), findState(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), and QDeclarativeStateGroupPrivate::updateAutoState().
stateChanged
void QDeclarativeStateGroup::stateChanged (const QString &) signal
states()
QList<QDeclarativeState *> QDeclarativeStateGroup::states () const
Referenced by QDeclarativeStateGroupPrivate::setCurrentStateInternal(), QDeclarativeStateGroupPrivate::updateAutoState(), and ~QDeclarativeStateGroup().
statesProperty()
QDeclarativeListProperty< QDeclarativeState > QDeclarativeStateGroup::statesProperty ()
Definition at line 168 of file qdeclarativestategroup.cpp.
 {
     Q_D(QDeclarativeStateGroup);
     return QDeclarativeListProperty<QDeclarativeState>(this, &d->states, &QDeclarativeStateGroupPrivate::append_state,
                                                        &QDeclarativeStateGroupPrivate::count_state,
                                                        &QDeclarativeStateGroupPrivate::at_state,
                                                        &QDeclarativeStateGroupPrivate::clear_states);
 }
transitionsProperty()
QDeclarativeListProperty< QDeclarativeTransition > QDeclarativeStateGroup::transitionsProperty ()
Definition at line 232 of file qdeclarativestategroup.cpp.
 {
     Q_D(QDeclarativeStateGroup);
     return QDeclarativeListProperty<QDeclarativeTransition>(this, &d->transitions, &QDeclarativeStateGroupPrivate::append_transition,
                                                        &QDeclarativeStateGroupPrivate::count_transitions,
                                                        &QDeclarativeStateGroupPrivate::at_transition,
                                                        &QDeclarativeStateGroupPrivate::clear_transitions);
 }
updateAutoState()
bool QDeclarativeStateGroup::updateAutoState () private
Returns true if the state was changed, otherwise false.
Definition at line 336 of file qdeclarativestategroup.cpp.
 {
     Q_D(QDeclarativeStateGroup);
     return d->updateAutoState();
 }
Friends and Related Functions
QDeclarativeState
friend class QDeclarativeState friend
Definition at line 84 of file qdeclarativestategroup_p.h.
Referenced by QDeclarativeStateGroupPrivate::setCurrentStateInternal().
Properties
state
QString QDeclarativeStateGroup::state private
Definition at line 60 of file qdeclarativestategroup_p.h.
Referenced by QDeclarativeState::isStateActive().
states
QList< QDeclarativeState * > QDeclarativeStateGroup::states private
Definition at line 61 of file qdeclarativestategroup_p.h.
Referenced by QDeclarativeStateGroupPrivate::append_state(), QDeclarativeStateGroupPrivate::at_state(), QDeclarativeStateGroupPrivate::clear_states(), QDeclarativeStateGroupPrivate::count_state(), and QDeclarativeStatePrivate::generateActionList().
transitions
QDeclarativeListProperty<QDeclarativeTransition> QDeclarativeStateGroup::transitions private
Definition at line 62 of file qdeclarativestategroup_p.h.
Referenced by QDeclarativeStateGroupPrivate::append_transition(), QDeclarativeStateGroupPrivate::at_transition(), QDeclarativeStateGroupPrivate::clear_transitions(), QDeclarativeStateGroupPrivate::count_transitions(), and QDeclarativeStateGroupPrivate::findTransition().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestategroup_p.h
/src/declarative/util/qdeclarativestategroup.cpp