Qt 4.8: QTestData Class Reference
QTestData Class Reference
#include <qtestdata.h>
Public Functions
void append (int type, const void *data)
void * data (int index) const
int dataCount () const
const char * dataTag () const
QTestTable * parent () const
~QTestData ()
Private Functions
QTestData (const char *tag=0, QTestTable *parent=0)
Properties
QTestDataPrivate * d
Friends
class QTestTable
Detailed Description
Definition at line 59 of file qtestdata.h.
Constructors and Destructors
~QTestData()
QTestData::~QTestData ()
Definition at line 75 of file qtestdata.cpp.
 {
     for (int i = 0; i < d->dataCount; ++i) {
         if (d->data[i])
             QMetaType::destroy(d->parent->elementTypeId(i), d->data[i]);
     }
     delete [] d->data;
     delete [] d->tag;
     delete d;
 }
QTestData()
QTestData::QTestData (const char * tag = 0, QTestTable * parent = 0) private
Definition at line 64 of file qtestdata.cpp.
 {
     QTEST_ASSERT(tag);
     QTEST_ASSERT(parent);
     d = new QTestDataPrivate;
     d->tag = qstrdup(tag);
     d->parent = parent;
     d->data = new void *[parent->elementCount()];
     memset(d->data, 0, parent->elementCount() * sizeof(void*));
 }
Functions
append()
void QTestData::append (int type, const void * data)
Definition at line 86 of file qtestdata.cpp.
Referenced by operator<<().
 {
     QTEST_ASSERT(d->dataCount < d->parent->elementCount());
     if (d->parent->elementTypeId(d->dataCount) != type) {
         qDebug("expected data of type '%s', got '%s' for element %d of data with tag '%s'",
                 QMetaType::typeName(d->parent->elementTypeId(d->dataCount)),
                 QMetaType::typeName(type),
                 d->dataCount, d->tag);
         QTEST_ASSERT(false);
     }
     d->data[d->dataCount] = QMetaType::construct(type, data);
     ++d->dataCount;
 }
data()
void * QTestData::data (int index) const
Definition at line 100 of file qtestdata.cpp.
Referenced by QTest::fetchData(), and QTest::qElementData().
 {
     QTEST_ASSERT(index >= 0);
     QTEST_ASSERT(index < d->parent->elementCount());
     return d->data[index];
 }
dataCount()
int QTestData::dataCount () const
Definition at line 117 of file qtestdata.cpp.
Referenced by QTest::fetchData().
 {
     return d->dataCount;
 }
dataTag()
const char * QTestData::dataTag () const
Definition at line 112 of file qtestdata.cpp.
Referenced by QTestResult::currentDataTag(), QTestResult::currentGlobalDataTag(), QTest::qInvokeTestMethod(), and QTest::qPrintDataTags().
 {
     return d->tag;
 }
parent()
QTestTable * QTestData::parent () const
Definition at line 107 of file qtestdata.cpp.
Referenced by QTest::fetchData(), and QTest::qElementData().
 {
     return d->parent;
 }
Friends and Related Functions
QTestTable
friend class QTestTable friend
Definition at line 71 of file qtestdata.h.
Properties
d
QTestDataPrivate* QTestData::d private
Definition at line 76 of file qtestdata.h.
The documentation for this class was generated from the following files:
/src/testlib/qtestdata.h
/src/testlib/qtestdata.cpp