Qt 4.8: QWSYellowSurface Class Reference
QWSYellowSurface Class Reference
#include <qwindowsurface_qws_p.h>
Public Functions
void flush (QWidget *widget, const QRegion &region, const QPoint &offset)
Flushes the given region from the specified widget onto the screen.
QImage image () const
Implement this function to return an image of the top-level window.
bool isValid () const
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
QString key () const
Implement this function to return a string that uniquely identifies the class of this surface.
QPaintDevice * paintDevice ()
Implement this function to return the appropriate paint device.
QByteArray permanentState () const
Implement this function to return the data required for creating a server-side representation of the surface.
QWSYellowSurface (bool isClient=false)
void setDelay (int msec)
void setPermanentState (const QByteArray &data)
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
~QWSYellowSurface ()
Public Functions inherited from QWSWindowSurface
virtual void beginPaint (const QRegion &)
This function is called before painting onto the surface begins, with the region in which the painting will occur.
const QRegion clipRegion () const
Returns the region currently visible on the screen.
virtual void endPaint (const QRegion &)
This function is called after painting onto the surface has ended, with the region in which the painting was performed.
bool isBuffered () const
Returns true if the QWSWindowSurface::Buffered is set; otherwise returns false.
bool isOpaque () const
Returns true if the QWSWindowSurface::Opaque is set; otherwise returns false.
bool isRegionReserved () const
Returns true if the QWSWindowSurface::RegionReserved is set; otherwise returns false.
virtual bool lock (int timeout=-1)
virtual bool move (const QPoint &offset)
Move the surface with the given offset.
virtual QRegion move (const QPoint &offset, const QRegion &newClip)
Move the surface with the given offset.
virtual QPoint painterOffset () const
Returns the offset to be used when painting.
QWSWindowSurface ()
Constructs an empty surface.
QWSWindowSurface (QWidget *widget)
Constructs an empty surface for the given top-level widget.
virtual void releaseSurface ()
void setClipRegion (const QRegion &)
Sets the region currently visible on the screen to be the given clip region.
virtual void setGeometry (const QRect &rect)
Sets the currently allocated area to be the given rect.
virtual void setGeometry (const QRect &rect, const QRegion &mask)
virtual void setTransientState (const QByteArray &state)
SurfaceFlags surfaceFlags () const
Returns the surface flags describing the contents of this surface.
virtual QByteArray transientState () const
virtual void unlock ()
int winId () const
~QWSWindowSurface ()
Public Functions inherited from QWindowSurface
virtual QImage * buffer (const QWidget *widget)
Returns a QImage pointer which represents the actual buffer the widget is drawn into or 0 if this is unavailable.
virtual WindowSurfaceFeatures features () const
QRect geometry () const
Returns the currently allocated area on the screen.
virtual QPixmap grabWidget (const QWidget *widget, const QRect &rectangle=QRect()) const
Returns a QPixmap generated from the part of the backing store corresponding to widget.
bool hasFeature (WindowSurfaceFeature feature) const
virtual QPoint offset (const QWidget *widget) const
Returns the offset of widget in the coordinates of this window surface.
QWindowSurface (QWidget *window, bool setDefaultSurface=true)
Constructs an empty surface for the given top-level window.
QRect rect (const QWidget *widget) const
Returns the rectangle for widget in the coordinates of this window surface.
virtual bool scroll (const QRegion &area, int dx, int dy)
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
void setStaticContents (const QRegion &region)
QRegion staticContents () const
QWidget * window () const
Returns a pointer to the top-level window associated with this surface.
virtual ~QWindowSurface ()
Destroys this surface.
Properties
int delay
QImage img
QSize surfaceSize
Additional Inherited Members
Public Types inherited from QWSWindowSurface
enum SurfaceFlag { RegionReserved = 0x1, Buffered = 0x2, Opaque = 0x4 }
This enum is used to describe the window surface's contents.
Public Types inherited from QWindowSurface
enum WindowSurfaceFeature { PartialUpdates = 0x00000001, PreservedContents = 0x00000002, StaticContents = 0x00000004, AllFeatures = 0xffffffff }
Protected Functions inherited from QWSWindowSurface
void setSurfaceFlags (SurfaceFlags type)
Sets the surface flags describing the contents of this surface, to be the given flags.
void setWinId (int id)
Protected Functions inherited from QWindowSurface
bool hasStaticContents () const
Detailed Description
Definition at line 269 of file qwindowsurface_qws_p.h.
Constructors and Destructors
QWSYellowSurface()
QWSYellowSurface::QWSYellowSurface (bool isClient = false)
Definition at line 1290 of file qwindowsurface_qws.cpp.
     : QWSWindowSurface(), delay(10)
 {
     if (isClient) {
         setWinId(QWidget::qwsDisplay()->takeId());
         QWidget::qwsDisplay()->nameRegion(winId(),
                                           QLatin1String("Debug flush paint"),
                                           QLatin1String("Silly yellow thing"));
         QWidget::qwsDisplay()->setAltitude(winId(), 1, true);
     }
     setSurfaceFlags(Buffered);
 }
~QWSYellowSurface()
QWSYellowSurface::~QWSYellowSurface ()
Definition at line 1303 of file qwindowsurface_qws.cpp.
 {
 }
Functions
flush()
void QWSYellowSurface::flush (QWidget * widget, const QRegion & region, const QPoint & offset) virtual
Flushes the given region from the specified widget onto the screen.
Note that the offset parameter is currently unused.
Reimplemented from QWSWindowSurface.
Definition at line 1329 of file qwindowsurface_qws.cpp.
Referenced by flushUpdate(), and QWidgetBackingStore::showYellowThing().
 {
     Q_UNUSED(offset);
     QWSDisplay *display = QWidget::qwsDisplay();
     QRegion rgn = region;
     if (widget)
         rgn.translate(widget->mapToGlobal(QPoint(0, 0)));
     surfaceSize = region.boundingRect().size();
     const int id = winId();
     display->requestRegion(id, key(), permanentState(), rgn);
     display->setAltitude(id, 1, true);
     display->repaintRegion(id, 0, false, rgn);
     ::usleep(500 * delay);
     display->requestRegion(id, key(), permanentState(), QRegion());
     ::usleep(500 * delay);
 }
image()
QImage QWSYellowSurface::image () const inline virtual
Implement this function to return an image of the top-level window.
See also
geometry()
Implements QWSWindowSurface.
Definition at line 287 of file qwindowsurface_qws_p.h.
 { return img; }
isValid()
bool QWSYellowSurface::isValid () const inline virtual
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
Since
4.3
See also
window(), key()
Implements QWSWindowSurface.
Definition at line 277 of file qwindowsurface_qws_p.h.
 { return true; }
key()
QString QWSYellowSurface::key () const inline virtual
Implement this function to return a string that uniquely identifies the class of this surface.
See also
window(), isValid()
Implements QWSWindowSurface.
Definition at line 281 of file qwindowsurface_qws_p.h.
Referenced by flush().
 { return QLatin1String("Yellow"); }
paintDevice()
QPaintDevice* QWSYellowSurface::paintDevice () inline virtual
Implement this function to return the appropriate paint device.
Implements QWSWindowSurface.
Definition at line 286 of file qwindowsurface_qws_p.h.
 { return &img; }
permanentState()
QByteArray QWSYellowSurface::permanentState () const virtual
Implement this function to return the data required for creating a server-side representation of the surface.
Since
4.3
See also
attach()
Reimplemented from QWSWindowSurface.
Definition at line 1307 of file qwindowsurface_qws.cpp.
Referenced by flush().
 {
     QByteArray array(2 * sizeof(int), Qt::Uninitialized);
     int *ptr = reinterpret_cast<int*>(array.data());
     ptr[0] = surfaceSize.width();
     ptr[1] = surfaceSize.height();
     return array;
 }
setDelay()
void QWSYellowSurface::setDelay (int msec) inline
Definition at line 275 of file qwindowsurface_qws_p.h.
Referenced by flushUpdate(), and QWidgetBackingStore::showYellowThing().
 { delay = msec; }
setPermanentState()
void QWSYellowSurface::setPermanentState (const QByteArray & data) virtual
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
Since
4.3
Return true if successful; otherwise return false.
See also
data()
Reimplemented from QWSWindowSurface.
Definition at line 1318 of file qwindowsurface_qws.cpp.
 {
     const int *ptr = reinterpret_cast<const int*>(data.constData());
     const int width = ptr[0];
     const int height = ptr[1];
     img = QImage(width, height, QImage::Format_ARGB32);
     img.fill(qRgba(255,255,31,127));
 }
Properties
delay
int QWSYellowSurface::delay private
Definition at line 290 of file qwindowsurface_qws_p.h.
Referenced by flush().
img
QImage QWSYellowSurface::img private
Definition at line 292 of file qwindowsurface_qws_p.h.
surfaceSize
QSize QWSYellowSurface::surfaceSize private
Definition at line 291 of file qwindowsurface_qws_p.h.
Referenced by flush(), and permanentState().
The documentation for this class was generated from the following files:
/src/gui/painting/qwindowsurface_qws_p.h
/src/gui/painting/qwindowsurface_qws.cpp