Qt 4.8: QMngHandler Class Reference
QMngHandler Class Reference
#include <qmnghandler_p.h>
Public Functions
virtual bool canRead () const
Reimplemented Function
virtual int currentImageNumber () const
Reimplemented Function
virtual int imageCount () const
Reimplemented Function
virtual bool jumpToImage (int imageNumber)
Reimplemented Function
virtual bool jumpToNextImage ()
Reimplemented Function
virtual int loopCount () const
Reimplemented Function
virtual QByteArray name () const
Reimplemented Function
virtual int nextImageDelay () const
Reimplemented Function
virtual QVariant option (ImageOption option) const
Reimplemented Function
QMngHandler ()
virtual bool read (QImage *image)
Reimplemented Function
virtual void setOption (ImageOption option, const QVariant &value)
Reimplemented Function
virtual bool supportsOption (ImageOption option) const
Reimplemented Function
virtual bool write (const QImage &image)
Reimplemented Function
~QMngHandler ()
Public Functions inherited from QImageIOHandler
virtual QRect currentImageRect () const
Returns the rect of the current image.
QIODevice * device () const
Returns the device currently assigned to the QImageIOHandler.
QByteArray format () const
Returns the format that is currently assigned to QImageIOHandler.
QImageIOHandler ()
Constructs a QImageIOHandler object.
void setDevice (QIODevice *device)
Sets the device of the QImageIOHandler to device.
void setFormat (const QByteArray &format)
Sets the format of the QImageIOHandler to format.
void setFormat (const QByteArray &format) const
Sets the format of the QImageIOHandler to format.
virtual ~QImageIOHandler ()
Destructs the QImageIOHandler object.
Static Public Functions
static bool canRead (QIODevice *device)
Properties
QScopedPointer< QMngHandlerPrivate > d_ptr
Additional Inherited Members
Public Types inherited from QImageIOHandler
enum ImageOption {
Size, ClipRect, Description, ScaledClipRect,
ScaledSize, CompressionRatio, Gamma, Quality,
Name, SubType, IncrementalReading, Endianness,
Animation, BackgroundColor, ImageFormat
}
This enum describes the different options supported by QImageIOHandler.
Protected Functions inherited from QImageIOHandler
QImageIOHandler (QImageIOHandlerPrivate &dd)
Constructs a QImageIOHandler object, using the private member dd.
Protected Variables inherited from QImageIOHandler
QScopedPointer< QImageIOHandlerPrivate > d_ptr
Detailed Description
Definition at line 56 of file qmnghandler_p.h.
Constructors and Destructors
QMngHandler()
QMngHandler::QMngHandler ()
Definition at line 378 of file qmnghandler.cpp.
     : d_ptr(new QMngHandlerPrivate(this))
 {
 }
~QMngHandler()
QMngHandler::~QMngHandler ()
Definition at line 383 of file qmnghandler.cpp.
 {
 }
Functions
canRead() [1/2]
bool QMngHandler::canRead () const virtual
Reimplemented Function
Implements QImageIOHandler.
Definition at line 388 of file qmnghandler.cpp.
Referenced by QMngPlugin::capabilities(), createReadHandlerHelper(), and read().
 {
     Q_D(const QMngHandler);
     if ((!d->haveReadNone
          && (!d->haveReadAll || (d->haveReadAll && (d->nextIndex < d->frameCount))))
         || canRead(device()))
     {
         setFormat("mng");
         return true;
     }
     return false;
 }
canRead() [2/2]
bool QMngHandler::canRead (QIODevice * device) static
Warning
This function is not part of the public interface.
Definition at line 402 of file qmnghandler.cpp.
 {
     if (!device) {
         qWarning("QMngHandler::canRead() called with no device");
         return false;
     }
     return device->peek(8) == "\x8A\x4D\x4E\x47\x0D\x0A\x1A\x0A";
 }
currentImageNumber()
int QMngHandler::currentImageNumber () const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 433 of file qmnghandler.cpp.
 {
     Q_D(const QMngHandler);
     return d->currentImageNumber();
 }
imageCount()
int QMngHandler::imageCount () const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 440 of file qmnghandler.cpp.
 {
     Q_D(const QMngHandler);
     return d->imageCount();
 }
jumpToImage()
bool QMngHandler::jumpToImage (int imageNumber) virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 447 of file qmnghandler.cpp.
 {
     Q_D(QMngHandler);
     return d->jumpToImage(imageNumber);
 }
jumpToNextImage()
bool QMngHandler::jumpToNextImage () virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 454 of file qmnghandler.cpp.
 {
     Q_D(QMngHandler);
     return d->jumpToNextImage();
 }
loopCount()
int QMngHandler::loopCount () const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 461 of file qmnghandler.cpp.
 {
     Q_D(const QMngHandler);
     if (d->iterCount == 0x7FFFFFFF)
         return -1; // infinite loop
     return d->iterCount-1;
 }
name()
QByteArray QMngHandler::name () const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 413 of file qmnghandler.cpp.
 {
     return "mng";
 }
nextImageDelay()
int QMngHandler::nextImageDelay () const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 470 of file qmnghandler.cpp.
 {
     Q_D(const QMngHandler);
     return d->nextImageDelay();
 }
option()
QVariant QMngHandler::option (ImageOption option) const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 477 of file qmnghandler.cpp.
 {
     Q_D(const QMngHandler);
     if (option == QImageIOHandler::Animation)
         return true;
     else if (option == QImageIOHandler::BackgroundColor)
         return d->backgroundColor();
     return QVariant();
 }
read()
bool QMngHandler::read (QImage * image) virtual
Reimplemented Function
Implements QImageIOHandler.
Definition at line 419 of file qmnghandler.cpp.
 {
     Q_D(QMngHandler);
     return canRead() ? d->getNextImage(image) : false;
 }
setOption()
void QMngHandler::setOption (ImageOption option, const QVariant & value) virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 488 of file qmnghandler.cpp.
 {
     Q_D(QMngHandler);
     if (option == QImageIOHandler::BackgroundColor)
         d->setBackgroundColor(qvariant_cast<QColor>(value));
 }
supportsOption()
bool QMngHandler::supportsOption (ImageOption option) const virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 496 of file qmnghandler.cpp.
 {
     if (option == QImageIOHandler::Animation)
         return true;
     else if (option == QImageIOHandler::BackgroundColor)
         return true;
     return false;
 }
write()
bool QMngHandler::write (const QImage & image) virtual
Reimplemented Function
Reimplemented from QImageIOHandler.
Definition at line 426 of file qmnghandler.cpp.
 {
     Q_D(QMngHandler);
     return d->writeImage(image);
 }
Properties
d_ptr
QScopedPointer<QMngHandlerPrivate> QMngHandler::d_ptr private
Definition at line 78 of file qmnghandler_p.h.
The documentation for this class was generated from the following files:
/src/gui/image/qmnghandler_p.h
/src/gui/image/qmnghandler.cpp