Qt 4.8: QTextFrameFormat Class Reference
QTextFrameFormat Class Reference
The QTextFrameFormat class provides formatting information for frames in a QTextDocument.
#include <qtextformat.h>
Public Types
enum BorderStyle {
BorderStyle_None, BorderStyle_Dotted, BorderStyle_Dashed, BorderStyle_Solid,
BorderStyle_Double, BorderStyle_DotDash, BorderStyle_DotDotDash, BorderStyle_Groove,
BorderStyle_Ridge, BorderStyle_Inset, BorderStyle_Outset
}
This enum describes different border styles for the text frame.
enum Position { InFlow, FloatLeft, FloatRight }
This enum describes how a frame is located relative to the surrounding text.
Public Types inherited from QTextFormat
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Public Functions
qreal border () const
Returns the width of the border in pixels.
QBrush borderBrush () const
Returns the brush used for the frame's border.
BorderStyle borderStyle () const
Returns the style of the frame's border.
qreal bottomMargin () const
Returns the width of the frame's bottom margin in pixels.
QTextLength height () const
Returns the height of the frame's border rectangle.
bool isValid () const
Returns true if the format description is valid; otherwise returns false.
qreal leftMargin () const
Returns the width of the frame's left margin in pixels.
qreal margin () const
Returns the width of the frame's external margin in pixels.
qreal padding () const
Returns the width of the frame's internal padding in pixels.
PageBreakFlags pageBreakPolicy () const
Returns the currently set page break policy for the frame/table.
Position position () const
Returns the positioning policy for frames with this frame format.
QTextFrameFormat ()
Constructs a text frame format object with the default properties.
qreal rightMargin () const
Returns the width of the frame's right margin in pixels.
void setBorder (qreal border)
Sets the width (in pixels) of the frame's border.
void setBorderBrush (const QBrush &brush)
Sets the brush used for the frame's border.
void setBorderStyle (BorderStyle style)
Sets the style of the frame's border.
void setBottomMargin (qreal margin)
Sets the frame's bottom margin in pixels.
void setHeight (qreal height)
Sets the frame's height.
void setHeight (const QTextLength &height)
Sets the frame's height.
void setLeftMargin (qreal margin)
Sets the frame's left margin in pixels.
void setMargin (qreal margin)
Sets the frame's margin in pixels.
void setPadding (qreal padding)
Sets the width of the frame's internal padding in pixels.
void setPageBreakPolicy (PageBreakFlags flags)
Sets the page break policy for the frame/table to policy.
void setPosition (Position f)
Sets the policy for positioning frames with this frame format.
void setRightMargin (qreal margin)
Sets the frame's right margin in pixels.
void setTopMargin (qreal margin)
Sets the frame's top margin in pixels.
void setWidth (qreal width)
Convenience method that sets the width of the frame's border rectangle's width to the specified fixed width.
void setWidth (const QTextLength &length)
Sets the frame's border rectangle's width.
qreal topMargin () const
Returns the width of the frame's top margin in pixels.
QTextLength width () const
Returns the width of the frame's border rectangle.
Public Functions inherited from QTextFormat
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Protected Functions
QTextFrameFormat (const QTextFormat &fmt)
Creates a new frame format with the same attributes as the given text format.
Friends
class QTextFormat
Detailed Description
The QTextFrameFormat class provides formatting information for frames in a QTextDocument.
Note
This class or function is reentrant.
A text frame groups together one or more blocks of text, providing a layer of structure larger than the paragraph. The format of a frame specifies how it is rendered and positioned on the screen. It does not directly specify the behavior of the text formatting within, but provides constraints on the layout of its children.
The frame format defines the width() and height() of the frame on the screen. Each frame can have a border() that surrounds its contents with a rectangular box. The border is surrounded by a margin() around the frame, and the contents of the frame are kept separate from the border by the frame's padding(). This scheme is similar to the box model used by Cascading Style Sheets for HTML pages.
The position() of a frame is set using setPosition() and determines how it is located relative to the surrounding text.
The validity of a QTextFrameFormat object can be determined with the isValid() function.
See also
QTextFrame QTextBlockFormat
Definition at line 727 of file qtextformat.h.
Enumerations
BorderStyle
enum QTextFrameFormat::BorderStyle
This enum describes different border styles for the text frame.
Since
4.3
BorderStyle_None
BorderStyle_Dotted
BorderStyle_Dashed
BorderStyle_Solid
BorderStyle_Double
BorderStyle_DotDash
BorderStyle_DotDotDash
BorderStyle_Groove
BorderStyle_Ridge
BorderStyle_Inset
BorderStyle_Outset
See also
borderStyle() FrameBorderStyle
Enumerator
BorderStyle_None
BorderStyle_Dotted
BorderStyle_Dashed
BorderStyle_Solid
BorderStyle_Double
BorderStyle_DotDash
BorderStyle_DotDotDash
BorderStyle_Groove
BorderStyle_Ridge
BorderStyle_Inset
BorderStyle_Outset
Definition at line 742 of file qtextformat.h.
                      {
         BorderStyle_None,
         BorderStyle_Dotted,
         BorderStyle_Dashed,
         BorderStyle_Solid,
         BorderStyle_Double,
         BorderStyle_DotDash,
         BorderStyle_DotDotDash,
         BorderStyle_Groove,
         BorderStyle_Ridge,
         BorderStyle_Inset,
         BorderStyle_Outset
     };
Position
enum QTextFrameFormat::Position
This enum describes how a frame is located relative to the surrounding text.
InFlow
FloatLeft
FloatRight
See also
position() CssFloat
Enumerator
InFlow
FloatLeft
FloatRight
Definition at line 734 of file qtextformat.h.
                   {
         InFlow,
         FloatLeft,
         FloatRight
         // ######
 //        Absolute
     };
Constructors and Destructors
QTextFrameFormat() [1/2]
QTextFrameFormat::QTextFrameFormat ()
Constructs a text frame format object with the default properties.
Definition at line 2863 of file qtextformat.cpp.
                                    : QTextFormat(FrameFormat)
 {
     setBorderStyle(BorderStyle_Outset);
     setBorderBrush(Qt::darkGray);
 }
QTextFrameFormat() [2/2]
QTextFrameFormat::QTextFrameFormat (const QTextFormat & other) explicit protected
Creates a new frame format with the same attributes as the given text format.
Warning
This function is not part of the public interface.
Definition at line 2879 of file qtextformat.cpp.
  : QTextFormat(fmt)
 {
 }
Functions
border()
qreal QTextFrameFormat::border () const inline
Returns the width of the border in pixels.
Definition at line 762 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTable(), QTextHtmlExporter::emitTextFrame(), and QTextDocumentLayoutPrivate::layoutFrame().
     { return doubleProperty(FrameBorder); }
borderBrush()
QBrush QTextFrameFormat::borderBrush () const inline
Returns the brush used for the frame's border.
Since
4.3
Definition at line 767 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::drawFrameDecoration(), QTextDocumentLayoutPrivate::drawTableCell(), and QTextHtmlExporter::emitFrameStyle().
     { return brushProperty(FrameBorderBrush); }
borderStyle()
BorderStyle QTextFrameFormat::borderStyle () const inline
Returns the style of the frame's border.
Since
4.3
Definition at line 772 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::drawFrameDecoration(), QTextDocumentLayoutPrivate::drawTableCell(), and QTextHtmlExporter::emitFrameStyle().
     { return static_cast<BorderStyle>(intProperty(FrameBorderStyle)); }
bottomMargin()
qreal QTextFrameFormat::bottomMargin () const
Returns the width of the frame's bottom margin in pixels.
Since
4.3
Definition at line 3045 of file qtextformat.cpp.
Referenced by QGraphicsTextItemPrivate::_q_mouseOnEdge(), QTextHtmlExporter::emitFrameStyle(), QTextDocumentLayoutPrivate::layoutFrame(), QTextHtmlImporter::scanTable(), and QTextOdfWriter::writeFrameFormat().
 {
     if (!hasProperty(FrameBottomMargin))
         return margin();
     return doubleProperty(FrameBottomMargin);
 }
height()
qreal QTextFrameFormat::height () const inline
Returns the height of the frame's border rectangle.
Definition at line 803 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTextFrame(), and QTextDocumentLayoutPrivate::layoutFrame().
     { return lengthProperty(FrameHeight); }
isValid()
QTextFrameFormat::isValid () const inline
Returns true if the format description is valid; otherwise returns false.
Definition at line 732 of file qtextformat.h.
 { return isFrameFormat(); }
leftMargin()
qreal QTextFrameFormat::leftMargin () const
Returns the width of the frame's left margin in pixels.
Since
4.3
Definition at line 3071 of file qtextformat.cpp.
Referenced by QGraphicsTextItemPrivate::_q_mouseOnEdge(), QTextHtmlExporter::emitFrameStyle(), QTextDocumentLayoutPrivate::layoutFrame(), QTextHtmlImporter::scanTable(), and QTextOdfWriter::writeFrameFormat().
 {
     if (!hasProperty(FrameLeftMargin))
         return margin();
     return doubleProperty(FrameLeftMargin);
 }
margin()
qreal QTextFrameFormat::margin () const inline
Returns the width of the frame's external margin in pixels.
Definition at line 776 of file qtextformat.h.
Referenced by bottomMargin(), leftMargin(), rightMargin(), and topMargin().
     { return doubleProperty(FrameMargin); }
padding()
qreal QTextFrameFormat::padding () const inline
Returns the width of the frame's internal padding in pixels.
Definition at line 792 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::layoutFrame().
     { return doubleProperty(FramePadding); }
pageBreakPolicy()
QTextFormat::PageBreakFlags QTextFrameFormat::pageBreakPolicy () const inline
Returns the currently set page break policy for the frame/table.
Since
4.2
The default is QTextFormat::PageBreak_Auto.
See also
setPageBreakPolicy()
Definition at line 808 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitFrameStyle(), and QTextDocumentLayoutPrivate::layoutFlow().
     { return PageBreakFlags(intProperty(PageBreakPolicy)); }
position()
Position QTextFrameFormat::position () const inline
Returns the positioning policy for frames with this frame format.
Definition at line 758 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::drawFlow(), QTextHtmlExporter::emitFrameStyle(), QTextDocumentLayoutPrivate::floatMargins(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::positionFloat(), and QTextDocumentLayout::resizeInlineObject().
     { return static_cast<Position>(intProperty(CssFloat)); }
rightMargin()
qreal QTextFrameFormat::rightMargin () const
Returns the width of the frame's right margin in pixels.
Since
4.3
Definition at line 3097 of file qtextformat.cpp.
Referenced by QGraphicsTextItemPrivate::_q_mouseOnEdge(), QTextHtmlExporter::emitFrameStyle(), QTextDocumentLayoutPrivate::layoutFrame(), QTextHtmlImporter::scanTable(), and QTextOdfWriter::writeFrameFormat().
 {
     if (!hasProperty(FrameRightMargin))
         return margin();
     return doubleProperty(FrameRightMargin);
 }
setBorder()
void QTextFrameFormat::setBorder (qreal border) inline
Sets the width (in pixels) of the frame's border.
Definition at line 816 of file qtextformat.h.
Referenced by QTextTableFormat::QTextTableFormat(), and QTextHtmlImporter::scanTable().
 { setProperty(FrameBorder, aborder); }
setBorderBrush()
QTextFrameFormat::setBorderBrush (const QBrush & brush) inline
Sets the brush used for the frame's border.
Since
4.3
Definition at line 765 of file qtextformat.h.
Referenced by QTextFrameFormat(), and QTextHtmlImporter::scanTable().
     { setProperty(FrameBorderBrush, brush); }
setBorderStyle()
QTextFrameFormat::setBorderStyle (BorderStyle style) inline
Sets the style of the frame's border.
Since
4.3
Definition at line 770 of file qtextformat.h.
Referenced by QTextFrameFormat(), and QTextHtmlImporter::scanTable().
     { setProperty(FrameBorderStyle, style); }
setBottomMargin()
void QTextFrameFormat::setBottomMargin (qreal margin) inline
Sets the frame's bottom margin in pixels.
Since
4.3
Definition at line 833 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(FrameBottomMargin, amargin); }
setHeight() [1/2]
void QTextFrameFormat::setHeight (qreal height) inline
Sets the frame's height.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 825 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(FrameHeight, QTextLength(QTextLength::FixedLength, aheight)); }
setHeight() [2/2]
void QTextFrameFormat::setHeight (const QTextLength & height) inline
Sets the frame's height.
Definition at line 827 of file qtextformat.h.
 { setProperty(FrameHeight, aheight); }
setLeftMargin()
void QTextFrameFormat::setLeftMargin (qreal margin) inline
Sets the frame's left margin in pixels.
Since
4.3
Definition at line 836 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(FrameLeftMargin, amargin); }
setMargin()
void QTextFrameFormat::setMargin (qreal margin)
Sets the frame's margin in pixels.
This method also sets the left, right, top and bottom margins of the frame to the same value. The individual margins override the general margin.
Definition at line 2981 of file qtextformat.cpp.
Referenced by QLabelPrivate::ensureTextLayouted(), QTextDocumentPrivate::rootFrame(), QTextDocument::setDocumentMargin(), and QTextHtmlExporter::toHtml().
 {
     setProperty(FrameMargin, amargin);
     setProperty(FrameTopMargin, amargin);
     setProperty(FrameBottomMargin, amargin);
     setProperty(FrameLeftMargin, amargin);
     setProperty(FrameRightMargin, amargin);
 }
setPadding()
void QTextFrameFormat::setPadding (qreal padding) inline
Sets the width of the frame's internal padding in pixels.
Definition at line 819 of file qtextformat.h.
 { setProperty(FramePadding, apadding); }
setPageBreakPolicy()
void QTextFrameFormat::setPageBreakPolicy (PageBreakFlags policy) inline
Sets the page break policy for the frame/table to policy.
Since
4.2
See also
pageBreakPolicy()
Definition at line 806 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
     { setProperty(PageBreakPolicy, int(flags)); }
setPosition()
QTextFrameFormat::setPosition (Position f) inline
Sets the policy for positioning frames with this frame format.
Definition at line 756 of file qtextformat.h.
Referenced by QTextCursor::insertImage(), and QTextHtmlImporter::scanTable().
     { setProperty(CssFloat, f); }
setRightMargin()
void QTextFrameFormat::setRightMargin (qreal margin) inline
Sets the frame's right margin in pixels.
Since
4.3
Definition at line 839 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(FrameRightMargin, amargin); }
setTopMargin()
void QTextFrameFormat::setTopMargin (qreal margin) inline
Sets the frame's top margin in pixels.
Since
4.3
Definition at line 830 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(FrameTopMargin, amargin); }
setWidth() [1/2]
void QTextFrameFormat::setWidth (qreal width) inline
Convenience method that sets the width of the frame's border rectangle's width to the specified fixed width.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 822 of file qtextformat.h.
Referenced by QTextHtmlImporter::scanTable().
 { setProperty(FrameWidth, QTextLength(QTextLength::FixedLength, awidth)); }
setWidth() [2/2]
QTextFrameFormat::setWidth (const QTextLength & width) inline
Sets the frame's border rectangle's width.
See also
QTextLength
Definition at line 796 of file qtextformat.h.
     { setProperty(FrameWidth, length); }
topMargin()
qreal QTextFrameFormat::topMargin () const
Returns the width of the frame's top margin in pixels.
Since
4.3
Definition at line 3019 of file qtextformat.cpp.
Referenced by QGraphicsTextItemPrivate::_q_mouseOnEdge(), QTextHtmlExporter::emitFrameStyle(), QTextDocumentLayoutPrivate::layoutFrame(), QTextHtmlImporter::scanTable(), and QTextOdfWriter::writeFrameFormat().
 {
     if (!hasProperty(FrameTopMargin))
         return margin();
     return doubleProperty(FrameTopMargin);
 }
width()
QTextLength QTextFrameFormat::width () const inline
Returns the width of the frame's border rectangle.
See also
QTextLength
Definition at line 798 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitTable(), QTextHtmlExporter::emitTextFrame(), QTextDocumentLayoutPrivate::layoutFrame(), and QTextDocumentLayoutPrivate::layoutTable().
     { return lengthProperty(FrameWidth); }
Friends and Related Functions
QTextFormat
friend class QTextFormat friend
Definition at line 813 of file qtextformat.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp