Qt 4.8: QGraphicsEffectSourcePrivate Class Reference
QGraphicsEffectSourcePrivate Class Reference abstract
#include <qgraphicseffect_p.h>
Public Types
enum InvalidateReason { TransformChanged, EffectRectChanged, SourceChanged }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
virtual QRectF boundingRect (Qt::CoordinateSystem system) const =0
QGraphicsEffect::PixmapPadMode currentCachedMode () const
Qt::CoordinateSystem currentCachedSystem () const
virtual void detach ()=0
virtual QRect deviceRect () const =0
virtual void draw (QPainter *p)=0
virtual void effectBoundingRectChanged ()=0
virtual const QGraphicsItem * graphicsItem () const =0
void invalidateCache (InvalidateReason reason=SourceChanged) const
virtual bool isPixmap () const =0
virtual QPixmap pixmap (Qt::CoordinateSystem system, QPoint *offset=0, QGraphicsEffect::PixmapPadMode mode=QGraphicsEffect::PadToTransparentBorder) const =0
QGraphicsEffectSourcePrivate ()
void setCachedOffset (const QPoint &offset)
virtual const QStyleOption * styleOption () const =0
virtual void update ()=0
virtual const QWidget * widget () const =0
virtual ~QGraphicsEffectSourcePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Properties
QGraphicsEffect::PixmapPadMode m_cachedMode
QPoint m_cachedOffset
Qt::CoordinateSystem m_cachedSystem
QPixmapCache::Key m_cacheKey
Friends
class QGraphicsItem
class QGraphicsItemPrivate
class QGraphicsScenePrivate
Additional Inherited Members
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Detailed Description
Definition at line 101 of file qgraphicseffect_p.h.
Enumerations
InvalidateReason
enum QGraphicsEffectSourcePrivate::InvalidateReason
Enumerator
TransformChanged
EffectRectChanged
SourceChanged
Definition at line 111 of file qgraphicseffect_p.h.
     {
         TransformChanged,
         EffectRectChanged,
         SourceChanged
     };
Constructors and Destructors
QGraphicsEffectSourcePrivate()
QGraphicsEffectSourcePrivate::QGraphicsEffectSourcePrivate () inline
Definition at line 105 of file qgraphicseffect_p.h.
         : QObjectPrivate()
         , m_cachedSystem(Qt::DeviceCoordinates)
         , m_cachedMode(QGraphicsEffect::PadToTransparentBorder)
     {}
~QGraphicsEffectSourcePrivate()
QGraphicsEffectSourcePrivate::~QGraphicsEffectSourcePrivate () virtual
Definition at line 378 of file qgraphicseffect.cpp.
 {
     invalidateCache();
 }
Functions
boundingRect()
virtual QRectF QGraphicsEffectSourcePrivate::boundingRect (Qt::CoordinateSystem system) const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
currentCachedMode()
QGraphicsEffect::PixmapPadMode QGraphicsEffectSourcePrivate::currentCachedMode () const inline
Definition at line 135 of file qgraphicseffect_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive().
 { return m_cachedMode; }
currentCachedSystem()
Qt::CoordinateSystem QGraphicsEffectSourcePrivate::currentCachedSystem () const inline
Definition at line 134 of file qgraphicseffect_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive().
 { return m_cachedSystem; }
detach()
virtual void QGraphicsEffectSourcePrivate::detach () pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
deviceRect()
virtual QRect QGraphicsEffectSourcePrivate::deviceRect () const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
draw()
virtual void QGraphicsEffectSourcePrivate::draw (QPainter * p) pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
effectBoundingRectChanged()
virtual void QGraphicsEffectSourcePrivate::effectBoundingRectChanged () pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
graphicsItem()
virtual const QGraphicsItem* QGraphicsEffectSourcePrivate::graphicsItem () const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
invalidateCache()
void QGraphicsEffectSourcePrivate::invalidateCache (InvalidateReason reason = SourceChanged) const
Definition at line 388 of file qgraphicseffect.cpp.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), and QWidgetPrivate::drawWidget().
 {
     if (m_cachedMode != QGraphicsEffect::PadToEffectiveBoundingRect
         && (reason == EffectRectChanged
             || (reason == TransformChanged && m_cachedSystem == Qt::LogicalCoordinates))) {
         return;
     }
     QPixmapCache::remove(m_cacheKey);
 }
isPixmap()
virtual bool QGraphicsEffectSourcePrivate::isPixmap () const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
pixmap()
virtual QPixmap QGraphicsEffectSourcePrivate::pixmap (Qt::CoordinateSystem system, QPoint * offset = 0, QGraphicsEffect::PixmapPadMode mode = QGraphicsEffect::PadToTransparentBorder) const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
setCachedOffset()
void QGraphicsEffectSourcePrivate::setCachedOffset (const QPoint & offset)
Definition at line 383 of file qgraphicseffect.cpp.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive().
 {
     m_cachedOffset = offset;
 }
styleOption()
virtual const QStyleOption* QGraphicsEffectSourcePrivate::styleOption () const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
update()
virtual void QGraphicsEffectSourcePrivate::update () pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
widget()
virtual const QWidget* QGraphicsEffectSourcePrivate::widget () const pure virtual
Implemented in QWidgetEffectSourcePrivate, and QGraphicsItemEffectSourcePrivate.
Friends and Related Functions
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 138 of file qgraphicseffect_p.h.
QGraphicsItemPrivate
friend class QGraphicsItemPrivate friend
Definition at line 139 of file qgraphicseffect_p.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 137 of file qgraphicseffect_p.h.
Properties
m_cachedMode
QGraphicsEffect::PixmapPadMode QGraphicsEffectSourcePrivate::m_cachedMode mutable private
Definition at line 143 of file qgraphicseffect_p.h.
m_cachedOffset
QPoint QGraphicsEffectSourcePrivate::m_cachedOffset mutable private
Definition at line 144 of file qgraphicseffect_p.h.
m_cachedSystem
Qt::CoordinateSystem QGraphicsEffectSourcePrivate::m_cachedSystem mutable private
Definition at line 142 of file qgraphicseffect_p.h.
m_cacheKey
QPixmapCache::Key QGraphicsEffectSourcePrivate::m_cacheKey mutable private
Definition at line 145 of file qgraphicseffect_p.h.
The documentation for this class was generated from the following files:
/src/gui/effects/qgraphicseffect_p.h
/src/gui/effects/qgraphicseffect.cpp