Qt 4.8: QFontInfo Class Reference
QFontInfo Class Reference
The QFontInfo class provides general information about fonts.
#include <qfontinfo.h>
Public Functions
bool bold () const
Returns true if weight() would return a value greater than QFont::Normal; otherwise returns false.
bool exactMatch () const
Returns true if the matched window system font is exactly the same as the one specified by the font; otherwise returns false.
QString family () const
Returns the family name of the matched window system font.
bool fixedPitch () const
Returns the fixed pitch value of the matched window system font.
bool italic () const
Returns the italic value of the matched window system font.
QFontInfo & operator= (const QFontInfo &)
Assigns the font info in fi.
bool overline () const
Returns the overline value of the matched window system font.
int pixelSize () const
Returns the pixel size of the matched window system font.
int pointSize () const
Returns the point size of the matched window system font.
qreal pointSizeF () const
Returns the point size of the matched window system font.
QFontInfo (const QFont &)
Constructs a font info object for font.
QFontInfo (const QFontInfo &)
Constructs a copy of fi.
bool rawMode () const
Returns true if the font is a raw mode font; otherwise returns false.
bool strikeOut () const
Returns the strikeout value of the matched window system font.
QFont::Style style () const
Returns the style value of the matched window system font.
QFont::StyleHint styleHint () const
Returns the style of the matched window system font.
QString styleName () const
Returns the style name of the matched window system font on system that supports it.
bool underline () const
Returns the underline value of the matched window system font.
int weight () const
Returns the weight of the matched window system font.
~QFontInfo ()
Destroys the font info object.
Properties
QExplicitlySharedDataPointer< QFontPrivate > d
Detailed Description
The QFontInfo class provides general information about fonts.
Note
This class or function is reentrant.
The QFontInfo class provides the same access functions as QFont, e.g. family(), pointSize(), italic(), weight(), fixedPitch(), styleHint() etc. But whilst the QFont access functions return the values that were set, a QFontInfo object returns the values that apply to the font that will actually be used to draw the text.
For example, when the program asks for a 25pt Courier font on a machine that has a non-scalable 24pt Courier font, QFont will (normally) use the 24pt Courier for rendering. In this case, QFont::pointSize() returns 25 and QFontInfo::pointSize() returns 24.
There are three ways to create a QFontInfo object.
Calling the QFontInfo constructor with a QFont creates a font info object for a screen-compatible font, i.e. the font cannot be a printer font. If the font is changed later, the font info object is not updated.
(Note: If you use a printer font the values returned may be inaccurate. Printer fonts are not always accessible so the nearest screen font is used if a printer font is supplied.)
QWidget::fontInfo() returns the font info for a widget's font. This is equivalent to calling QFontInfo(widget->font()). If the widget's font is changed later, the font info object is not updated.
QPainter::fontInfo() returns the font info for a painter's current font. If the painter's font is changed later, the font info object is not updated.
See also
QFont QFontMetrics QFontDatabase
Definition at line 54 of file qfontinfo.h.
Constructors and Destructors
QFontInfo() [1/2]
QFontInfo::QFontInfo (const QFont & font)
Constructs a font info object for font.
The font must be screen-compatible, i.e. a font you use when drawing text in widgets or pixmaps, not QPicture or QPrinter.
The font info object holds the information for the font that is passed in the constructor at the time it is created, and is not updated if the font's attributes are changed later.
Use QPainter::fontInfo() to get the font info when painting. This will give correct results also when painting on paint device that is not screen-compatible.
Definition at line 2634 of file qfont.cpp.
     : d(font.d.data())
 {
 }
QFontInfo() [2/2]
QFontInfo::QFontInfo (const QFontInfo & fi)
Constructs a copy of fi.
Definition at line 2642 of file qfont.cpp.
     : d(fi.d.data())
 {
 }
~QFontInfo()
QFontInfo::~QFontInfo ()
Destroys the font info object.
Definition at line 2650 of file qfont.cpp.
 {
 }
Functions
bold()
bool QFontInfo::bold () const inline
Returns true if weight() would return a value greater than QFont::Normal; otherwise returns false.
See also
weight(), QFont::bold()
Definition at line 71 of file qfontinfo.h.
 { return weight() > QFont::Normal; }
exactMatch()
bool QFontInfo::exactMatch () const
Returns true if the matched window system font is exactly the same as the one specified by the font; otherwise returns false.
See also
QFont::exactMatch()
Definition at line 2878 of file qfont.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return (d->rawMode
             ? engine->type() != QFontEngine::Box
             : d->request.exactMatch(engine->fontDef));
 }
family()
QString QFontInfo::family () const
Returns the family name of the matched window system font.
See also
QFont::family()
Definition at line 2668 of file qfont.cpp.
Referenced by QFontComboBoxPrivate::_q_updateModel(), and qt_set_x11_resources().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->fontDef.family;
 }
fixedPitch()
bool QFontInfo::fixedPitch () const
Returns the fixed pitch value of the matched window system font.
See also
QFont::fixedPitch()
Definition at line 2826 of file qfont.cpp.
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
 #ifdef Q_OS_MAC
     if (!engine->fontDef.fixedPitchComputed) {
         QChar ch[2] = { QLatin1Char('i'), QLatin1Char('m') };
         QGlyphLayoutArray<2> g;
         int l = 2;
         engine->stringToCMap(ch, 2, &g, &l, 0);
         engine->fontDef.fixedPitch = g.advances_x[0] == g.advances_x[1];
         engine->fontDef.fixedPitchComputed = true;
     }
 #endif
     return engine->fontDef.fixedPitch;
 }
italic()
bool QFontInfo::italic () const
Returns the italic value of the matched window system font.
See also
QFont::italic()
Definition at line 2734 of file qfont.cpp.
Referenced by qt_set_x11_resources().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->fontDef.style != QFont::StyleNormal;
 }
operator=()
QFontInfo & QFontInfo::operator= (const QFontInfo & fi)
Assigns the font info in fi.
Definition at line 2657 of file qfont.cpp.
 {
     d = fi.d.data();
     return *this;
 }
overline()
bool QFontInfo::overline () const
Returns the overline value of the matched window system font.
See also
QFont::overline()
Warning
This function is not part of the public interface.
Here we read the overline flag directly from the QFont. This is OK for X11 and for Windows because we always get what we want.
Definition at line 2803 of file qfont.cpp.
 {
     return d->overline;
 }
pixelSize()
int QFontInfo::pixelSize () const
Returns the pixel size of the matched window system font.
See also
QFont::pointSize()
Definition at line 2722 of file qfont.cpp.
Referenced by QVGFontEngineCleaner::fontEngineDestroyed(), and qt_set_x11_resources().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->fontDef.pixelSize;
 }
pointSize()
int QFontInfo::pointSize () const
Returns the point size of the matched window system font.
See also
pointSizeF() QFont::pointSize()
Definition at line 2698 of file qfont.cpp.
Referenced by QFontDialog::setCurrentFont().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return qRound(engine->fontDef.pointSize);
 }
pointSizeF()
qreal QFontInfo::pointSizeF () const
Returns the point size of the matched window system font.
See also
QFont::pointSizeF()
Definition at line 2710 of file qfont.cpp.
Referenced by QCleanlooksStyle::drawControl(), and QMacStyle::drawControl().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->fontDef.pointSize;
 }
rawMode()
bool QFontInfo::rawMode () const
Returns true if the font is a raw mode font; otherwise returns false.
If it is a raw mode font, all other functions in QFontInfo will return the same values set in the QFont, regardless of the font actually used.
See also
QFont::rawMode()
Definition at line 2867 of file qfont.cpp.
Referenced by qt_set_x11_resources().
 {
     return d->rawMode;
 }
strikeOut()
bool QFontInfo::strikeOut () const
Returns the strikeout value of the matched window system font.
See also
QFont::strikeOut()
Warning
This function is not part of the public interface. Here we read the strikeOut flag directly from the QFont. This is OK for X11 and for Windows because we always get what we want.
Definition at line 2816 of file qfont.cpp.
Referenced by qt_set_x11_resources().
 {
     return d->strikeOut;
 }
style()
QFont::Style QFontInfo::style () const
Returns the style value of the matched window system font.
See also
QFont::style()
Definition at line 2746 of file qfont.cpp.
Referenced by QFontDatabase::styleString().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return (QFont::Style)engine->fontDef.style;
 }
styleHint()
QFont::StyleHint QFontInfo::styleHint () const
Returns the style of the matched window system font.
Currently only returns the style hint set in QFont.
See also
QFont::styleHint() QFont::StyleHint
Definition at line 2850 of file qfont.cpp.
Referenced by qt_set_x11_resources().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return (QFont::StyleHint) engine->fontDef.styleHint;
 }
styleName()
QString QFontInfo::styleName () const
Returns the style name of the matched window system font on system that supports it.
Since
4.8
See also
QFont::styleName()
Definition at line 2686 of file qfont.cpp.
Referenced by QFontDatabase::styleString().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->fontDef.styleName;
 }
underline()
bool QFontInfo::underline () const
Returns the underline value of the matched window system font.
See also
QFont::underline()
Warning
This function is not part of the public interface.
Here we read the underline flag directly from the QFont. This is OK for X11 and for Windows because we always get what we want.
Definition at line 2788 of file qfont.cpp.
Referenced by qt_set_x11_resources().
 {
     return d->underline;
 }
weight()
int QFontInfo::weight () const
Returns the weight of the matched window system font.
See also
QFont::weight(), bold()
Definition at line 2758 of file qfont.cpp.
Referenced by qt_set_x11_resources(), and QFontDatabase::styleString().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return engine->fontDef.weight;
 }
Properties
d
QExplicitlySharedDataPointer<QFontPrivate> QFontInfo::d private
Definition at line 82 of file qfontinfo.h.
Referenced by exactMatch(), family(), fixedPitch(), italic(), operator=(), overline(), pixelSize(), pointSize(), pointSizeF(), rawMode(), strikeOut(), style(), styleHint(), styleName(), underline(), and weight().
The documentation for this class was generated from the following files:
/src/gui/text/qfontinfo.h
/src/gui/text/qfont.cpp