Qt 4.8: QNetworkRequest Class Reference
QNetworkRequest Class Reference
The QNetworkRequest class holds a request to be sent with QNetworkAccessManager.
#include <qnetworkrequest.h>
Public Types
enum Attribute {
HttpStatusCodeAttribute, HttpReasonPhraseAttribute, RedirectionTargetAttribute, ConnectionEncryptedAttribute,
CacheLoadControlAttribute, CacheSaveControlAttribute, SourceIsFromCacheAttribute, DoNotBufferUploadDataAttribute,
HttpPipeliningAllowedAttribute, HttpPipeliningWasUsedAttribute, CustomVerbAttribute, CookieLoadControlAttribute,
AuthenticationReuseAttribute, CookieSaveControlAttribute, MaximumDownloadBufferSizeAttribute, DownloadBufferAttribute,
SynchronousRequestAttribute, User = 1000, UserMax = 32767
}
Attribute codes for the QNetworkRequest and QNetworkReply.
enum CacheLoadControl { AlwaysNetwork, PreferNetwork, PreferCache, AlwaysCache }
Controls the caching mechanism of QNetworkAccessManager.
enum KnownHeaders {
ContentTypeHeader, ContentLengthHeader, LocationHeader, LastModifiedHeader,
CookieHeader, SetCookieHeader, ContentDispositionHeader
}
List of known header types that QNetworkRequest parses.
enum LoadControl { Automatic = 0, Manual }
Indicates if an aspect of the request's loading mechanism has been manually overridden, e.
enum Priority { HighPriority = 1, NormalPriority = 3, LowPriority = 5 }
This enum lists the possible network request priorities.
Public Functions
QVariant attribute (Attribute code, const QVariant &defaultValue=QVariant()) const
Returns the attribute associated with the code code.
bool hasRawHeader (const QByteArray &headerName) const
Returns true if the raw header headerName is present in this network request.
QVariant header (KnownHeaders header) const
Returns the value of the known network header header if it is present in this request.
bool operator!= (const QNetworkRequest &other) const
Returns false if this object is not the same as other.
QNetworkRequest & operator= (const QNetworkRequest &other)
Creates a copy of other.
bool operator== (const QNetworkRequest &other) const
Returns true if this object is the same as other (i.e., if they have the same URL, same headers and same meta-data settings).
QObject * originatingObject () const
Returns a reference to the object that initiated this network request; returns 0 if not set or the object has been destroyed.
Priority priority () const
Return the priority of this request.
QNetworkRequest (const QUrl &url=QUrl())
Constructs a QNetworkRequest object with url as the URL to be requested.
QNetworkRequest (const QNetworkRequest &other)
Creates a copy of other.
QByteArray rawHeader (const QByteArray &headerName) const
Returns the raw form of header headerName.
QList< QByteArray > rawHeaderList () const
Returns a list of all raw headers that are set in this network request.
void setAttribute (Attribute code, const QVariant &value)
Sets the attribute associated with code code to be value value.
void setHeader (KnownHeaders header, const QVariant &value)
Sets the value of the known header header to be value, overriding any previously set headers.
void setOriginatingObject (QObject *object)
Allows setting a reference to the object initiating the request.
void setPriority (Priority priority)
Set the priority of this request to priority.
void setRawHeader (const QByteArray &headerName, const QByteArray &value)
Sets the header headerName to be of value headerValue.
void setSslConfiguration (const QSslConfiguration &configuration)
Sets this network request's SSL configuration to be config.
void setUrl (const QUrl &url)
Sets the URL this network request is referring to to be url.
QSslConfiguration sslConfiguration () const
Returns this network request's SSL configuration.
QUrl url () const
Returns the URL this network request is referring to.
~QNetworkRequest ()
Disposes of the QNetworkRequest object.
Properties
QSharedDataPointer< QNetworkRequestPrivate > d
Friends
class QNetworkRequestPrivate
Detailed Description
The QNetworkRequest class holds a request to be sent with QNetworkAccessManager.
Since
4.4
Attention
Module: QtNetwork
QNetworkRequest is part of the Network Access API and is the class holding the information necessary to send a request over the network. It contains a URL and some ancillary information that can be used to modify the request.
See also
QNetworkReply, QNetworkAccessManager
Definition at line 59 of file qnetworkrequest.h.
Enumerations
Attribute
enum QNetworkRequest::Attribute
Attribute codes for the QNetworkRequest and QNetworkReply.
Since
4.7
Attributes are extra meta-data that are used to control the behavior of the request and to pass further information from the reply back to the application. Attributes are also extensible, allowing custom implementations to pass custom values.
The following table explains what the default attribute codes are, the QVariant types associated, the default value if said attribute is missing and whether it's used in requests or replies.
HttpStatusCodeAttribute Replies only, type: QVariant::Int (no default) Indicates the HTTP status code received from the HTTP server (like 200, 304, 404, 401, etc.). If the connection was not HTTP-based, this attribute will not be present.
HttpReasonPhraseAttribute Replies only, type: QVariant::ByteArray (no default) Indicates the HTTP reason phrase as received from the HTTP server (like "Ok", "Found", "Not Found", "Access Denied", etc.) This is the human-readable representation of the status code (see above). If the connection was not HTTP-based, this attribute will not be present.
RedirectionTargetAttribute Replies only, type: QVariant::Url (no default) If present, it indicates that the server is redirecting the request to a different URL. The Network Access API does not by default follow redirections: it's up to the application to determine if the requested redirection should be allowed, according to its security policies. The returned URL might be relative. Use QUrl::resolved() to create an absolute URL out of it.
ConnectionEncryptedAttribute Replies only, type: QVariant::Bool (default: false) Indicates whether the data was obtained through an encrypted (secure) connection.
CacheLoadControlAttribute Requests only, type: QVariant::Int (default: QNetworkRequest::PreferNetwork) Controls how the cache should be accessed. The possible values are those of QNetworkRequest::CacheLoadControl. Note that the default QNetworkAccessManager implementation does not support caching. However, this attribute may be used by certain backends to modify their requests (for example, for caching proxies).
CacheSaveControlAttribute Requests only, type: QVariant::Bool (default: true) Controls if the data obtained should be saved to cache for future uses. If the value is false, the data obtained will not be automatically cached. If true, data may be cached, provided it is cacheable (what is cacheable depends on the protocol being used).
SourceIsFromCacheAttribute Replies only, type: QVariant::Bool (default: false) Indicates whether the data was obtained from cache or not.
DoNotBufferUploadDataAttribute Requests only, type: QVariant::Bool (default: false) Indicates whether the QNetworkAccessManager code is allowed to buffer the upload data, e.g. when doing a HTTP POST. When using this flag with sequential upload data, the ContentLengthHeader header must be set.
HttpPipeliningAllowedAttribute Requests only, type: QVariant::Bool (default: false) Indicates whether the QNetworkAccessManager code is allowed to use HTTP pipelining with this request.
HttpPipeliningWasUsedAttribute Replies only, type: QVariant::Bool Indicates whether the HTTP pipelining was used for receiving this reply.
CustomVerbAttribute Requests only, type: QVariant::ByteArray Holds the value for the custom HTTP verb to send (destined for usage of other verbs than GET, POST, PUT and DELETE). This verb is set when calling QNetworkAccessManager::sendCustomRequest().
CookieLoadControlAttribute Requests only, type: QVariant::Int (default: QNetworkRequest::Automatic) Indicates whether to send 'Cookie' headers in the request. This attribute is set to false by QtWebKit when creating a cross-origin XMLHttpRequest where withCredentials has not been set explicitly to true by the Javascript that created the request. See here for more information. (This value was introduced in 4.7.)
CookieSaveControlAttribute Requests only, type: QVariant::Int (default: QNetworkRequest::Automatic) Indicates whether to save 'Cookie' headers received from the server in reply to the request. This attribute is set to false by QtWebKit when creating a cross-origin XMLHttpRequest where withCredentials has not been set explicitly to true by the Javascript that created the request. See here for more information. (This value was introduced in 4.7.)
AuthenticationReuseAttribute Requests only, type: QVariant::Int (default: QNetworkRequest::Automatic) Indicates whether to use cached authorization credentials in the request, if available. If this is set to QNetworkRequest::Manual and the authentication mechanism is 'Basic' or 'Digest', Qt will not send an an 'Authorization' HTTP header with any cached credentials it may have for the request's URL. This attribute is set to QNetworkRequest::Manual by QtWebKit when creating a cross-origin XMLHttpRequest where withCredentials has not been set explicitly to true by the Javascript that created the request. See here for more information. (This value was introduced in 4.7.)
MaximumDownloadBufferSizeAttribute
DownloadBufferAttribute
SynchronousRequestAttribute
User Special type. Additional information can be passed in QVariants with types ranging from User to UserMax. The default implementation of Network Access will ignore any request attributes in this range and it will not produce any attributes in this range in replies. The range is reserved for extensions of QNetworkAccessManager.
UserMax Special type. See User.
Enumerator
HttpStatusCodeAttribute
HttpReasonPhraseAttribute
RedirectionTargetAttribute
ConnectionEncryptedAttribute
CacheLoadControlAttribute
CacheSaveControlAttribute
SourceIsFromCacheAttribute
DoNotBufferUploadDataAttribute
HttpPipeliningAllowedAttribute
HttpPipeliningWasUsedAttribute
CustomVerbAttribute
CookieLoadControlAttribute
AuthenticationReuseAttribute
CookieSaveControlAttribute
MaximumDownloadBufferSizeAttribute
DownloadBufferAttribute
SynchronousRequestAttribute
User
UserMax
Definition at line 71 of file qnetworkrequest.h.
                    {
         HttpStatusCodeAttribute,
         HttpReasonPhraseAttribute,
         RedirectionTargetAttribute,
         ConnectionEncryptedAttribute,
         CacheLoadControlAttribute,
         CacheSaveControlAttribute,
         SourceIsFromCacheAttribute,
         DoNotBufferUploadDataAttribute,
         HttpPipeliningAllowedAttribute,
         HttpPipeliningWasUsedAttribute,
         CustomVerbAttribute,
         CookieLoadControlAttribute,
         AuthenticationReuseAttribute,
         CookieSaveControlAttribute,
         MaximumDownloadBufferSizeAttribute, // internal
         DownloadBufferAttribute, // internal
         SynchronousRequestAttribute, // internal
         User = 1000,
         UserMax = 32767
     };
CacheLoadControl
enum QNetworkRequest::CacheLoadControl
Controls the caching mechanism of QNetworkAccessManager.
AlwaysNetwork always load from network and do not check if the cache has a valid entry (similar to the "Reload" feature in browsers)
PreferNetwork default value; load from the network if the cached entry is older than the network entry
PreferCache load from cache if available, otherwise load from network. Note that this can return possibly stale (but not expired) items from cache.
AlwaysCache only load from cache, indicating error if the item was not cached (i.e., off-line mode)
Enumerator
AlwaysNetwork
PreferNetwork
PreferCache
AlwaysCache
Definition at line 93 of file qnetworkrequest.h.
{
         AlwaysNetwork,
         PreferNetwork,
         PreferCache,
         AlwaysCache
     };
KnownHeaders
enum QNetworkRequest::KnownHeaders
List of known header types that QNetworkRequest parses.
Each known header is also represented in raw form with its full HTTP name.
ContentTypeHeader corresponds to the HTTP Content-Type header and contains a string containing the media (MIME) type and any auxiliary data (for instance, charset)
ContentLengthHeader corresponds to the HTTP Content-Length header and contains the length in bytes of the data transmitted.
LocationHeader corresponds to the HTTP Location header and contains a URL representing the actual location of the data, including the destination URL in case of redirections.
LastModifiedHeader corresponds to the HTTP Last-Modified header and contains a QDateTime representing the last modification date of the contents
CookieHeader corresponds to the HTTP Cookie header and contains a QList<QNetworkCookie> representing the cookies to be sent back to the server
SetCookieHeader corresponds to the HTTP Set-Cookie header and contains a QList<QNetworkCookie> representing the cookies sent by the server to be stored locally
See also
header(), setHeader(), rawHeader(), setRawHeader()
Enumerator
ContentTypeHeader
ContentLengthHeader
LocationHeader
LastModifiedHeader
CookieHeader
SetCookieHeader
ContentDispositionHeader
Definition at line 62 of file qnetworkrequest.h.
                       {
         ContentTypeHeader,
         ContentLengthHeader,
         LocationHeader,
         LastModifiedHeader,
         CookieHeader,
         SetCookieHeader,
         ContentDispositionHeader  // added for QMultipartMessage
     };
LoadControl
enum QNetworkRequest::LoadControl
Indicates if an aspect of the request's loading mechanism has been manually overridden, e.
Since
4.7
g. by QtWebKit.
\arg \b Automatic            default value: indicates default behaviour.
\arg \b Manual               indicates behaviour has been manually overridden.
Enumerator
Automatic
Manual
Definition at line 99 of file qnetworkrequest.h.
                      {
         Automatic = 0,
         Manual
     };
Priority
enum QNetworkRequest::Priority
This enum lists the possible network request priorities.
Since
4.7
HighPriority High priority
NormalPriority Normal priority
LowPriority Low priority
Enumerator
HighPriority
NormalPriority
LowPriority
Definition at line 104 of file qnetworkrequest.h.
                   {
         HighPriority = 1,
         NormalPriority = 3,
         LowPriority = 5
     };
Constructors and Destructors
QNetworkRequest() [1/2]
QNetworkRequest::QNetworkRequest (const QUrl & url = QUrl()) explicit
Constructs a QNetworkRequest object with url as the URL to be requested.
See also
url(), setUrl()
Definition at line 342 of file qnetworkrequest.cpp.
     : d(new QNetworkRequestPrivate)
 {
     d->url = url;
 }
QNetworkRequest() [2/2]
QNetworkRequest::QNetworkRequest (const QNetworkRequest & other)
Creates a copy of other.
Definition at line 351 of file qnetworkrequest.cpp.
     : d(other.d)
 {
 }
~QNetworkRequest()
QNetworkRequest::~QNetworkRequest ()
Disposes of the QNetworkRequest object.
Definition at line 359 of file qnetworkrequest.cpp.
 {
     // QSharedDataPointer auto deletes
     d = 0;
 }
Functions
attribute()
QVariant QNetworkRequest::attribute (Attribute code, const QVariant & defaultValue = QVariant()) const
Returns the attribute associated with the code code.
If the attribute has not been set, it returns defaultValue.
Note: this function does not apply the defaults listed in QNetworkRequest::Attribute.
See also
setAttribute(), QNetworkRequest::Attribute
Definition at line 514 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QNetworkReplyImplPrivate::createCache(), QNetworkAccessManager::createRequest(), QNetworkReplyImplPrivate::getDownloadBuffer(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkReplyImplPrivate::metaDataChanged(), QNetworkAccessHttpBackend::postRequest(), and QNetworkReplyImplPrivate::setup().
 {
     return d->attributes.value(code, defaultValue);
 }
hasRawHeader()
bool QNetworkRequest::hasRawHeader (const QByteArray & headerName) const
Returns true if the raw header headerName is present in this network request.
See also
rawHeader(), setRawHeader()
Definition at line 446 of file qnetworkrequest.cpp.
Referenced by QDeclarativeXMLHttpRequest::addHeader(), and QNetworkAccessManagerPrivate::prepareMultipart().
 {
     return d->findRawHeader(headerName) != d->rawHeaders.constEnd();
 }
header()
QVariant QNetworkRequest::header (KnownHeaders header) const
Returns the value of the known network header header if it is present in this request.
If it is not present, returns QVariant() (i.e., an invalid variant).
See also
KnownHeaders, rawHeader(), setHeader()
Definition at line 423 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessManager::createRequest(), QNetworkAccessManagerPrivate::prepareMultipart(), QDeclarativeXMLHttpRequest::requestFromUrl(), and QNetworkReplyImplPrivate::setup().
 {
     return d->cookedHeaders.value(header);
 }
operator!=()
bool QNetworkRequest::operator!= (const QNetworkRequest & other) const inline
Returns false if this object is not the same as other.
See also
operator==()
Definition at line 116 of file qnetworkrequest.h.
     { return !operator==(other); }
operator=()
QNetworkRequest & QNetworkRequest::operator= (const QNetworkRequest & other)
Creates a copy of other.
Definition at line 390 of file qnetworkrequest.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QNetworkRequest::operator== (const QNetworkRequest & other) const
Returns true if this object is the same as other (i.e., if they have the same URL, same headers and same meta-data settings).
See also
operator!=()
Definition at line 371 of file qnetworkrequest.cpp.
 {
     return d == other.d || *d == *other.d;
 }
originatingObject()
QObject * QNetworkRequest::originatingObject () const
Returns a reference to the object that initiated this network request; returns 0 if not set or the object has been destroyed.
Since
4.6
See also
setOriginatingObject()
Definition at line 601 of file qnetworkrequest.cpp.
 {
     return d->originatingObject.data();
 }
priority()
QNetworkRequest::Priority QNetworkRequest::priority () const
Return the priority of this request.
Since
4.7
See also
setPriority()
Definition at line 616 of file qnetworkrequest.cpp.
Referenced by setPriority().
 {
     return d->priority;
 }
rawHeader()
QByteArray QNetworkRequest::rawHeader (const QByteArray & headerName) const
Returns the raw form of header headerName.
If no such header is present, an empty QByteArray is returned, which may be indistinguishable from a header that is present but has no content (use hasRawHeader() to find out if the header exists or not).
Raw headers can be set with setRawHeader() or with setHeader().
See also
header(), setRawHeader()
Definition at line 461 of file qnetworkrequest.cpp.
Referenced by QDeclarativeXMLHttpRequest::addHeader(), QNetworkAccessHttpBackend::canResume(), and QNetworkAccessHttpBackend::postRequest().
 {
     QNetworkHeadersPrivate::RawHeadersList::ConstIterator it =
         d->findRawHeader(headerName);
     if (it != d->rawHeaders.constEnd())
         return it->second;
     return QByteArray();
 }
rawHeaderList()
QList< QByteArray > QNetworkRequest::rawHeaderList () const
Returns a list of all raw headers that are set in this network request.
The list is in the order that the headers were set.
See also
hasRawHeader(), rawHeader()
Definition at line 476 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest().
 {
     return d->rawHeadersKeys();
 }
setAttribute()
void QNetworkRequest::setAttribute (Attribute code, const QVariant & value)
Sets the attribute associated with code code to be value value.
If the attribute is already set, the previous value is discarded. In special, if value is an invalid QVariant, the attribute is unset.
See also
attribute(), QNetworkRequest::Attribute
Definition at line 527 of file qnetworkrequest.cpp.
Referenced by QDeclarativeFontObject::download(), QDeclarativeAnimatedImage::load(), QDeclarativePixmapReader::networkRequestDone(), QDeclarativePixmapReader::processJob(), and QNetworkAccessManager::sendCustomRequest().
 {
     if (value.isValid())
         d->attributes.insert(code, value);
     else
         d->attributes.remove(code);
 }
setHeader()
void QNetworkRequest::setHeader (KnownHeaders header, const QVariant & value)
Sets the value of the known header header to be value, overriding any previously set headers.
This operation also sets the equivalent raw HTTP header.
See also
KnownHeaders, setRawHeader(), header()
Definition at line 435 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessManager::createRequest(), QNetworkAccessManagerPrivate::prepareMultipart(), and QDeclarativeXMLHttpRequest::requestFromUrl().
 {
     d->setCookedHeader(header, value);
 }
setOriginatingObject()
void QNetworkRequest::setOriginatingObject (QObject * object)
Allows setting a reference to the object initiating the request.
Since
4.6
For example QtWebKit sets the originating object to the QWebFrame that initiated the request.
See also
originatingObject()
Definition at line 584 of file qnetworkrequest.cpp.
 {
     d->originatingObject = object;
 }
setPriority()
void QNetworkRequest::setPriority (Priority priority)
Set the priority of this request to priority.
Since
4.7
Note
The priority is only a hint to the network access manager. It can use it or not. Currently it is used for HTTP to decide which request should be sent first to a server.
See also
priority()
Definition at line 649 of file qnetworkrequest.cpp.
 {
     d->priority = priority;
 }
setRawHeader()
void QNetworkRequest::setRawHeader (const QByteArray & headerName, const QByteArray & headerValue)
Sets the header headerName to be of value headerValue.
If headerName corresponds to a known header (see QNetworkRequest::KnownHeaders), the raw format will be parsed and the corresponding "cooked" header will be set as well.
For example:
request.setRawHeader("Last-Modified", "Sun, 06 Nov 1994 08:49:37 GMT");
will also set the known header LastModifiedHeader to be the QDateTime object of the parsed date.
Note: setting the same header twice overrides the previous setting. To accomplish the behaviour of multiple HTTP headers of the same name, you should concatenate the two values, separating them with a comma (",") and set one single raw header.
See also
KnownHeaders, setHeader(), hasRawHeader(), rawHeader()
Definition at line 500 of file qnetworkrequest.cpp.
Referenced by QDeclarativeXMLHttpRequest::addHeader(), QNetworkAccessManagerPrivate::prepareMultipart(), and QDeclarativeXmlListModel::reload().
 {
     d->setRawHeader(headerName, headerValue);
 }
setSslConfiguration()
void QNetworkRequest::setSslConfiguration (const QSslConfiguration & config)
Sets this network request's SSL configuration to be config.
The settings that apply are the private key, the local certificate, the SSL protocol (SSLv2, SSLv3, TLSv1 where applicable), the CA certificates and the ciphers that the SSL backend is allowed to use.
By default, no SSL configuration is set, which allows the backends to choose freely what configuration is best for them.
See also
sslConfiguration(), QSslConfiguration::defaultConfiguration()
Definition at line 561 of file qnetworkrequest.cpp.
 {
     if (!d->sslConfiguration)
         d->sslConfiguration = new QSslConfiguration(config);
     else
         *d->sslConfiguration = config;
 }
setUrl()
void QNetworkRequest::setUrl (const QUrl & url)
Sets the URL this network request is referring to to be url.
See also
url()
Definition at line 411 of file qnetworkrequest.cpp.
Referenced by QDeclarativeInclude::finished(), QDeclarativeInclude::QDeclarativeInclude(), and QDeclarativeXMLHttpRequest::requestFromUrl().
 {
     d->url = url;
 }
sslConfiguration()
QSslConfiguration QNetworkRequest::sslConfiguration () const
Returns this network request's SSL configuration.
By default, no SSL settings are specified.
See also
setSslConfiguration()
Definition at line 542 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessManager::createRequest(), QNetworkAccessHttpBackend::fetchSslConfiguration(), and QNetworkAccessHttpBackend::postRequest().
 {
     if (!d->sslConfiguration)
         d->sslConfiguration = new QSslConfiguration(QSslConfiguration::defaultConfiguration());
     return *d->sslConfiguration;
 }
url()
QUrl QNetworkRequest::url () const
Returns the URL this network request is referring to.
See also
setUrl()
Definition at line 401 of file qnetworkrequest.cpp.
Referenced by QNetworkReplyImplPrivate::_q_networkSessionConnected(), QNetworkAccessFileBackendFactory::create(), QNetworkAccessFtpBackendFactory::create(), QNetworkAccessHttpBackendFactory::create(), QPatternist::URILoader::createRequest(), QNetworkAccessManager::createRequest(), QNetworkAccessHttpBackend::postRequest(), QDisabledNetworkReply::QDisabledNetworkReply(), QNetworkReplyDataImpl::QNetworkReplyDataImpl(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QNetworkRequest(), QNetworkReplyImplPrivate::setup(), and setUrl().
 {
     return d->url;
 }
Friends and Related Functions
QNetworkRequestPrivate
friend class QNetworkRequestPrivate friend
Definition at line 149 of file qnetworkrequest.h.
Properties
d
QSharedDataPointer<QNetworkRequestPrivate> QNetworkRequest::d private
Definition at line 148 of file qnetworkrequest.h.
Referenced by attribute(), hasRawHeader(), header(), operator=(), operator==(), originatingObject(), priority(), QNetworkRequest(), rawHeader(), rawHeaderList(), setAttribute(), setHeader(), setOriginatingObject(), setPriority(), setRawHeader(), setSslConfiguration(), setUrl(), sslConfiguration(), url(), and ~QNetworkRequest().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkrequest.h
/src/network/access/qnetworkrequest.cpp