Qt 4.8: QPatternist::SchemaTypeFactory Class Reference
QPatternist::SchemaTypeFactory Class Reference abstract
A factory creating schema types.
#include <qschematypefactory_p.h>
Public Types
typedef QExplicitlySharedDataPointer< SchemaTypeFactory > Ptr
Public Functions
virtual SchemaType::Ptr createSchemaType (const QXmlName name) const =0
SchemaTypeFactory ()
virtual SchemaType::Hash types () const =0
virtual ~SchemaTypeFactory ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
A factory creating schema types.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 73 of file qschematypefactory_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<SchemaTypeFactory> QPatternist::SchemaTypeFactory::Ptr
Definition at line 76 of file qschematypefactory_p.h.
Constructors and Destructors
SchemaTypeFactory()
SchemaTypeFactory::SchemaTypeFactory ()
Definition at line 48 of file qschematypefactory.cpp.
 {
 }
~SchemaTypeFactory()
SchemaTypeFactory::~SchemaTypeFactory () virtual
Definition at line 52 of file qschematypefactory.cpp.
 {
 }
Functions
createSchemaType()
virtual SchemaType::Ptr QPatternist::SchemaTypeFactory::createSchemaType (const QXmlName name) const pure virtual
Returns
a schema type for name name. If no schema type exists for name, null is returned
Implemented in QPatternist::BasicTypesFactory, and QPatternist::XsdSchemaTypesFactory.
Referenced by QPatternist::XsdSchemaTypesFactory::createSchemaType(), QPatternist::XsdSchemaResolver::resolveAlternativeTypes(), QPatternist::XsdSchemaResolver::resolveAttributeTypes(), QPatternist::XsdSchemaResolver::resolveComplexBaseTypes(), QPatternist::XsdSchemaResolver::resolveElementTypes(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::ConstructorFunctionsFactory::retrieveExpression(), QPatternist::XsdValidatingInstanceReader::typeByName(), and QPatternist::XsdValidatingInstanceReader::XsdValidatingInstanceReader().
types()
virtual SchemaType::Hash QPatternist::SchemaTypeFactory::types () const pure virtual
Returns
a dictionary containing the types this factory serves. The key is the type's QName in Clark name syntax.
Implemented in QPatternist::BasicTypesFactory, and QPatternist::XsdSchemaTypesFactory.
Referenced by QPatternist::ConstructorFunctionsFactory::ConstructorFunctionsFactory(), QPatternist::TypeAvailableFN::evaluateSingleton(), and QPatternist::XsdSchemaResolver::XsdSchemaResolver().
The documentation for this class was generated from the following files:
/src/xmlpatterns/type/qschematypefactory_p.h
/src/xmlpatterns/type/qschematypefactory.cpp