Qt 4.8: QPatternist::AtomicValue Class Reference
QPatternist::AtomicValue Class Reference abstract
Base class for all classes representing atomic values.
#include <qitem_p.h>
Public Types
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual QString stringValue () const =0
virtual ItemType::Ptr type () const =0
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Base class for all classes representing atomic values.
Instantiating AtomicValues sub classes from a value of somekind, for a certain type is done in three different ways:
The static factory fromLexical which available in most classes. This function attempts to create a value from a QString that is considered a lexical representation of the value. Thus, this function performs validation, takes care of whitespace facets, and everything else related to instantiating a value from a lexical representation.
The static factory function fromValue. This function exists for values where a C++ type exists which corresponds to the type's value space.
By using instances available in CommonValues. This is the preferred method since it uses existing singleton instances and thus saves memory. CommonValues should be used whenever possible, it can be thought as a collection of constant values.
For types that does not distinguish the value space and lexical space, such as xs:string, only the fromValue() function exist, and fromLexical() is omitted.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 118 of file qitem_p.h.
Typedefs
List
typedef QList<AtomicValue::Ptr> QPatternist::AtomicValue::List
A list if smart pointers wrapping AtomicValue instances.
Definition at line 132 of file qitem_p.h.
Ptr
typedef QExplicitlySharedDataPointer<AtomicValue> QPatternist::AtomicValue::Ptr
A smart pointer wrapping AtomicValue instances.
Definition at line 127 of file qitem_p.h.
Constructors and Destructors
~AtomicValue()
AtomicValue::~AtomicValue () virtual
Definition at line 73 of file qatomicvalue.cpp.
 {
 }
AtomicValue()
QPatternist::AtomicValue::AtomicValue () inline protected
Definition at line 166 of file qitem_p.h.
         {
         }
Functions
evaluateEBV()
bool AtomicValue::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > & context) const virtual
Always fails by issuing the type error ReportContext::FORG0006. Sub-classes whose represented type do allow EBV to be extracted from, must thus re-implement this function.
Reimplemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::DerivedString< DerivedType >, QPatternist::DerivedString< TypeLanguage >, QPatternist::DerivedString< TypeID >, QPatternist::DerivedString< TypeToken >, QPatternist::Boolean, QPatternist::AtomicString, QPatternist::Decimal, QPatternist::AbstractFloat< isDouble >, and QPatternist::Integer.
Definition at line 77 of file qatomicvalue.cpp.
Referenced by QPatternist::BooleanToDecimalCaster::castFrom(), and QPatternist::BooleanToIntegerCaster::castFrom().
 {
     context->error(QtXmlPatterns::tr("A value of type %1 cannot have an "
                                      "Effective Boolean Value.")
                       .arg(formatType(context->namePool(), type())),
                       ReportContext::FORG0006,
                       QSourceLocation());
     return false; /* Silence GCC warning. */
 }
hasError()
bool AtomicValue::hasError () const virtual
Determines whether this atomic value has an error. This is used for implementing casting.
Returns
always false
Reimplemented in QPatternist::SortTuple, and QPatternist::ValidationError.
Definition at line 87 of file qatomicvalue.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdSchemaHelper::constructAndCompare(), QPatternist::NumberFN::evaluateSingleton(), QPatternist::XsdTypeChecker::isValidString(), isValidUri(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QPatternist::XsdSchemaParser::readXPathExpression(), QPatternist::XsdValidatingInstanceReader::validateElement(), and QPatternist::XsdSchemaParser::validateIdAttribute().
 {
     return false;
 }
qtToXDMType()
ItemType::Ptr AtomicValue::qtToXDMType (const QXmlItem & item) static
Definition at line 192 of file qatomicvalue.cpp.
Referenced by QPatternist::VariableLoader::announceExternalVariable(), QXmlQueryPrivate::staticContext(), and toQt().
 {
     Q_ASSERT(!item.isNull());
     if(item.isNull())
         return ItemType::Ptr();
     if(item.isNode())
         return BuiltinTypes::node;
     Q_ASSERT(item.isAtomicValue());
     const QVariant v(item.toAtomicValue());
     switch(int(v.type()))
     {
         case QVariant::Char:
         /* Fallthrough. */
         case QVariant::String:
         /* Fallthrough. */
         case QVariant::Url:
             return BuiltinTypes::xsString;
         case QVariant::Bool:
             return BuiltinTypes::xsBoolean;
         case QVariant::ByteArray:
             return BuiltinTypes::xsBase64Binary;
         case QVariant::Int:
         /* Fallthrough. */
         case QVariant::LongLong:
             return BuiltinTypes::xsInteger;
         case QVariant::ULongLong:
             return BuiltinTypes::xsUnsignedLong;
         case QVariant::Date:
             return BuiltinTypes::xsDate;
         case QVariant::DateTime:
         /* Fallthrough. */
         case QVariant::Time:
             return BuiltinTypes::xsDateTime;
         case QMetaType::Float:
         return BuiltinTypes::xsFloat;
         case QVariant::Double:
             return BuiltinTypes::xsDouble;
         default:
             return ItemType::Ptr();
     }
 }
stringValue()
virtual QString QPatternist::AtomicValue::stringValue () const pure virtual
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::DerivedString< DerivedType >, QPatternist::DerivedString< TypeLanguage >, QPatternist::DerivedString< TypeID >, QPatternist::DerivedString< TypeToken >, QPatternist::AbstractFloat< isDouble >, QPatternist::AtomicString, QPatternist::SortTuple, QPatternist::ValidationError, QPatternist::Decimal, QPatternist::DayTimeDuration, QPatternist::Integer, QPatternist::QNameValue, QPatternist::Duration, QPatternist::Boolean, QPatternist::DateTime, QPatternist::Base64Binary, QPatternist::SchemaTime, QPatternist::YearMonthDuration, QPatternist::GMonthDay, QPatternist::Date, QPatternist::GDay, QPatternist::GMonth, QPatternist::GYear, QPatternist::GYearMonth, and QPatternist::HexBinary.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::ComparisonFactory::constructAndCompare(), QPatternist::XsdSchemaHelper::constructAndCompare(), QPatternist::XsdTypeChecker::normalizedValue(), QPatternist::Boolean::stringValue(), and toQt().
toQt() [1/2]
QVariant AtomicValue::toQt (const AtomicValue *const value) static
Converts value to a QVariant.
Definition at line 92 of file qatomicvalue.cpp.
Referenced by QAbstractXmlReceiver::item(), QXmlItem::toAtomicValue(), and toQt().
 {
     Q_ASSERT_X(value, Q_FUNC_INFO,
                "Internal error, a null pointer cannot be passed.");
     const ItemType::Ptr t(value->type());
     if(BuiltinTypes::xsString->xdtTypeMatches(t)
        || BuiltinTypes::xsUntypedAtomic->xdtTypeMatches(t)
        || BuiltinTypes::xsAnyURI->xdtTypeMatches(t))
         return value->stringValue();
     /* Note, this occurs before the xsInteger test, since xs:unsignedLong
      * is a subtype of it. */
     else if(*BuiltinTypes::xsUnsignedLong == *t)
         return QVariant(value->as<DerivedInteger<TypeUnsignedLong> >()->storedValue());
     else if(BuiltinTypes::xsInteger->xdtTypeMatches(t))
         return QVariant(value->as<Numeric>()->toInteger());
     else if(BuiltinTypes::xsFloat->xdtTypeMatches(t)
             || BuiltinTypes::xsDouble->xdtTypeMatches(t)
             || BuiltinTypes::xsDecimal->xdtTypeMatches(t))
         return QVariant(value->as<Numeric>()->toDouble());
     /* We currently does not support xs:time. */
     else if(BuiltinTypes::xsDateTime->xdtTypeMatches(t))
         return QVariant(value->as<AbstractDateTime>()->toDateTime());
     else if(BuiltinTypes::xsDate->xdtTypeMatches(t))
         return QVariant(value->as<AbstractDateTime>()->toDateTime().toUTC().date());
     else if(BuiltinTypes::xsBoolean->xdtTypeMatches(t))
         return QVariant(value->as<Boolean>()->value());
     else if(BuiltinTypes::xsBase64Binary->xdtTypeMatches(t)
             || BuiltinTypes::xsHexBinary->xdtTypeMatches(t))
         return QVariant(value->as<Base64Binary>()->asByteArray());
     else if(BuiltinTypes::xsQName->xdtTypeMatches(t))
         return QVariant::fromValue(value->as<QNameValue>()->qName());
     else
     {
         /* A type we don't support in Qt. Includes xs:time currently. */
         return QVariant();
     }
 }
toQt() [2/2]
static QVariant QPatternist::AtomicValue::toQt (const AtomicValue::Ptr & value) inline static
Definition at line 157 of file qitem_p.h.
         {
             return toQt(value.data());
         }
toXDM()
Item AtomicValue::toXDM (const QVariant & value) static
Definition at line 132 of file qatomicvalue.cpp.
Referenced by QPatternist::VariantListIterator::inputToOutputItem(), QPatternist::VariableLoader::itemForName(), QXmlItem::QXmlItem(), and toQt().
 {
     Q_ASSERT_X(value.isValid(), Q_FUNC_INFO,
                "QVariants sent to Patternist must be valid.");
     switch(value.userType())
     {
         case QVariant::Char:
         /* Fallthrough. A single codepoint is a string in XQuery. */
         case QVariant::String:
             return AtomicString::fromValue(value.toString());
         case QVariant::Url:
         {
             /* QUrl doesn't follow the spec properly, so we
              * have to let it be an xs:string. Calling QVariant::toString()
              * on a QVariant that contains a QUrl returns, surprisingly,
              * an empty string. */
             return AtomicString::fromValue(value.toUrl().toString());
         }
         case QVariant::ByteArray:
             return HexBinary::fromValue(value.toByteArray());
         case QVariant::Int:
         /* Fallthrough. */
         case QVariant::LongLong:
         /* Fallthrough. */
         case QVariant::UInt:
             return Integer::fromValue(value.toLongLong());
         case QVariant::ULongLong:
             return DerivedInteger<TypeUnsignedLong>::fromValueUnchecked(value.toULongLong());
         case QVariant::Bool:
             return Boolean::fromValue(value.toBool());
         case QVariant::Time:
             return SchemaTime::fromDateTime(value.toDateTime());
         case QVariant::Date:
             return Date::fromDateTime(QDateTime(value.toDate(), QTime(), Qt::UTC));
         case QVariant::DateTime:
             return DateTime::fromDateTime(value.toDateTime());
         case QMetaType::Float:
             return Item(Double::fromValue(value.toFloat()));
         case QVariant::Double:
             return Item(Double::fromValue(value.toDouble()));
         default:
         {
             if (value.userType() == qMetaTypeId<float>())
             {
                 return Item(Float::fromValue(value.value<float>()));
             }
             else {
                 Q_ASSERT_X(false,
                            Q_FUNC_INFO,
                            qPrintable(QString::fromLatin1(
                                "QVariants of type %1 are not supported in "
                                "Patternist, see the documentation")
                                   .arg(QLatin1String(value.typeName()))));
                 return AtomicValue::Ptr();
             }
         }
     }
 }
type()
virtual ItemType::Ptr QPatternist::AtomicValue::type () const pure virtual
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::DerivedString< DerivedType >, QPatternist::DerivedString< TypeLanguage >, QPatternist::DerivedString< TypeID >, QPatternist::DerivedString< TypeToken >, QPatternist::AnyURI, QPatternist::AbstractFloat< isDouble >, QPatternist::SortTuple, QPatternist::AtomicString, QPatternist::Boolean, QPatternist::Decimal, QPatternist::Integer, QPatternist::ValidationError, QPatternist::DayTimeDuration, QPatternist::QNameValue, QPatternist::Duration, QPatternist::DateTime, QPatternist::Base64Binary, QPatternist::UntypedAtomic, QPatternist::SchemaTime, QPatternist::YearMonthDuration, QPatternist::HexBinary, QPatternist::Date, QPatternist::GDay, QPatternist::GMonth, QPatternist::GMonthDay, QPatternist::GYear, and QPatternist::GYearMonth.
Referenced by evaluateEBV(), and toQt().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qitem_p.h
/src/xmlpatterns/data/qatomicvalue.cpp