Qt 4.8: QShortcut Class Reference
QShortcut Class Reference
The QShortcut class is used to create keyboard shortcuts.
#include <qshortcut.h>
Signals
void activated ()
This signal is emitted when the user types the shortcut's key sequence.
void activatedAmbiguously ()
When a key sequence is being typed at the keyboard, it is said to be ambiguous as long as it matches the start of more than one shortcut.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool autoRepeat () const
Qt::ShortcutContext context ()
int id () const
Returns the shortcut's ID.
bool isEnabled () const
QKeySequence key () const
QWidget * parentWidget () const
Returns the shortcut's parent widget.
QShortcut (QWidget *parent)
Constructs a QShortcut object for the parent widget.
QShortcut (const QKeySequence &key, QWidget *parent, const char *member=0, const char *ambiguousMember=0, Qt::ShortcutContext context=Qt::WindowShortcut)
Constructs a QShortcut object for the parent widget.
void setAutoRepeat (bool on)
void setContext (Qt::ShortcutContext context)
void setEnabled (bool enable)
void setKey (const QKeySequence &key)
void setWhatsThis (const QString &text)
QString whatsThis () const
~QShortcut ()
Destroys the shortcut.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *e)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool autoRepeat
whether the shortcut can auto repeat
Qt::ShortcutContext context
the context in which the shortcut is valid
bool enabled
whether the shortcut is enabled
QKeySequence key
the shortcut's key sequence
QString whatsThis
the shortcut's "What's This?" help text
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QShortcut class is used to create keyboard shortcuts.
The QShortcut class provides a way of connecting keyboard shortcuts to Qt's signals and slots mechanism, so that objects can be informed when a shortcut is executed. The shortcut can be set up to contain all the key presses necessary to describe a keyboard shortcut, including the states of modifier keys such as Shift, Ctrl, and Alt.
On certain widgets, using '&' in front of a character will automatically create a mnemonic (a shortcut) for that character, e.g. "E&xit" will create the shortcut Alt+X (use '&&' to display an actual ampersand). The widget might consume and perform an action on a given shortcut. On X11 the ampersand will not be shown and the character will be underlined. On Windows, shortcuts are normally not displayed until the user presses the Alt key, but this is a setting the user can change. On Mac, shortcuts are disabled by default. Call qt_set_sequence_auto_mnemonic() to enable them. However, because mnemonic shortcuts do not fit in with Aqua's guidelines, Qt will not show the shortcut character underlined.
For applications that use menus, it may be more convenient to use the convenience functions provided in the QMenu class to assign keyboard shortcuts to menu items as they are created. Alternatively, shortcuts may be associated with other types of actions in the QAction class.
The simplest way to create a shortcut for a particular widget is to construct the shortcut with a key sequence. For example:
shortcut = new QShortcut(QKeySequence(tr("Ctrl+O", "File|Open")),
                         parent);
When the user types the key sequence for a given shortcut, the shortcut's activated() signal is emitted. (In the case of ambiguity, the activatedAmbiguously() signal is emitted.) A shortcut is "listened for" by Qt's event loop when the shortcut's parent widget is receiving events.
A shortcut's key sequence can be set with setKey() and retrieved with key(). A shortcut can be enabled or disabled with setEnabled(), and can have "What's This?" help text set with setWhatsThis().
See also
QShortcutEvent, QKeySequence, QAction
Definition at line 57 of file qshortcut.h.
Constructors and Destructors
QShortcut() [1/2]
QShortcut::QShortcut (QWidget * parent) explicit
Constructs a QShortcut object for the parent widget.
Since no shortcut key sequence is specified, the shortcut will not emit any signals.
See also
setKey()
Definition at line 198 of file qshortcut.cpp.
     : QObject(*new QShortcutPrivate, parent)
 {
     Q_ASSERT(parent != 0);
 }
QShortcut() [2/2]
QShortcut::QShortcut (const QKeySequence & key, QWidget * parent, const char * member = 0, const char * ambiguousMember = 0, Qt::ShortcutContext context = Qt::WindowShortcut)
Constructs a QShortcut object for the parent widget.
The shortcut operates on its parent, listening for QShortcutEvent that match the key sequence. Depending on the ambiguity of the event, the shortcut will call the member function, or the ambiguousMember function, if the key press was in the shortcut's context.
Definition at line 212 of file qshortcut.cpp.
     : QObject(*new QShortcutPrivate, parent)
 {
     QAPP_CHECK("QShortcut");
     Q_D(QShortcut);
     Q_ASSERT(parent != 0);
     d->sc_context = context;
     d->sc_sequence = key;
     d->redoGrab(qApp->d_func()->shortcutMap);
     if (member)
         connect(this, SIGNAL(activated()), parent, member);
     if (ambiguousMember)
         connect(this, SIGNAL(activatedAmbiguously()), parent, ambiguousMember);
 }
~QShortcut()
QShortcut::~QShortcut ()
Destroys the shortcut.
Definition at line 233 of file qshortcut.cpp.
 {
     Q_D(QShortcut);
     if (qApp)
         qApp->d_func()->shortcutMap.removeShortcut(d->sc_id, this);
 }
Functions
activated
void QShortcut::activated () signal
This signal is emitted when the user types the shortcut's key sequence.
See also
activatedAmbiguously()
Referenced by event(), and QShortcut().
activatedAmbiguously
void QShortcut::activatedAmbiguously () signal
When a key sequence is being typed at the keyboard, it is said to be ambiguous as long as it matches the start of more than one shortcut.
When a shortcut's key sequence is completed, activatedAmbiguously() is emitted if the key sequence is still ambiguous (i.e., it is the start of one or more other shortcuts). The activated() signal is not emitted in this case.
See also
activated()
Referenced by event(), and QShortcut().
autoRepeat()
bool QShortcut::autoRepeat () const
Referenced by setAutoRepeat().
context()
Qt::ShortcutContext QShortcut::context ()
Referenced by QShortcut(), and setContext().
event()
bool QShortcut::event (QEvent * e) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Definition at line 407 of file qshortcut.cpp.
 {
     Q_D(QShortcut);
     bool handled = false;
     if (d->sc_enabled && e->type() == QEvent::Shortcut) {
         QShortcutEvent *se = static_cast<QShortcutEvent *>(e);
         if (se->shortcutId() == d->sc_id && se->key() == d->sc_sequence){
 #ifndef QT_NO_WHATSTHIS
             if (QWhatsThis::inWhatsThisMode()) {
                 QWhatsThis::showText(QCursor::pos(), d->sc_whatsthis);
                 handled = true;
             } else
 #endif
             if (se->isAmbiguous())
                 emit activatedAmbiguously();
             else
                 emit activated();
             handled = true;
         }
     }
     return handled;
 }
id()
int QShortcut::id () const
Returns the shortcut's ID.
See also
QShortcutEvent::shortcutId()
Definition at line 398 of file qshortcut.cpp.
 {
     Q_D(const QShortcut);
     return d->sc_id;
 }
isEnabled()
bool QShortcut::isEnabled () const
Definition at line 298 of file qshortcut.cpp.
 {
     Q_D(const QShortcut);
     return d->sc_enabled;
 }
key()
QKeySequence QShortcut::key () const
Referenced by QShortcut(), and setKey().
parentWidget()
QWidget * QShortcut::parentWidget () const inline
Returns the shortcut's parent widget.
Definition at line 90 of file qshortcut.h.
Referenced by QShortcutMap::correctContext().
     { return static_cast<QWidget *>(QObject::parent()); }
setAutoRepeat()
void QShortcut::setAutoRepeat (bool on)
Definition at line 377 of file qshortcut.cpp.
 {
     Q_D(QShortcut);
     if (d->sc_autorepeat == on)
         return;
     QAPP_CHECK("setAutoRepeat");
     d->sc_autorepeat = on;
     qApp->d_func()->shortcutMap.setShortcutAutoRepeat(on, d->sc_id, this);
 }
setContext()
void QShortcut::setContext (Qt::ShortcutContext context)
Definition at line 319 of file qshortcut.cpp.
 {
     Q_D(QShortcut);
     if(d->sc_context == context)
         return;
     QAPP_CHECK("setContext");
     d->sc_context = context;
     d->redoGrab(qApp->d_func()->shortcutMap);
 }
setEnabled()
void QShortcut::setEnabled (bool enable)
Definition at line 288 of file qshortcut.cpp.
 {
     Q_D(QShortcut);
     if (d->sc_enabled == enable)
         return;
     QAPP_CHECK("setEnabled");
     d->sc_enabled = enable;
     qApp->d_func()->shortcutMap.setShortcutEnabled(enable, d->sc_id, this);
 }
setKey()
void QShortcut::setKey (const QKeySequence & key)
Definition at line 254 of file qshortcut.cpp.
Referenced by QFileDialogPrivate::createWidgets().
 {
     Q_D(QShortcut);
     if (d->sc_sequence == key)
         return;
     QAPP_CHECK("setKey");
     d->sc_sequence = key;
     d->redoGrab(qApp->d_func()->shortcutMap);
 }
setWhatsThis()
void QShortcut::setWhatsThis (const QString & text)
Definition at line 352 of file qshortcut.cpp.
 {
     Q_D(QShortcut);
     d->sc_whatsthis = text;
 }
whatsThis()
QString QShortcut::whatsThis () const
Referenced by setWhatsThis().
Properties
autoRepeat
bool QShortcut::autoRepeat private
whether the shortcut can auto repeat
Since
4.2
If true, the shortcut will auto repeat when the keyboard shortcut combination is held down, provided that keyboard auto repeat is enabled on the system. The default value is true.
Definition at line 64 of file qshortcut.h.
context
Qt::ShortcutContext QShortcut::context private
the context in which the shortcut is valid
A shortcut's context decides in which circumstances a shortcut is allowed to be triggered. The normal context is Qt::WindowShortcut, which allows the shortcut to trigger if the parent (the widget containing the shortcut) is a subwidget of the active top-level window.
By default, this property is set to Qt::WindowShortcut.
Definition at line 65 of file qshortcut.h.
enabled
QShortcut::enabled private
whether the shortcut is enabled
An enabled shortcut emits the activated() or activatedAmbiguously() signal when a QShortcutEvent occurs that matches the shortcut's key() sequence.
If the application is in WhatsThis mode the shortcut will not emit the signals, but will show the "What's This?" text instead.
By default, this property is true.
See also
whatsThis
Definition at line 63 of file qshortcut.h.
key
QKeySequence QShortcut::key private
the shortcut's key sequence
This is a key sequence with an optional combination of Shift, Ctrl, and Alt. The key sequence may be supplied in a number of ways:
setKey(0);                  // no signal emitted
setKey(QKeySequence());     // no signal emitted
setKey(0x3b1);              // Greek letter alpha
setKey(Qt::Key_D);              // 'd', e.g. to delete
setKey('q');                // 'q', e.g. to quit
setKey(Qt::CTRL + Qt::Key_P);       // Ctrl+P, e.g. to print document
setKey("Ctrl+P");           // Ctrl+P, e.g. to print document
By default, this property contains an empty key sequence.
Definition at line 61 of file qshortcut.h.
whatsThis
QString QShortcut::whatsThis private
the shortcut's "What's This?" help text
The text will be shown when the application is in "What's This?" mode and the user types the shortcut key() sequence.
To set "What's This?" help on a menu item (with or without a shortcut key), set the help on the item's action.
By default, this property contains an empty string.
See also
QWhatsThis::inWhatsThisMode(), QAction::setWhatsThis()
Definition at line 62 of file qshortcut.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qshortcut.h
/src/gui/kernel/qshortcut.cpp