Qt 4.8: QDeclarativeJS::AST::Node Class Reference
QDeclarativeJS::AST::Node Class Reference abstract
#include <qdeclarativejsast_p.h>
Public Types
enum Kind {
Kind_Undefined, Kind_ArgumentList, Kind_ArrayLiteral, Kind_ArrayMemberExpression,
Kind_BinaryExpression, Kind_Block, Kind_BreakStatement, Kind_CallExpression,
Kind_CaseBlock, Kind_CaseClause, Kind_CaseClauses, Kind_Catch,
Kind_ConditionalExpression, Kind_ContinueStatement, Kind_DebuggerStatement, Kind_DefaultClause,
Kind_DeleteExpression, Kind_DoWhileStatement, Kind_ElementList, Kind_Elision,
Kind_EmptyStatement, Kind_Expression, Kind_ExpressionStatement, Kind_FalseLiteral,
Kind_FieldMemberExpression, Kind_Finally, Kind_ForEachStatement, Kind_ForStatement,
Kind_FormalParameterList, Kind_FunctionBody, Kind_FunctionDeclaration, Kind_FunctionExpression,
Kind_FunctionSourceElement, Kind_IdentifierExpression, Kind_IdentifierPropertyName, Kind_IfStatement,
Kind_LabelledStatement, Kind_LocalForEachStatement, Kind_LocalForStatement, Kind_NewExpression,
Kind_NewMemberExpression, Kind_NotExpression, Kind_NullExpression, Kind_NumericLiteral,
Kind_NumericLiteralPropertyName, Kind_ObjectLiteral, Kind_PostDecrementExpression, Kind_PostIncrementExpression,
Kind_PreDecrementExpression, Kind_PreIncrementExpression, Kind_Program, Kind_PropertyName,
Kind_PropertyNameAndValueList, Kind_RegExpLiteral, Kind_ReturnStatement, Kind_SourceElement,
Kind_SourceElements, Kind_StatementList, Kind_StatementSourceElement, Kind_StringLiteral,
Kind_StringLiteralPropertyName, Kind_SwitchStatement, Kind_ThisExpression, Kind_ThrowStatement,
Kind_TildeExpression, Kind_TrueLiteral, Kind_TryStatement, Kind_TypeOfExpression,
Kind_UnaryMinusExpression, Kind_UnaryPlusExpression, Kind_VariableDeclaration, Kind_VariableDeclarationList,
Kind_VariableStatement, Kind_VoidExpression, Kind_WhileStatement, Kind_WithStatement,
Kind_NestedExpression, Kind_UiArrayBinding, Kind_UiImport, Kind_UiImportList,
Kind_UiObjectBinding, Kind_UiObjectDefinition, Kind_UiObjectInitializer, Kind_UiObjectMemberList,
Kind_UiArrayMemberList, Kind_UiProgram, Kind_UiParameterList, Kind_UiPublicMember,
Kind_UiQualifiedId, Kind_UiScriptBinding, Kind_UiSourceElement, Kind_UiFormal,
Kind_UiFormalList, Kind_UiSignature
}
Public Functions
void accept (Visitor *visitor)
virtual void accept0 (Visitor *visitor)=0
virtual BinaryExpression * binaryExpressionCast ()
virtual ExpressionNode * expressionCast ()
Node ()
virtual Statement * statementCast ()
virtual UiObjectMember * uiObjectMemberCast ()
virtual ~Node ()
Static Public Functions
static void accept (Node *node, Visitor *visitor)
static void acceptChild (Node *node, Visitor *visitor)
Public Variables
int kind
Detailed Description
Definition at line 122 of file qdeclarativejsast_p.h.
Enumerations
Kind
enum QDeclarativeJS::AST::Node::Kind
Enumerator
Kind_Undefined
Kind_ArgumentList
Kind_ArrayLiteral
Kind_ArrayMemberExpression
Kind_BinaryExpression
Kind_Block
Kind_BreakStatement
Kind_CallExpression
Kind_CaseBlock
Kind_CaseClause
Kind_CaseClauses
Kind_Catch
Kind_ConditionalExpression
Kind_ContinueStatement
Kind_DebuggerStatement
Kind_DefaultClause
Kind_DeleteExpression
Kind_DoWhileStatement
Kind_ElementList
Kind_Elision
Kind_EmptyStatement
Kind_Expression
Kind_ExpressionStatement
Kind_FalseLiteral
Kind_FieldMemberExpression
Kind_Finally
Kind_ForEachStatement
Kind_ForStatement
Kind_FormalParameterList
Kind_FunctionBody
Kind_FunctionDeclaration
Kind_FunctionExpression
Kind_FunctionSourceElement
Kind_IdentifierExpression
Kind_IdentifierPropertyName
Kind_IfStatement
Kind_LabelledStatement
Kind_LocalForEachStatement
Kind_LocalForStatement
Kind_NewExpression
Kind_NewMemberExpression
Kind_NotExpression
Kind_NullExpression
Kind_NumericLiteral
Kind_NumericLiteralPropertyName
Kind_ObjectLiteral
Kind_PostDecrementExpression
Kind_PostIncrementExpression
Kind_PreDecrementExpression
Kind_PreIncrementExpression
Kind_Program
Kind_PropertyName
Kind_PropertyNameAndValueList
Kind_RegExpLiteral
Kind_ReturnStatement
Kind_SourceElement
Kind_SourceElements
Kind_StatementList
Kind_StatementSourceElement
Kind_StringLiteral
Kind_StringLiteralPropertyName
Kind_SwitchStatement
Kind_ThisExpression
Kind_ThrowStatement
Kind_TildeExpression
Kind_TrueLiteral
Kind_TryStatement
Kind_TypeOfExpression
Kind_UnaryMinusExpression
Kind_UnaryPlusExpression
Kind_VariableDeclaration
Kind_VariableDeclarationList
Kind_VariableStatement
Kind_VoidExpression
Kind_WhileStatement
Kind_WithStatement
Kind_NestedExpression
Kind_UiArrayBinding
Kind_UiImport
Kind_UiImportList
Kind_UiObjectBinding
Kind_UiObjectDefinition
Kind_UiObjectInitializer
Kind_UiObjectMemberList
Kind_UiArrayMemberList
Kind_UiProgram
Kind_UiParameterList
Kind_UiPublicMember
Kind_UiQualifiedId
Kind_UiScriptBinding
Kind_UiSourceElement
Kind_UiFormal
Kind_UiFormalList
Kind_UiSignature
Definition at line 125 of file qdeclarativejsast_p.h.
               {
         Kind_Undefined,
         Kind_ArgumentList,
         Kind_ArrayLiteral,
         Kind_ArrayMemberExpression,
         Kind_BinaryExpression,
         Kind_Block,
         Kind_BreakStatement,
         Kind_CallExpression,
         Kind_CaseBlock,
         Kind_CaseClause,
         Kind_CaseClauses,
         Kind_Catch,
         Kind_ConditionalExpression,
         Kind_ContinueStatement,
         Kind_DebuggerStatement,
         Kind_DefaultClause,
         Kind_DeleteExpression,
         Kind_DoWhileStatement,
         Kind_ElementList,
         Kind_Elision,
         Kind_EmptyStatement,
         Kind_Expression,
         Kind_ExpressionStatement,
         Kind_FalseLiteral,
         Kind_FieldMemberExpression,
         Kind_Finally,
         Kind_ForEachStatement,
         Kind_ForStatement,
         Kind_FormalParameterList,
         Kind_FunctionBody,
         Kind_FunctionDeclaration,
         Kind_FunctionExpression,
         Kind_FunctionSourceElement,
         Kind_IdentifierExpression,
         Kind_IdentifierPropertyName,
         Kind_IfStatement,
         Kind_LabelledStatement,
         Kind_LocalForEachStatement,
         Kind_LocalForStatement,
         Kind_NewExpression,
         Kind_NewMemberExpression,
         Kind_NotExpression,
         Kind_NullExpression,
         Kind_NumericLiteral,
         Kind_NumericLiteralPropertyName,
         Kind_ObjectLiteral,
         Kind_PostDecrementExpression,
         Kind_PostIncrementExpression,
         Kind_PreDecrementExpression,
         Kind_PreIncrementExpression,
         Kind_Program,
         Kind_PropertyName,
         Kind_PropertyNameAndValueList,
         Kind_RegExpLiteral,
         Kind_ReturnStatement,
         Kind_SourceElement,
         Kind_SourceElements,
         Kind_StatementList,
         Kind_StatementSourceElement,
         Kind_StringLiteral,
         Kind_StringLiteralPropertyName,
         Kind_SwitchStatement,
         Kind_ThisExpression,
         Kind_ThrowStatement,
         Kind_TildeExpression,
         Kind_TrueLiteral,
         Kind_TryStatement,
         Kind_TypeOfExpression,
         Kind_UnaryMinusExpression,
         Kind_UnaryPlusExpression,
         Kind_VariableDeclaration,
         Kind_VariableDeclarationList,
         Kind_VariableStatement,
         Kind_VoidExpression,
         Kind_WhileStatement,
         Kind_WithStatement,
         Kind_NestedExpression,
         Kind_UiArrayBinding,
         Kind_UiImport,
         Kind_UiImportList,
         Kind_UiObjectBinding,
         Kind_UiObjectDefinition,
         Kind_UiObjectInitializer,
         Kind_UiObjectMemberList,
         Kind_UiArrayMemberList,
         Kind_UiProgram,
         Kind_UiParameterList,
         Kind_UiPublicMember,
         Kind_UiQualifiedId,
         Kind_UiScriptBinding,
         Kind_UiSourceElement,
         Kind_UiFormal,
         Kind_UiFormalList,
         Kind_UiSignature
     };
Constructors and Destructors
Node()
QDeclarativeJS::AST::Node::Node () inline
Definition at line 224 of file qdeclarativejsast_p.h.
         : kind(Kind_Undefined) {}
~Node()
virtual QDeclarativeJS::AST::Node::~Node () inline virtual
Definition at line 230 of file qdeclarativejsast_p.h.
 {}
Functions
accept() [1/2]
void Node::accept (Visitor * visitor)
Definition at line 50 of file qdeclarativejsast.cpp.
Referenced by accept(), QDeclarativeJS::AST::UiFormalList::accept0(), QDeclarativeJS::AST::UiSignature::accept0(), QDeclarativeJS::AST::NestedExpression::accept0(), QDeclarativeJS::AST::ArrayLiteral::accept0(), QDeclarativeJS::AST::ObjectLiteral::accept0(), QDeclarativeJS::AST::ElementList::accept0(), QDeclarativeJS::AST::PropertyNameAndValueList::accept0(), QDeclarativeJS::AST::ArrayMemberExpression::accept0(), QDeclarativeJS::AST::FieldMemberExpression::accept0(), QDeclarativeJS::AST::NewMemberExpression::accept0(), QDeclarativeJS::AST::NewExpression::accept0(), QDeclarativeJS::AST::CallExpression::accept0(), QDeclarativeJS::AST::ArgumentList::accept0(), QDeclarativeJS::AST::PostIncrementExpression::accept0(), QDeclarativeJS::AST::PostDecrementExpression::accept0(), QDeclarativeJS::AST::DeleteExpression::accept0(), QDeclarativeJS::AST::VoidExpression::accept0(), QDeclarativeJS::AST::TypeOfExpression::accept0(), QDeclarativeJS::AST::PreIncrementExpression::accept0(), QDeclarativeJS::AST::PreDecrementExpression::accept0(), QDeclarativeJS::AST::UnaryPlusExpression::accept0(), QDeclarativeJS::AST::UnaryMinusExpression::accept0(), QDeclarativeJS::AST::TildeExpression::accept0(), QDeclarativeJS::AST::NotExpression::accept0(), QDeclarativeJS::AST::BinaryExpression::accept0(), QDeclarativeJS::AST::ConditionalExpression::accept0(), QDeclarativeJS::AST::Expression::accept0(), QDeclarativeJS::AST::Block::accept0(), QDeclarativeJS::AST::StatementList::accept0(), QDeclarativeJS::AST::VariableStatement::accept0(), QDeclarativeJS::AST::VariableDeclaration::accept0(), QDeclarativeJS::AST::VariableDeclarationList::accept0(), QDeclarativeJS::AST::ExpressionStatement::accept0(), QDeclarativeJS::AST::IfStatement::accept0(), QDeclarativeJS::AST::DoWhileStatement::accept0(), QDeclarativeJS::AST::WhileStatement::accept0(), QDeclarativeJS::AST::ForStatement::accept0(), QDeclarativeJS::AST::LocalForStatement::accept0(), QDeclarativeJS::AST::ForEachStatement::accept0(), QDeclarativeJS::AST::LocalForEachStatement::accept0(), QDeclarativeJS::AST::ReturnStatement::accept0(), QDeclarativeJS::AST::WithStatement::accept0(), QDeclarativeJS::AST::CaseBlock::accept0(), QDeclarativeJS::AST::SwitchStatement::accept0(), QDeclarativeJS::AST::CaseClauses::accept0(), QDeclarativeJS::AST::CaseClause::accept0(), QDeclarativeJS::AST::DefaultClause::accept0(), QDeclarativeJS::AST::LabelledStatement::accept0(), QDeclarativeJS::AST::ThrowStatement::accept0(), QDeclarativeJS::AST::Catch::accept0(), QDeclarativeJS::AST::Finally::accept0(), QDeclarativeJS::AST::TryStatement::accept0(), QDeclarativeJS::AST::FunctionExpression::accept0(), QDeclarativeJS::AST::FunctionDeclaration::accept0(), QDeclarativeJS::AST::FunctionBody::accept0(), QDeclarativeJS::AST::Program::accept0(), QDeclarativeJS::AST::SourceElements::accept0(), QDeclarativeJS::AST::FunctionSourceElement::accept0(), QDeclarativeJS::AST::StatementSourceElement::accept0(), QDeclarativeJS::AST::UiProgram::accept0(), QDeclarativeJS::AST::UiImport::accept0(), QDeclarativeJS::AST::UiImportList::accept0(), QDeclarativeJS::AST::UiObjectMemberList::accept0(), QDeclarativeJS::AST::UiArrayMemberList::accept0(), QDeclarativeJS::AST::UiObjectInitializer::accept0(), QDeclarativeJS::AST::UiPublicMember::accept0(), QDeclarativeJS::AST::UiObjectDefinition::accept0(), QDeclarativeJS::AST::UiSourceElement::accept0(), QDeclarativeJS::AST::UiObjectBinding::accept0(), QDeclarativeJS::AST::UiScriptBinding::accept0(), and QDeclarativeJS::AST::UiArrayBinding::accept0().
 {
     if (visitor->preVisit(this)) {
         accept0(visitor);
     }
     visitor->postVisit(this);
 }
accept() [2/2]
void Node::accept (Node * node, Visitor * visitor) static
Definition at line 58 of file qdeclarativejsast.cpp.
 {
     if (node)
         node->accept(visitor);
 }
accept0()
virtual void QDeclarativeJS::AST::Node::accept0 (Visitor * visitor) pure virtual
Implemented in QDeclarativeJS::AST::UiArrayBinding, QDeclarativeJS::AST::UiScriptBinding, QDeclarativeJS::AST::UiObjectBinding, QDeclarativeJS::AST::UiSourceElement, QDeclarativeJS::AST::UiObjectDefinition, QDeclarativeJS::AST::UiPublicMember, QDeclarativeJS::AST::UiParameterList, QDeclarativeJS::AST::UiObjectInitializer, QDeclarativeJS::AST::UiArrayMemberList, QDeclarativeJS::AST::UiObjectMemberList, QDeclarativeJS::AST::UiImportList, QDeclarativeJS::AST::UiImport, QDeclarativeJS::AST::UiQualifiedId, QDeclarativeJS::AST::UiProgram, QDeclarativeJS::AST::DebuggerStatement, QDeclarativeJS::AST::StatementSourceElement, QDeclarativeJS::AST::FunctionSourceElement, QDeclarativeJS::AST::SourceElements, QDeclarativeJS::AST::Program, QDeclarativeJS::AST::FunctionBody, QDeclarativeJS::AST::FormalParameterList, QDeclarativeJS::AST::FunctionDeclaration, QDeclarativeJS::AST::FunctionExpression, QDeclarativeJS::AST::TryStatement, QDeclarativeJS::AST::Finally, QDeclarativeJS::AST::Catch, QDeclarativeJS::AST::ThrowStatement, QDeclarativeJS::AST::LabelledStatement, QDeclarativeJS::AST::DefaultClause, QDeclarativeJS::AST::CaseClause, QDeclarativeJS::AST::CaseClauses, QDeclarativeJS::AST::SwitchStatement, QDeclarativeJS::AST::CaseBlock, QDeclarativeJS::AST::WithStatement, QDeclarativeJS::AST::ReturnStatement, QDeclarativeJS::AST::BreakStatement, QDeclarativeJS::AST::ContinueStatement, QDeclarativeJS::AST::LocalForEachStatement, QDeclarativeJS::AST::ForEachStatement, QDeclarativeJS::AST::LocalForStatement, QDeclarativeJS::AST::ForStatement, QDeclarativeJS::AST::WhileStatement, QDeclarativeJS::AST::DoWhileStatement, QDeclarativeJS::AST::IfStatement, QDeclarativeJS::AST::ExpressionStatement, QDeclarativeJS::AST::EmptyStatement, QDeclarativeJS::AST::VariableDeclarationList, QDeclarativeJS::AST::VariableDeclaration, QDeclarativeJS::AST::VariableStatement, QDeclarativeJS::AST::StatementList, QDeclarativeJS::AST::Block, QDeclarativeJS::AST::Expression, QDeclarativeJS::AST::ConditionalExpression, QDeclarativeJS::AST::BinaryExpression, QDeclarativeJS::AST::NotExpression, QDeclarativeJS::AST::TildeExpression, QDeclarativeJS::AST::UnaryMinusExpression, QDeclarativeJS::AST::UnaryPlusExpression, QDeclarativeJS::AST::PreDecrementExpression, QDeclarativeJS::AST::PreIncrementExpression, QDeclarativeJS::AST::TypeOfExpression, QDeclarativeJS::AST::VoidExpression, QDeclarativeJS::AST::DeleteExpression, QDeclarativeJS::AST::PostDecrementExpression, QDeclarativeJS::AST::PostIncrementExpression, QDeclarativeJS::AST::ArgumentList, QDeclarativeJS::AST::CallExpression, QDeclarativeJS::AST::NewExpression, QDeclarativeJS::AST::NewMemberExpression, QDeclarativeJS::AST::FieldMemberExpression, QDeclarativeJS::AST::ArrayMemberExpression, QDeclarativeJS::AST::NumericLiteralPropertyName, QDeclarativeJS::AST::StringLiteralPropertyName, QDeclarativeJS::AST::IdentifierPropertyName, QDeclarativeJS::AST::PropertyNameAndValueList, QDeclarativeJS::AST::Elision, QDeclarativeJS::AST::ElementList, QDeclarativeJS::AST::ObjectLiteral, QDeclarativeJS::AST::ArrayLiteral, QDeclarativeJS::AST::RegExpLiteral, QDeclarativeJS::AST::StringLiteral, QDeclarativeJS::AST::NumericLiteral, QDeclarativeJS::AST::FalseLiteral, QDeclarativeJS::AST::TrueLiteral, QDeclarativeJS::AST::NullExpression, QDeclarativeJS::AST::IdentifierExpression, QDeclarativeJS::AST::ThisExpression, QDeclarativeJS::AST::NestedExpression, QDeclarativeJS::AST::UiSignature, QDeclarativeJS::AST::UiFormalList, and QDeclarativeJS::AST::UiFormal.
Referenced by accept().
acceptChild()
static void QDeclarativeJS::AST::Node::acceptChild (Node * node, Visitor * visitor) inline static
Definition at line 240 of file qdeclarativejsast_p.h.
     { return accept(node, visitor); } // ### remove
binaryExpressionCast()
BinaryExpression * Node::binaryExpressionCast () virtual
Reimplemented in QDeclarativeJS::AST::BinaryExpression.
Definition at line 69 of file qdeclarativejsast.cpp.
 {
     return 0;
 }
expressionCast()
ExpressionNode * Node::expressionCast () virtual
Reimplemented in QDeclarativeJS::AST::ExpressionNode.
Definition at line 64 of file qdeclarativejsast.cpp.
Referenced by QDeclarativeBindingCompilerPrivate::compile(), and QDeclarativeRewrite::RewriteBinding::operator()().
 {
     return 0;
 }
statementCast()
Statement * Node::statementCast () virtual
Reimplemented in QDeclarativeJS::AST::Statement.
Definition at line 74 of file qdeclarativejsast.cpp.
Referenced by QDeclarativeRewrite::RewriteBinding::operator()().
 {
     return 0;
 }
uiObjectMemberCast()
UiObjectMember * Node::uiObjectMemberCast () virtual
Reimplemented in QDeclarativeJS::AST::UiObjectMember.
Definition at line 79 of file qdeclarativejsast.cpp.
 {
     return 0;
 }
Properties
kind
int QDeclarativeJS::AST::Node::kind
Definition at line 246 of file qdeclarativejsast_p.h.
Referenced by astNodeToStringList(), QDeclarativeBindingCompilerPrivate::buildName(), QDeclarativeBindingCompilerPrivate::parseConditional(), QDeclarativeBindingCompilerPrivate::parseConstant(), QDeclarativeBindingCompilerPrivate::parseExpression(), QDeclarativeBindingCompilerPrivate::tryArith(), QDeclarativeBindingCompilerPrivate::tryConditional(), QDeclarativeBindingCompilerPrivate::tryConstant(), QDeclarativeBindingCompilerPrivate::tryLogic(), QDeclarativeBindingCompilerPrivate::tryMethod(), and QDeclarativeBindingCompilerPrivate::tryName().
The documentation for this class was generated from the following files:
/src/declarative/qml/parser/qdeclarativejsast_p.h
/src/declarative/qml/parser/qdeclarativejsast.cpp