Qt 4.8: QAuthenticator Class Reference
QAuthenticator Class Reference
The QAuthenticator class provides an authentication object.
#include <qauthenticator.h>
Public Functions
void detach ()
bool isNull () const
Returns true if the authenticator is null.
bool operator!= (const QAuthenticator &other) const
Returns true if this authenticator is different from other; otherwise returns false.
QAuthenticator & operator= (const QAuthenticator &other)
Assigns the contents of other to this authenticator.
bool operator== (const QAuthenticator &other) const
Returns true if this authenticator is identical to other; otherwise returns false.
QVariant option (const QString &opt) const
Returns the value related to option opt if it was set by the server.
QVariantHash options () const
Returns all incoming options set in this QAuthenticator object by parsing the server reply.
QString password () const
returns the password used for authentication.
QAuthenticator ()
Constructs an empty authentication object.
QAuthenticator (const QAuthenticator &other)
Constructs a copy of other.
QString realm () const
returns the realm requiring authentication.
void setOption (const QString &opt, const QVariant &value)
Sets the outgoing option opt to value value.
void setPassword (const QString &password)
Sets the password used for authentication.
void setUser (const QString &user)
Sets the user used for authentication.
QString user () const
returns the user used for authentication.
~QAuthenticator ()
Destructs the object.
Properties
QAuthenticatorPrivate * d
Friends
class QAuthenticatorPrivate
Detailed Description
The QAuthenticator class provides an authentication object.
Since
4.3
Note
This class or function is reentrant.
Attention
Module: QtNetwork
The QAuthenticator class is usually used in the QNetworkAccessManager::authenticationRequired() and QNetworkAccessManager::proxyAuthenticationRequired() signals of QNetworkAccessManager and QAbstractSocket. The class provides a way to pass back the required authentication information to the socket when accessing services that require authentication.
QAuthenticator supports the following authentication methods:
Basic
NTLM version 2
Digest-MD5
Options
In addition to the username and password required for authentication, a QAuthenticator object can also contain additional options. The options() function can be used to query incoming options sent by the server; the setOption() function can be used to set outgoing options, to be processed by the authenticator calculation. The options accepted and provided depend on the authentication type (see method()).
The following tables list known incoming options as well as accepted outgoing options. The list of incoming options is not exhaustive, since servers may include additional information at any time. The list of outgoing options is exhaustive, however, and no unknown options will be treated or sent back to the server.
Basic
Option Direction Description
realm Incoming Contains the realm of the authentication, the same as realm()
The Basic authentication mechanism supports no outgoing options.
NTLM version 2
The NTLM authentication mechanism currently supports no incoming or outgoing options.
Digest-MD5
Option Direction Description
realm Incoming Contains the realm of the authentication, the same as realm()
The Digest-MD5 authentication mechanism supports no outgoing options.
See also
QSslSocket
Definition at line 57 of file qauthenticator.h.
Constructors and Destructors
QAuthenticator() [1/2]
QAuthenticator::QAuthenticator ()
Constructs an empty authentication object.
Definition at line 137 of file qauthenticator.cpp.
     : d(0)
 {
 }
~QAuthenticator()
QAuthenticator::~QAuthenticator ()
Destructs the object.
Definition at line 145 of file qauthenticator.cpp.
 {
     if (d)
         delete d;
 }
QAuthenticator() [2/2]
QAuthenticator::QAuthenticator (const QAuthenticator & other)
Constructs a copy of other.
Definition at line 154 of file qauthenticator.cpp.
     : d(0)
 {
     if (other.d)
         *this = other;
 }
Functions
detach()
void QAuthenticator::detach ()
Warning
This function is not part of the public interface.
Definition at line 252 of file qauthenticator.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), QHttpNetworkConnectionChannel::ensureConnection(), QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), operator=(), setOption(), setPassword(), and setUser().
 {
     if (!d) {
         d = new QAuthenticatorPrivate;
         return;
     }
     if (d->phase == QAuthenticatorPrivate::Done)
         d->phase = QAuthenticatorPrivate::Start;
 }
isNull()
bool QAuthenticator::isNull () const
Returns true if the authenticator is null.
Definition at line 324 of file qauthenticator.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), QNetworkAccessFtpBackend::ftpDone(), and QHttpNetworkConnectionPrivate::handleAuthenticateChallenge().
 {
     return !d;
 }
operator!=()
bool QAuthenticator::operator!= (const QAuthenticator & other) const inline
Returns true if this authenticator is different from other; otherwise returns false.
Definition at line 67 of file qauthenticator.h.
 { return !operator==(other); }
operator=()
QAuthenticator & QAuthenticator::operator= (const QAuthenticator & other)
Assigns the contents of other to this authenticator.
Definition at line 164 of file qauthenticator.cpp.
 {
     if (d == other.d)
         return *this;
     // Do not share the d since challenge reponse/based changes
     // could corrupt the internal store and different network requests
     // can utilize different types of proxies.
     detach();
     if (other.d) {
         d->user = other.d->user;
         d->userDomain = other.d->userDomain;
         d->workstation = other.d->workstation;
         d->extractedUser = other.d->extractedUser;
         d->password = other.d->password;
         d->realm = other.d->realm;
         d->method = other.d->method;
         d->options = other.d->options;
     } else if (d->phase == QAuthenticatorPrivate::Start) {
         delete d;
         d = 0;
     }
     return *this;
 }
operator==()
bool QAuthenticator::operator== (const QAuthenticator & other) const
Returns true if this authenticator is identical to other; otherwise returns false.
Definition at line 193 of file qauthenticator.cpp.
 {
     if (d == other.d)
         return true;
     return d->user == other.d->user
         && d->password == other.d->password
         && d->realm == other.d->realm
         && d->method == other.d->method
         && d->options == other.d->options;
 }
option()
QVariant QAuthenticator::option (const QString & opt) const
Returns the value related to option opt if it was set by the server.
Since
4.7
See QAuthenticator#Options for more information on incoming options. If option opt isn't found, an invalid QVariant will be returned.
See also
options(), QAuthenticator::Options
Definition at line 282 of file qauthenticator.cpp.
 {
     return d ? d->options.value(opt) : QVariant();
 }
options()
QVariantHash QAuthenticator::options () const
Returns all incoming options set in this QAuthenticator object by parsing the server reply.
Since
4.7 See QAuthenticator#Options for more information on incoming options.
See also
option(), QAuthenticator::Options
Definition at line 298 of file qauthenticator.cpp.
 {
     return d ? d->options : QVariantHash();
 }
password()
QString QAuthenticator::password () const
returns the password used for authentication.
Definition at line 235 of file qauthenticator.cpp.
Referenced by QNetworkAccessAuthenticationManager::cacheCredentials(), QNetworkAccessAuthenticationManager::cacheProxyCredentials(), QHttpNetworkConnectionPrivate::copyCredentials(), QHttpNetworkConnectionPrivate::fillPipeline(), QNetworkAccessFtpBackend::ftpDone(), QSocks5SocketEnginePrivate::reauthenticate(), QHttpNetworkConnectionChannel::sendRequest(), and setPassword().
 {
     return d ? d->password : QString();
 }
realm()
QString QAuthenticator::realm () const
returns the realm requiring authentication.
Definition at line 266 of file qauthenticator.cpp.
Referenced by QNetworkAccessAuthenticationManager::cacheCredentials(), QNetworkAccessAuthenticationManager::cacheProxyCredentials(), QNetworkAccessAuthenticationManager::fetchCachedCredentials(), and QNetworkAccessAuthenticationManager::fetchCachedProxyCredentials().
 {
     return d ? d->realm : QString();
 }
setOption()
void QAuthenticator::setOption (const QString & opt, const QVariant & value)
Sets the outgoing option opt to value value.
Since
4.7
See QAuthenticator#Options for more information on outgoing options.
See also
options(), option(), QAuthenticator::Options
Definition at line 314 of file qauthenticator.cpp.
 {
     detach();
     d->options.insert(opt, value);
 }
setPassword()
void QAuthenticator::setPassword (const QString & password)
Sets the password used for authentication.
Definition at line 243 of file qauthenticator.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QHttpNetworkConnectionPrivate::copyCredentials(), QNetworkAccessManagerPrivate::proxyAuthenticationRequired(), QHttpNetworkConnectionChannel::sendRequest(), QHttpThreadDelegate::synchronousAuthenticationRequiredSlot(), and QHttpThreadDelegate::synchronousProxyAuthenticationRequiredSlot().
 {
     detach();
     d->password = password;
 }
setUser()
void QAuthenticator::setUser (const QString & user)
Sets the user used for authentication.
Definition at line 225 of file qauthenticator.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QHttpNetworkConnectionPrivate::copyCredentials(), QNetworkAccessManagerPrivate::proxyAuthenticationRequired(), QHttpNetworkConnectionChannel::sendRequest(), QHttpThreadDelegate::synchronousAuthenticationRequiredSlot(), and QHttpThreadDelegate::synchronousProxyAuthenticationRequiredSlot().
 {
     detach();
     d->user = user;
     d->updateCredentials();
 }
user()
QString QAuthenticator::user () const
returns the user used for authentication.
Definition at line 217 of file qauthenticator.cpp.
Referenced by QNetworkAccessAuthenticationManager::cacheCredentials(), QNetworkAccessAuthenticationManager::cacheProxyCredentials(), QHttpNetworkConnectionPrivate::copyCredentials(), QHttpNetworkConnectionPrivate::fillPipeline(), QNetworkAccessFtpBackend::ftpDone(), QSocks5SocketEnginePrivate::reauthenticate(), QHttpNetworkConnectionChannel::sendRequest(), and setUser().
 {
     return d ? d->user : QString();
 }
Friends and Related Functions
QAuthenticatorPrivate
friend class QAuthenticatorPrivate friend
Definition at line 84 of file qauthenticator.h.
Referenced by detach().
Properties
d
QAuthenticatorPrivate* QAuthenticator::d private
Definition at line 85 of file qauthenticator.h.
Referenced by detach(), QAuthenticatorPrivate::getPrivate(), isNull(), operator=(), operator==(), option(), options(), password(), QAuthenticator(), realm(), setOption(), setPassword(), setUser(), user(), and ~QAuthenticator().
The documentation for this class was generated from the following files:
/src/network/kernel/qauthenticator.h
/src/network/kernel/qauthenticator.cpp