Qt 4.8: QDeclarativeParentAnimation Class Reference
QDeclarativeParentAnimation Class Reference
#include <qdeclarativeanimation_p.h>
Signals
void newParentChanged ()
void targetChanged ()
void viaChanged ()
Signals inherited from QDeclarativeAbstractAnimation
void alwaysRunToEndChanged (bool)
void completed ()
void loopCountChanged (int)
void pausedChanged (bool)
void runningChanged (bool)
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeItem * newParent () const
QDeclarativeParentAnimation (QObject *parent=0)
void setNewParent (QDeclarativeItem *)
void setTarget (QDeclarativeItem *)
void setVia (QDeclarativeItem *)
QDeclarativeItem * target () const
QDeclarativeItem * via () const
virtual ~QDeclarativeParentAnimation ()
Public Functions inherited from QDeclarativeAnimationGroup
QDeclarativeListProperty< QDeclarativeAbstractAnimation > animations ()
QDeclarativeAnimationGroup (QObject *parent)
virtual ~QDeclarativeAnimationGroup ()
Public Functions inherited from QDeclarativeAbstractAnimation
bool alwaysRunToEnd () const
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int currentTime ()
QDeclarativeAnimationGroup * group () const
bool isPaused () const
bool isRunning () const
int loops () const
QDeclarativeAbstractAnimation (QObject *parent=0)
void setAlwaysRunToEnd (bool)
void setCurrentTime (int)
void setDefaultTarget (const QDeclarativeProperty &)
void setDisableUserControl ()
void setGroup (QDeclarativeAnimationGroup *)
void setLoops (int)
void setPaused (bool)
void setRunning (bool)
virtual ~QDeclarativeAbstractAnimation ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueSource
QDeclarativePropertyValueSource ()
Constructs a QDeclarativePropertyValueSource.
virtual ~QDeclarativePropertyValueSource ()
Destroys the value source.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual QAbstractAnimation * qtAnimation ()
virtual void transition (QDeclarativeStateActions &actions, QDeclarativeProperties &modified, TransitionDirection direction)
Protected Functions inherited from QDeclarativeAnimationGroup
QDeclarativeAnimationGroup (QDeclarativeAnimationGroupPrivate &dd, QObject *parent)
Protected Functions inherited from QDeclarativeAbstractAnimation
QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QDeclarativeItem * newParent
QDeclarativeItem * target
QDeclarativeItem * via
Additional Inherited Members
Public Types inherited from QDeclarativeAbstractAnimation
enum Loops { Infinite = -2 }
enum TransitionDirection { Forward, Backward }
Public Slots inherited from QDeclarativeAbstractAnimation
void complete ()
void pause ()
void restart ()
void resume ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 444 of file qdeclarativeanimation_p.h.
Constructors and Destructors
QDeclarativeParentAnimation()
QDeclarativeParentAnimation::QDeclarativeParentAnimation (QObject * parent = 0)
Definition at line 2600 of file qdeclarativeanimation.cpp.
     : QDeclarativeAnimationGroup(*(new QDeclarativeParentAnimationPrivate), parent)
 {
     Q_D(QDeclarativeParentAnimation);
     d->topLevelGroup = new QSequentialAnimationGroup;
     QDeclarative_setParent_noEvent(d->topLevelGroup, this);
     d->startAction = new QActionAnimation;
     QDeclarative_setParent_noEvent(d->startAction, d->topLevelGroup);
     d->topLevelGroup->addAnimation(d->startAction);
     d->ag = new QParallelAnimationGroup;
     QDeclarative_setParent_noEvent(d->ag, d->topLevelGroup);
     d->topLevelGroup->addAnimation(d->ag);
     d->endAction = new QActionAnimation;
     QDeclarative_setParent_noEvent(d->endAction, d->topLevelGroup);
     d->topLevelGroup->addAnimation(d->endAction);
 }
~QDeclarativeParentAnimation()
QDeclarativeParentAnimation::~QDeclarativeParentAnimation () virtual
Definition at line 2620 of file qdeclarativeanimation.cpp.
 {
 }
Functions
newParent()
QDeclarativeItem* QDeclarativeParentAnimation::newParent () const
Referenced by setNewParent(), and setTarget().
newParentChanged
void QDeclarativeParentAnimation::newParentChanged () signal
Referenced by setNewParent().
qtAnimation()
QAbstractAnimation * QDeclarativeParentAnimation::qtAnimation () protected virtual
Implements QDeclarativeAbstractAnimation.
Definition at line 2927 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeParentAnimation);
     return d->topLevelGroup;
 }
setNewParent()
void QDeclarativeParentAnimation::setNewParent (QDeclarativeItem * newParent)
Definition at line 2668 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeParentAnimation);
     if (newParent == d->newParent)
         return;
     d->newParent = newParent;
     emit newParentChanged();
 }
setTarget()
void QDeclarativeParentAnimation::setTarget (QDeclarativeItem * target)
Definition at line 2640 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeParentAnimation);
     if (target == d->target)
         return;
     d->target = target;
     emit targetChanged();
 }
setVia()
void QDeclarativeParentAnimation::setVia (QDeclarativeItem * via)
Definition at line 2700 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeParentAnimation);
     if (via == d->via)
         return;
     d->via = via;
     emit viaChanged();
 }
target()
QDeclarativeItem* QDeclarativeParentAnimation::target () const
Referenced by setTarget(), transition(), and ~QDeclarativeParentAnimation().
targetChanged
void QDeclarativeParentAnimation::targetChanged () signal
Referenced by setTarget().
transition()
void QDeclarativeParentAnimation::transition (QDeclarativeStateActions & actions, QDeclarativeProperties & modified, TransitionDirection direction) protected virtual
Reimplemented from QDeclarativeAbstractAnimation.
Definition at line 2736 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeParentAnimation);
     struct QDeclarativeParentAnimationData : public QAbstractAnimationAction
     {
         QDeclarativeParentAnimationData() {}
         ~QDeclarativeParentAnimationData() { qDeleteAll(pc); }
         QDeclarativeStateActions actions;
         //### reverse should probably apply on a per-action basis
         bool reverse;
         QList<QDeclarativeParentChange *> pc;
         virtual void doAction()
         {
             for (int ii = 0; ii < actions.count(); ++ii) {
                 const QDeclarativeAction &action = actions.at(ii);
                 if (reverse)
                     action.event->reverse();
                 else
                     action.event->execute();
             }
         }
     };
     QDeclarativeParentAnimationData *data = new QDeclarativeParentAnimationData;
     QDeclarativeParentAnimationData *viaData = new QDeclarativeParentAnimationData;
     bool hasExplicit = false;
     if (d->target && d->newParent) {
         data->reverse = false;
         QDeclarativeAction myAction;
         QDeclarativeParentChange *pc = new QDeclarativeParentChange;
         pc->setObject(d->target);
         pc->setParent(d->newParent);
         myAction.event = pc;
         data->pc << pc;
         data->actions << myAction;
         hasExplicit = true;
         if (d->via) {
             viaData->reverse = false;
             QDeclarativeAction myVAction;
             QDeclarativeParentChange *vpc = new QDeclarativeParentChange;
             vpc->setObject(d->target);
             vpc->setParent(d->via);
             myVAction.event = vpc;
             viaData->pc << vpc;
             viaData->actions << myVAction;
         }
         //### once actions have concept of modified,
         //    loop to match appropriate ParentChanges and mark as modified
     }
     if (!hasExplicit)
     for (int i = 0; i < actions.size(); ++i) {
         QDeclarativeAction &action = actions[i];
         if (action.event && action.event->typeName() == QLatin1String("ParentChange")
             && (!d->target || static_cast<QDeclarativeParentChange*>(action.event)->object() == d->target)) {
             QDeclarativeParentChange *pc = static_cast<QDeclarativeParentChange*>(action.event);
             QDeclarativeAction myAction = action;
             data->reverse = action.reverseEvent;
             //### this logic differs from PropertyAnimation
             //    (probably a result of modified vs. done)
             if (d->newParent) {
                 QDeclarativeParentChange *epc = new QDeclarativeParentChange;
                 epc->setObject(static_cast<QDeclarativeParentChange*>(action.event)->object());
                 epc->setParent(d->newParent);
                 myAction.event = epc;
                 data->pc << epc;
                 data->actions << myAction;
                 pc = epc;
             } else {
                 action.actionDone = true;
                 data->actions << myAction;
             }
             if (d->via) {
                 viaData->reverse = false;
                 QDeclarativeAction myAction;
                 QDeclarativeParentChange *vpc = new QDeclarativeParentChange;
                 vpc->setObject(pc->object());
                 vpc->setParent(d->via);
                 myAction.event = vpc;
                 viaData->pc << vpc;
                 viaData->actions << myAction;
                 QDeclarativeAction dummyAction;
                 QDeclarativeAction &xAction = pc->xIsSet() && i < actions.size()-1 ? actions[++i] : dummyAction;
                 QDeclarativeAction &yAction = pc->yIsSet() && i < actions.size()-1 ? actions[++i] : dummyAction;
                 QDeclarativeAction &sAction = pc->scaleIsSet() && i < actions.size()-1 ? actions[++i] : dummyAction;
                 QDeclarativeAction &rAction = pc->rotationIsSet() && i < actions.size()-1 ? actions[++i] : dummyAction;
                 QDeclarativeItem *target = pc->object();
                 QDeclarativeItem *targetParent = action.reverseEvent ? pc->originalParent() : pc->parent();
                 //### this mirrors the logic in QDeclarativeParentChange.
                 bool ok;
                 const QTransform &transform = targetParent->itemTransform(d->via, &ok);
                 if (transform.type() >= QTransform::TxShear || !ok) {
                     qmlInfo(this) << QDeclarativeParentAnimation::tr("Unable to preserve appearance under complex transform");
                     ok = false;
                 }
                 qreal scale = 1;
                 qreal rotation = 0;
                 bool isRotate = (transform.type() == QTransform::TxRotate) || (transform.m11() < 0);
                 if (ok && !isRotate) {
                     if (transform.m11() == transform.m22())
                         scale = transform.m11();
                     else {
                         qmlInfo(this) << QDeclarativeParentAnimation::tr("Unable to preserve appearance under non-uniform scale");
                         ok = false;
                     }
                 } else if (ok && isRotate) {
                     if (transform.m11() == transform.m22())
                         scale = qSqrt(transform.m11()*transform.m11() + transform.m12()*transform.m12());
                     else {
                         qmlInfo(this) << QDeclarativeParentAnimation::tr("Unable to preserve appearance under non-uniform scale");
                         ok = false;
                     }
                     if (scale != 0)
                         rotation = atan2(transform.m12()/scale, transform.m11()/scale) * 180/qreal(M_PI);
                     else {
                         qmlInfo(this) << QDeclarativeParentAnimation::tr("Unable to preserve appearance under scale of 0");
                         ok = false;
                     }
                 }
                 const QPointF &point = transform.map(QPointF(xAction.toValue.toReal(),yAction.toValue.toReal()));
                 qreal x = point.x();
                 qreal y = point.y();
                 if (ok && target->transformOrigin() != QDeclarativeItem::TopLeft) {
                     qreal w = target->width();
                     qreal h = target->height();
                     if (pc->widthIsSet() && i < actions.size() - 1)
                         w = actions[++i].toValue.toReal();
                     if (pc->heightIsSet() && i < actions.size() - 1)
                         h = actions[++i].toValue.toReal();
                     const QPointF &transformOrigin
                             = d->computeTransformOrigin(target->transformOrigin(), w,h);
                     qreal tempxt = transformOrigin.x();
                     qreal tempyt = transformOrigin.y();
                     QTransform t;
                     t.translate(-tempxt, -tempyt);
                     t.rotate(rotation);
                     t.scale(scale, scale);
                     t.translate(tempxt, tempyt);
                     const QPointF &offset = t.map(QPointF(0,0));
                     x += offset.x();
                     y += offset.y();
                 }
                 if (ok) {
                     //qDebug() << x << y << rotation << scale;
                     xAction.toValue = x;
                     yAction.toValue = y;
                     sAction.toValue = sAction.toValue.toReal() * scale;
                     rAction.toValue = rAction.toValue.toReal() + rotation;
                 }
             }
         }
     }
     if (data->actions.count()) {
         if (direction == QDeclarativeAbstractAnimation::Forward) {
             d->startAction->setAnimAction(d->via ? viaData : data, QActionAnimation::DeleteWhenStopped);
             d->endAction->setAnimAction(d->via ? data : 0, QActionAnimation::DeleteWhenStopped);
         } else {
             d->endAction->setAnimAction(d->via ? viaData : data, QActionAnimation::DeleteWhenStopped);
             d->startAction->setAnimAction(d->via ? data : 0, QActionAnimation::DeleteWhenStopped);
         }
         if (!d->via)
             delete viaData;
     } else {
         delete data;
         delete viaData;
     }
     //take care of any child animations
     bool valid = d->defaultProperty.isValid();
     for (int ii = 0; ii < d->animations.count(); ++ii) {
         if (valid)
             d->animations.at(ii)->setDefaultTarget(d->defaultProperty);
         d->animations.at(ii)->transition(actions, modified, direction);
     }
 }
via()
QDeclarativeItem* QDeclarativeParentAnimation::via () const
Referenced by setNewParent(), and setVia().
viaChanged
void QDeclarativeParentAnimation::viaChanged () signal
Referenced by setVia().
Properties
newParent
QDeclarativeItem * QDeclarativeParentAnimation::newParent private
Definition at line 450 of file qdeclarativeanimation_p.h.
target
QDeclarativeItem * QDeclarativeParentAnimation::target private
Definition at line 449 of file qdeclarativeanimation_p.h.
via
QDeclarativeItem * QDeclarativeParentAnimation::via private
Definition at line 451 of file qdeclarativeanimation_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeanimation_p.h
/src/declarative/util/qdeclarativeanimation.cpp