Qt 4.8: QFakeDevice Class Reference
QFakeDevice Class Reference
Public Functions
int metric (PaintDeviceMetric m) const
int metric (PaintDeviceMetric m) const
QPaintEngine * paintEngine () const
QPaintEngine * paintEngine () const
QFakeDevice ()
QFakeDevice ()
void setDpiX (int dpi)
void setDpiX (int dpi)
void setDpiY (int dpi)
void setDpiY (int dpi)
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual int devType () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Properties
int dpi_x
int dpi_y
Additional Inherited Members
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 455 of file qpicture.cpp.
Constructors and Destructors
QFakeDevice() [1/2]
QFakeDevice::QFakeDevice () inline
Definition at line 458 of file qpicture.cpp.
 { dpi_x = qt_defaultDpiX(); dpi_y = qt_defaultDpiY(); }
QFakeDevice() [2/2]
QFakeDevice::QFakeDevice () inline
Definition at line 1348 of file qpaintbuffer.cpp.
 { dpi_x = qt_defaultDpiX(); dpi_y = qt_defaultDpiY(); }
Functions
metric() [1/2]
int QFakeDevice::metric (PaintDeviceMetric m) const inline virtual
Reimplemented from QPaintDevice.
Definition at line 462 of file qpicture.cpp.
     {
         switch(m) {
             case PdmPhysicalDpiX:
             case PdmDpiX:
                 return dpi_x;
             case PdmPhysicalDpiY:
             case PdmDpiY:
                 return dpi_y;
             default:
                 return QPaintDevice::metric(m);
         }
     }
metric() [2/2]
int QFakeDevice::metric (PaintDeviceMetric m) const inline virtual
Reimplemented from QPaintDevice.
Definition at line 1352 of file qpaintbuffer.cpp.
     {
         switch(m) {
             case PdmPhysicalDpiX:
             case PdmDpiX:
                 return dpi_x;
             case PdmPhysicalDpiY:
             case PdmDpiY:
                 return dpi_y;
             default:
                 return QPaintDevice::metric(m);
         }
     }
paintEngine() [1/2]
QPaintEngine* QFakeDevice::paintEngine () const inline virtual
Implements QPaintDevice.
Definition at line 461 of file qpicture.cpp.
 { return 0; }
paintEngine() [2/2]
QPaintEngine* QFakeDevice::paintEngine () const inline virtual
Implements QPaintDevice.
Definition at line 1351 of file qpaintbuffer.cpp.
 { return 0; }
setDpiX() [1/2]
void QFakeDevice::setDpiX (int dpi) inline
Definition at line 459 of file qpicture.cpp.
Referenced by QPicture::exec(), and QPainterReplayer::process().
 { dpi_x = dpi; }
setDpiX() [2/2]
void QFakeDevice::setDpiX (int dpi) inline
Definition at line 1349 of file qpaintbuffer.cpp.
 { dpi_x = dpi; }
setDpiY() [1/2]
void QFakeDevice::setDpiY (int dpi) inline
Definition at line 460 of file qpicture.cpp.
Referenced by QPicture::exec(), and QPainterReplayer::process().
 { dpi_y = dpi; }
setDpiY() [2/2]
void QFakeDevice::setDpiY (int dpi) inline
Definition at line 1350 of file qpaintbuffer.cpp.
 { dpi_y = dpi; }
Properties
dpi_x
int QFakeDevice::dpi_x private
Definition at line 477 of file qpicture.cpp.
dpi_y
int QFakeDevice::dpi_y private
Definition at line 478 of file qpicture.cpp.
The documentation for this class was generated from the following files:
/src/gui/image/qpicture.cpp
/src/gui/painting/qpaintbuffer.cpp