Qt 4.8: QSqlRecord Class Reference
QSqlRecord Class Reference
The QSqlRecord class encapsulates a database record.
#include <qsqlrecord.h>
Public Functions
void append (const QSqlField &field)
Append a copy of field field to the end of the record.
void clear ()
Removes all the record's fields.
void clearValues ()
Clears the value of all fields in the record and sets each field to null.
bool contains (const QString &name) const
Returns true if there is a field in the record called name; otherwise returns false.
int count () const
Returns the number of fields in the record.
QSqlField field (int i) const
Returns the field at position index.
QSqlField field (const QString &name) const
Returns the field called name.
QString fieldName (int i) const
Returns the name of the field at position index.
int indexOf (const QString &name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
void insert (int pos, const QSqlField &field)
Inserts the field field at position pos in the record.
bool isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
bool isGenerated (int i) const
Returns true if the record has a field at position index and this field is to be generated (the default); otherwise returns false.
bool isGenerated (const QString &name) const
Returns true if the record has a field called name and this field is to be generated (the default); otherwise returns false.
bool isNull (int i) const
Returns true if the field index is null or if there is no field at position index; otherwise returns false.
bool isNull (const QString &name) const
Returns true if the field called name is null or if there is no field called name; otherwise returns false.
bool operator!= (const QSqlRecord &other) const
Returns true if this object is not identical to other; otherwise returns false.
QSqlRecord & operator= (const QSqlRecord &other)
Sets the record equal to other.
bool operator== (const QSqlRecord &other) const
Returns true if this object is identical to other (i.e., has the same fields in the same order); otherwise returns false.
QSqlRecord ()
Constructs an empty record.
QSqlRecord (const QSqlRecord &other)
Constructs a copy of other.
void remove (int pos)
Removes the field at position pos.
void replace (int pos, const QSqlField &field)
Replaces the field at position pos with the given field.
void setGenerated (const QString &name, bool generated)
Sets the generated flag for the field called name to generated.
void setGenerated (int i, bool generated)
Sets the generated flag for the field index to generated.
void setNull (int i)
Sets the value of field index to null.
void setNull (const QString &name)
Sets the value of the field called name to null.
void setValue (int i, const QVariant &val)
Sets the value of the field at position index to val.
void setValue (const QString &name, const QVariant &val)
Sets the value of the field called name to val.
QVariant value (int i) const
Returns the value of the field located at position index in the record.
QVariant value (const QString &name) const
Returns the value of the field called name in the record.
~QSqlRecord ()
Destroys the object and frees any allocated resources.
Private Functions
void detach ()
Properties
QSqlRecordPrivate * d
Detailed Description
The QSqlRecord class encapsulates a database record.
Attention
Module: QtSql
The QSqlRecord class encapsulates the functionality and characteristics of a database record (usually a row in a table or view within the database). QSqlRecord supports adding and removing fields as well as setting and retrieving field values.
The values of a record's fields' can be set by name or position with setValue(); if you want to set a field to null use setNull(). To find the position of a field by name use indexOf(), and to find the name of a field at a particular position use fieldName(). Use field() to retrieve a QSqlField object for a given field. Use contains() to see if the record contains a particular field name.
When queries are generated to be executed on the database only those fields for which isGenerated() is true are included in the generated SQL.
A record can have fields added with append() or insert(), replaced with replace(), and removed with remove(). All the fields can be removed with clear(). The number of fields is given by count(); all their values can be cleared (to null) using clearValues().
See also
QSqlField, QSqlQuery::record()
Definition at line 58 of file qsqlrecord.h.
Constructors and Destructors
QSqlRecord() [1/2]
QSqlRecord::QSqlRecord ()
Constructs an empty record.
See also
isEmpty(), append(), insert()
Definition at line 131 of file qsqlrecord.cpp.
 {
     d = new QSqlRecordPrivate();
 }
QSqlRecord() [2/2]
QSqlRecord::QSqlRecord (const QSqlRecord & other)
Constructs a copy of other.
QSqlRecord is implicitly shared. This means you can make copies of a record in constant time.
Definition at line 143 of file qsqlrecord.cpp.
 {
     d = other.d;
     d->ref.ref();
 }
~QSqlRecord()
QSqlRecord::~QSqlRecord ()
Destroys the object and frees any allocated resources.
Definition at line 166 of file qsqlrecord.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
append()
void QSqlRecord::append (const QSqlField & field)
Append a copy of field field to the end of the record.
See also
insert() replace() remove()
Definition at line 312 of file qsqlrecord.cpp.
Referenced by QSqlIndex::append(), QDB2Result::exec(), QODBCResult::exec(), QSQLite2ResultPrivate::init(), QSQLiteResultPrivate::initColumns(), QSymSQLResultPrivate::initColumns(), QDB2Result::nextResult(), QODBCResult::nextResult(), QOCICols::QOCICols(), QIBaseResult::record(), QPSQLResult::record(), QMYSQLResult::record(), QDB2Driver::record(), QIBaseDriver::record(), QOCIDriver::record(), QTDSDriver::record(), QMYSQLDriver::record(), QODBCDriver::record(), QPSQLDriver::record(), QDB2Result::reset(), QTDSResult::reset(), and QODBCResult::reset().
 {
     detach();
     d->fields.append(field);
 }
clear()
void QSqlRecord::clear (void)
Removes all the record's fields.
See also
clearValues() isEmpty()
Definition at line 367 of file qsqlrecord.cpp.
Referenced by QTDSResult::cleanup(), QSQLite2ResultPrivate::cleanup(), QSQLiteResultPrivate::cleanup(), QSqlTableModelPrivate::clear(), QDB2Result::exec(), QSQLiteResult::exec(), QODBCResult::exec(), QSQLite2ResultPrivate::init(), QDB2Result::nextResult(), QODBCResult::nextResult(), QDB2Result::prepare(), QODBCResult::prepare(), QDB2Result::reset(), and QODBCResult::reset().
 {
     detach();
     d->fields.clear();
 }
clearValues()
void QSqlRecord::clearValues ()
Clears the value of all fields in the record and sets each field to null.
See also
setValue()
Definition at line 403 of file qsqlrecord.cpp.
 {
     detach();
     int count = d->fields.count();
     for (int i = 0; i < count; ++i)
         d->fields[i].clear();
 }
contains()
bool QSqlRecord::contains (const QString & name) const
Returns true if there is a field in the record called name; otherwise returns false.
Definition at line 391 of file qsqlrecord.cpp.
Referenced by QSQLite2Driver::primaryIndex().
 {
     return indexOf(name) >= 0;
 }
count()
int QSqlRecord::count () const
Returns the number of fields in the record.
See also
isEmpty()
Definition at line 573 of file qsqlrecord.cpp.
Referenced by QSqlTableModelPrivate::clearGenerated(), QDB2Result::data(), QODBCResult::data(), QSqlTableModelPrivate::exec(), QSQLiteResultPrivate::fetchNext(), QTDSResult::gotoNext(), operator<<(), QSqlTableModelPrivate::primaryValues(), qmlsqldatabase_item(), QSqlQueryModel::record(), QSqlTableModelPrivate::record(), QSqlQuery::record(), QSqlRelationalTableModel::selectStatement(), QSqlIndex::setDescending(), QSqlQueryModel::setQuery(), QSqlTableModelPrivate::setRecord(), QSqlTableModel::setRecord(), QSqlDriver::sqlStatement(), and QSqlRelationalTableModelPrivate::translateFieldNames().
 {
     return d->fields.count();
 }
detach()
void QSqlRecord::detach () private
Warning
This function is not part of the public interface.
Definition at line 612 of file qsqlrecord.cpp.
 {
     qAtomicDetach(d);
 }
field() [1/2]
QSqlField QSqlRecord::field (int index) const
Returns the field at position index.
If the index is out of range, function returns a default-constructed value.
Definition at line 289 of file qsqlrecord.cpp.
Referenced by QSqlIndex::createField(), QDB2Result::data(), QODBCResult::data(), QTDSResult::gotoNext(), operator<<(), QRelation::populateDictionary(), QDB2Driver::primaryIndex(), QSQLite2Driver::primaryIndex(), QTDSDriver::primaryIndex(), QMYSQLDriver::primaryIndex(), QODBCDriver::primaryIndex(), and QSqlDriver::sqlStatement().
 {
     return d->fields.value(index);
 }
field() [2/2]
QSqlField QSqlRecord::field (const QString & name) const
Returns the field called name.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 300 of file qsqlrecord.cpp.
 {
     return field(indexOf(name));
 }
fieldName()
QString QSqlRecord::fieldName (int index) const
Returns the name of the field at position index.
If the field does not exist, an empty string is returned.
See also
indexOf()
Definition at line 232 of file qsqlrecord.cpp.
Referenced by QSqlTableModelPrivate::primaryValues(), qmlsqldatabase_item(), QSqlRelationalTableModel::selectStatement(), QSqlTableModelPrivate::setRecord(), QSqlTableModel::setRecord(), and QSqlDriver::sqlStatement().
 {
     return d->fields.value(index).name();
 }
indexOf()
int QSqlRecord::indexOf (const QString & name) const
Returns the position of the field called name within the record, or -1 if it cannot be found.
Field names are not case-sensitive. If more than one field matches, the first one is returned.
See also
fieldName()
Definition at line 246 of file qsqlrecord.cpp.
Referenced by QSqlTableModelPrivate::nameToIndex(), QSqlTableModelPrivate::primaryValues(), and QSqlTableModel::setRecord().
 {
     QString nm = name.toUpper();
     for (int i = 0; i < count(); ++i) {
         if (d->fields.at(i).name().toUpper() == nm) // TODO: case-insensitive comparison
             return i;
     }
     return -1;
 }
insert()
void QSqlRecord::insert (int pos, const QSqlField & field)
Inserts the field field at position pos in the record.
See also
append() replace() remove()
Definition at line 323 of file qsqlrecord.cpp.
 {
    detach();
    d->fields.insert(pos, field);
 }
isEmpty()
bool QSqlRecord::isEmpty () const
Returns true if there are no fields in the record; otherwise returns false.
See also
append() insert() clear()
Definition at line 380 of file qsqlrecord.cpp.
Referenced by QSQLiteResult::exec(), QSQLite2ResultPrivate::fetchNext(), QSQLiteResultPrivate::fetchNext(), QSqlTableModelPrivate::primaryValues(), and QSQLite2Result::reset().
 {
     return d->fields.isEmpty();
 }
isGenerated() [1/2]
bool QSqlRecord::isGenerated (int index) const
Returns true if the record has a field at position index and this field is to be generated (the default); otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setGenerated()
Definition at line 519 of file qsqlrecord.cpp.
Referenced by QSqlTableModel::data(), QSqlRelationalTableModel::data(), QSqlTableModelPrivate::exec(), QSqlTableModel::isDirty(), QSqlTableModelPrivate::setRecord(), QSqlTableModel::setRecord(), QSqlDriver::sqlStatement(), and QSqlRelationalTableModelPrivate::translateFieldNames().
 {
     return d->fields.value(index).isGenerated();
 }
isGenerated() [2/2]
bool QSqlRecord::isGenerated (const QString & name) const
Returns true if the record has a field called name and this field is to be generated (the default); otherwise returns false.
See also
setGenerated()
Definition at line 504 of file qsqlrecord.cpp.
 {
     return isGenerated(indexOf(name));
 }
isNull() [1/2]
bool QSqlRecord::isNull (int index) const
Returns true if the field index is null or if there is no field at position index; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 453 of file qsqlrecord.cpp.
Referenced by QSqlTableModelPrivate::exec(), and QSqlDriver::sqlStatement().
 {
     return d->fields.value(index).isNull();
 }
isNull() [2/2]
bool QSqlRecord::isNull (const QString & name) const
Returns true if the field called name is null or if there is no field called name; otherwise returns false.
See also
setNull()
Definition at line 464 of file qsqlrecord.cpp.
 {
     return isNull(indexOf(name));
 }
operator!=()
bool QSqlRecord::operator!= (const QSqlRecord & other) const inline
Returns true if this object is not identical to other; otherwise returns false.
See also
operator==()
Definition at line 67 of file qsqlrecord.h.
 { return !operator==(other); }
operator=()
QSqlRecord & QSqlRecord::operator= (const QSqlRecord & other)
Sets the record equal to other.
QSqlRecord is implicitly shared. This means you can make copies of a record in constant time.
Definition at line 156 of file qsqlrecord.cpp.
Referenced by QSqlIndex::operator=().
 {
     qAtomicAssign(d, other.d);
     return *this;
 }
operator==()
bool QSqlRecord::operator== (const QSqlRecord & other) const
Returns true if this object is identical to other (i.e., has the same fields in the same order); otherwise returns false.
See also
operator!=()
Definition at line 190 of file qsqlrecord.cpp.
 {
     return d->fields == other.d->fields;
 }
remove()
void QSqlRecord::remove (int pos)
Removes the field at position pos.
If pos is out of range, nothing happens.
See also
append() insert() replace()
Definition at line 352 of file qsqlrecord.cpp.
 {
     if (!d->contains(pos))
         return;
     detach();
     d->fields.remove(pos);
 }
replace()
void QSqlRecord::replace (int pos, const QSqlField & field)
Replaces the field at position pos with the given field.
If pos is out of range, nothing happens.
See also
append() insert() remove()
Definition at line 336 of file qsqlrecord.cpp.
Referenced by QSqlRelationalTableModelPrivate::translateFieldNames().
 {
     if (!d->contains(pos))
         return;
     detach();
     d->fields[pos] = field;
 }
setGenerated() [1/2]
void QSqlRecord::setGenerated (const QString & name, bool generated)
Sets the generated flag for the field called name to generated.
If the field does not exist, nothing happens. Only fields that have generated set to true are included in the SQL that is generated by QSqlQueryModel for example.
See also
isGenerated()
Definition at line 420 of file qsqlrecord.cpp.
Referenced by QSqlTableModelPrivate::clearGenerated(), QSqlTableModelPrivate::setGeneratedValue(), QSqlTableModel::setRecord(), and QSqlRelationalTableModelPrivate::translateFieldNames().
 {
     setGenerated(indexOf(name), generated);
 }
setGenerated() [2/2]
void QSqlRecord::setGenerated (int index, bool generated)
Sets the generated flag for the field index to generated.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
isGenerated()
Definition at line 436 of file qsqlrecord.cpp.
 {
     if (!d->contains(index))
         return;
     detach();
     d->fields[index].setGenerated(generated);
 }
setNull() [1/2]
void QSqlRecord::setNull (int index)
Sets the value of field index to null.
If the field does not exist, nothing happens.
See also
setValue()
Definition at line 475 of file qsqlrecord.cpp.
 {
     if (!d->contains(index))
         return;
     detach();
     d->fields[index].clear();
 }
setNull() [2/2]
void QSqlRecord::setNull (const QString & name)
Sets the value of the field called name to null.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the field does not exist, nothing happens.
Definition at line 492 of file qsqlrecord.cpp.
 {
     setNull(indexOf(name));
 }
setValue() [1/2]
void QSqlRecord::setValue (int index, const QVariant & val)
Sets the value of the field at position index to val.
If the field does not exist, nothing happens.
See also
setNull()
Definition at line 585 of file qsqlrecord.cpp.
Referenced by QSqlTableModelPrivate::primaryValues(), QSqlQueryModel::record(), QSqlTableModelPrivate::record(), QSqlQuery::record(), QSqlTableModelPrivate::setGeneratedValue(), QSqlTableModel::setRecord(), and QSqlRelationalTableModelPrivate::translateFieldNames().
 {
     if (!d->contains(index))
         return;
     detach();
     d->fields[index].setValue(val);
 }
setValue() [2/2]
void QSqlRecord::setValue (const QString & name, const QVariant & val)
Sets the value of the field called name to val.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the field does not exist, nothing happens.
Definition at line 604 of file qsqlrecord.cpp.
 {
     setValue(indexOf(name), val);
 }
value() [1/2]
QVariant QSqlRecord::value (int index) const
Returns the value of the field located at position index in the record.
If index is out of bounds, an invalid QVariant is returned.
See also
fieldName() isNull()
Definition at line 203 of file qsqlrecord.cpp.
Referenced by QSqlTableModel::data(), QSqlRelationalTableModel::data(), QSqlTableModelPrivate::exec(), operator<<(), qmlsqldatabase_item(), QSqlTableModelPrivate::setRecord(), QSqlTableModel::setRecord(), and QSqlRelationalTableModelPrivate::translateFieldNames().
 {
     return d->fields.value(index).value();
 }
value() [2/2]
QVariant QSqlRecord::value (const QString & name) const
Returns the value of the field called name in the record.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If field name does not exist an invalid variant is returned.
See also
indexOf()
Definition at line 220 of file qsqlrecord.cpp.
 {
     return value(indexOf(name));
 }
Properties
d
QSqlRecordPrivate* QSqlRecord::d private
Definition at line 112 of file qsqlrecord.h.
Referenced by operator=(), operator==(), and QSqlRecord().
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqlrecord.h
/src/sql/kernel/qsqlrecord.cpp