Qt 4.8: QTgaFile Class Reference
QTgaFile Class Reference
#include <qtgafile.h>
Public Types
enum Compression { NoCompression = 0, RleCompression = 1 }
enum FooterOffset { ExtensionOffset = 0, DeveloperOffset = 4, SignatureOffset = 8, FooterSize = 26 }
enum HeaderOffset {
IdLength = 0, ColorMapType = 1, ImageType = 2, CMapStart = 3,
CMapLength = 5, CMapDepth = 7, XOffset = 8, YOffset = 10,
Width = 12, Height = 14, PixelDepth = 16, ImageDescriptor = 17,
HeaderSize = 18
}
Public Functions
Compression compression () const
QString errorMessage () const
int height () const
bool isValid () const
QTgaFile (QIODevice *)
Construct a new QTgaFile object getting data from device.
QImage readImage ()
Reads an image file from the QTgaFile's device, and returns it.
QSize size () const
int width () const
int xOffset () const
int yOffset () const
~QTgaFile ()
Destroy the device, recovering any resources.
Static Private Functions
static quint16 littleEndianInt (const unsigned char *d)
Returns the integer encoded in the two little endian bytes at d.
Properties
QIODevice * mDevice
QString mErrorMessage
unsigned char mHeader [HeaderSize]
Detailed Description
Since
4.8
Warning
This function is not part of the public interface.
File data container for a TrueVision Graphics format file.
Format is as described here: http://local.wasp.uwa.edu.au/~pbourke/dataformats/tga/ http://netghost.narod.ru/gff2/graphics/summary/tga.htm
Usage is:
QTgaFile tga(myFile);
QImage tgaImage;
if (tga.isValid())
    tgaImage = tga.readImage();
The class is designed to handle sequential and non-sequential sources, so during construction the mHeader is read. Then during the readImage() call the rest of the data is read.
After passing myFile to the constructor, if the QIODevice *myFile is read, or has seek() called, the results are undefined - so don't do that.
Definition at line 52 of file qtgafile.h.
Enumerations
Compression
enum QTgaFile::Compression
Enumerator
NoCompression
RleCompression
Definition at line 55 of file qtgafile.h.
                      {
         NoCompression = 0,
         RleCompression = 1
     };
FooterOffset
enum QTgaFile::FooterOffset
Enumerator
ExtensionOffset
DeveloperOffset
SignatureOffset
FooterSize
Definition at line 76 of file qtgafile.h.
                       {
         ExtensionOffset = 0,
         DeveloperOffset = 4,
         SignatureOffset = 8,
         FooterSize = 26
     };
HeaderOffset
enum QTgaFile::HeaderOffset
Enumerator
IdLength
ColorMapType
ImageType
CMapStart
CMapLength
CMapDepth
XOffset
YOffset
Width
Height
PixelDepth
ImageDescriptor
HeaderSize
Definition at line 60 of file qtgafile.h.
                       {
         IdLength = 0,          /* 00h  Size of Image ID field */
         ColorMapType = 1,      /* 01h  Color map type */
         ImageType = 2,         /* 02h  Image type code */
         CMapStart = 3,         /* 03h  Color map origin */
         CMapLength = 5,        /* 05h  Color map length */
         CMapDepth = 7,         /* 07h  Depth of color map entries */
         XOffset = 8,           /* 08h  X origin of image */
         YOffset = 10,          /* 0Ah  Y origin of image */
         Width = 12,            /* 0Ch  Width of image */
         Height = 14,           /* 0Eh  Height of image */
         PixelDepth = 16,       /* 10h  Image pixel size */
         ImageDescriptor = 17,  /* 11h  Image descriptor byte */
         HeaderSize = 18
     };
Constructors and Destructors
QTgaFile()
QTgaFile::QTgaFile (QIODevice * device)
Construct a new QTgaFile object getting data from device.
The object does not take ownership of the device, but until the object is destroyed do not do any non-const operations, eg seek or read on the device.
Definition at line 130 of file qtgafile.cpp.
     : mDevice(device)
 {
     ::memset(mHeader, 0, HeaderSize);
     if (!mDevice->isReadable())
     {
         mErrorMessage = QObject::tr("Could not read image data");
         return;
     }
     if (mDevice->isSequential())
     {
         mErrorMessage = QObject::tr("Sequential device (eg socket) for image read not supported");
         return;
     }
     if (!mDevice->seek(0))
     {
         mErrorMessage = QObject::tr("Seek file/device for image read failed");
         return;
     }
     int bytes = device->read((char*)mHeader, HeaderSize);
     if (bytes != HeaderSize)
     {
         mErrorMessage = QObject::tr("Image mHeader read failed");
         device->seek(0);
         return;
     }
     if (mHeader[ImageType] != 2)
     {
         // TODO: should support other image types
         mErrorMessage = QObject::tr("Image type not supported");
         device->seek(0);
         return;
     }
     int bitsPerPixel = mHeader[PixelDepth];
     bool validDepth = (bitsPerPixel == 16 || bitsPerPixel == 24 || bitsPerPixel == 32);
     if (!validDepth)
     {
         mErrorMessage = QObject::tr("Image depth not valid");
     }
     int fileBytes = mDevice->size();
     if (!mDevice->seek(fileBytes - FooterSize))
     {
         mErrorMessage = QObject::tr("Could not seek to image read footer");
         device->seek(0);
         return;
     }
     char footer[FooterSize];
     bytes = mDevice->read((char*)footer, FooterSize);
     if (bytes != FooterSize)
     {
         mErrorMessage = QObject::tr("Could not read footer");
     }
     if (qstrncmp(&footer[SignatureOffset], "TRUEVISION-XFILE", 16) != 0)
     {
         mErrorMessage = QObject::tr("Image type (non-TrueVision 2.0) not supported");
     }
     if (!mDevice->seek(0))
     {
         mErrorMessage = QObject::tr("Could not reset to start position");
     }
 }
~QTgaFile()
QTgaFile::~QTgaFile ()
Destroy the device, recovering any resources.
Warning
This function is not part of the public interface.
Definition at line 199 of file qtgafile.cpp.
 {
 }
Functions
compression()
QTgaFile::Compression QTgaFile::compression () const inline
Definition at line 151 of file qtgafile.h.
Referenced by QTgaHandler::option().
 {
     // TODO: for now, only handle type 2 files, with no color table
     // and no compression
     return NoCompression;
 }
errorMessage()
QString QTgaFile::errorMessage () const inline
Definition at line 109 of file qtgafile.h.
 {
     return mErrorMessage;
 }
height()
int QTgaFile::height () const inline
Definition at line 141 of file qtgafile.h.
Referenced by readImage(), and size().
 {
     return littleEndianInt(&mHeader[Height]);
 }
isValid()
bool QTgaFile::isValid () const inline
Definition at line 104 of file qtgafile.h.
Referenced by QTgaHandler::canRead(), and readImage().
 {
     return mErrorMessage.isEmpty();
 }
littleEndianInt()
quint16 QTgaFile::littleEndianInt (const unsigned char * d) inline static private
Returns the integer encoded in the two little endian bytes at d.
Warning
This function is not part of the public interface.
Definition at line 121 of file qtgafile.h.
Referenced by height(), readImage(), width(), xOffset(), and yOffset().
 {
     return d[0] + d[1] * 256;
 }
readImage()
QImage QTgaFile::readImage ()
Reads an image file from the QTgaFile's device, and returns it.
Warning
This function is not part of the public interface.
This method seeks to the absolute position of the image data in the file, so no assumptions are made about where the devices read pointer is when this method is called. For this reason only random access devices are supported.
If the constructor completed successfully, such that isValid() returns true, then this method is likely to succeed, unless the file is somehow corrupted.
In the case that the read fails, the QImage returned will be null, such that QImage::isNull() will be true.
Definition at line 220 of file qtgafile.cpp.
Referenced by QTgaHandler::read().
 {
     if (!isValid())
         return QImage();
     int offset = mHeader[IdLength];  // Mostly always zero
     // Even in TrueColor files a color pallette may be present
     if (mHeader[ColorMapType] == 1)
         offset += littleEndianInt(&mHeader[CMapLength]) * littleEndianInt(&mHeader[CMapDepth]);
     mDevice->seek(HeaderSize + offset);
     char dummy;
     for (int i = 0; i < offset; ++i)
         mDevice->getChar(&dummy);
     int bitsPerPixel = mHeader[PixelDepth];
     int imageWidth = width();
     int imageHeight = height();
     unsigned char desc = mHeader[ImageDescriptor];
     //unsigned char xCorner = desc & 0x10; // 0 = left, 1 = right
     unsigned char yCorner = desc & 0x20; // 0 = lower, 1 = upper
     QImage im(imageWidth, imageHeight, QImage::Format_ARGB32);
     TgaReader *reader = 0;
     if (bitsPerPixel == 16)
         reader = new Tga16Reader();
     else if (bitsPerPixel == 24)
         reader = new Tga24Reader();
     else if (bitsPerPixel == 32)
         reader = new Tga32Reader();
     TgaReader &read = *reader;
     // For now only deal with yCorner, since no one uses xCorner == 1
     // Also this is upside down, since Qt has the origin flipped
     if (yCorner)
     {
         for (int y = 0; y < imageHeight; ++y)
             for (int x = 0; x < imageWidth; ++x)
                 im.setPixel(x, y, read(mDevice));
     }
     else
     {
         for (int y = imageHeight - 1; y >= 0; --y)
             for (int x = 0; x < imageWidth; ++x)
                 im.setPixel(x, y, read(mDevice));
     }
     delete reader;
     // TODO: add processing of TGA extension information - ie TGA 2.0 files
     return im;
 }
size()
QSize QTgaFile::size () const inline
Definition at line 146 of file qtgafile.h.
Referenced by QTgaHandler::option().
 {
     return QSize(width(), height());
 }
width()
int QTgaFile::width () const inline
Definition at line 136 of file qtgafile.h.
Referenced by readImage(), and size().
 {
     return littleEndianInt(&mHeader[Width]);
 }
xOffset()
int QTgaFile::xOffset () const inline
Definition at line 126 of file qtgafile.h.
 {
     return littleEndianInt(&mHeader[XOffset]);
 }
yOffset()
int QTgaFile::yOffset () const inline
Definition at line 131 of file qtgafile.h.
 {
     return littleEndianInt(&mHeader[YOffset]);
 }
Properties
mDevice
QIODevice* QTgaFile::mDevice private
Definition at line 101 of file qtgafile.h.
Referenced by QTgaFile(), and readImage().
mErrorMessage
QString QTgaFile::mErrorMessage private
Definition at line 99 of file qtgafile.h.
Referenced by errorMessage(), isValid(), and QTgaFile().
mHeader
unsigned char QTgaFile::mHeader[HeaderSize] private
Definition at line 100 of file qtgafile.h.
Referenced by height(), QTgaFile(), readImage(), width(), xOffset(), and yOffset().
The documentation for this class was generated from the following files:
/src/plugins/imageformats/tga/qtgafile.h
/src/plugins/imageformats/tga/qtgafile.cpp