Qt 4.8: QVertexIndexVector Class Reference
QVertexIndexVector Class Reference
#include <qtriangulator_p.h>
Public Types
enum Type { UnsignedInt, UnsignedShort }
Public Functions
const void * data () const
QVertexIndexVector & operator= (const QVertexIndexVector &other)
void setDataUint (const QVector< quint32 > &data)
void setDataUshort (const QVector< quint16 > &data)
int size () const
Type type () const
Properties
QVector< quint16 > indices16
QVector< quint32 > indices32
Type t
Detailed Description
Definition at line 61 of file qtriangulator_p.h.
Enumerations
Type
enum QVertexIndexVector::Type
Enumerator
UnsignedInt
UnsignedShort
Definition at line 64 of file qtriangulator_p.h.
               {
         UnsignedInt,
         UnsignedShort
     };
Functions
data()
const void* QVertexIndexVector::data () const inline
Definition at line 83 of file qtriangulator_p.h.
Referenced by QGL2PaintEngineExPrivate::fill(), setDataUint(), and setDataUshort().
     {
         if (t == UnsignedInt)
             return indices32.data();
         return indices16.data();
     }
operator=()
QVertexIndexVector& QVertexIndexVector::operator= (const QVertexIndexVector & other) inline
Definition at line 97 of file qtriangulator_p.h.
     {
          if (t == UnsignedInt)
            indices32 = other.indices32;
          else
            indices16 = other.indices16;
          return *this;
     }
setDataUint()
void QVertexIndexVector::setDataUint (const QVector< quint32 > & data) inline
Definition at line 71 of file qtriangulator_p.h.
Referenced by qPolyline(), and qTriangulate().
     {
         t = UnsignedInt;
         indices32 = data;
     }
setDataUshort()
void QVertexIndexVector::setDataUshort (const QVector< quint16 > & data) inline
Definition at line 77 of file qtriangulator_p.h.
Referenced by qPolyline(), and qTriangulate().
     {
         t = UnsignedShort;
         indices16 = data;
     }
size()
int QVertexIndexVector::size () const inline
Definition at line 90 of file qtriangulator_p.h.
Referenced by QGL2PaintEngineExPrivate::fill().
     {
         if (t == UnsignedInt)
             return indices32.size();
         return indices16.size();
     }
type()
Type QVertexIndexVector::type () const inline
Definition at line 69 of file qtriangulator_p.h.
 { return t; }
Properties
indices16
QVector<quint16> QVertexIndexVector::indices16 private
Definition at line 111 of file qtriangulator_p.h.
Referenced by data(), operator=(), setDataUshort(), and size().
indices32
QVector<quint32> QVertexIndexVector::indices32 private
Definition at line 110 of file qtriangulator_p.h.
Referenced by data(), operator=(), setDataUint(), and size().
t
Type QVertexIndexVector::t private
Definition at line 109 of file qtriangulator_p.h.
Referenced by data(), operator=(), setDataUint(), setDataUshort(), size(), and type().
The documentation for this class was generated from the following file:
/src/opengl/gl2paintengineex/qtriangulator_p.h