Qt 4.8: QScriptDebuggerWidgetFactoryInterface Class Reference
QScriptDebuggerWidgetFactoryInterface Class Reference abstract
#include <qscriptdebuggerwidgetfactoryinterface_p.h>
Public Functions
virtual QScriptBreakpointsWidgetInterface * createBreakpointsWidget ()=0
virtual QScriptDebuggerCodeFinderWidgetInterface * createCodeFinderWidget ()=0
virtual QScriptDebuggerCodeWidgetInterface * createCodeWidget ()=0
virtual QScriptDebuggerConsoleWidgetInterface * createConsoleWidget ()=0
virtual QScriptDebugOutputWidgetInterface * createDebugOutputWidget ()=0
virtual QScriptErrorLogWidgetInterface * createErrorLogWidget ()=0
virtual QScriptDebuggerLocalsWidgetInterface * createLocalsWidget ()=0
virtual QScriptDebuggerScriptsWidgetInterface * createScriptsWidget ()=0
virtual QScriptDebuggerStackWidgetInterface * createStackWidget ()=0
virtual ~QScriptDebuggerWidgetFactoryInterface ()
Detailed Description
Definition at line 70 of file qscriptdebuggerwidgetfactoryinterface_p.h.
Constructors and Destructors
~QScriptDebuggerWidgetFactoryInterface()
virtual QScriptDebuggerWidgetFactoryInterface::~QScriptDebuggerWidgetFactoryInterface () inline virtual
Definition at line 73 of file qscriptdebuggerwidgetfactoryinterface_p.h.
 {}
Functions
createBreakpointsWidget()
virtual QScriptBreakpointsWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createBreakpointsWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebugger::widget().
createCodeFinderWidget()
virtual QScriptDebuggerCodeFinderWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createCodeFinderWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebuggerPrivate::_q_findInScript(), and QScriptDebugger::widget().
createCodeWidget()
virtual QScriptDebuggerCodeWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createCodeWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebugger::widget().
createConsoleWidget()
virtual QScriptDebuggerConsoleWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createConsoleWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebuggerPrivate::debuggerEvent(), and QScriptDebugger::widget().
createDebugOutputWidget()
virtual QScriptDebugOutputWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createDebugOutputWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebuggerPrivate::debuggerEvent(), and QScriptDebugger::widget().
createErrorLogWidget()
virtual QScriptErrorLogWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createErrorLogWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebuggerPrivate::debuggerEvent(), and QScriptDebugger::widget().
createLocalsWidget()
virtual QScriptDebuggerLocalsWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createLocalsWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebugger::widget().
createScriptsWidget()
virtual QScriptDebuggerScriptsWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createScriptsWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebugger::widget().
createStackWidget()
virtual QScriptDebuggerStackWidgetInterface* QScriptDebuggerWidgetFactoryInterface::createStackWidget () pure virtual
Implemented in QScriptDebuggerStandardWidgetFactory.
Referenced by QScriptDebugger::widget().
The documentation for this class was generated from the following file:
/src/scripttools/debugging/qscriptdebuggerwidgetfactoryinterface_p.h