Qt 4.8: QInputDialogPrivate Class Reference
QInputDialogPrivate Class Reference
Public Functions
void _q_currentRowChanged (const QModelIndex &newIndex, const QModelIndex &oldIndex)
void _q_textChanged (const QString &text)
void chooseRightTextInputWidget ()
void ensureComboBox ()
void ensureDoubleSpinBox ()
void ensureEnabledConnection (QAbstractSpinBox *spinBox)
void ensureIntSpinBox ()
void ensureLayout ()
void ensureLayout () const
void ensureLineEdit ()
void ensureListView ()
QString listViewText () const
QInputDialogPrivate ()
void setComboBoxText (const QString &text)
void setInputWidget (QWidget *widget)
void setListViewText (const QString &text)
bool useComboBoxOrListView () const
Public Functions inherited from QDialogPrivate
void hideDefault ()
Hides the default button indicator.
virtual void mac_nativeDialogModalHelp ()
QDialogPrivate ()
void resetModalitySetByOpen ()
void setDefault (QPushButton *)
This function is called by the push button pushButton when it becomes the default button.
void setMainDefault (QPushButton *)
This function sets the default default push button to pushButton.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QDialogButtonBox * buttonBox
QComboBox * comboBox
QDoubleSpinBox * doubleSpinBox
QWidget * inputWidget
QSpinBox * intSpinBox
QLabel * label
QLineEdit * lineEdit
QListView * listView
QVBoxLayout * mainLayout
QByteArray memberToDisconnectOnClose
QInputDialog::InputDialogOptions opts
QPointer< QObject > receiverToDisconnectOnClose
QString textValue
Public Variables inherited from QDialogPrivate
bool doShowExtension
QPointer< QEventLoop > eventLoop
QWidget * extension
QPoint lastRMBPress
QPointer< QPushButton > mainDef
QSize max
QSize min
Qt::Orientation orientation
int rescode
int resetModalityTo
QSizeGrip * resizer
QSize size
bool sizeGripEnabled
bool wasModalitySet
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 165 of file qinputdialog.cpp.
Constructors and Destructors
QInputDialogPrivate()
QInputDialogPrivate::QInputDialogPrivate ()
Definition at line 204 of file qinputdialog.cpp.
     : label(0), buttonBox(0), lineEdit(0), intSpinBox(0), doubleSpinBox(0), comboBox(0), listView(0),
       inputWidget(0), mainLayout(0)
 {
 }
Functions
_q_currentRowChanged()
void QInputDialogPrivate::_q_currentRowChanged (const QModelIndex & newIndex, const QModelIndex & oldIndex)
Definition at line 428 of file qinputdialog.cpp.
Referenced by ensureListView().
 {
     _q_textChanged(comboBox->model()->data(newIndex).toString());
     buttonBox->button(QDialogButtonBox::Ok)->setEnabled(true);
 }
_q_textChanged()
void QInputDialogPrivate::_q_textChanged (const QString & text)
Definition at line 419 of file qinputdialog.cpp.
Referenced by _q_currentRowChanged(), chooseRightTextInputWidget(), ensureComboBox(), and ensureLineEdit().
 {
     Q_Q(QInputDialog);
     if (textValue != text) {
         textValue = text;
         emit q->textValueChanged(text);
     }
 }
chooseRightTextInputWidget()
void QInputDialogPrivate::chooseRightTextInputWidget ()
Definition at line 364 of file qinputdialog.cpp.
 {
     QWidget *widget;
     if (useComboBoxOrListView()) {
         if ((opts & QInputDialog::UseListViewForComboBoxItems) && !comboBox->isEditable()) {
             ensureListView();
             widget = listView;
         } else {
             widget = comboBox;
         }
     } else {
         ensureLineEdit();
         widget = lineEdit;
     }
     setInputWidget(widget);
     if (inputWidget == comboBox) {
         _q_textChanged(comboBox->currentText());
     } else if (inputWidget == listView) {
         _q_textChanged(listViewText());
     }
 }
ensureComboBox()
void QInputDialogPrivate::ensureComboBox ()
Definition at line 261 of file qinputdialog.cpp.
Referenced by ensureListView().
 {
     Q_Q(QInputDialog);
     if (!comboBox) {
         comboBox = new QComboBox(q);
 #ifndef QT_NO_IM
         qt_widget_private(comboBox)->inheritsInputMethodHints = 1;
 #endif
         comboBox->hide();
         QObject::connect(comboBox, SIGNAL(editTextChanged(QString)),
                          q, SLOT(_q_textChanged(QString)));
         QObject::connect(comboBox, SIGNAL(currentIndexChanged(QString)),
                          q, SLOT(_q_textChanged(QString)));
     }
 }
ensureDoubleSpinBox()
void QInputDialogPrivate::ensureDoubleSpinBox ()
Definition at line 306 of file qinputdialog.cpp.
 {
     Q_Q(QInputDialog);
     if (!doubleSpinBox) {
         doubleSpinBox = new QInputDialogDoubleSpinBox(q);
         doubleSpinBox->hide();
         QObject::connect(doubleSpinBox, SIGNAL(valueChanged(double)),
                          q, SIGNAL(doubleValueChanged(double)));
     }
 }
ensureEnabledConnection()
void QInputDialogPrivate::ensureEnabledConnection (QAbstractSpinBox * spinBox)
Definition at line 317 of file qinputdialog.cpp.
Referenced by ensureLayout(), and setInputWidget().
 {
     if (spinBox) {
         QAbstractButton *okButton = buttonBox->button(QDialogButtonBox::Ok);
         QObject::connect(spinBox, SIGNAL(textChanged(bool)), okButton, SLOT(setEnabled(bool)), Qt::UniqueConnection);
     }
 }
ensureIntSpinBox()
void QInputDialogPrivate::ensureIntSpinBox ()
Definition at line 295 of file qinputdialog.cpp.
 {
     Q_Q(QInputDialog);
     if (!intSpinBox) {
         intSpinBox = new QInputDialogSpinBox(q);
         intSpinBox->hide();
         QObject::connect(intSpinBox, SIGNAL(valueChanged(int)),
                          q, SIGNAL(intValueChanged(int)));
     }
 }
ensureLayout() [1/2]
void QInputDialogPrivate::ensureLayout ()
Definition at line 210 of file qinputdialog.cpp.
Referenced by setInputWidget().
 {
     Q_Q(QInputDialog);
     if (mainLayout)
         return;
     if (!inputWidget) {
         ensureLineEdit();
         inputWidget = lineEdit;
     }
     if (!label)
         label = new QLabel(QInputDialog::tr("Enter a value:"), q);
 #ifndef QT_NO_SHORTCUT
     label->setBuddy(inputWidget);
 #endif
     label->setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Fixed);
     buttonBox = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel, Qt::Horizontal, q);
     QObject::connect(buttonBox, SIGNAL(accepted()), q, SLOT(accept()));
     QObject::connect(buttonBox, SIGNAL(rejected()), q, SLOT(reject()));
     mainLayout = new QVBoxLayout(q);
     //we want to let the input dialog grow to available size on Symbian.
 #ifndef Q_OS_SYMBIAN
     mainLayout->setSizeConstraint(QLayout::SetMinAndMaxSize);
 #else
     label->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
 #endif
     mainLayout->addWidget(label);
     mainLayout->addWidget(inputWidget);
     mainLayout->addWidget(buttonBox);
     ensureEnabledConnection(qobject_cast<QAbstractSpinBox *>(inputWidget));
     inputWidget->show();
 }
ensureLayout() [2/2]
void QInputDialogPrivate::ensureLayout () const inline
Definition at line 184 of file qinputdialog.cpp.
Referenced by ensureLayout().
 { const_cast<QInputDialogPrivate *>(this)->ensureLayout(); }
ensureLineEdit()
void QInputDialogPrivate::ensureLineEdit ()
Definition at line 247 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget(), and ensureLayout().
 {
     Q_Q(QInputDialog);
     if (!lineEdit) {
         lineEdit = new QLineEdit(q);
 #ifndef QT_NO_IM
         qt_widget_private(lineEdit)->inheritsInputMethodHints = 1;
 #endif
         lineEdit->hide();
         QObject::connect(lineEdit, SIGNAL(textChanged(QString)),
                          q, SLOT(_q_textChanged(QString)));
     }
 }
ensureListView()
void QInputDialogPrivate::ensureListView ()
Definition at line 277 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget().
 {
     Q_Q(QInputDialog);
     if (!listView) {
         ensureComboBox();
         listView = new QListView(q);
         listView->hide();
         listView->setEditTriggers(QAbstractItemView::NoEditTriggers);
         listView->setSelectionMode(QAbstractItemView::SingleSelection);
         listView->setModel(comboBox->model());
         listView->setCurrentIndex(QModelIndex()); // ###
         QObject::connect(listView->selectionModel(),
                          SIGNAL(currentRowChanged(QModelIndex,QModelIndex)),
                          q, SLOT(_q_currentRowChanged(QModelIndex,QModelIndex)));
     }
 }
listViewText()
QString QInputDialogPrivate::listViewText () const
Definition at line 409 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget().
 {
     if (listView->selectionModel()->hasSelection()) {
         int row = listView->selectionModel()->selectedRows().value(0).row();
         return comboBox->itemText(row);
     } else {
         return QString();
     }
 }
setComboBoxText()
void QInputDialogPrivate::setComboBoxText (const QString & text)
Definition at line 389 of file qinputdialog.cpp.
Referenced by setInputWidget().
 {
     int index = comboBox->findText(text);
     if (index != -1) {
         comboBox->setCurrentIndex(index);
     } else if (comboBox->isEditable()) {
         comboBox->setEditText(text);
     }
 }
setInputWidget()
void QInputDialogPrivate::setInputWidget (QWidget * widget)
Definition at line 325 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget().
 {
     Q_ASSERT(widget);
     if (inputWidget == widget)
         return;
     if (mainLayout) {
         Q_ASSERT(inputWidget);
         mainLayout->removeWidget(inputWidget);
         inputWidget->hide();
         mainLayout->insertWidget(1, widget);
         widget->show();
         // disconnect old input widget
         QAbstractButton *okButton = buttonBox->button(QDialogButtonBox::Ok);
         if (QAbstractSpinBox *spinBox = qobject_cast<QAbstractSpinBox *>(inputWidget))
             QObject::disconnect(spinBox, SIGNAL(textChanged(bool)), okButton, SLOT(setEnabled(bool)));
         // connect new input widget and update enabled state of OK button
         QAbstractSpinBox *spinBox = qobject_cast<QAbstractSpinBox *>(widget);
         ensureEnabledConnection(spinBox);
         okButton->setEnabled(!spinBox || spinBox->hasAcceptableInput());
     }
     inputWidget = widget;
     // synchronize the text shown in the new text editor with the current
     // textValue
     if (widget == lineEdit) {
         lineEdit->setText(textValue);
     } else if (widget == comboBox) {
         setComboBoxText(textValue);
     } else if (widget == listView) {
         setListViewText(textValue);
         ensureLayout();
         buttonBox->button(QDialogButtonBox::Ok)->setEnabled(listView->selectionModel()->hasSelection());
     }
 }
setListViewText()
void QInputDialogPrivate::setListViewText (const QString & text)
Definition at line 399 of file qinputdialog.cpp.
Referenced by setInputWidget().
 {
     int row = comboBox->findText(text);
     if (row != -1) {
         QModelIndex index(comboBox->model()->index(row, 0));
         listView->selectionModel()->setCurrentIndex(index, QItemSelectionModel::Clear
                                                          | QItemSelectionModel::SelectCurrent);
     }
 }
useComboBoxOrListView()
bool QInputDialogPrivate::useComboBoxOrListView () const inline
Definition at line 185 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget().
 { return comboBox && comboBox->count() > 0; }
Properties
buttonBox
QDialogButtonBox* QInputDialogPrivate::buttonBox mutable
Definition at line 190 of file qinputdialog.cpp.
Referenced by _q_currentRowChanged(), ensureEnabledConnection(), ensureLayout(), and setInputWidget().
comboBox
QComboBox* QInputDialogPrivate::comboBox mutable
Definition at line 194 of file qinputdialog.cpp.
Referenced by _q_currentRowChanged(), chooseRightTextInputWidget(), ensureComboBox(), ensureListView(), listViewText(), setComboBoxText(), setInputWidget(), and setListViewText().
doubleSpinBox
QDoubleSpinBox* QInputDialogPrivate::doubleSpinBox mutable
Definition at line 193 of file qinputdialog.cpp.
Referenced by ensureDoubleSpinBox().
inputWidget
QWidget* QInputDialogPrivate::inputWidget mutable
Definition at line 196 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget(), ensureLayout(), and setInputWidget().
intSpinBox
QSpinBox* QInputDialogPrivate::intSpinBox mutable
Definition at line 192 of file qinputdialog.cpp.
Referenced by ensureIntSpinBox().
label
QLabel* QInputDialogPrivate::label mutable
Definition at line 189 of file qinputdialog.cpp.
Referenced by ensureLayout().
lineEdit
QLineEdit* QInputDialogPrivate::lineEdit mutable
Definition at line 191 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget(), ensureLayout(), ensureLineEdit(), and setInputWidget().
listView
QListView* QInputDialogPrivate::listView mutable
Definition at line 195 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget(), ensureListView(), listViewText(), setInputWidget(), and setListViewText().
mainLayout
QVBoxLayout* QInputDialogPrivate::mainLayout mutable
Definition at line 197 of file qinputdialog.cpp.
Referenced by ensureLayout(), and setInputWidget().
memberToDisconnectOnClose
QByteArray QInputDialogPrivate::memberToDisconnectOnClose
Definition at line 201 of file qinputdialog.cpp.
opts
QInputDialog::InputDialogOptions QInputDialogPrivate::opts
Definition at line 198 of file qinputdialog.cpp.
Referenced by chooseRightTextInputWidget().
receiverToDisconnectOnClose
QPointer<QObject> QInputDialogPrivate::receiverToDisconnectOnClose
Definition at line 200 of file qinputdialog.cpp.
textValue
QString QInputDialogPrivate::textValue
Definition at line 199 of file qinputdialog.cpp.
Referenced by _q_textChanged(), and setInputWidget().
The documentation for this class was generated from the following file:
/src/gui/dialogs/qinputdialog.cpp