Qt 4.8: QVariantAnimation Class Reference
QVariantAnimation Class Reference abstract
The QVariantAnimation class provides an abstract base class for animations.
#include <qvariantanimation.h>
Public Types
typedef QVariant(* Interpolator) (const void *from, const void *to, qreal progress)
typedef QPair< qreal, QVariant > KeyValue
This is a typedef for QPair<qreal, QVariant>.
typedef QVector< KeyValue > KeyValues
This is a typedef for QVector<KeyValue>
Public Types inherited from QAbstractAnimation
enum DeletionPolicy { KeepWhenStopped = 0, DeleteWhenStopped }
enum Direction { Forward, Backward }
This enum describes the direction of the animation when in Running state.
enum State { Stopped, Paused, Running }
This enum describes the state of the animation.
Signals
void valueChanged (const QVariant &value)
QVariantAnimation emits this signal whenever the current value changes.
Signals inherited from QAbstractAnimation
void currentLoopChanged (int currentLoop)
QAbstractAnimation emits this signal whenever the current loop changes.
void directionChanged (QAbstractAnimation::Direction)
QAbstractAnimation emits this signal whenever the direction has been changed.
void finished ()
QAbstractAnimation emits this signal after the animation has stopped and has reached the end.
void stateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
QAbstractAnimation emits this signal whenever the state of the animation has changed from oldState to newState.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QVariant currentValue () const
int duration () const
QEasingCurve easingCurve () const
QVariant endValue () const
QVariant keyValueAt (qreal step) const
Returns the key frame value for the given step.
KeyValues keyValues () const
Returns the key frames of this animation.
QVariantAnimation (QObject *parent=0)
Construct a QVariantAnimation object.
void setDuration (int msecs)
void setEasingCurve (const QEasingCurve &easing)
void setEndValue (const QVariant &value)
void setKeyValueAt (qreal step, const QVariant &value)
Creates a key frame at the given step with the given value.
void setKeyValues (const KeyValues &values)
Replaces the current set of key frames with the given keyValues.
void setStartValue (const QVariant &value)
QVariant startValue () const
~QVariantAnimation ()
Destroys the animation.
Public Functions inherited from QAbstractAnimation
int currentLoop () const
int currentLoopTime () const
Returns the current time inside the current loop.
int currentTime () const
Direction direction () const
QAnimationGroup * group () const
If this animation is part of a QAnimationGroup, this function returns a pointer to the group; otherwise, it returns 0.
int loopCount () const
QAbstractAnimation (QObject *parent=0)
Constructs the QAbstractAnimation base class, and passes parent to QObject's constructor.
void setDirection (Direction direction)
void setLoopCount (int loopCount)
State state () const
int totalDuration () const
Returns the total and effective duration of the animation, including the loop count.
virtual ~QAbstractAnimation ()
Stops the animation if it's running, then destroys the QAbstractAnimation.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *event)
Reimplemented Function
virtual QVariant interpolated (const QVariant &from, const QVariant &to, qreal progress) const
This virtual function returns the linear interpolation between variants from and to, at progress, usually a value between 0 and 1.
QVariantAnimation (QVariantAnimationPrivate &dd, QObject *parent=0)
void updateCurrentTime (int)
Reimplemented Function
virtual void updateCurrentValue (const QVariant &value)=0
This pure virtual function is called every time the animation's current value changes.
void updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
Reimplemented Function
Protected Functions inherited from QAbstractAnimation
QAbstractAnimation (QAbstractAnimationPrivate &dd, QObject *parent=0)
virtual void updateDirection (QAbstractAnimation::Direction direction)
This virtual function is called by QAbstractAnimation when the direction of the animation is changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Private Functions
static void registerInterpolator (Interpolator func, int interpolationType)
Properties
QVariant currentValue
the current value of the animation.
int duration
the duration of the animation
QEasingCurve easingCurve
the easing curve of the animation
QVariant endValue
the end value of the animation
QVariant startValue
the optional start value of the animation
Friends
template<typename T >
void qRegisterAnimationInterpolator (QVariant(*func)(const T &, const T &, qreal))
Related Functions
(Note that these are not member functions.)
void qRegisterAnimationInterpolator (QVariant(*func)(const T &from, const T &to, qreal progress))
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Additional Inherited Members
Public Slots inherited from QAbstractAnimation
void pause ()
Pauses the animation.
void resume ()
Resumes the animation after it was paused.
void setCurrentTime (int msecs)
void setPaused (bool)
If paused is true, the animation is paused.
void start (QAbstractAnimation::DeletionPolicy policy=KeepWhenStopped)
Starts the animation.
void stop ()
Stops the animation.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Detailed Description
The QVariantAnimation class provides an abstract base class for animations.
Since
4.6
This class is part of The Animation Framework. It serves as a base class for property and item animations, with functions for shared functionality.
QVariantAnimation cannot be used directly as it is an abstract class; it has a pure virtual method called updateCurrentValue(). The class performs interpolation over QVariant, but leaves using the interpolated values to its subclasses. Currently, Qt provides QPropertyAnimation, which animates Qt Qt's Property System{properties}. See the QPropertyAnimation class description if you wish to animate such properties.
You can then set start and end values for the property by calling setStartValue() and setEndValue(), and finally call start() to start the animation. QVariantAnimation will interpolate the property of the target object and emit valueChanged(). To react to a change in the current value you have to reimplement the updateCurrentValue() virtual function.
It is also possible to set values at specified steps situated between the start and end value. The interpolation will then touch these points at the specified steps. Note that the start and end values are defined as the key values at 0.0 and 1.0.
There are two ways to affect how QVariantAnimation interpolates the values. You can set an easing curve by calling setEasingCurve(), and configure the duration by calling setDuration(). You can change how the QVariants are interpolated by creating a subclass of QVariantAnimation, and reimplementing the virtual interpolated() function.
Subclassing QVariantAnimation can be an alternative if you have QVariant that you do not wish to declare as Qt properties. Note, however, that you in most cases will be better off declaring your QVariant as a property.
Not all QVariant types are supported. Below is a list of currently supported QVariant types:
QMetaType::Int
QMetaType::UInt
QMetaType::Double
QMetaType::Float
QMetaType::QLine
QMetaType::QLineF
QMetaType::QPoint
QMetaType::QPointF
QMetaType::QSize
QMetaType::QSizeF
QMetaType::QRect
QMetaType::QRectF
QMetaType::QColor
If you need to interpolate other variant types, including custom types, you have to implement interpolation for these yourself. To do this, you can register an interpolator function for a given type. This function takes 3 parameters: the start value, the end value and the current progress.
Example:
QVariant myColorInterpolator(const QColor &start, const QColor &end, qreal progress)
{
    ...
    return QColor(...);
}
...
qRegisterAnimationInterpolator<QColor>(myColorInterpolator);
Another option is to reimplement interpolated(), which returns interpolation values for the value being interpolated.
Warning
This function is not part of the public interface. We need some snippets around here.
See also
QPropertyAnimation, QAbstractAnimation, {The Animation Framework}
Definition at line 60 of file qvariantanimation.h.
Typedefs
Interpolator
QVariantAnimation::Interpolator
Warning
This function is not part of the public interface.
This is a typedef for a pointer to a function with the following signature:
QVariant myInterpolator(const QVariant &from, const QVariant &to, qreal progress);
Definition at line 96 of file qvariantanimation.h.
KeyValue
QVariantAnimation::KeyValue
This is a typedef for QPair<qreal, QVariant>.
Definition at line 70 of file qvariantanimation.h.
KeyValues
QVariantAnimation::KeyValues
This is a typedef for QVector<KeyValue>
Definition at line 71 of file qvariantanimation.h.
Constructors and Destructors
QVariantAnimation() [1/2]
QVariantAnimation::QVariantAnimation (QObject * parent = 0)
Construct a QVariantAnimation object.
parent is passed to QAbstractAnimation's constructor.
Definition at line 361 of file qvariantanimation.cpp.
                                                     : QAbstractAnimation(*new QVariantAnimationPrivate, parent)
 {
 }
~QVariantAnimation()
QVariantAnimation::~QVariantAnimation ()
Destroys the animation.
Definition at line 375 of file qvariantanimation.cpp.
 {
 }
QVariantAnimation() [2/2]
QVariantAnimation::QVariantAnimation (QVariantAnimationPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 368 of file qvariantanimation.cpp.
                                                                                   : QAbstractAnimation(dd, parent)
 {
 }
Functions
currentValue()
QVariant QVariantAnimation::currentValue () const
Referenced by setKeyValues().
duration()
int QVariantAnimation::duration () const virtual
Implements QAbstractAnimation.
Referenced by QVariantAnimationPrivate::getInterpolator(), and QTabBarPrivate::Tab::startAnimation().
easingCurve()
QEasingCurve QVariantAnimation::easingCurve () const
Referenced by ~QVariantAnimation().
endValue()
QVariant QVariantAnimation::endValue () const
Referenced by QStateMachinePrivate::initializeAnimation(), setStartValue(), and QPropertyAnimation::updateState().
event()
bool QVariantAnimation::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractAnimation.
Definition at line 682 of file qvariantanimation.cpp.
Referenced by QPropertyAnimation::event(), and CloseButton::minimumSizeHint().
 {
     return QAbstractAnimation::event(event);
 }
interpolated()
QVariant QVariantAnimation::interpolated (const QVariant & from, const QVariant & to, qreal progress) const protected virtual
This virtual function returns the linear interpolation between variants from and to, at progress, usually a value between 0 and 1.
You can reimplement this function in a subclass of QVariantAnimation to provide your own interpolation algorithm.
Note that in order for the interpolation to work with a QEasingCurve that return a value smaller than 0 or larger than 1 (such as QEasingCurve::InBack) you should make sure that it can extrapolate. If the semantic of the datatype does not allow extrapolation this function should handle that gracefully.
You should call the QVariantAnimation implementation of this function if you want your class to handle the types already supported by Qt (see class QVariantAnimation description for a list of supported types).
See also
QEasingCurve
Definition at line 717 of file qvariantanimation.cpp.
 {
     return d_func()->interpolator(from.constData(), to.constData(), progress);
 }
keyValueAt()
QVariant QVariantAnimation::keyValueAt (qreal step) const
Returns the key frame value for the given step.
The given step must be in the range 0 to 1. If there is no KeyValue for step, it returns an invalid QVariant.
See also
keyValues(), setKeyValueAt()
Definition at line 597 of file qvariantanimation.cpp.
Referenced by setDuration(), and setStartValue().
 {
     return d_func()->valueAt(step);
 }
keyValues()
QVariantAnimation::KeyValues QVariantAnimation::keyValues () const
Returns the key frames of this animation.
See also
keyValueAt(), setKeyValues()
Definition at line 632 of file qvariantanimation.cpp.
Referenced by setKeyValues().
 {
     return d_func()->keyValues;
 }
registerInterpolator()
void QVariantAnimation::registerInterpolator (QVariantAnimation::Interpolator func, int interpolationType) static private
Warning
This function is not part of the public interface. Registers a custom interpolator func for the specific interpolationType. The interpolator has to be registered before the animation is constructed. To unregister (and use the default interpolator) set func to 0.
Definition at line 447 of file qvariantanimation.cpp.
Referenced by qRegisterAnimationInterpolator().
 {
     // will override any existing interpolators
     QInterpolatorVector *interpolators = registeredInterpolators();
     // When built on solaris with GCC, the destructors can be called
     // in such an order that we get here with interpolators == NULL,
     // to continue causes the app to crash on exit with a SEGV
     if (interpolators) {
 #ifndef QT_NO_THREAD
         QMutexLocker locker(QMutexPool::globalInstanceGet(interpolators));
 #endif
         if (int(interpolationType) >= interpolators->count())
             interpolators->resize(int(interpolationType) + 1);
         interpolators->replace(interpolationType, func);
     }
 }
setDuration()
void QVariantAnimation::setDuration (int msecs)
Definition at line 531 of file qvariantanimation.cpp.
Referenced by QWidgetAnimator::animate(), and QTabBarPrivate::Tab::startAnimation().
 {
     Q_D(QVariantAnimation);
     if (msecs < 0) {
         qWarning("QVariantAnimation::setDuration: cannot set a negative duration");
         return;
     }
     if (d->duration == msecs)
         return;
     d->duration = msecs;
     d->recalculateCurrentInterval();
 }
setEasingCurve()
void QVariantAnimation::setEasingCurve (const QEasingCurve & easing)
Definition at line 410 of file qvariantanimation.cpp.
Referenced by QWidgetAnimator::animate(), and QTabBarPrivate::Tab::TabBarAnimation::TabBarAnimation().
 {
     Q_D(QVariantAnimation);
     d->easing = easing;
     d->recalculateCurrentInterval();
 }
setEndValue()
void QVariantAnimation::setEndValue (const QVariant & value)
Definition at line 584 of file qvariantanimation.cpp.
Referenced by QWidgetAnimator::animate(), QStateMachinePrivate::initializeAnimation(), and QTabBarPrivate::Tab::startAnimation().
 {
     setKeyValueAt(1, value);
 }
setKeyValueAt()
void QVariantAnimation::setKeyValueAt (qreal step, const QVariant & value)
Creates a key frame at the given step with the given value.
The given step must be in the range 0 to 1.
See also
setKeyValues(), keyValueAt()
Definition at line 622 of file qvariantanimation.cpp.
Referenced by setEndValue(), and setStartValue().
 {
     d_func()->setValueAt(step, value);
 }
setKeyValues()
void QVariantAnimation::setKeyValues (const KeyValues & keyValues)
Replaces the current set of key frames with the given keyValues.
the step of the key frames must be in the range 0 to 1.
See also
keyValues(), keyValueAt()
Definition at line 643 of file qvariantanimation.cpp.
 {
     Q_D(QVariantAnimation);
     d->keyValues = keyValues;
     qSort(d->keyValues.begin(), d->keyValues.end(), animationValueLessThan);
     d->recalculateCurrentInterval(/*force=*/true);
 }
setStartValue()
void QVariantAnimation::setStartValue (const QVariant & value)
Definition at line 563 of file qvariantanimation.cpp.
Referenced by QTabBarPrivate::Tab::startAnimation().
 {
     setKeyValueAt(0, value);
 }
startValue()
QVariant QVariantAnimation::startValue () const
Referenced by setDuration(), and QPropertyAnimation::updateState().
updateCurrentTime()
void QVariantAnimation::updateCurrentTime (int) protected virtual
Reimplemented Function
Implements QAbstractAnimation.
Definition at line 725 of file qvariantanimation.cpp.
 {
     d_func()->recalculateCurrentInterval();
 }
updateCurrentValue()
void QVariantAnimation::updateCurrentValue (const QVariant & value) protected pure virtual
This pure virtual function is called every time the animation's current value changes.
The value argument is the new current value.
See also
currentValue
Implemented in QDeclarativeBulkValueAnimator, QTabBarPrivate::Tab::TabBarAnimation, QTreeViewPrivate::AnimatedOperation, and QPropertyAnimation.
updateState()
void QVariantAnimation::updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState) protected virtual
Reimplemented Function
Reimplemented from QAbstractAnimation.
Definition at line 690 of file qvariantanimation.cpp.
Referenced by QPropertyAnimation::updateState(), and QDeclarativeBulkValueAnimator::updateState().
 {
     Q_UNUSED(oldState);
     Q_UNUSED(newState);
 }
valueChanged
void QVariantAnimation::valueChanged (const QVariant & value) signal
QVariantAnimation emits this signal whenever the current value changes.
See also
currentValue, startValue, endValue
Friends and Related Functions
qRegisterAnimationInterpolator [1/2]
template<typename T > void qRegisterAnimationInterpolator (QVariant(*)(const T &, const T &, qreal) func) friend
qRegisterAnimationInterpolator() [2/2]
void qRegisterAnimationInterpolator (QVariant(*)(const T &from, const T &to, qreal progress) func) related
Note
This class or function is threadsafe.
Registers a custom interpolator func for the template type T. The interpolator has to be registered before the animation is constructed. To unregister (and use the default interpolator) set func to 0.
Definition at line 120 of file qvariantanimation.h.
{
     QVariantAnimation::registerInterpolator(reinterpret_cast<QVariantAnimation::Interpolator>(func), qMetaTypeId<T>());
 }
Properties
currentValue
QVariant QVariantAnimation::currentValue private
the current value of the animation.
This property describes the current value; an interpolated value between the start value and the end value, using the current time for progress. The value itself is obtained from interpolated(), which is called repeatedly as the animation is running.
QVariantAnimation calls the virtual updateCurrentValue() function when the current value changes. This is particularly useful for subclasses that need to track updates. For example, QPropertyAnimation uses this function to animate Qt Qt's Property System{properties}.
See also
startValue, endValue
Definition at line 65 of file qvariantanimation.h.
duration
int QVariantAnimation::duration private
the duration of the animation
This property describes the duration in milliseconds of the animation. The default duration is 250 milliseconds.
See also
QAbstractAnimation::duration()
Definition at line 66 of file qvariantanimation.h.
easingCurve
QEasingCurve QVariantAnimation::easingCurve private
the easing curve of the animation
This property defines the easing curve of the animation. By default, a linear easing curve is used, resulting in linear interpolation. Other curves are provided, for instance, QEasingCurve::InCirc, which provides a circular entry curve. Another example is QEasingCurve::InOutElastic, which provides an elastic effect on the values of the interpolated variant.
QVariantAnimation will use the QEasingCurve::valueForProgress() to transform the "normalized progress" (currentTime / totalDuration) of the animation into the effective progress actually used by the animation. It is this effective progress that will be the progress when interpolated() is called. Also, the steps in the keyValues are referring to this effective progress.
The easing curve is used with the interpolator, the interpolated() virtual function, the animation's duration, and iterationCount, to control how the current value changes as the animation progresses.
Definition at line 67 of file qvariantanimation.h.
endValue
QVariant QVariantAnimation::endValue private
the end value of the animation
This property describes the end value of the animation.
See also
startValue
Definition at line 64 of file qvariantanimation.h.
Referenced by QStateMachinePrivate::applyProperties().
startValue
QVariant QVariantAnimation::startValue private
the optional start value of the animation
This property describes the optional start value of the animation. If omitted, or if a null QVariant is assigned as the start value, the animation will use the current position of the end when the animation is started.
See also
endValue
Definition at line 63 of file qvariantanimation.h.
The documentation for this class was generated from the following files:
/src/corelib/animation/qvariantanimation.h
/src/corelib/animation/qvariantanimation.cpp