Qt 4.8: QFormLayout Class Reference
QFormLayout Class Reference
The QFormLayout class manages forms of input widgets and their associated labels.
#include <qformlayout.h>
Public Types
enum FieldGrowthPolicy { FieldsStayAtSizeHint, ExpandingFieldsGrow, AllNonFixedFieldsGrow }
This enum specifies the different policies that can be used to control the way in which the form's fields grow.
enum ItemRole { LabelRole = 0, FieldRole = 1, SpanningRole = 2 }
This enum specifies the types of widgets (or other layout items) that may appear in a row.
enum RowWrapPolicy { DontWrapRows, WrapLongRows, WrapAllRows }
This enum specifies the different policies that can be used to control the way in which the form's rows wrap.
Public Types inherited from QLayout
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Public Functions
void addItem (QLayoutItem *item)
Reimplemented Function
void addRow (QWidget *label, QWidget *field)
Adds a new row to the bottom of this form layout, with the given label and field.
void addRow (QWidget *label, QLayout *field)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void addRow (const QString &labelText, QWidget *field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
void addRow (const QString &labelText, QLayout *field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
void addRow (QWidget *widget)
Adds the specified widget at the end of this form layout.
void addRow (QLayout *layout)
Adds the specified layout at the end of this form layout.
int count () const
Reimplemented Function
Qt::Orientations expandingDirections () const
Reimplemented Function
FieldGrowthPolicy fieldGrowthPolicy () const
Qt::Alignment formAlignment () const
void getItemPosition (int index, int *rowPtr, ItemRole *rolePtr) const
Retrieves the row and role (column) of the item at the specified index.
void getLayoutPosition (QLayout *layout, int *rowPtr, ItemRole *rolePtr) const
Retrieves the row and role (column) of the specified child layout.
void getWidgetPosition (QWidget *widget, int *rowPtr, ItemRole *rolePtr) const
Retrieves the row and role (column) of the specified widget in the layout.
bool hasHeightForWidth () const
Reimplemented Function
int heightForWidth (int width) const
Reimplemented Function
int horizontalSpacing () const
void insertRow (int row, QWidget *label, QWidget *field)
Inserts a new row at position row in this form layout, with the given label and field.
void insertRow (int row, QWidget *label, QLayout *field)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void insertRow (int row, const QString &labelText, QWidget *field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
void insertRow (int row, const QString &labelText, QLayout *field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
void insertRow (int row, QWidget *widget)
Inserts the specified widget at position row in this form layout.
void insertRow (int row, QLayout *layout)
Inserts the specified layout at position row in this form layout.
void invalidate ()
Reimplemented Function
QLayoutItem * itemAt (int row, ItemRole role) const
Returns the layout item in the given row with the specified role (column).
QLayoutItem * itemAt (int index) const
Reimplemented Function
Qt::Alignment labelAlignment () const
QWidget * labelForField (QWidget *field) const
Returns the label associated with the given field.
QWidget * labelForField (QLayout *field) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QSize minimumSize () const
Reimplemented Function
QFormLayout (QWidget *parent=0)
Constructs a new form layout with the given parent widget.
int rowCount () const
Returns the number of rows in the form.
RowWrapPolicy rowWrapPolicy () const
void setFieldGrowthPolicy (FieldGrowthPolicy policy)
void setFormAlignment (Qt::Alignment alignment)
void setGeometry (const QRect &rect)
Reimplemented Function
void setHorizontalSpacing (int spacing)
void setItem (int row, ItemRole role, QLayoutItem *item)
Sets the item in the given row for the given role to item, extending the layout with empty rows if necessary.
void setLabelAlignment (Qt::Alignment alignment)
void setLayout (int row, ItemRole role, QLayout *layout)
Sets the sub-layout in the given row for the given role to layout, extending the form layout with empty rows if necessary.
void setRowWrapPolicy (RowWrapPolicy policy)
void setSpacing (int)
This function sets both the vertical and horizontal spacing to spacing.
void setVerticalSpacing (int spacing)
void setWidget (int row, ItemRole role, QWidget *widget)
Sets the widget in the given row for the given role to widget, extending the layout with empty rows if necessary.
QSize sizeHint () const
Reimplemented Function
int spacing () const
If the vertical spacing is equal to the horizontal spacing, this function returns that value; otherwise it returns -1.
QLayoutItem * takeAt (int index)
Reimplemented Function
int verticalSpacing () const
~QFormLayout ()
Destroys the form layout.
Public Functions inherited from QLayout
bool activate ()
Redoes the layout for parentWidget() if necessary.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
virtual int indexOf (QWidget *) const
Searches for widget widget in this layout (not including child layouts).
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
QLayout * layout ()
Reimplemented Function
int margin () const
QSize maximumSize () const
Returns the maximum size of this layout.
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QSize minimumSize () const
Returns the minimum size of this layout.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Private Functions
void resetFieldGrowthPolicy ()
void resetFormAlignment ()
void resetLabelAlignment ()
void resetRowWrapPolicy ()
Properties
FieldGrowthPolicy fieldGrowthPolicy
the way in which the form's fields grow
Qt::Alignment formAlignment
the alignment of the form layout's contents within the layout's geometry
int horizontalSpacing
the spacing between widgets that are laid out side by side
Qt::Alignment labelAlignment
the horizontal alignment of the labels
RowWrapPolicy rowWrapPolicy
the way in which the form's rows wrap
int verticalSpacing
the spacing between widgets that are laid out vertically
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QLayout
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QLayout
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QFormLayout class manages forms of input widgets and their associated labels.
Since
4.4
QFormLayout is a convenience layout class that lays out its children in a two-column form. The left column consists of labels and the right column consists of "field" widgets (line editors, spin boxes, etc.).
Traditionally, such two-column form layouts were achieved using QGridLayout. QFormLayout is a higher-level alternative that provides the following advantages:
Adherence to the different platform's look and feel guidelines.
For example, the Mac OS X Aqua and KDE guidelines specify that the labels should be right-aligned, whereas Windows and GNOME applications normally use left-alignment.
Support for wrapping long rows.
For devices with small displays, QFormLayout can be set to wrap long rows, or even to wrap all rows.
Convenient API for creating label–field pairs.
The addRow() overload that takes a QString and a QWidget * creates a QLabel behind the scenes and automatically set up its buddy. We can then write code like this:
QFormLayout *formLayout = new QFormLayout;
formLayout->addRow(tr("&Name:"), nameLineEdit);
formLayout->addRow(tr("&Email:"), emailLineEdit);
formLayout->addRow(tr("&Age:"), ageSpinBox);
setLayout(formLayout);
Compare this with the following code, written using QGridLayout:
nameLabel = new QLabel(tr("&Name:"));
nameLabel->setBuddy(nameLineEdit);
emailLabel = new QLabel(tr("&Name:"));
emailLabel->setBuddy(emailLineEdit);
ageLabel = new QLabel(tr("&Name:"));
ageLabel->setBuddy(ageSpinBox);
QGridLayout *gridLayout = new QGridLayout;
gridLayout->addWidget(nameLabel, 0, 0);
gridLayout->addWidget(nameLineEdit, 0, 1);
gridLayout->addWidget(emailLabel, 1, 0);
gridLayout->addWidget(emailLineEdit, 1, 1);
gridLayout->addWidget(ageLabel, 2, 0);
gridLayout->addWidget(ageSpinBox, 2, 1);
setLayout(gridLayout);
The table below shows the default appearance in different styles.
QCommonStyle derived styles (except QPlastiqueStyle) QMacStyle QPlastiqueStyle Qt Extended styles
Traditional style used for Windows, GNOME, and earlier versions of KDE. Labels are left aligned, and expanding fields grow to fill the available space. (This normally corresponds to what we would get using a two-column QGridLayout.) Style based on the Mac OS X Aqua guidelines. Labels are right-aligned, the fields don't grow beyond their size hint, and the form is horizontally centered. Recommended style for KDE applications. Similar to MacStyle, except that the form is left-aligned and all fields grow to fill the available space. Default style for Qt Extended styles. Labels are right-aligned, expanding fields grow to fill the available space, and row wrapping is enabled for long lines.
The form styles can be also be overridden individually by calling setLabelAlignment(), setFormAlignment(), setFieldGrowthPolicy(), and setRowWrapPolicy(). For example, to simulate the form layout appearance of QMacStyle on all platforms, but with left-aligned labels, you could write:
formLayout->setRowWrapPolicy(QFormLayout::DontWrapRows);
formLayout->setFieldGrowthPolicy(QFormLayout::FieldsStayAtSizeHint);
formLayout->setFormAlignment(Qt::AlignHCenter | Qt::AlignTop);
formLayout->setLabelAlignment(Qt::AlignLeft);
See also
QGridLayout, QBoxLayout, QStackedLayout
Definition at line 55 of file qformlayout.h.
Enumerations
FieldGrowthPolicy
enum QFormLayout::FieldGrowthPolicy
This enum specifies the different policies that can be used to control the way in which the form's fields grow.
FieldsStayAtSizeHint The fields never grow beyond their effective size hint. This is the default for QMacStyle.
ExpandingFieldsGrow Fields with an horizontal size policy of QSizePolicy::Expanding or QSizePolicy::MinimumExpanding will grow to fill the available space. The other fields will not grow beyond their effective size hint. This is the default policy for Plastique.
AllNonFixedFieldsGrow All fields with a size policy that allows them to grow will grow to fill the available space. This is the default policy for most styles.
See also
fieldGrowthPolicy
Enumerator
FieldsStayAtSizeHint
ExpandingFieldsGrow
AllNonFixedFieldsGrow
Definition at line 68 of file qformlayout.h.
{
         FieldsStayAtSizeHint,
         ExpandingFieldsGrow,
         AllNonFixedFieldsGrow
     };
ItemRole
enum QFormLayout::ItemRole
This enum specifies the types of widgets (or other layout items) that may appear in a row.
LabelRole A label widget.
FieldRole A field widget.
SpanningRole A widget that spans label and field columns.
See also
itemAt(), getItemPosition()
Enumerator
LabelRole
FieldRole
SpanningRole
Definition at line 80 of file qformlayout.h.
                   {
         LabelRole = 0,
         FieldRole = 1,
         SpanningRole = 2
     };
RowWrapPolicy
enum QFormLayout::RowWrapPolicy
This enum specifies the different policies that can be used to control the way in which the form's rows wrap.
DontWrapRows Fields are always laid out next to their label. This is the default policy for all styles except Qt Extended styles and QS60Style.
WrapLongRows Labels are given enough horizontal space to fit the widest label, and the rest of the space is given to the fields. If the minimum size of a field pair is wider than the available space, the field is wrapped to the next line. This is the default policy for Qt Extended styles and and QS60Style.
WrapAllRows Fields are always laid out below their label.
See also
rowWrapPolicy
Enumerator
DontWrapRows
WrapLongRows
WrapAllRows
Definition at line 74 of file qformlayout.h.
{
         DontWrapRows,
         WrapLongRows,
         WrapAllRows
     };
Constructors and Destructors
QFormLayout()
QFormLayout::QFormLayout (QWidget * parent = 0) explicit
Constructs a new form layout with the given parent widget.
See also
QWidget::setLayout()
Definition at line 1173 of file qformlayout.cpp.
     : QLayout(*new QFormLayoutPrivate, 0, parent)
 {
 }
~QFormLayout()
QFormLayout::~QFormLayout ()
Destroys the form layout.
Definition at line 1181 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     /*
         The clearing and destruction order here is important. We start by clearing
         m_things so that QLayout and the rest of the world know that we don't babysit
         the layout items anymore and don't care if they are destroyed.
     */
     d->m_things.clear();
     qDeleteAll(d->m_matrix.storage());
     d->m_matrix.clear();
 }
Functions
addItem()
void QFormLayout::addItem (QLayoutItem * item) virtual
Reimplemented Function
Implements QLayout.
Definition at line 1392 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     int row = d->insertRow(d->m_matrix.rowCount());
     d->setItem(row, FieldRole, item);
     invalidate();
 }
addRow() [1/6]
void QFormLayout::addRow (QWidget * label, QWidget * field)
Adds a new row to the bottom of this form layout, with the given label and field.
See also
insertRow()
Definition at line 1201 of file qformlayout.cpp.
 {
     insertRow(-1, label, field);
 }
addRow() [2/6]
void QFormLayout::addRow (QWidget * label, QLayout * field)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1209 of file qformlayout.cpp.
 {
     insertRow(-1, label, field);
 }
addRow() [3/6]
void QFormLayout::addRow (const QString & labelText, QWidget * field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The field is set as the new QLabel's buddy.
Definition at line 1224 of file qformlayout.cpp.
 {
     insertRow(-1, labelText, field);
 }
addRow() [4/6]
void QFormLayout::addRow (const QString & labelText, QLayout * field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1238 of file qformlayout.cpp.
 {
     insertRow(-1, labelText, field);
 }
addRow() [5/6]
void QFormLayout::addRow (QWidget * widget)
Adds the specified widget at the end of this form layout.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The widget spans both columns.
Definition at line 1252 of file qformlayout.cpp.
 {
     insertRow(-1, widget);
 }
addRow() [6/6]
void QFormLayout::addRow (QLayout * layout)
Adds the specified layout at the end of this form layout.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The layout spans both columns.
Definition at line 1266 of file qformlayout.cpp.
 {
     insertRow(-1, layout);
 }
count()
int QFormLayout::count () const virtual
Reimplemented Function
Implements QLayout.
Definition at line 1404 of file qformlayout.cpp.
Referenced by getLayoutPosition().
 {
     Q_D(const QFormLayout);
     return d->m_things.count();
 }
expandingDirections()
Qt::Orientations QFormLayout::expandingDirections () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1462 of file qformlayout.cpp.
 {
     Q_D(const QFormLayout);
     QFormLayoutPrivate *e = const_cast<QFormLayoutPrivate *>(d);
     e->updateSizes();
     Qt::Orientations o = 0;
     if (e->expandHorizontal)
         o = Qt::Horizontal;
     if (e->expandVertical)
         o |= Qt::Vertical;
     return o;
 }
fieldGrowthPolicy()
FieldGrowthPolicy QFormLayout::fieldGrowthPolicy () const
Referenced by setFieldGrowthPolicy().
formAlignment()
Qt::Alignment QFormLayout::formAlignment () const
Referenced by QFormLayoutPrivate::arrangeWidgets(), and setFormAlignment().
getItemPosition()
void QFormLayout::getItemPosition (int index, int * rowPtr, ItemRole * rolePtr) const
Retrieves the row and role (column) of the item at the specified index.
If index is out of bounds, *rowPtr is set to -1; otherwise the row is stored in *rowPtr and the role is stored in *rolePtr.
See also
itemAt(), count(), getLayoutPosition(), getWidgetPosition()
Definition at line 1631 of file qformlayout.cpp.
Referenced by getLayoutPosition(), and getWidgetPosition().
 {
     Q_D(const QFormLayout);
     int col = -1;
     int row = -1;
     const int storageIndex = storageIndexFromLayoutItem(d->m_matrix, d->m_things.value(index));
     if (storageIndex != -1)
         QFormLayoutPrivate::ItemMatrix::storageIndexToPosition(storageIndex, &row, &col);
     if (rowPtr)
         *rowPtr = row;
     if (rolePtr && col != -1) {
         const bool spanning = col == 1 && d->m_matrix(row, col)->fullRow;
         if (spanning) {
             *rolePtr = SpanningRole;
         } else {
             *rolePtr = ItemRole(col);
         }
     }
 }
getLayoutPosition()
void QFormLayout::getLayoutPosition (QLayout * layout, int * rowPtr, ItemRole * rolePtr) const
Retrieves the row and role (column) of the specified child layout.
If layout is not in the form layout, *rowPtr is set to -1; otherwise the row is stored in *rowPtr and the role is stored in *rolePtr.
Definition at line 1659 of file qformlayout.cpp.
Referenced by labelForField().
 {
     int n = count();
     int index = 0;
     while (index < n) {
         if (itemAt(index) == layout)
             break;
         ++index;
     }
     getItemPosition(index, rowPtr, rolePtr);
 }
getWidgetPosition()
void QFormLayout::getWidgetPosition (QWidget * widget, int * rowPtr, ItemRole * rolePtr) const
Retrieves the row and role (column) of the specified widget in the layout.
If widget is not in the layout, *rowPtr is set to -1; otherwise the row is stored in *rowPtr and the role is stored in *rolePtr.
See also
getItemPosition(), itemAt()
Definition at line 1679 of file qformlayout.cpp.
Referenced by labelForField().
 {
     getItemPosition(indexOf(widget), rowPtr, rolePtr);
 }
hasHeightForWidth()
bool QFormLayout::hasHeightForWidth () const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1479 of file qformlayout.cpp.
Referenced by heightForWidth(), and setGeometry().
 {
     Q_D(const QFormLayout);
     QFormLayoutPrivate *e = const_cast<QFormLayoutPrivate *>(d);
     e->updateSizes();
     return (d->has_hfw || rowWrapPolicy() == WrapLongRows);
 }
heightForWidth()
int QFormLayout::heightForWidth (int width) const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1490 of file qformlayout.cpp.
 {
     Q_D(const QFormLayout);
     if (!hasHeightForWidth())
         return -1;
     int leftMargin, topMargin, rightMargin, bottomMargin;
     getContentsMargins(&leftMargin, &topMargin, &rightMargin, &bottomMargin);
     int targetWidth = width - leftMargin - rightMargin;
     if (!d->haveHfwCached(targetWidth)) {
         QFormLayoutPrivate *dat = const_cast<QFormLayoutPrivate *>(d);
         dat->setupVerticalLayoutData(targetWidth);
         dat->setupHorizontalLayoutData(targetWidth);
         dat->recalcHFW(targetWidth);
     }
     if (targetWidth == d->sh_width)
         return d->hfw_sh_height + topMargin + bottomMargin;
     else
         return d->hfw_height + topMargin + bottomMargin;
 }
horizontalSpacing()
int QFormLayout::horizontalSpacing () const
Referenced by setHorizontalSpacing(), and spacing().
insertRow() [1/6]
void QFormLayout::insertRow (int row, QWidget * label, QWidget * field)
Inserts a new row at position row in this form layout, with the given label and field.
If row is out of bounds, the new row is added at the end.
See also
addRow()
Definition at line 1278 of file qformlayout.cpp.
Referenced by addRow(), and insertRow().
 {
     Q_D(QFormLayout);
     row = d->insertRow(row);
     if (label)
         d->setWidget(row, LabelRole, label);
     if (field)
         d->setWidget(row, FieldRole, field);
     invalidate();
 }
insertRow() [2/6]
void QFormLayout::insertRow (int row, QWidget * label, QLayout * field)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1293 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     row = d->insertRow(row);
     if (label)
         d->setWidget(row, LabelRole, label);
     if (field)
         d->setLayout(row, FieldRole, field);
     invalidate();
 }
insertRow() [3/6]
void QFormLayout::insertRow (int row, const QString & labelText, QWidget * field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The field is set as the new QLabel's buddy.
Definition at line 1315 of file qformlayout.cpp.
 {
     QLabel *label = 0;
     if (!labelText.isEmpty()) {
         label = new QLabel(labelText);
 #ifndef QT_NO_SHORTCUT
         label->setBuddy(field);
 #endif
     }
     insertRow(row, label, field);
 }
insertRow() [4/6]
void QFormLayout::insertRow (int row, const QString & labelText, QLayout * field)
This overload automatically creates a QLabel behind the scenes with labelText as its text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1336 of file qformlayout.cpp.
 {
     insertRow(row, labelText.isEmpty() ? 0 : new QLabel(labelText), field);
 }
insertRow() [5/6]
void QFormLayout::insertRow (int row, QWidget * widget)
Inserts the specified widget at position row in this form layout.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The widget spans both columns. If row is out of bounds, the widget is added at the end.
Definition at line 1351 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (!widget) {
         qWarning("QFormLayout: Cannot add null field to %s", qPrintable(objectName()));
         return;
     }
     row = d->insertRow(row);
     d->setWidget(row, SpanningRole, widget);
     invalidate();
 }
insertRow() [6/6]
void QFormLayout::insertRow (int row, QLayout * layout)
Inserts the specified layout at position row in this form layout.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The layout spans both columns. If row is out of bounds, the widget is added at the end.
Definition at line 1375 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (!layout) {
         qWarning("QFormLayout: Cannot add null field to %s", qPrintable(objectName()));
         return;
     }
     row = d->insertRow(row);
     d->setLayout(row, SpanningRole, layout);
     invalidate();
 }
invalidate()
void QFormLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 1571 of file qformlayout.cpp.
Referenced by addItem(), insertRow(), setFieldGrowthPolicy(), setFormAlignment(), setHorizontalSpacing(), setLabelAlignment(), setRowWrapPolicy(), setSpacing(), setVerticalSpacing(), and takeAt().
 {
     Q_D(QFormLayout);
     d->dirty = true;
     d->sizesDirty = true;
     d->minSize = QSize();
     d->prefSize = QSize();
     d->formMaxWidth = -1;
     d->hfw_width = -1;
     d->sh_width = -1;
     d->layoutWidth = -1;
     d->hfw_sh_height = -1;
     QLayout::invalidate();
 }
itemAt() [1/2]
QLayoutItem * QFormLayout::itemAt (int row, ItemRole role) const
Returns the layout item in the given row with the specified role (column).
Returns 0 if there is no such item.
See also
QLayout::itemAt(), setItem()
Definition at line 1603 of file qformlayout.cpp.
Referenced by getLayoutPosition().
 {
     Q_D(const QFormLayout);
     if (uint(row) >= uint(d->m_matrix.rowCount()))
         return 0;
     switch (role) {
     case SpanningRole:
         if (QFormLayoutItem *item = d->m_matrix(row, 1))
             if (item->fullRow)
                 return item->item;
         break;
     case LabelRole:
     case FieldRole:
         if (QFormLayoutItem *item = d->m_matrix(row, (role == LabelRole) ? 0 : 1))
             return item->item;
         break;
     }
     return 0;
 }
itemAt() [2/2]
QLayoutItem * QFormLayout::itemAt (int index) const virtual
Reimplemented Function
Implements QLayout.
Definition at line 1413 of file qformlayout.cpp.
 {
     Q_D(const QFormLayout);
     if (QFormLayoutItem *formItem = d->m_things.value(index))
         return formItem->item;
     return 0;
 }
labelAlignment()
Qt::Alignment QFormLayout::labelAlignment () const
Referenced by setLabelAlignment().
labelForField() [1/2]
QWidget * QFormLayout::labelForField (QWidget * field) const
Returns the label associated with the given field.
See also
itemAt()
Definition at line 1691 of file qformlayout.cpp.
 {
     Q_D(const QFormLayout);
     int row;
     ItemRole role;
     getWidgetPosition(field, &row, &role);
     if (row != -1 && role == FieldRole) {
         if (QFormLayoutItem *label = d->m_matrix(row, LabelRole))
             return label->widget();
     }
     return 0;
 }
labelForField() [2/2]
QWidget * QFormLayout::labelForField (QLayout * field) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1710 of file qformlayout.cpp.
 {
     Q_D(const QFormLayout);
     int row;
     ItemRole role;
     getLayoutPosition(field, &row, &role);
     if (row != -1 && role == FieldRole) {
         if (QFormLayoutItem *label = d->m_matrix(row, LabelRole))
             return label->widget();
     }
     return 0;
 }
minimumSize()
QSize QFormLayout::minimumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1557 of file qformlayout.cpp.
 {
     // ### fix minimumSize if hfw
     Q_D(const QFormLayout);
     if (!d->minSize.isValid()) {
         QFormLayoutPrivate *dat = const_cast<QFormLayoutPrivate *>(d);
         dat->calcSizeHints();
     }
     return d->minSize;
 }
resetFieldGrowthPolicy()
void QFormLayout::resetFieldGrowthPolicy () private
Warning
This function is not part of the public interface.
Definition at line 2090 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     d->fieldGrowthPolicy = DefaultFieldGrowthPolicy;
 }
resetFormAlignment()
void QFormLayout::resetFormAlignment () private
Warning
This function is not part of the public interface.
Definition at line 2110 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     d->formAlignment = 0;
 }
resetLabelAlignment()
void QFormLayout::resetLabelAlignment () private
Warning
This function is not part of the public interface.
Definition at line 2120 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     d->labelAlignment = 0;
 }
resetRowWrapPolicy()
void QFormLayout::resetRowWrapPolicy () private
Warning
This function is not part of the public interface.
Definition at line 2100 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     d->rowWrapPolicy = DefaultRowWrapPolicy;
 }
rowCount()
int QFormLayout::rowCount () const
Returns the number of rows in the form.
See also
QLayout::count()
Definition at line 1591 of file qformlayout.cpp.
Referenced by resetLabelAlignment(), setItem(), setLayout(), and setWidget().
 {
     Q_D(const QFormLayout);
     return d->m_matrix.rowCount();
 }
rowWrapPolicy()
RowWrapPolicy QFormLayout::rowWrapPolicy () const
Referenced by hasHeightForWidth(), and setRowWrapPolicy().
setFieldGrowthPolicy()
void QFormLayout::setFieldGrowthPolicy (FieldGrowthPolicy policy)
Definition at line 1746 of file qformlayout.cpp.
Referenced by QPrintPreviewDialogPrivate::init().
 {
     Q_D(QFormLayout);
     if (FieldGrowthPolicy(d->fieldGrowthPolicy) != policy) {
         d->fieldGrowthPolicy = policy;
         invalidate();
     }
 }
setFormAlignment()
void QFormLayout::setFormAlignment (Qt::Alignment alignment)
Definition at line 1849 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (d->formAlignment != alignment) {
         d->formAlignment = alignment;
         invalidate();
     }
 }
setGeometry()
void QFormLayout::setGeometry (const QRect & rect) virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 1516 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (d->dirty || rect != geometry()) {
         QRect cr = rect;
         int leftMargin, topMargin, rightMargin, bottomMargin;
         getContentsMargins(&leftMargin, &topMargin, &rightMargin, &bottomMargin);
         cr.adjust(+leftMargin, +topMargin, -rightMargin, -bottomMargin);
         bool hfw = hasHeightForWidth();
         d->setupVerticalLayoutData(cr.width());
         d->setupHorizontalLayoutData(cr.width());
         if (hfw && (!d->haveHfwCached(cr.width()) || d->hfwLayouts.size() != d->vLayoutCount))
             d->recalcHFW(cr.width());
         if (hfw) {
             qGeomCalc(d->hfwLayouts, 0, d->vLayoutCount, cr.y(), cr.height());
             d->arrangeWidgets(d->hfwLayouts, cr);
         } else {
             qGeomCalc(d->vLayouts, 0, d->vLayoutCount, cr.y(), cr.height());
             d->arrangeWidgets(d->vLayouts, cr);
         }
         QLayout::setGeometry(rect);
     }
 }
setHorizontalSpacing()
void QFormLayout::setHorizontalSpacing (int spacing)
Definition at line 1881 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (spacing != d->hSpacing) {
         d->hSpacing = spacing;
         invalidate();
     }
 }
setItem()
void QFormLayout::setItem (int row, ItemRole role, QLayoutItem * item)
Sets the item in the given row for the given role to item, extending the layout with empty rows if necessary.
If the cell is already occupied, the item is not inserted and an error message is sent to the console. The item spans both columns.
Warning
Do not use this function to add child layouts or child widget items. Use setLayout() or setWidget() instead.
See also
setLayout()
Definition at line 2077 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     int rowCnt = rowCount();
     if (row >= rowCnt)
         d->insertRows(rowCnt, row - rowCnt + 1);
     d->setItem(row, role, item);
 }
setLabelAlignment()
void QFormLayout::setLabelAlignment (Qt::Alignment alignment)
Definition at line 1816 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (d->labelAlignment != alignment) {
         d->labelAlignment = alignment;
         invalidate();
     }
 }
setLayout()
void QFormLayout::setLayout (int row, ItemRole role, QLayout * layout)
Sets the sub-layout in the given row for the given role to layout, extending the form layout with empty rows if necessary.
If the cell is already occupied, the layout is not inserted and an error message is sent to the console.
Note: For most applications, addRow() or insertRow() should be used instead of setLayout().
See also
setWidget()
Definition at line 2055 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     int rowCnt = rowCount();
     if (row >= rowCnt)
         d->insertRows(rowCnt, row - rowCnt + 1);
     d->setLayout(row, role, layout);
 }
setRowWrapPolicy()
void QFormLayout::setRowWrapPolicy (RowWrapPolicy policy)
Definition at line 1782 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (RowWrapPolicy(d->rowWrapPolicy) != policy) {
         d->rowWrapPolicy = policy;
         invalidate();
     }
 }
setSpacing()
void QFormLayout::setSpacing (int spacing)
This function sets both the vertical and horizontal spacing to spacing.
See also
setVerticalSpacing(), setHorizontalSpacing()
Definition at line 1938 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     d->vSpacing = d->hSpacing = spacing;
     invalidate();
 }
setVerticalSpacing()
void QFormLayout::setVerticalSpacing (int spacing)
Definition at line 1913 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     if (spacing != d->vSpacing) {
         d->vSpacing = spacing;
         invalidate();
     }
 }
setWidget()
void QFormLayout::setWidget (int row, ItemRole role, QWidget * widget)
Sets the widget in the given row for the given role to widget, extending the layout with empty rows if necessary.
If the cell is already occupied, the widget is not inserted and an error message is sent to the console.
Note: For most applications, addRow() or insertRow() should be used instead of setWidget().
See also
setLayout()
Definition at line 2035 of file qformlayout.cpp.
Referenced by QPrintPreviewDialogPrivate::init().
 {
     Q_D(QFormLayout);
     int rowCnt = rowCount();
     if (row >= rowCnt)
         d->insertRows(rowCnt, row - rowCnt + 1);
     d->setWidget(row, role, widget);
 }
sizeHint()
QSize QFormLayout::sizeHint () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 1544 of file qformlayout.cpp.
 {
     Q_D(const QFormLayout);
     if (!d->prefSize.isValid()) {
         QFormLayoutPrivate *dat = const_cast<QFormLayoutPrivate *>(d);
         dat->calcSizeHints();
     }
     return d->prefSize;
 }
spacing()
int QFormLayout::spacing () const
If the vertical spacing is equal to the horizontal spacing, this function returns that value; otherwise it returns -1.
See also
setSpacing(), verticalSpacing(), horizontalSpacing()
Definition at line 1951 of file qformlayout.cpp.
Referenced by setHorizontalSpacing(), setSpacing(), and setVerticalSpacing().
 {
     int hSpacing = horizontalSpacing();
     if (hSpacing == verticalSpacing()) {
         return hSpacing;
     } else {
         return -1;
     }
 }
takeAt()
QLayoutItem * QFormLayout::takeAt (int index) virtual
Reimplemented Function
Implements QLayout.
Definition at line 1424 of file qformlayout.cpp.
 {
     Q_D(QFormLayout);
     const int storageIndex = storageIndexFromLayoutItem(d->m_matrix, d->m_things.value(index));
     if (storageIndex == -1) {
         qWarning("QFormLayout::takeAt: Invalid index %d", index);
         return 0;
     }
     int row, col;
     QFormLayoutPrivate::ItemMatrix::storageIndexToPosition(storageIndex, &row, &col);
     Q_ASSERT(d->m_matrix(row, col));
     QFormLayoutItem *item = d->m_matrix(row, col);
     Q_ASSERT(item);
     d->m_things.removeAt(index);
     d->m_matrix(row, col) = 0;
     invalidate();
     // grab ownership back from the QFormLayoutItem
     QLayoutItem *i = item->item;
     item->item = 0;
     delete item;
     if (QLayout *l = i->layout()) {
         // sanity check in case the user passed something weird to QObject::setParent()
         if (l->parent() == this)
             l->setParent(0);
     }
     return i;
 }
verticalSpacing()
int QFormLayout::verticalSpacing () const
Referenced by setVerticalSpacing(), and spacing().
Properties
fieldGrowthPolicy
QFormLayout::FieldGrowthPolicy QFormLayout::fieldGrowthPolicy private
the way in which the form's fields grow
The default value depends on the widget or application style. For QMacStyle, the default is FieldsStayAtSizeHint; for QCommonStyle derived styles (like Plastique and Windows), the default is ExpandingFieldsGrow; for Qt Extended styles, the default is AllNonFixedFieldsGrow.
If none of the fields can grow and the form is resized, extra space is distributed according to the current form alignment.
See also
formAlignment, rowWrapPolicy
Definition at line 60 of file qformlayout.h.
formAlignment
Qt::Alignment QFormLayout::formAlignment private
the alignment of the form layout's contents within the layout's geometry
The default value depends on the widget or application style. For QMacStyle, the default is Qt::AlignHCenter | Qt::AlignTop; for the other styles, the default is Qt::AlignLeft | Qt::AlignTop.
See also
labelAlignment, rowWrapPolicy
Definition at line 63 of file qformlayout.h.
horizontalSpacing
int QFormLayout::horizontalSpacing private
the spacing between widgets that are laid out side by side
By default, if no value is explicitly set, the layout's horizontal spacing is inherited from the parent layout, or from the style settings for the parent widget.
See also
verticalSpacing, QStyle::pixelMetric(), {QStyle::}{PM_LayoutHorizontalSpacing}
Definition at line 64 of file qformlayout.h.
labelAlignment
Qt::Alignment QFormLayout::labelAlignment private
the horizontal alignment of the labels
The default value depends on the widget or application style. For QCommonStyle derived styles, except for QPlastiqueStyle, the default is Qt::AlignLeft; for the other styles, the default is Qt::AlignRight.
See also
formAlignment
Definition at line 62 of file qformlayout.h.
rowWrapPolicy
QFormLayout::RowWrapPolicy QFormLayout::rowWrapPolicy private
the way in which the form's rows wrap
The default value depends on the widget or application style. For Qt Extended styles and QS60Style, the default is WrapLongRows; for the other styles, the default is DontWrapRows.
If you want to display each label above its associated field (instead of next to it), set this property to WrapAllRows.
See also
fieldGrowthPolicy
Definition at line 61 of file qformlayout.h.
verticalSpacing
int QFormLayout::verticalSpacing private
the spacing between widgets that are laid out vertically
By default, if no value is explicitly set, the layout's vertical spacing is inherited from the parent layout, or from the style settings for the parent widget.
See also
horizontalSpacing, QStyle::pixelMetric(), {QStyle::}{PM_LayoutHorizontalSpacing}
Definition at line 65 of file qformlayout.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qformlayout.h
/src/gui/kernel/qformlayout.cpp