Qt 4.8: QSocks5SocketEnginePrivate Class Reference
QSocks5SocketEnginePrivate Class Reference
#include <qsocks5socketengine_p.h>
Public Types
enum Socks5Error {
SocksFailure = 0x01, ConnectionNotAllowed = 0x02, NetworkUnreachable = 0x03, HostUnreachable = 0x04,
ConnectionRefused = 0x05, TTLExpired = 0x06, CommandNotSupported = 0x07, AddressTypeNotSupported = 0x08,
LastKnownError = AddressTypeNotSupported, UnknownError
}
enum Socks5Mode { NoMode, ConnectMode, BindMode, UdpAssociateMode }
enum Socks5State {
Uninitialized = 0, ConnectError, AuthenticationMethodsSent, Authenticating,
AuthenticatingError, RequestMethodSent, RequestError, Connected,
UdpAssociateSuccess, BindSuccess, ControlSocketError, SocksError,
HostNameLookupError
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_controlSocketBytesWritten ()
void _q_controlSocketConnected ()
void _q_controlSocketDisconnected ()
void _q_controlSocketError (QAbstractSocket::SocketError)
void _q_controlSocketReadNotification ()
void _q_controlSocketStateChanged (QAbstractSocket::SocketState)
void _q_emitPendingConnectionNotification ()
void _q_emitPendingReadNotification ()
void _q_emitPendingWriteNotification ()
void _q_udpSocketReadNotification ()
void checkForDatagrams () const
void emitConnectionNotification ()
void emitReadNotification ()
void emitWriteNotification ()
void initialize (Socks5Mode socks5Mode)
void parseAuthenticatingReply ()
void parseAuthenticationMethodReply ()
void parseNewConnection ()
void parseRequestMethodReply ()
QSocks5SocketEnginePrivate ()
void reauthenticate ()
void sendRequestMethod ()
void setErrorState (Socks5State state, const QString &extraMessage=QString())
void setErrorState (Socks5State state, Socks5Error socks5error)
bool waitForConnected (int msecs, bool *timedOut)
~QSocks5SocketEnginePrivate ()
Public Functions inherited from QAbstractSocketEnginePrivate
QAbstractSocketEnginePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QSocks5BindData * bindData
QSocks5ConnectData * connectData
bool connectionNotificationPending
QSocks5Data * data
bool exceptNotificationEnabled
Socks5Mode mode
QString peerName
QNetworkProxy proxyInfo
bool readNotificationActivated
bool readNotificationEnabled
bool readNotificationPending
int socketDescriptor
Socks5State socks5State
QSocks5UdpAssociateData * udpData
bool writeNotificationActivated
bool writeNotificationEnabled
bool writeNotificationPending
Public Variables inherited from QAbstractSocketEnginePrivate
bool hasSetSocketError
QHostAddress localAddress
quint16 localPort
QHostAddress peerAddress
quint16 peerPort
QAbstractSocketEngineReceiver * receiver
QAbstractSocket::SocketError socketError
QString socketErrorString
QAbstractSocket::NetworkLayerProtocol socketProtocol
QAbstractSocket::SocketState socketState
QAbstractSocket::SocketType socketType
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 187 of file qsocks5socketengine_p.h.
Enumerations
Socks5Error
enum QSocks5SocketEnginePrivate::Socks5Error
Enumerator
SocksFailure
ConnectionNotAllowed
NetworkUnreachable
HostUnreachable
ConnectionRefused
TTLExpired
CommandNotSupported
AddressTypeNotSupported
LastKnownError
UnknownError
Definition at line 221 of file qsocks5socketengine_p.h.
     {
         SocksFailure = 0x01,
         ConnectionNotAllowed = 0x02,
         NetworkUnreachable = 0x03,
         HostUnreachable = 0x04,
         ConnectionRefused = 0x05,
         TTLExpired = 0x06,
         CommandNotSupported = 0x07,
         AddressTypeNotSupported = 0x08,
         LastKnownError = AddressTypeNotSupported,
         UnknownError
     };
Socks5Mode
enum QSocks5SocketEnginePrivate::Socks5Mode
Enumerator
NoMode
ConnectMode
BindMode
UdpAssociateMode
Definition at line 212 of file qsocks5socketengine_p.h.
     {
         NoMode,
         ConnectMode,
         BindMode,
         UdpAssociateMode
     };
Socks5State
enum QSocks5SocketEnginePrivate::Socks5State
Enumerator
Uninitialized
ConnectError
AuthenticationMethodsSent
Authenticating
AuthenticatingError
RequestMethodSent
RequestError
Connected
UdpAssociateSuccess
BindSuccess
ControlSocketError
SocksError
HostNameLookupError
Definition at line 194 of file qsocks5socketengine_p.h.
     {
         Uninitialized = 0,
         ConnectError,
         AuthenticationMethodsSent,
         Authenticating,
         AuthenticatingError,
         RequestMethodSent,
         RequestError,
         Connected,
         UdpAssociateSuccess,
         BindSuccess,
         ControlSocketError,
         SocksError,
         HostNameLookupError
     };
Constructors and Destructors
QSocks5SocketEnginePrivate()
QSocks5SocketEnginePrivate::QSocks5SocketEnginePrivate ()
Definition at line 521 of file qsocks5socketengine.cpp.
     : socks5State(Uninitialized)
     , readNotificationEnabled(false)
     , writeNotificationEnabled(false)
     , exceptNotificationEnabled(false)
     , socketDescriptor(-1)
     , data(0)
     , connectData(0)
 #ifndef QT_NO_UDPSOCKET
     , udpData(0)
 #endif
     , bindData(0)
     , readNotificationActivated(false)
     , writeNotificationActivated(false)
     , readNotificationPending(false)
     , writeNotificationPending(false)
     , connectionNotificationPending(false)
 {
     mode = NoMode;
 }
~QSocks5SocketEnginePrivate()
QSocks5SocketEnginePrivate::~QSocks5SocketEnginePrivate ()
Definition at line 542 of file qsocks5socketengine.cpp.
 {
 }
Functions
_q_controlSocketBytesWritten()
void QSocks5SocketEnginePrivate::_q_controlSocketBytesWritten ()
Definition at line 1219 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_DEBUG << "_q_controlSocketBytesWritten";
     if (socks5State != Connected
         || (mode == ConnectMode
         && data->controlSocket->bytesToWrite()))
         return;
     if (data->controlSocket->bytesToWrite() < MaxWriteBufferSize) {
         emitWriteNotification();
         writeNotificationActivated = false;
     }
 }
_q_controlSocketConnected()
void QSocks5SocketEnginePrivate::_q_controlSocketConnected ()
Definition at line 1160 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_DEBUG << "_q_controlSocketConnected";
     QByteArray buf(3, 0);
     buf[0] = S5_VERSION_5;
     buf[1] = 0x01;
     buf[2] = data->authenticator->methodId();
     data->controlSocket->write(buf);
     socks5State = AuthenticationMethodsSent;
 }
_q_controlSocketDisconnected()
void QSocks5SocketEnginePrivate::_q_controlSocketDisconnected ()
Definition at line 1264 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_D_DEBUG << "_q_controlSocketDisconnected";
 }
_q_controlSocketError()
void QSocks5SocketEnginePrivate::_q_controlSocketError (QAbstractSocket::SocketError error)
Definition at line 1233 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_D_DEBUG << "controlSocketError" << error << data->controlSocket->errorString();
     if (error == QAbstractSocket::SocketTimeoutError)
         return;                 // ignore this error -- comes from the waitFor* functions
     if (error == QAbstractSocket::RemoteHostClosedError
         && socks5State == Connected) {
         // clear the read buffer in connect mode so that bytes available returns 0
         // if there already is a read notification pending then this will be processed first
         if (!readNotificationPending)
             connectData->readBuffer.clear();
         emitReadNotification();
         data->controlSocket->close();
         // cause a disconnect in the outer socket
         emitWriteNotification();
     } else if (socks5State == Uninitialized
                || socks5State == AuthenticationMethodsSent
                || socks5State == Authenticating
                || socks5State == RequestMethodSent) {
         setErrorState(socks5State == Uninitialized ? ConnectError : ControlSocketError);
         data->controlSocket->close();
         emitConnectionNotification();
     } else {
         q_func()->setError(data->controlSocket->error(), data->controlSocket->errorString());
         emitReadNotification();
         emitWriteNotification();
     }
 }
_q_controlSocketReadNotification()
void QSocks5SocketEnginePrivate::_q_controlSocketReadNotification ()
Definition at line 1171 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_D_DEBUG << "_q_controlSocketReadNotification socks5state" <<  s5StateToString(socks5State)
                     << "bytes available" << data->controlSocket->bytesAvailable();
     if (data->controlSocket->bytesAvailable() == 0) {
         QSOCKS5_D_DEBUG << "########## bogus read why do we get these ... on windows only";
         return;
     }
     switch (socks5State) {
         case AuthenticationMethodsSent:
             parseAuthenticationMethodReply();
             break;
         case Authenticating:
             parseAuthenticatingReply();
             break;
         case RequestMethodSent:
             parseRequestMethodReply();
             break;
         case Connected: {
             QByteArray buf;
             if (!data->authenticator->unSeal(data->controlSocket, &buf)) {
                 // qDebug() << "unseal error maybe need to wait for more data";
             }
             if (buf.size()) {
                 QSOCKS5_DEBUG << dump(buf);
                 connectData->readBuffer += buf;
                 emitReadNotification();
             }
             break;
         }
         case BindSuccess:
             // only get here if command is bind
             if (mode == BindMode) {
                 parseRequestMethodReply();
                 break;
             }
             // fall through
         default:
             qWarning("QSocks5SocketEnginePrivate::_q_controlSocketReadNotification: "
                      "Unexpectedly received data while in state=%d and mode=%d",
                      socks5State, mode);
             break;
     };
 }
_q_controlSocketStateChanged()
void QSocks5SocketEnginePrivate::_q_controlSocketStateChanged (QAbstractSocket::SocketState state)
Definition at line 1269 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_D_DEBUG << "_q_controlSocketStateChanged" << state;
 }
_q_emitPendingConnectionNotification()
void QSocks5SocketEnginePrivate::_q_emitPendingConnectionNotification ()
Definition at line 970 of file qsocks5socketengine.cpp.
 {
     connectionNotificationPending = false;
     Q_Q(QSocks5SocketEngine);
     QSOCKS5_D_DEBUG << "emitting connectionNotification";
     emit q->connectionNotification();
 }
_q_emitPendingReadNotification()
void QSocks5SocketEnginePrivate::_q_emitPendingReadNotification ()
Definition at line 919 of file qsocks5socketengine.cpp.
 {
     Q_Q(QSocks5SocketEngine);
     readNotificationPending = false;
     if (readNotificationEnabled) {
         QSOCKS5_D_DEBUG << "emitting readNotification";
         QPointer<QSocks5SocketEngine> qq = q;
         emit q->readNotification();
         if (!qq)
             return;
         // check if there needs to be a new zero read notification
         if (data && data->controlSocket->state() == QAbstractSocket::UnconnectedState
                 && data->controlSocket->error() == QAbstractSocket::RemoteHostClosedError) {
             connectData->readBuffer.clear();
             emitReadNotification();
         }
     }
 }
_q_emitPendingWriteNotification()
void QSocks5SocketEnginePrivate::_q_emitPendingWriteNotification ()
Definition at line 949 of file qsocks5socketengine.cpp.
 {
     writeNotificationPending = false;
     Q_Q(QSocks5SocketEngine);
     if (writeNotificationEnabled) {
         QSOCKS5_D_DEBUG << "emitting writeNotification";
         emit q->writeNotification();
     }
 }
_q_udpSocketReadNotification()
void QSocks5SocketEnginePrivate::_q_udpSocketReadNotification ()
Definition at line 1282 of file qsocks5socketengine.cpp.
Referenced by initialize().
 {
     QSOCKS5_D_DEBUG << "_q_udpSocketReadNotification()";
     // check some state stuff
     if (!udpData->udpSocket->hasPendingDatagrams()) {
         QSOCKS5_D_DEBUG << "false read ??";
         return;
     }
     while (udpData->udpSocket->hasPendingDatagrams()) {
         QByteArray sealedBuf(udpData->udpSocket->pendingDatagramSize(), 0);
         QSOCKS5_D_DEBUG << "new datagram";
         udpData->udpSocket->readDatagram(sealedBuf.data(), sealedBuf.size());
         QByteArray inBuf;
         if (!data->authenticator->unSeal(sealedBuf, &inBuf)) {
             QSOCKS5_D_DEBUG << "failed unsealing datagram discarding";
             return;
         }
         QSOCKS5_DEBUG << dump(inBuf);
         int pos = 0;
         const char *buf = inBuf.constData();
         if (inBuf.size() < 4) {
             QSOCKS5_D_DEBUG << "bugus udp data, discarding";
             return;
         }
         QSocks5RevivedDatagram datagram;
         if (buf[pos++] != 0 || buf[pos++] != 0) {
             QSOCKS5_D_DEBUG << "invalid datagram discarding";
             return;
         }
         if (buf[pos++] != 0) { //### add fragmentation reading support
             QSOCKS5_D_DEBUG << "don't support fragmentation yet disgarding";
             return;
         }
         if (!qt_socks5_get_host_address_and_port(inBuf, &datagram.address, &datagram.port, &pos)) {
             QSOCKS5_D_DEBUG << "failed to get address from datagram disgarding";
             return;
         }
         datagram.data = QByteArray(&buf[pos], inBuf.size() - pos);
         udpData->pendingDatagrams.enqueue(datagram);
     }
     emitReadNotification();
 }
checkForDatagrams()
void QSocks5SocketEnginePrivate::checkForDatagrams () const
Definition at line 1275 of file qsocks5socketengine.cpp.
 {
     // udp should be unbuffered so we need to do some polling at certain points
     if (udpData->udpSocket->hasPendingDatagrams())
         const_cast<QSocks5SocketEnginePrivate *>(this)->_q_udpSocketReadNotification();
 }
emitConnectionNotification()
void QSocks5SocketEnginePrivate::emitConnectionNotification ()
Definition at line 978 of file qsocks5socketengine.cpp.
Referenced by parseAuthenticationMethodReply(), parseRequestMethodReply(), and reauthenticate().
 {
     Q_Q(QSocks5SocketEngine);
     QSOCKS5_D_DEBUG << "queueing connectionNotification";
     connectionNotificationPending = true;
     QMetaObject::invokeMethod(q, "_q_emitPendingConnectionNotification", Qt::QueuedConnection);
 }
emitReadNotification()
void QSocks5SocketEnginePrivate::emitReadNotification ()
Definition at line 938 of file qsocks5socketengine.cpp.
Referenced by _q_emitPendingReadNotification(), and parseRequestMethodReply().
 {
     Q_Q(QSocks5SocketEngine);
     readNotificationActivated = true;
     if (readNotificationEnabled && !readNotificationPending) {
         QSOCKS5_D_DEBUG << "queueing readNotification";
         readNotificationPending = true;
         QMetaObject::invokeMethod(q, "_q_emitPendingReadNotification", Qt::QueuedConnection);
     }
 }
emitWriteNotification()
void QSocks5SocketEnginePrivate::emitWriteNotification ()
Definition at line 959 of file qsocks5socketengine.cpp.
 {
     Q_Q(QSocks5SocketEngine);
     writeNotificationActivated = true;
     if (writeNotificationEnabled && !writeNotificationPending) {
         QSOCKS5_D_DEBUG << "queueing writeNotification";
         writeNotificationPending = true;
         QMetaObject::invokeMethod(q, "_q_emitPendingWriteNotification", Qt::QueuedConnection);
     }
 }
initialize()
void QSocks5SocketEnginePrivate::initialize (Socks5Mode socks5Mode)
Definition at line 546 of file qsocks5socketengine.cpp.
 {
     Q_Q(QSocks5SocketEngine);
     mode = socks5Mode;
     if (mode == ConnectMode) {
         connectData = new QSocks5ConnectData;
         data = connectData;
 #ifndef QT_NO_UDPSOCKET
     } else if (mode == UdpAssociateMode) {
         udpData = new QSocks5UdpAssociateData;
         data = udpData;
         udpData->udpSocket = new QUdpSocket(q);
 #ifndef QT_NO_BEARERMANAGEMENT
         udpData->udpSocket->setProperty("_q_networksession", q->property("_q_networksession"));
 #endif
         udpData->udpSocket->setProxy(QNetworkProxy::NoProxy);
         QObject::connect(udpData->udpSocket, SIGNAL(readyRead()),
                          q, SLOT(_q_udpSocketReadNotification()),
                          Qt::DirectConnection);
 #endif // QT_NO_UDPSOCKET
     } else if (mode == BindMode) {
         bindData = new QSocks5BindData;
         data = bindData;
     }
     data->controlSocket = new QTcpSocket(q);
 #ifndef QT_NO_BEARERMANAGEMENT
     data->controlSocket->setProperty("_q_networksession", q->property("_q_networksession"));
 #endif
     data->controlSocket->setProxy(QNetworkProxy::NoProxy);
     QObject::connect(data->controlSocket, SIGNAL(connected()), q, SLOT(_q_controlSocketConnected()),
                      Qt::DirectConnection);
     QObject::connect(data->controlSocket, SIGNAL(readyRead()), q, SLOT(_q_controlSocketReadNotification()),
                      Qt::DirectConnection);
     QObject::connect(data->controlSocket, SIGNAL(bytesWritten(qint64)), q, SLOT(_q_controlSocketBytesWritten()),
                      Qt::DirectConnection);
     QObject::connect(data->controlSocket, SIGNAL(error(QAbstractSocket::SocketError)),
                      q, SLOT(_q_controlSocketError(QAbstractSocket::SocketError)),
                      Qt::DirectConnection);
     QObject::connect(data->controlSocket, SIGNAL(disconnected()), q, SLOT(_q_controlSocketDisconnected()),
                      Qt::DirectConnection);
     QObject::connect(data->controlSocket, SIGNAL(stateChanged(QAbstractSocket::SocketState)),
                      q, SLOT(_q_controlSocketStateChanged(QAbstractSocket::SocketState)),
                      Qt::DirectConnection);
     if (!proxyInfo.user().isEmpty() || !proxyInfo.password().isEmpty()) {
         QSOCKS5_D_DEBUG << "using username/password authentication; user =" << proxyInfo.user();
         data->authenticator = new QSocks5PasswordAuthenticator(proxyInfo.user(), proxyInfo.password());
     } else {
         QSOCKS5_D_DEBUG << "not using authentication";
         data->authenticator = new QSocks5Authenticator();
     }
 }
parseAuthenticatingReply()
void QSocks5SocketEnginePrivate::parseAuthenticatingReply ()
Definition at line 788 of file qsocks5socketengine.cpp.
 {
     bool authComplete = false;
     if (!data->authenticator->continueAuthenticate(data->controlSocket, &authComplete)) {
         reauthenticate();
         return;
     }
     if (authComplete)
         sendRequestMethod();
 }
parseAuthenticationMethodReply()
void QSocks5SocketEnginePrivate::parseAuthenticationMethodReply ()
Definition at line 753 of file qsocks5socketengine.cpp.
 {
     // not enough data to begin
     if (data->controlSocket->bytesAvailable() < 2)
         return;
     QByteArray buf = data->controlSocket->read(2);
     if (buf.at(0) != S5_VERSION_5) {
         QSOCKS5_D_DEBUG << "Socks5 version incorrect";
         setErrorState(SocksError);
         data->controlSocket->close();
         emitConnectionNotification();
         return;
     }
     bool authComplete = false;
     if (uchar(buf.at(1)) == S5_AUTHMETHOD_NONE) {
         authComplete = true;
     } else if (uchar(buf.at(1)) == S5_AUTHMETHOD_NOTACCEPTABLE) {
         reauthenticate();
         return;
     } else if (buf.at(1) != data->authenticator->methodId()
                || !data->authenticator->beginAuthenticate(data->controlSocket, &authComplete)) {
         setErrorState(AuthenticatingError, QLatin1String("Socks5 host did not support authentication method."));
         socketError = QAbstractSocket::SocketAccessError; // change the socket error
         emitConnectionNotification();
         return;
     }
     if (authComplete)
         sendRequestMethod();
     else
         socks5State = Authenticating;
 }
parseNewConnection()
void QSocks5SocketEnginePrivate::parseNewConnection ()
parseRequestMethodReply()
void QSocks5SocketEnginePrivate::parseRequestMethodReply ()
Definition at line 844 of file qsocks5socketengine.cpp.
 {
     Q_Q(QSocks5SocketEngine);
     QSOCKS5_DEBUG << "parseRequestMethodReply()";
     QByteArray inBuf;
     if (!data->authenticator->unSeal(data->controlSocket, &inBuf)) {
         // ### check error and not just not enough data
         QSOCKS5_DEBUG << "unSeal failed, needs more data";
         return;
     }
     QSOCKS5_DEBUG << dump(inBuf);
     if (inBuf.size() < 2) {
         QSOCKS5_DEBUG << "need more data for request reply header .. put this data somewhere";
         return;
     }
     QHostAddress address;
     quint16 port = 0;
     if (inBuf.at(0) != S5_VERSION_5 || inBuf.length() < 3 || inBuf.at(2) != 0x00) {
         QSOCKS5_DEBUG << "socks protocol error";
         setErrorState(SocksError);
     } else if (inBuf.at(1) != S5_SUCCESS) {
         Socks5Error socks5Error = Socks5Error(inBuf.at(1));
         QSOCKS5_DEBUG <<  "Request error :" << socks5Error;
         if ((socks5Error == SocksFailure || socks5Error == ConnectionNotAllowed)
             && !peerName.isEmpty()) {
             // Dante seems to use this error code to indicate hostname resolution failure
             setErrorState(HostNameLookupError);
         } else {
             setErrorState(RequestError, socks5Error);
         }
     } else {
         // connection success, retrieve the remote addresses
         int pos = 3;
         if (!qt_socks5_get_host_address_and_port(inBuf, &address, &port, &pos)) {
             QSOCKS5_DEBUG << "error getting address";
             setErrorState(SocksError);
         } else {
             inBuf.remove(0, pos);
             for (int i = inBuf.size() - 1; i >= 0 ; --i)
                 data->controlSocket->ungetChar(inBuf.at(i));
         }
     }
     if (socks5State == RequestMethodSent) {
         // no error
         localAddress = address;
         localPort = port;
         if (mode == ConnectMode) {
             socks5State = Connected;
             // notify the upper layer that we're done
             q->setState(QAbstractSocket::ConnectedState);
             emitConnectionNotification();
         } else if (mode == BindMode) {
             socks5State = BindSuccess;
             q->setState(QAbstractSocket::ListeningState);
         } else {
             socks5State = UdpAssociateSuccess;
         }
     } else if (socks5State == BindSuccess) {
         // no error and we got a connection
         bindData->peerAddress = address;
         bindData->peerPort = port;
         emitReadNotification();
     } else {
         // got an error
         data->controlSocket->close();
         emitConnectionNotification();
     }
 }
reauthenticate()
void QSocks5SocketEnginePrivate::reauthenticate ()
Definition at line 722 of file qsocks5socketengine.cpp.
Referenced by parseAuthenticatingReply(), and parseAuthenticationMethodReply().
 {
     Q_Q(QSocks5SocketEngine);
     // we require authentication
     QAuthenticator auth;
     emit q->proxyAuthenticationRequired(proxyInfo, &auth);
     if (!auth.user().isEmpty() || !auth.password().isEmpty()) {
         // we have new credentials, let's try again
         QSOCKS5_DEBUG << "authentication failure: retrying connection";
         socks5State = QSocks5SocketEnginePrivate::Uninitialized;
         delete data->authenticator;
         proxyInfo.setUser(auth.user());
         proxyInfo.setPassword(auth.password());
         data->authenticator = new QSocks5PasswordAuthenticator(proxyInfo.user(), proxyInfo.password());
         data->controlSocket->blockSignals(true);
         data->controlSocket->abort();
         data->controlSocket->blockSignals(false);
         data->controlSocket->connectToHost(proxyInfo.hostName(), proxyInfo.port());
     } else {
         // authentication failure
         setErrorState(AuthenticatingError);
         data->controlSocket->close();
         emitConnectionNotification();
     }
 }
sendRequestMethod()
void QSocks5SocketEnginePrivate::sendRequestMethod ()
Definition at line 799 of file qsocks5socketengine.cpp.
Referenced by parseAuthenticatingReply(), and parseAuthenticationMethodReply().
 {
     QHostAddress address;
     quint16 port = 0;
     char command = 0;
     if (mode == ConnectMode) {
         command = S5_CONNECT;
         address = peerAddress;
         port = peerPort;
     } else if (mode == BindMode) {
         command = S5_BIND;
         address = localAddress;
         port = localPort;
     } else {
 #ifndef QT_NO_UDPSOCKET
         command = S5_UDP_ASSOCIATE;
         address = localAddress; //data->controlSocket->localAddress();
         port = localPort;
 #endif
     }
     QByteArray buf;
     buf.reserve(270); // big enough for domain name;
     buf[0] = S5_VERSION_5;
     buf[1] = command;
     buf[2] = 0x00;
     if (peerName.isEmpty() && !qt_socks5_set_host_address_and_port(address, port, &buf)) {
         QSOCKS5_DEBUG << "error setting address" << address << " : " << port;
         //### set error code ....
         return;
     } else if (!peerName.isEmpty() && !qt_socks5_set_host_name_and_port(peerName, port, &buf)) {
         QSOCKS5_DEBUG << "error setting address" << address << " : " << port;
         //### set error code ....
         return;
     }
     QSOCKS5_DEBUG << "sending" << dump(buf);
     QByteArray sealedBuf;
     if (!data->authenticator->seal(buf, &sealedBuf)) {
         // ### Handle this error.
     }
     data->controlSocket->write(sealedBuf);
     data->controlSocket->flush();
     socks5State = RequestMethodSent;
 }
setErrorState() [1/2]
void QSocks5SocketEnginePrivate::setErrorState (Socks5State state, const QString & extraMessage = QString())
Definition at line 601 of file qsocks5socketengine.cpp.
Referenced by parseAuthenticationMethodReply(), parseRequestMethodReply(), reauthenticate(), and setErrorState().
 {
     Q_Q(QSocks5SocketEngine);
     switch (state) {
     case Uninitialized:
     case Authenticating:
     case AuthenticationMethodsSent:
     case RequestMethodSent:
     case Connected:
     case UdpAssociateSuccess:
     case BindSuccess:
         // these aren't error states
         return;
     case ConnectError:
     case ControlSocketError: {
         QAbstractSocket::SocketError controlSocketError = data->controlSocket->error();
         if (socks5State != Connected) {
             switch (controlSocketError) {
             case QAbstractSocket::ConnectionRefusedError:
                 q->setError(QAbstractSocket::ProxyConnectionRefusedError,
                              QSocks5SocketEngine::tr("Connection to proxy refused"));
                 break;
             case QAbstractSocket::RemoteHostClosedError:
                 q->setError(QAbstractSocket::ProxyConnectionClosedError,
                              QSocks5SocketEngine::tr("Connection to proxy closed prematurely"));
                 break;
             case QAbstractSocket::HostNotFoundError:
                 q->setError(QAbstractSocket::ProxyNotFoundError,
                              QSocks5SocketEngine::tr("Proxy host not found"));
                 break;
             case QAbstractSocket::SocketTimeoutError:
                 if (state == ConnectError) {
                     q->setError(QAbstractSocket::ProxyConnectionTimeoutError,
                                  QSocks5SocketEngine::tr("Connection to proxy timed out"));
                     break;
                 }
                 /* fall through */
             default:
                 q->setError(controlSocketError, data->controlSocket->errorString());
                 break;
             }
         } else {
             q->setError(controlSocketError, data->controlSocket->errorString());
         }
         break;
     }
     case AuthenticatingError:
         q->setError(QAbstractSocket::ProxyAuthenticationRequiredError,
                     extraMessage.isEmpty() ?
                      QSocks5SocketEngine::tr("Proxy authentication failed") :
                      QSocks5SocketEngine::tr("Proxy authentication failed: %1").arg(extraMessage));
         break;
     case RequestError:
         // error code set by caller (overload)
         break;
     case SocksError:
         q->setError(QAbstractSocket::ProxyProtocolError,
                      QSocks5SocketEngine::tr("SOCKS version 5 protocol error"));
         break;
     case HostNameLookupError:
         q->setError(QAbstractSocket::HostNotFoundError,
                     QAbstractSocket::tr("Host not found"));
         break;
     }
     q->setState(QAbstractSocket::UnconnectedState);
     socks5State = state;
 }
setErrorState() [2/2]
void QSocks5SocketEnginePrivate::setErrorState (Socks5State state, Socks5Error socks5error)
Definition at line 676 of file qsocks5socketengine.cpp.
 {
     Q_Q(QSocks5SocketEngine);
     switch (socks5error) {
     case SocksFailure:
         q->setError(QAbstractSocket::NetworkError,
                      QSocks5SocketEngine::tr("General SOCKSv5 server failure"));
         break;
     case ConnectionNotAllowed:
         q->setError(QAbstractSocket::SocketAccessError,
                      QSocks5SocketEngine::tr("Connection not allowed by SOCKSv5 server"));
         break;
     case NetworkUnreachable:
         q->setError(QAbstractSocket::NetworkError,
                     QAbstractSocket::tr("Network unreachable"));
         break;
     case HostUnreachable:
         q->setError(QAbstractSocket::HostNotFoundError,
                     QAbstractSocket::tr("Host not found"));
         break;
     case ConnectionRefused:
         q->setError(QAbstractSocket::ConnectionRefusedError,
                     QAbstractSocket::tr("Connection refused"));
         break;
     case TTLExpired:
         q->setError(QAbstractSocket::NetworkError,
                      QSocks5SocketEngine::tr("TTL expired"));
         break;
     case CommandNotSupported:
         q->setError(QAbstractSocket::UnsupportedSocketOperationError,
                      QSocks5SocketEngine::tr("SOCKSv5 command not supported"));
         break;
     case AddressTypeNotSupported:
         q->setError(QAbstractSocket::UnsupportedSocketOperationError,
                      QSocks5SocketEngine::tr("Address type not supported"));
         break;
     default:
         q->setError(QAbstractSocket::UnknownSocketError,
                      QSocks5SocketEngine::tr("Unknown SOCKSv5 proxy error code 0x%1").arg(int(socks5error), 16));
         break;
     }
     setErrorState(state, QString());
 }
waitForConnected()
bool QSocks5SocketEnginePrivate::waitForConnected (int msecs, bool * timedOut)
Definition at line 1715 of file qsocks5socketengine.cpp.
 {
     if (data->controlSocket->state() == QAbstractSocket::UnconnectedState)
         return false;
     const Socks5State wantedState =
         mode == ConnectMode ? Connected :
         mode == BindMode ? BindSuccess :
         UdpAssociateSuccess;
     QElapsedTimer stopWatch;
     stopWatch.start();
     while (socks5State != wantedState) {
         if (!data->controlSocket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
             if (data->controlSocket->state() == QAbstractSocket::UnconnectedState)
                 return true;
             setErrorState(QSocks5SocketEnginePrivate::ControlSocketError);
             if (timedOut && data->controlSocket->error() == QAbstractSocket::SocketTimeoutError)
                 *timedOut = true;
             return false;
         }
     }
     return true;
 }
Properties
bindData
QSocks5BindData* QSocks5SocketEnginePrivate::bindData
Definition at line 271 of file qsocks5socketengine_p.h.
Referenced by initialize(), and parseRequestMethodReply().
connectData
QSocks5ConnectData* QSocks5SocketEnginePrivate::connectData
Definition at line 267 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingReadNotification(), and initialize().
connectionNotificationPending
bool QSocks5SocketEnginePrivate::connectionNotificationPending
Definition at line 283 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingConnectionNotification(), and emitConnectionNotification().
data
QSocks5Data* QSocks5SocketEnginePrivate::data
Definition at line 266 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingReadNotification(), initialize(), parseAuthenticatingReply(), parseAuthenticationMethodReply(), parseRequestMethodReply(), reauthenticate(), sendRequestMethod(), and setErrorState().
exceptNotificationEnabled
bool QSocks5SocketEnginePrivate::exceptNotificationEnabled
Definition at line 262 of file qsocks5socketengine_p.h.
mode
Socks5Mode QSocks5SocketEnginePrivate::mode
Definition at line 219 of file qsocks5socketengine_p.h.
Referenced by initialize(), parseRequestMethodReply(), QSocks5SocketEnginePrivate(), and sendRequestMethod().
peerName
QString QSocks5SocketEnginePrivate::peerName
Definition at line 272 of file qsocks5socketengine_p.h.
Referenced by parseRequestMethodReply(), and sendRequestMethod().
proxyInfo
QNetworkProxy QSocks5SocketEnginePrivate::proxyInfo
Definition at line 260 of file qsocks5socketengine_p.h.
Referenced by initialize(), and reauthenticate().
readNotificationActivated
bool QSocks5SocketEnginePrivate::readNotificationActivated mutable
Definition at line 274 of file qsocks5socketengine_p.h.
Referenced by emitReadNotification().
readNotificationEnabled
bool QSocks5SocketEnginePrivate::readNotificationEnabled
Definition at line 262 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingReadNotification(), and emitReadNotification().
readNotificationPending
bool QSocks5SocketEnginePrivate::readNotificationPending
Definition at line 277 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingReadNotification(), and emitReadNotification().
socketDescriptor
int QSocks5SocketEnginePrivate::socketDescriptor
Definition at line 264 of file qsocks5socketengine_p.h.
socks5State
Socks5State QSocks5SocketEnginePrivate::socks5State
Definition at line 210 of file qsocks5socketengine_p.h.
Referenced by parseAuthenticationMethodReply(), parseRequestMethodReply(), reauthenticate(), sendRequestMethod(), and setErrorState().
udpData
QSocks5UdpAssociateData* QSocks5SocketEnginePrivate::udpData
Definition at line 269 of file qsocks5socketengine_p.h.
Referenced by initialize().
writeNotificationActivated
bool QSocks5SocketEnginePrivate::writeNotificationActivated mutable
Definition at line 275 of file qsocks5socketengine_p.h.
Referenced by emitWriteNotification().
writeNotificationEnabled
bool QSocks5SocketEnginePrivate::writeNotificationEnabled
Definition at line 262 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingWriteNotification(), and emitWriteNotification().
writeNotificationPending
bool QSocks5SocketEnginePrivate::writeNotificationPending
Definition at line 280 of file qsocks5socketengine_p.h.
Referenced by _q_emitPendingWriteNotification(), and emitWriteNotification().
The documentation for this class was generated from the following files:
/src/network/socket/qsocks5socketengine_p.h
/src/network/socket/qsocks5socketengine.cpp