Qt 4.8: QDrag Class Reference
QDrag Class Reference
The QDrag class provides support for MIME-based drag and drop data transfer.
#include <qdrag.h>
Signals
void actionChanged (Qt::DropAction action)
This signal is emitted when the action associated with the drag changes.
void targetChanged (QWidget *newTarget)
This signal is emitted when the target of the drag and drop operation changes, with newTarget the new target.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::DropAction exec (Qt::DropActions supportedActions=Qt::MoveAction)
Starts the drag and drop operation and returns a value indicating the requested drop action when it is completed.
Qt::DropAction exec (Qt::DropActions supportedActions, Qt::DropAction defaultAction)
Starts the drag and drop operation and returns a value indicating the requested drop action when it is completed.
QPoint hotSpot () const
Returns the position of the hot spot relative to the top-left corner of the cursor.
QMimeData * mimeData () const
Returns the MIME data that is encapsulated by the drag object.
QPixmap pixmap () const
Returns the pixmap used to represent the data in a drag and drop operation.
QDrag (QWidget *dragSource)
Constructs a new drag object for the widget specified by dragSource.
void setDragCursor (const QPixmap &cursor, Qt::DropAction action)
Sets the drag cursor for the action.
void setHotSpot (const QPoint &hotspot)
Sets the position of the hot spot relative to the top-left corner of the pixmap used to the point specified by hotspot.
void setMimeData (QMimeData *data)
Sets the data to be sent to the given MIME data.
void setPixmap (const QPixmap &)
Sets pixmap as the pixmap used to represent the data in a drag and drop operation.
QWidget * source () const
Returns the source of the drag object.
Qt::DropAction start (Qt::DropActions supportedActions=Qt::CopyAction)
Starts the drag and drop operation and returns a value indicating the requested drop action when it is completed.
QWidget * target () const
Returns the target of the drag and drop operation.
~QDrag ()
Destroys the drag object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Friends
class QDragManager
class QWidgetPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDrag class provides support for MIME-based drag and drop data transfer.
Drag and drop is an intuitive way for users to copy or move data around in an application, and is used in many desktop environments as a mechanism for copying data between applications. Drag and drop support in Qt is centered around the QDrag class that handles most of the details of a drag and drop operation.
The data to be transferred by the drag and drop operation is contained in a QMimeData object. This is specified with the setMimeData() function in the following way:
        QDrag *drag = new QDrag(this);
        QMimeData *mimeData = new QMimeData;
        mimeData->setText(commentEdit->toPlainText());
        drag->setMimeData(mimeData);
Note that setMimeData() assigns ownership of the QMimeData object to the QDrag object. The QDrag must be constructed on the heap with a parent QWidget to ensure that Qt can clean up after the drag and drop operation has been completed.
A pixmap can be used to represent the data while the drag is in progress, and will move with the cursor to the drop target. This pixmap typically shows an icon that represents the MIME type of the data being transferred, but any pixmap can be set with setPixmap(). The cursor's hot spot can be given a position relative to the top-left corner of the pixmap with the setHotSpot() function. The following code positions the pixmap so that the cursor's hot spot points to the center of its bottom edge:
    drag->setHotSpot(QPoint(drag->pixmap().width()/2,
                            drag->pixmap().height()));
Note
On X11, the pixmap may not be able to keep up with the mouse movements if the hot spot causes the pixmap to be displayed directly under the cursor.
The source and target widgets can be found with source() and target(). These functions are often used to determine whether drag and drop operations started and finished at the same widget, so that special behavior can be implemented.
QDrag only deals with the drag and drop operation itself. It is up to the developer to decide when a drag operation begins, and how a QDrag object should be constructed and used. For a given widget, it is often necessary to reimplement mousePressEvent() to determine whether the user has pressed a mouse button, and reimplement mouseMoveEvent() to check whether a QDrag is required.
See also
{Drag and Drop}, QClipboard, QMimeData, QWindowsMime, QMacPasteboardMime, {Draggable Icons Example}, {Draggable Text Example}, {Drop Site Example}, {Fridge Magnets Example}
Definition at line 61 of file qdrag.h.
Constructors and Destructors
QDrag()
QDrag::QDrag (QWidget * dragSource) explicit
Constructs a new drag object for the widget specified by dragSource.
Definition at line 113 of file qdrag.cpp.
     : QObject(*new QDragPrivate, dragSource)
 {
     Q_D(QDrag);
     d->source = dragSource;
     d->target = 0;
     d->data = 0;
     d->hotspot = QPoint(-10, -10);
     d->possible_actions = Qt::CopyAction;
     d->executed_action = Qt::IgnoreAction;
     d->defaultDropAction = Qt::IgnoreAction;
 }
~QDrag()
QDrag::~QDrag ()
Destroys the drag object.
Definition at line 129 of file qdrag.cpp.
 {
     Q_D(QDrag);
     delete d->data;
     QDragManager *manager = QDragManager::self();
     if (manager && manager->object == this)
         manager->cancel(false);
 }
Functions
actionChanged
void QDrag::actionChanged (Qt::DropAction action) signal
This signal is emitted when the action associated with the drag changes.
See also
targetChanged()
exec() [1/2]
Qt::DropAction QDrag::exec (Qt::DropActions supportedActions = Qt::MoveAction)
Starts the drag and drop operation and returns a value indicating the requested drop action when it is completed.
Since
4.3
The drop actions that the user can choose from are specified in supportedActions. The default proposed action will be selected among the allowed actions in the following order: Move, Copy and Link.
Note: On Linux and Mac OS X, the drag and drop operation can take some time, but this function does not block the event loop. Other events are still delivered to the application while the operation is performed. On Windows, the Qt event loop is blocked while during the operation.
Definition at line 243 of file qdrag.cpp.
Referenced by QIconModeViewBase::filterStartDrag(), QmlJSDebugger::ToolBarColorBox::mouseMoveEvent(), QTextControlPrivate::startDrag(), and QAbstractItemView::startDrag().
 {
     return exec(supportedActions, Qt::IgnoreAction);
 }
exec() [2/2]
Qt::DropAction QDrag::exec (Qt::DropActions supportedActions, Qt::DropAction defaultDropAction)
Starts the drag and drop operation and returns a value indicating the requested drop action when it is completed.
Since
4.3
The drop actions that the user can choose from are specified in supportedActions.
The defaultDropAction determines which action will be proposed when the user performs a drag without using modifier keys.
Note: On Linux and Mac OS X, the drag and drop operation can take some time, but this function does not block the event loop. Other events are still delivered to the application while the operation is performed. On Windows, the Qt event loop is blocked during the operation. However, QDrag::exec() on Windows causes processEvents() to be called frequently to keep the GUI responsive. If any loops or operations are called while a drag operation is active, it will block the drag operation.
Definition at line 270 of file qdrag.cpp.
 {
     Q_D(QDrag);
     if (!d->data) {
         qWarning("QDrag: No mimedata set before starting the drag");
         return d->executed_action;
     }
     QDragManager *manager = QDragManager::self();
     d->defaultDropAction = Qt::IgnoreAction;
     d->possible_actions = supportedActions;
     if (manager) {
         if (defaultDropAction == Qt::IgnoreAction) {
             if (supportedActions & Qt::MoveAction) {
                 d->defaultDropAction = Qt::MoveAction;
             } else if (supportedActions & Qt::CopyAction) {
                 d->defaultDropAction = Qt::CopyAction;
             } else if (supportedActions & Qt::LinkAction) {
                 d->defaultDropAction = Qt::LinkAction;
             }
         } else {
             d->defaultDropAction = defaultDropAction;
         }
         d->executed_action = manager->drag(this);
     }
     return d->executed_action;
 }
hotSpot()
QPoint QDrag::hotSpot () const
Returns the position of the hot spot relative to the top-left corner of the cursor.
Definition at line 199 of file qdrag.cpp.
Referenced by QOleDropSource::createCursors().
 {
     Q_D(const QDrag);
     return d->hotspot;
 }
mimeData()
QMimeData * QDrag::mimeData () const
Returns the MIME data that is encapsulated by the drag object.
Definition at line 155 of file qdrag.cpp.
Referenced by QDragManager::drag(), and QOleDropTarget::Drop().
 {
     Q_D(const QDrag);
     return d->data;
 }
pixmap()
QPixmap QDrag::pixmap () const
Returns the pixmap used to represent the data in a drag and drop operation.
Definition at line 175 of file qdrag.cpp.
Referenced by QOleDropSource::createCursors(), and setPixmap().
 {
     Q_D(const QDrag);
     return d->pixmap;
 }
setDragCursor()
void QDrag::setDragCursor (const QPixmap & cursor, Qt::DropAction action)
Sets the drag cursor for the action.
This allows you to override the default native cursors. To revert to using the native cursor for action pass in a null QPixmap as cursor.
The action can only be CopyAction, MoveAction or LinkAction. All other values of DropAction are ignored.
Definition at line 340 of file qdrag.cpp.
 {
     Q_D(QDrag);
     if (action != Qt::CopyAction && action != Qt::MoveAction && action != Qt::LinkAction)
         return;
     if (cursor.isNull())
         d->customCursors.remove(action);
     else
         d->customCursors[action] = cursor;
 }
setHotSpot()
void QDrag::setHotSpot (const QPoint & hotspot)
Sets the position of the hot spot relative to the top-left corner of the pixmap used to the point specified by hotspot.
Note: on X11, the pixmap may not be able to keep up with the mouse movements if the hot spot causes the pixmap to be displayed directly under the cursor.
Definition at line 189 of file qdrag.cpp.
Referenced by QIconModeViewBase::filterStartDrag(), and QAbstractItemView::startDrag().
 {
     Q_D(QDrag);
     d->hotspot = hotspot;
 }
setMimeData()
void QDrag::setMimeData (QMimeData * data)
Sets the data to be sent to the given MIME data.
Ownership of the data is transferred to the QDrag object.
Definition at line 142 of file qdrag.cpp.
Referenced by QLineEditPrivate::drag(), QDragManager::drag(), QOleDropTarget::Drop(), QIconModeViewBase::filterStartDrag(), QmlJSDebugger::ToolBarColorBox::mouseMoveEvent(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QTextControlPrivate::startDrag(), and QAbstractItemView::startDrag().
 {
     Q_D(QDrag);
     if (d->data == data)
         return;
     if (d->data != 0)
         delete d->data;
     d->data = data;
 }
setPixmap()
void QDrag::setPixmap (const QPixmap & pixmap)
Sets pixmap as the pixmap used to represent the data in a drag and drop operation.
You can only set a pixmap before the drag is started.
Definition at line 166 of file qdrag.cpp.
Referenced by QIconModeViewBase::filterStartDrag(), QmlJSDebugger::ToolBarColorBox::mouseMoveEvent(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), and QAbstractItemView::startDrag().
 {
     Q_D(QDrag);
     d->pixmap = pixmap;
 }
source()
QWidget * QDrag::source () const
Returns the source of the drag object.
This is the widget where the drag and drop operation originated.
Definition at line 209 of file qdrag.cpp.
Referenced by QX11Data::dndEnable(), and QOleDropTarget::Drop().
 {
     Q_D(const QDrag);
     return d->source;
 }
start()
Qt::DropAction QDrag::start (Qt::DropActions request = Qt::CopyAction)
Starts the drag and drop operation and returns a value indicating the requested drop action when it is completed.
Note: It is recommended to use exec() instead of this function.
The drop actions that the user can choose from are specified in request. Qt::CopyAction is always allowed.
Note: Although the drag and drop operation can take some time, this function does not block the event loop. Other events are still delivered to the application while the operation is performed.
See also
exec()
Definition at line 317 of file qdrag.cpp.
Referenced by QLineEditPrivate::drag(), QColorWell::mouseMoveEvent(), and QColorShowLabel::mouseMoveEvent().
 {
     Q_D(QDrag);
     if (!d->data) {
         qWarning("QDrag: No mimedata set before starting the drag");
         return d->executed_action;
     }
     QDragManager *manager = QDragManager::self();
     d->defaultDropAction = Qt::IgnoreAction;
     d->possible_actions = request | Qt::CopyAction;
     if (manager)
         d->executed_action = manager->drag(this);
     return d->executed_action;
 }
target()
QWidget * QDrag::target () const
Returns the target of the drag and drop operation.
This is the widget where the drag object was dropped.
Definition at line 219 of file qdrag.cpp.
Referenced by QX11Data::dndEnable(), QLineEditPrivate::drag(), QDragManager::drag(), and QTextControlPrivate::startDrag().
 {
     Q_D(const QDrag);
     return d->target;
 }
targetChanged
void QDrag::targetChanged (QWidget * newTarget) signal
This signal is emitted when the target of the drag and drop operation changes, with newTarget the new target.
See also
target(), actionChanged()
Friends and Related Functions
QDragManager
friend class QDragManager friend
Definition at line 95 of file qdrag.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 93 of file qdrag.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qdrag.h
/src/gui/kernel/qdrag.cpp