Qt 4.8: QRasterizer Class Reference
QRasterizer Class Reference
#include <qrasterizer_p.h>
Public Functions
void initialize (ProcessSpans blend, void *data)
QRasterizer ()
void rasterize (const QT_FT_Outline *outline, Qt::FillRule fillRule)
void rasterize (const QPainterPath &path, Qt::FillRule fillRule)
void rasterizeLine (const QPointF &a, const QPointF &b, qreal width, bool squareCap=false)
void setAntialiased (bool antialiased)
void setClipRect (const QRect &clipRect)
~QRasterizer ()
Properties
QRasterizerPrivate * d
Detailed Description
Definition at line 68 of file qrasterizer_p.h.
Constructors and Destructors
QRasterizer()
QRasterizer::QRasterizer ()
Definition at line 635 of file qrasterizer.cpp.
     : d(new QRasterizerPrivate)
 {
 }
~QRasterizer()
QRasterizer::~QRasterizer ()
Definition at line 640 of file qrasterizer.cpp.
 {
     delete d;
 }
Functions
initialize()
void QRasterizer::initialize (ProcessSpans blend, void * data)
Definition at line 650 of file qrasterizer.cpp.
 {
     d->blend = blend;
     d->data = data;
 }
rasterize() [1/2]
void QRasterizer::rasterize (const QT_FT_Outline * outline, Qt::FillRule fillRule)
Definition at line 1189 of file qrasterizer.cpp.
Referenced by QRasterPaintEngine::fillPath().
 {
     if (outline->n_points < 3 || outline->n_contours == 0)
         return;
     const QT_FT_Vector *points = outline->points;
     QSpanBuffer buffer(d->blend, d->data, d->clipRect);
     // ### QT_FT_Outline already has a bounding rect which is
     // ### precomputed at this point, so we should probably just be
     // ### using that instead...
     QT_FT_Pos min_y = points[0].y, max_y = points[0].y;
     for (int i = 1; i < outline->n_points; ++i) {
         const QT_FT_Vector &p = points[i];
         min_y = qMin(p.y, min_y);
         max_y = qMax(p.y, max_y);
     }
     int iTopBound = qMax(d->clipRect.top(), int((min_y + 32 + COORD_OFFSET - COORD_ROUNDING) >> 6));
     int iBottomBound = qMin(d->clipRect.bottom(), int((max_y - 32 + COORD_OFFSET - COORD_ROUNDING) >> 6));
     if (iTopBound > iBottomBound)
         return;
     d->scanConverter.begin(iTopBound, iBottomBound, d->clipRect.left(), d->clipRect.right(), fillRule, &buffer);
     int first = 0;
     for (int i = 0; i < outline->n_contours; ++i) {
         const int last = outline->contours[i];
         for (int j = first; j < last; ++j) {
             if (outline->tags[j+1] == QT_FT_CURVE_TAG_CUBIC) {
                 Q_ASSERT(outline->tags[j+2] == QT_FT_CURVE_TAG_CUBIC);
                 d->scanConverter.mergeCurve(points[j], points[j+1], points[j+2], points[j+3]);
                 j += 2;
             } else {
                 d->scanConverter.mergeLine(points[j], points[j+1]);
             }
         }
         first = last + 1;
     }
     d->scanConverter.end();
 }
rasterize() [2/2]
void QRasterizer::rasterize (const QPainterPath & path, Qt::FillRule fillRule)
Definition at line 1235 of file qrasterizer.cpp.
 {
     if (path.isEmpty())
         return;
     QSpanBuffer buffer(d->blend, d->data, d->clipRect);
     QRectF bounds = path.controlPointRect();
     int iTopBound = qMax(d->clipRect.top(), int(bounds.top() + qreal(0.5) + (COORD_OFFSET - COORD_ROUNDING)/qreal(64.)));
     int iBottomBound = qMin(d->clipRect.bottom(), int(bounds.bottom() - qreal(0.5) + (COORD_OFFSET - COORD_ROUNDING)/qreal(64.)));
     if (iTopBound > iBottomBound)
         return;
     d->scanConverter.begin(iTopBound, iBottomBound, d->clipRect.left(), d->clipRect.right(), fillRule, &buffer);
     int subpathStart = 0;
     QT_FT_Vector last = { 0, 0 };
     for (int i = 0; i < path.elementCount(); ++i) {
         switch (path.elementAt(i).type) {
         case QPainterPath::LineToElement:
             {
                 QT_FT_Vector p1 = last;
                 QT_FT_Vector p2 = PointToVector(path.elementAt(i));
                 d->scanConverter.mergeLine(p1, p2);
                 last = p2;
                 break;
             }
         case QPainterPath::MoveToElement:
             {
                 if (i != 0) {
                     QT_FT_Vector first = PointToVector(path.elementAt(subpathStart));
                     // close previous subpath
                     if (first.x != last.x || first.y != last.y)
                         d->scanConverter.mergeLine(last, first);
                 }
                 subpathStart = i;
                 last = PointToVector(path.elementAt(i));
                 break;
             }
         case QPainterPath::CurveToElement:
             {
                 QT_FT_Vector p1 = last;
                 QT_FT_Vector p2 = PointToVector(path.elementAt(i));
                 QT_FT_Vector p3 = PointToVector(path.elementAt(++i));
                 QT_FT_Vector p4 = PointToVector(path.elementAt(++i));
                 d->scanConverter.mergeCurve(p1, p2, p3, p4);
                 last = p4;
                 break;
             }
         default:
             Q_ASSERT(false);
             break;
         }
     }
     QT_FT_Vector first = PointToVector(path.elementAt(subpathStart));
     // close path
     if (first.x != last.x || first.y != last.y)
         d->scanConverter.mergeLine(last, first);
     d->scanConverter.end();
 }
rasterizeLine()
void QRasterizer::rasterizeLine (const QPointF & a, const QPointF & b, qreal width, bool squareCap = false)
Definition at line 752 of file qrasterizer.cpp.
Referenced by QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawRects(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillRect(), and QRasterPaintEngine::stroke().
 {
     if (a == b || width == 0 || d->clipRect.isEmpty())
         return;
     Q_ASSERT(width > 0.0);
     QPointF pa = a;
     QPointF pb = b;
     if (squareCap) {
         QPointF delta = pb - pa;
         pa -= (0.5f * width) * delta;
         pb += (0.5f * width) * delta;
     }
     QPointF offs = QPointF(qAbs(b.y() - a.y()), qAbs(b.x() - a.x())) * width * 0.5;
     const QRectF clip(d->clipRect.topLeft() - offs, d->clipRect.bottomRight() + QPoint(1, 1) + offs);
     if (!clip.contains(pa) || !clip.contains(pb)) {
         qreal t1 = 0;
         qreal t2 = 1;
         const qreal o[2] = { pa.x(), pa.y() };
         const qreal d[2] = { pb.x() - pa.x(), pb.y() - pa.y() };
         const qreal low[2] = { clip.left(), clip.top() };
         const qreal high[2] = { clip.right(), clip.bottom() };
         for (int i = 0; i < 2; ++i) {
             if (d[i] == 0) {
                 if (o[i] <= low[i] || o[i] >= high[i])
                     return;
                 continue;
             }
             const qreal d_inv = 1 / d[i];
             qreal t_low = (low[i] - o[i]) * d_inv;
             qreal t_high = (high[i] - o[i]) * d_inv;
             if (t_low > t_high)
                 qSwap(t_low, t_high);
             if (t1 < t_low)
                 t1 = t_low;
             if (t2 > t_high)
                 t2 = t_high;
             if (t1 >= t2)
                 return;
         }
         QPointF npa = pa + (pb - pa) * t1;
         QPointF npb = pa + (pb - pa) * t2;
         pa = npa;
         pb = npb;
     }
     if (!d->antialiased) {
         pa.rx() += (COORD_OFFSET - COORD_ROUNDING)/64.;
         pa.ry() += (COORD_OFFSET - COORD_ROUNDING)/64.;
         pb.rx() += (COORD_OFFSET - COORD_ROUNDING)/64.;
         pb.ry() += (COORD_OFFSET - COORD_ROUNDING)/64.;
     }
     {
         // old delta
         const QPointF d0 = a - b;
         const qreal w0 = d0.x() * d0.x() + d0.y() * d0.y();
         // new delta
         const QPointF d = pa - pb;
         const qreal w = d.x() * d.x() + d.y() * d.y();
         if (w == 0)
             return;
         // adjust width which is given relative to |b - a|
         width *= sqrt(w0 / w);
     }
     QSpanBuffer buffer(d->blend, d->data, d->clipRect);
     if (q26Dot6Compare(pa.y(), pb.y())) {
         const qreal x = (pa.x() + pb.x()) * 0.5f;
         const qreal dx = qAbs(pb.x() - pa.x()) * 0.5f;
         const qreal y = pa.y();
         const qreal dy = width * dx;
         pa = QPointF(x, y - dy);
         pb = QPointF(x, y + dy);
         width = 1 / width;
     }
     if (q26Dot6Compare(pa.x(), pb.x())) {
         if (pa.y() > pb.y())
             qSwap(pa, pb);
         const qreal dy = pb.y() - pa.y();
         const qreal halfWidth = 0.5f * width * dy;
         qreal left = pa.x() - halfWidth;
         qreal right = pa.x() + halfWidth;
         left = qBound(qreal(d->clipRect.left()), left, qreal(d->clipRect.right() + 1));
         right = qBound(qreal(d->clipRect.left()), right, qreal(d->clipRect.right() + 1));
         pa.ry() = qBound(qreal(d->clipRect.top()), pa.y(), qreal(d->clipRect.bottom() + 1));
         pb.ry() = qBound(qreal(d->clipRect.top()), pb.y(), qreal(d->clipRect.bottom() + 1));
         if (q26Dot6Compare(left, right) || q26Dot6Compare(pa.y(), pb.y()))
             return;
         if (d->antialiased) {
             const Q16Dot16 iLeft = int(left);
             const Q16Dot16 iRight = int(right);
             const Q16Dot16 leftWidth = IntToQ16Dot16(iLeft + 1)
                                        - FloatToQ16Dot16(left);
             const Q16Dot16 rightWidth = FloatToQ16Dot16(right)
                                         - IntToQ16Dot16(iRight);
             Q16Dot16 coverage[3];
             int x[3];
             int len[3];
             int n = 1;
             if (iLeft == iRight) {
                 coverage[0] = (leftWidth + rightWidth) * 255;
                 x[0] = iLeft;
                 len[0] = 1;
             } else {
                 coverage[0] = leftWidth * 255;
                 x[0] = iLeft;
                 len[0] = 1;
                 if (leftWidth == Q16Dot16Factor) {
                     len[0] = iRight - iLeft;
                 } else if (iRight - iLeft > 1) {
                     coverage[1] = IntToQ16Dot16(255);
                     x[1] = iLeft + 1;
                     len[1] = iRight - iLeft - 1;
                     ++n;
                 }
                 if (rightWidth) {
                     coverage[n] = rightWidth * 255;
                     x[n] = iRight;
                     len[n] = 1;
                     ++n;
                 }
             }
             const Q16Dot16 iTopFP = IntToQ16Dot16(int(pa.y()));
             const Q16Dot16 iBottomFP = IntToQ16Dot16(int(pb.y()));
             const Q16Dot16 yPa = FloatToQ16Dot16(pa.y());
             const Q16Dot16 yPb = FloatToQ16Dot16(pb.y());
             for (Q16Dot16 yFP = iTopFP; yFP <= iBottomFP; yFP += Q16Dot16Factor) {
                 const Q16Dot16 rowHeight = qMin(yFP + Q16Dot16Factor, yPb)
                                            - qMax(yFP, yPa);
                 const int y = Q16Dot16ToInt(yFP);
                 if (y > d->clipRect.bottom())
                     break;
                 for (int i = 0; i < n; ++i) {
                     buffer.addSpan(x[i], len[i], y,
                                    Q16Dot16ToInt(Q16Dot16Multiply(rowHeight, coverage[i])));
                 }
             }
         } else { // aliased
             int iTop = int(pa.y() + 0.5f);
             int iBottom = pb.y() < 0.5f ? -1 : int(pb.y() - 0.5f);
             int iLeft = int(left + 0.5f);
             int iRight = right < 0.5f ? -1 : int(right - 0.5f);
             int iWidth = iRight - iLeft + 1;
             for (int y = iTop; y <= iBottom; ++y)
                 buffer.addSpan(iLeft, iWidth, y, 255);
         }
     } else {
         if (pa.y() > pb.y())
             qSwap(pa, pb);
         QPointF delta = pb - pa;
         delta *= 0.5f * width;
         const QPointF perp(delta.y(), -delta.x());
         QPointF top;
         QPointF left;
         QPointF right;
         QPointF bottom;
         if (pa.x() < pb.x()) {
             top = pa + perp;
             left = pa - perp;
             right = pb + perp;
             bottom = pb - perp;
         } else {
             top = pa - perp;
             left = pb - perp;
             right = pa + perp;
             bottom = pb + perp;
         }
         top = snapTo26Dot6Grid(top);
         bottom = snapTo26Dot6Grid(bottom);
         left = snapTo26Dot6Grid(left);
         right = snapTo26Dot6Grid(right);
         const qreal topBound = qBound(qreal(d->clipRect.top()), top.y(), qreal(d->clipRect.bottom()));
         const qreal bottomBound = qBound(qreal(d->clipRect.top()), bottom.y(), qreal(d->clipRect.bottom()));
         const QPointF topLeftEdge = left - top;
         const QPointF topRightEdge = right - top;
         const QPointF bottomLeftEdge = bottom - left;
         const QPointF bottomRightEdge = bottom - right;
         const qreal topLeftSlope = qSafeDivide(topLeftEdge.x(), topLeftEdge.y());
         const qreal bottomLeftSlope = qSafeDivide(bottomLeftEdge.x(), bottomLeftEdge.y());
         const qreal topRightSlope = qSafeDivide(topRightEdge.x(), topRightEdge.y());
         const qreal bottomRightSlope = qSafeDivide(bottomRightEdge.x(), bottomRightEdge.y());
         const Q16Dot16 topLeftSlopeFP = qSafeFloatToQ16Dot16(topLeftSlope);
         const Q16Dot16 topRightSlopeFP = qSafeFloatToQ16Dot16(topRightSlope);
         const Q16Dot16 bottomLeftSlopeFP = qSafeFloatToQ16Dot16(bottomLeftSlope);
         const Q16Dot16 bottomRightSlopeFP = qSafeFloatToQ16Dot16(bottomRightSlope);
         const Q16Dot16 invTopLeftSlopeFP = qSafeFloatToQ16Dot16(qSafeDivide(1, topLeftSlope));
         const Q16Dot16 invTopRightSlopeFP = qSafeFloatToQ16Dot16(qSafeDivide(1, topRightSlope));
         const Q16Dot16 invBottomLeftSlopeFP = qSafeFloatToQ16Dot16(qSafeDivide(1, bottomLeftSlope));
         const Q16Dot16 invBottomRightSlopeFP = qSafeFloatToQ16Dot16(qSafeDivide(1, bottomRightSlope));
         if (d->antialiased) {
             const Q16Dot16 iTopFP = IntToQ16Dot16(int(topBound));
             const Q16Dot16 iLeftFP = IntToQ16Dot16(int(left.y()));
             const Q16Dot16 iRightFP = IntToQ16Dot16(int(right.y()));
             const Q16Dot16 iBottomFP = IntToQ16Dot16(int(bottomBound));
             Q16Dot16 leftIntersectAf = FloatToQ16Dot16(top.x() + (int(topBound) - top.y()) * topLeftSlope);
             Q16Dot16 rightIntersectAf = FloatToQ16Dot16(top.x() + (int(topBound) - top.y()) * topRightSlope);
             Q16Dot16 leftIntersectBf = 0;
             Q16Dot16 rightIntersectBf = 0;
             if (iLeftFP < iTopFP)
                 leftIntersectBf = FloatToQ16Dot16(left.x() + (int(topBound) - left.y()) * bottomLeftSlope);
             if (iRightFP < iTopFP)
                 rightIntersectBf = FloatToQ16Dot16(right.x() + (int(topBound) - right.y()) * bottomRightSlope);
             Q16Dot16 rowTop, rowBottomLeft, rowBottomRight, rowTopLeft, rowTopRight, rowBottom;
             Q16Dot16 topLeftIntersectAf, topLeftIntersectBf, topRightIntersectAf, topRightIntersectBf;
             Q16Dot16 bottomLeftIntersectAf, bottomLeftIntersectBf, bottomRightIntersectAf, bottomRightIntersectBf;
             int leftMin, leftMax, rightMin, rightMax;
             const Q16Dot16 yTopFP = FloatToQ16Dot16(top.y());
             const Q16Dot16 yLeftFP = FloatToQ16Dot16(left.y());
             const Q16Dot16 yRightFP = FloatToQ16Dot16(right.y());
             const Q16Dot16 yBottomFP = FloatToQ16Dot16(bottom.y());
             rowTop = qMax(iTopFP, yTopFP);
             topLeftIntersectAf = leftIntersectAf +
                                  Q16Dot16Multiply(topLeftSlopeFP, rowTop - iTopFP);
             topRightIntersectAf = rightIntersectAf +
                                   Q16Dot16Multiply(topRightSlopeFP, rowTop - iTopFP);
             Q16Dot16 yFP = iTopFP;
             while (yFP <= iBottomFP) {
                 rowBottomLeft = qMin(yFP + Q16Dot16Factor, yLeftFP);
                 rowBottomRight = qMin(yFP + Q16Dot16Factor, yRightFP);
                 rowTopLeft = qMax(yFP, yLeftFP);
                 rowTopRight = qMax(yFP, yRightFP);
                 rowBottom = qMin(yFP + Q16Dot16Factor, yBottomFP);
                 if (yFP == iLeftFP) {
                     const int y = Q16Dot16ToInt(yFP);
                     leftIntersectBf = FloatToQ16Dot16(left.x() + (y - left.y()) * bottomLeftSlope);
                     topLeftIntersectBf = leftIntersectBf + Q16Dot16Multiply(bottomLeftSlopeFP, rowTopLeft - yFP);
                     bottomLeftIntersectAf = leftIntersectAf + Q16Dot16Multiply(topLeftSlopeFP, rowBottomLeft - yFP);
                 } else {
                     topLeftIntersectBf = leftIntersectBf;
                     bottomLeftIntersectAf = leftIntersectAf + topLeftSlopeFP;
                 }
                 if (yFP == iRightFP) {
                     const int y = Q16Dot16ToInt(yFP);
                     rightIntersectBf = FloatToQ16Dot16(right.x() + (y - right.y()) * bottomRightSlope);
                     topRightIntersectBf = rightIntersectBf + Q16Dot16Multiply(bottomRightSlopeFP, rowTopRight - yFP);
                     bottomRightIntersectAf = rightIntersectAf + Q16Dot16Multiply(topRightSlopeFP, rowBottomRight - yFP);
                 } else {
                     topRightIntersectBf = rightIntersectBf;
                     bottomRightIntersectAf = rightIntersectAf + topRightSlopeFP;
                 }
                 if (yFP == iBottomFP) {
                     bottomLeftIntersectBf = leftIntersectBf + Q16Dot16Multiply(bottomLeftSlopeFP, rowBottom - yFP);
                     bottomRightIntersectBf = rightIntersectBf + Q16Dot16Multiply(bottomRightSlopeFP, rowBottom - yFP);
                 } else {
                     bottomLeftIntersectBf = leftIntersectBf + bottomLeftSlopeFP;
                     bottomRightIntersectBf = rightIntersectBf + bottomRightSlopeFP;
                 }
                 if (yFP < iLeftFP) {
                     leftMin = Q16Dot16ToInt(bottomLeftIntersectAf);
                     leftMax = Q16Dot16ToInt(topLeftIntersectAf);
                 } else if (yFP == iLeftFP) {
                     leftMin = Q16Dot16ToInt(qMax(bottomLeftIntersectAf, topLeftIntersectBf));
                     leftMax = Q16Dot16ToInt(qMax(topLeftIntersectAf, bottomLeftIntersectBf));
                 } else {
                     leftMin = Q16Dot16ToInt(topLeftIntersectBf);
                     leftMax = Q16Dot16ToInt(bottomLeftIntersectBf);
                 }
                 leftMin = qBound(d->clipRect.left(), leftMin, d->clipRect.right());
                 leftMax = qBound(d->clipRect.left(), leftMax, d->clipRect.right());
                 if (yFP < iRightFP) {
                     rightMin = Q16Dot16ToInt(topRightIntersectAf);
                     rightMax = Q16Dot16ToInt(bottomRightIntersectAf);
                 } else if (yFP == iRightFP) {
                     rightMin = Q16Dot16ToInt(qMin(topRightIntersectAf, bottomRightIntersectBf));
                     rightMax = Q16Dot16ToInt(qMin(bottomRightIntersectAf, topRightIntersectBf));
                 } else {
                     rightMin = Q16Dot16ToInt(bottomRightIntersectBf);
                     rightMax = Q16Dot16ToInt(topRightIntersectBf);
                 }
                 rightMin = qBound(d->clipRect.left(), rightMin, d->clipRect.right());
                 rightMax = qBound(d->clipRect.left(), rightMax, d->clipRect.right());
                 if (leftMax > rightMax)
                     leftMax = rightMax;
                 if (rightMin < leftMin)
                     rightMin = leftMin;
                 Q16Dot16 rowHeight = rowBottom - rowTop;
                 int x = leftMin;
                 while (x <= leftMax) {
                     Q16Dot16 excluded = 0;
                     if (yFP <= iLeftFP)
                         excluded += intersectPixelFP(x, rowTop, rowBottomLeft,
                                                      bottomLeftIntersectAf, topLeftIntersectAf,
                                                      topLeftSlopeFP, invTopLeftSlopeFP);
                     if (yFP >= iLeftFP)
                         excluded += intersectPixelFP(x, rowTopLeft, rowBottom,
                                                      topLeftIntersectBf, bottomLeftIntersectBf,
                                                      bottomLeftSlopeFP, invBottomLeftSlopeFP);
                     if (x >= rightMin) {
                         if (yFP <= iRightFP)
                             excluded += (rowBottomRight - rowTop) - intersectPixelFP(x, rowTop, rowBottomRight,
                                                                                      topRightIntersectAf, bottomRightIntersectAf,
                                                                                      topRightSlopeFP, invTopRightSlopeFP);
                         if (yFP >= iRightFP)
                             excluded += (rowBottom - rowTopRight) - intersectPixelFP(x, rowTopRight, rowBottom,
                                                                                      bottomRightIntersectBf, topRightIntersectBf,
                                                                                      bottomRightSlopeFP, invBottomRightSlopeFP);
                     }
                     Q16Dot16 coverage = rowHeight - excluded;
                     buffer.addSpan(x, 1, Q16Dot16ToInt(yFP),
                                    Q16Dot16ToInt(255 * coverage));
                     ++x;
                 }
                 if (x < rightMin) {
                     buffer.addSpan(x, rightMin - x, Q16Dot16ToInt(yFP),
                                    Q16Dot16ToInt(255 * rowHeight));
                     x = rightMin;
                 }
                 while (x <= rightMax) {
                     Q16Dot16 excluded = 0;
                     if (yFP <= iRightFP)
                         excluded += (rowBottomRight - rowTop) - intersectPixelFP(x, rowTop, rowBottomRight,
                                                                                  topRightIntersectAf, bottomRightIntersectAf,
                                                                                  topRightSlopeFP, invTopRightSlopeFP);
                     if (yFP >= iRightFP)
                         excluded += (rowBottom - rowTopRight) - intersectPixelFP(x, rowTopRight, rowBottom,
                                                                                  bottomRightIntersectBf, topRightIntersectBf,
                                                                                  bottomRightSlopeFP, invBottomRightSlopeFP);
                     Q16Dot16 coverage = rowHeight - excluded;
                     buffer.addSpan(x, 1, Q16Dot16ToInt(yFP),
                                    Q16Dot16ToInt(255 * coverage));
                     ++x;
                 }
                 leftIntersectAf += topLeftSlopeFP;
                 leftIntersectBf += bottomLeftSlopeFP;
                 rightIntersectAf += topRightSlopeFP;
                 rightIntersectBf += bottomRightSlopeFP;
                 topLeftIntersectAf = leftIntersectAf;
                 topRightIntersectAf = rightIntersectAf;
                 yFP += Q16Dot16Factor;
                 rowTop = yFP;
             }
         } else { // aliased
             int iTop = int(top.y() + 0.5f);
             int iLeft = left.y() < 0.5f ? -1 : int(left.y() - 0.5f);
             int iRight = right.y() < 0.5f ? -1 : int(right.y() - 0.5f);
             int iBottom = bottom.y() < 0.5f? -1 : int(bottom.y() - 0.5f);
             int iMiddle = qMin(iLeft, iRight);
             Q16Dot16 leftIntersectAf = qSafeFloatToQ16Dot16(top.x() + 0.5f + (iTop + 0.5f - top.y()) * topLeftSlope);
             Q16Dot16 leftIntersectBf = qSafeFloatToQ16Dot16(left.x() + 0.5f + (iLeft + 1.5f - left.y()) * bottomLeftSlope);
             Q16Dot16 rightIntersectAf = qSafeFloatToQ16Dot16(top.x() - 0.5f + (iTop + 0.5f - top.y()) * topRightSlope);
             Q16Dot16 rightIntersectBf = qSafeFloatToQ16Dot16(right.x() - 0.5f + (iRight + 1.5f - right.y()) * bottomRightSlope);
             int ny;
             int y = iTop;
 #define DO_SEGMENT(next, li, ri, ls, rs) \
             ny = qMin(next + 1, d->clipRect.top()); \
             if (y < ny) { \
                 li += ls * (ny - y); \
                 ri += rs * (ny - y); \
                 y = ny; \
             } \
             if (next > d->clipRect.bottom()) \
                 next = d->clipRect.bottom(); \
             for (; y <= next; ++y) { \
                 const int x1 = qMax(Q16Dot16ToInt(li), d->clipRect.left()); \
                 const int x2 = qMin(Q16Dot16ToInt(ri), d->clipRect.right()); \
                 if (x2 >= x1) \
                     buffer.addSpan(x1, x2 - x1 + 1, y, 255); \
                 li += ls; \
                 ri += rs; \
              }
             DO_SEGMENT(iMiddle, leftIntersectAf, rightIntersectAf, topLeftSlopeFP, topRightSlopeFP)
             DO_SEGMENT(iRight, leftIntersectBf, rightIntersectAf, bottomLeftSlopeFP, topRightSlopeFP)
             DO_SEGMENT(iLeft, leftIntersectAf, rightIntersectBf, topLeftSlopeFP, bottomRightSlopeFP);
             DO_SEGMENT(iBottom, leftIntersectBf, rightIntersectBf, bottomLeftSlopeFP, bottomRightSlopeFP);
 #undef DO_SEGMENT
         }
     }
 }
setAntialiased()
void QRasterizer::setAntialiased (bool antialiased)
Definition at line 645 of file qrasterizer.cpp.
Referenced by QRasterPaintEngine::drawImage(), and QRasterPaintEngine::drawTiledPixmap().
 {
     d->antialiased = antialiased;
 }
setClipRect()
void QRasterizer::setClipRect (const QRect & clipRect)
Definition at line 656 of file qrasterizer.cpp.
 {
     d->clipRect = clipRect;
 }
Properties
d
QRasterizerPrivate* QRasterizer::d private
Definition at line 90 of file qrasterizer_p.h.
Referenced by initialize(), rasterize(), rasterizeLine(), setAntialiased(), setClipRect(), and ~QRasterizer().
The documentation for this class was generated from the following files:
/src/gui/painting/qrasterizer_p.h
/src/gui/painting/qrasterizer.cpp