Qt 4.8: QDialog Class Reference
QDialog Class Reference
The QDialog class is the base class of dialog windows.
#include <qdialog.h>
Public Types
enum DialogCode { Rejected, Accepted }
The value returned by a modal dialog.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
virtual void accept ()
Hides the modal dialog and sets the result code to Accepted.
virtual void done (int)
Closes the dialog and sets its result code to r.
int exec ()
Shows the dialog as a modal dialog, blocking until the user closes it.
void open ()
Shows the dialog as a window modal dialog, returning immediately.
virtual void reject ()
Hides the modal dialog and sets the result code to Rejected.
void showExtension (bool)
If showIt is true, the dialog's extension is shown; otherwise the extension is hidden.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void accepted ()
This signal is emitted when the dialog has been accepted either by the user or by calling accept() or done() with the QDialog::Accepted argument.
void finished (int result)
This signal is emitted when the dialog's result code has been set, either by the user or by calling done(), accept(), or reject().
void rejected ()
This signal is emitted when the dialog has been rejected either by the user or by calling reject() or done() with the QDialog::Rejected argument.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QWidget * extension () const
Returns the dialog's extension or 0 if no extension has been defined.
bool isSizeGripEnabled () const
QSize minimumSizeHint () const
Reimplemented Function
Qt::Orientation orientation () const
Returns the dialog's extension orientation.
QDialog (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a dialog with parent parent.
int result () const
In general returns the modal dialog's result code, Accepted or Rejected.
void setExtension (QWidget *extension)
Sets the widget, extension, to be the dialog's extension, deleting any previous extension.
void setModal (bool modal)
void setOrientation (Qt::Orientation orientation)
If orientation is Qt::Horizontal, the extension will be displayed to the right of the dialog's main area.
void setResult (int r)
Sets the modal dialog's result code to i.
void setSizeGripEnabled (bool)
void setVisible (bool visible)
Reimplemented Function
QSize sizeHint () const
Reimplemented Function
~QDialog ()
Destroys the QDialog, deleting all its children.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void adjustPosition (QWidget *)
void closeEvent (QCloseEvent *)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
Reimplemented Function
QDialog (QDialogPrivate &, QWidget *parent, Qt::WindowFlags f=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void resizeEvent (QResizeEvent *)
Reimplemented Function
void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool modal
whether show() should pop up the dialog as modal or modeless
bool sizeGripEnabled
whether the size grip is enabled
Friends
class QPushButton
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QDialog class is the base class of dialog windows.
A dialog window is a top-level window mostly used for short-term tasks and brief communications with the user. QDialogs may be modal or modeless. QDialogs can provide a return value, and they can have default buttons. QDialogs can also have a QSizeGrip in their lower-right corner, using setSizeGripEnabled().
Note that QDialog (and any other widget that has type Qt::Dialog) uses the parent widget slightly differently from other classes in Qt. A dialog is always a top-level widget, but if it has a parent, its default location is centered on top of the parent's top-level widget (if it is not top-level itself). It will also share the parent's taskbar entry.
Use the overload of the QWidget::setParent() function to change the ownership of a QDialog widget. This function allows you to explicitly set the window flags of the reparented widget; using the overloaded function will clear the window flags specifying the window-system properties for the widget (in particular it will reset the Qt::Dialog flag).
Modal Dialogs
A modal dialog is a dialog that blocks input to other visible windows in the same application. Dialogs that are used to request a file name from the user or that are used to set application preferences are usually modal. Dialogs can be application modal (the default) or window modal.
When an application modal dialog is opened, the user must finish interacting with the dialog and close it before they can access any other window in the application. Window modal dialogs only block access to the window associated with the dialog, allowing the user to continue to use other windows in an application.
The most common way to display a modal dialog is to call its exec() function. When the user closes the dialog, exec() will provide a useful return value. Typically, to get the dialog to close and return the appropriate value, we connect a default button, e.g. OK, to the accept() slot and a Cancel button to the reject() slot. Alternatively you can call the done() slot with Accepted or Rejected.
An alternative is to call setModal(true) or setWindowModality(), then show(). Unlike exec(), show() returns control to the caller immediately. Calling setModal(true) is especially useful for progress dialogs, where the user must have the ability to interact with the dialog, e.g. to cancel a long running operation. If you use show() and setModal(true) together to perform a long operation, you must call QApplication::processEvents() periodically during processing to enable the user to interact with the dialog. (See QProgressDialog.)
Modeless Dialogs
A modeless dialog is a dialog that operates independently of other windows in the same application. Find and replace dialogs in word-processors are often modeless to allow the user to interact with both the application's main window and with the dialog.
Modeless dialogs are displayed using show(), which returns control to the caller immediately.
If you invoke the show() function after hiding a dialog, the dialog will be displayed in its original position. This is because the window manager decides the position for windows that have not been explicitly placed by the programmer. To preserve the position of a dialog that has been moved by the user, save its position in your closeEvent() handler and then move the dialog to that position, before showing it again.
Default Button
A dialog's default button is the button that's pressed when the user presses Enter (Return). This button is used to signify that the user accepts the dialog's settings and wants to close the dialog. Use QPushButton::setDefault(), QPushButton::isDefault() and QPushButton::autoDefault() to set and control the dialog's default button.
Escape Key
If the user presses the Esc key in a dialog, QDialog::reject() will be called. This will cause the window to close: The close event cannot be ignored .
Extensibility
Extensibility is the ability to show the dialog in two ways: a partial dialog that shows the most commonly used options, and a full dialog that shows all the options. Typically an extensible dialog will initially appear as a partial dialog, but with a More toggle button. If the user presses the More button down, the dialog is expanded. The Extension Example shows how to achieve extensible dialogs using Qt.
(Modal-Dialogs)
Return Value (Modal Dialogs)
Modal dialogs are often used in situations where a return value is required, e.g. to indicate whether the user pressed OK or Cancel. A dialog can be closed by calling the accept() or the reject() slots, and exec() will return Accepted or Rejected as appropriate. The exec() call returns the result of the dialog. The result is also available from result() if the dialog has not been destroyed.
In order to modify your dialog's close behavior, you can reimplement the functions accept(), reject() or done(). The closeEvent() function should only be reimplemented to preserve the dialog's position or to override the standard close or reject behavior.
Code Examples
A modal dialog:
void EditorWindow::countWords()
{
    WordCountDialog dialog(this);
    dialog.setWordCount(document().wordCount());
    dialog.exec();
}
A modeless dialog:
void EditorWindow::find()
{
    if (!findDialog) {
        findDialog = new FindDialog(this);
        connect(findDialog, SIGNAL(findNext()), this, SLOT(findNext()));
    }
    findDialog->show();
    findDialog->raise();
    findDialog->activateWindow();
}
See also
QDialogButtonBox, QTabWidget, QWidget, QProgressDialog, {fowler}{GUI Design Handbook: Dialogs, Standard}, {Extension Example}, {Standard Dialogs Example}
Definition at line 56 of file qdialog.h.
Enumerations
DialogCode
enum QDialog::DialogCode
The value returned by a modal dialog.
Accepted
Rejected
Enumerator
Rejected
Accepted
Definition at line 72 of file qdialog.h.
 { Rejected, Accepted };
Constructors and Destructors
QDialog() [1/2]
QDialog::QDialog (QWidget * parent = 0, Qt::WindowFlags f = 0) explicit
Constructs a dialog with parent parent.
A dialog is always a top-level widget, but if it has a parent, its default location is centered on top of the parent. It will also share the parent's taskbar entry.
The widget flags f are passed on to the QWidget constructor. If, for example, you don't want a What's This button in the title bar of the dialog, pass Qt::WindowTitleHint | Qt::WindowSystemMenuHint in f.
See also
QWidget::setWindowFlags()
Definition at line 268 of file qdialog.cpp.
Referenced by QMessageBox::setWindowModality().
     : QWidget(*new QDialogPrivate, parent,
               f | ((f & Qt::WindowType_Mask) == 0 ? Qt::Dialog : Qt::WindowType(0)))
 {
 #ifdef Q_WS_WINCE
     if (!qt_wince_is_smartphone())
         setWindowFlags(windowFlags() | Qt::WindowOkButtonHint | QFlag(qt_wince_is_mobile() ? 0 : Qt::WindowCancelButtonHint));
 #endif
 #ifdef Q_WS_S60
     if (S60->avkonComponentsSupportTransparency) {
         bool noSystemBackground = testAttribute(Qt::WA_NoSystemBackground);
         setAttribute(Qt::WA_TranslucentBackground); // also sets WA_NoSystemBackground
         setAttribute(Qt::WA_NoSystemBackground, noSystemBackground); // restore system background attribute
     }
 #endif
 }
~QDialog()
QDialog::~QDialog ()
Destroys the QDialog, deleting all its children.
Definition at line 327 of file qdialog.cpp.
 {
     QT_TRY {
         // Need to hide() here, as our (to-be) overridden hide()
         // will not be called in ~QWidget.
         hide();
     } QT_CATCH(...) {
         // we're in the destructor - just swallow the exception
     }
 }
QDialog() [2/2]
QDialog::QDialog (QDialogPrivate & dd, QWidget * parent, Qt::WindowFlags f = 0) protected
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Warning
This function is not part of the public interface.
Definition at line 306 of file qdialog.cpp.
     : QWidget(dd, parent, f | ((f & Qt::WindowType_Mask) == 0 ? Qt::Dialog : Qt::WindowType(0)))
 {
 #ifdef Q_WS_WINCE
     if (!qt_wince_is_smartphone())
         setWindowFlags(windowFlags() | Qt::WindowOkButtonHint | QFlag(qt_wince_is_mobile() ? 0 : Qt::WindowCancelButtonHint));
 #endif
 #ifdef Q_WS_S60
     if (S60->avkonComponentsSupportTransparency) {
         bool noSystemBackground = testAttribute(Qt::WA_NoSystemBackground);
         setAttribute(Qt::WA_TranslucentBackground); // also sets WA_NoSystemBackground
         setAttribute(Qt::WA_NoSystemBackground, noSystemBackground); // restore system background attribute
     }
 #endif
 }
Functions
accept
void QDialog::accept () virtual slot
Hides the modal dialog and sets the result code to Accepted.
See also
reject() done()
Reimplemented in QFileDialog.
Definition at line 639 of file qdialog.cpp.
Referenced by QFileDialog::accept(), QPrintPropertiesDialog::addItemToOptions(), event(), QFontDialogPrivate::init(), QAxSelect::on_ActiveXList_doubleClicked(), QAxSelect::QAxSelect(), QErrorMessage::QErrorMessage(), QPrintPropertiesDialog::QPrintPropertiesDialog(), and QPrintDialogPrivate::selectPrinter().
 {
     done(Accepted);
 }
accepted
void QDialog::accepted () signal
This signal is emitted when the dialog has been accepted either by the user or by calling accept() or done() with the QDialog::Accepted argument.
Since
4.1
Note that this signal is not emitted when hiding the dialog with hide() or setVisible(false). This includes deleting the dialog while it is visible.
See also
finished(), rejected()
Referenced by QPrintPropertiesDialog::addItemToOptions(), QAbstractPageSetupDialog::done(), QPrintDialog::done(), done(), QFontDialogPrivate::init(), and QPrintDialog::open().
adjustPosition()
void QDialog::adjustPosition (QWidget * w) protected
Warning
This function is not part of the public interface.
Definition at line 850 of file qdialog.cpp.
Referenced by event(), setVisible(), and showEvent().
 {
 #ifdef Q_WS_X11
     // if the WM advertises that it will place the windows properly for us, let it do it :)
     if (X11->isSupportedByWM(ATOM(_NET_WM_FULL_PLACEMENT)))
         return;
 #endif
 #ifdef Q_OS_SYMBIAN
     if (symbianAdjustedPosition())
         //dialog has already been positioned
         return;
 #endif
     QPoint p(0, 0);
     int extraw = 0, extrah = 0, scrn = 0;
     if (w)
         w = w->window();
     QRect desk;
     if (w) {
         scrn = QApplication::desktop()->screenNumber(w);
     } else if (QApplication::desktop()->isVirtualDesktop()) {
         scrn = QApplication::desktop()->screenNumber(QCursor::pos());
     } else {
         scrn = QApplication::desktop()->screenNumber(this);
     }
     desk = QApplication::desktop()->availableGeometry(scrn);
     QWidgetList list = QApplication::topLevelWidgets();
     for (int i = 0; (extraw == 0 || extrah == 0) && i < list.size(); ++i) {
         QWidget * current = list.at(i);
         if (current->isVisible()) {
             int framew = current->geometry().x() - current->x();
             int frameh = current->geometry().y() - current->y();
             extraw = qMax(extraw, framew);
             extrah = qMax(extrah, frameh);
         }
     }
     // sanity check for decoration frames. With embedding, we
     // might get extraordinary values
     if (extraw == 0 || extrah == 0 || extraw >= 10 || extrah >= 40) {
         extrah = 40;
         extraw = 10;
     }
     if (w) {
         // Use mapToGlobal rather than geometry() in case w might
         // be embedded in another application
         QPoint pp = w->mapToGlobal(QPoint(0,0));
         p = QPoint(pp.x() + w->width()/2,
                     pp.y() + w->height()/ 2);
     } else {
         // p = middle of the desktop
         p = QPoint(desk.x() + desk.width()/2, desk.y() + desk.height()/2);
     }
     // p = origin of this
     p = QPoint(p.x()-width()/2 - extraw,
                 p.y()-height()/2 - extrah);
     if (p.x() + extraw + width() > desk.x() + desk.width())
         p.setX(desk.x() + desk.width() - width() - extraw);
     if (p.x() < desk.x())
         p.setX(desk.x());
     if (p.y() + extrah + height() > desk.y() + desk.height())
         p.setY(desk.y() + desk.height() - height() - extrah);
     if (p.y() < desk.y())
         p.setY(desk.y());
     move(p);
 }
closeEvent()
void QDialog::closeEvent (QCloseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QMessageBox, and QProgressDialog.
Definition at line 733 of file qdialog.cpp.
Referenced by QProgressDialog::closeEvent(), QMessageBox::closeEvent(), and QMessageBox::critical().
 {
 #ifndef QT_NO_WHATSTHIS
     if (isModal() && QWhatsThis::inWhatsThisMode())
         QWhatsThis::leaveWhatsThisMode();
 #endif
     if (isVisible()) {
         QPointer<QObject> that = this;
         reject();
         if (that && isVisible())
             e->ignore();
     } else {
         e->accept();
     }
 }
contextMenuEvent()
void QDialog::contextMenuEvent (QContextMenuEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 667 of file qdialog.cpp.
 {
 #if defined(QT_NO_WHATSTHIS) || defined(QT_NO_MENU)
     Q_UNUSED(e);
 #else
     QWidget *w = childAt(e->pos());
     if (!w) {
         w = rect().contains(e->pos()) ? this : 0;
         if (!w)
             return;
     }
     while (w && w->whatsThis().size() == 0 && !w->testAttribute(Qt::WA_CustomWhatsThis))
         w = w->isWindow() ? 0 : w->parentWidget();
     if (w) {
         QWeakPointer<QMenu> p = new QMenu(this);
         QAction *wt = p.data()->addAction(tr("What's This?"));
         if (p.data()->exec(e->globalPos()) == wt) {
             QHelpEvent e(QEvent::WhatsThis, w->rect().center(),
                          w->mapToGlobal(w->rect().center()));
             QApplication::sendEvent(w, &e);
         }
         delete p.data();
     }
 #endif
 }
done
void QDialog::done (int r) virtual slot
Closes the dialog and sets its result code to r.
If this dialog is shown with exec(), done() causes the local event loop to finish, and exec() to return r.
As with QWidget::close(), done() deletes the dialog if the Qt::WA_DeleteOnClose flag is set. If the dialog is the application's main widget, the application terminates. If the dialog is the last window closed, the QApplication::lastWindowClosed() signal is emitted.
See also
accept(), reject(), QApplication::activeWindow(), QApplication::quit()
Reimplemented in QFileDialog, QInputDialog, QWizard, QColorDialog, QFontDialog, QPrintDialog, QPrintPreviewDialog, QErrorMessage, and QAbstractPageSetupDialog.
Definition at line 617 of file qdialog.cpp.
Referenced by accept(), QAbstractPageSetupDialog::done(), QErrorMessage::done(), QPrintPreviewDialog::done(), QPrintDialog::done(), QFontDialog::done(), QColorDialog::done(), QWizard::done(), QInputDialog::done(), QFileDialog::done(), and reject().
 {
     Q_D(QDialog);
     hide();
     setResult(r);
     d->close_helper(QWidgetPrivate::CloseNoEvent);
     d->resetModalitySetByOpen();
     emit finished(r);
     if (r == Accepted)
         emit accepted();
     else if (r == Rejected)
         emit rejected();
 }
event()
bool QDialog::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Reimplemented in QMessageBox, and QWizard.
Definition at line 426 of file qdialog.cpp.
Referenced by QMessageBox::critical(), QWizard::event(), QMessageBox::event(), and QPrintPropertiesDialog::setCups().
 {
     bool result = QWidget::event(e);
 #ifdef Q_WS_WINCE
     if (e->type() == QEvent::OkRequest) {
         accept();
         result = true;
      }
 #elif defined(Q_WS_S60)
     if ((e->type() == QEvent::StyleChange) || (e->type() == QEvent::Resize )) {
         if (!testAttribute(Qt::WA_Moved)) {
             Qt::WindowStates state = windowState();
             adjustPosition(parentWidget());
             setAttribute(Qt::WA_Moved, false); // not really an explicit position
             if (state != windowState())
                 setWindowState(state);
         }
     }
     // TODO is Symbian, non-S60 behaviour required?
 #endif
     return result;
 }
eventFilter()
bool QDialog::eventFilter (QObject * o, QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Reimplemented in QFontDialog.
Definition at line 656 of file qdialog.cpp.
Referenced by QPrintDialogPrivate::setupOptions().
 {
     return QWidget::eventFilter(o, e);
 }
exec
int QDialog::exec () slot
Shows the dialog as a modal dialog, blocking until the user closes it.
The function returns a DialogCode result.
If the dialog is application modal, users cannot interact with any other window in the same application until they close the dialog. If the dialog is window modal, only interaction with the parent window is blocked while the dialog is open. By default, the dialog is application modal.
See also
open(), show(), result(), setWindowModality()
Definition at line 524 of file qdialog.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_btnPropertiesClicked(), QMessageBox::critical(), QColorDialog::getColor(), QInputDialog::getDouble(), QFileDialog::getExistingDirectory(), QFontDialogPrivate::getFont(), QInputDialog::getInt(), QFileDialog::getOpenFileName(), QFileDialog::getOpenFileNames(), QFileDialog::getSaveFileName(), QInputDialog::getText(), QPrintDialogPrivate::selectPrinter(), QPrintDialogPrivate::setPrinter(), and QPageSetupWidget::setRightMargin().
 {
     Q_D(QDialog);
     if (d->eventLoop) {
         qWarning("QDialog::exec: Recursive call detected");
         return -1;
     }
     bool deleteOnClose = testAttribute(Qt::WA_DeleteOnClose);
     setAttribute(Qt::WA_DeleteOnClose, false);
     d->resetModalitySetByOpen();
     bool wasShowModal = testAttribute(Qt::WA_ShowModal);
     setAttribute(Qt::WA_ShowModal, true);
     setResult(0);
 //On Windows Mobile we create an empty menu to hide the current menu
 #ifdef Q_WS_WINCE_WM
 #ifndef QT_NO_MENUBAR
     QMenuBar *menuBar = 0;
     if (!findChild<QMenuBar *>())
         menuBar = new QMenuBar(this);
     if (qt_wince_is_smartphone()) {
         QAction *doneAction = new QAction(tr("Done"), this);
         menuBar->setDefaultAction(doneAction);
         connect(doneAction, SIGNAL(triggered()), this, SLOT(_q_doneAction()));
     }
 #endif //QT_NO_MENUBAR
 #endif //Q_WS_WINCE_WM
     bool showSystemDialogFullScreen = false;
 #ifdef Q_OS_SYMBIAN
     if (qobject_cast<QFileDialog *>(this) || qobject_cast<QFontDialog *>(this) ||
         qobject_cast<QWizard *>(this)) {
         showSystemDialogFullScreen = true;
     }
 #endif // Q_OS_SYMBIAN
 #ifdef Q_OS_BLACKBERRY
     if (!qobject_cast<QMessageBox *>(this))
         showSystemDialogFullScreen = true;
 #endif // Q_OS_BLACKBERRY
     if (showSystemDialogFullScreen) {
         setWindowFlags(windowFlags() | Qt::WindowSoftkeysVisibleHint);
         setWindowState(Qt::WindowFullScreen);
     }
     show();
 #ifdef Q_WS_MAC
     d->mac_nativeDialogModalHelp();
 #endif
     QEventLoop eventLoop;
     d->eventLoop = &eventLoop;
     QPointer<QDialog> guard = this;
     (void) eventLoop.exec(QEventLoop::DialogExec);
     if (guard.isNull())
         return QDialog::Rejected;
     d->eventLoop = 0;
     setAttribute(Qt::WA_ShowModal, wasShowModal);
     int res = result();
     if (deleteOnClose)
         delete this;
 #ifdef Q_WS_WINCE_WM
 #ifndef QT_NO_MENUBAR
     else if (menuBar)
         delete menuBar;
 #endif //QT_NO_MENUBAR
 #endif //Q_WS_WINCE_WM
     return res;
 }
extension()
QWidget * QDialog::extension () const
Returns the dialog's extension or 0 if no extension has been defined.
Instead of using this functionality, we recommend that you simply call show() or hide() on the part of the dialog that you want to use as an extension. See the Extension Example for details.
See also
showExtension(), setOrientation()
Definition at line 1087 of file qdialog.cpp.
Referenced by setExtension().
 {
     Q_D(const QDialog);
     return d->extension;
 }
finished
void QDialog::finished (int result) signal
This signal is emitted when the dialog's result code has been set, either by the user or by calling done(), accept(), or reject().
Since
4.1
Note that this signal is not emitted when hiding the dialog with hide() or setVisible(false). This includes deleting the dialog while it is visible.
See also
accepted(), rejected()
Referenced by QPrintPreviewDialog::done(), done(), QPrintPreviewDialog::open(), and QMessageBox::open().
isSizeGripEnabled()
bool QDialog::isSizeGripEnabled () const
Definition at line 1224 of file qdialog.cpp.
Referenced by showExtension().
 {
 #ifndef QT_NO_SIZEGRIP
     Q_D(const QDialog);
     return !!d->resizer;
 #else
     return false;
 #endif
 }
keyPressEvent()
void QDialog::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QMessageBox.
Definition at line 695 of file qdialog.cpp.
Referenced by QMessageBox::critical(), and QMessageBox::keyPressEvent().
 {
     //   Calls reject() if Escape is pressed. Simulates a button
     //   click for the default button if Enter is pressed. Move focus
     //   for the arrow keys. Ignore the rest.
 #ifdef Q_WS_MAC
     if(e->modifiers() == Qt::ControlModifier && e->key() == Qt::Key_Period) {
         reject();
     } else
 #endif
     if (!e->modifiers() || (e->modifiers() & Qt::KeypadModifier && e->key() == Qt::Key_Enter)) {
         switch (e->key()) {
         case Qt::Key_Enter:
         case Qt::Key_Return: {
             QList<QPushButton*> list = findChildren<QPushButton*>();
             for (int i=0; i<list.size(); ++i) {
                 QPushButton *pb = list.at(i);
                 if (pb->isDefault() && pb->isVisible()) {
                     if (pb->isEnabled())
                         pb->click();
                     return;
                 }
             }
         }
         break;
         case Qt::Key_Escape:
             reject();
             break;
         default:
             e->ignore();
             return;
         }
     } else {
         e->ignore();
     }
 }
minimumSizeHint()
QSize QDialog::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QInputDialog.
Definition at line 1186 of file qdialog.cpp.
Referenced by QInputDialog::minimumSizeHint().
 {
     Q_D(const QDialog);
     if (d->extension) {
         if (d->orientation == Qt::Horizontal)
             return QSize(QWidget::minimumSizeHint().width(),
                         qMax(QWidget::minimumSizeHint().height(), d->extension->minimumSizeHint().height()));
         else
             return QSize(qMax(QWidget::minimumSizeHint().width(), d->extension->minimumSizeHint().width()),
                         QWidget::minimumSizeHint().height());
     }
     return QWidget::minimumSizeHint();
 }
open
void QDialog::open () slot
Shows the dialog as a window modal dialog, returning immediately.
Since
4.5
See also
exec(), show(), result(), setWindowModality()
Definition at line 492 of file qdialog.cpp.
Referenced by QPrintPreviewDialog::open(), QColorDialog::open(), QFontDialog::open(), QPageSetupDialog::open(), QProgressDialog::open(), QPrintDialog::open(), QMessageBox::open(), QInputDialog::open(), and QFileDialog::open().
 {
     Q_D(QDialog);
     Qt::WindowModality modality = windowModality();
     if (modality != Qt::WindowModal) {
         d->resetModalityTo = modality;
         d->wasModalitySet = testAttribute(Qt::WA_SetWindowModality);
         setWindowModality(Qt::WindowModal);
         setAttribute(Qt::WA_SetWindowModality, false);
 #ifdef Q_WS_MAC
         setParent(parentWidget(), Qt::Sheet);
 #endif
     }
     setResult(0);
     show();
 }
orientation()
Qt::Orientation QDialog::orientation () const
Returns the dialog's extension orientation.
Instead of using this functionality, we recommend that you simply call show() or hide() on the part of the dialog that you want to use as an extension. See the Extension Example for details.
See also
extension()
Definition at line 1035 of file qdialog.cpp.
Referenced by setOrientation().
 {
     Q_D(const QDialog);
     return d->orientation;
 }
reject
void QDialog::reject () virtual slot
Hides the modal dialog and sets the result code to Rejected.
See also
accept() done()
Definition at line 650 of file qdialog.cpp.
Referenced by QPrintPropertiesDialog::addItemToOptions(), closeEvent(), QFontDialogPrivate::init(), keyPressEvent(), QAxSelect::QAxSelect(), and QPrintPropertiesDialog::QPrintPropertiesDialog().
 {
     done(Rejected);
 }
rejected
void QDialog::rejected () signal
This signal is emitted when the dialog has been rejected either by the user or by calling reject() or done() with the QDialog::Rejected argument.
Since
4.1
Note that this signal is not emitted when hiding the dialog with hide() or setVisible(false). This includes deleting the dialog while it is visible.
See also
finished(), accepted()
Referenced by QPrintPropertiesDialog::addItemToOptions(), done(), and QFontDialogPrivate::init().
resizeEvent()
void QDialog::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QMessageBox, QWizard, and QProgressDialog.
Definition at line 1268 of file qdialog.cpp.
Referenced by QMessageBox::critical(), QWizard::resizeEvent(), and QMessageBox::resizeEvent().
 {
 #ifndef QT_NO_SIZEGRIP
     Q_D(QDialog);
     if (d->resizer) {
         if (isRightToLeft())
             d->resizer->move(rect().bottomLeft() -d->resizer->rect().bottomLeft());
         else
             d->resizer->move(rect().bottomRight() -d->resizer->rect().bottomRight());
         d->resizer->raise();
     }
 #endif
 }
result()
int QDialog::result () const
In general returns the modal dialog's result code, Accepted or Rejected.
Note
When used from QMessageBox instance the result code type is QMessageBox::StandardButton
Do not call this function if the dialog was constructed with the Qt::WA_DeleteOnClose attribute.
Definition at line 458 of file qdialog.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_btnPropertiesClicked(), QMessageBoxPrivate::abstractButtonForId(), QInputDialog::comboBoxItems(), event(), QMessageBox::event(), QPageSetupDialog::exec(), QPrintDialog::exec(), QColorDialog::getRgba(), QUnixPrintWidgetPrivate::setupPrinter(), and QWizard::sizeHint().
 {
     Q_D(const QDialog);
     return d->rescode;
 }
setExtension()
void QDialog::setExtension (QWidget * extension)
Sets the widget, extension, to be the dialog's extension, deleting any previous extension.
The dialog takes ownership of the extension. Note that if 0 is passed any existing extension will be deleted. This function must only be called while the dialog is hidden.
Instead of using this functionality, we recommend that you simply call show() or hide() on the part of the dialog that you want to use as an extension. See the Extension Example for details.
See also
showExtension(), setOrientation()
Definition at line 1058 of file qdialog.cpp.
 {
     Q_D(QDialog);
     delete d->extension;
     d->extension = extension;
     if (!extension)
         return;
     if (extension->parentWidget() != this)
         extension->setParent(this);
     extension->hide();
 }
setModal()
void QDialog::setModal (bool modal)
Definition at line 1218 of file qdialog.cpp.
Referenced by QMessageBox::setWindowModality().
 {
     setAttribute(Qt::WA_ShowModal, modal);
 }
setOrientation()
void QDialog::setOrientation (Qt::Orientation orientation)
If orientation is Qt::Horizontal, the extension will be displayed to the right of the dialog's main area.
If orientation is Qt::Vertical, the extension will be displayed below the dialog's main area.
Instead of using this functionality, we recommend that you simply call show() or hide() on the part of the dialog that you want to use as an extension. See the Extension Example for details.
See also
setExtension()
Definition at line 1015 of file qdialog.cpp.
 {
     Q_D(QDialog);
     d->orientation = orientation;
 }
setResult()
void QDialog::setResult (int i)
Sets the modal dialog's result code to i.
Note
We recommend that you use one of the values defined by QDialog::DialogCode.
Definition at line 475 of file qdialog.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_btnPropertiesClicked(), QMessageBox::closeEvent(), done(), exec(), and open().
 {
     Q_D(QDialog);
     d->rescode = r;
 }
setSizeGripEnabled()
void QDialog::setSizeGripEnabled (bool enabled)
Definition at line 1235 of file qdialog.cpp.
Referenced by showExtension().
 {
 #ifdef QT_NO_SIZEGRIP
     Q_UNUSED(enabled);
 #else
     Q_D(QDialog);
 #ifndef QT_NO_SIZEGRIP
     d->sizeGripEnabled = enabled;
     if (enabled && d->doShowExtension)
         return;
 #endif
     if (!enabled != !d->resizer) {
         if (enabled) {
             d->resizer = new QSizeGrip(this);
             // adjustSize() processes all events, which is suboptimal
             d->resizer->resize(d->resizer->sizeHint());
             if (isRightToLeft())
                 d->resizer->move(rect().bottomLeft() -d->resizer->rect().bottomLeft());
             else
                 d->resizer->move(rect().bottomRight() -d->resizer->rect().bottomRight());
             d->resizer->raise();
             d->resizer->show();
         } else {
             delete d->resizer;
             d->resizer = 0;
         }
     }
 #endif //QT_NO_SIZEGRIP
 }
setVisible()
void QDialog::setVisible (bool visible) virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QFileDialog, QWizard, QInputDialog, QMessageBox, QPrintDialog, QFontDialog, QPageSetupDialog, and QPrintPreviewDialog.
Definition at line 756 of file qdialog.cpp.
Referenced by QPrintDialogPrivate::init(), QPrintDialogPrivate::selectPrinter(), QPrintPreviewDialog::setVisible(), QColorDialog::setVisible(), QFontDialog::setVisible(), QMessageBox::setVisible(), QInputDialog::setVisible(), QWizard::setVisible(), and QFileDialog::setVisible().
showEvent()
void QDialog::showEvent (QShowEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
Non-spontaneous show events are sent to widgets immediately before they are shown. The spontaneous show events of windows are delivered afterwards.
Note: A widget receives spontaneous show and hide events when its mapping status is changed by the window system, e.g. a spontaneous hide event when the user minimizes the window, and a spontaneous show event when the window is restored again. After receiving a spontaneous hide event, a widget is still considered visible in the sense of isVisible().
See also
visible, event(), QShowEvent
Reimplemented from QWidget.
Reimplemented in QMessageBox, QProgressDialog, and QPrintPropertiesDialog.
Definition at line 838 of file qdialog.cpp.
Referenced by QMessageBox::critical(), QProgressDialog::showEvent(), and QMessageBox::showEvent().
 {
     if (!event->spontaneous() && !testAttribute(Qt::WA_Moved)) {
         Qt::WindowStates  state = windowState();
         adjustPosition(parentWidget());
         setAttribute(Qt::WA_Moved, false); // not really an explicit position
         if (state != windowState())
             setWindowState(state);
     }
 }
showExtension
void QDialog::showExtension (bool showIt) slot
If showIt is true, the dialog's extension is shown; otherwise the extension is hidden.
Instead of using this functionality, we recommend that you simply call show() or hide() on the part of the dialog that you want to use as an extension. See the Extension Example for details.
See also
show(), setExtension(), setOrientation()
Definition at line 1109 of file qdialog.cpp.
Referenced by setVisible().
 {
     Q_D(QDialog);
     d->doShowExtension = showIt;
     if (!d->extension)
         return;
     if (!testAttribute(Qt::WA_WState_Visible))
         return;
     if (d->extension->isVisible() == showIt)
         return;
     if (showIt) {
         d->size = size();
         d->min = minimumSize();
         d->max = maximumSize();
         if (layout())
             layout()->setEnabled(false);
         QSize s(d->extension->sizeHint()
                  .expandedTo(d->extension->minimumSize())
                  .boundedTo(d->extension->maximumSize()));
         if (d->orientation == Qt::Horizontal) {
             int h = qMax(height(), s.height());
             d->extension->setGeometry(width(), 0, s.width(), h);
             setFixedSize(width() + s.width(), h);
         } else {
             int w = qMax(width(), s.width());
             d->extension->setGeometry(0, height(), w, s.height());
             setFixedSize(w, height() + s.height());
         }
         d->extension->show();
 #ifndef QT_NO_SIZEGRIP
         const bool sizeGripEnabled = isSizeGripEnabled();
         setSizeGripEnabled(false);
         d->sizeGripEnabled = sizeGripEnabled;
 #endif
     } else {
         d->extension->hide();
         // workaround for CDE window manager that won't shrink with (-1,-1)
         setMinimumSize(d->min.expandedTo(QSize(1, 1)));
         setMaximumSize(d->max);
         resize(d->size);
         if (layout())
             layout()->setEnabled(true);
 #ifndef QT_NO_SIZEGRIP
         setSizeGripEnabled(d->sizeGripEnabled);
 #endif
     }
 }
sizeHint()
QSize QDialog::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QMessageBox, QWizard, QInputDialog, and QProgressDialog.
Definition at line 1160 of file qdialog.cpp.
Referenced by QInputDialog::sizeHint(), and QMessageBox::sizeHint().
 {
     Q_D(const QDialog);
     if (d->extension) {
         if (d->orientation == Qt::Horizontal)
             return QSize(QWidget::sizeHint().width(),
                         qMax(QWidget::sizeHint().height(),d->extension->sizeHint().height()));
         else
             return QSize(qMax(QWidget::sizeHint().width(), d->extension->sizeHint().width()),
                         QWidget::sizeHint().height());
     }
 #if defined(Q_WS_S60)
     // if size is not fixed, try to adjust it according to S60 layoutting
     if (minimumSize() != maximumSize()) {
         // In S60, dialogs are always the width of screen (in portrait, regardless of current layout)
         return QSize(qMin(S60->screenHeightInPixels, S60->screenWidthInPixels), QWidget::sizeHint().height());
     } else {
         return QWidget::sizeHint();
     }
 #else
     return QWidget::sizeHint();
 #endif //Q_WS_S60
 }
Friends and Related Functions
QPushButton
friend class QPushButton friend
Definition at line 59 of file qdialog.h.
Referenced by QMessageBox::addButton(), QPrintPropertiesDialog::addItemToOptions(), QErrorMessage::QErrorMessage(), and QProgressDialog::setCancelButtonText().
Properties
modal
QDialog::modal private
whether show() should pop up the dialog as modal or modeless
By default, this property is false and show() pops up the dialog as modeless. Setting his property to true is equivalent to setting QWidget::windowModality to Qt::ApplicationModal.
exec() ignores the value of this property and always pops up the dialog as modal.
See also
QWidget::windowModality, show(), exec()
Definition at line 62 of file qdialog.h.
Referenced by QDialog(), and QMessageBox::setWindowModality().
sizeGripEnabled
QDialog::sizeGripEnabled private
whether the size grip is enabled
A QSizeGrip is placed in the bottom-right corner of the dialog when this property is enabled. By default, the size grip is disabled.
Definition at line 61 of file qdialog.h.
Referenced by showExtension().
The documentation for this class was generated from the following files:
/src/gui/dialogs/qdialog.h
/src/gui/dialogs/qdialog.cpp