Qt 4.8: QGraphicsItemPrivate Class Reference
QGraphicsItemPrivate Class Reference
#include <qgraphicsitem_p.h>
Classes
struct ExtraStruct
struct TransformData
Public Types
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Public Functions
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
virtual qreal height () const
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
virtual void resetHeight ()
virtual void resetWidth ()
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
virtual void resolveFont (uint inheritedMask)
virtual void resolvePalette (uint inheritedMask)
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
virtual void setHeight (qreal)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void setWidth (qreal)
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
virtual void transformChanged ()
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual qreal width () const
virtual ~QGraphicsItemPrivate ()
Static Public Functions
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Public Variables
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Detailed Description
Definition at line 158 of file qgraphicsitem_p.h.
Enumerations
AncestorFlag
enum QGraphicsItemPrivate::AncestorFlag
Enumerator
NoFlag
AncestorHandlesChildEvents
AncestorClipsChildren
AncestorIgnoresTransformations
AncestorFiltersChildEvents
Definition at line 170 of file qgraphicsitem_p.h.
                       {
         NoFlag = 0,
         AncestorHandlesChildEvents = 0x1,
         AncestorClipsChildren = 0x2,
         AncestorIgnoresTransformations = 0x4,
         AncestorFiltersChildEvents = 0x8
     };
Extra
enum QGraphicsItemPrivate::Extra
Enumerator
ExtraToolTip
ExtraCursor
ExtraCacheData
ExtraMaxDeviceCoordCacheSize
ExtraBoundingRegionGranularity
Definition at line 162 of file qgraphicsitem_p.h.
                {
         ExtraToolTip,
         ExtraCursor,
         ExtraCacheData,
         ExtraMaxDeviceCoordCacheSize,
         ExtraBoundingRegionGranularity
     };
InvalidateReason
enum QGraphicsItemPrivate::InvalidateReason
Enumerator
OpacityChanged
Definition at line 291 of file qgraphicsitem_p.h.
{
         OpacityChanged
     };
Constructors and Destructors
QGraphicsItemPrivate()
QGraphicsItemPrivate::QGraphicsItemPrivate () inline
Definition at line 178 of file qgraphicsitem_p.h.
         : z(0),
         opacity(1.),
         scene(0),
         parent(0),
         transformData(0),
         graphicsEffect(0),
         index(-1),
         siblingIndex(-1),
         itemDepth(-1),
         focusProxy(0),
         subFocusItem(0),
         focusScopeItem(0),
         imHints(Qt::ImhNone),
         panelModality(QGraphicsItem::NonModal),
         acceptedMouseButtons(0x1f),
         visible(1),
         explicitlyHidden(0),
         enabled(1),
         explicitlyDisabled(0),
         selected(0),
         acceptsHover(0),
         acceptDrops(0),
         isMemberOfGroup(0),
         handlesChildEvents(0),
         itemDiscovered(0),
         hasCursor(0),
         ancestorFlags(0),
         cacheMode(0),
         hasBoundingRegionGranularity(0),
         isWidget(0),
         dirty(0),
         dirtyChildren(0),
         localCollisionHack(0),
         inSetPosHelper(0),
         needSortChildren(0),
         allChildrenDirty(0),
         fullUpdatePending(0),
         dirtyChildrenBoundingRect(1),
         flags(0),
         paintedViewBoundingRectsNeedRepaint(0),
         dirtySceneTransform(1),
         geometryChanged(1),
         inDestructor(0),
         isObject(0),
         ignoreVisible(0),
         ignoreOpacity(0),
         acceptTouchEvents(0),
         acceptedTouchBeginEvent(0),
         filtersDescendantEvents(0),
         sceneTransformTranslateOnly(0),
         notifyBoundingRectChanged(0),
         notifyInvalidated(0),
         mouseSetsFocus(1),
         explicitActivate(0),
         wantsActive(0),
         holesInSiblingIndex(0),
         sequentialOrdering(1),
         updateDueToGraphicsEffect(0),
         scenePosDescendants(0),
         pendingPolish(0),
         mayHaveChildWithGraphicsEffect(0),
         isDeclarativeItem(0),
         sendParentChangeNotification(0),
         globalStackingOrder(-1),
         q_ptr(0)
     {
     }
~QGraphicsItemPrivate()
virtual QGraphicsItemPrivate::~QGraphicsItemPrivate () inline virtual
Definition at line 247 of file qgraphicsitem_p.h.
     { }
Functions
addChild()
void QGraphicsItemPrivate::addChild (QGraphicsItem * child)
QGraphicsScenePrivate::registerTopLevelItem().
Warning
This function is not part of the public interface.
This function is almost identical to
Definition at line 5794 of file qgraphicsitem.cpp.
 {
     // Remove all holes from the sibling index list. Now the max index
     // number is equal to the size of the children list.
     ensureSequentialSiblingIndex();
     needSortChildren = 1; // ### maybe 0
     child->d_ptr->siblingIndex = children.size();
     children.append(child);
     if (isObject)
         emit static_cast<QGraphicsObject *>(q_ptr)->childrenChanged();
 }
appendGraphicsTransform()
void QGraphicsItemPrivate::appendGraphicsTransform (QGraphicsTransform * t)
Warning
This function is not part of the public interface.
Definition at line 4305 of file qgraphicsitem.cpp.
 {
     if (!transformData)
         transformData = new QGraphicsItemPrivate::TransformData;
     if (!transformData->graphicsTransforms.contains(t))
         transformData->graphicsTransforms.append(t);
     Q_Q(QGraphicsItem);
     t->d_func()->setItem(q);
     transformData->onlyTransform = false;
     dirtySceneTransform = 1;
     transformChanged();
 }
calcEffectiveOpacity()
qreal QGraphicsItemPrivate::calcEffectiveOpacity () const inline
Definition at line 401 of file qgraphicsitem_p.h.
     {
         qreal o = opacity;
         QGraphicsItem *p = parent;
         int myFlags = flags;
         while (p) {
             int parentFlags = p->d_ptr->flags;
             // If I have a parent, and I don't ignore my parent's opacity, and my
             // parent propagates to me, then combine my local opacity with my parent's
             // effective opacity into my effective opacity.
             if ((myFlags & QGraphicsItem::ItemIgnoresParentOpacity)
                 || (parentFlags & QGraphicsItem::ItemDoesntPropagateOpacityToChildren)) {
                 break;
             }
             o *= p->d_ptr->opacity;
             p = p->d_ptr->parent;
             myFlags = parentFlags;
         }
         return o;
     }
children_append()
void QGraphicsItemPrivate::children_append (QDeclarativeListProperty< QGraphicsObject > * list, QGraphicsObject * item) static
Definition at line 8163 of file qgraphicsitem.cpp.
 {
     if (item) {
         QGraphicsObject *graphicsObject = static_cast<QGraphicsObject *>(list->object);
         if (QGraphicsItemPrivate::get(graphicsObject)->sendParentChangeNotification) {
             item->setParentItem(graphicsObject);
         } else {
             QGraphicsItemPrivate::get(item)->setParentItemHelper(graphicsObject, 0, 0);
         }
     }
 }
children_at()
QGraphicsObject * QGraphicsItemPrivate::children_at (QDeclarativeListProperty< QGraphicsObject > * list, int index) static
Definition at line 8181 of file qgraphicsitem.cpp.
 {
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(static_cast<QGraphicsObject *>(list->object));
     if (index >= 0 && index < d->children.count())
         return d->children.at(index)->toGraphicsObject();
     else
         return 0;
 }
children_clear()
void QGraphicsItemPrivate::children_clear (QDeclarativeListProperty< QGraphicsObject > * list) static
Definition at line 8190 of file qgraphicsitem.cpp.
 {
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(static_cast<QGraphicsObject *>(list->object));
     int childCount = d->children.count();
     if (d->sendParentChangeNotification) {
         for (int index = 0; index < childCount; index++)
             d->children.at(0)->setParentItem(0);
     } else {
         for (int index = 0; index < childCount; index++)
             QGraphicsItemPrivate::get(d->children.at(0))->setParentItemHelper(0, 0, 0);
     }
 }
children_count()
int QGraphicsItemPrivate::children_count (QDeclarativeListProperty< QGraphicsObject > * list) static
Definition at line 8175 of file qgraphicsitem.cpp.
 {
     QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(static_cast<QGraphicsObject *>(list->object));
     return d->children.count();
 }
childrenBoundingRectHelper()
void QGraphicsItemPrivate::childrenBoundingRectHelper (QTransform * x, QRectF * rect, QGraphicsItem * topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
Warning
This function is not part of the public interface.
Definition at line 1341 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::childrenBoundingRect(), and childrenBoundingRectHelper().
 {
     Q_Q(QGraphicsItem);
     QRectF childrenRect;
     QRectF *result = rect;
     rect = &childrenRect;
     const bool setTopMostEffectItem = !topMostEffectItem;
     for (int i = 0; i < children.size(); ++i) {
         QGraphicsItem *child = children.at(i);
         QGraphicsItemPrivate *childd = child->d_ptr.data();
         if (setTopMostEffectItem)
             topMostEffectItem = child;
         bool hasPos = !childd->pos.isNull();
         if (hasPos || childd->transformData) {
             // COMBINE
             QTransform matrix = childd->transformToParent();
             if (x)
                 matrix *= *x;
             *rect |= matrix.mapRect(child->d_ptr->effectiveBoundingRect(topMostEffectItem));
             if (!childd->children.isEmpty())
                 childd->childrenBoundingRectHelper(&matrix, rect, topMostEffectItem);
         } else {
             if (x)
                 *rect |= x->mapRect(child->d_ptr->effectiveBoundingRect(topMostEffectItem));
             else
                 *rect |= child->d_ptr->effectiveBoundingRect(topMostEffectItem);
             if (!childd->children.isEmpty())
                 childd->childrenBoundingRectHelper(x, rect, topMostEffectItem);
         }
     }
     if (flags & QGraphicsItem::ItemClipsChildrenToShape){
         if (x)
             *rect &= x->mapRect(q->boundingRect());
         else
             *rect &= q->boundingRect();
     }
     *result |= *rect;
 }
childrenClippedToShape()
bool QGraphicsItemPrivate::childrenClippedToShape () const inline
Definition at line 470 of file qgraphicsitem_p.h.
     { return (flags & QGraphicsItem::ItemClipsChildrenToShape) || children.isEmpty(); }
childrenCombineOpacity()
bool QGraphicsItemPrivate::childrenCombineOpacity () const inline
Definition at line 456 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsSceneIndexPrivate::recursive_items_helper().
     {
         if (!children.size())
             return true;
         if (flags & QGraphicsItem::ItemDoesntPropagateOpacityToChildren)
             return false;
         for (int i = 0; i < children.size(); ++i) {
             if (children.at(i)->d_ptr->flags & QGraphicsItem::ItemIgnoresParentOpacity)
                 return false;
         }
         return true;
     }
childrenList()
QDeclarativeListProperty< QGraphicsObject > QGraphicsItemPrivate::childrenList ()
Returns a list of this item's children.
The items are sorted by stacking order. This takes into account both the items' insertion order and their Z-values.
Definition at line 8210 of file qgraphicsitem.cpp.
Referenced by QDeclarativeFlickablePrivate::data_clear().
 {
     Q_Q(QGraphicsItem);
     if (isObject) {
         QGraphicsObject *that = static_cast<QGraphicsObject *>(q);
         return QDeclarativeListProperty<QGraphicsObject>(that, &children, children_append,
                                                          children_count, children_at, children_clear);
     } else {
         //QGraphicsItem is not supported for this property
         return QDeclarativeListProperty<QGraphicsObject>();
     }
 }
clearFocusHelper()
void QGraphicsItemPrivate::clearFocusHelper (bool giveFocusToParent)
Warning
This function is not part of the public interface.
Definition at line 3529 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::clearFocus().
 {
     QGraphicsItem *subFocusItem = q_ptr;
     if (flags & QGraphicsItem::ItemIsFocusScope) {
         while (subFocusItem->d_ptr->focusScopeItem)
             subFocusItem = subFocusItem->d_ptr->focusScopeItem;
     }
     if (giveFocusToParent) {
         // Pass focus to the closest parent focus scope
         if (!inDestructor) {
             QGraphicsItem *p = parent;
             while (p) {
                 if (p->flags() & QGraphicsItem::ItemIsFocusScope) {
                     if (p->d_ptr->focusScopeItem == q_ptr) {
                         p->d_ptr->focusScopeItem = 0;
                         if (!subFocusItem->hasFocus()) //if it has focus, focusScopeItemChange is called elsewhere
                             focusScopeItemChange(false);
                     }
                     if (subFocusItem->hasFocus())
                         p->d_ptr->setFocusHelper(Qt::OtherFocusReason, /* climb = */ false,
                                                  /* focusFromHide = */ false);
                     return;
                 }
                 p = p->d_ptr->parent;
             }
         }
     }
     if (subFocusItem->hasFocus()) {
         // Invisible items with focus must explicitly clear subfocus.
         clearSubFocus(q_ptr);
         // If this item has the scene's input focus, clear it.
         scene->setFocusItem(0);
     }
 }
clearSubFocus()
void QGraphicsItemPrivate::clearSubFocus (QGraphicsItem * rootItem = 0, QGraphicsItem * stopItem = 0)
Warning
This function is not part of the public interface.
Definition at line 5951 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::removeItemHelper(), setFocusHelper(), and setSubFocus().
 {
     // Reset sub focus chain.
     QGraphicsItem *parent = rootItem ? rootItem : q_ptr;
     do {
         if (parent->d_ptr->subFocusItem != q_ptr)
             break;
         parent->d_ptr->subFocusItem = 0;
         if (parent != stopItem && !parent->isAncestorOf(stopItem))
             parent->d_ptr->subFocusItemChange();
     } while (!parent->isPanel() && (parent = parent->d_ptr->parent));
 }
combineOpacityFromParent()
qreal QGraphicsItemPrivate::combineOpacityFromParent (qreal parentOpacity) const inline
Definition at line 447 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsSceneIndexPrivate::recursive_items_helper().
     {
         if (parent && !(flags & QGraphicsItem::ItemIgnoresParentOpacity)
             && !(parent->d_ptr->flags & QGraphicsItem::ItemDoesntPropagateOpacityToChildren)) {
             return parentOpacity * opacity;
         }
         return opacity;
     }
combineTransformFromParent()
void QGraphicsItemPrivate::combineTransformFromParent (QTransform * x, const QTransform * viewTransform = 0) const
Combines this item's position and transform onto transform.
Warning
This function is not part of the public interface.
If you need to change this function (e.g., adding more transformation modes / options), make sure to change QGraphicsItem::deviceTransform() as well.
Definition at line 1073 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::deviceTransform(), and QGraphicsItem::itemTransform().
 {
     // COMBINE
     if (viewTransform && itemIsUntransformable()) {
         *x = q_ptr->deviceTransform(*viewTransform);
     } else {
         x->translate(pos.x(), pos.y());
         if (transformData)
             *x = transformData->computedFullTransform(x);
     }
 }
combineTransformToParent()
void QGraphicsItemPrivate::combineTransformToParent (QTransform * x, const QTransform * viewTransform = 0) const
Combines this item's position and transform onto transform.
Warning
This function is not part of the public interface.
If you need to change this function (e.g., adding more transformation modes / options), make sure to change all places marked with COMBINE.
Definition at line 1048 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::itemTransform().
 {
     // COMBINE
     if (viewTransform && itemIsUntransformable()) {
         *x = q_ptr->deviceTransform(*viewTransform);
     } else {
         if (transformData)
             *x *= transformData->computedFullTransform();
         if (!pos.isNull())
             *x *= QTransform::fromTranslate(pos.x(), pos.y());
     }
 }
depth()
int QGraphicsItemPrivate::depth () const
Warning
This function is not part of the public interface.
Definition at line 5711 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::commonAncestorItem(), QGraphicsItem::isAncestorOf(), and qt_closestItemFirst().
 {
     if (itemDepth == -1)
         const_cast<QGraphicsItemPrivate *>(this)->resolveDepth();
     return itemDepth;
 }
discardUpdateRequest()
bool QGraphicsItemPrivate::discardUpdateRequest (bool ignoreVisibleBit = false, bool ignoreDirtyBit = false, bool ignoreOpacity = false) const
Returns true if we can discard an update request; otherwise false.
Warning
This function is not part of the public interface.
Definition at line 5697 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::markDirty().
 {
     // No scene, or if the scene is updating everything, means we have nothing
     // to do. The only exception is if the scene tracks the growing scene rect.
     return !scene
            || (!visible && !ignoreVisibleBit && !this->ignoreVisible)
            || (!ignoreDirtyBit && fullUpdatePending)
            || (!ignoreOpacity && !this->ignoreOpacity && childrenCombineOpacity() && isFullyTransparent());
 }
effectiveBoundingRect() [1/2]
QRectF QGraphicsItemPrivate::effectiveBoundingRect (QGraphicsItem * topMostEffectItem = 0) const
Returns the effective bounding rect of the item.
Warning
This function is not part of the public interface.
Since
4.6
If the item has no effect, this is the same as the item's bounding rect. If the item has an effect, the effective rect can be larger than the item's bouding rect, depending on the effect.
See also
boundingRect()
Definition at line 2994 of file qgraphicsitem.cpp.
Referenced by childrenBoundingRectHelper(), and effectiveBoundingRect().
 {
 #ifndef QT_NO_GRAPHICSEFFECT
     Q_Q(const QGraphicsItem);
     QRectF brect = effectiveBoundingRect(q_ptr->boundingRect());
     if (ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren || topMostEffectItem == q)
         return brect;
     const QGraphicsItem *effectParent = parent;
     while (effectParent) {
         QGraphicsEffect *effect = effectParent->d_ptr->graphicsEffect;
         if (scene && effect && effect->isEnabled()) {
             const QRectF brectInParentSpace = q->mapRectToItem(effectParent, brect);
             const QRectF effectRectInParentSpace = effectParent->d_ptr->effectiveBoundingRect(brectInParentSpace);
             brect = effectParent->mapRectToItem(q, effectRectInParentSpace);
         }
         if (effectParent->d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren
             || topMostEffectItem == effectParent) {
             return brect;
         }
         effectParent = effectParent->d_ptr->parent;
     }
     return brect;
 #else //QT_NO_GRAPHICSEFFECT
     return q_ptr->boundingRect();
 #endif //QT_NO_GRAPHICSEFFECT
 }
effectiveBoundingRect() [2/2]
QRectF QGraphicsItemPrivate::effectiveBoundingRect (const QRectF & rect) const
Returns the effective bounding rect of the given item space rect.
Warning
This function is not part of the public interface.
Since
4.6
If the item has no effect, the rect is returned unmodified. If the item has an effect, the effective rect can be extend beyond the item's bounding rect, depending on the effect.
See also
boundingRect()
Definition at line 2960 of file qgraphicsitem.cpp.
 {
 #ifndef QT_NO_GRAPHICSEFFECT
     Q_Q(const QGraphicsItem);
     QGraphicsEffect *effect = graphicsEffect;
     if (scene && effect && effect->isEnabled()) {
         if (scene->d_func()->views.isEmpty())
             return effect->boundingRectFor(rect);
         QRectF sceneRect = q->mapRectToScene(rect);
         QRectF sceneEffectRect;
         foreach (QGraphicsView *view, scene->views()) {
             QRectF deviceRect = view->d_func()->mapRectFromScene(sceneRect);
             QRect deviceEffectRect = effect->boundingRectFor(deviceRect).toAlignedRect();
             sceneEffectRect |= view->d_func()->mapRectToScene(deviceEffectRect);
         }
         return q->mapRectFromScene(sceneEffectRect);
     }
 #endif //QT_NO_GRAPHICSEFFECT
     return rect;
 }
effectiveOpacity()
qreal QGraphicsItemPrivate::effectiveOpacity () const inline
Definition at line 440 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::effectiveOpacity().
{
         if (!parent || !opacity)
             return opacity;
         return calcEffectiveOpacity();
     }
ensureSceneTransform()
void QGraphicsItemPrivate::ensureSceneTransform () inline
Definition at line 383 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::deviceTransform(), QGraphicsItem::itemTransform(), QGraphicsItem::sceneMatrix(), and QGraphicsItem::sceneTransform().
     {
         QGraphicsItem *that = q_func();
         ensureSceneTransformRecursive(&that);
     }
ensureSceneTransformRecursive()
void QGraphicsItemPrivate::ensureSceneTransformRecursive (QGraphicsItem ** topMostDirtyItem)
Definition at line 5891 of file qgraphicsitem.cpp.
Referenced by ensureSceneTransformRecursive().
 {
     Q_ASSERT(topMostDirtyItem);
     if (dirtySceneTransform)
         *topMostDirtyItem = q_ptr;
     if (parent)
         parent->d_ptr->ensureSceneTransformRecursive(topMostDirtyItem);
     if (*topMostDirtyItem == q_ptr) {
         if (!dirtySceneTransform)
             return; // OK, neither my ancestors nor I have dirty scene transforms.
         *topMostDirtyItem = 0;
     } else if (*topMostDirtyItem) {
         return; // Continue backtrack.
     }
     // This item and all its descendants have dirty scene transforms.
     // We're about to validate this item's scene transform, so we have to
     // invalidate all the children; otherwise there's no way for the descendants
     // to detect that the ancestor has changed.
     invalidateChildrenSceneTransform();
     // COMBINE my transform with the parent's scene transform.
     updateSceneTransformFromParent();
     Q_ASSERT(!dirtySceneTransform);
 }
ensureSequentialSiblingIndex()
void QGraphicsItemPrivate::ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
Warning
This function is not part of the public interface.
This function is almost identical to
QGraphicsScenePrivate::ensureSequentialTopLevelSiblingIndexes().
Definition at line 4956 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::registerTopLevelItem(), and QGraphicsItem::stackBefore().
 {
     if (!sequentialOrdering) {
         qSort(children.begin(), children.end(), insertionOrder);
         sequentialOrdering = 1;
         needSortChildren = 1;
     }
     if (holesInSiblingIndex) {
         holesInSiblingIndex = 0;
         for (int i = 0; i < children.size(); ++i)
             children[i]->d_ptr->siblingIndex = i;
     }
 }
ensureSortedChildren()
void QGraphicsItemPrivate::ensureSortedChildren () inline
Warning
This function is not part of the public interface.
Definition at line 824 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), QGraphicsItem::childItems(), QGraphicsScenePrivate::draw(), and QGraphicsSceneIndexPrivate::recursive_items_helper().
 {
     if (needSortChildren) {
         needSortChildren = 0;
         sequentialOrdering = 1;
         if (children.isEmpty())
             return;
         qSort(children.begin(), children.end(), qt_notclosestLeaf);
         for (int i = 0; i < children.size(); ++i) {
             if (children.at(i)->d_ptr->siblingIndex != i) {
                 sequentialOrdering = 0;
                 break;
             }
         }
     }
 }
extra()
QVariant QGraphicsItemPrivate::extra (Extra type) const inline
Definition at line 326 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::boundingRegionGranularity(), QGraphicsItem::cursor(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsProxyWidgetPrivate::embedSubWindow(), QGraphicsSvgItem::setMaximumCacheSize(), and QGraphicsItem::toolTip().
     {
         for (int i = 0; i < extras.size(); ++i) {
             const ExtraStruct &extra = extras.at(i);
             if (extra.type == type)
                 return extra.value;
         }
         return QVariant();
     }
extraItemCache()
QGraphicsItemCache * QGraphicsItemPrivate::extraItemCache () const
Warning
This function is not part of the public interface.
Definition at line 5844 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::drawItemHelper(), QGraphicsItem::setCacheMode(), and QGraphicsItem::update().
 {
     QGraphicsItemCache *c = (QGraphicsItemCache *)qvariant_cast<void *>(extra(ExtraCacheData));
     if (!c) {
         QGraphicsItemPrivate *that = const_cast<QGraphicsItemPrivate *>(this);
         c = new QGraphicsItemCache;
         that->setExtra(ExtraCacheData, QVariant::fromValue<void *>(c));
     }
     return c;
 }
focusScopeItemChange()
void QGraphicsItemPrivate::focusScopeItemChange (bool isSubFocusItem) virtual
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
Warning
This function is not part of the public interface.
Reimplemented in QDeclarativeItemPrivate.
Definition at line 6002 of file qgraphicsitem.cpp.
Referenced by setFocusHelper(), and setParentItemHelper().
 {
     Q_UNUSED(isSubFocusItem);
 }
genericMapFromScene()
QPointF QGraphicsItemPrivate::genericMapFromScene (const QPointF & pos, const QWidget * viewport) const
Maps the point pos from scene to item coordinates.
Warning
This function is not part of the public interface.
If view is passed and the item is untransformable, this function will correctly map pos from the scene using the view's transformation.
Definition at line 1022 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::contextMenuEvent(), QGraphicsScenePrivate::sendDragDropEvent(), QGraphicsScenePrivate::sendHoverEvent(), QGraphicsScenePrivate::sendMouseEvent(), QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber(), QGraphicsScenePrivate::updateTouchPointsForItem(), and QGraphicsScene::wheelEvent().
 {
     Q_Q(const QGraphicsItem);
     if (!itemIsUntransformable())
         return q->mapFromScene(pos);
     QGraphicsView *view = 0;
     if (viewport)
         view = qobject_cast<QGraphicsView *>(viewport->parentWidget());
     if (!view)
         return q->mapFromScene(pos);
     // ### More ping pong than needed.
     return q->deviceTransform(view->viewportTransform()).inverted().map(view->mapFromScene(pos));
 }
get() [1/2]
static const QGraphicsItemPrivate* QGraphicsItemPrivate::get (const QGraphicsItem * item) inline static
Definition at line 250 of file qgraphicsitem_p.h.
Referenced by QDeclarativeAnchorsPrivate::addDepend(), adjustedItemEffectiveBoundingRect(), adjustedPosition(), children_append(), children_at(), children_at_helper(), children_clear(), children_clear_helper(), children_count(), children_count_helper(), QDeclarativeLoaderPrivate::clear(), QDeclarativeListViewPrivate::createHighlight(), QDeclarativeListViewPrivate::createItem(), QDeclarativeItemPrivate::data_append(), QDeclarativeFlickablePrivate::data_append(), QDeclarativeFlickablePrivate::data_clear(), QDeclarativeColumn::doPositioning(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QDeclarativeAnchorsPrivate::fillChanged(), QDeclarativeItemPrivate::focusChanged(), QDeclarativePathViewPrivate::getItem(), hcenter(), QDeclarativeFlickablePrivate::init(), QDeclarativeLoaderPrivate::initResize(), QDeclarativeViewPrivate::initResize(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QDeclarativeAnchors::mirrored(), position(), QDeclarativeBasePositioner::prePositioning(), QDeclarativeItemKeyFilter::QDeclarativeItemKeyFilter(), QDeclarativePathViewPrivate::releaseItem(), QDeclarativeListViewPrivate::releaseItem(), QDeclarativeAnchorsPrivate::remDepend(), QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), QDeclarativeFlow::reportConflictingAnchors(), QDeclarativeFlipablePrivate::setBackTransform(), QDeclarativeAnchorsPrivate::setItemHeight(), QDeclarativeAnchorsPrivate::setItemSize(), QDeclarativeAnchorsPrivate::setItemWidth(), QDeclarativeView::setResizeMode(), QDeclarativeItemPrivate::transform_append(), QDeclarativeItemPrivate::transform_at(), QDeclarativeItemPrivate::transform_clear(), QDeclarativeItemPrivate::transform_count(), QDeclarativeBasePositionerPrivate::unwatchChanges(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeListViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), QDeclarativeListViewPrivate::updateHeader(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), QDeclarativeAnchorsPrivate::updateVerticalAnchors(), QDeclarativeFlickableVisibleArea::updateVisible(), vcenter(), QDeclarativeBasePositionerPrivate::watchChanges(), and QDeclarativeLoader::~QDeclarativeLoader().
     {
         return item->d_ptr.data();
     }
get() [2/2]
static QGraphicsItemPrivate* QGraphicsItemPrivate::get (QGraphicsItem * item) inline static
Definition at line 254 of file qgraphicsitem_p.h.
     {
         return item->d_ptr.data();
     }
hasTranslateOnlySceneTransform()
bool QGraphicsItemPrivate::hasTranslateOnlySceneTransform () inline
Definition at line 389 of file qgraphicsitem_p.h.
Referenced by QGraphicsView::fitInView(), QGraphicsItem::mapFromScene(), QGraphicsItem::mapRectFromScene(), QGraphicsItem::mapRectToScene(), QGraphicsItem::mapToScene(), QGraphicsItem::prepareGeometryChange(), and QGraphicsItem::sceneBoundingRect().
     {
         ensureSceneTransform();
         return sceneTransformTranslateOnly;
     }
height()
qreal QGraphicsItemPrivate::height () const virtual
Warning
This function is not part of the public interface. Returns the height of the item Reimplemented by QGraphicsWidget
Reimplemented in QDeclarativeItemPrivate, and QGraphicsWidgetPrivate.
Definition at line 8257 of file qgraphicsitem.cpp.
Referenced by adjustedPosition(), QDeclarativeColumn::doPositioning(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QDeclarativeAnchorsPrivate::fillChanged(), position(), QDeclarativeBasePositioner::prePositioning(), QDeclarativeFlipablePrivate::setBackTransform(), QDeclarativeAnchorsPrivate::updateVerticalAnchors(), and vcenter().
 {
     return 0;
 }
initStyleOption()
void QGraphicsItemPrivate::initStyleOption (QStyleOptionGraphicsItem * option, const QTransform & worldTransform, const QRegion & exposedRegion, bool allItems = false) const
Definition at line 1384 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::draw(), and QGraphicsView::paintEvent().
 {
     Q_ASSERT(option);
     Q_Q(const QGraphicsItem);
     // Initialize standard QStyleOption values.
     const QRectF brect = q->boundingRect();
     option->state = QStyle::State_None;
     option->rect = brect.toRect();
     option->levelOfDetail = 1;
     option->exposedRect = brect;
     if (selected)
         option->state |= QStyle::State_Selected;
     if (enabled)
         option->state |= QStyle::State_Enabled;
     if (q->hasFocus())
         option->state |= QStyle::State_HasFocus;
     if (scene) {
         if (scene->d_func()->hoverItems.contains(q_ptr))
             option->state |= QStyle::State_MouseOver;
         if (q == scene->mouseGrabberItem())
             option->state |= QStyle::State_Sunken;
     }
     if (!(flags & QGraphicsItem::ItemUsesExtendedStyleOption))
         return;
     // Initialize QStyleOptionGraphicsItem specific values (matrix, exposedRect).
     option->matrix = worldTransform.toAffine(); //### discards perspective
     if (!allItems) {
         // Determine the item's exposed area
         option->exposedRect = QRectF();
         const QTransform reverseMap = worldTransform.inverted();
         const QVector<QRect> exposedRects(exposedRegion.rects());
         for (int i = 0; i < exposedRects.size(); ++i) {
             option->exposedRect |= reverseMap.mapRect(QRectF(exposedRects.at(i)));
             if (option->exposedRect.contains(brect))
                 break;
         }
         option->exposedRect &= brect;
     }
 }
inputMethodQueryHelper()
QVariant QGraphicsItemPrivate::inputMethodQueryHelper (Qt::InputMethodQuery query) const virtual
This helper function helped us add input method query support in Qt 4.
Warning
This function is not part of the public interface.
4.1 without having to reimplement the inputMethodQuery() function in QGraphicsProxyWidget. ### Qt 5: Remove. We cannot remove it in 4.5+ even if we do reimplement the function properly, because apps compiled with 4.4 will not be able to call the reimplementation.
Reimplemented in QGraphicsProxyWidgetPrivate.
Definition at line 1134 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::inputMethodQuery().
 {
     Q_UNUSED(query);
     return QVariant();
 }
insertionOrder()
bool QGraphicsItemPrivate::insertionOrder (QGraphicsItem * a, QGraphicsItem * b) inline static
Warning
This function is not part of the public interface.
Definition at line 844 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::ensureSequentialTopLevelSiblingIndexes().
 {
     return a->d_ptr->siblingIndex < b->d_ptr->siblingIndex;
 }
invalidateChildGraphicsEffectsRecursively()
void QGraphicsItemPrivate::invalidateChildGraphicsEffectsRecursively (QGraphicsItemPrivate::InvalidateReason reason)
Definition at line 5734 of file qgraphicsitem.cpp.
Referenced by invalidateChildGraphicsEffectsRecursively(), and QGraphicsItem::setOpacity().
 {
     if (!mayHaveChildWithGraphicsEffect)
         return;
     for (int i = 0; i < children.size(); ++i) {
         QGraphicsItemPrivate *childPrivate = children.at(i)->d_ptr.data();
         if (reason == OpacityChanged && (childPrivate->flags & QGraphicsItem::ItemIgnoresParentOpacity))
             continue;
         if (childPrivate->graphicsEffect) {
             childPrivate->notifyInvalidated = 1;
             static_cast<QGraphicsItemEffectSourcePrivate *>(childPrivate->graphicsEffect->d_func()->source->d_func())->invalidateCache();
         }
         childPrivate->invalidateChildGraphicsEffectsRecursively(reason);
     }
 }
invalidateChildrenSceneTransform()
void QGraphicsItemPrivate::invalidateChildrenSceneTransform () inline
Definition at line 395 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsSceneIndexPrivate::recursive_items_helper().
     {
         for (int i = 0; i < children.size(); ++i)
             children.at(i)->d_ptr->dirtySceneTransform = 1;
     }
invalidateDepthRecursively()
void QGraphicsItemPrivate::invalidateDepthRecursively ()
Warning
This function is not part of the public interface.
Definition at line 5756 of file qgraphicsitem.cpp.
Referenced by invalidateDepthRecursively().
 {
     if (itemDepth == -1)
         return;
     itemDepth = -1;
     for (int i = 0; i < children.size(); ++i)
         children.at(i)->d_ptr->invalidateDepthRecursively();
 }
invalidateParentGraphicsEffectsRecursively()
void QGraphicsItemPrivate::invalidateParentGraphicsEffectsRecursively ()
Warning
This function is not part of the public interface.
Definition at line 5723 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setOpacity(), and QGraphicsItem::update().
 {
     QGraphicsItemPrivate *itemPrivate = this;
     do {
         if (itemPrivate->graphicsEffect && !itemPrivate->updateDueToGraphicsEffect) {
             itemPrivate->notifyInvalidated = 1;
             static_cast<QGraphicsItemEffectSourcePrivate *>(itemPrivate->graphicsEffect->d_func()->source->d_func())->invalidateCache();
         }
     } while ((itemPrivate = itemPrivate->parent ? itemPrivate->parent->d_ptr.data() : 0));
 }
isFullyTransparent()
bool QGraphicsItemPrivate::isFullyTransparent () const inline
Definition at line 430 of file qgraphicsitem_p.h.
     {
         if (isOpacityNull())
             return true;
         if (!parent)
             return false;
         return isOpacityNull(calcEffectiveOpacity());
     }
isInvisible()
bool QGraphicsItemPrivate::isInvisible () const inline
Definition at line 473 of file qgraphicsitem_p.h.
     {
         return !visible || (childrenCombineOpacity() && isFullyTransparent());
     }
isOpacityNull() [1/2]
bool QGraphicsItemPrivate::isOpacityNull () const inline
Definition at line 424 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::draw(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), and QGraphicsItem::setOpacity().
     { return (opacity < qreal(0.001)); }
isOpacityNull() [2/2]
static bool QGraphicsItemPrivate::isOpacityNull (qreal opacity) inline static
Definition at line 427 of file qgraphicsitem_p.h.
     { return (opacity < qreal(0.001)); }
isProxyWidget()
bool QGraphicsItemPrivate::isProxyWidget () const virtual
Warning
This function is not part of the public interface.
Tells us if it is a proxy widget
Reimplemented in QGraphicsProxyWidgetPrivate.
Definition at line 6025 of file qgraphicsitem.cpp.
Referenced by QGraphicsProxyWidgetPrivate::setWidget_helper().
 {
     return false;
 }
itemIsUntransformable()
bool QGraphicsItemPrivate::itemIsUntransformable () const inline
Definition at line 266 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::deviceTransform(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsSceneBspTreeIndex::itemChange(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsView::paintEvent(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), and QGraphicsViewPrivate::setUpdateClip().
     {
         return (flags & QGraphicsItem::ItemIgnoresTransformations)
             || (ancestorFlags & AncestorIgnoresTransformations);
     }
markParentDirty()
void QGraphicsItemPrivate::markParentDirty (bool updateBoundingRect = false) inline
Warning
This function is not part of the public interface.
Definition at line 852 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), QGraphicsItem::prepareGeometryChange(), and QGraphicsItem::setFlags().
 {
     QGraphicsItemPrivate *parentp = this;
 #ifndef QT_NO_GRAPHICSEFFECT
     if (updateBoundingRect && parentp->graphicsEffect && !parentp->inSetPosHelper) {
         parentp->notifyInvalidated = 1;
         static_cast<QGraphicsItemEffectSourcePrivate *>(parentp->graphicsEffect->d_func()
                                                         ->source->d_func())->invalidateCache();
     }
 #endif
     while (parentp->parent) {
         parentp = parentp->parent->d_ptr.data();
         parentp->dirtyChildren = 1;
         if (updateBoundingRect) {
             parentp->dirtyChildrenBoundingRect = 1;
             // ### Only do this if the parent's effect applies to the entire subtree.
             parentp->notifyBoundingRectChanged = 1;
         }
 #ifndef QT_NO_GRAPHICSEFFECT
         if (parentp->graphicsEffect) {
             if (updateBoundingRect) {
                 static_cast<QGraphicsItemEffectSourcePrivate *>(parentp->graphicsEffect->d_func()
                                                                 ->source->d_func())->invalidateCache();
                 parentp->notifyInvalidated = 1;
             }
             if (parentp->scene && parentp->graphicsEffect->isEnabled()) {
                 parentp->dirty = 1;
                 parentp->fullUpdatePending = 1;
             }
         }
 #endif
     }
 }
maybeExtraItemCache()
QGraphicsItemCache * QGraphicsItemPrivate::maybeExtraItemCache () const
Warning
This function is not part of the public interface.
Definition at line 5836 of file qgraphicsitem.cpp.
 {
     return (QGraphicsItemCache *)qvariant_cast<void *>(extra(ExtraCacheData));
 }
movableAncestorIsSelected()
bool QGraphicsItemPrivate::movableAncestorIsSelected (const QGraphicsItem * item) static
Definition at line 7529 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::mouseMoveEvent().
 {
     const QGraphicsItem *parent = item->d_ptr->parent;
     return parent && (((parent->flags() & QGraphicsItem::ItemIsMovable) && parent->isSelected()) || _qt_movableAncestorIsSelected(parent));
 }
prependGraphicsTransform()
void QGraphicsItemPrivate::prependGraphicsTransform (QGraphicsTransform * t)
Warning
This function is not part of the public interface.
Definition at line 4288 of file qgraphicsitem.cpp.
Referenced by QDeclarativeItemPrivate::transform_append().
 {
     if (!transformData)
         transformData = new QGraphicsItemPrivate::TransformData;
     if (!transformData->graphicsTransforms.contains(t))
         transformData->graphicsTransforms.prepend(t);
     Q_Q(QGraphicsItem);
     t->d_func()->setItem(q);
     transformData->onlyTransform = false;
     dirtySceneTransform = 1;
     transformChanged();
 }
remapItemPos()
void QGraphicsItemPrivate::remapItemPos (QEvent * event, QGraphicsItem * item)
Maps any item pos properties of event to item's coordinate system.
Warning
This function is not part of the public interface.
Definition at line 973 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::sceneEvent().
 {
     Q_Q(QGraphicsItem);
     switch (event->type()) {
     case QEvent::GraphicsSceneMouseMove:
     case QEvent::GraphicsSceneMousePress:
     case QEvent::GraphicsSceneMouseRelease:
     case QEvent::GraphicsSceneMouseDoubleClick: {
         QGraphicsSceneMouseEvent *mouseEvent = static_cast<QGraphicsSceneMouseEvent *>(event);
         mouseEvent->setPos(item->mapFromItem(q, mouseEvent->pos()));
         mouseEvent->setLastPos(item->mapFromItem(q, mouseEvent->pos()));
         for (int i = 0x1; i <= 0x10; i <<= 1) {
             if (mouseEvent->buttons() & i) {
                 Qt::MouseButton button = Qt::MouseButton(i);
                 mouseEvent->setButtonDownPos(button, item->mapFromItem(q, mouseEvent->buttonDownPos(button)));
             }
         }
         break;
     }
     case QEvent::GraphicsSceneWheel: {
         QGraphicsSceneWheelEvent *wheelEvent = static_cast<QGraphicsSceneWheelEvent *>(event);
         wheelEvent->setPos(item->mapFromItem(q, wheelEvent->pos()));
         break;
     }
     case QEvent::GraphicsSceneContextMenu: {
         QGraphicsSceneContextMenuEvent *contextEvent = static_cast<QGraphicsSceneContextMenuEvent *>(event);
         contextEvent->setPos(item->mapFromItem(q, contextEvent->pos()));
         break;
     }
     case QEvent::GraphicsSceneHoverMove: {
         QGraphicsSceneHoverEvent *hoverEvent = static_cast<QGraphicsSceneHoverEvent *>(event);
         hoverEvent->setPos(item->mapFromItem(q, hoverEvent->pos()));
         break;
     }
     default:
         break;
     }
 }
removeChild()
void QGraphicsItemPrivate::removeChild (QGraphicsItem * child)
QGraphicsScenePrivate::unregisterTopLevelItem().
Warning
This function is not part of the public interface.
This function is almost identical to
Definition at line 5815 of file qgraphicsitem.cpp.
 {
     // When removing elements in the middle of the children list,
     // there will be a "gap" in the list of sibling indexes (0,1,3,4).
     if (!holesInSiblingIndex)
         holesInSiblingIndex = child->d_ptr->siblingIndex != children.size() - 1;
     if (sequentialOrdering && !holesInSiblingIndex)
         children.removeAt(child->d_ptr->siblingIndex);
     else
         children.removeOne(child);
     // NB! Do not use children.removeAt(child->d_ptr->siblingIndex) because
     // the child is not guaranteed to be at the index after the list is sorted.
     // (see ensureSortedChildren()).
     child->d_ptr->siblingIndex = -1;
     if (isObject)
         emit static_cast<QGraphicsObject *>(q_ptr)->childrenChanged();
 }
removeExtraItemCache()
void QGraphicsItemPrivate::removeExtraItemCache ()
Warning
This function is not part of the public interface.
Definition at line 5858 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setCacheMode(), and QGraphicsItem::~QGraphicsItem().
 {
     QGraphicsItemCache *c = (QGraphicsItemCache *)qvariant_cast<void *>(extra(ExtraCacheData));
     if (c) {
         c->purge();
         delete c;
     }
     unsetExtra(ExtraCacheData);
 }
resetFocusProxy()
void QGraphicsItemPrivate::resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
Warning
This function is not part of the public interface.
Qt 5: Use QPointer instead.
Definition at line 5973 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::removeItemHelper(), and QGraphicsItem::~QGraphicsItem().
 {
     for (int i = 0; i < focusProxyRefs.size(); ++i)
         *focusProxyRefs.at(i) = 0;
     focusProxyRefs.clear();
 }
resetHeight()
void QGraphicsItemPrivate::resetHeight () virtual
Warning
This function is not part of the public interface. Reset the height of the item Reimplemented by QGraphicsWidget
Reimplemented in QDeclarativeItemPrivate, and QGraphicsWidgetPrivate.
Definition at line 8277 of file qgraphicsitem.cpp.
 {
 }
resetWidth()
void QGraphicsItemPrivate::resetWidth () virtual
Warning
This function is not part of the public interface. Reset the width of the item Reimplemented by QGraphicsWidget
Reimplemented in QDeclarativeItemPrivate, and QGraphicsWidgetPrivate.
Definition at line 8248 of file qgraphicsitem.cpp.
 {
 }
resolveDepth()
void QGraphicsItemPrivate::resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
Warning
This function is not part of the public interface.
Definition at line 5774 of file qgraphicsitem.cpp.
 {
     if (!parent)
         itemDepth = 0;
     else {
         if (parent->d_ptr->itemDepth == -1)
             parent->d_ptr->resolveDepth();
         itemDepth = parent->d_ptr->itemDepth + 1;
     }
 }
resolveFont()
virtual void QGraphicsItemPrivate::resolveFont (uint inheritedMask) inline virtual
Reimplemented in QGraphicsWidgetPrivate.
Definition at line 312 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), QGraphicsWidgetPrivate::updateFont(), and QGraphicsScenePrivate::updateFont().
     {
         for (int i = 0; i < children.size(); ++i)
             children.at(i)->d_ptr->resolveFont(inheritedMask);
     }
resolvePalette()
virtual void QGraphicsItemPrivate::resolvePalette (uint inheritedMask) inline virtual
Reimplemented in QGraphicsWidgetPrivate.
Definition at line 318 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), QGraphicsWidgetPrivate::updatePalette(), and QGraphicsScenePrivate::updatePalette().
     {
         for (int i = 0; i < children.size(); ++i)
             children.at(i)->d_ptr->resolveFont(inheritedMask);
     }
sceneEffectiveBoundingRect()
QRectF QGraphicsItemPrivate::sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
Warning
This function is not part of the public interface.
Since
4.6
If the item has no effect, this is the same as sceneBoundingRect().
See also
effectiveBoundingRect(), sceneBoundingRect()
Definition at line 3038 of file qgraphicsitem.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::removeItem().
 {
     // Find translate-only offset
     // COMBINE
     QPointF offset;
     const QGraphicsItem *parentItem = q_ptr;
     const QGraphicsItemPrivate *itemd;
     do {
         itemd = parentItem->d_ptr.data();
         if (itemd->transformData)
             break;
         offset += itemd->pos;
     } while ((parentItem = itemd->parent));
     QRectF br = effectiveBoundingRect();
     br.translate(offset);
     return !parentItem ? br : parentItem->sceneTransform().mapRect(br);
 }
sendScenePosChange()
void QGraphicsItemPrivate::sendScenePosChange () inline
Warning
This function is not part of the public interface.
Definition at line 4973 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setPos(), and QGraphicsItem::setTransform().
 {
     Q_Q(QGraphicsItem);
     if (scene) {
         if (flags & QGraphicsItem::ItemSendsScenePositionChanges)
             q->itemChange(QGraphicsItem::ItemScenePositionHasChanged, q->scenePos());
         if (scenePosDescendants) {
             foreach (QGraphicsItem *item, scene->d_func()->scenePosItems) {
                 if (q->isAncestorOf(item))
                     item->itemChange(QGraphicsItem::ItemScenePositionHasChanged, item->scenePos());
             }
         }
     }
 }
setEnabledHelper()
void QGraphicsItemPrivate::setEnabledHelper (bool newEnabled, bool explicitly, bool update = true)
Sets this item's visibility to newEnabled.
Warning
This function is not part of the public interface.
If explicitly is true, this item will be "explicitly" newEnabled; otherwise, it.. will not be.
Definition at line 2618 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setEnabled(), and setEnabledHelper().
 {
     // Update explicit bit.
     if (explicitly)
         explicitlyDisabled = newEnabled ? 0 : 1;
     // Check if there's nothing to do.
     if (enabled == quint32(newEnabled))
         return;
     // Certain properties are dropped when an item is disabled.
     if (!newEnabled) {
         if (scene && scene->mouseGrabberItem() == q_ptr)
             q_ptr->ungrabMouse();
         if (q_ptr->hasFocus()) {
             // Disabling the closest non-panel ancestor of the focus item
             // causes focus to pop to the next item, otherwise it's cleared.
             QGraphicsItem *focusItem = scene->focusItem();
             if (isWidget && !focusItem->isPanel() && q_ptr->isAncestorOf(focusItem)) {
                 do {
                     if (focusItem == q_ptr) {
                         static_cast<QGraphicsWidget *>(q_ptr)->focusNextPrevChild(true);
                         break;
                     }
                 } while ((focusItem = focusItem->parentWidget()) && !focusItem->isPanel());
             }
             // Clear focus if previous steps didn't move it to another widget
             if (q_ptr->hasFocus())
                 q_ptr->clearFocus();
         }
         if (q_ptr->isSelected())
             q_ptr->setSelected(false);
     }
     // Modify the property.
     const QVariant newEnabledVariant(q_ptr->itemChange(QGraphicsItem::ItemEnabledChange,
                                                        quint32(newEnabled)));
     enabled = newEnabledVariant.toBool();
     // Schedule redraw.
     if (update)
         q_ptr->update();
     foreach (QGraphicsItem *child, children) {
         if (!newEnabled || !child->d_ptr->explicitlyDisabled)
             child->d_ptr->setEnabledHelper(newEnabled, /* explicitly = */ false);
     }
     // Deliver post-change notification.
     q_ptr->itemChange(QGraphicsItem::ItemEnabledHasChanged, newEnabledVariant);
     if (isObject)
         emit static_cast<QGraphicsObject *>(q_ptr)->enabledChanged();
 }
setExtra()
void QGraphicsItemPrivate::setExtra (Extra type, const QVariant & value) inline
Definition at line 336 of file qgraphicsitem_p.h.
Referenced by extraItemCache(), QGraphicsItem::setBoundingRegionGranularity(), QGraphicsItem::setCursor(), QGraphicsSvgItem::setMaximumCacheSize(), and QGraphicsItem::setToolTip().
     {
         int index = -1;
         for (int i = 0; i < extras.size(); ++i) {
             if (extras.at(i).type == type) {
                 index = i;
                 break;
             }
         }
         if (index == -1) {
             extras << ExtraStruct(type, value);
         } else {
             extras[index].value = value;
         }
     }
setFocusHelper()
void QGraphicsItemPrivate::setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
Warning
This function is not part of the public interface.
Definition at line 3450 of file qgraphicsitem.cpp.
Referenced by clearFocusHelper(), QGraphicsItem::setFocus(), and setVisibleHelper().
 {
     // Disabled / unfocusable items cannot accept focus.
     if (!q_ptr->isEnabled() || !(flags & QGraphicsItem::ItemIsFocusable))
         return;
     // Find focus proxy.
     QGraphicsItem *f = q_ptr;
     while (f->d_ptr->focusProxy)
         f = f->d_ptr->focusProxy;
     // Return if it already has focus.
     if (scene && scene->focusItem() == f)
         return;
     // Update focus scope item ptr.
     QGraphicsItem *p = parent;
     while (p) {
         if (p->flags() & QGraphicsItem::ItemIsFocusScope) {
             QGraphicsItem *oldFocusScopeItem = p->d_ptr->focusScopeItem;
             p->d_ptr->focusScopeItem = q_ptr;
             if (oldFocusScopeItem)
                 oldFocusScopeItem->d_ptr->focusScopeItemChange(false);
             focusScopeItemChange(true);
             if (!p->focusItem() && !focusFromHide) {
                 // Calling setFocus() on a child of a focus scope that does
                 // not have focus changes only the focus scope pointer,
                 // so that focus is restored the next time the scope gains
                 // focus.
                 return;
             }
             break;
         }
         p = p->d_ptr->parent;
     }
     if (climb) {
         while (f->d_ptr->focusScopeItem && f->d_ptr->focusScopeItem->isVisible())
             f = f->d_ptr->focusScopeItem;
     }
     // Update the child focus chain.
     QGraphicsItem *commonAncestor = 0;
     if (scene && scene->focusItem()) {
         commonAncestor = scene->focusItem()->commonAncestorItem(f);
         scene->focusItem()->d_ptr->clearSubFocus(scene->focusItem(), commonAncestor);
     }
     f->d_ptr->setSubFocus(f, commonAncestor);
     // Update the scene's focus item.
     if (scene) {
         QGraphicsItem *p = q_ptr->panel();
         if ((!p && scene->isActive()) || (p && p->isActive())) {
             // Visible items immediately gain focus from scene.
             scene->d_func()->setFocusItemHelper(f, focusReason);
         }
     }
 }
setHeight()
void QGraphicsItemPrivate::setHeight (qreal h) virtual
Warning
This function is not part of the public interface. Set the height of the item Reimplemented by QGraphicsWidget
Reimplemented in QDeclarativeItemPrivate, and QGraphicsWidgetPrivate.
Definition at line 8267 of file qgraphicsitem.cpp.
Referenced by QDeclarativeAnchorsPrivate::setItemHeight().
 {
     Q_UNUSED(h);
 }
setIsMemberOfGroup()
void QGraphicsItemPrivate::setIsMemberOfGroup (bool enabled)
Propagates item group membership.
Warning
This function is not part of the public interface.
Definition at line 955 of file qgraphicsitem.cpp.
 {
     Q_Q(QGraphicsItem);
     isMemberOfGroup = enabled;
     if (!qgraphicsitem_cast<QGraphicsItemGroup *>(q)) {
         foreach (QGraphicsItem *child, children)
             child->d_func()->setIsMemberOfGroup(enabled);
     }
 }
setParentItemHelper()
void QGraphicsItemPrivate::setParentItemHelper (QGraphicsItem * newParent, const QVariant * newParentVariant, const QVariant * thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
Warning
This function is not part of the public interface.
g., prepareGeometryChange) if the item is in its destructor, i.e. inDestructor is 1.
Definition at line 1150 of file qgraphicsitem.cpp.
Referenced by children_append(), QDeclarativeItemPrivate::data_append(), QDeclarativeFlickablePrivate::data_append(), QGraphicsWidgetPrivate::init(), and QGraphicsItem::setParentItem().
 {
     Q_Q(QGraphicsItem);
     if (newParent == parent)
         return;
     if (isWidget)
         static_cast<QGraphicsWidgetPrivate *>(this)->fixFocusChainBeforeReparenting((newParent &&
                                                         newParent->isWidget()) ? static_cast<QGraphicsWidget *>(newParent) : 0,
                                                         scene);
     if (scene) {
         // Deliver the change to the index
         if (scene->d_func()->indexMethod != QGraphicsScene::NoIndex)
             scene->d_func()->index->itemChange(q, QGraphicsItem::ItemParentChange, newParent);
         // Disable scene pos notifications for old ancestors
         if (scenePosDescendants || (flags & QGraphicsItem::ItemSendsScenePositionChanges))
             scene->d_func()->setScenePosItemEnabled(q, false);
     }
     if (subFocusItem && parent) {
         // Make sure none of the old parents point to this guy.
         subFocusItem->d_ptr->clearSubFocus(parent);
     }
     // We anticipate geometry changes. If the item is deleted, it will be
     // removed from the index at a later stage, and the whole scene will be
     // updated.
     if (!inDestructor)
         q_ptr->prepareGeometryChange();
     if (parent) {
         // Remove from current parent
         parent->d_ptr->removeChild(q);
         if (thisPointerVariant)
             parent->itemChange(QGraphicsItem::ItemChildRemovedChange, *thisPointerVariant);
     }
     // Update toplevelitem list. If this item is being deleted, its parent
     // will be 0 but we don't want to register/unregister it in the TLI list.
     if (scene && !inDestructor) {
         if (parent && !newParent) {
             scene->d_func()->registerTopLevelItem(q);
         } else if (!parent && newParent) {
             scene->d_func()->unregisterTopLevelItem(q);
         }
     }
     // Ensure any last parent focus scope does not point to this item or any of
     // its descendents.
     QGraphicsItem *p = parent;
     QGraphicsItem *parentFocusScopeItem = 0;
     while (p) {
         if (p->d_ptr->flags & QGraphicsItem::ItemIsFocusScope) {
             // If this item's focus scope's focus scope item points
             // to this item or a descendent, then clear it.
             QGraphicsItem *fsi = p->d_ptr->focusScopeItem;
             if (q_ptr == fsi || q_ptr->isAncestorOf(fsi)) {
                 parentFocusScopeItem = fsi;
                 p->d_ptr->focusScopeItem = 0;
             }
             break;
         }
         p = p->d_ptr->parent;
     }
     // Update graphics effect optimization flag
     if (newParent && (graphicsEffect || mayHaveChildWithGraphicsEffect))
         newParent->d_ptr->updateChildWithGraphicsEffectFlagRecursively();
     // Update focus scope item ptr in new scope.
     QGraphicsItem *newFocusScopeItem = subFocusItem ? subFocusItem : parentFocusScopeItem;
     if (newFocusScopeItem && newParent) {
         QGraphicsItem *p = newParent;
         while (p) {
             if (p->d_ptr->flags & QGraphicsItem::ItemIsFocusScope) {
                 if (subFocusItem && subFocusItem != q_ptr) {
                     // Find the subFocusItem's topmost focus scope within the new parent's focusscope
                     QGraphicsItem *ancestorScope = 0;
                     QGraphicsItem *p2 = subFocusItem->d_ptr->parent;
                     while (p2 && p2 != p) {
                         if (p2->d_ptr->flags & QGraphicsItem::ItemIsFocusScope)
                             ancestorScope = p2;
                         if (p2->d_ptr->flags & QGraphicsItem::ItemIsPanel)
                             break;
                         if (p2 == q_ptr)
                             break;
                         p2 = p2->d_ptr->parent;
                     }
                     if (ancestorScope)
                         newFocusScopeItem = ancestorScope;
                 }
                 p->d_ptr->focusScopeItem = newFocusScopeItem;
                 newFocusScopeItem->d_ptr->focusScopeItemChange(true);
                 // Ensure the new item is no longer the subFocusItem. The
                 // only way to set focus on a child of a focus scope is
                 // by setting focus on the scope itself.
                 if (subFocusItem && !p->focusItem())
                     subFocusItem->d_ptr->clearSubFocus();
                 break;
             }
             p = p->d_ptr->parent;
         }
     }
     // Resolve depth.
     invalidateDepthRecursively();
     if ((parent = newParent)) {
         if (parent->d_func()->scene && parent->d_func()->scene != scene) {
             // Move this item to its new parent's scene
             parent->d_func()->scene->addItem(q);
         } else if (!parent->d_func()->scene && scene) {
             // Remove this item from its former scene
             scene->removeItem(q);
         }
         parent->d_ptr->addChild(q);
         if (thisPointerVariant)
             parent->itemChange(QGraphicsItem::ItemChildAddedChange, *thisPointerVariant);
         if (scene) {
             // Re-enable scene pos notifications for new ancestors
             if (scenePosDescendants || (flags & QGraphicsItem::ItemSendsScenePositionChanges))
                 scene->d_func()->setScenePosItemEnabled(q, true);
         }
         // Propagate dirty flags to the new parent
         markParentDirty(/*updateBoundingRect=*/true);
         // Inherit ancestor flags from the new parent.
         updateAncestorFlags();
         // Update item visible / enabled.
         if (parent->d_ptr->visible != visible) {
             if (!parent->d_ptr->visible || !explicitlyHidden)
                 setVisibleHelper(parent->d_ptr->visible, /* explicit = */ false, /* update = */ false);
         }
         if (parent->isEnabled() != enabled) {
             if (!parent->d_ptr->enabled || !explicitlyDisabled)
                 setEnabledHelper(parent->d_ptr->enabled, /* explicit = */ false, /* update = */ false);
         }
         // Auto-activate if visible and the parent is active.
         if (visible && parent->isActive())
             q->setActive(true);
     } else {
         // Inherit ancestor flags from the new parent.
         updateAncestorFlags();
         if (!inDestructor) {
             // Update item visible / enabled.
             if (!visible && !explicitlyHidden)
                 setVisibleHelper(true, /* explicit = */ false);
             if (!enabled && !explicitlyDisabled)
                 setEnabledHelper(true, /* explicit = */ false);
         }
     }
     dirtySceneTransform = 1;
     if (!inDestructor && (transformData || (newParent && newParent->d_ptr->transformData)))
         transformChanged();
     // Reparenting is finished, now safe to notify the previous focusScopeItem about changes
     if (parentFocusScopeItem)
       parentFocusScopeItem->d_ptr->focusScopeItemChange(false);
     // Restore the sub focus chain.
     if (subFocusItem) {
         subFocusItem->d_ptr->setSubFocus(newParent);
         if (parent && parent->isActive())
             subFocusItem->setFocus();
     }
     // Deliver post-change notification
     if (newParentVariant)
         q->itemChange(QGraphicsItem::ItemParentHasChanged, *newParentVariant);
     if (isObject)
         emit static_cast<QGraphicsObject *>(q)->parentChanged();
 }
setPosHelper()
void QGraphicsItemPrivate::setPosHelper (const QPointF & pos) virtual
Sets the position pos.
Warning
This function is not part of the public interface.
Reimplemented in QDeclarativeItemPrivate.
Definition at line 3903 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setPos(), and QDeclarativeItemPrivate::setPosHelper().
 {
     Q_Q(QGraphicsItem);
     inSetPosHelper = 1;
     if (scene)
         q->prepareGeometryChange();
     QPointF oldPos = this->pos;
     this->pos = pos;
     dirtySceneTransform = 1;
     inSetPosHelper = 0;
     if (isObject) {
         if (pos.x() != oldPos.x())
             emit static_cast<QGraphicsObject *>(q_ptr)->xChanged();
         if (pos.y() != oldPos.y())
             emit static_cast<QGraphicsObject *>(q_ptr)->yChanged();
     }
 }
setSubFocus()
void QGraphicsItemPrivate::setSubFocus (QGraphicsItem * rootItem = 0, QGraphicsItem * stopItem = 0)
Warning
This function is not part of the public interface.
Definition at line 5923 of file qgraphicsitem.cpp.
Referenced by setFocusHelper().
 {
     // Update focus child chain. Stop at panels, or if this item
     // is hidden, stop at the first item with a visible parent.
     QGraphicsItem *parent = rootItem ? rootItem : q_ptr;
     if (parent->panel() != q_ptr->panel())
         return;
     do {
         // Clear any existing ancestor's subFocusItem.
         if (parent != q_ptr && parent->d_ptr->subFocusItem) {
             if (parent->d_ptr->subFocusItem == q_ptr)
                 break;
             parent->d_ptr->subFocusItem->d_ptr->clearSubFocus(0, stopItem);
         }
         parent->d_ptr->subFocusItem = q_ptr;
         parent->d_ptr->subFocusItemChange();
     } while (!parent->isPanel() && (parent = parent->d_ptr->parent) && (visible || !parent->d_ptr->visible));
     if (scene && !scene->isActive()) {
         scene->d_func()->passiveFocusItem = subFocusItem;
         scene->d_func()->lastFocusItem = subFocusItem;
     }
 }
setTransformHelper()
void QGraphicsItemPrivate::setTransformHelper (const QTransform & transform)
Sets the transform transform.
Warning
This function is not part of the public interface.
Definition at line 3929 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setMatrix(), and QGraphicsItem::setTransform().
 {
     q_ptr->prepareGeometryChange();
     transformData->transform = transform;
     dirtySceneTransform = 1;
     transformChanged();
 }
setVisibleHelper()
void QGraphicsItemPrivate::setVisibleHelper (bool newVisible, bool explicitly, bool update = true)
Sets this item's visibility to newVisible.
Warning
This function is not part of the public interface.
If explicitly is true, this item will be "explicitly" newVisible; otherwise, it.. will not be.
Definition at line 2387 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setVisible(), and setVisibleHelper().
 {
     Q_Q(QGraphicsItem);
     // Update explicit bit.
     if (explicitly)
         explicitlyHidden = newVisible ? 0 : 1;
     // Check if there's nothing to do.
     if (visible == quint32(newVisible))
         return;
     // Don't show child if parent is not visible
     if (parent && newVisible && !parent->d_ptr->visible)
         return;
     // Modify the property.
     const QVariant newVisibleVariant(q_ptr->itemChange(QGraphicsItem::ItemVisibleChange,
                                                        quint32(newVisible)));
     newVisible = newVisibleVariant.toBool();
     if (visible == quint32(newVisible))
         return;
     visible = newVisible;
     // Schedule redrawing
     if (update) {
         QGraphicsItemCache *c = (QGraphicsItemCache *)qvariant_cast<void *>(extra(ExtraCacheData));
         if (c)
             c->purge();
         if (scene) {
 #ifndef QT_NO_GRAPHICSEFFECT
             invalidateParentGraphicsEffectsRecursively();
 #endif //QT_NO_GRAPHICSEFFECT
             scene->d_func()->markDirty(q_ptr, QRectF(), /*invalidateChildren=*/false, /*force=*/true);
         }
     }
     // Certain properties are dropped as an item becomes invisible.
     bool hasFocus = q_ptr->hasFocus();
     if (!newVisible) {
         if (scene) {
             if (scene->d_func()->mouseGrabberItems.contains(q))
                 q->ungrabMouse();
             if (scene->d_func()->keyboardGrabberItems.contains(q))
                 q->ungrabKeyboard();
             if (q->isPanel() && panelModality != QGraphicsItem::NonModal)
                 scene->d_func()->leaveModal(q_ptr);
         }
         if (hasFocus && scene) {
             // Hiding the closest non-panel ancestor of the focus item
             QGraphicsItem *focusItem = scene->focusItem();
             if (isWidget && !focusItem->isPanel()) {
                 do {
                     if (focusItem == q_ptr) {
                         static_cast<QGraphicsWidget *>(q_ptr)->focusNextPrevChild(true);
                         break;
                     }
                 } while ((focusItem = focusItem->parentWidget()) && !focusItem->isPanel());
             }
             // Clear focus if previous steps didn't move it to another widget
             if (q_ptr->hasFocus())
                 clearFocusHelper(/* giveFocusToParent = */ false);
         }
         if (q_ptr->isSelected())
             q_ptr->setSelected(false);
     } else {
         geometryChanged = 1;
         paintedViewBoundingRectsNeedRepaint = 1;
         if (scene) {
             if (isWidget) {
                 QGraphicsWidget *widget = static_cast<QGraphicsWidget *>(q_ptr);
                 if (widget->windowType() == Qt::Popup)
                     scene->d_func()->addPopup(widget);
             }
             if (q->isPanel() && panelModality != QGraphicsItem::NonModal) {
                 scene->d_func()->enterModal(q_ptr);
             }
         }
     }
     // Update children with explicitly = false.
     const bool updateChildren = update && !((flags & QGraphicsItem::ItemClipsChildrenToShape)
                                             && !(flags & QGraphicsItem::ItemHasNoContents));
     foreach (QGraphicsItem *child, children) {
         if (!newVisible || !child->d_ptr->explicitlyHidden)
             child->d_ptr->setVisibleHelper(newVisible, false, updateChildren);
     }
     // Update activation
     if (scene && q->isPanel()) {
         if (newVisible) {
             if (parent && parent->isActive())
                 q->setActive(true);
         } else {
             if (q->isActive())
                 scene->setActivePanel(parent);
         }
     }
     // Enable subfocus
     if (scene) {
         if (newVisible) {
             // Item is shown
             QGraphicsItem *p = parent;
             bool done = false;
             while (p) {
                 if (p->flags() & QGraphicsItem::ItemIsFocusScope) {
                     QGraphicsItem *fsi = p->d_ptr->focusScopeItem;
                     if (q_ptr == fsi || q_ptr->isAncestorOf(fsi)) {
                         done = true;
                         while (fsi->d_ptr->focusScopeItem && fsi->d_ptr->focusScopeItem->isVisible())
                             fsi = fsi->d_ptr->focusScopeItem;
                         fsi->d_ptr->setFocusHelper(Qt::OtherFocusReason, /* climb = */ true,
                                                    /* focusFromHide = */ false);
                     }
                     break;
                 }
                 p = p->d_ptr->parent;
             }
             if (!done) {
                 QGraphicsItem *fi = subFocusItem;
                 if (fi && fi != scene->focusItem()) {
                     scene->setFocusItem(fi);
                 } else if (flags & QGraphicsItem::ItemIsFocusScope &&
                            !scene->focusItem() &&
                            q->isAncestorOf(scene->d_func()->lastFocusItem)) {
                     q_ptr->setFocus();
                 }
             }
         } else {
             // Item is hidden
             if (hasFocus) {
                 QGraphicsItem *p = parent;
                 while (p) {
                     if (p->flags() & QGraphicsItem::ItemIsFocusScope) {
                         if (p->d_ptr->visible) {
                             p->d_ptr->setFocusHelper(Qt::OtherFocusReason, /* climb = */ true,
                                                      /* focusFromHide = */ true);
                         }
                         break;
                     }
                     p = p->d_ptr->parent;
                 }
             }
         }
     }
     // Deliver post-change notification.
     q_ptr->itemChange(QGraphicsItem::ItemVisibleHasChanged, newVisibleVariant);
     if (isObject)
         emit static_cast<QGraphicsObject *>(q_ptr)->visibleChanged();
 }
setWidth()
void QGraphicsItemPrivate::setWidth (qreal w) virtual
Warning
This function is not part of the public interface. Set the width of the item Reimplemented by QGraphicsWidget
Reimplemented in QDeclarativeItemPrivate, and QGraphicsWidgetPrivate.
Definition at line 8238 of file qgraphicsitem.cpp.
Referenced by QDeclarativeAnchorsPrivate::setItemWidth().
 {
     Q_UNUSED(w);
 }
siblingOrderChange()
void QGraphicsItemPrivate::siblingOrderChange () virtual
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
Warning
This function is not part of the public interface.
Reimplemented in QDeclarativeItemPrivate.
Definition at line 6016 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::stackBefore().
 {
 }
subFocusItemChange()
void QGraphicsItemPrivate::subFocusItemChange () virtual
Subclasses can reimplement this function to be notified when subFocusItem changes.
Warning
This function is not part of the public interface.
Definition at line 5989 of file qgraphicsitem.cpp.
Referenced by clearSubFocus(), and setSubFocus().
 {
 }
transformChanged()
virtual void QGraphicsItemPrivate::transformChanged () inline virtual
Reimplemented in QDeclarativeItemPrivate.
Definition at line 288 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::setRotation(), QGraphicsItem::setScale(), and QGraphicsItem::setTransformations().
 {}
transformToParent()
QTransform QGraphicsItemPrivate::transformToParent () const inline
Definition at line 814 of file qgraphicsitem_p.h.
Referenced by childrenBoundingRectHelper(), QGraphicsItem::mapFromParent(), QGraphicsItem::mapRectFromParent(), QGraphicsItem::mapRectToParent(), and QGraphicsItem::mapToParent().
 {
     QTransform matrix;
     combineTransformToParent(&matrix);
     return matrix;
 }
unsetExtra()
void QGraphicsItemPrivate::unsetExtra (Extra type) inline
Definition at line 353 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::setBoundingRegionGranularity(), and QGraphicsItem::unsetCursor().
     {
         for (int i = 0; i < extras.size(); ++i) {
             if (extras.at(i).type == type) {
                 extras.removeAt(i);
                 return;
             }
         }
     }
updateAncestorFlag()
void QGraphicsItemPrivate::updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag = NoFlag, bool enabled = false, bool root = true)
Propagates the ancestor flag flag with value enabled to all this item's children.
Warning
This function is not part of the public interface.
If root is false, the flag is also set on this item (default is true).
Definition at line 853 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setFiltersChildEvents(), QGraphicsItem::setFlags(), and QGraphicsItem::setHandlesChildEvents().
 {
     Q_Q(QGraphicsItem);
     if (root) {
         // For root items only. This is the item that has either enabled or
         // disabled \a childFlag, or has been reparented.
         switch (int(childFlag)) {
         case -2:
             flag = AncestorFiltersChildEvents;
             enabled = q->filtersChildEvents();
             break;
         case -1:
             flag = AncestorHandlesChildEvents;
             enabled = q->handlesChildEvents();
             break;
         case QGraphicsItem::ItemClipsChildrenToShape:
             flag = AncestorClipsChildren;
             enabled = flags & QGraphicsItem::ItemClipsChildrenToShape;
             break;
         case QGraphicsItem::ItemIgnoresTransformations:
             flag = AncestorIgnoresTransformations;
             enabled = flags & QGraphicsItem::ItemIgnoresTransformations;
             break;
         default:
             return;
         }
         if (parent) {
             // Inherit the enabled-state from our parents.
             if ((parent->d_ptr->ancestorFlags & flag)
                     || (int(parent->d_ptr->flags & childFlag) == childFlag)
                         || (childFlag == -1 && parent->d_ptr->handlesChildEvents)
                         || (childFlag == -2 && parent->d_ptr->filtersDescendantEvents)) {
                 enabled = true;
                 ancestorFlags |= flag;
             } else {
                 ancestorFlags &= ~flag;
             }
         } else {
             // Top-level root items don't have any ancestors, so there are no
             // ancestor flags either.
             ancestorFlags = 0;
         }
     } else {
         // Don't set or propagate the ancestor flag if it's already correct.
         if (((ancestorFlags & flag) && enabled) || (!(ancestorFlags & flag) && !enabled))
             return;
         // Set the flag.
         if (enabled)
             ancestorFlags |= flag;
         else
             ancestorFlags &= ~flag;
         // Don't process children if the item has the main flag set on itself.
         if ((childFlag != -1 &&  int(flags & childFlag) == childFlag)
             || (int(childFlag) == -1 && handlesChildEvents)
             || (int(childFlag) == -2 && filtersDescendantEvents))
             return;
     }
     for (int i = 0; i < children.size(); ++i)
         children.at(i)->d_ptr->updateAncestorFlag(childFlag, flag, enabled, false);
 }
updateAncestorFlags()
void QGraphicsItemPrivate::updateAncestorFlags ()
Definition at line 919 of file qgraphicsitem.cpp.
 {
     int flags = 0;
     if (parent) {
         // Inherit the parent's ancestor flags.
         QGraphicsItemPrivate *pd = parent->d_ptr.data();
         flags = pd->ancestorFlags;
         // Add in flags from the parent.
         if (pd->filtersDescendantEvents)
             flags |= AncestorFiltersChildEvents;
         if (pd->handlesChildEvents)
             flags |= AncestorHandlesChildEvents;
         if (pd->flags & QGraphicsItem::ItemClipsChildrenToShape)
             flags |= AncestorClipsChildren;
         if (pd->flags & QGraphicsItem::ItemIgnoresTransformations)
             flags |= AncestorIgnoresTransformations;
     }
     if (ancestorFlags == flags)
         return; // No change; stop propagation.
     ancestorFlags = flags;
     // Propagate to children recursively.
     for (int i = 0; i < children.size(); ++i)
         children.at(i)->d_ptr->updateAncestorFlags();
 }
updateChildWithGraphicsEffectFlagRecursively()
void QGraphicsItemPrivate::updateChildWithGraphicsEffectFlagRecursively ()
Definition at line 2934 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setGraphicsEffect(), and setParentItemHelper().
 {
 #ifndef QT_NO_GRAPHICSEFFECT
     QGraphicsItemPrivate *itemPrivate = this;
     do {
         // parent chain already notified?
         if (itemPrivate->mayHaveChildWithGraphicsEffect)
             return;
         itemPrivate->mayHaveChildWithGraphicsEffect = 1;
     } while ((itemPrivate = itemPrivate->parent ? itemPrivate->parent->d_ptr.data() : 0));
 #endif
 }
updatePaintedViewBoundingRects()
void QGraphicsItemPrivate::updatePaintedViewBoundingRects (bool updateChildren)
Definition at line 5868 of file qgraphicsitem.cpp.
Referenced by QGraphicsItem::setFlags(), and updatePaintedViewBoundingRects().
 {
     if (!scene)
         return;
     for (int i = 0; i < scene->d_func()->views.size(); ++i) {
         QGraphicsViewPrivate *viewPrivate = scene->d_func()->views.at(i)->d_func();
         QRect rect = paintedViewBoundingRects.value(viewPrivate->viewport);
         rect.translate(viewPrivate->dirtyScrollOffset);
         viewPrivate->updateRect(rect);
     }
     if (updateChildren) {
         for (int i = 0; i < children.size(); ++i)
             children.at(i)->d_ptr->updatePaintedViewBoundingRects(true);
     }
 }
updateSceneTransformFromParent()
void QGraphicsItemPrivate::updateSceneTransformFromParent () virtual
Reimplemented in QDeclarativeFlipablePrivate.
Definition at line 1085 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), and QDeclarativeFlipablePrivate::updateSceneTransformFromParent().
 {
     if (parent) {
         Q_ASSERT(!parent->d_ptr->dirtySceneTransform);
         if (parent->d_ptr->sceneTransformTranslateOnly) {
             sceneTransform = QTransform::fromTranslate(parent->d_ptr->sceneTransform.dx() + pos.x(),
                                                        parent->d_ptr->sceneTransform.dy() + pos.y());
         } else {
             sceneTransform = parent->d_ptr->sceneTransform;
             sceneTransform.translate(pos.x(), pos.y());
         }
         if (transformData) {
             sceneTransform = transformData->computedFullTransform(&sceneTransform);
             sceneTransformTranslateOnly = (sceneTransform.type() <= QTransform::TxTranslate);
         } else {
             sceneTransformTranslateOnly = parent->d_ptr->sceneTransformTranslateOnly;
         }
     } else if (!transformData) {
         sceneTransform = QTransform::fromTranslate(pos.x(), pos.y());
         sceneTransformTranslateOnly = 1;
     } else if (transformData->onlyTransform) {
         sceneTransform = transformData->transform;
         if (!pos.isNull())
             sceneTransform *= QTransform::fromTranslate(pos.x(), pos.y());
         sceneTransformTranslateOnly = (sceneTransform.type() <= QTransform::TxTranslate);
     } else if (pos.isNull()) {
         sceneTransform = transformData->computedFullTransform();
         sceneTransformTranslateOnly = (sceneTransform.type() <= QTransform::TxTranslate);
     } else {
         sceneTransform = QTransform::fromTranslate(pos.x(), pos.y());
         sceneTransform = transformData->computedFullTransform(&sceneTransform);
         sceneTransformTranslateOnly = (sceneTransform.type() <= QTransform::TxTranslate);
     }
     dirtySceneTransform = 0;
 }
width()
qreal QGraphicsItemPrivate::width () const virtual
Warning
This function is not part of the public interface. Returns the width of the item Reimplemented by QGraphicsWidget
Reimplemented in QDeclarativeItemPrivate, and QGraphicsWidgetPrivate.
Definition at line 8228 of file qgraphicsitem.cpp.
Referenced by adjustedPosition(), QDeclarativeColumn::doPositioning(), QDeclarativeRow::doPositioning(), QDeclarativeGrid::doPositioning(), QDeclarativeFlow::doPositioning(), QDeclarativeAnchorsPrivate::fillChanged(), hcenter(), position(), QDeclarativeBasePositioner::prePositioning(), QDeclarativeFlipablePrivate::setBackTransform(), and QDeclarativeAnchorsPrivate::updateHorizontalAnchors().
 {
     return 0;
 }
Properties
acceptDrops
quint32 QGraphicsItemPrivate::acceptDrops
Definition at line 543 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::acceptDrops(), and QGraphicsItem::setAcceptDrops().
acceptedMouseButtons
quint32 QGraphicsItemPrivate::acceptedMouseButtons
Definition at line 536 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::acceptedMouseButtons(), QDeclarativeItemPrivate::QDeclarativeItemPrivate(), QDeclarativeTextPrivate::QDeclarativeTextPrivate(), and QGraphicsItem::setAcceptedMouseButtons().
acceptedTouchBeginEvent
quint32 QGraphicsItemPrivate::acceptedTouchBeginEvent
Definition at line 571 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::sendTouchBeginEvent().
acceptsHover
quint32 QGraphicsItemPrivate::acceptsHover
Definition at line 542 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::acceptHoverEvents(), QGraphicsItem::acceptsHoverEvents(), QGraphicsScenePrivate::itemAcceptsHoverEvents_helper(), and QGraphicsItem::setAcceptHoverEvents().
acceptTouchEvents
quint32 QGraphicsItemPrivate::acceptTouchEvents
Definition at line 570 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::acceptTouchEvents(), QGraphicsScene::addItem(), and QGraphicsItem::setAcceptTouchEvents().
allChildrenDirty
quint32 QGraphicsItemPrivate::allChildrenDirty
Definition at line 557 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
ancestorFlags
quint32 QGraphicsItemPrivate::ancestorFlags
Definition at line 548 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::addToIndex(), QGraphicsItem::clipPath(), QGraphicsItem::collidesWithItem(), QGraphicsItem::deviceTransform(), effectiveBoundingRect(), QGraphicsScenePrivate::filterDescendantEvent(), QGraphicsSceneBspTreeIndex::itemChange(), QGraphicsItem::mouseMoveEvent(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), QGraphicsItem::removeFromIndex(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsItem::sceneEvent(), and updateAncestorFlags().
cacheMode
quint32 QGraphicsItemPrivate::cacheMode
Definition at line 549 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::cacheMode(), QGraphicsScenePrivate::draw(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsItem::setCacheMode(), and QGraphicsItem::update().
children
QList<QGraphicsItem *> QGraphicsItemPrivate::children
Definition at line 517 of file qgraphicsitem_p.h.
Referenced by QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsScene::addItem(), QGraphicsItem::childItems(), children_at(), children_at_helper(), children_clear(), children_clear_helper(), children_count(), children_count_helper(), childrenBoundingRectHelper(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QGraphicsScenePrivate::draw(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsScenePrivate::resetDirtyItem(), QGraphicsItem::sceneEvent(), QGraphicsWidgetPrivate::setLayoutDirection_helper(), QGraphicsItem::stackBefore(), QGraphicsProxyWidgetPrivate::unembedSubWindow(), QGraphicsWidgetPrivate::updateFont(), QGraphicsWidgetPrivate::updatePalette(), and QGraphicsItem::~QGraphicsItem().
childrenBoundingRect
QRectF QGraphicsItemPrivate::childrenBoundingRect
Definition at line 509 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::childrenBoundingRect().
dirty
quint32 QGraphicsItemPrivate::dirty
Definition at line 552 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), markParentDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
dirtyChildren
quint32 QGraphicsItemPrivate::dirtyChildren
Definition at line 553 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), markParentDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
dirtyChildrenBoundingRect
quint32 QGraphicsItemPrivate::dirtyChildrenBoundingRect
Definition at line 559 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::childrenBoundingRect(), markParentDirty(), and QGraphicsItem::setFlags().
dirtySceneTransform
quint32 QGraphicsItemPrivate::dirtySceneTransform
Definition at line 564 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::draw(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsTransformPrivate::setItem(), QGraphicsItem::setRotation(), QGraphicsItem::setScale(), QGraphicsItem::setTransformations(), QGraphicsItem::setTransformOriginPoint(), and QGraphicsTransformPrivate::updateItem().
enabled
quint32 QGraphicsItemPrivate::enabled
Definition at line 539 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::isEnabled(), and QGraphicsItem::setSelected().
explicitActivate
quint32 QGraphicsItemPrivate::explicitActivate
Definition at line 579 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), and QGraphicsItem::setActive().
explicitlyDisabled
quint32 QGraphicsItemPrivate::explicitlyDisabled
Definition at line 540 of file qgraphicsitem_p.h.
Referenced by setEnabledHelper().
explicitlyHidden
quint32 QGraphicsItemPrivate::explicitlyHidden
Definition at line 538 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::_q_polishItems(), QGraphicsItem::isVisibleTo(), QDeclarativeBasePositioner::prePositioning(), and setVisibleHelper().
extras
QList<ExtraStruct> QGraphicsItemPrivate::extras
Definition at line 375 of file qgraphicsitem_p.h.
filtersDescendantEvents
quint32 QGraphicsItemPrivate::filtersDescendantEvents
Definition at line 572 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::filterDescendantEvent(), QGraphicsItem::filtersChildEvents(), QGraphicsItem::setFiltersChildEvents(), and updateAncestorFlags().
flags
quint32 QGraphicsItemPrivate::flags
Definition at line 562 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), calcEffectiveOpacity(), QGraphicsItem::clipPath(), QGraphicsScenePrivate::draw(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsItem::flags(), QGraphicsWidgetPrivate::init(), invalidateChildGraphicsEffectsRecursively(), QGraphicsItem::isPanel(), QGraphicsSceneBspTreeIndex::itemChange(), QGraphicsScenePrivate::markDirty(), QGraphicsScenePrivate::mousePressEventHandler(), QGraphicsItem::panel(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QDeclarativeImageBasePrivate::QDeclarativeImageBasePrivate(), QDeclarativeItemPrivate::QDeclarativeItemPrivate(), QDeclarativeRectanglePrivate::QDeclarativeRectanglePrivate(), QDeclarativeTextPrivate::QDeclarativeTextPrivate(), qt_closestItemFirst(), qt_closestLeaf(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsItem::setFlag(), QGraphicsItem::setFlags(), QGraphicsItem::setMatrix(), QGraphicsItem::setOpacity(), setParentItemHelper(), QGraphicsItem::setPos(), QGraphicsItem::setRotation(), QGraphicsItem::setScale(), QGraphicsItem::setSelected(), QGraphicsItem::setTransform(), QGraphicsItem::setTransformOriginPoint(), QGraphicsItem::setZValue(), and updateAncestorFlags().
focusProxy
QGraphicsItem* QGraphicsItemPrivate::focusProxy
Definition at line 525 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::focusProxy(), QGraphicsItem::hasFocus(), setFocusHelper(), and QGraphicsItem::setFocusProxy().
focusProxyRefs
QList<QGraphicsItem **> QGraphicsItemPrivate::focusProxyRefs
Definition at line 526 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::setFocusProxy().
focusScopeItem
QGraphicsItem* QGraphicsItemPrivate::focusScopeItem
Definition at line 528 of file qgraphicsitem_p.h.
Referenced by clearFocusHelper(), QDeclarativeItemPrivate::focusChanged(), QGraphicsItem::focusScopeItem(), setFocusHelper(), setParentItemHelper(), setVisibleHelper(), and QGraphicsItem::~QGraphicsItem().
fullUpdatePending
quint32 QGraphicsItemPrivate::fullUpdatePending
Definition at line 558 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), markParentDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsScenePrivate::resetDirtyItem(), and QGraphicsItem::update().
geometryChanged
quint32 QGraphicsItemPrivate::geometryChanged
Definition at line 565 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
gestureContext
QMap<Qt::GestureType, Qt::GestureFlags> QGraphicsItemPrivate::gestureContext
Definition at line 532 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), QGraphicsScenePrivate::cancelGesturesForChildren(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsObject::grabGesture(), QGraphicsScenePrivate::removeItemHelper(), and QGraphicsItem::~QGraphicsItem().
globalStackingOrder
int QGraphicsItemPrivate::globalStackingOrder
Definition at line 592 of file qgraphicsitem_p.h.
Referenced by QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), QGraphicsSceneBspTreeIndexPrivate::closestItemFirst_withCache(), and QGraphicsSceneBspTreeIndexPrivate::closestItemLast_withCache().
graphicsEffect
QGraphicsEffect* QGraphicsItemPrivate::graphicsEffect
Definition at line 520 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), effectiveBoundingRect(), QGraphicsItem::graphicsEffect(), invalidateChildGraphicsEffectsRecursively(), invalidateParentGraphicsEffectsRecursively(), QGraphicsScenePrivate::markDirty(), markParentDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsScenePrivate::resetDirtyItem(), QGraphicsItem::setGraphicsEffect(), and QGraphicsItem::~QGraphicsItem().
handlesChildEvents
quint32 QGraphicsItemPrivate::handlesChildEvents
Definition at line 545 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::handlesChildEvents(), QGraphicsItem::setHandlesChildEvents(), and updateAncestorFlags().
hasBoundingRegionGranularity
quint32 QGraphicsItemPrivate::hasBoundingRegionGranularity
Definition at line 550 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::boundingRegionGranularity(), QGraphicsItem::setBoundingRegionGranularity(), and updateHelper().
hasCursor
quint32 QGraphicsItemPrivate::hasCursor
Definition at line 547 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), QGraphicsItem::hasCursor(), QGraphicsItem::setCursor(), and QGraphicsItem::unsetCursor().
holesInSiblingIndex
quint32 QGraphicsItemPrivate::holesInSiblingIndex
Definition at line 581 of file qgraphicsitem_p.h.
ignoreOpacity
quint32 QGraphicsItemPrivate::ignoreOpacity
Definition at line 569 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
ignoreVisible
quint32 QGraphicsItemPrivate::ignoreVisible
Definition at line 568 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
imHints
Qt::InputMethodHints QGraphicsItemPrivate::imHints
Definition at line 529 of file qgraphicsitem_p.h.
inDestructor
quint32 QGraphicsItemPrivate::inDestructor
Definition at line 566 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::prepareGeometryChange(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsItem::setPos(), QGraphicsItem::setX(), QGraphicsItem::setY(), and QGraphicsItem::~QGraphicsItem().
index
int QGraphicsItemPrivate::index
Definition at line 522 of file qgraphicsitem_p.h.
Referenced by QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QDeclarativePathViewPrivate::scheduleLayout(), and setParentItemHelper().
inSetPosHelper
quint32 QGraphicsItemPrivate::inSetPosHelper
Definition at line 555 of file qgraphicsitem_p.h.
Referenced by markParentDirty(), and QGraphicsItem::prepareGeometryChange().
isDeclarativeItem
quint32 QGraphicsItemPrivate::isDeclarativeItem
Definition at line 587 of file qgraphicsitem_p.h.
Referenced by QDeclarativeAnchorsPrivate::addDepend(), QGraphicsScene::addItem(), adjustedPosition(), QDeclarativeAnchors::mirrored(), position(), QDeclarativeAnchorsPrivate::remDepend(), QDeclarativeColumn::reportConflictingAnchors(), QDeclarativeRow::reportConflictingAnchors(), QDeclarativeGrid::reportConflictingAnchors(), QDeclarativeFlow::reportConflictingAnchors(), QDeclarativeAnchorsPrivate::setItemSize(), QDeclarativeBasePositionerPrivate::unwatchChanges(), QDeclarativeAnchorsPrivate::updateVerticalAnchors(), and QDeclarativeBasePositionerPrivate::watchChanges().
isMemberOfGroup
quint32 QGraphicsItemPrivate::isMemberOfGroup
Definition at line 544 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::group().
isObject
quint32 QGraphicsItemPrivate::isObject
Definition at line 567 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::parentObject(), QGraphicsObject::QGraphicsObject(), QGraphicsItem::setOpacity(), QGraphicsItem::setRotation(), QGraphicsItem::setScale(), QGraphicsItem::setZValue(), QGraphicsItem::toGraphicsObject(), QGraphicsScenePrivate::ungrabGesture(), and QGraphicsItem::~QGraphicsItem().
isWidget
quint32 QGraphicsItemPrivate::isWidget
Definition at line 551 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::_q_polishItems(), QDeclarativeAnchorsPrivate::addDepend(), QGraphicsScenePrivate::draw(), QGraphicsWidgetPrivate::init(), QGraphicsItem::isWidget(), QGraphicsItem::isWindow(), QGraphicsScenePrivate::itemAcceptsHoverEvents_helper(), QGraphicsItem::mousePressEvent(), QDeclarativeAnchorsPrivate::remDepend(), QGraphicsItem::sceneEvent(), and QGraphicsItem::setPos().
itemDepth
int QGraphicsItemPrivate::itemDepth
Definition at line 524 of file qgraphicsitem_p.h.
itemDiscovered
quint32 QGraphicsItemPrivate::itemDiscovered
Definition at line 546 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::drawItems(), QGraphicsSceneBspTree::items(), and QGraphicsSceneBspTreeIndexPrivate::removeItem().
localCollisionHack
quint32 QGraphicsItemPrivate::localCollisionHack
Definition at line 554 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::collidesWithItem(), and QGraphicsItem::collidesWithPath().
mayHaveChildWithGraphicsEffect
quint32 QGraphicsItemPrivate::mayHaveChildWithGraphicsEffect
Definition at line 586 of file qgraphicsitem_p.h.
Referenced by updateChildWithGraphicsEffectFlagRecursively().
mouseSetsFocus
quint32 QGraphicsItemPrivate::mouseSetsFocus
Definition at line 578 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::mousePressEventHandler(), QGraphicsScenePrivate::sendTouchBeginEvent(), and QGraphicsScene::wheelEvent().
needSortChildren
quint32 QGraphicsItemPrivate::needSortChildren
Definition at line 556 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::setFlags(), and QGraphicsItem::setZValue().
needsRepaint
QRectF QGraphicsItemPrivate::needsRepaint
Definition at line 510 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::markDirty(), QGraphicsScenePrivate::processDirtyItemsRecursive(), and QGraphicsScenePrivate::resetDirtyItem().
notifyBoundingRectChanged
quint32 QGraphicsItemPrivate::notifyBoundingRectChanged
Definition at line 574 of file qgraphicsitem_p.h.
Referenced by markParentDirty(), QGraphicsItem::prepareGeometryChange(), and QGraphicsScenePrivate::resetDirtyItem().
notifyInvalidated
quint32 QGraphicsItemPrivate::notifyInvalidated
Definition at line 575 of file qgraphicsitem_p.h.
Referenced by invalidateChildGraphicsEffectsRecursively(), invalidateParentGraphicsEffectsRecursively(), markParentDirty(), and QGraphicsScenePrivate::resetDirtyItem().
opacity
qreal QGraphicsItemPrivate::opacity
Definition at line 514 of file qgraphicsitem_p.h.
Referenced by calcEffectiveOpacity(), QGraphicsItem::opacity(), and QGraphicsItem::setOpacity().
padding
quint32 QGraphicsItemPrivate::padding
Definition at line 589 of file qgraphicsitem_p.h.
paintedViewBoundingRects
QMap<QWidget *, QRect> QGraphicsItemPrivate::paintedViewBoundingRects
Definition at line 511 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsScenePrivate::markDirty(), QGraphicsView::paintEvent(), and QGraphicsScenePrivate::processDirtyItemsRecursive().
paintedViewBoundingRectsNeedRepaint
quint32 QGraphicsItemPrivate::paintedViewBoundingRectsNeedRepaint
Definition at line 563 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsScenePrivate::resetDirtyItem(), and QGraphicsItem::setOpacity().
panelModality
QGraphicsItem::PanelModality QGraphicsItemPrivate::panelModality
Definition at line 530 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::enterModal(), QGraphicsItem::panelModality(), QGraphicsItem::setFlags(), and QGraphicsItem::setPanelModality().
parent
QGraphicsItem* QGraphicsItemPrivate::parent
Definition at line 516 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::_q_updateScenePosDescendants(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), QGraphicsScene::addItem(), calcEffectiveOpacity(), clearFocusHelper(), clearSubFocus(), QGraphicsItem::clipPath(), QGraphicsItem::commonAncestorItem(), effectiveBoundingRect(), QGraphicsSceneBspTreeIndexPrivate::estimateItems(), QGraphicsItem::group(), invalidateParentGraphicsEffectsRecursively(), QGraphicsItem::isAncestorOf(), QGraphicsItem::isVisibleTo(), QGraphicsItem::itemTransform(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsScenePrivate::markDirty(), markParentDirty(), movableAncestorIsSelected(), QGraphicsWidgetPrivate::naturalWidgetFont(), QGraphicsWidgetPrivate::naturalWidgetPalette(), QGraphicsItem::panel(), QGraphicsItem::parentItem(), QGraphicsItem::parentObject(), qt_closestItemFirst(), QGraphicsItemGroup::removeFromGroup(), QGraphicsItem::sceneBoundingRect(), sceneEffectiveBoundingRect(), QGraphicsItem::sceneEvent(), QGraphicsItem::setFlags(), setFocusHelper(), QGraphicsItem::setGraphicsEffect(), QGraphicsItem::setParentItem(), setParentItemHelper(), QGraphicsScenePrivate::setScenePosItemEnabled(), setSubFocus(), setVisibleHelper(), QGraphicsItem::setZValue(), QGraphicsItem::stackBefore(), updateChildWithGraphicsEffectFlagRecursively(), QGraphicsSceneFindItemBspTreeVisitor::visit(), and QGraphicsItem::~QGraphicsItem().
pendingPolish
quint32 QGraphicsItemPrivate::pendingPolish
Definition at line 585 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::_q_polishItems(), QGraphicsScene::addItem(), and QGraphicsScenePrivate::removeItemHelper().
pos
QPointF QGraphicsItemPrivate::pos
Definition at line 512 of file qgraphicsitem_p.h.
Referenced by childrenBoundingRectHelper(), QGraphicsItem::itemTransform(), QGraphicsItem::mapFromParent(), QGraphicsItem::mapRectFromParent(), QGraphicsItem::mapRectToParent(), QGraphicsItem::mapToParent(), QGraphicsProxyWidgetPrivate::mapToReceiver(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsItem::mouseMoveEvent(), QGraphicsItem::pos(), QGraphicsItem::sceneBoundingRect(), sceneEffectiveBoundingRect(), QDeclarativePathViewPrivate::scheduleLayout(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), QGraphicsWidgetPrivate::setGeometryFromSetPos(), QGraphicsItem::setPos(), QGraphicsItem::setX(), QGraphicsItem::setY(), QGraphicsWidgetPrivate::windowFrameHoverMoveEvent(), and QGraphicsWidgetPrivate::windowFrameMouseReleaseEvent().
q_ptr
QGraphicsItem* QGraphicsItemPrivate::q_ptr
Definition at line 593 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::QGraphicsItem(), and updateHelper().
scene
QGraphicsScene* QGraphicsItemPrivate::scene
Definition at line 515 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), QGraphicsItem::addToIndex(), QGraphicsItem::collidingItems(), QGraphicsItem::ensureVisible(), QGraphicsObject::grabGesture(), QGraphicsItem::grabKeyboard(), QGraphicsItem::grabMouse(), QGraphicsItem::hasFocus(), QGraphicsItem::installSceneEventFilter(), QGraphicsItem::isActive(), QGraphicsItem::isBlockedByModalPanel(), markParentDirty(), QGraphicsItem::mouseMoveEvent(), QGraphicsItem::mousePressEvent(), QGraphicsItem::mouseReleaseEvent(), QGraphicsWidgetPrivate::naturalWidgetFont(), QGraphicsWidgetPrivate::naturalWidgetPalette(), QGraphicsItem::prepareGeometryChange(), QGraphicsItem::removeFromIndex(), QGraphicsItem::removeSceneEventFilter(), QGraphicsWidgetPrivate::resolveLayoutDirection(), QGraphicsItem::scene(), QGraphicsItem::sceneEvent(), QGraphicsItem::setAcceptedMouseButtons(), QGraphicsItem::setAcceptHoverEvents(), QGraphicsItem::setAcceptTouchEvents(), QGraphicsItem::setActive(), QGraphicsItem::setCursor(), QGraphicsItem::setFlags(), QGraphicsItem::setFocusProxy(), QGraphicsWidget::setGeometry(), QGraphicsItem::setOpacity(), QGraphicsItem::setPanelModality(), QGraphicsItem::setSelected(), QGraphicsItem::setZValue(), QGraphicsItem::stackBefore(), QGraphicsProxyWidgetPrivate::unembedSubWindow(), QGraphicsObject::ungrabGesture(), QGraphicsItem::ungrabKeyboard(), QGraphicsItem::ungrabMouse(), QGraphicsItem::unsetCursor(), QGraphicsItem::update(), and QGraphicsItem::~QGraphicsItem().
scenePosDescendants
quint32 QGraphicsItemPrivate::scenePosDescendants
Definition at line 584 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::_q_updateScenePosDescendants(), QGraphicsItem::setPos(), QGraphicsScenePrivate::setScenePosItemEnabled(), and QGraphicsItem::setTransform().
sceneTransform
QTransform QGraphicsItemPrivate::sceneTransform
Definition at line 521 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::deviceTransform(), QGraphicsView::fitInView(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsItem::itemTransform(), QGraphicsItem::mapFromScene(), QGraphicsItem::mapRectFromScene(), QGraphicsItem::mapRectToScene(), QGraphicsItem::mapToScene(), QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsItem::sceneBoundingRect(), QGraphicsItem::sceneMatrix(), QGraphicsItem::sceneTransform(), QGraphicsViewPrivate::setUpdateClip(), and updateHelper().
sceneTransformTranslateOnly
quint32 QGraphicsItemPrivate::sceneTransformTranslateOnly
Definition at line 573 of file qgraphicsitem_p.h.
Referenced by QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsViewPrivate::setUpdateClip(), and updateHelper().
selected
quint32 QGraphicsItemPrivate::selected
Definition at line 541 of file qgraphicsitem_p.h.
Referenced by QGraphicsItem::isSelected(), QGraphicsItem::mousePressEvent(), QGraphicsItem::mouseReleaseEvent(), and QGraphicsItem::setSelected().
sendParentChangeNotification
quint32 QGraphicsItemPrivate::sendParentChangeNotification
Definition at line 588 of file qgraphicsitem_p.h.
Referenced by children_append(), and children_clear().
sequentialOrdering
quint32 QGraphicsItemPrivate::sequentialOrdering
Definition at line 582 of file qgraphicsitem_p.h.
siblingIndex
int QGraphicsItemPrivate::siblingIndex
Definition at line 523 of file qgraphicsitem_p.h.
Referenced by addChild(), ensureSequentialSiblingIndex(), insertionOrder(), qt_closestLeaf(), QGraphicsScenePrivate::registerTopLevelItem(), removeChild(), QGraphicsItem::stackBefore(), and QGraphicsScenePrivate::unregisterTopLevelItem().
subFocusItem
QGraphicsItem* QGraphicsItemPrivate::subFocusItem
Definition at line 527 of file qgraphicsitem_p.h.
Referenced by clearSubFocus(), QGraphicsItem::focusItem(), and setSubFocus().
transformData
TransformData* QGraphicsItemPrivate::transformData
Definition at line 518 of file qgraphicsitem_p.h.
Referenced by childrenBoundingRectHelper(), QGraphicsItem::deviceTransform(), QGraphicsItem::itemTransform(), QGraphicsItem::mapFromParent(), QGraphicsItem::mapRectFromParent(), QGraphicsItem::mapRectToParent(), QGraphicsItem::mapToParent(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsItem::mouseMoveEvent(), QGraphicsItem::rotation(), QGraphicsItem::scale(), QGraphicsItem::sceneBoundingRect(), sceneEffectiveBoundingRect(), QGraphicsTransformPrivate::setItem(), QGraphicsItem::setMatrix(), setParentItemHelper(), QGraphicsItem::setRotation(), QGraphicsItem::setScale(), QGraphicsItem::setTransform(), QGraphicsItem::setTransformations(), QGraphicsItem::setTransformOriginPoint(), QGraphicsItem::transform(), QDeclarativeItemPrivate::transform_at(), QDeclarativeItemPrivate::transform_clear(), QDeclarativeItemPrivate::transform_count(), QGraphicsItem::transformations(), QGraphicsItem::transformOriginPoint(), and QGraphicsItem::~QGraphicsItem().
updateDueToGraphicsEffect
quint32 QGraphicsItemPrivate::updateDueToGraphicsEffect
Definition at line 583 of file qgraphicsitem_p.h.
Referenced by invalidateParentGraphicsEffectsRecursively(), and QGraphicsItem::update().
visible
quint32 QGraphicsItemPrivate::visible
Definition at line 537 of file qgraphicsitem_p.h.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsItem::grabKeyboard(), QGraphicsItem::grabMouse(), QGraphicsItem::isVisible(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsItem::sceneEvent(), QGraphicsItem::setSelected(), setSubFocus(), setVisibleHelper(), and QGraphicsSceneFindItemBspTreeVisitor::visit().
wantsActive
quint32 QGraphicsItemPrivate::wantsActive
Definition at line 580 of file qgraphicsitem_p.h.
Referenced by QGraphicsScene::addItem(), and QGraphicsItem::setActive().
z
qreal QGraphicsItemPrivate::z
Definition at line 513 of file qgraphicsitem_p.h.
Referenced by qt_closestLeaf(), QGraphicsItem::setFlags(), QGraphicsItem::setZValue(), and QGraphicsItem::zValue().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsitem_p.h
/src/gui/graphicsview/qgraphicsitem.cpp