Qt 4.8: QFutureInterfaceBase Class Reference
QFutureInterfaceBase Class Reference
#include <qfutureinterface.h>
Public Types
enum State {
NoState = 0x00, Running = 0x01, Started = 0x02, Finished = 0x04,
Canceled = 0x08, Paused = 0x10, Throttled = 0x20
}
Public Functions
void cancel ()
QtConcurrent::internal::ExceptionStore & exceptionStore ()
int expectedResultCount ()
bool isCanceled () const
bool isFinished () const
bool isPaused () const
bool isProgressUpdateNeeded () const
bool isResultReadyAt (int index) const
bool isRunning () const
bool isStarted () const
bool isThrottled () const
QMutex * mutex () const
bool operator!= (const QFutureInterfaceBase &other) const
QFutureInterfaceBase & operator= (const QFutureInterfaceBase &other)
bool operator== (const QFutureInterfaceBase &other) const
int progressMaximum () const
int progressMinimum () const
QString progressText () const
int progressValue () const
QFutureInterfaceBase (State initialState=NoState)
QFutureInterfaceBase (const QFutureInterfaceBase &other)
bool queryState (State state) const
void reportCanceled ()
void reportException (const QtConcurrent::Exception &e)
void reportFinished ()
void reportResultsReady (int beginIndex, int endIndex)
void reportStarted ()
int resultCount () const
QtConcurrent::ResultStoreBase & resultStoreBase ()
const QtConcurrent::ResultStoreBase & resultStoreBase () const
void setExpectedResultCount (int resultCount)
void setFilterMode (bool enable)
void setPaused (bool paused)
void setProgressRange (int minimum, int maximum)
void setProgressValue (int progressValue)
void setProgressValueAndText (int progressValue, const QString &progressText)
void setRunnable (QRunnable *runnable)
void setThrottled (bool enable)
void togglePaused ()
void waitForFinished ()
bool waitForNextResult ()
void waitForResult (int resultIndex)
void waitForResume ()
virtual ~QFutureInterfaceBase ()
Protected Functions
bool referenceCountIsOne () const
Properties
QFutureInterfaceBasePrivate * d
Friends
class QFutureWatcherBase
class QFutureWatcherBasePrivate
Detailed Description
Definition at line 64 of file qfutureinterface.h.
Enumerations
State
enum QFutureInterfaceBase::State
Enumerator
NoState
Running
Started
Finished
Canceled
Paused
Throttled
Definition at line 67 of file qfutureinterface.h.
                {
         NoState   = 0x00,
         Running   = 0x01,
         Started   = 0x02,
         Finished  = 0x04,
         Canceled  = 0x08,
         Paused    = 0x10,
         Throttled = 0x20
     };
Constructors and Destructors
QFutureInterfaceBase() [1/2]
QFutureInterfaceBase::QFutureInterfaceBase (State initialState = NoState)
Definition at line 60 of file qfutureinterface.cpp.
     : d(new QFutureInterfaceBasePrivate(initialState))
 { }
QFutureInterfaceBase() [2/2]
QFutureInterfaceBase::QFutureInterfaceBase (const QFutureInterfaceBase & other)
Definition at line 64 of file qfutureinterface.cpp.
     : d(other.d)
 {
     d->refCount.ref();
 }
~QFutureInterfaceBase()
QFutureInterfaceBase::~QFutureInterfaceBase () virtual
Definition at line 70 of file qfutureinterface.cpp.
 {
     if (!d->refCount.deref())
         delete d;
 }
Functions
cancel()
void QFutureInterfaceBase::cancel ()
Definition at line 76 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::cancel(), and reportCanceled().
 {
     QMutexLocker locker(&d->m_mutex);
     if (d->state & Canceled)
         return;
     d->state = State((d->state & ~Paused) | Canceled);
     d->waitCondition.wakeAll();
     d->pausedWaitCondition.wakeAll();
     d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Canceled));
 }
exceptionStore()
QtConcurrent::internal::ExceptionStore & QFutureInterfaceBase::exceptionStore ()
Definition at line 393 of file qfutureinterface.cpp.
 {
     return d->m_exceptionStore;
 }
expectedResultCount()
int QFutureInterfaceBase::expectedResultCount ()
Definition at line 272 of file qfutureinterface.cpp.
 {
     return d->m_expectedResultCount;
 }
isCanceled()
bool QFutureInterfaceBase::isCanceled () const
Definition at line 142 of file qfutureinterface.cpp.
 {
     return queryState(Canceled);
 }
isFinished()
bool QFutureInterfaceBase::isFinished () const
Definition at line 147 of file qfutureinterface.cpp.
 {
     return queryState(Finished);
 }
isPaused()
bool QFutureInterfaceBase::isPaused () const
Definition at line 152 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::event().
 {
     return queryState(Paused);
 }
isProgressUpdateNeeded()
bool QFutureInterfaceBase::isProgressUpdateNeeded () const
Definition at line 219 of file qfutureinterface.cpp.
 {
     QMutexLocker locker(&d->m_mutex);
     return !d->progressTime.isValid() || (d->progressTime.elapsed() > (1000 / MaxProgressEmitsPerSecond));
 }
isResultReadyAt()
bool QFutureInterfaceBase::isResultReadyAt (int index) const
Definition at line 162 of file qfutureinterface.cpp.
 {
     QMutexLocker lock(&d->m_mutex);
     return d->internal_isResultReadyAt(index);
 }
isRunning()
bool QFutureInterfaceBase::isRunning () const
Definition at line 132 of file qfutureinterface.cpp.
 {
     return queryState(Running);
 }
isStarted()
bool QFutureInterfaceBase::isStarted () const
Definition at line 137 of file qfutureinterface.cpp.
 {
     return queryState(Started);
 }
isThrottled()
bool QFutureInterfaceBase::isThrottled () const
Definition at line 157 of file qfutureinterface.cpp.
 {
     return queryState(Throttled);
 }
mutex()
QMutex * QFutureInterfaceBase::mutex () const
Definition at line 388 of file qfutureinterface.cpp.
 {
     return &d->m_mutex;
 }
operator!=()
bool QFutureInterfaceBase::operator!= (const QFutureInterfaceBase & other) const inline
Definition at line 130 of file qfutureinterface.h.
 { return d != other.d; }
operator=()
QFutureInterfaceBase & QFutureInterfaceBase::operator= (const QFutureInterfaceBase & other)
Definition at line 408 of file qfutureinterface.cpp.
Referenced by QFutureInterface< T >::operator=(), and QFutureInterface< T >::results().
 {
     other.d->refCount.ref();
     if (!d->refCount.deref())
         delete d;
     d = other.d;
     return *this;
 }
operator==()
bool QFutureInterfaceBase::operator== (const QFutureInterfaceBase & other) const inline
Definition at line 129 of file qfutureinterface.h.
 { return d == other.d; }
progressMaximum()
int QFutureInterfaceBase::progressMaximum () const
Definition at line 202 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::progressMaximum().
 {
     return d->m_progressMaximum;
 }
progressMinimum()
int QFutureInterfaceBase::progressMinimum () const
Definition at line 197 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::progressMinimum().
 {
     return d->m_progressMinimum;
 }
progressText()
QString QFutureInterfaceBase::progressText () const
Definition at line 213 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::progressText().
 {
     QMutexLocker locker(&d->m_mutex);
     return d->m_progressText;
 }
progressValue()
int QFutureInterfaceBase::progressValue () const
Definition at line 192 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::progressValue().
 {
     return d->m_progressValue;
 }
queryState()
bool QFutureInterfaceBase::queryState (State state) const
Definition at line 277 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::isCanceled(), isCanceled(), isFinished(), QFutureWatcherBase::isPaused(), isPaused(), QFutureWatcherBase::isRunning(), isRunning(), QFutureWatcherBase::isStarted(), isStarted(), and isThrottled().
 {
     return (d->state & state);
 }
referenceCountIsOne()
bool QFutureInterfaceBase::referenceCountIsOne () const protected
Definition at line 417 of file qfutureinterface.cpp.
 {
     return d->refCount == 1;
 }
reportCanceled()
void QFutureInterfaceBase::reportCanceled ()
Definition at line 235 of file qfutureinterface.cpp.
 {
     cancel();
 }
reportException()
void QFutureInterfaceBase::reportException (const QtConcurrent::Exception & e)
Definition at line 241 of file qfutureinterface.cpp.
 {
     QMutexLocker locker(&d->m_mutex);
     if ((d->state & Canceled) || (d->state & Finished))
         return;
     d->m_exceptionStore.setException(exception);
     d->state = State(d->state | Canceled);
     d->waitCondition.wakeAll();
     d->pausedWaitCondition.wakeAll();
     d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Canceled));
 }
reportFinished()
void QFutureInterfaceBase::reportFinished ()
Definition at line 255 of file qfutureinterface.cpp.
Referenced by QFutureInterface< T >::reportFinished(), and QFutureInterface< T >::results().
 {
     QMutexLocker locker(&d->m_mutex);
     if (!(d->state & Finished)) {
         d->state = State((d->state & ~Running) | Finished);
         d->waitCondition.wakeAll();
         d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Finished));
     }
 }
reportResultsReady()
void QFutureInterfaceBase::reportResultsReady (int beginIndex, int endIndex)
Definition at line 319 of file qfutureinterface.cpp.
 {
     if ((d->state & Canceled) || (d->state & Finished) || beginIndex == endIndex)
         return;
     d->waitCondition.wakeAll();
     if (d->manualProgress == false) {
         if (d->internal_updateProgress(d->m_progressValue + endIndex - beginIndex) == false) {
             d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::ResultsReady,
                                                beginIndex,
                                                endIndex));
             return;
         }
         d->sendCallOuts(QFutureCallOutEvent(QFutureCallOutEvent::Progress,
                                             d->m_progressValue,
                                             d->m_progressText),
                         QFutureCallOutEvent(QFutureCallOutEvent::ResultsReady,
                                             beginIndex,
                                             endIndex));
         return;
     }
     d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::ResultsReady, beginIndex, endIndex));
 }
reportStarted()
void QFutureInterfaceBase::reportStarted ()
Definition at line 225 of file qfutureinterface.cpp.
 {
     QMutexLocker locker(&d->m_mutex);
     if ((d->state & Started) || (d->state & Canceled) || (d->state & Finished))
         return;
     d->setState(State(Started | Running));
     d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Started));
 }
resultCount()
int QFutureInterfaceBase::resultCount () const
Definition at line 207 of file qfutureinterface.cpp.
Referenced by setExpectedResultCount().
 {
     QMutexLocker lock(&d->m_mutex);
     return d->internal_resultCount();
 }
resultStoreBase() [1/2]
QtConcurrent::ResultStoreBase & QFutureInterfaceBase::resultStoreBase ()
Definition at line 398 of file qfutureinterface.cpp.
Referenced by setFilterMode().
 {
     return d->m_results;
 }
resultStoreBase() [2/2]
const QtConcurrent::ResultStoreBase & QFutureInterfaceBase::resultStoreBase () const
Definition at line 403 of file qfutureinterface.cpp.
 {
     return d->m_results;
 }
setExpectedResultCount()
void QFutureInterfaceBase::setExpectedResultCount (int resultCount)
Definition at line 265 of file qfutureinterface.cpp.
 {
     if (d->manualProgress == false)
         setProgressRange(0, resultCount);
     d->m_expectedResultCount = resultCount;
 }
setFilterMode()
void QFutureInterfaceBase::setFilterMode (bool enable)
Definition at line 350 of file qfutureinterface.cpp.
 {
     QMutexLocker locker(&d->m_mutex);
     resultStoreBase().setFilterMode(enable);
 }
setPaused()
void QFutureInterfaceBase::setPaused (bool paused)
Definition at line 88 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::pause(), QFutureWatcherBase::resume(), and QFutureWatcherBase::setPaused().
 {
     QMutexLocker locker(&d->m_mutex);
     if (paused) {
         d->state = State(d->state | Paused);
         d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Paused));
     } else {
         d->state = State(d->state & ~Paused);
         d->pausedWaitCondition.wakeAll();
         d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Resumed));
     }
 }
setProgressRange()
void QFutureInterfaceBase::setProgressRange (int minimum, int maximum)
Definition at line 356 of file qfutureinterface.cpp.
Referenced by setExpectedResultCount().
 {
     QMutexLocker locker(&d->m_mutex);
     d->m_progressMinimum = minimum;
     d->m_progressMaximum = maximum;
     d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::ProgressRange, minimum, maximum));
 }
setProgressValue()
void QFutureInterfaceBase::setProgressValue (int progressValue)
Definition at line 364 of file qfutureinterface.cpp.
 {
     setProgressValueAndText(progressValue, QString());
 }
setProgressValueAndText()
void QFutureInterfaceBase::setProgressValueAndText (int progressValue, const QString & progressText)
Definition at line 369 of file qfutureinterface.cpp.
Referenced by setProgressValue().
 {
     QMutexLocker locker(&d->m_mutex);
     if (d->manualProgress == false)
         d->manualProgress = true;
     if (d->m_progressValue >= progressValue)
         return;
     if ((d->state & Canceled) || (d->state & Finished))
         return;
     if (d->internal_updateProgress(progressValue, progressText)) {
         d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Progress,
                                            d->m_progressValue,
                                            d->m_progressText));
     }
 }
setRunnable()
void QFutureInterfaceBase::setRunnable (QRunnable * runnable)
Definition at line 345 of file qfutureinterface.cpp.
 {
     d->runnable = runnable;
 }
setThrottled()
void QFutureInterfaceBase::setThrottled (bool enable)
Definition at line 114 of file qfutureinterface.cpp.
 {
     // bail out if we are not changing the state
     if ((enable && (d->state & Throttled)) || (!enable && !(d->state & Throttled)))
         return;
     // lock and change the state
     QMutexLocker lock(&d->m_mutex);
     if (enable) {
         d->state  = State(d->state | Throttled);
     } else {
         d->state  = State(d->state & ~Throttled);
         if (!(d->state & Paused))
             d->pausedWaitCondition.wakeAll();
     }
 }
togglePaused()
void QFutureInterfaceBase::togglePaused ()
Definition at line 101 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::togglePaused().
 {
     QMutexLocker locker(&d->m_mutex);
     if (d->state & Paused) {
         d->state = State(d->state & ~Paused);
         d->pausedWaitCondition.wakeAll();
         d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Resumed));
     } else {
         d->state = State(d->state | Paused);
         d->sendCallOut(QFutureCallOutEvent(QFutureCallOutEvent::Paused));
     }
 }
waitForFinished()
void QFutureInterfaceBase::waitForFinished ()
Definition at line 305 of file qfutureinterface.cpp.
Referenced by QFutureWatcherBase::waitForFinished().
 {
     if (d->state & Running) {
         QThreadPool::globalInstance()->d_func()->stealRunnable(d->runnable);
         QMutexLocker lock(&d->m_mutex);
         while (d->state & Running)
             d->waitCondition.wait(&d->m_mutex);
     }
     d->m_exceptionStore.throwPossibleException();
 }
waitForNextResult()
bool QFutureInterfaceBase::waitForNextResult ()
Definition at line 168 of file qfutureinterface.cpp.
 {
     QMutexLocker lock(&d->m_mutex);
     return d->internal_waitForNextResult();
 }
waitForResult()
void QFutureInterfaceBase::waitForResult (int resultIndex)
Definition at line 282 of file qfutureinterface.cpp.
Referenced by QFutureInterface< T >::results().
 {
     d->m_exceptionStore.throwPossibleException();
     if (!(d->state & Running))
         return;
     // To avoid deadlocks and reduce the number of threads used, try to
     // run the runnable in the current thread.
     QThreadPool::globalInstance()->d_func()->stealRunnable(d->runnable);
     QMutexLocker lock(&d->m_mutex);
     if (!(d->state & Running))
         return;
     const int waitIndex = (resultIndex == -1) ? INT_MAX : resultIndex;
     while ((d->state & Running) && d->internal_isResultReadyAt(waitIndex) == false)
         d->waitCondition.wait(&d->m_mutex);
     d->m_exceptionStore.throwPossibleException();
 }
waitForResume()
void QFutureInterfaceBase::waitForResume ()
Definition at line 174 of file qfutureinterface.cpp.
 {
     // return early if possible to avoid taking the mutex lock.
     if ((d->state & Paused) == false || (d->state & Canceled))
         return;
     QMutexLocker lock(&d->m_mutex);
     if ((d->state & Paused) == false || (d->state & Canceled))
         return;
     // decrease active thread count since this thread will wait.
     QThreadPool::globalInstance()->releaseThread();
     d->pausedWaitCondition.wait(&d->m_mutex);
     QThreadPool::globalInstance()->reserveThread();
 }
Friends and Related Functions
QFutureWatcherBase
friend class QFutureWatcherBase friend
Definition at line 143 of file qfutureinterface.h.
QFutureWatcherBasePrivate
friend class QFutureWatcherBasePrivate friend
Definition at line 144 of file qfutureinterface.h.
Properties
d
QFutureInterfaceBasePrivate* QFutureInterfaceBase::d private
Definition at line 140 of file qfutureinterface.h.
Referenced by cancel(), exceptionStore(), expectedResultCount(), isProgressUpdateNeeded(), isResultReadyAt(), mutex(), operator!=(), operator=(), operator==(), progressMaximum(), progressMinimum(), progressText(), progressValue(), QFutureInterfaceBase(), queryState(), referenceCountIsOne(), reportException(), reportFinished(), reportResultsReady(), reportStarted(), resultCount(), resultStoreBase(), setExpectedResultCount(), setFilterMode(), setPaused(), setProgressRange(), setProgressValueAndText(), setRunnable(), setThrottled(), togglePaused(), waitForFinished(), waitForNextResult(), waitForResult(), waitForResume(), and ~QFutureInterfaceBase().
The documentation for this class was generated from the following files:
/src/corelib/concurrent/qfutureinterface.h
/src/corelib/concurrent/qfutureinterface.cpp