Qt 4.8: QCoreWlanEngine Class Reference
QCoreWlanEngine Class Reference
#include <qcorewlanengine.h>
Public Functions
quint64 bytesReceived (const QString &id)
quint64 bytesWritten (const QString &id)
QNetworkConfigurationManager::Capabilities capabilities () const
void connectToId (const QString &id)
QNetworkSessionPrivate * createSessionBackend ()
QNetworkConfigurationPrivatePointer defaultConfiguration ()
void disconnectFromId (const QString &id)
QString getInterfaceFromId (const QString &id)
bool hasIdentifier (const QString &id)
Q_INVOKABLE void initialize ()
QCoreWlanEngine (QObject *parent=0)
Q_INVOKABLE void requestUpdate ()
bool requiresPolling () const
QNetworkSession::State sessionStateForId (const QString &id)
quint64 startTime (const QString &id)
~QCoreWlanEngine ()
Public Functions inherited from QBearerEngineImpl
QBearerEngineImpl (QObject *parent=0)
~QBearerEngineImpl ()
Public Functions inherited from QBearerEngine
bool configurationsInUse () const
QBearerEngine (QObject *parent=0)
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void startNetworkChangeLoop ()
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void doRequestUpdate ()
void networksChanged ()
Private Functions
quint64 getBytes (const QString &interfaceName, bool b)
bool isWifiReady (const QString &dev)
Properties
QList< QNetworkConfigurationPrivate * > foundConfigurations
bool hasWifi
CFRunLoopSourceRef runloopSource
bool scanning
QScanThread * scanThread
SCDynamicStoreRef storeSession
Friends
class QScanThread
Additional Inherited Members
Public Types inherited from QBearerEngineImpl
enum ConnectionError { InterfaceLookupError = 0, ConnectError, OperationNotSupported, DisconnectionError }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QBearerEngineImpl
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 59 of file qcorewlanengine.h.
Constructors and Destructors
QCoreWlanEngine()
QCoreWlanEngine::QCoreWlanEngine (QObject * parent = 0)
Definition at line 397 of file qcorewlanengine_10_6.mm.
 :   QBearerEngineImpl(parent), scanThread(0)
 {
     scanThread = new QScanThread(this);
     connect(scanThread, SIGNAL(networksChanged()),
             this, SLOT(networksChanged()));
 }
~QCoreWlanEngine()
QCoreWlanEngine::~QCoreWlanEngine ()
Definition at line 405 of file qcorewlanengine_10_6.mm.
 {
     while (!foundConfigurations.isEmpty())
         delete foundConfigurations.takeFirst();
     [listener remove];
     [listener release];
 }
Functions
bytesReceived()
quint64 QCoreWlanEngine::bytesReceived (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 833 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     const QString interfaceStr = getInterfaceFromId(id);
     return getBytes(interfaceStr,true);
 }
bytesWritten()
quint64 QCoreWlanEngine::bytesWritten (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 826 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     const QString interfaceStr = getInterfaceFromId(id);
     return getBytes(interfaceStr,false);
 }
capabilities()
QNetworkConfigurationManager::Capabilities QCoreWlanEngine::capabilities () const virtual
Implements QBearerEngine.
Definition at line 680 of file qcorewlanengine_10_6.mm.
 {
     return QNetworkConfigurationManager::ForcedRoaming;
 }
connectToId()
void QCoreWlanEngine::connectToId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 446 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     NSAutoreleasePool *autoreleasepool = [[NSAutoreleasePool alloc] init];
     QString interfaceString = getInterfaceFromId(id);
     CWInterface *wifiInterface =
         [CWInterface interfaceWithName: (NSString *)QCFString::toCFStringRef(interfaceString)];
     if ([wifiInterface power]) {
         NSError *err = nil;
         NSMutableDictionary *params = [NSMutableDictionary dictionaryWithCapacity:0];
         QString wantedSsid;
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
         const QString idHash = QString::number(qHash(QLatin1String("corewlan:") + ptr->name));
         const QString idHash2 = QString::number(qHash(QLatin1String("corewlan:") + scanThread->getNetworkNameFromSsid(ptr->name)));
         bool using8021X = false;
         if (idHash2 != id) {
             NSArray *array = [CW8021XProfile allUser8021XProfiles];
             for (NSUInteger i = 0; i < [array count]; ++i) {
                 const QString networkNameHashCheck = QString::number(qHash(QLatin1String("corewlan:") + QCFString::toQString(CFStringRef([[array objectAtIndex:i] userDefinedName]))));
                 const QString ssidHash = QString::number(qHash(QLatin1String("corewlan:") + QCFString::toQString(CFStringRef([[array objectAtIndex:i] ssid]))));
                 if (id == networkNameHashCheck || id == ssidHash) {
                     const QString thisName = scanThread->getSsidFromNetworkName(id);
                     if (thisName.isEmpty())
                         wantedSsid = id;
                     else
                         wantedSsid = thisName;
                     [params setValue: [array objectAtIndex:i] forKey:kCWAssocKey8021XProfile];
                     using8021X = true;
                     break;
                 }
             }
         }
         if (!using8021X) {
             QString wantedNetwork;
             QMapIterator<QString, QMap<QString,QString> > i(scanThread->userProfiles);
             while (i.hasNext()) {
                 i.next();
                 wantedNetwork = i.key();
                 const QString networkNameHash = QString::number(qHash(QLatin1String("corewlan:") + wantedNetwork));
                 if (id == networkNameHash) {
                     wantedSsid =  scanThread->getSsidFromNetworkName(wantedNetwork);
                     break;
                 }
             }
         }
         NSDictionary *scanParameters = [NSDictionary dictionaryWithObjectsAndKeys:
                                         [NSNumber numberWithBool:YES], kCWScanKeyMerge,
                                         [NSNumber numberWithInt:kCWScanTypeFast], kCWScanKeyScanType,
                                         [NSNumber numberWithInteger:100], kCWScanKeyRestTime,
                                         (NSString *)QCFString::toCFStringRef(wantedSsid), kCWScanKeySSID,
                                         nil];
         NSArray *scanArray = [wifiInterface scanForNetworksWithParameters:scanParameters error:&err];
         if(!err) {
             for(uint row=0; row < [scanArray count]; row++ ) {
                 CWNetwork *apNetwork = [scanArray objectAtIndex:row];
                 if(wantedSsid == QCFString::toQString(CFStringRef([apNetwork ssid]))) {
                     if(!using8021X) {
                         SecKeychainAttribute attributes[3];
                         NSString *account = [apNetwork ssid];
                         NSString *keyKind = @"AirPort network password";
                         NSString *keyName = account;
                         attributes[0].tag = kSecAccountItemAttr;
                         attributes[0].data = (void *)[account UTF8String];
                         attributes[0].length = [account length];
                         attributes[1].tag = kSecDescriptionItemAttr;
                         attributes[1].data = (void *)[keyKind UTF8String];
                         attributes[1].length = [keyKind length];
                         attributes[2].tag = kSecLabelItemAttr;
                         attributes[2].data = (void *)[keyName UTF8String];
                         attributes[2].length = [keyName length];
                         SecKeychainAttributeList attributeList = {3,attributes};
                         SecKeychainSearchRef searchRef;
                         SecKeychainSearchCreateFromAttributes(NULL, kSecGenericPasswordItemClass, &attributeList, &searchRef);
                         NSString *password = @"";
                         SecKeychainItemRef searchItem;
                         if (SecKeychainSearchCopyNext(searchRef, &searchItem) == noErr) {
                             UInt32 realPasswordLength;
                             SecKeychainAttribute attributesW[8];
                             attributesW[0].tag = kSecAccountItemAttr;
                             SecKeychainAttributeList listW = {1,attributesW};
                             char *realPassword;
                             OSStatus status = SecKeychainItemCopyContent(searchItem, NULL, &listW, &realPasswordLength,(void **)&realPassword);
                             if (status == noErr) {
                                 if (realPassword != NULL) {
                                     QByteArray pBuf;
                                     pBuf.resize(realPasswordLength);
                                     pBuf.prepend(realPassword);
                                     pBuf.insert(realPasswordLength,'\0');
                                     password = [NSString stringWithUTF8String:pBuf];
                                 }
                                 SecKeychainItemFreeContent(&listW, realPassword);
                             }
                             CFRelease(searchItem);
                         } else {
                             qDebug() << "SecKeychainSearchCopyNext error";
                         }
                         [params setValue: password forKey: kCWAssocKeyPassphrase];
                     } // end using8021X
                     bool result = [wifiInterface associateToNetwork: apNetwork parameters:[NSDictionary dictionaryWithDictionary:params] error:&err];
                     if(!err) {
                         if(!result) {
                             emit connectionError(id, ConnectError);
                         } else {
                             return;
                         }
                     } else {
                         qDebug() <<"associate ERROR"<<  QCFString::toQString(CFStringRef([err localizedDescription ]));
                     }
                 }
             } //end scan network
         } else {
             qDebug() <<"scan ERROR"<<  QCFString::toQString(CFStringRef([err localizedDescription ]));
         }
         emit connectionError(id, InterfaceLookupError);
     }
     locker.unlock();
     emit connectionError(id, InterfaceLookupError);
     [autoreleasepool release];
 }
createSessionBackend()
QNetworkSessionPrivate * QCoreWlanEngine::createSessionBackend () virtual
Implements QBearerEngine.
Definition at line 738 of file qcorewlanengine_10_6.mm.
 {
     return new QNetworkSessionPrivateImpl;
 }
defaultConfiguration()
QNetworkConfigurationPrivatePointer QCoreWlanEngine::defaultConfiguration () virtual
Implements QBearerEngine.
Definition at line 743 of file qcorewlanengine_10_6.mm.
 {
     return QNetworkConfigurationPrivatePointer();
 }
disconnectFromId()
void QCoreWlanEngine::disconnectFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 597 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     QString interfaceString = getInterfaceFromId(id);
     NSAutoreleasePool *autoreleasepool = [[NSAutoreleasePool alloc] init];
     CWInterface *wifiInterface =
         [CWInterface interfaceWithName: (NSString *)QCFString::toCFStringRef(interfaceString)];
     [wifiInterface disassociate];
     if ([[wifiInterface interfaceState]intValue] != kCWInterfaceStateInactive) {
         locker.unlock();
         emit connectionError(id, DisconnectionError);
         locker.relock();
     }
     [autoreleasepool release];
 }
doRequestUpdate
void QCoreWlanEngine::doRequestUpdate () private slot
Definition at line 622 of file qcorewlanengine_10_6.mm.
Referenced by requestUpdate().
 {
     QMutexLocker locker(&mutex);
     NSAutoreleasePool *autoreleasepool = [[NSAutoreleasePool alloc] init];
     NSArray *wifiInterfaces = [CWInterface supportedInterfaces];
     for (uint row = 0; row < [wifiInterfaces count]; ++row) {
             scanThread->interfaceName = QCFString::toQString(CFStringRef([wifiInterfaces objectAtIndex:row]));
             scanThread->start();
     }
     locker.unlock();
     if ([wifiInterfaces count] == 0)
         networksChanged();
     [autoreleasepool release];
 }
getBytes()
quint64 QCoreWlanEngine::getBytes (const QString & interfaceName, bool b) private
Definition at line 894 of file qcorewlanengine_10_6.mm.
Referenced by bytesReceived(), and bytesWritten().
 {
     struct ifaddrs *ifAddressList, *ifAddress;
     struct if_data *if_data;
     quint64 bytes = 0;
     ifAddressList = nil;
     if(getifaddrs(&ifAddressList) == 0) {
         for(ifAddress = ifAddressList; ifAddress; ifAddress = ifAddress->ifa_next) {
             if(interfaceName == ifAddress->ifa_name) {
                 if_data = (struct if_data*)ifAddress->ifa_data;
                 if(b) {
                     bytes = if_data->ifi_ibytes;
                     break;
                 } else {
                     bytes = if_data->ifi_obytes;
                     break;
                 }
             }
         }
         freeifaddrs(ifAddressList);
     }
     return bytes;
 }
getInterfaceFromId()
QString QCoreWlanEngine::getInterfaceFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 432 of file qcorewlanengine_10_6.mm.
Referenced by bytesReceived(), bytesWritten(), connectToId(), and disconnectFromId().
 {
     QMutexLocker locker(&mutex);
     return scanThread->configurationInterface.value(id);
 }
hasIdentifier()
bool QCoreWlanEngine::hasIdentifier (const QString & id) virtual
Implements QBearerEngine.
Definition at line 439 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     return scanThread->configurationInterface.contains(id);
 }
initialize()
void QCoreWlanEngine::initialize ()
Definition at line 413 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     NSAutoreleasePool *autoreleasepool = [[NSAutoreleasePool alloc] init];
     if([[CWInterface supportedInterfaces] count] > 0 && !listener) {
         listener = [[QT_MANGLE_NAMESPACE(QNSListener) alloc] init];
         listener.engine = this;
         hasWifi = true;
     } else {
         hasWifi = false;
     }
     storeSession = NULL;
     startNetworkChangeLoop();
     [autoreleasepool release];
 }
isWifiReady()
bool QCoreWlanEngine::isWifiReady (const QString & dev) private
Definition at line 639 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     bool haswifi = false;
     if(hasWifi) {
         NSAutoreleasePool *autoreleasepool = [[NSAutoreleasePool alloc] init];
         CWInterface *defaultInterface = [CWInterface interfaceWithName: (NSString *)QCFString::toCFStringRef(wifiDeviceName)];
         if([defaultInterface power]) {
             haswifi = true;
         }
         [autoreleasepool release];
     }
     return haswifi;
 }
networksChanged
void QCoreWlanEngine::networksChanged () private slot
Definition at line 753 of file qcorewlanengine_10_6.mm.
Referenced by doRequestUpdate(), and QCoreWlanEngine().
 {
     QMutexLocker locker(&mutex);
     QStringList previous = accessPointConfigurations.keys();
     QList<QNetworkConfigurationPrivate *> foundConfigurations = scanThread->getConfigurations();
     while (!foundConfigurations.isEmpty()) {
         QNetworkConfigurationPrivate *cpPriv = foundConfigurations.takeFirst();
         previous.removeAll(cpPriv->id);
         if (accessPointConfigurations.contains(cpPriv->id)) {
             QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(cpPriv->id);
             bool changed = false;
             ptr->mutex.lock();
             if (ptr->isValid != cpPriv->isValid) {
                 ptr->isValid = cpPriv->isValid;
                 changed = true;
             }
             if (ptr->name != cpPriv->name) {
                 ptr->name = cpPriv->name;
                 changed = true;
             }
             if (ptr->bearerType != cpPriv->bearerType) {
                 ptr->bearerType = cpPriv->bearerType;
                 changed = true;
             }
             if (ptr->state != cpPriv->state) {
                 ptr->state = cpPriv->state;
                 changed = true;
             }
             ptr->mutex.unlock();
             if (changed) {
                 locker.unlock();
                 emit configurationChanged(ptr);
                 locker.relock();
             }
             delete cpPriv;
         } else {
             QNetworkConfigurationPrivatePointer ptr(cpPriv);
             accessPointConfigurations.insert(ptr->id, ptr);
             locker.unlock();
             emit configurationAdded(ptr);
             locker.relock();
         }
     }
     while (!previous.isEmpty()) {
         QNetworkConfigurationPrivatePointer ptr =
             accessPointConfigurations.take(previous.takeFirst());
         locker.unlock();
         emit configurationRemoved(ptr);
         locker.relock();
     }
     locker.unlock();
     emit updateCompleted();
 }
requestUpdate()
void QCoreWlanEngine::requestUpdate ()
Definition at line 616 of file qcorewlanengine_10_6.mm.
Referenced by networkChangeCallback().
 {
     scanThread->getUserConfigurations();
     doRequestUpdate();
 }
requiresPolling()
bool QCoreWlanEngine::requiresPolling () const virtual
Reimplemented from QBearerEngine.
Definition at line 748 of file qcorewlanengine_10_6.mm.
 {
     return true;
 }
sessionStateForId()
QNetworkSession::State QCoreWlanEngine::sessionStateForId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 655 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (!ptr)
         return QNetworkSession::Invalid;
     if (!ptr->isValid) {
         return QNetworkSession::Invalid;
     } else if ((ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         return QNetworkSession::Connected;
     } else if ((ptr->state & QNetworkConfiguration::Discovered) ==
                 QNetworkConfiguration::Discovered) {
         return QNetworkSession::Disconnected;
     } else if ((ptr->state & QNetworkConfiguration::Defined) == QNetworkConfiguration::Defined) {
         return QNetworkSession::NotAvailable;
     } else if ((ptr->state & QNetworkConfiguration::Undefined) ==
                 QNetworkConfiguration::Undefined) {
         return QNetworkSession::NotAvailable;
     }
     return QNetworkSession::Invalid;
 }
startNetworkChangeLoop()
void QCoreWlanEngine::startNetworkChangeLoop () protected
Definition at line 685 of file qcorewlanengine_10_6.mm.
Referenced by initialize().
 {
     SCDynamicStoreContext dynStoreContext = { 0, this/*(void *)storeSession*/, NULL, NULL, NULL };
     storeSession = SCDynamicStoreCreate(NULL,
                                  CFSTR("networkChangeCallback"),
                                  networkChangeCallback,
                                  &dynStoreContext);
     if (!storeSession ) {
         qWarning() << "could not open dynamic store: error:" << SCErrorString(SCError());
         return;
     }
     CFMutableArrayRef notificationKeys;
     notificationKeys = CFArrayCreateMutable(NULL, 0, &kCFTypeArrayCallBacks);
     CFMutableArrayRef patternsArray;
     patternsArray = CFArrayCreateMutable(NULL, 0, &kCFTypeArrayCallBacks);
     CFStringRef storeKey;
     storeKey = SCDynamicStoreKeyCreateNetworkGlobalEntity(NULL,
                                                      kSCDynamicStoreDomainState,
                                                      kSCEntNetIPv4);
     CFArrayAppendValue(notificationKeys, storeKey);
     CFRelease(storeKey);
     storeKey = SCDynamicStoreKeyCreateNetworkServiceEntity(NULL,
                                                       kSCDynamicStoreDomainState,
                                                       kSCCompAnyRegex,
                                                       kSCEntNetIPv4);
     CFArrayAppendValue(patternsArray, storeKey);
     CFRelease(storeKey);
     if (!SCDynamicStoreSetNotificationKeys(storeSession , notificationKeys, patternsArray)) {
         qWarning() << "register notification error:"<< SCErrorString(SCError());
         CFRelease(storeSession );
         CFRelease(notificationKeys);
         CFRelease(patternsArray);
         return;
     }
     CFRelease(notificationKeys);
     CFRelease(patternsArray);
     runloopSource = SCDynamicStoreCreateRunLoopSource(NULL, storeSession , 0);
     if (!runloopSource) {
         qWarning() << "runloop source error:"<< SCErrorString(SCError());
         CFRelease(storeSession );
         return;
     }
     CFRunLoopAddSource(CFRunLoopGetCurrent(), runloopSource, kCFRunLoopDefaultMode);
     return;
 }
startTime()
quint64 QCoreWlanEngine::startTime (const QString & id) virtual
Reimplemented from QBearerEngineImpl.
Definition at line 840 of file qcorewlanengine_10_6.mm.
 {
     QMutexLocker locker(&mutex);
     NSAutoreleasePool *autoreleasepool = [[NSAutoreleasePool alloc] init];
     quint64 timestamp = 0;
     NSString *filePath = @"/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist";
     NSDictionary* plistDict = [[[NSDictionary alloc] initWithContentsOfFile:filePath] autorelease];
     if(plistDict == nil)
         return timestamp;
     NSString *input = @"KnownNetworks";
     NSString *timeStampStr = @"_timeStamp";
     NSString *ssidStr = @"SSID_STR";
     for (id key in plistDict) {
         if ([input isEqualToString:key]) {
             NSDictionary *knownNetworksDict = [plistDict objectForKey:key];
             if(knownNetworksDict == nil)
                 return timestamp;
             for (id networkKey in knownNetworksDict) {
                 bool isFound = false;
                 NSDictionary *itemDict = [knownNetworksDict objectForKey:networkKey];
                 if(itemDict == nil)
                     return timestamp;
                 NSInteger dictSize = [itemDict count];
                 id objects[dictSize];
                 id keys[dictSize];
                 [itemDict getObjects:objects andKeys:keys];
                 bool ok = false;
                 for(int i = 0; i < dictSize; i++) {
                     if([ssidStr isEqualToString:keys[i]]) {
                         const QString ident = QString::number(qHash(QLatin1String("corewlan:") + QCFString::toQString(CFStringRef(objects[i]))));
                         if(ident == identifier) {
                             ok = true;
                         }
                     }
                     if(ok && [timeStampStr isEqualToString:keys[i]]) {
                         timestamp = (quint64)[objects[i] timeIntervalSince1970];
                         isFound = true;
                         break;
                     }
                 }
                 if(isFound)
                     break;
             }
         }
     }
     [autoreleasepool release];
     return timestamp;
 }
Friends and Related Functions
QScanThread
friend class QScanThread friend
Definition at line 61 of file qcorewlanengine.h.
Referenced by QCoreWlanEngine().
Properties
foundConfigurations
QList<QNetworkConfigurationPrivate *> QCoreWlanEngine::foundConfigurations private
Definition at line 97 of file qcorewlanengine.h.
Referenced by networksChanged(), and ~QCoreWlanEngine().
hasWifi
bool QCoreWlanEngine::hasWifi private
Definition at line 101 of file qcorewlanengine.h.
Referenced by initialize(), and isWifiReady().
runloopSource
CFRunLoopSourceRef QCoreWlanEngine::runloopSource private
Definition at line 100 of file qcorewlanengine.h.
Referenced by startNetworkChangeLoop().
scanning
bool QCoreWlanEngine::scanning private
Definition at line 102 of file qcorewlanengine.h.
scanThread
QScanThread* QCoreWlanEngine::scanThread private
Definition at line 103 of file qcorewlanengine.h.
Referenced by connectToId(), doRequestUpdate(), getInterfaceFromId(), hasIdentifier(), networksChanged(), QCoreWlanEngine(), and requestUpdate().
storeSession
SCDynamicStoreRef QCoreWlanEngine::storeSession private
Definition at line 99 of file qcorewlanengine.h.
Referenced by initialize(), and startNetworkChangeLoop().
The documentation for this class was generated from the following files:
/src/plugins/bearer/corewlan/qcorewlanengine.h
/src/plugins/bearer/corewlan/qcorewlanengine_10_6.mm