Qt 4.8: QDeclarativeTextInput Class Reference
QDeclarativeTextInput Class Reference
#include <qdeclarativetextinput_p.h>
Public Types
enum CursorPosition { CursorBetweenCharacters, CursorOnCharacter }
enum EchoMode { Normal, NoEcho, Password, PasswordEchoOnEdit }
enum HAlignment { AlignLeft = Qt::AlignLeft, AlignRight = Qt::AlignRight, AlignHCenter = Qt::AlignHCenter }
enum SelectionMode { SelectCharacters, SelectWords }
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
void copy ()
void cut ()
void deselect ()
bool isRightToLeft (int start, int end)
void paste ()
void select (int start, int end)
void selectAll ()
void selectWord ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void acceptableInputChanged ()
void accepted ()
void activeFocusOnPressChanged (bool activeFocusOnPress)
void autoScrollChanged (bool autoScroll)
void canPasteChanged ()
void colorChanged (const QColor &color)
void cursorDelegateChanged ()
void cursorPositionChanged ()
void cursorRectangleChanged ()
void cursorVisibleChanged (bool isCursorVisible)
void displayTextChanged ()
void echoModeChanged (EchoMode echoMode)
void fontChanged (const QFont &font)
void horizontalAlignmentChanged (HAlignment alignment)
void inputMaskChanged (const QString &inputMask)
void inputMethodComposingChanged ()
void maximumLengthChanged (int maximumLength)
void mouseSelectionModeChanged (SelectionMode mode)
void passwordCharacterChanged ()
void readOnlyChanged (bool isReadOnly)
void selectByMouseChanged (bool selectByMouse)
void selectedTextChanged ()
void selectedTextColorChanged (const QColor &color)
void selectionColorChanged (const QColor &color)
void selectionEndChanged ()
void selectionStartChanged ()
void textChanged ()
void validatorChanged ()
Signals inherited from QDeclarativeImplicitSizePaintedItem
void implicitHeightChanged ()
void implicitWidthChanged ()
Signals inherited from QDeclarativePaintedItem
void contentsScaleChanged ()
void contentsSizeChanged ()
void fillColorChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool autoScroll () const
QRectF boundingRect () const
bool canPaste () const
Q_INVOKABLE void closeSoftwareInputPanel ()
QColor color () const
QDeclarativeComponent * cursorDelegate () const
int cursorPosition () const
QRect cursorRectangle () const
QString displayText () const
void drawContents (QPainter *p, const QRect &r)
This function is called when the cache needs to be refreshed.
EchoMode echoMode () const
HAlignment effectiveHAlign () const
bool focusOnPress () const
QFont font () const
HAlignment hAlign () const
bool hasAcceptableInput () const
Qt::InputMethodHints imHints () const
QString inputMask () const
QVariant inputMethodQuery (Qt::InputMethodQuery property) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Returns the value of the given property.
bool isCursorVisible () const
bool isInputMethodComposing () const
bool isReadOnly () const
int maxLength () const
SelectionMode mouseSelectionMode () const
Q_INVOKABLE void moveCursorSelection (int pos)
Q_INVOKABLE void moveCursorSelection (int pos, SelectionMode mode)
Q_INVOKABLE void openSoftwareInputPanel ()
QString passwordCharacter () const
Q_INVOKABLE int positionAt (int x) const
Q_INVOKABLE int positionAt (int x, CursorPosition position) const
Q_INVOKABLE QRectF positionToRectangle (int pos) const
QDeclarativeTextInput (QDeclarativeItem *parent=0)
void resetHAlign ()
bool selectByMouse () const
QString selectedText () const
QColor selectedTextColor () const
QColor selectionColor () const
int selectionEnd () const
int selectionStart () const
void setAutoScroll (bool)
void setColor (const QColor &c)
void setCursorDelegate (QDeclarativeComponent *)
void setCursorPosition (int cp)
void setCursorVisible (bool on)
void setEchoMode (EchoMode echo)
void setFocusOnPress (bool)
void setFont (const QFont &font)
void setHAlign (HAlignment align)
void setIMHints (Qt::InputMethodHints hints)
void setInputMask (const QString &im)
void setMaxLength (int ml)
void setMouseSelectionMode (SelectionMode mode)
void setPasswordCharacter (const QString &str)
void setReadOnly (bool)
void setSelectByMouse (bool)
void setSelectedTextColor (const QColor &c)
void setSelectionColor (const QColor &c)
void setText (const QString &)
void setValidator (QValidator *v)
QString text () const
QValidator * validator () const
~QDeclarativeTextInput ()
Public Functions inherited from QDeclarativeImplicitSizePaintedItem
QDeclarativeImplicitSizePaintedItem (QDeclarativeItem *parent=0)
Public Functions inherited from QDeclarativePaintedItem
qreal contentsScale () const
QSize contentsSize () const
QColor fillColor () const
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
int pixelCacheSize () const
QDeclarativePaintedItem (QDeclarativeItem *parent=0)
Constructs a new QDeclarativePaintedItem with the given parent.
void setContentsScale (qreal)
void setContentsSize (const QSize &)
Sets the size of the contents to the given size.
void setFillColor (const QColor &)
void setPixelCacheSize (int pixels)
void setSmoothCache (bool on)
bool smoothCache () const
~QDeclarativePaintedItem ()
Destroys the image item.
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
bool event (QEvent *e)
void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
void inputMethodEvent (QInputMethodEvent *)
void keyPressEvent (QKeyEvent *ev)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
bool sceneEvent (QEvent *event)
Protected Functions inherited from QDeclarativeImplicitSizePaintedItem
QDeclarativeImplicitSizePaintedItem (QDeclarativeImplicitSizePaintedItemPrivate &dd, QDeclarativeItem *parent)
Protected Functions inherited from QDeclarativePaintedItem
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
QDeclarativePaintedItem (QDeclarativePaintedItemPrivate &dd, QDeclarativeItem *parent)
Constructs a new QDeclarativePaintedItem with the given parent and initialized private data member dd.
void setCacheFrozen (bool)
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual void componentComplete ()
bool heightValid () const
Returns whether the height property has been set explicitly.
void inputMethodPreHandler (QInputMethodEvent *)
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Private Slots
void createCursor ()
void cursorPosChanged ()
void q_canPasteChanged ()
void q_textChanged ()
void selectionChanged ()
void updateCursorRectangle ()
void updateRect (const QRect &r=QRect())
void updateSize (bool needsRedraw=true)
Properties
bool acceptableInput
bool activeFocusOnPress
bool autoScroll
bool canPaste
QColor color
QDeclarativeComponent * cursorDelegate
int cursorPosition
QRect cursorRectangle
Returns a Rect which encompasses the cursor, but which may be larger than is required.
bool cursorVisible
QString displayText
EchoMode echoMode
QFont font
HAlignment horizontalAlignment
QString inputMask
bool inputMethodComposing
Qt::InputMethodHints inputMethodHints
int maximumLength
SelectionMode mouseSelectionMode
QString passwordCharacter
bool readOnly
bool selectByMouse
QString selectedText
QColor selectedTextColor
QColor selectionColor
int selectionEnd
int selectionStart
QString text
QValidator * validator
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QDeclarativePaintedItem
void clearCache ()
Marks the entirety of the contents cache as dirty.
void dirtyCache (const QRect &)
Marks areas of the cache that intersect with the given rect as dirty and in need of being refreshed.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 61 of file qdeclarativetextinput_p.h.
Enumerations
CursorPosition
enum QDeclarativeTextInput::CursorPosition
Enumerator
CursorBetweenCharacters
CursorOnCharacter
Definition at line 123 of file qdeclarativetextinput_p.h.
{
         CursorBetweenCharacters,
         CursorOnCharacter
     };
EchoMode
enum QDeclarativeTextInput::EchoMode
Enumerator
Normal
NoEcho
Password
PasswordEchoOnEdit
Definition at line 105 of file qdeclarativetextinput_p.h.
                   {//To match QLineEdit::EchoMode
         Normal,
         NoEcho,
         Password,
         PasswordEchoOnEdit
     };
HAlignment
enum QDeclarativeTextInput::HAlignment
Enumerator
AlignLeft
AlignRight
AlignHCenter
Definition at line 112 of file qdeclarativetextinput_p.h.
                     {
         AlignLeft = Qt::AlignLeft,
         AlignRight = Qt::AlignRight,
         AlignHCenter = Qt::AlignHCenter
     };
SelectionMode
enum QDeclarativeTextInput::SelectionMode
Enumerator
SelectCharacters
SelectWords
Definition at line 118 of file qdeclarativetextinput_p.h.
{
         SelectCharacters,
         SelectWords
     };
Constructors and Destructors
QDeclarativeTextInput()
QDeclarativeTextInput::QDeclarativeTextInput (QDeclarativeItem * parent = 0)
Definition at line 83 of file qdeclarativetextinput.cpp.
     : QDeclarativeImplicitSizePaintedItem(*(new QDeclarativeTextInputPrivate), parent)
 {
     Q_D(QDeclarativeTextInput);
     d->init();
 }
~QDeclarativeTextInput()
QDeclarativeTextInput::~QDeclarativeTextInput ()
Definition at line 90 of file qdeclarativetextinput.cpp.
 {
 }
Functions
acceptableInputChanged
void QDeclarativeTextInput::acceptableInputChanged () signal
Referenced by q_textChanged(), and setValidator().
accepted
void QDeclarativeTextInput::accepted () signal
Referenced by QDeclarativeTextInputPrivate::init().
activeFocusOnPressChanged
void QDeclarativeTextInput::activeFocusOnPressChanged (bool activeFocusOnPress) signal
Referenced by setFocusOnPress().
autoScroll()
bool QDeclarativeTextInput::autoScroll () const
Referenced by setFocusOnPress(), and QDeclarativeTextInputPrivate::updateHorizontalScroll().
autoScrollChanged
void QDeclarativeTextInput::autoScrollChanged (bool autoScroll) signal
Referenced by setAutoScroll().
boundingRect()
QRectF QDeclarativeTextInput::boundingRect () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativePaintedItem.
Definition at line 2159 of file qdeclarativetextinput.cpp.
Referenced by drawContents(), and mouseReleaseEvent().
 {
     Q_D(const QDeclarativeTextInput);
     QRectF r = QDeclarativePaintedItem::boundingRect();
     int cursorWidth = d->cursorItem ? d->cursorItem->width() : d->control->cursorWidth();
     // Could include font max left/right bearings to either side of rectangle.
     r.setRight(r.right() + cursorWidth);
     return r;
 }
canPaste()
bool QDeclarativeTextInput::canPaste () const
Referenced by QDeclarativeTextInputPrivate::init(), and setMouseSelectionMode().
canPasteChanged
void QDeclarativeTextInput::canPasteChanged () signal
Referenced by q_canPasteChanged().
closeSoftwareInputPanel()
void QDeclarativeTextInput::closeSoftwareInputPanel ()
Definition at line 1996 of file qdeclarativetextinput.cpp.
 {
     QEvent event(QEvent::CloseSoftwareInputPanel);
     if (qApp) {
         QEvent event(QEvent::CloseSoftwareInputPanel);
         if (QGraphicsView * view = qobject_cast<QGraphicsView*>(qApp->focusWidget())) {
             if (view->scene() && view->scene() == scene()) {
                 QApplication::sendEvent(view, &event);
             }
         }
     }
 }
color()
QColor QDeclarativeTextInput::color () const
Referenced by setFont(), setSelectedTextColor(), and setSelectionColor().
colorChanged
void QDeclarativeTextInput::colorChanged (const QColor & color) signal
Referenced by setColor().
copy
void QDeclarativeTextInput::copy () slot
Definition at line 1617 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     d->control->copy();
 }
createCursor
void QDeclarativeTextInput::createCursor () private slot
Definition at line 1091 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::startCreatingCursor().
 {
     Q_D(QDeclarativeTextInput);
     if(d->cursorComponent->isError()){
         qmlInfo(this, d->cursorComponent->errors()) << tr("Could not load cursor delegate");
         return;
     }
     if(!d->cursorComponent->isReady())
         return;
     if(d->cursorItem)
         delete d->cursorItem;
     d->cursorItem = qobject_cast<QDeclarativeItem*>(d->cursorComponent->create());
     if(!d->cursorItem){
         qmlInfo(this, d->cursorComponent->errors()) << tr("Could not instantiate cursor delegate");
         return;
     }
     QDeclarative_setParent_noEvent(d->cursorItem, this);
     d->cursorItem->setParentItem(this);
     d->cursorItem->setX(d->control->cursorToX());
     d->cursorItem->setHeight(d->control->height()-1); // -1 to counter QLineControl's +1 which is not consistent with Text.
 }
cursorDelegate()
QDeclarativeComponent* QDeclarativeTextInput::cursorDelegate () const
Referenced by setIMHints().
cursorDelegateChanged
void QDeclarativeTextInput::cursorDelegateChanged () signal
Referenced by setCursorDelegate().
cursorPosChanged
void QDeclarativeTextInput::cursorPosChanged () private slot
Definition at line 2083 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::init().
 {
     Q_D(QDeclarativeTextInput);
     updateCursorRectangle();
     emit cursorPositionChanged();
     d->control->resetCursorBlinkTimer();
     if(!d->control->hasSelectedText()){
         if(d->lastSelectionStart != d->control->cursor()){
             d->lastSelectionStart = d->control->cursor();
             emit selectionStartChanged();
         }
         if(d->lastSelectionEnd != d->control->cursor()){
             d->lastSelectionEnd = d->control->cursor();
             emit selectionEndChanged();
         }
     }
 }
cursorPosition()
int QDeclarativeTextInput::cursorPosition () const
Referenced by keyPressEvent(), and setCursorVisible().
cursorPositionChanged
void QDeclarativeTextInput::cursorPositionChanged () signal
Referenced by cursorPosChanged(), and QDeclarativeTextInputPrivate::init().
cursorRectangle()
QRect QDeclarativeTextInput::cursorRectangle () const
Referenced by inputMethodQuery(), positionToRectangle(), and setCursorPosition().
cursorRectangleChanged
void QDeclarativeTextInput::cursorRectangleChanged () signal
Referenced by updateCursorRectangle().
cursorVisibleChanged
void QDeclarativeTextInput::cursorVisibleChanged (bool isCursorVisible) signal
Referenced by setCursorVisible().
cut
void QDeclarativeTextInput::cut () slot
Definition at line 1602 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     d->control->copy();
     d->control->del();
 }
deselect
void QDeclarativeTextInput::deselect () slot
Definition at line 1553 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     d->control->deselect();
 }
displayText()
QString QDeclarativeTextInput::displayText () const
Referenced by inputMethodQuery(), and setPasswordCharacter().
displayTextChanged
void QDeclarativeTextInput::displayTextChanged () signal
Referenced by QDeclarativeTextInputPrivate::init(), and q_textChanged().
drawContents()
void QDeclarativeTextInput::drawContents (QPainter * painter, const QRect & rect) virtual
This function is called when the cache needs to be refreshed.
When sub-classing QDeclarativePaintedItem this function should be implemented so as to paint the contents of the item using the given painter for the area of the contents specified by rect.
Reimplemented from QDeclarativeImplicitSizePaintedItem.
Definition at line 1485 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     p->setRenderHint(QPainter::TextAntialiasing, true);
     p->save();
     p->setPen(QPen(d->color));
     int flags = QLineControl::DrawText;
     if(!isReadOnly() && d->cursorVisible && !d->cursorItem)
         flags |= QLineControl::DrawCursor;
     if (d->control->hasSelectedText())
             flags |= QLineControl::DrawSelections;
     QPoint offset = QPoint(0,0);
     QFontMetrics fm = QFontMetrics(d->font);
     QRect br(boundingRect().toRect());
     if (d->autoScroll) {
         // the y offset is there to keep the baseline constant in case we have script changes in the text.
         offset = br.topLeft() - QPoint(d->hscroll, d->control->ascent() - fm.ascent());
     } else {
         offset = QPoint(d->hscroll, 0);
     }
     d->control->draw(p, offset, r, flags);
     p->restore();
 }
echoMode()
EchoMode QDeclarativeTextInput::echoMode () const
Referenced by setEchoMode(), setPasswordCharacter(), and QDeclarativeTextInputPrivate::updateInputMethodHints().
echoModeChanged
void QDeclarativeTextInput::echoModeChanged (EchoMode echoMode) signal
Referenced by setEchoMode().
effectiveHAlign()
QDeclarativeTextInput::HAlignment QDeclarativeTextInput::effectiveHAlign () const
Definition at line 425 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::updateHorizontalScroll().
 {
     Q_D(const QDeclarativeTextInput);
     QDeclarativeTextInput::HAlignment effectiveAlignment = d->hAlign;
     if (!d->hAlignImplicit && d->effectiveLayoutMirror) {
         switch (d->hAlign) {
         case QDeclarativeTextInput::AlignLeft:
             effectiveAlignment = QDeclarativeTextInput::AlignRight;
             break;
         case QDeclarativeTextInput::AlignRight:
             effectiveAlignment = QDeclarativeTextInput::AlignLeft;
             break;
         default:
             break;
         }
     }
     return effectiveAlignment;
 }
event()
bool QDeclarativeTextInput::event (QEvent * ev) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1389 of file qdeclarativetextinput.cpp.
Referenced by closeSoftwareInputPanel(), and openSoftwareInputPanel().
 {
     Q_D(QDeclarativeTextInput);
     //Anything we don't deal with ourselves, pass to the control
     bool handled = false;
     switch(ev->type()){
         case QEvent::KeyPress:
         case QEvent::KeyRelease://###Should the control be doing anything with release?
         case QEvent::InputMethod:
         case QEvent::GraphicsSceneMousePress:
         case QEvent::GraphicsSceneMouseMove:
         case QEvent::GraphicsSceneMouseRelease:
         case QEvent::GraphicsSceneMouseDoubleClick:
             break;
         default:
             handled = d->control->processEvent(ev);
     }
     if(!handled)
         handled = QDeclarativePaintedItem::event(ev);
     return handled;
 }
focusInEvent()
void QDeclarativeTextInput::focusInEvent (QFocusEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive focus in events for this item.
The default implementation calls ensureVisible().
See also
focusOutEvent(), sceneEvent(), setFocus()
Reimplemented from QGraphicsItem.
Definition at line 2009 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     if (d->showInputPanelOnFocus) {
         if (d->focusOnPress && !isReadOnly()) {
             openSoftwareInputPanel();
         }
     }
     QDeclarativePaintedItem::focusInEvent(event);
 }
focusOnPress()
bool QDeclarativeTextInput::focusOnPress () const
Definition at line 719 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     return d->focusOnPress;
 }
font()
QFont QDeclarativeTextInput::font () const
Referenced by inputMethodQuery(), setFont(), and setText().
fontChanged
void QDeclarativeTextInput::fontChanged (const QFont & font) signal
Referenced by setFont().
geometryChanged()
void QDeclarativeTextInput::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented from QDeclarativePaintedItem.
Definition at line 1411 of file qdeclarativetextinput.cpp.
 {
     if (newGeometry.width() != oldGeometry.width()) {
         updateSize();
         updateCursorRectangle();
     }
     QDeclarativePaintedItem::geometryChanged(newGeometry, oldGeometry);
 }
hAlign()
QDeclarativeTextInput::HAlignment QDeclarativeTextInput::hAlign () const
Definition at line 400 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::mirrorChange(), and QDeclarativeTextInputPrivate::setHAlign().
 {
     Q_D(const QDeclarativeTextInput);
     return d->hAlign;
 }
hasAcceptableInput()
bool QDeclarativeTextInput::hasAcceptableInput () const
Definition at line 960 of file qdeclarativetextinput.cpp.
Referenced by q_textChanged().
 {
     Q_D(const QDeclarativeTextInput);
     return d->control->hasAcceptableInput();
 }
horizontalAlignmentChanged
void QDeclarativeTextInput::horizontalAlignmentChanged (HAlignment alignment) signal
imHints()
Qt::InputMethodHints QDeclarativeTextInput::imHints () const
Definition at line 1024 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     return d->inputMethodHints;
 }
inputMask()
QString QDeclarativeTextInput::inputMask () const
Referenced by setValidator().
inputMaskChanged
void QDeclarativeTextInput::inputMaskChanged (const QString & inputMask) signal
Referenced by setInputMask().
inputMethodComposingChanged
void QDeclarativeTextInput::inputMethodComposingChanged () signal
Referenced by inputMethodEvent().
inputMethodEvent()
void QDeclarativeTextInput::inputMethodEvent (QInputMethodEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1219 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     ev->ignore();
     const bool wasComposing = d->control->preeditAreaText().length() > 0;
     inputMethodPreHandler(ev);
     if (!ev->isAccepted()) {
         if (d->control->isReadOnly()) {
             ev->ignore();
         } else {
             d->control->processInputMethodEvent(ev);
         }
     }
     if (!ev->isAccepted())
         QDeclarativePaintedItem::inputMethodEvent(ev);
     if (wasComposing != (d->control->preeditAreaText().length() > 0))
         emit inputMethodComposingChanged();
 }
inputMethodQuery()
QVariant QDeclarativeTextInput::inputMethodQuery (Qt::InputMethodQuery property) const virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Returns the value of the given property.
Reimplemented from QDeclarativeItem.
Definition at line 1513 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     switch(property) {
     case Qt::ImMicroFocus:
         return cursorRectangle();
     case Qt::ImFont:
         return font();
     case Qt::ImCursorPosition:
         return QVariant(d->control->cursor());
     case Qt::ImSurroundingText:
         if (d->control->echoMode() == PasswordEchoOnEdit && !d->control->passwordEchoEditing())
             return QVariant(displayText());
         else
             return QVariant(text());
     case Qt::ImCurrentSelection:
         return QVariant(selectedText());
     case Qt::ImMaximumTextLength:
         return QVariant(maxLength());
     case Qt::ImAnchorPosition:
         if (d->control->selectionStart() == d->control->selectionEnd())
             return QVariant(d->control->cursor());
         else if (d->control->selectionStart() == d->control->cursor())
             return QVariant(d->control->selectionEnd());
         else
             return QVariant(d->control->selectionStart());
     default:
         return QVariant();
     }
 }
isCursorVisible()
bool QDeclarativeTextInput::isCursorVisible () const
Definition at line 569 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     return d->cursorVisible;
 }
isInputMethodComposing()
bool QDeclarativeTextInput::isInputMethodComposing () const
Definition at line 2036 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     return d->control->preeditAreaText().length() > 0;
 }
isReadOnly()
bool QDeclarativeTextInput::isReadOnly () const
Definition at line 494 of file qdeclarativetextinput.cpp.
Referenced by drawContents(), focusInEvent(), mousePressEvent(), and mouseReleaseEvent().
 {
     Q_D(const QDeclarativeTextInput);
     return d->control->isReadOnly();
 }
isRightToLeft
bool QDeclarativeTextInput::isRightToLeft (int start, int end) slot
Definition at line 1582 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::determineHorizontalAlignment().
 {
     Q_D(QDeclarativeTextInput);
     if (start > end) {
         qmlInfo(this) << "isRightToLeft(start, end) called with the end property being smaller than the start.";
         return false;
     } else {
         return d->control->text().mid(start, end - start).isRightToLeft();
     }
 }
keyPressEvent()
void QDeclarativeTextInput::keyPressEvent (QKeyEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1192 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     keyPressPreHandler(ev);
     if (ev->isAccepted())
         return;
     // Don't allow MacOSX up/down support, and we don't allow a completer.
     bool ignore = (ev->key() == Qt::Key_Up || ev->key() == Qt::Key_Down) && ev->modifiers() == Qt::NoModifier;
     if (!ignore && (d->lastSelectionStart == d->lastSelectionEnd) && (ev->key() == Qt::Key_Right || ev->key() == Qt::Key_Left)) {
         // Ignore when moving off the end unless there is a selection,
         // because then moving will do something (deselect).
         int cursorPosition = d->control->cursor();
         if (cursorPosition == 0)
             ignore = ev->key() == (d->control->layoutDirection() == Qt::LeftToRight ? Qt::Key_Left : Qt::Key_Right);
         if (!ignore && cursorPosition == d->control->text().length())
             ignore = ev->key() == (d->control->layoutDirection() == Qt::LeftToRight ? Qt::Key_Right : Qt::Key_Left);
     }
     if (ignore) {
         ev->ignore();
     } else {
         d->control->processKeyEvent(ev);
     }
     if (!ev->isAccepted())
         QDeclarativePaintedItem::keyPressEvent(ev);
 }
maximumLengthChanged
void QDeclarativeTextInput::maximumLengthChanged (int maximumLength) signal
Referenced by setMaxLength().
maxLength()
int QDeclarativeTextInput::maxLength () const
Definition at line 523 of file qdeclarativetextinput.cpp.
Referenced by inputMethodQuery().
 {
     Q_D(const QDeclarativeTextInput);
     return d->control->maxLength();
 }
mouseDoubleClickEvent()
void QDeclarativeTextInput::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Reimplemented from QGraphicsItem.
Definition at line 1243 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->sendMouseEventToInputContext(event, QEvent::MouseButtonDblClick))
         return;
     if (d->selectByMouse) {
         int cursor = d->xToPos(event->pos().x());
         d->control->selectWordAtPos(cursor);
         event->setAccepted(true);
     } else {
         QDeclarativePaintedItem::mouseDoubleClickEvent(event);
     }
 }
mouseMoveEvent()
void QDeclarativeTextInput::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
If you do receive this event, you can be certain that this item also received a mouse press event, and that this item is the current mouse grabber.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseMoveEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 1287 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->sendMouseEventToInputContext(event, QEvent::MouseMove))
         return;
     if (d->selectPressed) {
         if (qAbs(int(event->pos().x() - d->pressPos.x())) > QApplication::startDragDistance())
             setKeepMouseGrab(true);
         moveCursorSelection(d->xToPos(event->pos().x()), d->mouseSelectionMode);
         event->setAccepted(true);
     } else {
         QDeclarativePaintedItem::mouseMoveEvent(event);
     }
 }
mousePressEvent()
void QDeclarativeTextInput::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
Mouse press events are only delivered to items that accept the mouse button that is pressed. By default, an item accepts all mouse buttons, but you can change this by calling setAcceptedMouseButtons().
The mouse press event decides which item should become the mouse grabber (see QGraphicsScene::mouseGrabberItem()). If you do not reimplement this function, the press event will propagate to any topmost item beneath this item, and no other mouse events will be delivered to this item.
If you do reimplement this function, event will by default be accepted (see QEvent::accept()), and this item is then the mouse grabber. This allows the item to receive future move, release and doubleclick events. If you call QEvent::ignore() on event, this item will lose the mouse grab, and event will propagate to any topmost item beneath. No further mouse events will be delivered to this item unless a new mouse press event is received.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mousePressEvent() in your reimplementation.
The event is for items that are neither QGraphicsItem::ItemIsMovable "movable" nor QGraphicsItem::ItemIsSelectable "selectable". mouseMoveEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 1257 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->sendMouseEventToInputContext(event, QEvent::MouseButtonPress))
         return;
     if(d->focusOnPress){
         bool hadActiveFocus = hasActiveFocus();
         forceActiveFocus();
         if (d->showInputPanelOnFocus) {
             if (hasActiveFocus() && hadActiveFocus && !isReadOnly()) {
                 // re-open input panel on press if already focused
                 openSoftwareInputPanel();
             }
         } else { // show input panel on click
             if (hasActiveFocus() && !hadActiveFocus) {
                 d->clickCausedFocus = true;
             }
         }
     }
     if (d->selectByMouse) {
         setKeepMouseGrab(false);
         d->selectPressed = true;
         d->pressPos = event->pos();
     }
     bool mark = (event->modifiers() & Qt::ShiftModifier) && d->selectByMouse;
     int cursor = d->xToPos(event->pos().x());
     d->control->moveCursor(cursor, mark);
     event->setAccepted(true);
 }
mouseReleaseEvent()
void QDeclarativeTextInput::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Handles the given mouse event.
Reimplemented from QGraphicsItem.
Definition at line 1306 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->sendMouseEventToInputContext(event, QEvent::MouseButtonRelease))
         return;
     if (d->selectPressed) {
         d->selectPressed = false;
         setKeepMouseGrab(false);
     }
     if (!d->showInputPanelOnFocus) { // input panel on click
         if (d->focusOnPress && !isReadOnly() && boundingRect().contains(event->pos())) {
             if (QGraphicsView * view = qobject_cast<QGraphicsView*>(qApp->focusWidget())) {
                 if (view->scene() && view->scene() == scene()) {
                     qt_widget_private(view)->handleSoftwareInputPanel(event->button(), d->clickCausedFocus);
                 }
             }
         }
     }
     d->clickCausedFocus = false;
     d->control->processEvent(event);
     if (!event->isAccepted())
         QDeclarativePaintedItem::mouseReleaseEvent(event);
 }
mouseSelectionMode()
SelectionMode QDeclarativeTextInput::mouseSelectionMode () const
Referenced by setSelectByMouse().
mouseSelectionModeChanged
void QDeclarativeTextInput::mouseSelectionModeChanged (SelectionMode mode) signal
Referenced by setMouseSelectionMode().
moveCursorSelection() [1/2]
void QDeclarativeTextInput::moveCursorSelection (int pos)
Definition at line 1797 of file qdeclarativetextinput.cpp.
Referenced by mouseMoveEvent().
 {
     Q_D(QDeclarativeTextInput);
     d->control->moveCursor(position, true);
 }
moveCursorSelection() [2/2]
void QDeclarativeTextInput::moveCursorSelection (int pos, SelectionMode mode)
Definition at line 1844 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (mode == SelectCharacters) {
         d->control->moveCursor(pos, true);
     } else if (pos != d->control->cursor()){
         const int cursor = d->control->cursor();
         int anchor;
         if (!d->control->hasSelectedText())
             anchor = d->control->cursor();
         else if (d->control->selectionStart() == d->control->cursor())
             anchor = d->control->selectionEnd();
         else
             anchor = d->control->selectionStart();
         if (anchor < pos || (anchor == pos && cursor < pos)) {
             const QString text = d->control->text();
             QTextBoundaryFinder finder(QTextBoundaryFinder::Word, text);
             finder.setPosition(anchor);
             const QTextBoundaryFinder::BoundaryReasons reasons = finder.boundaryReasons();
             if (anchor < text.length() && (!(reasons & QTextBoundaryFinder::StartWord)
                     || ((reasons & QTextBoundaryFinder::EndWord) && anchor > cursor))) {
                 finder.toPreviousBoundary();
             }
             anchor = finder.position() != -1 ? finder.position() : 0;
             finder.setPosition(pos);
             if (pos > 0 && !finder.boundaryReasons())
                 finder.toNextBoundary();
             const int cursor = finder.position() != -1 ? finder.position() : text.length();
             d->control->setSelection(anchor, cursor - anchor);
         } else if (anchor > pos || (anchor == pos && cursor > pos)) {
             const QString text = d->control->text();
             QTextBoundaryFinder finder(QTextBoundaryFinder::Word, text);
             finder.setPosition(anchor);
             const QTextBoundaryFinder::BoundaryReasons reasons = finder.boundaryReasons();
             if (anchor > 0 && (!(reasons & QTextBoundaryFinder::EndWord)
                     || ((reasons & QTextBoundaryFinder::StartWord) && anchor < cursor))) {
                 finder.toNextBoundary();
             }
             anchor = finder.position() != -1 ? finder.position() : text.length();
             finder.setPosition(pos);
             if (pos < text.length() && !finder.boundaryReasons())
                  finder.toPreviousBoundary();
             const int cursor = finder.position() != -1 ? finder.position() : 0;
             d->control->setSelection(anchor, cursor - anchor);
         }
     }
 }
openSoftwareInputPanel()
void QDeclarativeTextInput::openSoftwareInputPanel ()
Definition at line 1942 of file qdeclarativetextinput.cpp.
Referenced by focusInEvent(), and mousePressEvent().
 {
     QEvent event(QEvent::RequestSoftwareInputPanel);
     if (qApp) {
         if (QGraphicsView * view = qobject_cast<QGraphicsView*>(qApp->focusWidget())) {
             if (view->scene() && view->scene() == scene()) {
                 QApplication::sendEvent(view, &event);
             }
         }
     }
 }
passwordCharacter()
QString QDeclarativeTextInput::passwordCharacter () const
Referenced by selectWord().
passwordCharacterChanged
void QDeclarativeTextInput::passwordCharacterChanged () signal
Referenced by setPasswordCharacter().
paste
void QDeclarativeTextInput::paste () slot
Definition at line 1631 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if(!d->control->isReadOnly())
         d->control->paste();
 }
positionAt() [1/2]
int QDeclarativeTextInput::positionAt (int x) const
Definition at line 1139 of file qdeclarativetextinput.cpp.
 {
     return positionAt(x, CursorBetweenCharacters);
 }
positionAt() [2/2]
int QDeclarativeTextInput::positionAt (int x, CursorPosition position) const
Definition at line 1166 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     int pos = d->control->xToPos(x + d->hscroll, QTextLine::CursorPosition(position));
     const int cursor = d->control->cursor();
     if (pos > cursor) {
         const int preeditLength = d->control->preeditAreaText().length();
         pos = pos > cursor + preeditLength
                 ? pos - preeditLength
                 : cursor;
     }
     return pos;
 }
positionToRectangle()
QRectF QDeclarativeTextInput::positionToRectangle (int pos) const
Definition at line 1128 of file qdeclarativetextinput.cpp.
 {
     Q_D(const QDeclarativeTextInput);
     if (pos > d->control->cursorPosition())
         pos += d->control->preeditAreaText().length();
     return QRectF(d->control->cursorToX(pos)-d->hscroll,
         0.0,
         d->control->cursorWidth(),
         cursorRectangle().height());
 }
q_canPasteChanged
void QDeclarativeTextInput::q_canPasteChanged () private slot
Definition at line 2186 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::init().
 {
     Q_D(QDeclarativeTextInput);
     bool old = d->canPaste;
 #ifndef QT_NO_CLIPBOARD
     d->canPaste = !d->control->isReadOnly() && QApplication::clipboard()->text().length() != 0;
 #endif
     if(d->canPaste != old)
         emit canPasteChanged();
 }
q_textChanged
void QDeclarativeTextInput::q_textChanged () private slot
Definition at line 2134 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::init(), and setEchoMode().
 {
     Q_D(QDeclarativeTextInput);
     emit textChanged();
     emit displayTextChanged();
     updateSize();
     d->determineHorizontalAlignment();
     d->updateHorizontalScroll();
     updateMicroFocus();
     if(hasAcceptableInput() != d->oldValidity){
         d->oldValidity = hasAcceptableInput();
         emit acceptableInputChanged();
     }
 }
readOnlyChanged
void QDeclarativeTextInput::readOnlyChanged (bool isReadOnly) signal
Referenced by QDeclarativeTextInputPrivate::init(), and setReadOnly().
resetHAlign()
void QDeclarativeTextInput::resetHAlign ()
Definition at line 416 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     d->hAlignImplicit = true;
     if (d->determineHorizontalAlignment() && isComponentComplete()) {
         updateCursorRectangle();
     }
 }
sceneEvent()
bool QDeclarativeTextInput::sceneEvent (QEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1378 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     bool rv = QDeclarativeItem::sceneEvent(event);
     if (event->type() == QEvent::UngrabMouse) {
         d->selectPressed = false;
         setKeepMouseGrab(false);
     }
     return rv;
 }
select
void QDeclarativeTextInput::select (int start, int end) slot
Definition at line 679 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (start < 0 || end < 0 || start > d->control->text().length() || end > d->control->text().length())
         return;
     d->control->setSelection(start, end-start);
 }
selectAll
void QDeclarativeTextInput::selectAll () slot
Definition at line 1567 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     d->control->setSelection(0, d->control->text().length());
 }
selectByMouse()
bool QDeclarativeTextInput::selectByMouse () const
Referenced by setPasswordCharacter().
selectByMouseChanged
void QDeclarativeTextInput::selectByMouseChanged (bool selectByMouse) signal
Referenced by setSelectByMouse().
selectedText()
QString QDeclarativeTextInput::selectedText () const
Referenced by inputMethodQuery(), and select().
selectedTextChanged
void QDeclarativeTextInput::selectedTextChanged () signal
Referenced by selectionChanged().
selectedTextColor()
QColor QDeclarativeTextInput::selectedTextColor () const
Referenced by QDeclarativeTextInputPrivate::init(), and setSelectionColor().
selectedTextColorChanged
void QDeclarativeTextInput::selectedTextColorChanged (const QColor & color) signal
Referenced by setSelectedTextColor().
selectionChanged
void QDeclarativeTextInput::selectionChanged () private slot
Definition at line 2114 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::init().
 {
     Q_D(QDeclarativeTextInput);
     updateRect();//TODO: Only update rect in selection
     emit selectedTextChanged();
     if(d->lastSelectionStart != d->control->selectionStart()){
         d->lastSelectionStart = d->control->selectionStart();
         if(d->lastSelectionStart == -1)
             d->lastSelectionStart = d->control->cursor();
         emit selectionStartChanged();
     }
     if(d->lastSelectionEnd != d->control->selectionEnd()){
         d->lastSelectionEnd = d->control->selectionEnd();
         if(d->lastSelectionEnd == -1)
             d->lastSelectionEnd = d->control->cursor();
         emit selectionEndChanged();
     }
 }
selectionColor()
QColor QDeclarativeTextInput::selectionColor () const
Referenced by QDeclarativeTextInputPrivate::init(), and setColor().
selectionColorChanged
void QDeclarativeTextInput::selectionColorChanged (const QColor & color) signal
Referenced by setSelectionColor().
selectionEnd()
int QDeclarativeTextInput::selectionEnd () const
Referenced by setCursorPosition().
selectionEndChanged
void QDeclarativeTextInput::selectionEndChanged () signal
Referenced by cursorPosChanged(), and selectionChanged().
selectionStart()
int QDeclarativeTextInput::selectionStart () const
Referenced by setCursorPosition().
selectionStartChanged
void QDeclarativeTextInput::selectionStartChanged () signal
Referenced by cursorPosChanged(), and selectionChanged().
selectWord
void QDeclarativeTextInput::selectWord () slot
Definition at line 1647 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     d->control->selectWordAtPos(d->control->cursor());
 }
setAutoScroll()
void QDeclarativeTextInput::setAutoScroll (bool b)
Definition at line 751 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->autoScroll == b)
         return;
     d->autoScroll = b;
     //We need to repaint so that the scrolling is taking into account.
     updateSize(true);
     updateCursorRectangle();
     emit autoScrollChanged(d->autoScroll);
 }
setColor()
void QDeclarativeTextInput::setColor (const QColor & c)
Definition at line 301 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (c != d->color) {
         d->color = c;
         clearCache();
         update();
         emit colorChanged(c);
     }
 }
setCursorDelegate()
void QDeclarativeTextInput::setCursorDelegate (QDeclarativeComponent * c)
Definition at line 1061 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->cursorComponent == c)
         return;
     d->cursorComponent = c;
     if(!c){
         //note that the components are owned by something else
         delete d->cursorItem;
     }else{
         d->startCreatingCursor();
     }
     emit cursorDelegateChanged();
 }
setCursorPosition()
void QDeclarativeTextInput::setCursorPosition (int cp)
Definition at line 602 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (cp < 0 || cp > d->control->text().length())
         return;
     d->control->moveCursor(cp);
 }
setCursorVisible()
void QDeclarativeTextInput::setCursorVisible (bool on)
Definition at line 575 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->cursorVisible == on)
         return;
     d->cursorVisible = on;
     d->control->setCursorBlinkPeriod(on?QApplication::cursorFlashTime():0);
     QRect r = d->control->cursorRect();
     if (d->control->inputMask().isEmpty())
         updateRect(r);
     else
         updateRect();
     emit cursorVisibleChanged(d->cursorVisible);
 }
setEchoMode()
void QDeclarativeTextInput::setEchoMode (QDeclarativeTextInput::EchoMode echo)
Definition at line 1013 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (echoMode() == echo)
         return;
     d->control->setEchoMode((uint)echo);
     d->updateInputMethodHints();
     q_textChanged();
     emit echoModeChanged(echoMode());
 }
setFocusOnPress()
void QDeclarativeTextInput::setFocusOnPress (bool b)
Definition at line 725 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->focusOnPress == b)
         return;
     d->focusOnPress = b;
     emit activeFocusOnPressChanged(d->focusOnPress);
 }
setFont()
void QDeclarativeTextInput::setFont (const QFont & font)
Definition at line 261 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->sourceFont == font)
         return;
     d->sourceFont = font;
     QFont oldFont = d->font;
     d->font = font;
     if (d->font.pointSizeF() != -1) {
         // 0.5pt resolution
         qreal size = qRound(d->font.pointSizeF()*2.0);
         d->font.setPointSizeF(size/2.0);
     }
     if (oldFont != d->font) {
         d->control->setFont(d->font);
         updateSize();
         updateCursorRectangle();
         if(d->cursorItem){
             d->cursorItem->setHeight(QFontMetrics(d->font).height());
         }
     }
     emit fontChanged(d->sourceFont);
 }
setHAlign()
void QDeclarativeTextInput::setHAlign (HAlignment align)
Definition at line 406 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::determineHorizontalAlignment().
 {
     Q_D(QDeclarativeTextInput);
     bool forceAlign = d->hAlignImplicit && d->effectiveLayoutMirror;
     d->hAlignImplicit = false;
     if (d->setHAlign(align, forceAlign) && isComponentComplete()) {
         updateCursorRectangle();
     }
 }
setIMHints()
void QDeclarativeTextInput::setIMHints (Qt::InputMethodHints hints)
Definition at line 1030 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->inputMethodHints == hints)
         return;
     d->inputMethodHints = hints;
     d->updateInputMethodHints();
 }
setInputMask()
void QDeclarativeTextInput::setInputMask (const QString & im)
Definition at line 939 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->control->inputMask() == im)
         return;
     d->control->setInputMask(im);
     emit inputMaskChanged(d->control->inputMask());
 }
setMaxLength()
void QDeclarativeTextInput::setMaxLength (int ml)
Definition at line 529 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->control->maxLength() == ml)
         return;
     d->control->setMaxLength(ml);
     emit maximumLengthChanged(ml);
 }
setMouseSelectionMode()
void QDeclarativeTextInput::setMouseSelectionMode (SelectionMode mode)
Definition at line 1772 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->mouseSelectionMode != mode) {
         d->mouseSelectionMode = mode;
         emit mouseSelectionModeChanged(mode);
     }
 }
setPasswordCharacter()
void QDeclarativeTextInput::setPasswordCharacter (const QString & str)
Definition at line 1689 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if(str.length() < 1)
         return;
     d->control->setPasswordCharacter(str.constData()[0]);
     EchoMode echoMode_ = echoMode();
     if (echoMode_ == Password || echoMode_ == PasswordEchoOnEdit) {
         updateSize();
     }
     emit passwordCharacterChanged();
 }
setReadOnly()
void QDeclarativeTextInput::setReadOnly (bool ro)
Definition at line 500 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->control->isReadOnly() == ro)
         return;
     setFlag(QGraphicsItem::ItemAcceptsInputMethod, !ro);
     d->control->setReadOnly(ro);
     emit readOnlyChanged(ro);
 }
setSelectByMouse()
void QDeclarativeTextInput::setSelectByMouse (bool on)
Definition at line 1740 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->selectByMouse != on) {
         d->selectByMouse = on;
         emit selectByMouseChanged(on);
     }
 }
setSelectedTextColor()
void QDeclarativeTextInput::setSelectedTextColor (const QColor & c)
Definition at line 358 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->selectedTextColor == color)
         return;
     d->selectedTextColor = color;
     QPalette p = d->control->palette();
     p.setColor(QPalette::HighlightedText, d->selectedTextColor);
     d->control->setPalette(p);
     if (d->control->hasSelectedText()) {
         clearCache();
         update();
     }
     emit selectedTextColorChanged(color);
 }
setSelectionColor()
void QDeclarativeTextInput::setSelectionColor (const QColor & c)
Definition at line 327 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->selectionColor == color)
         return;
     d->selectionColor = color;
     QPalette p = d->control->palette();
     p.setColor(QPalette::Highlight, d->selectionColor);
     d->control->setPalette(p);
     if (d->control->hasSelectedText()) {
         clearCache();
         update();
     }
     emit selectionColorChanged(color);
 }
setText()
void QDeclarativeTextInput::setText (const QString & s)
Definition at line 109 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if(s == text())
         return;
     d->control->setText(s);
 }
setValidator()
void QDeclarativeTextInput::setValidator (QValidator * v)
Definition at line 905 of file qdeclarativetextinput.cpp.
 {
     Q_D(QDeclarativeTextInput);
     if (d->control->validator() == v)
         return;
     d->control->setValidator(v);
     if(!d->control->hasAcceptableInput()){
         d->oldValidity = false;
         emit acceptableInputChanged();
     }
     emit validatorChanged();
 }
text()
QString QDeclarativeTextInput::text () const
Referenced by QDeclarativeTextInputPrivate::determineHorizontalAlignment(), inputMethodQuery(), moveCursorSelection(), setText(), and ~QDeclarativeTextInput().
textChanged
void QDeclarativeTextInput::textChanged () signal
Referenced by QDeclarativeTextInputPrivate::init(), and q_textChanged().
updateCursorRectangle
void QDeclarativeTextInput::updateCursorRectangle () private slot
Definition at line 2102 of file qdeclarativetextinput.cpp.
Referenced by cursorPosChanged(), geometryChanged(), QDeclarativeTextInputPrivate::init(), resetHAlign(), setAutoScroll(), setFont(), and setHAlign().
 {
     Q_D(QDeclarativeTextInput);
     d->determineHorizontalAlignment();
     d->updateHorizontalScroll();
     updateRect();//TODO: Only update rect between pos's
     updateMicroFocus();
     emit cursorRectangleChanged();
     if (d->cursorItem)
         d->cursorItem->setX(d->control->cursorToX() - d->hscroll);
 }
updateRect
void QDeclarativeTextInput::updateRect (const QRect & r = QRect()) private slot
Definition at line 2149 of file qdeclarativetextinput.cpp.
Referenced by QDeclarativeTextInputPrivate::init(), selectionChanged(), setCursorVisible(), and updateCursorRectangle().
 {
     Q_D(QDeclarativeTextInput);
     if(r == QRect())
         clearCache();
     else
         dirtyCache(QRect(r.x() - d->hscroll, r.y(), r.width(), r.height()));
     update();
 }
updateSize
void QDeclarativeTextInput::updateSize (bool needsRedraw = true) private slot
Definition at line 2172 of file qdeclarativetextinput.cpp.
Referenced by geometryChanged(), q_textChanged(), setAutoScroll(), setFont(), and setPasswordCharacter().
 {
     Q_D(QDeclarativeTextInput);
     int w = width();
     int h = height();
     setImplicitHeight(d->control->height()-1); // -1 to counter QLineControl's +1 which is not consistent with Text.
     setImplicitWidth(d->calculateTextWidth());
     setContentsSize(QSize(width(), height()));//Repaints if changed
     if(w==width() && h==height() && needsRedraw){
         clearCache();
         update();
     }
 }
validator()
QValidator* QDeclarativeTextInput::validator () const
Referenced by setAutoScroll().
validatorChanged
void QDeclarativeTextInput::validatorChanged () signal
Referenced by setValidator().
Properties
acceptableInput
bool QDeclarativeTextInput::acceptableInput private
Definition at line 90 of file qdeclarativetextinput_p.h.
activeFocusOnPress
bool QDeclarativeTextInput::activeFocusOnPress private
Definition at line 92 of file qdeclarativetextinput_p.h.
autoScroll
bool QDeclarativeTextInput::autoScroll private
Definition at line 95 of file qdeclarativetextinput_p.h.
canPaste
bool QDeclarativeTextInput::canPaste private
Definition at line 98 of file qdeclarativetextinput_p.h.
color
QColor QDeclarativeTextInput::color private
Definition at line 69 of file qdeclarativetextinput_p.h.
cursorDelegate
QDeclarativeComponent * QDeclarativeTextInput::cursorDelegate private
Definition at line 78 of file qdeclarativetextinput_p.h.
cursorPosition
int QDeclarativeTextInput::cursorPosition private
Definition at line 76 of file qdeclarativetextinput_p.h.
cursorRectangle
QRect QDeclarativeTextInput::cursorRectangle private
Returns a Rect which encompasses the cursor, but which may be larger than is required.
Ignores custom cursor delegates.
Definition at line 77 of file qdeclarativetextinput_p.h.
cursorVisible
bool QDeclarativeTextInput::cursorVisible private
Definition at line 75 of file qdeclarativetextinput_p.h.
displayText
QString QDeclarativeTextInput::displayText private
Definition at line 94 of file qdeclarativetextinput_p.h.
echoMode
QDeclarativeTextInput::EchoMode QDeclarativeTextInput::echoMode private
Definition at line 91 of file qdeclarativetextinput_p.h.
font
QFont QDeclarativeTextInput::font private
Definition at line 72 of file qdeclarativetextinput_p.h.
horizontalAlignment
HAlignment QDeclarativeTextInput::horizontalAlignment private
Definition at line 73 of file qdeclarativetextinput_p.h.
inputMask
QString QDeclarativeTextInput::inputMask private
Definition at line 87 of file qdeclarativetextinput_p.h.
inputMethodComposing
bool QDeclarativeTextInput::inputMethodComposing private
Definition at line 99 of file qdeclarativetextinput_p.h.
inputMethodHints
Qt::InputMethodHints QDeclarativeTextInput::inputMethodHints private
Definition at line 88 of file qdeclarativetextinput_p.h.
maximumLength
int QDeclarativeTextInput::maximumLength private
Definition at line 83 of file qdeclarativetextinput_p.h.
mouseSelectionMode
QDeclarativeTextInput::SelectionMode QDeclarativeTextInput::mouseSelectionMode private
Definition at line 97 of file qdeclarativetextinput_p.h.
passwordCharacter
QString QDeclarativeTextInput::passwordCharacter private
Definition at line 93 of file qdeclarativetextinput_p.h.
readOnly
bool QDeclarativeTextInput::readOnly private
Definition at line 74 of file qdeclarativetextinput_p.h.
selectByMouse
bool QDeclarativeTextInput::selectByMouse private
Definition at line 96 of file qdeclarativetextinput_p.h.
selectedText
QString QDeclarativeTextInput::selectedText private
Definition at line 81 of file qdeclarativetextinput_p.h.
selectedTextColor
QColor QDeclarativeTextInput::selectedTextColor private
Definition at line 71 of file qdeclarativetextinput_p.h.
selectionColor
QColor QDeclarativeTextInput::selectionColor private
Definition at line 70 of file qdeclarativetextinput_p.h.
selectionEnd
int QDeclarativeTextInput::selectionEnd private
Definition at line 80 of file qdeclarativetextinput_p.h.
selectionStart
int QDeclarativeTextInput::selectionStart private
Definition at line 79 of file qdeclarativetextinput_p.h.
text
QString QDeclarativeTextInput::text private
Definition at line 68 of file qdeclarativetextinput_p.h.
validator
QValidator * QDeclarativeTextInput::validator private
Definition at line 85 of file qdeclarativetextinput_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativetextinput_p.h
/src/declarative/graphicsitems/qdeclarativetextinput.cpp