Qt 4.8: QDirectFBPixmapData Class Reference
QDirectFBPixmapData Class Reference
#include <qdirectfbpixmap.h>
Public Functions
virtual QImage * buffer ()
virtual void copy (const QPixmapData *data, const QRect &rect)
virtual void fill (const QColor &color)
virtual bool fromData (const uchar *buffer, uint len, const char *format, Qt::ImageConversionFlags flags)
virtual bool fromFile (const QString &filename, const char *format, Qt::ImageConversionFlags flags)
virtual void fromImage (const QImage &image, Qt::ImageConversionFlags flags)
bool hasAlphaChannel () const
virtual int metric (QPaintDevice::PaintDeviceMetric m) const
virtual QPaintEngine * paintEngine () const
QImage::Format pixelFormat () const
QDirectFBPixmapData (QDirectFBScreen *screen, PixelType pixelType)
virtual void resize (int width, int height)
virtual bool scroll (int dx, int dy, const QRect &rect)
virtual QImage toImage () const
virtual QPixmap transformed (const QTransform &matrix, Qt::TransformationMode mode) const
~QDirectFBPixmapData ()
Public Functions inherited from QPixmapData
virtual QPixmap alphaChannel () const
qint64 cacheKey () const
ClassId classId () const
int colorCount () const
virtual QPixmapData * createCompatiblePixmapData () const
int depth () const
virtual void fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags)
int height () const
bool isNull () const
virtual QBitmap mask () const
QT_DEPRECATED int numColors () const
PixelType pixelType () const
QPixmapData (PixelType pixelType, int classId)
virtual QPixmapData * runtimeData () const
int serialNumber () const
virtual void setAlphaChannel (const QPixmap &alphaChannel)
virtual void setMask (const QBitmap &mask)
virtual QImage toImage (const QRect &rect) const
int width () const
virtual ~QPixmapData ()
Public Functions inherited from QDirectFBPaintDevice
int bytesPerLine () const
Returns the number of bytes per line in the framebuffer.
virtual IDirectFBSurface * directFBSurface () const
QImage::Format format () const
Returns the format of the device's memory buffet.
DFBSurfaceLockFlags lockFlags () const
bool lockSurface (DFBSurfaceLockFlags lockFlags)
void * memory () const
Returns a pointer to the paint device's memory buffer, or 0 if no such buffer exists.
QSize size () const
void unlockSurface ()
~QDirectFBPaintDevice ()
Public Functions inherited from QCustomRasterPaintDevice
int devType () const
QCustomRasterPaintDevice (QWidget *w)
Constructs a custom raster based paint device for the given top-level widget.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static bool hasAlphaChannel (const QImage &img, Qt::ImageConversionFlags flags=Qt::AutoColor)
Static Public Functions inherited from QPixmapData
static QPixmapData * create (int w, int h, PixelType type)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Private Functions
bool fromDataBufferDescription (const DFBDataBufferDescription &dataBuffer)
void invalidate ()
Properties
bool alpha
Additional Inherited Members
Public Types inherited from QPixmapData
enum ClassId {
RasterClass, X11Class, MacClass, DirectFBClass,
OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
CustomClass = 1024
}
enum PixelType { PixmapType, BitmapType }
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Protected Functions inherited from QPixmapData
void setSerialNumber (int serNo)
Protected Functions inherited from QDirectFBPaintDevice
int dotsPerMeterX () const
int dotsPerMeterY () const
QDirectFBPaintDevice (QDirectFBScreen *scr)
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables inherited from QPixmapData
int d
int h
bool is_null
int w
Protected Variables inherited from QDirectFBPaintDevice
int bpl
IDirectFBSurface * dfbSurface
QDirectFBPaintEngine * engine
QImage::Format imageFormat
QImage lockedImage
DFBSurfaceLockFlags lockFlgs
uchar * mem
QDirectFBScreen * screen
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 62 of file qdirectfbpixmap.h.
Constructors and Destructors
QDirectFBPixmapData()
QDirectFBPixmapData::QDirectFBPixmapData (QDirectFBScreen * screen, PixelType pixelType)
Definition at line 58 of file qdirectfbpixmap.cpp.
Referenced by transformed().
     : QPixmapData(pixelType, DirectFBClass), QDirectFBPaintDevice(screen),
       alpha(false)
 {
     setSerialNumber(0);
 }
~QDirectFBPixmapData()
QDirectFBPixmapData::~QDirectFBPixmapData ()
Definition at line 65 of file qdirectfbpixmap.cpp.
 {
 }
Functions
buffer()
QImage * QDirectFBPixmapData::buffer () virtual
Reimplemented from QPixmapData.
Definition at line 526 of file qdirectfbpixmap.cpp.
Referenced by fromData(), toImage(), and transformed().
 {
     if (!lockFlgs) {
         lockSurface(DSLF_READ|DSLF_WRITE);
     }
     Q_ASSERT(lockFlgs);
     Q_ASSERT(!lockedImage.isNull());
     return &lockedImage;
 }
copy()
void QDirectFBPixmapData::copy (const QPixmapData * data, const QRect & rect) virtual
Reimplemented from QPixmapData.
Definition at line 332 of file qdirectfbpixmap.cpp.
 {
     if (data->classId() != DirectFBClass) {
         QPixmapData::copy(data, rect);
         return;
     }
     const QDirectFBPixmapData *otherData = static_cast<const QDirectFBPixmapData*>(data);
 #ifdef QT_NO_DIRECTFB_SUBSURFACE
     if (otherData->lockFlags()) {
         const_cast<QDirectFBPixmapData*>(otherData)->unlockSurface();
     }
 #endif
     IDirectFBSurface *src = otherData->directFBSurface();
     alpha = data->hasAlphaChannel();
     imageFormat = (alpha
                    ? QDirectFBScreen::instance()->alphaPixmapFormat()
                    : QDirectFBScreen::instance()->pixelFormat());
     dfbSurface = screen->createDFBSurface(rect.size(), imageFormat,
                                           QDirectFBScreen::TrackSurface);
     if (!dfbSurface) {
         qWarning("QDirectFBPixmapData::copy()");
         invalidate();
         return;
     }
     if (alpha) {
         dfbSurface->Clear(dfbSurface, 0, 0, 0, 0);
         dfbSurface->SetBlittingFlags(dfbSurface, DSBLIT_BLEND_ALPHACHANNEL);
     } else {
         dfbSurface->SetBlittingFlags(dfbSurface, DSBLIT_NOFX);
     }
     const DFBRectangle blitRect = { rect.x(), rect.y(),
                                     rect.width(), rect.height() };
     w = rect.width();
     h = rect.height();
     d = otherData->d;
     is_null = (w <= 0 || h <= 0);
     unlockSurface();
     DFBResult result = dfbSurface->Blit(dfbSurface, src, &blitRect, 0, 0);
 #if (Q_DIRECTFB_VERSION >= 0x010000)
     dfbSurface->ReleaseSource(dfbSurface);
 #endif
     if (result != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::copy()", result);
         invalidate();
         return;
     }
     setSerialNumber(++global_ser_no);
 }
fill()
void QDirectFBPixmapData::fill (const QColor & color) virtual
Implements QPixmapData.
Definition at line 402 of file qdirectfbpixmap.cpp.
 {
     if (!serialNumber())
         return;
     Q_ASSERT(dfbSurface);
     alpha |= (color.alpha() < 255);
     if (alpha && isOpaqueFormat(imageFormat)) {
         QSize size;
         dfbSurface->GetSize(dfbSurface, &size.rwidth(), &size.rheight());
         screen->releaseDFBSurface(dfbSurface);
         imageFormat = screen->alphaPixmapFormat();
         d = QDirectFBScreen::depth(imageFormat);
         dfbSurface = screen->createDFBSurface(size, screen->alphaPixmapFormat(), QDirectFBScreen::TrackSurface);
         setSerialNumber(++global_ser_no);
         if (!dfbSurface) {
             qWarning("QDirectFBPixmapData::fill()");
             invalidate();
             return;
         }
     }
     dfbSurface->Clear(dfbSurface, color.red(), color.green(), color.blue(), color.alpha());
 }
fromData()
bool QDirectFBPixmapData::fromData (const uchar * buffer, uint len, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 206 of file qdirectfbpixmap.cpp.
Referenced by fromFile().
 {
     if (flags == Qt::AutoColor) {
         DFBDataBufferDescription description;
         description.flags = DBDESC_MEMORY;
         description.memory.data = buffer;
         description.memory.length = len;
         if (fromDataBufferDescription(description))
             return true;
         // fall back to Qt
     }
     return QPixmapData::fromData(buffer, len, format, flags);
 }
fromDataBufferDescription()
bool QDirectFBPixmapData::fromDataBufferDescription (const DFBDataBufferDescription & dataBuffer) private
Definition at line 235 of file qdirectfbpixmap.cpp.
Referenced by fromData(), fromFile(), and hasAlphaChannel().
 {
     IDirectFB *dfb = screen->dfb();
     Q_ASSERT(dfb);
     DFBResult result = DFB_OK;
     IDirectFBDataBuffer *dataBufferPtr;
     if ((result = dfb->CreateDataBuffer(dfb, &dataBufferDescription, &dataBufferPtr)) != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::fromDataBufferDescription()", result);
         return false;
     }
     QDirectFBPointer<IDirectFBDataBuffer> dataBuffer(dataBufferPtr);
     IDirectFBImageProvider *providerPtr;
     if ((result = dataBuffer->CreateImageProvider(dataBuffer.data(), &providerPtr)) != DFB_OK)
         return false;
     QDirectFBPointer<IDirectFBImageProvider> provider(providerPtr);
     DFBImageDescription imageDescription;
     result = provider->GetImageDescription(provider.data(), &imageDescription);
     if (result != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::fromSurfaceDescription(): Can't get image description", result);
         return false;
     }
     if (imageDescription.caps & DICAPS_COLORKEY) {
         return false;
     }
     DFBSurfaceDescription surfaceDescription;
     if ((result = provider->GetSurfaceDescription(provider.data(), &surfaceDescription)) != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::fromDataBufferDescription(): Can't get surface description", result);
         return false;
     }
     alpha = imageDescription.caps & DICAPS_ALPHACHANNEL;
     imageFormat = alpha ? screen->alphaPixmapFormat() : screen->pixelFormat();
     dfbSurface = screen->createDFBSurface(QSize(surfaceDescription.width, surfaceDescription.height),
                                           imageFormat, QDirectFBScreen::TrackSurface);
     result = provider->RenderTo(provider.data(), dfbSurface, 0);
     if (result != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::fromSurfaceDescription(): Can't render to surface", result);
         return false;
     }
     w = surfaceDescription.width;
     h = surfaceDescription.height;
     is_null = (w <= 0 || h <= 0);
     d = QDirectFBScreen::depth(imageFormat);
     setSerialNumber(++global_ser_no);
 #if defined QT_DIRECTFB_IMAGEPROVIDER_KEEPALIVE
     screen->setDirectFBImageProvider(providerPtr);
     provider.take();
 #endif
     return true;
 }
fromFile()
bool QDirectFBPixmapData::fromFile (const QString & filename, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 179 of file qdirectfbpixmap.cpp.
 {
     if (!QFile::exists(filename))
         return false;
     if (flags == Qt::AutoColor) {
         if (filename.startsWith(QLatin1Char(':'))) { // resource
             QFile file(filename);
             if (!file.open(QIODevice::ReadOnly))
                 return false;
             const QByteArray data = file.readAll();
             file.close();
             return fromData(reinterpret_cast<const uchar*>(data.constData()), data.size(), format, flags);
         } else {
             DFBDataBufferDescription description;
             description.flags = DBDESC_FILE;
             const QByteArray fileNameData = filename.toLocal8Bit();
             description.file = fileNameData.constData();
             if (fromDataBufferDescription(description)) {
                 return true;
             }
             // fall back to Qt
         }
     }
     return QPixmapData::fromFile(filename, format, flags);
 }
fromImage()
void QDirectFBPixmapData::fromImage (const QImage & image, Qt::ImageConversionFlags flags) virtual
Implements QPixmapData.
Definition at line 298 of file qdirectfbpixmap.cpp.
Referenced by transformed().
 {
     alpha = QDirectFBPixmapData::hasAlphaChannel(img, flags);
     imageFormat = alpha ? screen->alphaPixmapFormat() : screen->pixelFormat();
     QImage image;
     if ((flags & ~Qt::NoOpaqueDetection) != Qt::AutoColor) {
         image = img.convertToFormat(imageFormat, flags);
         flags = Qt::AutoColor;
     } else if (img.format() == QImage::Format_RGB32 || img.depth() == 1) {
         image = img.convertToFormat(imageFormat, flags);
     } else if (img.format() != imageFormat) {
         image = img.convertToFormat(imageFormat, flags);
     } else {
         image = img;
     }
     dfbSurface = screen->createDFBSurface(image, image.format(), QDirectFBScreen::NoPreallocated | QDirectFBScreen::TrackSurface);
     if (!dfbSurface) {
         qWarning("QDirectFBPixmapData::fromImage()");
         invalidate();
         return;
     }
     w = image.width();
     h = image.height();
     is_null = (w <= 0 || h <= 0);
     d = QDirectFBScreen::depth(imageFormat);
     setSerialNumber(++global_ser_no);
 #ifdef QT_NO_DIRECTFB_OPAQUE_DETECTION
     Q_UNUSED(flags);
 #endif
 }
hasAlphaChannel() [1/2]
bool QDirectFBPixmapData::hasAlphaChannel () const inline virtual
Implements QPixmapData.
Definition at line 89 of file qdirectfbpixmap.h.
Referenced by QDirectFBScreen::createDFBSurface(), fromImage(), QDirectFBPaintEnginePrivate::getSurface(), and toImage().
 { return alpha; }
hasAlphaChannel() [2/2]
bool QDirectFBPixmapData::hasAlphaChannel (const QImage & img, Qt::ImageConversionFlags flags = Qt::AutoColor) static
Definition at line 166 of file qdirectfbpixmap.cpp.
 {
     if (img.depth() == 1)
         return true;
 #ifdef QT_DIRECTFB_OPAQUE_DETECTION
     return ((flags & Qt::NoOpaqueDetection) ? img.hasAlphaChannel() : checkForAlphaPixels(img));
 #else
     Q_UNUSED(flags);
     return img.hasAlphaChannel();
 #endif
 }
invalidate()
void QDirectFBPixmapData::invalidate () private
Definition at line 564 of file qdirectfbpixmap.cpp.
Referenced by copy(), fill(), fromImage(), hasAlphaChannel(), and resize().
 {
     if (dfbSurface) {
         screen->releaseDFBSurface(dfbSurface);
         dfbSurface = 0;
     }
     setSerialNumber(0);
     alpha = false;
     d = w = h = 0;
     is_null = true;
     imageFormat = QImage::Format_Invalid;
 }
metric()
virtual int QDirectFBPixmapData::metric (QPaintDevice::PaintDeviceMetric m) const inline virtual
Implements QPixmapData.
Definition at line 86 of file qdirectfbpixmap.h.
 { return QDirectFBPaintDevice::metric(m); }
paintEngine()
QPaintEngine * QDirectFBPixmapData::paintEngine () const virtual
Implements QPixmapData.
Definition at line 515 of file qdirectfbpixmap.cpp.
 {
     if (!engine) {
         // QDirectFBPixmapData is also a QCustomRasterPaintDevice, so pass
         // that to the paint engine:
         QDirectFBPixmapData *that = const_cast<QDirectFBPixmapData*>(this);
         that->engine = new QDirectFBPaintEngine(that);
     }
     return engine;
 }
pixelFormat()
QImage::Format QDirectFBPixmapData::pixelFormat () const inline
Definition at line 88 of file qdirectfbpixmap.h.
 { return imageFormat; }
resize()
void QDirectFBPixmapData::resize (int width, int height) virtual
Implements QPixmapData.
Definition at line 69 of file qdirectfbpixmap.cpp.
 {
     if (width <= 0 || height <= 0) {
         invalidate();
         return;
     }
     imageFormat = screen->pixelFormat();
     dfbSurface = screen->createDFBSurface(QSize(width, height),
                                           imageFormat,
                                           QDirectFBScreen::TrackSurface);
     d = QDirectFBScreen::depth(imageFormat);
     alpha = false;
     if (!dfbSurface) {
         invalidate();
         qWarning("QDirectFBPixmapData::resize(): Unable to allocate surface");
         return;
     }
     w = width;
     h = height;
     is_null = (w <= 0 || h <= 0);
     setSerialNumber(++global_ser_no);
 }
scroll()
bool QDirectFBPixmapData::scroll (int dx, int dy, const QRect & rect) virtual
Reimplemented from QPixmapData.
Definition at line 537 of file qdirectfbpixmap.cpp.
 {
     if (!dfbSurface) {
         return false;
     }
     unlockSurface();
     DFBResult result = dfbSurface->SetBlittingFlags(dfbSurface, DSBLIT_NOFX);
     if (result != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::scroll", result);
         return false;
     }
     result = dfbSurface->SetPorterDuff(dfbSurface, DSPD_NONE);
     if (result != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::scroll", result);
         return false;
     }
     const DFBRectangle source = { rect.x(), rect.y(), rect.width(), rect.height() };
     result = dfbSurface->Blit(dfbSurface, dfbSurface, &source, source.x + dx, source.y + dy);
     if (result != DFB_OK) {
         DirectFBError("QDirectFBPixmapData::scroll", result);
         return false;
     }
     return true;
 }
toImage()
QImage QDirectFBPixmapData::toImage () const virtual
Implements QPixmapData.
Definition at line 480 of file qdirectfbpixmap.cpp.
 {
     if (!dfbSurface)
         return QImage();
 #if 0
     // In later versions of DirectFB one can set a flag to tell
     // DirectFB not to move the surface to videomemory. When that
     // happens we can use this (hopefully faster) codepath
 #ifndef QT_NO_DIRECTFB_PREALLOCATED
     QImage ret(w, h, QDirectFBScreen::getImageFormat(dfbSurface));
     if (IDirectFBSurface *imgSurface = screen->createDFBSurface(ret, QDirectFBScreen::DontTrackSurface)) {
         if (hasAlphaChannel()) {
             imgSurface->SetBlittingFlags(imgSurface, DSBLIT_BLEND_ALPHACHANNEL);
             imgSurface->Clear(imgSurface, 0, 0, 0, 0);
         } else {
             imgSurface->SetBlittingFlags(imgSurface, DSBLIT_NOFX);
         }
         imgSurface->Blit(imgSurface, dfbSurface, 0, 0, 0);
 #if (Q_DIRECTFB_VERSION >= 0x010000)
         imgSurface->ReleaseSource(imgSurface);
 #endif
         imgSurface->Release(imgSurface);
         return ret;
     }
 #endif
 #endif
     QDirectFBPixmapData *that = const_cast<QDirectFBPixmapData*>(this);
     const QImage *img = that->buffer();
     return img->copy();
 }
transformed()
QPixmap QDirectFBPixmapData::transformed (const QTransform & matrix, Qt::TransformationMode mode) const virtual
Reimplemented from QPixmapData.
Definition at line 429 of file qdirectfbpixmap.cpp.
 {
     QDirectFBPixmapData *that = const_cast<QDirectFBPixmapData*>(this);
 #ifdef QT_NO_DIRECTFB_SUBSURFACE
     if (lockFlags())
         that->unlockSurface();
 #endif
     if (!dfbSurface || transform.type() != QTransform::TxScale
         || mode != Qt::FastTransformation)
     {
         const QImage *image = that->buffer();
         Q_ASSERT(image);
         const QImage transformed = image->transformed(transform, mode);
         QDirectFBPixmapData *data = new QDirectFBPixmapData(screen, QPixmapData::PixmapType);
         data->fromImage(transformed, Qt::AutoColor);
         return QPixmap(data);
     }
     const QSize size = transform.mapRect(QRect(0, 0, w, h)).size();
     if (size.isEmpty())
         return QPixmap();
     QDirectFBPixmapData *data = new QDirectFBPixmapData(screen, QPixmapData::PixmapType);
     data->setSerialNumber(++global_ser_no);
     DFBSurfaceBlittingFlags flags = DSBLIT_NOFX;
     data->alpha = alpha;
     if (alpha) {
         flags = DSBLIT_BLEND_ALPHACHANNEL;
     }
     data->dfbSurface = screen->createDFBSurface(size,
                                                 imageFormat,
                                                 QDirectFBScreen::TrackSurface);
     if (flags & DSBLIT_BLEND_ALPHACHANNEL) {
         data->dfbSurface->Clear(data->dfbSurface, 0, 0, 0, 0);
     }
     data->dfbSurface->SetBlittingFlags(data->dfbSurface, flags);
     const DFBRectangle destRect = { 0, 0, size.width(), size.height() };
     data->dfbSurface->StretchBlit(data->dfbSurface, dfbSurface, 0, &destRect);
     data->w = size.width();
     data->h = size.height();
     data->is_null = (data->w <= 0 || data->h <= 0);
 #if (Q_DIRECTFB_VERSION >= 0x010000)
     data->dfbSurface->ReleaseSource(data->dfbSurface);
 #endif
     return QPixmap(data);
 }
Properties
alpha
bool QDirectFBPixmapData::alpha private
Definition at line 96 of file qdirectfbpixmap.h.
Referenced by copy(), fill(), fromDataBufferDescription(), fromImage(), hasAlphaChannel(), invalidate(), resize(), and transformed().
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/directfb/qdirectfbpixmap.h
/src/plugins/gfxdrivers/directfb/qdirectfbpixmap.cpp