Qt 4.8: QExplicitlySharedDataPointer< T > Class Template Reference
QExplicitlySharedDataPointer< T > Class Template Reference
The QExplicitlySharedDataPointer class represents a pointer to an explicitly shared object.
#include <qshareddata.h>
Public Types
typedef T * pointer
typedef T Type
This is the type of the shared data object.
Public Functions
const T * constData () const
Returns a const pointer to the shared data object.
T * data () const
Returns a pointer to the shared data object.
void detach ()
If the shared data object's reference count is greater than 1, this function creates a deep copy of the shared data object and sets the d pointer of this to the copy.
operator bool () const
Returns true if the d pointer of this is not null.
bool operator! () const
Returns true if the d pointer of this is null.
bool operator!= (const QExplicitlySharedDataPointer< T > &other) const
Returns true if other and this do not have the same d pointer.
bool operator!= (const T *ptr) const
Returns true if the d pointer of this is not ptr.
T & operator* () const
Provides access to the shared data object's members.
T * operator-> ()
Provides access to the shared data object's members.
T * operator-> () const
Provides const access to the shared data object's members.
QExplicitlySharedDataPointer< T > & operator= (const QExplicitlySharedDataPointer< T > &o)
Sets the d pointer of this to the d pointer of other and increments the reference count of the shared data object.
QExplicitlySharedDataPointer & operator= (T *o)
Sets the d pointer of this to sharedData and increments {sharedData}'s reference count.
bool operator== (const QExplicitlySharedDataPointer< T > &other) const
Returns true if other and this have the same d pointer.
bool operator== (const T *ptr) const
Returns true if the d pointer of this is ptr.
QExplicitlySharedDataPointer ()
Constructs a QExplicitlySharedDataPointer initialized with a null d pointer.
QExplicitlySharedDataPointer (T *data)
Constructs a QExplicitlySharedDataPointer with d pointer set to sharedData and increments {sharedData}'s reference count.
QExplicitlySharedDataPointer (const QExplicitlySharedDataPointer< T > &o)
This standard copy constructor sets the {d pointer} of this to the {d pointer} in other and increments the reference count of the shared data object.
template<class X >
QExplicitlySharedDataPointer (const QExplicitlySharedDataPointer< X > &o)
This copy constructor is different in that it allows other to be a different type of explicitly shared data pointer but one that has a compatible shared data object.
void reset ()
Resets this to be null.
void swap (QExplicitlySharedDataPointer &other)
Swap this instance's explicitly shared data pointer with the explicitly shared data pointer in other.
~QExplicitlySharedDataPointer ()
Decrements the reference count of the shared data object.
Protected Functions
T * clone ()
Private Functions
void detach_helper ()
Properties
T * d
Detailed Description
template<class T>
class QExplicitlySharedDataPointer< T >
The QExplicitlySharedDataPointer class represents a pointer to an explicitly shared object.
Since
4.4
Note
This class or function is reentrant.
QExplicitlySharedDataPointer<T> makes writing your own explicitly shared classes easy. QExplicitlySharedDataPointer implements thread-safe reference counting, ensuring that adding QExplicitlySharedDataPointers to your reentrant classes won't make them non-reentrant.
Except for one big difference, QExplicitlySharedDataPointer is just like QSharedDataPointer. The big difference is that member functions of QExplicitlySharedDataPointer do not do the automatic copy on write operation (detach()) that non-const members of QSharedDataPointer do before allowing the shared data object to be modified. There is a detach() function available, but if you really want to detach(), you have to call it yourself. This means that QExplicitlySharedDataPointers behave like regular C++ pointers, except that by doing reference counting and not deleting the shared data object until the reference count is 0, they avoid the dangling pointer problem.
It is instructive to compare QExplicitlySharedDataPointer with QSharedDataPointer by way of an example. Consider the Employee example in QSharedDataPointer, modified to use explicit sharing as explained in the discussion Implicit vs Explicit Sharing.
Note that if you use this class but find you are calling detach() a lot, you probably should be using QSharedDataPointer instead.
In the member function documentation, d pointer always refers to the internal pointer to the shared data object.
See also
QSharedData, QSharedDataPointer
Definition at line 136 of file qshareddata.h.
Typedefs
pointer
template<class T> QExplicitlySharedDataPointer< T >::pointer
Warning
This function is not part of the public interface.
Definition at line 140 of file qshareddata.h.
Type
template<class T> QExplicitlySharedDataPointer< T >::Type
This is the type of the shared data object.
The d pointer points to an object of this type.
Definition at line 139 of file qshareddata.h.
Constructors and Destructors
QExplicitlySharedDataPointer() [1/4]
template<class T> QExplicitlySharedDataPointer< T >::QExplicitlySharedDataPointer () inline
Constructs a QExplicitlySharedDataPointer initialized with a null d pointer.
Definition at line 165 of file qshareddata.h.
 { d = 0; }
~QExplicitlySharedDataPointer()
template<class T> QExplicitlySharedDataPointer< T >::~QExplicitlySharedDataPointer () inline
Decrements the reference count of the shared data object.
If the reference count becomes 0, the shared data object is deleted. This is then destroyed.
Definition at line 166 of file qshareddata.h.
 { if (d && !d->ref.deref()) delete d; }
QExplicitlySharedDataPointer() [2/4]
template<class T> Q_INLINE_TEMPLATE QExplicitlySharedDataPointer< T >::QExplicitlySharedDataPointer (T * data) explicit
Constructs a QExplicitlySharedDataPointer with d pointer set to sharedData and increments {sharedData}'s reference count.
Definition at line 257 of file qshareddata.h.
                                                                                         : d(adata)
 { if (d) d->ref.ref(); }
QExplicitlySharedDataPointer() [3/4]
template<class T> QExplicitlySharedDataPointer< T >::QExplicitlySharedDataPointer (const QExplicitlySharedDataPointer< T > & o) inline
This standard copy constructor sets the {d pointer} of this to the {d pointer} in other and increments the reference count of the shared data object.
Definition at line 169 of file qshareddata.h.
 : d(o.d) { if (d) d->ref.ref(); }
QExplicitlySharedDataPointer() [4/4]
template<class T> template<class X > QExplicitlySharedDataPointer< T >::QExplicitlySharedDataPointer (const QExplicitlySharedDataPointer< X > & other) inline
This copy constructor is different in that it allows other to be a different type of explicitly shared data pointer but one that has a compatible shared data object.
It performs a static cast of the d pointer in other and sets the {d pointer} of this to the converted d pointer. It increments the reference count of the shared data object.
Definition at line 172 of file qshareddata.h.
                                                                                   : d(static_cast<T *>(o.data()))
     {
         if(d)
             d->ref.ref();
     }
Functions
clone()
template<class T > Q_INLINE_TEMPLATE T * QExplicitlySharedDataPointer< T >::clone () protected
Since
4.5
Creates and returns a deep copy of the current data. This function is called by detach() when the reference count is greater than 1 in order to create the new copy. This function uses the {operator new} and calls the copy constructor of the type T.
See QSharedDataPointer::clone() for an explanation of how to use it.
Definition at line 241 of file qshareddata.h.
 {
     return new T(*d);
 }
constData()
template<class T> const T * QExplicitlySharedDataPointer< T >::constData () const inline
Returns a const pointer to the shared data object.
See also
data()
Definition at line 146 of file qshareddata.h.
 { return d; }
data()
template<class T> T * QExplicitlySharedDataPointer< T >::data () const inline
Returns a pointer to the shared data object.
Definition at line 145 of file qshareddata.h.
Referenced by QPatternist::DistinctIterator::actualReflection(), QPatternist::UntypedAtomicConverter::actualReflection(), QPatternist::IndexOfIterator::actualReflection(), QPatternist::ContextItem::actualReflection(), QPatternist::OrderBy::OrderSpec::actualReflection(), QPatternist::QNameConstructor::actualReflection(), QPatternist::XsdElement::addSubstitutionGroup(), QPatternist::DocumentContentValidator::attribute(), QX11PaintEngine::begin(), QX11WindowSurface::beginPaint(), QGLContextPrivate::bindTextureFromNativePixmap(), QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFontMetrics::charWidth(), QPatternist::CallTargetDescription::checkCallsiteCircularity(), QPatternist::checkVariableCircularity(), QPixmap::clut(), QPixmap::colorCount(), QPatternist::SimpleContentConstructor::compress(), QPixmap::copy(), QPatternist::GenericPredicate::create(), QPatternist::create(), QPatternist::ExpressionFactory::createExpression(), QPatternist::XsdValidatingInstanceReader::createXQuery(), QPixmap::detach(), QFont::detach(), QX11PaintEngine::drawPixmap(), QX11PaintEngine::drawTiledPixmap(), QXmlQueryPrivate::dynamicContext(), QFontMetrics::elidedText(), QFontMetricsF::elidedText(), QPatternist::XsdValidatingInstanceReader::error(), QPatternist::ComparisonPlatform< IndexOfIterator, false >::fetchComparator(), QPatternist::findAxisStep(), QX11GLWindowSurface::flush(), QRawFont::fromFont(), QStaticTextPrivate::get(), QMeeGoGraphicsSystem::getLiveTextureHandle(), QMeeGoLivePixmapData::getSurfaceForBackingPixmap(), hasDuplicatedElementsInternal(), QMeeGoLivePixmapData::invalidateSurfaces(), QPatternist::Expression::invokeOptimizers(), QSslCertificate::issuerInfo(), QPatternist::Item::Item(), QPatternist::AtomicType::itemMatches(), QPatternist::CastingPlatform< UntypedAtomicConverter, true >::locateCaster(), QMeeGoGraphicsSystem::lockLiveTexture(), QFontInfo::operator=(), QFontMetrics::operator=(), QFontMetricsF::operator=(), QFont::operator=(), QPatternist::ItemType::operator|(), QPatternist::AxisStep::patternPriority(), QPixmap::pixmapData(), QPatternist::pushVariable(), QFont::QFont(), QFontMetrics::QFontMetrics(), QFontMetricsF::QFontMetricsF(), qstring_to_xtp(), qt_mac_cg_context(), qt_mac_create_imagemask(), qt_mac_pixmap_get_base(), qt_mac_pixmap_get_bytes_per_line(), QTextLayout::QTextLayout(), QPixmap::qwsBits(), QPixmap::qwsBytesPerLine(), QMeeGoGraphicsSystem::releaseLiveTexture(), QFont::resolve(), QPatternist::resolveVariable(), QPatternist::AccelTreeResourceLoader::retrieveDocument(), QPatternist::ConstructorFunctionsFactory::retrieveExpression(), QPatternist::Expression::rewrite(), QX11GLWindowSurface::scroll(), QSslCertificate::serialNumber(), QMacPixmapData::setAlphaChannel(), QPatternist::XsdSimpleType::setContext(), QPatternist::XsdComplexType::setContext(), QPatternist::XsdAttribute::Scope::setParent(), QPatternist::XsdElement::Scope::setParent(), QPatternist::UserFunctionCallsite::setSource(), QPatternist::XsdElement::setType(), QPatternist::XsdComplexType::setWxsSuperType(), QFontPrivate::smallCapsFontPrivate(), QSslCertificate::subjectInfo(), QFontMetrics::tightBoundingRect(), QFontMetricsF::tightBoundingRect(), toIcdConfig(), QPatternist::toItem(), QPatternist::AbstractFloat< isDouble >::toNegated(), QPatternist::Decimal::toNegated(), QPatternist::AtomicValue::toQt(), QPixmap::toWinHBITMAP(), QPatternist::DocumentFN::typeCheck(), QPatternist::CardinalityVerifier::verifyCardinality(), QPatternist::TypeChecker::verifyType(), QSslCertificate::version(), QFontMetrics::width(), QFontMetricsF::width(), QPatternist::NodeSortExpression::wrapAround(), QPatternist::StaticContext::wrapExpressionWith(), QPatternist::Literal::wrapLiteral(), QPatternist::AnyType::wxsTypeMatches(), QPatternist::BuiltinNodeType< kind >::xdtTypeMatches(), QPatternist::XSLTNodeTest::xdtTypeMatches(), QPatternist::XsdSchemaParser::XsdSchemaParser(), QPatternist::FunctionFactoryCollection::xslt20Factory(), and QPatternist::yyparse().
 { return d; }
detach()
template<class T> void QExplicitlySharedDataPointer< T >::detach () inline
If the shared data object's reference count is greater than 1, this function creates a deep copy of the shared data object and sets the d pointer of this to the copy.
Because QExplicitlySharedDataPointer does not do the automatic copy on write operations that members of QSharedDataPointer do, detach() is not called automatically anywhere in the member functions of this class. If you find that you are calling detach() everywhere in your code, consider using QSharedDataPointer instead.
Definition at line 148 of file qshareddata.h.
Referenced by QPicture::detach(), QStaticText::detach(), QGlyphRun::detach(), QDateTime::detach(), QFont::detach(), QDBusUnixFileDescriptor::giveFileDescriptor(), QRawFont::loadFromData(), QScriptString::operator=(), QScriptString::QScriptString(), and QRawFont::setPixelSize().
 { if (d && d->ref != 1) detach_helper(); }
detach_helper()
template<class T > Q_OUTOFLINE_TEMPLATE void QExplicitlySharedDataPointer< T >::detach_helper () private
Definition at line 247 of file qshareddata.h.
 {
     T *x = clone();
     x->ref.ref();
     if (!d->ref.deref())
         delete d;
     d = x;
 }
operator bool()
template<class T> QExplicitlySharedDataPointer< T >::operator bool () const inline
Returns true if the d pointer of this is not null.
Definition at line 158 of file qshareddata.h.
 { return d != 0; }
operator!()
template<class T> bool QExplicitlySharedDataPointer< T >::operator! () const inline
Returns true if the d pointer of this is null.
Definition at line 206 of file qshareddata.h.
 { return !d; }
operator!=() [1/2]
template<class T> bool QExplicitlySharedDataPointer< T >::operator!= (const QExplicitlySharedDataPointer< T > & other) const inline
Returns true if other and this do not have the same d pointer.
Definition at line 161 of file qshareddata.h.
 { return d != other.d; }
operator!=() [2/2]
template<class T> bool QExplicitlySharedDataPointer< T >::operator!= (const T * ptr) const inline
Returns true if the d pointer of this is not ptr.
Definition at line 163 of file qshareddata.h.
 { return d != ptr; }
operator*()
template<class T> T & QExplicitlySharedDataPointer< T >::operator* () const inline
Provides access to the shared data object's members.
Definition at line 142 of file qshareddata.h.
 { return *d; }
operator->() [1/2]
template<class T> T * QExplicitlySharedDataPointer< T >::operator-> () inline
Provides access to the shared data object's members.
Definition at line 143 of file qshareddata.h.
 { return d; }
operator->() [2/2]
template<class T> const T * QExplicitlySharedDataPointer< T >::operator-> () const inline
Provides const access to the shared data object's members.
Definition at line 144 of file qshareddata.h.
 { return d; }
operator=() [1/2]
template<class T> QExplicitlySharedDataPointer< T > & QExplicitlySharedDataPointer< T >::operator= (const QExplicitlySharedDataPointer< T > & other) inline
Sets the d pointer of this to the d pointer of other and increments the reference count of the shared data object.
The reference count of the old shared data object of this is decremented. If the reference count of the old shared data object becomes 0, the old shared data object is deleted.
Definition at line 178 of file qshareddata.h.
{
         if (o.d != d) {
             if (o.d)
                 o.d->ref.ref();
             T *old = d;
             d = o.d;
             if (old && !old->ref.deref())
                 delete old;
         }
         return *this;
     }
operator=() [2/2]
template<class T> QExplicitlySharedDataPointer & QExplicitlySharedDataPointer< T >::operator= (T * sharedData) inline
Sets the d pointer of this to sharedData and increments {sharedData}'s reference count.
The reference count of the old shared data object of this is decremented. If the reference count of the old shared data object becomes 0, the old shared data object is deleted.
Definition at line 189 of file qshareddata.h.
{
         if (o != d) {
             if (o)
                 o->ref.ref();
             T *old = d;
             d = o;
             if (old && !old->ref.deref())
                 delete old;
         }
         return *this;
     }
operator==() [1/2]
template<class T> bool QExplicitlySharedDataPointer< T >::operator== (const QExplicitlySharedDataPointer< T > & other) const inline
Returns true if other and this have the same d pointer.
Definition at line 160 of file qshareddata.h.
 { return d == other.d; }
operator==() [2/2]
template<class T> bool QExplicitlySharedDataPointer< T >::operator== (const T * ptr) const inline
Returns true if the d pointer of this is ptr.
Definition at line 162 of file qshareddata.h.
 { return d == ptr; }
reset()
template<class T> void QExplicitlySharedDataPointer< T >::reset () inline
Resets this to be null.
i.e., this function sets the d pointer of this to 0, but first it decrements the reference count of the shared data object and deletes the shared data object if the reference count became 0.
Definition at line 150 of file qshareddata.h.
Referenced by QPatternist::ApplyTemplate::compress(), QXmlQueryPrivate::expression(), QXmlQueryPrivate::recompileRequired(), and QXmlQueryPrivate::setRequiredType().
     {
         if(d && !d->ref.deref())
             delete d;
         d = 0;
     }
swap()
template<class T> void QExplicitlySharedDataPointer< T >::swap (QExplicitlySharedDataPointer< T > & other) inline
Swap this instance's explicitly shared data pointer with the explicitly shared data pointer in other.
Definition at line 208 of file qshareddata.h.
Referenced by qSwap().
     { qSwap(d, other.d); }
Properties
d
template<class T> T* QExplicitlySharedDataPointer< T >::d private
Definition at line 217 of file qshareddata.h.
Referenced by QExplicitlySharedDataPointer< QSslConfigurationPrivate >::operator!=(), QExplicitlySharedDataPointer< QSslConfigurationPrivate >::operator=(), QExplicitlySharedDataPointer< QSslConfigurationPrivate >::operator==(), QExplicitlySharedDataPointer< QSslConfigurationPrivate >::QExplicitlySharedDataPointer(), and QExplicitlySharedDataPointer< QSslConfigurationPrivate >::swap().
The documentation for this class was generated from the following files:
/src/corelib/tools/qshareddata.h
/src/corelib/tools/qshareddata.cpp