Qt 4.8: QBenchmarkEvent Class Reference
QBenchmarkEvent Class Reference
#include <qbenchmarkevent_p.h>
Public Functions
int adjustIterationCount (int suggestion)
int adjustMedianCount (int suggestion)
qint64 checkpoint ()
bool isMeasurementAccepted (qint64 measurement)
QTest::QBenchmarkMetric metricType ()
bool repeatCount ()
void start ()
qint64 stop ()
~QBenchmarkEvent ()
Public Functions inherited from QBenchmarkMeasurerBase
virtual void init ()
virtual bool needsWarmupIteration ()
virtual ~QBenchmarkMeasurerBase ()
Static Public Functions
static bool eventCountingMechanism (void *message)
Static Public Variables
static qint64 eventCounter = 0
Detailed Description
Definition at line 62 of file qbenchmarkevent_p.h.
Constructors and Destructors
~QBenchmarkEvent()
QBenchmarkEvent::~QBenchmarkEvent ()
Definition at line 52 of file qbenchmarkevent.cpp.
 {
 }
Functions
adjustIterationCount()
int QBenchmarkEvent::adjustIterationCount (int suggestion) virtual
Implements QBenchmarkMeasurerBase.
Definition at line 84 of file qbenchmarkevent.cpp.
 {
     return suggestion;
 }
adjustMedianCount()
int QBenchmarkEvent::adjustMedianCount (int suggestion) virtual
Implements QBenchmarkMeasurerBase.
Definition at line 89 of file qbenchmarkevent.cpp.
 {
     Q_UNUSED(suggestion);
     return 1;
 }
checkpoint()
qint64 QBenchmarkEvent::checkpoint () virtual
Implements QBenchmarkMeasurerBase.
Definition at line 63 of file qbenchmarkevent.cpp.
 {
     return QBenchmarkEvent::eventCounter;
 }
eventCountingMechanism()
bool QBenchmarkEvent::eventCountingMechanism (void * message) static
Definition at line 101 of file qbenchmarkevent.cpp.
Referenced by repeatCount(), and start().
 {
     Q_UNUSED(message);
     QBenchmarkEvent::eventCounter++;
     return false;
 }
isMeasurementAccepted()
bool QBenchmarkEvent::isMeasurementAccepted (qint64 measurement) virtual
Implements QBenchmarkMeasurerBase.
Definition at line 78 of file qbenchmarkevent.cpp.
 {
     Q_UNUSED(measurement);
     return true;
 }
metricType()
QTest::QBenchmarkMetric QBenchmarkEvent::metricType () virtual
Implements QBenchmarkMeasurerBase.
Definition at line 95 of file qbenchmarkevent.cpp.
Referenced by repeatCount().
 {
     return QTest::Events;
 }
repeatCount()
bool QBenchmarkEvent::repeatCount () inline virtual
Reimplemented from QBenchmarkMeasurerBase.
Definition at line 72 of file qbenchmarkevent_p.h.
 { return 1; }
start()
void QBenchmarkEvent::start () virtual
Implements QBenchmarkMeasurerBase.
Definition at line 56 of file qbenchmarkevent.cpp.
 {
     QBenchmarkEvent::eventCounter = 0;
     QAbstractEventDispatcher *parent = QAbstractEventDispatcher::instance();
     oldEventFilter = parent->setEventFilter(QBenchmarkEvent::eventCountingMechanism);
 }
stop()
qint64 QBenchmarkEvent::stop () virtual
Implements QBenchmarkMeasurerBase.
Definition at line 68 of file qbenchmarkevent.cpp.
 {
     QAbstractEventDispatcher *parent = QAbstractEventDispatcher::instance();
     parent->setEventFilter(oldEventFilter);
     return QBenchmarkEvent::eventCounter;
 }
Properties
eventCounter
qint64 QBenchmarkEvent::eventCounter = 0 static
Definition at line 75 of file qbenchmarkevent_p.h.
Referenced by checkpoint(), eventCountingMechanism(), start(), and stop().
The documentation for this class was generated from the following files:
/src/testlib/qbenchmarkevent_p.h
/src/testlib/qbenchmarkevent.cpp