Qt 4.8: QWSLinuxInputKeyboardHandler Class Reference
QWSLinuxInputKeyboardHandler Class Reference
#include <qkbdlinuxinput_qws.h>
Public Functions
virtual bool filterInputEvent (quint16 &input_code, qint32 &input_value)
virtual bool filterInputEvent (quint16 &input_code, qint32 &input_value)
QWSLinuxInputKeyboardHandler (const QString &)
QWSLinuxInputKeyboardHandler (const QString &)
virtual ~QWSLinuxInputKeyboardHandler ()
~QWSLinuxInputKeyboardHandler ()
Public Functions inherited from QWSKeyboardHandler
KeycodeAction processKeycode (quint16 keycode, bool pressed, bool autorepeat)
Maps keycode according to a keymap and sends that key event to the Qt for Embedded Linux server application.
virtual void processKeyEvent (int unicode, int keycode, Qt::KeyboardModifiers modifiers, bool isPress, bool autoRepeat)
Sends a key event to the Qt for Embedded Linux server application.
QWSKeyboardHandler ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QWSKeyboardHandler (const QString &device)
Constructs a keyboard driver.
virtual ~QWSKeyboardHandler ()
Destroys this keyboard driver.
Properties
QWSLinuxInputKbPrivate * d
Additional Inherited Members
Public Types inherited from QWSKeyboardHandler
enum KeycodeAction {
None = 0, CapsLockOff = 0x01000000, CapsLockOn = 0x01000001, NumLockOff = 0x02000000,
NumLockOn = 0x02000001, ScrollLockOff = 0x03000000, ScrollLockOn = 0x03000001, Reboot = 0x04000000,
PreviousConsole = 0x05000000, NextConsole = 0x05000001, SwitchConsoleFirst = 0x06000000, SwitchConsoleLast = 0x0600007f,
SwitchConsoleMask = 0x0000007f
}
This enum describes the various special actions that actual QWSKeyboardHandler implementations have to take care of.
Protected Functions inherited from QWSKeyboardHandler
void beginAutoRepeat (int uni, int code, Qt::KeyboardModifiers mod)
Begins auto-repeating the specified key press; after a short delay the key press is sent periodically until the endAutoRepeat() function is called.
void endAutoRepeat ()
Stops auto-repeating a key press.
int transformDirKey (int key)
Transforms the arrow key specified by the given keycode, to the orientation of the display and returns the transformed keycode.
Detailed Description
Definition at line 59 of file qkbdlinuxinput_qws.h.
Constructors and Destructors
QWSLinuxInputKeyboardHandler() [1/2]
QWSLinuxInputKeyboardHandler::QWSLinuxInputKeyboardHandler (const QString & device)
Definition at line 82 of file qkbdlinuxinput_qws.cpp.
Referenced by QLinuxInputMouseHandler::readMouseData().
     : QWSKeyboardHandler(device)
 {
     d = new QWSLinuxInputKbPrivate(this, device);
 }
~QWSLinuxInputKeyboardHandler() [1/2]
QWSLinuxInputKeyboardHandler::~QWSLinuxInputKeyboardHandler () virtual
Definition at line 88 of file qkbdlinuxinput_qws.cpp.
Referenced by QLinuxInputMouseHandler::readMouseData().
 {
     delete d;
 }
QWSLinuxInputKeyboardHandler() [2/2]
QWSLinuxInputKeyboardHandler::QWSLinuxInputKeyboardHandler (const QString &)
~QWSLinuxInputKeyboardHandler() [2/2]
QWSLinuxInputKeyboardHandler::~QWSLinuxInputKeyboardHandler ()
Functions
filterInputEvent() [1/2]
bool QWSLinuxInputKeyboardHandler::filterInputEvent (quint16 & input_code, qint32 & input_value) virtual
Definition at line 93 of file qkbdlinuxinput_qws.cpp.
Referenced by QWSLinuxInputKbPrivate::readKeycode(), QLinuxInputKeyboardHandler::readKeycode(), and QLinuxInputMouseHandler::readMouseData().
 {
     return false;
 }
filterInputEvent() [2/2]
virtual bool QWSLinuxInputKeyboardHandler::filterInputEvent (quint16 & input_code, qint32 & input_value) virtual
Properties
d
QWSLinuxInputKbPrivate* QWSLinuxInputKeyboardHandler::d private
Definition at line 68 of file qkbdlinuxinput_qws.h.
Referenced by QWSLinuxInputKeyboardHandler(), and ~QWSLinuxInputKeyboardHandler().
The documentation for this class was generated from the following files:
/src/gui/embedded/qkbdlinuxinput_qws.h
/src/plugins/generic/linuxinput/qlinuxinput.cpp
/src/gui/embedded/qkbdlinuxinput_qws.cpp