Qt 4.8: QIdentityProxyModel Class Reference
QIdentityProxyModel Class Reference
The QIdentityProxyModel class proxies its source model unmodified.
#include <qidentityproxymodel.h>
Public Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
Reimplemented Function
QItemSelection mapSelectionFromSource (const QItemSelection &selection) const
Reimplemented Function
QItemSelection mapSelectionToSource (const QItemSelection &selection) const
Reimplemented Function
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
Reimplemented Function
QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Reimplemented Function
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QIdentityProxyModel (QObject *parent=0)
Constructs an identity model with the given parent.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void setSourceModel (QAbstractItemModel *sourceModel)
Reimplemented Function
~QIdentityProxyModel ()
Destroys this identity model.
Public Functions inherited from QAbstractProxyModel
QModelIndex buddy (const QModelIndex &index) const
Reimplemented Function
bool canFetchMore (const QModelIndex &parent) const
Reimplemented Function
QVariant data (const QModelIndex &proxyIndex, int role=Qt::DisplayRole) const
Reimplemented Function
void fetchMore (const QModelIndex &parent)
Reimplemented Function
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role) const
Reimplemented Function
QMap< int, QVariant > itemData (const QModelIndex &index) const
Reimplemented Function
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QAbstractProxyModel (QObject *parent=0)
Constructs a proxy model with the given parent.
void revert ()
Reimplemented Function
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Reimplemented Function
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
QAbstractItemModel * sourceModel () const
Returns the model that contains the data that is available through the proxy model.
QSize span (const QModelIndex &index) const
Reimplemented Function
bool submit ()
Reimplemented Function
Qt::DropActions supportedDropActions () const
Reimplemented Function
~QAbstractProxyModel ()
Destroys the proxy model.
Public Functions inherited from QAbstractItemModel
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QIdentityProxyModel (QIdentityProxyModelPrivate &dd, QObject *parent)
Protected Functions inherited from QAbstractProxyModel
QAbstractProxyModel (QAbstractProxyModelPrivate &, QObject *parent)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QIdentityProxyModel class proxies its source model unmodified.
Since
4.8
QIdentityProxyModel can be used to forward the structure of a source model exactly, with no sorting, filtering or other transformation. This is similar in concept to an identity matrix where A.I = A.
Because it does no sorting or filtering, this class is most suitable to proxy models which transform the data() of the source model. For example, a proxy model could be created to define the font used, or the background colour, or the tooltip etc. This removes the need to implement all data handling in the same class that creates the structure of the model, and can also be used to create re-usable components.
This also provides a way to change the data in the case where a source model is supplied by a third party which can not be modified.
class DateFormatProxyModel : public QIdentityProxyModel
{
  // ...
  void setDateFormatString(const QString &formatString)
  {
    m_formatString = formatString;
  }
  QVariant data(const QModelIndex &index, int role)
  {
    if (role != Qt::DisplayRole)
      return QIdentityProxyModel::data(index, role);
    const QDateTime dateTime = sourceModel()->data(SourceClass::DateRole).toDateTime();
    return dateTime.toString(m_formatString);
  }
private:
  QString m_formatString;
};
See also
QAbstractProxyModel, {Model/View Programming}, QAbstractItemModel
Definition at line 58 of file qidentityproxymodel.h.
Constructors and Destructors
QIdentityProxyModel() [1/2]
QIdentityProxyModel::QIdentityProxyModel (QObject * parent = 0) explicit
Constructs an identity model with the given parent.
Definition at line 120 of file qidentityproxymodel.cpp.
   : QAbstractProxyModel(*new QIdentityProxyModelPrivate, parent)
 {
 }
~QIdentityProxyModel()
QIdentityProxyModel::~QIdentityProxyModel ()
Destroys this identity model.
Definition at line 137 of file qidentityproxymodel.cpp.
 {
 }
QIdentityProxyModel() [2/2]
QIdentityProxyModel::QIdentityProxyModel (QIdentityProxyModelPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 128 of file qidentityproxymodel.cpp.
   : QAbstractProxyModel(dd, parent)
 {
 }
Functions
columnCount()
int QIdentityProxyModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 144 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(const QIdentityProxyModel);
     return d->model->columnCount(mapToSource(parent));
 }
dropMimeData()
bool QIdentityProxyModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 154 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(QIdentityProxyModel);
     return d->model->dropMimeData(data, action, row, column, mapToSource(parent));
 }
index()
QModelIndex QIdentityProxyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 164 of file qidentityproxymodel.cpp.
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(const QIdentityProxyModel);
     if (!hasIndex(row, column, parent))
         return QModelIndex();
     const QModelIndex sourceParent = mapToSource(parent);
     const QModelIndex sourceIndex = d->model->index(row, column, sourceParent);
     Q_ASSERT(sourceIndex.isValid());
     return mapFromSource(sourceIndex);
 }
insertColumns()
bool QIdentityProxyModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 179 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::insertColumn(), and QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(QIdentityProxyModel);
     return d->model->insertColumns(column, count, mapToSource(parent));
 }
insertRows()
bool QIdentityProxyModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 189 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::insertRow(), and QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(QIdentityProxyModel);
     return d->model->insertRows(row, count, mapToSource(parent));
 }
mapFromSource()
QModelIndex QIdentityProxyModel::mapFromSource (const QModelIndex & sourceIndex) const virtual
Reimplemented Function
Implements QAbstractProxyModel.
Definition at line 199 of file qidentityproxymodel.cpp.
Referenced by index(), mapSelectionFromSource(), match(), and parent().
 {
     Q_D(const QIdentityProxyModel);
     if (!d->model || !sourceIndex.isValid())
         return QModelIndex();
     Q_ASSERT(sourceIndex.model() == d->model);
     return createIndex(sourceIndex.row(), sourceIndex.column(), sourceIndex.internalPointer());
 }
mapSelectionFromSource()
QItemSelection QIdentityProxyModel::mapSelectionFromSource (const QItemSelection & selection) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 212 of file qidentityproxymodel.cpp.
 {
     Q_D(const QIdentityProxyModel);
     QItemSelection proxySelection;
     if (!d->model)
         return proxySelection;
     QItemSelection::const_iterator it = selection.constBegin();
     const QItemSelection::const_iterator end = selection.constEnd();
     for ( ; it != end; ++it) {
         Q_ASSERT(it->model() == d->model);
         const QItemSelectionRange range(mapFromSource(it->topLeft()), mapFromSource(it->bottomRight()));
         proxySelection.append(range);
     }
     return proxySelection;
 }
mapSelectionToSource()
QItemSelection QIdentityProxyModel::mapSelectionToSource (const QItemSelection & selection) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 234 of file qidentityproxymodel.cpp.
 {
     Q_D(const QIdentityProxyModel);
     QItemSelection sourceSelection;
     if (!d->model)
         return sourceSelection;
     QItemSelection::const_iterator it = selection.constBegin();
     const QItemSelection::const_iterator end = selection.constEnd();
     for ( ; it != end; ++it) {
         Q_ASSERT(it->model() == this);
         const QItemSelectionRange range(mapToSource(it->topLeft()), mapToSource(it->bottomRight()));
         sourceSelection.append(range);
     }
     return sourceSelection;
 }
mapToSource()
QModelIndex QIdentityProxyModel::mapToSource (const QModelIndex & proxyIndex) const virtual
Reimplemented Function
Implements QAbstractProxyModel.
Definition at line 256 of file qidentityproxymodel.cpp.
Referenced by columnCount(), dropMimeData(), index(), insertColumns(), insertRows(), mapSelectionToSource(), match(), parent(), removeColumns(), removeRows(), and rowCount().
 {
     Q_D(const QIdentityProxyModel);
     if (!d->model || !proxyIndex.isValid())
         return QModelIndex();
     Q_ASSERT(proxyIndex.model() == this);
     return d->model->createIndex(proxyIndex.row(), proxyIndex.column(), proxyIndex.internalPointer());
 }
match()
QModelIndexList QIdentityProxyModel::match (const QModelIndex & start, int role, const QVariant & value, int hits = 1, Qt::MatchFlags flags = Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 268 of file qidentityproxymodel.cpp.
 {
     Q_D(const QIdentityProxyModel);
     Q_ASSERT(start.isValid() ? start.model() == this : true);
     if (!d->model)
         return QModelIndexList();
     const QModelIndexList sourceList = d->model->match(mapToSource(start), role, value, hits, flags);
     QModelIndexList::const_iterator it = sourceList.constBegin();
     const QModelIndexList::const_iterator end = sourceList.constEnd();
     QModelIndexList proxyList;
     for ( ; it != end; ++it)
         proxyList.append(mapFromSource(*it));
     return proxyList;
 }
parent()
QModelIndex QIdentityProxyModel::parent (const QModelIndex & child) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 287 of file qidentityproxymodel.cpp.
 {
     Q_ASSERT(child.isValid() ? child.model() == this : true);
     const QModelIndex sourceIndex = mapToSource(child);
     const QModelIndex sourceParent = sourceIndex.parent();
     return mapFromSource(sourceParent);
 }
removeColumns()
bool QIdentityProxyModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 298 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::removeColumn(), and QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(QIdentityProxyModel);
     return d->model->removeColumns(column, count, mapToSource(parent));
 }
removeRows()
bool QIdentityProxyModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 308 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::removeRow(), and QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(QIdentityProxyModel);
     return d->model->removeRows(row, count, mapToSource(parent));
 }
rowCount()
int QIdentityProxyModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 318 of file qidentityproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_ASSERT(parent.isValid() ? parent.model() == this : true);
     Q_D(const QIdentityProxyModel);
     return d->model->rowCount(mapToSource(parent));
 }
setSourceModel()
void QIdentityProxyModel::setSourceModel (QAbstractItemModel * sourceModel) virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 328 of file qidentityproxymodel.cpp.
 {
     beginResetModel();
     if (sourceModel()) {
         disconnect(sourceModel(), SIGNAL(rowsAboutToBeInserted(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceRowsAboutToBeInserted(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceRowsInserted(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(rowsAboutToBeRemoved(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceRowsAboutToBeRemoved(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceRowsRemoved(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(rowsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                    this, SLOT(_q_sourceRowsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         disconnect(sourceModel(), SIGNAL(rowsMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                    this, SLOT(_q_sourceRowsMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         disconnect(sourceModel(), SIGNAL(columnsAboutToBeInserted(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceColumnsAboutToBeInserted(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(columnsInserted(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceColumnsInserted(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(columnsAboutToBeRemoved(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceColumnsAboutToBeRemoved(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(columnsRemoved(const QModelIndex &, int, int)),
                    this, SLOT(_q_sourceColumnsRemoved(const QModelIndex &, int, int)));
         disconnect(sourceModel(), SIGNAL(columnsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                    this, SLOT(_q_sourceColumnsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         disconnect(sourceModel(), SIGNAL(columnsMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                    this, SLOT(_q_sourceColumnsMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         disconnect(sourceModel(), SIGNAL(modelAboutToBeReset()),
                    this, SLOT(_q_sourceModelAboutToBeReset()));
         disconnect(sourceModel(), SIGNAL(modelReset()),
                    this, SLOT(_q_sourceModelReset()));
         disconnect(sourceModel(), SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
                    this, SLOT(_q_sourceDataChanged(const QModelIndex &, const QModelIndex &)));
         disconnect(sourceModel(), SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                    this, SLOT(_q_sourceHeaderDataChanged(Qt::Orientation,int,int)));
         disconnect(sourceModel(), SIGNAL(layoutAboutToBeChanged()),
                    this, SLOT(_q_sourceLayoutAboutToBeChanged()));
         disconnect(sourceModel(), SIGNAL(layoutChanged()),
                    this, SLOT(_q_sourceLayoutChanged()));
     }
     QAbstractProxyModel::setSourceModel(newSourceModel);
     if (sourceModel()) {
         connect(sourceModel(), SIGNAL(rowsAboutToBeInserted(const QModelIndex &, int, int)),
                 SLOT(_q_sourceRowsAboutToBeInserted(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(rowsInserted(const QModelIndex &, int, int)),
                 SLOT(_q_sourceRowsInserted(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(rowsAboutToBeRemoved(const QModelIndex &, int, int)),
                 SLOT(_q_sourceRowsAboutToBeRemoved(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(rowsRemoved(const QModelIndex &, int, int)),
                 SLOT(_q_sourceRowsRemoved(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(rowsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                 SLOT(_q_sourceRowsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         connect(sourceModel(), SIGNAL(rowsMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                 SLOT(_q_sourceRowsMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         connect(sourceModel(), SIGNAL(columnsAboutToBeInserted(const QModelIndex &, int, int)),
                 SLOT(_q_sourceColumnsAboutToBeInserted(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(columnsInserted(const QModelIndex &, int, int)),
                 SLOT(_q_sourceColumnsInserted(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(columnsAboutToBeRemoved(const QModelIndex &, int, int)),
                 SLOT(_q_sourceColumnsAboutToBeRemoved(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(columnsRemoved(const QModelIndex &, int, int)),
                 SLOT(_q_sourceColumnsRemoved(const QModelIndex &, int, int)));
         connect(sourceModel(), SIGNAL(columnsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                 SLOT(_q_sourceColumnsAboutToBeMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         connect(sourceModel(), SIGNAL(columnsMoved(const QModelIndex &, int, int, const QModelIndex &, int)),
                 SLOT(_q_sourceColumnsMoved(const QModelIndex &, int, int, const QModelIndex &, int)));
         connect(sourceModel(), SIGNAL(modelAboutToBeReset()),
                 SLOT(_q_sourceModelAboutToBeReset()));
         connect(sourceModel(), SIGNAL(modelReset()),
                 SLOT(_q_sourceModelReset()));
         connect(sourceModel(), SIGNAL(dataChanged(const QModelIndex &, const QModelIndex &)),
                 SLOT(_q_sourceDataChanged(const QModelIndex &, const QModelIndex &)));
         connect(sourceModel(), SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                 SLOT(_q_sourceHeaderDataChanged(Qt::Orientation,int,int)));
         connect(sourceModel(), SIGNAL(layoutAboutToBeChanged()),
                 SLOT(_q_sourceLayoutAboutToBeChanged()));
         connect(sourceModel(), SIGNAL(layoutChanged()),
                 SLOT(_q_sourceLayoutChanged()));
     }
     endResetModel();
 }
The documentation for this class was generated from the following files:
/src/gui/itemviews/qidentityproxymodel.h
/src/gui/itemviews/qidentityproxymodel.cpp