Qt 4.8: QDeclarativeVMEVariant Class Reference
QDeclarativeVMEVariant Class Reference
Public Functions
bool asBool ()
double asDouble ()
int asInt ()
const QColor & asQColor ()
const QDate & asQDate ()
const QDateTime & asQDateTime ()
QObject * asQObject ()
const QScriptValue & asQScriptValue ()
const QString & asQString ()
const QTime & asQTime ()
const QUrl & asQUrl ()
const QVariant & asQVariant ()
const void * dataPtr () const
void * dataPtr ()
int dataType () const
QDeclarativeVMEVariant ()
void setValue (QObject *)
void setValue (const QVariant &)
void setValue (int)
void setValue (bool)
void setValue (double)
void setValue (const QString &)
void setValue (const QUrl &)
void setValue (const QColor &)
void setValue (const QTime &)
void setValue (const QDate &)
void setValue (const QDateTime &)
void setValue (const QScriptValue &)
~QDeclarativeVMEVariant ()
Private Functions
void cleanup ()
Properties
void * data [4]
int type
Detailed Description
Definition at line 55 of file qdeclarativevmemetaobject.cpp.
Constructors and Destructors
QDeclarativeVMEVariant()
QDeclarativeVMEVariant::QDeclarativeVMEVariant () inline
Definition at line 97 of file qdeclarativevmemetaobject.cpp.
 : type(QVariant::Invalid)
 {
 }
~QDeclarativeVMEVariant()
QDeclarativeVMEVariant::~QDeclarativeVMEVariant () inline
Definition at line 102 of file qdeclarativevmemetaobject.cpp.
 {
     cleanup();
 }
Functions
asBool()
bool QDeclarativeVMEVariant::asBool () inline
Definition at line 184 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::Bool)
         setValue(bool(false));
     return *(bool *)(dataPtr());
 }
asDouble()
double QDeclarativeVMEVariant::asDouble () inline
Definition at line 192 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::Double)
         setValue(double(0));
     return *(double *)(dataPtr());
 }
asInt()
int QDeclarativeVMEVariant::asInt () inline
Definition at line 176 of file qdeclarativevmemetaobject.cpp.
Referenced by QDeclarativeVMEMetaObject::metaCall().
 {
     if (type != QMetaType::Int)
         setValue(int(0));
     return *(int *)(dataPtr());
 }
asQColor()
const QColor & QDeclarativeVMEVariant::asQColor () inline
Definition at line 216 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QColor)
         setValue(QColor());
     return *(QColor *)(dataPtr());
 }
asQDate()
const QDate & QDeclarativeVMEVariant::asQDate () inline
Definition at line 232 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QDate)
         setValue(QDate());
     return *(QDate *)(dataPtr());
 }
asQDateTime()
const QDateTime & QDeclarativeVMEVariant::asQDateTime () inline
Definition at line 240 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QDateTime)
         setValue(QDateTime());
     return *(QDateTime *)(dataPtr());
 }
asQObject()
QObject * QDeclarativeVMEVariant::asQObject () inline
Definition at line 160 of file qdeclarativevmemetaobject.cpp.
Referenced by QDeclarativeVMEMetaObject::writeVarProperty().
 {
     if (type != QMetaType::QObjectStar)
         setValue((QObject *)0);
     return *(QDeclarativeGuard<QObject> *)(dataPtr());
 }
asQScriptValue()
const QScriptValue & QDeclarativeVMEVariant::asQScriptValue () inline
Definition at line 248 of file qdeclarativevmemetaobject.cpp.
Referenced by QDeclarativeVMEMetaObject::readVarProperty().
 {
     if (type != qMetaTypeId<QScriptValue>())
         setValue(QScriptValue());
     return *(QScriptValue *)(dataPtr());
 }
asQString()
const QString & QDeclarativeVMEVariant::asQString () inline
Definition at line 200 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QString)
         setValue(QString());
     return *(QString *)(dataPtr());
 }
asQTime()
const QTime & QDeclarativeVMEVariant::asQTime () inline
Definition at line 224 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QTime)
         setValue(QTime());
     return *(QTime *)(dataPtr());
 }
asQUrl()
const QUrl & QDeclarativeVMEVariant::asQUrl () inline
Definition at line 208 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QUrl)
         setValue(QUrl());
     return *(QUrl *)(dataPtr());
 }
asQVariant()
const QVariant & QDeclarativeVMEVariant::asQVariant () inline
Definition at line 168 of file qdeclarativevmemetaobject.cpp.
Referenced by QDeclarativeVMEMetaObject::readVarPropertyAsVariant(), and QDeclarativeVMEMetaObject::writeVarProperty().
 {
     if (type != QMetaType::QVariant)
         setValue(QVariant());
     return *(QVariant *)(dataPtr());
 }
cleanup()
void QDeclarativeVMEVariant::cleanup () inline private
Definition at line 107 of file qdeclarativevmemetaobject.cpp.
Referenced by setValue(), and ~QDeclarativeVMEVariant().
 {
     if (type == QVariant::Invalid) {
     } else if (type == QMetaType::Int ||
                type == QMetaType::Bool ||
                type == QMetaType::Double) {
         type = QVariant::Invalid;
     } else if (type == QMetaType::QObjectStar) {
         ((QDeclarativeGuard<QObject>*)dataPtr())->~QDeclarativeGuard<QObject>();
         type = QVariant::Invalid;
     } else if (type == QMetaType::QString) {
         ((QString *)dataPtr())->~QString();
         type = QVariant::Invalid;
     } else if (type == QMetaType::QUrl) {
         ((QUrl *)dataPtr())->~QUrl();
         type = QVariant::Invalid;
     } else if (type == QMetaType::QColor) {
         ((QColor *)dataPtr())->~QColor();
         type = QVariant::Invalid;
     } else if (type == QMetaType::QTime) {
         ((QTime *)dataPtr())->~QTime();
         type = QVariant::Invalid;
     } else if (type == QMetaType::QDate) {
         ((QDate *)dataPtr())->~QDate();
         type = QVariant::Invalid;
     } else if (type == QMetaType::QDateTime) {
         ((QDateTime *)dataPtr())->~QDateTime();
         type = QVariant::Invalid;
     } else if (type == qMetaTypeId<QVariant>()) {
         ((QVariant *)dataPtr())->~QVariant();
         type = QVariant::Invalid;
     } else if (type == qMetaTypeId<QScriptValue>()) {
         ((QScriptValue *)dataPtr())->~QScriptValue();
         type = QVariant::Invalid;
     }
 }
dataPtr() [1/2]
const void * QDeclarativeVMEVariant::dataPtr () const inline
Definition at line 150 of file qdeclarativevmemetaobject.cpp.
Referenced by asBool(), asDouble(), asInt(), asQColor(), asQDate(), asQDateTime(), asQObject(), asQScriptValue(), asQString(), asQTime(), asQUrl(), asQVariant(), cleanup(), and setValue().
 {
     return &data;
 }
dataPtr() [2/2]
void * QDeclarativeVMEVariant::dataPtr () inline
Definition at line 155 of file qdeclarativevmemetaobject.cpp.
 {
     return &data;
 }
dataType()
int QDeclarativeVMEVariant::dataType () const inline
Definition at line 145 of file qdeclarativevmemetaobject.cpp.
Referenced by QDeclarativeVMEMetaObject::writeVarProperty().
 {
     return type;
 }
setValue() [1/12]
void QDeclarativeVMEVariant::setValue (QObject * v) inline
Definition at line 256 of file qdeclarativevmemetaobject.cpp.
Referenced by asBool(), asDouble(), asInt(), asQColor(), asQDate(), asQDateTime(), asQObject(), asQScriptValue(), asQString(), asQTime(), asQUrl(), asQVariant(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), and QDeclarativeVMEMetaObject::writeVarProperty().
 {
     if (type != QMetaType::QObjectStar) {
         cleanup();
         type = QMetaType::QObjectStar;
         new (dataPtr()) QDeclarativeGuard<QObject>();
     }
     *(QDeclarativeGuard<QObject>*)(dataPtr()) = v;
 }
setValue() [2/12]
void QDeclarativeVMEVariant::setValue (const QVariant & v) inline
Definition at line 266 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != qMetaTypeId<QVariant>()) {
         cleanup();
         type = qMetaTypeId<QVariant>();
         new (dataPtr()) QVariant(v);
     } else {
         *(QVariant *)(dataPtr()) = v;
     }
 }
setValue() [3/12]
void QDeclarativeVMEVariant::setValue (int v) inline
Definition at line 277 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::Int) {
         cleanup();
         type = QMetaType::Int;
     }
     *(int *)(dataPtr()) = v;
 }
setValue() [4/12]
void QDeclarativeVMEVariant::setValue (bool v) inline
Definition at line 286 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::Bool) {
         cleanup();
         type = QMetaType::Bool;
     }
     *(bool *)(dataPtr()) = v;
 }
setValue() [5/12]
void QDeclarativeVMEVariant::setValue (double v) inline
Definition at line 295 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::Double) {
         cleanup();
         type = QMetaType::Double;
     }
     *(double *)(dataPtr()) = v;
 }
setValue() [6/12]
void QDeclarativeVMEVariant::setValue (const QString & v) inline
Definition at line 304 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QString) {
         cleanup();
         type = QMetaType::QString;
         new (dataPtr()) QString(v);
     } else {
         *(QString *)(dataPtr()) = v;
     }
 }
setValue() [7/12]
void QDeclarativeVMEVariant::setValue (const QUrl & v) inline
Definition at line 315 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QUrl) {
         cleanup();
         type = QMetaType::QUrl;
         new (dataPtr()) QUrl(v);
     } else {
         *(QUrl *)(dataPtr()) = v;
     }
 }
setValue() [8/12]
void QDeclarativeVMEVariant::setValue (const QColor & v) inline
Definition at line 326 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QColor) {
         cleanup();
         type = QMetaType::QColor;
         new (dataPtr()) QColor(v);
     } else {
         *(QColor *)(dataPtr()) = v;
     }
 }
setValue() [9/12]
void QDeclarativeVMEVariant::setValue (const QTime & v) inline
Definition at line 337 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QTime) {
         cleanup();
         type = QMetaType::QTime;
         new (dataPtr()) QTime(v);
     } else {
         *(QTime *)(dataPtr()) = v;
     }
 }
setValue() [10/12]
void QDeclarativeVMEVariant::setValue (const QDate & v) inline
Definition at line 348 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QDate) {
         cleanup();
         type = QMetaType::QDate;
         new (dataPtr()) QDate(v);
     } else {
         *(QDate *)(dataPtr()) = v;
     }
 }
setValue() [11/12]
void QDeclarativeVMEVariant::setValue (const QDateTime & v) inline
Definition at line 359 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != QMetaType::QDateTime) {
         cleanup();
         type = QMetaType::QDateTime;
         new (dataPtr()) QDateTime(v);
     } else {
         *(QDateTime *)(dataPtr()) = v;
     }
 }
setValue() [12/12]
void QDeclarativeVMEVariant::setValue (const QScriptValue & v) inline
Definition at line 370 of file qdeclarativevmemetaobject.cpp.
 {
     if (type != qMetaTypeId<QScriptValue>()) {
         cleanup();
         type = qMetaTypeId<QScriptValue>();
         new (dataPtr()) QScriptValue(v);
     } else {
         *(QScriptValue *)(dataPtr()) = v;
     }
 }
Properties
data
void* QDeclarativeVMEVariant::data[4] private
Definition at line 92 of file qdeclarativevmemetaobject.cpp.
Referenced by dataPtr().
type
int QDeclarativeVMEVariant::type private
Definition at line 91 of file qdeclarativevmemetaobject.cpp.
Referenced by asBool(), asDouble(), asInt(), asQColor(), asQDate(), asQDateTime(), asQObject(), asQScriptValue(), asQString(), asQTime(), asQUrl(), asQVariant(), cleanup(), dataType(), and setValue().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativevmemetaobject.cpp