Qt 4.8: QSvgGradientStyle Class Reference
QSvgGradientStyle Class Reference
#include <qsvgstyle_p.h>
Public Functions
QBrush brush (QPainter *, QSvgExtraStates &)
bool gradientStopsSet () const
QGradient * qgradient () const
QMatrix qmatrix () const
QSvgGradientStyle (QGradient *grad)
void resolveStops ()
void setGradientStopsSet (bool set)
void setMatrix (const QMatrix &matrix)
void setStopLink (const QString &link, QSvgTinyDocument *doc)
QString stopLink () const
virtual Type type () const
~QSvgGradientStyle ()
Public Functions inherited from QSvgFillStyleProperty
virtual void apply (QPainter *p, const QSvgNode *node, QSvgExtraStates &states)
virtual void revert (QPainter *p, QSvgExtraStates &states)
Public Functions inherited from QSvgStyleProperty
virtual ~QSvgStyleProperty ()
Public Functions inherited from QSvgRefCounted
void deref ()
QSvgRefCounted ()
void ref ()
virtual ~QSvgRefCounted ()
Properties
QSvgTinyDocument * m_doc
QGradient * m_gradient
bool m_gradientStopsSet
QString m_link
QMatrix m_matrix
Additional Inherited Members
Public Types inherited from QSvgStyleProperty
enum Type {
QUALITY, FILL, VIEWPORT_FILL, FONT,
STROKE, SOLID_COLOR, GRADIENT, TRANSFORM,
ANIMATE_TRANSFORM, ANIMATE_COLOR, OPACITY, COMP_OP
}
Detailed Description
Definition at line 574 of file qsvgstyle_p.h.
Constructors and Destructors
QSvgGradientStyle()
QSvgGradientStyle::QSvgGradientStyle (QGradient * grad)
Definition at line 410 of file qsvgstyle.cpp.
     : m_gradient(grad), m_gradientStopsSet(false)
 {
 }
~QSvgGradientStyle()
QSvgGradientStyle::~QSvgGradientStyle () inline
Definition at line 578 of file qsvgstyle_p.h.
 { delete m_gradient; }
Functions
brush()
QBrush QSvgGradientStyle::brush (QPainter * , QSvgExtraStates &) virtual
Implements QSvgFillStyleProperty.
Definition at line 415 of file qsvgstyle.cpp.
 {
     if (!m_link.isEmpty()) {
         resolveStops();
     }
     // If the gradient is marked as empty, insert transparent black
     if (!m_gradientStopsSet) {
         m_gradient->setStops(QGradientStops() << QGradientStop(0.0, QColor(0, 0, 0, 0)));
         m_gradientStopsSet = true;
     }
     QBrush b(*m_gradient);
     if (!m_matrix.isIdentity())
         b.setMatrix(m_matrix);
     return b;
 }
gradientStopsSet()
bool QSvgGradientStyle::gradientStopsSet () const inline
Definition at line 596 of file qsvgstyle_p.h.
Referenced by parseBaseGradient(), parseStopNode(), and resolveStops().
     {
         return m_gradientStopsSet;
     }
qgradient()
QGradient* QSvgGradientStyle::qgradient () const inline
Definition at line 591 of file qsvgstyle_p.h.
Referenced by parseBaseGradient(), parseStopNode(), and resolveStops().
     {
         return m_gradient;
     }
qmatrix()
QMatrix QSvgGradientStyle::qmatrix () const inline
Definition at line 586 of file qsvgstyle_p.h.
Referenced by parseBaseGradient().
     {
         return m_matrix;
     }
resolveStops()
void QSvgGradientStyle::resolveStops ()
Definition at line 937 of file qsvgstyle.cpp.
Referenced by brush(), and resolveStops().
 {
     if (!m_link.isEmpty() && m_doc) {
         QSvgStyleProperty *prop = m_doc->styleProperty(m_link);
         if (prop) {
             if (prop->type() == QSvgStyleProperty::GRADIENT) {
                 QSvgGradientStyle *st =
                     static_cast<QSvgGradientStyle*>(prop);
                 st->resolveStops();
                 m_gradient->setStops(st->qgradient()->stops());
                 m_gradientStopsSet = st->gradientStopsSet();
             }
         } else {
             qWarning("Could not resolve property : %s", qPrintable(m_link));
         }
         m_link = QString();
     }
 }
setGradientStopsSet()
void QSvgGradientStyle::setGradientStopsSet (bool set) inline
Definition at line 601 of file qsvgstyle_p.h.
Referenced by parseBaseGradient(), and parseStopNode().
     {
         m_gradientStopsSet = set;
     }
setMatrix()
void QSvgGradientStyle::setMatrix (const QMatrix & matrix)
Definition at line 436 of file qsvgstyle.cpp.
Referenced by parseBaseGradient().
 {
     m_matrix = mat;
 }
setStopLink()
void QSvgGradientStyle::setStopLink (const QString & link, QSvgTinyDocument * doc)
Definition at line 931 of file qsvgstyle.cpp.
Referenced by parseBaseGradient().
 {
     m_link = link;
     m_doc  = doc;
 }
stopLink()
QString QSvgGradientStyle::stopLink () const inline
Definition at line 582 of file qsvgstyle_p.h.
Referenced by parseBaseGradient().
 { return m_link; }
type()
QSvgStyleProperty::Type QSvgGradientStyle::type () const virtual
Implements QSvgStyleProperty.
Definition at line 487 of file qsvgstyle.cpp.
 {
     return GRADIENT;
 }
Properties
m_doc
QSvgTinyDocument* QSvgGradientStyle::m_doc private
Definition at line 611 of file qsvgstyle_p.h.
m_gradient
QGradient* QSvgGradientStyle::m_gradient private
Definition at line 608 of file qsvgstyle_p.h.
Referenced by brush().
m_gradientStopsSet
bool QSvgGradientStyle::m_gradientStopsSet private
Definition at line 613 of file qsvgstyle_p.h.
Referenced by brush().
m_link
QString QSvgGradientStyle::m_link private
Definition at line 612 of file qsvgstyle_p.h.
Referenced by brush().
m_matrix
QMatrix QSvgGradientStyle::m_matrix private
Definition at line 609 of file qsvgstyle_p.h.
Referenced by brush(), and setMatrix().
The documentation for this class was generated from the following files:
/src/svg/qsvgstyle_p.h
/src/svg/qsvgstyle.cpp