Qt 4.8: QTextEditPrivate Class Reference
QTextEditPrivate Class Reference
#include <qtextedit_p.h>
Public Functions
void _q_adjustScrollbars ()
void _q_currentCharFormatChanged (const QTextCharFormat &format)
void _q_ensureVisible (const QRectF &rect)
void _q_repaintContents (const QRectF &contentsRect)
void createAutoBulletList ()
int horizontalOffset () const
void init (const QString &html=QString())
QPoint mapToContents (const QPoint &point) const
void pageUpDown (QTextCursor::MoveOperation op, QTextCursor::MoveMode moveMode)
void paint (QPainter *p, QPaintEvent *e)
QTextEditPrivate ()
void relayoutDocument ()
virtual QUrl resolveUrl (const QUrl &url) const
void sendControlEvent (QEvent *e)
void updateDefaultTextOption ()
int verticalOffset () const
Public Functions inherited from QAbstractScrollAreaPrivate
void _q_hslide (int)
void _q_showOrHideScrollBars ()
void _q_vslide (int)
virtual QPoint contentsOffset () const
void init ()
void layoutChildren ()
QAbstractScrollAreaPrivate ()
void replaceScrollBar (QScrollBar *scrollBar, Qt::Orientation orientation)
virtual void scrollBarPolicyChanged (Qt::Orientation, Qt::ScrollBarPolicy)
void setSingleFingerPanEnabled (bool on=true)
bool viewportEvent (QEvent *event)
Public Functions inherited from QFramePrivate
void init ()
QFramePrivate ()
void updateFrameWidth ()
Updated the frameWidth parameter.
void updateStyledFrameWidths ()
Updates the frame widths from the style.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QString anchorToScrollToWhenVisible
QTextEdit::AutoFormatting autoFormatting
QPoint autoScrollDragPos
QBasicTimer autoScrollTimer
uint clickCausedFocus: 1
QTextControl * control
uint ignoreAutomaticScrollbarAdjustment: 1
uint inDrag: 1
QTextEdit::LineWrapMode lineWrap
int lineWrapColumnOrWidth
uint preferRichText: 1
uint showCursorOnInitialShow: 1
bool tabChangesFocus
Qt::TextFormat textFormat
QTextOption::WrapMode wordWrap
Public Variables inherited from QAbstractScrollAreaPrivate
int bottom
QRect cornerPaintingRect
QWidget * cornerWidget
QScrollBar * hbar
Qt::ScrollBarPolicy hbarpolicy
int left
QRect reverseCornerPaintingRect
int right
QAbstractScrollAreaScrollBarContainer * scrollBarContainers [Qt::Vertical+1]
bool singleFingerPanEnabled
int top
QScrollBar * vbar
Qt::ScrollBarPolicy vbarpolicy
QWidget * viewport
QScopedPointer< QObject > viewportFilter
int xoffset
int yoffset
Public Variables inherited from QFramePrivate
short bottomFrameWidth
int frameStyle
short frameWidth
QRect frect
short leftFrameWidth
short lineWidth
short midLineWidth
short rightFrameWidth
short topFrameWidth
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 73 of file qtextedit_p.h.
Constructors and Destructors
QTextEditPrivate()
QTextEditPrivate::QTextEditPrivate ()
Definition at line 108 of file qtextedit.cpp.
     : control(0),
       autoFormatting(QTextEdit::AutoNone), tabChangesFocus(false),
       lineWrap(QTextEdit::WidgetWidth), lineWrapColumnOrWidth(0),
       wordWrap(QTextOption::WrapAtWordBoundaryOrAnywhere), clickCausedFocus(0),
       textFormat(Qt::AutoText)
 {
     ignoreAutomaticScrollbarAdjustment = false;
     preferRichText = false;
     showCursorOnInitialShow = true;
     inDrag = false;
 }
Functions
_q_adjustScrollbars()
void QTextEditPrivate::_q_adjustScrollbars ()
Definition at line 258 of file qtextedit.cpp.
Referenced by _q_ensureVisible(), init(), and mapToContents().
 {
     if (ignoreAutomaticScrollbarAdjustment)
         return;
     ignoreAutomaticScrollbarAdjustment = true; // avoid recursion, #106108
     QSize viewportSize = viewport->size();
     QSize docSize = documentSize(control);
     // due to the recursion guard we have to repeat this step a few times,
     // as adding/removing a scroll bar will cause the document or viewport
     // size to change
     // ideally we should loop until the viewport size and doc size stabilize,
     // but in corner cases they might fluctuate, so we need to limit the
     // number of iterations
     for (int i = 0; i < 4; ++i) {
         hbar->setRange(0, docSize.width() - viewportSize.width());
         hbar->setPageStep(viewportSize.width());
         vbar->setRange(0, docSize.height() - viewportSize.height());
         vbar->setPageStep(viewportSize.height());
         // if we are in left-to-right mode widening the document due to
         // lazy layouting does not require a repaint. If in right-to-left
         // the scroll bar has the value zero and it visually has the maximum
         // value (it is visually at the right), then widening the document
         // keeps it at value zero but visually adjusts it to the new maximum
         // on the right, hence we need an update.
         if (q_func()->isRightToLeft())
             viewport->update();
         _q_showOrHideScrollBars();
         const QSize oldViewportSize = viewportSize;
         const QSize oldDocSize = docSize;
         // make sure the document is layouted if the viewport width changes
         viewportSize = viewport->size();
         if (viewportSize.width() != oldViewportSize.width())
             relayoutDocument();
         docSize = documentSize(control);
         if (viewportSize == oldViewportSize && docSize == oldDocSize)
             break;
     }
     ignoreAutomaticScrollbarAdjustment = false;
 }
_q_currentCharFormatChanged()
void QTextEditPrivate::_q_currentCharFormatChanged (const QTextCharFormat & format)
Definition at line 1546 of file qtextedit.cpp.
Referenced by init(), and sendControlEvent().
 {
     Q_Q(QTextEdit);
     emit q->currentCharFormatChanged(fmt);
 #ifdef QT3_SUPPORT
     // compat signals
     emit q->currentFontChanged(fmt.font());
     emit q->currentColorChanged(fmt.foreground().color());
 #endif
 }
_q_ensureVisible()
void QTextEditPrivate::_q_ensureVisible (const QRectF & rect)
Definition at line 308 of file qtextedit.cpp.
Referenced by init(), and mapToContents().
 {
     const QRect rect = _rect.toRect();
     if ((vbar->isVisible() && vbar->maximum() < rect.bottom())
         || (hbar->isVisible() && hbar->maximum() < rect.right()))
         _q_adjustScrollbars();
     const int visibleWidth = viewport->width();
     const int visibleHeight = viewport->height();
     const bool rtl = q_func()->isRightToLeft();
     if (rect.x() < horizontalOffset()) {
         if (rtl)
             hbar->setValue(hbar->maximum() - rect.x());
         else
             hbar->setValue(rect.x());
     } else if (rect.x() + rect.width() > horizontalOffset() + visibleWidth) {
         if (rtl)
             hbar->setValue(hbar->maximum() - (rect.x() + rect.width() - visibleWidth));
         else
             hbar->setValue(rect.x() + rect.width() - visibleWidth);
     }
     if (rect.y() < verticalOffset())
         vbar->setValue(rect.y());
     else if (rect.y() + rect.height() > verticalOffset() + visibleHeight)
         vbar->setValue(rect.y() + rect.height() - visibleHeight);
 }
_q_repaintContents()
void QTextEditPrivate::_q_repaintContents (const QRectF & contentsRect)
Definition at line 193 of file qtextedit.cpp.
Referenced by init().
 {
     if (!contentsRect.isValid()) {
         viewport->update();
         return;
     }
     const int xOffset = horizontalOffset();
     const int yOffset = verticalOffset();
     const QRectF visibleRect(xOffset, yOffset, viewport->width(), viewport->height());
     QRect r = contentsRect.intersected(visibleRect).toAlignedRect();
     if (r.isEmpty())
         return;
     r.translate(-xOffset, -yOffset);
     viewport->update(r);
 }
createAutoBulletList()
void QTextEditPrivate::createAutoBulletList ()
Definition at line 121 of file qtextedit.cpp.
Referenced by mapToContents().
 {
     QTextCursor cursor = control->textCursor();
     cursor.beginEditBlock();
     QTextBlockFormat blockFmt = cursor.blockFormat();
     QTextListFormat listFmt;
     listFmt.setStyle(QTextListFormat::ListDisc);
     listFmt.setIndent(blockFmt.indent() + 1);
     blockFmt.setIndent(0);
     cursor.setBlockFormat(blockFmt);
     cursor.createList(listFmt);
     cursor.endEditBlock();
     control->setTextCursor(cursor);
 }
horizontalOffset()
int QTextEditPrivate::horizontalOffset () const inline
Definition at line 93 of file qtextedit_p.h.
Referenced by _q_ensureVisible(), _q_repaintContents(), mapToContents(), and sendControlEvent().
     { return q_func()->isRightToLeft() ? (hbar->maximum() - hbar->value()) : hbar->value(); }
init()
void QTextEditPrivate::init (const QString & html = QString())
Definition at line 141 of file qtextedit.cpp.
 {
     Q_Q(QTextEdit);
     control = new QTextEditControl(q);
     control->setPalette(q->palette());
     QObject::connect(control, SIGNAL(microFocusChanged()), q, SLOT(updateMicroFocus()));
     QObject::connect(control, SIGNAL(documentSizeChanged(QSizeF)), q, SLOT(_q_adjustScrollbars()));
     QObject::connect(control, SIGNAL(updateRequest(QRectF)), q, SLOT(_q_repaintContents(QRectF)));
     QObject::connect(control, SIGNAL(visibilityRequest(QRectF)), q, SLOT(_q_ensureVisible(QRectF)));
     QObject::connect(control, SIGNAL(currentCharFormatChanged(QTextCharFormat)),
                      q, SLOT(_q_currentCharFormatChanged(QTextCharFormat)));
     QObject::connect(control, SIGNAL(textChanged()), q, SIGNAL(textChanged()));
     QObject::connect(control, SIGNAL(undoAvailable(bool)), q, SIGNAL(undoAvailable(bool)));
     QObject::connect(control, SIGNAL(redoAvailable(bool)), q, SIGNAL(redoAvailable(bool)));
     QObject::connect(control, SIGNAL(copyAvailable(bool)), q, SIGNAL(copyAvailable(bool)));
     QObject::connect(control, SIGNAL(selectionChanged()), q, SIGNAL(selectionChanged()));
     QObject::connect(control, SIGNAL(cursorPositionChanged()), q, SIGNAL(cursorPositionChanged()));
     QObject::connect(control, SIGNAL(textChanged()), q, SLOT(updateMicroFocus()));
     QTextDocument *doc = control->document();
     // set a null page size initially to avoid any relayouting until the textedit
     // is shown. relayoutDocument() will take care of setting the page size to the
     // viewport dimensions later.
     doc->setPageSize(QSize(0, 0));
     doc->documentLayout()->setPaintDevice(viewport);
     doc->setDefaultFont(q->font());
     doc->setUndoRedoEnabled(false); // flush undo buffer.
     doc->setUndoRedoEnabled(true);
     if (!html.isEmpty())
         control->setHtml(html);
     hbar->setSingleStep(20);
     vbar->setSingleStep(20);
     viewport->setBackgroundRole(QPalette::Base);
     q->setAcceptDrops(true);
     q->setFocusPolicy(Qt::WheelFocus);
     q->setAttribute(Qt::WA_KeyCompression);
     q->setAttribute(Qt::WA_InputMethodEnabled);
 #ifndef QT_NO_CURSOR
     viewport->setCursor(Qt::IBeamCursor);
 #endif
 #ifdef Q_WS_WIN
     setSingleFingerPanEnabled(true);
 #endif
 }
mapToContents()
QPoint QTextEditPrivate::mapToContents (const QPoint & point) const inline
Definition at line 83 of file qtextedit_p.h.
     { return QPoint(point.x() + horizontalOffset(), point.y() + verticalOffset()); }
pageUpDown()
void QTextEditPrivate::pageUpDown (QTextCursor::MoveOperation op, QTextCursor::MoveMode moveMode)
Definition at line 211 of file qtextedit.cpp.
Referenced by mapToContents().
 {
     QTextCursor cursor = control->textCursor();
     bool moved = false;
     qreal lastY = control->cursorRect(cursor).top();
     qreal distance = 0;
     // move using movePosition to keep the cursor's x
     do {
         qreal y = control->cursorRect(cursor).top();
         distance += qAbs(y - lastY);
         lastY = y;
         moved = cursor.movePosition(op, moveMode);
     } while (moved && distance < viewport->height());
     if (moved) {
         if (op == QTextCursor::Up) {
             cursor.movePosition(QTextCursor::Down, moveMode);
             vbar->triggerAction(QAbstractSlider::SliderPageStepSub);
         } else {
             cursor.movePosition(QTextCursor::Up, moveMode);
             vbar->triggerAction(QAbstractSlider::SliderPageStepAdd);
         }
     }
     control->setTextCursor(cursor);
 }
paint()
void QTextEditPrivate::paint (QPainter * p, QPaintEvent * e)
Definition at line 1508 of file qtextedit.cpp.
 {
     const int xOffset = horizontalOffset();
     const int yOffset = verticalOffset();
     QRect r = e->rect();
     p->translate(-xOffset, -yOffset);
     r.translate(xOffset, yOffset);
     QTextDocument *doc = control->document();
     QTextDocumentLayout *layout = qobject_cast<QTextDocumentLayout *>(doc->documentLayout());
     // the layout might need to expand the root frame to
     // the viewport if NoWrap is set
     if (layout)
         layout->setViewport(viewport->rect());
     control->drawContents(p, r, q_func());
     if (layout)
         layout->setViewport(QRect());
 }
relayoutDocument()
void QTextEditPrivate::relayoutDocument ()
Definition at line 1434 of file qtextedit.cpp.
Referenced by _q_adjustScrollbars(), and mapToContents().
 {
     QTextDocument *doc = control->document();
     QAbstractTextDocumentLayout *layout = doc->documentLayout();
     if (QTextDocumentLayout *tlayout = qobject_cast<QTextDocumentLayout *>(layout)) {
         if (lineWrap == QTextEdit::FixedColumnWidth)
             tlayout->setFixedColumnWidth(lineWrapColumnOrWidth);
         else
             tlayout->setFixedColumnWidth(-1);
     }
     QTextDocumentLayout *tlayout = qobject_cast<QTextDocumentLayout *>(layout);
     QSize lastUsedSize;
     if (tlayout)
         lastUsedSize = tlayout->dynamicDocumentSize().toSize();
     else
         lastUsedSize = layout->documentSize().toSize();
     // ignore calls to _q_adjustScrollbars caused by an emission of the
     // usedSizeChanged() signal in the layout, as we're calling it
     // later on our own anyway (or deliberately not) .
     const bool oldIgnoreScrollbarAdjustment = ignoreAutomaticScrollbarAdjustment;
     ignoreAutomaticScrollbarAdjustment = true;
     int width = viewport->width();
     if (lineWrap == QTextEdit::FixedPixelWidth)
         width = lineWrapColumnOrWidth;
     else if (lineWrap == QTextEdit::NoWrap) {
         QVariant alignmentProperty = doc->documentLayout()->property("contentHasAlignment");
         if (alignmentProperty.type() == QVariant::Bool && !alignmentProperty.toBool()) {
             width = 0;
         }
     }
     doc->setPageSize(QSize(width, -1));
     if (tlayout)
         tlayout->ensureLayouted(verticalOffset() + viewport->height());
     ignoreAutomaticScrollbarAdjustment = oldIgnoreScrollbarAdjustment;
     QSize usedSize;
     if (tlayout)
         usedSize = tlayout->dynamicDocumentSize().toSize();
     else
         usedSize = layout->documentSize().toSize();
     // this is an obscure situation in the layout that can happen:
     // if a character at the end of a line is the tallest one and therefore
     // influencing the total height of the line and the line right below it
     // is always taller though, then it can happen that if due to line breaking
     // that tall character wraps into the lower line the document not only shrinks
     // horizontally (causing the character to wrap in the first place) but also
     // vertically, because the original line is now smaller and the one below kept
     // its size. So a layout with less width _can_ take up less vertical space, too.
     // If the wider case causes a vertical scroll bar to appear and the narrower one
     // (narrower because the vertical scroll bar takes up horizontal space)) to disappear
     // again then we have an endless loop, as _q_adjustScrollBars sets new ranges on the
     // scroll bars, the QAbstractScrollArea will find out about it and try to show/hide
     // the scroll bars again. That's why we try to detect this case here and break out.
     //
     // (if you change this please also check the layoutingLoop() testcase in
     // QTextEdit's autotests)
     if (lastUsedSize.isValid()
         && !vbar->isHidden()
         && viewport->width() < lastUsedSize.width()
         && usedSize.height() < lastUsedSize.height()
         && usedSize.height() <= viewport->height())
         return;
     _q_adjustScrollbars();
 }
resolveUrl()
virtual QUrl QTextEditPrivate::resolveUrl (const QUrl & url) const inline virtual
Reimplemented in QTextBrowserPrivate.
Definition at line 106 of file qtextedit_p.h.
     { return url; }
sendControlEvent()
void QTextEditPrivate::sendControlEvent (QEvent * e) inline
Definition at line 98 of file qtextedit_p.h.
     { control->processEvent(e, QPointF(horizontalOffset(), verticalOffset()), viewport); }
updateDefaultTextOption()
void QTextEditPrivate::updateDefaultTextOption ()
Definition at line 1557 of file qtextedit.cpp.
Referenced by sendControlEvent().
 {
     QTextDocument *doc = control->document();
     QTextOption opt = doc->defaultTextOption();
     QTextOption::WrapMode oldWrapMode = opt.wrapMode();
     if (lineWrap == QTextEdit::NoWrap)
         opt.setWrapMode(QTextOption::NoWrap);
     else
         opt.setWrapMode(wordWrap);
     if (opt.wrapMode() != oldWrapMode)
         doc->setDefaultTextOption(opt);
 }
verticalOffset()
int QTextEditPrivate::verticalOffset () const inline
Definition at line 95 of file qtextedit_p.h.
Referenced by _q_ensureVisible(), _q_repaintContents(), mapToContents(), and sendControlEvent().
     { return vbar->value(); }
Properties
anchorToScrollToWhenVisible
QString QTextEditPrivate::anchorToScrollToWhenVisible
Definition at line 130 of file qtextedit_p.h.
autoFormatting
QTextEdit::AutoFormatting QTextEditPrivate::autoFormatting
Definition at line 111 of file qtextedit_p.h.
autoScrollDragPos
QPoint QTextEditPrivate::autoScrollDragPos
Definition at line 115 of file qtextedit_p.h.
autoScrollTimer
QBasicTimer QTextEditPrivate::autoScrollTimer
Definition at line 114 of file qtextedit_p.h.
clickCausedFocus
uint QTextEditPrivate::clickCausedFocus
Definition at line 125 of file qtextedit_p.h.
control
QTextControl* QTextEditPrivate::control
Definition at line 109 of file qtextedit_p.h.
Referenced by _q_adjustScrollbars(), createAutoBulletList(), QTextBrowserPrivate::createHistoryEntry(), QTextBrowserPrivate::init(), init(), pageUpDown(), QTextBrowserPrivate::restoreHistoryEntry(), sendControlEvent(), and QTextBrowserPrivate::setSource().
ignoreAutomaticScrollbarAdjustment
uint QTextEditPrivate::ignoreAutomaticScrollbarAdjustment
Definition at line 121 of file qtextedit_p.h.
Referenced by _q_adjustScrollbars(), and QTextEditPrivate().
inDrag
uint QTextEditPrivate::inDrag
Definition at line 124 of file qtextedit_p.h.
Referenced by QTextEditPrivate().
lineWrap
QTextEdit::LineWrapMode QTextEditPrivate::lineWrap
Definition at line 117 of file qtextedit_p.h.
lineWrapColumnOrWidth
int QTextEditPrivate::lineWrapColumnOrWidth
Definition at line 118 of file qtextedit_p.h.
preferRichText
uint QTextEditPrivate::preferRichText
Definition at line 122 of file qtextedit_p.h.
Referenced by QTextEditPrivate().
showCursorOnInitialShow
uint QTextEditPrivate::showCursorOnInitialShow
Definition at line 123 of file qtextedit_p.h.
Referenced by QTextEditPrivate().
tabChangesFocus
bool QTextEditPrivate::tabChangesFocus
Definition at line 112 of file qtextedit_p.h.
textFormat
Qt::TextFormat QTextEditPrivate::textFormat
Definition at line 128 of file qtextedit_p.h.
wordWrap
QTextOption::WrapMode QTextEditPrivate::wordWrap
Definition at line 119 of file qtextedit_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qtextedit_p.h
/src/gui/widgets/qtextedit.cpp