Qt 4.8: QXlibScreen Class Reference
QXlibScreen Class Reference
#include <qxlibscreen.h>
Public Slots
void eventDispatcher ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
unsigned long blackPixel ()
Visual * defaultVisual () const
int depth () const
Reimplement in subclass to return current depth of the screen.
QXlibDisplay * display () const
QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
QImage grabWindow (Window window, int x, int y, int w, int h)
bool handleEvent (XEvent *xe)
QXlibKeyboard * keyboard () const
QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
QXlibScreen ()
Window rootWindow ()
bool waitForClipboardEvent (Window win, int type, XEvent *event, int timeout)
unsigned long whitePixel ()
int xScreenNumber () const
~QXlibScreen ()
Public Functions inherited from QPlatformScreen
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual void setDirty (const QRect &)
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QXlibScreen * testLiteScreenForWidget (QWidget *widget)
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Functions
void handleSelectionRequest (XEvent *event)
Properties
QXlibCursor * mCursor
int mDepth
QXlibDisplay * mDisplay
QImage::Format mFormat
QRect mGeometry
QXlibKeyboard * mKeyboard
QSize mPhysicalSize
int mScreen
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 54 of file qxlibscreen.h.
Constructors and Destructors
QXlibScreen()
QXlibScreen::QXlibScreen ()
Definition at line 192 of file qxlibscreen.cpp.
         : mFormat(QImage::Format_RGB32)
 #if !defined(QT_NO_OPENGL) && defined(QT_OPENGL_ES_2)
         , mEGLDisplay(0)
 #endif
 {
     char *display_name = getenv("DISPLAY");
     Display *display = XOpenDisplay(display_name);
     mDisplay = new QXlibDisplay(display);
 #ifndef DONT_USE_MIT_SHM
     int MIT_SHM_extension_supported = XShmQueryExtension (mDisplay->nativeDisplay());
     Q_ASSERT(MIT_SHM_extension_supported == True);
 #endif
     original_x_errhandler = XSetErrorHandler(qt_x_errhandler);
     if (qgetenv("DO_X_SYNCHRONIZE").toInt())
         XSynchronize(mDisplay->nativeDisplay(), true);
     mScreen = DefaultScreen(mDisplay->nativeDisplay());
     XSelectInput(mDisplay->nativeDisplay(),rootWindow(), KeymapStateMask | EnterWindowMask | LeaveWindowMask | PropertyChangeMask);
     int width = DisplayWidth(mDisplay->nativeDisplay(), mScreen);
     int height = DisplayHeight(mDisplay->nativeDisplay(), mScreen);
     mGeometry = QRect(0,0,width,height);
     int physicalWidth = DisplayWidthMM(mDisplay->nativeDisplay(), mScreen);
     int physicalHeight = DisplayHeightMM(mDisplay->nativeDisplay(), mScreen);
     mPhysicalSize = QSize(physicalWidth,physicalHeight);
     int xSocketNumber = XConnectionNumber(mDisplay->nativeDisplay());
     mDepth = DefaultDepth(mDisplay->nativeDisplay(),mScreen);
 #ifdef MYX11_DEBUG
     qDebug() << "X socket:"<< xSocketNumber;
 #endif
     QSocketNotifier *sock = new QSocketNotifier(xSocketNumber, QSocketNotifier::Read, this);
     connect(sock, SIGNAL(activated(int)), this, SLOT(eventDispatcher()));
     mCursor = new QXlibCursor(this);
     mKeyboard = new QXlibKeyboard(this);
 }
~QXlibScreen()
QXlibScreen::~QXlibScreen ()
Definition at line 235 of file qxlibscreen.cpp.
 {
     delete mCursor;
     delete mDisplay;
 }
Functions
blackPixel()
unsigned long QXlibScreen::blackPixel ()
Definition at line 246 of file qxlibscreen.cpp.
Referenced by QXlibClipboard::owner(), physicalSize(), QXlibWindow::QXlibWindow(), and QXlibClipboard::requestor().
 {
     return BlackPixel(mDisplay->nativeDisplay(), mScreen);
 }
defaultVisual()
Visual * QXlibScreen::defaultVisual () const
Definition at line 471 of file qxlibscreen.cpp.
Referenced by physicalSize(), and QXlibWindow::QXlibWindow().
 {
     return DefaultVisual(display()->nativeDisplay(), xScreenNumber());
 }
depth()
int QXlibScreen::depth () const inline virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 63 of file qxlibscreen.h.
Referenced by QXlibWindow::correctColorBuffers(), and QXlibWindow::QXlibWindow().
 { return mDepth; }
display()
QXlibDisplay * QXlibScreen::display () const
Definition at line 461 of file qxlibscreen.cpp.
Referenced by QXlibKeyboard::changeLayout(), QXlibClipboard::clipboardReadIncrementalProperty(), QXlibClipboard::clipboardReadProperty(), QXlibWindow::createGC(), defaultVisual(), QXlibWindow::doSizeHints(), QXlibClipboardMime::empty(), QXlibWindowSurface::flush(), QXlibClipboardMime::formats_sys(), QXlibClipboard::getDataInFormat(), QXlibWindow::getMWMHints(), QXlibWindow::getNetWmState(), QXlibIntegration::hasOpenGL(), QTestLiteStaticInfoPrivate::initializeAllAtoms(), QTestLiteStaticInfoPrivate::initializeSupportedAtoms(), QXlibWindow::lower(), QXlibClipboard::owner(), physicalSize(), QGLXContext::QGLXContext(), QXlibScreen(), QXlibWindow::QXlibWindow(), QXlibWindow::raise(), QXlibWindow::requestActivateWindow(), QXlibClipboard::requestor(), QXlibWindowSurface::resizeShmImage(), QTestLiteStaticInfoPrivate::resolveXFixes(), QXlibWindow::setCursor(), QXlibWindow::setGeometry(), QXlibClipboard::setMimeData(), QXlibWindow::setMWMHints(), QXlibClipboard::setOwner(), QXlibWindow::setParent(), QXlibClipboard::setRequestor(), QXlibWindow::setVisible(), QXlibWindow::setWindowFlags(), QXlibWindow::setWindowTitle(), and QXlibWindow::~QXlibWindow().
 {
     return mDisplay;
 }
eventDispatcher
void QXlibScreen::eventDispatcher () slot
Definition at line 395 of file qxlibscreen.cpp.
Referenced by physicalSize(), and QXlibScreen().
 {
         ulong marker = XNextRequest(mDisplay->nativeDisplay());
     //    int i = 0;
         while (XPending(mDisplay->nativeDisplay())) {
             XEvent event;
             XNextEvent(mDisplay->nativeDisplay(), &event);
             /* done = */
             handleEvent(&event);
             if (event.xany.serial >= marker) {
     #ifdef MYX11_DEBUG
                 qDebug() << "potential livelock averted";
     #endif
     #if 0
                 if (XEventsQueued(mDisplay->nativeDisplay(), QueuedAfterFlush)) {
                     qDebug() << "   with events queued";
                     QTimer::singleShot(0, this, SLOT(eventDispatcher()));
                 }
     #endif
                 break;
             }
         }
 }
format()
QImage::Format QXlibScreen::format () const inline virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 64 of file qxlibscreen.h.
 { return mFormat; }
geometry()
QRect QXlibScreen::geometry () const inline virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 62 of file qxlibscreen.h.
 { return mGeometry; }
grabWindow()
QImage QXlibScreen::grabWindow (Window window, int x, int y, int w, int h)
Definition at line 420 of file qxlibscreen.cpp.
Referenced by QXlibIntegration::grabWindow(), and physicalSize().
 {
     if (w == 0 || h ==0)
         return QImage();
     //WinId 0 means the desktop widget
     if (!window)
         window = rootWindow();
     XWindowAttributes window_attr;
     if (!XGetWindowAttributes(mDisplay->nativeDisplay(), window, &window_attr))
         return QImage();
     if (w < 0)
         w = window_attr.width - x;
     if (h < 0)
         h = window_attr.height - y;
     // Ideally, we should also limit ourselves to the screen area, but the Qt docs say
     // that it's "unsafe" to go outside the screen, so we can ignore that problem.
     //We're definitely not optimizing for speed...
     XImage *xi = XGetImage(mDisplay->nativeDisplay(), window, x, y, w, h, AllPlanes, ZPixmap);
     if (!xi)
         return QImage();
     //taking a copy to make sure we have ownership -- not fast
     QImage result = QImage( (uchar*) xi->data, xi->width, xi->height, xi->bytes_per_line, QImage::Format_RGB32 ).copy();
     XDestroyImage(xi);
     return result;
 }
handleEvent()
bool QXlibScreen::handleEvent (XEvent * xe)
Definition at line 263 of file qxlibscreen.cpp.
Referenced by eventDispatcher(), physicalSize(), and waitForClipboardEvent().
 {
     int quit = false;
     QXlibWindow *platformWindow = 0;
     QWidget *widget = QWidget::find(xe->xany.window);
     if (widget) {
         platformWindow = static_cast<QXlibWindow *>(widget->platformWindow());
     }
     Atom wmProtocolsAtom = QXlibStatic::atom(QXlibStatic::WM_PROTOCOLS);
     Atom wmDeleteWindowAtom = QXlibStatic::atom(QXlibStatic::WM_DELETE_WINDOW);
     switch (xe->type) {
     case ClientMessage:
         if (xe->xclient.format == 32 && xe->xclient.message_type == wmProtocolsAtom) {
             Atom a = xe->xclient.data.l[0];
             if (a == wmDeleteWindowAtom)
                 platformWindow->handleCloseEvent();
         }
         break;
     case Expose:
         if (platformWindow)
             if (xe->xexpose.count == 0)
                 platformWindow->paintEvent();
         break;
     case ConfigureNotify:
         if (platformWindow)
             platformWindow->resizeEvent(&xe->xconfigure);
         break;
     case ButtonPress:
         if (platformWindow)
             platformWindow->mousePressEvent(&xe->xbutton);
         break;
     case ButtonRelease:
         if (platformWindow)
             platformWindow->handleMouseEvent(QEvent::MouseButtonRelease, &xe->xbutton);
         break;
     case MotionNotify:
         if (platformWindow)
             platformWindow->handleMouseEvent(QEvent::MouseMove, &xe->xbutton);
         break;
         case XKeyPress:
         mKeyboard->handleKeyEvent(widget,QEvent::KeyPress, &xe->xkey);
         break;
     case XKeyRelease:
         mKeyboard->handleKeyEvent(widget,QEvent::KeyRelease, &xe->xkey);
         break;
     case EnterNotify:
         if (platformWindow)
             platformWindow->handleEnterEvent();
         break;
     case LeaveNotify:
         if (platformWindow)
             platformWindow->handleLeaveEvent();
         break;
     case XFocusIn:
         if (platformWindow)
             platformWindow->handleFocusInEvent();
         break;
     case XFocusOut:
         if (platformWindow)
             platformWindow->handleFocusOutEvent();
         break;
     case PropertyNotify:
         break;
     case SelectionClear:
         qDebug() << "Selection Clear!!!";
         break;
     case SelectionRequest:
         handleSelectionRequest(xe);
         break;
     case SelectionNotify:
         qDebug() << "Selection Notify!!!!";
         break;
     default:
 #ifdef MYX11_DEBUG
         qDebug() << hex << xe->xany.window << "Other X event" << xe->type;
 #endif
         break;
     }
     return quit;
 }
handleSelectionRequest()
void QXlibScreen::handleSelectionRequest (XEvent * event) private
Definition at line 481 of file qxlibscreen.cpp.
Referenced by handleEvent(), and physicalSize().
 {
     QPlatformIntegration *integration = QApplicationPrivate::platformIntegration();
     QXlibClipboard *clipboard = static_cast<QXlibClipboard *>(integration->clipboard());
     clipboard->handleSelectionRequest(event);
 }
keyboard()
QXlibKeyboard * QXlibScreen::keyboard () const
Definition at line 476 of file qxlibscreen.cpp.
Referenced by QXlibWindow::handleMouseEvent(), and physicalSize().
 {
     return mKeyboard;
 }
physicalSize()
QSize QXlibScreen::physicalSize () const inline virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented from QPlatformScreen.
Definition at line 65 of file qxlibscreen.h.
 { return mPhysicalSize; }
rootWindow()
Window QXlibScreen::rootWindow ()
Definition at line 241 of file qxlibscreen.cpp.
Referenced by QXlibCursor::createCursorBitmap(), QXlibIntegration::grabWindow(), grabWindow(), QTestLiteStaticInfoPrivate::initializeSupportedAtoms(), QXlibClipboard::owner(), physicalSize(), QXlibScreen(), QXlibWindow::QXlibWindow(), and QXlibClipboard::requestor().
 {
     return RootWindow(mDisplay->nativeDisplay(), mScreen);
 }
testLiteScreenForWidget()
QXlibScreen * QXlibScreen::testLiteScreenForWidget (QWidget * widget) static
Definition at line 455 of file qxlibscreen.cpp.
Referenced by QXlibWindowSurface::flush(), QXlibIntegration::grabWindow(), physicalSize(), and QXlibWindowSurface::resizeShmImage().
 {
     QPlatformScreen *platformScreen = platformScreenForWidget(widget);
     return static_cast<QXlibScreen *>(platformScreen);
 }
waitForClipboardEvent()
bool QXlibScreen::waitForClipboardEvent (Window win, int type, XEvent * event, int timeout)
Definition at line 371 of file qxlibscreen.cpp.
Referenced by physicalSize().
 {
     QElapsedTimer timer;
     timer.start();
     do {
         if (XCheckTypedWindowEvent(mDisplay->nativeDisplay(),win,type,event))
             return true;
         // process other clipboard events, since someone is probably requesting data from us
         XEvent e;
         if (XCheckIfEvent(mDisplay->nativeDisplay(), &e, checkForClipboardEvents, 0))
             handleEvent(&e);
         mDisplay->flush();
         // sleep 50 ms, so we don't use up CPU cycles all the time.
         struct timeval usleep_tv;
         usleep_tv.tv_sec = 0;
         usleep_tv.tv_usec = 50000;
         select(0, 0, 0, 0, &usleep_tv);
     } while (timer.elapsed() < timeout);
     return false;
 }
whitePixel()
unsigned long QXlibScreen::whitePixel ()
Definition at line 251 of file qxlibscreen.cpp.
Referenced by QXlibClipboard::owner(), physicalSize(), QXlibWindow::QXlibWindow(), and QXlibClipboard::requestor().
 {
     return WhitePixel(mDisplay->nativeDisplay(), mScreen);
 }
xScreenNumber()
int QXlibScreen::xScreenNumber () const
Definition at line 466 of file qxlibscreen.cpp.
Referenced by defaultVisual(), physicalSize(), QGLXContext::QGLXContext(), and QXlibWindow::QXlibWindow().
 {
     return mScreen;
 }
Properties
mCursor
QXlibCursor* QXlibScreen::mCursor private
Definition at line 100 of file qxlibscreen.h.
Referenced by QXlibScreen(), and ~QXlibScreen().
mDepth
int QXlibScreen::mDepth private
Definition at line 98 of file qxlibscreen.h.
Referenced by depth(), and QXlibScreen().
mDisplay
QXlibDisplay* QXlibScreen::mDisplay private
Definition at line 103 of file qxlibscreen.h.
Referenced by blackPixel(), display(), eventDispatcher(), grabWindow(), QXlibScreen(), rootWindow(), waitForClipboardEvent(), whitePixel(), and ~QXlibScreen().
mFormat
QImage::Format QXlibScreen::mFormat private
Definition at line 99 of file qxlibscreen.h.
Referenced by format().
mGeometry
QRect QXlibScreen::mGeometry private
Definition at line 96 of file qxlibscreen.h.
Referenced by geometry(), and QXlibScreen().
mKeyboard
QXlibKeyboard* QXlibScreen::mKeyboard private
Definition at line 101 of file qxlibscreen.h.
Referenced by handleEvent(), keyboard(), and QXlibScreen().
mPhysicalSize
QSize QXlibScreen::mPhysicalSize private
Definition at line 97 of file qxlibscreen.h.
Referenced by physicalSize(), and QXlibScreen().
mScreen
int QXlibScreen::mScreen private
Definition at line 107 of file qxlibscreen.h.
Referenced by blackPixel(), QXlibScreen(), rootWindow(), whitePixel(), and xScreenNumber().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xlib/qxlibscreen.h
/src/plugins/platforms/xlib/qxlibscreen.cpp