Qt 4.8: QPatternist::XsdAttributeGroup Class Reference
QPatternist::XsdAttributeGroup Class Reference
XML Schema Processing
Represents the XSD attributeGroup object.
#include <qxsdattributegroup_p.h>
Public Types
typedef QList< XsdAttributeGroup::Ptr > List
typedef QExplicitlySharedDataPointer< XsdAttributeGroup > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
void addAttributeUse (const XsdAttributeUse::Ptr &use)
XsdAttributeUse::List attributeUses () const
void setAttributeUses (const XsdAttributeUse::List &uses)
void setWildcard (const XsdWildcard::Ptr &wildcard)
XsdWildcard::Ptr wildcard () const
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
XsdAttributeUse::List m_attributeUses
XsdWildcard::Ptr m_wildcard
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents the XSD attributeGroup object.
This class represents the attributeGroup object of a XML schema as described here.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 77 of file qxsdattributegroup_p.h.
Typedefs
List
typedef QList<XsdAttributeGroup::Ptr> QPatternist::XsdAttributeGroup::List
Definition at line 81 of file qxsdattributegroup_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdAttributeGroup> QPatternist::XsdAttributeGroup::Ptr
Definition at line 80 of file qxsdattributegroup_p.h.
Functions
addAttributeUse()
void XsdAttributeGroup::addAttributeUse (const XsdAttributeUse::Ptr & use)
Adds a new attribute use to the attribute group.
Definition at line 53 of file qxsdattributegroup.cpp.
Referenced by QPatternist::XsdSchemaParser::parseNamedAttributeGroup().
 {
     m_attributeUses.append(attributeUse);
 }
attributeUses()
XsdAttributeUse::List XsdAttributeGroup::attributeUses () const
Returns the list of all attribute uses of the attribute group.
Definition at line 58 of file qxsdattributegroup.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkDuplicatedAttributeUses(), QPatternist::XsdSchemaHelper::isValidAttributeGroupRestriction(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), and setAttributeUses().
 {
     return m_attributeUses;
 }
setAttributeUses()
void XsdAttributeGroup::setAttributeUses (const XsdAttributeUse::List & uses)
Sets the list of attribute uses that are defined in the attribute group.
See also
Attribute Uses
Definition at line 48 of file qxsdattributegroup.cpp.
 {
     m_attributeUses = attributeUses;
 }
setWildcard()
void XsdAttributeGroup::setWildcard (const XsdWildcard::Ptr & wildcard)
Sets the attribute wildcard of the attribute group.
See also
Attribute Wildcard
Definition at line 63 of file qxsdattributegroup.cpp.
Referenced by QPatternist::XsdSchemaParser::parseNamedAttributeGroup().
 {
     m_wildcard = wildcard;
 }
wildcard()
XsdWildcard::Ptr XsdAttributeGroup::wildcard () const
Returns the attribute wildcard of the attribute group.
Definition at line 68 of file qxsdattributegroup.cpp.
Referenced by QPatternist::XsdSchemaHelper::isValidAttributeGroupRestriction(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), and setWildcard().
 {
     return m_wildcard;
 }
Properties
m_attributeUses
XsdAttributeUse::List QPatternist::XsdAttributeGroup::m_attributeUses private
Definition at line 113 of file qxsdattributegroup_p.h.
Referenced by addAttributeUse(), attributeUses(), and setAttributeUses().
m_wildcard
XsdWildcard::Ptr QPatternist::XsdAttributeGroup::m_wildcard private
Definition at line 114 of file qxsdattributegroup_p.h.
Referenced by setWildcard(), and wildcard().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdattributegroup_p.h
/src/xmlpatterns/schema/qxsdattributegroup.cpp