Qt 4.8: QDeclarativeComponent Class Reference
QDeclarativeComponent Class Reference
The QDeclarativeComponent class encapsulates a QML component definition.
#include <qdeclarativecomponent.h>
Public Functions
qreal progress () const
Status status () const
QUrl url () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Friends
class QDeclarativeCompositeTypeData
class QDeclarativeTypeData
class QDeclarativeVME
enum Status { Null, Ready, Loading, Error }
Emitted after component "startup" has completed.
qreal progress
The progress of loading the component, from 0.
Status status
The component's current status.
QUrl url
The component URL.
QDeclarativeComponent (QObject *parent=0)
QDeclarativeComponent (QDeclarativeEngine *, QObject *parent=0)
Create a QDeclarativeComponent with no data and give it the specified engine and parent.
QDeclarativeComponent (QDeclarativeEngine *, const QString &fileName, QObject *parent=0)
Create a QDeclarativeComponent from the given fileName and give it the specified parent and engine.
QDeclarativeComponent (QDeclarativeEngine *, const QUrl &url, QObject *parent=0)
Create a QDeclarativeComponent from the given url and give it the specified parent and engine.
virtual ~QDeclarativeComponent ()
Destruct the QDeclarativeComponent.
bool isNull () const
Returns true if status() == QDeclarativeComponent::Null.
bool isReady () const
Returns true if status() == QDeclarativeComponent::Ready.
bool isError () const
Returns true if status() == QDeclarativeComponent::Error.
bool isLoading () const
Returns true if status() == QDeclarativeComponent::Loading.
QList< QDeclarativeError > errors () const
Return the list of errors that occurred during the last compile or create operation.
Q_INVOKABLE QString errorString () const
virtual QObject * create (QDeclarativeContext *context=0)
Create an object instance from this component.
virtual QObject * beginCreate (QDeclarativeContext *)
This method provides more advanced control over component instance creation.
virtual void completeCreate ()
This method provides more advanced control over component instance creation.
void loadUrl (const QUrl &url)
Load the QDeclarativeComponent from the provided url.
void setData (const QByteArray &, const QUrl &baseUrl)
Sets the QDeclarativeComponent to use the given QML data.
QDeclarativeContext * creationContext () const
Returns the QDeclarativeContext the component was created in.
static QDeclarativeComponentAttached * qmlAttachedProperties (QObject *)
void statusChanged (QDeclarativeComponent::Status)
Emitted whenever the component's status changes.
void progressChanged (qreal)
Emitted whenever the component's loading progress changes.
QDeclarativeComponent (QDeclarativeComponentPrivate &dd, QObject *parent)
Q_INVOKABLE QScriptValue createObject (QObject *parent)
A version of create which returns a scriptObject, for use in script.
Q_INVOKABLE QScriptValue createObject (QObject *parent, const QScriptValue &valuemap)
QDeclarativeComponent (QDeclarativeEngine *, QDeclarativeCompiledData *, int, int, QObject *parent)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDeclarativeComponent class encapsulates a QML component definition.
Since
4.7
Components are reusable, encapsulated QML elements with well-defined interfaces. They are often defined in Component Files.
A QDeclarativeComponent instance can be created from a QML file. For example, if there is a main.qml file like this:
import QtQuick 1.0
Item {
    width: 200
    height: 200
}
The following code loads this QML file as a component, creates an instance of this component using create(), and then queries the Item's Item::width value:
QDeclarativeEngine *engine = new QDeclarativeEngine;
QDeclarativeComponent component(engine, QUrl::fromLocalFile("main.qml"));
QObject *myObject = component.create();
QDeclarativeItem *item = qobject_cast<QDeclarativeItem*>(myObject);
int width = item->width();  // width = 200
Network Components
If the URL passed to QDeclarativeComponent is a network resource, or if the QML document references a network resource, the QDeclarativeComponent has to fetch the network data before it is able to create objects. In this case, the QDeclarativeComponent will have a QDeclarativeComponent::Loading{Loading} QDeclarativeComponent::status(){status}. An application will have to wait until the component is QDeclarativeComponent::Ready{Ready} before calling QDeclarativeComponent::create().
The following example shows how to load a QML file from a network resource. After creating the QDeclarativeComponent, it tests whether the component is loading. If it is, it connects to the QDeclarativeComponent::statusChanged() signal and otherwise calls the {continueLoading()} method directly. Note that QDeclarativeComponent::isLoading() may be false for a network component if the component has been cached and is ready immediately.
MyApplication::MyApplication()
{
    // ...
    component = new QDeclarativeComponent(engine, QUrl("http://www.example.com/main.qml"));
    if (component->isLoading())
        QObject::connect(component, SIGNAL(statusChanged(QDeclarativeComponent::Status)),
                         this, SLOT(continueLoading()));
    else
        continueLoading();
}
void MyApplication::continueLoading()
{
    if (component->isError()) {
        qWarning() << component->errors();
    } else {
        QObject *myObject = component->create();
    }
}
See also
{Using QML Bindings in C++ Applications}, {Integrating QML Code with Existing Qt UI Code}
Definition at line 63 of file qdeclarativecomponent.h.
Enumerations
Status
enum QDeclarativeComponent::Status
Emitted after component "startup" has completed.
Component::onCompleted()
This can be used to execute script code at startup, once the full QML environment has been established.
The {Component::onCompleted} attached property can be applied to any element. The order of running the onCompleted scripts is undefined.
Rectangle {
    Component.onCompleted: console.log("Completed Running!")
    Rectangle {
        Component.onCompleted: console.log("Nested Completed Running!")
    }
}
Emitted as the component begins destruction.
Component::onDestruction()
This can be used to undo work done in the onCompleted signal, or other imperative code in your application.
The {Component::onDestruction} attached property can be applied to any element. However, it applies to the destruction of the component as a whole, and not the destruction of the specific object. The order of running the onDestruction scripts is undefined.
Rectangle {
    Component.onDestruction: console.log("Destruction Beginning!")
    Rectangle {
        Component.onDestruction: console.log("Nested Destruction Beginning!")
    }
}
See also
QtDeclarative
Specifies the loading status of the QDeclarativeComponent.
Null This QDeclarativeComponent has no data. Call loadUrl() or setData() to add QML content.
Ready This QDeclarativeComponent is ready and create() may be called.
Loading This QDeclarativeComponent is loading network data.
Error An error has occurred. Call errors() to retrieve a list ofQDeclarativeError}{errors}.
Enumerator
Null
Ready
Loading
Error
Definition at line 80 of file qdeclarativecomponent.h.
 { Null, Ready, Loading, Error };
Constructors and Destructors
QDeclarativeComponent() [1/6]
QDeclarativeComponent::QDeclarativeComponent (QObject * parent = 0)
Warning
This function is not part of the public interface.
Definition at line 309 of file qdeclarativecomponent.cpp.
     : QObject(*(new QDeclarativeComponentPrivate), parent)
 {
 }
QDeclarativeComponent() [2/6]
QDeclarativeComponent::QDeclarativeComponent (QDeclarativeEngine * engine, QObject * parent = 0)
Create a QDeclarativeComponent with no data and give it the specified engine and parent.
Set the data with setData().
Definition at line 449 of file qdeclarativecomponent.cpp.
     : QObject(*(new QDeclarativeComponentPrivate), parent)
 {
     Q_D(QDeclarativeComponent);
     d->engine = engine;
 }
QDeclarativeComponent() [3/6]
QDeclarativeComponent::QDeclarativeComponent (QDeclarativeEngine * engine, const QString & fileName, QObject * parent = 0)
Create a QDeclarativeComponent from the given fileName and give it the specified parent and engine.
See also
loadUrl()
Definition at line 479 of file qdeclarativecomponent.cpp.
 : QObject(*(new QDeclarativeComponentPrivate), parent)
 {
     Q_D(QDeclarativeComponent);
     d->engine = engine;
     loadUrl(d->engine->baseUrl().resolved(QUrl::fromLocalFile(fileName)));
 }
QDeclarativeComponent() [4/6]
QDeclarativeComponent::QDeclarativeComponent (QDeclarativeEngine * engine, const QUrl & url, QObject * parent = 0)
Create a QDeclarativeComponent from the given url and give it the specified parent and engine.
Ensure that the URL provided is full and correct, in particular, use QUrl::fromLocalFile() when loading a file from the local filesystem.
See also
loadUrl()
Definition at line 465 of file qdeclarativecomponent.cpp.
 : QObject(*(new QDeclarativeComponentPrivate), parent)
 {
     Q_D(QDeclarativeComponent);
     d->engine = engine;
     loadUrl(url);
 }
~QDeclarativeComponent()
QDeclarativeComponent::~QDeclarativeComponent () virtual
Destruct the QDeclarativeComponent.
Definition at line 317 of file qdeclarativecomponent.cpp.
 {
     Q_D(QDeclarativeComponent);
     if (d->state.completePending) {
         qWarning("QDeclarativeComponent: Component destroyed while completion pending");
         d->completeCreate();
     }
     if (d->typeData) {
         d->typeData->unregisterCallback(d);
         d->typeData->release();
     }
     if (d->cc)
         d->cc->release();
 }
QDeclarativeComponent() [5/6]
QDeclarativeComponent::QDeclarativeComponent (QDeclarativeComponentPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 654 of file qdeclarativecomponent.cpp.
     : QObject(dd, parent)
 {
 }
QDeclarativeComponent() [6/6]
QDeclarativeComponent::QDeclarativeComponent (QDeclarativeEngine * engine, QDeclarativeCompiledData * cc, int start, int count, QObject * parent) private
Warning
This function is not part of the public interface.
Definition at line 491 of file qdeclarativecomponent.cpp.
     : QObject(*(new QDeclarativeComponentPrivate), parent)
 {
     Q_D(QDeclarativeComponent);
     d->engine = engine;
     d->cc = cc;
     cc->addref();
     d->start = start;
     d->count = count;
     d->url = cc->url;
     d->progress = 1.0;
 }
Functions
beginCreate()
QObject * QDeclarativeComponent::beginCreate (QDeclarativeContext * context) virtual
This method provides more advanced control over component instance creation.
In general, programmers should use QDeclarativeComponent::create() to create a component.
Create an object instance from this component. Returns 0 if creation failed. context specifies the context within which to create the object instance.
When QDeclarativeComponent constructs an instance, it occurs in three steps:
The object hierarchy is created, and constant values are assigned.
Property bindings are evaluated for the the first time.
If applicable, QDeclarativeParserStatus::componentComplete() is called on objects.
QDeclarativeComponent::beginCreate() differs from QDeclarativeComponent::create() in that it only performs step 1. QDeclarativeComponent::completeCreate() must be called to complete steps 2 and 3.
This breaking point is sometimes useful when using attached properties to communicate information to an instantiated component, as it allows their initial values to be configured before property bindings take effect.
Definition at line 843 of file qdeclarativecomponent.cpp.
Referenced by create(), and QDeclarativeEnginePrivate::createQmlObject().
 {
     Q_D(QDeclarativeComponent);
     QObject *rv = d->beginCreate(context?QDeclarativeContextData::get(context):0, QBitField());
     if (rv) {
         QDeclarativeData *ddata = QDeclarativeData::get(rv);
         Q_ASSERT(ddata);
         ddata->indestructible = true;
     }
     return rv;
 }
completeCreate()
void QDeclarativeComponent::completeCreate () virtual
This method provides more advanced control over component instance creation.
In general, programmers should use QDeclarativeComponent::create() to create a component.
Complete a component creation begin with QDeclarativeComponent::beginCreate().
Definition at line 1081 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), create(), and QDeclarativeEnginePrivate::createQmlObject().
 {
     Q_D(QDeclarativeComponent);
     d->completeCreate();
 }
create()
QObject * QDeclarativeComponent::create (QDeclarativeContext * context = 0) virtual
Create an object instance from this component.
Returns 0 if creation failed. context specifies the context within which to create the object instance.
If context is 0 (the default), it will create the instance in the engine' s QDeclarativeEngine::rootContext(){root context}.
Definition at line 808 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeGridViewPrivate::createComponentItem(), QDeclarativeListViewPrivate::createComponentItem(), and QmlJSDebugger::AbstractViewInspector::createQmlObject().
 {
     Q_D(QDeclarativeComponent);
     if (!context)
         context = d->engine->rootContext();
     QObject *rv = beginCreate(context);
     completeCreate();
     return rv;
 }
createObject() [1/2]
QScriptValue QDeclarativeComponent::createObject (QObject * parent) protected
A version of create which returns a scriptObject, for use in script.
Warning
This function is not part of the public interface.
This function will only work on components created in QML.
Sets graphics object parent because forgetting to do this is a frequent and serious problem.
Definition at line 712 of file qdeclarativecomponent.cpp.
 {
     Q_D(QDeclarativeComponent);
     return d->createObject(parent, QScriptValue(QScriptValue::NullValue));
 }
createObject() [2/2]
QScriptValue QDeclarativeComponent::createObject (QObject * parent, const QScriptValue & valuemap) protected
Warning
This function is not part of the public interface. Overloadable method allows properties to be set during creation
Definition at line 722 of file qdeclarativecomponent.cpp.
 {
     Q_D(QDeclarativeComponent);
     if (!valuemap.isObject() || valuemap.isArray()) {
         qmlInfo(this) << tr("createObject: value is not an object");
         return QScriptValue(QScriptValue::NullValue);
     }
     return d->createObject(parent, valuemap);
 }
creationContext()
QDeclarativeContext * QDeclarativeComponent::creationContext () const
Returns the QDeclarativeContext the component was created in.
This is only valid for components created directly from QML.
Definition at line 535 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeComponentPrivate::beginCreate(), QDeclarativeGridViewPrivate::createComponentItem(), and QDeclarativeListViewPrivate::createComponentItem().
 {
     Q_D(const QDeclarativeComponent);
     if(d->creationContext)
         return d->creationContext->asQDeclarativeContext();
     return qmlContext(this);
 }
errors()
QList< QDeclarativeError > QDeclarativeComponent::errors () const
Return the list of errors that occurred during the last compile or create operation.
An empty list is returned if isError() is not set.
Definition at line 588 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject().
 {
     Q_D(const QDeclarativeComponent);
     if (isError())
         return d->state.errors;
     else
         return QList<QDeclarativeError>();
 }
errorString()
QString QDeclarativeComponent::errorString () const
Warning
This function is not part of the public interface. errorString is only meant as a way to get the errors in script
Definition at line 615 of file qdeclarativecomponent.cpp.
 {
     Q_D(const QDeclarativeComponent);
     QString ret;
     if(!isError())
         return ret;
     foreach(const QDeclarativeError &e, d->state.errors) {
         ret += e.url().toString() + QLatin1Char(':') +
                QString::number(e.line()) + QLatin1Char(' ') +
                e.description() + QLatin1Char('\n');
     }
     return ret;
 }
isError()
bool QDeclarativeComponent::isError () const
Returns true if status() == QDeclarativeComponent::Error.
Definition at line 389 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), errors(), and errorString().
 {
     return status() == Error;
 }
isLoading()
bool QDeclarativeComponent::isLoading () const
Returns true if status() == QDeclarativeComponent::Loading.
Definition at line 397 of file qdeclarativecomponent.cpp.
 {
     return status() == Loading;
 }
isNull()
bool QDeclarativeComponent::isNull () const
Returns true if status() == QDeclarativeComponent::Null.
Definition at line 373 of file qdeclarativecomponent.cpp.
 {
     return status() == Null;
 }
isReady()
bool QDeclarativeComponent::isReady () const
Returns true if status() == QDeclarativeComponent::Ready.
Definition at line 381 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), and QDeclarativeTextEdit::setCursorDelegate().
 {
     return status() == Ready;
 }
loadUrl()
void QDeclarativeComponent::loadUrl (const QUrl & url)
Load the QDeclarativeComponent from the provided url.
Ensure that the URL provided is full and correct, in particular, use QUrl::fromLocalFile() when loading a file from the local filesystem.
Definition at line 550 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeComponent().
 {
     Q_D(QDeclarativeComponent);
     d->clear();
     if ((url.isRelative() && !url.isEmpty())
     || url.scheme() == QLatin1String("file")) // Workaround QTBUG-11929
         d->url = d->engine->baseUrl().resolved(url);
     else
         d->url = url;
     if (url.isEmpty()) {
         QDeclarativeError error;
         error.setDescription(tr("Invalid empty URL"));
         d->state.errors << error;
         return;
     }
     QDeclarativeTypeData *data = QDeclarativeEnginePrivate::get(d->engine)->typeLoader.get(d->url);
     if (data->isCompleteOrError()) {
         d->fromTypeData(data);
         d->progress = 1.0;
     } else {
         d->typeData = data;
         d->typeData->registerCallback(d);
         d->progress = data->progress();
     }
     emit statusChanged(status());
     emit progressChanged(d->progress);
 }
progress()
qreal QDeclarativeComponent::progress () const
Referenced by isLoading().
progressChanged
void QDeclarativeComponent::progressChanged (qreal progress) signal
Emitted whenever the component's loading progress changes.
progress will be the current progress between 0.0 (nothing loaded) and 1.0 (finished).
Referenced by loadUrl(), and setData().
qmlAttachedProperties()
QDeclarativeComponentAttached * QDeclarativeComponent::qmlAttachedProperties (QObject * obj) static
Warning
This function is not part of the public interface.
Definition at line 1113 of file qdeclarativecomponent.cpp.
 {
     QDeclarativeComponentAttached *a = new QDeclarativeComponentAttached(obj);
     QDeclarativeEngine *engine = qmlEngine(obj);
     if (!engine)
         return a;
     if (QDeclarativeEnginePrivate::get(engine)->inBeginCreate) {
         QDeclarativeEnginePrivate *p = QDeclarativeEnginePrivate::get(engine);
         a->add(&p->componentAttached);
     } else {
         QDeclarativeData *d = QDeclarativeData::get(obj);
         Q_ASSERT(d);
         Q_ASSERT(d->context);
         a->add(&d->context->componentAttached);
     }
     return a;
 }
setData()
void QDeclarativeComponent::setData (const QByteArray & data, const QUrl & url)
Sets the QDeclarativeComponent to use the given QML data.
If url is provided, it is used to set the component name and to provide a base path for items resolved by this component.
Definition at line 509 of file qdeclarativecomponent.cpp.
Referenced by QmlJSDebugger::AbstractViewInspector::createQmlObject(), and QDeclarativeEnginePrivate::createQmlObject().
 {
     Q_D(QDeclarativeComponent);
     d->clear();
     d->url = url;
     QDeclarativeTypeData *typeData = QDeclarativeEnginePrivate::get(d->engine)->typeLoader.get(data, url);
     if (typeData->isCompleteOrError()) {
         d->fromTypeData(typeData);
     } else {
         d->typeData = typeData;
         d->typeData->registerCallback(d);
     }
     d->progress = 1.0;
     emit statusChanged(status());
     emit progressChanged(d->progress);
 }
status()
Status QDeclarativeComponent::status () const
Referenced by QDeclarativeComponentPrivate::complete(), isError(), isLoading(), isNull(), isReady(), loadUrl(), setData(), and ~QDeclarativeComponent().
statusChanged
void QDeclarativeComponent::statusChanged (QDeclarativeComponent::Status status) signal
Emitted whenever the component's status changes.
status will be the new status.
Referenced by loadUrl(), and setData().
url()
QUrl QDeclarativeComponent::url () const
Referenced by errorString(), loadUrl(), and setData().
Friends and Related Functions
QDeclarativeCompositeTypeData
friend class QDeclarativeCompositeTypeData friend
Definition at line 120 of file qdeclarativecomponent.h.
QDeclarativeTypeData
friend class QDeclarativeTypeData friend
Definition at line 121 of file qdeclarativecomponent.h.
QDeclarativeVME
friend class QDeclarativeVME friend
Definition at line 119 of file qdeclarativecomponent.h.
Properties
progress
qreal QDeclarativeComponent::progress private
The progress of loading the component, from 0.
0 (nothing loaded) to 1.0 (finished).
Definition at line 68 of file qdeclarativecomponent.h.
status
QDeclarativeComponent::Status QDeclarativeComponent::status private
The component's current status.
Definition at line 69 of file qdeclarativecomponent.h.
url
QUrl QDeclarativeComponent::url private
The component URL.
This is the URL passed to either the constructor, or the loadUrl() or setData() methods.
Definition at line 70 of file qdeclarativecomponent.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecomponent.h
/src/declarative/qml/qdeclarativecomponent.cpp