Qt 4.8: QGLExtensions Class Reference
QGLExtensions Class Reference
#include <qgl_p.h>
Public Types
enum Extension {
TextureRectangle = 0x00000001, SampleBuffers = 0x00000002, GenerateMipmap = 0x00000004, TextureCompression = 0x00000008,
FragmentProgram = 0x00000010, MirroredRepeat = 0x00000020, FramebufferObject = 0x00000040, StencilTwoSide = 0x00000080,
StencilWrap = 0x00000100, PackedDepthStencil = 0x00000200, NVFloatBuffer = 0x00000400, PixelBufferObject = 0x00000800,
FramebufferBlit = 0x00001000, NPOTTextures = 0x00002000, BGRATextureFormat = 0x00004000, DDSTextureCompression = 0x00008000,
ETC1TextureCompression = 0x00010000, PVRTCTextureCompression = 0x00020000, FragmentShader = 0x00040000, ElementIndexUint = 0x00080000,
Depth24 = 0x00100000, SRGBFrameBuffer = 0x00200000
}
Static Public Functions
static Extensions glExtensions ()
static Extensions currentContextExtensions ()
Detailed Description
Definition at line 284 of file qgl_p.h.
Enumerations
Extension
enum QGLExtensions::Extension
Enumerator
TextureRectangle
SampleBuffers
GenerateMipmap
TextureCompression
FragmentProgram
MirroredRepeat
FramebufferObject
StencilTwoSide
StencilWrap
PackedDepthStencil
NVFloatBuffer
PixelBufferObject
FramebufferBlit
NPOTTextures
BGRATextureFormat
DDSTextureCompression
ETC1TextureCompression
PVRTCTextureCompression
FragmentShader
ElementIndexUint
Depth24
SRGBFrameBuffer
Definition at line 286 of file qgl_p.h.
                    {
         TextureRectangle        = 0x00000001,
         SampleBuffers           = 0x00000002,
         GenerateMipmap          = 0x00000004,
         TextureCompression      = 0x00000008,
         FragmentProgram         = 0x00000010,
         MirroredRepeat          = 0x00000020,
         FramebufferObject       = 0x00000040,
         StencilTwoSide          = 0x00000080,
         StencilWrap             = 0x00000100,
         PackedDepthStencil      = 0x00000200,
         NVFloatBuffer           = 0x00000400,
         PixelBufferObject       = 0x00000800,
         FramebufferBlit         = 0x00001000,
         NPOTTextures            = 0x00002000,
         BGRATextureFormat       = 0x00004000,
         DDSTextureCompression   = 0x00008000,
         ETC1TextureCompression  = 0x00010000,
         PVRTCTextureCompression = 0x00020000,
         FragmentShader          = 0x00040000,
         ElementIndexUint        = 0x00080000,
         Depth24                 = 0x00100000,
         SRGBFrameBuffer         = 0x00200000
     };
Functions
currentContextExtensions()
QGLExtensions::Extensions QGLExtensions::currentContextExtensions () static
Definition at line 5673 of file qgl.cpp.
 {
     QGLExtensionMatcher extensions;
     Extensions glExtensions;
     if (extensions.match("GL_ARB_texture_rectangle"))
         glExtensions |= TextureRectangle;
     if (extensions.match("GL_ARB_multisample"))
         glExtensions |= SampleBuffers;
     if (extensions.match("GL_SGIS_generate_mipmap"))
         glExtensions |= GenerateMipmap;
     if (extensions.match("GL_ARB_texture_compression"))
         glExtensions |= TextureCompression;
     if (extensions.match("GL_EXT_texture_compression_s3tc"))
         glExtensions |= DDSTextureCompression;
     if (extensions.match("GL_OES_compressed_ETC1_RGB8_texture"))
         glExtensions |= ETC1TextureCompression;
     if (extensions.match("GL_IMG_texture_compression_pvrtc"))
         glExtensions |= PVRTCTextureCompression;
     if (extensions.match("GL_ARB_fragment_program"))
         glExtensions |= FragmentProgram;
     if (extensions.match("GL_ARB_fragment_shader"))
         glExtensions |= FragmentShader;
     if (extensions.match("GL_ARB_shader_objects"))
         glExtensions |= FragmentShader;
     if (extensions.match("GL_ARB_texture_mirrored_repeat"))
         glExtensions |= MirroredRepeat;
     if (extensions.match("GL_EXT_framebuffer_object"))
         glExtensions |= FramebufferObject;
     if (extensions.match("GL_EXT_stencil_two_side"))
         glExtensions |= StencilTwoSide;
     if (extensions.match("GL_EXT_stencil_wrap"))
         glExtensions |= StencilWrap;
     if (extensions.match("GL_EXT_packed_depth_stencil"))
         glExtensions |= PackedDepthStencil;
     if (extensions.match("GL_NV_float_buffer"))
         glExtensions |= NVFloatBuffer;
     if (extensions.match("GL_ARB_pixel_buffer_object"))
         glExtensions |= PixelBufferObject;
     if (extensions.match("GL_IMG_texture_format_BGRA8888")
         || extensions.match("GL_EXT_texture_format_BGRA8888"))
         glExtensions |= BGRATextureFormat;
 #if defined(QT_OPENGL_ES_2)
     glExtensions |= FramebufferObject;
     glExtensions |= GenerateMipmap;
     glExtensions |= FragmentShader;
 #endif
 #if defined(QT_OPENGL_ES_1)
     if (extensions.match("GL_OES_framebuffer_object"))
         glExtensions |= FramebufferObject;
 #endif
 #if defined(QT_OPENGL_ES)
     if (extensions.match("GL_OES_packed_depth_stencil"))
         glExtensions |= PackedDepthStencil;
     if (extensions.match("GL_OES_element_index_uint"))
         glExtensions |= ElementIndexUint;
     if (extensions.match("GL_OES_depth24"))
         glExtensions |= Depth24;
 #else
     glExtensions |= ElementIndexUint;
 #endif
     if (extensions.match("GL_ARB_framebuffer_object")) {
         // ARB_framebuffer_object also includes EXT_framebuffer_blit.
         glExtensions |= FramebufferObject;
         glExtensions |= FramebufferBlit;
     }
     if (extensions.match("GL_EXT_framebuffer_blit"))
         glExtensions |= FramebufferBlit;
     if (extensions.match("GL_ARB_texture_non_power_of_two"))
         glExtensions |= NPOTTextures;
     if (extensions.match("GL_EXT_bgra"))
         glExtensions |= BGRATextureFormat;
     {
         GLboolean srgbCapableFramebuffers = false;
         glGetBooleanv(FRAMEBUFFER_SRGB_CAPABLE_EXT, &srgbCapableFramebuffers);
         if (srgbCapableFramebuffers)
             glExtensions |= SRGBFrameBuffer;
         // Clear possible error which is generated if
         // FRAMEBUFFER_SRGB_CAPABLE_EXT isn't supported.
         glGetError();
     }
     return glExtensions;
 }
glExtensions()
QGLExtensions::Extensions QGLExtensions::glExtensions () static
Definition at line 5781 of file qgl.cpp.
Referenced by QOpenGLPaintEngine::begin(), QGLFramebufferObject::bindDefault(), QGLFramebufferObject::blitFramebuffer(), QGLContext::choosePixelFormat(), QGLContext::chooseVisual(), QGL2PaintEngineExPrivate::fill(), QGLWindowSurface::flush(), QGLFramebufferObject::hasOpenGLFramebufferBlit(), QGLFramebufferObject::hasOpenGLFramebufferObjects(), QGLFramebufferObjectPrivate::init(), QGLOffscreen::isSupported(), nearest_gl_texture_size(), needsEmulation(), pfiToQGLFormat(), QGLEngineSelector::preferredPaintEngine(), qPolyline(), qt_format_to_attrib_list(), qt_gl_preferredTextureFormat(), qt_gl_preferredTextureTarget(), qt_resolve_glsl_extensions(), qTriangulate(), QGLWindowSurface::updateGeometry(), QOpenGLPaintEnginePrivate::updateGradient(), and QOpenGLPaintEngine::updateRenderHints().
 {
     Extensions extensionFlags = 0;
     QGLContext *currentCtx = const_cast<QGLContext *>(QGLContext::currentContext());
     if (currentCtx && currentCtx->d_func()->extension_flags_cached)
         return currentCtx->d_func()->extension_flags;
     if (!currentCtx) {
         extensionFlags = qtDefaultExtensions()->extensions;
     } else {
         extensionFlags = currentContextExtensions();
         currentCtx->d_func()->extension_flags_cached = true;
         currentCtx->d_func()->extension_flags = extensionFlags;
     }
     return extensionFlags;
 }
The documentation for this class was generated from the following files:
/src/opengl/qgl_p.h
/src/opengl/qgl.cpp