Qt 4.8: QApplication Class Reference
QApplication Class Reference
The QApplication class manages the GUI application's control flow and main settings.
#include <qapplication.h>
Public Types
enum ColorSpec { NormalColor =0, CustomColor =1, ManyColor =2 }
See setColorSpec() for full details.
enum Type { Tty, GuiClient, GuiServer }
Public Types inherited from QCoreApplication
enum { ApplicationFlags }
enum Encoding { CodecForTr, UnicodeUTF8, DefaultCodec = CodecForTr }
This enum type defines the 8-bit encoding of character string arguments to translate():
typedef bool(* EventFilter) (void *message, long *result)
A function with the following signature that can be used as an event filter:
Public Slots
static void aboutQt ()
Displays a simple message box about Qt.
int autoMaximizeThreshold () const
bool autoSipEnabled () const
static void closeAllWindows ()
Closes all top-level windows.
void setAutoMaximizeThreshold (const int threshold)
void setAutoSipEnabled (const bool enabled)
void setStyleSheet (const QString &sheet)
Public Slots inherited from QCoreApplication
static void quit ()
Tells the application to exit with return code 0 (success).
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void commitDataRequest (QSessionManager &sessionManager)
This signal deals with Session Management{session management}.
void focusChanged (QWidget *old, QWidget *now)
void fontDatabaseChanged ()
This signal is emitted when application fonts are loaded or removed.
void lastWindowClosed ()
This signal is emitted from QApplication::exec() when the last visible primary window (i.
void saveStateRequest (QSessionManager &sessionManager)
This signal deals with Session Management{session management}.
Signals inherited from QCoreApplication
void aboutToQuit ()
This signal is emitted when the application is about to quit the main event loop, e.
void unixSignal (int)
This signal is emitted whenever a Unix signal is received by the application.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void commitData (QSessionManager &sm)
This function deals with Session Management{session management}.
QInputContext * inputContext () const
Returns the QInputContext instance used by the application.
bool isSessionRestored () const
Returns true if the application has been restored from an earlier Session Management{session}; otherwise returns false.
virtual bool macEventFilter (EventHandlerCallRef, EventRef)
bool notify (QObject *, QEvent *)
Reimplemented Function
QApplication (int &argc, char **argv)
Initializes the window system and constructs an application object with argc command line arguments in argv.
QApplication (int &argc, char **argv, bool GUIenabled)
Constructs an application object with argc command line arguments in argv.
QApplication (int &argc, char **argv, Type)
Constructs an application object with argc command line arguments in argv.
QApplication (Display *dpy, Qt::HANDLE visual=0, Qt::HANDLE cmap=0)
Creates an application, given an already open display display.
QApplication (Display *dpy, int &argc, char **argv, Qt::HANDLE visual=0, Qt::HANDLE cmap=0)
Creates an application, given an already open display and using argc command line arguments in argv.
QApplication (QApplication::QS60MainApplicationFactory factory, int &argc, char **argv)
virtual bool qwsEventFilter (QWSEvent *)
This virtual function is only implemented under Qt for Embedded Linux.
int qwsProcessEvent (QWSEvent *)
void qwsSetCustomColors (QRgb *colortable, int start, int numColors)
Set Qt for Embedded Linux custom color table.
virtual void saveState (QSessionManager &sm)
This function deals with Session Management{session management}.
QString sessionId () const
Returns the current Session Management{session's} identifier.
QString sessionKey () const
Returns the session key in the current Session Management{session}.
void setInputContext (QInputContext *)
This function replaces the QInputContext instance used by the application with inputContext.
QString styleSheet () const
void winFocus (QWidget *, bool)
virtual int x11ClientMessage (QWidget *, XEvent *, bool passive_only)
virtual bool x11EventFilter (XEvent *)
int x11ProcessEvent (XEvent *)
This function does the core processing of individual X {event}s, normally by dispatching Qt events to the right destination.
virtual ~QApplication ()
Cleans up any window system resources that were allocated by this application.
Public Functions inherited from QCoreApplication
bool filterEvent (void *message, long *result)
Sends message through the event filter that was set by setEventFilter().
QCoreApplication (int &argc, char **argv)
Constructs a Qt kernel application.
EventFilter setEventFilter (EventFilter filter)
Replaces the event filter function for the QCoreApplication with filter and returns the pointer to the replaced event filter function.
virtual bool winEventFilter (MSG *message, long *result)
The message procedure calls this function for every message received.
~QCoreApplication ()
Destroys the QCoreApplication object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QWidget * activeModalWidget ()
Returns the active modal widget.
static QWidget * activePopupWidget ()
Returns the active popup widget.
static QWidget * activeWindow ()
Returns the application top-level window that has the keyboard input focus, or 0 if no application window has the focus.
static void alert (QWidget *widget, int duration=0)
static QWidgetList allWidgets ()
Returns a list of all the widgets in the application.
static void beep ()
Sounds the bell, using the default volume and sound.
static void changeOverrideCursor (const QCursor &)
Changes the currently active application override cursor to cursor.
static QClipboard * clipboard ()
Returns a pointer to the application global clipboard.
static int colorSpec ()
Returns the color specification.
static int cursorFlashTime ()
static QDesktopWidget * desktop ()
Returns the desktop widget (also called the root window).
static bool desktopSettingsAware ()
Returns true if Qt is set to use the system's standard colors, fonts, etc.
static int doubleClickInterval ()
static int exec ()
Enters the main event loop and waits until exit() is called, then returns the value that was set to exit() (which is 0 if exit() is called via quit()).
static QWidget * focusWidget ()
Returns the application widget that has the keyboard input focus, or 0 if no widget in this application has the focus.
static QFont font ()
Returns the default application font.
static QFont font (const QWidget *)
Returns the default font for the widget.
static QFont font (const char *className)
Returns the font for widgets of the given className.
static QFontMetrics fontMetrics ()
Returns display (screen) font metrics for the application font.
static QSize globalStrut ()
static bool isEffectEnabled (Qt::UIEffect)
Returns true if effect is enabled; otherwise returns false.
static bool isLeftToRight ()
Returns true if the application's layout direction is Qt::LeftToRight; otherwise returns false.
static bool isRightToLeft ()
Returns true if the application's layout direction is Qt::RightToLeft; otherwise returns false.
static Qt::LayoutDirection keyboardInputDirection ()
Returns the current keyboard input direction.
static int keyboardInputInterval ()
static QLocale keyboardInputLocale ()
Returns the current keyboard input locale.
static Qt::KeyboardModifiers keyboardModifiers ()
Returns the current state of the modifier keys on the keyboard.
static Qt::LayoutDirection layoutDirection ()
static Qt::MouseButtons mouseButtons ()
Returns the current state of the buttons on the mouse.
static QCursor * overrideCursor ()
Strips out vertical alignment flags and transforms an alignment align of Qt::AlignLeft into Qt::AlignLeft or Qt::AlignRight according to the language used.
static QPalette palette ()
Returns the application palette.
static QPalette palette (const QWidget *)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.If a widget is passed, the default palette for the widget's class is returned.
static QPalette palette (const char *className)
Returns the palette for widgets of the given className.
static Qt::KeyboardModifiers queryKeyboardModifiers ()
Queries and returns the state of the modifier keys on the keyboard.
static bool quitOnLastWindowClosed ()
static void restoreOverrideCursor ()
Undoes the last setOverrideCursor().
static void setActiveWindow (QWidget *act)
Sets the active window to the active widget in response to a system event.
static void setColorSpec (int)
Sets the color specification for the application to spec.
static void setCursorFlashTime (int)
static void setDesktopSettingsAware (bool)
Sets whether Qt should use the system's standard colors, fonts, etc., to on.
static void setDoubleClickInterval (int)
static void setEffectEnabled (Qt::UIEffect, bool enable=true)
Enables the UI effect effect if enable is true, otherwise the effect will not be used.
static void setFont (const QFont &, const char *className=0)
Changes the default application font to font.
static void setGlobalStrut (const QSize &)
static void setGraphicsSystem (const QString &)
Sets the default graphics backend to system, which will be used for on-screen widgets and QPixmaps.
static void setKeyboardInputInterval (int)
static void setLayoutDirection (Qt::LayoutDirection direction)
static void setOverrideCursor (const QCursor &)
Use changeOverrideCursor(cursor) (if replace is true) or setOverrideCursor(cursor) (if replace is false).
static void setPalette (const QPalette &, const char *className=0)
Changes the default application palette to palette.
static void setQuitOnLastWindowClosed (bool quit)
static void setStartDragDistance (int l)
static void setStartDragTime (int ms)
static void setStyle (QStyle *)
Sets the application's GUI style to style.
static QStyle * setStyle (const QString &)
Requests a QStyle object for style from the QStyleFactory.
static void setWheelScrollLines (int)
static void setWindowIcon (const QIcon &icon)
static int startDragDistance ()
static int startDragTime ()
static QStyle * style ()
Returns the application's style object.
static void syncX ()
Synchronizes with the X server in the X11 implementation.
static QWidget * topLevelAt (const QPoint &p)
Returns the top-level widget at the given point; returns 0 if there is no such widget.
static QWidget * topLevelAt (int x, int y)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the top-level widget at the point ({x}, {y}); returns 0 if there is no such widget.
static QWidgetList topLevelWidgets ()
Returns a list of the top-level widgets (windows) in the application.
static Type type ()
Returns the type of application (Tty , GuiClient, or GuiServer).
static int wheelScrollLines ()
static QWidget * widgetAt (const QPoint &p)
Returns the widget at global screen position point, or 0 if there is no Qt widget there.
static QWidget * widgetAt (int x, int y)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the widget at global screen position (x, y), or 0 if there is no Qt widget there.
static QIcon windowIcon ()
static void winMouseButtonUp ()
Static Public Functions inherited from QCoreApplication
static void addLibraryPath (const QString &)
Prepends path to the beginning of the library path list, ensuring that it is searched for libraries first.
static QString applicationDirPath ()
Returns the directory that contains the application executable.
static QString applicationFilePath ()
Returns the file path of the application executable.
static QString applicationName ()
static qint64 applicationPid ()
Returns the current process ID for the application.
static QString applicationVersion ()
static QT_DEPRECATED int argc ()
Use arguments().
static QStringList arguments ()
Returns the list of command-line arguments.
static QT_DEPRECATED char ** argv ()
Use arguments() instead.
static bool closingDown ()
Returns true if the application objects are being destroyed; otherwise returns false.
static int exec ()
Enters the main event loop and waits until exit() is called.
static void exit (int retcode=0)
Tells the application to exit with a return code.
static void flush ()
Flushes the platform specific event queues.
static bool hasPendingEvents ()
This function returns true if there are pending events; otherwise returns false.
static void installTranslator (QTranslator *messageFile)
Adds the translation file translationFile to the list of translation files to be used for translations.
static QCoreApplication * instance ()
Returns a pointer to the application's QCoreApplication (or QApplication) instance.
static QStringList libraryPaths ()
Returns a list of paths that the application will search when dynamically loading libraries.
static QString organizationDomain ()
static QString organizationName ()
static void postEvent (QObject *receiver, QEvent *event)
Adds the event event, with the object receiver as the receiver of the event, to an event queue and returns immediately.
static void postEvent (QObject *receiver, QEvent *event, int priority)
static void processEvents (QEventLoop::ProcessEventsFlags flags=QEventLoop::AllEvents)
Processes all pending events for the calling thread according to the specified flags until there are no more events to process.
static void processEvents (QEventLoop::ProcessEventsFlags flags, int maxtime)
static void removeLibraryPath (const QString &)
Removes path from the library path list.
static void removePostedEvents (QObject *receiver)
Removes all events posted using postEvent() for receiver.
static void removePostedEvents (QObject *receiver, int eventType)
static void removeTranslator (QTranslator *messageFile)
Removes the translation file translationFile from the list of translation files used by this application.
static bool sendEvent (QObject *receiver, QEvent *event)
Sends event event directly to receiver receiver, using the notify() function.
static void sendPostedEvents (QObject *receiver, int event_type)
Immediately dispatches all events which have been previously queued with QCoreApplication::postEvent() and which are for the object receiver and have the event type event_type.
static void sendPostedEvents ()
static void setApplicationName (const QString &application)
static void setApplicationVersion (const QString &version)
static void setAttribute (Qt::ApplicationAttribute attribute, bool on=true)
Sets the attribute attribute if on is true; otherwise clears the attribute.
static void setLibraryPaths (const QStringList &)
Sets the list of directories to search when loading libraries to paths.
static void setOrganizationDomain (const QString &orgDomain)
static void setOrganizationName (const QString &orgName)
static bool startingUp ()
Returns true if an application object has not been created yet; otherwise returns false.
static bool testAttribute (Qt::ApplicationAttribute attribute)
Returns true if attribute attribute is set; otherwise returns false.
static QString translate (const char *context, const char *key, const char *disambiguation=0, Encoding encoding=CodecForTr)
static QString translate (const char *context, const char *key, const char *disambiguation, Encoding encoding, int n)
Returns the translation text for sourceText, by querying the installed translation files.
static void watchUnixSignal (int signal, bool watch)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
bool compressEvent (QEvent *, QObject *receiver, QPostEventList *)
bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
void setArgs (int, char **)
Protected Functions inherited from QCoreApplication
QCoreApplication (QCoreApplicationPrivate &p)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int autoMaximizeThreshold
defines a threshold for auto maximizing widgets
bool autoSipEnabled
toggles automatic SIP (software input panel) visibility
int cursorFlashTime
the text cursor's flash (blink) time in milliseconds
int doubleClickInterval
the time limit in milliseconds that distinguishes a double click from two consecutive mouse clicks
QSize globalStrut
the minimum size that any GUI element that the user can interact with should have
int keyboardInputInterval
the time limit in milliseconds that distinguishes a key press from two consecutive key presses
Qt::LayoutDirection layoutDirection
the default layout direction for this application
bool quitOnLastWindowClosed
whether the application implicitly quits when the last window is closed.
int startDragDistance
If you support drag and drop in your application, and want to start a drag and drop operation after the user has moved the cursor a certain distance with a button held down, you should use this property's value as the minimum distance required.
int startDragTime
the time in milliseconds that a mouse button must be held down before a drag and drop operation will begin
QString styleSheet
the application style sheet
int wheelScrollLines
the number of lines to scroll a widget, when the mouse wheel is rotated.
QIcon windowIcon
the default window icon
Friends
class Q3AccelManager
class QAction
class QDirectPainter
class QDirectPainterPrivate
class QETWidget
class QFontDatabasePrivate
class QGestureManager
class QGraphicsItem
class QGraphicsScene
class QGraphicsScenePrivate
class QGraphicsWidget
class QInputContext
class QLineEdit
class QShortcut
class QTextControl
class QTranslator
class QWidget
class QWidgetAnimator
class QWidgetPrivate
class QWSDirectPainterSurface
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QCoreApplication
void qAddPostRoutine (QtCleanUpFunction ptr)
Adds a global routine that will be called from the QApplication destructor.
removePostedEvents
Removes all events of the given eventType that were posted using postEvent() for receiver.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QApplication class manages the GUI application's control flow and main settings.
QApplication contains the main event loop, where all events from the window system and other sources are processed and dispatched. It also handles the application's initialization, finalization, and provides session management. In addition, QApplication handles most of the system-wide and application-wide settings.
For any GUI application using Qt, there is precisely one QApplication object, no matter whether the application has 0, 1, 2 or more windows at any given time. For non-GUI Qt applications, use QCoreApplication instead, as it does not depend on the QtGui library.
The QApplication object is accessible through the instance() function that returns a pointer equivalent to the global qApp pointer.
QApplication's main areas of responsibility are:
It initializes the application with the user's desktop settings such as palette(), font() and doubleClickInterval(). It keeps track of these properties in case the user changes the desktop globally, for example through some kind of control panel.
It performs event handling, meaning that it receives events from the underlying window system and dispatches them to the relevant widgets. By using sendEvent() and postEvent() you can send your own events to widgets.
It parses common command line arguments and sets its internal state accordingly. See the constructor documentation below for more details.
It defines the application's look and feel, which is encapsulated in a QStyle object. This can be changed at runtime with setStyle().
It specifies how the application is to allocate colors. See setColorSpec() for details.
It provides localization of strings that are visible to the user via translate().
It provides some magical objects like the desktop() and the clipboard().
It knows about the application's windows. You can ask which widget is at a certain position using widgetAt(), get a list of topLevelWidgets() and closeAllWindows(), etc.
It manages the application's mouse cursor handling, see setOverrideCursor()
On the X window system, it provides functions to flush and sync the communication stream, see flushX() and syncX().
It provides support for sophisticated Session Management {session management}. This makes it possible for applications to terminate gracefully when the user logs out, to cancel a shutdown process if termination isn't possible and even to preserve the entire application's state for a future session. See isSessionRestored(), sessionId() and commitData() and saveState() for details.
Since the QApplication object does so much initialization, it must be created before any other objects related to the user interface are created. QApplication also deals with common command line arguments. Hence, it is usually a good idea to create it before any interpretation or modification of argv is done in the application itself.
Groups of functions
System settings
desktopSettingsAware(), setDesktopSettingsAware(), cursorFlashTime(), setCursorFlashTime(), doubleClickInterval(), setDoubleClickInterval(), setKeyboardInputInterval(), wheelScrollLines(), setWheelScrollLines(), palette(), setPalette(), font(), setFont(), fontMetrics().
Event handling
exec(), processEvents(), exit(), quit(). sendEvent(), postEvent(), sendPostedEvents(), removePostedEvents(), hasPendingEvents(), notify(), macEventFilter(), qwsEventFilter(), x11EventFilter(), x11ProcessEvent(), winEventFilter().
GUI Styles
style(), setStyle().
Color usage
colorSpec(), setColorSpec(), qwsSetCustomColors().
Text handling
installTranslator(), removeTranslator() translate().
Widgets
allWidgets(), topLevelWidgets(), desktop(), activePopupWidget(), activeModalWidget(), clipboard(), focusWidget(), activeWindow(), widgetAt().
Advanced cursor handling
overrideCursor(), setOverrideCursor(), restoreOverrideCursor().
X Window System synchronization
flushX(), syncX().
Session management
isSessionRestored(), sessionId(), commitData(), saveState().
Miscellaneous closeAllWindows(), startingUp(), closingDown(), type().
See also
QCoreApplication, QAbstractEventDispatcher, QEventLoop, QSettings
Definition at line 99 of file qapplication.h.
Enumerations
ColorSpec
enum QApplication::ColorSpec
See setColorSpec() for full details.
NormalColor the default color allocation policy
CustomColor the same as NormalColor for X11; allocates colors to a palette on demand under Windows
ManyColor the right choice for applications that use thousands of colors
Enumerator
NormalColor
CustomColor
ManyColor
Definition at line 148 of file qapplication.h.
 { NormalColor=0, CustomColor=1, ManyColor=2 };
Type
enum QApplication::Type
Tty a console application
GuiClient a GUI client application
GuiServer a GUI server application (for Qt for Embedded Linux)
Enumerator
Tty
GuiClient
GuiServer
Definition at line 123 of file qapplication.h.
 { Tty, GuiClient, GuiServer };
Constructors and Destructors
~QApplication()
QApplication::~QApplication () virtual
Cleans up any window system resources that were allocated by this application.
Sets the global variable qApp to 0.
Definition at line 1105 of file qapplication.cpp.
 {
     Q_D(QApplication);
 #ifndef QT_NO_CLIPBOARD
     // flush clipboard contents
     if (qt_clipboard) {
         QEvent event(QEvent::Clipboard);
         QApplication::sendEvent(qt_clipboard, &event);
     }
 #endif
     //### this should probable be done even later
     qt_call_post_routines();
     // kill timers before closing down the dispatcher
     d->toolTipWakeUp.stop();
     d->toolTipFallAsleep.stop();
     d->eventDispatcher->closingDown();
     d->eventDispatcher = 0;
     QApplicationPrivate::is_app_closing = true;
     QApplicationPrivate::is_app_running = false;
     delete QWidgetPrivate::mapper;
     QWidgetPrivate::mapper = 0;
     // delete all widgets
     if (QWidgetPrivate::allWidgets) {
         QWidgetSet *mySet = QWidgetPrivate::allWidgets;
         QWidgetPrivate::allWidgets = 0;
         for (QWidgetSet::ConstIterator it = mySet->constBegin(); it != mySet->constEnd(); ++it) {
             register QWidget *w = *it;
             if (!w->parent())                        // window
                 w->destroy(true, true);
         }
         delete mySet;
     }
     delete qt_desktopWidget;
     qt_desktopWidget = 0;
 #ifndef QT_NO_CLIPBOARD
     delete qt_clipboard;
     qt_clipboard = 0;
 #endif
 #if defined(Q_WS_X11) || defined(Q_WS_WIN)
     delete d->move_cursor; d->move_cursor = 0;
     delete d->copy_cursor; d->copy_cursor = 0;
     delete d->link_cursor; d->link_cursor = 0;
 #endif
 #if defined(Q_WS_WIN)
     delete d->ignore_cursor; d->ignore_cursor = 0;
 #endif
     delete QApplicationPrivate::app_pal;
     QApplicationPrivate::app_pal = 0;
     delete QApplicationPrivate::sys_pal;
     QApplicationPrivate::sys_pal = 0;
     delete QApplicationPrivate::set_pal;
     QApplicationPrivate::set_pal = 0;
     app_palettes()->clear();
     {
         QMutexLocker locker(applicationFontMutex());
         delete QApplicationPrivate::app_font;
         QApplicationPrivate::app_font = 0;
     }
     delete QApplicationPrivate::sys_font;
     QApplicationPrivate::sys_font = 0;
     delete QApplicationPrivate::set_font;
     QApplicationPrivate::set_font = 0;
     app_fonts()->clear();
     delete QApplicationPrivate::app_style;
     QApplicationPrivate::app_style = 0;
     delete QApplicationPrivate::app_icon;
     QApplicationPrivate::app_icon = 0;
     delete QApplicationPrivate::graphics_system;
     QApplicationPrivate::graphics_system = 0;
 #ifndef QT_NO_CURSOR
     d->cursor_list.clear();
 #endif
 #ifndef QT_NO_DRAGANDDROP
     if (qt_is_gui_used)
         delete QDragManager::self();
 #endif
     d->cleanupMultitouch();
     qt_cleanup();
     if (QApplicationPrivate::widgetCount)
         qDebug("Widgets left: %i    Max widgets: %i \n", QWidgetPrivate::instanceCounter, QWidgetPrivate::maxInstances);
 #ifndef QT_NO_SESSIONMANAGER
     delete d->session_manager;
     d->session_manager = 0;
 #endif //QT_NO_SESSIONMANAGER
     QApplicationPrivate::obey_desktop_settings = true;
     QApplicationPrivate::cursor_flash_time = 1000;
     QApplicationPrivate::mouse_double_click_time = 400;
     QApplicationPrivate::keyboard_input_time = 400;
     drag_time = 500;
     drag_distance = 4;
     layout_direction = Qt::LeftToRight;
     QApplicationPrivate::app_strut = QSize(0, 0);
     QApplicationPrivate::animate_ui = true;
     QApplicationPrivate::animate_menu = false;
     QApplicationPrivate::fade_menu = false;
     QApplicationPrivate::animate_combo = false;
     QApplicationPrivate::animate_tooltip = false;
     QApplicationPrivate::fade_tooltip = false;
     QApplicationPrivate::widgetCount = false;
 #ifndef QT_NO_STATEMACHINE
     // trigger unregistering of QStateMachine's GUI types
     qUnregisterGuiStateMachine();
 #endif
     // trigger unregistering of QVariant's GUI types
     qUnregisterGuiVariant();
 }
QApplication() [1/6]
QApplication::QApplication (int & argc, char ** argv)
Initializes the window system and constructs an application object with argc command line arguments in argv.
Warning
The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string.
The global qApp pointer refers to this application object. Only one application object should be created.
This application object must be constructed before any paint devices (including widgets, pixmaps, bitmaps etc.).
Note
argc and argv might be changed as Qt removes command line arguments that it recognizes.
Qt debugging options (not available if Qt was compiled without the QT_DEBUG flag defined):
-nograb, tells Qt that it must never grab the mouse or the keyboard.
-dograb (only under X11), running under a debugger can cause an implicit -nograb, use -dograb to override.
-sync (only under X11), switches to synchronous mode for debugging.
See Debugging Techniques for a more detailed explanation.
All Qt programs automatically support the following command line options:
-style= style, sets the application GUI style. Possible values are motif, windows, and platinum. If you compiled Qt with additional styles or have additional styles as plugins these will be available to the -style command line option.
-style style, is the same as listed above.
-stylesheet= stylesheet, sets the application styleSheet . The value must be a path to a file that contains the Style Sheet.
Note
Relative URLs in the Style Sheet file are relative to the Style Sheet file's path.
-stylesheet stylesheet, is the same as listed above.
-session= session, restores the application from an earlier Session Management{session}.
-session session, is the same as listed above.
-widgetcount, prints debug message at the end about number of widgets left undestroyed and maximum number of widgets existed at the same time
-reverse, sets the application's layout direction to Qt::RightToLeft
-graphicssystem, sets the backend to be used for on-screen widgets and QPixmaps. Available options are raster and opengl.
-qmljsdebugger=, activates the QML/JS debugger with a specified port. The value must be of format port:1234[,block], where block is optional and will make the application wait until a debugger connects to it.
The X11 version of Qt supports some traditional X11 command line options:
-display display, sets the X display (default is $DISPLAY).
-geometry geometry, sets the client geometry of the first window that is shown.
-fn or -font font, defines the application font. The font should be specified using an X logical font description. Note that this option is ignored when Qt is built with fontconfig support enabled.
-bg or -background color, sets the default background color and an application palette (light and dark shades are calculated).
-fg or -foreground color, sets the default foreground color.
-btn or -button color, sets the default button color.
-name name, sets the application name.
-title title, sets the application title.
-visual TrueColor, forces the application to use a TrueColor visual on an 8-bit display.
-ncols count, limits the number of colors allocated in the color cube on an 8-bit display, if the application is using the QApplication::ManyColor color specification. If count is 216 then a 6x6x6 color cube is used (i.e. 6 levels of red, 6 of green, and 6 of blue); for other values, a cube approximately proportional to a 2x3x1 cube is used.
-cmap, causes the application to install a private color map on an 8-bit display.
-im, sets the input method server (equivalent to setting the XMODIFIERS environment variable)
-inputstyle, defines how the input is inserted into the given widget, e.g., onTheSpot makes the input appear directly in the widget, while overTheSpot makes the input appear in a box floating over the widget and is not inserted until the editing is done.
X11 Notes
If QApplication fails to open the X11 display, it will terminate the process. This behavior is consistent with most X11 applications.
See also
arguments()
Definition at line 739 of file qapplication.cpp.
Referenced by QApplication().
     : QCoreApplication(*new QApplicationPrivate(argc, argv, GuiClient, 0x040000))
 { Q_D(QApplication); d->construct(); }
QApplication() [2/6]
QApplication::QApplication (int & argc, char ** argv, bool GUIenabled)
Constructs an application object with argc command line arguments in argv.
If GUIenabled is true, a GUI application is constructed, otherwise a non-GUI (console) application is created.
Warning
The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string.
Set GUIenabled to false for programs without a graphical user interface that should be able to run without a window system.
On X11, the window system is initialized if GUIenabled is true. If GUIenabled is false, the application does not connect to the X server. On Windows and Mac OS, currently the window system is always initialized, regardless of the value of GUIenabled. This may change in future versions of Qt.
The following example shows how to create an application that uses a graphical interface when available.
int main(int argc, char **argv)
{
#ifdef Q_WS_X11
    bool useGUI = getenv("DISPLAY") != 0;
#else
    bool useGUI = true;
#endif
    QApplication app(argc, argv, useGUI);
    if (useGUI) {
       // start GUI version
       ...
    } else {
       // start non-GUI version
       ...
    }
    return app.exec();
}
Definition at line 773 of file qapplication.cpp.
     : QCoreApplication(*new QApplicationPrivate(argc, argv, GUIenabled ? GuiClient : Tty, 0x040000))
 { Q_D(QApplication); d->construct(); }
QApplication() [3/6]
QApplication::QApplication (int & argc, char ** argv, Type type)
Constructs an application object with argc command line arguments in argv.
Warning
The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object. In addition, argc must be greater than zero and argv must contain at least one valid character string.
With Qt for Embedded Linux, passing QApplication::GuiServer for type makes this application the server (equivalent to running with the -qws option).
Definition at line 796 of file qapplication.cpp.
     : QCoreApplication(*new QApplicationPrivate(argc, argv, type, 0x040000))
 { Q_D(QApplication); d->construct(); }
QApplication() [4/6]
QApplication::QApplication (Display * display, Qt::HANDLE visual = 0, Qt::HANDLE colormap = 0)
Creates an application, given an already open display display.
If visual and colormap are non-zero, the application will use those values as the default Visual and Colormap contexts.
Warning
Qt only supports TrueColor visuals at depths higher than 8 bits-per-pixel.
This function is only available on X11.
Definition at line 911 of file qapplication.cpp.
     : QCoreApplication(*new QApplicationPrivate(aargc, aargv, GuiClient, 0x040000))
 {
     if (! dpy)
         qWarning("QApplication: Invalid Display* argument");
     Q_D(QApplication);
     d->construct(dpy, visual, colormap);
 }
QApplication() [5/6]
QApplication::QApplication (Display * display, int & argc, char ** argv, Qt::HANDLE visual = 0, Qt::HANDLE colormap = 0)
Creates an application, given an already open display and using argc command line arguments in argv.
If visual and colormap are non-zero, the application will use those values as the default Visual and Colormap contexts.
Warning
Qt only supports TrueColor visuals at depths higher than 8 bits-per-pixel.
This function is only available on X11.
Definition at line 944 of file qapplication.cpp.
     : QCoreApplication(*new QApplicationPrivate(argc, argv, GuiClient, 0x040000))
 {
     if (! dpy)
         qWarning("QApplication: Invalid Display* argument");
     Q_D(QApplication);
     d->construct(dpy, visual, colormap);
 }
QApplication() [6/6]
QApplication::QApplication (QApplication::QS60MainApplicationFactory factory, int & argc, char ** argv)
Functions
aboutQt
void QApplication::aboutQt () static slot
Displays a simple message box about Qt.
The message includes the version number of Qt being used by the application.
This is useful for inclusion in the Help menu of an application, as shown in the Menus example.
This function is a convenience slot for QMessageBox::aboutQt().
Definition at line 2400 of file qapplication.cpp.
 {
 #ifndef QT_NO_MESSAGEBOX
     QMessageBox::aboutQt(
 #ifdef Q_WS_MAC
             0
 #else
             activeWindow()
 #endif // Q_WS_MAC
             );
 #endif // QT_NO_MESSAGEBOX
 }
activeModalWidget()
QWidget * QApplication::activeModalWidget () static
Returns the active modal widget.
A modal widget is a special top-level widget which is a subclass of QDialog that specifies the modal parameter of the constructor as true. A modal widget must be closed before the user can continue with other parts of the program.
Modal widgets are organized in a stack. This function returns the active modal widget at the top of the stack.
See also
activePopupWidget(), topLevelWidgets()
Definition at line 1095 of file qapplication.cpp.
Referenced by closeAllWindows(), QApplicationPrivate::dispatchEnterLeave(), QWidget::event(), QAxServerBase::eventFilter(), QApplicationPrivate::globalEventProcessor(), qt_mac_mouse_inside_answer_rect(), qwsProcessEvent(), QSoftKeyManager::softkeySource(), QApplicationPrivate::tryModalHelper(), QGraphicsView::viewportEvent(), and QAxClientSite::windowActivationChange().
 {
     return qt_modal_stack && !qt_modal_stack->isEmpty() ? qt_modal_stack->first() : 0;
 }
activePopupWidget()
QWidget * QApplication::activePopupWidget () static
Returns the active popup widget.
A popup widget is a special top-level widget that sets the Qt::WType_Popup widget flag, e.g. the QMenu widget. When the application opens a popup widget, all events are sent to the popup. Normal widgets and modal widgets cannot be accessed before the popup widget is closed.
Only other popup widgets may be opened when a popup widget is shown. The popup widgets are organized in a stack. This function returns the active popup widget at the top of the stack.
See also
activeModalWidget(), topLevelWidgets()
Definition at line 1074 of file qapplication.cpp.
Referenced by QMenuPrivate::activateAction(), QShortcutMap::correctContext(), QApplicationPrivate::dispatchEnterLeave(), QToolBar::event(), QWidget::event(), QWidgetResizeHandler::eventFilter(), flipPoint(), QLineEdit::focusOutEvent(), QApplicationPrivate::globalEventProcessor(), QApplicationPrivate::isBlockedByModal(), QWidget::mousePressEvent(), notify(), QApplicationPrivate::notify_helper(), onApplicationChangedActivation(), qt_mac_handleTabletEvent(), QtWndProc(), qwsProcessEvent(), QTest::sendKeyEvent(), QApplicationPrivate::sendMouseEvent(), QWidgetPrivate::show_helper(), QSoftKeyManager::softkeySource(), QETWidget::translateMouseEvent(), QETWidget::translateWheelEvent(), QApplicationPrivate::tryModalHelper(), QGraphicsView::viewportEvent(), and x11ProcessEvent().
 {
     return QApplicationPrivate::popupWidgets && !QApplicationPrivate::popupWidgets->isEmpty() ?
         QApplicationPrivate::popupWidgets->last() : 0;
 }
activeWindow()
QWidget * QApplication::activeWindow () static
Returns the application top-level window that has the keyboard input focus, or 0 if no application window has the focus.
There might be an activeWindow() even if there is no focusWidget(), for example if no widget in that window accepts key events.
See also
QWidget::setFocus(), QWidget::hasFocus(), focusWidget()
Definition at line 2334 of file qapplication.cpp.
Referenced by aboutQt(), QShortcutMap::correctContext(), QWidgetPrivate::deactivateWidgetCleanup(), QAccessibleApplication::doAction(), QApplicationPrivate::globalEventProcessor(), QBBNavigatorEventHandler::handleSwipeDown(), QBBScreenEventHandler::injectKeyboardEvent(), QAccessibleApplication::navigate(), onApplicationChangedActivation(), QPrintDialogPrivate::openWindowsPrintDialogModally(), QWidget::previousInFocusChain(), qstring_to_xtp(), qt_cleanup(), qt_qpa_set_cursor(), qt_try_modal(), qt_win_get_existing_directory(), qt_win_get_save_file_name(), qt_win_make_OFN(), QTest::sendKeyEvent(), QSoftKeyManager::softkeySource(), QAccessibleApplication::state(), QWindowsStyle::styleHint(), QBBButtonEventNotifier::updateButtonStates(), and QGraphicsView::viewportEvent().
 {
     return QApplicationPrivate::active_window;
 }
alert()
void QApplication::alert (QWidget * widget, int msec = 0) static
Since
4.3
Causes an alert to be shown for widget if the window is not the active window. The alert is shown for msec miliseconds. If msec is zero (the default), then the alert is shown indefinitely until the window becomes active again.
Currently this function does nothing on Qt for Embedded Linux.
On Mac OS X, this works more at the application level and will cause the application icon to bounce in the dock.
On Windows, this causes the window's taskbar entry to flash for a time. If msec is zero, the flashing will stop and the taskbar entry will turn a different color (currently orange).
On X11, this will cause the window to be marked as "demands attention", the window must not be hidden (i.e. not have hide() called on it, but be visible in some sort of way) in order for this to work.
Definition at line 2741 of file qapplication_mac.mm.
Referenced by alert_widget(), parseGeometry(), and syncX().
 {
     if (!QApplicationPrivate::checkInstance("alert"))
         return;
     QWidgetList windowsToMark;
     if (!widget)
         windowsToMark += topLevelWidgets();
     else
         windowsToMark.append(widget->window());
     bool needNotification = false;
     for (int i = 0; i < windowsToMark.size(); ++i) {
         QWidget *window = windowsToMark.at(i);
         if (!window->isActiveWindow() && window->isVisible()) {
             needNotification = true; // yeah, we may set it multiple times, but that's OK.
             if (duration != 0) {
                QTimer *timer = new QTimer(qApp);
                timer->setSingleShot(true);
                connect(timer, SIGNAL(timeout()), qApp, SLOT(_q_alertTimeOut()));
                if (QTimer *oldTimer = qApp->d_func()->alertTimerHash.value(widget)) {
                    qApp->d_func()->alertTimerHash.remove(widget);
                    delete oldTimer;
                }
                qApp->d_func()->alertTimerHash.insert(widget, timer);
                timer->start(duration);
             }
         }
     }
     if (needNotification)
         qt_mac_send_notification();
 }
allWidgets()
QWidgetList QApplication::allWidgets () static
Returns a list of all the widgets in the application.
The list is empty (QList::isEmpty()) if there are no widgets.
Note
Some of the widgets may be hidden.
Example:
void updateAllWidgets()
{
    foreach (QWidget *widget, QApplication::allWidgets())
        widget->update();
}
See also
topLevelWidgets(), QWidget::isVisible()
Definition at line 2214 of file qapplication.cpp.
Referenced by QWidgetPrivate::frameStrut(), setFont(), QApplicationPrivate::setPalette_helper(), setStyle(), setWindowIcon(), topLevelWidgets(), update_toolbar_style(), and QGtkStyleUpdateScheduler::updateTheme().
 {
     if (QWidgetPrivate::allWidgets)
         return QWidgetPrivate::allWidgets->toList();
     return QWidgetList();
 }
autoMaximizeThreshold
int QApplication::autoMaximizeThreshold () const slot
Referenced by setAutoMaximizeThreshold().
autoSipEnabled
bool QApplication::autoSipEnabled () const slot
Referenced by setAutoSipEnabled().
beep()
void QApplication::beep () static
Sounds the bell, using the default volume and sound.
The function is not available in Qt for Embedded Linux.
Definition at line 2736 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::globalAppleEventProcessor(), QApplicationPrivate::globalEventProcessor(), QKeyMapperPrivate::isADeadKey(), QMenu::keyPressEvent(), parseGeometry(), qt_try_modal(), qt_win_getKeyboardModifiers(), and syncX().
 {
     qt_mac_beep();
 }
changeOverrideCursor()
void QApplication::changeOverrideCursor (const QCursor & cursor) static
Changes the currently active application override cursor to cursor.
This function has no effect if setOverrideCursor() was not called.
See also
setOverrideCursor(), overrideCursor(), restoreOverrideCursor(), QWidget::setCursor()
Definition at line 3868 of file qapplication.cpp.
Referenced by QWhatsThisPrivate::eventFilter().
 {
     if (qApp->d_func()->cursor_list.isEmpty())
         return;
     qApp->d_func()->cursor_list.removeFirst();
     setOverrideCursor(cursor);
 }
clipboard()
QClipboard * QApplication::clipboard () static
Returns a pointer to the application global clipboard.
Note
The QApplication object should already be constructed before accessing the clipboard.
Definition at line 3336 of file qapplication.cpp.
Referenced by QTextControlPrivate::_q_copyLink(), QTextControl::canPaste(), QX11Data::clipboardWaitForEvent(), QLineControl::copy(), QTextControl::copy(), QmlJSDebugger::ToolBarColorBox::copyColorToClipboard(), QAccessibleTextWidget::copyText(), QAccessibleSimpleEditableTextInterface::copyText(), QLineEdit::createStandardContextMenu(), QAccessibleTextWidget::cutText(), QAccessibleSimpleEditableTextInterface::cutText(), QPlatformClipboard::emitChanged(), QDeclarativeTextEditPrivate::init(), QDeclarativeTextInputPrivate::init(), QMessageBox::keyPressEvent(), QAbstractItemView::keyPressEvent(), QTextControlPrivate::mouseReleaseEvent(), QLineEdit::mouseReleaseEvent(), QLineControl::paste(), QTextControl::paste(), QAccessibleTextWidget::pasteText(), QAccessibleSimpleEditableTextInterface::pasteText(), QLineControl::processMouseEvent(), QDeclarativeTextInput::q_canPasteChanged(), QClipboardINCRTransaction::QClipboardINCRTransaction(), qt_check_clipboard_sentinel(), qt_check_selection_sentinel(), QTextControlPrivate::setClipboardSelection(), and QClipboardINCRTransaction::x11Event().
 {
     if (qt_clipboard == 0) {
         if (!qApp) {
             qWarning("QApplication: Must construct a QApplication before accessing a QClipboard");
             return 0;
         }
         qt_clipboard = new QClipboard(0);
     }
     return qt_clipboard;
 }
closeAllWindows
void QApplication::closeAllWindows () static slot
Closes all top-level windows.
This function is particularly useful for applications with many top-level windows. It could, for example, be connected to a Exit entry in the File menu:
    exitAct = new QAction(tr("E&xit"), this);
    exitAct->setShortcuts(QKeySequence::Quit);
    exitAct->setStatusTip(tr("Exit the application"));
    connect(exitAct, SIGNAL(triggered()), qApp, SLOT(closeAllWindows()));
The windows are closed in random order, until one window does not accept the close event. The application quits when the last window was successfully closed; this can be turned off by setting quitOnLastWindowClosed to false.
See also
quitOnLastWindowClosed, lastWindowClosed(), QWidget::close(), QWidget::closeEvent(), lastWindowClosed(), quit(), topLevelWidgets(), QWidget::isWindow()
Definition at line 2369 of file qapplication.cpp.
Referenced by event().
 {
     bool did_close = true;
     QWidget *w;
     while ((w = activeModalWidget()) && did_close) {
         if (!w->isVisible() || w->data->is_closing)
             break;
         did_close = w->close();
     }
     QWidgetList list = QApplication::topLevelWidgets();
     for (int i = 0; did_close && i < list.size(); ++i) {
         w = list.at(i);
         if (w->isVisible()
             && w->windowType() != Qt::Desktop
             && !w->data->is_closing) {
             did_close = w->close();
             list = QApplication::topLevelWidgets();
             i = -1;
         }
     }
 }
colorSpec()
int QApplication::colorSpec () static
Returns the color specification.
See also
QApplication::setColorSpec()
Definition at line 1706 of file qapplication.cpp.
 {
     return QApplicationPrivate::app_cspec;
 }
commitData()
void QApplication::commitData (QSessionManager & manager) virtual
This function deals with Session Management{session management}.
It is invoked when the QSessionManager wants the application to commit all its data.
Usually this means saving all open files, after getting permission from the user. Furthermore you may want to provide a means by which the user can cancel the shutdown.
You should not exit the application within this function. Instead, the session manager may or may not do this afterwards, depending on the context.
Warning
Within this function, no user interaction is possible, unless you ask the manager for explicit permission. See QSessionManager::allowsInteraction() and QSessionManager::allowsErrorInteraction() for details and example usage.
The default implementation requests interaction and sends a close event to all visible top-level widgets. If any event was rejected, the shutdown is canceled.
See also
isSessionRestored(), sessionId(), saveState(), {Session Management}
Definition at line 3592 of file qapplication.cpp.
 {
     emit commitDataRequest(manager);
     if (manager.allowsInteraction()) {
         QWidgetList done;
         QWidgetList list = QApplication::topLevelWidgets();
         bool cancelled = false;
         for (int i = 0; !cancelled && i < list.size(); ++i) {
             QWidget* w = list.at(i);
             if (w->isVisible() && !done.contains(w)) {
                 cancelled = !w->close();
                 if (!cancelled)
                     done.append(w);
                 list = QApplication::topLevelWidgets();
                 i = -1;
             }
         }
         if (cancelled)
             manager.cancel();
     }
 }
commitDataRequest
void QApplication::commitDataRequest (QSessionManager & manager) signal
This signal deals with Session Management{session management}.
Since
4.2
It is emitted when the QSessionManager wants the application to commit all its data.
Usually this means saving all open files, after getting permission from the user. Furthermore you may want to provide a means by which the user can cancel the shutdown.
You should not exit the application within this signal. Instead, the session manager may or may not do this afterwards, depending on the context.
Warning
Within this signal, no user interaction is possible, unless you ask the manager for explicit permission. See QSessionManager::allowsInteraction() and QSessionManager::allowsErrorInteraction() for details and example usage.
Note
You should use Qt::DirectConnection when connecting to this signal.
See also
isSessionRestored(), sessionId(), saveState(), {Session Management}
Referenced by commitData().
compressEvent()
bool QApplication::compressEvent (QEvent * event, QObject * receiver, QPostEventList * postedEvents) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QCoreApplication.
Definition at line 1298 of file qapplication.cpp.
 {
     if ((event->type() == QEvent::UpdateRequest
 #ifdef QT3_SUPPORT
           || event->type() == QEvent::LayoutHint
 #endif
           || event->type() == QEvent::LayoutRequest
           || event->type() == QEvent::Resize
           || event->type() == QEvent::Move
           || event->type() == QEvent::LanguageChange
           || event->type() == QEvent::UpdateSoftKeys
           || event->type() == QEvent::InputMethod)) {
         for (QPostEventList::const_iterator it = postedEvents->constBegin(); it != postedEvents->constEnd(); ++it) {
             const QPostEvent &cur = *it;
             if (cur.receiver != receiver || cur.event == 0 || cur.event->type() != event->type())
                 continue;
             if (cur.event->type() == QEvent::LayoutRequest
 #ifdef QT3_SUPPORT
                  || cur.event->type() == QEvent::LayoutHint
 #endif
                  || cur.event->type() == QEvent::UpdateRequest) {
                 ;
             } else if (cur.event->type() == QEvent::Resize) {
                 ((QResizeEvent *)(cur.event))->s = ((QResizeEvent *)event)->s;
             } else if (cur.event->type() == QEvent::Move) {
                 ((QMoveEvent *)(cur.event))->p = ((QMoveEvent *)event)->p;
             } else if (cur.event->type() == QEvent::LanguageChange) {
                 ;
             } else if (cur.event->type() == QEvent::UpdateSoftKeys) {
                 ;
             } else if ( cur.event->type() == QEvent::InputMethod ) {
                 *(QInputMethodEvent *)(cur.event) = *(QInputMethodEvent *)event;
             } else {
                 continue;
             }
             delete event;
             return true;
         }
         return false;
     }
     return QCoreApplication::compressEvent(event, receiver, postedEvents);
 }
cursorFlashTime()
static int QApplication::cursorFlashTime () static
Referenced by QLineEdit::event(), QLineEdit::focusInEvent(), QApplicationPrivate::qt_mac_apply_settings(), QTextControlPrivate::setBlinkingCursorEnabled(), setCursorFlashTime(), QDeclarativeTextInput::setCursorVisible(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
desktop()
QDesktopWidget * QApplication::desktop () static
Returns the desktop widget (also called the root window).
The desktop may be composed of multiple screens, so it would be incorrect, for example, to attempt to center some widget in the desktop's geometry. QDesktopWidget has various functions for obtaining useful geometries upon the desktop, such as QDesktopWidget::screenGeometry() and QDesktopWidget::availableGeometry().
On X11, it is also possible to draw on the desktop.
Definition at line 3320 of file qapplication.cpp.
Referenced by QPushButtonPrivate::adjustedMenuPosition(), QWidgetPrivate::adjustedSize(), QDialog::adjustPosition(), QApplicationPrivate::applyX11SpecificCommandLineArguments(), QBalloonTip::balloon(), QVistaHelper::basicWindowFrameColor(), QWidgetPrivate::create_sys(), QApplicationPrivate::dispatchEnterLeave(), QVistaHelper::drawTitleText(), effectiveState(), QDockWidget::event(), find_trans_colors(), findRealWindow(), flipYCoordinate(), fontMetrics(), QClipboardWatcher::getDataInFormat(), getScreen(), QTipLabel::getTipScreen(), QTabWidget::heightForWidth(), QColorDialogPrivate::init(), QFontDialogPrivate::init(), QWidgetResizeHandler::keyPressEvent(), QWidgetPrivate::mapFromGlobal(), QWidgetPrivate::mapToGlobal(), QMenuBar::minimumSizeHint(), QWidgetResizeHandler::mouseMoveEvent(), QSizeGrip::mousePressEvent(), parseGeometry(), QWSOnScreenSurface::permanentState(), QTipLabel::placeTip(), QMenu::popup(), QMenuBarPrivate::popupAction(), QMenuPrivate::popupGeometry(), QComboBoxPrivate::popupGeometry(), QToolButtonPrivate::popupTimerDone(), QDateTimeEditPrivate::positionCalendarPopup(), QBalloonTip::QBalloonTip(), qstring_to_xtp(), qt_check_clipboard_sentinel(), qt_check_selection_sentinel(), qt_cleanup(), qt_grab_cursor(), qt_qpa_set_cursor(), QWhatsThat::QWhatsThat(), QWidget::restoreGeometry(), QDockAreaLayoutInfo::restoreState(), QAlphaWidget::run(), QWidget::saveGeometry(), QWhatsThisPrivate::say(), QWidgetPrivate::setGeometry_sys(), QApplicationPrivate::setMaxWindowRect(), QWidgetPrivate::setMinimumSize_helper(), QSplashScreen::setPixmap(), QApplicationPrivate::setScreenTransformation(), QWizardHeader::setup(), QWidget::setWindowState(), QWhatsThat::showEvent(), QCompleterPrivate::showPopup(), QComboBox::showPopup(), QToolTip::showText(), QWorkspace::sizeHint(), QProgressDialog::sizeHint(), QMdiArea::sizeHint(), QMenuBar::sizeHint(), QGraphicsView::sizeHint(), QTabWidget::sizeHint(), QWizard::sizeHint(), QWindowsXPStylePrivate::tabBody(), QPlatformScreen::topLevelAt(), QETWidget::translateConfigEvent(), QETWidget::translateTabletEvent(), QApplicationPrivate::translateTouchEvent(), QGLContext::updatePaintDevice(), QMessageBoxPrivate::updateSize(), and x11ProcessEvent().
 {
     if (!qt_desktopWidget || // not created yet
          !(qt_desktopWidget->windowType() == Qt::Desktop)) { // reparented away
         qt_desktopWidget = new QDesktopWidget();
     }
     return qt_desktopWidget;
 }
desktopSettingsAware()
bool QApplication::desktopSettingsAware () static
Returns true if Qt is set to use the system's standard colors, fonts, etc.
; otherwise returns false. The default is true.
See also
setDesktopSettingsAware()
Definition at line 3371 of file qapplication.cpp.
Referenced by QMdiSubWindowPrivate::desktopPalette(), QMacStyle::drawComplexControl(), QApplicationPrivate::globalEventProcessor(), onApplicationChangedActivation(), QGuiPlatformPlugin::palette(), QCommonStyle::pixelMetric(), QGuiPlatformPlugin::platformHint(), QWindowsStyle::polish(), QGtkStyle::polish(), qt_aqua_get_known_size(), qt_guiPlatformPlugin(), qt_init(), qt_set_qws_resources(), qt_set_x11_resources(), QtWndProc(), QWorkspaceTitleBarPrivate::readColors(), QMacStyle::sizeFromContents(), QCommonStyle::standardIconImplementation(), QCommonStyle::standardPixmap(), QMacStyle::subControlRect(), and QGtkStyle::unpolish().
 {
     return QApplicationPrivate::obey_desktop_settings;
 }
doubleClickInterval()
static int QApplication::doubleClickInterval () static
Referenced by QAbstractItemView::edit(), QWorkspace::eventFilter(), QTextControlPrivate::mouseDoubleClickEvent(), QLineEdit::mouseDoubleClickEvent(), QXlibWindow::mousePressEvent(), QComboBox::mousePressEvent(), QWorkspaceTitleBar::mousePressEvent(), QAbstractItemView::mousePressEvent(), QLineControl::processMouseEvent(), qt_cleanup(), QApplicationPrivate::qt_mac_apply_settings(), setDoubleClickInterval(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::translateMouseEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
event()
bool QApplication::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QCoreApplication.
Definition at line 2504 of file qapplication.cpp.
Referenced by compressEvent(), notify(), and ~QApplication().
 {
     Q_D(QApplication);
     if(e->type() == QEvent::Close) {
 #if defined(Q_OS_SYMBIAN)
         // In order to have proper application-exit effects on Symbian, certain
         // native APIs have to be called _before_ closing/destroying the widgets.
         bool effectStarted = qt_beginFullScreenEffect();
 #endif
         QCloseEvent *ce = static_cast<QCloseEvent*>(e);
         ce->accept();
         closeAllWindows();
         QWidgetList list = topLevelWidgets();
         for (int i = 0; i < list.size(); ++i) {
             QWidget *w = list.at(i);
             if (w->isVisible() && !(w->windowType() == Qt::Desktop) && !(w->windowType() == Qt::Popup) &&
                  (!(w->windowType() == Qt::Dialog) || !w->parentWidget())) {
                 ce->ignore();
                 break;
             }
         }
         if (ce->isAccepted()) {
             return true;
         } else {
 #if defined(Q_OS_SYMBIAN)
             if (effectStarted)
                 qt_abortFullScreenEffect();
 #endif
         }
     } else if(e->type() == QEvent::LanguageChange) {
 #ifndef QT_NO_TRANSLATION
         setLayoutDirection(qt_detectRTLLanguage()?Qt::RightToLeft:Qt::LeftToRight);
 #endif
 #if defined(QT_MAC_USE_COCOA)
         qt_mac_post_retranslateAppMenu();
 #endif
         QWidgetList list = topLevelWidgets();
         for (int i = 0; i < list.size(); ++i) {
             QWidget *w = list.at(i);
             if (!(w->windowType() == Qt::Desktop))
                 postEvent(w, new QEvent(QEvent::LanguageChange));
         }
 #ifndef Q_OS_WIN
     } else if (e->type() == QEvent::LocaleChange) {
         // on Windows the event propagation is taken care by the
         // WM_SETTINGCHANGE event handler.
         QWidgetList list = topLevelWidgets();
         for (int i = 0; i < list.size(); ++i) {
             QWidget *w = list.at(i);
             if (!(w->windowType() == Qt::Desktop)) {
                 if (!w->testAttribute(Qt::WA_SetLocale))
                     w->d_func()->setLocale_helper(QLocale(), true);
             }
         }
 #endif
     } else if (e->type() == QEvent::Timer) {
         QTimerEvent *te = static_cast<QTimerEvent*>(e);
         Q_ASSERT(te != 0);
         if (te->timerId() == d->toolTipWakeUp.timerId()) {
             d->toolTipWakeUp.stop();
             if (d->toolTipWidget) {
                 QWidget *w = d->toolTipWidget->window();
                 // show tooltip if WA_AlwaysShowToolTips is set, or if
                 // any ancestor of d->toolTipWidget is the active
                 // window
                 bool showToolTip = w->testAttribute(Qt::WA_AlwaysShowToolTips);
                 while (w && !showToolTip) {
                     showToolTip = w->isActiveWindow();
                     w = w->parentWidget();
                     w = w ? w->window() : 0;
                 }
                 if (showToolTip) {
                     QHelpEvent e(QEvent::ToolTip, d->toolTipPos, d->toolTipGlobalPos);
                     QApplication::sendEvent(d->toolTipWidget, &e);
                     if (e.isAccepted())
                         d->toolTipFallAsleep.start(2000, this);
                 }
             }
         } else if (te->timerId() == d->toolTipFallAsleep.timerId()) {
             d->toolTipFallAsleep.stop();
         }
     }
     return QCoreApplication::event(e);
 }
exec()
int QApplication::exec () static
Enters the main event loop and waits until exit() is called, then returns the value that was set to exit() (which is 0 if exit() is called via quit()).
It is necessary to call this function to start event handling. The main event loop receives events from the window system and dispatches these to the application widgets.
Generally, no user interaction can take place before calling exec(). As a special case, modal widgets like QMessageBox can be used before calling exec(), because modal widgets call exec() to start a local event loop.
To make your application perform idle processing, i.e., executing a special function whenever there are no pending events, use a QTimer with 0 timeout. More advanced idle processing schemes can be achieved using processEvents().
We recommend that you connect clean-up code to the QCoreApplication::aboutToQuit() signal, instead of putting it in your application's main() function. This is because, on some platforms the QApplication::exec() call may not return. For example, on the Windows platform, when the user logs off, the system terminates the process after Qt closes all top-level windows. Hence, there is no guarantee that the application will have time to exit its event loop and execute code at the end of the main() function, after the QApplication::exec() call.
See also
quitOnLastWindowClosed, quit(), exit(), processEvents(), QCoreApplication::exec()
Definition at line 3916 of file qapplication.cpp.
Referenced by main().
 {
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::setRootObject(qApp);
 #endif
     return QCoreApplication::exec();
 }
focusChanged
void QApplication::focusChanged (QWidget * old, QWidget * now) signal
Since
4.1
This signal is emitted when the widget that has keyboard focus changed from old to now, i.e., because the user pressed the tab-key, clicked into a widget or changed the active window. Both old and now can be the null-pointer.
The signal is emitted after both widget have been notified about the change through QFocusEvent.
See also
QWidget::setFocus(), QWidget::clearFocus(), Qt::FocusReason
focusWidget()
QWidget * QApplication::focusWidget () static
Returns the application widget that has the keyboard input focus, or 0 if no widget in this application has the focus.
See also
QWidget::setFocus(), QWidget::hasFocus(), activeWindow(), focusChanged()
Definition at line 2228 of file qapplication.cpp.
Referenced by QAbstractItemViewPrivate::checkPersistentEditorFocus(), QApplicationPrivate::closePopup(), QWinInputContext::composition(), QShortcutMap::correctWidgetContext(), QXIMInputContext::create_xim(), QTreeView::drawRow(), QWinInputContext::endComposition(), QMotifStyle::event(), QMacStyle::event(), QStyledItemDelegate::eventFilter(), QItemDelegate::eventFilter(), QWidgetPrivate::frameStrut(), QApplicationPrivate::globalEventProcessor(), QBBScreenEventHandler::handleKeyboardEvent(), QWidget::hasFocus(), QWidgetPrivate::hide_helper(), QMenu::keyPressEvent(), QTabWidget::keyPressEvent(), QAbstractItemView::keyPressEvent(), QAbstractButtonPrivate::moveFocus(), qt_cleanup(), qt_try_modal(), QtWndProc(), QTest::sendKeyEvent(), QMdiSubWindowPrivate::setActive(), QWidget::setFocus(), QGraphicsItem::setInputMethodHints(), QMenuBarPrivate::setKeyboardMode(), QMdiSubWindowPrivate::setMaximizeMode(), QMdiSubWindow::showShaded(), QSoftKeyManager::softkeySource(), QAccessibleMdiSubWindow::state(), QETWidget::translateWheelEvent(), and QGraphicsItem::updateMicroFocus().
 {
     return QApplicationPrivate::focus_widget;
 }
font() [1/3]
QFont QApplication::font () static
Returns the default application font.
See also
fontMetrics(), QWidget::font()
Definition at line 1982 of file qapplication.cpp.
Referenced by QPPDOptionsModel::data(), QVistaHelper::drawTitleBar(), QGraphicsWidget::event(), QWidget::event(), QFontDatabase::findFont(), QToolTip::font(), QTextItem::font(), QInputContext::font(), QFontDatabase::font(), font(), getFcPattern(), QGraphicsWidgetPrivate::initStyleOptionTitleBar(), loadFromDatabase(), loadWin(), QWidgetPrivate::naturalWidgetFont(), QGraphicsWidget::paintWindowFrame(), QMdiSubWindow::QMdiSubWindow(), QApplicationPrivate::qt_mac_apply_settings(), QWhatsThat::QWhatsThat(), QMdi::SimpleCascader::rearrange(), registerFont(), QWidgetBackingStore::removeDirtyWidget(), QFont::resolve(), QGraphicsScenePrivate::resolveFont(), setFont(), QGraphicsScene::setFont(), QApplicationPrivate::setSystemFont(), QWindowsVistaStyle::unpolish(), QMessageBoxPrivate::updateSize(), QGtkStyleUpdateScheduler::updateTheme(), and QApplicationPrivate::x11_apply_settings().
 {
     QMutexLocker locker(applicationFontMutex());
     if (!QApplicationPrivate::app_font) {
 #if defined(Q_OS_BLACKBERRY)
         // See http://docs.blackberry.com/en/developers/deliverables/41577/typography.jsp
         // which recommends using font family "Slate Pro" and normal font size of 8 points
         QApplicationPrivate::app_font = new QFont(QLatin1String("Slate Pro"));
         QApplicationPrivate::app_font->setPointSize(8);
 #else
         QApplicationPrivate::app_font = new QFont(QLatin1String("Helvetica"));
 #endif
     }
     return *QApplicationPrivate::app_font;
 }
font() [2/3]
QFont QApplication::font (const QWidget * widget) static
Returns the default font for the widget.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
fontMetrics(), QWidget::setFont()
Definition at line 2009 of file qapplication.cpp.
 {
     FontHash *hash = app_fonts();
 #ifdef Q_WS_MAC
     // short circuit for small and mini controls
     if (widget->testAttribute(Qt::WA_MacSmallSize)) {
         return hash->value("QSmallFont");
     } else if (widget->testAttribute(Qt::WA_MacMiniSize)) {
         return hash->value("QMiniFont");
     }
 #endif
     if (widget && hash  && hash->size()) {
         QHash<QByteArray, QFont>::ConstIterator it =
                 hash->constFind(widget->metaObject()->className());
         if (it != hash->constEnd())
             return it.value();
         for (it = hash->constBegin(); it != hash->constEnd(); ++it) {
             if (widget->inherits(it.key()))
                 return it.value();
         }
     }
     return font();
 }
font() [3/3]
QFont QApplication::font (const char * className) static
Returns the font for widgets of the given className.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setFont(), QWidget::font()
Definition at line 2044 of file qapplication.cpp.
 {
     FontHash *hash = app_fonts();
     if (className && hash && hash->size()) {
         QHash<QByteArray, QFont>::ConstIterator it = hash->constFind(className);
         if (it != hash->constEnd())
             return *it;
     }
     return font();
 }
fontDatabaseChanged
void QApplication::fontDatabaseChanged () signal
This signal is emitted when application fonts are loaded or removed.
Since
4.5
See also
QFontDatabase::addApplicationFont(), QFontDatabase::addApplicationFontFromData(), QFontDatabase::removeAllApplicationFonts(), QFontDatabase::removeApplicationFont()
fontMetrics()
QFontMetrics QApplication::fontMetrics () static
Returns display (screen) font metrics for the application font.
See also
font(), setFont(), QWidget::fontMetrics(), QPainter::fontMetrics()
Definition at line 2345 of file qapplication.cpp.
Referenced by QDecorationWindows::region(), and QDecorationDefault::titleBarHeight().
 {
     return desktop()->fontMetrics();
 }
globalStrut()
static QSize QApplication::globalStrut () static
Referenced by QWindowsStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QTabBarPrivate::extraWidth(), QTabWidget::heightForWidth(), QMdiSubWindow::minimumSizeHint(), QMdiArea::minimumSizeHint(), QMenuBar::minimumSizeHint(), QAbstractSpinBox::minimumSizeHint(), QTabWidget::minimumSizeHint(), QLineEdit::minimumSizeHint(), QTabBar::minimumSizeHint(), QCommonStyle::pixelMetric(), QWindowsXPStyle::pixelMetric(), QWindowsStyle::pixelMetric(), QWindowsCEStyle::pixelMetric(), QWindowsMobileStyle::pixelMetric(), QMotifStyle::pixelMetric(), QMacStyle::pixelMetric(), QComboBoxPrivate::recomputeSizeHint(), QMenuPrivate::scrollerHeight(), setColorSpec(), QHeaderView::setDefaultSectionSize(), QSizeGrip::sizeHint(), QRadioButton::sizeHint(), QScrollBar::sizeHint(), QCheckBox::sizeHint(), QPushButton::sizeHint(), QToolBoxButton::sizeHint(), QDial::sizeHint(), QToolButton::sizeHint(), QSlider::sizeHint(), QMdiArea::sizeHint(), QMenuBar::sizeHint(), QAbstractSpinBox::sizeHint(), QTabWidget::sizeHint(), QLineEdit::sizeHint(), QMenu::sizeHint(), DetailButton::sizeHint(), QTabBar::sizeHint(), QDateTimeEdit::sizeHint(), QSplitterHandle::sizeHint(), QCommonStyle::subControlRect(), QWindowsMobileStyle::subControlRect(), QWindowsCEStyle::subControlRect(), QMotifStyle::subControlRect(), QMenuPrivate::updateActionRects(), and QExpandingLineEdit::updateMinimumWidth().
inputContext()
QInputContext * QApplication::inputContext () const
Returns the QInputContext instance used by the application.
See also
setInputContext()
Definition at line 5719 of file qapplication.cpp.
Referenced by inputContext().
 {
     Q_D(const QApplication);
     Q_UNUSED(d);// only static members being used.
     if (QApplicationPrivate::is_app_closing)
         return d->inputContext;
 #ifdef Q_WS_X11
     if (!X11)
         return 0;
     if (!d->inputContext) {
         QApplication *that = const_cast<QApplication *>(this);
         QInputContext *qic = QInputContextFactory::create(X11->default_im, that);
         // fallback to default X Input Method.
         if (!qic)
             qic = QInputContextFactory::create(QLatin1String("xim"), that);
         that->d_func()->inputContext = qic;
     }
 #elif defined(Q_OS_SYMBIAN)
     if (!d->inputContext) {
         QApplication *that = const_cast<QApplication *>(this);
         const QStringList keys = QInputContextFactory::keys();
         // Try hbim and coefep first, then try others.
         if (keys.contains(QLatin1String("hbim"))) {
             that->d_func()->inputContext = QInputContextFactory::create(QLatin1String("hbim"), that);
         } else if (keys.contains(QLatin1String("coefep"))) {
             if (!that->d_func()->inputContextBeingCreated) {
                 that->d_func()->inputContextBeingCreated = true;
                 that->d_func()->inputContext = QInputContextFactory::create(QLatin1String("coefep"), that);
                 that->d_func()->inputContextBeingCreated = false;
             }
         } else {
             for (int c = 0; c < keys.size() && !d->inputContext; ++c) {
                 that->d_func()->inputContext = QInputContextFactory::create(keys[c], that);
             }
         }
     }
 #endif
     return d->inputContext;
 }
isEffectEnabled()
bool QApplication::isEffectEnabled (Qt::UIEffect effect) static
Returns true if effect is enabled; otherwise returns false.
By default, Qt will try to use the desktop settings. To prevent this, call setDesktopSettingsAware(false).
Note
All effects are disabled on screens running at less than 16-bit color depth.
See also
setEffectEnabled(), Qt::UIEffect
Definition at line 2875 of file qapplication_mac.mm.
Referenced by QMenu::popup(), QComboBox::showPopup(), QToolTip::showText(), QTipLabel::timerEvent(), QETWidget::translateCloseEvent(), and QETWidget::updateRegion().
 {
     if (QColormap::instance().depth() < 16 || !QApplicationPrivate::animate_ui)
         return false;
     switch(effect) {
     case Qt::UI_AnimateMenu:
         return QApplicationPrivate::animate_menu;
     case Qt::UI_FadeMenu:
         return QApplicationPrivate::fade_menu;
     case Qt::UI_AnimateCombo:
         return QApplicationPrivate::animate_combo;
     case Qt::UI_AnimateTooltip:
         return QApplicationPrivate::animate_tooltip;
     case Qt::UI_FadeTooltip:
         return QApplicationPrivate::fade_tooltip;
     case Qt::UI_AnimateToolBox:
         return QApplicationPrivate::animate_toolbox;
     default:
         break;
     }
     return QApplicationPrivate::animate_ui;
 }
isLeftToRight()
bool QApplication::isLeftToRight () inline static
Returns true if the application's layout direction is Qt::LeftToRight; otherwise returns false.
See also
layoutDirection(), isRightToLeft()
Definition at line 234 of file qapplication.h.
 { return layoutDirection() == Qt::LeftToRight; }
isRightToLeft()
bool QApplication::isRightToLeft () inline static
Returns true if the application's layout direction is Qt::RightToLeft; otherwise returns false.
See also
layoutDirection(), isLeftToRight()
Definition at line 233 of file qapplication.h.
Referenced by do_size_hints(), QXlibWindow::doSizeHints(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QAbstractScrollArea::event(), QPlainTextEdit::event(), getNetWmState(), QStyle::itemPixmapRect(), qDrawPlainRect(), qt_aqua_get_known_size(), QCommonStyle::standardIconImplementation(), and QCommonStyle::standardPixmap().
 { return layoutDirection() == Qt::RightToLeft; }
isSessionRestored()
bool QApplication::isSessionRestored () const
Returns true if the application has been restored from an earlier Session Management{session}; otherwise returns false.
See also
sessionId(), commitData(), saveState()
Definition at line 3481 of file qapplication.cpp.
 {
     Q_D(const QApplication);
     return d->is_session_restored;
 }
keyboardInputDirection()
Qt::LayoutDirection QApplication::keyboardInputDirection () static
Returns the current keyboard input direction.
Since
4.2
Definition at line 5808 of file qapplication.cpp.
Referenced by QDeclarativeTextPrivate::determineHorizontalAlignment(), QDeclarativeTextEditPrivate::determineHorizontalAlignment(), QDeclarativeTextInputPrivate::determineHorizontalAlignment(), QTextEngine::isRightToLeft(), and QLineControl::layoutDirection().
 {
     if (!QApplicationPrivate::checkInstance("keyboardInputDirection"))
         return Qt::LeftToRight;
     return qt_keymapper_private()->keyboardInputDirection;
 }
keyboardInputInterval()
static int QApplication::keyboardInputInterval () static
Referenced by QTreeView::keyboardSearch(), QAbstractItemView::keyboardSearch(), setKeyboardInputInterval(), QMdiAreaPrivate::startTabToPreviousTimer(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), and QETWidget::updateRegion().
keyboardInputLocale()
QLocale QApplication::keyboardInputLocale () static
Returns the current keyboard input locale.
Since
4.2
Definition at line 5793 of file qapplication.cpp.
 {
     if (!QApplicationPrivate::checkInstance("keyboardInputLocale"))
         return QLocale::c();
     return qt_keymapper_private()->keyboardInputLocale;
 }
keyboardModifiers()
Qt::KeyboardModifiers QApplication::keyboardModifiers () static
Returns the current state of the modifier keys on the keyboard.
The current state is updated sychronously as the event queue is emptied of events that will spontaneously change the keyboard state (QEvent::KeyPress and QEvent::KeyRelease events).
It should be noted this may not reflect the actual keys held on the input device at the time of calling but rather the modifiers as last reported in one of the above events. If no keys are being held Qt::NoModifier is returned.
See also
mouseButtons(), queryKeyboardModifiers()
Definition at line 3390 of file qapplication.cpp.
Referenced by QFileDialogPrivate::_q_enterDirectory(), QDockWidget::event(), QToolBar::event(), QAbstractItemViewPrivate::extendedSelectionCommand(), findRealWindow(), handle_xdnd_position(), QX11Data::motifdndHandle(), QContextMenuEvent::QContextMenuEvent(), qt_cleanup(), qt_mac_dnd_update_action(), qt_mac_mouse_inside_answer_rect(), QCursor::setPos(), QMacStyle::styleHint(), QApplicationPrivate::translateRawTouchEvent(), QETWidget::translateTabletEvent(), and QX11Data::xdndHandleDrop().
 {
     return QApplicationPrivate::modifier_buttons;
 }
lastWindowClosed
void QApplication::lastWindowClosed () signal
This signal is emitted from QApplication::exec() when the last visible primary window (i.
e. window with no parent) with the Qt::WA_QuitOnClose attribute set is closed.
By default,
this attribute is set for all widgets except transient windows such as splash screens, tool windows, and popup menus
QApplication implicitly quits when this signal is emitted.
This feature can be turned off by setting quitOnLastWindowClosed to false.
See also
QWidget::close()
layoutDirection()
static Qt::LayoutDirection QApplication::layoutDirection () static
Referenced by QLayout::alignmentRect(), QFormLayoutPrivate::arrangeWidgets(), QWindowsCEStyle::drawComplexControl(), QStyle::drawItemPixmap(), QWindowsCEStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QBoxLayoutPrivate::effectiveMargins(), QDeclarativeApplication::eventFilter(), QPainterState::init(), QMessageBoxPrivate::init(), QErrorMessage::QErrorMessage(), QTextOption::QTextOption(), QDecorationStyled::region(), QGraphicsWidgetPrivate::resolveLayoutDirection(), QWidgetPrivate::resolveLayoutDirection(), QMessageBox::setInformativeText(), setLayoutDirection(), QDecorationStyled::titleBarHeight(), QMenuPrivate::updateLayoutDirection(), and QGraphicsLayoutPrivate::visualDirection().
macEventFilter()
bool QApplication::macEventFilter (EventHandlerCallRef caller, EventRef event) virtual
Warning
This virtual function is only used under Mac OS X, and behaves different depending on if Qt is based on Carbon or Cocoa.
For the Carbon port, If you create an application that inherits QApplication and reimplement this function, you get direct access to all Carbon Events that Qt registers for from Mac OS X with this function being called with the caller and the event.
For the Cocoa port, If you create an application that inherits QApplication and reimplement this function, you get direct access to all Cocoa Events that Qt receives from Mac OS X with this function being called with the caller being 0 and the event being an NSEvent pointer:
NSEvent *e = reinterpret_cast<NSEvent *>(event);
Return true if you want to stop the event from being processed. Return false for normal event dispatching. The default implementation returns false.
Definition at line 2670 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor().
 {
     return false;
 }
mouseButtons()
Qt::MouseButtons QApplication::mouseButtons () static
Returns the current state of the buttons on the mouse.
The current state is updated syncronously as the event queue is emptied of events that will spontaneously change the mouse state (QEvent::MouseButtonPress and QEvent::MouseButtonRelease events).
It should be noted this may not reflect the actual buttons held on the input device at the time of calling but rather the mouse buttons as last reported in one of the above events. If no mouse buttons are being held Qt::NoButton is returned.
See also
keyboardModifiers()
Definition at line 3431 of file qapplication.cpp.
Referenced by QDockWidget::event(), QToolBar::event(), flipPoint(), QApplicationPrivate::globalEventProcessor(), handle_xdnd_position(), QX11Data::motifdndHandle(), QContextMenuEvent::QContextMenuEvent(), qt_mac_mouse_inside_answer_rect(), QTabBarPrivate::refresh(), QCursor::setPos(), and QX11Data::xdndHandleDrop().
 {
     return QApplicationPrivate::mouse_buttons;
 }
notify()
bool QApplication::notify (QObject * receiver, QEvent * e) virtual
Reimplemented Function
Reimplemented from QCoreApplication.
Definition at line 3926 of file qapplication.cpp.
 {
     Q_D(QApplication);
     // no events are delivered after ~QCoreApplication() has started
     if (QApplicationPrivate::is_app_closing)
         return true;
     if (receiver == 0) {                        // serious error
         qWarning("QApplication::notify: Unexpected null receiver");
         return true;
     }
 #ifndef QT_NO_DEBUG
     d->checkReceiverThread(receiver);
 #endif
     // capture the current mouse/keyboard state
     if(e->spontaneous()) {
         if (e->type() == QEvent::KeyPress
             || e->type() == QEvent::KeyRelease) {
             QKeyEvent *ke = static_cast<QKeyEvent*>(e);
             QApplicationPrivate::modifier_buttons = ke->modifiers();
         } else if(e->type() == QEvent::MouseButtonPress
             || e->type() == QEvent::MouseButtonRelease) {
                 QMouseEvent *me = static_cast<QMouseEvent*>(e);
                 QApplicationPrivate::modifier_buttons = me->modifiers();
                 if(me->type() == QEvent::MouseButtonPress)
                     QApplicationPrivate::mouse_buttons |= me->button();
                 else
                     QApplicationPrivate::mouse_buttons &= ~me->button();
             }
 #if !defined(QT_NO_WHEELEVENT) || !defined(QT_NO_TABLETEVENT)
             else if (false
 #  ifndef QT_NO_WHEELEVENT
                      || e->type() == QEvent::Wheel
 #  endif
 #  ifndef QT_NO_TABLETEVENT
                      || e->type() == QEvent::TabletMove
                      || e->type() == QEvent::TabletPress
                      || e->type() == QEvent::TabletRelease
 #  endif
                      ) {
             QInputEvent *ie = static_cast<QInputEvent*>(e);
             QApplicationPrivate::modifier_buttons = ie->modifiers();
         }
 #endif // !QT_NO_WHEELEVENT || !QT_NO_TABLETEVENT
     }
 #ifndef QT_NO_GESTURES
     // walk through parents and check for gestures
     if (d->gestureManager) {
         switch (e->type()) {
         case QEvent::Paint:
         case QEvent::MetaCall:
         case QEvent::DeferredDelete:
         case QEvent::DragEnter: case QEvent::DragMove: case QEvent::DragLeave:
         case QEvent::Drop: case QEvent::DragResponse:
         case QEvent::ChildAdded: case QEvent::ChildPolished:
 #ifdef QT3_SUPPORT
         case QEvent::ChildInsertedRequest:
         case QEvent::ChildInserted:
         case QEvent::LayoutHint:
 #endif
         case QEvent::ChildRemoved:
         case QEvent::UpdateRequest:
         case QEvent::UpdateLater:
         case QEvent::AccessibilityPrepare:
         case QEvent::LocaleChange:
         case QEvent::Style:
         case QEvent::IconDrag:
         case QEvent::StyleChange:
         case QEvent::AccessibilityHelp:
         case QEvent::AccessibilityDescription:
         case QEvent::GraphicsSceneDragEnter:
         case QEvent::GraphicsSceneDragMove:
         case QEvent::GraphicsSceneDragLeave:
         case QEvent::GraphicsSceneDrop:
         case QEvent::DynamicPropertyChange:
         case QEvent::NetworkReplyUpdated:
             break;
         default:
             if (d->gestureManager->thread() == QThread::currentThread()) {
                 if (receiver->isWidgetType()) {
                     if (d->gestureManager->filterEvent(static_cast<QWidget *>(receiver), e))
                         return true;
                 } else {
                     // a special case for events that go to QGesture objects.
                     // We pass the object to the gesture manager and it'll figure
                     // out if it's QGesture or not.
                     if (d->gestureManager->filterEvent(receiver, e))
                         return true;
                 }
             }
             break;
         }
     }
 #endif // QT_NO_GESTURES
     // User input and window activation makes tooltips sleep
     switch (e->type()) {
     case QEvent::Wheel:
     case QEvent::ActivationChange:
     case QEvent::KeyPress:
     case QEvent::KeyRelease:
     case QEvent::FocusOut:
     case QEvent::FocusIn:
     case QEvent::MouseButtonPress:
     case QEvent::MouseButtonRelease:
     case QEvent::MouseButtonDblClick:
         d->toolTipFallAsleep.stop();
         // fall-through
     case QEvent::Leave:
         d->toolTipWakeUp.stop();
     default:
         break;
     }
     bool res = false;
     if (!receiver->isWidgetType()) {
         res = d->notify_helper(receiver, e);
     } else switch (e->type()) {
 #if defined QT3_SUPPORT && !defined(QT_NO_SHORTCUT)
     case QEvent::Accel:
         {
             if (d->use_compat()) {
                 QKeyEvent* key = static_cast<QKeyEvent*>(e);
                 res = d->notify_helper(receiver, e);
                 if (!res && !key->isAccepted())
                     res = d->qt_dispatchAccelEvent(static_cast<QWidget *>(receiver), key);
                 // next lines are for compatibility with Qt <= 3.0.x: old
                 // QAccel was listening on toplevel widgets
                 if (!res && !key->isAccepted() && !static_cast<QWidget *>(receiver)->isWindow())
                     res = d->notify_helper(static_cast<QWidget *>(receiver)->window(), e);
             }
             break;
         }
 #endif //QT3_SUPPORT && !QT_NO_SHORTCUT
     case QEvent::ShortcutOverride:
     case QEvent::KeyPress:
     case QEvent::KeyRelease:
         {
             bool isWidget = receiver->isWidgetType();
             bool isGraphicsWidget = false;
 #ifndef QT_NO_GRAPHICSVIEW
             isGraphicsWidget = !isWidget && qobject_cast<QGraphicsWidget *>(receiver);
 #endif
             if (!isWidget && !isGraphicsWidget) {
                 res = d->notify_helper(receiver, e);
                 break;
             }
             QKeyEvent* key = static_cast<QKeyEvent*>(e);
 #if defined QT3_SUPPORT && !defined(QT_NO_SHORTCUT)
             if (d->use_compat() && d->qt_tryComposeUnicode(static_cast<QWidget*>(receiver), key))
                 break;
 #endif
             if (key->type()==QEvent::KeyPress) {
 #ifndef QT_NO_SHORTCUT
                 // Try looking for a Shortcut before sending key events
                 if ((res = qApp->d_func()->shortcutMap.tryShortcutEvent(receiver, key)))
                     return res;
 #endif
                 qt_in_tab_key_event = (key->key() == Qt::Key_Backtab
                                        || key->key() == Qt::Key_Tab
                                        || key->key() == Qt::Key_Left
                                        || key->key() == Qt::Key_Up
                                        || key->key() == Qt::Key_Right
                                        || key->key() == Qt::Key_Down);
             }
             bool def = key->isAccepted();
             QPointer<QObject> pr = receiver;
             while (receiver) {
                 if (def)
                     key->accept();
                 else
                     key->ignore();
                 res = d->notify_helper(receiver, e);
                 QWidget *w = isWidget ? static_cast<QWidget *>(receiver) : 0;
 #ifndef QT_NO_GRAPHICSVIEW
                 QGraphicsWidget *gw = isGraphicsWidget ? static_cast<QGraphicsWidget *>(receiver) : 0;
 #endif
                 if ((res && key->isAccepted())
                     /*
                        QLineEdit will emit a signal on Key_Return, but
                        ignore the event, and sometimes the connected
                        slot deletes the QLineEdit (common in itemview
                        delegates), so we have to check if the widget
                        was destroyed even if the event was ignored (to
                        prevent a crash)
                        note that we don't have to reset pw while
                        propagating (because the original receiver will
                        be destroyed if one of its ancestors is)
                     */
                     || !pr
                     || (isWidget && (w->isWindow() || !w->parentWidget()))
 #ifndef QT_NO_GRAPHICSVIEW
                     || (isGraphicsWidget && (gw->isWindow() || !gw->parentWidget()))
 #endif
                     ) {
                     break;
                 }
 #ifndef QT_NO_GRAPHICSVIEW
                 receiver = w ? (QObject *)w->parentWidget() : (QObject *)gw->parentWidget();
 #else
                 receiver = w->parentWidget();
 #endif
             }
             qt_in_tab_key_event = false;
         }
         break;
     case QEvent::MouseButtonPress:
     case QEvent::MouseButtonRelease:
     case QEvent::MouseButtonDblClick:
     case QEvent::MouseMove:
         {
             QWidget* w = static_cast<QWidget *>(receiver);
             QMouseEvent* mouse = static_cast<QMouseEvent*>(e);
             QPoint relpos = mouse->pos();
             if (e->spontaneous()) {
 #ifndef QT_NO_IM
                 QInputContext *ic = w->inputContext();
                 if (ic
                         && w->testAttribute(Qt::WA_InputMethodEnabled)
                         && ic->filterEvent(mouse))
                     return true;
 #endif
                 if (e->type() == QEvent::MouseButtonPress) {
                     QApplicationPrivate::giveFocusAccordingToFocusPolicy(w,
                                                                          Qt::ClickFocus,
                                                                          Qt::MouseFocusReason);
                 }
                 // ### Qt 5 These dynamic tool tips should be an OPT-IN feature. Some platforms
                 // like Mac OS X (probably others too), can optimize their views by not
                 // dispatching mouse move events. We have attributes to control hover,
                 // and mouse tracking, but as long as we are deciding to implement this
                 // feature without choice of opting-in or out, you ALWAYS have to have
                 // tracking enabled. Therefore, the other properties give a false sense of
                 // performance enhancement.
                 if (e->type() == QEvent::MouseMove && mouse->buttons() == 0) {
                     d->toolTipWidget = w;
                     d->toolTipPos = relpos;
                     d->toolTipGlobalPos = mouse->globalPos();
                     d->toolTipWakeUp.start(d->toolTipFallAsleep.isActive()?20:700, this);
                 }
             }
             bool eventAccepted = mouse->isAccepted();
             QPointer<QWidget> pw = w;
             while (w) {
                 QMouseEvent me(mouse->type(), relpos, mouse->globalPos(), mouse->button(), mouse->buttons(),
                                mouse->modifiers());
                 me.spont = mouse->spontaneous();
                 // throw away any mouse-tracking-only mouse events
                 if (!w->hasMouseTracking()
                     && mouse->type() == QEvent::MouseMove && mouse->buttons() == 0) {
                     // but still send them through all application event filters (normally done by notify_helper)
                     for (int i = 0; i < d->eventFilters.size(); ++i) {
                         register QObject *obj = d->eventFilters.at(i);
                         if (!obj)
                             continue;
                         if (obj->d_func()->threadData != w->d_func()->threadData) {
                             qWarning("QApplication: Object event filter cannot be in a different thread.");
                             continue;
                         }
                         if (obj->eventFilter(w, w == receiver ? mouse : &me))
                             break;
                     }
                     res = true;
                 } else {
                     w->setAttribute(Qt::WA_NoMouseReplay, false);
                     res = d->notify_helper(w, w == receiver ? mouse : &me);
                     e->spont = false;
                 }
                 eventAccepted = (w == receiver ? mouse : &me)->isAccepted();
                 if (res && eventAccepted)
                     break;
                 if (w->isWindow() || w->testAttribute(Qt::WA_NoMousePropagation))
                     break;
                 relpos += w->pos();
                 w = w->parentWidget();
             }
             mouse->setAccepted(eventAccepted);
             if (e->type() == QEvent::MouseMove) {
                 if (!pw)
                     break;
                 w = static_cast<QWidget *>(receiver);
                 relpos = mouse->pos();
                 QPoint diff = relpos - w->mapFromGlobal(d->hoverGlobalPos);
                 while (w) {
                     if (w->testAttribute(Qt::WA_Hover) &&
                         (!QApplication::activePopupWidget() || QApplication::activePopupWidget() == w->window())) {
                         QHoverEvent he(QEvent::HoverMove, relpos, relpos - diff);
                         d->notify_helper(w, &he);
                     }
                     if (w->isWindow() || w->testAttribute(Qt::WA_NoMousePropagation))
                         break;
                     relpos += w->pos();
                     w = w->parentWidget();
                 }
             }
             d->hoverGlobalPos = mouse->globalPos();
         }
         break;
 #ifndef QT_NO_WHEELEVENT
     case QEvent::Wheel:
         {
             QWidget* w = static_cast<QWidget *>(receiver);
             QWheelEvent* wheel = static_cast<QWheelEvent*>(e);
             QPoint relpos = wheel->pos();
             bool eventAccepted = wheel->isAccepted();
             if (e->spontaneous()) {
                 QApplicationPrivate::giveFocusAccordingToFocusPolicy(w,
                                                                      Qt::WheelFocus,
                                                                      Qt::MouseFocusReason);
             }
             while (w) {
                 QWheelEvent we(relpos, wheel->globalPos(), wheel->delta(), wheel->buttons(),
                                wheel->modifiers(), wheel->orientation());
                 we.spont = wheel->spontaneous();
                 res = d->notify_helper(w, w == receiver ? wheel : &we);
                 eventAccepted = ((w == receiver) ? wheel : &we)->isAccepted();
                 e->spont = false;
                 if ((res && eventAccepted)
                     || w->isWindow() || w->testAttribute(Qt::WA_NoMousePropagation))
                     break;
                 relpos += w->pos();
                 w = w->parentWidget();
             }
             wheel->setAccepted(eventAccepted);
         }
         break;
 #endif
 #ifndef QT_NO_CONTEXTMENU
     case QEvent::ContextMenu:
         {
             QWidget* w = static_cast<QWidget *>(receiver);
             QContextMenuEvent *context = static_cast<QContextMenuEvent*>(e);
             QPoint relpos = context->pos();
             bool eventAccepted = context->isAccepted();
             while (w) {
                 QContextMenuEvent ce(context->reason(), relpos, context->globalPos(), context->modifiers());
                 ce.spont = e->spontaneous();
                 res = d->notify_helper(w, w == receiver ? context : &ce);
                 eventAccepted = ((w == receiver) ? context : &ce)->isAccepted();
                 e->spont = false;
                 if ((res && eventAccepted)
                     || w->isWindow() || w->testAttribute(Qt::WA_NoMousePropagation))
                     break;
                 relpos += w->pos();
                 w = w->parentWidget();
             }
             context->setAccepted(eventAccepted);
         }
         break;
 #endif // QT_NO_CONTEXTMENU
 #ifndef QT_NO_TABLETEVENT
     case QEvent::TabletMove:
     case QEvent::TabletPress:
     case QEvent::TabletRelease:
         {
             QWidget *w = static_cast<QWidget *>(receiver);
             QTabletEvent *tablet = static_cast<QTabletEvent*>(e);
             QPoint relpos = tablet->pos();
             bool eventAccepted = tablet->isAccepted();
             while (w) {
                 QTabletEvent te(tablet->type(), relpos, tablet->globalPos(),
                                 tablet->hiResGlobalPos(), tablet->device(), tablet->pointerType(),
                                 tablet->pressure(), tablet->xTilt(), tablet->yTilt(),
                                 tablet->tangentialPressure(), tablet->rotation(), tablet->z(),
                                 tablet->modifiers(), tablet->uniqueId());
                 te.spont = e->spontaneous();
                 res = d->notify_helper(w, w == receiver ? tablet : &te);
                 eventAccepted = ((w == receiver) ? tablet : &te)->isAccepted();
                 e->spont = false;
                 if ((res && eventAccepted)
                      || w->isWindow()
                      || w->testAttribute(Qt::WA_NoMousePropagation))
                     break;
                 relpos += w->pos();
                 w = w->parentWidget();
             }
             tablet->setAccepted(eventAccepted);
             qt_tabletChokeMouse = tablet->isAccepted();
         }
         break;
 #endif // QT_NO_TABLETEVENT
 #if !defined(QT_NO_TOOLTIP) || !defined(QT_NO_WHATSTHIS)
     case QEvent::ToolTip:
     case QEvent::WhatsThis:
     case QEvent::QueryWhatsThis:
         {
             QWidget* w = static_cast<QWidget *>(receiver);
             QHelpEvent *help = static_cast<QHelpEvent*>(e);
             QPoint relpos = help->pos();
             bool eventAccepted = help->isAccepted();
             while (w) {
                 QHelpEvent he(help->type(), relpos, help->globalPos());
                 he.spont = e->spontaneous();
                 res = d->notify_helper(w, w == receiver ? help : &he);
                 e->spont = false;
                 eventAccepted = (w == receiver ? help : &he)->isAccepted();
                 if ((res && eventAccepted) || w->isWindow())
                     break;
                 relpos += w->pos();
                 w = w->parentWidget();
             }
             help->setAccepted(eventAccepted);
         }
         break;
 #endif
 #if !defined(QT_NO_STATUSTIP) || !defined(QT_NO_WHATSTHIS)
     case QEvent::StatusTip:
     case QEvent::WhatsThisClicked:
         {
             QWidget *w = static_cast<QWidget *>(receiver);
             while (w) {
                 res = d->notify_helper(w, e);
                 if ((res && e->isAccepted()) || w->isWindow())
                     break;
                 w = w->parentWidget();
             }
         }
         break;
 #endif
 #ifndef QT_NO_DRAGANDDROP
     case QEvent::DragEnter: {
             QWidget* w = static_cast<QWidget *>(receiver);
             QDragEnterEvent *dragEvent = static_cast<QDragEnterEvent *>(e);
 #ifdef Q_WS_MAC
             // HIView has a slight difference in how it delivers events to children and parents
             // It will not give a leave to a child's parent when it enters a child.
             QWidget *currentTarget = QDragManager::self()->currentTarget();
             if (currentTarget) {
                 // Assume currentTarget did not get a leave
                 QDragLeaveEvent event;
                 QApplication::sendEvent(currentTarget, &event);
             }
 #endif
 #ifndef QT_NO_GRAPHICSVIEW
             // QGraphicsProxyWidget handles its own propagation,
             // and we must not change QDragManagers currentTarget.
             QWExtra *extra = w->window()->d_func()->extra;
             if (extra && extra->proxyWidget) {
                 res = d->notify_helper(w, dragEvent);
                 break;
             }
 #endif
             while (w) {
                 if (w->isEnabled() && w->acceptDrops()) {
                     res = d->notify_helper(w, dragEvent);
                     if (res && dragEvent->isAccepted()) {
                         QDragManager::self()->setCurrentTarget(w);
                         break;
                     }
                 }
                 if (w->isWindow())
                     break;
                 dragEvent->p = w->mapToParent(dragEvent->p);
                 w = w->parentWidget();
             }
         }
         break;
     case QEvent::DragMove:
     case QEvent::Drop:
     case QEvent::DragLeave: {
             QWidget* w = static_cast<QWidget *>(receiver);
 #ifndef QT_NO_GRAPHICSVIEW
             // QGraphicsProxyWidget handles its own propagation,
             // and we must not change QDragManagers currentTarget.
             QWExtra *extra = w->window()->d_func()->extra;
             bool isProxyWidget = extra && extra->proxyWidget;
             if (!isProxyWidget)
 #endif
                 w = QDragManager::self()->currentTarget();
             if (!w) {
 #ifdef Q_WS_MAC
                 // HIView has a slight difference in how it delivers events to children and parents
                 // It will not give an enter to a child's parent when it leaves the child.
                 if (e->type() == QEvent::DragLeave)
                     break;
                 // Assume that w did not get an enter.
                 QDropEvent *dropEvent = static_cast<QDropEvent *>(e);
                 QDragEnterEvent dragEnterEvent(dropEvent->pos(), dropEvent->possibleActions(),
                                                dropEvent->mimeData(), dropEvent->mouseButtons(),
                                                dropEvent->keyboardModifiers());
                 QApplication::sendEvent(receiver, &dragEnterEvent);
                 w = QDragManager::self()->currentTarget();
                 if (!w)
 #endif
                     break;
             }
             if (e->type() == QEvent::DragMove || e->type() == QEvent::Drop) {
                 QDropEvent *dragEvent = static_cast<QDropEvent *>(e);
                 QWidget *origReciver = static_cast<QWidget *>(receiver);
                 while (origReciver && w != origReciver) {
                     dragEvent->p = origReciver->mapToParent(dragEvent->p);
                     origReciver = origReciver->parentWidget();
                 }
             }
             res = d->notify_helper(w, e);
             if (e->type() != QEvent::DragMove
 #ifndef QT_NO_GRAPHICSVIEW
                 && !isProxyWidget
 #endif
                 )
                 QDragManager::self()->setCurrentTarget(0, e->type() == QEvent::Drop);
         }
         break;
 #endif
     case QEvent::TouchBegin:
     // Note: TouchUpdate and TouchEnd events are never propagated
     {
         QWidget *widget = static_cast<QWidget *>(receiver);
         QTouchEvent *touchEvent = static_cast<QTouchEvent *>(e);
         bool eventAccepted = touchEvent->isAccepted();
         if (widget->testAttribute(Qt::WA_AcceptTouchEvents) && e->spontaneous()) {
             // give the widget focus if the focus policy allows it
             QApplicationPrivate::giveFocusAccordingToFocusPolicy(widget,
                                                                  Qt::ClickFocus,
                                                                  Qt::MouseFocusReason);
         }
         while (widget) {
             // first, try to deliver the touch event
             bool acceptTouchEvents = widget->testAttribute(Qt::WA_AcceptTouchEvents);
             touchEvent->setWidget(widget);
             touchEvent->setAccepted(acceptTouchEvents);
             QWeakPointer<QWidget> p = widget;
             res = acceptTouchEvents && d->notify_helper(widget, touchEvent);
             eventAccepted = touchEvent->isAccepted();
             if (p.isNull()) {
                 // widget was deleted
                 widget = 0;
             } else {
                 widget->setAttribute(Qt::WA_WState_AcceptedTouchBeginEvent, res && eventAccepted);
             }
             touchEvent->spont = false;
             if (res && eventAccepted) {
                 // the first widget to accept the TouchBegin gets an implicit grab.
                 for (int i = 0; i < touchEvent->touchPoints().count(); ++i) {
                     const QTouchEvent::TouchPoint &touchPoint = touchEvent->touchPoints().at(i);
                     d->widgetForTouchPointId[touchPoint.id()] = widget;
                 }
                 break;
             } else if (p.isNull() || widget->isWindow() || widget->testAttribute(Qt::WA_NoMousePropagation)) {
                 break;
             }
             QPoint offset = widget->pos();
             widget = widget->parentWidget();
             touchEvent->setWidget(widget);
             for (int i = 0; i < touchEvent->_touchPoints.size(); ++i) {
                 QTouchEvent::TouchPoint &pt = touchEvent->_touchPoints[i];
                 QRectF rect = pt.rect();
                 rect.moveCenter(offset);
                 pt.d->rect = rect;
                 pt.d->startPos = pt.startPos() + offset;
                 pt.d->lastPos = pt.lastPos() + offset;
             }
         }
         touchEvent->setAccepted(eventAccepted);
         break;
     }
     case QEvent::RequestSoftwareInputPanel:
     case QEvent::CloseSoftwareInputPanel:
 #ifndef QT_NO_IM
         if (receiver->isWidgetType()) {
             QWidget *w = static_cast<QWidget *>(receiver);
             QInputContext *ic = w->inputContext();
             if (ic && ic->filterEvent(e)) {
                 break;
             }
         }
 #endif
         res = d->notify_helper(receiver, e);
         break;
 #ifndef QT_NO_GESTURES
     case QEvent::NativeGesture:
     {
         // only propagate the first gesture event (after the GID_BEGIN)
         QWidget *w = static_cast<QWidget *>(receiver);
         while (w) {
             e->ignore();
             res = d->notify_helper(w, e);
             if ((res && e->isAccepted()) || w->isWindow())
                 break;
             w = w->parentWidget();
         }
         break;
     }
     case QEvent::Gesture:
     case QEvent::GestureOverride:
     {
         if (receiver->isWidgetType()) {
             QWidget *w = static_cast<QWidget *>(receiver);
             QGestureEvent *gestureEvent = static_cast<QGestureEvent *>(e);
             QList<QGesture *> allGestures = gestureEvent->gestures();
             bool eventAccepted = gestureEvent->isAccepted();
             bool wasAccepted = eventAccepted;
             while (w) {
                 // send only gestures the widget expects
                 QList<QGesture *> gestures;
                 QWidgetPrivate *wd = w->d_func();
                 for (int i = 0; i < allGestures.size();) {
                     QGesture *g = allGestures.at(i);
                     Qt::GestureType type = g->gestureType();
                     QMap<Qt::GestureType, Qt::GestureFlags>::iterator contextit =
                             wd->gestureContext.find(type);
                     bool deliver = contextit != wd->gestureContext.end() &&
                         (g->state() == Qt::GestureStarted || w == receiver ||
                          (contextit.value() & Qt::ReceivePartialGestures));
                     if (deliver) {
                         allGestures.removeAt(i);
                         gestures.append(g);
                     } else {
                         ++i;
                     }
                 }
                 if (!gestures.isEmpty()) { // we have gestures for this w
                     QGestureEvent ge(gestures);
                     ge.t = gestureEvent->t;
                     ge.spont = gestureEvent->spont;
                     ge.m_accept = wasAccepted;
                     ge.d_func()->accepted = gestureEvent->d_func()->accepted;
                     res = d->notify_helper(w, &ge);
                     gestureEvent->spont = false;
                     eventAccepted = ge.isAccepted();
                     for (int i = 0; i < gestures.size(); ++i) {
                         QGesture *g = gestures.at(i);
                         // Ignore res [event return value] because handling of multiple gestures
                         // packed into a single QEvent depends on not consuming the event
                         if (eventAccepted || ge.isAccepted(g)) {
                             // if the gesture was accepted, mark the target widget for it
                             gestureEvent->d_func()->targetWidgets[g->gestureType()] = w;
                             gestureEvent->setAccepted(g, true);
                         } else {
                             // if the gesture was explicitly ignored by the application,
                             // put it back so a parent can get it
                             allGestures.append(g);
                         }
                     }
                 }
                 if (allGestures.isEmpty()) // everything delivered
                     break;
                 if (w->isWindow())
                     break;
                 w = w->parentWidget();
             }
             foreach (QGesture *g, allGestures)
                 gestureEvent->setAccepted(g, false);
             gestureEvent->m_accept = false; // to make sure we check individual gestures
         } else {
             res = d->notify_helper(receiver, e);
         }
         break;
     }
 #endif // QT_NO_GESTURES
 #ifdef QT_MAC_USE_COCOA
     case QEvent::Enter:
         if (receiver->isWidgetType()) {
             QWidget *w = static_cast<QWidget *>(receiver);
             if (w->testAttribute(Qt::WA_AcceptTouchEvents))
                 qt_widget_private(w)->registerTouchWindow(true);
         }
         res = d->notify_helper(receiver, e);
     break;
     case QEvent::Leave:
         if (receiver->isWidgetType()) {
             QWidget *w = static_cast<QWidget *>(receiver);
             if (w->testAttribute(Qt::WA_AcceptTouchEvents))
                 qt_widget_private(w)->registerTouchWindow(false);
         }
         res = d->notify_helper(receiver, e);
     break;
 #endif
     default:
         res = d->notify_helper(receiver, e);
         break;
     }
     return res;
 }
overrideCursor()
QCursor * QApplication::overrideCursor () static
Strips out vertical alignment flags and transforms an alignment align of Qt::AlignLeft into Qt::AlignLeft or Qt::AlignRight according to the language used.
Returns the active application override cursor.
This function returns 0 if no application cursor has been defined (i.e. the internal cursor stack is empty).
See also
setOverrideCursor(), restoreOverrideCursor()
Definition at line 3855 of file qapplication.cpp.
Referenced by effectiveState(), qt_mac_updateCursorWithWidgetUnderMouse(), qt_qpa_set_cursor(), qt_try_modal(), qt_win_set_cursor(), qt_x11_enforce_cursor(), QtWndProc(), and QETWidget::translateMouseEvent().
 {
     return qApp->d_func()->cursor_list.isEmpty() ? 0 : &qApp->d_func()->cursor_list.first();
 }
palette() [1/3]
QPalette QApplication::palette () static
Returns the application palette.
See also
setPalette(), QWidget::palette()
Definition at line 1807 of file qapplication.cpp.
Referenced by QMacStyle::drawControl(), QDeclarativeSystemPalette::event(), QWidget::event(), QComboMenuDelegate::getStyleOption(), QGtkStylePrivate::gtkWidgetPalette(), QTextHtmlParserNode::initializeProperties(), QApplicationPrivate::initializeWidgetPaletteHash(), QWidgetPrivate::naturalWidgetPalette(), QDecorationWindows::paint(), QDecorationDefault::paint(), palette(), QSvgIconEngine::pixmap(), QPixmapIconEngine::pixmap(), QWindowsStyle::polish(), QDeclarativeSystemPalette::QDeclarativeSystemPalette(), QRenderRule::QRenderRule(), QApplicationPrivate::qt_mac_apply_settings(), QGraphicsScenePrivate::resolvePalette(), QTextControlPrivate::setContent(), QGraphicsScene::setPalette(), QApplicationPrivate::setPalette_helper(), QInputContext::standardFormat(), and QMotifStyle::standardPixmap().
 {
     if (!QApplicationPrivate::app_pal)
         QApplicationPrivate::app_pal = new QPalette(Qt::black);
     return *QApplicationPrivate::app_pal;
 }
palette() [2/3]
QPalette QApplication::palette (const QWidget * widget) static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.If a widget is passed, the default palette for the widget's class is returned.
This may or may not be the application palette. In most cases there is no special palette for certain types of widgets, but one notable exception is the popup menu under Windows, if the user has defined a special background color for menus in the display settings.
See also
setPalette(), QWidget::palette()
Definition at line 1826 of file qapplication.cpp.
 {
     PaletteHash *hash = app_palettes();
     if (w && hash && hash->size()) {
         QHash<QByteArray, QPalette>::ConstIterator it = hash->constFind(w->metaObject()->className());
         if (it != hash->constEnd())
             return *it;
         for (it = hash->constBegin(); it != hash->constEnd(); ++it) {
             if (w->inherits(it.key()))
                 return it.value();
         }
     }
     return palette();
 }
palette() [3/3]
QPalette QApplication::palette (const char * className) static
Returns the palette for widgets of the given className.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setPalette(), QWidget::palette()
Definition at line 1851 of file qapplication.cpp.
 {
     if (!QApplicationPrivate::app_pal)
         palette();
     PaletteHash *hash = app_palettes();
     if (className && hash && hash->size()) {
         QHash<QByteArray, QPalette>::ConstIterator it = hash->constFind(className);
         if (it != hash->constEnd())
             return *it;
     }
     return *QApplicationPrivate::app_pal;
 }
queryKeyboardModifiers()
Qt::KeyboardModifiers QApplication::queryKeyboardModifiers () static
Queries and returns the state of the modifier keys on the keyboard.
Unlike keyboardModifiers, this method returns the actual keys held on the input device at the time of calling the method.
It does not rely on the keypress events having been received by this process, which makes it possible to check the modifiers while moving a window, for instance. Note that in most cases, you should use keyboardModifiers(), which is faster and more accurate since it contains the state of the modifiers as they were when the currently processed event was received.
See also
keyboardModifiers()
Since
4.8
Definition at line 1436 of file qapplication_mac.mm.
Referenced by parseGeometry(), qt_win_getKeyboardModifiers(), syncX(), and QX11Data::xdndHandleDrop().
 {
     return qt_mac_get_modifiers(GetCurrentEventKeyModifiers());
 }
quitOnLastWindowClosed()
static bool QApplication::quitOnLastWindowClosed () static
Referenced by setQuitOnLastWindowClosed().
qwsEventFilter()
bool QApplication::qwsEventFilter (QWSEvent * event) virtual
This virtual function is only implemented under Qt for Embedded Linux.
If you create an application that inherits QApplication and reimplement this function, you get direct access to all QWS (Q Window System) events that the are received from the QWS master process. The events are passed in the event parameter.
Return true if you want to stop the event from being processed. Return false for normal event dispatching. The default implementation returns false.
Definition at line 3090 of file qapplication_qws.cpp.
 {
     return false;
 }
qwsProcessEvent()
int QApplication::qwsProcessEvent (QWSEvent * event)
Warning
This function is not part of the public interface.
Definition at line 2712 of file qapplication_qws.cpp.
 {
     Q_D(QApplication);
     QScopedLoopLevelCounter loopLevelCounter(d->threadData);
     int oldstate = -1;
     bool isMove = false;
     if (event->type == QWSEvent::Mouse) {
         QWSMouseEvent::SimpleData &mouse = event->asMouse()->simpleData;
         isMove = mouse_x_root != mouse.x_root || mouse_y_root != mouse.y_root;
         oldstate = mouse_state;
         mouse_x_root = mouse.x_root;
         mouse_y_root = mouse.y_root;
         mouse_state = mouse.state;
     }
     long unused;
     if (filterEvent(event, &unused))                  // send through app filter
         return 1;
     if (qwsEventFilter(event))                        // send through app filter
         return 1;
 #ifndef QT_NO_QWS_PROPERTIES
     if (event->type == QWSEvent::PropertyNotify) {
         QWSPropertyNotifyEvent *e = static_cast<QWSPropertyNotifyEvent*>(event);
         if (e->simpleData.property == 424242) {       // Clipboard
 #ifndef QT_NO_CLIPBOARD
             if (qt_clipboard) {
                 QClipboardEvent e(reinterpret_cast<QEventPrivate*>(event));
                 QApplication::sendEvent(qt_clipboard, &e);
             }
 #endif
         }
     }
 #endif //QT_NO_QWS_PROPERTIES
 #ifndef QT_NO_COP
     else if (event->type == QWSEvent::QCopMessage) {
         QWSQCopMessageEvent *e = static_cast<QWSQCopMessageEvent*>(event);
         QCopChannel::sendLocally(QLatin1String(e->channel), QLatin1String(e->message), e->data);
         return 0;
     }
 #endif
 #if !defined(QT_NO_QWS_QPF2)
     else if (event->type == QWSEvent::Font) {
         QWSFontEvent *e = static_cast<QWSFontEvent *>(event);
         if (e->simpleData.type == QWSFontEvent::FontRemoved) {
             QFontCache::instance()->removeEngineForFont(e->fontName);
         }
     }
 #endif
     QPointer<QETWidget> widget = static_cast<QETWidget*>(QWidget::find(WId(event->window())));
 #ifdef Q_BACKINGSTORE_SUBSURFACES
     if (!widget) { // XXX: hw: hack for accessing subsurfaces
         extern QWSWindowSurface* qt_findWindowSurface(int);
         QWSWindowSurface *s = qt_findWindowSurface(event->window());
         if (s)
             widget = static_cast<QETWidget*>(s->window());
     }
 #endif
 #ifndef QT_NO_DIRECTPAINTER
     if (!widget && d->directPainters) {
         QDirectPainter *dp = d->directPainters->value(WId(event->window()));
         if (dp == 0) {
         } else if (event->type == QWSEvent::Region) {
             QWSRegionEvent *e = static_cast<QWSRegionEvent*>(event);
             QRegion reg;
             reg.setRects(e->rectangles, e->simpleData.nrectangles);
             qt_directpainter_region(dp, reg, e->simpleData.type);
             return 1;
 #ifndef QT_NO_QWSEMBEDWIDGET
         } else if (event->type == QWSEvent::Embed) {
             QWSEmbedEvent *e = static_cast<QWSEmbedEvent*>(event);
             qt_directpainter_embedevent(dp, e);
             return 1;
  #endif // QT_NO_QWSEMBEDWIDGET
         }
     }
 #endif // QT_NO_DIRECTPAINTER
 #ifndef QT_NO_QWS_MANAGER
     if (d->last_manager && event->type == QWSEvent::Mouse) {
         QPoint pos(event->asMouse()->simpleData.x_root, event->asMouse()->simpleData.y_root);
         if (!d->last_manager->cachedRegion().contains(pos)) {
             // MouseEvent not yet delivered, so QCursor::pos() is not yet updated, sending 2 x pos
             QMouseEvent outside(QEvent::MouseMove, pos, pos, Qt::NoButton, 0, 0);
             QApplication::sendSpontaneousEvent(d->last_manager, &outside);
             d->last_manager = 0;
             qt_last_cursor = 0xffffffff; //decoration is like another window; must redo cursor
         }
     }
 #endif // QT_NO_QWS_MANAGER
     QETWidget *keywidget=0;
     bool grabbed=false;
     if (event->type==QWSEvent::Key || event->type == QWSEvent::IMEvent || event->type == QWSEvent::IMQuery) {
         keywidget = static_cast<QETWidget*>(QWidget::keyboardGrabber());
         if (keywidget) {
             grabbed = true;
         } else {
             if (QWidget *popup = QApplication::activePopupWidget()) {
                 if (popup->focusWidget())
                     keywidget = static_cast<QETWidget*>(popup->focusWidget());
                 else
                     keywidget = static_cast<QETWidget*>(popup);
             } else if (QApplicationPrivate::focus_widget && QApplicationPrivate::focus_widget->isVisible())
                 keywidget = static_cast<QETWidget*>(QApplicationPrivate::focus_widget);
             else if (widget)
                 keywidget = static_cast<QETWidget*>(widget->window());
         }
     } else if (event->type==QWSEvent::MaxWindowRect) {
         QRect r = static_cast<QWSMaxWindowRectEvent*>(event)->simpleData.rect;
         setMaxWindowRect(r);
         return 0;
 #ifndef QT_NO_QWS_DYNAMICSCREENTRANSFORMATION
     } else if (event->type == QWSEvent::ScreenTransformation) {
         QWSScreenTransformationEvent *pe = static_cast<QWSScreenTransformationEvent*>(event);
         setScreenTransformation(pe->simpleData.screen,
                                 pe->simpleData.transformation);
         return 0;
 #endif
     } else if (widget && event->type==QWSEvent::Mouse) {
         // The mouse event is to one of my top-level widgets
         // which one?
         const int btnMask = Qt::LeftButton | Qt::RightButton | Qt::MidButton;
         QPoint p(event->asMouse()->simpleData.x_root,
                  event->asMouse()->simpleData.y_root);
         int mouseButtonState = event->asMouse()->simpleData.state & btnMask;
         static int btnstate = 0;
         QETWidget *w = static_cast<QETWidget*>(QWidget::mouseGrabber());
         if (w && !mouseButtonState && qt_pressGrab == w)
             qt_pressGrab = 0;
 #ifndef QT_NO_QWS_MANAGER
         if (!w)
             w = static_cast<QETWidget*>(QWSManager::grabbedMouse());
 #endif
         if (w) {
             // Our mouse is grabbed - send it.
             widget = w;
             btnstate = mouseButtonState;
         } else {
             static QWidget *gw = 0;
             // Three jobs to do here:
             // 1. find the child widget this event belongs to.
             // 2. make sure the cursor is correct.
             // 3. handle implicit mouse grab due to button press.
             w = widget; // w is the widget the cursor is in.
             //### ??? alloc_region
             //#### why should we get events outside alloc_region ????
             if (1 /*widget->data->alloc_region.contains(dp) */) {
                 // Find the child widget that the cursor is in.
                 w = static_cast<QETWidget*>(widget->childAt(widget->mapFromParent(p)));
                 if (!w)
                     w = widget;
 #ifndef QT_NO_CURSOR
                 // Update Cursor.
                 if (!gw || gw != w || qt_last_cursor == 0xffffffff) {
                     QCursor *curs = 0;
                     if (!qApp->d_func()->cursor_list.isEmpty())
                         curs = &qApp->d_func()->cursor_list.first();
                     else if (w->d_func()->extraData())
                         curs = w->d_func()->extraData()->curs;
                     QWidget *pw = w;
                     // If this widget has no cursor set, try parent.
                     while (!curs) {
                         pw = pw->parentWidget();
                         if (!pw)
                             break;
                         if (pw->d_func()->extraData())
                             curs = pw->d_func()->extraData()->curs;
                     }
                     if (!qws_overrideCursor) {
                         if (curs)
                             QPaintDevice::qwsDisplay()->selectCursor(widget, curs->handle());
                         else
                             QPaintDevice::qwsDisplay()->selectCursor(widget, Qt::ArrowCursor);
                     }
                 }
 #endif
                 gw = w;
             } else {
                 // This event is not for any of our widgets
                 gw = 0;
             }
             if (mouseButtonState && !btnstate) {
                 // The server has grabbed the mouse for us.
                 // Remember which of my widgets has it.
                 qt_pressGrab = w;
                 if (!widget->isActiveWindow() &&
                     (!app_do_modal || QApplication::activeModalWidget() == widget) &&
                     !((widget->windowFlags() & Qt::FramelessWindowHint) || (widget->windowType() == Qt::Tool))) {
                     widget->activateWindow();
                     if (widget->raiseOnClick())
                         widget->raise();
                 }
             }
             btnstate = mouseButtonState;
             widget = w;
         }
     }
     if (!widget) {                                // don't know this window
         if (!QWidget::mouseGrabber()
 #ifndef QT_NO_QWS_MANAGER
             && !QWSManager::grabbedMouse()
 #endif
             ) {
             qt_last_cursor = 0xffffffff; // cursor can be changed by another application
         }
         QWidget* popup = QApplication::activePopupWidget();
         if (popup) {
             /*
               That is more than suboptimal. The real solution should
               do some keyevent and buttonevent translation, so that
               the popup still continues to work as the user expects.
               Unfortunately this translation is currently only
               possible with a known widget. I'll change that soon
               (Matthias).
             */
             // Danger - make sure we don't lock the server
             switch (event->type) {
             case QWSEvent::Mouse:
             case QWSEvent::Key:
                 do {
                     popup->close();
                 } while ((popup = qApp->activePopupWidget()));
                 return 1;
             }
         }
         if (event->type == QWSEvent::Mouse && *mouseInWidget) {
             QApplicationPrivate::dispatchEnterLeave(0, *mouseInWidget);
             (*mouseInWidget) = 0;
         }
         return -1;
     }
     if (app_do_modal)                                // modal event handling
         if (!qt_try_modal(widget, event)) {
             return 1;
         }
     if (widget->qwsEvent(event))                // send through widget filter
         return 1;
     switch (event->type) {
     case QWSEvent::Mouse: {                        // mouse event
         QWSMouseEvent *me = event->asMouse();
         QWSMouseEvent::SimpleData &mouse = me->simpleData;
         //  Translate a QWS event into separate move
         // and press/release events
         // Beware of reentrancy: we can enter a modal state
         // inside translateMouseEvent
         if (isMove) {
             QWSMouseEvent move = *me;
             move.simpleData.state = oldstate;
             widget->translateMouseEvent(&move, oldstate);
         }
         if ((mouse.state&Qt::MouseButtonMask) != (oldstate&Qt::MouseButtonMask)) {
             widget->translateMouseEvent(me, oldstate);
         }
         if (mouse.delta != 0)
             widget->translateWheelEvent(me);
         if (qt_button_down && (mouse_state & Qt::MouseButtonMask) == 0)
             qt_button_down = 0;
         break;
     }
     case QWSEvent::Key:                                // keyboard event
         if (keywidget) // should always exist
             keywidget->translateKeyEvent(static_cast<QWSKeyEvent*>(event), grabbed);
         break;
 #ifndef QT_NO_QWS_INPUTMETHODS
     case QWSEvent::IMEvent:
         if (keywidget) // should always exist
             QWSInputContext::translateIMEvent(keywidget, static_cast<QWSIMEvent*>(event));
         break;
     case QWSEvent::IMQuery:
         if (keywidget) // should always exist
             QWSInputContext::translateIMQueryEvent(keywidget, static_cast<QWSIMQueryEvent*>(event));
         break;
     case QWSEvent::IMInit:
         QWSInputContext::translateIMInitEvent(static_cast<QWSIMInitEvent*>(event));
         break;
 #endif
     case QWSEvent::Region:
         widget->translateRegionEvent(static_cast<QWSRegionEvent*>(event));
         break;
     case QWSEvent::Focus:
         if ((static_cast<QWSFocusEvent*>(event))->simpleData.get_focus) {
             if (widget == static_cast<QWidget *>(desktop()))
                 return true; // not interesting
             if (activeWindow() != widget) {
                 setActiveWindow(widget);
                 if (QApplicationPrivate::active_window)
                     static_cast<QETWidget *>(QApplicationPrivate::active_window)->repaintDecoration(desktop()->rect(), false);
                 if (widget && !d->inPopupMode()) {
                     QWidget *w = widget->focusWidget();
                     while (w && w->focusProxy())
                         w = w->focusProxy();
                     if (w && (w->focusPolicy() != Qt::NoFocus))
                         w->setFocus();
                     else
                         widget->QWidget::focusNextPrevChild(true);
                     if (!QApplicationPrivate::focus_widget) {
                         if (widget->focusWidget())
                             widget->focusWidget()->setFocus();
                         else
                             widget->window()->setFocus();
                     }
                 }
             }
         } else {        // lost focus
             if (widget == static_cast<QWidget *>(desktop()))
                 return true; // not interesting
             if (QApplicationPrivate::focus_widget) {
                 QETWidget *old = static_cast<QETWidget *>(QApplicationPrivate::active_window);
                 setActiveWindow(0);
                 qt_last_cursor = 0xffffffff;
                 //QApplicationPrivate::active_window = 0;
                 if (old)
                     old->repaintDecoration(desktop()->rect(), false);
                 /* activateWindow() sends focus events
                    QApplication::setFocusWidget(0);
                 */
             }
         }
         break;
     case QWSEvent::WindowOperation:
         if (static_cast<QWidget *>(widget) == desktop())
             return true;
         switch ((static_cast<QWSWindowOperationEvent *>(event))->simpleData.op) {
         case QWSWindowOperationEvent::Show:
             widget->show();
             break;
         case QWSWindowOperationEvent::Hide:
             widget->hide();
             break;
         case QWSWindowOperationEvent::ShowMaximized:
             widget->showMaximized();
             break;
         case QWSWindowOperationEvent::ShowMinimized:
             widget->showMinimized();
             break;
         case QWSWindowOperationEvent::ShowNormal:
             widget->showNormal();
             break;
         case QWSWindowOperationEvent::Close:
             widget->d_func()->close_helper(QWidgetPrivate::CloseWithSpontaneousEvent);
             break;
         }
         break;
 #ifndef QT_NO_QWSEMBEDWIDGET
     case QWSEvent::Embed:
         widget->translateEmbedEvent(static_cast<QWSEmbedEvent*>(event));
         break;
 #endif
     default:
         break;
     }
     return 0;
 }
qwsSetCustomColors()
void QApplication::qwsSetCustomColors (QRgb * colorTable, int start, int numColors)
Set Qt for Embedded Linux custom color table.
Qt for Embedded Linux on 8-bpp displays allocates a standard 216 color cube. The remaining 40 colors may be used by setting a custom color table in the QWS master process before any clients connect.
colorTable is an array of up to 40 custom colors. start is the starting index (0-39) and numColors is the number of colors to be set (1-40).
This method is non-portable. It is available only in Qt for Embedded Linux.
Note
The custom colors will not be used by the default screen driver. To make use of the new colors, implement a custom screen driver, or use QDirectPainter.
Definition at line 3095 of file qapplication_qws.cpp.
 {
     if (start < 0 || start > 39) {
         qWarning("QApplication::qwsSetCustomColors: start < 0 || start > 39");
         return;
     }
     if (start + numColors > 40) {
         numColors = 40 - start;
         qWarning("QApplication::qwsSetCustomColors: Too many colors");
     }
     start += 216;
     for (int i = 0; i < numColors; i++) {
         qt_screen->set(start + i, qRed(colorTable[i]), qGreen(colorTable[i]),
                         qBlue(colorTable[i]));
     }
 }
restoreOverrideCursor()
void QApplication::restoreOverrideCursor () static
Undoes the last setOverrideCursor().
If setOverrideCursor() has been called twice, calling restoreOverrideCursor() will activate the first cursor set. Calling this function a second time restores the original widgets' cursors.
See also
setOverrideCursor(), overrideCursor()
Definition at line 1419 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::applyX11SpecificCommandLineArguments(), QOleDropTarget::Drop(), findRealWindow(), parseGeometry(), QGuiEventDispatcherWin32::processEvents(), QAxSelect::QAxSelect(), QTextBrowserPrivate::setSource(), QDragManager::~QDragManager(), and QWhatsThisPrivate::~QWhatsThisPrivate().
 {
     if (qApp->d_func()->cursor_list.isEmpty())
         return;
     qApp->d_func()->cursor_list.removeFirst();
 #ifdef QT_MAC_USE_COCOA
     qt_mac_update_cursor();
 #else
     if (qApp && qApp->activeWindow()) {
         const QCursor def(Qt::ArrowCursor);
         qt_mac_set_cursor(qApp->d_func()->cursor_list.isEmpty() ? &def : &qApp->d_func()->cursor_list.first());
     }
 #endif
 }
saveState()
void QApplication::saveState (QSessionManager & manager) virtual
This function deals with Session Management{session management}.
It is invoked when the session manager wants the application to preserve its state for a future session.
For example, a text editor would create a temporary file that includes the current contents of its edit buffers, the location of the cursor and other aspects of the current editing session.
You should never exit the application within this function. Instead, the session manager may or may not do this afterwards, depending on the context. Futhermore, most session managers will very likely request a saved state immediately after the application has been started. This permits the session manager to learn about the application's restart policy.
Warning
Within this function, no user interaction is possible, unless you ask the manager for explicit permission. See QSessionManager::allowsInteraction() and QSessionManager::allowsErrorInteraction() for details.
See also
isSessionRestored(), sessionId(), commitData(), {Session Management}
Definition at line 3668 of file qapplication.cpp.
 {
     emit saveStateRequest(manager);
 }
saveStateRequest
void QApplication::saveStateRequest (QSessionManager & manager) signal
This signal deals with Session Management{session management}.
Since
4.2
It is invoked when the session manager wants the application to preserve its state for a future session.
For example, a text editor would create a temporary file that includes the current contents of its edit buffers, the location of the cursor and other aspects of the current editing session.
You should never exit the application within this signal. Instead, the session manager may or may not do this afterwards, depending on the context. Futhermore, most session managers will very likely request a saved state immediately after the application has been started. This permits the session manager to learn about the application's restart policy.
Warning
Within this function, no user interaction is possible, unless you ask the manager for explicit permission. See QSessionManager::allowsInteraction() and QSessionManager::allowsErrorInteraction() for details.
Note
You should use Qt::DirectConnection when connecting to this signal.
See also
isSessionRestored(), sessionId(), commitData(), {Session Management}
Referenced by saveState().
sessionId()
QString QApplication::sessionId () const
Returns the current Session Management{session's} identifier.
If the application has been restored from an earlier session, this identifier is the same as it was in that previous session. The session identifier is guaranteed to be unique both for different applications and for different instances of the same application.
See also
isSessionRestored(), sessionKey(), commitData(), saveState()
Definition at line 3487 of file qapplication.cpp.
 {
     Q_D(const QApplication);
     return d->session_id;
 }
sessionKey()
QString QApplication::sessionKey () const
Returns the session key in the current Session Management{session}.
If the application has been restored from an earlier session, this key is the same as it was when the previous session ended.
The session key changes with every call of commitData() or saveState().
See also
isSessionRestored(), sessionId(), commitData(), saveState()
Definition at line 3493 of file qapplication.cpp.
 {
     Q_D(const QApplication);
     return d->session_key;
 }
setActiveWindow()
void QApplication::setActiveWindow (QWidget * active) static
Sets the active window to the active widget in response to a system event.
The function is called from the platform specific event handlers.
Warning
This function does not set the keyboard focus to the active widget. Call QWidget::activateWindow() instead.
It sets the activeWindow() and focusWidget() attributes and sends proper WindowActivate/WindowDeactivate and FocusIn/FocusOut events to all appropriate widgets. The window will then be painted in active state (e.g. cursors in line edits will blink), and it will have tool tips enabled.
See also
activeWindow(), QWidget::activateWindow()
Definition at line 2622 of file qapplication.cpp.
Referenced by QWidgetPrivate::deactivateWidgetCleanup(), QApplicationPrivate::globalEventProcessor(), onApplicationChangedActivation(), q_createNativeChildrenAndSetParent(), qt_cleanup(), QtWndProc(), and QX11EmbedWidget::x11Event().
 {
     QWidget* window = act?act->window():0;
     if (QApplicationPrivate::active_window == window)
         return;
 #ifndef QT_NO_GRAPHICSVIEW
     if (window && window->graphicsProxyWidget()) {
         // Activate the proxy's view->viewport() ?
         return;
     }
 #endif
     QWidgetList toBeActivated;
     QWidgetList toBeDeactivated;
     if (QApplicationPrivate::active_window) {
         if (style()->styleHint(QStyle::SH_Widget_ShareActivation, 0, QApplicationPrivate::active_window)) {
             QWidgetList list = topLevelWidgets();
             for (int i = 0; i < list.size(); ++i) {
                 QWidget *w = list.at(i);
                 if (w->isVisible() && w->isActiveWindow())
                     toBeDeactivated.append(w);
             }
         } else {
             toBeDeactivated.append(QApplicationPrivate::active_window);
         }
     }
 #if !defined(Q_WS_MAC)
     QWidget *previousActiveWindow =  QApplicationPrivate::active_window;
 #endif
     QApplicationPrivate::active_window = window;
     if (QApplicationPrivate::active_window) {
         if (style()->styleHint(QStyle::SH_Widget_ShareActivation, 0, QApplicationPrivate::active_window)) {
             QWidgetList list = topLevelWidgets();
             for (int i = 0; i < list.size(); ++i) {
                 QWidget *w = list.at(i);
                 if (w->isVisible() && w->isActiveWindow())
                     toBeActivated.append(w);
             }
         } else {
             toBeActivated.append(QApplicationPrivate::active_window);
         }
     }
     // first the activation/deactivation events
     QEvent activationChange(QEvent::ActivationChange);
     QEvent windowActivate(QEvent::WindowActivate);
     QEvent windowDeactivate(QEvent::WindowDeactivate);
 #if !defined(Q_WS_MAC)
     if (!previousActiveWindow) {
         QEvent appActivate(QEvent::ApplicationActivate);
         sendSpontaneousEvent(qApp, &appActivate);
     }
 #endif
     for (int i = 0; i < toBeActivated.size(); ++i) {
         QWidget *w = toBeActivated.at(i);
         sendSpontaneousEvent(w, &windowActivate);
         sendSpontaneousEvent(w, &activationChange);
     }
 #ifdef QT_MAC_USE_COCOA
     // In case the user clicked on a child window, we need to
     // reestablish the stacking order of the window so
     // it pops in front of other child windows in cocoa:
     qt_cocoaStackChildWindowOnTopOfOtherChildren(window);
 #endif
     for(int i = 0; i < toBeDeactivated.size(); ++i) {
         QWidget *w = toBeDeactivated.at(i);
         sendSpontaneousEvent(w, &windowDeactivate);
         sendSpontaneousEvent(w, &activationChange);
     }
 #if !defined(Q_WS_MAC)
     if (!QApplicationPrivate::active_window) {
         QEvent appDeactivate(QEvent::ApplicationDeactivate);
         sendSpontaneousEvent(qApp, &appDeactivate);
     }
 #endif
     if (QApplicationPrivate::popupWidgets == 0) { // !inPopupMode()
         // then focus events
         if (!QApplicationPrivate::active_window && QApplicationPrivate::focus_widget) {
             QApplicationPrivate::setFocusWidget(0, Qt::ActiveWindowFocusReason);
         } else if (QApplicationPrivate::active_window) {
             QWidget *w = QApplicationPrivate::active_window->focusWidget();
             if (w && w->isVisible() /*&& w->focusPolicy() != QWidget::NoFocus*/)
                 w->setFocus(Qt::ActiveWindowFocusReason);
             else {
                 w = QApplicationPrivate::focusNextPrevChild_helper(QApplicationPrivate::active_window, true);
                 if (w) {
                     w->setFocus(Qt::ActiveWindowFocusReason);
                 } else {
                     // If the focus widget is not in the activate_window, clear the focus
                     w = QApplicationPrivate::focus_widget;
                     if (!w && QApplicationPrivate::active_window->focusPolicy() != Qt::NoFocus)
                         QApplicationPrivate::setFocusWidget(QApplicationPrivate::active_window, Qt::ActiveWindowFocusReason);
                     else if (!QApplicationPrivate::active_window->isAncestorOf(w))
                         QApplicationPrivate::setFocusWidget(0, Qt::ActiveWindowFocusReason);
                 }
             }
         }
     }
 }
setArgs()
void QApplication::setArgs (int argc, char ** argv) protected
Warning
This function is not part of the public interface.
Definition at line 3772 of file qapplication_qws.cpp.
 {
     Q_D(QApplication);
     d->argc = c;
     d->argv = v;
 }
setAutoMaximizeThreshold
void QApplication::setAutoMaximizeThreshold (const int threshold) slot
Definition at line 1402 of file qapplication.cpp.
 {
     QApplicationPrivate::autoMaximizeThreshold = threshold;
 }
setAutoSipEnabled
void QApplication::setAutoSipEnabled (const bool enabled) slot
Definition at line 1413 of file qapplication.cpp.
 {
     QApplicationPrivate::autoSipEnabled = enabled;
 }
setColorSpec()
void QApplication::setColorSpec (int spec) static
Sets the color specification for the application to spec.
The color specification controls how the application allocates colors when run on a display with a limited amount of colors, e.g. 8 bit / 256 color displays.
The color specification must be set before you create the QApplication object.
The options are:
QApplication::NormalColor. This is the default color allocation strategy. Use this option if your application uses buttons, menus, texts and pixmaps with few colors. With this option, the application uses system global colors. This works fine for most applications under X11, but on the Windows platform, it may cause dithering of non-standard colors.
QApplication::CustomColor. Use this option if your application needs a small number of custom colors. On X11, this option is the same as NormalColor. On Windows, Qt creates a Windows palette, and allocates colors to it on demand.
QApplication::ManyColor. Use this option if your application is very color hungry, e.g., it requires thousands of colors.
Under X11 the effect is:
For 256-color displays which have at best a 256 color true color visual, the default visual is used, and colors are allocated from a color cube. The color cube is the 6x6x6 (216 color) "Web palette" (the red, green, and blue components always have one of the following values: 0x00, 0x33, 0x66, 0x99, 0xCC, or 0xFF), but the number of colors can be changed by the -ncols option. The user can force the application to use the true color visual with the -visual option.
For 256-color displays which have a true color visual with more than 256 colors, use that visual. Silicon Graphics X servers this feature, for example. They provide an 8 bit visual by default but can deliver true color when asked.
On Windows, Qt creates a Windows palette, and fills it with a color cube.
Be aware that the CustomColor and ManyColor choices may lead to colormap flashing: The foreground application gets (most) of the available colors, while the background windows will look less attractive.
Example:
int main(int argc, char *argv[])
{
    QApplication::setColorSpec(QApplication::ManyColor);
    QApplication app(argc, argv);
    ...
    return app.exec();
}
See also
colorSpec()
Definition at line 1766 of file qapplication.cpp.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), and QApplicationPrivate::x11_apply_settings().
 {
     if (qApp)
         qWarning("QApplication::setColorSpec: This function must be "
                  "called before the QApplication object is created");
     QApplicationPrivate::app_cspec = spec;
 }
setCursorFlashTime()
void QApplication::setCursorFlashTime (int msecs) static
Definition at line 2792 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
 {
     QApplicationPrivate::cursor_flash_time = msecs;
 }
setDesktopSettingsAware()
void QApplication::setDesktopSettingsAware (bool on) static
Sets whether Qt should use the system's standard colors, fonts, etc., to on.
By default, this is true.
This function must be called before creating the QApplication object, like this:
int main(int argc, char *argv[])
{
    QApplication::setDesktopSettingsAware(false);
    QApplication app(argc, argv);
    ...
    return app.exec();
}
See also
desktopSettingsAware()
Definition at line 3360 of file qapplication.cpp.
 {
     QApplicationPrivate::obey_desktop_settings = on;
 }
setDoubleClickInterval()
void QApplication::setDoubleClickInterval (int ms) static
Definition at line 2802 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
 {
     qt_mac_dblclick.use_qt_time_limit = true;
     QApplicationPrivate::mouse_double_click_time = ms;
 }
setEffectEnabled()
void QApplication::setEffectEnabled (Qt::UIEffect effect, bool enable = true) static
Enables the UI effect effect if enable is true, otherwise the effect will not be used.
Note
All effects are disabled on screens running at less than 16-bit color depth.
See also
isEffectEnabled(), Qt::UIEffect, setDesktopSettingsAware()
Definition at line 2842 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), qt_set_x11_resources(), QETWidget::translateCloseEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
 {
     switch (effect) {
     case Qt::UI_FadeMenu:
         QApplicationPrivate::fade_menu = enable;
         break;
     case Qt::UI_AnimateMenu:
         QApplicationPrivate::animate_menu = enable;
         break;
     case Qt::UI_FadeTooltip:
         QApplicationPrivate::fade_tooltip = enable;
         break;
     case Qt::UI_AnimateTooltip:
         QApplicationPrivate::animate_tooltip = enable;
         break;
     case Qt::UI_AnimateCombo:
         QApplicationPrivate::animate_combo = enable;
         break;
     case Qt::UI_AnimateToolBox:
         QApplicationPrivate::animate_toolbox = enable;
         break;
     case Qt::UI_General:
         QApplicationPrivate::fade_tooltip = true;
         break;
     default:
         QApplicationPrivate::animate_ui = enable;
         break;
     }
     if (enable)
         QApplicationPrivate::animate_ui = true;
 }
setFont()
void QApplication::setFont (const QFont & font, const char * className = 0) static
Changes the default application font to font.
Use the two-argument overload instead.
If className is passed, the change applies only to classes that inherit className (as reported by QObject::inherits()).
On application start-up, the default font depends on the window system. It can vary depending on both the window system version and the locale. This function lets you override the default font; but overriding may be a bad idea because, for example, some locales need extra large fonts to support their special characters.
Warning
Do not use this function in conjunction with Qt Style Sheets. The font of an application can be customized using the "font" style sheet property. To set a bold font for all QPushButtons, set the application styleSheet() as "QPushButton { font: bold }"
See also
font(), fontMetrics(), QWidget::setFont()
Definition at line 2075 of file qapplication.cpp.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), qt_set_qws_resources(), qt_set_windows_font_resources(), QFont::resolve(), QToolTip::setFont(), and QApplicationPrivate::setSystemFont().
 {
     bool all = false;
     FontHash *hash = app_fonts();
     if (!className) {
         QMutexLocker locker(applicationFontMutex());
         if (!QApplicationPrivate::app_font)
             QApplicationPrivate::app_font = new QFont(font);
         else
             *QApplicationPrivate::app_font = font;
         if (hash && hash->size()) {
             all = true;
             hash->clear();
         }
     } else if (hash) {
         hash->insert(className, font);
     }
     if (QApplicationPrivate::is_app_running && !QApplicationPrivate::is_app_closing) {
         // Send ApplicationFontChange to qApp itself, and to the widgets.
         QEvent e(QEvent::ApplicationFontChange);
         QApplication::sendEvent(QApplication::instance(), &e);
         QWidgetList wids = QApplication::allWidgets();
         for (QWidgetList::ConstIterator it = wids.constBegin(); it != wids.constEnd(); ++it) {
             register QWidget *w = *it;
             if (all || (!className && w->isWindow()) || w->inherits(className)) // matching class
                 sendEvent(w, &e);
         }
 #ifndef QT_NO_GRAPHICSVIEW
         // Send to all scenes as well.
         QList<QGraphicsScene *> &scenes = qApp->d_func()->scene_list;
         for (QList<QGraphicsScene *>::ConstIterator it = scenes.constBegin();
              it != scenes.constEnd(); ++it) {
             QApplication::sendEvent(*it, &e);
         }
 #endif //QT_NO_GRAPHICSVIEW
     }
     if (!className && (!QApplicationPrivate::sys_font || !font.isCopyOf(*QApplicationPrivate::sys_font))) {
         if (!QApplicationPrivate::set_font)
             QApplicationPrivate::set_font = new QFont(font);
         else
             *QApplicationPrivate::set_font = font;
     }
 }
setGlobalStrut()
void QApplication::setGlobalStrut (const QSize & strut) static
Definition at line 1797 of file qapplication.cpp.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), and QApplicationPrivate::x11_apply_settings().
 {
     QApplicationPrivate::app_strut = strut;
 }
setGraphicsSystem()
void QApplication::setGraphicsSystem (const QString & system) static
Sets the default graphics backend to system, which will be used for on-screen widgets and QPixmaps.
Since
4.5
The available systems are "native", "raster" and "opengl".
There are several ways to set the graphics backend, in order of decreasing precedence:
the application commandline -graphicssystem switch
QApplication::setGraphicsSystem()
the QT_GRAPHICSSYSTEM environment variable
the Qt configure -graphicssystem switch
If the highest precedence switch sets an invalid name, the error will be ignored and the default backend will be used.
Warning
This function is only effective before the QApplication constructor is called.
Note
The "opengl" option is currently experimental.
Definition at line 1684 of file qapplication.cpp.
Referenced by QMeeGoGraphicsSystem::switchToMeeGo(), and QMeeGoGraphicsSystem::switchToRaster().
 {
 #ifdef Q_WS_QPA
         Q_UNUSED(system);
 #else
 # ifdef QT_GRAPHICSSYSTEM_RUNTIME
     if (QApplicationPrivate::graphics_system_name == QLatin1String("runtime")) {
         QRuntimeGraphicsSystem *r =
                 static_cast<QRuntimeGraphicsSystem *>(QApplicationPrivate::graphics_system);
         r->setGraphicsSystem(system);
     } else
 # endif
         QApplicationPrivate::graphics_system_name = system;
 #endif
 }
setInputContext()
void QApplication::setInputContext (QInputContext * inputContext)
This function replaces the QInputContext instance used by the application with inputContext.
Qt takes ownership of the given inputContext.
See also
inputContext()
Definition at line 5701 of file qapplication.cpp.
 {
     if (inputContext == QApplicationPrivate::inputContext)
         return;
     if (!inputContext) {
         qWarning("QApplication::setInputContext: called with 0 input context");
         return;
     }
     delete QApplicationPrivate::inputContext;
     QApplicationPrivate::inputContext = inputContext;
     QApplicationPrivate::inputContext->setParent(this);
 }
setKeyboardInputInterval()
void QApplication::setKeyboardInputInterval (int ms) static
Definition at line 2819 of file qapplication_mac.mm.
Referenced by QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), and QETWidget::updateRegion().
 {
     QApplicationPrivate::keyboard_input_time = ms;
 }
setLayoutDirection()
void QApplication::setLayoutDirection (Qt::LayoutDirection direction) static
Definition at line 3804 of file qapplication.cpp.
Referenced by event(), and QApplicationPrivate::process_cmdline().
 {
     if (layout_direction == direction || direction == Qt::LayoutDirectionAuto)
         return;
     layout_direction = direction;
     QWidgetList list = topLevelWidgets();
     for (int i = 0; i < list.size(); ++i) {
         QWidget *w = list.at(i);
         QEvent ev(QEvent::ApplicationLayoutDirectionChange);
         sendEvent(w, &ev);
     }
 }
setOverrideCursor()
void QApplication::setOverrideCursor (const QCursor & cursor) static
Use changeOverrideCursor(cursor) (if replace is true) or setOverrideCursor(cursor) (if replace is false).
Sets the application override cursor to cursor.
Application override cursors are intended for showing the user that the application is in a special state, for example during an operation that might take some time.
This cursor will be displayed in all the application's widgets until restoreOverrideCursor() or another setOverrideCursor() is called.
Application cursors are stored on an internal stack. setOverrideCursor() pushes the cursor onto the stack, and restoreOverrideCursor() pops the active cursor off the stack. changeOverrideCursor() changes the curently active application override cursor.
Every setOverrideCursor() must eventually be followed by a corresponding restoreOverrideCursor(), otherwise the stack will never be emptied.
Example:
QApplication::setOverrideCursor(QCursor(Qt::WaitCursor));
calculateHugeMandelbrot();              // lunch time...
QApplication::restoreOverrideCursor();
See also
overrideCursor(), restoreOverrideCursor(), changeOverrideCursor(), QWidget::setCursor()
Definition at line 1407 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::applyX11SpecificCommandLineArguments(), changeOverrideCursor(), parseGeometry(), QGuiEventDispatcherWin32::processEvents(), QAxSelect::QAxSelect(), QWhatsThisPrivate::QWhatsThisPrivate(), and QTextBrowserPrivate::setSource().
 {
     qApp->d_func()->cursor_list.prepend(cursor);
 #ifdef QT_MAC_USE_COCOA
     qt_mac_update_cursor();
 #else
     if (qApp && qApp->activeWindow())
         qt_mac_set_cursor(&qApp->d_func()->cursor_list.first());
 #endif
 }
setPalette()
void QApplication::setPalette (const QPalette & palette, const char * className = 0) static
Changes the default application palette to palette.
Use the two-argument overload instead.
If className is passed, the change applies only to widgets that inherit className (as reported by QObject::inherits()). If className is left 0, the change affects all widgets, thus overriding any previously set class specific palettes.
The palette may be changed according to the current GUI style in QStyle::polish().
Warning
Do not use this function in conjunction with Qt Style Sheets. When using style sheets, the palette of a widget can be customized using the "color", "background-color", "selection-color", "selection-background-color" and "alternate-background-color".
Note
Some styles do not use the palette for all drawing, for instance, if they make use of native theme engines. This is the case for the Windows XP, Windows Vista, and Mac OS X styles.
See also
QWidget::setPalette(), palette(), QStyle::polish()
Definition at line 1941 of file qapplication.cpp.
Referenced by QApplicationPrivate::initializeWidgetPaletteHash(), QApplicationPrivate::qt_mac_apply_settings(), setStyle(), QApplicationPrivate::setSystemPalette(), style(), and QGtkStyleUpdateScheduler::updateTheme().
 {
     QApplicationPrivate::setPalette_helper(palette, className, /*clearWidgetPaletteHash=*/ true);
 }
setQuitOnLastWindowClosed()
void QApplication::setQuitOnLastWindowClosed (bool quit) static
Definition at line 5328 of file qapplication.cpp.
Referenced by main().
 {
     QApplicationPrivate::quitOnLastWindowClosed = quit;
 }
setStartDragDistance()
void QApplication::setStartDragDistance (int l) static
Definition at line 3715 of file qapplication.cpp.
 {
     drag_distance = l;
 }
setStartDragTime()
void QApplication::setStartDragTime (int ms) static
Definition at line 3679 of file qapplication.cpp.
 {
     drag_time = ms;
 }
setStyle() [1/2]
void QApplication::setStyle (QStyle * style) static
Sets the application's GUI style to style.
Ownership of the style object is transferred to QApplication, so QApplication will delete the style object on application exit or when a new style is set and the old style is still the parent of the application object.
Example usage:
QApplication::setStyle(new QWindowsStyle);
When switching application styles, the color palette is set back to the initial colors or the system defaults. This is necessary since certain styles have to adapt the color palette to be fully style-guide compliant.
Setting the style before a palette has been set, i.e., before creating QApplication, will cause the application to use QStyle::standardPalette() for the palette.
Warning
Qt style sheets are currently not supported for custom QStyle subclasses. We plan to address this in some future release.
See also
style(), QStyle, setPalette(), desktopSettingsAware()
Definition at line 1534 of file qapplication.cpp.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), setStyle(), setStyleSheet(), and QApplicationPrivate::x11_apply_settings().
 {
     if (!style || style == QApplicationPrivate::app_style)
         return;
     QWidgetList all = allWidgets();
     // clean up the old style
     if (QApplicationPrivate::app_style) {
         if (QApplicationPrivate::is_app_running && !QApplicationPrivate::is_app_closing) {
             for (QWidgetList::ConstIterator it = all.constBegin(); it != all.constEnd(); ++it) {
                 register QWidget *w = *it;
                 if (!(w->windowType() == Qt::Desktop) &&        // except desktop
                      w->testAttribute(Qt::WA_WState_Polished)) { // has been polished
                     QApplicationPrivate::app_style->unpolish(w);
                 }
             }
         }
         QApplicationPrivate::app_style->unpolish(qApp);
     }
     QStyle *old = QApplicationPrivate::app_style; // save
 #ifndef QT_NO_STYLE_STYLESHEET
     if (!QApplicationPrivate::styleSheet.isEmpty() && !qobject_cast<QStyleSheetStyle *>(style)) {
         // we have a stylesheet already and a new style is being set
         QStyleSheetStyle *newProxy = new QStyleSheetStyle(style);
         style->setParent(newProxy);
         QApplicationPrivate::app_style = newProxy;
     } else
 #endif // QT_NO_STYLE_STYLESHEET
         QApplicationPrivate::app_style = style;
     QApplicationPrivate::app_style->setParent(qApp); // take ownership
     // take care of possible palette requirements of certain gui
     // styles. Do it before polishing the application since the style
     // might call QApplication::setPalette() itself
     if (QApplicationPrivate::set_pal) {
         QApplication::setPalette(*QApplicationPrivate::set_pal);
     } else if (QApplicationPrivate::sys_pal) {
         QApplicationPrivate::initializeWidgetPaletteHash();
         QApplicationPrivate::setPalette_helper(*QApplicationPrivate::sys_pal, /*className=*/0, /*clearWidgetPaletteHash=*/false);
     } else if (!QApplicationPrivate::sys_pal) {
         // Initialize the sys_pal if it hasn't happened yet...
         QApplicationPrivate::setSystemPalette(QApplicationPrivate::app_style->standardPalette());
     }
     // initialize the application with the new style
     QApplicationPrivate::app_style->polish(qApp);
     // re-polish existing widgets if necessary
     if (QApplicationPrivate::is_app_running && !QApplicationPrivate::is_app_closing) {
         for (QWidgetList::ConstIterator it1 = all.constBegin(); it1 != all.constEnd(); ++it1) {
             register QWidget *w = *it1;
             if (w->windowType() != Qt::Desktop && w->testAttribute(Qt::WA_WState_Polished)) {
                 if (w->style() == QApplicationPrivate::app_style)
                     QApplicationPrivate::app_style->polish(w);                // repolish
 #ifndef QT_NO_STYLE_STYLESHEET
                 else
                     w->setStyleSheet(w->styleSheet()); // touch
 #endif
             }
         }
         for (QWidgetList::ConstIterator it2 = all.constBegin(); it2 != all.constEnd(); ++it2) {
             register QWidget *w = *it2;
             if (w->windowType() != Qt::Desktop && !w->testAttribute(Qt::WA_SetStyle)) {
                     QEvent e(QEvent::StyleChange);
                     QApplication::sendEvent(w, &e);
 #ifdef QT3_SUPPORT
                     if (old)
                         w->styleChange(*old);
 #endif
                     w->update();
             }
         }
     }
 #ifndef QT_NO_STYLE_STYLESHEET
     if (QStyleSheetStyle *oldProxy = qobject_cast<QStyleSheetStyle *>(old)) {
         oldProxy->deref();
     } else
 #endif
     if (old && old->parent() == qApp) {
         delete old;
     }
     if (QApplicationPrivate::focus_widget) {
         QFocusEvent in(QEvent::FocusIn, Qt::OtherFocusReason);
         QApplication::sendEvent(QApplicationPrivate::focus_widget->style(), &in);
         QApplicationPrivate::focus_widget->update();
     }
 }
setStyle() [2/2]
QStyle * QApplication::setStyle (const QString & style) static
Requests a QStyle object for style from the QStyleFactory.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The string must be one of the QStyleFactory::keys(), typically one of "windows", "motif", "cde", "plastique", "windowsxp", or "macintosh". Style names are case insensitive.
Returns 0 if an unknown style is passed, otherwise the QStyle object returned is set as the application's GUI style.
Warning
To ensure that the application's style is set correctly, it is best to call this function before the QApplication constructor, if possible.
Definition at line 1647 of file qapplication.cpp.
 {
     QStyle *s = QStyleFactory::create(style);
     if (!s)
         return 0;
     setStyle(s);
     return s;
 }
setStyleSheet
void QApplication::setStyleSheet (const QString & sheet) slot
Definition at line 1430 of file qapplication.cpp.
 {
     QApplicationPrivate::styleSheet = styleSheet;
     QStyleSheetStyle *proxy = qobject_cast<QStyleSheetStyle*>(QApplicationPrivate::app_style);
     if (styleSheet.isEmpty()) { // application style sheet removed
         if (!proxy)
             return; // there was no stylesheet before
         setStyle(proxy->base);
     } else if (proxy) { // style sheet update, just repolish
         proxy->repolish(qApp);
     } else { // stylesheet set the first time
         QStyleSheetStyle *newProxy = new QStyleSheetStyle(QApplicationPrivate::app_style);
         QApplicationPrivate::app_style->setParent(newProxy);
         setStyle(newProxy);
     }
 }
setWheelScrollLines()
void QApplication::setWheelScrollLines (int n) static
Definition at line 2831 of file qapplication_mac.mm.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
 {
     QApplicationPrivate::wheel_scroll_lines = n;
 }
setWindowIcon()
void QApplication::setWindowIcon (const QIcon & icon) static
Definition at line 2155 of file qapplication.cpp.
 {
     if (!QApplicationPrivate::app_icon)
         QApplicationPrivate::app_icon = new QIcon();
     *QApplicationPrivate::app_icon = icon;
     if (QApplicationPrivate::is_app_running && !QApplicationPrivate::is_app_closing) {
 #ifdef Q_WS_MAC
         void qt_mac_set_app_icon(const QPixmap &); //qapplication_mac.cpp
         QSize size = QApplicationPrivate::app_icon->actualSize(QSize(128, 128));
         qt_mac_set_app_icon(QApplicationPrivate::app_icon->pixmap(size));
 #endif
         QEvent e(QEvent::ApplicationWindowIconChange);
         QWidgetList all = QApplication::allWidgets();
         for (QWidgetList::ConstIterator it = all.constBegin(); it != all.constEnd(); ++it) {
             register QWidget *w = *it;
             if (w->isWindow())
                 sendEvent(w, &e);
         }
     }
 }
startDragDistance()
static int QApplication::startDragDistance () static
Referenced by QDeclarativePathViewPrivate::handleMouseMoveEvent(), QDeclarativeFlickablePrivate::handleMouseMoveEvent(), QMenuPrivate::hasMouseMoved(), QDockWidgetPrivate::mouseMoveEvent(), QToolBarPrivate::mouseMoveEvent(), QTextControlPrivate::mouseMoveEvent(), QDeclarativeMouseArea::mouseMoveEvent(), QTabBar::mouseMoveEvent(), QHeaderView::mouseMoveEvent(), QLineEdit::mouseMoveEvent(), QGraphicsView::mouseMoveEvent(), QDeclarativeTextInput::mouseMoveEvent(), QAbstractItemView::mouseMoveEvent(), QColorWell::mouseMoveEvent(), QColorShowLabel::mouseMoveEvent(), QTextControlPrivate::mousePressEvent(), QLineEdit::mousePressEvent(), QToolBarAreaLayoutInfo::moveToolBar(), QLineControl::processMouseEvent(), setStartDragDistance(), and QDeclarativePinchArea::updatePinch().
startDragTime()
static int QApplication::startDragTime () static
Referenced by QLineEdit::mousePressEvent(), and setStartDragTime().
style()
QStyle * QApplication::style () static
Returns the application's style object.
See also
setStyle(), QStyle
Definition at line 1454 of file qapplication.cpp.
Referenced by QStyleSheetStyle::baseStyle(), QItemDelegate::check(), QDialogButtonBoxPrivate::createButton(), QItemDelegate::doLayout(), QItemDelegate::drawCheck(), QItemDelegate::drawDisplay(), QItemDelegate::drawFocus(), drawTextItemDecoration(), QStyledItemDelegate::editorEvent(), QWizardPrivate::ensureButton(), QFileIconProviderPrivate::getIcon(), QTextControl::getPaintContext(), QFormLayoutPrivate::getStyle(), QTabBarPrivate::layoutTabs(), QDecorationStyled::paint(), QStyledItemDelegate::paint(), QColumnViewDelegate::paint(), QSvgIconEngine::pixmap(), QPixmapIconEngine::pixmap(), qt_mac_update_os_settings(), QtWndProc(), QDecorationStyled::region(), setActiveWindow(), QTextControl::setOverwriteMode(), setStyle(), QSystemTrayIconPrivate::showMessage_sys(), QStyledItemDelegate::sizeHint(), QMessageBoxPrivate::standardIcon(), QGraphicsWidget::style(), QGraphicsScene::style(), QWidget::style(), QGraphicsGridLayoutPrivate::styleInfo(), QGraphicsLinearLayoutPrivate::styleInfo(), QGraphicsAnchorLayoutPrivate::styleInfo(), QItemDelegate::textRectangle(), QTextControl::timerEvent(), QDecorationStyled::titleBarHeight(), QStyledItemDelegate::updateEditorGeometry(), and QMessageBoxPrivate::updateSize().
 {
     if (QApplicationPrivate::app_style)
         return QApplicationPrivate::app_style;
     if (!qt_is_gui_used) {
         Q_ASSERT(!"No style available in non-gui applications!");
         return 0;
     }
     if (!QApplicationPrivate::app_style) {
         // Compile-time search for default style
         //
         QString style;
 #ifdef QT_BUILD_INTERNAL
         QString envStyle = QString::fromLocal8Bit(qgetenv("QT_STYLE_OVERRIDE"));
 #else
         QString envStyle;
 #endif
         if (!QApplicationPrivate::styleOverride.isEmpty()) {
             style = QApplicationPrivate::styleOverride;
         } else if (!envStyle.isEmpty()) {
             style = envStyle;
         } else {
             style = QApplicationPrivate::desktopStyleKey();
         }
         QStyle *&app_style = QApplicationPrivate::app_style;
         app_style = QStyleFactory::create(style);
         if (!app_style) {
             QStringList styles = QStyleFactory::keys();
             for (int i = 0; i < styles.size(); ++i) {
                 if ((app_style = QStyleFactory::create(styles.at(i))))
                     break;
             }
         }
         if (!app_style) {
             Q_ASSERT(!"No styles available!");
             return 0;
         }
     }
     // take ownership of the style
     QApplicationPrivate::app_style->setParent(qApp);
     if (!QApplicationPrivate::sys_pal)
         QApplicationPrivate::setSystemPalette(QApplicationPrivate::app_style->standardPalette());
     if (QApplicationPrivate::set_pal) // repolish set palette with the new style
         QApplication::setPalette(*QApplicationPrivate::set_pal);
 #ifndef QT_NO_STYLE_STYLESHEET
     if (!QApplicationPrivate::styleSheet.isEmpty()) {
         qApp->setStyleSheet(QApplicationPrivate::styleSheet);
     } else
 #endif
         QApplicationPrivate::app_style->polish(qApp);
     return QApplicationPrivate::app_style;
 }
styleSheet()
QString QApplication::styleSheet () const
Referenced by setAutoSipEnabled(), and setStyleSheet().
syncX()
void QApplication::syncX () static
Synchronizes with the X server in the X11 implementation.
This normally takes some time. Does nothing on other platforms.
Definition at line 3029 of file qapplication_x11.cpp.
Referenced by event(), QWidgetResizeHandler::mouseMoveEvent(), QWidgetBackingStore::showYellowThing(), and QETWidget::translateConfigEvent().
 {
     if (X11->display)
         XSync(X11->display, False);  // don't discard events
 }
topLevelAt() [1/2]
QWidget * QApplication::topLevelAt (const QPoint & p) static
Returns the top-level widget at the given point; returns 0 if there is no such widget.
Definition at line 1441 of file qapplication_mac.mm.
Referenced by QX11Data::findClientWindow(), parseGeometry(), qt_cleanup(), qt_qpa_set_cursor(), qt_win_getKeyboardModifiers(), QApplicationPrivate::translateRawTouchEvent(), and widgetAt().
 {
 #ifndef QT_MAC_USE_COCOA
     QWidget *widget;
     qt_mac_window_at(p.x(), p.y(), &widget);
     return widget;
 #else
     // Use a cache to avoid iterate through the whole list of windows for all
     // calls to to topLevelAt. We e.g. do this for each and every mouse
     // move since we need to find the widget under mouse:
     if (topLevelAt_cache && topLevelAt_cache->frameGeometry().contains(p))
         return topLevelAt_cache;
     // INVARIANT: Cache miss. Go through the list if windows instead:
     QMacCocoaAutoReleasePool pool;
     NSPoint cocoaPoint = flipPoint(p);
     NSInteger windowCount;
     NSCountWindows(&windowCount);
     if (windowCount <= 0)
         return 0;  // There's no window to find!
     QVarLengthArray<NSInteger> windowList(windowCount);
     NSWindowList(windowCount, windowList.data());
     int firstQtWindowFound = -1;
     for (int i = 0; i < windowCount; ++i) {
         NSWindow *window = [NSApp windowWithWindowNumber:windowList[i]];
         if (window) {
             QWidget *candidateWindow = [window QT_MANGLE_NAMESPACE(qt_qwidget)];
             if (candidateWindow && firstQtWindowFound == -1)
                 firstQtWindowFound = i;
             if (NSPointInRect(cocoaPoint, [window frame])) {
                 // Check to see if there's a hole in the window where the mask is.
                 // If there is, we should just continue to see if there is a window below.
                 if (candidateWindow && !candidateWindow->mask().isEmpty()) {
                     QPoint localPoint = candidateWindow->mapFromGlobal(p);
                     if (!candidateWindow->mask().contains(localPoint))
                         continue;
                     else
                         return candidateWindow;
                 } else {
                     if (i == firstQtWindowFound) {
                         // The cache will only work when the window under mouse is
                         // top most (that is, not partially obscured by other windows.
                         // And we only set it if no mask is present to optimize for the common case:
                         topLevelAt_cache = candidateWindow;
                     }
                     return candidateWindow;
                 }
             }
         }
     }
     topLevelAt_cache = 0;
     return 0;
 #endif
 }
topLevelAt() [2/2]
QWidget * QApplication::topLevelAt (int x, int y) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the top-level widget at the point ({x}, {y}); returns 0 if there is no such widget.
Definition at line 196 of file qapplication.h.
Referenced by topLevelAt().
 { return topLevelAt(QPoint(x, y)); }
topLevelWidgets()
QWidgetList QApplication::topLevelWidgets () static
Returns a list of the top-level widgets (windows) in the application.
Note
Some of the top-level widgets may be hidden, for example a tooltip if no tooltip is currently shown.
Example:
void showAllHiddenTopLevelWidgets()
{
    foreach (QWidget *widget, QApplication::topLevelWidgets()) {
        if (widget->isHidden())
            widget->show();
    }
}
See also
allWidgets(), QWidget::isWindow(), QWidget::isHidden()
Definition at line 2188 of file qapplication.cpp.
Referenced by QDialog::adjustPosition(), QApplicationPrivate::canQuit(), QKeyMapper::changeKeyboard(), QWidgetPrivate::close_helper(), closeAllWindows(), commitData(), QApplicationPrivate::enterModal(), event(), QX11Data::findClientWindow(), findWindowThatShouldDisplayMenubar(), QEventDispatcherMac::flush(), QApplicationPrivate::globalEventProcessor(), QApplicationPrivate::leaveModal(), QWhatsThisPrivate::notifyToplevels(), qt_cleanup(), qt_mac_should_disable_menu(), QtWndProc(), setActiveWindow(), setLayoutDirection(), QApplicationPrivate::setMaxWindowRect(), QApplicationPrivate::setScreenTransformation(), QPlatformScreen::topLevelAt(), and topLevelWidgets().
 {
     QWidgetList list;
     QWidgetList all = allWidgets();
     for (QWidgetList::ConstIterator it = all.constBegin(); it != all.constEnd(); ++it) {
         QWidget *w = *it;
         if (w->isWindow() && w->windowType() != Qt::Desktop)
             list.append(w);
     }
     return list;
 }
type()
QApplication::Type QApplication::type () static
Returns the type of application (Tty , GuiClient, or GuiServer).
The type is set when constructing the QApplication object.
Definition at line 1050 of file qapplication.cpp.
Referenced by attachLayer(), QVNCScreenPrivate::configure(), QAhiScreen::connect(), QQnxScreen::connect(), QLinuxFbScreen::connect(), createMemSurface(), QDirectFBScreen::createSurface(), QScreen::createSurface(), QDeclarativeItemModule::defineModule(), QDeclarativeUtilModule::defineModule(), QDeclarativeItemModule::defineModuleCompat(), QDeclarativeUtilModule::defineModuleCompat(), QWidgetPrivate::init(), notify(), QApplication(), QShapedPixmapWidget::QShapedPixmapWidget(), qt_cleanup(), qt_init(), qt_set_windows_resources(), QtWndProc(), and QDeclarativeValueTypeFactory::registerValueTypesCompat().
 {
     return qt_appType;
 }
wheelScrollLines()
static int QApplication::wheelScrollLines () static
Referenced by QApplicationPrivate::qt_mac_apply_settings(), QAbstractSliderPrivate::scrollByDelta(), setWheelScrollLines(), QETWidget::translateCloseEvent(), QETWidget::translateGestureEvent(), QETWidget::updateRegion(), and QApplicationPrivate::x11_apply_settings().
widgetAt() [1/2]
QWidget * QApplication::widgetAt (const QPoint & point) static
Returns the widget at global screen position point, or 0 if there is no Qt widget there.
This function can be slow.
See also
QCursor::pos(), QWidget::grabMouse(), QWidget::grabKeyboard()
Definition at line 1242 of file qapplication.cpp.
Referenced by QCompleter::eventFilter(), flipPoint(), QApplicationPrivate::globalEventProcessor(), QApplicationPrivate::leaveModal_sys(), make_widget_eventUPP(), make_win_eventUPP(), parseGeometry(), qstring_to_xtp(), qt_mac_update_cursor(), qt_mac_update_cursor_at_global_pos(), qt_qpa_set_cursor(), QtWndProc(), QWhatsThisPrivate::QWhatsThisPrivate(), QApplicationPrivate::sendMouseEvent(), QWSServerPrivate::sendMouseEventUnfiltered(), QCursor::setPos(), QETWidget::translateMouseEvent(), QETWidget::translateTabletEvent(), QETWidget::translateWheelEvent(), and x11EventFilter().
 {
     QWidget *window = QApplication::topLevelAt(p);
     if (!window)
         return 0;
     QWidget *child = 0;
     if (!window->testAttribute(Qt::WA_TransparentForMouseEvents))
         child = window->childAt(window->mapFromGlobal(p));
     if (child)
         return child;
     if (window->testAttribute(Qt::WA_TransparentForMouseEvents)) {
         //shoot a hole in the widget and try once again,
         //suboptimal on Qt for Embedded Linux where we do
         //know the stacking order of the toplevels.
         int x = p.x();
         int y = p.y();
         QRegion oldmask = window->mask();
         QPoint wpoint = window->mapFromGlobal(QPoint(x, y));
         QRegion newmask = (oldmask.isEmpty() ? QRegion(window->rect()) : oldmask)
                           - QRegion(wpoint.x(), wpoint.y(), 1, 1);
         window->setMask(newmask);
         QWidget *recurse = 0;
         if (QApplication::topLevelAt(p) != window) // verify recursion will terminate
             recurse = widgetAt(x, y);
         if (oldmask.isEmpty())
             window->clearMask();
         else
             window->setMask(oldmask);
         return recurse;
     }
     return window;
 }
widgetAt() [2/2]
QWidget * QApplication::widgetAt (int x, int y) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the widget at global screen position (x, y), or 0 if there is no Qt widget there.
Definition at line 194 of file qapplication.h.
Referenced by widgetAt().
 { return widgetAt(QPoint(x, y)); }
windowIcon()
static QIcon QApplication::windowIcon () static
Referenced by QApplicationPrivate::desktopStyleKey(), QWindowsVistaStyle::drawControl(), QWindowsXPStyle::drawControl(), QWidget::setWindowTitle(), QCommonStyle::subElementRect(), and QMacStyle::subElementRect().
winFocus()
void QApplication::winFocus (QWidget * widget, bool gotFocus)
Warning
This function is not part of the public interface.
Since
4.1
If gotFocus is true, widget will become the active window. Otherwise the active window is reset to 0.
Definition at line 1407 of file qapplication_win.cpp.
 {
     if (d_func()->inPopupMode()) // some delayed focus event to ignore
         return;
     if (gotFocus) {
         setActiveWindow(widget);
         if (QApplicationPrivate::active_window
             && (QApplicationPrivate::active_window->windowType() == Qt::Dialog)) {
             // raise the entire application, not just the dialog
             QWidget* mw = QApplicationPrivate::active_window;
 #ifndef Q_WS_WINCE
             while(mw->parentWidget() && (mw->windowType() == Qt::Dialog))
                 mw = mw->parentWidget()->window();
             if (mw->testAttribute(Qt::WA_WState_Created) && mw != QApplicationPrivate::active_window)
                 SetWindowPos(mw->internalWinId(), HWND_TOP, 0, 0, 0, 0, SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE);
 #else
             // On Desktop Windows, we set the first parent of the dialog on top
             // Child windows will be automatically set above again.
             // On Windows CE we pass no parent in CreateWindowEx as otherwise
             // dialogs get embedded into the parent window. Thus we need to
             // manually iterate and reactivate all windows from bottom up.
             QList<QWidget*> raiseList;
             raiseList.push_back(mw);
             while(mw->parentWidget() && (mw->windowType() == Qt::Dialog)) {
                 mw = mw->parentWidget()->window();
                 raiseList.push_back(mw);
             }
             while(!raiseList.isEmpty()) {
                 mw = raiseList.takeLast();
                 if (mw->testAttribute(Qt::WA_WState_Created)) {
                     HWND state = HWND_TOP;
                     if (mw->windowFlags() & Qt::WindowStaysOnBottomHint)
                         state = HWND_BOTTOM;
                     else if (mw->windowFlags() & Qt::WindowStaysOnTopHint)
                         state = HWND_TOPMOST;
                     SetWindowPos(mw->internalWinId(), state, 0, 0, 0, 0, SWP_NOACTIVATE | SWP_NOMOVE | SWP_NOSIZE);
                 }
             }
 #endif
         }
     } else {
         setActiveWindow(0);
     }
 }
winMouseButtonUp()
void QApplication::winMouseButtonUp () static
Warning
This function is not part of the public interface.
Definition at line 3033 of file qapplication_win.cpp.
 {
     qt_button_down = 0;
     releaseAutoCapture();
 }
x11ClientMessage()
int QApplication::x11ClientMessage (QWidget * w, XEvent * event, bool passive_only) virtual
Warning
This function is not part of the public interface.
Definition at line 3149 of file qapplication_x11.cpp.
 {
     if (w && !w->internalWinId())
         return 0;
     QETWidget *widget = (QETWidget*)w;
     if (event->xclient.format == 32 && event->xclient.message_type) {
         if (event->xclient.message_type == ATOM(WM_PROTOCOLS)) {
             Atom a = event->xclient.data.l[0];
             if (a == ATOM(WM_DELETE_WINDOW)) {
                 if (passive_only) return 0;
                 widget->translateCloseEvent(event);
             }
             else if (a == ATOM(WM_TAKE_FOCUS)) {
                 if ((ulong) event->xclient.data.l[1] > X11->time)
                     X11->time = event->xclient.data.l[1];
                 QWidget *amw = activeModalWidget();
                 if (amw && amw->testAttribute(Qt::WA_X11DoNotAcceptFocus))
                     amw = 0;
                 if (amw && !QApplicationPrivate::tryModalHelper(widget, 0)) {
                     QWidget *p = amw->parentWidget();
                     while (p && p != widget)
                         p = p->parentWidget();
                     if (!p || !X11->net_supported_list)
                         amw->raise(); // help broken window managers
                     amw->activateWindow();
                 }
 #ifndef QT_NO_WHATSTHIS
             } else if (a == ATOM(_NET_WM_CONTEXT_HELP)) {
                 QWhatsThis::enterWhatsThisMode();
 #endif // QT_NO_WHATSTHIS
             } else if (a == ATOM(_NET_WM_PING)) {
                 // avoid send/reply loops
                 Window root = RootWindow(X11->display, w->x11Info().screen());
                 if (event->xclient.window != root) {
                     event->xclient.window = root;
                     XSendEvent(event->xclient.display, event->xclient.window,
                                 False, SubstructureNotifyMask|SubstructureRedirectMask, event);
                 }
 #ifndef QT_NO_XSYNC
             } else if (a == ATOM(_NET_WM_SYNC_REQUEST)) {
                 const ulong timestamp = (const ulong) event->xclient.data.l[1];
                 if (timestamp > X11->time)
                     X11->time = timestamp;
                 if (QTLWExtra *tlw = w->d_func()->maybeTopData()) {
                     if (timestamp == CurrentTime || timestamp > tlw->syncRequestTimestamp) {
                         tlw->syncRequestTimestamp = timestamp;
                         tlw->newCounterValueLo = event->xclient.data.l[2];
                         tlw->newCounterValueHi = event->xclient.data.l[3];
                     }
                 }
 #endif
             }
         } else if (event->xclient.message_type == ATOM(_QT_SCROLL_DONE)) {
             widget->translateScrollDoneEvent(event);
         } else if (event->xclient.message_type == ATOM(XdndPosition)) {
             X11->xdndHandlePosition(widget, event, passive_only);
         } else if (event->xclient.message_type == ATOM(XdndEnter)) {
             X11->xdndHandleEnter(widget, event, passive_only);
         } else if (event->xclient.message_type == ATOM(XdndStatus)) {
             X11->xdndHandleStatus(widget, event, passive_only);
         } else if (event->xclient.message_type == ATOM(XdndLeave)) {
             X11->xdndHandleLeave(widget, event, passive_only);
         } else if (event->xclient.message_type == ATOM(XdndDrop)) {
             X11->xdndHandleDrop(widget, event, passive_only);
         } else if (event->xclient.message_type == ATOM(XdndFinished)) {
             X11->xdndHandleFinished(widget, event, passive_only);
         } else {
             if (passive_only) return 0;
             // All other are interactions
         }
     } else {
         X11->motifdndHandle(widget, event, passive_only);
     }
     return 0;
 }
x11EventFilter()
bool QApplication::x11EventFilter (XEvent * event) virtual
Warning
This virtual function is only implemented under X11.
If you create an application that inherits QApplication and reimplement this function, you get direct access to all X events that the are received from the X server. The events are passed in the event parameter.
Return true if you want to stop the event from being processed. Return false for normal event dispatching. The default implementation returns false.
It is only the directly addressed messages that are filtered. You must install an event filter directly on the event dispatcher, which is returned by QAbstractEventDispatcher::instance(), to handle system wide messages.
See also
x11ProcessEvent()
Definition at line 3927 of file qapplication_x11.cpp.
 {
     return false;
 }
x11ProcessEvent()
int QApplication::x11ProcessEvent (XEvent * event)
This function does the core processing of individual X {event}s, normally by dispatching Qt events to the right destination.
It returns 1 if the event was consumed by special handling, 0 if the event was consumed by normal handling, and -1 if the event was for an unrecognized widget.
See also
x11EventFilter()
Definition at line 3226 of file qapplication_x11.cpp.
 {
     Q_D(QApplication);
     QScopedLoopLevelCounter loopLevelCounter(d->threadData);
 #ifdef ALIEN_DEBUG
     //qDebug() << "QApplication::x11ProcessEvent:" << event->type;
 #endif
     switch (event->type) {
     case ButtonPress:
         pressed_window = event->xbutton.window;
         X11->userTime = event->xbutton.time;
         // fallthrough intended
     case ButtonRelease:
         X11->time = event->xbutton.time;
         break;
     case MotionNotify:
         X11->time = event->xmotion.time;
         break;
     case XKeyPress:
         X11->userTime = event->xkey.time;
         // fallthrough intended
     case XKeyRelease:
         X11->time = event->xkey.time;
         break;
     case PropertyNotify:
         X11->time = event->xproperty.time;
         break;
     case EnterNotify:
     case LeaveNotify:
         X11->time = event->xcrossing.time;
         break;
     case SelectionClear:
         X11->time = event->xselectionclear.time;
         break;
     default:
         break;
     }
 #ifndef QT_NO_XFIXES
     if (X11->use_xfixes && event->type == (X11->xfixes_eventbase + XFixesSelectionNotify)) {
         XFixesSelectionNotifyEvent *req =
             reinterpret_cast<XFixesSelectionNotifyEvent *>(event);
         X11->time = req->selection_timestamp;
         if (req->selection == ATOM(_NET_WM_CM_S0))
             X11->compositingManagerRunning = req->owner;
     }
 #endif
     QETWidget *widget = (QETWidget*)QWidget::find((WId)event->xany.window);
     if (wPRmapper) {                                // just did a widget reparent?
         if (widget == 0) {                        // not in std widget mapper
             switch (event->type) {                // only for mouse/key events
             case ButtonPress:
             case ButtonRelease:
             case MotionNotify:
             case XKeyPress:
             case XKeyRelease:
                 widget = qPRFindWidget(event->xany.window);
                 break;
             }
         }
         else if (widget->testAttribute(Qt::WA_WState_Reparented))
             qPRCleanup(widget);                // remove from alt mapper
     }
     QETWidget *keywidget=0;
     bool grabbed=false;
     if (event->type==XKeyPress || event->type==XKeyRelease) {
         keywidget = (QETWidget*)QWidget::keyboardGrabber();
         if (keywidget) {
             grabbed = true;
         } else if (!keywidget) {
             if (d->inPopupMode()) // no focus widget, see if we have a popup
                 keywidget = (QETWidget*) (activePopupWidget()->focusWidget() ? activePopupWidget()->focusWidget() : activePopupWidget());
             else if (QApplicationPrivate::focus_widget)
                 keywidget = (QETWidget*)QApplicationPrivate::focus_widget;
             else if (widget)
                 keywidget = (QETWidget*)widget->window();
         }
     }
 #ifndef QT_NO_IM
     // Filtering input events by the input context. It has to be taken
     // place before any other key event consumers such as eventfilters
     // and accelerators because some input methods require quite
     // various key combination and sequences. It often conflicts with
     // accelerators and so on, so we must give the input context the
     // filtering opportunity first to ensure all input methods work
     // properly regardless of application design.
     if(keywidget && keywidget->isEnabled() && keywidget->testAttribute(Qt::WA_InputMethodEnabled)) {
         // block user interaction during session management
     if((event->type==XKeyPress || event->type==XKeyRelease) && qt_sm_blockUserInput)
         return true;
         // for XIM handling
     QInputContext *qic = keywidget->inputContext();
     if(qic && qic->x11FilterEvent(keywidget, event))
         return true;
     // filterEvent() accepts QEvent *event rather than preexpanded
     // key event attribute values. This is intended to pass other
     // QInputEvent in future. Other non IM-related events should
     // not be forwarded to input contexts to prevent weird event
     // handling.
     if ((event->type == XKeyPress || event->type == XKeyRelease)) {
         int code = -1;
         int count = 0;
         Qt::KeyboardModifiers modifiers;
         QEvent::Type type;
         QString text;
             KeySym keySym;
             qt_keymapper_private()->translateKeyEventInternal(keywidget, event, keySym, count,
                                                               text, modifiers, code, type, false);
         // both key press/release is required for some complex
         // input methods. don't eliminate anything.
         QKeyEventEx keyevent(type, code, modifiers, text, false, qMax(qMax(count, 1), text.length()),
                                  event->xkey.keycode, keySym, event->xkey.state);
         if(qic && qic->filterEvent(&keyevent))
         return true;
     }
     } else
 #endif // QT_NO_IM
         {
             if (XFilterEvent(event, XNone))
                 return true;
         }
     if (qt_x11EventFilter(event))                // send through app filter
         return 1;
     if (event->type == MappingNotify) {
         // keyboard mapping changed
         XRefreshKeyboardMapping(&event->xmapping);
         QKeyMapper::changeKeyboard();
         return 0;
     }
 #ifndef QT_NO_XKB
     else if (X11->use_xkb && event->type == X11->xkb_eventbase) {
         XkbAnyEvent *xkbevent = (XkbAnyEvent *) event;
         switch (xkbevent->xkb_type) {
         case XkbStateNotify:
             {
                 XkbStateNotifyEvent *xkbstateevent = (XkbStateNotifyEvent *) xkbevent;
                 if ((xkbstateevent->changed & XkbGroupStateMask) != 0) {
                     qt_keymapper_private()->xkb_currentGroup = xkbstateevent->group;
                     QKeyMapper::changeKeyboard();
                 }
                 break;
             }
         default:
             break;
         }
     }
 #endif
     if (!widget) {                                // don't know this windows
         QWidget* popup = QApplication::activePopupWidget();
         if (popup) {
             /*
               That is more than suboptimal. The real solution should
               do some keyevent and buttonevent translation, so that
               the popup still continues to work as the user expects.
               Unfortunately this translation is currently only
               possible with a known widget. I'll change that soon
               (Matthias).
             */
             // Danger - make sure we don't lock the server
             switch (event->type) {
             case ButtonPress:
             case ButtonRelease:
             case XKeyPress:
             case XKeyRelease:
                 do {
                     popup->close();
                 } while ((popup = qApp->activePopupWidget()));
                 return 1;
             }
         }
         return -1;
     }
     if (event->type == XKeyPress || event->type == XKeyRelease)
         widget = keywidget; // send XKeyEvents through keywidget->x11Event()
     if (app_do_modal)                                // modal event handling
         if (!qt_try_modal(widget, event)) {
             if (event->type == ClientMessage && !widget->x11Event(event))
                 x11ClientMessage(widget, event, true);
             return 1;
         }
     if (widget->x11Event(event))                // send through widget filter
         return 1;
 #if !defined (QT_NO_TABLET)
     if (!qt_xdnd_dragging) {
         QTabletDeviceDataList *tablets = qt_tablet_devices();
         for (int i = 0; i < tablets->size(); ++i) {
             QTabletDeviceData &tab = tablets->operator [](i);
             if (event->type == tab.xinput_motion
             || event->type == tab.xinput_button_release
             || event->type == tab.xinput_button_press
             || event->type == tab.xinput_proximity_in
             || event->type == tab.xinput_proximity_out) {
                 widget->translateXinputEvent(event, &tab);
                 return 0;
             }
         }
     }
 #endif
 #ifndef QT_NO_XRANDR
     if (X11->use_xrandr && event->type == (X11->xrandr_eventbase + RRScreenChangeNotify)) {
         // update Xlib internals with the latest screen configuration
         X11->ptrXRRUpdateConfiguration(event);
         // update the size for desktop widget
         int scr = X11->ptrXRRRootToScreen(X11->display, event->xany.window);
         QDesktopWidget *desktop = QApplication::desktop();
         QWidget *w = desktop->screen(scr);
         QSize oldSize(w->size());
         w->data->crect.setWidth(DisplayWidth(X11->display, scr));
         w->data->crect.setHeight(DisplayHeight(X11->display, scr));
         QResizeEvent e(w->size(), oldSize);
         QApplication::sendEvent(w, &e);
         if (w != desktop)
             QApplication::sendEvent(desktop, &e);
     }
 #endif // QT_NO_XRANDR
 #ifndef QT_NO_XFIXES
     if (X11->use_xfixes && event->type == (X11->xfixes_eventbase + XFixesSelectionNotify)) {
         XFixesSelectionNotifyEvent *req = reinterpret_cast<XFixesSelectionNotifyEvent *>(event);
         // compress all XFixes events related to this selection
         // we don't want to handle old SelectionNotify events.
         qt_xfixes_selection_event_data xfixes_event;
         xfixes_event.selection = req->selection;
         for (XEvent ev;;) {
             if (!XCheckIfEvent(X11->display, &ev, &qt_xfixes_scanner, (XPointer)&xfixes_event))
                 break;
         }
         if (req->selection == ATOM(CLIPBOARD)) {
             if (qt_xfixes_clipboard_changed(req->owner, req->selection_timestamp)) {
                 emit clipboard()->changed(QClipboard::Clipboard);
                 emit clipboard()->dataChanged();
             }
         } else if (req->selection == XA_PRIMARY) {
             if (qt_xfixes_selection_changed(req->owner, req->selection_timestamp)) {
                 emit clipboard()->changed(QClipboard::Selection);
                 emit clipboard()->selectionChanged();
             }
         }
     }
 #endif // QT_NO_XFIXES
     switch (event->type) {
     case ButtonRelease:                        // mouse event
         if (!d->inPopupMode() && !QWidget::mouseGrabber() && pressed_window != widget->internalWinId()
             && (widget = (QETWidget*) QWidget::find((WId)pressed_window)) == 0)
             break;
         // fall through intended
     case ButtonPress:
         if (event->xbutton.root != RootWindow(X11->display, widget->x11Info().screen())
             && ! qt_xdnd_dragging) {
             while (activePopupWidget())
                 activePopupWidget()->close();
             return 1;
         }
         if (event->type == ButtonPress)
             qt_net_update_user_time(widget->window(), X11->userTime);
         // fall through intended
     case MotionNotify:
 #if !defined(QT_NO_TABLET)
         if (!qt_tabletChokeMouse) {
 #endif
             if (widget->testAttribute(Qt::WA_TransparentForMouseEvents)) {
                 QPoint pos(event->xbutton.x, event->xbutton.y);
                 pos = widget->d_func()->mapFromWS(pos);
                 QWidget *window = widget->window();
                 pos = widget->mapTo(window, pos);
                 if (QWidget *child = window->childAt(pos)) {
                     widget = static_cast<QETWidget *>(child);
                     pos = child->mapFrom(window, pos);
                     event->xbutton.x = pos.x();
                     event->xbutton.y = pos.y();
                 }
             }
             widget->translateMouseEvent(event);
 #if !defined(QT_NO_TABLET)
         } else {
             qt_tabletChokeMouse = false;
         }
 #endif
         break;
     case XKeyPress:                                // keyboard event
         qt_net_update_user_time(widget->window(), X11->userTime);
         // fallthrough intended
     case XKeyRelease:
         {
             if (keywidget && keywidget->isEnabled()) { // should always exist
                 // qDebug("sending key event");
                 qt_keymapper_private()->translateKeyEvent(keywidget, event, grabbed);
             }
             break;
         }
     case GraphicsExpose:
     case Expose:                                // paint event
         widget->translatePaintEvent(event);
         break;
     case ConfigureNotify:                        // window move/resize event
         if (event->xconfigure.event == event->xconfigure.window)
             widget->translateConfigEvent(event);
         break;
     case XFocusIn: {                                // got focus
         if ((widget->windowType() == Qt::Desktop))
             break;
         if (d->inPopupMode()) // some delayed focus event to ignore
             break;
         if (!widget->isWindow())
             break;
         if (event->xfocus.detail != NotifyAncestor &&
             event->xfocus.detail != NotifyInferior &&
             event->xfocus.detail != NotifyNonlinear)
             break;
         setActiveWindow(widget);
         if (X11->focus_model == QX11Data::FM_PointerRoot) {
             // We got real input focus from somewhere, but we were in PointerRoot
             // mode, so we don't trust this event.  Check the focus model to make
             // sure we know what focus mode we are using...
             qt_check_focus_model();
         }
     }
         break;
     case XFocusOut:                                // lost focus
         if ((widget->windowType() == Qt::Desktop))
             break;
         if (!widget->isWindow())
             break;
         if (event->xfocus.mode == NotifyGrab) {
             qt_xfocusout_grab_counter++;
             break;
         }
         if (event->xfocus.detail != NotifyAncestor &&
             event->xfocus.detail != NotifyNonlinearVirtual &&
             event->xfocus.detail != NotifyNonlinear)
             break;
         if (!d->inPopupMode() && widget == QApplicationPrivate::active_window) {
             XEvent ev;
             bool focus_will_change = false;
             if (XCheckTypedEvent(X11->display, XFocusIn, &ev)) {
                 // we're about to get an XFocusIn, if we know we will
                 // get a new active window, we don't want to set the
                 // active window to 0 now
                 QWidget *w2 = QWidget::find(ev.xany.window);
                 if (w2
                     && w2->windowType() != Qt::Desktop
                     && !d->inPopupMode() // some delayed focus event to ignore
                     && w2->isWindow()
                     && (ev.xfocus.detail == NotifyAncestor
                         || ev.xfocus.detail == NotifyInferior
                         || ev.xfocus.detail == NotifyNonlinear))
                     focus_will_change = true;
                 XPutBackEvent(X11->display, &ev);
             }
             if (!focus_will_change)
                 setActiveWindow(0);
         }
         break;
     case EnterNotify: {                        // enter window
         if (QWidget::mouseGrabber() && (!d->inPopupMode() || widget->window() != activePopupWidget()))
             break;
         if ((event->xcrossing.mode != NotifyNormal
              && event->xcrossing.mode != NotifyUngrab)
             || event->xcrossing.detail == NotifyVirtual
             || event->xcrossing.detail == NotifyNonlinearVirtual)
             break;
         if (event->xcrossing.focus &&
             !(widget->windowType() == Qt::Desktop) && !widget->isActiveWindow()) {
             if (X11->focus_model == QX11Data::FM_Unknown) // check focus model
                 qt_check_focus_model();
             if (X11->focus_model == QX11Data::FM_PointerRoot) // PointerRoot mode
                 setActiveWindow(widget);
         }
         if (qt_button_down && !d->inPopupMode())
             break;
         QWidget *alien = widget->childAt(widget->d_func()->mapFromWS(QPoint(event->xcrossing.x,
                                                                             event->xcrossing.y)));
         QWidget *enter = alien ? alien : widget;
         QWidget *leave = 0;
         if (qt_last_mouse_receiver && !qt_last_mouse_receiver->internalWinId())
             leave = qt_last_mouse_receiver;
         else
             leave = QWidget::find(curWin);
         // ### Alien: enter/leave might be wrong here with overlapping siblings
         // if the enter widget is native and stacked under a non-native widget.
         QApplicationPrivate::dispatchEnterLeave(enter, leave);
         curWin = widget->internalWinId();
         qt_last_mouse_receiver = enter;
         if (!d->inPopupMode() || widget->window() == activePopupWidget())
             widget->translateMouseEvent(event); //we don't get MotionNotify, emulate it
     }
         break;
     case LeaveNotify: {                        // leave window
         QWidget *mouseGrabber = QWidget::mouseGrabber();
         if (mouseGrabber && !d->inPopupMode())
             break;
         if (curWin && widget->internalWinId() != curWin)
             break;
         if ((event->xcrossing.mode != NotifyNormal
             && event->xcrossing.mode != NotifyUngrab)
             || event->xcrossing.detail == NotifyInferior)
             break;
         if (!(widget->windowType() == Qt::Desktop))
             widget->translateMouseEvent(event); //we don't get MotionNotify, emulate it
         QWidget* enter = 0;
         QPoint enterPoint;
         XEvent ev;
         while (XCheckMaskEvent(X11->display, EnterWindowMask | LeaveWindowMask , &ev)
                && !qt_x11EventFilter(&ev)) {
             QWidget* event_widget = QWidget::find(ev.xcrossing.window);
             if(event_widget && event_widget->x11Event(&ev))
                 break;
             if (ev.type == LeaveNotify
                 || (ev.xcrossing.mode != NotifyNormal
                     && ev.xcrossing.mode != NotifyUngrab)
                 || ev.xcrossing.detail == NotifyVirtual
                 || ev.xcrossing.detail == NotifyNonlinearVirtual)
                 continue;
             enter = event_widget;
             if (enter)
                 enterPoint = enter->d_func()->mapFromWS(QPoint(ev.xcrossing.x, ev.xcrossing.y));
             if (ev.xcrossing.focus &&
                 enter && !(enter->windowType() == Qt::Desktop) && !enter->isActiveWindow()) {
                 if (X11->focus_model == QX11Data::FM_Unknown) // check focus model
                     qt_check_focus_model();
                 if (X11->focus_model == QX11Data::FM_PointerRoot) // PointerRoot mode
                     setActiveWindow(enter);
             }
             break;
         }
         if ((! enter || (enter->windowType() == Qt::Desktop)) &&
             event->xcrossing.focus && widget == QApplicationPrivate::active_window &&
             X11->focus_model == QX11Data::FM_PointerRoot // PointerRoot mode
             ) {
             setActiveWindow(0);
         }
         if (qt_button_down && !d->inPopupMode())
             break;
         if (!curWin)
             QApplicationPrivate::dispatchEnterLeave(widget, 0);
         if (enter) {
             QWidget *alienEnter = enter->childAt(enterPoint);
             if (alienEnter)
                 enter = alienEnter;
         }
         QWidget *leave = qt_last_mouse_receiver ? qt_last_mouse_receiver : widget;
         QWidget *activePopupWidget = qApp->activePopupWidget();
         if (mouseGrabber && activePopupWidget && leave == activePopupWidget)
             enter = mouseGrabber;
         else if (enter != widget && mouseGrabber) {
             if (!widget->rect().contains(widget->d_func()->mapFromWS(QPoint(event->xcrossing.x,
                                                                             event->xcrossing.y))))
                 break;
         }
         QApplicationPrivate::dispatchEnterLeave(enter, leave);
         qt_last_mouse_receiver = enter;
         if (enter && QApplicationPrivate::tryModalHelper(enter, 0)) {
             QWidget *nativeEnter = enter->internalWinId() ? enter : enter->nativeParentWidget();
             curWin = nativeEnter->internalWinId();
             static_cast<QETWidget *>(nativeEnter)->translateMouseEvent(&ev); //we don't get MotionNotify, emulate it
         } else {
             curWin = 0;
             qt_last_mouse_receiver = 0;
         }
     }
         break;
     case UnmapNotify:                                // window hidden
         if (widget->isWindow()) {
             Q_ASSERT(widget->testAttribute(Qt::WA_WState_Created));
             widget->d_func()->topData()->waitingForMapNotify = 0;
             if (widget->windowType() != Qt::Popup && !widget->testAttribute(Qt::WA_DontShowOnScreen)) {
                 widget->setAttribute(Qt::WA_Mapped, false);
                 if (widget->isVisible()) {
                     widget->d_func()->topData()->spont_unmapped = 1;
                     QHideEvent e;
                     QApplication::sendSpontaneousEvent(widget, &e);
                     widget->d_func()->hideChildren(true);
                 }
             }
             if (!widget->d_func()->topData()->validWMState && X11->deferred_map.removeAll(widget))
                 widget->doDeferredMap();
         }
         break;
     case MapNotify:                                // window shown
         if (widget->isWindow()) {
             // if we got a MapNotify when we were not waiting for it, it most
             // likely means the user has already asked to hide the window before
             // it ever being shown, so we try to withdraw a window after sending
             // the QShowEvent.
             bool pendingHide = widget->testAttribute(Qt::WA_WState_ExplicitShowHide) && widget->testAttribute(Qt::WA_WState_Hidden);
             widget->d_func()->topData()->waitingForMapNotify = 0;
             if (widget->windowType() != Qt::Popup) {
                 widget->setAttribute(Qt::WA_Mapped);
                 if (widget->d_func()->topData()->spont_unmapped) {
                     widget->d_func()->topData()->spont_unmapped = 0;
                     widget->d_func()->showChildren(true);
                     QShowEvent e;
                     QApplication::sendSpontaneousEvent(widget, &e);
                     // show() must have been called on this widget in
                     // order to reach this point, but we could have
                     // cleared these 2 attributes in case something
                     // previously forced us into WithdrawnState
                     // (e.g. kdocker)
                     widget->setAttribute(Qt::WA_WState_ExplicitShowHide, true);
                     widget->setAttribute(Qt::WA_WState_Visible, true);
                 }
             }
             if (pendingHide) // hide the window
                 XWithdrawWindow(X11->display, widget->internalWinId(), widget->x11Info().screen());
         }
         break;
     case ClientMessage:                        // client message
         return x11ClientMessage(widget,event,False);
     case ReparentNotify: {                      // window manager reparents
         // compress old reparent events to self
         XEvent ev;
         while (XCheckTypedWindowEvent(X11->display,
                                       widget->effectiveWinId(),
                                       ReparentNotify,
                                       &ev)) {
             if (ev.xreparent.window != ev.xreparent.event) {
                 XPutBackEvent(X11->display, &ev);
                 break;
             }
         }
         if (widget->isWindow()) {
             QTLWExtra *topData = widget->d_func()->topData();
             // store the parent. Useful for many things, embedding for instance.
             topData->parentWinId = event->xreparent.parent;
             // the widget frame strut should also be invalidated
             widget->data->fstrut_dirty = 1;
             // work around broken window managers... if we get a
             // ReparentNotify before the MapNotify, we assume that
             // we're being managed by a reparenting window
             // manager.
             //
             // however, the WM_STATE property may not have been set
             // yet, but we are going to assume that it will
             // be... otherwise we could try to map again after getting
             // an UnmapNotify... which could then, in turn, trigger a
             // race in the window manager which causes the window to
             // disappear when it really should be hidden.
             if (topData->waitingForMapNotify && !topData->validWMState) {
                 topData->waitingForMapNotify = 0;
                 topData->validWMState = 1;
             }
             if (X11->focus_model != QX11Data::FM_Unknown) {
                 // toplevel reparented...
                 QWidget *newparent = QWidget::find(event->xreparent.parent);
                 if (! newparent || (newparent->windowType() == Qt::Desktop)) {
                     // we don't know about the new parent (or we've been
                     // reparented to root), perhaps a window manager
                     // has been (re)started?  reset the focus model to unknown
                     X11->focus_model = QX11Data::FM_Unknown;
                 }
             }
         }
         break;
     }
     case SelectionRequest: {
         XSelectionRequestEvent *req = &event->xselectionrequest;
         if (! req)
             break;
         if (ATOM(XdndSelection) && req->selection == ATOM(XdndSelection)) {
             X11->xdndHandleSelectionRequest(req);
         } else if (qt_clipboard) {
             QClipboardEvent e(reinterpret_cast<QEventPrivate*>(event));
             QApplication::sendSpontaneousEvent(qt_clipboard, &e);
         }
         break;
     }
     case SelectionClear: {
         XSelectionClearEvent *req = &event->xselectionclear;
         // don't deliver dnd events to the clipboard, it gets confused
         if (! req || (ATOM(XdndSelection) && req->selection == ATOM(XdndSelection)))
             break;
         if (qt_clipboard && !X11->use_xfixes) {
             QClipboardEvent e(reinterpret_cast<QEventPrivate*>(event));
             QApplication::sendSpontaneousEvent(qt_clipboard, &e);
         }
         break;
     }
     case SelectionNotify: {
         XSelectionEvent *req = &event->xselection;
         // don't deliver dnd events to the clipboard, it gets confused
         if (! req || (ATOM(XdndSelection) && req->selection == ATOM(XdndSelection)))
             break;
         if (qt_clipboard) {
             QClipboardEvent e(reinterpret_cast<QEventPrivate*>(event));
             QApplication::sendSpontaneousEvent(qt_clipboard, &e);
         }
         break;
     }
     case PropertyNotify:
         // some properties changed
         if (event->xproperty.window == QX11Info::appRootWindow(0)) {
             // root properties for the first screen
             if (!X11->use_xfixes && event->xproperty.atom == ATOM(_QT_CLIPBOARD_SENTINEL)) {
                 if (qt_check_clipboard_sentinel()) {
                     emit clipboard()->changed(QClipboard::Clipboard);
                     emit clipboard()->dataChanged();
                 }
             } else if (!X11->use_xfixes && event->xproperty.atom == ATOM(_QT_SELECTION_SENTINEL)) {
                 if (qt_check_selection_sentinel()) {
                     emit clipboard()->changed(QClipboard::Selection);
                     emit clipboard()->selectionChanged();
                 }
             } else if (QApplicationPrivate::obey_desktop_settings) {
                 if (event->xproperty.atom == ATOM(RESOURCE_MANAGER))
                     qt_set_x11_resources();
                 else if (event->xproperty.atom == ATOM(_QT_SETTINGS_TIMESTAMP))
                     qt_set_x11_resources();
             }
         }
         if (event->xproperty.window == QX11Info::appRootWindow()) {
             // root properties for the default screen
             if (event->xproperty.atom == ATOM(_QT_INPUT_ENCODING)) {
                 qt_set_input_encoding();
             } else if (event->xproperty.atom == ATOM(_NET_SUPPORTED)) {
                 qt_get_net_supported();
             } else if (event->xproperty.atom == ATOM(_NET_VIRTUAL_ROOTS)) {
                 qt_get_net_virtual_roots();
             } else if (event->xproperty.atom == ATOM(_NET_WORKAREA)) {
                 qt_desktopwidget_update_workarea();
                 // emit the workAreaResized() signal
                 QDesktopWidget *desktop = QApplication::desktop();
                 int numScreens = desktop->numScreens();
                 for (int i = 0; i < numScreens; ++i)
                     emit desktop->workAreaResized(i);
             }
         } else if (widget) {
             widget->translatePropertyEvent(event);
         }  else {
             return -1; // don't know this window
         }
         break;
     default:
         break;
     }
     return 0;
 }
Friends and Related Functions
Q3AccelManager
friend class Q3AccelManager friend
Definition at line 401 of file qapplication.h.
QAction
friend class QAction friend
Definition at line 409 of file qapplication.h.
QDirectPainter
friend class QDirectPainter friend
Definition at line 415 of file qapplication.h.
QDirectPainterPrivate
friend class QDirectPainterPrivate friend
Definition at line 416 of file qapplication.h.
QETWidget
friend class QETWidget friend
Definition at line 400 of file qapplication.h.
QFontDatabasePrivate
friend class QFontDatabasePrivate friend
Definition at line 410 of file qapplication.h.
QGestureManager
friend class QGestureManager friend
Definition at line 419 of file qapplication.h.
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 395 of file qapplication.h.
QGraphicsScene
friend class QGraphicsScene friend
Definition at line 396 of file qapplication.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 397 of file qapplication.h.
QGraphicsWidget
friend class QGraphicsWidget friend
Definition at line 394 of file qapplication.h.
QInputContext
friend class QInputContext friend
Definition at line 413 of file qapplication.h.
QLineEdit
friend class QLineEdit friend
Definition at line 406 of file qapplication.h.
QShortcut
friend class QShortcut friend
Definition at line 405 of file qapplication.h.
QTextControl
friend class QTextControl friend
Definition at line 407 of file qapplication.h.
QTranslator
friend class QTranslator friend
Definition at line 402 of file qapplication.h.
QWidget
friend class QWidget friend
Definition at line 398 of file qapplication.h.
QWidgetAnimator
friend class QWidgetAnimator friend
Definition at line 403 of file qapplication.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 399 of file qapplication.h.
QWSDirectPainterSurface
friend class QWSDirectPainterSurface friend
Definition at line 414 of file qapplication.h.
Properties
autoMaximizeThreshold
int QApplication::autoMaximizeThreshold private
defines a threshold for auto maximizing widgets
Since
4.4
The auto maximize threshold is only available as part of Qt for Windows CE.
This property defines a threshold for the size of a window as a percentage of the screen size. If the minimum size hint of a window exceeds the threshold, calling show() will cause the window to be maximized automatically.
Setting the threshold to 100 or greater means that the widget will always be maximized. Alternatively, setting the threshold to 50 means that the widget will be maximized only if the vertical minimum size hint is at least 50% of the vertical screen size.
Setting the threshold to -1 disables the feature.
On Windows CE the default is -1 (i.e., it is disabled). On Windows Mobile the default is 40.
Definition at line 118 of file qapplication.h.
autoSipEnabled
bool QApplication::autoSipEnabled private
toggles automatic SIP (software input panel) visibility
Since
4.5
Set this property to true to automatically display the SIP when entering widgets that accept keyboard input. This property only affects widgets with the WA_InputMethodEnabled attribute set, and is typically used to launch a virtual keyboard on devices which have very few or no keys.
The property only has an effect on platforms which use software input panels, such as Windows CE and Symbian.
The default is platform dependent.
Definition at line 120 of file qapplication.h.
cursorFlashTime
int QApplication::cursorFlashTime private
the text cursor's flash (blink) time in milliseconds
The flash time is the time required to display, invert and restore the caret display. Usually the text cursor is displayed for half the cursor flash time, then hidden for the same amount of time, but this may vary.
The default value on X11 is 1000 milliseconds. On Windows, the Control Panel value is used and setting this property sets the cursor flash time for all applications.
We recommend that widgets do not cache this value as it may change at any time if the user changes the global desktop settings.
Definition at line 104 of file qapplication.h.
doubleClickInterval
int QApplication::doubleClickInterval private
the time limit in milliseconds that distinguishes a double click from two consecutive mouse clicks
The default value on X11 is 400 milliseconds. On Windows and Mac OS, the operating system's value is used. However, on Windows and Symbian OS, calling this function sets the double click interval for all applications.
Definition at line 105 of file qapplication.h.
globalStrut
QSize QApplication::globalStrut private
the minimum size that any GUI element that the user can interact with should have
For example, no button should be resized to be smaller than the global strut size. The strut size should be considered when reimplementing GUI controls that may be used on touch-screens or similar I/O devices.
Example:
QSize MyWidget::sizeHint() const
{
    return QSize(80, 25).expandedTo(QApplication::globalStrut());
}
By default, this property contains a QSize object with zero width and height.
Definition at line 110 of file qapplication.h.
keyboardInputInterval
int QApplication::keyboardInputInterval private
the time limit in milliseconds that distinguishes a key press from two consecutive key presses
Since
4.2
The default value on X11 is 400 milliseconds. On Windows and Mac OS, the operating system's value is used.
Definition at line 106 of file qapplication.h.
layoutDirection
Qt::LayoutDirection QApplication::layoutDirection private
the default layout direction for this application
On system start-up, the default layout direction depends on the application's language.
See also
QWidget::layoutDirection, isLeftToRight(), isRightToLeft()
Definition at line 102 of file qapplication.h.
quitOnLastWindowClosed
bool QApplication::quitOnLastWindowClosed private
whether the application implicitly quits when the last window is closed.
The default is true.
If this property is true, the applications quits when the last visible primary window (i.e. window with no parent) with the Qt::WA_QuitOnClose attribute set is closed. By default this attribute is set for all widgets except for sub-windows. Refer to Qt::WindowType for a detailed list of Qt::Window objects.
See also
quit(), QWidget::close()
Definition at line 113 of file qapplication.h.
startDragDistance
int QApplication::startDragDistance private
If you support drag and drop in your application, and want to start a drag and drop operation after the user has moved the cursor a certain distance with a button held down, you should use this property's value as the minimum distance required.
For example, if the mouse position of the click is stored in startPos and the current position (e.g. in the mouse move event) is currentPos, you can find out if a drag should be started with code like this:
if ((startPos - currentPos).manhattanLength() >=
        QApplication::startDragDistance())
    startTheDrag();
Qt uses this value internally, e.g. in QFileDialog.
The default value is 4 pixels.
See also
startDragTime() QPoint::manhattanLength() {Drag and Drop}
Definition at line 112 of file qapplication.h.
startDragTime
int QApplication::startDragTime private
the time in milliseconds that a mouse button must be held down before a drag and drop operation will begin
If you support drag and drop in your application, and want to start a drag and drop operation after the user has held down a mouse button for a certain amount of time, you should use this property's value as the delay.
Qt also uses this delay internally, e.g. in QTextEdit and QLineEdit, for starting a drag.
The default value is 500 ms.
See also
startDragDistance(), {Drag and Drop}
Definition at line 111 of file qapplication.h.
styleSheet
QString QApplication::styleSheet private
the application style sheet
Since
4.2
By default, this property returns an empty string unless the user specifies the -stylesheet option on the command line when running the application.
See also
QWidget::setStyle(), {Qt Style Sheets}
Definition at line 115 of file qapplication.h.
wheelScrollLines
int QApplication::wheelScrollLines private
the number of lines to scroll a widget, when the mouse wheel is rotated.
If the value exceeds the widget's number of visible lines, the widget should interpret the scroll operation as a single page up or page down. If the widget is an item view class, then the result of scrolling one line depends on the setting of the widget's scroll mode. Scroll one line can mean scroll one item or scroll one pixel.
By default, this property has a value of 3.
Definition at line 108 of file qapplication.h.
windowIcon
QIcon QApplication::windowIcon private
the default window icon
See also
QWidget::setWindowIcon(), {Setting the Application Icon}
Definition at line 103 of file qapplication.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qapplication.h
/src/gui/kernel/qapplication.cpp
/src/gui/kernel/qapplication_mac.mm
/src/gui/kernel/qapplication_qpa.cpp
/src/gui/kernel/qapplication_qws.cpp
/src/gui/kernel/qapplication_win.cpp
/src/gui/kernel/qapplication_x11.cpp