Qt 4.8: QBBInputContext Class Reference
QBBInputContext Class Reference
#include <qbbinputcontext_imf.h>
Public Functions
virtual QList< QAction * > actions ()
This is a preliminary interface for Qt 4.
virtual bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
virtual bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
virtual QFont font () const
Returns the font of the current input widget.
bool handleKeyboardEvent (int flags, int sym, int mod, int scan, int cap)
bool handleKeyboardEvent (int flags, int sym, int mod, int scan, int cap)
QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
virtual QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
virtual bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
QString language ()
This function must be implemented in any subclasses to return a language code (e.
virtual QString language ()
This function must be implemented in any subclasses to return a language code (e.
virtual void mouseHandler (int x, QMouseEvent *event)
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
QBBInputContext (QBBAbstractVirtualKeyboard &keyboard, QObject *parent=0)
QBBInputContext (QBBAbstractVirtualKeyboard &keyboard, QObject *parent=0)
void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
virtual void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
void setFocusWidget (QWidget *w)
Sets the widget that has an input focus for this input context.
virtual void setFocusWidget (QWidget *widget)
Sets the widget that has an input focus for this input context.
virtual void update ()
This virtual function is called when a state in the focus widget has changed.
virtual void widgetDestroyed (QWidget *widget)
This virtual function is called when the specified widget is destroyed.
~QBBInputContext ()
~QBBInputContext ()
Public Functions inherited from QInputContext
QWidget * focusWidget () const
Returns the widget that has an input focus for this input context.
QInputContext (QObject *parent=0)
Constructs an input context with the given parent.
void sendEvent (const QInputMethodEvent &event)
Sends an input method event specified by event to the current focus widget.
QTextFormat standardFormat (StandardFormat s) const
Returns a QTextFormat object that specifies the format for component s.
virtual bool x11FilterEvent (QWidget *keywidget, XEvent *event)
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
virtual ~QInputContext ()
Destroys the input context.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool eventFilter (QObject *obj, QEvent *event)
Filters events if this object has been installed as an event filter for the watched object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void closeSession ()
bool dispatchCloseSoftwareInputPanel ()
bool dispatchFocusEvent (FocusEventId id, int hints=Qt::ImhNone)
bool dispatchRequestSoftwareInputPanel ()
void endComposition ()
bool hasPhysicalKeyboard ()
bool hasSelectedText ()
bool hasSession ()
int32_t onBeginBatchEdit (input_session_t *ic)
int32_t onClearMetaKeyStates (input_session_t *ic, int32_t states)
int32_t onCommitText (input_session_t *ic, spannable_string_t *text, int32_t new_cursor_position)
int32_t onDeleteSurroundingText (input_session_t *ic, int32_t left_length, int32_t right_length)
int32_t onEndBatchEdit (input_session_t *ic)
int32_t onFinishComposingText (input_session_t *ic)
int32_t onForceUpdate ()
int32_t onGetCursorCapsMode (input_session_t *ic, int32_t req_modes)
int32_t onGetCursorPosition (input_session_t *ic)
extracted_text_t * onGetExtractedText (input_session_t *ic, extracted_text_request_t *request, int32_t flags)
spannable_string_t * onGetSelectedText (input_session_t *ic, int32_t flags)
spannable_string_t * onGetTextAfterCursor (input_session_t *ic, int32_t n, int32_t flags)
spannable_string_t * onGetTextBeforeCursor (input_session_t *ic, int32_t n, int32_t flags)
int32_t onPerformEditorAction (input_session_t *ic, int32_t editor_action)
int32_t onReportFullscreenMode (input_session_t *ic, int32_t enabled)
int32_t onSendAsyncEvent (input_session_t *ic, event_t *event)
int32_t onSendEvent (input_session_t *ic, event_t *event)
int32_t onSetComposingRegion (input_session_t *ic, int32_t start, int32_t end)
int32_t onSetComposingText (input_session_t *ic, spannable_string_t *text, int32_t new_cursor_position)
int32_t onSetSelection (input_session_t *ic, int32_t start, int32_t end)
void openSession ()
int32_t processEvent (event_t *event)
void setComposingText (QString const &composingText)
Properties
QString mComposingText
bool mIsComposing
int mLastCaretPos
QBBAbstractVirtualKeyboard & mVirtualKeyboard
Additional Inherited Members
Public Types inherited from QInputContext
enum StandardFormat { PreeditFormat, SelectionFormat }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 55 of file qbbinputcontext_imf.h.
Constructors and Destructors
QBBInputContext() [1/2]
QBBInputContext::QBBInputContext (QBBAbstractVirtualKeyboard & keyboard, QObject * parent = 0) explicit
Definition at line 683 of file qbbinputcontext_imf.cpp.
                                                                                      :
          QInputContext(parent),
          mLastCaretPos(0),
          mIsComposing(false),
          mVirtualKeyboard(keyboard)
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!imfAvailable())
         return;
    if ( p_imf_client_init() != 0 ) {
         s_imfInitFailed = true;
         qCritical("imf_client_init failed - IMF services will be unavailable");
     }
     QCoreApplication::instance()->installEventFilter(this);
     // p_vkb_init_selection_service();
 }
~QBBInputContext() [1/2]
QBBInputContext::~QBBInputContext ()
Definition at line 706 of file qbbinputcontext_imf.cpp.
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!imfAvailable())
         return;
     QCoreApplication::instance()->removeEventFilter(this);
     p_imf_client_disconnect();
 }
QBBInputContext() [2/2]
QBBInputContext::QBBInputContext (QBBAbstractVirtualKeyboard & keyboard, QObject * parent = 0) explicit
~QBBInputContext() [2/2]
QBBInputContext::~QBBInputContext ()
Functions
actions()
QList< QAction * > QBBInputContext::actions () virtual
This is a preliminary interface for Qt 4.
Reimplemented from QInputContext.
Definition at line 919 of file qbbinputcontext_imf.cpp.
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     return QInputContext::actions();
 }
closeSession()
void QBBInputContext::closeSession () private
Definition at line 1006 of file qbbinputcontext_imf.cpp.
Referenced by openSession(), and setFocusWidget().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;;
 #endif
     if (!imfAvailable())
         return;
     if (sInputSession) {
         p_ictrl_close_session((input_session_t *)sInputSession);
         sInputSession = 0;
     }
 }
dispatchCloseSoftwareInputPanel()
bool QBBInputContext::dispatchCloseSoftwareInputPanel () private
Definition at line 1071 of file qbbinputcontext_imf.cpp.
Referenced by filterEvent().
 {
     mVirtualKeyboard.hideKeyboard();
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << "QBB: hiding virtual keyboard";
 #endif
     // This also means we are stopping composition, but we should already have done that.
     return true;
 }
dispatchFocusEvent()
bool QBBInputContext::dispatchFocusEvent (FocusEventId id, int hints = Qt::ImhNone) private
Definition at line 1085 of file qbbinputcontext_imf.cpp.
Referenced by setFocusWidget().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!sInputSession) {
         qWarning() << TAG << "Attempt to dispatch a focus event with no input session.";
         return false;
     }
     if (!imfAvailable())
         return false;
     // Set the last caret position to 0 since we don't really have one and we don't
     // want to have the old one.
     mLastCaretPos = 0;
     focus_event_t focusEvent;
     memset(&focusEvent, 0, sizeof(focusEvent));
     initEvent(&focusEvent.event, sInputSession, EVENT_FOCUS, id);
     focusEvent.style = DEFAULT_STYLE;
     if (hints && Qt::ImhNoPredictiveText)
         focusEvent.style |= NO_PREDICTION | NO_AUTO_CORRECTION;
     if (hints && Qt::ImhNoAutoUppercase)
         focusEvent.style |= NO_AUTO_TEXT;
     p_ictrl_dispatch_event((event_t *)&focusEvent);
     return true;
 }
dispatchRequestSoftwareInputPanel()
bool QBBInputContext::dispatchRequestSoftwareInputPanel () private
Definition at line 1050 of file qbbinputcontext_imf.cpp.
Referenced by filterEvent().
 {
     mVirtualKeyboard.showKeyboard();
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << "QBB: requesting virtual keyboard";
 #endif
     if (!imfAvailable() || !focusWidget())
         return true;
     // This also means that the caret position has moved
     int caretPos = focusWidget()->inputMethodQuery(Qt::ImCursorPosition).toInt();
     caret_event_t caretEvent;
     memset(&caretEvent, 0, sizeof(caret_event_t));
     initEvent(&caretEvent.event, sInputSession, EVENT_CARET, CARET_POS_CHANGED);
     caretEvent.old_pos = mLastCaretPos;
     mLastCaretPos = caretEvent.new_pos = caretPos;
     p_ictrl_dispatch_event((event_t *)&caretEvent);
     return true;
 }
endComposition()
void QBBInputContext::endComposition () private
Definition at line 1220 of file qbbinputcontext_imf.cpp.
Referenced by reset(), and setFocusWidget().
 {
     if (!imfAvailable())
         return;
     if (!isComposing())
         return;
     QList<QInputMethodEvent::Attribute> attributes;
     QInputMethodEvent event(QLatin1String(""), attributes);
     event.setCommitString(mComposingText);
     mComposingText = QString();
     mIsComposing = false;
     sendEvent(event);
     action_event_t actionEvent;
     memset(&actionEvent, 0, sizeof(actionEvent));
     initEvent(&actionEvent.event, sInputSession, EVENT_ACTION, ACTION_END_COMPOSITION);
     p_ictrl_dispatch_event(&actionEvent.event);
 }
eventFilter()
bool QBBInputContext::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 722 of file qbbinputcontext_imf.cpp.
 {
     if (event->type() == ImfEvent::sUserEventType) {
         // Forward the event to our real handler.
         ImfEvent* imfEvent = static_cast<ImfEvent*>(event);
         switch (imfEvent->mImfType) {
         case ImfBeginBatchEdit:
         {
             int32_t ret = onBeginBatchEdit(imfEvent->mSession);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfClearMetaKeyStates:
         {
             getarg(int32_t, states);
             int32_t ret = onClearMetaKeyStates(imfEvent->mSession, states);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfCommitText:
         {
             getparg(spannable_string_t*, text);
             getarg(int32_t, new_cursor_position);
             int32_t ret = onCommitText(imfEvent->mSession, text, new_cursor_position);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfDeleteSurroundingText:
         {
             getarg(int32_t, left_length);
             getarg(int32_t, right_length);
             int32_t ret = onDeleteSurroundingText(imfEvent->mSession, left_length, right_length);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfEndBatchEdit:
         {
             int32_t ret = onEndBatchEdit(imfEvent->mSession);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfFinishComposingText:
         {
             int32_t ret = onFinishComposingText(imfEvent->mSession);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfGetCursorCapsMode:
         {
             getarg(int32_t, req_modes);
             int32_t ret = onGetCursorCapsMode(imfEvent->mSession, req_modes);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfGetCursorPosition:
         {
             int32_t ret = onGetCursorPosition(imfEvent->mSession);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfGetExtractedText:
         {
             getparg(extracted_text_request_t*, request);
             getarg(int32_t, flags);
             extracted_text_t* ret = onGetExtractedText(imfEvent->mSession, request, flags);
             imfEvent->mResult->setResult(QVariant::fromValue((void*)ret));
             break;
         }
         case ImfGetSelectedText:
         {
             getarg(int32_t, flags);
             spannable_string_t* ret = onGetSelectedText(imfEvent->mSession, flags);
             imfEvent->mResult->setResult(QVariant::fromValue((void*)ret));
             break;
         }
         case ImfGetTextAfterCursor:
         {
             getarg(int32_t, n);
             getarg(int32_t, flags);
             spannable_string_t* ret = onGetTextAfterCursor(imfEvent->mSession, n, flags);
             imfEvent->mResult->setResult(QVariant::fromValue((void*)ret));
             break;
         }
         case ImfGetTextBeforeCursor:
         {
             getarg(int32_t, n);
             getarg(int32_t, flags);
             spannable_string_t* ret = onGetTextBeforeCursor(imfEvent->mSession, n, flags);
             imfEvent->mResult->setResult(QVariant::fromValue((void*)ret));
             break;
         }
         case ImfPerformEditorAction:
         {
             getarg(int32_t, editor_action);
             int32_t ret = onPerformEditorAction(imfEvent->mSession, editor_action);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfReportFullscreenMode:
         {
             getarg(int32_t, enabled);
             int32_t ret = onReportFullscreenMode(imfEvent->mSession, enabled);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfSendEvent:
         {
             getparg(event_t*, event);
             onSendEvent(imfEvent->mSession, event);
             break;
         }
         case ImfSendAsyncEvent:
         {
             getparg(event_t*, event);
             onSendAsyncEvent(imfEvent->mSession, event);
             break;
         }
         case ImfSetComposingRegion:
         {
             getarg(int32_t, start);
             getarg(int32_t, end);
             int32_t ret = onSetComposingRegion(imfEvent->mSession, start, end);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfSetComposingText:
         {
             getparg(spannable_string_t*, text);
             getarg(int32_t, new_cursor_position);
             int32_t ret = onSetComposingText(imfEvent->mSession, text, new_cursor_position);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         case ImfSetSelection:
         {
             getarg(int32_t, start);
             getarg(int32_t, end);
             int32_t ret = onSetSelection(imfEvent->mSession, start, end);
             imfEvent->mResult->setResult(QVariant::fromValue(ret));
             break;
         }
         }; //switch
         return true;
     } else {
         // standard event processing
         return QObject::eventFilter(obj, event);
     }
 }
filterEvent() [1/2]
bool QBBInputContext::filterEvent (const QEvent * event) virtual
This function can be reimplemented in a subclass to filter input events.
Return true if the event has been consumed. Otherwise, the unfiltered event will be forwarded to widgets as ordinary way. Although the input events have accept() and ignore() methods, leave it untouched.
event is currently restricted to events of these types:
CloseSoftwareInputPanel
KeyPress
KeyRelease
MouseButtonDblClick
MouseButtonPress
MouseButtonRelease
MouseMove
RequestSoftwareInputPanel
But some input method related events such as QWheelEvent or QTabletEvent may be added in future.
The filtering opportunity is always given to the input context as soon as possible. It has to be taken place before any other key event consumers such as eventfilters and accelerators because some input methods require quite various key combination and sequences. It often conflicts with accelerators and so on, so we must give the input context the filtering opportunity first to ensure all input methods work properly regardless of application design.
Ordinary input methods require discrete key events to work properly, so Qt's key compression is always disabled for any input contexts.
See also
QKeyEvent, x11FilterEvent()
Reimplemented from QInputContext.
Definition at line 901 of file qbbinputcontext_imf.cpp.
Referenced by hasPhysicalKeyboard(), and isComposing().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG << event;
 #endif
     switch (event->type()) {
     case QEvent::CloseSoftwareInputPanel: {
         return dispatchCloseSoftwareInputPanel();
     }
     case QEvent::RequestSoftwareInputPanel: {
         return dispatchRequestSoftwareInputPanel();
     }
     default:
         return false;
     }
 }
filterEvent() [2/2]
virtual bool QBBInputContext::filterEvent (const QEvent * event) virtual
This function can be reimplemented in a subclass to filter input events.
Return true if the event has been consumed. Otherwise, the unfiltered event will be forwarded to widgets as ordinary way. Although the input events have accept() and ignore() methods, leave it untouched.
event is currently restricted to events of these types:
CloseSoftwareInputPanel
KeyPress
KeyRelease
MouseButtonDblClick
MouseButtonPress
MouseButtonRelease
MouseMove
RequestSoftwareInputPanel
But some input method related events such as QWheelEvent or QTabletEvent may be added in future.
The filtering opportunity is always given to the input context as soon as possible. It has to be taken place before any other key event consumers such as eventfilters and accelerators because some input methods require quite various key combination and sequences. It often conflicts with accelerators and so on, so we must give the input context the filtering opportunity first to ensure all input methods work properly regardless of application design.
Ordinary input methods require discrete key events to work properly, so Qt's key compression is always disabled for any input contexts.
See also
QKeyEvent, x11FilterEvent()
Reimplemented from QInputContext.
font()
QFont QBBInputContext::font () const virtual
Returns the font of the current input widget.
Reimplemented from QInputContext.
Definition at line 927 of file qbbinputcontext_imf.cpp.
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     return QInputContext::font();
 }
handleKeyboardEvent() [1/2]
bool QBBInputContext::handleKeyboardEvent (int flags, int sym, int mod, int scan, int cap)
handleKeyboardEvent() [2/2]
bool QBBInputContext::handleKeyboardEvent (int flags, int sym, int mod, int scan, int cap)
Definition at line 1118 of file qbbinputcontext_imf.cpp.
Referenced by QBBScreenEventHandler::handleKeyboardEvent(), hasPhysicalKeyboard(), and isComposing().
 {
     if (!imfAvailable())
         return false;
     int key = (flags & KEY_SYM_VALID) ? sym : cap;
     bool navKey = false;
     switch ( key ) {
     case KEYCODE_RETURN:
          /* In a single line edit we should end composition because enter might be used by something.
             endComposition();
             return false;*/
         break;
     case KEYCODE_BACKSPACE:
     case KEYCODE_DELETE:
         // If there is a selection range, then we want a delete key to operate on that (by
         // deleting the contents of the select range) rather than operating on the composition
         // range.
         if (hasSelectedText())
             return false;
         break;
     case  KEYCODE_LEFT:
         key = NAVIGATE_LEFT;
         navKey = true;
         break;
     case  KEYCODE_RIGHT:
         key = NAVIGATE_RIGHT;
         navKey = true;
         break;
     case  KEYCODE_UP:
         key = NAVIGATE_UP;
         navKey = true;
         break;
     case  KEYCODE_DOWN:
         key = NAVIGATE_DOWN;
         navKey = true;
         break;
     case  KEYCODE_CAPS_LOCK:
     case  KEYCODE_LEFT_SHIFT:
     case  KEYCODE_RIGHT_SHIFT:
     case  KEYCODE_LEFT_CTRL:
     case  KEYCODE_RIGHT_CTRL:
     case  KEYCODE_LEFT_ALT:
     case  KEYCODE_RIGHT_ALT:
     case  KEYCODE_MENU:
     case  KEYCODE_LEFT_HYPER:
     case  KEYCODE_RIGHT_HYPER:
     case  KEYCODE_INSERT:
     case  KEYCODE_HOME:
     case  KEYCODE_PG_UP:
     case  KEYCODE_END:
     case  KEYCODE_PG_DOWN:
         // Don't send these
         key = 0;
         break;
     }
     if ( mod & KEYMOD_CTRL ) {
         // If CTRL is pressed, just let AIR handle it.  But terminate any composition first
         //endComposition();
         return false;
     }
     // Pass the keys we don't know about on through
     if ( key == 0 )
         return false;
     // IMF doesn't need key releases so just swallow them.
     if (!(flags & KEY_DOWN))
         return true;
     if ( navKey ) {
         // Even if we're forwarding up events, we can't do this for
         // navigation keys.
         if ( flags & KEY_DOWN ) {
             navigation_event_t navEvent;
             initEvent(&navEvent.event, sInputSession, EVENT_NAVIGATION, key);
             navEvent.magnitude = 1;
 #if defined(QBBINPUTCONTEXT_DEBUG)
             qDebug() << TAG << "dispatch navigation event " << key;
 #endif
             p_ictrl_dispatch_event(&navEvent.event);
         }
     }
     else {
         key_event_t keyEvent;
         initEvent(&keyEvent.event, sInputSession, EVENT_KEY, flags & KEY_DOWN ? IMF_KEY_DOWN : IMF_KEY_UP);
         keyEvent.key_code = key;
         keyEvent.character = 0;
         keyEvent.meta_key_state = 0;
         p_ictrl_dispatch_event(&keyEvent.event);
 #if defined(QBBINPUTCONTEXT_DEBUG)
         qDebug() << TAG << "dispatch key event " << key;
 #endif
     }
     scan = 0;
     return true;
 }
hasPhysicalKeyboard()
bool QBBInputContext::hasPhysicalKeyboard () private
Definition at line 69 of file qbbinputcontext_noimf.cpp.
Referenced by isComposing().
 {
     // TODO: This should query the system to check if a USB keyboard is connected.
     return false;
 }
hasSelectedText()
bool QBBInputContext::hasSelectedText () private
Definition at line 1039 of file qbbinputcontext_imf.cpp.
Referenced by handleKeyboardEvent(), and onDeleteSurroundingText().
 {
     if (focusWidget()) {
         return focusWidget()->inputMethodQuery(Qt::ImCursorPosition).toInt() != focusWidget()->inputMethodQuery(Qt::ImAnchorPosition).toInt();
     }
     else
     {
         return false;
     }
 }
hasSession()
bool QBBInputContext::hasSession () private
Definition at line 1034 of file qbbinputcontext_imf.cpp.
Referenced by setFocusWidget().
 {
     return sInputSession != 0;
 }
identifierName() [1/2]
QString QBBInputContext::identifierName () inline virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 57 of file qbbinputcontext_noimf.h.
 { return QString("BlackBerry IMF"); }
identifierName() [2/2]
QString QBBInputContext::identifierName () virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 891 of file qbbinputcontext_imf.cpp.
 {
     return tr("PlayBook IMF");
 }
isComposing() [1/2]
bool QBBInputContext::isComposing () const inline virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 61 of file qbbinputcontext_noimf.h.
 { return false; }
isComposing() [2/2]
bool QBBInputContext::isComposing () const virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 935 of file qbbinputcontext_imf.cpp.
Referenced by endComposition().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     return mIsComposing;
 }
language() [1/2]
QString QBBInputContext::language () virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
language() [2/2]
QString QBBInputContext::language () virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
Definition at line 896 of file qbbinputcontext_imf.cpp.
Referenced by identifierName().
 {
     return mVirtualKeyboard.languageId();
 }
mouseHandler()
void QBBInputContext::mouseHandler (int x, QMouseEvent * event) virtual
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
You can use the function to implement mouse-oriented user interface such as text selection or popup menu for candidate selection.
The x parameter is the offset within the string that was sent with the InputMethodCompose event. The alteration boundary of x is ensured as character boundary of preedit string accurately.
The event parameter is the event that was sent to the editor widget. The event type is QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QEvent::MouseButtonDblClick or QEvent::MouseMove. The event's button and state indicate the kind of operation that was performed.
Reimplemented from QInputContext.
Definition at line 943 of file qbbinputcontext_imf.cpp.
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     return QInputContext::mouseHandler(x, event);
 }
onBeginBatchEdit()
int32_t QBBInputContext::onBeginBatchEdit (input_session_t * ic) private
Definition at line 1319 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // We don't care.
     return 0;
 }
onClearMetaKeyStates()
int32_t QBBInputContext::onClearMetaKeyStates (input_session_t * ic, int32_t states) private
Definition at line 1332 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(states);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // Should never get called.
     qCritical() << TAG << "onClearMetaKeyStates is unsupported.";
     return 0;
 }
onCommitText()
int32_t QBBInputContext::onCommitText (input_session_t * ic, spannable_string_t * text, int32_t new_cursor_position) private
Definition at line 1347 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(new_cursor_position);  // TODO: How can we set the cursor position it's not part of the API.
     if (!isSessionOkay(ic))
         return 0;
     QString commitString = QString::fromWCharArray(text->str, text->length);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG << "Committing [" << commitString << "]";
 #endif
     QList<QInputMethodEvent::Attribute> attributes;
     QInputMethodEvent event(QLatin1String(""), attributes);
     event.setCommitString(commitString, 0, 0);
     sendEvent(event);
     mComposingText = QString();
     return 0;
 }
onDeleteSurroundingText()
int32_t QBBInputContext::onDeleteSurroundingText (input_session_t * ic, int32_t left_length, int32_t right_length) private
Definition at line 1369 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG << "L:" << left_length << " R:" << right_length;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     if (hasSelectedText()) {
         QBBEventThread::injectKeyboardEvent(KEY_DOWN | KEY_CAP_VALID, KEYCODE_DELETE, 0, 0, 0);
         QBBEventThread::injectKeyboardEvent(KEY_CAP_VALID, KEYCODE_DELETE, 0, 0, 0);
         reset();
         return 0;
     }
     int replacementLength = left_length + right_length;
     int replacementStart = -left_length;
     QList<QInputMethodEvent::Attribute> attributes;
     QInputMethodEvent event(QLatin1String(""), attributes);
     event.setCommitString(QLatin1String(""), replacementStart, replacementLength);
     sendEvent(event);
     return 0;
 }
onEndBatchEdit()
int32_t QBBInputContext::onEndBatchEdit (input_session_t * ic) private
Definition at line 1396 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     return 0;
 }
onFinishComposingText()
int32_t QBBInputContext::onFinishComposingText (input_session_t * ic) private
Definition at line 1408 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // Only update the control, no need to send a message back to imf (don't call
     // end composition)
     QList<QInputMethodEvent::Attribute> attributes;
     QInputMethodEvent event(QLatin1String(""), attributes);
     event.setCommitString(mComposingText);
     mComposingText = QString();
     mIsComposing = false;
     sendEvent(event);
     return 0;
 }
onForceUpdate()
int32_t QBBInputContext::onForceUpdate () private
onGetCursorCapsMode()
int32_t QBBInputContext::onGetCursorCapsMode (input_session_t * ic, int32_t req_modes) private
Definition at line 1429 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(req_modes);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // Should never get called.
     qCritical() << TAG << "onGetCursorCapsMode is unsupported.";
     return 0;
 }
onGetCursorPosition()
int32_t QBBInputContext::onGetCursorPosition (input_session_t * ic) private
Definition at line 1445 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     mLastCaretPos = focusWidget()->inputMethodQuery(Qt::ImCursorPosition).toInt();
     return mLastCaretPos;
 }
onGetExtractedText()
extracted_text_t * QBBInputContext::onGetExtractedText (input_session_t * ic, extracted_text_request_t * request, int32_t flags) private
Definition at line 1458 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(flags);
     Q_UNUSED(request);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic)) {
         extracted_text_t *et = (extracted_text_t *)calloc(sizeof(extracted_text_t),1);
         et->text = (spannable_string_t *)calloc(sizeof(spannable_string_t),1);
         return 0;
     }
     // Used to update dictionaries, but not supported right now.
     extracted_text_t *et = (extracted_text_t *)calloc(sizeof(extracted_text_t),1);
     et->text = (spannable_string_t *)calloc(sizeof(spannable_string_t),1);
     return et;
 }
onGetSelectedText()
spannable_string_t * QBBInputContext::onGetSelectedText (input_session_t * ic, int32_t flags) private
Definition at line 1479 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(flags);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return toSpannableString("");
     QString text = focusWidget()->inputMethodQuery(Qt::ImCurrentSelection).toString();
     return toSpannableString(text);
 }
onGetTextAfterCursor()
spannable_string_t * QBBInputContext::onGetTextAfterCursor (input_session_t * ic, int32_t n, int32_t flags) private
Definition at line 1493 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(flags);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return toSpannableString("");
     QString text = focusWidget()->inputMethodQuery(Qt::ImSurroundingText).toString();
     mLastCaretPos = focusWidget()->inputMethodQuery(Qt::ImCursorPosition).toInt();
     return toSpannableString(text.mid(mLastCaretPos+1, n));
 }
onGetTextBeforeCursor()
spannable_string_t * QBBInputContext::onGetTextBeforeCursor (input_session_t * ic, int32_t n, int32_t flags) private
Definition at line 1509 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(flags);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return toSpannableString("");
     QString text = focusWidget()->inputMethodQuery(Qt::ImSurroundingText).toString();
     mLastCaretPos = focusWidget()->inputMethodQuery(Qt::ImCursorPosition).toInt();
     if (n < mLastCaretPos)
     {
         return toSpannableString(text.mid(mLastCaretPos - n, n));
     }
     else
         return toSpannableString(text.mid(0, mLastCaretPos));
 }
onPerformEditorAction()
int32_t QBBInputContext::onPerformEditorAction (input_session_t * ic, int32_t editor_action) private
Definition at line 1530 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(editor_action);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // Should never get called.
     qCritical() << TAG << "onPerformEditorAction is unsupported.";
     return 0;
 }
onReportFullscreenMode()
int32_t QBBInputContext::onReportFullscreenMode (input_session_t * ic, int32_t enabled) private
Definition at line 1546 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(enabled);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // Should never get called.
     qCritical() << TAG << "onReportFullscreenMode is unsupported.";
     return 0;
 }
onSendAsyncEvent()
int32_t QBBInputContext::onSendAsyncEvent (input_session_t * ic, event_t * event) private
Definition at line 1574 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     return processEvent(event);
 }
onSendEvent()
int32_t QBBInputContext::onSendEvent (input_session_t * ic, event_t * event) private
Definition at line 1562 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     return processEvent(event);
 }
onSetComposingRegion()
int32_t QBBInputContext::onSetComposingRegion (input_session_t * ic, int32_t start, int32_t end) private
Definition at line 1586 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     if (!focusWidget())
     {
         qCritical() << "No focus widget!";
         return 0;
     }
     QList<QInputMethodEvent::Attribute> attributes;
     mLastCaretPos = focusWidget()->inputMethodQuery(Qt::ImCursorPosition).toInt();
     QString text = focusWidget()->inputMethodQuery(Qt::ImSurroundingText).toString();
     QString empty = QString::fromLatin1("");
     text = text.mid(start, end - start);
     // Delete the current text.
     {
         QInputMethodEvent event(empty, attributes);
         event.setCommitString(empty, start - mLastCaretPos, end - start);
         sendEvent(event);
     }
     // Move the specified text into a preedit string.
     {
         setComposingText(text);
     }
     return 0;
 }
onSetComposingText()
int32_t QBBInputContext::onSetComposingText (input_session_t * ic, spannable_string_t * text, int32_t new_cursor_position) private
Definition at line 1623 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(new_cursor_position);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     if (!focusWidget())
     {
         qCritical() << "No focus widget!";
         return 0;
     }
     mIsComposing = true;
     QString preeditString = QString::fromWCharArray(text->str, text->length);
     setComposingText(preeditString);
     return 0;
 }
onSetSelection()
int32_t QBBInputContext::onSetSelection (input_session_t * ic, int32_t start, int32_t end) private
Definition at line 1647 of file qbbinputcontext_imf.cpp.
Referenced by eventFilter().
 {
     Q_UNUSED(start);
     Q_UNUSED(end);
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (!isSessionOkay(ic))
         return 0;
     // Should never get called.
     qCritical() << TAG << "onSetSelection is unsupported.";
     return 0;
 }
openSession()
void QBBInputContext::openSession () private
Definition at line 1021 of file qbbinputcontext_imf.cpp.
Referenced by setFocusWidget().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;;
 #endif
     if (!imfAvailable())
         return;
     closeSession();
     sInputSession = p_ictrl_open_session(&ic_funcs);
 }
processEvent()
int32_t QBBInputContext::processEvent (event_t * event) private
Definition at line 1256 of file qbbinputcontext_imf.cpp.
Referenced by onSendAsyncEvent(), and onSendEvent().
 {
     int32_t result = -1;
     switch (event->event_type) {
     case EVENT_SPELL_CHECK: {
         #if defined(QBBINPUTCONTEXT_DEBUG)
         qDebug() << TAG << "EVENT_SPELL_CHECK";
         #endif
         result = 0;
         break;
     }
     case EVENT_NAVIGATION: {
         #if defined(QBBINPUTCONTEXT_DEBUG)
         qDebug() << TAG << "EVENT_NAVIGATION";
         #endif
         int key = event->event_id == NAVIGATE_UP ? KEYCODE_UP :
             event->event_id == NAVIGATE_DOWN ? KEYCODE_DOWN :
             event->event_id == NAVIGATE_LEFT ? KEYCODE_LEFT :
             event->event_id == NAVIGATE_RIGHT ? KEYCODE_RIGHT : 0;
         QBBEventThread::injectKeyboardEvent(KEY_DOWN | KEY_CAP_VALID, key, 0, 0, 0);
         QBBEventThread::injectKeyboardEvent(KEY_CAP_VALID, key, 0, 0, 0);
         result = 0;
         break;
     }
     case EVENT_KEY: {
         #if defined(QBBINPUTCONTEXT_DEBUG)
         qDebug() << TAG << "EVENT_KEY";
         #endif
         key_event_t* kevent = (key_event_t*) event;
         QBBEventThread::injectKeyboardEvent(KEY_DOWN | KEY_SYM_VALID | KEY_CAP_VALID, kevent->key_code, 0, 0, kevent->key_code);
         QBBEventThread::injectKeyboardEvent(KEY_SYM_VALID | KEY_CAP_VALID, kevent->key_code, 0, 0, kevent->key_code);
         result = 0;
         break;
     }
     case EVENT_ACTION:
             // Don't care, indicates that IMF is done.
         break;
     case EVENT_CARET:
     case EVENT_NOTHING:
     case EVENT_FOCUS:
     case EVENT_USER_ACTION:
     case EVENT_STROKE:
     case EVENT_INVOKE_LATER:
         qCritical() << TAG << "Unsupported event type: " << event->event_type;
         break;
     default:
         qCritical() << TAG << "Unknown event type: " << event->event_type;
     }
     return result;
 }
reset() [1/2]
void QBBInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
reset() [2/2]
void QBBInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
Definition at line 951 of file qbbinputcontext_imf.cpp.
Referenced by hasPhysicalKeyboard(), identifierName(), onDeleteSurroundingText(), and update().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     endComposition();
 }
setComposingText()
void QBBInputContext::setComposingText (QString const & composingText) private
Definition at line 1241 of file qbbinputcontext_imf.cpp.
Referenced by onSetComposingRegion(), and onSetComposingText().
 {
     mComposingText = composingText;
     mIsComposing = true;
     QList<QInputMethodEvent::Attribute> attributes;
     QTextCharFormat format;
     format.setFontUnderline(true);
     attributes.push_back(QInputMethodEvent::Attribute(QInputMethodEvent::TextFormat, 0, composingText.length(), format));
     QInputMethodEvent event(composingText, attributes);
     sendEvent(event);
 }
setFocusWidget() [1/2]
void QBBInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
setFocusWidget() [2/2]
void QBBInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
Definition at line 960 of file qbbinputcontext_imf.cpp.
Referenced by hasPhysicalKeyboard(), and isComposing().
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     if (hasSession()) {
         endComposition();
         dispatchFocusEvent(FOCUS_LOST);
         closeSession();
     }
     // Update the widget before moving on.
     QInputContext::setFocusWidget(widget);
     // If we have hidden text, or any flags that restrict input (exclusive flags), then we just disable
     // imf for this field.
     if (widget != 0 && !(widget->inputMethodHints() & Qt::ImhHiddenText) && !(widget->inputMethodHints()  >= Qt::ImhDigitsOnly && widget->inputMethodHints() <= Qt::ImhUrlCharactersOnly))
     {
 #if defined(QBBINPUTCONTEXT_DEBUG)
         qDebug() << TAG << "Starting input session for " << widget;
 #endif
         openSession();
         dispatchFocusEvent(FOCUS_GAINED, widget->inputMethodHints());
     }
 }
update()
void QBBInputContext::update (void) virtual
This virtual function is called when a state in the focus widget has changed.
QInputContext can then use QWidget::inputMethodQuery() to query the new state of the widget.
Reimplemented from QInputContext.
Definition at line 987 of file qbbinputcontext_imf.cpp.
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     reset();
     QInputContext::update();
 }
widgetDestroyed()
void QBBInputContext::widgetDestroyed (QWidget * widget) virtual
This virtual function is called when the specified widget is destroyed.
The widget is a widget on which this input context is installed.
Reimplemented from QInputContext.
Definition at line 998 of file qbbinputcontext_imf.cpp.
 {
 #if defined(QBBINPUTCONTEXT_DEBUG)
     qDebug() << TAG;
 #endif
     QInputContext::widgetDestroyed(widget);
 }
Properties
mComposingText
QString QBBInputContext::mComposingText private
Definition at line 116 of file qbbinputcontext_imf.h.
Referenced by endComposition(), onCommitText(), onFinishComposingText(), and setComposingText().
mIsComposing
bool QBBInputContext::mIsComposing private
Definition at line 115 of file qbbinputcontext_imf.h.
Referenced by endComposition(), isComposing(), onFinishComposingText(), onSetComposingText(), and setComposingText().
mLastCaretPos
int QBBInputContext::mLastCaretPos private
Definition at line 114 of file qbbinputcontext_imf.h.
Referenced by dispatchFocusEvent(), dispatchRequestSoftwareInputPanel(), onGetCursorPosition(), onGetTextAfterCursor(), onGetTextBeforeCursor(), and onSetComposingRegion().
mVirtualKeyboard
QBBAbstractVirtualKeyboard & QBBInputContext::mVirtualKeyboard private
Definition at line 117 of file qbbinputcontext_imf.h.
Referenced by dispatchCloseSoftwareInputPanel(), dispatchRequestSoftwareInputPanel(), hasPhysicalKeyboard(), isComposing(), and language().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbinputcontext_imf.h
/src/plugins/platforms/blackberry/qbbinputcontext_noimf.h
/src/plugins/platforms/blackberry/qbbinputcontext_imf.cpp
/src/plugins/platforms/blackberry/qbbinputcontext_noimf.cpp