Qt 4.8: QMap< Key, T >::iterator Class Reference
QMap< Key, T >::iterator Class Reference
The QMap::iterator class provides an STL-style non-const iterator for QMap and QMultiMap.
#include <qmap.h>
Public Types
typedef qptrdiff difference_type
typedef std::bidirectional_iterator_tag iterator_category
A synonym for {std::bidirectional_iterator_tag} indicating this iterator is a bidirectional iterator.
typedef T * pointer
typedef T & reference
typedef T value_type
Public Functions
iterator ()
Constructs an uninitialized iterator.
iterator (QMapData::Node *node)
const Key & key () const
Returns the current item's key as a const reference.
operator QMapData::Node * () const
bool operator!= (const iterator &o) const
Returns true if other points to a different item than this iterator; otherwise returns false.
bool operator!= (const const_iterator &o) const
T & operator* () const
Returns a modifiable reference to the current item's value.
iterator operator+ (int j) const
Returns an iterator to the item at j positions forward from this iterator.
iterator & operator++ ()
The prefix ++ operator (++i) advances the iterator to the next item in the map and returns an iterator to the new current item.
iterator operator++ (int)
The postfix ++ operator (i++) advances the iterator to the next item in the map and returns an iterator to the previously current item.
iterator & operator+= (int j)
Advances the iterator by j items.
iterator operator- (int j) const
Returns an iterator to the item at j positions backward from this iterator.
iterator & operator-- ()
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
iterator operator-- (int)
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
iterator & operator-= (int j)
Makes the iterator go back by j items.
T * operator-> () const
Returns a pointer to the current item's value.
bool operator== (const iterator &o) const
Returns true if other points to the same item as this iterator; otherwise returns false.
bool operator== (const const_iterator &o) const
T & value () const
Returns a modifiable reference to the current item's value.
Private Functions
operator bool () const
Properties
QMapData::Node * i
Friends
class const_iterator
Detailed Description
template<class Key, class T>
class QMap< Key, T >::iterator
The QMap::iterator class provides an STL-style non-const iterator for QMap and QMultiMap.
QMap features both STL-style iterators and Java-style iterators. The STL-style iterators are more low-level and more cumbersome to use; on the other hand, they are slightly faster and, for developers who already know STL, have the advantage of familiarity.
QMap<Key, T>::iterator allows you to iterate over a QMap (or QMultiMap) and to modify the value (but not the key) stored under a particular key. If you want to iterate over a const QMap, you should use QMap::const_iterator. It is generally good practice to use QMap::const_iterator on a non-const QMap as well, unless you need to change the QMap through the iterator. Const iterators are slightly faster, and can improve code readability.
The default QMap::iterator constructor creates an uninitialized iterator. You must initialize it using a QMap function like QMap::begin(), QMap::end(), or QMap::find() before you can start iterating. Here's a typical loop that prints all the (key, value) pairs stored in a map:
QMap<QString, int> map;
map.insert("January", 1);
map.insert("February", 2);
...
map.insert("December", 12);
QMap<QString, int>::iterator i;
for (i = map.begin(); i != map.end(); ++i)
    cout << i.key() << ": " << i.value() << endl;
Unlike QHash, which stores its items in an arbitrary order, QMap stores its items ordered by key. Items that share the same key (because they were inserted using QMap::insertMulti(), or due to a unite()) will appear consecutively, from the most recently to the least recently inserted value.
Let's see a few examples of things we can do with a QMap::iterator that we cannot do with a QMap::const_iterator. Here's an example that increments every value stored in the QMap by 2:
QMap<QString, int>::iterator i;
for (i = map.begin(); i != map.end(); ++i)
    i.value() += 2;
Here's an example that removes all the items whose key is a string that starts with an underscore character:
QMap<QString, int>::iterator i = map.begin();
while (i != map.end()) {
    if (i.key().startsWith("_"))
        i = map.erase(i);
    else
        ++i;
}
The call to QMap::erase() removes the item pointed to by the iterator from the map, and returns an iterator to the next item. Here's another way of removing an item while iterating:
QMap<QString, int>::iterator i = map.begin();
while (i != map.end()) {
    QMap<QString, int>::iterator prev = i;
    ++i;
    if (prev.key().startsWith("_"))
        map.erase(prev);
}
It might be tempting to write code like this:
// WRONG
while (i != map.end()) {
    if (i.key().startsWith("_"))
        map.erase(i);
    ++i;
}
However, this will potentially crash in ++i, because i is a dangling iterator after the call to erase().
Multiple iterators can be used on the same map. If you add items to the map, existing iterators will remain valid. If you remove items from the map, iterators that point to the removed items will become dangling iterators.
See also
QMap::const_iterator, QMutableMapIterator
Definition at line 233 of file qmap.h.
Typedefs
difference_type
template<class Key, class T> QMap< Key, T >::iterator::difference_type
Warning
This function is not part of the public interface.
Definition at line 240 of file qmap.h.
iterator_category
template<class Key, class T> QMap< Key, T >::iterator::iterator_category
A synonym for {std::bidirectional_iterator_tag} indicating this iterator is a bidirectional iterator.
Definition at line 239 of file qmap.h.
pointer
template<class Key, class T> QMap< Key, T >::iterator::pointer
Warning
This function is not part of the public interface.
Definition at line 242 of file qmap.h.
reference
template<class Key, class T> QMap< Key, T >::iterator::reference
Warning
This function is not part of the public interface.
Definition at line 243 of file qmap.h.
value_type
template<class Key, class T> QMap< Key, T >::iterator::value_type
Warning
This function is not part of the public interface.
Definition at line 241 of file qmap.h.
Constructors and Destructors
iterator() [1/2]
template<class Key, class T> QMap< Key, T >::iterator::iterator () inline
Constructs an uninitialized iterator.
Functions like key(), value(), and operator++() must not be called on an uninitialized iterator. Use operator=() to assign a value to it before using it.
See also
QMap::begin() QMap::end()
Definition at line 247 of file qmap.h.
 : i(0) { }
iterator() [2/2]
template<class Key, class T> QMap< Key, T >::iterator::iterator (QMapData::Node * node) inline
Warning
This function is not part of the public interface.
Definition at line 248 of file qmap.h.
 : i(node) { }
Functions
key()
template<class Key, class T> const Key & QMap< Key, T >::iterator::key () const inline
Returns the current item's key as a const reference.
There is no direct way of changing an item's key through an iterator, although it can be done by calling QMap::erase() followed by QMap::insert() or QMap::insertMulti().
See also
value()
Definition at line 250 of file qmap.h.
Referenced by QSpanCollection::cleanSpanSubIndex(), QFontCache::cleanupPrinterFonts(), QGraphicsScenePrivate::filterEvent(), QMultiMap< QString, Method >::find(), QSqlTableModel::insertRows(), menuItemEntry(), QAxClientSite::qt_metacall(), qt_transparent_pixel(), QMultiMap< QString, Method >::remove(), QGraphicsScenePrivate::removeItemHelper(), QSqlTableModelPrivate::revertCachedRow(), and write_xpm_image().
 { return concrete(i)->key; }
operator bool()
template<class Key, class T> QMap< Key, T >::iterator::operator bool () const inline private
Definition at line 297 of file qmap.h.
 { return false; }
operator QMapData::Node *()
template<class Key, class T> QMap< Key, T >::iterator::operator QMapData::Node * () const inline
Warning
This function is not part of the public interface.
Definition at line 246 of file qmap.h.
 { return i; }
operator!=() [1/2]
template<class Key, class T> bool QMap< Key, T >::iterator::operator!= (const iterator & o) const inline
Returns true if other points to a different item than this iterator; otherwise returns false.
Definition at line 258 of file qmap.h.
 { return i != o.i; }
operator!=() [2/2]
template<class Key, class T> bool QMap< Key, T >::iterator::operator!= (const const_iterator & other) const inline
See also
operator==()
Definition at line 292 of file qmap.h.
             { return i != o.i; }
operator*()
template<class Key, class T> T & QMap< Key, T >::iterator::operator* () const inline
Returns a modifiable reference to the current item's value.
Same as value().
See also
key()
Definition at line 255 of file qmap.h.
 { return concrete(i)->value; }
operator+()
template<class Key, class T> QMap::iterator QMap< Key, T >::iterator::operator+ (int j) const inline
Returns an iterator to the item at j positions forward from this iterator.
(If j is negative, the iterator goes backward.)
This operation can be slow for large j values.
See also
operator-()
Definition at line 278 of file qmap.h.
         { iterator r = *this; if (j > 0) while (j--) ++r; else while (j++) --r; return r; }
operator++() [1/2]
template<class Key, class T> QMap::iterator QMap< Key, T >::iterator::operator++ () inline
The prefix ++ operator (++i) advances the iterator to the next item in the map and returns an iterator to the new current item.
Calling this function on QMap::end() leads to undefined results.
See also
operator--()
Definition at line 260 of file qmap.h.
{
             i = i->forward[0];
             return *this;
         }
operator++() [2/2]
template<class Key, class T> QMap::iterator QMap< Key, T >::iterator::operator++ (int) inline
The postfix ++ operator (i++) advances the iterator to the next item in the map and returns an iterator to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 264 of file qmap.h.
{
             iterator r = *this;
             i = i->forward[0];
             return r;
         }
operator+=()
template<class Key, class T> QMap::iterator & QMap< Key, T >::iterator::operator+= (int j) inline
Advances the iterator by j items.
(If j is negative, the iterator goes backward.)
See also
operator-=(), operator+()
Definition at line 281 of file qmap.h.
 { return *this = *this + j; }
operator-()
template<class Key, class T> QMap::iterator QMap< Key, T >::iterator::operator- (int j) const inline
Returns an iterator to the item at j positions backward from this iterator.
(If j is negative, the iterator goes forward.)
This operation can be slow for large j values.
See also
operator+()
Definition at line 280 of file qmap.h.
 { return operator+(-j); }
operator--() [1/2]
template<class Key, class T> QMap::iterator QMap< Key, T >::iterator::operator-- () inline
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
Calling this function on QMap::begin() leads to undefined results.
See also
operator++()
Definition at line 269 of file qmap.h.
{
             i = i->backward;
             return *this;
         }
operator--() [2/2]
template<class Key, class T> QMap::iterator QMap< Key, T >::iterator::operator-- (int) inline
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 273 of file qmap.h.
{
             iterator r = *this;
             i = i->backward;
             return r;
         }
operator-=()
template<class Key, class T> QMap::iterator & QMap< Key, T >::iterator::operator-= (int j) inline
Makes the iterator go back by j items.
(If j is negative, the iterator goes forward.)
See also
operator+=(), operator-()
Definition at line 282 of file qmap.h.
 { return *this = *this - j; }
operator->()
template<class Key, class T> T * QMap< Key, T >::iterator::operator-> () const inline
Returns a pointer to the current item's value.
See also
value()
Definition at line 256 of file qmap.h.
 { return &concrete(i)->value; }
operator==() [1/2]
template<class Key, class T> bool QMap< Key, T >::iterator::operator== (const iterator & o) const inline
Returns true if other points to the same item as this iterator; otherwise returns false.
Definition at line 257 of file qmap.h.
 { return i == o.i; }
operator==() [2/2]
template<class Key, class T> bool QMap< Key, T >::iterator::operator== (const const_iterator & other) const inline
See also
operator!=()
Definition at line 290 of file qmap.h.
             { return i == o.i; }
value()
template<class Key, class T> T & QMap< Key, T >::iterator::value () const inline
Returns a modifiable reference to the current item's value.
You can change the value of an item by using value() on the left side of an assignment, for example:
if (i.key() == "Hello")
    i.value() = "Bonjour";
See also
key(), operator*()
Definition at line 251 of file qmap.h.
Referenced by QSpanCollection::cleanSpanSubIndex(), QFontCache::cleanupPrinterFonts(), QFontCache::clear(), QGraphicsScenePrivate::filterEvent(), QMultiMap< QString, Method >::find(), QCopChannel::init(), QSqlTableModel::insertRows(), QWSServerPrivate::invokeSelectCursor(), QMultiMap< QString, Method >::remove(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsScenePrivate::removeSceneEventFilter(), QScriptDebuggerScriptsModel::removeScript(), QSqlTableModelPrivate::revertCachedRow(), QCompletionEngine::saveInCache(), QFontCache::timerEvent(), and QCopChannel::~QCopChannel().
 { return concrete(i)->value; }
Friends and Related Functions
const_iterator
template<class Key, class T> friend class const_iterator friend
Definition at line 235 of file qmap.h.
Properties
i
template<class Key, class T> QMapData::Node* QMap< Key, T >::iterator::i private
Definition at line 236 of file qmap.h.
Referenced by QMap< Key, T >::const_iterator::const_iterator(), QMap< Key, T >::iterator::operator!=(), and QMap< Key, T >::iterator::operator==().
The documentation for this class was generated from the following files:
/src/corelib/tools/qmap.h
/src/corelib/tools/qmap.cpp