Qt 4.8: QGraphicsAnchorLayoutPrivate Class Reference
QGraphicsAnchorLayoutPrivate Class Reference
QGraphicsAnchorLayout private methods and attributes.
#include <qgraphicsanchorlayout_p.h>
Public Types
enum Interval { MinimumToMinPreferred = 0, MinPreferredToPreferred, PreferredToMaxPreferred, MaxPreferredToMaximum }
enum Orientation { Horizontal = 0, Vertical, NOrientations }
Public Types inherited from QGraphicsLayoutItemPrivate
enum SizeComponent { Width, Height }
Public Functions
QGraphicsAnchor * acquireGraphicsAnchor (AnchorData *data)
QGraphicsAnchor * addAnchor (QGraphicsLayoutItem *firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem *secondItem, Qt::AnchorPoint secondEdge, qreal *spacing=0)
void addAnchor_helper (QGraphicsLayoutItem *firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem *secondItem, Qt::AnchorPoint secondEdge, AnchorData *data)
AnchorData * addAnchorMaybeParallel (AnchorData *newAnchor, bool *feasible)
Adds newAnchor to the graph.
AnchorVertex * addInternalVertex (QGraphicsLayoutItem *item, Qt::AnchorPoint edge)
void calculateGraphs ()
Called on activation.
void calculateGraphs (Orientation orientation)
Calculate graphs is the method that puts together all the helper routines so that the AnchorLayout can calculate the sizes of each item.
bool calculateNonTrunk (const QList< QSimplexConstraint *> &constraints, const QList< AnchorData *> &variables)
bool calculateTrunk (Orientation orientation, const GraphPath &trunkPath, const QList< QSimplexConstraint *> &constraints, const QList< AnchorData *> &variables)
Calculate the sizes for all anchors which are part of the trunk.
void calculateVertexPositions (Orientation orientation)
Calculate the position of each vertex based on the paths to each of them as well as the current edges sizes.
void changeLayoutVertex (Orientation orientation, AnchorVertex *oldV, AnchorVertex *newV)
void constraintsFromPaths (Orientation orientation)
Each vertex on the graph that has more than one path to it represents a contra int to the sizes of the items in these paths.
QList< QSimplexConstraint * > constraintsFromSizeHints (const QList< AnchorData *> &anchors)
void correctEdgeDirection (QGraphicsLayoutItem *&firstItem, Qt::AnchorPoint &firstEdge, QGraphicsLayoutItem *&secondItem, Qt::AnchorPoint &secondEdge)
Use heuristics to determine the correct orientation of a given anchor.
void createCenterAnchors (QGraphicsLayoutItem *item, Qt::AnchorPoint centerEdge)
By default, each item in the layout is represented internally as a single anchor in each direction.
void createItemEdges (QGraphicsLayoutItem *item)
void createLayoutEdges ()
Create internal anchors to connect the layout edges (Left to Right and Top to Bottom).
void deleteLayoutEdges ()
void dumpGraph (const QString &name=QString())
void findPaths (Orientation orientation)
This method walks the graph using a breadth-first search to find paths between the root vertex and each vertex on the graph.
QGraphicsAnchor * getAnchor (QGraphicsLayoutItem *firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem *secondItem, Qt::AnchorPoint secondEdge)
QList< QList< QSimplexConstraint * > > getGraphParts (Orientation orientation)
bool hasConflicts () const
Returns true if there are no arrangement that satisfies all constraints.
void identifyFloatItems (const QSet< AnchorData *> &visited, Orientation orientation)
Use all visited Anchors on findPaths() so we can identify non-float Items.
void identifyNonFloatItems_helper (const AnchorData *ad, QSet< QGraphicsLayoutItem *> *nonFloatingItemsIdentifiedSoFar)
Given an anchor, if it is an internal anchor and Normal we must mark it's item as non-float.
AnchorVertex * internalVertex (const QPair< QGraphicsLayoutItem *, Qt::AnchorPoint > &itemEdge) const
AnchorVertex * internalVertex (const QGraphicsLayoutItem *item, Qt::AnchorPoint edge) const
void interpolateEdge (AnchorVertex *base, AnchorData *edge)
Calculate the current Edge size based on the current Layout size and the size the edge is supposed to have when the layout is at its:
QGraphicsAnchorLayoutPrivate ()
void refreshAllSizeHints (Orientation orientation)
Traverse the graph refreshing the size hints.
void removeAnchor (AnchorVertex *firstVertex, AnchorVertex *secondVertex)
void removeAnchor_helper (AnchorVertex *v1, AnchorVertex *v2)
void removeAnchors (QGraphicsLayoutItem *item)
void removeCenterAnchors (QGraphicsLayoutItem *item, Qt::AnchorPoint centerEdge, bool substitute=true)
void removeCenterConstraints (QGraphicsLayoutItem *item, Orientation orientation)
void removeInternalVertex (QGraphicsLayoutItem *item, Qt::AnchorPoint edge)
void removeVertex (QGraphicsLayoutItem *item, Qt::AnchorPoint edge)
bool replaceVertex (Orientation orientation, AnchorVertex *oldV, AnchorVertex *newV, const QList< AnchorData *> &edges)
void restoreSimplifiedAnchor (AnchorData *edge)
void restoreSimplifiedConstraints (ParallelAnchorData *parallel)
void restoreSimplifiedGraph (Orientation orientation)
void restoreVertices (Orientation orientation)
void setItemsGeometries (const QRectF &geom)
Use the current vertices distance to calculate and set the geometry of each item.
void setupEdgesInterpolation (Orientation orientation)
Calculate interpolation parameters based on current Layout Size.
bool simplifyGraph (Orientation orientation)
The purpose of this function is to simplify the graph.
bool simplifyGraphIteration (Orientation orientation, bool *feasible)
One iteration of the simplification algorithm.
bool simplifyVertices (Orientation orientation)
bool solveMinMax (const QList< QSimplexConstraint *> &constraints, GraphPath path, qreal *min, qreal *max)
bool solvePreferred (const QList< QSimplexConstraint *> &constraints, const QList< AnchorData *> &variables)
QLayoutStyleInfo & styleInfo () const
void updateAnchorSizes (Orientation orientation)
Public Functions inherited from QGraphicsLayoutPrivate
void activateRecursive (QGraphicsLayoutItem *item)
void addChildLayoutItem (QGraphicsLayoutItem *item)
This function is called from subclasses to add a layout item layoutItem to a layout.
void getMargin (qreal *result, qreal userMargin, QStyle::PixelMetric pm) const
QGraphicsLayoutPrivate ()
void reparentChildItems (QGraphicsItem *newParent)
Qt::LayoutDirection visualDirection () const
Public Functions inherited from QGraphicsLayoutItemPrivate
QSizeF * effectiveSizeHints (const QSizeF &constraint) const
void ensureUserSizeHints ()
Ensures that userSizeHints is allocated.
bool hasHeightForWidth () const
bool hasWidthForHeight () const
void init ()
QGraphicsItem * parentItem () const
Returns the parent item of this layout, or 0 if this layout is not installed on any widget.
QGraphicsLayoutItemPrivate (QGraphicsLayoutItem *parent, bool isLayout)
void setSize (Qt::SizeHint which, const QSizeF &size)
Sets the user size hint which to size.
void setSizeComponent (Qt::SizeHint which, SizeComponent component, qreal value)
Sets the width of the user size hint which to width.
virtual ~QGraphicsLayoutItemPrivate ()
Static Public Functions
static Orientation edgeOrientation (Qt::AnchorPoint edge)
static QGraphicsAnchorLayoutPrivate * get (QGraphicsAnchorLayout *q)
static Qt::AnchorPoint oppositeEdge (Qt::AnchorPoint edge)
static Qt::AnchorPoint pickEdge (Qt::AnchorPoint edge, Orientation orientation)
Static Public Functions inherited from QGraphicsLayoutItemPrivate
static QGraphicsLayoutItemPrivate * get (QGraphicsLayoutItem *q)
static const QGraphicsLayoutItemPrivate * get (const QGraphicsLayoutItem *q)
Public Variables
QList< AnchorData * > anchorsFromSimplifiedVertices [2]
QLayoutStyleInfo cachedStyleInfo
uint calculateGraphCacheDirty: 1
QList< QSimplexConstraint * > constraints [2]
Graph< AnchorVertex, AnchorData > graph [2]
bool graphHasConflicts [2]
QMultiHash< AnchorVertex *, GraphPath > graphPaths [2]
Interval interpolationInterval [2]
qreal interpolationProgress [2]
QList< QSimplexConstraint * > itemCenterConstraints [2]
QVector< QGraphicsLayoutItem * > items
bool lastCalculationUsedSimplex [2]
AnchorVertex * layoutCentralVertex [2]
AnchorVertex * layoutFirstVertex [2]
AnchorVertex * layoutLastVertex [2]
QSet< QGraphicsLayoutItem * > m_floatItems [2]
QHash< QPair< QGraphicsLayoutItem *, Qt::AnchorPoint >, QPair< AnchorVertex *, int > > m_vertexList
QList< AnchorVertexPair * > simplifiedVertices [2]
qreal sizeHints [2][3]
qreal spacings [NOrientations]
uint styleInfoDirty: 1
Public Variables inherited from QGraphicsLayoutPrivate
bool activated
qreal bottom
qreal left
qreal right
qreal top
Public Variables inherited from QGraphicsLayoutItemPrivate
QSizeF cachedConstraint
QSizeF cachedSizeHints [Qt::NSizeHints]
QSizeF cachedSizeHintsWithConstraints [Qt::NSizeHints]
QRectF geom
QGraphicsItem * graphicsItem
quint32 isLayout: 1
quint32 ownedByLayout: 1
QGraphicsLayoutItem * parent
QGraphicsLayoutItem * q_ptr
quint32 sizeHintCacheDirty: 1
quint32 sizeHintWithConstraintCacheDirty: 1
QSizePolicy sizePolicy
QSizeF * userSizeHints
Friends
class QGraphicsAnchorPrivate
Detailed Description
QGraphicsAnchorLayout private methods and attributes.
Warning
This function is not part of the public interface.
Definition at line 376 of file qgraphicsanchorlayout_p.h.
Enumerations
Interval
enum QGraphicsAnchorLayoutPrivate::Interval
Enumerator
MinimumToMinPreferred
MinPreferredToPreferred
PreferredToMaxPreferred
MaxPreferredToMaximum
Definition at line 386 of file qgraphicsanchorlayout_p.h.
                   {
         MinimumToMinPreferred = 0,
         MinPreferredToPreferred,
         PreferredToMaxPreferred,
         MaxPreferredToMaximum
     };
Orientation
enum QGraphicsAnchorLayoutPrivate::Orientation
Enumerator
Horizontal
Vertical
NOrientations
Definition at line 397 of file qgraphicsanchorlayout_p.h.
                      {
         Horizontal = 0,
         Vertical,
         NOrientations
     };
Constructors and Destructors
QGraphicsAnchorLayoutPrivate()
QGraphicsAnchorLayoutPrivate::QGraphicsAnchorLayoutPrivate ()
Definition at line 623 of file qgraphicsanchorlayout_p.cpp.
     : calculateGraphCacheDirty(true), styleInfoDirty(true)
 {
     for (int i = 0; i < NOrientations; ++i) {
         for (int j = 0; j < 3; ++j) {
             sizeHints[i][j] = -1;
         }
         interpolationProgress[i] = -1;
         spacings[i] = -1;
         graphHasConflicts[i] = false;
         layoutFirstVertex[i] = 0;
         layoutCentralVertex[i] = 0;
         layoutLastVertex[i] = 0;
     }
 }
Functions
acquireGraphicsAnchor()
QGraphicsAnchor* QGraphicsAnchorLayoutPrivate::acquireGraphicsAnchor (AnchorData * data) inline
Definition at line 433 of file qgraphicsanchorlayout_p.h.
Referenced by addAnchor().
     {
         Q_Q(QGraphicsAnchorLayout);
         if (!data->graphicsAnchor) {
             data->graphicsAnchor = new QGraphicsAnchor(q);
             data->graphicsAnchor->d_func()->data = data;
         }
         return data->graphicsAnchor;
     }
addAnchor()
QGraphicsAnchor * QGraphicsAnchorLayoutPrivate::addAnchor (QGraphicsLayoutItem * firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem * secondItem, Qt::AnchorPoint secondEdge, qreal * spacing = 0)
Warning
This function is not part of the public interface. Implements the high level "addAnchor" feature. Called by the public API addAnchor method.
The optional spacing argument defines the size of the anchor. If not provided, the anchor size is either 0 or not-set, depending on type of anchor created (see matrix below).
All anchors that remain with size not-set will assume the standard spacing, set either by the layout style or through the "setSpacing" layout API.
Definition at line 1662 of file qgraphicsanchorlayout_p.cpp.
 {
     Q_Q(QGraphicsAnchorLayout);
     if ((firstItem == 0) || (secondItem == 0)) {
         qWarning("QGraphicsAnchorLayout::addAnchor(): "
                  "Cannot anchor NULL items");
         return 0;
     }
     if (firstItem == secondItem) {
         qWarning("QGraphicsAnchorLayout::addAnchor(): "
                  "Cannot anchor the item to itself");
         return 0;
     }
     if (edgeOrientation(secondEdge) != edgeOrientation(firstEdge)) {
         qWarning("QGraphicsAnchorLayout::addAnchor(): "
                  "Cannot anchor edges of different orientations");
         return 0;
     }
     const QGraphicsLayoutItem *parentWidget = q->parentLayoutItem();
     if (firstItem == parentWidget || secondItem == parentWidget) {
         qWarning("QGraphicsAnchorLayout::addAnchor(): "
                  "You cannot add the parent of the layout to the layout.");
         return 0;
     }
     // In QGraphicsAnchorLayout, items are represented in its internal
     // graph as four anchors that connect:
     //  - Left -> HCenter
     //  - HCenter-> Right
     //  - Top -> VCenter
     //  - VCenter -> Bottom
     // Ensure that the internal anchors have been created for both items.
     if (firstItem != q && !items.contains(firstItem)) {
         createItemEdges(firstItem);
         addChildLayoutItem(firstItem);
     }
     if (secondItem != q && !items.contains(secondItem)) {
         createItemEdges(secondItem);
         addChildLayoutItem(secondItem);
     }
     // Create center edges if needed
     createCenterAnchors(firstItem, firstEdge);
     createCenterAnchors(secondItem, secondEdge);
     // Use heuristics to find out what the user meant with this anchor.
     correctEdgeDirection(firstItem, firstEdge, secondItem, secondEdge);
     AnchorData *data = new AnchorData;
     QGraphicsAnchor *graphicsAnchor = acquireGraphicsAnchor(data);
     addAnchor_helper(firstItem, firstEdge, secondItem, secondEdge, data);
     if (spacing) {
         graphicsAnchor->setSpacing(*spacing);
     } else {
         // If firstItem or secondItem is the layout itself, the spacing will default to 0.
         // Otherwise, the following matrix is used (questionmark means that the spacing
         // is queried from the style):
         //                from
         //  to      Left    HCenter Right
         //  Left    0       0       ?
         //  HCenter 0       0       0
         //  Right   ?       0       0
         if (firstItem == q
             || secondItem == q
             || pickEdge(firstEdge, Horizontal) == Qt::AnchorHorizontalCenter
             || oppositeEdge(firstEdge) != secondEdge) {
             graphicsAnchor->setSpacing(0);
         } else {
             graphicsAnchor->unsetSpacing();
         }
     }
     return graphicsAnchor;
 }
addAnchor_helper()
void QGraphicsAnchorLayoutPrivate::addAnchor_helper (QGraphicsLayoutItem * firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem * secondItem, Qt::AnchorPoint secondEdge, AnchorData * data)
Definition at line 1756 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor(), createCenterAnchors(), createItemEdges(), createLayoutEdges(), and removeCenterAnchors().
 {
     Q_Q(QGraphicsAnchorLayout);
     const Orientation orientation = edgeOrientation(firstEdge);
     // Create or increase the reference count for the related vertices.
     AnchorVertex *v1 = addInternalVertex(firstItem, firstEdge);
     AnchorVertex *v2 = addInternalVertex(secondItem, secondEdge);
     // Remove previous anchor
     if (graph[orientation].edgeData(v1, v2)) {
         removeAnchor_helper(v1, v2);
     }
     // If its an internal anchor, set the associated item
     if (firstItem == secondItem)
         data->item = firstItem;
     data->orientation = orientation;
     // Create a bi-directional edge in the sense it can be transversed both
     // from v1 or v2. "data" however is shared between the two references
     // so we still know that the anchor direction is from 1 to 2.
     data->from = v1;
     data->to = v2;
 #ifdef QT_DEBUG
     data->name = QString::fromAscii("%1 --to--> %2").arg(v1->toString()).arg(v2->toString());
 #endif
     // ### bit to track internal anchors, since inside AnchorData methods
     // we don't have access to the 'q' pointer.
     data->isLayoutAnchor = (data->item == q);
     graph[orientation].createEdge(v1, v2, data);
 }
addAnchorMaybeParallel()
AnchorData * QGraphicsAnchorLayoutPrivate::addAnchorMaybeParallel (AnchorData * newAnchor, bool * feasible)
Adds newAnchor to the graph.
Warning
This function is not part of the public interface.
Returns the newAnchor itself if it could be added without further changes to the graph. If a new parallel anchor had to be created, then returns the new parallel anchor. If a parallel anchor had to be created and it results in an unfeasible setup, feasible is set to false, otherwise true.
Note that in the case a new parallel anchor is created, it might also take over some constraints from its children anchors.
Definition at line 693 of file qgraphicsanchorlayout_p.cpp.
Referenced by replaceVertex(), and simplifyGraphIteration().
 {
     Orientation orientation = Orientation(newAnchor->orientation);
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     *feasible = true;
     // If already exists one anchor where newAnchor is supposed to be, we create a parallel
     // anchor.
     if (AnchorData *oldAnchor = g.takeEdge(newAnchor->from, newAnchor->to)) {
         ParallelAnchorData *parallel = new ParallelAnchorData(oldAnchor, newAnchor);
         // The parallel anchor will "replace" its children anchors in
         // every center constraint that they appear.
         // ### If the dependent (center) anchors had reference(s) to their constraints, we
         // could avoid traversing all the itemCenterConstraints.
         QList<QSimplexConstraint *> &constraints = itemCenterConstraints[orientation];
         AnchorData *children[2] = { oldAnchor, newAnchor };
         QList<QSimplexConstraint *> *childrenConstraints[2] = { &parallel->m_firstConstraints,
                                                                 &parallel->m_secondConstraints };
         for (int i = 0; i < 2; ++i) {
             AnchorData *child = children[i];
             QList<QSimplexConstraint *> *childConstraints = childrenConstraints[i];
             // We need to fix the second child constraints if the parallel group will have the
             // opposite direction of the second child anchor. For the point of view of external
             // entities, this anchor was reversed. So if at some point we say that the parallel
             // has a value of 20, this mean that the second child (when reversed) will be
             // assigned -20.
             const bool needsReverse = i == 1 && !parallel->secondForward();
             if (!child->isCenterAnchor)
                 continue;
             parallel->isCenterAnchor = true;
             for (int j = 0; j < constraints.count(); ++j) {
                 QSimplexConstraint *c = constraints[j];
                 if (c->variables.contains(child)) {
                     childConstraints->append(c);
                     qreal v = c->variables.take(child);
                     if (needsReverse)
                         v *= -1;
                     c->variables.insert(parallel, v);
                 }
             }
         }
         // At this point we can identify that the parallel anchor is not feasible, e.g. one
         // anchor minimum size is bigger than the other anchor maximum size.
         *feasible = parallel->calculateSizeHints();
         newAnchor = parallel;
     }
     g.createEdge(newAnchor->from, newAnchor->to, newAnchor);
     return newAnchor;
 }
addInternalVertex()
AnchorVertex * QGraphicsAnchorLayoutPrivate::addInternalVertex (QGraphicsLayoutItem * item, Qt::AnchorPoint edge)
Definition at line 1918 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor_helper().
 {
     QPair<QGraphicsLayoutItem *, Qt::AnchorPoint> pair(item, edge);
     QPair<AnchorVertex *, int> v = m_vertexList.value(pair);
     if (!v.first) {
         Q_ASSERT(v.second == 0);
         v.first = new AnchorVertex(item, edge);
     }
     v.second++;
     m_vertexList.insert(pair, v);
     return v.first;
 }
calculateGraphs() [1/2]
void QGraphicsAnchorLayoutPrivate::calculateGraphs ()
Called on activation.
Warning
This function is not part of the public interface.
Uses Linear Programming to define minimum, preferred and maximum sizes for the layout. Also calculates the sizes that each item should assume when the layout is in one of such situations.
Definition at line 2087 of file qgraphicsanchorlayout_p.cpp.
Referenced by hasConflicts().
 {
     if (!calculateGraphCacheDirty)
         return;
     calculateGraphs(Horizontal);
     calculateGraphs(Vertical);
     calculateGraphCacheDirty = false;
 }
calculateGraphs() [2/2]
void QGraphicsAnchorLayoutPrivate::calculateGraphs (QGraphicsAnchorLayoutPrivate::Orientation orientation)
Calculate graphs is the method that puts together all the helper routines so that the AnchorLayout can calculate the sizes of each item.
Warning
This function is not part of the public interface.
In a nutshell it should do:
1) Refresh anchor nominal sizes, that is, the size that each anchor would have if no other restrictions applied. This is done by quering the layout style and the sizeHints of the items belonging to the layout.
2) Simplify the graph by grouping together parallel and sequential anchors into "group anchors". These have equivalent minimum, preferred and maximum sizeHints as the anchors they replace.
3) Check if we got to a trivial case. In some cases, the whole graph can be simplified into a single anchor. If so, use this information. If not, then call the Simplex solver to calculate the anchors sizes.
4) Once the root anchors had its sizes calculated, propagate that to the anchors they represent.
Definition at line 2136 of file qgraphicsanchorlayout_p.cpp.
 {
 #if defined(QT_DEBUG) || defined(Q_AUTOTEST_EXPORT)
     lastCalculationUsedSimplex[orientation] = false;
 #endif
     static bool simplificationEnabled = qgetenv("QT_ANCHORLAYOUT_NO_SIMPLIFICATION").isEmpty();
     // Reset the nominal sizes of each anchor based on the current item sizes
     refreshAllSizeHints(orientation);
     // Simplify the graph
     if (simplificationEnabled && !simplifyGraph(orientation)) {
         qWarning("QGraphicsAnchorLayout: anchor setup is not feasible.");
         graphHasConflicts[orientation] = true;
         return;
     }
     // Traverse all graph edges and store the possible paths to each vertex
     findPaths(orientation);
     // From the paths calculated above, extract the constraints that the current
     // anchor setup impose, to our Linear Programming problem.
     constraintsFromPaths(orientation);
     // Split the constraints and anchors into groups that should be fed to the
     // simplex solver independently. Currently we find two groups:
     //
     //  1) The "trunk", that is, the set of anchors (items) that are connected
     //     to the two opposite sides of our layout, and thus need to stretch in
     //     order to fit in the current layout size.
     //
     //  2) The floating or semi-floating anchors (items) that are those which
     //     are connected to only one (or none) of the layout sides, thus are not
     //     influenced by the layout size.
     QList<QList<QSimplexConstraint *> > parts = getGraphParts(orientation);
     // Now run the simplex solver to calculate Minimum, Preferred and Maximum sizes
     // of the "trunk" set of constraints and variables.
     // ### does trunk always exist? empty = trunk is the layout left->center->right
     QList<QSimplexConstraint *> trunkConstraints = parts.at(0);
     QList<AnchorData *> trunkVariables = getVariables(trunkConstraints);
     // For minimum and maximum, use the path between the two layout sides as the
     // objective function.
     AnchorVertex *v = layoutLastVertex[orientation];
     GraphPath trunkPath = graphPaths[orientation].value(v);
     bool feasible = calculateTrunk(orientation, trunkPath, trunkConstraints, trunkVariables);
     // For the other parts that not the trunk, solve only for the preferred size
     // that is the size they will remain at, since they are not stretched by the
     // layout.
     // Skipping the first (trunk)
     for (int i = 1; i < parts.count(); ++i) {
         if (!feasible)
             break;
         QList<QSimplexConstraint *> partConstraints = parts.at(i);
         QList<AnchorData *> partVariables = getVariables(partConstraints);
         Q_ASSERT(!partVariables.isEmpty());
         feasible &= calculateNonTrunk(partConstraints, partVariables);
     }
     // Propagate the new sizes down the simplified graph, ie. tell the
     // group anchors to set their children anchors sizes.
     updateAnchorSizes(orientation);
     graphHasConflicts[orientation] = !feasible;
     // Clean up our data structures. They are not needed anymore since
     // distribution uses just interpolation.
     qDeleteAll(constraints[orientation]);
     constraints[orientation].clear();
     graphPaths[orientation].clear(); // ###
     if (simplificationEnabled)
         restoreSimplifiedGraph(orientation);
 }
calculateNonTrunk()
bool QGraphicsAnchorLayoutPrivate::calculateNonTrunk (const QList< QSimplexConstraint *> & constraints, const QList< AnchorData *> & variables)
Warning
This function is not part of the public interface.
Definition at line 2319 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     shiftConstraints(constraints, g_offset);
     bool feasible = solvePreferred(constraints, variables);
     if (feasible) {
         // Propagate size at preferred to other sizes. Semi-floats always will be
         // in their sizeAtPreferred.
         for (int j = 0; j < variables.count(); ++j) {
             AnchorData *ad = variables.at(j);
             Q_ASSERT(ad);
             ad->sizeAtMinimum = ad->sizeAtPreferred;
             ad->sizeAtMaximum = ad->sizeAtPreferred;
         }
     }
     shiftConstraints(constraints, -g_offset);
     return feasible;
 }
calculateTrunk()
bool QGraphicsAnchorLayoutPrivate::calculateTrunk (Orientation orientation, const GraphPath & path, const QList< QSimplexConstraint *> & constraints, const QList< AnchorData *> & variables)
Calculate the sizes for all anchors which are part of the trunk.
Warning
This function is not part of the public interface.
This works on top of a (possibly) simplified graph.
Definition at line 2249 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     bool feasible = true;
     bool needsSimplex = !constraints.isEmpty();
 #if 0
     qDebug("Simplex %s for trunk of %s", needsSimplex ? "used" : "NOT used",
            orientation == Horizontal ? "Horizontal" : "Vertical");
 #endif
     if (needsSimplex) {
         QList<QSimplexConstraint *> sizeHintConstraints = constraintsFromSizeHints(variables);
         QList<QSimplexConstraint *> allConstraints = constraints + sizeHintConstraints;
         shiftConstraints(allConstraints, g_offset);
         // Solve min and max size hints
         qreal min, max;
         feasible = solveMinMax(allConstraints, path, &min, &max);
         if (feasible) {
             solvePreferred(constraints, variables);
             // Calculate and set the preferred size for the layout,
             // from the edge sizes that were calculated above.
             qreal pref(0.0);
             foreach (const AnchorData *ad, path.positives) {
                 pref += ad->sizeAtPreferred;
             }
             foreach (const AnchorData *ad, path.negatives) {
                 pref -= ad->sizeAtPreferred;
             }
             sizeHints[orientation][Qt::MinimumSize] = min;
             sizeHints[orientation][Qt::PreferredSize] = pref;
             sizeHints[orientation][Qt::MaximumSize] = max;
         }
         qDeleteAll(sizeHintConstraints);
         shiftConstraints(constraints, -g_offset);
     } else {
         // No Simplex is necessary because the path was simplified all the way to a single
         // anchor.
         Q_ASSERT(path.positives.count() == 1);
         Q_ASSERT(path.negatives.count() == 0);
         AnchorData *ad = path.positives.toList()[0];
         ad->sizeAtMinimum = ad->minSize;
         ad->sizeAtPreferred = ad->prefSize;
         ad->sizeAtMaximum = ad->maxSize;
         sizeHints[orientation][Qt::MinimumSize] = ad->sizeAtMinimum;
         sizeHints[orientation][Qt::PreferredSize] = ad->sizeAtPreferred;
         sizeHints[orientation][Qt::MaximumSize] = ad->sizeAtMaximum;
     }
 #if defined(QT_DEBUG) || defined(Q_AUTOTEST_EXPORT)
     lastCalculationUsedSimplex[orientation] = needsSimplex;
 #endif
     return feasible;
 }
calculateVertexPositions()
void QGraphicsAnchorLayoutPrivate::calculateVertexPositions (QGraphicsAnchorLayoutPrivate::Orientation orientation)
Calculate the position of each vertex based on the paths to each of them as well as the current edges sizes.
Warning
This function is not part of the public interface.
Definition at line 2769 of file qgraphicsanchorlayout_p.cpp.
 {
     QQueue<QPair<AnchorVertex *, AnchorVertex *> > queue;
     QSet<AnchorVertex *> visited;
     // Get root vertex
     AnchorVertex *root = layoutFirstVertex[orientation];
     root->distance = 0;
     visited.insert(root);
     // Add initial edges to the queue
     foreach (AnchorVertex *v, graph[orientation].adjacentVertices(root)) {
         queue.enqueue(qMakePair(root, v));
     }
     // Do initial calculation required by "interpolateEdge()"
     setupEdgesInterpolation(orientation);
     // Traverse the graph and calculate vertex positions
     while (!queue.isEmpty()) {
         QPair<AnchorVertex *, AnchorVertex *> pair = queue.dequeue();
         AnchorData *edge = graph[orientation].edgeData(pair.first, pair.second);
         if (visited.contains(pair.second))
             continue;
         visited.insert(pair.second);
         interpolateEdge(pair.first, edge);
         QList<AnchorVertex *> adjacents = graph[orientation].adjacentVertices(pair.second);
         for (int i = 0; i < adjacents.count(); ++i) {
             if (!visited.contains(adjacents.at(i)))
                 queue.enqueue(qMakePair(pair.second, adjacents.at(i)));
         }
     }
 }
changeLayoutVertex()
void QGraphicsAnchorLayoutPrivate::changeLayoutVertex (Orientation orientation, AnchorVertex * oldV, AnchorVertex * newV) inline
Definition at line 520 of file qgraphicsanchorlayout_p.h.
Referenced by restoreVertices(), and simplifyVertices().
     {
         if (layoutFirstVertex[orientation] == oldV)
             layoutFirstVertex[orientation] = newV;
         else if (layoutCentralVertex[orientation] == oldV)
             layoutCentralVertex[orientation] = newV;
         else if (layoutLastVertex[orientation] == oldV)
             layoutLastVertex[orientation] = newV;
     }
constraintsFromPaths()
void QGraphicsAnchorLayoutPrivate::constraintsFromPaths (Orientation orientation)
Each vertex on the graph that has more than one path to it represents a contra int to the sizes of the items in these paths.
Warning
This function is not part of the public interface.
This method walks the list of paths to each vertex, generate the constraints and store them in a list so they can be used later by the Simplex solver.
Definition at line 2430 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     foreach (AnchorVertex *vertex, graphPaths[orientation].uniqueKeys())
     {
         int valueCount = graphPaths[orientation].count(vertex);
         if (valueCount == 1)
             continue;
         QList<GraphPath> pathsToVertex = graphPaths[orientation].values(vertex);
         for (int i = 1; i < valueCount; ++i) {
             constraints[orientation] += \
                 pathsToVertex[0].constraint(pathsToVertex.at(i));
         }
     }
 }
constraintsFromSizeHints()
QList< QSimplexConstraint * > QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints (const QList< AnchorData *> & anchors)
Warning
This function is not part of the public interface.
Create LP constraints for each anchor based on its minimum and maximum sizes, as specified in its size hints
Definition at line 2466 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateTrunk().
 {
     if (anchors.isEmpty())
         return QList<QSimplexConstraint *>();
     // Look for the layout edge. That can be either the first half in case the
     // layout is split in two, or the whole layout anchor.
     Orientation orient = Orientation(anchors.first()->orientation);
     AnchorData *layoutEdge = 0;
     if (layoutCentralVertex[orient]) {
         layoutEdge = graph[orient].edgeData(layoutFirstVertex[orient], layoutCentralVertex[orient]);
     } else {
         layoutEdge = graph[orient].edgeData(layoutFirstVertex[orient], layoutLastVertex[orient]);
     }
     // If maxSize is less then "infinite", that means there are other anchors
     // grouped together with this one. We can't ignore its maximum value so we
     // set back the variable to NULL to prevent the continue condition from being
     // satisfied in the loop below.
     const qreal expectedMax = layoutCentralVertex[orient] ? QWIDGETSIZE_MAX / 2 : QWIDGETSIZE_MAX;
     qreal actualMax;
     if (layoutEdge->from == layoutFirstVertex[orient]) {
         actualMax = layoutEdge->maxSize;
     } else {
         actualMax = -layoutEdge->minSize;
     }
     if (actualMax != expectedMax) {
         layoutEdge = 0;
     }
     // For each variable, create constraints based on size hints
     QList<QSimplexConstraint *> anchorConstraints;
     bool unboundedProblem = true;
     for (int i = 0; i < anchors.size(); ++i) {
         AnchorData *ad = anchors.at(i);
         // Anchors that have their size directly linked to another one don't need constraints
         // For exammple, the second half of an item has exactly the same size as the first half
         // thus constraining the latter is enough.
         if (ad->dependency == AnchorData::Slave)
             continue;
         // To use negative variables inside simplex, we shift them so the minimum negative value is
         // mapped to zero before solving. To make sure that it works, we need to guarantee that the
         // variables are all inside a certain boundary.
         qreal boundedMin = qBound(-g_offset, ad->minSize, g_offset);
         qreal boundedMax = qBound(-g_offset, ad->maxSize, g_offset);
         if ((boundedMin == boundedMax) || qFuzzyCompare(boundedMin, boundedMax)) {
             QSimplexConstraint *c = new QSimplexConstraint;
             c->variables.insert(ad, 1.0);
             c->constant = boundedMin;
             c->ratio = QSimplexConstraint::Equal;
             anchorConstraints += c;
             unboundedProblem = false;
         } else {
             QSimplexConstraint *c = new QSimplexConstraint;
             c->variables.insert(ad, 1.0);
             c->constant = boundedMin;
             c->ratio = QSimplexConstraint::MoreOrEqual;
             anchorConstraints += c;
             // We avoid adding restrictions to the layout internal anchors. That's
             // to prevent unnecessary fair distribution from happening due to this
             // artificial restriction.
             if (ad == layoutEdge)
                 continue;
             c = new QSimplexConstraint;
             c->variables.insert(ad, 1.0);
             c->constant = boundedMax;
             c->ratio = QSimplexConstraint::LessOrEqual;
             anchorConstraints += c;
             unboundedProblem = false;
         }
     }
     // If no upper boundary restriction was added, add one to avoid unbounded problem
     if (unboundedProblem) {
         QSimplexConstraint *c = new QSimplexConstraint;
         c->variables.insert(layoutEdge, 1.0);
         // The maximum size that the layout can take
         c->constant = g_offset;
         c->ratio = QSimplexConstraint::LessOrEqual;
         anchorConstraints += c;
     }
     return anchorConstraints;
 }
correctEdgeDirection()
void QGraphicsAnchorLayoutPrivate::correctEdgeDirection (QGraphicsLayoutItem *& firstItem, Qt::AnchorPoint & firstEdge, QGraphicsLayoutItem *& secondItem, Qt::AnchorPoint & secondEdge)
Use heuristics to determine the correct orientation of a given anchor.
Warning
This function is not part of the public interface.
After API discussions, we decided we would like expressions like anchor(A, Left, B, Right) to mean the same as anchor(B, Right, A, Left). The problem with this is that anchors could become ambiguous, for instance, what does the anchor A, B of size X mean?
"pos(B) = pos(A) + X" or "pos(A) = pos(B) + X" ?
To keep the API user friendly and at the same time, keep our algorithm deterministic, we use an heuristic to determine a direction for each added anchor and then keep it. The heuristic is based on the fact that people usually avoid overlapping items, therefore:
"A, RIGHT to B, LEFT" means that B is to the LEFT of A. "B, LEFT to A, RIGHT" is corrected to the above anchor.
Special correction is also applied when one of the items is the layout. We handle Layout Left as if it was another items's Right and Layout Right as another item's Left.
Definition at line 2020 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor().
 {
     Q_Q(QGraphicsAnchorLayout);
     if ((firstItem != q) && (secondItem != q)) {
         // If connection is between widgets (not the layout itself)
         // Ensure that "right-edges" sit to the left of "left-edges".
         if (firstEdge < secondEdge) {
             qSwap(firstItem, secondItem);
             qSwap(firstEdge, secondEdge);
         }
     } else if (firstItem == q) {
         // If connection involves the right or bottom of a layout, ensure
         // the layout is the second item.
         if ((firstEdge == Qt::AnchorRight) || (firstEdge == Qt::AnchorBottom)) {
             qSwap(firstItem, secondItem);
             qSwap(firstEdge, secondEdge);
         }
     } else if ((secondEdge != Qt::AnchorRight) && (secondEdge != Qt::AnchorBottom)) {
         // If connection involves the left, center or top of layout, ensure
         // the layout is the first item.
         qSwap(firstItem, secondItem);
         qSwap(firstEdge, secondEdge);
     }
 }
createCenterAnchors()
void QGraphicsAnchorLayoutPrivate::createCenterAnchors (QGraphicsLayoutItem * item, Qt::AnchorPoint centerEdge)
By default, each item in the layout is represented internally as a single anchor in each direction.
Warning
This function is not part of the public interface.
For instance, from Left to Right.
However, to support anchorage of items to the center of items, we must split this internal anchor into two half-anchors. From Left to Center and then from Center to Right, with the restriction that these anchors must have the same time at all times.
Definition at line 1471 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor().
 {
     Q_Q(QGraphicsAnchorLayout);
     Orientation orientation;
     switch (centerEdge) {
     case Qt::AnchorHorizontalCenter:
         orientation = Horizontal;
         break;
     case Qt::AnchorVerticalCenter:
         orientation = Vertical;
         break;
     default:
         // Don't create center edges unless needed
         return;
     }
     // Check if vertex already exists
     if (internalVertex(item, centerEdge))
         return;
     // Orientation code
     Qt::AnchorPoint firstEdge;
     Qt::AnchorPoint lastEdge;
     if (orientation == Horizontal) {
         firstEdge = Qt::AnchorLeft;
         lastEdge = Qt::AnchorRight;
     } else {
         firstEdge = Qt::AnchorTop;
         lastEdge = Qt::AnchorBottom;
     }
     AnchorVertex *first = internalVertex(item, firstEdge);
     AnchorVertex *last = internalVertex(item, lastEdge);
     Q_ASSERT(first && last);
     // Create new anchors
     QSimplexConstraint *c = new QSimplexConstraint;
     AnchorData *data = new AnchorData;
     c->variables.insert(data, 1.0);
     addAnchor_helper(item, firstEdge, item, centerEdge, data);
     data->isCenterAnchor = true;
     data->dependency = AnchorData::Master;
     data->refreshSizeHints();
     data = new AnchorData;
     c->variables.insert(data, -1.0);
     addAnchor_helper(item, centerEdge, item, lastEdge, data);
     data->isCenterAnchor = true;
     data->dependency = AnchorData::Slave;
     data->refreshSizeHints();
     itemCenterConstraints[orientation].append(c);
     // Remove old one
     removeAnchor_helper(first, last);
     if (item == q) {
         layoutCentralVertex[orientation] = internalVertex(q, centerEdge);
     }
 }
createItemEdges()
void QGraphicsAnchorLayoutPrivate::createItemEdges (QGraphicsLayoutItem * item)
Definition at line 1442 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor().
 {
     items.append(item);
     // Create horizontal and vertical internal anchors for the item and
     // refresh its size hint / policy values.
     AnchorData *data = new AnchorData;
     addAnchor_helper(item, Qt::AnchorLeft, item, Qt::AnchorRight, data);
     data->refreshSizeHints();
     data = new AnchorData;
     addAnchor_helper(item, Qt::AnchorTop, item, Qt::AnchorBottom, data);
     data->refreshSizeHints();
 }
createLayoutEdges()
void QGraphicsAnchorLayoutPrivate::createLayoutEdges ()
Create internal anchors to connect the layout edges (Left to Right and Top to Bottom).
Warning
This function is not part of the public interface.
These anchors doesn't have size restrictions, that will be enforced by other anchors and items in the layout.
Definition at line 1401 of file qgraphicsanchorlayout_p.cpp.
 {
     Q_Q(QGraphicsAnchorLayout);
     QGraphicsLayoutItem *layout = q;
     // Horizontal
     AnchorData *data = new AnchorData;
     addAnchor_helper(layout, Qt::AnchorLeft, layout,
                      Qt::AnchorRight, data);
     data->maxSize = QWIDGETSIZE_MAX;
     // Save a reference to layout vertices
     layoutFirstVertex[Horizontal] = internalVertex(layout, Qt::AnchorLeft);
     layoutCentralVertex[Horizontal] = 0;
     layoutLastVertex[Horizontal] = internalVertex(layout, Qt::AnchorRight);
     // Vertical
     data = new AnchorData;
     addAnchor_helper(layout, Qt::AnchorTop, layout,
                      Qt::AnchorBottom, data);
     data->maxSize = QWIDGETSIZE_MAX;
     // Save a reference to layout vertices
     layoutFirstVertex[Vertical] = internalVertex(layout, Qt::AnchorTop);
     layoutCentralVertex[Vertical] = 0;
     layoutLastVertex[Vertical] = internalVertex(layout, Qt::AnchorBottom);
 }
deleteLayoutEdges()
void QGraphicsAnchorLayoutPrivate::deleteLayoutEdges ()
Definition at line 1429 of file qgraphicsanchorlayout_p.cpp.
 {
     Q_Q(QGraphicsAnchorLayout);
     Q_ASSERT(!internalVertex(q, Qt::AnchorHorizontalCenter));
     Q_ASSERT(!internalVertex(q, Qt::AnchorVerticalCenter));
     removeAnchor_helper(internalVertex(q, Qt::AnchorLeft),
                         internalVertex(q, Qt::AnchorRight));
     removeAnchor_helper(internalVertex(q, Qt::AnchorTop),
                         internalVertex(q, Qt::AnchorBottom));
 }
dumpGraph()
void QGraphicsAnchorLayoutPrivate::dumpGraph (const QString & name = QString())
Definition at line 3063 of file qgraphicsanchorlayout_p.cpp.
Referenced by simplifyGraph().
 {
     QFile file(QString::fromAscii("anchorlayout.%1.dot").arg(name));
     if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate))
         qWarning("Could not write to %s", file.fileName().toLocal8Bit().constData());
     QString str = QString::fromAscii("digraph anchorlayout {\nnode [shape=\"rect\"]\n%1}");
     QString dotContents = graph[0].serializeToDot();
     dotContents += graph[1].serializeToDot();
     file.write(str.arg(dotContents).toLocal8Bit());
     file.close();
 }
edgeOrientation()
QGraphicsAnchorLayoutPrivate::Orientation QGraphicsAnchorLayoutPrivate::edgeOrientation (Qt::AnchorPoint edge) static
Definition at line 1384 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor(), addAnchor_helper(), getAnchor(), AnchorData::refreshSizeHints(), removeAnchor_helper(), and removeVertex().
 {
     return edge > Qt::AnchorRight ? Vertical : Horizontal;
 }
findPaths()
void QGraphicsAnchorLayoutPrivate::findPaths (Orientation orientation)
This method walks the graph using a breadth-first search to find paths between the root vertex and each vertex on the graph.
Warning
This function is not part of the public interface.
The edges directions in each path are considered and they are stored as a positive edge (left-to-right) or negative edge (right-to-left).
The list of paths is used later to generate a list of constraints.
Definition at line 2374 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     QQueue<QPair<AnchorVertex *, AnchorVertex *> > queue;
     QSet<AnchorData *> visited;
     AnchorVertex *root = layoutFirstVertex[orientation];
     graphPaths[orientation].insert(root, GraphPath());
     foreach (AnchorVertex *v, graph[orientation].adjacentVertices(root)) {
         queue.enqueue(qMakePair(root, v));
     }
     while(!queue.isEmpty()) {
         QPair<AnchorVertex *, AnchorVertex *>  pair = queue.dequeue();
         AnchorData *edge = graph[orientation].edgeData(pair.first, pair.second);
         if (visited.contains(edge))
             continue;
         visited.insert(edge);
         GraphPath current = graphPaths[orientation].value(pair.first);
         if (edge->from == pair.first)
             current.positives.insert(edge);
         else
             current.negatives.insert(edge);
         graphPaths[orientation].insert(pair.second, current);
         foreach (AnchorVertex *v,
                 graph[orientation].adjacentVertices(pair.second)) {
             queue.enqueue(qMakePair(pair.second, v));
         }
     }
     // We will walk through every reachable items (non-float) store them in a temporary set.
     // We them create a set of all items and subtract the non-floating items from the set in
     // order to get the floating items. The floating items is then stored in m_floatItems
     identifyFloatItems(visited, orientation);
 }
get()
static QGraphicsAnchorLayoutPrivate* QGraphicsAnchorLayoutPrivate::get (QGraphicsAnchorLayout * q) inline static
Definition at line 405 of file qgraphicsanchorlayout_p.h.
     {
         return q ? q->d_func() : 0;
     }
getAnchor()
QGraphicsAnchor * QGraphicsAnchorLayoutPrivate::getAnchor (QGraphicsLayoutItem * firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem * secondItem, Qt::AnchorPoint secondEdge)
Definition at line 1796 of file qgraphicsanchorlayout_p.cpp.
 {
     // Do not expose internal anchors
     if (firstItem == secondItem)
         return 0;
     const Orientation orientation = edgeOrientation(firstEdge);
     AnchorVertex *v1 = internalVertex(firstItem, firstEdge);
     AnchorVertex *v2 = internalVertex(secondItem, secondEdge);
     QGraphicsAnchor *graphicsAnchor = 0;
     AnchorData *data = graph[orientation].edgeData(v1, v2);
     if (data) {
         // We could use "acquireGraphicsAnchor" here, but to avoid a regression where
         // an internal anchor was wrongly exposed, I want to ensure no new
         // QGraphicsAnchor instances are created by this call.
         // This assumption must hold because anchors are either user-created (and already
         // have their public object created), or they are internal (and must not reach
         // this point).
         Q_ASSERT(data->graphicsAnchor);
         graphicsAnchor = data->graphicsAnchor;
     }
     return graphicsAnchor;
 }
getGraphParts()
QList< QList< QSimplexConstraint * > > QGraphicsAnchorLayoutPrivate::getGraphParts (Orientation orientation)
Warning
This function is not part of the public interface.
Definition at line 2561 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     Q_ASSERT(layoutFirstVertex[orientation] && layoutLastVertex[orientation]);
     AnchorData *edgeL1 = 0;
     AnchorData *edgeL2 = 0;
     // The layout may have a single anchor between Left and Right or two half anchors
     // passing through the center
     if (layoutCentralVertex[orientation]) {
         edgeL1 = graph[orientation].edgeData(layoutFirstVertex[orientation], layoutCentralVertex[orientation]);
         edgeL2 = graph[orientation].edgeData(layoutCentralVertex[orientation], layoutLastVertex[orientation]);
     } else {
         edgeL1 = graph[orientation].edgeData(layoutFirstVertex[orientation], layoutLastVertex[orientation]);
     }
     QLinkedList<QSimplexConstraint *> remainingConstraints;
     for (int i = 0; i < constraints[orientation].count(); ++i) {
         remainingConstraints += constraints[orientation].at(i);
     }
     for (int i = 0; i < itemCenterConstraints[orientation].count(); ++i) {
         remainingConstraints += itemCenterConstraints[orientation].at(i);
     }
     QList<QSimplexConstraint *> trunkConstraints;
     QSet<QSimplexVariable *> trunkVariables;
     trunkVariables += edgeL1;
     if (edgeL2)
         trunkVariables += edgeL2;
     bool dirty;
     do {
         dirty = false;
         QLinkedList<QSimplexConstraint *>::iterator it = remainingConstraints.begin();
         while (it != remainingConstraints.end()) {
             QSimplexConstraint *c = *it;
             bool match = false;
             // Check if this constraint have some overlap with current
             // trunk variables...
             foreach (QSimplexVariable *ad, trunkVariables) {
                 if (c->variables.contains(ad)) {
                     match = true;
                     break;
                 }
             }
             // If so, we add it to trunk, and erase it from the
             // remaining constraints.
             if (match) {
                 trunkConstraints += c;
                 trunkVariables += QSet<QSimplexVariable *>::fromList(c->variables.keys());
                 it = remainingConstraints.erase(it);
                 dirty = true;
             } else {
                 // Note that we don't erase the constraint if it's not
                 // a match, since in a next iteration of a do-while we
                 // can pass on it again and it will be a match.
                 //
                 // For example: if trunk share a variable with
                 // remainingConstraints[1] and it shares with
                 // remainingConstraints[0], we need a second iteration
                 // of the do-while loop to match both.
                 ++it;
             }
         }
     } while (dirty);
     QList< QList<QSimplexConstraint *> > result;
     result += trunkConstraints;
     if (!remainingConstraints.isEmpty()) {
         QList<QSimplexConstraint *> nonTrunkConstraints;
         QLinkedList<QSimplexConstraint *>::iterator it = remainingConstraints.begin();
         while (it != remainingConstraints.end()) {
             nonTrunkConstraints += *it;
             ++it;
         }
         result += nonTrunkConstraints;
     }
     return result;
 }
hasConflicts()
bool QGraphicsAnchorLayoutPrivate::hasConflicts () const
Returns true if there are no arrangement that satisfies all constraints.
Warning
This function is not part of the public interface.
Otherwise returns false.
See also
addAnchor()
Definition at line 3052 of file qgraphicsanchorlayout_p.cpp.
 {
     QGraphicsAnchorLayoutPrivate *that = const_cast<QGraphicsAnchorLayoutPrivate*>(this);
     that->calculateGraphs();
     bool floatConflict = !m_floatItems[0].isEmpty() || !m_floatItems[1].isEmpty();
     return graphHasConflicts[0] || graphHasConflicts[1] || floatConflict;
 }
identifyFloatItems()
void QGraphicsAnchorLayoutPrivate::identifyFloatItems (const QSet< AnchorData *> & visited, Orientation orientation)
Use all visited Anchors on findPaths() so we can identify non-float Items.
Warning
This function is not part of the public interface.
Definition at line 2655 of file qgraphicsanchorlayout_p.cpp.
Referenced by findPaths().
 {
     QSet<QGraphicsLayoutItem *> nonFloating;
     foreach (const AnchorData *ad, visited)
         identifyNonFloatItems_helper(ad, &nonFloating);
     QSet<QGraphicsLayoutItem *> allItems;
     foreach (QGraphicsLayoutItem *item, items)
         allItems.insert(item);
     m_floatItems[orientation] = allItems - nonFloating;
 }
identifyNonFloatItems_helper()
void QGraphicsAnchorLayoutPrivate::identifyNonFloatItems_helper (const AnchorData * ad, QSet< QGraphicsLayoutItem *> * nonFloatingItemsIdentifiedSoFar)
Given an anchor, if it is an internal anchor and Normal we must mark it's item as non-float.
Warning
This function is not part of the public interface.
If the anchor is Sequential or Parallel, we must iterate on its children recursively until we reach internal anchors (items).
Definition at line 2679 of file qgraphicsanchorlayout_p.cpp.
Referenced by identifyFloatItems().
 {
     Q_Q(QGraphicsAnchorLayout);
     switch(ad->type) {
     case AnchorData::Normal:
         if (ad->item && ad->item != q)
             nonFloatingItemsIdentifiedSoFar->insert(ad->item);
         break;
     case AnchorData::Sequential:
         foreach (const AnchorData *d, static_cast<const SequentialAnchorData *>(ad)->m_edges)
             identifyNonFloatItems_helper(d, nonFloatingItemsIdentifiedSoFar);
         break;
     case AnchorData::Parallel:
         identifyNonFloatItems_helper(static_cast<const ParallelAnchorData *>(ad)->firstEdge, nonFloatingItemsIdentifiedSoFar);
         identifyNonFloatItems_helper(static_cast<const ParallelAnchorData *>(ad)->secondEdge, nonFloatingItemsIdentifiedSoFar);
         break;
     }
 }
internalVertex() [1/2]
AnchorVertex* QGraphicsAnchorLayoutPrivate::internalVertex (const QPair< QGraphicsLayoutItem *, Qt::AnchorPoint > & itemEdge) const inline
Definition at line 510 of file qgraphicsanchorlayout_p.h.
Referenced by createCenterAnchors(), createLayoutEdges(), deleteLayoutEdges(), getAnchor(), removeCenterAnchors(), removeCenterConstraints(), removeVertex(), and setItemsGeometries().
     {
         return m_vertexList.value(itemEdge).first;
     }
internalVertex() [2/2]
AnchorVertex* QGraphicsAnchorLayoutPrivate::internalVertex (const QGraphicsLayoutItem * item, Qt::AnchorPoint edge) const inline
Definition at line 515 of file qgraphicsanchorlayout_p.h.
     {
         return internalVertex(qMakePair(const_cast<QGraphicsLayoutItem *>(item), edge));
     }
interpolateEdge()
void QGraphicsAnchorLayoutPrivate::interpolateEdge (AnchorVertex * base, AnchorData * edge)
Calculate the current Edge size based on the current Layout size and the size the edge is supposed to have when the layout is at its:
minimum size,
preferred size,
maximum size.
Warning
This function is not part of the public interface.
These three key values are calculated in advance using linear programming (more expensive) or the simplification algorithm, then subsequential resizes of the parent layout require a simple interpolation.
Definition at line 2856 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateVertexPositions().
 {
     const Orientation orientation = Orientation(edge->orientation);
     const QPair<Interval, qreal> factor(interpolationInterval[orientation],
                                         interpolationProgress[orientation]);
     qreal edgeDistance = interpolate(factor, edge->sizeAtMinimum, edge->sizeAtPreferred,
                                      edge->sizeAtPreferred, edge->sizeAtPreferred,
                                      edge->sizeAtMaximum);
     Q_ASSERT(edge->from == base || edge->to == base);
     // Calculate the distance for the vertex opposite to the base
     if (edge->from == base) {
         edge->to->distance = base->distance + edgeDistance;
     } else {
         edge->from->distance = base->distance - edgeDistance;
     }
 }
oppositeEdge()
Qt::AnchorPoint QGraphicsAnchorLayoutPrivate::oppositeEdge (Qt::AnchorPoint edge) static
Definition at line 641 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor().
 {
     switch (edge) {
     case Qt::AnchorLeft:
         edge = Qt::AnchorRight;
         break;
     case Qt::AnchorRight:
         edge = Qt::AnchorLeft;
         break;
     case Qt::AnchorTop:
         edge = Qt::AnchorBottom;
         break;
     case Qt::AnchorBottom:
         edge = Qt::AnchorTop;
         break;
     default:
         break;
     }
     return edge;
 }
pickEdge()
static Qt::AnchorPoint QGraphicsAnchorLayoutPrivate::pickEdge (Qt::AnchorPoint edge, Orientation orientation) inline static
Definition at line 415 of file qgraphicsanchorlayout_p.h.
Referenced by addAnchor().
     {
         if (orientation == Vertical && int(edge) <= 2)
             return (Qt::AnchorPoint)(edge + 3);
         else if (orientation == Horizontal && int(edge) >= 3) {
             return (Qt::AnchorPoint)(edge - 3);
         }
         return edge;
     }
refreshAllSizeHints()
void QGraphicsAnchorLayoutPrivate::refreshAllSizeHints (Orientation orientation)
Traverse the graph refreshing the size hints.
Warning
This function is not part of the public interface.
Edges will query their associated item or graphicsAnchor for their size hints.
Definition at line 2349 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     QList<QPair<AnchorVertex *, AnchorVertex *> > vertices = g.connections();
     QLayoutStyleInfo styleInf = styleInfo();
     for (int i = 0; i < vertices.count(); ++i) {
         AnchorData *data = g.edgeData(vertices.at(i).first, vertices.at(i).second);
         data->refreshSizeHints(&styleInf);
     }
 }
removeAnchor()
void QGraphicsAnchorLayoutPrivate::removeAnchor (AnchorVertex * firstVertex, AnchorVertex * secondVertex)
Warning
This function is not part of the public interface.
Implements the high level "removeAnchor" feature. Called by the QAnchorData destructor.
Definition at line 1831 of file qgraphicsanchorlayout_p.cpp.
Referenced by QGraphicsAnchorPrivate::~QGraphicsAnchorPrivate().
 {
     Q_Q(QGraphicsAnchorLayout);
     // Save references to items while it's safe to assume the vertices exist
     QGraphicsLayoutItem *firstItem = firstVertex->m_item;
     QGraphicsLayoutItem *secondItem = secondVertex->m_item;
     // Delete the anchor (may trigger deletion of center vertices)
     removeAnchor_helper(firstVertex, secondVertex);
     // Ensure no dangling pointer is left behind
     firstVertex = secondVertex = 0;
     // Checking if the item stays in the layout or not
     bool keepFirstItem = false;
     bool keepSecondItem = false;
     QPair<AnchorVertex *, int> v;
     int refcount = -1;
     if (firstItem != q) {
         for (int i = Qt::AnchorLeft; i <= Qt::AnchorBottom; ++i) {
             v = m_vertexList.value(qMakePair(firstItem, static_cast<Qt::AnchorPoint>(i)));
             if (v.first) {
                 if (i == Qt::AnchorHorizontalCenter || i == Qt::AnchorVerticalCenter)
                     refcount = 2;
                 else
                     refcount = 1;
                 if (v.second > refcount) {
                     keepFirstItem = true;
                     break;
                 }
             }
         }
     } else
         keepFirstItem = true;
     if (secondItem != q) {
         for (int i = Qt::AnchorLeft; i <= Qt::AnchorBottom; ++i) {
             v = m_vertexList.value(qMakePair(secondItem, static_cast<Qt::AnchorPoint>(i)));
             if (v.first) {
                 if (i == Qt::AnchorHorizontalCenter || i == Qt::AnchorVerticalCenter)
                     refcount = 2;
                 else
                     refcount = 1;
                 if (v.second > refcount) {
                     keepSecondItem = true;
                     break;
                 }
             }
         }
     } else
         keepSecondItem = true;
     if (!keepFirstItem)
         q->removeAt(items.indexOf(firstItem));
     if (!keepSecondItem)
         q->removeAt(items.indexOf(secondItem));
     // Removing anchors invalidates the layout
     q->invalidate();
 }
removeAnchor_helper()
void QGraphicsAnchorLayoutPrivate::removeAnchor_helper (AnchorVertex * v1, AnchorVertex * v2)
Definition at line 1905 of file qgraphicsanchorlayout_p.cpp.
Referenced by addAnchor_helper(), createCenterAnchors(), deleteLayoutEdges(), removeAnchor(), and removeCenterAnchors().
 {
     Q_ASSERT(v1 && v2);
     // Remove edge from graph
     const Orientation o = edgeOrientation(v1->m_edge);
     graph[o].removeEdge(v1, v2);
     // Decrease vertices reference count (may trigger a deletion)
     removeInternalVertex(v1->m_item, v1->m_edge);
     removeInternalVertex(v2->m_item, v2->m_edge);
 }
removeAnchors()
void QGraphicsAnchorLayoutPrivate::removeAnchors (QGraphicsLayoutItem * item)
Definition at line 1981 of file qgraphicsanchorlayout_p.cpp.
 {
     // remove the center anchor first!!
     removeCenterAnchors(item, Qt::AnchorHorizontalCenter, false);
     removeVertex(item, Qt::AnchorLeft);
     removeVertex(item, Qt::AnchorRight);
     removeCenterAnchors(item, Qt::AnchorVerticalCenter, false);
     removeVertex(item, Qt::AnchorTop);
     removeVertex(item, Qt::AnchorBottom);
 }
removeCenterAnchors()
void QGraphicsAnchorLayoutPrivate::removeCenterAnchors (QGraphicsLayoutItem * item, Qt::AnchorPoint centerEdge, bool substitute = true)
Definition at line 1536 of file qgraphicsanchorlayout_p.cpp.
Referenced by removeAnchors(), and removeInternalVertex().
 {
     Q_Q(QGraphicsAnchorLayout);
     Orientation orientation;
     switch (centerEdge) {
     case Qt::AnchorHorizontalCenter:
         orientation = Horizontal;
         break;
     case Qt::AnchorVerticalCenter:
         orientation = Vertical;
         break;
     default:
         // Don't remove edges that not the center ones
         return;
     }
     // Orientation code
     Qt::AnchorPoint firstEdge;
     Qt::AnchorPoint lastEdge;
     if (orientation == Horizontal) {
         firstEdge = Qt::AnchorLeft;
         lastEdge = Qt::AnchorRight;
     } else {
         firstEdge = Qt::AnchorTop;
         lastEdge = Qt::AnchorBottom;
     }
     AnchorVertex *center = internalVertex(item, centerEdge);
     if (!center)
         return;
     AnchorVertex *first = internalVertex(item, firstEdge);
     Q_ASSERT(first);
     Q_ASSERT(center);
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     AnchorData *oldData = g.edgeData(first, center);
     // Remove center constraint
     for (int i = itemCenterConstraints[orientation].count() - 1; i >= 0; --i) {
         if (itemCenterConstraints[orientation].at(i)->variables.contains(oldData)) {
             delete itemCenterConstraints[orientation].takeAt(i);
             break;
         }
     }
     if (substitute) {
         // Create the new anchor that should substitute the left-center-right anchors.
         AnchorData *data = new AnchorData;
         addAnchor_helper(item, firstEdge, item, lastEdge, data);
         data->refreshSizeHints();
         // Remove old anchors
         removeAnchor_helper(first, center);
         removeAnchor_helper(center, internalVertex(item, lastEdge));
     } else {
         // this is only called from removeAnchors()
         // first, remove all non-internal anchors
         QList<AnchorVertex*> adjacents = g.adjacentVertices(center);
         for (int i = 0; i < adjacents.count(); ++i) {
             AnchorVertex *v = adjacents.at(i);
             if (v->m_item != item) {
                 removeAnchor_helper(center, internalVertex(v->m_item, v->m_edge));
             }
         }
         // when all non-internal anchors is removed it will automatically merge the
         // center anchor into a left-right (or top-bottom) anchor. We must also delete that.
         // by this time, the center vertex is deleted and merged into a non-centered internal anchor
         removeAnchor_helper(first, internalVertex(item, lastEdge));
     }
     if (item == q) {
         layoutCentralVertex[orientation] = 0;
     }
 }
removeCenterConstraints()
void QGraphicsAnchorLayoutPrivate::removeCenterConstraints (QGraphicsLayoutItem * item, Orientation orientation)
Definition at line 1619 of file qgraphicsanchorlayout_p.cpp.
 {
     // Remove the item center constraints associated to this item
     // ### This is a temporary solution. We should probably use a better
     // data structure to hold items and/or their associated constraints
     // so that we can remove those easily
     AnchorVertex *first = internalVertex(item, orientation == Horizontal ?
                                        Qt::AnchorLeft :
                                        Qt::AnchorTop);
     AnchorVertex *center = internalVertex(item, orientation == Horizontal ?
                                         Qt::AnchorHorizontalCenter :
                                         Qt::AnchorVerticalCenter);
     // Skip if no center constraints exist
     if (!center)
         return;
     Q_ASSERT(first);
     AnchorData *internalAnchor = graph[orientation].edgeData(first, center);
     // Look for our anchor in all item center constraints, then remove it
     for (int i = 0; i < itemCenterConstraints[orientation].size(); ++i) {
         if (itemCenterConstraints[orientation].at(i)->variables.contains(internalAnchor)) {
             delete itemCenterConstraints[orientation].takeAt(i);
             break;
         }
     }
 }
removeInternalVertex()
void QGraphicsAnchorLayoutPrivate::removeInternalVertex (QGraphicsLayoutItem * item, Qt::AnchorPoint edge)
Warning
This function is not part of the public interface.
returns the AnchorVertex that was dereferenced, also when it was removed. returns 0 if it did not exist.
Definition at line 1939 of file qgraphicsanchorlayout_p.cpp.
Referenced by removeAnchor_helper(), and removeVertex().
 {
     QPair<QGraphicsLayoutItem *, Qt::AnchorPoint> pair(item, edge);
     QPair<AnchorVertex *, int> v = m_vertexList.value(pair);
     if (!v.first) {
         qWarning("This item with this edge is not in the graph");
         return;
     }
     v.second--;
     if (v.second == 0) {
         // Remove reference and delete vertex
         m_vertexList.remove(pair);
         delete v.first;
     } else {
         // Update reference count
         m_vertexList.insert(pair, v);
         if ((v.second == 2) &&
             ((edge == Qt::AnchorHorizontalCenter) ||
              (edge == Qt::AnchorVerticalCenter))) {
             removeCenterAnchors(item, edge, true);
         }
     }
 }
removeVertex()
void QGraphicsAnchorLayoutPrivate::removeVertex (QGraphicsLayoutItem * item, Qt::AnchorPoint edge)
Definition at line 1967 of file qgraphicsanchorlayout_p.cpp.
Referenced by removeAnchors().
 {
     if (AnchorVertex *v = internalVertex(item, edge)) {
         Graph<AnchorVertex, AnchorData> &g = graph[edgeOrientation(edge)];
         const QList<AnchorVertex *> allVertices = graph[edgeOrientation(edge)].adjacentVertices(v);
         AnchorVertex *v2;
         foreach (v2, allVertices) {
             g.removeEdge(v, v2);
             removeInternalVertex(item, edge);
             removeInternalVertex(v2->m_item, v2->m_edge);
         }
     }
 }
replaceVertex()
bool QGraphicsAnchorLayoutPrivate::replaceVertex (Orientation orientation, AnchorVertex * oldV, AnchorVertex * newV, const QList< AnchorData *> & edges)
Definition at line 904 of file qgraphicsanchorlayout_p.cpp.
Referenced by simplifyVertices().
 {
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     bool feasible = true;
     for (int i = 0; i < edges.count(); ++i) {
         AnchorData *ad = edges[i];
         AnchorVertex *otherV = replaceVertex_helper(ad, oldV, newV);
 #if defined(QT_DEBUG)
         ad->name = QString::fromAscii("%1 --to--> %2").arg(ad->from->toString()).arg(ad->to->toString());
 #endif
         bool newFeasible;
         AnchorData *newAnchor = addAnchorMaybeParallel(ad, &newFeasible);
         feasible &= newFeasible;
         if (newAnchor != ad) {
             // A parallel was created, we mark that in the list of anchors created by vertex
             // simplification. This is needed because we want to restore them in a separate step
             // from the restoration of anchor simplification.
             anchorsFromSimplifiedVertices[orientation].append(newAnchor);
         }
         g.takeEdge(oldV, otherV);
     }
     return feasible;
 }
restoreSimplifiedAnchor()
void QGraphicsAnchorLayoutPrivate::restoreSimplifiedAnchor (AnchorData * edge)
Definition at line 1210 of file qgraphicsanchorlayout_p.cpp.
Referenced by restoreSimplifiedGraph().
 {
 #if 0
     static const char *anchortypes[] = {"Normal",
                                         "Sequential",
                                         "Parallel"};
     qDebug("Restoring %s edge.", anchortypes[int(edge->type)]);
 #endif
     Graph<AnchorVertex, AnchorData> &g = graph[edge->orientation];
     if (edge->type == AnchorData::Normal) {
         g.createEdge(edge->from, edge->to, edge);
     } else if (edge->type == AnchorData::Sequential) {
         SequentialAnchorData *sequence = static_cast<SequentialAnchorData *>(edge);
         for (int i = 0; i < sequence->m_edges.count(); ++i) {
             AnchorData *data = sequence->m_edges.at(i);
             restoreSimplifiedAnchor(data);
         }
         delete sequence;
     } else if (edge->type == AnchorData::Parallel) {
         // Skip parallel anchors that were created by vertex simplification, they will be processed
         // later, when restoring vertex simplification.
         // ### we could improve this check bit having a bit inside 'edge'
         if (anchorsFromSimplifiedVertices[edge->orientation].contains(edge))
             return;
         ParallelAnchorData* parallel = static_cast<ParallelAnchorData*>(edge);
         restoreSimplifiedConstraints(parallel);
         // ### Because of the way parallel anchors are created in the anchor simplification
         // algorithm, we know that one of these will be a sequence, so it'll be safe if the other
         // anchor create an edge between the same vertices as the parallel.
         Q_ASSERT(parallel->firstEdge->type == AnchorData::Sequential
                  || parallel->secondEdge->type == AnchorData::Sequential);
         restoreSimplifiedAnchor(parallel->firstEdge);
         restoreSimplifiedAnchor(parallel->secondEdge);
         delete parallel;
     }
 }
restoreSimplifiedConstraints()
void QGraphicsAnchorLayoutPrivate::restoreSimplifiedConstraints (ParallelAnchorData * parallel)
Definition at line 1257 of file qgraphicsanchorlayout_p.cpp.
Referenced by restoreSimplifiedAnchor(), and restoreVertices().
 {
     if (!parallel->isCenterAnchor)
         return;
     for (int i = 0; i < parallel->m_firstConstraints.count(); ++i) {
         QSimplexConstraint *c = parallel->m_firstConstraints.at(i);
         qreal v = c->variables[parallel];
         c->variables.remove(parallel);
         c->variables.insert(parallel->firstEdge, v);
     }
     // When restoring, we might have to revert constraints back. See comments on
     // addAnchorMaybeParallel().
     const bool needsReverse = !parallel->secondForward();
     for (int i = 0; i < parallel->m_secondConstraints.count(); ++i) {
         QSimplexConstraint *c = parallel->m_secondConstraints.at(i);
         qreal v = c->variables[parallel];
         if (needsReverse)
             v *= -1;
         c->variables.remove(parallel);
         c->variables.insert(parallel->secondEdge, v);
     }
 }
restoreSimplifiedGraph()
void QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph (Orientation orientation)
Definition at line 1283 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs(), and simplifyGraph().
 {
 #if 0
     qDebug("Restoring Simplified Graph for %s",
            orientation == Horizontal ? "Horizontal" : "Vertical");
 #endif
     // Restore anchor simplification
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     QList<QPair<AnchorVertex*, AnchorVertex*> > connections = g.connections();
     for (int i = 0; i < connections.count(); ++i) {
         AnchorVertex *v1 = connections.at(i).first;
         AnchorVertex *v2 = connections.at(i).second;
         AnchorData *edge = g.edgeData(v1, v2);
         // We restore only sequential anchors and parallels that were not created by
         // vertex simplification.
         if (edge->type == AnchorData::Sequential
             || (edge->type == AnchorData::Parallel &&
                 !anchorsFromSimplifiedVertices[orientation].contains(edge))) {
             g.takeEdge(v1, v2);
             restoreSimplifiedAnchor(edge);
         }
     }
     restoreVertices(orientation);
 }
restoreVertices()
void QGraphicsAnchorLayoutPrivate::restoreVertices (Orientation orientation)
Definition at line 1312 of file qgraphicsanchorlayout_p.cpp.
Referenced by restoreSimplifiedGraph(), and simplifyGraph().
 {
     Q_Q(QGraphicsAnchorLayout);
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     QList<AnchorVertexPair *> &toRestore = simplifiedVertices[orientation];
     // Since we keep a list of parallel anchors and vertices that were created during vertex
     // simplification, we can now iterate on those lists instead of traversing the graph
     // recursively.
     // First, restore the constraints changed when we created parallel anchors. Note that this
     // works at this point because the constraints doesn't depend on vertex information and at
     // this point it's always safe to identify whether the second child is forward or backwards.
     // In the next step, we'll change the anchors vertices so that would not be possible anymore.
     QList<AnchorData *> &parallelAnchors = anchorsFromSimplifiedVertices[orientation];
     for (int i = parallelAnchors.count() - 1; i >= 0; --i) {
         ParallelAnchorData *parallel = static_cast<ParallelAnchorData *>(parallelAnchors.at(i));
         restoreSimplifiedConstraints(parallel);
     }
     // Then, we will restore the vertices in the inverse order of creation, this way we ensure that
     // the vertex being restored was not wrapped by another simplification.
     for (int i = toRestore.count() - 1; i >= 0; --i) {
         AnchorVertexPair *pair = toRestore.at(i);
         QList<AnchorVertex *> adjacents = g.adjacentVertices(pair);
         // Restore the removed edge, this will also restore both vertices 'first' and 'second' to
         // the graph structure.
         AnchorVertex *first = pair->m_first;
         AnchorVertex *second = pair->m_second;
         g.createEdge(first, second, pair->m_removedAnchor);
         // Restore the anchors for the first child vertex
         for (int j = 0; j < pair->m_firstAnchors.count(); ++j) {
             AnchorData *ad = pair->m_firstAnchors.at(j);
             Q_ASSERT(ad->from == pair || ad->to == pair);
             replaceVertex_helper(ad, pair, first);
             g.createEdge(ad->from, ad->to, ad);
         }
         // Restore the anchors for the second child vertex
         for (int j = 0; j < pair->m_secondAnchors.count(); ++j) {
             AnchorData *ad = pair->m_secondAnchors.at(j);
             Q_ASSERT(ad->from == pair || ad->to == pair);
             replaceVertex_helper(ad, pair, second);
             g.createEdge(ad->from, ad->to, ad);
         }
         for (int j = 0; j < adjacents.count(); ++j) {
             g.takeEdge(pair, adjacents.at(j));
         }
         // The pair simplified a layout vertex, so place back the correct vertex in the variable
         // that track layout vertices
         if (pair->m_item == q) {
             AnchorVertex *layoutVertex = first->m_item == q ? first : second;
             Q_ASSERT(layoutVertex->m_item == q);
             changeLayoutVertex(orientation, pair, layoutVertex);
         }
         delete pair;
     }
     qDeleteAll(parallelAnchors);
     parallelAnchors.clear();
     toRestore.clear();
 }
setItemsGeometries()
void QGraphicsAnchorLayoutPrivate::setItemsGeometries (const QRectF & geom)
Use the current vertices distance to calculate and set the geometry of each item.
Warning
This function is not part of the public interface.
Definition at line 2708 of file qgraphicsanchorlayout_p.cpp.
 {
     Q_Q(QGraphicsAnchorLayout);
     AnchorVertex *firstH, *secondH, *firstV, *secondV;
     qreal top;
     qreal left;
     qreal right;
     q->getContentsMargins(&left, &top, &right, 0);
     const Qt::LayoutDirection visualDir = visualDirection();
     if (visualDir == Qt::RightToLeft)
         qSwap(left, right);
     left += geom.left();
     top += geom.top();
     right = geom.right() - right;
     foreach (QGraphicsLayoutItem *item, items) {
         QRectF newGeom;
         QSizeF itemPreferredSize = item->effectiveSizeHint(Qt::PreferredSize);
         if (m_floatItems[Horizontal].contains(item)) {
             newGeom.setLeft(0);
             newGeom.setRight(itemPreferredSize.width());
         } else {
             firstH = internalVertex(item, Qt::AnchorLeft);
             secondH = internalVertex(item, Qt::AnchorRight);
             if (visualDir == Qt::LeftToRight) {
                 newGeom.setLeft(left + firstH->distance);
                 newGeom.setRight(left + secondH->distance);
             } else {
                 newGeom.setLeft(right - secondH->distance);
                 newGeom.setRight(right - firstH->distance);
             }
         }
         if (m_floatItems[Vertical].contains(item)) {
             newGeom.setTop(0);
             newGeom.setBottom(itemPreferredSize.height());
         } else {
             firstV = internalVertex(item, Qt::AnchorTop);
             secondV = internalVertex(item, Qt::AnchorBottom);
             newGeom.setTop(top + firstV->distance);
             newGeom.setBottom(top + secondV->distance);
         }
         item->setGeometry(newGeom);
     }
 }
setupEdgesInterpolation()
void QGraphicsAnchorLayoutPrivate::setupEdgesInterpolation (Orientation orientation)
Calculate interpolation parameters based on current Layout Size.
Warning
This function is not part of the public interface.
Must be called once before calling "interpolateEdgeSize()" for the edges.
Definition at line 2818 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateVertexPositions().
 {
     Q_Q(QGraphicsAnchorLayout);
     qreal current;
     current = (orientation == Horizontal) ? q->contentsRect().width() : q->contentsRect().height();
     QPair<Interval, qreal> result;
     result = getFactor(current,
                        sizeHints[orientation][Qt::MinimumSize],
                        sizeHints[orientation][Qt::PreferredSize],
                        sizeHints[orientation][Qt::PreferredSize],
                        sizeHints[orientation][Qt::PreferredSize],
                        sizeHints[orientation][Qt::MaximumSize]);
     interpolationInterval[orientation] = result.first;
     interpolationProgress[orientation] = result.second;
 }
simplifyGraph()
bool QGraphicsAnchorLayoutPrivate::simplifyGraph (Orientation orientation)
The purpose of this function is to simplify the graph.
Warning
This function is not part of the public interface.
Simplification serves two purposes:
Reduce the number of edges in the graph, (thus the number of variables to the equation solver is reduced, and the solver performs better).
Be able to do distribution of sequences of edges more intelligently (esp. with sequential anchors)
It is essential that it must be possible to restore simplified anchors back to their "original" form. This is done by restoreSimplifiedAnchor().
There are two types of simplification that can be done:
Sequential simplification Sequential simplification means that all sequences of anchors will be merged into one single anchor. Only anhcors that points in the same direction will be merged.
Parallel simplification If a simplified sequential anchor is about to be inserted between two vertices in the graph and there already exist an anchor between those two vertices, a parallel anchor will be created that serves as a placeholder for the sequential anchor and the anchor that was already between the two vertices.
The process of simplification can be described as:
Simplify all sequences of anchors into one anchor. If no further simplification was done, go to (3)
If there already exist an anchor where the sequential anchor is supposed to be inserted, take that anchor out of the graph
Then create a parallel anchor that holds the sequential anchor and the anchor just taken out of the graph.
Go to (1)
Done
When creating the parallel anchors, the algorithm might identify unfeasible situations. In this case the simplification process stops and returns false. Otherwise returns true.
Definition at line 847 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     if (items.isEmpty())
         return true;
 #if defined(QT_DEBUG) && 0
     qDebug("Simplifying Graph for %s",
            orientation == Horizontal ? "Horizontal" : "Vertical");
     static int count = 0;
     if (orientation == Horizontal) {
         count++;
         dumpGraph(QString::fromAscii("%1-full").arg(count));
     }
 #endif
     // Vertex simplification
     if (!simplifyVertices(orientation)) {
         restoreVertices(orientation);
         return false;
     }
     // Anchor simplification
     bool dirty;
     bool feasible = true;
     do {
         dirty = simplifyGraphIteration(orientation, &feasible);
     } while (dirty && feasible);
     // Note that if we are not feasible, we fallback and make sure that the graph is fully restored
     if (!feasible) {
         restoreSimplifiedGraph(orientation);
         restoreVertices(orientation);
         return false;
     }
 #if defined(QT_DEBUG) && 0
     dumpGraph(QString::fromAscii("%1-simplified-%2").arg(count).arg(
                   QString::fromAscii(orientation == Horizontal ? "Horizontal" : "Vertical")));
 #endif
     return true;
 }
simplifyGraphIteration()
bool QGraphicsAnchorLayoutPrivate::simplifyGraphIteration (QGraphicsAnchorLayoutPrivate::Orientation orientation, bool * feasible)
One iteration of the simplification algorithm.
Warning
This function is not part of the public interface.
Returns true if another iteration is needed.
The algorithm walks the graph in depth-first order, and only collects vertices that has two edges connected to it. If the vertex does not have two edges or if it is a layout edge, it will take all the previously collected vertices and try to create a simplified sequential anchor representing all the previously collected vertices. Once the simplified anchor is inserted, the collected list is cleared in order to find the next sequence to simplify.
Note that there are some catches to this that are not covered by the above explanation, see the function comments for more details.
Definition at line 1054 of file qgraphicsanchorlayout_p.cpp.
Referenced by simplifyGraph().
 {
     Q_Q(QGraphicsAnchorLayout);
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     QSet<AnchorVertex *> visited;
     QStack<QPair<AnchorVertex *, AnchorVertex *> > stack;
     stack.push(qMakePair(static_cast<AnchorVertex *>(0), layoutFirstVertex[orientation]));
     QVector<AnchorVertex*> candidates;
     // Walk depth-first, in the stack we store start of the candidate sequence (beforeSequence)
     // and the vertex to be visited.
     while (!stack.isEmpty()) {
         QPair<AnchorVertex *, AnchorVertex *> pair = stack.pop();
         AnchorVertex *beforeSequence = pair.first;
         AnchorVertex *v = pair.second;
         // The basic idea is to determine whether we found an end of sequence,
         // if that's the case, we stop adding vertices to the candidate list
         // and do a simplification step.
         //
         // A vertex can trigger an end of sequence if
         // (a) it is a layout vertex, we don't simplify away the layout vertices;
         // (b) it does not have exactly 2 adjacents;
         // (c) its next adjacent is already visited (a cycle in the graph).
         // (d) the next anchor is a center anchor.
         const QList<AnchorVertex *> &adjacents = g.adjacentVertices(v);
         const bool isLayoutVertex = v->m_item == q;
         AnchorVertex *afterSequence = v;
         bool endOfSequence = false;
         //
         // Identify the end cases.
         //
         // Identifies cases (a) and (b)
         endOfSequence = isLayoutVertex || adjacents.count() != 2;
         if (!endOfSequence) {
             // This is a tricky part. We peek at the next vertex to find out whether
             //
             // - we already visited the next vertex (c);
             // - the next anchor is a center (d).
             //
             // Those are needed to identify the remaining end of sequence cases. Note that unlike
             // (a) and (b), we preempt the end of sequence by looking into the next vertex.
             // Peek at the next vertex
             AnchorVertex *after;
             if (candidates.isEmpty())
                 after = (beforeSequence == adjacents.last() ? adjacents.first() : adjacents.last());
             else
                 after = (candidates.last() == adjacents.last() ? adjacents.first() : adjacents.last());
             // ### At this point we assumed that candidates will not contain 'after', this may not hold
             // when simplifying FLOATing anchors.
             Q_ASSERT(!candidates.contains(after));
             const AnchorData *data = g.edgeData(v, after);
             Q_ASSERT(data);
             const bool cycleFound = visited.contains(after);
             // Now cases (c) and (d)...
             endOfSequence = cycleFound || data->isCenterAnchor;
             if (!endOfSequence) {
                 // If it's not an end of sequence, then the vertex didn't trigger neither of the
                 // previously three cases, so it can be added to the candidates list.
                 candidates.append(v);
             } else if (cycleFound && (beforeSequence != after)) {
                 afterSequence = after;
                 candidates.append(v);
             }
         }
         //
         // Add next non-visited vertices to the stack.
         //
         for (int i = 0; i < adjacents.count(); ++i) {
             AnchorVertex *next = adjacents.at(i);
             if (visited.contains(next))
                 continue;
             // If current vertex is an end of sequence, and it'll reset the candidates list. So
             // the next vertices will build candidates lists with the current vertex as 'before'
             // vertex. If it's not an end of sequence, we keep the original 'before' vertex,
             // since we are keeping the candidates list.
             if (endOfSequence)
                 stack.push(qMakePair(v, next));
             else
                 stack.push(qMakePair(beforeSequence, next));
         }
         visited.insert(v);
         if (!endOfSequence || candidates.isEmpty())
             continue;
         //
         // Create a sequence for (beforeSequence, candidates, afterSequence).
         //
         // One restriction we have is to not simplify half of an anchor and let the other half
         // unsimplified. So we remove center edges before and after the sequence.
         const AnchorData *firstAnchor = g.edgeData(beforeSequence, candidates.first());
         if (firstAnchor->isCenterAnchor) {
             beforeSequence = candidates.first();
             candidates.remove(0);
             // If there's not candidates to be simplified, leave.
             if (candidates.isEmpty())
                 continue;
         }
         const AnchorData *lastAnchor = g.edgeData(candidates.last(), afterSequence);
         if (lastAnchor->isCenterAnchor) {
             afterSequence = candidates.last();
             candidates.remove(candidates.count() - 1);
             if (candidates.isEmpty())
                 continue;
         }
         //
         // Add the sequence to the graph.
         //
         AnchorData *sequence = createSequence(&g, beforeSequence, candidates, afterSequence);
         // If 'beforeSequence' and 'afterSequence' already had an anchor between them, we'll
         // create a parallel anchor between the new sequence and the old anchor.
         bool newFeasible;
         AnchorData *newAnchor = addAnchorMaybeParallel(sequence, &newFeasible);
         if (!newFeasible) {
             *feasible = false;
             return false;
         }
         // When a new parallel anchor is create in the graph, we finish the iteration and return
         // true to indicate a new iteration is needed. This happens because a parallel anchor
         // changes the number of adjacents one vertex has, possibly opening up oportunities for
         // building candidate lists (when adjacents == 2).
         if (newAnchor != sequence)
             return true;
         // If there was no parallel simplification, we'll keep walking the graph. So we clear the
         // candidates list to start again.
         candidates.clear();
     }
     return false;
 }
simplifyVertices()
bool QGraphicsAnchorLayoutPrivate::simplifyVertices (Orientation orientation)
Warning
This function is not part of the public interface.
Definition at line 938 of file qgraphicsanchorlayout_p.cpp.
Referenced by simplifyGraph().
 {
     Q_Q(QGraphicsAnchorLayout);
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     // We'll walk through vertices
     QStack<AnchorVertex *> stack;
     stack.push(layoutFirstVertex[orientation]);
     QSet<AnchorVertex *> visited;
     while (!stack.isEmpty()) {
         AnchorVertex *v = stack.pop();
         visited.insert(v);
         // Each adjacent of 'v' is a possible vertex to be merged. So we traverse all of
         // them. Since once a merge is made, we might add new adjacents, and we don't want to
         // pass two times through one adjacent. The 'index' is used to track our position.
         QList<AnchorVertex *> adjacents = g.adjacentVertices(v);
         int index = 0;
         while (index < adjacents.count()) {
             AnchorVertex *next = adjacents.at(index);
             index++;
             AnchorData *data = g.edgeData(v, next);
             const bool bothLayoutVertices = v->m_item == q && next->m_item == q;
             const bool zeroSized = !data->minSize && !data->maxSize;
             if (!bothLayoutVertices && zeroSized) {
                 // Create a new vertex pair, note that we keep a list of those vertices so we can
                 // easily process them when restoring the graph.
                 AnchorVertexPair *newV = new AnchorVertexPair(v, next, data);
                 simplifiedVertices[orientation].append(newV);
                 // Collect the anchors of both vertices, the new vertex pair will take their place
                 // in those anchors
                 const QList<AnchorVertex *> &vAdjacents = g.adjacentVertices(v);
                 const QList<AnchorVertex *> &nextAdjacents = g.adjacentVertices(next);
                 for (int i = 0; i < vAdjacents.count(); ++i) {
                     AnchorVertex *adjacent = vAdjacents.at(i);
                     if (adjacent != next) {
                         AnchorData *ad = g.edgeData(v, adjacent);
                         newV->m_firstAnchors.append(ad);
                     }
                 }
                 for (int i = 0; i < nextAdjacents.count(); ++i) {
                     AnchorVertex *adjacent = nextAdjacents.at(i);
                     if (adjacent != v) {
                         AnchorData *ad = g.edgeData(next, adjacent);
                         newV->m_secondAnchors.append(ad);
                         // We'll also add new vertices to the adjacent list of the new 'v', to be
                         // created as a vertex pair and replace the current one.
                         if (!adjacents.contains(adjacent))
                             adjacents.append(adjacent);
                     }
                 }
                 // ### merge this loop into the ones that calculated m_firstAnchors/m_secondAnchors?
                 // Make newV take the place of v and next
                 bool feasible = replaceVertex(orientation, v, newV, newV->m_firstAnchors);
                 feasible &= replaceVertex(orientation, next, newV, newV->m_secondAnchors);
                 // Update the layout vertex information if one of the vertices is a layout vertex.
                 AnchorVertex *layoutVertex = 0;
                 if (v->m_item == q)
                     layoutVertex = v;
                 else if (next->m_item == q)
                     layoutVertex = next;
                 if (layoutVertex) {
                     // Layout vertices always have m_item == q...
                     newV->m_item = q;
                     changeLayoutVertex(orientation, layoutVertex, newV);
                 }
                 g.takeEdge(v, next);
                 // If a non-feasibility is found, we leave early and cancel the simplification
                 if (!feasible)
                     return false;
                 v = newV;
                 visited.insert(newV);
             } else if (!visited.contains(next) && !stack.contains(next)) {
                 // If the adjacent is not fit for merge and it wasn't visited by the outermost
                 // loop, we add it to the stack.
                 stack.push(next);
             }
         }
     }
     return true;
 }
solveMinMax()
bool QGraphicsAnchorLayoutPrivate::solveMinMax (const QList< QSimplexConstraint *> & constraints, GraphPath path, qreal * min, qreal * max)
Definition at line 2876 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateTrunk().
 {
     QSimplex simplex;
     bool feasible = simplex.setConstraints(constraints);
     if (feasible) {
         // Obtain the objective constraint
         QSimplexConstraint objective;
         QSet<AnchorData *>::const_iterator iter;
         for (iter = path.positives.constBegin(); iter != path.positives.constEnd(); ++iter)
             objective.variables.insert(*iter, 1.0);
         for (iter = path.negatives.constBegin(); iter != path.negatives.constEnd(); ++iter)
             objective.variables.insert(*iter, -1.0);
         const qreal objectiveOffset = (path.positives.count() - path.negatives.count()) * g_offset;
         simplex.setObjective(&objective);
         // Calculate minimum values
         *min = simplex.solveMin() - objectiveOffset;
         // Save sizeAtMinimum results
         QList<AnchorData *> variables = getVariables(constraints);
         for (int i = 0; i < variables.size(); ++i) {
             AnchorData *ad = static_cast<AnchorData *>(variables.at(i));
             ad->sizeAtMinimum = ad->result - g_offset;
         }
         // Calculate maximum values
         *max = simplex.solveMax() - objectiveOffset;
         // Save sizeAtMaximum results
         for (int i = 0; i < variables.size(); ++i) {
             AnchorData *ad = static_cast<AnchorData *>(variables.at(i));
             ad->sizeAtMaximum = ad->result - g_offset;
         }
     }
     return feasible;
 }
solvePreferred()
bool QGraphicsAnchorLayoutPrivate::solvePreferred (const QList< QSimplexConstraint *> & constraints, const QList< AnchorData *> & variables)
Definition at line 2931 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateNonTrunk(), and calculateTrunk().
 {
     QList<QSimplexConstraint *> preferredConstraints;
     QList<QSimplexVariable *> preferredVariables;
     QSimplexConstraint objective;
     // Fill the objective coefficients for this variable. In the
     // end the objective function will be
     //
     //     z = n * (A_shrinker_hard + A_grower_hard + B_shrinker_hard + B_grower_hard + ...) +
     //             (A_shrinker_soft + A_grower_soft + B_shrinker_soft + B_grower_soft + ...)
     //
     // where n is the number of variables that have
     // slacks. Note that here we use the number of variables
     // as coefficient, this is to mark the "shrinker slack
     // variable" less likely to get value than the "grower
     // slack variable".
     // This will fill the values for the structural constraints
     // and we now fill the values for the slack constraints (one per variable),
     // which have this form (the constant A_pref was set when creating the slacks):
     //
     //      A + A_shrinker_hard + A_shrinker_soft - A_grower_hard - A_grower_soft = A_pref
     //
     for (int i = 0; i < variables.size(); ++i) {
         AnchorData *ad = variables.at(i);
         // The layout original structure anchors are not relevant in preferred size calculation
         if (ad->isLayoutAnchor)
             continue;
         // By default, all variables are equal to their preferred size. If they have room to
         // grow or shrink, such flexibility will be added by the additional variables below.
         QSimplexConstraint *sizeConstraint = new QSimplexConstraint;
         preferredConstraints += sizeConstraint;
         sizeConstraint->variables.insert(ad, 1.0);
         sizeConstraint->constant = ad->prefSize + g_offset;
         // Can easily shrink
         QPair<QSimplexVariable *, QSimplexConstraint *> slack;
         const qreal softShrinkInterval = ad->prefSize - ad->minPrefSize;
         if (softShrinkInterval) {
             slack = createSlack(sizeConstraint, softShrinkInterval, Shrinker);
             preferredVariables += slack.first;
             preferredConstraints += slack.second;
             // Add to objective with ratio == 1 (soft)
             objective.variables.insert(slack.first, 1.0);
         }
         // Can easily grow
         const qreal softGrowInterval = ad->maxPrefSize - ad->prefSize;
         if (softGrowInterval) {
             slack = createSlack(sizeConstraint, softGrowInterval, Grower);
             preferredVariables += slack.first;
             preferredConstraints += slack.second;
             // Add to objective with ratio == 1 (soft)
             objective.variables.insert(slack.first, 1.0);
         }
         // Can shrink if really necessary
         const qreal hardShrinkInterval = ad->minPrefSize - ad->minSize;
         if (hardShrinkInterval) {
             slack = createSlack(sizeConstraint, hardShrinkInterval, Shrinker);
             preferredVariables += slack.first;
             preferredConstraints += slack.second;
             // Add to objective with ratio == N (hard)
             objective.variables.insert(slack.first, variables.size());
         }
         // Can grow if really necessary
         const qreal hardGrowInterval = ad->maxSize - ad->maxPrefSize;
         if (hardGrowInterval) {
             slack = createSlack(sizeConstraint, hardGrowInterval, Grower);
             preferredVariables += slack.first;
             preferredConstraints += slack.second;
             // Add to objective with ratio == N (hard)
             objective.variables.insert(slack.first, variables.size());
         }
     }
     QSimplex *simplex = new QSimplex;
     bool feasible = simplex->setConstraints(constraints + preferredConstraints);
     if (feasible) {
         simplex->setObjective(&objective);
         // Calculate minimum values
         simplex->solveMin();
         // Save sizeAtPreferred results
         for (int i = 0; i < variables.size(); ++i) {
             AnchorData *ad = variables.at(i);
             ad->sizeAtPreferred = ad->result - g_offset;
         }
     }
     // Make sure we delete the simplex solver -before- we delete the
     // constraints used by it.
     delete simplex;
     // Delete constraints and variables we created.
     qDeleteAll(preferredConstraints);
     qDeleteAll(preferredVariables);
     return feasible;
 }
styleInfo()
QLayoutStyleInfo & QGraphicsAnchorLayoutPrivate::styleInfo () const
Definition at line 2049 of file qgraphicsanchorlayout_p.cpp.
Referenced by refreshAllSizeHints().
 {
     if (styleInfoDirty) {
         Q_Q(const QGraphicsAnchorLayout);
         //### Fix this if QGV ever gets support for Metal style or different Aqua sizes.
         QWidget *wid = 0;
         QGraphicsLayoutItem *parent = q->parentLayoutItem();
         while (parent && parent->isLayout()) {
             parent = parent->parentLayoutItem();
         }
         QGraphicsWidget *w = 0;
         if (parent) {
             QGraphicsItem *parentItem = parent->graphicsItem();
             if (parentItem && parentItem->isWidget())
                 w = static_cast<QGraphicsWidget*>(parentItem);
         }
         QStyle *style = w ? w->style() : QApplication::style();
         cachedStyleInfo = QLayoutStyleInfo(style, wid);
         cachedStyleInfo.setDefaultSpacing(Qt::Horizontal, spacings[0]);
         cachedStyleInfo.setDefaultSpacing(Qt::Vertical, spacings[1]);
         styleInfoDirty = false;
     }
     return cachedStyleInfo;
 }
updateAnchorSizes()
void QGraphicsAnchorLayoutPrivate::updateAnchorSizes (Orientation orientation)
Warning
This function is not part of the public interface.
Definition at line 2449 of file qgraphicsanchorlayout_p.cpp.
Referenced by calculateGraphs().
 {
     Graph<AnchorVertex, AnchorData> &g = graph[orientation];
     const QList<QPair<AnchorVertex *, AnchorVertex *> > &vertices = g.connections();
     for (int i = 0; i < vertices.count(); ++i) {
         AnchorData *ad = g.edgeData(vertices.at(i).first, vertices.at(i).second);
         ad->updateChildrenSizes();
     }
 }
Friends and Related Functions
QGraphicsAnchorPrivate
friend class QGraphicsAnchorPrivate friend
Definition at line 597 of file qgraphicsanchorlayout_p.h.
Properties
anchorsFromSimplifiedVertices
QList<AnchorData *> QGraphicsAnchorLayoutPrivate::anchorsFromSimplifiedVertices[2]
Definition at line 574 of file qgraphicsanchorlayout_p.h.
Referenced by replaceVertex(), restoreSimplifiedAnchor(), restoreSimplifiedGraph(), and restoreVertices().
cachedStyleInfo
QLayoutStyleInfo QGraphicsAnchorLayoutPrivate::cachedStyleInfo mutable
Definition at line 595 of file qgraphicsanchorlayout_p.h.
Referenced by styleInfo().
calculateGraphCacheDirty
uint QGraphicsAnchorLayoutPrivate::calculateGraphCacheDirty
Definition at line 593 of file qgraphicsanchorlayout_p.h.
Referenced by calculateGraphs().
constraints
QList<QSimplexConstraint *> QGraphicsAnchorLayoutPrivate::constraints[2]
Definition at line 578 of file qgraphicsanchorlayout_p.h.
Referenced by addAnchorMaybeParallel(), calculateGraphs(), constraintsFromPaths(), and getGraphParts().
graph
Graph<AnchorVertex, AnchorData> QGraphicsAnchorLayoutPrivate::graph[2]
Definition at line 566 of file qgraphicsanchorlayout_p.h.
Referenced by addAnchor_helper(), addAnchorMaybeParallel(), calculateVertexPositions(), constraintsFromSizeHints(), dumpGraph(), findPaths(), getAnchor(), getGraphParts(), refreshAllSizeHints(), removeAnchor_helper(), removeCenterAnchors(), removeCenterConstraints(), removeVertex(), replaceVertex(), restoreSimplifiedAnchor(), restoreSimplifiedGraph(), restoreVertices(), simplifyGraphIteration(), simplifyVertices(), and updateAnchorSizes().
graphHasConflicts
bool QGraphicsAnchorLayoutPrivate::graphHasConflicts[2]
Definition at line 586 of file qgraphicsanchorlayout_p.h.
Referenced by calculateGraphs(), hasConflicts(), and QGraphicsAnchorLayoutPrivate().
graphPaths
QMultiHash<AnchorVertex *, GraphPath> QGraphicsAnchorLayoutPrivate::graphPaths[2]
Definition at line 577 of file qgraphicsanchorlayout_p.h.
Referenced by calculateGraphs(), constraintsFromPaths(), and findPaths().
interpolationInterval
Interval QGraphicsAnchorLayoutPrivate::interpolationInterval[2]
Definition at line 583 of file qgraphicsanchorlayout_p.h.
Referenced by interpolateEdge(), and setupEdgesInterpolation().
interpolationProgress
qreal QGraphicsAnchorLayoutPrivate::interpolationProgress[2]
Definition at line 584 of file qgraphicsanchorlayout_p.h.
Referenced by interpolateEdge(), QGraphicsAnchorLayoutPrivate(), and setupEdgesInterpolation().
itemCenterConstraints
QList<QSimplexConstraint *> QGraphicsAnchorLayoutPrivate::itemCenterConstraints[2]
Definition at line 579 of file qgraphicsanchorlayout_p.h.
Referenced by addAnchorMaybeParallel(), createCenterAnchors(), getGraphParts(), removeCenterAnchors(), and removeCenterConstraints().
items
QVector<QGraphicsLayoutItem *> QGraphicsAnchorLayoutPrivate::items
Definition at line 558 of file qgraphicsanchorlayout_p.h.
Referenced by addAnchor(), createItemEdges(), identifyFloatItems(), removeAnchor(), setItemsGeometries(), and simplifyGraph().
lastCalculationUsedSimplex
bool QGraphicsAnchorLayoutPrivate::lastCalculationUsedSimplex[2]
Definition at line 590 of file qgraphicsanchorlayout_p.h.
Referenced by calculateGraphs(), and calculateTrunk().
layoutCentralVertex
AnchorVertex* QGraphicsAnchorLayoutPrivate::layoutCentralVertex[2]
Definition at line 569 of file qgraphicsanchorlayout_p.h.
Referenced by constraintsFromSizeHints(), createCenterAnchors(), createLayoutEdges(), getGraphParts(), QGraphicsAnchorLayoutPrivate(), and removeCenterAnchors().
layoutFirstVertex
AnchorVertex* QGraphicsAnchorLayoutPrivate::layoutFirstVertex[2]
Definition at line 568 of file qgraphicsanchorlayout_p.h.
Referenced by calculateVertexPositions(), constraintsFromSizeHints(), createLayoutEdges(), findPaths(), getGraphParts(), QGraphicsAnchorLayoutPrivate(), simplifyGraphIteration(), and simplifyVertices().
layoutLastVertex
AnchorVertex* QGraphicsAnchorLayoutPrivate::layoutLastVertex[2]
Definition at line 570 of file qgraphicsanchorlayout_p.h.
Referenced by calculateGraphs(), constraintsFromSizeHints(), createLayoutEdges(), getGraphParts(), and QGraphicsAnchorLayoutPrivate().
m_floatItems
QSet<QGraphicsLayoutItem *> QGraphicsAnchorLayoutPrivate::m_floatItems[2]
Definition at line 587 of file qgraphicsanchorlayout_p.h.
Referenced by hasConflicts(), identifyFloatItems(), and setItemsGeometries().
m_vertexList
QHash<QPair<QGraphicsLayoutItem*, Qt::AnchorPoint>, QPair<AnchorVertex *, int> > QGraphicsAnchorLayoutPrivate::m_vertexList
Definition at line 563 of file qgraphicsanchorlayout_p.h.
Referenced by addInternalVertex(), removeAnchor(), and removeInternalVertex().
simplifiedVertices
QList<AnchorVertexPair *> QGraphicsAnchorLayoutPrivate::simplifiedVertices[2]
Definition at line 573 of file qgraphicsanchorlayout_p.h.
Referenced by restoreVertices(), and simplifyVertices().
sizeHints
qreal QGraphicsAnchorLayoutPrivate::sizeHints[2][3]
Definition at line 555 of file qgraphicsanchorlayout_p.h.
Referenced by calculateTrunk(), QGraphicsAnchorLayoutPrivate(), and setupEdgesInterpolation().
spacings
qreal QGraphicsAnchorLayoutPrivate::spacings[NOrientations]
Definition at line 553 of file qgraphicsanchorlayout_p.h.
Referenced by QGraphicsAnchorLayoutPrivate(), and styleInfo().
styleInfoDirty
uint QGraphicsAnchorLayoutPrivate::styleInfoDirty mutable
Definition at line 594 of file qgraphicsanchorlayout_p.h.
Referenced by styleInfo().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsanchorlayout_p.h
/src/gui/graphicsview/qgraphicsanchorlayout_p.cpp