Qt 4.8: QDeclarativeText Class Reference
QDeclarativeText Class Reference
#include <qdeclarativetext_p.h>
Public Types
enum HAlignment { AlignLeft = Qt::AlignLeft, AlignRight = Qt::AlignRight, AlignHCenter = Qt::AlignHCenter, AlignJustify = Qt::AlignJustify }
enum LineHeightMode { ProportionalHeight, FixedHeight }
enum TextElideMode { ElideLeft = Qt::ElideLeft, ElideRight = Qt::ElideRight, ElideMiddle = Qt::ElideMiddle, ElideNone = Qt::ElideNone }
enum TextFormat { PlainText = Qt::PlainText, RichText = Qt::RichText, AutoText = Qt::AutoText, StyledText = 4 }
enum TextStyle { Normal, Outline, Raised, Sunken }
enum VAlignment { AlignTop = Qt::AlignTop, AlignBottom = Qt::AlignBottom, AlignVCenter = Qt::AlignVCenter }
enum WrapMode {
NoWrap = QTextOption::NoWrap, WordWrap = QTextOption::WordWrap, WrapAnywhere = QTextOption::WrapAnywhere, WrapAtWordBoundaryOrAnywhere = QTextOption::WrapAtWordBoundaryOrAnywhere,
Wrap = QTextOption::WrapAtWordBoundaryOrAnywhere
}
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Signals
void colorChanged (const QColor &color)
void elideModeChanged (TextElideMode mode)
void fontChanged (const QFont &font)
void horizontalAlignmentChanged (HAlignment alignment)
void lineCountChanged ()
void lineHeightChanged (qreal lineHeight)
void lineHeightModeChanged (LineHeightMode mode)
void linkActivated (const QString &link)
void maximumLineCountChanged ()
void paintedSizeChanged ()
void styleChanged (TextStyle style)
void styleColorChanged (const QColor &color)
void textChanged (const QString &text)
void textFormatChanged (TextFormat textFormat)
void truncatedChanged ()
void verticalAlignmentChanged (VAlignment alignment)
void wrapModeChanged ()
Signals inherited from QDeclarativeImplicitSizeItem
void implicitHeightChanged ()
void implicitWidthChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QRectF boundingRect () const
QColor color () const
virtual void componentComplete ()
HAlignment effectiveHAlign () const
TextElideMode elideMode () const
QFont font () const
HAlignment hAlign () const
int lineCount () const
qreal lineHeight () const
LineHeightMode lineHeightMode () const
int maximumLineCount () const
void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
qreal paintedHeight () const
qreal paintedWidth () const
QDeclarativeText (QDeclarativeItem *parent=0)
void resetHAlign ()
void resetMaximumLineCount ()
int resourcesLoading () const
Returns the number of resources (images) that are being loaded asynchronously.
void setColor (const QColor &c)
void setElideMode (TextElideMode)
void setFont (const QFont &font)
void setHAlign (HAlignment align)
void setLineHeight (qreal lineHeight)
void setLineHeightMode (LineHeightMode)
void setMaximumLineCount (int lines)
void setStyle (TextStyle style)
void setStyleColor (const QColor &c)
void setText (const QString &)
void setTextFormat (TextFormat format)
void setVAlign (VAlignment align)
void setWrapMode (WrapMode w)
TextStyle style () const
QColor styleColor () const
QString text () const
TextFormat textFormat () const
bool truncated () const
VAlignment vAlign () const
WrapMode wrapMode () const
~QDeclarativeText ()
Public Functions inherited from QDeclarativeImplicitSizeItem
QDeclarativeImplicitSizeItem (QDeclarativeItem *parent=0)
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
Protected Functions inherited from QDeclarativeImplicitSizeItem
QDeclarativeImplicitSizeItem (QDeclarativeImplicitSizeItemPrivate &dd, QDeclarativeItem *parent)
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual bool event (QEvent *)
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
virtual bool sceneEvent (QEvent *)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Properties
QColor color
TextElideMode elide
QFont font
HAlignment horizontalAlignment
int lineCount
qreal lineHeight
LineHeightMode lineHeightMode
int maximumLineCount
qreal paintedHeight
qreal paintedWidth
TextStyle style
QColor styleColor
QString text
TextFormat textFormat
bool truncated
VAlignment verticalAlignment
WrapMode wrapMode
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 56 of file qdeclarativetext_p.h.
Enumerations
HAlignment
enum QDeclarativeText::HAlignment
Enumerator
AlignLeft
AlignRight
AlignHCenter
AlignJustify
Definition at line 90 of file qdeclarativetext_p.h.
                     { AlignLeft = Qt::AlignLeft,
                        AlignRight = Qt::AlignRight,
                        AlignHCenter = Qt::AlignHCenter,
                        AlignJustify = Qt::AlignJustify }; // ### VERSIONING: Only in QtQuick 1.1
LineHeightMode
enum QDeclarativeText::LineHeightMode
Enumerator
ProportionalHeight
FixedHeight
Definition at line 117 of file qdeclarativetext_p.h.
 { ProportionalHeight, FixedHeight };
TextElideMode
enum QDeclarativeText::TextElideMode
Enumerator
ElideLeft
ElideRight
ElideMiddle
ElideNone
Definition at line 105 of file qdeclarativetext_p.h.
                        { ElideLeft = Qt::ElideLeft,
                           ElideRight = Qt::ElideRight,
                           ElideMiddle = Qt::ElideMiddle,
                           ElideNone = Qt::ElideNone };
TextFormat
enum QDeclarativeText::TextFormat
Enumerator
PlainText
RichText
AutoText
StyledText
Definition at line 101 of file qdeclarativetext_p.h.
                     { PlainText = Qt::PlainText,
                        RichText = Qt::RichText,
                        AutoText = Qt::AutoText,
                        StyledText = 4 };
TextStyle
enum QDeclarativeText::TextStyle
Enumerator
Normal
Outline
Raised
Sunken
Definition at line 97 of file qdeclarativetext_p.h.
                    { Normal,
                       Outline,
                       Raised,
                       Sunken };
VAlignment
enum QDeclarativeText::VAlignment
Enumerator
AlignTop
AlignBottom
AlignVCenter
Definition at line 94 of file qdeclarativetext_p.h.
                     { AlignTop = Qt::AlignTop,
                        AlignBottom = Qt::AlignBottom,
                        AlignVCenter = Qt::AlignVCenter };
WrapMode
enum QDeclarativeText::WrapMode
Enumerator
NoWrap
WordWrap
WrapAnywhere
WrapAtWordBoundaryOrAnywhere
Wrap
Definition at line 110 of file qdeclarativetext_p.h.
                   { NoWrap = QTextOption::NoWrap,
                     WordWrap = QTextOption::WordWrap,
                     WrapAnywhere = QTextOption::WrapAnywhere,
                     WrapAtWordBoundaryOrAnywhere = QTextOption::WrapAtWordBoundaryOrAnywhere, // COMPAT
                     Wrap = QTextOption::WrapAtWordBoundaryOrAnywhere
                   };
Constructors and Destructors
QDeclarativeText()
QDeclarativeText::QDeclarativeText (QDeclarativeItem * parent = 0)
Definition at line 712 of file qdeclarativetext.cpp.
   : QDeclarativeImplicitSizeItem(*(new QDeclarativeTextPrivate), parent)
 {
 }
~QDeclarativeText()
QDeclarativeText::~QDeclarativeText ()
Definition at line 717 of file qdeclarativetext.cpp.
 {
 }
Functions
boundingRect()
QRectF QDeclarativeText::boundingRect () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1465 of file qdeclarativetext.cpp.
Referenced by paint().
 {
     Q_D(const QDeclarativeText);
     QRect rect = d->layedOutTextRect;
     if (d->style != Normal)
         rect.adjust(-1, 0, 1, 2);
     // Could include font max left/right bearings to either side of rectangle.
     int h = height();
     switch (d->vAlign) {
     case AlignTop:
         break;
     case AlignBottom:
         rect.moveTop(h - rect.height());
         break;
     case AlignVCenter:
         rect.moveTop((h - rect.height()) / 2);
         break;
     }
     return QRectF(rect);
 }
color()
QColor QDeclarativeText::color () const
Referenced by setColor(), setStyleColor(), and setText().
colorChanged
void QDeclarativeText::colorChanged (const QColor & color) signal
Referenced by setColor().
componentComplete()
void QDeclarativeText::componentComplete () virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1669 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     QDeclarativeItem::componentComplete();
     if (d->updateOnComponentComplete) {
         d->updateOnComponentComplete = false;
         if (d->richText) {
             d->ensureDoc();
             d->doc->setText(d->text);
             d->rightToLeftText = d->doc->toPlainText().isRightToLeft();
         } else {
             d->rightToLeftText = d->text.isRightToLeft();
         }
         d->determineHorizontalAlignment();
         d->updateLayout();
     }
 }
effectiveHAlign()
QDeclarativeText::HAlignment QDeclarativeText::effectiveHAlign () const
Definition at line 1146 of file qdeclarativetext.cpp.
 {
     Q_D(const QDeclarativeText);
     QDeclarativeText::HAlignment effectiveAlignment = d->hAlign;
     if (!d->hAlignImplicit && d->effectiveLayoutMirror) {
         switch (d->hAlign) {
         case QDeclarativeText::AlignLeft:
             effectiveAlignment = QDeclarativeText::AlignRight;
             break;
         case QDeclarativeText::AlignRight:
             effectiveAlignment = QDeclarativeText::AlignLeft;
             break;
         default:
             break;
         }
     }
     return effectiveAlignment;
 }
elideMode()
QDeclarativeText::TextElideMode QDeclarativeText::elideMode () const
Definition at line 1446 of file qdeclarativetext.cpp.
 {
     Q_D(const QDeclarativeText);
     return d->elideMode;
 }
elideModeChanged
void QDeclarativeText::elideModeChanged (TextElideMode mode) signal
Referenced by setElideMode().
font()
QFont QDeclarativeText::font () const
Referenced by setFont(), and ~QDeclarativeText().
fontChanged
void QDeclarativeText::fontChanged (const QFont & font) signal
Referenced by setFont().
geometryChanged()
void QDeclarativeText::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1491 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if ((!d->internalWidthUpdate && newGeometry.width() != oldGeometry.width())
             && (d->wrapMode != QDeclarativeText::NoWrap
                 || d->elideMode != QDeclarativeText::ElideNone
                 || d->hAlign != QDeclarativeText::AlignLeft)) {
         if ((d->singleline || d->maximumLineCountValid) && d->elideMode != QDeclarativeText::ElideNone && widthValid()) {
             // We need to re-elide
             d->updateLayout();
         } else {
             // We just need to re-layout
             d->updateSize();
         }
     }
     QDeclarativeItem::geometryChanged(newGeometry, oldGeometry);
 }
hAlign()
QDeclarativeText::HAlignment QDeclarativeText::hAlign () const
Definition at line 1123 of file qdeclarativetext.cpp.
Referenced by QDeclarativeTextPrivate::mirrorChange(), and QDeclarativeTextPrivate::setHAlign().
 {
     Q_D(const QDeclarativeText);
     return d->hAlign;
 }
horizontalAlignmentChanged
void QDeclarativeText::horizontalAlignmentChanged (HAlignment alignment) signal
lineCount()
int QDeclarativeText::lineCount () const
Referenced by setWrapMode().
lineCountChanged
void QDeclarativeText::lineCountChanged () signal
lineHeight()
qreal QDeclarativeText::lineHeight () const
Referenced by geometryChanged(), and setLineHeight().
lineHeightChanged
void QDeclarativeText::lineHeightChanged (qreal lineHeight) signal
Referenced by setLineHeight().
lineHeightMode()
LineHeightMode QDeclarativeText::lineHeightMode () const
Referenced by setLineHeight().
lineHeightModeChanged
void QDeclarativeText::lineHeightModeChanged (LineHeightMode mode) signal
Referenced by setLineHeightMode().
linkActivated
void QDeclarativeText::linkActivated (const QString & link) signal
Referenced by mouseReleaseEvent().
maximumLineCount()
int QDeclarativeText::maximumLineCount () const
Referenced by setWrapMode().
maximumLineCountChanged
void QDeclarativeText::maximumLineCountChanged () signal
Referenced by setMaximumLineCount().
mousePressEvent()
void QDeclarativeText::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Definition at line 1688 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (!d->richText || !d->doc || d->doc->documentLayout()->anchorAt(event->pos()).isEmpty()) {
         event->setAccepted(false);
         d->activeLink.clear();
     } else {
         d->activeLink = d->doc->documentLayout()->anchorAt(event->pos());
     }
     // ### may malfunction if two of the same links are clicked & dragged onto each other)
     if (!event->isAccepted())
         QDeclarativeItem::mousePressEvent(event);
 }
mouseReleaseEvent()
void QDeclarativeText::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QGraphicsItem.
Definition at line 1707 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
         // ### confirm the link, and send a signal out
     if (d->richText && d->doc && d->activeLink == d->doc->documentLayout()->anchorAt(event->pos()))
         emit linkActivated(d->activeLink);
     else
         event->setAccepted(false);
     if (!event->isAccepted())
         QDeclarativeItem::mouseReleaseEvent(event);
 }
paint()
void QDeclarativeText::paint (QPainter * p, const QStyleOptionGraphicsItem * , QWidget *) virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1614 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->cacheAllTextAsImage || d->style != Normal) {
         d->checkImageCache();
         if (d->imageCache.isNull())
             return;
         bool oldAA = p->testRenderHint(QPainter::Antialiasing);
         bool oldSmooth = p->testRenderHint(QPainter::SmoothPixmapTransform);
         if (d->smooth)
             p->setRenderHints(QPainter::Antialiasing | QPainter::SmoothPixmapTransform, d->smooth);
         QRect br = boundingRect().toRect();
         bool needClip = clip() && (d->imageCache.width() > width() ||
                                    d->imageCache.height() > height());
         if (needClip)
             p->drawPixmap(0, 0, width(), height(), d->imageCache, -br.x(), -br.y(), width(), height());
         else
             p->drawPixmap(br.x(), br.y(), d->imageCache);
         if (d->smooth) {
             p->setRenderHint(QPainter::Antialiasing, oldAA);
             p->setRenderHint(QPainter::SmoothPixmapTransform, oldSmooth);
         }
     } else {
         QRectF bounds = boundingRect();
         bool needClip = clip() && (d->layedOutTextRect.width() > width() ||
                                    d->layedOutTextRect.height() > height());
         if (needClip) {
             p->save();
             p->setClipRect(0, 0, width(), height(), Qt::IntersectClip);
         }
         if (d->richText) {
             QAbstractTextDocumentLayout::PaintContext context;
             context.palette.setColor(QPalette::Text, d->color);
             p->translate(bounds.x(), bounds.y());
             d->doc->documentLayout()->draw(p, context);
             p->translate(-bounds.x(), -bounds.y());
         } else {
             d->drawTextLayout(p, QPointF(0, bounds.y()), false);
         }
         if (needClip) {
             p->restore();
         }
     }
 }
paintedHeight()
qreal QDeclarativeText::paintedHeight () const
Referenced by geometryChanged().
paintedSizeChanged
void QDeclarativeText::paintedSizeChanged () signal
paintedWidth()
qreal QDeclarativeText::paintedWidth () const
Referenced by geometryChanged().
resetHAlign()
void QDeclarativeText::resetHAlign ()
Definition at line 1138 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     d->hAlignImplicit = true;
     if (d->determineHorizontalAlignment() && isComponentComplete())
         d->updateLayout();
 }
resetMaximumLineCount()
void QDeclarativeText::resetMaximumLineCount ()
Definition at line 1325 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     setMaximumLineCount(INT_MAX);
     d->elidePos = QPointF();
     if (d->truncated != false) {
         d->truncated = false;
         emit truncatedChanged();
     }
 }
resourcesLoading()
int QDeclarativeText::resourcesLoading () const
Returns the number of resources (images) that are being loaded asynchronously.
Definition at line 1607 of file qdeclarativetext.cpp.
 {
     Q_D(const QDeclarativeText);
     return d->doc ? d->doc->resourcesLoading() : 0;
 }
setColor()
void QDeclarativeText::setColor (const QColor & c)
Definition at line 1003 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->color == color)
         return;
     d->color = color;
     d->invalidateImageCache();
     emit colorChanged(d->color);
 }
setElideMode()
void QDeclarativeText::setElideMode (QDeclarativeText::TextElideMode mode)
Definition at line 1452 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (mode == d->elideMode)
         return;
     d->elideMode = mode;
     d->updateLayout();
     emit elideModeChanged(d->elideMode);
 }
setFont()
void QDeclarativeText::setFont (const QFont & font)
Definition at line 912 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->sourceFont == font)
         return;
     d->sourceFont = font;
     QFont oldFont = d->font;
     d->font = font;
     if (d->font.pointSizeF() != -1) {
         // 0.5pt resolution
         qreal size = qRound(d->font.pointSizeF()*2.0);
         d->font.setPointSizeF(size/2.0);
     }
     if (oldFont != d->font)
         d->updateLayout();
     emit fontChanged(d->sourceFont);
 }
setHAlign()
void QDeclarativeText::setHAlign (HAlignment align)
Definition at line 1129 of file qdeclarativetext.cpp.
Referenced by QDeclarativeTextPrivate::determineHorizontalAlignment().
 {
     Q_D(QDeclarativeText);
     bool forceAlign = d->hAlignImplicit && d->effectiveLayoutMirror;
     d->hAlignImplicit = false;
     if (d->setHAlign(align, forceAlign) && isComponentComplete())
         d->updateLayout();
 }
setLineHeight()
void QDeclarativeText::setLineHeight (qreal lineHeight)
Definition at line 1559 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if ((d->lineHeight == lineHeight) || (lineHeight < 0.0))
         return;
     d->lineHeight = lineHeight;
     d->updateLayout();
     emit lineHeightChanged(lineHeight);
 }
setLineHeightMode()
void QDeclarativeText::setLineHeightMode (LineHeightMode mode)
Definition at line 1592 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (mode == d->lineHeightMode)
         return;
     d->lineHeightMode = mode;
     d->updateLayout();
     emit lineHeightModeChanged(mode);
 }
setMaximumLineCount()
void QDeclarativeText::setMaximumLineCount (int lines)
Definition at line 1313 of file qdeclarativetext.cpp.
Referenced by resetMaximumLineCount().
 {
     Q_D(QDeclarativeText);
     d->maximumLineCountValid = lines==INT_MAX ? false : true;
     if (d->maximumLineCount != lines) {
         d->maximumLineCount = lines;
         d->updateLayout();
         emit maximumLineCountChanged();
     }
 }
setStyle()
void QDeclarativeText::setStyle (QDeclarativeText::TextStyle style)
Definition at line 1047 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->style == style)
         return;
     // changing to/from Normal requires the boundingRect() to change
     if (isComponentComplete() && (d->style == Normal || style == Normal))
         prepareGeometryChange();
     d->style = style;
     d->invalidateImageCache();
     emit styleChanged(d->style);
 }
setStyleColor()
void QDeclarativeText::setStyleColor (const QColor & c)
Definition at line 1085 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->styleColor == color)
         return;
     d->styleColor = color;
     d->invalidateImageCache();
     emit styleColorChanged(d->styleColor);
 }
setText()
void QDeclarativeText::setText (const QString & n)
Definition at line 950 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->text == n)
         return;
     d->richText = d->format == RichText || (d->format == AutoText && Qt::mightBeRichText(n));
     d->text = n;
     if (isComponentComplete()) {
         if (d->richText) {
             d->ensureDoc();
             d->doc->setText(n);
             d->rightToLeftText = d->doc->toPlainText().isRightToLeft();
         } else {
             d->rightToLeftText = d->text.isRightToLeft();
         }
         d->determineHorizontalAlignment();
     }
     d->updateLayout();
     emit textChanged(d->text);
 }
setTextFormat()
void QDeclarativeText::setTextFormat (TextFormat format)
Definition at line 1399 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (format == d->format)
         return;
     d->format = format;
     bool wasRich = d->richText;
     d->richText = format == RichText || (format == AutoText && Qt::mightBeRichText(d->text));
     if (!wasRich && d->richText && isComponentComplete()) {
         d->ensureDoc();
         d->doc->setText(d->text);
     }
     d->updateLayout();
     emit textFormatChanged(d->format);
 }
setVAlign()
void QDeclarativeText::setVAlign (VAlignment align)
Definition at line 1207 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (d->vAlign == align)
         return;
     if (isComponentComplete())
         prepareGeometryChange();
     d->vAlign = align;
     emit verticalAlignmentChanged(align);
 }
setWrapMode()
void QDeclarativeText::setWrapMode (WrapMode w)
Definition at line 1241 of file qdeclarativetext.cpp.
 {
     Q_D(QDeclarativeText);
     if (mode == d->wrapMode)
         return;
     d->wrapMode = mode;
     d->updateLayout();
     emit wrapModeChanged();
 }
style()
TextStyle QDeclarativeText::style () const
Referenced by setColor(), and setStyle().
styleChanged
void QDeclarativeText::styleChanged (TextStyle style) signal
Referenced by setStyle().
styleColor()
QColor QDeclarativeText::styleColor () const
Referenced by setStyle().
styleColorChanged
void QDeclarativeText::styleColorChanged (const QColor & color) signal
Referenced by setStyleColor().
text()
QString QDeclarativeText::text () const
Referenced by QDeclarativeTextPrivate::determineHorizontalAlignment(), and setFont().
textChanged
void QDeclarativeText::textChanged (const QString & text) signal
Referenced by setText().
textFormat()
TextFormat QDeclarativeText::textFormat () const
Referenced by resetMaximumLineCount().
textFormatChanged
void QDeclarativeText::textFormatChanged (TextFormat textFormat) signal
Referenced by setTextFormat().
truncated()
bool QDeclarativeText::truncated () const
Referenced by setWrapMode().
truncatedChanged
void QDeclarativeText::truncatedChanged () signal
Referenced by resetMaximumLineCount().
vAlign()
QDeclarativeText::VAlignment QDeclarativeText::vAlign () const
Definition at line 1201 of file qdeclarativetext.cpp.
 {
     Q_D(const QDeclarativeText);
     return d->vAlign;
 }
verticalAlignmentChanged
void QDeclarativeText::verticalAlignmentChanged (VAlignment alignment) signal
Referenced by setVAlign().
wrapMode()
WrapMode QDeclarativeText::wrapMode () const
Referenced by setVAlign().
wrapModeChanged
void QDeclarativeText::wrapModeChanged () signal
Referenced by setWrapMode().
Properties
color
QColor QDeclarativeText::color private
Definition at line 69 of file qdeclarativetext_p.h.
elide
TextElideMode QDeclarativeText::elide private
Definition at line 80 of file qdeclarativetext_p.h.
font
QFont QDeclarativeText::font private
Definition at line 68 of file qdeclarativetext_p.h.
horizontalAlignment
HAlignment QDeclarativeText::horizontalAlignment private
Definition at line 72 of file qdeclarativetext_p.h.
lineCount
int QDeclarativeText::lineCount private
Definition at line 75 of file qdeclarativetext_p.h.
lineHeight
qreal QDeclarativeText::lineHeight private
Definition at line 83 of file qdeclarativetext_p.h.
lineHeightMode
QDeclarativeText::LineHeightMode QDeclarativeText::lineHeightMode private
Definition at line 84 of file qdeclarativetext_p.h.
maximumLineCount
int QDeclarativeText::maximumLineCount private
Definition at line 77 of file qdeclarativetext_p.h.
paintedHeight
qreal QDeclarativeText::paintedHeight private
Definition at line 82 of file qdeclarativetext_p.h.
paintedWidth
qreal QDeclarativeText::paintedWidth private
Definition at line 81 of file qdeclarativetext_p.h.
style
QDeclarativeText::TextStyle QDeclarativeText::style private
Definition at line 70 of file qdeclarativetext_p.h.
styleColor
QColor QDeclarativeText::styleColor private
Definition at line 71 of file qdeclarativetext_p.h.
text
QString QDeclarativeText::text private
Definition at line 67 of file qdeclarativetext_p.h.
Referenced by QTextDocumentWithImageResources::requestFinished().
textFormat
QDeclarativeText::TextFormat QDeclarativeText::textFormat private
Definition at line 79 of file qdeclarativetext_p.h.
truncated
bool QDeclarativeText::truncated private
Definition at line 76 of file qdeclarativetext_p.h.
verticalAlignment
VAlignment QDeclarativeText::verticalAlignment private
Definition at line 73 of file qdeclarativetext_p.h.
wrapMode
QDeclarativeText::WrapMode QDeclarativeText::wrapMode private
Definition at line 74 of file qdeclarativetext_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativetext_p.h
/src/declarative/graphicsitems/qdeclarativetext.cpp