Qt 4.8: QScriptDebuggerAgent Class Reference
QScriptDebuggerAgent Class Reference
This class implements a state machine that uses the low-level events reported by the QScriptEngineAgent interface to implement debugging- specific functionality such as stepping and breakpoints.
#include <qscriptdebuggeragent_p.h>
Public Functions
QScriptBreakpointData breakpointData (int id) const
Returns the data associated with the breakpoint with the given id.
QScriptBreakpointMap breakpoints () const
Returns all breakpoints.
QList< qint64 > contextIds () const
void contextPop ()
Reimplemented Function
void contextPush ()
Reimplemented Function
QPair< QList< qint64 >, QList< qint64 > > contextsCheckpoint ()
void deleteAllBreakpoints ()
Deletes all breakpoints.
bool deleteBreakpoint (int id)
Deletes the breakpoint with the given id.
void enterContinueMode ()
Instructs the agent to continue evaluation.
void enterInterruptMode ()
Instructs the agent to interrupt evaluation.
void enterReturnByForceMode (int contextIndex, const QScriptValue &value)
void enterRunToLocationMode (const QString &fileName, int lineNumber)
Instructs the agent to continue evaluation until the location described by fileName and lineNumber is reached.
void enterRunToLocationMode (qint64 scriptId, int lineNumber)
Instructs the agent to continue evaluation until the location described by scriptId and lineNumber is reached.
void enterStepIntoMode (int count=1)
Instructs the agent to perform a "step into" operation.
void enterStepOutMode ()
Instructs the agent to perform a "step out" operation.
void enterStepOverMode (int count=1)
Instructs the agent to perform a "step over" operation.
void exceptionCatch (qint64 scriptId, const QScriptValue &exception)
Reimplemented Function
void exceptionThrow (qint64 scriptId, const QScriptValue &exception, bool hasHandler)
Reimplemented Function
QVariant extension (Extension extension, const QVariant &argument=QVariant())
Reimplemented Function
void functionEntry (qint64 scriptId)
Reimplemented Function
void functionExit (qint64 scriptId, const QScriptValue &returnValue)
Reimplemented Function
void nullifyBackendPointer ()
void positionChange (qint64 scriptId, int lineNumber, int columnNumber)
Reimplemented Function
QScriptDebuggerAgent (QScriptDebuggerBackendPrivate *backend, QScriptEngine *engine)
Constructs a new agent for the given engine.
qint64 resolveScript (const QString &fileName) const
Returns the identifier of the script that has the given fileName, or -1 if there is no such script.
QScriptScriptData scriptData (qint64 id) const
Returns the data associated with the script with the given id.
void scriptLoad (qint64 id, const QString &program, const QString &fileName, int baseLineNumber)
Reimplemented Function
QScriptScriptMap scripts () const
Returns all scripts.
void scriptsCheckpoint ()
Checkpoints the current scripts.
QPair< QList< qint64 >, QList< qint64 > > scriptsDelta () const
Returns the difference between the current checkpoint and the previous checkpoint.
void scriptUnload (qint64 id)
Reimplemented Function
int setBreakpoint (const QScriptBreakpointData &data)
Sets a breakpoint defined by the given data.
bool setBreakpointData (int id, const QScriptBreakpointData &data)
Sets the data associated with the breakpoint with the given id.
bool supportsExtension (Extension extension) const
Reimplemented Function
~QScriptDebuggerAgent ()
Destroys this QScriptDebuggerAgent.
Public Functions inherited from QScriptEngineAgent
QScriptEngine * engine () const
Returns the QScriptEngine that this agent is associated with.
QScriptEngineAgent (QScriptEngine *engine)
Constructs a QScriptEngineAgent object for the given engine.
virtual ~QScriptEngineAgent ()
Destroys this QScriptEngineAgent.
Properties
QScriptDebuggerAgentPrivate * d_ptr
Additional Inherited Members
Public Types inherited from QScriptEngineAgent
enum Extension { DebuggerInvocationRequest }
This enum specifies the possible extensions to a QScriptEngineAgent.
Protected Functions inherited from QScriptEngineAgent
QScriptEngineAgent (QScriptEngineAgentPrivate &dd, QScriptEngine *engine)
Protected Variables inherited from QScriptEngineAgent
QScopedPointer< QScriptEngineAgentPrivate > d_ptr
Detailed Description
This class implements a state machine that uses the low-level events reported by the QScriptEngineAgent interface to implement debugging- specific functionality such as stepping and breakpoints.
Since
4.5
Warning
This function is not part of the public interface.
It is used internally by the QScriptDebuggerBackend class.
Definition at line 68 of file qscriptdebuggeragent_p.h.
Constructors and Destructors
QScriptDebuggerAgent()
QScriptDebuggerAgent::QScriptDebuggerAgent (QScriptDebuggerBackendPrivate * backend, QScriptEngine * engine)
Constructs a new agent for the given engine.
The agent will report debugging-related events (e.g. step completion) to the given backend.
Definition at line 92 of file qscriptdebuggeragent.cpp.
     : QScriptEngineAgent(engine), d_ptr(new QScriptDebuggerAgentPrivate())
 {
     Q_D(QScriptDebuggerAgent);
     d->backend = backend;
     QScriptContext *ctx = engine->currentContext();
     while (ctx) {
         d->scriptIdStack.append(QList<qint64>());
         d->contextIdStack.append(d->nextContextId);
         ++d->nextContextId;
         ctx = ctx->parentContext();
     }
 }
~QScriptDebuggerAgent()
QScriptDebuggerAgent::~QScriptDebuggerAgent ()
Destroys this QScriptDebuggerAgent.
Definition at line 111 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     if (d->backend)
         d->backend->agentDestroyed(this);
     delete d;
 }
Functions
breakpointData()
QScriptBreakpointData QScriptDebuggerAgent::breakpointData (int id) const
Returns the data associated with the breakpoint with the given id.
Definition at line 335 of file qscriptdebuggeragent.cpp.
 {
     Q_D(const QScriptDebuggerAgent);
     return d->breakpoints.value(id);
 }
breakpoints()
QScriptBreakpointMap QScriptDebuggerAgent::breakpoints () const
Returns all breakpoints.
Definition at line 358 of file qscriptdebuggeragent.cpp.
 {
     Q_D(const QScriptDebuggerAgent);
     return d->breakpoints;
 }
contextIds()
QList< qint64 > QScriptDebuggerAgent::contextIds () const
Definition at line 424 of file qscriptdebuggeragent.cpp.
 {
     Q_D(const QScriptDebuggerAgent);
     return d->contextIdStack;
 }
contextPop()
void QScriptDebuggerAgent::contextPop () virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 510 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->scriptIdStack.removeLast();
     d->contextIdStack.removeFirst();
 }
contextPush()
void QScriptDebuggerAgent::contextPush () virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 499 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->scriptIdStack.append(QList<qint64>());
     d->contextIdStack.prepend(d->nextContextId);
     ++d->nextContextId;
 }
contextsCheckpoint()
QPair< QList< qint64 >, QList< qint64 > > QScriptDebuggerAgent::contextsCheckpoint ()
Definition at line 430 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     int i = d->checkpointContextIdStack.size() - 1;
     int j = d->contextIdStack.size() - 1;
     for ( ; (i >= 0) && (j >= 0); --i, --j) {
         if (d->checkpointContextIdStack.at(i) != d->contextIdStack.at(j))
             break;
     }
     QList<qint64> removed = d->checkpointContextIdStack.mid(0, i+1);
     QList<qint64> added = d->contextIdStack.mid(0, j+1);
     d->checkpointContextIdStack = d->contextIdStack;
     return qMakePair(removed, added);
 }
deleteAllBreakpoints()
void QScriptDebuggerAgent::deleteAllBreakpoints ()
Deletes all breakpoints.
Definition at line 323 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->breakpoints.clear();
     d->resolvedBreakpoints.clear();
     d->unresolvedBreakpoints.clear();
 }
deleteBreakpoint()
bool QScriptDebuggerAgent::deleteBreakpoint (int id)
Deletes the breakpoint with the given id.
Returns true if the breakpoint was deleted, false if no such breakpoint exists.
Definition at line 272 of file qscriptdebuggeragent.cpp.
Referenced by positionChange().
 {
     Q_D(QScriptDebuggerAgent);
     if (!d->breakpoints.contains(id))
         return false;
     d->breakpoints.remove(id);
     bool found = false;
     {
         QHash<qint64, QList<int> >::iterator it;
         it = d->resolvedBreakpoints.begin();
         for ( ; !found && (it != d->resolvedBreakpoints.end()); ) {
             QList<int> &lst = it.value();
             Q_ASSERT(!lst.isEmpty());
             for (int i = 0; i < lst.size(); ++i) {
                 if (lst.at(i) == id) {
                     lst.removeAt(i);
                     found = true;
                     break;
                 }
             }
             if (lst.isEmpty())
                 it = d->resolvedBreakpoints.erase(it);
             else
                 ++it;
         }
     }
     if (!found) {
         QHash<QString, QList<int> >::iterator it;
         it = d->unresolvedBreakpoints.begin();
         for ( ; !found && (it != d->unresolvedBreakpoints.end()); ) {
             QList<int> &lst = it.value();
             Q_ASSERT(!lst.isEmpty());
             for (int i = 0; i < lst.size(); ++i) {
                 if (lst.at(i) == id) {
                     lst.removeAt(i);
                     found = true;
                     break;
                 }
             }
             if (lst.isEmpty())
                 it = d->unresolvedBreakpoints.erase(it);
             else
                 ++it;
         }
     }
     return found;
 }
enterContinueMode()
void QScriptDebuggerAgent::enterContinueMode ()
Instructs the agent to continue evaluation.
This function returns immediately.
Definition at line 168 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->state = QScriptDebuggerAgentPrivate::NoState;
 }
enterInterruptMode()
void QScriptDebuggerAgent::enterInterruptMode ()
Instructs the agent to interrupt evaluation.
This function returns immediately.
Definition at line 178 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->state = QScriptDebuggerAgentPrivate::InterruptingState;
 }
enterReturnByForceMode()
void QScriptDebuggerAgent::enterReturnByForceMode (int contextIndex, const QScriptValue & value)
Definition at line 212 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->returnCounter = contextIndex + 1;
     d->returnValue = QScriptValue();
     d->state = QScriptDebuggerAgentPrivate::ReturningByForceState;
     // throw an exception; we will catch it when the proper frame is popped
     engine()->currentContext()->throwValue(value);
 }
enterRunToLocationMode() [1/2]
void QScriptDebuggerAgent::enterRunToLocationMode (const QString & fileName, int lineNumber)
Instructs the agent to continue evaluation until the location described by fileName and lineNumber is reached.
This function returns immediately.
Definition at line 189 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->targetFileName = fileName;
     d->targetLineNumber = lineNumber;
     d->targetScriptId = resolveScript(fileName);
     d->state = QScriptDebuggerAgentPrivate::RunningToLocationState;
 }
enterRunToLocationMode() [2/2]
void QScriptDebuggerAgent::enterRunToLocationMode (qint64 scriptId, int lineNumber)
Instructs the agent to continue evaluation until the location described by scriptId and lineNumber is reached.
This function returns immediately.
Definition at line 203 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->targetScriptId = scriptId;
     d->targetFileName = QString();
     d->targetLineNumber = lineNumber;
     d->state = QScriptDebuggerAgentPrivate::RunningToLocationState;
 }
enterStepIntoMode()
void QScriptDebuggerAgent::enterStepIntoMode (int count = 1)
Instructs the agent to perform a "step into" operation.
This function returns immediately. The agent will report step completion at a later time, i.e. when script statements are evaluated.
Definition at line 124 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->state = QScriptDebuggerAgentPrivate::SteppingIntoState;
     d->stepCount = count;
     d->stepResult = QScriptValue();
 }
enterStepOutMode()
void QScriptDebuggerAgent::enterStepOutMode ()
Instructs the agent to perform a "step out" operation.
This function returns immediately. The agent will report step completion at a later time, i.e. when script statements are evaluated.
Definition at line 154 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->state = QScriptDebuggerAgentPrivate::SteppingOutState;
     if (engine()->isEvaluating())
         d->stepDepth = 0;
     else
         d->stepDepth = -1;
 }
enterStepOverMode()
void QScriptDebuggerAgent::enterStepOverMode (int count = 1)
Instructs the agent to perform a "step over" operation.
This function returns immediately. The agent will report step completion at a later time, i.e. when script statements are evaluated.
Definition at line 137 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->state = QScriptDebuggerAgentPrivate::SteppingOverState;
     if (engine()->isEvaluating())
         d->stepDepth = 0;
     else
         d->stepDepth = -1;
     d->stepCount = count;
     d->stepResult = QScriptValue();
 }
exceptionCatch()
void QScriptDebuggerAgent::exceptionCatch (qint64 scriptId, const QScriptValue & exception) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 697 of file qscriptdebuggeragent.cpp.
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(exception);
 }
exceptionThrow()
void QScriptDebuggerAgent::exceptionThrow (qint64 scriptId, const QScriptValue & exception, bool hasHandler) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 680 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     if (d->state == QScriptDebuggerAgentPrivate::ReturningByForceState) {
         // we threw this exception ourselves, so ignore it for now
         // (see functionExit()).
         return;
     }
     if (d->backend)
         d->backend->exception(scriptId, exception, hasHandler);
 }
extension()
QVariant QScriptDebuggerAgent::extension (Extension extension, const QVariant & argument = QVariant()) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 715 of file qscriptdebuggeragent.cpp.
 {
     Q_UNUSED(extension);
     Q_D(QScriptDebuggerAgent);
     Q_ASSERT(extension == DebuggerInvocationRequest);
     QVariantList lst = argument.toList();
     qint64 scriptId = lst.at(0).toLongLong();
     int lineNumber = lst.at(1).toInt();
     int columnNumber = lst.at(2).toInt();
     d->state = QScriptDebuggerAgentPrivate::NoState;
     if (d->backend) {
         d->backend->debuggerInvocationRequest(
             scriptId, lineNumber, columnNumber);
     }
     return QVariant();
 }
functionEntry()
void QScriptDebuggerAgent::functionEntry (qint64 scriptId) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 520 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     QList<qint64> &ids = d->scriptIdStack.last();
     ids.append(scriptId);
     if ((d->state == QScriptDebuggerAgentPrivate::SteppingOverState)
         || (d->state == QScriptDebuggerAgentPrivate::SteppingOutState)) {
         ++d->stepDepth;
     }
 }
functionExit()
void QScriptDebuggerAgent::functionExit (qint64 scriptId, const QScriptValue & returnValue) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 534 of file qscriptdebuggeragent.cpp.
 {
     Q_UNUSED(scriptId);
     Q_D(QScriptDebuggerAgent);
     QList<qint64> &ids = d->scriptIdStack.last();
     ids.removeLast();
     if (d->state == QScriptDebuggerAgentPrivate::SteppingOverState) {
         --d->stepDepth;
     } else if (d->state == QScriptDebuggerAgentPrivate::SteppingOutState) {
         if (--d->stepDepth < 0) {
             d->stepResult = returnValue;
             d->state = QScriptDebuggerAgentPrivate::SteppedOutState;
         }
     } else if (d->state == QScriptDebuggerAgentPrivate::ReturningByForceState) {
         if (--d->returnCounter == 0) {
             d->returnValue = returnValue;
             d->state = QScriptDebuggerAgentPrivate::ReturnedByForceState;
             engine()->clearExceptions();
         }
     }
 }
nullifyBackendPointer()
void QScriptDebuggerAgent::nullifyBackendPointer ()
Definition at line 445 of file qscriptdebuggeragent.cpp.
Referenced by QScriptDebuggerBackendPrivate::~QScriptDebuggerBackendPrivate().
 {
     Q_D(QScriptDebuggerAgent);
     d->backend = 0;
 }
positionChange()
void QScriptDebuggerAgent::positionChange (qint64 scriptId, int lineNumber, int columnNumber) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 560 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     if (engine()->processEventsInterval() == -1) {
         // see if it's time to call processEvents()
         if ((++d->statementCounter % 25000) == 0) {
             if (!d->processEventsTimer.isNull()) {
                 if (d->processEventsTimer.elapsed() > 30) {
                     QCoreApplication::processEvents();
                     d->processEventsTimer.restart();
                 }
             } else {
                 d->processEventsTimer.start();
             }
         }
     }
     // check breakpoints
     {
         QList<int> lst = d->resolvedBreakpoints.value(scriptId);
         for (int i = 0; i < lst.size(); ++i) {
             int id = lst.at(i);
             QScriptBreakpointData &data = d->breakpoints[id];
             if (!data.isEnabled())
                 continue;
             if (data.lineNumber() != lineNumber)
                 continue;
             if (!data.condition().isEmpty()) {
                 // ### careful, evaluate() can cause an exception
                 // ### disable callbacks in nested evaluate?
                 QScriptDebuggerAgentPrivate::State was = d->state;
                 d->state = QScriptDebuggerAgentPrivate::NoState;
                 QScriptValue ret = engine()->evaluate(
                     data.condition(),
                     QString::fromLatin1("Breakpoint %0 condition checker").arg(id));
                 if (!ret.isError())
                     d->state = was;
                 if (!ret.toBoolean())
                     continue;
             }
             if (!data.hit())
                 continue;
             d->hitBreakpointId = id;
             d->state = QScriptDebuggerAgentPrivate::BreakpointState;
         }
     }
     switch (d->state) {
     case QScriptDebuggerAgentPrivate::NoState:
     case QScriptDebuggerAgentPrivate::SteppingOutState:
     case QScriptDebuggerAgentPrivate::ReturningByForceState:
         // Do nothing
         break;
     case QScriptDebuggerAgentPrivate::SteppingIntoState:
         if (--d->stepCount == 0) {
             d->state = QScriptDebuggerAgentPrivate::NoState;
             if (d->backend)
                 d->backend->stepped(scriptId, lineNumber, columnNumber, QScriptValue());
         }
         break;
     case QScriptDebuggerAgentPrivate::SteppingOverState:
         if ((d->stepDepth > 0) || (--d->stepCount != 0))
             break;
         // fallthrough
     case QScriptDebuggerAgentPrivate::SteppedOverState:
         d->state = QScriptDebuggerAgentPrivate::NoState;
         if (d->backend)
             d->backend->stepped(scriptId, lineNumber, columnNumber, d->stepResult);
         break;
     case QScriptDebuggerAgentPrivate::SteppedOutState:
         d->state = QScriptDebuggerAgentPrivate::NoState;
         if (d->backend)
             d->backend->stepped(scriptId, lineNumber, columnNumber, d->stepResult);
         break;
     case QScriptDebuggerAgentPrivate::RunningToLocationState:
         if (((lineNumber == d->targetLineNumber) || (d->targetLineNumber == -1))
             && (scriptId == d->targetScriptId)) {
             d->state = QScriptDebuggerAgentPrivate::NoState;
             if (d->backend)
                 d->backend->locationReached(scriptId, lineNumber, columnNumber);
         }
         break;
     case QScriptDebuggerAgentPrivate::InterruptingState:
         d->state = QScriptDebuggerAgentPrivate::NoState;
         if (d->backend)
             d->backend->interrupted(scriptId, lineNumber, columnNumber);
         break;
     case QScriptDebuggerAgentPrivate::BreakpointState:
         d->state = QScriptDebuggerAgentPrivate::NoState;
         if (d->backend)
             d->backend->breakpoint(scriptId, lineNumber, columnNumber, d->hitBreakpointId);
         if (d->breakpoints.value(d->hitBreakpointId).isSingleShot())
             deleteBreakpoint(d->hitBreakpointId);
         break;
     case QScriptDebuggerAgentPrivate::ReturnedByForceState:
         d->state = QScriptDebuggerAgentPrivate::NoState;
         if (d->backend)
             d->backend->forcedReturn(scriptId, lineNumber, columnNumber, d->returnValue);
         break;
     case QScriptDebuggerAgentPrivate::SteppedIntoState:
     case QScriptDebuggerAgentPrivate::ReachedLocationState:
     case QScriptDebuggerAgentPrivate::InterruptedState:
 // ### deal with the case when code is evaluated while we're already paused
 //        Q_ASSERT(false);
         break;
     }
 }
resolveScript()
qint64 QScriptDebuggerAgent::resolveScript (const QString & fileName) const
Returns the identifier of the script that has the given fileName, or -1 if there is no such script.
Definition at line 413 of file qscriptdebuggeragent.cpp.
Referenced by enterRunToLocationMode().
 {
     Q_D(const QScriptDebuggerAgent);
     QScriptScriptMap::const_iterator it;
     for (it = d->scripts.constBegin(); it != d->scripts.constEnd(); ++it) {
         if (it.value().fileName() == fileName)
             return it.key();
     }
     return -1;
 }
scriptData()
QScriptScriptData QScriptDebuggerAgent::scriptData (qint64 id) const
Returns the data associated with the script with the given id.
Definition at line 376 of file qscriptdebuggeragent.cpp.
Referenced by QScriptDebuggerBackendPrivate::breakpoint(), QScriptDebuggerBackendPrivate::debuggerInvocationRequest(), QScriptDebuggerBackendPrivate::exception(), QScriptDebuggerBackendPrivate::forcedReturn(), QScriptDebuggerBackendPrivate::interrupted(), QScriptDebuggerBackendPrivate::locationReached(), and QScriptDebuggerBackendPrivate::stepped().
 {
     Q_D(const QScriptDebuggerAgent);
     return d->scripts.value(id);
 }
scriptLoad()
void QScriptDebuggerAgent::scriptLoad (qint64 id, const QString & program, const QString & fileName, int baseLineNumber) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 454 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     QScriptScriptData data = QScriptScriptData(program, fileName, baseLineNumber);
     d->scripts.insert(id, data);
     if ((d->state == QScriptDebuggerAgentPrivate::RunningToLocationState)
         && (d->targetScriptId == -1)
         && ((d->targetFileName == fileName) || d->targetFileName.isEmpty())) {
         d->targetScriptId = id;
     }
     if (!fileName.isEmpty()) {
         QList<int> lst = d->unresolvedBreakpoints.take(fileName);
         if (!lst.isEmpty())
             d->resolvedBreakpoints.insert(id, lst);
     }
 }
scripts()
QScriptScriptMap QScriptDebuggerAgent::scripts () const
Returns all scripts.
Definition at line 367 of file qscriptdebuggeragent.cpp.
 {
     Q_D(const QScriptDebuggerAgent);
     return d->scripts;
 }
scriptsCheckpoint()
void QScriptDebuggerAgent::scriptsCheckpoint ()
Checkpoints the current scripts.
Definition at line 385 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     d->previousCheckpointScripts = d->checkpointScripts;
     d->checkpointScripts = d->scripts;
 }
scriptsDelta()
QPair< QList< qint64 >, QList< qint64 > > QScriptDebuggerAgent::scriptsDelta () const
Returns the difference between the current checkpoint and the previous checkpoint.
The first item in the pair is a list containing the identifiers of the scripts that were added. The second item in the pair is a list containing the identifiers of the scripts that were removed.
Definition at line 399 of file qscriptdebuggeragent.cpp.
 {
     Q_D(const QScriptDebuggerAgent);
     QSet<qint64> prevSet = d->previousCheckpointScripts.keys().toSet();
     QSet<qint64> currSet = d->checkpointScripts.keys().toSet();
     QSet<qint64> addedScriptIds = currSet - prevSet;
     QSet<qint64> removedScriptIds = prevSet - currSet;
     return qMakePair(addedScriptIds.toList(), removedScriptIds.toList());
 }
scriptUnload()
void QScriptDebuggerAgent::scriptUnload (qint64 id) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 477 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     QScriptScriptData data = d->scripts.take(id);
     QString fileName = data.fileName();
     if ((d->state == QScriptDebuggerAgentPrivate::RunningToLocationState)
         && (d->targetScriptId == id)) {
         d->targetScriptId = -1;
         d->targetFileName = fileName;
     }
     if (!fileName.isEmpty()) {
         QList<int> lst = d->resolvedBreakpoints.take(id);
         if (!lst.isEmpty())
             d->unresolvedBreakpoints.insert(fileName, lst);
     }
 }
setBreakpoint()
int QScriptDebuggerAgent::setBreakpoint (const QScriptBreakpointData & data)
Sets a breakpoint defined by the given data.
Returns an integer that uniquely identifies the new breakpoint, or -1 if setting the breakpoint failed.
Definition at line 227 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     qint64 scriptId = data.scriptId();
     if (scriptId != -1) {
         if (!d->scripts.contains(scriptId)) {
             // that script has been unloaded, so invalidate the ID
             scriptId = -1;
             const_cast<QScriptBreakpointData&>(data).setScriptId(-1);
         } else if (data.fileName().isEmpty()) {
             QString fileName = d->scripts[scriptId].fileName();
             const_cast<QScriptBreakpointData&>(data).setFileName(fileName);
         }
     }
     int id = d->nextBreakpointId;
     ++d->nextBreakpointId;
     if (scriptId != -1) {
         d->resolvedBreakpoints[scriptId].append(id);
     } else {
         QString fileName = data.fileName();
         bool resolved = false;
         QScriptScriptMap::const_iterator it;
         for (it = d->scripts.constBegin(); it != d->scripts.constEnd(); ++it) {
             if (it.value().fileName() == fileName) {
                 d->resolvedBreakpoints[it.key()].append(id);
                 resolved = true;
                 break;
             }
         }
         if (!resolved)
             d->unresolvedBreakpoints[fileName].append(id);
     }
     d->breakpoints.insert(id, data);
     return id;
 }
setBreakpointData()
bool QScriptDebuggerAgent::setBreakpointData (int id, const QScriptBreakpointData & data)
Sets the data associated with the breakpoint with the given id.
Definition at line 345 of file qscriptdebuggeragent.cpp.
 {
     Q_D(QScriptDebuggerAgent);
     if (!d->breakpoints.contains(id))
         return false;
     d->breakpoints[id] = data;
     return true;
 }
supportsExtension()
bool QScriptDebuggerAgent::supportsExtension (Extension extension) const virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 707 of file qscriptdebuggeragent.cpp.
 {
     return (extension == DebuggerInvocationRequest);
 }
Properties
d_ptr
QScriptDebuggerAgentPrivate* QScriptDebuggerAgent::d_ptr private
Definition at line 128 of file qscriptdebuggeragent_p.h.
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggeragent_p.h
/src/scripttools/debugging/qscriptdebuggeragent.cpp