Qt 4.8: QStackedLayout Class Reference
QStackedLayout Class Reference
The QStackedLayout class provides a stack of widgets where only one widget is visible at a time.
#include <qstackedlayout.h>
Public Types
enum StackingMode { StackOne, StackAll }
This enum specifies how the layout handles its child widgets regarding their visibility.
Public Types inherited from QLayout
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Public Slots
void setCurrentIndex (int index)
void setCurrentWidget (QWidget *w)
Sets the current widget to be the specified widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentChanged (int index)
This signal is emitted whenever the current widget in the layout changes.
void widgetRemoved (int index)
This signal is emitted whenever a widget is removed from the layout.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addItem (QLayoutItem *item)
Reimplemented Function
int addWidget (QWidget *w)
Adds the given widget to the end of this layout and returns the index position of the widget.
int count () const
the number of widgets contained in the layout
int currentIndex () const
QWidget * currentWidget () const
Returns the current widget, or 0 if there are no widgets in this layout.
int insertWidget (int index, QWidget *w)
Inserts the given widget at the given index in this QStackedLayout.
QLayoutItem * itemAt (int) const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
QStackedLayout ()
Constructs a QStackedLayout with no parent.
QStackedLayout (QWidget *parent)
Constructs a new QStackedLayout with the given parent.
QStackedLayout (QLayout *parentLayout)
Constructs a new QStackedLayout and inserts it into the given parentLayout.
void setGeometry (const QRect &rect)
Reimplemented Function
void setStackingMode (StackingMode stackingMode)
QSize sizeHint () const
Reimplemented Function
StackingMode stackingMode () const
QLayoutItem * takeAt (int)
Reimplemented Function
QWidget * widget (int) const
Returns the widget at the given index, or 0 if there is no widget at the given position.
~QStackedLayout ()
Destroys this QStackedLayout.
Public Functions inherited from QLayout
bool activate ()
Redoes the layout for parentWidget() if necessary.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
virtual int indexOf (QWidget *) const
Searches for widget widget in this layout (not including child layouts).
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
QLayout * layout ()
Reimplemented Function
int margin () const
QSize maximumSize () const
Returns the maximum size of this layout.
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual bool hasHeightForWidth () const
Returns true if this layout's preferred height depends on its width; otherwise returns false.
virtual int heightForWidth (int) const
Returns the preferred height for this layout item, given the width w.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Properties
int currentIndex
the index position of the widget that is visible
StackingMode stackingMode
determines the way visibility of child widgets are handled.
Additional Inherited Members
Static Public Functions inherited from QLayout
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QLayout
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QStackedLayout class provides a stack of widgets where only one widget is visible at a time.
QStackedLayout can be used to create a user interface similar to the one provided by QTabWidget. There is also a convenience QStackedWidget class built on top of QStackedLayout.
A QStackedLayout can be populated with a number of child widgets ("pages"). For example:
    QWidget *firstPageWidget = new QWidget;
    QWidget *secondPageWidget = new QWidget;
    QWidget *thirdPageWidget = new QWidget;
    QStackedLayout *stackedLayout = new QStackedLayout;
    stackedLayout->addWidget(firstPageWidget);
    stackedLayout->addWidget(secondPageWidget);
    stackedLayout->addWidget(thirdPageWidget);
    QVBoxLayout *mainLayout = new QVBoxLayout;
    mainLayout->addLayout(stackedLayout);
    setLayout(mainLayout);
QStackedLayout provides no intrinsic means for the user to switch page. This is typically done through a QComboBox or a QListWidget that stores the titles of the QStackedLayout's pages. For example:
    QComboBox *pageComboBox = new QComboBox;
    pageComboBox->addItem(tr("Page 1"));
    pageComboBox->addItem(tr("Page 2"));
    pageComboBox->addItem(tr("Page 3"));
    connect(pageComboBox, SIGNAL(activated(int)),
            stackedLayout, SLOT(setCurrentIndex(int)));
When populating a layout, the widgets are added to an internal list. The indexOf() function returns the index of a widget in that list. The widgets can either be added to the end of the list using the addWidget() function, or inserted at a given index using the insertWidget() function. The removeWidget() function removes the widget at the given index from the layout. The number of widgets contained in the layout, can be obtained using the count() function.
The widget() function returns the widget at a given index position. The index of the widget that is shown on screen is given by currentIndex() and can be changed using setCurrentIndex(). In a similar manner, the currently shown widget can be retrieved using the currentWidget() function, and altered using the setCurrentWidget() function.
Whenever the current widget in the layout changes or a widget is removed from the layout, the currentChanged() and widgetRemoved() signals are emitted respectively.
See also
QStackedWidget, QTabWidget
Definition at line 55 of file qstackedlayout.h.
Enumerations
StackingMode
enum QStackedLayout::StackingMode
This enum specifies how the layout handles its child widgets regarding their visibility.
Since
4.4
StackOne Only the current widget is visible. This is the default.
StackAll All widgets are visible. The current widget is merely raised.
Enumerator
StackOne
StackAll
Definition at line 65 of file qstackedlayout.h.
                       {
         StackOne,
         StackAll
     };
Constructors and Destructors
QStackedLayout() [1/3]
QStackedLayout::QStackedLayout ()
Constructs a QStackedLayout with no parent.
This QStackedLayout must be installed on a widget later on to become effective.
See also
addWidget(), insertWidget()
Definition at line 153 of file qstackedlayout.cpp.
     : QLayout(*new QStackedLayoutPrivate, 0, 0)
 {
 }
QStackedLayout() [2/3]
QStackedLayout::QStackedLayout (QWidget * parent) explicit
Constructs a new QStackedLayout with the given parent.
This layout will install itself on the parent widget and manage the geometry of its children.
Definition at line 164 of file qstackedlayout.cpp.
     : QLayout(*new QStackedLayoutPrivate, 0, parent)
 {
 }
QStackedLayout() [3/3]
QStackedLayout::QStackedLayout (QLayout * parentLayout) explicit
Constructs a new QStackedLayout and inserts it into the given parentLayout.
Definition at line 173 of file qstackedlayout.cpp.
     : QLayout(*new QStackedLayoutPrivate, parentLayout, 0)
 {
 }
~QStackedLayout()
QStackedLayout::~QStackedLayout ()
Destroys this QStackedLayout.
Note that the layout's widgets are not destroyed.
Definition at line 182 of file qstackedlayout.cpp.
 {
     Q_D(QStackedLayout);
     qDeleteAll(d->list);
 }
Functions
addItem()
void QStackedLayout::addItem (QLayoutItem * item) virtual
Reimplemented Function
Implements QLayout.
Definition at line 429 of file qstackedlayout.cpp.
 {
     QWidget *widget = item->widget();
     if (widget) {
         addWidget(widget);
         delete item;
     } else {
         qWarning("QStackedLayout::addItem: Only widgets can be added");
     }
 }
addWidget()
int QStackedLayout::addWidget (QWidget * widget)
Adds the given widget to the end of this layout and returns the index position of the widget.
If the QStackedLayout is empty before this function is called, the given widget becomes the current widget.
See also
insertWidget(), removeWidget(), setCurrentWidget()
Definition at line 197 of file qstackedlayout.cpp.
Referenced by addItem().
 {
     Q_D(QStackedLayout);
     return insertWidget(d->list.count(), widget);
 }
count()
int QStackedLayout::count () const virtual
the number of widgets contained in the layout
See also
currentIndex(), widget()
Implements QLayout.
Definition at line 419 of file qstackedlayout.cpp.
Referenced by QStackedLayoutHFW::hasHeightForWidth(), and QStackedLayoutHFW::heightForWidth().
 {
     Q_D(const QStackedLayout);
     return d->list.size();
 }
currentChanged
void QStackedLayout::currentChanged (int index) signal
This signal is emitted whenever the current widget in the layout changes.
The index specifies the index of the new current widget, or -1 if there isn't a new one (for example, if there are no widgets in the QStackedLayout)
See also
currentWidget(), setCurrentWidget()
Referenced by setCurrentIndex(), and takeAt().
currentIndex()
int QStackedLayout::currentIndex () const
Referenced by setCurrentIndex(), and setStackingMode().
currentWidget()
QWidget * QStackedLayout::currentWidget () const
Returns the current widget, or 0 if there are no widgets in this layout.
See also
currentIndex(), setCurrentWidget()
Definition at line 390 of file qstackedlayout.cpp.
Referenced by setCurrentIndex(), setGeometry(), and setStackingMode().
 {
     Q_D(const QStackedLayout);
     return d->index >= 0 ? d->list.at(d->index)->widget() : 0;
 }
insertWidget()
int QStackedLayout::insertWidget (int index, QWidget * widget)
Inserts the given widget at the given index in this QStackedLayout.
If index is out of range, the widget is appended (in which case it is the actual index of the widget that is returned).
If the QStackedLayout is empty before this function is called, the given widget becomes the current widget.
Inserting a new widget at an index less than or equal to the current index will increment the current index, but keep the current widget.
See also
addWidget(), removeWidget(), setCurrentWidget()
Definition at line 217 of file qstackedlayout.cpp.
Referenced by addWidget().
 {
     Q_D(QStackedLayout);
     addChildWidget(widget);
     index = qMin(index, d->list.count());
     if (index < 0)
         index = d->list.count();
     QWidgetItem *wi = QLayoutPrivate::createWidgetItem(this, widget);
     d->list.insert(index, wi);
     invalidate();
     if (d->index < 0) {
         setCurrentIndex(index);
     } else {
         if (index <= d->index)
             ++d->index;
         if (d->stackingMode == StackOne)
             widget->hide();
         widget->lower();
     }
     return index;
 }
itemAt()
QLayoutItem * QStackedLayout::itemAt (int index) const virtual
Reimplemented Function
Implements QLayout.
Definition at line 242 of file qstackedlayout.cpp.
Referenced by QStackedLayoutHFW::hasHeightForWidth(), and QStackedLayoutHFW::heightForWidth().
 {
     Q_D(const QStackedLayout);
     return d->list.value(index);
 }
minimumSize()
QSize QStackedLayout::minimumSize () const virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 464 of file qstackedlayout.cpp.
Referenced by QStackedLayoutHFW::heightForWidth().
 {
     Q_D(const QStackedLayout);
     QSize s(0, 0);
     int n = d->list.count();
     for (int i = 0; i < n; ++i)
         if (QWidget *widget = d->list.at(i)->widget())
             s = s.expandedTo(qSmartMinSize(widget));
     return s;
 }
setCurrentIndex
void QStackedLayout::setCurrentIndex (int index) slot
Definition at line 298 of file qstackedlayout.cpp.
Referenced by insertWidget(), setCurrentWidget(), and takeAt().
 {
     Q_D(QStackedLayout);
     QWidget *prev = currentWidget();
     QWidget *next = widget(index);
     if (!next || next == prev)
         return;
     bool reenableUpdates = false;
     QWidget *parent = parentWidget();
     if (parent && parent->updatesEnabled()) {
         reenableUpdates = true;
         parent->setUpdatesEnabled(false);
     }
     QPointer<QWidget> fw = parent ? parent->window()->focusWidget() : 0;
     const bool focusWasOnOldPage = fw && (prev && prev->isAncestorOf(fw));
     if (prev) {
         prev->clearFocus();
         if (d->stackingMode == StackOne)
             prev->hide();
     }
     d->index = index;
     next->raise();
     next->show();
     // try to move focus onto the incoming widget if focus
     // was somewhere on the outgoing widget.
     if (parent) {
         if (focusWasOnOldPage) {
             // look for the best focus widget we can find
             if (QWidget *nfw = next->focusWidget())
                 nfw->setFocus();
             else {
                 // second best: first child widget in the focus chain
                 if (QWidget *i = fw) {
                     while ((i = i->nextInFocusChain()) != fw) {
                         if (((i->focusPolicy() & Qt::TabFocus) == Qt::TabFocus)
                             && !i->focusProxy() && i->isVisibleTo(next) && i->isEnabled()
                             && next->isAncestorOf(i)) {
                             i->setFocus();
                             break;
                         }
                     }
                     // third best: incoming widget
                     if (i == fw )
                         next->setFocus();
                 }
             }
         }
     }
     if (reenableUpdates)
         parent->setUpdatesEnabled(true);
     emit currentChanged(index);
 }
setCurrentWidget
void QStackedLayout::setCurrentWidget (QWidget * widget) slot
Sets the current widget to be the specified widget.
The new current widget must already be contained in this stacked layout.
See also
setCurrentIndex(), currentWidget()
Definition at line 373 of file qstackedlayout.cpp.
 {
     int index = indexOf(widget);
     if (index == -1) {
         qWarning("QStackedLayout::setCurrentWidget: Widget %p not contained in stack", widget);
         return;
     }
     setCurrentIndex(index);
 }
setGeometry()
void QStackedLayout::setGeometry (const QRect & rect) virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 479 of file qstackedlayout.cpp.
 {
     Q_D(QStackedLayout);
     switch (d->stackingMode) {
     case StackOne:
         if (QWidget *widget = currentWidget())
             widget->setGeometry(rect);
         break;
     case StackAll:
         if (const int n = d->list.count())
             for (int i = 0; i < n; ++i)
                 if (QWidget *widget = d->list.at(i)->widget())
                     widget->setGeometry(rect);
         break;
     }
 }
setStackingMode()
void QStackedLayout::setStackingMode (StackingMode stackingMode)
Definition at line 534 of file qstackedlayout.cpp.
 {
     Q_D(QStackedLayout);
     if (d->stackingMode == stackingMode)
         return;
     d->stackingMode = stackingMode;
     const int n = d->list.count();
     if (n == 0)
         return;
     switch (d->stackingMode) {
     case StackOne:
         if (const int idx = currentIndex())
             for (int i = 0; i < n; ++i)
                 if (QWidget *widget = d->list.at(i)->widget())
                     widget->setVisible(i == idx);
         break;
     case StackAll: { // Turn overlay on: Make sure all widgets are the same size
         QRect geometry;
         if (const QWidget *widget = currentWidget())
             geometry = widget->geometry();
         for (int i = 0; i < n; ++i)
             if (QWidget *widget = d->list.at(i)->widget()) {
                 if (!geometry.isNull())
                     widget->setGeometry(geometry);
                 widget->setVisible(true);
             }
     }
         break;
     }
 }
sizeHint()
QSize QStackedLayout::sizeHint () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 443 of file qstackedlayout.cpp.
 {
     Q_D(const QStackedLayout);
     QSize s(0, 0);
     int n = d->list.count();
     for (int i = 0; i < n; ++i)
         if (QWidget *widget = d->list.at(i)->widget()) {
             QSize ws(widget->sizeHint());
             if (widget->sizePolicy().horizontalPolicy() == QSizePolicy::Ignored)
                 ws.setWidth(0);
             if (widget->sizePolicy().verticalPolicy() == QSizePolicy::Ignored)
                 ws.setHeight(0);
             s = s.expandedTo(ws);
         }
     return s;
 }
stackingMode()
StackingMode QStackedLayout::stackingMode () const
Referenced by setGeometry(), and setStackingMode().
takeAt()
QLayoutItem * QStackedLayout::takeAt (int index) virtual
Reimplemented Function
Implements QLayout.
Definition at line 264 of file qstackedlayout.cpp.
 {
     Q_D(QStackedLayout);
     if (index <0 || index >= d->list.size())
         return 0;
     QLayoutItem *item = d->list.takeAt(index);
     if (index == d->index) {
         d->index = -1;
         if ( d->list.count() > 0 ) {
             int newIndex = (index == d->list.count()) ? index-1 : index;
             setCurrentIndex(newIndex);
         } else {
             emit currentChanged(-1);
         }
     } else if (index < d->index) {
         --d->index;
     }
     emit widgetRemoved(index);
     if (item->widget() && !qt_wasDeleted(item->widget()))
         item->widget()->hide();
     return item;
 }
widget()
QWidget * QStackedLayout::widget (int index) const
Returns the widget at the given index, or 0 if there is no widget at the given position.
Warning
This function is not part of the public interface.
See also
currentWidget(), indexOf()
Definition at line 402 of file qstackedlayout.cpp.
 {
     Q_D(const QStackedLayout);
      if (index < 0 || index >= d->list.size())
         return 0;
     return d->list.at(index)->widget();
 }
widgetRemoved
void QStackedLayout::widgetRemoved (int index) signal
This signal is emitted whenever a widget is removed from the layout.
The widget's index is passed as parameter.
See also
removeWidget()
Referenced by takeAt().
Properties
currentIndex
int QStackedLayout::currentIndex private
the index position of the widget that is visible
The current index is -1 if there is no current widget.
See also
currentWidget(), indexOf()
Definition at line 60 of file qstackedlayout.h.
stackingMode
QStackedLayout::StackingMode QStackedLayout::stackingMode private
determines the way visibility of child widgets are handled.
Since
4.4
The default value is StackOne. Setting the property to StackAll allows you to make use of the layout for overlay widgets that do additional drawing on top of other widgets, for example, graphical editors.
Definition at line 61 of file qstackedlayout.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qstackedlayout.h
/src/gui/kernel/qstackedlayout.cpp