Qt 4.8: QPatternist::XsdStateMachineBuilder Class Reference
QPatternist::XsdStateMachineBuilder Class Reference
XML Schema Processing
A helper class to build up validation state machines.
#include <qxsdstatemachinebuilder_p.h>
Public Types
enum Mode { CheckingMode, ValidatingMode }
typedef QExplicitlySharedDataPointer< XsdStateMachineBuilder > Ptr
Public Functions
XsdStateMachine< XsdTerm::Ptr >::StateId addStartState (XsdStateMachine< XsdTerm::Ptr >::StateId state)
XsdStateMachine< XsdTerm::Ptr >::StateId buildParticle (const XsdParticle::Ptr &particle, XsdStateMachine< XsdTerm::Ptr >::StateId endState)
XsdStateMachine< XsdTerm::Ptr >::StateId buildTerm (const XsdTerm::Ptr &term, XsdStateMachine< XsdTerm::Ptr >::StateId endState)
XsdStateMachine< XsdTerm::Ptr >::StateId reset ()
XsdStateMachineBuilder (XsdStateMachine< XsdTerm::Ptr > *machine, const NamePool::Ptr &namePool, Mode mode=CheckingMode)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static QHash< XsdTerm::Ptr, XsdParticle::Ptr > particleLookupMap (const XsdParticle::Ptr &particle)
Properties
Mode m_mode
NamePool::Ptr m_namePool
XsdStateMachine< XsdTerm::Ptr > * m_stateMachine
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
A helper class to build up validation state machines.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 74 of file qxsdstatemachinebuilder_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdStateMachineBuilder> QPatternist::XsdStateMachineBuilder::Ptr
Definition at line 77 of file qxsdstatemachinebuilder_p.h.
Enumerations
Mode
enum QPatternist::XsdStateMachineBuilder::Mode
Enumerator
CheckingMode
ValidatingMode
Definition at line 79 of file qxsdstatemachinebuilder_p.h.
             {
                 CheckingMode,
                 ValidatingMode
             };
Constructors and Destructors
XsdStateMachineBuilder()
XsdStateMachineBuilder::XsdStateMachineBuilder (XsdStateMachine< XsdTerm::Ptr > * machine, const NamePool::Ptr & namePool, Mode mode = CheckingMode)
Creates a new state machine builder.
Parameters
machine The state machine it should work on.
namePool The name pool used by all schema components.
mode The mode the machine shall be build for.
Definition at line 90 of file qxsdstatemachinebuilder.cpp.
     : m_stateMachine(machine), m_namePool(namePool), m_mode(mode)
 {
 }
Functions
addStartState()
XsdStateMachine< XsdTerm::Ptr >::StateId XsdStateMachineBuilder::addStartState (XsdStateMachine< XsdTerm::Ptr >::StateId state)
Prepends a start state to the given state. That is needed to allow the conversion of the state machine from a FSA to a DFA.
Definition at line 104 of file qxsdstatemachinebuilder.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::createAndPushStateMachine(), QPatternist::XsdParticleChecker::isUPAConform(), and QPatternist::XsdParticleChecker::subsumes().
 {
     const XsdStateMachine<XsdTerm::Ptr>::StateId startState = m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::StartState);
     m_stateMachine->addEpsilonTransition(startState, state);
     return startState;
 }
buildParticle()
XsdStateMachine< XsdTerm::Ptr >::StateId XsdStateMachineBuilder::buildParticle (const XsdParticle::Ptr & particle, XsdStateMachine< XsdTerm::Ptr >::StateId endState)
Creates the state machine for the given particle that should have the given endState.
Returns
The new start state.
Definition at line 115 of file qxsdstatemachinebuilder.cpp.
Referenced by buildTerm(), QPatternist::XsdValidatingInstanceReader::createAndPushStateMachine(), QPatternist::XsdParticleChecker::isUPAConform(), and QPatternist::XsdParticleChecker::subsumes().
 {
     XsdStateMachine<XsdTerm::Ptr>::StateId currentStartState = endState;
     XsdStateMachine<XsdTerm::Ptr>::StateId currentEndState = endState;
     // 2
     if (particle->maximumOccursUnbounded()) {
         const XsdStateMachine<XsdTerm::Ptr>::StateId t = m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::InternalState);
         const XsdStateMachine<XsdTerm::Ptr>::StateId n = buildTerm(particle->term(), t);
         m_stateMachine->addEpsilonTransition(t, n);
         m_stateMachine->addEpsilonTransition(n, endState);
         currentEndState = t;
         currentStartState = t;
     } else { // 3
         int count = (particle->maximumOccurs() - particle->minimumOccurs());
         if (count > 100)
             count = 100;
         for (int i = 0; i < count; ++i) {
             currentStartState = buildTerm(particle->term(), currentEndState);
             m_stateMachine->addEpsilonTransition(currentStartState, endState);
             currentEndState = currentStartState;
         }
     }
     int minOccurs = particle->minimumOccurs();
     if (minOccurs > 100)
         minOccurs = 100;
     for (int i = 0; i < minOccurs; ++i) {
         currentStartState = buildTerm(particle->term(), currentEndState);
         currentEndState = currentStartState;
     }
     return currentStartState;
 }
buildTerm()
XsdStateMachine< XsdTerm::Ptr >::StateId XsdStateMachineBuilder::buildTerm (const XsdTerm::Ptr & term, XsdStateMachine< XsdTerm::Ptr >::StateId endState)
Creates the state machine for the given term that should have the given endState.
Returns
The new start state.
Definition at line 157 of file qxsdstatemachinebuilder.cpp.
Referenced by buildParticle().
 {
     if (term->isWildcard()) { // 1
         const XsdStateMachine<XsdTerm::Ptr>::StateId b = m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::InternalState);
         m_stateMachine->addTransition(b, term, endState);
         return b;
     } else if (term->isElement()) { // 2
         const XsdStateMachine<XsdTerm::Ptr>::StateId b = m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::InternalState);
         m_stateMachine->addTransition(b, term, endState);
         const XsdElement::Ptr element(term);
         if (m_mode == CheckingMode) {
             const XsdElement::WeakList substGroups = element->substitutionGroups();
             for (int i = 0; i < substGroups.count(); ++i)
                 m_stateMachine->addTransition(b, XsdElement::Ptr(substGroups.at(i)), endState);
         } else if (m_mode == ValidatingMode) {
             const XsdElement::WeakList substGroups = element->substitutionGroups();
             for (int i = 0; i < substGroups.count(); ++i) {
                 if (XsdSchemaHelper::substitutionGroupOkTransitive(element, XsdElement::Ptr(substGroups.at(i)), m_namePool))
                     m_stateMachine->addTransition(b, XsdElement::Ptr(substGroups.at(i)), endState);
             }
         }
         return b;
     } else if (term->isModelGroup()) {
         const XsdModelGroup::Ptr group(term);
         if (group->compositor() == XsdModelGroup::ChoiceCompositor) { // 3
             const XsdStateMachine<XsdTerm::Ptr>::StateId b = m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::InternalState);
             for (int i = 0; i < group->particles().count(); ++i) {
                 const XsdParticle::Ptr particle(group->particles().at(i));
                 if (particle->maximumOccurs() != 0) {
                     const XsdStateMachine<XsdTerm::Ptr>::StateId state = buildParticle(particle, endState);
                     m_stateMachine->addEpsilonTransition(b, state);
                 }
             }
             return b;
         } else if (group->compositor() == XsdModelGroup::SequenceCompositor) { // 4
             XsdStateMachine<XsdTerm::Ptr>::StateId currentStartState = endState;
             XsdStateMachine<XsdTerm::Ptr>::StateId currentEndState = endState;
             for (int i = (group->particles().count() - 1); i >= 0; --i) { // iterate reverse
                 const XsdParticle::Ptr particle(group->particles().at(i));
                 if (particle->maximumOccurs() != 0) {
                     currentStartState = buildParticle(particle, currentEndState);
                     currentEndState = currentStartState;
                 }
             }
             return currentStartState;
         } else if (group->compositor() == XsdModelGroup::AllCompositor) {
             const XsdStateMachine<XsdTerm::Ptr>::StateId newStartState = m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::InternalState);
             const QList<XsdParticle::List> list = allCombinations(group->particles());
             for (int i = 0; i < list.count(); ++i) {
                 XsdStateMachine<XsdTerm::Ptr>::StateId currentStartState = endState;
                 XsdStateMachine<XsdTerm::Ptr>::StateId currentEndState = endState;
                 const XsdParticle::List particles = list.at(i);
                 for (int j = (particles.count() - 1); j >= 0; --j) { // iterate reverse
                     const XsdParticle::Ptr particle(particles.at(j));
                     if (particle->maximumOccurs() != 0) {
                         currentStartState = buildParticle(particle, currentEndState);
                         currentEndState = currentStartState;
                     }
                 }
                 m_stateMachine->addEpsilonTransition(newStartState, currentStartState);
             }
             if (list.isEmpty())
                 return endState;
             else
                 return newStartState;
         }
     }
     Q_ASSERT(false);
     return 0;
 }
particleLookupMap()
QHash< XsdTerm::Ptr, XsdParticle::Ptr > XsdStateMachineBuilder::particleLookupMap (const XsdParticle::Ptr & particle) static
Returns a hash that maps each term that appears inside particle, to the particle it belongs.
Note
These information are used by XsdParticleChecker to check particle inheritance.
Definition at line 252 of file qxsdstatemachinebuilder.cpp.
Referenced by QPatternist::XsdParticleChecker::subsumes().
 {
     QHash<XsdTerm::Ptr, XsdParticle::Ptr> result;
     internalParticleLookupMap(particle, result);
     return result;
 }
reset()
XsdStateMachine< XsdTerm::Ptr >::StateId XsdStateMachineBuilder::reset ()
Resets the state machine.
Returns
The initial end state.
Definition at line 95 of file qxsdstatemachinebuilder.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::createAndPushStateMachine(), QPatternist::XsdParticleChecker::isUPAConform(), and QPatternist::XsdParticleChecker::subsumes().
 {
     Q_ASSERT(m_stateMachine);
     m_stateMachine->clear();
     return m_stateMachine->addState(XsdStateMachine<XsdTerm::Ptr>::EndState);
 }
Properties
m_mode
Mode QPatternist::XsdStateMachineBuilder::m_mode private
Definition at line 133 of file qxsdstatemachinebuilder_p.h.
Referenced by buildTerm().
m_namePool
NamePool::Ptr QPatternist::XsdStateMachineBuilder::m_namePool private
Definition at line 132 of file qxsdstatemachinebuilder_p.h.
Referenced by buildTerm().
m_stateMachine
XsdStateMachine<XsdTerm::Ptr>* QPatternist::XsdStateMachineBuilder::m_stateMachine private
Definition at line 131 of file qxsdstatemachinebuilder_p.h.
Referenced by addStartState(), buildParticle(), buildTerm(), and reset().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdstatemachinebuilder_p.h
/src/xmlpatterns/schema/qxsdstatemachinebuilder.cpp