Qt 4.8: QScriptProgram Class Reference
QScriptProgram Class Reference
The QScriptProgram class encapsulates a Qt Script program.
#include <qscriptprogram.h>
Public Functions
QString fileName () const
Returns the filename associated with this program.
int firstLineNumber () const
Returns the line number associated with this program.
bool isNull () const
Returns true if this QScriptProgram is null; otherwise returns false.
bool operator!= (const QScriptProgram &other) const
Returns true if this QScriptProgram is not equal to other; otherwise returns false.
QScriptProgram & operator= (const QScriptProgram &other)
Assigns the other value to this QScriptProgram.
bool operator== (const QScriptProgram &other) const
Returns true if this QScriptProgram is equal to other; otherwise returns false.
QScriptProgram ()
Constructs a null QScriptProgram.
QScriptProgram (const QString &sourceCode, const QString fileName=QString(), int firstLineNumber=1)
Constructs a new QScriptProgram with the given sourceCode, fileName and firstLineNumber.
QScriptProgram (const QScriptProgram &other)
Constructs a new QScriptProgram that is a copy of other.
QString sourceCode () const
Returns the source code of this program.
~QScriptProgram ()
Destroys this QScriptProgram.
Properties
QExplicitlySharedDataPointer< QScriptProgramPrivate > d_ptr
Detailed Description
The QScriptProgram class encapsulates a Qt Script program.
Since
4.7
QScriptProgram retains the compiled representation of the script if possible. Thus, QScriptProgram can be used to evaluate the same script multiple times more efficiently.
QScriptEngine engine;
QScriptProgram program("1 + 2");
QScriptValue result = engine.evaluate(program);
Definition at line 38 of file qscriptprogram.h.
Constructors and Destructors
QScriptProgram() [1/3]
QScriptProgram::QScriptProgram ()
Constructs a null QScriptProgram.
Definition at line 113 of file qscriptprogram.cpp.
     : d_ptr(0)
 {
 }
QScriptProgram() [2/3]
QScriptProgram::QScriptProgram (const QString & sourceCode, const QString fileName = QString(), int firstLineNumber = 1)
Constructs a new QScriptProgram with the given sourceCode, fileName and firstLineNumber.
Definition at line 122 of file qscriptprogram.cpp.
     : d_ptr(new QScriptProgramPrivate(sourceCode, fileName, firstLineNumber))
 {
 }
QScriptProgram() [3/3]
QScriptProgram::QScriptProgram (const QScriptProgram & other)
Constructs a new QScriptProgram that is a copy of other.
Definition at line 132 of file qscriptprogram.cpp.
     : d_ptr(other.d_ptr)
 {
 }
~QScriptProgram()
QScriptProgram::~QScriptProgram ()
Destroys this QScriptProgram.
Definition at line 140 of file qscriptprogram.cpp.
 {
 }
Functions
fileName()
QString QScriptProgram::fileName () const
Returns the filename associated with this program.
Definition at line 177 of file qscriptprogram.cpp.
Referenced by operator==().
 {
     Q_D(const QScriptProgram);
     if (!d)
         return QString();
     return d->fileName;
 }
firstLineNumber()
int QScriptProgram::firstLineNumber () const
Returns the line number associated with this program.
Definition at line 188 of file qscriptprogram.cpp.
Referenced by operator==().
 {
     Q_D(const QScriptProgram);
     if (!d)
         return -1;
     return d->firstLineNumber;
 }
isNull()
bool QScriptProgram::isNull () const
Returns true if this QScriptProgram is null; otherwise returns false.
Definition at line 157 of file qscriptprogram.cpp.
 {
     Q_D(const QScriptProgram);
     return (d == 0);
 }
operator!=()
bool QScriptProgram::operator!= (const QScriptProgram & other) const
Returns true if this QScriptProgram is not equal to other; otherwise returns false.
Definition at line 214 of file qscriptprogram.cpp.
 {
     return !operator==(other);
 }
operator=()
QScriptProgram & QScriptProgram::operator= (const QScriptProgram & other)
Assigns the other value to this QScriptProgram.
Definition at line 147 of file qscriptprogram.cpp.
 {
     d_ptr = other.d_ptr;
     return *this;
 }
operator==()
bool QScriptProgram::operator== (const QScriptProgram & other) const
Returns true if this QScriptProgram is equal to other; otherwise returns false.
Definition at line 200 of file qscriptprogram.cpp.
Referenced by operator!=().
 {
     Q_D(const QScriptProgram);
     if (d == other.d_func())
         return true;
     return (sourceCode() == other.sourceCode())
         && (fileName() == other.fileName())
         && (firstLineNumber() == other.firstLineNumber());
 }
sourceCode()
QString QScriptProgram::sourceCode () const
Returns the source code of this program.
Definition at line 166 of file qscriptprogram.cpp.
Referenced by operator==().
 {
     Q_D(const QScriptProgram);
     if (!d)
         return QString();
     return d->sourceCode;
 }
Properties
d_ptr
QExplicitlySharedDataPointer<QScriptProgramPrivate> QScriptProgram::d_ptr private
Definition at line 60 of file qscriptprogram.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
/src/script/api/qscriptprogram.h
/src/script/api/qscriptprogram.cpp