Qt 4.8: QDeclarativeConnections Class Reference
QDeclarativeConnections Class Reference
#include <qdeclarativeconnections_p.h>
Signals
void targetChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool ignoreUnknownSignals () const
QDeclarativeConnections (QObject *parent=0)
void setIgnoreUnknownSignals (bool ignore)
void setTarget (QObject *)
QObject * target () const
~QDeclarativeConnections ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Private Functions
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
void connectSignals ()
Properties
bool ignoreUnknownSignals
QObject * target
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 61 of file qdeclarativeconnections_p.h.
Constructors and Destructors
QDeclarativeConnections()
QDeclarativeConnections::QDeclarativeConnections (QObject * parent = 0)
Definition at line 133 of file qdeclarativeconnections.cpp.
                                                                 :
     QObject(*(new QDeclarativeConnectionsPrivate), parent)
 {
 }
~QDeclarativeConnections()
QDeclarativeConnections::~QDeclarativeConnections ()
Definition at line 138 of file qdeclarativeconnections.cpp.
 {
 }
Functions
classBegin()
void QDeclarativeConnections::classBegin () private virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 285 of file qdeclarativeconnections.cpp.
 {
     Q_D(QDeclarativeConnections);
     d->componentcomplete=false;
 }
componentComplete()
void QDeclarativeConnections::componentComplete () private virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 291 of file qdeclarativeconnections.cpp.
 {
     Q_D(QDeclarativeConnections);
     d->componentcomplete=true;
     connectSignals();
 }
connectSignals()
void QDeclarativeConnections::connectSignals () private
Definition at line 256 of file qdeclarativeconnections.cpp.
Referenced by componentComplete(), and setTarget().
 {
     Q_D(QDeclarativeConnections);
     if (!d->componentcomplete || (d->targetSet && !target()))
         return;
     QDataStream ds(d->data);
     while (!ds.atEnd()) {
         QString propName;
         ds >> propName;
         QString script;
         ds >> script;
         QDeclarativeProperty prop(target(), propName);
         if (prop.isValid() && (prop.type() & QDeclarativeProperty::SignalProperty)) {
             QDeclarativeBoundSignal *signal =
                 new QDeclarativeBoundSignal(target(), prop.method(), this);
             QDeclarativeExpression *expression = new QDeclarativeExpression(qmlContext(this), 0, script);
             QDeclarativeData *ddata = QDeclarativeData::get(this);
             if (ddata && ddata->outerContext && !ddata->outerContext->url.isEmpty())
                 expression->setSourceLocation(ddata->outerContext->url.toString(), ddata->lineNumber);
             signal->setExpression(expression);
             d->boundsignals += signal;
         } else {
             if (!d->ignoreUnknownSignals)
                 qmlInfo(this) << tr("Cannot assign to non-existent property \"%1\"").arg(propName);
         }
     }
 }
ignoreUnknownSignals()
bool QDeclarativeConnections::ignoreUnknownSignals () const
Referenced by setTarget().
setIgnoreUnknownSignals()
void QDeclarativeConnections::setIgnoreUnknownSignals (bool ignore)
Definition at line 198 of file qdeclarativeconnections.cpp.
 {
     Q_D(QDeclarativeConnections);
     d->ignoreUnknownSignals = ignore;
 }
setTarget()
void QDeclarativeConnections::setTarget (QObject * obj)
Definition at line 160 of file qdeclarativeconnections.cpp.
 {
     Q_D(QDeclarativeConnections);
     d->targetSet = true; // even if setting to 0, it is *set*
     if (d->target == obj)
         return;
     foreach (QDeclarativeBoundSignal *s, d->boundsignals) {
         // It is possible that target is being changed due to one of our signal
         // handlers -> use deleteLater().
         if (s->isEvaluating())
             s->deleteLater();
         else
             delete s;
     }
     d->boundsignals.clear();
     d->target = obj;
     connectSignals();
     emit targetChanged();
 }
target()
QObject* QDeclarativeConnections::target () const
Referenced by connectSignals(), and ~QDeclarativeConnections().
targetChanged
void QDeclarativeConnections::targetChanged () signal
Referenced by setTarget().
Properties
ignoreUnknownSignals
bool QDeclarativeConnections::ignoreUnknownSignals private
Definition at line 68 of file qdeclarativeconnections_p.h.
target
QObject * QDeclarativeConnections::target private
Definition at line 67 of file qdeclarativeconnections_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeconnections_p.h
/src/declarative/util/qdeclarativeconnections.cpp