Qt 4.8: QTestResult Class Reference
QTestResult Class Reference
#include <qtestresult_p.h>
Public Types
enum TestLocation {
NoWhere = 0, DataFunc = 1, InitFunc = 2, Func = 3,
CleanupFunc = 4
}
Static Public Functions
static void addFailure (const char *message, const char *file, int line)
static void addSkip (const char *message, QTest::SkipMode mode, const char *file, int line)
static bool allDataPassed ()
static bool compare (bool success, const char *msg, const char *file, int line)
static bool compare (bool success, const char *msg, char *val1, char *val2, const char *actual, const char *expected, const char *file, int line)
static const char * currentAppName ()
static const char * currentDataTag ()
static const char * currentGlobalDataTag ()
static QTestData * currentGlobalTestData ()
static QTestData * currentTestData ()
static bool currentTestFailed ()
static const char * currentTestFunction ()
static TestLocation currentTestLocation ()
static const char * currentTestObjectName ()
static bool expectFail (const char *dataIndex, const char *comment, QTest::TestFailMode mode, const char *file, int line)
static int failCount ()
static void finishedCurrentTestFunction ()
static void ignoreMessage (QtMsgType type, const char *msg)
static int passCount ()
static void reset ()
static void setCurrentAppName (const char *appName)
static void setCurrentGlobalTestData (QTestData *data)
static void setCurrentTestData (QTestData *data)
static void setCurrentTestFunction (const char *func)
static void setCurrentTestLocation (TestLocation loc)
static void setCurrentTestObject (const char *name)
static void setSkipCurrentTest (bool value)
static int skipCount ()
static bool skipCurrentTest ()
static bool testFailed ()
static bool verify (bool statement, const char *statementStr, const char *extraInfo, const char *file, int line)
Detailed Description
Definition at line 63 of file qtestresult_p.h.
Enumerations
TestLocation
enum QTestResult::TestLocation
Enumerator
NoWhere
DataFunc
InitFunc
Func
CleanupFunc
Definition at line 66 of file qtestresult_p.h.
 { NoWhere = 0, DataFunc = 1, InitFunc = 2, Func = 3, CleanupFunc = 4 };
Functions
addFailure()
void QTestResult::addFailure (const char * message, const char * file, int line) static
Definition at line 280 of file qtestresult.cpp.
Referenced by checkStatement(), QTest::messageHandler(), QTest::qExec(), QTest::qFail(), and QTest::qInvokeTestMethodDataEntry().
 {
     clearExpectFail();
     QTestLog::addFail(message, file, line);
     QTest::failed = true;
     QTest::dataFailed = true;
     ++QTest::fails;
 }
addSkip()
void QTestResult::addSkip (const char * message, QTest::SkipMode mode, const char * file, int line) static
Definition at line 290 of file qtestresult.cpp.
Referenced by QTest::qSkip().
 {
     clearExpectFail();
     QTestLog::addSkip(message, mode, file, line);
     ++QTest::skips;
 }
allDataPassed()
bool QTestResult::allDataPassed () static
Definition at line 93 of file qtestresult.cpp.
 {
     return !QTest::failed;
 }
compare() [1/2]
bool QTestResult::compare (bool success, const char * msg, const char * file, int line) static
Definition at line 253 of file qtestresult.cpp.
Referenced by QTest::compare_helper().
 {
     if (QTestLog::verboseLevel() >= 2) {
         QTestLog::info(msg, file, line);
     }
     return checkStatement(success, msg, file, line);
 }
compare() [2/2]
bool QTestResult::compare (bool success, const char * msg, char * val1, char * val2, const char * actual, const char * expected, const char * file, int line) static
Definition at line 262 of file qtestresult.cpp.
 {
     QTEST_ASSERT(expected);
     QTEST_ASSERT(actual);
     if (!val1 && !val2)
         return compare(success, msg, file, line);
     char buf[1024];
     QTest::qt_snprintf(buf, 1024, "%s\n   Actual (%s): %s\n   Expected (%s): %s", msg,
                        actual, val1 ? val1 : "<null>",
                        expected, val2 ? val2 : "<null>");
     delete [] val1;
     delete [] val2;
     return compare(success, buf, file, line);
 }
currentAppName()
const char * QTestResult::currentAppName () static
Definition at line 358 of file qtestresult.cpp.
Referenced by QTest::currentAppName().
 {
     return QTest::currentAppName;
 }
currentDataTag()
const char * QTestResult::currentDataTag () static
Definition at line 167 of file qtestresult.cpp.
Referenced by QXmlTestLogger::addIncident(), QXmlTestLogger::addMessage(), QTestLogger::addTag(), QTest::currentDataTag(), QTest::printMessage(), and QTest::qInvokeTestMethodDataEntry().
 {
     return QTest::currentTestData ? QTest::currentTestData->dataTag()
                                    : static_cast<const char *>(0);
 }
currentGlobalDataTag()
const char * QTestResult::currentGlobalDataTag () static
Definition at line 173 of file qtestresult.cpp.
Referenced by QXmlTestLogger::addIncident(), QXmlTestLogger::addMessage(), QTestLogger::addTag(), and QTest::printMessage().
 {
     return QTest::currentGlobalTestData ? QTest::currentGlobalTestData->dataTag()
                                          : static_cast<const char *>(0);
 }
currentGlobalTestData()
QTestData * QTestResult::currentGlobalTestData () static
Definition at line 103 of file qtestresult.cpp.
Referenced by QTest::qGlobalData().
 {
     return QTest::currentGlobalTestData;
 }
currentTestData()
QTestData * QTestResult::currentTestData () static
Definition at line 108 of file qtestresult.cpp.
Referenced by QTest::qData(), and QTest::qElementData().
 {
     return QTest::currentTestData;
 }
currentTestFailed()
bool QTestResult::currentTestFailed () static
Definition at line 98 of file qtestresult.cpp.
Referenced by QTest::currentTestFailed().
 {
     return QTest::dataFailed;
 }
currentTestFunction()
const char * QTestResult::currentTestFunction () static
Definition at line 162 of file qtestresult.cpp.
Referenced by QTest::currentTestFunction(), QTest::printMessage(), and QTest::qExec().
 {
     return QTest::currentTestFunc;
 }
currentTestLocation()
QTestResult::TestLocation QTestResult::currentTestLocation () static
Definition at line 299 of file qtestresult.cpp.
 {
     return QTest::location;
 }
currentTestObjectName()
const char * QTestResult::currentTestObjectName () static
Definition at line 314 of file qtestresult.cpp.
Referenced by QTestFileLogger::init(), QTestXmlStreamer::output(), QTest::printBenchmarkResult(), QTest::printMessage(), QPlainTestLogger::startLogging(), QXmlTestLogger::startLogging(), QPlainTestLogger::stopLogging(), and QTestLogger::stopLogging().
 {
     return QTest::currentTestObjectName ? QTest::currentTestObjectName : "";
 }
expectFail()
bool QTestResult::expectFail (const char * dataIndex, const char * comment, QTest::TestFailMode mode, const char * file, int line) static
Definition at line 190 of file qtestresult.cpp.
Referenced by QTest::qExpectFail().
 {
     QTEST_ASSERT(comment);
     QTEST_ASSERT(mode > 0);
     if (!isExpectFailData(dataIndex)) {
         delete[] comment;
         return true; // we don't care
     }
     if (QTest::expectFailMode) {
         delete[] comment;
         clearExpectFail();
         addFailure("Already expecting a fail", file, line);
         return false;
     }
     QTest::expectFailMode = mode;
     QTest::expectFailComment = comment;
     return true;
 }
failCount()
int QTestResult::failCount () static
Definition at line 324 of file qtestresult.cpp.
Referenced by QTest::qExec(), and QPlainTestLogger::stopLogging().
 {
     return QTest::fails;
 }
finishedCurrentTestFunction()
void QTestResult::finishedCurrentTestFunction () static
Definition at line 141 of file qtestresult.cpp.
Referenced by QTest::qExec(), QTest::qInvokeTestMethod(), and QTest::qInvokeTestMethods().
 {
     if (!QTest::failed && QTestLog::unhandledIgnoreMessages()) {
         QTestLog::printUnhandledIgnoreMessages();
         addFailure("Not all expected messages were received", 0, 0);
     }
     if (!QTest::failed && !QTest::skipCurrentTest) {
         QTestLog::addPass("");
         ++QTest::passes;
     }
     QTest::currentTestFunc = 0;
     QTest::failed = false;
     QTest::dataFailed = false;
     QTest::location = NoWhere;
     QTestLog::leaveTestFunction();
     clearExpectFail();
 }
ignoreMessage()
void QTestResult::ignoreMessage (QtMsgType type, const char * msg) static
Definition at line 334 of file qtestresult.cpp.
Referenced by QTest::ignoreMessage().
 {
     QTestLog::addIgnoreMessage(type, msg);
 }
passCount()
int QTestResult::passCount () static
Definition at line 319 of file qtestresult.cpp.
Referenced by QPlainTestLogger::stopLogging().
 {
     return QTest::passes;
 }
reset()
void QTestResult::reset () static
Definition at line 75 of file qtestresult.cpp.
Referenced by QTest::qExec().
 {
     QTest::currentTestData = 0;
     QTest::currentGlobalTestData = 0;
     QTest::currentTestFunc = 0;
     QTest::currentTestObjectName = 0;
     QTest::failed = false;
     QTest::dataFailed = false;
     QTest::location = QTestResult::NoWhere;
     QTest::fails = 0;
     QTest::passes = 0;
     QTest::skips = 0;
     QTest::expectFailComment = 0;
     QTest::expectFailMode = 0;
 }
setCurrentAppName()
void QTestResult::setCurrentAppName (const char * appName) static
Definition at line 354 of file qtestresult.cpp.
Referenced by QTest::qExec().
 {
     QTest::currentAppName = appName;
 }
setCurrentGlobalTestData()
void QTestResult::setCurrentGlobalTestData (QTestData * data) static
Definition at line 113 of file qtestresult.cpp.
Referenced by QTest::qInvokeTestMethod().
 {
     QTest::currentGlobalTestData = data;
 }
setCurrentTestData()
void QTestResult::setCurrentTestData (QTestData * data) static
Definition at line 118 of file qtestresult.cpp.
Referenced by QTest::qInvokeTestMethod(), QTest::QTestDataSetter::QTestDataSetter(), and QTest::QTestDataSetter::~QTestDataSetter().
 {
     QTest::currentTestData = data;
     QTest::dataFailed = false;
 }
setCurrentTestFunction()
void QTestResult::setCurrentTestFunction (const char * func) static
Definition at line 124 of file qtestresult.cpp.
Referenced by QTest::qExec(), QTest::qInvokeTestMethod(), and QTest::qInvokeTestMethods().
 {
     QTest::currentTestFunc = func;
     QTest::failed = false;
     if (!func)
         QTest::location = NoWhere;
     if (func)
         QTestLog::enterTestFunction(func);
 }
setCurrentTestLocation()
void QTestResult::setCurrentTestLocation (TestLocation loc) static
Definition at line 304 of file qtestresult.cpp.
Referenced by QTest::qInvokeTestMethod(), QTest::qInvokeTestMethodDataEntry(), and QTest::qInvokeTestMethods().
 {
     QTest::location = loc;
 }
setCurrentTestObject()
void QTestResult::setCurrentTestObject (const char * name) static
Definition at line 309 of file qtestresult.cpp.
Referenced by QTest::qExec().
 {
     QTest::currentTestObjectName = name;
 }
setSkipCurrentTest()
void QTestResult::setSkipCurrentTest (bool value) static
Definition at line 344 of file qtestresult.cpp.
Referenced by QTest::qInvokeTestMethod(), QTest::qInvokeTestMethods(), and QTest::qSkip().
 {
     QTest::skipCurrentTest = value;
 }
skipCount()
int QTestResult::skipCount () static
Definition at line 329 of file qtestresult.cpp.
Referenced by QPlainTestLogger::stopLogging().
 {
     return QTest::skips;
 }
skipCurrentTest()
bool QTestResult::skipCurrentTest () static
Definition at line 349 of file qtestresult.cpp.
Referenced by QTest::qInvokeTestMethod(), QTest::qInvokeTestMethodDataEntry(), and QTest::qInvokeTestMethods().
 {
     return QTest::skipCurrentTest;
 }
testFailed()
bool QTestResult::testFailed () static
Definition at line 339 of file qtestresult.cpp.
Referenced by QTest::qInvokeTestMethods().
 {
     return QTest::failed;
 }
verify()
bool QTestResult::verify (bool statement, const char * statementStr, const char * extraInfo, const char * file, int line) static
Definition at line 238 of file qtestresult.cpp.
Referenced by QTest::qVerify().
 {
     char msg[1024];
     if (QTestLog::verboseLevel() >= 2) {
         QTest::qt_snprintf(msg, 1024, "QVERIFY(%s)", statementStr);
         QTestLog::info(msg, file, line);
     }
     QTest::qt_snprintf(msg, 1024, "'%s' returned FALSE. (%s)", statementStr, description);
     return checkStatement(statement, msg, file, line);
 }
The documentation for this class was generated from the following files:
/src/testlib/qtestresult_p.h
/src/testlib/qtestresult.cpp