Qt 4.8: QScriptStaticScopeObject Class Reference
QScriptStaticScopeObject Class Reference
Represents a static scope object.
#include <qscriptstaticscopeobject_p.h>
Classes
struct Data
struct PropertyInfo
Public Functions
virtual const JSC::ClassInfo * classInfo () const
virtual bool deleteProperty (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual bool getOwnPropertyDescriptor (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual bool getOwnPropertySlot (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual bool isDynamicScope () const
virtual void markChildren (JSC::MarkStack &)
virtual void put (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::JSValue value, JSC::PutPropertySlot &)
virtual void putWithAttributes (JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue value, unsigned attributes)
QScriptStaticScopeObject (WTF::NonNullPassRefPtr< JSC::Structure > structure, int propertyCount, const PropertyInfo *)
Creates a static scope object with a fixed set of undeletable properties.
QScriptStaticScopeObject (WTF::NonNullPassRefPtr< JSC::Structure > structure)
Creates an empty static scope object.
virtual ~QScriptStaticScopeObject ()
Static Public Functions
static WTF::PassRefPtr< JSC::Structure > createStructure (JSC::JSValue proto)
Static Public Variables
static const JSC::ClassInfo info = { "QScriptStaticScopeObject", 0, 0, 0 }
Protected Functions
Data * d_ptr () const
Static Protected Variables
static const unsigned StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::NeedsThisConversion | JSC::OverridesMarkChildren | JSC::OverridesGetPropertyNames | JSC::JSVariableObject::StructureFlags
Private Functions
void addSymbolTableProperty (const JSC::Identifier &, JSC::JSValue, unsigned attributes)
int growRegisterArray (int)
Grows the register array by count elements, and returns the offset of the newly added elements (note that the register file grows downwards, starting at index -1).
Detailed Description
Represents a static scope object.
Warning
This function is not part of the public interface.
This class allows the VM to determine at JS script compile time whether the object has a given property or not. If the object has the property, a fast, index-based read/write operation will be used. If the object doesn't have the property, the compiler knows it can safely skip this object when dynamically resolving the property. Either way, this can greatly improve performance.
See also
QScriptContext::pushScope()
Definition at line 44 of file qscriptstaticscopeobject_p.h.
Constructors and Destructors
QScriptStaticScopeObject() [1/2]
QScriptStaticScopeObject::QScriptStaticScopeObject (WTF::NonNullPassRefPtr< JSC::Structure > structure, int propertyCount, const PropertyInfo * props)
Creates a static scope object with a fixed set of undeletable properties.
It's not possible to add new properties to the object after construction.
Definition at line 60 of file qscriptstaticscopeobject.cpp.
     : JSC::JSVariableObject(structure, new Data(/*canGrow=*/false))
 {
     int index = growRegisterArray(propertyCount);
     for (int i = 0; i < propertyCount; ++i, --index) {
         const PropertyInfo& prop = props[i];
         JSC::SymbolTableEntry entry(index, prop.attributes);
         symbolTable().add(prop.identifier.ustring().rep(), entry);
         registerAt(index) = prop.value;
     }
 }
QScriptStaticScopeObject() [2/2]
QScriptStaticScopeObject::QScriptStaticScopeObject (WTF::NonNullPassRefPtr< JSC::Structure > structure)
Creates an empty static scope object.
Properties can be added to the object after construction, either by calling QScriptValue::setProperty(), or by pushing the object on the scope chain; variable declarations ("var" statements) and function declarations in JavaScript will create properties on the scope object.
Note that once the scope object has been used in a closure and the resulting function has been compiled, it's no longer safe to add properties to the scope object (because the VM will bypass this object the next time the function is executed).
Definition at line 86 of file qscriptstaticscopeobject.cpp.
     : JSC::JSVariableObject(structure, new Data(/*canGrow=*/true))
 {
 }
~QScriptStaticScopeObject()
QScriptStaticScopeObject::~QScriptStaticScopeObject () virtual
Definition at line 91 of file qscriptstaticscopeobject.cpp.
 {
     delete d_ptr();
 }
Functions
addSymbolTableProperty()
void QScriptStaticScopeObject::addSymbolTableProperty (const JSC::Identifier & name, JSC::JSValue value, unsigned attributes) private
Definition at line 135 of file qscriptstaticscopeobject.cpp.
Referenced by d_ptr(), put(), and putWithAttributes().
 {
     int index = growRegisterArray(1);
     JSC::SymbolTableEntry newEntry(index, attributes | JSC::DontDelete);
     symbolTable().add(name.ustring().rep(), newEntry);
     registerAt(index) = value;
 }
classInfo()
virtual const JSC::ClassInfo* QScriptStaticScopeObject::classInfo () const inline virtual
Definition at line 74 of file qscriptstaticscopeobject_p.h.
 { return &info; }
createStructure()
static WTF::PassRefPtr<JSC::Structure> QScriptStaticScopeObject::createStructure (JSC::JSValue proto) inline static
Definition at line 77 of file qscriptstaticscopeobject_p.h.
Referenced by QScriptEnginePrivate::QScriptEnginePrivate().
{
         return JSC::Structure::create(proto, JSC::TypeInfo(JSC::ObjectType, StructureFlags));
     }
d_ptr()
Data* QScriptStaticScopeObject::d_ptr () const inline protected
Definition at line 94 of file qscriptstaticscopeobject_p.h.
Referenced by growRegisterArray(), markChildren(), put(), putWithAttributes(), and ~QScriptStaticScopeObject().
 { return static_cast<Data*>(JSVariableObject::d); }
deleteProperty()
bool QScriptStaticScopeObject::deleteProperty (JSC::ExecState * , const JSC::Identifier & propertyName) virtual
Definition at line 122 of file qscriptstaticscopeobject.cpp.
Referenced by isDynamicScope().
 {
     return false;
 }
getOwnPropertyDescriptor()
bool QScriptStaticScopeObject::getOwnPropertyDescriptor (JSC::ExecState * , const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Definition at line 101 of file qscriptstaticscopeobject.cpp.
Referenced by isDynamicScope().
 {
     return symbolTableGet(propertyName, descriptor);
 }
getOwnPropertySlot()
bool QScriptStaticScopeObject::getOwnPropertySlot (JSC::ExecState * , const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Definition at line 96 of file qscriptstaticscopeobject.cpp.
Referenced by isDynamicScope().
 {
     return symbolTableGet(propertyName, slot);
 }
growRegisterArray()
int QScriptStaticScopeObject::growRegisterArray (int count) private
Grows the register array by count elements, and returns the offset of the newly added elements (note that the register file grows downwards, starting at index -1).
Definition at line 148 of file qscriptstaticscopeobject.cpp.
Referenced by addSymbolTableProperty(), d_ptr(), and QScriptStaticScopeObject().
 {
     size_t oldSize = d_ptr()->registerArraySize;
     size_t newSize = oldSize + count;
     JSC::Register* registerArray = new JSC::Register[newSize];
     if (d_ptr()->registerArray)
         memcpy(registerArray + count, d_ptr()->registerArray.get(), oldSize * sizeof(JSC::Register));
     setRegisters(registerArray + newSize, registerArray);
     d_ptr()->registerArraySize = newSize;
     return -oldSize - 1;
 }
isDynamicScope()
virtual bool QScriptStaticScopeObject::isDynamicScope () const inline virtual
Definition at line 62 of file qscriptstaticscopeobject_p.h.
 { return false; }
markChildren()
void QScriptStaticScopeObject::markChildren (JSC::MarkStack & markStack) virtual
Definition at line 127 of file qscriptstaticscopeobject.cpp.
Referenced by isDynamicScope().
 {
     JSC::Register* registerArray = d_ptr()->registerArray.get();
     if (!registerArray)
         return;
     markStack.appendValues(reinterpret_cast<JSC::JSValue*>(registerArray), d_ptr()->registerArraySize);
 }
put()
void QScriptStaticScopeObject::put (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot &) virtual
Definition at line 114 of file qscriptstaticscopeobject.cpp.
Referenced by isDynamicScope().
 {
     if (symbolTablePut(propertyName, value))
         return;
     Q_ASSERT(d_ptr()->canGrow);
     addSymbolTableProperty(propertyName, value, /*attributes=*/0);
 }
putWithAttributes()
void QScriptStaticScopeObject::putWithAttributes (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, unsigned attributes) virtual
Definition at line 106 of file qscriptstaticscopeobject.cpp.
Referenced by isDynamicScope().
 {
     if (symbolTablePutWithAttributes(propertyName, value, attributes))
         return;
     Q_ASSERT(d_ptr()->canGrow);
     addSymbolTableProperty(propertyName, value, attributes);
 }
Properties
info
const JSC::ClassInfo QScriptStaticScopeObject::info = { "QScriptStaticScopeObject", 0, 0, 0 } static
Definition at line 75 of file qscriptstaticscopeobject_p.h.
Referenced by classInfo().
StructureFlags
const unsigned QScriptStaticScopeObject::StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::NeedsThisConversion | JSC::OverridesMarkChildren | JSC::OverridesGetPropertyNames | JSC::JSVariableObject::StructureFlags static protected
Definition at line 82 of file qscriptstaticscopeobject_p.h.
Referenced by createStructure().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptstaticscopeobject_p.h
/src/script/bridge/qscriptstaticscopeobject.cpp