Qt 4.8: QMdiSubWindowPrivate Class Reference
QMdiSubWindowPrivate Class Reference
#include <qmdisubwindow_p.h>
Classes
struct OperationInfo
Public Types
enum ChangeFlag {
HMove = 0x01, VMove = 0x02, HResize = 0x04, VResize = 0x08,
HResizeReverse = 0x10, VResizeReverse = 0x20
}
enum Operation {
None, Move, TopResize, BottomResize,
LeftResize, RightResize, TopLeftResize, TopRightResize,
BottomLeftResize, BottomRightResize
}
typedef QMap< Operation, OperationInfo > OperationInfoMap
enum WindowStateAction {
RestoreAction, MoveAction, ResizeAction, MinimizeAction,
MaximizeAction, StayOnTopAction, CloseAction, NumWindowStateActions
}
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_enterInteractiveMode ()
void _q_processFocusChanged (QWidget *old, QWidget *now)
void _q_updateStaysOnTopHint ()
void addToSystemMenu (WindowStateAction, const QString &text, const char *slot)
bool autoRaise () const
void createSystemMenu ()
QPalette desktopPalette () const
bool drawTitleBarWhenMaximized () const
void ensureWindowState (Qt::WindowState state)
void enterRubberBandMode ()
Operation getOperation (const QPoint &pos) const
QRegion getRegion (Operation operation) const
QStyle::SubControl getSubControl (const QPoint &pos) const
bool hasBorder (const QStyleOptionTitleBar &options) const
QSize iconSize () const
void initOperationMap ()
bool isMoveOperation () const
bool isResizeOperation () const
void leaveInteractiveMode ()
void leaveRubberBandMode ()
QMenuBar * menuBar () const
QString originalWindowTitle ()
void processClickedSubControl ()
QMdiSubWindowPrivate ()
void removeBaseWidget ()
void removeButtonsFromMenuBar ()
void restoreFocus ()
void setActive (bool activate, bool changeFocus=true)
void setEnabled (WindowStateAction, bool enable=true)
void setFocusWidget ()
void setMaximizeMode ()
void setMinimizeMode ()
void setNewGeometry (const QPoint &pos)
void setNewGeometry (QRect *geometry)
void setNewWindowTitle ()
void setNormalMode ()
void setSizeGrip (QSizeGrip *sizeGrip)
void setSizeGripVisible (bool visible=true) const
void setVisible (WindowStateAction, bool visible=true)
void setWindowFlags (Qt::WindowFlags windowFlags)
void showButtonsInMenuBar (QMenuBar *menuBar)
void sizeParameters (int *margin, int *minWidth) const
int titleBarHeight (const QStyleOptionTitleBar &options) const
int titleBarHeight () const
QStyleOptionTitleBar titleBarOptions () const
void updateActions ()
void updateCursor ()
void updateDirtyRegions ()
void updateGeometryConstraints ()
void updateInternalWindowTitle ()
void updateMask ()
void updateWindowTitle (bool requestFromChild)
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QPointer< QAction > actions [NumWindowStateActions]
bool activationEnabled
QStyle::SubControl activeSubControl
QPointer< QWidget > baseWidget
QStyleOptionTitleBar cachedStyleOptions
QPointer< QMdi::ControlContainer > controlContainer
Operation currentOperation
Qt::FocusReason focusInReason
QFont font
QStyle::SubControl hoveredSubControl
bool ignoreNextActivationEvent
bool ignoreWindowTitleChange
QSize internalMinimumSize
bool isActive
bool isExplicitlyDeactivated
bool isInInteractiveMode
bool isInRubberBandMode
bool isMaximizeMode
bool isShadeMode
bool isShadeRequestFromMinimizeMode
bool isWidgetHiddenByUs
int keyboardPageStep
int keyboardSingleStep
QString lastChildWindowTitle
QIcon menuIcon
QPoint mousePressPosition
bool moveEnabled
QRect oldGeometry
OperationInfoMap operationMap
QMdiSubWindow::SubWindowOptions options
QString originalTitle
bool resizeEnabled
int resizeTimerId
QPointer< QWidget > restoreFocusWidget
QSize restoreSize
QRubberBand * rubberBand
QPointer< QSizeGrip > sizeGrip
QPointer< QMenu > systemMenu
QPalette titleBarPalette
QSize userMinimumSize
QString windowTitle
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 121 of file qmdisubwindow_p.h.
Typedefs
OperationInfoMap
typedef QMap<Operation, OperationInfo> QMdiSubWindowPrivate::OperationInfoMap
Definition at line 172 of file qmdisubwindow_p.h.
Enumerations
ChangeFlag
enum QMdiSubWindowPrivate::ChangeFlag
Enumerator
HMove
VMove
HResize
VResize
HResizeReverse
VResizeReverse
Definition at line 139 of file qmdisubwindow_p.h.
                     {
         HMove = 0x01,
         VMove = 0x02,
         HResize = 0x04,
         VResize = 0x08,
         HResizeReverse = 0x10,
         VResizeReverse = 0x20
     };
Operation
enum QMdiSubWindowPrivate::Operation
Enumerator
None
Move
TopResize
BottomResize
LeftResize
RightResize
TopLeftResize
TopRightResize
BottomLeftResize
BottomRightResize
Definition at line 126 of file qmdisubwindow_p.h.
                    {
         None,
         Move,
         TopResize,
         BottomResize,
         LeftResize,
         RightResize,
         TopLeftResize,
         TopRightResize,
         BottomLeftResize,
         BottomRightResize
     };
WindowStateAction
enum QMdiSubWindowPrivate::WindowStateAction
Enumerator
RestoreAction
MoveAction
ResizeAction
MinimizeAction
MaximizeAction
StayOnTopAction
CloseAction
NumWindowStateActions
Definition at line 148 of file qmdisubwindow_p.h.
{
         RestoreAction,
         MoveAction,
         ResizeAction,
         MinimizeAction,
         MaximizeAction,
         StayOnTopAction,
         CloseAction,
         /* Add new states _above_ this line! */
         NumWindowStateActions
     };
Constructors and Destructors
QMdiSubWindowPrivate()
QMdiSubWindowPrivate::QMdiSubWindowPrivate ()
Warning
This function is not part of the public interface.
Definition at line 877 of file qmdisubwindow.cpp.
     : baseWidget(0),
       restoreFocusWidget(0),
       controlContainer(0),
 #ifndef QT_NO_SIZEGRIP
       sizeGrip(0),
 #endif
 #ifndef QT_NO_RUBBERBAND
       rubberBand(0),
 #endif
       userMinimumSize(0,0),
       resizeEnabled(true),
       moveEnabled(true),
       isInInteractiveMode(false),
 #ifndef QT_NO_RUBBERBAND
       isInRubberBandMode(false),
 #endif
       isShadeMode(false),
       ignoreWindowTitleChange(false),
       ignoreNextActivationEvent(false),
       activationEnabled(true),
       isShadeRequestFromMinimizeMode(false),
       isMaximizeMode(false),
       isWidgetHiddenByUs(false),
       isActive(false),
       isExplicitlyDeactivated(false),
       keyboardSingleStep(5),
       keyboardPageStep(20),
       resizeTimerId(-1),
       currentOperation(None),
       hoveredSubControl(QStyle::SC_None),
       activeSubControl(QStyle::SC_None),
       focusInReason(Qt::ActiveWindowFocusReason)
 {
     initOperationMap();
 }
Functions
_q_enterInteractiveMode()
void QMdiSubWindowPrivate::_q_enterInteractiveMode ()
Warning
This function is not part of the public interface.
Definition at line 936 of file qmdisubwindow.cpp.
Referenced by createSystemMenu().
 {
 #ifndef QT_NO_ACTION
     Q_Q(QMdiSubWindow);
     QAction *action = qobject_cast<QAction *>(q->sender());
     if (!action)
         return;
     QPoint pressPos;
     if (actions[MoveAction] && actions[MoveAction] == action) {
         currentOperation = Move;
         pressPos = QPoint(q->width() / 2, titleBarHeight() - 1);
     } else if (actions[ResizeAction] && actions[ResizeAction] == action) {
         currentOperation = q->isLeftToRight() ? BottomRightResize : BottomLeftResize;
         int offset = q->style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, q) / 2;
         int x = q->isLeftToRight() ? q->width() - offset : offset;
         pressPos = QPoint(x, q->height() - offset);
     } else {
         return;
     }
     updateCursor();
 #ifndef QT_NO_CURSOR
     q->cursor().setPos(q->mapToGlobal(pressPos));
 #endif
     mousePressPosition = q->mapToParent(pressPos);
     oldGeometry = q->geometry();
     isInInteractiveMode = true;
     q->setFocus();
 #ifndef QT_NO_RUBBERBAND
     if ((q->testOption(QMdiSubWindow::RubberBandResize)
             && (currentOperation == BottomRightResize || currentOperation == BottomLeftResize))
             || (q->testOption(QMdiSubWindow::RubberBandMove) && currentOperation == Move)) {
         enterRubberBandMode();
     } else
 #endif // QT_NO_RUBBERBAND
     {
         q->grabMouse();
     }
 #endif // QT_NO_ACTION
 }
_q_processFocusChanged()
void QMdiSubWindowPrivate::_q_processFocusChanged (QWidget * old, QWidget * now)
Warning
This function is not part of the public interface.
Definition at line 981 of file qmdisubwindow.cpp.
 {
     Q_UNUSED(old);
     Q_Q(QMdiSubWindow);
     if (now && (now == q || q->isAncestorOf(now))) {
         if (now == q && !isInInteractiveMode)
             setFocusWidget();
         setActive(true);
     }
 }
_q_updateStaysOnTopHint()
void QMdiSubWindowPrivate::_q_updateStaysOnTopHint ()
Warning
This function is not part of the public interface.
Definition at line 917 of file qmdisubwindow.cpp.
Referenced by createSystemMenu().
 {
 #ifndef QT_NO_ACTION
     Q_Q(QMdiSubWindow);
     if (QAction *senderAction = qobject_cast<QAction *>(q->sender())) {
         if (senderAction->isChecked()) {
             q->setWindowFlags(q->windowFlags() | Qt::WindowStaysOnTopHint);
             q->raise();
         } else {
             q->setWindowFlags(q->windowFlags() & ~Qt::WindowStaysOnTopHint);
             q->lower();
         }
     }
 #endif // QT_NO_ACTION
 }
addToSystemMenu()
void QMdiSubWindowPrivate::addToSystemMenu (WindowStateAction action, const QString & text, const char * slot)
Definition at line 2159 of file qmdisubwindow.cpp.
Referenced by createSystemMenu().
 {
     if (!systemMenu)
         return;
     actions[action] = systemMenu->addAction(text, q_func(), slot);
 }
autoRaise()
bool QMdiSubWindowPrivate::autoRaise () const inline
Definition at line 327 of file qmdisubwindow_p.h.
Referenced by titleBarOptions().
     {
         Q_Q(const QMdiSubWindow);
         return q->style()->styleHint(QStyle::SH_TitleBar_AutoRaise, 0, q);
     }
createSystemMenu()
void QMdiSubWindowPrivate::createSystemMenu ()
Warning
This function is not part of the public interface.
Definition at line 1060 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT_X(q, "QMdiSubWindowPrivate::createSystemMenu",
                "You can NOT call this function before QMdiSubWindow's ctor");
     systemMenu = new QMenu(q);
     const QStyle *style = q->style();
     addToSystemMenu(RestoreAction, QMdiSubWindow::tr("&Restore"), SLOT(showNormal()));
     actions[RestoreAction]->setIcon(style->standardIcon(QStyle::SP_TitleBarNormalButton, 0, q));
     actions[RestoreAction]->setEnabled(false);
     addToSystemMenu(MoveAction, QMdiSubWindow::tr("&Move"), SLOT(_q_enterInteractiveMode()));
     addToSystemMenu(ResizeAction, QMdiSubWindow::tr("&Size"), SLOT(_q_enterInteractiveMode()));
     addToSystemMenu(MinimizeAction, QMdiSubWindow::tr("Mi&nimize"), SLOT(showMinimized()));
     actions[MinimizeAction]->setIcon(style->standardIcon(QStyle::SP_TitleBarMinButton, 0, q));
     addToSystemMenu(MaximizeAction, QMdiSubWindow::tr("Ma&ximize"), SLOT(showMaximized()));
     actions[MaximizeAction]->setIcon(style->standardIcon(QStyle::SP_TitleBarMaxButton, 0, q));
     addToSystemMenu(StayOnTopAction, QMdiSubWindow::tr("Stay on &Top"), SLOT(_q_updateStaysOnTopHint()));
     actions[StayOnTopAction]->setCheckable(true);
     systemMenu->addSeparator();
     addToSystemMenu(CloseAction, QMdiSubWindow::tr("&Close"), SLOT(close()));
     actions[CloseAction]->setIcon(style->standardIcon(QStyle::SP_TitleBarCloseButton, 0, q));
 #if !defined(QT_NO_SHORTCUT)
     actions[CloseAction]->setShortcuts(QKeySequence::Close);
 #endif
     updateActions();
 }
desktopPalette()
QPalette QMdiSubWindowPrivate::desktopPalette () const
Definition at line 1937 of file qmdisubwindow.cpp.
 {
     Q_Q(const QMdiSubWindow);
     QPalette newPalette = q->palette();
     bool colorsInitialized = false;
 #ifdef Q_WS_WIN // ask system properties on windows
 #ifndef SPI_GETGRADIENTCAPTIONS
 #define SPI_GETGRADIENTCAPTIONS 0x1008
 #endif
 #ifndef COLOR_GRADIENTACTIVECAPTION
 #define COLOR_GRADIENTACTIVECAPTION 27
 #endif
 #ifndef COLOR_GRADIENTINACTIVECAPTION
 #define COLOR_GRADIENTINACTIVECAPTION 28
 #endif
     if (QApplication::desktopSettingsAware()) {
         newPalette.setColor(QPalette::Active, QPalette::Highlight,
                             colorref2qrgb(GetSysColor(COLOR_ACTIVECAPTION)));
         newPalette.setColor(QPalette::Inactive, QPalette::Highlight,
                             colorref2qrgb(GetSysColor(COLOR_INACTIVECAPTION)));
         newPalette.setColor(QPalette::Active, QPalette::HighlightedText,
                             colorref2qrgb(GetSysColor(COLOR_CAPTIONTEXT)));
         newPalette.setColor(QPalette::Inactive, QPalette::HighlightedText,
                             colorref2qrgb(GetSysColor(COLOR_INACTIVECAPTIONTEXT)));
         colorsInitialized = true;
         BOOL hasGradient = false;
         SystemParametersInfo(SPI_GETGRADIENTCAPTIONS, 0, &hasGradient, 0);
         if (hasGradient) {
             newPalette.setColor(QPalette::Active, QPalette::Base,
                                 colorref2qrgb(GetSysColor(COLOR_GRADIENTACTIVECAPTION)));
             newPalette.setColor(QPalette::Inactive, QPalette::Base,
                                 colorref2qrgb(GetSysColor(COLOR_GRADIENTINACTIVECAPTION)));
         } else {
             newPalette.setColor(QPalette::Active, QPalette::Base,
                                 newPalette.color(QPalette::Active, QPalette::Highlight));
             newPalette.setColor(QPalette::Inactive, QPalette::Base,
                                 newPalette.color(QPalette::Inactive, QPalette::Highlight));
         }
     }
 #endif // Q_WS_WIN
     if (!colorsInitialized) {
         newPalette.setColor(QPalette::Active, QPalette::Highlight,
                             newPalette.color(QPalette::Active, QPalette::Highlight));
         newPalette.setColor(QPalette::Active, QPalette::Base,
                             newPalette.color(QPalette::Active, QPalette::Highlight));
         newPalette.setColor(QPalette::Inactive, QPalette::Highlight,
                             newPalette.color(QPalette::Inactive, QPalette::Dark));
         newPalette.setColor(QPalette::Inactive, QPalette::Base,
                             newPalette.color(QPalette::Inactive, QPalette::Dark));
         newPalette.setColor(QPalette::Inactive, QPalette::HighlightedText,
                             newPalette.color(QPalette::Inactive, QPalette::Window));
     }
     return newPalette;
 }
drawTitleBarWhenMaximized()
bool QMdiSubWindowPrivate::drawTitleBarWhenMaximized () const
Warning
This function is not part of the public interface.
Definition at line 1779 of file qmdisubwindow.cpp.
Referenced by removeButtonsFromMenuBar(), showButtonsInMenuBar(), sizeParameters(), titleBarHeight(), and updateMask().
 {
     Q_Q(const QMdiSubWindow);
     if (q->window()->testAttribute(Qt::WA_CanHostQMdiSubWindowTitleBar))
         return false;
     if (isChildOfTabbedQMdiArea(q))
         return false;
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC) || defined(Q_WS_WINCE_WM)
     return true;
 #else
     if (q->style()->styleHint(QStyle::SH_Workspace_FillSpaceOnMaximize, 0, q))
         return true;
 #if defined(QT_NO_MENUBAR) || defined(QT_NO_MAINWINDOW)
     return true;
 #else
     QMainWindow *mainWindow = qobject_cast<QMainWindow *>(q->window());
     if (!mainWindow || !qobject_cast<QMenuBar *>(mainWindow->menuWidget())
         || mainWindow->menuWidget()->isHidden())
         return true;
     return isChildOfQMdiSubWindow(q);
 #endif
 #endif
 }
ensureWindowState()
void QMdiSubWindowPrivate::ensureWindowState (Qt::WindowState state)
Warning
This function is not part of the public interface.
Definition at line 1692 of file qmdisubwindow.cpp.
Referenced by setActive(), setMaximizeMode(), setMinimizeMode(), and setNormalMode().
 {
     Q_Q(QMdiSubWindow);
     Qt::WindowStates windowStates = q->windowState() | state;
     switch (state) {
     case Qt::WindowMinimized:
         windowStates &= ~Qt::WindowMaximized;
         windowStates &= ~Qt::WindowNoState;
         break;
     case Qt::WindowMaximized:
         windowStates &= ~Qt::WindowMinimized;
         windowStates &= ~Qt::WindowNoState;
         break;
     case Qt::WindowNoState:
         windowStates &= ~Qt::WindowMinimized;
         windowStates &= ~Qt::WindowMaximized;
         break;
     default:
         break;
     }
     if (baseWidget) {
         if (!(baseWidget->windowState() & Qt::WindowActive) && windowStates & Qt::WindowActive)
             baseWidget->overrideWindowState(windowStates & ~Qt::WindowActive);
         else
             baseWidget->overrideWindowState(windowStates);
     }
     q->overrideWindowState(windowStates);
 }
enterRubberBandMode()
void QMdiSubWindowPrivate::enterRubberBandMode ()
Definition at line 1903 of file qmdisubwindow.cpp.
Referenced by _q_enterInteractiveMode().
 {
     Q_Q(QMdiSubWindow);
     if (q->isMaximized())
         return;
     Q_ASSERT(oldGeometry.isValid());
     Q_ASSERT(parent);
     if (!rubberBand) {
         rubberBand = new QRubberBand(QRubberBand::Rectangle, q->parentWidget());
         // For accessibility to identify this special widget.
         rubberBand->setObjectName(QLatin1String("qt_rubberband"));
     }
     QPoint rubberBandPos = q->mapToParent(QPoint(0, 0));
     rubberBand->setGeometry(rubberBandPos.x(), rubberBandPos.y(),
                             oldGeometry.width(), oldGeometry.height());
     rubberBand->show();
     isInRubberBandMode = true;
     q->grabMouse();
 }
getOperation()
QMdiSubWindowPrivate::Operation QMdiSubWindowPrivate::getOperation (const QPoint & pos) const
Warning
This function is not part of the public interface.
Definition at line 1623 of file qmdisubwindow.cpp.
 {
     OperationInfoMap::const_iterator it;
     for (it = operationMap.constBegin(); it != operationMap.constEnd(); ++it)
         if (it.value().region.contains(pos))
             return it.key();
     return None;
 }
getRegion()
QRegion QMdiSubWindowPrivate::getRegion (Operation operation) const
Warning
This function is not part of the public interface.
Definition at line 1554 of file qmdisubwindow.cpp.
Referenced by updateDirtyRegions().
 {
     Q_Q(const QMdiSubWindow);
     int width = q->width();
     int height = q->height();
     int titleBarHeight = this->titleBarHeight();
     int frameWidth = q->style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, q);
     int cornerConst = titleBarHeight - frameWidth;
     int titleBarConst = 2 * titleBarHeight;
     if (operation == Move) {
         QStyleOptionTitleBar titleBarOptions = this->titleBarOptions();
         QRegion move(frameWidth, frameWidth, width - 2 * frameWidth, cornerConst);
         // Depending on which window flags are set, activated sub controllers will
         // be subtracted from the 'move' region.
         for (int i = 0; i < NumSubControls; ++i) {
             if (SubControls[i] == QStyle::SC_TitleBarLabel)
                 continue;
             move -= QRegion(q->style()->subControlRect(QStyle::CC_TitleBar, &titleBarOptions,
                             SubControls[i]));
         }
         return move;
     }
     QRegion region;
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     if (qobject_cast<QMacStyle *>(q->style()))
         return region;
 #endif
     switch (operation) {
     case TopResize:
         region = QRegion(titleBarHeight, 0, width - titleBarConst, frameWidth);
         break;
     case BottomResize:
         region = QRegion(titleBarHeight, height - frameWidth, width - titleBarConst, frameWidth);
         break;
     case LeftResize:
         region = QRegion(0, titleBarHeight, frameWidth, height - titleBarConst);
         break;
     case RightResize:
         region = QRegion(width - frameWidth, titleBarHeight, frameWidth, height - titleBarConst);
         break;
     case TopLeftResize:
         region = QRegion(0, 0, titleBarHeight, titleBarHeight)
                  - QRegion(frameWidth, frameWidth, cornerConst, cornerConst);
         break;
     case TopRightResize:
         region =  QRegion(width - titleBarHeight, 0, titleBarHeight, titleBarHeight)
                   - QRegion(width - titleBarHeight, frameWidth, cornerConst, cornerConst);
         break;
     case BottomLeftResize:
         region = QRegion(0, height - titleBarHeight, titleBarHeight, titleBarHeight)
                  - QRegion(frameWidth, height - titleBarHeight, cornerConst, cornerConst);
         break;
     case BottomRightResize:
         region = QRegion(width - titleBarHeight, height - titleBarHeight, titleBarHeight, titleBarHeight)
                  - QRegion(width - titleBarHeight, height - titleBarHeight, cornerConst, cornerConst);
         break;
     default:
         break;
     }
     return region;
 }
getSubControl()
QStyle::SubControl QMdiSubWindowPrivate::getSubControl (const QPoint & pos) const inline
Definition at line 301 of file qmdisubwindow_p.h.
     {
         Q_Q(const QMdiSubWindow);
         QStyleOptionTitleBar titleBarOptions = this->titleBarOptions();
         return q->style()->hitTestComplexControl(QStyle::CC_TitleBar, &titleBarOptions, pos, q);
     }
hasBorder()
bool QMdiSubWindowPrivate::hasBorder (const QStyleOptionTitleBar & options) const inline
Definition at line 321 of file qmdisubwindow_p.h.
Referenced by titleBarHeight(), and titleBarOptions().
     {
         Q_Q(const QMdiSubWindow);
         return !q->style()->styleHint(QStyle::SH_TitleBar_NoBorder, &options, q);
     }
iconSize()
QSize QMdiSubWindowPrivate::iconSize () const
Warning
This function is not part of the public interface.
Definition at line 2172 of file qmdisubwindow.cpp.
 {
     Q_Q(const QMdiSubWindow);
     if (!parent || q->windowFlags() & Qt::FramelessWindowHint)
         return QSize(-1, -1);
     return QSize(q->style()->pixelMetric(QStyle::PM_MdiSubWindowMinimizedWidth, 0, q), titleBarHeight());
 }
initOperationMap()
void QMdiSubWindowPrivate::initOperationMap ()
Warning
This function is not part of the public interface.
Definition at line 1039 of file qmdisubwindow.cpp.
Referenced by QMdiSubWindowPrivate().
 {
     operationMap.insert(Move, OperationInfo(HMove | VMove, Qt::ArrowCursor, false));
     operationMap.insert(TopResize, OperationInfo(VMove | VResize | VResizeReverse, Qt::SizeVerCursor));
     operationMap.insert(BottomResize, OperationInfo(VResize, Qt::SizeVerCursor));
     operationMap.insert(LeftResize, OperationInfo(HMove | HResize | HResizeReverse, Qt::SizeHorCursor));
     operationMap.insert(RightResize, OperationInfo(HResize, Qt::SizeHorCursor));
     operationMap.insert(TopLeftResize, OperationInfo(HMove | VMove | HResize | VResize | VResizeReverse
                                                      | HResizeReverse, Qt::SizeFDiagCursor));
     operationMap.insert(TopRightResize, OperationInfo(VMove | HResize | VResize
                                                       | VResizeReverse, Qt::SizeBDiagCursor));
     operationMap.insert(BottomLeftResize, OperationInfo(HMove | HResize | VResize | HResizeReverse,
                                                         Qt::SizeBDiagCursor));
     operationMap.insert(BottomRightResize, OperationInfo(HResize | VResize, Qt::SizeFDiagCursor));
 }
isMoveOperation()
bool QMdiSubWindowPrivate::isMoveOperation () const inline
Definition at line 338 of file qmdisubwindow_p.h.
     {
         return currentOperation == Move;
     }
isResizeOperation()
bool QMdiSubWindowPrivate::isResizeOperation () const inline
Definition at line 333 of file qmdisubwindow_p.h.
     {
         return currentOperation != None && currentOperation != Move;
     }
leaveInteractiveMode()
void QMdiSubWindowPrivate::leaveInteractiveMode ()
Warning
This function is not part of the public interface.
Definition at line 995 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
 #ifndef QT_NO_RUBBERBAND
     if (isInRubberBandMode)
         leaveRubberBandMode();
     else
 #endif
         q->releaseMouse();
     isInInteractiveMode = false;
     currentOperation = None;
     updateDirtyRegions();
     updateCursor();
     if (baseWidget && baseWidget->focusWidget())
         baseWidget->focusWidget()->setFocus();
 }
leaveRubberBandMode()
void QMdiSubWindowPrivate::leaveRubberBandMode ()
Definition at line 1923 of file qmdisubwindow.cpp.
Referenced by leaveInteractiveMode().
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT(rubberBand);
     Q_ASSERT(isInRubberBandMode);
     q->releaseMouse();
     isInRubberBandMode = false;
     q->setGeometry(rubberBand->geometry());
     rubberBand->hide();
     currentOperation = None;
 }
menuBar()
QMenuBar * QMdiSubWindowPrivate::menuBar () const
Definition at line 758 of file qmdisubwindow.cpp.
Referenced by setActive(), and setMaximizeMode().
 {
 #if defined(QT_NO_MAINWINDOW)
     return 0;
 #else
     Q_Q(const QMdiSubWindow);
     if (!q->isMaximized() || drawTitleBarWhenMaximized() || isChildOfTabbedQMdiArea(q))
         return 0;
     if (QMainWindow *mainWindow = qobject_cast<QMainWindow *>(q->window()))
         return mainWindow->menuBar();
     return 0;
 #endif
 }
originalWindowTitle()
QString QMdiSubWindowPrivate::originalWindowTitle ()
Definition at line 273 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     if (originalTitle.isNull()) {
         originalTitle = q->window()->windowTitle();
         if (originalTitle.isNull())
             originalTitle = QLatin1String("");
     }
     return originalTitle;
 }
processClickedSubControl()
void QMdiSubWindowPrivate::processClickedSubControl ()
Warning
This function is not part of the public interface.
Definition at line 1496 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     switch (activeSubControl) {
     case QStyle::SC_TitleBarContextHelpButton:
 #ifndef QT_NO_WHATSTHIS
         QWhatsThis::enterWhatsThisMode();
 #endif
         break;
     case QStyle::SC_TitleBarShadeButton:
         q->showShaded();
         hoveredSubControl = QStyle::SC_TitleBarUnshadeButton;
         break;
     case QStyle::SC_TitleBarUnshadeButton:
         if (q->isShaded())
             hoveredSubControl = QStyle::SC_TitleBarShadeButton;
         q->showNormal();
         break;
     case QStyle::SC_TitleBarMinButton:
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
         if (qobject_cast<QMacStyle *>(q->style())) {
             if (q->isMinimized())
                 q->showNormal();
             else
                 q->showMinimized();
             break;
         }
 #endif
         q->showMinimized();
         break;
     case QStyle::SC_TitleBarNormalButton:
         if (q->isShaded())
             hoveredSubControl = QStyle::SC_TitleBarMinButton;
         q->showNormal();
         break;
     case QStyle::SC_TitleBarMaxButton:
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
         if (qobject_cast<QMacStyle *>(q->style())) {
             if (q->isMaximized())
                 q->showNormal();
             else
                 q->showMaximized();
             break;
         }
 #endif
         q->showMaximized();
         break;
     case QStyle::SC_TitleBarCloseButton:
         q->close();
         break;
     default:
         break;
     }
 }
removeBaseWidget()
void QMdiSubWindowPrivate::removeBaseWidget ()
Warning
This function is not part of the public interface.
Definition at line 1015 of file qmdisubwindow.cpp.
 {
     if (!baseWidget)
         return;
     Q_Q(QMdiSubWindow);
     baseWidget->removeEventFilter(q);
     if (layout)
         layout->removeWidget(baseWidget);
     if (baseWidget->windowTitle() == q->windowTitle()) {
         ignoreWindowTitleChange = true;
         q->setWindowTitle(QString());
         ignoreWindowTitleChange = false;
         q->setWindowModified(false);
     }
     lastChildWindowTitle.clear();
     baseWidget->setParent(0);
     baseWidget = 0;
     isWidgetHiddenByUs = false;
 }
removeButtonsFromMenuBar()
void QMdiSubWindowPrivate::removeButtonsFromMenuBar ()
Warning
This function is not part of the public interface.
Definition at line 1850 of file qmdisubwindow.cpp.
Referenced by setNormalMode(), and showButtonsInMenuBar().
 {
     Q_Q(QMdiSubWindow);
     if (!controlContainer || isChildOfTabbedQMdiArea(q))
         return;
     QMenuBar *currentMenuBar = 0;
 #ifndef QT_NO_MAINWINDOW
     if (QMainWindow *mainWindow = qobject_cast<QMainWindow *>(q->window())) {
         // NB! We can't use menuBar() here because that one will actually create
         // a menubar for us if not set. That's not what we want :-)
         currentMenuBar = qobject_cast<QMenuBar *>(mainWindow->menuWidget());
     }
 #endif
     ignoreWindowTitleChange = true;
     controlContainer->removeButtonsFromMenuBar(currentMenuBar);
     ignoreWindowTitleChange = false;
     QWidget *topLevelWindow = q->window();
     topLevelWindow->removeEventFilter(q);
     if (baseWidget && !drawTitleBarWhenMaximized())
         topLevelWindow->setWindowModified(false);
     originalTitle = QString::null;
 }
restoreFocus()
void QMdiSubWindowPrivate::restoreFocus ()
Definition at line 2071 of file qmdisubwindow.cpp.
Referenced by setMaximizeMode(), and setNormalMode().
 {
     if (!restoreFocusWidget)
         return;
     if (!restoreFocusWidget->hasFocus() && q_func()->isAncestorOf(restoreFocusWidget)
             && restoreFocusWidget->isVisible()
             && restoreFocusWidget->focusPolicy() != Qt::NoFocus) {
         restoreFocusWidget->setFocus();
     }
     restoreFocusWidget = 0;
 }
setActive()
void QMdiSubWindowPrivate::setActive (bool activate, bool changeFocus = true)
Warning
This function is not part of the public interface.
Definition at line 1436 of file qmdisubwindow.cpp.
Referenced by _q_processFocusChanged(), setMinimizeMode(), and setNormalMode().
 {
     Q_Q(QMdiSubWindow);
     if (!parent || !activationEnabled)
         return;
     if (activate && !isActive && q->isEnabled()) {
         isActive = true;
         isExplicitlyDeactivated = false;
         Qt::WindowStates oldWindowState = q->windowState();
         ensureWindowState(Qt::WindowActive);
         emit q->aboutToActivate();
 #ifndef QT_NO_MENUBAR
         if (QMenuBar *mBar = menuBar())
             showButtonsInMenuBar(mBar);
 #endif
         Q_ASSERT(isActive);
         emit q->windowStateChanged(oldWindowState, q->windowState());
     } else if (!activate && isActive) {
         isActive = false;
         Qt::WindowStates oldWindowState = q->windowState();
         q->overrideWindowState(q->windowState() & ~Qt::WindowActive);
         if (changeFocus) {
             QWidget *focusWidget = QApplication::focusWidget();
             if (focusWidget && (focusWidget == q || q->isAncestorOf(focusWidget)))
                 focusWidget->clearFocus();
         }
         if (baseWidget)
             baseWidget->overrideWindowState(baseWidget->windowState() & ~Qt::WindowActive);
         Q_ASSERT(!isActive);
         emit q->windowStateChanged(oldWindowState, q->windowState());
     }
     if (activate && isActive && q->isEnabled() && !q->hasFocus()
             && !q->isAncestorOf(QApplication::focusWidget())) {
         if (changeFocus)
             setFocusWidget();
         ensureWindowState(Qt::WindowActive);
     }
     int frameWidth = q->style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, q);
     int titleBarHeight = this->titleBarHeight();
     QRegion windowDecoration = QRegion(0, 0, q->width(), q->height());
     windowDecoration -= QRegion(frameWidth, titleBarHeight, q->width() - 2 * frameWidth,
                                 q->height() - titleBarHeight - frameWidth);
     // Make sure we don't use cached style options if we get
     // resize events right before activation/deactivation.
     if (resizeTimerId != -1) {
         q->killTimer(resizeTimerId);
         resizeTimerId = -1;
         updateDirtyRegions();
     }
     q->update(windowDecoration);
 }
setEnabled()
void QMdiSubWindowPrivate::setEnabled (WindowStateAction action, bool enable = true)
Definition at line 2152 of file qmdisubwindow.cpp.
Referenced by setMaximizeMode(), setMinimizeMode(), and setNormalMode().
 {
     if (actions[action])
         actions[action]->setEnabled(enable);
 }
setFocusWidget()
void QMdiSubWindowPrivate::setFocusWidget ()
Definition at line 2027 of file qmdisubwindow.cpp.
Referenced by _q_processFocusChanged(), and setActive().
 {
     Q_Q(QMdiSubWindow);
     if (!baseWidget) {
         q->setFocus();
         return;
     }
     // This will give focus to the next child if possible, otherwise
     // do nothing, hence it's not possible to tab between windows with
     // just hitting tab (unless Qt::TabFocus is removed from the focus policy).
     if (focusInReason == Qt::TabFocusReason) {
         q->focusNextChild();
         return;
     }
     // Same as above, but gives focus to the previous child.
     if (focusInReason == Qt::BacktabFocusReason) {
         q->focusPreviousChild();
         return;
     }
     if (QWidget *focusWidget = baseWidget->focusWidget()) {
         if (!focusWidget->hasFocus() && q->isAncestorOf(focusWidget)
                 && focusWidget->isVisible() && !q->isMinimized()
                 && focusWidget->focusPolicy() != Qt::NoFocus) {
             focusWidget->setFocus();
         } else {
             q->setFocus();
         }
         return;
     }
     QWidget *focusWidget = q->nextInFocusChain();
     while (focusWidget && focusWidget != q && focusWidget->focusPolicy() == Qt::NoFocus)
         focusWidget = focusWidget->nextInFocusChain();
     if (focusWidget && q->isAncestorOf(focusWidget))
         focusWidget->setFocus();
     else if (baseWidget->focusPolicy() != Qt::NoFocus)
         baseWidget->setFocus();
     else if (!q->hasFocus())
         q->setFocus();
 }
setMaximizeMode()
void QMdiSubWindowPrivate::setMaximizeMode ()
Warning
This function is not part of the public interface.
Definition at line 1347 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT(parent);
     ensureWindowState(Qt::WindowMaximized);
     isShadeMode = false;
     isMaximizeMode = true;
     if (!restoreFocusWidget && q->isAncestorOf(QApplication::focusWidget()))
         restoreFocusWidget = QApplication::focusWidget();
 #ifndef QT_NO_SIZEGRIP
     setSizeGripVisible(false);
 #endif
     // Store old geometry and set restore size if not already set.
     if (!restoreSize.isValid()) {
         oldGeometry = q->geometry();
         restoreSize.setWidth(oldGeometry.width());
         restoreSize.setHeight(oldGeometry.height());
     }
     // Hide the window before we change the geometry to avoid multiple resize
     // events and wrong window state.
     const bool wasVisible = q->isVisible();
     if (wasVisible)
         q->setVisible(false);
     // Show the internal widget if it was hidden by us.
     if (baseWidget && isWidgetHiddenByUs) {
         baseWidget->show();
         isWidgetHiddenByUs = false;
     }
     updateGeometryConstraints();
     if (wasVisible) {
 #ifndef QT_NO_MENUBAR
         if (QMenuBar *mBar = menuBar())
             showButtonsInMenuBar(mBar);
         else
 #endif
         if (!controlContainer)
             controlContainer = new ControlContainer(q);
     }
     QWidget *parent = q->parentWidget();
     QRect availableRect = parent->contentsRect();
     // Adjust geometry if the sub-window is inside a scroll area.
     QAbstractScrollArea *scrollArea = qobject_cast<QAbstractScrollArea *>(parent->parentWidget());
     if (scrollArea && scrollArea->viewport() == parent) {
         QScrollBar *hbar = scrollArea->horizontalScrollBar();
         QScrollBar *vbar = scrollArea->verticalScrollBar();
         const int xOffset = hbar ? hbar->value() : 0;
         const int yOffset = vbar ? vbar->value() : 0;
         availableRect.adjust(-xOffset, -yOffset, -xOffset, -yOffset);
         oldGeometry.adjust(xOffset, yOffset, xOffset, yOffset);
     }
     setNewGeometry(&availableRect);
     // QWidget::setGeometry will reset Qt::WindowMaximized so we have to update it here.
     ensureWindowState(Qt::WindowMaximized);
     if (wasVisible)
         q->setVisible(true);
     resizeEnabled = false;
     moveEnabled = false;
 #ifndef QT_NO_ACTION
     setEnabled(MoveAction, moveEnabled);
     setEnabled(MaximizeAction, false);
     setEnabled(MinimizeAction, true);
     setEnabled(RestoreAction, true);
     setEnabled(ResizeAction, resizeEnabled);
 #endif // QT_NO_ACTION
     Q_ASSERT(q->windowState() & Qt::WindowMaximized);
     Q_ASSERT(!(q->windowState() & Qt::WindowMinimized));
     restoreFocus();
     updateMask();
 }
setMinimizeMode()
void QMdiSubWindowPrivate::setMinimizeMode ()
Warning
This function is not part of the public interface.
Definition at line 1248 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT(parent);
     ensureWindowState(Qt::WindowMinimized);
     isShadeRequestFromMinimizeMode = true;
     q->showShaded();
     isShadeRequestFromMinimizeMode = false;
     moveEnabled = false;
 #ifndef QT_NO_ACTION
     setEnabled(MoveAction, moveEnabled);
 #endif
     Q_ASSERT(q->windowState() & Qt::WindowMinimized);
     Q_ASSERT(!(q->windowState() & Qt::WindowMaximized));
     // This should be a valid assert, but people can actually re-implement
     // setVisible and do crazy stuff, so we're not guaranteed that
     // the widget is hidden after calling hide().
     // Q_ASSERT(baseWidget ? baseWidget->isHidden() : true);
     setActive(true);
 }
setNewGeometry() [1/2]
void QMdiSubWindowPrivate::setNewGeometry (const QPoint & pos)
Warning
This function is not part of the public interface.
Definition at line 1180 of file qmdisubwindow.cpp.
Referenced by setMaximizeMode().
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT(currentOperation != None);
     Q_ASSERT(parent);
     uint cflags = operationMap.find(currentOperation).value().changeFlags;
     int posX = pos.x();
     int posY = pos.y();
     const bool restrictHorizontal = !q->testOption(QMdiSubWindow::AllowOutsideAreaHorizontally);
     const bool restrictVertical = !q->testOption(QMdiSubWindow::AllowOutsideAreaVertically);
     if (restrictHorizontal || restrictVertical) {
         QRect parentRect = q->parentWidget()->rect();
         if (restrictVertical && (cflags & VResizeReverse || currentOperation == Move)) {
             posY = qMin(qMax(mousePressPosition.y() - oldGeometry.y(), posY),
                         parentRect.height() - BoundaryMargin);
         }
         if (currentOperation == Move) {
             if (restrictHorizontal)
                 posX = qMin(qMax(BoundaryMargin, posX), parentRect.width() - BoundaryMargin);
             if (restrictVertical)
                 posY = qMin(posY, parentRect.height() - BoundaryMargin);
         } else {
             if (restrictHorizontal) {
                 if (cflags & HResizeReverse)
                     posX = qMax(mousePressPosition.x() - oldGeometry.x(), posX);
                 else
                     posX = qMin(parentRect.width() - (oldGeometry.x() + oldGeometry.width()
                                                       - mousePressPosition.x()), posX);
             }
             if (restrictVertical && !(cflags & VResizeReverse)) {
                 posY = qMin(parentRect.height() - (oldGeometry.y() + oldGeometry.height()
                                                    - mousePressPosition.y()), posY);
             }
         }
     }
     QRect geometry;
     if (cflags & (HMove | VMove)) {
         int dx = getMoveDeltaComponent(cflags, HMove, HResize, posX - mousePressPosition.x(),
                                        oldGeometry.width() - internalMinimumSize.width(),
                                        oldGeometry.width() - q->maximumWidth());
         int dy = getMoveDeltaComponent(cflags, VMove, VResize, posY - mousePressPosition.y(),
                                        oldGeometry.height() - internalMinimumSize.height(),
                                        oldGeometry.height() - q->maximumHeight());
         geometry.setTopLeft(oldGeometry.topLeft() + QPoint(dx, dy));
     } else {
         geometry.setTopLeft(q->geometry().topLeft());
     }
     if (cflags & (HResize | VResize)) {
         int dx = getResizeDeltaComponent(cflags, HResize, HResizeReverse,
                                          posX - mousePressPosition.x());
         int dy = getResizeDeltaComponent(cflags, VResize, VResizeReverse,
                                          posY - mousePressPosition.y());
         geometry.setSize(oldGeometry.size() + QSize(dx, dy));
     } else {
         geometry.setSize(q->geometry().size());
     }
     setNewGeometry(&geometry);
 }
setNewGeometry() [2/2]
void QMdiSubWindowPrivate::setNewGeometry (QRect * geometry) inline
Definition at line 308 of file qmdisubwindow_p.h.
     {
         Q_Q(QMdiSubWindow);
         Q_ASSERT(parent);
         geometry->setSize(geometry->size().expandedTo(internalMinimumSize));
 #ifndef QT_NO_RUBBERBAND
         if (isInRubberBandMode)
             rubberBand->setGeometry(*geometry);
         else
 #endif
             q->setGeometry(*geometry);
     }
setNewWindowTitle()
void QMdiSubWindowPrivate::setNewWindowTitle ()
Definition at line 284 of file qmdisubwindow.cpp.
Referenced by updateWindowTitle().
 {
     Q_Q(QMdiSubWindow);
     QString childTitle = q->windowTitle();
     if (childTitle.isEmpty())
         return;
     QString original = originalWindowTitle();
     if (!original.isEmpty()) {
         if (!original.contains(QMdiSubWindow::tr("- [%1]").arg(childTitle)))
             q->window()->setWindowTitle(QMdiSubWindow::tr("%1 - [%2]").arg(original, childTitle));
     } else {
         q->window()->setWindowTitle(childTitle);
     }
 }
setNormalMode()
void QMdiSubWindowPrivate::setNormalMode ()
Warning
This function is not part of the public interface.
Definition at line 1276 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT(parent);
     isShadeMode = false;
     isMaximizeMode = false;
     ensureWindowState(Qt::WindowNoState);
 #ifndef QT_NO_MENUBAR
     removeButtonsFromMenuBar();
 #endif
     // Hide the window before we change the geometry to avoid multiple resize
     // events and wrong window state.
     const bool wasVisible = q->isVisible();
     if (wasVisible)
         q->setVisible(false);
     // Restore minimum size if set by user.
     if (!userMinimumSize.isNull()) {
         q->setMinimumSize(userMinimumSize);
         userMinimumSize = QSize(0, 0);
     }
     // Show the internal widget if it was hidden by us,
     if (baseWidget && isWidgetHiddenByUs) {
         baseWidget->show();
         isWidgetHiddenByUs = false;
     }
     updateGeometryConstraints();
     QRect newGeometry = oldGeometry;
     newGeometry.setSize(restoreSize.expandedTo(internalMinimumSize));
     q->setGeometry(newGeometry);
     if (wasVisible)
         q->setVisible(true);
     // Invalidate the restore size.
     restoreSize.setWidth(-1);
     restoreSize.setHeight(-1);
 #ifndef QT_NO_SIZEGRIP
     setSizeGripVisible(true);
 #endif
 #ifndef QT_NO_ACTION
     setEnabled(MoveAction, true);
     setEnabled(MaximizeAction, true);
     setEnabled(MinimizeAction, true);
     setEnabled(RestoreAction, false);
     setEnabled(ResizeAction, resizeEnabled);
 #endif // QT_NO_ACTION
     Q_ASSERT(!(q_func()->windowState() & Qt::WindowMinimized));
     // This sub-window can be maximized when shown above if not the
     // QMdiArea::DontMaximizeSubWindowOnActionvation is set. Make sure
     // the Qt::WindowMaximized flag is set accordingly.
     Q_ASSERT((isMaximizeMode && q_func()->windowState() & Qt::WindowMaximized)
              || (!isMaximizeMode && !(q_func()->windowState() & Qt::WindowMaximized)));
     Q_ASSERT(!isShadeMode);
     setActive(true);
     restoreFocus();
     updateMask();
 }
setSizeGrip()
void QMdiSubWindowPrivate::setSizeGrip (QSizeGrip * newSizeGrip)
Warning
This function is not part of the public interface.
Definition at line 2185 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     if (!newSizeGrip || sizeGrip || q->windowFlags() & Qt::FramelessWindowHint)
         return;
     if (layout && layout->indexOf(newSizeGrip) != -1)
         return;
     newSizeGrip->setFixedSize(newSizeGrip->sizeHint());
     bool putSizeGripInLayout = layout ? true : false;
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     if (qobject_cast<QMacStyle *>(q->style()))
         putSizeGripInLayout = false;
 #endif
     if (putSizeGripInLayout) {
         layout->addWidget(newSizeGrip);
         layout->setAlignment(newSizeGrip, Qt::AlignBottom | Qt::AlignRight);
     } else {
         newSizeGrip->setParent(q);
         newSizeGrip->move(q->isLeftToRight() ? q->width() - newSizeGrip->width() : 0,
                           q->height() - newSizeGrip->height());
         sizeGrip = newSizeGrip;
     }
     newSizeGrip->raise();
     updateGeometryConstraints();
     newSizeGrip->installEventFilter(q);
 }
setSizeGripVisible()
void QMdiSubWindowPrivate::setSizeGripVisible (bool visible = true) const
Warning
This function is not part of the public interface.
Definition at line 2216 of file qmdisubwindow.cpp.
Referenced by setMaximizeMode(), and setNormalMode().
 {
     // See if we can find any size grips
     QList<QSizeGrip *> sizeGrips = q_func()->findChildren<QSizeGrip *>();
     foreach (QSizeGrip *grip, sizeGrips)
         grip->setVisible(visible);
 }
setVisible()
void QMdiSubWindowPrivate::setVisible (WindowStateAction action, bool visible = true)
Definition at line 2134 of file qmdisubwindow.cpp.
Referenced by QMdiAreaTabBar::contextMenuEvent(), and updateActions().
 {
 #ifndef QT_NO_ACTION
     if (actions[action])
         actions[action]->setVisible(visible);
 #endif
     Q_Q(QMdiSubWindow);
     if (!controlContainer)
         controlContainer = new ControlContainer(q);
     if (ControllerWidget *ctrlWidget = qobject_cast<ControllerWidget *>
                                        (controlContainer->controllerWidget())) {
         ctrlWidget->setControlVisible(action, visible);
     }
 }
setWindowFlags()
void QMdiSubWindowPrivate::setWindowFlags (Qt::WindowFlags windowFlags)
Warning
This function is not part of the public interface.
Please add QEvent::WindowFlagsChange event
Definition at line 2087 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     if (!parent) {
         q->setWindowFlags(windowFlags);
         return;
     }
     Qt::WindowFlags windowType = windowFlags & Qt::WindowType_Mask;
     if (windowType == Qt::Dialog || windowFlags & Qt::MSWindowsFixedSizeDialogHint)
         windowFlags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint;
     // Set standard flags if none of the customize flags are set
     if (!(windowFlags & CustomizeWindowFlags))
         windowFlags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowMinMaxButtonsHint | Qt::WindowCloseButtonHint;
     else if (windowFlags & Qt::FramelessWindowHint && windowFlags & Qt::WindowStaysOnTopHint)
         windowFlags = Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint;
     else if (windowFlags & Qt::FramelessWindowHint)
         windowFlags = Qt::FramelessWindowHint;
     windowFlags &= ~windowType;
     windowFlags |= Qt::SubWindow;
 #ifndef QT_NO_ACTION
     if (QAction *stayOnTopAction = actions[QMdiSubWindowPrivate::StayOnTopAction]) {
         if (windowFlags & Qt::WindowStaysOnTopHint)
             stayOnTopAction->setChecked(true);
         else
             stayOnTopAction->setChecked(false);
     }
 #endif
 #ifndef QT_NO_SIZEGRIP
     if ((windowFlags & Qt::FramelessWindowHint) && sizeGrip)
         delete sizeGrip;
 #endif
     q->setWindowFlags(windowFlags);
     updateGeometryConstraints();
     updateActions();
     QSize currentSize = q->size();
     if (q->isVisible() && (currentSize.width() < internalMinimumSize.width()
             || currentSize.height() < internalMinimumSize.height())) {
         q->resize(currentSize.expandedTo(internalMinimumSize));
     }
 }
showButtonsInMenuBar()
void QMdiSubWindowPrivate::showButtonsInMenuBar (QMenuBar * menuBar)
Warning
This function is not part of the public interface.
Definition at line 1811 of file qmdisubwindow.cpp.
Referenced by setActive(), and setMaximizeMode().
 {
     Q_Q(QMdiSubWindow);
     Q_ASSERT(q->isMaximized() && !drawTitleBarWhenMaximized());
     if (isChildOfTabbedQMdiArea(q))
         return;
     removeButtonsFromMenuBar();
     if (!controlContainer)
         controlContainer = new ControlContainer(q);
     ignoreWindowTitleChange = true;
     controlContainer->showButtonsInMenuBar(menuBar);
     ignoreWindowTitleChange = false;
     QWidget *topLevelWindow = q->window();
     topLevelWindow->setWindowModified(q->isWindowModified());
     topLevelWindow->installEventFilter(q);
     int buttonHeight = 0;
     if (controlContainer->controllerWidget())
         buttonHeight = controlContainer->controllerWidget()->height();
     else if (controlContainer->systemMenuLabel())
         buttonHeight = controlContainer->systemMenuLabel()->height();
     // This will rarely happen.
     if (menuBar && menuBar->height() < buttonHeight
             && topLevelWindow->layout()) {
         // Make sure topLevelWindow->contentsRect returns correct geometry.
         // topLevelWidget->updateGeoemtry will not do the trick here since it will post the event.
         QEvent event(QEvent::LayoutRequest);
         QApplication::sendEvent(topLevelWindow, &event);
     }
 }
sizeParameters()
void QMdiSubWindowPrivate::sizeParameters (int * margin, int * minWidth) const
Warning
This function is not part of the public interface.
Definition at line 1746 of file qmdisubwindow.cpp.
Referenced by updateGeometryConstraints().
 {
     Q_Q(const QMdiSubWindow);
     Qt::WindowFlags flags = q->windowFlags();
     if (!parent || flags & Qt::FramelessWindowHint) {
         *margin = 0;
         *minWidth = 0;
         return;
     }
     if (q->isMaximized() && !drawTitleBarWhenMaximized())
         *margin = 0;
     else
         *margin = q->style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, q);
     QStyleOptionTitleBar opt = this->titleBarOptions();
     int tempWidth = 0;
     for (int i = 0; i < NumSubControls; ++i) {
         if (SubControls[i] == QStyle::SC_TitleBarLabel) {
             tempWidth += 30;
             continue;
         }
         QRect rect = q->style()->subControlRect(QStyle::CC_TitleBar, &opt, SubControls[i], q);
         if (!rect.isValid())
             continue;
         tempWidth += rect.width();
     }
     *minWidth = tempWidth;
 }
titleBarHeight() [1/2]
int QMdiSubWindowPrivate::titleBarHeight (const QStyleOptionTitleBar & options) const
Warning
This function is not part of the public interface.
Definition at line 1724 of file qmdisubwindow.cpp.
 {
     Q_Q(const QMdiSubWindow);
     if (!parent || q->windowFlags() & Qt::FramelessWindowHint
         || (q->isMaximized() && !drawTitleBarWhenMaximized())) {
         return 0;
     }
     int height = q->style()->pixelMetric(QStyle::PM_TitleBarHeight, &options, q);
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     // ### Fix mac style, the +4 pixels hack is not necessary anymore
     if (qobject_cast<QMacStyle *>(q->style()))
         height -= 4;
 #endif
     if (hasBorder(options))
         height += q->isMinimized() ? 8 : 4;
     return height;
 }
titleBarHeight() [2/2]
int QMdiSubWindowPrivate::titleBarHeight () const inline
Definition at line 287 of file qmdisubwindow_p.h.
Referenced by _q_enterInteractiveMode(), getRegion(), iconSize(), setActive(), titleBarOptions(), updateGeometryConstraints(), and updateInternalWindowTitle().
     {
         Q_Q(const QMdiSubWindow);
         if (!parent || q->windowFlags() & Qt::FramelessWindowHint
             || (q->isMaximized() && !drawTitleBarWhenMaximized())) {
             return 0;
         }
         QStyleOptionTitleBar options = titleBarOptions();
         int height = options.rect.height();
         if (hasBorder(options))
             height += q->isMinimized() ? 8 : 4;
         return height;
     }
titleBarOptions()
QStyleOptionTitleBar QMdiSubWindowPrivate::titleBarOptions () const
Warning
This function is not part of the public interface.
Definition at line 1637 of file qmdisubwindow.cpp.
Referenced by getRegion(), sizeParameters(), and updateMask().
 {
     Q_Q(const QMdiSubWindow);
     QStyleOptionTitleBar titleBarOptions;
     titleBarOptions.initFrom(q);
     if (activeSubControl != QStyle::SC_None) {
         if (hoveredSubControl == activeSubControl) {
             titleBarOptions.state |= QStyle::State_Sunken;
             titleBarOptions.activeSubControls = activeSubControl;
         }
     } else if (autoRaise() && hoveredSubControl != QStyle::SC_None
                && hoveredSubControl != QStyle::SC_TitleBarLabel) {
         titleBarOptions.state |= QStyle::State_MouseOver;
         titleBarOptions.activeSubControls = hoveredSubControl;
     } else {
         titleBarOptions.state &= ~QStyle::State_MouseOver;
         titleBarOptions.activeSubControls = QStyle::SC_None;
     }
     titleBarOptions.subControls = QStyle::SC_All;
     titleBarOptions.titleBarFlags = q->windowFlags();
     titleBarOptions.titleBarState = q->windowState();
     titleBarOptions.palette = titleBarPalette;
     titleBarOptions.icon = menuIcon;
     if (isActive) {
         titleBarOptions.state |= QStyle::State_Active;
         titleBarOptions.titleBarState |= QStyle::State_Active;
         titleBarOptions.palette.setCurrentColorGroup(QPalette::Active);
     } else {
         titleBarOptions.state &= ~QStyle::State_Active;
         titleBarOptions.palette.setCurrentColorGroup(QPalette::Inactive);
     }
     int border = hasBorder(titleBarOptions) ? 4 : 0;
     int paintHeight = titleBarHeight(titleBarOptions);
     paintHeight -= q->isMinimized() ? 2 * border : border;
     titleBarOptions.rect = QRect(border, border, q->width() - 2 * border, paintHeight);
     if (!windowTitle.isEmpty()) {
         // Set the text here before asking for the width of the title bar label
         // in case people uses the actual text to calculate the width.
         titleBarOptions.text = windowTitle;
         titleBarOptions.fontMetrics = QFontMetrics(font);
         int width = q->style()->subControlRect(QStyle::CC_TitleBar, &titleBarOptions,
                                                QStyle::SC_TitleBarLabel, q).width();
         // Set elided text if we don't have enough space for the entire title.
         titleBarOptions.text = titleBarOptions.fontMetrics.elidedText(windowTitle, Qt::ElideRight, width);
     }
     return titleBarOptions;
 }
updateActions()
void QMdiSubWindowPrivate::updateActions ()
Definition at line 1996 of file qmdisubwindow.cpp.
Referenced by QMdiAreaTabBar::contextMenuEvent(), createSystemMenu(), and setWindowFlags().
 {
     Qt::WindowFlags windowFlags = q_func()->windowFlags();
     // Hide all
     for (int i = 0; i < NumWindowStateActions; ++i)
         setVisible(WindowStateAction(i), false);
     if (windowFlags & Qt::FramelessWindowHint)
         return;
     setVisible(StayOnTopAction, true);
     setVisible(MoveAction, moveEnabled);
     setVisible(ResizeAction, resizeEnabled);
     // CloseAction
     if (windowFlags & Qt::WindowSystemMenuHint)
         setVisible(CloseAction, true);
     // RestoreAction
     if (windowFlags & (Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint))
         setVisible(RestoreAction, true);
     // MinimizeAction
     if (windowFlags & Qt::WindowMinimizeButtonHint)
         setVisible(MinimizeAction, true);
     // MaximizeAction
     if (windowFlags & Qt::WindowMaximizeButtonHint)
         setVisible(MaximizeAction, true);
 }
updateCursor()
void QMdiSubWindowPrivate::updateCursor ()
Warning
This function is not part of the public interface.
Definition at line 1091 of file qmdisubwindow.cpp.
Referenced by _q_enterInteractiveMode(), and leaveInteractiveMode().
 {
 #ifndef QT_NO_CURSOR
     Q_Q(QMdiSubWindow);
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     if (qobject_cast<QMacStyle *>(q->style()))
         return;
 #endif
     if (currentOperation == None) {
         q->unsetCursor();
         return;
     }
     if (currentOperation == Move || operationMap.find(currentOperation).value().hover) {
         q->setCursor(operationMap.find(currentOperation).value().cursorShape);
         return;
     }
 #endif
 }
updateDirtyRegions()
void QMdiSubWindowPrivate::updateDirtyRegions ()
Warning
This function is not part of the public interface.
Definition at line 1115 of file qmdisubwindow.cpp.
Referenced by leaveInteractiveMode(), setActive(), and updateGeometryConstraints().
 {
     // No update necessary
     if (!parent)
         return;
     foreach (Operation operation, operationMap.keys())
         operationMap.find(operation).value().region = getRegion(operation);
 }
updateGeometryConstraints()
void QMdiSubWindowPrivate::updateGeometryConstraints ()
Warning
This function is not part of the public interface.
Definition at line 1128 of file qmdisubwindow.cpp.
Referenced by setMaximizeMode(), setNormalMode(), setSizeGrip(), and setWindowFlags().
 {
     Q_Q(QMdiSubWindow);
     if (!parent)
         return;
     internalMinimumSize = (!q->isMinimized() && !q->minimumSize().isNull())
                           ? q->minimumSize() : q->minimumSizeHint();
     int margin, minWidth;
     sizeParameters(&margin, &minWidth);
     q->setContentsMargins(margin, titleBarHeight(), margin, margin);
     if (q->isMaximized() || (q->isMinimized() && !q->isShaded())) {
         moveEnabled = false;
         resizeEnabled = false;
     } else {
         moveEnabled = true;
         if ((q->windowFlags() & Qt::MSWindowsFixedSizeDialogHint) || q->isShaded())
             resizeEnabled = false;
         else
             resizeEnabled = true;
     }
     updateDirtyRegions();
 }
updateInternalWindowTitle()
void QMdiSubWindowPrivate::updateInternalWindowTitle ()
Warning
This function is not part of the public interface.
Definition at line 2229 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     if (q->isWindowModified()) {
         windowTitle = q->windowTitle();
         windowTitle.replace(QLatin1String("[*]"), QLatin1String("*"));
     } else {
         windowTitle = qt_setWindowTitle_helperHelper(q->windowTitle(), q);
     }
     q->update(0, 0, q->width(), titleBarHeight());
 }
updateMask()
void QMdiSubWindowPrivate::updateMask ()
Warning
This function is not part of the public interface.
Definition at line 1155 of file qmdisubwindow.cpp.
Referenced by setMaximizeMode(), and setNormalMode().
 {
     Q_Q(QMdiSubWindow);
     if (!q->mask().isEmpty())
         q->clearMask();
     if (!parent)
         return;
     if ((q->isMaximized() && !drawTitleBarWhenMaximized())
         || q->windowFlags() & Qt::FramelessWindowHint)
         return;
     if (resizeTimerId == -1)
         cachedStyleOptions = titleBarOptions();
     cachedStyleOptions.rect = q->rect();
     QStyleHintReturnMask frameMask;
     q->style()->styleHint(QStyle::SH_WindowFrame_Mask, &cachedStyleOptions, q, &frameMask);
     if (!frameMask.region.isEmpty())
         q->setMask(frameMask.region);
 }
updateWindowTitle()
void QMdiSubWindowPrivate::updateWindowTitle (bool requestFromChild)
Definition at line 1879 of file qmdisubwindow.cpp.
 {
     Q_Q(QMdiSubWindow);
     if (isRequestFromChild && !q->windowTitle().isEmpty() && !lastChildWindowTitle.isEmpty()
             && lastChildWindowTitle != q->windowTitle()) {
         return;
     }
     QWidget *titleWidget = 0;
     if (isRequestFromChild)
         titleWidget = baseWidget;
     else
         titleWidget = q;
     if (!titleWidget || titleWidget->windowTitle().isEmpty())
         return;
     ignoreWindowTitleChange = true;
     q->setWindowTitle(titleWidget->windowTitle());
     if (q->maximizedButtonsWidget())
         setNewWindowTitle();
     ignoreWindowTitleChange = false;
 }
Properties
actions
QPointer<QAction> QMdiSubWindowPrivate::actions[NumWindowStateActions]
Definition at line 216 of file qmdisubwindow_p.h.
Referenced by _q_enterInteractiveMode(), addToSystemMenu(), createSystemMenu(), setEnabled(), setVisible(), and setWindowFlags().
activationEnabled
bool QMdiSubWindowPrivate::activationEnabled
Definition at line 200 of file qmdisubwindow_p.h.
Referenced by setActive().
activeSubControl
QStyle::SubControl QMdiSubWindowPrivate::activeSubControl
Definition at line 211 of file qmdisubwindow_p.h.
Referenced by processClickedSubControl(), and titleBarOptions().
baseWidget
QPointer<QWidget> QMdiSubWindowPrivate::baseWidget
Definition at line 177 of file qmdisubwindow_p.h.
Referenced by ensureWindowState(), leaveInteractiveMode(), removeBaseWidget(), removeButtonsFromMenuBar(), setActive(), setFocusWidget(), setMaximizeMode(), setNormalMode(), and updateWindowTitle().
cachedStyleOptions
QStyleOptionTitleBar QMdiSubWindowPrivate::cachedStyleOptions
Definition at line 224 of file qmdisubwindow_p.h.
Referenced by updateMask().
controlContainer
QPointer<QMdi::ControlContainer> QMdiSubWindowPrivate::controlContainer
Definition at line 179 of file qmdisubwindow_p.h.
Referenced by removeButtonsFromMenuBar(), setMaximizeMode(), setVisible(), and showButtonsInMenuBar().
currentOperation
Operation QMdiSubWindowPrivate::currentOperation
Definition at line 209 of file qmdisubwindow_p.h.
Referenced by _q_enterInteractiveMode(), leaveInteractiveMode(), leaveRubberBandMode(), setNewGeometry(), and updateCursor().
focusInReason
Qt::FocusReason QMdiSubWindowPrivate::focusInReason
Definition at line 212 of file qmdisubwindow_p.h.
Referenced by setFocusWidget().
font
QFont QMdiSubWindowPrivate::font
Definition at line 222 of file qmdisubwindow_p.h.
Referenced by titleBarOptions().
hoveredSubControl
QStyle::SubControl QMdiSubWindowPrivate::hoveredSubControl
Definition at line 210 of file qmdisubwindow_p.h.
Referenced by processClickedSubControl(), and titleBarOptions().
ignoreNextActivationEvent
bool QMdiSubWindowPrivate::ignoreNextActivationEvent
Definition at line 199 of file qmdisubwindow_p.h.
ignoreWindowTitleChange
bool QMdiSubWindowPrivate::ignoreWindowTitleChange
Definition at line 198 of file qmdisubwindow_p.h.
Referenced by removeBaseWidget(), removeButtonsFromMenuBar(), showButtonsInMenuBar(), and updateWindowTitle().
internalMinimumSize
QSize QMdiSubWindowPrivate::internalMinimumSize
Definition at line 188 of file qmdisubwindow_p.h.
Referenced by setNewGeometry(), setNormalMode(), setWindowFlags(), and updateGeometryConstraints().
isActive
bool QMdiSubWindowPrivate::isActive
Definition at line 204 of file qmdisubwindow_p.h.
Referenced by setActive(), and titleBarOptions().
isExplicitlyDeactivated
bool QMdiSubWindowPrivate::isExplicitlyDeactivated
Definition at line 205 of file qmdisubwindow_p.h.
Referenced by setActive().
isInInteractiveMode
bool QMdiSubWindowPrivate::isInInteractiveMode
Definition at line 193 of file qmdisubwindow_p.h.
Referenced by _q_enterInteractiveMode(), _q_processFocusChanged(), and leaveInteractiveMode().
isInRubberBandMode
bool QMdiSubWindowPrivate::isInRubberBandMode
Definition at line 195 of file qmdisubwindow_p.h.
Referenced by enterRubberBandMode(), leaveInteractiveMode(), and leaveRubberBandMode().
isMaximizeMode
bool QMdiSubWindowPrivate::isMaximizeMode
Definition at line 202 of file qmdisubwindow_p.h.
Referenced by setMaximizeMode(), and setNormalMode().
isShadeMode
bool QMdiSubWindowPrivate::isShadeMode
Definition at line 197 of file qmdisubwindow_p.h.
Referenced by setMaximizeMode(), and setNormalMode().
isShadeRequestFromMinimizeMode
bool QMdiSubWindowPrivate::isShadeRequestFromMinimizeMode
Definition at line 201 of file qmdisubwindow_p.h.
Referenced by setMinimizeMode().
isWidgetHiddenByUs
bool QMdiSubWindowPrivate::isWidgetHiddenByUs
Definition at line 203 of file qmdisubwindow_p.h.
Referenced by removeBaseWidget(), setMaximizeMode(), and setNormalMode().
keyboardPageStep
int QMdiSubWindowPrivate::keyboardPageStep
Definition at line 207 of file qmdisubwindow_p.h.
keyboardSingleStep
int QMdiSubWindowPrivate::keyboardSingleStep
Definition at line 206 of file qmdisubwindow_p.h.
lastChildWindowTitle
QString QMdiSubWindowPrivate::lastChildWindowTitle
Definition at line 219 of file qmdisubwindow_p.h.
Referenced by removeBaseWidget(), and updateWindowTitle().
menuIcon
QIcon QMdiSubWindowPrivate::menuIcon
Definition at line 223 of file qmdisubwindow_p.h.
Referenced by titleBarOptions().
mousePressPosition
QPoint QMdiSubWindowPrivate::mousePressPosition
Definition at line 186 of file qmdisubwindow_p.h.
Referenced by _q_enterInteractiveMode(), and setNewGeometry().
moveEnabled
bool QMdiSubWindowPrivate::moveEnabled
Definition at line 192 of file qmdisubwindow_p.h.
Referenced by setMaximizeMode(), setMinimizeMode(), updateActions(), and updateGeometryConstraints().
oldGeometry
QRect QMdiSubWindowPrivate::oldGeometry
Definition at line 187 of file qmdisubwindow_p.h.
Referenced by _q_enterInteractiveMode(), enterRubberBandMode(), setMaximizeMode(), setNewGeometry(), and setNormalMode().
operationMap
OperationInfoMap QMdiSubWindowPrivate::operationMap
Definition at line 213 of file qmdisubwindow_p.h.
Referenced by getOperation(), initOperationMap(), setNewGeometry(), updateCursor(), and updateDirtyRegions().
options
QMdiSubWindow::SubWindowOptions QMdiSubWindowPrivate::options
Definition at line 218 of file qmdisubwindow_p.h.
originalTitle
QString QMdiSubWindowPrivate::originalTitle
Definition at line 225 of file qmdisubwindow_p.h.
Referenced by removeButtonsFromMenuBar().
resizeEnabled
bool QMdiSubWindowPrivate::resizeEnabled
Definition at line 191 of file qmdisubwindow_p.h.
Referenced by setMaximizeMode(), setNormalMode(), updateActions(), and updateGeometryConstraints().
resizeTimerId
int QMdiSubWindowPrivate::resizeTimerId
Definition at line 208 of file qmdisubwindow_p.h.
Referenced by setActive(), and updateMask().
restoreFocusWidget
QPointer<QWidget> QMdiSubWindowPrivate::restoreFocusWidget
Definition at line 178 of file qmdisubwindow_p.h.
Referenced by restoreFocus(), and setMaximizeMode().
restoreSize
QSize QMdiSubWindowPrivate::restoreSize
Definition at line 190 of file qmdisubwindow_p.h.
Referenced by setMaximizeMode(), and setNormalMode().
rubberBand
QRubberBand* QMdiSubWindowPrivate::rubberBand
Definition at line 184 of file qmdisubwindow_p.h.
Referenced by enterRubberBandMode(), and leaveRubberBandMode().
sizeGrip
QPointer<QSizeGrip> QMdiSubWindowPrivate::sizeGrip
Definition at line 181 of file qmdisubwindow_p.h.
Referenced by setSizeGrip(), and setWindowFlags().
systemMenu
QPointer<QMenu> QMdiSubWindowPrivate::systemMenu
Definition at line 214 of file qmdisubwindow_p.h.
Referenced by addToSystemMenu(), QMdiAreaTabBar::contextMenuEvent(), and createSystemMenu().
titleBarPalette
QPalette QMdiSubWindowPrivate::titleBarPalette
Definition at line 220 of file qmdisubwindow_p.h.
Referenced by titleBarOptions().
userMinimumSize
QSize QMdiSubWindowPrivate::userMinimumSize
Definition at line 189 of file qmdisubwindow_p.h.
Referenced by setNormalMode().
windowTitle
QString QMdiSubWindowPrivate::windowTitle
Definition at line 221 of file qmdisubwindow_p.h.
Referenced by titleBarOptions(), and updateInternalWindowTitle().
The documentation for this class was generated from the following files:
/src/gui/widgets/qmdisubwindow_p.h
/src/gui/widgets/qmdisubwindow.cpp