Qt 4.8: QDeclarativeTimeLineValue Class Reference
QDeclarativeTimeLineValue Class Reference
The QDeclarativeTimeLineValue class provides a value that can be modified by QDeclarativeTimeLine.
#include <qdeclarativetimeline_p_p.h>
Public Functions
operator qreal () const
QDeclarativeTimeLineValue & operator= (qreal v)
QDeclarativeTimeLineValue (qreal v=0.)
Construct a new QDeclarativeTimeLineValue with an initial value.
virtual void setValue (qreal v)
Set the current value.
QDeclarativeTimeLine * timeLine () const
If a QDeclarativeTimeLine is operating on this value, return a pointer to it, otherwise return null.
virtual qreal value () const
Return the current value.
Public Functions inherited from QDeclarativeTimeLineObject
QDeclarativeTimeLineObject ()
virtual ~QDeclarativeTimeLineObject ()
Properties
qreal _v
Friends
class QDeclarativeTimeLine
struct QDeclarativeTimeLinePrivate
Additional Inherited Members
Protected Variables inherited from QDeclarativeTimeLineObject
QDeclarativeTimeLine * _t
Detailed Description
The QDeclarativeTimeLineValue class provides a value that can be modified by QDeclarativeTimeLine.
Warning
This function is not part of the public interface.
Definition at line 132 of file qdeclarativetimeline_p_p.h.
Constructors and Destructors
QDeclarativeTimeLineValue()
QDeclarativeTimeLineValue::QDeclarativeTimeLineValue (qreal v = 0.) inline
Construct a new QDeclarativeTimeLineValue with an initial value.
Definition at line 135 of file qdeclarativetimeline_p_p.h.
 : _v(v) {}
Functions
operator qreal()
QDeclarativeTimeLineValue::operator qreal () const inline
Definition at line 142 of file qdeclarativetimeline_p_p.h.
 { return _v; }
operator=()
QDeclarativeTimeLineValue& QDeclarativeTimeLineValue::operator= (qreal v) inline
Definition at line 143 of file qdeclarativetimeline_p_p.h.
 { setValue(v); return *this; }
setValue()
void QDeclarativeTimeLineValue::setValue (qreal v) inline virtual
Set the current value.
Reimplemented in QDeclarativeTimeLineValueProxy< T >, QDeclarativeTimeLineValueProxy< QDeclarativeFlickablePrivate >, QDeclarativeTimeLineValueProxy< QDeclarativePathViewPrivate >, and QDeclarativeFlickablePrivate::Velocity.
Definition at line 138 of file qdeclarativetimeline_p_p.h.
Referenced by QDeclarativeTimeLinePrivate::advance(), QDeclarativeFlickablePrivate::Velocity::setValue(), and QDeclarativeTimeLineValueProxy< QDeclarativePathViewPrivate >::setValue().
 { _v = v; }
timeLine()
QDeclarativeTimeLine * QDeclarativeTimeLineValue::timeLine () const inline
If a QDeclarativeTimeLine is operating on this value, return a pointer to it, otherwise return null.
Definition at line 140 of file qdeclarativetimeline_p_p.h.
 { return _t; }
value()
qreal QDeclarativeTimeLineValue::value () const inline virtual
Return the current value.
Definition at line 137 of file qdeclarativetimeline_p_p.h.
Referenced by QDeclarativeTimeLinePrivate::advance(), QDeclarativeFlickablePrivate::fixup(), QDeclarativeGridViewPrivate::fixup(), QDeclarativeListViewPrivate::fixup(), QDeclarativeFlickablePrivate::flick(), QDeclarativeGridViewPrivate::flick(), QDeclarativeListViewPrivate::flick(), QDeclarativeFlickablePrivate::Velocity::setValue(), QDeclarativeFlickablePrivate::updateBeginningEnd(), and QDeclarativeFlickableVisibleArea::updateVisible().
 { return _v; }
Friends and Related Functions
QDeclarativeTimeLine
friend class QDeclarativeTimeLine friend
Definition at line 145 of file qdeclarativetimeline_p_p.h.
QDeclarativeTimeLinePrivate
friend struct QDeclarativeTimeLinePrivate friend
Definition at line 146 of file qdeclarativetimeline_p_p.h.
Properties
_v
qreal QDeclarativeTimeLineValue::_v private
Definition at line 147 of file qdeclarativetimeline_p_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativetimeline_p_p.h
/src/declarative/util/qdeclarativetimeline.cpp