Qt 4.8: QAxEventSink Class Reference
QAxEventSink Class Reference
Public Functions
void addProperty (DISPID propid, const char *name, const char *signal)
unsigned long __stdcall AddRef ()
void addSignal (DISPID memid, const char *name)
void advise (IConnectionPoint *cp, IID iid)
QUuid connectionInterface () const
QByteArray findProperty (DISPID dispID)
HRESULT __stdcall GetIDsOfNames (const _GUID &, wchar_t **, unsigned int, unsigned long, long *)
HRESULT __stdcall GetTypeInfo (UINT, LCID, ITypeInfo **)
HRESULT __stdcall GetTypeInfoCount (unsigned int *)
HRESULT __stdcall Invoke (DISPID dispIdMember, REFIID riid, LCID, WORD wFlags, DISPPARAMS *pDispParams, VARIANT *, EXCEPINFO *, UINT *)
HRESULT __stdcall OnChanged (DISPID dispID)
HRESULT __stdcall OnRequestEdit (DISPID dispID)
QMap< DISPID, QByteArray > propertyMap () const
QMap< DISPID, QByteArray > propSignalMap () const
QAxEventSink (QAxBase *com)
HRESULT __stdcall QueryInterface (REFIID riid, void **ppvObject)
unsigned long __stdcall Release ()
QMap< DISPID, QByteArray > signalMap () const
void unadvise ()
virtual ~QAxEventSink ()
Static Public Functions
static bool signalHasReceivers (QObject *qobject, const char *signalName)
Public Variables
IID ciid
QAxBase * combase
ULONG cookie
IConnectionPoint * cpoint
QMap< DISPID, QByteArray > props
QMap< DISPID, QByteArray > propsigs
LONG ref
QMap< DISPID, QByteArray > sigs
Detailed Description
Definition at line 211 of file qaxbase.cpp.
Constructors and Destructors
QAxEventSink()
QAxEventSink::QAxEventSink (QAxBase * com) inline
Definition at line 214 of file qaxbase.cpp.
         : cpoint(0), ciid(IID_NULL), combase(com), ref(1)
     {}
~QAxEventSink()
virtual QAxEventSink::~QAxEventSink () inline virtual
Definition at line 217 of file qaxbase.cpp.
     {
         Q_ASSERT(!cpoint);
     }
Functions
addProperty()
void QAxEventSink::addProperty (DISPID propid, const char * name, const char * signal) inline
Definition at line 284 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::addChangedSignal().
     {
         props.insert(propid, name);
         propsigs.insert(propid, signal);
     }
AddRef()
unsigned long __stdcall QAxEventSink::AddRef () inline
Definition at line 291 of file qaxbase.cpp.
     {
         return InterlockedIncrement(&ref);
     }
addSignal()
void QAxEventSink::addSignal (DISPID memid, const char * name) inline
Definition at line 259 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::readEventInterface().
     {
     QByteArray signalname = name;
     int pi = signalname.indexOf('(');
         int i = 0;
         while (type_conversion[i][0]) {
             int ti = pi;
             int len = int(strlen(type_conversion[i][0]));
             while ((ti = signalname.indexOf(type_conversion[i][0], ti)) != -1)
             signalname.replace(ti, len, type_conversion[i][1]);
             ++i;
         }
         sigs.insert(memid, signalname);
         QMap<DISPID,QByteArray>::ConstIterator it;
         DISPID id = -1;
         for (it = propsigs.constBegin(); it!= propsigs.constEnd(); ++it) {
             if (it.value() == signalname) {
                 id = it.key();
                 break;
             }
         }
         if (id != -1)
             propsigs.remove(id);
     }
advise()
void QAxEventSink::advise (IConnectionPoint * cp, IID iid) inline
Definition at line 240 of file qaxbase.cpp.
Referenced by QAxBase::connectNotify(), MetaObjectGenerator::readEventInfo(), MetaObjectGenerator::readEventInterface(), and MetaObjectGenerator::tryCache().
     {
         cpoint = cp;
         cpoint->AddRef();
         ciid = iid;
         cpoint->Advise((IUnknown*)(IDispatch*)this, &cookie);
     }
connectionInterface()
QUuid QAxEventSink::connectionInterface () const inline
Definition at line 222 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::metaObject().
     {
         return ciid;
     }
findProperty()
QByteArray QAxEventSink::findProperty (DISPID dispID)
Definition at line 618 of file qaxbase.cpp.
 {
     // look up in cache, and fall back to
     // type info for precompiled metaobjects
     QByteArray propname(props.value(dispID));
     if (!propname.isEmpty())
         return propname;
     IDispatch *dispatch = combase->d->dispatch();
     ITypeInfo *typeinfo = 0;
     if (dispatch)
         dispatch->GetTypeInfo(0, LOCALE_USER_DEFAULT, &typeinfo);
     if (!typeinfo)
         return propname;
     BSTR names;
     UINT cNames;
     typeinfo->GetNames(dispID, &names, 1, &cNames);
     if (cNames) {
         propname = QString::fromWCharArray(names).toLatin1();
         SysFreeString(names);
     }
     typeinfo->Release();
     QByteArray propsignal(propname + "Changed(");
     const QMetaObject *mo = combase->metaObject();
     int index = mo->indexOfProperty(propname);
     const QMetaProperty prop = mo->property(index);
     propsignal += prop.typeName();
     propsignal += ')';
     addProperty(dispID, propname, propsignal);
     return propname;
 }
GetIDsOfNames()
HRESULT __stdcall QAxEventSink::GetIDsOfNames (const _GUID & , wchar_t ** , unsigned int, unsigned long, long *) inline
Definition at line 324 of file qaxbase.cpp.
 { return E_NOTIMPL; }
GetTypeInfo()
HRESULT __stdcall QAxEventSink::GetTypeInfo (UINT , LCID , ITypeInfo **) inline
Definition at line 323 of file qaxbase.cpp.
 { return E_NOTIMPL; }
GetTypeInfoCount()
HRESULT __stdcall QAxEventSink::GetTypeInfoCount (unsigned int *) inline
Definition at line 322 of file qaxbase.cpp.
 { return E_NOTIMPL; }
Invoke()
HRESULT __stdcall QAxEventSink::Invoke (DISPID dispIdMember, REFIID riid, LCID , WORD wFlags, DISPPARAMS * pDispParams, VARIANT * , EXCEPINFO * , UINT *) inline
Definition at line 326 of file qaxbase.cpp.
     {
         // verify input
         if (riid != IID_NULL)
             return DISP_E_UNKNOWNINTERFACE;
         if (!(wFlags & DISPATCH_METHOD))
             return DISP_E_MEMBERNOTFOUND;
         if (!combase)
             return E_UNEXPECTED;
         QByteArray signame = sigs.value(dispIdMember);
         if (signame.isEmpty())
             return DISP_E_MEMBERNOTFOUND;
         QObject *qobject = combase->qObject();
         if (qobject->signalsBlocked())
             return S_OK;
         QAxMetaObject *axmeta = combase->internalMetaObject();
         const QMetaObject *meta = combase->metaObject();
         int index = -1;
         // emit the generic signal "as is"
         if (signalHasReceivers(qobject, "signal(QString,int,void*)")) {
             index = meta->indexOfSignal("signal(QString,int,void*)");
             Q_ASSERT(index != -1);
             QString nameString = QLatin1String(signame);
             void *argv[] = {0, &nameString, &pDispParams->cArgs, &pDispParams->rgvarg};
             combase->qt_metacall(QMetaObject::InvokeMetaMethod, index, argv);
         }
         HRESULT hres = S_OK;
         // get the signal information from the metaobject
         index = -1;
         if (signalHasReceivers(qobject, signame)) {
             index = meta->indexOfSignal(signame);
             Q_ASSERT(index != -1);
             const QMetaMethod signal = meta->method(index);
             Q_ASSERT(signal.methodType() == QMetaMethod::Signal);
             Q_ASSERT(signame == signal.signature());
             // verify parameter count
             int pcount = axmeta->numParameter(signame);
             int argcount = pDispParams->cArgs;
             if (pcount > argcount)
                 return DISP_E_PARAMNOTOPTIONAL;
             else if (pcount < argcount)
                 return DISP_E_BADPARAMCOUNT;
             // setup parameters (no return values in signals)
             bool ok = true;
             void *static_argv[QAX_NUM_PARAMS + 1];
             void *static_argv_pointer[QAX_NUM_PARAMS + 1];
             QVariant static_varp[QAX_NUM_PARAMS + 1];
             void **argv = 0;
             void **argv_pointer = 0; // in case we need an additional level of indirection
             QVariant *varp = 0;
             if (pcount) {
                 if (pcount <= QAX_NUM_PARAMS) {
                     argv = static_argv;
                     argv_pointer = static_argv_pointer;
                     varp = static_varp;
                 } else {
                     argv = new void*[pcount + 1];
                     argv_pointer = new void*[pcount + 1];
                     varp = new QVariant[pcount + 1];
                 }
                 argv[0] = 0;
                 argv_pointer[0] = 0;
             }
             int p;
             for (p = 0; p < pcount && ok; ++p) {
                 // map the VARIANT to the void*
                 QByteArray ptype = axmeta->paramType(signame, p);
                 varp[p + 1] = VARIANTToQVariant(pDispParams->rgvarg[pcount - p - 1], ptype);
                 argv_pointer[p + 1] = 0;
                 if (varp[p + 1].isValid()) {
                     if (varp[p + 1].type() == QVariant::UserType) {
                         argv[p + 1] = varp[p + 1].data();
                     } else if (ptype == "QVariant") {
                         argv[p + 1] = varp + p + 1;
                     } else {
                         argv[p + 1] = const_cast<void*>(varp[p + 1].constData());
                         if (ptype.endsWith('*')) {
                             argv_pointer[p + 1] = argv[p + 1];
                             argv[p + 1] = argv_pointer + p + 1;
                         }
                     }
                 } else if (ptype == "QVariant") {
                     argv[p + 1] = varp + p + 1;
                 } else {
                     ok = false;
                 }
             }
             if (ok) {
                 // emit the generated signal if everything went well
                 combase->qt_metacall(QMetaObject::InvokeMetaMethod, index, argv);
                 // update the VARIANT for references and free memory
                 for (p = 0; p < pcount; ++p) {
                     bool out;
                     QByteArray ptype = axmeta->paramType(signame, p, &out);
                     if (out) {
                         if (!QVariantToVARIANT(varp[p + 1], pDispParams->rgvarg[pcount - p - 1], ptype, out))
                             ok = false;
                     }
                 }
             }
             if (argv != static_argv) {
                 delete [] argv;
                 delete [] argv_pointer;
                 delete [] varp;
             }
             hres = ok ? S_OK : (ok ? DISP_E_MEMBERNOTFOUND : DISP_E_TYPEMISMATCH);
         }
         return hres;
     }
OnChanged()
HRESULT __stdcall QAxEventSink::OnChanged (DISPID dispID) inline
Definition at line 461 of file qaxbase.cpp.
     {
         // verify input
         if (dispID == DISPID_UNKNOWN || !combase)
             return S_OK;
         const QMetaObject *meta = combase->metaObject();
         if (!meta)
             return S_OK;
         QByteArray propname(findProperty(dispID));
         if (propname.isEmpty())
             return S_OK;
         QObject *qobject = combase->qObject();
         if (qobject->signalsBlocked())
             return S_OK;
         // emit the generic signal
         int index = meta->indexOfSignal("propertyChanged(QString)");
         if (index != -1) {
             QString propnameString = QString::fromLatin1(propname);
             void *argv[] = {0, &propnameString};
             combase->qt_metacall(QMetaObject::InvokeMetaMethod, index, argv);
         }
         QByteArray signame = propsigs.value(dispID);
         if (signame.isEmpty())
             return S_OK;
         index = meta->indexOfSignal(signame);
         if (index == -1) // bindable but not marked as bindable in typelib
             return S_OK;
         // get the signal information from the metaobject
         if (signalHasReceivers(qobject, signame)) {
             index = meta->indexOfSignal(signame);
             Q_ASSERT(index != -1);
             // setup parameters
             QVariant var = qobject->property(propname);
             if (!var.isValid())
                 return S_OK;
             const QMetaProperty metaProp = meta->property(meta->indexOfProperty(propname));
             void *argv[] = {0, var.data()};
             if (metaProp.type() == QVariant::LastType)
                 argv[1] = &var;
             // emit the "changed" signal
             combase->qt_metacall(QMetaObject::InvokeMetaMethod, index, argv);
         }
         return S_OK;
     }
OnRequestEdit()
HRESULT __stdcall QAxEventSink::OnRequestEdit (DISPID dispID) inline
Definition at line 514 of file qaxbase.cpp.
     {
         if (dispID == DISPID_UNKNOWN || !combase)
             return S_OK;
         QByteArray propname(findProperty(dispID));
         if (propname.isEmpty())
             return S_OK;
         return combase->propertyWritable(propname) ? S_OK : S_FALSE;
     }
propertyMap()
QMap<DISPID, QByteArray> QAxEventSink::propertyMap () const inline
Definition at line 230 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::metaObject().
     {
         return props;
     }
propSignalMap()
QMap<DISPID, QByteArray> QAxEventSink::propSignalMap () const inline
Definition at line 234 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::metaObject().
     {
         return propsigs;
     }
QueryInterface()
HRESULT __stdcall QAxEventSink::QueryInterface (REFIID riid, void ** ppvObject) inline
Definition at line 303 of file qaxbase.cpp.
     {
         *ppvObject = 0;
         if (riid == IID_IUnknown)
             *ppvObject = (IUnknown*)(IDispatch*)this;
         else if (riid == IID_IDispatch)
             *ppvObject = (IDispatch*)this;
         else if (riid == IID_IPropertyNotifySink)
             *ppvObject = (IPropertyNotifySink*)this;
         else if (ciid == riid)
             *ppvObject = (IDispatch*)this;
         else
             return E_NOINTERFACE;
         AddRef();
         return S_OK;
     }
Release()
unsigned long __stdcall QAxEventSink::Release () inline
Definition at line 295 of file qaxbase.cpp.
Referenced by QAxBase::clear().
     {
         LONG refCount = InterlockedDecrement(&ref);
         if (!refCount)
             delete this;
         return refCount;
     }
signalHasReceivers()
static bool QAxEventSink::signalHasReceivers (QObject * qobject, const char * signalName) inline static
Definition at line 526 of file qaxbase.cpp.
Referenced by checkHRESULT().
     {
         Q_ASSERT(qobject);
         return ((QAxObject*)qobject)->receivers(QByteArray::number(QSIGNAL_CODE) + signalName);
     }
signalMap()
QMap<DISPID, QByteArray> QAxEventSink::signalMap () const inline
Definition at line 226 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::metaObject().
     {
         return sigs;
     }
unadvise()
void QAxEventSink::unadvise () inline
Definition at line 249 of file qaxbase.cpp.
Referenced by QAxBase::clear().
     {
         combase = 0;
         if (cpoint) {
             cpoint->Unadvise(cookie);
             cpoint->Release();
             cpoint = 0;
         }
     }
Properties
ciid
IID QAxEventSink::ciid
Definition at line 533 of file qaxbase.cpp.
combase
QAxBase* QAxEventSink::combase
Definition at line 540 of file qaxbase.cpp.
cookie
ULONG QAxEventSink::cookie
Definition at line 534 of file qaxbase.cpp.
cpoint
IConnectionPoint* QAxEventSink::cpoint
Definition at line 532 of file qaxbase.cpp.
props
QMap<DISPID, QByteArray> QAxEventSink::props
Definition at line 538 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::tryCache().
propsigs
QMap<DISPID, QByteArray> QAxEventSink::propsigs
Definition at line 537 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::tryCache().
ref
LONG QAxEventSink::ref
Definition at line 541 of file qaxbase.cpp.
sigs
QMap<DISPID, QByteArray> QAxEventSink::sigs
Definition at line 536 of file qaxbase.cpp.
Referenced by MetaObjectGenerator::tryCache().
The documentation for this class was generated from the following file:
/src/activeqt/container/qaxbase.cpp