Qt 4.8: QLayoutPrivate Class Reference
QLayoutPrivate Class Reference
#include <qlayout_p.h>
Public Types
typedef QSpacerItem *(* QSpacerItemFactoryMethod) (const QLayout *layout, int w, int h, QSizePolicy::Policy hPolicy, QSizePolicy::Policy)
typedef QWidgetItem *(* QWidgetItemFactoryMethod) (const QLayout *layout, QWidget *widget)
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void doResize (const QSize &)
void getMargin (int *result, int userMargin, QStyle::PixelMetric pm) const
QLayoutPrivate ()
void reparentChildWidgets (QWidget *mw)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QSpacerItem * createSpacerItem (const QLayout *layout, int w, int h, QSizePolicy::Policy hPolicy=QSizePolicy::Minimum, QSizePolicy::Policy vPolicy=QSizePolicy::Minimum)
static QWidgetItem * createWidgetItem (const QLayout *layout, QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
uint activated: 1
uint autoNewChild: 1
QLayout::SizeConstraint constraint
uint enabled: 1
int insideSpacing
QWidget * menubar
QRect rect
uint topLevel: 1
int userBottomMargin
int userLeftMargin
int userRightMargin
int userTopMargin
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static QSpacerItemFactoryMethod spacerItemFactoryMethod = 0
static QWidgetItemFactoryMethod widgetItemFactoryMethod = 0
Detailed Description
Definition at line 65 of file qlayout_p.h.
Typedefs
QSpacerItemFactoryMethod
typedef QSpacerItem*(* QLayoutPrivate::QSpacerItemFactoryMethod) (const QLayout *layout, int w, int h, QSizePolicy::Policy hPolicy, QSizePolicy::Policy)
Definition at line 71 of file qlayout_p.h.
QWidgetItemFactoryMethod
typedef QWidgetItem*(* QLayoutPrivate::QWidgetItemFactoryMethod) (const QLayout *layout, QWidget *widget)
Definition at line 70 of file qlayout_p.h.
Constructors and Destructors
QLayoutPrivate()
QLayoutPrivate::QLayoutPrivate ()
Definition at line 161 of file qlayout.cpp.
     : QObjectPrivate(), insideSpacing(-1), userLeftMargin(-1), userTopMargin(-1), userRightMargin(-1),
       userBottomMargin(-1), topLevel(false), enabled(true), activated(true), autoNewChild(false),
       constraint(QLayout::SetDefaultConstraint), menubar(0)
 {
 }
Functions
createSpacerItem()
QSpacerItem * QLayoutPrivate::createSpacerItem (const QLayout * layout, int w, int h, QSizePolicy::Policy hPolicy = QSizePolicy::Minimum, QSizePolicy::Policy vPolicy = QSizePolicy::Minimum) static
Definition at line 198 of file qlayout.cpp.
Referenced by QBoxLayout::addStrut(), QBoxLayout::insertSpacing(), and QBoxLayout::insertStretch().
 {
     if (spacerItemFactoryMethod)
         if (QSpacerItem *si = (*spacerItemFactoryMethod)(layout, w, h, hPolicy, vPolicy))
             return si;
     return new QSpacerItem(w, h,  hPolicy, vPolicy);
 }
createWidgetItem()
QWidgetItem * QLayoutPrivate::createWidgetItem (const QLayout * layout, QWidget * widget) static
Definition at line 190 of file qlayout.cpp.
Referenced by QGridLayout::addWidget(), QLayout::addWidget(), QStackedLayout::insertWidget(), QBoxLayout::insertWidget(), QGridBox::QGridBox(), QFormLayoutPrivate::setWidget(), and QLayout::widgetEvent().
 {
     if (widgetItemFactoryMethod)
         if (QWidgetItem *wi = (*widgetItemFactoryMethod)(layout, widget))
             return wi;
     return new QWidgetItemV2(widget);
 }
doResize()
void QLayoutPrivate::doResize (const QSize & r)
Definition at line 702 of file qlayout.cpp.
 {
     Q_Q(QLayout);
     int mbh = menuBarHeightForWidth(menubar, r.width());
     QWidget *mw = q->parentWidget();
     QRect rect = mw->testAttribute(Qt::WA_LayoutOnEntireRect) ? mw->rect() : mw->contentsRect();
     rect.setTop(rect.top() + mbh);
     q->setGeometry(rect);
 #ifndef QT_NO_MENUBAR
     if (menubar)
         menubar->setGeometry(0,0,r.width(), mbh);
 #endif
 }
getMargin()
void QLayoutPrivate::getMargin (int * result, int userMargin, QStyle::PixelMetric pm) const
Definition at line 168 of file qlayout.cpp.
 {
     if (!result)
         return;
     Q_Q(const QLayout);
     if (userMargin >= 0) {
         *result = userMargin;
     } else if (!topLevel) {
         *result = 0;
     } else if (QWidget *pw = q->parentWidget()) {
         *result = pw->style()->pixelMetric(pm, 0, pw);
     } else {
         *result = 0;
     }
 }
reparentChildWidgets()
void QLayoutPrivate::reparentChildWidgets (QWidget * mw)
Definition at line 1005 of file qlayout.cpp.
 {
     Q_Q(QLayout);
     int n =  q->count();
 #ifndef QT_NO_MENUBAR
     if (menubar && menubar->parentWidget() != mw) {
         menubar->setParent(mw);
     }
 #endif
     bool mwVisible = mw && mw->isVisible();
     for (int i = 0; i < n; ++i) {
         QLayoutItem *item = q->itemAt(i);
         if (QWidget *w = item->widget()) {
             QWidget *pw = w->parentWidget();
 #ifdef QT_DEBUG
             if (pw && pw != mw && layoutDebug()) {
                 qWarning("QLayout::addChildLayout: widget %s \"%s\" in wrong parent; moved to correct parent",
                          w->metaObject()->className(), w->objectName().toLocal8Bit().data());
             }
 #endif
             bool needShow = mwVisible && !(w->isHidden() && w->testAttribute(Qt::WA_WState_ExplicitShowHide));
             if (pw != mw)
                 w->setParent(mw);
             if (needShow)
                 QMetaObject::invokeMethod(w, "_q_showIfNotHidden", Qt::QueuedConnection); //show later
         } else if (QLayout *l = item->layout()) {
             l->d_func()->reparentChildWidgets(mw);
         }
     }
 }
Properties
activated
uint QLayoutPrivate::activated
Definition at line 92 of file qlayout_p.h.
autoNewChild
uint QLayoutPrivate::autoNewChild
Definition at line 93 of file qlayout_p.h.
constraint
QLayout::SizeConstraint QLayoutPrivate::constraint
Definition at line 94 of file qlayout_p.h.
Referenced by QLayout::setSizeConstraint().
enabled
uint QLayoutPrivate::enabled
Definition at line 91 of file qlayout_p.h.
insideSpacing
int QLayoutPrivate::insideSpacing
Definition at line 85 of file qlayout_p.h.
menubar
QWidget* QLayoutPrivate::menubar
Definition at line 96 of file qlayout_p.h.
Referenced by doResize(), and reparentChildWidgets().
rect
QRect QLayoutPrivate::rect
Definition at line 95 of file qlayout_p.h.
Referenced by doResize().
spacerItemFactoryMethod
QLayoutPrivate::QSpacerItemFactoryMethod QLayoutPrivate::spacerItemFactoryMethod = 0 static
Definition at line 83 of file qlayout_p.h.
Referenced by createSpacerItem(), and getMargin().
topLevel
uint QLayoutPrivate::topLevel
Definition at line 90 of file qlayout_p.h.
Referenced by getMargin().
userBottomMargin
int QLayoutPrivate::userBottomMargin
Definition at line 89 of file qlayout_p.h.
userLeftMargin
int QLayoutPrivate::userLeftMargin
Definition at line 86 of file qlayout_p.h.
userRightMargin
int QLayoutPrivate::userRightMargin
Definition at line 88 of file qlayout_p.h.
userTopMargin
int QLayoutPrivate::userTopMargin
Definition at line 87 of file qlayout_p.h.
widgetItemFactoryMethod
QLayoutPrivate::QWidgetItemFactoryMethod QLayoutPrivate::widgetItemFactoryMethod = 0 static
Definition at line 82 of file qlayout_p.h.
Referenced by createWidgetItem(), and getMargin().
The documentation for this class was generated from the following files:
/src/gui/kernel/qlayout_p.h
/src/gui/kernel/qlayout.cpp