Qt 4.8: QItemDelegatePrivate Class Reference
QItemDelegatePrivate Class Reference
Classes
struct Icon
Public Functions
void _q_commitDataAndCloseEditor (QWidget *editor)
QSizeF doTextLayout (int lineWidth) const
const QItemEditorFactory * editorFactory () const
QIcon::Mode iconMode (QStyle::State state) const
QIcon::State iconState (QStyle::State state) const
QItemDelegatePrivate ()
QRect textLayoutBounds (const QStyleOptionViewItemV2 &options) const
const QWidget * widget (const QStyleOptionViewItem &option) const
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QString replaceNewLine (QString text)
static QString valueToText (const QVariant &value, const QStyleOptionViewItemV4 &option)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool clipPainting
QItemEditorFactory * f
QTextLayout textLayout
QTextOption textOption
struct QItemDelegatePrivate::Icon tmp
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 82 of file qitemdelegate.cpp.
Constructors and Destructors
QItemDelegatePrivate()
QItemDelegatePrivate::QItemDelegatePrivate () inline
Definition at line 87 of file qitemdelegate.cpp.
 : f(0), clipPainting(true) {}
Functions
_q_commitDataAndCloseEditor()
void QItemDelegatePrivate::_q_commitDataAndCloseEditor (QWidget * editor)
Definition at line 139 of file qitemdelegate.cpp.
Referenced by replaceNewLine().
 {
     Q_Q(QItemDelegate);
     emit q->commitData(editor);
     emit q->closeEditor(editor, QAbstractItemDelegate::SubmitModelCache);
 }
doTextLayout()
QSizeF QItemDelegatePrivate::doTextLayout (int lineWidth) const
Definition at line 164 of file qitemdelegate.cpp.
 {
     qreal height = 0;
     qreal widthUsed = 0;
     textLayout.beginLayout();
     while (true) {
         QTextLine line = textLayout.createLine();
         if (!line.isValid())
             break;
         line.setLineWidth(lineWidth);
         line.setPosition(QPointF(0, height));
         height += line.height();
         widthUsed = qMax(widthUsed, line.naturalTextWidth());
     }
     textLayout.endLayout();
     return QSizeF(widthUsed, height);
 }
editorFactory()
const QItemEditorFactory* QItemDelegatePrivate::editorFactory () const inline
Definition at line 89 of file qitemdelegate.cpp.
         { return f ? f : QItemEditorFactory::defaultFactory(); }
iconMode()
QIcon::Mode QItemDelegatePrivate::iconMode (QStyle::State state) const inline
Definition at line 92 of file qitemdelegate.cpp.
         {
             if (!(state & QStyle::State_Enabled)) return QIcon::Disabled;
             if (state & QStyle::State_Selected) return QIcon::Selected;
             return QIcon::Normal;
         }
iconState()
QIcon::State QItemDelegatePrivate::iconState (QStyle::State state) const inline
Definition at line 99 of file qitemdelegate.cpp.
         { return state & QStyle::State_Open ? QIcon::On : QIcon::Off; }
replaceNewLine()
static QString QItemDelegatePrivate::replaceNewLine (QString text) inline static
Definition at line 102 of file qitemdelegate.cpp.
Referenced by QItemDelegate::drawDisplay(), QItemDelegate::textRectangle(), and QItemDelegate::updateEditorGeometry().
         {
             const QChar nl = QLatin1Char('\n');
             for (int i = 0; i < text.count(); ++i)
                 if (text.at(i) == nl)
                     text[i] = QChar::LineSeparator;
             return text;
         }
textLayoutBounds()
QRect QItemDelegatePrivate::textLayoutBounds (const QStyleOptionViewItemV2 & options) const
Definition at line 146 of file qitemdelegate.cpp.
 {
     QRect rect = option.rect;
     const bool wrapText = option.features & QStyleOptionViewItemV2::WrapText;
     switch (option.decorationPosition) {
     case QStyleOptionViewItem::Left:
     case QStyleOptionViewItem::Right:
         rect.setWidth(wrapText && rect.isValid() ? rect.width() : (QFIXED_MAX));
         break;
     case QStyleOptionViewItem::Top:
     case QStyleOptionViewItem::Bottom:
         rect.setWidth(wrapText ? option.decorationSize.width() : (QFIXED_MAX));
         break;
     }
     return rect;
 }
valueToText()
QString QItemDelegatePrivate::valueToText (const QVariant & value, const QStyleOptionViewItemV4 & option) static
Definition at line 358 of file qitemdelegate.cpp.
Referenced by QItemDelegate::paint(), QItemDelegate::rect(), and replaceNewLine().
 {
     QString text;
     switch (value.userType()) {
         case QMetaType::Float:
             text = option.locale.toString(value.toFloat(), 'g');
             break;
         case QVariant::Double:
             text = option.locale.toString(value.toDouble(), 'g', DBL_DIG);
             break;
         case QVariant::Int:
         case QVariant::LongLong:
             text = option.locale.toString(value.toLongLong());
             break;
         case QVariant::UInt:
         case QVariant::ULongLong:
             text = option.locale.toString(value.toULongLong());
             break;
         case QVariant::Date:
             text = option.locale.toString(value.toDate(), QLocale::ShortFormat);
             break;
         case QVariant::Time:
             text = option.locale.toString(value.toTime(), QLocale::ShortFormat);
             break;
         case QVariant::DateTime:
             text = option.locale.toString(value.toDateTime().date(), QLocale::ShortFormat);
             text += QLatin1Char(' ');
             text += option.locale.toString(value.toDateTime().time(), QLocale::ShortFormat);
             break;
         default:
             text = replaceNewLine(value.toString());
             break;
     }
     return text;
 }
widget()
const QWidget* QItemDelegatePrivate::widget (const QStyleOptionViewItem & option) const inline
Definition at line 123 of file qitemdelegate.cpp.
     {
         if (const QStyleOptionViewItemV3 *v3 = qstyleoption_cast<const QStyleOptionViewItemV3 *>(&option))
             return v3->widget;
         return 0;
     }
Properties
clipPainting
bool QItemDelegatePrivate::clipPainting
Definition at line 116 of file qitemdelegate.cpp.
f
QItemEditorFactory* QItemDelegatePrivate::f
Definition at line 115 of file qitemdelegate.cpp.
Referenced by editorFactory().
textLayout
QTextLayout QItemDelegatePrivate::textLayout mutable
Definition at line 120 of file qitemdelegate.cpp.
Referenced by doTextLayout().
textOption
QTextOption QItemDelegatePrivate::textOption mutable
Definition at line 121 of file qitemdelegate.cpp.
tmp
struct QItemDelegatePrivate::Icon QItemDelegatePrivate::tmp
The documentation for this class was generated from the following file:
/src/gui/itemviews/qitemdelegate.cpp