Qt 4.8: QRasterPaintEnginePrivate Class Reference
QRasterPaintEnginePrivate Class Reference
#include <qpaintengine_raster_p.h>
Public Functions
QTransform brushMatrix () const
bool canUseFastImageBlending (QPainter::CompositionMode mode, const QImage &image) const
const QClipData * clip () const
void drawImage (const QPointF &pt, const QImage &img, SrcOverBlendFunc func, const QRect &clip, int alpha, const QRect &sr=QRect())
ProcessSpans getBrushFunc (const QRect &rect, const QSpanData *data) const
ProcessSpans getBrushFunc (const QRectF &rect, const QSpanData *data) const
ProcessSpans getPenFunc (const QRectF &rect, const QSpanData *data) const
void initializeRasterizer (QSpanData *data)
bool isUnclipped (const QRect &rect, int penWidth) const
bool isUnclipped (const QRectF &rect, int penWidth) const
bool isUnclipped_normalized (const QRect &rect) const
Returns true if the rectangle is completely within the current clip state of the paint engine.
void prepare (QCustomRasterPaintDevice *)
QRasterPaintEnginePrivate ()
void rasterize (QT_FT_Outline *outline, ProcessSpans callback, QSpanData *spanData, QRasterBuffer *rasterBuffer)
void rasterize (QT_FT_Outline *outline, ProcessSpans callback, void *userData, QRasterBuffer *rasterBuffer)
void rasterizeLine_dashed (QLineF line, qreal width, int *dashIndex, qreal *dashOffset, bool *inDash)
void recalculateFastImages ()
void systemStateChanged ()
void updateMatrixData (QSpanData *spanData, const QBrush &brush, const QTransform &brushMatrix)
Public Functions inherited from QPaintEngineExPrivate
bool hasClipOperations () const
QPaintEngineExPrivate ()
void replayClipOperations ()
~QPaintEngineExPrivate ()
Public Functions inherited from QPaintEnginePrivate
void drawBoxTextItem (const QPointF &p, const QTextItemInt &ti)
QPaintEnginePrivate ()
void setSystemTransform (const QTransform &xform)
void setSystemViewport (const QRegion &region)
void transformSystemClip ()
virtual ~QPaintEnginePrivate ()
Public Variables
QScopedPointer< QClipData > baseClip
QStroker basicStroker
QDataBuffer< QLineF > cachedLines
QScopedPointer< QDashStroker > dashStroker
QPaintDevice * device
int deviceDepth
QRect deviceRect
QRect deviceRectUnclipped
QFontEngineGlyphCache::Type glyphCacheType
QScopedPointer< QT_FT_Raster > grayRaster
HDC hdc
QSpanData image_filler
QSpanData image_filler_xform
uint isPlain45DegreeRotation: 1
uint mono_surface: 1
QScopedPointer< QOutlineMapper > outlineMapper
uint outlinemapper_xform_dirty: 1
QScopedPointer< QRasterBuffer > rasterBuffer
QScopedPointer< QRasterizer > rasterizer
QSpanData solid_color_filler
Public Variables inherited from QPaintEngineExPrivate
QStrokerOps * activeStroker
QDashStroker dasher
QRect exDeviceRect
StrokeHandler * strokeHandler
QStroker stroker
QPen strokerPen
Public Variables inherited from QPaintEnginePrivate
QWidget * currentClipWidget
uint hasSystemTransform: 1
uint hasSystemViewport: 1
QPaintDevice * pdev
QPaintEngine * q_ptr
QRegion systemClip
QRect systemRect
QTransform systemTransform
QRegion systemViewport
Detailed Description
Definition at line 298 of file qpaintengine_raster_p.h.
Constructors and Destructors
QRasterPaintEnginePrivate()
QRasterPaintEnginePrivate::QRasterPaintEnginePrivate ()
Definition at line 249 of file qpaintengine_raster.cpp.
                                                      :
     QPaintEngineExPrivate(),
     cachedLines(0)
 {
 }
Functions
brushMatrix()
QTransform QRasterPaintEnginePrivate::brushMatrix () const inline
Definition at line 319 of file qpaintengine_raster_p.h.
{
         Q_Q(const QRasterPaintEngine);
         const QRasterPaintEngineState *s = q->state();
         QTransform m(s->matrix);
         m.translate(s->brushOrigin.x(), s->brushOrigin.y());
         return m;
     }
canUseFastImageBlending()
bool QRasterPaintEnginePrivate::canUseFastImageBlending (QPainter::CompositionMode mode, const QImage & image) const
Definition at line 3881 of file qpaintengine_raster.cpp.
Referenced by brushMatrix(), and QRasterPaintEngine::drawImage().
 {
     Q_Q(const QRasterPaintEngine);
     const QRasterPaintEngineState *s = q->state();
     return s->flags.fast_images
            && (mode == QPainter::CompositionMode_SourceOver
                || (mode == QPainter::CompositionMode_Source
                    && !image.hasAlphaChannel()));
 }
clip()
const QClipData * QRasterPaintEnginePrivate::clip () const inline
Definition at line 557 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::alphaPenBlt(), QRasterPaintEngine::clip(), QRasterPaintEngine::clipBoundingRect(), QRasterPaintEngine::clipType(), QRasterPaintEngine::drawImage(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::fillRect(), qrasterpaintengine_dirty_clip(), QDirectFBPaintEnginePrivate::updateClip(), and updateMatrixData().
{
     Q_Q(const QRasterPaintEngine);
     if (q->state() && q->state()->clip && q->state()->clip->enabled)
         return q->state()->clip;
     return baseClip.data();
 }
drawImage()
void QRasterPaintEnginePrivate::drawImage (const QPointF & pt, const QImage & img, SrcOverBlendFunc func, const QRect & clip, int alpha, const QRect & sr = QRect())
Definition at line 995 of file qpaintengine_raster.cpp.
Referenced by QRasterPaintEngine::drawImage().
 {
     if (alpha == 0 || !clip.isValid())
         return;
     Q_ASSERT(img.depth() >= 8);
     int srcBPL = img.bytesPerLine();
     const uchar *srcBits = img.bits();
     int srcSize = img.depth() >> 3; // This is the part that is incompatible with lower than 8-bit..
     int iw = img.width();
     int ih = img.height();
     if (!sr.isEmpty()) {
         iw = sr.width();
         ih = sr.height();
         // Adjust the image according to the source offset...
         srcBits += ((sr.y() * srcBPL) + sr.x() * srcSize);
     }
     // adapt the x parameters
     int x = qRound(pt.x());
     int cx1 = clip.x();
     int cx2 = clip.x() + clip.width();
     if (x < cx1) {
         int d = cx1 - x;
         srcBits += srcSize * d;
         iw -= d;
         x = cx1;
     }
     if (x + iw > cx2) {
         int d = x + iw - cx2;
         iw -= d;
     }
     if (iw <= 0)
         return;
     // adapt the y paremeters...
     int cy1 = clip.y();
     int cy2 = clip.y() + clip.height();
     int y = qRound(pt.y());
     if (y < cy1) {
         int d = cy1 - y;
         srcBits += srcBPL * d;
         ih -= d;
         y = cy1;
     }
     if (y + ih > cy2) {
         int d = y + ih - cy2;
         ih -= d;
     }
     if (ih <= 0)
         return;
     // call the blend function...
     int dstSize = rasterBuffer->bytesPerPixel();
     int dstBPL = rasterBuffer->bytesPerLine();
     func(rasterBuffer->buffer() + x * dstSize + y * dstBPL, dstBPL,
          srcBits, srcBPL,
          iw, ih,
          alpha);
 }
getBrushFunc() [1/2]
ProcessSpans QRasterPaintEnginePrivate::getBrushFunc (const QRect & rect, const QSpanData * data) const inline
Definition at line 3042 of file qpaintengine_raster.cpp.
Referenced by brushMatrix(), QRasterPaintEngine::drawEllipse(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), and QRasterPaintEngine::fillPolygon().
 {
     return isUnclipped(rect, 0) ? data->unclipped_blend : data->blend;
 }
getBrushFunc() [2/2]
ProcessSpans QRasterPaintEnginePrivate::getBrushFunc (const QRectF & rect, const QSpanData * data) const inline
Definition at line 3049 of file qpaintengine_raster.cpp.
 {
     return isUnclipped(rect, 0) ? data->unclipped_blend : data->blend;
 }
getPenFunc()
ProcessSpans QRasterPaintEnginePrivate::getPenFunc (const QRectF & rect, const QSpanData * data) const inline
Definition at line 3056 of file qpaintengine_raster.cpp.
Referenced by brushMatrix(), and QRasterPaintEngine::drawEllipse().
 {
     Q_Q(const QRasterPaintEngine);
     const QRasterPaintEngineState *s = q->state();
     if (!s->flags.fast_pen && s->matrix.type() > QTransform::TxTranslate)
         return data->blend;
     const int penWidth = s->flags.fast_pen ? 1 : qCeil(s->lastPen.widthF());
     return isUnclipped(rect, penWidth) ? data->unclipped_blend : data->blend;
 }
initializeRasterizer()
void QRasterPaintEnginePrivate::initializeRasterizer (QSpanData * data)
Definition at line 3722 of file qpaintengine_raster.cpp.
Referenced by brushMatrix(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawRects(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), QRasterPaintEngine::fillRect(), and QRasterPaintEngine::stroke().
 {
     Q_Q(QRasterPaintEngine);
     QRasterPaintEngineState *s = q->state();
     rasterizer->setAntialiased(s->flags.antialiased);
     QRect clipRect(deviceRect);
     ProcessSpans blend;
     // ### get from optimized rectbased QClipData
     const QClipData *c = clip();
     if (c) {
         const QRect r(QPoint(c->xmin, c->ymin),
                       QSize(c->xmax - c->xmin, c->ymax - c->ymin));
         clipRect = clipRect.intersected(r);
         blend = data->blend;
     } else {
         blend = data->unclipped_blend;
     }
     rasterizer->setClipRect(clipRect);
     rasterizer->initialize(blend, data);
 }
isUnclipped() [1/2]
bool QRasterPaintEnginePrivate::isUnclipped (const QRect & rect, int penWidth) const
Definition at line 2995 of file qpaintengine_raster.cpp.
Referenced by brushMatrix().
 {
     Q_Q(const QRasterPaintEngine);
     const QRasterPaintEngineState *s = q->state();
     const QClipData *cl = clip();
     if (!cl) {
         QRect r = rect.normalized();
         // inline contains() for performance (we know the rects are normalized)
         const QRect &r1 = deviceRect;
         return (r.left() >= r1.left() && r.right() <= r1.right()
                 && r.top() >= r1.top() && r.bottom() <= r1.bottom());
     }
     // currently all painting functions that call this function clip to deviceRect internally
     if (cl->hasRectClip && cl->clipRect == deviceRect)
         return true;
     if (s->flags.antialiased)
         ++penWidth;
     QRect r = rect.normalized();
     if (penWidth > 0) {
         r.setX(r.x() - penWidth);
         r.setY(r.y() - penWidth);
         r.setWidth(r.width() + 2 * penWidth);
         r.setHeight(r.height() + 2 * penWidth);
     }
     if (cl->hasRectClip) {
         // inline contains() for performance (we know the rects are normalized)
         const QRect &r1 = cl->clipRect;
         return (r.left() >= r1.left() && r.right() <= r1.right()
                 && r.top() >= r1.top() && r.bottom() <= r1.bottom());
     } else {
         return qt_region_strictContains(cl->clipRegion, r);
     }
 }
isUnclipped() [2/2]
bool QRasterPaintEnginePrivate::isUnclipped (const QRectF & rect, int penWidth) const inline
Definition at line 3035 of file qpaintengine_raster.cpp.
 {
     return isUnclipped(rect.normalized().toAlignedRect(), penWidth);
 }
isUnclipped_normalized()
bool QRasterPaintEnginePrivate::isUnclipped_normalized (const QRect & rect) const
Returns true if the rectangle is completely within the current clip state of the paint engine.
Definition at line 2970 of file qpaintengine_raster.cpp.
Referenced by QRasterPaintEngine::alphaPenBlt(), brushMatrix(), and fillRect_normalized().
 {
     const QClipData *cl = clip();
     if (!cl) {
         // inline contains() for performance (we know the rects are normalized)
         const QRect &r1 = deviceRect;
         return (r.left() >= r1.left() && r.right() <= r1.right()
                 && r.top() >= r1.top() && r.bottom() <= r1.bottom());
     }
     if (cl->hasRectClip) {
         // currently all painting functions clips to deviceRect internally
         if (cl->clipRect == deviceRect)
             return true;
         // inline contains() for performance (we know the rects are normalized)
         const QRect &r1 = cl->clipRect;
         return (r.left() >= r1.left() && r.right() <= r1.right()
                 && r.top() >= r1.top() && r.bottom() <= r1.bottom());
     } else {
         return qt_region_strictContains(cl->clipRegion, r);
     }
 }
prepare()
void QRasterPaintEnginePrivate::prepare (QCustomRasterPaintDevice * device)
Definition at line 989 of file qpaintengine_raster.cpp.
Referenced by brushMatrix(), and QDirectFBPaintEnginePrivate::lock().
 {
     rasterBuffer->prepare(device);
 }
rasterize() [1/2]
void QRasterPaintEnginePrivate::rasterize (QT_FT_Outline * outline, ProcessSpans callback, QSpanData * spanData, QRasterBuffer * rasterBuffer)
Definition at line 3747 of file qpaintengine_raster.cpp.
Referenced by QRasterPaintEngine::clip(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), and QRasterPaintEngine::fillPolygon().
 {
     if (!callback || !outline)
         return;
     Q_Q(QRasterPaintEngine);
     QRasterPaintEngineState *s = q->state();
     if (!s->flags.antialiased) {
         initializeRasterizer(spanData);
         const Qt::FillRule fillRule = outline->flags == QT_FT_OUTLINE_NONE
                                       ? Qt::WindingFill
                                       : Qt::OddEvenFill;
         rasterizer->rasterize(outline, fillRule);
         return;
     }
     rasterize(outline, callback, (void *)spanData, rasterBuffer);
 }
rasterize() [2/2]
void QRasterPaintEnginePrivate::rasterize (QT_FT_Outline * outline, ProcessSpans callback, void * userData, QRasterBuffer * rasterBuffer)
Definition at line 3780 of file qpaintengine_raster.cpp.
 {
     if (!callback || !outline)
         return;
     Q_Q(QRasterPaintEngine);
     QRasterPaintEngineState *s = q->state();
     if (!s->flags.antialiased) {
         rasterizer->setAntialiased(s->flags.antialiased);
         rasterizer->setClipRect(deviceRect);
         rasterizer->initialize(callback, userData);
         const Qt::FillRule fillRule = outline->flags == QT_FT_OUTLINE_NONE
                                       ? Qt::WindingFill
                                       : Qt::OddEvenFill;
         rasterizer->rasterize(outline, fillRule);
         return;
     }
     // Initial size for raster pool is MINIMUM_POOL_SIZE so as to
     // minimize memory reallocations. However if initial size for
     // raster pool is changed for lower value, reallocations will
     // occur normally.
     int rasterPoolSize = MINIMUM_POOL_SIZE;
     uchar rasterPoolOnStack[MINIMUM_POOL_SIZE + 0xf];
     uchar *rasterPoolBase = alignAddress(rasterPoolOnStack, 0xf);
     uchar *rasterPoolOnHeap = 0;
     qt_ft_grays_raster.raster_reset(*grayRaster.data(), rasterPoolBase, rasterPoolSize);
     void *data = userData;
     QT_FT_BBox clip_box = { deviceRect.x(),
                             deviceRect.y(),
                             deviceRect.x() + deviceRect.width(),
                             deviceRect.y() + deviceRect.height() };
     QT_FT_Raster_Params rasterParams;
     rasterParams.target = 0;
     rasterParams.source = outline;
     rasterParams.flags = QT_FT_RASTER_FLAG_CLIP;
     rasterParams.gray_spans = 0;
     rasterParams.black_spans = 0;
     rasterParams.bit_test = 0;
     rasterParams.bit_set = 0;
     rasterParams.user = data;
     rasterParams.clip_box = clip_box;
     bool done = false;
     int error;
     int rendered_spans = 0;
     while (!done) {
         rasterParams.flags |= (QT_FT_RASTER_FLAG_AA | QT_FT_RASTER_FLAG_DIRECT);
         rasterParams.gray_spans = callback;
         rasterParams.skip_spans = rendered_spans;
         error = qt_ft_grays_raster.raster_render(*grayRaster.data(), &rasterParams);
         // Out of memory, reallocate some more and try again...
         if (error == -6) { // ErrRaster_OutOfMemory from qgrayraster.c
             rasterPoolSize *= 2;
             if (rasterPoolSize > 1024 * 1024) {
                 qWarning("QPainter: Rasterization of primitive failed");
                 break;
             }
             rendered_spans += q_gray_rendered_spans(*grayRaster.data());
             free(rasterPoolOnHeap);
             rasterPoolOnHeap = (uchar *)malloc(rasterPoolSize + 0xf);
             Q_CHECK_PTR(rasterPoolOnHeap); // note: we just freed the old rasterPoolBase. I hope it's not fatal.
             rasterPoolBase = alignAddress(rasterPoolOnHeap, 0xf);
             qt_ft_grays_raster.raster_done(*grayRaster.data());
             qt_ft_grays_raster.raster_new(grayRaster.data());
             qt_ft_grays_raster.raster_reset(*grayRaster.data(), rasterPoolBase, rasterPoolSize);
         } else {
             done = true;
         }
     }
     free(rasterPoolOnHeap);
 }
rasterizeLine_dashed()
void QRasterPaintEnginePrivate::rasterizeLine_dashed (QLineF line, qreal width, int * dashIndex, qreal * dashOffset, bool * inDash)
Definition at line 3275 of file qpaintengine_raster.cpp.
Referenced by QRasterPaintEngine::stroke().
 {
     Q_Q(QRasterPaintEngine);
     QRasterPaintEngineState *s = q->state();
     const QPen &pen = s->lastPen;
     const bool squareCap = (pen.capStyle() == Qt::SquareCap);
     const QVector<qreal> pattern = pen.dashPattern();
     qreal patternLength = 0;
     for (int i = 0; i < pattern.size(); ++i)
         patternLength += pattern.at(i);
     if (patternLength <= 0)
         return;
     qreal length = line.length();
     Q_ASSERT(length > 0);
     while (length > 0) {
         const bool rasterize = *inDash;
         qreal dash = (pattern.at(*dashIndex) - *dashOffset) * width;
         QLineF l = line;
         if (dash >= length) {
             dash = length;
             *dashOffset += dash / width;
             length = 0;
         } else {
             *dashOffset = 0;
             *inDash = !(*inDash);
             if (++*dashIndex >= pattern.size())
                 *dashIndex = 0;
             length -= dash;
             l.setLength(dash);
             line.setP1(l.p2());
         }
         if (rasterize && dash > 0)
             rasterizer->rasterizeLine(l.p1(), l.p2(), width / dash, squareCap);
     }
 }
recalculateFastImages()
void QRasterPaintEnginePrivate::recalculateFastImages ()
Definition at line 3872 of file qpaintengine_raster.cpp.
Referenced by brushMatrix().
 {
     Q_Q(QRasterPaintEngine);
     QRasterPaintEngineState *s = q->state();
     s->flags.fast_images = !(s->renderHints & QPainter::SmoothPixmapTransform)
                            && s->matrix.type() <= QTransform::TxShear;
 }
systemStateChanged()
void QRasterPaintEnginePrivate::systemStateChanged () virtual
Reimplemented from QPaintEnginePrivate.
Reimplemented in QDirectFBPaintEnginePrivate.
Definition at line 1064 of file qpaintengine_raster.cpp.
Referenced by QDirectFBPaintEnginePrivate::systemStateChanged().
 {
     deviceRectUnclipped = QRect(0, 0,
             qMin(QT_RASTER_COORD_LIMIT, device->width()),
             qMin(QT_RASTER_COORD_LIMIT, device->height()));
     if (!systemClip.isEmpty()) {
         QRegion clippedDeviceRgn = systemClip & deviceRectUnclipped;
         deviceRect = clippedDeviceRgn.boundingRect();
         baseClip->setClipRegion(clippedDeviceRgn);
     } else {
         deviceRect = deviceRectUnclipped;
         baseClip->setClipRect(deviceRect);
     }
 #ifdef QT_DEBUG_DRAW
     qDebug() << "systemStateChanged" << this << "deviceRect" << deviceRect << deviceRectUnclipped << systemClip;
 #endif
     exDeviceRect = deviceRect;
     Q_Q(QRasterPaintEngine);
     q->state()->strokeFlags |= QPaintEngine::DirtyClipRegion;
     q->state()->fillFlags |= QPaintEngine::DirtyClipRegion;
     q->state()->pixmapFlags |= QPaintEngine::DirtyClipRegion;
 }
updateMatrixData()
void QRasterPaintEnginePrivate::updateMatrixData (QSpanData * spanData, const QBrush & brush, const QTransform & brushMatrix)
Definition at line 1090 of file qpaintengine_raster.cpp.
 {
     if (b.d->style == Qt::NoBrush || b.d->style == Qt::SolidPattern)
         return;
     Q_Q(QRasterPaintEngine);
     bool bilinear = q->state()->flags.bilinear;
     if (b.d->transform.type() > QTransform::TxNone) { // FALCON: optimize
         spanData->setupMatrix(b.transform() * m, bilinear);
     } else {
         if (m.type() <= QTransform::TxTranslate) {
             // specialize setupMatrix for translation matrices
             // to avoid needless matrix inversion
             spanData->m11 = 1;
             spanData->m12 = 0;
             spanData->m13 = 0;
             spanData->m21 = 0;
             spanData->m22 = 1;
             spanData->m23 = 0;
             spanData->m33 = 1;
             spanData->dx = -m.dx();
             spanData->dy = -m.dy();
             spanData->txop = m.type();
             spanData->bilinear = bilinear;
             spanData->fast_matrix = qAbs(m.dx()) < 1e4 && qAbs(m.dy()) < 1e4;
             spanData->adjustSpanMethods();
         } else {
             spanData->setupMatrix(m, bilinear);
         }
     }
 }
Properties
baseClip
QScopedPointer<QClipData> QRasterPaintEnginePrivate::baseClip
Definition at line 371 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::clip().
basicStroker
QStroker QRasterPaintEnginePrivate::basicStroker
Definition at line 358 of file qpaintengine_raster_p.h.
cachedLines
QDataBuffer<QLineF> QRasterPaintEnginePrivate::cachedLines
Definition at line 363 of file qpaintengine_raster_p.h.
dashStroker
QScopedPointer<QDashStroker> QRasterPaintEnginePrivate::dashStroker
Definition at line 359 of file qpaintengine_raster_p.h.
device
QPaintDevice* QRasterPaintEnginePrivate::device
Definition at line 345 of file qpaintengine_raster_p.h.
Referenced by rasterFallbacksMask().
deviceDepth
int QRasterPaintEnginePrivate::deviceDepth
Definition at line 373 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::alphaPenBlt().
deviceRect
QRect QRasterPaintEnginePrivate::deviceRect
Definition at line 355 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::clipBoundingRect(), QRasterPaintEngine::drawEllipse(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawLines(), QRasterPaintEngine::drawPoints(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::drawRects(), fillRect_normalized(), QRasterPaintEngine::setClipRectInDeviceCoords(), and QRasterPaintEngine::stroke().
deviceRectUnclipped
QRect QRasterPaintEnginePrivate::deviceRectUnclipped
Definition at line 356 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawLines(), QRasterPaintEngine::drawPoints(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::drawRects(), and QRasterPaintEngine::stroke().
glyphCacheType
QFontEngineGlyphCache::Type QRasterPaintEnginePrivate::glyphCacheType
Definition at line 369 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), and QRasterPaintEngine::drawTextItem().
grayRaster
QScopedPointer<QT_FT_Raster> QRasterPaintEnginePrivate::grayRaster
Definition at line 361 of file qpaintengine_raster_p.h.
hdc
HDC QRasterPaintEnginePrivate::hdc
Definition at line 350 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::getDC(), and QRasterPaintEngine::setDC().
image_filler
QSpanData QRasterPaintEnginePrivate::image_filler
Definition at line 364 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), and QRasterPaintEngine::drawTiledPixmap().
image_filler_xform
QSpanData QRasterPaintEnginePrivate::image_filler_xform
Definition at line 365 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), and QRasterPaintEngine::drawTiledPixmap().
isPlain45DegreeRotation
uint QRasterPaintEnginePrivate::isPlain45DegreeRotation
Definition at line 379 of file qpaintengine_raster_p.h.
mono_surface
uint QRasterPaintEnginePrivate::mono_surface
Definition at line 375 of file qpaintengine_raster_p.h.
outlineMapper
QScopedPointer<QOutlineMapper> QRasterPaintEnginePrivate::outlineMapper
Definition at line 346 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::clip(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), and QRasterPaintEngine::fillPolygon().
outlinemapper_xform_dirty
uint QRasterPaintEnginePrivate::outlinemapper_xform_dirty
Definition at line 376 of file qpaintengine_raster_p.h.
rasterBuffer
QScopedPointer<QRasterBuffer> QRasterPaintEnginePrivate::rasterBuffer
Definition at line 347 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::alphaPenBlt(), QRasterPaintEngine::clip(), QRasterPaintEngine::drawBitmap(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawPixmap(), QRasterPaintEngine::drawPolygon(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), QRasterPaintEngine::fillPolygon(), fillRect_normalized(), qrasterpaintengine_dirty_clip(), and QRasterPaintEngine::setClipRectInDeviceCoords().
rasterizer
QScopedPointer<QRasterizer> QRasterPaintEnginePrivate::rasterizer
Definition at line 382 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawRects(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), QRasterPaintEngine::fillRect(), and QRasterPaintEngine::stroke().
solid_color_filler
QSpanData QRasterPaintEnginePrivate::solid_color_filler
Definition at line 366 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), QRasterPaintEngine::fillRect(), and qrasterpaintengine_dirty_clip().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine_raster_p.h
/src/gui/painting/qpaintengine_raster.cpp