Qt 4.8: QAbstractDeclarativeData Class Reference
QAbstractDeclarativeData Class Reference
#include <qobject_p.h>
Static Public Variables
static void(* destroyed)(QAbstractDeclarativeData *, QObject *)
static void(* objectNameChanged)(QAbstractDeclarativeData *, QObject *)
static void(* parentChanged)(QAbstractDeclarativeData *, QObject *, QObject *)
Detailed Description
Definition at line 90 of file qobject_p.h.
Properties
destroyed
void(* QAbstractDeclarativeData::destroyed)(QAbstractDeclarativeData *, QObject *)=0 static
Definition at line 93 of file qobject_p.h.
Referenced by QDeclarativeData::init(), QGraphicsItem::~QGraphicsItem(), QObject::~QObject(), and QWidget::~QWidget().
objectNameChanged
void(* QAbstractDeclarativeData::objectNameChanged)(QAbstractDeclarativeData *, QObject *)=0 static
Definition at line 95 of file qobject_p.h.
Referenced by QDeclarativeData::init(), and QObject::setObjectName().
parentChanged
void(* QAbstractDeclarativeData::parentChanged)(QAbstractDeclarativeData *, QObject *, QObject *)=0 static
Definition at line 94 of file qobject_p.h.
Referenced by QDeclarativeData::init(), and QObjectPrivate::setParent_helper().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qobject_p.h
/src/corelib/kernel/qobject.cpp