Qt 4.8: QHttpNetworkConnection Class Reference
QHttpNetworkConnection Class Reference
#include <qhttpnetworkconnection_p.h>
Public Functions
QNetworkProxy cacheProxy () const
QHttpNetworkConnectionChannel * channels () const
QString hostName () const
void ignoreSslErrors (int channel=-1)
void ignoreSslErrors (const QList< QSslError > &errors, int channel=-1)
bool isSsl () const
quint16 port () const
QHttpNetworkConnection (const QString &hostName, quint16 port=80, bool encrypt=false, QObject *parent=0, QSharedPointer< QNetworkSession > networkSession=QSharedPointer< QNetworkSession >())
QHttpNetworkConnection (quint16 channelCount, const QString &hostName, quint16 port=80, bool encrypt=false, QObject *parent=0, QSharedPointer< QNetworkSession > networkSession=QSharedPointer< QNetworkSession >())
QHttpNetworkReply * sendRequest (const QHttpNetworkRequest &request)
void setCacheProxy (const QNetworkProxy &networkProxy)
void setSslConfiguration (const QSslConfiguration &config)
void setTransparentProxy (const QNetworkProxy &networkProxy)
QNetworkProxy transparentProxy () const
~QHttpNetworkConnection ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Friends
class QHttpNetworkConnectionChannel
class QHttpNetworkReply
class QHttpNetworkReplyPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 87 of file qhttpnetworkconnection_p.h.
Constructors and Destructors
QHttpNetworkConnection() [1/2]
QHttpNetworkConnection::QHttpNetworkConnection (const QString & hostName, quint16 port = 80, bool encrypt = false, QObject * parent = 0, QSharedPointer< QNetworkSession > networkSession = QSharedPointer<QNetworkSession>())
Definition at line 881 of file qhttpnetworkconnection.cpp.
Referenced by QHttpNetworkConnection().
     : QObject(*(new QHttpNetworkConnectionPrivate(hostName, port, encrypt)), parent)
 {
     Q_D(QHttpNetworkConnection);
     d->networkSession = networkSession;
     d->init();
 }
QHttpNetworkConnection() [2/2]
QHttpNetworkConnection::QHttpNetworkConnection (quint16 channelCount, const QString & hostName, quint16 port = 80, bool encrypt = false, QObject * parent = 0, QSharedPointer< QNetworkSession > networkSession = QSharedPointer<QNetworkSession>())
Definition at line 889 of file qhttpnetworkconnection.cpp.
      : QObject(*(new QHttpNetworkConnectionPrivate(connectionCount, hostName, port, encrypt)), parent)
 {
     Q_D(QHttpNetworkConnection);
     d->networkSession = networkSession;
     d->init();
 }
~QHttpNetworkConnection()
QHttpNetworkConnection::~QHttpNetworkConnection ()
Definition at line 912 of file qhttpnetworkconnection.cpp.
 {
 }
Functions
cacheProxy()
QNetworkProxy QHttpNetworkConnection::cacheProxy () const
Definition at line 959 of file qhttpnetworkconnection.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection().
 {
     Q_D(const QHttpNetworkConnection);
     return d->networkProxy;
 }
channels()
QHttpNetworkConnectionChannel * QHttpNetworkConnection::channels () const
Definition at line 940 of file qhttpnetworkconnection.cpp.
 {
     return d_func()->channels;
 }
hostName()
QString QHttpNetworkConnection::hostName () const
Definition at line 916 of file qhttpnetworkconnection.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection(), and QHttpNetworkConnection().
 {
     Q_D(const QHttpNetworkConnection);
     return d->hostName;
 }
ignoreSslErrors() [1/2]
void QHttpNetworkConnection::ignoreSslErrors (int channel = -1)
Definition at line 993 of file qhttpnetworkconnection.cpp.
Referenced by ignoreSslErrors().
 {
     Q_D(QHttpNetworkConnection);
     if (!d->encrypt)
         return;
     if (channel == -1) { // ignore for all channels
         for (int i = 0; i < d->channelCount; ++i) {
             static_cast<QSslSocket *>(d->channels[i].socket)->ignoreSslErrors();
             d->channels[i].ignoreAllSslErrors = true;
         }
     } else {
         static_cast<QSslSocket *>(d->channels[channel].socket)->ignoreSslErrors();
         d->channels[channel].ignoreAllSslErrors = true;
     }
 }
ignoreSslErrors() [2/2]
void QHttpNetworkConnection::ignoreSslErrors (const QList< QSslError > & errors, int channel = -1)
Definition at line 1011 of file qhttpnetworkconnection.cpp.
 {
     Q_D(QHttpNetworkConnection);
     if (!d->encrypt)
         return;
     if (channel == -1) { // ignore for all channels
         for (int i = 0; i < d->channelCount; ++i) {
             static_cast<QSslSocket *>(d->channels[i].socket)->ignoreSslErrors(errors);
             d->channels[i].ignoreSslErrorsList = errors;
         }
     } else {
         static_cast<QSslSocket *>(d->channels[channel].socket)->ignoreSslErrors(errors);
         d->channels[channel].ignoreSslErrorsList = errors;
     }
 }
isSsl()
bool QHttpNetworkConnection::isSsl () const
Definition at line 934 of file qhttpnetworkconnection.cpp.
 {
     Q_D(const QHttpNetworkConnection);
     return d->encrypt;
 }
port()
quint16 QHttpNetworkConnection::port () const
Definition at line 922 of file qhttpnetworkconnection.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection(), and QHttpNetworkConnection().
 {
     Q_D(const QHttpNetworkConnection);
     return d->port;
 }
sendRequest()
QHttpNetworkReply * QHttpNetworkConnection::sendRequest (const QHttpNetworkRequest & request)
Definition at line 928 of file qhttpnetworkconnection.cpp.
Referenced by QHttpThreadDelegate::startRequest().
 {
     Q_D(QHttpNetworkConnection);
     return d->queueRequest(request);
 }
setCacheProxy()
void QHttpNetworkConnection::setCacheProxy (const QNetworkProxy & networkProxy)
Definition at line 946 of file qhttpnetworkconnection.cpp.
Referenced by QHttpThreadDelegate::startRequest().
 {
     Q_D(QHttpNetworkConnection);
     d->networkProxy = networkProxy;
     // update the authenticator
     if (!d->networkProxy.user().isEmpty()) {
         for (int i = 0; i < d->channelCount; ++i) {
             d->channels[i].proxyAuthenticator.setUser(d->networkProxy.user());
             d->channels[i].proxyAuthenticator.setPassword(d->networkProxy.password());
         }
     }
 }
setSslConfiguration()
void QHttpNetworkConnection::setSslConfiguration (const QSslConfiguration & config)
Definition at line 982 of file qhttpnetworkconnection.cpp.
Referenced by QHttpThreadDelegate::startRequest().
 {
     Q_D(QHttpNetworkConnection);
     if (!d->encrypt)
         return;
     // set the config on all channels
     for (int i = 0; i < d->channelCount; ++i)
         static_cast<QSslSocket *>(d->channels[i].socket)->setSslConfiguration(config);
 }
setTransparentProxy()
void QHttpNetworkConnection::setTransparentProxy (const QNetworkProxy & networkProxy)
Definition at line 965 of file qhttpnetworkconnection.cpp.
Referenced by QHttpThreadDelegate::startRequest().
 {
     Q_D(QHttpNetworkConnection);
     for (int i = 0; i < d->channelCount; ++i)
         d->channels[i].socket->setProxy(networkProxy);
 }
transparentProxy()
QNetworkProxy QHttpNetworkConnection::transparentProxy () const
Definition at line 972 of file qhttpnetworkconnection.cpp.
Referenced by QHttpNetworkConnectionChannel::ensureConnection().
 {
     Q_D(const QHttpNetworkConnection);
     return d->channels[0].socket->proxy();
 }
Friends and Related Functions
QHttpNetworkConnectionChannel
friend class QHttpNetworkConnectionChannel friend
Definition at line 132 of file qhttpnetworkconnection_p.h.
QHttpNetworkReply
friend class QHttpNetworkReply friend
Definition at line 130 of file qhttpnetworkconnection_p.h.
QHttpNetworkReplyPrivate
friend class QHttpNetworkReplyPrivate friend
Definition at line 131 of file qhttpnetworkconnection_p.h.
The documentation for this class was generated from the following files:
/src/network/access/qhttpnetworkconnection_p.h
/src/network/access/qhttpnetworkconnection.cpp