Qt 4.8: QScriptBreakpointsModel Class Reference
QScriptBreakpointsModel Class Reference
#include <qscriptbreakpointsmodel_p.h>
Public Functions
void addBreakpoint (int id, const QScriptBreakpointData &data)
Adds a breakpoint to the model.
QScriptBreakpointData breakpointData (int id) const
QScriptBreakpointData breakpointDataAt (int row) const
Returns the data for the breakpoint at the given row.
int breakpointIdAt (int row) const
Returns the id of the breakpoint at the given row.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
void deleteBreakpoint (int id)
Deletes the breakpoint with the given id.
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation, int role=Qt::DisplayRole) const
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void modifyBreakpoint (int id, const QScriptBreakpointData &data)
Modify the data of breakpoint id.
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QScriptBreakpointsModel (QScriptDebuggerJobSchedulerInterface *jobScheduler, QScriptDebuggerCommandSchedulerInterface *commandScheduler, QObject *parent=0)
void removeBreakpoint (int id)
Remove the breakpoint identified by id from the model.
int resolveBreakpoint (qint64 scriptId, int lineNumber) const
Tries to find a breakpoint with the given scriptId and lineNumber.
int resolveBreakpoint (const QString &fileName, int lineNumber) const
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void setBreakpoint (const QScriptBreakpointData &data)
Sets a breakpoint defined by the given data.
void setBreakpointData (int id, const QScriptBreakpointData &data)
Sets the data associated with the breakpoint identified by id.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
~QScriptBreakpointsModel ()
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
virtual bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Returns true if parent has any children; otherwise returns false.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the model by column in the given order.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 66 of file qscriptbreakpointsmodel_p.h.
Constructors and Destructors
QScriptBreakpointsModel()
QScriptBreakpointsModel::QScriptBreakpointsModel (QScriptDebuggerJobSchedulerInterface * jobScheduler, QScriptDebuggerCommandSchedulerInterface * commandScheduler, QObject * parent = 0)
Definition at line 83 of file qscriptbreakpointsmodel.cpp.
     : QAbstractItemModel(*new QScriptBreakpointsModelPrivate, parent)
 {
     Q_D(QScriptBreakpointsModel);
     d->jobScheduler = jobScheduler;
     d->commandScheduler = commandScheduler;
 }
~QScriptBreakpointsModel()
QScriptBreakpointsModel::~QScriptBreakpointsModel ()
Definition at line 94 of file qscriptbreakpointsmodel.cpp.
 {
 }
Functions
addBreakpoint()
void QScriptBreakpointsModel::addBreakpoint (int id, const QScriptBreakpointData & data)
Adds a breakpoint to the model.
This function does not actually set a breakpoint (i.e. it doesn't communicate with the debugger).
Definition at line 225 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerPrivate::handleResponse().
 {
     Q_D(QScriptBreakpointsModel);
     int rowIndex = d->breakpoints.size();
     beginInsertRows(QModelIndex(), rowIndex, rowIndex);
     d->breakpoints.append(qMakePair(id, data));
     endInsertRows();
 }
breakpointData()
QScriptBreakpointData QScriptBreakpointsModel::breakpointData (int id) const
Definition at line 285 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), and QScriptDebuggerPrivate::debuggerEvent().
 {
     Q_D(const QScriptBreakpointsModel);
     for (int i = 0; i < d->breakpoints.size(); ++i) {
         if (d->breakpoints.at(i).first == id)
             return d->breakpoints.at(i).second;
     }
     return QScriptBreakpointData();
 }
breakpointDataAt()
QScriptBreakpointData QScriptBreakpointsModel::breakpointDataAt (int row) const
Returns the data for the breakpoint at the given row.
Definition at line 279 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsAboutToBeRemoved(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), and QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsInserted().
 {
     Q_D(const QScriptBreakpointsModel);
     return d->breakpoints.at(row).second;
 }
breakpointIdAt()
int QScriptBreakpointsModel::breakpointIdAt (int row) const
Returns the id of the breakpoint at the given row.
Definition at line 270 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptBreakpointsWidget::keyPressEvent().
 {
     Q_D(const QScriptBreakpointsModel);
     return d->breakpoints.at(row).first;
 }
columnCount()
int QScriptBreakpointsModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 350 of file qscriptbreakpointsmodel.cpp.
Referenced by index(), and modifyBreakpoint().
 {
     if (!parent.isValid())
         return 6;
     return 0;
 }
data()
QVariant QScriptBreakpointsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 371 of file qscriptbreakpointsmodel.cpp.
Referenced by setBreakpoint(), and ~QScriptBreakpointsModel().
 {
     Q_D(const QScriptBreakpointsModel);
     if (!index.isValid() || (index.row() >= d->breakpoints.size()))
         return QVariant();
     const QPair<int, QScriptBreakpointData> &item = d->breakpoints.at(index.row());
     if (role == Qt::DisplayRole) {
         if (index.column() == 0)
             return item.first;
         else if (index.column() == 1) {
             QString loc = item.second.fileName();
             if (loc.isEmpty())
                 loc = QString::fromLatin1("<anonymous script, id=%0>").arg(item.second.scriptId());
             loc.append(QString::fromLatin1(":%0").arg(item.second.lineNumber()));
             return loc;
         } else if (index.column() == 2) {
             if (!item.second.condition().isEmpty())
                 return item.second.condition();
         } else if (index.column() == 3) {
             if (item.second.ignoreCount() != 0)
                 return item.second.ignoreCount();
         } else if (index.column() == 5) {
             return item.second.hitCount();
         }
     } else if (role == Qt::CheckStateRole) {
         if (index.column() == 0) {
             return item.second.isEnabled() ? Qt::Checked : Qt::Unchecked;
         } else if (index.column() == 4) {
             return item.second.isSingleShot() ? Qt::Checked : Qt::Unchecked;
         }
     } else if (role == Qt::EditRole) {
         if (index.column() == 2)
             return item.second.condition();
         else if (index.column() == 3)
             return item.second.ignoreCount();
     }
     return QVariant();
 }
deleteBreakpoint()
void QScriptBreakpointsModel::deleteBreakpoint (int id)
Deletes the breakpoint with the given id.
The corresponding row in the model will be removed if the breakpoint was successfully deleted.
Definition at line 214 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), QScriptDebuggerPrivate::_q_toggleBreakpoint(), and QScriptBreakpointsWidget::keyPressEvent().
 {
     Q_D(QScriptBreakpointsModel);
     QScriptDebuggerJob *job = new DeleteBreakpointJob(id, d->commandScheduler);
     d->jobScheduler->scheduleJob(job);
 }
flags()
Qt::ItemFlags QScriptBreakpointsModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 474 of file qscriptbreakpointsmodel.cpp.
 {
     if (!index.isValid())
         return 0;
     Qt::ItemFlags ret = Qt::ItemIsEnabled | Qt::ItemIsSelectable;
     switch (index.column()) {
     case 0:
         ret |= Qt::ItemIsUserCheckable;
         break;
     case 1:
         break;
     case 2:
         ret |= Qt::ItemIsEditable;
         break;
     case 3:
         ret |= Qt::ItemIsEditable;
         break;
     case 4:
         ret |= Qt::ItemIsUserCheckable;
         break;
     }
     return ret;
 }
headerData()
QVariant QScriptBreakpointsModel::headerData (int section, Qt::Orientation orient, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 450 of file qscriptbreakpointsmodel.cpp.
 {
     if (orient == Qt::Horizontal) {
         if (role == Qt::DisplayRole) {
             if (section == 0)
                 return QCoreApplication::translate("QScriptBreakpointsModel", "ID");
             else if (section == 1)
                 return QCoreApplication::translate("QScriptBreakpointsModel", "Location");
             else if (section == 2)
                 return QCoreApplication::translate("QScriptBreakpointsModel", "Condition");
             else if (section == 3)
                 return QCoreApplication::translate("QScriptBreakpointsModel", "Ignore-count");
             else if (section == 4)
                 return QCoreApplication::translate("QScriptBreakpointsModel", "Single-shot");
             else if (section == 5)
                 return QCoreApplication::translate("QScriptBreakpointsModel", "Hit-count");
         }
     }
     return QVariant();
 }
index()
QModelIndex QScriptBreakpointsModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 327 of file qscriptbreakpointsmodel.cpp.
 {
     Q_D(const QScriptBreakpointsModel);
     if (parent.isValid())
         return QModelIndex();
     if ((row < 0) || (row >= d->breakpoints.size()))
         return QModelIndex();
     if ((column < 0) || (column >= columnCount()))
         return QModelIndex();
     return createIndex(row, column);
 }
modifyBreakpoint()
void QScriptBreakpointsModel::modifyBreakpoint (int id, const QScriptBreakpointData & data)
Modify the data of breakpoint id.
Definition at line 237 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerPrivate::handleResponse().
 {
     Q_D(QScriptBreakpointsModel);
     for (int i = 0; i < d->breakpoints.size(); ++i) {
         if (d->breakpoints.at(i).first == id) {
             d->breakpoints[i] = qMakePair(id, data);
             emit dataChanged(createIndex(i, 0), createIndex(i, columnCount()-1));
             break;
         }
     }
 }
parent()
QModelIndex QScriptBreakpointsModel::parent (const QModelIndex & child) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 342 of file qscriptbreakpointsmodel.cpp.
 {
     return QModelIndex();
 }
removeBreakpoint()
void QScriptBreakpointsModel::removeBreakpoint (int id)
Remove the breakpoint identified by id from the model.
This function does not delete the breakpoint (i.e. it doesn't communicate with the debugger).
Definition at line 254 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerPrivate::debuggerEvent(), and QScriptDebuggerPrivate::handleResponse().
 {
     Q_D(QScriptBreakpointsModel);
     for (int i = 0; i < d->breakpoints.size(); ++i) {
         if (d->breakpoints.at(i).first == id) {
             beginRemoveRows(QModelIndex(), i, i);
             d->breakpoints.removeAt(i);
             endRemoveRows();
             break;
         }
     }
 }
resolveBreakpoint() [1/2]
int QScriptBreakpointsModel::resolveBreakpoint (qint64 scriptId, int lineNumber) const
Tries to find a breakpoint with the given scriptId and lineNumber.
Returns the id of the first breakpoint that matches, or -1 if no such breakpoint is found.
Definition at line 300 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), and QScriptDebuggerPrivate::_q_toggleBreakpoint().
 {
     Q_D(const QScriptBreakpointsModel);
     for (int i = 0; i < d->breakpoints.size(); ++i) {
         if ((d->breakpoints.at(i).second.scriptId() == scriptId)
             && (d->breakpoints.at(i).second.lineNumber() == lineNumber)) {
             return d->breakpoints.at(i).first;
         }
     }
     return -1;
 }
resolveBreakpoint() [2/2]
int QScriptBreakpointsModel::resolveBreakpoint (const QString & fileName, int lineNumber) const
Definition at line 312 of file qscriptbreakpointsmodel.cpp.
 {
     Q_D(const QScriptBreakpointsModel);
     for (int i = 0; i < d->breakpoints.size(); ++i) {
         if ((d->breakpoints.at(i).second.fileName() == fileName)
             && (d->breakpoints.at(i).second.lineNumber() == lineNumber)) {
             return d->breakpoints.at(i).first;
         }
     }
     return -1;
 }
rowCount()
int QScriptBreakpointsModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 360 of file qscriptbreakpointsmodel.cpp.
 {
     Q_D(const QScriptBreakpointsModel);
     if (!parent.isValid())
         return d->breakpoints.size();
     return 0;
 }
setBreakpoint()
void QScriptBreakpointsModel::setBreakpoint (const QScriptBreakpointData & data)
Sets a breakpoint defined by the given data.
A new row will be inserted into the model if the breakpoint could be successfully set.
Definition at line 132 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), and QScriptDebuggerPrivate::_q_toggleBreakpoint().
 {
     Q_D(QScriptBreakpointsModel);
     QScriptDebuggerJob *job = new SetBreakpointJob(data, d->commandScheduler);
     d->jobScheduler->scheduleJob(job);
 }
setBreakpointData()
void QScriptBreakpointsModel::setBreakpointData (int id, const QScriptBreakpointData & data)
Sets the data associated with the breakpoint identified by id.
A dataChanged() signal will be emitted if the breakpoint data could be successfully changed.
Definition at line 174 of file qscriptbreakpointsmodel.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest().
 {
     Q_D(QScriptBreakpointsModel);
     QScriptDebuggerJob *job = new SetBreakpointDataJob(id, data, d->commandScheduler);
     d->jobScheduler->scheduleJob(job);
 }
setData()
bool QScriptBreakpointsModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 413 of file qscriptbreakpointsmodel.cpp.
 {
     Q_D(QScriptBreakpointsModel);
     if (!index.isValid() || (index.row() >= d->breakpoints.size()))
         return false;
     const QPair<int, QScriptBreakpointData> &item = d->breakpoints.at(index.row());
     QScriptBreakpointData modifiedData;
     int col = index.column();
     if ((col == 0) || (col == 4)) {
         if (role == Qt::CheckStateRole) {
             modifiedData = item.second;
             if (col == 0)
                 modifiedData.setEnabled(value.toInt() == Qt::Checked);
             else
                 modifiedData.setSingleShot(value.toInt() == Qt::Checked);
         }
     } else if (col == 2) {
         if (role == Qt::EditRole) {
             modifiedData = item.second;
             modifiedData.setCondition(value.toString());
         }
     } else if (col == 3) {
         if (role == Qt::EditRole) {
             modifiedData = item.second;
             modifiedData.setIgnoreCount(value.toInt());
         }
     }
     if (!modifiedData.isValid())
         return false;
     QScriptDebuggerJob *job = new SetBreakpointDataJob(item.first, modifiedData, d->commandScheduler);
     d->jobScheduler->scheduleJob(job);
     return true;
 }
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptbreakpointsmodel_p.h
/src/scripttools/debugging/qscriptbreakpointsmodel.cpp