Qt 4.8: QDomNodePrivate Class Reference
QDomNodePrivate Class Reference
Public Functions
virtual QDomNodePrivate * appendChild (QDomNodePrivate *newChild)
virtual void clear ()
virtual QDomNodePrivate * cloneNode (bool deep=true)
virtual QDomNodePrivate * insertAfter (QDomNodePrivate *newChild, QDomNodePrivate *refChild)
virtual QDomNodePrivate * insertBefore (QDomNodePrivate *newChild, QDomNodePrivate *refChild)
virtual bool isAttr () const
virtual bool isCDATASection () const
virtual bool isCharacterData () const
virtual bool isComment () const
virtual bool isDocument () const
virtual bool isDocumentFragment () const
virtual bool isDocumentType () const
virtual bool isElement () const
virtual bool isEntity () const
virtual bool isEntityReference () const
virtual bool isNotation () const
virtual bool isProcessingInstruction () const
virtual bool isText () const
QDomNodePrivate * namedItem (const QString &name)
QString nodeName () const
virtual QDomNode::NodeType nodeType () const
QString nodeValue () const
virtual void normalize ()
QDomDocumentPrivate * ownerDocument ()
QDomNodePrivate * parent () const
QDomNodePrivate (QDomDocumentPrivate *, QDomNodePrivate *parent=0)
QDomNodePrivate (QDomNodePrivate *n, bool deep)
virtual QDomNodePrivate * removeChild (QDomNodePrivate *oldChild)
virtual QDomNodePrivate * replaceChild (QDomNodePrivate *newChild, QDomNodePrivate *oldChild)
virtual void save (QTextStream &, int, int) const
void setLocation (int lineNumber, int columnNumber)
virtual void setNodeValue (const QString &v)
void setNoParent ()
void setOwnerDocument (QDomDocumentPrivate *doc)
void setParent (QDomNodePrivate *p)
virtual ~QDomNodePrivate ()
Public Variables
int columnNumber
bool createdWithDom1Interface: 1
QDomNodePrivate * first
bool hasParent: 1
QDomNodePrivate * last
int lineNumber
QString name
QString namespaceURI
QDomNodePrivate * next
QDomNodePrivate * ownerNode
QString prefix
QDomNodePrivate * prev
QAtomicInt ref
QString value
Detailed Description
Definition at line 135 of file qdom.cpp.
Constructors and Destructors
QDomNodePrivate() [1/2]
QDomNodePrivate::QDomNodePrivate (QDomDocumentPrivate * doc, QDomNodePrivate * parent = 0)
Definition at line 1482 of file qdom.cpp.
 {
     ref = 1;
     if (par)
         setParent(par);
     else
         setOwnerDocument(doc);
     prev = 0;
     next = 0;
     first = 0;
     last = 0;
     createdWithDom1Interface = true;
     lineNumber = -1;
     columnNumber = -1;
 }
QDomNodePrivate() [2/2]
QDomNodePrivate::QDomNodePrivate (QDomNodePrivate * n, bool deep)
Definition at line 1498 of file qdom.cpp.
 {
     ref = 1;
     setOwnerDocument(n->ownerDocument());
     prev = 0;
     next = 0;
     first = 0;
     last = 0;
     name = n->name;
     value = n->value;
     prefix = n->prefix;
     namespaceURI = n->namespaceURI;
     createdWithDom1Interface = n->createdWithDom1Interface;
     lineNumber = -1;
     columnNumber = -1;
     if (!deep)
         return;
     for (QDomNodePrivate* x = n->first; x; x = x->next)
         appendChild(x->cloneNode(true));
 }
~QDomNodePrivate()
QDomNodePrivate::~QDomNodePrivate () virtual
Definition at line 1522 of file qdom.cpp.
 {
     QDomNodePrivate* p = first;
     QDomNodePrivate* n;
     while (p) {
         n = p->next;
         if (!p->ref.deref())
             delete p;
         else
             p->setNoParent();
         p = n;
     }
     first = 0;
     last = 0;
 }
Functions
appendChild()
QDomNodePrivate * QDomNodePrivate::appendChild (QDomNodePrivate * newChild) virtual
Reimplemented in QDomDocumentTypePrivate.
Definition at line 1887 of file qdom.cpp.
Referenced by QDomHandler::characters(), QDomHandler::comment(), QDomHandler::processingInstruction(), QDomNamedNodeMapPrivate::setNamedItem(), QDomNamedNodeMapPrivate::setNamedItemNS(), QDomAttrPrivate::setNodeValue(), QDomHandler::skippedEntity(), and QDomHandler::startElement().
 {
     // No reference manipulation needed. Done in insertAfter.
     return insertAfter(newChild, 0);
 }
clear()
void QDomNodePrivate::clear (void) virtual
Reimplemented in QDomDocumentPrivate.
Definition at line 1539 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), and QDomDocumentPrivate::setContent().
 {
     QDomNodePrivate* p = first;
     QDomNodePrivate* n;
     while (p) {
         n = p->next;
         if (!p->ref.deref())
             delete p;
         p = n;
     }
     first = 0;
     last = 0;
 }
cloneNode()
QDomNodePrivate * QDomNodePrivate::cloneNode (bool deep = true) virtual
Reimplemented in QDomDocumentPrivate, QDomProcessingInstructionPrivate, QDomEntityReferencePrivate, QDomEntityPrivate, QDomNotationPrivate, QDomCDATASectionPrivate, QDomCommentPrivate, QDomElementPrivate, QDomAttrPrivate, QDomTextPrivate, QDomCharacterDataPrivate, QDomDocumentFragmentPrivate, and QDomDocumentTypePrivate.
Definition at line 1905 of file qdom.cpp.
Referenced by QDomNamedNodeMapPrivate::clone().
 {
     QDomNodePrivate* p = new QDomNodePrivate(this, deep);
     // We are not interested in this node
     p->ref.deref();
     return p;
 }
insertAfter()
QDomNodePrivate * QDomNodePrivate::insertAfter (QDomNodePrivate * newChild, QDomNodePrivate * refChild) virtual
Reimplemented in QDomDocumentTypePrivate.
Definition at line 1661 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::insertAfter().
 {
     // Error check
     if (!newChild)
         return 0;
     // Error check
     if (newChild == refChild)
         return 0;
     // Error check
     if (refChild && refChild->parent() != this)
         return 0;
     // "mark lists as dirty"
     QDomDocumentPrivate *const doc = ownerDocument();
     if(doc)
         doc->nodeListTime++;
     // Special handling for inserting a fragment. We just insert
     // all elements of the fragment instead of the fragment itself.
     if (newChild->isDocumentFragment()) {
         // Fragment is empty ?
         if (newChild->first == 0)
             return newChild;
         // New parent
         QDomNodePrivate* n = newChild->first;
         while (n) {
             n->setParent(this);
             n = n->next;
         }
         // Insert at the end
         if (!refChild || refChild->next == 0) {
             if (last)
                 last->next = newChild->first;
             newChild->first->prev = last;
             if (!first)
                 first = newChild->first;
             last = newChild->last;
         } else { // Insert in the middle
             newChild->first->prev = refChild;
             newChild->last->next = refChild->next;
             refChild->next->prev = newChild->last;
             refChild->next = newChild->first;
         }
         // No need to increase the reference since QDomDocumentFragment
         // does not decrease the reference.
         // Remove the nodes from the fragment
         newChild->first = 0;
         newChild->last = 0;
         return newChild;
     }
     // Release new node from its current parent
     if (newChild->parent())
         newChild->parent()->removeChild(newChild);
     // No more errors can occur now, so we take
     // ownership of the node
     newChild->ref.ref();
     newChild->setParent(this);
     // Insert at the end
     if (!refChild) {
         if (last)
             last->next = newChild;
         newChild->prev = last;
         if (!first)
             first = newChild;
         last = newChild;
         return newChild;
     }
     if (refChild->next == 0) {
         if (last)
             last->next = newChild;
         newChild->prev = last;
         if (!first)
             first = newChild;
         last = newChild;
         return newChild;
     }
     newChild->prev = refChild;
     newChild->next = refChild->next;
     refChild->next->prev = newChild;
     refChild->next = newChild;
     return newChild;
 }
insertBefore()
QDomNodePrivate * QDomNodePrivate::insertBefore (QDomNodePrivate * newChild, QDomNodePrivate * refChild) virtual
Reimplemented in QDomDocumentTypePrivate.
Definition at line 1566 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::insertBefore().
 {
     // Error check
     if (!newChild)
         return 0;
     // Error check
     if (newChild == refChild)
         return 0;
     // Error check
     if (refChild && refChild->parent() != this)
         return 0;
     // "mark lists as dirty"
     QDomDocumentPrivate *const doc = ownerDocument();
     if(doc)
         doc->nodeListTime++;
     // Special handling for inserting a fragment. We just insert
     // all elements of the fragment instead of the fragment itself.
     if (newChild->isDocumentFragment()) {
         // Fragment is empty ?
         if (newChild->first == 0)
             return newChild;
         // New parent
         QDomNodePrivate* n = newChild->first;
         while (n)  {
             n->setParent(this);
             n = n->next;
         }
         // Insert at the beginning ?
         if (!refChild || refChild->prev == 0) {
             if (first)
                 first->prev = newChild->last;
             newChild->last->next = first;
             if (!last)
                 last = newChild->last;
             first = newChild->first;
         } else {
             // Insert in the middle
             newChild->last->next = refChild;
             newChild->first->prev = refChild->prev;
             refChild->prev->next = newChild->first;
             refChild->prev = newChild->last;
         }
         // No need to increase the reference since QDomDocumentFragment
         // does not decrease the reference.
         // Remove the nodes from the fragment
         newChild->first = 0;
         newChild->last = 0;
         return newChild;
     }
     // No more errors can occur now, so we take
     // ownership of the node.
     newChild->ref.ref();
     if (newChild->parent())
         newChild->parent()->removeChild(newChild);
     newChild->setParent(this);
     if (!refChild) {
         if (first)
             first->prev = newChild;
         newChild->next = first;
         if (!last)
             last = newChild;
         first = newChild;
         return newChild;
     }
     if (refChild->prev == 0) {
         if (first)
             first->prev = newChild;
         newChild->next = first;
         if (!last)
             last = newChild;
         first = newChild;
         return newChild;
     }
     newChild->next = refChild;
     newChild->prev = refChild->prev;
     refChild->prev->next = newChild;
     refChild->prev = newChild;
     return newChild;
 }
isAttr()
virtual bool QDomNodePrivate::isAttr () const inline virtual
Reimplemented in QDomAttrPrivate.
Definition at line 170 of file qdom.cpp.
Referenced by QDomNode::toAttr().
 { return false; }
isCDATASection()
virtual bool QDomNodePrivate::isCDATASection () const inline virtual
Reimplemented in QDomCDATASectionPrivate.
Definition at line 171 of file qdom.cpp.
Referenced by QDomElementPrivate::text(), and QDomNode::toCDATASection().
 { return false; }
isCharacterData()
virtual bool QDomNodePrivate::isCharacterData () const inline virtual
Reimplemented in QDomCharacterDataPrivate.
Definition at line 181 of file qdom.cpp.
Referenced by QDomNode::toCharacterData().
 { return false; }
isComment()
virtual bool QDomNodePrivate::isComment () const inline virtual
Reimplemented in QDomCommentPrivate.
Definition at line 182 of file qdom.cpp.
Referenced by QDomNode::toComment().
 { return false; }
isDocument()
virtual bool QDomNodePrivate::isDocument () const inline virtual
Reimplemented in QDomDocumentPrivate.
Definition at line 173 of file qdom.cpp.
Referenced by ownerDocument(), and QDomNode::toDocument().
 { return false; }
isDocumentFragment()
virtual bool QDomNodePrivate::isDocumentFragment () const inline virtual
Reimplemented in QDomDocumentFragmentPrivate.
Definition at line 172 of file qdom.cpp.
Referenced by insertAfter(), insertBefore(), replaceChild(), and QDomNode::toDocumentFragment().
 { return false; }
isDocumentType()
virtual bool QDomNodePrivate::isDocumentType () const inline virtual
Reimplemented in QDomDocumentTypePrivate.
Definition at line 174 of file qdom.cpp.
Referenced by QDomNode::toDocumentType().
 { return false; }
isElement()
virtual bool QDomNodePrivate::isElement () const inline virtual
Reimplemented in QDomElementPrivate.
Definition at line 175 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomDocumentPrivate::documentElement(), QDomAttr::ownerElement(), QDomElementPrivate::text(), and QDomNode::toElement().
 { return false; }
isEntity()
virtual bool QDomNodePrivate::isEntity () const inline virtual
Reimplemented in QDomEntityPrivate.
Definition at line 178 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::insertAfter(), QDomDocumentTypePrivate::insertBefore(), QDomDocumentTypePrivate::QDomDocumentTypePrivate(), QDomDocumentTypePrivate::removeChild(), QDomDocumentTypePrivate::replaceChild(), and QDomNode::toEntity().
 { return false; }
isEntityReference()
virtual bool QDomNodePrivate::isEntityReference () const inline virtual
Reimplemented in QDomEntityReferencePrivate.
Definition at line 176 of file qdom.cpp.
Referenced by QDomNode::toEntityReference().
 { return false; }
isNotation()
virtual bool QDomNodePrivate::isNotation () const inline virtual
Reimplemented in QDomNotationPrivate.
Definition at line 179 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::insertAfter(), QDomDocumentTypePrivate::insertBefore(), QDomDocumentTypePrivate::QDomDocumentTypePrivate(), QDomDocumentTypePrivate::removeChild(), QDomDocumentTypePrivate::replaceChild(), and QDomNode::toNotation().
 { return false; }
isProcessingInstruction()
virtual bool QDomNodePrivate::isProcessingInstruction () const inline virtual
Reimplemented in QDomProcessingInstructionPrivate.
Definition at line 180 of file qdom.cpp.
Referenced by QDomDocumentPrivate::saveDocument(), and QDomNode::toProcessingInstruction().
 { return false; }
isText()
virtual bool QDomNodePrivate::isText () const inline virtual
Reimplemented in QDomTextPrivate.
Definition at line 177 of file qdom.cpp.
Referenced by qNormalizeNode(), QDomElementPrivate::save(), QDomElementPrivate::text(), and QDomNode::toText().
 { return false; }
namedItem()
QDomNodePrivate * QDomNodePrivate::namedItem (const QString & name)
Definition at line 1554 of file qdom.cpp.
 {
     QDomNodePrivate* p = first;
     while (p) {
         if (p->nodeName() == n)
             return p;
         p = p->next;
     }
     return 0;
 }
nodeName()
QString QDomNodePrivate::nodeName () const inline
Definition at line 142 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomDocumentTypePrivate::insertAfter(), QDomDocumentTypePrivate::insertBefore(), QDomAttr::name(), namedItem(), QDomDocumentTypePrivate::QDomDocumentTypePrivate(), QDomElementPrivate::removeAttributeNode(), QDomDocumentTypePrivate::removeChild(), QDomNamedNodeMapPrivate::removeNamedItem(), QDomDocumentTypePrivate::replaceChild(), QDomDocumentPrivate::saveDocument(), QDomElementPrivate::setAttributeNode(), QDomNamedNodeMapPrivate::setNamedItem(), and QDomNamedNodeMapPrivate::setNamedItemNS().
 { return name; }
nodeType()
virtual QDomNode::NodeType QDomNodePrivate::nodeType () const inline virtual
Reimplemented in QDomDocumentPrivate, QDomProcessingInstructionPrivate, QDomEntityReferencePrivate, QDomEntityPrivate, QDomNotationPrivate, QDomCDATASectionPrivate, QDomCommentPrivate, QDomElementPrivate, QDomAttrPrivate, QDomTextPrivate, QDomCharacterDataPrivate, QDomDocumentFragmentPrivate, and QDomDocumentTypePrivate.
Definition at line 184 of file qdom.cpp.
Referenced by QDomDocumentPrivate::importNode().
 { return QDomNode::BaseNode; }
nodeValue()
QString QDomNodePrivate::nodeValue () const inline
Definition at line 143 of file qdom.cpp.
Referenced by QDomElementPrivate::attribute(), QDomElementPrivate::attributeNS(), QDomCharacterData::data(), qNormalizeNode(), QDomDocumentPrivate::saveDocument(), QDomElementPrivate::text(), and QDomAttr::value().
 { return value; }
normalize()
void QDomNodePrivate::normalize () virtual
Definition at line 1935 of file qdom.cpp.
 {
     // ### This one has moved from QDomElementPrivate to this position. It is
     // not tested.
     qNormalizeNode(this);
 }
ownerDocument()
QDomDocumentPrivate * QDomNodePrivate::ownerDocument ()
Definition at line 1893 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomNodeListPrivate::item(), QDomNodeListPrivate::length(), QDomNodePrivate(), QDomElementPrivate::setAttribute(), and QDomElementPrivate::setAttributeNS().
 {
     QDomNodePrivate* p = this;
     while (p && !p->isDocument()) {
         if (!p->hasParent)
             return (QDomDocumentPrivate*)p->ownerNode;
         p = p->parent();
     }
     return static_cast<QDomDocumentPrivate *>(p);
 }
parent()
QDomNodePrivate* QDomNodePrivate::parent () const inline
Definition at line 161 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomHandler::endElement(), insertAfter(), insertBefore(), ownerDocument(), QDomAttr::ownerElement(), removeChild(), and replaceChild().
 { return hasParent ? ownerNode : 0; }
removeChild()
QDomNodePrivate * QDomNodePrivate::removeChild (QDomNodePrivate * oldChild) virtual
Reimplemented in QDomDocumentTypePrivate.
Definition at line 1851 of file qdom.cpp.
Referenced by insertAfter(), insertBefore(), qNormalizeNode(), QDomDocumentTypePrivate::removeChild(), replaceChild(), and QDomAttrPrivate::setNodeValue().
 {
     // Error check
     if (oldChild->parent() != this)
         return 0;
     // "mark lists as dirty"
     QDomDocumentPrivate *const doc = ownerDocument();
     if(doc)
         doc->nodeListTime++;
     // Perhaps oldChild was just created with "createElement" or that. In this case
     // its parent is QDomDocument but it is not part of the documents child list.
     if (oldChild->next == 0 && oldChild->prev == 0 && first != oldChild)
         return 0;
     if (oldChild->next)
         oldChild->next->prev = oldChild->prev;
     if (oldChild->prev)
         oldChild->prev->next = oldChild->next;
     if (last == oldChild)
         last = oldChild->prev;
     if (first == oldChild)
         first = oldChild->next;
     oldChild->setNoParent();
     oldChild->next = 0;
     oldChild->prev = 0;
     // We are no longer interested in the old node
     oldChild->ref.deref();
     return oldChild;
 }
replaceChild()
QDomNodePrivate * QDomNodePrivate::replaceChild (QDomNodePrivate * newChild, QDomNodePrivate * oldChild) virtual
Reimplemented in QDomDocumentTypePrivate.
Definition at line 1757 of file qdom.cpp.
Referenced by QDomDocumentTypePrivate::replaceChild().
 {
     if (!newChild || !oldChild)
         return 0;
     if (oldChild->parent() != this)
         return 0;
     if (newChild == oldChild)
         return 0;
     // mark lists as dirty
     QDomDocumentPrivate *const doc = ownerDocument();
     if(doc)
         doc->nodeListTime++;
     // Special handling for inserting a fragment. We just insert
     // all elements of the fragment instead of the fragment itself.
     if (newChild->isDocumentFragment()) {
         // Fragment is empty ?
         if (newChild->first == 0)
             return newChild;
         // New parent
         QDomNodePrivate* n = newChild->first;
         while (n) {
             n->setParent(this);
             n = n->next;
         }
         if (oldChild->next)
             oldChild->next->prev = newChild->last;
         if (oldChild->prev)
             oldChild->prev->next = newChild->first;
         newChild->last->next = oldChild->next;
         newChild->first->prev = oldChild->prev;
         if (first == oldChild)
             first = newChild->first;
         if (last == oldChild)
             last = newChild->last;
         oldChild->setNoParent();
         oldChild->next = 0;
         oldChild->prev = 0;
         // No need to increase the reference since QDomDocumentFragment
         // does not decrease the reference.
         // Remove the nodes from the fragment
         newChild->first = 0;
         newChild->last = 0;
         // We are no longer interested in the old node
         if (oldChild)
             oldChild->ref.deref();
         return oldChild;
     }
     // No more errors can occur now, so we take
     // ownership of the node
     newChild->ref.ref();
     // Release new node from its current parent
     if (newChild->parent())
         newChild->parent()->removeChild(newChild);
     newChild->setParent(this);
     if (oldChild->next)
         oldChild->next->prev = newChild;
     if (oldChild->prev)
         oldChild->prev->next = newChild;
     newChild->next = oldChild->next;
     newChild->prev = oldChild->prev;
     if (first == oldChild)
         first = newChild;
     if (last == oldChild)
         last = newChild;
     oldChild->setNoParent();
     oldChild->next = 0;
     oldChild->prev = 0;
     // We are no longer interested in the old node
     if (oldChild)
         oldChild->ref.deref();
     return oldChild;
 }
save()
void QDomNodePrivate::save (QTextStream & s, int depth, int indent) const virtual
Warning
This function is not part of the public interface. depth is used for indentation, it seems.
Reimplemented in QDomProcessingInstructionPrivate, QDomEntityReferencePrivate, QDomEntityPrivate, QDomNotationPrivate, QDomCDATASectionPrivate, QDomCommentPrivate, QDomElementPrivate, QDomAttrPrivate, QDomTextPrivate, and QDomDocumentTypePrivate.
Definition at line 1945 of file qdom.cpp.
Referenced by save(), and QDomDocumentPrivate::saveDocument().
 {
     const QDomNodePrivate* n = first;
     while (n) {
         n->save(s, depth, indent);
         n = n->next;
     }
 }
setLocation()
void QDomNodePrivate::setLocation (int lineNumber, int columnNumber)
Definition at line 1954 of file qdom.cpp.
Referenced by QDomHandler::characters(), QDomHandler::comment(), QDomHandler::processingInstruction(), QDomHandler::skippedEntity(), and QDomHandler::startElement().
 {
     this->lineNumber = lineNumber;
     this->columnNumber = columnNumber;
 }
setNodeValue()
virtual void QDomNodePrivate::setNodeValue (const QString & v) inline virtual
Reimplemented in QDomAttrPrivate.
Definition at line 144 of file qdom.cpp.
Referenced by QDomElementPrivate::setAttribute(), QDomElementPrivate::setAttributeNS(), QDomCharacterData::setData(), and QDomAttr::setValue().
 { value = v; }
setNoParent()
void QDomNodePrivate::setNoParent () inline
Definition at line 164 of file qdom.cpp.
Referenced by removeChild(), replaceChild(), and ~QDomNodePrivate().
{
         ownerNode = hasParent ? (QDomNodePrivate*)ownerDocument() : 0;
         hasParent = false;
     }
setOwnerDocument()
void QDomNodePrivate::setOwnerDocument (QDomDocumentPrivate * doc) inline
Definition at line 1476 of file qdom.cpp.
Referenced by QDomDocumentPrivate::importNode().
 {
     ownerNode = doc;
     hasParent = false;
 }
setParent()
void QDomNodePrivate::setParent (QDomNodePrivate * p) inline
Definition at line 162 of file qdom.cpp.
Referenced by QDomNamedNodeMapPrivate::clone(), insertAfter(), insertBefore(), replaceChild(), and QDomElementPrivate::setAttributeNode().
 { ownerNode = p; hasParent = true; }
Properties
columnNumber
int QDomNodePrivate::columnNumber
Definition at line 206 of file qdom.cpp.
createdWithDom1Interface
bool QDomNodePrivate::createdWithDom1Interface
Definition at line 202 of file qdom.cpp.
Referenced by QDomAttrPrivate::QDomAttrPrivate(), QDomElementPrivate::QDomElementPrivate(), and QDomNodePrivate().
first
QDomNodePrivate* QDomNodePrivate::first
Definition at line 195 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomDocumentPrivate::documentElement(), insertAfter(), insertBefore(), QDomDocumentTypePrivate::QDomDocumentTypePrivate(), QDomNodePrivate(), qNormalizeNode(), replaceChild(), QDomElementPrivate::save(), QDomDocumentPrivate::saveDocument(), QDomAttrPrivate::setNodeValue(), and QDomElementPrivate::text().
hasParent
bool QDomNodePrivate::hasParent
Definition at line 203 of file qdom.cpp.
Referenced by ownerDocument().
last
QDomNodePrivate* QDomNodePrivate::last
Definition at line 196 of file qdom.cpp.
Referenced by insertAfter(), insertBefore(), replaceChild(), and QDomElementPrivate::save().
lineNumber
int QDomNodePrivate::lineNumber
Definition at line 205 of file qdom.cpp.
name
QString QDomNodePrivate::name
Definition at line 198 of file qdom.cpp.
Referenced by QDomImplementation::createDocumentType(), QDomNodeListPrivate::createList(), QDomNamedNodeMapPrivate::namedItemNS(), QDomNodePrivate(), QDomNamedNodeMap::removeNamedItemNS(), QDomDocumentTypePrivate::save(), QDomElementPrivate::save(), QDomElementPrivate::setAttributeNodeNS(), QDomNamedNodeMapPrivate::setNamedItemNS(), and QDomHandler::startDTD().
namespaceURI
QString QDomNodePrivate::namespaceURI
Definition at line 201 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomNamedNodeMapPrivate::namedItemNS(), QDomAttrPrivate::QDomAttrPrivate(), QDomElementPrivate::QDomElementPrivate(), QDomNodePrivate(), QDomAttrPrivate::save(), QDomElementPrivate::save(), QDomElementPrivate::setAttributeNodeNS(), and QDomNamedNodeMapPrivate::setNamedItemNS().
next
QDomNodePrivate* QDomNodePrivate::next
Definition at line 193 of file qdom.cpp.
Referenced by clear(), QDomNodeListPrivate::createList(), QDomDocumentPrivate::documentElement(), insertAfter(), insertBefore(), namedItem(), QDomDocumentTypePrivate::QDomDocumentTypePrivate(), QDomNodePrivate(), qNormalizeNode(), removeChild(), replaceChild(), save(), QDomDocumentPrivate::saveDocument(), QDomElementPrivate::text(), and ~QDomNodePrivate().
ownerNode
QDomNodePrivate* QDomNodePrivate::ownerNode
Definition at line 194 of file qdom.cpp.
Referenced by ownerDocument(), and QDomAttrPrivate::save().
prefix
QString QDomNodePrivate::prefix
Definition at line 200 of file qdom.cpp.
Referenced by QDomNamedNodeMapPrivate::namedItemNS(), QDomAttrPrivate::QDomAttrPrivate(), QDomElementPrivate::QDomElementPrivate(), QDomNodePrivate(), QDomAttrPrivate::save(), QDomElementPrivate::save(), QDomElementPrivate::setAttributeNodeNS(), QDomElementPrivate::setAttributeNS(), and QDomNamedNodeMapPrivate::setNamedItemNS().
prev
QDomNodePrivate* QDomNodePrivate::prev
Definition at line 192 of file qdom.cpp.
Referenced by insertAfter(), insertBefore(), removeChild(), replaceChild(), and QDomElementPrivate::save().
ref
QAtomicInt QDomNodePrivate::ref
Definition at line 191 of file qdom.cpp.
Referenced by QDomHandler::characters(), clear(), cloneNode(), QDomDocumentTypePrivate::cloneNode(), QDomDocumentFragmentPrivate::cloneNode(), QDomCharacterDataPrivate::cloneNode(), QDomAttrPrivate::cloneNode(), QDomElementPrivate::cloneNode(), QDomCDATASectionPrivate::cloneNode(), QDomNotationPrivate::cloneNode(), QDomDocumentPrivate::cloneNode(), QDomDocumentPrivate::createAttribute(), QDomDocumentPrivate::createAttributeNS(), QDomDocumentPrivate::createCDATASection(), QDomDocumentPrivate::createComment(), QDomDocumentPrivate::createDocumentFragment(), QDomImplementation::createDocumentType(), QDomDocumentPrivate::createElement(), QDomDocumentPrivate::createElementNS(), QDomDocumentPrivate::createEntityReference(), QDomDocumentPrivate::createProcessingInstruction(), QDomDocumentPrivate::createTextNode(), QDomDocumentPrivate::importNode(), insertAfter(), insertBefore(), QDomHandler::notationDecl(), QDomNode::operator=(), QDomNodeListPrivate::QDomNodeListPrivate(), QDomElementPrivate::removeAttribute(), removeChild(), QDomNamedNodeMapPrivate::removeNamedItem(), replaceChild(), QDomElementPrivate::setAttribute(), QDomElementPrivate::setAttributeNS(), QDomNamedNodeMapPrivate::setNamedItem(), QDomNamedNodeMapPrivate::setNamedItemNS(), QDomAttrPrivate::setNodeValue(), QDomHandler::unparsedEntityDecl(), and ~QDomNodePrivate().
value
QString QDomNodePrivate::value
Definition at line 199 of file qdom.cpp.
Referenced by QDomCharacterDataPrivate::appendData(), QDomHandler::characters(), QDomCharacterDataPrivate::dataLength(), QDomCharacterDataPrivate::deleteData(), QDomCharacterDataPrivate::insertData(), QDomCharacterDataPrivate::QDomCharacterDataPrivate(), QDomNodePrivate(), QDomCharacterDataPrivate::replaceData(), QDomAttrPrivate::save(), QDomAttrPrivate::setNodeValue(), and QDomCharacterDataPrivate::substringData().
The documentation for this class was generated from the following file:
/src/xml/dom/qdom.cpp