Qt 4.8: QNetworkSessionPrivate Class Reference
QNetworkSessionPrivate Class Reference abstract
#include <qnetworksession_p.h>
Signals
void closed ()
void error (QNetworkSession::SessionError error)
void newConfigurationActivated ()
void preferredConfigurationChanged (const QNetworkConfiguration &config, bool isSeamless)
void quitPendingWaitsForOpened ()
void stateChanged (QNetworkSession::State state)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void accept ()=0
virtual quint64 activeTime () const =0
virtual quint64 bytesReceived () const =0
virtual quint64 bytesWritten () const =0
virtual void close ()=0
virtual QNetworkInterface currentInterface () const =0
virtual QNetworkSession::SessionError error () const =0
virtual QString errorString () const =0
virtual void ignore ()=0
virtual void migrate ()=0
virtual void open ()=0
QNetworkSessionPrivate ()
virtual void reject ()=0
virtual QVariant sessionProperty (const QString &key) const =0
virtual void setALREnabled (bool)
virtual void setSessionProperty (const QString &key, const QVariant &value)=0
virtual void stop ()=0
virtual void syncStateWithInterface ()=0
virtual ~QNetworkSessionPrivate ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QNetworkConfigurationPrivatePointer privateConfiguration (const QNetworkConfiguration &config) const
void setPrivateConfiguration (QNetworkConfiguration &config, QNetworkConfigurationPrivatePointer ptr) const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables
QNetworkConfiguration activeConfig
bool isOpen
QMutex mutex
QNetworkConfiguration publicConfig
QNetworkSession * q
QNetworkConfiguration serviceConfig
QNetworkSession::State state
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Friends
class QNetworkSession
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 70 of file qnetworksession_p.h.
Constructors and Destructors
QNetworkSessionPrivate()
QNetworkSessionPrivate::QNetworkSessionPrivate () inline
Definition at line 77 of file qnetworksession_p.h.
                              : QObject(),
         state(QNetworkSession::Invalid), isOpen(false), mutex(QMutex::Recursive)
     {}
~QNetworkSessionPrivate()
virtual QNetworkSessionPrivate::~QNetworkSessionPrivate () inline virtual
Definition at line 80 of file qnetworksession_p.h.
     {}
Functions
accept()
virtual void QNetworkSessionPrivate::accept () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::accept().
activeTime()
virtual quint64 QNetworkSessionPrivate::activeTime () const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::activeTime().
bytesReceived()
virtual quint64 QNetworkSessionPrivate::bytesReceived () const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::bytesReceived().
bytesWritten()
virtual quint64 QNetworkSessionPrivate::bytesWritten () const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::bytesWritten().
close()
virtual void QNetworkSessionPrivate::close () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::close().
closed
void QNetworkSessionPrivate::closed () signal
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSessionPrivateImpl::finishStopBySendingClosedSignal(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::updateState(), and QNetworkSessionPrivateImpl::updateStateFromActiveConfig().
currentInterface()
virtual QNetworkInterface QNetworkSessionPrivate::currentInterface () const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::interface().
error() [1/2]
virtual QNetworkSession::SessionError QNetworkSessionPrivate::error () const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSessionPrivateImpl::connectionError(), QNetworkSessionPrivateImpl::connectTimeout(), QNetworkSession::error(), QNetworkSessionPrivateImpl::forcedSessionClose(), QNetworkSessionManagerPrivate::forceSessionClose(), QNetworkSessionPrivateImpl::open(), QNetworkSessionPrivateImpl::stateChange(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::updateState(), and QNetworkSessionPrivateImpl::updateStateFromActiveConfig().
error [2/2]
void QNetworkSessionPrivate::error (QNetworkSession::SessionError error) signal
errorString()
virtual QString QNetworkSessionPrivate::errorString () const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::errorString().
ignore()
virtual void QNetworkSessionPrivate::ignore () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::ignore().
migrate()
virtual void QNetworkSessionPrivate::migrate () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::migrate().
newConfigurationActivated
void QNetworkSessionPrivate::newConfigurationActivated () signal
Referenced by QNetworkSessionPrivateImpl::updateStateFromServiceNetwork().
open()
virtual void QNetworkSessionPrivate::open () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::open().
preferredConfigurationChanged
void QNetworkSessionPrivate::preferredConfigurationChanged (const QNetworkConfiguration & config, bool isSeamless) signal
privateConfiguration()
QNetworkConfigurationPrivatePointer QNetworkSessionPrivate::privateConfiguration (const QNetworkConfiguration & config) const inline protected
Definition at line 122 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::clearConfiguration(), QNetworkSessionPrivateImpl::copyConfig(), QNetworkSessionPrivateImpl::do_open(), QNetworkSessionPrivateImpl::getStatistics(), QNetworkSessionPrivateImpl::stateChange(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateIdentifier(), and QNetworkSessionPrivateImpl::updateState().
     {
         return config.d;
     }
quitPendingWaitsForOpened
void QNetworkSessionPrivate::quitPendingWaitsForOpened () signal
Referenced by QNetworkSessionPrivateImpl::do_open(), QNetworkSessionPrivateImpl::open(), QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::updateStateFromActiveConfig().
reject()
virtual void QNetworkSessionPrivate::reject () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::reject().
sessionProperty()
virtual QVariant QNetworkSessionPrivate::sessionProperty (const QString & key) const pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::sessionProperty().
setALREnabled()
virtual void QNetworkSessionPrivate::setALREnabled (bool) inline virtual
Definition at line 99 of file qnetworksession_p.h.
Referenced by QNetworkSession::connectNotify(), and QNetworkSession::disconnectNotify().
 {}
setPrivateConfiguration()
void QNetworkSessionPrivate::setPrivateConfiguration (QNetworkConfiguration & config, QNetworkConfigurationPrivatePointer ptr) const inline protected
Definition at line 127 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::copyConfig(), QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
     {
         config.d = ptr;
     }
setSessionProperty()
virtual void QNetworkSessionPrivate::setSessionProperty (const QString & key, const QVariant & value) pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::setSessionProperty().
stateChanged
void QNetworkSessionPrivate::stateChanged (QNetworkSession::State state) signal
Referenced by QNetworkSessionPrivateImpl::cleanupSession(), QNetworkSessionPrivateImpl::close(), QNetworkSessionPrivateImpl::do_open(), QNetworkSessionPrivateImpl::finishStopBySendingClosedSignal(), QNetworkSessionPrivateImpl::open(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateState(), QNetworkSessionPrivateImpl::updateStateFromActiveConfig(), and QNetworkSessionPrivateImpl::updateStateFromServiceNetwork().
stop()
virtual void QNetworkSessionPrivate::stop () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::stop().
syncStateWithInterface()
virtual void QNetworkSessionPrivate::syncStateWithInterface () pure virtual
Implemented in QNetworkSessionPrivateImpl, and QNetworkSessionPrivateImpl.
Referenced by QNetworkSession::QNetworkSession().
Friends and Related Functions
QNetworkSession
friend class QNetworkSession friend
Definition at line 74 of file qnetworksession_p.h.
Properties
activeConfig
QNetworkConfiguration QNetworkSessionPrivate::activeConfig protected
Definition at line 156 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSessionPrivateImpl::connectTimeout(), QNetworkSessionPrivateImpl::do_open(), QNetworkSessionPrivateImpl::finishStopBySendingClosedSignal(), QNetworkSessionPrivateImpl::getStatistics(), QNetworkSessionPrivateImpl::iapStateChanged(), QNetworkSessionPrivateImpl::open(), QNetworkSession::sessionProperty(), QNetworkSessionPrivateImpl::stateChange(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateIdentifier(), QNetworkSessionPrivateImpl::updateState(), QNetworkSessionPrivateImpl::updateStateFromActiveConfig(), and QNetworkSessionPrivateImpl::updateStateFromServiceNetwork().
isOpen
bool QNetworkSessionPrivate::isOpen protected
Definition at line 159 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSession::isOpen(), QNetworkSessionPrivateImpl::open(), QNetworkSession::sessionProperty(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateState(), QNetworkSessionPrivateImpl::updateStateFromActiveConfig(), and QNetworkSession::waitForOpened().
mutex
QMutex QNetworkSessionPrivate::mutex protected
Definition at line 161 of file qnetworksession_p.h.
Referenced by QNetworkSession::disconnectNotify().
publicConfig
QNetworkConfiguration QNetworkSessionPrivate::publicConfig protected
Definition at line 147 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSession::configuration(), QNetworkSessionPrivateImpl::connectTimeout(), QNetworkSessionPrivateImpl::currentInterface(), QNetworkSessionPrivateImpl::do_open(), QNetworkSessionPrivateImpl::iapStateChanged(), QNetworkSessionPrivateImpl::open(), QNetworkSession::QNetworkSession(), QNetworkSession::sessionProperty(), QNetworkSessionPrivateImpl::stateChange(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateIdentifier(), and QNetworkSessionPrivateImpl::updateState().
q
QNetworkSession* QNetworkSessionPrivate::q protected
Definition at line 144 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::cleanupSession(), QNetworkSessionPrivateImpl::errorString(), QNetworkSession::QNetworkSession(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
serviceConfig
QNetworkConfiguration QNetworkSessionPrivate::serviceConfig protected
Definition at line 152 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSessionPrivateImpl::networkConfigurationsChanged(), QNetworkSessionPrivateImpl::open(), QNetworkSession::sessionProperty(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::syncStateWithInterface(), and QNetworkSessionPrivateImpl::updateStateFromServiceNetwork().
state
QNetworkSession::State QNetworkSessionPrivate::state protected
Definition at line 158 of file qnetworksession_p.h.
Referenced by QNetworkSessionPrivateImpl::close(), QNetworkSessionPrivateImpl::currentInterface(), QNetworkSessionPrivateImpl::do_open(), QNetworkSessionPrivateImpl::finishStopBySendingClosedSignal(), QNetworkSessionPrivateImpl::open(), QNetworkSession::state(), QNetworkSessionPrivateImpl::stop(), QNetworkSessionPrivateImpl::syncStateWithInterface(), QNetworkSessionPrivateImpl::updateState(), QNetworkSessionPrivateImpl::updateStateFromActiveConfig(), QNetworkSessionPrivateImpl::updateStateFromServiceNetwork(), and QNetworkSession::waitForOpened().
The documentation for this class was generated from the following file:
/src/network/bearer/qnetworksession_p.h