Qt 4.8: QTcpServer Class Reference
QTcpServer Class Reference
The QTcpServer class provides a TCP-based server.
#include <qtcpserver.h>
Signals
void newConnection ()
This signal is emitted every time a new connection is available.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void close ()
Closes the server.
QString errorString () const
Returns a human readable description of the last error that occurred.
virtual bool hasPendingConnections () const
Returns true if the server has a pending connection; otherwise returns false.
bool isListening () const
Returns true if the server is currently listening for incoming connections; otherwise returns false.
bool listen (const QHostAddress &address=QHostAddress::Any, quint16 port=0)
Tells the server to listen for incoming connections on address address and port port.
int maxPendingConnections () const
Returns the maximum number of pending accepted connections.
virtual QTcpSocket * nextPendingConnection ()
Returns the next pending connection as a connected QTcpSocket object.
QNetworkProxy proxy () const
Returns the network proxy for this socket.
QTcpServer (QObject *parent=0)
Constructs a QTcpServer object.
QHostAddress serverAddress () const
Returns the server's address if the server is listening for connections; otherwise returns QHostAddress::Null.
QAbstractSocket::SocketError serverError () const
Returns an error code for the last error that occurred.
quint16 serverPort () const
Returns the server's port if the server is listening for connections; otherwise returns 0.
void setMaxPendingConnections (int numConnections)
Sets the maximum number of pending accepted connections to numConnections.
void setProxy (const QNetworkProxy &networkProxy)
Sets the explicit network proxy for this socket to networkProxy.
bool setSocketDescriptor (int socketDescriptor)
Sets the socket descriptor this server should use when listening for incoming connections to socketDescriptor.
int socketDescriptor () const
Returns the native socket descriptor the server uses to listen for incoming instructions, or -1 if the server is not listening.
bool waitForNewConnection (int msec=0, bool *timedOut=0)
Waits for at most msec milliseconds or until an incoming connection is available.
virtual ~QTcpServer ()
Destroys the QTcpServer object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void addPendingConnection (QTcpSocket *socket)
This function is called by QTcpServer::incomingConnection() to add the socket to the list of pending incoming connections.
virtual void incomingConnection (int handle)
This virtual function is called by QTcpServer when a new connection is available.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTcpServer class provides a TCP-based server.
Note
This class or function is reentrant.
Attention
Module: QtNetwork
This class makes it possible to accept incoming TCP connections. You can specify the port or have QTcpServer pick one automatically. You can listen on a specific address or on all the machine's addresses.
Call listen() to have the server listen for incoming connections. The newConnection() signal is then emitted each time a client connects to the server.
Call nextPendingConnection() to accept the pending connection as a connected QTcpSocket. The function returns a pointer to a QTcpSocket in QAbstractSocket::ConnectedState that you can use for communicating with the client.
If an error occurs, serverError() returns the type of error, and errorString() can be called to get a human readable description of what happened.
When listening for connections, the address and port on which the server is listening are available as serverAddress() and serverPort().
Calling close() makes QTcpServer stop listening for incoming connections.
Although QTcpServer is mostly designed for use with an event loop, it's possible to use it without one. In that case, you must use waitForNewConnection(), which blocks until either a connection is available or a timeout expires.
Symbian Platform Security Requirements
On Symbian, processes which use this class must have the NetworkServices platform security capability. If the client process lacks this capability, it will lead to a panic.
Platform security capabilities are added via the TARGET.CAPABILITY qmake variable.
See also
QTcpSocket, {Fortune Server Example}, {Threaded Fortune Server Example}, {Loopback Example}, {Torrent Example}
Definition at line 61 of file qtcpserver.h.
Constructors and Destructors
QTcpServer()
QTcpServer::QTcpServer (QObject * parent = 0) explicit
Constructs a QTcpServer object.
parent is passed to the QObject constructor.
See also
listen(), setSocketDescriptor()
Definition at line 252 of file qtcpserver.cpp.
     : QObject(*new QTcpServerPrivate, parent)
 {
 }
~QTcpServer()
QTcpServer::~QTcpServer () virtual
Destroys the QTcpServer object.
If the server is listening for connections, the socket is automatically closed.
Any client QTcpSocket that are still connected must either disconnect or be reparented before the server is deleted.
See also
close()
Definition at line 266 of file qtcpserver.cpp.
 {
     close();
 }
Functions
addPendingConnection()
void QTcpServer::addPendingConnection (QTcpSocket * socket) protected
This function is called by QTcpServer::incomingConnection() to add the socket to the list of pending incoming connections.
Note
Don't forget to call this member from reimplemented incomingConnection() if you do not want to break the Pending Connections mechanism.
See also
incomingConnection()
Since
4.7
Definition at line 611 of file qtcpserver.cpp.
Referenced by incomingConnection().
 {
     d_func()->pendingConnections.append(socket);
 }
close()
void QTcpServer::close ()
Closes the server.
The server will no longer listen for incoming connections.
See also
listen()
Definition at line 371 of file qtcpserver.cpp.
Referenced by QFtpDTP::setupSocket(), and ~QTcpServer().
 {
     Q_D(QTcpServer);
     qDeleteAll(d->pendingConnections);
     d->pendingConnections.clear();
     if (d->socketEngine) {
         d->socketEngine->close();
         QT_TRY {
             d->socketEngine->deleteLater();
         } QT_CATCH(const std::bad_alloc &) {
             // in out of memory situations, the socketEngine
             // will be deleted in ~QTcpServer (it's a child-object of this)
         }
         d->socketEngine = 0;
     }
     d->state = QAbstractSocket::UnconnectedState;
 }
errorString()
QString QTcpServer::errorString () const
Returns a human readable description of the last error that occurred.
See also
serverError()
Definition at line 663 of file qtcpserver.cpp.
Referenced by QVNCServer::init().
 {
     return d_func()->serverSocketErrorString;
 }
hasPendingConnections()
bool QTcpServer::hasPendingConnections () const virtual
Returns true if the server has a pending connection; otherwise returns false.
See also
nextPendingConnection(), setMaxPendingConnections()
Definition at line 531 of file qtcpserver.cpp.
 {
     return !d_func()->pendingConnections.isEmpty();
 }
incomingConnection()
void QTcpServer::incomingConnection (int socketDescriptor) protected virtual
This virtual function is called by QTcpServer when a new connection is available.
The socketDescriptor argument is the native socket descriptor for the accepted connection.
The base implementation creates a QTcpSocket, sets the socket descriptor and then stores the QTcpSocket in an internal list of pending connections. Finally newConnection() is emitted.
Reimplement this function to alter the server's behavior when a connection is available.
If this server is using QNetworkProxy then the socketDescriptor may not be usable with native socket functions, and should only be used with QTcpSocket::setSocketDescriptor().
Note
If you want to handle an incoming connection as a new QTcpSocket object in another thread you have to pass the socketDescriptor to the other thread and create the QTcpSocket object there and use its setSocketDescriptor() method.
See also
newConnection(), nextPendingConnection(), addPendingConnection()
Definition at line 589 of file qtcpserver.cpp.
 {
 #if defined (QTCPSERVER_DEBUG)
     qDebug("QTcpServer::incomingConnection(%i)", socketDescriptor);
 #endif
     QTcpSocket *socket = new QTcpSocket(this);
     socket->setSocketDescriptor(socketDescriptor);
     addPendingConnection(socket);
 }
isListening()
bool QTcpServer::isListening () const
Returns true if the server is currently listening for incoming connections; otherwise returns false.
See also
listen()
Definition at line 358 of file qtcpserver.cpp.
Referenced by QTcpServerPrivate::readNotification(), setSocketDescriptor(), QFtpDTP::setupListener(), and QFtpDTP::waitForConnection().
 {
     Q_D(const QTcpServer);
     Q_CHECK_SOCKETENGINE(false);
     return d->socketEngine->state() == QAbstractSocket::ListeningState;
 }
listen()
bool QTcpServer::listen (const QHostAddress & address = QHostAddress::Any, quint16 port = 0)
Tells the server to listen for incoming connections on address address and port port.
If port is 0, a port is chosen automatically. If address is QHostAddress::Any, the server will listen on all network interfaces.
Returns true on success; otherwise returns false.
See also
isListening()
Definition at line 281 of file qtcpserver.cpp.
Referenced by QVNCServer::init(), and QFtpDTP::setupListener().
 {
     Q_D(QTcpServer);
     if (d->state == QAbstractSocket::ListeningState) {
         qWarning("QTcpServer::listen() called when already listening");
         return false;
     }
     QAbstractSocket::NetworkLayerProtocol proto = address.protocol();
 #ifdef QT_NO_NETWORKPROXY
     static const QNetworkProxy &proxy = *(QNetworkProxy *)0;
 #else
     QNetworkProxy proxy = d->resolveProxy(address, port);
 #endif
     delete d->socketEngine;
     d->socketEngine = QAbstractSocketEngine::createSocketEngine(QAbstractSocket::TcpSocket, proxy, this);
     if (!d->socketEngine) {
         d->serverSocketError = QAbstractSocket::UnsupportedSocketOperationError;
         d->serverSocketErrorString = tr("Operation on socket is not supported");
         return false;
     }
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the socket engine (if it has been set)
     d->socketEngine->setProperty("_q_networksession", property("_q_networksession"));
 #endif
     if (!d->socketEngine->initialize(QAbstractSocket::TcpSocket, proto)) {
         d->serverSocketError = d->socketEngine->error();
         d->serverSocketErrorString = d->socketEngine->errorString();
         return false;
     }
 #if defined(Q_OS_UNIX)
     // Under Unix, we want to be able to bind to the port, even if a socket on
     // the same address-port is in TIME_WAIT. Under Windows this is possible
     // anyway -- furthermore, the meaning of reusable on Windows is different:
     // it means that you can use the same address-port for multiple listening
     // sockets.
     // Don't abort though if we can't set that option. For example the socks
     // engine doesn't support that option, but that shouldn't prevent us from
     // trying to bind/listen.
     d->socketEngine->setOption(QAbstractSocketEngine::AddressReusable, 1);
 #endif
     if (!d->socketEngine->bind(address, port)) {
         d->serverSocketError = d->socketEngine->error();
         d->serverSocketErrorString = d->socketEngine->errorString();
         return false;
     }
     if (!d->socketEngine->listen()) {
         d->serverSocketError = d->socketEngine->error();
         d->serverSocketErrorString = d->socketEngine->errorString();
         return false;
     }
     d->socketEngine->setReceiver(d);
     d->socketEngine->setReadNotificationEnabled(true);
     d->state = QAbstractSocket::ListeningState;
     d->address = d->socketEngine->localAddress();
     d->port = d->socketEngine->localPort();
 #if defined (QTCPSERVER_DEBUG)
     qDebug("QTcpServer::listen(%i, \"%s\") == true (listening on port %i)", port,
            address.toString().toLatin1().constData(), d->socketEngine->localPort());
 #endif
     return true;
 }
maxPendingConnections()
int QTcpServer::maxPendingConnections () const
Returns the maximum number of pending accepted connections.
The default is 30.
See also
setMaxPendingConnections(), hasPendingConnections()
Definition at line 642 of file qtcpserver.cpp.
 {
     return d_func()->maxConnections;
 }
newConnection
void QTcpServer::newConnection () signal
This signal is emitted every time a new connection is available.
See also
hasPendingConnections(), nextPendingConnection()
nextPendingConnection()
QTcpSocket * QTcpServer::nextPendingConnection () virtual
Returns the next pending connection as a connected QTcpSocket object.
The socket is created as a child of the server, which means that it is automatically deleted when the QTcpServer object is destroyed. It is still a good idea to delete the object explicitly when you are done with it, to avoid wasting memory.
0 is returned if this function is called when there are no pending connections.
Note
The returned QTcpSocket object cannot be used from another thread. If you want to use an incoming connection from another thread, you need to override incomingConnection().
See also
hasPendingConnections()
Definition at line 554 of file qtcpserver.cpp.
Referenced by QVNCServer::newConnection(), and QFtpDTP::setupSocket().
 {
     Q_D(QTcpServer);
     if (d->pendingConnections.isEmpty())
         return 0;
     if (!d->socketEngine->isReadNotificationEnabled())
         d->socketEngine->setReadNotificationEnabled(true);
     return d->pendingConnections.takeFirst();
 }
proxy()
QNetworkProxy QTcpServer::proxy () const
Returns the network proxy for this socket.
Since
4.1
By default QNetworkProxy::DefaultProxy is used.
See also
setProxy(), QNetworkProxy
Definition at line 701 of file qtcpserver.cpp.
Referenced by listen().
 {
     Q_D(const QTcpServer);
     return d->proxy;
 }
serverAddress()
QHostAddress QTcpServer::serverAddress () const
Returns the server's address if the server is listening for connections; otherwise returns QHostAddress::Null.
See also
serverPort(), listen()
Definition at line 479 of file qtcpserver.cpp.
 {
     Q_D(const QTcpServer);
     Q_CHECK_SOCKETENGINE(QHostAddress(QHostAddress::Null));
     return d->socketEngine->localAddress();
 }
serverError()
QAbstractSocket::SocketError QTcpServer::serverError () const
Returns an error code for the last error that occurred.
See also
errorString()
Definition at line 652 of file qtcpserver.cpp.
 {
     return d_func()->serverSocketError;
 }
serverPort()
quint16 QTcpServer::serverPort () const
Returns the server's port if the server is listening for connections; otherwise returns 0.
See also
serverAddress(), listen()
Definition at line 466 of file qtcpserver.cpp.
Referenced by QFtpDTP::setupListener().
 {
     Q_D(const QTcpServer);
     Q_CHECK_SOCKETENGINE(0);
     return d->socketEngine->localPort();
 }
setMaxPendingConnections()
void QTcpServer::setMaxPendingConnections (int numConnections)
Sets the maximum number of pending accepted connections to numConnections.
QTcpServer will accept no more than numConnections incoming connections before nextPendingConnection() is called. By default, the limit is 30 pending connections.
Clients may still able to connect after the server has reached its maximum number of pending connections (i.e., QTcpSocket can still emit the connected() signal). QTcpServer will stop accepting the new connections, but the operating system may still keep them in queue.
See also
maxPendingConnections(), hasPendingConnections()
Definition at line 631 of file qtcpserver.cpp.
 {
     d_func()->maxConnections = numConnections;
 }
setProxy()
void QTcpServer::setProxy (const QNetworkProxy & networkProxy)
Sets the explicit network proxy for this socket to networkProxy.
Since
4.1
To disable the use of a proxy for this socket, use the QNetworkProxy::NoProxy proxy type:
server->setProxy(QNetworkProxy::NoProxy);
See also
proxy(), QNetworkProxy
Definition at line 684 of file qtcpserver.cpp.
 {
     Q_D(QTcpServer);
     d->proxy = networkProxy;
 }
setSocketDescriptor()
bool QTcpServer::setSocketDescriptor (int socketDescriptor)
Sets the socket descriptor this server should use when listening for incoming connections to socketDescriptor.
Returns true if the socket is set successfully; otherwise returns false.
The socket is assumed to be in listening state.
See also
socketDescriptor(), isListening()
Definition at line 417 of file qtcpserver.cpp.
 {
     Q_D(QTcpServer);
     if (isListening()) {
         qWarning("QTcpServer::setSocketDescriptor() called when already listening");
         return false;
     }
     if (d->socketEngine)
         delete d->socketEngine;
     d->socketEngine = QAbstractSocketEngine::createSocketEngine(socketDescriptor, this);
     if (!d->socketEngine) {
         d->serverSocketError = QAbstractSocket::UnsupportedSocketOperationError;
         d->serverSocketErrorString = tr("Operation on socket is not supported");
         return false;
     }
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the socket engine (if it has been set)
     d->socketEngine->setProperty("_q_networksession", property("_q_networksession"));
 #endif
     if (!d->socketEngine->initialize(socketDescriptor, QAbstractSocket::ListeningState)) {
         d->serverSocketError = d->socketEngine->error();
         d->serverSocketErrorString = d->socketEngine->errorString();
 #if defined (QTCPSERVER_DEBUG)
         qDebug("QTcpServer::setSocketDescriptor(%i) failed (%s)", socketDescriptor,
                d->serverSocketErrorString.toLatin1().constData());
 #endif
         return false;
     }
     d->socketEngine->setReceiver(d);
     d->socketEngine->setReadNotificationEnabled(true);
     d->state = d->socketEngine->state();
     d->address = d->socketEngine->localAddress();
     d->port = d->socketEngine->localPort();
 #if defined (QTCPSERVER_DEBUG)
     qDebug("QTcpServer::setSocketDescriptor(%i) succeeded.", socketDescriptor);
 #endif
     return true;
 }
socketDescriptor()
int QTcpServer::socketDescriptor () const
Returns the native socket descriptor the server uses to listen for incoming instructions, or -1 if the server is not listening.
If the server is using QNetworkProxy, the returned descriptor may not be usable with native socket functions.
See also
setSocketDescriptor(), isListening()
Definition at line 401 of file qtcpserver.cpp.
 {
     Q_D(const QTcpServer);
     Q_CHECK_SOCKETENGINE(-1);
     return d->socketEngine->socketDescriptor();
 }
waitForNewConnection()
bool QTcpServer::waitForNewConnection (int msec = 0, bool * timedOut = 0)
Waits for at most msec milliseconds or until an incoming connection is available.
Returns true if a connection is available; otherwise returns false. If the operation timed out and timedOut is not 0, *timedOut will be set to true.
This is a blocking function call. Its use is disadvised in a single-threaded GUI application, since the whole application will stop responding until the function returns. waitForNewConnection() is mostly useful when there is no event loop available.
The non-blocking alternative is to connect to the newConnection() signal.
If msec is -1, this function will not time out.
See also
hasPendingConnections(), nextPendingConnection()
Definition at line 505 of file qtcpserver.cpp.
Referenced by QFtpDTP::waitForConnection().
 {
     Q_D(QTcpServer);
     if (d->state != QAbstractSocket::ListeningState)
         return false;
     if (!d->socketEngine->waitForRead(msec, timedOut)) {
         d->serverSocketError = d->socketEngine->error();
         d->serverSocketErrorString = d->socketEngine->errorString();
         return false;
     }
     if (timedOut && *timedOut)
         return false;
     d->readNotification();
     return true;
 }
The documentation for this class was generated from the following files:
/src/network/socket/qtcpserver.h
/src/network/socket/qtcpserver.cpp