Qt 4.8: QTranslator Class Reference
QTranslator Class Reference
The QTranslator class provides internationalization support for text output.
#include <qtranslator.h>
Public Functions
virtual bool isEmpty () const
Returns true if this translator is empty, otherwise returns false.
bool load (const QString &filename, const QString &directory=QString(), const QString &search_delimiters=QString(), const QString &suffix=QString())
Loads filename + suffix (".qm" if the suffix is not specified), which may be an absolute file name or relative to directory.
bool load (const QLocale &locale, const QString &filename, const QString &prefix=QString(), const QString &directory=QString(), const QString &suffix=QString())
Loads filename + prefix + ui language name + suffix (".
bool load (const uchar *data, int len)
Loads the QM file data data of length len into the translator.
QTranslator (QObject *parent=0)
Constructs an empty message file object with parent parent that is not connected to any file.
virtual QString translate (const char *context, const char *sourceText, const char *disambiguation=0) const
Returns the translation for the key (context, sourceText, disambiguation).
QString translate (const char *context, const char *sourceText, const char *disambiguation, int n) const
~QTranslator ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTranslator class provides internationalization support for text output.
An object of this class contains a set of translations from a source language to a target language. QTranslator provides functions to look up translations in a translation file. Translation files are created using Qt Linguist.
The most common use of QTranslator is to: load a translation file, install it using QApplication::installTranslator(), and use it via QObject::tr(). Here's the main() function from the Hello tr() example:
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QTranslator translator;
    translator.load("hellotr_la");
    app.installTranslator(&translator);
    QPushButton hello(QPushButton::tr("Hello world!"));
    hello.resize(100, 30);
    hello.show();
    return app.exec();
}
Note that the translator must be created before the application's widgets.
Most applications will never need to do anything else with this class. The other functions provided by this class are useful for applications that work on translator files.
Looking up Translations
It is possible to look up a translation using translate() (as tr() and QApplication::translate() do). The translate() function takes up to three parameters:
The context - usually the class name for the tr() caller.
The {source text} - usually the argument to tr().
The disambiguation - an optional string that helps disambiguate different uses of the same text in the same context.
For example, the "Cancel" in a dialog might have "Anuluj" when the program runs in Polish (in this case the source text would be "Cancel"). The context would (normally) be the dialog's class name; there would normally be no comment, and the translated text would be "Anuluj".
But it's not always so simple. The Spanish version of a printer dialog with settings for two-sided printing and binding would probably require both "Activado" and "Activada" as translations for "Enabled". In this case the source text would be "Enabled" in both cases, and the context would be the dialog's class name, but the two items would have disambiguations such as "two-sided printing" for one and "binding" for the other. The disambiguation enables the translator to choose the appropriate gender for the Spanish version, and enables Qt to distinguish between translations.
Using Multiple Translations
Multiple translation files can be installed in an application. Translations are searched for in the reverse order in which they were installed, so the most recently installed translation file is searched for translations first and the earliest translation file is searched last. The search stops as soon as a translation containing a matching string is found.
This mechanism makes it possible for a specific translation to be "selected" or given priority over the others; simply uninstall the translator from the application by passing it to the QApplication::removeTranslator() function and reinstall it with QApplication::installTranslator(). It will then be the first translation to be searched for matching strings.
See also
QApplication::installTranslator(), QApplication::removeTranslator(), QObject::tr(), QApplication::translate(), {I18N Example}, {Hello tr() Example}, {Arrow Pad Example}, {Troll Print Example}
Definition at line 59 of file qtranslator.h.
Constructors and Destructors
QTranslator()
QTranslator::QTranslator (QObject * parent = 0) explicit
Constructs an empty message file object with parent parent that is not connected to any file.
Definition at line 342 of file qtranslator.cpp.
     : QObject(*new QTranslatorPrivate, parent)
 {
 }
~QTranslator()
QTranslator::~QTranslator ()
Destroys the object and frees any allocated resources.
Definition at line 363 of file qtranslator.cpp.
 {
     if (QCoreApplication::instance())
         QCoreApplication::removeTranslator(this);
     Q_D(QTranslator);
     d->clear();
 }
Functions
isEmpty()
bool QTranslator::isEmpty () const virtual
Returns true if this translator is empty, otherwise returns false.
This function works with stripped and unstripped translation files.
Definition at line 1045 of file qtranslator.cpp.
Referenced by QCoreApplication::installTranslator().
 {
     Q_D(const QTranslator);
     return !d->unmapPointer && !d->unmapLength && !d->messageArray &&
            !d->offsetArray && !d->contextArray;
 }
load() [1/3]
bool QTranslator::load (const QString & filename, const QString & directory = QString(), const QString & search_delimiters = QString(), const QString & suffix = QString())
Loads filename + suffix (".qm" if the suffix is not specified), which may be an absolute file name or relative to directory.
Returns true if the translation is successfully loaded; otherwise returns false.
If directory is not specified, the directory of the application's executable is used (i.e., as QCoreApplication::applicationDirPath()).
The previous contents of this translator object are discarded.
If the file name does not exist, other file names are tried in the following order:
File name without suffix appended.
File name with text after a character in search_delimiters stripped ("_." is the default for search_delimiters if it is an empty string) and suffix.
File name stripped without suffix appended.
File name stripped further, etc.
For example, an application running in the fr_CA locale (French-speaking Canada) might call load("foo.fr_ca", "/opt/foolib"). load() would then try to open the first existing readable file from this list:
/opt/foolib/foo.fr_ca.qm
/opt/foolib/foo.fr_ca
/opt/foolib/foo.fr.qm
/opt/foolib/foo.fr
/opt/foolib/foo.qm
/opt/foolib/foo
Definition at line 411 of file qtranslator.cpp.
 {
     Q_D(QTranslator);
     d->clear();
     QString fname = filename;
     QString prefix;
     if (QFileInfo(filename).isRelative()) {
 #ifdef Q_OS_SYMBIAN
         //TFindFile doesn't like path in the filename
         QString dir(directory);
         int slash = filename.lastIndexOf(QLatin1Char('/'));
         slash = qMax(slash, filename.lastIndexOf(QLatin1Char('\\')));
         if (slash >=0) {
             //so move the path component into the directory prefix
             if (dir.isEmpty())
                 dir = filename.left(slash + 1);
             else
                 dir = dir + QLatin1Char('/') + filename.left(slash + 1);
             fname = fname.mid(slash + 1);
         }
         if (dir.isEmpty())
             prefix = QCoreApplication::applicationDirPath();
         else
             prefix = QFileInfo(dir).absoluteFilePath(); //TFindFile doesn't like dirty paths
         if (prefix.length() > 2 && prefix.at(1) == QLatin1Char(':') && prefix.at(0).isLetter())
             prefix[0] = QLatin1Char('Y');
 #else
         prefix = directory;
 #endif
         if (prefix.length() && !prefix.endsWith(QLatin1Char('/')))
             prefix += QLatin1Char('/');
     }
 #ifdef Q_OS_SYMBIAN
     QString nativePrefix = QDir::toNativeSeparators(prefix);
 #endif
     QString realname;
     QString delims;
     delims = search_delimiters.isNull() ? QString::fromLatin1("_.") : search_delimiters;
     for (;;) {
         QFileInfo fi;
 #ifdef Q_OS_SYMBIAN
         //search for translations on other drives, e.g. Qt may be in Z, while app is in C
         //note this uses symbian search rules, i.e. y:->a:, followed by z:
         TFindFile finder(qt_s60GetRFs());
         QString fname2 = fname + (suffix.isNull() ? QString::fromLatin1(".qm") : suffix);
         TInt err = finder.FindByDir(
             qt_QString2TPtrC(fname2),
             qt_QString2TPtrC(nativePrefix));
         if (err != KErrNone)
             err = finder.FindByDir(qt_QString2TPtrC(fname), qt_QString2TPtrC(nativePrefix));
         if (err == KErrNone) {
             fi.setFile(qt_TDesC2QString(finder.File()));
             realname = fi.canonicalFilePath();
             if (fi.isReadable() && fi.isFile())
                 break;
         }
 #endif
         realname = prefix + fname + (suffix.isNull() ? QString::fromLatin1(".qm") : suffix);
         fi.setFile(realname);
         if (fi.isReadable() && fi.isFile())
             break;
         realname = prefix + fname;
         fi.setFile(realname);
         if (fi.isReadable() && fi.isFile())
             break;
         int rightmost = 0;
         for (int i = 0; i < (int)delims.length(); i++) {
             int k = fname.lastIndexOf(delims[i]);
             if (k > rightmost)
                 rightmost = k;
         }
         // no truncations? fail
         if (rightmost == 0)
             return false;
         fname.truncate(rightmost);
     }
     // realname is now the fully qualified name of a readable file.
     return d->do_load(realname);
 }
load() [2/3]
bool QTranslator::load (const QLocale & locale, const QString & filename, const QString & prefix = QString(), const QString & directory = QString(), const QString & suffix = QString())
Loads filename + prefix + ui language name + suffix (".
Since
4.8
qm" if the suffix is not specified), which may be an absolute file name or relative to directory. Returns true if the translation is successfully loaded; otherwise returns false.
The previous contents of this translator object are discarded.
If the file name does not exist, other file names are tried in the following order:
File name without suffix appended.
File name with ui language part after a "_" character stripped and suffix.
File name with ui language part stripped without suffix appended.
File name with ui language part stripped further, etc.
For example, an application running in the locale with the following ui languages - "es", "fr-CA", "de" might call load(QLocale::system(), "foo", ".", "/opt/foolib", ".qm"). load() would replace '-' (dash) with '_' (underscore) in the ui language and then try to open the first existing readable file from this list:
/opt/foolib/foo.es.qm
/opt/foolib/foo.es
/opt/foolib/foo.fr_CA.qm
/opt/foolib/foo.fr_CA
/opt/foolib/foo.de.qm
/opt/foolib/foo.de
/opt/foolib/foo.fr.qm
/opt/foolib/foo.fr
/opt/foolib/foo.qm
/opt/foolib/foo.
/opt/foolib/foo
On operating systems where file system is case sensitive, QTranslator also tries to load a lower-cased version of the locale name.
Definition at line 718 of file qtranslator.cpp.
 {
     Q_D(QTranslator);
     d->clear();
     QString fname = find_translation(locale, filename, prefix, directory, suffix);
     return !fname.isEmpty() && d->do_load(fname);
 }
load() [3/3]
bool QTranslator::load (const uchar * data, int len)
Loads the QM file data data of length len into the translator.
The data is not copied. The caller must be able to guarantee that data will not be deleted or modified.
Definition at line 740 of file qtranslator.cpp.
 {
     Q_D(QTranslator);
     d->clear();
     return d->do_load(data, len);
 }
translate() [1/2]
QString QTranslator::translate (const char * context, const char * sourceText, const char * disambiguation = 0) const virtual
Returns the translation for the key (context, sourceText, disambiguation).
If none is found, also tries (context, sourceText, ""). If that still fails, returns an empty string.
If you need to programatically insert translations in to a QTranslator, this function can be reimplemented.
See also
load()
Definition at line 1009 of file qtranslator.cpp.
Referenced by translate(), and QCoreApplication::translate().
 {
     Q_D(const QTranslator);
     return d->do_translate(context, sourceText, disambiguation, -1);
 }
translate() [2/2]
QString QTranslator::translate (const char * context, const char * sourceText, const char * disambiguation, int n) const
Definition at line 1031 of file qtranslator.cpp.
 {
     Q_D(const QTranslator);
     // this step is necessary because the 3-parameter translate() overload is virtual
     if (n == -1)
         return translate(context, sourceText, disambiguation);
     return d->do_translate(context, sourceText, disambiguation, n);
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qtranslator.h
/src/corelib/kernel/qtranslator.cpp