Qt 4.8: QAccessibleItemRow Class Reference
QAccessibleItemRow Class Reference
#include <complexwidgets.h>
Public Functions
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
QModelIndex childIndex (int child) const
QList< QModelIndex > children () const
bool doAction (int action, int child, const QVariantList &params=QVariantList())
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
QHeaderView * horizontalHeader () const
int indexOfChild (const QAccessibleInterface *) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
int navigate (RelationFlag relation, int index, QAccessibleInterface **iface) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleItemRow (QAbstractItemView *view, const QModelIndex &index=QModelIndex(), bool isHeader=false)
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Private Functions
int logicalFromChild (QHeaderView *header, int child) const
QString text_helper (int child) const
int treeLevel () const
QHeaderView * verticalHeader () const
Static Private Functions
static QAbstractItemView::CursorAction toCursorAction (Relation rel)
Properties
bool m_header
QPersistentModelIndex row
QPointer< QAbstractItemView > view
Friends
class QAccessibleItemView
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 123 of file complexwidgets.h.
Constructors and Destructors
QAccessibleItemRow()
QAccessibleItemRow::QAccessibleItemRow (QAbstractItemView * view, const QModelIndex & index = QModelIndex(), bool isHeader = false)
Definition at line 99 of file complexwidgets.cpp.
Referenced by navigate().
     : row(index), view(aView), m_header(isHeader)
 {
 }
Functions
actionText()
QString QAccessibleItemRow::actionText (int action, Text t, int child) const virtual
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
See also
text(), userActionCount()
Implements QAccessibleInterface.
Definition at line 652 of file complexwidgets.cpp.
 {
     return QString();
 }
childAt()
int QAccessibleItemRow::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Implements QAccessibleInterface.
Definition at line 452 of file complexwidgets.cpp.
 {
     if (!view || !view->isVisible())
         return -1;
     for (int i = childCount(); i >= 0; --i) {
         if (rect(i).contains(x, y))
             return i;
     }
     return -1;
 }
childCount()
int QAccessibleItemRow::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Implements QAccessibleInterface.
Definition at line 408 of file complexwidgets.cpp.
Referenced by childAt(), and navigate().
 {
     int count = 0;
     if (QHeaderView *header = horizontalHeader()) {
         count = header->count() - header->hiddenSectionCount();
     } else {
         count = children().count();
     }
 #ifndef QT_NO_TABLEVIEW
     if (qobject_cast<const QTableView*>(view)) {
         if (verticalHeader())
             ++count;
     }
 #endif
     return count;
 }
childIndex()
QModelIndex QAccessibleItemRow::childIndex (int child) const
Definition at line 379 of file complexwidgets.cpp.
Referenced by doAction(), rect(), setText(), state(), text(), and text_helper().
 {
     QList<QModelIndex> kids = children();
     Q_ASSERT(child >= 1 && child <= kids.count());
     return kids.at(child - 1);
 }
children()
QList< QModelIndex > QAccessibleItemRow::children () const
Definition at line 386 of file complexwidgets.cpp.
Referenced by childCount(), childIndex(), indexOfChild(), navigate(), setText(), text(), and text_helper().
 {
     QList<QModelIndex> kids;
     for (int i = 0; i < row.model()->columnCount(row.parent()); ++i) {
         QModelIndex idx = row.model()->index(row.row(), i, row.parent());
         if (!view->isIndexHidden(idx)) {
             kids << idx;
         }
     }
     return kids;
 }
doAction()
bool QAccessibleItemRow::doAction (int action, int child, const QVariantList & params = QVariantList()) virtual
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
Returns true if the action could be executed; otherwise returns false.
action can be a predefined or a custom action.
See also
userActionCount(), actionText()
Implements QAccessibleInterface.
Definition at line 663 of file complexwidgets.cpp.
 {
     if (!view)
         return false;
     if (verticalHeader())
         --child;
     QModelIndex idx = child ? childIndex(child) : QModelIndex(row);
     if (!idx.isValid())
         return false;
     QItemSelectionModel::SelectionFlags command = QItemSelectionModel::NoUpdate;
     switch  (action) {
     case SetFocus:
         view->setCurrentIndex(idx);
         return true;
     case ExtendSelection:
         if (!child)
             return false;
         view->selectionModel()->select(QItemSelection(view->currentIndex(), idx),
                     QItemSelectionModel::SelectCurrent);
         return true;
     case Select:
         command = QItemSelectionModel::ClearAndSelect;
         break;
     case ClearSelection:
         command = QItemSelectionModel::Clear;
         break;
     case RemoveSelection:
         command = QItemSelectionModel::Deselect;
         break;
     case AddToSelection:
         command = QItemSelectionModel::SelectCurrent;
         break;
     }
     if (command == QItemSelectionModel::NoUpdate)
         return false;
     if (child)
         view->selectionModel()->select(idx, command);
     else
         view->selectionModel()->select(rowAt(row), command);
     return true;
 }
horizontalHeader()
QHeaderView * QAccessibleItemRow::horizontalHeader () const
Definition at line 104 of file complexwidgets.cpp.
Referenced by childCount(), QAccessibleItemView::indexOfChild(), rect(), role(), state(), and text_helper().
 {
     QHeaderView *header = 0;
     if (m_header) {
         if (false) {
 #ifndef QT_NO_TABLEVIEW
         } else if (const QTableView *tv = qobject_cast<const QTableView*>(view)) {
             header = tv->horizontalHeader();
 #endif
 #ifndef QT_NO_TREEVIEW
         } else if (const QTreeView *tv = qobject_cast<const QTreeView*>(view)) {
             header = tv->header();
 #endif
         }
     }
     return header;
 }
indexOfChild()
int QAccessibleItemRow::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Implements QAccessibleInterface.
Definition at line 425 of file complexwidgets.cpp.
 {
     if (!iface || iface->role(0) != Row)
         return -1;
     //### meaningless code?
     QList<QModelIndex> kids = children();
     QModelIndex idx = static_cast<const QAccessibleItemRow *>(iface)->row;
     if (!idx.isValid())
         return -1;
     return kids.indexOf(idx) + 1;
 }
isValid()
bool QAccessibleItemRow::isValid () const virtual
Returns true if all the data necessary to use this interface implementation is valid (e.
g. all pointers are non-null); otherwise returns false.
See also
object()
Implements QAccessibleInterface.
Definition at line 398 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::text().
 {
     return m_header ? true : row.isValid();
 }
logicalFromChild()
int QAccessibleItemRow::logicalFromChild (QHeaderView * header, int child) const private
Definition at line 132 of file complexwidgets.cpp.
Referenced by rect(), and text_helper().
 {
     int logical = -1;
     if (header->sectionsHidden()) {
         int kid = 0;
         for (int i = 0; i < header->count(); ++i) {
             if (!header->isSectionHidden(i))
                 ++kid;
             if (kid == child) {
                 logical = i;
                 break;
             }
         }
     } else {
         logical = child - 1;
     }
     return logical;
 }
navigate()
int QAccessibleItemRow::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Implements QAccessibleInterface.
Definition at line 483 of file complexwidgets.cpp.
Referenced by state().
 {
     *iface = 0;
     if (!view)
         return -1;
     switch (relation) {
     case Ancestor: {
         if (!index)
             return -1;
         QAccessibleItemView *ancestor = new QAccessibleItemView(view->viewport());
         if (index == 1) {
             *iface = ancestor;
             return 0;
         } else if (index > 1) {
             int ret = ancestor->navigate(Ancestor, index - 1, iface);
             delete ancestor;
             return ret;
         }
         }
     case Child: {
         if (!index)
             return -1;
         if (index < 1 && index > childCount())
             return -1;
         return index;}
     case Sibling:
         if (index) {
             QAccessibleInterface *ifaceParent = 0;
             navigate(Ancestor, 1, &ifaceParent);
             if (ifaceParent) {
                 int entry = ifaceParent->navigate(Child, index, iface);
                 delete ifaceParent;
                 return entry;
             }
         }
         return -1;
     case Up:
     case Down:
     case Left:
     case Right: {
         // This is in the "not so nice" category. In order to find out which item
         // is geometrically around, we have to set the current index, navigate
         // and restore the index as well as the old selection
         view->setUpdatesEnabled(false);
         const QModelIndex oldIdx = view->currentIndex();
         QList<QModelIndex> kids = children();
         const QModelIndex currentIndex = index ? kids.at(index - 1) : QModelIndex(row);
         const QItemSelection oldSelection = view->selectionModel()->selection();
         view->setCurrentIndex(currentIndex);
         const QModelIndex idx = view->moveCursor(toCursorAction(relation), Qt::NoModifier);
         view->setCurrentIndex(oldIdx);
         view->selectionModel()->select(oldSelection, QItemSelectionModel::ClearAndSelect);
         view->setUpdatesEnabled(true);
         if (!idx.isValid())
             return -1;
         if (idx.parent() != row.parent() || idx.row() != row.row())
             *iface = new QAccessibleItemRow(view, idx);
         return index ? kids.indexOf(idx) + 1 : 0; }
     default:
         break;
     }
     return -1;
 }
object()
QObject * QAccessibleItemRow::object () const virtual
Returns a pointer to the QObject this interface implementation provides information for.
See also
isValid()
Implements QAccessibleInterface.
Definition at line 403 of file complexwidgets.cpp.
 {
     return 0;
 }
rect()
QRect QAccessibleItemRow::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Implements QAccessibleInterface.
Definition at line 151 of file complexwidgets.cpp.
Referenced by childAt(), and state().
 {
     QRect r;
     if (view && view->isVisible()) {
         if (QHeaderView *header = horizontalHeader()) {
             if (!child) {
                 r = header->rect();
             } else {
                 if (QHeaderView *vheader = verticalHeader()) {
                     if (child == 1) {
                         int w = vheader->width();
                         int h = header->height();
                         r.setRect(0, 0, w, h);
                     }
                     --child;
                 }
                 if (child) {
                     int logical = logicalFromChild(header, child);
                     int w = header->sectionSize(logical);
                     r.setRect(header->sectionViewportPosition(logical), 0, w, header->height());
                     r.translate(header->mapTo(view, QPoint(0, 0)));
                 }
             }
         } else if (row.isValid()) {
             if (!child) {
                 QModelIndex parent = row.parent();
                 const int colCount = row.model()->columnCount(parent);
                 for (int i = 0; i < colCount; ++i)
                     r |= view->visualRect(row.model()->index(row.row(), i, parent));
                 r.translate(view->viewport()->mapTo(view, QPoint(0,0)));
                 if (const QHeaderView *vheader = verticalHeader()) { // include the section of the vertical header
                     QRect re;
                     int logicalRow = row.row();
                     int h = vheader->sectionSize(logicalRow);
                     re.setRect(0, vheader->sectionViewportPosition(logicalRow), vheader->width(), h);
                     re.translate(vheader->mapTo(view, QPoint(0, 0)));
                     r |= re;
                 }
             } else {
                 if (QHeaderView *vheader = verticalHeader()) {
                     if (child == 1) {
                         int logicalRow = row.row();
                         int h = vheader->sectionSize(logicalRow);
                         r.setRect(0, vheader->sectionViewportPosition(logicalRow), vheader->width(), h);
                         r.translate(vheader->mapTo(view, QPoint(0, 0)));
                     }
                     --child;
                 }
                 if (child) {
                     r = view->visualRect(childIndex(child));
                     r.translate(view->viewport()->mapTo(view, QPoint(0,0)));
                 }
             }
         }
     }
     if (!r.isNull())
         r.translate(view->mapToGlobal(QPoint(0, 0)));
     return r;
 }
relationTo()
QAccessible::Relation QAccessibleItemRow::relationTo (int child, const QAccessibleInterface * other, int otherChild) const virtual
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
If child is 0 the object's own relation is returned.
The returned value indicates the relation of the called object to the other object, e.g. if this object is a child of other the return value will be Child.
The return value is a combination of the bit flags in the QAccessible::Relation enumeration.
All objects provide this information.
See also
indexOfChild(), navigate()
Implements QAccessibleInterface.
Definition at line 438 of file complexwidgets.cpp.
 {
     if (!child && !otherChild && other->object() == view)
         return Child;
     if (!child && !otherChild && other == this)
         return Self;
     if (!child && otherChild && other == this)
         return Ancestor;
     if (child && otherChild && other == this)
         return Sibling;
     return Unrelated;
 }
role()
QAccessible::Role QAccessibleItemRow::role (int child) const virtual
Returns the role of the object, or of the object's child if child is not 0.
The role of an object is usually static.
All accessible objects have a role.
See also
text(), state()
Implements QAccessibleInterface.
Definition at line 552 of file complexwidgets.cpp.
 {
     if (false) {
 #ifndef QT_NO_TREEVIEW
     } else if (qobject_cast<const QTreeView*>(view)) {
         if (horizontalHeader()) {
             if (!child)
                 return Row;
             return ColumnHeader;
         }
         return TreeItem;
 #endif
 #ifndef QT_NO_LISTVIEW
     } else if (qobject_cast<const QListView*>(view)) {
         return ListItem;
 #endif
 #ifndef QT_NO_TABLEVIEW
     } else if (qobject_cast<const QTableView *>(view)) {
         if (!child)
             return Row;
         if (child == 1) {
             if (verticalHeader())
                 return RowHeader;
         }
         if (m_header)
             return ColumnHeader;
 #endif
     }
     return Cell;
 }
setText()
void QAccessibleItemRow::setText (Text t, int child, const QString & text) virtual
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Note that the text properties of most objects are read-only.
See also
text()
Implements QAccessibleInterface.
Definition at line 340 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::setText().
 {
     if (m_header) {
         if (child)
             view->model()->setHeaderData(child - 1, Qt::Horizontal, text);
         // child == 0 means the cell to the left of the horizontal header, which is empty!?
     } else {
         if (!child) {
             if (children().count() == 1)
                 child = 1;
             else
                 return;
         }
         if (verticalHeader()) {
             if (child == 1) {
                 view->model()->setHeaderData(row.row(), Qt::Vertical, text);
                 return;
             }
             --child;
         }
         QModelIndex idx = childIndex(child);
         if (!idx.isValid())
             return;
         switch (t) {
         case Description:
             const_cast<QAbstractItemModel *>(idx.model())->setData(idx, text,
                                              Qt::AccessibleDescriptionRole);
             break;
         case Value:
             const_cast<QAbstractItemModel *>(idx.model())->setData(idx, text, Qt::EditRole);
             break;
         default:
             break;
         }
     }
 }
state()
QAccessible::State QAccessibleItemRow::state (int child) const virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Implements QAccessibleInterface.
Definition at line 583 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::state().
 {
     State st = Normal;
     if (!view)
         return st;
     QAccessibleInterface *parent = 0;
     QRect globalRect;
     if (navigate(Ancestor, 1, &parent) == 0) {
         globalRect = parent->rect(0);
         delete parent;
     }
     if (!globalRect.intersects(rect(child)))
         st |= Invisible;
     if (!horizontalHeader()) {
         if (!(st & Invisible)) {
             if (child) {
                 if (QHeaderView *vheader = verticalHeader() ) {
                     if (child == 1) {
                         if (!vheader->isVisible())
                             st |= Invisible;
                     }
                     --child;
                 }
                 if (child) {
                     QModelIndex idx = childIndex(child);
                     if (!idx.isValid())
                         return st;
                     if (view->selectionModel()->isSelected(idx))
                         st |= Selected;
                     if (view->selectionModel()->currentIndex() == idx)
                         st |= Focused;
                     if (idx.model()->data(idx, Qt::CheckStateRole).toInt() == Qt::Checked)
                         st |= Checked;
                     Qt::ItemFlags flags = idx.flags();
                     if (flags & Qt::ItemIsSelectable) {
                         st |= Selectable;
                         if (view->selectionMode() == QAbstractItemView::MultiSelection)
                             st |= MultiSelectable;
                         if (view->selectionMode() == QAbstractItemView::ExtendedSelection)
                             st |= ExtSelectable;
                     }
                 }
             } else {
                 Qt::ItemFlags flags = row.flags();
                 if (flags & Qt::ItemIsSelectable) {
                     st |= Selectable;
                     st |= Focusable;
                 }
                 if (view->selectionModel()->isRowSelected(row.row(), row.parent()))
                     st |= Selected;
                 if (view->selectionModel()->currentIndex().row() == row.row())
                     st |= Focused;
             }
         }
     }
     return st;
 }
text()
QString QAccessibleItemRow::text (Text t, int child) const virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Implements QAccessibleInterface.
Definition at line 271 of file complexwidgets.cpp.
Referenced by setText(), and QAccessibleItemView::text().
 {
     QString value;
     if (t == Name) {
         value = text_helper(child);
     } else if (t == Value) {
 #ifndef QT_NO_TREEVIEW
         if (qobject_cast<const QTreeView*>(view)) {
             if (child == 0)
                 value = QString::number(treeLevel());
         } else
 #endif
         {
             value = text_helper(child);
         }
     } else if (t == Description) {
 #ifndef QT_NO_TREEVIEW
         if (child == 0 && qobject_cast<const QTreeView*>(view)) {
             // We store the tree coordinates of the current item in the description.
             // This enables some screen readers to report where the focus is
             // in a tree view. (works in JAWS). Also, Firefox does the same thing.
             // For instance the description "L2, 4 of 25 with 24" means
             // "L2": Tree Level 2
             // "4 of 25": We are item 4 out of in total 25 other siblings
             // "with 24": We have 24 children. (JAWS does not read this number)
             // level
             int level = treeLevel();
             QAbstractItemModel *m = view->model();
             // totalSiblings and itemIndex
             QModelIndex parent = row.parent();
             int rowCount = m->rowCount(parent);
             int itemIndex = -1;
             int totalSiblings = 0;
             for (int i = 0 ; i < rowCount; ++i) {
                 QModelIndex sibling = row.sibling(i, 0);
                 if (!view->isIndexHidden(sibling))
                     ++totalSiblings;
                 if (row == sibling)
                     itemIndex = totalSiblings;
             }
             int totalChildren = m->rowCount(row);   // JAWS does not report child count, so we do
                                                     // this simple and efficient.
                                                     // (don't check if they are all visible).
             value = QString::fromAscii("L%1, %2 of %3 with %4").arg(level).arg(itemIndex).arg(totalSiblings).arg(totalChildren);
         } else
 #endif // QT_NO_TREEVIEW
         {
             if (!m_header) {
                 if (child == 0 && children().count() >= 1)
                     child = 1;
                 if (verticalHeader()) {
                     if (child == 1) {
                         value = view->model()->headerData(row.row(), Qt::Vertical).toString();
                     }
                     --child;
                 }
                 if (child) {
                     QModelIndex idx = childIndex(child);
                     value = idx.model()->data(idx, Qt::AccessibleDescriptionRole).toString();
                 }
             }
         }
     }
     return value;
 }
text_helper()
QString QAccessibleItemRow::text_helper (int child) const private
Definition at line 224 of file complexwidgets.cpp.
Referenced by text().
 {
     QString value;
     if (m_header) {
         if (!child)
             return QString();
         if (verticalHeader()) {
             if (child == 1)
                 return QString();
             --child;
         }
         QHeaderView *header = horizontalHeader();
         int logical = logicalFromChild(header, child);
         value = view->model()->headerData(logical, Qt::Horizontal, Qt::AccessibleTextRole).toString();
         if (value.isEmpty())
             value = view->model()->headerData(logical, Qt::Horizontal).toString();
         return value;
     } else {
         if (!child) {   // for one-column views (i.e. QListView)
             if (children().count() >= 1)
                 child = 1;
             else
                 return QString();
         }
         if (verticalHeader()) {
             if (child == 1) {
                 int logical = row.row();
                 value = view->model()->headerData(logical, Qt::Vertical, Qt::AccessibleTextRole).toString();
                 if (value.isEmpty())
                     value = view->model()->headerData(logical, Qt::Vertical).toString();
                 return value;
             } else {
                 --child;
             }
         }
     }
     if (value.isEmpty()) {
         QModelIndex idx = childIndex(child);
         if (idx.isValid()) {
             value = idx.model()->data(idx, Qt::AccessibleTextRole).toString();
             if (value.isEmpty())
                 value = idx.model()->data(idx, Qt::DisplayRole).toString();
         }
     }
     return value;
 }
toCursorAction()
QAbstractItemView::CursorAction QAccessibleItemRow::toCursorAction (Relation rel) static private
Definition at line 464 of file complexwidgets.cpp.
Referenced by navigate().
 {
     switch (rel) {
     case QAccessible::Up:
         return QAbstractItemView::MoveUp;
     case QAccessible::Down:
         return QAbstractItemView::MoveDown;
     case QAccessible::Left:
         return QAbstractItemView::MoveLeft;
     case QAccessible::Right:
         return QAbstractItemView::MoveRight;
     default:
         Q_ASSERT(false);
     }
     // should never be reached.
     return QAbstractItemView::MoveRight;
 }
treeLevel()
int QAccessibleItemRow::treeLevel () const private
Definition at line 213 of file complexwidgets.cpp.
Referenced by text().
 {
     int level = 0;
     QModelIndex idx = row;
     while (idx.isValid()) {
         idx = idx.parent();
         ++level;
     }
     return level;
 }
userActionCount()
int QAccessibleItemRow::userActionCount (int child) const virtual
Returns the number of custom actions of the object, or of the object's child if child is not 0.
The Action type enumerates predefined actions: these are not included in the returned value.
See also
actionText(), doAction()
Implements QAccessibleInterface.
Definition at line 647 of file complexwidgets.cpp.
 {
     return 0;
 }
verticalHeader()
QHeaderView * QAccessibleItemRow::verticalHeader () const private
Definition at line 122 of file complexwidgets.cpp.
Referenced by childCount(), doAction(), rect(), role(), setText(), state(), text(), and text_helper().
 {
     QHeaderView *header = 0;
 #ifndef QT_NO_TABLEVIEW
     if (const QTableView *tv = qobject_cast<const QTableView*>(view))
         header = tv->verticalHeader();
 #endif
     return header;
 }
Friends and Related Functions
QAccessibleItemView
friend class QAccessibleItemView friend
Definition at line 125 of file complexwidgets.h.
Referenced by navigate().
Properties
m_header
bool QAccessibleItemRow::m_header private
Definition at line 160 of file complexwidgets.h.
Referenced by horizontalHeader(), isValid(), role(), setText(), text(), and text_helper().
row
QPersistentModelIndex QAccessibleItemRow::row private
Definition at line 158 of file complexwidgets.h.
Referenced by children(), doAction(), indexOfChild(), QAccessibleItemView::indexOfChild(), isValid(), navigate(), ModelIndexIterator::next(), rect(), setText(), state(), text(), text_helper(), and treeLevel().
view
QPointer<QAbstractItemView> QAccessibleItemRow::view private
Definition at line 159 of file complexwidgets.h.
Referenced by childAt(), childCount(), children(), doAction(), horizontalHeader(), navigate(), rect(), relationTo(), role(), setText(), state(), text(), text_helper(), and verticalHeader().
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/complexwidgets.h
/src/plugins/accessible/widgets/complexwidgets.cpp