Qt 4.8: QEventLoop Class Reference
QEventLoop Class Reference
The QEventLoop class provides a means of entering and leaving an event loop.
#include <qeventloop.h>
Public Types
enum ProcessEventsFlag {
AllEvents = 0x00, ExcludeUserInputEvents = 0x01, ExcludeSocketNotifiers = 0x02, WaitForMoreEvents = 0x04,
X11ExcludeTimers = 0x08, DeferredDeletion = 0x10, EventLoopExec = 0x20, DialogExec = 0x40
}
This enum controls the types of events processed by the processEvents() functions.
Public Slots
void quit ()
Tells the event loop to exit normally.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
int exec (ProcessEventsFlags flags=AllEvents)
Enters the main event loop and waits until exit() is called.
void exit (int returnCode=0)
Tells the event loop to exit with a return code.
bool isRunning () const
Returns true if the event loop is running; otherwise returns false.
bool processEvents (ProcessEventsFlags flags=AllEvents)
Processes pending events that match flags until there are no more events to process.
void processEvents (ProcessEventsFlags flags, int maximumTime)
Process pending events that match flags for a maximum of maxTime milliseconds, or until there are no more events to process, whichever is shorter.
QEventLoop (QObject *parent=0)
Constructs an event loop object with the given parent.
void wakeUp ()
Wakes up the event loop.
~QEventLoop ()
Destroys the event loop object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QEventLoop class provides a means of entering and leaving an event loop.
At any time, you can create a QEventLoop object and call exec() on it to start a local event loop. From within the event loop, calling exit() will force exec() to return.
See also
QAbstractEventDispatcher
Definition at line 55 of file qeventloop.h.
Enumerations
ProcessEventsFlag
enum QEventLoop::ProcessEventsFlag
This enum controls the types of events processed by the processEvents() functions.
AllEvents All events. Note that DeferredDelete events are processed specially. See QObject::deleteLater() for more details.
ExcludeUserInputEvents Do not process user input events, such as ButtonPress and KeyPress. Note that the events are not discarded; they will be delivered the next time processEvents() is called without the ExcludeUserInputEvents flag.
ExcludeSocketNotifiers Do not process socket notifier events. Note that the events are not discarded; they will be delivered the next time processEvents() is called without the ExcludeSocketNotifiers flag.
WaitForMoreEvents Wait for events if no pending events are available.
X11ExcludeTimers
ExcludeUserInput
WaitForMore
EventLoopExec
DialogExec
DeferredDeletion deprecated - do not use.
See also
processEvents()
Enumerator
AllEvents
ExcludeUserInputEvents
ExcludeSocketNotifiers
WaitForMoreEvents
X11ExcludeTimers
DeferredDeletion
EventLoopExec
DialogExec
Definition at line 64 of file qeventloop.h.
{
         AllEvents = 0x00,
         ExcludeUserInputEvents = 0x01,
         ExcludeSocketNotifiers = 0x02,
         WaitForMoreEvents = 0x04,
 #ifdef QT3_SUPPORT
         ExcludeUserInput = ExcludeUserInputEvents,
         WaitForMore = WaitForMoreEvents,
 #endif
     X11ExcludeTimers = 0x08
 #ifdef QT_DEPRECATED
     , DeferredDeletion = 0x10
 #endif
         , EventLoopExec = 0x20
         , DialogExec = 0x40
     };
Constructors and Destructors
QEventLoop()
QEventLoop::QEventLoop (QObject * parent = 0) explicit
Constructs an event loop object with the given parent.
Definition at line 117 of file qeventloop.cpp.
     : QObject(*new QEventLoopPrivate, parent)
 {
     Q_D(QEventLoop);
     if (!QCoreApplication::instance()) {
         qWarning("QEventLoop: Cannot be used without QApplication");
     } else if (!d->threadData->eventDispatcher) {
         QThreadPrivate::createEventDispatcher(d->threadData);
     }
 }
~QEventLoop()
QEventLoop::~QEventLoop ()
Destroys the event loop object.
Definition at line 131 of file qeventloop.cpp.
 { }
Functions
exec()
int QEventLoop::exec (ProcessEventsFlags flags = AllEvents)
Enters the main event loop and waits until exit() is called.
Returns the value that was passed to exit().
If flags are specified, only events of the types allowed by the flags will be processed.
It is necessary to call this function to start event handling. The main event loop receives events from the window system and dispatches these to the application widgets.
Generally speaking, no user interaction can take place before calling exec(). As a special case, modal widgets like QMessageBox can be used before calling exec(), because modal widgets use their own local event loop.
To make your application perform idle processing (i.e. executing a special function whenever there are no pending events), use a QTimer with 0 timeout. More sophisticated idle processing schemes can be achieved using processEvents().
See also
QApplication::quit(), exit(), processEvents()
Definition at line 181 of file qeventloop.cpp.
Referenced by QTestEventLoop::enterLoop(), QScriptEngineDebuggerBackend::event(), QThread::exec(), QCoreApplication::exec(), QCoreApplication::hasPendingEvents(), QMenuPrivate::hideMenu(), QComboBox::hidePopup(), QMenuPrivate::hideUpToMenuBar(), QDBusConnectionPrivate::sendWithReply(), QHttpThreadDelegate::startRequestSynchronously(), and QNetworkSession::waitForOpened().
 {
     Q_D(QEventLoop);
     //we need to protect from race condition with QThread::exit
     QMutexLocker locker(&static_cast<QThreadPrivate *>(QObjectPrivate::get(d->threadData->thread))->mutex);
     if (d->threadData->quitNow)
         return -1;
     if (d->inExec) {
         qWarning("QEventLoop::exec: instance %p has already called exec()", this);
         return -1;
     }
     d->inExec = true;
     d->exit = false;
     ++d->threadData->loopLevel;
     d->threadData->eventLoops.push(this);
     locker.unlock();
     // remove posted quit events when entering a new event loop
     QCoreApplication *app = QCoreApplication::instance();
     if (app && app->thread() == thread())
         QCoreApplication::removePostedEvents(app, QEvent::Quit);
 #if defined(QT_NO_EXCEPTIONS)
     while (!d->exit)
         processEvents(flags | WaitForMoreEvents | EventLoopExec);
 #else
     try {
         while (!d->exit)
             processEvents(flags | WaitForMoreEvents | EventLoopExec);
     } catch (...) {
         qWarning("Qt has caught an exception thrown from an event handler. Throwing\n"
                  "exceptions from an event handler is not supported in Qt. You must\n"
                  "reimplement QApplication::notify() and catch all exceptions there.\n");
         // copied from below
         locker.relock();
         QEventLoop *eventLoop = d->threadData->eventLoops.pop();
         Q_ASSERT_X(eventLoop == this, "QEventLoop::exec()", "internal error");
         Q_UNUSED(eventLoop); // --release warning
         d->inExec = false;
         --d->threadData->loopLevel;
         throw;
     }
 #endif
     // copied above
     locker.relock();
     QEventLoop *eventLoop = d->threadData->eventLoops.pop();
     Q_ASSERT_X(eventLoop == this, "QEventLoop::exec()", "internal error");
     Q_UNUSED(eventLoop); // --release warning
     d->inExec = false;
     --d->threadData->loopLevel;
     return d->returnCode;
 }
exit()
void QEventLoop::exit (int returnCode = 0)
Tells the event loop to exit with a return code.
After this function has been called, the event loop returns from the call to exec(). The exec() function returns returnCode.
By convention, a returnCode of 0 means success, and any non-zero value indicates an error.
Note that unlike the C library function of the same name, this function does return to the caller – it is event processing that stops.
See also
QCoreApplication::quit(), quit(), exec()
Definition at line 288 of file qeventloop.cpp.
Referenced by QPatternist::NetworkLoop::error(), QThread::exit(), QCoreApplication::exit(), QTestEventLoop::exitLoop(), QPatternist::NetworkLoop::finished(), QCoreApplication::hasPendingEvents(), and quit().
 {
     Q_D(QEventLoop);
     if (!d->threadData->eventDispatcher)
         return;
     d->returnCode = returnCode;
     d->exit = true;
     d->threadData->eventDispatcher->interrupt();
 }
isRunning()
bool QEventLoop::isRunning () const
Returns true if the event loop is running; otherwise returns false.
The event loop is considered running from the time when exec() is called until exit() is called.
See also
exec() exit()
Definition at line 306 of file qeventloop.cpp.
Referenced by QScriptEngineDebuggerBackend::event(), QScriptEngineDebuggerBackend::resume(), and QScriptEngineDebuggerBackendPrivate::~QScriptEngineDebuggerBackendPrivate().
 {
     Q_D(const QEventLoop);
     return !d->exit;
 }
processEvents() [1/2]
bool QEventLoop::processEvents (ProcessEventsFlags flags = AllEvents)
Processes pending events that match flags until there are no more events to process.
Returns true if pending events were handled; otherwise returns false.
This function is especially useful if you have a long running operation and want to show its progress without allowing user input; i.e. by using the ExcludeUserInputEvents flag.
This function is simply a wrapper for QAbstractEventDispatcher::processEvents(). See the documentation for that function for details.
Definition at line 148 of file qeventloop.cpp.
Referenced by exec(), and processEvents().
 {
     Q_D(QEventLoop);
     if (!d->threadData->eventDispatcher)
         return false;
     if (flags & DeferredDeletion)
         QCoreApplication::sendPostedEvents(0, QEvent::DeferredDelete);
     return d->threadData->eventDispatcher->processEvents(flags);
 }
processEvents() [2/2]
void QEventLoop::processEvents (ProcessEventsFlags flags, int maxTime)
Process pending events that match flags for a maximum of maxTime milliseconds, or until there are no more events to process, whichever is shorter.
This function is especially useful if you have a long running operation and want to show its progress without allowing user input, i.e. by using the ExcludeUserInputEvents flag.
Notes:
This function does not process events continuously; it returns after all available events are processed.
Specifying the WaitForMoreEvents flag makes no sense and will be ignored.
Definition at line 255 of file qeventloop.cpp.
 {
     Q_D(QEventLoop);
     if (!d->threadData->eventDispatcher)
         return;
     QElapsedTimer start;
     start.start();
     if (flags & DeferredDeletion)
         QCoreApplication::sendPostedEvents(0, QEvent::DeferredDelete);
     while (processEvents(flags & ~WaitForMoreEvents)) {
         if (start.elapsed() > maxTime)
             break;
         if (flags & DeferredDeletion)
             QCoreApplication::sendPostedEvents(0, QEvent::DeferredDelete);
     }
 }
quit
void QEventLoop::quit () slot
Tells the event loop to exit normally.
Same as exit(0).
See also
QCoreApplication::quit(), exit()
Definition at line 332 of file qeventloop.cpp.
Referenced by QScriptEngineDebuggerBackend::resume(), and QScriptEngineDebuggerBackendPrivate::~QScriptEngineDebuggerBackendPrivate().
 { exit(0); }
wakeUp()
void QEventLoop::wakeUp ()
Wakes up the event loop.
See also
QAbstractEventDispatcher::wakeUp()
Definition at line 317 of file qeventloop.cpp.
 {
     Q_D(QEventLoop);
     if (!d->threadData->eventDispatcher)
         return;
     d->threadData->eventDispatcher->wakeUp();
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qeventloop.h
/src/corelib/kernel/qeventloop.cpp