Qt 4.8: QGraphicsLinearLayoutPrivate Class Reference
QGraphicsLinearLayoutPrivate Class Reference
Public Functions
void fixIndex (int *index) const
int gridColumn (int index) const
int gridRow (int index) const
QGraphicsLinearLayoutPrivate (Qt::Orientation orientation)
void removeGridItem (QGridLayoutItem *gridItem)
QLayoutStyleInfo styleInfo () const
Public Functions inherited from QGraphicsLayoutPrivate
void activateRecursive (QGraphicsLayoutItem *item)
void addChildLayoutItem (QGraphicsLayoutItem *item)
This function is called from subclasses to add a layout item layoutItem to a layout.
void getMargin (qreal *result, qreal userMargin, QStyle::PixelMetric pm) const
QGraphicsLayoutPrivate ()
void reparentChildItems (QGraphicsItem *newParent)
Qt::LayoutDirection visualDirection () const
Public Functions inherited from QGraphicsLayoutItemPrivate
QSizeF * effectiveSizeHints (const QSizeF &constraint) const
void ensureUserSizeHints ()
Ensures that userSizeHints is allocated.
bool hasHeightForWidth () const
bool hasWidthForHeight () const
void init ()
QGraphicsItem * parentItem () const
Returns the parent item of this layout, or 0 if this layout is not installed on any widget.
QGraphicsLayoutItemPrivate (QGraphicsLayoutItem *parent, bool isLayout)
void setSize (Qt::SizeHint which, const QSizeF &size)
Sets the user size hint which to size.
void setSizeComponent (Qt::SizeHint which, SizeComponent component, qreal value)
Sets the width of the user size hint which to width.
virtual ~QGraphicsLayoutItemPrivate ()
Public Variables
QGridLayoutEngine engine
Qt::Orientation orientation
Public Variables inherited from QGraphicsLayoutPrivate
bool activated
qreal bottom
qreal left
qreal right
qreal top
Public Variables inherited from QGraphicsLayoutItemPrivate
QSizeF cachedConstraint
QSizeF cachedSizeHints [Qt::NSizeHints]
QSizeF cachedSizeHintsWithConstraints [Qt::NSizeHints]
QRectF geom
QGraphicsItem * graphicsItem
quint32 isLayout: 1
quint32 ownedByLayout: 1
QGraphicsLayoutItem * parent
QGraphicsLayoutItem * q_ptr
quint32 sizeHintCacheDirty: 1
quint32 sizeHintWithConstraintCacheDirty: 1
QSizePolicy sizePolicy
QSizeF * userSizeHints
Additional Inherited Members
Public Types inherited from QGraphicsLayoutItemPrivate
enum SizeComponent { Width, Height }
Static Public Functions inherited from QGraphicsLayoutItemPrivate
static QGraphicsLayoutItemPrivate * get (QGraphicsLayoutItem *q)
static const QGraphicsLayoutItemPrivate * get (const QGraphicsLayoutItem *q)
Detailed Description
Definition at line 134 of file qgraphicslinearlayout.cpp.
Constructors and Destructors
QGraphicsLinearLayoutPrivate()
QGraphicsLinearLayoutPrivate::QGraphicsLinearLayoutPrivate (Qt::Orientation orientation) inline
Definition at line 137 of file qgraphicslinearlayout.cpp.
 : orientation(orientation) { }
Functions
fixIndex()
void QGraphicsLinearLayoutPrivate::fixIndex (int * index) const
Definition at line 156 of file qgraphicslinearlayout.cpp.
Referenced by QGraphicsLinearLayoutPrivate().
 {
     int count = engine.rowCount(orientation);
     if (uint(*index) > uint(count))
         *index = count;
 }
gridColumn()
int QGraphicsLinearLayoutPrivate::gridColumn (int index) const
Definition at line 170 of file qgraphicslinearlayout.cpp.
Referenced by QGraphicsLinearLayoutPrivate().
 {
     if (orientation == Qt::Vertical)
         return 0;
     return int(qMin(uint(index), uint(engine.columnCount())));
 }
gridRow()
int QGraphicsLinearLayoutPrivate::gridRow (int index) const
Definition at line 163 of file qgraphicslinearlayout.cpp.
Referenced by QGraphicsLinearLayoutPrivate().
 {
     if (orientation == Qt::Horizontal)
         return 0;
     return int(qMin(uint(index), uint(engine.rowCount())));
 }
removeGridItem()
void QGraphicsLinearLayoutPrivate::removeGridItem (QGridLayoutItem * gridItem)
Definition at line 149 of file qgraphicslinearlayout.cpp.
Referenced by QGraphicsLinearLayoutPrivate().
 {
     int index = gridItem->firstRow(orientation);
     engine.removeItem(gridItem);
     engine.removeRows(index, 1, orientation);
 }
styleInfo()
QLayoutStyleInfo QGraphicsLinearLayoutPrivate::styleInfo () const
Definition at line 179 of file qgraphicslinearlayout.cpp.
Referenced by QGraphicsLinearLayoutPrivate().
 {
     QGraphicsItem *item = parentItem();
     QStyle *style = (item && item->isWidget()) ? static_cast<QGraphicsWidget*>(item)->style() : QApplication::style();
     return QLayoutStyleInfo(style, globalStyleInfoWidget());
 }
Properties
engine
QGridLayoutEngine QGraphicsLinearLayoutPrivate::engine
Definition at line 146 of file qgraphicslinearlayout.cpp.
Referenced by fixIndex(), gridColumn(), gridRow(), and removeGridItem().
orientation
Qt::Orientation QGraphicsLinearLayoutPrivate::orientation
Definition at line 145 of file qgraphicslinearlayout.cpp.
Referenced by fixIndex(), gridColumn(), gridRow(), and removeGridItem().
The documentation for this class was generated from the following file:
/src/gui/graphicsview/qgraphicslinearlayout.cpp