Qt 4.8: QStandardItemModel Class Reference
QStandardItemModel Class Reference
The QStandardItemModel class provides a generic model for storing custom data.
#include <qstandarditemmodel.h>
Signals
void itemChanged (QStandardItem *item)
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void appendColumn (const QList< QStandardItem *> &items)
Appends a column containing items.
void appendRow (const QList< QStandardItem *> &items)
Appends a row containing items.
void appendRow (QStandardItem *item)
void clear ()
Removes all items (including header items) from the model and sets the number of rows and columns to zero.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QList< QStandardItem * > findItems (const QString &text, Qt::MatchFlags flags=Qt::MatchExactly, int column=0) const
Returns a list of items that match the given text, using the given flags, in the given column.
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Reimplemented Function
QStandardItem * horizontalHeaderItem (int column) const
Returns the horizontal header item for column if one has been set; otherwise returns 0.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QModelIndex indexFromItem (const QStandardItem *item) const
Returns the QModelIndex associated with the given item.
void insertColumn (int column, const QList< QStandardItem *> &items)
Inserts a column at column containing items.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
void insertRow (int row, const QList< QStandardItem *> &items)
Inserts a row at row containing items.
void insertRow (int row, QStandardItem *item)
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
QStandardItem * invisibleRootItem () const
Returns the model's invisible root item.
QStandardItem * item (int row, int column=0) const
Returns the item for the given row and column if one has been set; otherwise returns 0.
QMap< int, QVariant > itemData (const QModelIndex &index) const
Reimplemented Function
QStandardItem * itemFromIndex (const QModelIndex &index) const
Returns a pointer to the QStandardItem associated with the given index.
const QStandardItem * itemPrototype () const
Returns the item prototype used by the model.
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QStandardItemModel (QObject *parent=0)
Constructs a new item model with the given parent.
QStandardItemModel (int rows, int columns, QObject *parent=0)
Constructs a new item model that initially has rows rows and columns columns, and that has the given parent.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void setColumnCount (int columns)
Sets the number of columns in this model to columns.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
void setHorizontalHeaderItem (int column, QStandardItem *item)
Sets the horizontal header item for column to item.
void setHorizontalHeaderLabels (const QStringList &labels)
Sets the horizontal header labels using labels.
void setItem (int row, int column, QStandardItem *item)
Sets the item for the given row and column to item.
void setItem (int row, QStandardItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Reimplemented Function
void setItemPrototype (const QStandardItem *item)
Sets the item prototype for the model to the specified item.
void setRowCount (int rows)
Sets the number of rows in this model to rows.
void setSortRole (int role)
void setVerticalHeaderItem (int row, QStandardItem *item)
Sets the vertical header item for row to item.
void setVerticalHeaderLabels (const QStringList &labels)
Sets the vertical header labels using labels.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
int sortRole () const
Qt::DropActions supportedDropActions () const
QStandardItemModel supports both copy and move.
QList< QStandardItem * > takeColumn (int column)
Removes the given column without deleting the column items, and returns a list of pointers to the removed items.
QStandardItem * takeHorizontalHeaderItem (int column)
Removes the horizontal header item at column from the header without deleting it, and returns a pointer to the item.
QStandardItem * takeItem (int row, int column=0)
Removes the item at (row, column) without deleting it.
QList< QStandardItem * > takeRow (int row)
Removes the given row without deleting the row items, and returns a list of pointers to the removed items.
QStandardItem * takeVerticalHeaderItem (int row)
Removes the vertical header item at row from the header without deleting it, and returns a pointer to the item.
QStandardItem * verticalHeaderItem (int row) const
Returns the vertical header item for row row if one has been set; otherwise returns 0.
~QStandardItemModel ()
Destructs the model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QStandardItemModel (QStandardItemModelPrivate &dd, QObject *parent=0)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int sortRole
the item role that is used to query the model's data when sorting items
Friends
class QStandardItem
class QStandardItemPrivate
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QStandardItemModel class provides a generic model for storing custom data.
QStandardItemModel can be used as a repository for standard Qt data types. It is one of the Model/View Classes and is part of Qt's Model/View Programming framework.
QStandardItemModel provides a classic item-based approach to working with the model. The items in a QStandardItemModel are provided by QStandardItem.
QStandardItemModel implements the QAbstractItemModel interface, which means that the model can be used to provide data in any view that supports that interface (such as QListView, QTableView and QTreeView, and your own custom views). For performance and flexibility, you may want to subclass QAbstractItemModel to provide support for different kinds of data repositories. For example, the QDirModel provides a model interface to the underlying file system.
When you want a list or tree, you typically create an empty QStandardItemModel and use appendRow() to add items to the model, and item() to access an item. If your model represents a table, you typically pass the dimensions of the table to the QStandardItemModel constructor and use setItem() to position items into the table. You can also use setRowCount() and setColumnCount() to alter the dimensions of the model. To insert items, use insertRow() or insertColumn(), and to remove items, use removeRow() or removeColumn().
You can set the header labels of your model with setHorizontalHeaderLabels() and setVerticalHeaderLabels().
You can search for items in the model with findItems(), and sort the model by calling sort().
Call clear() to remove all items from the model.
An example usage of QStandardItemModel to create a table:
QStandardItemModel model(4, 4);
for (int row = 0; row < 4; ++row) {
    for (int column = 0; column < 4; ++column) {
        QStandardItem *item = new QStandardItem(QString("row %0, column %1").arg(row).arg(column));
        model.setItem(row, column, item);
    }
}
An example usage of QStandardItemModel to create a tree:
QStandardItemModel model;
QStandardItem *parentItem = model.invisibleRootItem();
for (int i = 0; i < 4; ++i) {
    QStandardItem *item = new QStandardItem(QString("item %0").arg(i));
    parentItem->appendRow(item);
    parentItem = item;
}
After setting the model on a view, you typically want to react to user actions, such as an item being clicked. Since a QAbstractItemView provides QModelIndex-based signals and functions, you need a way to obtain the QStandardItem that corresponds to a given QModelIndex, and vice versa. itemFromIndex() and indexFromItem() provide this mapping. Typical usage of itemFromIndex() includes obtaining the item at the current index in a view, and obtaining the item that corresponds to an index carried by a QAbstractItemView signal, such as QAbstractItemView::clicked(). First you connect the view's signal to a slot in your class:
QTreeView *treeView = new QTreeView(this);
treeView->setModel(myStandardItemModel);
connect(treeView, SIGNAL(clicked(QModelIndex)),
        this, SLOT(clicked(QModelIndex)));
When you receive the signal, you call itemFromIndex() on the given model index to get a pointer to the item:
void MyWidget::clicked(const QModelIndex &index)
{
    QStandardItem *item = myStandardItemModel->itemFromIndex(index);
    // Do stuff with the item ...
}
Conversely, you must obtain the QModelIndex of an item when you want to invoke a model/view function that takes an index as argument. You can obtain the index either by using the model's indexFromItem() function, or, equivalently, by calling QStandardItem::index():
treeView->scrollTo(item->index());
You are, of course, not required to use the item-based approach; you could instead rely entirely on the QAbstractItemModel interface when working with the model, or use a combination of the two as appropriate.
See also
QStandardItem, {Model/View Programming}, QAbstractItemModel, {itemviews/simpletreemodel}{Simple Tree Model example}, {Item View Convenience Classes}
Definition at line 318 of file qstandarditemmodel.h.
Constructors and Destructors
QStandardItemModel() [1/3]
QStandardItemModel::QStandardItemModel (QObject * parent = 0) explicit
Constructs a new item model with the given parent.
Definition at line 2162 of file qstandarditemmodel.cpp.
     : QAbstractItemModel(*new QStandardItemModelPrivate, parent)
 {
     Q_D(QStandardItemModel);
     d->init();
     d->root->d_func()->setModel(this);
 }
QStandardItemModel() [2/3]
QStandardItemModel::QStandardItemModel (int rows, int columns, QObject * parent = 0)
Constructs a new item model that initially has rows rows and columns columns, and that has the given parent.
Definition at line 2174 of file qstandarditemmodel.cpp.
     : QAbstractItemModel(*new QStandardItemModelPrivate, parent)
 {
     Q_D(QStandardItemModel);
     d->init();
     d->root->insertColumns(0, columns);
     d->columnHeaderItems.insert(0, columns, 0);
     d->root->insertRows(0, rows);
     d->rowHeaderItems.insert(0, rows, 0);
     d->root->d_func()->setModel(this);
 }
~QStandardItemModel()
QStandardItemModel::~QStandardItemModel ()
Destructs the model.
The model destroys all its items.
Definition at line 2199 of file qstandarditemmodel.cpp.
 {
 }
QStandardItemModel() [3/3]
QStandardItemModel::QStandardItemModel (QStandardItemModelPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 2189 of file qstandarditemmodel.cpp.
     : QAbstractItemModel(dd, parent)
 {
     Q_D(QStandardItemModel);
     d->init();
 }
Functions
appendColumn()
void QStandardItemModel::appendColumn (const QList< QStandardItem *> & items)
Appends a column containing items.
Since
4.2
If necessary, the row count is increased to the size of items.
See also
insertColumn(), appendRow()
Definition at line 2651 of file qstandarditemmodel.cpp.
 {
     invisibleRootItem()->appendColumn(items);
 }
appendRow() [1/2]
void QStandardItemModel::appendRow (const QList< QStandardItem *> & items)
Appends a row containing items.
Since
4.2
If necessary, the column count is increased to the size of items.
See also
insertRow(), appendColumn()
Definition at line 2635 of file qstandarditemmodel.cpp.
 {
     invisibleRootItem()->appendRow(items);
 }
appendRow() [2/2]
void QStandardItemModel::appendRow (QStandardItem * item) inline
Since
4.2
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
When building a list or a tree that has only one column, this function provides a convenient way to append a single new item.
Definition at line 434 of file qstandarditemmodel.h.
 { appendRow(QList<QStandardItem*>() << aitem); }
clear()
void QStandardItemModel::clear ()
Removes all items (including header items) from the model and sets the number of rows and columns to zero.
See also
removeColumns(), removeRows()
Definition at line 2209 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::setFileSystemModel().
 {
     Q_D(QStandardItemModel);
     d->root.reset(new QStandardItem);
     d->root->d_func()->setModel(this);
     qDeleteAll(d->columnHeaderItems);
     d->columnHeaderItems.clear();
     qDeleteAll(d->rowHeaderItems);
     d->rowHeaderItems.clear();
     reset();
 }
columnCount()
int QStandardItemModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 2841 of file qstandarditemmodel.cpp.
Referenced by dropMimeData(), headerData(), horizontalHeaderItem(), setHeaderData(), setHorizontalHeaderItem(), setHorizontalHeaderLabels(), and takeHorizontalHeaderItem().
 {
     Q_D(const QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(parent);
     return item ? item->columnCount() : 0;
 }
data()
QVariant QStandardItemModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 2851 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::addUrls(), QUrlModel::mimeData(), mimeData(), and QUrlModel::urls().
 {
     Q_D(const QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(index);
     return item ? item->data(role) : QVariant();
 }
dropMimeData()
bool QStandardItemModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3199 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     // check if the action is supported
     if (!data || !(action == Qt::CopyAction || action == Qt::MoveAction))
         return false;
     // check if the format is supported
     QString format = QLatin1String("application/x-qstandarditemmodeldatalist");
     if (!data->hasFormat(format))
         return QAbstractItemModel::dropMimeData(data, action, row, column, parent);
     if (row > rowCount(parent))
         row = rowCount(parent);
     if (row == -1)
         row = rowCount(parent);
     if (column == -1)
         column = 0;
     // decode and insert
     QByteArray encoded = data->data(format);
     QDataStream stream(&encoded, QIODevice::ReadOnly);
     //code based on QAbstractItemModel::decodeData
     // adapted to work with QStandardItem
     int top = INT_MAX;
     int left = INT_MAX;
     int bottom = 0;
     int right = 0;
     QVector<int> rows, columns;
     QVector<QStandardItem *> items;
     while (!stream.atEnd()) {
         int r, c;
         QStandardItem *item = d->createItem();
         stream >> r >> c;
         d->decodeDataRecursive(stream, item);
         rows.append(r);
         columns.append(c);
         items.append(item);
         top = qMin(r, top);
         left = qMin(c, left);
         bottom = qMax(r, bottom);
         right = qMax(c, right);
     }
     // insert the dragged items into the table, use a bit array to avoid overwriting items,
     // since items from different tables can have the same row and column
     int dragRowCount = 0;
     int dragColumnCount = right - left + 1;
     // Compute the number of continuous rows upon insertion and modify the rows to match
     QVector<int> rowsToInsert(bottom + 1);
     for (int i = 0; i < rows.count(); ++i)
         rowsToInsert[rows.at(i)] = 1;
     for (int i = 0; i < rowsToInsert.count(); ++i) {
         if (rowsToInsert[i] == 1){
             rowsToInsert[i] = dragRowCount;
             ++dragRowCount;
         }
     }
     for (int i = 0; i < rows.count(); ++i)
         rows[i] = top + rowsToInsert[rows[i]];
     QBitArray isWrittenTo(dragRowCount * dragColumnCount);
     // make space in the table for the dropped data
     int colCount = columnCount(parent);
     if (colCount < dragColumnCount + column) {
         insertColumns(colCount, dragColumnCount + column - colCount, parent);
         colCount = columnCount(parent);
     }
     insertRows(row, dragRowCount, parent);
     row = qMax(0, row);
     column = qMax(0, column);
     QStandardItem *parentItem = itemFromIndex (parent);
     if (!parentItem)
         parentItem = invisibleRootItem();
     QVector<QPersistentModelIndex> newIndexes(items.size());
     // set the data in the table
     for (int j = 0; j < items.size(); ++j) {
         int relativeRow = rows.at(j) - top;
         int relativeColumn = columns.at(j) - left;
         int destinationRow = relativeRow + row;
         int destinationColumn = relativeColumn + column;
         int flat = (relativeRow * dragColumnCount) + relativeColumn;
         // if the item was already written to, or we just can't fit it in the table, create a new row
         if (destinationColumn >= colCount || isWrittenTo.testBit(flat)) {
             destinationColumn = qBound(column, destinationColumn, colCount - 1);
             destinationRow = row + dragRowCount;
             insertRows(row + dragRowCount, 1, parent);
             flat = (dragRowCount * dragColumnCount) + relativeColumn;
             isWrittenTo.resize(++dragRowCount * dragColumnCount);
         }
         if (!isWrittenTo.testBit(flat)) {
             newIndexes[j] = index(destinationRow, destinationColumn, parentItem->index());
             isWrittenTo.setBit(flat);
         }
     }
     for(int k = 0; k < newIndexes.size(); k++) {
         if (newIndexes.at(k).isValid()) {
             parentItem->setChild(newIndexes.at(k).row(), newIndexes.at(k).column(), items.at(k));
         } else {
             delete items.at(k);
         }
     }
     return true;
 }
findItems()
QList< QStandardItem * > QStandardItemModel::findItems (const QString & text, Qt::MatchFlags flags = Qt::MatchExactly, int column = 0) const
Returns a list of items that match the given text, using the given flags, in the given column.
Since
4.2
Definition at line 2613 of file qstandarditemmodel.cpp.
 {
     QModelIndexList indexes = match(index(0, column, QModelIndex()),
                                     Qt::DisplayRole, text, -1, flags);
     QList<QStandardItem*> items;
     for (int i = 0; i < indexes.size(); ++i)
         items.append(itemFromIndex(indexes.at(i)));
     return items;
 }
flags()
Qt::ItemFlags QStandardItemModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2861 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::flags(), and QFileDialogComboBox::showPopup().
 {
     Q_D(const QStandardItemModel);
     if (!d->indexValid(index))
         return d->root->flags();
     QStandardItem *item = d->itemFromIndex(index);
     if (item)
         return item->flags();
     return Qt::ItemIsSelectable
         |Qt::ItemIsEnabled
         |Qt::ItemIsEditable
         |Qt::ItemIsDragEnabled
         |Qt::ItemIsDropEnabled;
 }
hasChildren()
bool QStandardItemModel::hasChildren (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2879 of file qstandarditemmodel.cpp.
 {
     Q_D(const QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(parent);
     return item ? item->hasChildren() : false;
 }
headerData()
QVariant QStandardItemModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2889 of file qstandarditemmodel.cpp.
 {
     Q_D(const QStandardItemModel);
     if ((section < 0)
         || ((orientation == Qt::Horizontal) && (section >= columnCount()))
         || ((orientation == Qt::Vertical) && (section >= rowCount()))) {
         return QVariant();
     }
     QStandardItem *headerItem = 0;
     if (orientation == Qt::Horizontal)
         headerItem = d->columnHeaderItems.at(section);
     else if (orientation == Qt::Vertical)
         headerItem = d->rowHeaderItems.at(section);
     return headerItem ? headerItem->data(role)
         : QAbstractItemModel::headerData(section, orientation, role);
 }
horizontalHeaderItem()
QStandardItem * QStandardItemModel::horizontalHeaderItem (int column) const
Returns the horizontal header item for column if one has been set; otherwise returns 0.
Since
4.2
See also
setHorizontalHeaderItem(), verticalHeaderItem()
Definition at line 2437 of file qstandarditemmodel.cpp.
Referenced by setHorizontalHeaderLabels().
 {
     Q_D(const QStandardItemModel);
     if ((column < 0) || (column >= columnCount()))
         return 0;
     return d->columnHeaderItems.at(column);
 }
index()
QModelIndex QStandardItemModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 2922 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::addUrls(), QUrlModel::changed(), QUrlModel::dataChanged(), dropMimeData(), findItems(), and QUrlModel::urls().
 {
     Q_D(const QStandardItemModel);
     QStandardItem *parentItem = d->itemFromIndex(parent);
     if ((parentItem == 0)
         || (row < 0)
         || (column < 0)
         || (row >= parentItem->rowCount())
         || (column >= parentItem->columnCount())) {
         return QModelIndex();
     }
     return createIndex(row, column, parentItem);
 }
indexFromItem()
QModelIndex QStandardItemModel::indexFromItem (const QStandardItem * item) const
Returns the QModelIndex associated with the given item.
Since
4.2
Use this function when you want to perform an operation that requires the QModelIndex of the item, such as QAbstractItemView::scrollTo(). QStandardItem::index() is provided as convenience; it is equivalent to calling this function.
See also
itemFromIndex(), QStandardItem::index()
Definition at line 2275 of file qstandarditemmodel.cpp.
Referenced by parent(), and QStandardItemPrivate::setModel().
 {
     if (item && item->d_func()->parent) {
         QPair<int, int> pos = item->d_func()->position();
         return createIndex(pos.first, pos.second, item->d_func()->parent);
     }
     return QModelIndex();
 }
insertColumn() [1/2]
void QStandardItemModel::insertColumn (int column, const QList< QStandardItem *> & items)
Inserts a column at column containing items.
Since
4.2
If necessary, the row count is increased to the size of items.
See also
takeColumn(), appendColumn(), insertRow()
Definition at line 2704 of file qstandarditemmodel.cpp.
 {
     invisibleRootItem()->insertColumn(column, items);
 }
insertColumn() [2/2]
bool QStandardItemModel::insertColumn (int column, const QModelIndex & parent = QModelIndex()) inline
Inserts a single column before the given column in the child items of the parent specified.
Returns true if the column is inserted; otherwise returns false.
See also
insertColumns(), insertRow(), removeColumn()
Definition at line 442 of file qstandarditemmodel.h.
 { return QAbstractItemModel::insertColumn(acolumn, aparent); }
insertColumns()
bool QStandardItemModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2939 of file qstandarditemmodel.cpp.
Referenced by dropMimeData(), and QUrlModel::setFileSystemModel().
 {
     Q_D(QStandardItemModel);
     QStandardItem *item = parent.isValid() ? itemFromIndex(parent) : d->root.data();
     if (item == 0)
         return false;
     return item->d_func()->insertColumns(column, count, QList<QStandardItem*>());
 }
insertRow() [1/3]
void QStandardItemModel::insertRow (int row, const QList< QStandardItem *> & items)
Inserts a row at row containing items.
Since
4.2
If necessary, the column count is increased to the size of items.
See also
takeRow(), appendRow(), insertColumn()
Definition at line 2676 of file qstandarditemmodel.cpp.
 {
     invisibleRootItem()->insertRow(row, items);
 }
insertRow() [2/3]
void QStandardItemModel::insertRow (int row, QStandardItem * item) inline
Since
4.2
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Inserts a row at row containing item.
When building a list or a tree that has only one column, this function provides a convenient way to append a single new item.
Definition at line 437 of file qstandarditemmodel.h.
 { insertRow(arow, QList<QStandardItem*>() << aitem); }
insertRow() [3/3]
bool QStandardItemModel::insertRow (int row, const QModelIndex & parent = QModelIndex()) inline
Inserts a single row before the given row in the child items of the parent specified.
Returns true if the row is inserted; otherwise returns false.
See also
insertRows(), insertColumn(), removeRow()
Definition at line 440 of file qstandarditemmodel.h.
 { return QAbstractItemModel::insertRow(arow, aparent); }
insertRows()
bool QStandardItemModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2951 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::addUrls(), and dropMimeData().
 {
     Q_D(QStandardItemModel);
     QStandardItem *item = parent.isValid() ? itemFromIndex(parent) : d->root.data();
     if (item == 0)
         return false;
     return item->d_func()->insertRows(row, count, QList<QStandardItem*>());
 }
invisibleRootItem()
QStandardItem * QStandardItemModel::invisibleRootItem () const
Returns the model's invisible root item.
Since
4.2
The invisible root item provides access to the model's top-level items through the QStandardItem API, making it possible to write functions that can treat top-level items and their children in a uniform way; for example, recursive functions involving a tree model.
Note
Calling index() on the QStandardItem object retrieved from this function is not valid.
Definition at line 2377 of file qstandarditemmodel.cpp.
Referenced by appendColumn(), appendRow(), dropMimeData(), insertColumn(), and insertRow().
 {
     Q_D(const QStandardItemModel);
     return d->root.data();
 }
item()
QStandardItem * QStandardItemModel::item (int row, int column = 0) const
Returns the item for the given row and column if one has been set; otherwise returns 0.
Since
4.2
See also
setItem(), takeItem(), itemFromIndex()
Definition at line 2355 of file qstandarditemmodel.cpp.
Referenced by columnCount(), data(), QStandardItemModelPrivate::decodeDataRecursive(), dropMimeData(), flags(), hasChildren(), insertColumns(), insertRows(), itemData(), itemFromIndex(), mimeData(), removeColumns(), removeRows(), rowCount(), setData(), setHorizontalHeaderLabels(), setItemData(), setItemPrototype(), setVerticalHeaderLabels(), and QFileDialogComboBox::showPopup().
 {
     Q_D(const QStandardItemModel);
     return d->root->child(row, column);
 }
itemChanged
void QStandardItemModel::itemChanged (QStandardItem * item) signal
Since
4.2
This signal is emitted whenever the data of item has changed.
itemData()
QMap< int, QVariant > QStandardItemModel::itemData (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2963 of file qstandarditemmodel.cpp.
 {
     Q_D(const QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(index);
     return item ? item->d_func()->itemData() : QMap<int, QVariant>();
 }
itemFromIndex()
QStandardItem * QStandardItemModel::itemFromIndex (const QModelIndex & index) const
Returns a pointer to the QStandardItem associated with the given index.
Since
4.2
Calling this function is typically the initial step when processing QModelIndex-based signals from a view, such as QAbstractItemView::activated(). In your slot, you call itemFromIndex(), with the QModelIndex carried by the signal as argument, to obtain a pointer to the corresponding QStandardItem.
Note that this function will lazily create an item for the index (using itemPrototype()), and set it in the parent item's child table, if no item already exists at that index.
If index is an invalid index, this function returns 0.
See also
indexFromItem()
Definition at line 2243 of file qstandarditemmodel.cpp.
Referenced by dropMimeData(), findItems(), insertColumns(), insertRows(), mimeData(), setData(), and setItemData().
 {
     Q_D(const QStandardItemModel);
     if ((index.row() < 0) || (index.column() < 0) || (index.model() != this))
         return 0;
     QStandardItem *parent = static_cast<QStandardItem*>(index.internalPointer());
     if (parent == 0)
         return 0;
     QStandardItem *item = parent->child(index.row(), index.column());
     // lazy part
     if (item == 0) {
         item = d->createItem();
         parent->d_func()->setChild(index.row(), index.column(), item);
     }
     return item;
 }
itemPrototype()
const QStandardItem * QStandardItemModel::itemPrototype () const
Returns the item prototype used by the model.
Since
4.2
The model uses the item prototype as an item factory when it needs to construct new items on demand (for instance, when a view or item delegate calls setData()).
See also
setItemPrototype()
Definition at line 2598 of file qstandarditemmodel.cpp.
 {
     Q_D(const QStandardItemModel);
     return d->itemPrototype;
 }
mimeData()
QMimeData * QStandardItemModel::mimeData (const QModelIndexList & indexes) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3104 of file qstandarditemmodel.cpp.
 {
     QMimeData *data = QAbstractItemModel::mimeData(indexes);
     if(!data)
         return 0;
     QString format = QLatin1String("application/x-qstandarditemmodeldatalist");
     if (!mimeTypes().contains(format))
         return data;
     QByteArray encoded;
     QDataStream stream(&encoded, QIODevice::WriteOnly);
     QSet<QStandardItem*> itemsSet;
     QStack<QStandardItem*> stack;
     itemsSet.reserve(indexes.count());
     stack.reserve(indexes.count());
     for (int i = 0; i < indexes.count(); ++i) {
         QStandardItem *item = itemFromIndex(indexes.at(i));
         itemsSet << item;
         stack.push(item);
     }
     //remove duplicates childrens
     {
         QSet<QStandardItem *> seen;
         while (!stack.isEmpty()) {
             QStandardItem *itm = stack.pop();
             if (seen.contains(itm))
                 continue;
             seen.insert(itm);
             const QVector<QStandardItem*> &childList = itm->d_func()->children;
             for (int i = 0; i < childList.count(); ++i) {
                 QStandardItem *chi = childList.at(i);
                 if (chi) {
                     QSet<QStandardItem *>::iterator it = itemsSet.find(chi);
                     if (it != itemsSet.end()) {
                         itemsSet.erase(it);
                     }
                     stack.push(chi);
                 }
             }
         }
     }
     stack.reserve(itemsSet.count());
     foreach (QStandardItem *item, itemsSet) {
         stack.push(item);
     }
     //stream everything recursively
     while (!stack.isEmpty()) {
         QStandardItem *item = stack.pop();
         if(itemsSet.contains(item)) { //if the item is selection 'top-level', strem its position
             stream << item->row() << item->column();
         }
         if(item) {
             stream << *item << item->columnCount() << item->d_ptr->children.count();
             stack += item->d_ptr->children;
         } else {
             QStandardItem dummy;
             stream << dummy << 0 << 0;
         }
     }
     data->setData(format, encoded);
     return data;
 }
mimeTypes()
QStringList QStandardItemModel::mimeTypes () const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3096 of file qstandarditemmodel.cpp.
Referenced by mimeData().
 {
     return QAbstractItemModel::mimeTypes() <<  QLatin1String("application/x-qstandarditemmodeldatalist");
 }
parent()
QObject * QStandardItemModel::parent (const QModelIndex & child) const virtual
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemModel.
Definition at line 2973 of file qstandarditemmodel.cpp.
 {
     Q_D(const QStandardItemModel);
     if (!d->indexValid(child))
         return QModelIndex();
     QStandardItem *parentItem = static_cast<QStandardItem*>(child.internalPointer());
     return indexFromItem(parentItem);
 }
removeColumns()
bool QStandardItemModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2985 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(parent);
     if ((item == 0) || (count < 1) || (column < 0) || ((column + count) > item->columnCount()))
         return false;
     item->removeColumns(column, count);
     return true;
 }
removeRows()
bool QStandardItemModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2998 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::setUrls().
 {
     Q_D(QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(parent);
     if ((item == 0) || (count < 1) || (row < 0) || ((row + count) > item->rowCount()))
         return false;
     item->removeRows(row, count);
     return true;
 }
rowCount()
int QStandardItemModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 3011 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::addUrls(), QUrlModel::changed(), dropMimeData(), headerData(), setHeaderData(), QUrlModel::setUrls(), setVerticalHeaderItem(), setVerticalHeaderLabels(), takeVerticalHeaderItem(), QUrlModel::urls(), and verticalHeaderItem().
 {
     Q_D(const QStandardItemModel);
     QStandardItem *item = d->itemFromIndex(parent);
     return item ? item->rowCount() : 0;
 }
setColumnCount()
void QStandardItemModel::setColumnCount (int columns)
Sets the number of columns in this model to columns.
Since
4.2
If this is less than columnCount(), the data in the unwanted columns is discarded.
See also
setRowCount()
Definition at line 2314 of file qstandarditemmodel.cpp.
Referenced by setHorizontalHeaderItem(), and setHorizontalHeaderLabels().
 {
     Q_D(QStandardItemModel);
     d->root->setColumnCount(columns);
 }
setData()
bool QStandardItemModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3021 of file qstandarditemmodel.cpp.
Referenced by QUrlModel::setData().
 {
     if (!index.isValid())
         return false;
     QStandardItem *item = itemFromIndex(index);
     if (item == 0)
         return false;
     item->setData(value, role);
     return true;
 }
setHeaderData()
bool QStandardItemModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3035 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     if ((section < 0)
         || ((orientation == Qt::Horizontal) && (section >= columnCount()))
         || ((orientation == Qt::Vertical) && (section >= rowCount()))) {
         return false;
     }
     QStandardItem *headerItem = 0;
     if (orientation == Qt::Horizontal) {
         headerItem = d->columnHeaderItems.at(section);
         if (headerItem == 0) {
             headerItem = d->createItem();
             headerItem->d_func()->setModel(this);
             d->columnHeaderItems.replace(section, headerItem);
         }
     } else if (orientation == Qt::Vertical) {
         headerItem = d->rowHeaderItems.at(section);
         if (headerItem == 0) {
             headerItem = d->createItem();
             headerItem->d_func()->setModel(this);
             d->rowHeaderItems.replace(section, headerItem);
         }
     }
     if (headerItem) {
         headerItem->setData(value, role);
         return true;
     }
     return false;
 }
setHorizontalHeaderItem()
void QStandardItemModel::setHorizontalHeaderItem (int column, QStandardItem * item)
Sets the horizontal header item for column to item.
Since
4.2
The model takes ownership of the item. If necessary, the column count is increased to fit the item. The previous header item (if there was one) is deleted.
See also
horizontalHeaderItem(), setHorizontalHeaderLabels(), setVerticalHeaderItem()
Definition at line 2396 of file qstandarditemmodel.cpp.
Referenced by setHorizontalHeaderLabels().
 {
     Q_D(QStandardItemModel);
     if (column < 0)
         return;
     if (columnCount() <= column)
         setColumnCount(column + 1);
     QStandardItem *oldItem = d->columnHeaderItems.at(column);
     if (item == oldItem)
         return;
     if (item) {
         if (item->model() == 0) {
             item->d_func()->setModel(this);
         } else {
             qWarning("QStandardItem::setHorizontalHeaderItem: Ignoring duplicate insertion of item %p",
                      item);
             return;
         }
     }
     if (oldItem)
         oldItem->d_func()->setModel(0);
     delete oldItem;
     d->columnHeaderItems.replace(column, item);
     emit headerDataChanged(Qt::Horizontal, column, column);
 }
setHorizontalHeaderLabels()
void QStandardItemModel::setHorizontalHeaderLabels (const QStringList & labels)
Sets the horizontal header labels using labels.
Since
4.2
If necessary, the column count is increased to the size of labels.
See also
setHorizontalHeaderItem()
Definition at line 2518 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     if (columnCount() < labels.count())
         setColumnCount(labels.count());
     for (int i = 0; i < labels.count(); ++i) {
         QStandardItem *item = horizontalHeaderItem(i);
         if (!item) {
             item = d->createItem();
             setHorizontalHeaderItem(i, item);
         }
         item->setText(labels.at(i));
     }
 }
setItem() [1/2]
void QStandardItemModel::setItem (int row, int column, QStandardItem * item)
Sets the item for the given row and column to item.
Since
4.2
The model takes ownership of the item. If necessary, the row count and column count are increased to fit the item. The previous item at the given location (if there was one) is deleted.
See also
item()
Definition at line 2333 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     d->root->d_func()->setChild(row, column, item, true);
 }
setItem() [2/2]
void QStandardItemModel::setItem (int row, QStandardItem * item) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 431 of file qstandarditemmodel.h.
 { setItem(arow, 0, aitem); }
setItemData()
bool QStandardItemModel::setItemData (const QModelIndex & index, const QMap< int, QVariant > & roles) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3069 of file qstandarditemmodel.cpp.
 {
     QStandardItem *item = itemFromIndex(index);
     if (item == 0)
         return false;
     item->d_func()->setItemData(roles);
     return true;
 }
setItemPrototype()
void QStandardItemModel::setItemPrototype (const QStandardItem * item)
Sets the item prototype for the model to the specified item.
Since
4.2
The model takes ownership of the prototype.
The item prototype acts as a QStandardItem factory, by relying on the QStandardItem::clone() function. To provide your own prototype, subclass QStandardItem, reimplement QStandardItem::clone() and set the prototype to be an instance of your custom class. Whenever QStandardItemModel needs to create an item on demand (for instance, when a view or item delegate calls setData())), the new items will be instances of your custom class.
See also
itemPrototype(), QStandardItem::clone()
Definition at line 2577 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     if (d->itemPrototype != item) {
         delete d->itemPrototype;
         d->itemPrototype = item;
     }
 }
setRowCount()
void QStandardItemModel::setRowCount (int rows)
Sets the number of rows in this model to rows.
Since
4.2
If this is less than rowCount(), the data in the unwanted rows is discarded.
See also
setColumnCount()
Definition at line 2296 of file qstandarditemmodel.cpp.
Referenced by setVerticalHeaderItem(), and setVerticalHeaderLabels().
 {
     Q_D(QStandardItemModel);
     d->root->setRowCount(rows);
 }
setSortRole()
void QStandardItemModel::setSortRole (int role)
Definition at line 2832 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     d->sortRole = role;
 }
setVerticalHeaderItem()
void QStandardItemModel::setVerticalHeaderItem (int row, QStandardItem * item)
Sets the vertical header item for row to item.
Since
4.2
The model takes ownership of the item. If necessary, the row count is increased to fit the item. The previous header item (if there was one) is deleted.
See also
verticalHeaderItem(), setVerticalHeaderLabels(), setHorizontalHeaderItem()
Definition at line 2458 of file qstandarditemmodel.cpp.
Referenced by setVerticalHeaderLabels().
 {
     Q_D(QStandardItemModel);
     if (row < 0)
         return;
     if (rowCount() <= row)
         setRowCount(row + 1);
     QStandardItem *oldItem = d->rowHeaderItems.at(row);
     if (item == oldItem)
         return;
     if (item) {
         if (item->model() == 0) {
             item->d_func()->setModel(this);
         } else {
             qWarning("QStandardItem::setVerticalHeaderItem: Ignoring duplicate insertion of item %p",
                      item);
             return;
         }
     }
     if (oldItem)
         oldItem->d_func()->setModel(0);
     delete oldItem;
     d->rowHeaderItems.replace(row, item);
     emit headerDataChanged(Qt::Vertical, row, row);
 }
setVerticalHeaderLabels()
void QStandardItemModel::setVerticalHeaderLabels (const QStringList & labels)
Sets the vertical header labels using labels.
Since
4.2
If necessary, the row count is increased to the size of labels.
See also
setVerticalHeaderItem()
Definition at line 2544 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     if (rowCount() < labels.count())
         setRowCount(labels.count());
     for (int i = 0; i < labels.count(); ++i) {
         QStandardItem *item = verticalHeaderItem(i);
         if (!item) {
             item = d->createItem();
             setVerticalHeaderItem(i, item);
         }
         item->setText(labels.at(i));
     }
 }
sort()
void QStandardItemModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 3081 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     d->root->sortChildren(column, order);
 }
sortRole()
int QStandardItemModel::sortRole () const
Referenced by takeVerticalHeaderItem().
supportedDropActions()
Qt::DropActions QStandardItemModel::supportedDropActions () const virtual
QStandardItemModel supports both copy and move.
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 2914 of file qstandarditemmodel.cpp.
 {
     return Qt::CopyAction | Qt::MoveAction;
 }
takeColumn()
QList< QStandardItem * > QStandardItemModel::takeColumn (int column)
Removes the given column without deleting the column items, and returns a list of pointers to the removed items.
Since
4.2
The model releases ownership of the items. For items in the column that have not been set, the corresponding pointers in the list will be 0.
See also
takeRow()
Definition at line 2758 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     return d->root->takeColumn(column);
 }
takeHorizontalHeaderItem()
QStandardItem * QStandardItemModel::takeHorizontalHeaderItem (int column)
Removes the horizontal header item at column from the header without deleting it, and returns a pointer to the item.
Since
4.2
The model releases ownership of the item.
See also
horizontalHeaderItem(), takeVerticalHeaderItem()
Definition at line 2776 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     if ((column < 0) || (column >= columnCount()))
         return 0;
     QStandardItem *headerItem = d->columnHeaderItems.at(column);
     if (headerItem) {
         headerItem->d_func()->setParentAndModel(0, 0);
         d->columnHeaderItems.replace(column, 0);
     }
     return headerItem;
 }
takeItem()
QStandardItem * QStandardItemModel::takeItem (int row, int column = 0)
Removes the item at (row, column) without deleting it.
Since
4.2
The model releases ownership of the item.
See also
item(), takeRow(), takeColumn()
Definition at line 2720 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     return d->root->takeChild(row, column);
 }
takeRow()
QList< QStandardItem * > QStandardItemModel::takeRow (int row)
Removes the given row without deleting the row items, and returns a list of pointers to the removed items.
Since
4.2
The model releases ownership of the items. For items in the row that have not been set, the corresponding pointers in the list will be 0.
See also
takeColumn()
Definition at line 2739 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     return d->root->takeRow(row);
 }
takeVerticalHeaderItem()
QStandardItem * QStandardItemModel::takeVerticalHeaderItem (int row)
Removes the vertical header item at row from the header without deleting it, and returns a pointer to the item.
Since
4.2
The model releases ownership of the item.
See also
verticalHeaderItem(), takeHorizontalHeaderItem()
Definition at line 2801 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItemModel);
     if ((row < 0) || (row >= rowCount()))
         return 0;
     QStandardItem *headerItem = d->rowHeaderItems.at(row);
     if (headerItem) {
         headerItem->d_func()->setParentAndModel(0, 0);
         d->rowHeaderItems.replace(row, 0);
     }
     return headerItem;
 }
verticalHeaderItem()
QStandardItem * QStandardItemModel::verticalHeaderItem (int row) const
Returns the vertical header item for row row if one has been set; otherwise returns 0.
Since
4.2
See also
setVerticalHeaderItem(), horizontalHeaderItem()
Definition at line 2499 of file qstandarditemmodel.cpp.
Referenced by setVerticalHeaderLabels().
 {
     Q_D(const QStandardItemModel);
     if ((row < 0) || (row >= rowCount()))
         return 0;
     return d->rowHeaderItems.at(row);
 }
Friends and Related Functions
QStandardItem
friend class QStandardItem friend
Definition at line 423 of file qstandarditemmodel.h.
QStandardItemPrivate
friend class QStandardItemPrivate friend
Definition at line 422 of file qstandarditemmodel.h.
Properties
sortRole
int QStandardItemModel::sortRole private
the item role that is used to query the model's data when sorting items
Since
4.2
The default value is Qt::DisplayRole.
See also
sort(), QStandardItem::sortChildren()
Definition at line 321 of file qstandarditemmodel.h.
Referenced by QStandardItem::operator<().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qstandarditemmodel.h
/src/gui/itemviews/qstandarditemmodel.cpp