Qt 4.8: Maemo::IAPConf Class Reference
Maemo::IAPConf Class Reference
#include <iapconf.h>
Public Functions
IAPConf (const QString &iap_id)
QVariant value (const QString &key) const
virtual ~IAPConf ()
Static Public Functions
static void getAll (QList< QString > &all_iaps, bool return_path=false)
Properties
IAPConfPrivate * d_ptr
Detailed Description
Definition at line 52 of file iapconf.h.
Constructors and Destructors
IAPConf()
Maemo::IAPConf::IAPConf (const QString & iap_id)
Definition at line 197 of file iapconf.cpp.
     : d_ptr(new IAPConfPrivate)
 {
     d_ptr->settings = conn_settings_open(CONN_SETTINGS_CONNECTION,
                                          QSTRING_TO_CONST_CSTR(iap_id));
     if (d_ptr->settings == 0) {
         qWarning("IAPConf: Unable to open ConnSettings for %s",
                  QSTRING_TO_CONST_CSTR(iap_id));
     }
 }
~IAPConf()
Maemo::IAPConf::~IAPConf () virtual
Definition at line 208 of file iapconf.cpp.
 {
     conn_settings_close(d_ptr->settings);
     delete d_ptr;
 }
Functions
getAll()
void Maemo::IAPConf::getAll (QList< QString > & all_iaps, bool return_path = false) static
Return all the IAPs found in the system. If return_path is true, then do not strip the IAP path away.
Definition at line 226 of file iapconf.cpp.
Referenced by QIcdEngine::doRequestUpdate().
 {
     Q_UNUSED(return_path); // We don't use return path currently
     // Go through all available connections and add them to the list
     char **ids = conn_settings_list_ids(CONN_SETTINGS_CONNECTION);
     if (ids == 0) {
         // No ids found - nothing to do
         return;
     }
     for (int idx = 0; ids[idx]; idx++) {
         all_iaps.append(QString(ids[idx]));
         free(ids[idx]);
     }
     free(ids);
 }
value()
QVariant Maemo::IAPConf::value (const QString & key) const
Get one IAP value.
Definition at line 215 of file iapconf.cpp.
Referenced by QIcdEngine::addConfiguration(), QIcdEngine::doRequestUpdate(), getNetworkAttrs(), QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
 {
     ConnSettingsValue *val = conn_settings_get(d_ptr->settings,
                                                QSTRING_TO_CONST_CSTR(key));
     QVariant variant = d_ptr->valueToVariant(val);
     conn_settings_value_destroy(val);
     return variant;
 }
Properties
d_ptr
IAPConfPrivate* Maemo::IAPConf::d_ptr private
Definition at line 69 of file iapconf.h.
Referenced by IAPConf(), value(), and ~IAPConf().
The documentation for this class was generated from the following files:
/src/plugins/bearer/icd/iapconf.h
/src/plugins/bearer/icd/iapconf.cpp