Qt 4.8: QXmlStreamReader Class Reference
QXmlStreamReader Class Reference
The QXmlStreamReader class provides a fast parser for reading well-formed XML via a simple streaming API.
#include <qxmlstream.h>
Public Types
enum Error {
NoError, UnexpectedElementError, CustomError, NotWellFormedError,
PrematureEndOfDocumentError
}
This enum specifies different error cases.
enum ReadElementTextBehaviour { ErrorOnUnexpectedElement, IncludeChildElements, SkipChildElements }
This enum specifies the different behaviours of readElementText().
enum TokenType {
NoToken = 0, Invalid, StartDocument, EndDocument,
StartElement, EndElement, Characters, Comment,
DTD, EntityReference, ProcessingInstruction
}
This enum specifies the type of token the reader just read.
Public Functions
void addData (const QByteArray &data)
Adds more data for the reader to read.
void addData (const QString &data)
Adds more data for the reader to read.
void addData (const char *data)
Adds more data for the reader to read.
void addExtraNamespaceDeclaration (const QXmlStreamNamespaceDeclaration &extraNamespaceDeclaraction)
Adds an extraNamespaceDeclaration.
void addExtraNamespaceDeclarations (const QXmlStreamNamespaceDeclarations &extraNamespaceDeclaractions)
Adds a vector of declarations specified by extraNamespaceDeclarations.
bool atEnd () const
Returns true if the reader has read until the end of the XML document, or if an error() has occurred and reading has been aborted.
QXmlStreamAttributes attributes () const
Returns the attributes of a StartElement.
qint64 characterOffset () const
Returns the current character offset, starting with 0.
void clear ()
Removes any device() or data from the reader and resets its internal state to the initial state.
qint64 columnNumber () const
Returns the current column number, starting with 0.
QIODevice * device () const
Returns the current device associated with the QXmlStreamReader, or 0 if no device has been assigned.
QStringRef documentEncoding () const
If the state() is StartDocument , this function returns the encoding string as specified in the XML declaration.
QStringRef documentVersion () const
If the state() is StartDocument , this function returns the version string as specified in the XML declaration.
QStringRef dtdName () const
If the state() is DTD , this function returns the DTD's name.
QStringRef dtdPublicId () const
If the state() is DTD , this function returns the DTD's public identifier.
QStringRef dtdSystemId () const
If the state() is DTD , this function returns the DTD's system identifier.
QXmlStreamEntityDeclarations entityDeclarations () const
If the state() is DTD , this function returns the DTD's unparsed (external) entity declarations.
QXmlStreamEntityResolver * entityResolver () const
Returns the entity resolver, or 0 if there is no entity resolver.
Error error () const
Returns the type of the current error, or NoError if no error occurred.
QString errorString () const
Returns the error message that was set with raiseError().
bool hasError () const
Returns true if an error has occurred, otherwise false.
bool isCDATA () const
Returns true if the reader reports characters that stem from a CDATA section; otherwise returns false.
bool isCharacters () const
Returns true if tokenType() equals Characters ; otherwise returns false.
bool isComment () const
Returns true if tokenType() equals Comment ; otherwise returns false.
bool isDTD () const
Returns true if tokenType() equals DTD ; otherwise returns false.
bool isEndDocument () const
Returns true if tokenType() equals EndDocument ; otherwise returns false.
bool isEndElement () const
Returns true if tokenType() equals EndElement ; otherwise returns false.
bool isEntityReference () const
Returns true if tokenType() equals EntityReference ; otherwise returns false.
bool isProcessingInstruction () const
Returns true if tokenType() equals ProcessingInstruction ; otherwise returns false.
bool isStandaloneDocument () const
Returns true if this document has been declared standalone in the XML declaration; otherwise returns false.
bool isStartDocument () const
Returns true if tokenType() equals StartDocument ; otherwise returns false.
bool isStartElement () const
Returns true if tokenType() equals StartElement ; otherwise returns false.
bool isWhitespace () const
Returns true if the reader reports characters that only consist of white-space; otherwise returns false.
qint64 lineNumber () const
Returns the current line number, starting with 1.
QStringRef name () const
Returns the local name of a StartElement, EndElement, or an EntityReference.
QXmlStreamNamespaceDeclarations namespaceDeclarations () const
If the state() is StartElement , this function returns the element's namespace declarations.
bool namespaceProcessing () const
This property controls whether or not the stream reader processes namespaces.
QStringRef namespaceUri () const
Returns the namespaceUri of a StartElement or EndElement.
QXmlStreamNotationDeclarations notationDeclarations () const
If the state() is DTD , this function returns the DTD's notation declarations.
QStringRef prefix () const
Returns the prefix of a StartElement or EndElement.
QStringRef processingInstructionData () const
Returns the data of a ProcessingInstruction.
QStringRef processingInstructionTarget () const
Returns the target of a ProcessingInstruction.
QStringRef qualifiedName () const
Returns the qualified name of a StartElement or EndElement;.
QXmlStreamReader ()
Constructs a stream reader.
QXmlStreamReader (QIODevice *device)
Creates a new stream reader that reads from device.
QXmlStreamReader (const QByteArray &data)
Creates a new stream reader that reads from data.
QXmlStreamReader (const QString &data)
Creates a new stream reader that reads from data.
QXmlStreamReader (const char *data)
Creates a new stream reader that reads from data.
void raiseError (const QString &message=QString())
Raises a custom error with an optional error message.
QString readElementText (ReadElementTextBehaviour behaviour)
Convenience function to be called in case a StartElement was read.
QString readElementText ()
TokenType readNext ()
Reads the next token and returns its type.
bool readNextStartElement ()
Reads until the next start element within the current element.
void setDevice (QIODevice *device)
Sets the current device to device.
void setEntityResolver (QXmlStreamEntityResolver *resolver)
Makes resolver the new entityResolver().
void setNamespaceProcessing (bool)
void skipCurrentElement ()
Reads until the end of the current element, skipping any child nodes.
QStringRef text () const
Returns the text of Characters , Comment , DTD , or EntityReference.
QString tokenString () const
Returns the reader's current token as string.
TokenType tokenType () const
Returns the type of the current token.
~QXmlStreamReader ()
Destructs the reader.
Properties
QScopedPointer< QXmlStreamReaderPrivate > d_ptr
Detailed Description
The QXmlStreamReader class provides a fast parser for reading well-formed XML via a simple streaming API.
Note
This class or function is reentrant.
Since
4.3
QXmlStreamReader is a faster and more convenient replacement for Qt's own SAX parser (see QXmlSimpleReader). In some cases it might also be a faster and more convenient alternative for use in applications that would otherwise use a DOM tree (see QDomDocument). QXmlStreamReader reads data either from a QIODevice (see setDevice()), or from a raw QByteArray (see addData()).
Qt provides QXmlStreamWriter for writing XML.
The basic concept of a stream reader is to report an XML document as a stream of tokens, similar to SAX. The main difference between QXmlStreamReader and SAX is how these XML tokens are reported. With SAX, the application must provide handlers (callback functions) that receive so-called XML events from the parser at the parser's convenience. With QXmlStreamReader, the application code itself drives the loop and pulls tokens from the reader, one after another, as it needs them. This is done by calling readNext(), where the reader reads from the input stream until it completes the next token, at which point it returns the tokenType(). A set of convenient functions including isStartElement() and text() can then be used to examine the token to obtain information about what has been read. The big advantage of this pulling approach is the possibility to build recursive descent parsers with it, meaning you can split your XML parsing code easily into different methods or classes. This makes it easy to keep track of the application's own state when parsing XML.
A typical loop with QXmlStreamReader looks like this:
  QXmlStreamReader xml;
  ...
  while (!xml.atEnd()) {
        xml.readNext();
        ... // do processing
  }
  if (xml.hasError()) {
        ... // do error handling
  }
QXmlStreamReader is a well-formed XML 1.0 parser that does not include external parsed entities. As long as no error occurs, the application code can thus be assured that the data provided by the stream reader satisfies the W3C's criteria for well-formed XML. For example, you can be certain that all tags are indeed nested and closed properly, that references to internal entities have been replaced with the correct replacement text, and that attributes have been normalized or added according to the internal subset of the DTD.
If an error occurs while parsing, atEnd() and hasError() return true, and error() returns the error that occurred. The functions errorString(), lineNumber(), columnNumber(), and characterOffset() are for constructing an appropriate error or warning message. To simplify application code, QXmlStreamReader contains a raiseError() mechanism that lets you raise custom errors that trigger the same error handling described.
The QXmlStream Bookmarks Example illustrates how to use the recursive descent technique to read an XML bookmark file (XBEL) with a stream reader.
Namespaces
QXmlStream understands and resolves XML namespaces. E.g. in case of a StartElement, namespaceUri() returns the namespace the element is in, and name() returns the element's local name. The combination of namespaceUri and name uniquely identifies an element. If a namespace prefix was not declared in the XML entities parsed by the reader, the namespaceUri is empty.
If you parse XML data that does not utilize namespaces according to the XML specification or doesn't use namespaces at all, you can use the element's qualifiedName() instead. A qualified name is the element's prefix() followed by colon followed by the element's local name() - exactly like the element appears in the raw XML data. Since the mapping namespaceUri to prefix is neither unique nor universal, qualifiedName() should be avoided for namespace-compliant XML data.
In order to parse standalone documents that do use undeclared namespace prefixes, you can turn off namespace processing completely with the namespaceProcessing property.
Incremental parsing
QXmlStreamReader is an incremental parser. It can handle the case where the document can't be parsed all at once because it arrives in chunks (e.g. from multiple files, or over a network connection). When the reader runs out of data before the complete document has been parsed, it reports a PrematureEndOfDocumentError. When more data arrives, either because of a call to addData() or because more data is available through the network device(), the reader recovers from the PrematureEndOfDocumentError error and continues parsing the new data with the next call to readNext().
For example, if your application reads data from the network using a network access manager, you would issue a network request to the manager and receive a network reply in return. Since a QNetworkReply is a QIODevice, you connect its readyRead() signal to a custom slot, e.g. slotReadyRead() in the code snippet shown in the discussion for QNetworkAccessManager. In this slot, you read all available data with readAll() and pass it to the XML stream reader using addData(). Then you call your custom parsing function that reads the XML events from the reader.
Performance and memory consumption
QXmlStreamReader is memory-conservative by design, since it doesn't store the entire XML document tree in memory, but only the current token at the time it is reported. In addition, QXmlStreamReader avoids the many small string allocations that it normally takes to map an XML document to a convenient and Qt-ish API. It does this by reporting all string data as QStringRef rather than real QString objects. QStringRef is a thin wrapper around QString substrings that provides a subset of the QString API without the memory allocation and reference-counting overhead. Calling toString() on any of those objects returns an equivalent real QString object.
Definition at line 290 of file qxmlstream.h.
Enumerations
Error
enum QXmlStreamReader::Error
This enum specifies different error cases.
NoError No error has occurred.
CustomError A custom error has been raised with raiseError()
NotWellFormedError The parser internally raised an error due to the read XML not being well-formed.
PrematureEndOfDocumentError The input stream ended before a well-formed XML document was parsed. Recovery from this error is possible if more XML arrives in the stream, either by calling addData() or by waiting for it to arrive on the device().
UnexpectedElementError The parser encountered an element that was different to those it expected.
Enumerator
NoError
UnexpectedElementError
CustomError
NotWellFormedError
PrematureEndOfDocumentError
Definition at line 385 of file qxmlstream.h.
                {
         NoError,
         UnexpectedElementError,
         CustomError,
         NotWellFormedError,
         PrematureEndOfDocumentError
     };
ReadElementTextBehaviour
enum QXmlStreamReader::ReadElementTextBehaviour
This enum specifies the different behaviours of readElementText().
ErrorOnUnexpectedElement Raise an UnexpectedElementError and return what was read so far when a child element is encountered.
IncludeChildElements Recursively include the text from child elements.
SkipChildElements Skip child elements.
Since
4.6
Enumerator
ErrorOnUnexpectedElement
IncludeChildElements
SkipChildElements
Definition at line 357 of file qxmlstream.h.
{
         ErrorOnUnexpectedElement,
         IncludeChildElements,
         SkipChildElements
     };
TokenType
enum QXmlStreamReader::TokenType
This enum specifies the type of token the reader just read.
NoToken The reader has not yet read anything.
Invalid An error has occurred, reported in error() and errorString().
StartDocument The reader reports the XML version number in documentVersion(), and the encoding as specified in the XML document in documentEncoding(). If the document is declared standalone, isStandaloneDocument() returns true; otherwise it returns false.
EndDocument The reader reports the end of the document.
StartElement The reader reports the start of an element with namespaceUri() and name(). Empty elements are also reported as StartElement, followed directly by EndElement. The convenience function readElementText() can be called to concatenate all content until the corresponding EndElement. Attributes are reported in attributes(), namespace declarations in namespaceDeclarations().
EndElement The reader reports the end of an element with namespaceUri() and name().
Characters The reader reports characters in text(). If the characters are all white-space, isWhitespace() returns true. If the characters stem from a CDATA section, isCDATA() returns true.
Comment The reader reports a comment in text().
DTD The reader reports a DTD in text(), notation declarations in notationDeclarations(), and entity declarations in entityDeclarations(). Details of the DTD declaration are reported in in dtdName(), dtdPublicId(), and dtdSystemId().
EntityReference The reader reports an entity reference that could not be resolved. The name of the reference is reported in name(), the replacement text in text().
ProcessingInstruction The reader reports a processing instruction in processingInstructionTarget() and processingInstructionData().
Enumerator
NoToken
Invalid
StartDocument
EndDocument
StartElement
EndElement
Characters
Comment
DTD
EntityReference
ProcessingInstruction
Definition at line 293 of file qxmlstream.h.
                    {
         NoToken = 0,
         Invalid,
         StartDocument,
         EndDocument,
         StartElement,
         EndElement,
         Characters,
         Comment,
         DTD,
         EntityReference,
         ProcessingInstruction
     };
Constructors and Destructors
QXmlStreamReader() [1/5]
QXmlStreamReader::QXmlStreamReader ()
Constructs a stream reader.
See also
setDevice(), addData()
Definition at line 406 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamReaderPrivate(this))
 {
 }
QXmlStreamReader() [2/5]
QXmlStreamReader::QXmlStreamReader (QIODevice * device)
Creates a new stream reader that reads from device.
See also
setDevice(), clear()
Definition at line 415 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamReaderPrivate(this))
 {
     setDevice(device);
 }
QXmlStreamReader() [3/5]
QXmlStreamReader::QXmlStreamReader (const QByteArray & data)
Creates a new stream reader that reads from data.
See also
addData(), clear(), setDevice()
Definition at line 426 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamReaderPrivate(this))
 {
     Q_D(QXmlStreamReader);
     d->dataBuffer = data;
 }
QXmlStreamReader() [4/5]
QXmlStreamReader::QXmlStreamReader (const QString & data)
Creates a new stream reader that reads from data.
See also
addData(), clear(), setDevice()
Definition at line 438 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamReaderPrivate(this))
 {
     Q_D(QXmlStreamReader);
 #ifdef QT_NO_TEXTCODEC
     d->dataBuffer = data.toLatin1();
 #else
     d->dataBuffer = d->codec->fromUnicode(data);
     d->decoder = d->codec->makeDecoder();
 #endif
     d->lockEncoding = true;
 }
QXmlStreamReader() [5/5]
QXmlStreamReader::QXmlStreamReader (const char * data)
Creates a new stream reader that reads from data.
See also
addData(), clear(), setDevice()
Definition at line 457 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamReaderPrivate(this))
 {
     Q_D(QXmlStreamReader);
     d->dataBuffer = QByteArray(data);
 }
~QXmlStreamReader()
QXmlStreamReader::~QXmlStreamReader ()
Destructs the reader.
Definition at line 467 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     if (d->deleteDevice)
         delete d->device;
 }
Functions
addData() [1/3]
void QXmlStreamReader::addData (const QByteArray & data)
Adds more data for the reader to read.
This function does nothing if the reader has a device().
See also
readNext(), clear()
Definition at line 520 of file qxmlstream.cpp.
Referenced by addData().
 {
     Q_D(QXmlStreamReader);
     if (d->device) {
         qWarning("QXmlStreamReader: addData() with device()");
         return;
     }
     d->dataBuffer += data;
 }
addData() [2/3]
void QXmlStreamReader::addData (const QString & data)
Adds more data for the reader to read.
This function does nothing if the reader has a device().
See also
readNext(), clear()
Definition at line 536 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     d->lockEncoding = true;
 #ifdef QT_NO_TEXTCODEC
     addData(data.toLatin1());
 #else
     addData(d->codec->fromUnicode(data));
 #endif
 }
addData() [3/3]
void QXmlStreamReader::addData (const char * data)
Adds more data for the reader to read.
This function does nothing if the reader has a device().
See also
readNext(), clear()
Definition at line 553 of file qxmlstream.cpp.
 {
     addData(QByteArray(data));
 }
addExtraNamespaceDeclaration()
void QXmlStreamReader::addExtraNamespaceDeclaration (const QXmlStreamNamespaceDeclaration & extraNamespaceDeclaration)
Adds an extraNamespaceDeclaration.
Since
4.4
The declaration will be valid for children of the current element, or - should the function be called before any elements are read - for the entire XML document.
See also
namespaceDeclarations(), addExtraNamespaceDeclarations(), setNamespaceProcessing()
Definition at line 2110 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     QXmlStreamReaderPrivate::NamespaceDeclaration &namespaceDeclaration = d->namespaceDeclarations.push();
     namespaceDeclaration.prefix = d->addToStringStorage(extraNamespaceDeclaration.prefix());
     namespaceDeclaration.namespaceUri = d->addToStringStorage(extraNamespaceDeclaration.namespaceUri());
 }
addExtraNamespaceDeclarations()
void QXmlStreamReader::addExtraNamespaceDeclarations (const QXmlStreamNamespaceDeclarations & extraNamespaceDeclarations)
Adds a vector of declarations specified by extraNamespaceDeclarations.
Since
4.4
See also
namespaceDeclarations(), addExtraNamespaceDeclaration()
Definition at line 2128 of file qxmlstream.cpp.
 {
     for (int i = 0; i < extraNamespaceDeclarations.size(); ++i)
         addExtraNamespaceDeclaration(extraNamespaceDeclarations.at(i));
 }
atEnd()
bool QXmlStreamReader::atEnd () const
Returns true if the reader has read until the end of the XML document, or if an error() has occurred and reading has been aborted.
Otherwise, it returns false.
When atEnd() and hasError() return true and error() returns PrematureEndOfDocumentError, it means the XML has been well-formed so far, but a complete XML document has not been parsed. The next chunk of XML can be added with addData(), if the XML is being read from a QByteArray, or by waiting for more data to arrive if the XML is being read from a QIODevice. Either way, atEnd() will return false once more data is available.
See also
hasError(), error(), device(), QIODevice::atEnd()
Definition at line 590 of file qxmlstream.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::XSLTTokenizer::insideAttributeSet(), QPatternist::XSLTTokenizer::insideChoose(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideStylesheetModule(), Document::load(), QPatternist::XSLTTokenizer::outsideDocumentElement(), QScriptXmlParser::parse(), QPatternist::XsdSchemaParser::parse(), QSvgHandler::parse(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAppInfo(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseDocumentation(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::parseUnknownDocumentation(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QPatternist::XSLTTokenizer::queueParams(), QPatternist::XSLTTokenizer::queueSorting(), QPatternist::XSLTTokenizer::queueWithParams(), QPatternist::XSLTTokenizer::readElementText(), QPatternist::XSLTTokenizer::skipSubTree(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and tokenUntil().
 {
     Q_D(const QXmlStreamReader);
     if (d->atEnd
         && ((d->type == QXmlStreamReader::Invalid && d->error == PrematureEndOfDocumentError)
             || (d->type == QXmlStreamReader::EndDocument))) {
         if (d->device)
             return d->device->atEnd();
         else
             return !d->dataBuffer.size();
     }
     return (d->atEnd || d->type == QXmlStreamReader::Invalid);
 }
attributes()
QXmlStreamAttributes QXmlStreamReader::attributes () const
Returns the attributes of a StartElement.
Definition at line 2317 of file qxmlstream.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::XSLTTokenizer::handleXSLTVersion(), Document::load(), QScriptXmlParser::parse(), QSvgHandler::parse(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), tokenUntil(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->attributes;
 }
characterOffset()
qint64 QXmlStreamReader::characterOffset () const
Returns the current character offset, starting with 0.
See also
lineNumber(), columnNumber()
Definition at line 1979 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamReader);
     return d->characterOffset + d->readBufferPos;
 }
clear()
void QXmlStreamReader::clear ()
Removes any device() or data from the reader and resets its internal state to the initial state.
See also
addData()
Definition at line 564 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     d->init();
     if (d->device) {
         if (d->deleteDevice)
             delete d->device;
         d->device = 0;
     }
 }
columnNumber()
qint64 QXmlStreamReader::columnNumber () const
Returns the current column number, starting with 0.
See also
lineNumber(), characterOffset()
Definition at line 1969 of file qxmlstream.cpp.
Referenced by QPatternist::XsdSchemaParser::currentSourceLocation(), QPatternist::XSLTTokenizer::currentSourceLocator(), and QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     Q_D(const QXmlStreamReader);
     return d->characterOffset - d->lastLineStart + d->readBufferPos;
 }
device()
QIODevice * QXmlStreamReader::device () const
Returns the current device associated with the QXmlStreamReader, or 0 if no device has been assigned.
See also
setDevice()
Definition at line 507 of file qxmlstream.cpp.
Referenced by setDevice().
 {
     Q_D(const QXmlStreamReader);
     return d->device;
 }
documentEncoding()
QStringRef QXmlStreamReader::documentEncoding () const
If the state() is StartDocument , this function returns the encoding string as specified in the XML declaration.
Since
4.4
Otherwise an empty string is returned.
Definition at line 3031 of file qxmlstream.cpp.
Referenced by QDeclarativeXMLHttpRequest::findTextCodec(), and Document::load().
 {
    Q_D(const QXmlStreamReader);
    if (d->type == QXmlStreamReader::StartDocument)
        return d->documentEncoding;
    return QStringRef();
 }
documentVersion()
QStringRef QXmlStreamReader::documentVersion () const
If the state() is StartDocument , this function returns the version string as specified in the XML declaration.
Since
4.4
Otherwise an empty string is returned.
Definition at line 3013 of file qxmlstream.cpp.
Referenced by Document::load().
 {
    Q_D(const QXmlStreamReader);
    if (d->type == QXmlStreamReader::StartDocument)
        return d->documentVersion;
    return QStringRef();
 }
dtdName()
QStringRef QXmlStreamReader::dtdName () const
If the state() is DTD , this function returns the DTD's name.
Since
4.4
Otherwise an empty string is returned.
Definition at line 2035 of file qxmlstream.cpp.
 {
    Q_D(const QXmlStreamReader);
    if (d->type == QXmlStreamReader::DTD)
        return d->dtdName;
    return QStringRef();
 }
dtdPublicId()
QStringRef QXmlStreamReader::dtdPublicId () const
If the state() is DTD , this function returns the DTD's public identifier.
Since
4.4
Otherwise an empty string is returned.
Definition at line 2053 of file qxmlstream.cpp.
 {
    Q_D(const QXmlStreamReader);
    if (d->type == QXmlStreamReader::DTD)
        return d->dtdPublicId;
    return QStringRef();
 }
dtdSystemId()
QStringRef QXmlStreamReader::dtdSystemId () const
If the state() is DTD , this function returns the DTD's system identifier.
Since
4.4
Otherwise an empty string is returned.
Definition at line 2071 of file qxmlstream.cpp.
 {
    Q_D(const QXmlStreamReader);
    if (d->type == QXmlStreamReader::DTD)
        return d->dtdSystemId;
    return QStringRef();
 }
entityDeclarations()
QXmlStreamEntityDeclarations QXmlStreamReader::entityDeclarations () const
If the state() is DTD , this function returns the DTD's unparsed (external) entity declarations.
Otherwise an empty vector is returned.
The QXmlStreamEntityDeclarations class is defined to be a QVector of QXmlStreamEntityDeclaration.
Definition at line 2017 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamReader);
     if (d->entityDeclarations.size())
         const_cast<QXmlStreamReaderPrivate *>(d)->resolveDtd();
     return d->publicEntityDeclarations;
 }
entityResolver()
QXmlStreamEntityResolver * QXmlStreamReader::entityResolver () const
Returns the entity resolver, or 0 if there is no entity resolver.
Since
4.4
See also
setEntityResolver()
Definition at line 264 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamReader);
     return d->entityResolver;
 }
error()
QXmlStreamReader::Error QXmlStreamReader::error () const
Returns the type of the current error, or NoError if no error occurred.
See also
errorString(), raiseError()
Definition at line 2228 of file qxmlstream.cpp.
Referenced by QPatternist::XsdSchemaParser::addAttribute(), QPatternist::XsdSchemaParser::addAttributeGroup(), QPatternist::XsdSchemaParser::addElement(), QPatternist::XsdSchemaParser::addElementGroup(), QPatternist::XsdSchemaParser::addFacet(), QPatternist::XsdSchemaParser::addIdentityConstraint(), QPatternist::XsdSchemaParser::addNotation(), QPatternist::XsdSchemaParser::addType(), QPatternist::XsdSchemaParser::attributeContentError(), QPatternist::XSLTTokenizer::checkForParseError(), QPatternist::XsdSchemaParser::convertName(), QPatternist::XsdSchemaParser::error(), QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleValidationAttributes(), QPatternist::XSLTTokenizer::handleXSLTVersion(), QPatternist::XSLTTokenizer::insideChoose(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideStylesheetModule(), QPatternist::XSLTTokenizer::insideTemplate(), QPatternist::XSLTTokenizer::outsideDocumentElement(), QPatternist::XsdSchemaParser::parse(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XSLTTokenizer::queueParams(), QPatternist::XSLTTokenizer::queueSelectOrSequenceConstructor(), QPatternist::XSLTTokenizer::queueSorting(), QPatternist::XSLTTokenizer::queueVariableDeclaration(), QPatternist::XSLTTokenizer::readAlternativeAttribute(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), QPatternist::XSLTTokenizer::readToggleAttribute(), QPatternist::XSLTTokenizer::skipBodyOfParam(), QPatternist::XSLTTokenizer::unexpectedContent(), and QPatternist::XsdSchemaParser::validateIdAttribute().
 {
     Q_D(const QXmlStreamReader);
     if (d->type == QXmlStreamReader::Invalid)
         return d->error;
     return NoError;
 }
errorString()
QString QXmlStreamReader::errorString () const
Returns the error message that was set with raiseError().
See also
error(), lineNumber(), columnNumber(), characterOffset()
Definition at line 2216 of file qxmlstream.cpp.
Referenced by QPatternist::XSLTTokenizer::checkForParseError(), QPatternist::XsdSchemaParser::parse(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QPatternist::XSLTTokenizer::unexpectedContent().
 {
     Q_D(const QXmlStreamReader);
     if (d->type == QXmlStreamReader::Invalid)
         return d->errorString;
     return QString();
 }
hasError()
bool QXmlStreamReader::hasError () const inline
Returns true if an error has occurred, otherwise false.
See also
errorString(), error()
Definition at line 396 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::checkForParseError(), QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), and Document::load().
     {
         return error() != NoError;
     }
isCDATA()
bool QXmlStreamReader::isCDATA () const
Returns true if the reader reports characters that stem from a CDATA section; otherwise returns false.
See also
isCharacters(), text()
Definition at line 2982 of file qxmlstream.cpp.
Referenced by Document::load(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->type == QXmlStreamReader::Characters && d->isCDATA;
 }
isCharacters()
bool QXmlStreamReader::isCharacters () const inline
Returns true if tokenType() equals Characters ; otherwise returns false.
See also
isWhitespace(), isCDATA()
Definition at line 339 of file qxmlstream.h.
Referenced by QPatternist::XsdSchemaParser::parseNotation().
 { return tokenType() == Characters; }
isComment()
bool QXmlStreamReader::isComment () const inline
Returns true if tokenType() equals Comment ; otherwise returns false.
Definition at line 342 of file qxmlstream.h.
 { return tokenType() == Comment; }
isDTD()
bool QXmlStreamReader::isDTD () const inline
Returns true if tokenType() equals DTD ; otherwise returns false.
Definition at line 343 of file qxmlstream.h.
 { return tokenType() == DTD; }
isEndDocument()
bool QXmlStreamReader::isEndDocument () const inline
Returns true if tokenType() equals EndDocument ; otherwise returns false.
Definition at line 336 of file qxmlstream.h.
 { return tokenType() == EndDocument; }
isEndElement()
bool QXmlStreamReader::isEndElement () const inline
Returns true if tokenType() equals EndElement ; otherwise returns false.
Definition at line 338 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::insideStylesheetModule(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAppInfo(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseDocumentation(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::parseUnknownDocumentation(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), readNextStartElement(), and skipCurrentElement().
 { return tokenType() == EndElement; }
isEntityReference()
bool QXmlStreamReader::isEntityReference () const inline
Returns true if tokenType() equals EntityReference ; otherwise returns false.
Definition at line 344 of file qxmlstream.h.
Referenced by QPatternist::XsdSchemaParser::parseNotation().
 { return tokenType() == EntityReference; }
isProcessingInstruction()
bool QXmlStreamReader::isProcessingInstruction () const inline
Returns true if tokenType() equals ProcessingInstruction ; otherwise returns false.
Definition at line 345 of file qxmlstream.h.
 { return tokenType() == ProcessingInstruction; }
isStandaloneDocument()
bool QXmlStreamReader::isStandaloneDocument () const
Returns true if this document has been declared standalone in the XML declaration; otherwise returns false.
If no XML declaration has been parsed, this function returns false.
Definition at line 2996 of file qxmlstream.cpp.
Referenced by Document::load().
 {
     Q_D(const QXmlStreamReader);
     return d->standalone;
 }
isStartDocument()
bool QXmlStreamReader::isStartDocument () const inline
Returns true if tokenType() equals StartDocument ; otherwise returns false.
Definition at line 335 of file qxmlstream.h.
 { return tokenType() == StartDocument; }
isStartElement()
bool QXmlStreamReader::isStartElement () const inline
Returns true if tokenType() equals StartElement ; otherwise returns false.
Definition at line 337 of file qxmlstream.h.
Referenced by QPatternist::ElementNamespaceHandler::ElementNamespaceHandler(), QPatternist::XsdSchemaParser::parse(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAppInfo(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseDocumentation(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::parseUnknownDocumentation(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), readNextStartElement(), and skipCurrentElement().
 { return tokenType() == StartElement; }
isWhitespace()
bool QXmlStreamReader::isWhitespace () const
Returns true if the reader reports characters that only consist of white-space; otherwise returns false.
See also
isCharacters(), text()
Definition at line 2971 of file qxmlstream.cpp.
Referenced by QPatternist::MaintainingReader< XSLTTokenLookup >::isWhitespace(), and QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     Q_D(const QXmlStreamReader);
     return d->type == QXmlStreamReader::Characters && d->isWhitespace;
 }
lineNumber()
qint64 QXmlStreamReader::lineNumber () const
Returns the current line number, starting with 1.
See also
columnNumber(), characterOffset()
Definition at line 1959 of file qxmlstream.cpp.
Referenced by QPatternist::XsdSchemaParser::currentSourceLocation(), QPatternist::XSLTTokenizer::currentSourceLocator(), and QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     Q_D(const QXmlStreamReader);
     return d->lineNumber + 1; // in public we start with 1
 }
name()
QStringRef QXmlStreamReader::name () const
Returns the local name of a StartElement, EndElement, or an EntityReference.
See also
namespaceUri(), qualifiedName()
Definition at line 2261 of file qxmlstream.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::ElementNamespaceHandler::ElementNamespaceHandler(), QPatternist::XSLTTokenizer::insideStylesheetModule(), QPatternist::XSLTTokenizer::isElement(), QPatternist::XSLTTokenizer::isStylesheetElement(), Document::load(), QScriptXmlParser::parse(), QPatternist::XsdSchemaParser::parse(), QSvgHandler::parse(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QPatternist::XSLTTokenizer::readToggleAttribute(), QPatternist::XsdSchemaParser::setupBuiltinTypeNames(), QPatternist::XSLTTokenizer::skipBodyOfParam(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::XSLTTokenizer::unexpectedContent(), QPatternist::TagValidationHandler::validate(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->name;
 }
namespaceDeclarations()
QXmlStreamNamespaceDeclarations QXmlStreamReader::namespaceDeclarations () const
If the state() is StartElement , this function returns the element's namespace declarations.
Otherwise an empty vector is returned.
The QXmlStreamNamespaceDeclaration class is defined to be a QVector of QXmlStreamNamespaceDeclaration.
See also
addExtraNamespaceDeclaration(), addExtraNamespaceDeclarations()
Definition at line 2088 of file qxmlstream.cpp.
Referenced by QPatternist::ElementNamespaceHandler::ElementNamespaceHandler(), QPatternist::XsdSchemaParser::parseUnknown(), QPatternist::XsdSchemaParser::parseUnknownDocumentation(), QPatternist::XSLTTokenizer::queueNamespaceDeclarations(), QXmlStreamPrivateTagStack::QXmlStreamPrivateTagStack(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     if (d->publicNamespaceDeclarations.isEmpty() && d->type == StartElement)
         const_cast<QXmlStreamReaderPrivate *>(d)->resolvePublicNamespaces();
     return d->publicNamespaceDeclarations;
 }
namespaceProcessing()
bool QXmlStreamReader::namespaceProcessing () const
This property controls whether or not the stream reader processes namespaces.
the namespace-processing flag of the stream reader
If enabled, the reader processes namespaces, otherwise it does not.
By default, namespace-processing is enabled.
Definition at line 788 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamReader);
     return d->namespaceProcessing;
 }
namespaceUri()
QStringRef QXmlStreamReader::namespaceUri () const
Returns the namespaceUri of a StartElement or EndElement.
See also
name(), qualifiedName()
Definition at line 2272 of file qxmlstream.cpp.
Referenced by QPatternist::ElementNamespaceHandler::ElementNamespaceHandler(), QPatternist::XSLTTokenizer::insideStylesheetModule(), QPatternist::XSLTTokenizer::isXSLT(), Document::load(), QPatternist::XsdSchemaParser::parse(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->namespaceUri;
 }
notationDeclarations()
QXmlStreamNotationDeclarations QXmlStreamReader::notationDeclarations () const
If the state() is DTD , this function returns the DTD's notation declarations.
Otherwise an empty vector is returned.
The QXmlStreamNotationDeclarations class is defined to be a QVector of QXmlStreamNotationDeclaration.
Definition at line 2002 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamReader);
     if (d->notationDeclarations.size())
         const_cast<QXmlStreamReaderPrivate *>(d)->resolveDtd();
     return d->publicNotationDeclarations;
 }
prefix()
QStringRef QXmlStreamReader::prefix () const
Returns the prefix of a StartElement or EndElement.
Since
4.4
See also
name(), qualifiedName()
Definition at line 2308 of file qxmlstream.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     Q_D(const QXmlStreamReader);
     return d->prefix;
 }
processingInstructionData()
QStringRef QXmlStreamReader::processingInstructionData () const
Returns the data of a ProcessingInstruction.
Definition at line 2248 of file qxmlstream.cpp.
Referenced by QSvgHandler::parse(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->processingInstructionData;
 }
processingInstructionTarget()
QStringRef QXmlStreamReader::processingInstructionTarget () const
Returns the target of a ProcessingInstruction.
Definition at line 2239 of file qxmlstream.cpp.
Referenced by QSvgHandler::parse(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->processingInstructionTarget;
 }
qualifiedName()
QStringRef QXmlStreamReader::qualifiedName () const
Returns the qualified name of a StartElement or EndElement;.
A qualified name is the raw name of an element in the XML data. It consists of the namespace prefix, followed by colon, followed by the element's local name. Since the namespace prefix is not unique (the same prefix can point to different namespaces and different prefixes can point to the same namespace), you shouldn't use qualifiedName(), but the resolved namespaceUri() and the attribute's local name().
See also
name(), prefix(), namespaceUri()
Definition at line 2290 of file qxmlstream.cpp.
Referenced by QPatternist::XSLTTokenizer::insideSequenceConstructor().
 {
     Q_D(const QXmlStreamReader);
     return d->qualifiedName;
 }
raiseError()
void QXmlStreamReader::raiseError (const QString & message = QString())
Raises a custom error with an optional error message.
See also
error(), errorString()
Definition at line 2205 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     d->raiseError(CustomError, message);
 }
readElementText() [1/2]
QString QXmlStreamReader::readElementText (ReadElementTextBehaviour behaviour)
Convenience function to be called in case a StartElement was read.
Reads until the corresponding EndElement and returns all text in-between. In case of no error, the current token (see tokenType()) after having called this function is EndElement.
The function concatenates text() when it reads either Characters or EntityReference tokens, but skips ProcessingInstruction and Comment . If the current token is not StartElement, an empty string is returned.
The behaviour defines what happens in case anything else is read before reaching EndElement. The function can include the text from child elements (useful for example for HTML), ignore child elements, or raise an UnexpectedElementError and return what was read so far.
Since
4.6
Definition at line 2151 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     if (isStartElement()) {
         QString result;
         forever {
             switch (readNext()) {
             case Characters:
             case EntityReference:
                 result.insert(result.size(), d->text.unicode(), d->text.size());
                 break;
             case EndElement:
                 return result;
             case ProcessingInstruction:
             case Comment:
                 break;
             case StartElement:
                 if (behaviour == SkipChildElements) {
                     skipCurrentElement();
                     break;
                 } else if (behaviour == IncludeChildElements) {
                     result += readElementText(behaviour);
                     break;
                 }
                 // Fall through (for ErrorOnUnexpectedElement)
             default:
                 if (d->error || behaviour == ErrorOnUnexpectedElement) {
                     if (!d->error)
                         d->raiseError(UnexpectedElementError, QXmlStream::tr("Expected character data."));
                     return result;
                 }
             }
         }
     }
     return QString();
 }
readElementText() [2/2]
QString QXmlStreamReader::readElementText ()
Definition at line 2196 of file qxmlstream.cpp.
 {
     return readElementText(ErrorOnUnexpectedElement);
 }
readNext()
QXmlStreamReader::TokenType QXmlStreamReader::readNext ()
Reads the next token and returns its type.
With one exception, once an error() is reported by readNext(), further reading of the XML stream is not possible. Then atEnd() returns true, hasError() returns true, and this function returns QXmlStreamReader::Invalid.
The exception is when error() returns PrematureEndOfDocumentError. This error is reported when the end of an otherwise well-formed chunk of XML is reached, but the chunk doesn't represent a complete XML document. In that case, parsing can be resumed by calling addData() to add the next chunk of XML, when the stream is being read from a QByteArray, or by waiting for more data to arrive when the stream is being read from a device().
See also
tokenType(), tokenString()
Definition at line 623 of file qxmlstream.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QDeclarativeXMLHttpRequest::findTextCodec(), Document::load(), QScriptXmlParser::parse(), QSvgHandler::parse(), QPatternist::MaintainingReader< XSLTTokenLookup >::readNext(), readNextStartElement(), skipCurrentElement(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and tokenUntil().
 {
     Q_D(QXmlStreamReader);
     if (d->type != Invalid) {
         if (!d->hasCheckedStartDocument)
             if (!d->checkStartDocument())
                 return d->type; // synthetic StartDocument or error
         d->parse();
         if (d->atEnd && d->type != EndDocument && d->type != Invalid)
             d->raiseError(PrematureEndOfDocumentError);
         else if (!d->atEnd && d->type == EndDocument)
             d->raiseWellFormedError(QXmlStream::tr("Extra content at end of document."));
     } else if (d->error == PrematureEndOfDocumentError) {
         // resume error
         d->type = NoToken;
         d->atEnd = false;
         d->token = -1;
         return readNext();
     }
     return d->type;
 }
readNextStartElement()
bool QXmlStreamReader::readNextStartElement ()
Reads until the next start element within the current element.
Returns true when a start element was reached. When the end element was reached, or when an error occurred, false is returned.
The current element is the element matching the most recently parsed start element of which a matching end element has not yet been reached. When the parser has reached the end element, the current element becomes the parent element.
You can traverse a document by repeatedly calling this function while ensuring that the stream reader is not at the end of the document:
    QXmlStreamReader xs(&file);
    while (!xs.atEnd()) {
        if (xs.readNextStartElement())
            std::cout << qPrintable(xs.name().toString()) << std::endl;
    }
This is a convenience function for when you're only concerned with parsing XML elements. The QXmlStream Bookmarks Example makes extensive use of this function.
Since
4.6
See also
readNext()
Definition at line 684 of file qxmlstream.cpp.
 {
     while (readNext() != Invalid) {
         if (isEndElement())
             return false;
         else if (isStartElement())
             return true;
     }
     return false;
 }
setDevice()
void QXmlStreamReader::setDevice (QIODevice * device)
Sets the current device to device.
Setting the device resets the stream to its initial state.
See also
device(), clear()
Definition at line 489 of file qxmlstream.cpp.
Referenced by QSvgIOHandlerPrivate::load(), and QXmlStreamReader().
 {
     Q_D(QXmlStreamReader);
     if (d->deleteDevice) {
         delete d->device;
         d->deleteDevice = false;
     }
     d->device = device;
     d->init();
 }
setEntityResolver()
void QXmlStreamReader::setEntityResolver (QXmlStreamEntityResolver * resolver)
Makes resolver the new entityResolver().
Since
4.4
The stream reader does not take ownership of the resolver. It's the callers responsibility to ensure that the resolver is valid during the entire life-time of the stream reader object, or until another resolver or 0 is set.
See also
entityResolver()
Definition at line 248 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamReader);
     d->entityResolver = resolver;
 }
setNamespaceProcessing()
void QXmlStreamReader::setNamespaceProcessing (bool enable)
Definition at line 782 of file qxmlstream.cpp.
Referenced by QSvgHandler::parse().
 {
     Q_D(QXmlStreamReader);
     d->namespaceProcessing = enable;
 }
skipCurrentElement()
void QXmlStreamReader::skipCurrentElement ()
Reads until the end of the current element, skipping any child nodes.
This function is useful for skipping unknown elements.
The current element is the element matching the most recently parsed start element of which a matching end element has not yet been reached. When the parser has reached the end element, the current element becomes the parent element.
Since
4.6
Definition at line 706 of file qxmlstream.cpp.
 {
     int depth = 1;
     while (depth && readNext() != Invalid) {
         if (isEndElement())
             --depth;
         else if (isStartElement())
             ++depth;
     }
 }
text()
QStringRef QXmlStreamReader::text () const
Returns the text of Characters , Comment , DTD , or EntityReference.
Definition at line 1989 of file qxmlstream.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), Document::load(), QScriptXmlParser::parse(), QSvgHandler::parse(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XSLTTokenizer::readElementText(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->text;
 }
tokenString()
QString QXmlStreamReader::tokenString () const
Returns the reader's current token as string.
See also
tokenType()
Definition at line 798 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamReader);
     return QLatin1String(QXmlStreamReader_tokenTypeString_string +
                          QXmlStreamReader_tokenTypeString_indices[d->type]);
 }
tokenType()
QXmlStreamReader::TokenType QXmlStreamReader::tokenType () const
Returns the type of the current token.
The current token can also be queried with the convenience functions isStartDocument(), isEndDocument(), isStartElement(), isEndElement(), isCharacters(), isComment(), isDTD(), isEntityReference(), and isProcessingInstruction().
See also
tokenString()
Definition at line 656 of file qxmlstream.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleValidationAttributes(), QPatternist::XSLTTokenizer::insideChoose(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideTemplate(), QPatternist::XSLTTokenizer::isElement(), QPatternist::XSLTTokenizer::isStylesheetElement(), QPatternist::XSLTTokenizer::isXSLT(), QPatternist::XSLTTokenizer::parseFallbacksOnly(), QPatternist::XSLTTokenizer::queueNamespaceDeclarations(), QPatternist::XSLTTokenizer::queueParams(), QPatternist::XSLTTokenizer::queueSelectOrSequenceConstructor(), QPatternist::XSLTTokenizer::queueSorting(), QPatternist::XSLTTokenizer::queueVariableDeclaration(), QPatternist::XSLTTokenizer::queueWithParams(), QPatternist::XSLTTokenizer::skipBodyOfParam(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::XSLTTokenizer::unexpectedContent(), and QXmlStreamWriter::writeCurrentToken().
 {
     Q_D(const QXmlStreamReader);
     return d->type;
 }
Properties
d_ptr
QScopedPointer<QXmlStreamReaderPrivate> QXmlStreamReader::d_ptr private
Definition at line 407 of file qxmlstream.h.
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlstream.h
/src/corelib/xml/qxmlstream.cpp