Qt 4.8: QDockAreaLayout Class Reference
QDockAreaLayout Class Reference
#include <qdockarealayout_p.h>
Public Types
enum { EmptyDropAreaSize = 80 }
enum { DockWidgetStateMarker = 0xfd }
Public Functions
void addDockWidget (QInternal::DockPosition pos, QDockWidget *dockWidget, Qt::Orientation orientation)
void apply (bool animate)
void clear ()
void deleteAllLayoutItems ()
QList< int > findSeparator (const QPoint &pos) const
void fitLayout ()
QList< int > gapIndex (const QPoint &pos) const
QRect gapRect (const QList< int > &path) const
void getGrid (QVector< QLayoutStruct > *ver_struct_list, QVector< QLayoutStruct > *hor_struct_list)
QList< int > indexOf (QWidget *dockWidget) const
QList< int > indexOfPlaceHolder (const QString &objectName) const
QDockAreaLayoutInfo * info (const QList< int > &path)
const QDockAreaLayoutInfo * info (const QList< int > &path) const
QDockAreaLayoutInfo * info (QWidget *widget)
bool insertGap (const QList< int > &path, QLayoutItem *dockWidgetItem)
bool isValid () const
QDockAreaLayoutItem & item (const QList< int > &path)
QLayoutItem * itemAt (int *x, int index) const
QRect itemRect (const QList< int > &path) const
void keepSize (QDockWidget *w)
QSize minimumSize () const
void paintSeparators (QPainter *p, QWidget *widget, const QRegion &clip, const QPoint &mouse) const
QLayoutItem * plug (const QList< int > &path)
QDockAreaLayout (QMainWindow *win)
void remove (const QList< int > &path)
bool restoreDockWidget (QDockWidget *dockWidget)
bool restoreState (QDataStream &stream, const QList< QDockWidget *> &widgets, bool testing=false)
void saveState (QDataStream &stream) const
int separatorMove (const QList< int > &separator, const QPoint &origin, const QPoint &dest)
QRect separatorRect (int index) const
QRect separatorRect (const QList< int > &path) const
QRegion separatorRegion () const
void setGrid (QVector< QLayoutStruct > *ver_struct_list, QVector< QLayoutStruct > *hor_struct_list)
QSize sizeHint () const
void splitDockWidget (QDockWidget *after, QDockWidget *dockWidget, Qt::Orientation orientation)
void styleChangedEvent ()
void tabifyDockWidget (QDockWidget *first, QDockWidget *second)
QLayoutItem * takeAt (int *x, int index)
QLayoutItem * unplug (const QList< int > &path)
void updateSeparatorWidgets () const
QSet< QWidget * > usedSeparatorWidgets () const
QSet< QTabBar * > usedTabBars () const
Public Variables
QLayoutItem * centralWidgetItem
QRect centralWidgetRect
Qt::DockWidgetArea corners [4]
QDockAreaLayoutInfo docks [4]
bool fallbackToSizeHints
QMainWindow * mainWindow
QRect rect
int sep
QVector< QWidget * > separatorWidgets
Detailed Description
Definition at line 222 of file qdockarealayout_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
EmptyDropAreaSize
Definition at line 225 of file qdockarealayout_p.h.
 { EmptyDropAreaSize = 80 }; // when a dock area is empty, how "wide" is it?
anonymous enum
anonymous enum
Enumerator
DockWidgetStateMarker
Definition at line 240 of file qdockarealayout_p.h.
 { DockWidgetStateMarker = 0xfd };
Constructors and Destructors
QDockAreaLayout()
QDockAreaLayout::QDockAreaLayout (QMainWindow * win)
Definition at line 2262 of file qdockarealayout.cpp.
                                                  : fallbackToSizeHints(true)
 {
     mainWindow = win;
     sep = win->style()->pixelMetric(QStyle::PM_DockWidgetSeparatorExtent, 0, win);
 #ifndef QT_NO_TABBAR
     const int tabShape = QTabBar::RoundedSouth;
 #else
     const int tabShape = 0;
 #endif
     docks[QInternal::LeftDock]
         = QDockAreaLayoutInfo(&sep, QInternal::LeftDock, Qt::Vertical, tabShape, win);
     docks[QInternal::RightDock]
         = QDockAreaLayoutInfo(&sep, QInternal::RightDock, Qt::Vertical, tabShape, win);
     docks[QInternal::TopDock]
         = QDockAreaLayoutInfo(&sep, QInternal::TopDock, Qt::Horizontal, tabShape, win);
     docks[QInternal::BottomDock]
         = QDockAreaLayoutInfo(&sep, QInternal::BottomDock, Qt::Horizontal, tabShape, win);
     centralWidgetItem = 0;
     corners[Qt::TopLeftCorner] = Qt::TopDockWidgetArea;
     corners[Qt::TopRightCorner] = Qt::TopDockWidgetArea;
     corners[Qt::BottomLeftCorner] = Qt::BottomDockWidgetArea;
     corners[Qt::BottomRightCorner] = Qt::BottomDockWidgetArea;
 }
Functions
addDockWidget()
void QDockAreaLayout::addDockWidget (QInternal::DockPosition pos, QDockWidget * dockWidget, Qt::Orientation orientation)
Definition at line 3002 of file qdockarealayout.cpp.
 {
     QLayoutItem *dockWidgetItem = new QDockWidgetItem(dockWidget);
     QDockAreaLayoutInfo &info = docks[pos];
     if (orientation == info.o || info.item_list.count() <= 1) {
         // empty dock areas, or dock areas containing exactly one widget can have their orientation
         // switched.
         info.o = orientation;
         QDockAreaLayoutItem new_item(dockWidgetItem);
         info.item_list.append(new_item);
 #ifndef QT_NO_TABBAR
         if (info.tabbed && !new_item.skip()) {
             info.updateTabBar();
             info.setCurrentTabId(tabId(new_item));
         }
 #endif
     } else {
 #ifndef QT_NO_TABBAR
         int tbshape = info.tabBarShape;
 #else
         int tbshape = 0;
 #endif
         QDockAreaLayoutInfo new_info(&sep, pos, orientation, tbshape, mainWindow);
         new_info.item_list.append(new QDockAreaLayoutInfo(info));
         new_info.item_list.append(dockWidgetItem);
         info = new_info;
     }
     QList<int> index = indexOfPlaceHolder(dockWidget->objectName());
     if (!index.isEmpty())
         remove(index);
 }
apply()
void QDockAreaLayout::apply (bool animate)
Definition at line 3069 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::apply(), and separatorMove().
 {
     QWidgetAnimator &widgetAnimator = qt_mainwindow_layout(mainWindow)->widgetAnimator;
     for (int i = 0; i < QInternal::DockCount; ++i)
         docks[i].apply(animate);
     if (centralWidgetItem != 0 && !centralWidgetItem->isEmpty()) {
         widgetAnimator.animate(centralWidgetItem->widget(), centralWidgetRect,
                                 animate);
     }
 #ifndef QT_NO_TABBAR
     if (sep == 1)
         updateSeparatorWidgets();
 #endif //QT_NO_TABBAR
 }
clear()
void QDockAreaLayout::clear ()
Definition at line 2864 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::clear().
 {
     for (int i = 0; i < QInternal::DockCount; ++i)
         docks[i].clear();
     rect = QRect();
     centralWidgetRect = QRect();
 }
deleteAllLayoutItems()
void QDockAreaLayout::deleteAllLayoutItems ()
Definition at line 3231 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::deleteAllLayoutItems().
 {
     for (int i = 0; i < QInternal::DockCount; ++i)
         docks[i].deleteAllLayoutItems();
 }
findSeparator()
QList< int > QDockAreaLayout::findSeparator (const QPoint & pos) const
Definition at line 2446 of file qdockarealayout.cpp.
 {
     QList<int> result;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &info = docks[i];
         if (info.isEmpty())
             continue;
         QRect rect = separatorRect(i);
         if (!rect.isNull() && sep == 1)
             rect.adjust(-2, -2, 2, 2);
         if (rect.contains(pos) && !info.hasFixedSize()) {
             result << i;
             break;
         } else if (info.rect.contains(pos)) {
             result = docks[i].findSeparator(pos);
             if (!result.isEmpty()) {
                 result.prepend(i);
                 break;
             }
         }
     }
     return result;
 }
fitLayout()
void QDockAreaLayout::fitLayout ()
Definition at line 2852 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::fitLayout(), and styleChangedEvent().
 {
     QVector<QLayoutStruct> ver_struct_list(3);
     QVector<QLayoutStruct> hor_struct_list(3);
     getGrid(&ver_struct_list, &hor_struct_list);
     qGeomCalc(ver_struct_list, 0, 3, rect.top(), rect.height(), sep);
     qGeomCalc(hor_struct_list, 0, 3, rect.left(), rect.width(), sep);
     setGrid(&ver_struct_list, &hor_struct_list);
 }
gapIndex()
QList< int > QDockAreaLayout::gapIndex (const QPoint & pos) const
Definition at line 2381 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::gapIndex().
 {
     QMainWindow::DockOptions opts = mainWindow->dockOptions();
     bool nestingEnabled = opts & QMainWindow::AllowNestedDocks;
     QDockAreaLayoutInfo::TabMode tabMode = QDockAreaLayoutInfo::NoTabs;
 #ifndef QT_NO_TABBAR
     if (opts & QMainWindow::AllowTabbedDocks
         || opts & QMainWindow::VerticalTabs)
         tabMode = QDockAreaLayoutInfo::AllowTabs;
     if (opts & QMainWindow::ForceTabbedDocks)
         tabMode = QDockAreaLayoutInfo::ForceTabs;
     if (tabMode == QDockAreaLayoutInfo::ForceTabs)
         nestingEnabled = false;
 #endif
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &info = docks[i];
         if (!info.isEmpty() && info.rect.contains(pos)) {
             QList<int> result
                 = docks[i].gapIndex(pos, nestingEnabled, tabMode);
             if (!result.isEmpty())
                 result.prepend(i);
             return result;
         }
     }
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &info = docks[i];
         if (info.isEmpty()) {
             QRect r;
             switch (i) {
                 case QInternal::LeftDock:
                     r = QRect(rect.left(), rect.top(), EmptyDropAreaSize, rect.height());
                     break;
                 case QInternal::RightDock:
                     r = QRect(rect.right() - EmptyDropAreaSize, rect.top(),
                                 EmptyDropAreaSize, rect.height());
                     break;
                 case QInternal::TopDock:
                     r = QRect(rect.left(), rect.top(), rect.width(), EmptyDropAreaSize);
                     break;
                 case QInternal::BottomDock:
                     r = QRect(rect.left(), rect.bottom() - EmptyDropAreaSize,
                                 rect.width(), EmptyDropAreaSize);
                     break;
             }
             if (r.contains(pos)) {
                 if (opts & QMainWindow::ForceTabbedDocks && !info.item_list.isEmpty()) {
                     //in case of ForceTabbedDocks, we pass -1 in order to force the gap to be tabbed
                     //it mustn't be completely empty otherwise it won't work
                     return QList<int>() << i << -1 << 0;
                 } else {
                     return QList<int>() << i << 0;
                 }
             }
         }
     }
     return QList<int>();
 }
gapRect()
QRect QDockAreaLayout::gapRect (const QList< int > & path) const
Definition at line 3263 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::gapRect().
 {
     const QDockAreaLayoutInfo *info = this->info(path);
     if (info == 0)
         return QRect();
     const QList<QDockAreaLayoutItem> &item_list = info->item_list;
     Qt::Orientation o = info->o;
     int index = path.last();
     if (index < 0 || index >= item_list.count())
         return QRect();
     const QDockAreaLayoutItem &item = item_list.at(index);
     if (!(item.flags & QDockAreaLayoutItem::GapItem))
         return QRect();
     QRect result;
 #ifndef QT_NO_TABBAR
     if (info->tabbed) {
         result = info->tabContentRect();
     } else
 #endif
     {
         int pos = item.pos;
         int size = item.size;
         int prev = info->prev(index);
         int next = info->next(index);
         if (prev != -1 && !(item_list.at(prev).flags & QDockAreaLayoutItem::GapItem)) {
             pos += sep;
             size -= sep;
         }
         if (next != -1 && !(item_list.at(next).flags & QDockAreaLayoutItem::GapItem))
             size -= sep;
         QPoint p;
         rpick(o, p) = pos;
         rperp(o, p) = perp(o, info->rect.topLeft());
         QSize s;
         rpick(o, s) = size;
         rperp(o, s) = perp(o, info->rect.size());
         result = QRect(p, s);
     }
     return result;
 }
getGrid()
void QDockAreaLayout::getGrid (QVector< QLayoutStruct > * ver_struct_list, QVector< QLayoutStruct > * hor_struct_list)
Definition at line 2583 of file qdockarealayout.cpp.
Referenced by fitLayout(), and separatorMove().
 {
     QSize center_hint(0, 0);
     QSize center_min(0, 0);
     const bool have_central = centralWidgetItem != 0 && !centralWidgetItem->isEmpty();
     if (have_central) {
         center_hint = centralWidgetRect.size();
         if (!center_hint.isValid())
             center_hint = centralWidgetItem->sizeHint();
         center_min = centralWidgetItem->minimumSize();
     }
     QRect center_rect = rect;
     if (!docks[QInternal::LeftDock].isEmpty())
         center_rect.setLeft(rect.left() + docks[QInternal::LeftDock].rect.width() + sep);
     if (!docks[QInternal::TopDock].isEmpty())
         center_rect.setTop(rect.top() + docks[QInternal::TopDock].rect.height() + sep);
     if (!docks[QInternal::RightDock].isEmpty())
         center_rect.setRight(rect.right() - docks[QInternal::RightDock].rect.width() - sep);
     if (!docks[QInternal::BottomDock].isEmpty())
         center_rect.setBottom(rect.bottom() - docks[QInternal::BottomDock].rect.height() - sep);
     QSize left_hint = docks[QInternal::LeftDock].size();
     if (left_hint.isNull() || fallbackToSizeHints)
         left_hint = docks[QInternal::LeftDock].sizeHint();
     QSize left_min = docks[QInternal::LeftDock].minimumSize();
     QSize left_max = docks[QInternal::LeftDock].maximumSize();
     left_hint = left_hint.boundedTo(left_max).expandedTo(left_min);
     QSize right_hint = docks[QInternal::RightDock].size();
     if (right_hint.isNull() || fallbackToSizeHints)
         right_hint = docks[QInternal::RightDock].sizeHint();
     QSize right_min = docks[QInternal::RightDock].minimumSize();
     QSize right_max = docks[QInternal::RightDock].maximumSize();
     right_hint = right_hint.boundedTo(right_max).expandedTo(right_min);
     QSize top_hint = docks[QInternal::TopDock].size();
     if (top_hint.isNull() || fallbackToSizeHints)
         top_hint = docks[QInternal::TopDock].sizeHint();
     QSize top_min = docks[QInternal::TopDock].minimumSize();
     QSize top_max = docks[QInternal::TopDock].maximumSize();
     top_hint = top_hint.boundedTo(top_max).expandedTo(top_min);
     QSize bottom_hint = docks[QInternal::BottomDock].size();
     if (bottom_hint.isNull() || fallbackToSizeHints)
         bottom_hint = docks[QInternal::BottomDock].sizeHint();
     QSize bottom_min = docks[QInternal::BottomDock].minimumSize();
     QSize bottom_max = docks[QInternal::BottomDock].maximumSize();
     bottom_hint = bottom_hint.boundedTo(bottom_max).expandedTo(bottom_min);
     fallbackToSizeHints = false;
     if (_ver_struct_list != 0) {
         QVector<QLayoutStruct> &ver_struct_list = *_ver_struct_list;
         ver_struct_list.resize(3);
         // top --------------------------------------------------
         ver_struct_list[0].init();
         ver_struct_list[0].stretch = 0;
         ver_struct_list[0].sizeHint = top_hint.height();
         ver_struct_list[0].minimumSize = top_min.height();
         ver_struct_list[0].maximumSize = top_max.height();
         ver_struct_list[0].expansive = false;
         ver_struct_list[0].empty = docks[QInternal::TopDock].isEmpty();
         ver_struct_list[0].pos = docks[QInternal::TopDock].rect.top();
         ver_struct_list[0].size = docks[QInternal::TopDock].rect.height();
         // center --------------------------------------------------
         ver_struct_list[1].init();
         ver_struct_list[1].stretch = center_hint.height();
         bool tl_significant = corners[Qt::TopLeftCorner] == Qt::TopDockWidgetArea
                                     || docks[QInternal::TopDock].isEmpty();
         bool bl_significant = corners[Qt::BottomLeftCorner] == Qt::BottomDockWidgetArea
                                     || docks[QInternal::BottomDock].isEmpty();
         bool tr_significant = corners[Qt::TopRightCorner] == Qt::TopDockWidgetArea
                                     || docks[QInternal::TopDock].isEmpty();
         bool br_significant = corners[Qt::BottomRightCorner] == Qt::BottomDockWidgetArea
                                     || docks[QInternal::BottomDock].isEmpty();
         int left = (tl_significant && bl_significant) ? left_hint.height() : 0;
         int right = (tr_significant && br_significant) ? right_hint.height() : 0;
         ver_struct_list[1].sizeHint = qMax(left, center_hint.height(), right);
         left = (tl_significant && bl_significant) ? left_min.height() : 0;
         right = (tr_significant && br_significant) ? right_min.height() : 0;
         ver_struct_list[1].minimumSize = qMax(left, center_min.height(), right);
         ver_struct_list[1].maximumSize = have_central ? QWIDGETSIZE_MAX : 0;
         ver_struct_list[1].expansive = have_central;
         ver_struct_list[1].empty = docks[QInternal::LeftDock].isEmpty()
                                         && !have_central
                                         && docks[QInternal::RightDock].isEmpty();
         ver_struct_list[1].pos = center_rect.top();
         ver_struct_list[1].size = center_rect.height();
         // bottom --------------------------------------------------
         ver_struct_list[2].init();
         ver_struct_list[2].stretch = 0;
         ver_struct_list[2].sizeHint = bottom_hint.height();
         ver_struct_list[2].minimumSize = bottom_min.height();
         ver_struct_list[2].maximumSize = bottom_max.height();
         ver_struct_list[2].expansive = false;
         ver_struct_list[2].empty = docks[QInternal::BottomDock].isEmpty();
         ver_struct_list[2].pos = docks[QInternal::BottomDock].rect.top();
         ver_struct_list[2].size = docks[QInternal::BottomDock].rect.height();
         for (int i = 0; i < 3; ++i) {
             ver_struct_list[i].sizeHint
                 = qMax(ver_struct_list[i].sizeHint, ver_struct_list[i].minimumSize);
         }
     }
     if (_hor_struct_list != 0) {
         QVector<QLayoutStruct> &hor_struct_list = *_hor_struct_list;
         hor_struct_list.resize(3);
         // left --------------------------------------------------
         hor_struct_list[0].init();
         hor_struct_list[0].stretch = 0;
         hor_struct_list[0].sizeHint = left_hint.width();
         hor_struct_list[0].minimumSize = left_min.width();
         hor_struct_list[0].maximumSize = left_max.width();
         hor_struct_list[0].expansive = false;
         hor_struct_list[0].empty = docks[QInternal::LeftDock].isEmpty();
         hor_struct_list[0].pos = docks[QInternal::LeftDock].rect.left();
         hor_struct_list[0].size = docks[QInternal::LeftDock].rect.width();
         // center --------------------------------------------------
         hor_struct_list[1].init();
         hor_struct_list[1].stretch = center_hint.width();
         bool tl_significant = corners[Qt::TopLeftCorner] == Qt::LeftDockWidgetArea
                                     || docks[QInternal::LeftDock].isEmpty();
         bool tr_significant = corners[Qt::TopRightCorner] == Qt::RightDockWidgetArea
                                     || docks[QInternal::RightDock].isEmpty();
         bool bl_significant = corners[Qt::BottomLeftCorner] == Qt::LeftDockWidgetArea
                                     || docks[QInternal::LeftDock].isEmpty();
         bool br_significant = corners[Qt::BottomRightCorner] == Qt::RightDockWidgetArea
                                     || docks[QInternal::RightDock].isEmpty();
         int top = (tl_significant && tr_significant) ? top_hint.width() : 0;
         int bottom = (bl_significant && br_significant) ? bottom_hint.width() : 0;
         hor_struct_list[1].sizeHint = qMax(top, center_hint.width(), bottom);
         top = (tl_significant && tr_significant) ? top_min.width() : 0;
         bottom = (bl_significant && br_significant) ? bottom_min.width() : 0;
         hor_struct_list[1].minimumSize = qMax(top, center_min.width(), bottom);
         hor_struct_list[1].maximumSize = have_central ? QWIDGETSIZE_MAX : 0;
         hor_struct_list[1].expansive = have_central;
         hor_struct_list[1].empty = !have_central;
         hor_struct_list[1].pos = center_rect.left();
         hor_struct_list[1].size = center_rect.width();
         // right --------------------------------------------------
         hor_struct_list[2].init();
         hor_struct_list[2].stretch = 0;
         hor_struct_list[2].sizeHint = right_hint.width();
         hor_struct_list[2].minimumSize = right_min.width();
         hor_struct_list[2].maximumSize = right_max.width();
         hor_struct_list[2].expansive = false;
         hor_struct_list[2].empty = docks[QInternal::RightDock].isEmpty();
         hor_struct_list[2].pos = docks[QInternal::RightDock].rect.left();
         hor_struct_list[2].size = docks[QInternal::RightDock].rect.width();
         for (int i = 0; i < 3; ++i) {
             hor_struct_list[i].sizeHint
                 = qMax(hor_struct_list[i].sizeHint, hor_struct_list[i].minimumSize);
         }
     }
 }
indexOf()
QList< int > QDockAreaLayout::indexOf (QWidget * dockWidget) const
Definition at line 2369 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::contains(), QMainWindowLayoutState::indexOf(), keepSize(), QMainWindowLayoutState::remove(), QMainWindowLayoutState::restoreState(), splitDockWidget(), and tabifyDockWidget().
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QList<int> result = docks[i].indexOf(dockWidget);
         if (!result.isEmpty()) {
             result.prepend(i);
             return result;
         }
     }
     return QList<int>();
 }
indexOfPlaceHolder()
QList< int > QDockAreaLayout::indexOfPlaceHolder (const QString & objectName) const
Definition at line 2357 of file qdockarealayout.cpp.
Referenced by addDockWidget(), restoreDockWidget(), splitDockWidget(), and tabifyDockWidget().
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QList<int> result = docks[i].indexOfPlaceHolder(objectName);
         if (!result.isEmpty()) {
             result.prepend(i);
             return result;
         }
     }
     return QList<int>();
 }
info() [1/3]
QDockAreaLayoutInfo * QDockAreaLayout::info (const QList< int > & path)
Definition at line 2481 of file qdockarealayout.cpp.
Referenced by addDockWidget(), findSeparator(), gapIndex(), gapRect(), info(), QMainWindowLayoutState::restoreState(), separatorMove(), splitDockWidget(), and tabifyDockWidget().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     if (path.count() == 1)
         return &docks[index];
     return docks[index].info(path.mid(1));
 }
info() [2/3]
const QDockAreaLayoutInfo * QDockAreaLayout::info (const QList< int > & path) const
Definition at line 2493 of file qdockarealayout.cpp.
 {
     return const_cast<QDockAreaLayout*>(this)->info(path);
 }
info() [3/3]
QDockAreaLayoutInfo * QDockAreaLayout::info (QWidget * widget)
Definition at line 2471 of file qdockarealayout.cpp.
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         if (QDockAreaLayoutInfo *result = docks[i].info(widget))
             return result;
     }
     return 0;
 }
insertGap()
bool QDockAreaLayout::insertGap (const QList< int > & path, QLayoutItem * dockWidgetItem)
Definition at line 2548 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::insertGap().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     return docks[index].insertGap(path.mid(1), dockWidgetItem);
 }
isValid()
bool QDockAreaLayout::isValid () const
Definition at line 2288 of file qdockarealayout.cpp.
Referenced by styleChangedEvent().
 {
     return rect.isValid();
 }
item()
QDockAreaLayoutItem & QDockAreaLayout::item (const QList< int > & path)
Definition at line 2498 of file qdockarealayout.cpp.
Referenced by gapRect(), QMainWindowLayoutState::item(), keepSize(), and restoreDockWidget().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     return docks[index].item(path.mid(1));
 }
itemAt()
QLayoutItem * QDockAreaLayout::itemAt (int * x, int index) const
Definition at line 3196 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::itemAt().
 {
     Q_ASSERT(x != 0);
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &dock = docks[i];
         if (QLayoutItem *ret = dock.itemAt(x, index))
             return ret;
     }
     if (centralWidgetItem && (*x)++ == index)
         return centralWidgetItem;
     return 0;
 }
itemRect()
QRect QDockAreaLayout::itemRect (const QList< int > & path) const
Definition at line 2506 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::itemRect().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     return docks[index].itemRect(path.mid(1));
 }
keepSize()
void QDockAreaLayout::keepSize (QDockWidget * w)
Definition at line 3311 of file qdockarealayout.cpp.
 {
     QList<int> path = indexOf(w);
     if (path.isEmpty())
         return;
     QDockAreaLayoutItem &item = this->item(path);
     if (item.size != -1)
         item.flags |= QDockAreaLayoutItem::KeepSize;
 }
minimumSize()
QSize QDockAreaLayout::minimumSize () const
Definition at line 2923 of file qdockarealayout.cpp.
Referenced by getGrid(), and QMainWindowLayoutState::minimumSize().
 {
     int left_sep = 0;
     int right_sep = 0;
     int top_sep = 0;
     int bottom_sep = 0;
     if (centralWidgetItem != 0) {
         left_sep = docks[QInternal::LeftDock].isEmpty() ? 0 : sep;
         right_sep = docks[QInternal::RightDock].isEmpty() ? 0 : sep;
         top_sep = docks[QInternal::TopDock].isEmpty() ? 0 : sep;
         bottom_sep = docks[QInternal::BottomDock].isEmpty() ? 0 : sep;
     }
     QSize left = docks[QInternal::LeftDock].minimumSize() + QSize(left_sep, 0);
     QSize right = docks[QInternal::RightDock].minimumSize() + QSize(right_sep, 0);
     QSize top = docks[QInternal::TopDock].minimumSize() + QSize(0, top_sep);
     QSize bottom = docks[QInternal::BottomDock].minimumSize() + QSize(0, bottom_sep);
     QSize center = centralWidgetItem == 0 ? QSize(0, 0) : centralWidgetItem->minimumSize();
     int row1 = top.width();
     int row2 = left.width() + center.width() + right.width();
     int row3 = bottom.width();
     int col1 = left.height();
     int col2 = top.height() + center.height() + bottom.height();
     int col3 = right.height();
     if (corners[Qt::TopLeftCorner] == Qt::LeftDockWidgetArea)
         row1 += left.width();
     else
         col1 += top.height();
     if (corners[Qt::TopRightCorner] == Qt::RightDockWidgetArea)
         row1 += right.width();
     else
         col3 += top.height();
     if (corners[Qt::BottomLeftCorner] == Qt::LeftDockWidgetArea)
         row3 += left.width();
     else
         col1 += bottom.height();
     if (corners[Qt::BottomRightCorner] == Qt::RightDockWidgetArea)
         row3 += right.width();
     else
         col3 += bottom.height();
     return QSize(qMax(row1, row2, row3), qMax(col1, col2, col3));
 }
paintSeparators()
void QDockAreaLayout::paintSeparators (QPainter * p, QWidget * widget, const QRegion & clip, const QPoint & mouse) const
Definition at line 3085 of file qdockarealayout.cpp.
 {
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &dock = docks[i];
         if (dock.isEmpty())
             continue;
         QRect r = separatorRect(i);
         if (clip.contains(r) && !dock.hasFixedSize()) {
             Qt::Orientation opposite = dock.o == Qt::Horizontal
                                         ? Qt::Vertical : Qt::Horizontal;
             paintSep(p, widget, r, opposite, r.contains(mouse));
         }
         if (clip.contains(dock.rect))
             dock.paintSeparators(p, widget, clip, mouse);
     }
 }
plug()
QLayoutItem * QDockAreaLayout::plug (const QList< int > & path)
Definition at line 2556 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::plug().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     return docks[index].plug(path.mid(1));
 }
remove()
void QDockAreaLayout::remove (const QList< int > & path)
Definition at line 2572 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::remove().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     docks[index].remove(path.mid(1));
 }
restoreDockWidget()
bool QDockAreaLayout::restoreDockWidget (QDockWidget * dockWidget)
Definition at line 2973 of file qdockarealayout.cpp.
 {
     QList<int> index = indexOfPlaceHolder(dockWidget->objectName());
     if (index.isEmpty())
         return false;
     QDockAreaLayoutItem &item = this->item(index);
     QPlaceHolderItem *placeHolder = item.placeHolderItem;
     Q_ASSERT(placeHolder != 0);
     item.widgetItem = new QDockWidgetItem(dockWidget);
     if (placeHolder->window) {
         QDesktopWidget desktop;
         QRect r = constrainedRect(placeHolder->topLevelRect, desktop.screenGeometry(dockWidget));
         dockWidget->d_func()->setWindowState(true, true, r);
     }
     dockWidget->setVisible(!placeHolder->hidden);
 #ifdef Q_WS_X11
     if (placeHolder->window) // gets rid of the X11BypassWindowManager window flag
         dockWidget->d_func()->setWindowState(true);
 #endif
     item.placeHolderItem = 0;
     delete placeHolder;
     return true;
 }
restoreState()
bool QDockAreaLayout::restoreState (QDataStream & stream, const QList< QDockWidget *> & widgets, bool testing = false)
Definition at line 2315 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::checkFormat(), and QMainWindowLayoutState::restoreState().
 {
     QList<QDockWidget*> dockwidgets = _dockwidgets;
     int cnt;
     stream >> cnt;
     for (int i = 0; i < cnt; ++i) {
         int pos;
         stream >> pos;
         QSize size;
         stream >> size;
         if (!testing) {
             docks[pos].rect = QRect(QPoint(0, 0), size);
         }
         if (!docks[pos].restoreState(stream, dockwidgets, testing)) {
             stream.setStatus(QDataStream::ReadCorruptData);
             return false;
         }
     }
     QSize size;
     stream >> size;
     centralWidgetRect = QRect(QPoint(0, 0), size);
     bool ok = stream.status() == QDataStream::Ok;
     if (ok) {
         int cornerData[4];
         for (int i = 0; i < 4; ++i)
             stream >> cornerData[i];
         if (stream.status() == QDataStream::Ok) {
             for (int i = 0; i < 4; ++i)
                 corners[i] = static_cast<Qt::DockWidgetArea>(cornerData[i]);
         }
         if (!testing)
             fallbackToSizeHints = false;
     }
     return ok;
 }
saveState()
void QDockAreaLayout::saveState (QDataStream & stream) const
Definition at line 2293 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::saveState().
 {
     stream << (uchar) DockWidgetStateMarker;
     int cnt = 0;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         if (!docks[i].item_list.isEmpty())
             ++cnt;
     }
     stream << cnt;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         if (docks[i].item_list.isEmpty())
             continue;
         stream << i << docks[i].rect.size();
         docks[i].saveState(stream);
     }
     stream << centralWidgetRect.size();
     for (int i = 0; i < 4; ++i)
         stream << static_cast<int>(corners[i]);
 }
separatorMove()
int QDockAreaLayout::separatorMove (const QList< int > & separator, const QPoint & origin, const QPoint & dest)
Definition at line 3119 of file qdockarealayout.cpp.
Referenced by QMainWindowLayout::timerEvent().
 {
     int delta = 0;
     int index = separator.last();
     if (separator.count() > 1) {
         QDockAreaLayoutInfo *info = this->info(separator);
         delta = pick(info->o, dest - origin);
         if (delta != 0)
             delta = info->separatorMove(index, delta);
         info->apply(false);
         return delta;
     }
     QVector<QLayoutStruct> list;
     if (index == QInternal::LeftDock || index == QInternal::RightDock)
         getGrid(0, &list);
     else
         getGrid(&list, 0);
     int sep_index = index == QInternal::LeftDock || index == QInternal::TopDock
                         ? 0 : 1;
     Qt::Orientation o = index == QInternal::LeftDock || index == QInternal::RightDock
                         ? Qt::Horizontal
                         : Qt::Vertical;
     delta = pick(o, dest - origin);
     delta = separatorMoveHelper(list, sep_index, delta, sep);
     if (index == QInternal::LeftDock || index == QInternal::RightDock)
         setGrid(0, &list);
     else
         setGrid(&list, 0);
     apply(false);
     return delta;
 }
separatorRect() [1/2]
QRect QDockAreaLayout::separatorRect (int index) const
Definition at line 2514 of file qdockarealayout.cpp.
Referenced by findSeparator(), paintSeparators(), separatorRect(), separatorRegion(), and updateSeparatorWidgets().
 {
     const QDockAreaLayoutInfo &dock = docks[index];
     if (dock.isEmpty())
         return QRect();
     QRect r = dock.rect;
     switch (index) {
         case QInternal::LeftDock:
             return QRect(r.right() + 1, r.top(), sep, r.height());
         case QInternal::RightDock:
             return QRect(r.left() - sep, r.top(), sep, r.height());
         case QInternal::TopDock:
             return QRect(r.left(), r.bottom() + 1, r.width(), sep);
         case QInternal::BottomDock:
             return QRect(r.left(), r.top() - sep, r.width(), sep);
         default:
             break;
     }
     return QRect();
 }
separatorRect() [2/2]
QRect QDockAreaLayout::separatorRect (const QList< int > & path) const
Definition at line 2535 of file qdockarealayout.cpp.
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     if (path.count() == 1)
         return separatorRect(index);
     else
         return docks[index].separatorRect(path.mid(1));
 }
separatorRegion()
QRegion QDockAreaLayout::separatorRegion () const
Definition at line 3104 of file qdockarealayout.cpp.
Referenced by QMainWindowLayout::hover(), and QMainWindowLayout::timerEvent().
 {
     QRegion result;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &dock = docks[i];
         if (dock.isEmpty())
             continue;
         result |= separatorRect(i);
         result |= dock.separatorRegion();
     }
     return result;
 }
setGrid()
void QDockAreaLayout::setGrid (QVector< QLayoutStruct > * ver_struct_list, QVector< QLayoutStruct > * hor_struct_list)
Definition at line 2756 of file qdockarealayout.cpp.
Referenced by fitLayout(), and separatorMove().
 {
     // top ---------------------------------------------------
     if (!docks[QInternal::TopDock].isEmpty()) {
         QRect r = docks[QInternal::TopDock].rect;
         if (hor_struct_list != 0) {
             r.setLeft(corners[Qt::TopLeftCorner] == Qt::TopDockWidgetArea
                 || docks[QInternal::LeftDock].isEmpty()
                 ? rect.left() : hor_struct_list->at(1).pos);
             r.setRight(corners[Qt::TopRightCorner] == Qt::TopDockWidgetArea
                 || docks[QInternal::RightDock].isEmpty()
                 ? rect.right() : hor_struct_list->at(2).pos - sep - 1);
         }
         if (ver_struct_list != 0) {
             r.setTop(rect.top());
             r.setBottom(ver_struct_list->at(1).pos - sep - 1);
         }
         docks[QInternal::TopDock].rect = r;
         docks[QInternal::TopDock].fitItems();
     }
     // bottom ---------------------------------------------------
     if (!docks[QInternal::BottomDock].isEmpty()) {
         QRect r = docks[QInternal::BottomDock].rect;
         if (hor_struct_list != 0) {
             r.setLeft(corners[Qt::BottomLeftCorner] == Qt::BottomDockWidgetArea
                         || docks[QInternal::LeftDock].isEmpty()
                             ? rect.left() : hor_struct_list->at(1).pos);
             r.setRight(corners[Qt::BottomRightCorner] == Qt::BottomDockWidgetArea
                         || docks[QInternal::RightDock].isEmpty()
                             ? rect.right() : hor_struct_list->at(2).pos - sep - 1);
         }
         if (ver_struct_list != 0) {
             r.setTop(ver_struct_list->at(2).pos);
             r.setBottom(rect.bottom());
         }
         docks[QInternal::BottomDock].rect = r;
         docks[QInternal::BottomDock].fitItems();
     }
     // left ---------------------------------------------------
     if (!docks[QInternal::LeftDock].isEmpty()) {
         QRect r = docks[QInternal::LeftDock].rect;
         if (hor_struct_list != 0) {
             r.setLeft(rect.left());
             r.setRight(hor_struct_list->at(1).pos - sep - 1);
         }
         if (ver_struct_list != 0) {
             r.setTop(corners[Qt::TopLeftCorner] == Qt::LeftDockWidgetArea
                 || docks[QInternal::TopDock].isEmpty()
                 ? rect.top() : ver_struct_list->at(1).pos);
             r.setBottom(corners[Qt::BottomLeftCorner] == Qt::LeftDockWidgetArea
                 || docks[QInternal::BottomDock].isEmpty()
                 ? rect.bottom() : ver_struct_list->at(2).pos - sep - 1);
         }
         docks[QInternal::LeftDock].rect = r;
         docks[QInternal::LeftDock].fitItems();
     }
     // right ---------------------------------------------------
     if (!docks[QInternal::RightDock].isEmpty()) {
         QRect r = docks[QInternal::RightDock].rect;
         if (hor_struct_list != 0) {
             r.setLeft(hor_struct_list->at(2).pos);
             r.setRight(rect.right());
         }
         if (ver_struct_list != 0) {
             r.setTop(corners[Qt::TopRightCorner] == Qt::RightDockWidgetArea
                         || docks[QInternal::TopDock].isEmpty()
                             ? rect.top() : ver_struct_list->at(1).pos);
             r.setBottom(corners[Qt::BottomRightCorner] == Qt::RightDockWidgetArea
                         || docks[QInternal::BottomDock].isEmpty()
                             ? rect.bottom() : ver_struct_list->at(2).pos - sep - 1);
         }
         docks[QInternal::RightDock].rect = r;
         docks[QInternal::RightDock].fitItems();
     }
     // center ---------------------------------------------------
     if (hor_struct_list != 0) {
         centralWidgetRect.setLeft(hor_struct_list->at(1).pos);
         centralWidgetRect.setWidth(hor_struct_list->at(1).size);
     }
     if (ver_struct_list != 0) {
         centralWidgetRect.setTop(ver_struct_list->at(1).pos);
         centralWidgetRect.setHeight(ver_struct_list->at(1).size);
     }
 }
sizeHint()
QSize QDockAreaLayout::sizeHint () const
Definition at line 2873 of file qdockarealayout.cpp.
Referenced by getGrid(), and QMainWindowLayoutState::sizeHint().
 {
     int left_sep = 0;
     int right_sep = 0;
     int top_sep = 0;
     int bottom_sep = 0;
     if (centralWidgetItem != 0) {
         left_sep = docks[QInternal::LeftDock].isEmpty() ? 0 : sep;
         right_sep = docks[QInternal::RightDock].isEmpty() ? 0 : sep;
         top_sep = docks[QInternal::TopDock].isEmpty() ? 0 : sep;
         bottom_sep = docks[QInternal::BottomDock].isEmpty() ? 0 : sep;
     }
     QSize left = docks[QInternal::LeftDock].sizeHint() + QSize(left_sep, 0);
     QSize right = docks[QInternal::RightDock].sizeHint() + QSize(right_sep, 0);
     QSize top = docks[QInternal::TopDock].sizeHint() + QSize(0, top_sep);
     QSize bottom = docks[QInternal::BottomDock].sizeHint() + QSize(0, bottom_sep);
     QSize center = centralWidgetItem == 0 ? QSize(0, 0) : centralWidgetItem->sizeHint();
     int row1 = top.width();
     int row2 = left.width() + center.width() + right.width();
     int row3 = bottom.width();
     int col1 = left.height();
     int col2 = top.height() + center.height() + bottom.height();
     int col3 = right.height();
     if (corners[Qt::TopLeftCorner] == Qt::LeftDockWidgetArea)
         row1 += left.width();
     else
         col1 += top.height();
     if (corners[Qt::TopRightCorner] == Qt::RightDockWidgetArea)
         row1 += right.width();
     else
         col3 += top.height();
     if (corners[Qt::BottomLeftCorner] == Qt::LeftDockWidgetArea)
         row3 += left.width();
     else
         col1 += bottom.height();
     if (corners[Qt::BottomRightCorner] == Qt::RightDockWidgetArea)
         row3 += right.width();
     else
         col3 += bottom.height();
     return QSize(qMax(row1, row2, row3), qMax(col1, col2, col3));
 }
splitDockWidget()
void QDockAreaLayout::splitDockWidget (QDockWidget * after, QDockWidget * dockWidget, Qt::Orientation orientation)
Definition at line 3052 of file qdockarealayout.cpp.
 {
     QList<int> path = indexOf(after);
     if (path.isEmpty())
         return;
     QDockAreaLayoutInfo *info = this->info(path);
     Q_ASSERT(info != 0);
     info->split(path.last(), orientation, new QDockWidgetItem(dockWidget));
     QList<int> index = indexOfPlaceHolder(dockWidget->objectName());
     if (!index.isEmpty())
         remove(index);
 }
styleChangedEvent()
void QDockAreaLayout::styleChangedEvent ()
Definition at line 3321 of file qdockarealayout.cpp.
 {
     sep = mainWindow->style()->pixelMetric(QStyle::PM_DockWidgetSeparatorExtent, 0, mainWindow);
     if (isValid())
         fitLayout();
 }
tabifyDockWidget()
void QDockAreaLayout::tabifyDockWidget (QDockWidget * first, QDockWidget * second)
Definition at line 3037 of file qdockarealayout.cpp.
 {
     QList<int> path = indexOf(first);
     if (path.isEmpty())
         return;
     QDockAreaLayoutInfo *info = this->info(path);
     Q_ASSERT(info != 0);
     info->tab(path.last(), new QDockWidgetItem(second));
     QList<int> index = indexOfPlaceHolder(second->objectName());
     if (!index.isEmpty())
         remove(index);
 }
takeAt()
QLayoutItem * QDockAreaLayout::takeAt (int * x, int index)
Definition at line 3212 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::takeAt().
 {
     Q_ASSERT(x != 0);
     for (int i = 0; i < QInternal::DockCount; ++i) {
         QDockAreaLayoutInfo &dock = docks[i];
         if (QLayoutItem *ret = dock.takeAt(x, index))
             return ret;
     }
     if (centralWidgetItem && (*x)++ == index) {
         QLayoutItem *ret = centralWidgetItem;
         centralWidgetItem = 0;
         return ret;
     }
     return 0;
 }
unplug()
QLayoutItem * QDockAreaLayout::unplug (const QList< int > & path)
Definition at line 2564 of file qdockarealayout.cpp.
Referenced by QMainWindowLayoutState::unplug().
 {
     Q_ASSERT(!path.isEmpty());
     const int index = path.first();
     Q_ASSERT(index >= 0 && index < QInternal::DockCount);
     return docks[index].unplug(path.mid(1));
 }
updateSeparatorWidgets()
void QDockAreaLayout::updateSeparatorWidgets () const
Definition at line 3163 of file qdockarealayout.cpp.
Referenced by apply().
 {
     int j = 0;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &dock = docks[i];
         if (dock.isEmpty())
             continue;
         QWidget *sepWidget;
         if (j < separatorWidgets.size()) {
             sepWidget = separatorWidgets.at(j);
         } else {
             sepWidget = qt_mainwindow_layout(mainWindow)->getSeparatorWidget();
             separatorWidgets.append(sepWidget);
         }
         j++;
 #ifndef QT_MAC_USE_COCOA
         sepWidget->raise();
 #endif
         QRect sepRect = separatorRect(i).adjusted(-2, -2, 2, 2);
         sepWidget->setGeometry(sepRect);
         sepWidget->setMask( QRegion(separatorRect(i).translated( - sepRect.topLeft())));
         sepWidget->show();
     }
     for (int i = j; i < separatorWidgets.size(); ++i)
         separatorWidgets.at(i)->hide();
     separatorWidgets.resize(j);
 }
usedSeparatorWidgets()
QSet< QWidget * > QDockAreaLayout::usedSeparatorWidgets () const
Definition at line 3249 of file qdockarealayout.cpp.
Referenced by QMainWindowLayout::applyState().
 {
     QSet<QWidget*> result;
     for (int i = 0; i < separatorWidgets.count(); ++i)
         result << separatorWidgets.at(i);
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &dock = docks[i];
         result += dock.usedSeparatorWidgets();
     }
     return result;
 }
usedTabBars()
QSet< QTabBar * > QDockAreaLayout::usedTabBars () const
Definition at line 3238 of file qdockarealayout.cpp.
Referenced by QMainWindowLayout::applyState().
 {
     QSet<QTabBar*> result;
     for (int i = 0; i < QInternal::DockCount; ++i) {
         const QDockAreaLayoutInfo &dock = docks[i];
         result += dock.usedTabBars();
     }
     return result;
 }
Properties
centralWidgetItem
QLayoutItem* QDockAreaLayout::centralWidgetItem
Definition at line 229 of file qdockarealayout_p.h.
Referenced by apply(), QMainWindowLayoutState::centralWidget(), QMainWindowLayoutState::contains(), QMainWindowLayoutState::deleteCentralWidgetItem(), getGrid(), itemAt(), minimumSize(), QDockAreaLayout(), QMainWindowLayoutState::setCentralWidget(), QMainWindowLayout::setCentralWidget(), sizeHint(), and takeAt().
centralWidgetRect
QRect QDockAreaLayout::centralWidgetRect
Definition at line 231 of file qdockarealayout_p.h.
Referenced by apply(), clear(), getGrid(), restoreState(), saveState(), and setGrid().
corners
Qt::DockWidgetArea QDockAreaLayout::corners[4]
Definition at line 227 of file qdockarealayout_p.h.
Referenced by getGrid(), minimumSize(), QDockAreaLayout(), restoreState(), saveState(), setGrid(), and sizeHint().
docks
QDockAreaLayoutInfo QDockAreaLayout::docks[4]
Definition at line 233 of file qdockarealayout_p.h.
Referenced by addDockWidget(), apply(), clear(), deleteAllLayoutItems(), findSeparator(), gapIndex(), getGrid(), indexOf(), indexOfPlaceHolder(), info(), insertGap(), item(), itemAt(), itemRect(), minimumSize(), paintSeparators(), plug(), QDockAreaLayout(), remove(), restoreState(), saveState(), separatorRect(), separatorRegion(), setGrid(), sizeHint(), takeAt(), unplug(), updateSeparatorWidgets(), QMainWindowLayout::updateTabBarShapes(), usedSeparatorWidgets(), and usedTabBars().
fallbackToSizeHints
bool QDockAreaLayout::fallbackToSizeHints
Definition at line 235 of file qdockarealayout_p.h.
Referenced by getGrid(), restoreState(), and QMainWindowLayout::setCentralWidget().
mainWindow
QMainWindow* QDockAreaLayout::mainWindow
Definition at line 230 of file qdockarealayout_p.h.
Referenced by addDockWidget(), apply(), gapIndex(), QDockAreaLayout(), styleChangedEvent(), and updateSeparatorWidgets().
rect
QRect QDockAreaLayout::rect
Definition at line 228 of file qdockarealayout_p.h.
Referenced by clear(), findSeparator(), QMainWindowLayoutState::fitLayout(), fitLayout(), gapIndex(), getGrid(), isValid(), and setGrid().
sep
int QDockAreaLayout::sep
Definition at line 234 of file qdockarealayout_p.h.
Referenced by addDockWidget(), apply(), findSeparator(), fitLayout(), gapRect(), getGrid(), minimumSize(), QDockAreaLayout(), separatorMove(), separatorRect(), setGrid(), sizeHint(), and styleChangedEvent().
separatorWidgets
QVector<QWidget*> QDockAreaLayout::separatorWidgets mutable
Definition at line 236 of file qdockarealayout_p.h.
Referenced by updateSeparatorWidgets(), and usedSeparatorWidgets().
The documentation for this class was generated from the following files:
/src/gui/widgets/qdockarealayout_p.h
/src/gui/widgets/qdockarealayout.cpp