Qt 4.8: QTextTableCell Class Reference
QTextTableCell Class Reference
The QTextTableCell class represents the properties of a cell in a QTextTable.
#include <qtexttable.h>
Public Functions
QTextFrame::iterator begin () const
Returns a frame iterator pointing to the beginning of the table's cell.
int column () const
Returns the number of the column in the table that contains this cell.
int columnSpan () const
Returns the number of columns this cell spans.
QTextFrame::iterator end () const
Returns a frame iterator pointing to the end of the table's cell.
QTextCursor firstCursorPosition () const
Returns the first valid cursor position in this cell.
int firstPosition () const
Returns the first valid position in the document occupied by this cell.
QTextCharFormat format () const
Returns the cell's character format.
bool isValid () const
Returns true if this is a valid table cell; otherwise returns false.
QTextCursor lastCursorPosition () const
Returns the last valid cursor position in this cell.
int lastPosition () const
Returns the last valid position in the document occupied by this cell.
bool operator!= (const QTextTableCell &other) const
Returns true if this cell object and the other cell object describe different cells; otherwise returns false.
QTextTableCell & operator= (const QTextTableCell &o)
Assigns the other table cell to this table cell.
bool operator== (const QTextTableCell &other) const
Returns true if this cell object and the other cell object describe the same cell; otherwise returns false.
QTextTableCell ()
Constructs an invalid table cell.
QTextTableCell (const QTextTableCell &o)
Copy constructor.
int row () const
Returns the number of the row in the table that contains this cell.
int rowSpan () const
Returns the number of rows this cell spans.
void setFormat (const QTextCharFormat &format)
Sets the cell's character format to format.
int tableCellFormatIndex () const
Returns the index of the tableCell's format in the document's internal list of formats.
~QTextTableCell ()
Destroys the table cell.
Private Functions
QTextTableCell (const QTextTable *t, int f)
Properties
int fragment
const QTextTable * table
Friends
class QTextTable
Detailed Description
The QTextTableCell class represents the properties of a cell in a QTextTable.
Note
This class or function is reentrant.
Table cells are pieces of document structure that belong to a table. The table orders cells into particular rows and columns; cells can also span multiple columns and rows.
Cells are usually created when a table is inserted into a document with QTextCursor::insertTable(), but they are also created and destroyed when a table is resized.
Cells contain information about their location in a table; you can obtain the row() and column() numbers of a cell, and its rowSpan() and columnSpan().
The format() of a cell describes the default character format of its contents. The firstCursorPosition() and lastCursorPosition() functions are used to obtain the extent of the cell in the document.
See also
QTextTable QTextTableFormat
Definition at line 59 of file qtexttable.h.
Constructors and Destructors
QTextTableCell() [1/3]
QTextTableCell::QTextTableCell () inline
Constructs an invalid table cell.
See also
isValid()
Definition at line 62 of file qtexttable.h.
 : table(0) {}
~QTextTableCell()
QTextTableCell::~QTextTableCell () inline
Destroys the table cell.
Definition at line 63 of file qtexttable.h.
 {}
QTextTableCell() [2/3]
QTextTableCell::QTextTableCell (const QTextTableCell & other) inline
Copy constructor.
Creates a new QTextTableCell object based on the other cell.
Definition at line 64 of file qtexttable.h.
 : table(o.table), fragment(o.fragment) {}
QTextTableCell() [3/3]
QTextTableCell::QTextTableCell (const QTextTable * t, int f) inline private
Definition at line 96 of file qtexttable.h.
         : table(t), fragment(f) {}
Functions
begin()
QTextFrame::iterator QTextTableCell::begin () const
Returns a frame iterator pointing to the beginning of the table's cell.
See also
end()
Definition at line 306 of file qtexttable.cpp.
Referenced by QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), and QTextDocumentLayoutPrivate::layoutTable().
 {
     QTextDocumentPrivate *p = table->docHandle();
     int b = p->blockMap().findNode(firstPosition());
     int e = p->blockMap().findNode(lastPosition()+1);
     return QTextFrame::iterator(const_cast<QTextTable *>(table), b, b, e);
 }
column()
int QTextTableCell::column () const
Returns the number of the column in the table that contains this cell.
See also
row()
Definition at line 201 of file qtexttable.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), QTextCursorPrivate::adjustCursor(), QTextTableData::cellPosition(), QTextTableData::cellRect(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextControlPrivate::gotoNextTableCell(), QTextControlPrivate::gotoPreviousTableCell(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutTable(), QTextTable::mergeCells(), QTextCursorPrivate::movePosition(), QTextCursorPrivate::selectedTableCells(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), and QTextTable::splitCell().
 {
     const QTextTablePrivate *tp = table->d_func();
     if (tp->dirty)
         tp->update();
     int idx = tp->findCellIndex(fragment);
     if (idx == -1)
         return idx;
     return tp->cellIndices.at(idx) % tp->nCols;
 }
columnSpan()
int QTextTableCell::columnSpan () const
Returns the number of columns this cell spans.
The default is 1.
See also
rowSpan()
Definition at line 228 of file qtexttable.cpp.
Referenced by QTextTableData::cellRect(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextControlPrivate::gotoNextTableCell(), QTextDocumentLayoutPrivate::layoutTable(), QTextCursorPrivate::movePosition(), QTextHtmlImporter::TableCellIterator::operator++(), QTextCursorPrivate::selectedTableCells(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), and QTextOdfWriter::writeFrame().
 {
     return format().tableCellColumnSpan();
 }
end()
QTextFrame::iterator QTextTableCell::end () const
Returns a frame iterator pointing to the end of the table's cell.
See also
begin()
Definition at line 319 of file qtexttable.cpp.
 {
     QTextDocumentPrivate *p = table->docHandle();
     int b = p->blockMap().findNode(firstPosition());
     int e = p->blockMap().findNode(lastPosition()+1);
     return QTextFrame::iterator(const_cast<QTextTable *>(table), e, b, e);
 }
firstCursorPosition()
QTextCursor QTextTableCell::firstCursorPosition () const
Returns the first valid cursor position in this cell.
See also
lastCursorPosition()
Definition at line 249 of file qtexttable.cpp.
Referenced by QTextControlPrivate::gotoNextTableCell(), QTextControlPrivate::gotoPreviousTableCell(), and QTextTable::mergeCells().
 {
     return QTextCursor(table->d_func()->pieceTable, firstPosition());
 }
firstPosition()
int QTextTableCell::firstPosition () const
Returns the first valid position in the document occupied by this cell.
Warning
This function is not part of the public interface.
Definition at line 273 of file qtexttable.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), adjustContextSelectionsForCell(), QTextCursorPrivate::adjustCursor(), begin(), QTextCursorPrivate::clearCells(), QTextCopyHelper::copy(), end(), firstCursorPosition(), QTextDocumentLayoutPrivate::hitTest(), QTextTable::mergeCells(), QTextCursorPrivate::movePosition(), QTextHtmlImporter::processBlockNode(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), and QTextTable::splitCell().
 {
     QTextDocumentPrivate *p = table->docHandle();
     return p->fragmentMap().position(fragment) + 1;
 }
format()
QTextCharFormat QTextTableCell::format () const
Returns the cell's character format.
Definition at line 153 of file qtexttable.cpp.
Referenced by QTextTableData::cellPosition(), columnSpan(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutTable(), QTextTable::mergeCells(), QTextHtmlImporter::processBlockNode(), rowSpan(), setFormat(), QTextTable::splitCell(), and QTextOdfWriter::writeFrame().
 {
     QTextDocumentPrivate *p = table->docHandle();
     QTextFormatCollection *c = p->formatCollection();
     QTextCharFormat fmt = c->charFormat(tableCellFormatIndex());
     fmt.setObjectType(QTextFormat::TableCellObject);
     return fmt;
 }
isValid()
bool QTextTableCell::isValid () const inline
Returns true if this is a valid table cell; otherwise returns false.
Definition at line 77 of file qtexttable.h.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), QTextDocumentLayout::blockBoundingRect(), QTextCursorPrivate::complexSelectionTable(), QTextDocumentLayoutPrivate::frameBoundingRectInternal(), QTextDocumentLayoutPrivate::hitTest(), QTextTable::mergeCells(), QTextCursorPrivate::movePosition(), QTextHtmlImporter::TableCellIterator::operator++(), QTextHtmlImporter::processBlockNode(), QTextTable::rowEnd(), QTextTable::rowStart(), QTextCursorPrivate::selectedTableCells(), and QTextTable::splitCell().
 { return table != 0; }
lastCursorPosition()
QTextCursor QTextTableCell::lastCursorPosition () const
Returns the last valid cursor position in this cell.
See also
firstCursorPosition()
Definition at line 259 of file qtexttable.cpp.
Referenced by QTextHtmlImporter::closeTag().
 {
     return QTextCursor(table->d_func()->pieceTable, lastPosition());
 }
lastPosition()
int QTextTableCell::lastPosition () const
Returns the last valid position in the document occupied by this cell.
Warning
This function is not part of the public interface.
Definition at line 287 of file qtexttable.cpp.
Referenced by adjustContextSelectionsForCell(), QTextCursorPrivate::adjustCursor(), begin(), QTextCursorPrivate::clearCells(), QTextCopyHelper::copy(), end(), QTextDocumentLayoutPrivate::hitTest(), lastCursorPosition(), QTextCursorPrivate::movePosition(), QTextTable::removeColumns(), QTextTable::removeRows(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), and QTextTable::splitCell().
 {
     QTextDocumentPrivate *p = table->docHandle();
     const QTextTablePrivate *td = table->d_func();
     int index = table->d_func()->findCellIndex(fragment);
     int f;
     if (index != -1)
         f = td->cells.value(index + 1, td->fragment_end);
     else
         f = td->fragment_end;
     return p->fragmentMap().position(f);
 }
operator!=()
QTextCursor QTextTableCell::operator!= (const QTextTableCell & other) const inline
Returns true if this cell object and the other cell object describe different cells; otherwise returns false.
Definition at line 86 of file qtexttable.h.
     { return !operator==(other); }
operator=()
QTextTableCell & QTextTableCell::operator= (const QTextTableCell & o) inline
Assigns the other table cell to this table cell.
Definition at line 65 of file qtexttable.h.
     { table = o.table; fragment = o.fragment; return *this; }
operator==()
QTextCursor QTextTableCell::operator== (const QTextTableCell & other) const inline
Returns true if this cell object and the other cell object describe the same cell; otherwise returns false.
Definition at line 84 of file qtexttable.h.
     { return table == other.table && fragment == other.fragment; }
row()
int QTextTableCell::row () const
Returns the number of the row in the table that contains this cell.
See also
column()
Definition at line 184 of file qtexttable.cpp.
Referenced by QTextCursorPrivate::aboutToRemoveCell(), QTextCursorPrivate::adjustCursor(), QTextTableData::cellPosition(), QTextTableData::cellRect(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextControlPrivate::gotoNextTableCell(), QTextControlPrivate::gotoPreviousTableCell(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutTable(), QTextTable::mergeCells(), QTextCursorPrivate::movePosition(), QTextTable::rowEnd(), QTextTable::rowStart(), QTextCursorPrivate::selectedTableCells(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), QTextTable::splitCell(), and QTextOdfWriter::writeFrame().
 {
     const QTextTablePrivate *tp = table->d_func();
     if (tp->dirty)
         tp->update();
     int idx = tp->findCellIndex(fragment);
     if (idx == -1)
         return idx;
     return tp->cellIndices.at(idx) / tp->nCols;
 }
rowSpan()
int QTextTableCell::rowSpan () const
Returns the number of rows this cell spans.
The default is 1.
See also
columnSpan()
Definition at line 218 of file qtexttable.cpp.
Referenced by QTextTableData::cellRect(), QTextCopyHelper::copy(), QTextDocumentLayoutPrivate::drawTableCell(), QTextHtmlExporter::emitTable(), QTextDocumentLayoutPrivate::layoutTable(), QTextCursorPrivate::movePosition(), QTextCursorPrivate::selectedTableCells(), QTextCursor::selectedText(), QTextCursorPrivate::setBlockCharFormat(), QTextCursorPrivate::setBlockFormat(), QTextCursorPrivate::setCharFormat(), and QTextOdfWriter::writeFrame().
 {
     return format().tableCellRowSpan();
 }
setFormat()
void QTextTableCell::setFormat (const QTextCharFormat & format)
Sets the cell's character format to format.
Since
4.2
This can for example be used to change the background color of the entire cell:
QTextTableCell cell = table->cellAt(2, 3); QTextCharFormat format = cell.format(); format.setBackground(Qt::blue); cell.setFormat(format);
Note that the cell's row or column span cannot be changed through this function. You have to use QTextTable::mergeCells and QTextTable::splitCell instead.
See also
format()
Definition at line 134 of file qtexttable.cpp.
Referenced by QTextHtmlImporter::processBlockNode().
 {
     QTextCharFormat fmt = format;
     fmt.clearProperty(QTextFormat::ObjectIndex);
     fmt.setObjectType(QTextFormat::TableCellObject);
     QTextDocumentPrivate *p = table->docHandle();
     QTextDocumentPrivate::FragmentIterator frag(&p->fragmentMap(), fragment);
     QTextFormatCollection *c = p->formatCollection();
     QTextCharFormat oldFormat = c->charFormat(frag->format);
     fmt.setTableCellRowSpan(oldFormat.tableCellRowSpan());
     fmt.setTableCellColumnSpan(oldFormat.tableCellColumnSpan());
     p->setCharFormat(frag.position(), 1, fmt, QTextDocumentPrivate::SetFormatAndPreserveObjectIndices);
 }
tableCellFormatIndex()
int QTextTableCell::tableCellFormatIndex () const
Returns the index of the tableCell's format in the document's internal list of formats.
Since
4.5
See also
QTextDocument::allFormats()
Definition at line 173 of file qtexttable.cpp.
Referenced by format(), and QTextOdfWriter::writeFrame().
 {
     QTextDocumentPrivate *p = table->docHandle();
     return QTextDocumentPrivate::FragmentIterator(&p->fragmentMap(), fragment)->format;
 }
Friends and Related Functions
QTextTable
friend class QTextTable friend
Definition at line 95 of file qtexttable.h.
Properties
fragment
int QTextTableCell::fragment private
Definition at line 100 of file qtexttable.h.
Referenced by column(), firstPosition(), QTextTablePrivate::fragmentAdded(), lastPosition(), operator=(), operator==(), row(), setFormat(), tableCellFormatIndex(), and QTextTablePrivate::update().
table
const QTextTable* QTextTableCell::table private
Definition at line 99 of file qtexttable.h.
Referenced by begin(), column(), QTextTablePrivate::createTable(), end(), firstCursorPosition(), firstPosition(), format(), lastCursorPosition(), lastPosition(), operator=(), operator==(), row(), setFormat(), and tableCellFormatIndex().
The documentation for this class was generated from the following files:
/src/gui/text/qtexttable.h
/src/gui/text/qtexttable.cpp