Qt 4.8: QDBusAdaptorConnector Class Reference
QDBusAdaptorConnector Class Reference
#include <qdbusabstractadaptor_p.h>
Classes
struct AdaptorData
Public Types
typedef QVector< AdaptorData > AdaptorMap
Public Functions
void addAdaptor (QDBusAbstractAdaptor *adaptor)
void connectAllSignals (QObject *object)
void disconnectAllSignals (QObject *object)
void polish ()
QDBusAdaptorConnector (QObject *parent)
void relay (QObject *sender, int id, void **)
void relaySlot (void **)
~QDBusAdaptorConnector ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
AdaptorMap adaptors
bool waitingForPolish: 1
Protected Functions
void relaySignal (QObject *obj, const QMetaObject *metaObject, int sid, const QVariantList &args)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 91 of file qdbusabstractadaptor_p.h.
Typedefs
AdaptorMap
typedef QVector<AdaptorData> QDBusAdaptorConnector::AdaptorMap
Definition at line 108 of file qdbusabstractadaptor_p.h.
Constructors and Destructors
QDBusAdaptorConnector()
QDBusAdaptorConnector::QDBusAdaptorConnector (QObject * parent) explicit
Definition at line 198 of file qdbusabstractadaptor.cpp.
     : QObject(obj), waitingForPolish(false)
 {
 }
~QDBusAdaptorConnector()
QDBusAdaptorConnector::~QDBusAdaptorConnector ()
Definition at line 203 of file qdbusabstractadaptor.cpp.
 {
 }
Functions
addAdaptor()
void QDBusAdaptorConnector::addAdaptor (QDBusAbstractAdaptor * adaptor)
Definition at line 207 of file qdbusabstractadaptor.cpp.
Referenced by polish().
 {
     // find the interface name
     const QMetaObject *mo = adaptor->metaObject();
     int ciid = mo->indexOfClassInfo(QCLASSINFO_DBUS_INTERFACE);
     if (ciid != -1) {
         QMetaClassInfo mci = mo->classInfo(ciid);
         if (*mci.value()) {
             // find out if this interface exists first
             const char *interface = mci.value();
             AdaptorMap::Iterator it = qLowerBound(adaptors.begin(), adaptors.end(),
                                                   QByteArray(interface));
             if (it != adaptors.end() && qstrcmp(interface, it->interface) == 0) {
                 // exists. Replace it (though it's probably the same)
                 if (it->adaptor != adaptor) {
                     // reconnect the signals
                     disconnectAllSignals(it->adaptor);
                     connectAllSignals(adaptor);
                 }
                 it->adaptor = adaptor;
             } else {
                 // create a new one
                 AdaptorData entry;
                 entry.interface = interface;
                 entry.adaptor = adaptor;
                 adaptors << entry;
                 // connect the adaptor's signals to our relaySlot slot
                 connectAllSignals(adaptor);
             }
         }
     }
 }
connectAllSignals()
void QDBusAdaptorConnector::connectAllSignals (QObject * object)
Definition at line 246 of file qdbusabstractadaptor.cpp.
Referenced by addAdaptor(), and QDBusConnectionPrivate::registerObject().
 {
     QMetaObject::connect(obj, -1, this, metaObject()->methodOffset(), Qt::DirectConnection);
 }
disconnectAllSignals()
void QDBusAdaptorConnector::disconnectAllSignals (QObject * object)
Definition at line 241 of file qdbusabstractadaptor.cpp.
Referenced by addAdaptor(), and QDBusConnectionPrivate::registerObject().
 {
     QMetaObject::disconnect(obj, -1, this, metaObject()->methodOffset());
 }
polish()
void QDBusAdaptorConnector::polish ()
Definition at line 251 of file qdbusabstractadaptor.cpp.
Referenced by qDBusFindAdaptorConnector().
 {
     if (!waitingForPolish)
         return;                 // avoid working multiple times if multiple adaptors were added
     waitingForPolish = false;
     const QObjectList &objs = parent()->children();
     QObjectList::ConstIterator it = objs.constBegin();
     QObjectList::ConstIterator end = objs.constEnd();
     for ( ; it != end; ++it) {
         QDBusAbstractAdaptor *adaptor = qobject_cast<QDBusAbstractAdaptor *>(*it);
         if (adaptor)
             addAdaptor(adaptor);
     }
     // sort the adaptor list
     qSort(adaptors);
 }
relay()
void QDBusAdaptorConnector::relay (QObject * sender, int id, void ** argv)
Definition at line 284 of file qdbusabstractadaptor.cpp.
Referenced by relaySlot().
 {
     if (lastSignalIdx < QObject::staticMetaObject.methodCount())
         // QObject signal (destroyed(QObject *)) -- ignore
         return;
     const QMetaObject *senderMetaObject = senderObj->metaObject();
     QMetaMethod mm = senderMetaObject->method(lastSignalIdx);
     QObject *realObject = senderObj;
     if (qobject_cast<QDBusAbstractAdaptor *>(senderObj))
         // it's an adaptor, so the real object is in fact its parent
         realObject = realObject->parent();
     // break down the parameter list
     QList<int> types;
     int inputCount = qDBusParametersForMethod(mm, types);
     if (inputCount == -1)
         // invalid signal signature
         // qDBusParametersForMethod has already complained
         return;
     if (inputCount + 1 != types.count() ||
         types.at(inputCount) == QDBusMetaTypeId::message) {
         // invalid signal signature
         // qDBusParametersForMethod has not yet complained about this one
         qWarning("QDBusAbstractAdaptor: Cannot relay signal %s::%s",
                  senderMetaObject->className(), mm.signature());
         return;
     }
     QVariantList args;
     for (int i = 1; i < types.count(); ++i)
         args << QVariant(types.at(i), argv[i]);
     // now emit the signal with all the information
     emit relaySignal(realObject, senderMetaObject, lastSignalIdx, args);
 }
relaySignal()
void QDBusAdaptorConnector::relaySignal (QObject * obj, const QMetaObject * metaObject, int sid, const QVariantList & args) protected
Definition at line 387 of file qdbusabstractadaptor.cpp.
Referenced by relay().
 {
     void *_a[] = { 0, const_cast<void*>(reinterpret_cast<const void*>(&_t1)), const_cast<void*>(reinterpret_cast<const void*>(&_t2)), const_cast<void*>(reinterpret_cast<const void*>(&_t3)), const_cast<void*>(reinterpret_cast<const void*>(&_t4)) };
     QMetaObject::activate(this, &staticMetaObject, 2, _a);
 }
relaySlot()
void QDBusAdaptorConnector::relaySlot (void ** argv)
Definition at line 270 of file qdbusabstractadaptor.cpp.
 {
     QObjectPrivate *d = static_cast<QObjectPrivate *>(d_ptr.data());
     if (Q_LIKELY(d->currentSender)) {
         relay(d->currentSender->sender, d->currentSender->signal, argv);
     } else {
         qWarning("QtDBus: cannot relay signals from parent %s(%p \"%s\") unless they are emitted in the object's thread %s(%p \"%s\"). "
                  "Current thread is %s(%p \"%s\").",
                  parent()->metaObject()->className(), parent(), qPrintable(parent()->objectName()),
                  parent()->thread()->metaObject()->className(), parent()->thread(), qPrintable(parent()->thread()->objectName()),
                  QThread::currentThread()->metaObject()->className(), QThread::currentThread(), qPrintable(QThread::currentThread()->objectName()));
     }
 }
Properties
adaptors
AdaptorMap QDBusAdaptorConnector::adaptors
Definition at line 128 of file qdbusabstractadaptor_p.h.
Referenced by QDBusConnectionPrivate::activateObject(), addAdaptor(), polish(), qDBusIntrospectObject(), qDBusPropertyGet(), qDBusPropertyGetAll(), and qDBusPropertySet().
waitingForPolish
bool QDBusAdaptorConnector::waitingForPolish
Definition at line 129 of file qdbusabstractadaptor_p.h.
Referenced by polish(), and QDBusAbstractAdaptor::QDBusAbstractAdaptor().
The documentation for this class was generated from the following files:
/src/dbus/qdbusabstractadaptor_p.h
/src/dbus/qdbusabstractadaptor.cpp