Qt 4.8: QSvgIconEnginePrivate Class Reference
QSvgIconEnginePrivate Class Reference
Public Functions
void loadDataForModeAndState (QSvgRenderer *renderer, QIcon::Mode mode, QIcon::State state)
QString pmcKey (const QSize &size, QIcon::Mode mode, QIcon::State state)
QSvgIconEnginePrivate ()
void stepSerialNum ()
~QSvgIconEnginePrivate ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static int hashKey (QIcon::Mode mode, QIcon::State state)
Public Variables
QHash< int, QPixmap > * addedPixmaps
int serialNum
QHash< int, QByteArray > * svgBuffers
QHash< int, QString > svgFiles
Public Variables inherited from QSharedData
QAtomicInt ref
Static Public Variables
static QAtomicInt lastSerialNum
Detailed Description
Definition at line 58 of file qsvgiconengine.cpp.
Constructors and Destructors
QSvgIconEnginePrivate()
QSvgIconEnginePrivate::QSvgIconEnginePrivate () inline
Definition at line 61 of file qsvgiconengine.cpp.
         : svgBuffers(0), addedPixmaps(0)
         { stepSerialNum(); }
~QSvgIconEnginePrivate()
QSvgIconEnginePrivate::~QSvgIconEnginePrivate () inline
Definition at line 65 of file qsvgiconengine.cpp.
         { delete addedPixmaps; delete svgBuffers; }
Functions
hashKey()
static int QSvgIconEnginePrivate::hashKey (QIcon::Mode mode, QIcon::State state) inline static
Definition at line 68 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::actualSize(), QSvgIconEngine::addFile(), QSvgIconEngine::addPixmap(), QSvgIconEngine::pixmap(), QSvgIconEngine::read(), and QSvgIconEngine::write().
         { return (((mode)<<4)|state); }
loadDataForModeAndState()
void QSvgIconEnginePrivate::loadDataForModeAndState (QSvgRenderer * renderer, QIcon::Mode mode, QIcon::State state)
Definition at line 131 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::pixmap(), and stepSerialNum().
 {
     QByteArray buf;
     if (svgBuffers) {
         buf = svgBuffers->value(hashKey(mode, state));
         if (buf.isEmpty())
             buf = svgBuffers->value(hashKey(QIcon::Normal, QIcon::Off));
     }
     if (!buf.isEmpty()) {
 #ifndef QT_NO_COMPRESS
         buf = qUncompress(buf);
 #endif
         renderer->load(buf);
     } else {
         QString svgFile = svgFiles.value(hashKey(mode, state));
         if (svgFile.isEmpty())
             svgFile = svgFiles.value(hashKey(QIcon::Normal, QIcon::Off));
         if (!svgFile.isEmpty())
             renderer->load(svgFile);
     }
 }
pmcKey()
QString QSvgIconEnginePrivate::pmcKey (const QSize & size, QIcon::Mode mode, QIcon::State state) inline
Definition at line 71 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::pixmap().
         { return QLatin1String("$qt_svgicon_")
                  + QString::number(serialNum, 16).append(QLatin1Char('_'))
                  + QString::number((((((size.width()<<11)|size.height())<<11)|mode)<<4)|state, 16); }
stepSerialNum()
void QSvgIconEnginePrivate::stepSerialNum () inline
Definition at line 76 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::addFile(), QSvgIconEngine::addPixmap(), and QSvgIconEnginePrivate().
         { serialNum = lastSerialNum.fetchAndAddRelaxed(1); }
Properties
addedPixmaps
QHash<int, QPixmap>* QSvgIconEnginePrivate::addedPixmaps
Definition at line 83 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::actualSize(), QSvgIconEngine::addPixmap(), QSvgIconEngine::pixmap(), QSvgIconEngine::QSvgIconEngine(), QSvgIconEngine::read(), QSvgIconEngine::write(), and ~QSvgIconEnginePrivate().
lastSerialNum
QAtomicInt QSvgIconEnginePrivate::lastSerialNum static
Definition at line 85 of file qsvgiconengine.cpp.
Referenced by stepSerialNum().
serialNum
int QSvgIconEnginePrivate::serialNum
Definition at line 84 of file qsvgiconengine.cpp.
Referenced by pmcKey(), and stepSerialNum().
svgBuffers
QHash<int, QByteArray>* QSvgIconEnginePrivate::svgBuffers
Definition at line 82 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::QSvgIconEngine(), QSvgIconEngine::read(), QSvgIconEngine::write(), and ~QSvgIconEnginePrivate().
svgFiles
QHash<int, QString> QSvgIconEnginePrivate::svgFiles
Definition at line 81 of file qsvgiconengine.cpp.
Referenced by QSvgIconEngine::addFile(), QSvgIconEngine::QSvgIconEngine(), and QSvgIconEngine::write().
The documentation for this class was generated from the following file:
/src/plugins/iconengines/svgiconengine/qsvgiconengine.cpp