Qt 4.8: QDeclarativeValueTypeProxyBinding Class Reference
QDeclarativeValueTypeProxyBinding Class Reference
#include <qdeclarativebinding_p.h>
Public Functions
QDeclarativeAbstractBinding * binding (int propertyIndex)
virtual Type bindingType () const
virtual void disconnect (DisconnectMode disconnectMode)
QDeclarativeValueTypeProxyBinding (QObject *o, int coreIndex)
void removeBindings (quint32 mask)
Removes a collection of bindings, corresponding to the set bits in mask.
virtual void setEnabled (bool, QDeclarativePropertyPrivate::WriteFlags)
virtual void update (QDeclarativePropertyPrivate::WriteFlags)
Public Functions inherited from QDeclarativeAbstractBinding
void addToObject (QObject *, int)
Add this binding to object.
virtual void destroy (DestroyMode mode=DisconnectBinding)
Destroy the binding.
virtual QString expression () const
QObject * object () const
int propertyIndex () const
QDeclarativeAbstractBinding ()
void removeFromObject ()
Remove the binding from the object.
void setEnabled (bool e)
void update ()
Protected Functions
~QDeclarativeValueTypeProxyBinding ()
Protected Functions inherited from QDeclarativeAbstractBinding
void clear ()
virtual ~QDeclarativeAbstractBinding ()
Private Functions
void recursiveDisable (QDeclarativeAbstractBinding *)
void recursiveEnable (QDeclarativeAbstractBinding *, QDeclarativePropertyPrivate::WriteFlags)
Properties
QDeclarativeAbstractBinding * m_bindings
int m_index
QObject * m_object
Friends
class QDeclarativeAbstractBinding
Additional Inherited Members
Public Types inherited from QDeclarativeAbstractBinding
enum DestroyMode { DisconnectBinding, KeepBindingConnected }
enum DisconnectMode { DisconnectOne, DisconnectAll }
typedef QWeakPointer< QDeclarativeAbstractBinding > Pointer
enum Type { PropertyBinding, ValueTypeProxy }
Static Public Functions inherited from QDeclarativeAbstractBinding
static Pointer getPointer (QDeclarativeAbstractBinding *p)
Detailed Description
Definition at line 146 of file qdeclarativebinding_p.h.
Constructors and Destructors
QDeclarativeValueTypeProxyBinding()
QDeclarativeValueTypeProxyBinding::QDeclarativeValueTypeProxyBinding (QObject * o, int coreIndex)
Definition at line 500 of file qdeclarativebinding.cpp.
 : m_object(o), m_index(index), m_bindings(0)
 {
 }
~QDeclarativeValueTypeProxyBinding()
QDeclarativeValueTypeProxyBinding::~QDeclarativeValueTypeProxyBinding () protected
Definition at line 505 of file qdeclarativebinding.cpp.
 {
     while (m_bindings) {
         QDeclarativeAbstractBinding *binding = m_bindings;
         binding->setEnabled(false, 0);
         binding->destroy();
     }
 }
Functions
binding()
QDeclarativeAbstractBinding * QDeclarativeValueTypeProxyBinding::binding (int propertyIndex)
Definition at line 557 of file qdeclarativebinding.cpp.
Referenced by removeBindings(), and ~QDeclarativeValueTypeProxyBinding().
 {
     QDeclarativeAbstractBinding *binding = m_bindings;
     while (binding && binding->propertyIndex() != propertyIndex)
         binding = binding->m_nextBinding;
     return binding;
 }
bindingType()
virtual Type QDeclarativeValueTypeProxyBinding::bindingType () const inline virtual
Reimplemented from QDeclarativeAbstractBinding.
Definition at line 151 of file qdeclarativebinding_p.h.
 { return ValueTypeProxy; }
disconnect()
void QDeclarativeValueTypeProxyBinding::disconnect (DisconnectMode disconnectMode) virtual
Implements QDeclarativeAbstractBinding.
Definition at line 551 of file qdeclarativebinding.cpp.
 {
     Q_UNUSED(disconnectMode);
     // Nothing to do
 }
recursiveDisable()
void QDeclarativeValueTypeProxyBinding::recursiveDisable (QDeclarativeAbstractBinding * b) private
Definition at line 536 of file qdeclarativebinding.cpp.
Referenced by setEnabled().
 {
     if (!b)
         return;
     recursiveDisable(b->m_nextBinding);
     if (b)
         b->setEnabled(false, 0);
 }
recursiveEnable()
void QDeclarativeValueTypeProxyBinding::recursiveEnable (QDeclarativeAbstractBinding * b, QDeclarativePropertyPrivate::WriteFlags flags) private
Definition at line 525 of file qdeclarativebinding.cpp.
Referenced by setEnabled().
 {
     if (!b)
         return;
     recursiveEnable(b->m_nextBinding, flags);
     if (b)
         b->setEnabled(true, flags);
 }
removeBindings()
void QDeclarativeValueTypeProxyBinding::removeBindings (quint32 mask)
Removes a collection of bindings, corresponding to the set bits in mask.
Definition at line 570 of file qdeclarativebinding.cpp.
 {
     QDeclarativeAbstractBinding *binding = m_bindings;
     while (binding) {
         if (mask & (1 << (binding->propertyIndex() >> 24))) {
             QDeclarativeAbstractBinding *remove = binding;
             binding = remove->m_nextBinding;
             *remove->m_prevBinding = remove->m_nextBinding;
             if (remove->m_nextBinding) remove->m_nextBinding->m_prevBinding = remove->m_prevBinding;
             remove->m_prevBinding = 0;
             remove->m_nextBinding = 0;
             remove->destroy();
         } else {
             binding = binding->m_nextBinding;
         }
     }
 }
setEnabled()
void QDeclarativeValueTypeProxyBinding::setEnabled (bool e, QDeclarativePropertyPrivate::WriteFlags flags) virtual
Implements QDeclarativeAbstractBinding.
Definition at line 514 of file qdeclarativebinding.cpp.
 {
     if (e) {
         QDeclarativeAbstractBinding *bindings = m_bindings;
         recursiveEnable(bindings, flags);
     } else {
         QDeclarativeAbstractBinding *bindings = m_bindings;
         recursiveDisable(bindings);
     }
 }
update()
void QDeclarativeValueTypeProxyBinding::update (QDeclarativePropertyPrivate::WriteFlags) virtual
Implements QDeclarativeAbstractBinding.
Definition at line 547 of file qdeclarativebinding.cpp.
 {
 }
Friends and Related Functions
QDeclarativeAbstractBinding
friend class QDeclarativeAbstractBinding friend
Definition at line 168 of file qdeclarativebinding_p.h.
Properties
m_bindings
QDeclarativeAbstractBinding* QDeclarativeValueTypeProxyBinding::m_bindings private
Definition at line 171 of file qdeclarativebinding_p.h.
Referenced by QDeclarativeAbstractBinding::addToObject(), binding(), removeBindings(), setEnabled(), and ~QDeclarativeValueTypeProxyBinding().
m_index
int QDeclarativeValueTypeProxyBinding::m_index private
Definition at line 170 of file qdeclarativebinding_p.h.
m_object
QObject* QDeclarativeValueTypeProxyBinding::m_object private
Definition at line 169 of file qdeclarativebinding_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativebinding_p.h
/src/declarative/qml/qdeclarativebinding.cpp