Qt 4.8: QXcbShmImage Class Reference
QXcbShmImage Class Reference
Public Functions
QImage * image ()
void preparePaint (const QRegion &region)
void put (xcb_window_t window, const QPoint &dst, const QRect &source)
QXcbShmImage (QXcbScreen *connection, const QSize &size, uint depth, QImage::Format format)
~QXcbShmImage ()
Public Functions inherited from QXcbObject
xcb_atom_t atom (QXcbAtom::Atom atom) const
QXcbConnection * connection () const
QXcbObject (QXcbConnection *connection=0)
void setConnection (QXcbConnection *connection)
xcb_connection_t * xcb_connection () const
Private Functions
void destroy ()
Properties
QRegion m_dirty
xcb_gcontext_t m_gc
xcb_window_t m_gc_window
QImage m_qimage
xcb_shm_segment_info_t m_shm_info
xcb_image_t * m_xcb_image
Detailed Description
Definition at line 59 of file qxcbwindowsurface.cpp.
Constructors and Destructors
QXcbShmImage()
QXcbShmImage::QXcbShmImage (QXcbScreen * connection, const QSize & size, uint depth, QImage::Format format)
Definition at line 85 of file qxcbwindowsurface.cpp.
     : QXcbObject(screen->connection())
     , m_gc(0)
     , m_gc_window(0)
 {
     Q_XCB_NOOP(connection());
     m_xcb_image = xcb_image_create_native(xcb_connection(),
                                           size.width(),
                                           size.height(),
                                           XCB_IMAGE_FORMAT_Z_PIXMAP,
                                           depth,
                                           0,
                                           ~0,
                                           0);
     m_shm_info.shmid = shmget (IPC_PRIVATE,
           m_xcb_image->stride * m_xcb_image->height, IPC_CREAT|0600);
     m_shm_info.shmaddr = m_xcb_image->data = (quint8 *)shmat (m_shm_info.shmid, 0, 0);
     m_shm_info.shmseg = xcb_generate_id(xcb_connection());
     xcb_generic_error_t *error = xcb_request_check(xcb_connection(), xcb_shm_attach_checked(xcb_connection(), m_shm_info.shmseg, m_shm_info.shmid, false));
     if (error) {
         qWarning() << "QXcbWindowSurface: Unable to attach to shared memory segment";
         free(error);
     }
     if (shmctl(m_shm_info.shmid, IPC_RMID, 0) == -1)
         qWarning() << "QXcbWindowSurface: Error while marking the shared memory segment to be destroyed";
     m_qimage = QImage( (uchar*) m_xcb_image->data, m_xcb_image->width, m_xcb_image->height, m_xcb_image->stride, format);
 }
~QXcbShmImage()
QXcbShmImage::~QXcbShmImage () inline
Definition at line 63 of file qxcbwindowsurface.cpp.
 { destroy(); }
Functions
destroy()
void QXcbShmImage::destroy () private
Definition at line 118 of file qxcbwindowsurface.cpp.
Referenced by image(), and ~QXcbShmImage().
 {
     Q_XCB_CALL(xcb_shm_detach(xcb_connection(), m_shm_info.shmseg));
     xcb_image_destroy(m_xcb_image);
     shmdt(m_shm_info.shmaddr);
     shmctl(m_shm_info.shmid, IPC_RMID, 0);
     if (m_gc)
         Q_XCB_CALL(xcb_free_gc(xcb_connection(), m_gc));
 }
image()
QImage* QXcbShmImage::image () inline
Definition at line 65 of file qxcbwindowsurface.cpp.
Referenced by QXcbWindowSurface::beginPaint(), QXcbWindowSurface::paintDevice(), and QXcbWindowSurface::scroll().
 { return &m_qimage; }
preparePaint()
void QXcbShmImage::preparePaint (const QRegion & region)
Definition at line 162 of file qxcbwindowsurface.cpp.
Referenced by QXcbWindowSurface::beginPaint(), image(), and QXcbWindowSurface::scroll().
 {
     // to prevent X from reading from the image region while we're writing to it
     if (m_dirty.intersects(region)) {
         connection()->sync();
         m_dirty = QRegion();
     }
 }
put()
void QXcbShmImage::put (xcb_window_t window, const QPoint & dst, const QRect & source)
Definition at line 128 of file qxcbwindowsurface.cpp.
Referenced by QXcbWindowSurface::flush(), and image().
 {
     Q_XCB_NOOP(connection());
     if (m_gc_window != window) {
         if (m_gc)
             Q_XCB_CALL(xcb_free_gc(xcb_connection(), m_gc));
         m_gc = xcb_generate_id(xcb_connection());
         Q_XCB_CALL(xcb_create_gc(xcb_connection(), m_gc, window, 0, 0));
         m_gc_window = window;
     }
     Q_XCB_NOOP(connection());
     xcb_image_shm_put(xcb_connection(),
                       window,
                       m_gc,
                       m_xcb_image,
                       m_shm_info,
                       source.x(),
                       source.y(),
                       target.x(),
                       target.y(),
                       source.width(),
                       source.height(),
                       false);
     Q_XCB_NOOP(connection());
     m_dirty = m_dirty | source;
     xcb_flush(xcb_connection());
     Q_XCB_NOOP(connection());
 }
Properties
m_dirty
QRegion QXcbShmImage::m_dirty private
Definition at line 82 of file qxcbwindowsurface.cpp.
Referenced by preparePaint(), and put().
m_gc
xcb_gcontext_t QXcbShmImage::m_gc private
Definition at line 79 of file qxcbwindowsurface.cpp.
Referenced by destroy(), and put().
m_gc_window
xcb_window_t QXcbShmImage::m_gc_window private
Definition at line 80 of file qxcbwindowsurface.cpp.
Referenced by put().
m_qimage
QImage QXcbShmImage::m_qimage private
Definition at line 77 of file qxcbwindowsurface.cpp.
Referenced by image(), and QXcbShmImage().
m_shm_info
xcb_shm_segment_info_t QXcbShmImage::m_shm_info private
Definition at line 73 of file qxcbwindowsurface.cpp.
Referenced by destroy(), put(), and QXcbShmImage().
m_xcb_image
xcb_image_t* QXcbShmImage::m_xcb_image private
Definition at line 75 of file qxcbwindowsurface.cpp.
Referenced by destroy(), put(), and QXcbShmImage().
The documentation for this class was generated from the following file:
/src/plugins/platforms/xcb/qxcbwindowsurface.cpp