Qt 4.8: QGLPaintDevice Class Reference
QGLPaintDevice Class Reference abstract
#include <qglpaintdevice_p.h>
Public Functions
virtual bool alphaRequested () const
virtual void beginPaint ()
virtual QGLContext * context () const =0
int devType () const
virtual void endPaint ()
virtual void ensureActiveTarget ()
virtual QGLFormat format () const
virtual bool isFlipped () const
QGLPaintDevice ()
virtual QSize size () const =0
virtual ~QGLPaintDevice ()
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
virtual QPaintEngine * paintEngine () const =0
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static QGLPaintDevice * getDevice (QPaintDevice *)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
int metric (QPaintDevice::PaintDeviceMetric metric) const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables
GLuint m_previousFBO
GLuint m_thisFBO
Protected Variables inherited from QPaintDevice
ushort painters
Additional Inherited Members
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 63 of file qglpaintdevice_p.h.
Constructors and Destructors
QGLPaintDevice()
QGLPaintDevice::QGLPaintDevice ()
Definition at line 57 of file qglpaintdevice.cpp.
     : m_thisFBO(0)
 {
 }
~QGLPaintDevice()
QGLPaintDevice::~QGLPaintDevice () virtual
Definition at line 62 of file qglpaintdevice.cpp.
 {
 }
Functions
alphaRequested()
bool QGLPaintDevice::alphaRequested () const virtual
Reimplemented in QGLFBOGLPaintDevice, and QGLPixmapGLPaintDevice.
Definition at line 143 of file qglpaintdevice.cpp.
 {
     return context()->d_func()->reqFormat.alpha();
 }
beginPaint()
void QGLPaintDevice::beginPaint () virtual
Reimplemented in QGLWidgetGLPaintDevice, QGLPixmapGLPaintDevice, QX11GLPixmapData, and QEglFSPaintDevice.
Definition at line 83 of file qglpaintdevice.cpp.
Referenced by QEglFSPaintDevice::beginPaint(), QX11GLPixmapData::beginPaint(), QGLPixmapGLPaintDevice::beginPaint(), QGLWidgetGLPaintDevice::beginPaint(), and QBBGLWindowSurface::paintDevice().
 {
     // Make sure our context is the current one:
     QGLContext *ctx = context();
     if (ctx != QGLContext::currentContext())
         ctx->makeCurrent();
     // Record the currently bound FBO so we can restore it again
     // in endPaint() and bind this device's FBO
     //
     // Note: m_thisFBO could be zero if the paint device is not
     // backed by an FBO (e.g. window back buffer).  But there could
     // be a previous FBO bound to the context which we need to
     // explicitly unbind.  Otherwise the painting will go into
     // the previous FBO instead of to the window.
     m_previousFBO = ctx->d_func()->current_fbo;
     if (m_previousFBO != m_thisFBO) {
         ctx->d_ptr->current_fbo = m_thisFBO;
         glBindFramebuffer(GL_FRAMEBUFFER_EXT, m_thisFBO);
     }
     // Set the default fbo for the context to m_thisFBO so that
     // if some raw GL code between beginNativePainting() and
     // endNativePainting() calls QGLFramebufferObject::release(),
     // painting will revert to the window surface's fbo.
     ctx->d_ptr->default_fbo = m_thisFBO;
 }
context()
virtual QGLContext* QGLPaintDevice::context () const pure virtual
Implemented in QGLPBufferGLPaintDevice, QGLFBOGLPaintDevice, QGLWidgetGLPaintDevice, QGLPixmapGLPaintDevice, EAGLPaintDevice, QX11GLPixmapData, QGLWindowSurfaceGLPaintDevice, QBBGLPaintDevice, and QEglFSPaintDevice.
Referenced by alphaRequested(), beginPaint(), QGLWidgetGLPaintDevice::beginPaint(), QOpenGLPaintEnginePrivate::composite(), QOpenGLPaintEnginePrivate::createGradientPaletteTexture(), QOpenGLPaintEnginePrivate::drawOffscreenPath(), endPaint(), ensureActiveTarget(), format(), and QOpenGLPaintEnginePrivate::strokeLines().
devType()
int QGLPaintDevice::devType () const inline virtual
Reimplemented from QPaintDevice.
Reimplemented in EAGLPaintDevice.
Definition at line 69 of file qglpaintdevice_p.h.
 {return QInternal::OpenGL;}
endPaint()
void QGLPaintDevice::endPaint () virtual
Reimplemented in QGLPBufferGLPaintDevice, QGLWidgetGLPaintDevice, and QGLPixmapGLPaintDevice.
Definition at line 126 of file qglpaintdevice.cpp.
Referenced by QGLPixmapGLPaintDevice::endPaint(), QGLWidgetGLPaintDevice::endPaint(), QGLPBufferGLPaintDevice::endPaint(), and QBBGLWindowSurface::paintDevice().
 {
     // Make sure the FBO bound at beginPaint is re-bound again here:
     QGLContext *ctx = context();
     if (m_previousFBO != ctx->d_func()->current_fbo) {
         ctx->d_ptr->current_fbo = m_previousFBO;
         glBindFramebuffer(GL_FRAMEBUFFER_EXT, m_previousFBO);
     }
     ctx->d_ptr->default_fbo = 0;
 }
ensureActiveTarget()
void QGLPaintDevice::ensureActiveTarget () virtual
Definition at line 112 of file qglpaintdevice.cpp.
 {
     QGLContext* ctx = context();
     if (ctx != QGLContext::currentContext())
         ctx->makeCurrent();
     if (ctx->d_ptr->current_fbo != m_thisFBO) {
         ctx->d_ptr->current_fbo = m_thisFBO;
         glBindFramebuffer(GL_FRAMEBUFFER_EXT, m_thisFBO);
     }
     ctx->d_ptr->default_fbo = m_thisFBO;
 }
format()
QGLFormat QGLPaintDevice::format () const virtual
Reimplemented in QGLFBOGLPaintDevice.
Definition at line 138 of file qglpaintdevice.cpp.
Referenced by QGLPixelBufferPrivate::common_init(), QGL2PaintEngineExPrivate::fill(), and metric().
 {
     return context()->format();
 }
getDevice()
QGLPaintDevice * QGLPaintDevice::getDevice (QPaintDevice * pd) static
Definition at line 206 of file qglpaintdevice.cpp.
Referenced by QOpenGLPaintEngine::begin(), QGL2PaintEngineEx::begin(), and QGLOffscreen::setDevice().
 {
     QGLPaintDevice* glpd = 0;
     switch(pd->devType()) {
         case QInternal::Widget:
             // Should not be called on a non-gl widget:
             Q_ASSERT(qobject_cast<QGLWidget*>(static_cast<QWidget*>(pd)));
             glpd = &(static_cast<QGLWidget*>(pd)->d_func()->glDevice);
             break;
         case QInternal::Pbuffer:
             glpd = &(static_cast<QGLPixelBuffer*>(pd)->d_func()->glDevice);
             break;
         case QInternal::FramebufferObject:
             glpd = &(static_cast<QGLFramebufferObject*>(pd)->d_func()->glDevice);
             break;
         case QInternal::Pixmap: {
 #if !defined(QT_OPENGL_ES_1)
             QPixmapData* pmd = static_cast<QPixmap*>(pd)->pixmapData();
             if (pmd->classId() == QPixmapData::OpenGLClass)
                 glpd = static_cast<QGLPixmapData*>(pmd)->glDevice();
 #ifdef Q_WS_X11
             else if (pmd->classId() == QPixmapData::X11Class)
                 glpd = static_cast<QX11GLPixmapData*>(pmd);
 #endif
             else
                 qWarning("Pixmap type not supported for GL rendering");
 #else
             qWarning("Pixmap render targets not supported on OpenGL ES 1.x");
 #endif
             break;
         }
         default:
             qWarning("QGLPaintDevice::getDevice() - Unknown device type %d", pd->devType());
             break;
     }
     return glpd;
 }
isFlipped()
bool QGLPaintDevice::isFlipped () const virtual
Definition at line 148 of file qglpaintdevice.cpp.
Referenced by QGL2PaintEngineExPrivate::updateBrushUniforms(), and QGL2PaintEngineExPrivate::updateMatrix().
 {
     return false;
 }
metric()
int QGLPaintDevice::metric (QPaintDevice::PaintDeviceMetric metric) const protected virtual
Reimplemented from QPaintDevice.
Reimplemented in QGLWindowSurfaceGLPaintDevice.
Definition at line 66 of file qglpaintdevice.cpp.
 {
     switch(metric) {
     case PdmWidth:
         return size().width();
     case PdmHeight:
         return size().height();
     case PdmDepth: {
         const QGLFormat f = format();
         return f.redBufferSize() + f.greenBufferSize() + f.blueBufferSize() + f.alphaBufferSize();
     }
     default:
         qWarning("QGLPaintDevice::metric() - metric %d not known", metric);
         return 0;
     }
 }
size()
virtual QSize QGLPaintDevice::size () const pure virtual
Implemented in QGLPBufferGLPaintDevice, QGLFBOGLPaintDevice, QGLWidgetGLPaintDevice, QGLPixmapGLPaintDevice, EAGLPaintDevice, QX11GLPixmapData, QGLWindowSurfaceGLPaintDevice, QBBGLPaintDevice, and QEglFSPaintDevice.
Referenced by QOpenGLPaintEnginePrivate::copyDrawable(), QOpenGLPaintEnginePrivate::drawItem(), QOpenGLPaintEnginePrivate::fillVertexArray(), metric(), and QOpenGLPaintEnginePrivate::updateDepthClip().
Properties
m_previousFBO
GLuint QGLPaintDevice::m_previousFBO protected
Definition at line 86 of file qglpaintdevice_p.h.
Referenced by beginPaint(), and endPaint().
m_thisFBO
GLuint QGLPaintDevice::m_thisFBO protected
Definition at line 87 of file qglpaintdevice_p.h.
Referenced by beginPaint(), and ensureActiveTarget().
The documentation for this class was generated from the following files:
/src/opengl/qglpaintdevice_p.h
/src/opengl/qglpaintdevice.cpp