Qt 4.8: QtopiaPrintEngine Class Reference
QtopiaPrintEngine Class Reference
#include <qprintengine_qws_p.h>
Public Functions
bool abort ()
Instructs the print engine to abort the printing process.
bool begin (QPaintDevice *dev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawTextItem (const QPointF &p, const QTextItem &ti)
This function draws the text item textItem at position p.
bool end ()
Reimplement this function to finish painting on the current paint device.
int metric (QPaintDevice::PaintDeviceMetric metricType) const
Returns the metric for the given id.
bool newPage ()
Instructs the print engine to start a new page.
QRect pageRect () const
QPaintEngine * paintEngine () const
QRect paperRect () const
QPrinter::PrinterState printerState () const
Returns the current state of the printer being used by the print engine.
QVariant property (PrintEnginePropertyKey key) const
Returns the print engine's property specified by key.
QtopiaPrintEngine (QPrinter::PrinterMode mode)
void setProperty (PrintEnginePropertyKey key, const QVariant &value)
Sets the print engine's property specified by key to the given value.
QPaintEngine::Type type () const
Reimplement this function to return the paint engine Type.
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
virtual void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
virtual void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Public Functions inherited from QPrintEngine
virtual HDC getPrinterDC () const
virtual void releasePrinterDC (HDC) const
virtual ~QPrintEngine ()
Destroys the print engine.
Private Functions
void clearPage ()
void flushPage ()
Friends
class QPageSetupDialog
class QPrintDialog
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Types inherited from QPrintEngine
enum PrintEnginePropertyKey {
PPK_CollateCopies, PPK_ColorMode, PPK_Creator, PPK_DocumentName,
PPK_FullPage, PPK_NumberOfCopies, PPK_Orientation, PPK_OutputFileName,
PPK_PageOrder, PPK_PageRect, PPK_PageSize, PPK_PaperRect,
PPK_PaperSource, PPK_PrinterName, PPK_PrinterProgram, PPK_Resolution,
PPK_SelectionOption, PPK_SupportedResolutions, PPK_WindowsPageSize, PPK_FontEmbedding,
PPK_SuppressSystemPrintStatus, PPK_Duplex, PPK_PaperSources, PPK_CustomPaperSize,
PPK_PageMargins, PPK_CopyCount, PPK_SupportsMultipleCopies, PPK_PaperSize = PPK_PageSize,
PPK_CustomBase = 0xff00
}
This enum is used to communicate properties between the print engine and QPrinter.
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 71 of file qprintengine_qws_p.h.
Constructors and Destructors
QtopiaPrintEngine()
QtopiaPrintEngine::QtopiaPrintEngine (QPrinter::PrinterMode mode)
Definition at line 59 of file qprintengine_qws.cpp.
     : QPaintEngine(*(new QtopiaPrintEnginePrivate( mode )))
 {
     d_func()->initialize();
 }
Functions
abort()
bool QtopiaPrintEngine::abort () virtual
Instructs the print engine to abort the printing process.
Returns true if successful; otherwise returns false.
Implements QPrintEngine.
Definition at line 200 of file qprintengine_qws.cpp.
Referenced by type().
 {
     return false;
 }
begin()
bool QtopiaPrintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Definition at line 65 of file qprintengine_qws.cpp.
 {
     Q_D(QtopiaPrintEngine);
     Q_ASSERT_X(d->printerState == QPrinter::Idle, "QtopiaPrintEngine", "printer already active");
     // Create a new off-screen monochrome image to handle the drawing process.
     QSize size = paperRect().size();
     if ( d->pageImage )
     delete d->pageImage;
     d->pageImage = new QImage( size, QImage::Format_RGB32 );
     if ( !(d->pageImage) )
     return false;
     // Recreate the paint engine on the new image.
     delete d->_paintEngine;
     d->_paintEngine = 0;
     d->paintEngine()->state = state;
     // Begin the paint process on the image.
     if (!d->paintEngine()->begin(d->pageImage))
         return false;
     // Clear the first page to all-white.
     clearPage();
     // Clear the print buffer and output the image header.
     d->buffer.clear();
     d->writeG3FaxHeader();
     // The print engine is currently active.
     d->printerState = QPrinter::Active;
     return true;
 }
clearPage()
void QtopiaPrintEngine::clearPage () private
Definition at line 368 of file qprintengine_qws.cpp.
Referenced by begin(), and newPage().
 {
     d_func()->pageImage->fill(QColor(255, 255, 255).rgb());
 }
drawPixmap()
void QtopiaPrintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Definition at line 150 of file qprintengine_qws.cpp.
 {
     Q_D(QtopiaPrintEngine);
     Q_ASSERT(d->printerState == QPrinter::Active);
     d->paintEngine()->drawPixmap(r, pm, sr);
 }
drawTextItem()
void QtopiaPrintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Definition at line 157 of file qprintengine_qws.cpp.
 {
     Q_D(QtopiaPrintEngine);
     Q_ASSERT(d->printerState == QPrinter::Active);
     d->paintEngine()->drawTextItem(p, ti);
 }
end()
bool QtopiaPrintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Definition at line 99 of file qprintengine_qws.cpp.
 {
     Q_D(QtopiaPrintEngine);
     d->paintEngine()->end();
     // Flush the last page.
     flushPage();
     // Output the fax data to a file (TODO: send to the print queuing daemon).
     QString filename;
     if ( !d->outputFileName.isEmpty() )
         filename = QString::fromLocal8Bit(qgetenv("HOME").constData()) + QLatin1String("/Documents/") + d->outputFileName;
     else
         filename = QString::fromLocal8Bit(qgetenv("HOME").constData()) + QLatin1String("/tmp/qwsfax.tiff");
     setProperty(QPrintEngine::PPK_OutputFileName, filename);
     QFile file( filename );
     if ( !file.open( QIODevice::WriteOnly | QIODevice::Truncate ) ) {
     qDebug( "Failed to open %s for printer output",
         filename.toLatin1().constData() );
     } else {
     file.write( d->buffer.data() );
     file.close();
     }
     // Free up the memory for the image buffer.
     d->buffer.clear();
     // Finalize the print job.
     d->printerState = QPrinter::Idle;
     // call qcop service
     QMap<QString, QVariant> map;
     for ( int x = 0; x <= QPrintEngine::PPK_Duplex; x++ )
         map.insert( QString::number(x), property((QPrintEngine::PrintEnginePropertyKey)(x)));
     QVariant variant(map);
     QByteArray data;
     QDataStream out(&data, QIODevice::WriteOnly);
     out << variant;
     QCopChannel::send(QLatin1String("QPE/Service/Print"), QLatin1String("print(QVariant)"), data);
     return true;
 }
flushPage()
void QtopiaPrintEngine::flushPage () private
Definition at line 373 of file qprintengine_qws.cpp.
Referenced by end(), and newPage().
 {
     d_func()->writeG3FaxPage();
 }
metric()
int QtopiaPrintEngine::metric (QPaintDevice::PaintDeviceMetric id) const virtual
Returns the metric for the given id.
Implements QPrintEngine.
Definition at line 210 of file qprintengine_qws.cpp.
Referenced by type().
 {
     int val;
     QRect r = d_func()->fullPage ? paperRect() : pageRect();
     switch (metricType) {
     case QPaintDevice::PdmWidth:
         val = r.width();
         break;
     case QPaintDevice::PdmHeight:
         val = r.height();
         break;
     case QPaintDevice::PdmDpiX:
         val = d_func()->resolution;
         break;
     case QPaintDevice::PdmDpiY:
         val = d_func()->resolution;
         break;
     case QPaintDevice::PdmPhysicalDpiX:
     case QPaintDevice::PdmPhysicalDpiY:
         val = QT_QWS_PRINTER_DEFAULT_DPI;
         break;
     case QPaintDevice::PdmWidthMM:
         val = qRound(r.width()*25.4/d_func()->resolution);
         break;
     case QPaintDevice::PdmHeightMM:
         val = qRound(r.height()*25.4/d_func()->resolution);
         break;
     case QPaintDevice::PdmNumColors:
         val = 2;
         break;
     case QPaintDevice::PdmDepth:
         val = 1;
         break;
     default:
         qWarning("QtopiaPrintEngine::metric: Invalid metric command");
         return 0;
     }
     return val;
 }
newPage()
bool QtopiaPrintEngine::newPage () virtual
Instructs the print engine to start a new page.
Returns true if the printer was able to create the new page; otherwise returns false.
Implements QPrintEngine.
Definition at line 192 of file qprintengine_qws.cpp.
Referenced by type().
 {
     flushPage();
     clearPage();
     ++(d_func()->pageNumber);
     return true;
 }
pageRect()
QRect QtopiaPrintEngine::pageRect () const
Definition at line 183 of file qprintengine_qws.cpp.
Referenced by metric(), property(), and type().
 {
     QRect r = paperRect();
     if (d_func()->fullPage)
         return r;
     // would be nice to get better margins than this.
     return QRect(d_func()->resolution/3, d_func()->resolution/3, r.width()-2*d_func()->resolution/3, r.height()-2*d_func()->resolution/3);
 }
paintEngine()
QPaintEngine * QtopiaPrintEngine::paintEngine () const
Definition at line 145 of file qprintengine_qws.cpp.
Referenced by QtopiaPrintEnginePrivate::QtopiaPrintEnginePrivate(), and type().
 {
     return const_cast<QtopiaPrintEnginePrivate *>(d_func())->paintEngine();
 }
paperRect()
QRect QtopiaPrintEngine::paperRect () const
Definition at line 170 of file qprintengine_qws.cpp.
Referenced by begin(), metric(), pageRect(), property(), and type().
 {
     QSizeF s = qt_paperSizeToQSizeF(d_func()->paperSize);
     s.rwidth() = MM(s.width());
     s.rheight() = MM(s.height());
     int w = qRound(s.width()*d_func()->resolution/72.);
     int h = qRound(s.height()*d_func()->resolution/72.);
     if (d_func()->orientation == QPrinter::Portrait)
         return QRect(0, 0, w, h);
     else
         return QRect(0, 0, h, w);
 }
printerState()
QPrinter::PrinterState QtopiaPrintEngine::printerState () const virtual
Returns the current state of the printer being used by the print engine.
Implements QPrintEngine.
Definition at line 205 of file qprintengine_qws.cpp.
Referenced by type().
 {
     return d_func()->printerState;
 }
property()
QVariant QtopiaPrintEngine::property (PrintEnginePropertyKey key) const virtual
Returns the print engine's property specified by key.
See also
setProperty()
Implements QPrintEngine.
Definition at line 250 of file qprintengine_qws.cpp.
Referenced by end(), and type().
 {
     Q_D(const  QtopiaPrintEngine);
     QVariant ret;
     switch (key) {
     case PPK_CollateCopies:
         ret = d->collateCopies;
         break;
     case PPK_ColorMode:
         ret = d->colorMode;
         break;
     case PPK_Creator:
         ret = d->creator;
         break;
     case PPK_DocumentName:
         ret = d->docName;
         break;
     case PPK_FullPage:
         ret = d->fullPage;
         break;
     case PPK_CopyCount: // fallthrough
     case PPK_NumberOfCopies:
         ret = d->numCopies;
         break;
     case PPK_SupportsMultipleCopies:
         ret = false;
         break;
     case PPK_Orientation:
         ret = d->orientation;
         break;
     case PPK_OutputFileName:
         ret = d->outputFileName;
         break;
     case PPK_PageOrder:
         ret = d->pageOrder;
         break;
     case PPK_PageRect:
         ret = pageRect();
         break;
     case PPK_PaperSize:
         ret = d->paperSize;
         break;
     case PPK_PaperRect:
         ret = paperRect();
         break;
     case PPK_PaperSource:
         ret = d->paperSource;
         break;
     case PPK_PrinterName:
         ret = d->printerName;
         break;
     case PPK_PrinterProgram:
         ret = d->printProgram;
         break;
     case PPK_Resolution:
         ret = d->resolution;
         break;
     case PPK_SupportedResolutions:
         ret = QList<QVariant>() << QT_QWS_PRINTER_DEFAULT_DPI;
         break;
     default:
         break;
     }
     return ret;
 }
setProperty()
void QtopiaPrintEngine::setProperty (PrintEnginePropertyKey key, const QVariant & value) virtual
Sets the print engine's property specified by key to the given value.
See also
property()
Implements QPrintEngine.
Definition at line 317 of file qprintengine_qws.cpp.
Referenced by end(), and type().
 {
     Q_D(QtopiaPrintEngine);
     switch (key) {
     case PPK_CollateCopies:
         d->collateCopies = value.toBool();
         break;
     case PPK_ColorMode:
         d->colorMode = QPrinter::ColorMode(value.toInt());
         break;
     case PPK_Creator:
         d->creator = value.toString();
         break;
     case PPK_DocumentName:
         d->docName = value.toString();
         break;
     case PPK_FullPage:
         d->fullPage = value.toBool();
         break;
     case PPK_CopyCount: // fallthrough
     case PPK_NumberOfCopies:
         d->numCopies = value.toInt();
         break;
     case PPK_Orientation:
         d->orientation = QPrinter::Orientation(value.toInt());
         break;
     case PPK_OutputFileName:
         d->outputFileName = value.toString();
         break;
     case PPK_PageOrder:
         d->pageOrder = QPrinter::PageOrder(value.toInt());
         break;
     case PPK_PaperSize:
         d->paperSize = QPrinter::PaperSize(value.toInt());
         break;
     case PPK_PaperSource:
         d->paperSource = QPrinter::PaperSource(value.toInt());
     case PPK_PrinterName:
         d->printerName = value.toString();
         break;
     case PPK_PrinterProgram:
         d->printProgram = value.toString();
         break;
     case PPK_Resolution:
         d->resolution = value.toInt();
         break;
     default:
         break;
     }
 }
type()
QPaintEngine::Type QtopiaPrintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 82 of file qprintengine_qws_p.h.
 { return QPaintEngine::X11; }
updateState()
void QtopiaPrintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Definition at line 164 of file qprintengine_qws.cpp.
Referenced by type().
 {
     Q_D(QtopiaPrintEngine);
     d->paintEngine()->updateState(state);
 }
Friends and Related Functions
QPageSetupDialog
friend class QPageSetupDialog friend
Definition at line 103 of file qprintengine_qws_p.h.
QPrintDialog
friend class QPrintDialog friend
Definition at line 102 of file qprintengine_qws_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qprintengine_qws_p.h
/src/gui/painting/qprintengine_qws.cpp