Qt 4.8: QDBusMetaObjectGenerator Class Reference
QDBusMetaObjectGenerator Class Reference
Classes
struct Method
struct Property
struct Type
Public Functions
QDBusMetaObjectGenerator (const QString &interface, const QDBusIntrospection::Interface *parsedData)
void write (QDBusMetaObject *obj)
void writeWithoutXml (QDBusMetaObject *obj)
Private Types
enum MethodFlags {
AccessPrivate = 0x00, AccessProtected = 0x01, AccessPublic = 0x02, AccessMask = 0x03,
MethodMethod = 0x00, MethodSignal = 0x04, MethodSlot = 0x08, MethodTypeMask = 0x0c,
MethodCompatibility = 0x10, MethodCloned = 0x20, MethodScriptable = 0x40
}
enum PropertyFlags {
Invalid = 0x00000000, Readable = 0x00000001, Writable = 0x00000002, Resettable = 0x00000004,
EnumOrFlag = 0x00000008, StdCppSet = 0x00000100, Designable = 0x00001000, ResolveDesignable = 0x00002000,
Scriptable = 0x00004000, ResolveScriptable = 0x00008000, Stored = 0x00010000, ResolveStored = 0x00020000,
Editable = 0x00040000, ResolveEditable = 0x00080000, User = 0x00100000, ResolveUser = 0x00200000
}
Private Functions
Type findType (const QByteArray &signature, const QDBusIntrospection::Annotations &annotations, const char *direction="Out", int id=-1)
void parseMethods ()
void parseProperties ()
void parseSignals ()
Properties
const QDBusIntrospection::Interface * data
QString interface
QMap< QByteArray, Method > methods
QMap< QByteArray, Property > properties
Detailed Description
Definition at line 60 of file qdbusmetaobject.cpp.
Enumerations
MethodFlags
enum QDBusMetaObjectGenerator::MethodFlags private
Enumerator
AccessPrivate
AccessProtected
AccessPublic
AccessMask
MethodMethod
MethodSignal
MethodSlot
MethodTypeMask
MethodCompatibility
MethodCloned
MethodScriptable
Definition at line 112 of file qdbusmetaobject.cpp.
                       {
         AccessPrivate = 0x00,
         AccessProtected = 0x01,
         AccessPublic = 0x02,
         AccessMask = 0x03, //mask
         MethodMethod = 0x00,
         MethodSignal = 0x04,
         MethodSlot = 0x08,
         MethodTypeMask = 0x0c,
         MethodCompatibility = 0x10,
         MethodCloned = 0x20,
         MethodScriptable = 0x40
     };
PropertyFlags
enum QDBusMetaObjectGenerator::PropertyFlags private
Enumerator
Invalid
Readable
Writable
Resettable
EnumOrFlag
StdCppSet
Designable
ResolveDesignable
Scriptable
ResolveScriptable
Stored
ResolveStored
Editable
ResolveEditable
User
ResolveUser
Definition at line 92 of file qdbusmetaobject.cpp.
{
         Invalid = 0x00000000,
         Readable = 0x00000001,
         Writable = 0x00000002,
         Resettable = 0x00000004,
         EnumOrFlag = 0x00000008,
         StdCppSet = 0x00000100,
   //    Override = 0x00000200,
         Designable = 0x00001000,
         ResolveDesignable = 0x00002000,
         Scriptable = 0x00004000,
         ResolveScriptable = 0x00008000,
         Stored = 0x00010000,
         ResolveStored = 0x00020000,
         Editable = 0x00040000,
         ResolveEditable = 0x00080000,
         User = 0x00100000,
         ResolveUser = 0x00200000
     };
Constructors and Destructors
QDBusMetaObjectGenerator()
QDBusMetaObjectGenerator::QDBusMetaObjectGenerator (const QString & interface, const QDBusIntrospection::Interface * parsedData)
Definition at line 161 of file qdbusmetaobject.cpp.
     : data(parsedData), interface(interfaceName)
 {
     if (data) {
         parseProperties();
         parseSignals();             // call parseSignals first so that slots override signals
         parseMethods();
     }
 }
Functions
findType()
QDBusMetaObjectGenerator::Type QDBusMetaObjectGenerator::findType (const QByteArray & signature, const QDBusIntrospection::Annotations & annotations, const char * direction = "Out", int id = -1) private
Definition at line 175 of file qdbusmetaobject.cpp.
Referenced by parseMethods(), parseProperties(), and parseSignals().
 {
     Type result;
     result.id = QVariant::Invalid;
     int type = QDBusMetaType::signatureToType(signature);
     if (type == QVariant::Invalid && !qt_dbus_metaobject_skip_annotations) {
         // it's not a type normally handled by our meta type system
         // it must contain an annotation
         QString annotationName = QString::fromLatin1("org.qtproject.QtDBus.QtTypeName");
         if (id >= 0)
             annotationName += QString::fromLatin1(".%1%2")
                               .arg(QLatin1String(direction))
                               .arg(id);
         // extract from annotations:
         QByteArray typeName = annotations.value(annotationName).toLatin1();
         // verify that it's a valid one
         if (typeName.isEmpty()) {
             // try the old annotation from Qt 4
             annotationName = QString::fromLatin1("com.trolltech.QtDBus.QtTypeName");
             if (id >= 0)
                 annotationName += QString::fromLatin1(".%1%2")
                                   .arg(QLatin1String(direction))
                                   .arg(id);
             typeName = annotations.value(annotationName).toLatin1();
         }
         if (!typeName.isEmpty()) {
             // type name found
             type = QVariant::nameToType(typeName);
             if (type == QVariant::UserType)
                 type = QMetaType::type(typeName);
         }
         if (type == QVariant::Invalid || signature != QDBusMetaType::typeToSignature(type)) {
             // type is still unknown or doesn't match back to the signature that it
             // was expected to, so synthesize a fake type
             type = QMetaType::VoidStar;
             typeName = "QDBusRawType<0x" + signature.toHex() + ">*";
         }
         result.name = typeName;
     } else if (type == QVariant::Invalid) {
         // this case is used only by the qdbus command-line tool
         // invalid, let's create an impossible type that contains the signature
         if (signature == "av") {
             result.name = "QVariantList";
             type = QVariant::List;
         } else if (signature == "a{sv}") {
             result.name = "QVariantMap";
             type = QVariant::Map;
         } else {
             result.name = "QDBusRawType::" + signature;
             type = -1;
         }
     } else {
         result.name = QVariant::typeToName( QVariant::Type(type) );
     }
     result.id = type;
     return result;              // success
 }
parseMethods()
void QDBusMetaObjectGenerator::parseMethods () private
Definition at line 243 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObjectGenerator().
 {
     //
     // TODO:
     //  Add cloned methods when the remote object has return types
     //
     QDBusIntrospection::Methods::ConstIterator method_it = data->methods.constBegin();
     QDBusIntrospection::Methods::ConstIterator method_end = data->methods.constEnd();
     for ( ; method_it != method_end; ++method_it) {
         const QDBusIntrospection::Method &m = *method_it;
         Method mm;
         mm.name = m.name.toLatin1();
         QByteArray prototype = mm.name;
         prototype += '(';
         bool ok = true;
         // build the input argument list
         for (int i = 0; i < m.inputArgs.count(); ++i) {
             const QDBusIntrospection::Argument &arg = m.inputArgs.at(i);
             Type type = findType(arg.type.toLatin1(), m.annotations, "In", i);
             if (type.id == QVariant::Invalid) {
                 ok = false;
                 break;
             }
             mm.inputSignature += arg.type.toLatin1();
             mm.inputTypes.append(type.id);
             mm.parameters.append(arg.name.toLatin1());
             mm.parameters.append(',');
             prototype.append(type.name);
             prototype.append(',');
         }
         if (!ok) continue;
         // build the output argument list:
         for (int i = 0; i < m.outputArgs.count(); ++i) {
             const QDBusIntrospection::Argument &arg = m.outputArgs.at(i);
             Type type = findType(arg.type.toLatin1(), m.annotations, "Out", i);
             if (type.id == QVariant::Invalid) {
                 ok = false;
                 break;
             }
             mm.outputSignature += arg.type.toLatin1();
             mm.outputTypes.append(type.id);
             if (i == 0) {
                 // return value
                 mm.typeName = type.name;
             } else {
                 // non-const ref parameter
                 mm.parameters.append(arg.name.toLatin1());
                 mm.parameters.append(',');
                 prototype.append(type.name);
                 prototype.append("&,");
             }
         }
         if (!ok) continue;
         // convert the last commas:
         if (!mm.parameters.isEmpty()) {
             mm.parameters.truncate(mm.parameters.length() - 1);
             prototype[prototype.length() - 1] = ')';
         } else {
             prototype.append(')');
         }
         // check the async tag
         if (m.annotations.value(QLatin1String(ANNOTATION_NO_WAIT)) == QLatin1String("true"))
             mm.tag = "Q_NOREPLY";
         // meta method flags
         mm.flags = AccessPublic | MethodSlot | MethodScriptable;
         // add
         methods.insert(QMetaObject::normalizedSignature(prototype), mm);
     }
 }
parseProperties()
void QDBusMetaObjectGenerator::parseProperties () private
Definition at line 381 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObjectGenerator().
 {
     QDBusIntrospection::Properties::ConstIterator prop_it = data->properties.constBegin();
     QDBusIntrospection::Properties::ConstIterator prop_end = data->properties.constEnd();
     for ( ; prop_it != prop_end; ++prop_it) {
         const QDBusIntrospection::Property &p = *prop_it;
         Property mp;
         Type type = findType(p.type.toLatin1(), p.annotations);
         if (type.id == QVariant::Invalid)
             continue;
         QByteArray name = p.name.toLatin1();
         mp.signature = p.type.toLatin1();
         mp.type = type.id;
         mp.typeName = type.name;
         // build the flags:
         mp.flags = StdCppSet | Scriptable | Stored | Designable;
         if (p.access != QDBusIntrospection::Property::Write)
             mp.flags |= Readable;
         if (p.access != QDBusIntrospection::Property::Read)
             mp.flags |= Writable;
         if (mp.typeName == "QDBusVariant")
             mp.flags |= 0xff << 24;
         else if (mp.type < 0xff)
             // encode the type in the flags
             mp.flags |= mp.type << 24;
         // add the property:
         properties.insert(name, mp);
     }
 }
parseSignals()
void QDBusMetaObjectGenerator::parseSignals () private
Definition at line 330 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObjectGenerator().
 {
     QDBusIntrospection::Signals::ConstIterator signal_it = data->signals_.constBegin();
     QDBusIntrospection::Signals::ConstIterator signal_end = data->signals_.constEnd();
     for ( ; signal_it != signal_end; ++signal_it) {
         const QDBusIntrospection::Signal &s = *signal_it;
         Method mm;
         mm.name = s.name.toLatin1();
         QByteArray prototype = mm.name;
         prototype += '(';
         bool ok = true;
         // build the output argument list
         for (int i = 0; i < s.outputArgs.count(); ++i) {
             const QDBusIntrospection::Argument &arg = s.outputArgs.at(i);
             Type type = findType(arg.type.toLatin1(), s.annotations, "Out", i);
             if (type.id == QVariant::Invalid) {
                 ok = false;
                 break;
             }
             mm.inputSignature += arg.type.toLatin1();
             mm.inputTypes.append(type.id);
             mm.parameters.append(arg.name.toLatin1());
             mm.parameters.append(',');
             prototype.append(type.name);
             prototype.append(',');
         }
         if (!ok) continue;
         // convert the last commas:
         if (!mm.parameters.isEmpty()) {
             mm.parameters.truncate(mm.parameters.length() - 1);
             prototype[prototype.length() - 1] = ')';
         } else {
             prototype.append(')');
         }
         // meta method flags
         mm.flags = AccessProtected | MethodSignal | MethodScriptable;
         // add
         methods.insert(QMetaObject::normalizedSignature(prototype), mm);
     }
 }
write()
void QDBusMetaObjectGenerator::write (QDBusMetaObject * obj)
Definition at line 415 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObject::createMetaObject().
 {
     // this code here is mostly copied from qaxbase.cpp
     // with a few modifications to make it cleaner
     QString className = interface;
     className.replace(QLatin1Char('.'), QLatin1String("::"));
     if (className.isEmpty())
         className = QLatin1String("QDBusInterface");
     QVarLengthArray<int> idata;
     idata.resize(sizeof(QDBusMetaObjectPrivate) / sizeof(int));
     QDBusMetaObjectPrivate *header = reinterpret_cast<QDBusMetaObjectPrivate *>(idata.data());
     header->revision = 1;
     header->className = 0;
     header->classInfoCount = 0;
     header->classInfoData = 0;
     header->methodCount = methods.count();
     header->methodData = idata.size();
     header->propertyCount = properties.count();
     header->propertyData = header->methodData + header->methodCount * 5;
     header->enumeratorCount = 0;
     header->enumeratorData = 0;
     header->propertyDBusData = header->propertyData + header->propertyCount * 3;
     header->methodDBusData = header->propertyDBusData + header->propertyCount * intsPerProperty;
     int data_size = idata.size() +
                     (header->methodCount * (5+intsPerMethod)) +
                     (header->propertyCount * (3+intsPerProperty));
     foreach (const Method &mm, methods)
         data_size += 2 + mm.inputTypes.count() + mm.outputTypes.count();
     idata.resize(data_size + 1);
     char null('\0');
     QByteArray stringdata = className.toLatin1();
     stringdata += null;
     stringdata.reserve(8192);
     int offset = header->methodData;
     int signatureOffset = header->methodDBusData;
     int typeidOffset = header->methodDBusData + header->methodCount * intsPerMethod;
     idata[typeidOffset++] = 0;                           // eod
     // add each method:
     for (QMap<QByteArray, Method>::ConstIterator it = methods.constBegin();
          it != methods.constEnd(); ++it) {
         // form "prototype\0parameters\0typeName\0tag\0methodname\0inputSignature\0outputSignature"
         const Method &mm = it.value();
         idata[offset++] = stringdata.length();
         stringdata += it.key();                 // prototype
         stringdata += null;
         idata[offset++] = stringdata.length();
         stringdata += mm.parameters;
         stringdata += null;
         idata[offset++] = stringdata.length();
         stringdata += mm.typeName;
         stringdata += null;
         idata[offset++] = stringdata.length();
         stringdata += mm.tag;
         stringdata += null;
         idata[offset++] = mm.flags;
         idata[signatureOffset++] = stringdata.length();
         stringdata += mm.name;
         stringdata += null;
         idata[signatureOffset++] = stringdata.length();
         stringdata += mm.inputSignature;
         stringdata += null;
         idata[signatureOffset++] = stringdata.length();
         stringdata += mm.outputSignature;
         stringdata += null;
         idata[signatureOffset++] = typeidOffset;
         idata[typeidOffset++] = mm.inputTypes.count();
         memcpy(idata.data() + typeidOffset, mm.inputTypes.data(), mm.inputTypes.count() * sizeof(int));
         typeidOffset += mm.inputTypes.count();
         idata[signatureOffset++] = typeidOffset;
         idata[typeidOffset++] = mm.outputTypes.count();
         memcpy(idata.data() + typeidOffset, mm.outputTypes.data(), mm.outputTypes.count() * sizeof(int));
         typeidOffset += mm.outputTypes.count();
     }
     Q_ASSERT(offset == header->propertyData);
     Q_ASSERT(signatureOffset == header->methodDBusData + header->methodCount * intsPerMethod);
     Q_ASSERT(typeidOffset == idata.size());
     // add each property
     signatureOffset = header->propertyDBusData;
     for (QMap<QByteArray, Property>::ConstIterator it = properties.constBegin();
          it != properties.constEnd(); ++it) {
         const Property &mp = it.value();
         // form is "name\0typeName\0signature\0"
         idata[offset++] = stringdata.length();
         stringdata += it.key();                 // name
         stringdata += null;
         idata[offset++] = stringdata.length();
         stringdata += mp.typeName;
         stringdata += null;
         idata[offset++] = mp.flags;
         idata[signatureOffset++] = stringdata.length();
         stringdata += mp.signature;
         stringdata += null;
         idata[signatureOffset++] = mp.type;
     }
     Q_ASSERT(offset == header->propertyDBusData);
     Q_ASSERT(signatureOffset == header->methodDBusData);
     char *string_data = new char[stringdata.length()];
     memcpy(string_data, stringdata, stringdata.length());
     uint *uint_data = new uint[idata.size()];
     memcpy(uint_data, idata.data(), idata.size() * sizeof(int));
     // put the metaobject together
     obj->d.data = uint_data;
     obj->d.extradata = 0;
     obj->d.stringdata = string_data;
     obj->d.superdata = &QDBusAbstractInterface::staticMetaObject;
 }
writeWithoutXml()
void QDBusMetaObjectGenerator::writeWithoutXml (QDBusMetaObject * obj)
Referenced by write().
Properties
data
const QDBusIntrospection::Interface* QDBusMetaObjectGenerator::data private
Definition at line 131 of file qdbusmetaobject.cpp.
Referenced by parseMethods(), parseProperties(), parseSignals(), priv(), and QDBusMetaObjectGenerator().
interface
QString QDBusMetaObjectGenerator::interface private
Definition at line 132 of file qdbusmetaobject.cpp.
Referenced by QDBusMetaObject::createMetaObject(), and write().
methods
QMap<QByteArray, Method> QDBusMetaObjectGenerator::methods private
Definition at line 128 of file qdbusmetaobject.cpp.
Referenced by parseMethods(), parseSignals(), and write().
properties
QMap<QByteArray, Property> QDBusMetaObjectGenerator::properties private
Definition at line 129 of file qdbusmetaobject.cpp.
Referenced by parseProperties(), and write().
The documentation for this class was generated from the following file:
/src/dbus/qdbusmetaobject.cpp