Qt 4.8: QDeclarativeFlickablePrivate Class Reference
QDeclarativeFlickablePrivate Class Reference
#include <qdeclarativeflickable_p_p.h>
Classes
struct AxisData
struct Velocity
Public Types
enum FixupMode { Normal, Immediate, ExtentChanged }
Public Types inherited from QDeclarativeItemPrivate
enum ChangeType {
Geometry = 0x01, SiblingOrder = 0x02, Visibility = 0x04, Opacity = 0x08,
Destroyed = 0x10
}
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Public Functions
void captureDelayedPress (QGraphicsSceneMouseEvent *event)
void clearDelayedPress ()
virtual void fixup (AxisData &data, qreal minExtent, qreal maxExtent)
void fixupX ()
void fixupY ()
virtual void flick (AxisData &data, qreal minExtent, qreal maxExtent, qreal vSize, QDeclarativeTimeLineCallback::Callback fixupCallback, qreal velocity)
void flickX (qreal velocity)
void flickY (qreal velocity)
void handleMouseMoveEvent (QGraphicsSceneMouseEvent *)
void handleMousePressEvent (QGraphicsSceneMouseEvent *)
void handleMouseReleaseEvent (QGraphicsSceneMouseEvent *)
void init ()
bool isOutermostPressDelay () const
void itemGeometryChanged (QDeclarativeItem *, const QRectF &, const QRectF &)
qreal overShootDistance (qreal size)
QDeclarativeFlickablePrivate ()
void setRoundedViewportX (qreal x)
void setRoundedViewportY (qreal y)
void updateBeginningEnd ()
void updateVelocity ()
Public Functions inherited from QDeclarativeItemPrivate
QDeclarativeStateGroup * _states ()
void addItemChangeListener (QDeclarativeItemChangeListener *listener, ChangeTypes types)
AnchorLines * anchorLines () const
QDeclarativeAnchors * anchors ()
QDeclarativeAnchorLine baseline () const
QDeclarativeAnchorLine bottom () const
QPointF computeTransformOrigin () const
QDeclarativeListProperty< QObject > data ()
virtual void focusChanged (bool)
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
qreal height () const
QDeclarativeAnchorLine horizontalCenter () const
virtual qreal implicitHeight () const
virtual void implicitHeightChanged ()
virtual qreal implicitWidth () const
virtual void implicitWidthChanged ()
void init (QDeclarativeItem *parent)
bool isMirrored () const
QDeclarativeAnchorLine left () const
virtual void mirrorChange ()
QDeclarativeItemPrivate ()
void removeItemChangeListener (QDeclarativeItemChangeListener *, ChangeTypes types)
void resetHeight ()
void resetWidth ()
void resolveLayoutMirror ()
QDeclarativeListProperty< QObject > resources ()
QDeclarativeAnchorLine right () const
void setHeight (qreal)
void setImplicitLayoutMirror (bool mirror, bool inherit)
void setLayoutMirror (bool mirror)
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setState (const QString &)
void setWidth (qreal)
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
QString state () const
QDeclarativeListProperty< QDeclarativeState > states ()
QDeclarativeAnchorLine top () const
virtual void transformChanged ()
QDeclarativeListProperty< QDeclarativeTransition > transitions ()
QDeclarativeAnchorLine verticalCenter () const
qreal width () const
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
virtual void resolveFont (uint inheritedMask)
virtual void resolvePalette (uint inheritedMask)
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Public Functions inherited from QDeclarativeItemChangeListener
virtual QDeclarativeAnchorsPrivate * anchorPrivate ()
virtual void itemDestroyed (QDeclarativeItem *)
virtual void itemOpacityChanged (QDeclarativeItem *)
virtual void itemSiblingOrderChanged (QDeclarativeItem *)
virtual void itemVisibilityChanged (QDeclarativeItem *)
Static Public Functions
static void data_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * data_at (QDeclarativeListProperty< QObject > *, int)
static void data_clear (QDeclarativeListProperty< QObject > *)
static int data_count (QDeclarativeListProperty< QObject > *)
static void fixupX_callback (void *)
static void fixupY_callback (void *)
Static Public Functions inherited from QDeclarativeItemPrivate
static void data_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * data_at (QDeclarativeListProperty< QObject > *, int)
static void data_clear (QDeclarativeListProperty< QObject > *)
static int data_count (QDeclarativeListProperty< QObject > *)
static qint64 elapsed (QElapsedTimer &)
static QDeclarativeItemPrivate * get (QDeclarativeItem *item)
static void parentProperty (QObject *o, void *rv, QDeclarativeNotifierEndpoint *e)
static void resources_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * resources_at (QDeclarativeListProperty< QObject > *, int)
static void resources_clear (QDeclarativeListProperty< QObject > *)
static int resources_count (QDeclarativeListProperty< QObject > *)
static qint64 restart (QElapsedTimer &)
static void setConsistentTime (qint64 t)
static void start (QElapsedTimer &)
static void transform_append (QDeclarativeListProperty< QGraphicsTransform > *list, QGraphicsTransform *)
static QGraphicsTransform * transform_at (QDeclarativeListProperty< QGraphicsTransform > *list, int)
static void transform_clear (QDeclarativeListProperty< QGraphicsTransform > *list)
static int transform_count (QDeclarativeListProperty< QGraphicsTransform > *list)
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Public Variables
QDeclarativeFlickable::BoundsBehavior boundsBehavior
bool calcVelocity: 1
QDeclarativeItem * contentItem
qreal deceleration
QGraphicsSceneMouseEvent * delayedPressEvent
QGraphicsItem * delayedPressTarget
QBasicTimer delayedPressTimer
int fixupDuration
FixupMode fixupMode
QDeclarativeFlickable::FlickableDirection flickableDirection
AxisData hData
bool hMoved: 1
bool interactive: 1
QPointF lastFlickablePosition
QPointF lastPos
QElapsedTimer lastPosTime
qreal maxVelocity
int pressDelay
bool pressed: 1
QPointF pressPos
QElapsedTimer pressTime
qreal reportedVelocitySmoothing
bool stealMouse: 1
QDeclarativeTimeLine timeline
AxisData vData
QElapsedTimer velocityTime
QDeclarativeTimeLine velocityTimeline
QDeclarativeFlickableVisibleArea * visibleArea
bool vMoved: 1
int vTime
Public Variables inherited from QDeclarativeItemPrivate
AnchorLines * _anchorLines
QDeclarativeAnchors * _anchors
QDeclarativeContents * _contents
QDeclarativeStateGroup * _stateGroup
QDeclarativeLayoutMirroringAttached * attachedLayoutDirection
QDeclarativeNullableValue< qreal > baselineOffset
QPODVector< ChangeListener, 4 > changeListeners
bool componentComplete:1
bool doneEventPreHandler: 1
bool effectiveLayoutMirror:1
bool hadActiveFocus:1
bool hadFocus:1
bool heightValid:1
bool inheritedLayoutMirror:1
bool inheritMirrorFromItem:1
bool inheritMirrorFromParent:1
bool isMirrorImplicit:1
bool keepMouse:1
QDeclarativeItemKeyFilter * keyHandler
qreal mHeight
qreal mImplicitHeight
qreal mImplicitWidth
qreal mWidth
QDeclarativeItem::TransformOrigin origin:5
QDeclarativeNotifier parentNotifier
bool smooth:1
bool transformOriginDirty: 1
bool widthValid:1
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Additional Inherited Members
Static Public Variables inherited from QDeclarativeItemPrivate
static qint64 consistentTime = -1
Detailed Description
Definition at line 78 of file qdeclarativeflickable_p_p.h.
Enumerations
FixupMode
enum QDeclarativeFlickablePrivate::FixupMode
Enumerator
Normal
Immediate
ExtentChanged
Definition at line 183 of file qdeclarativeflickable_p_p.h.
 { Normal, Immediate, ExtentChanged };
Constructors and Destructors
QDeclarativeFlickablePrivate()
QDeclarativeFlickablePrivate::QDeclarativeFlickablePrivate ()
Definition at line 167 of file qdeclarativeflickable.cpp.
   : contentItem(new QDeclarativeItem)
     , hData(this, &QDeclarativeFlickablePrivate::setRoundedViewportX)
     , vData(this, &QDeclarativeFlickablePrivate::setRoundedViewportY)
     , hMoved(false), vMoved(false)
     , stealMouse(false), pressed(false), interactive(true), calcVelocity(false)
     , deceleration(QML_FLICK_DEFAULTDECELERATION)
     , maxVelocity(QML_FLICK_DEFAULTMAXVELOCITY), reportedVelocitySmoothing(100)
     , delayedPressEvent(0), delayedPressTarget(0), pressDelay(0), fixupDuration(400)
     , fixupMode(Normal), vTime(0), visibleArea(0)
     , flickableDirection(QDeclarativeFlickable::AutoFlickDirection)
     , boundsBehavior(QDeclarativeFlickable::DragAndOvershootBounds)
 {
 }
Functions
captureDelayedPress()
void QDeclarativeFlickablePrivate::captureDelayedPress (QGraphicsSceneMouseEvent * event)
Definition at line 1056 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     if (!q->scene() || pressDelay <= 0)
         return;
     if (!isOutermostPressDelay())
         return;
     delayedPressTarget = q->scene()->mouseGrabberItem();
     delayedPressEvent = new QGraphicsSceneMouseEvent(event->type());
     delayedPressEvent->setAccepted(false);
     for (int i = 0x1; i <= 0x10; i <<= 1) {
         if (event->buttons() & i) {
             Qt::MouseButton button = Qt::MouseButton(i);
             delayedPressEvent->setButtonDownPos(button, event->buttonDownPos(button));
             delayedPressEvent->setButtonDownScenePos(button, event->buttonDownScenePos(button));
             delayedPressEvent->setButtonDownScreenPos(button, event->buttonDownScreenPos(button));
         }
     }
     delayedPressEvent->setButtons(event->buttons());
     delayedPressEvent->setButton(event->button());
     delayedPressEvent->setPos(event->pos());
     delayedPressEvent->setScenePos(event->scenePos());
     delayedPressEvent->setScreenPos(event->screenPos());
     delayedPressEvent->setLastPos(event->lastPos());
     delayedPressEvent->setLastScenePos(event->lastScenePos());
     delayedPressEvent->setLastScreenPos(event->lastScreenPos());
     delayedPressEvent->setModifiers(event->modifiers());
     delayedPressTimer.start(pressDelay, q);
 }
clearDelayedPress()
void QDeclarativeFlickablePrivate::clearDelayedPress ()
Definition at line 1086 of file qdeclarativeflickable.cpp.
 {
     if (delayedPressEvent) {
         delayedPressTimer.stop();
         delete delayedPressEvent;
         delayedPressEvent = 0;
     }
 }
data_append()
void QDeclarativeFlickablePrivate::data_append (QDeclarativeListProperty< QObject > * prop, QObject * o) static
Definition at line 1253 of file qdeclarativeflickable.cpp.
Referenced by data_clear().
 {
     QGraphicsObject *i = qobject_cast<QGraphicsObject *>(o);
     if (i) {
         QGraphicsItemPrivate *d = QGraphicsItemPrivate::get(i);
         if (static_cast<QDeclarativeItemPrivate*>(d)->componentComplete) {
             i->setParentItem(static_cast<QDeclarativeFlickablePrivate*>(prop->data)->contentItem);
         } else {
             d->setParentItemHelper(static_cast<QDeclarativeFlickablePrivate*>(prop->data)->contentItem, 0, 0);
         }
     } else {
         o->setParent(prop->object);
     }
 }
data_at()
QObject * QDeclarativeFlickablePrivate::data_at (QDeclarativeListProperty< QObject > * property, int index) static
Definition at line 1274 of file qdeclarativeflickable.cpp.
Referenced by data_clear().
 {
     QDeclarativeItem *contentItem = static_cast<QDeclarativeFlickablePrivate*>(property->data)->contentItem;
     int childItemCount = contentItem->childItems().count();
     if (index < 0)
         return 0;
     if (index < childItemCount) {
         return contentItem->childItems().at(index)->toGraphicsObject();
     } else {
         return contentItem->children().at(index - childItemCount);
     }
     return 0;
 }
data_clear()
void QDeclarativeFlickablePrivate::data_clear (QDeclarativeListProperty< QObject > * property) static
Definition at line 1292 of file qdeclarativeflickable.cpp.
 {
     QDeclarativeItem *contentItem = static_cast<QDeclarativeFlickablePrivate*>(property->data)->contentItem;
     const QList<QGraphicsItem*> graphicsItems = contentItem->childItems();
     for (int i = 0; i < graphicsItems.count(); i++)
         contentItem->scene()->removeItem(graphicsItems[i]);
     const QList<QObject*> objects = contentItem->children();
     for (int i = 0; i < objects.count(); i++)
         objects[i]->setParent(0);
 }
data_count()
int QDeclarativeFlickablePrivate::data_count (QDeclarativeListProperty< QObject > * property) static
Definition at line 1268 of file qdeclarativeflickable.cpp.
Referenced by data_clear().
 {
     QDeclarativeItem *contentItem= static_cast<QDeclarativeFlickablePrivate*>(property->data)->contentItem;
     return contentItem->childItems().count() + contentItem->children().count();
 }
fixup()
void QDeclarativeFlickablePrivate::fixup (AxisData & data, qreal minExtent, qreal maxExtent) virtual
Reimplemented in QDeclarativeListViewPrivate, and QDeclarativeGridViewPrivate.
Definition at line 337 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridViewPrivate::fixup(), QDeclarativeListViewPrivate::fixup(), fixupX(), fixupY(), and flick().
 {
     if (data.move.value() > minExtent || maxExtent > minExtent) {
         timeline.reset(data.move);
         if (data.move.value() != minExtent) {
             switch (fixupMode) {
             case Immediate:
                 timeline.set(data.move, minExtent);
                 break;
             case ExtentChanged:
                 // The target has changed. Don't start from the beginning; just complete the
                 // second half of the animation using the new extent.
                 timeline.move(data.move, minExtent, QEasingCurve(QEasingCurve::OutExpo), 3*fixupDuration/4);
                 data.fixingUp = true;
                 break;
             default: {
                     qreal dist = minExtent - data.move;
                     timeline.move(data.move, minExtent - dist/2, QEasingCurve(QEasingCurve::InQuad), fixupDuration/4);
                     timeline.move(data.move, minExtent, QEasingCurve(QEasingCurve::OutExpo), 3*fixupDuration/4);
                     data.fixingUp = true;
                 }
             }
         }
     } else if (data.move.value() < maxExtent) {
         timeline.reset(data.move);
         switch (fixupMode) {
         case Immediate:
             timeline.set(data.move, maxExtent);
             break;
         case ExtentChanged:
             // The target has changed. Don't start from the beginning; just complete the
             // second half of the animation using the new extent.
             timeline.move(data.move, maxExtent, QEasingCurve(QEasingCurve::OutExpo), 3*fixupDuration/4);
             data.fixingUp = true;
             break;
         default: {
                 qreal dist = maxExtent - data.move;
                 timeline.move(data.move, maxExtent - dist/2, QEasingCurve(QEasingCurve::InQuad), fixupDuration/4);
                 timeline.move(data.move, maxExtent, QEasingCurve(QEasingCurve::OutExpo), 3*fixupDuration/4);
                 data.fixingUp = true;
             }
         }
     }
     data.inOvershoot = false;
     fixupMode = Normal;
     vTime = timeline.time();
 }
fixupX()
void QDeclarativeFlickablePrivate::fixupX ()
Definition at line 325 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     fixup(hData, q->minXExtent(), q->maxXExtent());
 }
fixupX_callback()
void QDeclarativeFlickablePrivate::fixupX_callback (void * data) static
Definition at line 320 of file qdeclarativeflickable.cpp.
Referenced by flickX().
 {
     ((QDeclarativeFlickablePrivate *)data)->fixupX();
 }
fixupY()
void QDeclarativeFlickablePrivate::fixupY ()
Definition at line 331 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     fixup(vData, q->minYExtent(), q->maxYExtent());
 }
fixupY_callback()
void QDeclarativeFlickablePrivate::fixupY_callback (void * data) static
Definition at line 315 of file qdeclarativeflickable.cpp.
Referenced by flickY().
 {
     ((QDeclarativeFlickablePrivate *)data)->fixupY();
 }
flick()
void QDeclarativeFlickablePrivate::flick (AxisData & data, qreal minExtent, qreal maxExtent, qreal vSize, QDeclarativeTimeLineCallback::Callback fixupCallback, qreal velocity) virtual
Reimplemented in QDeclarativeListViewPrivate, and QDeclarativeGridViewPrivate.
Definition at line 267 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridViewPrivate::flick(), QDeclarativeListViewPrivate::flick(), flickX(), and flickY().
 {
     Q_Q(QDeclarativeFlickable);
     qreal maxDistance = -1;
     data.fixingUp = false;
     // -ve velocity means list is moving up
     if (velocity > 0) {
         maxDistance = qAbs(minExtent - data.move.value());
         data.flickTarget = minExtent;
     } else {
         maxDistance = qAbs(maxExtent - data.move.value());
         data.flickTarget = maxExtent;
     }
     if (maxDistance > 0) {
         qreal v = velocity;
         if (maxVelocity != -1 && maxVelocity < qAbs(v)) {
             if (v < 0)
                 v = -maxVelocity;
             else
                 v = maxVelocity;
         }
         timeline.reset(data.move);
         if (boundsBehavior == QDeclarativeFlickable::DragAndOvershootBounds)
             timeline.accel(data.move, v, deceleration);
         else
             timeline.accel(data.move, v, deceleration, maxDistance);
         timeline.callback(QDeclarativeTimeLineCallback(&data.move, fixupCallback, this));
         if (!hData.flicking && q->xflick()) {
             hData.flicking = true;
             emit q->flickingChanged();
             emit q->flickingHorizontallyChanged();
             if (!vData.flicking)
                 emit q->flickStarted();
         }
         if (!vData.flicking && q->yflick()) {
             vData.flicking = true;
             emit q->flickingChanged();
             emit q->flickingVerticallyChanged();
             if (!hData.flicking)
                 emit q->flickStarted();
         }
     } else {
         timeline.reset(data.move);
         fixup(data, minExtent, maxExtent);
     }
 }
flickX()
void QDeclarativeFlickablePrivate::flickX (qreal velocity)
Definition at line 255 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     flick(hData, q->minXExtent(), q->maxXExtent(), q->width(), fixupX_callback, velocity);
 }
flickY()
void QDeclarativeFlickablePrivate::flickY (qreal velocity)
Definition at line 261 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     flick(vData, q->minYExtent(), q->maxYExtent(), q->height(), fixupY_callback, velocity);
 }
handleMouseMoveEvent()
void QDeclarativeFlickablePrivate::handleMouseMoveEvent (QGraphicsSceneMouseEvent * event)
Definition at line 814 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     if (!interactive || !lastPosTime.isValid())
         return;
     bool rejectY = false;
     bool rejectX = false;
     bool stealY = stealMouse;
     bool stealX = stealMouse;
     if (q->yflick()) {
         int dy = int(event->pos().y() - pressPos.y());
         if (qAbs(dy) > QApplication::startDragDistance() || QDeclarativeItemPrivate::elapsed(pressTime) > 200) {
             if (!vMoved)
                 vData.dragStartOffset = dy;
             qreal newY = dy + vData.pressPos - vData.dragStartOffset;
             const qreal minY = vData.dragMinBound;
             const qreal maxY = vData.dragMaxBound;
             if (newY > minY)
                 newY = minY + (newY - minY) / 2;
             if (newY < maxY && maxY - minY <= 0)
                 newY = maxY + (newY - maxY) / 2;
             if (boundsBehavior == QDeclarativeFlickable::StopAtBounds && newY <= maxY) {
                 newY = maxY;
                 rejectY = vData.pressPos == maxY && dy < 0;
             }
             if (boundsBehavior == QDeclarativeFlickable::StopAtBounds && newY >= minY) {
                 newY = minY;
                 rejectY = vData.pressPos == minY && dy > 0;
             }
             if (!rejectY && stealMouse && dy != 0) {
                 vData.move.setValue(qRound(newY));
                 vMoved = true;
             }
             if (!rejectY && qAbs(dy) > QApplication::startDragDistance())
                 stealY = true;
         }
     }
     if (q->xflick()) {
         int dx = int(event->pos().x() - pressPos.x());
         if (qAbs(dx) > QApplication::startDragDistance() || QDeclarativeItemPrivate::elapsed(pressTime) > 200) {
             if (!hMoved)
                 hData.dragStartOffset = dx;
             qreal newX = dx + hData.pressPos - hData.dragStartOffset;
             const qreal minX = hData.dragMinBound;
             const qreal maxX = hData.dragMaxBound;
             if (newX > minX)
                 newX = minX + (newX - minX) / 2;
             if (newX < maxX && maxX - minX <= 0)
                 newX = maxX + (newX - maxX) / 2;
             if (boundsBehavior == QDeclarativeFlickable::StopAtBounds && newX <= maxX) {
                 newX = maxX;
                 rejectX = hData.pressPos == maxX && dx < 0;
             }
             if (boundsBehavior == QDeclarativeFlickable::StopAtBounds && newX >= minX) {
                 newX = minX;
                 rejectX = hData.pressPos == minX && dx > 0;
             }
             if (!rejectX && stealMouse && dx != 0) {
                 hData.move.setValue(qRound(newX));
                 hMoved = true;
             }
             if (!rejectX && qAbs(dx) > QApplication::startDragDistance())
                 stealX = true;
         }
     }
     stealMouse = stealX || stealY;
     if (stealMouse)
         q->setKeepMouseGrab(true);
     if (rejectY) {
         vData.velocityBuffer.clear();
         vData.velocity = 0;
     }
     if (rejectX) {
         hData.velocityBuffer.clear();
         hData.velocity = 0;
     }
     if (hMoved || vMoved) {
         q->movementStarting();
         q->viewportMoved();
     }
     if (!lastPos.isNull()) {
         qreal elapsed = qreal(QDeclarativeItemPrivate::elapsed(lastPosTime)) / 1000.;
         if (elapsed <= 0)
             return;
         QDeclarativeItemPrivate::restart(lastPosTime);
         qreal dy = event->pos().y()-lastPos.y();
         if (q->yflick() && !rejectY)
             vData.addVelocitySample(dy/elapsed, maxVelocity);
         qreal dx = event->pos().x()-lastPos.x();
         if (q->xflick() && !rejectX)
             hData.addVelocitySample(dx/elapsed, maxVelocity);
     }
     lastPos = event->pos();
 }
handleMousePressEvent()
void QDeclarativeFlickablePrivate::handleMousePressEvent (QGraphicsSceneMouseEvent * event)
Definition at line 785 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     if (interactive && timeline.isActive()
             && (qAbs(hData.smoothVelocity.value()) > RetainGrabVelocity || qAbs(vData.smoothVelocity.value()) > RetainGrabVelocity))
         stealMouse = true; // If we've been flicked then steal the click.
     else
         stealMouse = false;
     q->setKeepMouseGrab(stealMouse);
     pressed = true;
     timeline.clear();
     hData.reset();
     vData.reset();
     hData.dragMinBound = q->minXExtent();
     vData.dragMinBound = q->minYExtent();
     hData.dragMaxBound = q->maxXExtent();
     vData.dragMaxBound = q->maxYExtent();
     fixupMode = Normal;
     lastPos = QPoint();
     QDeclarativeItemPrivate::start(lastPosTime);
     pressPos = event->pos();
     hData.pressPos = hData.move.value();
     vData.pressPos = vData.move.value();
     hData.flicking = false;
     vData.flicking = false;
     QDeclarativeItemPrivate::start(pressTime);
     QDeclarativeItemPrivate::start(velocityTime);
 }
handleMouseReleaseEvent()
void QDeclarativeFlickablePrivate::handleMouseReleaseEvent (QGraphicsSceneMouseEvent * event)
Definition at line 918 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     stealMouse = false;
     q->setKeepMouseGrab(false);
     pressed = false;
     if (!lastPosTime.isValid())
         return;
     // if we drag then pause before release we should not cause a flick.
     qint64 elapsed = QDeclarativeItemPrivate::elapsed(lastPosTime);
     vData.updateVelocity();
     hData.updateVelocity();
     vTime = timeline.time();
     qreal velocity = elapsed < 100 ? vData.velocity : 0;
     if (vData.atBeginning || vData.atEnd)
         velocity /= 2;
     if (q->yflick() && qAbs(velocity) > MinimumFlickVelocity && qAbs(event->pos().y() - pressPos.y()) > FlickThreshold) {
         velocityTimeline.reset(vData.smoothVelocity);
         vData.smoothVelocity.setValue(-velocity);
         flickY(velocity);
     } else {
         fixupY();
     }
     velocity = elapsed < 100 ? hData.velocity : 0;
     if (hData.atBeginning || hData.atEnd)
         velocity /= 2;
     if (q->xflick() && qAbs(velocity) > MinimumFlickVelocity && qAbs(event->pos().x() - pressPos.x()) > FlickThreshold) {
         velocityTimeline.reset(hData.smoothVelocity);
         hData.smoothVelocity.setValue(-velocity);
         flickX(velocity);
     } else {
         fixupX();
     }
     if (!timeline.isActive())
         q->movementEnding();
 }
init()
void QDeclarativeFlickablePrivate::init ()
Definition at line 182 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     QDeclarative_setParent_noEvent(contentItem, q);
     contentItem->setParentItem(q);
     static int timelineUpdatedIdx = -1;
     static int timelineCompletedIdx = -1;
     static int flickableTickedIdx = -1;
     static int flickableMovementEndingIdx = -1;
     if (timelineUpdatedIdx == -1) {
         timelineUpdatedIdx = QDeclarativeTimeLine::staticMetaObject.indexOfSignal("updated()");
         timelineCompletedIdx = QDeclarativeTimeLine::staticMetaObject.indexOfSignal("completed()");
         flickableTickedIdx = QDeclarativeFlickable::staticMetaObject.indexOfSlot("ticked()");
         flickableMovementEndingIdx = QDeclarativeFlickable::staticMetaObject.indexOfSlot("movementEnding()");
     }
     QMetaObject::connect(&timeline, timelineUpdatedIdx,
                          q, flickableTickedIdx, Qt::DirectConnection);
     QMetaObject::connect(&timeline, timelineCompletedIdx,
                          q, flickableMovementEndingIdx, Qt::DirectConnection);
     q->setAcceptedMouseButtons(Qt::LeftButton);
     q->setFiltersChildEvents(true);
     QDeclarativeItemPrivate *viewportPrivate = static_cast<QDeclarativeItemPrivate*>(QGraphicsItemPrivate::get(contentItem));
     viewportPrivate->addItemChangeListener(this, QDeclarativeItemPrivate::Geometry);
     lastPosTime.invalidate();
 }
isOutermostPressDelay()
bool QDeclarativeFlickablePrivate::isOutermostPressDelay () const
Definition at line 1042 of file qdeclarativeflickable.cpp.
 {
     Q_Q(const QDeclarativeFlickable);
     QDeclarativeItem *item = q->parentItem();
     while (item) {
         QDeclarativeFlickable *flick = qobject_cast<QDeclarativeFlickable*>(item);
         if (flick && flick->pressDelay() > 0 && flick->isInteractive())
             return false;
         item = item->parentItem();
     }
     return true;
 }
itemGeometryChanged()
void QDeclarativeFlickablePrivate::itemGeometryChanged (QDeclarativeItem * item, const QRectF & newGeom, const QRectF & oldGeom) virtual
Reimplemented from QDeclarativeItemChangeListener.
Reimplemented in QDeclarativeListViewPrivate, and QDeclarativeGridViewPrivate.
Definition at line 244 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridViewPrivate::itemGeometryChanged(), and QDeclarativeListViewPrivate::itemGeometryChanged().
 {
     Q_Q(QDeclarativeFlickable);
     if (item == contentItem) {
         if (newGeom.x() != oldGeom.x())
             emit q->contentXChanged();
         if (newGeom.y() != oldGeom.y())
             emit q->contentYChanged();
     }
 }
overShootDistance()
qreal QDeclarativeFlickablePrivate::overShootDistance (qreal size)
Definition at line 212 of file qdeclarativeflickable.cpp.
 {
     if (maxVelocity <= 0)
         return 0.0;
     return qMin(qreal(QML_FLICK_OVERSHOOT), size/3);
 }
setRoundedViewportX()
void QDeclarativeFlickablePrivate::setRoundedViewportX (qreal x)
Definition at line 1095 of file qdeclarativeflickable.cpp.
 {
     contentItem->setX(qRound(x));
 }
setRoundedViewportY()
void QDeclarativeFlickablePrivate::setRoundedViewportY (qreal y)
Definition at line 1100 of file qdeclarativeflickable.cpp.
 {
     contentItem->setY(qRound(y));
 }
updateBeginningEnd()
void QDeclarativeFlickablePrivate::updateBeginningEnd ()
Definition at line 385 of file qdeclarativeflickable.cpp.
 {
     Q_Q(QDeclarativeFlickable);
     bool atBoundaryChange = false;
     // Vertical
     const int maxyextent = int(-q->maxYExtent());
     const qreal ypos = -vData.move.value();
     bool atBeginning = (ypos <= -q->minYExtent());
     bool atEnd = (maxyextent <= ypos);
     if (atBeginning != vData.atBeginning) {
         vData.atBeginning = atBeginning;
         atBoundaryChange = true;
     }
     if (atEnd != vData.atEnd) {
         vData.atEnd = atEnd;
         atBoundaryChange = true;
     }
     // Horizontal
     const int maxxextent = int(-q->maxXExtent());
     const qreal xpos = -hData.move.value();
     atBeginning = (xpos <= -q->minXExtent());
     atEnd = (maxxextent <= xpos);
     if (atBeginning != hData.atBeginning) {
         hData.atBeginning = atBeginning;
         atBoundaryChange = true;
     }
     if (atEnd != hData.atEnd) {
         hData.atEnd = atEnd;
         atBoundaryChange = true;
     }
     if (atBoundaryChange)
         emit q->isAtBoundaryChanged();
     if (visibleArea)
         visibleArea->updateVisible();
 }
updateVelocity()
void QDeclarativeFlickablePrivate::updateVelocity ()
Definition at line 1855 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeFlickablePrivate::AxisData::reset(), and QDeclarativeFlickablePrivate::Velocity::setValue().
 {
     Q_Q(QDeclarativeFlickable);
     emit q->horizontalVelocityChanged();
     emit q->verticalVelocityChanged();
 }
Properties
boundsBehavior
QDeclarativeFlickable::BoundsBehavior QDeclarativeFlickablePrivate::boundsBehavior
Definition at line 194 of file qdeclarativeflickable_p_p.h.
Referenced by flick().
calcVelocity
bool QDeclarativeFlickablePrivate::calcVelocity
Definition at line 167 of file qdeclarativeflickable_p_p.h.
contentItem
QDeclarativeItem* QDeclarativeFlickablePrivate::contentItem
Definition at line 156 of file qdeclarativeflickable_p_p.h.
Referenced by init(), and itemGeometryChanged().
deceleration
qreal QDeclarativeFlickablePrivate::deceleration
Definition at line 172 of file qdeclarativeflickable_p_p.h.
Referenced by flick().
delayedPressEvent
QGraphicsSceneMouseEvent* QDeclarativeFlickablePrivate::delayedPressEvent
Definition at line 177 of file qdeclarativeflickable_p_p.h.
delayedPressTarget
QGraphicsItem* QDeclarativeFlickablePrivate::delayedPressTarget
Definition at line 178 of file qdeclarativeflickable_p_p.h.
delayedPressTimer
QBasicTimer QDeclarativeFlickablePrivate::delayedPressTimer
Definition at line 179 of file qdeclarativeflickable_p_p.h.
fixupDuration
int QDeclarativeFlickablePrivate::fixupDuration
Definition at line 181 of file qdeclarativeflickable_p_p.h.
Referenced by fixup().
fixupMode
FixupMode QDeclarativeFlickablePrivate::fixupMode
Definition at line 184 of file qdeclarativeflickable_p_p.h.
Referenced by fixup().
flickableDirection
QDeclarativeFlickable::FlickableDirection QDeclarativeFlickablePrivate::flickableDirection
Definition at line 193 of file qdeclarativeflickable_p_p.h.
hData
AxisData QDeclarativeFlickablePrivate::hData
Definition at line 158 of file qdeclarativeflickable_p_p.h.
Referenced by fixupX(), flick(), flickX(), updateBeginningEnd(), and QDeclarativeFlickableVisibleArea::updateVisible().
hMoved
bool QDeclarativeFlickablePrivate::hMoved
Definition at line 162 of file qdeclarativeflickable_p_p.h.
interactive
bool QDeclarativeFlickablePrivate::interactive
Definition at line 166 of file qdeclarativeflickable_p_p.h.
lastFlickablePosition
QPointF QDeclarativeFlickablePrivate::lastFlickablePosition
Definition at line 175 of file qdeclarativeflickable_p_p.h.
lastPos
QPointF QDeclarativeFlickablePrivate::lastPos
Definition at line 169 of file qdeclarativeflickable_p_p.h.
lastPosTime
QElapsedTimer QDeclarativeFlickablePrivate::lastPosTime
Definition at line 168 of file qdeclarativeflickable_p_p.h.
Referenced by init().
maxVelocity
qreal QDeclarativeFlickablePrivate::maxVelocity
Definition at line 173 of file qdeclarativeflickable_p_p.h.
Referenced by QDeclarativeFlickablePrivate::AxisData::addVelocitySample(), flick(), overShootDistance(), and QDeclarativeFlickablePrivate::AxisData::reset().
pressDelay
int QDeclarativeFlickablePrivate::pressDelay
Definition at line 180 of file qdeclarativeflickable_p_p.h.
pressed
bool QDeclarativeFlickablePrivate::pressed
Definition at line 165 of file qdeclarativeflickable_p_p.h.
pressPos
QPointF QDeclarativeFlickablePrivate::pressPos
Definition at line 170 of file qdeclarativeflickable_p_p.h.
pressTime
QElapsedTimer QDeclarativeFlickablePrivate::pressTime
Definition at line 171 of file qdeclarativeflickable_p_p.h.
reportedVelocitySmoothing
qreal QDeclarativeFlickablePrivate::reportedVelocitySmoothing
Definition at line 176 of file qdeclarativeflickable_p_p.h.
stealMouse
bool QDeclarativeFlickablePrivate::stealMouse
Definition at line 164 of file qdeclarativeflickable_p_p.h.
timeline
QDeclarativeTimeLine QDeclarativeFlickablePrivate::timeline
Definition at line 161 of file qdeclarativeflickable_p_p.h.
Referenced by fixup(), flick(), and init().
vData
AxisData QDeclarativeFlickablePrivate::vData
Definition at line 159 of file qdeclarativeflickable_p_p.h.
Referenced by fixupY(), flick(), flickY(), updateBeginningEnd(), and QDeclarativeFlickableVisibleArea::updateVisible().
velocityTime
QElapsedTimer QDeclarativeFlickablePrivate::velocityTime
Definition at line 174 of file qdeclarativeflickable_p_p.h.
velocityTimeline
QDeclarativeTimeLine QDeclarativeFlickablePrivate::velocityTimeline
Definition at line 191 of file qdeclarativeflickable_p_p.h.
visibleArea
QDeclarativeFlickableVisibleArea* QDeclarativeFlickablePrivate::visibleArea
Definition at line 192 of file qdeclarativeflickable_p_p.h.
Referenced by updateBeginningEnd().
vMoved
bool QDeclarativeFlickablePrivate::vMoved
Definition at line 163 of file qdeclarativeflickable_p_p.h.
vTime
int QDeclarativeFlickablePrivate::vTime
Definition at line 190 of file qdeclarativeflickable_p_p.h.
Referenced by fixup().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeflickable_p_p.h
/src/declarative/graphicsitems/qdeclarativeflickable.cpp