Qt 4.8: QBBBpsEventFilter Class Reference
QBBBpsEventFilter Class Reference
#include <qbbbpseventfilter.h>
Public Functions
void installOnEventDispatcher (QAbstractEventDispatcher *dispatcher)
QBBBpsEventFilter (QBBNavigatorEventHandler *navigatorEventHandler, QBBScreenEventHandler *screenEventHandler, QBBVirtualKeyboardBps *virtualKeyboard, QObject *parent=0)
void registerForScreenEvents (QBBScreen *screen)
void unregisterForScreenEvents (QBBScreen *screen)
~QBBBpsEventFilter ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
bool bpsEventFilter (bps_event_t *event)
bool handleNavigatorEvent (bps_event_t *event)
Static Private Functions
static bool dispatcherEventFilter (void *message)
Properties
QBBNavigatorEventHandler * mNavigatorEventHandler
QBBScreenEventHandler * mScreenEventHandler
QBBVirtualKeyboardBps * mVirtualKeyboard
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 57 of file qbbbpseventfilter.h.
Constructors and Destructors
QBBBpsEventFilter()
QBBBpsEventFilter::QBBBpsEventFilter (QBBNavigatorEventHandler * navigatorEventHandler, QBBScreenEventHandler * screenEventHandler, QBBVirtualKeyboardBps * virtualKeyboard, QObject * parent = 0)
Definition at line 62 of file qbbbpseventfilter.cpp.
     : QObject(parent)
     , mNavigatorEventHandler(navigatorEventHandler)
     , mScreenEventHandler(screenEventHandler)
     , mVirtualKeyboard(virtualKeyboard)
 {
     Q_ASSERT(sInstance == 0);
     sInstance = this;
 }
~QBBBpsEventFilter()
QBBBpsEventFilter::~QBBBpsEventFilter ()
Definition at line 75 of file qbbbpseventfilter.cpp.
 {
     Q_ASSERT(sInstance == this);
     sInstance = 0;
 }
Functions
bpsEventFilter()
bool QBBBpsEventFilter::bpsEventFilter (bps_event_t * event) private
Definition at line 147 of file qbbbpseventfilter.cpp.
Referenced by dispatcherEventFilter().
 {
     const int eventDomain = bps_event_get_domain(event);
 #if defined(QBBBPSEVENTFILTER_DEBUG)
     qDebug() << Q_FUNC_INFO << "event=" << event << "domain=" << eventDomain;
 #endif
     if (eventDomain == screen_get_domain()) {
         if (!mScreenEventHandler) {
             qWarning("QBB: registered for screen events, but no handler provided");
             return false;
         }
         screen_event_t screenEvent = screen_event_get_event(event);
         return mScreenEventHandler->handleEvent(screenEvent);
     }
     if (eventDomain == navigator_get_domain())
         return handleNavigatorEvent(event);
     if (mVirtualKeyboard->handleEvent(event))
         return true;
     return false;
 }
dispatcherEventFilter()
bool QBBBpsEventFilter::dispatcherEventFilter (void * message) static private
Definition at line 135 of file qbbbpseventfilter.cpp.
Referenced by installOnEventDispatcher().
 {
 #if defined(QBBBPSEVENTFILTER_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     if (sInstance == 0)
         return false;
     bps_event_t *event = static_cast<bps_event_t *>(message);
     return sInstance->bpsEventFilter(event);
 }
handleNavigatorEvent()
bool QBBBpsEventFilter::handleNavigatorEvent (bps_event_t * event) private
Definition at line 174 of file qbbbpseventfilter.cpp.
Referenced by bpsEventFilter().
 {
     switch (bps_event_get_code(event)) {
     case NAVIGATOR_ORIENTATION_CHECK: {
         const int angle = navigator_event_get_orientation_angle(event);
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator ORIENTATION CHECK event. angle=" << angle;
         #endif
         const bool result = mNavigatorEventHandler->handleOrientationCheck(angle);
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator ORIENTATION CHECK event. result=" << result;
         #endif
         // reply to navigator whether orientation is acceptable
         navigator_orientation_check_response(event, result);
         break;
     }
     case NAVIGATOR_ORIENTATION: {
         const int angle = navigator_event_get_orientation_angle(event);
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator ORIENTATION event. angle=" << angle;
         #endif
         mNavigatorEventHandler->handleOrientationChange(angle);
         navigator_done_orientation(event);
         break;
     }
     case NAVIGATOR_SWIPE_DOWN:
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator SWIPE DOWN event";
         #endif
         mNavigatorEventHandler->handleSwipeDown();
         break;
     case NAVIGATOR_EXIT:
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator EXIT event";
         #endif
         mNavigatorEventHandler->handleExit();
         break;
     case NAVIGATOR_WINDOW_STATE: {
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << Q_FUNC_INFO << "WINDOW STATE event";
         #endif
         const navigator_window_state_t state = navigator_event_get_window_state(event);
         const QByteArray id(navigator_event_get_groupid(event));
         switch (state) {
         case NAVIGATOR_WINDOW_FULLSCREEN:
             mNavigatorEventHandler->handleWindowGroupStateChanged(id, Qt::WindowFullScreen);
             break;
         case NAVIGATOR_WINDOW_THUMBNAIL:
             mNavigatorEventHandler->handleWindowGroupStateChanged(id, Qt::WindowMinimized);
             break;
         case NAVIGATOR_WINDOW_INVISIBLE:
             mNavigatorEventHandler->handleWindowGroupDeactivated(id);
             break;
         }
         break;
     }
     case NAVIGATOR_WINDOW_ACTIVE: {
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator WINDOW ACTIVE event";
         #endif
         const QByteArray id(navigator_event_get_groupid(event));
         mNavigatorEventHandler->handleWindowGroupActivated(id);
         break;
     }
     case NAVIGATOR_WINDOW_INACTIVE: {
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Navigator WINDOW INACTIVE event";
         #endif
         const QByteArray id(navigator_event_get_groupid(event));
         mNavigatorEventHandler->handleWindowGroupDeactivated(id);
         break;
     }
     case NAVIGATOR_LOW_MEMORY:
         qWarning() << "QApplication based process" << QCoreApplication::applicationPid()
                    << "received \"NAVIGATOR_LOW_MEMORY\" event";
         return false;
     default:
         #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << "QBB: Unhandled navigator event. code=" << bps_event_get_code(event);
         #endif
         return false;
     }
     return true;
 }
installOnEventDispatcher()
void QBBBpsEventFilter::installOnEventDispatcher (QAbstractEventDispatcher * dispatcher)
Definition at line 82 of file qbbbpseventfilter.cpp.
Referenced by QBBIntegration::QBBIntegration().
 {
 #if defined(QBBBPSEVENTFILTER_DEBUG)
     qDebug() << Q_FUNC_INFO << "dispatcher=" << dispatcher;
 #endif
     if (navigator_request_events(0) != BPS_SUCCESS)
         qWarning("QBB: failed to register for navigator events");
     QAbstractEventDispatcher::EventFilter previousEventFilter = dispatcher->setEventFilter(dispatcherEventFilter);
     // the QPA plugin in created in the QApplication constructor which indirectly also creates
     // the event dispatcher so we are the first event filter.
     // assert on that just in case somebody adds another event filter
     // in the QBBIntegration constructor instead of adding a new section in here
     Q_ASSERT(previousEventFilter == 0);
     Q_UNUSED(previousEventFilter);
 }
registerForScreenEvents()
void QBBBpsEventFilter::registerForScreenEvents (QBBScreen * screen)
Definition at line 100 of file qbbbpseventfilter.cpp.
Referenced by QBBIntegration::QBBIntegration().
 {
     if (!mScreenEventHandler) {
         qWarning("QBB: trying to register for screen events, but no handler provided");
         return;
     }
     int attached;
     if (screen_get_display_property_iv(screen->nativeDisplay(), SCREEN_PROPERTY_ATTACHED, &attached) != BPS_SUCCESS) {
         qWarning() << "QBB: unable to query display attachment";
         return;
     }
     if (!attached) {
 #if defined(QBBBPSEVENTFILTER_DEBUG)
         qDebug() << Q_FUNC_INFO << "skipping event registration for non-attached screen";
 #endif
         return;
     }
     if (screen_request_events(screen->nativeContext()) != BPS_SUCCESS)
         qWarning("QBB: failed to register for screen events on screen %p", screen->nativeContext());
 }
unregisterForScreenEvents()
void QBBBpsEventFilter::unregisterForScreenEvents (QBBScreen * screen)
Definition at line 124 of file qbbbpseventfilter.cpp.
Referenced by QBBIntegration::~QBBIntegration().
 {
     if (!mScreenEventHandler) {
         qWarning("QBB: trying to unregister for screen events, but no handler provided");
         return;
     }
     if (screen_stop_events(screen->nativeContext()) != BPS_SUCCESS)
         qWarning("QBB: failed to unregister for screen events on screen %p", screen->nativeContext());
 }
Properties
mNavigatorEventHandler
QBBNavigatorEventHandler* QBBBpsEventFilter::mNavigatorEventHandler private
Definition at line 78 of file qbbbpseventfilter.h.
Referenced by handleNavigatorEvent().
mScreenEventHandler
QBBScreenEventHandler* QBBBpsEventFilter::mScreenEventHandler private
Definition at line 79 of file qbbbpseventfilter.h.
Referenced by bpsEventFilter(), registerForScreenEvents(), and unregisterForScreenEvents().
mVirtualKeyboard
QBBVirtualKeyboardBps* QBBBpsEventFilter::mVirtualKeyboard private
Definition at line 80 of file qbbbpseventfilter.h.
Referenced by bpsEventFilter().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbbpseventfilter.h
/src/plugins/platforms/blackberry/qbbbpseventfilter.cpp