Qt 4.8: QSvgGenerator Class Reference
QSvgGenerator Class Reference
The QSvgGenerator class provides a paint device that is used to create SVG drawings.
#include <qsvggenerator.h>
Public Functions
QString description () const
QString fileName () const
QIODevice * outputDevice () const
QSvgGenerator ()
Constructs a new generator.
int resolution () const
void setDescription (const QString &description)
void setFileName (const QString &fileName)
void setOutputDevice (QIODevice *outputDevice)
void setResolution (int dpi)
void setSize (const QSize &size)
void setTitle (const QString &title)
void setViewBox (const QRect &viewBox)
void setViewBox (const QRectF &viewBox)
QSize size () const
QString title () const
QRect viewBox () const
QRectF viewBoxF () const
~QSvgGenerator ()
Destroys the generator.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual int devType () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
int metric (QPaintDevice::PaintDeviceMetric metric) const
Reimplemented Function
QPaintEngine * paintEngine () const
Returns the paint engine used to render graphics to be converted to SVG format information.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
QScopedPointer< QSvgGeneratorPrivate > d_ptr
QString description
the description of the generated SVG drawing
QString fileName
the target filename for the generated SVG drawing
QIODevice * outputDevice
the output device for the generated SVG drawing
int resolution
the resolution of the generated output
QSize size
the size of the generated SVG drawing
QString title
the title of the generated SVG drawing
QRectF viewBox
the viewBox of the generated SVG drawing
Additional Inherited Members
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QSvgGenerator class provides a paint device that is used to create SVG drawings.
Since
4.3
Note
This class or function is reentrant.
This paint device represents a Scalable Vector Graphics (SVG) drawing. Like QPrinter, it is designed as a write-only device that generates output in a specific format.
To write an SVG file, you first need to configure the output by setting the fileName or outputDevice properties. It is usually necessary to specify the size of the drawing by setting the size property, and in some cases where the drawing will be included in another, the viewBox property also needs to be set.
    QSvgGenerator generator;
    generator.setFileName(path);
    generator.setSize(QSize(200, 200));
    generator.setViewBox(QRect(0, 0, 200, 200));
    generator.setTitle(tr("SVG Generator Example Drawing"));
    generator.setDescription(tr("An SVG drawing created by the SVG Generator "
                                "Example provided with Qt."));
Other meta-data can be specified by setting the title, description and resolution properties.
As with other QPaintDevice subclasses, a QPainter object is used to paint onto an instance of this class:
    QPainter painter;
    painter.begin(&generator);
...
    painter.end();
Painting is performed in the same way as for any other paint device. However, it is necessary to use the QPainter::begin() and QPainter::end() to explicitly begin and end painting on the device.
The SVG Generator Example shows how the same painting commands can be used for painting a widget and writing an SVG file.
See also
QSvgRenderer, QSvgWidget, {About SVG}
Definition at line 62 of file qsvggenerator.h.
Constructors and Destructors
QSvgGenerator()
QSvgGenerator::QSvgGenerator ()
Constructs a new generator.
Definition at line 551 of file qsvggenerator.cpp.
     : d_ptr(new QSvgGeneratorPrivate)
 {
     Q_D(QSvgGenerator);
     d->engine = new QSvgPaintEngine;
     d->owns_iodevice = false;
 }
~QSvgGenerator()
QSvgGenerator::~QSvgGenerator ()
Destroys the generator.
Definition at line 563 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     if (d->owns_iodevice)
         delete d->engine->outputDevice();
     delete d->engine;
 }
Functions
description()
QString QSvgGenerator::description () const
Referenced by setTitle().
fileName()
QString QSvgGenerator::fileName () const
Referenced by setFileName(), and setViewBox().
metric()
int QSvgGenerator::metric (QPaintDevice::PaintDeviceMetric metric) const protected virtual
Reimplemented Function
Reimplemented from QPaintDevice.
Definition at line 807 of file qsvggenerator.cpp.
 {
     Q_D(const QSvgGenerator);
     switch (metric) {
     case QPaintDevice::PdmDepth:
         return 32;
     case QPaintDevice::PdmWidth:
         return d->engine->size().width();
     case QPaintDevice::PdmHeight:
         return d->engine->size().height();
     case QPaintDevice::PdmDpiX:
         return d->engine->resolution();
     case QPaintDevice::PdmDpiY:
         return d->engine->resolution();
     case QPaintDevice::PdmHeightMM:
         return qRound(d->engine->size().height() * 25.4 / d->engine->resolution());
     case QPaintDevice::PdmWidthMM:
         return qRound(d->engine->size().width() * 25.4 / d->engine->resolution());
     case QPaintDevice::PdmNumColors:
         return 0xffffffff;
     case QPaintDevice::PdmPhysicalDpiX:
         return d->engine->resolution();
     case QPaintDevice::PdmPhysicalDpiY:
         return d->engine->resolution();
     default:
         qWarning("QSvgGenerator::metric(), unhandled metric %d\n", metric);
         break;
     }
     return 0;
 }
outputDevice()
QIODevice* QSvgGenerator::outputDevice () const
Referenced by setFileName().
paintEngine()
QPaintEngine * QSvgGenerator::paintEngine () const protected virtual
Returns the paint engine used to render graphics to be converted to SVG format information.
Implements QPaintDevice.
Definition at line 798 of file qsvggenerator.cpp.
 {
     Q_D(const QSvgGenerator);
     return d->engine;
 }
resolution()
int QSvgGenerator::resolution () const
Referenced by setOutputDevice().
setDescription()
void QSvgGenerator::setDescription (const QString & description)
Definition at line 610 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     d->engine->setDocumentDescription(description);
 }
setFileName()
void QSvgGenerator::setFileName (const QString & fileName)
Definition at line 720 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     if (d->engine->isActive()) {
         qWarning("QSvgGenerator::setFileName(), cannot set file name while SVG is being generated");
         return;
     }
     if (d->owns_iodevice)
         delete d->engine->outputDevice();
     d->owns_iodevice = true;
     d->fileName = fileName;
     QFile *file = new QFile(fileName);
     d->engine->setOutputDevice(file);
 }
setOutputDevice()
void QSvgGenerator::setOutputDevice (QIODevice * outputDevice)
Definition at line 757 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     if (d->engine->isActive()) {
         qWarning("QSvgGenerator::setOutputDevice(), cannot set output device while SVG is being generated");
         return;
     }
     d->owns_iodevice = false;
     d->engine->setOutputDevice(outputDevice);
     d->fileName = QString();
 }
setResolution()
void QSvgGenerator::setResolution (int dpi)
Definition at line 788 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     d->engine->setResolution(dpi);
 }
setSize()
void QSvgGenerator::setSize (const QSize & size)
Definition at line 640 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     if (d->engine->isActive()) {
         qWarning("QSvgGenerator::setSize(), cannot set size while SVG is being generated");
         return;
     }
     d->engine->setSize(size);
 }
setTitle()
void QSvgGenerator::setTitle (const QString & title)
Definition at line 587 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     d->engine->setDocumentTitle(title);
 }
setViewBox() [1/2]
void QSvgGenerator::setViewBox (const QRect & viewBox)
Definition at line 699 of file qsvggenerator.cpp.
 {
     setViewBox(QRectF(viewBox));
 }
setViewBox() [2/2]
void QSvgGenerator::setViewBox (const QRectF & viewBox)
Definition at line 689 of file qsvggenerator.cpp.
 {
     Q_D(QSvgGenerator);
     if (d->engine->isActive()) {
         qWarning("QSvgGenerator::setViewBox(), cannot set viewBox while SVG is being generated");
         return;
     }
     d->engine->setViewBox(viewBox);
 }
size()
QSize QSvgGenerator::size () const
Referenced by setDescription().
title()
QString QSvgGenerator::title () const
Referenced by ~QSvgGenerator().
viewBox()
QRect QSvgGenerator::viewBox () const
Referenced by viewBoxF().
viewBoxF()
QRectF QSvgGenerator::viewBoxF () const
Definition at line 667 of file qsvggenerator.cpp.
 {
     Q_D(const QSvgGenerator);
     return d->engine->viewBox();
 }
Properties
d_ptr
QScopedPointer<QSvgGeneratorPrivate> QSvgGenerator::d_ptr private
Definition at line 104 of file qsvggenerator.h.
description
QString QSvgGenerator::description private
the description of the generated SVG drawing
Since
4.5
See also
title
Definition at line 69 of file qsvggenerator.h.
fileName
QString QSvgGenerator::fileName private
the target filename for the generated SVG drawing
Since
4.5
See also
outputDevice
Definition at line 70 of file qsvggenerator.h.
outputDevice
QIODevice * QSvgGenerator::outputDevice private
the output device for the generated SVG drawing
Since
4.5
If both output device and file name are specified, the output device will have precedence.
See also
fileName
Definition at line 71 of file qsvggenerator.h.
resolution
int QSvgGenerator::resolution private
the resolution of the generated output
Since
4.5
The resolution is specified in dots per inch, and is used to calculate the physical size of an SVG drawing.
See also
size, viewBox
Definition at line 72 of file qsvggenerator.h.
size
QSize QSvgGenerator::size private
the size of the generated SVG drawing
Since
4.5
By default this property is set to QSize(-1, -1), which indicates that the generator should not output the width and height attributes of the <svg> element.
Note
It is not possible to change this property while a QPainter is active on the generator.
See also
viewBox, resolution
Definition at line 66 of file qsvggenerator.h.
title
QString QSvgGenerator::title private
the title of the generated SVG drawing
Since
4.5
See also
description
Definition at line 68 of file qsvggenerator.h.
viewBox
QRect QSvgGenerator::viewBox private
the viewBox of the generated SVG drawing
Returns viewBoxF().
Since
4.5
By default this property is set to QRect(0, 0, -1, -1), which indicates that the generator should not output the viewBox attribute of the <svg> element.
Note
It is not possible to change this property while a QPainter is active on the generator.
See also
viewBox(), size, resolution
Since
4.5
toRect().
\sa viewBoxF()
Definition at line 67 of file qsvggenerator.h.
The documentation for this class was generated from the following files:
/src/svg/qsvggenerator.h
/src/svg/qsvggenerator.cpp