Qt 4.8: QFontEngineFT Class Reference
QFontEngineFT Class Reference
#include <qfontengine_ft_p.h>
Classes
struct Glyph
struct GlyphAndSubPixelPosition
struct QGlyphSet
Public Types
typedef XGlyphInfo GlyphInfo
enum HintStyle { HintNone, HintLight, HintMedium, HintFull }
enum Scaling { Scaled, Unscaled }
enum SubpixelAntialiasingType {
Subpixel_None, Subpixel_RGB, Subpixel_BGR, Subpixel_VRGB,
Subpixel_VBGR
}
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Functions
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int nglyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual void addOutlineToPath (qreal x, qreal y, const QGlyphLayout &glyphs, QPainterPath *path, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed subPixelPosition, const QTransform &matrix, QFontEngine::GlyphFormat format)
virtual QImage alphaMapForGlyph (glyph_t g)
virtual QImage alphaMapForGlyph (glyph_t, QFixed)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual QFixed ascent () const
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
virtual glyph_metrics_t boundingBox (glyph_t glyph)
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
Glyph * cachedGlyph (glyph_t g) const
virtual bool canRender (const QChar *string, int len)
virtual QFontEngine * cloneWithSize (qreal pixelSize) const
GlyphFormat defaultGlyphFormat () const
QGlyphSet * defaultGlyphs ()
HintStyle defaultHintStyle () const
virtual QFixed descent () const
void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual void draw (QPaintEngine *, qreal, qreal, const QTextItemInt &)
bool drawAntialiased () const
virtual QFixed emSquareSize () const
virtual QFontEngine::FaceId faceId () const
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
virtual bool getSfntTableData (uint tag, uchar *buffer, uint *length) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
virtual int glyphCount () const
bool init (FaceId faceId, bool antiaalias, GlyphFormat defaultFormat=Format_None, const QByteArray &fontData=QByteArray())
bool init (FaceId faceId, bool antialias, GlyphFormat format, QFreetypeFace *freetypeFace)
bool initFromFontEngine (const QFontEngineFT *fontEngine)
bool invalid () const
bool isBitmapFont () const
virtual QFixed leading () const
virtual QFixed lineThickness () const
Glyph * loadGlyph (uint glyph, QFixed subPixelPosition, GlyphFormat format=Format_None, bool fetchMetricsOnly=false) const
Glyph * loadGlyph (QGlyphSet *set, uint glyph, QFixed subPixelPosition, GlyphFormat=Format_None, bool fetchMetricsOnly=false) const
bool loadGlyphs (QGlyphSet *gs, const glyph_t *glyphs, int num_glyphs, const QFixedPoint *positions, GlyphFormat format=Format_Render)
QGlyphSet * loadTransformedGlyphSet (const QTransform &matrix)
FT_Face lockFace (Scaling scale=Scaled) const
virtual qreal maxCharWidth () const
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
virtual const char * name () const
FT_Face non_locked_face () const
virtual QFontEngine::Properties properties () const
QFontEngineFT (const QFontDef &fd)
virtual void recalcAdvances (QGlyphLayout *glyphs, QTextEngine::ShaperFlags flags) const
virtual void removeGlyphFromCache (glyph_t glyph)
void setDefaultHintStyle (HintStyle style)
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *nglyphs, QTextEngine::ShaperFlags flags) const
QFixed subPixelPositionForX (QFixed x)
virtual bool supportsSubPixelPositions () const
virtual int synthesized () const
virtual Type type () const
virtual QFixed underlinePosition () const
void unlockFace () const
virtual QFixed xHeight () const
virtual ~QFontEngineFT ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
QByteArray getSfntTable (uint) const
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
void loadKerningPairs (QFixed scalingFactor)
QFontEngine ()
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual unsigned long allocateServerGlyphSet ()
void freeGlyphSets ()
virtual void freeServerGlyphSet (unsigned long id)
virtual bool uploadGlyphToServer (QGlyphSet *set, uint glyphid, Glyph *g, GlyphInfo *info, int glyphDataSize) const
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables
bool antialias
bool canUploadGlyphsToServer
HintStyle default_hint_style
int default_load_flags
bool embeddedbitmap
bool embolden
QFreetypeFace * freetype
int lcdFilterType
SubpixelAntialiasingType subpixelType
bool transform
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Private Functions
int loadFlags (QGlyphSet *set, GlyphFormat format, int flags, bool &hsubpixel, int &vfactor) const
Properties
GlyphFormat defaultFormat
QGlyphSet defaultGlyphSet
QFontEngine::FaceId face_id
bool kerning_pairs_loaded
QFixed lbearing
QFixed line_thickness
FT_Matrix matrix
FT_Size_Metrics metrics
QFixed rbearing
QList< QGlyphSet > transformedGlyphSets
QFixed underline_position
int xsize
int ysize
Friends
class QFontEngineFTRawFont
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 134 of file qfontengine_ft_p.h.
Typedefs
GlyphInfo
typedef XGlyphInfo QFontEngineFT::GlyphInfo
Definition at line 161 of file qfontengine_ft_p.h.
Enumerations
HintStyle
enum QFontEngineFT::HintStyle
Enumerator
HintNone
HintLight
HintMedium
HintFull
Definition at line 309 of file qfontengine_ft_p.h.
                    {
         HintNone,
         HintLight,
         HintMedium,
         HintFull
     };
Scaling
enum QFontEngineFT::Scaling
Enumerator
Scaled
Unscaled
Definition at line 267 of file qfontengine_ft_p.h.
                  {
         Scaled,
         Unscaled
     };
SubpixelAntialiasingType
enum QFontEngineFT::SubpixelAntialiasingType
Enumerator
Subpixel_None
Subpixel_RGB
Subpixel_BGR
Subpixel_VRGB
Subpixel_VBGR
Definition at line 152 of file qfontengine_ft_p.h.
{
         Subpixel_None,
         Subpixel_RGB,
         Subpixel_BGR,
         Subpixel_VRGB,
         Subpixel_VBGR
     };
Constructors and Destructors
QFontEngineFT()
QFontEngineFT::QFontEngineFT (const QFontDef & fd)
Definition at line 624 of file qfontengine_ft.cpp.
Referenced by cloneWithSize().
 {
     fontDef = fd;
     matrix.xx = 0x10000;
     matrix.yy = 0x10000;
     matrix.xy = 0;
     matrix.yx = 0;
     cache_cost = 100;
     kerning_pairs_loaded = false;
     transform = false;
     embolden = false;
     antialias = true;
     freetype = 0;
     default_load_flags = FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH;
     default_hint_style = HintNone;
     subpixelType = Subpixel_None;
     lcdFilterType = 0;
 #if defined(FT_LCD_FILTER_H)
     lcdFilterType = (int)((quintptr) FT_LCD_FILTER_DEFAULT);
 #endif
     defaultFormat = Format_None;
     canUploadGlyphsToServer = false;
     embeddedbitmap = false;
 }
~QFontEngineFT()
QFontEngineFT::~QFontEngineFT () virtual
Definition at line 649 of file qfontengine_ft.cpp.
 {
     if (freetype)
         freetype->release(face_id);
     hbFace = 0; // we share the face in QFreeTypeFace, don't let ~QFontEngine delete it
 }
Functions
addGlyphsToPath()
void QFontEngineFT::addGlyphsToPath (glyph_t * glyphs, QFixedPoint * positions, int nglyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented from QFontEngine.
Definition at line 1483 of file qfontengine_ft.cpp.
 {
     FT_Face face = lockFace(Unscaled);
     for (int gl = 0; gl < numGlyphs; gl++) {
         FT_UInt glyph = glyphs[gl];
         FT_Load_Glyph(face, glyph, FT_LOAD_NO_BITMAP);
         FT_GlyphSlot g = face->glyph;
         if (g->format != FT_GLYPH_FORMAT_OUTLINE)
             continue;
         QFreetypeFace::addGlyphToPath(face, g, positions[gl], path, xsize, ysize);
     }
     unlockFace();
 }
addOutlineToPath()
void QFontEngineFT::addOutlineToPath (qreal x, qreal y, const QGlyphLayout & glyphs, QPainterPath * path, QTextItem::RenderFlags flags) virtual
Reimplemented from QFontEngine.
Definition at line 1459 of file qfontengine_ft.cpp.
 {
     if (!glyphs.numGlyphs)
         return;
     if (FT_IS_SCALABLE(freetype->face)) {
         QFontEngine::addOutlineToPath(x, y, glyphs, path, flags);
     } else {
         QVarLengthArray<QFixedPoint> positions;
         QVarLengthArray<glyph_t> positioned_glyphs;
         QTransform matrix;
         matrix.translate(x, y);
         getGlyphPositions(glyphs, matrix, flags, positioned_glyphs, positions);
         FT_Face face = lockFace(Unscaled);
         for (int gl = 0; gl < glyphs.numGlyphs; gl++) {
             FT_UInt glyph = positioned_glyphs[gl];
             FT_Load_Glyph(face, glyph, FT_LOAD_TARGET_MONO);
             freetype->addBitmapToPath(face->glyph, positions[gl], path);
         }
         unlockFace();
     }
 }
allocateServerGlyphSet()
unsigned long QFontEngineFT::allocateServerGlyphSet () protected virtual
Reimplemented in QFontEngineX11FT.
Definition at line 1954 of file qfontengine_ft.cpp.
 {
     return 0;
 }
alphaMapBoundingBox()
glyph_metrics_t QFontEngineFT::alphaMapBoundingBox (glyph_t glyph, QFixed subPixelPosition, const QTransform & matrix, QFontEngine::GlyphFormat format) virtual
Reimplemented from QFontEngine.
Definition at line 1713 of file qfontengine_ft.cpp.
 {
     FT_Face face = 0;
     glyph_metrics_t overall;
     QGlyphSet *glyphSet = 0;
     if (matrix.type() > QTransform::TxTranslate && FT_IS_SCALABLE(freetype->face)) {
         // TODO move everything here to a method of its own to access glyphSets
         // to be shared with a new method that will replace loadTransformedGlyphSet()
         FT_Matrix m;
         m.xx = FT_Fixed(matrix.m11() * 65536);
         m.xy = FT_Fixed(-matrix.m21() * 65536);
         m.yx = FT_Fixed(-matrix.m12() * 65536);
         m.yy = FT_Fixed(matrix.m22() * 65536);
         for (int i = 0; i < transformedGlyphSets.count(); ++i) {
             const QGlyphSet &g = transformedGlyphSets.at(i);
             if (g.transformationMatrix.xx == m.xx
                 && g.transformationMatrix.xy == m.xy
                 && g.transformationMatrix.yx == m.yx
                 && g.transformationMatrix.yy == m.yy) {
                 // found a match, move it to the front
                 transformedGlyphSets.move(i, 0);
                 glyphSet = &transformedGlyphSets[0];
                 break;
             }
         }
         if (!glyphSet) {
             // don't cache more than 10 transformations
             if (transformedGlyphSets.count() >= 10) {
                 transformedGlyphSets.move(transformedGlyphSets.size() - 1, 0);
                 freeServerGlyphSet(transformedGlyphSets.at(0).id);
             } else {
                 transformedGlyphSets.prepend(QGlyphSet());
             }
             glyphSet = &transformedGlyphSets[0];
             glyphSet->clear();
             glyphSet->id = allocateServerGlyphSet();
             glyphSet->transformationMatrix = m;
         }
         Q_ASSERT(glyphSet);
     } else {
         glyphSet = &defaultGlyphSet;
     }
     Glyph * g = glyphSet->getGlyph(glyph);
     if (!g || g->format != format) {
         face = lockFace();
         FT_Matrix m = this->matrix;
         FT_Matrix_Multiply(&glyphSet->transformationMatrix, &m);
         freetype->matrix = m;
         g = loadGlyph(glyphSet, glyph, subPixelPosition, format);
     }
     if (g) {
         overall.x = g->x;
         overall.y = -g->y;
         overall.width = g->width;
         overall.height = g->height;
         overall.xoff = g->advance;
     } else {
         int left  = FLOOR(face->glyph->metrics.horiBearingX);
         int right = CEIL(face->glyph->metrics.horiBearingX + face->glyph->metrics.width);
         int top    = CEIL(face->glyph->metrics.horiBearingY);
         int bottom = FLOOR(face->glyph->metrics.horiBearingY - face->glyph->metrics.height);
         overall.width = TRUNC(right-left);
         overall.height = TRUNC(top-bottom);
         overall.x = TRUNC(left);
         overall.y = -TRUNC(top);
         overall.xoff = TRUNC(ROUND(face->glyph->advance.x));
     }
     if (face)
         unlockFace();
     return overall;
 }
alphaMapForGlyph() [1/2]
virtual QImage QFontEngineFT::alphaMapForGlyph (glyph_t glyph) inline virtual
Create a qimage with the alpha values for the glyph. Returns an image indexed_8 with index values ranging from 0=fully transparent to 255=opaque
Reimplemented from QFontEngine.
Definition at line 256 of file qfontengine_ft_p.h.
Referenced by alphaMapForGlyph().
 { return alphaMapForGlyph(g, 0); }
alphaMapForGlyph() [2/2]
QImage QFontEngineFT::alphaMapForGlyph (glyph_t g, QFixed subPixelPosition) virtual
Reimplemented from QFontEngine.
Definition at line 1789 of file qfontengine_ft.cpp.
 {
     lockFace();
     GlyphFormat glyph_format = antialias ? Format_A8 : Format_Mono;
     Glyph *glyph = defaultGlyphSet.outline_drawing ? 0 : loadGlyph(g, subPixelPosition, glyph_format);
     if (!glyph) {
         unlockFace();
         return QFontEngine::alphaMapForGlyph(g);
     }
     const int pitch = antialias ? (glyph->width + 3) & ~3 : ((glyph->width + 31)/32) * 4;
     QImage img(glyph->width, glyph->height, antialias ? QImage::Format_Indexed8 : QImage::Format_Mono);
     if (antialias) {
         QVector<QRgb> colors(256);
         for (int i=0; i<256; ++i)
             colors[i] = qRgba(0, 0, 0, i);
         img.setColorTable(colors);
     } else {
         QVector<QRgb> colors(2);
         colors[0] = qRgba(0, 0, 0, 0);
         colors[1] = qRgba(0, 0, 0, 255);
         img.setColorTable(colors);
     }
     Q_ASSERT(img.bytesPerLine() == pitch);
     if (glyph->width) {
         for (int y = 0; y < glyph->height; ++y)
             memcpy(img.scanLine(y), &glyph->data[y * pitch], pitch);
     }
     unlockFace();
     return img;
 }
alphaRGBMapForGlyph()
QImage QFontEngineFT::alphaRGBMapForGlyph (glyph_t g, QFixed subPixelPosition, int margin, const QTransform & t) virtual
Reimplemented from QFontEngine.
Definition at line 1825 of file qfontengine_ft.cpp.
 {
     if (t.type() > QTransform::TxTranslate)
         return QFontEngine::alphaRGBMapForGlyph(g, subPixelPosition, margin, t);
     lockFace();
     GlyphFormat glyph_format = Format_A32;
     Glyph *glyph = defaultGlyphSet.outline_drawing ? 0 : loadGlyph(g, subPixelPosition, glyph_format);
     if (!glyph) {
         unlockFace();
         return QFontEngine::alphaRGBMapForGlyph(g, subPixelPosition, margin, t);
     }
     QImage img(glyph->width, glyph->height, QImage::Format_RGB32);
     memcpy(img.bits(), glyph->data, 4 * glyph->width * glyph->height);
     unlockFace();
     return img;
 }
ascent()
QFixed QFontEngineFT::ascent () const virtual
Implements QFontEngine.
Definition at line 1170 of file qfontengine_ft.cpp.
 {
     return QFixed::fromFixed(metrics.ascender);
 }
averageCharWidth()
QFixed QFontEngineFT::averageCharWidth () const virtual
Reimplemented from QFontEngine.
Definition at line 1198 of file qfontengine_ft.cpp.
 {
     TT_OS2 *os2 = (TT_OS2 *)FT_Get_Sfnt_Table(freetype->face, ft_sfnt_os2);
     if (os2 && os2->xAvgCharWidth) {
         lockFace();
         QFixed answer = QFixed(os2->xAvgCharWidth*freetype->face->size->metrics.x_ppem)/freetype->face->units_per_EM;
         unlockFace();
         return answer;
     }
     return QFontEngine::averageCharWidth();
 }
boundingBox() [1/3]
glyph_metrics_t QFontEngineFT::boundingBox (const QGlyphLayout & glyphs) virtual
Implements QFontEngine.
Definition at line 1623 of file qfontengine_ft.cpp.
 {
     FT_Face face = 0;
     glyph_metrics_t overall;
     // initialize with line height, we get the same behaviour on all platforms
     overall.y = -ascent();
     overall.height = ascent() + descent() + 1;
     QFixed ymax = 0;
     QFixed xmax = 0;
     for (int i = 0; i < glyphs.numGlyphs; i++) {
         Glyph *g = defaultGlyphSet.getGlyph(glyphs.glyphs[i]);
         if (!g) {
             if (!face)
                 face = lockFace();
             g = loadGlyph(glyphs.glyphs[i], 0, Format_None, true);
         }
         if (g) {
             QFixed x = overall.xoff + glyphs.offsets[i].x + g->x;
             QFixed y = overall.yoff + glyphs.offsets[i].y - g->y;
             overall.x = qMin(overall.x, x);
             overall.y = qMin(overall.y, y);
             xmax = qMax(xmax, x + g->width);
             ymax = qMax(ymax, y + g->height);
             overall.xoff += qRound(g->advance);
         } else {
             int left  = FLOOR(face->glyph->metrics.horiBearingX);
             int right = CEIL(face->glyph->metrics.horiBearingX + face->glyph->metrics.width);
             int top    = CEIL(face->glyph->metrics.horiBearingY);
             int bottom = FLOOR(face->glyph->metrics.horiBearingY - face->glyph->metrics.height);
             QFixed x = overall.xoff + glyphs.offsets[i].x - (-TRUNC(left));
             QFixed y = overall.yoff + glyphs.offsets[i].y - TRUNC(top);
             overall.x = qMin(overall.x, x);
             overall.y = qMin(overall.y, y);
             xmax = qMax(xmax, x + TRUNC(right - left));
             ymax = qMax(ymax, y + TRUNC(top - bottom));
             overall.xoff += qRound(TRUNC(ROUND(face->glyph->advance.x)));
         }
     }
     overall.height = qMax(overall.height, ymax - overall.y);
     overall.width = xmax - overall.x;
     if (face)
         unlockFace();
     return overall;
 }
boundingBox() [2/3]
glyph_metrics_t QFontEngineFT::boundingBox (glyph_t glyph) virtual
Implements QFontEngine.
Definition at line 1674 of file qfontengine_ft.cpp.
 {
     FT_Face face = 0;
     glyph_metrics_t overall;
     Glyph *g = defaultGlyphSet.getGlyph(glyph);
     if (!g) {
         face = lockFace();
         g = loadGlyph(glyph, 0, Format_None, true);
     }
     if (g) {
         overall.x = g->x;
         overall.y = -g->y;
         overall.width = g->width;
         overall.height = g->height;
         overall.xoff = g->advance;
         if (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             overall.xoff = overall.xoff.round();
     } else {
         int left  = FLOOR(face->glyph->metrics.horiBearingX);
         int right = CEIL(face->glyph->metrics.horiBearingX + face->glyph->metrics.width);
         int top    = CEIL(face->glyph->metrics.horiBearingY);
         int bottom = FLOOR(face->glyph->metrics.horiBearingY - face->glyph->metrics.height);
         overall.width = TRUNC(right-left);
         overall.height = TRUNC(top-bottom);
         overall.x = TRUNC(left);
         overall.y = -TRUNC(top);
         overall.xoff = TRUNC(ROUND(face->glyph->advance.x));
     }
     if (face)
         unlockFace();
     return overall;
 }
boundingBox() [3/3]
glyph_metrics_t QFontEngineFT::boundingBox (glyph_t glyph, const QTransform & matrix) virtual
Reimplemented from QFontEngine.
Definition at line 1708 of file qfontengine_ft.cpp.
 {
     return alphaMapBoundingBox(glyph, 0, matrix, QFontEngine::Format_None);
 }
cachedGlyph()
Glyph* QFontEngineFT::cachedGlyph (glyph_t g) const inline
Definition at line 287 of file qfontengine_ft_p.h.
Referenced by QX11PaintEngine::drawFreetype().
 { return defaultGlyphSet.getGlyph(g, 0); }
canRender()
bool QFontEngineFT::canRender (const QChar * string, int len) virtual
Implements QFontEngine.
Definition at line 1433 of file qfontengine_ft.cpp.
 {
     FT_Face face = freetype->face;
 #if 0
     if (_cmap != -1) {
         lockFace();
         for ( int i = 0; i < len; i++ ) {
             unsigned int uc = getChar(string, i, len);
             if (!FcCharSetHasChar (_font->charset, uc) && getAdobeCharIndex(face, _cmap, uc) == 0) {
                 allExist = false;
                 break;
             }
         }
         unlockFace();
     } else
 #endif
     {
         for ( int i = 0; i < len; i++ ) {
             unsigned int uc = getChar(string, i, len);
             if (!FT_Get_Char_Index(face, uc))
                     return false;
         }
     }
     return true;
 }
cloneWithSize()
QFontEngine * QFontEngineFT::cloneWithSize (qreal pixelSize) const virtual
Reimplemented from QFontEngine.
Reimplemented in QFontEngineX11FT.
Definition at line 1997 of file qfontengine_ft.cpp.
 {
     QFontDef fontDef;
     fontDef.pixelSize = pixelSize;
     QFontEngineFT *fe = new QFontEngineFT(fontDef);
     if (!fe->initFromFontEngine(this)) {
         delete fe;
         return 0;
     } else {
         return fe;
     }
 }
defaultGlyphFormat()
GlyphFormat QFontEngineFT::defaultGlyphFormat () const inline
Definition at line 285 of file qfontengine_ft_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs().
 { return defaultFormat; }
defaultGlyphs()
QGlyphSet* QFontEngineFT::defaultGlyphs () inline
Definition at line 284 of file qfontengine_ft_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QX11PaintEngine::drawFreetype(), and loadSingleEngine().
 { return &defaultGlyphSet; }
defaultHintStyle()
HintStyle QFontEngineFT::defaultHintStyle () const inline
Definition at line 321 of file qfontengine_ft_p.h.
Referenced by QTextLine::glyphs().
 { return default_hint_style; }
descent()
QFixed QFontEngineFT::descent () const virtual
Implements QFontEngine.
Definition at line 1175 of file qfontengine_ft.cpp.
 {
     // subtract a pixel to work around QFontMetrics's built-in + 1
     return QFixed::fromFixed(-metrics.descender - 64);
 }
doKerning()
void QFontEngineFT::doKerning (QGlyphLayout * g, QTextEngine::ShaperFlags flags) const virtual
Reimplemented from QFontEngine.
Definition at line 1275 of file qfontengine_ft.cpp.
 {
     if (!kerning_pairs_loaded) {
         kerning_pairs_loaded = true;
         lockFace();
         if (freetype->face->size->metrics.x_ppem != 0) {
             QFixed scalingFactor(freetype->face->units_per_EM/freetype->face->size->metrics.x_ppem);
             unlockFace();
             const_cast<QFontEngineFT *>(this)->loadKerningPairs(scalingFactor);
         } else {
             unlockFace();
         }
     }
     QFontEngine::doKerning(g, flags);
 }
draw()
virtual void QFontEngineFT::draw (QPaintEngine * , qreal , qreal , const QTextItemInt &) inline virtual
Definition at line 296 of file qfontengine_ft_p.h.
 {}
drawAntialiased()
bool QFontEngineFT::drawAntialiased () const inline
Definition at line 276 of file qfontengine_ft_p.h.
Referenced by qgl_use_font().
 { return antialias; }
emSquareSize()
QFixed QFontEngineFT::emSquareSize () const virtual
Reimplemented from QFontEngine.
Definition at line 1145 of file qfontengine_ft.cpp.
 {
     if (FT_IS_SCALABLE(freetype->face))
         return freetype->face->units_per_EM;
     else
         return freetype->face->size->metrics.y_ppem;
 }
faceId()
QFontEngine::FaceId QFontEngineFT::faceId () const virtual
Reimplemented from QFontEngine.
Definition at line 1130 of file qfontengine_ft.cpp.
Referenced by QFontEngineFTRawFont::initFromData(), and initFromFontEngine().
 {
     return face_id;
 }
freeGlyphSets()
void QFontEngineFT::freeGlyphSets () protected
Definition at line 656 of file qfontengine_ft.cpp.
Referenced by QFontEngineX11FT::~QFontEngineX11FT().
 {
     freeServerGlyphSet(defaultGlyphSet.id);
     for (int i = 0; i < transformedGlyphSets.count(); ++i)
         freeServerGlyphSet(transformedGlyphSets.at(i).id);
 }
freeServerGlyphSet()
void QFontEngineFT::freeServerGlyphSet (unsigned long id) protected virtual
Reimplemented in QFontEngineX11FT.
Definition at line 1959 of file qfontengine_ft.cpp.
 {
     Q_UNUSED(id);
 }
getPointInOutline()
HB_Error QFontEngineFT::getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed * xpos, HB_Fixed * ypos, hb_uint32 * nPoints) virtual
Reimplemented from QFontEngine.
Definition at line 1964 of file qfontengine_ft.cpp.
 {
     lockFace();
     bool hsubpixel = true;
     int vfactor = 1;
     int load_flags = loadFlags(0, Format_A8, flags, hsubpixel, vfactor);
     HB_Error result = freetype->getPointInOutline(glyph, load_flags, point, xpos, ypos, nPoints);
     unlockFace();
     return result;
 }
getSfntTableData()
bool QFontEngineFT::getSfntTableData (uint tag, uchar * buffer, uint * length) const virtual
Reimplemented from QFontEngine.
Definition at line 1153 of file qfontengine_ft.cpp.
 {
     return freetype->getSfntTable(tag, buffer, length);
 }
getUnscaledGlyph()
void QFontEngineFT::getUnscaledGlyph (glyph_t glyph, QPainterPath * path, glyph_metrics_t * metrics) virtual
Reimplemented from QFontEngine.
Definition at line 1393 of file qfontengine_ft.cpp.
 {
     FT_Face face = lockFace(Unscaled);
     FT_Set_Transform(face, 0, 0);
     FT_Load_Glyph(face, glyph, FT_LOAD_NO_BITMAP);
     int left  = face->glyph->metrics.horiBearingX;
     int right = face->glyph->metrics.horiBearingX + face->glyph->metrics.width;
     int top    = face->glyph->metrics.horiBearingY;
     int bottom = face->glyph->metrics.horiBearingY - face->glyph->metrics.height;
     QFixedPoint p;
     p.x = 0;
     p.y = 0;
     metrics->width = QFixed::fromFixed(right-left);
     metrics->height = QFixed::fromFixed(top-bottom);
     metrics->x = QFixed::fromFixed(left);
     metrics->y = QFixed::fromFixed(-top);
     metrics->xoff = QFixed::fromFixed(face->glyph->advance.x);
     if (!FT_IS_SCALABLE(freetype->face))
         QFreetypeFace::addBitmapToPath(face->glyph, p, path);
     else
         QFreetypeFace::addGlyphToPath(face, face->glyph, p, path, face->units_per_EM << 6, face->units_per_EM << 6);
     FT_Set_Transform(face, &freetype->matrix, 0);
     unlockFace();
 }
glyphCount()
int QFontEngineFT::glyphCount () const virtual
Reimplemented from QFontEngine.
Definition at line 1852 of file qfontengine_ft.cpp.
 {
     int count = 0;
     FT_Face face = lockFace();
     if (face) {
         count = face->num_glyphs;
         unlockFace();
     }
     return count;
 }
init() [1/2]
bool QFontEngineFT::init (FaceId faceId, bool antiaalias, GlyphFormat defaultFormat = Format_None, const QByteArray & fontData = QByteArray())
Definition at line 663 of file qfontengine_ft.cpp.
Referenced by QFontconfigDatabase::fontEngine(), QBasicUnixFontDatabase::fontEngine(), initFromFontEngine(), and loadSingleEngine().
 {
     return init(faceId, antialias, format, QFreetypeFace::getFace(faceId, fontData));
 }
init() [2/2]
bool QFontEngineFT::init (FaceId faceId, bool antialias, GlyphFormat format, QFreetypeFace * freetypeFace)
Definition at line 669 of file qfontengine_ft.cpp.
 {
     freetype = freetypeFace;
     if (!freetype) {
         xsize = 0;
         ysize = 0;
         return false;
     }
     defaultFormat = format;
     this->antialias = antialias;
     if (!antialias)
         glyphFormat = QFontEngineGlyphCache::Raster_Mono;
     else if (format == Format_A8)
         glyphFormat = QFontEngineGlyphCache::Raster_A8;
     else if (format == Format_A32)
         glyphFormat = QFontEngineGlyphCache::Raster_RGBMask;
     face_id = faceId;
     symbol = freetype->symbol_map != 0;
     PS_FontInfoRec psrec;
     // don't assume that type1 fonts are symbol fonts by default
     if (FT_Get_PS_Font_Info(freetype->face, &psrec) == FT_Err_Ok) {
         symbol = bool(fontDef.family.contains(QLatin1String("symbol"), Qt::CaseInsensitive));
     }
     // #####
     freetype->hbFace->isSymbolFont = symbol;
     lbearing = rbearing = SHRT_MIN;
     freetype->computeSize(fontDef, &xsize, &ysize, &defaultGlyphSet.outline_drawing);
     FT_Face face = lockFace();
     if (FT_IS_SCALABLE(face)) {
         bool fake_oblique = (fontDef.style != QFont::StyleNormal) && !(face->style_flags & FT_STYLE_FLAG_ITALIC);
         if (fake_oblique)
             matrix.xy = 0x10000*3/10;
         FT_Set_Transform(face, &matrix, 0);
         freetype->matrix = matrix;
         if (fake_oblique)
             transform = true;
         // fake bold
         if ((fontDef.weight == QFont::Bold) && !(face->style_flags & FT_STYLE_FLAG_BOLD) && !FT_IS_FIXED_WIDTH(face))
             embolden = true;
         // underline metrics
         line_thickness =  QFixed::fromFixed(FT_MulFix(face->underline_thickness, face->size->metrics.y_scale));
         underline_position = QFixed::fromFixed(-FT_MulFix(face->underline_position, face->size->metrics.y_scale));
     } else {
         // copied from QFontEngineQPF
         // ad hoc algorithm
         int score = fontDef.weight * fontDef.pixelSize;
         line_thickness = score / 700;
         // looks better with thicker line for small pointsizes
         if (line_thickness < 2 && score >= 1050)
             line_thickness = 2;
         underline_position =  ((line_thickness * 2) + 3) / 6;
     }
     if (line_thickness < 1)
         line_thickness = 1;
     hbFont.x_ppem  = face->size->metrics.x_ppem;
     hbFont.y_ppem  = face->size->metrics.y_ppem;
     hbFont.x_scale = face->size->metrics.x_scale;
     hbFont.y_scale = face->size->metrics.y_scale;
     hbFace = freetype->hbFace;
     metrics = face->size->metrics;
 #if defined(Q_WS_QWS) || defined(Q_WS_QPA)
     /*
        TrueType fonts with embedded bitmaps may have a bitmap font specific
        ascent/descent in the EBLC table. There is no direct public API
        to extract those values. The only way we've found is to trick freetype
        into thinking that it's not a scalable font in FT_SelectSize so that
        the metrics are retrieved from the bitmap strikes.
     */
     if (FT_IS_SCALABLE(face)) {
         for (int i = 0; i < face->num_fixed_sizes; ++i) {
             if (xsize == X_SIZE(face, i) && ysize == Y_SIZE(face, i)) {
                 face->face_flags &= ~FT_FACE_FLAG_SCALABLE;
                 FT_Select_Size(face, i);
                 metrics.ascender = face->size->metrics.ascender;
                 metrics.descender = face->size->metrics.descender;
                 FT_Set_Char_Size(face, xsize, ysize, 0, 0);
                 face->face_flags |= FT_FACE_FLAG_SCALABLE;
                 break;
             }
         }
     }
 #endif
     fontDef.styleName = QString::fromUtf8(face->style_name);
     unlockFace();
     fsType = freetype->fsType();
     defaultGlyphSet.id = allocateServerGlyphSet();
     return true;
 }
initFromFontEngine()
bool QFontEngineFT::initFromFontEngine (const QFontEngineFT * fontEngine)
Definition at line 1975 of file qfontengine_ft.cpp.
Referenced by QFontEngineX11FT::cloneWithSize(), and cloneWithSize().
 {
     if (!init(fe->faceId(), fe->antialias, fe->defaultFormat, fe->freetype))
         return false;
     // Increase the reference of this QFreetypeFace since one more QFontEngineFT
     // will be using it
     freetype->ref.ref();
     default_load_flags = fe->default_load_flags;
     default_hint_style = fe->default_hint_style;
     antialias = fe->antialias;
     transform = fe->transform;
     embolden = fe->embolden;
     subpixelType = fe->subpixelType;
     lcdFilterType = fe->lcdFilterType;
     canUploadGlyphsToServer = fe->canUploadGlyphsToServer;
     embeddedbitmap = fe->embeddedbitmap;
     return true;
 }
invalid()
bool QFontEngineFT::invalid () const inline
Definition at line 277 of file qfontengine_ft_p.h.
Referenced by engineForPattern(), QFontconfigDatabase::fontEngine(), QBasicUnixFontDatabase::fontEngine(), and tryPatternLoad().
 { return xsize == 0 && ysize == 0; }
isBitmapFont()
bool QFontEngineFT::isBitmapFont () const inline
Definition at line 278 of file qfontengine_ft_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs().
 { return defaultFormat == Format_Mono; }
leading()
QFixed QFontEngineFT::leading () const virtual
Implements QFontEngine.
Definition at line 1181 of file qfontengine_ft.cpp.
 {
     return QFixed::fromFixed(metrics.height - metrics.ascender + metrics.descender);
 }
lineThickness()
QFixed QFontEngineFT::lineThickness () const virtual
Reimplemented from QFontEngine.
Definition at line 1265 of file qfontengine_ft.cpp.
 {
     return line_thickness;
 }
loadFlags()
int QFontEngineFT::loadFlags (QGlyphSet * set, GlyphFormat format, int flags, bool & hsubpixel, int & vfactor) const private
Definition at line 779 of file qfontengine_ft.cpp.
Referenced by getPointInOutline().
 {
     int load_flags = FT_LOAD_DEFAULT | default_load_flags;
     int load_target = default_hint_style == HintLight
                       ? FT_LOAD_TARGET_LIGHT
                       : FT_LOAD_TARGET_NORMAL;
     if (format == Format_Mono) {
         load_target = FT_LOAD_TARGET_MONO;
     } else if (format == Format_A32) {
         if (subpixelType == QFontEngineFT::Subpixel_RGB || subpixelType == QFontEngineFT::Subpixel_BGR) {
             if (default_hint_style == HintFull)
                 load_target = FT_LOAD_TARGET_LCD;
             hsubpixel = true;
         } else if (subpixelType == QFontEngineFT::Subpixel_VRGB || subpixelType == QFontEngineFT::Subpixel_VBGR) {
             if (default_hint_style == HintFull)
                 load_target = FT_LOAD_TARGET_LCD_V;
             vfactor = 3;
         }
     }
     if (set && set->outline_drawing)
         load_flags = FT_LOAD_NO_BITMAP;
     if (default_hint_style == HintNone || (flags & HB_ShaperFlag_UseDesignMetrics) || (set && set->outline_drawing))
         load_flags |= FT_LOAD_NO_HINTING;
     else
         load_flags |= load_target;
     return load_flags;
 }
loadGlyph() [1/2]
Glyph* QFontEngineFT::loadGlyph (uint glyph, QFixed subPixelPosition, GlyphFormat format = Format_None, bool fetchMetricsOnly = false) const inline
Definition at line 280 of file qfontengine_ft_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), and path_for_glyphs().
     { return loadGlyph(&defaultGlyphSet, glyph, subPixelPosition, format, fetchMetricsOnly); }
loadGlyph() [2/2]
QFontEngineFT::Glyph * QFontEngineFT::loadGlyph (QGlyphSet * set, uint glyph, QFixed subPixelPosition, GlyphFormat format = Format_None, bool fetchMetricsOnly = false) const
Definition at line 812 of file qfontengine_ft.cpp.
 {
 //     Q_ASSERT(freetype->lock == 1);
     bool uploadToServer = false;
     if (format == Format_None) {
         if (defaultFormat != Format_None) {
             format = defaultFormat;
             if (canUploadGlyphsToServer)
                 uploadToServer = true;
         } else {
             format = Format_Mono;
         }
     }
     Glyph *g = set->getGlyph(glyph, subPixelPosition);
     if (g && g->format == format) {
         if (uploadToServer && !g->uploadedToServer) {
             set->setGlyph(glyph, subPixelPosition, 0);
             delete g;
             g = 0;
         } else {
             return g;
         }
     }
     QFontEngineFT::GlyphInfo info;
     Q_ASSERT(format != Format_None);
     bool hsubpixel = false;
     int vfactor = 1;
     int load_flags = loadFlags(set, format, 0, hsubpixel, vfactor);
 #ifndef Q_WS_QWS
     if (format != Format_Mono && !embeddedbitmap)
         load_flags |= FT_LOAD_NO_BITMAP;
 #endif
     FT_Matrix matrix = freetype->matrix;
     bool transform = matrix.xx != 0x10000
                      || matrix.yy != 0x10000
                      || matrix.xy != 0
                      || matrix.yx != 0;
     if (transform)
         load_flags |= FT_LOAD_NO_BITMAP;
     FT_Face face = freetype->face;
     FT_Vector v;
     v.x = format == Format_Mono ? 0 : FT_Pos(subPixelPosition.toReal() * 64);
     v.y = 0;
     FT_Set_Transform(face, &freetype->matrix, &v);
     FT_Error err = FT_Load_Glyph(face, glyph, load_flags);
     if (err && (load_flags & FT_LOAD_NO_BITMAP)) {
         load_flags &= ~FT_LOAD_NO_BITMAP;
         err = FT_Load_Glyph(face, glyph, load_flags);
     }
     if (err == FT_Err_Too_Few_Arguments) {
         // this is an error in the bytecode interpreter, just try to run without it
         load_flags |= FT_LOAD_FORCE_AUTOHINT;
         err = FT_Load_Glyph(face, glyph, load_flags);
     }
     if (err != FT_Err_Ok)
         qWarning("load glyph failed err=%x face=%p, glyph=%d", err, face, glyph);
     if (set->outline_drawing && fetchMetricsOnly)
         return 0;
     FT_GlyphSlot slot = face->glyph;
     if (embolden) Q_FT_GLYPHSLOT_EMBOLDEN(slot);
     FT_Library library = qt_getFreetype();
     info.xOff = TRUNC(ROUND(slot->advance.x));
     info.yOff = 0;
     uchar *glyph_buffer = 0;
     int glyph_buffer_size = 0;
 #if defined(QT_USE_FREETYPE_LCDFILTER)
     bool useFreetypeRenderGlyph = false;
     if (slot->format == FT_GLYPH_FORMAT_OUTLINE && (hsubpixel || vfactor != 1)) {
         err = FT_Library_SetLcdFilter(library, (FT_LcdFilter)lcdFilterType);
         if (err == FT_Err_Ok)
             useFreetypeRenderGlyph = true;
     }
     if (useFreetypeRenderGlyph) {
         err = FT_Render_Glyph(slot, hsubpixel ? FT_RENDER_MODE_LCD : FT_RENDER_MODE_LCD_V);
         if (err != FT_Err_Ok)
             qWarning("render glyph failed err=%x face=%p, glyph=%d", err, face, glyph);
         FT_Library_SetLcdFilter(library, FT_LCD_FILTER_NONE);
         info.height = slot->bitmap.rows / vfactor;
         info.width = hsubpixel ? slot->bitmap.width / 3 : slot->bitmap.width;
         info.x = -slot->bitmap_left;
         info.y = slot->bitmap_top;
         glyph_buffer_size = info.width * info.height * 4;
         glyph_buffer = new uchar[glyph_buffer_size];
         if (hsubpixel)
             convertRGBToARGB(slot->bitmap.buffer, (uint *)glyph_buffer, info.width, info.height, slot->bitmap.pitch, subpixelType != QFontEngineFT::Subpixel_RGB, false);
         else if (vfactor != 1)
             convertRGBToARGB_V(slot->bitmap.buffer, (uint *)glyph_buffer, info.width, info.height, slot->bitmap.pitch, subpixelType != QFontEngineFT::Subpixel_VRGB, false);
     } else
 #endif
     {
     int left  = slot->metrics.horiBearingX;
     int right = slot->metrics.horiBearingX + slot->metrics.width;
     int top    = slot->metrics.horiBearingY;
     int bottom = slot->metrics.horiBearingY - slot->metrics.height;
     if(transform && slot->format != FT_GLYPH_FORMAT_BITMAP) {
         int l, r, t, b;
         FT_Vector vector;
         vector.x = left;
         vector.y = top;
         FT_Vector_Transform(&vector, &matrix);
         l = r = vector.x;
         t = b = vector.y;
         vector.x = right;
         vector.y = top;
         FT_Vector_Transform(&vector, &matrix);
         if (l > vector.x) l = vector.x;
         if (r < vector.x) r = vector.x;
         if (t < vector.y) t = vector.y;
         if (b > vector.y) b = vector.y;
         vector.x = right;
         vector.y = bottom;
         FT_Vector_Transform(&vector, &matrix);
         if (l > vector.x) l = vector.x;
         if (r < vector.x) r = vector.x;
         if (t < vector.y) t = vector.y;
         if (b > vector.y) b = vector.y;
         vector.x = left;
         vector.y = bottom;
         FT_Vector_Transform(&vector, &matrix);
         if (l > vector.x) l = vector.x;
         if (r < vector.x) r = vector.x;
         if (t < vector.y) t = vector.y;
         if (b > vector.y) b = vector.y;
         left = l;
         right = r;
         top = t;
         bottom = b;
     }
     left = FLOOR(left);
     right = CEIL(right);
     bottom = FLOOR(bottom);
     top = CEIL(top);
     int hpixels = TRUNC(right - left);
     // subpixel position requires one more pixel
     if (subPixelPosition > 0 && format != Format_Mono)
         hpixels++;
     if (hsubpixel)
         hpixels = hpixels*3 + 8;
     info.width = hpixels;
     info.height = TRUNC(top - bottom);
     info.x = -TRUNC(left);
     info.y = TRUNC(top);
     if (hsubpixel) {
         info.width /= 3;
         info.x += 1;
     }
     bool large_glyph = (((short)(slot->linearHoriAdvance>>10) != slot->linearHoriAdvance>>10)
                         || ((uchar)(info.width) != info.width)
                         || ((uchar)(info.height) != info.height)
                         || ((signed char)(info.x) != info.x)
                         || ((signed char)(info.y) != info.y)
                         || ((signed char)(info.xOff) != info.xOff));
     if (large_glyph) {
         delete [] glyph_buffer;
         return 0;
     }
     int pitch = (format == Format_Mono ? ((info.width + 31) & ~31) >> 3 :
                  (format == Format_A8 ? (info.width + 3) & ~3 : info.width * 4));
     glyph_buffer_size = pitch * info.height;
     glyph_buffer = new uchar[glyph_buffer_size];
     if (slot->format == FT_GLYPH_FORMAT_OUTLINE) {
         FT_Bitmap bitmap;
         bitmap.rows = info.height*vfactor;
         bitmap.width = hpixels;
         bitmap.pitch = format == Format_Mono ? (((info.width + 31) & ~31) >> 3) : ((bitmap.width + 3) & ~3);
         if (!hsubpixel && vfactor == 1)
             bitmap.buffer = glyph_buffer;
         else
             bitmap.buffer = new uchar[bitmap.rows*bitmap.pitch];
         memset(bitmap.buffer, 0, bitmap.rows*bitmap.pitch);
         bitmap.pixel_mode = format == Format_Mono ? FT_PIXEL_MODE_MONO : FT_PIXEL_MODE_GRAY;
         FT_Matrix matrix;
         matrix.xx = (hsubpixel ? 3 : 1) << 16;
         matrix.yy = vfactor << 16;
         matrix.yx = matrix.xy = 0;
         FT_Outline_Transform(&slot->outline, &matrix);
         FT_Outline_Translate (&slot->outline, (hsubpixel ? -3*left +(4<<6) : -left), -bottom*vfactor);
         FT_Outline_Get_Bitmap(library, &slot->outline, &bitmap);
         if (hsubpixel) {
             Q_ASSERT (bitmap.pixel_mode == FT_PIXEL_MODE_GRAY);
             Q_ASSERT(antialias);
             uchar *convoluted = new uchar[bitmap.rows*bitmap.pitch];
             bool useLegacyLcdFilter = false;
 #if defined(FC_LCD_FILTER) && defined(FT_LCD_FILTER_H)
             useLegacyLcdFilter = (lcdFilterType == FT_LCD_FILTER_LEGACY);
 #endif
             uchar *buffer = bitmap.buffer;
             if (!useLegacyLcdFilter) {
                 convoluteBitmap(bitmap.buffer, convoluted, bitmap.width, info.height, bitmap.pitch);
                 buffer = convoluted;
             }
             convertRGBToARGB(buffer + 1, (uint *)glyph_buffer, info.width, info.height, bitmap.pitch, subpixelType != QFontEngineFT::Subpixel_RGB, useLegacyLcdFilter);
             delete [] convoluted;
         } else if (vfactor != 1) {
             convertRGBToARGB_V(bitmap.buffer, (uint *)glyph_buffer, info.width, info.height, bitmap.pitch, subpixelType != QFontEngineFT::Subpixel_VRGB, true);
         }
         if (bitmap.buffer != glyph_buffer)
             delete [] bitmap.buffer;
     } else if (slot->format == FT_GLYPH_FORMAT_BITMAP) {
         Q_ASSERT(slot->bitmap.pixel_mode == FT_PIXEL_MODE_MONO);
         uchar *src = slot->bitmap.buffer;
         uchar *dst = glyph_buffer;
         int h = slot->bitmap.rows;
         if (format == Format_Mono) {
             int bytes = ((info.width + 7) & ~7) >> 3;
             while (h--) {
                 memcpy (dst, src, bytes);
                 dst += pitch;
                 src += slot->bitmap.pitch;
             }
         } else {
             if (hsubpixel) {
                 while (h--) {
                     uint *dd = (uint *)dst;
                     *dd++ = 0;
                     for (int x = 0; x < slot->bitmap.width; x++) {
                         uint a = ((src[x >> 3] & (0x80 >> (x & 7))) ? 0xffffff : 0x000000);
                         *dd++ = a;
                     }
                     *dd++ = 0;
                     dst += pitch;
                     src += slot->bitmap.pitch;
                 }
             } else if (vfactor != 1) {
                 while (h--) {
                     uint *dd = (uint *)dst;
                     for (int x = 0; x < slot->bitmap.width; x++) {
                         uint a = ((src[x >> 3] & (0x80 >> (x & 7))) ? 0xffffff : 0x000000);
                         *dd++ = a;
                     }
                     dst += pitch;
                     src += slot->bitmap.pitch;
                 }
             } else {
                 while (h--) {
                     for (int x = 0; x < slot->bitmap.width; x++) {
                         unsigned char a = ((src[x >> 3] & (0x80 >> (x & 7))) ? 0xff : 0x00);
                         dst[x] = a;
                     }
                     dst += pitch;
                     src += slot->bitmap.pitch;
                 }
             }
         }
     } else {
         qWarning("QFontEngine: Glyph neither outline nor bitmap format=%d", slot->format);
         delete [] glyph_buffer;
         return 0;
     }
     }
     if (!g) {
         g = new Glyph;
         g->uploadedToServer = false;
         g->data = 0;
     }
     g->linearAdvance = slot->linearHoriAdvance >> 10;
     g->width = info.width;
     g->height = info.height;
     g->x = -info.x;
     g->y = info.y;
     g->advance = info.xOff;
     g->format = format;
     delete [] g->data;
     g->data = glyph_buffer;
     if (uploadToServer) {
         uploadGlyphToServer(set, glyph, g, &info, glyph_buffer_size);
     }
     set->setGlyph(glyph, subPixelPosition, g);
     return g;
 }
loadGlyphs()
bool QFontEngineFT::loadGlyphs (QGlyphSet * gs, const glyph_t * glyphs, int num_glyphs, const QFixedPoint * positions, GlyphFormat format = Format_Render)
Definition at line 1363 of file qfontengine_ft.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QX11PaintEngine::drawFreetype(), and QTextureGlyphCache::textureMapForGlyph().
 {
     FT_Face face = 0;
     for (int i = 0; i < num_glyphs; ++i) {
         QFixed spp = subPixelPositionForX(positions[i].x);
         Glyph *glyph = gs->getGlyph(glyphs[i], spp);
         if (glyph == 0 || glyph->format != format) {
             if (!face) {
                 face = lockFace();
                 FT_Matrix m = matrix;
                 FT_Matrix_Multiply(&gs->transformationMatrix, &m);
                 FT_Set_Transform(face, &m, 0);
                 freetype->matrix = m;
             }
             if (!loadGlyph(gs, glyphs[i], spp, format)) {
                 unlockFace();
                 return false;
             }
         }
     }
     if (face)
         unlockFace();
     return true;
 }
loadTransformedGlyphSet()
QFontEngineFT::QGlyphSet * QFontEngineFT::loadTransformedGlyphSet (const QTransform & matrix)
Definition at line 1291 of file qfontengine_ft.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), QX11PaintEngine::drawFreetype(), and QTextureGlyphCache::textureMapForGlyph().
 {
     if (matrix.type() > QTransform::TxShear)
         return 0;
     // FT_Set_Transform only supports scalable fonts
     if (!FT_IS_SCALABLE(freetype->face))
         return 0;
     FT_Matrix m;
     m.xx = FT_Fixed(matrix.m11() * 65536);
     m.xy = FT_Fixed(-matrix.m21() * 65536);
     m.yx = FT_Fixed(-matrix.m12() * 65536);
     m.yy = FT_Fixed(matrix.m22() * 65536);
     QGlyphSet *gs = 0;
     for (int i = 0; i < transformedGlyphSets.count(); ++i) {
         const QGlyphSet &g = transformedGlyphSets.at(i);
         if (g.transformationMatrix.xx == m.xx
             && g.transformationMatrix.xy == m.xy
             && g.transformationMatrix.yx == m.yx
             && g.transformationMatrix.yy == m.yy) {
             // found a match, move it to the front
             transformedGlyphSets.move(i, 0);
             gs = &transformedGlyphSets[0];
             break;
         }
     }
     if (!gs) {
         // don't try to load huge fonts
         bool draw_as_outline = fontDef.pixelSize * qSqrt(qAbs(matrix.det())) >= QT_MAX_CACHED_GLYPH_SIZE;
         if (draw_as_outline)
             return 0;
         // don't cache more than 10 transformations
         if (transformedGlyphSets.count() >= 10) {
             transformedGlyphSets.move(transformedGlyphSets.size() - 1, 0);
             freeServerGlyphSet(transformedGlyphSets.at(0).id);
         } else {
             transformedGlyphSets.prepend(QGlyphSet());
         }
         gs = &transformedGlyphSets[0];
         gs->clear();
         gs->id = allocateServerGlyphSet();
         gs->transformationMatrix = m;
         gs->outline_drawing = draw_as_outline;
     }
     return gs;
 }
lockFace()
FT_Face QFontEngineFT::lockFace (Scaling scale = Scaled) const
Definition at line 1863 of file qfontengine_ft.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), getPointInOutline(), path_for_glyphs(), and qgl_use_font().
 {
     freetype->lock();
     FT_Face face = freetype->face;
     if (scale == Unscaled) {
         FT_Set_Char_Size(face, face->units_per_EM << 6, face->units_per_EM << 6, 0, 0);
         freetype->xsize = face->units_per_EM << 6;
         freetype->ysize = face->units_per_EM << 6;
     } else if (freetype->xsize != xsize || freetype->ysize != ysize) {
         FT_Set_Char_Size(face, xsize, ysize, 0, 0);
         freetype->xsize = xsize;
         freetype->ysize = ysize;
     }
     if (freetype->matrix.xx != matrix.xx ||
         freetype->matrix.yy != matrix.yy ||
         freetype->matrix.xy != matrix.xy ||
         freetype->matrix.yx != matrix.yx) {
         freetype->matrix = matrix;
         FT_Set_Transform(face, &freetype->matrix, 0);
     }
     return face;
 }
maxCharWidth()
qreal QFontEngineFT::maxCharWidth () const virtual
Implements QFontEngine.
Definition at line 1210 of file qfontengine_ft.cpp.
 {
     return metrics.max_advance >> 6;
 }
minLeftBearing()
qreal QFontEngineFT::minLeftBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 1239 of file qfontengine_ft.cpp.
 {
     if (lbearing == SHRT_MIN)
         (void) minRightBearing(); // calculates both
     return lbearing.toReal();
 }
minRightBearing()
qreal QFontEngineFT::minRightBearing () const virtual
Reimplemented from QFontEngine.
Definition at line 1246 of file qfontengine_ft.cpp.
 {
     if (rbearing == SHRT_MIN) {
         lbearing = rbearing = 0;
         const QChar *ch = (const QChar *)(const void*)char_table;
         QGlyphLayoutArray<char_table_entries> glyphs;
         int ng = char_table_entries;
         stringToCMap(ch, char_table_entries, &glyphs, &ng, QTextEngine::GlyphIndicesOnly);
         while (--ng) {
             if (glyphs.glyphs[ng]) {
                 glyph_metrics_t gi = const_cast<QFontEngineFT *>(this)->boundingBox(glyphs.glyphs[ng]);
                 lbearing = qMin(lbearing, gi.x);
                 rbearing = qMin(rbearing, (gi.xoff - gi.x - gi.width));
             }
         }
     }
     return rbearing.toReal();
 }
name()
virtual const char* QFontEngineFT::name () const inline virtual
Implements QFontEngine.
Definition at line 236 of file qfontengine_ft_p.h.
     { return "freetype"; }
non_locked_face()
FT_Face QFontEngineFT::non_locked_face () const
Definition at line 1892 of file qfontengine_ft.cpp.
Referenced by QFont::freetypeFace(), ft_face(), and qt_x11_set_fallback_font_family().
 {
     return freetype->face;
 }
properties()
QFontEngine::Properties QFontEngineFT::properties () const virtual
Reimplemented from QFontEngine.
Definition at line 1135 of file qfontengine_ft.cpp.
 {
     Properties p = freetype->properties();
     if (p.postscriptName.isEmpty()) {
         p.postscriptName = QFontEngine::convertToPostscriptFontFamilyName(fontDef.family.toUtf8());
     }
     return freetype->properties();
 }
recalcAdvances()
void QFontEngineFT::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented from QFontEngine.
Definition at line 1598 of file qfontengine_ft.cpp.
 {
     FT_Face face = 0;
     bool design = (default_hint_style == HintNone ||
                    default_hint_style == HintLight ||
                    (flags & HB_ShaperFlag_UseDesignMetrics)) && FT_IS_SCALABLE(freetype->face);
     for (int i = 0; i < glyphs->numGlyphs; i++) {
         Glyph *g = defaultGlyphSet.getGlyph(glyphs->glyphs[i]);
         if (g) {
             glyphs->advances_x[i] = design ? QFixed::fromFixed(g->linearAdvance) : QFixed(g->advance);
         } else {
             if (!face)
                 face = lockFace();
             g = loadGlyph(glyphs->glyphs[i], 0, Format_None, true);
             glyphs->advances_x[i] = design ? QFixed::fromFixed(face->glyph->linearHoriAdvance >> 10)
                                            : QFixed::fromFixed(face->glyph->metrics.horiAdvance).round();
         }
         if (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             glyphs->advances_x[i] = glyphs->advances_x[i].round();
         glyphs->advances_y[i] = 0;
     }
     if (face)
         unlockFace();
 }
removeGlyphFromCache()
void QFontEngineFT::removeGlyphFromCache (glyph_t glyph) virtual
Reimplemented from QFontEngine.
Definition at line 1847 of file qfontengine_ft.cpp.
 {
     defaultGlyphSet.removeGlyphFromCache(glyph, 0);
 }
setDefaultHintStyle()
void QFontEngineFT::setDefaultHintStyle (HintStyle style)
Definition at line 774 of file qfontengine_ft.cpp.
Referenced by QFontconfigDatabase::fontEngine(), and QRawFontPrivate::platformLoadFromData().
 {
     default_hint_style = style;
 }
stringToCMap()
bool QFontEngineFT::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * nglyphs, QTextEngine::ShaperFlags flags) const virtual
Implements QFontEngine.
Definition at line 1501 of file qfontengine_ft.cpp.
 {
     if (*nglyphs < len) {
         *nglyphs = len;
         return false;
     }
 #if !defined(QT_NO_FONTCONFIG)
     extern QMutex *qt_fontdatabase_mutex();
     QMutex *mtx = 0;
 #endif
     bool mirrored = flags & QTextEngine::RightToLeft;
     int glyph_pos = 0;
     if (freetype->symbol_map) {
         FT_Face face = freetype->face;
         for ( int i = 0; i < len; ++i ) {
             unsigned int uc = getChar(str, i, len);
             glyphs->glyphs[glyph_pos] = uc < QFreetypeFace::cmapCacheSize ? freetype->cmapCache[uc] : 0;
             if ( !glyphs->glyphs[glyph_pos] ) {
                 glyph_t glyph;
 #if !defined(QT_NO_FONTCONFIG)
                 if (!mtx) {
                     mtx = qt_fontdatabase_mutex();
                     mtx->lock();
                 }
                 if (freetype->charset != 0 && FcCharSetHasChar(freetype->charset, uc)) {
 #else
                 if (false) {
 #endif
                 redo0:
                     glyph = FT_Get_Char_Index(face, uc);
                     if (!glyph && (uc == 0xa0 || uc == 0x9)) {
                         uc = 0x20;
                         goto redo0;
                     }
                 } else {
                     FT_Set_Charmap(face, freetype->symbol_map);
                     glyph = FT_Get_Char_Index(face, uc);
                     FT_Set_Charmap(face, freetype->unicode_map);
                 }
                 glyphs->glyphs[glyph_pos] = glyph;
                 if (uc < QFreetypeFace::cmapCacheSize)
                     freetype->cmapCache[uc] = glyph;
             }
             ++glyph_pos;
         }
     } else {
         FT_Face face = freetype->face;
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(str, i, len);
             if (mirrored)
                 uc = QChar::mirroredChar(uc);
             glyphs->glyphs[glyph_pos] = uc < QFreetypeFace::cmapCacheSize ? freetype->cmapCache[uc] : 0;
             if (!glyphs->glyphs[glyph_pos]) {
 #if !defined(QT_NO_FONTCONFIG)
                 if (!mtx) {
                     mtx = qt_fontdatabase_mutex();
                     mtx->lock();
                 }
                 if (freetype->charset == 0 || FcCharSetHasChar(freetype->charset, uc))
 #endif
                 {
                 redo:
                     glyph_t glyph = FT_Get_Char_Index(face, uc);
                     if (!glyph && (uc == 0xa0 || uc == 0x9)) {
                         uc = 0x20;
                         goto redo;
                     }
                     glyphs->glyphs[glyph_pos] = glyph;
                     if (uc < QFreetypeFace::cmapCacheSize)
                         freetype->cmapCache[uc] = glyph;
                 }
             }
             ++glyph_pos;
         }
     }
     *nglyphs = glyph_pos;
     glyphs->numGlyphs = glyph_pos;
 #if !defined(QT_NO_FONTCONFIG)
     if (mtx)
         mtx->unlock();
 #endif
     if (flags & QTextEngine::GlyphIndicesOnly)
         return true;
     recalcAdvances(glyphs, flags);
     return true;
 }
subPixelPositionForX()
QFixed QFontEngineFT::subPixelPositionForX (QFixed x)
Definition at line 1348 of file qfontengine_ft.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs().
 {
     int m_subPixelPositionCount = 4;
     if (!supportsSubPixelPositions())
         return 0;
     QFixed subPixelPosition;
     if (x != 0) {
         subPixelPosition = x - x.floor();
         QFixed fraction = (subPixelPosition / QFixed::fromReal(1.0 / m_subPixelPositionCount)).floor();
         subPixelPosition = fraction / QFixed(m_subPixelPositionCount);
     }
     return subPixelPosition;
 }
supportsSubPixelPositions()
virtual bool QFontEngineFT::supportsSubPixelPositions () const inline virtual
Reimplemented from QFontEngine.
Definition at line 211 of file qfontengine_ft_p.h.
Referenced by QRasterPaintEngine::drawCachedGlyphs().
     {
         return default_hint_style == HintLight ||
                default_hint_style == HintNone;
     }
synthesized()
int QFontEngineFT::synthesized () const virtual
Reimplemented from QFontEngine.
Definition at line 1158 of file qfontengine_ft.cpp.
 {
     int s = 0;
     if ((fontDef.style != QFont::StyleNormal) && !(freetype->face->style_flags & FT_STYLE_FLAG_ITALIC))
         s = SynthesizedItalic;
     if ((fontDef.weight == QFont::Bold) && !(freetype->face->style_flags & FT_STYLE_FLAG_BOLD))
         s |= SynthesizedBold;
     if (fontDef.stretch != 100 && FT_IS_SCALABLE(freetype->face))
         s |= SynthesizedStretch;
     return s;
 }
type()
virtual Type QFontEngineFT::type () const inline virtual
Implements QFontEngine.
Definition at line 234 of file qfontengine_ft_p.h.
     { return QFontEngine::Freetype; }
underlinePosition()
QFixed QFontEngineFT::underlinePosition () const virtual
Reimplemented from QFontEngine.
Definition at line 1270 of file qfontengine_ft.cpp.
 {
     return underline_position;
 }
unlockFace()
void QFontEngineFT::unlockFace () const
Definition at line 1887 of file qfontengine_ft.cpp.
Referenced by QRasterPaintEngine::drawCachedGlyphs(), getPointInOutline(), path_for_glyphs(), and qgl_use_font().
 {
     freetype->unlock();
 }
uploadGlyphToServer()
bool QFontEngineFT::uploadGlyphToServer (QGlyphSet * set, uint glyphid, Glyph * g, GlyphInfo * info, int glyphDataSize) const protected virtual
Reimplemented in QFontEngineX11FT.
Definition at line 1120 of file qfontengine_ft.cpp.
 {
     Q_UNUSED(set);
     Q_UNUSED(glyphid);
     Q_UNUSED(g);
     Q_UNUSED(info);
     Q_UNUSED(glyphDataSize);
     return false;
 }
xHeight()
QFixed QFontEngineFT::xHeight () const virtual
Reimplemented from QFontEngine.
Definition at line 1186 of file qfontengine_ft.cpp.
 {
     TT_OS2 *os2 = (TT_OS2 *)FT_Get_Sfnt_Table(freetype->face, ft_sfnt_os2);
     if (os2 && os2->sxHeight) {
         lockFace();
         QFixed answer = QFixed(os2->sxHeight*freetype->face->size->metrics.y_ppem)/freetype->face->units_per_EM;
         unlockFace();
         return answer;
     }
     return QFontEngine::xHeight();
 }
Friends and Related Functions
QFontEngineFTRawFont
friend class QFontEngineFTRawFont friend
Definition at line 345 of file qfontengine_ft_p.h.
Properties
antialias
bool QFontEngineFT::antialias protected
Definition at line 336 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine(), and QFontEngineX11FT::QFontEngineX11FT().
canUploadGlyphsToServer
bool QFontEngineFT::canUploadGlyphsToServer protected
Definition at line 341 of file qfontengine_ft_p.h.
Referenced by QFontEngineX11FT::allocateServerGlyphSet(), initFromFontEngine(), QFontEngineX11FT::QFontEngineX11FT(), and QFontEngineX11FT::uploadGlyphToServer().
default_hint_style
HintStyle QFontEngineFT::default_hint_style protected
Definition at line 334 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
default_load_flags
int QFontEngineFT::default_load_flags protected
Definition at line 331 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
defaultFormat
GlyphFormat QFontEngineFT::defaultFormat private
Definition at line 349 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
defaultGlyphSet
QGlyphSet QFontEngineFT::defaultGlyphSet mutable private
Definition at line 353 of file qfontengine_ft_p.h.
embeddedbitmap
bool QFontEngineFT::embeddedbitmap protected
Definition at line 342 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
embolden
bool QFontEngineFT::embolden protected
Definition at line 338 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
face_id
QFontEngine::FaceId QFontEngineFT::face_id private
Definition at line 355 of file qfontengine_ft_p.h.
Referenced by QFontEngineX11FT::QFontEngineX11FT().
freetype
QFreetypeFace* QFontEngineFT::freetype protected
Definition at line 330 of file qfontengine_ft_p.h.
Referenced by getPointInOutline(), initFromFontEngine(), and QFontEngineFTRawFont::updateFamilyNameAndStyle().
kerning_pairs_loaded
bool QFontEngineFT::kerning_pairs_loaded mutable private
Definition at line 366 of file qfontengine_ft_p.h.
lbearing
QFixed QFontEngineFT::lbearing mutable private
Definition at line 360 of file qfontengine_ft_p.h.
lcdFilterType
int QFontEngineFT::lcdFilterType protected
Definition at line 340 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
line_thickness
QFixed QFontEngineFT::line_thickness private
Definition at line 362 of file qfontengine_ft_p.h.
matrix
FT_Matrix QFontEngineFT::matrix private
Definition at line 350 of file qfontengine_ft_p.h.
metrics
FT_Size_Metrics QFontEngineFT::metrics private
Definition at line 365 of file qfontengine_ft_p.h.
rbearing
QFixed QFontEngineFT::rbearing mutable private
Definition at line 361 of file qfontengine_ft_p.h.
subpixelType
SubpixelAntialiasingType QFontEngineFT::subpixelType protected
Definition at line 339 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine(), and QFontEngineX11FT::QFontEngineX11FT().
transform
bool QFontEngineFT::transform protected
Definition at line 337 of file qfontengine_ft_p.h.
Referenced by initFromFontEngine().
transformedGlyphSets
QList<QGlyphSet> QFontEngineFT::transformedGlyphSets private
Definition at line 352 of file qfontengine_ft_p.h.
underline_position
QFixed QFontEngineFT::underline_position private
Definition at line 363 of file qfontengine_ft_p.h.
xsize
int QFontEngineFT::xsize private
Definition at line 357 of file qfontengine_ft_p.h.
ysize
int QFontEngineFT::ysize private
Definition at line 358 of file qfontengine_ft_p.h.
The documentation for this class was generated from the following files:
/src/gui/text/qfontengine_ft_p.h
/src/gui/text/qfontengine_ft.cpp