Qt 4.8: QMutex Class Reference
QMutex Class Reference
The QMutex class provides access serialization between threads.
#include <qmutex.h>
Public Types
enum RecursionMode { NonRecursive, Recursive }
Public Functions
void lock ()
Locks the mutex.
void lockInline ()
QMutex (RecursionMode mode=NonRecursive)
Constructs a new mutex.
bool tryLock ()
Attempts to lock the mutex.
bool tryLock (int timeout)
Attempts to lock the mutex.
bool tryLockInline ()
void unlock ()
Unlocks the mutex.
void unlockInline ()
~QMutex ()
Destroys the mutex.
Private Functions
void lockInternal ()
void unlockInternal ()
Properties
QMutexData * d
Friends
class QWaitCondition
class QWaitConditionPrivate
Detailed Description
The QMutex class provides access serialization between threads.
Note
This class or function is threadsafe.
The purpose of a QMutex is to protect an object, data structure or section of code so that only one thread can access it at a time (this is similar to the Java synchronized keyword). It is usually best to use a mutex with a QMutexLocker since this makes it easy to ensure that locking and unlocking are performed consistently.
For example, say there is a method that prints a message to the user on two lines:
int number = 6;
void method1()
{
    number *= 5;
    number /= 4;
}
void method2()
{
    number *= 3;
    number /= 2;
}
If these two methods are called in succession, the following happens:
// method1()
number *= 5;        // number is now 30
number /= 4;        // number is now 7
// method2()
number *= 3;        // number is now 21
number /= 2;        // number is now 10
If these two methods are called simultaneously from two threads then the following sequence could result:
// Thread 1 calls method1()
number *= 5;        // number is now 30
// Thread 2 calls method2().
//
// Most likely Thread 1 has been put to sleep by the operating
// system to allow Thread 2 to run.
number *= 3;        // number is now 90
number /= 2;        // number is now 45
// Thread 1 finishes executing.
number /= 4;        // number is now 11, instead of 10
If we add a mutex, we should get the result we want:
QMutex mutex;
int number = 6;
void method1()
{
    mutex.lock();
    number *= 5;
    number /= 4;
    mutex.unlock();
}
void method2()
{
    mutex.lock();
    number *= 3;
    number /= 2;
    mutex.unlock();
}
Then only one thread can modify number at any given time and the result is correct. This is a trivial example, of course, but applies to any other case where things need to happen in a particular sequence.
When you call lock() in a thread, other threads that try to call lock() in the same place will block until the thread that got the lock calls unlock(). A non-blocking alternative to lock() is tryLock().
See also
QMutexLocker, QReadWriteLock, QSemaphore, QWaitCondition
Definition at line 60 of file qmutex.h.
Enumerations
RecursionMode
enum QMutex::RecursionMode
Recursive In this mode, a thread can lock the same mutex multiple times and the mutex won't be unlocked until a corresponding number of unlock() calls have been made.
NonRecursive In this mode, a thread may only lock a mutex once.
See also
QMutex()
Enumerator
NonRecursive
Recursive
Definition at line 66 of file qmutex.h.
 { NonRecursive, Recursive };
Constructors and Destructors
QMutex()
QMutex::QMutex (RecursionMode mode = NonRecursive) explicit
Constructs a new mutex.
Use the constructor that takes a RecursionMode parameter instead.
The mutex is created in an unlocked state.
If mode is QMutex::Recursive, a thread can lock the same mutex multiple times and the mutex won't be unlocked until a corresponding number of unlock() calls have been made. The default is QMutex::NonRecursive.
See also
lock(), unlock()
Definition at line 127 of file qmutex.cpp.
     : d(new QMutexPrivate(mode))
 { }
~QMutex()
QMutex::~QMutex ()
Destroys the mutex.
Warning
Destroying a locked mutex may result in undefined behavior.
Definition at line 136 of file qmutex.cpp.
 { delete static_cast<QMutexPrivate *>(d); }
Functions
lock()
void QMutex::lock ()
Locks the mutex.
If another thread has locked the mutex then this call will block until that thread has unlocked it.
Calling this function multiple times on the same mutex from the same thread is allowed if this mutex is a recursive mutex. If this mutex is a non-recursive mutex, this function will dead-lock when the mutex is locked recursively.
See also
unlock()
Definition at line 151 of file qmutex.cpp.
Referenced by QNetworkManagerEngine::activationFinished(), QNetworkManagerEngine::activeConnectionPropertiesChanged(), QIcdEngine::addConfiguration(), QNetworkConfigurationManagerPrivate::configurationAdded(), QConnmanEngine::configurationChange(), QNetworkConfigurationManagerPrivate::configurationChanged(), QNetworkConfigurationManagerPrivate::configurationRemoved(), QNetworkManagerEngine::deviceAdded(), QNetworkSessionPrivateImpl::do_open(), QGenericEngine::doRequestUpdate(), QIcdEngine::doRequestUpdate(), QNlaThread::fetchConfigurations(), QThreadPrivate::finish(), QNlaThread::forceUpdate(), QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QIcdEngine::getIcdInitialState(), QNetworkSessionPrivateImpl::getStatistics(), QDeclarativeXmlQueryEngine::instance(), QNetworkManagerEngine::interfacePropertiesChanged(), QDeclarativePixmap::load(), QFreetypeFace::lock(), QWSDirectPainterSurface::lock(), locking_function(), QDeclarativePixmapReader::networkRequestDone(), QCoreWlanEngine::networksChanged(), QNlaEngine::networksChanged(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::parseConnection(), QWaitConditionPrivate::post(), QCoreApplication::postEvent(), QDBusMutexLocker::QDBusMutexLocker(), QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine(), qt_adopted_thread_watcher_function(), QDeclarativePixmapData::release(), QOrderedMutexLocker::relock(), QNetworkManagerEngine::removeAccessPoint(), QScanThread::run(), QWindowsPipeWriter::run(), QDeclarativeXmlQueryEngine::run(), QNlaThread::run(), QNativeWifiEngine::scanComplete(), QDnotifySignalThread::startNotify(), QNetworkSessionPrivateImpl::stateChange(), QFontEngineFT::stringToCMap(), QDeclarativeListModelWorkerAgent::sync(), QNetworkManagerEngine::updateAccessPoint(), QNlaThread::updateConfigurations(), QNetworkManagerEngine::updateConnection(), QNetworkSessionPrivateImpl::updateIdentifier(), QNetworkSessionPrivateImpl::updateState(), QWaitCondition::wait(), QDBusConnectionPrivate::waitForFinished(), QDeclarativePixmapReader::~QDeclarativePixmapReader(), QDeclarativeWorkerScriptEngine::~QDeclarativeWorkerScriptEngine(), QDeclarativeXmlQueryEngine::~QDeclarativeXmlQueryEngine(), QNlaThread::~QNlaThread(), and QWindowsPipeWriter::~QWindowsPipeWriter().
 {
     QMutexPrivate *d = static_cast<QMutexPrivate *>(this->d);
     Qt::HANDLE self;
     if (d->recursive) {
         self = QThread::currentThreadId();
         if (d->owner == self) {
             ++d->count;
             Q_ASSERT_X(d->count != 0, "QMutex::lock", "Overflow in recursion counter");
             return;
         }
         bool isLocked = d->contenders.testAndSetAcquire(0, 1);
         if (!isLocked) {
             // didn't get the lock, wait for it
             isLocked = d->wait();
             Q_ASSERT_X(isLocked, "QMutex::lock",
                        "Internal error, infinite wait has timed out.");
         }
         d->owner = self;
         ++d->count;
         Q_ASSERT_X(d->count != 0, "QMutex::lock", "Overflow in recursion counter");
         return;
     }
     bool isLocked = d->contenders.testAndSetAcquire(0, 1);
     if (!isLocked) {
         lockInternal();
     }
 }
lockInline()
void QMutex::lockInline () inline
Warning
This function is not part of the public interface. inline version of QMutex::lock()
Definition at line 198 of file qmutex.h.
Referenced by QMutexLocker::QMutexLocker(), and QOrderedMutexLocker::relock().
 { lock(); }
lockInternal()
void QMutex::lockInternal () private
Warning
This function is not part of the public interface. helper for lockInline()
Definition at line 454 of file qmutex.cpp.
Referenced by lock().
 {
     QMutexPrivate *d = static_cast<QMutexPrivate *>(this->d);
     if (QThread::idealThreadCount() == 1) {
         // don't spin on single cpu machines
         bool isLocked = d->wait();
         Q_ASSERT_X(isLocked, "QMutex::lock",
                    "Internal error, infinite wait has timed out.");
         Q_UNUSED(isLocked);
         return;
     }
     QElapsedTimer elapsedTimer;
     elapsedTimer.start();
     do {
         qint64 spinTime = elapsedTimer.nsecsElapsed();
         if (spinTime > d->maximumSpinTime) {
             // didn't get the lock, wait for it, since we're not going to gain anything by spinning more
             elapsedTimer.start();
             bool isLocked = d->wait();
             Q_ASSERT_X(isLocked, "QMutex::lock",
                        "Internal error, infinite wait has timed out.");
             Q_UNUSED(isLocked);
             qint64 maximumSpinTime = d->maximumSpinTime;
             qint64 averageWaitTime = d->averageWaitTime;
             qint64 actualWaitTime = elapsedTimer.nsecsElapsed();
             if (actualWaitTime < (QMutexPrivate::MaximumSpinTimeThreshold * 3 / 2)) {
                 // measure the wait times
                 averageWaitTime = d->averageWaitTime = qMin((averageWaitTime + actualWaitTime) / 2, qint64(QMutexPrivate::MaximumSpinTimeThreshold));
             }
             // adjust the spin count when spinning does not benefit contention performance
             if ((spinTime + actualWaitTime) - qint64(QMutexPrivate::MaximumSpinTimeThreshold) >= qint64(QMutexPrivate::MaximumSpinTimeThreshold)) {
                 // long waits, stop spinning
                 d->maximumSpinTime = 0;
             } else {
                 // allow spinning if wait times decrease, but never spin more than the average wait time (otherwise we may perform worse)
                 d->maximumSpinTime = qBound(qint64(averageWaitTime * 3 / 2), maximumSpinTime / 2, qint64(QMutexPrivate::MaximumSpinTimeThreshold));
             }
             return;
         }
         // be a good citizen... yielding lets something else run if there is something to run, but may also relieve memory pressure if not
         QThread::yieldCurrentThread();
     } while (d->contenders != 0 || !d->contenders.testAndSetAcquire(0, 1));
     // spinning is working, do not change the spin time (unless we are using much less time than allowed to spin)
     qint64 maximumSpinTime = d->maximumSpinTime;
     qint64 spinTime = elapsedTimer.nsecsElapsed();
     if (spinTime < maximumSpinTime / 2) {
         // we are using much less time than we need, adjust the limit
         d->maximumSpinTime = qBound(qint64(d->averageWaitTime * 3 / 2), maximumSpinTime / 2, qint64(QMutexPrivate::MaximumSpinTimeThreshold));
     }
 }
tryLock() [1/2]
bool QMutex::tryLock ()
Attempts to lock the mutex.
If the lock was obtained, this function returns true. If another thread has locked the mutex, this function returns false immediately.
If the lock was obtained, the mutex must be unlocked with unlock() before another thread can successfully lock it.
Calling this function multiple times on the same mutex from the same thread is allowed if this mutex is a recursive mutex. If this mutex is a non-recursive mutex, this function will always return false when attempting to lock the mutex recursively.
See also
lock(), unlock()
Definition at line 201 of file qmutex.cpp.
 {
     QMutexPrivate *d = static_cast<QMutexPrivate *>(this->d);
     Qt::HANDLE self;
     if (d->recursive) {
         self = QThread::currentThreadId();
         if (d->owner == self) {
             ++d->count;
             Q_ASSERT_X(d->count != 0, "QMutex::tryLock", "Overflow in recursion counter");
             return true;
         }
         bool isLocked = d->contenders.testAndSetAcquire(0, 1);
         if (!isLocked) {
             // some other thread has the mutex locked, or we tried to
             // recursively lock an non-recursive mutex
             return isLocked;
         }
         d->owner = self;
         ++d->count;
         Q_ASSERT_X(d->count != 0, "QMutex::tryLock", "Overflow in recursion counter");
         return isLocked;
     }
     return d->contenders.testAndSetAcquire(0, 1);
 }
tryLock() [2/2]
bool QMutex::tryLock (int timeout)
Attempts to lock the mutex.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function returns true if the lock was obtained; otherwise it returns false. If another thread has locked the mutex, this function will wait for at most timeout milliseconds for the mutex to become available.
Note: Passing a negative number as the timeout is equivalent to calling lock(), i.e. this function will wait forever until mutex can be locked if timeout is negative.
If the lock was obtained, the mutex must be unlocked with unlock() before another thread can successfully lock it.
Calling this function multiple times on the same mutex from the same thread is allowed if this mutex is a recursive mutex. If this mutex is a non-recursive mutex, this function will always return false when attempting to lock the mutex recursively.
See also
lock(), unlock()
Definition at line 256 of file qmutex.cpp.
 {
     QMutexPrivate *d = static_cast<QMutexPrivate *>(this->d);
     Qt::HANDLE self;
     if (d->recursive) {
         self = QThread::currentThreadId();
         if (d->owner == self) {
             ++d->count;
             Q_ASSERT_X(d->count != 0, "QMutex::tryLock", "Overflow in recursion counter");
             return true;
         }
         bool isLocked = d->contenders.testAndSetAcquire(0, 1);
         if (!isLocked) {
             // didn't get the lock, wait for it
             isLocked = d->wait(timeout);
             if (!isLocked)
                 return false;
         }
         d->owner = self;
         ++d->count;
         Q_ASSERT_X(d->count != 0, "QMutex::tryLock", "Overflow in recursion counter");
         return true;
     }
     return (d->contenders.testAndSetAcquire(0, 1)
             // didn't get the lock, wait for it
             || d->wait(timeout));
 }
tryLockInline()
bool QMutex::tryLockInline () inline
Warning
This function is not part of the public interface. inline version of QMutex::tryLock()
Definition at line 197 of file qmutex.h.
Referenced by QOrderedMutexLocker::relock().
 { return tryLock(); }
unlock()
void QMutex::unlock ()
Unlocks the mutex.
Attempting to unlock a mutex in a different thread to the one that locked it results in an error. Unlocking a mutex that is not locked results in undefined behavior.
See also
lock()
Definition at line 296 of file qmutex.cpp.
Referenced by QNetworkManagerEngine::activationFinished(), QNetworkManagerEngine::activeConnectionPropertiesChanged(), QIcdEngine::addConfiguration(), QNetworkConfigurationManagerPrivate::configurationAdded(), QConnmanEngine::configurationChange(), QNetworkConfigurationManagerPrivate::configurationChanged(), QNetworkConfigurationManagerPrivate::configurationRemoved(), QNetworkManagerEngine::deviceAdded(), QNetworkSessionPrivateImpl::do_open(), QGenericEngine::doRequestUpdate(), QIcdEngine::doRequestUpdate(), QNlaThread::fetchConfigurations(), QThreadPrivate::finish(), QNlaThread::forceUpdate(), QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QIcdEngine::getIcdInitialState(), QNetworkSessionPrivateImpl::getStatistics(), QDeclarativeXmlQueryEngine::instance(), QNetworkManagerEngine::interfacePropertiesChanged(), QDeclarativePixmap::load(), locking_function(), QDeclarativePixmapReader::networkRequestDone(), QCoreWlanEngine::networksChanged(), QNlaEngine::networksChanged(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::parseConnection(), QWaitConditionPrivate::post(), QCoreApplication::postEvent(), QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine(), qt_adopted_thread_watcher_function(), QDeclarativePixmapData::release(), QOrderedMutexLocker::relock(), QNetworkManagerEngine::removeAccessPoint(), QScanThread::run(), QWindowsPipeWriter::run(), QDeclarativeXmlQueryEngine::run(), QNlaThread::run(), QNativeWifiEngine::scanComplete(), QDnotifySignalThread::startNotify(), QNetworkSessionPrivateImpl::stateChange(), QFontEngineFT::stringToCMap(), QDeclarativeListModelWorkerAgent::sync(), QFreetypeFace::unlock(), QMutexUnlocker::unlock(), QWSDirectPainterSurface::unlock(), QNetworkManagerEngine::updateAccessPoint(), QNlaThread::updateConfigurations(), QNetworkManagerEngine::updateConnection(), QNetworkSessionPrivateImpl::updateIdentifier(), QNetworkSessionPrivateImpl::updateState(), QWaitCondition::wait(), QDBusConnectionPrivate::waitForFinished(), QDBusMutexLocker::~QDBusMutexLocker(), QDeclarativePixmapReader::~QDeclarativePixmapReader(), QDeclarativeWorkerScriptEngine::~QDeclarativeWorkerScriptEngine(), QDeclarativeXmlQueryEngine::~QDeclarativeXmlQueryEngine(), QNlaThread::~QNlaThread(), and QWindowsPipeWriter::~QWindowsPipeWriter().
 {
     QMutexPrivate *d = static_cast<QMutexPrivate *>(this->d);
     if (d->recursive) {
         if (!--d->count) {
             d->owner = 0;
             if (!d->contenders.testAndSetRelease(1, 0))
                 d->wakeUp();
         }
     } else {
         if (!d->contenders.testAndSetRelease(1, 0))
             d->wakeUp();
     }
 }
unlockInline()
void QMutex::unlockInline () inline
Warning
This function is not part of the public interface. inline version of QMutex::unlock()
Definition at line 196 of file qmutex.h.
Referenced by QMetaObjectPrivate::disconnectHelper(), QOrderedMutexLocker::unlock(), and QObject::~QObject().
 { unlock(); }
unlockInternal()
void QMutex::unlockInternal () private
Warning
This function is not part of the public interface.
Definition at line 513 of file qmutex.cpp.
 {
     static_cast<QMutexPrivate *>(d)->wakeUp();
 }
Friends and Related Functions
QWaitCondition
friend class QWaitCondition friend
Definition at line 62 of file qmutex.h.
QWaitConditionPrivate
friend class QWaitConditionPrivate friend
Definition at line 63 of file qmutex.h.
Properties
d
QMutexData* QMutex::d private
Definition at line 98 of file qmutex.h.
Referenced by lock(), lockInternal(), QWaitConditionPrivate::post(), tryLock(), unlock(), unlockInternal(), QWaitCondition::wait(), and ~QMutex().
The documentation for this class was generated from the following files:
/src/corelib/thread/qmutex.h
/src/corelib/thread/qmutex.cpp