Qt 4.8: QDeclarativeState Class Reference
QDeclarativeState Class Reference
#include <qdeclarativestate_p.h>
Signals
void completed ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addEntriesToRevertList (const QList< QDeclarativeAction > &actions)
void addEntryToRevertList (const QDeclarativeAction &action)
void apply (QDeclarativeStateGroup *, QDeclarativeTransition *, QDeclarativeState *revert)
QDeclarativeAbstractBinding * bindingInRevertList (QObject *target, const QString &name) const
void cancel ()
bool changeBindingInRevertList (QObject *target, const QString &name, QDeclarativeAbstractBinding *binding)
QDeclarativeListProperty< QDeclarativeStateOperation > changes ()
bool changeValueInRevertList (QObject *target, const QString &name, const QVariant &revertValue)
bool containsPropertyInRevertList (QObject *target, const QString &name) const
QString extends () const
bool isNamed () const
bool isStateActive () const
bool isWhenKnown () const
QString name () const
QDeclarativeStateOperation * operationAt (int) const
int operationCount () const
QDeclarativeState & operator<< (QDeclarativeStateOperation *)
QDeclarativeState (QObject *parent=0)
void removeAllEntriesFromRevertList (QObject *target)
bool removeEntryFromRevertList (QObject *target, const QString &name)
void setExtends (const QString &)
void setName (const QString &)
void setStateGroup (QDeclarativeStateGroup *)
void setWhen (QDeclarativeBinding *)
QDeclarativeStateGroup * stateGroup () const
QVariant valueInRevertList (QObject *target, const QString &name) const
QDeclarativeBinding * when () const
virtual ~QDeclarativeState ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QDeclarativeListProperty< QDeclarativeStateOperation > changes
QString extend
QString name
QDeclarativeBinding * when
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 143 of file qdeclarativestate_p.h.
Constructors and Destructors
QDeclarativeState()
QDeclarativeState::QDeclarativeState (QObject * parent = 0)
Definition at line 167 of file qdeclarativestate.cpp.
 : QObject(*(new QDeclarativeStatePrivate), parent)
 {
     Q_D(QDeclarativeState);
     d->transitionManager.setState(this);
 }
~QDeclarativeState()
QDeclarativeState::~QDeclarativeState () virtual
Definition at line 174 of file qdeclarativestate.cpp.
 {
     Q_D(QDeclarativeState);
     if (d->group)
         d->group->removeState(this);
     /*
       destroying an active state does not return us to the
       base state, so we need to clean up our revert list to
       prevent leaks. In the future we may want to redconsider
       this overall architecture.
     */
     for (int i = 0; i < d->revertList.count(); ++i) {
         if (d->revertList.at(i).binding()) {
             d->revertList.at(i).binding()->destroy();
         }
     }
 }
Functions
addEntriesToRevertList()
void QDeclarativeState::addEntriesToRevertList (const QList< QDeclarativeAction > & actions)
Definition at line 525 of file qdeclarativestate.cpp.
Referenced by QDeclarativePropertyChanges::attachToState().
 {
     Q_D(QDeclarativeState);
     if (isStateActive()) {
         QList<QDeclarativeSimpleAction> simpleActionList;
         QListIterator<QDeclarativeAction> actionListIterator(actionList);
         while(actionListIterator.hasNext()) {
             const QDeclarativeAction &action = actionListIterator.next();
             QDeclarativeSimpleAction simpleAction(action);
             action.property.write(action.toValue);
             if (!action.toBinding.isNull()) {
                 QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(simpleAction.property());
                 if (oldBinding)
                     QDeclarativePropertyPrivate::setBinding(simpleAction.property(), 0);
                 QDeclarativePropertyPrivate::setBinding(simpleAction.property(), action.toBinding.data(), QDeclarativePropertyPrivate::DontRemoveBinding);
             }
             simpleActionList.append(simpleAction);
         }
         d->revertList.append(simpleActionList);
     }
 }
addEntryToRevertList()
void QDeclarativeState::addEntryToRevertList (const QDeclarativeAction & action)
Definition at line 490 of file qdeclarativestate.cpp.
Referenced by QDeclarativePropertyChanges::changeExpression(), and QDeclarativePropertyChanges::changeValue().
 {
     Q_D(QDeclarativeState);
     QDeclarativeSimpleAction simpleAction(action);
     d->revertList.append(simpleAction);
 }
apply()
void QDeclarativeState::apply (QDeclarativeStateGroup * group, QDeclarativeTransition * trans, QDeclarativeState * revert)
Definition at line 589 of file qdeclarativestate.cpp.
Referenced by QDeclarativeStateGroupPrivate::setCurrentStateInternal().
 {
     Q_D(QDeclarativeState);
     qmlExecuteDeferred(this);
     cancel();
     if (revert)
         revert->cancel();
     d->revertList.clear();
     d->reverting.clear();
     if (revert) {
         QDeclarativeStatePrivate *revertPrivate =
             static_cast<QDeclarativeStatePrivate*>(revert->d_func());
         d->revertList = revertPrivate->revertList;
         revertPrivate->revertList.clear();
     }
     // List of actions caused by this state
     QDeclarativeStateOperation::ActionList applyList = d->generateActionList(group);
     // List of actions that need to be reverted to roll back (just) this state
     QDeclarativeStatePrivate::SimpleActionList additionalReverts;
     // First add the reverse of all the applyList actions
     for (int ii = 0; ii < applyList.count(); ++ii) {
         QDeclarativeAction &action = applyList[ii];
         if (action.event) {
             if (!action.event->isReversable())
                 continue;
             bool found = false;
             for (int jj = 0; jj < d->revertList.count(); ++jj) {
                 QDeclarativeActionEvent *event = d->revertList.at(jj).event();
                 if (event && event->typeName() == action.event->typeName()) {
                     if (action.event->override(event)) {
                         found = true;
                         if (action.event != d->revertList.at(jj).event() && action.event->needsCopy()) {
                             action.event->copyOriginals(d->revertList.at(jj).event());
                             QDeclarativeSimpleAction r(action);
                             additionalReverts << r;
                             d->revertList.removeAt(jj);
                             --jj;
                         } else if (action.event->isRewindable())    //###why needed?
                             action.event->saveCurrentValues();
                         break;
                     }
                 }
             }
             if (!found) {
                 action.event->saveOriginals();
                 // Only need to revert the applyList action if the previous
                 // state doesn't have a higher priority revert already
                 QDeclarativeSimpleAction r(action);
                 additionalReverts << r;
             }
         } else {
             bool found = false;
             action.fromBinding = QDeclarativePropertyPrivate::binding(action.property);
             for (int jj = 0; jj < d->revertList.count(); ++jj) {
                 if (d->revertList.at(jj).property() == action.property) {
                     found = true;
                     if (d->revertList.at(jj).binding() != action.fromBinding) {
                         action.deleteFromBinding();
                     }
                     break;
                 }
             }
             if (!found) {
                 if (!action.restore) {
                     action.deleteFromBinding();;
                 } else {
                     // Only need to revert the applyList action if the previous
                     // state doesn't have a higher priority revert already
                     QDeclarativeSimpleAction r(action);
                     additionalReverts << r;
                 }
             }
         }
     }
     // Any reverts from a previous state that aren't carried forth
     // into this state need to be translated into apply actions
     for (int ii = 0; ii < d->revertList.count(); ++ii) {
         bool found = false;
         if (d->revertList.at(ii).event()) {
             QDeclarativeActionEvent *event = d->revertList.at(ii).event();
             if (!event->isReversable())
                 continue;
             for (int jj = 0; !found && jj < applyList.count(); ++jj) {
                 const QDeclarativeAction &action = applyList.at(jj);
                 if (action.event && action.event->typeName() == event->typeName()) {
                     if (action.event->override(event))
                         found = true;
                 }
             }
         } else {
             for (int jj = 0; !found && jj < applyList.count(); ++jj) {
                 const QDeclarativeAction &action = applyList.at(jj);
                 if (action.property == d->revertList.at(ii).property())
                     found = true;
             }
         }
         if (!found) {
             QVariant cur = d->revertList.at(ii).property().read();
             QDeclarativeAbstractBinding *delBinding =
                 QDeclarativePropertyPrivate::setBinding(d->revertList.at(ii).property(), 0);
             if (delBinding)
                 delBinding->destroy();
             QDeclarativeAction a;
             a.property = d->revertList.at(ii).property();
             a.fromValue = cur;
             a.toValue = d->revertList.at(ii).value();
             a.toBinding = QDeclarativeAbstractBinding::getPointer(d->revertList.at(ii).binding());
             a.specifiedObject = d->revertList.at(ii).specifiedObject();
             a.specifiedProperty = d->revertList.at(ii).specifiedProperty();
             a.event = d->revertList.at(ii).event();
             a.reverseEvent = d->revertList.at(ii).reverseEvent();
             if (a.event && a.event->isRewindable())
                 a.event->saveCurrentValues();
             applyList << a;
             // Store these special reverts in the reverting list
             d->reverting << d->revertList.at(ii).property();
         }
     }
     // All the local reverts now become part of the ongoing revertList
     d->revertList << additionalReverts;
 #ifndef QT_NO_DEBUG_STREAM
     // Output for debugging
     if (stateChangeDebug()) {
         foreach(const QDeclarativeAction &action, applyList) {
             if (action.event)
                 qWarning() << "    QDeclarativeAction event:" << action.event->typeName();
             else
                 qWarning() << "    QDeclarativeAction:" << action.property.object()
                            << action.property.name() << "From:" << action.fromValue
                            << "To:" << action.toValue;
         }
     }
 #endif
     d->transitionManager.transition(applyList, trans);
 }
bindingInRevertList()
QDeclarativeAbstractBinding * QDeclarativeState::bindingInRevertList (QObject * target, const QString & name) const
Definition at line 567 of file qdeclarativestate.cpp.
 {
     Q_D(const QDeclarativeState);
     if (isStateActive()) {
         QListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
         while (revertListIterator.hasNext()) {
             const QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
             if (simpleAction.specifiedObject() == target && simpleAction.specifiedProperty() == name)
                 return simpleAction.binding();
         }
     }
     return 0;
 }
cancel()
void QDeclarativeState::cancel ()
Definition at line 388 of file qdeclarativestate.cpp.
Referenced by apply().
 {
     Q_D(QDeclarativeState);
     d->transitionManager.cancel();
 }
changeBindingInRevertList()
bool QDeclarativeState::changeBindingInRevertList (QObject * target, const QString & name, QDeclarativeAbstractBinding * binding)
Definition at line 439 of file qdeclarativestate.cpp.
Referenced by QDeclarativePropertyChanges::changeExpression().
 {
     Q_D(QDeclarativeState);
     if (isStateActive()) {
         QMutableListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
         while (revertListIterator.hasNext()) {
             QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
             if (simpleAction.specifiedObject() == target && simpleAction.specifiedProperty() == name) {
                 if (simpleAction.binding())
                     simpleAction.binding()->destroy();
                 simpleAction.setBinding(binding);
                 return true;
             }
         }
     }
     return false;
 }
changes()
QDeclarativeListProperty<QDeclarativeStateOperation> QDeclarativeState::changes ()
Referenced by setExtends().
changeValueInRevertList()
bool QDeclarativeState::changeValueInRevertList (QObject * target, const QString & name, const QVariant & revertValue)
Definition at line 420 of file qdeclarativestate.cpp.
 {
     Q_D(QDeclarativeState);
     if (isStateActive()) {
         QMutableListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
         while (revertListIterator.hasNext()) {
             QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
             if (simpleAction.specifiedObject() == target && simpleAction.specifiedProperty() == name) {
                     simpleAction.setValue(revertValue);
                     return true;
             }
         }
     }
     return false;
 }
completed
void QDeclarativeState::completed () signal
containsPropertyInRevertList()
bool QDeclarativeState::containsPropertyInRevertList (QObject * target, const QString & name) const
Definition at line 403 of file qdeclarativestate.cpp.
 {
     Q_D(const QDeclarativeState);
     if (isStateActive()) {
         QListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
         while (revertListIterator.hasNext()) {
             const QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
             if (simpleAction.specifiedObject() == target && simpleAction.specifiedProperty() == name)
                 return true;
         }
     }
     return false;
 }
extends()
QString QDeclarativeState::extends () const
Definition at line 280 of file qdeclarativestate.cpp.
Referenced by QDeclarativeStatePrivate::generateActionList(), and setExtends().
 {
     Q_D(const QDeclarativeState);
     return d->extends;
 }
isNamed()
bool QDeclarativeState::isNamed () const
Definition at line 215 of file qdeclarativestate.cpp.
Referenced by QDeclarativeStateGroup::componentComplete(), and QDeclarativeStateGroupPrivate::updateAutoState().
 {
     Q_D(const QDeclarativeState);
     return d->named;
 }
isStateActive()
bool QDeclarativeState::isStateActive () const
Definition at line 584 of file qdeclarativestate.cpp.
Referenced by addEntriesToRevertList(), bindingInRevertList(), changeBindingInRevertList(), changeValueInRevertList(), containsPropertyInRevertList(), removeAllEntriesFromRevertList(), removeEntryFromRevertList(), and valueInRevertList().
 {
     return stateGroup() && stateGroup()->state() == name();
 }
isWhenKnown()
bool QDeclarativeState::isWhenKnown () const
Definition at line 221 of file qdeclarativestate.cpp.
Referenced by QDeclarativeStateGroupPrivate::updateAutoState().
 {
     Q_D(const QDeclarativeState);
     return d->when != 0;
 }
name()
QString QDeclarativeState::name () const
Referenced by bindingInRevertList(), changeBindingInRevertList(), changeValueInRevertList(), containsPropertyInRevertList(), isStateActive(), removeEntryFromRevertList(), valueInRevertList(), and ~QDeclarativeState().
operationAt()
QDeclarativeStateOperation * QDeclarativeState::operationAt (int index) const
Definition at line 318 of file qdeclarativestate.cpp.
 {
     Q_D(const QDeclarativeState);
     return d->operations.at(index);
 }
operationCount()
int QDeclarativeState::operationCount () const
Definition at line 312 of file qdeclarativestate.cpp.
 {
     Q_D(const QDeclarativeState);
     return d->operations.count();
 }
operator<<()
QDeclarativeState & QDeclarativeState::operator<< (QDeclarativeStateOperation * op)
Definition at line 324 of file qdeclarativestate.cpp.
 {
     Q_D(QDeclarativeState);
     d->operations.append(QDeclarativeStatePrivate::OperationGuard(op, &d->operations));
     return *this;
 }
removeAllEntriesFromRevertList()
void QDeclarativeState::removeAllEntriesFromRevertList (QObject * target)
Definition at line 499 of file qdeclarativestate.cpp.
Referenced by QDeclarativePropertyChanges::detachFromState().
 {
      Q_D(QDeclarativeState);
      if (isStateActive()) {
          QMutableListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
          while (revertListIterator.hasNext()) {
              QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
              if (simpleAction.property().object() == target) {
                  QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(simpleAction.property());
                  if (oldBinding) {
                      QDeclarativePropertyPrivate::setBinding(simpleAction.property(), 0);
                      oldBinding->destroy();
                  }
                  simpleAction.property().write(simpleAction.value());
                  if (simpleAction.binding())
                      QDeclarativePropertyPrivate::setBinding(simpleAction.property(), simpleAction.binding());
                  revertListIterator.remove();
              }
          }
      }
 }
removeEntryFromRevertList()
bool QDeclarativeState::removeEntryFromRevertList (QObject * target, const QString & name)
Definition at line 461 of file qdeclarativestate.cpp.
Referenced by QDeclarativePropertyChanges::removeProperty().
 {
     Q_D(QDeclarativeState);
     if (isStateActive()) {
         QMutableListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
         while (revertListIterator.hasNext()) {
             QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
             if (simpleAction.property().object() == target && simpleAction.property().name() == name) {
                 QDeclarativeAbstractBinding *oldBinding = QDeclarativePropertyPrivate::binding(simpleAction.property());
                 if (oldBinding) {
                     QDeclarativePropertyPrivate::setBinding(simpleAction.property(), 0);
                     oldBinding->destroy();
                 }
                 simpleAction.property().write(simpleAction.value());
                 if (simpleAction.binding())
                     QDeclarativePropertyPrivate::setBinding(simpleAction.property(), simpleAction.binding());
                 revertListIterator.remove();
                 return true;
             }
         }
     }
     return false;
 }
setExtends()
void QDeclarativeState::setExtends (const QString &)
Definition at line 286 of file qdeclarativestate.cpp.
 {
     Q_D(QDeclarativeState);
     d->extends = extends;
 }
setName()
void QDeclarativeState::setName (const QString & n)
Definition at line 208 of file qdeclarativestate.cpp.
Referenced by QDeclarativeStateGroup::componentComplete().
 {
     Q_D(QDeclarativeState);
     d->name = n;
     d->named = true;
 }
setStateGroup()
void QDeclarativeState::setStateGroup (QDeclarativeStateGroup * group)
Definition at line 382 of file qdeclarativestate.cpp.
Referenced by QDeclarativeStateGroupPrivate::append_state().
 {
     Q_D(QDeclarativeState);
     d->group = group;
 }
setWhen()
void QDeclarativeState::setWhen (QDeclarativeBinding * when)
Definition at line 260 of file qdeclarativestate.cpp.
 {
     Q_D(QDeclarativeState);
     d->when = when;
     if (d->group)
         d->group->updateAutoState();
 }
stateGroup()
QDeclarativeStateGroup * QDeclarativeState::stateGroup () const
Definition at line 376 of file qdeclarativestate.cpp.
Referenced by isStateActive().
 {
     Q_D(const QDeclarativeState);
     return d->group;
 }
valueInRevertList()
QVariant QDeclarativeState::valueInRevertList (QObject * target, const QString & name) const
Definition at line 550 of file qdeclarativestate.cpp.
 {
     Q_D(const QDeclarativeState);
     if (isStateActive()) {
         QListIterator<QDeclarativeSimpleAction> revertListIterator(d->revertList);
         while (revertListIterator.hasNext()) {
             const QDeclarativeSimpleAction &simpleAction = revertListIterator.next();
             if (simpleAction.specifiedObject() == target && simpleAction.specifiedProperty() == name)
                 return simpleAction.value();
         }
     }
     return QVariant();
 }
when()
QDeclarativeBinding* QDeclarativeState::when () const
Referenced by isWhenKnown(), and setWhen().
Properties
changes
QDeclarativeListProperty< QDeclarativeStateOperation > QDeclarativeState::changes private
Definition at line 150 of file qdeclarativestate_p.h.
extend
QString QDeclarativeState::extend private
Definition at line 149 of file qdeclarativestate_p.h.
name
QString QDeclarativeState::name private
Definition at line 147 of file qdeclarativestate_p.h.
Referenced by QDeclarativeStateGroup::findState(), QDeclarativeStatePrivate::generateActionList(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), and QDeclarativeStateGroupPrivate::updateAutoState().
when
QDeclarativeBinding * QDeclarativeState::when private
Definition at line 148 of file qdeclarativestate_p.h.
Referenced by QDeclarativeStateGroupPrivate::updateAutoState().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestate_p.h
/src/declarative/util/qdeclarativestate.cpp