Qt 4.8: QWSWindow Class Reference
QWSWindow Class Reference
The QWSWindow class encapsulates a top-level window in Qt for Embedded Linux.
#include <qwindowsystem_qws.h>
Public Types
enum State {
NoState, Hidden, Showing, Visible,
Hiding, Raising, Lowering, Moving,
ChangingGeometry, Destroyed
}
This enum describes the state of a window.
Public Functions
QRegion allocatedRegion () const
Returns the region that the window is allowed to draw onto, including any window decorations but excluding regions covered by other windows.
const QString & caption () const
Returns the window's caption.
QWSClient * client () const
Returns a reference to the QWSClient object that owns this window.
QRegion dirtyOnScreen () const
Returns the region that has been repainted since the previous QScreen::exposeRegion(), and needs to be copied to the screen.
void hide ()
Hides the window.
bool isFullyObscured () const
Returns true if the window is completely obsured by another window or by the bounds of the screen; otherwise returns false.
bool isOpaque () const
Returns true if the window is opaque, i.
bool isPartiallyObscured () const
Returns true if the window is partially obsured by another window or by the bounds of the screen; otherwise returns false.
bool isVisible () const
Returns true if the window is visible; otherwise returns false.
void lower ()
Lowers the window below other windows.
const QString & name () const
Returns the window's name, which is taken from the QWidget::objectName() at the time of QWidget::show() .
uint opacity () const
Returns the window's alpha channel value.
QRegion paintedRegion () const
Returns the region that the window is known to have drawn into.
QWSWindow (int i, QWSClient *client)
void raise ()
Raises the window above all other windows except "Stay on top" windows.
const QRegion & requestedRegion () const
Returns the region that the window has requested to draw onto, including any window decorations.
void setActiveWindow ()
Make this the active window (i.
void show ()
Shows the window.
State state () const
Returns the current state of the window.
Qt::WindowFlags windowFlags () const
Returns the window flags of the window.
QWSWindowSurface * windowSurface () const
int winId () const
Returns the window's ID.
~QWSWindow ()
Destructor.
Private Functions
void createSurface (const QString &key, const QByteArray &data)
void focus (bool get)
int focusPriority () const
bool forClient (const QWSClient *cl) const
bool hidden () const
void operation (QWSWindowOperationEvent::Operation o)
void setAllocatedRegion (const QRegion &region)
void setCaption (const QString &c)
Sets the window's caption to c.
void setName (const QString &n)
void shuttingDown ()
void startEmbed (QWSWindow *window)
void stopEmbed (QWSWindow *window)
Properties
uint _opacity
QWSClient * c
QWSWindowPrivate * d
QRegion exposed
int id
int last_focus_time
bool modified
bool onTop
bool opaque
QRegion requested_region
QString rgnCaption
QString rgnName
QWSWindowSurface * surface
Friends
class QWSServer
class QWSServerPrivate
Detailed Description
The QWSWindow class encapsulates a top-level window in Qt for Embedded Linux.
When you run a Qt for Embedded Linux application, it either runs as a server or connects to an existing server. As applications add and remove windows, the server process maintains information about each window. In Qt for Embedded Linux, top-level windows are encapsulated as QWSWindow objects. Note that you should never construct the QWSWindow class yourself; the current top-level windows can be retrieved using the QWSServer::clientWindows() function.
With a window at hand, you can retrieve its caption, name, opacity and ID using the caption(), name(), opacity() and winId() functions, respectively. Use the client() function to retrieve a pointer to the client that owns the window.
Use the isVisible() function to find out if the window is visible. You can find out if the window is completely obscured by another window or by the bounds of the screen, using the isFullyObscured() function. The isOpaque() function returns true if the window has an alpha channel equal to 255. Finally, the requestedRegion() function returns the region of the display the window wants to draw on.
See also
QWSServer, QWSClient, {Qt for Embedded Linux Architecture}
Definition at line 94 of file qwindowsystem_qws.h.
Enumerations
State
enum QWSWindow::State
This enum describes the state of a window.
Most of the transitional states are set just before a call to QScreen::exposeRegion() and reset immediately afterwards.
NoState Initial state before the window is properly initialized.
Hidden The window is not visible.
Showing The window is being shown.
Visible The window is visible, and not in a transition.
Hiding The window is being hidden.
Raising The windoe is being raised.
Lowering The window is being raised.
Moving The window is being moved.
ChangingGeometry The window's geometry is being changed.
Destroyed The window is destroyed.
See also
state(), QScreen::exposeRegion()
Enumerator
NoState
Hidden
Showing
Visible
Hiding
Raising
Lowering
Moving
ChangingGeometry
Destroyed
Definition at line 114 of file qwindowsystem_qws.h.
 { NoState, Hidden, Showing, Visible, Hiding, Raising, Lowering, Moving, ChangingGeometry, Destroyed };
Constructors and Destructors
QWSWindow()
QWSWindow::QWSWindow (int i, QWSClient * client)
Warning
This function is not part of the public interface.
Constructs a new top-level window, associated with the client client and giving it the id i.
Definition at line 409 of file qwindowsystem_qws.cpp.
         : id(i), modified(false),
           onTop(false), c(client), last_focus_time(0), _opacity(255),
           opaque(true), d(new QWSWindowPrivate)
 {
     surface = 0;
 }
~QWSWindow()
QWSWindow::~QWSWindow ()
Destructor.
Warning
This function is not part of the public interface.
Definition at line 625 of file qwindowsystem_qws.cpp.
 {
 #ifndef QT_NO_QWS_INPUTMETHODS
     if (current_IM_composing_win == this)
         current_IM_composing_win = 0;
 #endif
 #ifndef QT_NO_QWSEMBEDWIDGET
     QWSWindow *embedder = d->embedder;
     if (embedder) {
         embedder->d->embedded.removeAll(this);
         d->embedder = 0;
     }
     while (!d->embedded.isEmpty())
         stopEmbed(d->embedded.first());
 #endif
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (surface && !surface->isBuffered()) {
         if (c && c->d_func()) // d_func() will be 0 if client is deleted
             c->removeUnbufferedSurface();
     }
 #endif
     delete surface;
     delete d;
 }
Functions
allocatedRegion()
QRegion QWSWindow::allocatedRegion () const
Returns the region that the window is allowed to draw onto, including any window decorations but excluding regions covered by other windows.
Warning
This function is not part of the public interface.
See also
paintedRegion(), requestedRegion()
Definition at line 664 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::_q_clientClosed(), QWSTtyKbPrivate::handleConsoleSwitch(), QWSServerPrivate::invokeEmbed(), QWSServerPrivate::invokeSelectCursor(), QWSServerPrivate::invokeSetOpacity(), QWSServerPrivate::lowerWindow(), QWSServerPrivate::moveWindowRegion(), QWSServerPrivate::raiseWindow(), QWSServerPrivate::request_region(), QWSServerPrivate::setWindowRegion(), QWSServerPrivate::update_regions(), and QWSServer::windowAt().
 {
     return d->allocatedRegion;
 }
caption()
const QString & QWSWindow::caption () const inline
Returns the window's caption.
See also
name(), winId()
Definition at line 105 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::invokeRegionName().
 { return rgnCaption; }
client()
QWSClient * QWSWindow::client () const inline
Returns a reference to the QWSClient object that owns this window.
See also
requestedRegion()
Definition at line 106 of file qwindowsystem_qws.h.
Referenced by QWSServer::enablePainting(), QScreen::exposeRegion(), QWSServerPrivate::invokeConvertSelection(), QWSServerPrivate::invokeEmbed(), QWSServerPrivate::invokeGrabKeyboard(), QWSServerPrivate::invokeSetSelectionOwner(), QWSServerPrivate::request_region(), QWSServer::sendIMEvent(), QWSServer::sendIMQuery(), QWSServerPrivate::sendKeyEventUnfiltered(), QWSServerPrivate::sendMouseEventUnfiltered(), QWSServerPrivate::setFocus(), stopEmbed(), QWSServerPrivate::update_regions(), QWSServerPrivate::updateClientCursorPos(), and QWSServer::windowList().
 { return c; }
createSurface()
void QWSWindow::createSurface (const QString & key, const QByteArray & data) private
Definition at line 473 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::request_region().
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (surface && !surface->isBuffered())
         c->removeUnbufferedSurface();
 #endif
     delete surface;
     surface = qt_screen->createSurface(key);
     surface->setPermanentState(data);
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (!surface->isBuffered())
         c->addUnbufferedSurface();
 #endif
 }
dirtyOnScreen()
QRegion QWSWindow::dirtyOnScreen () const
Returns the region that has been repainted since the previous QScreen::exposeRegion(), and needs to be copied to the screen.
Since
4.3
Definition at line 468 of file qwindowsystem_qws.cpp.
 {
     return d->dirtyOnScreen;
 }
focus()
void QWSWindow::focus (bool get) private
Definition at line 596 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::setFocus().
 {
     if (get)
         last_focus_time = global_focus_time_counter++;
     if (c) {
         QWSFocusEvent event;
         event.simpleData.window = id;
         event.simpleData.get_focus = get;
         c->sendEvent(&event);
     }
 }
focusPriority()
int QWSWindow::focusPriority () const inline private
Definition at line 138 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::setFocus().
 { return last_focus_time; }
forClient()
bool QWSWindow::forClient (const QWSClient * cl) const inline private
Definition at line 132 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QWSServerPrivate::invokeRegion(), QWSServerPrivate::invokeRegionDestroy(), QWSServerPrivate::invokeRegionMove(), and QWSServerPrivate::invokeSetFocus().
 { return cl==c; }
hidden()
bool QWSWindow::hidden () const inline private
Definition at line 131 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::setFocus().
 { return requested_region.isEmpty(); }
hide()
void QWSWindow::hide ()
Hides the window.
Warning
This function is not part of the public interface.
Definition at line 548 of file qwindowsystem_qws.cpp.
Referenced by hide().
 {
     operation(QWSWindowOperationEvent::Hide);
 #ifndef QT_NO_QWSEMBEDWIDGET
     const int n = d->embedded.size();
     for (int i = 0; i < n; ++i)
         d->embedded.at(i)->hide();
 #endif
 }
isFullyObscured()
bool QWSWindow::isFullyObscured () const inline
Returns true if the window is completely obsured by another window or by the bounds of the screen; otherwise returns false.
See also
isVisible()
Definition at line 112 of file qwindowsystem_qws.h.
 { return allocatedRegion().isEmpty(); }
isOpaque()
bool QWSWindow::isOpaque () const inline
Returns true if the window is opaque, i.
e., if its alpha channel equals 255; otherwise returns false.
See also
opacity()
Definition at line 125 of file qwindowsystem_qws.h.
Referenced by QScreen::compose(), QDirectFBScreen::exposeRegion(), QWSServerPrivate::invokeSetOpacity(), QWSServerPrivate::lowerWindow(), QWSServerPrivate::raiseWindow(), and QWSServerPrivate::update_regions().
 {return opaque && _opacity == 255;}
isPartiallyObscured()
bool QWSWindow::isPartiallyObscured () const inline
Returns true if the window is partially obsured by another window or by the bounds of the screen; otherwise returns false.
Warning
This function is not part of the public interface.
Definition at line 111 of file qwindowsystem_qws.h.
 { return requested_region != allocatedRegion(); }
isVisible()
bool QWSWindow::isVisible () const inline
Returns true if the window is visible; otherwise returns false.
See also
isFullyObscured()
Definition at line 110 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::request_region().
 { return !requested_region.isEmpty(); }
lower()
void QWSWindow::lower ()
Lowers the window below other windows.
Warning
This function is not part of the public interface.
Definition at line 514 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeSetAltitude(), and lower().
 {
     qwsServerPrivate->lowerWindow(this);
 #ifndef QT_NO_QWSEMBEDWIDGET
     const int n = d->embedded.size();
     for (int i = 0; i < n; ++i)
         d->embedded.at(i)->lower();
 #endif
 }
name()
const QString & QWSWindow::name () const inline
Returns the window's name, which is taken from the QWidget::objectName() at the time of QWidget::show() .
See also
caption(), winId()
Definition at line 104 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::invokeRegionName().
 { return rgnName; }
opacity()
uint QWSWindow::opacity () const inline
Returns the window's alpha channel value.
See also
isOpaque()
Definition at line 126 of file qwindowsystem_qws.h.
Referenced by QScreen::compose(), and QDirectFBScreen::exposeRegion().
 { return _opacity; }
operation()
void QWSWindow::operation (QWSWindowOperationEvent::Operation o) private
Definition at line 608 of file qwindowsystem_qws.cpp.
Referenced by hide(), and show().
 {
     if (!c)
         return;
     QWSWindowOperationEvent event;
     event.simpleData.window = id;
     event.simpleData.op = o;
     c->sendEvent(&event);
 }
paintedRegion()
QRegion QWSWindow::paintedRegion () const
Returns the region that the window is known to have drawn into.
Warning
This function is not part of the public interface.
See also
allocatedRegion(), requestedRegion()
Definition at line 691 of file qwindowsystem_qws.cpp.
Referenced by QScreen::blit(), and QScreen::compose().
 {
     return (d->painted ? d->allocatedRegion : QRegion());
 }
raise()
void QWSWindow::raise ()
Raises the window above all other windows except "Stay on top" windows.
Warning
This function is not part of the public interface.
Definition at line 497 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeSetAltitude(), and raise().
 {
     qwsServerPrivate->raiseWindow(this);
 #ifndef QT_NO_QWSEMBEDWIDGET
     const int n = d->embedded.size();
     for (int i = 0; i < n; ++i)
         d->embedded.at(i)->raise();
 #endif
 }
requestedRegion()
QRegion QWSWindow::requestedRegion () const inline
Returns the region that the window has requested to draw onto, including any window decorations.
See also
client()
Definition at line 107 of file qwindowsystem_qws.h.
Referenced by QScreen::blit(), and QScreen::compose().
 { return requested_region; }
setActiveWindow()
void QWSWindow::setActiveWindow ()
Make this the active window (i.
Warning
This function is not part of the public interface. e., sets the keyboard focus to this window).
Definition at line 566 of file qwindowsystem_qws.cpp.
Referenced by setActiveWindow().
 {
     qwsServerPrivate->setFocus(this, true);
 #ifndef QT_NO_QWSEMBEDWIDGET
     const int n = d->embedded.size();
     for (int i = 0; i < n; ++i)
         d->embedded.at(i)->setActiveWindow();
 #endif
 }
setAllocatedRegion()
void QWSWindow::setAllocatedRegion (const QRegion & region) inline private
Definition at line 696 of file qwindowsystem_qws.cpp.
Referenced by QWSServer::enablePainting(), QWSServerPrivate::moveWindowRegion(), and QWSServerPrivate::update_regions().
 {
     d->allocatedRegion = region;
 }
setCaption()
void QWSWindow::setCaption (const QString & c) private
Sets the window's caption to c.
Warning
This function is not part of the public interface.
Definition at line 588 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeRegionName().
 {
     rgnCaption = c;
 }
setName()
void QWSWindow::setName (const QString & n) private
Definition at line 576 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeRegionName().
 {
     rgnName = n;
 }
show()
void QWSWindow::show ()
Shows the window.
Warning
This function is not part of the public interface.
Definition at line 531 of file qwindowsystem_qws.cpp.
Referenced by show().
 {
     operation(QWSWindowOperationEvent::Show);
 #ifndef QT_NO_QWSEMBEDWIDGET
     const int n = d->embedded.size();
     for (int i = 0; i < n; ++i)
         d->embedded.at(i)->show();
 #endif
 }
shuttingDown()
void QWSWindow::shuttingDown () inline private
Definition at line 140 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), and QWSServerPrivate::handleWindowClose().
 { last_focus_time=0; }
startEmbed()
void QWSWindow::startEmbed (QWSWindow * window) inline private
Definition at line 702 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeEmbed().
 {
     d->embedded.append(w);
     w->d->embedder = this;
 }
state()
QWSWindow::State QWSWindow::state () const
Returns the current state of the window.
Since
4.3
Definition at line 447 of file qwindowsystem_qws.cpp.
Referenced by QScreen::exposeRegion().
 {
     return d->state;
 }
stopEmbed()
void QWSWindow::stopEmbed (QWSWindow * window) inline private
Definition at line 708 of file qwindowsystem_qws.cpp.
Referenced by QWSServerPrivate::invokeEmbed(), and ~QWSWindow().
 {
     w->d->embedder = 0;
     w->client()->sendEmbedEvent(w->winId(), QWSEmbedEvent::Region, QRegion());
     d->embedded.removeAll(w);
 }
windowFlags()
Qt::WindowFlags QWSWindow::windowFlags () const
Returns the window flags of the window.
This value is only available after the first paint event.
Since
4.3
Definition at line 458 of file qwindowsystem_qws.cpp.
 {
     return d->windowFlags;
 }
windowSurface()
QWSWindowSurface * QWSWindow::windowSurface () const inline
Warning
This function is not part of the public interface.
Definition at line 128 of file qwindowsystem_qws.h.
Referenced by QScreen::blit(), QScreen::compose(), QDirectFBScreen::exposeRegion(), QWSTtyKbPrivate::handleConsoleSwitch(), QWSServerPrivate::moveWindowRegion(), QDirectFBScreenPrivate::onWindowEvent(), QWSServerPrivate::request_region(), and QWSServerPrivate::update_regions().
 { return surface; }
winId()
int QWSWindow::winId () const inline
Returns the window's ID.
See also
name(), caption()
Definition at line 103 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QWSServer::enablePainting(), QWSServerPrivate::findWindow(), QWSServerPrivate::invokeEmbed(), QWSServerPrivate::invokeRegionDestroy(), QWSServer::sendIMEvent(), QWSServer::sendIMQuery(), QWSServerPrivate::sendKeyEventUnfiltered(), QWSServerPrivate::setFocus(), stopEmbed(), QWSServerPrivate::update_regions(), QWSDisplay::windowAt(), and QWSServer::windowList().
 { return id; }
Friends and Related Functions
QWSServer
friend class QWSServer friend
Definition at line 96 of file qwindowsystem_qws.h.
QWSServerPrivate
friend class QWSServerPrivate friend
Definition at line 97 of file qwindowsystem_qws.h.
Properties
_opacity
uint QWSWindow::_opacity private
Definition at line 166 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::invokeSetOpacity().
c
QWSClient* QWSWindow::c private
Definition at line 161 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), createSurface(), focus(), operation(), setCaption(), and ~QWSWindow().
d
QWSWindowPrivate* QWSWindow::d private
Definition at line 168 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), allocatedRegion(), dirtyOnScreen(), hide(), lower(), QWSServerPrivate::lowerWindow(), QWSServerPrivate::moveWindowRegion(), paintedRegion(), raise(), QWSServerPrivate::raiseWindow(), QWSServerPrivate::repaint_region(), QWSServerPrivate::request_region(), setActiveWindow(), setAllocatedRegion(), show(), startEmbed(), state(), stopEmbed(), QWSServerPrivate::update_regions(), windowFlags(), and ~QWSWindow().
exposed
QRegion QWSWindow::exposed private
Definition at line 163 of file qwindowsystem_qws.h.
id
int QWSWindow::id private
Definition at line 156 of file qwindowsystem_qws.h.
Referenced by focus(), operation(), and QWSServerPrivate::sendMouseEventUnfiltered().
last_focus_time
int QWSWindow::last_focus_time private
Definition at line 164 of file qwindowsystem_qws.h.
Referenced by focus().
modified
bool QWSWindow::modified private
Definition at line 159 of file qwindowsystem_qws.h.
onTop
bool QWSWindow::onTop private
Definition at line 160 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::invokeSetAltitude(), QWSServerPrivate::newWindow(), and QWSServerPrivate::raiseWindow().
opaque
bool QWSWindow::opaque private
Definition at line 167 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::repaint_region(), and QWSServerPrivate::request_region().
requested_region
QRegion QWSWindow::requested_region private
Definition at line 162 of file qwindowsystem_qws.h.
Referenced by QWSServerPrivate::moveWindowRegion(), QWSServerPrivate::request_region(), QWSServerPrivate::reserve_region(), QWSServerPrivate::setWindowRegion(), and QWSServerPrivate::update_regions().
rgnCaption
QString QWSWindow::rgnCaption private
Definition at line 158 of file qwindowsystem_qws.h.
Referenced by setCaption().
rgnName
QString QWSWindow::rgnName private
Definition at line 157 of file qwindowsystem_qws.h.
Referenced by setName().
surface
QWSWindowSurface* QWSWindow::surface private
Definition at line 165 of file qwindowsystem_qws.h.
Referenced by createSurface(), QWSWindow(), and ~QWSWindow().
The documentation for this class was generated from the following files:
/src/gui/embedded/qwindowsystem_qws.h
/src/gui/embedded/qwindowsystem_qws.cpp