Qt 4.8: QScriptObject Class Reference
QScriptObject Class Reference
#include <qscriptobject_p.h>
Classes
struct Data
Public Functions
virtual const JSC::ClassInfo * classInfo () const
virtual bool compareToObject (JSC::ExecState *, JSC::JSObject *)
JSC::JSValue data () const
QScriptObjectDelegate * delegate () const
virtual bool deleteProperty (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual JSC::CallType getCallData (JSC::CallData &)
virtual JSC::ConstructType getConstructData (JSC::ConstructData &)
virtual bool getOwnPropertyDescriptor (JSC::ExecState *, const JSC::Identifier &, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual bool hasInstance (JSC::ExecState *, JSC::JSValue value, JSC::JSValue proto)
virtual void markChildren (JSC::MarkStack &markStack)
virtual void put (JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue, JSC::PutPropertySlot &)
QScriptObject (WTF::PassRefPtr< JSC::Structure > sid)
void setData (JSC::JSValue data)
void setDelegate (QScriptObjectDelegate *delegate)
virtual ~QScriptObject ()
Static Public Functions
static WTF::PassRefPtr< JSC::Structure > createStructure (JSC::JSValue prototype)
Static Public Variables
static const JSC::ClassInfo info = { "Object", 0, 0, 0 }
Protected Variables
Data * d
Static Protected Variables
static const unsigned StructureFlags = JSC::ImplementsHasInstance | JSC::OverridesHasInstance | JSC::OverridesGetOwnPropertySlot | JSC::OverridesMarkChildren | JSC::OverridesGetPropertyNames | JSObject::StructureFlags
Detailed Description
Definition at line 46 of file qscriptobject_p.h.
Constructors and Destructors
QScriptObject()
QScriptObject::QScriptObject (WTF::PassRefPtr< JSC::Structure > sid) explicit
Definition at line 45 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
     : JSC::JSObject(sid), d(0)
 {
 }
~QScriptObject()
QScriptObject::~QScriptObject () virtual
Definition at line 50 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     delete d;
 }
Functions
classInfo()
virtual const JSC::ClassInfo* QScriptObject::classInfo () const inline virtual
Definition at line 79 of file qscriptobject_p.h.
 { return &info; }
compareToObject()
bool QScriptObject::compareToObject (JSC::ExecState * exec, JSC::JSObject * other) virtual
Definition at line 101 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate) {
         return JSC::JSObject::compareToObject(exec, other);
     }
     return d->delegate->compareToObject(this, exec, other);
 }
createStructure()
static WTF::PassRefPtr<JSC::Structure> QScriptObject::createStructure (JSC::JSValue prototype) inline static
Definition at line 82 of file qscriptobject_p.h.
Referenced by QScriptEnginePrivate::QScriptEnginePrivate().
     {
         return JSC::Structure::create(prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags));
     }
data()
JSC::JSValue QScriptObject::data () const inline
Definition at line 144 of file qscriptobject_p.h.
Referenced by QScriptValue::data().
 {
     if (!d)
         return JSC::JSValue();
     return d->data;
 }
delegate()
QScriptObjectDelegate * QScriptObject::delegate () const inline
Definition at line 158 of file qscriptobject_p.h.
Referenced by QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), QScript::DeclarativeObjectDelegate::compareToObject(), QScriptEnginePrivate::declarativeClass(), QScriptEnginePrivate::declarativeObject(), QScriptEngine::newQObject(), QScript::QtFunction::qobject(), QScript::qobjectProtoFuncFindChild(), QScript::qobjectProtoFuncFindChildren(), QScript::qobjectProtoFuncToString(), QScriptValue::scriptClass(), and QScriptValue::setScriptClass().
 {
     if (!d)
         return 0;
     return d->delegate;
 }
deleteProperty()
bool QScriptObject::deleteProperty (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 83 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate)
         return JSC::JSObject::deleteProperty(exec, propertyName);
     return d->delegate->deleteProperty(this, exec, propertyName);
 }
getCallData()
JSC::CallType QScriptObject::getCallData (JSC::CallData & data) virtual
Definition at line 125 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate)
         return JSC::JSObject::getCallData(data);
     return d->delegate->getCallData(this, data);
 }
getConstructData()
JSC::ConstructType QScriptObject::getConstructData (JSC::ConstructData & data) virtual
Definition at line 132 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate)
         return JSC::JSObject::getConstructData(data);
     return d->delegate->getConstructData(this, data);
 }
getOwnPropertyDescriptor()
bool QScriptObject::getOwnPropertyDescriptor (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Definition at line 64 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate)
         return JSC::JSObject::getOwnPropertyDescriptor(exec, propertyName, descriptor);
     return d->delegate->getOwnPropertyDescriptor(this, exec, propertyName, descriptor);
 }
getOwnPropertyNames()
void QScriptObject::getOwnPropertyNames (JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Definition at line 91 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate) {
         JSC::JSObject::getOwnPropertyNames(exec, propertyNames, mode);
         return;
     }
     d->delegate->getOwnPropertyNames(this, exec, propertyNames, mode);
 }
getOwnPropertySlot()
bool QScriptObject::getOwnPropertySlot (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Definition at line 55 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate)
         return JSC::JSObject::getOwnPropertySlot(exec, propertyName, slot);
     return d->delegate->getOwnPropertySlot(this, exec, propertyName, slot);
 }
hasInstance()
bool QScriptObject::hasInstance (JSC::ExecState * exec, JSC::JSValue value, JSC::JSValue proto) virtual
Definition at line 139 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate)
         return JSC::JSObject::hasInstance(exec, value, proto);
     return d->delegate->hasInstance(this, exec, value, proto);
 }
markChildren()
void QScriptObject::markChildren (JSC::MarkStack & markStack) virtual
Definition at line 109 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d)
         d = new Data();
     if (d->isMarking)
         return;
     QBoolBlocker markBlocker(d->isMarking, true);
     if (d && d->data)
         markStack.append(d->data);
     if (!d || !d->delegate) {
         JSC::JSObject::markChildren(markStack);
         return;
     }
     d->delegate->markChildren(this, markStack);
 }
put()
void QScriptObject::put (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Definition at line 73 of file qscriptobject.cpp.
Referenced by QScriptObject::Data::Data().
 {
     if (!d || !d->delegate) {
         JSC::JSObject::put(exec, propertyName, value, slot);
         return;
     }
     d->delegate->put(this, exec, propertyName, value, slot);
 }
setData()
void QScriptObject::setData (JSC::JSValue data) inline
Definition at line 151 of file qscriptobject_p.h.
Referenced by createStructure(), and QScriptValue::setData().
 {
     if (!d)
         d = new Data();
     d->data = data;
 }
setDelegate()
void QScriptObject::setDelegate (QScriptObjectDelegate * delegate) inline
Definition at line 165 of file qscriptobject_p.h.
Referenced by createStructure(), QScriptDeclarativeClass::newObject(), QScriptEngine::newObject(), QScriptDeclarativeClass::newObjectValue(), QScriptEngine::newQObject(), QScriptEnginePrivate::newQObject(), QScriptEnginePrivate::newVariant(), QScript::QObjectPrototype::QObjectPrototype(), QScript::QVariantPrototype::QVariantPrototype(), and QScriptValue::setScriptClass().
 {
     if (!d)
         d = new Data();
     else
         delete d->delegate;
     d->delegate = delegate;
 }
Properties
d
Data* QScriptObject::d protected
Definition at line 96 of file qscriptobject_p.h.
Referenced by compareToObject(), data(), delegate(), deleteProperty(), getCallData(), getConstructData(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), hasInstance(), markChildren(), put(), setData(), setDelegate(), and ~QScriptObject().
info
const JSC::ClassInfo QScriptObject::info = { "Object", 0, 0, 0 } static
Definition at line 80 of file qscriptobject_p.h.
Referenced by QScript::ClassObjectDelegate::call(), QScript::DeclarativeObjectDelegate::call(), classInfo(), QScript::QObjectDelegate::compareToObject(), QScript::DeclarativeObjectDelegate::compareToObject(), QScript::ClassObjectDelegate::construct(), QScriptValue::data(), QScriptEnginePrivate::declarativeClass(), QScriptEnginePrivate::declarativeObject(), QScript::QObjectConnectionManager::execute(), QScript::QtFunction::execute(), QScript::QMetaObjectWrapperObject::execute(), QScriptEnginePrivate::isQObject(), QScriptEnginePrivate::isVariant(), QScript::QObjectConnection::mark(), QScriptEngine::newQObject(), QScriptEnginePrivate::newVariant(), QScript::qobjectProtoFuncFindChild(), QScript::qobjectProtoFuncFindChildren(), QScript::qobjectProtoFuncToString(), QScriptValue::scriptClass(), QScriptValue::setData(), QScriptValue::setScriptClass(), QScriptEnginePrivate::setVariantValue(), QScriptEnginePrivate::toQObject(), QScript::variantProtoFuncToString(), QScript::variantProtoFuncValueOf(), QScriptEnginePrivate::variantValue(), and QScript::QtFunction::wrapperObject().
StructureFlags
const unsigned QScriptObject::StructureFlags = JSC::ImplementsHasInstance | JSC::OverridesHasInstance | JSC::OverridesGetOwnPropertySlot | JSC::OverridesMarkChildren | JSC::OverridesGetPropertyNames | JSObject::StructureFlags static protected
Definition at line 94 of file qscriptobject_p.h.
Referenced by createStructure().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptobject_p.h
/src/script/bridge/qscriptobject.cpp