Qt 4.8: QPlatformCursorImage Class Reference
QPlatformCursorImage Class Reference
The QPlatformCursorImage class provides a set of graphics intended to be used as cursors.
#include <qplatformcursor_qpa.h>
Public Functions
QPoint hotspot ()
Return the cursor's hotspot.
QImage * image ()
Return the cursor graphic as a pointer to a QImage.
QPlatformCursorImage (const uchar *data, const uchar *mask, int width, int height, int hotX, int hotY)
Sets the cursor image to the graphic represented by the combination of data and mask, with dimensions given by width and height and a hotspot at the point specified by (hotX, hotY).
void set (const uchar *data, const uchar *mask, int width, int height, int hotX, int hotY)
Sets the cursor image to the graphic represented by the combination of data and mask, with dimensions given by width and height and a hotspot at the point specified by (hx, hy).
void set (const QImage &image, int hx, int hy)
Sets the cursor image to the given image, with the hotspot at the point specified by (hx, hy).
void set (Qt::CursorShape)
Calling this method sets the cursor image to the specified shape.
Static Private Functions
static void createSystemCursor (int id)
Properties
QImage cursorImage
QPoint hot
Detailed Description
The QPlatformCursorImage class provides a set of graphics intended to be used as cursors.
Since
4.8
See also
QPlatformCursor
Definition at line 59 of file qplatformcursor_qpa.h.
Constructors and Destructors
QPlatformCursorImage()
QPlatformCursorImage::QPlatformCursorImage (const uchar * data, const uchar * mask, int width, int height, int hotX, int hotY) inline
Sets the cursor image to the graphic represented by the combination of data and mask, with dimensions given by width and height and a hotspot at the point specified by (hotX, hotY).
See also
set()
Definition at line 61 of file qplatformcursor_qpa.h.
     { set(data, mask, width, height, hotX, hotY); }
Functions
createSystemCursor()
void QPlatformCursorImage::createSystemCursor (int id) static private
Definition at line 423 of file qplatformcursor_qpa.cpp.
 {
     if (!systemCursorTableInit) {
         for (int i = 0; i <= Qt::LastCursor; i++)
             systemCursorTable[i] = 0;
         systemCursorTableInit = true;
     }
     switch (id) {
         // 16x16 cursors
         case Qt::ArrowCursor:
             systemCursorTable[Qt::ArrowCursor] =
                 new QPlatformCursorImage(cur_arrow_bits, mcur_arrow_bits, 16, 16, 0, 0);
             break;
         case Qt::UpArrowCursor:
             systemCursorTable[Qt::UpArrowCursor] =
                 new QPlatformCursorImage(cur_up_arrow_bits, mcur_up_arrow_bits, 16, 16, 7, 0);
             break;
         case Qt::CrossCursor:
             systemCursorTable[Qt::CrossCursor] =
                 new QPlatformCursorImage(cur_cross_bits, mcur_cross_bits, 16, 16, 7, 7);
             break;
         case Qt::IBeamCursor:
             systemCursorTable[Qt::IBeamCursor] =
                 new QPlatformCursorImage(cur_ibeam_bits, mcur_ibeam_bits, 16, 16, 7, 7);
             break;
         case Qt::SizeVerCursor:
             systemCursorTable[Qt::SizeVerCursor] =
                 new QPlatformCursorImage(cur_ver_bits, mcur_ver_bits, 16, 16, 7, 7);
             break;
         case Qt::SizeHorCursor:
             systemCursorTable[Qt::SizeHorCursor] =
                 new QPlatformCursorImage(cur_hor_bits, mcur_hor_bits, 16, 16, 7, 7);
             break;
         case Qt::SizeBDiagCursor:
             systemCursorTable[Qt::SizeBDiagCursor] =
                 new QPlatformCursorImage(cur_bdiag_bits, mcur_bdiag_bits, 16, 16, 7, 7);
             break;
         case Qt::SizeFDiagCursor:
             systemCursorTable[Qt::SizeFDiagCursor] =
                 new QPlatformCursorImage(cur_fdiag_bits, mcur_fdiag_bits, 16, 16, 7, 7);
             break;
         case Qt::BlankCursor:
             systemCursorTable[Qt::BlankCursor] =
                 new QPlatformCursorImage(0, 0, 0, 0, 0, 0);
             break;
         // 20x20 cursors
         case Qt::ForbiddenCursor:
             systemCursorTable[Qt::ForbiddenCursor] =
                 new QPlatformCursorImage(forbidden_bits, forbiddenm_bits, 20, 20, 10, 10);
             break;
         // 32x32 cursors
         case Qt::WaitCursor:
             systemCursorTable[Qt::WaitCursor] =
                 new QPlatformCursorImage(wait_data_bits, wait_mask_bits, 32, 32, 15, 15);
             break;
         case Qt::SplitVCursor:
             systemCursorTable[Qt::SplitVCursor] =
                 new QPlatformCursorImage(vsplit_bits, vsplitm_bits, 32, 32, 15, 15);
             break;
         case Qt::SplitHCursor:
             systemCursorTable[Qt::SplitHCursor] =
                 new QPlatformCursorImage(hsplit_bits, hsplitm_bits, 32, 32, 15, 15);
             break;
         case Qt::SizeAllCursor:
             systemCursorTable[Qt::SizeAllCursor] =
                 new QPlatformCursorImage(size_all_data_bits, size_all_mask_bits, 32, 32, 15, 15);
             break;
         case Qt::PointingHandCursor:
             systemCursorTable[Qt::PointingHandCursor] =
                 new QPlatformCursorImage(phand_bits, phandm_bits, 32, 32, 0, 0);
             break;
         case Qt::WhatsThisCursor:
             systemCursorTable[Qt::WhatsThisCursor] =
                 new QPlatformCursorImage(whatsthis_bits, whatsthism_bits, 32, 32, 0, 0);
             break;
         case Qt::BusyCursor:
             systemCursorTable[Qt::BusyCursor] =
                 new QPlatformCursorImage(busy_bits, busym_bits, 32, 32, 0, 0);
             break;
         case Qt::OpenHandCursor:
             systemCursorTable[Qt::OpenHandCursor] =
                 new QPlatformCursorImage(openhand_bits, openhandm_bits, 16, 16, 8, 8);
             break;
         case Qt::ClosedHandCursor:
             systemCursorTable[Qt::ClosedHandCursor] =
                 new QPlatformCursorImage(closedhand_bits, closedhandm_bits, 16, 16, 8, 8);
             break;
         default:
             qWarning("Unknown system cursor %d", id);
     }
 }
hotspot()
QPoint QPlatformCursorImage::hotspot () inline
Return the cursor's hotspot.
Definition at line 64 of file qplatformcursor_qpa.h.
Referenced by QDirectFBCursor::changeCursor(), QPlatformSoftwareCursor::getCurrentRect(), and QVNCCursor::sendClientCursor().
 { return hot; }
image()
QImage * QPlatformCursorImage::image () inline
Return the cursor graphic as a pointer to a QImage.
Definition at line 63 of file qplatformcursor_qpa.h.
Referenced by QDirectFBCursor::changeCursor(), QPlatformSoftwareCursor::drawCursor(), QPlatformSoftwareCursor::getCurrentRect(), and QVNCCursor::sendClientCursor().
 { return &cursorImage; }
set() [1/3]
void QPlatformCursorImage::set (const uchar * data, const uchar * mask, int width, int height, int hx, int hy)
Sets the cursor image to the graphic represented by the combination of data and mask, with dimensions given by width and height and a hotspot at the point specified by (hx, hy).
The image data specified by data must be supplied in the format described by QImage::Format_Indexed8.
The corresponding mask data specified by mask must be supplied in a character array containing packed 1 bit per pixel format data, with any padding bits at the end of the array. Bits of value 0 represent transparent pixels in the image data.
Definition at line 590 of file qplatformcursor_qpa.cpp.
Referenced by QDirectFBCursor::changeCursor(), and QPlatformSoftwareCursor::setCursor().
 {
     hot.setX(hx);
     hot.setY(hy);
     cursorImage = QImage(width,height, QImage::Format_Indexed8);
     if (!width || !height || !data || !mask || cursorImage.isNull())
         return;
     cursorImage.setNumColors(3);
     cursorImage.setColor(0, 0xff000000);
     cursorImage.setColor(1, 0xffffffff);
     cursorImage.setColor(2, 0x00000000);
     int bytesPerLine = (width + 7) / 8;
     int p = 0;
     int d, m;
     int x = -1, w = 0;
     uchar *cursor_data = cursorImage.bits();
     int bpl = cursorImage.bytesPerLine();
     for (int i = 0; i < height; i++)
     {
         for (int j = 0; j < bytesPerLine; j++, data++, mask++)
         {
             for (int b = 0; b < 8 && j*8+b < width; b++)
             {
                 d = *data & (1 << b);
                 m = *mask & (1 << b);
                 if (d && m) p = 0;
                 else if (!d && m) p = 1;
                 else p = 2;
                 cursor_data[j*8+b] = p;
                 // calc region
                 if (x < 0 && m)
                     x = j*8+b;
                 else if (x >= 0 && !m) {
                     x = -1;
                     w = 0;
                 }
                 if (m)
                     w++;
             }
         }
         if (x >= 0) {
             x = -1;
             w = 0;
         }
         cursor_data += bpl;
     }
 }
set() [2/3]
void QPlatformCursorImage::set (const QImage & image, int hx, int hy)
Sets the cursor image to the given image, with the hotspot at the point specified by (hx, hy).
Definition at line 568 of file qplatformcursor_qpa.cpp.
 {
     hot.setX(hx);
     hot.setY(hy);
     cursorImage = image;
 }
set() [3/3]
void QPlatformCursorImage::set (Qt::CursorShape id)
Calling this method sets the cursor image to the specified shape.
id is one of the defined Qt::CursorShape values.
If id is invalid, Qt::BitmapCursor, or unknown by the implementation, Qt::ArrowCursor is used instead.
Definition at line 545 of file qplatformcursor_qpa.cpp.
 {
     QPlatformCursorImage *cursor = 0;
     if (id >= 0 && id <= Qt::LastCursor) {
         if (!systemCursorTable[id])
             createSystemCursor(id);
         cursor = systemCursorTable[id];
     }
     if (cursor == 0) {
         if (!systemCursorTable[Qt::ArrowCursor])
             createSystemCursor(Qt::ArrowCursor);
         cursor = systemCursorTable[Qt::ArrowCursor];
     }
     cursorImage = cursor->cursorImage;
     hot = cursor->hot;
 }
Properties
cursorImage
QImage QPlatformCursorImage::cursorImage private
Definition at line 70 of file qplatformcursor_qpa.h.
Referenced by set().
hot
QPoint QPlatformCursorImage::hot private
Definition at line 71 of file qplatformcursor_qpa.h.
Referenced by set().
The documentation for this class was generated from the following files:
/src/gui/kernel/qplatformcursor_qpa.h
/src/gui/kernel/qplatformcursor_qpa.cpp