Qt 4.8: QWaitCondition Class Reference
QWaitCondition Class Reference
#include <qwaitcondition.h>
Public Functions
QWaitCondition ()
bool wait (QMutex *mutex, unsigned long time=ULONG_MAX)
bool wait (QReadWriteLock *readWriteLock, unsigned long time=ULONG_MAX)
void wakeAll ()
void wakeOne ()
~QWaitCondition ()
Properties
QWaitConditionPrivate * d
Detailed Description
Definition at line 61 of file qwaitcondition.h.
Constructors and Destructors
QWaitCondition()
QWaitCondition::QWaitCondition ()
Definition at line 113 of file qwaitcondition_unix.cpp.
Referenced by QWaitConditionPrivate::post().
 {
     d = new QWaitConditionPrivate;
     report_error(pthread_mutex_init(&d->mutex, NULL), "QWaitCondition", "mutex init");
     report_error(pthread_cond_init(&d->cond, NULL), "QWaitCondition", "cv init");
     d->waiters = d->wakeups = 0;
 }
~QWaitCondition()
QWaitCondition::~QWaitCondition ()
Definition at line 122 of file qwaitcondition_unix.cpp.
Referenced by QWaitConditionPrivate::post().
 {
     report_error(pthread_cond_destroy(&d->cond), "QWaitCondition", "cv destroy");
     report_error(pthread_mutex_destroy(&d->mutex), "QWaitCondition", "mutex destroy");
     delete d;
 }
Functions
wait() [1/2]
bool QWaitCondition::wait (QMutex * mutex, unsigned long time = ULONG_MAX)
Definition at line 145 of file qwaitcondition_unix.cpp.
Referenced by QFutureInterfaceBasePrivate::internal_waitForNextResult(), QReadWriteLock::lockForRead(), QReadWriteLock::lockForWrite(), QWaitConditionPrivate::post(), QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine(), QThreadPoolThread::run(), QWindowsPipeWriter::run(), QFileInfoGatherer::run(), QDnotifySignalThread::startNotify(), QFSEventsFileSystemWatcherEngine::stop(), QDeclarativeListModelWorkerAgent::sync(), QReadWriteLock::tryLockForRead(), QReadWriteLock::tryLockForWrite(), QThreadPoolPrivate::waitForDone(), QFutureInterfaceBase::waitForFinished(), QDBusConnectionPrivate::waitForFinished(), QFutureInterfaceBase::waitForResult(), QFutureInterfaceBase::waitForResume(), QWindowsPipeWriter::waitForWrite(), and QFSEventsFileSystemWatcherEngine::warmUpFSEvents().
 {
     if (! mutex)
         return false;
     if (mutex->d->recursive) {
         qWarning("QWaitCondition: cannot wait on recursive mutexes");
         return false;
     }
     report_error(pthread_mutex_lock(&d->mutex), "QWaitCondition::wait()", "mutex lock");
     ++d->waiters;
     mutex->unlock();
     bool returnValue = d->wait(time);
     mutex->lock();
     return returnValue;
 }
wait() [2/2]
bool QWaitCondition::wait (QReadWriteLock * readWriteLock, unsigned long time = ULONG_MAX)
Definition at line 165 of file qwaitcondition_unix.cpp.
 {
     if (!readWriteLock || readWriteLock->d->accessCount == 0)
         return false;
     if (readWriteLock->d->accessCount < -1) {
         qWarning("QWaitCondition: cannot wait on QReadWriteLocks with recursive lockForWrite()");
         return false;
     }
     report_error(pthread_mutex_lock(&d->mutex), "QWaitCondition::wait()", "mutex lock");
     ++d->waiters;
     int previousAccessCount = readWriteLock->d->accessCount;
     readWriteLock->unlock();
     bool returnValue = d->wait(time);
     if (previousAccessCount < 0)
         readWriteLock->lockForWrite();
     else
         readWriteLock->lockForRead();
     return returnValue;
 }
wakeAll()
void QWaitCondition::wakeAll ()
Definition at line 137 of file qwaitcondition_unix.cpp.
Referenced by QFutureInterfaceBase::cancel(), QDnotifySignalThread::event(), QDeclarativeListModelWorkerAgent::event(), QFileInfoGatherer::fetchExtendedInformation(), QThreadPrivate::finish(), QFutureInterfaceBasePrivate::internal_setThrottled(), QWaitConditionPrivate::post(), QThreadPoolThread::registerThreadInactive(), QFutureInterfaceBase::reportException(), QFutureInterfaceBase::reportFinished(), QFutureInterfaceBase::reportResultsReady(), QThreadPoolPrivate::reset(), QFSEventsFileSystemWatcherEngine::run(), QFutureInterfaceBase::setPaused(), QFutureInterfaceBase::setThrottled(), QFutureInterfaceBase::togglePaused(), QReadWriteLock::unlock(), QFSEventsFileSystemWatcherEngine::updateFiles(), and QDBusConnectionPrivate::waitForFinished().
 {
     report_error(pthread_mutex_lock(&d->mutex), "QWaitCondition::wakeAll()", "mutex lock");
     d->wakeups = d->waiters;
     report_error(pthread_cond_broadcast(&d->cond), "QWaitCondition::wakeAll()", "cv broadcast");
     report_error(pthread_mutex_unlock(&d->mutex), "QWaitCondition::wakeAll()", "mutex unlock");
 }
wakeOne()
void QWaitCondition::wakeOne ()
Definition at line 129 of file qwaitcondition_unix.cpp.
Referenced by QWaitConditionPrivate::post(), QWindowsPipeWriter::run(), QReadWriteLock::unlock(), QWindowsPipeWriter::write(), QFileInfoGatherer::~QFileInfoGatherer(), and QWindowsPipeWriter::~QWindowsPipeWriter().
 {
     report_error(pthread_mutex_lock(&d->mutex), "QWaitCondition::wakeOne()", "mutex lock");
     d->wakeups = qMin(d->wakeups + 1, d->waiters);
     report_error(pthread_cond_signal(&d->cond), "QWaitCondition::wakeOne()", "cv signal");
     report_error(pthread_mutex_unlock(&d->mutex), "QWaitCondition::wakeOne()", "mutex unlock");
 }
Properties
d
QWaitConditionPrivate* QWaitCondition::d private
Definition at line 76 of file qwaitcondition.h.
The documentation for this class was generated from the following files:
/src/corelib/thread/qwaitcondition.h
/src/corelib/thread/qwaitcondition_unix.cpp
/src/corelib/thread/qwaitcondition_win.cpp