Qt 4.8: QNetworkHeadersPrivate Class Reference
QNetworkHeadersPrivate Class Reference
#include <qnetworkrequest_p.h>
Public Types
typedef QHash< QNetworkRequest::Attribute, QVariant > AttributesMap
typedef QHash< QNetworkRequest::KnownHeaders, QVariant > CookedHeadersMap
typedef QPair< QByteArray, QByteArray > RawHeaderPair
typedef QList< RawHeaderPair > RawHeadersList
Public Functions
RawHeadersList allRawHeaders () const
RawHeadersList::ConstIterator findRawHeader (const QByteArray &key) const
QList< QByteArray > rawHeadersKeys () const
void setAllRawHeaders (const RawHeadersList &list)
Sets the internal raw headers list to match list.
void setCookedHeader (QNetworkRequest::KnownHeaders header, const QVariant &value)
void setRawHeader (const QByteArray &key, const QByteArray &value)
Static Public Functions
static QDateTime fromHttpDate (const QByteArray &value)
static QByteArray toHttpDate (const QDateTime &dt)
Public Variables
AttributesMap attributes
CookedHeadersMap cookedHeaders
QWeakPointer< QObject > originatingObject
RawHeadersList rawHeaders
Private Functions
void parseAndSetHeader (const QByteArray &key, const QByteArray &value)
void setRawHeaderInternal (const QByteArray &key, const QByteArray &value)
Detailed Description
Definition at line 66 of file qnetworkrequest_p.h.
Typedefs
AttributesMap
typedef QHash<QNetworkRequest::Attribute, QVariant> QNetworkHeadersPrivate::AttributesMap
Definition at line 72 of file qnetworkrequest_p.h.
CookedHeadersMap
typedef QHash<QNetworkRequest::KnownHeaders, QVariant> QNetworkHeadersPrivate::CookedHeadersMap
Definition at line 71 of file qnetworkrequest_p.h.
RawHeaderPair
typedef QPair<QByteArray, QByteArray> QNetworkHeadersPrivate::RawHeaderPair
Definition at line 69 of file qnetworkrequest_p.h.
RawHeadersList
typedef QList<RawHeaderPair> QNetworkHeadersPrivate::RawHeadersList
Definition at line 70 of file qnetworkrequest_p.h.
Functions
allRawHeaders()
QNetworkHeadersPrivate::RawHeadersList QNetworkHeadersPrivate::allRawHeaders () const
Definition at line 853 of file qnetworkrequest.cpp.
 {
     return rawHeaders;
 }
findRawHeader()
QNetworkHeadersPrivate::RawHeadersList::ConstIterator QNetworkHeadersPrivate::findRawHeader (const QByteArray & key) const
Definition at line 842 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkRequest::hasRawHeader(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QNetworkRequest::rawHeader(), and QNetworkAccessHttpBackend::replyDownloadMetaData().
 {
     RawHeadersList::ConstIterator it = rawHeaders.constBegin();
     RawHeadersList::ConstIterator end = rawHeaders.constEnd();
     for ( ; it != end; ++it)
         if (qstricmp(it->first.constData(), key.constData()) == 0)
             return it;
     return end;                 // not found
 }
fromHttpDate()
QDateTime QNetworkHeadersPrivate::fromHttpDate (const QByteArray & value) static
Definition at line 1026 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), and parseHttpDate().
 {
     // HTTP dates have three possible formats:
     //  RFC 1123/822      -   ddd, dd MMM yyyy hh:mm:ss "GMT"
     //  RFC 850           -   dddd, dd-MMM-yy hh:mm:ss "GMT"
     //  ANSI C's asctime  -   ddd MMM d hh:mm:ss yyyy
     // We only handle them exactly. If they deviate, we bail out.
     int pos = value.indexOf(',');
     QDateTime dt;
 #ifndef QT_NO_DATESTRING
     if (pos == -1) {
         // no comma -> asctime(3) format
         dt = QDateTime::fromString(QString::fromLatin1(value), Qt::TextDate);
     } else {
         // Use sscanf over QLocal/QDateTimeParser for speed reasons. See the
         // QtWebKit performance benchmarks to get an idea.
         if (pos == 3) {
             char month_name[4];
             int day, year, hour, minute, second;
             if (sscanf(value.constData(), "%*3s, %d %3s %d %d:%d:%d 'GMT'", &day, month_name, &year, &hour, &minute, &second) == 6)
                 dt = QDateTime(QDate(year, name_to_month(month_name), day), QTime(hour, minute, second));
         } else {
             QLocale c = QLocale::c();
             // eat the weekday, the comma and the space following it
             QString sansWeekday = QString::fromLatin1(value.constData() + pos + 2);
             // must be RFC 850 date
             dt = c.toDateTime(sansWeekday, QLatin1String("dd-MMM-yy hh:mm:ss 'GMT'"));
         }
     }
 #endif // QT_NO_DATESTRING
     if (dt.isValid())
         dt.setTimeSpec(Qt::UTC);
     return dt;
 }
parseAndSetHeader()
void QNetworkHeadersPrivate::parseAndSetHeader (const QByteArray & key, const QByteArray & value) private
Definition at line 946 of file qnetworkrequest.cpp.
 {
     // is it a known header?
     QNetworkRequest::KnownHeaders parsedKey = parseHeaderName(key);
     if (parsedKey != QNetworkRequest::KnownHeaders(-1)) {
         if (value.isNull()) {
             cookedHeaders.remove(parsedKey);
         } else if (parsedKey == QNetworkRequest::ContentLengthHeader
                  && cookedHeaders.contains(QNetworkRequest::ContentLengthHeader)) {
             // Only set the cooked header "Content-Length" once.
             // See bug QTBUG-15311
         } else {
             cookedHeaders.insert(parsedKey, parseHeaderValue(parsedKey, value));
         }
     }
 }
rawHeadersKeys()
QList< QByteArray > QNetworkHeadersPrivate::rawHeadersKeys () const
Definition at line 858 of file qnetworkrequest.cpp.
Referenced by QNetworkRequest::rawHeaderList().
 {
     QList<QByteArray> result;
     RawHeadersList::ConstIterator it = rawHeaders.constBegin(),
                                  end = rawHeaders.constEnd();
     for ( ; it != end; ++it)
         result << it->first;
     return result;
 }
setAllRawHeaders()
void QNetworkHeadersPrivate::setAllRawHeaders (const RawHeadersList & list)
Sets the internal raw headers list to match list.
Warning
This function is not part of the public interface. The cooked headers will also be updated.
If list contains duplicates, they will be stored, but only the first one is usually accessed.
Definition at line 890 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), and QNetworkAccessHttpBackend::replyDownloadMetaData().
 {
     cookedHeaders.clear();
     rawHeaders = list;
     RawHeadersList::ConstIterator it = rawHeaders.constBegin();
     RawHeadersList::ConstIterator end = rawHeaders.constEnd();
     for ( ; it != end; ++it)
         parseAndSetHeader(it->first, it->second);
 }
setCookedHeader()
void QNetworkHeadersPrivate::setCookedHeader (QNetworkRequest::KnownHeaders header, const QVariant & value)
Definition at line 901 of file qnetworkrequest.cpp.
Referenced by QHttpPart::setHeader(), QNetworkRequest::setHeader(), and QNetworkAccessBackend::setHeader().
 {
     QByteArray name = headerName(header);
     if (name.isEmpty()) {
         // headerName verifies that \a header is a known value
         qWarning("QNetworkRequest::setHeader: invalid header value KnownHeader(%d) received", header);
         return;
     }
     if (value.isNull()) {
         setRawHeaderInternal(name, QByteArray());
         cookedHeaders.remove(header);
     } else {
         QByteArray rawValue = headerValue(header, value);
         if (rawValue.isEmpty()) {
             qWarning("QNetworkRequest::setHeader: QVariant of type %s cannot be used with header %s",
                      value.typeName(), name.constData());
             return;
         }
         setRawHeaderInternal(name, rawValue);
         cookedHeaders.insert(header, value);
     }
 }
setRawHeader()
void QNetworkHeadersPrivate::setRawHeader (const QByteArray & key, const QByteArray & value)
Definition at line 869 of file qnetworkrequest.cpp.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QHttpPart::setRawHeader(), QNetworkRequest::setRawHeader(), and QNetworkAccessBackend::setRawHeader().
 {
     if (key.isEmpty())
         // refuse to accept an empty raw header
         return;
     setRawHeaderInternal(key, value);
     parseAndSetHeader(key, value);
 }
setRawHeaderInternal()
void QNetworkHeadersPrivate::setRawHeaderInternal (const QByteArray & key, const QByteArray & value) private
Definition at line 927 of file qnetworkrequest.cpp.
 {
     RawHeadersList::Iterator it = rawHeaders.begin();
     while (it != rawHeaders.end()) {
         if (qstricmp(it->first.constData(), key.constData()) == 0)
             it = rawHeaders.erase(it);
         else
             ++it;
     }
     if (value.isNull())
         return;                 // only wanted to erase key
     RawHeaderPair pair;
     pair.first = key;
     pair.second = value;
     rawHeaders.append(pair);
 }
toHttpDate()
QByteArray QNetworkHeadersPrivate::toHttpDate (const QDateTime & dt) static
Definition at line 1063 of file qnetworkrequest.cpp.
Referenced by headerValue(), and QNetworkAccessHttpBackend::loadFromCacheIfAllowed().
 {
     return QLocale::c().toString(dt, QLatin1String("ddd, dd MMM yyyy hh:mm:ss 'GMT'"))
         .toLatin1();
 }
Properties
attributes
AttributesMap QNetworkHeadersPrivate::attributes
Definition at line 76 of file qnetworkrequest_p.h.
Referenced by QNetworkRequest::attribute(), QNetworkReplyImplPrivate::initCacheSaveDevice(), QNetworkRequestPrivate::operator==(), QNetworkReplyPrivate::QNetworkReplyPrivate(), QNetworkReplyImplPrivate::redirectionRequested(), QNetworkRequest::setAttribute(), and QNetworkAccessBackend::setAttribute().
cookedHeaders
CookedHeadersMap QNetworkHeadersPrivate::cookedHeaders
Definition at line 75 of file qnetworkrequest_p.h.
Referenced by QNetworkReplyImplPrivate::_q_copyReadyRead(), QNetworkReplyImplPrivate::appendDownstreamDataSignalEmissions(), QNetworkReplyImplPrivate::finished(), QNetworkRequest::header(), and QNetworkReplyImplPrivate::metaDataChanged().
originatingObject
QWeakPointer<QObject> QNetworkHeadersPrivate::originatingObject
Definition at line 77 of file qnetworkrequest_p.h.
Referenced by QNetworkRequest::originatingObject(), and QNetworkRequest::setOriginatingObject().
rawHeaders
RawHeadersList QNetworkHeadersPrivate::rawHeaders
Definition at line 74 of file qnetworkrequest_p.h.
Referenced by QNetworkAccessHttpBackend::fetchCacheMetaData(), QNetworkRequest::hasRawHeader(), QNetworkAccessHttpBackend::loadFromCacheIfAllowed(), QHttpPartPrivate::operator==(), QNetworkRequestPrivate::operator==(), QNetworkRequest::rawHeader(), and QNetworkAccessHttpBackend::replyDownloadMetaData().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkrequest_p.h
/src/network/access/qnetworkrequest.cpp