Qt 4.8: QAbstractStatePrivate Class Reference
QAbstractStatePrivate Class Reference
#include <qabstractstate_p.h>
Public Types
enum StateType { AbstractState, StandardState, FinalState, HistoryState }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void callOnEntry (QEvent *e)
void callOnExit (QEvent *e)
void emitEntered ()
void emitExited ()
QStateMachine * machine () const
QAbstractStatePrivate (StateType type)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QAbstractStatePrivate * get (QAbstractState *q)
static const QAbstractStatePrivate * get (const QAbstractState *q)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
uint isMachine:1
QState * parentState
uint stateType:31
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Detailed Description
Definition at line 63 of file qabstractstate_p.h.
Enumerations
StateType
enum QAbstractStatePrivate::StateType
Enumerator
AbstractState
StandardState
FinalState
HistoryState
Definition at line 68 of file qabstractstate_p.h.
                    {
         AbstractState,
         StandardState,
         FinalState,
         HistoryState
     };
Constructors and Destructors
QAbstractStatePrivate()
QAbstractStatePrivate::QAbstractStatePrivate (StateType type)
Definition at line 84 of file qabstractstate.cpp.
     : stateType(type), isMachine(false), parentState(0)
 {
 }
Functions
callOnEntry()
void QAbstractStatePrivate::callOnEntry (QEvent * e)
Definition at line 110 of file qabstractstate.cpp.
Referenced by QStateMachinePrivate::enterStates().
 {
     Q_Q(QAbstractState);
     q->onEntry(e);
 }
callOnExit()
void QAbstractStatePrivate::callOnExit (QEvent * e)
Definition at line 116 of file qabstractstate.cpp.
Referenced by QStateMachinePrivate::exitStates().
 {
     Q_Q(QAbstractState);
     q->onExit(e);
 }
emitEntered()
void QAbstractStatePrivate::emitEntered ()
Definition at line 122 of file qabstractstate.cpp.
Referenced by QStateMachinePrivate::enterStates().
 {
     Q_Q(QAbstractState);
     emit q->entered();
 }
emitExited()
void QAbstractStatePrivate::emitExited ()
Definition at line 128 of file qabstractstate.cpp.
Referenced by QStateMachinePrivate::exitStates().
 {
     Q_Q(QAbstractState);
     emit q->exited();
 }
get() [1/2]
QAbstractStatePrivate * QAbstractStatePrivate::get (QAbstractState * q) static
Definition at line 89 of file qabstractstate.cpp.
Referenced by QStateMachine::addState(), QState::addTransition(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), QStateMachinePrivate::isFinal(), QStateMachine::removeState(), QStateMachinePrivate::toFinalState(), QStateMachinePrivate::toHistoryState(), and QStateMachinePrivate::toStandardState().
 {
     return q->d_func();
 }
get() [2/2]
const QAbstractStatePrivate * QAbstractStatePrivate::get (const QAbstractState * q) static
Definition at line 94 of file qabstractstate.cpp.
 {
     return q->d_func();
 }
machine()
QStateMachine * QAbstractStatePrivate::machine () const
Definition at line 99 of file qabstractstate.cpp.
Referenced by QState::addTransition().
 {
     QObject *par = parent;
     while (par != 0) {
         if (QStateMachine *mach = qobject_cast<QStateMachine*>(par))
             return mach;
         par = par->parent();
     }
     return 0;
 }
Properties
isMachine
uint QAbstractStatePrivate::isMachine
Definition at line 89 of file qabstractstate_p.h.
Referenced by QStateMachinePrivate::isAtomic(), QStateMachinePrivate::isCompound(), and QStateMachinePrivate::QStateMachinePrivate().
parentState
QState* QAbstractStatePrivate::parentState mutable
Definition at line 90 of file qabstractstate_p.h.
Referenced by QStateMachinePrivate::applyProperties(), and QStateMachinePrivate::selectTransitions().
stateType
uint QAbstractStatePrivate::stateType
Definition at line 88 of file qabstractstate_p.h.
Referenced by QStateMachinePrivate::isFinal(), QStateMachinePrivate::toFinalState(), QStateMachinePrivate::toHistoryState(), and QStateMachinePrivate::toStandardState().
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qabstractstate_p.h
/src/corelib/statemachine/qabstractstate.cpp