Qt 4.8: QInternal Class Reference
QInternal Class Reference
#include <qnamespace.h>
Public Types
enum Callback {
ConnectCallback, DisconnectCallback, AdoptCurrentThread, EventNotifyCallback,
LastCallback
}
enum DockPosition {
LeftDock, RightDock, TopDock, BottomDock,
DockCount
}
enum InternalFunction {
CreateThreadForAdoption, RefAdoptedThread, DerefAdoptedThread, SetCurrentThreadToMainThread,
SetQObjectSender, GetQObjectSender, ResetQObjectSender, LastInternalFunction
}
enum PaintDeviceFlags {
UnknownDevice = 0x00, Widget = 0x01, Pixmap = 0x02, Image = 0x03,
Printer = 0x04, Picture = 0x05, Pbuffer = 0x06, FramebufferObject = 0x07,
CustomRaster = 0x08, MacQuartz = 0x09, PaintBuffer = 0x0a, OpenGL = 0x0b
}
enum RelayoutType { RelayoutNormal, RelayoutDragging, RelayoutDropped }
Static Public Functions
static bool activateCallbacks (Callback, void **)
static bool callFunction (InternalFunction func, void **)
static bool registerCallback (Callback, qInternalCallback)
static bool unregisterCallback (Callback, qInternalCallback)
Detailed Description
Definition at line 1820 of file qnamespace.h.
Enumerations
Callback
enum QInternal::Callback
Enumerator
ConnectCallback
DisconnectCallback
AdoptCurrentThread
EventNotifyCallback
LastCallback
Definition at line 1843 of file qnamespace.h.
                   {
         ConnectCallback,
         DisconnectCallback,
         AdoptCurrentThread,
         EventNotifyCallback,
         LastCallback
     };
DockPosition
enum QInternal::DockPosition
Enumerator
LeftDock
RightDock
TopDock
BottomDock
DockCount
Definition at line 1862 of file qnamespace.h.
                       {
         LeftDock,
         RightDock,
         TopDock,
         BottomDock,
         DockCount
     };
InternalFunction
enum QInternal::InternalFunction
Enumerator
CreateThreadForAdoption
RefAdoptedThread
DerefAdoptedThread
SetCurrentThreadToMainThread
SetQObjectSender
GetQObjectSender
ResetQObjectSender
LastInternalFunction
Definition at line 1851 of file qnamespace.h.
{
         CreateThreadForAdoption,
         RefAdoptedThread,
         DerefAdoptedThread,
         SetCurrentThreadToMainThread,
         SetQObjectSender,
         GetQObjectSender,
         ResetQObjectSender,
         LastInternalFunction
     };
PaintDeviceFlags
enum QInternal::PaintDeviceFlags
Enumerator
UnknownDevice
Widget
Pixmap
Image
Printer
Picture
Pbuffer
FramebufferObject
CustomRaster
MacQuartz
PaintBuffer
OpenGL
Definition at line 1822 of file qnamespace.h.
{
         UnknownDevice = 0x00,
         Widget        = 0x01,
         Pixmap        = 0x02,
         Image         = 0x03,
         Printer       = 0x04,
         Picture       = 0x05,
         Pbuffer       = 0x06,    // GL pbuffer
         FramebufferObject = 0x07, // GL framebuffer object
         CustomRaster  = 0x08,
         MacQuartz     = 0x09,
         PaintBuffer   = 0x0a,
         OpenGL        = 0x0b
     };
RelayoutType
enum QInternal::RelayoutType
Enumerator
RelayoutNormal
RelayoutDragging
RelayoutDropped
Definition at line 1836 of file qnamespace.h.
                       {
         RelayoutNormal,
         RelayoutDragging,
         RelayoutDropped
     };
Functions
activateCallbacks()
bool QInternal::activateCallbacks (Callback cb, void ** parameters) static
Definition at line 3653 of file qglobal.cpp.
Referenced by QObject::connect(), QThreadData::current(), QObject::disconnect(), QCoreApplication::notifyInternal(), and qt_free_tls().
 {
     Q_ASSERT_X(cb >= 0, "QInternal::activateCallback()", "Callback id must be a valid id");
     QInternal_CallBackTable *cbt = global_callback_table();
     if (cbt && cb < cbt->callbacks.size()) {
         QList<qInternalCallback> callbacks = cbt->callbacks[cb];
         bool ret = false;
         for (int i=0; i<callbacks.size(); ++i)
             ret |= (callbacks.at(i))(parameters);
         return ret;
     }
     return false;
 }
callFunction()
bool QInternal::callFunction (InternalFunction func, void ** args) static
Definition at line 3670 of file qglobal.cpp.
 {
     Q_ASSERT_X(func >= 0,
                "QInternal::callFunction()", "Callback id must be a valid id");
 #ifndef QT_NO_QOBJECT
     switch (func) {
 #ifndef QT_NO_THREAD
     case QInternal::CreateThreadForAdoption:
         *args = QAdoptedThread::createThreadForAdoption();
         return true;
 #endif
     case QInternal::RefAdoptedThread:
         QThreadData::get2((QThread *) *args)->ref();
         return true;
     case QInternal::DerefAdoptedThread:
         QThreadData::get2((QThread *) *args)->deref();
         return true;
     case QInternal::SetCurrentThreadToMainThread:
         qt_set_current_thread_to_main_thread();
         return true;
     case QInternal::SetQObjectSender: {
         QObject *receiver = (QObject *) args[0];
         QObjectPrivate::Sender *sender = new QObjectPrivate::Sender;
         sender->sender = (QObject *) args[1];
         sender->signal = *(int *) args[2];
         sender->ref = 1;
         // Store the old sender as "return value"
         args[3] = QObjectPrivate::setCurrentSender(receiver, sender);
         args[4] = sender;
         return true;
     }
     case QInternal::GetQObjectSender: {
         QObject *receiver = (QObject *) args[0];
         QObjectPrivate *d = QObjectPrivate::get(receiver);
         args[1] = d->currentSender ? d->currentSender->sender : 0;
         return true;
     }
     case QInternal::ResetQObjectSender: {
         QObject *receiver = (QObject *) args[0];
         QObjectPrivate::Sender *oldSender = (QObjectPrivate::Sender *) args[1];
         QObjectPrivate::Sender *sender = (QObjectPrivate::Sender *) args[2];
         QObjectPrivate::resetCurrentSender(receiver, sender, oldSender);
         delete sender;
         return true;
     }
     default:
         break;
     }
 #else
     Q_UNUSED(args);
     Q_UNUSED(func);
 #endif
     return false;
 }
registerCallback()
bool QInternal::registerCallback (Callback cb, qInternalCallback callback) static
Definition at line 3633 of file qglobal.cpp.
Referenced by QScriptDebugger::setFrontend().
 {
     if (cb >= 0 && cb < QInternal::LastCallback) {
         QInternal_CallBackTable *cbt = global_callback_table();
         cbt->callbacks.resize(cb + 1);
         cbt->callbacks[cb].append(callback);
         return true;
     }
     return false;
 }
unregisterCallback()
bool QInternal::unregisterCallback (Callback cb, qInternalCallback callback) static
Definition at line 3644 of file qglobal.cpp.
Referenced by QScriptDebugger::~QScriptDebugger().
 {
     if (cb >= 0 && cb < QInternal::LastCallback) {
         QInternal_CallBackTable *cbt = global_callback_table();
         return (bool) cbt->callbacks[cb].removeAll(callback);
     }
     return false;
 }
The documentation for this class was generated from the following files:
/src/corelib/global/qnamespace.h
/src/corelib/global/qglobal.cpp