Qt 4.8: QStack< T > Class Template Reference
QStack< T > Class Template Reference
The QStack class is a template class that provides a stack.
#include <qcontainerfwd.h>
Public Functions
T pop ()
Removes the top item from the stack and returns it.
void push (const T &t)
Adds element t to the top of the stack.
QStack ()
Constructs an empty stack.
void swap (QStack< T > &other)
Swaps stack other with this stack.
T & top ()
Returns a reference to the stack's top item.
const T & top () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
~QStack ()
Destroys the stack.
Public Functions inherited from QVector< T >
void append (const T &t)
Inserts value at the end of the vector.
const T & at (int i) const
Returns the item at index position i in the vector.
reference back ()
This function is provided for STL compatibility.
const_reference back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the vector.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int capacity () const
Returns the maximum number of items that can be stored in the vector without forcing a reallocation.
void clear ()
Removes all the elements from the vector and releases the memory used by the vector.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the vector.
const T * constData () const
Returns a const pointer to the data stored in the vector.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the vector.
bool contains (const T &t) const
Returns true if the vector contains an occurrence of value; otherwise returns false.
int count (const T &t) const
Returns the number of occurrences of value in the vector.
int count () const
Same as size().
T * data ()
Returns a pointer to the data stored in the vector.
const T * data () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void detach ()
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the vector.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const T &t) const
Returns true if this vector is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator begin, iterator end)
Removes all the items from begin up to (but not including) end.
iterator erase (iterator pos)
Removes the item pointed to by the iterator pos from the vector, and returns an iterator to the next item in the vector (which may be end()).
QVector< T > & fill (const T &t, int size=-1)
Assigns value to all items in the vector.
T & first ()
Returns a reference to the first item in the vector.
const T & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & front ()
This function is provided for STL compatibility.
const_reference front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const T &t, int from=0) const
Returns the index position of the first occurrence of value in the vector, searching forward from index position from.
void insert (int i, const T &t)
Inserts value at index position i in the vector.
void insert (int i, int n, const T &t)
Inserts count copies of value at index position i in the vector.
iterator insert (iterator before, int n, const T &x)
Inserts count copies of value in front of the item pointed to by the iterator before.
iterator insert (iterator before, const T &x)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the vector has size 0; otherwise returns false.
bool isSharedWith (const QVector< T > &other) const
T & last ()
Returns a reference to the last item in the vector.
const T & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const T &t, int from=-1) const
Returns the index position of the last occurrence of the value value in the vector, searching backward from index position from.
QVector< T > mid (int pos, int length=-1) const
Returns a vector whose elements are copied from this vector, starting at position pos.
bool operator!= (const QVector< T > &v) const
Returns true if other is not equal to this vector; otherwise returns false.
QVector< T > operator+ (const QVector< T > &l) const
Returns a vector that contains all the items in this vector followed by all the items in the other vector.
QVector< T > & operator+= (const QVector< T > &l)
Appends the items of the other vector to this vector and returns a reference to this vector.
QVector< T > & operator+= (const T &t)
Appends value to the vector.
QVector< T > & operator<< (const QVector< T > &l)
Appends other to the vector and returns a reference to the vector.
QVector< T > & operator<< (const T &t)
Appends value to the vector and returns a reference to this vector.
QVector< T > & operator= (const QVector< T > &v)
Assigns other to this vector and returns a reference to this vector.
bool operator== (const QVector< T > &v) const
Returns true if other is equal to this vector; otherwise returns false.
T & operator[] (int i)
Returns the item at index position i as a modifiable reference.
const T & operator[] (int i) const
Same as at(i).
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const T &t)
Inserts value at the beginning of the vector.
void push_back (const T &t)
This function is provided for STL compatibility.
void push_front (const T &t)
This function is provided for STL compatibility.
QVector ()
Constructs an empty vector.
QVector (int size)
Constructs a vector with an initial size of size elements.
QVector (int size, const T &t)
Constructs a vector with an initial size of size elements.
QVector (const QVector< T > &v)
Constructs a copy of other.
void remove (int i)
Removes the element at index position i.
void remove (int i, int n)
Removes count elements from the middle of the vector, starting at index position i.
void replace (int i, const T &t)
Replaces the item at index position i with value.
void reserve (int size)
Attempts to allocate memory for at least size elements.
void resize (int size)
Sets the size of the vector to size.
void setSharable (bool sharable)
int size () const
Returns the number of items in the vector.
void squeeze ()
Releases any memory not required to store the items.
bool startsWith (const T &t) const
Returns true if this vector is not empty and its first item is equal to value; otherwise returns false.
void swap (QVector< T > &other)
Swaps vector other with this vector.
QList< T > toList () const
Returns a QList object with the data contained in this QVector.
std::vector< T > toStdVector () const
Returns a std::vector object with the data contained in this QVector.
T value (int i) const
Returns the value at index position i in the vector.
T value (int i, const T &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QVector ()
Destroys the vector.
Additional Inherited Members
Public Types inherited from QVector< T >
typedef const T * const_iterator
The QVector::const_iterator typedef provides an STL-style const iterator for QVector and QStack.
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for T &.
typedef const_iterator ConstIterator
Qt-style synonym for QVector::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef T * iterator
The QVector::iterator typedef provides an STL-style non-const iterator for QVector and QStack.
typedef iterator Iterator
Qt-style synonym for QVector::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef T value_type
Typedef for T.
Static Public Functions inherited from QVector< T >
static QVector< T > fromList (const QList< T > &list)
Returns a QVector object with the data contained in list.
static QVector< T > fromStdVector (const std::vector< T > &vector)
Returns a QVector object with the data contained in vector.
Related Functions inherited from QVector< T >
QDataStream & operator<< (QDataStream &out, const QVector< T > &vector)
Writes the vector vector to stream out.
QDataStream & operator>> (QDataStream &in, QVector< T > &vector)
Reads a vector from stream in into vector.
Detailed Description
template<class T>
class QStack< T >
The QStack class is a template class that provides a stack.
Note
This class or function is reentrant.
QStack<T> is one of Qt's generic container classes. It implements a stack data structure for items of a same type.
A stack is a last in, first out (LIFO) structure. Items are added to the top of the stack using push() and retrieved from the top using pop(). The top() function provides access to the topmost item without removing it.
Example:
    QStack<int> stack;
    stack.push(1);
    stack.push(2);
    stack.push(3);
    while (!stack.isEmpty())
        cout << stack.pop() << endl;
The example will output 3, 2, 1 in that order.
QStack inherits from QVector. All of QVector's functionality also applies to QStack. For example, you can use isEmpty() to test whether the stack is empty, and you can traverse a QStack using QVector's iterator classes (for example, QVectorIterator). But in addition, QStack provides three convenience functions that make it easy to implement LIFO semantics: push(), pop(), and top().
QStack's value type must be an assignable data type. This covers most data types that are commonly used, but the compiler won't let you, for example, store a QWidget as a value; instead, store a QWidget *.
See also
QVector, QQueue
Definition at line 63 of file qcontainerfwd.h.
Constructors and Destructors
QStack()
template<class T> QStack< T >::QStack () inline
Constructs an empty stack.
Definition at line 57 of file qstack.h.
 {}
~QStack()
template<class T> QStack< T >::~QStack () inline
Destroys the stack.
References to the values in the stack, and all iterators over this stack, become invalid.
Definition at line 58 of file qstack.h.
 {}
Functions
pop()
template<class T > T QStack< T >::pop () inline
Removes the top item from the stack and returns it.
This function assumes that the stack isn't empty.
See also
top(), push(), isEmpty()
Definition at line 67 of file qstack.h.
Referenced by QDirIteratorPrivate::advance(), QTreeWidgetItem::clone(), QPatternist::AccelTree::copyNodeTo(), QSvgHandler::endElement(), QPatternist::ParserContext::endParsingWithParam(), QPatternist::ParserContext::finalizePushedVariable(), QTreeWidgetItem::insertChild(), QTreeWidgetItem::insertChildren(), QTreeModel::insertColumns(), QDirModelPrivate::invalidate(), QTreeView::keyPressEvent(), QPatternist::XSLTTokenizer::leaveState(), Document::load(), QStandardItemModel::mimeData(), QPatternist::PullBridge::next(), StringSplitter::next(), QPatternist::XQueryTokenizer::nextToken(), QDeclarativeStyledTextPrivate::parse(), QXmlSimpleReaderPrivate::parseAttlistDecl(), QXmlSimpleReaderPrivate::parseAttribute(), QXmlSimpleReaderPrivate::parseAttType(), QXmlSimpleReaderPrivate::parseAttValue(), QXmlSimpleReaderPrivate::parseChoiceSeq(), QXmlSimpleReaderPrivate::parseComment(), QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::parseDoctype(), QXmlSimpleReaderPrivate::parseElement(), QXmlSimpleReaderPrivate::parseElementDecl(), QXmlSimpleReaderPrivate::parseEntityDecl(), QXmlSimpleReaderPrivate::parseEntityValue(), QXmlSimpleReaderPrivate::parseExternalID(), QXmlSimpleReaderPrivate::parseMarkupdecl(), QXmlSimpleReaderPrivate::parseMisc(), QXmlSimpleReaderPrivate::parseName(), QXmlSimpleReaderPrivate::parseNmtoken(), QXmlSimpleReaderPrivate::parseNotationDecl(), QXmlSimpleReaderPrivate::parsePEReference(), QXmlSimpleReaderPrivate::parsePI(), QXmlSimpleReaderPrivate::parseProlog(), QXmlSimpleReaderPrivate::parseReference(), QXmlSimpleReaderPrivate::parseString(), QSvgHandler::popColor(), QPatternist::XQueryTokenizer::popState(), QXmlSimpleReaderPrivate::processElementEmptyTag(), QXmlSimpleReaderPrivate::processElementETagBegin2(), QTreeWidgetItemPrivate::propagateDisabled(), QStack< State >::push(), QPatternist::XSLTTokenizer::queueOnExit(), QTreeViewPrivate::select(), QDeclarativeListModelParser::setCustomData(), QTreeWidgetItem::setFlags(), QStandardItemPrivate::setModel(), QComboBox::showPopup(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QTreeWidgetItem::takeChild(), and QTreeWidgetItem::takeChildren().
 { Q_ASSERT(!this->isEmpty()); T t = this->data()[this->size() -1];
   this->resize(this->size()-1); return t; }
push()
template<class T> void QStack< T >::push (const T & t) inline
Adds element t to the top of the stack.
This is the same as QVector::append().
See also
pop(), top()
Definition at line 60 of file qstack.h.
Referenced by QSettingsPrivate::beginGroupOrArray(), QTreeWidgetItem::clone(), QPatternist::AccelTree::copyNodeTo(), QSvgTinyDocument::draw(), QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleXMLBase(), QPatternist::XSLTTokenizer::handleXSLTVersion(), QTreeWidgetItem::insertChild(), QTreeWidgetItem::insertChildren(), QTreeModel::insertColumns(), QXmlSimpleReaderPrivate::insertXmlRef(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QDirModelPrivate::invalidate(), QTreeView::keyPressEvent(), StringSplitter::loadNext(), QStandardItemModel::mimeData(), QPatternist::PullBridge::next(), QPatternist::XQueryTokenizer::nextToken(), QDeclarativeStyledTextPrivate::parse(), QXmlSimpleReaderPrivate::parseElement(), QPatternist::ParserContext::ParserContext(), QTreeWidgetItemPrivate::propagateDisabled(), QPatternist::PullBridge::PullBridge(), QSvgHandler::pushColor(), QXmlSimpleReaderPrivate::pushParseState(), QPatternist::XQueryTokenizer::pushState(), QPatternist::XSLTTokenizer::pushState(), QPatternist::pushVariable(), QPatternist::XSLTTokenizer::queueNamespaceDeclarations(), QXmlFormatterPrivate::QXmlFormatterPrivate(), QXmlSerializerPrivate::QXmlSerializerPrivate(), QTreeViewPrivate::select(), QDeclarativeListModelParser::setCustomData(), QTreeWidgetItem::setFlags(), QStandardItemPrivate::setModel(), QComboBox::showPopup(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QSvgHandler::startElement(), QPatternist::ParserContext::startParsingWithParam(), StringSplitter::StringSplitter(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), and QSvgNode::transformedBounds().
 { QVector<T>::append(t); }
swap()
template<class T> void QStack< T >::swap (QStack< T > & other) inline
Swaps stack other with this stack.
Since
4.8
This operation is very fast and never fails.
Definition at line 59 of file qstack.h.
 { QVector<T>::swap(other); } // prevent QVector<->QStack swaps
top() [1/2]
template<class T > T & QStack< T >::top () inline
Returns a reference to the stack's top item.
This function assumes that the stack isn't empty.
This is the same as QVector::last().
See also
pop(), push(), isEmpty()
Definition at line 72 of file qstack.h.
Referenced by QDirIteratorPrivate::advance(), QSvgHandler::characters(), QPatternist::AccelTree::copyNodeTo(), QSvgHandler::currentColor(), QPatternist::AccelTreeBuilder< true >::currentParent(), QSvgHandler::endElement(), QPatternist::ParserContext::finalizePushedVariable(), QCoreApplication::hasPendingEvents(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideStylesheetModule(), QPatternist::XSLTTokenizer::isAnyAttributeAllowed(), QPatternist::ParserContext::isParsingWithParam(), Document::load(), QPatternist::PullBridge::next(), QXmlSimpleReaderPrivate::next(), QPatternist::XSLTTokenizer::nextToken(), QDeclarativeStyledTextPrivate::parse(), QXmlSimpleReaderPrivate::parseAttlistDecl(), QXmlSimpleReaderPrivate::parseAttribute(), QXmlSimpleReaderPrivate::parseAttType(), QXmlSimpleReaderPrivate::parseAttValue(), QXmlSimpleReaderPrivate::parseChoiceSeq(), QXmlSimpleReaderPrivate::parseComment(), QXmlSimpleReaderPrivate::parseContent(), QXmlSimpleReaderPrivate::parseDoctype(), QXmlSimpleReaderPrivate::parseElement(), QXmlSimpleReaderPrivate::parseElementDecl(), QXmlSimpleReaderPrivate::parseEntityDecl(), QXmlSimpleReaderPrivate::parseEntityValue(), QXmlSimpleReaderPrivate::parseExternalID(), QXmlSimpleReaderPrivate::parseMarkupdecl(), QXmlSimpleReaderPrivate::parseMisc(), QXmlSimpleReaderPrivate::parseName(), QXmlSimpleReaderPrivate::parseNmtoken(), QXmlSimpleReaderPrivate::parseNotationDecl(), QXmlSimpleReaderPrivate::parsePEReference(), QXmlSimpleReaderPrivate::parsePI(), QXmlSimpleReaderPrivate::parseProlog(), QXmlSimpleReaderPrivate::parseReference(), QXmlSimpleReaderPrivate::parseString(), QSvgHandler::popColor(), QXmlSimpleReaderPrivate::processElementEmptyTag(), QStack< State >::push(), QSvgHandler::pushColorCopy(), QXmlSimpleReaderPrivate::reportEndEntities(), QDeclarativeListModelParser::setCustomData(), QSvgHandler::startElement(), and QPatternist::XSLTTokenizer::whitespaceToSkip().
 { Q_ASSERT(!this->isEmpty()); this->detach(); return this->data()[this->size()-1]; }
top() [2/2]
template<class T > const T & QStack< T >::top () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
pop(), push()
Definition at line 76 of file qstack.h.
 { Q_ASSERT(!this->isEmpty()); return this->data()[this->size()-1]; }
The documentation for this class was generated from the following files:
/src/corelib/tools/qcontainerfwd.h
/src/corelib/tools/qstack.h
/src/corelib/tools/qstack.cpp