Qt 4.8: QIntValidator Class Reference
QIntValidator Class Reference
The QIntValidator class provides a validator that ensures a string contains a valid integer within a specified range.
#include <qvalidator.h>
Public Functions
int bottom () const
void fixup (QString &input) const
Reimplemented Function
QIntValidator (QObject *parent=0)
Constructs a validator with a parent object that accepts all integers.
QIntValidator (int bottom, int top, QObject *parent=0)
Constructs a validator with a parent, that accepts integers from minimum to maximum inclusive.
void setBottom (int)
virtual void setRange (int bottom, int top)
Sets the range of the validator to only accept integers between bottom and top inclusive.
void setTop (int)
int top () const
QValidator::State validate (QString &, int &) const
Returns Acceptable if the input is an integer within the valid range, Intermediate if the input is a prefix of an integer in the valid range, and Invalid otherwise.
~QIntValidator ()
Destroys the validator.
Public Functions inherited from QValidator
QLocale locale () const
Returns the locale for the validator.
QValidator (QObject *parent=0)
Sets up the validator.
void setLocale (const QLocale &locale)
Sets the locale that will be used for the validator.
~QValidator ()
Destroys the validator, freeing any storage and other resources used.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
int b
int bottom
the validator's lowest acceptable value
int t
int top
the validator's highest acceptable value
Additional Inherited Members
Public Types inherited from QValidator
enum State { Invalid, Intermediate, Acceptable }
This enum type defines the states in which a validated string can exist.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QValidator
QValidator (QObjectPrivate &d, QObject *parent)
QValidator (QValidatorPrivate &d, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QIntValidator class provides a validator that ensures a string contains a valid integer within a specified range.
Example of use:
QValidator *validator = new QIntValidator(100, 999, this);
QLineEdit *edit = new QLineEdit(this);
// the edit lineedit will only accept integers between 100 and 999
edit->setValidator(validator);
Below we present some examples of validators. In practice they would normally be associated with a widget as in the example above.
QString str;
int pos = 0;
QIntValidator v(100, 900, this);
str = "1";
v.validate(str, pos);     // returns Intermediate
str = "012";
v.validate(str, pos);     // returns Intermediate
str = "123";
v.validate(str, pos);     // returns Acceptable
str = "678";
v.validate(str, pos);     // returns Acceptable
str = "999";
v.validate(str, pos);    // returns Intermediate
str = "1234";
v.validate(str, pos);     // returns Invalid
str = "-123";
v.validate(str, pos);     // returns Invalid
str = "abc";
v.validate(str, pos);     // returns Invalid
str = "12cm";
v.validate(str, pos);     // returns Invalid
Notice that the value 999 returns Intermediate. Values consisting of a number of digits equal to or less than the max value are considered intermediate. This is intended because the digit that prevents a number to be in range is not necessarily the last digit typed. This also means that an intermediate number can have leading zeros.
The minimum and maximum values are set in one call with setRange(), or individually with setBottom() and setTop().
QIntValidator uses its locale() to interpret the number. For example, in Arabic locales, QIntValidator will accept Arabic digits. In addition, QIntValidator is always guaranteed to accept a number formatted according to the "C" locale.
See also
QDoubleValidator, QRegExpValidator, {Line Edits Example}
Definition at line 96 of file qvalidator.h.
Constructors and Destructors
QIntValidator() [1/2]
QIntValidator::QIntValidator (QObject * parent = 0) explicit
Constructs a validator with a parent object that accepts all integers.
Definition at line 291 of file qvalidator.cpp.
Referenced by QIntValidator().
     : QValidator(parent)
 {
     b = INT_MIN;
     t = INT_MAX;
 }
QIntValidator() [2/2]
QIntValidator::QIntValidator (int bottom, int top, QObject * parent = 0)
Constructs a validator with a parent, that accepts integers from minimum to maximum inclusive.
Definition at line 304 of file qvalidator.cpp.
     : QValidator(parent)
 {
     b = minimum;
     t = maximum;
 }
~QIntValidator()
QIntValidator::~QIntValidator ()
Destroys the validator.
Definition at line 357 of file qvalidator.cpp.
 {
     // nothing
 }
Functions
bottom()
int QIntValidator::bottom () const inline
Definition at line 114 of file qvalidator.h.
Referenced by setRange(), and setTop().
 { return b; }
fixup()
void QIntValidator::fixup (QString & input) const virtual
Reimplemented Function
Reimplemented from QValidator.
Definition at line 441 of file qvalidator.cpp.
 {
     QByteArray buff;
     if (!locale().d()->validateChars(input, QLocalePrivate::IntegerMode, &buff)) {
         QLocale cl(QLocale::C);
         if (!cl.d()->validateChars(input, QLocalePrivate::IntegerMode, &buff))
             return;
     }
     bool ok, overflow;
     qlonglong entered = QLocalePrivate::bytearrayToLongLong(buff.constData(), 10, &ok, &overflow);
     if (ok && !overflow)
         input = locale().toString(entered);
 }
setBottom()
void QIntValidator::setBottom (int bottom)
Definition at line 479 of file qvalidator.cpp.
 {
     setRange(bottom, top());
 }
setRange()
void QIntValidator::setRange (int bottom, int top) virtual
Sets the range of the validator to only accept integers between bottom and top inclusive.
Definition at line 460 of file qvalidator.cpp.
Referenced by setBottom(), and setTop().
 {
     b = bottom;
     t = top;
 }
setTop()
void QIntValidator::setTop (int top)
Definition at line 496 of file qvalidator.cpp.
 {
     setRange(bottom(), top);
 }
top()
int QIntValidator::top () const inline
Definition at line 115 of file qvalidator.h.
Referenced by setBottom(), and setRange().
 { return t; }
validate()
QValidator::State QIntValidator::validate (QString & input, int & pos) const virtual
Returns Acceptable if the input is an integer within the valid range, Intermediate if the input is a prefix of an integer in the valid range, and Invalid otherwise.
If the valid range consists of just positive integers (e.g., 32 to 100) and input is a negative integer, then Invalid is returned. (On the other hand, if the range consists of negative integers (e.g., -100 to -32) and input is a positive integer, then Intermediate is returned, because the user might be just about to type the minus (especially for right-to-left languages).
int pos = 0;
s = "abc";
v.validate(s, pos);    // returns Invalid
s = "5";
v.validate(s, pos);    // returns Intermediate
s = "50";
v.validate(s, pos);    // returns Acceptable
By default, the pos parameter is not used by this validator.
Implements QValidator.
Definition at line 400 of file qvalidator.cpp.
 {
     QByteArray buff;
     if (!locale().d()->validateChars(input, QLocalePrivate::IntegerMode, &buff)) {
         QLocale cl(QLocale::C);
         if (!cl.d()->validateChars(input, QLocalePrivate::IntegerMode, &buff))
             return Invalid;
     }
     if (buff.isEmpty())
         return Intermediate;
     if (b >= 0 && buff.startsWith('-'))
         return Invalid;
     if (t < 0 && buff.startsWith('+'))
         return Invalid;
     if (buff.size() == 1 && (buff.at(0) == '+' || buff.at(0) == '-'))
         return Intermediate;
     bool ok, overflow;
     qlonglong entered = QLocalePrivate::bytearrayToLongLong(buff.constData(), 10, &ok, &overflow);
     if (overflow || !ok)
         return Invalid;
     if (entered >= b && entered <= t) {
         locale().toInt(input, &ok, 10);
         return ok ? Acceptable : Intermediate;
     }
     if (entered >= 0) {
         // the -entered < b condition is necessary to allow people to type
         // the minus last (e.g. for right-to-left languages)
         return (entered > t && -entered < b) ? Invalid : Intermediate;
     } else {
         return (entered < b) ? Invalid : Intermediate;
     }
 }
Properties
b
int QIntValidator::b private
Definition at line 126 of file qvalidator.h.
Referenced by QIntValidator(), setRange(), and validate().
bottom
QIntValidator::bottom private
the validator's lowest acceptable value
By default, this property's value is derived from the lowest signed integer available (typically -2147483647).
See also
setRange()
Definition at line 99 of file qvalidator.h.
t
int QIntValidator::t private
Definition at line 127 of file qvalidator.h.
Referenced by QIntValidator(), setRange(), and validate().
top
QIntValidator::top private
the validator's highest acceptable value
By default, this property's value is derived from the highest signed integer available (typically 2147483647).
See also
setRange()
Definition at line 100 of file qvalidator.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qvalidator.h
/src/gui/widgets/qvalidator.cpp