Qt 4.8: QVGCompositionHelper Class Reference
QVGCompositionHelper Class Reference
#include <qvgcompositionhelper_p.h>
Public Functions
void blitWindow (VGImage image, const QSize &imageSize, const QRect &rect, const QPoint &topLeft, int opacity)
void clearScissor ()
void drawCursorPixmap (const QPixmap &pixmap, const QPoint &offset)
void endCompositing ()
void fillBackground (const QRegion &region, const QBrush &brush)
QVGCompositionHelper ()
void setScissor (const QRegion &region)
void startCompositing (const QSize &screenSize)
virtual ~QVGCompositionHelper ()
Properties
QVGPaintEnginePrivate * d
QSize screenSize
Detailed Description
Definition at line 65 of file qvgcompositionhelper_p.h.
Constructors and Destructors
QVGCompositionHelper()
QVGCompositionHelper::QVGCompositionHelper ()
Definition at line 3990 of file qpaintengine_vg.cpp.
 {
     d = qt_vg_create_paint_engine()->vgPrivate();
 }
~QVGCompositionHelper()
QVGCompositionHelper::~QVGCompositionHelper () virtual
Definition at line 3995 of file qpaintengine_vg.cpp.
 {
 }
Functions
blitWindow()
void QVGCompositionHelper::blitWindow (VGImage image, const QSize & imageSize, const QRect & rect, const QPoint & topLeft, int opacity)
Definition at line 4012 of file qpaintengine_vg.cpp.
Referenced by endCompositing().
 {
     if (image == VG_INVALID_HANDLE)
         return;
     // Determine which sub rectangle of the window to draw.
     QRect sr = rect.translated(-topLeft);
     if (opacity >= 255) {
         // Fully opaque: use vgSetPixels() to directly copy the sub-region.
         int y = screenSize.height() - (rect.bottom() + 1);
         vgSetPixels(rect.x(), y, image, sr.x(),
                     imageSize.height() - (sr.y() + sr.height()),
                     sr.width(), sr.height());
     } else {
         // Extract the child image that we want to draw.
         VGImage child;
         if (sr.topLeft().isNull() && sr.size() == imageSize)
             child = image;
         else {
             child = vgChildImage
                 (image, sr.x(), imageSize.height() - (sr.y() + sr.height()),
                  sr.width(), sr.height());
         }
         // Set the image transform.
         QTransform transform;
         int y = screenSize.height() - (rect.bottom() + 1);
         transform.translate(rect.x() - 0.5f, y - 0.5f);
         d->setTransform(VG_MATRIX_IMAGE_USER_TO_SURFACE, transform);
         // Enable opacity for image drawing if necessary.
         if (opacity != d->paintOpacity) {
             VGfloat values[4];
             values[0] = 1.0f;
             values[1] = 1.0f;
             values[2] = 1.0f;
             values[3] = ((VGfloat)opacity) / 255.0f;
             vgSetParameterfv(d->opacityPaint, VG_PAINT_COLOR, 4, values);
             d->paintOpacity = values[3];
         }
         if (d->fillPaint != d->opacityPaint) {
             vgSetPaint(d->opacityPaint, VG_FILL_PATH);
             d->fillPaint = d->opacityPaint;
         }
         d->setImageMode(VG_DRAW_IMAGE_MULTIPLY);
         // Draw the child image.
         vgDrawImage(child);
         // Destroy the child image.
         if(child != image)
             vgDestroyImage(child);
     }
 }
clearScissor()
void QVGCompositionHelper::clearScissor ()
Definition at line 4228 of file qpaintengine_vg.cpp.
 {
     if (d->scissorActive || d->scissorDirty) {
         vgSeti(VG_SCISSORING, VG_FALSE);
         d->scissorActive = false;
         d->scissorDirty = false;
     }
 }
drawCursorPixmap()
void QVGCompositionHelper::drawCursorPixmap (const QPixmap & pixmap, const QPoint & offset)
Definition at line 4161 of file qpaintengine_vg.cpp.
Referenced by fillBackground().
 {
     VGImage vgImage = VG_INVALID_HANDLE;
     // Fetch the VGImage from the pixmap if possible.
     QPixmapData *pd = pixmap.pixmapData();
     if (!pd)
         return; // null QPixmap
     if (pd->classId() == QPixmapData::OpenVGClass) {
         QVGPixmapData *vgpd = static_cast<QVGPixmapData *>(pd);
         if (vgpd->isValid())
             vgImage = vgpd->toVGImage();
     }
     // Set the image transformation and modes.
     VGfloat devh = screenSize.height();
     QTransform transform(1.0f, 0.0f, 0.0f,
                          0.0f, -1.0f, 0.0f,
                          0.0f, devh, 1.0f);
     transform.translate(offset.x(), offset.y());
     d->setTransform(VG_MATRIX_IMAGE_USER_TO_SURFACE, transform);
     d->setImageMode(VG_DRAW_IMAGE_NORMAL);
     // Draw the VGImage.
     if (vgImage != VG_INVALID_HANDLE) {
         vgDrawImage(vgImage);
     } else {
         QImage img = pixmap.toImage().convertToFormat
             (QImage::Format_ARGB32_Premultiplied);
         vgImage = vgCreateImage
             (VG_sARGB_8888_PRE, img.width(), img.height(),
              VG_IMAGE_QUALITY_FASTER);
         if (vgImage == VG_INVALID_HANDLE)
             return;
         vgImageSubData
             (vgImage, img.constBits() + img.bytesPerLine() * (img.height() - 1),
              -(img.bytesPerLine()), VG_sARGB_8888_PRE, 0, 0,
              img.width(), img.height());
         vgDrawImage(vgImage);
         vgDestroyImage(vgImage);
     }
 }
endCompositing()
void QVGCompositionHelper::endCompositing ()
Definition at line 4006 of file qpaintengine_vg.cpp.
 {
     clearScissor();
 }
fillBackground()
void QVGCompositionHelper::fillBackground (const QRegion & region, const QBrush & brush)
Definition at line 4107 of file qpaintengine_vg.cpp.
Referenced by fillBackgroundRect().
 {
     if (brush.style() == Qt::SolidPattern) {
         // Use vgClear() to quickly fill the background.
         QColor color = brush.color();
         if (d->clearColor != color || d->clearOpacity != 1.0f) {
             VGfloat values[4];
             values[0] = color.redF();
             values[1] = color.greenF();
             values[2] = color.blueF();
             values[3] = color.alphaF();
             vgSetfv(VG_CLEAR_COLOR, 4, values);
             d->clearColor = color;
             d->clearOpacity = 1.0f;
         }
         if (region.rectCount() == 1) {
             QRect r = region.boundingRect();
             vgClear(r.x(), screenSize.height() - r.y() - r.height(),
                     r.width(), r.height());
         } else {
             const QVector<QRect> rects = region.rects();
             for (int i = 0; i < rects.size(); ++i) {
                 QRect r = rects.at(i);
                 vgClear(r.x(), screenSize.height() - r.y() - r.height(),
                         r.width(), r.height());
             }
         }
     } else {
         // Set the path transform to the default viewport transformation.
         VGfloat devh = screenSize.height();
         QTransform viewport(1.0f, 0.0f, 0.0f,
                             0.0f, -1.0f, 0.0f,
                             0.0f, devh, 1.0f);
         d->setTransform(VG_MATRIX_PATH_USER_TO_SURFACE, viewport);
         // Set the brush to use to fill the background.
         d->ensureBrush(brush);
         d->setFillRule(VG_EVEN_ODD);
         if (region.rectCount() == 1) {
             fillBackgroundRect(region.boundingRect(), d);
         } else {
             const QVector<QRect> rects = region.rects();
             for (int i = 0; i < rects.size(); ++i)
                 fillBackgroundRect(rects.at(i), d);
         }
         // We will need to reset the path transform during the next paint.
         d->pathTransformSet = false;
     }
 }
setScissor()
void QVGCompositionHelper::setScissor (const QRegion & region)
Definition at line 4206 of file qpaintengine_vg.cpp.
 {
     QVector<QRect> rects = region.rects();
     int count = rects.count();
     if (count > d->maxScissorRects)
         count = d->maxScissorRects;
     QVarLengthArray<VGint> params(count * 4);
     int height = screenSize.height();
     for (int i = 0; i < count; ++i) {
         params[i * 4 + 0] = rects[i].x();
         params[i * 4 + 1] = height - rects[i].y() - rects[i].height();
         params[i * 4 + 2] = rects[i].width();
         params[i * 4 + 3] = rects[i].height();
     }
     vgSetiv(VG_SCISSOR_RECTS, count * 4, params.data());
     vgSeti(VG_SCISSORING, VG_TRUE);
     d->scissorDirty = false;
     d->scissorActive = true;
     d->scissorRegion = region;
 }
startCompositing()
void QVGCompositionHelper::startCompositing (const QSize & screenSize)
Definition at line 3999 of file qpaintengine_vg.cpp.
 {
     this->screenSize = screenSize;
     clearScissor();
     d->setBlendMode(VG_BLEND_SRC_OVER);
 }
Properties
d
QVGPaintEnginePrivate* QVGCompositionHelper::d private
Definition at line 82 of file qvgcompositionhelper_p.h.
screenSize
QSize QVGCompositionHelper::screenSize private
Definition at line 83 of file qvgcompositionhelper_p.h.
The documentation for this class was generated from the following files:
/src/openvg/qvgcompositionhelper_p.h
/src/openvg/qpaintengine_vg.cpp