Qt 4.8: QHttpPartPrivate Class Reference
QHttpPartPrivate Class Reference
#include <qhttpmultipart_p.h>
Public Functions
qint64 bytesAvailable () const
bool operator== (const QHttpPartPrivate &other) const
QHttpPartPrivate ()
QHttpPartPrivate (const QHttpPartPrivate &other)
qint64 readData (char *data, qint64 maxSize)
bool reset ()
void setBody (const QByteArray &newBody)
void setBodyDevice (QIODevice *device)
qint64 size () const
~QHttpPartPrivate ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QNetworkHeadersPrivate
RawHeadersList allRawHeaders () const
RawHeadersList::ConstIterator findRawHeader (const QByteArray &key) const
QList< QByteArray > rawHeadersKeys () const
void setAllRawHeaders (const RawHeadersList &list)
Sets the internal raw headers list to match list.
void setCookedHeader (QNetworkRequest::KnownHeaders header, const QVariant &value)
void setRawHeader (const QByteArray &key, const QByteArray &value)
Public Variables
QByteArray body
QIODevice * bodyDevice
Public Variables inherited from QSharedData
QAtomicInt ref
Public Variables inherited from QNetworkHeadersPrivate
AttributesMap attributes
CookedHeadersMap cookedHeaders
QWeakPointer< QObject > originatingObject
RawHeadersList rawHeaders
Private Functions
void checkHeaderCreated () const
Properties
QByteArray header
bool headerCreated
qint64 readPointer
Additional Inherited Members
Public Types inherited from QNetworkHeadersPrivate
typedef QHash< QNetworkRequest::Attribute, QVariant > AttributesMap
typedef QHash< QNetworkRequest::KnownHeaders, QVariant > CookedHeadersMap
typedef QPair< QByteArray, QByteArray > RawHeaderPair
typedef QList< RawHeaderPair > RawHeadersList
Static Public Functions inherited from QNetworkHeadersPrivate
static QDateTime fromHttpDate (const QByteArray &value)
static QByteArray toHttpDate (const QDateTime &dt)
Detailed Description
Definition at line 63 of file qhttpmultipart_p.h.
Constructors and Destructors
QHttpPartPrivate() [1/2]
QHttpPartPrivate::QHttpPartPrivate () inline
Definition at line 66 of file qhttpmultipart_p.h.
                               : bodyDevice(0), headerCreated(false), readPointer(0)
     {
     }
~QHttpPartPrivate()
QHttpPartPrivate::~QHttpPartPrivate () inline
Definition at line 69 of file qhttpmultipart_p.h.
     {
     }
QHttpPartPrivate() [2/2]
QHttpPartPrivate::QHttpPartPrivate (const QHttpPartPrivate & other) inline
Definition at line 74 of file qhttpmultipart_p.h.
         : QSharedData(other), QNetworkHeadersPrivate(other), body(other.body),
         header(other.header), headerCreated(other.headerCreated), readPointer(other.readPointer)
     {
         bodyDevice = other.bodyDevice;
     }
Functions
bytesAvailable()
qint64 QHttpPartPrivate::bytesAvailable () const
Definition at line 358 of file qhttpmultipart.cpp.
Referenced by setBody().
 {
     checkHeaderCreated();
     qint64 bytesAvailable = header.count();
     if (bodyDevice) {
         bytesAvailable += bodyDevice->bytesAvailable() - readPointer;
     } else {
         bytesAvailable += body.count() - readPointer;
     }
     // the device might have closed etc., so make sure we do not return a negative value
     return qMax(bytesAvailable, (qint64) 0);
 }
checkHeaderCreated()
void QHttpPartPrivate::checkHeaderCreated () const private
Definition at line 426 of file qhttpmultipart.cpp.
 {
     if (!headerCreated) {
         // copied from QHttpNetworkRequestPrivate::header() and adapted
         QList<QPair<QByteArray, QByteArray> > fields = allRawHeaders();
         QList<QPair<QByteArray, QByteArray> >::const_iterator it = fields.constBegin();
         for (; it != fields.constEnd(); ++it)
             header += it->first + ": " + it->second + "\r\n";
         header += "\r\n";
         headerCreated = true;
     }
 }
operator==()
bool QHttpPartPrivate::operator== (const QHttpPartPrivate & other) const inline
Definition at line 81 of file qhttpmultipart_p.h.
     {
         return rawHeaders == other.rawHeaders && body == other.body &&
                 bodyDevice == other.bodyDevice && readPointer == other.readPointer;
     }
readData()
qint64 QHttpPartPrivate::readData (char * data, qint64 maxSize)
Definition at line 371 of file qhttpmultipart.cpp.
Referenced by QHttpMultiPartIODevice::bytesToWrite(), and setBody().
 {
     checkHeaderCreated();
     qint64 bytesRead = 0;
     qint64 headerDataCount = header.count();
     // read header if it has not been read yet
     if (readPointer < headerDataCount) {
         bytesRead = qMin(headerDataCount - readPointer, maxSize);
         const char *headerData = header.constData();
         memcpy(data, headerData + readPointer, bytesRead);
         readPointer += bytesRead;
     }
     // read content if there is still space
     if (bytesRead < maxSize) {
         if (bodyDevice) {
             qint64 dataBytesRead = bodyDevice->read(data + bytesRead, maxSize - bytesRead);
             if (dataBytesRead == -1)
                 return -1;
             bytesRead += dataBytesRead;
             readPointer += dataBytesRead;
         } else {
             qint64 contentBytesRead = qMin(body.count() - readPointer + headerDataCount, maxSize - bytesRead);
             const char *contentData = body.constData();
             // if this method is called several times, we need to find the
             // right offset in the content ourselves:
             memcpy(data + bytesRead, contentData + readPointer - headerDataCount, contentBytesRead);
             bytesRead += contentBytesRead;
             readPointer += contentBytesRead;
         }
     }
     return bytesRead;
 }
reset()
bool QHttpPartPrivate::reset ()
Definition at line 417 of file qhttpmultipart.cpp.
Referenced by QHttpMultiPartIODevice::bytesToWrite(), and setBody().
 {
     bool ret = true;
     if (bodyDevice)
         if (!bodyDevice->reset())
             ret = false;
     readPointer = 0;
     return ret;
 }
setBody()
void QHttpPartPrivate::setBody (const QByteArray & newBody) inline
Definition at line 91 of file qhttpmultipart_p.h.
Referenced by QHttpPart::setBody().
{
         body = newBody;
         readPointer = 0;
     }
setBodyDevice()
void QHttpPartPrivate::setBodyDevice (QIODevice * device) inline
Definition at line 87 of file qhttpmultipart_p.h.
Referenced by QHttpPart::setBodyDevice().
{
         bodyDevice = device;
         readPointer = 0;
     }
size()
qint64 QHttpPartPrivate::size () const
Definition at line 405 of file qhttpmultipart.cpp.
Referenced by QHttpMultiPartIODevice::atEnd(), QHttpMultiPartIODevice::bytesAvailable(), QHttpMultiPartIODevice::bytesToWrite(), QHttpMultiPartIODevice::readData(), and setBody().
 {
     checkHeaderCreated();
     qint64 size = header.count();
     if (bodyDevice) {
         size += bodyDevice->size();
     } else {
         size += body.count();
     }
     return size;
 }
Properties
body
QByteArray QHttpPartPrivate::body
Definition at line 103 of file qhttpmultipart_p.h.
Referenced by operator==(), and setBody().
bodyDevice
QIODevice* QHttpPartPrivate::bodyDevice
Definition at line 104 of file qhttpmultipart_p.h.
Referenced by operator==(), QHttpPartPrivate(), and setBodyDevice().
header
QByteArray QHttpPartPrivate::header mutable private
Definition at line 109 of file qhttpmultipart_p.h.
headerCreated
bool QHttpPartPrivate::headerCreated mutable private
Definition at line 110 of file qhttpmultipart_p.h.
readPointer
qint64 QHttpPartPrivate::readPointer private
Definition at line 111 of file qhttpmultipart_p.h.
Referenced by QHttpMultiPartIODevice::atEnd(), QHttpMultiPartIODevice::bytesAvailable(), QHttpMultiPartIODevice::close(), operator==(), setBody(), and setBodyDevice().
The documentation for this class was generated from the following files:
/src/network/access/qhttpmultipart_p.h
/src/network/access/qhttpmultipart.cpp