Qt 4.8: QValidator Class Reference
QValidator Class Reference abstract
The QValidator class provides validation of input text.
#include <qvalidator.h>
Public Types
enum State { Invalid, Intermediate, Acceptable }
This enum type defines the states in which a validated string can exist.
Public Functions
virtual void fixup (QString &) const
This function attempts to change input to be valid according to this validator's rules.
QLocale locale () const
Returns the locale for the validator.
QValidator (QObject *parent=0)
Sets up the validator.
void setLocale (const QLocale &locale)
Sets the locale that will be used for the validator.
virtual State validate (QString &, int &) const =0
This virtual function returns Invalid if input is invalid according to this validator's rules, Intermediate if it is likely that a little more editing will make the input acceptable (e.
~QValidator ()
Destroys the validator, freeing any storage and other resources used.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QValidator (QObjectPrivate &d, QObject *parent)
QValidator (QValidatorPrivate &d, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QValidator class provides validation of input text.
The class itself is abstract. Two subclasses, QIntValidator and QDoubleValidator , provide basic numeric-range checking, and QRegExpValidator provides general checking using a custom regular expression.
If the built-in validators aren't sufficient, you can subclass QValidator. The class has two virtual functions: validate() and fixup().
validate() must be implemented by every subclass. It returns Invalid , Intermediate or Acceptable depending on whether its argument is valid (for the subclass's definition of valid).
These three states require some explanation. An Invalid string is clearly invalid. Intermediate is less obvious: the concept of validity is difficult to apply when the string is incomplete (still being edited). QValidator defines Intermediate as the property of a string that is neither clearly invalid nor acceptable as a final result. Acceptable means that the string is acceptable as a final result. One might say that any string that is a plausible intermediate state during entry of an Acceptable string is Intermediate .
Here are some examples:
For a line edit that accepts integers from 10 to 1000 inclusive, 42 and 123 are Acceptable , the empty string and 5 are Intermediate , and "asdf" and 1114 is Invalid .
For an editable combobox that accepts URLs, any well-formed URL is Acceptable , "http://example.com/," is Intermediate (it might be a cut and paste action that accidentally took in a comma at the end), the empty string is Intermediate (the user might select and delete all of the text in preparation for entering a new URL) and "http:///./" is Invalid .
For a spin box that accepts lengths, "11cm" and "1in" are Acceptable , "11" and the empty string are Intermediate , and "http://example.com" and "hour" are Invalid .
fixup() is provided for validators that can repair some user errors. The default implementation does nothing. QLineEdit, for example, will call fixup() if the user presses Enter (or Return) and the content is not currently valid. This allows the fixup() function the opportunity of performing some magic to make an Invalid string Acceptable .
A validator has a locale, set with setLocale(). It is typically used to parse localized data. For example, QIntValidator and QDoubleValidator use it to parse localized representations of integers and doubles.
QValidator is typically used with QLineEdit, QSpinBox and QComboBox.
See also
QIntValidator, QDoubleValidator, QRegExpValidator, {Line Edits Example}
Definition at line 60 of file qvalidator.h.
Enumerations
State
enum QValidator::State
This enum type defines the states in which a validated string can exist.
Invalid The string is clearly invalid.
Intermediate The string is a plausible intermediate value.
Acceptable The string is acceptable as a final result; i.e. it is valid.
Valid
Enumerator
Invalid
Intermediate
Acceptable
Definition at line 67 of file qvalidator.h.
                {
         Invalid,
         Intermediate,
         Acceptable
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         , Valid = Intermediate
 #endif
     };
Constructors and Destructors
QValidator() [1/3]
QValidator::QValidator (QObject * parent = 0) explicit
Sets up the validator.
The parent parameter is passed on to the QObject constructor.
Definition at line 151 of file qvalidator.cpp.
Referenced by QDoubleValidator::QDoubleValidator(), QIntValidator::QIntValidator(), and QRegExpValidator::QRegExpValidator().
     : QObject(*new QValidatorPrivate, parent)
 {
 }
~QValidator()
QValidator::~QValidator ()
Destroys the validator, freeing any storage and other resources used.
Definition at line 178 of file qvalidator.cpp.
 {
 }
QValidator() [2/3]
QValidator::QValidator (QObjectPrivate & d, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 507 of file qvalidator.cpp.
         : QObject(d, parent)
 {
 }
QValidator() [3/3]
QValidator::QValidator (QValidatorPrivate & d, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 515 of file qvalidator.cpp.
         : QObject(d, parent)
 {
 }
Functions
fixup()
void QValidator::fixup (QString & input) const virtual
This function attempts to change input to be valid according to this validator's rules.
It need not result in a valid string: callers of this function must re-test afterwards; the default does nothing.
Reimplementations of this function can change input even if they do not produce a valid string. For example, an ISBN validator might want to delete every character except digits and "-", even if the result is still not a valid ISBN; a surname validator might want to remove whitespace from the start and end of the string, even if the resulting string is not in the list of accepted surnames.
Reimplemented in QSpinBoxValidator, and QIntValidator.
Definition at line 246 of file qvalidator.cpp.
Referenced by QLineControl::fixup().
 {
 }
locale()
QLocale QValidator::locale () const
Returns the locale for the validator.
The locale is by default initialized to the same as QLocale().
See also
setLocale()
QLocale::QLocale()
Definition at line 188 of file qvalidator.cpp.
Referenced by QIntValidator::fixup(), setLocale(), QIntValidator::validate(), and QDoubleValidator::validate().
 {
     Q_D(const QValidator);
     return d->locale;
 }
setLocale()
void QValidator::setLocale (const QLocale & locale)
Sets the locale that will be used for the validator.
Unless setLocale has been called, the validator will use the default locale set with QLocale::setDefault(). If a default locale has not been set, it is the operating system's locale.
See also
locale() QLocale::setDefault()
Definition at line 202 of file qvalidator.cpp.
 {
     Q_D(QValidator);
     d->locale = locale;
 }
validate()
QValidator::State QValidator::validate (QString & input, int & pos) const pure virtual
This virtual function returns Invalid if input is invalid according to this validator's rules, Intermediate if it is likely that a little more editing will make the input acceptable (e.
g. the user types "4" into a widget which accepts integers between 10 and 99), and Acceptable if the input is valid.
The function can change both input and pos (the cursor position) if required.
Implemented in QRegExpValidator, QSpinBoxValidator, QDoubleValidator, and QIntValidator.
Referenced by QLineControl::finishChange(), QLineControl::fixup(), and QLineControl::hasAcceptableInput().
The documentation for this class was generated from the following files:
/src/gui/widgets/qvalidator.h
/src/gui/widgets/qvalidator.cpp