Qt 4.8: QQueue< T > Class Template Reference
QQueue< T > Class Template Reference
The QQueue class is a generic container that provides a queue.
#include <qcontainerfwd.h>
Public Functions
T dequeue ()
Removes the head item in the queue and returns it.
void enqueue (const T &t)
Adds value t to the tail of the queue.
T & head ()
Returns a reference to the queue's head item.
const T & head () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QQueue ()
Constructs an empty queue.
void swap (QQueue< T > &other)
Swaps queue other with this queue.
~QQueue ()
Destroys the queue.
Public Functions inherited from QList< T >
void append (const T &t)
Inserts value at the end of the list.
void append (const QList< T > &t)
Appends the items of the value list to this list.
const T & at (int i) const
Returns the item at index position i in the list.
T & back ()
This function is provided for STL compatibility.
const T & back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the list.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all items from the list.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the list.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
QBool contains (const T &t) const
Returns true if the list contains an occurrence of value; otherwise returns false.
int count (const T &t) const
Returns the number of occurrences of value in the list.
int count () const
Returns the number of items in the list.
void detach ()
void detachShared ()
This prevents needless mallocs, and makes QList more exception safe in case of cleanup work done in destructors on empty lists.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const T &t) const
Returns true if this list is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator pos)
Removes the item associated with the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
iterator erase (iterator first, iterator last)
Removes all the items from begin up to (but not including) end.
T & first ()
Returns a reference to the first item in the list.
const T & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & front ()
This function is provided for STL compatibility.
const T & front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const T &t, int from=0) const
Returns the index position of the first occurrence of value in the list, searching forward from index position from.
void insert (int i, const T &t)
Inserts value at index position i in the list.
iterator insert (iterator before, const T &t)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the list contains no items; otherwise returns false.
bool isSharedWith (const QList< T > &other) const
T & last ()
Returns a reference to the last item in the list.
const T & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const T &t, int from=-1) const
Returns the index position of the last occurrence of value in the list, searching backward from index position from.
int length () const
This function is identical to count().
QList< T > mid (int pos, int length=-1) const
Returns a list whose elements are copied from this list, starting at position pos.
void move (int from, int to)
Moves the item at index position from to index position to.
bool operator!= (const QList< T > &l) const
Returns true if other is not equal to this list; otherwise returns false.
QList< T > operator+ (const QList< T > &l) const
Returns a list that contains all the items in this list followed by all the items in the other list.
QList< T > & operator+= (const QList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< T > & operator+= (const T &t)
Appends value to the list.
QList< T > & operator<< (const QList< T > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< T > & operator<< (const T &t)
Appends value to the list.
QList< T > & operator= (const QList< T > &l)
Assigns other to this list and returns a reference to this list.
bool operator== (const QList< T > &l) const
Returns true if other is equal to this list; otherwise returns false.
const T & operator[] (int i) const
Same as at().
T & operator[] (int i)
Returns the item at index position i as a modifiable reference.
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const T &t)
Inserts value at the beginning of the list.
void push_back (const T &t)
This function is provided for STL compatibility.
void push_front (const T &t)
This function is provided for STL compatibility.
QList ()
Constructs an empty list.
QList (const QList< T > &l)
Constructs a copy of other.
int removeAll (const T &t)
Removes all occurrences of value in the list and returns the number of entries removed.
void removeAt (int i)
Removes the item at index position i.
void removeFirst ()
Removes the first item in the list.
void removeLast ()
Removes the last item in the list.
bool removeOne (const T &t)
Removes the first occurrence of value in the list and returns true on success; otherwise returns false.
void replace (int i, const T &t)
Replaces the item at index position i with value.
void reserve (int size)
Reserve space for alloc elements.
void setSharable (bool sharable)
int size () const
Returns the number of items in the list.
bool startsWith (const T &t) const
Returns true if this list is not empty and its first item is equal to value; otherwise returns false.
void swap (QList< T > &other)
Swaps list other with this list.
void swap (int i, int j)
Exchange the item at index position i with the item at index position j.
T takeAt (int i)
Removes the item at index position i and returns it.
T takeFirst ()
Removes the first item in the list and returns it.
T takeLast ()
Removes the last item in the list and returns it.
QSet< T > toSet () const
Returns a QSet object with the data contained in this QList.
std::list< T > toStdList () const
Returns a std::list object with the data contained in this QList.
QVector< T > toVector () const
Returns a QVector object with the data contained in this QList.
T value (int i) const
Returns the value at index position i in the list.
T value (int i, const T &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QList ()
Destroys the list.
Additional Inherited Members
Public Types inherited from QList< T >
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for const T &.
typedef const_iterator ConstIterator
Qt-style synonym for QList::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QList::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef T value_type
Typedef for T.
Static Public Functions inherited from QList< T >
static QList< T > fromSet (const QSet< T > &set)
Returns a QList object with the data contained in set.
static QList< T > fromStdList (const std::list< T > &list)
Returns a QList object with the data contained in list.
static QList< T > fromVector (const QVector< T > &vector)
Returns a QList object with the data contained in vector.
Related Functions inherited from QList< T >
QDataStream & operator<< (QDataStream &out, const QList< T > &list)
Writes the list list to stream out.
QDataStream & operator>> (QDataStream &in, QList< T > &list)
Reads a list from stream in into list.
Detailed Description
template<class T>
class QQueue< T >
The QQueue class is a generic container that provides a queue.
Note
This class or function is reentrant.
QQueue<T> is one of Qt's generic container classes. It implements a queue data structure for items of a same type.
A queue is a first in, first out (FIFO) structure. Items are added to the tail of the queue using enqueue() and retrieved from the head using dequeue(). The head() function provides access to the head item without removing it.
Example:
QQueue<int> queue;
queue.enqueue(1);
queue.enqueue(2);
queue.enqueue(3);
while (!queue.isEmpty())
    cout << queue.dequeue() << endl;
The example will output 1, 2, 3 in that order.
QQueue inherits from QList. All of QList's functionality also applies to QQueue. For example, you can use isEmpty() to test whether the queue is empty, and you can traverse a QQueue using QList's iterator classes (for example, QListIterator). But in addition, QQueue provides three convenience functions that make it easy to implement FIFO semantics: enqueue(), dequeue(), and head().
QQueue's value type must be an assignable data type. This covers most data types that are commonly used, but the compiler won't let you, for example, store a QWidget as a value. Use QWidget* instead.
See also
QList, QStack
Definition at line 61 of file qcontainerfwd.h.
Constructors and Destructors
QQueue()
template<class T> QQueue< T >::QQueue () inline
Constructs an empty queue.
Definition at line 57 of file qqueue.h.
 {}
~QQueue()
template<class T> QQueue< T >::~QQueue () inline
Destroys the queue.
References to the values in the queue, and all iterators over this queue, become invalid.
Definition at line 58 of file qqueue.h.
 {}
Functions
dequeue()
template<class T> T QQueue< T >::dequeue () inline
Removes the head item in the queue and returns it.
This function assumes that the queue isn't empty.
This is the same as QList::takeFirst().
See also
head(), enqueue(), isEmpty()
Definition at line 61 of file qqueue.h.
Referenced by QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QGraphicsAnchorLayoutPrivate::findPaths(), QNetworkReplyImplPrivate::handleNotifications(), QPatternist::XSLTTokenizer::nextToken(), QNetworkAccessCache::releaseEntry(), and QThreadPoolPrivate::tryStart().
 { return QList<T>::takeFirst(); }
enqueue()
template<class T> void QQueue< T >::enqueue (const T & t) inline
Adds value t to the tail of the queue.
This is the same as QList::append().
See also
dequeue(), head()
Definition at line 60 of file qqueue.h.
Referenced by QNetworkReplyImplPrivate::backendNotify(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QGraphicsAnchorLayoutPrivate::findPaths(), QPatternist::XSLTTokenizer::queueAVT(), QPatternist::XSLTTokenizer::queueExpression(), QPatternist::XSLTTokenizer::queueSequenceType(), QPatternist::XSLTTokenizer::queueToken(), QNetworkAccessCache::requestEntry(), QThreadPoolThread::run(), QHostInfoLookupManager::scheduleLookup(), and QUnixSocket::write().
 { QList<T>::append(t); }
head() [1/2]
template<class T> T & QQueue< T >::head () inline
Returns a reference to the queue's head item.
This function assumes that the queue isn't empty.
This is the same as QList::first().
See also
dequeue(), enqueue(), isEmpty()
Definition at line 62 of file qqueue.h.
Referenced by QPatternist::XSLTTokenizer::nextToken().
 { return QList<T>::first(); }
head() [2/2]
template<class T> const T & QQueue< T >::head () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 63 of file qqueue.h.
 { return QList<T>::first(); }
swap()
template<class T> void QQueue< T >::swap (QQueue< T > & other) inline
Swaps queue other with this queue.
Since
4.8
This operation is very fast and never fails.
Definition at line 59 of file qqueue.h.
 { QList<T>::swap(other); } // prevent QList<->QQueue swaps
The documentation for this class was generated from the following files:
/src/corelib/tools/qcontainerfwd.h
/src/corelib/tools/qqueue.h
/src/corelib/tools/qqueue.cpp