Qt 4.8: QDeclarativeJS::Parser Class Reference
QDeclarativeJS::Parser Class Reference
#include <qdeclarativejsparser_p.h>
Classes
struct SavedToken
union Value
Public Functions
AST::UiProgram * ast () const
DiagnosticMessage diagnosticMessage () const
QList< DiagnosticMessage > diagnosticMessages () const
int errorColumnNumber () const
int errorLineNumber () const
QString errorMessage () const
AST::ExpressionNode * expression () const
bool parse ()
bool parseExpression ()
bool parseProgram ()
Parser (Engine *engine)
bool parseSourceElement ()
bool parseStatement ()
bool parseUiObjectMember ()
AST::Node * rootNode () const
AST::Statement * statement () const
AST::UiObjectMember * uiObjectMember () const
~Parser ()
Protected Types
enum { TOKEN_BUFFER_SIZE = 3 }
Protected Types inherited from QDeclarativeJSGrammar
enum VariousConstants {
EOF_SYMBOL = 0, REDUCE_HERE = 100, SHIFT_THERE = 99, T_AND = 1,
T_AND_AND = 2, T_AND_EQ = 3, T_AS = 91, T_AUTOMATIC_SEMICOLON = 62,
T_BREAK = 4, T_CASE = 5, T_CATCH = 6, T_COLON = 7,
T_COMMA = 8, T_COMMENT = 88, T_CONST = 84, T_CONTINUE = 9,
T_DEBUGGER = 85, T_DEFAULT = 10, T_DELETE = 11, T_DIVIDE_ = 12,
T_DIVIDE_EQ = 13, T_DO = 14, T_DOT = 15, T_ELSE = 16,
T_EQ = 17, T_EQ_EQ = 18, T_EQ_EQ_EQ = 19, T_FALSE = 83,
T_FEED_JS_EXPRESSION = 96, T_FEED_JS_PROGRAM = 98, T_FEED_JS_SOURCE_ELEMENT = 97, T_FEED_JS_STATEMENT = 95,
T_FEED_UI_OBJECT_MEMBER = 94, T_FEED_UI_PROGRAM = 93, T_FINALLY = 20, T_FOR = 21,
T_FUNCTION = 22, T_GE = 23, T_GT = 24, T_GT_GT = 25,
T_GT_GT_EQ = 26, T_GT_GT_GT = 27, T_GT_GT_GT_EQ = 28, T_IDENTIFIER = 29,
T_IF = 30, T_IMPORT = 90, T_IN = 31, T_INSTANCEOF = 32,
T_LBRACE = 33, T_LBRACKET = 34, T_LE = 35, T_LPAREN = 36,
T_LT = 37, T_LT_LT = 38, T_LT_LT_EQ = 39, T_MINUS = 40,
T_MINUS_EQ = 41, T_MINUS_MINUS = 42, T_MULTILINE_STRING_LITERAL = 87, T_NEW = 43,
T_NOT = 44, T_NOT_EQ = 45, T_NOT_EQ_EQ = 46, T_NULL = 81,
T_NUMERIC_LITERAL = 47, T_ON = 92, T_OR = 48, T_OR_EQ = 49,
T_OR_OR = 50, T_PLUS = 51, T_PLUS_EQ = 52, T_PLUS_PLUS = 53,
T_PROPERTY = 66, T_PUBLIC = 89, T_QUESTION = 54, T_RBRACE = 55,
T_RBRACKET = 56, T_READONLY = 68, T_REMAINDER = 57, T_REMAINDER_EQ = 58,
T_RESERVED_WORD = 86, T_RETURN = 59, T_RPAREN = 60, T_SEMICOLON = 61,
T_SIGNAL = 67, T_STAR = 63, T_STAR_EQ = 64, T_STRING_LITERAL = 65,
T_SWITCH = 69, T_THIS = 70, T_THROW = 71, T_TILDE = 72,
T_TRUE = 82, T_TRY = 73, T_TYPEOF = 74, T_VAR = 75,
T_VOID = 76, T_WHILE = 77, T_WITH = 78, T_XOR = 79,
T_XOR_EQ = 80, ACCEPT_STATE = 645, RULE_COUNT = 347, STATE_COUNT = 646,
TERMINAL_COUNT = 101, NON_TERMINAL_COUNT = 106, GOTO_INDEX_OFFSET = 646, GOTO_INFO_OFFSET = 2714,
GOTO_CHECK_OFFSET = 2714
}
Protected Functions
AST::SourceLocation & loc (int index)
bool parse (int startToken)
void reallocateStack ()
AST::UiQualifiedId * reparseAsQualifiedId (AST::ExpressionNode *expr)
Value & sym (int index)
Protected Variables
QList< DiagnosticMessage > diagnostic_messages
Engine * driver
SavedToken * first_token
SavedToken * last_token
AST::SourceLocation * location_stack
AST::Node * program
int stack_size
int * state_stack
Value * sym_stack
SavedToken token_buffer [TOKEN_BUFFER_SIZE]
int tos
AST::SourceLocation yylloc
double yylval
AST::SourceLocation yyprevlloc
Additional Inherited Members
Static Protected Functions inherited from QDeclarativeJSGrammar
static int nt_action (int state, int nt)
static int t_action (int state, int token)
Static Protected Variables inherited from QDeclarativeJSGrammar
static const short action_check []
static const short action_default []
static const short action_index []
static const short action_info []
static const short goto_default []
static const short lhs []
static const short rhs []
static const char *const spell []
Detailed Description
Definition at line 77 of file qdeclarativejsparser_p.h.
Enumerations
anonymous enum
anonymous enum protected
Enumerator
TOKEN_BUFFER_SIZE
Definition at line 215 of file qdeclarativejsparser_p.h.
 { TOKEN_BUFFER_SIZE = 3 };
Constructors and Destructors
Parser()
Parser::Parser (Engine * engine)
Definition at line 86 of file qdeclarativejsparser.cpp.
                             :
     driver(engine),
     tos(0),
     stack_size(0),
     sym_stack(0),
     state_stack(0),
     location_stack(0),
     first_token(0),
     last_token(0)
 {
 }
~Parser()
Parser::~Parser ()
Definition at line 98 of file qdeclarativejsparser.cpp.
 {
     if (stack_size) {
         qFree(sym_stack);
         qFree(state_stack);
         qFree(location_stack);
     }
 }
Functions
ast()
AST::UiProgram* QDeclarativeJS::Parser::ast () const inline
Definition at line 139 of file qdeclarativejsparser_p.h.
Referenced by QDeclarativeScriptParser::parse().
     { return AST::cast<AST::UiProgram *>(program); }
diagnosticMessage()
DiagnosticMessage QDeclarativeJS::Parser::diagnosticMessage () const inline
Definition at line 172 of file qdeclarativejsparser_p.h.
     {
         foreach (const DiagnosticMessage &d, diagnostic_messages) {
             if (! d.kind == DiagnosticMessage::Warning)
                 return d;
         }
         return DiagnosticMessage();
     }
diagnosticMessages()
QList<DiagnosticMessage> QDeclarativeJS::Parser::diagnosticMessages () const inline
Definition at line 169 of file qdeclarativejsparser_p.h.
Referenced by QDeclarativeScriptParser::parse().
     { return diagnostic_messages; }
errorColumnNumber()
int QDeclarativeJS::Parser::errorColumnNumber () const inline
Definition at line 188 of file qdeclarativejsparser_p.h.
     { return diagnosticMessage().loc.startColumn; }
errorLineNumber()
int QDeclarativeJS::Parser::errorLineNumber () const inline
Definition at line 185 of file qdeclarativejsparser_p.h.
     { return diagnosticMessage().loc.startLine; }
errorMessage()
QString QDeclarativeJS::Parser::errorMessage () const inline
Definition at line 182 of file qdeclarativejsparser_p.h.
     { return diagnosticMessage().message; }
expression()
AST::ExpressionNode* QDeclarativeJS::Parser::expression () const inline
Definition at line 150 of file qdeclarativejsparser_p.h.
     {
         if (! program)
             return 0;
         return program->expressionCast();
     }
loc()
AST::SourceLocation& QDeclarativeJS::Parser::loc (int index) inline protected
Definition at line 199 of file qdeclarativejsparser_p.h.
Referenced by location(), and parse().
     { return location_stack [tos + index - 1]; }
parse() [1/2]
bool QDeclarativeJS::Parser::parse () inline
Definition at line 132 of file qdeclarativejsparser_p.h.
Referenced by QDeclarativeScriptParser::parse(), and parse().
 { return parse(T_FEED_UI_PROGRAM); }
parse() [2/2]
bool Parser::parse (int startToken) protected
Definition at line 145 of file qdeclarativejsparser.cpp.
 {
     Lexer *lexer = driver->lexer();
     bool hadErrors = false;
     int yytoken = -1;
     int action = 0;
     token_buffer[0].token = startToken;
     first_token = &token_buffer[0];
     last_token = &token_buffer[1];
     tos = -1;
     program = 0;
     do {
         if (++tos == stack_size)
             reallocateStack();
         state_stack[tos] = action;
     _Lcheck_token:
         if (yytoken == -1 && -TERMINAL_COUNT != action_index[action]) {
             yyprevlloc = yylloc;
             if (first_token == last_token) {
                 yytoken = lexer->lex();
                 yylval = lexer->dval();
                 yylloc = location(lexer);
             } else {
                 yytoken = first_token->token;
                 yylval = first_token->dval;
                 yylloc = first_token->loc;
                 ++first_token;
             }
         }
         action = t_action(action, yytoken);
         if (action > 0) {
             if (action != ACCEPT_STATE) {
                 yytoken = -1;
                 sym(1).dval = yylval;
                 loc(1) = yylloc;
             } else {
               --tos;
               return ! hadErrors;
             }
         } else if (action < 0) {
           const int r = -action - 1;
           tos -= rhs[r];
           switch (r) {
 case 0: {
   sym(1).Node = sym(2).Node;
   program = sym(1).Node;
 } break;
 case 1: {
   sym(1).Node = sym(2).Node;
   program = sym(1).Node;
 } break;
 case 2: {
   sym(1).Node = sym(2).Node;
   program = sym(1).Node;
 } break;
 case 3: {
   sym(1).Node = sym(2).Node;
   program = sym(1).Node;
 } break;
 case 4: {
   sym(1).Node = sym(2).Node;
   program = sym(1).Node;
 } break;
 case 5: {
   sym(1).Node = sym(2).Node;
   program = sym(1).Node;
 } break;
 case 6: {
   sym(1).UiProgram = makeAstNode<AST::UiProgram> (driver->nodePool(), sym(1).UiImportList,
         sym(2).UiObjectMemberList->finish());
 } break;
 case 8: {
     sym(1).Node = sym(1).UiImportList->finish();
 } break;
 case 9: {
     sym(1).Node = makeAstNode<AST::UiImportList> (driver->nodePool(), sym(1).UiImport);
 } break;
 case 10: {
     sym(1).Node = makeAstNode<AST::UiImportList> (driver->nodePool(),
         sym(1).UiImportList, sym(2).UiImport);
 } break;
 case 13: {
     sym(1).UiImport->semicolonToken = loc(2);
 } break;
 case 15: {
     sym(1).UiImport->versionToken = loc(2);
     sym(1).UiImport->semicolonToken = loc(3);
 } break;
 case 17: {
     sym(1).UiImport->versionToken = loc(2);
     sym(1).UiImport->asToken = loc(3);
     sym(1).UiImport->importIdToken = loc(4);
     sym(1).UiImport->importId = sym(4).sval;
     sym(1).UiImport->semicolonToken = loc(5);
 } break;
 case 19: {
     sym(1).UiImport->asToken = loc(2);
     sym(1).UiImport->importIdToken = loc(3);
     sym(1).UiImport->importId = sym(3).sval;
     sym(1).UiImport->semicolonToken = loc(4);
 } break;
 case 20: {
     AST::UiImport *node = 0;
     if (AST::StringLiteral *importIdLiteral = AST::cast<AST::StringLiteral *>(sym(2).Expression)) {
         node = makeAstNode<AST::UiImport>(driver->nodePool(), importIdLiteral->value);
         node->fileNameToken = loc(2);
     } else if (AST::UiQualifiedId *qualifiedId = reparseAsQualifiedId(sym(2).Expression)) {
         node = makeAstNode<AST::UiImport>(driver->nodePool(), qualifiedId);
         node->fileNameToken = loc(2);
     }
     sym(1).Node = node;
     if (node) {
         node->importToken = loc(1);
     } else {
        diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, loc(1),
          QLatin1String("Expected a qualified name id or a string literal")));
         return false; // ### remove me
     }
 } break;
 case 21: {
     sym(1).Node = 0;
 } break;
 case 22: {
     sym(1).Node = makeAstNode<AST::UiObjectMemberList> (driver->nodePool(), sym(1).UiObjectMember);
 } break;
 case 23: {
     sym(1).Node = makeAstNode<AST::UiObjectMemberList> (driver->nodePool(), sym(1).UiObjectMember);
 } break;
 case 24: {
     AST::UiObjectMemberList *node = makeAstNode<AST:: UiObjectMemberList> (driver->nodePool(),
         sym(1).UiObjectMemberList, sym(2).UiObjectMember);
     sym(1).Node = node;
 } break;
 case 25: {
     sym(1).Node = makeAstNode<AST::UiArrayMemberList> (driver->nodePool(), sym(1).UiObjectMember);
 } break;
 case 26: {
     AST::UiArrayMemberList *node = makeAstNode<AST::UiArrayMemberList> (driver->nodePool(),
         sym(1).UiArrayMemberList, sym(3).UiObjectMember);
     node->commaToken = loc(2);
     sym(1).Node = node;
 } break;
 case 27: {
     AST::UiObjectInitializer *node = makeAstNode<AST::UiObjectInitializer> (driver->nodePool(), (AST::UiObjectMemberList*)0);
     node->lbraceToken = loc(1);
     node->rbraceToken = loc(2);
     sym(1).Node = node;
 }   break;
 case 28: {
     AST::UiObjectInitializer *node = makeAstNode<AST::UiObjectInitializer> (driver->nodePool(), sym(2).UiObjectMemberList->finish());
     node->lbraceToken = loc(1);
     node->rbraceToken = loc(3);
     sym(1).Node = node;
 }   break;
 case 29: {
     AST::UiObjectDefinition *node = makeAstNode<AST::UiObjectDefinition> (driver->nodePool(), sym(1).UiQualifiedId,
         sym(2).UiObjectInitializer);
     sym(1).Node = node;
 }   break;
 case 31: {
     AST::UiArrayBinding *node = makeAstNode<AST::UiArrayBinding> (driver->nodePool(),
         sym(1).UiQualifiedId, sym(4).UiArrayMemberList->finish());
     node->colonToken = loc(2);
     node->lbracketToken = loc(3);
     node->rbracketToken = loc(5);
     sym(1).Node = node;
 }   break;
 case 32: {
     AST::UiObjectBinding *node = makeAstNode<AST::UiObjectBinding> (driver->nodePool(),
       sym(1).UiQualifiedId, sym(3).UiQualifiedId, sym(4).UiObjectInitializer);
     node->colonToken = loc(2);
     sym(1).Node = node;
 } break;
 case 33: {
     AST::UiObjectBinding *node = makeAstNode<AST::UiObjectBinding> (driver->nodePool(),
       sym(3).UiQualifiedId, sym(1).UiQualifiedId, sym(4).UiObjectInitializer);
     node->colonToken = loc(2);
     node->hasOnToken = true;
     sym(1).Node = node;
 } break;
 case 34:case 35:case 36:case 37:
 {
     AST::UiScriptBinding *node = makeAstNode<AST::UiScriptBinding> (driver->nodePool(),
         sym(1).UiQualifiedId, sym(3).Statement);
     node->colonToken = loc(2);
     sym(1).Node = node;
 }   break;
 case 38:
 case 39: {
     sym(1).sval = driver->intern(lexer->characterBuffer(), lexer->characterCount());
     break;
 }
 case 41: {
   sym(1).Node = 0;
 } break;
 case 42: {
   sym(1).Node = sym(1).UiParameterList->finish ();
 } break;
 case 43: {
   AST::UiParameterList *node = makeAstNode<AST::UiParameterList> (driver->nodePool(), sym(1).sval, sym(2).sval);
   node->identifierToken = loc(2);
   sym(1).Node = node;
 } break;
 case 44: {
   AST::UiParameterList *node = makeAstNode<AST::UiParameterList> (driver->nodePool(), sym(1).UiParameterList, sym(3).sval, sym(4).sval);
   node->commaToken = loc(2);
   node->identifierToken = loc(4);
   sym(1).Node = node;
 } break;
 case 46: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), (NameId *)0, sym(2).sval);
     node->type = AST::UiPublicMember::Signal;
     node->propertyToken = loc(1);
     node->typeToken = loc(2);
     node->identifierToken = loc(2);
     node->parameters = sym(4).UiParameterList;
     node->semicolonToken = loc(6);
     sym(1).Node = node;
 }   break;
 case 48: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), (NameId *)0, sym(2).sval);
     node->type = AST::UiPublicMember::Signal;
     node->propertyToken = loc(1);
     node->typeToken = loc(2);
     node->identifierToken = loc(2);
     node->semicolonToken = loc(3);
     sym(1).Node = node;
 }   break;
 case 50: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(4).sval, sym(6).sval);
     node->typeModifier = sym(2).sval;
     node->propertyToken = loc(1);
     node->typeModifierToken = loc(2);
     node->typeToken = loc(4);
     node->identifierToken = loc(6);
     node->semicolonToken = loc(7);
     sym(1).Node = node;
 }   break;
 case 52: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(2).sval, sym(3).sval);
     node->propertyToken = loc(1);
     node->typeToken = loc(2);
     node->identifierToken = loc(3);
     node->semicolonToken = loc(4);
     sym(1).Node = node;
 }   break;
 case 54: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(3).sval, sym(4).sval);
     node->isDefaultMember = true;
     node->defaultToken = loc(1);
     node->propertyToken = loc(2);
     node->typeToken = loc(3);
     node->identifierToken = loc(4);
     node->semicolonToken = loc(5);
     sym(1).Node = node;
 }   break;
 case 56: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(2).sval, sym(3).sval,
         sym(5).Expression);
     node->propertyToken = loc(1);
     node->typeToken = loc(2);
     node->identifierToken = loc(3);
     node->colonToken = loc(4);
     node->semicolonToken = loc(6);
     sym(1).Node = node;
 }   break;
 case 58: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(3).sval, sym(4).sval,
         sym(6).Expression);
     node->isReadonlyMember = true;
     node->readonlyToken = loc(1);
     node->propertyToken = loc(2);
     node->typeToken = loc(3);
     node->identifierToken = loc(4);
     node->colonToken = loc(5);
     node->semicolonToken = loc(7);
     sym(1).Node = node;
 }   break;
 case 60: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(3).sval, sym(4).sval,
         sym(6).Expression);
     node->isDefaultMember = true;
     node->defaultToken = loc(1);
     node->propertyToken = loc(2);
     node->typeToken = loc(3);
     node->identifierToken = loc(4);
     node->colonToken = loc(5);
     node->semicolonToken = loc(7);
     sym(1).Node = node;
 }   break;
 case 61: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(4).sval, sym(6).sval);
     node->typeModifier = sym(2).sval;
     node->propertyToken = loc(1);
     node->typeModifierToken = loc(2);
     node->typeToken = loc(4);
     node->identifierToken = loc(6);
     node->semicolonToken = loc(7); // insert a fake ';' before ':'
     AST::UiQualifiedId *propertyName = makeAstNode<AST::UiQualifiedId>(driver->nodePool(), sym(6).sval);
     propertyName->identifierToken = loc(6);
     propertyName->next = 0;
     AST::UiArrayBinding *binding = makeAstNode<AST::UiArrayBinding> (driver->nodePool(),
         propertyName, sym(9).UiArrayMemberList->finish());
     binding->colonToken = loc(7);
     binding->lbracketToken = loc(8);
     binding->rbracketToken = loc(10);
     node->binding = binding;
     sym(1).Node = node;
 }   break;
 case 62: {
     AST::UiPublicMember *node = makeAstNode<AST::UiPublicMember> (driver->nodePool(), sym(2).sval, sym(3).sval);
     node->propertyToken = loc(1);
     node->typeToken = loc(2);
     node->identifierToken = loc(3);
     node->semicolonToken = loc(4); // insert a fake ';' before ':'
     AST::UiQualifiedId *propertyName = makeAstNode<AST::UiQualifiedId>(driver->nodePool(), sym(3).sval);
     propertyName->identifierToken = loc(3);
     propertyName->next = 0;
     AST::UiObjectBinding *binding = makeAstNode<AST::UiObjectBinding> (driver->nodePool(),
       propertyName, sym(5).UiQualifiedId, sym(6).UiObjectInitializer);
     binding->colonToken = loc(4);
     node->binding = binding;
     sym(1).Node = node;
 }   break;
 case 63: {
     sym(1).Node = makeAstNode<AST::UiSourceElement>(driver->nodePool(), sym(1).Node);
 }   break;
 case 64: {
     sym(1).Node = makeAstNode<AST::UiSourceElement>(driver->nodePool(), sym(1).Node);
 }   break;
 case 66: {
     QString s = QLatin1String(QDeclarativeJSGrammar::spell[T_PROPERTY]);
     sym(1).sval = driver->intern(s.constData(), s.length());
     break;
 }
 case 67: {
     QString s = QLatin1String(QDeclarativeJSGrammar::spell[T_SIGNAL]);
     sym(1).sval = driver->intern(s.constData(), s.length());
     break;
 }
 case 68: {
     QString s = QLatin1String(QDeclarativeJSGrammar::spell[T_READONLY]);
     sym(1).sval = driver->intern(s.constData(), s.length());
     break;
 }
 case 69: {
     QString s = QLatin1String(QDeclarativeJSGrammar::spell[T_ON]);
     sym(1).sval = driver->intern(s.constData(), s.length());
     break;
 }
 case 70: {
   AST::ThisExpression *node = makeAstNode<AST::ThisExpression> (driver->nodePool());
   node->thisToken = loc(1);
   sym(1).Node = node;
 } break;
 case 71: {
   AST::IdentifierExpression *node = makeAstNode<AST::IdentifierExpression> (driver->nodePool(), sym(1).sval);
   node->identifierToken = loc(1);
   sym(1).Node = node;
 } break;
 case 72: {
   AST::NullExpression *node = makeAstNode<AST::NullExpression> (driver->nodePool());
   node->nullToken = loc(1);
   sym(1).Node = node;
 } break;
 case 73: {
   AST::TrueLiteral *node = makeAstNode<AST::TrueLiteral> (driver->nodePool());
   node->trueToken = loc(1);
   sym(1).Node = node;
 } break;
 case 74: {
   AST::FalseLiteral *node = makeAstNode<AST::FalseLiteral> (driver->nodePool());
   node->falseToken = loc(1);
   sym(1).Node = node;
 } break;
 case 75: {
   AST::NumericLiteral *node = makeAstNode<AST::NumericLiteral> (driver->nodePool(), sym(1).dval);
   node->literalToken = loc(1);
   sym(1).Node = node;
 } break;
 case 76:
 case 77: {
   AST::StringLiteral *node = makeAstNode<AST::StringLiteral> (driver->nodePool(), sym(1).sval);
   node->literalToken = loc(1);
   sym(1).Node = node;
 } break;
 case 78: {
   bool rx = lexer->scanRegExp(Lexer::NoPrefix);
   if (!rx) {
     diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, location(lexer), lexer->errorMessage()));
     return false; // ### remove me
   }
   loc(1).length = lexer->tokenLength();
   AST::RegExpLiteral *node = makeAstNode<AST::RegExpLiteral> (driver->nodePool(), lexer->pattern, lexer->flags);
   node->literalToken = loc(1);
   sym(1).Node = node;
 } break;
 case 79: {
   bool rx = lexer->scanRegExp(Lexer::EqualPrefix);
   if (!rx) {
     diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, location(lexer), lexer->errorMessage()));
     return false;
   }
   loc(1).length = lexer->tokenLength();
   AST::RegExpLiteral *node = makeAstNode<AST::RegExpLiteral> (driver->nodePool(), lexer->pattern, lexer->flags);
   node->literalToken = loc(1);
   sym(1).Node = node;
 } break;
 case 80: {
   AST::ArrayLiteral *node = makeAstNode<AST::ArrayLiteral> (driver->nodePool(), (AST::Elision *) 0);
   node->lbracketToken = loc(1);
   node->rbracketToken = loc(2);
   sym(1).Node = node;
 } break;
 case 81: {
   AST::ArrayLiteral *node = makeAstNode<AST::ArrayLiteral> (driver->nodePool(), sym(2).Elision->finish());
   node->lbracketToken = loc(1);
   node->rbracketToken = loc(3);
   sym(1).Node = node;
 } break;
 case 82: {
   AST::ArrayLiteral *node = makeAstNode<AST::ArrayLiteral> (driver->nodePool(), sym(2).ElementList->finish ());
   node->lbracketToken = loc(1);
   node->rbracketToken = loc(3);
   sym(1).Node = node;
 } break;
 case 83: {
   AST::ArrayLiteral *node = makeAstNode<AST::ArrayLiteral> (driver->nodePool(), sym(2).ElementList->finish (),
     (AST::Elision *) 0);
   node->lbracketToken = loc(1);
   node->commaToken = loc(3);
   node->rbracketToken = loc(4);
   sym(1).Node = node;
 } break;
 case 84: {
   AST::ArrayLiteral *node = makeAstNode<AST::ArrayLiteral> (driver->nodePool(), sym(2).ElementList->finish (),
     sym(4).Elision->finish());
   node->lbracketToken = loc(1);
   node->commaToken = loc(3);
   node->rbracketToken = loc(5);
   sym(1).Node = node;
 } break;
 case 85: {
   AST::ObjectLiteral *node = 0;
   if (sym(2).Node)
     node = makeAstNode<AST::ObjectLiteral> (driver->nodePool(),
         sym(2).PropertyNameAndValueList->finish ());
   else
     node = makeAstNode<AST::ObjectLiteral> (driver->nodePool());
   node->lbraceToken = loc(1);
   node->rbraceToken = loc(3);
   sym(1).Node = node;
 } break;
 case 86: {
   AST::ObjectLiteral *node = makeAstNode<AST::ObjectLiteral> (driver->nodePool(),
     sym(2).PropertyNameAndValueList->finish ());
   node->lbraceToken = loc(1);
   node->rbraceToken = loc(4);
   sym(1).Node = node;
 } break;
 case 87: {
   AST::NestedExpression *node = makeAstNode<AST::NestedExpression>(driver->nodePool(), sym(2).Expression);
   node->lparenToken = loc(1);
   node->rparenToken = loc(3);
   sym(1).Node = node;
 } break;
 case 88: {
   if (AST::ArrayMemberExpression *mem = AST::cast<AST::ArrayMemberExpression *>(sym(1).Expression)) {
     diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Warning, mem->lbracketToken,
       QLatin1String("Ignored annotation")));
     sym(1).Expression = mem->base;
   }
   if (AST::UiQualifiedId *qualifiedId = reparseAsQualifiedId(sym(1).Expression)) {
     sym(1).UiQualifiedId = qualifiedId;
   } else {
     sym(1).UiQualifiedId = 0;
     diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, loc(1),
       QLatin1String("Expected a qualified name id")));
     return false; // ### recover
   }
 } break;
 case 89: {
   sym(1).Node = makeAstNode<AST::ElementList> (driver->nodePool(), (AST::Elision *) 0, sym(1).Expression);
 } break;
 case 90: {
   sym(1).Node = makeAstNode<AST::ElementList> (driver->nodePool(), sym(1).Elision->finish(), sym(2).Expression);
 } break;
 case 91: {
   AST::ElementList *node = makeAstNode<AST::ElementList> (driver->nodePool(), sym(1).ElementList,
     (AST::Elision *) 0, sym(3).Expression);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 92: {
   AST::ElementList *node = makeAstNode<AST::ElementList> (driver->nodePool(), sym(1).ElementList, sym(3).Elision->finish(),
     sym(4).Expression);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 93: {
   AST::Elision *node = makeAstNode<AST::Elision> (driver->nodePool());
   node->commaToken = loc(1);
   sym(1).Node = node;
 } break;
 case 94: {
   AST::Elision *node = makeAstNode<AST::Elision> (driver->nodePool(), sym(1).Elision);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 95: {
   AST::PropertyNameAndValueList *node = makeAstNode<AST::PropertyNameAndValueList> (driver->nodePool(),
       sym(1).PropertyName, sym(3).Expression);
   node->colonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 96: {
   AST::PropertyNameAndValueList *node = makeAstNode<AST::PropertyNameAndValueList> (driver->nodePool(),
       sym(1).PropertyNameAndValueList, sym(3).PropertyName, sym(5).Expression);
   node->commaToken = loc(2);
   node->colonToken = loc(4);
   sym(1).Node = node;
 } break;
 case 97: {
   AST::IdentifierPropertyName *node = makeAstNode<AST::IdentifierPropertyName> (driver->nodePool(), sym(1).sval);
   node->propertyNameToken = loc(1);
   sym(1).Node = node;
 } break;
 case 98:
 case 99: {
   AST::IdentifierPropertyName *node = makeAstNode<AST::IdentifierPropertyName> (driver->nodePool(), driver->intern(lexer->characterBuffer(), lexer->characterCount()));
   node->propertyNameToken = loc(1);
   sym(1).Node = node;
 } break;
 case 100: {
   AST::StringLiteralPropertyName *node = makeAstNode<AST::StringLiteralPropertyName> (driver->nodePool(), sym(1).sval);
   node->propertyNameToken = loc(1);
   sym(1).Node = node;
 } break;
 case 101: {
   AST::NumericLiteralPropertyName *node = makeAstNode<AST::NumericLiteralPropertyName> (driver->nodePool(), sym(1).dval);
   node->propertyNameToken = loc(1);
   sym(1).Node = node;
 } break;
 case 102: {
   AST::IdentifierPropertyName *node = makeAstNode<AST::IdentifierPropertyName> (driver->nodePool(), sym(1).sval);
   node->propertyNameToken = loc(1);
   sym(1).Node = node;
 } break;
 case 103:
 case 104:
 case 105:
 case 106:
 case 107:
 case 108:
 case 109:
 case 110:
 case 111:
 case 112:
 case 113:
 case 114:
 case 115:
 case 116:
 case 117:
 case 118:
 case 119:
 case 120:
 case 121:
 case 122:
 case 123:
 case 124:
 case 125:
 case 126:
 case 127:
 case 128:
 case 129:
 case 130:
 case 131:
 case 132:
 case 133:
 {
   sym(1).sval = driver->intern(lexer->characterBuffer(), lexer->characterCount());
 } break;
 case 138: {
   AST::ArrayMemberExpression *node = makeAstNode<AST::ArrayMemberExpression> (driver->nodePool(), sym(1).Expression, sym(3).Expression);
   node->lbracketToken = loc(2);
   node->rbracketToken = loc(4);
   sym(1).Node = node;
 } break;
 case 139: {
   AST::FieldMemberExpression *node = makeAstNode<AST::FieldMemberExpression> (driver->nodePool(), sym(1).Expression, sym(3).sval);
   node->dotToken = loc(2);
   node->identifierToken = loc(3);
   sym(1).Node = node;
 } break;
 case 140: {
   AST::NewMemberExpression *node = makeAstNode<AST::NewMemberExpression> (driver->nodePool(), sym(2).Expression, sym(4).ArgumentList);
   node->newToken = loc(1);
   node->lparenToken = loc(3);
   node->rparenToken = loc(5);
   sym(1).Node = node;
 } break;
 case 142: {
   AST::NewExpression *node = makeAstNode<AST::NewExpression> (driver->nodePool(), sym(2).Expression);
   node->newToken = loc(1);
   sym(1).Node = node;
 } break;
 case 143: {
   AST::CallExpression *node = makeAstNode<AST::CallExpression> (driver->nodePool(), sym(1).Expression, sym(3).ArgumentList);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 144: {
   AST::CallExpression *node = makeAstNode<AST::CallExpression> (driver->nodePool(), sym(1).Expression, sym(3).ArgumentList);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 145: {
   AST::ArrayMemberExpression *node = makeAstNode<AST::ArrayMemberExpression> (driver->nodePool(), sym(1).Expression, sym(3).Expression);
   node->lbracketToken = loc(2);
   node->rbracketToken = loc(4);
   sym(1).Node = node;
 } break;
 case 146: {
   AST::FieldMemberExpression *node = makeAstNode<AST::FieldMemberExpression> (driver->nodePool(), sym(1).Expression, sym(3).sval);
   node->dotToken = loc(2);
   node->identifierToken = loc(3);
   sym(1).Node = node;
 } break;
 case 147: {
   sym(1).Node = 0;
 } break;
 case 148: {
   sym(1).Node = sym(1).ArgumentList->finish();
 } break;
 case 149: {
   sym(1).Node = makeAstNode<AST::ArgumentList> (driver->nodePool(), sym(1).Expression);
 } break;
 case 150: {
   AST::ArgumentList *node = makeAstNode<AST::ArgumentList> (driver->nodePool(), sym(1).ArgumentList, sym(3).Expression);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 154: {
   AST::PostIncrementExpression *node = makeAstNode<AST::PostIncrementExpression> (driver->nodePool(), sym(1).Expression);
   node->incrementToken = loc(2);
   sym(1).Node = node;
 } break;
 case 155: {
   AST::PostDecrementExpression *node = makeAstNode<AST::PostDecrementExpression> (driver->nodePool(), sym(1).Expression);
   node->decrementToken = loc(2);
   sym(1).Node = node;
 } break;
 case 157: {
   AST::DeleteExpression *node = makeAstNode<AST::DeleteExpression> (driver->nodePool(), sym(2).Expression);
   node->deleteToken = loc(1);
   sym(1).Node = node;
 } break;
 case 158: {
   AST::VoidExpression *node = makeAstNode<AST::VoidExpression> (driver->nodePool(), sym(2).Expression);
   node->voidToken = loc(1);
   sym(1).Node = node;
 } break;
 case 159: {
   AST::TypeOfExpression *node = makeAstNode<AST::TypeOfExpression> (driver->nodePool(), sym(2).Expression);
   node->typeofToken = loc(1);
   sym(1).Node = node;
 } break;
 case 160: {
   AST::PreIncrementExpression *node = makeAstNode<AST::PreIncrementExpression> (driver->nodePool(), sym(2).Expression);
   node->incrementToken = loc(1);
   sym(1).Node = node;
 } break;
 case 161: {
   AST::PreDecrementExpression *node = makeAstNode<AST::PreDecrementExpression> (driver->nodePool(), sym(2).Expression);
   node->decrementToken = loc(1);
   sym(1).Node = node;
 } break;
 case 162: {
   AST::UnaryPlusExpression *node = makeAstNode<AST::UnaryPlusExpression> (driver->nodePool(), sym(2).Expression);
   node->plusToken = loc(1);
   sym(1).Node = node;
 } break;
 case 163: {
   AST::UnaryMinusExpression *node = makeAstNode<AST::UnaryMinusExpression> (driver->nodePool(), sym(2).Expression);
   node->minusToken = loc(1);
   sym(1).Node = node;
 } break;
 case 164: {
   AST::TildeExpression *node = makeAstNode<AST::TildeExpression> (driver->nodePool(), sym(2).Expression);
   node->tildeToken = loc(1);
   sym(1).Node = node;
 } break;
 case 165: {
   AST::NotExpression *node = makeAstNode<AST::NotExpression> (driver->nodePool(), sym(2).Expression);
   node->notToken = loc(1);
   sym(1).Node = node;
 } break;
 case 167: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Mul, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 168: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Div, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 169: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Mod, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 171: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Add, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 172: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Sub, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 174: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::LShift, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 175: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::RShift, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 176: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::URShift, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 178: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Lt, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 179: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Gt, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 180: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Le, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 181: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Ge, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 182: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::InstanceOf, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 183: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::In, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 185: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Lt, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 186: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Gt, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 187: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Le, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 188: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
    QSOperator::Ge, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 189: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::InstanceOf, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 191: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Equal, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 192: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::NotEqual, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 193: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::StrictEqual, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 194: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::StrictNotEqual, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 196: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Equal, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 197: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::NotEqual, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 198: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::StrictEqual, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 199: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::StrictNotEqual, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 201: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::BitAnd, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 203: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::BitAnd, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 205: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::BitXor, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 207: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::BitXor, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 209: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::BitOr, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 211: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::BitOr, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 213: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::And, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 215: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::And, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 217: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Or, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 219: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     QSOperator::Or, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 221: {
   AST::ConditionalExpression *node = makeAstNode<AST::ConditionalExpression> (driver->nodePool(), sym(1).Expression,
     sym(3).Expression, sym(5).Expression);
   node->questionToken = loc(2);
   node->colonToken = loc(4);
   sym(1).Node = node;
 } break;
 case 223: {
   AST::ConditionalExpression *node = makeAstNode<AST::ConditionalExpression> (driver->nodePool(), sym(1).Expression,
     sym(3).Expression, sym(5).Expression);
   node->questionToken = loc(2);
   node->colonToken = loc(4);
   sym(1).Node = node;
 } break;
 case 225: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     sym(2).ival, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 227: {
   AST::BinaryExpression *node = makeAstNode<AST::BinaryExpression> (driver->nodePool(), sym(1).Expression,
     sym(2).ival, sym(3).Expression);
   node->operatorToken = loc(2);
   sym(1).Node = node;
 } break;
 case 228: {
   sym(1).ival = QSOperator::Assign;
 } break;
 case 229: {
   sym(1).ival = QSOperator::InplaceMul;
 } break;
 case 230: {
   sym(1).ival = QSOperator::InplaceDiv;
 } break;
 case 231: {
   sym(1).ival = QSOperator::InplaceMod;
 } break;
 case 232: {
   sym(1).ival = QSOperator::InplaceAdd;
 } break;
 case 233: {
   sym(1).ival = QSOperator::InplaceSub;
 } break;
 case 234: {
   sym(1).ival = QSOperator::InplaceLeftShift;
 } break;
 case 235: {
   sym(1).ival = QSOperator::InplaceRightShift;
 } break;
 case 236: {
   sym(1).ival = QSOperator::InplaceURightShift;
 } break;
 case 237: {
   sym(1).ival = QSOperator::InplaceAnd;
 } break;
 case 238: {
   sym(1).ival = QSOperator::InplaceXor;
 } break;
 case 239: {
   sym(1).ival = QSOperator::InplaceOr;
 } break;
 case 241: {
   AST::Expression *node = makeAstNode<AST::Expression> (driver->nodePool(), sym(1).Expression, sym(3).Expression);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 242: {
   sym(1).Node = 0;
 } break;
 case 245: {
   AST::Expression *node = makeAstNode<AST::Expression> (driver->nodePool(), sym(1).Expression, sym(3).Expression);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 246: {
   sym(1).Node = 0;
 } break;
 case 263: {
   AST::Block *node = makeAstNode<AST::Block> (driver->nodePool(), sym(2).StatementList);
   node->lbraceToken = loc(1);
   node->rbraceToken = loc(3);
   sym(1).Node = node;
 } break;
 case 264: {
   sym(1).Node = makeAstNode<AST::StatementList> (driver->nodePool(), sym(1).Statement);
 } break;
 case 265: {
   sym(1).Node = makeAstNode<AST::StatementList> (driver->nodePool(), sym(1).StatementList, sym(2).Statement);
 } break;
 case 266: {
   sym(1).Node = 0;
 } break;
 case 267: {
   sym(1).Node = sym(1).StatementList->finish ();
 } break;
 case 269: {
   AST::VariableStatement *node = makeAstNode<AST::VariableStatement> (driver->nodePool(),
      sym(2).VariableDeclarationList->finish (/*readOnly=*/sym(1).ival == T_CONST));
   node->declarationKindToken = loc(1);
   node->semicolonToken = loc(3);
   sym(1).Node = node;
 } break;
 case 270: {
   sym(1).ival = T_CONST;
 } break;
 case 271: {
   sym(1).ival = T_VAR;
 } break;
 case 272: {
   sym(1).Node = makeAstNode<AST::VariableDeclarationList> (driver->nodePool(), sym(1).VariableDeclaration);
 } break;
 case 273: {
   AST::VariableDeclarationList *node = makeAstNode<AST::VariableDeclarationList> (driver->nodePool(),
     sym(1).VariableDeclarationList, sym(3).VariableDeclaration);
   node->commaToken = loc(2);
   sym(1).Node = node;
 } break;
 case 274: {
   sym(1).Node = makeAstNode<AST::VariableDeclarationList> (driver->nodePool(), sym(1).VariableDeclaration);
 } break;
 case 275: {
   sym(1).Node = makeAstNode<AST::VariableDeclarationList> (driver->nodePool(), sym(1).VariableDeclarationList, sym(3).VariableDeclaration);
 } break;
 case 276: {
   AST::VariableDeclaration *node = makeAstNode<AST::VariableDeclaration> (driver->nodePool(), sym(1).sval, sym(2).Expression);
   node->identifierToken = loc(1);
   sym(1).Node = node;
 } break;
 case 277: {
   AST::VariableDeclaration *node = makeAstNode<AST::VariableDeclaration> (driver->nodePool(), sym(1).sval, sym(2).Expression);
   node->identifierToken = loc(1);
   sym(1).Node = node;
 } break;
 case 278: {
   // ### TODO: AST for initializer
   sym(1) = sym(2);
 } break;
 case 279: {
   sym(1).Node = 0;
 } break;
 case 281: {
   // ### TODO: AST for initializer
   sym(1) = sym(2);
 } break;
 case 282: {
   sym(1).Node = 0;
 } break;
 case 284: {
   AST::EmptyStatement *node = makeAstNode<AST::EmptyStatement> (driver->nodePool());
   node->semicolonToken = loc(1);
   sym(1).Node = node;
 } break;
 case 286: {
   AST::ExpressionStatement *node = makeAstNode<AST::ExpressionStatement> (driver->nodePool(), sym(1).Expression);
   node->semicolonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 287: {
   AST::IfStatement *node = makeAstNode<AST::IfStatement> (driver->nodePool(), sym(3).Expression, sym(5).Statement, sym(7).Statement);
   node->ifToken = loc(1);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   node->elseToken = loc(5);
   sym(1).Node = node;
 } break;
 case 288: {
   AST::IfStatement *node = makeAstNode<AST::IfStatement> (driver->nodePool(), sym(3).Expression, sym(5).Statement);
   node->ifToken = loc(1);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 290: {
   AST::DoWhileStatement *node = makeAstNode<AST::DoWhileStatement> (driver->nodePool(), sym(2).Statement, sym(5).Expression);
   node->doToken = loc(1);
   node->whileToken = loc(3);
   node->lparenToken = loc(4);
   node->rparenToken = loc(6);
   node->semicolonToken = loc(7);
   sym(1).Node = node;
 } break;
 case 291: {
   AST::WhileStatement *node = makeAstNode<AST::WhileStatement> (driver->nodePool(), sym(3).Expression, sym(5).Statement);
   node->whileToken = loc(1);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 292: {
   AST::ForStatement *node = makeAstNode<AST::ForStatement> (driver->nodePool(), sym(3).Expression,
     sym(5).Expression, sym(7).Expression, sym(9).Statement);
   node->forToken = loc(1);
   node->lparenToken = loc(2);
   node->firstSemicolonToken = loc(4);
   node->secondSemicolonToken = loc(6);
   node->rparenToken = loc(8);
   sym(1).Node = node;
 } break;
 case 293: {
   AST::LocalForStatement *node = makeAstNode<AST::LocalForStatement> (driver->nodePool(),
      sym(4).VariableDeclarationList->finish (/*readOnly=*/false), sym(6).Expression,
      sym(8).Expression, sym(10).Statement);
   node->forToken = loc(1);
   node->lparenToken = loc(2);
   node->varToken = loc(3);
   node->firstSemicolonToken = loc(5);
   node->secondSemicolonToken = loc(7);
   node->rparenToken = loc(9);
   sym(1).Node = node;
 } break;
 case 294: {
   AST:: ForEachStatement *node = makeAstNode<AST::ForEachStatement> (driver->nodePool(), sym(3).Expression,
     sym(5).Expression, sym(7).Statement);
   node->forToken = loc(1);
   node->lparenToken = loc(2);
   node->inToken = loc(4);
   node->rparenToken = loc(6);
   sym(1).Node = node;
 } break;
 case 295: {
   AST::LocalForEachStatement *node = makeAstNode<AST::LocalForEachStatement> (driver->nodePool(),
     sym(4).VariableDeclaration, sym(6).Expression, sym(8).Statement);
   node->forToken = loc(1);
   node->lparenToken = loc(2);
   node->varToken = loc(3);
   node->inToken = loc(5);
   node->rparenToken = loc(7);
   sym(1).Node = node;
 } break;
 case 297: {
   AST::ContinueStatement *node = makeAstNode<AST::ContinueStatement> (driver->nodePool());
   node->continueToken = loc(1);
   node->semicolonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 299: {
   AST::ContinueStatement *node = makeAstNode<AST::ContinueStatement> (driver->nodePool(), sym(2).sval);
   node->continueToken = loc(1);
   node->identifierToken = loc(2);
   node->semicolonToken = loc(3);
   sym(1).Node = node;
 } break;
 case 301: {
   AST::BreakStatement *node = makeAstNode<AST::BreakStatement> (driver->nodePool());
   node->breakToken = loc(1);
   node->semicolonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 303: {
   AST::BreakStatement *node = makeAstNode<AST::BreakStatement> (driver->nodePool(), sym(2).sval);
   node->breakToken = loc(1);
   node->identifierToken = loc(2);
   node->semicolonToken = loc(3);
   sym(1).Node = node;
 } break;
 case 305: {
   AST::ReturnStatement *node = makeAstNode<AST::ReturnStatement> (driver->nodePool(), sym(2).Expression);
   node->returnToken = loc(1);
   node->semicolonToken = loc(3);
   sym(1).Node = node;
 } break;
 case 306: {
   AST::WithStatement *node = makeAstNode<AST::WithStatement> (driver->nodePool(), sym(3).Expression, sym(5).Statement);
   node->withToken = loc(1);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 307: {
   AST::SwitchStatement *node = makeAstNode<AST::SwitchStatement> (driver->nodePool(), sym(3).Expression, sym(5).CaseBlock);
   node->switchToken = loc(1);
   node->lparenToken = loc(2);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 308: {
   AST::CaseBlock *node = makeAstNode<AST::CaseBlock> (driver->nodePool(), sym(2).CaseClauses);
   node->lbraceToken = loc(1);
   node->rbraceToken = loc(3);
   sym(1).Node = node;
 } break;
 case 309: {
   AST::CaseBlock *node = makeAstNode<AST::CaseBlock> (driver->nodePool(), sym(2).CaseClauses, sym(3).DefaultClause, sym(4).CaseClauses);
   node->lbraceToken = loc(1);
   node->rbraceToken = loc(5);
   sym(1).Node = node;
 } break;
 case 310: {
   sym(1).Node = makeAstNode<AST::CaseClauses> (driver->nodePool(), sym(1).CaseClause);
 } break;
 case 311: {
   sym(1).Node = makeAstNode<AST::CaseClauses> (driver->nodePool(), sym(1).CaseClauses, sym(2).CaseClause);
 } break;
 case 312: {
   sym(1).Node = 0;
 } break;
 case 313: {
   sym(1).Node = sym(1).CaseClauses->finish ();
 } break;
 case 314: {
   AST::CaseClause *node = makeAstNode<AST::CaseClause> (driver->nodePool(), sym(2).Expression, sym(4).StatementList);
   node->caseToken = loc(1);
   node->colonToken = loc(3);
   sym(1).Node = node;
 } break;
 case 315: {
   AST::DefaultClause *node = makeAstNode<AST::DefaultClause> (driver->nodePool(), sym(3).StatementList);
   node->defaultToken = loc(1);
   node->colonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 316:
 case 317: {
   AST::LabelledStatement *node = makeAstNode<AST::LabelledStatement> (driver->nodePool(), driver->intern(lexer->characterBuffer(), lexer->characterCount()), sym(3).Statement);
   node->identifierToken = loc(1);
   node->colonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 318: {
   AST::LabelledStatement *node = makeAstNode<AST::LabelledStatement> (driver->nodePool(), sym(1).sval, sym(3).Statement);
   node->identifierToken = loc(1);
   node->colonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 320: {
   AST::ThrowStatement *node = makeAstNode<AST::ThrowStatement> (driver->nodePool(), sym(2).Expression);
   node->throwToken = loc(1);
   node->semicolonToken = loc(3);
   sym(1).Node = node;
 } break;
 case 321: {
   AST::TryStatement *node = makeAstNode<AST::TryStatement> (driver->nodePool(), sym(2).Statement, sym(3).Catch);
   node->tryToken = loc(1);
   sym(1).Node = node;
 } break;
 case 322: {
   AST::TryStatement *node = makeAstNode<AST::TryStatement> (driver->nodePool(), sym(2).Statement, sym(3).Finally);
   node->tryToken = loc(1);
   sym(1).Node = node;
 } break;
 case 323: {
   AST::TryStatement *node = makeAstNode<AST::TryStatement> (driver->nodePool(), sym(2).Statement, sym(3).Catch, sym(4).Finally);
   node->tryToken = loc(1);
   sym(1).Node = node;
 } break;
 case 324: {
   AST::Catch *node = makeAstNode<AST::Catch> (driver->nodePool(), sym(3).sval, sym(5).Block);
   node->catchToken = loc(1);
   node->lparenToken = loc(2);
   node->identifierToken = loc(3);
   node->rparenToken = loc(4);
   sym(1).Node = node;
 } break;
 case 325: {
   AST::Finally *node = makeAstNode<AST::Finally> (driver->nodePool(), sym(2).Block);
   node->finallyToken = loc(1);
   sym(1).Node = node;
 } break;
 case 327: {
   AST::DebuggerStatement *node = makeAstNode<AST::DebuggerStatement> (driver->nodePool());
   node->debuggerToken = loc(1);
   node->semicolonToken = loc(2);
   sym(1).Node = node;
 } break;
 case 328: {
   AST::FunctionDeclaration *node = makeAstNode<AST::FunctionDeclaration> (driver->nodePool(), sym(2).sval, sym(4).FormalParameterList, sym(7).FunctionBody);
   node->functionToken = loc(1);
   node->identifierToken = loc(2);
   node->lparenToken = loc(3);
   node->rparenToken = loc(5);
   node->lbraceToken = loc(6);
   node->rbraceToken = loc(8);
   sym(1).Node = node;
 } break;
 case 329: {
   AST::FunctionExpression *node = makeAstNode<AST::FunctionExpression> (driver->nodePool(), sym(2).sval, sym(4).FormalParameterList, sym(7).FunctionBody);
   node->functionToken = loc(1);
   if (sym(2).sval)
       node->identifierToken = loc(2);
   node->lparenToken = loc(3);
   node->rparenToken = loc(5);
   node->lbraceToken = loc(6);
   node->rbraceToken = loc(8);
   sym(1).Node = node;
 } break;
 case 330: {
   AST::FormalParameterList *node = makeAstNode<AST::FormalParameterList> (driver->nodePool(), sym(1).sval);
   node->identifierToken = loc(1);
   sym(1).Node = node;
 } break;
 case 331: {
   AST::FormalParameterList *node = makeAstNode<AST::FormalParameterList> (driver->nodePool(), sym(1).FormalParameterList, sym(3).sval);
   node->commaToken = loc(2);
   node->identifierToken = loc(3);
   sym(1).Node = node;
 } break;
 case 332: {
   sym(1).Node = 0;
 } break;
 case 333: {
   sym(1).Node = sym(1).FormalParameterList->finish ();
 } break;
 case 334: {
   sym(1).Node = 0;
 } break;
 case 336: {
   sym(1).Node = makeAstNode<AST::FunctionBody> (driver->nodePool(), sym(1).SourceElements->finish ());
 } break;
 case 337: {
   sym(1).Node = makeAstNode<AST::Program> (driver->nodePool(), sym(1).SourceElements->finish ());
 } break;
 case 338: {
   sym(1).Node = makeAstNode<AST::SourceElements> (driver->nodePool(), sym(1).SourceElement);
 } break;
 case 339: {
   sym(1).Node = makeAstNode<AST::SourceElements> (driver->nodePool(), sym(1).SourceElements, sym(2).SourceElement);
 } break;
 case 340: {
   sym(1).Node = makeAstNode<AST::StatementSourceElement> (driver->nodePool(), sym(1).Statement);
 } break;
 case 341: {
   sym(1).Node = makeAstNode<AST::FunctionSourceElement> (driver->nodePool(), sym(1).FunctionDeclaration);
 } break;
 case 342: {
   sym(1).sval = 0;
 } break;
 case 344: {
   sym(1).Node = 0;
 } break;
             } // switch
             action = nt_action(state_stack[tos], lhs[r] - TERMINAL_COUNT);
         } // if
     } while (action != 0);
     if (first_token == last_token) {
         const int errorState = state_stack[tos];
         // automatic insertion of `;'
         if (yytoken != -1 && t_action(errorState, T_AUTOMATIC_SEMICOLON) && automatic(driver, yytoken)) {
             SavedToken &tk = token_buffer[0];
             tk.token = yytoken;
             tk.dval = yylval;
             tk.loc = yylloc;
             yylloc = yyprevlloc;
             yylloc.offset += yylloc.length;
             yylloc.startColumn += yylloc.length;
             yylloc.length = 0;
             //const QString msg = qApp->translate("QDeclarativeParser", "Missing `;'");
             //diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Warning, yylloc, msg));
             first_token = &token_buffer[0];
             last_token = &token_buffer[1];
             yytoken = T_SEMICOLON;
             yylval = 0;
             action = errorState;
             goto _Lcheck_token;
         }
         hadErrors = true;
         token_buffer[0].token = yytoken;
         token_buffer[0].dval = yylval;
         token_buffer[0].loc = yylloc;
         token_buffer[1].token = yytoken = lexer->lex();
         token_buffer[1].dval  = yylval  = lexer->dval();
         token_buffer[1].loc   = yylloc  = location(lexer);
         if (t_action(errorState, yytoken)) {
             QString msg;
             int token = token_buffer[0].token;
             if (token < 0 || token >= TERMINAL_COUNT)
                 msg = qApp->translate("QDeclarativeParser", "Syntax error");
             else
                 msg = qApp->translate("QDeclarativeParser", "Unexpected token `%1'").arg(QLatin1String(spell[token]));
             diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, token_buffer[0].loc, msg));
             action = errorState;
             goto _Lcheck_token;
         }
         static int tokens[] = {
             T_PLUS,
             T_EQ,
             T_COMMA,
             T_COLON,
             T_SEMICOLON,
             T_RPAREN, T_RBRACKET, T_RBRACE,
             T_NUMERIC_LITERAL,
             T_IDENTIFIER,
             T_LPAREN, T_LBRACKET, T_LBRACE,
             EOF_SYMBOL
         };
         for (int *tk = tokens; *tk != EOF_SYMBOL; ++tk) {
             int a = t_action(errorState, *tk);
             if (a > 0 && t_action(a, yytoken)) {
                 const QString msg = qApp->translate("QDeclarativeParser", "Expected token `%1'").arg(QLatin1String(spell[*tk]));
                 diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, token_buffer[0].loc, msg));
                 yytoken = *tk;
                 yylval = 0;
                 yylloc = token_buffer[0].loc;
                 yylloc.length = 0;
                 first_token = &token_buffer[0];
                 last_token = &token_buffer[2];
                 action = errorState;
                 goto _Lcheck_token;
             }
         }
         for (int tk = 1; tk < TERMINAL_COUNT; ++tk) {
             if (tk == T_AUTOMATIC_SEMICOLON || tk == T_FEED_UI_PROGRAM    ||
                 tk == T_FEED_JS_STATEMENT   || tk == T_FEED_JS_EXPRESSION ||
                 tk == T_FEED_JS_SOURCE_ELEMENT)
                continue;
             int a = t_action(errorState, tk);
             if (a > 0 && t_action(a, yytoken)) {
                 const QString msg = qApp->translate("QDeclarativeParser", "Expected token `%1'").arg(QLatin1String(spell[tk]));
                 diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, token_buffer[0].loc, msg));
                 yytoken = tk;
                 yylval = 0;
                 yylloc = token_buffer[0].loc;
                 yylloc.length = 0;
                 action = errorState;
                 goto _Lcheck_token;
             }
         }
         const QString msg = qApp->translate("QDeclarativeParser", "Syntax error");
         diagnostic_messages.append(DiagnosticMessage(DiagnosticMessage::Error, token_buffer[0].loc, msg));
     }
     return false;
 }
parseExpression()
bool QDeclarativeJS::Parser::parseExpression () inline
Definition at line 134 of file qdeclarativejsparser_p.h.
 { return parse(T_FEED_JS_EXPRESSION); }
parseProgram()
bool QDeclarativeJS::Parser::parseProgram () inline
Definition at line 137 of file qdeclarativejsparser_p.h.
 { return parse(T_FEED_JS_PROGRAM); }
parseSourceElement()
bool QDeclarativeJS::Parser::parseSourceElement () inline
Definition at line 135 of file qdeclarativejsparser_p.h.
 { return parse(T_FEED_JS_SOURCE_ELEMENT); }
parseStatement()
bool QDeclarativeJS::Parser::parseStatement () inline
Definition at line 133 of file qdeclarativejsparser_p.h.
Referenced by QDeclarativeRewrite::SharedBindingTester::isSharable(), and QDeclarativeRewrite::RewriteBinding::operator()().
 { return parse(T_FEED_JS_STATEMENT); }
parseUiObjectMember()
bool QDeclarativeJS::Parser::parseUiObjectMember () inline
Definition at line 136 of file qdeclarativejsparser_p.h.
 { return parse(T_FEED_UI_OBJECT_MEMBER); }
reallocateStack()
QT_QML_BEGIN_NAMESPACE void Parser::reallocateStack () protected
Definition at line 66 of file qdeclarativejsparser.cpp.
Referenced by parse().
 {
     if (! stack_size)
         stack_size = 128;
     else
         stack_size <<= 1;
     sym_stack = reinterpret_cast<Value*> (qRealloc(sym_stack, stack_size * sizeof(Value)));
     state_stack = reinterpret_cast<int*> (qRealloc(state_stack, stack_size * sizeof(int)));
     location_stack = reinterpret_cast<AST::SourceLocation*> (qRealloc(location_stack, stack_size * sizeof(AST::SourceLocation)));
 }
reparseAsQualifiedId()
AST::UiQualifiedId * Parser::reparseAsQualifiedId (AST::ExpressionNode * expr) protected
Definition at line 117 of file qdeclarativejsparser.cpp.
Referenced by parse().
 {
     QVarLengthArray<NameId *, 4> nameIds;
     QVarLengthArray<AST::SourceLocation, 4> locations;
     AST::ExpressionNode *it = expr;
     while (AST::FieldMemberExpression *m = AST::cast<AST::FieldMemberExpression *>(it)) {
         nameIds.append(m->name);
         locations.append(m->identifierToken);
         it = m->base;
     }
     if (AST::IdentifierExpression *idExpr = AST::cast<AST::IdentifierExpression *>(it)) {
         AST::UiQualifiedId *q = makeAstNode<AST::UiQualifiedId>(driver->nodePool(), idExpr->name);
         q->identifierToken = idExpr->identifierToken;
         AST::UiQualifiedId *currentId = q;
         for (int i = nameIds.size() - 1; i != -1; --i) {
             currentId = makeAstNode<AST::UiQualifiedId>(driver->nodePool(), currentId, nameIds[i]);
             currentId->identifierToken = locations[i];
         }
         return currentId->finish();
     }
     return 0;
 }
rootNode()
AST::Node* QDeclarativeJS::Parser::rootNode () const inline
Definition at line 166 of file qdeclarativejsparser_p.h.
     { return program; }
statement()
AST::Statement* QDeclarativeJS::Parser::statement () const inline
Definition at line 142 of file qdeclarativejsparser_p.h.
Referenced by QDeclarativeRewrite::SharedBindingTester::isSharable(), and QDeclarativeRewrite::RewriteBinding::operator()().
     {
         if (! program)
             return 0;
         return program->statementCast();
     }
sym()
Value& QDeclarativeJS::Parser::sym (int index) inline protected
Definition at line 196 of file qdeclarativejsparser_p.h.
Referenced by parse().
     { return sym_stack [tos + index - 1]; }
uiObjectMember()
AST::UiObjectMember* QDeclarativeJS::Parser::uiObjectMember () const inline
Definition at line 158 of file qdeclarativejsparser_p.h.
     {
         if (! program)
             return 0;
         return program->uiObjectMemberCast();
     }
Properties
diagnostic_messages
QList<DiagnosticMessage> QDeclarativeJS::Parser::diagnostic_messages protected
Definition at line 231 of file qdeclarativejsparser_p.h.
Referenced by parse().
driver
Engine* QDeclarativeJS::Parser::driver protected
Definition at line 205 of file qdeclarativejsparser_p.h.
Referenced by parse(), and reparseAsQualifiedId().
first_token
SavedToken* QDeclarativeJS::Parser::first_token protected
Definition at line 228 of file qdeclarativejsparser_p.h.
Referenced by parse().
last_token
SavedToken* QDeclarativeJS::Parser::last_token protected
Definition at line 229 of file qdeclarativejsparser_p.h.
Referenced by parse().
location_stack
AST::SourceLocation* QDeclarativeJS::Parser::location_stack protected
Definition at line 210 of file qdeclarativejsparser_p.h.
Referenced by reallocateStack(), and ~Parser().
program
AST::Node* QDeclarativeJS::Parser::program protected
Definition at line 212 of file qdeclarativejsparser_p.h.
Referenced by parse().
stack_size
int QDeclarativeJS::Parser::stack_size protected
Definition at line 207 of file qdeclarativejsparser_p.h.
Referenced by parse(), reallocateStack(), and ~Parser().
state_stack
int* QDeclarativeJS::Parser::state_stack protected
Definition at line 209 of file qdeclarativejsparser_p.h.
Referenced by parse(), reallocateStack(), and ~Parser().
sym_stack
Value* QDeclarativeJS::Parser::sym_stack protected
Definition at line 208 of file qdeclarativejsparser_p.h.
Referenced by reallocateStack(), and ~Parser().
token_buffer
SavedToken QDeclarativeJS::Parser::token_buffer[TOKEN_BUFFER_SIZE] protected
Definition at line 227 of file qdeclarativejsparser_p.h.
Referenced by parse().
tos
int QDeclarativeJS::Parser::tos protected
Definition at line 206 of file qdeclarativejsparser_p.h.
Referenced by parse().
yylloc
AST::SourceLocation QDeclarativeJS::Parser::yylloc protected
Definition at line 224 of file qdeclarativejsparser_p.h.
Referenced by parse().
yylval
double QDeclarativeJS::Parser::yylval protected
Definition at line 223 of file qdeclarativejsparser_p.h.
Referenced by parse().
yyprevlloc
AST::SourceLocation QDeclarativeJS::Parser::yyprevlloc protected
Definition at line 225 of file qdeclarativejsparser_p.h.
Referenced by parse().
The documentation for this class was generated from the following files:
/src/declarative/qml/parser/qdeclarativejsparser_p.h
/src/declarative/qml/parser/qdeclarativejsparser.cpp