Qt 4.8: QMacStylePrivate Class Reference
QMacStylePrivate Class Reference
#include <qmacstyle_mac_p.h>
Classes
struct ButtonState
Public Types
enum Animates { AquaPushButton, AquaProgressBar, AquaListViewItemOpen }
Public Functions
bool addWidget (QWidget *)
bool animatable (Animates, const QWidget *) const
int animateSpeed (Animates) const
QAquaWidgetSize aquaSizeConstrain (const QStyleOption *option, const QWidget *widg, QStyle::ContentsType ct=QStyle::CT_CustomBase, QSize szHint=QSize(-1, -1), QSize *insz=0) const
bool contentFitsInPushButton (const QStyleOptionButton *btn, HIThemeButtonDrawInfo *bdi, ThemeButtonKind buttonKindToCheck) const
bool doAnimate (Animates)
void drawColorlessButton (const HIRect &macRect, HIThemeButtonDrawInfo *bdi, QPainter *p, const QStyleOption *opt) const
QPixmap generateBackgroundPattern () const
void getSliderInfo (QStyle::ComplexControl cc, const QStyleOptionSlider *slider, HIThemeTrackDrawInfo *tdi, const QWidget *needToRemoveMe)
void initComboboxBdi (const QStyleOptionComboBox *combo, HIThemeButtonDrawInfo *bdi, const QWidget *widget, const ThemeDrawState &tds)
void initHIThemePushButton (const QStyleOptionButton *btn, const QWidget *widget, const ThemeDrawState tds, HIThemeButtonDrawInfo *bdi) const
HIRect pushButtonContentBounds (const QStyleOptionButton *btn, const HIThemeButtonDrawInfo *bdi) const
QSize pushButtonSizeFromContents (const QStyleOptionButton *btn) const
QMacStylePrivate (QMacStyle *style)
void removeWidget (QWidget *)
void startAnimate (Animates, QWidget *)
void stopAnimate (Animates, QWidget *)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QRect comboboxEditBounds (const QRect &outerBounds, const HIThemeButtonDrawInfo &bdi)
static HIRect comboboxInnerBounds (const HIRect &outerBounds, int buttonKind)
static void drawCombobox (const HIRect &outerBounds, const HIThemeButtonDrawInfo &bdi, QPainter *p)
static void drawTableHeader (const HIRect &outerBounds, bool drawTopBorder, bool drawLeftBorder, const HIThemeButtonDrawInfo &bdi, QPainter *p)
static ThemeDrawState getDrawState (QStyle::State flags)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
struct QMacStylePrivate::ButtonState buttonState
QPointer< QPushButton > defaultButton
CFAbsoluteTime defaultButtonStart
QPointer< QFocusFrame > focusWidget
bool mouseDown
QList< QPointer< QWidget > > progressBars
UInt8 progressFrame
QMacStyle * q
int timerID
Static Public Variables
static const int BevelButtonH = 22
static const int BevelButtonW = 50
static const int MiniButtonH = 26
static const int PushButtonBottomOffset = 12
static const int PushButtonContentPadding = 6
static const int PushButtonLeftOffset = 6
static const int PushButtonRightOffset = 12
static const int PushButtonTopOffset = 4
static const int SmallButtonH = 30
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions
bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Slots
void startAnimationTimer ()
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 155 of file qmacstyle_mac_p.h.
Enumerations
Animates
enum QMacStylePrivate::Animates
Enumerator
AquaPushButton
AquaProgressBar
AquaListViewItemOpen
Definition at line 178 of file qmacstyle_mac_p.h.
 { AquaPushButton, AquaProgressBar, AquaListViewItemOpen };
Constructors and Destructors
QMacStylePrivate()
QMacStylePrivate::QMacStylePrivate (QMacStyle * style)
Definition at line 1427 of file qmacstyle_mac.mm.
     : timerID(-1), progressFrame(0), q(style), mouseDown(false)
 {
     defaultButtonStart = CFAbsoluteTimeGetCurrent();
     memset(&buttonState, 0, sizeof(ButtonState));
     if (ptrHIShapeGetBounds == 0) {
         QLibrary library(QLatin1String("/System/Library/Frameworks/Carbon.framework/Carbon"));
         library.setLoadHints(QLibrary::ExportExternalSymbolsHint);
         ptrHIShapeGetBounds = reinterpret_cast<PtrHIShapeGetBounds>(library.resolve("HIShapeGetBounds"));
     }
 }
Functions
addWidget()
bool QMacStylePrivate::addWidget (QWidget * w)
Definition at line 1489 of file qmacstyle_mac.mm.
Referenced by QMacStyle::polish().
 {
     //already knew of it
     if (static_cast<QPushButton*>(w) == defaultButton
             || progressBars.contains(static_cast<QProgressBar*>(w)))
         return false;
     if (QPushButton *btn = qobject_cast<QPushButton *>(w)) {
         btn->installEventFilter(this);
         if (btn->isDefault() || (btn->autoDefault() && btn->hasFocus()))
             startAnimate(AquaPushButton, btn);
         return true;
     } else {
         bool isProgressBar = (qobject_cast<QProgressBar *>(w)
 #ifdef QT3_SUPPORT
                 || w->inherits("Q3ProgressBar")
 #endif
             );
         if (isProgressBar) {
             w->installEventFilter(this);
             startAnimate(AquaProgressBar, w);
             return true;
         }
     }
     if (w->isWindow()) {
         w->installEventFilter(this);
         return true;
     }
     return false;
 }
animatable()
bool QMacStylePrivate::animatable (QMacStylePrivate::Animates as, const QWidget * w) const
Definition at line 1441 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawControl().
 {
     if (!w)
         return false;
     if (as == AquaPushButton) {
         QPushButton *pb = const_cast<QPushButton *>(static_cast<const QPushButton *>(w));
         if (w->window()->isActiveWindow() && pb && !mouseDown) {
             if (static_cast<const QPushButton *>(w) != defaultButton) {
                 // Changed on its own, update the value.
                 const_cast<QMacStylePrivate *>(this)->stopAnimate(as, defaultButton);
                 const_cast<QMacStylePrivate *>(this)->startAnimate(as, pb);
             }
             return true;
         }
     } else if (as == AquaProgressBar) {
         if (progressBars.contains((const_cast<QWidget *>(w))))
             return true;
     }
     return false;
 }
animateSpeed()
int QMacStylePrivate::animateSpeed (Animates) const inline
Definition at line 189 of file qmacstyle_mac_p.h.
Referenced by startAnimationTimer().
 { return 33; }
aquaSizeConstrain()
QAquaWidgetSize QMacStylePrivate::aquaSizeConstrain (const QStyleOption * option, const QWidget * widg, QStyle::ContentsType ct = QStyle::CT_CustomBase, QSize szHint = QSize(-1, -1), QSize * insz = 0) const
Definition at line 866 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::drawPrimitive(), getSliderInfo(), initComboboxBdi(), initHIThemePushButton(), QMacStyle::pixelMetric(), QMacStyle::sizeFromContents(), and QMacStyle::subControlRect().
 {
 #if defined(QMAC_QAQUASTYLE_SIZE_CONSTRAIN) || defined(DEBUG_SIZE_CONSTRAINT)
     if (option) {
         if (option->state & QStyle::State_Small)
             return QAquaSizeSmall;
         if (option->state & QStyle::State_Mini)
             return QAquaSizeMini;
     }
     if (!widg) {
         if (insz)
             *insz = QSize();
         if (!qgetenv("QWIDGET_ALL_SMALL").isNull())
             return QAquaSizeSmall;
         if (!qgetenv("QWIDGET_ALL_MINI").isNull())
             return QAquaSizeMini;
         return QAquaSizeUnknown;
     }
     QSize large = qt_aqua_get_known_size(ct, widg, szHint, QAquaSizeLarge),
           small = qt_aqua_get_known_size(ct, widg, szHint, QAquaSizeSmall),
           mini  = qt_aqua_get_known_size(ct, widg, szHint, QAquaSizeMini);
     bool guess_size = false;
     QAquaWidgetSize ret = QAquaSizeUnknown;
     QMacStyle::WidgetSizePolicy wsp = q->widgetSizePolicy(widg);
     if (wsp == QMacStyle::SizeDefault)
         guess_size = true;
     else if (wsp == QMacStyle::SizeMini)
         ret = QAquaSizeMini;
     else if (wsp == QMacStyle::SizeSmall)
         ret = QAquaSizeSmall;
     else if (wsp == QMacStyle::SizeLarge)
         ret = QAquaSizeLarge;
     if (guess_size)
         ret = qt_aqua_guess_size(widg, large, small, mini);
     QSize *sz = 0;
     if (ret == QAquaSizeSmall)
         sz = &small;
     else if (ret == QAquaSizeLarge)
         sz = &large;
     else if (ret == QAquaSizeMini)
         sz = &mini;
     if (insz)
         *insz = sz ? *sz : QSize(-1, -1);
 #ifdef DEBUG_SIZE_CONSTRAINT
     if (sz) {
         const char *size_desc = "Unknown";
         if (sz == &small)
             size_desc = "Small";
         else if (sz == &large)
             size_desc = "Large";
         else if (sz == &mini)
             size_desc = "Mini";
         qDebug("%s - %s: %s taken (%d, %d) [%d, %d]",
                widg ? widg->objectName().toLatin1().constData() : "*Unknown*",
                widg ? widg->metaObject()->className() : "*Unknown*", size_desc, widg->width(), widg->height(),
                sz->width(), sz->height());
     }
 #endif
     return ret;
 #else
     if (insz)
         *insz = QSize();
     Q_UNUSED(widg);
     Q_UNUSED(ct);
     Q_UNUSED(szHint);
     return QAquaSizeUnknown;
 #endif
 }
comboboxEditBounds()
QRect QMacStylePrivate::comboboxEditBounds (const QRect & outerBounds, const HIThemeButtonDrawInfo & bdi) static
Inside a combobox Qt places a line edit widget. The size of this widget should depend on the kind of combobox we choose to draw. This function calculates and returns this size.
Definition at line 1193 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), and QMacStyle::subControlRect().
 {
     QRect ret = outerBounds;
     switch (bdi.kind){
     case kThemeComboBox:
         ret.adjust(5, 5, -22, -5);
         break;
     case kThemeComboBoxSmall:
         ret.adjust(4, 6, -20, 0);
         ret.setHeight(14);
         break;
     case kThemeComboBoxMini:
         ret.adjust(4, 5, -18, -1);
         ret.setHeight(12);
         break;
     case kThemePopupButton:
         ret.adjust(10, 2, -23, -4);
         break;
     case kThemePopupButtonSmall:
         ret.adjust(9, 3, -20, -3);
         break;
     case kThemePopupButtonMini:
         ret.adjust(8, 3, -19, 0);
         ret.setHeight(13);
         break;
     }
     return ret;
 }
comboboxInnerBounds()
HIRect QMacStylePrivate::comboboxInnerBounds (const HIRect & outerBounds, int buttonKind) static
Carbon draws comboboxes (and other views) outside the rect given as argument. Use this function to obtain the corresponding inner rect for drawing the same combobox so that it stays inside the given outerBounds.
Definition at line 1140 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), drawCombobox(), QMacStyle::sizeFromContents(), and QMacStyle::subControlRect().
 {
     HIRect innerBounds = outerBounds;
     // Carbon draw parts of the view outside the rect.
     // So make the rect a bit smaller to compensate
     // (I wish HIThemeGetButtonBackgroundBounds worked)
     switch (buttonKind){
     case kThemePopupButton:
         innerBounds.origin.x += 2;
         innerBounds.origin.y += 2;
         innerBounds.size.width -= 5;
         innerBounds.size.height -= 6;
         break;
     case kThemePopupButtonSmall:
         innerBounds.origin.x += 3;
         innerBounds.origin.y += 3;
         innerBounds.size.width -= 6;
         innerBounds.size.height -= 7;
         break;
     case kThemePopupButtonMini:
         innerBounds.origin.x += 2;
         innerBounds.origin.y += 2;
         innerBounds.size.width -= 5;
         innerBounds.size.height -= 6;
         break;
     case kThemeComboBox:
         innerBounds.origin.x += 3;
         innerBounds.origin.y += 2;
         innerBounds.size.width -= 6;
         innerBounds.size.height -= 8;
         break;
     case kThemeComboBoxSmall:
         innerBounds.origin.x += 3;
         innerBounds.origin.y += 3;
         innerBounds.size.width -= 7;
         innerBounds.size.height -= 8;
         break;
     case kThemeComboBoxMini:
         innerBounds.origin.x += 3;
         innerBounds.origin.y += 3;
         innerBounds.size.width -= 4;
         innerBounds.size.height -= 8;
         break;
     default:
         break;
     }
     return innerBounds;
 }
contentFitsInPushButton()
bool QMacStylePrivate::contentFitsInPushButton (const QStyleOptionButton * btn, HIThemeButtonDrawInfo * bdi, ThemeButtonKind buttonKindToCheck) const
Checks if the actual contents of btn fits inside the free content bounds of 'buttonKindToCheck'. Meant as a helper function for 'initHIThemePushButton' for determining which button kind to use for drawing.
Definition at line 983 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), and initHIThemePushButton().
 {
     ThemeButtonKind tmp = bdi->kind;
     bdi->kind = buttonKindToCheck;
     QSize contentSize = pushButtonSizeFromContents(btn);
     QRect freeContentRect = qt_qrectForHIRect(pushButtonContentBounds(btn, bdi));
     bdi->kind = tmp;
     return freeContentRect.contains(QRect(freeContentRect.x(), freeContentRect.y(),
                                     contentSize.width(), contentSize.height()));
 }
doAnimate()
bool QMacStylePrivate::doAnimate (QMacStylePrivate::Animates as)
Definition at line 1665 of file qmacstyle_mac.mm.
Referenced by timerEvent().
 {
     if (as == AquaPushButton) {
     } else if (as == AquaProgressBar) {
         // something for later...
     } else if (as == AquaListViewItemOpen) {
         // To be revived later...
     }
     return true;
 }
drawColorlessButton()
void QMacStylePrivate::drawColorlessButton (const HIRect & macRect, HIThemeButtonDrawInfo * bdi, QPainter * p, const QStyleOption * opt) const
Definition at line 1676 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), QMacStyle::drawComplexControl(), and QMacStyle::drawPrimitive().
 {
     int xoff = 0,
         yoff = 0,
         extraWidth = 0,
         extraHeight = 0,
         finalyoff = 0;
     const QStyleOptionComboBox *combo = qstyleoption_cast<const QStyleOptionComboBox *>(opt);
     int width = int(macRect.size.width) + extraWidth;
     int height = int(macRect.size.height) + extraHeight;
     if (width <= 0 || height <= 0)
         return;   // nothing to draw
     QString key = QLatin1String("$qt_mac_style_ctb_") + QString::number(bdi->kind) + QLatin1Char('_')
                   + QString::number(bdi->value) + QLatin1Char('_') + QString::number(width)
                   + QLatin1Char('_') + QString::number(height);
     QPixmap pm;
     if (!QPixmapCache::find(key, pm)) {
         QPixmap activePixmap(width, height);
         activePixmap.fill(Qt::transparent);
         {
             if (combo){
                 // Carbon combos don't scale. Therefore we draw it
                 // ourselves, if a scaled version is needed.
                 QPainter tmpPainter(&activePixmap);
                 QMacStylePrivate::drawCombobox(macRect, *bdi, &tmpPainter);
             }
             else {
                 QMacCGContext cg(&activePixmap);
                 HIRect newRect = CGRectMake(xoff, yoff, macRect.size.width, macRect.size.height);
                 HIThemeDrawButton(&newRect, bdi, cg, kHIThemeOrientationNormal, 0);
             }
         }
         if (!combo && bdi->value == kThemeButtonOff) {
             pm = activePixmap;
         } else if (combo) {
             QImage image = activePixmap.toImage();
             for (int y = 0; y < height; ++y) {
                 QRgb *scanLine = reinterpret_cast<QRgb *>(image.scanLine(y));
                 for (int x = 0; x < width; ++x) {
                     QRgb &pixel = scanLine[x];
                     int darkest = qRed(pixel);
                     int mid = qGreen(pixel);
                     int lightest = qBlue(pixel);
                     if (darkest > mid)
                         qSwap(darkest, mid);
                     if (mid > lightest)
                         qSwap(mid, lightest);
                     if (darkest > mid)
                         qSwap(darkest, mid);
                     int gray = (mid + 2 * lightest) / 3;
                     pixel = qRgba(gray, gray, gray, qAlpha(pixel));
                 }
             }
             pm = QPixmap::fromImage(image);
         } else {
             QImage activeImage = activePixmap.toImage();
             QImage colorlessImage;
             {
                 QPixmap colorlessPixmap(width, height);
                 colorlessPixmap.fill(Qt::transparent);
                 QMacCGContext cg(&colorlessPixmap);
                 HIRect newRect = CGRectMake(xoff, yoff, macRect.size.width, macRect.size.height);
                 int oldValue = bdi->value;
                 bdi->value = kThemeButtonOff;
                 HIThemeDrawButton(&newRect, bdi, cg, kHIThemeOrientationNormal, 0);
                 bdi->value = oldValue;
                 colorlessImage = colorlessPixmap.toImage();
             }
             for (int y = 0; y < height; ++y) {
                 QRgb *colorlessScanLine = reinterpret_cast<QRgb *>(colorlessImage.scanLine(y));
                 const QRgb *activeScanLine = reinterpret_cast<const QRgb *>(activeImage.scanLine(y));
                 for (int x = 0; x < width; ++x) {
                     QRgb &colorlessPixel = colorlessScanLine[x];
                     QRgb activePixel = activeScanLine[x];
                     if (activePixel != colorlessPixel) {
                         int max = qMax(qMax(qRed(activePixel), qGreen(activePixel)),
                                        qBlue(activePixel));
                         QRgb newPixel = qRgba(max, max, max, qAlpha(activePixel));
                         if (qGray(newPixel) < qGray(colorlessPixel)
                                 || qAlpha(newPixel) > qAlpha(colorlessPixel))
                             colorlessPixel = newPixel;
                     }
                 }
             }
             pm = QPixmap::fromImage(colorlessImage);
         }
         QPixmapCache::insert(key, pm);
     }
     p->drawPixmap(int(macRect.origin.x), int(macRect.origin.y) + finalyoff, width, height, pm);
 }
drawCombobox()
void QMacStylePrivate::drawCombobox (const HIRect & outerBounds, const HIThemeButtonDrawInfo & bdi, QPainter * p) static
Carbon comboboxes don't scale (sight). If the size of the combo suggest a scaled version, create it manually by drawing a small Carbon combo onto a pixmap (use pixmap cache), chop it up, and copy it back onto the widget. Othervise, draw the combobox supplied by Carbon directly.
Definition at line 1227 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), drawColorlessButton(), and QMacStyle::drawComplexControl().
 {
     if (!(bdi.kind == kThemeComboBox && outerBounds.size.height > 28)){
         // We have an unscaled combobox, or popup-button; use Carbon directly.
         HIRect innerBounds = QMacStylePrivate::comboboxInnerBounds(outerBounds, bdi.kind);
         HIThemeDrawButton(&innerBounds, &bdi, QMacCGContext(p), kHIThemeOrientationNormal, 0);
     } else {
         QPixmap buffer;
         QString key = QString(QLatin1String("$qt_cbox%1-%2")).arg(int(bdi.state)).arg(int(bdi.adornment));
         if (!QPixmapCache::find(key, buffer)) {
             HIRect innerBoundsSmallCombo = {{3, 3}, {29, 25}};
             buffer = QPixmap(35, 28);
             buffer.fill(Qt::transparent);
             QPainter buffPainter(&buffer);
             HIThemeDrawButton(&innerBoundsSmallCombo, &bdi, QMacCGContext(&buffPainter), kHIThemeOrientationNormal, 0);
             buffPainter.end();
             QPixmapCache::insert(key, buffer);
         }
         const int bwidth = 20;
         const int fwidth = 10;
         const int fheight = 10;
         int w = qRound(outerBounds.size.width);
         int h = qRound(outerBounds.size.height);
         int bstart = w - bwidth;
         int blower = fheight + 1;
         int flower = h - fheight;
         int sheight = flower - fheight;
         int center = qRound(outerBounds.size.height + outerBounds.origin.y) / 2;
         // Draw upper and lower gap
         p->drawPixmap(fwidth, 0, bstart - fwidth, fheight, buffer, fwidth, 0, 1, fheight);
         p->drawPixmap(fwidth, flower, bstart - fwidth, fheight, buffer, fwidth, buffer.height() - fheight, 1, fheight);
         // Draw left and right gap. Right gap is drawn top and bottom separatly
         p->drawPixmap(0, fheight, fwidth, sheight, buffer, 0, fheight, fwidth, 1);
         p->drawPixmap(bstart, fheight, bwidth, center - fheight, buffer, buffer.width() - bwidth, fheight - 1, bwidth, 1);
         p->drawPixmap(bstart, center, bwidth, sheight / 2, buffer, buffer.width() - bwidth, fheight + 6, bwidth, 1);
         // Draw arrow
         p->drawPixmap(bstart, center - 4, bwidth - 3, 6, buffer, buffer.width() - bwidth, fheight, bwidth - 3, 6);
         // Draw corners
         p->drawPixmap(0, 0, fwidth, fheight, buffer, 0, 0, fwidth, fheight);
         p->drawPixmap(bstart, 0, bwidth, fheight, buffer, buffer.width() - bwidth, 0, bwidth, fheight);
         p->drawPixmap(0, flower, fwidth, fheight, buffer, 0, buffer.height() - fheight, fwidth, fheight);
         p->drawPixmap(bstart, h - blower, bwidth, blower, buffer, buffer.width() - bwidth, buffer.height() - blower, bwidth, blower);
     }
 }
drawTableHeader()
void QMacStylePrivate::drawTableHeader (const HIRect & outerBounds, bool drawTopBorder, bool drawLeftBorder, const HIThemeButtonDrawInfo & bdi, QPainter * p) static
Carbon tableheaders don't scale (sight). So create it manually by drawing a small Carbon header onto a pixmap (use pixmap cache), chop it up, and copy it back onto the widget.
Definition at line 1278 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), and QMacStyle::drawControl().
 {
     static SInt32 headerHeight = 0;
     static OSStatus err = GetThemeMetric(kThemeMetricListHeaderHeight, &headerHeight);
     Q_UNUSED(err);
     QPixmap buffer;
     QString key = QString(QLatin1String("$qt_tableh%1-%2-%3")).arg(int(bdi.state)).arg(int(bdi.adornment)).arg(int(bdi.value));
     if (!QPixmapCache::find(key, buffer)) {
         HIRect headerNormalRect = {{0., 0.}, {16., CGFloat(headerHeight)}};
         buffer = QPixmap(headerNormalRect.size.width, headerNormalRect.size.height);
         buffer.fill(Qt::transparent);
         QPainter buffPainter(&buffer);
         HIThemeDrawButton(&headerNormalRect, &bdi, QMacCGContext(&buffPainter), kHIThemeOrientationNormal, 0);
         buffPainter.end();
         QPixmapCache::insert(key, buffer);
     }
     const int buttonw = qRound(outerBounds.size.width);
     const int buttonh = qRound(outerBounds.size.height);
     const int framew = 1;
     const int frameh_n = 4;
     const int frameh_s = 3;
     const int transh = buffer.height() - frameh_n - frameh_s;
     int center = buttonh - frameh_s - int(transh / 2.0f) + 1; // Align bottom;
     int skipTopBorder = 0;
     if (!drawTopBorder)
         skipTopBorder = 1;
     p->translate(outerBounds.origin.x, outerBounds.origin.y);
     p->drawPixmap(QRect(QRect(0, -skipTopBorder, buttonw - framew , frameh_n)), buffer, QRect(framew, 0, 1, frameh_n));
     p->drawPixmap(QRect(0, buttonh - frameh_s, buttonw - framew, frameh_s), buffer, QRect(framew, buffer.height() - frameh_s, 1, frameh_s));
     // Draw upper and lower center blocks
     p->drawPixmap(QRect(0, frameh_n - skipTopBorder, buttonw - framew, center - frameh_n + skipTopBorder), buffer, QRect(framew, frameh_n, 1, 1));
     p->drawPixmap(QRect(0, center, buttonw - framew, buttonh - center - frameh_s), buffer, QRect(framew, buffer.height() - frameh_s, 1, 1));
     // Draw right center block borders
     p->drawPixmap(QRect(buttonw - framew, frameh_n - skipTopBorder, framew, center - frameh_n), buffer, QRect(buffer.width() - framew, frameh_n, framew, 1));
     p->drawPixmap(QRect(buttonw - framew, center, framew, buttonh - center - 1), buffer, QRect(buffer.width() - framew, buffer.height() - frameh_s, framew, 1));
     // Draw right corners
     p->drawPixmap(QRect(buttonw - framew, -skipTopBorder, framew, frameh_n), buffer, QRect(buffer.width() - framew, 0, framew, frameh_n));
     p->drawPixmap(QRect(buttonw - framew, buttonh - frameh_s, framew, frameh_s), buffer, QRect(buffer.width() - framew, buffer.height() - frameh_s, framew, frameh_s));
     // Draw center transition block
     p->drawPixmap(QRect(0, center - qRound(transh / 2.0f), buttonw - framew, buffer.height() - frameh_n - frameh_s), buffer, QRect(framew, frameh_n + 1, 1, transh));
     // Draw right center transition block border
     p->drawPixmap(QRect(buttonw - framew, center - qRound(transh / 2.0f), framew, buffer.height() - frameh_n - frameh_s), buffer, QRect(buffer.width() - framew, frameh_n + 1, framew, transh));
     if (drawLeftBorder){
         // Draw left center block borders
         p->drawPixmap(QRect(0, frameh_n - skipTopBorder, framew, center - frameh_n + skipTopBorder), buffer, QRect(0, frameh_n, framew, 1));
         p->drawPixmap(QRect(0, center, framew, buttonh - center - 1), buffer, QRect(0, buffer.height() - frameh_s, framew, 1));
         // Draw left corners
         p->drawPixmap(QRect(0, -skipTopBorder, framew, frameh_n), buffer, QRect(0, 0, framew, frameh_n));
         p->drawPixmap(QRect(0, buttonh - frameh_s, framew, frameh_s), buffer, QRect(0, buffer.height() - frameh_s, framew, frameh_s));
         // Draw left center transition block border
         p->drawPixmap(QRect(0, center - qRound(transh / 2.0f), framew, buffer.height() - frameh_n - frameh_s), buffer, QRect(0, frameh_n + 1, framew, transh));
     }
     p->translate(-outerBounds.origin.x, -outerBounds.origin.y);
 }
eventFilter()
bool QMacStylePrivate::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 1603 of file qmacstyle_mac.mm.
Referenced by animateSpeed().
 {
     //animate
     if (QProgressBar *pb = qobject_cast<QProgressBar *>(o)) {
         switch (e->type()) {
         default:
             break;
         case QEvent::Show:
             if (!progressBars.contains(pb))
                 startAnimate(AquaProgressBar, pb);
             break;
         case QEvent::Destroy:
         case QEvent::Hide:
             progressBars.removeAll(pb);
         }
     } else if (QPushButton *btn = qobject_cast<QPushButton *>(o)) {
         switch (e->type()) {
         default:
             break;
         case QEvent::FocusIn:
             if (btn->autoDefault())
                 startAnimate(AquaPushButton, btn);
             break;
         case QEvent::Destroy:
         case QEvent::Hide:
             if (btn == defaultButton)
                 stopAnimate(AquaPushButton, btn);
             break;
         case QEvent::MouseButtonPress:
             // It is very confusing to keep the button pulsing, so just stop the animation.
             if (static_cast<QMouseEvent *>(e)->button() == Qt::LeftButton)
                 mouseDown = true;
             stopAnimate(AquaPushButton, btn);
             break;
         case QEvent::MouseButtonRelease:
             if (static_cast<QMouseEvent *>(e)->button() == Qt::LeftButton)
                 mouseDown = false;
             // fall through
         case QEvent::FocusOut:
         case QEvent::Show:
         case QEvent::WindowActivate: {
             QList<QPushButton *> list = btn->window()->findChildren<QPushButton *>();
             for (int i = 0; i < list.size(); ++i) {
                 QPushButton *pBtn = list.at(i);
                 if ((e->type() == QEvent::FocusOut
                      && (pBtn->isDefault() || (pBtn->autoDefault() && pBtn->hasFocus()))
                      && pBtn != btn)
                     || ((e->type() == QEvent::Show || e->type() == QEvent::MouseButtonRelease
                          || e->type() == QEvent::WindowActivate)
                         && pBtn->isDefault())) {
                     if (pBtn->window()->isActiveWindow()) {
                         startAnimate(AquaPushButton, pBtn);
                     }
                     break;
                 }
             }
             break; }
         }
     }
     return false;
 }
generateBackgroundPattern()
QPixmap QMacStylePrivate::generateBackgroundPattern () const
Warning
This function is not part of the public interface. Generates the standard widget background pattern.
Definition at line 1797 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), and QMacStyle::polish().
 {
     QPixmap px(4, 4);
     QMacCGContext cg(&px);
     HIThemeSetFill(kThemeBrushDialogBackgroundActive, 0, cg, kHIThemeOrientationNormal);
     const CGRect cgRect = CGRectMake(0, 0, px.width(), px.height());
     CGContextFillRect(cg, cgRect);
     return px;
 }
getDrawState()
ThemeDrawState QMacStylePrivate::getDrawState (QStyle::State flags) static
Definition at line 1534 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::drawControl(), QMacStyle::drawPrimitive(), QMacStyle::subControlRect(), and QMacStyle::subElementRect().
 {
     ThemeDrawState tds = kThemeStateActive;
     if (flags & QStyle::State_Sunken) {
         tds = kThemeStatePressed;
     } else if (flags & QStyle::State_Active) {
         if (!(flags & QStyle::State_Enabled))
             tds = kThemeStateUnavailable;
     } else {
         if (flags & QStyle::State_Enabled)
             tds = kThemeStateInactive;
         else
             tds = kThemeStateUnavailableInactive;
     }
     return tds;
 }
getSliderInfo()
void QMacStylePrivate::getSliderInfo (QStyle::ComplexControl cc, const QStyleOptionSlider * slider, HIThemeTrackDrawInfo * tdi, const QWidget * needToRemoveMe)
Definition at line 1356 of file qmacstyle_mac.mm.
Referenced by QMacStyle::drawComplexControl(), QMacStyle::hitTestComplexControl(), and QMacStyle::subControlRect().
 {
     memset(tdi, 0, sizeof(HIThemeTrackDrawInfo)); // We don't get it all for some reason or another...
     tdi->version = qt_mac_hitheme_version;
     tdi->reserved = 0;
     tdi->filler1 = 0;
     bool isScrollbar = (cc == QStyle::CC_ScrollBar);
     switch (aquaSizeConstrain(0, needToRemoveMe)) {
     case QAquaSizeUnknown:
     case QAquaSizeLarge:
         if (isScrollbar)
             tdi->kind = kThemeMediumScrollBar;
         else
             tdi->kind = kThemeMediumSlider;
         break;
     case QAquaSizeMini:
         if (isScrollbar)
             tdi->kind = kThemeSmallScrollBar; // should be kThemeMiniScrollBar, but not implemented
         else
             tdi->kind = kThemeMiniSlider;
         break;
     case QAquaSizeSmall:
         if (isScrollbar)
             tdi->kind = kThemeSmallScrollBar;
         else
             tdi->kind = kThemeSmallSlider;
         break;
     }
     tdi->bounds = qt_hirectForQRect(slider->rect);
     tdi->min = slider->minimum;
     tdi->max = slider->maximum;
     tdi->value = slider->sliderPosition;
     tdi->attributes = kThemeTrackShowThumb;
     if (slider->upsideDown)
         tdi->attributes |= kThemeTrackRightToLeft;
     if (slider->orientation == Qt::Horizontal) {
         tdi->attributes |= kThemeTrackHorizontal;
         if (isScrollbar && slider->direction == Qt::RightToLeft) {
             if (!slider->upsideDown)
                 tdi->attributes |= kThemeTrackRightToLeft;
             else
                 tdi->attributes &= ~kThemeTrackRightToLeft;
         }
     }
     // Tiger broke reverse scroll bars so put them back and "fake it"
     if (isScrollbar && (tdi->attributes & kThemeTrackRightToLeft)) {
         tdi->attributes &= ~kThemeTrackRightToLeft;
         tdi->value = tdi->max - slider->sliderPosition;
     }
     tdi->enableState = (slider->state & QStyle::State_Enabled) ? kThemeTrackActive
                                                              : kThemeTrackDisabled;
     if (!(slider->state & QStyle::State_Active))
         tdi->enableState = kThemeTrackInactive;
     if (!isScrollbar) {
         if (slider->state & QStyle::QStyle::State_HasFocus)
             tdi->attributes |= kThemeTrackHasFocus;
         if (slider->tickPosition == QSlider::NoTicks || slider->tickPosition == QSlider::TicksBothSides)
             tdi->trackInfo.slider.thumbDir = kThemeThumbPlain;
         else if (slider->tickPosition == QSlider::TicksAbove)
             tdi->trackInfo.slider.thumbDir = kThemeThumbUpward;
         else
             tdi->trackInfo.slider.thumbDir = kThemeThumbDownward;
     } else {
         tdi->trackInfo.scrollbar.viewsize = slider->pageStep;
     }
 }
initComboboxBdi()
void QMacStylePrivate::initComboboxBdi (const QStyleOptionComboBox * combo, HIThemeButtonDrawInfo * bdi, const QWidget * widget, const ThemeDrawState & tds)
Creates a HIThemeButtonDrawInfo structure that specifies the correct button kind and other details to use for drawing the given combobox. Which button kind depends on the size of the combo, wether or not it is editable, explicit user style settings, etc.
Definition at line 1078 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), QMacStyle::drawComplexControl(), and QMacStyle::subControlRect().
 {
     bdi->version = qt_mac_hitheme_version;
     bdi->adornment = kThemeAdornmentArrowLeftArrow;
     bdi->value = kThemeButtonOff;
     if (combo->state & QStyle::State_HasFocus)
         bdi->adornment = kThemeAdornmentFocus;
     bool drawColorless = combo->palette.currentColorGroup() == QPalette::Active && tds == kThemeStateInactive;
     if (combo->activeSubControls & QStyle::SC_ComboBoxArrow)
         bdi->state = kThemeStatePressed;
     else if (drawColorless)
         bdi->state = kThemeStateActive;
     else
         bdi->state = tds;
     QAquaWidgetSize aSize = aquaSizeConstrain(combo, widget);
     switch (aSize) {
     case QAquaSizeMini:
         bdi->kind = combo->editable ? ThemeButtonKind(kThemeComboBoxMini)
             : ThemeButtonKind(kThemePopupButtonMini);
         break;
     case QAquaSizeSmall:
         bdi->kind = combo->editable ? ThemeButtonKind(kThemeComboBoxSmall)
             : ThemeButtonKind(kThemePopupButtonSmall);
         break;
     case QAquaSizeUnknown:
     case QAquaSizeLarge:
         // Unless the user explicitly specified large buttons, determine the
         // kind by looking at the combox size.
         // ... specifying small and mini-buttons it not a current feature of
         // Qt (e.g. QWidget::getAttribute(WA_ButtonSize)). But when it is, add
         // an extra check here before using the mini and small buttons.
         int h = combo->rect.size().height();
         if (combo->editable){
             if (h < 21)
                 bdi->kind = kThemeComboBoxMini;
             else if (h < 26)
                 bdi->kind = kThemeComboBoxSmall;
             else
                 bdi->kind = kThemeComboBox;
         } else {
             // Even if we specify that we want the kThemePopupButton, Carbon
             // will use the kThemePopupButtonSmall if the size matches. So we
             // do the same size check explicit to have the size of the inner
             // text field be correct. Therefore, do this even if the user specifies
             // the use of LargeButtons explicit.
             if (h < 21)
                 bdi->kind = kThemePopupButtonMini;
             else if (h < 26)
                 bdi->kind = kThemePopupButtonSmall;
             else
                 bdi->kind = kThemePopupButton;
         }
         break;
     }
 }
initHIThemePushButton()
void QMacStylePrivate::initHIThemePushButton (const QStyleOptionButton * btn, const QWidget * widget, const ThemeDrawState tds, HIThemeButtonDrawInfo * bdi) const
Creates a HIThemeButtonDrawInfo structure that specifies the correct button kind and other details to use for drawing the given push button. Which button kind depends on the size of the button, the size of the contents, explicit user style settings, etc.
Definition at line 1002 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), QMacStyle::drawControl(), qt_mac_buttonIsRenderedFlat(), and QMacStyle::subElementRect().
 {
     bool drawColorless = btn->palette.currentColorGroup() == QPalette::Active;
     ThemeDrawState tdsModified = tds;
     if (btn->state & QStyle::State_On)
         tdsModified = kThemeStatePressed;
     bdi->version = qt_mac_hitheme_version;
     bdi->state = tdsModified;
     bdi->value = kThemeButtonOff;
     if (drawColorless && tdsModified == kThemeStateInactive)
         bdi->state = kThemeStateActive;
     if (btn->state & QStyle::State_HasFocus)
         bdi->adornment = kThemeAdornmentFocus;
     else
         bdi->adornment = kThemeAdornmentNone;
     if (btn->features & (QStyleOptionButton::Flat)) {
         bdi->kind = kThemeBevelButton;
     } else {
         switch (aquaSizeConstrain(btn, widget)) {
         case QAquaSizeSmall:
             bdi->kind = kThemePushButtonSmall;
             break;
         case QAquaSizeMini:
             bdi->kind = kThemePushButtonMini;
             break;
         case QAquaSizeLarge:
             // ... We should honor if the user is explicit about using the
             // large button. But right now Qt will specify the large button
             // as default rather than QAquaSizeUnknown.
             // So we treat it like QAquaSizeUnknown
             // to get the dynamic choosing of button kind.
         case QAquaSizeUnknown:
             // Choose the button kind that closest match the button rect, but at the
             // same time displays the button contents without clipping.
             bdi->kind = kThemeBevelButton;
             if (btn->rect.width() >= QMacStylePrivate::BevelButtonW && btn->rect.height() >= QMacStylePrivate::BevelButtonH){
                 if (widget && widget->testAttribute(Qt::WA_MacVariableSize)) {
                     if (btn->rect.height() <= QMacStylePrivate::MiniButtonH){
                         if (contentFitsInPushButton(btn, bdi, kThemePushButtonMini))
                             bdi->kind = kThemePushButtonMini;
                     } else if (btn->rect.height() <= QMacStylePrivate::SmallButtonH){
                         if (contentFitsInPushButton(btn, bdi, kThemePushButtonSmall))
                             bdi->kind = kThemePushButtonSmall;
                     } else if (contentFitsInPushButton(btn, bdi, kThemePushButton)) {
                         bdi->kind = kThemePushButton;
                     }
                 } else {
                     bdi->kind = kThemePushButton;
                 }
             }
         }
     }
 }
pushButtonContentBounds()
HIRect QMacStylePrivate::pushButtonContentBounds (const QStyleOptionButton * btn, const HIThemeButtonDrawInfo * bdi) const
Returns the free space awailable for contents inside the button (and not the size of the contents itself)
Definition at line 942 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), contentFitsInPushButton(), and QMacStyle::subElementRect().
 {
     HIRect outerBounds = qt_hirectForQRect(btn->rect);
     // Adjust the bounds to correct for
     // carbon not calculating the content bounds fully correct
     if (bdi->kind == kThemePushButton || bdi->kind == kThemePushButtonSmall){
         outerBounds.origin.y += QMacStylePrivate::PushButtonTopOffset;
         outerBounds.size.height -= QMacStylePrivate::PushButtonBottomOffset;
     } else if (bdi->kind == kThemePushButtonMini) {
         outerBounds.origin.y += QMacStylePrivate::PushButtonTopOffset;
     }
     HIRect contentBounds;
     HIThemeGetButtonContentBounds(&outerBounds, bdi, &contentBounds);
     return contentBounds;
 }
pushButtonSizeFromContents()
QSize QMacStylePrivate::pushButtonSizeFromContents (const QStyleOptionButton * btn) const
Calculates the size of the button contents. This includes both the text and the icon.
Definition at line 964 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), and contentFitsInPushButton().
 {
     QSize csz(0, 0);
     QSize iconSize = btn->icon.isNull() ? QSize(0, 0)
                 : (btn->iconSize + QSize(QMacStylePrivate::PushButtonContentPadding, 0));
     QRect textRect = btn->text.isEmpty() ? QRect(0, 0, 1, 1)
                 : btn->fontMetrics.boundingRect(QRect(), Qt::AlignCenter, btn->text);
     csz.setWidth(iconSize.width() + textRect.width()
              + ((btn->features & QStyleOptionButton::HasMenu)
                             ? q->proxy()->pixelMetric(QStyle::PM_MenuButtonIndicator, btn, 0) : 0));
     csz.setHeight(qMax(iconSize.height(), textRect.height()));
     return csz;
 }
removeWidget()
void QMacStylePrivate::removeWidget (QWidget * w)
Definition at line 1520 of file qmacstyle_mac.mm.
Referenced by QMacStyle::unpolish().
 {
     QPushButton *btn = qobject_cast<QPushButton *>(w);
     if (btn && btn == defaultButton) {
         stopAnimate(AquaPushButton, btn);
     } else if (qobject_cast<QProgressBar *>(w)
 #ifdef QT3_SUPPORT
             || w->inherits("Q3ProgressBar")
 #endif
             ) {
         stopAnimate(AquaProgressBar, w);
     }
 }
startAnimate()
void QMacStylePrivate::startAnimate (QMacStylePrivate::Animates as, QWidget * w)
Definition at line 1474 of file qmacstyle_mac.mm.
Referenced by addWidget(), animatable(), and eventFilter().
 {
     if (as == AquaPushButton)
         defaultButton = static_cast<QPushButton *>(w);
     else if (as == AquaProgressBar)
         progressBars.append(w);
     startAnimationTimer();
 }
startAnimationTimer
void QMacStylePrivate::startAnimationTimer () private slot
Definition at line 1483 of file qmacstyle_mac.mm.
Referenced by animateSpeed(), and startAnimate().
 {
     if ((defaultButton || !progressBars.isEmpty()) && timerID <= -1)
         timerID = startTimer(animateSpeed(AquaListViewItemOpen));
 }
stopAnimate()
void QMacStylePrivate::stopAnimate (QMacStylePrivate::Animates as, QWidget * w)
Definition at line 1463 of file qmacstyle_mac.mm.
Referenced by animatable(), eventFilter(), and removeWidget().
 {
     if (as == AquaPushButton && defaultButton) {
         QPushButton *tmp = defaultButton;
         defaultButton = 0;
         tmp->update();
     } else if (as == AquaProgressBar) {
         progressBars.removeAll(w);
     }
 }
timerEvent()
void QMacStylePrivate::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 1551 of file qmacstyle_mac.mm.
Referenced by animateSpeed().
 {
     int animated = 0;
     if (defaultButton && defaultButton->isEnabled() && defaultButton->window()->isActiveWindow()
         && defaultButton->isVisibleTo(0) && (defaultButton->isDefault()
         || (defaultButton->autoDefault() && defaultButton->hasFocus()))
         && doAnimate(AquaPushButton)) {
         ++animated;
         defaultButton->update();
     }
     if (!progressBars.isEmpty()) {
         int i = 0;
         while (i < progressBars.size()) {
             QWidget *maybeProgress = progressBars.at(i);
             if (!maybeProgress) {
                 progressBars.removeAt(i);
             } else {
                 if (QProgressBar *pb = qobject_cast<QProgressBar *>(maybeProgress)) {
                     if (pb->maximum() == 0 || (pb->value() > 0 && pb->value() < pb->maximum())) {
                         if (doAnimate(AquaProgressBar))
                             pb->update();
                     }
                 }
 #ifdef QT3_SUPPORT
                 else {
                     // Watch me now...
                     QVariant progress = maybeProgress->property("progress");
                     QVariant totalSteps = maybeProgress->property("totalSteps");
                     if (progress.isValid() && totalSteps.isValid()) {
                         int intProgress = progress.toInt();
                         int intTotalSteps = totalSteps.toInt();
                         if (intTotalSteps == 0 || intProgress > 0 && intProgress < intTotalSteps) {
                             if (doAnimate(AquaProgressBar))
                                 maybeProgress->update();
                         }
                     }
                 }
 #endif
                 ++i;
             }
         }
         if (i > 0) {
             ++progressFrame;
             animated += i;
         }
     }
     if (animated <= 0) {
         killTimer(timerID);
         timerID = -1;
     }
 }
Properties
BevelButtonH
const int QMacStylePrivate::BevelButtonH = 22 static
Definition at line 170 of file qmacstyle_mac_p.h.
Referenced by initHIThemePushButton().
BevelButtonW
const int QMacStylePrivate::BevelButtonW = 50 static
Definition at line 169 of file qmacstyle_mac_p.h.
Referenced by initHIThemePushButton().
buttonState
struct QMacStylePrivate::ButtonState QMacStylePrivate::buttonState
Referenced by QMacStylePrivate().
defaultButton
QPointer<QPushButton> QMacStylePrivate::defaultButton
Definition at line 224 of file qmacstyle_mac_p.h.
Referenced by addWidget(), animatable(), eventFilter(), removeWidget(), startAnimate(), startAnimationTimer(), stopAnimate(), and timerEvent().
defaultButtonStart
CFAbsoluteTime QMacStylePrivate::defaultButtonStart
Definition at line 234 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), and QMacStylePrivate().
focusWidget
QPointer<QFocusFrame> QMacStylePrivate::focusWidget
Definition at line 233 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::event().
MiniButtonH
const int QMacStylePrivate::MiniButtonH = 26 static
Definition at line 167 of file qmacstyle_mac_p.h.
Referenced by initHIThemePushButton().
mouseDown
bool QMacStylePrivate::mouseDown
Definition at line 236 of file qmacstyle_mac_p.h.
Referenced by animatable(), and eventFilter().
progressBars
QList<QPointer<QWidget> > QMacStylePrivate::progressBars
Definition at line 226 of file qmacstyle_mac_p.h.
Referenced by addWidget(), animatable(), eventFilter(), startAnimate(), startAnimationTimer(), stopAnimate(), and timerEvent().
progressFrame
UInt8 QMacStylePrivate::progressFrame
Definition at line 232 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), and timerEvent().
PushButtonBottomOffset
const int QMacStylePrivate::PushButtonBottomOffset = 12 static
Definition at line 166 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), QPushButtonPrivate::hitButton(), pushButtonContentBounds(), and QMacStyle::sizeFromContents().
PushButtonContentPadding
const int QMacStylePrivate::PushButtonContentPadding = 6 static
Definition at line 171 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), QPushButtonPrivate::hitButton(), and pushButtonSizeFromContents().
PushButtonLeftOffset
const int QMacStylePrivate::PushButtonLeftOffset = 6 static
Definition at line 163 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), QPushButtonPrivate::hitButton(), and QMacStyle::sizeFromContents().
PushButtonRightOffset
const int QMacStylePrivate::PushButtonRightOffset = 12 static
Definition at line 165 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), QPushButtonPrivate::hitButton(), and QMacStyle::sizeFromContents().
PushButtonTopOffset
const int QMacStylePrivate::PushButtonTopOffset = 4 static
Definition at line 164 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), pushButtonContentBounds(), and QMacStyle::sizeFromContents().
q
QMacStyle* QMacStylePrivate::q
Definition at line 235 of file qmacstyle_mac_p.h.
Referenced by aquaSizeConstrain(), and pushButtonSizeFromContents().
SmallButtonH
const int QMacStylePrivate::SmallButtonH = 30 static
Definition at line 168 of file qmacstyle_mac_p.h.
Referenced by initHIThemePushButton().
timerID
int QMacStylePrivate::timerID
Definition at line 225 of file qmacstyle_mac_p.h.
Referenced by QMacStyle::drawControl(), startAnimationTimer(), and timerEvent().
The documentation for this class was generated from the following files:
/src/gui/styles/qmacstyle_mac_p.h
/src/gui/styles/qmacstyle_mac.mm