Qt 4.8: QZipReaderPrivate Class Reference
QZipReaderPrivate Class Reference
Public Functions
QZipReaderPrivate (QIODevice *device, bool ownDev)
void scanFiles ()
Public Functions inherited from QZipPrivate
void fillFileInfo (int index, QZipReader::FileInfo &fileInfo) const
QZipPrivate (QIODevice *device, bool ownDev)
~QZipPrivate ()
Public Variables
QZipReader::Status status
Public Variables inherited from QZipPrivate
QByteArray comment
QIODevice * device
bool dirtyFileTree
QList< FileHeader > fileHeaders
bool ownDevice
uint start_of_directory
Detailed Description
Definition at line 430 of file qzip.cpp.
Constructors and Destructors
QZipReaderPrivate()
QZipReaderPrivate::QZipReaderPrivate (QIODevice * device, bool ownDev) inline
Definition at line 433 of file qzip.cpp.
         : QZipPrivate(device, ownDev), status(QZipReader::NoError)
     {
     }
Functions
scanFiles()
void QZipReaderPrivate::scanFiles ()
Definition at line 479 of file qzip.cpp.
Referenced by QZipReader::count(), QZipReader::entryInfoAt(), QZipReader::fileData(), and QZipReader::fileInfoList().
 {
     if (!dirtyFileTree)
         return;
     if (! (device->isOpen() || device->open(QIODevice::ReadOnly))) {
         status = QZipReader::FileOpenError;
         return;
     }
     if ((device->openMode() & QIODevice::ReadOnly) == 0) { // only read the index from readable files.
         status = QZipReader::FileReadError;
         return;
     }
     dirtyFileTree = false;
     uchar tmp[4];
     device->read((char *)tmp, 4);
     if (readUInt(tmp) != 0x04034b50) {
         qWarning() << "QZip: not a zip file!";
         return;
     }
     // find EndOfDirectory header
     int i = 0;
     int start_of_directory = -1;
     int num_dir_entries = 0;
     EndOfDirectory eod;
     while (start_of_directory == -1) {
         int pos = device->size() - sizeof(EndOfDirectory) - i;
         if (pos < 0 || i > 65535) {
             qWarning() << "QZip: EndOfDirectory not found";
             return;
         }
         device->seek(pos);
         device->read((char *)&eod, sizeof(EndOfDirectory));
         if (readUInt(eod.signature) == 0x06054b50)
             break;
         ++i;
     }
     // have the eod
     start_of_directory = readUInt(eod.dir_start_offset);
     num_dir_entries = readUShort(eod.num_dir_entries);
     ZDEBUG("start_of_directory at %d, num_dir_entries=%d", start_of_directory, num_dir_entries);
     int comment_length = readUShort(eod.comment_length);
     if (comment_length != i)
         qWarning() << "QZip: failed to parse zip file.";
     comment = device->read(qMin(comment_length, i));
     device->seek(start_of_directory);
     for (i = 0; i < num_dir_entries; ++i) {
         FileHeader header;
         int read = device->read((char *) &header.h, sizeof(CentralFileHeader));
         if (read < (int)sizeof(CentralFileHeader)) {
             qWarning() << "QZip: Failed to read complete header, index may be incomplete";
             break;
         }
         if (readUInt(header.h.signature) != 0x02014b50) {
             qWarning() << "QZip: invalid header signature, index may be incomplete";
             break;
         }
         int l = readUShort(header.h.file_name_length);
         header.file_name = device->read(l);
         if (header.file_name.length() != l) {
             qWarning() << "QZip: Failed to read filename from zip index, index may be incomplete";
             break;
         }
         l = readUShort(header.h.extra_field_length);
         header.extra_field = device->read(l);
         if (header.extra_field.length() != l) {
             qWarning() << "QZip: Failed to read extra field in zip file, skipping file, index may be incomplete";
             break;
         }
         l = readUShort(header.h.file_comment_length);
         header.file_comment = device->read(l);
         if (header.file_comment.length() != l) {
             qWarning() << "QZip: Failed to read read file comment, index may be incomplete";
             break;
         }
         ZDEBUG("found file '%s'", header.file_name.data());
         fileHeaders.append(header);
     }
 }
Properties
status
QZipReader::Status QZipReaderPrivate::status
Definition at line 440 of file qzip.cpp.
Referenced by QZipWriter::QZipWriter(), and QZipReader::status().
The documentation for this class was generated from the following file:
/src/gui/text/qzip.cpp