Qt 4.8: QDeclarativeJS::NameId Class Reference
QDeclarativeJS::NameId Class Reference
#include <qdeclarativejsengine_p.h>
Public Functions
const QString asString () const
NameId (const QChar *u, int s)
bool operator!= (const NameId &other) const
bool operator< (const NameId &other) const
bool operator== (const NameId &other) const
Properties
QString _text
Detailed Description
Definition at line 65 of file qdeclarativejsengine_p.h.
Constructors and Destructors
NameId()
QDeclarativeJS::NameId::NameId (const QChar * u, int s) inline
Definition at line 70 of file qdeclarativejsengine_p.h.
         : _text(u, s)
     { }
Functions
asString()
const QString QDeclarativeJS::NameId::asString () const inline
Definition at line 74 of file qdeclarativejsengine_p.h.
Referenced by QDeclarativeParser::Variant::asStringList(), astNodeToStringList(), and QDeclarativeBindingCompilerPrivate::buildName().
     { return _text; }
operator!=()
bool QDeclarativeJS::NameId::operator!= (const NameId & other) const inline
Definition at line 80 of file qdeclarativejsengine_p.h.
     { return _text != other._text; }
operator<()
bool QDeclarativeJS::NameId::operator< (const NameId & other) const inline
Definition at line 83 of file qdeclarativejsengine_p.h.
     { return _text < other._text; }
operator==()
bool QDeclarativeJS::NameId::operator== (const NameId & other) const inline
Definition at line 77 of file qdeclarativejsengine_p.h.
     { return _text == other._text; }
Properties
_text
QString QDeclarativeJS::NameId::_text private
Definition at line 67 of file qdeclarativejsengine_p.h.
Referenced by operator!=(), operator<(), and operator==().
The documentation for this class was generated from the following file:
/src/declarative/qml/parser/qdeclarativejsengine_p.h