Qt 4.8: QUndoStack Class Reference
QUndoStack Class Reference
The QUndoStack class is a stack of QUndoCommand objects.
#include <qundostack.h>
Public Slots
void redo ()
Redoes the current command by calling QUndoCommand::redo().
void setActive (bool active=true)
void setClean ()
Marks the stack as clean and emits cleanChanged() if the stack was not already clean.
void setIndex (int idx)
Repeatedly calls undo() or redo() until the current command index reaches idx.
void undo ()
Undoes the command below the current command by calling QUndoCommand::undo().
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void canRedoChanged (bool canRedo)
This signal is emitted whenever the value of canRedo() changes.
void canUndoChanged (bool canUndo)
This signal is emitted whenever the value of canUndo() changes.
void cleanChanged (bool clean)
This signal is emitted whenever the stack enters or leaves the clean state.
void indexChanged (int idx)
This signal is emitted whenever a command modifies the state of the document.
void redoTextChanged (const QString &redoText)
This signal is emitted whenever the value of redoText() changes.
void undoTextChanged (const QString &undoText)
This signal is emitted whenever the value of undoText() changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void beginMacro (const QString &text)
Begins composition of a macro command with the given text description.
bool canRedo () const
Returns true if there is a command available for redo; otherwise returns false.
bool canUndo () const
Returns true if there is a command available for undo; otherwise returns false.
int cleanIndex () const
Returns the clean index.
void clear ()
Clears the command stack by deleting all commands on it, and returns the stack to the clean state.
const QUndoCommand * command (int index) const
Returns a const pointer to the command at index.
int count () const
Returns the number of commands on the stack.
QAction * createRedoAction (QObject *parent, const QString &prefix=QString()) const
Creates an redo QAction object with the given parent.
QAction * createUndoAction (QObject *parent, const QString &prefix=QString()) const
Creates an undo QAction object with the given parent.
void endMacro ()
Ends composition of a macro command.
int index () const
Returns the index of the current command.
bool isActive () const
bool isClean () const
If the stack is in the clean state, returns true; otherwise returns false.
void push (QUndoCommand *cmd)
Pushes cmd on the stack or merges it with the most recently executed command.
QUndoStack (QObject *parent=0)
Constructs an empty undo stack with the parent parent.
QString redoText () const
Returns the text of the command which will be redone in the next call to redo().
void setUndoLimit (int limit)
QString text (int idx) const
Returns the text of the command at index idx.
int undoLimit () const
QString undoText () const
Returns the text of the command which will be undone in the next call to undo().
~QUndoStack ()
Destroys the undo stack, deleting any commands that are on it.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool active
the active status of this stack.
int undoLimit
the maximum number of commands on this stack.
Friends
class QUndoGroup
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QUndoStack class is a stack of QUndoCommand objects.
Since
4.2
For an overview of Qt's Undo Framework, see the Overview of Qt's Undo Framework{overview document}.
An undo stack maintains a stack of commands that have been applied to a document.
New commands are pushed on the stack using push(). Commands can be undone and redone using undo() and redo(), or by triggering the actions returned by createUndoAction() and createRedoAction().
QUndoStack keeps track of the current command. This is the command which will be executed by the next call to redo(). The index of this command is returned by index(). The state of the edited object can be rolled forward or back using setIndex(). If the top-most command on the stack has already been redone, index() is equal to count().
QUndoStack provides support for undo and redo actions, command compression, command macros, and supports the concept of a clean state.
Undo and Redo Actions
QUndoStack provides convenient undo and redo QAction objects, which can be inserted into a menu or a toolbar. When commands are undone or redone, QUndoStack updates the text properties of these actions to reflect what change they will trigger. The actions are also disabled when no command is available for undo or redo. These actions are returned by QUndoStack::createUndoAction() and QUndoStack::createRedoAction().
Command Compression and Macros
Command compression is useful when several commands can be compressed into a single command that can be undone and redone in a single operation. For example, when a user types a character in a text editor, a new command is created. This command inserts the character into the document at the cursor position. However, it is more convenient for the user to be able to undo or redo typing of whole words, sentences, or paragraphs. Command compression allows these single-character commands to be merged into a single command which inserts or deletes sections of text. For more information, see QUndoCommand::mergeWith() and push().
A command macro is a sequence of commands, all of which are undone and redone in one go. Command macros are created by giving a command a list of child commands. Undoing or redoing the parent command will cause the child commands to be undone or redone. Command macros may be created explicitly by specifying a parent in the QUndoCommand constructor, or by using the convenience functions beginMacro() and endMacro().
Although command compression and macros appear to have the same effect to the user, they often have different uses in an application. Commands that perform small changes to a document may be usefully compressed if there is no need to individually record them, and if only larger changes are relevant to the user. However, for commands that need to be recorded individually, or those that cannot be compressed, it is useful to use macros to provide a more convenient user experience while maintaining a record of each command.
Clean State
QUndoStack supports the concept of a clean state. When the document is saved to disk, the stack can be marked as clean using setClean(). Whenever the stack returns to this state through undoing and redoing commands, it emits the signal cleanChanged(). This signal is also emitted when the stack leaves the clean state. This signal is usually used to enable and disable the save actions in the application, and to update the document's title to reflect that it contains unsaved changes.
See also
QUndoCommand, QUndoView
Definition at line 91 of file qundostack.h.
Constructors and Destructors
QUndoStack()
QUndoStack::QUndoStack (QObject * parent = 0) explicit
Constructs an empty undo stack with the parent parent.
The stack will initially be in the clean state. If parent is a QUndoGroup object, the stack is automatically added to the group.
See also
push()
Definition at line 513 of file qundostack.cpp.
     : QObject(*(new QUndoStackPrivate), parent)
 {
 #ifndef QT_NO_UNDOGROUP
     if (QUndoGroup *group = qobject_cast<QUndoGroup*>(parent))
         group->addStack(this);
 #endif
 }
~QUndoStack()
QUndoStack::~QUndoStack ()
Destroys the undo stack, deleting any commands that are on it.
If the stack is in a QUndoGroup, the stack is automatically removed from the group.
See also
QUndoStack()
Definition at line 529 of file qundostack.cpp.
 {
 #ifndef QT_NO_UNDOGROUP
     Q_D(QUndoStack);
     if (d->group != 0)
         d->group->removeStack(this);
 #endif
     clear();
 }
Functions
beginMacro()
void QUndoStack::beginMacro (const QString & text)
Begins composition of a macro command with the given text description.
An empty command described by the specified text is pushed on the stack. Any subsequent commands pushed on the stack will be appended to the empty command's children until endMacro() is called.
Calls to beginMacro() and endMacro() may be nested, but every call to beginMacro() must have a matching call to endMacro().
While a macro is composed, the stack is disabled. This means that:
indexChanged() and cleanChanged() are not emitted,
canUndo() and canRedo() return false,
calling undo() or redo() has no effect,
the undo/redo actions are disabled.
The stack becomes enabled and appropriate signals are emitted when endMacro() is called for the outermost macro.
stack.beginMacro("insert red text");
stack.push(new InsertText(document, idx, text));
stack.push(new SetColor(document, idx, text.length(), Qt::red));
stack.endMacro(); // indexChanged() is emitted
This code is equivalent to:
QUndoCommand *insertRed = new QUndoCommand(); // an empty command
insertRed->setText("insert red text");
new InsertText(document, idx, text, insertRed); // becomes child of insertRed
new SetColor(document, idx, text.length(), Qt::red, insertRed);
stack.push(insertRed);
See also
endMacro()
Definition at line 972 of file qundostack.cpp.
 {
     Q_D(QUndoStack);
     QUndoCommand *cmd = new QUndoCommand();
     cmd->setText(text);
     if (d->macro_stack.isEmpty()) {
         while (d->index < d->command_list.size())
             delete d->command_list.takeLast();
         if (d->clean_index > d->index)
             d->clean_index = -1; // we've deleted the clean state
         d->command_list.append(cmd);
     } else {
         d->macro_stack.last()->d->child_list.append(cmd);
     }
     d->macro_stack.append(cmd);
     if (d->macro_stack.count() == 1) {
         emit canUndoChanged(false);
         emit undoTextChanged(QString());
         emit canRedoChanged(false);
         emit redoTextChanged(QString());
     }
 }
canRedo()
bool QUndoStack::canRedo () const
Returns true if there is a command available for redo; otherwise returns false.
This function returns false if the stack is empty or if the top command on the stack has already been redone.
Synonymous with index() == count().
See also
index() canUndo()
Definition at line 838 of file qundostack.cpp.
Referenced by createRedoAction(), and push().
 {
     Q_D(const QUndoStack);
     if (!d->macro_stack.isEmpty())
         return false;
     return d->index < d->command_list.size();
 }
canRedoChanged
void QUndoStack::canRedoChanged (bool canRedo) signal
This signal is emitted whenever the value of canRedo() changes.
It is used to enable or disable the redo action returned by createRedoAction(). canRedo specifies the new value.
Referenced by beginMacro(), clear(), createRedoAction(), and push().
canUndo()
bool QUndoStack::canUndo () const
Returns true if there is a command available for undo; otherwise returns false.
This function returns false if the stack is empty, or if the bottom command on the stack has already been undone.
Synonymous with index() == 0.
See also
index() canRedo()
Definition at line 819 of file qundostack.cpp.
Referenced by createUndoAction(), and push().
 {
     Q_D(const QUndoStack);
     if (!d->macro_stack.isEmpty())
         return false;
     return d->index > 0;
 }
canUndoChanged
void QUndoStack::canUndoChanged (bool canUndo) signal
This signal is emitted whenever the value of canUndo() changes.
It is used to enable or disable the undo action returned by createUndoAction(). canUndo specifies the new value.
Referenced by beginMacro(), clear(), createUndoAction(), and push().
cleanChanged
void QUndoStack::cleanChanged (bool clean) signal
This signal is emitted whenever the stack enters or leaves the clean state.
If clean is true, the stack is in a clean state; otherwise this signal indicates that it has left the clean state.
See also
isClean() setClean()
Referenced by clear().
cleanIndex()
int QUndoStack::cleanIndex () const
Returns the clean index.
This is the index at which setClean() was called.
A stack may not have a clean index. This happens if a document is saved, some commands are undone, then a new command is pushed. Since push() deletes all the undone commands before pushing the new command, the stack can't return to the clean state again. In this case, this function returns -1.
See also
isClean() setClean()
Definition at line 694 of file qundostack.cpp.
Referenced by QUndoModel::data().
 {
     Q_D(const QUndoStack);
     return d->clean_index;
 }
clear()
void QUndoStack::clear ()
Clears the command stack by deleting all commands on it, and returns the stack to the clean state.
Commands are not undone or redone; the state of the edited object remains unchanged.
This function is usually used when the contents of the document are abandoned.
See also
QUndoStack()
Definition at line 552 of file qundostack.cpp.
Referenced by ~QUndoStack().
 {
     Q_D(QUndoStack);
     if (d->command_list.isEmpty())
         return;
     bool was_clean = isClean();
     d->macro_stack.clear();
     qDeleteAll(d->command_list);
     d->command_list.clear();
     d->index = 0;
     d->clean_index = 0;
     emit indexChanged(0);
     emit canUndoChanged(false);
     emit undoTextChanged(QString());
     emit canRedoChanged(false);
     emit redoTextChanged(QString());
     if (!was_clean)
         emit cleanChanged(true);
 }
command()
const QUndoCommand * QUndoStack::command (int index) const
Returns a const pointer to the command at index.
Since
4.4
This function returns a const pointer, because modifying a command, once it has been pushed onto the stack and executed, almost always causes corruption of the state of the document, if the command is later undone or redone.
See also
QUndoCommand::child()
Definition at line 1037 of file qundostack.cpp.
 {
     Q_D(const QUndoStack);
     if (index < 0 || index >= d->command_list.count())
         return 0;
     return d->command_list.at(index);
 }
count()
int QUndoStack::count () const
Returns the number of commands on the stack.
Macro commands are counted as one command.
See also
index() setIndex() command()
Definition at line 758 of file qundostack.cpp.
Referenced by QUndoModel::data(), QUndoModel::index(), and QUndoModel::rowCount().
 {
     Q_D(const QUndoStack);
     return d->command_list.size();
 }
createRedoAction()
QAction * QUndoStack::createRedoAction (QObject * parent, const QString & prefix = QString()) const
Creates an redo QAction object with the given parent.
Triggering this action will cause a call to redo(). The text of this action is the text of the command which will be redone in the next call to redo(), prefixed by the specified prefix. If there is no command available for redo, this action will be disabled.
If prefix is empty, the default template "Redo %1" is used instead of prefix. Before Qt 4.8, the prefix "Redo" was used by default.
See also
createUndoAction(), canRedo(), QUndoCommand::text()
Definition at line 924 of file qundostack.cpp.
 {
     QUndoAction *result = new QUndoAction(prefix, parent);
     if (prefix.isEmpty())
         result->setTextFormat(tr("Redo %1"), tr("Redo", "Default text for redo action"));
     result->setEnabled(canRedo());
     result->setPrefixedText(redoText());
     connect(this, SIGNAL(canRedoChanged(bool)),
             result, SLOT(setEnabled(bool)));
     connect(this, SIGNAL(redoTextChanged(QString)),
             result, SLOT(setPrefixedText(QString)));
     connect(result, SIGNAL(triggered()), this, SLOT(redo()));
     return result;
 }
createUndoAction()
QAction * QUndoStack::createUndoAction (QObject * parent, const QString & prefix = QString()) const
Creates an undo QAction object with the given parent.
Triggering this action will cause a call to undo(). The text of this action is the text of the command which will be undone in the next call to undo(), prefixed by the specified prefix. If there is no command available for undo, this action will be disabled.
If prefix is empty, the default template "Undo %1" is used instead of prefix. Before Qt 4.8, the prefix "Undo" was used by default.
See also
createRedoAction(), canUndo(), QUndoCommand::text()
Definition at line 894 of file qundostack.cpp.
 {
     QUndoAction *result = new QUndoAction(prefix, parent);
     if (prefix.isEmpty())
         result->setTextFormat(tr("Undo %1"), tr("Undo", "Default text for undo action"));
     result->setEnabled(canUndo());
     result->setPrefixedText(undoText());
     connect(this, SIGNAL(canUndoChanged(bool)),
             result, SLOT(setEnabled(bool)));
     connect(this, SIGNAL(undoTextChanged(QString)),
             result, SLOT(setPrefixedText(QString)));
     connect(result, SIGNAL(triggered()), this, SLOT(undo()));
     return result;
 }
endMacro()
void QUndoStack::endMacro ()
Ends composition of a macro command.
If this is the outermost macro in a set nested macros, this function emits indexChanged() once for the entire macro command.
See also
beginMacro()
Definition at line 1006 of file qundostack.cpp.
 {
     Q_D(QUndoStack);
     if (d->macro_stack.isEmpty()) {
         qWarning("QUndoStack::endMacro(): no matching beginMacro()");
         return;
     }
     d->macro_stack.removeLast();
     if (d->macro_stack.isEmpty()) {
         d->checkUndoLimit();
         d->setIndex(d->index + 1, false);
     }
 }
index()
int QUndoStack::index () const
Returns the index of the current command.
This is the command that will be executed on the next call to redo(). It is not always the top-most command on the stack, since a number of commands may have been undone.
See also
undo() redo() count()
Definition at line 772 of file qundostack.cpp.
Referenced by QUndoModel::selectedIndex().
 {
     Q_D(const QUndoStack);
     return d->index;
 }
indexChanged
void QUndoStack::indexChanged (int idx) signal
This signal is emitted whenever a command modifies the state of the document.
This happens when a command is undone or redone. When a macro command is undone or redone, or setIndex() is called, this signal is emitted only once.
idx specifies the index of the current command, ie. the command which will be executed on the next call to redo().
See also
index() setIndex()
Referenced by clear(), and push().
isActive()
bool QUndoStack::isActive () const
Definition at line 1137 of file qundostack.cpp.
 {
 #ifdef QT_NO_UNDOGROUP
     return true;
 #else
     Q_D(const QUndoStack);
     return d->group == 0 || d->group->activeStack() == this;
 #endif
 }
isClean()
bool QUndoStack::isClean () const
If the stack is in the clean state, returns true; otherwise returns false.
See also
setClean() cleanIndex()
Definition at line 675 of file qundostack.cpp.
Referenced by clear().
 {
     Q_D(const QUndoStack);
     if (!d->macro_stack.isEmpty())
         return false;
     return d->clean_index == d->index;
 }
push()
void QUndoStack::push (QUndoCommand * cmd)
Pushes cmd on the stack or merges it with the most recently executed command.
In either case, executes cmd by calling its redo() function.
If cmd's id is not -1, and if the id is the same as that of the most recently executed command, QUndoStack will attempt to merge the two commands by calling QUndoCommand::mergeWith() on the most recently executed command. If QUndoCommand::mergeWith() returns true, cmd is deleted.
In all other cases cmd is simply pushed on the stack.
If commands were undone before cmd was pushed, the current command and all commands above it are deleted. Hence cmd always ends up being the top-most on the stack.
Once a command is pushed, the stack takes ownership of it. There are no getters to return the command, since modifying it after it has been executed will almost always lead to corruption of the document's state.
See also
QUndoCommand::id() QUndoCommand::mergeWith()
Definition at line 601 of file qundostack.cpp.
 {
     Q_D(QUndoStack);
     cmd->redo();
     bool macro = !d->macro_stack.isEmpty();
     QUndoCommand *cur = 0;
     if (macro) {
         QUndoCommand *macro_cmd = d->macro_stack.last();
         if (!macro_cmd->d->child_list.isEmpty())
             cur = macro_cmd->d->child_list.last();
     } else {
         if (d->index > 0)
             cur = d->command_list.at(d->index - 1);
         while (d->index < d->command_list.size())
             delete d->command_list.takeLast();
         if (d->clean_index > d->index)
             d->clean_index = -1; // we've deleted the clean state
     }
     bool try_merge = cur != 0
                         && cur->id() != -1
                         && cur->id() == cmd->id()
                         && (macro || d->index != d->clean_index);
     if (try_merge && cur->mergeWith(cmd)) {
         delete cmd;
         if (!macro) {
             emit indexChanged(d->index);
             emit canUndoChanged(canUndo());
             emit undoTextChanged(undoText());
             emit canRedoChanged(canRedo());
             emit redoTextChanged(redoText());
         }
     } else {
         if (macro) {
             d->macro_stack.last()->d->child_list.append(cmd);
         } else {
             d->command_list.append(cmd);
             d->checkUndoLimit();
             d->setIndex(d->index + 1, false);
         }
     }
 }
redo
void QUndoStack::redo () slot
Redoes the current command by calling QUndoCommand::redo().
Increments the current command index.
If the stack is empty, or if the top command on the stack has already been redone, this function does nothing.
See also
undo() index()
Definition at line 736 of file qundostack.cpp.
Referenced by createRedoAction().
 {
     Q_D(QUndoStack);
     if (d->index == d->command_list.size())
         return;
     if (!d->macro_stack.isEmpty()) {
         qWarning("QUndoStack::redo(): cannot redo in the middle of a macro");
         return;
     }
     d->command_list.at(d->index)->redo();
     d->setIndex(d->index + 1, false);
 }
redoText()
QString QUndoStack::redoText () const
Returns the text of the command which will be redone in the next call to redo().
See also
QUndoCommand::actionText() undoText()
Definition at line 868 of file qundostack.cpp.
Referenced by createRedoAction(), and push().
 {
     Q_D(const QUndoStack);
     if (!d->macro_stack.isEmpty())
         return QString();
     if (d->index < d->command_list.size())
         return d->command_list.at(d->index)->actionText();
     return QString();
 }
redoTextChanged
void QUndoStack::redoTextChanged (const QString & redoText) signal
This signal is emitted whenever the value of redoText() changes.
It is used to update the text property of the redo action returned by createRedoAction(). redoText specifies the new text.
Referenced by beginMacro(), clear(), createRedoAction(), and push().
setActive
void QUndoStack::setActive (bool active = true) slot
Definition at line 1121 of file qundostack.cpp.
 {
 #ifdef QT_NO_UNDOGROUP
     Q_UNUSED(active);
 #else
     Q_D(QUndoStack);
     if (d->group != 0) {
         if (active)
             d->group->setActiveStack(this);
         else if (d->group->activeStack() == this)
             d->group->setActiveStack(0);
     }
 #endif
 }
setClean
void QUndoStack::setClean () slot
Marks the stack as clean and emits cleanChanged() if the stack was not already clean.
Whenever the stack returns to this state through the use of undo/redo commands, it emits the signal cleanChanged(). This signal is also emitted when the stack leaves the clean state.
See also
isClean(), cleanIndex()
Definition at line 658 of file qundostack.cpp.
 {
     Q_D(QUndoStack);
     if (!d->macro_stack.isEmpty()) {
         qWarning("QUndoStack::setClean(): cannot set clean in the middle of a macro");
         return;
     }
     d->setIndex(d->index, true);
 }
setIndex
void QUndoStack::setIndex (int idx) slot
Repeatedly calls undo() or redo() until the current command index reaches idx.
This function can be used to roll the state of the document forwards of backwards. indexChanged() is emitted only once.
See also
index() count() undo() redo()
Definition at line 786 of file qundostack.cpp.
Referenced by QUndoModel::setStackCurrentIndex().
 {
     Q_D(QUndoStack);
     if (!d->macro_stack.isEmpty()) {
         qWarning("QUndoStack::setIndex(): cannot set index in the middle of a macro");
         return;
     }
     if (idx < 0)
         idx = 0;
     else if (idx > d->command_list.size())
         idx = d->command_list.size();
     int i = d->index;
     while (i < idx)
         d->command_list.at(i++)->redo();
     while (i > idx)
         d->command_list.at(--i)->undo();
     d->setIndex(idx, false);
 }
setUndoLimit()
void QUndoStack::setUndoLimit (int limit)
Definition at line 1079 of file qundostack.cpp.
 {
     Q_D(QUndoStack);
     if (!d->command_list.isEmpty()) {
         qWarning("QUndoStack::setUndoLimit(): an undo limit can only be set when the stack is empty");
         return;
     }
     if (limit == d->undo_limit)
         return;
     d->undo_limit = limit;
     d->checkUndoLimit();
 }
text()
QString QUndoStack::text (int idx) const
Returns the text of the command at index idx.
See also
beginMacro()
Definition at line 1052 of file qundostack.cpp.
Referenced by QUndoModel::data().
 {
     Q_D(const QUndoStack);
     if (idx < 0 || idx >= d->command_list.size())
         return QString();
     return d->command_list.at(idx)->text();
 }
undo
void QUndoStack::undo () slot
Undoes the command below the current command by calling QUndoCommand::undo().
Decrements the current command index.
If the stack is empty, or if the bottom command on the stack has already been undone, this function does nothing.
See also
redo() index()
Definition at line 710 of file qundostack.cpp.
Referenced by createUndoAction().
 {
     Q_D(QUndoStack);
     if (d->index == 0)
         return;
     if (!d->macro_stack.isEmpty()) {
         qWarning("QUndoStack::undo(): cannot undo in the middle of a macro");
         return;
     }
     int idx = d->index - 1;
     d->command_list.at(idx)->undo();
     d->setIndex(idx, false);
 }
undoLimit()
int QUndoStack::undoLimit () const
Referenced by setUndoLimit().
undoText()
QString QUndoStack::undoText () const
Returns the text of the command which will be undone in the next call to undo().
See also
QUndoCommand::actionText() redoText()
Definition at line 852 of file qundostack.cpp.
Referenced by createUndoAction(), and push().
 {
     Q_D(const QUndoStack);
     if (!d->macro_stack.isEmpty())
         return QString();
     if (d->index > 0)
         return d->command_list.at(d->index - 1)->actionText();
     return QString();
 }
undoTextChanged
void QUndoStack::undoTextChanged (const QString & undoText) signal
This signal is emitted whenever the value of undoText() changes.
It is used to update the text property of the undo action returned by createUndoAction(). undoText specifies the new text.
Referenced by beginMacro(), clear(), createUndoAction(), and push().
Friends and Related Functions
QUndoGroup
friend class QUndoGroup friend
Definition at line 150 of file qundostack.h.
Properties
active
QUndoStack::active private
the active status of this stack.
An application often has multiple undo stacks, one for each opened document. The active stack is the one associated with the currently active document. If the stack belongs to a QUndoGroup, calls to QUndoGroup::undo() or QUndoGroup::redo() will be forwarded to this stack when it is active. If the QUndoGroup is watched by a QUndoView, the view will display the contents of this stack when it is active. If the stack does not belong to a QUndoGroup, making it active has no effect.
It is the programmer's responsibility to specify which stack is active by calling setActive(), usually when the associated document window receives focus.
See also
QUndoGroup
Definition at line 95 of file qundostack.h.
undoLimit
int QUndoStack::undoLimit private
the maximum number of commands on this stack.
Since
4.3
When the number of commands on a stack exceedes the stack's undoLimit, commands are deleted from the bottom of the stack. Macro commands (commands with child commands) are treated as one command. The default value is 0, which means that there is no limit.
This property may only be set when the undo stack is empty, since setting it on a non-empty stack might delete the command at the current index. Calling setUndoLimit() on a non-empty stack prints a warning and does nothing.
Definition at line 96 of file qundostack.h.
The documentation for this class was generated from the following files:
/src/gui/util/qundostack.h
/src/gui/util/qundostack.cpp