Qt 4.8: QScriptMessageHandlerInterface Class Reference
QScriptMessageHandlerInterface Class Reference abstract
#include <qscriptmessagehandlerinterface_p.h>
Public Functions
virtual void message (QtMsgType type, const QString &text, const QString &fileName=QString(), int lineNumber=-1, int columnNumber=-1, const QVariant &data=QVariant())=0
virtual ~QScriptMessageHandlerInterface ()
Detailed Description
Definition at line 62 of file qscriptmessagehandlerinterface_p.h.
Constructors and Destructors
~QScriptMessageHandlerInterface()
virtual QScriptMessageHandlerInterface::~QScriptMessageHandlerInterface () inline virtual
Definition at line 65 of file qscriptmessagehandlerinterface_p.h.
 {}
Functions
message()
virtual void QScriptMessageHandlerInterface::message (QtMsgType type, const QString & text, const QString & fileName = QString(), int lineNumber = -1, int columnNumber = -1, const QVariant & data = QVariant()) pure virtual
Implemented in QScriptStdMessageHandler, QScriptDebuggerConsoleWidget, QScriptDebugOutputWidget, and QScriptErrorLogWidget.
Referenced by QScriptDebuggerConsolePrivate::createJob(), QScriptDebuggerPrivate::debuggerEvent(), QScriptDebuggerScriptedConsoleCommand::parse(), and QScriptDebuggerConsole::showDebuggerInfoMessage().
The documentation for this class was generated from the following file:
/src/scripttools/debugging/qscriptmessagehandlerinterface_p.h