Qt 4.8: QAccessibleAbstractScrollArea Class Reference
QAccessibleAbstractScrollArea Class Reference
#include <complexwidgets.h>
Public Types
enum AbstractScrollAreaElement {
Self = 0, Viewport, HorizontalContainer, VerticalContainer,
CornerWidget, Undefined
}
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Public Functions
QAbstractScrollArea * abstractScrollArea () const
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethodEx (QAccessible::Method method, int child, const QVariantList &params)
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
int navigate (RelationFlag relation, int entry, QAccessibleInterface **target) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QAccessibleAbstractScrollArea (QWidget *widget)
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
void setText (Text textType, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
QString text (Text textType, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleWidgetEx
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleObjectEx
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Private Functions
QWidgetList accessibleChildren () const
AbstractScrollAreaElement elementType (QWidget *widget) const
bool isLeftToRight () const
Additional Inherited Members
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Protected Functions inherited from QAccessibleWidgetEx
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Detailed Description
Definition at line 63 of file complexwidgets.h.
Enumerations
AbstractScrollAreaElement
enum QAccessibleAbstractScrollArea::AbstractScrollAreaElement
Enumerator
Self
Viewport
HorizontalContainer
VerticalContainer
CornerWidget
Undefined
Definition at line 68 of file complexwidgets.h.
{
         Self = 0,
         Viewport,
         HorizontalContainer,
         VerticalContainer,
         CornerWidget,
         Undefined
     };
Constructors and Destructors
QAccessibleAbstractScrollArea()
QAccessibleAbstractScrollArea::QAccessibleAbstractScrollArea (QWidget * widget) explicit
Definition at line 1943 of file complexwidgets.cpp.
     : QAccessibleWidgetEx(widget, Client)
 {
     Q_ASSERT(qobject_cast<QAbstractScrollArea *>(widget));
 }
Functions
abstractScrollArea()
QAbstractScrollArea * QAccessibleAbstractScrollArea::abstractScrollArea () const
Definition at line 2182 of file complexwidgets.cpp.
Referenced by accessibleChildren(), childAt(), elementType(), isLeftToRight(), isValid(), navigate(), and rect().
 {
     return static_cast<QAbstractScrollArea *>(object());
 }
accessibleChildren()
QWidgetList QAccessibleAbstractScrollArea::accessibleChildren () const private
Definition at line 2187 of file complexwidgets.cpp.
Referenced by childAt(), childCount(), indexOfChild(), navigate(), rect(), setText(), state(), and text().
 {
     QWidgetList children;
     // Viewport.
     QWidget * viewport = abstractScrollArea()->viewport();
     if (viewport)
         children.append(viewport);
     // Horizontal scrollBar container.
     QScrollBar *horizontalScrollBar = abstractScrollArea()->horizontalScrollBar();
     if (horizontalScrollBar && horizontalScrollBar->isVisible()) {
         children.append(horizontalScrollBar->parentWidget());
     }
     // Vertical scrollBar container.
     QScrollBar *verticalScrollBar = abstractScrollArea()->verticalScrollBar();
     if (verticalScrollBar && verticalScrollBar->isVisible()) {
         children.append(verticalScrollBar->parentWidget());
     }
     // CornerWidget.
     QWidget *cornerWidget = abstractScrollArea()->cornerWidget();
     if (cornerWidget && cornerWidget->isVisible())
         children.append(cornerWidget);
     return children;
 }
childAt()
int QAccessibleAbstractScrollArea::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 2156 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::childAt().
 {
     if (!abstractScrollArea()->isVisible())
         return -1;
 #if 0
     const QRect globalSelfGeometry = rect(Self);
     if (!globalSelfGeometry.isValid() || !globalSelfGeometry.contains(QPoint(x, y)))
         return -1;
     const QWidgetList children = accessibleChildren();
     for (int i = 0; i < children.count(); ++i) {
         const QWidget *child = children.at(i);
         const QRect globalChildGeometry = QRect(child->mapToGlobal(QPoint(0, 0)), child->size());
         if (globalChildGeometry.contains(QPoint(x, y))) {
             return ++i;
         }
     }
     return 0;
 #else
     for (int i = childCount(); i >= 0; --i) {
         if (rect(i).contains(x, y))
             return i;
     }
     return -1;
 #endif
 }
childCount()
int QAccessibleAbstractScrollArea::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 2002 of file complexwidgets.cpp.
Referenced by childAt(), and QAccessibleItemView::childCount().
 {
     return accessibleChildren().count();
 }
elementType()
QAccessibleAbstractScrollArea::AbstractScrollAreaElement QAccessibleAbstractScrollArea::elementType (QWidget * widget) const private
Definition at line 2217 of file complexwidgets.cpp.
Referenced by navigate().
 {
     if (!widget)
         return Undefined;
     if (widget == abstractScrollArea())
         return Self;
     if (widget == abstractScrollArea()->viewport())
         return Viewport;
     if (widget->objectName() == QLatin1String("qt_scrollarea_hcontainer"))
         return HorizontalContainer;
     if (widget->objectName() == QLatin1String("qt_scrollarea_vcontainer"))
         return VerticalContainer;
     if (widget == abstractScrollArea()->cornerWidget())
         return CornerWidget;
     return Undefined;
 }
indexOfChild()
int QAccessibleAbstractScrollArea::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 2007 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::indexOfChild().
 {
     if (!child || !child->object())
         return -1;
     int index = accessibleChildren().indexOf(qobject_cast<QWidget *>(child->object()));
     if (index >= 0)
         return ++index;
     return -1;
 }
invokeMethodEx()
QVariant QAccessibleAbstractScrollArea::invokeMethodEx (QAccessible::Method method, int child, const QVariantList & params) virtual
Reimplemented from QAccessibleWidgetEx.
Definition at line 1997 of file complexwidgets.cpp.
 {
     return QVariant();
 }
isLeftToRight()
bool QAccessibleAbstractScrollArea::isLeftToRight () const private
Definition at line 2236 of file complexwidgets.cpp.
Referenced by navigate().
 {
     return abstractScrollArea()->isLeftToRight();
 }
isValid()
bool QAccessibleAbstractScrollArea::isValid () const virtual
Returns true if all the data necessary to use this interface implementation is valid (e.
g. all pointers are non-null); otherwise returns false.
See also
object()
Reimplemented from QAccessibleObjectEx.
Reimplemented in QAccessibleItemView.
Definition at line 2017 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::isValid().
 {
     return (QAccessibleWidgetEx::isValid() && abstractScrollArea() && abstractScrollArea()->viewport());
 }
navigate()
int QAccessibleAbstractScrollArea::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 2022 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::navigate().
 {
     if (!target)
         return -1;
     *target = 0;
     QWidget *targetWidget = 0;
     QWidget *entryWidget = 0;
     if (relation == Child ||
         relation == Left || relation == Up || relation == Right || relation == Down) {
         QWidgetList children = accessibleChildren();
         if (entry < 0 || entry > children.count())
             return -1;
         if (entry == Self)
             entryWidget = abstractScrollArea();
         else
             entryWidget = children.at(entry - 1);
         AbstractScrollAreaElement entryElement = elementType(entryWidget);
         // Not one of the most beautiful switches I've ever seen, but I believe it has
         // to be like this since each case need special handling.
         // It might be possible to make it more general, but I'll leave that as an exercise
         // to the reader. :-)
         switch (relation) {
         case Child:
             if (entry > 0)
                 targetWidget = children.at(entry - 1);
             break;
         case Left:
             if (entry < 1)
                 break;
             switch (entryElement) {
             case Viewport:
                 if (!isLeftToRight())
                     targetWidget = abstractScrollArea()->verticalScrollBar();
                 break;
             case HorizontalContainer:
                 if (!isLeftToRight())
                     targetWidget = abstractScrollArea()->cornerWidget();
                 break;
             case VerticalContainer:
                 if (isLeftToRight())
                     targetWidget = abstractScrollArea()->viewport();
                 break;
             case CornerWidget:
                 if (isLeftToRight())
                     targetWidget = abstractScrollArea()->horizontalScrollBar();
                 break;
             default:
                 break;
             }
             break;
         case Right:
             if (entry < 1)
                 break;
             switch (entryElement) {
             case Viewport:
                 if (isLeftToRight())
                     targetWidget = abstractScrollArea()->verticalScrollBar();
                 break;
             case HorizontalContainer:
                 targetWidget = abstractScrollArea()->cornerWidget();
                 break;
             case VerticalContainer:
                 if (!isLeftToRight())
                     targetWidget = abstractScrollArea()->viewport();
                 break;
             case CornerWidget:
                 if (!isLeftToRight())
                     targetWidget = abstractScrollArea()->horizontalScrollBar();
                 break;
             default:
                 break;
             }
             break;
         case Up:
             if (entry < 1)
                 break;
             switch (entryElement) {
             case HorizontalContainer:
                 targetWidget = abstractScrollArea()->viewport();
                 break;
             case CornerWidget:
                 targetWidget = abstractScrollArea()->verticalScrollBar();
                 break;
             default:
                 break;
             }
             break;
         case Down:
             if (entry < 1)
                 break;
             switch (entryElement) {
             case Viewport:
                 targetWidget = abstractScrollArea()->horizontalScrollBar();
                 break;
             case VerticalContainer:
                 targetWidget = abstractScrollArea()->cornerWidget();
                 break;
             default:
                 break;
             }
             break;
         default:
             break;
         }
     } else {
         return QAccessibleWidgetEx::navigate(relation, entry, target);
     }
     if (qobject_cast<const QScrollBar *>(targetWidget))
         targetWidget = targetWidget->parentWidget();
     *target = QAccessible::queryAccessibleInterface(targetWidget);
     return *target ? 0: -1;
 }
rect()
QRect QAccessibleAbstractScrollArea::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 2141 of file complexwidgets.cpp.
Referenced by childAt(), and QAccessibleItemView::rect().
 {
     if (!abstractScrollArea()->isVisible())
         return QRect();
     if (child == Self)
         return QAccessibleWidgetEx::rect(child);
     QWidgetList children = accessibleChildren();
     if (child < 1 || child > children.count())
         return QRect();
     const QWidget *childWidget = children.at(child - 1);
     if (!childWidget->isVisible())
         return QRect();
     return QRect(childWidget->mapToGlobal(QPoint(0, 0)), childWidget->size());
 }
setText()
void QAccessibleAbstractScrollArea::setText (Text t, int child, const QString & text) virtual
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Note that the text properties of most objects are read-only.
See also
text()
Reimplemented from QAccessibleObjectEx.
Reimplemented in QAccessibleItemView.
Definition at line 1964 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::setText().
 {
     if (text.isEmpty())
         return;
     if (child == 0) {
         QAccessibleWidgetEx::setText(textType, 0, text);
         return;
     }
     QWidgetList children = accessibleChildren();
     if (child < 1 || child > children.count())
         return;
     QAccessibleInterface *childInterface = queryAccessibleInterface(children.at(child - 1));
     if (!childInterface)
         return;
     childInterface->setText(textType, 0, text);
     delete childInterface;
 }
state()
QAccessible::State QAccessibleAbstractScrollArea::state (int child) const virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 1982 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::state().
 {
     if (child == Self)
         return QAccessibleWidgetEx::state(child);
     QWidgetList children = accessibleChildren();
     if (child < 1 || child > children.count())
         return QAccessibleWidgetEx::state(Self);
     QAccessibleInterface *childInterface = queryAccessibleInterface(children.at(child - 1));
     if (!childInterface)
         return QAccessibleWidgetEx::state(Self);
     QAccessible::State returnState = childInterface->state(0);
     delete childInterface;
     return returnState;
 }
text()
QString QAccessibleAbstractScrollArea::text (Text t, int child) const virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Reimplemented from QAccessibleWidgetEx.
Reimplemented in QAccessibleItemView.
Definition at line 1949 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::text().
 {
     if (child == Self)
         return QAccessibleWidgetEx::text(textType, 0);
     QWidgetList children = accessibleChildren();
     if (child < 1 || child > children.count())
         return QString();
     QAccessibleInterface *childInterface = queryAccessibleInterface(children.at(child - 1));
     if (!childInterface)
         return QString();
     QString string = childInterface->text(textType, 0);
     delete childInterface;
     return string;
 }
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/complexwidgets.h
/src/plugins/accessible/widgets/complexwidgets.cpp