Qt 4.8: QContiguousCache< T > Class Template Reference
QContiguousCache< T > Class Template Reference
The QContiguousCache class is a template class that provides a contiguous cache.
#include <qcontiguouscache.h>
Public Types
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef qptrdiff difference_type
typedef value_type * pointer
typedef value_type & reference
typedef int size_type
typedef T value_type
Public Functions
void append (const T &value)
Inserts value at the end of the cache.
bool areIndexesValid () const
Returns whether the indexes for items stored in the cache are valid.
const T & at (int pos) const
Returns the item at index position i in the cache.
int available () const
Returns the number of items that can be added to the cache before it becomes full.
int capacity () const
Returns the number of items the cache can store before it is full.
void clear ()
Removes all items from the cache.
bool containsIndex (int pos) const
Returns true if the cache's index range includes the given index i.
int count () const
Same as size().
void detach ()
const T & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & first ()
Returns a reference to the first item in the cache.
int firstIndex () const
Returns the first valid index in the cache.
void insert (int pos, const T &value)
Inserts the value at the index position i.
bool isDetached () const
bool isEmpty () const
Returns true if no items are stored within the cache.
bool isFull () const
Returns true if the number of items stored within the cache is equal to the capacity of the cache.
const T & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
T & last ()
Returns a reference to the last item in the cache.
int lastIndex () const
Returns the last valid index in the cache.
void normalizeIndexes ()
Moves the first index and last index of the cache such that they point to valid indexes.
bool operator!= (const QContiguousCache< T > &other) const
Returns true if other is not equal to this cache; otherwise returns false.
QContiguousCache< T > & operator= (const QContiguousCache< T > &other)
Assigns other to this cache and returns a reference to this cache.
bool operator== (const QContiguousCache< T > &other) const
Returns true if other is equal to this cache; otherwise returns false.
T & operator[] (int i)
Returns the item at index position i as a modifiable reference.
const T & operator[] (int i) const
Same as at(i).
void prepend (const T &value)
Inserts value at the start of the cache.
QContiguousCache (int capacity=0)
Constructs a cache with the given capacity.
QContiguousCache (const QContiguousCache< T > &v)
Constructs a copy of other.
void removeFirst ()
Removes the first item from the cache.
void removeLast ()
Removes the last item from the cache.
void setCapacity (int size)
Sets the capacity of the cache to the given size.
void setSharable (bool sharable)
int size () const
Returns the number of items contained within the cache.
void swap (QContiguousCache< T > &other)
Swaps cache other with this cache.
T takeFirst ()
Removes the first item in the cache and returns it.
T takeLast ()
Removes the last item in the cache and returns it.
~QContiguousCache ()
Destroys the cache.
Private Types
typedef QContiguousCacheTypedData< T > Data
Private Functions
int alignOfTypedData () const
void detach_helper ()
void free (Data *x)
QContiguousCacheData * malloc (int aalloc)
int sizeOfTypedData ()
Properties
union {
QContiguousCacheData * d
QContiguousCacheTypedData< T > * p
};
Detailed Description
template<typename T>
class QContiguousCache< T >
The QContiguousCache class is a template class that provides a contiguous cache.
Note
This class or function is reentrant.
Since
4.6
The QContiguousCache class provides an efficient way of caching items for display in a user interface view. Unlike QCache, it adds a restriction that elements within the cache are contiguous. This has the advantage of matching how user interface views most commonly request data, as a set of rows localized around the current scrolled position. This restriction allows the cache to consume less memory and processor cycles than QCache. The QContiguousCache class also can provide an upper bound on memory usage via setCapacity().
The simplest way of using a contiguous cache is to use the append() and prepend().
MyRecord record(int row) const
{
    Q_ASSERT(row >= 0 && row < count());
    while(row > cache.lastIndex())
        cache.append(slowFetchRecord(cache.lastIndex()+1));
    while(row < cache.firstIndex())
        cache.prepend(slowFetchRecord(cache.firstIndex()-1));
    return cache.at(row);
}
If the cache is full then the item at the opposite end of the cache from
where the new item is appended or prepended will be removed.
This usage can be further optimized by using the insert() function
in the case where the requested row is a long way from the currently cached
items. If there is a gap between where the new item is inserted and the currently
cached items then the existing cached items are first removed to retain
the contiguous nature of the cache. Hence it is important to take some care then
when using insert() in order to avoid unwanted clearing of the cache.
The range of valid indexes for the QContiguousCache class are from
0 to INT_MAX.  Calling prepend() such that the first index would become less
than 0 or append() such that the last index would become greater
than INT_MAX can result in the indexes of the cache being invalid.
When the cache indexes are invalid it is important to call
normalizeIndexes() before calling any of containsIndex(), firstIndex(),
lastIndex(), at() or \ref QContiguousCache::operator[]() "operator[]()".
Calling these functions when the cache has invalid indexes will result in
undefined behavior. The indexes can be checked by using areIndexesValid()
In most cases the indexes will not exceed 0 to INT_MAX, and
normalizeIndexes() will not need to be used.
See the <b>Contiguous Cache Example</b>{Contiguous Cache} example.
Definition at line 90 of file qcontiguouscache.h.
Typedefs
const_pointer
template<typename T> QContiguousCache< T >::const_pointer
Warning
This function is not part of the public interface.
Definition at line 97 of file qcontiguouscache.h.
const_reference
template<typename T> QContiguousCache< T >::const_reference
Warning
This function is not part of the public interface.
Definition at line 99 of file qcontiguouscache.h.
Data
template<typename T> typedef QContiguousCacheTypedData<T> QContiguousCache< T >::Data private
Definition at line 91 of file qcontiguouscache.h.
difference_type
template<typename T> QContiguousCache< T >::difference_type
Warning
This function is not part of the public interface.
Definition at line 100 of file qcontiguouscache.h.
pointer
template<typename T> QContiguousCache< T >::pointer
Warning
This function is not part of the public interface.
Definition at line 96 of file qcontiguouscache.h.
reference
template<typename T> QContiguousCache< T >::reference
Warning
This function is not part of the public interface.
Definition at line 98 of file qcontiguouscache.h.
size_type
template<typename T> QContiguousCache< T >::size_type
Warning
This function is not part of the public interface.
Definition at line 101 of file qcontiguouscache.h.
value_type
template<typename T> QContiguousCache< T >::value_type
Warning
This function is not part of the public interface.
Definition at line 95 of file qcontiguouscache.h.
Constructors and Destructors
QContiguousCache() [1/2]
template<typename T > QContiguousCache< T >::QContiguousCache (int capacity = 0) explicit
Constructs a cache with the given capacity.
See also
setCapacity()
Definition at line 293 of file qcontiguouscache.h.
 {
     d = malloc(cap);
     d->ref = 1;
     d->alloc = cap;
     d->count = d->start = d->offset = 0;
     d->sharable = true;
 }
QContiguousCache() [2/2]
template<typename T> QContiguousCache< T >::QContiguousCache (const QContiguousCache< T > & other) inline
Constructs a copy of other.
This operation takes constant time, because QContiguousCache is implicitly shared. This makes returning a QContiguousCache from a function very fast. If a shared instance is modified, it will be copied (copy-on-write), and that takes linear time.
See also
operator=()
Definition at line 104 of file qcontiguouscache.h.
 : d(v.d) { d->ref.ref(); if (!d->sharable) detach_helper(); }
~QContiguousCache()
template<typename T> QContiguousCache< T >::~QContiguousCache () inline
Destroys the cache.
Definition at line 106 of file qcontiguouscache.h.
 { if (!d) return; if (!d->ref.deref()) free(p); }
Functions
alignOfTypedData()
template<typename T> int QContiguousCache< T >::alignOfTypedData () const inline private
Definition at line 172 of file qcontiguouscache.h.
     {
 #ifdef Q_ALIGNOF
         return qMax<int>(sizeof(void*), Q_ALIGNOF(Data));
 #else
         return 0;
 #endif
     }
append()
template<typename T > void QContiguousCache< T >::append (const T & value)
Inserts value at the end of the cache.
If the cache is already full the item at the start of the cache will be removed.
See also
prepend(), insert(), isFull()
Definition at line 347 of file qcontiguouscache.h.
 {
     if (!d->alloc)
         return;     // zero capacity
     detach();
     if (QTypeInfo<T>::isComplex) {
         if (d->count == d->alloc)
             (p->array + (d->start+d->count) % d->alloc)->~T();
         new (p->array + (d->start+d->count) % d->alloc) T(value);
     } else {
         p->array[(d->start+d->count) % d->alloc] = value;
     }
     if (d->count == d->alloc) {
         d->start++;
         d->start %= d->alloc;
         d->offset++;
     } else {
         d->count++;
     }
 }
areIndexesValid()
template<typename T> bool QContiguousCache< T >::areIndexesValid () const inline
Returns whether the indexes for items stored in the cache are valid.
Indexes can become invalid if items are appended after the index position INT_MAX or prepended before the index position 0. This is only expected to occur in very long lived circular buffer style usage of the contiguous cache. Indexes can be made valid again by calling normalizeIndexs().
See also
normalizeIndexes(), append(), prepend()
Definition at line 154 of file qcontiguouscache.h.
     { return d->offset >= 0 && d->offset < INT_MAX - d->count && (d->offset % d->alloc) == d->start; }
at()
template<typename T > const T & QContiguousCache< T >::at (int i) const inline
Returns the item at index position i in the cache.
i must be a valid index position in the cache (i.e, firstIndex() <= i <= lastIndex()).
The indexes in the cache refer to the number of positions the item is from the first item appended into the cache. That is to say a cache with a capacity of 100, that has had 150 items appended will have a valid index range of 50 to 149. This allows inserting and retrieving items into the cache based on a theoretical infinite list
See also
firstIndex(), lastIndex(), insert(), operator[]()
Definition at line 425 of file qcontiguouscache.h.
Referenced by QContiguousCache< T >::operator==().
 { Q_ASSERT_X(pos >= d->offset && pos - d->offset < d->count, "QContiguousCache<T>::at", "index out of range"); return p->array[pos % d->alloc]; }
available()
template<typename T> int QContiguousCache< T >::available () const inline
Returns the number of items that can be added to the cache before it becomes full.
See also
size(), capacity(), isFull()
Definition at line 127 of file qcontiguouscache.h.
 { return d->alloc - d->count; }
capacity()
template<typename T> int QContiguousCache< T >::capacity () const inline
Returns the number of items the cache can store before it is full.
When a cache contains a number of items equal to its capacity, adding new items will cause items farthest from the added item to be removed.
See also
setCapacity(), size()
Definition at line 121 of file qcontiguouscache.h.
 {return d->alloc; }
clear()
template<typename T > void QContiguousCache< T >::clear ()
Removes all items from the cache.
The capacity is unchanged.
Definition at line 259 of file qcontiguouscache.h.
 {
     if (d->ref == 1) {
         if (QTypeInfo<T>::isComplex) {
             int oldcount = d->count;
             T * i = p->array + d->start;
             T * e = p->array + d->alloc;
             while (oldcount--) {
                 i->~T();
                 i++;
                 if (i == e)
                     i = p->array;
             }
         }
         d->count = d->start = d->offset = 0;
     } else {
         union { QContiguousCacheData *d; QContiguousCacheTypedData<T> *p; } x;
         x.d = malloc(d->alloc);
         x.d->ref = 1;
         x.d->alloc = d->alloc;
         x.d->count = x.d->start = x.d->offset = 0;
         x.d->sharable = true;
         if (!d->ref.deref()) free(p);
         d = x.d;
     }
 }
containsIndex()
template<typename T> bool QContiguousCache< T >::containsIndex (int i) const inline
Returns true if the cache's index range includes the given index i.
See also
firstIndex(), lastIndex()
Definition at line 140 of file qcontiguouscache.h.
 { return pos >= d->offset && pos - d->offset < d->count; }
count()
template<typename T> int QContiguousCache< T >::count () const inline
Same as size().
Definition at line 122 of file qcontiguouscache.h.
 { return d->count; }
detach()
template<typename T> void QContiguousCache< T >::detach () inline
Warning
This function is not part of the public interface.
Definition at line 108 of file qcontiguouscache.h.
 { if (d->ref != 1) detach_helper(); }
detach_helper()
template<typename T > void QContiguousCache< T >::detach_helper () private
Definition at line 183 of file qcontiguouscache.h.
 {
     union { QContiguousCacheData *d; QContiguousCacheTypedData<T> *p; } x;
     x.d = malloc(d->alloc);
     x.d->ref = 1;
     x.d->count = d->count;
     x.d->start = d->start;
     x.d->offset = d->offset;
     x.d->alloc = d->alloc;
     x.d->sharable = true;
     x.d->reserved = 0;
     T *dest = x.p->array + x.d->start;
     T *src = p->array + d->start;
     int oldcount = x.d->count;
     while (oldcount--) {
         if (QTypeInfo<T>::isComplex) {
             new (dest) T(*src);
         } else {
             *dest = *src;
         }
         dest++;
         if (dest == x.p->array + x.d->alloc)
             dest = x.p->array;
         src++;
         if (src == p->array + d->alloc)
             src = p->array;
     }
     if (!d->ref.deref())
         free(p);
     d = x.d;
 }
first() [1/2]
template<typename T> const T & QContiguousCache< T >::first () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 144 of file qcontiguouscache.h.
 { Q_ASSERT(!isEmpty()); return p->array[d->start]; }
first() [2/2]
template<typename T> T & QContiguousCache< T >::first () inline
Returns a reference to the first item in the cache.
This function assumes that the cache isn't empty.
See also
last(), isEmpty()
Definition at line 146 of file qcontiguouscache.h.
 { Q_ASSERT(!isEmpty()); detach(); return p->array[d->start]; }
firstIndex()
template<typename T> int QContiguousCache< T >::firstIndex () const inline
Returns the first valid index in the cache.
The index will be invalid if the cache is empty.
See also
capacity(), size(), lastIndex()
Definition at line 141 of file qcontiguouscache.h.
Referenced by operator<<().
 { return d->offset; }
free()
template<typename T > void QContiguousCache< T >::free (Data * x) private
Definition at line 331 of file qcontiguouscache.h.
 {
     if (QTypeInfo<T>::isComplex) {
         int oldcount = d->count;
         T * i = p->array + d->start;
         T * e = p->array + d->alloc;
         while (oldcount--) {
             i->~T();
             i++;
             if (i == e)
                 i = p->array;
         }
     }
     x->free(x);
 }
insert()
template<typename T > void QContiguousCache< T >::insert (int i, const T & value)
Inserts the value at the index position i.
If the cache already contains an item at i then that value is replaced. If i is either one more than lastIndex() or one less than firstIndex() it is the equivalent to an append() or a prepend().
If the given index i is not within the current range of the cache nor adjacent to the bounds of the cache's index range, the cache is first cleared before inserting the item. At this point the cache will have a size of 1. It is worthwhile taking effort to insert items in an order that starts adjacent to the current index range for the cache.
The range of valid indexes for the QContiguousCache class are from 0 to INT_MAX. Inserting outside of this range has undefined behavior.
See also
prepend(), append(), isFull(), firstIndex(), lastIndex()
Definition at line 394 of file qcontiguouscache.h.
 {
     Q_ASSERT_X(pos >= 0 && pos < INT_MAX, "QContiguousCache<T>::insert", "index out of range");
     if (!d->alloc)
         return;     // zero capacity
     detach();
     if (containsIndex(pos)) {
         if (QTypeInfo<T>::isComplex) {
             (p->array + pos % d->alloc)->~T();
             new (p->array + pos % d->alloc) T(value);
         } else {
             p->array[pos % d->alloc] = value;
         }
     } else if (pos == d->offset-1)
         prepend(value);
     else if (pos == d->offset+d->count)
         append(value);
     else {
         // we don't leave gaps.
         clear();
         d->offset = pos;
         d->start = pos % d->alloc;
         d->count = 1;
         if (QTypeInfo<T>::isComplex)
             new (p->array + d->start) T(value);
         else
             p->array[d->start] = value;
     }
 }
isDetached()
template<typename T> bool QContiguousCache< T >::isDetached () const inline
Warning
This function is not part of the public interface.
Definition at line 109 of file qcontiguouscache.h.
 { return d->ref == 1; }
isEmpty()
template<typename T> bool QContiguousCache< T >::isEmpty () const inline
Returns true if no items are stored within the cache.
See also
size(), capacity()
Definition at line 125 of file qcontiguouscache.h.
 { return d->count == 0; }
isFull()
template<typename T> bool QContiguousCache< T >::isFull () const inline
Returns true if the number of items stored within the cache is equal to the capacity of the cache.
See also
size(), capacity()
Definition at line 126 of file qcontiguouscache.h.
 { return d->count == d->alloc; }
last() [1/2]
template<typename T> const T & QContiguousCache< T >::last () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 145 of file qcontiguouscache.h.
 { Q_ASSERT(!isEmpty()); return p->array[(d->start + d->count -1) % d->alloc]; }
last() [2/2]
template<typename T> T & QContiguousCache< T >::last () inline
Returns a reference to the last item in the cache.
This function assumes that the cache isn't empty.
See also
first(), isEmpty()
Definition at line 147 of file qcontiguouscache.h.
 { Q_ASSERT(!isEmpty()); detach(); return p->array[(d->start + d->count -1) % d->alloc]; }
lastIndex()
template<typename T> int QContiguousCache< T >::lastIndex () const inline
Returns the last valid index in the cache.
The index will be invalid if the cache is empty.
See also
capacity(), size(), firstIndex()
Definition at line 142 of file qcontiguouscache.h.
Referenced by operator<<().
 { return d->offset + d->count - 1; }
malloc()
template<typename T > QContiguousCacheData * QContiguousCache< T >::malloc (int aalloc) inline private
Definition at line 287 of file qcontiguouscache.h.
 {
     return QContiguousCacheData::allocate(sizeOfTypedData() + (aalloc - 1) * sizeof(T), alignOfTypedData());
 }
normalizeIndexes()
template<typename T> void QContiguousCache< T >::normalizeIndexes () inline
Moves the first index and last index of the cache such that they point to valid indexes.
The function does not modify the contents of the cache or the ordering of elements within the cache.
It is provided so that index overflows can be corrected when using the cache as a circular buffer.
QContiguousCache<int> cache(10);
cache.insert(INT_MAX, 1); // cache contains one value and has valid indexes, INT_MAX to INT_MAX
cache.append(2); // cache contains two values but does not have valid indexes.
cache.normalizeIndexes(); // cache has two values, 1 and 2.  New first index will be in the range of 0 to capacity().
See also
areIndexesValid(), append(), prepend()
Definition at line 157 of file qcontiguouscache.h.
 { d->offset = d->start; }
operator!=()
template<typename T> bool QContiguousCache< T >::operator!= (const QContiguousCache< T > & other) const inline
Returns true if other is not equal to this cache; otherwise returns false.
Two caches are considered equal if they contain the same values at the same indexes. This function requires the value type to implement the operator==().
See also
operator==()
Definition at line 119 of file qcontiguouscache.h.
 { return !(*this == other); }
operator=()
template<typename T > QContiguousCache< T > & QContiguousCache< T >::operator= (const QContiguousCache< T > & other)
Assigns other to this cache and returns a reference to this cache.
Definition at line 303 of file qcontiguouscache.h.
 {
     other.d->ref.ref();
     if (!d->ref.deref())
         free(d);
     d = other.d;
     if (!d->sharable)
         detach_helper();
     return *this;
 }
operator==()
template<typename T > bool QContiguousCache< T >::operator== (const QContiguousCache< T > & other) const
Returns true if other is equal to this cache; otherwise returns false.
Two caches are considered equal if they contain the same values at the same indexes. This function requires the value type to implement the operator==().
See also
operator!=()
Definition at line 315 of file qcontiguouscache.h.
 {
     if (other.d == d)
         return true;
     if (other.d->start != d->start
             || other.d->count != d->count
             || other.d->offset != d->offset
             || other.d->alloc != d->alloc)
         return false;
     for (int i = firstIndex(); i <= lastIndex(); ++i)
         if (!(at(i) == other.at(i)))
             return false;
     return true;
 }
operator[]() [1/2]
template<typename T > T & QContiguousCache< T >::operator[] (int i) inline
Returns the item at index position i as a modifiable reference.
If the cache does not contain an item at the given index position i then it will first insert an empty item at that position.
In most cases it is better to use either at() or insert().
Note
This non-const overload of operator[] requires QContiguousCache to make a deep copy. Use at() for read-only access to a non-const QContiguousCache.
See also
insert(), at()
Definition at line 432 of file qcontiguouscache.h.
 {
     detach();
     if (!containsIndex(pos))
         insert(pos, T());
     return p->array[pos % d->alloc];
 }
operator[]() [2/2]
template<typename T > const T & QContiguousCache< T >::operator[] (int i) const inline
Same as at(i).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 428 of file qcontiguouscache.h.
 { Q_ASSERT_X(pos >= d->offset && pos - d->offset < d->count, "QContiguousCache<T>::at", "index out of range"); return p->array[pos % d->alloc]; }
prepend()
template<typename T > void QContiguousCache< T >::prepend (const T & value)
Inserts value at the start of the cache.
If the cache is already full the item at the end of the cache will be removed.
See also
append(), insert(), isFull()
Definition at line 370 of file qcontiguouscache.h.
 {
     if (!d->alloc)
         return;     // zero capacity
     detach();
     if (d->start)
         d->start--;
     else
         d->start = d->alloc-1;
     d->offset--;
     if (d->count != d->alloc)
         d->count++;
     else
         if (d->count == d->alloc)
             (p->array + d->start)->~T();
     if (QTypeInfo<T>::isComplex)
         new (p->array + d->start) T(value);
     else
         p->array[d->start] = value;
 }
removeFirst()
template<typename T > void QContiguousCache< T >::removeFirst () inline
Removes the first item from the cache.
This function assumes that the cache isn't empty.
See also
removeLast()
Definition at line 441 of file qcontiguouscache.h.
 {
     Q_ASSERT(d->count > 0);
     detach();
     d->count--;
     if (QTypeInfo<T>::isComplex)
         (p->array + d->start)->~T();
     d->start = (d->start + 1) % d->alloc;
     d->offset++;
 }
removeLast()
template<typename T > void QContiguousCache< T >::removeLast () inline
Removes the last item from the cache.
This function assumes that the cache isn't empty.
See also
removeFirst()
Definition at line 453 of file qcontiguouscache.h.
 {
     Q_ASSERT(d->count > 0);
     detach();
     d->count--;
     if (QTypeInfo<T>::isComplex)
         (p->array + (d->start + d->count) % d->alloc)->~T();
 }
setCapacity()
template<typename T > void QContiguousCache< T >::setCapacity (int size)
Sets the capacity of the cache to the given size.
A cache can hold a number of items equal to its capacity. When inserting, appending or prepending items to the cache, if the cache is already full then the item farthest from the added item will be removed.
If the given size is smaller than the current count of items in the cache then only the last size items from the cache will remain.
See also
capacity(), isFull()
Definition at line 219 of file qcontiguouscache.h.
 {
     if (asize == d->alloc)
         return;
     detach();
     union { QContiguousCacheData *d; QContiguousCacheTypedData<T> *p; } x;
     x.d = malloc(asize);
     x.d->alloc = asize;
     x.d->count = qMin(d->count, asize);
     x.d->offset = d->offset + d->count - x.d->count;
     if(asize)
         x.d->start = x.d->offset % x.d->alloc;
     else
         x.d->start = 0;
     int oldcount = x.d->count;
     if(oldcount)
     {
         T *dest = x.p->array + (x.d->start + x.d->count-1) % x.d->alloc;
         T *src = p->array + (d->start + d->count-1) % d->alloc;
         while (oldcount--) {
             if (QTypeInfo<T>::isComplex) {
                 new (dest) T(*src);
             } else {
                 *dest = *src;
             }
             if (dest == x.p->array)
                 dest = x.p->array + x.d->alloc;
             dest--;
             if (src == p->array)
                 src = p->array + d->alloc;
             src--;
         }
     }
     /* free old */
     free(p);
     d = x.d;
 }
setSharable()
template<typename T> void QContiguousCache< T >::setSharable (bool sharable) inline
Warning
This function is not part of the public interface.
Definition at line 110 of file qcontiguouscache.h.
 { if (!sharable) detach(); d->sharable = sharable; }
size()
template<typename T> int QContiguousCache< T >::size () const inline
Returns the number of items contained within the cache.
See also
capacity()
Definition at line 123 of file qcontiguouscache.h.
 { return d->count; }
sizeOfTypedData()
template<typename T> int QContiguousCache< T >::sizeOfTypedData () inline private
Definition at line 167 of file qcontiguouscache.h.
{
         // this is more or less the same as sizeof(Data), except that it doesn't
         // count the padding at the end
         return reinterpret_cast<const char *>(&(reinterpret_cast<const Data *>(this))->array[1]) - reinterpret_cast<const char *>(this);
     }
swap()
template<typename T> void QContiguousCache< T >::swap (QContiguousCache< T > & other) inline
Swaps cache other with this cache.
Since
4.8
This operation is very fast and never fails.
Definition at line 117 of file qcontiguouscache.h.
 { qSwap(d, other.d); }
takeFirst()
template<typename T > T QContiguousCache< T >::takeFirst () inline
Removes the first item in the cache and returns it.
This function assumes that the cache isn't empty.
If you don't use the return value, removeFirst() is more efficient.
See also
takeLast(), removeFirst()
Definition at line 463 of file qcontiguouscache.h.
 { T t = first(); removeFirst(); return t; }
takeLast()
template<typename T > T QContiguousCache< T >::takeLast () inline
Removes the last item in the cache and returns it.
This function assumes that the cache isn't empty.
If you don't use the return value, removeLast() is more efficient.
See also
takeFirst(), removeLast()
Definition at line 467 of file qcontiguouscache.h.
 { T t = last(); removeLast(); return t; }
Properties
@49
union { ... }
d
template<typename T> QContiguousCacheData* QContiguousCache< T >::d
Definition at line 92 of file qcontiguouscache.h.
Referenced by QContiguousCache< T >::operator=(), QContiguousCache< T >::operator==(), QContiguousCache< T >::setSharable(), and QContiguousCache< T >::swap().
p
template<typename T> QContiguousCacheTypedData<T>* QContiguousCache< T >::p
Definition at line 92 of file qcontiguouscache.h.
The documentation for this class was generated from the following files:
/src/corelib/tools/qcontiguouscache.h
/src/corelib/tools/qcontiguouscache.cpp