Qt 4.8: QGraphicsWidgetPrivate Class Reference
QGraphicsWidgetPrivate Class Reference
#include <qgraphicswidget_p.h>
Classes
struct WindowData
Public Types
enum { Left, Top, Right, Bottom }
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Public Functions
void _q_relayout ()
void adjustWindowFlags (Qt::WindowFlags *wFlags)
int attributeToBitIndex (Qt::WidgetAttribute att) const
void ensureMargins () const
Ensures that margins is allocated.
void ensureWindowData ()
Ensures that windowData is allocated.
void ensureWindowFrameMargins () const
Ensures that windowFrameMargins is allocated.
void fixFocusChainBeforeReparenting (QGraphicsWidget *newParent, QGraphicsScene *oldScene, QGraphicsScene *newScene=0)
bool hasDecoration () const
qreal height () const
void init (QGraphicsItem *parentItem, Qt::WindowFlags wFlags)
void initStyleOptionTitleBar (QStyleOptionTitleBar *option)
QFont naturalWidgetFont () const
QPalette naturalWidgetPalette () const
QGraphicsWidgetPrivate ()
void resetHeight ()
void resetWidth ()
void resolveFont (uint inheritedMask)
void resolveLayoutDirection ()
void resolvePalette (uint inheritedMask)
void setAttribute (Qt::WidgetAttribute att, bool value)
void setFont_helper (const QFont &font)
void setGeometryFromSetPos ()
void setHeight (qreal)
void setLayout_helper (QGraphicsLayout *l)
void setLayoutDirection_helper (Qt::LayoutDirection direction)
void setPalette_helper (const QPalette &palette)
void setWidth (qreal)
bool testAttribute (Qt::WidgetAttribute att) const
qreal titleBarHeight (const QStyleOptionTitleBar &options) const
void updateFont (const QFont &font)
void updatePalette (const QPalette &palette)
qreal width () const
void windowFrameHoverLeaveEvent (QGraphicsSceneHoverEvent *event)
void windowFrameHoverMoveEvent (QGraphicsSceneHoverEvent *event)
void windowFrameMouseMoveEvent (QGraphicsSceneMouseEvent *event)
void windowFrameMousePressEvent (QGraphicsSceneMouseEvent *event)
void windowFrameMouseReleaseEvent (QGraphicsSceneMouseEvent *event)
virtual ~QGraphicsWidgetPrivate ()
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
virtual void transformChanged ()
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Public Variables
QList< QAction * > actions
quint32 attributes: 10
quint32 autoFillBackground: 1
QGraphicsWidget * focusNext
Qt::FocusPolicy focusPolicy
QGraphicsWidget * focusPrev
QFont font
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
quint32 inSetGeometry: 1
quint32 inSetPos: 1
QGraphicsLayout * layout
qreal * margins
quint32 padding: 2
QPalette palette
quint32 polished: 1
quint32 refCountInvokeRelayout: 16
bool setWindowFrameMargins
struct QGraphicsWidgetPrivate::WindowData * windowData
Qt::WindowFlags windowFlags
qreal * windowFrameMargins
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Additional Inherited Members
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Detailed Description
Definition at line 71 of file qgraphicswidget_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
Left
Top
Right
Bottom
Definition at line 99 of file qgraphicswidget_p.h.
 {Left, Top, Right, Bottom};
Constructors and Destructors
QGraphicsWidgetPrivate()
QGraphicsWidgetPrivate::QGraphicsWidgetPrivate () inline
Definition at line 75 of file qgraphicswidget_p.h.
         : margins(0),
           layout(0),
           inheritedPaletteResolveMask(0),
           inheritedFontResolveMask(0),
           inSetGeometry(0),
           polished(0),
           inSetPos(0),
           autoFillBackground(0),
           refCountInvokeRelayout(0),
           focusPolicy(Qt::NoFocus),
           focusNext(0),
           focusPrev(0),
           windowFlags(0),
           windowData(0),
           setWindowFrameMargins(false),
           windowFrameMargins(0)
     { }
~QGraphicsWidgetPrivate()
QGraphicsWidgetPrivate::~QGraphicsWidgetPrivate () virtual
Warning
This function is not part of the public interface.
Definition at line 104 of file qgraphicswidget_p.cpp.
Referenced by QGraphicsWidgetPrivate().
 {
     // Remove any lazily allocated data
     delete[] margins;
     delete[] windowFrameMargins;
     delete windowData;
 }
Functions
_q_relayout()
void QGraphicsWidgetPrivate::_q_relayout ()
Definition at line 246 of file qgraphicswidget_p.cpp.
 {
     --refCountInvokeRelayout;
     if (refCountInvokeRelayout == 0) {
         Q_Q(QGraphicsWidget);
         bool wasResized = q->testAttribute(Qt::WA_Resized);
         q->resize(q->size()); // this will restrict the size
         q->setAttribute(Qt::WA_Resized, wasResized);
     }
 }
adjustWindowFlags()
void QGraphicsWidgetPrivate::adjustWindowFlags (Qt::WindowFlags * wFlags)
Definition at line 355 of file qgraphicswidget_p.cpp.
Referenced by init().
 {
     bool customize =  (*flags & (Qt::CustomizeWindowHint
             | Qt::FramelessWindowHint
             | Qt::WindowTitleHint
             | Qt::WindowSystemMenuHint
             | Qt::WindowMinimizeButtonHint
             | Qt::WindowMaximizeButtonHint
             | Qt::WindowContextHelpButtonHint));
     uint type = (*flags & Qt::WindowType_Mask);
     if (customize)
         ;
     else if (type == Qt::Dialog || type == Qt::Sheet)
         *flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowContextHelpButtonHint;
     else if (type == Qt::Tool)
         *flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint;
     else if (type == Qt::Window || type == Qt::SubWindow)
         *flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint
                   | Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint;
 }
attributeToBitIndex()
int QGraphicsWidgetPrivate::attributeToBitIndex (Qt::WidgetAttribute att) const inline
Definition at line 147 of file qgraphicswidget_p.h.
Referenced by setAttribute(), and testAttribute().
     {
         int bit = -1;
         switch (att) {
         case Qt::WA_SetLayoutDirection: bit = 0; break;
         case Qt::WA_RightToLeft: bit = 1; break;
         case Qt::WA_SetStyle: bit = 2; break;
         case Qt::WA_Resized: bit = 3; break;
         case Qt::WA_DeleteOnClose: bit = 4; break;
         case Qt::WA_NoSystemBackground: bit = 5; break;
         case Qt::WA_OpaquePaintEvent: bit = 6; break;
         case Qt::WA_SetPalette: bit = 7; break;
         case Qt::WA_SetFont: bit = 8; break;
         case Qt::WA_WindowPropagation: bit = 9; break;
         default: break;
         }
         return bit;
     }
ensureMargins()
void QGraphicsWidgetPrivate::ensureMargins () const
Ensures that margins is allocated.
Warning
This function is not part of the public interface.
This function must be called before any dereferencing.
Definition at line 121 of file qgraphicswidget_p.cpp.
 {
     if (!margins) {
         margins = new qreal[4];
         for (int i = 0; i < 4; ++i)
             margins[i] = 0;
     }
 }
ensureWindowData()
void QGraphicsWidgetPrivate::ensureWindowData ()
Ensures that windowData is allocated.
Warning
This function is not part of the public interface.
This function must be called before any dereferencing.
Definition at line 157 of file qgraphicswidget_p.cpp.
Referenced by initStyleOptionTitleBar(), QGraphicsWidgetPrivate::WindowData::WindowData(), windowFrameHoverLeaveEvent(), windowFrameHoverMoveEvent(), windowFrameMouseMoveEvent(), windowFrameMousePressEvent(), and windowFrameMouseReleaseEvent().
 {
     if (!windowData)
         windowData = new WindowData;
 }
ensureWindowFrameMargins()
void QGraphicsWidgetPrivate::ensureWindowFrameMargins () const
Ensures that windowFrameMargins is allocated.
Warning
This function is not part of the public interface.
This function must be called before any dereferencing.
Definition at line 139 of file qgraphicswidget_p.cpp.
 {
     if (!windowFrameMargins) {
         windowFrameMargins = new qreal[4];
         for (int i = 0; i < 4; ++i)
             windowFrameMargins[i] = 0;
     }
 }
fixFocusChainBeforeReparenting()
void QGraphicsWidgetPrivate::fixFocusChainBeforeReparenting (QGraphicsWidget * newParent, QGraphicsScene * oldScene, QGraphicsScene * newScene = 0)
is called after a reparent has taken place to fix up the focus chain(s)
Definition at line 785 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     Q_ASSERT(focusNext && focusPrev);
     QGraphicsWidget *n = q;     //last one in 'new' list
     QGraphicsWidget *o = 0;     //last one in 'old' list
     QGraphicsWidget *w = focusNext;
     QGraphicsWidget *firstOld = 0;
     bool wasPreviousNew = true;
     while (w != q) {
         bool isCurrentNew = q->isAncestorOf(w);
         if (isCurrentNew) {
             if (!wasPreviousNew) {
                 n->d_func()->focusNext = w;
                 w->d_func()->focusPrev = n;
             }
             n = w;
         } else /*if (!isCurrentNew)*/ {
             if (wasPreviousNew) {
                 if (o) {
                     o->d_func()->focusNext = w;
                     w->d_func()->focusPrev = o;
                 } else {
                     firstOld = w;
                 }
             }
             o = w;
         }
         w = w->d_func()->focusNext;
         wasPreviousNew = isCurrentNew;
     }
     // repair the 'old' chain
     if (firstOld) {
         o->d_func()->focusNext = firstOld;
         firstOld->d_func()->focusPrev = o;
     }
     // update tabFocusFirst for oldScene if the item is going to be removed from oldScene
     if (newParent)
         newScene = newParent->scene();
     if (oldScene && newScene != oldScene)
         oldScene->d_func()->tabFocusFirst = (firstOld && firstOld->scene() == oldScene) ? firstOld : 0;
     QGraphicsItem *topLevelItem = newParent ? newParent->topLevelItem() : 0;
     QGraphicsWidget *topLevel = 0;
     if (topLevelItem && topLevelItem->isWidget())
         topLevel = static_cast<QGraphicsWidget *>(topLevelItem);
     if (topLevel && newParent) {
         QGraphicsWidget *last = topLevel->d_func()->focusPrev;
         // link last with new chain
         last->d_func()->focusNext = q;
         focusPrev = last;
         // link last in chain with
         topLevel->d_func()->focusPrev = n;
         n->d_func()->focusNext = topLevel;
     } else {
         // q is the start of the focus chain
         n->d_func()->focusNext = q;
         focusPrev = n;
     }
 }
hasDecoration()
bool QGraphicsWidgetPrivate::hasDecoration () const
Definition at line 777 of file qgraphicswidget_p.cpp.
Referenced by windowFrameHoverLeaveEvent(), and windowFrameHoverMoveEvent().
 {
     return (windowFlags & Qt::Window) && (windowFlags & Qt::WindowTitleHint);
 }
height()
qreal QGraphicsWidgetPrivate::height () const virtual
Warning
This function is not part of the public interface. Returns the height of the item Reimplemented by QGraphicsWidget
Reimplemented from QGraphicsItemPrivate.
Definition at line 890 of file qgraphicswidget_p.cpp.
Referenced by _q_boundGeometryToSizeConstraints(), resetWidth(), setWidth(), and titleBarHeight().
 {
     Q_Q(const QGraphicsWidget);
     return q->geometry().height();
 }
init()
void QGraphicsWidgetPrivate::init (QGraphicsItem * parentItem, Qt::WindowFlags wFlags)
Definition at line 63 of file qgraphicswidget_p.cpp.
Referenced by QGraphicsWidgetPrivate().
 {
     Q_Q(QGraphicsWidget);
     attributes = 0;
     isWidget = 1; // QGraphicsItem::isWidget() returns true.
     focusNext = focusPrev = q;
     focusPolicy = Qt::NoFocus;
     adjustWindowFlags(&wFlags);
     windowFlags = wFlags;
     if (parentItem)
         setParentItemHelper(parentItem, 0, 0);
     q->setSizePolicy(QSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred, QSizePolicy::DefaultType));
     q->setGraphicsItem(q);
     resolveLayoutDirection();
     q->unsetWindowFrameMargins();
     flags |= QGraphicsItem::ItemUsesExtendedStyleOption;
     flags |= QGraphicsItem::ItemSendsGeometryChanges;
     if (windowFlags & Qt::Window)
         flags |= QGraphicsItem::ItemIsPanel;
 }
initStyleOptionTitleBar()
void QGraphicsWidgetPrivate::initStyleOptionTitleBar (QStyleOptionTitleBar * option)
Definition at line 331 of file qgraphicswidget_p.cpp.
Referenced by windowFrameHoverMoveEvent(), and windowFrameMouseReleaseEvent().
 {
     Q_Q(QGraphicsWidget);
     ensureWindowData();
     q->initStyleOption(option);
     option->rect.setHeight(titleBarHeight(*option));
     option->titleBarFlags = windowFlags;
     option->subControls = QStyle::SC_TitleBarCloseButton | QStyle::SC_TitleBarLabel | QStyle::SC_TitleBarSysMenu;
     option->activeSubControls = windowData->hoveredSubControl;
     bool isActive = q->isActiveWindow();
     if (isActive) {
         option->state |= QStyle::State_Active;
         option->titleBarState = Qt::WindowActive;
         option->titleBarState |= QStyle::State_Active;
     } else {
         option->state &= ~QStyle::State_Active;
         option->titleBarState = Qt::WindowNoState;
     }
     QFont windowTitleFont = QApplication::font("QWorkspaceTitleBar");
     QRect textRect = q->style()->subControlRect(QStyle::CC_TitleBar, option, QStyle::SC_TitleBarLabel, 0);
     option->text = QFontMetrics(windowTitleFont).elidedText(
         windowData->windowTitle, Qt::ElideRight, textRect.width());
 }
naturalWidgetFont()
QFont QGraphicsWidgetPrivate::naturalWidgetFont () const
Definition at line 318 of file qgraphicswidget_p.cpp.
Referenced by resolveFont().
 {
     Q_Q(const QGraphicsWidget);
     QFont naturalFont; // ### no application font support
     if (QGraphicsWidget *parent = q->parentWidget()) {
         naturalFont = parent->font();
     } else if (scene) {
         naturalFont = scene->font();
     }
     naturalFont.resolve(0);
     return naturalFont;
 }
naturalWidgetPalette()
QPalette QGraphicsWidgetPrivate::naturalWidgetPalette () const
Definition at line 257 of file qgraphicswidget_p.cpp.
Referenced by resolvePalette().
 {
     Q_Q(const QGraphicsWidget);
     QPalette palette;
     if (QGraphicsWidget *parent = q->parentWidget()) {
         palette = parent->palette();
     } else if (scene) {
         palette = scene->palette();
     }
     palette.resolve(0);
     return palette;
 }
resetHeight()
void QGraphicsWidgetPrivate::resetHeight () virtual
Warning
This function is not part of the public interface. Reset the height of the item Reimplemented by QGraphicsWidget
Reimplemented from QGraphicsItemPrivate.
Definition at line 907 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     q->setGeometry(QRectF(q->x(), q->y(), width(), 0));
 }
resetWidth()
void QGraphicsWidgetPrivate::resetWidth () virtual
Warning
This function is not part of the public interface. Reset the width of the item Reimplemented by QGraphicsWidget
Reimplemented from QGraphicsItemPrivate.
Definition at line 884 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     q->setGeometry(QRectF(q->x(), q->y(), 0, height()));
 }
resolveFont()
void QGraphicsWidgetPrivate::resolveFont (uint inheritedMask) virtual
Reimplemented from QGraphicsItemPrivate.
Definition at line 277 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     inheritedFontResolveMask = inheritedMask;
     if (QGraphicsWidget *p = q->parentWidget())
         inheritedFontResolveMask |= p->d_func()->inheritedFontResolveMask;
     QFont naturalFont = naturalWidgetFont();
     QFont resolvedFont = font.resolve(naturalFont);
     updateFont(resolvedFont);
 }
resolveLayoutDirection()
void QGraphicsWidgetPrivate::resolveLayoutDirection ()
Definition at line 228 of file qgraphicswidget_p.cpp.
Referenced by init().
 {
     Q_Q(QGraphicsWidget);
     if (q->testAttribute(Qt::WA_SetLayoutDirection)) {
         return;
     }
     if (QGraphicsWidget *parentWidget = q->parentWidget()) {
         setLayoutDirection_helper(parentWidget->layoutDirection());
     } else if (scene) {
         // ### shouldn't the scene have a layoutdirection really? how does
         // ### QGraphicsWidget get changes from QApplication::layoutDirection?
         setLayoutDirection_helper(QApplication::layoutDirection());
     } else {
         setLayoutDirection_helper(QApplication::layoutDirection());
     }
 }
resolvePalette()
void QGraphicsWidgetPrivate::resolvePalette (uint inheritedMask) virtual
Reimplemented from QGraphicsItemPrivate.
Definition at line 170 of file qgraphicswidget_p.cpp.
 {
     inheritedPaletteResolveMask = inheritedMask;
     QPalette naturalPalette = naturalWidgetPalette();
     QPalette resolvedPalette = palette.resolve(naturalPalette);
     updatePalette(resolvedPalette);
 }
setAttribute()
void QGraphicsWidgetPrivate::setAttribute (Qt::WidgetAttribute att, bool value) inline
Definition at line 165 of file qgraphicswidget_p.h.
     {
         int bit = attributeToBitIndex(att);
         if (bit == -1) {
             qWarning("QGraphicsWidget::setAttribute: unsupported attribute %d", int(att));
             return;
         }
         if (value)
             attributes |= (1 << bit);
         else
             attributes &= ~(1 << bit);
     }
setFont_helper()
void QGraphicsWidgetPrivate::setFont_helper (const QFont & font)
Definition at line 270 of file qgraphicswidget_p.cpp.
 {
     if (this->font == font && this->font.resolve() == font.resolve())
         return;
     updateFont(font);
 }
setGeometryFromSetPos()
void QGraphicsWidgetPrivate::setGeometryFromSetPos ()
Definition at line 913 of file qgraphicswidget_p.cpp.
 {
     if (inSetGeometry)
         return;
     Q_Q(QGraphicsWidget);
     inSetPos = 1;
     // Ensure setGeometry is called (avoid recursion when setPos is
     // called from within setGeometry).
     q->setGeometry(QRectF(pos, q->size()));
     inSetPos = 0 ;
 }
setHeight()
void QGraphicsWidgetPrivate::setHeight (qreal h) virtual
Warning
This function is not part of the public interface. Set the height of the item Reimplemented by QGraphicsWidget
Reimplemented from QGraphicsItemPrivate.
Definition at line 896 of file qgraphicswidget_p.cpp.
 {
     if (qIsNaN(h))
         return;
     Q_Q(QGraphicsWidget);
     if (q->geometry().height() == h)
         return;
     q->setGeometry(QRectF(q->x(), q->y(), width(), h));
 }
setLayout_helper()
void QGraphicsWidgetPrivate::setLayout_helper (QGraphicsLayout * l)
Definition at line 857 of file qgraphicswidget_p.cpp.
 {
     delete (this->layout);
     layout = l;
     if (!l) {
         Q_Q(QGraphicsWidget);
         q->updateGeometry();
     }
 }
setLayoutDirection_helper()
void QGraphicsWidgetPrivate::setLayoutDirection_helper (Qt::LayoutDirection direction)
Definition at line 206 of file qgraphicswidget_p.cpp.
Referenced by resolveLayoutDirection().
 {
     Q_Q(QGraphicsWidget);
     if ((direction == Qt::RightToLeft) == (testAttribute(Qt::WA_RightToLeft)))
         return;
     q->setAttribute(Qt::WA_RightToLeft, (direction == Qt::RightToLeft));
     // Propagate this change to all children.
     for (int i = 0; i < children.size(); ++i) {
         QGraphicsItem *item = children.at(i);
         if (item->isWidget()) {
             QGraphicsWidget *widget = static_cast<QGraphicsWidget *>(item);
             if (widget->parentWidget() && !widget->testAttribute(Qt::WA_SetLayoutDirection))
                 widget->d_func()->setLayoutDirection_helper(direction);
         }
     }
     // Send the notification event to this widget item.
     QEvent e(QEvent::LayoutDirectionChange);
     QApplication::sendEvent(q, &e);
 }
setPalette_helper()
void QGraphicsWidgetPrivate::setPalette_helper (const QPalette & palette)
Definition at line 163 of file qgraphicswidget_p.cpp.
 {
     if (this->palette == palette && this->palette.resolve() == palette.resolve())
         return;
     updatePalette(palette);
 }
setWidth()
void QGraphicsWidgetPrivate::setWidth (qreal w) virtual
Warning
This function is not part of the public interface. Set the width of the item Reimplemented by QGraphicsWidget
Reimplemented from QGraphicsItemPrivate.
Definition at line 873 of file qgraphicswidget_p.cpp.
 {
     if (qIsNaN(w))
         return;
     Q_Q(QGraphicsWidget);
     if (q->geometry().width() == w)
         return;
     q->setGeometry(QRectF(q->x(), q->y(), w, height()));
 }
testAttribute()
bool QGraphicsWidgetPrivate::testAttribute (Qt::WidgetAttribute att) const inline
Definition at line 177 of file qgraphicswidget_p.h.
Referenced by setLayoutDirection_helper().
     {
         int bit = attributeToBitIndex(att);
         if (bit == -1)
             return false;
         return (attributes & (1 << bit)) != 0;
     }
titleBarHeight()
qreal QGraphicsWidgetPrivate::titleBarHeight (const QStyleOptionTitleBar & options) const
Definition at line 89 of file qgraphicswidget_p.cpp.
Referenced by initStyleOptionTitleBar(), QGraphicsWidgetPrivate(), and windowFrameHoverMoveEvent().
 {
     Q_Q(const QGraphicsWidget);
     int height = q->style()->pixelMetric(QStyle::PM_TitleBarHeight, &options);
 #if defined(Q_WS_MAC) && !defined(QT_NO_STYLE_MAC)
     if (qobject_cast<QMacStyle*>(q->style())) {
         height -=4;
     }
 #endif
     return (qreal)height;
 }
updateFont()
void QGraphicsWidgetPrivate::updateFont (const QFont & font)
Definition at line 288 of file qgraphicswidget_p.cpp.
Referenced by resolveFont(), and setFont_helper().
 {
     Q_Q(QGraphicsWidget);
     // Update the local font setting.
     this->font = font;
     // Calculate new mask.
     if (q->isWindow() && !q->testAttribute(Qt::WA_WindowPropagation))
         inheritedFontResolveMask = 0;
     int mask = font.resolve() | inheritedFontResolveMask;
     // Propagate to children.
     for (int i = 0; i < children.size(); ++i) {
         QGraphicsItem *item = children.at(i);
         if (item->isWidget()) {
             QGraphicsWidget *w = static_cast<QGraphicsWidget *>(item);
             if (!w->isWindow() || w->testAttribute(Qt::WA_WindowPropagation))
                 w->d_func()->resolveFont(mask);
         } else {
             item->d_ptr->resolveFont(mask);
         }
     }
     if (!polished)
         return;
     // Notify change.
     QEvent event(QEvent::FontChange);
     QApplication::sendEvent(q, &event);
 }
updatePalette()
void QGraphicsWidgetPrivate::updatePalette (const QPalette & palette)
Definition at line 178 of file qgraphicswidget_p.cpp.
Referenced by resolvePalette(), and setPalette_helper().
 {
     Q_Q(QGraphicsWidget);
     // Update local palette setting.
     this->palette = palette;
     // Calculate new mask.
     if (q->isWindow() && !q->testAttribute(Qt::WA_WindowPropagation))
         inheritedPaletteResolveMask = 0;
     int mask = palette.resolve() | inheritedPaletteResolveMask;
     // Propagate to children.
     for (int i = 0; i < children.size(); ++i) {
         QGraphicsItem *item = children.at(i);
         if (item->isWidget()) {
             QGraphicsWidget *w = static_cast<QGraphicsWidget *>(item);
             if (!w->isWindow() || w->testAttribute(Qt::WA_WindowPropagation))
                 w->d_func()->resolvePalette(mask);
         } else {
             item->d_ptr->resolvePalette(mask);
         }
     }
     // Notify change.
     QEvent event(QEvent::PaletteChange);
     QApplication::sendEvent(q, &event);
 }
width()
qreal QGraphicsWidgetPrivate::width () const virtual
Warning
This function is not part of the public interface. Returns the width of the item Reimplemented by QGraphicsWidget
Reimplemented from QGraphicsItemPrivate.
Definition at line 867 of file qgraphicswidget_p.cpp.
Referenced by _q_boundGeometryToSizeConstraints(), minimumHeightForWidth(), resetHeight(), and setHeight().
 {
     Q_Q(const QGraphicsWidget);
     return q->geometry().width();
 }
windowFrameHoverLeaveEvent()
void QGraphicsWidgetPrivate::windowFrameHoverLeaveEvent (QGraphicsSceneHoverEvent * event)
Definition at line 751 of file qgraphicswidget_p.cpp.
Referenced by windowFrameHoverMoveEvent().
 {
     Q_UNUSED(event);
     Q_Q(QGraphicsWidget);
     if (hasDecoration()) {
         // ### restore the cursor, don't override it
 #ifndef QT_NO_CURSOR
         q->unsetCursor();
 #endif
         ensureWindowData();
         bool needsUpdate = false;
         if (windowData->hoveredSubControl == QStyle::SC_TitleBarCloseButton
             || windowData->buttonMouseOver)
             needsUpdate = true;
         // update the hover state (of buttons etc...)
         windowData->hoveredSubControl = QStyle::SC_None;
         windowData->buttonMouseOver = false;
         windowData->buttonRect = QRect();
         if (needsUpdate)
             q->update(windowData->buttonRect);
     }
 }
windowFrameHoverMoveEvent()
void QGraphicsWidgetPrivate::windowFrameHoverMoveEvent (QGraphicsSceneHoverEvent * event)
Definition at line 667 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     if (!hasDecoration())
         return;
     ensureWindowData();
     if (q->rect().contains(event->pos())) {
         if (windowData->buttonMouseOver || windowData->hoveredSubControl != QStyle::SC_None)
             windowFrameHoverLeaveEvent(event);
         return;
     }
     bool wasMouseOver = windowData->buttonMouseOver;
     QRect oldButtonRect = windowData->buttonRect;
     windowData->buttonRect = QRect();
     windowData->buttonMouseOver = false;
     QPointF pos = event->pos();
     QStyleOptionTitleBar bar;
     // make sure that the coordinates (rect and pos) we send to the style are positive.
     if (windowFrameMargins) {
         pos.rx() += windowFrameMargins[Left];
         pos.ry() += windowFrameMargins[Top];
     }
     initStyleOptionTitleBar(&bar);
     bar.rect = q->windowFrameRect().toRect();
     bar.rect.moveTo(0,0);
     bar.rect.setHeight(int(titleBarHeight(bar)));
     Qt::CursorShape cursorShape = Qt::ArrowCursor;
     bool needsSetCursorCall = true;
     switch (q->windowFrameSectionAt(event->pos())) {
         case Qt::TopLeftSection:
         case Qt::BottomRightSection:
             cursorShape = Qt::SizeFDiagCursor;
             break;
         case Qt::TopRightSection:
         case Qt::BottomLeftSection:
             cursorShape = Qt::SizeBDiagCursor;
             break;
         case Qt::LeftSection:
         case Qt::RightSection:
             cursorShape = Qt::SizeHorCursor;
             break;
         case Qt::TopSection:
         case Qt::BottomSection:
             cursorShape = Qt::SizeVerCursor;
             break;
         case Qt::TitleBarArea:
             windowData->buttonRect = q->style()->subControlRect(
                 QStyle::CC_TitleBar, &bar, QStyle::SC_TitleBarCloseButton, 0);
 #ifdef Q_WS_MAC
             // On mac we should hover if we are in the 'area' of the buttons
             windowData->buttonRect |= q->style()->subControlRect(
                 QStyle::CC_TitleBar, &bar, QStyle::SC_TitleBarMinButton, 0);
             windowData->buttonRect |= q->style()->subControlRect(
                 QStyle::CC_TitleBar, &bar, QStyle::SC_TitleBarMaxButton, 0);
 #endif
             if (windowData->buttonRect.contains(pos.toPoint()))
                 windowData->buttonMouseOver = true;
             event->ignore();
             break;
         default:
             needsSetCursorCall = false;
             event->ignore();
         }
 #ifndef QT_NO_CURSOR
     if (needsSetCursorCall)
         q->setCursor(cursorShape);
 #endif
     // update buttons if we hover over them
     windowData->hoveredSubControl = q->style()->hitTestComplexControl(QStyle::CC_TitleBar, &bar, pos.toPoint(), 0);
     if (windowData->hoveredSubControl != QStyle::SC_TitleBarCloseButton)
         windowData->hoveredSubControl = QStyle::SC_TitleBarLabel;
     if (windowData->buttonMouseOver != wasMouseOver) {
         if (!oldButtonRect.isNull())
             q->update(QRectF(oldButtonRect).translated(q->windowFrameRect().topLeft()));
         if (!windowData->buttonRect.isNull())
             q->update(QRectF(windowData->buttonRect).translated(q->windowFrameRect().topLeft()));
     }
 }
windowFrameMouseMoveEvent()
void QGraphicsWidgetPrivate::windowFrameMouseMoveEvent (QGraphicsSceneMouseEvent * event)
Definition at line 597 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     ensureWindowData();
     if (!(event->buttons() & Qt::LeftButton) || windowData->hoveredSubControl != QStyle::SC_TitleBarLabel)
         return;
     QLineF delta(q->mapFromScene(event->buttonDownScenePos(Qt::LeftButton)), event->pos());
     QLineF parentDelta(q->mapToParent(delta.p1()), q->mapToParent(delta.p2()));
     QLineF parentXDelta(q->mapToParent(QPointF(delta.p1().x(), 0)), q->mapToParent(QPointF(delta.p2().x(), 0)));
     QLineF parentYDelta(q->mapToParent(QPointF(0, delta.p1().y())), q->mapToParent(QPointF(0, delta.p2().y())));
     QRectF newGeometry;
     switch (windowData->grabbedSection) {
     case Qt::LeftSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft()
                              + QPointF(parentXDelta.dx(), parentXDelta.dy()),
                              windowData->startGeometry.size() - QSizeF(delta.dx(), delta.dy()));
         break;
     case Qt::TopLeftSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft()
                              + QPointF(parentDelta.dx(), parentDelta.dy()),
                              windowData->startGeometry.size() - QSizeF(delta.dx(), delta.dy()));
         break;
     case Qt::TopSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft()
                              + QPointF(parentYDelta.dx(), parentYDelta.dy()),
                              windowData->startGeometry.size() - QSizeF(0, delta.dy()));
         break;
     case Qt::TopRightSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft()
                              + QPointF(parentYDelta.dx(), parentYDelta.dy()),
                              windowData->startGeometry.size() - QSizeF(-delta.dx(), delta.dy()));
         break;
     case Qt::RightSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft(),
                              windowData->startGeometry.size() + QSizeF(delta.dx(), 0));
         break;
     case Qt::BottomRightSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft(),
                              windowData->startGeometry.size() + QSizeF(delta.dx(), delta.dy()));
         break;
     case Qt::BottomSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft(),
                              windowData->startGeometry.size() + QSizeF(0, delta.dy()));
         break;
     case Qt::BottomLeftSection:
         newGeometry = QRectF(windowData->startGeometry.topLeft()
                              + QPointF(parentXDelta.dx(), parentXDelta.dy()),
                              windowData->startGeometry.size() - QSizeF(delta.dx(), -delta.dy()));
         break;
     case Qt::TitleBarArea:
         newGeometry = QRectF(windowData->startGeometry.topLeft()
                              + QPointF(parentDelta.dx(), parentDelta.dy()),
                              windowData->startGeometry.size());
         break;
     case Qt::NoSection:
         break;
     }
     if (windowData->grabbedSection != Qt::NoSection) {
         _q_boundGeometryToSizeConstraints(windowData->startGeometry, &newGeometry,
                                           windowData->grabbedSection,
                                           q->effectiveSizeHint(Qt::MinimumSize),
                                           q->effectiveSizeHint(Qt::MaximumSize),
                                           q);
         q->setGeometry(newGeometry);
     }
 }
windowFrameMousePressEvent()
void QGraphicsWidgetPrivate::windowFrameMousePressEvent (QGraphicsSceneMouseEvent * event)
Definition at line 408 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     if (event->button() != Qt::LeftButton)
         return;
     ensureWindowData();
     windowData->startGeometry = q->geometry();
     windowData->grabbedSection = q->windowFrameSectionAt(event->pos());
     ensureWindowData();
     if (windowData->grabbedSection == Qt::TitleBarArea
         && windowData->hoveredSubControl == QStyle::SC_TitleBarCloseButton) {
         windowData->buttonSunken = true;
         q->update();
     }
     event->setAccepted(windowData->grabbedSection != Qt::NoSection);
 }
windowFrameMouseReleaseEvent()
void QGraphicsWidgetPrivate::windowFrameMouseReleaseEvent (QGraphicsSceneMouseEvent * event)
Definition at line 377 of file qgraphicswidget_p.cpp.
 {
     Q_Q(QGraphicsWidget);
     ensureWindowData();
     if (windowData->grabbedSection != Qt::NoSection) {
         if (windowData->grabbedSection == Qt::TitleBarArea) {
             windowData->buttonSunken = false;
             QStyleOptionTitleBar bar;
             initStyleOptionTitleBar(&bar);
             // make sure that the coordinates (rect and pos) we send to the style are positive.
             bar.rect = q->windowFrameRect().toRect();
             bar.rect.moveTo(0,0);
             bar.rect.setHeight(q->style()->pixelMetric(QStyle::PM_TitleBarHeight, &bar));
             QPointF pos = event->pos();
             if (windowFrameMargins) {
                 pos.rx() += windowFrameMargins[Left];
                 pos.ry() += windowFrameMargins[Top];
             }
             bar.subControls = QStyle::SC_TitleBarCloseButton;
             if (q->style()->subControlRect(QStyle::CC_TitleBar, &bar,
                                            QStyle::SC_TitleBarCloseButton,
                                            event->widget()).contains(pos.toPoint())) {
                 q->close();
             }
         }
         if (!(static_cast<QGraphicsSceneMouseEvent *>(event)->buttons()))
             windowData->grabbedSection = Qt::NoSection;
         event->accept();
     }
 }
Properties
actions
QList<QAction *> QGraphicsWidgetPrivate::actions
Definition at line 222 of file qgraphicswidget_p.h.
attributes
quint32 QGraphicsWidgetPrivate::attributes
Definition at line 185 of file qgraphicswidget_p.h.
Referenced by init(), setAttribute(), and testAttribute().
autoFillBackground
quint32 QGraphicsWidgetPrivate::autoFillBackground
Definition at line 189 of file qgraphicswidget_p.h.
focusNext
QGraphicsWidget* QGraphicsWidgetPrivate::focusNext
Definition at line 195 of file qgraphicswidget_p.h.
Referenced by fixFocusChainBeforeReparenting(), and init().
focusPolicy
Qt::FocusPolicy QGraphicsWidgetPrivate::focusPolicy
Definition at line 194 of file qgraphicswidget_p.h.
Referenced by init().
focusPrev
QGraphicsWidget* QGraphicsWidgetPrivate::focusPrev
Definition at line 196 of file qgraphicswidget_p.h.
Referenced by fixFocusChainBeforeReparenting(), and init().
font
QFont QGraphicsWidgetPrivate::font
Definition at line 119 of file qgraphicswidget_p.h.
Referenced by resolveFont(), and updateFont().
inheritedFontResolveMask
uint QGraphicsWidgetPrivate::inheritedFontResolveMask
Definition at line 120 of file qgraphicswidget_p.h.
Referenced by resolveFont(), and updateFont().
inheritedPaletteResolveMask
uint QGraphicsWidgetPrivate::inheritedPaletteResolveMask
Definition at line 114 of file qgraphicswidget_p.h.
Referenced by resolvePalette(), and updatePalette().
inSetGeometry
quint32 QGraphicsWidgetPrivate::inSetGeometry
Definition at line 186 of file qgraphicswidget_p.h.
Referenced by QGraphicsWidget::setGeometry(), and setGeometryFromSetPos().
inSetPos
quint32 QGraphicsWidgetPrivate::inSetPos
Definition at line 188 of file qgraphicswidget_p.h.
Referenced by QGraphicsWidget::setGeometry(), and setGeometryFromSetPos().
layout
QGraphicsLayout* QGraphicsWidgetPrivate::layout
Definition at line 107 of file qgraphicswidget_p.h.
Referenced by QGraphicsWidget::setGeometry(), and setLayout_helper().
margins
qreal* QGraphicsWidgetPrivate::margins mutable
Definition at line 100 of file qgraphicswidget_p.h.
Referenced by ensureMargins(), and ~QGraphicsWidgetPrivate().
padding
quint32 QGraphicsWidgetPrivate::padding
Definition at line 191 of file qgraphicswidget_p.h.
palette
QPalette QGraphicsWidgetPrivate::palette
Definition at line 113 of file qgraphicswidget_p.h.
Referenced by naturalWidgetPalette(), resolvePalette(), and updatePalette().
polished
quint32 QGraphicsWidgetPrivate::polished
Definition at line 187 of file qgraphicswidget_p.h.
Referenced by updateFont().
refCountInvokeRelayout
quint32 QGraphicsWidgetPrivate::refCountInvokeRelayout
Definition at line 190 of file qgraphicswidget_p.h.
Referenced by _q_relayout().
setWindowFrameMargins
bool QGraphicsWidgetPrivate::setWindowFrameMargins
Definition at line 217 of file qgraphicswidget_p.h.
windowData
struct QGraphicsWidgetPrivate::WindowData * QGraphicsWidgetPrivate::windowData
Referenced by ensureWindowData(), initStyleOptionTitleBar(), QGraphicsWidgetPrivate::WindowData::WindowData(), windowFrameHoverLeaveEvent(), windowFrameHoverMoveEvent(), windowFrameMouseMoveEvent(), windowFrameMousePressEvent(), windowFrameMouseReleaseEvent(), and ~QGraphicsWidgetPrivate().
windowFlags
Qt::WindowFlags QGraphicsWidgetPrivate::windowFlags
Definition at line 199 of file qgraphicswidget_p.h.
Referenced by hasDecoration(), init(), and initStyleOptionTitleBar().
windowFrameMargins
qreal* QGraphicsWidgetPrivate::windowFrameMargins mutable
Definition at line 218 of file qgraphicswidget_p.h.
Referenced by ensureWindowFrameMargins(), windowFrameHoverMoveEvent(), windowFrameMouseReleaseEvent(), and ~QGraphicsWidgetPrivate().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicswidget_p.h
/src/gui/graphicsview/qgraphicswidget_p.cpp