Qt 4.8: QRasterPixmapData Class Reference
QRasterPixmapData Class Reference
#include <qpixmap_raster_p.h>
Public Functions
QImage * buffer ()
void copy (const QPixmapData *data, const QRect &rect)
QPixmapData * createCompatiblePixmapData () const
void fill (const QColor &color)
bool fromData (const uchar *buffer, uint len, const char *format, Qt::ImageConversionFlags flags)
void fromFile (const QString &filename, Qt::ImageConversionFlags flags)
void fromImage (const QImage &image, Qt::ImageConversionFlags flags)
void fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags)
bool hasAlphaChannel () const
QPaintEngine * paintEngine () const
QRasterPixmapData (PixelType type)
void resize (int width, int height)
bool scroll (int dx, int dy, const QRect &rect)
void setAlphaChannel (const QPixmap &alphaChannel)
void setMask (const QBitmap &mask)
QImage toImage () const
QImage toImage (const QRect &rect) const
~QRasterPixmapData ()
Public Functions inherited from QPixmapData
virtual QPixmap alphaChannel () const
qint64 cacheKey () const
ClassId classId () const
int colorCount () const
int depth () const
virtual bool fromFile (const QString &filename, const char *format, Qt::ImageConversionFlags flags)
int height () const
bool isNull () const
virtual QBitmap mask () const
QT_DEPRECATED int numColors () const
PixelType pixelType () const
QPixmapData (PixelType pixelType, int classId)
virtual QPixmapData * runtimeData () const
int serialNumber () const
virtual QPixmap transformed (const QTransform &matrix, Qt::TransformationMode mode) const
int width () const
virtual ~QPixmapData ()
Protected Functions
void createPixmapForImage (QImage &sourceImage, Qt::ImageConversionFlags flags, bool inPlace)
int metric (QPaintDevice::PaintDeviceMetric metric) const
void setImage (const QImage &image)
Protected Functions inherited from QPixmapData
void setSerialNumber (int serNo)
Protected Variables
QImage image
Protected Variables inherited from QPixmapData
int d
int h
bool is_null
int w
Friends
class QBitmap
class QPixmap
class QPixmapCacheEntry
class QRasterPaintEngine
Additional Inherited Members
Public Types inherited from QPixmapData
enum ClassId {
RasterClass, X11Class, MacClass, DirectFBClass,
OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
CustomClass = 1024
}
enum PixelType { PixmapType, BitmapType }
Static Public Functions inherited from QPixmapData
static QPixmapData * create (int w, int h, PixelType type)
Detailed Description
Definition at line 65 of file qpixmap_raster_p.h.
Constructors and Destructors
QRasterPixmapData()
QRasterPixmapData::QRasterPixmapData (PixelType type)
Definition at line 88 of file qpixmap_raster.cpp.
Referenced by createCompatiblePixmapData().
     : QPixmapData(type, RasterClass)
 {
 }
~QRasterPixmapData()
QRasterPixmapData::~QRasterPixmapData ()
Definition at line 93 of file qpixmap_raster.cpp.
 {
 }
Functions
buffer()
QImage * QRasterPixmapData::buffer () virtual
Reimplemented from QPixmapData.
Definition at line 488 of file qpixmap_raster.cpp.
Referenced by QMeeGoGraphicsSystem::createPixmapData(), and QMeeGoGraphicsSystem::pixmapDataFromEGLSharedImage().
 {
     return &image;
 }
copy()
void QRasterPixmapData::copy (const QPixmapData * data, const QRect & rect) virtual
Reimplemented from QPixmapData.
Reimplemented in QMeeGoRasterPixmapData.
Definition at line 173 of file qpixmap_raster.cpp.
Referenced by QMeeGoRasterPixmapData::copy().
 {
     fromImage(data->toImage(rect).copy(), Qt::NoOpaqueDetection);
 }
createCompatiblePixmapData()
QPixmapData * QRasterPixmapData::createCompatiblePixmapData () const virtual
Reimplemented from QPixmapData.
Definition at line 97 of file qpixmap_raster.cpp.
 {
     return new QRasterPixmapData(pixelType());
 }
createPixmapForImage()
void QRasterPixmapData::createPixmapForImage (QImage & sourceImage, Qt::ImageConversionFlags flags, bool inPlace) protected
Definition at line 386 of file qpixmap_raster.cpp.
Referenced by fromData(), fromImage(), and fromImageReader().
 {
     QImage::Format format;
     if (flags & Qt::NoFormatConversion)
         format = sourceImage.format();
     else
 #ifdef Q_WS_QWS
     if (pixelType() == BitmapType) {
         format = QImage::Format_Mono;
     } else {
         format = QScreen::instance()->pixelFormat();
         if (format == QImage::Format_Invalid)
             format = QImage::Format_ARGB32_Premultiplied;
         else if (format == QImage::Format_Indexed8) // currently not supported
             format = QImage::Format_RGB444;
     }
     if (sourceImage.hasAlphaChannel()
         && ((flags & Qt::NoOpaqueDetection)
             || const_cast<QImage &>(sourceImage).data_ptr()->checkForAlphaPixels())) {
         switch (format) {
             case QImage::Format_RGB16:
                 format = QImage::Format_ARGB8565_Premultiplied;
                 break;
             case QImage::Format_RGB666:
                 format = QImage::Format_ARGB6666_Premultiplied;
                 break;
             case QImage::Format_RGB555:
                 format = QImage::Format_ARGB8555_Premultiplied;
                 break;
             case QImage::Format_RGB444:
                 format = QImage::Format_ARGB4444_Premultiplied;
                 break;
             default:
                 format = QImage::Format_ARGB32_Premultiplied;
                 break;
         }
     } else if (format == QImage::Format_Invalid) {
         format = QImage::Format_ARGB32_Premultiplied;
     }
 #else
     if (pixelType() == BitmapType) {
         format = QImage::Format_MonoLSB;
     } else {
         if (sourceImage.depth() == 1) {
             format = sourceImage.hasAlphaChannel()
                     ? QImage::Format_ARGB32_Premultiplied
                     : QImage::Format_RGB32;
         } else {
             QImage::Format opaqueFormat = QNativeImage::systemFormat();
             QImage::Format alphaFormat = QImage::Format_ARGB32_Premultiplied;
 #if !defined(QT_HAVE_NEON) && !defined(QT_ALWAYS_HAVE_SSE2)
             switch (opaqueFormat) {
             case QImage::Format_RGB16:
                 alphaFormat = QImage::Format_ARGB8565_Premultiplied;
                 break;
             default: // We don't care about the others...
                 break;
             }
 #endif
             if (!sourceImage.hasAlphaChannel()) {
                 format = opaqueFormat;
             } else if ((flags & Qt::NoOpaqueDetection) == 0
                        && !const_cast<QImage &>(sourceImage).data_ptr()->checkForAlphaPixels())
             {
                 // image has alpha format but is really opaque, so try to do a
                 // more efficient conversion
                 if (sourceImage.format() == QImage::Format_ARGB32
                     || sourceImage.format() == QImage::Format_ARGB32_Premultiplied)
                 {
                     if (!inPlace)
                         sourceImage.detach();
                     sourceImage.d->format = QImage::Format_RGB32;
                 }
                 format = opaqueFormat;
             } else {
                 format = alphaFormat;
             }
         }
     }
 #endif
     if (inPlace && sourceImage.d->convertInPlace(format, flags)) {
         image = sourceImage;
     } else {
         image = sourceImage.convertToFormat(format);
     }
     if (image.d) {
         w = image.d->width;
         h = image.d->height;
         d = image.d->depth;
     } else {
         w = h = d = 0;
     }
     is_null = (w <= 0 || h <= 0);
     setSerialNumber(image.serialNumber());
 }
fill()
void QRasterPixmapData::fill (const QColor & color) virtual
Implements QPixmapData.
Definition at line 185 of file qpixmap_raster.cpp.
 {
     uint pixel;
     if (image.depth() == 1) {
         int gray = qGray(color.rgba());
         // Pick the best approximate color in the image's colortable.
         if (qAbs(qGray(image.color(0)) - gray) < qAbs(qGray(image.color(1)) - gray))
             pixel = 0;
         else
             pixel = 1;
     } else if (image.depth() >= 15) {
         int alpha = color.alpha();
         if (alpha != 255) {
             if (!image.hasAlphaChannel()) {
                 QImage::Format toFormat;
 #if !(defined(QT_HAVE_NEON) || defined(QT_ALWAYS_HAVE_SSE2))
                 if (image.format() == QImage::Format_RGB16)
                     toFormat = QImage::Format_ARGB8565_Premultiplied;
                 else if (image.format() == QImage::Format_RGB666)
                     toFormat = QImage::Format_ARGB6666_Premultiplied;
                 else if (image.format() == QImage::Format_RGB555)
                     toFormat = QImage::Format_ARGB8555_Premultiplied;
                 else if (image.format() == QImage::Format_RGB444)
                     toFormat = QImage::Format_ARGB4444_Premultiplied;
                 else
 #endif
                     toFormat = QImage::Format_ARGB32_Premultiplied;
                 if (!image.isNull() && qt_depthForFormat(image.format()) == qt_depthForFormat(toFormat)) {
                     image.detach();
                     image.d->format = toFormat;
                 } else {
                     image = QImage(image.width(), image.height(), toFormat);
                 }
             }
             switch (image.format()) {
             case QImage::Format_ARGB8565_Premultiplied:
                 pixel = qargb8565(color.rgba()).rawValue();
                 break;
             case QImage::Format_ARGB8555_Premultiplied:
                 pixel = qargb8555(color.rgba()).rawValue();
                 break;
             case QImage::Format_ARGB6666_Premultiplied:
                 pixel = qargb6666(color.rgba()).rawValue();
                 break;
             case QImage::Format_ARGB4444_Premultiplied:
                 pixel = qargb4444(color.rgba()).rawValue();
                 break;
             default:
                 pixel = PREMUL(color.rgba());
                 break;
             }
         } else {
             switch (image.format()) {
             case QImage::Format_RGB16:
                 pixel = qt_colorConvert<quint16, quint32>(color.rgba(), 0);
                 break;
             case QImage::Format_RGB444:
                 pixel = qrgb444(color.rgba()).rawValue();
                 break;
             case QImage::Format_RGB555:
                 pixel = qrgb555(color.rgba()).rawValue();
                 break;
             case QImage::Format_RGB666:
                 pixel = qrgb666(color.rgba()).rawValue();
                 break;
             case QImage::Format_RGB888:
                 pixel = qrgb888(color.rgba()).rawValue();
                 break;
             default:
                 pixel = color.rgba();
                 break;
             }
         }
     } else {
         pixel = 0;
         // ### what about 8 bits
     }
     image.fill(pixel);
 }
fromData()
bool QRasterPixmapData::fromData (const uchar * buffer, uint len, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 137 of file qpixmap_raster.cpp.
 {
     QByteArray a = QByteArray::fromRawData(reinterpret_cast<const char *>(buffer), len);
     QBuffer b(&a);
     b.open(QIODevice::ReadOnly);
     QImage image = QImageReader(&b, format).read();
     if (image.isNull())
         return false;
     createPixmapForImage(image, flags, /* inplace = */true);
     return !isNull();
 }
fromFile()
void QRasterPixmapData::fromFile (const QString & filename, Qt::ImageConversionFlags flags)
fromImage()
void QRasterPixmapData::fromImage (const QImage & image, Qt::ImageConversionFlags flags) virtual
Implements QPixmapData.
Definition at line 151 of file qpixmap_raster.cpp.
Referenced by QMeeGoRasterPixmapData::copy(), copy(), QDirectFBPaintEngine::drawTiledPixmap(), and QMeeGoGraphicsSystem::pixmapDataFromEGLSharedImage().
 {
     Q_UNUSED(flags);
     QImage image = sourceImage;
     createPixmapForImage(image, flags, /* inplace = */false);
 }
fromImageReader()
void QRasterPixmapData::fromImageReader (QImageReader * imageReader, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 159 of file qpixmap_raster.cpp.
 {
     Q_UNUSED(flags);
     QImage image = imageReader->read();
     if (image.isNull())
         return;
     createPixmapForImage(image, flags, /* inplace = */true);
 }
hasAlphaChannel()
bool QRasterPixmapData::hasAlphaChannel () const virtual
Implements QPixmapData.
Definition at line 308 of file qpixmap_raster.cpp.
 {
     return image.hasAlphaChannel();
 }
metric()
int QRasterPixmapData::metric (QPaintDevice::PaintDeviceMetric metric) const protected virtual
Implements QPixmapData.
Definition at line 352 of file qpixmap_raster.cpp.
 {
     QImageData *d = image.d;
     if (!d)
         return 0;
     // override the image dpi with the screen dpi when rendering to a pixmap
     switch (metric) {
     case QPaintDevice::PdmWidth:
         return w;
     case QPaintDevice::PdmHeight:
         return h;
     case QPaintDevice::PdmWidthMM:
         return qRound(d->width * 25.4 / qt_defaultDpiX());
     case QPaintDevice::PdmHeightMM:
         return qRound(d->height * 25.4 / qt_defaultDpiY());
     case QPaintDevice::PdmNumColors:
         return d->colortable.size();
     case QPaintDevice::PdmDepth:
         return this->d;
     case QPaintDevice::PdmDpiX: // fall-through
     case QPaintDevice::PdmPhysicalDpiX:
         return qt_defaultDpiX();
     case QPaintDevice::PdmDpiY: // fall-through
     case QPaintDevice::PdmPhysicalDpiY:
         return qt_defaultDpiY();
     default:
         qWarning("QRasterPixmapData::metric(): Unhandled metric type %d", metric);
         break;
     }
     return 0;
 }
paintEngine()
QPaintEngine * QRasterPixmapData::paintEngine () const virtual
Implements QPixmapData.
Definition at line 347 of file qpixmap_raster.cpp.
 {
     return image.paintEngine();
 }
resize()
void QRasterPixmapData::resize (int width, int height) virtual
Implements QPixmapData.
Definition at line 102 of file qpixmap_raster.cpp.
 {
     QImage::Format format;
 #ifdef Q_WS_QWS
     if (pixelType() == BitmapType) {
         format = QImage::Format_Mono;
     } else {
         format = QScreen::instance()->pixelFormat();
         if (format == QImage::Format_Invalid)
             format = QImage::Format_ARGB32_Premultiplied;
         else if (format == QImage::Format_Indexed8) // currently not supported
             format = QImage::Format_RGB444;
     }
 #else
     if (pixelType() == BitmapType)
         format = QImage::Format_MonoLSB;
     else
         format = QNativeImage::systemFormat();
 #endif
     image = QImage(width, height, format);
     w = width;
     h = height;
     d = image.depth();
     is_null = (w <= 0 || h <= 0);
     if (pixelType() == BitmapType && !image.isNull()) {
         image.setColorCount(2);
         image.setColor(0, QColor(Qt::color0).rgba());
         image.setColor(1, QColor(Qt::color1).rgba());
     }
     setSerialNumber(image.serialNumber());
 }
scroll()
bool QRasterPixmapData::scroll (int dx, int dy, const QRect & rect) virtual
Reimplemented from QPixmapData.
Definition at line 178 of file qpixmap_raster.cpp.
 {
     if (!image.isNull())
         qt_scrollRectInImage(image, rect, QPoint(dx, dy));
     return true;
 }
setAlphaChannel()
void QRasterPixmapData::setAlphaChannel (const QPixmap & alphaChannel) virtual
Reimplemented from QPixmapData.
Definition at line 342 of file qpixmap_raster.cpp.
 {
     image.setAlphaChannel(alphaChannel.toImage());
 }
setImage()
void QRasterPixmapData::setImage (const QImage & image) protected
setMask()
void QRasterPixmapData::setMask (const QBitmap & mask) virtual
Reimplemented from QPixmapData.
Definition at line 269 of file qpixmap_raster.cpp.
 {
     if (mask.size().isEmpty()) {
         if (image.depth() != 1) { // hw: ????
             image = image.convertToFormat(QImage::Format_RGB32);
         }
     } else {
         const int w = image.width();
         const int h = image.height();
         switch (image.depth()) {
         case 1: {
             const QImage imageMask = mask.toImage().convertToFormat(image.format());
             for (int y = 0; y < h; ++y) {
                 const uchar *mscan = imageMask.scanLine(y);
                 uchar *tscan = image.scanLine(y);
                 int bytesPerLine = image.bytesPerLine();
                 for (int i = 0; i < bytesPerLine; ++i)
                     tscan[i] &= mscan[i];
             }
             break;
         }
         default: {
             const QImage imageMask = mask.toImage().convertToFormat(QImage::Format_MonoLSB);
             image = image.convertToFormat(QImage::Format_ARGB32_Premultiplied);
             for (int y = 0; y < h; ++y) {
                 const uchar *mscan = imageMask.scanLine(y);
                 QRgb *tscan = (QRgb *)image.scanLine(y);
                 for (int x = 0; x < w; ++x) {
                     if (!(mscan[x>>3] & qt_pixmap_bit_mask[x&7]))
                         tscan[x] = 0;
                 }
             }
             break;
         }
         }
     }
 }
toImage() [1/2]
QImage QRasterPixmapData::toImage () const virtual
Implements QPixmapData.
Definition at line 313 of file qpixmap_raster.cpp.
 {
     if (!image.isNull()) {
         QImageData *data = const_cast<QImage &>(image).data_ptr();
         if (data->paintEngine && data->paintEngine->isActive()
             && data->paintEngine->paintDevice() == &image)
         {
             return image.copy();
         }
     }
     return image;
 }
toImage() [2/2]
QImage QRasterPixmapData::toImage (const QRect & rect) const virtual
Reimplemented from QPixmapData.
Definition at line 327 of file qpixmap_raster.cpp.
 {
     if (rect.isNull())
         return image;
     QRect clipped = rect.intersected(QRect(0, 0, w, h));
     const uint du = uint(d);
     if ((du % 8 == 0) && (((uint(clipped.x()) * du)) % 32 == 0))
         return QImage(image.scanLine(clipped.y()) + clipped.x() * (du / 8),
                       clipped.width(), clipped.height(),
                       image.bytesPerLine(), image.format());
     else
         return image.copy(clipped);
 }
Friends and Related Functions
QBitmap
friend class QBitmap friend
Definition at line 98 of file qpixmap_raster_p.h.
QPixmap
friend class QPixmap friend
Definition at line 97 of file qpixmap_raster_p.h.
QPixmapCacheEntry
friend class QPixmapCacheEntry friend
Definition at line 99 of file qpixmap_raster_p.h.
QRasterPaintEngine
friend class QRasterPaintEngine friend
Definition at line 100 of file qpixmap_raster_p.h.
Properties
image
QImage QRasterPixmapData::image protected
Definition at line 94 of file qpixmap_raster_p.h.
Referenced by buffer(), QPixmap::clut(), QPixmap::colorCount(), createPixmapForImage(), QPixmap::detach(), fill(), fromData(), fromImage(), fromImageReader(), hasAlphaChannel(), metric(), paintEngine(), QPixmapCacheEntry::QPixmapCacheEntry(), QPixmap::qwsBits(), QPixmap::qwsBytesPerLine(), resize(), scroll(), setAlphaChannel(), setMask(), toImage(), and QPixmap::toWinHBITMAP().
The documentation for this class was generated from the following files:
/src/gui/image/qpixmap_raster_p.h
/src/gui/image/qpixmap_raster.cpp