Qt 4.8: QPatternist::GMonth Class Reference
QPatternist::GMonth Class Reference
Implements the value instance of the xs:gMonth type.
#include <qgmonth_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AbstractDateTime
enum { DefaultYear = 2000, DefaultMonth = 1, DefaultDay = 1 }
typedef QExplicitlySharedDataPointer< AbstractDateTime > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AbstractDateTime
AbstractDateTime (const QDateTime &dateTime)
QString dateToString () const
virtual Item fromValue (const QDateTime &dt) const
QString timeToString () const
const QDateTime & toDateTime () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static GMonth::Ptr fromDateTime (const QDateTime &dt)
static GMonth::Ptr fromLexical (const QString &string)
Static Public Functions inherited from QPatternist::AbstractDateTime
static bool isRangeValid (const QDate &date, QString &message)
static QString serializeMSeconds (const MSecondProperty msecs)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
GMonth (const QDateTime &dateTime)
Protected Functions inherited from QPatternist::AbstractDateTime
QString zoneOffsetToString () const
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDateTime
static void copyTimeSpec (const QDateTime &from, QDateTime &to)
Makes the QDateTime::timeSpec() and QDateTime::zoneOffset() of ot * consistent to from.
static QDateTime create (AtomicValue::Ptr &errorMessage, const QString &lexicalSource, const CaptureTable &captTable)
Protected Variables inherited from QPatternist::AbstractDateTime
const QDateTime m_dateTime
Detailed Description
Implements the value instance of the xs:gMonth type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qgmonth_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::GMonth::Ptr
Definition at line 72 of file qgmonth_p.h.
Constructors and Destructors
GMonth()
GMonth::GMonth (const QDateTime & dateTime) protected
Definition at line 50 of file qgmonth.cpp.
Referenced by fromDateTime(), and fromLexical().
                                         : AbstractDateTime(dateTime)
 {
 }
Functions
fromDateTime()
GMonth::Ptr GMonth::fromDateTime (const QDateTime & dt) static
Definition at line 77 of file qgmonth.cpp.
Referenced by QPatternist::AbstractDateTimeToGMonthCaster::castFrom().
 {
     QDateTime result(QDate(DefaultYear, dt.date().month(), DefaultDay));
     copyTimeSpec(dt, result);
     return GMonth::Ptr(new GMonth(result));
 }
fromLexical()
GMonth::Ptr GMonth::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 54 of file qgmonth.cpp.
Referenced by QPatternist::StringToGMonthCaster::castFrom().
 {
     static const CaptureTable captureTable( // STATIC DATA
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"                             /* Any preceding whitespace. */
                 "--"                                /* Delimier. */
                 "(\\d{2})"                          /* The month part, "03". */
                 "(?:(\\+|-)(\\d{2}):(\\d{2})|(Z))?" /* Timezone, "+08:24". */
                 "\\s*$"                             /* Any terminating whitespace. */))),
         /*zoneOffsetSignP*/         2,
         /*zoneOffsetHourP*/         3,
         /*zoneOffsetMinuteP*/       4,
         /*zoneOffsetUTCSymbolP*/    5,
         /*yearP*/                   -1,
         /*monthP*/                  1);
     AtomicValue::Ptr err;
     const QDateTime retval(create(err, lexical, captureTable));
     return err ? err : GMonth::Ptr(new GMonth(retval));
 }
stringValue()
QString GMonth::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 85 of file qgmonth.cpp.
 {
     return m_dateTime.toString(QLatin1String("--MM")) + zoneOffsetToString();
 }
type()
ItemType::Ptr GMonth::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 90 of file qgmonth.cpp.
 {
     return BuiltinTypes::xsGMonth;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 84 of file qgmonth_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qgmonth_p.h
/src/xmlpatterns/data/qgmonth.cpp