Qt 4.8: QDeclarativeRewrite::RewriteBinding Class Reference
QDeclarativeRewrite::RewriteBinding Class Reference
#include <qdeclarativerewrite_p.h>
Public Functions
QString operator() (const QString &code, bool *ok=0, bool *sharable=0)
QString operator() (QDeclarativeJS::AST::Node *node, const QString &code, bool *sharable=0)
void setName (const QByteArray &name)
Protected Functions
void accept (AST::Node *node)
virtual void endVisit (AST::DoWhileStatement *ast)
virtual void endVisit (AST::WhileStatement *ast)
virtual void endVisit (AST::ForStatement *ast)
virtual void endVisit (AST::LocalForStatement *ast)
virtual void endVisit (AST::ForEachStatement *ast)
virtual void endVisit (AST::LocalForEachStatement *ast)
QString rewrite (QString code, unsigned position, AST::Statement *node)
virtual bool visit (AST::Block *ast)
virtual bool visit (AST::ExpressionStatement *ast)
virtual bool visit (AST::DoWhileStatement *ast)
virtual bool visit (AST::WhileStatement *ast)
virtual bool visit (AST::ForStatement *ast)
virtual bool visit (AST::LocalForStatement *ast)
virtual bool visit (AST::ForEachStatement *ast)
virtual bool visit (AST::LocalForEachStatement *ast)
Protected Functions inherited from QDeclarativeJS::AST::Visitor
virtual void endVisit (UiProgram *)
virtual void endVisit (UiImportList *)
virtual void endVisit (UiImport *)
virtual void endVisit (UiPublicMember *)
virtual void endVisit (UiSourceElement *)
virtual void endVisit (UiObjectDefinition *)
virtual void endVisit (UiObjectInitializer *)
virtual void endVisit (UiObjectBinding *)
virtual void endVisit (UiScriptBinding *)
virtual void endVisit (UiArrayBinding *)
virtual void endVisit (UiObjectMemberList *)
virtual void endVisit (UiArrayMemberList *)
virtual void endVisit (UiQualifiedId *)
virtual void endVisit (UiSignature *)
virtual void endVisit (UiFormalList *)
virtual void endVisit (UiFormal *)
virtual void endVisit (ThisExpression *)
virtual void endVisit (IdentifierExpression *)
virtual void endVisit (NullExpression *)
virtual void endVisit (TrueLiteral *)
virtual void endVisit (FalseLiteral *)
virtual void endVisit (StringLiteral *)
virtual void endVisit (NumericLiteral *)
virtual void endVisit (RegExpLiteral *)
virtual void endVisit (ArrayLiteral *)
virtual void endVisit (ObjectLiteral *)
virtual void endVisit (ElementList *)
virtual void endVisit (Elision *)
virtual void endVisit (PropertyNameAndValueList *)
virtual void endVisit (NestedExpression *)
virtual void endVisit (IdentifierPropertyName *)
virtual void endVisit (StringLiteralPropertyName *)
virtual void endVisit (NumericLiteralPropertyName *)
virtual void endVisit (ArrayMemberExpression *)
virtual void endVisit (FieldMemberExpression *)
virtual void endVisit (NewMemberExpression *)
virtual void endVisit (NewExpression *)
virtual void endVisit (CallExpression *)
virtual void endVisit (ArgumentList *)
virtual void endVisit (PostIncrementExpression *)
virtual void endVisit (PostDecrementExpression *)
virtual void endVisit (DeleteExpression *)
virtual void endVisit (VoidExpression *)
virtual void endVisit (TypeOfExpression *)
virtual void endVisit (PreIncrementExpression *)
virtual void endVisit (PreDecrementExpression *)
virtual void endVisit (UnaryPlusExpression *)
virtual void endVisit (UnaryMinusExpression *)
virtual void endVisit (TildeExpression *)
virtual void endVisit (NotExpression *)
virtual void endVisit (BinaryExpression *)
virtual void endVisit (ConditionalExpression *)
virtual void endVisit (Expression *)
virtual void endVisit (Block *)
virtual void endVisit (StatementList *)
virtual void endVisit (VariableStatement *)
virtual void endVisit (VariableDeclarationList *)
virtual void endVisit (VariableDeclaration *)
virtual void endVisit (EmptyStatement *)
virtual void endVisit (ExpressionStatement *)
virtual void endVisit (IfStatement *)
virtual void endVisit (ContinueStatement *)
virtual void endVisit (BreakStatement *)
virtual void endVisit (ReturnStatement *)
virtual void endVisit (WithStatement *)
virtual void endVisit (SwitchStatement *)
virtual void endVisit (CaseBlock *)
virtual void endVisit (CaseClauses *)
virtual void endVisit (CaseClause *)
virtual void endVisit (DefaultClause *)
virtual void endVisit (LabelledStatement *)
virtual void endVisit (ThrowStatement *)
virtual void endVisit (TryStatement *)
virtual void endVisit (Catch *)
virtual void endVisit (Finally *)
virtual void endVisit (FunctionDeclaration *)
virtual void endVisit (FunctionExpression *)
virtual void endVisit (FormalParameterList *)
virtual void endVisit (FunctionBody *)
virtual void endVisit (Program *)
virtual void endVisit (SourceElements *)
virtual void endVisit (FunctionSourceElement *)
virtual void endVisit (StatementSourceElement *)
virtual void endVisit (DebuggerStatement *)
virtual void postVisit (Node *)
virtual bool preVisit (Node *)
virtual bool visit (UiProgram *)
virtual bool visit (UiImportList *)
virtual bool visit (UiImport *)
virtual bool visit (UiPublicMember *)
virtual bool visit (UiSourceElement *)
virtual bool visit (UiObjectDefinition *)
virtual bool visit (UiObjectInitializer *)
virtual bool visit (UiObjectBinding *)
virtual bool visit (UiScriptBinding *)
virtual bool visit (UiArrayBinding *)
virtual bool visit (UiObjectMemberList *)
virtual bool visit (UiArrayMemberList *)
virtual bool visit (UiQualifiedId *)
virtual bool visit (UiSignature *)
virtual bool visit (UiFormalList *)
virtual bool visit (UiFormal *)
virtual bool visit (ThisExpression *)
virtual bool visit (IdentifierExpression *)
virtual bool visit (NullExpression *)
virtual bool visit (TrueLiteral *)
virtual bool visit (FalseLiteral *)
virtual bool visit (StringLiteral *)
virtual bool visit (NumericLiteral *)
virtual bool visit (RegExpLiteral *)
virtual bool visit (ArrayLiteral *)
virtual bool visit (ObjectLiteral *)
virtual bool visit (ElementList *)
virtual bool visit (Elision *)
virtual bool visit (PropertyNameAndValueList *)
virtual bool visit (NestedExpression *)
virtual bool visit (IdentifierPropertyName *)
virtual bool visit (StringLiteralPropertyName *)
virtual bool visit (NumericLiteralPropertyName *)
virtual bool visit (ArrayMemberExpression *)
virtual bool visit (FieldMemberExpression *)
virtual bool visit (NewMemberExpression *)
virtual bool visit (NewExpression *)
virtual bool visit (CallExpression *)
virtual bool visit (ArgumentList *)
virtual bool visit (PostIncrementExpression *)
virtual bool visit (PostDecrementExpression *)
virtual bool visit (DeleteExpression *)
virtual bool visit (VoidExpression *)
virtual bool visit (TypeOfExpression *)
virtual bool visit (PreIncrementExpression *)
virtual bool visit (PreDecrementExpression *)
virtual bool visit (UnaryPlusExpression *)
virtual bool visit (UnaryMinusExpression *)
virtual bool visit (TildeExpression *)
virtual bool visit (NotExpression *)
virtual bool visit (BinaryExpression *)
virtual bool visit (ConditionalExpression *)
virtual bool visit (Expression *)
virtual bool visit (StatementList *)
virtual bool visit (VariableStatement *)
virtual bool visit (VariableDeclarationList *)
virtual bool visit (VariableDeclaration *)
virtual bool visit (EmptyStatement *)
virtual bool visit (IfStatement *)
virtual bool visit (ContinueStatement *)
virtual bool visit (BreakStatement *)
virtual bool visit (ReturnStatement *)
virtual bool visit (WithStatement *)
virtual bool visit (SwitchStatement *)
virtual bool visit (CaseBlock *)
virtual bool visit (CaseClauses *)
virtual bool visit (CaseClause *)
virtual bool visit (DefaultClause *)
virtual bool visit (LabelledStatement *)
virtual bool visit (ThrowStatement *)
virtual bool visit (TryStatement *)
virtual bool visit (Catch *)
virtual bool visit (Finally *)
virtual bool visit (FunctionDeclaration *)
virtual bool visit (FunctionExpression *)
virtual bool visit (FormalParameterList *)
virtual bool visit (FunctionBody *)
virtual bool visit (Program *)
virtual bool visit (SourceElements *)
virtual bool visit (FunctionSourceElement *)
virtual bool visit (StatementSourceElement *)
virtual bool visit (DebuggerStatement *)
Visitor ()
virtual ~Visitor ()
Properties
int _inLoop
QByteArray _name
unsigned _position
TextWriter * _writer
Detailed Description
Definition at line 78 of file qdeclarativerewrite_p.h.
Functions
accept()
void QDeclarativeRewrite::RewriteBinding::accept (AST::Node * node) protected
Definition at line 145 of file qdeclarativerewrite.cpp.
 {
     AST::Node::acceptChild(node, this);
 }
endVisit() [1/6]
void QDeclarativeRewrite::RewriteBinding::endVisit (AST::DoWhileStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 211 of file qdeclarativerewrite.cpp.
 {
     --_inLoop;
 }
endVisit() [2/6]
void QDeclarativeRewrite::RewriteBinding::endVisit (AST::WhileStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 222 of file qdeclarativerewrite.cpp.
 {
     --_inLoop;
 }
endVisit() [3/6]
void QDeclarativeRewrite::RewriteBinding::endVisit (AST::ForStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 233 of file qdeclarativerewrite.cpp.
 {
     --_inLoop;
 }
endVisit() [4/6]
void QDeclarativeRewrite::RewriteBinding::endVisit (AST::LocalForStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 244 of file qdeclarativerewrite.cpp.
 {
     --_inLoop;
 }
endVisit() [5/6]
void QDeclarativeRewrite::RewriteBinding::endVisit (AST::ForEachStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 255 of file qdeclarativerewrite.cpp.
 {
     --_inLoop;
 }
endVisit() [6/6]
void QDeclarativeRewrite::RewriteBinding::endVisit (AST::LocalForEachStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 266 of file qdeclarativerewrite.cpp.
 {
     --_inLoop;
 }
operator()() [1/2]
QString QDeclarativeRewrite::RewriteBinding::operator() (const QString & code, bool * ok = 0, bool * sharable = 0)
Definition at line 75 of file qdeclarativerewrite.cpp.
 {
     Engine engine;
     NodePool pool(QString(), &engine);
     Lexer lexer(&engine);
     Parser parser(&engine);
     lexer.setCode(code, 0);
     parser.parseStatement();
     if (!parser.statement()) {
         if (ok) *ok = false;
         return QString();
     } else {
         if (ok) *ok = true;
         if (sharable) {
             SharedBindingTester tester;
             *sharable = tester.isSharable(parser.statement());
         }
     }
     return rewrite(code, 0, parser.statement());
 }
operator()() [2/2]
QString QDeclarativeRewrite::RewriteBinding::operator() (QDeclarativeJS::AST::Node * node, const QString & code, bool * sharable = 0)
Definition at line 96 of file qdeclarativerewrite.cpp.
 {
     if (!node)
         return code;
     if (sharable) {
         SharedBindingTester tester;
         *sharable = tester.isSharable(node);
     }
     QDeclarativeJS::AST::ExpressionNode *expression = node->expressionCast();
     QDeclarativeJS::AST::Statement *statement = node->statementCast();
     if(!expression && !statement)
         return code;
     TextWriter w;
     _writer = &w;
     _position = expression ? expression->firstSourceLocation().begin() : statement->firstSourceLocation().begin();
     _inLoop = 0;
     accept(node);
     unsigned startOfStatement = 0;
     unsigned endOfStatement = (expression ? expression->lastSourceLocation().end() : statement->lastSourceLocation().end()) - _position;
     QString startString = QLatin1String("(function ") + QString::fromUtf8(_name) + QLatin1String("() { ");
     if (expression)
         startString += QLatin1String("return ");
     _writer->replace(startOfStatement, 0, startString);
     _writer->replace(endOfStatement, 0, QLatin1String(" })"));
     if (rewriteDump()) {
         qWarning() << "=============================================================";
         qWarning() << "Rewrote:";
         qWarning() << qPrintable(code);
     }
     QString codeCopy = code;
     w.write(&codeCopy);
     if (rewriteDump()) {
         qWarning() << "To:";
         qWarning() << qPrintable(code);
         qWarning() << "=============================================================";
     }
     return codeCopy;
 }
rewrite()
QString QDeclarativeRewrite::RewriteBinding::rewrite (QString code, unsigned position, AST::Statement * node) protected
Definition at line 150 of file qdeclarativerewrite.cpp.
 {
     TextWriter w;
     _writer = &w;
     _position = position;
     _inLoop = 0;
     accept(node);
     unsigned startOfStatement = node->firstSourceLocation().begin() - _position;
     unsigned endOfStatement = node->lastSourceLocation().end() - _position;
     _writer->replace(startOfStatement, 0, QLatin1String("(function ") + QString::fromUtf8(_name) + QLatin1String("() { "));
     _writer->replace(endOfStatement, 0, QLatin1String(" })"));
     if (rewriteDump()) {
         qWarning() << "=============================================================";
         qWarning() << "Rewrote:";
         qWarning() << qPrintable(code);
     }
     w.write(&code);
     if (rewriteDump()) {
         qWarning() << "To:";
         qWarning() << qPrintable(code);
         qWarning() << "=============================================================";
     }
     return code;
 }
setName()
void QDeclarativeRewrite::RewriteBinding::setName (const QByteArray & name) inline
Definition at line 89 of file qdeclarativerewrite_p.h.
Referenced by QDeclarativeCompiler::completeComponentBuild(), QDeclarativeCompiler::rewriteBinding(), and QDeclarativeExpressionPrivate::scriptValue().
 { _name = name; }
visit() [1/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::Block * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 183 of file qdeclarativerewrite.cpp.
 {
     for (AST::StatementList *it = ast->statements; it; it = it->next) {
         if (! it->next) {
             // we need to rewrite only the last statement of a block.
             accept(it->statement);
         }
     }
     return false;
 }
visit() [2/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::ExpressionStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 195 of file qdeclarativerewrite.cpp.
 {
     if (! _inLoop) {
         unsigned startOfExpressionStatement = ast->firstSourceLocation().begin() - _position;
         _writer->replace(startOfExpressionStatement, 0, QLatin1String("return "));
     }
     return false;
 }
visit() [3/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::DoWhileStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 205 of file qdeclarativerewrite.cpp.
 {
     ++_inLoop;
     return true;
 }
visit() [4/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::WhileStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 216 of file qdeclarativerewrite.cpp.
 {
     ++_inLoop;
     return true;
 }
visit() [5/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::ForStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 227 of file qdeclarativerewrite.cpp.
 {
     ++_inLoop;
     return true;
 }
visit() [6/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::LocalForStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 238 of file qdeclarativerewrite.cpp.
 {
     ++_inLoop;
     return true;
 }
visit() [7/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::ForEachStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 249 of file qdeclarativerewrite.cpp.
 {
     ++_inLoop;
     return true;
 }
visit() [8/8]
bool QDeclarativeRewrite::RewriteBinding::visit (AST::LocalForEachStatement * ast) protected virtual
Reimplemented from QDeclarativeJS::AST::Visitor.
Definition at line 260 of file qdeclarativerewrite.cpp.
 {
     ++_inLoop;
     return true;
 }
Properties
_inLoop
int QDeclarativeRewrite::RewriteBinding::_inLoop private
Definition at line 119 of file qdeclarativerewrite_p.h.
_name
QByteArray QDeclarativeRewrite::RewriteBinding::_name private
Definition at line 82 of file qdeclarativerewrite_p.h.
_position
unsigned QDeclarativeRewrite::RewriteBinding::_position private
Definition at line 80 of file qdeclarativerewrite_p.h.
_writer
TextWriter* QDeclarativeRewrite::RewriteBinding::_writer private
Definition at line 81 of file qdeclarativerewrite_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativerewrite_p.h
/src/declarative/qml/qdeclarativerewrite.cpp