Qt 4.8: QPixmapBlurFilter Class Reference
QPixmapBlurFilter Class Reference
The QPixmapBlurFilter class provides blur filtering for pixmaps.
#include <qpixmapfilter_p.h>
Public Functions
QGraphicsBlurEffect::BlurHints blurHints () const
Gets the blur hints of the blur filter.
QRectF boundingRectFor (const QRectF &rect) const
void draw (QPainter *painter, const QPointF &dest, const QPixmap &src, const QRectF &srcRect=QRectF()) const
QPixmapBlurFilter (QObject *parent=0)
Constructs a pixmap blur filter.
qreal radius () const
Gets the radius of the blur filter.
void setBlurHints (QGraphicsBlurEffect::BlurHints hints)
Setting the blur hints to PerformanceHint causes the implementation to trade off visual quality to blur the image faster.
void setRadius (qreal radius)
Sets the radius of the blur filter.
~QPixmapBlurFilter ()
Destructor of pixmap blur filter.
Public Functions inherited from QPixmapFilter
FilterType type () const
Returns the type of the filter.
virtual ~QPixmapFilter ()=0
Destroys the pixmap filter.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Friends
class QGLPixmapBlurFilter
Additional Inherited Members
Public Types inherited from QPixmapFilter
enum FilterType {
ConvolutionFilter, ColorizeFilter, DropShadowFilter, BlurFilter,
UserFilter = 1024
}
This enum describes the types of filter that can be applied to pixmaps.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QPixmapFilter
QPixmapFilter (QPixmapFilterPrivate &d, FilterType type, QObject *parent)
QPixmapFilter (FilterType type, QObject *parent)
Constructs a default QPixmapFilter with the given type.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPixmapBlurFilter class provides blur filtering for pixmaps.
Since
4.6
QPixmapBlurFilter implements a blur pixmap filter, which is applied when QPixmapFilter::draw() is called.
The filter lets you specialize the radius of the blur as well as hints as to whether to prefer performance or quality.
By default, the blur effect is produced by applying an exponential filter generated from the specified blurRadius(). Paint engines may override this with a custom blur that is faster on the underlying hardware.
See also
{Pixmap Filters Example}, QPixmapConvolutionFilter, QPixmapDropShadowFilter
Warning
This function is not part of the public interface.
Definition at line 125 of file qpixmapfilter_p.h.
Constructors and Destructors
QPixmapBlurFilter()
QPixmapBlurFilter::QPixmapBlurFilter (QObject * parent = 0)
Constructs a pixmap blur filter.
Warning
This function is not part of the public interface.
Definition at line 539 of file qpixmapfilter.cpp.
     : QPixmapFilter(*new QPixmapBlurFilterPrivate, BlurFilter, parent)
 {
 }
~QPixmapBlurFilter()
QPixmapBlurFilter::~QPixmapBlurFilter ()
Destructor of pixmap blur filter.
Warning
This function is not part of the public interface.
Definition at line 549 of file qpixmapfilter.cpp.
 {
 }
Functions
blurHints()
QGraphicsBlurEffect::BlurHints QPixmapBlurFilter::blurHints () const
Gets the blur hints of the blur filter.
Warning
This function is not part of the public interface.
Definition at line 601 of file qpixmapfilter.cpp.
 {
     Q_D(const QPixmapBlurFilter);
     return d->hints;
 }
boundingRectFor()
QRectF QPixmapBlurFilter::boundingRectFor (const QRectF & rect) const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPixmapFilter.
Definition at line 612 of file qpixmapfilter.cpp.
 {
     Q_D(const QPixmapBlurFilter);
     const qreal delta = radiusScale * d->radius + 1;
     return rect.adjusted(-delta, -delta, delta, delta);
 }
draw()
void QPixmapBlurFilter::draw (QPainter * painter, const QPointF & p, const QPixmap & src, const QRectF & rect = QRectF()) const virtual
Warning
This function is not part of the public interface.
Implements QPixmapFilter.
Reimplemented in QVGPixmapBlurFilter, and QGLPixmapFilter< QPixmapBlurFilter >.
Definition at line 925 of file qpixmapfilter.cpp.
Referenced by QVGPixmapBlurFilter::draw(), and draw().
 {
     Q_D(const QPixmapBlurFilter);
     if (!painter->isActive())
         return;
     if (src.isNull())
         return;
     QRectF srcRect = rect;
     if (srcRect.isNull())
         srcRect = src.rect();
     if (d->radius <= 1) {
         painter->drawPixmap(srcRect.translated(p), src, srcRect);
         return;
     }
     qreal scaledRadius = radiusScale * d->radius;
     qreal scale;
     if (qt_scaleForTransform(painter->transform(), &scale))
         scaledRadius /= scale;
     QPixmapFilter *filter = painter->paintEngine() && painter->paintEngine()->isExtended() ?
         static_cast<QPaintEngineEx *>(painter->paintEngine())->pixmapFilter(type(), this) : 0;
     QPixmapBlurFilter *blurFilter = static_cast<QPixmapBlurFilter*>(filter);
     if (blurFilter) {
         blurFilter->setRadius(scaledRadius);
         blurFilter->setBlurHints(d->hints);
         blurFilter->draw(painter, p, src, srcRect);
         return;
     }
     QImage srcImage;
     QImage destImage;
     if (srcRect == src.rect()) {
         srcImage = src.toImage();
     } else {
         QRect rect = srcRect.toAlignedRect().intersected(src.rect());
         srcImage = src.copy(rect).toImage();
     }
     QTransform transform = painter->worldTransform();
     painter->translate(p);
     qt_blurImage(painter, srcImage, scaledRadius, (d->hints & QGraphicsBlurEffect::QualityHint), false);
     painter->setWorldTransform(transform);
 }
radius()
qreal QPixmapBlurFilter::radius () const
Gets the radius of the blur filter.
Warning
This function is not part of the public interface.
Definition at line 569 of file qpixmapfilter.cpp.
Referenced by QVGPixmapBlurFilter::draw(), qt_blurImage(), and setRadius().
 {
     Q_D(const QPixmapBlurFilter);
     return d->radius;
 }
setBlurHints()
void QPixmapBlurFilter::setBlurHints (QGraphicsBlurEffect::BlurHints hints)
Setting the blur hints to PerformanceHint causes the implementation to trade off visual quality to blur the image faster.
Setting the blur hints to QualityHint causes the implementation to improve visual quality at the expense of speed.
AnimationHint causes the implementation to optimize for animating the blur radius, possibly by caching blurred versions of the source pixmap.
The implementation is free to ignore this value if it only has a single blur algorithm.
Warning
This function is not part of the public interface.
Definition at line 590 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapBlurFilter);
     d->hints = hints;
 }
setRadius()
void QPixmapBlurFilter::setRadius (qreal radius)
Sets the radius of the blur filter.
Higher radius produces increased blurriness.
Warning
This function is not part of the public interface.
Definition at line 558 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapBlurFilter);
     d->radius = radius;
 }
Friends and Related Functions
QGLPixmapBlurFilter
friend class QGLPixmapBlurFilter friend
Definition at line 144 of file qpixmapfilter_p.h.
The documentation for this class was generated from the following files:
/src/gui/image/qpixmapfilter_p.h
/src/gui/image/qpixmapfilter.cpp