Qt 4.8: QGLBuffer Class Reference
QGLBuffer Class Reference
The QGLBuffer class provides functions for creating and managing GL buffer objects.
#include <qglbuffer.h>
Public Types
enum Access { ReadOnly = 0x88B8, WriteOnly = 0x88B9, ReadWrite = 0x88BA }
This enum defines the access mode for QGLBuffer::map().
enum Type { VertexBuffer = 0x8892, IndexBuffer = 0x8893, PixelPackBuffer = 0x88EB, PixelUnpackBuffer = 0x88EC }
This enum defines the type of GL buffer object to create with QGLBuffer.
enum UsagePattern {
StreamDraw = 0x88E0, StreamRead = 0x88E1, StreamCopy = 0x88E2, StaticDraw = 0x88E4,
StaticRead = 0x88E5, StaticCopy = 0x88E6, DynamicDraw = 0x88E8, DynamicRead = 0x88E9,
DynamicCopy = 0x88EA
}
This enum defines the usage pattern of a QGLBuffer object.
Public Functions
void allocate (const void *data, int count)
Allocates count bytes of space to the buffer, initialized to the contents of data.
void allocate (int count)
Allocates count bytes of space to the buffer.
bool bind ()
Binds the buffer associated with this object to the current GL context.
GLuint bufferId () const
Returns the GL identifier associated with this buffer; zero if the buffer has not been created.
bool create ()
Creates the buffer object in the GL server.
void destroy ()
Destroys this buffer object, including the storage being used in the GL server.
bool isCreated () const
Returns true if this buffer has been created; false otherwise.
void * map (QGLBuffer::Access access)
Maps the contents of this buffer into the application's memory space and returns a pointer to it.
QGLBuffer & operator= (const QGLBuffer &other)
Assigns a shallow copy of other to this object.
QGLBuffer ()
Constructs a new buffer object of type QGLBuffer::VertexBuffer.
QGLBuffer (QGLBuffer::Type type)
Constructs a new buffer object of type.
QGLBuffer (const QGLBuffer &other)
Constructs a shallow copy of other.
bool read (int offset, void *data, int count)
Reads the count bytes in this buffer starting at offset into data.
void release ()
Releases the buffer associated with this object from the current GL context.
void setUsagePattern (QGLBuffer::UsagePattern value)
Sets the usage pattern for this buffer object to value.
int size () const
Returns the size of the data in this buffer, for reading operations.
QGLBuffer::Type type () const
Returns the type of buffer represented by this object.
bool unmap ()
Unmaps the buffer after it was mapped into the application's memory space with a previous call to map().
QGLBuffer::UsagePattern usagePattern () const
Returns the usage pattern for this buffer object.
void write (int offset, const void *data, int count)
Replaces the count bytes of this buffer starting at offset with the contents of data.
~QGLBuffer ()
Destroys this buffer object, including the storage being used in the GL server.
Static Public Functions
static void release (QGLBuffer::Type type)
Releases the buffer associated with type in the current QGLContext.
Properties
QGLBufferPrivate * d_ptr
Detailed Description
The QGLBuffer class provides functions for creating and managing GL buffer objects.
Since
4.7
Buffer objects are created in the GL server so that the client application can avoid uploading vertices, indices, texture image data, etc every time they are needed.
QGLBuffer objects can be copied around as a reference to the underlying GL buffer object:
QGLBuffer buffer1(QGLBuffer::IndexBuffer);
buffer1.create();
QGLBuffer buffer2 = buffer1;
QGLBuffer performs a shallow copy when objects are copied in this manner, but does not implement copy-on-write semantics. The original object will be affected whenever the copy is modified.
Definition at line 56 of file qglbuffer.h.
Enumerations
Access
enum QGLBuffer::Access
This enum defines the access mode for QGLBuffer::map().
ReadOnly The buffer will be mapped for reading only.
WriteOnly The buffer will be mapped for writing only.
ReadWrite The buffer will be mapped for reading and writing.
Enumerator
ReadOnly
WriteOnly
ReadWrite
Definition at line 87 of file qglbuffer.h.
     {
         ReadOnly            = 0x88B8, // GL_READ_ONLY
         WriteOnly           = 0x88B9, // GL_WRITE_ONLY
         ReadWrite           = 0x88BA  // GL_READ_WRITE
     };
Type
enum QGLBuffer::Type
This enum defines the type of GL buffer object to create with QGLBuffer.
VertexBuffer Vertex buffer object for use when specifying vertex arrays.
IndexBuffer Index buffer object for use with glDrawElements().
PixelPackBuffer Pixel pack buffer object for reading pixel data from the GL server (for example, with glReadPixels()). Not supported under OpenGL/ES.
PixelUnpackBuffer Pixel unpack buffer object for writing pixel data to the GL server (for example, with glTexImage2D()). Not supported under OpenGL/ES.
Enumerator
VertexBuffer
IndexBuffer
PixelPackBuffer
PixelUnpackBuffer
Definition at line 59 of file qglbuffer.h.
     {
         VertexBuffer        = 0x8892, // GL_ARRAY_BUFFER
         IndexBuffer         = 0x8893, // GL_ELEMENT_ARRAY_BUFFER
         PixelPackBuffer     = 0x88EB, // GL_PIXEL_PACK_BUFFER
         PixelUnpackBuffer   = 0x88EC  // GL_PIXEL_UNPACK_BUFFER
     };
UsagePattern
enum QGLBuffer::UsagePattern
This enum defines the usage pattern of a QGLBuffer object.
StreamDraw The data will be set once and used a few times for drawing operations. Under OpenGL/ES 1.1 this is identical to StaticDraw.
StreamRead The data will be set once and used a few times for reading data back from the GL server. Not supported under OpenGL/ES.
StreamCopy The data will be set once and used a few times for reading data back from the GL server for use in further drawing operations. Not supported under OpenGL/ES.
StaticDraw The data will be set once and used many times for drawing operations.
StaticRead The data will be set once and used many times for reading data back from the GL server. Not supported under OpenGL/ES.
StaticCopy The data will be set once and used many times for reading data back from the GL server for use in further drawing operations. Not supported under OpenGL/ES.
DynamicDraw The data will be modified repeatedly and used many times for drawing operations.
DynamicRead The data will be modified repeatedly and used many times for reading data back from the GL server. Not supported under OpenGL/ES.
DynamicCopy The data will be modified repeatedly and used many times for reading data back from the GL server for use in further drawing operations. Not supported under OpenGL/ES.
Enumerator
StreamDraw
StreamRead
StreamCopy
StaticDraw
StaticRead
StaticCopy
DynamicDraw
DynamicRead
DynamicCopy
Definition at line 74 of file qglbuffer.h.
     {
         StreamDraw          = 0x88E0, // GL_STREAM_DRAW
         StreamRead          = 0x88E1, // GL_STREAM_READ
         StreamCopy          = 0x88E2, // GL_STREAM_COPY
         StaticDraw          = 0x88E4, // GL_STATIC_DRAW
         StaticRead          = 0x88E5, // GL_STATIC_READ
         StaticCopy          = 0x88E6, // GL_STATIC_COPY
         DynamicDraw         = 0x88E8, // GL_DYNAMIC_DRAW
         DynamicRead         = 0x88E9, // GL_DYNAMIC_READ
         DynamicCopy         = 0x88EA  // GL_DYNAMIC_COPY
     };
Constructors and Destructors
QGLBuffer() [1/3]
QGLBuffer::QGLBuffer ()
Constructs a new buffer object of type QGLBuffer::VertexBuffer.
Note: this constructor just creates the QGLBuffer instance. The actual buffer object in the GL server is not created until create() is called.
See also
create()
Definition at line 169 of file qglbuffer.cpp.
     : d_ptr(new QGLBufferPrivate(QGLBuffer::VertexBuffer))
 {
 }
QGLBuffer() [2/3]
QGLBuffer::QGLBuffer (QGLBuffer::Type type) explicit
Constructs a new buffer object of type.
Note: this constructor just creates the QGLBuffer instance. The actual buffer object in the GL server is not created until create() is called.
See also
create()
Definition at line 182 of file qglbuffer.cpp.
     : d_ptr(new QGLBufferPrivate(type))
 {
 }
QGLBuffer() [3/3]
QGLBuffer::QGLBuffer (const QGLBuffer & other)
Constructs a shallow copy of other.
Note: QGLBuffer does not implement copy-on-write semantics, so other will be affected whenever the copy is modified.
Definition at line 193 of file qglbuffer.cpp.
     : d_ptr(other.d_ptr)
 {
     d_ptr->ref.ref();
 }
~QGLBuffer()
QGLBuffer::~QGLBuffer ()
Destroys this buffer object, including the storage being used in the GL server.
Definition at line 205 of file qglbuffer.cpp.
 {
     if (!d_ptr->ref.deref()) {
         destroy();
         delete d_ptr;
     }
 }
Functions
allocate() [1/2]
void QGLBuffer::allocate (const void * data, int count)
Allocates count bytes of space to the buffer, initialized to the contents of data.
Any previous contents will be removed.
It is assumed that create() has been called on this buffer and that it has been bound to the current context.
See also
create(), read(), write()
Definition at line 398 of file qglbuffer.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (!isCreated())
         qWarning("QGLBuffer::allocate(): buffer not created");
 #endif
     Q_D(QGLBuffer);
     if (d->guard.id())
         glBufferData(d->type, count, data, d->actualUsagePattern);
 }
allocate() [2/2]
void QGLBuffer::allocate (int count) inline
Allocates count bytes of space to the buffer.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Any previous contents will be removed.
It is assumed that create() has been called on this buffer and that it has been bound to the current context.
See also
create(), write()
Definition at line 117 of file qglbuffer.h.
Referenced by allocate().
 { allocate(0, count); }
bind()
bool QGLBuffer::bind ()
Binds the buffer associated with this object to the current GL context.
Returns false if binding was not possible, usually because type() is not supported on this GL implementation.
The buffer must be bound to the same QGLContext current when create() was called, or to another QGLContext that is sharing with it. Otherwise, false will be returned from this function.
See also
release(), create()
Definition at line 436 of file qglbuffer.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (!isCreated())
         qWarning("QGLBuffer::bind(): buffer not created");
 #endif
     Q_D(const QGLBuffer);
     GLuint bufferId = d->guard.id();
     if (bufferId) {
         if (!QGLContext::areSharing(QGLContext::currentContext(),
                                     d->guard.context())) {
 #ifndef QT_NO_DEBUG
             qWarning("QGLBuffer::bind: buffer is not valid in the current context");
 #endif
             return false;
         }
         glBindBuffer(d->type, bufferId);
         return true;
     } else {
         return false;
     }
 }
bufferId()
GLuint QGLBuffer::bufferId () const
Returns the GL identifier associated with this buffer; zero if the buffer has not been created.
See also
isCreated()
Definition at line 509 of file qglbuffer.cpp.
Referenced by bind(), create(), and destroy().
 {
     Q_D(const QGLBuffer);
     return d->guard.id();
 }
create()
bool QGLBuffer::create ()
Creates the buffer object in the GL server.
Returns true if the object was created; false otherwise.
This function must be called with a current QGLContext. The buffer will be bound to and can only be used in that context (or any other context that is shared with it).
This function will return false if the GL implementation does not support buffers, or there is no current QGLContext.
See also
isCreated(), allocate(), write(), destroy()
Definition at line 290 of file qglbuffer.cpp.
 {
     Q_D(QGLBuffer);
     if (d->guard.id())
         return true;
     const QGLContext *ctx = QGLContext::currentContext();
     if (ctx) {
         if (!qt_resolve_buffer_extensions(const_cast<QGLContext *>(ctx)))
             return false;
         GLuint bufferId = 0;
         glGenBuffers(1, &bufferId);
         if (bufferId) {
             d->guard.setContext(ctx);
             d->guard.setId(bufferId);
             return true;
         }
     }
     return false;
 }
destroy()
void QGLBuffer::destroy ()
Destroys this buffer object, including the storage being used in the GL server.
All references to the buffer will become invalid.
Definition at line 328 of file qglbuffer.cpp.
Referenced by operator=(), and ~QGLBuffer().
 {
     Q_D(QGLBuffer);
     GLuint bufferId = d->guard.id();
     if (bufferId) {
         // Switch to the original creating context to destroy it.
         QGLShareContextScope scope(d->guard.context());
         glDeleteBuffers(1, &bufferId);
     }
     d->guard.setId(0);
     d->guard.setContext(0);
 }
isCreated()
bool QGLBuffer::isCreated () const
Returns true if this buffer has been created; false otherwise.
See also
create(), destroy()
Definition at line 317 of file qglbuffer.cpp.
Referenced by allocate(), bind(), map(), release(), unmap(), and write().
 {
     Q_D(const QGLBuffer);
     return d->guard.id() != 0;
 }
map()
void * QGLBuffer::map (QGLBuffer::Access access)
Maps the contents of this buffer into the application's memory space and returns a pointer to it.
Returns null if memory mapping is not possible. The access parameter indicates the type of access to be performed.
It is assumed that create() has been called on this buffer and that it has been bound to the current context.
This function is only supported under OpenGL/ES if the GL_OES_mapbuffer extension is present.
See also
unmap(), create(), bind()
Definition at line 552 of file qglbuffer.cpp.
 {
     Q_D(QGLBuffer);
 #ifndef QT_NO_DEBUG
     if (!isCreated())
         qWarning("QGLBuffer::map(): buffer not created");
 #endif
     if (!d->guard.id())
         return 0;
     if (!glMapBufferARB)
         return 0;
 #ifdef QT_OPENGL_ES_2
     if (access != QGLBuffer::WriteOnly)
         return 0;
 #endif
     return glMapBufferARB(d->type, access);
 }
operator=()
QGLBuffer & QGLBuffer::operator= (const QGLBuffer & other)
Assigns a shallow copy of other to this object.
Note: QGLBuffer does not implement copy-on-write semantics, so other will be affected whenever the copy is modified.
Definition at line 219 of file qglbuffer.cpp.
 {
     if (d_ptr != other.d_ptr) {
         other.d_ptr->ref.ref();
         if (!d_ptr->ref.deref()) {
             destroy();
             delete d_ptr;
         }
         d_ptr = other.d_ptr;
     }
     return *this;
 }
read()
bool QGLBuffer::read (int offset, void * data, int count)
Reads the count bytes in this buffer starting at offset into data.
Returns true on success; false if reading from the buffer is not supported. Buffer reading is not supported under OpenGL/ES.
It is assumed that this buffer has been bound to the current context.
See also
write(), bind()
Definition at line 351 of file qglbuffer.cpp.
 {
 #if !defined(QT_OPENGL_ES)
     Q_D(QGLBuffer);
     if (!glGetBufferSubData || !d->guard.id())
         return false;
     while (glGetError() != GL_NO_ERROR) ; // Clear error state.
     glGetBufferSubData(d->type, offset, count, data);
     return glGetError() == GL_NO_ERROR;
 #else
     Q_UNUSED(offset);
     Q_UNUSED(data);
     Q_UNUSED(count);
     return false;
 #endif
 }
release() [1/2]
void QGLBuffer::release ()
Releases the buffer associated with this object from the current GL context.
This function must be called with the same QGLContext current as when bind() was called on the buffer.
See also
bind()
Definition at line 468 of file qglbuffer.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (!isCreated())
         qWarning("QGLBuffer::release(): buffer not created");
 #endif
     Q_D(const QGLBuffer);
     if (d->guard.id())
         glBindBuffer(d->type, 0);
 }
release() [2/2]
void QGLBuffer::release (QGLBuffer::Type type) static
Releases the buffer associated with type in the current QGLContext.
This function is a direct call to glBindBuffer(type, 0) for use when the caller does not know which QGLBuffer has been bound to the context but wants to make sure that it is released.
QGLBuffer::release(QGLBuffer::VertexBuffer);
Definition at line 494 of file qglbuffer.cpp.
 {
     const QGLContext *ctx = QGLContext::currentContext();
     if (ctx && qt_resolve_buffer_extensions(const_cast<QGLContext *>(ctx)))
         glBindBuffer(GLenum(type), 0);
 }
setUsagePattern()
void QGLBuffer::setUsagePattern (QGLBuffer::UsagePattern value)
Sets the usage pattern for this buffer object to value.
This function must be called before allocate() or write().
See also
usagePattern(), allocate(), write()
Definition at line 259 of file qglbuffer.cpp.
 {
     Q_D(QGLBuffer);
 #if defined(QT_OPENGL_ES_1)
     // OpenGL/ES 1.1 does not support GL_STREAM_DRAW, so use GL_STATIC_DRAW.
     // OpenGL/ES 2.0 does support GL_STREAM_DRAW.
     d->usagePattern = value;
     if (value == StreamDraw)
         d->actualUsagePattern = StaticDraw;
     else
         d->actualUsagePattern = value;
 #else
     d->usagePattern = d->actualUsagePattern = value;
 #endif
 }
size()
int QGLBuffer::size () const
Returns the size of the data in this buffer, for reading operations.
Returns -1 if fetching the buffer size is not supported, or the buffer has not been created.
It is assumed that this buffer has been bound to the current context.
See also
isCreated(), bind()
Definition at line 528 of file qglbuffer.cpp.
 {
     Q_D(const QGLBuffer);
     if (!d->guard.id())
         return -1;
     GLint value = -1;
     glGetBufferParameteriv(d->type, GL_BUFFER_SIZE, &value);
     return value;
 }
type()
QGLBuffer::Type QGLBuffer::type () const
Returns the type of buffer represented by this object.
Definition at line 235 of file qglbuffer.cpp.
 {
     Q_D(const QGLBuffer);
     return d->type;
 }
unmap()
bool QGLBuffer::unmap ()
Unmaps the buffer after it was mapped into the application's memory space with a previous call to map().
Returns true if the unmap succeeded; false otherwise.
It is assumed that this buffer has been bound to the current context, and that it was previously mapped with map().
This function is only supported under OpenGL/ES if the GL_OES_mapbuffer extension is present.
See also
map()
Definition at line 583 of file qglbuffer.cpp.
 {
     Q_D(QGLBuffer);
 #ifndef QT_NO_DEBUG
     if (!isCreated())
         qWarning("QGLBuffer::unmap(): buffer not created");
 #endif
     if (!d->guard.id())
         return false;
     if (!glUnmapBufferARB)
         return false;
     return glUnmapBufferARB(d->type) == GL_TRUE;
 }
usagePattern()
QGLBuffer::UsagePattern QGLBuffer::usagePattern () const
Returns the usage pattern for this buffer object.
The default value is StaticDraw.
See also
setUsagePattern()
Definition at line 247 of file qglbuffer.cpp.
 {
     Q_D(const QGLBuffer);
     return d->usagePattern;
 }
write()
void QGLBuffer::write (int offset, const void * data, int count)
Replaces the count bytes of this buffer starting at offset with the contents of data.
Any other bytes in the buffer will be left unmodified.
It is assumed that create() has been called on this buffer and that it has been bound to the current context.
See also
create(), read(), allocate()
Definition at line 378 of file qglbuffer.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (!isCreated())
         qWarning("QGLBuffer::allocate(): buffer not created");
 #endif
     Q_D(QGLBuffer);
     if (d->guard.id())
         glBufferSubData(d->type, offset, count, data);
 }
Properties
d_ptr
QGLBufferPrivate* QGLBuffer::d_ptr private
Definition at line 123 of file qglbuffer.h.
Referenced by operator=(), QGLBuffer(), and ~QGLBuffer().
The documentation for this class was generated from the following files:
/src/opengl/qglbuffer.h
/src/opengl/qglbuffer.cpp