Qt 4.8: QPen Class Reference
QPen Class Reference
The QPen class defines how a QPainter should draw lines and outlines of shapes.
#include <qpen.h>
Public Types
typedef QPenPrivate * DataPtr
Public Functions
QBrush brush () const
Returns the brush used to fill strokes generated with this pen.
Qt::PenCapStyle capStyle () const
Returns the pen's cap style.
QColor color () const
Returns the color of this pen's brush.
qreal dashOffset () const
Returns the dash offset for the pen.
QVector< qreal > dashPattern () const
Returns the dash pattern of this pen.
DataPtr & data_ptr ()
bool isCosmetic () const
Returns true if the pen is cosmetic; otherwise returns false.
bool isDetached ()
bool isSolid () const
Returns true if the pen has a solid fill, otherwise false.
Qt::PenJoinStyle joinStyle () const
Returns the pen's join style.
qreal miterLimit () const
Returns the miter limit of the pen.
operator QVariant () const
Returns the pen as a QVariant.
bool operator!= (const QPen &p) const
Returns true if the pen is different from the given pen; otherwise false.
QPen & operator= (const QPen &pen)
Assigns the given pen to this pen and returns a reference to this pen.
bool operator== (const QPen &p) const
Returns true if the pen is equal to the given pen; otherwise false.
QPen ()
Constructs a default black solid line pen with 0 width.
QPen (Qt::PenStyle)
Constructs a black pen with 0 width and the given style.
QPen (const QColor &color)
Constructs a solid line pen with 0 width and the given color.
QPen (const QBrush &brush, qreal width, Qt::PenStyle s=Qt::SolidLine, Qt::PenCapStyle c=Qt::SquareCap, Qt::PenJoinStyle j=Qt::BevelJoin)
Constructs a pen with the specified brush, width, pen style, cap style and join style.
QPen (const QPen &pen)
Constructs a pen that is a copy of the given pen.
void setBrush (const QBrush &brush)
Sets the brush used to fill strokes generated with this pen to the given brush.
void setCapStyle (Qt::PenCapStyle pcs)
Sets the pen's cap style to the given style.
void setColor (const QColor &color)
Sets the color of this pen's brush to the given color.
void setCosmetic (bool cosmetic)
Sets this pen to cosmetic or non-cosmetic, depending on the value of cosmetic.
void setDashOffset (qreal doffset)
Sets the dash offset (the starting point on the dash pattern) for this pen to the offset specified.
void setDashPattern (const QVector< qreal > &pattern)
Sets the dash pattern for this pen to the given pattern.
void setJoinStyle (Qt::PenJoinStyle pcs)
Sets the pen's join style to the given style.
void setMiterLimit (qreal limit)
Sets the miter limit of this pen to the given limit.
void setStyle (Qt::PenStyle)
Sets the pen style to the given style.
void setWidth (int width)
Sets the pen width to the given width in pixels with integer precision.
void setWidthF (qreal width)
Sets the pen width to the given width in pixels with floating point precision.
Qt::PenStyle style () const
Returns the pen style.
void swap (QPen &other)
Swaps pen other with this pen.
int width () const
Returns the pen width with integer precision.
qreal widthF () const
Returns the pen width with floating point precision.
~QPen ()
Destroys the pen.
Private Functions
void detach ()
Detaches from shared pen data to make sure that this pen is the only one referring the data.
Properties
class QPenPrivate * d
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QPen &)
Writes the given pen to the given stream and returns a reference to the stream.
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QPen &)
Reads a pen from the given stream into the given pen and returns a reference to the stream.
Detailed Description
The QPen class defines how a QPainter should draw lines and outlines of shapes.
A pen has a style(), width(), brush(), capStyle() and joinStyle().
The pen style defines the line type. The brush is used to fill strokes generated with the pen. Use the QBrush class to specify fill styles. The cap style determines the line end caps that can be drawn using QPainter, while the join style describes how joins between two lines are drawn. The pen width can be specified in both integer (width()) and floating point (widthF()) precision. A line width of zero indicates a cosmetic pen. This means that the pen width is always drawn one pixel wide, independent of the transformation set on the painter.
The various settings can easily be modified using the corresponding setStyle(), setWidth(), setBrush(), setCapStyle() and setJoinStyle() functions (note that the painter's pen must be reset when altering the pen's properties).
For example:
QPainter painter(this);
QPen pen(Qt::green, 3, Qt::DashDotLine, Qt::RoundCap, Qt::RoundJoin);
painter.setPen(pen);
which is equivalent to
QPainter painter(this);
QPen pen;  // creates a default pen
pen.setStyle(Qt::DashDotLine);
pen.setWidth(3);
pen.setBrush(Qt::green);
pen.setCapStyle(Qt::RoundCap);
pen.setJoinStyle(Qt::RoundJoin);
painter.setPen(pen);
The default pen is a solid black brush with 0 width, square cap style (Qt::SquareCap), and bevel join style (Qt::BevelJoin).
In addition QPen provides the color() and setColor() convenience functions to extract and set the color of the pen's brush, respectively. Pens may also be compared and streamed.
For more information about painting in general, see the Paint System documentation.
Pen Style
Qt provides several built-in styles represented by the Qt::PenStyle enum:
Qt::SolidLine Qt::DashLine Qt::DotLine
Qt::DashDotLine Qt::DashDotDotLine Qt::CustomDashLine
Simply use the setStyle() function to convert the pen style to either of the built-in styles, except the Qt::CustomDashLine style which we will come back to shortly. Setting the style to Qt::NoPen tells the painter to not draw lines or outlines. The default pen style is Qt::SolidLine.
Since Qt 4.1 it is also possible to specify a custom dash pattern using the setDashPattern() function which implicitly converts the style of the pen to Qt::CustomDashLine. The pattern argument, a QVector, must be specified as an even number of qreal entries where the entries 1, 3, 5... are the dashes and 2, 4, 6... are the spaces. For example, the custom pattern shown above is created using the following code:
QPen pen;
QVector<qreal> dashes;
qreal space = 4;
dashes << 1 << space << 3 << space << 9 << space
           << 27 << space << 9 << space;
pen.setDashPattern(dashes);
Note that the dash pattern is specified in units of the pens width, e.g. a dash of length 5 in width 10 is 50 pixels long.
The currently set dash pattern can be retrieved using the dashPattern() function. Use the isSolid() function to determine whether the pen has a solid fill, or not.
Cap Style
The cap style defines how the end points of lines are drawn using QPainter. The cap style only apply to wide lines, i.e. when the width is 1 or greater. The Qt::PenCapStyle enum provides the following styles:
Qt::SquareCap Qt::FlatCap Qt::RoundCap
The Qt::SquareCap style is a square line end that covers the end point and extends beyond it by half the line width. The Qt::FlatCap style is a square line end that does not cover the end point of the line. And the Qt::RoundCap style is a rounded line end covering the end point.
The default is Qt::SquareCap.
Whether or not end points are drawn when the pen width is 0 or 1 depends on the cap style. Using Qt::SquareCap or Qt::RoundCap they are drawn, using Qt::FlatCap they are not drawn.
Join Style
The join style defines how joins between two connected lines can be drawn using QPainter. The join style only apply to wide lines, i.e. when the width is 1 or greater. The Qt::PenJoinStyle enum provides the following styles:
Qt::BevelJoin Qt::MiterJoin Qt::RoundJoin
The Qt::BevelJoin style fills the triangular notch between the two lines. The Qt::MiterJoin style extends the lines to meet at an angle. And the Qt::RoundJoin style fills a circular arc between the two lines.
The default is Qt::BevelJoin.
When the Qt::MiterJoin style is applied, it is possible to use the setMiterLimit() function to specify how far the miter join can extend from the join point. The miterLimit() is used to reduce artifacts between line joins where the lines are close to parallel.
The miterLimit() must be specified in units of the pens width, e.g. a miter limit of 5 in width 10 is 50 pixels long. The default miter limit is 2, i.e. twice the pen width in pixels.
demos/pathstroke{The Path Stroking Demo}
The Path Stroking demo shows Qt's built-in dash patterns and shows how custom patterns can be used to extend the range of available patterns.
See also
QPainter, QBrush, {demos/pathstroke}{Path Stroking Demo}, {Scribble Example}
Definition at line 64 of file qpen.h.
Typedefs
DataPtr
QPen::DataPtr
Warning
This function is not part of the public interface.
Definition at line 131 of file qpen.h.
Constructors and Destructors
QPen() [1/5]
qpen_default_join QPen::QPen ()
Constructs a default black solid line pen with 0 width.
Definition at line 279 of file qpen.cpp.
 {
     d = defaultPenInstance();
     d->ref.ref();
 }
QPen() [2/5]
QPen::QPen (Qt::PenStyle style)
Constructs a black pen with 0 width and the given style.
See also
setStyle()
Definition at line 291 of file qpen.cpp.
 {
     if (style == Qt::NoPen) {
         d = nullPenInstance();
         d->ref.ref();
     } else {
         d = new QPenData(Qt::black, 0, style, qpen_default_cap, qpen_default_join);
     }
 }
QPen() [3/5]
QPen::QPen (const QColor & color)
Constructs a solid line pen with 0 width and the given color.
See also
setBrush(), setColor()
Definition at line 308 of file qpen.cpp.
 {
     d = new QPenData(color, 0, Qt::SolidLine, qpen_default_cap, qpen_default_join);
 }
QPen() [4/5]
QPen::QPen (const QBrush & brush, qreal width, Qt::PenStyle style = Qt::SolidLine, Qt::PenCapStyle cap = Qt::SquareCap, Qt::PenJoinStyle join = Qt::BevelJoin)
Constructs a pen with the specified brush, width, pen style, cap style and join style.
See also
setBrush(), setWidth(), setStyle(), setCapStyle(), setJoinStyle()
Definition at line 326 of file qpen.cpp.
 {
     d = new QPenData(brush, width, s, c, j);
 }
QPen() [5/5]
QPen::QPen (const QPen & pen)
Constructs a pen that is a copy of the given pen.
Definition at line 340 of file qpen.cpp.
 {
     d = p.d;
     d->ref.ref();
 }
~QPen()
QPen::~QPen ()
Destroys the pen.
Definition at line 351 of file qpen.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
brush()
QBrush QPen::brush () const
Returns the brush used to fill strokes generated with this pen.
Definition at line 797 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QRasterPaintEngine::begin(), QTextLine::draw(), QVGPaintEngine::drawCachedGlyphs(), QTextLayout::drawCursor(), QOpenGLPaintEnginePrivate::drawFastRect(), QPaintEngine::drawPoints(), QPaintEngineEx::drawPoints(), QPainterPrivate::drawStretchedGradient(), QEmulationPaintEngine::drawTextItem(), QWin32PrintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), QPaintEngine::drawTextItem(), QVGPaintEnginePrivate::ensurePen(), is_pen_transparent(), operator<<(), QVGPaintEngine::penChanged(), QPaintEngineState::penNeedsResolving(), QDirectFBPaintEnginePrivate::setPen(), QPainter::setPen(), QEmulationPaintEngine::stroke(), QVGPaintEngine::stroke(), QPaintEngineEx::stroke(), QOpenGLPaintEnginePrivate::strokeLines(), QOpenGLPaintEnginePrivate::strokePath(), QOpenGLPaintEnginePrivate::strokePathFastPen(), QSvgNode::strokeWidth(), QPainterPrivate::updateEmulationSpecifier(), QOpenGLPaintEngine::updatePen(), QRasterPaintEngine::updatePen(), and QOpenGLPaintEnginePrivate::updateUseEmulation().
 {
     return d->brush;
 }
capStyle()
Qt::PenCapStyle QPen::capStyle () const
Returns the pen's cap style.
See also
setCapStyle(), {QPen::Cap Style}{Cap Style}
Definition at line 706 of file qpen.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QSvgStrokeStyle::apply(), QPainterPrivate::draw_helper(), QPaintEngine::drawLines(), QVGPaintEngine::drawPoints(), QPaintEngine::drawPoints(), QPaintEngineEx::drawPoints(), QPainter::drawPoints(), QPainterPrivate::drawStretchedGradient(), operator<<(), QSvgPaintEngine::qpenToSvg(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), QPdf::Stroker::setPen(), QPainter::setPen(), QVGPaintEnginePrivate::setPenParams(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), strokeForPath(), and QX11PaintEngine::updatePen().
 {
     return d->capStyle;
 }
color()
QColor QPen::color () const
Returns the color of this pen's brush.
See also
brush(), setColor()
Definition at line 771 of file qpen.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QDeclarativeTextLayout::draw(), QMacStyle::drawControl(), QDirectFBPaintEngine::drawLines(), QRasterPaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPoints(), QDirectFBPaintEngine::drawRects(), QPainter::drawStaticText(), QPaintEngineEx::drawStaticTextItem(), drawTextItemDecoration(), QGL2PaintEngineExPrivate::drawTexture(), QVGPaintEngine::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), generateWavyPixmap(), QStaticTextPrivate::get(), hash(), operator<<(), QStaticTextPrivate::paintText(), QSvgPaintEngine::qpenToSvg(), qt_render_bitmap(), QPainter::setPen(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QPicturePaintEngine::updatePen(), QX11PaintEngine::updatePen(), and QOpenGLPaintEngine::updatePen().
 {
     return d->brush.color();
 }
dashOffset()
qreal QPen::dashOffset () const
Returns the dash offset for the pen.
See also
setDashOffset()
Definition at line 547 of file qpen.cpp.
Referenced by operator<<(), QDashedStrokeProcessor::process(), QSvgPaintEngine::qpenToSvg(), QPdf::Stroker::setPen(), QVGPaintEnginePrivate::setPenParams(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), strokeForPath(), and QRasterPaintEngine::updatePen().
 {
     QPenData *dd = static_cast<QPenData *>(d);
     return dd->dashOffset;
 }
dashPattern()
QVector< qreal > QPen::dashPattern () const
Returns the dash pattern of this pen.
See also
style(), isSolid()
Definition at line 466 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QPdf::generateDashes(), operator<<(), QDashedStrokeProcessor::process(), QSvgPaintEngine::qpenToSvg(), QRasterPaintEnginePrivate::rasterizeLine_dashed(), QPdf::Stroker::setPen(), QVGPaintEnginePrivate::setPenParams(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), strokeForPath(), and QRasterPaintEngine::updatePen().
 {
     QPenData *dd = static_cast<QPenData *>(d);
     if (d->style == Qt::SolidLine || d->style == Qt::NoPen) {
         return QVector<qreal>();
     } else if (dd->dashPattern.isEmpty()) {
         const qreal space = 2;
         const qreal dot = 1;
         const qreal dash = 4;
         switch (d->style) {
         case Qt::DashLine:
             dd->dashPattern << dash << space;
             break;
         case Qt::DotLine:
             dd->dashPattern << dot << space;
             break;
         case Qt::DashDotLine:
             dd->dashPattern << dash << space << dot << space;
             break;
         case Qt::DashDotDotLine:
             dd->dashPattern << dash << space << dot << space << dot << space;
             break;
         default:
             break;
         }
     }
     return dd->dashPattern;
 }
data_ptr()
DataPtr & QPen::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 132 of file qpen.h.
 { return d; }
detach()
void QPen::detach () private
Detaches from shared pen data to make sure that this pen is the only one referring the data.
If multiple pens share common data, this pen dereferences the data and gets a copy of the data. Nothing is done if there is just a single reference.
Definition at line 370 of file qpen.cpp.
Referenced by operator>>().
 {
     if (d->ref == 1)
         return;
     QPenData *x = new QPenData(*static_cast<QPenData *>(d));
     if (!d->ref.deref())
         delete d;
     x->ref = 1;
     d = x;
 }
isCosmetic()
bool QPen::isCosmetic () const
Returns true if the pen is cosmetic; otherwise returns false.
Cosmetic pens are used to draw strokes that have a constant width regardless of any transformations applied to the QPainter they are used with. Drawing a shape with a cosmetic pen ensures that its outline will have the same thickness at different scale factors.
A zero width pen is cosmetic by default; pens with a non-zero width are non-cosmetic.
See also
setCosmetic(), widthF()
Definition at line 840 of file qpen.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QPaintEngine::drawPoints(), QPaintBufferEngine::penChanged(), QTriangulatingStroker::process(), QDashedStrokeProcessor::process(), QDirectFBPaintEnginePrivate::setPen(), QPdf::Stroker::setPen(), QVGPaintEnginePrivate::setPenParams(), QGL2PaintEngineEx::stroke(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), QGL2PaintEngineExPrivate::stroke(), QOpenGLPaintEnginePrivate::strokePath(), QSvgNode::strokeWidth(), QOpenGLPaintEngine::updatePen(), and QRasterPaintEngine::updatePen().
 {
     QPenData *dd = static_cast<QPenData *>(d);
     return (dd->cosmetic == true) || d->width == 0;
 }
isDetached()
bool QPen::isDetached ()
Warning
This function is not part of the public interface.
Definition at line 913 of file qpen.cpp.
 {
     return d->ref == 1;
 }
isSolid()
bool QPen::isSolid () const
Returns true if the pen has a solid fill, otherwise false.
See also
style(), dashPattern()
Definition at line 820 of file qpen.cpp.
Referenced by QPainterPrivate::updateEmulationSpecifier().
 {
     return d->brush.style() == Qt::SolidPattern;
 }
joinStyle()
Qt::PenJoinStyle QPen::joinStyle () const
Returns the pen's join style.
See also
setJoinStyle(), {QPen::Join Style}{Join Style}
Definition at line 736 of file qpen.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QSvgStrokeStyle::apply(), QPainterPrivate::draw_helper(), QPainterPrivate::drawStretchedGradient(), operator<<(), QSvgPaintEngine::qpenToSvg(), QPdf::Stroker::setPen(), QPainter::setPen(), QVGPaintEnginePrivate::setPenParams(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QPaintEngineEx::stroke(), QGL2PaintEngineExPrivate::stroke(), strokeForPath(), and QX11PaintEngine::updatePen().
 {
     return d->joinStyle;
 }
miterLimit()
qreal QPen::miterLimit () const
Returns the miter limit of the pen.
The miter limit is only relevant when the join style is set to Qt::MiterJoin.
See also
setMiterLimit(), {QPen::Join Style}{Join Style}
Definition at line 589 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QPainterPrivate::drawStretchedGradient(), operator<<(), QTriangulatingStroker::process(), QDashedStrokeProcessor::process(), QSvgPaintEngine::qpenToSvg(), QPdf::Stroker::setPen(), QVGPaintEnginePrivate::setPenParams(), QPaintEngineEx::stroke(), QGL2PaintEngineExPrivate::stroke(), strokeForPath(), and QRasterPaintEngine::updatePen().
 {
     const QPenData *dd = static_cast<QPenData *>(d);
     return dd->miterLimit;
 }
operator QVariant()
QPen::operator QVariant () const
Returns the pen as a QVariant.
Definition at line 413 of file qpen.cpp.
 {
     return QVariant(QVariant::Pen, this);
 }
operator!=()
bool QPen::operator!= (const QPen & pen) const inline
Returns true if the pen is different from the given pen; otherwise false.
Two pens are different if they have different styles, widths or colors.
See also
operator==()
Definition at line 119 of file qpen.h.
 { return !(operator==(p)); }
operator=()
QPen & QPen::operator= (const QPen & pen)
Assigns the given pen to this pen and returns a reference to this pen.
Definition at line 393 of file qpen.cpp.
 {
     qAtomicAssign(d, p.d);
     return *this;
 }
operator==()
bool QPen::operator== (const QPen & pen) const
Returns true if the pen is equal to the given pen; otherwise false.
Two pens are equal if they have equal styles, widths and colors.
See also
operator!=()
Definition at line 889 of file qpen.cpp.
 {
     QPenData *dd = static_cast<QPenData *>(d);
     QPenData *pdd = static_cast<QPenData *>(p.d);
     return (p.d == d)
         || (p.d->style == d->style
             && p.d->capStyle == d->capStyle
             && p.d->joinStyle == d->joinStyle
             && p.d->width == d->width
             && pdd->miterLimit == dd->miterLimit
             && (d->style != Qt::CustomDashLine
                 || (qFuzzyCompare(pdd->dashOffset, dd->dashOffset) &&
                     pdd->dashPattern == dd->dashPattern))
             && p.d->brush == d->brush
             && pdd->cosmetic == dd->cosmetic);
 }
setBrush()
void QPen::setBrush (const QBrush & brush)
Sets the brush used to fill strokes generated with this pen to the given brush.
See also
brush(), setColor()
Definition at line 808 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QPainterPrivate::drawStretchedGradient(), QEmulationPaintEngine::drawTextItem(), QGraphicsSimpleTextItem::paint(), and QEmulationPaintEngine::stroke().
 {
     detach();
     d->brush = brush;
 }
setCapStyle()
void QPen::setCapStyle (Qt::PenCapStyle style)
Sets the pen's cap style to the given style.
The default value is Qt::SquareCap.
See also
capStyle(), {QPen::Cap Style}{Cap Style}
Definition at line 723 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QWindowsMobileStyle::drawComplexControl(), QWindowsMobileStyle::drawControl(), QVGPaintEngine::drawPoints(), QPaintEngineEx::drawPoints(), QPainter::drawPoints(), QWindowsMobileStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawTabBarTab(), drawTabCloseButton(), drawTextItemDecoration(), generateWavyPixmap(), and qDrawRoundedCorners().
 {
     if (d->capStyle == c)
         return;
     detach();
     d->capStyle = c;
 }
setColor()
void QPen::setColor (const QColor & color)
Sets the color of this pen's brush to the given color.
See also
setBrush(), color()
Definition at line 787 of file qpen.cpp.
Referenced by QSvgAnimateColor::apply(), QmlJSDebugger::BoundingBoxPolygonItem::BoundingBoxPolygonItem(), drawTabCloseButton(), and drawTextItemDecoration().
 {
     detach();
     d->brush = QBrush(c);
 }
setCosmetic()
void QPen::setCosmetic (bool cosmetic)
Sets this pen to cosmetic or non-cosmetic, depending on the value of cosmetic.
See also
isCosmetic()
Definition at line 854 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), and QPainterPrivate::updateState().
 {
     detach();
     QPenData *dd = static_cast<QPenData *>(d);
     dd->cosmetic = cosmetic;
 }
setDashOffset()
void QPen::setDashOffset (qreal offset)
Sets the dash offset (the starting point on the dash pattern) for this pen to the offset specified.
The offset is measured in terms of the units used to specify the dash pattern.
For example, a pattern where each stroke is four units long, followed by a gap of two units, will begin with the stroke when drawn as a line.
However, if the dash offset is set to 4.0, any line drawn will begin with the gap. Values of the offset up to 4.0 will cause part of the stroke to be drawn first, and values of the offset between 4.0 and 6.0 will cause the line to begin with part of the gap.
Note
This implicitly converts the style of the pen to Qt::CustomDashLine.
Definition at line 570 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply().
 {
     if (qFuzzyCompare(offset, static_cast<QPenData *>(d)->dashOffset))
         return;
     detach();
     QPenData *dd = static_cast<QPenData *>(d);
     dd->dashOffset = offset;
     if (d->style != Qt::CustomDashLine) {
         dd->dashPattern = dashPattern();
         d->style = Qt::CustomDashLine;
     }
 }
setDashPattern()
void QPen::setDashPattern (const QVector< qreal > & pattern)
Sets the dash pattern for this pen to the given pattern.
This implicitly converts the style of the pen to Qt::CustomDashLine.
The pattern must be specified as an even number of positive entries where the entries 1, 3, 5... are the dashes and 2, 4, 6... are the spaces. For example:
QPen pen;
QVector<qreal> dashes;
qreal space = 4;
dashes << 1 << space << 3 << space << 9 << space
           << 27 << space << 9 << space;
pen.setDashPattern(dashes);
The dash pattern is specified in units of the pens width; e.g. a dash of length 5 in width 10 is 50 pixels long. Note that a pen with zero width is equivalent to a cosmetic pen with a width of 1 pixel.
Each dash is also subject to cap styles so a dash of 1 with square cap set will extend 0.5 pixels out in each direction resulting in a total width of 2.
Note that the default cap style is Qt::SquareCap, meaning that a square line end covers the end point and extends beyond it by half the line width.
See also
setStyle(), dashPattern(), setCapStyle(), setCosmetic()
Definition at line 525 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), and QSvgStrokeStyle::setDashArray().
 {
     if (pattern.isEmpty())
         return;
     detach();
     QPenData *dd = static_cast<QPenData *>(d);
     dd->dashPattern = pattern;
     d->style = Qt::CustomDashLine;
     if ((dd->dashPattern.size() % 2) == 1) {
         qWarning("QPen::setDashPattern: Pattern not of even length");
         dd->dashPattern << 1;
     }
 }
setJoinStyle()
void QPen::setJoinStyle (Qt::PenJoinStyle style)
Sets the pen's join style to the given style.
The default value is Qt::BevelJoin.
See also
joinStyle(), {QPen::Join Style}{Join Style}
Definition at line 753 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QDeclarativeRectangle::drawRect(), and QDeclarativeRectangle::generateBorderedRect().
 {
     if (d->joinStyle == j)
         return;
     detach();
     d->joinStyle = j;
 }
setMiterLimit()
void QPen::setMiterLimit (qreal limit)
Sets the miter limit of this pen to the given limit.
The miter limit describes how far a miter join can extend from the join point. This is used to reduce artifacts between line joins where the lines are close to parallel.
This value does only have effect when the pen style is set to Qt::MiterJoin. The value is specified in units of the pen's width, e.g. a miter limit of 5 in width 10 is 50 pixels long. The default miter limit is 2, i.e. twice the pen width in pixels.
See also
miterLimit(), setJoinStyle(), {QPen::Join Style}{Join Style}
Definition at line 611 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QSvgTinyDocument::draw(), QSvgHandler::init(), and QSvgNode::transformedBounds().
 {
     detach();
     QPenData *dd = static_cast<QPenData *>(d);
     dd->miterLimit = limit;
 }
setStyle()
void QPen::setStyle (Qt::PenStyle style)
Sets the pen style to the given style.
See the Qt::PenStyle documentation for a list of the available styles. Since Qt 4.1 it is also possible to specify a custom dash pattern using the setDashPattern() function which implicitly converts the style of the pen to Qt::CustomDashLine.
Note
This function resets the dash offset to zero.
See also
style(), {QPen::Pen Style}{Pen Style}
Definition at line 450 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), drawTextItemDecoration(), QEmulationPaintEngine::stroke(), and QRasterPaintEngine::updatePen().
 {
     if (d->style == s)
         return;
     detach();
     d->style = s;
     QPenData *dd = static_cast<QPenData *>(d);
     dd->dashPattern.clear();
     dd->dashOffset = 0;
 }
setWidth()
void QPen::setWidth (int width)
Sets the pen width to the given width in pixels with integer precision.
A line width of zero indicates a cosmetic pen. This means that the pen width is always drawn one pixel wide, independent of the transformation set on the painter.
Setting a pen width with a negative value is not supported.
See also
setWidthF(), width()
Definition at line 667 of file qpen.cpp.
Referenced by QmlJSDebugger::BoundingBoxPolygonItem::BoundingBoxPolygonItem(), QWindowsMobileStyle::drawComplexControl(), QCommonStyle::drawControl(), QWindowsMobileStyle::drawControl(), QMacStyle::drawControl(), QWindowsMobileStyle::drawPrimitive(), QWindowsMobileStylePrivate::drawTabBarTab(), generateWavyPixmap(), and QPainterPrivate::updateState().
 {
     if (width < 0)
         qWarning("QPen::setWidth: Setting a pen width with a negative value is not defined");
     if ((qreal)width == d->width)
         return;
     detach();
     d->width = width;
 }
setWidthF()
void QPen::setWidthF (qreal width)
Sets the pen width to the given width in pixels with floating point precision.
A line width of zero indicates a cosmetic pen. This means that the pen width is always drawn one pixel wide, independent of the transformation on the painter.
Setting a pen width with a negative value is not supported.
See also
setWidth() widthF()
Definition at line 690 of file qpen.cpp.
Referenced by QSvgStrokeStyle::apply(), QFontEngineBox::boundingBox(), QSvgFont::draw(), QPaintEnginePrivate::drawBoxTextItem(), drawTabCloseButton(), drawTextItemDecoration(), and QOpenGLPaintEnginePrivate::strokePath().
 {
     if (width < 0.f)
         qWarning("QPen::setWidthF: Setting a pen width with a negative value is not defined");
     if (qAbs(d->width - width) < 0.00000001f)
         return;
     detach();
     d->width = width;
 }
style()
Qt::PenStyle QPen::style () const
Returns the pen style.
See also
setStyle(), {QPen::Pen Style}{Pen Style}
Definition at line 428 of file qpen.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QSvgStrokeStyle::apply(), QTextLine::draw(), QPainterPrivate::draw_helper(), QDirectFBPaintEngine::drawLines(), QPainterPrivate::drawOpaqueBackground(), QDirectFBPaintEngine::drawPoints(), QVGPaintEngine::drawPoints(), QDirectFBPaintEngine::drawRects(), QPainter::drawStaticText(), QPainterPrivate::drawStretchedGradient(), QPainter::drawText(), QRasterPaintEngine::ensurePen(), is_pen_transparent(), operator<<(), QVGPaintEngine::penChanged(), QPaintBufferEngine::penChanged(), QSvgPaintEngine::qpenToSvg(), QPainterPrivate::rectSubtraction(), QDirectFBPaintEnginePrivate::setPen(), QPdf::Stroker::setPen(), QPainter::setPen(), QVGPaintEnginePrivate::setPenParams(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QEmulationPaintEngine::stroke(), QVGPaintEnginePrivate::stroke(), QPaintEngineEx::stroke(), strokeForPath(), QSvgNode::strokeWidth(), QPicturePaintEngine::updatePen(), QX11PaintEngine::updatePen(), and QOpenGLPaintEngine::updatePen().
 {
     return d->style;
 }
swap()
void QPen::swap (QPen & other) inline
Swaps pen other with this pen.
Since
4.8
This operation is very fast and never fails.
Definition at line 81 of file qpen.h.
 { qSwap(d, other.d); }
width()
int QPen::width () const
Returns the pen width with integer precision.
See also
setWidth(), widthF()
Definition at line 630 of file qpen.cpp.
Referenced by QPainterPrivate::drawOpaqueBackground(), operator<<(), QSvgPaintEngine::qpenToSvg(), QPainterPrivate::rectSubtraction(), QPicturePaintEngine::updatePen(), and QPicturePaintEngine::writeCmdLength().
 {
     return qRound(d->width);
 }
widthF()
qreal QPen::widthF () const
Returns the pen width with floating point precision.
See also
setWidthF() width()
Definition at line 645 of file qpen.cpp.
Referenced by QAlphaPaintEnginePrivate::addPenWidth(), QSvgStrokeStyle::apply(), QGraphicsPathItem::boundingRect(), QGraphicsRectItem::boundingRect(), QGraphicsEllipseItem::boundingRect(), QGraphicsPolygonItem::boundingRect(), QSvgArc::draw(), QSvgFont::draw(), QSvgLine::draw(), QSvgPolyline::draw(), QPainterPrivate::draw_helper(), QCleanlooksStyle::drawItemText(), QStyle::drawItemText(), QPaintEngine::drawPoints(), QPainterPrivate::drawStretchedGradient(), drawTextItemDecoration(), QPdf::generateDashes(), generateWavyPixmap(), QRasterPaintEnginePrivate::getPenFunc(), hash(), operator<<(), QPaintBufferEngine::penChanged(), QSvgPaintEngine::qpenToSvg(), QSvgStrokeStyle::setDashArray(), QDirectFBPaintEnginePrivate::setPen(), QPdf::Stroker::setPen(), QVGPaintEnginePrivate::setPenParams(), QCoreGraphicsPaintEnginePrivate::setStrokePen(), QPaintEngineEx::stroke(), strokeForPath(), QOpenGLPaintEnginePrivate::strokeLines(), QOpenGLPaintEnginePrivate::strokePath(), QSvgNode::strokeWidth(), QX11PaintEngine::updatePen(), QOpenGLPaintEngine::updatePen(), and QPainterPrivate::updateState().
 {
     return d->width;
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & stream, const QPen & pen) friend
Writes the given pen to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 936 of file qpen.cpp.
 {
     QPenData *dd = static_cast<QPenData *>(p.d);
     if (s.version() < 3) {
         s << (quint8)p.style();
     } else if (s.version() < QDataStream::Qt_4_3) {
         s << (quint8)(p.style() | p.capStyle() | p.joinStyle());
     } else {
         s << (quint16)(p.style() | p.capStyle() | p.joinStyle());
         s << (bool)(dd->cosmetic);
     }
     if (s.version() < 7) {
         s << (quint8)p.width();
         s << p.color();
     } else {
         s << double(p.widthF());
         s << p.brush();
         s << double(p.miterLimit());
         if (sizeof(qreal) == sizeof(double)) {
             s << p.dashPattern();
         } else {
             // ensure that we write doubles here instead of streaming the pattern
             // directly; otherwise, platforms that redefine qreal might generate
             // data that cannot be read on other platforms.
             QVector<qreal> pattern = p.dashPattern();
             s << quint32(pattern.size());
             for (int i = 0; i < pattern.size(); ++i)
                 s << double(pattern.at(i));
         }
         if (s.version() >= 9)
             s << double(p.dashOffset());
     }
     return s;
 }
operator>>
QDataStream & operator>> (QDataStream & stream, QPen & pen) friend
Reads a pen from the given stream into the given pen and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 985 of file qpen.cpp.
 {
     quint16 style;
     quint8 width8 = 0;
     double width = 0;
     QColor color;
     QBrush brush;
     double miterLimit = 2;
     QVector<qreal> dashPattern;
     double dashOffset = 0;
     bool cosmetic = false;
     if (s.version() < QDataStream::Qt_4_3) {
         quint8 style8;
         s >> style8;
         style = style8;
     } else {
         s >> style;
         s >> cosmetic;
     }
     if (s.version() < 7) {
         s >> width8;
         s >> color;
         brush = color;
         width = width8;
     } else {
         s >> width;
         s >> brush;
         s >> miterLimit;
         if (sizeof(qreal) == sizeof(double)) {
             s >> dashPattern;
         } else {
             quint32 numDashes;
             s >> numDashes;
             double dash;
             for (quint32 i = 0; i < numDashes; ++i) {
                 s >> dash;
                 dashPattern << dash;
             }
         }
         if (s.version() >= 9)
             s >> dashOffset;
     }
     p.detach();
     QPenData *dd = static_cast<QPenData *>(p.d);
     dd->width = width;
     dd->brush = brush;
     dd->style = Qt::PenStyle(style & Qt::MPenStyle);
     dd->capStyle = Qt::PenCapStyle(style & Qt::MPenCapStyle);
     dd->joinStyle = Qt::PenJoinStyle(style & Qt::MPenJoinStyle);
     dd->dashPattern = dashPattern;
     dd->miterLimit = miterLimit;
     dd->dashOffset = dashOffset;
     dd->cosmetic = cosmetic;
     return s;
 }
Properties
d
class QPenPrivate* QPen::d private
Definition at line 128 of file qpen.h.
Referenced by operator<<(), operator=(), operator==(), operator>>(), QPen(), and swap().
The documentation for this class was generated from the following files:
/src/gui/painting/qpen.h
/src/gui/painting/qpen.cpp