Qt 4.8: QPatternist::XsdSchemaContext Class Reference
QPatternist::XsdSchemaContext Class Reference
XML Schema Processing
A context for schema parsing and validation.
#include <qxsdschemacontext_p.h>
Public Types
typedef QExplicitlySharedDataPointer< XsdSchemaContext > Ptr
Public Types inherited from QPatternist::ReportContext
enum ErrorCode {
XSDError, XPST0001, XPDY0002, XPST0003,
XPTY0004, XPST0005, XPTY0006, XPTY0007,
XPST0008, XQST0009, XPST0010, XQST0012,
XQST0013, XQST0014, XQST0015, XQST0016,
XPST0017, XPTY0018, XPTY0019, XPTY0020,
XPDY0021, XQST0022, XQTY0023, XQTY0024,
XQDY0025, XQDY0026, XQDY0027, XQTY0028,
XQDY0029, XQTY0030, XQST0031, XQST0032,
XQST0033, XQST0034, XQST0035, XQST0036,
XQST0037, XQST0038, XQST0039, XQST0040,
XQDY0041, XQST0042, XQST0043, XQDY0044,
XQST0045, XQST0046, XQST0047, XQST0048,
XQST0049, XPDY0050, XPST0051, XQDY0052,
XQST0053, XQST0054, XQST0055, XQST0056,
XQST0057, XQST0058, XQST0059, XQST0060,
XQDY0061, XQDY0062, XQST0063, XQDY0064,
XQST0065, XQST0066, XQST0067, XQST0068,
XQST0069, XQST0070, XQST0071, XQDY0072,
XQST0073, XQDY0074, XQST0075, XQST0076,
XQST0077, XQST0078, XQST0079, XPST0080,
XPST0081, XQST0082, XPST0083, XQDY0084,
XQST0085, XQTY0086, XQST0087, XQST0088,
XQST0089, XQST0090, XQDY0091, XQDY0092,
XQST0093, FOER0000, FOAR0001, FOAR0002,
FOCA0001, FOCA0002, FOCA0003, FOCA0005,
FOCA0006, FOCH0001, FOCH0002, FOCH0003,
FOCH0004, FODC0001, FODC0002, FODC0003,
FODC0004, FODC0005, FODT0001, FODT0002,
FODT0003, FONS0004, FONS0005, FORG0001,
FORG0002, FORG0003, FORG0004, FORG0005,
FORG0006, FORG0008, FORG0009, FORX0001,
FORX0002, FORX0003, FORX0004, FOTY0012,
SENR0001, SERE0003, SEPM0004, SERE0005,
SERE0006, SESU0007, SERE0008, SEPM0009,
SEPM0010, SESU0011, SERE0012, SESU0013,
SERE0014, SERE0015, SEPM0016, XTSE0010,
XTSE0020, XTSE0080, XTSE0090, XTSE0110,
XTSE0120, XTSE0125, XTSE0130, XTSE0150,
XTSE0165, XTSE0170, XTSE0180, XTSE0190,
XTSE0200, XTSE0210, XTSE0215, XTSE0220,
XTSE0260, XTSE0265, XTSE0280, XTSE0340,
XTSE0350, XTSE0370, XTSE0500, XTSE0530,
XTSE0550, XTSE0580, XTSE0620, XTSE0630,
XTSE0650, XTSE0660, XTSE0670, XTSE0680,
XTSE0690, XTSE0710, XTSE0720, XTSE0740,
XTSE0760, XTSE0770, XTSE0805, XTSE0808,
XTSE0809, XTSE0810, XTSE0812, XTSE0840,
XTSE0870, XTSE0880, XTSE0910, XTSE0940,
XTTE0950, XTSE0975, XTSE1015, XTSE1017,
XTSE1040, XTSE1060, XTSE1070, XTSE1080,
XTSE1090, XTSE1130, XTSE1205, XTSE1210,
XTSE1220, XTSE1290, XTSE1295, XTSE1300,
XTSE1430, XTSE1505, XTSE1520, XTSE1530,
XTSE1560, XTSE1570, XTSE1580, XTSE1590,
XTSE1600, XTSE1650, XTSE1660, XTTE0505,
XTTE0510, XTTE0520, XTTE0570, XTTE0590,
XTTE0600, XTTE0780, XTTE0790, XTTE0990,
XTTE1000, XTTE1020, XTTE1100, XTTE1120,
XTTE1510, XTTE1512, XTTE1515, XTTE1540,
XTTE1545, XTTE1550, XTTE1555, XTDE0030,
XTDE0040, XTDE0045, XTDE0047, XTDE0050,
XTDE0060, XTDE0160, XTRE0270, XTDE0290,
XTDE0410, XTDE0420, XTDE0430, XTDE0440,
XTDE0485, XTRE0540, XTDE0560, XTDE0610,
XTDE0640, XTDE0700, XTRE0795, XTDE0820,
XTDE0830, XTDE0835, XTDE0850, XTDE0855,
XTDE0860, XTDE0865, XTDE0890, XTDE0905,
XTDE0920, XTDE0925, XTDE0930, XTDE0980,
XTDE1030, XTDE1035, XTDE1110, XTDE1140,
XTDE1145, XTDE1150, XTRE1160, XTDE1170,
XTDE1190, XTDE1200, XTDE1260, XTDE1270,
XTDE1280, XTDE1310, XTDE1340, XTDE1350,
XTDE1360, XTDE1370, XTDE1380, XTDE1390,
XTMM9000, XTDE1400, XTDE1420, XTDE1425,
XTDE1428, XTDE1440, XTDE1450, XTDE1460,
XTDE1480, XTDE1490, XTRE1495, XTRE1500,
XTRE1620, XTRE1630, XTDE1665
}
typedef QHash< const SourceLocationReflection *, QSourceLocation > LocationHash
typedef QExplicitlySharedDataPointer< ReportContext > Ptr
Public Functions
virtual QUrl baseURI () const
XsdFacet::Hash facetsForType (const AnySimpleType::Ptr &type) const
virtual QSourceLocation locationFor (const SourceLocationReflection *const reflection) const
virtual QAbstractMessageHandler * messageHandler () const
virtual NamePool::Ptr namePool () const
virtual QNetworkAccessManager * networkAccessManager () const
SchemaTypeFactory::Ptr schemaTypeFactory () const
virtual void setBaseURI (const QUrl &uri)
void setMessageHandler (QAbstractMessageHandler *handler)
void setNetworkAccessManager (QNetworkAccessManager *accessManager)
void setUriResolver (const QAbstractUriResolver *resolver)
virtual const QAbstractUriResolver * uriResolver () const
XsdSchemaContext (const NamePool::Ptr &namePool)
Public Functions inherited from QPatternist::ReportContext
void error (const QString &message, const ReportContext::ErrorCode errorCode, const QSourceLocation &sourceLocation)
void error (const QString &message, const ReportContext::ErrorCode errorCode, const SourceLocationReflection *const reflection)
void error (const QString &message, const QXmlName qName, const SourceLocationReflection *const r)
ReportContext ()
Default constructors.
QUrl resolveURI (const QUrl &relative, const QUrl &baseURI) const
void warning (const QString &message, const QSourceLocation &sourceLocation=QSourceLocation())
virtual ~ReportContext ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Variables
QHash< SchemaType::Ptr, XsdFacet::Hash > m_builtinTypesFacetList
SchemaTypeFactory::Ptr m_schemaTypeFactory
Public Variables inherited from QSharedData
QAtomicInt ref
Private Functions
QHash< SchemaType::Ptr, XsdFacet::Hash > setupBuiltinTypesFacetList () const
Properties
QUrl m_baseURI
QAbstractMessageHandler * m_messageHandler
NamePool::Ptr m_namePool
QNetworkAccessManager * m_networkAccessManager
const QAbstractUriResolver * m_uriResolver
Additional Inherited Members
Static Public Functions inherited from QPatternist::ReportContext
static QString codeFromURI (const QString &typeURI, QString &uri)
static QString codeToString (const ReportContext::ErrorCode errorCode)
Related Functions inherited from QPatternist::ReportContext
typedef bool Exception
This is the class type that is being thrown when a query error occur.
Detailed Description
A context for schema parsing and validation.
This class provides the infrastructure for error reporting and network access. Additionally it stores objects that are used by both, the parser and the validator.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 83 of file qxsdschemacontext_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdSchemaContext> QPatternist::XsdSchemaContext::Ptr
A smart pointer wrapping XsdSchemaContext instances.
Definition at line 89 of file qxsdschemacontext_p.h.
Constructors and Destructors
XsdSchemaContext()
XsdSchemaContext::XsdSchemaContext (const NamePool::Ptr & namePool)
Creates a new schema context object.
Parameters
namePool The name pool all names belong to.
Definition at line 52 of file qxsdschemacontext.cpp.
     : m_namePool(namePool)
     , m_networkAccessManager(0)
     , m_uriResolver(0)
     , m_messageHandler(0)
 {
 }
Functions
baseURI()
QUrl XsdSchemaContext::baseURI () const virtual
Returns the base URI of the main schema.
Definition at line 65 of file qxsdschemacontext.cpp.
 {
     return m_baseURI;
 }
facetsForType()
XsdFacet::Hash XsdSchemaContext::facetsForType (const AnySimpleType::Ptr & type) const
Returns the list of facets for the given simple type.
Definition at line 110 of file qxsdschemacontext.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), and QPatternist::XsdTypeChecker::mergedFacetsForType().
 {
     if (type->isDefinedBySchema())
         return XsdSimpleType::Ptr(type)->facets();
     else {
         if (m_builtinTypesFacetList.isEmpty())
             m_builtinTypesFacetList = setupBuiltinTypesFacetList();
         return m_builtinTypesFacetList.value(type);
     }
 }
locationFor()
QSourceLocation XsdSchemaContext::locationFor (const SourceLocationReflection *const reflection) const virtual
Always returns an empty source location.
Implements QPatternist::ReportContext.
Definition at line 95 of file qxsdschemacontext.cpp.
 {
     return QSourceLocation();
 }
messageHandler()
QAbstractMessageHandler * XsdSchemaContext::messageHandler () const virtual
Returns the message handler used by the context for error reporting.
Implements QPatternist::ReportContext.
Definition at line 90 of file qxsdschemacontext.cpp.
 {
     return m_messageHandler;
 }
namePool()
NamePool::Ptr XsdSchemaContext::namePool () const virtual
Returns the name pool of the schema context.
Implements QPatternist::ReportContext.
Definition at line 60 of file qxsdschemacontext.cpp.
Referenced by QPatternist::XsdInstanceReader::convertToQName(), QPatternist::XsdTypeChecker::convertToQName(), derivedTermValid(), QPatternist::XsdSchemaHelper::isValidAttributeUsesExtension(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), and QPatternist::XsdParticleChecker::subsumes().
 {
     return m_namePool;
 }
networkAccessManager()
QNetworkAccessManager * XsdSchemaContext::networkAccessManager () const virtual
Returns the network access manager that is used to access referenced schema definitions.
Definition at line 80 of file qxsdschemacontext.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::loadSchema(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), and QPatternist::XsdSchemaParser::parseRedefine().
 {
     return m_networkAccessManager;
 }
schemaTypeFactory()
SchemaTypeFactory::Ptr XsdSchemaContext::schemaTypeFactory () const
Returns a schema type factory that contains some predefined schema types.
Definition at line 122 of file qxsdschemacontext.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveAlternativeTypes(), QPatternist::XsdSchemaResolver::resolveAttributeTypes(), QPatternist::XsdSchemaResolver::resolveComplexBaseTypes(), QPatternist::XsdSchemaResolver::resolveElementTypes(), QPatternist::XsdSchemaResolver::resolveSimpleListType(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictionBaseTypes(), QPatternist::XsdSchemaResolver::resolveSimpleUnionTypes(), QPatternist::XsdValidatingInstanceReader::typeByName(), QPatternist::XsdSchemaResolver::XsdSchemaResolver(), and QPatternist::XsdValidatingInstanceReader::XsdValidatingInstanceReader().
 {
     if (!m_schemaTypeFactory)
         m_schemaTypeFactory = SchemaTypeFactory::Ptr(new XsdSchemaTypesFactory(m_namePool));
     return m_schemaTypeFactory;
 }
setBaseURI()
void XsdSchemaContext::setBaseURI (const QUrl & uri) virtual
Sets the base URI for the main schema.
The main schema is the one that includes resp. imports all the other schema files.
Definition at line 70 of file qxsdschemacontext.cpp.
 {
     m_baseURI = uri;
 }
setMessageHandler()
void XsdSchemaContext::setMessageHandler (QAbstractMessageHandler * handler)
Sets the message handler used by the context for error reporting.
Definition at line 85 of file qxsdschemacontext.cpp.
 {
     m_messageHandler = handler;
 }
setNetworkAccessManager()
void XsdSchemaContext::setNetworkAccessManager (QNetworkAccessManager * accessManager)
Sets the network access manager that should be used to access referenced schema definitions.
Definition at line 75 of file qxsdschemacontext.cpp.
 {
     m_networkAccessManager = accessManager;
 }
setupBuiltinTypesFacetList()
QHash< SchemaType::Ptr, XsdFacet::Hash > XsdSchemaContext::setupBuiltinTypesFacetList () const private
Definition at line 130 of file qxsdschemacontext.cpp.
Referenced by facetsForType().
 {
     QHash<SchemaType::Ptr, XsdFacet::Hash> hash;
     const XsdFacet::Ptr fixedCollapseWhiteSpace(new XsdFacet());
     fixedCollapseWhiteSpace->setType(XsdFacet::WhiteSpace);
     fixedCollapseWhiteSpace->setValue(DerivedString<TypeString>::fromLexical(m_namePool, XsdSchemaToken::toString(XsdSchemaToken::Collapse)));
     fixedCollapseWhiteSpace->setFixed(true);
     const XsdFacet::Ptr collapseWhiteSpace(new XsdFacet());
     collapseWhiteSpace->setType(XsdFacet::WhiteSpace);
     collapseWhiteSpace->setValue(DerivedString<TypeString>::fromLexical(m_namePool, XsdSchemaToken::toString(XsdSchemaToken::Collapse)));
     collapseWhiteSpace->setFixed(false);
     const XsdFacet::Ptr preserveWhiteSpace(new XsdFacet());
     preserveWhiteSpace->setType(XsdFacet::WhiteSpace);
     preserveWhiteSpace->setValue(DerivedString<TypeString>::fromLexical(m_namePool, XsdSchemaToken::toString(XsdSchemaToken::Preserve)));
     preserveWhiteSpace->setFixed(false);
     const XsdFacet::Ptr replaceWhiteSpace(new XsdFacet());
     replaceWhiteSpace->setType(XsdFacet::WhiteSpace);
     replaceWhiteSpace->setValue(DerivedString<TypeString>::fromLexical(m_namePool, XsdSchemaToken::toString(XsdSchemaToken::Replace)));
     replaceWhiteSpace->setFixed(false);
     const XsdFacet::Ptr fixedZeroFractionDigits(new XsdFacet());
     fixedZeroFractionDigits->setType(XsdFacet::FractionDigits);
     fixedZeroFractionDigits->setValue(DerivedInteger<TypeNonNegativeInteger>::fromValue(m_namePool, 0));
     fixedZeroFractionDigits->setFixed(true);
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsString];
         facets.insert(preserveWhiteSpace->type(), preserveWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsBoolean];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsDecimal];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsFloat];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsDouble];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsDuration];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsDateTime];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsTime];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsDate];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsGYearMonth];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsGYear];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsGMonthDay];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsGDay];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsGMonth];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsHexBinary];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsBase64Binary];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsAnyURI];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsQName];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNOTATION];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNormalizedString];
         facets.insert(replaceWhiteSpace->type(), replaceWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsToken];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsLanguage];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         const XsdFacet::Ptr pattern(new XsdFacet());
         pattern->setType(XsdFacet::Pattern);
         pattern->setMultiValue(AtomicValue::List() << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*")));
         facets.insert(pattern->type(), pattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNMTOKEN];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         const XsdFacet::Ptr pattern(new XsdFacet());
         pattern->setType(XsdFacet::Pattern);
         pattern->setMultiValue(AtomicValue::List() << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("\\c+")));
         facets.insert(pattern->type(), pattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsName];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         const XsdFacet::Ptr pattern(new XsdFacet());
         pattern->setType(XsdFacet::Pattern);
         pattern->setMultiValue(AtomicValue::List() << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("\\i\\c*")));
         facets.insert(pattern->type(), pattern);
     }
     const XsdFacet::Ptr ncNamePattern(new XsdFacet());
     {
         ncNamePattern->setType(XsdFacet::Pattern);
         AtomicValue::List patterns;
         patterns << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("\\i\\c*"));
         patterns << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("[\\i-[:]][\\c-[:]]*"));
         ncNamePattern->setMultiValue(patterns);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNCName];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         facets.insert(ncNamePattern->type(), ncNamePattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsID];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         facets.insert(ncNamePattern->type(), ncNamePattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsIDREF];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         facets.insert(ncNamePattern->type(), ncNamePattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsENTITY];
         facets.insert(collapseWhiteSpace->type(), collapseWhiteSpace);
         facets.insert(ncNamePattern->type(), ncNamePattern);
     }
     const XsdFacet::Ptr integerPattern(new XsdFacet());
     integerPattern->setType(XsdFacet::Pattern);
     integerPattern->setMultiValue(AtomicValue::List() << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("[\\-+]?[0-9]+")));
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsInteger];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNonPositiveInteger];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("0")));
         facets.insert(maxInclusive->type(), maxInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNegativeInteger];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("-1")));
         facets.insert(maxInclusive->type(), maxInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsLong];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("9223372036854775807")));
         facets.insert(maxInclusive->type(), maxInclusive);
         const XsdFacet::Ptr minInclusive(new XsdFacet());
         minInclusive->setType(XsdFacet::MinimumInclusive);
         minInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("-9223372036854775808")));
         facets.insert(minInclusive->type(), minInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsInt];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("2147483647")));
         facets.insert(maxInclusive->type(), maxInclusive);
         const XsdFacet::Ptr minInclusive(new XsdFacet());
         minInclusive->setType(XsdFacet::MinimumInclusive);
         minInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("-2147483648")));
         facets.insert(minInclusive->type(), minInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsShort];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("32767")));
         facets.insert(maxInclusive->type(), maxInclusive);
         const XsdFacet::Ptr minInclusive(new XsdFacet());
         minInclusive->setType(XsdFacet::MinimumInclusive);
         minInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("-32768")));
         facets.insert(minInclusive->type(), minInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsByte];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("127")));
         facets.insert(maxInclusive->type(), maxInclusive);
         const XsdFacet::Ptr minInclusive(new XsdFacet());
         minInclusive->setType(XsdFacet::MinimumInclusive);
         minInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("-128")));
         facets.insert(minInclusive->type(), minInclusive);
     }
     const XsdFacet::Ptr unsignedMinInclusive(new XsdFacet());
     unsignedMinInclusive->setType(XsdFacet::MinimumInclusive);
     unsignedMinInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("0")));
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsNonNegativeInteger];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         facets.insert(unsignedMinInclusive->type(), unsignedMinInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsUnsignedLong];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         facets.insert(unsignedMinInclusive->type(), unsignedMinInclusive);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("18446744073709551615")));
         facets.insert(maxInclusive->type(), maxInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsUnsignedInt];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         facets.insert(unsignedMinInclusive->type(), unsignedMinInclusive);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("4294967295")));
         facets.insert(maxInclusive->type(), maxInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsUnsignedShort];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         facets.insert(unsignedMinInclusive->type(), unsignedMinInclusive);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("65535")));
         facets.insert(maxInclusive->type(), maxInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsUnsignedByte];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         facets.insert(integerPattern->type(), integerPattern);
         facets.insert(unsignedMinInclusive->type(), unsignedMinInclusive);
         const XsdFacet::Ptr maxInclusive(new XsdFacet());
         maxInclusive->setType(XsdFacet::MaximumInclusive);
         maxInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("255")));
         facets.insert(maxInclusive->type(), maxInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsPositiveInteger];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         facets.insert(fixedZeroFractionDigits->type(), fixedZeroFractionDigits);
         const XsdFacet::Ptr minInclusive(new XsdFacet());
         minInclusive->setType(XsdFacet::MinimumInclusive);
         minInclusive->setValue(DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("1")));
         facets.insert(minInclusive->type(), minInclusive);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsYearMonthDuration];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         const XsdFacet::Ptr pattern(new XsdFacet());
         pattern->setType(XsdFacet::Pattern);
         pattern->setMultiValue(AtomicValue::List() << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("[^DT]*")));
         facets.insert(pattern->type(), pattern);
     }
     {
         XsdFacet::Hash &facets = hash[BuiltinTypes::xsDayTimeDuration];
         facets.insert(fixedCollapseWhiteSpace->type(), fixedCollapseWhiteSpace);
         const XsdFacet::Ptr pattern(new XsdFacet());
         pattern->setType(XsdFacet::Pattern);
         pattern->setMultiValue(AtomicValue::List() << DerivedString<TypeString>::fromLexical(m_namePool, QString::fromLatin1("[^YM]*(T.*)?")));
         facets.insert(pattern->type(), pattern);
     }
     return hash;
 }
setUriResolver()
void XsdSchemaContext::setUriResolver (const QAbstractUriResolver * resolver)
Sets the uri resolver that is used for resolving URIs in the schema parser.
Definition at line 100 of file qxsdschemacontext.cpp.
 {
     m_uriResolver = uriResolver;
 }
uriResolver()
const QAbstractUriResolver * XsdSchemaContext::uriResolver () const virtual
Returns the uri resolver that is used for resolving URIs in the schema parser.
Implements QPatternist::ReportContext.
Definition at line 105 of file qxsdschemacontext.cpp.
Referenced by setUriResolver().
 {
     return m_uriResolver;
 }
Properties
m_baseURI
QUrl QPatternist::XsdSchemaContext::m_baseURI private
Definition at line 177 of file qxsdschemacontext_p.h.
Referenced by baseURI(), and setBaseURI().
m_builtinTypesFacetList
QHash<SchemaType::Ptr, XsdFacet::Hash> QPatternist::XsdSchemaContext::m_builtinTypesFacetList mutable
Definition at line 170 of file qxsdschemacontext_p.h.
Referenced by facetsForType().
m_messageHandler
QAbstractMessageHandler* QPatternist::XsdSchemaContext::m_messageHandler private
Definition at line 179 of file qxsdschemacontext_p.h.
Referenced by messageHandler(), and setMessageHandler().
m_namePool
NamePool::Ptr QPatternist::XsdSchemaContext::m_namePool private
Definition at line 175 of file qxsdschemacontext_p.h.
Referenced by namePool(), schemaTypeFactory(), and setupBuiltinTypesFacetList().
m_networkAccessManager
QNetworkAccessManager* QPatternist::XsdSchemaContext::m_networkAccessManager private
Definition at line 176 of file qxsdschemacontext_p.h.
Referenced by networkAccessManager(), and setNetworkAccessManager().
m_schemaTypeFactory
SchemaTypeFactory::Ptr QPatternist::XsdSchemaContext::m_schemaTypeFactory mutable
The following variables should not be accessed directly.
Definition at line 169 of file qxsdschemacontext_p.h.
Referenced by QPatternist::XsdValidatingInstanceReader::loadSchema(), and schemaTypeFactory().
m_uriResolver
const QAbstractUriResolver* QPatternist::XsdSchemaContext::m_uriResolver private
Definition at line 178 of file qxsdschemacontext_p.h.
Referenced by setUriResolver(), and uriResolver().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdschemacontext_p.h
/src/xmlpatterns/schema/qxsdschemacontext.cpp