Qt 4.8: QDeclarativeXmlQueryEngine Class Reference
QDeclarativeXmlQueryEngine Class Reference
Signals
void error (void *, const QString &)
void queryCompleted (const QDeclarativeXmlQueryResult &)
Signals inherited from QThread
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void abort (int id)
int doQuery (QString query, QString namespaces, QByteArray data, QList< QDeclarativeXmlListModelRole *> *roleObjects, QStringList keyRoleResultsCache)
void processJobs ()
QDeclarativeXmlQueryEngine (QDeclarativeEngine *eng)
~QDeclarativeXmlQueryEngine ()
Public Functions inherited from QThread
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeXmlQueryEngine * instance (QDeclarativeEngine *engine)
Static Public Functions inherited from QThread
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void run ()
The starting point for the thread.
Protected Functions inherited from QThread
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void addIndexToRangeList (QList< QDeclarativeXmlListRange > *ranges, int index) const
void doQueryJob (XmlQueryJob *job, QDeclarativeXmlQueryResult *currentResult)
void doSubQueryJob (XmlQueryJob *job, QDeclarativeXmlQueryResult *currentResult)
void getValuesOfKeyRoles (const XmlQueryJob &currentJob, QStringList *values, QXmlQuery *query) const
void processQuery (XmlQueryJob *job)
Properties
QSet< int > m_cancelledJobs
QDeclarativeEngine * m_engine
QObject * m_eventLoopQuitHack
QList< XmlQueryJob > m_jobs
QMutex m_mutex
QAtomicInt m_queryIds
QDeclarativeXmlQueryThreadObject * m_threadObject
Static Private Attributes
static QHash< QDeclarativeEngine *, QDeclarativeXmlQueryEngine * > queryEngines
static QMutex queryEnginesMutex
Additional Inherited Members
Public Types inherited from QThread
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Public Slots inherited from QThread
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QThread
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 178 of file qdeclarativexmllistmodel.cpp.
Constructors and Destructors
QDeclarativeXmlQueryEngine()
QDeclarativeXmlQueryEngine::QDeclarativeXmlQueryEngine (QDeclarativeEngine * eng)
Definition at line 244 of file qdeclarativexmllistmodel.cpp.
Referenced by instance().
 : QThread(eng), m_threadObject(0), m_queryIds(XMLLISTMODEL_CLEAR_ID + 1), m_engine(eng), m_eventLoopQuitHack(0)
 {
     qRegisterMetaType<QDeclarativeXmlQueryResult>("QDeclarativeXmlQueryResult");
     m_eventLoopQuitHack = new QObject;
     m_eventLoopQuitHack->moveToThread(this);
     connect(m_eventLoopQuitHack, SIGNAL(destroyed(QObject*)), SLOT(quit()), Qt::DirectConnection);
     start(QThread::IdlePriority);
 }
~QDeclarativeXmlQueryEngine()
QDeclarativeXmlQueryEngine::~QDeclarativeXmlQueryEngine ()
Definition at line 255 of file qdeclarativexmllistmodel.cpp.
 {
     queryEnginesMutex.lock();
     queryEngines.remove(m_engine);
     queryEnginesMutex.unlock();
     m_eventLoopQuitHack->deleteLater();
     wait();
 }
Functions
abort()
void QDeclarativeXmlQueryEngine::abort (int id)
Definition at line 301 of file qdeclarativexmllistmodel.cpp.
Referenced by QDeclarativeXmlListModel::reload().
 {
     QMutexLocker ml(&m_mutex);
     if (id != -1)
         m_cancelledJobs.insert(id);
 }
addIndexToRangeList()
void QDeclarativeXmlQueryEngine::addIndexToRangeList (QList< QDeclarativeXmlListRange > * ranges, int index) const private
Definition at line 432 of file qdeclarativexmllistmodel.cpp.
Referenced by doSubQueryJob().
{
     if (ranges->isEmpty())
         ranges->append(qMakePair(index, 1));
     else if (ranges->last().first + ranges->last().second == index)
         ranges->last().second += 1;
     else
         ranges->append(qMakePair(index, 1));
 }
doQuery()
int QDeclarativeXmlQueryEngine::doQuery (QString query, QString namespaces, QByteArray data, QList< QDeclarativeXmlListModelRole *> * roleObjects, QStringList keyRoleResultsCache)
Definition at line 265 of file qdeclarativexmllistmodel.cpp.
Referenced by QDeclarativeXmlListModel::reload(), and QDeclarativeXmlListModel::requestFinished().
{
     {
         QMutexLocker m1(&m_mutex);
         m_queryIds.ref();
         if (m_queryIds <= 0)
             m_queryIds = 1;
     }
     XmlQueryJob job;
     job.queryId = m_queryIds;
     job.data = data;
     job.query = QLatin1String("doc($src)") + query;
     job.namespaces = namespaces;
     job.keyRoleResultsCache = keyRoleResultsCache;
     for (int i=0; i<roleObjects->count(); i++) {
         if (!roleObjects->at(i)->isValid()) {
             job.roleQueries << QString();
             continue;
         }
         job.roleQueries << roleObjects->at(i)->query();
         job.roleQueryErrorId << static_cast<void*>(roleObjects->at(i));
         if (roleObjects->at(i)->isKey())
             job.keyRoleQueries << job.roleQueries.last();
     }
     {
         QMutexLocker ml(&m_mutex);
         m_jobs.append(job);
         if (m_threadObject)
             m_threadObject->processJobs();
     }
     return job.queryId;
 }
doQueryJob()
void QDeclarativeXmlQueryEngine::doQueryJob (XmlQueryJob * job, QDeclarativeXmlQueryResult * currentResult) private
Definition at line 372 of file qdeclarativexmllistmodel.cpp.
Referenced by processQuery().
 {
     Q_ASSERT(currentJob->queryId != -1);
     QString r;
     QXmlQuery query;
     QBuffer buffer(&currentJob->data);
     buffer.open(QIODevice::ReadOnly);
     query.bindVariable(QLatin1String("src"), &buffer);
     query.setQuery(currentJob->namespaces + currentJob->query);
     query.evaluateTo(&r);
     //always need a single root element
     QByteArray xml = "<dummy:items xmlns:dummy=\"http://qtsotware.com/dummy\">\n" + r.toUtf8() + "</dummy:items>";
     QBuffer b(&xml);
     b.open(QIODevice::ReadOnly);
     QString namespaces = QLatin1String("declare namespace dummy=\"http://qtsotware.com/dummy\";\n") + currentJob->namespaces;
     QString prefix = QLatin1String("doc($inputDocument)/dummy:items") +
                      currentJob->query.mid(currentJob->query.lastIndexOf(QLatin1Char('/')));
     //figure out how many items we are dealing with
     int count = -1;
     {
         QXmlResultItems result;
         QXmlQuery countquery;
         countquery.bindVariable(QLatin1String("inputDocument"), &b);
         countquery.setQuery(namespaces + QLatin1String("count(") + prefix + QLatin1Char(')'));
         countquery.evaluateTo(&result);
         QXmlItem item(result.next());
         if (item.isAtomicValue())
             count = item.toAtomicValue().toInt();
     }
     currentJob->data = xml;
     currentJob->prefix = namespaces + prefix + QLatin1Char('/');
     currentResult->size = (count > 0 ? count : 0);
 }
doSubQueryJob()
void QDeclarativeXmlQueryEngine::doSubQueryJob (XmlQueryJob * job, QDeclarativeXmlQueryResult * currentResult) private
Definition at line 441 of file qdeclarativexmllistmodel.cpp.
Referenced by processQuery().
 {
     Q_ASSERT(currentJob->queryId != -1);
     QBuffer b(&currentJob->data);
     b.open(QIODevice::ReadOnly);
     QXmlQuery subquery;
     subquery.bindVariable(QLatin1String("inputDocument"), &b);
     QStringList keyRoleResults;
     getValuesOfKeyRoles(*currentJob, &keyRoleResults, &subquery);
     // See if any values of key roles have been inserted or removed.
     if (currentJob->keyRoleResultsCache.isEmpty()) {
         currentResult->inserted << qMakePair(0, currentResult->size);
     } else {
         if (keyRoleResults != currentJob->keyRoleResultsCache) {
             QStringList temp;
             for (int i=0; i<currentJob->keyRoleResultsCache.count(); i++) {
                 if (!keyRoleResults.contains(currentJob->keyRoleResultsCache[i]))
                     addIndexToRangeList(&currentResult->removed, i);
                 else
                     temp << currentJob->keyRoleResultsCache[i];
             }
             for (int i=0; i<keyRoleResults.count(); i++) {
                 if (temp.count() == i || keyRoleResults[i] != temp[i]) {
                     temp.insert(i, keyRoleResults[i]);
                     addIndexToRangeList(&currentResult->inserted, i);
                 }
             }
         }
     }
     currentResult->keyRoleResultsCache = keyRoleResults;
     // Get the new values for each role.
     //### we might be able to condense even further (query for everything in one go)
     const QStringList &queries = currentJob->roleQueries;
     for (int i = 0; i < queries.size(); ++i) {
         QList<QVariant> resultList;
         if (!queries[i].isEmpty()) {
             subquery.setQuery(currentJob->prefix + QLatin1String("(let $v := string(") + queries[i] + QLatin1String(") return if ($v) then ") + queries[i] + QLatin1String(" else \"\")"));
             if (subquery.isValid()) {
                 QXmlResultItems resultItems;
                 subquery.evaluateTo(&resultItems);
                 QXmlItem item(resultItems.next());
                 while (!item.isNull()) {
                     resultList << item.toAtomicValue(); //### we used to trim strings
                     item = resultItems.next();
                 }
             } else {
                 emit error(currentJob->roleQueryErrorId.at(i), queries[i]);
             }
         }
         //### should warn here if things have gone wrong.
         while (resultList.count() < currentResult->size)
             resultList << QVariant();
         currentResult->data << resultList;
         b.seek(0);
     }
     //this method is much slower, but works better for incremental loading
     /*for (int j = 0; j < m_size; ++j) {
         QList<QVariant> resultList;
         for (int i = 0; i < m_roleObjects->size(); ++i) {
             QDeclarativeXmlListModelRole *role = m_roleObjects->at(i);
             subquery.setQuery(m_prefix.arg(j+1) + role->query());
             if (role->isStringList()) {
                 QStringList data;
                 subquery.evaluateTo(&data);
                 resultList << QVariant(data);
                 //qDebug() << data;
             } else {
                 QString s;
                 subquery.evaluateTo(&s);
                 if (role->isCData()) {
                     //un-escape
                     s.replace(QLatin1String("&lt;"), QLatin1String("<"));
                     s.replace(QLatin1String("&gt;"), QLatin1String(">"));
                     s.replace(QLatin1String("&amp;"), QLatin1String("&"));
                 }
                 resultList << s.trimmed();
                 //qDebug() << s;
             }
             b.seek(0);
         }
         m_modelData << resultList;
     }*/
 }
error
void QDeclarativeXmlQueryEngine::error (void * , const QString &) signal
Referenced by doSubQueryJob().
getValuesOfKeyRoles()
void QDeclarativeXmlQueryEngine::getValuesOfKeyRoles (const XmlQueryJob & currentJob, QStringList * values, QXmlQuery * query) const private
Definition at line 411 of file qdeclarativexmllistmodel.cpp.
Referenced by doSubQueryJob().
 {
     const QStringList &keysQueries = currentJob.keyRoleQueries;
     QString keysQuery;
     if (keysQueries.count() == 1)
         keysQuery = currentJob.prefix + keysQueries[0];
     else if (keysQueries.count() > 1)
         keysQuery = currentJob.prefix + QLatin1String("concat(") + keysQueries.join(QLatin1String(",")) + QLatin1String(")");
     if (!keysQuery.isEmpty()) {
         query->setQuery(keysQuery);
         QXmlResultItems resultItems;
         query->evaluateTo(&resultItems);
         QXmlItem item(resultItems.next());
         while (!item.isNull()) {
             values->append(item.toAtomicValue().toString());
             item = resultItems.next();
         }
     }
 }
instance()
QDeclarativeXmlQueryEngine * QDeclarativeXmlQueryEngine::instance (QDeclarativeEngine * engine) static
Definition at line 342 of file qdeclarativexmllistmodel.cpp.
Referenced by QDeclarativeXmlListModel::classBegin(), QDeclarativeXmlListModel::reload(), and QDeclarativeXmlListModel::requestFinished().
 {
     queryEnginesMutex.lock();
     QDeclarativeXmlQueryEngine *queryEng = queryEngines.value(engine);
     if (!queryEng) {
         queryEng = new QDeclarativeXmlQueryEngine(engine);
         queryEngines.insert(engine, queryEng);
     }
     queryEnginesMutex.unlock();
     return queryEng;
 }
processJobs()
void QDeclarativeXmlQueryEngine::processJobs ()
Definition at line 321 of file qdeclarativexmllistmodel.cpp.
Referenced by QDeclarativeXmlQueryThreadObject::event(), and run().
 {
     QMutexLocker locker(&m_mutex);
     while (true) {
         if (m_jobs.isEmpty())
             return;
         XmlQueryJob currentJob = m_jobs.takeLast();
         while (m_cancelledJobs.remove(currentJob.queryId)) {
             if (m_jobs.isEmpty())
               return;
             currentJob = m_jobs.takeLast();
         }
         locker.unlock();
         processQuery(&currentJob);
         locker.relock();
     }
 }
processQuery()
void QDeclarativeXmlQueryEngine::processQuery (XmlQueryJob * job) private
Definition at line 355 of file qdeclarativexmllistmodel.cpp.
Referenced by processJobs().
 {
     QDeclarativeXmlQueryResult result;
     result.queryId = job->queryId;
     doQueryJob(job, &result);
     doSubQueryJob(job, &result);
     {
         QMutexLocker ml(&m_mutex);
         if (m_cancelledJobs.contains(job->queryId)) {
             m_cancelledJobs.remove(job->queryId);
         } else {
             emit queryCompleted(result);
         }
     }
 }
queryCompleted
void QDeclarativeXmlQueryEngine::queryCompleted (const QDeclarativeXmlQueryResult &) signal
Referenced by processQuery().
run()
void QDeclarativeXmlQueryEngine::run (void) protected virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented from QThread.
Definition at line 308 of file qdeclarativexmllistmodel.cpp.
 {
     m_mutex.lock();
     m_threadObject = new QDeclarativeXmlQueryThreadObject(this);
     m_mutex.unlock();
     processJobs();
     exec();
     delete m_threadObject;
     m_threadObject = 0;
 }
Properties
m_cancelledJobs
QSet<int> QDeclarativeXmlQueryEngine::m_cancelledJobs private
Definition at line 209 of file qdeclarativexmllistmodel.cpp.
Referenced by abort(), processJobs(), and processQuery().
m_engine
QDeclarativeEngine* QDeclarativeXmlQueryEngine::m_engine private
Definition at line 212 of file qdeclarativexmllistmodel.cpp.
Referenced by ~QDeclarativeXmlQueryEngine().
m_eventLoopQuitHack
QObject* QDeclarativeXmlQueryEngine::m_eventLoopQuitHack private
Definition at line 213 of file qdeclarativexmllistmodel.cpp.
Referenced by QDeclarativeXmlQueryEngine(), and ~QDeclarativeXmlQueryEngine().
m_jobs
QList<XmlQueryJob> QDeclarativeXmlQueryEngine::m_jobs private
Definition at line 208 of file qdeclarativexmllistmodel.cpp.
Referenced by doQuery(), and processJobs().
m_mutex
QMutex QDeclarativeXmlQueryEngine::m_mutex private
Definition at line 206 of file qdeclarativexmllistmodel.cpp.
Referenced by abort(), doQuery(), processJobs(), processQuery(), and run().
m_queryIds
QAtomicInt QDeclarativeXmlQueryEngine::m_queryIds private
Definition at line 210 of file qdeclarativexmllistmodel.cpp.
Referenced by doQuery().
m_threadObject
QDeclarativeXmlQueryThreadObject* QDeclarativeXmlQueryEngine::m_threadObject private
Definition at line 207 of file qdeclarativexmllistmodel.cpp.
Referenced by doQuery(), and run().
queryEngines
QHash< QDeclarativeEngine *, QDeclarativeXmlQueryEngine * > QDeclarativeXmlQueryEngine::queryEngines static private
Definition at line 215 of file qdeclarativexmllistmodel.cpp.
Referenced by instance(), and ~QDeclarativeXmlQueryEngine().
queryEnginesMutex
QMutex QDeclarativeXmlQueryEngine::queryEnginesMutex static private
Definition at line 216 of file qdeclarativexmllistmodel.cpp.
Referenced by instance(), and ~QDeclarativeXmlQueryEngine().
The documentation for this class was generated from the following file:
/src/declarative/util/qdeclarativexmllistmodel.cpp