Qt 4.8: QDeclarativeAnchorAnimation Class Reference
QDeclarativeAnchorAnimation Class Reference
#include <qdeclarativeanimation_p.h>
Signals
void durationChanged (int)
void easingChanged (const QEasingCurve &)
Signals inherited from QDeclarativeAbstractAnimation
void alwaysRunToEndChanged (bool)
void completed ()
void loopCountChanged (int)
void pausedChanged (bool)
void runningChanged (bool)
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int duration () const
QEasingCurve easing () const
QDeclarativeAnchorAnimation (QObject *parent=0)
void setDuration (int)
void setEasing (const QEasingCurve &)
QDeclarativeListProperty< QDeclarativeItem > targets ()
virtual ~QDeclarativeAnchorAnimation ()
Public Functions inherited from QDeclarativeAbstractAnimation
bool alwaysRunToEnd () const
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int currentTime ()
QDeclarativeAnimationGroup * group () const
bool isPaused () const
bool isRunning () const
int loops () const
QDeclarativeAbstractAnimation (QObject *parent=0)
void setAlwaysRunToEnd (bool)
void setCurrentTime (int)
void setDefaultTarget (const QDeclarativeProperty &)
void setDisableUserControl ()
void setGroup (QDeclarativeAnimationGroup *)
void setLoops (int)
void setPaused (bool)
void setRunning (bool)
virtual ~QDeclarativeAbstractAnimation ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueSource
QDeclarativePropertyValueSource ()
Constructs a QDeclarativePropertyValueSource.
virtual ~QDeclarativePropertyValueSource ()
Destroys the value source.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual QAbstractAnimation * qtAnimation ()
virtual void transition (QDeclarativeStateActions &actions, QDeclarativeProperties &modified, TransitionDirection direction)
Protected Functions inherited from QDeclarativeAbstractAnimation
QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int duration
QEasingCurve easing
QDeclarativeListProperty< QDeclarativeItem > targets
Additional Inherited Members
Public Types inherited from QDeclarativeAbstractAnimation
enum Loops { Infinite = -2 }
enum TransitionDirection { Forward, Backward }
Public Slots inherited from QDeclarativeAbstractAnimation
void complete ()
void pause ()
void restart ()
void resume ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 479 of file qdeclarativeanimation_p.h.
Constructors and Destructors
QDeclarativeAnchorAnimation()
QDeclarativeAnchorAnimation::QDeclarativeAnchorAnimation (QObject * parent = 0)
Definition at line 2962 of file qdeclarativeanimation.cpp.
 : QDeclarativeAbstractAnimation(*(new QDeclarativeAnchorAnimationPrivate), parent)
 {
     Q_D(QDeclarativeAnchorAnimation);
     d->va = new QDeclarativeBulkValueAnimator;
     QDeclarative_setParent_noEvent(d->va, this);
 }
~QDeclarativeAnchorAnimation()
QDeclarativeAnchorAnimation::~QDeclarativeAnchorAnimation () virtual
Definition at line 2970 of file qdeclarativeanimation.cpp.
 {
 }
Functions
duration()
int QDeclarativeAnchorAnimation::duration () const
Referenced by qtAnimation(), and setDuration().
durationChanged
void QDeclarativeAnchorAnimation::durationChanged (int) signal
Referenced by setDuration().
easing()
QEasingCurve QDeclarativeAnchorAnimation::easing () const
Referenced by setDuration().
easingChanged
void QDeclarativeAnchorAnimation::easingChanged (const QEasingCurve &) signal
Referenced by setEasing().
qtAnimation()
QAbstractAnimation * QDeclarativeAnchorAnimation::qtAnimation () protected virtual
Implements QDeclarativeAbstractAnimation.
Definition at line 2974 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAnchorAnimation);
     return d->va;
 }
setDuration()
void QDeclarativeAnchorAnimation::setDuration (int duration)
Definition at line 3011 of file qdeclarativeanimation.cpp.
 {
     if (duration < 0) {
         qmlInfo(this) << tr("Cannot set a duration of < 0");
         return;
     }
     Q_D(QDeclarativeAnchorAnimation);
     if (d->va->duration() == duration)
         return;
     d->va->setDuration(duration);
     emit durationChanged(duration);
 }
setEasing()
void QDeclarativeAnchorAnimation::setEasing (const QEasingCurve & e)
Definition at line 3053 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAnchorAnimation);
     if (d->va->easingCurve() == e)
         return;
     d->va->setEasingCurve(e);
     emit easingChanged(e);
 }
targets()
QDeclarativeListProperty<QDeclarativeItem> QDeclarativeAnchorAnimation::targets ()
Referenced by qtAnimation().
transition()
void QDeclarativeAnchorAnimation::transition (QDeclarativeStateActions & actions, QDeclarativeProperties & modified, TransitionDirection direction) protected virtual
Reimplemented from QDeclarativeAbstractAnimation.
Definition at line 3063 of file qdeclarativeanimation.cpp.
 {
     Q_UNUSED(modified);
     Q_D(QDeclarativeAnchorAnimation);
     QDeclarativeAnimationPropertyUpdater *data = new QDeclarativeAnimationPropertyUpdater;
     data->interpolatorType = QMetaType::QReal;
     data->interpolator = d->interpolator;
     data->reverse = direction == Backward ? true : false;
     data->fromSourced = false;
     data->fromDefined = false;
     for (int ii = 0; ii < actions.count(); ++ii) {
         QDeclarativeAction &action = actions[ii];
         if (action.event && action.event->typeName() == QLatin1String("AnchorChanges")
             && (d->targets.isEmpty() || d->targets.contains(static_cast<QDeclarativeAnchorChanges*>(action.event)->object()))) {
             data->actions << static_cast<QDeclarativeAnchorChanges*>(action.event)->additionalActions();
         }
     }
     if (data->actions.count()) {
         if (!d->rangeIsSet) {
             d->va->setStartValue(qreal(0));
             d->va->setEndValue(qreal(1));
             d->rangeIsSet = true;
         }
         d->va->setAnimValue(data, QAbstractAnimation::DeleteWhenStopped);
         d->va->setFromSourcedValue(&data->fromSourced);
     } else {
         delete data;
     }
 }
Properties
duration
int QDeclarativeAnchorAnimation::duration private
Definition at line 484 of file qdeclarativeanimation_p.h.
easing
QEasingCurve QDeclarativeAnchorAnimation::easing private
Definition at line 485 of file qdeclarativeanimation_p.h.
targets
QDeclarativeListProperty< QDeclarativeItem > QDeclarativeAnchorAnimation::targets private
Definition at line 483 of file qdeclarativeanimation_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeanimation_p.h
/src/declarative/util/qdeclarativeanimation.cpp