Qt 4.8: QConfFileSettingsPrivate Class Reference
QConfFileSettingsPrivate Class Reference
#include <qsettings_p.h>
Public Functions
QStringList children (const QString &prefix, ChildSpec spec) const
void clear ()
QString fileName () const
void flush ()
bool get (const QString &key, QVariant *value) const
bool isWritable () const
QConfFileSettingsPrivate (QSettings::Format format, QSettings::Scope scope, const QString &organization, const QString &application)
QConfFileSettingsPrivate (const QString &fileName, QSettings::Format format)
void remove (const QString &key)
void set (const QString &key, const QVariant &value)
void sync ()
~QConfFileSettingsPrivate ()
Public Functions inherited from QSettingsPrivate
QString actualKey (const QString &key) const
void beginGroupOrArray (const QSettingsGroup &group)
QSettingsPrivate (QSettings::Format format)
QSettingsPrivate (QSettings::Format format, QSettings::Scope scope, const QString &organization, const QString &application)
void requestUpdate ()
void setStatus (QSettings::Status status) const
void update ()
virtual ~QSettingsPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static bool readIniFile (const QByteArray &data, UnparsedSettingsMap *unparsedIniSections)
static bool readIniLine (const QByteArray &data, int &dataPos, int &lineStart, int &lineLen, int &equalsPos)
static bool readIniSection (const QSettingsKey &section, const QByteArray &data, ParsedSettingsMap *settingsMap, QTextCodec *codec)
Static Public Functions inherited from QSettingsPrivate
static QSettingsPrivate * create (QSettings::Format format, QSettings::Scope scope, const QString &organization, const QString &application)
static QSettingsPrivate * create (const QString &fileName, QSettings::Format format)
static void iniEscapedKey (const QString &key, QByteArray &result)
static void iniEscapedString (const QString &str, QByteArray &result, QTextCodec *codec)
static void iniEscapedStringList (const QStringList &strs, QByteArray &result, QTextCodec *codec)
static bool iniUnescapedKey (const QByteArray &key, int from, int to, QString &result)
static bool iniUnescapedStringList (const QByteArray &str, int from, int to, QString &stringResult, QStringList &stringListResult, QTextCodec *codec)
static QString normalizedKey (const QString &key)
static void processChild (QString key, ChildSpec spec, QMap< QString, QString > &result)
static QStringList splitArgs (const QString &s, int idx)
static QVariant stringListToVariantList (const QStringList &l)
static QVariant stringToVariant (const QString &s)
static QStringList variantListToStringList (const QVariantList &l)
static QString variantToString (const QVariant &v)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Private Functions
void ensureAllSectionsParsed (QConfFile *confFile) const
void ensureSectionParsed (QConfFile *confFile, const QSettingsKey &key) const
void initAccess ()
void initFormat ()
bool readPlistFile (const QString &fileName, ParsedSettingsMap *map) const
void syncConfFile (int confFileNo)
bool writeIniFile (QIODevice &device, const ParsedSettingsMap &map)
bool writePlistFile (const QString &fileName, const ParsedSettingsMap &map) const
Properties
Qt::CaseSensitivity caseSensitivity
QScopedSharedPointer< QConfFile > confFiles [NumConfFiles]
QString extension
int nextPosition
QSettings::ReadFunc readFunc
QSettings::WriteFunc writeFunc
Additional Inherited Members
Public Types inherited from QSettingsPrivate
enum {
F_Application = 0x0, F_Organization = 0x1, F_User = 0x0, F_System = 0x2,
NumConfFiles = 4
}
enum ChildSpec { AllKeys, ChildKeys, ChildGroups }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Variables inherited from QSettingsPrivate
QString applicationName
QSettings::Format format
QTextCodec * iniCodec
QString organizationName
QSettings::Scope scope
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Protected Variables inherited from QSettingsPrivate
bool fallbacks
QString groupPrefix
QStack< QSettingsGroup > groupStack
bool pendingChanges
int spec
QSettings::Status status
Detailed Description
Definition at line 273 of file qsettings_p.h.
Constructors and Destructors
QConfFileSettingsPrivate() [1/2]
QConfFileSettingsPrivate::QConfFileSettingsPrivate (QSettings::Format format, QSettings::Scope scope, const QString & organization, const QString & application)
Definition at line 1150 of file qsettings.cpp.
     : QSettingsPrivate(format, scope, organization, application),
       nextPosition(0x40000000) // big positive number
 {
     int i;
     initFormat();
     QString org = organization;
     if (org.isEmpty()) {
         setStatus(QSettings::AccessError);
         org = QLatin1String("Unknown Organization");
     }
 #if !defined(Q_OS_BLACKBERRY)
     QString appFile = org + QDir::separator() + application + extension;
     QString orgFile = org + extension;
     if (scope == QSettings::UserScope) {
         QString userPath = getPath(format, QSettings::UserScope);
         if (!application.isEmpty())
             confFiles[F_User | F_Application].reset(QConfFile::fromName(userPath + appFile, true));
         confFiles[F_User | F_Organization].reset(QConfFile::fromName(userPath + orgFile, true));
     }
     QString systemPath = getPath(format, QSettings::SystemScope);
     if (!application.isEmpty())
         confFiles[F_System | F_Application].reset(QConfFile::fromName(systemPath + appFile, false));
     confFiles[F_System | F_Organization].reset(QConfFile::fromName(systemPath + orgFile, false));
 #else
     QString confName = getPath(format, QSettings::UserScope) + org;
     if (!application.isEmpty())
         confName += QDir::separator() + application;
     confName += extension;
     confFiles[SandboxConfFile].reset(QConfFile::fromName(confName, true));
 #endif
     for (i = 0; i < NumConfFiles; ++i) {
         if (confFiles[i]) {
             spec = i;
             break;
         }
     }
     initAccess();
 }
QConfFileSettingsPrivate() [2/2]
QConfFileSettingsPrivate::QConfFileSettingsPrivate (const QString & fileName, QSettings::Format format)
Definition at line 1199 of file qsettings.cpp.
     : QSettingsPrivate(format),
       nextPosition(0x40000000) // big positive number
 {
     initFormat();
     confFiles[0].reset(QConfFile::fromName(fileName, true));
     initAccess();
 }
~QConfFileSettingsPrivate()
QConfFileSettingsPrivate::~QConfFileSettingsPrivate ()
Definition at line 1211 of file qsettings.cpp.
 {
     QMutexLocker locker(globalMutex());
     ConfFileHash *usedHash = usedHashFunc();
     ConfFileCache *unusedCache = unusedCacheFunc();
     for (int i = 0; i < NumConfFiles; ++i) {
         if (confFiles[i] && !confFiles[i]->ref.deref()) {
             if (confFiles[i]->size == 0) {
                 delete confFiles[i].take();
             } else {
                 if (usedHash)
                     usedHash->remove(confFiles[i]->name);
                 if (unusedCache) {
                     QT_TRY {
                         // compute a better size?
                         unusedCache->insert(confFiles[i]->name, confFiles[i].data(),
                                         10 + (confFiles[i]->originalKeys.size() / 4));
                         confFiles[i].take();
                     } QT_CATCH(...) {
                         // out of memory. Do not cache the file.
                         delete confFiles[i].take();
                     }
                 } else {
                     // unusedCache is gone - delete the entry to prevent a memory leak
                     delete confFiles[i].take();
                 }
             }
         }
         // prevent the ScopedPointer to deref it again.
         confFiles[i].take();
     }
 }
Functions
children()
QStringList QConfFileSettingsPrivate::children (const QString & prefix, ChildSpec spec) const virtual
Implements QSettingsPrivate.
Definition at line 1317 of file qsettings.cpp.
 {
     QMap<QString, QString> result;
     ParsedSettingsMap::const_iterator j;
     QSettingsKey thePrefix(prefix, caseSensitivity);
     int startPos = prefix.size();
     for (int i = 0; i < NumConfFiles; ++i) {
         if (QConfFile *confFile = confFiles[i].data()) {
             QMutexLocker locker(&confFile->mutex);
             if (thePrefix.isEmpty()) {
                 ensureAllSectionsParsed(confFile);
             } else {
                 ensureSectionParsed(confFile, thePrefix);
             }
             j = const_cast<const ParsedSettingsMap *>(
                     &confFile->originalKeys)->lowerBound( thePrefix);
             while (j != confFile->originalKeys.constEnd() && j.key().startsWith(thePrefix)) {
                 if (!confFile->removedKeys.contains(j.key()))
                     processChild(j.key().originalCaseKey().mid(startPos), spec, result);
                 ++j;
             }
             j = const_cast<const ParsedSettingsMap *>(
                     &confFile->addedKeys)->lowerBound(thePrefix);
             while (j != confFile->addedKeys.constEnd() && j.key().startsWith(thePrefix)) {
                 processChild(j.key().originalCaseKey().mid(startPos), spec, result);
                 ++j;
             }
             if (!fallbacks)
                 break;
         }
     }
     return result.keys();
 }
clear()
void QConfFileSettingsPrivate::clear () virtual
Implements QSettingsPrivate.
Definition at line 1357 of file qsettings.cpp.
 {
     QConfFile *confFile = confFiles[spec].data();
     if (!confFile)
         return;
     QMutexLocker locker(&confFile->mutex);
     ensureAllSectionsParsed(confFile);
     confFile->addedKeys.clear();
     confFile->removedKeys = confFile->originalKeys;
 }
ensureAllSectionsParsed()
void QConfFileSettingsPrivate::ensureAllSectionsParsed (QConfFile * confFile) const private
Definition at line 1970 of file qsettings.cpp.
Referenced by children(), clear(), and syncConfFile().
 {
     UnparsedSettingsMap::const_iterator i = confFile->unparsedIniSections.constBegin();
     const UnparsedSettingsMap::const_iterator end = confFile->unparsedIniSections.constEnd();
     for (; i != end; ++i) {
         if (!QConfFileSettingsPrivate::readIniSection(i.key(), i.value(), &confFile->originalKeys, iniCodec))
             setStatus(QSettings::FormatError);
     }
     confFile->unparsedIniSections.clear();
 }
ensureSectionParsed()
void QConfFileSettingsPrivate::ensureSectionParsed (QConfFile * confFile, const QSettingsKey & key) const private
Definition at line 1982 of file qsettings.cpp.
Referenced by children(), get(), and remove().
 {
     if (confFile->unparsedIniSections.isEmpty())
         return;
     UnparsedSettingsMap::iterator i;
     int indexOfSlash = key.indexOf(QLatin1Char('/'));
     if (indexOfSlash != -1) {
         i = confFile->unparsedIniSections.upperBound(key);
         if (i == confFile->unparsedIniSections.begin())
             return;
         --i;
         if (i.key().isEmpty() || !key.startsWith(i.key()))
             return;
     } else {
         i = confFile->unparsedIniSections.begin();
         if (i == confFile->unparsedIniSections.end() || !i.key().isEmpty())
             return;
     }
     if (!QConfFileSettingsPrivate::readIniSection(i.key(), i.value(), &confFile->originalKeys, iniCodec))
         setStatus(QSettings::FormatError);
     confFile->unparsedIniSections.erase(i);
 }
fileName()
QString QConfFileSettingsPrivate::fileName () const virtual
Implements QSettingsPrivate.
Definition at line 1388 of file qsettings.cpp.
 {
     QConfFile *confFile = confFiles[spec].data();
     if (!confFile)
         return QString();
     return confFile->name;
 }
flush()
void QConfFileSettingsPrivate::flush () virtual
Implements QSettingsPrivate.
Definition at line 1383 of file qsettings.cpp.
 {
     sync();
 }
get()
bool QConfFileSettingsPrivate::get (const QString & key, QVariant * value) const virtual
Implements QSettingsPrivate.
Definition at line 1284 of file qsettings.cpp.
 {
     QSettingsKey theKey(key, caseSensitivity);
     ParsedSettingsMap::const_iterator j;
     bool found = false;
     for (int i = 0; i < NumConfFiles; ++i) {
         if (QConfFile *confFile = confFiles[i].data()) {
             QMutexLocker locker(&confFile->mutex);
             if (!confFile->addedKeys.isEmpty()) {
                 j = confFile->addedKeys.constFind(theKey);
                 found = (j != confFile->addedKeys.constEnd());
             }
             if (!found) {
                 ensureSectionParsed(confFile, theKey);
                 j = confFile->originalKeys.constFind(theKey);
                 found = (j != confFile->originalKeys.constEnd()
                          && !confFile->removedKeys.contains(theKey));
             }
             if (found && value)
                 *value = *j;
             if (found)
                 return true;
             if (!fallbacks)
                 break;
         }
     }
     return false;
 }
initAccess()
void QConfFileSettingsPrivate::initAccess () private
Definition at line 1012 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate().
 {
     if (confFiles[spec]) {
         if (format > QSettings::IniFormat) {
             if (!readFunc)
                 setStatus(QSettings::AccessError);
         }
     }
     sync();       // loads the files the first time
 }
initFormat()
void QConfFileSettingsPrivate::initFormat () private
Definition at line 986 of file qsettings.cpp.
Referenced by QConfFileSettingsPrivate().
 {
     extension = (format == QSettings::NativeFormat) ? QLatin1String(".conf") : QLatin1String(".ini");
     readFunc = 0;
     writeFunc = 0;
 #if defined(Q_OS_MAC)
     caseSensitivity = (format == QSettings::NativeFormat) ? Qt::CaseSensitive : IniCaseSensitivity;
 #else
     caseSensitivity = IniCaseSensitivity;
 #endif
     if (format > QSettings::IniFormat) {
         QMutexLocker locker(globalMutex());
         const CustomFormatVector *customFormatVector = customFormatVectorFunc();
         int i = (int)format - (int)QSettings::CustomFormat1;
         if (i >= 0 && i < customFormatVector->size()) {
             QConfFileCustomFormat info = customFormatVector->at(i);
             extension = info.extension;
             readFunc = info.readFunc;
             writeFunc = info.writeFunc;
             caseSensitivity = info.caseSensitivity;
         }
     }
 }
isWritable()
bool QConfFileSettingsPrivate::isWritable () const virtual
Implements QSettingsPrivate.
Definition at line 1396 of file qsettings.cpp.
 {
     if (format > QSettings::IniFormat && !writeFunc)
         return false;
     QConfFile *confFile = confFiles[spec].data();
     if (!confFile)
         return false;
     return confFile->isWritable();
 }
readIniFile()
bool QConfFileSettingsPrivate::readIniFile (const QByteArray & data, UnparsedSettingsMap * unparsedIniSections) static
Definition at line 1727 of file qsettings.cpp.
Referenced by syncConfFile().
 {
 #define FLUSH_CURRENT_SECTION() \
     { \
         QByteArray &sectionData = (*unparsedIniSections)[QSettingsKey(currentSection, \
                                                                       IniCaseSensitivity, \
                                                                       sectionPosition)]; \
         if (!sectionData.isEmpty()) \
             sectionData.append('\n'); \
         sectionData += data.mid(currentSectionStart, lineStart - currentSectionStart); \
         sectionPosition = ++position; \
     }
     QString currentSection;
     int currentSectionStart = 0;
     int dataPos = 0;
     int lineStart;
     int lineLen;
     int equalsPos;
     int position = 0;
     int sectionPosition = 0;
     bool ok = true;
     while (readIniLine(data, dataPos, lineStart, lineLen, equalsPos)) {
         char ch = data.at(lineStart);
         if (ch == '[') {
             FLUSH_CURRENT_SECTION();
             // this is a section
             QByteArray iniSection;
             int idx = data.indexOf(']', lineStart);
             if (idx == -1 || idx >= lineStart + lineLen) {
                 ok = false;
                 iniSection = data.mid(lineStart + 1, lineLen - 1);
             } else {
                 iniSection = data.mid(lineStart + 1, idx - lineStart - 1);
             }
             iniSection = iniSection.trimmed();
             if (qstricmp(iniSection, "general") == 0) {
                 currentSection.clear();
             } else {
                 if (qstricmp(iniSection, "%general") == 0) {
                     currentSection = QLatin1String(iniSection.constData() + 1);
                 } else {
                     currentSection.clear();
                     iniUnescapedKey(iniSection, 0, iniSection.size(), currentSection);
                 }
                 currentSection += QLatin1Char('/');
             }
             currentSectionStart = dataPos;
         }
         ++position;
     }
     Q_ASSERT(lineStart == data.length());
     FLUSH_CURRENT_SECTION();
     return ok;
 #undef FLUSH_CURRENT_SECTION
 }
readIniLine()
bool QConfFileSettingsPrivate::readIniLine (const QByteArray & data, int & dataPos, int & lineStart, int & lineLen, int & equalsPos) static
Definition at line 1659 of file qsettings.cpp.
Referenced by readIniFile(), and readIniSection().
 {
     int dataLen = data.length();
     bool inQuotes = false;
     equalsPos = -1;
     lineStart = dataPos;
     while (lineStart < dataLen && (charTraits[uint(uchar(data.at(lineStart)))] & Space))
         ++lineStart;
     int i = lineStart;
     while (i < dataLen) {
         while (!(charTraits[uint(uchar(data.at(i)))] & Special)) {
             if (++i == dataLen)
                 goto break_out_of_outer_loop;
         }
         char ch = data.at(i++);
         if (ch == '=') {
             if (!inQuotes && equalsPos == -1)
                 equalsPos = i - 1;
         } else if (ch == '\n' || ch == '\r') {
             if (i == lineStart + 1) {
                 ++lineStart;
             } else if (!inQuotes) {
                 --i;
                 goto break_out_of_outer_loop;
             }
         } else if (ch == '\\') {
             if (i < dataLen) {
                 char ch = data.at(i++);
                 if (i < dataLen) {
                     char ch2 = data.at(i);
                     // \n, \r, \r\n, and \n\r are legitimate line terminators in INI files
                     if ((ch == '\n' && ch2 == '\r') || (ch == '\r' && ch2 == '\n'))
                         ++i;
                 }
             }
         } else if (ch == '"') {
             inQuotes = !inQuotes;
         } else {
             Q_ASSERT(ch == ';');
             if (i == lineStart + 1) {
                 char ch;
                 while (i < dataLen && ((ch = data.at(i) != '\n') && ch != '\r'))
                     ++i;
                 lineStart = i;
             } else if (!inQuotes) {
                 --i;
                 goto break_out_of_outer_loop;
             }
         }
     }
 break_out_of_outer_loop:
     dataPos = i;
     lineLen = i - lineStart;
     return lineLen > 0;
 }
readIniSection()
bool QConfFileSettingsPrivate::readIniSection (const QSettingsKey & section, const QByteArray & data, ParsedSettingsMap * settingsMap, QTextCodec * codec) static
Definition at line 1792 of file qsettings.cpp.
Referenced by ensureAllSectionsParsed(), and ensureSectionParsed().
 {
     QStringList strListValue;
     bool sectionIsLowercase = (section == section.originalCaseKey());
     int equalsPos;
     bool ok = true;
     int dataPos = 0;
     int lineStart;
     int lineLen;
     int position = section.originalKeyPosition();
     while (readIniLine(data, dataPos, lineStart, lineLen, equalsPos)) {
         char ch = data.at(lineStart);
         Q_ASSERT(ch != '[');
         if (equalsPos == -1) {
             if (ch != ';')
                 ok = false;
             continue;
         }
         int keyEnd = equalsPos;
         while (keyEnd > lineStart && ((ch = data.at(keyEnd - 1)) == ' ' || ch == '\t'))
             --keyEnd;
         int valueStart = equalsPos + 1;
         QString key = section.originalCaseKey();
         bool keyIsLowercase = (iniUnescapedKey(data, lineStart, keyEnd, key) && sectionIsLowercase);
         QString strValue;
         strValue.reserve(lineLen - (valueStart - lineStart));
         bool isStringList = iniUnescapedStringList(data, valueStart, lineStart + lineLen,
                                                    strValue, strListValue, codec);
         QVariant variant;
         if (isStringList) {
             variant = stringListToVariantList(strListValue);
         } else {
             variant = stringToVariant(strValue);
         }
         /*
             We try to avoid the expensive toLower() call in
             QSettingsKey by passing Qt::CaseSensitive when the
             key is already in lowercase.
         */
         settingsMap->insert(QSettingsKey(key, keyIsLowercase ? Qt::CaseSensitive
                                                              : IniCaseSensitivity,
                                          position),
                             variant);
         ++position;
     }
     return ok;
 }
readPlistFile()
bool QConfFileSettingsPrivate::readPlistFile (const QString & fileName, ParsedSettingsMap * map) const private
Definition at line 677 of file qsettings_mac.cpp.
Referenced by syncConfFile().
 {
     QCFType<CFDataRef> resource;
     SInt32 code;
     if (!CFURLCreateDataAndPropertiesFromResource(kCFAllocatorDefault, urlFromFileName(fileName),
                                                   &resource, 0, 0, &code))
         return false;
     QCFString errorStr;
     QCFType<CFPropertyListRef> propertyList =
             CFPropertyListCreateFromXMLData(kCFAllocatorDefault, resource, kCFPropertyListImmutable,
                                             &errorStr);
     if (!propertyList)
         return true;
     if (CFGetTypeID(propertyList) != CFDictionaryGetTypeID())
         return false;
     CFDictionaryRef cfdict =
             static_cast<CFDictionaryRef>(static_cast<CFPropertyListRef>(propertyList));
     int size = (int)CFDictionaryGetCount(cfdict);
     QVarLengthArray<CFPropertyListRef> keys(size);
     QVarLengthArray<CFPropertyListRef> values(size);
     CFDictionaryGetKeysAndValues(cfdict, keys.data(), values.data());
     for (int i = 0; i < size; ++i) {
         QString key = qtKey(static_cast<CFStringRef>(keys[i]));
         map->insert(QSettingsKey(key, Qt::CaseSensitive), qtValue(values[i]));
     }
     return true;
 }
remove()
void QConfFileSettingsPrivate::remove (const QString & key) virtual
Implements QSettingsPrivate.
Definition at line 1245 of file qsettings.cpp.
 {
     QConfFile *confFile = confFiles[spec].data();
     if (!confFile)
         return;
     QSettingsKey theKey(key, caseSensitivity);
     QSettingsKey prefix(key + QLatin1Char('/'), caseSensitivity);
     QMutexLocker locker(&confFile->mutex);
     ensureSectionParsed(confFile, theKey);
     ensureSectionParsed(confFile, prefix);
     ParsedSettingsMap::iterator i = confFile->addedKeys.lowerBound(prefix);
     while (i != confFile->addedKeys.end() && i.key().startsWith(prefix))
         i = confFile->addedKeys.erase(i);
     confFile->addedKeys.remove(theKey);
     ParsedSettingsMap::const_iterator j = const_cast<const ParsedSettingsMap *>(&confFile->originalKeys)->lowerBound(prefix);
     while (j != confFile->originalKeys.constEnd() && j.key().startsWith(prefix)) {
         confFile->removedKeys.insert(j.key(), QVariant());
         ++j;
     }
     if (confFile->originalKeys.contains(theKey))
         confFile->removedKeys.insert(theKey, QVariant());
 }
set()
void QConfFileSettingsPrivate::set (const QString & key, const QVariant & value) virtual
Implements QSettingsPrivate.
Definition at line 1272 of file qsettings.cpp.
 {
     QConfFile *confFile = confFiles[spec].data();
     if (!confFile)
         return;
     QSettingsKey theKey(key, caseSensitivity, nextPosition++);
     QMutexLocker locker(&confFile->mutex);
     confFile->removedKeys.remove(theKey);
     confFile->addedKeys.insert(theKey, value);
 }
sync()
void QConfFileSettingsPrivate::sync () virtual
Implements QSettingsPrivate.
Definition at line 1369 of file qsettings.cpp.
Referenced by flush().
 {
     // people probably won't be checking the status a whole lot, so in case of
     // error we just try to go on and make the best of it
     for (int i = 0; i < NumConfFiles; ++i) {
         QConfFile *confFile = confFiles[i].data();
         if (confFile) {
             QMutexLocker locker(&confFile->mutex);
             syncConfFile(i);
         }
     }
 }
syncConfFile()
void QConfFileSettingsPrivate::syncConfFile (int confFileNo) private
Definition at line 1408 of file qsettings.cpp.
Referenced by sync().
 {
     QConfFile *confFile = confFiles[confFileNo].data();
     bool readOnly = confFile->addedKeys.isEmpty() && confFile->removedKeys.isEmpty();
     bool ok;
     /*
         We can often optimize the read-only case, if the file on disk
         hasn't changed.
     */
     if (readOnly && confFile->size > 0) {
         QFileInfo fileInfo(confFile->name);
         if (confFile->size == fileInfo.size() && confFile->timeStamp == fileInfo.lastModified())
             return;
     }
     /*
         Open the configuration file and try to use it using a named
         semaphore on Windows and an advisory lock on Unix-based
         systems. This protect us against other QSettings instances
         trying to access the same file from other threads or
         processes.
         As it stands now, the locking mechanism doesn't work for
         .plist files.
     */
     QFile file(confFile->name);
     bool createFile = !file.exists();
     if (!readOnly && confFile->isWritable())
         file.open(QFile::ReadWrite);
     if (!file.isOpen())
         file.open(QFile::ReadOnly);
     if (!createFile && !file.isOpen())
         setStatus(QSettings::AccessError);
 #ifdef Q_OS_WIN
     HANDLE readSemaphore = 0;
     HANDLE writeSemaphore = 0;
     static const int FileLockSemMax = 50;
     int numReadLocks = readOnly ? 1 : FileLockSemMax;
     if (file.isOpen()) {
         // Acquire the write lock if we will be writing
         if (!readOnly) {
             QString writeSemName = QLatin1String("QSettingsWriteSem ");
             writeSemName.append(file.fileName());
             writeSemaphore = CreateSemaphore(0, 1, 1, reinterpret_cast<const wchar_t *>(writeSemName.utf16()));
             if (writeSemaphore) {
                 WaitForSingleObject(writeSemaphore, INFINITE);
             } else {
                 setStatus(QSettings::AccessError);
                 return;
             }
         }
         // Acquire all the read locks if we will be writing, to make sure nobody
         // reads while we're writing. If we are only reading, acquire a single
         // read lock.
         QString readSemName(QLatin1String("QSettingsReadSem "));
         readSemName.append(file.fileName());
         readSemaphore = CreateSemaphore(0, FileLockSemMax, FileLockSemMax, reinterpret_cast<const wchar_t *>(readSemName.utf16()));
         if (readSemaphore) {
             for (int i = 0; i < numReadLocks; ++i)
                 WaitForSingleObject(readSemaphore, INFINITE);
         } else {
             setStatus(QSettings::AccessError);
             if (writeSemaphore != 0) {
                 ReleaseSemaphore(writeSemaphore, 1, 0);
                 CloseHandle(writeSemaphore);
             }
             return;
         }
     }
 #else
     if (file.isOpen())
         unixLock(file.handle(), readOnly ? F_RDLCK : F_WRLCK);
 #endif
     // If we have created the file, apply the file perms
     if (file.isOpen()) {
         if (createFile) {
             QFile::Permissions perms = file.permissions() | QFile::ReadOwner | QFile::WriteOwner;
             if (!confFile->userPerms)
                 perms |= QFile::ReadGroup | QFile::ReadOther;
             file.setPermissions(perms);
         }
     }
     /*
         We hold the lock. Let's reread the file if it has changed
         since last time we read it.
     */
     QFileInfo fileInfo(confFile->name);
     bool mustReadFile = true;
     if (!readOnly)
         mustReadFile = (confFile->size != fileInfo.size()
                         || (confFile->size != 0 && confFile->timeStamp != fileInfo.lastModified()));
     if (mustReadFile) {
         confFile->unparsedIniSections.clear();
         confFile->originalKeys.clear();
         /*
             Files that we can't read (because of permissions or
             because they don't exist) are treated as empty files.
         */
         if (file.isReadable() && fileInfo.size() != 0) {
 #ifdef Q_OS_MAC
             if (format == QSettings::NativeFormat) {
                 ok = readPlistFile(confFile->name, &confFile->originalKeys);
             } else
 #endif
             {
                 if (format <= QSettings::IniFormat) {
                     QByteArray data = file.readAll();
                     ok = readIniFile(data, &confFile->unparsedIniSections);
                 } else {
                     if (readFunc) {
                         QSettings::SettingsMap tempNewKeys;
                         ok = readFunc(file, tempNewKeys);
                         if (ok) {
                             QSettings::SettingsMap::const_iterator i = tempNewKeys.constBegin();
                             while (i != tempNewKeys.constEnd()) {
                                 confFile->originalKeys.insert(QSettingsKey(i.key(),
                                                                            caseSensitivity),
                                                               i.value());
                                 ++i;
                             }
                         }
                     } else {
                         ok = false;
                     }
                 }
             }
             if (!ok)
                 setStatus(QSettings::FormatError);
         }
         confFile->size = fileInfo.size();
         confFile->timeStamp = fileInfo.lastModified();
     }
     /*
         We also need to save the file. We still hold the file lock,
         so everything is under control.
     */
     if (!readOnly) {
         ensureAllSectionsParsed(confFile);
         ParsedSettingsMap mergedKeys = confFile->mergedKeyMap();
         if (file.isWritable()) {
 #ifdef Q_OS_MAC
             if (format == QSettings::NativeFormat) {
                 ok = writePlistFile(confFile->name, mergedKeys);
             } else
 #endif
             {
                 file.seek(0);
                 file.resize(0);
                 if (format <= QSettings::IniFormat) {
                     ok = writeIniFile(file, mergedKeys);
                     if (!ok) {
                         // try to restore old data; might work if the disk was full and the new data
                         // was larger than the old data
                         file.seek(0);
                         file.resize(0);
                         writeIniFile(file, confFile->originalKeys);
                     }
                 } else {
                     if (writeFunc) {
                         QSettings::SettingsMap tempOriginalKeys;
                         ParsedSettingsMap::const_iterator i = mergedKeys.constBegin();
                         while (i != mergedKeys.constEnd()) {
                             tempOriginalKeys.insert(i.key(), i.value());
                             ++i;
                         }
                         ok = writeFunc(file, tempOriginalKeys);
                     } else {
                         ok = false;
                     }
                 }
             }
         } else {
             ok = false;
         }
         if (ok) {
             confFile->unparsedIniSections.clear();
             confFile->originalKeys = mergedKeys;
             confFile->addedKeys.clear();
             confFile->removedKeys.clear();
             QFileInfo fileInfo(confFile->name);
             confFile->size = fileInfo.size();
             confFile->timeStamp = fileInfo.lastModified();
         } else {
             setStatus(QSettings::AccessError);
         }
     }
     /*
         Release the file lock.
     */
 #ifdef Q_OS_WIN
     if (readSemaphore != 0) {
         ReleaseSemaphore(readSemaphore, numReadLocks, 0);
         CloseHandle(readSemaphore);
     }
     if (writeSemaphore != 0) {
         ReleaseSemaphore(writeSemaphore, 1, 0);
         CloseHandle(writeSemaphore);
     }
 #endif
 }
writeIniFile()
bool QConfFileSettingsPrivate::writeIniFile (QIODevice & device, const ParsedSettingsMap & map) private
Definition at line 1881 of file qsettings.cpp.
Referenced by syncConfFile().
 {
     IniMap iniMap;
     IniMap::const_iterator i;
 #ifdef Q_OS_WIN
     const char * const eol = "\r\n";
 #else
     const char eol = '\n';
 #endif
     for (ParsedSettingsMap::const_iterator j = map.constBegin(); j != map.constEnd(); ++j) {
         QString section;
         QSettingsIniKey key(j.key().originalCaseKey(), j.key().originalKeyPosition());
         int slashPos;
         if ((slashPos = key.indexOf(QLatin1Char('/'))) != -1) {
             section = key.left(slashPos);
             key.remove(0, slashPos + 1);
         }
         QSettingsIniSection &iniSection = iniMap[section];
         // -1 means infinity
         if (uint(key.position) < uint(iniSection.position))
             iniSection.position = key.position;
         iniSection.keyMap[key] = j.value();
     }
     const int sectionCount = iniMap.size();
     QVector<QSettingsIniKey> sections;
     sections.reserve(sectionCount);
     for (i = iniMap.constBegin(); i != iniMap.constEnd(); ++i)
         sections.append(QSettingsIniKey(i.key(), i.value().position));
     qSort(sections);
     bool writeError = false;
     for (int j = 0; !writeError && j < sectionCount; ++j) {
         i = iniMap.constFind(sections.at(j));
         Q_ASSERT(i != iniMap.constEnd());
         QByteArray realSection;
         iniEscapedKey(i.key(), realSection);
         if (realSection.isEmpty()) {
             realSection = "[General]";
         } else if (qstricmp(realSection, "general") == 0) {
             realSection = "[%General]";
         } else {
             realSection.prepend('[');
             realSection.append(']');
         }
         if (j != 0)
             realSection.prepend(eol);
         realSection += eol;
         device.write(realSection);
         const IniKeyMap &ents = i.value().keyMap;
         for (IniKeyMap::const_iterator j = ents.constBegin(); j != ents.constEnd(); ++j) {
             QByteArray block;
             iniEscapedKey(j.key(), block);
             block += '=';
             const QVariant &value = j.value();
             /*
                 The size() != 1 trick is necessary because
                 QVariant(QString("foo")).toList() returns an empty
                 list, not a list containing "foo".
             */
             if (value.type() == QVariant::StringList
                     || (value.type() == QVariant::List && value.toList().size() != 1)) {
                 iniEscapedStringList(variantListToStringList(value.toList()), block, iniCodec);
             } else {
                 iniEscapedString(variantToString(value), block, iniCodec);
             }
             block += eol;
             if (device.write(block) == -1) {
                 writeError = true;
                 break;
             }
         }
     }
     return !writeError;
 }
writePlistFile()
bool QConfFileSettingsPrivate::writePlistFile (const QString & fileName, const ParsedSettingsMap & map) const private
Definition at line 709 of file qsettings_mac.cpp.
Referenced by syncConfFile().
 {
     QVarLengthArray<QCFType<CFStringRef> > cfkeys(map.size());
     QVarLengthArray<QCFType<CFPropertyListRef> > cfvalues(map.size());
     int i = 0;
     ParsedSettingsMap::const_iterator j;
     for (j = map.constBegin(); j != map.constEnd(); ++j) {
         cfkeys[i] = macKey(j.key());
         cfvalues[i] = macValue(j.value());
         ++i;
     }
     QCFType<CFDictionaryRef> propertyList =
             CFDictionaryCreate(kCFAllocatorDefault,
                                reinterpret_cast<const void **>(cfkeys.data()),
                                reinterpret_cast<const void **>(cfvalues.data()),
                                CFIndex(map.size()),
                                &kCFTypeDictionaryKeyCallBacks,
                                &kCFTypeDictionaryValueCallBacks);
     QCFType<CFDataRef> xmlData = CFPropertyListCreateXMLData(kCFAllocatorDefault, propertyList);
     SInt32 code;
     return CFURLWriteDataAndPropertiesToResource(urlFromFileName(fileName), xmlData, 0, &code);
 }
Properties
caseSensitivity
Qt::CaseSensitivity QConfFileSettingsPrivate::caseSensitivity private
Definition at line 315 of file qsettings_p.h.
Referenced by children(), get(), remove(), set(), and syncConfFile().
confFiles
QScopedSharedPointer<QConfFile> QConfFileSettingsPrivate::confFiles[NumConfFiles] private
Definition at line 311 of file qsettings_p.h.
Referenced by children(), clear(), fileName(), get(), isWritable(), QConfFileSettingsPrivate(), remove(), set(), sync(), syncConfFile(), and ~QConfFileSettingsPrivate().
extension
QString QConfFileSettingsPrivate::extension private
Definition at line 314 of file qsettings_p.h.
Referenced by QConfFileSettingsPrivate().
nextPosition
int QConfFileSettingsPrivate::nextPosition private
Definition at line 316 of file qsettings_p.h.
Referenced by set().
readFunc
QSettings::ReadFunc QConfFileSettingsPrivate::readFunc private
Definition at line 312 of file qsettings_p.h.
Referenced by syncConfFile().
writeFunc
QSettings::WriteFunc QConfFileSettingsPrivate::writeFunc private
Definition at line 313 of file qsettings_p.h.
Referenced by isWritable(), and syncConfFile().
The documentation for this class was generated from the following files:
/src/corelib/io/qsettings_p.h
/src/corelib/io/qsettings.cpp
/src/corelib/io/qsettings_mac.cpp