Qt 4.8: QAbstractAnimation Class Reference
QAbstractAnimation Class Reference abstract
The QAbstractAnimation class is the base of all animations.
#include <qabstractanimation.h>
Public Types
enum DeletionPolicy { KeepWhenStopped = 0, DeleteWhenStopped }
enum Direction { Forward, Backward }
This enum describes the direction of the animation when in Running state.
enum State { Stopped, Paused, Running }
This enum describes the state of the animation.
Public Slots
void pause ()
Pauses the animation.
void resume ()
Resumes the animation after it was paused.
void setCurrentTime (int msecs)
void setPaused (bool)
If paused is true, the animation is paused.
void start (QAbstractAnimation::DeletionPolicy policy=KeepWhenStopped)
Starts the animation.
void stop ()
Stops the animation.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentLoopChanged (int currentLoop)
QAbstractAnimation emits this signal whenever the current loop changes.
void directionChanged (QAbstractAnimation::Direction)
QAbstractAnimation emits this signal whenever the direction has been changed.
void finished ()
QAbstractAnimation emits this signal after the animation has stopped and has reached the end.
void stateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
QAbstractAnimation emits this signal whenever the state of the animation has changed from oldState to newState.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int currentLoop () const
int currentLoopTime () const
Returns the current time inside the current loop.
int currentTime () const
Direction direction () const
virtual int duration () const =0
QAnimationGroup * group () const
If this animation is part of a QAnimationGroup, this function returns a pointer to the group; otherwise, it returns 0.
int loopCount () const
QAbstractAnimation (QObject *parent=0)
Constructs the QAbstractAnimation base class, and passes parent to QObject's constructor.
void setDirection (Direction direction)
void setLoopCount (int loopCount)
State state () const
int totalDuration () const
Returns the total and effective duration of the animation, including the loop count.
virtual ~QAbstractAnimation ()
Stops the animation if it's running, then destroys the QAbstractAnimation.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *event)
Reimplemented Function
QAbstractAnimation (QAbstractAnimationPrivate &dd, QObject *parent=0)
virtual void updateCurrentTime (int currentTime)=0
This pure virtual function is called every time the animation's currentTime changes.
virtual void updateDirection (QAbstractAnimation::Direction direction)
This virtual function is called by QAbstractAnimation when the direction of the animation is changed.
virtual void updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
This virtual function is called by QAbstractAnimation when the state of the animation is changed from oldState to newState.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int currentLoop
the current loop of the animation
int currentTime
the current time and progress of the animation
Direction direction
the direction of the animation when it is in Running state.
int duration
the duration of the animation.
int loopCount
the loop count of the animation
State state
state of the animation.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractAnimation class is the base of all animations.
Since
4.6
The class defines the functions for the functionality shared by all animations. By inheriting this class, you can create custom animations that plug into the rest of the animation framework.
The progress of an animation is given by its current time (currentLoopTime()), which is measured in milliseconds from the start of the animation (0) to its end (duration()). The value is updated automatically while the animation is running. It can also be set directly with setCurrentTime().
At any point an animation is in one of three states: QAbstractAnimation::Running, QAbstractAnimation::Stopped, or QAbstractAnimation::Paused–as defined by the QAbstractAnimation::State enum. The current state can be changed by calling start(), stop(), pause(), or resume(). An animation will always reset its current time when it is started. If paused, it will continue with the same current time when resumed. When an animation is stopped, it cannot be resumed, but will keep its current time (until started again). QAbstractAnimation will emit stateChanged() whenever its state changes.
An animation can loop any number of times by setting the loopCount property. When an animation's current time reaches its duration(), it will reset the current time and keep running. A loop count of 1 (the default value) means that the animation will run one time. Note that a duration of -1 means that the animation will run until stopped; the current time will increase indefinitely. When the current time equals duration() and the animation is in its final loop, the QAbstractAnimation::Stopped state is entered, and the finished() signal is emitted.
QAbstractAnimation provides pure virtual functions used by subclasses to track the progress of the animation: duration() and updateCurrentTime(). The duration() function lets you report a duration for the animation (as discussed above). The animation framework calls updateCurrentTime() when current time has changed. By reimplementing this function, you can track the animation progress. Note that neither the interval between calls nor the number of calls to this function are defined; though, it will normally be 60 updates per second.
By reimplementing updateState(), you can track the animation's state changes, which is particularly useful for animations that are not driven by time.
See also
QVariantAnimation, QPropertyAnimation, QAnimationGroup, {The Animation Framework}
Definition at line 60 of file qabstractanimation.h.
Enumerations
DeletionPolicy
enum QAbstractAnimation::DeletionPolicy
KeepWhenStopped The animation will not be deleted when stopped.
DeleteWhenStopped The animation will be automatically deleted when stopped.
Enumerator
KeepWhenStopped
DeleteWhenStopped
Definition at line 84 of file qabstractanimation.h.
{
         KeepWhenStopped = 0,
         DeleteWhenStopped
     };
Direction
enum QAbstractAnimation::Direction
This enum describes the direction of the animation when in Running state.
Forward The current time of the animation increases with time (i.e., moves from 0 and towards the end / duration).
Backward The current time of the animation decreases with time (i.e., moves from the end / duration and towards 0).
See also
direction
Enumerator
Forward
Backward
Definition at line 73 of file qabstractanimation.h.
                    {
         Forward,
         Backward
     };
State
enum QAbstractAnimation::State
This enum describes the state of the animation.
Stopped The animation is not running. This is the initial state of QAbstractAnimation, and the state QAbstractAnimation reenters when finished. The current time remain unchanged until either setCurrentTime() is called, or the animation is started by calling start().
Paused The animation is paused (i.e., temporarily suspended). Calling resume() will resume animation activity.
Running The animation is running. While control is in the event loop, QAbstractAnimation will update its current time at regular intervals, calling updateCurrentTime() when appropriate.
See also
state(), stateChanged()
Enumerator
Stopped
Paused
Running
Definition at line 78 of file qabstractanimation.h.
                {
         Stopped,
         Paused,
         Running
     };
Constructors and Destructors
QAbstractAnimation() [1/2]
QAbstractAnimation::QAbstractAnimation (QObject * parent = 0)
Constructs the QAbstractAnimation base class, and passes parent to QObject's constructor.
See also
QVariantAnimation, QAnimationGroup
Definition at line 640 of file qabstractanimation.cpp.
     : QObject(*new QAbstractAnimationPrivate, 0)
 {
     // Allow auto-add on reparent
     setParent(parent);
 }
~QAbstractAnimation()
QAbstractAnimation::~QAbstractAnimation () virtual
Stops the animation if it's running, then destroys the QAbstractAnimation.
If the animation is part of a QAnimationGroup, it is automatically removed before it's destroyed.
Definition at line 662 of file qabstractanimation.cpp.
 {
     Q_D(QAbstractAnimation);
     //we can't call stop here. Otherwise we get pure virtual calls
     if (d->state != Stopped) {
         QAbstractAnimation::State oldState = d->state;
         d->state = Stopped;
         emit stateChanged(oldState, d->state);
         if (oldState == QAbstractAnimation::Running)
             QUnifiedTimer::unregisterAnimation(this);
     }
 }
QAbstractAnimation() [2/2]
QAbstractAnimation::QAbstractAnimation (QAbstractAnimationPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 650 of file qabstractanimation.cpp.
     : QObject(dd, 0)
 {
     // Allow auto-add on reparent
    setParent(parent);
 }
Functions
currentLoop()
int QAbstractAnimation::currentLoop () const
Referenced by QSequentialAnimationGroupPrivate::animationInsertedAt(), and setLoopCount().
currentLoopChanged
QAbstractAnimation::currentLoopChanged (int currentLoop) signal
QAbstractAnimation emits this signal whenever the current loop changes.
currentLoop is the current loop.
See also
currentLoop(), loopCount()
Referenced by setCurrentTime().
currentLoopTime()
int QAbstractAnimation::currentLoopTime () const
Returns the current time inside the current loop.
It can go from 0 to duration().
See also
duration(), currentTime
Definition at line 898 of file qabstractanimation.cpp.
Referenced by QUnifiedTimer::closestPauseAnimationTimeToFinish(), QDeclarativeAbstractAnimation::currentTime(), and ParallelAnimationWrapper::updateState().
 {
     Q_D(const QAbstractAnimation);
     return d->currentTime;
 }
currentTime()
int QAbstractAnimation::currentTime () const
Referenced by QParallelAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), QAnimationGroupPrivate::animationRemoved(), QSequentialAnimationGroupPrivate::animationRemoved(), currentLoopTime(), QSmoothedAnimation::init(), QParallelAnimationGroupPrivate::shouldAnimationStart(), and QParallelAnimationGroup::updateCurrentTime().
direction()
Direction QAbstractAnimation::direction () const
Referenced by QSequentialAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), QSequentialAnimationGroupPrivate::activateCurrentAnimation(), group(), setDirection(), QParallelAnimationGroupPrivate::shouldAnimationStart(), and ParallelAnimationWrapper::updateState().
directionChanged
QAbstractAnimation::directionChanged (QAbstractAnimation::Direction newDirection) signal
QAbstractAnimation emits this signal whenever the direction has been changed.
newDirection is the new direction.
See also
direction
Referenced by setDirection().
duration()
virtual int QAbstractAnimation::duration () const pure virtual
Implemented in TickAnimationProxy< T, method >, TickAnimationProxy< QDeclarativeParticlesPrivate, &QDeclarativeParticlesPrivate::tick >, QTickAnimationProxy< T, method >, QActionAnimation, QDeclarativeTimeLine, QVariantAnimation, QSmoothedAnimation, QSequentialAnimationGroup, QPauseAnimation, and QParallelAnimationGroup.
Referenced by setCurrentTime(), setDirection(), and totalDuration().
event()
bool QAbstractAnimation::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Reimplemented in QVariantAnimation, QSequentialAnimationGroup, QAnimationGroup, QPropertyAnimation, QPauseAnimation, and QParallelAnimationGroup.
Definition at line 1067 of file qabstractanimation.cpp.
Referenced by QPauseAnimation::event(), QAnimationGroup::event(), and QVariantAnimation::event().
 {
     return QObject::event(event);
 }
finished
QAbstractAnimation::finished () signal
QAbstractAnimation emits this signal after the animation has stopped and has reached the end.
This signal is emitted after stateChanged().
See also
stateChanged()
group()
QAnimationGroup * QAbstractAnimation::group () const
If this animation is part of a QAnimationGroup, this function returns a pointer to the group; otherwise, it returns 0.
See also
QAnimationGroup::addAnimation()
Definition at line 698 of file qabstractanimation.cpp.
Referenced by QStateMachinePrivate::applyProperties(), QAnimationGroup::insertAnimation(), QDeclarativeTransitionPrivate::QDeclarativeTransitionPrivate(), and QPropertyAnimation::updateState().
 {
     Q_D(const QAbstractAnimation);
     return d->group;
 }
loopCount()
int QAbstractAnimation::loopCount () const
Referenced by QSequentialAnimationGroupPrivate::animationRemoved(), setDirection(), setLoopCount(), and totalDuration().
pause
void QAbstractAnimation::pause () slot
Pauses the animation.
When the animation is paused, state() returns Paused. The value of currentTime will remain unchanged until resume() or start() is called. If you want to continue from the current time, call resume().
See also
start(), state(), resume()
Definition at line 1019 of file qabstractanimation.cpp.
Referenced by QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QSequentialAnimationGroup::addPause(), QParallelAnimationGroupPrivate::applyGroupState(), QSequentialAnimationGroup::insertPause(), QDeclarativeAbstractAnimation::setPaused(), setPaused(), and QDeclarativeTimeLine::sync().
 {
     Q_D(QAbstractAnimation);
     if (d->state == Stopped) {
         qWarning("QAbstractAnimation::pause: Cannot pause a stopped animation");
         return;
     }
     d->setState(Paused);
 }
resume
void QAbstractAnimation::resume () slot
Resumes the animation after it was paused.
When the animation is resumed, it emits the resumed() and stateChanged() signals. The currenttime is not changed.
See also
start(), pause(), state()
Definition at line 1037 of file qabstractanimation.cpp.
Referenced by QDeclarativeAbstractAnimation::setPaused(), and setPaused().
 {
     Q_D(QAbstractAnimation);
     if (d->state != Paused) {
         qWarning("QAbstractAnimation::resume: "
                  "Cannot resume an animation that is not paused");
         return;
     }
     d->setState(Running);
 }
setCurrentTime
void QAbstractAnimation::setCurrentTime (int msecs) slot
Definition at line 925 of file qabstractanimation.cpp.
Referenced by QSequentialAnimationGroupPrivate::advanceForwards(), QDeclarativeAbstractAnimation::complete(), QSequentialAnimationGroupPrivate::rewindForwards(), QDeclarativeAbstractAnimation::setCurrentTime(), QUnifiedTimer::updateAnimationsTime(), and QParallelAnimationGroup::updateCurrentTime().
 {
     Q_D(QAbstractAnimation);
     msecs = qMax(msecs, 0);
     // Calculate new time and loop.
     int dura = duration();
     int totalDura = dura <= 0 ? dura : ((d->loopCount < 0) ? -1 : dura * d->loopCount);
     if (totalDura != -1)
         msecs = qMin(totalDura, msecs);
     d->totalCurrentTime = msecs;
     // Update new values.
     int oldLoop = d->currentLoop;
     d->currentLoop = ((dura <= 0) ? 0 : (msecs / dura));
     if (d->currentLoop == d->loopCount) {
         //we're at the end
         d->currentTime = qMax(0, dura);
         d->currentLoop = qMax(0, d->loopCount - 1);
     } else {
         if (d->direction == Forward) {
             d->currentTime = (dura <= 0) ? msecs : (msecs % dura);
         } else {
             d->currentTime = (dura <= 0) ? msecs : ((msecs - 1) % dura) + 1;
             if (d->currentTime == dura)
                 --d->currentLoop;
         }
     }
     updateCurrentTime(d->currentTime);
     if (d->currentLoop != oldLoop)
         emit currentLoopChanged(d->currentLoop);
     // All animations are responsible for stopping the animation when their
     // own end state is reached; in this case the animation is time driven,
     // and has reached the end.
     if ((d->direction == Forward && d->totalCurrentTime == totalDura)
         || (d->direction == Backward && d->totalCurrentTime == 0)) {
         stop();
     }
 }
setDirection()
void QAbstractAnimation::setDirection (Direction direction)
Definition at line 763 of file qabstractanimation.cpp.
Referenced by QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QParallelAnimationGroup::updateDirection(), and QParallelAnimationGroup::updateState().
 {
     Q_D(QAbstractAnimation);
     if (d->direction == direction)
         return;
     if (state() == Stopped) {
         if (direction == Backward) {
             d->currentTime = duration();
             d->currentLoop = d->loopCount - 1;
         } else {
             d->currentTime = 0;
             d->currentLoop = 0;
         }
     }
     // the commands order below is important: first we need to setCurrentTime with the old direction,
     // then update the direction on this and all children and finally restart the pauseTimer if needed
     if (d->hasRegisteredTimer)
         QUnifiedTimer::ensureTimerUpdate();
     d->direction = direction;
     updateDirection(direction);
     if (d->hasRegisteredTimer)
         // needed to update the timer interval in case of a pause animation
         QUnifiedTimer::updateAnimationTimer();
     emit directionChanged(direction);
 }
setLoopCount()
void QAbstractAnimation::setLoopCount (int loopCount)
Definition at line 826 of file qabstractanimation.cpp.
Referenced by QDeclarativeAbstractAnimation::setLoops(), QDeclarativeAbstractAnimation::setRunning(), and QDeclarativeAbstractAnimation::timelineComplete().
 {
     Q_D(QAbstractAnimation);
     d->loopCount = loopCount;
 }
setPaused
void QAbstractAnimation::setPaused (bool paused) slot
If paused is true, the animation is paused.
If paused is false, the animation is resumed.
See also
state(), pause(), resume()
Definition at line 1055 of file qabstractanimation.cpp.
 {
     if (paused)
         pause();
     else
         resume();
 }
start
void QAbstractAnimation::start (QAbstractAnimation::DeletionPolicy policy = KeepWhenStopped) slot
Starts the animation.
The policy argument says whether or not the animation should be deleted when it's done. When the animation starts, the stateChanged() signal is emitted, and state() returns Running. When control reaches the event loop, the animation will run by itself, periodically calling updateCurrentTime() as the animation progresses.
If the animation is currently stopped or has already reached the end, calling start() will rewind the animation and start again from the beginning. When the animation reaches the end, the animation will either stop, or if the loop level is more than 1, it will rewind and continue from the beginning.
If the animation is already running, this function does nothing.
See also
stop(), state()
Definition at line 983 of file qabstractanimation.cpp.
Referenced by QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QDeclarativeTimeLinePrivate::add(), QWidgetAnimator::animate(), QParallelAnimationGroupPrivate::applyGroupState(), QStateMachinePrivate::applyProperties(), QDeclarativeTimeLine::remove(), QSmoothedAnimation::restart(), QTabBarPrivate::Tab::startAnimation(), QDeclarativeTimeLine::updateCurrentTime(), and QParallelAnimationGroup::updateState().
 {
     Q_D(QAbstractAnimation);
     if (d->state == Running)
         return;
     d->deleteWhenStopped = policy;
     d->setState(Running);
 }
state()
State QAbstractAnimation::state () const
Referenced by QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QParallelAnimationGroupPrivate::applyGroupState(), QTabBarPrivate::moveTabFinished(), QDeclarativeTimeLine::remove(), QSmoothedAnimation::restart(), setDirection(), QParallelAnimationGroup::updateCurrentTime(), QDeclarativeTimeLine::updateCurrentTime(), QParallelAnimationGroup::updateDirection(), QSequentialAnimationGroup::updateDirection(), and ~QAbstractAnimation().
stateChanged
QAbstractAnimation::stateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State oldState) signal
QAbstractAnimation emits this signal whenever the state of the animation has changed from oldState to newState.
This signal is emitted after the virtual updateState() function is called.
See also
updateState()
Referenced by ~QAbstractAnimation().
stop
void QAbstractAnimation::stop () slot
Stops the animation.
When the animation is stopped, it emits the stateChanged() signal, and state() returns Stopped. The current time is not changed.
If the animation stops by itself after reaching the end (i.e., currentLoopTime() == duration() and currentLoop() > loopCount() - 1), the finished() signal is emitted.
See also
start(), state()
Definition at line 1002 of file qabstractanimation.cpp.
Referenced by QWidgetAnimator::abort(), QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QDeclarativeTimeLinePrivate::add(), QStateMachinePrivate::applyProperties(), QSmoothedAnimation::init(), QSmoothedAnimation::QSmoothedAnimation(), QDeclarativeTimeLine::remove(), QSequentialAnimationGroupPrivate::setCurrentAnimation(), setCurrentTime(), QDeclarativeAbstractAnimation::setRunning(), QDeclarativeSpringAnimationPrivate::tick(), QParallelAnimationGroup::updateCurrentTime(), QSequentialAnimationGroup::updateCurrentTime(), QDeclarativeTimeLine::updateCurrentTime(), QParallelAnimationGroup::updateState(), QPropertyAnimation::updateState(), and QPropertyAnimation::~QPropertyAnimation().
 {
     Q_D(QAbstractAnimation);
     if (d->state == Stopped)
         return;
     d->setState(Stopped);
 }
totalDuration()
int QAbstractAnimation::totalDuration () const
Returns the total and effective duration of the animation, including the loop count.
See also
duration(), currentTime
Definition at line 881 of file qabstractanimation.cpp.
Referenced by QSequentialAnimationGroupPrivate::activateCurrentAnimation(), QSequentialAnimationGroupPrivate::animationActualTotalDuration(), QParallelAnimationGroup::duration(), QSequentialAnimationGroup::duration(), QParallelAnimationGroupPrivate::shouldAnimationStart(), and QParallelAnimationGroup::updateCurrentTime().
 {
     int dura = duration();
     if (dura <= 0)
         return dura;
     int loopcount = loopCount();
     if (loopcount < 0)
         return -1;
     return dura * loopcount;
 }
updateCurrentTime()
void QAbstractAnimation::updateCurrentTime (int currentTime) protected pure virtual
This pure virtual function is called every time the animation's currentTime changes.
See also
updateState()
Implemented in TickAnimationProxy< T, method >, TickAnimationProxy< QDeclarativeParticlesPrivate, &QDeclarativeParticlesPrivate::tick >, QTickAnimationProxy< T, method >, QActionAnimation, QDeclarativeTimeLine, QVariantAnimation, QSmoothedAnimation, QSequentialAnimationGroup, QPauseAnimation, and QParallelAnimationGroup.
Referenced by setCurrentTime().
updateDirection()
void QAbstractAnimation::updateDirection (QAbstractAnimation::Direction direction) protected virtual
This virtual function is called by QAbstractAnimation when the direction of the animation is changed.
The direction argument is the new direction.
See also
setDirection(), direction()
Reimplemented in QSequentialAnimationGroup, and QParallelAnimationGroup.
Definition at line 1103 of file qabstractanimation.cpp.
Referenced by setDirection().
 {
     Q_UNUSED(direction);
 }
updateState()
void QAbstractAnimation::updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState) protected virtual
This virtual function is called by QAbstractAnimation when the state of the animation is changed from oldState to newState.
See also
start(), stop(), pause(), resume()
Reimplemented in ParallelAnimationWrapper, QVariantAnimation, QSmoothedAnimation, QSequentialAnimationGroup, QPropertyAnimation, and QParallelAnimationGroup.
Definition at line 1090 of file qabstractanimation.cpp.
Referenced by QParallelAnimationGroup::updateState(), and QSequentialAnimationGroup::updateState().
 {
     Q_UNUSED(oldState);
     Q_UNUSED(newState);
 }
Properties
currentLoop
int QAbstractAnimation::currentLoop private
the current loop of the animation
This property describes the current loop of the animation. By default, the animation's loop count is 1, and so the current loop will always be 0. If the loop count is 2 and the animation runs past its duration, it will automatically rewind and restart at current time 0, and current loop 1, and so on.
When the current loop changes, QAbstractAnimation emits the currentLoopChanged() signal.
Definition at line 68 of file qabstractanimation.h.
Referenced by QSequentialAnimationGroupPrivate::animationInsertedAt().
currentTime
int QAbstractAnimation::currentTime private
the current time and progress of the animation
This property describes the animation's current time. You can change the current time by calling setCurrentTime, or you can call start() and let the animation run, setting the current time automatically as the animation progresses.
The animation's current time starts at 0, and ends at totalDuration().
See also
loopCount, currentLoopTime()
Definition at line 67 of file qabstractanimation.h.
Referenced by QParallelAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), QSequentialAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), and QSequentialAnimationGroupPrivate::animationInsertedAt().
direction
QAbstractAnimation::Direction QAbstractAnimation::direction private
the direction of the animation when it is in Running state.
This direction indicates whether the time moves from 0 towards the animation duration, or from the value of the duration and towards 0 after start() has been called.
By default, this property is set to Forward .
Definition at line 69 of file qabstractanimation.h.
Referenced by QUnifiedTimer::closestPauseAnimationTimeToFinish(), and QUnifiedTimer::updateAnimationsTime().
duration
int QAbstractAnimation::duration private
the duration of the animation.
This pure virtual function returns the duration of the animation, and defines for how long QAbstractAnimation should update the current time.
If the duration is -1, it means that the duration is undefined. In this case, loopCount is ignored.
This duration is local, and does not include the loop count.
A return value of -1 indicates that the animation has no defined duration; the animation should run forever until stopped. This is useful for animations that are not time driven, or where you cannot easily predict its duration (e.g., event driven audio playback in a game).
If the animation is a parallel QAnimationGroup, the duration will be the longest duration of all its animations. If the animation is a sequential QAnimationGroup, the duration will be the sum of the duration of all its animations.
See also
loopCount
Definition at line 70 of file qabstractanimation.h.
Referenced by QParallelAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), QUnifiedTimer::closestPauseAnimationTimeToFinish(), and QParallelAnimationGroupPrivate::connectUncontrolledAnimations().
loopCount
int QAbstractAnimation::loopCount private
the loop count of the animation
This property describes the loop count of the animation as an integer. By default this value is 1, indicating that the animation should run once only, and then stop. By changing it you can let the animation loop several times. With a value of 0, the animation will not run at all, and with a value of -1, the animation will loop forever until stopped. It is not supported to have loop on an animation that has an undefined duration. It will only run once.
Definition at line 66 of file qabstractanimation.h.
Referenced by QParallelAnimationGroupPrivate::_q_uncontrolledAnimationFinished(), and QParallelAnimationGroupPrivate::connectUncontrolledAnimations().
state
QAbstractAnimation::State QAbstractAnimation::state private
state of the animation.
This property describes the current state of the animation. When the animation state changes, QAbstractAnimation emits the stateChanged() signal.
Definition at line 65 of file qabstractanimation.h.
Referenced by QStateMachinePrivate::applyProperties(), QParallelAnimationGroup::updateCurrentTime(), and QPropertyAnimation::updateState().
The documentation for this class was generated from the following files:
/src/corelib/animation/qabstractanimation.h
/src/corelib/animation/qabstractanimation.cpp