Qt 4.8: QTextureGlyphCache Class Reference
QTextureGlyphCache Class Reference abstract
#include <qtextureglyphcache_p.h>
Classes
struct Coord
struct GlyphAndSubPixelPosition
Public Functions
void createCache (int width, int height)
virtual void createTextureData (int width, int height)=0
void fillInPendingGlyphs ()
virtual void fillTexture (const Coord &coord, glyph_t glyph, QFixed subPixelPosition)=0
virtual int glyphMargin () const
virtual int glyphPadding () const
bool isNull () const
virtual int maxTextureHeight () const
virtual int maxTextureWidth () const
bool populate (QFontEngine *fontEngine, int numGlyphs, const glyph_t *glyphs, const QFixedPoint *positions)
QTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform &matrix)
void resizeCache (int width, int height)
virtual void resizeTextureData (int width, int height)=0
QFixed subPixelPositionForX (QFixed x) const
QImage textureMapForGlyph (glyph_t g, QFixed subPixelPosition) const
virtual ~QTextureGlyphCache ()
Public Functions inherited from QFontEngineGlyphCache
Type cacheType () const
QFontEngineGlyphCache (const QTransform &matrix, Type type)
virtual ~QFontEngineGlyphCache ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Variables
QHash< GlyphAndSubPixelPosition, Coord > coords
Public Variables inherited from QFontEngineGlyphCache
QTransform m_transform
QFontEngineGlyphCache::Type m_type
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions
int calculateSubPixelPositionCount (glyph_t) const
Protected Variables
QFontEngine * m_current_fontengine
int m_currentRowHeight
int m_cx
int m_cy
int m_h
QHash< GlyphAndSubPixelPosition, Coord > m_pendingGlyphs
int m_subPixelPositionCount
int m_w
Additional Inherited Members
Public Types inherited from QFontEngineGlyphCache
enum Type { Raster_RGBMask, Raster_A8, Raster_Mono }
Detailed Description
Definition at line 79 of file qtextureglyphcache_p.h.
Constructors and Destructors
QTextureGlyphCache()
QTextureGlyphCache::QTextureGlyphCache (QFontEngineGlyphCache::Type type, const QTransform & matrix) inline
Definition at line 82 of file qtextureglyphcache_p.h.
         : QFontEngineGlyphCache(matrix, type), m_current_fontengine(0),
                                                m_w(0), m_h(0), m_cx(0), m_cy(0), m_currentRowHeight(0), m_subPixelPositionCount(0)
         { }
~QTextureGlyphCache()
virtual QTextureGlyphCache::~QTextureGlyphCache () inline virtual
Definition at line 87 of file qtextureglyphcache_p.h.
 { }
Functions
calculateSubPixelPositionCount()
int QTextureGlyphCache::calculateSubPixelPositionCount (glyph_t glyph) const protected
Definition at line 68 of file qtextureglyphcache.cpp.
Referenced by populate().
 {
     // Test 12 different subpixel positions since it factors into 3*4 so it gives
     // the coverage we need.
     QList<QImage> images;
     for (int i=0; i<12; ++i) {
         QImage img = textureMapForGlyph(glyph, QFixed::fromReal(i / 12.0));
         if (images.isEmpty()) {
             QPainterPath path;
             QFixedPoint point;
             m_current_fontengine->addGlyphsToPath(&glyph, &point, 1, &path, QTextItem::RenderFlags());
             // Glyph is space, return 0 to indicate that we need to keep trying
             if (path.isEmpty())
                 break;
             images.append(img);
         } else {
             bool found = false;
             for (int j=0; j<images.size(); ++j) {
                 if (images.at(j) == img) {
                     found = true;
                     break;
                 }
             }
             if (!found)
                 images.append(img);
         }
     }
     return images.size();
 }
createCache()
void QTextureGlyphCache::createCache (int width, int height) inline
Definition at line 128 of file qtextureglyphcache_p.h.
Referenced by fillInPendingGlyphs().
{
         m_w = width;
         m_h = height;
         createTextureData(width, height);
     }
createTextureData()
virtual void QTextureGlyphCache::createTextureData (int width, int height) pure virtual
Implemented in QImageTextureGlyphCache, and QGLTextureGlyphCache.
fillInPendingGlyphs()
void QTextureGlyphCache::fillInPendingGlyphs ()
Definition at line 259 of file qtextureglyphcache.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and QRasterPaintEngine::drawCachedGlyphs().
 {
     if (m_pendingGlyphs.isEmpty())
         return;
     int requiredHeight = m_h;
     int requiredWidth = m_w; // Use a minimum size to avoid a lot of initial reallocations
     {
         QHash<GlyphAndSubPixelPosition, Coord>::iterator iter = m_pendingGlyphs.begin();
         while (iter != m_pendingGlyphs.end()) {
             Coord c = iter.value();
             requiredHeight = qMax(requiredHeight, c.y + c.h);
             requiredWidth = qMax(requiredWidth, c.x + c.w);
             ++iter;
         }
     }
     if (isNull() || requiredHeight > m_h || requiredWidth > m_w) {
         if (isNull())
             createCache(qt_next_power_of_two(requiredWidth), qt_next_power_of_two(requiredHeight));
         else
             resizeCache(qt_next_power_of_two(requiredWidth), qt_next_power_of_two(requiredHeight));
     }
     {
         QHash<GlyphAndSubPixelPosition, Coord>::iterator iter = m_pendingGlyphs.begin();
         while (iter != m_pendingGlyphs.end()) {
             GlyphAndSubPixelPosition key = iter.key();
             fillTexture(iter.value(), key.glyph, key.subPixelPosition);
             ++iter;
         }
     }
     m_pendingGlyphs.clear();
 }
fillTexture()
virtual void QTextureGlyphCache::fillTexture (const Coord & coord, glyph_t glyph, QFixed subPixelPosition) pure virtual
Implemented in QImageTextureGlyphCache, and QGLTextureGlyphCache.
Referenced by fillInPendingGlyphs().
glyphMargin()
virtual int QTextureGlyphCache::glyphMargin () const inline virtual
Reimplemented in QImageTextureGlyphCache.
Definition at line 123 of file qtextureglyphcache_p.h.
Referenced by QImageTextureGlyphCache::fillTexture(), populate(), and textureMapForGlyph().
 { return 0; }
glyphPadding()
virtual int QTextureGlyphCache::glyphPadding () const inline virtual
Reimplemented in QGLTextureGlyphCache.
Definition at line 124 of file qtextureglyphcache_p.h.
Referenced by populate().
 { return 0; }
isNull()
bool QTextureGlyphCache::isNull () const inline
Definition at line 141 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::createTextureData(), and fillInPendingGlyphs().
 { return m_h == 0; }
maxTextureHeight()
virtual int QTextureGlyphCache::maxTextureHeight () const inline virtual
Reimplemented in QGLTextureGlyphCache.
Definition at line 145 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::maxTextureHeight(), and populate().
 { return -1; }
maxTextureWidth()
virtual int QTextureGlyphCache::maxTextureWidth () const inline virtual
Reimplemented in QGLTextureGlyphCache.
Definition at line 144 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::maxTextureWidth(), and populate().
 { return QT_DEFAULT_TEXTURE_GLYPH_CACHE_WIDTH; }
populate()
bool QTextureGlyphCache::populate (QFontEngine * fontEngine, int numGlyphs, const glyph_t * glyphs, const QFixedPoint * positions)
Definition at line 120 of file qtextureglyphcache.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), and QRasterPaintEngine::drawCachedGlyphs().
 {
 #ifdef CACHE_DEBUG
     printf("Populating with %d glyphs\n", numGlyphs);
     qDebug() << " -> current transformation: " << m_transform;
 #endif
     m_current_fontengine = fontEngine;
     const int margin = glyphMargin();
     const int paddingDoubled = glyphPadding() * 2;
     bool supportsSubPixelPositions = fontEngine->supportsSubPixelPositions();
     if (m_subPixelPositionCount == 0) {
         if (!supportsSubPixelPositions) {
             m_subPixelPositionCount = 1;
         } else {
 #if !defined(Q_WS_X11)
             int i = 0;
             while (m_subPixelPositionCount == 0 && i < numGlyphs)
                 m_subPixelPositionCount = calculateSubPixelPositionCount(glyphs[i++]);
 #else
             m_subPixelPositionCount = 4;
 #endif
         }
     }
     QHash<GlyphAndSubPixelPosition, Coord> listItemCoordinates;
     int rowHeight = 0;
     QFontEngine::GlyphFormat format;
     switch (m_type) {
     case Raster_A8: format = QFontEngine::Format_A8; break;
     case Raster_RGBMask: format = QFontEngine::Format_A32; break;
     default: format = QFontEngine::Format_Mono; break;
     }
     // check each glyph for its metrics and get the required rowHeight.
     for (int i=0; i < numGlyphs; ++i) {
         const glyph_t glyph = glyphs[i];
         QFixed subPixelPosition;
         if (supportsSubPixelPositions) {
             QFixed x = positions != 0 ? positions[i].x : QFixed();
             subPixelPosition = subPixelPositionForX(x);
         }
         if (coords.contains(GlyphAndSubPixelPosition(glyph, subPixelPosition)))
             continue;
         if (listItemCoordinates.contains(GlyphAndSubPixelPosition(glyph, subPixelPosition)))
             continue;
         glyph_metrics_t metrics = fontEngine->alphaMapBoundingBox(glyph, subPixelPosition, m_transform, format);
 #ifdef CACHE_DEBUG
         printf("(%4x): w=%.2f, h=%.2f, xoff=%.2f, yoff=%.2f, x=%.2f, y=%.2f\n",
                glyph,
                metrics.width.toReal(),
                metrics.height.toReal(),
                metrics.xoff.toReal(),
                metrics.yoff.toReal(),
                metrics.x.toReal(),
                metrics.y.toReal());
 #endif
         GlyphAndSubPixelPosition key(glyph, subPixelPosition);
         int glyph_width = metrics.width.ceil().toInt();
         int glyph_height = metrics.height.ceil().toInt();
         if (glyph_height == 0 || glyph_width == 0) {
             // Avoid multiple calls to boundingBox() for non-printable characters
             Coord c = { 0, 0, 0, 0, 0, 0 };
             coords.insert(key, c);
             continue;
         }
         glyph_width += margin * 2 + 4;
         glyph_height += margin * 2 + 4;
         // align to 8-bit boundary
         if (m_type == QFontEngineGlyphCache::Raster_Mono)
             glyph_width = (glyph_width+7)&~7;
         Coord c = { 0, 0, // will be filled in later
                     glyph_width,
                     glyph_height, // texture coords
                     metrics.x.truncate(),
                     -metrics.y.truncate() }; // baseline for horizontal scripts
         listItemCoordinates.insert(key, c);
         rowHeight = qMax(rowHeight, glyph_height);
     }
     if (listItemCoordinates.isEmpty())
         return true;
     rowHeight += margin * 2 + paddingDoubled;
     if (m_w == 0) {
         if (fontEngine->maxCharWidth() <= QT_DEFAULT_TEXTURE_GLYPH_CACHE_WIDTH)
             m_w = QT_DEFAULT_TEXTURE_GLYPH_CACHE_WIDTH;
         else
             m_w = qt_next_power_of_two(fontEngine->maxCharWidth());
     }
     // now actually use the coords and paint the wanted glyps into cache.
     QHash<GlyphAndSubPixelPosition, Coord>::iterator iter = listItemCoordinates.begin();
     int requiredWidth = m_w;
     while (iter != listItemCoordinates.end()) {
         Coord c = iter.value();
         m_currentRowHeight = qMax(m_currentRowHeight, c.h + margin * 2);
         if (m_cx + c.w > requiredWidth) {
             int new_width = requiredWidth*2;
             while (new_width < m_cx + c.w)
                 new_width *= 2;
             if (new_width <= maxTextureWidth()) {
                 requiredWidth = new_width;
             } else {
                 // no room on the current line, start new glyph strip
                 m_cx = 0;
                 m_cy += m_currentRowHeight + paddingDoubled;
                 m_currentRowHeight = c.h + margin * 2; // New row
             }
         }
         if (maxTextureHeight() > 0 && m_cy + c.h > maxTextureHeight()) {
             // We can't make a cache of the required size, so we bail out
             return false;
         }
         c.x = m_cx;
         c.y = m_cy;
         coords.insert(iter.key(), c);
         m_pendingGlyphs.insert(iter.key(), c);
         m_cx += c.w + paddingDoubled;
         ++iter;
     }
     return true;
 }
resizeCache()
void QTextureGlyphCache::resizeCache (int width, int height) inline
Definition at line 134 of file qtextureglyphcache_p.h.
Referenced by fillInPendingGlyphs().
     {
         resizeTextureData(width, height);
         m_w = width;
         m_h = height;
     }
resizeTextureData()
virtual void QTextureGlyphCache::resizeTextureData (int width, int height) pure virtual
Implemented in QImageTextureGlyphCache, and QGLTextureGlyphCache.
subPixelPositionForX()
QFixed QTextureGlyphCache::subPixelPositionForX (QFixed x) const
Definition at line 103 of file qtextureglyphcache.cpp.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs(), QRasterPaintEngine::drawCachedGlyphs(), and populate().
 {
     if (m_subPixelPositionCount <= 1)
         return QFixed();
     QFixed subPixelPosition;
     if (x != 0) {
         subPixelPosition = x - x.floor();
         QFixed fraction = (subPixelPosition / QFixed::fromReal(1.0 / m_subPixelPositionCount)).floor();
         // Compensate for precision loss in fixed point to make sure we are always drawing at a subpixel position over
         // the lower boundary for the selected rasterization by adding 1/64.
         subPixelPosition = fraction / QFixed(m_subPixelPositionCount) + QFixed::fromReal(0.015625);
     }
     return subPixelPosition;
 }
textureMapForGlyph()
QImage QTextureGlyphCache::textureMapForGlyph (glyph_t g, QFixed subPixelPosition) const
Definition at line 296 of file qtextureglyphcache.cpp.
Referenced by calculateSubPixelPositionCount(), QGLTextureGlyphCache::fillTexture(), and QImageTextureGlyphCache::fillTexture().
 {
 #if defined(Q_WS_X11)
     if (m_type != Raster_RGBMask && m_transform.type() > QTransform::TxTranslate && m_current_fontengine->type() == QFontEngine::Freetype) {
         QFontEngineFT::GlyphFormat format = QFontEngineFT::Format_None;
         QImage::Format imageFormat = QImage::Format_Invalid;
         switch (m_type) {
         case Raster_A8:
             format = QFontEngineFT::Format_A8;
             imageFormat = QImage::Format_Indexed8;
             break;
         case Raster_Mono:
             format = QFontEngineFT::Format_Mono;
             imageFormat = QImage::Format_Mono;
             break;
         case Raster_RGBMask:
             // impossible condition (see the if-clause above)
             // this option is here only to silence a compiler warning
             break;
         };
         QFontEngineFT *ft = static_cast<QFontEngineFT*> (m_current_fontengine);
         QFontEngineFT::QGlyphSet *gset = ft->loadTransformedGlyphSet(m_transform);
         QFixedPoint positions[1];
         positions[0].x = subPixelPosition;
         if (gset && ft->loadGlyphs(gset, &g, 1, positions, format)) {
             QFontEngineFT::Glyph *glyph = gset->getGlyph(g, subPixelPosition);
             const int bytesPerLine = (format == QFontEngineFT::Format_Mono ? ((glyph->width + 31) & ~31) >> 3
                                : (glyph->width + 3) & ~3);
             return QImage(glyph->data, glyph->width, glyph->height, bytesPerLine, imageFormat);
         }
     } else
 #endif
     if (m_type == QFontEngineGlyphCache::Raster_RGBMask)
         return m_current_fontengine->alphaRGBMapForGlyph(g, subPixelPosition, glyphMargin(), m_transform);
     else
         return m_current_fontengine->alphaMapForGlyph(g, subPixelPosition, m_transform);
     return QImage();
 }
Properties
coords
QHash<GlyphAndSubPixelPosition, Coord> QTextureGlyphCache::coords
Definition at line 143 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::clear(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QRasterPaintEngine::drawCachedGlyphs(), and populate().
m_current_fontengine
QFontEngine* QTextureGlyphCache::m_current_fontengine protected
Definition at line 154 of file qtextureglyphcache_p.h.
Referenced by calculateSubPixelPositionCount(), populate(), and textureMapForGlyph().
m_currentRowHeight
int QTextureGlyphCache::m_currentRowHeight protected
Definition at line 161 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::clear(), and populate().
m_cx
int QTextureGlyphCache::m_cx protected
Definition at line 159 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::clear(), and populate().
m_cy
int QTextureGlyphCache::m_cy protected
Definition at line 160 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::clear(), and populate().
m_h
int QTextureGlyphCache::m_h protected
Definition at line 158 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::clear(), fillInPendingGlyphs(), and QGLTextureGlyphCache::setContext().
m_pendingGlyphs
QHash<GlyphAndSubPixelPosition, Coord> QTextureGlyphCache::m_pendingGlyphs protected
Definition at line 155 of file qtextureglyphcache_p.h.
Referenced by fillInPendingGlyphs(), and populate().
m_subPixelPositionCount
int QTextureGlyphCache::m_subPixelPositionCount protected
Definition at line 162 of file qtextureglyphcache_p.h.
Referenced by populate(), and subPixelPositionForX().
m_w
int QTextureGlyphCache::m_w protected
Definition at line 157 of file qtextureglyphcache_p.h.
Referenced by QGLTextureGlyphCache::clear(), fillInPendingGlyphs(), and populate().
The documentation for this class was generated from the following files:
/src/gui/painting/qtextureglyphcache_p.h
/src/gui/painting/qtextureglyphcache.cpp