Qt 4.8: QGLFramebufferObjectFormat Class Reference
QGLFramebufferObjectFormat Class Reference
The QGLFramebufferObjectFormat class specifies the format of an OpenGL framebuffer object.
#include <qglframebufferobject.h>
Public Functions
QGLFramebufferObject::Attachment attachment () const
Returns the configuration of the depth and stencil buffers attached to a framebuffer object.
GLenum internalTextureFormat () const
Returns the internal format of a framebuffer object's texture or multisample framebuffer object's color buffer.
bool mipmap () const
Returns true if mipmapping is enabled.
bool operator!= (const QGLFramebufferObjectFormat &other) const
Returns false if all the options of this framebuffer object format are the same as other; otherwise returns true.
QGLFramebufferObjectFormat & operator= (const QGLFramebufferObjectFormat &other)
Assigns other to this object.
bool operator== (const QGLFramebufferObjectFormat &other) const
Returns true if all the options of this framebuffer object format are the same as other; otherwise returns false.
QGLFramebufferObjectFormat ()
Creates a QGLFramebufferObjectFormat object for specifying the format of an OpenGL framebuffer object.
QGLFramebufferObjectFormat (const QGLFramebufferObjectFormat &other)
Constructs a copy of other.
int samples () const
Returns the number of samples per pixel if a framebuffer object is a multisample framebuffer object.
void setAttachment (QGLFramebufferObject::Attachment attachment)
Sets the attachment configuration of a framebuffer object to attachment.
void setInternalTextureFormat (GLenum internalTextureFormat)
Sets the internal format of a framebuffer object's texture or multisample framebuffer object's color buffer to internalTextureFormat.
void setMipmap (bool enabled)
Enables mipmapping if enabled is true; otherwise disables it.
void setSamples (int samples)
Sets the number of samples per pixel for a multisample framebuffer object to samples.
void setTextureTarget (GLenum target)
Sets the texture target of the texture attached to a framebuffer object to target.
GLenum textureTarget () const
Returns the texture target of the texture attached to a framebuffer object.
~QGLFramebufferObjectFormat ()
Destroys the QGLFramebufferObjectFormat.
Private Functions
void detach ()
Properties
QGLFramebufferObjectFormatPrivate * d
Detailed Description
The QGLFramebufferObjectFormat class specifies the format of an OpenGL framebuffer object.
Since
4.6
A framebuffer object has several characteristics:
Number of samples per pixels.
Depth and/or stencil attachments.
Texture target.
Internal texture format.
Note that the desired attachments or number of samples per pixels might not be supported by the hardware driver. Call QGLFramebufferObject::format() after creating a QGLFramebufferObject to find the exact format that was used to create the frame buffer object.
See also
QGLFramebufferObject
Definition at line 140 of file qglframebufferobject.h.
Constructors and Destructors
QGLFramebufferObjectFormat() [1/2]
QGLFramebufferObjectFormat::QGLFramebufferObjectFormat ()
Creates a QGLFramebufferObjectFormat object for specifying the format of an OpenGL framebuffer object.
By default the format specifies a non-multisample framebuffer object with no attachments, texture target GL_TEXTURE_2D, and internal format GL_RGBA8. On OpenGL/ES systems, the default internal format is GL_RGBA.
See also
samples(), attachment(), internalTextureFormat()
Definition at line 138 of file qglframebufferobject.cpp.
 {
     d = new QGLFramebufferObjectFormatPrivate;
 }
QGLFramebufferObjectFormat() [2/2]
QGLFramebufferObjectFormat::QGLFramebufferObjectFormat (const QGLFramebufferObjectFormat & other)
Constructs a copy of other.
Definition at line 147 of file qglframebufferobject.cpp.
 {
     d = other.d;
     d->ref.ref();
 }
~QGLFramebufferObjectFormat()
QGLFramebufferObjectFormat::~QGLFramebufferObjectFormat ()
Destroys the QGLFramebufferObjectFormat.
Definition at line 171 of file qglframebufferobject.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
attachment()
QGLFramebufferObject::Attachment QGLFramebufferObjectFormat::attachment () const
Returns the configuration of the depth and stencil buffers attached to a framebuffer object.
The default is QGLFramebufferObject::NoAttachment.
See also
setAttachment()
Definition at line 263 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObject::QGLFramebufferObject(), and setAttachment().
 {
     return d->attachment;
 }
detach()
void QGLFramebufferObjectFormat::detach () private
Warning
This function is not part of the public interface.
Definition at line 116 of file qglframebufferobject.cpp.
Referenced by internalTextureFormat(), setAttachment(), setInternalTextureFormat(), setMipmap(), setSamples(), and setTextureTarget().
 {
     if (d->ref != 1) {
         QGLFramebufferObjectFormatPrivate *newd
             = new QGLFramebufferObjectFormatPrivate(d);
         if (!d->ref.deref())
             delete d;
         d = newd;
     }
 }
internalTextureFormat()
GLenum QGLFramebufferObjectFormat::internalTextureFormat () const
Returns the internal format of a framebuffer object's texture or multisample framebuffer object's color buffer.
The default is GL_RGBA8 on desktop OpenGL systems, and GL_RGBA on OpenGL/ES systems.
See also
setInternalTextureFormat()
Definition at line 313 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObject::QGLFramebufferObject(), QGLFBOGLPaintDevice::setFBO(), setInternalTextureFormat(), and ShaderEffectSource::updateBackbuffer().
 {
     return d->internal_format;
 }
mipmap()
bool QGLFramebufferObjectFormat::mipmap () const
Returns true if mipmapping is enabled.
Since
4.8
See also
setMipmap()
Definition at line 241 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObject::QGLFramebufferObject().
 {
     return d->mipmap;
 }
operator!=()
bool QGLFramebufferObjectFormat::operator!= (const QGLFramebufferObjectFormat & other) const
Returns false if all the options of this framebuffer object format are the same as other; otherwise returns true.
Definition at line 350 of file qglframebufferobject.cpp.
 {
     return !(*this == other);
 }
operator=()
QGLFramebufferObjectFormat & QGLFramebufferObjectFormat::operator= (const QGLFramebufferObjectFormat & other)
Assigns other to this object.
Definition at line 157 of file qglframebufferobject.cpp.
 {
     if (d != other.d) {
         other.d->ref.ref();
         if (!d->ref.deref())
             delete d;
         d = other.d;
     }
     return *this;
 }
operator==()
bool QGLFramebufferObjectFormat::operator== (const QGLFramebufferObjectFormat & other) const
Returns true if all the options of this framebuffer object format are the same as other; otherwise returns false.
Definition at line 338 of file qglframebufferobject.cpp.
 {
     if (d == other.d)
         return true;
     else
         return d->equals(other.d);
 }
samples()
int QGLFramebufferObjectFormat::samples () const
Returns the number of samples per pixel if a framebuffer object is a multisample framebuffer object.
Otherwise, returns 0. The default value is 0.
See also
setSamples()
Definition at line 203 of file qglframebufferobject.cpp.
Referenced by QGLWindowSurface::flush(), QGLFramebufferObject::QGLFramebufferObject(), setSamples(), and QGLWindowSurface::updateGeometry().
 {
     return d->samples;
 }
setAttachment()
void QGLFramebufferObjectFormat::setAttachment (QGLFramebufferObject::Attachment attachment)
Sets the attachment configuration of a framebuffer object to attachment.
See also
attachment()
Definition at line 251 of file qglframebufferobject.cpp.
Referenced by QGLPixmapData::paintEngine(), ShaderEffectSource::updateBackbuffer(), and QGLWindowSurface::updateGeometry().
 {
     detach();
     d->attachment = attachment;
 }
setInternalTextureFormat()
void QGLFramebufferObjectFormat::setInternalTextureFormat (GLenum internalTextureFormat)
Sets the internal format of a framebuffer object's texture or multisample framebuffer object's color buffer to internalTextureFormat.
See also
internalTextureFormat()
Definition at line 299 of file qglframebufferobject.cpp.
Referenced by internalTextureFormat(), QGLPixmapData::paintEngine(), ShaderEffectSource::updateBackbuffer(), and QGLWindowSurface::updateGeometry().
 {
     detach();
     d->internal_format = internalTextureFormat;
 }
setMipmap()
void QGLFramebufferObjectFormat::setMipmap (bool enabled)
Enables mipmapping if enabled is true; otherwise disables it.
Since
4.8
Mipmapping is disabled by default.
If mipmapping is enabled, additional memory will be allocated for the mipmap levels. The mipmap levels can be updated by binding the texture and calling glGenerateMipmap(). Mipmapping cannot be enabled for multisampled framebuffer objects.
See also
mipmap(), QGLFramebufferObject::texture()
Definition at line 225 of file qglframebufferobject.cpp.
 {
     detach();
     d->mipmap = enabled;
 }
setSamples()
void QGLFramebufferObjectFormat::setSamples (int samples)
Sets the number of samples per pixel for a multisample framebuffer object to samples.
The default sample count of 0 represents a regular non-multisample framebuffer object.
If the desired amount of samples per pixel is not supported by the hardware then the maximum number of samples per pixel will be used. Note that multisample framebuffer objects can not be bound as textures. Also, the GL_EXT_framebuffer_multisample extension is required to create a framebuffer with more than one sample per pixel.
See also
samples()
Definition at line 190 of file qglframebufferobject.cpp.
Referenced by QGLPixmapData::paintEngine(), and QGLWindowSurface::updateGeometry().
 {
     detach();
     d->samples = samples;
 }
setTextureTarget()
void QGLFramebufferObjectFormat::setTextureTarget (GLenum target)
Sets the texture target of the texture attached to a framebuffer object to target.
Ignored for multisample framebuffer objects.
See also
textureTarget(), samples()
Definition at line 274 of file qglframebufferobject.cpp.
Referenced by internalTextureFormat(), and QGLWindowSurface::updateGeometry().
 {
     detach();
     d->target = target;
 }
textureTarget()
GLenum QGLFramebufferObjectFormat::textureTarget () const
Returns the texture target of the texture attached to a framebuffer object.
Ignored for multisample framebuffer objects. The default is GL_TEXTURE_2D.
See also
setTextureTarget(), samples()
Definition at line 287 of file qglframebufferobject.cpp.
Referenced by QGLFramebufferObject::QGLFramebufferObject().
 {
     return d->target;
 }
Properties
d
QGLFramebufferObjectFormatPrivate* QGLFramebufferObjectFormat::d private
Definition at line 172 of file qglframebufferobject.h.
Referenced by attachment(), detach(), internalTextureFormat(), mipmap(), operator=(), operator==(), QGLFramebufferObjectFormat(), samples(), setAttachment(), setInternalTextureFormat(), setMipmap(), setSamples(), setTextureTarget(), textureTarget(), and ~QGLFramebufferObjectFormat().
The documentation for this class was generated from the following files:
/src/opengl/qglframebufferobject.h
/src/opengl/qglframebufferobject.cpp