Qt 4.8: QWindowsXPStyle Class Reference
QWindowsXPStyle Class Reference
The QWindowsXPStyle class provides a Microsoft Windows XP-like look and feel.
#include <qwindowsxpstyle.h>
Public Functions
void drawComplexControl (ComplexControl cc, const QStyleOptionComplex *option, QPainter *p, const QWidget *widget=0) const
Reimplemented Function
void drawControl (ControlElement element, const QStyleOption *option, QPainter *p, const QWidget *wwidget=0) const
Reimplemented Function
void drawPrimitive (PrimitiveElement pe, const QStyleOption *option, QPainter *p, const QWidget *widget=0) const
Reimplemented Function
int pixelMetric (PixelMetric pm, const QStyleOption *option=0, const QWidget *widget=0) const
Reimplemented Function
void polish (QApplication *)
Reimplemented Function
void polish (QWidget *)
Reimplemented Function
void polish (QPalette &)
Reimplemented Function
QWindowsXPStyle ()
Constructs a QWindowsStyle.
QWindowsXPStyle (QWindowsXPStylePrivate &dd)
Constructs a QWindowsXPStyle object.
QSize sizeFromContents (ContentsType ct, const QStyleOption *option, const QSize &contentsSize, const QWidget *widget=0) const
Reimplemented Function
QPalette standardPalette () const
Reimplemented Function
QPixmap standardPixmap (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget=0) const
Reimplemented Function
int styleHint (StyleHint hint, const QStyleOption *option=0, const QWidget *widget=0, QStyleHintReturn *returnData=0) const
Reimplemented Function
QRect subControlRect (ComplexControl cc, const QStyleOptionComplex *option, SubControl sc, const QWidget *widget=0) const
Reimplemented Function
QRect subElementRect (SubElement r, const QStyleOption *option, const QWidget *widget=0) const
Reimplemented Function
void unpolish (QApplication *)
Reimplemented Function
void unpolish (QWidget *)
Reimplemented Function
~QWindowsXPStyle ()
Destroys the style.
Public Functions inherited from QWindowsStyle
QWindowsStyle ()
Constructs a QWindowsStyle object.
~QWindowsStyle ()
Destroys the QWindowsStyle object.
Public Functions inherited from QCommonStyle
QPixmap generatedIconPixmap (QIcon::Mode iconMode, const QPixmap &pixmap, const QStyleOption *opt) const
Reimplemented Function
SubControl hitTestComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, const QPoint &pt, const QWidget *w=0) const
Reimplemented Function
QCommonStyle ()
Constructs a QCommonStyle.
~QCommonStyle ()
Destroys the style.
Public Functions inherited from QStyle
int combinedLayoutSpacing (QSizePolicy::ControlTypes controls1, QSizePolicy::ControlTypes controls2, Qt::Orientation orientation, QStyleOption *option=0, QWidget *widget=0) const
Returns the spacing that should be used between controls1 and controls2 in a layout.
virtual void drawItemPixmap (QPainter *painter, const QRect &rect, int alignment, const QPixmap &pixmap) const
Draws the given pixmap in the specified rectangle, according to the specified alignment, using the provided painter.
virtual void drawItemText (QPainter *painter, const QRect &rect, int flags, const QPalette &pal, bool enabled, const QString &text, QPalette::ColorRole textRole=QPalette::NoRole) const
Draws the given text in the specified rectangle using the provided painter and palette.
virtual QRect itemPixmapRect (const QRect &r, int flags, const QPixmap &pixmap) const
Returns the area within the given rectangle in which to draw the specified pixmap according to the defined alignment.
virtual QRect itemTextRect (const QFontMetrics &fm, const QRect &r, int flags, bool enabled, const QString &text) const
Returns the area within the given rectangle in which to draw the provided text according to the specified font metrics and alignment.
int layoutSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
Returns the spacing that should be used between control1 and control2 in a layout.
const QStyle * proxy () const
QStyle ()
Constructs a style object.
QIcon standardIcon (StandardPixmap standardIcon, const QStyleOption *option=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
virtual ~QStyle ()
Destroys the style object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget=0) const
Protected Slots inherited from QWindowsStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget=0) const
Protected Slots inherited from QCommonStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Protected Slots inherited from QStyle
int layoutSpacingImplementation (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
This slot is called by layoutSpacing() to determine the spacing that should be used between control1 and control2 in a layout.
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
Properties
void * reserved
Friends
class QStyleFactory
Additional Inherited Members
Public Types inherited from QStyle
enum ComplexControl {
CC_SpinBox, CC_ComboBox, CC_ScrollBar, CC_Slider,
CC_ToolButton, CC_TitleBar, CC_Q3ListView, CC_Dial,
CC_GroupBox, CC_MdiControls, CC_CustomBase = 0xf0000000
}
This enum describes the available complex controls.
enum ContentsType {
CT_PushButton, CT_CheckBox, CT_RadioButton, CT_ToolButton,
CT_ComboBox, CT_Splitter, CT_Q3DockWindow, CT_ProgressBar,
CT_MenuItem, CT_MenuBarItem, CT_MenuBar, CT_Menu,
CT_TabBarTab, CT_Slider, CT_ScrollBar, CT_Q3Header,
CT_LineEdit, CT_SpinBox, CT_SizeGrip, CT_TabWidget,
CT_DialogButtons, CT_HeaderSection, CT_GroupBox, CT_MdiControls,
CT_ItemViewItem, CT_CustomBase = 0xf0000000
}
This enum describes the available contents types.
enum ControlElement {
CE_PushButton, CE_PushButtonBevel, CE_PushButtonLabel, CE_CheckBox,
CE_CheckBoxLabel, CE_RadioButton, CE_RadioButtonLabel, CE_TabBarTab,
CE_TabBarTabShape, CE_TabBarTabLabel, CE_ProgressBar, CE_ProgressBarGroove,
CE_ProgressBarContents, CE_ProgressBarLabel, CE_MenuItem, CE_MenuScroller,
CE_MenuVMargin, CE_MenuHMargin, CE_MenuTearoff, CE_MenuEmptyArea,
CE_MenuBarItem, CE_MenuBarEmptyArea, CE_ToolButtonLabel, CE_Header,
CE_HeaderSection, CE_HeaderLabel, CE_Q3DockWindowEmptyArea, CE_ToolBoxTab,
CE_SizeGrip, CE_Splitter, CE_RubberBand, CE_DockWidgetTitle,
CE_ScrollBarAddLine, CE_ScrollBarSubLine, CE_ScrollBarAddPage, CE_ScrollBarSubPage,
CE_ScrollBarSlider, CE_ScrollBarFirst, CE_ScrollBarLast, CE_FocusFrame,
CE_ComboBoxLabel, CE_ToolBar, CE_ToolBoxTabShape, CE_ToolBoxTabLabel,
CE_HeaderEmptyArea, CE_ColumnViewGrip, CE_ItemViewItem, CE_ShapedFrame,
CE_CustomBase = 0xf0000000
}
This enum represents a control element.
enum PixelMetric {
PM_ButtonMargin, PM_ButtonDefaultIndicator, PM_MenuButtonIndicator, PM_ButtonShiftHorizontal,
PM_ButtonShiftVertical, PM_DefaultFrameWidth, PM_SpinBoxFrameWidth, PM_ComboBoxFrameWidth,
PM_MaximumDragDistance, PM_ScrollBarExtent, PM_ScrollBarSliderMin, PM_SliderThickness,
PM_SliderControlThickness, PM_SliderLength, PM_SliderTickmarkOffset, PM_SliderSpaceAvailable,
PM_DockWidgetSeparatorExtent, PM_DockWidgetHandleExtent, PM_DockWidgetFrameWidth, PM_TabBarTabOverlap,
PM_TabBarTabHSpace, PM_TabBarTabVSpace, PM_TabBarBaseHeight, PM_TabBarBaseOverlap,
PM_ProgressBarChunkWidth, PM_SplitterWidth, PM_TitleBarHeight, PM_MenuScrollerHeight,
PM_MenuHMargin, PM_MenuVMargin, PM_MenuPanelWidth, PM_MenuTearoffHeight,
PM_MenuDesktopFrameWidth, PM_MenuBarPanelWidth, PM_MenuBarItemSpacing, PM_MenuBarVMargin,
PM_MenuBarHMargin, PM_IndicatorWidth, PM_IndicatorHeight, PM_ExclusiveIndicatorWidth,
PM_ExclusiveIndicatorHeight, PM_CheckListButtonSize, PM_CheckListControllerSize, PM_DialogButtonsSeparator,
PM_DialogButtonsButtonWidth, PM_DialogButtonsButtonHeight, PM_MdiSubWindowFrameWidth, PM_MDIFrameWidth = PM_MdiSubWindowFrameWidth,
PM_MdiSubWindowMinimizedWidth, PM_MDIMinimizedWidth = PM_MdiSubWindowMinimizedWidth, PM_HeaderMargin, PM_HeaderMarkSize,
PM_HeaderGripMargin, PM_TabBarTabShiftHorizontal, PM_TabBarTabShiftVertical, PM_TabBarScrollButtonWidth,
PM_ToolBarFrameWidth, PM_ToolBarHandleExtent, PM_ToolBarItemSpacing, PM_ToolBarItemMargin,
PM_ToolBarSeparatorExtent, PM_ToolBarExtensionExtent, PM_SpinBoxSliderHeight, PM_DefaultTopLevelMargin,
PM_DefaultChildMargin, PM_DefaultLayoutSpacing, PM_ToolBarIconSize, PM_ListViewIconSize,
PM_IconViewIconSize, PM_SmallIconSize, PM_LargeIconSize, PM_FocusFrameVMargin,
PM_FocusFrameHMargin, PM_ToolTipLabelFrameWidth, PM_CheckBoxLabelSpacing, PM_TabBarIconSize,
PM_SizeGripSize, PM_DockWidgetTitleMargin, PM_MessageBoxIconSize, PM_ButtonIconSize,
PM_DockWidgetTitleBarButtonMargin, PM_RadioButtonLabelSpacing, PM_LayoutLeftMargin, PM_LayoutTopMargin,
PM_LayoutRightMargin, PM_LayoutBottomMargin, PM_LayoutHorizontalSpacing, PM_LayoutVerticalSpacing,
PM_TabBar_ScrollButtonOverlap, PM_TextCursorWidth, PM_TabCloseIndicatorWidth, PM_TabCloseIndicatorHeight,
PM_ScrollView_ScrollBarSpacing, PM_SubMenuOverlap, PM_CustomBase = 0xf0000000
}
This enum describes the various available pixel metrics.
enum PrimitiveElement {
PE_Q3CheckListController, PE_Q3CheckListExclusiveIndicator, PE_Q3CheckListIndicator, PE_Q3DockWindowSeparator,
PE_Q3Separator, PE_Frame, PE_FrameDefaultButton, PE_FrameDockWidget,
PE_FrameFocusRect, PE_FrameGroupBox, PE_FrameLineEdit, PE_FrameMenu,
PE_FrameStatusBar, PE_FrameStatusBarItem = PE_FrameStatusBar, PE_FrameTabWidget, PE_FrameWindow,
PE_FrameButtonBevel, PE_FrameButtonTool, PE_FrameTabBarBase, PE_PanelButtonCommand,
PE_PanelButtonBevel, PE_PanelButtonTool, PE_PanelMenuBar, PE_PanelToolBar,
PE_PanelLineEdit, PE_IndicatorArrowDown, PE_IndicatorArrowLeft, PE_IndicatorArrowRight,
PE_IndicatorArrowUp, PE_IndicatorBranch, PE_IndicatorButtonDropDown, PE_IndicatorViewItemCheck,
PE_IndicatorItemViewItemCheck = PE_IndicatorViewItemCheck, PE_IndicatorCheckBox, PE_IndicatorDockWidgetResizeHandle, PE_IndicatorHeaderArrow,
PE_IndicatorMenuCheckMark, PE_IndicatorProgressChunk, PE_IndicatorRadioButton, PE_IndicatorSpinDown,
PE_IndicatorSpinMinus, PE_IndicatorSpinPlus, PE_IndicatorSpinUp, PE_IndicatorToolBarHandle,
PE_IndicatorToolBarSeparator, PE_PanelTipLabel, PE_IndicatorTabTear, PE_PanelScrollAreaCorner,
PE_Widget, PE_IndicatorColumnViewArrow, PE_IndicatorItemViewItemDrop, PE_PanelItemViewItem,
PE_PanelItemViewRow, PE_PanelStatusBar, PE_IndicatorTabClose, PE_PanelMenu,
PE_CustomBase = 0xf000000
}
This enum describes the various primitive elements.
enum RequestSoftwareInputPanel { RSIP_OnMouseClickAndAlreadyFocused, RSIP_OnMouseClick }
This enum describes under what circumstances a software input panel will be requested by input capable widgets.
enum StandardPixmap {
SP_TitleBarMenuButton, SP_TitleBarMinButton, SP_TitleBarMaxButton, SP_TitleBarCloseButton,
SP_TitleBarNormalButton, SP_TitleBarShadeButton, SP_TitleBarUnshadeButton, SP_TitleBarContextHelpButton,
SP_DockWidgetCloseButton, SP_MessageBoxInformation, SP_MessageBoxWarning, SP_MessageBoxCritical,
SP_MessageBoxQuestion, SP_DesktopIcon, SP_TrashIcon, SP_ComputerIcon,
SP_DriveFDIcon, SP_DriveHDIcon, SP_DriveCDIcon, SP_DriveDVDIcon,
SP_DriveNetIcon, SP_DirOpenIcon, SP_DirClosedIcon, SP_DirLinkIcon,
SP_FileIcon, SP_FileLinkIcon, SP_ToolBarHorizontalExtensionButton, SP_ToolBarVerticalExtensionButton,
SP_FileDialogStart, SP_FileDialogEnd, SP_FileDialogToParent, SP_FileDialogNewFolder,
SP_FileDialogDetailedView, SP_FileDialogInfoView, SP_FileDialogContentsView, SP_FileDialogListView,
SP_FileDialogBack, SP_DirIcon, SP_DialogOkButton, SP_DialogCancelButton,
SP_DialogHelpButton, SP_DialogOpenButton, SP_DialogSaveButton, SP_DialogCloseButton,
SP_DialogApplyButton, SP_DialogResetButton, SP_DialogDiscardButton, SP_DialogYesButton,
SP_DialogNoButton, SP_ArrowUp, SP_ArrowDown, SP_ArrowLeft,
SP_ArrowRight, SP_ArrowBack, SP_ArrowForward, SP_DirHomeIcon,
SP_CommandLink, SP_VistaShield, SP_BrowserReload, SP_BrowserStop,
SP_MediaPlay, SP_MediaStop, SP_MediaPause, SP_MediaSkipForward,
SP_MediaSkipBackward, SP_MediaSeekForward, SP_MediaSeekBackward, SP_MediaVolume,
SP_MediaVolumeMuted, SP_CustomBase = 0xf0000000
}
This enum describes the available standard pixmaps.
enum StateFlag {
State_None = 0x00000000, State_Enabled = 0x00000001, State_Raised = 0x00000002, State_Sunken = 0x00000004,
State_Off = 0x00000008, State_NoChange = 0x00000010, State_On = 0x00000020, State_DownArrow = 0x00000040,
State_Horizontal = 0x00000080, State_HasFocus = 0x00000100, State_Top = 0x00000200, State_Bottom = 0x00000400,
State_FocusAtBorder = 0x00000800, State_AutoRaise = 0x00001000, State_MouseOver = 0x00002000, State_UpArrow = 0x00004000,
State_Selected = 0x00008000, State_Active = 0x00010000, State_Window = 0x00020000, State_Open = 0x00040000,
State_Children = 0x00080000, State_Item = 0x00100000, State_Sibling = 0x00200000, State_Editing = 0x00400000,
State_KeyboardFocusChange = 0x00800000, State_ReadOnly = 0x02000000, State_Small = 0x04000000, State_Mini = 0x08000000
}
This enum describes flags that are used when drawing primitive elements.
enum StyleHint {
SH_EtchDisabledText, SH_DitherDisabledText, SH_ScrollBar_MiddleClickAbsolutePosition, SH_ScrollBar_ScrollWhenPointerLeavesControl,
SH_TabBar_SelectMouseType, SH_TabBar_Alignment, SH_Header_ArrowAlignment, SH_Slider_SnapToValue,
SH_Slider_SloppyKeyEvents, SH_ProgressDialog_CenterCancelButton, SH_ProgressDialog_TextLabelAlignment, SH_PrintDialog_RightAlignButtons,
SH_MainWindow_SpaceBelowMenuBar, SH_FontDialog_SelectAssociatedText, SH_Menu_AllowActiveAndDisabled, SH_Menu_SpaceActivatesItem,
SH_Menu_SubMenuPopupDelay, SH_ScrollView_FrameOnlyAroundContents, SH_MenuBar_AltKeyNavigation, SH_ComboBox_ListMouseTracking,
SH_Menu_MouseTracking, SH_MenuBar_MouseTracking, SH_ItemView_ChangeHighlightOnFocus, SH_Widget_ShareActivation,
SH_Workspace_FillSpaceOnMaximize, SH_ComboBox_Popup, SH_TitleBar_NoBorder, SH_Slider_StopMouseOverSlider,
SH_ScrollBar_StopMouseOverSlider = SH_Slider_StopMouseOverSlider, SH_BlinkCursorWhenTextSelected, SH_RichText_FullWidthSelection, SH_Menu_Scrollable,
SH_GroupBox_TextLabelVerticalAlignment, SH_GroupBox_TextLabelColor, SH_Menu_SloppySubMenus, SH_Table_GridLineColor,
SH_LineEdit_PasswordCharacter, SH_DialogButtons_DefaultButton, SH_ToolBox_SelectedPageTitleBold, SH_TabBar_PreferNoArrows,
SH_ScrollBar_LeftClickAbsolutePosition, SH_Q3ListViewExpand_SelectMouseType, SH_UnderlineShortcut, SH_SpinBox_AnimateButton,
SH_SpinBox_KeyPressAutoRepeatRate, SH_SpinBox_ClickAutoRepeatRate, SH_Menu_FillScreenWithScroll, SH_ToolTipLabel_Opacity,
SH_DrawMenuBarSeparator, SH_TitleBar_ModifyNotification, SH_Button_FocusPolicy, SH_MenuBar_DismissOnSecondClick,
SH_MessageBox_UseBorderForButtonSpacing, SH_TitleBar_AutoRaise, SH_ToolButton_PopupDelay, SH_FocusFrame_Mask,
SH_RubberBand_Mask, SH_WindowFrame_Mask, SH_SpinControls_DisableOnBounds, SH_Dial_BackgroundRole,
SH_ComboBox_LayoutDirection, SH_ItemView_EllipsisLocation, SH_ItemView_ShowDecorationSelected, SH_ItemView_ActivateItemOnSingleClick,
SH_ScrollBar_ContextMenu, SH_ScrollBar_RollBetweenButtons, SH_Slider_AbsoluteSetButtons, SH_Slider_PageSetButtons,
SH_Menu_KeyboardSearch, SH_TabBar_ElideMode, SH_DialogButtonLayout, SH_ComboBox_PopupFrameStyle,
SH_MessageBox_TextInteractionFlags, SH_DialogButtonBox_ButtonsHaveIcons, SH_SpellCheckUnderlineStyle, SH_MessageBox_CenterButtons,
SH_Menu_SelectionWrap, SH_ItemView_MovementWithoutUpdatingSelection, SH_ToolTip_Mask, SH_FocusFrame_AboveWidget,
SH_TextControl_FocusIndicatorTextCharFormat, SH_WizardStyle, SH_ItemView_ArrowKeysNavigateIntoChildren, SH_Menu_Mask,
SH_Menu_FlashTriggeredItem, SH_Menu_FadeOutOnHide, SH_SpinBox_ClickAutoRepeatThreshold, SH_ItemView_PaintAlternatingRowColorsForEmptyArea,
SH_FormLayoutWrapPolicy, SH_TabWidget_DefaultTabPosition, SH_ToolBar_Movable, SH_FormLayoutFieldGrowthPolicy,
SH_FormLayoutFormAlignment, SH_FormLayoutLabelAlignment, SH_ItemView_DrawDelegateFrame, SH_TabBar_CloseButtonPosition,
SH_DockWidget_ButtonsHaveFrame, SH_ToolButtonStyle, SH_RequestSoftwareInputPanel, SH_CustomBase = 0xf0000000
}
This enum describes the available style hints.
enum SubControl {
SC_None = 0x00000000, SC_ScrollBarAddLine = 0x00000001, SC_ScrollBarSubLine = 0x00000002, SC_ScrollBarAddPage = 0x00000004,
SC_ScrollBarSubPage = 0x00000008, SC_ScrollBarFirst = 0x00000010, SC_ScrollBarLast = 0x00000020, SC_ScrollBarSlider = 0x00000040,
SC_ScrollBarGroove = 0x00000080, SC_SpinBoxUp = 0x00000001, SC_SpinBoxDown = 0x00000002, SC_SpinBoxFrame = 0x00000004,
SC_SpinBoxEditField = 0x00000008, SC_ComboBoxFrame = 0x00000001, SC_ComboBoxEditField = 0x00000002, SC_ComboBoxArrow = 0x00000004,
SC_ComboBoxListBoxPopup = 0x00000008, SC_SliderGroove = 0x00000001, SC_SliderHandle = 0x00000002, SC_SliderTickmarks = 0x00000004,
SC_ToolButton = 0x00000001, SC_ToolButtonMenu = 0x00000002, SC_TitleBarSysMenu = 0x00000001, SC_TitleBarMinButton = 0x00000002,
SC_TitleBarMaxButton = 0x00000004, SC_TitleBarCloseButton = 0x00000008, SC_TitleBarNormalButton = 0x00000010, SC_TitleBarShadeButton = 0x00000020,
SC_TitleBarUnshadeButton = 0x00000040, SC_TitleBarContextHelpButton = 0x00000080, SC_TitleBarLabel = 0x00000100, SC_Q3ListView = 0x00000001,
SC_Q3ListViewBranch = 0x00000002, SC_Q3ListViewExpand = 0x00000004, SC_DialGroove = 0x00000001, SC_DialHandle = 0x00000002,
SC_DialTickmarks = 0x00000004, SC_GroupBoxCheckBox = 0x00000001, SC_GroupBoxLabel = 0x00000002, SC_GroupBoxContents = 0x00000004,
SC_GroupBoxFrame = 0x00000008, SC_MdiMinButton = 0x00000001, SC_MdiNormalButton = 0x00000002, SC_MdiCloseButton = 0x00000004,
SC_CustomBase = 0xf0000000, SC_All = 0xffffffff
}
This enum describes the available sub controls.
enum SubElement {
SE_PushButtonContents, SE_PushButtonFocusRect, SE_CheckBoxIndicator, SE_CheckBoxContents,
SE_CheckBoxFocusRect, SE_CheckBoxClickRect, SE_RadioButtonIndicator, SE_RadioButtonContents,
SE_RadioButtonFocusRect, SE_RadioButtonClickRect, SE_ComboBoxFocusRect, SE_SliderFocusRect,
SE_Q3DockWindowHandleRect, SE_ProgressBarGroove, SE_ProgressBarContents, SE_ProgressBarLabel,
SE_DialogButtonAccept, SE_DialogButtonReject, SE_DialogButtonApply, SE_DialogButtonHelp,
SE_DialogButtonAll, SE_DialogButtonAbort, SE_DialogButtonIgnore, SE_DialogButtonRetry,
SE_DialogButtonCustom, SE_ToolBoxTabContents, SE_HeaderLabel, SE_HeaderArrow,
SE_TabWidgetTabBar, SE_TabWidgetTabPane, SE_TabWidgetTabContents, SE_TabWidgetLeftCorner,
SE_TabWidgetRightCorner, SE_ViewItemCheckIndicator, SE_ItemViewItemCheckIndicator = SE_ViewItemCheckIndicator, SE_TabBarTearIndicator,
SE_TreeViewDisclosureItem, SE_LineEditContents, SE_FrameContents, SE_DockWidgetCloseButton,
SE_DockWidgetFloatButton, SE_DockWidgetTitleBarText, SE_DockWidgetIcon, SE_CheckBoxLayoutItem,
SE_ComboBoxLayoutItem, SE_DateTimeEditLayoutItem, SE_DialogButtonBoxLayoutItem, SE_LabelLayoutItem,
SE_ProgressBarLayoutItem, SE_PushButtonLayoutItem, SE_RadioButtonLayoutItem, SE_SliderLayoutItem,
SE_SpinBoxLayoutItem, SE_ToolButtonLayoutItem, SE_FrameLayoutItem, SE_GroupBoxLayoutItem,
SE_TabWidgetLayoutItem, SE_ItemViewItemDecoration, SE_ItemViewItemText, SE_ItemViewItemFocusRect,
SE_TabBarTabLeftButton, SE_TabBarTabRightButton, SE_TabBarTabText, SE_ShapedFrameContents,
SE_ToolBarHandle, SE_CustomBase = 0xf0000000
}
This enum represents a sub-area of a widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QStyle
static QRect alignedRect (Qt::LayoutDirection direction, Qt::Alignment alignment, const QSize &size, const QRect &rectangle)
Returns a new rectangle of the specified size that is aligned to the given rectangle according to the specified alignment and direction.
static int sliderPositionFromValue (int min, int max, int val, int space, bool upsideDown=false)
Converts the given logicalValue to a pixel position.
static int sliderValueFromPosition (int min, int max, int pos, int space, bool upsideDown=false)
Converts the given pixel position to a logical value.
static Qt::Alignment visualAlignment (Qt::LayoutDirection direction, Qt::Alignment alignment)
Transforms an alignment of Qt::AlignLeft or Qt::AlignRight without Qt::AlignAbsolute into Qt::AlignLeft or Qt::AlignRight with Qt::AlignAbsolute according to the layout direction.
static QPoint visualPos (Qt::LayoutDirection direction, const QRect &boundingRect, const QPoint &logicalPos)
Returns the given logicalPosition converted to screen coordinates based on the specified direction.
static QRect visualRect (Qt::LayoutDirection direction, const QRect &boundingRect, const QRect &logicalRect)
Returns the given logicalRectangle converted to screen coordinates based on the specified direction.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QWindowsStyle
bool eventFilter (QObject *o, QEvent *e)
Reimplemented Function
QWindowsStyle (QWindowsStylePrivate &dd)
Constructs a QWindowsStyle object.
void timerEvent (QTimerEvent *event)
Reimplemented Function
Protected Functions inherited from QCommonStyle
QCommonStyle (QCommonStylePrivate &dd)
Protected Functions inherited from QStyle
QStyle (QStylePrivate &dd)
Constructs a style object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QWindowsXPStyle class provides a Microsoft Windows XP-like look and feel.
Warning
This style is only available on the Windows XP platform because it makes use of Windows XP's style engine.
Most of the functions are documented in the base classes QWindowsStyle, QCommonStyle, and QStyle, but the QWindowsXPStyle overloads of drawComplexControl(), drawControl(), drawControlMask(), drawPrimitive(), proxy()->subControlRect(), and sizeFromContents(), are documented here.
See also
QMacStyle, QWindowsStyle, QPlastiqueStyle, QCDEStyle, QMotifStyle
Definition at line 56 of file qwindowsxpstyle.h.
Constructors and Destructors
QWindowsXPStyle() [1/2]
QWindowsXPStyle::QWindowsXPStyle ()
Constructs a QWindowsStyle.
Definition at line 1112 of file qwindowsxpstyle.cpp.
     : QWindowsStyle(*new QWindowsXPStylePrivate)
 {
 }
QWindowsXPStyle() [2/2]
QWindowsXPStyle::QWindowsXPStyle (QWindowsXPStylePrivate & dd)
Constructs a QWindowsXPStyle object.
Warning
This function is not part of the public interface.
Definition at line 4044 of file qwindowsxpstyle.cpp.
                                                            : QWindowsStyle(dd)
 {
 }
~QWindowsXPStyle()
QWindowsXPStyle::~QWindowsXPStyle ()
Destroys the style.
Definition at line 1120 of file qwindowsxpstyle.cpp.
 {
 }
Functions
drawComplexControl()
void QWindowsXPStyle::drawComplexControl (ComplexControl cc, const QStyleOptionComplex * option, QPainter * p, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 2491 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl().
 {
     QWindowsXPStylePrivate *d = const_cast<QWindowsXPStylePrivate*>(d_func());
     if (!QWindowsXPStylePrivate::useXP()) {
         QWindowsStyle::drawComplexControl(cc, option, p, widget);
         return;
     }
     State flags = option->state;
     SubControls sub = option->subControls;
     QRect r = option->rect;
     int partId = 0;
     int stateId = 0;
     if (widget && widget->testAttribute(Qt::WA_UnderMouse) && widget->isActiveWindow())
         flags |= State_MouseOver;
     switch (cc) {
 #ifndef QT_NO_SPINBOX
     case CC_SpinBox:
         if (const QStyleOptionSpinBox *sb = qstyleoption_cast<const QStyleOptionSpinBox *>(option))
         {
             XPThemeData theme(widget, p, QLatin1String("SPIN"));
             if (sb->frame && (sub & SC_SpinBoxFrame)) {
                 partId = EP_EDITTEXT;
                 if (!(flags & State_Enabled))
                     stateId = ETS_DISABLED;
                 else if (flags & State_HasFocus)
                     stateId = ETS_FOCUSED;
                 else
                     stateId = ETS_NORMAL;
                 XPThemeData ftheme(widget, p, QLatin1String("EDIT"), partId, stateId, r);
                 ftheme.noContent = true;
                 d->drawBackground(ftheme);
             }
             if (sub & SC_SpinBoxUp) {
                 theme.rect = proxy()->subControlRect(CC_SpinBox, option, SC_SpinBoxUp, widget);
                 partId = SPNP_UP;
                 if (!(sb->stepEnabled & QAbstractSpinBox::StepUpEnabled) || !(flags & State_Enabled))
                     stateId = UPS_DISABLED;
                 else if (sb->activeSubControls == SC_SpinBoxUp && (sb->state & State_Sunken))
                     stateId = UPS_PRESSED;
                 else if (sb->activeSubControls == SC_SpinBoxUp && (sb->state & State_MouseOver))
                     stateId = UPS_HOT;
                 else
                     stateId = UPS_NORMAL;
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             }
             if (sub & SC_SpinBoxDown) {
                 theme.rect = proxy()->subControlRect(CC_SpinBox, option, SC_SpinBoxDown, widget);
                 partId = SPNP_DOWN;
                 if (!(sb->stepEnabled & QAbstractSpinBox::StepDownEnabled) || !(flags & State_Enabled))
                     stateId = DNS_DISABLED;
                 else if (sb->activeSubControls == SC_SpinBoxDown && (sb->state & State_Sunken))
                     stateId = DNS_PRESSED;
                 else if (sb->activeSubControls == SC_SpinBoxDown && (sb->state & State_MouseOver))
                     stateId = DNS_HOT;
                 else
                     stateId = DNS_NORMAL;
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             }
         }
         break;
 #endif // QT_NO_SPINBOX
 #ifndef QT_NO_COMBOBOX
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cmb = qstyleoption_cast<const QStyleOptionComboBox *>(option))
         {
             if (sub & SC_ComboBoxEditField) {
                 if (cmb->frame) {
                     partId = EP_EDITTEXT;
                     if (!(flags & State_Enabled))
                         stateId = ETS_DISABLED;
                     else if (flags & State_HasFocus)
                         stateId = ETS_FOCUSED;
                     else
                         stateId = ETS_NORMAL;
                     XPThemeData theme(widget, p, QLatin1String("EDIT"), partId, stateId, r);
                     d->drawBackground(theme);
                 } else {
                     QBrush editBrush = cmb->palette.brush(QPalette::Base);
                     p->fillRect(option->rect, editBrush);
                 }
                 if (!cmb->editable) {
                     QRect re = proxy()->subControlRect(CC_ComboBox, option, SC_ComboBoxEditField, widget);
                     if (option->state & State_HasFocus) {
                         p->fillRect(re, option->palette.highlight());
                         p->setPen(option->palette.highlightedText().color());
                         p->setBackground(option->palette.highlight());
                     } else {
                         p->fillRect(re, option->palette.base());
                         p->setPen(option->palette.text().color());
                         p->setBackground(option->palette.base());
                     }
                 }
             }
             if (sub & SC_ComboBoxArrow) {
                 XPThemeData theme(widget, p, QLatin1String("COMBOBOX"));
                 theme.rect = proxy()->subControlRect(CC_ComboBox, option, SC_ComboBoxArrow, widget);
                 partId = CP_DROPDOWNBUTTON;
                 if (!(flags & State_Enabled))
                     stateId = CBXS_DISABLED;
                 else if (cmb->activeSubControls == SC_ComboBoxArrow && (cmb->state & State_Sunken))
                     stateId = CBXS_PRESSED;
                 else if (cmb->activeSubControls == SC_ComboBoxArrow && (cmb->state & State_MouseOver))
                     stateId = CBXS_HOT;
                 else
                     stateId = CBXS_NORMAL;
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             }
         }
         break;
 #endif // QT_NO_COMBOBOX
     case CC_ScrollBar:
         if (const QStyleOptionSlider *scrollbar = qstyleoption_cast<const QStyleOptionSlider *>(option))
         {
             XPThemeData theme(widget, p, QLatin1String("SCROLLBAR"));
             bool maxedOut = (scrollbar->maximum == scrollbar->minimum);
             if (maxedOut)
                 flags &= ~State_Enabled;
             bool isHorz = flags & State_Horizontal;
             bool isRTL  = option->direction == Qt::RightToLeft;
             if (sub & SC_ScrollBarAddLine) {
                 theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarAddLine, widget);
                 partId = SBP_ARROWBTN;
                 if (!(flags & State_Enabled))
                     stateId = (isHorz ? (isRTL ? ABS_LEFTDISABLED : ABS_RIGHTDISABLED) : ABS_DOWNDISABLED);
                 else if (scrollbar->activeSubControls & SC_ScrollBarAddLine && (scrollbar->state & State_Sunken))
                     stateId = (isHorz ? (isRTL ? ABS_LEFTPRESSED : ABS_RIGHTPRESSED) : ABS_DOWNPRESSED);
                 else if (scrollbar->activeSubControls & SC_ScrollBarAddLine && (scrollbar->state & State_MouseOver))
                     stateId = (isHorz ? (isRTL ? ABS_LEFTHOT : ABS_RIGHTHOT) : ABS_DOWNHOT);
                 else
                     stateId = (isHorz ? (isRTL ? ABS_LEFTNORMAL : ABS_RIGHTNORMAL) : ABS_DOWNNORMAL);
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             }
             if (sub & SC_ScrollBarSubLine) {
                 theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarSubLine, widget);
                 partId = SBP_ARROWBTN;
                 if (!(flags & State_Enabled))
                     stateId = (isHorz ? (isRTL ? ABS_RIGHTDISABLED : ABS_LEFTDISABLED) : ABS_UPDISABLED);
                 else if (scrollbar->activeSubControls & SC_ScrollBarSubLine && (scrollbar->state & State_Sunken))
                     stateId = (isHorz ? (isRTL ? ABS_RIGHTPRESSED : ABS_LEFTPRESSED) : ABS_UPPRESSED);
                 else if (scrollbar->activeSubControls & SC_ScrollBarSubLine && (scrollbar->state & State_MouseOver))
                     stateId = (isHorz ? (isRTL ? ABS_RIGHTHOT : ABS_LEFTHOT) : ABS_UPHOT);
                 else
                     stateId = (isHorz ? (isRTL ? ABS_RIGHTNORMAL : ABS_LEFTNORMAL) : ABS_UPNORMAL);
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             }
             if (maxedOut) {
                 theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarSlider, widget);
                 theme.rect = theme.rect.united(proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarSubPage, widget));
                 theme.rect = theme.rect.united(proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarAddPage, widget));
                 partId = scrollbar->orientation == Qt::Horizontal ? SBP_LOWERTRACKHORZ : SBP_LOWERTRACKVERT;
                 stateId = SCRBS_DISABLED;
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             } else {
                 if (sub & SC_ScrollBarSubPage) {
                     theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarSubPage, widget);
                     partId = flags & State_Horizontal ? SBP_UPPERTRACKHORZ : SBP_UPPERTRACKVERT;
                     if (!(flags & State_Enabled))
                         stateId = SCRBS_DISABLED;
                     else if (scrollbar->activeSubControls & SC_ScrollBarSubPage && (scrollbar->state & State_Sunken))
                         stateId = SCRBS_PRESSED;
                     else if (scrollbar->activeSubControls & SC_ScrollBarSubPage && (scrollbar->state & State_MouseOver))
                         stateId = SCRBS_HOT;
                     else
                         stateId = SCRBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_ScrollBarAddPage) {
                     theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarAddPage, widget);
                     partId = flags & State_Horizontal ? SBP_LOWERTRACKHORZ : SBP_LOWERTRACKVERT;
                     if (!(flags & State_Enabled))
                         stateId = SCRBS_DISABLED;
                     else if (scrollbar->activeSubControls & SC_ScrollBarAddPage && (scrollbar->state & State_Sunken))
                         stateId = SCRBS_PRESSED;
                     else if (scrollbar->activeSubControls & SC_ScrollBarAddPage && (scrollbar->state & State_MouseOver))
                         stateId = SCRBS_HOT;
                     else
                         stateId = SCRBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_ScrollBarSlider) {
                     theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarSlider, widget);
                     if (!(flags & State_Enabled))
                         stateId = SCRBS_DISABLED;
                     else if (scrollbar->activeSubControls & SC_ScrollBarSlider && (scrollbar->state & State_Sunken))
                         stateId = SCRBS_PRESSED;
                     else if (scrollbar->activeSubControls & SC_ScrollBarSlider && (scrollbar->state & State_MouseOver))
                         stateId = SCRBS_HOT;
                     else
                         stateId = SCRBS_NORMAL;
                     // Draw handle
                     theme.rect = proxy()->subControlRect(CC_ScrollBar, option, SC_ScrollBarSlider, widget);
                     theme.partId = flags & State_Horizontal ? SBP_THUMBBTNHORZ : SBP_THUMBBTNVERT;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                     // Calculate rect of gripper
                     const int swidth = theme.rect.width();
                     const int sheight = theme.rect.height();
                     MARGINS contentsMargin;
                     RECT rect = theme.toRECT(theme.rect);
                     pGetThemeMargins(theme.handle(), 0, theme.partId, theme.stateId, TMT_SIZINGMARGINS, &rect, &contentsMargin);
                     SIZE size;
                     theme.partId = flags & State_Horizontal ? SBP_GRIPPERHORZ : SBP_GRIPPERVERT;
                     pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                     int gw = size.cx, gh = size.cy;
                     QRect gripperBounds;
                     if (flags & State_Horizontal && ((swidth - contentsMargin.cxLeftWidth - contentsMargin.cxRightWidth) > gw)) {
                         gripperBounds.setLeft(theme.rect.left() + swidth/2 - gw/2);
                         gripperBounds.setTop(theme.rect.top() + sheight/2 - gh/2);
                         gripperBounds.setWidth(gw);
                         gripperBounds.setHeight(gh);
                     } else if ((sheight - contentsMargin.cyTopHeight - contentsMargin.cyBottomHeight) > gh) {
                         gripperBounds.setLeft(theme.rect.left() + swidth/2 - gw/2);
                         gripperBounds.setTop(theme.rect.top() + sheight/2 - gh/2);
                         gripperBounds.setWidth(gw);
                         gripperBounds.setHeight(gh);
                     }
                     // Draw gripper if there is enough space
                     if (!gripperBounds.isEmpty()) {
                         p->save();
                         theme.rect = gripperBounds;
                         p->setClipRegion(d->region(theme));// Only change inside the region of the gripper
                         d->drawBackground(theme);          // Transparent gripper ontop of background
                         p->restore();
                     }
                 }
             }
         }
         break;
 #ifndef QT_NO_SLIDER
     case CC_Slider:
         if (const QStyleOptionSlider *slider = qstyleoption_cast<const QStyleOptionSlider *>(option))
         {
             XPThemeData theme(widget, p, QLatin1String("TRACKBAR"));
             QRect slrect = slider->rect;
             QRegion tickreg = slrect;
             if (sub & SC_SliderGroove) {
                 theme.rect = proxy()->subControlRect(CC_Slider, option, SC_SliderGroove, widget);
                 if (slider->orientation == Qt::Horizontal) {
                     partId = TKP_TRACK;
                     stateId = TRS_NORMAL;
                     theme.rect = QRect(slrect.left(), theme.rect.center().y() - 2, slrect.width(), 4);
                 } else {
                     partId = TKP_TRACKVERT;
                     stateId = TRVS_NORMAL;
                     theme.rect = QRect(theme.rect.center().x() - 2, slrect.top(), 4, slrect.height());
                 }
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
                 tickreg -= theme.rect;
             }
             if (sub & SC_SliderTickmarks) {
                 int tickOffset = proxy()->pixelMetric(PM_SliderTickmarkOffset, slider, widget);
                 int ticks = slider->tickPosition;
                 int thickness = proxy()->pixelMetric(PM_SliderControlThickness, slider, widget);
                 int len = proxy()->pixelMetric(PM_SliderLength, slider, widget);
                 int available = proxy()->pixelMetric(PM_SliderSpaceAvailable, slider, widget);
                 int interval = slider->tickInterval;
                 if (interval <= 0) {
                     interval = slider->singleStep;
                     if (QStyle::sliderPositionFromValue(slider->minimum, slider->maximum, interval,
                                                         available)
                         - QStyle::sliderPositionFromValue(slider->minimum, slider->maximum,
                                                           0, available) < 3)
                         interval = slider->pageStep;
                 }
                 if (!interval)
                     interval = 1;
                 int fudge = len / 2;
                 int pos;
                 int bothOffset = (ticks & QSlider::TicksAbove && ticks & QSlider::TicksBelow) ? 1 : 0;
                 p->setPen(d->sliderTickColor);
                 QVarLengthArray<QLine, 32> lines;
                 int v = slider->minimum;
                 while (v <= slider->maximum + 1) {
                     if (v == slider->maximum + 1 && interval == 1)
                         break;
                     const int v_ = qMin(v, slider->maximum);
                     int tickLength = (v_ == slider->minimum || v_ >= slider->maximum) ? 4 : 3;
                     pos = QStyle::sliderPositionFromValue(slider->minimum, slider->maximum,
                                                           v_, available) + fudge;
                     if (slider->orientation == Qt::Horizontal) {
                         if (ticks & QSlider::TicksAbove)
                             lines.append(QLine(pos, tickOffset - 1 - bothOffset,
                                                pos, tickOffset - 1 - bothOffset - tickLength));
                         if (ticks & QSlider::TicksBelow)
                             lines.append(QLine(pos, tickOffset + thickness + bothOffset,
                                                pos, tickOffset + thickness + bothOffset + tickLength));
                     } else {
                         if (ticks & QSlider::TicksAbove)
                             lines.append(QLine(tickOffset - 1 - bothOffset, pos,
                                                tickOffset - 1 - bothOffset - tickLength, pos));
                         if (ticks & QSlider::TicksBelow)
                             lines.append(QLine(tickOffset + thickness + bothOffset, pos,
                                                tickOffset + thickness + bothOffset + tickLength, pos));
                     }
                     // in the case where maximum is max int
                     int nextInterval = v + interval;
                     if (nextInterval < v)
                         break;
                     v = nextInterval;
                 }
                 if (lines.size() > 0) {
                     p->save();
                     p->translate(slrect.topLeft());
                     p->drawLines(lines.constData(), lines.size());
                     p->restore();
                 }
             }
             if (sub & SC_SliderHandle) {
                 theme.rect = proxy()->subControlRect(CC_Slider, option, SC_SliderHandle, widget);
                 if (slider->orientation == Qt::Horizontal) {
                     if (slider->tickPosition == QSlider::TicksAbove)
                         partId = TKP_THUMBTOP;
                     else if (slider->tickPosition == QSlider::TicksBelow)
                         partId = TKP_THUMBBOTTOM;
                     else
                         partId = TKP_THUMB;
                     if (!(slider->state & State_Enabled))
                         stateId = TUS_DISABLED;
                     else if (slider->activeSubControls & SC_SliderHandle && (slider->state & State_Sunken))
                         stateId = TUS_PRESSED;
                     else if (slider->activeSubControls & SC_SliderHandle && (slider->state & State_MouseOver))
                         stateId = TUS_HOT;
                     else if (flags & State_HasFocus)
                         stateId = TUS_FOCUSED;
                     else
                         stateId = TUS_NORMAL;
                 } else {
                     if (slider->tickPosition == QSlider::TicksLeft)
                         partId = TKP_THUMBLEFT;
                     else if (slider->tickPosition == QSlider::TicksRight)
                         partId = TKP_THUMBRIGHT;
                     else
                         partId = TKP_THUMBVERT;
                     if (!(slider->state & State_Enabled))
                         stateId = TUVS_DISABLED;
                     else if (slider->activeSubControls & SC_SliderHandle && (slider->state & State_Sunken))
                         stateId = TUVS_PRESSED;
                     else if (slider->activeSubControls & SC_SliderHandle && (slider->state & State_MouseOver))
                         stateId = TUVS_HOT;
                     else if (flags & State_HasFocus)
                         stateId = TUVS_FOCUSED;
                     else
                         stateId = TUVS_NORMAL;
                 }
                 theme.partId = partId;
                 theme.stateId = stateId;
                 d->drawBackground(theme);
             }
             if (slider->state & State_HasFocus) {
                 QStyleOptionFocusRect fropt;
                 fropt.QStyleOption::operator=(*slider);
                 fropt.rect = subElementRect(SE_SliderFocusRect, slider, widget);
                 proxy()->drawPrimitive(PE_FrameFocusRect, &fropt, p, widget);
             }
         }
         break;
 #endif
 #ifndef QT_NO_TOOLBUTTON
     case CC_ToolButton:
         if (const QStyleOptionToolButton *toolbutton
             = qstyleoption_cast<const QStyleOptionToolButton *>(option)) {
             QRect button, menuarea;
             button = proxy()->subControlRect(cc, toolbutton, SC_ToolButton, widget);
             menuarea = proxy()->subControlRect(cc, toolbutton, SC_ToolButtonMenu, widget);
             State bflags = toolbutton->state & ~State_Sunken;
             State mflags = bflags;
             bool autoRaise = flags & State_AutoRaise;
             if (autoRaise) {
                 if (!(bflags & State_MouseOver) || !(bflags & State_Enabled)) {
                     bflags &= ~State_Raised;
                 }
             }
             if (toolbutton->state & State_Sunken) {
                 if (toolbutton->activeSubControls & SC_ToolButton) {
                     bflags |= State_Sunken;
                     mflags |= State_MouseOver | State_Sunken;
                 } else if (toolbutton->activeSubControls & SC_ToolButtonMenu) {
                     mflags |= State_Sunken;
                     bflags |= State_MouseOver;
                 }
             }
             QStyleOption tool(0);
             tool.palette = toolbutton->palette;
             if (toolbutton->subControls & SC_ToolButton) {
                 if (flags & (State_Sunken | State_On | State_Raised) || !autoRaise) {
                     if (toolbutton->features & QStyleOptionToolButton::MenuButtonPopup && autoRaise) {
                         XPThemeData theme(widget, p, QLatin1String("TOOLBAR"));
                         theme.partId = TP_SPLITBUTTON;
                         theme.rect = button;
                         if (!(bflags & State_Enabled))
                             stateId = TS_DISABLED;
                         else if (bflags & State_Sunken)
                             stateId = TS_PRESSED;
                         else if (bflags & State_MouseOver || !(flags & State_AutoRaise))
                             stateId = flags & State_On ? TS_HOTCHECKED : TS_HOT;
                         else if (bflags & State_On)
                             stateId = TS_CHECKED;
                         else
                             stateId = TS_NORMAL;
                         if (option->direction == Qt::RightToLeft)
                             theme.mirrorHorizontally = true;
                         theme.stateId = stateId;
                         d->drawBackground(theme);
                     } else {
                         tool.rect = option->rect;
                         tool.state = bflags;
                         if (autoRaise) // for tool bars
                             proxy()->drawPrimitive(PE_PanelButtonTool, &tool, p, widget);
                         else
                             proxy()->drawPrimitive(PE_PanelButtonBevel, &tool, p, widget);
                     }
                 }
             }
             if (toolbutton->state & State_HasFocus) {
                 QStyleOptionFocusRect fr;
                 fr.QStyleOption::operator=(*toolbutton);
                 fr.rect.adjust(3, 3, -3, -3);
                 if (toolbutton->features & QStyleOptionToolButton::MenuButtonPopup)
                     fr.rect.adjust(0, 0, -proxy()->pixelMetric(QStyle::PM_MenuButtonIndicator,
                                                       toolbutton, widget), 0);
                 proxy()->drawPrimitive(PE_FrameFocusRect, &fr, p, widget);
             }
             QStyleOptionToolButton label = *toolbutton;
             label.state = bflags;
             int fw = 2;
             if (!autoRaise)
                 label.state &= ~State_Sunken;
             label.rect = button.adjusted(fw, fw, -fw, -fw);
             proxy()->drawControl(CE_ToolButtonLabel, &label, p, widget);
             if (toolbutton->subControls & SC_ToolButtonMenu) {
                 tool.rect = menuarea;
                 tool.state = mflags;
                 if (autoRaise) {
                     proxy()->drawPrimitive(PE_IndicatorButtonDropDown, &tool, p, widget);
                 } else {
                     tool.state = mflags;
                     menuarea.adjust(-2, 0, 0, 0);
                     // Draw menu button
                     if ((bflags & State_Sunken) != (mflags & State_Sunken)){
                         p->save();
                         p->setClipRect(menuarea);
                         tool.rect = option->rect;
                         proxy()->drawPrimitive(PE_PanelButtonBevel, &tool, p, 0);
                         p->restore();
                     }
                     // Draw arrow
                     p->save();
                     p->setPen(option->palette.dark().color());
                     p->drawLine(menuarea.left(), menuarea.top() + 3,
                                 menuarea.left(), menuarea.bottom() - 3);
                     p->setPen(option->palette.light().color());
                     p->drawLine(menuarea.left() - 1, menuarea.top() + 3,
                                 menuarea.left() - 1, menuarea.bottom() - 3);
                     tool.rect = menuarea.adjusted(2, 3, -2, -1);
                     proxy()->drawPrimitive(PE_IndicatorArrowDown, &tool, p, widget);
                     p->restore();
                 }
             } else if (toolbutton->features & QStyleOptionToolButton::HasMenu) {
                 int mbi = proxy()->pixelMetric(PM_MenuButtonIndicator, toolbutton, widget);
                 QRect ir = toolbutton->rect;
                 QStyleOptionToolButton newBtn = *toolbutton;
                 newBtn.rect = QRect(ir.right() + 4 - mbi, ir.height() - mbi + 4, mbi - 5, mbi - 5);
                 proxy()->drawPrimitive(PE_IndicatorArrowDown, &newBtn, p, widget);
             }
         }
         break;
 #endif // QT_NO_TOOLBUTTON
     case CC_TitleBar:
         {
             if (const QStyleOptionTitleBar *tb = qstyleoption_cast<const QStyleOptionTitleBar *>(option))
             {
                 bool isActive = tb->titleBarState & QStyle::State_Active;
                 XPThemeData theme(widget, p, QLatin1String("WINDOW"));
                 if (sub & SC_TitleBarLabel) {
 #ifdef QT3_SUPPORT
                     if (widget && widget->inherits("Q3DockWindowTitleBar")) {
                         partId = WP_SMALLCAPTION;
                     } else
 #endif
                         partId = (tb->titleBarState & Qt::WindowMinimized) ? WP_MINCAPTION : WP_CAPTION;
                     theme.rect = option->rect;
                     if (widget && !widget->isEnabled())
                         stateId = CS_DISABLED;
                     else if (isActive)
                         stateId = CS_ACTIVE;
                     else
                         stateId = CS_INACTIVE;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                     QRect ir = proxy()->subControlRect(CC_TitleBar, tb, SC_TitleBarLabel, widget);
                     int result = TST_NONE;
                     pGetThemeEnumValue(theme.handle(), WP_CAPTION, isActive ? CS_ACTIVE : CS_INACTIVE, TMT_TEXTSHADOWTYPE, &result);
                     if (result != TST_NONE) {
                         COLORREF textShadowRef;
                         pGetThemeColor(theme.handle(), WP_CAPTION, isActive ? CS_ACTIVE : CS_INACTIVE, TMT_TEXTSHADOWCOLOR, &textShadowRef);
                         QColor textShadow = qRgb(GetRValue(textShadowRef), GetGValue(textShadowRef), GetBValue(textShadowRef));
                         p->setPen(textShadow);
                         p->drawText(ir.x() + 3, ir.y() + 2, ir.width() - 1, ir.height(),
                                     Qt::AlignLeft | Qt::AlignVCenter | Qt::TextSingleLine, tb->text);
                     }
                     COLORREF captionText = GetSysColor(isActive ? COLOR_CAPTIONTEXT : COLOR_INACTIVECAPTIONTEXT);
                     QColor textColor = qRgb(GetRValue(captionText), GetGValue(captionText), GetBValue(captionText));
                     p->setPen(textColor);
                     p->drawText(ir.x() + 2, ir.y() + 1, ir.width() - 2, ir.height(),
                                 Qt::AlignLeft | Qt::AlignVCenter | Qt::TextSingleLine, tb->text);
                 }
                 if (sub & SC_TitleBarSysMenu && tb->titleBarFlags & Qt::WindowSystemMenuHint) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarSysMenu, widget);
                     partId = WP_SYSBUTTON;
                     if ((widget && !widget->isEnabled()) || !isActive)
                         stateId = SBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarSysMenu && (option->state & State_Sunken))
                         stateId = SBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarSysMenu && (option->state & State_MouseOver))
                         stateId = SBS_HOT;
                     else
                         stateId = SBS_NORMAL;
                     if (!tb->icon.isNull()) {
                         tb->icon.paint(p, theme.rect);
                     } else {
                         theme.partId = partId;
                         theme.stateId = stateId;
                         SIZE sz;
                         pGetThemePartSize(theme.handle(), qt_win_display_dc(), theme.partId, theme.stateId, 0, TS_TRUE, &sz);
                         if (sz.cx == 0 || sz.cy == 0) {
                             int iconSize = proxy()->pixelMetric(PM_SmallIconSize, tb, widget);
                             QPixmap pm = proxy()->standardIcon(SP_TitleBarMenuButton, tb, widget).pixmap(iconSize, iconSize);
                             p->save();
                             drawItemPixmap(p, theme.rect, Qt::AlignCenter, pm);
                             p->restore();
                         } else {
                             d->drawBackground(theme);
                         }
                     }
                 }
                 if (sub & SC_TitleBarMinButton && tb->titleBarFlags & Qt::WindowMinimizeButtonHint
                         && !(tb->titleBarState & Qt::WindowMinimized)) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarMinButton, widget);
                     partId = WP_MINBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = MINBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarMinButton && (option->state & State_Sunken))
                         stateId = MINBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarMinButton && (option->state & State_MouseOver))
                         stateId = MINBS_HOT;
                     else if (!isActive)
                         stateId = MINBS_INACTIVE;
                     else
                         stateId = MINBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_TitleBarMaxButton && tb->titleBarFlags & Qt::WindowMaximizeButtonHint
                         && !(tb->titleBarState & Qt::WindowMaximized)) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarMaxButton, widget);
                     partId = WP_MAXBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = MAXBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarMaxButton && (option->state & State_Sunken))
                         stateId = MAXBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarMaxButton && (option->state & State_MouseOver))
                         stateId = MAXBS_HOT;
                     else if (!isActive)
                         stateId = MAXBS_INACTIVE;
                     else
                         stateId = MAXBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_TitleBarContextHelpButton
                     && tb->titleBarFlags & Qt::WindowContextHelpButtonHint) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarContextHelpButton, widget);
                     partId = WP_HELPBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = MINBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarContextHelpButton && (option->state & State_Sunken))
                         stateId = MINBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarContextHelpButton && (option->state & State_MouseOver))
                         stateId = MINBS_HOT;
                     else if (!isActive)
                         stateId = MINBS_INACTIVE;
                     else
                         stateId = MINBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 bool drawNormalButton = (sub & SC_TitleBarNormalButton)
                                         && (((tb->titleBarFlags & Qt::WindowMinimizeButtonHint)
                                         && (tb->titleBarState & Qt::WindowMinimized))
                                         || ((tb->titleBarFlags & Qt::WindowMaximizeButtonHint)
                                         && (tb->titleBarState & Qt::WindowMaximized)));
                 if (drawNormalButton) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarNormalButton, widget);
                     partId = WP_RESTOREBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = RBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarNormalButton && (option->state & State_Sunken))
                         stateId = RBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarNormalButton && (option->state & State_MouseOver))
                         stateId = RBS_HOT;
                     else if (!isActive)
                         stateId = RBS_INACTIVE;
                     else
                         stateId = RBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_TitleBarShadeButton && tb->titleBarFlags & Qt::WindowShadeButtonHint
                         && !(tb->titleBarState & Qt::WindowMinimized)) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarShadeButton, widget);
                     partId = WP_MINBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = MINBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarShadeButton && (option->state & State_Sunken))
                         stateId = MINBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarShadeButton && (option->state & State_MouseOver))
                         stateId = MINBS_HOT;
                     else if (!isActive)
                         stateId = MINBS_INACTIVE;
                     else
                         stateId = MINBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_TitleBarUnshadeButton && tb->titleBarFlags & Qt::WindowShadeButtonHint
                         && tb->titleBarState & Qt::WindowMinimized) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarUnshadeButton, widget);
                     partId = WP_RESTOREBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = RBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarUnshadeButton && (option->state & State_Sunken))
                         stateId = RBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarUnshadeButton && (option->state & State_MouseOver))
                         stateId = RBS_HOT;
                     else if (!isActive)
                         stateId = RBS_INACTIVE;
                     else
                         stateId = RBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
                 if (sub & SC_TitleBarCloseButton && tb->titleBarFlags & Qt::WindowSystemMenuHint) {
                     theme.rect = proxy()->subControlRect(CC_TitleBar, option, SC_TitleBarCloseButton, widget);
                     //partId = titlebar->testWFlags(Qt::WA_WState_Tool) ? WP_SMALLCLOSEBUTTON : WP_CLOSEBUTTON;
                     partId = WP_CLOSEBUTTON;
                     if (widget && !widget->isEnabled())
                         stateId = CBS_DISABLED;
                     else if (option->activeSubControls == SC_TitleBarCloseButton && (option->state & State_Sunken))
                         stateId = CBS_PUSHED;
                     else if (option->activeSubControls == SC_TitleBarCloseButton && (option->state & State_MouseOver))
                         stateId = CBS_HOT;
                     else if (!isActive)
                         stateId = CBS_INACTIVE;
                     else
                         stateId = CBS_NORMAL;
                     theme.partId = partId;
                     theme.stateId = stateId;
                     d->drawBackground(theme);
                 }
             }
         }
         break;
 #ifndef QT_NO_WORKSPACE
     case CC_MdiControls:
         {
             QRect buttonRect;
             XPThemeData theme(widget, p, QLatin1String("WINDOW"), WP_MDICLOSEBUTTON, CBS_NORMAL);
             if (option->subControls & SC_MdiCloseButton) {
                 buttonRect = proxy()->subControlRect(CC_MdiControls, option, SC_MdiCloseButton, widget);
                 if (theme.isValid()) {
                     theme.partId = WP_MDICLOSEBUTTON;
                     theme.rect = buttonRect;
                     if (!(flags & State_Enabled))
                         theme.stateId = CBS_INACTIVE;
                     else if (flags & State_Sunken && (option->activeSubControls & SC_MdiCloseButton))
                         theme.stateId = CBS_PUSHED;
                     else if (flags & State_MouseOver && (option->activeSubControls & SC_MdiCloseButton))
                         theme.stateId = CBS_HOT;
                     else
                         theme.stateId = CBS_NORMAL;
                     d->drawBackground(theme);
                 }
             }
             if (option->subControls & SC_MdiNormalButton) {
                 buttonRect = proxy()->subControlRect(CC_MdiControls, option, SC_MdiNormalButton, widget);
                 if (theme.isValid()) {
                     theme.partId = WP_MDIRESTOREBUTTON;
                     theme.rect = buttonRect;
                     if (!(flags & State_Enabled))
                         theme.stateId = CBS_INACTIVE;
                     else if (flags & State_Sunken && (option->activeSubControls & SC_MdiNormalButton))
                         theme.stateId = CBS_PUSHED;
                     else if (flags & State_MouseOver && (option->activeSubControls & SC_MdiNormalButton))
                         theme.stateId = CBS_HOT;
                     else
                         theme.stateId = CBS_NORMAL;
                     d->drawBackground(theme);
                 }
             }
             if (option->subControls & QStyle::SC_MdiMinButton) {
                 buttonRect = proxy()->subControlRect(CC_MdiControls, option, SC_MdiMinButton, widget);
                 if (theme.isValid()) {
                     theme.partId = WP_MDIMINBUTTON;
                     theme.rect = buttonRect;
                     if (!(flags & State_Enabled))
                         theme.stateId = CBS_INACTIVE;
                     else if (flags & State_Sunken && (option->activeSubControls & SC_MdiMinButton))
                         theme.stateId = CBS_PUSHED;
                     else if (flags & State_MouseOver && (option->activeSubControls & SC_MdiMinButton))
                         theme.stateId = CBS_HOT;
                     else
                         theme.stateId = CBS_NORMAL;
                     d->drawBackground(theme);
                 }
             }
         }
         break;
 #endif //QT_NO_WORKSPACE
 #ifndef QT_NO_DIAL
     case CC_Dial:
         if (const QStyleOptionSlider *dial = qstyleoption_cast<const QStyleOptionSlider *>(option))
             QStyleHelper::drawDial(dial, p);
         break;
 #endif // QT_NO_DIAL
     default:
         QWindowsStyle::drawComplexControl(cc, option, p, widget);
         break;
     }
 }
drawControl()
void QWindowsXPStyle::drawControl (ControlElement element, const QStyleOption * option, QPainter * p, const QWidget * wwidget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1927 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::drawControl().
 {
   QWindowsXPStylePrivate *d = const_cast<QWindowsXPStylePrivate*>(d_func());
     if (!QWindowsXPStylePrivate::useXP()) {
         QWindowsStyle::drawControl(element, option, p, widget);
         return;
     }
     QRect rect(option->rect);
     State flags = option->state;
     int rotate = 0;
     bool hMirrored = false;
     bool vMirrored = false;
     QString name;
     int partId = 0;
     int stateId = 0;
     switch (element) {
     case CE_SizeGrip:
         {
             name = QLatin1String("STATUS");
             partId = SP_GRIPPER;
             SIZE sz;
             XPThemeData theme(0, p, name, partId, 0);
             pGetThemePartSize(theme.handle(), 0, partId, 0, 0, TS_TRUE, &sz);
             --sz.cy;
             if (const QStyleOptionSizeGrip *sg = qstyleoption_cast<const QStyleOptionSizeGrip *>(option)) {
                 switch (sg->corner) {
                     case Qt::BottomRightCorner:
                         rect = QRect(rect.right() - sz.cx, rect.bottom() - sz.cy, sz.cx, sz.cy);
                         break;
                     case Qt::BottomLeftCorner:
                         rect = QRect(rect.left() + 1, rect.bottom() - sz.cy, sz.cx, sz.cy);
                         hMirrored = true;
                         break;
                     case Qt::TopRightCorner:
                         rect = QRect(rect.right() - sz.cx, rect.top() + 1, sz.cx, sz.cy);
                         vMirrored = true;
                         break;
                     case Qt::TopLeftCorner:
                         rect = QRect(rect.left() + 1, rect.top() + 1, sz.cx, sz.cy);
                         hMirrored = vMirrored = true;
                 }
             }
         }
         break;
     case CE_HeaderSection:
         name = QLatin1String("HEADER");
         partId = HP_HEADERITEM;
         if (flags & State_Sunken)
             stateId = HIS_PRESSED;
         else if (flags & State_MouseOver)
             stateId = HIS_HOT;
         else
             stateId = HIS_NORMAL;
         break;
     case CE_Splitter:
         p->eraseRect(option->rect);
         return;
     case CE_PushButtonBevel:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(option))
         {
             name = QLatin1String("BUTTON");
             partId = BP_PUSHBUTTON;
             bool justFlat = ((btn->features & QStyleOptionButton::Flat) && !(flags & (State_On|State_Sunken)))
                 || ((btn->features & QStyleOptionButton::CommandLinkButton)
                     && !(flags & State_MouseOver)
                     && !(btn->features & QStyleOptionButton::DefaultButton));
             if (!(flags & State_Enabled) && !(btn->features & QStyleOptionButton::Flat))
                 stateId = PBS_DISABLED;
             else if (justFlat)
                 ;
             else if (flags & (State_Sunken | State_On))
                 stateId = PBS_PRESSED;
             else if (flags & State_MouseOver)
                 stateId = PBS_HOT;
             else if (btn->features & QStyleOptionButton::DefaultButton)
                 stateId = PBS_DEFAULTED;
             else
                 stateId = PBS_NORMAL;
             if (!justFlat) {
                 XPThemeData theme(widget, p, name, partId, stateId, rect);
                 d->drawBackground(theme);
             }
             if (btn->features & QStyleOptionButton::HasMenu) {
                 int mbiw = 0, mbih = 0;
                 XPThemeData theme(widget, 0, QLatin1String("TOOLBAR"), TP_SPLITBUTTONDROPDOWN);
                 if (theme.isValid()) {
                     SIZE size;
                     pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                     mbiw = size.cx;
                     mbih = size.cy;
                 }
                 QRect ir = btn->rect;
                 QStyleOptionButton newBtn = *btn;
                 newBtn.rect = QRect(ir.right() - mbiw - 1, 1 + (ir.height()/2) - (mbih/2), mbiw, mbih);
                 proxy()->drawPrimitive(PE_IndicatorArrowDown, &newBtn, p, widget);
             }
             return;
         }
         break;
     case CE_TabBarTab:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(option))
         {
             stateId = tab->state & State_Enabled ? TIS_NORMAL : TIS_DISABLED;
         }
     break;
     case CE_TabBarTabShape:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(option))
         {
             name = QLatin1String("TAB");
             bool isDisabled = !(tab->state & State_Enabled);
             bool hasFocus = tab->state & State_HasFocus;
             bool isHot = tab->state & State_MouseOver;
             bool selected = tab->state & State_Selected;
             bool lastTab = tab->position == QStyleOptionTab::End;
             bool firstTab = tab->position == QStyleOptionTab::Beginning;
             bool onlyOne = tab->position == QStyleOptionTab::OnlyOneTab;
             bool leftAligned = proxy()->styleHint(SH_TabBar_Alignment, tab, widget) == Qt::AlignLeft;
             bool centerAligned = proxy()->styleHint(SH_TabBar_Alignment, tab, widget) == Qt::AlignCenter;
             int borderThickness = proxy()->pixelMetric(PM_DefaultFrameWidth, option, widget);
             int tabOverlap = proxy()->pixelMetric(PM_TabBarTabOverlap, option, widget);
             if (isDisabled)
                 stateId = TIS_DISABLED;
             else if (selected)
                 stateId = TIS_SELECTED;
             else if (hasFocus)
                 stateId = TIS_FOCUSED;
             else if (isHot)
                 stateId = TIS_HOT;
             else
                 stateId = TIS_NORMAL;
             // Selecting proper part depending on position
             if (firstTab || onlyOne) {
                 if (leftAligned) {
                     partId = TABP_TABITEMLEFTEDGE;
                 } else if (centerAligned) {
                     partId = TABP_TABITEM;
                 } else { // rightAligned
                     partId = TABP_TABITEMRIGHTEDGE;
                 }
             } else {
                 partId = TABP_TABITEM;
             }
             if (tab->direction == Qt::RightToLeft
                 && (tab->shape == QTabBar::RoundedNorth
                     || tab->shape == QTabBar::RoundedSouth)) {
                 bool temp = firstTab;
                 firstTab = lastTab;
                 lastTab = temp;
             }
             bool begin = firstTab || onlyOne;
             bool end = lastTab || onlyOne;
             switch (tab->shape) {
             case QTabBar::RoundedNorth:
                 if (selected)
                     rect.adjust(begin ? 0 : -tabOverlap, 0, end ? 0 : tabOverlap, borderThickness);
                 else
                     rect.adjust(begin? tabOverlap : 0, tabOverlap, end ? -tabOverlap : 0, 0);
                 break;
             case QTabBar::RoundedSouth:
                 //vMirrored = true;
                 rotate = 180; // Not 100% correct, but works
                 if (selected)
                     rect.adjust(begin ? 0 : -tabOverlap , -borderThickness, end ? 0 : tabOverlap, 0);
                 else
                     rect.adjust(begin ? tabOverlap : 0, 0, end ? -tabOverlap : 0 , -tabOverlap);
                 break;
             case QTabBar::RoundedEast:
                 rotate = 90;
                 if (selected) {
                     rect.adjust(-borderThickness, begin ? 0 : -tabOverlap, 0, end ? 0 : tabOverlap);
                 }else{
                     rect.adjust(0, begin ? tabOverlap : 0, -tabOverlap, end ? -tabOverlap : 0);
                 }
                 break;
             case QTabBar::RoundedWest:
                 hMirrored = true;
                 rotate = 90;
                 if (selected) {
                     rect.adjust(0, begin ? 0 : -tabOverlap, borderThickness, end ? 0 : tabOverlap);
                 }else{
                     rect.adjust(tabOverlap, begin ? tabOverlap : 0, 0, end ? -tabOverlap : 0);
                 }
                 break;
             default:
                 name = QLatin1String("");  // Do our own painting for triangular
                 break;
             }
             if (!selected) {
                 switch (tab->shape) {
                 case QTabBar::RoundedNorth:
                     rect.adjust(0,0, 0,-1);
                     break;
                 case QTabBar::RoundedSouth:
                     rect.adjust(0,1, 0,0);
                     break;
                 case QTabBar::RoundedEast:
                     rect.adjust( 1,0, 0,0);
                     break;
                 case QTabBar::RoundedWest:
                     rect.adjust(0,0, -1,0);
                     break;
                 default:
                     break;
                 }
             }
         }
         break;
     case CE_ProgressBarGroove:
         {
         Qt::Orientation orient = Qt::Horizontal;
         if (const QStyleOptionProgressBarV2 *pb2 = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(option))
             orient = pb2->orientation;
         partId = (orient == Qt::Horizontal) ? PP_BAR : PP_BARVERT;
         name = QLatin1String("PROGRESS");
         stateId = 1;
         }
         break;
     case CE_MenuEmptyArea:
     case CE_MenuItem:
         if (const QStyleOptionMenuItem *menuitem = qstyleoption_cast<const QStyleOptionMenuItem *>(option))
         {
             int tab = menuitem->tabWidth;
             bool dis = !(menuitem->state & State_Enabled);
             bool act = menuitem->state & State_Selected;
             bool checkable = menuitem->menuHasCheckableItems;
             bool checked = checkable ? menuitem->checked : false;
             // windows always has a check column, regardless whether we have an icon or not
             int checkcol = qMax(menuitem->maxIconWidth, 12);
             int x, y, w, h;
             rect.getRect(&x, &y, &w, &h);
             QBrush fill = menuitem->palette.brush(act ? QPalette::Highlight : QPalette::Button);
             p->fillRect(rect, fill);
             if (element == CE_MenuEmptyArea)
                 break;
             // draw separator -------------------------------------------------
             if (menuitem->menuItemType == QStyleOptionMenuItem::Separator) {
                 int yoff = y-1 + h / 2;
                 p->setPen(menuitem->palette.dark().color());
                 p->drawLine(x, yoff, x+w, yoff);
                 ++yoff;
                 p->setPen(menuitem->palette.light().color());
                 p->drawLine(x, yoff, x+w, yoff);
                 return;
             }
             int xpos = x;
             // draw icon ------------------------------------------------------
             if (!menuitem->icon.isNull()) {
                 QIcon::Mode mode = dis ? QIcon::Disabled : QIcon::Normal;
                 if (act && !dis)
                     mode = QIcon::Active;
                 QPixmap pixmap = checked ?
                                  menuitem->icon.pixmap(proxy()->pixelMetric(PM_SmallIconSize, option, widget), mode, QIcon::On) :
                                  menuitem->icon.pixmap(proxy()->pixelMetric(PM_SmallIconSize, option, widget), mode);
                 int pixw = pixmap.width();
                 int pixh = pixmap.height();
                 QRect iconRect(0, 0, pixw, pixh);
                 iconRect.moveCenter(QRect(xpos, y, checkcol, h).center());
                 QRect vIconRect = visualRect(option->direction, option->rect, iconRect);
                 p->setPen(menuitem->palette.text().color());
                 p->setBrush(Qt::NoBrush);
                 if (checked)
                     p->drawRect(vIconRect.adjusted(-1, -1, 0, 0));
                 p->drawPixmap(vIconRect.topLeft(), pixmap);
             // draw checkmark -------------------------------------------------
             } else if (checked) {
                 QStyleOptionMenuItem newMi = *menuitem;
                 newMi.state = State_None;
                 if (!dis)
                     newMi.state |= State_Enabled;
                 if (act)
                     newMi.state |= State_On;
                 QRect checkMarkRect = QRect(menuitem->rect.x() + windowsItemFrame,
                                             menuitem->rect.y() + windowsItemFrame,
                                             checkcol - 2 * windowsItemFrame,
                                             menuitem->rect.height() - 2*windowsItemFrame);
                 newMi.rect = visualRect(option->direction, option->rect, checkMarkRect);
                 proxy()->drawPrimitive(PE_IndicatorMenuCheckMark, &newMi, p, widget);
             }
             QColor textColor = dis ? menuitem->palette.text().color() :
                                act ? menuitem->palette.highlightedText().color() : menuitem->palette.buttonText().color();
             p->setPen(textColor);
             // draw text ------------------------------------------------------
             int xm = windowsItemFrame + checkcol + windowsItemHMargin;
             xpos = menuitem->rect.x() + xm;
             QRect textRect(xpos, y + windowsItemVMargin, w - xm - windowsRightBorder - tab + 1, h - 2 * windowsItemVMargin);
             QRect vTextRect = visualRect(option->direction, option->rect, textRect);
             QString s = menuitem->text;
             if (!s.isEmpty()) {
                 p->save();
                 int t = s.indexOf(QLatin1Char('\t'));
                 int text_flags = Qt::AlignVCenter|Qt::TextShowMnemonic | Qt::TextDontClip | Qt::TextSingleLine | Qt::AlignLeft;
                 if (!proxy()->styleHint(SH_UnderlineShortcut, menuitem, widget))
                     text_flags |= Qt::TextHideMnemonic;
                 // draw tab text ----------------
                 if (t >= 0) {
                     QRect vShortcutRect = visualRect(option->direction, option->rect, QRect(textRect.topRight(), menuitem->rect.bottomRight()));
                     if (dis && !act && proxy()->styleHint(SH_EtchDisabledText, option, widget)) {
                         p->setPen(menuitem->palette.light().color());
                         p->drawText(vShortcutRect.adjusted(1,1,1,1), text_flags, s.mid(t + 1));
                         p->setPen(textColor);
                     }
                     p->drawText(vShortcutRect, text_flags, s.mid(t + 1));
                     s = s.left(t);
                 }
                 QFont font = menuitem->font;
                 if (menuitem->menuItemType == QStyleOptionMenuItem::DefaultItem)
                     font.setBold(true);
                 p->setFont(font);
                 if (dis && !act && proxy()->styleHint(SH_EtchDisabledText, option, widget)) {
                     p->setPen(menuitem->palette.light().color());
                     p->drawText(vTextRect.adjusted(1,1,1,1), text_flags, s.left(t));
                     p->setPen(textColor);
                 }
                 p->drawText(vTextRect, text_flags, s);
                 p->restore();
             }
             // draw sub menu arrow --------------------------------------------
             if (menuitem->menuItemType == QStyleOptionMenuItem::SubMenu) {
                 int dim = (h - 2) / 2;
                 PrimitiveElement arrow;
                 arrow = (option->direction == Qt::RightToLeft) ? PE_IndicatorArrowLeft : PE_IndicatorArrowRight;
                 xpos = x + w - windowsArrowHMargin - windowsItemFrame - dim;
                 QRect vSubMenuRect = visualRect(option->direction, option->rect, QRect(xpos, y + h / 2 - dim / 2, dim, dim));
                 QStyleOptionMenuItem newMI = *menuitem;
                 newMI.rect = vSubMenuRect;
                 newMI.state = dis ? State_None : State_Enabled;
                 if (act)
                     newMI.palette.setColor(QPalette::ButtonText, newMI.palette.highlightedText().color());
                 proxy()->drawPrimitive(arrow, &newMI, p, widget);
             }
         }
         return;
     case CE_MenuBarItem:
         if (const QStyleOptionMenuItem *mbi = qstyleoption_cast<const QStyleOptionMenuItem *>(option))
         {
             if (mbi->menuItemType == QStyleOptionMenuItem::DefaultItem)
                 break;
             bool act = mbi->state & State_Selected;
             bool dis = !(mbi->state & State_Enabled);
             QBrush fill = mbi->palette.brush(act ? QPalette::Highlight : QPalette::Button);
             QPalette::ColorRole textRole = dis ? QPalette::Text:
                                            act ? QPalette::HighlightedText : QPalette::ButtonText;
             QPixmap pix = mbi->icon.pixmap(proxy()->pixelMetric(PM_SmallIconSize, option, widget), QIcon::Normal);
             uint alignment = Qt::AlignCenter | Qt::TextShowMnemonic | Qt::TextDontClip | Qt::TextSingleLine;
             if (!proxy()->styleHint(SH_UnderlineShortcut, mbi, widget))
                 alignment |= Qt::TextHideMnemonic;
             p->fillRect(rect, fill);
             if (!pix.isNull())
                 drawItemPixmap(p, mbi->rect, alignment, pix);
             else
                 drawItemText(p, mbi->rect, alignment, mbi->palette, mbi->state & State_Enabled, mbi->text, textRole);
         }
         return;
 #ifndef QT_NO_DOCKWIDGET
     case CE_DockWidgetTitle:
         if (const QStyleOptionDockWidget *dwOpt = qstyleoption_cast<const QStyleOptionDockWidget *>(option))
         {
             int buttonMargin = 4;
             int mw = proxy()->pixelMetric(QStyle::PM_DockWidgetTitleMargin, dwOpt, widget);
             int fw = proxy()->pixelMetric(PM_DockWidgetFrameWidth, dwOpt, widget);
             bool isFloating = widget && widget->isWindow();
             bool isActive = dwOpt->state & State_Active;
             const QStyleOptionDockWidgetV2 *v2
                 = qstyleoption_cast<const QStyleOptionDockWidgetV2*>(dwOpt);
             bool verticalTitleBar = v2 == 0 ? false : v2->verticalTitleBar;
             if (verticalTitleBar) {
                 QSize s = rect.size();
                 s.transpose();
                 rect.setSize(s);
                 p->translate(rect.left() - 1, rect.top() + rect.width());
                 p->rotate(-90);
                 p->translate(-rect.left() + 1, -rect.top());
             }
             QRect r = rect.adjusted(0, 2, -1, -3);
             QRect titleRect = r;
             if (dwOpt->closable) {
                 QSize sz = proxy()->standardIcon(QStyle::SP_TitleBarCloseButton, dwOpt, widget).actualSize(QSize(10, 10));
                 titleRect.adjust(0, 0, -sz.width() - mw - buttonMargin, 0);
             }
             if (dwOpt->floatable) {
                 QSize sz = proxy()->standardIcon(QStyle::SP_TitleBarMaxButton, dwOpt, widget).actualSize(QSize(10, 10));
                 titleRect.adjust(0, 0, -sz.width() - mw - buttonMargin, 0);
             }
             if (isFloating) {
                 titleRect.adjust(0, -fw, 0, 0);
                 if (widget != 0 && widget->windowIcon().cacheKey() != QApplication::windowIcon().cacheKey())
                     titleRect.adjust(titleRect.height() + mw, 0, 0, 0);
             } else {
                 titleRect.adjust(mw, 0, 0, 0);
                 if (!dwOpt->floatable && !dwOpt->closable)
                     titleRect.adjust(0, 0, -mw, 0);
             }
             if (!verticalTitleBar)
                 titleRect = visualRect(dwOpt->direction, r, titleRect);
             if (!isFloating) {
                 QPen oldPen = p->pen();
                 QString titleText = p->fontMetrics().elidedText(dwOpt->title, Qt::ElideRight, titleRect.width());
                 p->setPen(dwOpt->palette.color(QPalette::Dark));
                 p->drawRect(r);
                 if (!titleText.isEmpty()) {
                     drawItemText(p, titleRect,
                                 Qt::AlignLeft | Qt::AlignVCenter | Qt::TextShowMnemonic, dwOpt->palette,
                                 dwOpt->state & State_Enabled, titleText,
                                 QPalette::WindowText);
                 }
                 p->setPen(oldPen);
             } else {
                 name = QLatin1String("WINDOW");
                 if (isActive)
                     stateId = CS_ACTIVE;
                 else
                     stateId = CS_INACTIVE;
                 int titleHeight = rect.height() - 2;
                 rect = rect.adjusted(-fw, -fw, fw, 0);
                 XPThemeData theme(widget, p, name, 0, stateId);
                 if (!theme.isValid())
                     break;
                 // Draw small type title bar
                 theme.rect = rect;
                 theme.partId = WP_SMALLCAPTION;
                 d->drawBackground(theme);
                 // Figure out maximal button space on title bar
                 QIcon ico = widget->windowIcon();
                 bool hasIcon = (ico.cacheKey() != QApplication::windowIcon().cacheKey());
                 if (hasIcon) {
                     QPixmap pxIco = ico.pixmap(titleHeight);
                     if (!verticalTitleBar && dwOpt->direction == Qt::RightToLeft)
                         p->drawPixmap(rect.width() - titleHeight - pxIco.width(), rect.bottom() - titleHeight - 2, pxIco);
                     else
                         p->drawPixmap(fw, rect.bottom() - titleHeight - 2, pxIco);
                 }
                 if (!dwOpt->title.isEmpty()) {
                     QPen oldPen = p->pen();
                     QFont oldFont = p->font();
                     QFont titleFont = oldFont;
                     titleFont.setBold(true);
                     p->setFont(titleFont);
                     QString titleText
                         = p->fontMetrics().elidedText(dwOpt->title, Qt::ElideRight, titleRect.width());
                     int result = TST_NONE;
                     pGetThemeEnumValue(theme.handle(), WP_SMALLCAPTION, isActive ? CS_ACTIVE : CS_INACTIVE, TMT_TEXTSHADOWTYPE, &result);
                     if (result != TST_NONE) {
                         COLORREF textShadowRef;
                         pGetThemeColor(theme.handle(), WP_SMALLCAPTION, isActive ? CS_ACTIVE : CS_INACTIVE, TMT_TEXTSHADOWCOLOR, &textShadowRef);
                         QColor textShadow = qRgb(GetRValue(textShadowRef), GetGValue(textShadowRef), GetBValue(textShadowRef));
                         p->setPen(textShadow);
                         drawItemText(p, titleRect.adjusted(1, 1, 1, 1),
                                     Qt::AlignLeft | Qt::AlignBottom, dwOpt->palette,
                                     dwOpt->state & State_Enabled, titleText);
                     }
                     COLORREF captionText = GetSysColor(isActive ? COLOR_CAPTIONTEXT : COLOR_INACTIVECAPTIONTEXT);
                     QColor textColor = qRgb(GetRValue(captionText), GetGValue(captionText), GetBValue(captionText));
                     p->setPen(textColor);
                     drawItemText(p, titleRect,
                                 Qt::AlignLeft | Qt::AlignBottom, dwOpt->palette,
                                 dwOpt->state & State_Enabled, titleText);
                     p->setFont(oldFont);
                     p->setPen(oldPen);
                 }
             }
             return;
         }
         break;
 #endif // QT_NO_DOCKWIDGET
 #ifndef QT_NO_RUBBERBAND
     case CE_RubberBand:
         if (qstyleoption_cast<const QStyleOptionRubberBand *>(option)) {
             QColor highlight = option->palette.color(QPalette::Active, QPalette::Highlight);
             p->save();
             p->setPen(highlight.darker(120));
             QColor dimHighlight(qMin(highlight.red()/2 + 110, 255),
                                 qMin(highlight.green()/2 + 110, 255),
                                 qMin(highlight.blue()/2 + 110, 255),
                                 (widget && widget->isTopLevel())? 255 : 127);
             p->setBrush(dimHighlight);
             p->drawRect(option->rect.adjusted(0, 0, -1, -1));
             p->restore();
             return;
         }
 #endif // QT_NO_RUBBERBAND
     case CE_HeaderEmptyArea:
         if (option->state & State_Horizontal)
         {
             name = QLatin1String("HEADER");
             stateId = HIS_NORMAL;
         }
         else {
             QWindowsStyle::drawControl(CE_HeaderEmptyArea, option, p, widget);
             return;
         }
         break;
     default:
         break;
     }
     XPThemeData theme(widget, p, name, partId, stateId, rect);
     if (!theme.isValid()) {
         QWindowsStyle::drawControl(element, option, p, widget);
         return;
     }
     theme.rotate = rotate;
     theme.mirrorHorizontally = hMirrored;
     theme.mirrorVertically = vMirrored;
     d->drawBackground(theme);
 }
drawPrimitive()
void QWindowsXPStyle::drawPrimitive (PrimitiveElement pe, const QStyleOption * option, QPainter * p, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1336 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::drawPrimitive().
 {
     QWindowsXPStylePrivate *d = const_cast<QWindowsXPStylePrivate*>(d_func());
     if (!QWindowsXPStylePrivate::useXP()) {
         QWindowsStyle::drawPrimitive(pe, option, p, widget);
         return;
     }
     QString name;
     int partId = 0;
     int stateId = 0;
     QRect rect = option->rect;
     State flags = option->state;
     bool hMirrored = false;
     bool vMirrored = false;
     bool noBorder = false;
     bool noContent = false;
     int  rotate = 0;
     switch (pe) {
     case PE_FrameTabBarBase:
         if (const QStyleOptionTabBarBase *tbb
                 = qstyleoption_cast<const QStyleOptionTabBarBase *>(option)) {
             p->save();
             switch (tbb->shape) {
             case QTabBar::RoundedNorth:
                 p->setPen(QPen(tbb->palette.dark(), 0));
                 p->drawLine(tbb->rect.topLeft(), tbb->rect.topRight());
                 break;
             case QTabBar::RoundedWest:
                 p->setPen(QPen(tbb->palette.dark(), 0));
                 p->drawLine(tbb->rect.left(), tbb->rect.top(), tbb->rect.left(), tbb->rect.bottom());
                 break;
             case QTabBar::RoundedSouth:
                 p->setPen(QPen(tbb->palette.dark(), 0));
                 p->drawLine(tbb->rect.left(), tbb->rect.top(),
                             tbb->rect.right(), tbb->rect.top());
                 break;
             case QTabBar::RoundedEast:
                 p->setPen(QPen(tbb->palette.dark(), 0));
                 p->drawLine(tbb->rect.topLeft(), tbb->rect.bottomLeft());
                 break;
             case QTabBar::TriangularNorth:
             case QTabBar::TriangularEast:
             case QTabBar::TriangularWest:
             case QTabBar::TriangularSouth:
                 p->restore();
                 QWindowsStyle::drawPrimitive(pe, option, p, widget);
                 return;
             }
             p->restore();
         }
         return;
     case PE_PanelButtonBevel:
         name = QLatin1String("BUTTON");
         partId = BP_PUSHBUTTON;
         if (!(flags & State_Enabled))
             stateId = PBS_DISABLED;
         else if ((flags & State_Sunken) || (flags & State_On))
             stateId = PBS_PRESSED;
         else if (flags & State_MouseOver)
             stateId = PBS_HOT;
         //else if (flags & State_ButtonDefault)
         //    stateId = PBS_DEFAULTED;
         else
             stateId = PBS_NORMAL;
         break;
     case PE_PanelButtonTool:
         if (widget && widget->inherits("QDockWidgetTitleButton")) {
             if (const QWidget *dw = widget->parentWidget())
                 if (dw->isWindow())
                     return;
         }
         name = QLatin1String("TOOLBAR");
         partId = TP_BUTTON;
         if (!(flags & State_Enabled))
             stateId = TS_DISABLED;
         else if (flags & State_Sunken)
             stateId = TS_PRESSED;
         else if (flags & State_MouseOver)
             stateId = flags & State_On ? TS_HOTCHECKED : TS_HOT;
         else if (flags & State_On)
             stateId = TS_CHECKED;
         else if (!(flags & State_AutoRaise))
             stateId = TS_HOT;
         else
             stateId = TS_NORMAL;
         break;
     case PE_IndicatorButtonDropDown:
         name = QLatin1String("TOOLBAR");
         partId = TP_SPLITBUTTONDROPDOWN;
         if (!(flags & State_Enabled))
             stateId = TS_DISABLED;
         else if (flags & State_Sunken)
             stateId = TS_PRESSED;
         else if (flags & State_MouseOver)
             stateId = flags & State_On ? TS_HOTCHECKED : TS_HOT;
         else if (flags & State_On)
             stateId = TS_CHECKED;
         else if (!(flags & State_AutoRaise))
             stateId = TS_HOT;
         else
             stateId = TS_NORMAL;
         if (option->direction == Qt::RightToLeft)
             hMirrored = true;
         break;
     case PE_IndicatorCheckBox:
         name = QLatin1String("BUTTON");
         partId = BP_CHECKBOX;
         if (!(flags & State_Enabled))
             stateId = CBS_UNCHECKEDDISABLED;
         else if (flags & State_Sunken)
             stateId = CBS_UNCHECKEDPRESSED;
         else if (flags & State_MouseOver)
             stateId = CBS_UNCHECKEDHOT;
         else
             stateId = CBS_UNCHECKEDNORMAL;
         if (flags & State_On)
             stateId += CBS_CHECKEDNORMAL-1;
         else if (flags & State_NoChange)
             stateId += CBS_MIXEDNORMAL-1;
         break;
     case PE_IndicatorRadioButton:
         name = QLatin1String("BUTTON");
         partId = BP_RADIOBUTTON;
         if (!(flags & State_Enabled))
             stateId = RBS_UNCHECKEDDISABLED;
         else if (flags & State_Sunken)
             stateId = RBS_UNCHECKEDPRESSED;
         else if (flags & State_MouseOver)
             stateId = RBS_UNCHECKEDHOT;
         else
             stateId = RBS_UNCHECKEDNORMAL;
         if (flags & State_On)
             stateId += RBS_CHECKEDNORMAL-1;
         break;
     case PE_IndicatorDockWidgetResizeHandle:
         return;
 case PE_Frame:
     {
         if (flags & State_Raised)
             return;
         name = QLatin1String("LISTVIEW");
         partId = LVP_LISTGROUP;
         XPThemeData theme(0, 0, name, partId, 0);
         if (!(flags & State_Enabled))
             stateId = ETS_DISABLED;
         else
             stateId = ETS_NORMAL;
         int fillType;
         if (pGetThemeEnumValue(theme.handle(), partId, stateId, TMT_BGTYPE, &fillType) == S_OK) {
             if (fillType == BT_BORDERFILL) {
                 COLORREF bcRef;
                 pGetThemeColor(theme.handle(), partId, stateId, TMT_BORDERCOLOR, &bcRef);
                 QColor bordercolor(qRgb(GetRValue(bcRef), GetGValue(bcRef), GetBValue(bcRef)));
                 QPen oldPen = p->pen();
                 // int borderSize = 1;
                 // pGetThemeInt(theme.handle(), partId, stateId, TMT_BORDERCOLOR, &borderSize);
                 // Inner white border
                 p->setPen(QPen(option->palette.base().color(), 1));
                 p->drawRect(option->rect.adjusted(1, 1, -2, -2));
                 // Outer dark border
                 p->setPen(QPen(bordercolor, 1));
                 p->drawRect(option->rect.adjusted(0, 0, -1, -1));
                 p->setPen(oldPen);
                 return;
             } else if (fillType == BT_NONE) {
                 return;
             } else {
                 break;
             }
         }
     }
     case PE_FrameLineEdit: {
         // we try to check if this lineedit is a delegate on a QAbstractItemView-derived class.
         if (QWindowsXPStylePrivate::isItemViewDelegateLineEdit(widget)) {
             QPen oldPen = p->pen();
             // Inner white border
             p->setPen(QPen(option->palette.base().color(), 1));
             p->drawRect(option->rect.adjusted(1, 1, -2, -2));
             // Outer dark border
             p->setPen(QPen(option->palette.shadow().color(), 1));
             p->drawRect(option->rect.adjusted(0, 0, -1, -1));
             p->setPen(oldPen);
             return;
         } else if (qstyleoption_cast<const QStyleOptionFrame *>(option)) {
             name = QLatin1String("EDIT");
             partId = EP_EDITTEXT;
             noContent = true;
             if (!(flags & State_Enabled))
                 stateId = ETS_DISABLED;
             else
                 stateId = ETS_NORMAL;
         }
         break;
     }
     case PE_PanelLineEdit:
         if (const QStyleOptionFrame *panel = qstyleoption_cast<const QStyleOptionFrame *>(option)) {
             name = QLatin1String("EDIT");
             partId = EP_EDITTEXT;
             noBorder = true;
             QBrush bg;
             bool usePalette = false;
             bool isEnabled = flags & State_Enabled;
             uint resolve_mask = panel->palette.resolve();
 #ifndef QT_NO_SPINBOX
             //Since spin box includes a line edit we need to resolve the palette on the spin box instead
             if (widget) {
                 if (QAbstractSpinBox *spinbox = qobject_cast<QAbstractSpinBox*>(widget->parentWidget()))
                     resolve_mask = spinbox->palette().resolve();
             }
 #endif // QT_NO_SPINBOX
             if (resolve_mask & (1 << QPalette::Base)) {
                 // Base color is set for this widget, so use it
                 bg = panel->palette.brush(QPalette::Base);
                 usePalette = true;
             }
             stateId = isEnabled ? ETS_NORMAL : ETS_DISABLED;
             if (usePalette) {
                 p->fillRect(panel->rect, bg);
             } else {
                 XPThemeData theme(0, p, name, partId, stateId, rect);
                 if (!theme.isValid()) {
                     QWindowsStyle::drawPrimitive(pe, option, p, widget);
                     return;
                 }
                 int bgType;
                 pGetThemeEnumValue( theme.handle(),
                                     partId,
                                     stateId,
                                     TMT_BGTYPE,
                                     &bgType);
                 if( bgType == BT_IMAGEFILE ) {
                     theme.mirrorHorizontally = hMirrored;
                     theme.mirrorVertically = vMirrored;
                     theme.noBorder = noBorder;
                     theme.noContent = noContent;
                     theme.rotate = rotate;
                     d->drawBackground(theme);
                 } else {
                     QBrush fillColor = option->palette.brush(QPalette::Base);
                     if (!isEnabled) {
                         PROPERTYORIGIN origin = PO_NOTFOUND;
                         pGetThemePropertyOrigin(theme.handle(), theme.partId, theme.stateId, TMT_FILLCOLOR, &origin);
                         // Use only if the fill property comes from our part
                         if ((origin == PO_PART || origin == PO_STATE)) {
                             COLORREF bgRef;
                             pGetThemeColor(theme.handle(), partId, stateId, TMT_FILLCOLOR, &bgRef);
                             fillColor = QBrush(qRgb(GetRValue(bgRef), GetGValue(bgRef), GetBValue(bgRef)));
                         }
                     }
                     p->fillRect(option->rect, fillColor);
                 }
             }
             if (panel->lineWidth > 0)
                 proxy()->drawPrimitive(PE_FrameLineEdit, panel, p, widget);
             return;
         }
         break;
     case PE_FrameTabWidget:
         if (const QStyleOptionTabWidgetFrame *tab = qstyleoption_cast<const QStyleOptionTabWidgetFrame *>(option))
         {
             name = QLatin1String("TAB");
             partId = TABP_PANE;
             if (widget) {
                 bool useGradient = true;
                 const int maxlength = 256;
                 wchar_t themeFileName[maxlength];
                 wchar_t themeColor[maxlength];
                 // Due to a a scaling issue with the XP Silver theme, tab gradients are not used with it
                 if (pGetCurrentThemeName(themeFileName, maxlength, themeColor, maxlength, NULL, 0) == S_OK) {
                     wchar_t *offset = 0;
                     if ((offset = wcsrchr(themeFileName, QChar(QLatin1Char('\\')).unicode())) != NULL) {
                         offset++;
                         if (!lstrcmp(offset, L"Luna.msstyles") && !lstrcmp(offset, L"Metallic")) {
                             useGradient = false;
                         }
                     }
                 }
                 // This should work, but currently there's an error in the ::drawBackgroundDirectly()
                 // code, when using the HDC directly..
                 if (useGradient) {
                     QStyleOptionTabWidgetFrameV2 frameOpt = *tab;
                     frameOpt.rect = widget->rect();
                     QRect contentsRect = subElementRect(SE_TabWidgetTabContents, &frameOpt, widget);
                     QRegion reg = option->rect;
                     reg -= contentsRect;
                     p->setClipRegion(reg);
                     XPThemeData theme(widget, p, name, partId, stateId, rect);
                     theme.mirrorHorizontally = hMirrored;
                     theme.mirrorVertically = vMirrored;
                     d->drawBackground(theme);
                     p->setClipRect(contentsRect);
                     partId = TABP_BODY;
                 }
             }
             switch (tab->shape) {
             case QTabBar::RoundedNorth:
             case QTabBar::TriangularNorth:
                 break;
             case QTabBar::RoundedSouth:
             case QTabBar::TriangularSouth:
                 vMirrored = true;
                 break;
             case QTabBar::RoundedEast:
             case QTabBar::TriangularEast:
                 rotate = 90;
                 break;
             case QTabBar::RoundedWest:
             case QTabBar::TriangularWest:
                 rotate = 90;
                 hMirrored = true;
                 break;
             default:
                 break;
             }
         }
         break;
     case PE_FrameMenu:
         p->save();
         p->setPen(option->palette.dark().color());
         p->drawRect(rect.adjusted(0, 0, -1, -1));
         p->restore();
         return;
     case PE_PanelMenuBar:
         break;
  case PE_FrameDockWidget:
      if (const QStyleOptionFrame *frm = qstyleoption_cast<const QStyleOptionFrame *>(option))
         {
             name = QLatin1String("WINDOW");
             if (flags & State_Active)
                 stateId = FS_ACTIVE;
             else
                 stateId = FS_INACTIVE;
             int fwidth = proxy()->pixelMetric(PM_DockWidgetFrameWidth, frm, widget);
             XPThemeData theme(widget, p, name, 0, stateId);
             if (!theme.isValid())
                 break;
             theme.rect = QRect(frm->rect.x(), frm->rect.y(), frm->rect.x()+fwidth, frm->rect.height()-fwidth);           theme.partId = WP_SMALLFRAMELEFT;
             d->drawBackground(theme);
             theme.rect = QRect(frm->rect.width()-fwidth, frm->rect.y(), fwidth, frm->rect.height()-fwidth);
             theme.partId = WP_SMALLFRAMERIGHT;
             d->drawBackground(theme);
             theme.rect = QRect(frm->rect.x(), frm->rect.bottom()-fwidth+1, frm->rect.width(), fwidth);
             theme.partId = WP_SMALLFRAMEBOTTOM;
             d->drawBackground(theme);
             return;
         }
         break;
     case PE_IndicatorHeaderArrow:
         {
 #if 0 // XP theme engine doesn't know about this :(
             name = QLatin1String("HEADER");
             partId = HP_HEADERSORTARROW;
             if (flags & State_Down)
                 stateId = HSAS_SORTEDDOWN;
             else
                 stateId = HSAS_SORTEDUP;
 #else
             if (const QStyleOptionHeader *header = qstyleoption_cast<const QStyleOptionHeader *>(option)) {
                 p->save();
                 p->setPen(option->palette.dark().color());
                 p->translate(0, option->rect.height()/2 - 4);
                 if (header->sortIndicator & QStyleOptionHeader::SortUp) { // invert logic to follow Windows style guide
                     p->drawLine(option->rect.x(), option->rect.y(), option->rect.x()+8, option->rect.y());
                     p->drawLine(option->rect.x()+1, option->rect.y()+1, option->rect.x()+7, option->rect.y()+1);
                     p->drawLine(option->rect.x()+2, option->rect.y()+2, option->rect.x()+6, option->rect.y()+2);
                     p->drawLine(option->rect.x()+3, option->rect.y()+3, option->rect.x()+5, option->rect.y()+3);
                     p->drawPoint(option->rect.x()+4, option->rect.y()+4);
                 } else if(header->sortIndicator & QStyleOptionHeader::SortDown) {
                     p->drawLine(option->rect.x(), option->rect.y()+4, option->rect.x()+8, option->rect.y()+4);
                     p->drawLine(option->rect.x()+1, option->rect.y()+3, option->rect.x()+7, option->rect.y()+3);
                     p->drawLine(option->rect.x()+2, option->rect.y()+2, option->rect.x()+6, option->rect.y()+2);
                     p->drawLine(option->rect.x()+3, option->rect.y()+1, option->rect.x()+5, option->rect.y()+1);
                     p->drawPoint(option->rect.x()+4, option->rect.y());
                 }
                 p->restore();
                 return;
             }
 #endif
         }
         break;
     case PE_FrameStatusBarItem:
         name = QLatin1String("STATUS");
         partId = SP_PANE;
         break;
     case PE_FrameGroupBox:
         name = QLatin1String("BUTTON");
         partId = BP_GROUPBOX;
         if (!(flags & State_Enabled))
             stateId = GBS_DISABLED;
         else
             stateId = GBS_NORMAL;
         if (const QStyleOptionFrame *frame = qstyleoption_cast<const QStyleOptionFrame *>(option)) {
             const QStyleOptionFrameV2 *frame2 = qstyleoption_cast<const QStyleOptionFrameV2 *>(option);
             if (frame2->features & QStyleOptionFrameV2::Flat) {
                 // Windows XP does not have a theme part for a flat GroupBox, paint it with the windows style
                 QRect fr = frame->rect;
                 QPoint p1(fr.x(), fr.y() + 1);
                 QPoint p2(fr.x() + fr.width(), p1.y() + 1);
                 rect = QRect(p1, p2);
                 name = QLatin1String("");
             }
         }
         break;
     case PE_IndicatorProgressChunk:
         {
         Qt::Orientation orient = Qt::Horizontal;
         bool inverted = false;
         if (const QStyleOptionProgressBarV2 *pb2 = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(option)) {
             orient = pb2->orientation;
             if (pb2->invertedAppearance)
                 inverted = true;
         }
         if (orient == Qt::Horizontal) {
             partId = PP_CHUNK;
             rect = QRect(option->rect.x(), option->rect.y(), option->rect.width(), option->rect.height() );
             if (inverted && option->direction == Qt::LeftToRight)
                 hMirrored = true;
         } else {
             partId = PP_CHUNKVERT;
             rect = QRect(option->rect.x(), option->rect.y(), option->rect.width(), option->rect.height());
         }
         name = QLatin1String("PROGRESS");
         stateId = 1;
         }
         break;
     case PE_Q3DockWindowSeparator:
         name = QLatin1String("TOOLBAR");
         if (flags & State_Horizontal)
             partId = TP_SEPARATOR;
         else
             partId = TP_SEPARATORVERT;
         break;
     case PE_FrameWindow:
         if (const QStyleOptionFrame *frm = qstyleoption_cast<const QStyleOptionFrame *>(option))
         {
             name = QLatin1String("WINDOW");
             if (flags & State_Active)
                 stateId = FS_ACTIVE;
             else
                 stateId = FS_INACTIVE;
             int fwidth = frm->lineWidth + frm->midLineWidth;
             XPThemeData theme(0, p, name, 0, stateId);
             if (!theme.isValid())
                 break;
             theme.rect = QRect(option->rect.x(), option->rect.y()+fwidth, option->rect.x()+fwidth, option->rect.height()-fwidth);
             theme.partId = WP_FRAMELEFT;
             d->drawBackground(theme);
             theme.rect = QRect(option->rect.width()-fwidth, option->rect.y()+fwidth, fwidth, option->rect.height()-fwidth);
             theme.partId = WP_FRAMERIGHT;
             d->drawBackground(theme);
             theme.rect = QRect(option->rect.x(), option->rect.height()-fwidth, option->rect.width(), fwidth);
             theme.partId = WP_FRAMEBOTTOM;
             d->drawBackground(theme);
             theme.rect = QRect(option->rect.x(), option->rect.y(), option->rect.width(), option->rect.y()+fwidth);
             theme.partId = WP_CAPTION;
             d->drawBackground(theme);
             return;
         }
         break;
     case PE_IndicatorBranch:
         {
             static const int decoration_size = 9;
             int mid_h = option->rect.x() + option->rect.width() / 2;
             int mid_v = option->rect.y() + option->rect.height() / 2;
             int bef_h = mid_h;
             int bef_v = mid_v;
             int aft_h = mid_h;
             int aft_v = mid_v;
             QBrush brush(option->palette.dark().color(), Qt::Dense4Pattern);
             if (option->state & State_Item) {
                 if (option->direction == Qt::RightToLeft)
                     p->fillRect(option->rect.left(), mid_v, bef_h - option->rect.left(), 1, brush);
                 else
                     p->fillRect(aft_h, mid_v, option->rect.right() - aft_h + 1, 1, brush);
             }
             if (option->state & State_Sibling)
                 p->fillRect(mid_h, aft_v, 1, option->rect.bottom() - aft_v + 1, brush);
             if (option->state & (State_Open | State_Children | State_Item | State_Sibling))
                 p->fillRect(mid_h, option->rect.y(), 1, bef_v - option->rect.y(), brush);
             if (option->state & State_Children) {
                 int delta = decoration_size / 2;
                 bef_h -= delta;
                 bef_v -= delta;
                 aft_h += delta;
                 aft_v += delta;
                 XPThemeData theme(0, p, QLatin1String("TREEVIEW"));
                 theme.rect = QRect(bef_h, bef_v, decoration_size, decoration_size);
                 theme.partId = TVP_GLYPH;
                 theme.stateId = flags & QStyle::State_Open ? GLPS_OPENED : GLPS_CLOSED;
                 d->drawBackground(theme);
             }
         }
         return;
     case PE_IndicatorToolBarSeparator:
         if (option->rect.height() < 3) {
             // XP style requires a few pixels for the separator
             // to be visible.
             QWindowsStyle::drawPrimitive(pe, option, p, widget);
             return;
         }
         name = QLatin1String("TOOLBAR");
         partId = TP_SEPARATOR;
         if (option->state & State_Horizontal)
             partId = TP_SEPARATOR;
         else
             partId = TP_SEPARATORVERT;
         break;
     case PE_IndicatorToolBarHandle:
         name = QLatin1String("REBAR");
         partId = RP_GRIPPER;
         if (option->state & State_Horizontal) {
             partId = RP_GRIPPER;
             rect.adjust(0, 0, -2, 0);
         }
         else {
             partId = RP_GRIPPERVERT;
             rect.adjust(0, 0, 0, -2);
         }
         break;
     case PE_IndicatorItemViewItemCheck: {
         QStyleOptionButton button;
         button.QStyleOption::operator=(*option);
         button.state &= ~State_MouseOver;
         proxy()->drawPrimitive(PE_IndicatorCheckBox, &button, p, widget);
         return;
     }
     default:
         break;
     }
     XPThemeData theme(0, p, name, partId, stateId, rect);
     if (!theme.isValid()) {
         QWindowsStyle::drawPrimitive(pe, option, p, widget);
         return;
     }
     theme.mirrorHorizontally = hMirrored;
     theme.mirrorVertically = vMirrored;
     theme.noBorder = noBorder;
     theme.noContent = noContent;
     theme.rotate = rotate;
     d->drawBackground(theme);
 }
pixelMetric()
int QWindowsXPStyle::pixelMetric (PixelMetric pm, const QStyleOption * option = 0, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 3282 of file qwindowsxpstyle.cpp.
Referenced by drawComplexControl(), drawControl(), QWindowsVistaStyle::pixelMetric(), and sizeFromContents().
 {
     if (!QWindowsXPStylePrivate::useXP())
         return QWindowsStyle::pixelMetric(pm, option, widget);
     int res = 0;
     switch (pm) {
     case PM_MenuBarPanelWidth:
         res = 0;
         break;
     case PM_DefaultFrameWidth:
         if (qobject_cast<const QListView*>(widget))
             res = 2;
         else
             res = 1;
         break;
     case PM_MenuPanelWidth:
     case PM_SpinBoxFrameWidth:
         res = 1;
         break;
     case PM_TabBarTabOverlap:
     case PM_MenuHMargin:
     case PM_MenuVMargin:
         res = 2;
         break;
     case PM_TabBarBaseOverlap:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(option)) {
             switch (tab->shape) {
             case QTabBar::RoundedNorth:
             case QTabBar::TriangularNorth:
                 res = 1;
                 break;
             case QTabBar::RoundedSouth:
             case QTabBar::TriangularSouth:
                 res = 2;
                 break;
             case QTabBar::RoundedEast:
             case QTabBar::TriangularEast:
                 res = 3;
                 break;
             case QTabBar::RoundedWest:
             case QTabBar::TriangularWest:
                 res = 1;
                 break;
             }
         }
         break;
     case PM_SplitterWidth:
         res = qMax(int(QStyleHelper::dpiScaled(5.)), QApplication::globalStrut().width());
         break;
     case PM_IndicatorWidth:
     case PM_IndicatorHeight:
         {
             XPThemeData theme(widget, 0, QLatin1String("BUTTON"), BP_CHECKBOX, CBS_UNCHECKEDNORMAL);
             if (theme.isValid()) {
                 SIZE size;
                 pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                 res = (pm == PM_IndicatorWidth) ? size.cx : size.cy;
             }
         }
         break;
     case PM_ExclusiveIndicatorWidth:
     case PM_ExclusiveIndicatorHeight:
         {
             XPThemeData theme(widget, 0, QLatin1String("BUTTON"), BP_RADIOBUTTON, RBS_UNCHECKEDNORMAL);
             if (theme.isValid()) {
                 SIZE size;
                 pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                 res = (pm == PM_ExclusiveIndicatorWidth) ? size.cx : size.cy;
             }
         }
         break;
     case PM_ProgressBarChunkWidth:
         {
             Qt::Orientation orient = Qt::Horizontal;
             if (const QStyleOptionProgressBarV2 *pb2 = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(option))
                 orient = pb2->orientation;
             XPThemeData theme(widget, 0, QLatin1String("PROGRESS"), (orient == Qt::Horizontal) ? PP_CHUNK : PP_CHUNKVERT);
             if (theme.isValid()) {
                 SIZE size;
                 pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                 res = (orient == Qt::Horizontal) ? size.cx : size.cy;
             }
         }
         break;
     case PM_SliderThickness:
         {
             XPThemeData theme(widget, 0, QLatin1String("TRACKBAR"), TKP_THUMB);
             if (theme.isValid()) {
                 SIZE size;
                 pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                 res = size.cy;
             }
         }
         break;
     case PM_TitleBarHeight:
         {
 #ifdef QT3_SUPPORT
             if (widget && widget->inherits("Q3DockWindowTitleBar")) {
                 res = GetSystemMetrics(SM_CYSMCAPTION) + GetSystemMetrics(SM_CXSIZEFRAME);
             } else
 #endif
             if (widget && (widget->windowType() == Qt::Tool))
                 res = GetSystemMetrics(SM_CYSMCAPTION) + GetSystemMetrics(SM_CXSIZEFRAME);
             else
                 res = GetSystemMetrics(SM_CYCAPTION) + GetSystemMetrics(SM_CXSIZEFRAME);
         }
         break;
     case PM_MdiSubWindowFrameWidth:
         {
             XPThemeData theme(widget, 0, QLatin1String("WINDOW"), WP_FRAMELEFT, FS_ACTIVE);
             if (theme.isValid()) {
                 SIZE size;
                 pGetThemePartSize(theme.handle(), 0, WP_FRAMELEFT, FS_ACTIVE, 0, TS_TRUE, &size);
                 res = size.cx-1;
             }
         }
         break;
     case PM_MdiSubWindowMinimizedWidth:
         res = 160;
         break;
 #ifndef QT_NO_TOOLBAR
     case PM_ToolBarHandleExtent:
         res = int(QStyleHelper::dpiScaled(8.));
         break;
 #endif // QT_NO_TOOLBAR
     case PM_DockWidgetFrameWidth:
     {
         XPThemeData theme(widget, 0, QLatin1String("WINDOW"), WP_SMALLFRAMERIGHT, FS_ACTIVE);
         if (theme.isValid()) {
             SIZE size;
             pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
             res = size.cx;
         }
     }
     break;
     case PM_DockWidgetSeparatorExtent:
         res = int(QStyleHelper::dpiScaled(4.));
         break;
     case PM_DockWidgetTitleMargin:
         res = int(QStyleHelper::dpiScaled(4.));
         break;
     case PM_ButtonShiftHorizontal:
     case PM_ButtonShiftVertical:
         if (qstyleoption_cast<const QStyleOptionToolButton *>(option))
             res = 1;
         else
             res = 0;
         break;
     case PM_ButtonDefaultIndicator:
         res = 0;
         break;
     default:
         res = QWindowsStyle::pixelMetric(pm, option, widget);
     }
     return res;
 }
polish() [1/3]
void QWindowsXPStyle::polish (QApplication * app) virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1131 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::polish().
 {
     QWindowsStyle::polish(app);
     if (!QWindowsXPStylePrivate::useXP())
         return;
 }
polish() [2/3]
void QWindowsXPStyle::polish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1139 of file qwindowsxpstyle.cpp.
 {
     QWindowsStyle::polish(widget);
     if (!QWindowsXPStylePrivate::useXP())
         return;
     if (qobject_cast<QAbstractButton*>(widget)
         || qobject_cast<QToolButton*>(widget)
         || qobject_cast<QTabBar*>(widget)
 #ifndef QT_NO_COMBOBOX
         || qobject_cast<QComboBox*>(widget)
 #endif // QT_NO_COMBOBOX
         || qobject_cast<QScrollBar*>(widget)
         || qobject_cast<QSlider*>(widget)
         || qobject_cast<QHeaderView*>(widget)
 #ifndef QT_NO_SPINBOX
         || qobject_cast<QAbstractSpinBox*>(widget)
         || qobject_cast<QSpinBox*>(widget)
 #endif // QT_NO_SPINBOX
         || widget->inherits("QWorkspaceChild")
         || widget->inherits("Q3TitleBar"))
         widget->setAttribute(Qt::WA_Hover);
 #ifndef QT_NO_RUBBERBAND
     if (qobject_cast<QRubberBand*>(widget)) {
         widget->setWindowOpacity(0.6);
     }
 #endif
     if (qobject_cast<QStackedWidget*>(widget) &&
                qobject_cast<QTabWidget*>(widget->parent()))
         widget->parentWidget()->setAttribute(Qt::WA_ContentsPropagated);
     Q_D(QWindowsXPStyle);
     if (!d->hasInitColors) {
         // Get text color for group box labels
         COLORREF cref;
         XPThemeData theme(0, 0, QLatin1String("BUTTON"), 0, 0);
         pGetThemeColor(theme.handle(), BP_GROUPBOX, GBS_NORMAL, TMT_TEXTCOLOR, &cref);
         d->groupBoxTextColor = qRgb(GetRValue(cref), GetGValue(cref), GetBValue(cref));
         pGetThemeColor(theme.handle(), BP_GROUPBOX, GBS_DISABLED, TMT_TEXTCOLOR, &cref);
         d->groupBoxTextColorDisabled = qRgb(GetRValue(cref), GetGValue(cref), GetBValue(cref));
         // Where does this color come from?
         //pGetThemeColor(theme.handle(), TKP_TICS, TSS_NORMAL, TMT_COLOR, &cref);
         d->sliderTickColor = qRgb(165, 162, 148);
         d->hasInitColors = true;
     }
 }
polish() [3/3]
void QWindowsXPStyle::polish (QPalette & pal) virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1188 of file qwindowsxpstyle.cpp.
 {
     QWindowsStyle::polish(pal);
     pal.setBrush(QPalette::AlternateBase, pal.base().color().darker(110));
 }
sizeFromContents()
QSize QWindowsXPStyle::sizeFromContents (ContentsType ct, const QStyleOption * option, const QSize & contentsSize, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 3709 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::sizeFromContents().
 {
     if (!QWindowsXPStylePrivate::useXP())
         return QWindowsStyle::sizeFromContents(ct, option, contentsSize, widget);
     QSize sz(contentsSize);
     switch (ct) {
     case CT_LineEdit:
     case CT_ComboBox:
         {
             XPThemeData buttontheme(widget, 0, QLatin1String("Button"));
             HTHEME theme = buttontheme.handle();
             MARGINS borderSize;
             if (theme) {
                 int result = pGetThemeMargins(theme,
                                               NULL,
                                               BP_PUSHBUTTON,
                                               PBS_NORMAL,
                                               TMT_CONTENTMARGINS,
                                               NULL,
                                               &borderSize);
                 if (result == S_OK) {
                     sz += QSize(borderSize.cxLeftWidth + borderSize.cxRightWidth - 2,
                                 borderSize.cyBottomHeight + borderSize.cyTopHeight - 2);
                 }
                 const int textMargins = 2*(proxy()->pixelMetric(PM_FocusFrameHMargin) + 1);
                 sz += QSize(qMax(pixelMetric(QStyle::PM_ScrollBarExtent, option, widget)
                                  + textMargins, 23), 0); //arrow button
             }
         }
         break;
     case CT_SpinBox:
         {
             //Spinbox adds frame twice
             sz = QWindowsStyle::sizeFromContents(ct, option, contentsSize, widget);
             int border = proxy()->pixelMetric(PM_SpinBoxFrameWidth, option, widget);
             sz -= QSize(2*border, 2*border);
         }
         break;
     case CT_TabWidget:
         sz += QSize(6, 6);
         break;
     case CT_Menu:
         sz += QSize(1, 0);
         break;
 #ifndef QT_NO_MENUBAR
     case CT_MenuBarItem:
         if (!sz.isEmpty())
             sz += QSize(windowsItemHMargin * 5 + 1, 6);
         break;
 #endif
     case CT_MenuItem:
         if (const QStyleOptionMenuItem *menuitem = qstyleoption_cast<const QStyleOptionMenuItem *>(option))
         {
             if (menuitem->menuItemType != QStyleOptionMenuItem::Separator) {
                 sz = QWindowsStyle::sizeFromContents(ct, option, sz, widget);
                 sz.setHeight(sz.height() - 2);
                 return sz;
             }
         }
         sz = QWindowsStyle::sizeFromContents(ct, option, sz, widget);
         break;
     case CT_MdiControls:
         if (const QStyleOptionComplex *styleOpt = qstyleoption_cast<const QStyleOptionComplex *>(option)) {
             int width = 0;
             if (styleOpt->subControls & SC_MdiMinButton)
                 width += 17 + 1;
             if (styleOpt->subControls & SC_MdiNormalButton)
                 width += 17 + 1;
             if (styleOpt->subControls & SC_MdiCloseButton)
                 width += 17 + 1;
             sz = QSize(width, 19);
         } else {
             sz = QSize(54, 19);
         }
         break;
     default:
         sz = QWindowsStyle::sizeFromContents(ct, option, sz, widget);
         break;
     }
     return sz;
 }
standardIconImplementation
QIcon QWindowsXPStyle::standardIconImplementation (StandardPixmap standardIcon, const QStyleOption * option, const QWidget * widget = 0) const protected slot
Warning
This function is not part of the public interface.
Definition at line 3915 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::standardIconImplementation().
 {
     if (!QWindowsXPStylePrivate::useXP()) {
         return QWindowsStyle::standardIconImplementation(standardIcon, option, widget);
     }
     QWindowsXPStylePrivate *d = const_cast<QWindowsXPStylePrivate*>(d_func());
     switch(standardIcon) {
     case SP_TitleBarMaxButton:
         if (qstyleoption_cast<const QStyleOptionDockWidget *>(option))
         {
             if (d->dockFloat.isNull()) {
                 XPThemeData themeSize(0, 0, QLatin1String("WINDOW"), WP_SMALLCLOSEBUTTON, CBS_NORMAL);
                 XPThemeData theme(0, 0, QLatin1String("WINDOW"), WP_MAXBUTTON, MAXBS_NORMAL);
                 if (theme.isValid()) {
                     SIZE size;
                     pGetThemePartSize(themeSize.handle(), 0, themeSize.partId, themeSize.stateId, 0, TS_TRUE, &size);
                     QPixmap pm = QPixmap(size.cx, size.cy);
                     pm.fill(Qt::transparent);
                     QPainter p(&pm);
                     theme.painter = &p;
                     theme.rect = QRect(0, 0, size.cx, size.cy);
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Normal, QIcon::Off);    // Normal
                     pm.fill(Qt::transparent);
                     theme.stateId = MAXBS_PUSHED;
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Normal, QIcon::On);     // Pressed
                     pm.fill(Qt::transparent);
                     theme.stateId = MAXBS_HOT;
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Active, QIcon::Off);    // Hover
                     pm.fill(Qt::transparent);
                     theme.stateId = MAXBS_INACTIVE;
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Disabled, QIcon::Off);  // Disabled
                 }
             }
             if (widget && widget->isWindow())
                 return d->dockFloat;
         }
         break;
     case SP_TitleBarCloseButton:
         if (qstyleoption_cast<const QStyleOptionDockWidget *>(option))
         {
             if (d->dockClose.isNull()) {
                 XPThemeData theme(0, 0, QLatin1String("WINDOW"), WP_SMALLCLOSEBUTTON, CBS_NORMAL);
                 if (theme.isValid()) {
                     SIZE size;
                     pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &size);
                     QPixmap pm = QPixmap(size.cx, size.cy);
                     pm.fill(Qt::transparent);
                     QPainter p(&pm);
                     theme.painter = &p;
                     theme.partId = WP_CLOSEBUTTON; // ####
                     theme.rect = QRect(0, 0, size.cx, size.cy);
                     d->drawBackground(theme);
                     d->dockClose.addPixmap(pm, QIcon::Normal, QIcon::Off);    // Normal
                     pm.fill(Qt::transparent);
                     theme.stateId = CBS_PUSHED;
                     d->drawBackground(theme);
                     d->dockClose.addPixmap(pm, QIcon::Normal, QIcon::On);     // Pressed
                     pm.fill(Qt::transparent);
                     theme.stateId = CBS_HOT;
                     d->drawBackground(theme);
                     d->dockClose.addPixmap(pm, QIcon::Active, QIcon::Off);    // Hover
                     pm.fill(Qt::transparent);
                     theme.stateId = CBS_INACTIVE;
                     d->drawBackground(theme);
                     d->dockClose.addPixmap(pm, QIcon::Disabled, QIcon::Off);  // Disabled
                 }
             }
             if (widget && widget->isWindow())
                 return d->dockClose;
         }
         break;
     case SP_TitleBarNormalButton:
         if (qstyleoption_cast<const QStyleOptionDockWidget *>(option))
         {
             if (d->dockFloat.isNull()) {
                 XPThemeData themeSize(0, 0, QLatin1String("WINDOW"), WP_SMALLCLOSEBUTTON, CBS_NORMAL);
                 XPThemeData theme(0, 0, QLatin1String("WINDOW"), WP_RESTOREBUTTON, RBS_NORMAL);
                 if (theme.isValid()) {
                     SIZE size;
                     pGetThemePartSize(themeSize.handle(), 0, themeSize.partId, themeSize.stateId, 0, TS_TRUE, &size);
                     QPixmap pm = QPixmap(size.cx, size.cy);
                     pm.fill(Qt::transparent);
                     QPainter p(&pm);
                     theme.painter = &p;
                     theme.rect = QRect(0, 0, size.cx, size.cy);
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Normal, QIcon::Off);    // Normal
                     pm.fill(Qt::transparent);
                     theme.stateId = RBS_PUSHED;
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Normal, QIcon::On);     // Pressed
                     pm.fill(Qt::transparent);
                     theme.stateId = RBS_HOT;
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Active, QIcon::Off);    // Hover
                     pm.fill(Qt::transparent);
                     theme.stateId = RBS_INACTIVE;
                     d->drawBackground(theme);
                     d->dockFloat.addPixmap(pm, QIcon::Disabled, QIcon::Off);  // Disabled
                 }
             }
             if (widget && widget->isWindow())
                 return d->dockFloat;
         }
         break;
     default:
         break;
     }
     return QWindowsStyle::standardIconImplementation(standardIcon, option, widget);
 }
standardPalette()
QPalette QWindowsXPStyle::standardPalette () const virtual
Reimplemented Function
Reimplemented from QStyle.
Definition at line 3874 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::standardPalette().
 {
     if (QWindowsXPStylePrivate::useXP() && QApplicationPrivate::sys_pal)
         return *QApplicationPrivate::sys_pal;
     else
         return QWindowsStyle::standardPalette();
 }
standardPixmap()
QPixmap QWindowsXPStyle::standardPixmap (StandardPixmap standardIcon, const QStyleOption * option, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 3885 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::standardPixmap().
 {
     if (!QWindowsXPStylePrivate::useXP())
         return QWindowsStyle::standardPixmap(standardPixmap, option, widget);
     switch(standardPixmap) {
     case SP_TitleBarMaxButton:
     case SP_TitleBarCloseButton:
         if (qstyleoption_cast<const QStyleOptionDockWidget *>(option))
         {
             if (widget && widget->isWindow()) {
                 XPThemeData theme(widget, 0, QLatin1String("WINDOW"), WP_SMALLCLOSEBUTTON, CBS_NORMAL);
                 if (theme.isValid()) {
                     SIZE sz;
                     pGetThemePartSize(theme.handle(), 0, theme.partId, theme.stateId, 0, TS_TRUE, &sz);
                     return QIcon(QWindowsStyle::standardPixmap(standardPixmap, option, widget)).pixmap(QSize(sz.cx, sz.cy));
                 }
             }
         }
         break;
     default:
         break;
     }
     return QWindowsStyle::standardPixmap(standardPixmap, option, widget);
 }
styleHint()
int QWindowsXPStyle::styleHint (StyleHint hint, const QStyleOption * option = 0, const QWidget * widget = 0, QStyleHintReturn * returnData = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 3798 of file qwindowsxpstyle.cpp.
Referenced by drawControl(), and QWindowsVistaStyle::styleHint().
 {
   QWindowsXPStylePrivate *d = const_cast<QWindowsXPStylePrivate*>(d_func());
     if (!QWindowsXPStylePrivate::useXP())
         return QWindowsStyle::styleHint(hint, option, widget, returnData);
     int res = 0;
     switch (hint) {
     case SH_EtchDisabledText:
         res = (qobject_cast<const QLabel*>(widget) != 0);
         break;
     case SH_SpinControls_DisableOnBounds:
         res = 0;
         break;
     case SH_TitleBar_AutoRaise:
     case SH_TitleBar_NoBorder:
         res = 1;
         break;
     case SH_GroupBox_TextLabelColor:
         if (!widget || (widget && widget->isEnabled()))
             res = d->groupBoxTextColor;
         else
             res = d->groupBoxTextColorDisabled;
         break;
     case SH_Table_GridLineColor:
         res = 0xC0C0C0;
         break;
     case SH_WindowFrame_Mask:
         {
             res = 1;
             QStyleHintReturnMask *mask = qstyleoption_cast<QStyleHintReturnMask *>(returnData);
             const QStyleOptionTitleBar *titlebar = qstyleoption_cast<const QStyleOptionTitleBar *>(option);
             if (mask && titlebar) {
                 // Note certain themes will not return the whole window frame but only the titlebar part when
                 // queried This function needs to return the entire window mask, hence we will only fetch the mask for the
                 // titlebar itself and add the remaining part of the window rect at the bottom.
                 int tbHeight = proxy()->pixelMetric(PM_TitleBarHeight, option, widget);
                 QRect titleBarRect = option->rect;
                 titleBarRect.setHeight(tbHeight);
                 XPThemeData themeData;
                 if (titlebar->titleBarState & Qt::WindowMinimized) {
                     themeData = XPThemeData(widget, 0, QLatin1String("WINDOW"), WP_MINCAPTION, CS_ACTIVE, titleBarRect);
                 } else
                     themeData = XPThemeData(widget, 0, QLatin1String("WINDOW"), WP_CAPTION, CS_ACTIVE, titleBarRect);
                 mask->region = d->region(themeData) +
                                QRect(0, tbHeight, option->rect.width(), option->rect.height() - tbHeight);
             }
         }
         break;
 #ifndef QT_NO_RUBBERBAND
     case SH_RubberBand_Mask:
         if (qstyleoption_cast<const QStyleOptionRubberBand *>(option)) {
             res = 0;
             break;
         }
 #endif // QT_NO_RUBBERBAND
     case SH_ItemView_DrawDelegateFrame:
         res = 1;
         break;
     default:
         res =QWindowsStyle::styleHint(hint, option, widget, returnData);
     }
     return res;
 }
subControlRect()
QRect QWindowsXPStyle::subControlRect (ComplexControl cc, const QStyleOptionComplex * option, SubControl sc, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Definition at line 3511 of file qwindowsxpstyle.cpp.
Referenced by drawComplexControl(), and QWindowsVistaStyle::subControlRect().
 {
     if (!QWindowsXPStylePrivate::useXP())
         return QWindowsStyle::subControlRect(cc, option, subControl, widget);
     QRect rect;
     switch (cc) {
     case CC_TitleBar:
         if (const QStyleOptionTitleBar *tb = qstyleoption_cast<const QStyleOptionTitleBar *>(option)) {
             if (!buttonVisible(subControl, tb))
                 return rect;
             const bool isToolTitle = false;
             const int height = tb->rect.height();
             const int width = tb->rect.width();
             int buttonHeight = GetSystemMetrics(SM_CYSIZE) - 4;
             int buttonWidth = GetSystemMetrics(SM_CXSIZE) - 4;
             const int delta = buttonWidth + 2;
             int controlTop = option->rect.bottom() - buttonHeight - 2;
             const int frameWidth = proxy()->pixelMetric(PM_MdiSubWindowFrameWidth, option, widget);
             const bool sysmenuHint  = (tb->titleBarFlags & Qt::WindowSystemMenuHint) != 0;
             const bool minimizeHint = (tb->titleBarFlags & Qt::WindowMinimizeButtonHint) != 0;
             const bool maximizeHint = (tb->titleBarFlags & Qt::WindowMaximizeButtonHint) != 0;
             const bool contextHint = (tb->titleBarFlags & Qt::WindowContextHelpButtonHint) != 0;
             const bool shadeHint = (tb->titleBarFlags & Qt::WindowShadeButtonHint) != 0;
             bool isMinimized = tb->titleBarState & Qt::WindowMinimized;
             bool isMaximized = tb->titleBarState & Qt::WindowMaximized;
             int offset = 0;
             switch (subControl) {
             case SC_TitleBarLabel:
                 rect = QRect(frameWidth, 0, width - (buttonWidth + frameWidth + 10), height);
                 if (isToolTitle) {
                     if (sysmenuHint) {
                         rect.adjust(0, 0, -buttonWidth - 3, 0);
                     }
                     if (minimizeHint || maximizeHint)
                         rect.adjust(0, 0, -buttonWidth - 2, 0);
                 } else {
                     if (sysmenuHint) {
                         const int leftOffset = height - 8;
                         rect.adjust(leftOffset, 0, 0, 0);
                     }
                     if (minimizeHint)
                         rect.adjust(0, 0, -buttonWidth - 2, 0);
                     if (maximizeHint)
                         rect.adjust(0, 0, -buttonWidth - 2, 0);
                     if (contextHint)
                         rect.adjust(0, 0, -buttonWidth - 2, 0);
                     if (shadeHint)
                         rect.adjust(0, 0, -buttonWidth - 2, 0);
                 }
                 break;
             case SC_TitleBarContextHelpButton:
                 if (tb->titleBarFlags & Qt::WindowContextHelpButtonHint)
                     offset += delta;
                 //fall through
             case SC_TitleBarMinButton:
                 if (!isMinimized && (tb->titleBarFlags & Qt::WindowMinimizeButtonHint))
                     offset += delta;
                 else if (subControl == SC_TitleBarMinButton)
                     break;
                 //fall through
             case SC_TitleBarNormalButton:
                 if (isMinimized && (tb->titleBarFlags & Qt::WindowMinimizeButtonHint))
                     offset += delta;
                 else if (isMaximized && (tb->titleBarFlags & Qt::WindowMaximizeButtonHint))
                     offset += delta;
                 else if (subControl == SC_TitleBarNormalButton)
                     break;
                 //fall through
             case SC_TitleBarMaxButton:
                 if (!isMaximized && (tb->titleBarFlags & Qt::WindowMaximizeButtonHint))
                     offset += delta;
                 else if (subControl == SC_TitleBarMaxButton)
                     break;
                 //fall through
             case SC_TitleBarShadeButton:
                 if (!isMinimized && (tb->titleBarFlags & Qt::WindowShadeButtonHint))
                     offset += delta;
                 else if (subControl == SC_TitleBarShadeButton)
                     break;
                 //fall through
             case SC_TitleBarUnshadeButton:
                 if (isMinimized && (tb->titleBarFlags & Qt::WindowShadeButtonHint))
                     offset += delta;
                 else if (subControl == SC_TitleBarUnshadeButton)
                     break;
                 //fall through
             case SC_TitleBarCloseButton:
                 if (tb->titleBarFlags & Qt::WindowSystemMenuHint)
                     offset += delta;
                 else if (subControl == SC_TitleBarCloseButton)
                     break;
                 rect.setRect(width - offset - controlTop + 1, controlTop,
                              buttonWidth, buttonHeight);
                 break;
             case SC_TitleBarSysMenu:
                 {
                     const int controlTop = 6;
                     const int controlHeight = height - controlTop - 3;
                     const int iconExtent = proxy()->pixelMetric(PM_SmallIconSize);
                     QSize iconSize = tb->icon.actualSize(QSize(iconExtent, iconExtent));
                     if (tb->icon.isNull())
                         iconSize = QSize(controlHeight, controlHeight);
                     int hPad = (controlHeight - iconSize.height())/2;
                     int vPad = (controlHeight - iconSize.width())/2;
                     rect = QRect(frameWidth + hPad, controlTop + vPad, iconSize.width(), iconSize.height());
                 }
                 break;
             default:
                 break;
             }
         }
         break;
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cmb = qstyleoption_cast<const QStyleOptionComboBox *>(option)) {
             int x = cmb->rect.x(), y = cmb->rect.y(), wi = cmb->rect.width(), he = cmb->rect.height();
             int xpos = x;
             xpos += wi - 1 - 16;
             switch (subControl) {
             case SC_ComboBoxFrame:
                 rect = cmb->rect;
                 break;
             case SC_ComboBoxArrow:
                 rect = QRect(xpos, y+1, 16, he-2);
                 break;
             case SC_ComboBoxEditField:
                 rect = QRect(x+2, y+2, wi-3-16, he-4);
                 break;
             case SC_ComboBoxListBoxPopup:
                 rect = cmb->rect;
                 break;
             default:
                 break;
             }
         }
         break;
 #ifndef QT_NO_WORKSPACE
     case CC_MdiControls:
     {
         int numSubControls = 0;
         if (option->subControls & SC_MdiCloseButton)
             ++numSubControls;
         if (option->subControls & SC_MdiMinButton)
             ++numSubControls;
         if (option->subControls & SC_MdiNormalButton)
             ++numSubControls;
         if (numSubControls == 0)
             break;
         int buttonWidth = option->rect.width()/ numSubControls;
         int offset = 0;
         switch (subControl) {
         case SC_MdiCloseButton:
             // Only one sub control, no offset needed.
             if (numSubControls == 1)
                 break;
             offset += buttonWidth;
             //FALL THROUGH
         case SC_MdiNormalButton:
             // No offset needed if
             // 1) There's only one sub control
             // 2) We have a close button and a normal button (offset already added in SC_MdiClose)
             if (numSubControls == 1 || (numSubControls == 2 && !(option->subControls & SC_MdiMinButton)))
                 break;
             if (option->subControls & SC_MdiNormalButton)
                 offset += buttonWidth;
             break;
         default:
             break;
         }
         rect = QRect(offset, 0, buttonWidth, option->rect.height());
         break;
     }
 #endif // QT_NO_WORKSPACE
     default:
         rect = visualRect(option->direction, option->rect,
                           QWindowsStyle::subControlRect(cc, option, subControl, widget));
         break;
     }
     return visualRect(option->direction, option->rect, rect);
 }
subElementRect()
QRect QWindowsXPStyle::subElementRect (SubElement r, const QStyleOption * option, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1237 of file qwindowsxpstyle.cpp.
Referenced by drawComplexControl(), drawPrimitive(), and QWindowsVistaStyle::subElementRect().
 {
     if (!QWindowsXPStylePrivate::useXP()) {
         return QWindowsStyle::subElementRect(sr, option, widget);
     }
     QRect rect(option->rect);
     switch(sr) {
     case SE_DockWidgetCloseButton:
     case SE_DockWidgetFloatButton:
         rect = QWindowsStyle::subElementRect(sr, option, widget);
         return rect.translated(0, 1);
     break;
     case SE_TabWidgetTabContents:
         if (qstyleoption_cast<const QStyleOptionTabWidgetFrame *>(option))
         {
             rect = QWindowsStyle::subElementRect(sr, option, widget);
             if (sr == SE_TabWidgetTabContents) {
                 if (const QTabWidget *tabWidget = qobject_cast<const QTabWidget *>(widget)) {
                     if (tabWidget->documentMode())
                         break;
                 }
                 rect.adjust(0, 0, -2, -2);
             }
         }
         break;
     case SE_TabWidgetTabBar: {
         rect = QWindowsStyle::subElementRect(sr, option, widget);
         const QStyleOptionTabWidgetFrame *twfOption =
             qstyleoption_cast<const QStyleOptionTabWidgetFrame *>(option);
         if (twfOption && twfOption->direction == Qt::RightToLeft
             && (twfOption->shape == QTabBar::RoundedNorth
                 || twfOption->shape == QTabBar::RoundedSouth))
         {
             QStyleOptionTab otherOption;
             otherOption.shape = (twfOption->shape == QTabBar::RoundedNorth
                                 ? QTabBar::RoundedEast : QTabBar::RoundedSouth);
             int overlap = proxy()->pixelMetric(PM_TabBarBaseOverlap, &otherOption, widget);
             int borderThickness = proxy()->pixelMetric(PM_DefaultFrameWidth, option, widget);
             rect.adjust(-overlap + borderThickness, 0, -overlap + borderThickness, 0);
         }
         break;}
     case SE_PushButtonContents:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(option)) {
             MARGINS borderSize;
             if (widget) {
                 XPThemeData buttontheme(widget, 0, QLatin1String("Button"));
                 HTHEME theme = buttontheme.handle();
                 if (theme) {
                     int stateId;
                     if (!(option->state & State_Enabled))
                         stateId = PBS_DISABLED;
                     else if (option->state & State_Sunken)
                         stateId = PBS_PRESSED;
                     else if (option->state & State_MouseOver)
                         stateId = PBS_HOT;
                     else if (btn->features & QStyleOptionButton::DefaultButton)
                         stateId = PBS_DEFAULTED;
                     else
                         stateId = PBS_NORMAL;
                     int border = proxy()->pixelMetric(PM_DefaultFrameWidth, btn, widget);
                     rect = option->rect.adjusted(border, border, -border, -border);
                     int result = pGetThemeMargins(theme,
                                                   NULL,
                                                   BP_PUSHBUTTON,
                                                   stateId,
                                                   TMT_CONTENTMARGINS,
                                                   NULL,
                                                   &borderSize);
                     if (result == S_OK) {
                         rect.adjust(borderSize.cxLeftWidth, borderSize.cyTopHeight,
                                     -borderSize.cxRightWidth, -borderSize.cyBottomHeight);
                         rect = visualRect(option->direction, option->rect, rect);
                     }
                 }
             }
         }
         break;
     case SE_ProgressBarContents:
         rect = QCommonStyle::subElementRect(SE_ProgressBarGroove, option, widget);
         if (option->state & QStyle::State_Horizontal)
             rect.adjust(4, 3, -4, -3);
         else
             rect.adjust(3, 2, -3, -2);
         break;
     default:
         rect = QWindowsStyle::subElementRect(sr, option, widget);
     }
     return rect;
 }
unpolish() [1/2]
void QWindowsXPStyle::unpolish (QApplication * app) virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1125 of file qwindowsxpstyle.cpp.
Referenced by QWindowsVistaStyle::unpolish().
 {
     QWindowsStyle::unpolish(app);
 }
unpolish() [2/2]
void QWindowsXPStyle::unpolish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QWindowsStyle.
Definition at line 1195 of file qwindowsxpstyle.cpp.
 {
 #ifndef QT_NO_RUBBERBAND
     if (qobject_cast<QRubberBand*>(widget)) {
         widget->setWindowOpacity(1.0);
     }
 #endif
     Q_D(QWindowsXPStyle);
     // Unpolish of widgets is the first thing that
     // happens when a theme changes, or the theme
     // engine is turned off. So we detect it here.
     bool oldState = QWindowsXPStylePrivate::useXP();
     bool newState = QWindowsXPStylePrivate::useXP(true);
     if ((oldState != newState) && newState) {
         d->cleanup(true);
         d->init(true);
     } else {
         // Cleanup handle map, if just changing style,
         // or turning it on. In both cases the values
         // already in the map might be old (other style).
         d->cleanupHandleMap();
     }
     if (qobject_cast<QAbstractButton*>(widget)
         || qobject_cast<QToolButton*>(widget)
         || qobject_cast<QTabBar*>(widget)
 #ifndef QT_NO_COMBOBOX
         || qobject_cast<QComboBox*>(widget)
 #endif // QT_NO_COMBOBOX
         || qobject_cast<QScrollBar*>(widget)
         || qobject_cast<QSlider*>(widget)
         || qobject_cast<QHeaderView*>(widget)
 #ifndef QT_NO_SPINBOX
         || qobject_cast<QAbstractSpinBox*>(widget)
         || qobject_cast<QSpinBox*>(widget)
 #endif // QT_NO_SPINBOX
         || widget->inherits("QWorkspaceChild")
         || widget->inherits("Q3TitleBar"))
         widget->setAttribute(Qt::WA_Hover, false);
     QWindowsStyle::unpolish(widget);
 }
Friends and Related Functions
QStyleFactory
friend class QStyleFactory friend
Definition at line 97 of file qwindowsxpstyle.h.
Properties
reserved
void* QWindowsXPStyle::reserved private
Definition at line 98 of file qwindowsxpstyle.h.
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowsxpstyle.h
/src/gui/styles/qwindowsxpstyle.cpp