Qt 4.8: QNetworkInterfaceManager Class Reference
QNetworkInterfaceManager Class Reference
#include <qnetworkinterface_p.h>
Public Functions
QList< QSharedDataPointer< QNetworkInterfacePrivate > > allInterfaces ()
QSharedDataPointer< QNetworkInterfacePrivate > interfaceFromIndex (int index)
QSharedDataPointer< QNetworkInterfacePrivate > interfaceFromName (const QString &name)
QNetworkInterfaceManager ()
~QNetworkInterfaceManager ()
Public Variables
QSharedDataPointer< QNetworkInterfacePrivate > empty
Private Functions
QList< QNetworkInterfacePrivate * > scan ()
Detailed Description
Definition at line 101 of file qnetworkinterface_p.h.
Constructors and Destructors
QNetworkInterfaceManager()
QNetworkInterfaceManager::QNetworkInterfaceManager ()
Definition at line 84 of file qnetworkinterface.cpp.
 {
 }
~QNetworkInterfaceManager()
QNetworkInterfaceManager::~QNetworkInterfaceManager ()
Definition at line 88 of file qnetworkinterface.cpp.
 {
 }
Functions
allInterfaces()
QList< QSharedDataPointer< QNetworkInterfacePrivate > > QNetworkInterfaceManager::allInterfaces ()
Definition at line 114 of file qnetworkinterface.cpp.
Referenced by interfaceFromIndex(), and interfaceFromName().
 {
     QList<QNetworkInterfacePrivate *> list = postProcess(scan());
     QList<QSharedDataPointer<QNetworkInterfacePrivate> > result;
     foreach (QNetworkInterfacePrivate *ptr, list)
         result << QSharedDataPointer<QNetworkInterfacePrivate>(ptr);
     return result;
 }
interfaceFromIndex()
QSharedDataPointer< QNetworkInterfacePrivate > QNetworkInterfaceManager::interfaceFromIndex (int index)
Definition at line 103 of file qnetworkinterface.cpp.
 {
     QList<QSharedDataPointer<QNetworkInterfacePrivate> > interfaceList = allInterfaces();
     QList<QSharedDataPointer<QNetworkInterfacePrivate> >::ConstIterator it = interfaceList.constBegin();
     for ( ; it != interfaceList.constEnd(); ++it)
         if ((*it)->index == index)
             return *it;
     return empty;
 }
interfaceFromName()
QSharedDataPointer< QNetworkInterfacePrivate > QNetworkInterfaceManager::interfaceFromName (const QString & name)
Definition at line 92 of file qnetworkinterface.cpp.
 {
     QList<QSharedDataPointer<QNetworkInterfacePrivate> > interfaceList = allInterfaces();
     QList<QSharedDataPointer<QNetworkInterfacePrivate> >::ConstIterator it = interfaceList.constBegin();
     for ( ; it != interfaceList.constEnd(); ++it)
         if ((*it)->name == name)
             return *it;
     return empty;
 }
scan()
QList< QNetworkInterfacePrivate * > QNetworkInterfaceManager::scan () private
Definition at line 453 of file qnetworkinterface_unix.cpp.
Referenced by allInterfaces(), and interfaceListing().
 {
     return interfaceListing();
 }
Properties
empty
QSharedDataPointer<QNetworkInterfacePrivate> QNetworkInterfaceManager::empty
Definition at line 112 of file qnetworkinterface_p.h.
Referenced by interfaceFromIndex(), and interfaceFromName().
The documentation for this class was generated from the following files:
/src/network/kernel/qnetworkinterface_p.h
/src/network/kernel/qnetworkinterface.cpp
/src/network/kernel/qnetworkinterface_unix.cpp
/src/network/kernel/qnetworkinterface_win.cpp