Qt 4.8: QTessellator Class Reference
QTessellator Class Reference abstract
#include <qtessellator_p.h>
Classes
struct Trapezoid
struct Vertex
Public Functions
virtual void addTrap (const Trapezoid &trap)=0
QTessellator ()
void setWinding (bool w)
QRectF tessellate (const QPointF *points, int nPoints)
void tessellateConvex (const QPointF *points, int nPoints)
void tessellateRect (const QPointF &a, const QPointF &b, qreal width)
virtual ~QTessellator ()
Properties
QTessellatorPrivate * d
Friends
class QTessellatorPrivate
Detailed Description
Definition at line 70 of file qtessellator_p.h.
Constructors and Destructors
QTessellator()
QTessellator::QTessellator ()
Definition at line 1199 of file qtessellator.cpp.
 {
     d = new QTessellatorPrivate;
 }
~QTessellator()
QTessellator::~QTessellator () virtual
Definition at line 1204 of file qtessellator.cpp.
 {
     delete d;
 }
Functions
addTrap()
virtual void QTessellator::addTrap (const Trapezoid & trap) pure virtual
Implemented in QOpenGLTrapezoidToArrayTessellator, QOpenGLImmediateModeTessellator, and QXRenderTessellator.
Referenced by QTessellatorPrivate::emitEdges().
setWinding()
void QTessellator::setWinding (bool w)
Definition at line 1209 of file qtessellator.cpp.
Referenced by QXRenderTessellator::tessellate().
 {
     d->winding = w;
 }
tessellate()
QRectF QTessellator::tessellate (const QPointF * points, int nPoints)
Definition at line 1215 of file qtessellator.cpp.
Referenced by QXRenderTessellator::tessellate(), QOpenGLImmediateModeTessellator::tessellate(), and QOpenGLTrapezoidToArrayTessellator::tessellate().
 {
     Q_ASSERT(points[0] == points[nPoints-1]);
     --nPoints;
 #ifdef DEBUG
     QDEBUG()<< "POINTS:";
     for (int i = 0; i < nPoints; ++i) {
         QDEBUG() << points[i];
     }
 #endif
     // collect edges and calculate bounds
     d->vertices.nPoints = nPoints;
     d->vertices.init(nPoints);
     int maxActiveEdges = 0;
     QRectF br = d->collectAndSortVertices(points, &maxActiveEdges);
     d->cancelCoincidingEdges();
 #ifdef DEBUG
     QDEBUG() << "nPoints = " << nPoints << "using " << d->vertices.nPoints;
     QDEBUG()<< "VERTICES:";
     for (int i = 0; i < d->vertices.nPoints; ++i) {
         QDEBUG() << "    " << i << ": "
                  << "point=" << d->vertices.position(d->vertices.sorted[i])
                  << "flags=" << d->vertices.sorted[i]->flags
                  << "pos=(" << Q27Dot5ToDouble(d->vertices.sorted[i]->x) << '/'
                  << Q27Dot5ToDouble(d->vertices.sorted[i]->y) << ')';
     }
 #endif
     d->scanline.init(maxActiveEdges);
     d->y = INT_MIN/256;
     d->currentVertex = 0;
     while (d->currentVertex < d->vertices.nPoints) {
         d->scanline.clearMarks();
         d->y = d->vertices.sorted[d->currentVertex]->y;
         if (!d->intersections.isEmpty())
             d->y = qMin(d->y, d->intersections.constBegin().key().y);
         QDEBUG()<< "===== SCANLINE: y =" << Q27Dot5ToDouble(d->y) << " =====";
         d->scanline.prepareLine();
         d->processIntersections();
         d->removeEdges();
         d->addEdges();
         d->addIntersections();
         d->emitEdges(this);
         d->scanline.lineDone();
 #ifdef DEBUG
         QDEBUG()<< "===== edges:";
         for (int i = 0; i < d->scanline.size; ++i) {
             QDEBUG() << "   " << d->scanline.edges[i]->edge
                      << "p0= (" << Q27Dot5ToDouble(d->scanline.edges[i]->v0->x)
                      << '/' << Q27Dot5ToDouble(d->scanline.edges[i]->v0->y)
                      << ") p1= (" << Q27Dot5ToDouble(d->scanline.edges[i]->v1->x)
                      << '/' << Q27Dot5ToDouble(d->scanline.edges[i]->v1->y) << ')'
                      << "x=" << Q27Dot5ToDouble(d->scanline.edges[i]->positionAt(d->y))
                      << "isLeftOfNext="
                      << ((i < d->scanline.size - 1)
                          ? d->scanline.edges[i]->isLeftOf(*d->scanline.edges[i+1], d->y)
                          : true);
         }
 #endif
 }
     d->scanline.done();
     d->intersections.clear();
     return br;
 }
tessellateConvex()
void QTessellator::tessellateConvex (const QPointF * points, int nPoints)
Definition at line 1291 of file qtessellator.cpp.
 {
     Q_ASSERT(points[0] == points[nPoints-1]);
     --nPoints;
     d->vertices.nPoints = nPoints;
     d->vertices.init(nPoints);
     for (int i = 0; i < nPoints; ++i) {
         d->vertices[i]->x = FloatToQ27Dot5(points[i].x());
         d->vertices[i]->y = FloatToQ27Dot5(points[i].y());
     }
     int left = 0, right = 0;
     int top = 0;
     for (int i = 1; i < nPoints; ++i) {
         if (d->vertices[i]->y < d->vertices[top]->y)
             top = i;
     }
     left = (top + nPoints - 1) % nPoints;
     right = (top + 1) % nPoints;
     while (d->vertices[left]->x == d->vertices[top]->x && d->vertices[left]->y == d->vertices[top]->y && left != right)
         left = (left + nPoints - 1) % nPoints;
     while (d->vertices[right]->x == d->vertices[top]->x && d->vertices[right]->y == d->vertices[top]->y && left != right)
         right = (right + 1) % nPoints;
     if (left == right)
         return;
     int dir = 1;
     Vertex dLeft = { d->vertices[top]->x - d->vertices[left]->x,
                      d->vertices[top]->y - d->vertices[left]->y };
     Vertex dRight = { d->vertices[right]->x - d->vertices[top]->x,
                       d->vertices[right]->y - d->vertices[top]->y };
     Q27Dot5 cross = dLeft.x * dRight.y - dLeft.y * dRight.x;
     // flip direction if polygon is clockwise
     if (cross < 0 || (cross == 0 && dLeft.x > 0)) {
         qSwap(left, right);
         dir = -1;
     }
     Vertex *lastLeft = d->vertices[top];
     Vertex *lastRight = d->vertices[top];
     QTessellator::Trapezoid trap;
     while (lastLeft->y == d->vertices[left]->y && left != right) {
         lastLeft = d->vertices[left];
         left = (left + nPoints - dir) % nPoints;
     }
     while (lastRight->y == d->vertices[right]->y && left != right) {
         lastRight = d->vertices[right];
         right = (right + nPoints + dir) % nPoints;
     }
     while (true) {
         trap.top = qMax(lastRight->y, lastLeft->y);
         trap.bottom = qMin(d->vertices[left]->y, d->vertices[right]->y);
         trap.topLeft = lastLeft;
         trap.topRight = lastRight;
         trap.bottomLeft = d->vertices[left];
         trap.bottomRight = d->vertices[right];
         if (trap.bottom > trap.top)
             addTrap(trap);
         if (left == right)
             break;
         if (d->vertices[right]->y < d->vertices[left]->y) {
             do {
                 lastRight = d->vertices[right];
                 right = (right + nPoints + dir) % nPoints;
             }
             while (lastRight->y == d->vertices[right]->y && left != right);
         } else {
             do {
                 lastLeft = d->vertices[left];
                 left = (left + nPoints - dir) % nPoints;
             }
             while (lastLeft->y == d->vertices[left]->y && left != right);
         }
     }
 }
tessellateRect()
void QTessellator::tessellateRect (const QPointF & a, const QPointF & b, qreal width)
Definition at line 1386 of file qtessellator.cpp.
Referenced by QGLLineMaskGenerator::generateTrapezoids().
 {
     Vertex a = { FloatToQ27Dot5(a_.x()), FloatToQ27Dot5(a_.y()) };
     Vertex b = { FloatToQ27Dot5(b_.x()), FloatToQ27Dot5(b_.y()) };
     QPointF pa = a_, pb = b_;
     if (a.y > b.y) {
         qSwap(a, b);
         qSwap(pa, pb);
     }
     Vertex delta = { b.x - a.x, b.y - a.y };
     if (delta.x == 0 && delta.y == 0)
         return;
     qreal hw = qreal(0.5) * width;
     if (delta.x == 0) {
         Q27Dot5 halfWidth = FloatToQ27Dot5(hw);
         if (halfWidth == 0)
             return;
         Vertex topLeft = { a.x - halfWidth, a.y };
         Vertex topRight = { a.x + halfWidth, a.y };
         Vertex bottomLeft = { a.x - halfWidth, b.y };
         Vertex bottomRight = { a.x + halfWidth, b.y };
         QTessellator::Trapezoid trap = { topLeft.y, bottomLeft.y, &topLeft, &bottomLeft, &topRight, &bottomRight };
         addTrap(trap);
     } else if (delta.y == 0) {
         Q27Dot5 halfWidth = FloatToQ27Dot5(hw);
         if (halfWidth == 0)
             return;
         if (a.x > b.x)
             qSwap(a.x, b.x);
         Vertex topLeft = { a.x, a.y - halfWidth };
         Vertex topRight = { b.x, a.y - halfWidth };
         Vertex bottomLeft = { a.x, a.y + halfWidth };
         Vertex bottomRight = { b.x, a.y + halfWidth };
         QTessellator::Trapezoid trap = { topLeft.y, bottomLeft.y, &topLeft, &bottomLeft, &topRight, &bottomRight };
         addTrap(trap);
     } else {
         QPointF perp(pb.y() - pa.y(), pa.x() - pb.x());
         qreal length = qSqrt(perp.x() * perp.x() + perp.y() * perp.y());
         if (qFuzzyIsNull(length))
             return;
         // need the half of the width
         perp *= hw / length;
         QPointF pta = pa + perp;
         QPointF ptb = pa - perp;
         QPointF ptc = pb - perp;
         QPointF ptd = pb + perp;
         Vertex ta = { FloatToQ27Dot5(pta.x()), FloatToQ27Dot5(pta.y()) };
         Vertex tb = { FloatToQ27Dot5(ptb.x()), FloatToQ27Dot5(ptb.y()) };
         Vertex tc = { FloatToQ27Dot5(ptc.x()), FloatToQ27Dot5(ptc.y()) };
         Vertex td = { FloatToQ27Dot5(ptd.x()), FloatToQ27Dot5(ptd.y()) };
         if (ta.y < tb.y) {
             if (tb.y < td.y) {
                 QTessellator::Trapezoid top = { ta.y, tb.y, &ta, &tb, &ta, &td };
                 QTessellator::Trapezoid bottom = { td.y, tc.y, &tb, &tc, &td, &tc };
                 addTrap(top);
                 addTrap(bottom);
                 QTessellator::Trapezoid middle = { tb.y, td.y, &tb, &tc, &ta, &td };
                 addTrap(middle);
             } else {
                 QTessellator::Trapezoid top = { ta.y, td.y, &ta, &tb, &ta, &td };
                 QTessellator::Trapezoid bottom = { tb.y, tc.y, &tb, &tc, &td, &tc };
                 addTrap(top);
                 addTrap(bottom);
                 if (tb.y != td.y) {
                     QTessellator::Trapezoid middle = { td.y, tb.y, &ta, &tb, &td, &tc };
                     addTrap(middle);
                 }
             }
         } else {
             if (ta.y < tc.y) {
                 QTessellator::Trapezoid top = { tb.y, ta.y, &tb, &tc, &tb, &ta };
                 QTessellator::Trapezoid bottom = { tc.y, td.y, &tc, &td, &ta, &td };
                 addTrap(top);
                 addTrap(bottom);
                 QTessellator::Trapezoid middle = { ta.y, tc.y, &tb, &tc, &ta, &td };
                 addTrap(middle);
             } else {
                 QTessellator::Trapezoid top = { tb.y, tc.y, &tb, &tc, &tb, &ta };
                 QTessellator::Trapezoid bottom = { ta.y, td.y, &tc, &td, &ta, &td };
                 addTrap(top);
                 addTrap(bottom);
                 if (ta.y != tc.y) {
                     QTessellator::Trapezoid middle = { tc.y, ta.y, &tc, &td, &tb, &ta };
                     addTrap(middle);
                 }
             }
         }
     }
 }
Friends and Related Functions
QTessellatorPrivate
friend class QTessellatorPrivate friend
Definition at line 96 of file qtessellator_p.h.
Properties
d
QTessellatorPrivate* QTessellator::d private
Definition at line 97 of file qtessellator_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qtessellator_p.h
/src/gui/painting/qtessellator.cpp