Qt 4.8: QTextListFormat Class Reference
QTextListFormat Class Reference
The QTextListFormat class provides formatting information for lists in a QTextDocument.
#include <qtextformat.h>
Public Types
enum Style {
ListDisc = -1, ListCircle = -2, ListSquare = -3, ListDecimal = -4,
ListLowerAlpha = -5, ListUpperAlpha = -6, ListLowerRoman = -7, ListUpperRoman = -8,
ListStyleUndefined = 0
}
This enum describes the symbols used to decorate list items:
Public Types inherited from QTextFormat
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Public Functions
int indent () const
Returns the list format's indentation.
bool isValid () const
Returns true if this list format is valid; otherwise returns false.
QString numberPrefix () const
Returns the list format's number prefix.
QString numberSuffix () const
Returns the list format's number suffix.
QTextListFormat ()
Constructs a new list format object.
void setIndent (int indent)
Sets the list format's indentation.
void setNumberPrefix (const QString &numberPrefix)
Sets the list format's number prefix to the string specified by numberPrefix.
void setNumberSuffix (const QString &numberSuffix)
Sets the list format's number suffix to the string specified by numberSuffix.
void setStyle (Style style)
Sets the list format's style.
Style style () const
Returns the list format's style.
Public Functions inherited from QTextFormat
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Protected Functions
QTextListFormat (const QTextFormat &fmt)
Creates a new list format with the same attributes as the given text format.
Friends
class QTextFormat
Detailed Description
The QTextListFormat class provides formatting information for lists in a QTextDocument.
Note
This class or function is reentrant.
A list is composed of one or more items, represented as text blocks. The list's format specifies the appearance of items in the list. In particular, it determines the indentation and the style of each item.
The indentation of the items is an integer value that causes each item to be offset from the left margin by a certain amount. This value is read with indent() and set with setIndent().
The style used to decorate each item is set with setStyle() and can be read with the style() function. The style controls the type of bullet points and numbering scheme used for items in the list. Note that lists that use the decimal numbering scheme begin counting at 1 rather than 0.
Style properties can be set to further configure the appearance of list items; for example, the ListNumberPrefix and ListNumberSuffix properties can be used to customize the numbers used in an ordered list so that they appear as (1), (2), (3), etc.:
    QTextListFormat listFormat;
    listFormat.setStyle(QTextListFormat::ListDecimal);
    listFormat.setNumberPrefix("(");
    listFormat.setNumberSuffix(")");
    cursor.insertList(listFormat);
See also
QTextList
Definition at line 642 of file qtextformat.h.
Enumerations
Style
enum QTextListFormat::Style
This enum describes the symbols used to decorate list items:
ListDisc a filled circle
ListCircle an empty circle
ListSquare a filled square
ListDecimal decimal values in ascending order
ListLowerAlpha lower case Latin characters in alphabetical order
ListUpperAlpha upper case Latin characters in alphabetical order
ListLowerRoman lower case roman numerals (supports up to 4999 items only)
ListUpperRoman upper case roman numerals (supports up to 4999 items only)
ListStyleUndefined
Enumerator
ListDisc
ListCircle
ListSquare
ListDecimal
ListLowerAlpha
ListUpperAlpha
ListLowerRoman
ListUpperRoman
ListStyleUndefined
Definition at line 649 of file qtextformat.h.
                {
         ListDisc = -1,
         ListCircle = -2,
         ListSquare = -3,
         ListDecimal = -4,
         ListLowerAlpha = -5,
         ListUpperAlpha = -6,
         ListLowerRoman = -7,
         ListUpperRoman = -8,
         ListStyleUndefined = 0
     };
Constructors and Destructors
QTextListFormat() [1/2]
QTextListFormat::QTextListFormat ()
Constructs a new list format object.
Definition at line 2643 of file qtextformat.cpp.
     : QTextFormat(ListFormat)
 {
     setIndent(1);
 }
QTextListFormat() [2/2]
QTextListFormat::QTextListFormat (const QTextFormat & other) explicit protected
Creates a new list format with the same attributes as the given text format.
Warning
This function is not part of the public interface.
Definition at line 2659 of file qtextformat.cpp.
  : QTextFormat(fmt)
 {
 }
Functions
indent()
int QTextListFormat::indent () const inline
Returns the list format's indentation.
The indentation is multiplied by the QTextDocument::indentWidth property to get the effective indent in pixels.
See also
setIndent()
Definition at line 666 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::blockIndent(), QTextHtmlExporter::emitBlock(), QTextControlPrivate::indent(), QTextControlPrivate::outdent(), QTextList::remove(), QTextOdfWriter::writeBlock(), and QTextOdfWriter::writeListFormat().
     { return intProperty(ListIndent); }
isValid()
bool QTextListFormat::isValid () const inline
Returns true if this list format is valid; otherwise returns false.
Definition at line 647 of file qtextformat.h.
 { return isListFormat(); }
numberPrefix()
int QTextListFormat::numberPrefix () const inline
Returns the list format's number prefix.
Since
4.8
See also
setNumberPrefix()
Definition at line 670 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlock(), QTextList::itemText(), and QTextOdfWriter::writeListFormat().
     { return stringProperty(ListNumberPrefix); }
numberSuffix()
int QTextListFormat::numberSuffix () const inline
Returns the list format's number suffix.
Since
4.8
See also
setNumberSuffix()
Definition at line 674 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlock(), QTextList::itemText(), and QTextOdfWriter::writeListFormat().
     { return stringProperty(ListNumberSuffix); }
setIndent()
void QTextListFormat::setIndent (int indentation) inline
Sets the list format's indentation.
The indentation is multiplied by the QTextDocument::indentWidth property to get the effective indent in pixels.
See also
indent()
Definition at line 685 of file qtextformat.h.
Referenced by QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextControlPrivate::indent(), QTextControlPrivate::outdent(), QTextHtmlImporter::processSpecialNodes(), and QTextListFormat().
 { setProperty(ListIndent, aindent); }
setNumberPrefix()
void QTextListFormat::setNumberPrefix (const QString & numberPrefix) inline
Sets the list format's number prefix to the string specified by numberPrefix.
Since
4.8
This can be used with all sorted list types. It does not have any effect on unsorted list types.
The default prefix is an empty string.
See also
numberPrefix()
Definition at line 688 of file qtextformat.h.
Referenced by QTextHtmlImporter::processSpecialNodes().
 { setProperty(ListNumberPrefix, np); }
setNumberSuffix()
void QTextListFormat::setNumberSuffix (const QString & numberSuffix) inline
Sets the list format's number suffix to the string specified by numberSuffix.
Since
4.8
This can be used with all sorted list types. It does not have any effect on unsorted list types.
The default suffix is ".".
See also
numberSuffix()
Definition at line 691 of file qtextformat.h.
Referenced by QTextHtmlImporter::processSpecialNodes().
 { setProperty(ListNumberSuffix, ns); }
setStyle()
void QTextListFormat::setStyle (Style style) inline
Sets the list format's style.
See also
style() Style
Definition at line 682 of file qtextformat.h.
Referenced by QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextCursor::createList(), and QTextHtmlImporter::processSpecialNodes().
 { setProperty(ListStyle, astyle); }
style()
Style QTextListFormat::style () const inline
Returns the list format's style.
See also
setStyle() Style
Definition at line 662 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawListItem(), QTextHtmlExporter::emitBlock(), QTextList::itemText(), and QTextOdfWriter::writeListFormat().
     { return static_cast<Style>(intProperty(ListStyle)); }
Friends and Related Functions
QTextFormat
friend class QTextFormat friend
Definition at line 679 of file qtextformat.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp