Qt 4.8: QProxyModel Class Reference
QProxyModel Class Reference
The QProxyModel class provides support for processing data passed between another model and a view.
#include <qproxymodel.h>
Public Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of columns for the given parent.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns the data stored in the item with the given index under the specified role.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Returns true if the model accepts the data dropped onto an attached view for the specified action; otherwise returns false.
void fetchMore (const QModelIndex &parent)
Fetches more child items of the given parent.
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Returns true if the item corresponding to the parent index has child items; otherwise returns false.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data stored in the section of the header with specified orientation under the given role.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the model index with the given row, column, and parent.
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Inserts count columns into the model, creating new items as children of the given parent.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Inserts count rows into the model, creating new items as children of the given parent.
QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of model indexes that each contain the given value for the role specified.
QMimeData * mimeData (const QModelIndexList &indexes) const
Returns MIME data for the specified indexes in the model.
QStringList mimeTypes () const
Returns a list of MIME types that are supported by the model.
QAbstractItemModel * model () const
Returns the model that contains the data that is available through the proxy model.
QModelIndex parent (const QModelIndex &child) const
Returns the model index that corresponds to the parent of the given child index.
QProxyModel (QObject *parent=0)
Constructs a proxy model with the given parent.
void revert ()
Lets the model know that it should discard cached information.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows for the given parent.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the role data for the item at index to value.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the role data in the section of the header with the specified orientation to the value given.
virtual void setModel (QAbstractItemModel *model)
Sets the given model to be processed by the proxy model.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the child items in the specified column according to the sort order defined by order.
QSize span (const QModelIndex &index) const
Returns the size of the item that corresponds to the specified index.
bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Qt::DropActions supportedDropActions () const
Returns the drop actions that are supported by the model; this is a combination of the individual actions defined in Qt::DropActions .
~QProxyModel ()
Destroys the proxy model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void connectToModel (const QAbstractItemModel *model) const
Connect to all the signals emitted by given model.
void disconnectFromModel (const QAbstractItemModel *model) const
Disconnect from all the signals emitted by the given model.
QProxyModel (QProxyModelPrivate &, QObject *parent=0)
QModelIndex setProxyModel (const QModelIndex &source_index) const
Change the model pointer in the given source_index to point to the proxy model.
QModelIndex setSourceModel (const QModelIndex &proxy_index) const
Change the model pointer in the given proxy_index to point to the source model.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QProxyModel class provides support for processing data passed between another model and a view.
If you want to do filtering and sorting, see QSortFilterProxyModel.
Proxy models provide a standard model interface that can be used to manipulate the data retrieved through an underlying model. They can be used to perform operations such as sorting and filtering on the data obtained without changing the contents of the model.
Just as with subclasses of QAbstractItemView, QProxyModel provides the setModel() function that is used to specify the model to be acted on by the proxy. Views can be connected to either the underlying model or the proxy model with QAbstractItemView::setModel() .
Since views rely on the information provided in model indexes to identify items of data from models, and to position these items in some visual representation, proxy models must create their own model indexes instead of supplying model indexes from their underlying models.
See also
Model/View Programming QAbstractItemModel
Definition at line 57 of file qproxymodel.h.
Constructors and Destructors
QProxyModel() [1/2]
QProxyModel::QProxyModel (QObject * parent = 0) explicit
Constructs a proxy model with the given parent.
Definition at line 87 of file qproxymodel.cpp.
     : QAbstractItemModel(*new QProxyModelPrivate, parent)
 {
     Q_D(QProxyModel);
     setModel(&d->empty);
 }
~QProxyModel()
QProxyModel::~QProxyModel ()
Destroys the proxy model.
Definition at line 107 of file qproxymodel.cpp.
 {
 }
QProxyModel() [2/2]
QProxyModel::QProxyModel (QProxyModelPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 97 of file qproxymodel.cpp.
     : QAbstractItemModel(dd, parent)
 {
     Q_D(QProxyModel);
     setModel(&d->empty);
 }
Functions
columnCount()
int QProxyModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of columns for the given parent.
See also
QAbstractItemModel::columnCount()
Implements QAbstractItemModel.
Definition at line 174 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->columnCount(setSourceModel(parent));
 }
connectToModel()
void QProxyModel::connectToModel (const QAbstractItemModel * model) const protected
Connect to all the signals emitted by given model.
Warning
This function is not part of the public interface.
Definition at line 437 of file qproxymodel.cpp.
Referenced by setModel().
 {
     connect(model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(_q_sourceDataChanged(QModelIndex,QModelIndex)));
     connect(model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
             this, SIGNAL(headerDataChanged(Qt::Orientation,int,int))); // signal to signal
     connect(model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsAboutToBeInserted(QModelIndex,int,int)));
     connect(model, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsInserted(QModelIndex,int,int)));
     connect(model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsAboutToBeRemoved(QModelIndex,int,int)));
     connect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceRowsRemoved(QModelIndex,int,int)));
     connect(model, SIGNAL(columnsAboutToBeInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsAboutToBeInserted(QModelIndex,int,int)));
     connect(model, SIGNAL(columnsInserted(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsInserted(QModelIndex,int,int)));
     connect(model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsAboutToBeRemoved(QModelIndex,int,int)));
     connect(model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sourceColumnsRemoved(QModelIndex,int,int)));
     connect(model, SIGNAL(modelReset()), this, SIGNAL(modelReset())); // signal to signal
     connect(model, SIGNAL(layoutAboutToBeChanged()), this, SIGNAL(layoutAboutToBeChanged())); // signal to signal
     connect(model, SIGNAL(layoutChanged()), this, SIGNAL(layoutChanged())); // signal to signal
 }
data()
QVariant QProxyModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Returns the data stored in the item with the given index under the specified role.
Implements QAbstractItemModel.
Definition at line 196 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->data(setSourceModel(index), role);
 }
disconnectFromModel()
void QProxyModel::disconnectFromModel (const QAbstractItemModel * model) const protected
Disconnect from all the signals emitted by the given model.
Warning
This function is not part of the public interface.
Definition at line 471 of file qproxymodel.cpp.
Referenced by setModel().
 {
     disconnect(model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                this, SLOT(_q_sourceDataChanged(QModelIndex,QModelIndex)));
     disconnect(model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                this, SIGNAL(headerDataChanged(Qt::Orientation,int,int))); // signal to signal
     disconnect(model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsAboutToBeInserted(QModelIndex,int,int)));
     disconnect(model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                this, SLOT(rowsInserted(QModelIndex,int,int)));
     disconnect(model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsAboutToBeRemoved(QModelIndex,int,int)));
     disconnect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceRowsRemoved(QModelIndex,int,int)));
     disconnect(model, SIGNAL(columnsAboutToBeInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsAboutToBeInserted(QModelIndex,int,int)));
     disconnect(model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsInserted(QModelIndex,int,int)));
     disconnect(model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsAboutToBeRemoved(QModelIndex,int,int)));
     disconnect(model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                this, SLOT(_q_sourceColumnsRemoved(QModelIndex,int,int)));
     disconnect(model, SIGNAL(modelReset()), this, SIGNAL(modelReset())); // signal to signal
     disconnect(model, SIGNAL(layoutAboutToBeChanged()), this, SIGNAL(layoutAboutToBeChanged())); // signal to signal
     disconnect(model, SIGNAL(layoutChanged()), this, SIGNAL(layoutChanged())); // signal to signal
 }
dropMimeData()
bool QProxyModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Returns true if the model accepts the data dropped onto an attached view for the specified action; otherwise returns false.
The parent, row, and column details can be used to control which MIME types are acceptable to different parts of a model when received via the drag and drop system.
Reimplemented from QAbstractItemModel.
Definition at line 269 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->dropMimeData(data, action, row, column, setSourceModel(parent));
 }
fetchMore()
void QProxyModel::fetchMore (const QModelIndex & parent) virtual
Fetches more child items of the given parent.
This function is used by views to tell the model that they can display more data than the model has provided.
See also
QAbstractItemModel::fetchMore()
Reimplemented from QAbstractItemModel.
Definition at line 330 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     d->model->fetchMore(parent);
 }
flags()
Qt::ItemFlags QProxyModel::flags (const QModelIndex & index) const virtual
Returns the item flags for the given index.
Reimplemented from QAbstractItemModel.
Definition at line 339 of file qproxymodel.cpp.
Referenced by QModelIndex::internalId().
 {
     Q_D(const QProxyModel);
     return d->model->flags(setSourceModel(index));
 }
hasChildren()
bool QProxyModel::hasChildren (const QModelIndex & parent = QModelIndex()) const virtual
Returns true if the item corresponding to the parent index has child items; otherwise returns false.
See also
QAbstractItemModel::hasChildren()
Reimplemented from QAbstractItemModel.
Definition at line 186 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->hasChildren(setSourceModel(parent));
 }
headerData()
QVariant QProxyModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Returns the data stored in the section of the header with specified orientation under the given role.
Reimplemented from QAbstractItemModel.
Definition at line 221 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->headerData(section, orientation, role);
 }
index()
QModelIndex QProxyModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Returns the model index with the given row, column, and parent.
See also
QAbstractItemModel::index()
Implements QAbstractItemModel.
Definition at line 142 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return setProxyModel(d->model->index(row, column, setSourceModel(parent)));
 }
insertColumns()
bool QProxyModel::insertColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Inserts count columns into the model, creating new items as children of the given parent.
The new columns are inserted before the column specified. If the parent item has no children, a single row is created to contain the required number of columns.
Returns true if the columns were successfully inserted; otherwise returns false.
See also
QAbstractItemModel::insertColumns()
Reimplemented from QAbstractItemModel.
Definition at line 318 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->insertColumns(column, count, setSourceModel(parent));
 }
insertRows()
bool QProxyModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Inserts count rows into the model, creating new items as children of the given parent.
The new rows are inserted before the row specified. If the parent item has no children, a single column is created to contain the required number of rows.
Returns true if the rows were successfully inserted; otherwise returns false.
See also
QAbstractItemModel::insertRows()
Reimplemented from QAbstractItemModel.
Definition at line 301 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->insertRows(row, count, setSourceModel(parent));
 }
match()
QModelIndexList QProxyModel::match (const QModelIndex & start, int role, const QVariant & value, int hits = 1, Qt::MatchFlags flags = Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const virtual
Returns a list of model indexes that each contain the given value for the role specified.
The search begins at the start index and is performed according to the specified flags. The search continues until the number of matching data items equals hits, the last row is reached, or the search reaches start again, depending on whether MatchWrap is specified in flags.
See also
QAbstractItemModel::match()
Reimplemented from QAbstractItemModel.
Definition at line 367 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->match(start, role, value, hits, flags);
 }
mimeData()
QMimeData * QProxyModel::mimeData (const QModelIndexList & indexes) const virtual
Returns MIME data for the specified indexes in the model.
Reimplemented from QAbstractItemModel.
Definition at line 252 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     QModelIndexList lst;
     for (int i = 0; i < indexes.count(); ++i)
         lst.append(setSourceModel(indexes.at(i)));
     return d->model->mimeData(lst);
 }
mimeTypes()
QStringList QProxyModel::mimeTypes () const virtual
Returns a list of MIME types that are supported by the model.
Reimplemented from QAbstractItemModel.
Definition at line 243 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->mimeTypes();
 }
model()
QAbstractItemModel * QProxyModel::model () const
Returns the model that contains the data that is available through the proxy model.
Definition at line 131 of file qproxymodel.cpp.
Referenced by QModelIndex::operator<(), and setModel().
 {
     Q_D(const QProxyModel);
     return d->model;
 }
parent()
QObject * QProxyModel::parent (const QModelIndex & child) const virtual
Returns the model index that corresponds to the parent of the given child index.
Warning
This function is not part of the public interface.
Implements QAbstractItemModel.
Definition at line 152 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return setProxyModel(d->model->parent(setSourceModel(child)));
 }
revert()
void QProxyModel::revert () virtual
Lets the model know that it should discard cached information.
This function is typically used for row editing.
See also
submit()
Reimplemented from QAbstractItemModel.
Definition at line 394 of file qproxymodel.cpp.
 {
     Q_D(QProxyModel);
     d->model->revert();
 }
rowCount()
int QProxyModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows for the given parent.
See also
QAbstractItemModel::rowCount()
Implements QAbstractItemModel.
Definition at line 163 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->rowCount(setSourceModel(parent));
 }
setData()
bool QProxyModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Sets the role data for the item at index to value.
Returns true if successful; otherwise returns false.
The base class implementation returns false. This function and data() must be reimplemented for editable models.
See also
data() itemData() QAbstractItemModel::setData()
Reimplemented from QAbstractItemModel.
Definition at line 211 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->setData(setSourceModel(index), value, role);
 }
setHeaderData()
bool QProxyModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) virtual
Sets the role data in the section of the header with the specified orientation to the value given.
See also
QAbstractItemModel::setHeaderData()
Reimplemented from QAbstractItemModel.
Definition at line 233 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->setHeaderData(section, orientation, value, role);
 }
setModel()
void QProxyModel::setModel (QAbstractItemModel * model) virtual
Sets the given model to be processed by the proxy model.
Definition at line 114 of file qproxymodel.cpp.
Referenced by QProxyModel().
 {
     Q_D(QProxyModel);
     if (d->model && d->model != &d->empty)
         disconnectFromModel(d->model);
     if (model) {
         d->model = model;
         connectToModel(model);
     } else {
         d->model = &d->empty;
     }
 }
setProxyModel()
QModelIndex QProxyModel::setProxyModel (const QModelIndex & source_index) const protected
Change the model pointer in the given source_index to point to the proxy model.
Warning
This function is not part of the public interface.
Definition at line 407 of file qproxymodel.cpp.
Referenced by index(), and parent().
 {
     QModelIndex proxy_index = source_index;
     if (proxy_index.isValid())
         proxy_index.m = this;
     return proxy_index;
 }
setSourceModel()
QModelIndex QProxyModel::setSourceModel (const QModelIndex & proxy_index) const protected
Change the model pointer in the given proxy_index to point to the source model.
Warning
This function is not part of the public interface.
Definition at line 422 of file qproxymodel.cpp.
Referenced by columnCount(), data(), dropMimeData(), flags(), hasChildren(), index(), insertColumns(), insertRows(), mimeData(), parent(), rowCount(), setData(), and span().
 {
     Q_D(const QProxyModel);
     QModelIndex source_index = proxy_index;
     source_index.m = d->model;
     return source_index;
 }
sort()
void QProxyModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Sorts the child items in the specified column according to the sort order defined by order.
See also
QAbstractItemModel::sort()
Reimplemented from QAbstractItemModel.
Definition at line 351 of file qproxymodel.cpp.
 {
     Q_D(QProxyModel);
     d->model->sort(column, order);
 }
span()
QSize QProxyModel::span (const QModelIndex & index) const virtual
Returns the size of the item that corresponds to the specified index.
Reimplemented from QAbstractItemModel.
Definition at line 378 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->span(setSourceModel(index));
 }
submit()
bool QProxyModel::submit () virtual
Lets the model know that it should submit cached information to permanent storage.
This function is typically used for row editing.
Returns true if there is no error; otherwise returns false.
See also
revert()
Reimplemented from QAbstractItemModel.
Definition at line 386 of file qproxymodel.cpp.
 {
     Q_D(QProxyModel);
     return d->model->submit();
 }
supportedDropActions()
Qt::DropActions QProxyModel::supportedDropActions () const virtual
Returns the drop actions that are supported by the model; this is a combination of the individual actions defined in Qt::DropActions .
The selection of drop actions provided by the model will influence the behavior of the component that started the drag and drop operation.
See also
Drag and Drop
Reimplemented from QAbstractItemModel.
Definition at line 285 of file qproxymodel.cpp.
 {
     Q_D(const QProxyModel);
     return d->model->supportedDropActions();
 }
The documentation for this class was generated from the following files:
/src/gui/itemviews/qproxymodel.h
/src/gui/itemviews/qproxymodel.cpp