Qt 4.8: QBBWindow Class Reference
QBBWindow Class Reference
#include <qbbwindow.h>
Public Functions
QSize bufferSize () const
const QList< QBBWindow * > & children () const
QBBWindow * findWindow (screen_window_t windowHandle)
QBBBuffer & frontBuffer ()
void gainedFocus ()
virtual QPlatformGLContext * glContext () const
Reimplement to return the glContext associated with the window.
bool hasBuffers () const
virtual void lower ()
Reimplement to be able to let Qt lower windows to the bottom of the desktop.
void post (const QRegion &dirty)
QBBWindow (QWidget *window, screen_context_t context, QBBScreen *screen)
virtual void raise ()
Reimplement to be able to let Qt rais windows to the top of the desktop.
QBBBuffer & renderBuffer ()
virtual void requestActivateWindow ()
Reimplement to let Qt be able to request activation/focus for a window.
QBBScreen * screen () const
void scroll (const QRegion &region, int dx, int dy, bool flush=false)
void setBufferSize (const QSize &size)
virtual void setGeometry (const QRect &rect)
This function is called by Qt whenever a window is moved or the window is resized.
virtual void setOpacity (qreal level)
Reimplement to be able to let Qt set the opacity level of a window.
virtual void setParent (const QPlatformWindow *window)
This function is called to enable native child widgets in QPA.
void setScreen (QBBScreen *platformScreen)
virtual void setVisible (bool visible)
Reimplemented in subclasses to show the surface if visible is true, and hide it if visible is false.
virtual WId winId () const
Reimplement in subclasses to return a handle to the native window.
virtual ~QBBWindow ()
Public Functions inherited from QPlatformWindow
virtual QRect geometry () const
Returnes the current geometry of a window.
QPlatformWindow (QWidget *tlw)
Constructs a platform window with the given top level widget.
virtual Qt::WindowFlags setWindowFlags (Qt::WindowFlags flags)
Requests setting the window flags of this surface to type.
virtual void setWindowTitle (const QString &title)
Reimplement to set the window title to title.
QWidget * widget () const
Returnes the widget which belongs to the QPlatformWindow.
virtual Qt::WindowFlags windowFlags () const
Returns the effective window flags for this surface.
virtual ~QPlatformWindow ()
Virtual destructor does not delete its top level widget.
Private Types
enum Buffer { BACK_BUFFER, FRONT_BUFFER, MAX_BUFFER_COUNT }
Private Functions
QBBBuffer & buffer (QBBWindow::Buffer bufferIndex)
void copyBack (const QRegion &region, int dx, int dy, bool flush=false)
void fetchBuffers ()
void offset (const QPoint &offset)
void removeFromParent ()
void updateVisibility (bool parentVisible)
void updateZorder (int &topZorder)
Static Private Functions
static int platformWindowFormatToNativeFormat (const QPlatformWindowFormat &format)
Properties
QBBBuffer mBuffers [MAX_BUFFER_COUNT]
QSize mBufferSize
QList< QBBWindow * > mChildren
screen_context_t mContext
int mCurrentBufferIndex
QBBWindow * mParent
QBBGLContext * mPlatformGlContext
int mPreviousBufferIndex
QRegion mPreviousDirty
QBBScreen * mScreen
QRegion mScrolled
bool mVisible
screen_window_t mWindow
Friends
class QBBScreen
Additional Inherited Members
Protected Variables inherited from QPlatformWindow
QScopedPointer< QPlatformWindowPrivate > d_ptr
Detailed Description
Definition at line 59 of file qbbwindow.h.
Enumerations
Buffer
enum QBBWindow::Buffer private
Enumerator
BACK_BUFFER
FRONT_BUFFER
MAX_BUFFER_COUNT
Definition at line 100 of file qbbwindow.h.
                 {
         BACK_BUFFER,
         FRONT_BUFFER,
         MAX_BUFFER_COUNT
     };
Constructors and Destructors
QBBWindow()
QBBWindow::QBBWindow (QWidget * window, screen_context_t context, QBBScreen * screen)
Definition at line 57 of file qbbwindow.cpp.
     : QPlatformWindow(window),
       mContext(context),
       mCurrentBufferIndex(-1),
       mPreviousBufferIndex(-1),
       mPlatformGlContext(NULL),
       mScreen(NULL),
       mParent(NULL),
       mVisible(true)
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::QBBWindow - w=" << window << ", s=" << window->size();
 #endif
     int result;
     // create child QNX window
     errno = 0;
     result = screen_create_window_type(&mWindow, mContext, SCREEN_CHILD_WINDOW);
     if (result != 0) {
         qFatal("QBBWindow: failed to create window, errno=%d", errno);
     }
     // set window buffer usage based on rendering API
     int val;
     QPlatformWindowFormat format = widget()->platformWindowFormat();
     switch (format.windowApi()) {
     case QPlatformWindowFormat::Raster:
         val = SCREEN_USAGE_NATIVE | SCREEN_USAGE_READ | SCREEN_USAGE_WRITE;
         break;
     case QPlatformWindowFormat::OpenGL:
         val = SCREEN_USAGE_OPENGL_ES2;
         break;
     default:
         qFatal("QBBWindow: unsupported window API");
         break;
     }
     errno = 0;
     result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_USAGE, &val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window buffer usage, errno=%d", errno);
     }
     // alpha channel is always pre-multiplied if present
     errno = 0;
     val = SCREEN_PRE_MULTIPLIED_ALPHA;
     result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_ALPHA_MODE, &val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window alpha mode, errno=%d", errno);
     }
     // make the window opaque
     errno = 0;
     val = SCREEN_TRANSPARENCY_NONE;
     result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_TRANSPARENCY, &val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window transparency, errno=%d", errno);
     }
     // set the window swap interval
     errno = 0;
     val = 1;
     result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_SWAP_INTERVAL, &val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window swap interval, errno=%d", errno);
     }
     // Set the screen to the primary display (this is the default specified by screen).
     setScreen(screen);
     // Qt somtimes doesn't call these setters after creating the window, so we need to do that
     // ourselves here
     if (window->parentWidget() && window->parentWidget()->platformWindow())
         setParent(window->parentWidget()->platformWindow());
     setGeometry(window->geometry());
     setVisible(window->isVisible());
 }
~QBBWindow()
QBBWindow::~QBBWindow () virtual
Definition at line 135 of file qbbwindow.cpp.
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::~QBBWindow - w=" << widget();
 #endif
     // Qt should have already deleted the children before deleting the parent.
     Q_ASSERT(mChildren.size() == 0);
     // Remove from parent's Hierarchy.
     removeFromParent();
     mScreen->updateHierarchy();
     // cleanup OpenGL/OpenVG context if it exists
     if (mPlatformGlContext != NULL) {
         delete mPlatformGlContext;
     }
     // cleanup QNX window and its buffers
     screen_destroy_window(mWindow);
 }
Functions
buffer()
QBBBuffer & QBBWindow::buffer (QBBWindow::Buffer bufferIndex) private
Definition at line 368 of file qbbwindow.cpp.
Referenced by frontBuffer(), and renderBuffer().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::buffer - w=" << widget();
 #endif
     // check if render buffer is invalid
     if (mCurrentBufferIndex == -1) {
         // get all buffers available for rendering
         errno = 0;
         screen_buffer_t buffers[MAX_BUFFER_COUNT];
         const int result = screen_get_window_property_pv(mWindow, SCREEN_PROPERTY_RENDER_BUFFERS, (void **)buffers);
         if (result != 0) {
             qFatal("QBBWindow: failed to query window buffers, errno=%d", errno);
         }
         // wrap each buffer
         for (int i = 0; i < MAX_BUFFER_COUNT; i++) {
             mBuffers[i] = QBBBuffer(buffers[i]);
         }
         // use the first available render buffer
         mCurrentBufferIndex = 0;
         mPreviousBufferIndex = -1;
     }
     if (bufferIndex == BACK_BUFFER) {
         return mBuffers[mCurrentBufferIndex];
     } else if (bufferIndex == FRONT_BUFFER) {
         int buf = mCurrentBufferIndex - 1;
         if (buf < 0)
             buf = MAX_BUFFER_COUNT - 1;
         return mBuffers[buf];
     }
     qFatal("QBBWindow::buffer() - invalid buffer index. Aborting");
     // never happens
     return mBuffers[mCurrentBufferIndex];
 }
bufferSize()
QSize QBBWindow::bufferSize () const inline
Definition at line 73 of file qbbwindow.h.
Referenced by QBBRasterWindowSurface::beginPaint().
 { return mBufferSize; }
children()
const QList<QBBWindow*>& QBBWindow::children () const inline
Definition at line 94 of file qbbwindow.h.
 { return mChildren; }
copyBack()
void QBBWindow::copyBack (const QRegion & region, int dx, int dy, bool flush = false) private
Definition at line 646 of file qbbwindow.cpp.
Referenced by post(), and scroll().
 {
     int result;
     // abort if previous buffer is invalid
     if (mPreviousBufferIndex == -1) {
         return;
     }
     // abort if nothing to copy
     if (region.isEmpty()) {
         return;
     }
     QBBBuffer &currentBuffer = mBuffers[mCurrentBufferIndex];
     QBBBuffer &previousBuffer = mBuffers[mPreviousBufferIndex];
     // break down region into non-overlapping rectangles
     QVector<QRect> rects = region.rects();
     for (int i = rects.size() - 1; i >= 0; i--) {
         // clip rectangle to bounds of target
         QRect rect = rects[i].intersected( currentBuffer.rect() );
         if (rect.isEmpty())
             continue;
         // setup blit operation
         int attribs[] = { SCREEN_BLIT_SOURCE_X, rect.x(),
                           SCREEN_BLIT_SOURCE_Y, rect.y(),
                           SCREEN_BLIT_SOURCE_WIDTH, rect.width(),
                           SCREEN_BLIT_SOURCE_HEIGHT, rect.height(),
                           SCREEN_BLIT_DESTINATION_X, rect.x() + dx,
                           SCREEN_BLIT_DESTINATION_Y, rect.y() + dy,
                           SCREEN_BLIT_DESTINATION_WIDTH, rect.width(),
                           SCREEN_BLIT_DESTINATION_HEIGHT, rect.height(),
                           SCREEN_BLIT_END };
         // queue blit operation
         errno = 0;
         result = screen_blit(mContext, currentBuffer.nativeBuffer(), previousBuffer.nativeBuffer(), attribs);
         if (result != 0) {
             qFatal("QBBWindow: failed to blit buffers, errno=%d", errno);
         }
     }
     // check if flush requested
     if (flush) {
         // wait for all blits to complete
         errno = 0;
         result = screen_flush_blits(mContext, SCREEN_WAIT_IDLE);
         if (result != 0) {
             qFatal("QBBWindow: failed to flush blits, errno=%d", errno);
         }
         // buffer was modified outside the CPU
         currentBuffer.invalidateInCache();
     }
 }
fetchBuffers()
void QBBWindow::fetchBuffers () private
findWindow()
QBBWindow * QBBWindow::findWindow (screen_window_t windowHandle)
Definition at line 617 of file qbbwindow.cpp.
Referenced by children(), QBBScreen::findWindow(), and findWindow().
 {
     if (mWindow == windowHandle)
         return this;
     Q_FOREACH (QBBWindow *window, mChildren) {
         QBBWindow * const result = window->findWindow(windowHandle);
         if (result)
             return result;
     }
     return 0;
 }
frontBuffer()
QBBBuffer & QBBWindow::frontBuffer ()
Definition at line 359 of file qbbwindow.cpp.
Referenced by hasBuffers(), and QBBRasterWindowSurface::paintDevice().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::frontBuffer - w=" << widget();
 #endif
     return buffer(FRONT_BUFFER);
 }
gainedFocus()
void QBBWindow::gainedFocus ()
Definition at line 607 of file qbbwindow.cpp.
Referenced by hasBuffers(), and requestActivateWindow().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::gainedFocus - w=" << widget();
 #endif
     // Got focus
     QWindowSystemInterface::handleWindowActivated(widget());
 }
glContext()
QPlatformGLContext * QBBWindow::glContext () const virtual
Reimplement to return the glContext associated with the window.
Reimplemented from QPlatformWindow.
Definition at line 461 of file qbbwindow.cpp.
Referenced by hasBuffers().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::glContext - w=" << widget();
 #endif
     // create opengl context on first access if rendering API is correct
     QPlatformWindowFormat format = widget()->platformWindowFormat();
     if (mPlatformGlContext == NULL && format.windowApi() == QPlatformWindowFormat::OpenGL) {
         mPlatformGlContext = new QBBGLContext( const_cast<QBBWindow*>(this) );
     }
     return mPlatformGlContext;
 }
hasBuffers()
bool QBBWindow::hasBuffers () const inline
Definition at line 74 of file qbbwindow.h.
Referenced by QBBGLContext::makeCurrent(), QBBRasterWindowSurface::paintDevice(), and setBufferSize().
 { return !mBufferSize.isEmpty(); }
lower()
void QBBWindow::lower () virtual
Reimplement to be able to let Qt lower windows to the bottom of the desktop.
Reimplemented from QPlatformWindow.
Definition at line 579 of file qbbwindow.cpp.
Referenced by hasBuffers().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::lower - w=" << widget();
 #endif
     if (mParent) {
         mParent->mChildren.removeAll(this);
         mParent->mChildren.push_front(this);
     } else {
         mScreen->lowerWindow(this);
     }
     mScreen->updateHierarchy();
 }
offset()
void QBBWindow::offset (const QPoint & offset) private
Definition at line 207 of file qbbwindow.cpp.
Referenced by setGeometry().
 {
     // Move self and then children.
     QRect newGeometry = geometry();
     newGeometry.translate(offset);
     // call the base class
     QPlatformWindow::setGeometry(newGeometry);
     int val[2];
     errno = 0;
     val[0] = newGeometry.x();
     val[1] = newGeometry.y();
     int result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_POSITION, val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window position, errno=%d", errno);
     }
     QList<QBBWindow*>::iterator it;
     for (it = mChildren.begin(); it != mChildren.end(); it++) {
         (*it)->offset(offset);
     }
 }
platformWindowFormatToNativeFormat()
int QBBWindow::platformWindowFormatToNativeFormat (const QPlatformWindowFormat & format) static private
Definition at line 707 of file qbbwindow.cpp.
Referenced by setBufferSize().
 {
     // extract size of colour channels from window format
     int redSize = format.redBufferSize();
     if (redSize == -1) {
         qFatal("QBBWindow: red size not defined");
     }
     int greenSize = format.greenBufferSize();
     if (greenSize == -1) {
         qFatal("QBBWindow: green size not defined");
     }
     int blueSize = format.blueBufferSize();
     if (blueSize == -1) {
         qFatal("QBBWindow: blue size not defined");
     }
     // select matching native format
     if (redSize == 5 && greenSize == 6 && blueSize == 5) {
         return SCREEN_FORMAT_RGB565;
     } else if (redSize == 8 && greenSize == 8 && blueSize == 8) {
         return SCREEN_FORMAT_RGBA8888;
     } else {
         qFatal("QBBWindow: unsupported pixel format");
         return 0;
     }
 }
post()
void QBBWindow::post (const QRegion & dirty)
Definition at line 417 of file qbbwindow.cpp.
Referenced by QBBRasterWindowSurface::flush(), and hasBuffers().
 {
     // check if render buffer exists and something was rendered
     if (mCurrentBufferIndex != -1 && !dirty.isEmpty()) {
 #if defined(QBBWINDOW_DEBUG)
         qDebug() << "QBBWindow::post - w=" << widget();
 #endif
         QBBBuffer &currentBuffer = mBuffers[mCurrentBufferIndex];
         // copy unmodified region from old render buffer to new render buffer;
         // required to allow partial updates
         QRegion preserve = mPreviousDirty - dirty - mScrolled;
         copyBack(preserve, 0, 0);
         // calculate region that changed
         QRegion modified = preserve + dirty + mScrolled;
         QRect rect = modified.boundingRect();
         int dirtyRect[4] = { rect.x(), rect.y(), rect.x() + rect.width(), rect.y() + rect.height() };
         // update the display with contents of render buffer
         errno = 0;
         int result = screen_post_window(mWindow, currentBuffer.nativeBuffer(), 1, dirtyRect, 0);
         if (result != 0) {
             qFatal("QBBWindow: failed to post window buffer, errno=%d", errno);
         }
         // advance to next nender buffer
         mPreviousBufferIndex = mCurrentBufferIndex++;
         if (mCurrentBufferIndex >= MAX_BUFFER_COUNT) {
             mCurrentBufferIndex = 0;
         }
         // save modified region and clear scrolled region
         mPreviousDirty = dirty;
         mScrolled = QRegion();
         // notify screen that window posted
         if (mScreen != NULL) {
             mScreen->onWindowPost(this);
         }
     }
 }
raise()
void QBBWindow::raise () virtual
Reimplement to be able to let Qt rais windows to the top of the desktop.
Reimplemented from QPlatformWindow.
Definition at line 563 of file qbbwindow.cpp.
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::raise - w=" << widget();
 #endif
     if (mParent) {
         mParent->mChildren.removeAll(this);
         mParent->mChildren.push_back(this);
     } else {
         mScreen->raiseWindow(this);
     }
     mScreen->updateHierarchy();
 }
removeFromParent()
void QBBWindow::removeFromParent () private
Definition at line 519 of file qbbwindow.cpp.
Referenced by setParent(), and ~QBBWindow().
 {
     // Remove from old Hierarchy position
     if (mParent) {
         if (mParent->mChildren.removeAll(this))
             mParent = 0;
         else
             qFatal("QBBWindow: Window Hierarchy broken; window has parent, but parent hasn't got child.");
     } else {
         mScreen->removeWindow(this);
     }
 }
renderBuffer()
QBBBuffer & QBBWindow::renderBuffer ()
Definition at line 350 of file qbbwindow.cpp.
Referenced by hasBuffers(), and QBBRasterWindowSurface::paintDevice().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::renderBuffer - w=" << widget();
 #endif
     return buffer(BACK_BUFFER);
 }
requestActivateWindow()
void QBBWindow::requestActivateWindow () virtual
Reimplement to let Qt be able to request activation/focus for a window.
Some window systems will probably not have callbacks for this functionality, and then calling QWindowSystemInterface::handleWindowActivated(QWidget *w) would be sufficient.
If the window system has some event handling/callbacks then call QWindowSystemInterface::handleWindowActivated(QWidget *w) when the window system gives the notification.
Default implementation calls QWindowSystem::handleWindowActivated(QWidget *w)
Reimplemented from QPlatformWindow.
Definition at line 595 of file qbbwindow.cpp.
Referenced by hasBuffers().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::requestActivateWindow - w=" << widget();
 #endif
     // TODO: Tell screen to set keyboard focus to this window.
     // Notify that we gained focus.
     gainedFocus();
 }
screen()
QBBScreen* QBBWindow::screen () const inline
Definition at line 93 of file qbbwindow.h.
Referenced by QBBGLContext::QBBGLContext().
 { return mScreen; }
scroll()
void QBBWindow::scroll (const QRegion & region, int dx, int dy, bool flush = false)
Definition at line 411 of file qbbwindow.cpp.
Referenced by QBBRasterWindowSurface::flush(), and hasBuffers().
 {
     copyBack(region, dx, dy, flush);
     mScrolled += region;
 }
setBufferSize()
void QBBWindow::setBufferSize (const QSize & size)
Definition at line 288 of file qbbwindow.cpp.
Referenced by QBBRasterWindowSurface::beginPaint(), QBBGLContext::makeCurrent(), QBBGLContext::resizeSurface(), and winId().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::setBufferSize - w=" << widget() << ", s=" << size;
 #endif
     // set window buffer size
     errno = 0;
     int val[2] = { size.width(), size.height() };
     int result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_BUFFER_SIZE, val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window buffer size, errno=%d", errno);
     }
     // create window buffers if they do not exist
     if (!hasBuffers()) {
 #if defined(QBBWINDOW_DEBUG)
         qDebug() << "QBBWindow::setBufferSize - create buffers";
 #endif
         // get pixel format from EGL config if using OpenGL;
         // otherwise inherit pixel format of window's screen
         if (mPlatformGlContext != NULL) {
             val[0] = platformWindowFormatToNativeFormat(mPlatformGlContext->platformWindowFormat());
         } else {
             val[0] = mScreen->nativeFormat();
         }
         errno = 0;
         result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_FORMAT, val);
         if (result != 0) {
             qFatal("QBBWindow: failed to set window pixel format, errno=%d", errno);
         }
         errno = 0;
         result = screen_create_window_buffers(mWindow, MAX_BUFFER_COUNT);
         if (result != 0) {
             qFatal("QBBWindow: failed to create window buffers, errno=%d", errno);
         }
         // check if there are any buffers available
         int bufferCount = 0;
         result = screen_get_window_property_iv(mWindow, SCREEN_PROPERTY_RENDER_BUFFER_COUNT, &bufferCount);
         if (result != 0) {
             qFatal("QBBWindow: failed to query window buffer count, errno=%d", errno);
         }
         if (bufferCount != MAX_BUFFER_COUNT) {
             qFatal("QBBWindow: invalid buffer count. Expected = %d, got = %d", MAX_BUFFER_COUNT, bufferCount);
         }
     }
     // cache new buffer size
     mBufferSize = size;
     // buffers were destroyed; reacquire them
     mCurrentBufferIndex = -1;
     mPreviousDirty = QRegion();
     mScrolled = QRegion();
 }
setGeometry()
void QBBWindow::setGeometry (const QRect & rect) virtual
This function is called by Qt whenever a window is moved or the window is resized.
The resize can happen programatically(from ie. user application) or by the window manager. This means that there is no need to call this function specifically from the window manager callback, instead call QWindowSystemInterface::handleGeometryChange(QWidget *w, const QRect &newRect);
Reimplemented from QPlatformWindow.
Definition at line 157 of file qbbwindow.cpp.
Referenced by QBBWindow().
 {
     int val[2];
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::setGeometry - w=" << widget() << ", (" << rect.x() << "," << rect.y() << "," << rect.width() << "," << rect.height() << ")";
 #endif
     QRect oldGeometry = geometry();
     // call parent method
     QPlatformWindow::setGeometry(rect);
     // set window geometry equal to widget geometry
     errno = 0;
     val[0] = rect.x();
     val[1] = rect.y();
     int result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_POSITION, val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window position, errno=%d", errno);
     }
     errno = 0;
     val[0] = rect.width();
     val[1] = rect.height();
     result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_SIZE, val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window size, errno=%d", errno);
     }
     // set viewport size equal to window size
     errno = 0;
     result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_SOURCE_SIZE, val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window source size, errno=%d", errno);
     }
     // Now move all children.
     QPoint offset;
     if (!oldGeometry.isEmpty()) {
         offset = rect.topLeft();
         offset -= oldGeometry.topLeft();
         QList<QBBWindow*>::iterator it;
         for (it = mChildren.begin(); it != mChildren.end(); it++) {
             (*it)->offset(offset);
         }
     }
 }
setOpacity()
void QBBWindow::setOpacity (qreal level) virtual
Reimplement to be able to let Qt set the opacity level of a window.
Reimplemented from QPlatformWindow.
Definition at line 270 of file qbbwindow.cpp.
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::setOpacity - w=" << widget() << ", o=" << level;
 #endif
     // set window global alpha
     errno = 0;
     int val = (int)(level * 255);
     int result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_GLOBAL_ALPHA, &val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window global alpha, errno=%d", errno);
     }
     // TODO: How to handle children of this window? If we change all the visibilities, then
     //       the transparency will look wrong...
 }
setParent()
void QBBWindow::setParent (const QPlatformWindow * parent) virtual
This function is called to enable native child widgets in QPA.
It is common not to support this feature in Window systems, but can be faked. When this function is called all geometry of this platform window will be relative to the parent.
Reimplemented from QPlatformWindow.
Definition at line 532 of file qbbwindow.cpp.
Referenced by hasBuffers(), and QBBWindow().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::setParent - w=" << widget() << " p=" << window;
 #endif
     // Cast away the const, we need to modify the Hierarchy.
     QBBWindow* newParent = 0;
     if (window)
         newParent = static_cast<QBBWindow*>((QPlatformWindow *)window);
     if (newParent == mParent)
         return;
     removeFromParent();
     mParent = newParent;
     // Add to new Hierarchy position.
     if (mParent) {
         if (mParent->mScreen != mScreen)
             setScreen(mParent->mScreen);
         mParent->mChildren.push_back(this);
     } else {
         mScreen->addWindow(this);
     }
     mScreen->updateHierarchy();
 }
setScreen()
void QBBWindow::setScreen (QBBScreen * platformScreen)
Definition at line 474 of file qbbwindow.cpp.
Referenced by hasBuffers(), QBBIntegration::moveToScreen(), QBBWindow(), and setParent().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::setScreen - w=" << widget();
 #endif
     if (mScreen == platformScreen)
         return;
     if (mScreen)
         mScreen->removeWindow(this);
     platformScreen->addWindow(this);
     mScreen = platformScreen;
     // The display may not have a root (desktop) window yet so we must ensure that one has been
     // created before we can join its group or get its native display property.
     mScreen->ensureDisplayCreated();
     // move window to proper display
     errno = 0;
     screen_display_t display = platformScreen->nativeDisplay();
     int result = screen_set_window_property_pv(mWindow, SCREEN_PROPERTY_DISPLAY, (void **)&display);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window display, errno=%d", errno);
     }
     // add window to display's window group
     errno = 0;
     result = screen_join_window_group(mWindow, platformScreen->windowGroupName());
     if (result != 0) {
         qFatal("QBBWindow: failed to join window group, errno=%d", errno);
     }
     QList<QBBWindow*>::iterator it;
     for (it = mChildren.begin(); it != mChildren.end(); it++) {
         // Only subwindows and tooltips need necessarily be moved to another display with
         // the window.
         if ((widget()->windowType() & Qt::WindowType_Mask) == Qt::SubWindow ||
             (widget()->windowType() & Qt::WindowType_Mask) == Qt::ToolTip)
             (*it)->setScreen(platformScreen);
     }
     mScreen->updateHierarchy();
 }
setVisible()
void QBBWindow::setVisible (bool visible) virtual
Reimplemented in subclasses to show the surface if visible is true, and hide it if visible is false.
Reimplemented from QPlatformWindow.
Definition at line 232 of file qbbwindow.cpp.
Referenced by QBBWindow().
 {
 #if defined(QBBWINDOW_DEBUG)
     qDebug() << "QBBWindow::setVisible - w=" << widget() << ", v=" << visible;
 #endif
     mVisible = visible;
     QBBWindow* root = this;
     while (root->mParent)
         root = root->mParent;
     root->updateVisibility(root->mVisible);
     widget()->activateWindow();
     // Flush the context when invisible, otherwise it won't disappear immediately,
     // but still allow navigator to capture screenshot (thumbnail) when minimized
     if (!visible && !(widget()->windowState() & Qt::WindowMinimized))
         screen_flush_context(mContext, 0);
 }
updateVisibility()
void QBBWindow::updateVisibility (bool parentVisible) private
Definition at line 254 of file qbbwindow.cpp.
Referenced by setVisible().
 {
     // set window visibility
     errno = 0;
     int val = (mVisible && parentVisible) ? 1 : 0;
     int result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_VISIBLE, &val);
     if (result != 0) {
         qFatal("QBBWindow: failed to set window visibility, errno=%d", errno);
     }
     QList<QBBWindow*>::iterator it;
     for (it = mChildren.begin(); it != mChildren.end(); it++) {
         (*it)->updateVisibility(mVisible && parentVisible);
     }
 }
updateZorder()
void QBBWindow::updateZorder (int & topZorder) private
Definition at line 631 of file qbbwindow.cpp.
 {
     errno = 0;
     int result = screen_set_window_property_iv(mWindow, SCREEN_PROPERTY_ZORDER, &topZorder);
     topZorder++;
     if (result != 0)
         qFatal("QBBWindow: failed to set window z-order=%d, errno=%d, mWindow=0x%08x", topZorder, errno, mWindow);
     QList<QBBWindow*>::const_iterator it;
     for (it = mChildren.begin(); it != mChildren.end(); it++)
         (*it)->updateZorder(topZorder);
 }
winId()
virtual WId QBBWindow::winId () const inline virtual
Reimplement in subclasses to return a handle to the native window.
Reimplemented from QPlatformWindow.
Definition at line 70 of file qbbwindow.h.
Referenced by QBBGLContext::createSurface().
 { return (WId)mWindow; }
Friends and Related Functions
QBBScreen
friend class QBBScreen friend
Definition at line 61 of file qbbwindow.h.
Properties
mBuffers
QBBBuffer QBBWindow::mBuffers[MAX_BUFFER_COUNT] private
Definition at line 111 of file qbbwindow.h.
Referenced by buffer(), copyBack(), and post().
mBufferSize
QSize QBBWindow::mBufferSize private
Definition at line 110 of file qbbwindow.h.
Referenced by bufferSize(), hasBuffers(), and setBufferSize().
mChildren
QList<QBBWindow*> QBBWindow::mChildren private
Definition at line 119 of file qbbwindow.h.
Referenced by children(), findWindow(), lower(), offset(), raise(), removeFromParent(), setGeometry(), setParent(), setScreen(), updateVisibility(), updateZorder(), and ~QBBWindow().
mContext
screen_context_t QBBWindow::mContext private
Definition at line 108 of file qbbwindow.h.
Referenced by copyBack(), QBBWindow(), and setVisible().
mCurrentBufferIndex
int QBBWindow::mCurrentBufferIndex private
Definition at line 112 of file qbbwindow.h.
Referenced by buffer(), copyBack(), post(), and setBufferSize().
mParent
QBBWindow* QBBWindow::mParent private
Definition at line 120 of file qbbwindow.h.
Referenced by lower(), raise(), removeFromParent(), setParent(), and setVisible().
mPlatformGlContext
QBBGLContext* QBBWindow::mPlatformGlContext mutable private
Definition at line 117 of file qbbwindow.h.
Referenced by glContext(), setBufferSize(), and ~QBBWindow().
mPreviousBufferIndex
int QBBWindow::mPreviousBufferIndex private
Definition at line 113 of file qbbwindow.h.
Referenced by buffer(), copyBack(), and post().
mPreviousDirty
QRegion QBBWindow::mPreviousDirty private
Definition at line 114 of file qbbwindow.h.
Referenced by post(), and setBufferSize().
mScreen
QBBScreen* QBBWindow::mScreen private
Definition at line 118 of file qbbwindow.h.
Referenced by lower(), post(), raise(), removeFromParent(), screen(), setBufferSize(), setParent(), setScreen(), and ~QBBWindow().
mScrolled
QRegion QBBWindow::mScrolled private
Definition at line 115 of file qbbwindow.h.
Referenced by post(), scroll(), and setBufferSize().
mVisible
bool QBBWindow::mVisible private
Definition at line 121 of file qbbwindow.h.
Referenced by setVisible(), and updateVisibility().
mWindow
screen_window_t QBBWindow::mWindow private
Definition at line 109 of file qbbwindow.h.
Referenced by buffer(), findWindow(), offset(), post(), QBBWindow(), setBufferSize(), setGeometry(), setOpacity(), setScreen(), updateVisibility(), updateZorder(), winId(), and ~QBBWindow().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbwindow.h
/src/plugins/platforms/blackberry/qbbwindow.cpp