Qt 4.8: QDeclarativeListReference Class Reference
QDeclarativeListReference Class Reference
The QDeclarativeListReference class allows the manipulation of QDeclarativeListProperty properties.
#include <qdeclarativelist.h>
Public Functions
bool append (QObject *) const
Appends object to the list.
QObject * at (int) const
Returns the list element at index, or 0 if the operation failed.
bool canAppend () const
Returns true if the list property can be appended to, otherwise false.
bool canAt () const
Returns true if the list property can queried by index, otherwise false.
bool canClear () const
Returns true if the list property can be cleared, otherwise false.
bool canCount () const
Returns true if the list property can be queried for its element count, otherwise false.
bool clear () const
Clears the list.
int count () const
Returns the number of objects in the list, or 0 if the operation failed.
bool isValid () const
Returns true if the instance refers to a valid list property, otherwise false.
const QMetaObject * listElementType () const
Returns the QMetaObject for the elements stored in the list property.
QObject * object () const
Returns the list property's object.
QDeclarativeListReference & operator= (const QDeclarativeListReference &)
QDeclarativeListReference ()
Constructs an invalid instance.
QDeclarativeListReference (QObject *, const char *property, QDeclarativeEngine *=0)
Constructs a QDeclarativeListReference for object's property.
QDeclarativeListReference (const QDeclarativeListReference &)
~QDeclarativeListReference ()
Properties
QDeclarativeListReferencePrivate * d
Friends
class QDeclarativeListReferencePrivate
Detailed Description
The QDeclarativeListReference class allows the manipulation of QDeclarativeListProperty properties.
Since
4.7 QtDeclarative
QDeclarativeListReference allows C++ programs to read from, and assign values to a QML list property in a simple and type safe way. A QDeclarativeListReference can be created by passing an object and property name or through a QDeclarativeProperty instance. These two are equivalant:
QDeclarativeListReference ref1(object, "children");
QDeclarativeProperty ref2(object, "children");
QDeclarativeListReference ref2 = qvariant_cast<QDeclarativeListReference>(ref2.read());
Not all QML list properties support all operations. A set of methods, canAppend(), canAt(), canClear() and canCount() allow programs to query whether an operation is supported on a given property.
QML list properties are typesafe. Only QObject's that derive from the correct base class can be assigned to the list. The listElementType() method can be used to query the QMetaObject of the QObject type supported. Attempting to add objects of the incorrect type to a list property will fail.
Like with normal lists, when accessing a list element by index, it is the callers responsibility to ensure that it does not request an out of range element using the count() method before calling at().
Definition at line 117 of file qdeclarativelist.h.
Constructors and Destructors
QDeclarativeListReference() [1/3]
QDeclarativeListReference::QDeclarativeListReference ()
Constructs an invalid instance.
Definition at line 122 of file qdeclarativelist.cpp.
 : d(0)
 {
 }
QDeclarativeListReference() [2/3]
QDeclarativeListReference::QDeclarativeListReference (QObject * object, const char * property, QDeclarativeEngine * engine = 0)
Constructs a QDeclarativeListReference for object's property.
If property is not a list property, an invalid QDeclarativeListReference is created. If object is destroyed after the reference is constructed, it will automatically become invalid. That is, it is safe to hold QDeclarativeListReference instances even after object is deleted.
Passing engine is required to access some QML created list properties. If in doubt, and an engine is available, pass it.
Definition at line 136 of file qdeclarativelist.cpp.
 : d(0)
 {
     if (!object || !property) return;
     QDeclarativePropertyCache::Data local;
     QDeclarativePropertyCache::Data *data =
         QDeclarativePropertyCache::property(engine, object, QLatin1String(property), local);
     if (!data || !(data->flags & QDeclarativePropertyCache::Data::IsQList)) return;
     QDeclarativeEnginePrivate *p = engine?QDeclarativeEnginePrivate::get(engine):0;
     int listType = p?p->listType(data->propType):QDeclarativeMetaType::listType(data->propType);
     if (listType == -1) return;
     d = new QDeclarativeListReferencePrivate;
     d->object = object;
     d->elementType = p?p->rawMetaObjectForType(listType):QDeclarativeMetaType::qmlType(listType)->baseMetaObject();
     d->propertyType = data->propType;
     void *args[] = { &d->property, 0 };
     QMetaObject::metacall(object, QMetaObject::ReadProperty, data->coreIndex, args);
 }
QDeclarativeListReference() [3/3]
QDeclarativeListReference::QDeclarativeListReference (const QDeclarativeListReference & o)
Warning
This function is not part of the public interface.
Definition at line 162 of file qdeclarativelist.cpp.
 : d(o.d)
 {
     if (d) d->addref();
 }
~QDeclarativeListReference()
QDeclarativeListReference::~QDeclarativeListReference ()
Warning
This function is not part of the public interface.
Definition at line 178 of file qdeclarativelist.cpp.
 {
     if (d) d->release();
 }
Functions
append()
bool QDeclarativeListReference::append (QObject * object) const
Appends object to the list.
Returns true if the operation succeeded, otherwise false.
See also
canAppend()
Definition at line 262 of file qdeclarativelist.cpp.
 {
     if (!canAppend()) return false;
     if (object && !QDeclarativePropertyPrivate::canConvert(object->metaObject(), d->elementType))
         return false;
     d->property.append(&d->property, object);
     return true;
 }
at()
QObject * QDeclarativeListReference::at (int index) const
Returns the list element at index, or 0 if the operation failed.
See also
canAt()
Definition at line 279 of file qdeclarativelist.cpp.
 {
     if (!canAt()) return 0;
     return d->property.at(&d->property, index);
 }
canAppend()
bool QDeclarativeListReference::canAppend () const
Returns true if the list property can be appended to, otherwise false.
Returns false if the reference is invalid.
See also
append()
Definition at line 219 of file qdeclarativelist.cpp.
Referenced by append().
 {
     return (isValid() && d->property.append);
 }
canAt()
bool QDeclarativeListReference::canAt () const
Returns true if the list property can queried by index, otherwise false.
Returns false if the reference is invalid.
See also
at()
Definition at line 230 of file qdeclarativelist.cpp.
Referenced by at().
 {
     return (isValid() && d->property.at);
 }
canClear()
bool QDeclarativeListReference::canClear () const
Returns true if the list property can be cleared, otherwise false.
Returns false if the reference is invalid.
See also
clear()
Definition at line 241 of file qdeclarativelist.cpp.
Referenced by clear().
 {
     return (isValid() && d->property.clear);
 }
canCount()
bool QDeclarativeListReference::canCount () const
Returns true if the list property can be queried for its element count, otherwise false.
Returns false if the reference is invalid.
See also
count()
Definition at line 252 of file qdeclarativelist.cpp.
Referenced by count().
 {
     return (isValid() && d->property.count);
 }
clear()
bool QDeclarativeListReference::clear () const
Clears the list.
Returns true if the operation succeeded, otherwise false.
See also
canClear()
Definition at line 291 of file qdeclarativelist.cpp.
 {
     if (!canClear()) return false;
     d->property.clear(&d->property);
     return true;
 }
count()
int QDeclarativeListReference::count () const
Returns the number of objects in the list, or 0 if the operation failed.
Definition at line 303 of file qdeclarativelist.cpp.
 {
     if (!canCount()) return 0;
     return d->property.count(&d->property);
 }
isValid()
bool QDeclarativeListReference::isValid () const
Returns true if the instance refers to a valid list property, otherwise false.
Definition at line 186 of file qdeclarativelist.cpp.
Referenced by canAppend(), canAt(), canClear(), canCount(), listElementType(), and object().
 {
     return d && d->object;
 }
listElementType()
const QMetaObject * QDeclarativeListReference::listElementType () const
Returns the QMetaObject for the elements stored in the list property.
Returns 0 if the reference is invalid.
The QMetaObject can be used ahead of time to determine whether a given instance can be added to a list.
Definition at line 207 of file qdeclarativelist.cpp.
 {
     if (isValid()) return d->elementType;
     else return 0;
 }
object()
QObject * QDeclarativeListReference::object () const
Returns the list property's object.
Returns 0 if the reference is invalid.
Definition at line 194 of file qdeclarativelist.cpp.
Referenced by QDeclarativeListReference().
 {
     if (isValid()) return d->object;
     else return 0;
 }
operator=()
QDeclarativeListReference & QDeclarativeListReference::operator= (const QDeclarativeListReference & o)
Warning
This function is not part of the public interface.
Definition at line 169 of file qdeclarativelist.cpp.
 {
     if (o.d) o.d->addref();
     if (d) d->release();
     d = o.d;
     return *this;
 }
Friends and Related Functions
QDeclarativeListReferencePrivate
friend class QDeclarativeListReferencePrivate friend
Definition at line 142 of file qdeclarativelist.h.
Referenced by QDeclarativeListReference().
Properties
d
QDeclarativeListReferencePrivate* QDeclarativeListReference::d private
Definition at line 143 of file qdeclarativelist.h.
Referenced by append(), at(), canAppend(), canAt(), canClear(), canCount(), clear(), count(), QDeclarativeListReferencePrivate::init(), isValid(), listElementType(), object(), operator=(), QDeclarativeListReference(), and ~QDeclarativeListReference().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativelist.h
/src/declarative/qml/qdeclarativelist.cpp