Qt 4.8: QBBAbstractVirtualKeyboard Class Reference
QBBAbstractVirtualKeyboard Class Reference abstract
#include <qbbabstractvirtualkeyboard.h>
Public Types
enum KeyboardMode {
Default, Url, Email, Web,
NumPunc, Symbol, Phone, Pin
}
Signals
void heightChanged (int height)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QString countryId () const
int getHeight () const
virtual bool hideKeyboard ()=0
bool isVisible () const
KeyboardMode keyboardMode () const
QString languageId () const
QBBAbstractVirtualKeyboard (QObject *parent=0)
void setInputHintsFromWidget (QWidget *focusWidget)
void setKeyboardMode (KeyboardMode mode)
virtual bool showKeyboard ()=0
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void applyKeyboardMode (KeyboardMode mode)=0
void setCountry (const QString &country)
void setHeight (int height)
void setLanguage (const QString &language)
void setVisible (bool visible)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QString mCountryId
int mHeight
KeyboardMode mKeyboardMode
QString mLanguageId
bool mVisible
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 49 of file qbbabstractvirtualkeyboard.h.
Enumerations
KeyboardMode
enum QBBAbstractVirtualKeyboard::KeyboardMode
Enumerator
Default
Url
Email
Web
NumPunc
Symbol
Phone
Pin
Definition at line 64 of file qbbabstractvirtualkeyboard.h.
 { Default, Url, Email, Web, NumPunc, Symbol, Phone, Pin };
Constructors and Destructors
QBBAbstractVirtualKeyboard()
QBBAbstractVirtualKeyboard::QBBAbstractVirtualKeyboard (QObject * parent = 0) explicit
Definition at line 48 of file qbbabstractvirtualkeyboard.cpp.
     : QObject(parent)
     , mHeight(0)
     , mKeyboardMode(Default)
     , mVisible(false)
     , mLanguageId(QString::fromLatin1("en"))
     , mCountryId(QString::fromLatin1("US"))
 {
 }
Functions
applyKeyboardMode()
virtual void QBBAbstractVirtualKeyboard::applyKeyboardMode (KeyboardMode mode) protected pure virtual
Implemented in QBBVirtualKeyboardPps, and QBBVirtualKeyboardBps.
Referenced by countryId(), and setKeyboardMode().
countryId()
QString QBBAbstractVirtualKeyboard::countryId () const inline
Definition at line 79 of file qbbabstractvirtualkeyboard.h.
Referenced by QBBVirtualKeyboardPps::handleKeyboardInfoMessage(), and QBBVirtualKeyboardBps::handleLocaleEvent().
 { return mCountryId; }
getHeight()
int QBBAbstractVirtualKeyboard::getHeight () const inline
Definition at line 71 of file qbbabstractvirtualkeyboard.h.
Referenced by QBBVirtualKeyboardPps::handleKeyboardInfoMessage(), QBBVirtualKeyboardBps::handleVirtualKeyboardEvent(), setHeight(), and setVisible().
 { return mVisible ? mHeight : 0; }
heightChanged
void QBBAbstractVirtualKeyboard::heightChanged (int height) signal
Referenced by countryId(), setHeight(), and setVisible().
hideKeyboard()
virtual bool QBBAbstractVirtualKeyboard::hideKeyboard () pure virtual
Implemented in QBBVirtualKeyboardPps, and QBBVirtualKeyboardBps.
Referenced by QBBInputContext::dispatchCloseSoftwareInputPanel(), and QBBInputContext::hasPhysicalKeyboard().
isVisible()
bool QBBAbstractVirtualKeyboard::isVisible () const inline
Definition at line 77 of file qbbabstractvirtualkeyboard.h.
Referenced by QBBVirtualKeyboardBps::handleVirtualKeyboardEvent(), QBBVirtualKeyboardBps::hideKeyboard(), and QBBVirtualKeyboardBps::showKeyboard().
 { return mVisible; }
keyboardMode()
KeyboardMode QBBAbstractVirtualKeyboard::keyboardMode () const inline
Definition at line 75 of file qbbabstractvirtualkeyboard.h.
Referenced by QBBVirtualKeyboardBps::showKeyboard(), and QBBVirtualKeyboardPps::showKeyboard().
 { return mKeyboardMode; }
languageId()
QString QBBAbstractVirtualKeyboard::languageId () const inline
Definition at line 78 of file qbbabstractvirtualkeyboard.h.
Referenced by QBBVirtualKeyboardPps::handleKeyboardInfoMessage(), QBBVirtualKeyboardBps::handleLocaleEvent(), and QBBInputContext::language().
 { return mLanguageId; }
setCountry()
void QBBAbstractVirtualKeyboard::setCountry (const QString & country) protected
Definition at line 121 of file qbbabstractvirtualkeyboard.cpp.
Referenced by countryId(), QBBVirtualKeyboardPps::handleKeyboardInfoMessage(), and QBBVirtualKeyboardBps::handleLocaleEvent().
 {
     if (country == mCountryId)
         return;
     mCountryId = country;
 }
setHeight()
void QBBAbstractVirtualKeyboard::setHeight (int height) protected
Definition at line 100 of file qbbabstractvirtualkeyboard.cpp.
Referenced by countryId(), QBBVirtualKeyboardPps::handleKeyboardInfoMessage(), QBBVirtualKeyboardBps::handleVirtualKeyboardEvent(), and QBBVirtualKeyboardBps::QBBVirtualKeyboardBps().
 {
     if (height == mHeight)
         return;
     const int effectiveHeight = getHeight();
     mHeight = height;
     if (effectiveHeight != getHeight())
         emit heightChanged(getHeight());
 }
setInputHintsFromWidget()
void QBBAbstractVirtualKeyboard::setInputHintsFromWidget (QWidget * focusWidget)
Definition at line 68 of file qbbabstractvirtualkeyboard.cpp.
Referenced by getHeight(), and QBBInputContext::hasPhysicalKeyboard().
 {
     if (focusWidget) {
         const Qt::InputMethodHints hints = focusWidget->inputMethodHints();
         if (hints & Qt::ImhEmailCharactersOnly)
             setKeyboardMode(QBBAbstractVirtualKeyboard::Email);
         else if (hints & Qt::ImhDialableCharactersOnly)
             setKeyboardMode(QBBAbstractVirtualKeyboard::Phone);
         else if (hints & Qt::ImhUrlCharactersOnly)
             setKeyboardMode(QBBAbstractVirtualKeyboard::Web);
         else if (hints & Qt::ImhFormattedNumbersOnly || hints & Qt::ImhDigitsOnly)
             setKeyboardMode(QBBAbstractVirtualKeyboard::NumPunc);
         else
             setKeyboardMode(QBBAbstractVirtualKeyboard::Default);
     } else {
         setKeyboardMode(QBBAbstractVirtualKeyboard::Default);
     }
 }
setKeyboardMode()
void QBBAbstractVirtualKeyboard::setKeyboardMode (KeyboardMode mode)
Definition at line 58 of file qbbabstractvirtualkeyboard.cpp.
Referenced by getHeight(), and setInputHintsFromWidget().
 {
     if (mode == mKeyboardMode)
         return;
     mKeyboardMode = mode;
     applyKeyboardMode(mode);
 }
setLanguage()
void QBBAbstractVirtualKeyboard::setLanguage (const QString & language) protected
Definition at line 113 of file qbbabstractvirtualkeyboard.cpp.
Referenced by countryId(), QBBVirtualKeyboardPps::handleKeyboardInfoMessage(), and QBBVirtualKeyboardBps::handleLocaleEvent().
 {
     if (language == mLanguageId)
         return;
     mLanguageId = language;
 }
setVisible()
void QBBAbstractVirtualKeyboard::setVisible (bool visible) protected
Definition at line 87 of file qbbabstractvirtualkeyboard.cpp.
Referenced by countryId(), QBBVirtualKeyboardBps::handleVirtualKeyboardEvent(), and QBBVirtualKeyboardPps::ppsDataReady().
 {
     if (visible == mVisible)
         return;
     const int effectiveHeight = getHeight();
     mVisible = visible;
     if (effectiveHeight != getHeight())
         emit heightChanged(getHeight());
 }
showKeyboard()
virtual bool QBBAbstractVirtualKeyboard::showKeyboard () pure virtual
Implemented in QBBVirtualKeyboardPps, and QBBVirtualKeyboardBps.
Referenced by QBBInputContext::dispatchRequestSoftwareInputPanel(), and QBBInputContext::hasPhysicalKeyboard().
Properties
mCountryId
QString QBBAbstractVirtualKeyboard::mCountryId private
Definition at line 97 of file qbbabstractvirtualkeyboard.h.
Referenced by countryId(), and setCountry().
mHeight
int QBBAbstractVirtualKeyboard::mHeight private
Definition at line 93 of file qbbabstractvirtualkeyboard.h.
Referenced by getHeight(), and setHeight().
mKeyboardMode
KeyboardMode QBBAbstractVirtualKeyboard::mKeyboardMode private
Definition at line 94 of file qbbabstractvirtualkeyboard.h.
Referenced by keyboardMode(), and setKeyboardMode().
mLanguageId
QString QBBAbstractVirtualKeyboard::mLanguageId private
Definition at line 96 of file qbbabstractvirtualkeyboard.h.
Referenced by languageId(), and setLanguage().
mVisible
bool QBBAbstractVirtualKeyboard::mVisible private
Definition at line 95 of file qbbabstractvirtualkeyboard.h.
Referenced by getHeight(), isVisible(), and setVisible().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbabstractvirtualkeyboard.h
/src/plugins/platforms/blackberry/qbbabstractvirtualkeyboard.cpp