Qt 4.8: QFontEngineInfo Class Reference
QFontEngineInfo Class Reference
The QFontEngineInfo class describes a specific font provided by a font engine plugin.
#include <qabstractfontengine_qws.h>
Public Functions
QString family () const
the family name of the font
QFontEngineInfo & operator= (const QFontEngineInfo &other)
Assigns other to this font engine info object, and returns a reference to this.
qreal pixelSize () const
A pixel size of 0 represents a freely scalable font.
QFontEngineInfo ()
Constructs a new empty QFontEngineInfo.
QFontEngineInfo (const QString &family)
Constructs a new QFontEngineInfo with the specified family.
QFontEngineInfo (const QFontEngineInfo &other)
Creates a new font engine info object with the same attributes as other.
void setFamily (const QString &name)
void setPixelSize (qreal size)
void setStyle (QFont::Style style)
void setWeight (int weight)
void setWritingSystems (const QList< QFontDatabase::WritingSystem > &writingSystems)
QFont::Style style () const
the style of the font
int weight () const
The value should be from the QFont::Weight enumeration.
QList< QFontDatabase::WritingSystem > writingSystems () const
An empty list means that any writing system is supported.
~QFontEngineInfo ()
Destroys this QFontEngineInfo object.
Properties
QFontEngineInfoPrivate * d
Detailed Description
The QFontEngineInfo class describes a specific font provided by a font engine plugin.
This function is under development and subject to change.
Since
4.3
QFontEngineInfo is used to describe a request of a font to a font engine plugin as well as to describe the actual fonts a plugin provides.
See also
QAbstractFontEngine, QFontEnginePlugin
Definition at line 60 of file qabstractfontengine_qws.h.
Constructors and Destructors
QFontEngineInfo() [1/3]
QFontEngineInfo::QFontEngineInfo ()
Constructs a new empty QFontEngineInfo.
Definition at line 87 of file qabstractfontengine_qws.cpp.
 {
     d = new QFontEngineInfoPrivate;
 }
QFontEngineInfo() [2/3]
QFontEngineInfo::QFontEngineInfo (const QString & family) explicit
Constructs a new QFontEngineInfo with the specified family.
The resulting object represents a freely scalable font with normal weight and style.
Definition at line 97 of file qabstractfontengine_qws.cpp.
 {
     d = new QFontEngineInfoPrivate;
     d->family = family;
 }
QFontEngineInfo() [3/3]
QFontEngineInfo::QFontEngineInfo (const QFontEngineInfo & other)
Creates a new font engine info object with the same attributes as other.
Definition at line 106 of file qabstractfontengine_qws.cpp.
     : d(new QFontEngineInfoPrivate(*other.d))
 {
 }
~QFontEngineInfo()
QFontEngineInfo::~QFontEngineInfo ()
Destroys this QFontEngineInfo object.
Definition at line 124 of file qabstractfontengine_qws.cpp.
 {
     delete d;
 }
Functions
family()
QString QFontEngineInfo::family () const
the family name of the font
Definition at line 139 of file qabstractfontengine_qws.cpp.
Referenced by initializeDb(), and setFamily().
 {
     return d->family;
 }
operator=()
QFontEngineInfo & QFontEngineInfo::operator= (const QFontEngineInfo & other)
Assigns other to this font engine info object, and returns a reference to this.
Definition at line 115 of file qabstractfontengine_qws.cpp.
 {
     *d = *other.d;
     return *this;
 }
pixelSize()
qreal QFontEngineInfo::pixelSize () const
A pixel size of 0 represents a freely scalable font.
the pixel size of the font
Definition at line 159 of file qabstractfontengine_qws.cpp.
Referenced by initializeDb().
 {
     return d->pixelSize;
 }
setFamily()
void QFontEngineInfo::setFamily (const QString & name)
Definition at line 134 of file qabstractfontengine_qws.cpp.
Referenced by loadSingleEngine().
 {
     d->family = family;
 }
setPixelSize()
void QFontEngineInfo::setPixelSize (qreal size)
Definition at line 154 of file qabstractfontengine_qws.cpp.
Referenced by loadSingleEngine().
 {
     d->pixelSize = size;
 }
setStyle()
void QFontEngineInfo::setStyle (QFont::Style style)
Definition at line 189 of file qabstractfontengine_qws.cpp.
Referenced by loadSingleEngine().
 {
     d->style = style;
 }
setWeight()
void QFontEngineInfo::setWeight (int weight)
Definition at line 174 of file qabstractfontengine_qws.cpp.
Referenced by loadSingleEngine().
 {
     d->weight = weight;
 }
setWritingSystems()
void QFontEngineInfo::setWritingSystems (const QList< QFontDatabase::WritingSystem > & writingSystems)
Definition at line 214 of file qabstractfontengine_qws.cpp.
 {
     d->writingSystems = writingSystems;
 }
style()
QFont::Style QFontEngineInfo::style () const
the style of the font
Definition at line 194 of file qabstractfontengine_qws.cpp.
Referenced by initializeDb(), and setStyle().
 {
     return d->style;
 }
weight()
int QFontEngineInfo::weight () const
The value should be from the QFont::Weight enumeration.
the weight of the font
Definition at line 179 of file qabstractfontengine_qws.cpp.
Referenced by initializeDb(), and setWeight().
 {
     return d->weight;
 }
writingSystems()
QList< QFontDatabase::WritingSystem > QFontEngineInfo::writingSystems () const
An empty list means that any writing system is supported.
the writing systems supported by the font
Definition at line 209 of file qabstractfontengine_qws.cpp.
Referenced by initializeDb(), and setWritingSystems().
 {
     return d->writingSystems;
 }
Properties
d
QFontEngineInfoPrivate* QFontEngineInfo::d private
Definition at line 91 of file qabstractfontengine_qws.h.
Referenced by family(), QFontEnginePlugin::keys(), operator=(), pixelSize(), QFontEnginePlugin::QFontEnginePlugin(), setFamily(), setPixelSize(), setStyle(), setWeight(), setWritingSystems(), style(), weight(), writingSystems(), and ~QFontEngineInfo().
The documentation for this class was generated from the following files:
/src/gui/text/qabstractfontengine_qws.h
/src/gui/text/qabstractfontengine_qws.cpp