Qt 4.8: QtPropertyBag Class Reference
QtPropertyBag Class Reference
Public Functions
unsigned long __stdcall AddRef ()
QtPropertyBag ()
HRESULT __stdcall QueryInterface (REFIID iid, LPVOID *iface)
HRESULT __stdcall Read (LPCOLESTR name, VARIANT *var, IErrorLog *)
unsigned long __stdcall Release ()
HRESULT __stdcall Write (LPCOLESTR name, VARIANT *var)
virtual ~QtPropertyBag ()
Public Variables
QAxBase::PropertyBag map
Properties
LONG ref
Detailed Description
Definition at line 4232 of file qaxbase.cpp.
Constructors and Destructors
QtPropertyBag()
QtPropertyBag::QtPropertyBag () inline
Definition at line 4235 of file qaxbase.cpp.
 :ref(0) {}
~QtPropertyBag()
virtual QtPropertyBag::~QtPropertyBag () inline virtual
Definition at line 4236 of file qaxbase.cpp.
 {}
Functions
AddRef()
unsigned long __stdcall QtPropertyBag::AddRef () inline
Definition at line 4251 of file qaxbase.cpp.
Referenced by QAxBase::propertyBag(), and QAxBase::setPropertyBag().
     {
         return InterlockedIncrement(&ref);
     }
QueryInterface()
HRESULT __stdcall QtPropertyBag::QueryInterface (REFIID iid, LPVOID * iface) inline
Definition at line 4238 of file qaxbase.cpp.
     {
         *iface = 0;
         if (iid == IID_IUnknown)
             *iface = this;
         else if (iid == IID_IPropertyBag)
             *iface = this;
         else
             return E_NOINTERFACE;
         AddRef();
         return S_OK;
     }
Read()
HRESULT __stdcall QtPropertyBag::Read (LPCOLESTR name, VARIANT * var, IErrorLog *) inline
Definition at line 4264 of file qaxbase.cpp.
     {
         if (!var)
             return E_POINTER;
         QString property = QString::fromWCharArray(name);
         QVariant qvar = map.value(property);
         QVariantToVARIANT(qvar, *var);
         return S_OK;
     }
Release()
unsigned long __stdcall QtPropertyBag::Release () inline
Definition at line 4255 of file qaxbase.cpp.
Referenced by QAxBase::propertyBag(), and QAxBase::setPropertyBag().
     {
         LONG refCount = InterlockedDecrement(&ref);
         if (!refCount)
             delete this;
         return refCount;
     }
Write()
HRESULT __stdcall QtPropertyBag::Write (LPCOLESTR name, VARIANT * var) inline
Definition at line 4274 of file qaxbase.cpp.
     {
         if (!var)
             return E_POINTER;
         QString property = QString::fromWCharArray(name);
         QVariant qvar = VARIANTToQVariant(*var, 0);
         map[property] = qvar;
         return S_OK;
     }
Properties
map
QAxBase::PropertyBag QtPropertyBag::map
Definition at line 4285 of file qaxbase.cpp.
Referenced by QAxBase::propertyBag(), and QAxBase::setPropertyBag().
ref
LONG QtPropertyBag::ref private
Definition at line 4288 of file qaxbase.cpp.
The documentation for this class was generated from the following file:
/src/activeqt/container/qaxbase.cpp