Qt 4.8: QGenericArgument Class Reference
QGenericArgument Class Reference
The QGenericArgument class is an internal helper class for marshalling arguments.
#include <qobjectdefs.h>
Public Functions
void * data () const
Returns the data set in the constructor.
const char * name () const
Returns the name set in the constructor.
QGenericArgument (const char *aName=0, const void *aData=0)
Constructs a QGenericArgument object with the given name and data.
Properties
const void * _data
const char * _name
Detailed Description
The QGenericArgument class is an internal helper class for marshalling arguments.
This class should never be used directly. Please use the Q_ARG() macro instead.
See also
Q_ARG(), QMetaObject::invokeMethod(), QGenericReturnArgument
Definition at line 256 of file qobjectdefs.h.
Constructors and Destructors
QGenericArgument()
QGenericArgument::QGenericArgument (const char * aName = 0, const void * aData = 0) inline
Constructs a QGenericArgument object with the given name and data.
Definition at line 259 of file qobjectdefs.h.
         : _data(aData), _name(aName) {}
Functions
data()
QGenericArgument::data () const inline
Returns the data set in the constructor.
Definition at line 261 of file qobjectdefs.h.
Referenced by QMetaMethod::invoke(), and QMetaObject::newInstance().
 { return const_cast<void *>(_data); }
name()
QGenericArgument::name () const inline
Returns the name set in the constructor.
Definition at line 262 of file qobjectdefs.h.
Referenced by QMetaMethod::invoke(), QMetaObject::invokeMethod(), and QMetaObject::newInstance().
 { return _name; }
Properties
_data
const void* QGenericArgument::_data private
Definition at line 265 of file qobjectdefs.h.
_name
const char* QGenericArgument::_name private
Definition at line 266 of file qobjectdefs.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qobjectdefs.h
/src/corelib/kernel/qmetaobject.cpp