Qt 4.8: QDeclarativePinch Class Reference
QDeclarativePinch Class Reference
#include <qdeclarativepincharea_p.h>
Public Types
enum Axis { NoDrag =0x00, XAxis =0x01, YAxis =0x02, XandYAxis =0x03 }
Signals
void activeChanged ()
void dragAxisChanged ()
void maximumRotationChanged ()
void maximumScaleChanged ()
void maximumXChanged ()
void maximumYChanged ()
void minimumRotationChanged ()
void minimumScaleChanged ()
void minimumXChanged ()
void minimumYChanged ()
void targetChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool active () const
Axis axis () const
qreal maximumRotation () const
qreal maximumScale () const
qreal minimumRotation () const
qreal minimumScale () const
QDeclarativePinch ()
void resetTarget ()
void setActive (bool a)
void setAxis (Axis a)
void setMaximumRotation (qreal r)
void setMaximumScale (qreal s)
void setMinimumRotation (qreal r)
void setMinimumScale (qreal s)
void setTarget (QGraphicsObject *target)
void setXmax (qreal x)
void setXmin (qreal x)
void setYmax (qreal y)
void setYmin (qreal y)
QGraphicsObject * target () const
qreal xmax () const
qreal xmin () const
qreal ymax () const
qreal ymin () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool active
Axis dragAxis
bool m_active
Axis m_axis
qreal m_maxRotation
qreal m_maxScale
qreal m_minRotation
qreal m_minScale
QGraphicsObject * m_target
qreal m_xmax
qreal m_xmin
qreal m_ymax
qreal m_ymin
qreal maximumRotation
qreal maximumScale
qreal maximumX
qreal maximumY
qreal minimumRotation
qreal minimumScale
qreal minimumX
qreal minimumY
QGraphicsObject * target
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file qdeclarativepincharea_p.h.
Enumerations
Axis
enum QDeclarativePinch::Axis
Enumerator
NoDrag
XAxis
YAxis
XandYAxis
Definition at line 117 of file qdeclarativepincharea_p.h.
 { NoDrag=0x00, XAxis=0x01, YAxis=0x02, XandYAxis=0x03 };
Constructors and Destructors
QDeclarativePinch()
QDeclarativePinch::QDeclarativePinch ()
Definition at line 170 of file qdeclarativepincharea.cpp.
     : m_target(0), m_minScale(1.0), m_maxScale(1.0)
     , m_minRotation(0.0), m_maxRotation(0.0)
     , m_axis(NoDrag), m_xmin(-FLT_MAX), m_xmax(FLT_MAX)
     , m_ymin(-FLT_MAX), m_ymax(FLT_MAX), m_active(false)
 {
 }
Functions
active()
bool QDeclarativePinch::active () const inline
Definition at line 155 of file qdeclarativepincharea_p.h.
 { return m_active; }
activeChanged
void QDeclarativePinch::activeChanged () signal
axis()
Axis QDeclarativePinch::axis () const inline
Definition at line 118 of file qdeclarativepincharea_p.h.
 { return m_axis; }
dragAxisChanged
void QDeclarativePinch::dragAxisChanged () signal
maximumRotation()
qreal QDeclarativePinch::maximumRotation () const inline
Definition at line 109 of file qdeclarativepincharea_p.h.
 { return m_maxRotation; }
maximumRotationChanged
void QDeclarativePinch::maximumRotationChanged () signal
maximumScale()
qreal QDeclarativePinch::maximumScale () const inline
Definition at line 94 of file qdeclarativepincharea_p.h.
 { return m_maxScale; }
maximumScaleChanged
void QDeclarativePinch::maximumScaleChanged () signal
maximumXChanged
void QDeclarativePinch::maximumXChanged () signal
maximumYChanged
void QDeclarativePinch::maximumYChanged () signal
minimumRotation()
qreal QDeclarativePinch::minimumRotation () const inline
Definition at line 102 of file qdeclarativepincharea_p.h.
 { return m_minRotation; }
minimumRotationChanged
void QDeclarativePinch::minimumRotationChanged () signal
minimumScale()
qreal QDeclarativePinch::minimumScale () const inline
Definition at line 87 of file qdeclarativepincharea_p.h.
 { return m_minScale; }
minimumScaleChanged
void QDeclarativePinch::minimumScaleChanged () signal
minimumXChanged
void QDeclarativePinch::minimumXChanged () signal
minimumYChanged
void QDeclarativePinch::minimumYChanged () signal
resetTarget()
void QDeclarativePinch::resetTarget () inline
Definition at line 80 of file qdeclarativepincharea_p.h.
{
         if (!m_target)
             return;
         m_target = 0;
         emit targetChanged();
     }
setActive()
void QDeclarativePinch::setActive (bool a) inline
Definition at line 156 of file qdeclarativepincharea_p.h.
{
         if (a == m_active)
             return;
         m_active = a;
         emit activeChanged();
     }
setAxis()
void QDeclarativePinch::setAxis (Axis a) inline
Definition at line 119 of file qdeclarativepincharea_p.h.
{
         if (a == m_axis)
             return;
         m_axis = a;
         emit dragAxisChanged();
     }
setMaximumRotation()
void QDeclarativePinch::setMaximumRotation (qreal r) inline
Definition at line 110 of file qdeclarativepincharea_p.h.
{
         if (r == m_maxRotation)
             return;
         m_maxRotation = r;
         emit maximumRotationChanged();
     }
setMaximumScale()
void QDeclarativePinch::setMaximumScale (qreal s) inline
Definition at line 95 of file qdeclarativepincharea_p.h.
{
         if (s == m_maxScale)
             return;
         m_maxScale = s;
         emit maximumScaleChanged();
     }
setMinimumRotation()
void QDeclarativePinch::setMinimumRotation (qreal r) inline
Definition at line 103 of file qdeclarativepincharea_p.h.
{
         if (r == m_minRotation)
             return;
         m_minRotation = r;
         emit minimumRotationChanged();
     }
setMinimumScale()
void QDeclarativePinch::setMinimumScale (qreal s) inline
Definition at line 88 of file qdeclarativepincharea_p.h.
{
         if (s == m_minScale)
             return;
         m_minScale = s;
         emit minimumScaleChanged();
     }
setTarget()
void QDeclarativePinch::setTarget (QGraphicsObject * target) inline
Definition at line 74 of file qdeclarativepincharea_p.h.
{
         if (target == m_target)
             return;
         m_target = target;
         emit targetChanged();
     }
setXmax()
void QDeclarativePinch::setXmax (qreal x) inline
Definition at line 134 of file qdeclarativepincharea_p.h.
{
         if (x == m_xmax)
             return;
         m_xmax = x;
         emit maximumXChanged();
     }
setXmin()
void QDeclarativePinch::setXmin (qreal x) inline
Definition at line 127 of file qdeclarativepincharea_p.h.
{
         if (x == m_xmin)
             return;
         m_xmin = x;
         emit minimumXChanged();
     }
setYmax()
void QDeclarativePinch::setYmax (qreal y) inline
Definition at line 148 of file qdeclarativepincharea_p.h.
{
         if (y == m_ymax)
             return;
         m_ymax = y;
         emit maximumYChanged();
     }
setYmin()
void QDeclarativePinch::setYmin (qreal y) inline
Definition at line 141 of file qdeclarativepincharea_p.h.
{
         if (y == m_ymin)
             return;
         m_ymin = y;
         emit minimumYChanged();
     }
target()
QGraphicsObject* QDeclarativePinch::target () const inline
Definition at line 73 of file qdeclarativepincharea_p.h.
 { return m_target; }
targetChanged
void QDeclarativePinch::targetChanged () signal
xmax()
qreal QDeclarativePinch::xmax () const inline
Definition at line 133 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { return m_xmax; }
xmin()
qreal QDeclarativePinch::xmin () const inline
Definition at line 126 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { return m_xmin; }
ymax()
qreal QDeclarativePinch::ymax () const inline
Definition at line 147 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { return m_ymax; }
ymin()
qreal QDeclarativePinch::ymin () const inline
Definition at line 140 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
 { return m_ymin; }
Properties
active
bool QDeclarativePinch::active private
Definition at line 68 of file qdeclarativepincharea_p.h.
dragAxis
Axis QDeclarativePinch::dragAxis private
Definition at line 63 of file qdeclarativepincharea_p.h.
m_active
bool QDeclarativePinch::m_active private
Definition at line 187 of file qdeclarativepincharea_p.h.
m_axis
Axis QDeclarativePinch::m_axis private
Definition at line 182 of file qdeclarativepincharea_p.h.
m_maxRotation
qreal QDeclarativePinch::m_maxRotation private
Definition at line 181 of file qdeclarativepincharea_p.h.
m_maxScale
qreal QDeclarativePinch::m_maxScale private
Definition at line 179 of file qdeclarativepincharea_p.h.
m_minRotation
qreal QDeclarativePinch::m_minRotation private
Definition at line 180 of file qdeclarativepincharea_p.h.
m_minScale
qreal QDeclarativePinch::m_minScale private
Definition at line 178 of file qdeclarativepincharea_p.h.
m_target
QGraphicsObject* QDeclarativePinch::m_target private
Definition at line 177 of file qdeclarativepincharea_p.h.
m_xmax
qreal QDeclarativePinch::m_xmax private
Definition at line 184 of file qdeclarativepincharea_p.h.
m_xmin
qreal QDeclarativePinch::m_xmin private
Definition at line 183 of file qdeclarativepincharea_p.h.
m_ymax
qreal QDeclarativePinch::m_ymax private
Definition at line 186 of file qdeclarativepincharea_p.h.
m_ymin
qreal QDeclarativePinch::m_ymin private
Definition at line 185 of file qdeclarativepincharea_p.h.
maximumRotation
qreal QDeclarativePinch::maximumRotation private
Definition at line 62 of file qdeclarativepincharea_p.h.
maximumScale
qreal QDeclarativePinch::maximumScale private
Definition at line 60 of file qdeclarativepincharea_p.h.
maximumX
qreal QDeclarativePinch::maximumX private
Definition at line 65 of file qdeclarativepincharea_p.h.
maximumY
qreal QDeclarativePinch::maximumY private
Definition at line 67 of file qdeclarativepincharea_p.h.
minimumRotation
qreal QDeclarativePinch::minimumRotation private
Definition at line 61 of file qdeclarativepincharea_p.h.
minimumScale
qreal QDeclarativePinch::minimumScale private
Definition at line 59 of file qdeclarativepincharea_p.h.
minimumX
qreal QDeclarativePinch::minimumX private
Definition at line 64 of file qdeclarativepincharea_p.h.
minimumY
qreal QDeclarativePinch::minimumY private
Definition at line 66 of file qdeclarativepincharea_p.h.
target
QGraphicsObject* QDeclarativePinch::target private
Definition at line 58 of file qdeclarativepincharea_p.h.
Referenced by QDeclarativePinchArea::updatePinch().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativepincharea_p.h
/src/declarative/graphicsitems/qdeclarativepincharea.cpp