Qt 4.8: QTDSDriver Class Reference
QTDSDriver Class Reference
#include <qsql_tds.h>
Public Functions
void close ()
Derived classes must reimplement this pure virtual function in order to close the database connection.
QSqlResult * createResult () const
Creates an empty SQL result on the database.
QString escapeIdentifier (const QString &identifier, IdentifierType type) const
Returns the identifier escaped according to the database rules.
QString formatValue (const QSqlField &field, bool trimStrings) const
Returns a string representation of the field value for the database.
QVariant handle () const
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
bool hasFeature (DriverFeature f) const
Returns true if the driver supports feature feature; otherwise returns false.
bool open (const QString &db, const QString &user, const QString &password, const QString &host, int port, const QString &connOpts)
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
QSqlIndex primaryIndex (const QString &tablename) const
Returns the primary index for table tableName.
QTDSDriver (QObject *parent=0)
QTDSDriver (LOGINREC *rec, const QString &host, const QString &db, QObject *parent=0)
QSqlRecord record (const QString &tablename) const
Returns a QSqlRecord populated with the names of the fields in table tableName.
QStringList tables (QSql::TableType) const
Returns a list of the names of the tables in the database.
~QTDSDriver ()
Public Functions inherited from QSqlDriver
bool isIdentifierEscaped (const QString &identifier, IdentifierType type) const
Returns whether identifier is escaped according to the database rules.
virtual bool isOpen () const
Returns true if the database connection is open; otherwise returns false.
bool isOpenError () const
Returns true if the there was an error opening the database connection; otherwise returns false.
QSqlError lastError () const
Returns a QSqlError object which contains information about the last error that occurred on the database.
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
QSqlDriver (QObject *parent=0)
Constructs a new driver with the given parent.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created by this driver to precisionPolicy.
virtual QString sqlStatement (StatementType type, const QString &tableName, const QSqlRecord &rec, bool preparedStatement) const
Returns a SQL statement of type type for the table tableName with the values from rec.
QString stripDelimiters (const QString &identifier, IdentifierType type) const
Returns the identifier with the leading and trailing delimiters removed, identifier can either be a table name or field name, dependent on type.
QStringList subscribedToNotifications () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotification (const QString &name)
This function is called to subscribe to event notifications from the database.
bool unsubscribeFromNotification (const QString &name)
This function is called to unsubscribe from event notifications from the database.
~QSqlDriver ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool beginTransaction ()
This function is called to begin a transaction.
bool commitTransaction ()
This function is called to commit a transaction.
bool rollbackTransaction ()
This function is called to rollback a transaction.
Protected Functions inherited from QSqlDriver
virtual void setLastError (const QSqlError &e)
This function is used to set the value of the last error, error, that occurred on the database.
virtual void setOpen (bool o)
This function sets the open state of the database to open.
virtual void setOpenError (bool e)
This function sets the open error state of the database to error.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void init ()
Properties
QTDSDriverPrivate * d
Friends
class QTDSResult
Additional Inherited Members
Public Types inherited from QSqlDriver
enum DriverFeature {
Transactions, QuerySize, BLOB, Unicode,
PreparedQueries, NamedPlaceholders, PositionalPlaceholders, LastInsertId,
BatchOperations, SimpleLocking, LowPrecisionNumbers, EventNotifications,
FinishQuery, MultipleResultSets
}
This enum contains a list of features a driver might support.
enum IdentifierType { FieldName, TableName }
This enum contains a list of SQL identifier types.
enum StatementType {
WhereStatement, SelectStatement, UpdateStatement, InsertStatement,
DeleteStatement
}
This enum contains a list of SQL statement (or clause) types the driver can create.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QSqlDriver
void notification (const QString &name)
This signal is emitted when the database posts an event notification that the driver subscribes to.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QSqlDriver
bool isIdentifierEscapedImplementation (const QString &identifier, IdentifierType type) const
This slot returns whether identifier is escaped according to the database rules.
QString stripDelimitersImplementation (const QString &identifier, IdentifierType type) const
This slot returns identifier with the leading and trailing delimiters removed, identifier can either be a tablename or field name, dependent on type.
QStringList subscribedToNotificationsImplementation () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotificationImplementation (const QString &name)
This slot is called to subscribe to event notifications from the database.
bool unsubscribeFromNotificationImplementation (const QString &name)
This slot is called to unsubscribe from event notifications from the database.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 97 of file qsql_tds.h.
Constructors and Destructors
QTDSDriver() [1/2]
QTDSDriver::QTDSDriver (QObject * parent = 0) explicit
Definition at line 511 of file qsql_tds.cpp.
     : QSqlDriver(parent)
 {
     init();
 }
QTDSDriver() [2/2]
QTDSDriver::QTDSDriver (LOGINREC * rec, const QString & host, const QString & db, QObject * parent = 0)
Definition at line 517 of file qsql_tds.cpp.
     : QSqlDriver(parent)
 {
     init();
     d->login = rec;
     d->hostName = host;
     d->db = db;
     if (rec) {
         setOpen(true);
         setOpenError(false);
     }
 }
~QTDSDriver()
QTDSDriver::~QTDSDriver ()
Definition at line 545 of file qsql_tds.cpp.
 {
     dberrhandle(0);
     dbmsghandle(0);
     // dbexit also calls dbclose if necessary
     dbexit();
     delete d;
 }
Functions
beginTransaction()
bool QTDSDriver::beginTransaction () protected virtual
This function is called to begin a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
commitTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 634 of file qsql_tds.cpp.
 {
     return false;
 /*
     if (!isOpen()) {
         qWarning("QTDSDriver::beginTransaction: Database not open");
         return false;
     }
     if (dbcmd(d->dbproc, "BEGIN TRANSACTION") == FAIL) {
         setLastError(d->lastError);
         dbfreebuf(d->dbproc);
         return false;
     }
     if (dbsqlexec(d->dbproc) == FAIL) {
         setLastError(d->lastError);
         dbfreebuf(d->dbproc);
         return false;
     }
     while(dbresults(d->dbproc) == NO_MORE_RESULTS) {}
     dbfreebuf(d->dbproc);
     inTransaction = true;
     return true;
 */
 }
close()
void QTDSDriver::close () virtual
Derived classes must reimplement this pure virtual function in order to close the database connection.
Return true on success, false on failure.
See also
open(), setOpen()
Implements QSqlDriver.
Definition at line 615 of file qsql_tds.cpp.
Referenced by open().
 {
     if (isOpen()) {
 #ifdef Q_USE_SYBASE
         dbloginfree(d->login);
 #else
         dbfreelogin(d->login);
 #endif
         d->login = 0;
         setOpen(false);
         setOpenError(false);
     }
 }
commitTransaction()
bool QTDSDriver::commitTransaction () protected virtual
This function is called to commit a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 659 of file qsql_tds.cpp.
 {
     return false;
 /*
     if (!isOpen()) {
         qWarning("QTDSDriver::commitTransaction: Database not open");
         return false;
     }
     if (dbcmd(d->dbproc, "COMMIT TRANSACTION") == FAIL) {
         setLastError(d->lastError);
         dbfreebuf(d->dbproc);
         return false;
     }
     if (dbsqlexec(d->dbproc) == FAIL) {
         setLastError(d->lastError);
         dbfreebuf(d->dbproc);
         return false;
     }
     while(dbresults(d->dbproc) == NO_MORE_RESULTS) {}
     dbfreebuf(d->dbproc);
     inTransaction = false;
     return true;
 */
 }
createResult()
QSqlResult * QTDSDriver::createResult () const virtual
Creates an empty SQL result on the database.
Derived classes must reimplement this function and return a QSqlResult object appropriate for their database to the caller.
Implements QSqlDriver.
Definition at line 629 of file qsql_tds.cpp.
Referenced by primaryIndex(), record(), and tables().
 {
     return new QTDSResult(this);
 }
escapeIdentifier()
QString QTDSDriver::escapeIdentifier (const QString & identifier, IdentifierType type) const virtual
Returns the identifier escaped according to the database rules.
identifier can either be a table name or field name, dependent on type.
The default implementation does nothing.
See also
isIdentifierEscaped()
Reimplemented from QSqlDriver.
Definition at line 823 of file qsql_tds.cpp.
 {
     QString res = identifier;
     if(!identifier.isEmpty() && !identifier.startsWith(QLatin1Char('"')) && !identifier.endsWith(QLatin1Char('"')) ) {
         res.replace(QLatin1Char('"'), QLatin1String("\"\""));
         res.prepend(QLatin1Char('"')).append(QLatin1Char('"'));
         res.replace(QLatin1Char('.'), QLatin1String("\".\""));
     }
     return res;
 }
formatValue()
QString QTDSDriver::formatValue (const QSqlField & field, bool trimStrings) const virtual
Returns a string representation of the field value for the database.
Use the other formatValue() overload instead.
This is used, for example, when constructing INSERT and UPDATE statements.
The default implementation returns the value formatted as a string according to the following rules:
If field is character data, the value is returned enclosed in single quotation marks, which is appropriate for many SQL databases. Any embedded single-quote characters are escaped (replaced with two single-quote characters). If trimStrings is true (the default is false), all trailing whitespace is trimmed from the field.
If field is date/time data, the value is formatted in ISO format and enclosed in single quotation marks. If the date/time data is invalid, "NULL" is returned.
If field is bytearray data, and the driver can edit binary fields, the value is formatted as a hexadecimal string.
For any other field type, toString() is called on its value and the result of this is returned.
See also
QVariant::toString()
Reimplemented from QSqlDriver.
Definition at line 762 of file qsql_tds.cpp.
 {
     QString r;
     if (field.isNull())
         r = QLatin1String("NULL");
     else if (field.type() == QVariant::DateTime) {
         if (field.value().toDateTime().isValid()){
             r = field.value().toDateTime().toString(QLatin1String("yyyyMMdd hh:mm:ss"));
             r.prepend(QLatin1String("'"));
             r.append(QLatin1String("'"));
         } else
             r = QLatin1String("NULL");
     } else if (field.type() == QVariant::ByteArray) {
         QByteArray ba = field.value().toByteArray();
         QString res;
         static const char hexchars[] = "0123456789abcdef";
         for (int i = 0; i < ba.size(); ++i) {
             uchar s = (uchar) ba[i];
             res += QLatin1Char(hexchars[s >> 4]);
             res += QLatin1Char(hexchars[s & 0x0f]);
         }
         r = QLatin1String("0x") + res;
     } else {
         r = QSqlDriver::formatValue(field, trim);
     }
     return r;
 }
handle()
QVariant QTDSDriver::handle () const virtual
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the connection is modified (for example, if you close the connection).
The handle can be NULL if the connection is not open yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a connection to sqlite:
QSqlDatabase db = ...;
QVariant v = db.driver()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3*") == 0) {
    // v.data() returns a pointer to the handle
    sqlite3 *handle = *static_cast<sqlite3 **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (qstrcmp(v.typeName(), "PGconn*") == 0) {
    PGconn *handle = *static_cast<PGconn **>(v.data());
    if (handle != 0) ...
}
if (qstrcmp(v.typeName(), "MYSQL*") == 0) {
    MYSQL *handle = *static_cast<MYSQL **>(v.data());
    if (handle != 0) ...
}
See also
QSqlResult::handle()
Reimplemented from QSqlDriver.
Definition at line 530 of file qsql_tds.cpp.
 {
     return QVariant(qRegisterMetaType<LOGINREC *>("LOGINREC*"), &d->login);
 }
hasFeature()
bool QTDSDriver::hasFeature (DriverFeature feature) const virtual
Returns true if the driver supports feature feature; otherwise returns false.
Note that some databases need to be open() before this can be determined.
See also
DriverFeature
Implements QSqlDriver.
Definition at line 554 of file qsql_tds.cpp.
 {
     switch (f) {
     case Transactions:
     case QuerySize:
     case Unicode:
     case SimpleLocking:
     case EventNotifications:
     case MultipleResultSets:
         return false;
     case BLOB:
         return true;
     default:
         return false;
     }
 }
init()
void QTDSDriver::init () private
Definition at line 535 of file qsql_tds.cpp.
Referenced by QTDSDriver().
 {
     d = new QTDSDriverPrivate();
     d->initialized = (dbinit() == SUCCEED);
     // the following two code-lines will fail compilation on some FreeTDS versions
     // just comment them out if you have FreeTDS (you won't get any errors and warnings then)
     dberrhandle((QERRHANDLE)qTdsErrHandler);
     dbmsghandle((QMSGHANDLE)qTdsMsgHandler);
 }
open()
bool QTDSDriver::open (const QString & db, const QString & user, const QString & password, const QString & host, int port, const QString & options) virtual
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
The function must return true on success and false on failure.
See also
setOpen()
Implements QSqlDriver.
Definition at line 571 of file qsql_tds.cpp.
 {
     if (isOpen())
         close();
     if (!d->initialized) {
         setOpenError(true);
         return false;
     }
     d->login = dblogin();
     if (!d->login) {
         setOpenError(true);
         return false;
     }
     DBSETLPWD(d->login, const_cast<char*>(password.toLocal8Bit().constData()));
     DBSETLUSER(d->login, const_cast<char*>(user.toLocal8Bit().constData()));
     // Now, try to open and use the database. If this fails, return false.
     DBPROCESS* dbproc;
     dbproc = dbopen(d->login, const_cast<char*>(host.toLatin1().constData()));
     if (!dbproc) {
         setLastError(qMakeError(tr("Unable to open connection"), QSqlError::ConnectionError, -1));
         setOpenError(true);
         return false;
     }
     if (dbuse(dbproc, const_cast<char*>(db.toLatin1().constData())) == FAIL) {
         setLastError(qMakeError(tr("Unable to use database"), QSqlError::ConnectionError, -1));
         setOpenError(true);
         return false;
     }
     dbclose( dbproc );
     setOpen(true);
     setOpenError(false);
     d->hostName = host;
     d->db = db;
     return true;
 }
primaryIndex()
QSqlIndex QTDSDriver::primaryIndex (const QString & tableName) const virtual
Returns the primary index for table tableName.
Returns an empty QSqlIndex if the table doesn't have a primary index. The default implementation returns an empty index.
Reimplemented from QSqlDriver.
Definition at line 791 of file qsql_tds.cpp.
 {
     QSqlRecord rec = record(tablename);
     QString table = tablename;
     if (isIdentifierEscaped(table, QSqlDriver::TableName))
         table = stripDelimiters(table, QSqlDriver::TableName);
     QSqlIndex idx(table);
     if ((!isOpen()) || (table.isEmpty()))
         return QSqlIndex();
     QSqlQuery t(createResult());
     t.setForwardOnly(true);
     t.exec(QString::fromLatin1("sp_helpindex '%1'").arg(table));
     if (t.next()) {
         QStringList fNames = t.value(2).toString().simplified().split(QLatin1Char(','));
         QRegExp regx(QLatin1String("\\s*(\\S+)(?:\\s+(DESC|desc))?\\s*"));
         for(QStringList::Iterator it = fNames.begin(); it != fNames.end(); ++it) {
             regx.indexIn(*it);
             QSqlField f(regx.cap(1), rec.field(regx.cap(1)).type());
             if (regx.cap(2).toLower() == QLatin1String("desc")) {
                 idx.append(f, true);
             } else {
                 idx.append(f, false);
             }
         }
         idx.setName(t.value(0).toString().simplified());
     }
     return idx;
 }
record()
QSqlRecord QTDSDriver::record (const QString & tableName) const virtual
Returns a QSqlRecord populated with the names of the fields in table tableName.
Use query.
If no such table exists, an empty record is returned. The default implementation returns an empty record.
record() instead.
Reimplemented from QSqlDriver.
Definition at line 709 of file qsql_tds.cpp.
Referenced by primaryIndex().
 {
     QSqlRecord info;
     if (!isOpen())
         return info;
     QSqlQuery t(createResult());
     t.setForwardOnly(true);
     QString table = tablename;
     if (isIdentifierEscaped(table, QSqlDriver::TableName))
         table = stripDelimiters(table, QSqlDriver::TableName);
     QString stmt (QLatin1String("select name, type, length, prec from syscolumns "
                    "where id = (select id from sysobjects where name = '%1')"));
     t.exec(stmt.arg(table));
     while (t.next()) {
         QSqlField f(t.value(0).toString().simplified(), qDecodeTDSType(t.value(1).toInt()));
         f.setLength(t.value(2).toInt());
         f.setPrecision(t.value(3).toInt());
         f.setSqlType(t.value(1).toInt());
         info.append(f);
     }
     return info;
 }
rollbackTransaction()
bool QTDSDriver::rollbackTransaction () protected virtual
This function is called to rollback a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), commitTransaction()
Reimplemented from QSqlDriver.
Definition at line 684 of file qsql_tds.cpp.
 {
     return false;
 /*
     if (!isOpen()) {
         qWarning("QTDSDriver::rollbackTransaction: Database not open");
         return false;
     }
     if (dbcmd(d->dbproc, "ROLLBACK TRANSACTION") == FAIL) {
         setLastError(d->lastError);
         dbfreebuf(d->dbproc);
         return false;
     }
     if (dbsqlexec(d->dbproc) == FAIL) {
         setLastError(d->lastError);
         dbfreebuf(d->dbproc);
         return false;
     }
     while(dbresults(d->dbproc) == NO_MORE_RESULTS) {}
     dbfreebuf(d->dbproc);
     inTransaction = false;
     return true;
 */
 }
tables()
QStringList QTDSDriver::tables (QSql::TableType tableType) const virtual
Returns a list of the names of the tables in the database.
The default implementation returns an empty list.
The tableType argument describes what types of tables should be returned. Due to binary compatibility, the string contains the value of the enum QSql::TableTypes as text. An empty string should be treated as QSql::Tables for backward compatibility.
Reimplemented from QSqlDriver.
Definition at line 734 of file qsql_tds.cpp.
 {
     QStringList list;
     if (!isOpen())
         return list;
     QStringList typeFilter;
     if (type & QSql::Tables)
         typeFilter += QLatin1String("type='U'");
     if (type & QSql::SystemTables)
         typeFilter += QLatin1String("type='S'");
     if (type & QSql::Views)
         typeFilter += QLatin1String("type='V'");
     if (typeFilter.isEmpty())
         return list;
     QSqlQuery t(createResult());
     t.setForwardOnly(true);
     t.exec(QLatin1String("select name from sysobjects where ") + typeFilter.join(QLatin1String(" or ")));
     while (t.next())
         list.append(t.value(0).toString().simplified());
     return list;
 }
Friends and Related Functions
QTDSResult
friend class QTDSResult friend
Definition at line 100 of file qsql_tds.h.
Referenced by createResult().
Properties
d
QTDSDriverPrivate* QTDSDriver::d private
Definition at line 130 of file qsql_tds.h.
Referenced by close(), handle(), init(), open(), QTDSDriver(), QTDSResult::QTDSResult(), and ~QTDSDriver().
The documentation for this class was generated from the following files:
/src/sql/drivers/tds/qsql_tds.h
/src/sql/drivers/tds/qsql_tds.cpp