Qt 4.8: QAccessibleItemView Class Reference
QAccessibleItemView Class Reference
#include <complexwidgets.h>
Public Functions
QAccessibleInterface * accessibleAt (int row, int column)
QAccessibleInterface * caption ()
void cellAtIndex (int index, int *row, int *column, int *rowSpan, int *columnSpan, bool *isSelected)
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
QModelIndex childIndex (int child) const
int childIndex (int rowIndex, int columnIndex)
int columnCount ()
QString columnDescription (int column)
QAccessibleInterface * columnHeader ()
int columnIndex (int childIndex)
int columnSpan (int row, int column)
int entryFromIndex (const QModelIndex &index) const
QHeaderView * horizontalHeader () const
int indexOfChild (const QAccessibleInterface *iface) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
bool isColumnSelected (int column)
bool isRowSelected (int row)
bool isSelected (int row, int column)
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
bool isValidChildRole (QAccessible::Role role) const
int navigate (RelationFlag relation, int index, QAccessibleInterface **iface) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleItemView (QWidget *w)
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
int rowCount ()
QString rowDescription (int row)
QAccessibleInterface * rowHeader ()
int rowIndex (int childIndex)
int rowSpan (int row, int column)
void selectColumn (int column)
int selectedColumnCount ()
int selectedColumns (int maxColumns, QList< int > *columns)
int selectedRowCount ()
int selectedRows (int maxRows, QList< int > *rows)
void selectRow (int row)
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
QAccessibleInterface * summary ()
QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
void unselectColumn (int column)
void unselectRow (int row)
QHeaderView * verticalHeader () const
Public Functions inherited from QAccessibleAbstractScrollArea
QAbstractScrollArea * abstractScrollArea () const
QVariant invokeMethodEx (QAccessible::Method method, int child, const QVariantList &params)
QAccessibleAbstractScrollArea (QWidget *widget)
Public Functions inherited from QAccessibleWidgetEx
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Public Functions inherited from QAccessibleObjectEx
QAccessibleObjectEx (QObject *object)
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Public Functions inherited from QAccessibleTableInterface
QAccessible2Interface * qAccessibleTableCastHelper ()
Public Functions inherited from QAccessible2Interface
virtual ~QAccessible2Interface ()
Protected Functions
QModelIndex index (int row, int column) const
QAbstractItemView * itemView () const
Protected Functions inherited from QAccessibleWidgetEx
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Private Functions
bool atViewport () const
QAccessible::Role expectedRoleOfChildren () const
Properties
bool atVP
Additional Inherited Members
Public Types inherited from QAccessibleAbstractScrollArea
enum AbstractScrollAreaElement {
Self = 0, Viewport, HorizontalContainer, VerticalContainer,
CornerWidget, Undefined
}
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 163 of file complexwidgets.h.
Constructors and Destructors
QAccessibleItemView()
QAccessibleItemView::QAccessibleItemView (QWidget * w) explicit
Definition at line 806 of file complexwidgets.cpp.
Referenced by navigate().
     : QAccessibleAbstractScrollArea(w->objectName() == QLatin1String("qt_scrollarea_viewport") ? w->parentWidget() : w)
 {
     atVP = w->objectName() == QLatin1String("qt_scrollarea_viewport");
 }
Functions
accessibleAt()
QAccessibleInterface * QAccessibleItemView::accessibleAt (int row, int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1161 of file complexwidgets.cpp.
 {
     QWidget *indexWidget = itemView()->indexWidget(index(row, column));
     return QAccessible::queryAccessibleInterface(indexWidget);
 }
atViewport()
bool QAccessibleItemView::atViewport () const inline private
Definition at line 221 of file complexwidgets.h.
Referenced by childAt(), childCount(), childIndex(), indexOfChild(), isValid(), isValidChildRole(), navigate(), object(), rect(), role(), setText(), state(), and text().
{
         return atVP;
     };
caption()
QAccessibleInterface * QAccessibleItemView::caption () virtual
Implements QAccessibleTableInterface.
Definition at line 1168 of file complexwidgets.cpp.
 {
     return 0;
 }
cellAtIndex()
void QAccessibleItemView::cellAtIndex (int index, int * row, int * column, int * rowSpan, int * columnSpan, bool * isSelected) virtual
Implements QAccessibleTableInterface.
Definition at line 1334 of file complexwidgets.cpp.
 {
     *row = rowIndex(index);
     *column = columnIndex(index);
     *rSpan = rowSpan(*row, *column);
     *cSpan = columnSpan(*row, *column);
     *isSelect = isSelected(*row, *column);
 }
childAt()
int QAccessibleItemView::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 1052 of file complexwidgets.cpp.
 {
     if (atViewport()) {
         QPoint p(x, y);
         for (int i = childCount(); i >= 0; --i) {
             if (rect(i).contains(p))
                 return i;
         }
         return -1;
     } else {
         return QAccessibleAbstractScrollArea::childAt(x, y);
     }
 }
childCount()
int QAccessibleItemView::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 944 of file complexwidgets.cpp.
Referenced by childAt().
 {
     if (atViewport()) {
         if (itemView()->model() == 0)
             return 0;
         QAbstractItemModel *m = itemView()->model();
         QModelIndex idx = m->index(0,0);
         if (!idx.isValid())
             return 0;
         ModelIndexIterator it(itemView());
         int count = 1;
         while (it.next()) {
             ++count;
         }
         if (horizontalHeader())
             ++count;
         return count;
     } else {
         return QAccessibleAbstractScrollArea::childCount();
     }
 }
childIndex() [1/2]
QModelIndex QAccessibleItemView::childIndex (int child) const
Definition at line 915 of file complexwidgets.cpp.
Referenced by navigate(), setText(), state(), and text().
 {
     if (!atViewport())
         return QModelIndex();
     ModelIndexIterator it(itemView());
     it.next(child - 1);
     return it.current();
 }
childIndex() [2/2]
int QAccessibleItemView::childIndex (int rowIndex, int columnIndex) virtual
Implements QAccessibleTableInterface.
Definition at line 1174 of file complexwidgets.cpp.
 {
     return rowIndex * itemView()->model()->columnCount() + columnIndex;
 }
columnCount()
int QAccessibleItemView::columnCount () virtual
Implements QAccessibleTableInterface.
Definition at line 1214 of file complexwidgets.cpp.
Referenced by columnIndex(), and rowIndex().
 {
     return itemView()->model()->columnCount();
 }
columnDescription()
QString QAccessibleItemView::columnDescription (int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1180 of file complexwidgets.cpp.
 {
     return itemView()->model()->headerData(column, Qt::Horizontal).toString();
 }
columnHeader()
QAccessibleInterface * QAccessibleItemView::columnHeader () virtual
Implements QAccessibleTableInterface.
Definition at line 1192 of file complexwidgets.cpp.
 {
 #ifndef QT_NO_TREEVIEW
     if (QTreeView *tree = qobject_cast<QTreeView *>(itemView()))
         return QAccessible::queryAccessibleInterface(tree->header());
 #endif
 #ifndef QT_NO_TABLEVIEW
     if (QTableView *table = qobject_cast<QTableView *>(itemView()))
         return QAccessible::queryAccessibleInterface(table->horizontalHeader());
 #endif
     return 0;
 }
columnIndex()
int QAccessibleItemView::columnIndex (int childIndex) virtual
Implements QAccessibleTableInterface.
Definition at line 1205 of file complexwidgets.cpp.
Referenced by cellAtIndex(), and childIndex().
 {
     int columnCount = itemView()->model()->columnCount();
     if (!columnCount)
         return 0;
     return childIndex % columnCount;
 }
columnSpan()
int QAccessibleItemView::columnSpan (int row, int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1186 of file complexwidgets.cpp.
Referenced by cellAtIndex().
 {
     return 1;
 }
entryFromIndex()
int QAccessibleItemView::entryFromIndex (const QModelIndex & index) const
Definition at line 924 of file complexwidgets.cpp.
Referenced by indexOfChild().
 {
     int entry = -1;
     if (false) {
 #ifndef QT_NO_TREEVIEW
     } else if (QTreeView *tree = qobject_cast<QTreeView*>(itemView())) {
         entry = tree->visualIndex(index) + 1;
 #endif
 #ifndef QT_NO_LISTVIEW
     } else if (QListView *list = qobject_cast<QListView*>(itemView())) {
         entry = list->visualIndex(index) + 1;
 #endif
 #ifndef QT_NO_TABLEVIEW
     } else if (QTableView *table = qobject_cast<QTableView*>(itemView())) {
         entry = table->visualIndex(index) + 1;
 #endif
     }
     return entry;
 }
expectedRoleOfChildren()
QAccessible::Role QAccessibleItemView::expectedRoleOfChildren () const private
horizontalHeader()
QHeaderView * QAccessibleItemView::horizontalHeader () const
Definition at line 814 of file complexwidgets.cpp.
Referenced by childCount(), indexOfChild(), navigate(), rect(), and state().
 {
     QHeaderView *header = 0;
     if (false) {
 #ifndef QT_NO_TABLEVIEW
     } else if (const QTableView *tv = qobject_cast<const QTableView*>(itemView())) {
         header = tv->horizontalHeader();
 #endif
 #ifndef QT_NO_TREEVIEW
     } else if (const QTreeView *tv = qobject_cast<const QTreeView*>(itemView())) {
         header = tv->header();
 #endif
     }
     return header;
 }
index()
QModelIndex QAccessibleItemView::index (int row, int column) const protected
Definition at line 1156 of file complexwidgets.cpp.
Referenced by accessibleAt(), isSelected(), navigate(), selectColumn(), selectRow(), unselectColumn(), and unselectRow().
 {
     return itemView()->model()->index(row, column);
 }
indexOfChild()
int QAccessibleItemView::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 888 of file complexwidgets.cpp.
 {
     if (atViewport()) {
         if (!iface || !isValidChildRole(iface->role(0)))
             return -1;
         int entry = -1;
         // ### This will fail if a row is hidden.
         const QAccessibleItemRow *ifRow = static_cast<const QAccessibleItemRow *>(iface);
         if (ifRow->horizontalHeader())
             return 1;
         QModelIndex idx = ifRow->row;
         if (!idx.isValid())
             return -1;
         entry = entryFromIndex(idx);
         if (horizontalHeader())
             ++entry;
         return entry;
     } else {
         return QAccessibleAbstractScrollArea::indexOfChild(iface);
     }
 }
isColumnSelected()
bool QAccessibleItemView::isColumnSelected (int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1295 of file complexwidgets.cpp.
 {
     return itemView()->selectionModel()->isColumnSelected(column, QModelIndex());
 }
isRowSelected()
bool QAccessibleItemView::isRowSelected (int row) virtual
Implements QAccessibleTableInterface.
Definition at line 1300 of file complexwidgets.cpp.
 {
     return itemView()->selectionModel()->isRowSelected(row, QModelIndex());
 }
isSelected()
bool QAccessibleItemView::isSelected (int row, int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1305 of file complexwidgets.cpp.
Referenced by cellAtIndex().
 {
     return itemView()->selectionModel()->isSelected(index(row, column));
 }
isValid()
bool QAccessibleItemView::isValid () const virtual
Returns true if all the data necessary to use this interface implementation is valid (e.
g. all pointers are non-null); otherwise returns false.
See also
object()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 1114 of file complexwidgets.cpp.
 {
     if (atViewport())
         return QAccessibleWidgetEx::isValid();
     else
         return QAccessibleAbstractScrollArea::isValid();
 }
isValidChildRole()
bool QAccessibleItemView::isValidChildRole (QAccessible::Role role) const
Definition at line 843 of file complexwidgets.cpp.
Referenced by indexOfChild().
 {
     if (atViewport()) {
         if (false) {
 #ifndef QT_NO_TREEVIEW
         } else if (qobject_cast<const QTreeView*>(itemView())) {
             return (role == TreeItem || role == Row);
 #endif
 #ifndef QT_NO_LISTVIEW
         } else if (qobject_cast<const QListView*>(itemView())) {
             return (role == ListItem);
 #endif
         }
         // TableView
         return role == Row;
     } else {
         if (false) {
 #ifndef QT_NO_TREEVIEW
         } else if (qobject_cast<const QTreeView*>(itemView())) {
             return (role == Tree);
 #endif
 #ifndef QT_NO_LISTVIEW
         } else if (qobject_cast<const QListView*>(itemView())) {
             return (role == List);
 #endif
         }
         // TableView
         return (role == Table);
     }
 }
itemView()
QAbstractItemView * QAccessibleItemView::itemView () const protected
Definition at line 883 of file complexwidgets.cpp.
Referenced by accessibleAt(), childCount(), childIndex(), columnCount(), columnDescription(), columnHeader(), columnIndex(), entryFromIndex(), horizontalHeader(), index(), isColumnSelected(), isRowSelected(), isSelected(), isValidChildRole(), navigate(), rect(), role(), rowCount(), rowDescription(), rowHeader(), rowIndex(), selectColumn(), selectedColumnCount(), selectedColumns(), selectedRowCount(), selectedRows(), selectRow(), setText(), state(), text(), unselectColumn(), unselectRow(), and verticalHeader().
 {
     return qobject_cast<QAbstractItemView *>(QAccessibleAbstractScrollArea::object());
 }
navigate()
int QAccessibleItemView::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 1122 of file complexwidgets.cpp.
Referenced by QAccessibleItemRow::navigate(), and rect().
 {
     if (atViewport()) {
         if (relation == Ancestor && index == 1) {
             *iface = new QAccessibleItemView(itemView());
             return 0;
         } else if (relation == Child && index >= 1) {
             if (horizontalHeader()) {
                 if (index == 1) {
                     *iface = new QAccessibleItemRow(itemView(), QModelIndex(), true);
                     return 0;
                 }
                 --index;
             }
             //###JAS hidden rows..
             QModelIndex idx = childIndex(index);
             if (idx.isValid()) {
                 *iface = new QAccessibleItemRow(itemView(), idx);
                 return 0;
             }
         } else if (relation == Sibling && index >= 1) {
             QAccessibleInterface *parent = new QAccessibleItemView(itemView());
             return parent->navigate(Child, index, iface);
         }
         *iface = 0;
         return -1;
     } else {
         return QAccessibleAbstractScrollArea::navigate(relation, index, iface);
     }
 }
object()
QObject * QAccessibleItemView::object () const virtual
Returns a pointer to the QObject this interface implementation provides information for.
See also
isValid()
Reimplemented from QAccessibleObjectEx.
Definition at line 874 of file complexwidgets.cpp.
 {
     QObject *view = QAccessibleAbstractScrollArea::object();
     Q_ASSERT(qobject_cast<const QAbstractItemView *>(view));
     if (atViewport())
         view = qobject_cast<const QAbstractItemView *>(view)->viewport();
     return view;
 }
rect()
QRect QAccessibleItemView::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 999 of file complexwidgets.cpp.
Referenced by childAt().
 {
     if (atViewport()) {
         QRect r;
         if (!child) {
             // Make sure that the rect *include* the vertical and horizontal headers, while
             // not including the potential vertical and horizontal scrollbars.
             QAbstractItemView *w = itemView();
             int vscrollWidth = 0;
             const QScrollBar *sb = w->verticalScrollBar();
             if (sb && sb->isVisible())
                 vscrollWidth = sb->width();
             int hscrollHeight = 0;
             sb = w->horizontalScrollBar();
             if (sb && sb->isVisible())
                 hscrollHeight = sb->height();
             QPoint globalPos = w->mapToGlobal(QPoint(0,0));
             r = w->rect().translated(globalPos);
             if (w->isRightToLeft()) {
                 r.adjust(vscrollWidth, 0, 0, -hscrollHeight);
             } else {
                 r.adjust(0, 0, -vscrollWidth, -hscrollHeight);
             }
         } else {
             QAccessibleInterface *iface = 0;
             if (navigate(Child, child, &iface) == 0) {
                 r = iface->rect(0);
                 delete iface;
             }
         }
         return r;
     } else {
         QRect r = QAccessibleAbstractScrollArea::rect(child);
         if (child == 1) {
             // include the potential vertical and horizontal headers
             const QHeaderView *header = verticalHeader();
             int headerWidth = (header && header->isVisible()) ? header->width() : 0;
             header = horizontalHeader();
             int headerHeight= (header && header->isVisible()) ? header->height() : 0;
             if (itemView()->isRightToLeft()) {
                 r.adjust(0, -headerHeight, headerWidth, 0);
             } else {
                 r.adjust(-headerWidth, -headerHeight, 0, 0);
             }
         }
         return r;
     }
 }
role()
QAccessible::Role QAccessibleItemView::role (int child) const virtual
Returns the role of the object, or of the object's child if child is not 0.
The role of an object is usually static.
All accessible objects have a role.
See also
text(), state()
Reimplemented from QAccessibleWidgetEx.
Definition at line 1066 of file complexwidgets.cpp.
 {
     if ((!atViewport() && child) || (atViewport() && child == 0)) {
         QAbstractItemView *view = itemView();
 #ifndef QT_NO_TABLEVIEW
         if (qobject_cast<QTableView *>(view))
             return Table;
 #endif
 #ifndef QT_NO_LISTVIEW
         if (qobject_cast<QListView *>(view))
             return List;
 #endif
         return Tree;
     }
     if (atViewport()) {
         if (child)
             return Row;
     }
     return QAccessibleAbstractScrollArea::role(child);
 }
rowCount()
int QAccessibleItemView::rowCount () virtual
Implements QAccessibleTableInterface.
Definition at line 1219 of file complexwidgets.cpp.
 {
     return itemView()->model()->rowCount();
 }
rowDescription()
QString QAccessibleItemView::rowDescription (int row) virtual
Implements QAccessibleTableInterface.
Definition at line 1234 of file complexwidgets.cpp.
 {
     return itemView()->model()->headerData(row, Qt::Vertical).toString();
 }
rowHeader()
QAccessibleInterface * QAccessibleItemView::rowHeader () virtual
Implements QAccessibleTableInterface.
Definition at line 1245 of file complexwidgets.cpp.
 {
 #ifndef QT_NO_TABLEVIEW
     if (QTableView *table = qobject_cast<QTableView *>(itemView()))
         return QAccessible::queryAccessibleInterface(table->verticalHeader());
 #endif
     return 0;
 }
rowIndex()
int QAccessibleItemView::rowIndex (int childIndex) virtual
Implements QAccessibleTableInterface.
Definition at line 1254 of file complexwidgets.cpp.
Referenced by cellAtIndex().
 {
     int columnCount = itemView()->model()->columnCount();
     if (!columnCount)
         return 0;
     return int(childIndex / columnCount);
 }
rowSpan()
int QAccessibleItemView::rowSpan (int row, int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1240 of file complexwidgets.cpp.
Referenced by cellAtIndex().
 {
     return 1;
 }
selectColumn()
void QAccessibleItemView::selectColumn (int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1316 of file complexwidgets.cpp.
 {
     QItemSelectionModel *s = itemView()->selectionModel();
     s->select(index(0, column), QItemSelectionModel::Select | QItemSelectionModel::Columns);
 }
selectedColumnCount()
int QAccessibleItemView::selectedColumnCount () virtual
Implements QAccessibleTableInterface.
Definition at line 1224 of file complexwidgets.cpp.
 {
     return itemView()->selectionModel()->selectedColumns().count();
 }
selectedColumns()
int QAccessibleItemView::selectedColumns (int maxColumns, QList< int > * columns) virtual
Implements QAccessibleTableInterface.
Definition at line 1276 of file complexwidgets.cpp.
 {
     Q_ASSERT(columns);
     const QModelIndexList selColumns = itemView()->selectionModel()->selectedColumns();
     int maxCount = qMin(selColumns.count(), maxColumns);
     for (int i = 0; i < maxCount; ++i)
         columns->append(selColumns.at(i).row());
     return maxCount;
 }
selectedRowCount()
int QAccessibleItemView::selectedRowCount () virtual
Implements QAccessibleTableInterface.
Definition at line 1229 of file complexwidgets.cpp.
 {
     return itemView()->selectionModel()->selectedRows().count();
 }
selectedRows()
int QAccessibleItemView::selectedRows (int maxRows, QList< int > * rows) virtual
Implements QAccessibleTableInterface.
Definition at line 1263 of file complexwidgets.cpp.
 {
     Q_ASSERT(rows);
     const QModelIndexList selRows = itemView()->selectionModel()->selectedRows();
     int maxCount = qMin(selRows.count(), maxRows);
     for (int i = 0; i < maxCount; ++i)
         rows->append(selRows.at(i).row());
     return maxCount;
 }
selectRow()
void QAccessibleItemView::selectRow (int row) virtual
Implements QAccessibleTableInterface.
Definition at line 1310 of file complexwidgets.cpp.
 {
     QItemSelectionModel *s = itemView()->selectionModel();
     s->select(index(row, 0), QItemSelectionModel::Select | QItemSelectionModel::Rows);
 }
setText()
void QAccessibleItemView::setText (Text t, int child, const QString & text) virtual
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Note that the text properties of most objects are read-only.
See also
text()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 984 of file complexwidgets.cpp.
 {
     if (atViewport()) {
         if (!child) {
             QAccessibleAbstractScrollArea::setText(t, child, text);
             return;
         }
         QAccessibleItemRow item(itemView(), childIndex(child));
         item.setText(t, 1, text);
     } else {
         QAccessibleAbstractScrollArea::setText(t, child, text);
     }
 }
state()
QAccessible::State QAccessibleItemView::state (int child) const virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 1088 of file complexwidgets.cpp.
 {
     State st = Normal;
     if (itemView() == 0)
         return State(Unavailable);
     bool queryViewPort = (atViewport() && child == 0) || (!atViewport() && child == 1);
     if (queryViewPort) {
         if (itemView()->selectionMode() != QAbstractItemView::NoSelection) {
             st |= Selectable;
             st |= Focusable;
         }
     } else if (atViewport()) {    // children of viewport
         if (horizontalHeader())
             --child;
         if (child) {
             QAccessibleItemRow item(itemView(), childIndex(child));
             st |= item.state(0);
         }
     } else if (!atViewport() && child != 1) {
         st = QAccessibleAbstractScrollArea::state(child);
     }
     return st;
 }
summary()
QAccessibleInterface * QAccessibleItemView::summary () virtual
Implements QAccessibleTableInterface.
Definition at line 1290 of file complexwidgets.cpp.
 {
     return 0;
 }
text()
QString QAccessibleItemView::text (Text t, int child) const virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Reimplemented from QAccessibleAbstractScrollArea.
Definition at line 967 of file complexwidgets.cpp.
 {
     if (atViewport()) {
         if (!child)
             return QAccessibleAbstractScrollArea::text(t, child);
         QAccessibleItemRow item(itemView(), childIndex(child));
         if (item.isValid()) {
             return item.text(t, 1);
         } else {
             return QString();
         }
     } else {
         return QAccessibleAbstractScrollArea::text(t, child);
     }
 }
unselectColumn()
void QAccessibleItemView::unselectColumn (int column) virtual
Implements QAccessibleTableInterface.
Definition at line 1328 of file complexwidgets.cpp.
 {
     QItemSelectionModel *s = itemView()->selectionModel();
     s->select(index(0, column), QItemSelectionModel::Deselect | QItemSelectionModel::Columns);
 }
unselectRow()
void QAccessibleItemView::unselectRow (int row) virtual
Implements QAccessibleTableInterface.
Definition at line 1322 of file complexwidgets.cpp.
 {
     QItemSelectionModel *s = itemView()->selectionModel();
     s->select(index(row, 0), QItemSelectionModel::Deselect | QItemSelectionModel::Rows);
 }
verticalHeader()
QHeaderView * QAccessibleItemView::verticalHeader () const
Definition at line 830 of file complexwidgets.cpp.
Referenced by rect().
 {
     QHeaderView *header = 0;
     if (false) {
 #ifndef QT_NO_TABLEVIEW
     } else if (const QTableView *tv = qobject_cast<const QTableView*>(itemView())) {
         header = tv->verticalHeader();
 #endif
     }
     return header;
 }
Properties
atVP
bool QAccessibleItemView::atVP private
Definition at line 226 of file complexwidgets.h.
Referenced by QAccessibleItemView().
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/complexwidgets.h
/src/plugins/accessible/widgets/complexwidgets.cpp