Qt 4.8: QComboBox Class Reference
QComboBox Class Reference
The QComboBox widget is a combined button and popup list.
#include <qcombobox.h>
Public Types
enum InsertPolicy {
NoInsert, InsertAtTop, InsertAtCurrent, InsertAtBottom,
InsertAfterCurrent, InsertBeforeCurrent, InsertAlphabetically
}
This enum specifies what the QComboBox should do when a new string is entered by the user.
enum SizeAdjustPolicy { AdjustToContents, AdjustToContentsOnFirstShow, AdjustToMinimumContentsLength, AdjustToMinimumContentsLengthWithIcon }
This enum specifies how the size hint of the QComboBox should adjust when new content is added or content changes.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void clear ()
Clears the combobox, removing all items.
void clearEditText ()
Clears the contents of the line edit used for editing in the combobox.
void setCurrentIndex (int index)
void setEditText (const QString &text)
Sets the text in the combobox's text edit.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activated (int index)
This signal is sent when the user chooses an item in the combobox.
void activated (const QString &)
This signal is sent when the user chooses an item in the combobox.
void currentIndexChanged (int index)
This signal is sent whenever the currentIndex in the combobox changes either through user interaction or programmatically.
void currentIndexChanged (const QString &)
This signal is sent whenever the currentIndex in the combobox changes either through user interaction or programmatically.
void editTextChanged (const QString &)
This signal is emitted when the text in the combobox's line edit widget is changed.
void highlighted (int index)
This signal is sent when an item in the combobox popup list is highlighted by the user.
void highlighted (const QString &)
This signal is sent when an item in the combobox popup list is highlighted by the user.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addItem (const QString &text, const QVariant &userData=QVariant())
Adds an item to the combobox with the given text, and containing the specified userData (stored in the Qt::UserRole).
void addItem (const QIcon &icon, const QString &text, const QVariant &userData=QVariant())
Adds an item to the combobox with the given icon and text, and containing the specified userData (stored in the Qt::UserRole).
void addItems (const QStringList &texts)
Adds each of the strings in the given texts to the combobox.
bool autoCompletion () const
Qt::CaseSensitivity autoCompletionCaseSensitivity () const
QCompleter * completer () const
Returns the completer that is used to auto complete text input for the combobox.
int count () const
int currentIndex () const
QString currentText () const
bool duplicatesEnabled () const
bool event (QEvent *event)
Reimplemented Function
int findData (const QVariant &data, int role=Qt::UserRole, Qt::MatchFlags flags=static_cast< Qt::MatchFlags >(Qt::MatchExactly|Qt::MatchCaseSensitive)) const
Returns the index of the item containing the given data for the given role; otherwise returns -1.
int findText (const QString &text, Qt::MatchFlags flags=static_cast< Qt::MatchFlags >(Qt::MatchExactly|Qt::MatchCaseSensitive)) const
Returns the index of the item containing the given text; otherwise returns -1.
bool hasFrame () const
virtual void hidePopup ()
Hides the list of items in the combobox if it is currently visible and resets the internal state, so that if the custom pop-up was shown inside the reimplemented showPopup(), then you also need to reimplement the hidePopup() function to hide your custom pop-up and call the base class implementation to reset the internal state whenever your custom pop-up widget is hidden.
QSize iconSize () const
void insertItem (int index, const QString &text, const QVariant &userData=QVariant())
Inserts the text and userData (stored in the Qt::UserRole) into the combobox at the given index.
void insertItem (int index, const QIcon &icon, const QString &text, const QVariant &userData=QVariant())
Inserts the icon, text and userData (stored in the Qt::UserRole) into the combobox at the given index.
void insertItems (int index, const QStringList &texts)
Inserts the strings from the list into the combobox as separate items, starting at the index specified.
InsertPolicy insertPolicy () const
void insertSeparator (int index)
Inserts a separator item into the combobox at the given index.
bool isEditable () const
QVariant itemData (int index, int role=Qt::UserRole) const
Returns the data for the given role in the given index in the combobox, or QVariant::Invalid if there is no data for this role.
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by the popup list view.
QIcon itemIcon (int index) const
Returns the icon for the given index in the combobox.
QString itemText (int index) const
Returns the text for the given index in the combobox.
QLineEdit * lineEdit () const
Returns the line edit used to edit items in the combobox, or 0 if there is no line edit.
int maxCount () const
int maxVisibleItems () const
int minimumContentsLength () const
QSize minimumSizeHint () const
Reimplemented Function
QAbstractItemModel * model () const
Returns the model used by the combobox.
int modelColumn () const
QComboBox (QWidget *parent=0)
Constructs a combobox with the given parent, using the default model QStandardItemModel.
void removeItem (int index)
Removes the item at the given index from the combobox.
QModelIndex rootModelIndex () const
Returns the root model item index for the items in the combobox.
void setAutoCompletion (bool enable)
Use setCompleter() instead.
void setAutoCompletionCaseSensitivity (Qt::CaseSensitivity sensitivity)
Use setCompleter() and QCompleter::setCaseSensitivity() instead.
void setCompleter (QCompleter *c)
void setDuplicatesEnabled (bool enable)
void setEditable (bool editable)
void setFrame (bool)
void setIconSize (const QSize &size)
void setInsertPolicy (InsertPolicy policy)
void setItemData (int index, const QVariant &value, int role=Qt::UserRole)
Sets the data role for the item on the given index in the combobox to the specified value.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for the popup list view.
void setItemIcon (int index, const QIcon &icon)
Sets the icon for the item on the given index in the combobox.
void setItemText (int index, const QString &text)
Sets the text for the item on the given index in the combobox.
void setLineEdit (QLineEdit *edit)
Sets the line edit to use instead of the current line edit widget.
void setMaxCount (int max)
void setMaxVisibleItems (int maxItems)
void setMinimumContentsLength (int characters)
void setModel (QAbstractItemModel *model)
Sets the model to be model.
void setModelColumn (int visibleColumn)
void setRootModelIndex (const QModelIndex &index)
Sets the root model item index for the items in the combobox.
void setSizeAdjustPolicy (SizeAdjustPolicy policy)
void setValidator (const QValidator *v)
Sets the validator to use instead of the current validator.
void setView (QAbstractItemView *itemView)
Sets the view to be used in the combobox popup to the given itemView.
virtual void showPopup ()
Displays the list of items in the combobox.
SizeAdjustPolicy sizeAdjustPolicy () const
QSize sizeHint () const
This implementation caches the size hint to avoid resizing when the contents change dynamically.
const QValidator * validator () const
Returns the validator that is used to constrain text input for the combobox.
QAbstractItemView * view () const
Returns the list view used for the combobox popup.
~QComboBox ()
Destroys the combobox.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *e)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *e)
Reimplemented Function
void focusInEvent (QFocusEvent *e)
Reimplemented Function
void focusOutEvent (QFocusEvent *e)
Reimplemented Function
void hideEvent (QHideEvent *e)
Reimplemented Function
void initStyleOption (QStyleOptionComboBox *option) const
Initialize option with the values from this QComboBox.
void inputMethodEvent (QInputMethodEvent *)
Reimplemented Function
QVariant inputMethodQuery (Qt::InputMethodQuery) const
Reimplemented Function
void keyPressEvent (QKeyEvent *e)
Reimplemented Function
void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
void mousePressEvent (QMouseEvent *e)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *e)
Reimplemented Function
QComboBox (QComboBoxPrivate &, QWidget *)
void resizeEvent (QResizeEvent *e)
Reimplemented Function
void showEvent (QShowEvent *e)
Reimplemented Function
void wheelEvent (QWheelEvent *e)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool autoCompletion
whether the combobox provides auto-completion for editable items
Qt::CaseSensitivity autoCompletionCaseSensitivity
whether string comparisons are case-sensitive or case-insensitive for auto-completion
int count
the number of items in the combobox
int currentIndex
the index of the current item in the combobox.
QString currentText
the current text
bool duplicatesEnabled
whether the user can enter duplicate items into the combobox
bool editable
whether the combo box can be edited by the user
bool frame
whether the combo box draws itself with a frame
QSize iconSize
the size of the icons shown in the combobox.
InsertPolicy insertPolicy
the policy used to determine where user-inserted items should appear in the combobox
int maxCount
the maximum number of items allowed in the combobox
int maxVisibleItems
the maximum allowed size on screen of the combo box, measured in items
int minimumContentsLength
the minimum number of characters that should fit into the combobox.
int modelColumn
the column in the model that is visible.
SizeAdjustPolicy sizeAdjustPolicy
the policy describing how the size of the combobox changes when the content changes
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QComboBox widget is a combined button and popup list.
A QComboBox provides a means of presenting a list of options to the user in a way that takes up the minimum amount of screen space.
A combobox is a selection widget that displays the current item, and can pop up a list of selectable items. A combobox may be editable, allowing the user to modify each item in the list.
Comboboxes can contain pixmaps as well as strings; the insertItem() and setItemText() functions are suitably overloaded. For editable comboboxes, the function clearEditText() is provided, to clear the displayed string without changing the combobox's contents.
There are two signals emitted if the current item of a combobox changes, currentIndexChanged() and activated(). currentIndexChanged() is always emitted regardless if the change was done programmatically or by user interaction, while activated() is only emitted when the change is caused by user interaction. The highlighted() signal is emitted when the user highlights an item in the combobox popup list. All three signals exist in two versions, one with a QString argument and one with an int argument. If the user selects or highlights a pixmap, only the int signals are emitted. Whenever the text of an editable combobox is changed the editTextChanged() signal is emitted.
When the user enters a new string in an editable combobox, the widget may or may not insert it, and it can insert it in several locations. The default policy is is AtBottom but you can change this using setInsertPolicy().
It is possible to constrain the input to an editable combobox using QValidator; see setValidator(). By default, any input is accepted.
A combobox can be populated using the insert functions, insertItem() and insertItems() for example. Items can be changed with setItemText(). An item can be removed with removeItem() and all items can be removed with clear(). The text of the current item is returned by currentText(), and the text of a numbered item is returned with text(). The current item can be set with setCurrentIndex(). The number of items in the combobox is returned by count(); the maximum number of items can be set with setMaxCount(). You can allow editing using setEditable(). For editable comboboxes you can set auto-completion using setCompleter() and whether or not the user can add duplicates is set with setDuplicatesEnabled().
QComboBox uses the Model/View Programming{model/view framework} for its popup list and to store its items. By default a QStandardItemModel stores the items and a QListView subclass displays the popuplist. You can access the model and view directly (with model() and view()), but QComboBox also provides functions to set and get item data (e.g., setItemData() and itemText()). You can also set a new model and view (with setModel() and setView()). For the text and icon in the combobox label, the data in the model that has the Qt::DisplayRole and Qt::DecorationRole is used. Note that you cannot alter the QAbstractItemView::SelectionMode of the view(), e.g., by using QAbstractItemView::setSelectionMode().
Comboboxes in the different built-in styles.
See also
QLineEdit, QSpinBox, QRadioButton, QButtonGroup, {fowler}{GUI Design Handbook: Combo Box, Drop-Down List Box}
Definition at line 62 of file qcombobox.h.
Enumerations
InsertPolicy
enum QComboBox::InsertPolicy
This enum specifies what the QComboBox should do when a new string is entered by the user.
NoInsert The string will not be inserted into the combobox.
InsertAtTop The string will be inserted as the first item in the combobox.
InsertAtCurrent The current item will be replaced by the string.
InsertAtBottom The string will be inserted after the last item in the combobox.
InsertAfterCurrent The string is inserted after the current item in the combobox.
InsertBeforeCurrent The string is inserted before the current item in the combobox.
InsertAlphabetically The string is inserted in the alphabetic order in the combobox.
NoInsertion
AtTop
AtCurrent
AtBottom
AfterCurrent
BeforeCurrent
Enumerator
NoInsert
InsertAtTop
InsertAtCurrent
InsertAtBottom
InsertAfterCurrent
InsertBeforeCurrent
InsertAlphabetically
Definition at line 119 of file qcombobox.h.
                       {
         NoInsert,
         InsertAtTop,
         InsertAtCurrent,
         InsertAtBottom,
         InsertAfterCurrent,
         InsertBeforeCurrent,
         InsertAlphabetically
 #if defined(QT3_SUPPORT) && !defined(Q_MOC_RUN)
         ,
         NoInsertion = NoInsert,
         AtTop = InsertAtTop,
         AtCurrent = InsertAtCurrent,
         AtBottom = InsertAtBottom,
         AfterCurrent = InsertAfterCurrent,
         BeforeCurrent = InsertBeforeCurrent
 #endif
     };
SizeAdjustPolicy
enum QComboBox::SizeAdjustPolicy
This enum specifies how the size hint of the QComboBox should adjust when new content is added or content changes.
AdjustToContents The combobox will always adjust to the contents
AdjustToContentsOnFirstShow The combobox will adjust to its contents the first time it is shown.
AdjustToMinimumContentsLength Use AdjustToContents or AdjustToContentsOnFirstShow instead.
AdjustToMinimumContentsLengthWithIcon The combobox will adjust to minimumContentsLength plus space for an icon. For performance reasons use this policy on large models.
Enumerator
AdjustToContents
AdjustToContentsOnFirstShow
AdjustToMinimumContentsLength
AdjustToMinimumContentsLengthWithIcon
Definition at line 144 of file qcombobox.h.
{
         AdjustToContents,
         AdjustToContentsOnFirstShow,
         AdjustToMinimumContentsLength, // ### Qt 5: remove
         AdjustToMinimumContentsLengthWithIcon
     };
Constructors and Destructors
QComboBox() [1/2]
QComboBox::QComboBox (QWidget * parent = 0) explicit
Constructs a combobox with the given parent, using the default model QStandardItemModel.
Definition at line 870 of file qcombobox.cpp.
Referenced by QComboBox().
     : QWidget(*new QComboBoxPrivate(), parent, 0)
 {
     Q_D(QComboBox);
     d->init();
 }
~QComboBox()
QComboBox::~QComboBox ()
Destroys the combobox.
Definition at line 1325 of file qcombobox.cpp.
 {
     // ### check delegateparent and delete delegate if us?
     Q_D(QComboBox);
     QT_TRY {
         disconnect(d->model, SIGNAL(destroyed()),
                 this, SLOT(_q_modelDestroyed()));
     } QT_CATCH(...) {
         ; // objects can't throw in destructor
     }
 }
QComboBox() [2/2]
QComboBox::QComboBox (QComboBoxPrivate & dd, QWidget * parent) protected
Warning
This function is not part of the public interface.
Definition at line 880 of file qcombobox.cpp.
     : QWidget(dd, parent, 0)
 {
     Q_D(QComboBox);
     d->init();
 }
Functions
activated [1/2]
void QComboBox::activated (int index) signal
This signal is sent when the user chooses an item in the combobox.
The item's index is passed. Note that this signal is sent even when the choice is not changed. If you need to know when the choice actually changes, use signal currentIndexChanged().
Referenced by setLineEdit().
activated [2/2]
void QComboBox::activated (const QString & text) signal
This signal is sent when the user chooses an item in the combobox.
The item's text is passed. Note that this signal is sent even when the choice is not changed. If you need to know when the choice actually changes, use signal currentIndexChanged().
addItem() [1/2]
void QComboBox::addItem (const QString & text, const QVariant & userData = QVariant()) inline
Adds an item to the combobox with the given text, and containing the specified userData (stored in the Qt::UserRole).
The item is appended to the list of existing items.
Definition at line 323 of file qcombobox.h.
Referenced by isc(), populatePaperSizes(), QBooleanComboBox::QBooleanComboBox(), QPPDOptionsEditor::setEditorData(), and QPrintDialogPrivate::setupOptions().
 { insertItem(count(), atext, auserData); }
addItem() [2/2]
void QComboBox::addItem (const QIcon & icon, const QString & text, const QVariant & userData = QVariant()) inline
Adds an item to the combobox with the given icon and text, and containing the specified userData (stored in the Qt::UserRole).
The item is appended to the list of existing items.
Definition at line 325 of file qcombobox.h.
 { insertItem(count(), aicon, atext, auserData); }
addItems()
void QComboBox::addItems (const QStringList & texts) inline
Adds each of the strings in the given texts to the combobox.
Each item is appended to the list of existing items in turn.
Definition at line 195 of file qcombobox.h.
         { insertItems(count(), texts); }
autoCompletion()
bool QComboBox::autoCompletion () const
Referenced by setMaxCount().
autoCompletionCaseSensitivity()
Qt::CaseSensitivity QComboBox::autoCompletionCaseSensitivity () const
Referenced by setAutoCompletion().
changeEvent()
void QComboBox::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2814 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     switch (e->type()) {
     case QEvent::StyleChange:
         d->updateDelegate();
 #ifdef Q_WS_MAC
     case QEvent::MacSizeChange:
 #endif
         d->sizeHint = QSize(); // invalidate size hint
         d->minimumSizeHint = QSize();
         d->updateLayoutDirection();
         if (d->lineEdit)
             d->updateLineEditGeometry();
         d->setLayoutItemMargins(QStyle::SE_ComboBoxLayoutItem);
 #ifdef Q_WS_S60
         if (d->container) {
             QStyleOptionComboBox opt;
             initStyleOption(&opt);
             if (style()->styleHint(QStyle::SH_ComboBox_Popup, &opt, this)) {
                 QRect screen = qt_TRect2QRect(static_cast<CEikAppUi*>(S60->appUi())->ClientRect());
                 QRect listRect(style()->subControlRect(QStyle::CC_ComboBox, &opt,
                     QStyle::SC_ComboBoxListBoxPopup, this));
                 listRect.setHeight(qMin(screen.height(), screen.width()));
                 if (screen.width() < screen.height()) {
                     // in portait, menu should be positioned above softkeys
                     listRect.moveBottom(screen.bottom());
                 } else {
                     TRect staConTopRect = TRect();
                     AknLayoutUtils::LayoutMetricsRect(AknLayoutUtils::EStaconTop, staConTopRect);
                     listRect.setWidth(listRect.height());
                     //by default popup is centered on screen in landscape
                     listRect.moveCenter(screen.center());
                     if (staConTopRect.IsEmpty() && AknLayoutUtils::CbaLocation() != AknLayoutUtils::EAknCbaLocationBottom) {
                         // landscape without stacon, menu should be at the right
                         (opt.direction == Qt::LeftToRight) ? listRect.setRight(screen.right()) :
                                                              listRect.setLeft(screen.left());
                     }
                 }
                 d->container->setGeometry(listRect);
             }
         }
 #endif
         // ### need to update scrollers etc. as well here
         break;
     case QEvent::EnabledChange:
         if (!isEnabled())
             hidePopup();
         break;
     case QEvent::PaletteChange: {
         d->updateViewContainerPaletteAndOpacity();
         break;
     }
     case QEvent::FontChange:
         d->sizeHint = QSize(); // invalidate size hint
         d->viewContainer()->setFont(font());
         if (d->lineEdit)
             d->updateLineEditGeometry();
         break;
     default:
         break;
     }
     QWidget::changeEvent(e);
 }
clear
void QComboBox::clear () slot
Clears the combobox, removing all items.
Note: If you have set an external model on the combobox this model will still be cleared when calling this function.
Definition at line 2742 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     d->model->removeRows(0, d->model->rowCount(d->root), d->root);
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::updateAccessibility(this, 0, QAccessible::NameChanged);
 #endif
 }
clearEditText
void QComboBox::clearEditText () slot
Clears the contents of the line edit used for editing in the combobox.
Definition at line 2763 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (d->lineEdit)
         d->lineEdit->clear();
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::updateAccessibility(this, 0, QAccessible::NameChanged);
 #endif
 }
completer()
QCompleter * QComboBox::completer () const
Returns the completer that is used to auto complete text input for the combobox.
Since
4.2
See also
editable
Definition at line 1924 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     return d->lineEdit ? d->lineEdit->completer() : 0;
 }
contextMenuEvent()
void QComboBox::contextMenuEvent (QContextMenuEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3204 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (d->lineEdit) {
         Qt::ContextMenuPolicy p = d->lineEdit->contextMenuPolicy();
         d->lineEdit->setContextMenuPolicy(Qt::DefaultContextMenu);
         d->lineEdit->event(e);
         d->lineEdit->setContextMenuPolicy(p);
     }
 }
count()
int QComboBox::count () const
Referenced by insertItem(), insertItems(), insertSeparator(), keyPressEvent(), removeItem(), setMaxCount(), setMaxVisibleItems(), setModel(), showPopup(), and wheelEvent().
currentIndex()
int QComboBox::currentIndex () const
Referenced by QComboBoxPrivate::_q_dataChanged(), QComboBoxPrivate::_q_editingFinished(), QComboBoxPrivate::_q_itemSelected(), QComboBoxPrivate::_q_returnPressed(), QComboBoxPrivate::_q_rowsInserted(), QComboBoxPrivate::_q_rowsRemoved(), QComboBoxPrivate::_q_updateIndexBeforeChange(), QComboBoxPrivate::keyboardSearchString(), keyPressEvent(), QComboBoxPrivate::setCurrentIndex(), setModelColumn(), setRootModelIndex(), QBooleanComboBox::setValue(), showPopup(), and wheelEvent().
currentIndexChanged [1/2]
void QComboBox::currentIndexChanged (int index) signal
This signal is sent whenever the currentIndex in the combobox changes either through user interaction or programmatically.
Since
4.1
The item's index is passed or -1 if the combobox becomes empty or the currentIndex was reset.
Referenced by QFontComboBox::QFontComboBox().
currentIndexChanged [2/2]
void QComboBox::currentIndexChanged (const QString & text) signal
This signal is sent whenever the currentIndex in the combobox changes either through user interaction or programmatically.
Since
4.1
The item's text is passed.
currentText()
QString QComboBox::currentText () const
Referenced by initStyleOption(), QComboBoxPrivate::setCurrentIndex(), and setLineEdit().
duplicatesEnabled()
bool QComboBox::duplicatesEnabled () const
Referenced by QComboBoxPrivate::_q_returnPressed(), and setAutoCompletionCaseSensitivity().
editTextChanged
void QComboBox::editTextChanged (const QString & text) signal
This signal is emitted when the text in the combobox's line edit widget is changed.
The new text is specified by text.
Referenced by setLineEdit().
event()
bool QComboBox::event (QEvent * event) virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QFontComboBox.
Definition at line 2940 of file qcombobox.cpp.
Referenced by QFontComboBox::event().
 {
     Q_D(QComboBox);
     switch(event->type()) {
     case QEvent::LayoutDirectionChange:
     case QEvent::ApplicationLayoutDirectionChange:
         d->updateLayoutDirection();
         d->updateLineEditGeometry();
         break;
     case QEvent::HoverEnter:
     case QEvent::HoverLeave:
     case QEvent::HoverMove:
     if (const QHoverEvent *he = static_cast<const QHoverEvent *>(event))
         d->updateHoverControl(he->pos());
         break;
     case QEvent::ShortcutOverride:
         if (d->lineEdit)
             return d->lineEdit->event(event);
         break;
 #ifdef QT_KEYPAD_NAVIGATION
     case QEvent::EnterEditFocus:
         if (!d->lineEdit)
             setEditFocus(false); // We never want edit focus if we are not editable
         else
             d->lineEdit->event(event);  //so cursor starts
         break;
     case QEvent::LeaveEditFocus:
         if (d->lineEdit)
             d->lineEdit->event(event);  //so cursor stops
         break;
 #endif
     default:
         break;
     }
     return QWidget::event(event);
 }
findData()
int QComboBox::findData (const QVariant & data, int role = Qt::UserRole, Qt::MatchFlags flags = static_cast<Qt::MatchFlags>(Qt::MatchExactly|Qt::MatchCaseSensitive)) const
Returns the index of the item containing the given data for the given role; otherwise returns -1.
The flags specify how the items in the combobox are searched.
Definition at line 1572 of file qcombobox.cpp.
Referenced by QPrintDialogPrivate::setPrinter().
 {
     Q_D(const QComboBox);
     QModelIndexList result;
     QModelIndex start = d->model->index(0, d->modelColumn, d->root);
     result = d->model->match(start, role, data, 1, flags);
     if (result.isEmpty())
         return -1;
     return result.first().row();
 }
findText()
int QComboBox::findText (const QString & text, Qt::MatchFlags flags = static_cast<Qt::MatchFlags>(Qt::MatchExactly|Qt::MatchCaseSensitive)) const inline
Returns the index of the item containing the given text; otherwise returns -1.
The flags specify how the items in the combobox are searched.
Definition at line 113 of file qcombobox.h.
Referenced by QInputDialogPrivate::setComboBoxText(), and QInputDialogPrivate::setListViewText().
         { return findData(text, Qt::DisplayRole, flags); }
focusInEvent()
void QComboBox::focusInEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2789 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     update();
     if (d->lineEdit) {
         d->lineEdit->event(e);
 #ifndef QT_NO_COMPLETER
         if (d->lineEdit->completer())
             d->lineEdit->completer()->setWidget(this);
 #endif
     }
 }
focusOutEvent()
void QComboBox::focusOutEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2805 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     update();
     if (d->lineEdit)
         d->lineEdit->event(e);
 }
hasFrame()
bool QComboBox::hasFrame () const
Definition at line 3458 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     return d->frame;
 }
hideEvent()
void QComboBox::hideEvent (QHideEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2932 of file qcombobox.cpp.
 {
     hidePopup();
 }
hidePopup()
void QComboBox::hidePopup () virtual
Hides the list of items in the combobox if it is currently visible and resets the internal state, so that if the custom pop-up was shown inside the reimplemented showPopup(), then you also need to reimplement the hidePopup() function to hide your custom pop-up and call the base class implementation to reset the internal state whenever your custom pop-up widget is hidden.
See also
showPopup()
Definition at line 2685 of file qcombobox.cpp.
Referenced by changeEvent(), QAccessibleComboBox::doAction(), QComboBoxPrivateContainer::eventFilter(), hideEvent(), QComboBoxPrivateContainer::mousePressEvent(), and QComboBoxPrivateContainer::mouseReleaseEvent().
 {
     Q_D(QComboBox);
     if (d->container && d->container->isVisible()) {
 #if !defined(QT_NO_EFFECTS)
         d->model->blockSignals(true);
         d->container->itemView()->blockSignals(true);
         d->container->blockSignals(true);
         // Flash selected/triggered item (if any).
         if (style()->styleHint(QStyle::SH_Menu_FlashTriggeredItem)) {
             QItemSelectionModel *selectionModel = view() ? view()->selectionModel() : 0;
             if (selectionModel && selectionModel->hasSelection()) {
                 QEventLoop eventLoop;
                 const QItemSelection selection = selectionModel->selection();
                 // Deselect item and wait 60 ms.
                 selectionModel->select(selection, QItemSelectionModel::Toggle);
                 QTimer::singleShot(60, &eventLoop, SLOT(quit()));
                 eventLoop.exec();
                 // Select item and wait 20 ms.
                 selectionModel->select(selection, QItemSelectionModel::Toggle);
                 QTimer::singleShot(20, &eventLoop, SLOT(quit()));
                 eventLoop.exec();
             }
         }
         // Fade out.
         bool needFade = style()->styleHint(QStyle::SH_Menu_FadeOutOnHide);
         if (needFade) {
 #if defined(Q_WS_MAC)
             macWindowFade(qt_mac_window_for(d->container));
 #endif // Q_WS_MAC
             // Other platform implementations welcome :-)
         }
         d->model->blockSignals(false);
         d->container->itemView()->blockSignals(false);
         d->container->blockSignals(false);
         if (!needFade)
 #endif // QT_NO_EFFECTS
             // Fade should implicitly hide as well ;-)
             d->container->hide();
     }
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled() && isEditable() && hasFocus())
         setEditFocus(true);
 #endif
     d->_q_resetButton();
 }
highlighted [1/2]
void QComboBox::highlighted (int index) signal
This signal is sent when an item in the combobox popup list is highlighted by the user.
The item's index is passed.
highlighted [2/2]
void QComboBox::highlighted (const QString & text) signal
This signal is sent when an item in the combobox popup list is highlighted by the user.
The item's text is passed.
iconSize()
QSize QComboBox::iconSize () const
Referenced by initStyleOption(), and setMinimumContentsLength().
initStyleOption()
void QComboBox::initStyleOption (QStyleOptionComboBox * option) const protected
Initialize option with the values from this QComboBox.
This method is useful for subclasses when they need a QStyleOptionComboBox, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 1141 of file qcombobox.cpp.
Referenced by changeEvent(), mousePressEvent(), paintEvent(), setEditable(), and showPopup().
 {
     if (!option)
         return;
     Q_D(const QComboBox);
     option->initFrom(this);
     option->editable = isEditable();
     option->frame = d->frame;
     if (hasFocus() && !option->editable)
         option->state |= QStyle::State_Selected;
     option->subControls = QStyle::SC_All;
     if (d->arrowState == QStyle::State_Sunken) {
         option->activeSubControls = QStyle::SC_ComboBoxArrow;
         option->state |= d->arrowState;
     } else {
         option->activeSubControls = d->hoverControl;
     }
     if (d->currentIndex.isValid()) {
         option->currentText = currentText();
         option->currentIcon = d->itemIcon(d->currentIndex);
     }
     option->iconSize = iconSize();
     if (d->container && d->container->isVisible())
         option->state |= QStyle::State_On;
 }
inputMethodEvent()
void QComboBox::inputMethodEvent (QInputMethodEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3243 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (d->lineEdit) {
         d->lineEdit->event(e);
     } else {
         if (!e->commitString().isEmpty())
             d->keyboardSearchString(e->commitString());
         else
             e->ignore();
     }
 }
inputMethodQuery()
QVariant QComboBox::inputMethodQuery (Qt::InputMethodQuery query) const protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3259 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     if (d->lineEdit)
         return d->lineEdit->inputMethodQuery(query);
     return QWidget::inputMethodQuery(query);
 }
insertItem() [1/2]
void QComboBox::insertItem (int index, const QString & text, const QVariant & userData = QVariant()) inline
Inserts the text and userData (stored in the Qt::UserRole) into the combobox at the given index.
If the index is equal to or higher than the total number of items, the new item is appended to the list of existing items. If the index is zero or negative, the new item is prepended to the list of existing items.
See also
insertItems()
Definition at line 329 of file qcombobox.h.
Referenced by insertSeparator().
 { insertItem(aindex, QIcon(), atext, auserData); }
insertItem() [2/2]
void QComboBox::insertItem (int index, const QIcon & icon, const QString & text, const QVariant & userData = QVariant())
Inserts the icon, text and userData (stored in the Qt::UserRole) into the combobox at the given index.
If the index is equal to or higher than the total number of items, the new item is appended to the list of existing items. If the index is zero or negative, the new item is prepended to the list of existing items.
See also
insertItems()
Definition at line 2218 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     int itemCount = count();
     index = qBound(0, index, itemCount);
     if (index >= d->maxCount)
         return;
     // For the common case where we are using the built in QStandardItemModel
     // construct a QStandardItem, reducing the number of expensive signals from the model
     if (QStandardItemModel *m = qobject_cast<QStandardItemModel*>(d->model)) {
         QStandardItem *item = new QStandardItem(text);
         if (!icon.isNull()) item->setData(icon, Qt::DecorationRole);
         if (userData.isValid()) item->setData(userData, Qt::UserRole);
         m->insertRow(index, item);
         ++itemCount;
     } else {
         d->inserting = true;
         if (d->model->insertRows(index, 1, d->root)) {
             QModelIndex item = d->model->index(index, d->modelColumn, d->root);
             if (icon.isNull() && !userData.isValid()) {
                 d->model->setData(item, text, Qt::EditRole);
             } else {
                 QMap<int, QVariant> values;
                 if (!text.isNull()) values.insert(Qt::EditRole, text);
                 if (!icon.isNull()) values.insert(Qt::DecorationRole, icon);
                 if (userData.isValid()) values.insert(Qt::UserRole, userData);
                 if (!values.isEmpty()) d->model->setItemData(item, values);
             }
             d->inserting = false;
             d->_q_rowsInserted(d->root, index, index);
             ++itemCount;
         } else {
             d->inserting = false;
         }
     }
     if (itemCount > d->maxCount)
         d->model->removeRows(itemCount - 1, itemCount - d->maxCount, d->root);
 }
insertItems()
void QComboBox::insertItems (int index, const QStringList & list)
Inserts the strings from the list into the combobox as separate items, starting at the index specified.
If the index is equal to or higher than the total number of items, the new items are appended to the list of existing items. If the index is zero or negative, the new items are prepended to the list of existing items.
See also
insertItem()
Definition at line 2269 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (list.isEmpty())
         return;
     index = qBound(0, index, count());
     int insertCount = qMin(d->maxCount - index, list.count());
     if (insertCount <= 0)
         return;
     // For the common case where we are using the built in QStandardItemModel
     // construct a QStandardItem, reducing the number of expensive signals from the model
     if (QStandardItemModel *m = qobject_cast<QStandardItemModel*>(d->model)) {
         QList<QStandardItem *> items;
         QStandardItem *hiddenRoot = m->invisibleRootItem();
         for (int i = 0; i < insertCount; ++i)
             items.append(new QStandardItem(list.at(i)));
         hiddenRoot->insertRows(index, items);
     } else {
         d->inserting = true;
         if (d->model->insertRows(index, insertCount, d->root)) {
             QModelIndex item;
             for (int i = 0; i < insertCount; ++i) {
                 item = d->model->index(i+index, d->modelColumn, d->root);
                 d->model->setData(item, list.at(i), Qt::EditRole);
             }
             d->inserting = false;
             d->_q_rowsInserted(d->root, index, index + insertCount - 1);
         } else {
             d->inserting = false;
         }
     }
     int mc = count();
     if (mc > d->maxCount)
         d->model->removeRows(d->maxCount, mc - d->maxCount, d->root);
 }
insertPolicy()
InsertPolicy QComboBox::insertPolicy () const
Referenced by QComboBoxPrivate::_q_returnPressed(), and findData().
insertSeparator()
void QComboBox::insertSeparator (int index)
Inserts a separator item into the combobox at the given index.
Since
4.4
If the index is equal to or higher than the total number of items, the new item is appended to the list of existing items. If the index is zero or negative, the new item is prepended to the list of existing items.
See also
insertItem()
Definition at line 2320 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     int itemCount = count();
     index = qBound(0, index, itemCount);
     if (index >= d->maxCount)
         return;
     insertItem(index, QIcon(), QString());
     QComboBoxDelegate::setSeparator(d->model, d->model->index(index, 0, d->root));
 }
isEditable()
bool QComboBox::isEditable () const
Definition at line 1723 of file qcombobox.cpp.
Referenced by QInputDialogPrivate::chooseRightTextInputWidget(), QComboBoxPrivateContainer::comboStyleOption(), hidePopup(), initStyleOption(), QComboBoxPrivateContainer::mousePressEvent(), mousePressEvent(), QComboBoxListView::paintEvent(), setAutoCompletion(), QInputDialogPrivate::setComboBoxText(), and setEditable().
 {
     Q_D(const QComboBox);
     return d->lineEdit != 0;
 }
itemData()
QVariant QComboBox::itemData (int index, int role = Qt::UserRole) const
Returns the data for the given role in the given index in the combobox, or QVariant::Invalid if there is no data for this role.
Definition at line 2182 of file qcombobox.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), and QPrintDialogPrivate::_q_printRangeSelected().
 {
     Q_D(const QComboBox);
     QModelIndex mi = d->model->index(index, d->modelColumn, d->root);
     return d->model->data(mi, role);
 }
itemDelegate()
QAbstractItemDelegate * QComboBox::itemDelegate () const
Returns the item delegate used by the popup list view.
See also
setItemDelegate()
Definition at line 1937 of file qcombobox.cpp.
 {
     return view()->itemDelegate();
 }
itemIcon()
QIcon QComboBox::itemIcon (int index) const
Returns the icon for the given index in the combobox.
Definition at line 2171 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     QModelIndex mi = d->model->index(index, d->modelColumn, d->root);
     return d->itemIcon(mi);
 }
itemText()
QString QComboBox::itemText (int index) const
Returns the text for the given index in the combobox.
Definition at line 2161 of file qcombobox.cpp.
Referenced by QComboBoxPrivate::_q_editingFinished(), QComboBoxPrivate::_q_emitCurrentIndexChanged(), QComboBoxPrivate::_q_emitHighlighted(), QComboBoxPrivate::emitActivated(), and QInputDialogPrivate::listViewText().
 {
     Q_D(const QComboBox);
     QModelIndex mi = d->model->index(index, d->modelColumn, d->root);
     return d->itemText(mi);
 }
keyPressEvent()
void QComboBox::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3027 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
 #ifndef QT_NO_COMPLETER
     if (d->lineEdit
         && d->lineEdit->completer()
         && d->lineEdit->completer()->popup()
         && d->lineEdit->completer()->popup()->isVisible()) {
         // provide same autocompletion support as line edit
         d->lineEdit->event(e);
         return;
     }
 #endif
     enum Move { NoMove=0 , MoveUp , MoveDown , MoveFirst , MoveLast};
     Move move = NoMove;
     int newIndex = currentIndex();
     switch (e->key()) {
     case Qt::Key_Up:
         if (e->modifiers() & Qt::ControlModifier)
             break; // pass to line edit for auto completion
     case Qt::Key_PageUp:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled())
             e->ignore();
         else
 #endif
         move = MoveUp;
         break;
     case Qt::Key_Down:
         if (e->modifiers() & Qt::AltModifier) {
             showPopup();
             return;
         } else if (e->modifiers() & Qt::ControlModifier)
             break; // pass to line edit for auto completion
         // fall through
     case Qt::Key_PageDown:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled())
             e->ignore();
         else
 #endif
         move = MoveDown;
         break;
     case Qt::Key_Home:
         if (!d->lineEdit)
             move = MoveFirst;
         break;
     case Qt::Key_End:
         if (!d->lineEdit)
             move = MoveLast;
         break;
     case Qt::Key_F4:
         if (!e->modifiers()) {
             showPopup();
             return;
         }
         break;
     case Qt::Key_Space:
         if (!d->lineEdit) {
             showPopup();
             return;
         }
     case Qt::Key_Enter:
     case Qt::Key_Return:
     case Qt::Key_Escape:
         if (!d->lineEdit)
             e->ignore();
         break;
 #ifdef QT_KEYPAD_NAVIGATION
     case Qt::Key_Select:
         if (QApplication::keypadNavigationEnabled()
                 && (!hasEditFocus() || !d->lineEdit)) {
             showPopup();
             return;
         }
         break;
     case Qt::Key_Left:
     case Qt::Key_Right:
         if (QApplication::keypadNavigationEnabled() && !hasEditFocus())
             e->ignore();
         break;
     case Qt::Key_Back:
         if (QApplication::keypadNavigationEnabled()) {
             if (!hasEditFocus() || !d->lineEdit)
                 e->ignore();
         } else {
             e->ignore(); // let the surounding dialog have it
         }
         break;
 #endif
     default:
         if (!d->lineEdit) {
             if (!e->text().isEmpty())
                 d->keyboardSearchString(e->text());
             else
                 e->ignore();
         }
     }
     if (move != NoMove) {
         e->accept();
         switch (move) {
         case MoveFirst:
             newIndex = -1;
         case MoveDown:
             newIndex++;
             while ((newIndex < count()) && !(d->model->flags(d->model->index(newIndex,d->modelColumn,d->root)) & Qt::ItemIsEnabled))
                 newIndex++;
             break;
         case MoveLast:
             newIndex = count();
         case MoveUp:
             newIndex--;
             while ((newIndex >= 0) && !(d->model->flags(d->model->index(newIndex,d->modelColumn,d->root)) & Qt::ItemIsEnabled))
                 newIndex--;
             break;
         default:
             e->ignore();
             break;
         }
         if (newIndex >= 0 && newIndex < count() && newIndex != currentIndex()) {
             setCurrentIndex(newIndex);
             d->emitActivated(d->currentIndex);
         }
     } else if (d->lineEdit) {
         d->lineEdit->event(e);
     }
 }
keyReleaseEvent()
void QComboBox::keyReleaseEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3164 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (d->lineEdit)
         d->lineEdit->event(e);
 }
lineEdit()
QLineEdit * QComboBox::lineEdit () const
Returns the line edit used to edit items in the combobox, or 0 if there is no line edit.
Only editable combo boxes have a line edit.
Definition at line 1858 of file qcombobox.cpp.
Referenced by QComboBoxPrivate::_q_dataChanged(), QComboBoxPrivate::_q_editingFinished(), QComboBoxPrivate::_q_itemSelected(), QComboBoxPrivate::_q_returnPressed(), QComboBoxPrivate::_q_rowsRemoved(), QComboBoxPrivate::matchFlags(), QAccessibleComboBox::rect(), QComboBoxPrivate::setCurrentIndex(), QAccessibleComboBox::text(), QComboBoxPrivate::updateLineEditGeometry(), and QComboBoxPrivate::updateViewContainerPaletteAndOpacity().
 {
     Q_D(const QComboBox);
     return d->lineEdit;
 }
maxCount()
int QComboBox::maxCount () const
Referenced by QComboBoxPrivate::_q_returnPressed(), and setMaxCount().
maxVisibleItems()
int QComboBox::maxVisibleItems () const
Referenced by ~QComboBox().
minimumContentsLength()
int QComboBox::minimumContentsLength () const
Referenced by setSizeAdjustPolicy().
minimumSizeHint()
QSize QComboBox::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2416 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     return d->recomputeSizeHint(d->minimumSizeHint);
 }
model()
QAbstractItemModel * QComboBox::model () const
Returns the model used by the combobox.
Definition at line 1968 of file qcombobox.cpp.
Referenced by QInputDialogPrivate::_q_currentRowChanged(), QInputDialogPrivate::ensureListView(), QComboBoxPrivate::itemIcon(), QComboBoxPrivate::itemText(), QComboBoxPrivate::setCurrentIndex(), QInputDialogPrivate::setListViewText(), setModel(), and QComboBoxPrivate::viewContainer().
 {
     Q_D(const QComboBox);
     if (d->model == QAbstractItemModelPrivate::staticEmptyModel()) {
         QComboBox *that = const_cast<QComboBox*>(this);
         that->setModel(new QStandardItemModel(0, 1, that));
     }
     return d->model;
 }
modelColumn()
int QComboBox::modelColumn () const
Referenced by QComboBoxPrivate::setCurrentIndex(), and setFrame().
mousePressEvent()
void QComboBox::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2980 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     QStyleOptionComboBox opt;
     initStyleOption(&opt);
     QStyle::SubControl sc = style()->hitTestComplexControl(QStyle::CC_ComboBox, &opt, e->pos(),
                                                            this);
     if (e->button() == Qt::LeftButton && (sc == QStyle::SC_ComboBoxArrow || !isEditable())
         && !d->viewContainer()->isVisible()) {
         if (sc == QStyle::SC_ComboBoxArrow)
             d->updateArrow(QStyle::State_Sunken);
 #ifdef QT_KEYPAD_NAVIGATION
         //if the container already exists, then d->viewContainer() is safe to call
         if (d->container) {
 #endif
             // We've restricted the next couple of lines, because by not calling
             // viewContainer(), we avoid creating the QComboBoxPrivateContainer.
             d->viewContainer()->blockMouseReleaseTimer.start(QApplication::doubleClickInterval());
             d->viewContainer()->initialClickPosition = mapToGlobal(e->pos());
 #ifdef QT_KEYPAD_NAVIGATION
         }
 #endif
         showPopup();
     } else {
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && sc == QStyle::SC_ComboBoxEditField && d->lineEdit) {
             d->lineEdit->event(e);  //so lineedit can move cursor, etc
             return;
         }
 #endif
         QWidget::mousePressEvent(e);
     }
 }
mouseReleaseEvent()
void QComboBox::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3017 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     Q_UNUSED(e);
     d->updateArrow(QStyle::State_None);
 }
paintEvent()
void QComboBox::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2901 of file qcombobox.cpp.
 {
     QStylePainter painter(this);
     painter.setPen(palette().color(QPalette::Text));
     // draw the combobox frame, focusrect and selected etc.
     QStyleOptionComboBox opt;
     initStyleOption(&opt);
     painter.drawComplexControl(QStyle::CC_ComboBox, opt);
     // draw the icon and text
     painter.drawControl(QStyle::CE_ComboBoxLabel, opt);
 }
removeItem()
void QComboBox::removeItem (int index)
Removes the item at the given index from the combobox.
This will update the current index if the index is removed.
This function does nothing if index is out of range.
Definition at line 2337 of file qcombobox.cpp.
Referenced by QPrintDialogPrivate::setPrinter().
 {
     Q_D(QComboBox);
     if (index < 0 || index >= count())
         return;
     d->model->removeRows(index, 1, d->root);
 }
resizeEvent()
void QComboBox::resizeEvent (QResizeEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2888 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
 #ifdef Q_WS_S60
     if (d->viewContainer() && d->viewContainer()->isVisible())
         showPopup();
 #endif
     d->updateLineEditGeometry();
 }
rootModelIndex()
QModelIndex QComboBox::rootModelIndex () const
Returns the root model item index for the items in the combobox.
See also
setRootModelIndex()
Definition at line 2065 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     return QModelIndex(d->root);
 }
setAutoCompletion()
void QComboBox::setAutoCompletion (bool enable)
Use setCompleter() instead.
Definition at line 1457 of file qcombobox.cpp.
Referenced by setLineEdit().
 {
     Q_D(QComboBox);
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled() && !enable && isEditable())
         qWarning("QComboBox::setAutoCompletion: auto completion is mandatory when combo box editable");
 #endif
     d->autoCompletion = enable;
     if (!d->lineEdit)
         return;
     if (enable) {
         if (d->lineEdit->completer())
             return;
         d->completer = new QCompleter(d->model, d->lineEdit);
         d->completer->setCaseSensitivity(d->autoCompletionCaseSensitivity);
         d->completer->setCompletionMode(QCompleter::InlineCompletion);
         d->completer->setCompletionColumn(d->modelColumn);
         d->lineEdit->setCompleter(d->completer);
         d->completer->setWidget(this);
     } else {
         d->lineEdit->setCompleter(0);
     }
 }
setAutoCompletionCaseSensitivity()
void QComboBox::setAutoCompletionCaseSensitivity (Qt::CaseSensitivity sensitivity)
Use setCompleter() and QCompleter::setCaseSensitivity() instead.
Definition at line 1521 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     d->autoCompletionCaseSensitivity = sensitivity;
     if (d->lineEdit && d->lineEdit->completer())
         d->lineEdit->completer()->setCaseSensitivity(sensitivity);
 }
setCompleter()
void QComboBox::setCompleter (QCompleter * completer)
Since
4.2
Sets the completer to use instead of the current completer. If completer is 0, auto completion is disabled.
By default, for an editable combo box, a QCompleter that performs case insensitive inline completion is automatically created.
Definition at line 1903 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (!d->lineEdit)
         return;
     d->lineEdit->setCompleter(c);
     if (c)
         c->setWidget(this);
 }
setCurrentIndex
void QComboBox::setCurrentIndex (int index) slot
Definition at line 2102 of file qcombobox.cpp.
Referenced by QComboBoxPrivate::_q_itemSelected(), QComboBoxPrivate::keyboardSearchString(), keyPressEvent(), QInputDialogPrivate::setComboBoxText(), QPPDOptionsEditor::setEditorData(), setModel(), setModelColumn(), QPrintDialogPrivate::setPrinter(), QBooleanComboBox::setValue(), and wheelEvent().
 {
     Q_D(QComboBox);
     QModelIndex mi = d->model->index(index, d->modelColumn, d->root);
     d->setCurrentIndex(mi);
 }
setDuplicatesEnabled()
void QComboBox::setDuplicatesEnabled (bool enable)
Definition at line 1549 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     d->duplicatesEnabled = enable;
 }
setEditable()
void QComboBox::setEditable (bool editable)
Definition at line 1759 of file qcombobox.cpp.
Referenced by QPrintPreviewDialogPrivate::init(), QComboBox(), and QFontComboBox::QFontComboBox().
 {
     Q_D(QComboBox);
     if (isEditable() == editable)
         return;
     d->updateDelegate();
     QStyleOptionComboBox opt;
     initStyleOption(&opt);
     if (editable) {
         if (style()->styleHint(QStyle::SH_ComboBox_Popup, &opt, this)) {
             d->viewContainer()->updateScrollers();
             view()->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
         }
         QLineEdit *le = new QLineEdit(this);
         setLineEdit(le);
     } else {
         if (style()->styleHint(QStyle::SH_ComboBox_Popup, &opt, this)) {
             d->viewContainer()->updateScrollers();
             view()->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
         }
         setAttribute(Qt::WA_InputMethodEnabled, false);
         d->lineEdit->hide();
         d->lineEdit->deleteLater();
         d->lineEdit = 0;
     }
     d->viewContainer()->updateTopBottomMargin();
     if (!testAttribute(Qt::WA_Resized))
         adjustSize();
 }
setEditText
void QComboBox::setEditText (const QString & text) slot
Sets the text in the combobox's text edit.
Definition at line 2776 of file qcombobox.cpp.
Referenced by QInputDialogPrivate::setComboBoxText().
 {
     Q_D(QComboBox);
     if (d->lineEdit)
         d->lineEdit->setText(text);
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::updateAccessibility(this, 0, QAccessible::NameChanged);
 #endif
 }
setFrame()
void QComboBox::setFrame (bool enable)
Definition at line 3465 of file qcombobox.cpp.
Referenced by QDefaultItemEditorFactory::createEditor().
 {
     Q_D(QComboBox);
     d->frame = enable;
     update();
     updateGeometry();
 }
setIconSize()
void QComboBox::setIconSize (const QSize & size)
Definition at line 1699 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (size == d->iconSize)
         return;
     view()->setIconSize(size);
     d->iconSize = size;
     d->sizeHint = QSize();
     updateGeometry();
 }
setInsertPolicy()
void QComboBox::setInsertPolicy (InsertPolicy policy)
Definition at line 1603 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     d->insertPolicy = policy;
 }
setItemData()
void QComboBox::setItemData (int index, const QVariant & value, int role = Qt::UserRole)
Sets the data role for the item on the given index in the combobox to the specified value.
Definition at line 2373 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     QModelIndex item = d->model->index(index, d->modelColumn, d->root);
     if (item.isValid()) {
         d->model->setData(item, value, role);
     }
 }
setItemDelegate()
void QComboBox::setItemDelegate (QAbstractItemDelegate * delegate)
Sets the item delegate for the popup list view.
The combobox takes ownership of the delegate.
Warning
You should not share the same instance of a delegate between comboboxes, widget mappers or views. Doing so can cause incorrect or unintuitive editing behavior since each view connected to a given delegate may receive the QAbstractItemDelegate::closeEditor() signal, and attempt to access, modify or close an editor that has already been closed.
See also
itemDelegate()
Definition at line 1954 of file qcombobox.cpp.
Referenced by QFontComboBox::QFontComboBox().
 {
     if (!delegate) {
         qWarning("QComboBox::setItemDelegate: cannot set a 0 delegate");
         return;
     }
     delete view()->itemDelegate();
     view()->setItemDelegate(delegate);
 }
setItemIcon()
void QComboBox::setItemIcon (int index, const QIcon & icon)
Sets the icon for the item on the given index in the combobox.
Definition at line 2360 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     QModelIndex item = d->model->index(index, d->modelColumn, d->root);
     if (item.isValid()) {
         d->model->setData(item, icon, Qt::DecorationRole);
     }
 }
setItemText()
void QComboBox::setItemText (int index, const QString & text)
Sets the text for the item on the given index in the combobox.
Definition at line 2348 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     QModelIndex item = d->model->index(index, d->modelColumn, d->root);
     if (item.isValid()) {
         d->model->setData(item, text, Qt::EditRole);
     }
 }
setLineEdit()
void QComboBox::setLineEdit (QLineEdit * edit)
Sets the line edit to use instead of the current line edit widget.
The combo box takes ownership of the line edit.
Definition at line 1797 of file qcombobox.cpp.
Referenced by setEditable().
 {
     Q_D(QComboBox);
     if (!edit) {
         qWarning("QComboBox::setLineEdit: cannot set a 0 line edit");
         return;
     }
     if (edit == d->lineEdit)
         return;
     edit->setText(currentText());
     delete d->lineEdit;
     d->lineEdit = edit;
     if (d->lineEdit->parent() != this)
         d->lineEdit->setParent(this);
     connect(d->lineEdit, SIGNAL(returnPressed()), this, SLOT(_q_returnPressed()));
     connect(d->lineEdit, SIGNAL(editingFinished()), this, SLOT(_q_editingFinished()));
     connect(d->lineEdit, SIGNAL(textChanged(QString)), this, SIGNAL(editTextChanged(QString)));
 #ifdef QT3_SUPPORT
     connect(d->lineEdit, SIGNAL(textChanged(QString)), this, SIGNAL(textChanged(QString)));
 #endif
     d->lineEdit->setFrame(false);
     d->lineEdit->setContextMenuPolicy(Qt::NoContextMenu);
     d->lineEdit->setFocusProxy(this);
     d->lineEdit->setAttribute(Qt::WA_MacShowFocusRect, false);
 #ifndef QT_NO_COMPLETER
     setAutoCompletion(d->autoCompletion);
 #endif
 #ifdef QT_KEYPAD_NAVIGATION
 #ifndef QT_NO_COMPLETER
     if (QApplication::keypadNavigationEnabled()) {
         // Editable combo boxes will have a completer that is set to UnfilteredPopupCompletion.
         // This means that when the user enters edit mode they are immediately presented with a
         // list of possible completions.
         setAutoCompletion(true);
         if (d->completer) {
             d->completer->setCompletionMode(QCompleter::UnfilteredPopupCompletion);
             connect(d->completer, SIGNAL(activated(QModelIndex)), this, SLOT(_q_completerActivated()));
         }
     }
 #endif
 #endif
     setAttribute(Qt::WA_InputMethodEnabled);
     d->updateLayoutDirection();
     d->updateLineEditGeometry();
     if (isVisible())
         d->lineEdit->show();
     update();
 }
setMaxCount()
void QComboBox::setMaxCount (int max)
Definition at line 1397 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (max < 0) {
         qWarning("QComboBox::setMaxCount: Invalid count (%d) must be >= 0", max);
         return;
     }
     if (max < count())
         d->model->removeRows(max, count() - max, d->root);
     d->maxCount = max;
 }
setMaxVisibleItems()
void QComboBox::setMaxVisibleItems (int maxItems)
Definition at line 1356 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (maxItems < 0) {
         qWarning("QComboBox::setMaxVisibleItems: "
                  "Invalid max visible items (%d) must be >= 0", maxItems);
         return;
     }
     d->maxVisibleItems = maxItems;
 }
setMinimumContentsLength()
void QComboBox::setMinimumContentsLength (int characters)
Definition at line 1660 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (characters == d->minimumContentsLength || characters < 0)
         return;
     d->minimumContentsLength = characters;
     if (d->sizeAdjustPolicy == AdjustToContents
             || d->sizeAdjustPolicy == AdjustToMinimumContentsLength
             || d->sizeAdjustPolicy == AdjustToMinimumContentsLengthWithIcon) {
         d->sizeHint = QSize();
         d->adjustComboBoxSize();
         updateGeometry();
     }
 }
setModel()
void QComboBox::setModel (QAbstractItemModel * model)
Sets the model to be model.
model must not be 0. If you want to clear the contents of a model, call clear().
See also
clear()
Definition at line 1984 of file qcombobox.cpp.
Referenced by model(), and QFontComboBox::QFontComboBox().
 {
     Q_D(QComboBox);
     if (!model) {
         qWarning("QComboBox::setModel: cannot set a 0 model");
         return;
     }
 #ifndef QT_NO_COMPLETER
     if (d->lineEdit && d->lineEdit->completer()
         && d->lineEdit->completer() == d->completer)
         d->lineEdit->completer()->setModel(model);
 #endif
     if (d->model) {
         disconnect(d->model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                    this, SLOT(_q_dataChanged(QModelIndex,QModelIndex)));
         disconnect(d->model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
                    this, SLOT(_q_updateIndexBeforeChange()));
         disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                    this, SLOT(_q_rowsInserted(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                    this, SLOT(_q_updateIndexBeforeChange()));
         disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                    this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(destroyed()),
                    this, SLOT(_q_modelDestroyed()));
         disconnect(d->model, SIGNAL(modelAboutToBeReset()),
                    this, SLOT(_q_updateIndexBeforeChange()));
         disconnect(d->model, SIGNAL(modelReset()),
                    this, SLOT(_q_modelReset()));
         if (d->model->QObject::parent() == this)
             delete d->model;
     }
     d->model = model;
     connect(model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(_q_dataChanged(QModelIndex,QModelIndex)));
     connect(model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
             this, SLOT(_q_updateIndexBeforeChange()));
     connect(model, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_rowsInserted(QModelIndex,int,int)));
     connect(model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
             this, SLOT(_q_updateIndexBeforeChange()));
     connect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
             this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
     connect(model, SIGNAL(destroyed()),
             this, SLOT(_q_modelDestroyed()));
     connect(model, SIGNAL(modelAboutToBeReset()),
             this, SLOT(_q_updateIndexBeforeChange()));
     connect(model, SIGNAL(modelReset()),
             this, SLOT(_q_modelReset()));
     if (d->container)
         d->container->itemView()->setModel(model);
     bool currentReset = false;
     if (count()) {
         for (int pos=0; pos < count(); pos++) {
             if (d->model->index(pos, d->modelColumn, d->root).flags() & Qt::ItemIsEnabled) {
                 setCurrentIndex(pos);
                 currentReset = true;
                 break;
             }
         }
     }
     if (!currentReset)
         setCurrentIndex(-1);
     d->modelChanged();
 }
setModelColumn()
void QComboBox::setModelColumn (int visibleColumn)
Definition at line 3492 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     d->modelColumn = visibleColumn;
     QListView *lv = qobject_cast<QListView *>(d->viewContainer()->itemView());
     if (lv)
         lv->setModelColumn(visibleColumn);
 #ifndef QT_NO_COMPLETER
     if (d->lineEdit && d->lineEdit->completer()
         && d->lineEdit->completer() == d->completer)
         d->lineEdit->completer()->setCompletionColumn(visibleColumn);
 #endif
     setCurrentIndex(currentIndex()); //update the text to the text of the new column;
 }
setRootModelIndex()
void QComboBox::setRootModelIndex (const QModelIndex & index)
Sets the root model item index for the items in the combobox.
See also
rootModelIndex()
Definition at line 2076 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     d->root = QPersistentModelIndex(index);
     view()->setRootIndex(index);
     update();
 }
setSizeAdjustPolicy()
void QComboBox::setSizeAdjustPolicy (QComboBox::SizeAdjustPolicy policy)
Definition at line 1628 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (policy == d->sizeAdjustPolicy)
         return;
     d->sizeAdjustPolicy = policy;
     d->sizeHint = QSize();
     d->adjustComboBoxSize();
     updateGeometry();
 }
setValidator()
void QComboBox::setValidator (const QValidator * v)
Sets the validator to use instead of the current validator.
Definition at line 1871 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (d->lineEdit)
         d->lineEdit->setValidator(v);
 }
setView()
void QComboBox::setView (QAbstractItemView * itemView)
Sets the view to be used in the combobox popup to the given itemView.
The combobox takes ownership of the view.
Note: If you want to use the convenience views (like QListWidget, QTableWidget or QTreeWidget), make sure to call setModel() on the combobox with the convenience widgets model before calling this function.
Definition at line 2400 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (!itemView) {
         qWarning("QComboBox::setView: cannot set a 0 view");
         return;
     }
     if (itemView->model() != d->model)
         itemView->setModel(d->model);
     d->viewContainer()->setItemView(itemView);
 }
showEvent()
void QComboBox::showEvent (QShowEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2918 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (!d->shownOnce && d->sizeAdjustPolicy == QComboBox::AdjustToContentsOnFirstShow) {
         d->sizeHint = QSize();
         updateGeometry();
     }
     d->shownOnce = true;
     QWidget::showEvent(e);
 }
showPopup()
void QComboBox::showPopup () virtual
Displays the list of items in the combobox.
If the list is empty then the no items will be shown.
If you reimplement this function to show a custom pop-up, make sure you call hidePopup() to reset the internal state.
See also
hidePopup()
Reimplemented in QFileDialogComboBox.
Definition at line 2447 of file qcombobox.cpp.
Referenced by QAccessibleComboBox::doAction(), keyPressEvent(), mousePressEvent(), resizeEvent(), and QFileDialogComboBox::showPopup().
 {
     Q_D(QComboBox);
     if (count() <= 0)
         return;
 #ifdef QT_KEYPAD_NAVIGATION
 #ifndef QT_NO_COMPLETER
     if (QApplication::keypadNavigationEnabled() && d->completer) {
         // editable combo box is line edit plus completer
         setEditFocus(true);
         d->completer->complete(); // show popup
         return;
     }
 #endif
 #endif
     QStyle * const style = this->style();
     // set current item and select it
     view()->selectionModel()->setCurrentIndex(d->currentIndex,
                                               QItemSelectionModel::ClearAndSelect);
     QComboBoxPrivateContainer* container = d->viewContainer();
     QStyleOptionComboBox opt;
     initStyleOption(&opt);
     QRect listRect(style->subControlRect(QStyle::CC_ComboBox, &opt,
                                          QStyle::SC_ComboBoxListBoxPopup, this));
 #ifndef Q_WS_S60
     QRect screen = d->popupGeometry(QApplication::desktop()->screenNumber(this));
 #else
     QRect screen = qt_TRect2QRect(static_cast<CEikAppUi*>(S60->appUi())->ClientRect());
 #endif
     QPoint below = mapToGlobal(listRect.bottomLeft());
     int belowHeight = screen.bottom() - below.y();
     QPoint above = mapToGlobal(listRect.topLeft());
     int aboveHeight = above.y() - screen.y();
     bool boundToScreen = !window()->testAttribute(Qt::WA_DontShowOnScreen);
     const bool usePopup = style->styleHint(QStyle::SH_ComboBox_Popup, &opt, this);
     {
         int listHeight = 0;
         int count = 0;
         QStack<QModelIndex> toCheck;
         toCheck.push(view()->rootIndex());
 #ifndef QT_NO_TREEVIEW
         QTreeView *treeView = qobject_cast<QTreeView*>(view());
         if (treeView && treeView->header() && !treeView->header()->isHidden())
             listHeight += treeView->header()->height();
 #endif
         while (!toCheck.isEmpty()) {
             QModelIndex parent = toCheck.pop();
             for (int i = 0; i < d->model->rowCount(parent); ++i) {
                 QModelIndex idx = d->model->index(i, d->modelColumn, parent);
                 if (!idx.isValid())
                     continue;
                 listHeight += view()->visualRect(idx).height() + container->spacing();
 #ifndef QT_NO_TREEVIEW
                 if (d->model->hasChildren(idx) && treeView && treeView->isExpanded(idx))
                     toCheck.push(idx);
 #endif
                 ++count;
                 if (!usePopup && count >= d->maxVisibleItems) {
                     toCheck.clear();
                     break;
                 }
             }
         }
         listRect.setHeight(listHeight);
     }
     {
         // add the spacing for the grid on the top and the bottom;
         int heightMargin = 2*container->spacing();
         // add the frame of the container
         int marginTop, marginBottom;
         container->getContentsMargins(0, &marginTop, 0, &marginBottom);
         heightMargin += marginTop + marginBottom;
         //add the frame of the view
         view()->getContentsMargins(0, &marginTop, 0, &marginBottom);
         marginTop += static_cast<QAbstractScrollAreaPrivate *>(QObjectPrivate::get(view()))->top;
         marginBottom += static_cast<QAbstractScrollAreaPrivate *>(QObjectPrivate::get(view()))->bottom;
         heightMargin += marginTop + marginBottom;
         listRect.setHeight(listRect.height() + heightMargin);
     }
     // Add space for margin at top and bottom if the style wants it.
     if (usePopup)
         listRect.setHeight(listRect.height() + style->pixelMetric(QStyle::PM_MenuVMargin, &opt, this) * 2);
     // Make sure the popup is wide enough to display its contents.
     if (usePopup) {
         const int diff = d->computeWidthHint() - width();
         if (diff > 0)
             listRect.setWidth(listRect.width() + diff);
     }
     //we need to activate the layout to make sure the min/maximum size are set when the widget was not yet show
     container->layout()->activate();
     //takes account of the minimum/maximum size of the container
     listRect.setSize( listRect.size().expandedTo(container->minimumSize())
                       .boundedTo(container->maximumSize()));
     // make sure the widget fits on screen
     if (boundToScreen) {
         if (listRect.width() > screen.width() )
             listRect.setWidth(screen.width());
         if (mapToGlobal(listRect.bottomRight()).x() > screen.right()) {
             below.setX(screen.x() + screen.width() - listRect.width());
             above.setX(screen.x() + screen.width() - listRect.width());
         }
         if (mapToGlobal(listRect.topLeft()).x() < screen.x() ) {
             below.setX(screen.x());
             above.setX(screen.x());
         }
     }
     if (usePopup) {
         // Position horizontally.
         listRect.moveLeft(above.x());
 #ifndef Q_WS_S60
         // Position vertically so the curently selected item lines up
         // with the combo box.
         const QRect currentItemRect = view()->visualRect(view()->currentIndex());
         const int offset = listRect.top() - currentItemRect.top();
         listRect.moveTop(above.y() + offset - listRect.top());
 #endif
         // Clamp the listRect height and vertical position so we don't expand outside the
         // available screen geometry.This may override the vertical position, but it is more
         // important to show as much as possible of the popup.
         const int height = !boundToScreen ? listRect.height() : qMin(listRect.height(), screen.height());
         listRect.setHeight(height);
         if (boundToScreen) {
             if (listRect.top() < screen.top())
                 listRect.moveTop(screen.top());
             if (listRect.bottom() > screen.bottom())
                 listRect.moveBottom(screen.bottom());
         }
 #ifdef Q_WS_S60
         if (screen.width() < screen.height()) {
             // in portait, menu should be positioned above softkeys
             listRect.moveBottom(screen.bottom());
         } else {
             TRect staConTopRect = TRect();
             AknLayoutUtils::LayoutMetricsRect(AknLayoutUtils::EStaconTop, staConTopRect);
             listRect.setWidth(screen.height());
             //by default popup is centered on screen in landscape
             listRect.moveCenter(screen.center());
             if (staConTopRect.IsEmpty() && AknLayoutUtils::CbaLocation() != AknLayoutUtils::EAknCbaLocationBottom) {
                 // landscape without stacon, menu should be at the right
                 (opt.direction == Qt::LeftToRight) ? listRect.setRight(screen.right()) :
                                                      listRect.setLeft(screen.left());
             }
         }
 #endif
     } else if (!boundToScreen || listRect.height() <= belowHeight) {
         listRect.moveTopLeft(below);
     } else if (listRect.height() <= aboveHeight) {
         listRect.moveBottomLeft(above);
     } else if (belowHeight >= aboveHeight) {
         listRect.setHeight(belowHeight);
         listRect.moveTopLeft(below);
     } else {
         listRect.setHeight(aboveHeight);
         listRect.moveBottomLeft(above);
     }
 #ifndef QT_NO_IM
     if (QInputContext *qic = inputContext())
         qic->reset();
 #endif
     QScrollBar *sb = view()->horizontalScrollBar();
     Qt::ScrollBarPolicy policy = view()->horizontalScrollBarPolicy();
     bool needHorizontalScrollBar = (policy == Qt::ScrollBarAsNeeded || policy == Qt::ScrollBarAlwaysOn)
                                    && sb->minimum() < sb->maximum();
     if (needHorizontalScrollBar) {
         listRect.adjust(0, 0, 0, sb->height());
     }
     container->setGeometry(listRect);
 #ifndef Q_WS_MAC
     const bool updatesEnabled = container->updatesEnabled();
 #endif
 #if defined(Q_WS_WIN) && !defined(QT_NO_EFFECTS)
     bool scrollDown = (listRect.topLeft() == below);
     if (QApplication::isEffectEnabled(Qt::UI_AnimateCombo)
         && !style->styleHint(QStyle::SH_ComboBox_Popup, &opt, this) && !window()->testAttribute(Qt::WA_DontShowOnScreen))
         qScrollEffect(container, scrollDown ? QEffects::DownScroll : QEffects::UpScroll, 150);
 #endif
 // Don't disable updates on Mac OS X. Windows are displayed immediately on this platform,
 // which means that the window will be visible before the call to container->show() returns.
 // If updates are disabled at this point we'll miss our chance at painting the popup
 // menu before it's shown, causing flicker since the window then displays the standard gray
 // background.
 #ifndef Q_WS_MAC
     container->setUpdatesEnabled(false);
 #endif
     container->raise();
     container->show();
     container->updateScrollers();
     view()->setFocus();
     view()->scrollTo(view()->currentIndex(),
                      style->styleHint(QStyle::SH_ComboBox_Popup, &opt, this)
                              ? QAbstractItemView::PositionAtCenter
                              : QAbstractItemView::EnsureVisible);
 #ifndef Q_WS_MAC
     container->setUpdatesEnabled(updatesEnabled);
 #endif
     container->update();
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled())
         view()->setEditFocus(true);
 #endif
 }
sizeAdjustPolicy()
SizeAdjustPolicy QComboBox::sizeAdjustPolicy () const
Referenced by QComboBoxPrivate::_q_dataChanged(), QComboBoxPrivate::_q_rowsInserted(), QComboBoxPrivate::_q_rowsRemoved(), QComboBoxPrivate::modelChanged(), and setInsertPolicy().
sizeHint()
QSize QComboBox::sizeHint () const virtual
This implementation caches the size hint to avoid resizing when the contents change dynamically.
Reimplemented Function
To invalidate the cached value change the sizeAdjustPolicy .
Reimplemented from QWidget.
Reimplemented in QFontComboBox.
Definition at line 2432 of file qcombobox.cpp.
Referenced by QComboBoxPrivate::_q_dataChanged(), QComboBoxPrivate::_q_rowsInserted(), QComboBoxPrivate::_q_rowsRemoved(), QComboBoxPrivate::modelChanged(), and QFontComboBox::sizeHint().
 {
     Q_D(const QComboBox);
     return d->recomputeSizeHint(d->sizeHint);
 }
validator()
const QValidator * QComboBox::validator () const
Returns the validator that is used to constrain text input for the combobox.
See also
editable
Definition at line 1884 of file qcombobox.cpp.
 {
     Q_D(const QComboBox);
     return d->lineEdit ? d->lineEdit->validator() : 0;
 }
view()
QAbstractItemView * QComboBox::view () const
Returns the list view used for the combobox popup.
Definition at line 2385 of file qcombobox.cpp.
Referenced by QAccessibleComboBox::actionText(), QAccessibleComboBox::childCount(), QFontComboBox::event(), hidePopup(), QAccessibleComboBox::indexOfChild(), itemDelegate(), QComboBoxPrivate::keyboardSearchString(), QAccessibleComboBox::navigate(), QFontComboBox::QFontComboBox(), setEditable(), setIconSize(), setItemDelegate(), setRootModelIndex(), QFontComboBox::setWritingSystem(), and showPopup().
 {
     Q_D(const QComboBox);
     return const_cast<QComboBoxPrivate*>(d)->viewContainer()->itemView();
 }
wheelEvent()
void QComboBox::wheelEvent (QWheelEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3175 of file qcombobox.cpp.
 {
     Q_D(QComboBox);
     if (!d->viewContainer()->isVisible()) {
         int newIndex = currentIndex();
         if (e->delta() > 0) {
             newIndex--;
             while ((newIndex >= 0) && !(d->model->flags(d->model->index(newIndex,d->modelColumn,d->root)) & Qt::ItemIsEnabled))
                 newIndex--;
         } else {
             newIndex++;
             while ((newIndex < count()) && !(d->model->flags(d->model->index(newIndex,d->modelColumn,d->root)) & Qt::ItemIsEnabled))
                 newIndex++;
         }
         if (newIndex >= 0 && newIndex < count() && newIndex != currentIndex()) {
             setCurrentIndex(newIndex);
             d->emitActivated(d->currentIndex);
         }
         e->accept();
     }
 }
Properties
autoCompletion
bool QComboBox::autoCompletion private
whether the combobox provides auto-completion for editable items
Use setCompleter() instead.
Since
4.1
Use setCompleter() instead.
By default, this property is true.
See also
editable
Definition at line 80 of file qcombobox.h.
autoCompletionCaseSensitivity
Qt::CaseSensitivity QComboBox::autoCompletionCaseSensitivity private
whether string comparisons are case-sensitive or case-insensitive for auto-completion
Use setCompleter() and QCompleter::setCaseSensitivity() instead.
By default, this property is Qt::CaseInsensitive.
Use setCompleter() instead. Case sensitivity of the auto completion can be changed using QCompleter::setCaseSensitivity().
See also
autoCompletion
Definition at line 81 of file qcombobox.h.
count
int QComboBox::count private
the number of items in the combobox
By default, for an empty combo box, this property has a value of 0.
Definition at line 69 of file qcombobox.h.
Referenced by isc().
currentIndex
int QComboBox::currentIndex private
the index of the current item in the combobox.
The current index can change when inserting or removing items.
By default, for an empty combo box or a combo box in which no current item is set, this property has a value of -1.
Definition at line 71 of file qcombobox.h.
Referenced by QPrintDialogPrivate::_q_okClicked(), and QPPDOptionsEditor::setModelData().
currentText
QString QComboBox::currentText private
the current text
If the combo box is editable, the current text is the value displayed by the line edit. Otherwise, it is the value of the current item or an empty string if the combo box is empty or no current item is set.
See also
editable
Definition at line 70 of file qcombobox.h.
Referenced by QInputDialogPrivate::chooseRightTextInputWidget(), and QAccessibleComboBox::text().
duplicatesEnabled
bool QComboBox::duplicatesEnabled private
whether the user can enter duplicate items into the combobox
Note that it is always possible to programmatically insert duplicate items into the combobox.
By default, this property is false (duplicates are not allowed).
Definition at line 84 of file qcombobox.h.
editable
bool QComboBox::editable private
whether the combo box can be edited by the user
Use isEditable() instead.
By default, this property is false. The effect of editing depends on the insert policy.
See also
InsertPolicy
Definition at line 68 of file qcombobox.h.
frame
QComboBox::frame private
whether the combo box draws itself with a frame
If enabled (the default) the combo box draws itself inside a frame, otherwise the combo box draws itself without any frame.
Definition at line 85 of file qcombobox.h.
iconSize
QSize QComboBox::iconSize private
the size of the icons shown in the combobox.
Unless explicitly set this returns the default value of the current style. This size is the maximum size that icons can have; icons of smaller size are not scaled up.
Definition at line 77 of file qcombobox.h.
Referenced by QMacStyle::sizeFromContents().
insertPolicy
QComboBox::InsertPolicy QComboBox::insertPolicy private
the policy used to determine where user-inserted items should appear in the combobox
The default value is AtBottom , indicating that new items will appear at the bottom of the list of items.
See also
InsertPolicy
Definition at line 74 of file qcombobox.h.
maxCount
int QComboBox::maxCount private
the maximum number of items allowed in the combobox
Note
If you set the maximum number to be less then the current amount of items in the combobox, the extra items will be truncated. This also applies if you have set an external model on the combobox.
By default, this property's value is derived from the highest signed integer available (typically 2147483647).
Definition at line 73 of file qcombobox.h.
maxVisibleItems
int QComboBox::maxVisibleItems private
the maximum allowed size on screen of the combo box, measured in items
By default, this property has a value of 10.
Note
This property is ignored for non-editable comboboxes in styles that returns true for QStyle::SH_ComboBox_Popup such as the Mac style or the Gtk+ Style.
Definition at line 72 of file qcombobox.h.
minimumContentsLength
int QComboBox::minimumContentsLength private
the minimum number of characters that should fit into the combobox.
The default value is 0.
If this property is set to a positive value, the minimumSizeHint() and sizeHint() take it into account.
See also
sizeAdjustPolicy
Definition at line 76 of file qcombobox.h.
modelColumn
int QComboBox::modelColumn private
the column in the model that is visible.
If set prior to populating the combo box, the pop-up view will not be affected and will show the first column (using this property's default value).
By default, this property has a value of 0.
Definition at line 86 of file qcombobox.h.
sizeAdjustPolicy
QComboBox::SizeAdjustPolicy QComboBox::sizeAdjustPolicy private
the policy describing how the size of the combobox changes when the content changes
The default value is AdjustToContentsOnFirstShow .
See also
SizeAdjustPolicy
Definition at line 75 of file qcombobox.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qcombobox.h
/src/gui/widgets/qcombobox.cpp