Qt 4.8: QScriptDebuggerJob Class Reference
QScriptDebuggerJob Class Reference abstract
#include <qscriptdebuggerjob_p.h>
Public Functions
virtual void evaluateFinished (const QScriptDebuggerValue &result)
void finish ()
void hibernateUntilEvaluateFinished ()
QScriptDebuggerJob ()
virtual void start ()=0
virtual ~QScriptDebuggerJob ()
Protected Functions
QScriptDebuggerJob (QScriptDebuggerJobPrivate &dd)
Protected Variables
QScopedPointer< QScriptDebuggerJobPrivate > d_ptr
Detailed Description
Since
4.5
Warning
This function is not part of the public interface.
Note
The QScriptDebuggerJob class is the base class of debugger jobs.
Definition at line 65 of file qscriptdebuggerjob_p.h.
Constructors and Destructors
QScriptDebuggerJob() [1/2]
QScriptDebuggerJob::QScriptDebuggerJob ()
Definition at line 72 of file qscriptdebuggerjob.cpp.
     : d_ptr(new QScriptDebuggerJobPrivate)
 {
     d_ptr->q_ptr = this;
     d_ptr->jobScheduler = 0;
 }
~QScriptDebuggerJob()
QScriptDebuggerJob::~QScriptDebuggerJob () virtual
Definition at line 86 of file qscriptdebuggerjob.cpp.
 {
 }
QScriptDebuggerJob() [2/2]
QScriptDebuggerJob::QScriptDebuggerJob (QScriptDebuggerJobPrivate & dd) protected
Definition at line 79 of file qscriptdebuggerjob.cpp.
     : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
     d_ptr->jobScheduler = 0;
 }
Functions
evaluateFinished()
void QScriptDebuggerJob::evaluateFinished (const QScriptDebuggerValue & result) virtual
Definition at line 104 of file qscriptdebuggerjob.cpp.
Referenced by QScriptDebuggerPrivate::debuggerEvent().
 {
     Q_ASSERT_X(false, "QScriptDebuggerJob::evaluateFinished()",
                "implement if hibernateUntilEvaluateFinished() is called");
 }
finish()
void QScriptDebuggerJob::finish ()
Definition at line 90 of file qscriptdebuggerjob.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), and QScriptDebuggerScriptedConsoleCommandJob::start().
 {
     Q_D(QScriptDebuggerJob);
     Q_ASSERT(d->jobScheduler != 0);
     d->jobScheduler->finishJob(this);
 }
hibernateUntilEvaluateFinished()
void QScriptDebuggerJob::hibernateUntilEvaluateFinished ()
Definition at line 97 of file qscriptdebuggerjob.cpp.
 {
     Q_D(QScriptDebuggerJob);
     Q_ASSERT(d->jobScheduler != 0);
     d->jobScheduler->hibernateUntilEvaluateFinished(this);
 }
start()
virtual void QScriptDebuggerJob::start () pure virtual
Implemented in QScriptDebuggerShowLineJob, QScriptToolTipJob, QScriptDebuggerScriptedConsoleCommandJob, QScriptCompleteScriptsJob, and QScriptCompleteExpressionJob.
Referenced by QScriptDebuggerPrivate::maybeStartNewJob().
Properties
d_ptr
QScopedPointer<QScriptDebuggerJobPrivate> QScriptDebuggerJob::d_ptr protected
Definition at line 80 of file qscriptdebuggerjob_p.h.
Referenced by QScriptDebuggerJob().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerjob_p.h
/src/scripttools/debugging/qscriptdebuggerjob.cpp