Qt 4.8: QTextCopyHelper Class Reference
QTextCopyHelper Class Reference
#include <qtextdocumentfragment_p.h>
Public Functions
void copy ()
QTextCopyHelper (const QTextCursor &_source, const QTextCursor &_destination, bool forceCharFormat=false, const QTextCharFormat &fmt=QTextCharFormat())
Private Functions
int appendFragment (int pos, int endPos, int objectIndex=-1)
void appendFragments (int pos, int endPos)
QTextFormat convertFormat (const QTextFormat &fmt)
int convertFormatIndex (const QTextFormat &oldFormat, int objectIndexToSet=-1)
int convertFormatIndex (int oldFormatIndex, int objectIndexToSet=-1)
Properties
QTextCursor cursor
QTextDocumentPrivate * dst
bool forceCharFormat
QTextFormatCollection & formatCollection
int insertPos
QMap< int, int > objectIndexMap
const QString originalText
int primaryCharFormatIndex
QTextDocumentPrivate * src
Detailed Description
Definition at line 71 of file qtextdocumentfragment_p.h.
Constructors and Destructors
QTextCopyHelper()
QTextCopyHelper::QTextCopyHelper (const QTextCursor & _source, const QTextCursor & _destination, bool forceCharFormat = false, const QTextCharFormat & fmt = QTextCharFormat())
Definition at line 55 of file qtextdocumentfragment.cpp.
     : formatCollection(*_destination.d->priv->formatCollection()), originalText((const QString)_source.d->priv->buffer())
 #else
     : formatCollection(*_destination.d->priv->formatCollection()), originalText(_source.d->priv->buffer())
 #endif
 {
     src = _source.d->priv;
     dst = _destination.d->priv;
     insertPos = _destination.position();
     this->forceCharFormat = forceCharFormat;
     primaryCharFormatIndex = convertFormatIndex(fmt);
     cursor = _source;
 }
Functions
appendFragment()
int QTextCopyHelper::appendFragment (int pos, int endPos, int objectIndex = -1) private
Definition at line 90 of file qtextdocumentfragment.cpp.
Referenced by appendFragments(), and copy().
 {
     QTextDocumentPrivate::FragmentIterator fragIt = src->find(pos);
     const QTextFragmentData * const frag = fragIt.value();
     Q_ASSERT(objectIndex == -1
              || (frag->size_array[0] == 1 && src->formatCollection()->format(frag->format).objectIndex() != -1));
     int charFormatIndex;
     if (forceCharFormat)
        charFormatIndex = primaryCharFormatIndex;
     else
        charFormatIndex = convertFormatIndex(frag->format, objectIndex);
     const int inFragmentOffset = qMax(0, pos - fragIt.position());
     int charsToCopy = qMin(int(frag->size_array[0] - inFragmentOffset), endPos - pos);
     QTextBlock nextBlock = src->blocksFind(pos + 1);
     int blockIdx = -2;
     if (nextBlock.position() == pos + 1) {
         blockIdx = convertFormatIndex(nextBlock.blockFormat());
     } else if (pos == 0 && insertPos == 0) {
         dst->setBlockFormat(dst->blocksBegin(), dst->blocksBegin(), convertFormat(src->blocksBegin().blockFormat()).toBlockFormat());
         dst->setCharFormat(-1, 1, convertFormat(src->blocksBegin().charFormat()).toCharFormat());
     }
     QString txtToInsert(originalText.constData() + frag->stringPosition + inFragmentOffset, charsToCopy);
     if (txtToInsert.length() == 1
         && (txtToInsert.at(0) == QChar::ParagraphSeparator
             || txtToInsert.at(0) == QTextBeginningOfFrame
             || txtToInsert.at(0) == QTextEndOfFrame
            )
        ) {
         dst->insertBlock(txtToInsert.at(0), insertPos, blockIdx, charFormatIndex);
         ++insertPos;
     } else {
         if (nextBlock.textList()) {
             QTextBlock dstBlock = dst->blocksFind(insertPos);
             if (!dstBlock.textList()) {
                 // insert a new text block with the block and char format from the
                 // source block to make sure that the following text fragments
                 // end up in a list as they should
                 int listBlockFormatIndex = convertFormatIndex(nextBlock.blockFormat());
                 int listCharFormatIndex = convertFormatIndex(nextBlock.charFormat());
                 dst->insertBlock(insertPos, listBlockFormatIndex, listCharFormatIndex);
                 ++insertPos;
             }
         }
         dst->insert(insertPos, txtToInsert, charFormatIndex);
         const int userState = nextBlock.userState();
         if (userState != -1)
             dst->blocksFind(insertPos).setUserState(userState);
         insertPos += txtToInsert.length();
     }
     return charsToCopy;
 }
appendFragments()
void QTextCopyHelper::appendFragments (int pos, int endPos) private
Definition at line 149 of file qtextdocumentfragment.cpp.
Referenced by copy().
 {
     Q_ASSERT(pos < endPos);
     while (pos < endPos)
         pos += appendFragment(pos, endPos);
 }
convertFormat()
QTextFormat QTextCopyHelper::convertFormat (const QTextFormat & fmt) inline private
Definition at line 84 of file qtextdocumentfragment_p.h.
Referenced by appendFragment().
     { return dst->formatCollection()->format(convertFormatIndex(fmt)); }
convertFormatIndex() [1/2]
int QTextCopyHelper::convertFormatIndex (const QTextFormat & oldFormat, int objectIndexToSet = -1) private
Definition at line 70 of file qtextdocumentfragment.cpp.
Referenced by appendFragment(), convertFormat(), convertFormatIndex(), and copy().
 {
     QTextFormat fmt = oldFormat;
     if (objectIndexToSet != -1) {
         fmt.setObjectIndex(objectIndexToSet);
     } else if (fmt.objectIndex() != -1) {
         int newObjectIndex = objectIndexMap.value(fmt.objectIndex(), -1);
         if (newObjectIndex == -1) {
             QTextFormat objFormat = src->formatCollection()->objectFormat(fmt.objectIndex());
             Q_ASSERT(objFormat.objectIndex() == -1);
             newObjectIndex = formatCollection.createObjectIndex(objFormat);
             objectIndexMap.insert(fmt.objectIndex(), newObjectIndex);
         }
         fmt.setObjectIndex(newObjectIndex);
     }
     int idx = formatCollection.indexForFormat(fmt);
     Q_ASSERT(formatCollection.format(idx).type() == oldFormat.type());
     return idx;
 }
convertFormatIndex() [2/2]
int QTextCopyHelper::convertFormatIndex (int oldFormatIndex, int objectIndexToSet = -1) inline private
Definition at line 82 of file qtextdocumentfragment_p.h.
     { return convertFormatIndex(src->formatCollection()->format(oldFormatIndex), objectIndexToSet); }
copy()
void QTextCopyHelper::copy ()
Definition at line 157 of file qtextdocumentfragment.cpp.
Referenced by QTextDocumentFragmentPrivate::QTextDocumentFragmentPrivate().
 {
     if (cursor.hasComplexSelection()) {
         QTextTable *table = cursor.currentTable();
         int row_start, col_start, num_rows, num_cols;
         cursor.selectedTableCells(&row_start, &num_rows, &col_start, &num_cols);
         QTextTableFormat tableFormat = table->format();
         tableFormat.setColumns(num_cols);
         tableFormat.clearColumnWidthConstraints();
         const int objectIndex = dst->formatCollection()->createObjectIndex(tableFormat);
         Q_ASSERT(row_start != -1);
         for (int r = row_start; r < row_start + num_rows; ++r) {
             for (int c = col_start; c < col_start + num_cols; ++c) {
                 QTextTableCell cell = table->cellAt(r, c);
                 const int rspan = cell.rowSpan();
                 const int cspan = cell.columnSpan();
                 if (rspan != 1) {
                     int cr = cell.row();
                     if (cr != r)
                         continue;
                 }
                 if (cspan != 1) {
                     int cc = cell.column();
                     if (cc != c)
                         continue;
                 }
                 // add the QTextBeginningOfFrame
                 QTextCharFormat cellFormat = cell.format();
                 if (r + rspan >= row_start + num_rows) {
                     cellFormat.setTableCellRowSpan(row_start + num_rows - r);
                 }
                 if (c + cspan >= col_start + num_cols) {
                     cellFormat.setTableCellColumnSpan(col_start + num_cols - c);
                 }
                 const int charFormatIndex = convertFormatIndex(cellFormat, objectIndex);
                 int blockIdx = -2;
                 const int cellPos = cell.firstPosition();
                 QTextBlock block = src->blocksFind(cellPos);
                 if (block.position() == cellPos) {
                     blockIdx = convertFormatIndex(block.blockFormat());
                 }
                 dst->insertBlock(QTextBeginningOfFrame, insertPos, blockIdx, charFormatIndex);
                 ++insertPos;
                 // nothing to add for empty cells
                 if (cell.lastPosition() > cellPos) {
                     // add the contents
                     appendFragments(cellPos, cell.lastPosition());
                 }
             }
         }
         // add end of table
         int end = table->lastPosition();
         appendFragment(end, end+1, objectIndex);
     } else {
         appendFragments(cursor.selectionStart(), cursor.selectionEnd());
     }
 }
Properties
cursor
QTextCursor QTextCopyHelper::cursor private
Definition at line 92 of file qtextdocumentfragment_p.h.
Referenced by copy(), and QTextDocumentFragmentPrivate::~QTextDocumentFragmentPrivate().
dst
QTextDocumentPrivate* QTextCopyHelper::dst private
Definition at line 93 of file qtextdocumentfragment_p.h.
Referenced by appendFragment(), convertFormat(), and copy().
forceCharFormat
bool QTextCopyHelper::forceCharFormat private
Definition at line 89 of file qtextdocumentfragment_p.h.
formatCollection
QTextFormatCollection& QTextCopyHelper::formatCollection private
Definition at line 95 of file qtextdocumentfragment_p.h.
Referenced by convertFormatIndex().
insertPos
int QTextCopyHelper::insertPos private
Definition at line 87 of file qtextdocumentfragment_p.h.
Referenced by appendFragment(), and copy().
objectIndexMap
QMap<int, int> QTextCopyHelper::objectIndexMap private
Definition at line 97 of file qtextdocumentfragment_p.h.
Referenced by convertFormatIndex().
originalText
const QString QTextCopyHelper::originalText private
Definition at line 96 of file qtextdocumentfragment_p.h.
Referenced by appendFragment().
primaryCharFormatIndex
int QTextCopyHelper::primaryCharFormatIndex private
Definition at line 90 of file qtextdocumentfragment_p.h.
Referenced by appendFragment().
src
QTextDocumentPrivate* QTextCopyHelper::src private
Definition at line 94 of file qtextdocumentfragment_p.h.
Referenced by appendFragment(), convertFormatIndex(), and copy().
The documentation for this class was generated from the following files:
/src/gui/text/qtextdocumentfragment_p.h
/src/gui/text/qtextdocumentfragment.cpp