Qt 4.8: QScript::GlobalObject Class Reference
QScript::GlobalObject Class Reference
#include <qscriptglobalobject_p.h>
Public Functions
virtual JSC::UString className () const
virtual void defineGetter (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::JSObject *getterFunction, unsigned attributes=0)
virtual void defineSetter (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::JSObject *setterFunction, unsigned attributes=0)
virtual bool deleteProperty (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual bool getOwnPropertyDescriptor (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
GlobalObject ()
virtual JSC::JSValue lookupGetter (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual JSC::JSValue lookupSetter (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual void markChildren (JSC::MarkStack &)
virtual void put (JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue, JSC::PutPropertySlot &)
virtual void putWithAttributes (JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue value, unsigned attributes)
virtual ~GlobalObject ()
Public Variables
JSC::JSObject * customGlobalObject
Detailed Description
Definition at line 47 of file qscriptglobalobject_p.h.
Constructors and Destructors
GlobalObject()
QScript::GlobalObject::GlobalObject ()
Definition at line 44 of file qscriptglobalobject.cpp.
     : JSC::JSGlobalObject(), customGlobalObject(0)
 {
 }
~GlobalObject()
QScript::GlobalObject::~GlobalObject () virtual
Definition at line 49 of file qscriptglobalobject.cpp.
 {
 }
Functions
className()
virtual JSC::UString QScript::GlobalObject::className () const inline virtual
Definition at line 52 of file qscriptglobalobject_p.h.
 { return "global"; }
defineGetter()
void QScript::GlobalObject::defineGetter (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSObject * getterFunction, unsigned attributes = 0) virtual
Definition at line 126 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         customGlobalObject->defineGetter(exec, propertyName, getterFunction, attributes);
     else
         JSC::JSGlobalObject::defineGetter(exec, propertyName, getterFunction, attributes);
 }
defineSetter()
void QScript::GlobalObject::defineSetter (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSObject * setterFunction, unsigned attributes = 0) virtual
Definition at line 134 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         customGlobalObject->defineSetter(exec, propertyName, setterFunction, attributes);
     else
         JSC::JSGlobalObject::defineSetter(exec, propertyName, setterFunction, attributes);
 }
deleteProperty()
bool QScript::GlobalObject::deleteProperty (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 110 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         return customGlobalObject->deleteProperty(exec, propertyName);
     return JSC::JSGlobalObject::deleteProperty(exec, propertyName);
 }
getOwnPropertyDescriptor()
bool QScript::GlobalObject::getOwnPropertyDescriptor (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Definition at line 75 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     // Must match the logic of getOwnPropertySlot().
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     if (propertyName == exec->propertyNames().arguments && engine->currentFrame->argumentCount() > 0) {
         // ### Can we get rid of this special handling of the arguments property?
         JSC::JSValue args = engine->scriptValueToJSCValue(engine->contextForFrame(engine->currentFrame)->argumentsObject());
         descriptor.setValue(args);
         return true;
     }
     if (customGlobalObject)
         return customGlobalObject->getOwnPropertyDescriptor(exec, propertyName, descriptor);
     return JSC::JSGlobalObject::getOwnPropertyDescriptor(exec, propertyName, descriptor);
 }
getOwnPropertyNames()
void QScript::GlobalObject::getOwnPropertyNames (JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Definition at line 117 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         customGlobalObject->getOwnPropertyNames(exec, propertyNames, mode);
     else
         JSC::JSGlobalObject::getOwnPropertyNames(exec, propertyNames, mode);
 }
getOwnPropertySlot()
bool QScript::GlobalObject::getOwnPropertySlot (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Definition at line 60 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     QScriptEnginePrivate *engine = scriptEngineFromExec(exec);
     if (propertyName == exec->propertyNames().arguments && engine->currentFrame->argumentCount() > 0) {
         JSC::JSValue args = engine->scriptValueToJSCValue(engine->contextForFrame(engine->currentFrame)->argumentsObject());
         slot.setValue(args);
         return true;
     }
     if (customGlobalObject)
         return customGlobalObject->getOwnPropertySlot(exec, propertyName, slot);
     return JSC::JSGlobalObject::getOwnPropertySlot(exec, propertyName, slot);
 }
lookupGetter()
JSC::JSValue QScript::GlobalObject::lookupGetter (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 142 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         return customGlobalObject->lookupGetter(exec, propertyName);
     return JSC::JSGlobalObject::lookupGetter(exec, propertyName);
 }
lookupSetter()
JSC::JSValue QScript::GlobalObject::lookupSetter (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 149 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         return customGlobalObject->lookupSetter(exec, propertyName);
     return JSC::JSGlobalObject::lookupSetter(exec, propertyName);
 }
markChildren()
void QScript::GlobalObject::markChildren (JSC::MarkStack & markStack) virtual
Definition at line 53 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     JSC::JSGlobalObject::markChildren(markStack);
     if (customGlobalObject)
         markStack.append(customGlobalObject);
 }
put()
void QScript::GlobalObject::put (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Definition at line 92 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         customGlobalObject->put(exec, propertyName, value, slot);
     else
         JSC::JSGlobalObject::put(exec, propertyName, value, slot);
 }
putWithAttributes()
void QScript::GlobalObject::putWithAttributes (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, unsigned attributes) virtual
Definition at line 101 of file qscriptglobalobject.cpp.
Referenced by className().
 {
     if (customGlobalObject)
         customGlobalObject->putWithAttributes(exec, propertyName, value, attributes);
     else
         JSC::JSGlobalObject::putWithAttributes(exec, propertyName, value, attributes);
 }
Properties
customGlobalObject
JSC::JSObject* QScript::GlobalObject::customGlobalObject
Definition at line 74 of file qscriptglobalobject_p.h.
Referenced by QScriptEnginePrivate::customGlobalObject(), defineGetter(), defineSetter(), deleteProperty(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), QScriptEnginePrivate::globalObject(), lookupGetter(), lookupSetter(), markChildren(), put(), putWithAttributes(), and QScriptEnginePrivate::setGlobalObject().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptglobalobject_p.h
/src/script/bridge/qscriptglobalobject.cpp