Qt 4.8: QJisCodec Class Reference
QJisCodec Class Reference
#include <qjiscodec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
QJisCodec ()
~QJisCodec ()
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
Returns the codec's mime name.
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Protected Variables
const QJpUnicodeConv * conv
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
Note
This class or function is reentrant.
Warning
This function is not part of the public interface.
Definition at line 82 of file qjiscodec.h.
Constructors and Destructors
QJisCodec()
QJisCodec::QJisCodec ()
Warning
This function is not part of the public interface.
Definition at line 95 of file qjiscodec.cpp.
Referenced by mibEnum().
                      : conv(QJpUnicodeConv::newConverter(QJpUnicodeConv::Default))
 {
 }
~QJisCodec()
QJisCodec::~QJisCodec ()
Warning
This function is not part of the public interface.
Definition at line 101 of file qjiscodec.cpp.
Referenced by mibEnum().
 {
     delete (QJpUnicodeConv*)conv;
     conv = 0;
 }
Functions
_aliases()
QList< QByteArray > QJisCodec::_aliases () static
Returns the codec's mime name.
Definition at line 358 of file qjiscodec.cpp.
Referenced by JPTextCodecs::aliases(), aliases(), and JPTextCodecs::createForName().
 {
     QList<QByteArray> list;
     list << "JIS7"; // Qt 3 compat
     return list;
 }
_mibEnum()
int QJisCodec::_mibEnum () static
Warning
This function is not part of the public interface.
Definition at line 344 of file qjiscodec.cpp.
Referenced by JPTextCodecs::createForMib(), mibEnum(), and JPTextCodecs::mibEnums().
 {
     return 39;
 }
_name()
QByteArray QJisCodec::_name () static
Warning
This function is not part of the public interface.
Definition at line 350 of file qjiscodec.cpp.
Referenced by JPTextCodecs::createForName(), name(), and JPTextCodecs::names().
 {
     return "ISO-2022-JP";
 }
aliases()
QList<QByteArray> QJisCodec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QTextCodec.
Definition at line 89 of file qjiscodec.h.
 { return _aliases(); }
convertFromUnicode()
QByteArray QJisCodec::convertFromUnicode (const QChar * input, int number, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first number of characters from the input array from Unicode to the encoding of the subclass, and returns the result in a QByteArray.
state can be 0 in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 107 of file qjiscodec.cpp.
Referenced by mibEnum().
 {
     char replacement = '?';
     if (cs) {
         if (cs->flags & ConvertInvalidToNull)
             replacement = 0;
     }
     int invalid = 0;
     QByteArray result;
     Iso2022State state = Ascii;
     Iso2022State prev = Ascii;
     for (int i = 0; i < len; i++) {
         QChar ch = uc[i];
         uint j;
         if (ch.row() == 0x00 && ch.cell() < 0x80) {
             // Ascii
             if (state != JISX0201_Latin ||
                 ch.cell() == ReverseSolidus || ch.cell() == Tilde) {
                 state = Ascii;
             }
             j = ch.cell();
         } else if ((j = conv->unicodeToJisx0201(ch.row(), ch.cell())) != 0) {
             if (j < 0x80) {
                 // JIS X 0201 Latin
                 if (state != Ascii ||
                     ch.cell() == YenSign || ch.cell() == Overline) {
                     state = JISX0201_Latin;
                 }
             } else {
                 // JIS X 0201 Kana
                 state = JISX0201_Kana;
                 j &= 0x7f;
             }
         } else if ((j = conv->unicodeToJisx0208(ch.row(), ch.cell())) != 0) {
             // JIS X 0208
             state = JISX0208_1983;
         } else if ((j = conv->unicodeToJisx0212(ch.row(), ch.cell())) != 0) {
             // JIS X 0212
             state = JISX0212;
         } else {
             // Invalid
             state = UnknownState;
             j = replacement;
             ++invalid;
         }
         if (state != prev) {
             if (state == UnknownState) {
                 result += Esc_Ascii;
             } else {
                 result += Esc_SEQ[state - MinState];
             }
             prev = state;
         }
         if (j < 0x0100) {
             result += j & 0xff;
         } else {
             result += (j >> 8) & 0xff;
             result += j & 0xff;
         }
     }
     if (prev != Ascii) {
         result += Esc_Ascii;
     }
     if (cs) {
         cs->invalidChars += invalid;
     }
     return result;
 }
convertToUnicode()
QString QJisCodec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 178 of file qjiscodec.cpp.
Referenced by mibEnum().
 {
     uchar buf[4] = {0, 0, 0, 0};
     int nbuf = 0;
     Iso2022State state = Ascii, prev = Ascii;
     bool esc = false;
     QChar replacement = QChar::ReplacementCharacter;
     if (cs) {
         if (cs->flags & ConvertInvalidToNull)
             replacement = QChar::Null;
         nbuf = cs->remainingChars;
         buf[0] = (cs->state_data[0] >> 24) & 0xff;
         buf[1] = (cs->state_data[0] >> 16) & 0xff;
         buf[2] = (cs->state_data[0] >>  8) & 0xff;
         buf[3] = (cs->state_data[0] >>  0) & 0xff;
         state = (Iso2022State)((cs->state_data[1] >>  0) & 0xff);
         prev = (Iso2022State)((cs->state_data[1] >>  8) & 0xff);
         esc = cs->state_data[2];
     }
     int invalid = 0;
     QString result;
     for (int i=0; i<len; i++) {
         uchar ch = chars[i];
         if (esc) {
             // Escape sequence
             state = UnknownState;
             switch (nbuf) {
             case 0:
                 if (ch == '$' || strchr(Esc_CHARS, ch)) {
                     buf[nbuf++] = ch;
                 } else {
                     nbuf = 0;
                     esc = false;
                 }
                 break;
             case 1:
                 if (buf[0] == '$') {
                     if (strchr(Esc_CHARS, ch)) {
                         buf[nbuf++] = ch;
                     } else {
                         switch (ch) {
                         case '@':
                             state = JISX0208_1978;        // Esc $ @
                             break;
                         case 'B':
                             state = JISX0208_1983;        // Esc $ B
                             break;
                         }
                         nbuf = 0;
                         esc = false;
                     }
                 } else {
                     if (buf[0] == '(') {
                         switch (ch) {
                         case 'B':
                             state = Ascii;        // Esc (B
                             break;
                         case 'I':
                             state = JISX0201_Kana;        // Esc (I
                             break;
                         case 'J':
                             state = JISX0201_Latin;        // Esc (J
                             break;
                         }
                     }
                     nbuf = 0;
                     esc = false;
                 }
                 break;
             case 2:
                 if (buf[1] == '(') {
                     switch (ch) {
                     case 'D':
                         state = JISX0212;        // Esc $ (D
                         break;
                     }
                 }
                 nbuf = 0;
                 esc = false;
                 break;
             }
         } else {
             if (ch == Esc) {
                 // Escape sequence
                 nbuf = 0;
                 esc = true;
             } else if (ch == So) {
                 // Shift out
                 prev = state;
                 state = JISX0201_Kana;
                 nbuf = 0;
             } else if (ch == Si) {
                 // Shift in
                 if (prev == Ascii || prev == JISX0201_Latin) {
                     state = prev;
                 } else {
                     state = Ascii;
                 }
                 nbuf = 0;
             } else {
                 uint u;
                 switch (nbuf) {
                 case 0:
                     switch (state) {
                     case Ascii:
                         if (ch < 0x80) {
                             result += QLatin1Char(ch);
                             break;
                         }
                         /* fall through */
                     case JISX0201_Latin:
                         u = conv->jisx0201ToUnicode(ch);
                         result += QValidChar(u);
                         break;
                     case JISX0201_Kana:
                         u = conv->jisx0201ToUnicode(ch | 0x80);
                         result += QValidChar(u);
                         break;
                     case JISX0208_1978:
                     case JISX0208_1983:
                     case JISX0212:
                         buf[nbuf++] = ch;
                         break;
                     default:
                         result += QChar::ReplacementCharacter;
                         break;
                     }
                     break;
                 case 1:
                     switch (state) {
                     case JISX0208_1978:
                     case JISX0208_1983:
                         u = conv->jisx0208ToUnicode(buf[0] & 0x7f, ch & 0x7f);
                         result += QValidChar(u);
                         break;
                     case JISX0212:
                         u = conv->jisx0212ToUnicode(buf[0] & 0x7f, ch & 0x7f);
                         result += QValidChar(u);
                         break;
                     default:
                         result += replacement;
                         ++invalid;
                         break;
                     }
                     nbuf = 0;
                     break;
                 }
             }
         }
     }
     if (cs) {
         cs->remainingChars = nbuf;
         cs->invalidChars += invalid;
         cs->state_data[0] = (buf[0] << 24) + (buf[1] << 16) + (buf[2] << 8) + buf[3];
         cs->state_data[1] = (prev << 8) + state;
         cs->state_data[2] = esc;
     }
     return result;
 }
mibEnum()
int QJisCodec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Definition at line 90 of file qjiscodec.h.
 { return _mibEnum(); }
name()
QByteArray QJisCodec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Definition at line 88 of file qjiscodec.h.
 { return _name(); }
Properties
conv
const QJpUnicodeConv* QJisCodec::conv protected
Definition at line 99 of file qjiscodec.h.
Referenced by convertFromUnicode(), convertToUnicode(), and ~QJisCodec().
The documentation for this class was generated from the following files:
/src/plugins/codecs/jp/qjiscodec.h
/src/plugins/codecs/jp/qjiscodec.cpp