Qt 4.8: QPointer< T > Class Template Reference
QPointer< T > Class Template Reference
The QPointer class is a template class that provides guarded pointers to QObject.
#include <qpointer.h>
Public Functions
T * data () const
bool isNull () const
Returns true if the referenced object has been destroyed or if there is no referenced object; otherwise returns false.
operator T* () const
Cast operator; implements pointer semantics.
T & operator* () const
Dereference operator; implements pointer semantics.
T * operator-> () const
Overloaded arrow operator; implements pointer semantics.
QPointer< T > & operator= (const QPointer< T > &p)
Assignment operator.
QPointer< T > & operator= (T *p)
Assignment operator.
QPointer ()
Constructs a 0 guarded pointer.
QPointer (T *p)
Constructs a guarded pointer that points to same object that p points to.
QPointer (const QPointer< T > &p)
Copies one guarded pointer from another.
~QPointer ()
Destroys the guarded pointer.
Properties
QObject * o
Related Functions
(Note that these are not member functions.)
bool operator!= (const T *o, const QPointer< T > &p)
bool operator!= (const QPointer< T > &p, const T *o)
bool operator!= (T *o, const QPointer< T > &p)
bool operator!= (const QPointer< T > &p, T *o)
bool operator!= (const QPointer< T > &p1, const QPointer< T > &p2)
Inequality operator.
bool operator== (const T *o, const QPointer< T > &p)
bool operator== (const QPointer< T > &p, const T *o)
bool operator== (T *o, const QPointer< T > &p)
bool operator== (const QPointer< T > &p, T *o)
bool operator== (const QPointer< T > &p1, const QPointer< T > &p2)
Equality operator.
Detailed Description
template<class T>
class QPointer< T >
The QPointer class is a template class that provides guarded pointers to QObject.
A guarded pointer, QPointer<T>, behaves like a normal C++ pointer T *, except that it is automatically set to 0 when the referenced object is destroyed (unlike normal C++ pointers, which become "dangling pointers" in such cases). T must be a subclass of QObject.
Guarded pointers are useful whenever you need to store a pointer to a QObject that is owned by someone else, and therefore might be destroyed while you still hold a reference to it. You can safely test the pointer for validity.
Qt also provides QSharedPointer, an implementation of a reference-counted shared pointer object, which can be used to maintain a collection of references to an individual pointer.
Example:
    QPointer<QLabel> label = new QLabel;
    label->setText("&Status:");
...
    if (label)
        label->show();
If the QLabel is deleted in the meantime, the label variable will hold 0 instead of an invalid address, and the last line will never be executed.
The functions and operators available with a QPointer are the same as those available with a normal unguarded pointer, except the pointer arithmetic operators (+, -, ++, and –), which are normally used only with arrays of objects.
Use QPointers like normal pointers and you will not need to read this class documentation.
For creating guarded pointers, you can construct or assign to them from a T* or from another guarded pointer of the same type. You can compare them with each other using operator==() and operator!=(), or test for 0 with isNull(). You can dereference them using either the *x or the x->member notation.
A guarded pointer will automatically cast to a T *, so you can freely mix guarded and unguarded pointers. This means that if you have a QPointer<QWidget>, you can pass it to a function that requires a QWidget *. For this reason, it is of little value to declare functions to take a QPointer as a parameter; just use normal pointers. Use a QPointer when you are storing a pointer over time.
Note that class T must inherit QObject, or a compilation or link error will result.
See also
QSharedPointer, QWeakPointer, QObject, QObjectCleanupHandler
Definition at line 54 of file qpointer.h.
Constructors and Destructors
QPointer() [1/3]
template<class T> QPointer< T >::QPointer () inline
Constructs a 0 guarded pointer.
See also
isNull()
Definition at line 58 of file qpointer.h.
 : o(0) {}
QPointer() [2/3]
template<class T> QPointer< T >::QPointer (T * p) inline
Constructs a guarded pointer that points to same object that p points to.
Definition at line 59 of file qpointer.h.
                           : o(p)
         { QMetaObject::addGuard(&o); }
QPointer() [3/3]
template<class T> QPointer< T >::QPointer (const QPointer< T > & p) inline
Copies one guarded pointer from another.
The constructed guarded pointer points to the same object that p points to (which may be 0).
Definition at line 61 of file qpointer.h.
                                           : o(p.o)
         { QMetaObject::addGuard(&o); }
~QPointer()
template<class T> QPointer< T >::~QPointer () inline
Destroys the guarded pointer.
Just like a normal pointer, destroying a guarded pointer does not destroy the object being pointed to.
Definition at line 63 of file qpointer.h.
         { QMetaObject::removeGuard(&o); }
Functions
data()
template<class T> T * QPointer< T >::data () const inline
Since
4.4
Returns the pointer to the object being guarded.
Definition at line 79 of file qpointer.h.
Referenced by QmlJSDebugger::QDeclarativeViewInspectorPrivate::setViewport(), ShaderEffectSource::sourceItem(), QX11Data::xdndHandleDrop(), and QMacMenuAction::~QMacMenuAction().
         { return static_cast<T*>(const_cast<QObject*>(o)); }
isNull()
template<class T> bool QPointer< T >::isNull () const inline
Returns true if the referenced object has been destroyed or if there is no referenced object; otherwise returns false.
Definition at line 70 of file qpointer.h.
Referenced by QNetworkReplyImplPrivate::_q_networkSessionConnected(), QWidgetPrivate::close_helper(), QDataWidgetMapperPrivate::commit(), QDBusConnectionPrivate::deliverCall(), QNetworkReplyImplPrivate::finished(), QTestEventLoop::instance(), QNetworkReplyImplPrivate::metaDataChanged(), operator!=(), QDataWidgetMapperPrivate::populate(), and QDBusConnectionPrivate::processFinishedCall().
         { return !o; }
operator T*()
template<class T> QPointer< T >::operator T* () const inline
Cast operator; implements pointer semantics.
Because of this function you can pass a QPointer<T> to a function where a T* is required.
Definition at line 77 of file qpointer.h.
         { return static_cast<T*>(const_cast<QObject*>(o)); }
operator*()
template<class T> T & QPointer< T >::operator* () const inline
Dereference operator; implements pointer semantics.
Just use this operator as you would with a normal C++ pointer.
Definition at line 75 of file qpointer.h.
         { return *static_cast<T*>(const_cast<QObject*>(o)); }
operator->()
template<class T> T * QPointer< T >::operator-> () const inline
Overloaded arrow operator; implements pointer semantics.
Just use this operator as you would with a normal C++ pointer.
Definition at line 73 of file qpointer.h.
         { return static_cast<T*>(const_cast<QObject*>(o)); }
operator=() [1/2]
template<class T> QPointer< T > & QPointer< T >::operator= (const QPointer< T > & p) inline
Assignment operator.
This guarded pointer will now point to the same object that p points to.
Definition at line 65 of file qpointer.h.
         { if (this != &p) QMetaObject::changeGuard(&o, p.o); return *this; }
operator=() [2/2]
template<class T> QPointer< T > & QPointer< T >::operator= (T * p) inline
Assignment operator.
This guarded pointer will now point to the same object that p points to.
Definition at line 67 of file qpointer.h.
         { if (o != p) QMetaObject::changeGuard(&o, p); return *this; }
Friends and Related Functions
operator!=() [1/5]
template<class T> bool operator!= (const T * o, const QPointer< T > & p) related
Inequality operator. Returns true if o and the guarded pointer p are not pointing to the same object, otherwise returns false.
Definition at line 122 of file qpointer.h.
Referenced by operator!=(), and QRect::QRect().
 { return o != p.operator->(); }
operator!=() [2/5]
template<class T> bool operator!= (const QPointer< T > & p, const T * o) related
Inequality operator. Returns true if o and the guarded pointer p are not pointing to the same object, otherwise returns false.
Definition at line 126 of file qpointer.h.
 { return p.operator->() != o; }
operator!=() [3/5]
template<class T> bool operator!= (T * o, const QPointer< T > & p) related
Inequality operator. Returns true if o and the guarded pointer p are not pointing to the same object, otherwise returns false.
Definition at line 142 of file qpointer.h.
 { return o != p.operator->(); }
operator!=() [4/5]
template<class T> bool operator!= (const QPointer< T > & p, T * o) related
Inequality operator. Returns true if o and the guarded pointer p are not pointing to the same object, otherwise returns false.
Definition at line 146 of file qpointer.h.
 { return p.operator->() != o; }
operator!=() [5/5]
template<class T> bool operator!= (const QPointer< T > & p1, const QPointer< T > & p2) related
Inequality operator.
Returns true if the guarded pointers p1 and p2 are not pointing to the same object, otherwise returns false.
Definition at line 150 of file qpointer.h.
 { return p1.operator->() != p2.operator->() ; }
operator==() [1/5]
template<class T> bool operator== (const T * o, const QPointer< T > & p) related
Equality operator. Returns true if o and the guarded pointer p are pointing to the same object, otherwise returns false.
Definition at line 87 of file qpointer.h.
Referenced by operator!=(), operator==(), and QRect::QRect().
 { return o == p.operator->(); }
operator==() [2/5]
template<class T> bool operator== (const QPointer< T > & p, const T * o) related
Equality operator. Returns true if o and the guarded pointer p are pointing to the same object, otherwise returns false.
Definition at line 91 of file qpointer.h.
 { return p.operator->() == o; }
operator==() [3/5]
template<class T> bool operator== (T * o, const QPointer< T > & p) related
Equality operator. Returns true if o and the guarded pointer p are pointing to the same object, otherwise returns false.
Definition at line 107 of file qpointer.h.
 { return o == p.operator->(); }
operator==() [4/5]
template<class T> bool operator== (const QPointer< T > & p, T * o) related
Equality operator. Returns true if o and the guarded pointer p are pointing to the same object, otherwise returns false.
Definition at line 111 of file qpointer.h.
 { return p.operator->() == o; }
operator==() [5/5]
template<class T> bool operator== (const QPointer< T > & p1, const QPointer< T > & p2) related
Equality operator.
Returns true if the guarded pointers p1 and p2 are pointing to the same object, otherwise returns false.
Definition at line 115 of file qpointer.h.
 { return p1.operator->() == p2.operator->(); }
Properties
o
template<class T> QObject* QPointer< T >::o private
Definition at line 56 of file qpointer.h.
Referenced by QPointer< QAbstractButton >::data(), QPointer< QAbstractButton >::isNull(), QPointer< T >::operator T*(), operator!=(), QPointer< QAbstractButton >::operator*(), QPointer< QAbstractButton >::operator->(), QPointer< QAbstractButton >::operator=(), and operator==().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qpointer.h
/src/corelib/kernel/qpointer.cpp