Qt 4.8: QXmlStreamNotationDeclaration Class Reference
QXmlStreamNotationDeclaration Class Reference
The QXmlStreamNotationDeclaration class represents a DTD notation declaration.
#include <qxmlstream.h>
Public Functions
QStringRef name () const
Returns the notation name.
bool operator!= (const QXmlStreamNotationDeclaration &other) const
Compares this notation declaration with other and returns true if they are not equal; otherwise returns false.
QXmlStreamNotationDeclaration & operator= (const QXmlStreamNotationDeclaration &)
Assigns other to this notation declaration.
bool operator== (const QXmlStreamNotationDeclaration &other) const
Compares this notation declaration with other and returns true if they are equal; otherwise returns false.
QStringRef publicId () const
Returns the public identifier.
QXmlStreamNotationDeclaration ()
Creates an empty notation declaration.
QXmlStreamNotationDeclaration (const QXmlStreamNotationDeclaration &)
Creates a copy of other.
QStringRef systemId () const
Returns the system identifier.
~QXmlStreamNotationDeclaration ()
Destructs this notation declaration.
Properties
QXmlStreamStringRef m_name
QXmlStreamStringRef m_publicId
QXmlStreamStringRef m_systemId
void * reserved
Friends
class QXmlStreamReaderPrivate
Related Functions
(Note that these are not member functions.)
QXmlStreamNotationDeclarations
Synonym for QVector<QXmlStreamNotationDeclaration>.
Detailed Description
The QXmlStreamNotationDeclaration class represents a DTD notation declaration.
Since
4.3
Note
This class or function is reentrant.
An notation declaration consists of a name(), a systemId(), and a publicId().
Definition at line 227 of file qxmlstream.h.
Constructors and Destructors
QXmlStreamNotationDeclaration() [1/2]
QXmlStreamNotationDeclaration::QXmlStreamNotationDeclaration ()
Creates an empty notation declaration.
Definition at line 2541 of file qxmlstream.cpp.
 {
 }
~QXmlStreamNotationDeclaration()
QXmlStreamNotationDeclaration::~QXmlStreamNotationDeclaration ()
Destructs this notation declaration.
Definition at line 2566 of file qxmlstream.cpp.
 {
 }
QXmlStreamNotationDeclaration() [2/2]
QXmlStreamNotationDeclaration::QXmlStreamNotationDeclaration (const QXmlStreamNotationDeclaration & other)
Creates a copy of other.
Definition at line 2547 of file qxmlstream.cpp.
 {
     *this = other;
 }
Functions
name()
QStringRef QXmlStreamNotationDeclaration::name () const inline
Returns the notation name.
Definition at line 237 of file qxmlstream.h.
Referenced by operator==().
 { return m_name; }
operator!=()
bool QXmlStreamNotationDeclaration::operator!= (const QXmlStreamNotationDeclaration & other) const inline
Compares this notation declaration with other and returns true if they are not equal; otherwise returns false.
Definition at line 244 of file qxmlstream.h.
         { return !operator==(other); }
operator=()
QXmlStreamNotationDeclaration & QXmlStreamNotationDeclaration::operator= (const QXmlStreamNotationDeclaration & other)
Assigns other to this notation declaration.
Definition at line 2555 of file qxmlstream.cpp.
 {
     m_name = other.m_name;
     m_systemId = other.m_systemId;
     m_publicId = other.m_publicId;
     return *this;
 }
operator==()
bool QXmlStreamNotationDeclaration::operator== (const QXmlStreamNotationDeclaration & other) const inline
Compares this notation declaration with other and returns true if they are equal; otherwise returns false.
Definition at line 240 of file qxmlstream.h.
{
         return (name() == other.name() && systemId() == other.systemId()
                 && publicId() == other.publicId());
     }
publicId()
QStringRef QXmlStreamNotationDeclaration::publicId () const inline
Returns the public identifier.
Definition at line 239 of file qxmlstream.h.
Referenced by operator==().
 { return m_publicId; }
systemId()
QStringRef QXmlStreamNotationDeclaration::systemId () const inline
Returns the system identifier.
Definition at line 238 of file qxmlstream.h.
Referenced by operator==().
 { return m_systemId; }
Friends and Related Functions
QXmlStreamNotationDeclarations()
QXmlStreamNotationDeclarations related
Synonym for QVector<QXmlStreamNotationDeclaration>.
QXmlStreamReaderPrivate
friend class QXmlStreamReaderPrivate friend
Definition at line 231 of file qxmlstream.h.
Properties
m_name
QXmlStreamStringRef QXmlStreamNotationDeclaration::m_name private
Definition at line 228 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
m_publicId
QXmlStreamStringRef QXmlStreamNotationDeclaration::m_publicId private
Definition at line 228 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
m_systemId
QXmlStreamStringRef QXmlStreamNotationDeclaration::m_systemId private
Definition at line 228 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveDtd().
reserved
void* QXmlStreamNotationDeclaration::reserved private
Definition at line 229 of file qxmlstream.h.
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlstream.h
/src/corelib/xml/qxmlstream.cpp