Qt 4.8: QMap< Key, T > Class Template Reference
QMap< Key, T > Class Template Reference
The QMap class is a template class that provides a skip-list-based dictionary.
#include <qdatastream.h>
Classes
class const_iterator
The QMap::const_iterator class provides an STL-style const iterator for QMap and QMultiMap.
class iterator
The QMap::iterator class provides an STL-style non-const iterator for QMap and QMultiMap.
Public Types
typedef const_iterator ConstIterator
Qt-style synonym for QMap::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QMap::iterator.
typedef Key key_type
Typedef for Key.
typedef T mapped_type
Typedef for T.
typedef int size_type
Typedef for int.
Public Functions
iterator begin ()
Returns an STL-style iterator pointing to the first item in the map.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all items from the map.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the map.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the map.
const_iterator constFind (const Key &key) const
Returns an const iterator pointing to the item with key key in the map.
bool contains (const Key &key) const
Returns true if the map contains an item with key key; otherwise returns false.
int count (const Key &key) const
Returns the number of items associated with key key.
int count () const
Same as size().
void detach ()
Detaches this map from any other maps with which it may share data.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the map.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator erase (iterator it)
Removes the (key, value) pair pointed to by the iterator pos from the map, and returns an iterator to the next item in the map.
iterator find (const Key &key)
Returns an iterator pointing to the item with key key in the map.
const_iterator find (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator insert (const Key &key, const T &value)
Inserts a new item with the key key and a value of value.
iterator insertMulti (const Key &key, const T &value)
Inserts a new item with the key key and a value of value.
bool isDetached () const
Returns true if the map's internal data isn't shared with any other map object; otherwise returns false.
bool isEmpty () const
Returns true if the map contains no items; otherwise returns false.
bool isSharedWith (const QMap< Key, T > &other) const
const Key key (const T &value) const
Returns the first key with value value.
const Key key (const T &value, const Key &defaultKey) const
Returns the first key with value value, or defaultKey if the map contains no item with value value.
QList< Key > keys () const
Returns a list containing all the keys in the map in ascending order.
QList< Key > keys (const T &value) const
Returns a list containing all the keys associated with value value in ascending order.
iterator lowerBound (const Key &key)
Returns an iterator pointing to the first item with key key in the map.
const_iterator lowerBound (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool operator!= (const QMap< Key, T > &other) const
Returns true if other is not equal to this map; otherwise returns false.
QMap< Key, T > & operator= (const QMap< Key, T > &other)
Assigns other to this map and returns a reference to this map.
bool operator== (const QMap< Key, T > &other) const
Returns true if other is equal to this map; otherwise returns false.
T & operator[] (const Key &key)
Returns the value associated with the key key as a modifiable reference.
const T operator[] (const Key &key) const
Same as value().
QMap ()
Constructs an empty map.
QMap (const QMap< Key, T > &other)
Constructs a copy of other.
QMap (const typename std::map< Key, T > &other)
int remove (const Key &key)
Removes all the items that have the key key from the map.
void setInsertInOrder (bool ordered)
void setSharable (bool sharable)
int size () const
Returns the number of (key, value) pairs in the map.
void swap (QMap< Key, T > &other)
Swaps map other with this map.
T take (const Key &key)
Removes the item with the key key from the map and returns the value associated with it.
std::map< Key, T > toStdMap () const
Returns an STL map equivalent to this QMap.
QList< Key > uniqueKeys () const
Returns a list containing all the keys in the map in ascending order.
QMap< Key, T > & unite (const QMap< Key, T > &other)
Inserts all the items in the other map into this map.
iterator upperBound (const Key &key)
Returns an iterator pointing to the item that immediately follows the last item with key key in the map.
const_iterator upperBound (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
const T value (const Key &key) const
Returns the value associated with the key key.
const T value (const Key &key, const T &defaultValue) const
If the map contains no item with key key, the function returns defaultValue.
QList< T > values () const
Returns a list containing all the values in the map, in ascending order of their keys.
QList< T > values (const Key &key) const
Returns a list containing all the values associated with key key, from the most recently inserted to the least recently inserted one.
~QMap ()
Destroys the map.
Private Types
typedef QMapNode< Key, T > Node
typedef QMapPayloadNode< Key, T > PayloadNode
Private Functions
void detach_helper ()
QMapData::Node * findNode (const Key &key) const
void freeData (QMapData *d)
QMapData::Node * mutableFindNode (QMapData::Node *update[], const Key &key) const
QMapData::Node * node_create (QMapData *d, QMapData::Node *update[], const Key &key, const T &value)
Static Private Functions
static int alignment ()
static Node * concrete (QMapData::Node *node)
static int payload ()
Properties
union {
QMapData * d
QMapData::Node * e
};
Friends
class const_iterator
class iterator
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QMap< Key, T > &map)
Writes the map map to stream out.
QDataStream & operator>> (QDataStream &in, QMap< Key, T > &map)
Reads a map from stream in into map.
Detailed Description
template<class Key, class T>
class QMap< Key, T >
The QMap class is a template class that provides a skip-list-based dictionary.
Note
This class or function is reentrant.
QMap<Key, T> is one of Qt's generic container classes. It stores (key, value) pairs and provides fast lookup of the value associated with a key.
QMap and QHash provide very similar functionality. The differences are:
QHash provides faster lookups than QMap. (See Algorithmic Complexity for details.)
When iterating over a QHash, the items are arbitrarily ordered. With QMap, the items are always sorted by key.
The key type of a QHash must provide operator==() and a global qHash(Key) function. The key type of a QMap must provide operator<() specifying a total order.
Here's an example QMap with QString keys and int values:
QMap<QString, int> map;
To insert a (key, value) pair into the map, you can use operator[]():
map["one"] = 1;
map["three"] = 3;
map["seven"] = 7;
This inserts the following three (key, value) pairs into the QMap: ("one", 1), ("three", 3), and ("seven", 7). Another way to insert items into the map is to use insert():
map.insert("twelve", 12);
To look up a value, use operator[]() or value():
int num1 = map["thirteen"];
int num2 = map.value("thirteen");
If there is no item with the specified key in the map, these functions return a default-constructed value.
If you want to check whether the map contains a certain key, use contains():
int timeout = 30;
if (map.contains("TIMEOUT"))
    timeout = map.value("TIMEOUT");
There is also a value() overload that uses its second argument as a default value if there is no item with the specified key:
int timeout = map.value("TIMEOUT", 30);
In general, we recommend that you use contains() and value() rather than operator[]() for looking up a key in a map. The reason is that operator[]() silently inserts an item into the map if no item exists with the same key (unless the map is const). For example, the following code snippet will create 1000 items in memory:
// WRONG
QMap<int, QWidget *> map;
...
for (int i = 0; i < 1000; ++i) {
    if (map[i] == okButton)
        cout << "Found button at index " << i << endl;
}
To avoid this problem, replace map[i] with map.value(i) in the code above.
If you want to navigate through all the (key, value) pairs stored in a QMap, you can use an iterator. QMap provides both Java-style iterators (QMapIterator and QMutableMapIterator) and STL-style iterators (QMap::const_iterator and QMap::iterator). Here's how to iterate over a QMap<QString, int> using a Java-style iterator:
QMapIterator<QString, int> i(map);
while (i.hasNext()) {
    i.next();
    cout << i.key() << ": " << i.value() << endl;
}
Here's the same code, but using an STL-style iterator this time:
QMap<QString, int>::const_iterator i = map.constBegin();
while (i != map.constEnd()) {
    cout << i.key() << ": " << i.value() << endl;
    ++i;
}
The items are traversed in ascending key order.
Normally, a QMap allows only one value per key. If you call insert() with a key that already exists in the QMap, the previous value will be erased. For example:
map.insert("plenty", 100);
map.insert("plenty", 2000);
// map.value("plenty") == 2000
However, you can store multiple values per key by using insertMulti() instead of insert() (or using the convenience subclass QMultiMap). If you want to retrieve all the values for a single key, you can use values(const Key &key), which returns a QList<T>:
QList<int> values = map.values("plenty");
for (int i = 0; i < values.size(); ++i)
    cout << values.at(i) << endl;
The items that share the same key are available from most recently to least recently inserted. Another approach is to call find() to get the STL-style iterator for the first item with a key and iterate from there:
QMap<QString, int>::iterator i = map.find("plenty");
while (i != map.end() && i.key() == "plenty") {
    cout << i.value() << endl;
    ++i;
}
If you only need to extract the values from a map (not the keys), you can also use foreach:
QMap<QString, int> map;
...
foreach (int value, map)
    cout << value << endl;
Items can be removed from the map in several ways. One way is to call remove(); this will remove any item with the given key. Another way is to use QMutableMapIterator::remove(). In addition, you can clear the entire map using clear().
QMap's key and value data types must be assignable data types. This covers most data types you are likely to encounter, but the compiler won't let you, for example, store a QWidget as a value; instead, store a QWidget *. In addition, QMap's key type must provide operator<(). QMap uses it to keep its items sorted, and assumes that two keys x and y are equal if neither x < y nor y < x is true.
Example:
#ifndef EMPLOYEE_H
#define EMPLOYEE_H
class Employee
{
public:
    Employee() {}
    Employee(const QString &name, const QDate &dateOfBirth);
    ...
private:
    QString myName;
    QDate myDateOfBirth;
};
inline bool operator<(const Employee &e1, const Employee &e2)
{
    if (e1.name() != e2.name())
        return e1.name() < e2.name();
    return e1.dateOfBirth() < e2.dateOfBirth();
}
#endif // EMPLOYEE_H
In the example, we start by comparing the employees' names. If they're equal, we compare their dates of birth to break the tie.
See also
QMapIterator, QMutableMapIterator, QHash, QSet
Definition at line 67 of file qdatastream.h.
Typedefs
ConstIterator
template<class Key, class T> QMap< Key, T >::ConstIterator
Qt-style synonym for QMap::const_iterator.
Definition at line 389 of file qmap.h.
difference_type
template<class Key, class T> QMap< Key, T >::difference_type
Typedef for ptrdiff_t.
Provided for STL compatibility.
Definition at line 411 of file qmap.h.
Iterator
template<class Key, class T> QMap< Key, T >::Iterator
Qt-style synonym for QMap::iterator.
Definition at line 388 of file qmap.h.
key_type
template<class Key, class T> QMap< Key, T >::key_type
Typedef for Key.
Provided for STL compatibility.
Definition at line 409 of file qmap.h.
mapped_type
template<class Key, class T> QMap< Key, T >::mapped_type
Typedef for T.
Provided for STL compatibility.
Definition at line 410 of file qmap.h.
Node
template<class Key, class T> typedef QMapNode<Key, T> QMap< Key, T >::Node private
Definition at line 161 of file qmap.h.
PayloadNode
template<class Key, class T> typedef QMapPayloadNode<Key, T> QMap< Key, T >::PayloadNode private
Definition at line 162 of file qmap.h.
size_type
template<class Key, class T> QMap< Key, T >::size_type
Typedef for int.
Provided for STL compatibility.
Definition at line 412 of file qmap.h.
Constructors and Destructors
QMap() [1/3]
template<class Key, class T> QMap< Key, T >::QMap () inline
Constructs an empty map.
See also
clear()
Definition at line 182 of file qmap.h.
Referenced by QMap< int, QFrameInfo >::operator==().
 : d(&QMapData::shared_null) { d->ref.ref(); }
QMap() [2/3]
template<class Key, class T> QMap< Key, T >::QMap (const QMap< Key, T > & other) inline
Constructs a copy of other.
This operation occurs in constant time, because QMap is implicitly shared. This makes returning a QMap from a function very fast. If a shared instance is modified, it will be copied (copy-on-write), and this takes linear time.
See also
operator=()
Definition at line 183 of file qmap.h.
                                            : d(other.d)
     { d->ref.ref(); if (!d->sharable) detach(); }
~QMap()
template<class Key, class T> QMap< Key, T >::~QMap () inline
Destroys the map.
References to the values in the map, and all iterators over this map, become invalid.
Definition at line 185 of file qmap.h.
 { if (!d) return; if (!d->ref.deref()) freeData(d); }
QMap() [3/3]
template<class Key, class T> QMap< Key, T >::QMap (const typename std::map< Key, T > & other) explicit
Functions
alignment()
template<class Key, class T> static int QMap< Key, T >::alignment () inline static private
Definition at line 170 of file qmap.h.
{
 #ifdef Q_ALIGNOF
         return int(qMax(sizeof(void*), Q_ALIGNOF(Node)));
 #else
         return 0;
 #endif
     }
begin() [1/2]
template<class Key, class T> QMap::iterator QMap< Key, T >::begin () inline
Returns an STL-style iterator pointing to the first item in the map.
See also
constBegin(), end()
Definition at line 372 of file qmap.h.
Referenced by QWizardPrivate::_q_handleFieldObjectDestroyed(), QSpanCollection::addSpan(), QSpanCollection::cleanSpanSubIndex(), QWindowsXPStylePrivate::cleanupHandleMap(), QFontCache::cleanupPrinterFonts(), QTextDocumentPrivate::clear(), QFontCache::clear(), QAbstractItemViewPrivate::clearOrRemove(), QAbstractItemViewPrivate::delegateRefCount(), QCopChannel::detach(), QConfFileSettingsPrivate::ensureSectionParsed(), formatDifference(), QConfFile::mergedKeyMap(), MetaObjectGenerator::metaObject(), QString::multiArg(), operator<<(), QMap< int, QFrameInfo >::operator==(), QRegExpEngine::parse(), QTessellatorPrivate::processIntersections(), qt_transparent_pixel(), qt_xclb_incr_timeout(), QGraphicsScenePrivate::removeItemHelper(), QCopChannel::reregisterAll(), QCompletionEngine::saveInCache(), QStandardItemPrivate::setItemData(), QAbstractItemModel::setItemData(), QSpanCollection::spansInRect(), QFontCache::timerEvent(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), QSpanCollection::updateSpan(), write_xpm_image(), and QAxServerBase::~QAxServerBase().
 { detach(); return iterator(e->forward[0]); }
begin() [2/2]
template<class Key, class T> QMap::const_iterator QMap< Key, T >::begin () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 373 of file qmap.h.
 { return const_iterator(e->forward[0]); }
clear()
template<class Key , class T > Q_INLINE_TEMPLATE void QMap< Key, T >::clear ()
Removes all items from the map.
See also
remove()
Definition at line 444 of file qmap.h.
Referenced by classIDL(), QSqlTableModelPrivate::clear(), QSpanCollection::clear(), QTextDocumentPrivate::clear(), QFontCache::clear(), QConfFileSettingsPrivate::clear(), QSqlTableModelPrivate::clearCache(), QTextDocument::clone(), QIBaseDriver::close(), QConfFileSettingsPrivate::ensureAllSectionsParsed(), QScanThread::getUserConfigurations(), QXmlSimpleReaderPrivate::init(), QCompletionModel::invalidate(), operator>>(), QAxServerBase::removeMenu(), QMoviePrivate::reset(), QImageReader::setDevice(), QConfFileSettingsPrivate::syncConfFile(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), and QTest::QTouchEventSequence::~QTouchEventSequence().
 {
     *this = QMap<Key, T>();
 }
concrete()
template<class Key, class T> static Node* QMap< Key, T >::concrete (QMapData::Node * node) inline static private
Definition at line 177 of file qmap.h.
{
         return reinterpret_cast<Node *>(reinterpret_cast<char *>(node) - payload());
     }
constBegin()
template<class Key, class T> QMap::const_iterator QMap< Key, T >::constBegin () const inline
Returns a const STL-style iterator pointing to the first item in the map.
See also
begin(), constEnd()
Definition at line 374 of file qmap.h.
Referenced by QScriptDebuggerScriptsModel::addExtraScriptInfo(), QTessellatorPrivate::addIntersections(), QAxEventSink::addSignal(), breakpointMapToScriptValue(), QIBaseDriver::close(), compare(), consoleCommandGroupMapToScriptValue(), QDBusMetaObject::createMetaObject(), QConfFileSettingsPrivate::ensureAllSectionsParsed(), QNetworkDiskCache::expire(), QTextHtmlExporter::findUrlForImage(), QMdiSubWindowPrivate::getOperation(), QScriptCompleteScriptsJob::handleResponse(), QSortedModelEngine::indexHint(), QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(), macValue(), mergeKeySets(), QWizardPage::nextId(), QScriptEnginePrivate::objectFromVariantMap(), operator+=(), operator<<(), operator>>(), QRegExpEngine::parse(), QDBusIntrospection::parseInterface(), QDBusMetaObjectGenerator::parseMethods(), QDBusMetaObjectGenerator::parseProperties(), QDBusMetaObjectGenerator::parseSignals(), QXmlSimpleReaderPrivate::processElementETagBegin2(), QIBaseDriver::qHandleEventNotification(), scriptMapToScriptValue(), set_text(), QTableModel::setItemData(), QCss::StyleSelector::styleRulesForNode(), QConfFileSettingsPrivate::syncConfFile(), QFontCache::timerEvent(), QApplicationPrivate::translateRawTouchEvent(), QMap< int, QFrameInfo >::unite(), QConfFileSettingsPrivate::writeIniFile(), QConfFileSettingsPrivate::writePlistFile(), and QFontCache::~QFontCache().
 { return const_iterator(e->forward[0]); }
constEnd()
template<class Key, class T> QMap::const_iterator QMap< Key, T >::constEnd () const inline
Returns a const STL-style iterator pointing to the imaginary item after the last item in the map.
See also
constBegin(), end()
Definition at line 380 of file qmap.h.
Referenced by QScriptDebuggerScriptsModel::addExtraScriptInfo(), QAxEventSink::addSignal(), QWidgetAnimator::animate(), breakpointMapToScriptValue(), QIBaseDriver::close(), compare(), consoleCommandGroupMapToScriptValue(), QMultiMap< QString, Method >::contains(), QDBusMetaObject::createMetaObject(), QConfFileSettingsPrivate::ensureAllSectionsParsed(), QNetworkDiskCache::expire(), QTextHtmlExporter::findUrlForImage(), QMdiSubWindowPrivate::getOperation(), QScriptCompleteScriptsJob::handleResponse(), QSortedModelEngine::indexHint(), QWSServerPrivate::invokeScreenTransform(), QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(), macValue(), mergeKeySets(), QWizardPage::nextId(), QScriptEnginePrivate::objectFromVariantMap(), operator+=(), operator<<(), operator>>(), QRegExpEngine::parse(), QDBusMetaObjectGenerator::parseMethods(), QDBusMetaObjectGenerator::parseProperties(), QDBusMetaObjectGenerator::parseSignals(), QXmlSimpleReaderPrivate::processElementETagBegin2(), QIBaseDriver::qHandleEventNotification(), QConfFileSettingsPrivate::remove(), scriptMapToScriptValue(), QWSServerPrivate::sendFontRemovedEvent(), QWSServerPrivate::sendMaxWindowRectEvents(), set_text(), QTableModel::setItemData(), QCss::StyleSelector::styleRulesForNode(), QConfFileSettingsPrivate::syncConfFile(), QFontCache::timerEvent(), QMap< int, QFrameInfo >::unite(), QConfFileSettingsPrivate::writeIniFile(), QConfFileSettingsPrivate::writePlistFile(), and QFontCache::~QFontCache().
 { return const_iterator(e); }
constFind()
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::const_iterator QMap< Key, T >::constFind (const Key & key) const
Returns an const iterator pointing to the item with key key in the map.
Since
4.1
If the map contains no item with key key, the function returns constEnd().
See also
find(), QMultiMap::constFind()
Definition at line 612 of file qmap.h.
Referenced by QWidgetAnimator::animate(), QMultiMap< QString, Method >::operator+(), and QConfFileSettingsPrivate::writeIniFile().
 {
     return const_iterator(findNode(akey));
 }
contains()
template<class Key, class T > Q_INLINE_TEMPLATE bool QMap< Key, T >::contains (const Key & key) const
Returns true if the map contains an item with key key; otherwise returns false.
See also
count(), QMultiMap::contains()
Definition at line 553 of file qmap.h.
Referenced by QRegExpEngine::addAnchors(), QRegExpEngine::addPlusTransitions(), QCopChannel::answer(), QGraphicsScenePrivate::cancelGesturesForChildren(), QBuiltInMimes::canConvertFromMime(), QXlibCursor::changeCursor(), QGraphicsItem::data(), QDragManager::dragCursor(), QGestureManager::filterEvent(), QCalendarModel::formatForCell(), QOfonoManagerInterface::getProperty(), QConnmanManagerInterface::getProperty(), QOfonoModemInterface::getProperty(), QConnmanProfileInterface::getProperty(), QOfonoNetworkRegistrationInterface::getProperty(), QOfonoNetworkOperatorInterface::getProperty(), QConnmanServiceInterface::getProperty(), QOfonoSimInterface::getProperty(), QConnmanTechnologyInterface::getProperty(), QOfonoDataConnectionManagerInterface::getProperty(), QOfonoPrimaryDataContextInterface::getProperty(), QOfonoSmsInterface::getProperty(), QScanThread::getUserConfigurations(), QGraphicsObject::grabGesture(), MetaObjectGenerator::hasClassInfo(), MetaObjectGenerator::hasEnum(), QGenericEngine::hasIdentifier(), QCoreWlanEngine::hasIdentifier(), QNlaEngine::hasIdentifier(), MetaObjectGenerator::hasProperty(), MetaObjectGenerator::hasSignal(), MetaObjectGenerator::hasSlot(), QCompletionEngine::lookupCache(), QCompletionEngine::matchHint(), QMultiMap< QString, Method >::operator+(), QTest::QTouchEventSequence::point(), QXmlSimpleReaderPrivate::processElementETagBegin2(), QConnmanEngine::propertyChangedContext(), QConfFileSettingsPrivate::remove(), renameOverloads(), QScanThread::run(), QIBaseDriver::subscribeToNotificationImplementation(), QApplicationPrivate::translateRawTouchEvent(), QIBaseDriver::unsubscribeFromNotificationImplementation(), and write_xpm_image().
 {
     return findNode(akey) != e;
 }
count() [1/2]
template<class Key, class T > Q_INLINE_TEMPLATE int QMap< Key, T >::count (const Key & key) const
Returns the number of items associated with key key.
See also
contains(), insertMulti(), QMultiMap::count()
Definition at line 539 of file qmap.h.
Referenced by compare(), QXmlSimpleReaderPrivate::insertXmlRef(), MetaObjectGenerator::metaObject(), QCompletionEngine::saveInCache(), and QCss::StyleSelector::styleRulesForNode().
 {
     int cnt = 0;
     QMapData::Node *node = findNode(akey);
     if (node != e) {
         do {
             ++cnt;
             node = node->forward[0];
         } while (node != e && !qMapLessThanKey<Key>(akey, concrete(node)->key));
     }
     return cnt;
 }
count() [2/2]
template<class Key, class T> int QMap< Key, T >::count () const inline
Same as size().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 390 of file qmap.h.
Referenced by QMultiMap< QString, Method >::operator+().
 { return d->size; }
detach()
template<class Key, class T> void QMap< Key, T >::detach () inline
Detaches this map from any other maps with which it may share data.
Warning
This function is not part of the public interface.
See also
isDetached()
Definition at line 205 of file qmap.h.
Referenced by operator>>().
 { if (d->ref != 1) detach_helper(); }
detach_helper()
template<class Key , class T > Q_OUTOFLINE_TEMPLATE void QMap< Key, T >::detach_helper () private
Definition at line 752 of file qmap.h.
 {
     union { QMapData *d; QMapData::Node *e; } x;
     x.d = QMapData::createData(alignment());
     if (d->size) {
         x.d->insertInOrder = true;
         QMapData::Node *update[QMapData::LastLevel + 1];
         QMapData::Node *cur = e->forward[0];
         update[0] = x.e;
         while (cur != e) {
             QT_TRY {
                 Node *concreteNode = concrete(cur);
                 node_create(x.d, update, concreteNode->key, concreteNode->value);
             } QT_CATCH(...) {
                 freeData(x.d);
                 QT_RETHROW;
             }
             cur = cur->forward[0];
         }
         x.d->insertInOrder = false;
     }
     if (!d->ref.deref())
         freeData(d);
     d = x.d;
 }
empty()
template<class Key, class T> bool QMap< Key, T >::empty () const inline
This function is provided for STL compatibility.
It is equivalent to isEmpty(), returning true if the map is empty; otherwise returning false.
Definition at line 413 of file qmap.h.
 { return isEmpty(); }
end() [1/2]
template<class Key, class T> QMap::iterator QMap< Key, T >::end () inline
Returns an STL-style iterator pointing to the imaginary item after the last item in the map.
See also
begin(), constEnd()
Definition at line 375 of file qmap.h.
Referenced by QWizardPrivate::_q_handleFieldObjectDestroyed(), QWidgetAnimator::abort(), QSpanCollection::addSpan(), QCopChannel::answer(), QSpanCollection::cleanSpanSubIndex(), QWSServerPrivate::cleanupFonts(), QWindowsXPStylePrivate::cleanupHandleMap(), QFontCache::cleanupPrinterFonts(), QTextDocumentPrivate::clear(), QFontCache::clear(), QAbstractItemViewPrivate::clearOrRemove(), QAbstractItemViewPrivate::delegateForIndex(), QAbstractItemViewPrivate::delegateRefCount(), QCopChannel::detach(), QConfFileSettingsPrivate::ensureSectionParsed(), QXmlSimpleReaderPrivate::entityExist(), QFontCache::findEngine(), QFontCache::findEngineData(), formatDifference(), QCopChannel::init(), QWSServerPrivate::invokeSelectCursor(), QConfFile::mergedKeyMap(), MetaObjectGenerator::metaObject(), QString::multiArg(), QApplication::notify(), operator<<(), QRegExpEngine::parse(), QXmlSimpleReaderPrivate::parsePEReference(), QTessellatorPrivate::processIntersections(), QXmlSimpleReaderPrivate::processReference(), qt_transparent_pixel(), qt_x11_incr_event_filter(), QCopChannel::registerChannel(), QConfFileSettingsPrivate::remove(), QGraphicsScenePrivate::removeItemHelper(), QCopChannel::reregisterAll(), QSqlTableModelPrivate::revertCachedRow(), QCompletionEngine::saveInCache(), QStandardItemPrivate::setItemData(), QAbstractItemModel::setItemData(), QSpanCollection::spanAt(), QSpanCollection::spansInRect(), QFontCache::timerEvent(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), QSpanCollection::updateSpan(), write_xpm_image(), QAxServerBase::~QAxServerBase(), and QCopChannel::~QCopChannel().
{
         detach();
         return iterator(e);
     }
end() [2/2]
template<class Key, class T> QMap::const_iterator QMap< Key, T >::end () const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 379 of file qmap.h.
 { return const_iterator(e); }
erase()
template<class Key , class T > Q_OUTOFLINE_TEMPLATE QMap< Key, T >::iterator QMap< Key, T >::erase (iterator pos)
Removes the (key, value) pair pointed to by the iterator pos from the map, and returns an iterator to the next item in the map.
Use remove(key) instead.
See also
remove()
Definition at line 717 of file qmap.h.
Referenced by QWidgetAnimator::abort(), QCopChannel::answer(), QSpanCollection::cleanSpanSubIndex(), QWSServerPrivate::cleanupFonts(), QFontCache::cleanupPrinterFonts(), QTextDocumentPrivate::clear(), QConfFileSettingsPrivate::ensureSectionParsed(), QRegExpEngine::parse(), QConfFileSettingsPrivate::remove(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsScenePrivate::removeSceneEventFilter(), QSqlTableModelPrivate::revertCachedRow(), QCompletionEngine::saveInCache(), QFontCache::timerEvent(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), and QSpanCollection::updateSpan().
 {
     QMapData::Node *update[QMapData::LastLevel + 1];
     QMapData::Node *cur = e;
     QMapData::Node *next = e;
     if (it == iterator(e))
         return it;
     for (int i = d->topLevel; i >= 0; i--) {
         while ((next = cur->forward[i]) != e && qMapLessThanKey<Key>(concrete(next)->key, it.key()))
             cur = next;
         update[i] = cur;
     }
     while (next != e) {
         cur = next;
         next = cur->forward[0];
         if (cur == it) {
             concrete(cur)->key.~Key();
             concrete(cur)->value.~T();
             d->node_delete(update, payload(), cur);
             return iterator(next);
         }
         for (int i = 0; i <= d->topLevel; ++i) {
             if (update[i]->forward[i] != cur)
                 break;
             update[i] = cur;
         }
     }
     return end();
 }
find() [1/2]
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::iterator QMap< Key, T >::find (const Key & key)
Returns an iterator pointing to the item with key key in the map.
If the map contains no item with key key, the function returns end().
If the map contains multiple items with key key, this function returns an iterator that points to the most recently inserted value. The other values are accessible by incrementing the iterator. For example, here's some code that iterates over all the items with the same key:
QMap<QString, int> map;
...
QMap<QString, int>::const_iterator i = map.find("HDR");
while (i != map.end() && i.key() == "HDR") {
    cout << i.value() << endl;
    ++i;
}
See also
constFind(), value(), values(), lowerBound(), upperBound(), QMultiMap::find()
Definition at line 618 of file qmap.h.
Referenced by QWidgetAnimator::abort(), QCopChannel::answer(), QAbstractItemViewPrivate::delegateForIndex(), QXmlSimpleReaderPrivate::entityExist(), QFontCache::findEngine(), QFontCache::findEngineData(), QCopChannel::init(), QWSServerPrivate::invokeSelectCursor(), QApplication::notify(), QMultiMap< QString, Method >::operator+(), QXmlSimpleReaderPrivate::parsePEReference(), QTessellatorPrivate::processIntersections(), QXmlSimpleReaderPrivate::processReference(), qt_x11_incr_event_filter(), QCopChannel::registerChannel(), QSqlTableModelPrivate::revertCachedRow(), QMdiSubWindowPrivate::setNewGeometry(), QMdiSubWindowPrivate::updateCursor(), QMdiSubWindowPrivate::updateDirtyRegions(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), and QCopChannel::~QCopChannel().
 {
     detach();
     return iterator(findNode(akey));
 }
find() [2/2]
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::const_iterator QMap< Key, T >::find (const Key & key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 606 of file qmap.h.
 {
     return const_iterator(findNode(akey));
 }
findNode()
template<class Key, class T > Q_INLINE_TEMPLATE QMapData::Node * QMap< Key, T >::findNode (const Key & key) const private
Definition at line 481 of file qmap.h.
 {
     QMapData::Node *cur = e;
     QMapData::Node *next = e;
     for (int i = d->topLevel; i >= 0; i--) {
         while ((next = cur->forward[i]) != e && qMapLessThanKey<Key>(concrete(next)->key, akey))
             cur = next;
     }
     if (next != e && !qMapLessThanKey<Key>(akey, concrete(next)->key)) {
         return next;
     } else {
         return e;
     }
 }
freeData()
template<class Key , class T > Q_OUTOFLINE_TEMPLATE void QMap< Key, T >::freeData (QMapData * d) private
Definition at line 642 of file qmap.h.
 {
     if (QTypeInfo<Key>::isComplex || QTypeInfo<T>::isComplex) {
         QMapData *cur = x;
         QMapData *next = cur->forward[0];
         while (next != x) {
             cur = next;
             next = cur->forward[0];
             Node *concreteNode = concrete(reinterpret_cast<QMapData::Node *>(cur));
             concreteNode->key.~Key();
             concreteNode->value.~T();
         }
     }
     x->continueFreeData(payload());
 }
insert()
template<class Key, class T> Q_INLINE_TEMPLATE QMap< Key, T >::iterator QMap< Key, T >::insert (const Key & key, const T & value)
Inserts a new item with the key key and a value of value.
Use the two-argument insert() overload instead.
If there is already an item with the key key, that item's value is replaced with value.
If there are multiple items with the key key, the most recently inserted item's value is replaced with value.
See also
insertMulti()
If you don't want to overwrite, call contains() beforehand.
QMap<QString, int> map; ... map.insert("delay", 30000, false); QMap<QString, int> map; ... if (!map.contains("delay")) map.insert("delay", 30000);
Definition at line 559 of file qmap.h.
Referenced by QRegExpEngine::addAnchors(), QTessellatorPrivate::addIntersection(), QRegExpEngine::addPlusTransitions(), QAxEventSink::addProperty(), QDir::addResourceSearchPath(), QAxEventSink::addSignal(), QSpanCollection::addSpan(), allKeys(), QScriptObjectSnapshot::capture(), QRegExpEngine::Box::cat(), QRegExpEngine::Box::catAnchor(), QXlibCursor::changeCursor(), QSpanCollection::cleanSpanSubIndex(), ControlList::ControlList(), QTextCopyHelper::convertFormatIndex(), QMacPasteboardMimeVCard::convertFromMime(), QAxServerBase::createMenu(), QAxServerBase::createPopup(), QGenericEngine::doRequestUpdate(), QGraphicsScenePrivate::drawSubtreeRecursive(), QtopiaPrintEngine::end(), QGestureManager::filterEvent(), QLastResortMimes::formatsForMime(), QScanThread::foundNetwork(), QImageReaderPrivate::getText(), QScanThread::getUserConfigurations(), QGraphicsObject::grabGesture(), QCopChannel::init(), QMdiSubWindowPrivate::initOperationMap(), QMap< int, QFrameInfo >::insert(), QFontCache::insertEngine(), QFontCache::insertEngineData(), QComboBox::insertItem(), QDBusXmlParser::interfaces(), QWSServerPrivate::invokeDefineCursor(), QListModel::itemData(), QTreeModel::itemData(), QStandardItemPrivate::itemData(), QTableModel::itemData(), QAbstractItemModel::itemData(), mdiAreaNavigate(), QConfFile::mergedKeyMap(), mergeKeySets(), MetaObjectGenerator::metaObject(), QString::multiArg(), QAudioDeviceInfo::nearestFormat(), QDBusXmlParser::objectTree(), operator+=(), QGraphicsView::paintEvent(), QScriptXmlParser::parse(), parseAnnotations(), QXmlSimpleReaderPrivate::parseEntityDecl(), QSettingsPrivate::processChild(), QTextFormat::properties(), QAxBase::propertyBag(), QConnmanEngine::propertyChangedContext(), QBuiltInMimes::QBuiltInMimes(), QClipboardINCRTransaction::QClipboardINCRTransaction(), QDirectPainter::QDirectPainter(), QLibraryPrivate::QLibraryPrivate(), qt_transparent_pixel(), read_xpm_body(), readAllProperties(), QConfFileSettingsPrivate::readIniSection(), QConfFileSettingsPrivate::readPlistFile(), QCopChannel::registerChannel(), QConfFileSettingsPrivate::remove(), renameOverloads(), QMultiMap< QString, Method >::replace(), QSqlTableModelPrivate::revertCachedRow(), QScriptDebuggerScriptsModel::scripts(), QConfFileSettingsPrivate::set(), set_text(), QGtkStylePrivate::setupGtkFileChooser(), QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber(), QIBaseDriver::subscribeToNotificationImplementation(), QConfFileSettingsPrivate::syncConfFile(), QApplicationPrivate::translateRawTouchEvent(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateInsertedRows(), QSpanCollection::updateRemovedRows(), QDeclarativeEngineDebugService::valueContents(), QScriptEnginePrivate::variantMapFromObject(), and write_xpm_image().
 {
     detach();
     QMapData::Node *update[QMapData::LastLevel + 1];
     QMapData::Node *node = mutableFindNode(update, akey);
     if (node == e) {
         node = node_create(d, update, akey, avalue);
     } else {
         concrete(node)->value = avalue;
     }
     return iterator(node);
 }
insertMulti()
template<class Key, class T> Q_INLINE_TEMPLATE QMap< Key, T >::iterator QMap< Key, T >::insertMulti (const Key & key, const T & value)
Inserts a new item with the key key and a value of value.
If there is already an item with the same key in the map, this function will simply create a new one. (This behavior is different from insert(), which overwrites the value of an existing item.)
See also
insert(), values()
Definition at line 595 of file qmap.h.
Referenced by QGestureManager::filterEvent(), QMultiMap< QString, Method >::insert(), QCss::StyleSelector::matchRule(), operator>>(), and QGestureManager::registerGestureRecognizer().
 {
     detach();
     QMapData::Node *update[QMapData::LastLevel + 1];
     mutableFindNode(update, akey);
     return iterator(node_create(d, update, akey, avalue));
 }
isDetached()
template<class Key, class T> bool QMap< Key, T >::isDetached () const inline
Returns true if the map's internal data isn't shared with any other map object; otherwise returns false.
Warning
This function is not part of the public interface.
See also
detach()
Definition at line 206 of file qmap.h.
 { return d->ref == 1; }
isEmpty()
template<class Key, class T> bool QMap< Key, T >::isEmpty () const inline
Returns true if the map contains no items; otherwise returns false.
See also
size()
Definition at line 203 of file qmap.h.
Referenced by QWidgetAnimator::animating(), QSpanCollection::cleanSpanSubIndex(), QDBusMetaObject::createMetaObject(), QConfFileSettingsPrivate::ensureSectionParsed(), QScriptDebuggerCommandExecutor::execute(), QGestureManager::filterEvent(), QImageReaderPrivate::getText(), QDragManager::hasCustomDragCursors(), QComboBox::insertItem(), QSslCertificate::issuerInfo(), QGraphicsItem::mouseMoveEvent(), QRegExpEngine::parse(), QDBusIntrospection::parseInterface(), QTessellatorPrivate::processIntersections(), MetaObjectGenerator::readEnumInfo(), set_text(), QSslCertificate::subjectInfo(), QConfFileSettingsPrivate::syncConfFile(), QApplicationPrivate::translateRawTouchEvent(), QClipboardINCRTransaction::~QClipboardINCRTransaction(), and QGraphicsItem::~QGraphicsItem().
 { return d->size == 0; }
isSharedWith()
template<class Key, class T> bool QMap< Key, T >::isSharedWith (const QMap< Key, T > & other) const inline
Warning
This function is not part of the public interface.
Definition at line 208 of file qmap.h.
 { return d == other.d; }
key() [1/2]
template<class Key , class T> Q_OUTOFLINE_TEMPLATE const Key QMap< Key, T >::key (const T & value) const
Returns the first key with value value.
If the map contains no item with value value, the function returns a default-constructed key.
This function can be slow (linear time), because QMap's internal data structure is optimized for fast lookup by key, not by value.
See also
value(), keys()
Definition at line 844 of file qmap.h.
Referenced by QWizardPrivate::_q_handleFieldObjectDestroyed(), QScriptDebuggerScriptsModel::addExtraScriptInfo(), QAxEventSink::addSignal(), QBuiltInMimes::canConvertToMime(), QGestureManager::cleanupCachedGestures(), QWSServerPrivate::cleanupFonts(), QBuiltInMimes::convertToMime(), QTextHtmlExporter::findUrlForImage(), QBuiltInMimes::formatsForMime(), macValue(), QString::multiArg(), set_text(), and QGestureManager::unregisterGestureRecognizer().
 {
     return key(avalue, Key());
 }
key() [2/2]
template<class Key, class T> Q_OUTOFLINE_TEMPLATE const Key QMap< Key, T >::key (const T & value, const Key & defaultKey) const
Returns the first key with value value, or defaultKey if the map contains no item with value value.
Since
4.3 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function can be slow (linear time), because QMap's internal data structure is optimized for fast lookup by key, not by value.
Definition at line 850 of file qmap.h.
 {
     const_iterator i = begin();
     while (i != end()) {
         if (i.value() == avalue)
             return i.key();
         ++i;
     }
     return defaultKey;
 }
keys() [1/2]
template<class Key , class T > Q_OUTOFLINE_TEMPLATE QList< Key > QMap< Key, T >::keys () const
Returns a list containing all the keys in the map in ascending order.
Keys that occur multiple times in the map (because items were inserted with insertMulti(), or unite() was used) also occur multiple times in the list.
To obtain a list of unique keys, where each key from the map only occurs once, use uniqueKeys().
The order is guaranteed to be the same as that used by values().
See also
uniqueKeys(), values(), key()
Definition at line 818 of file qmap.h.
Referenced by QGraphicsScene::addItem(), QAccessibleTextWidget::attributes(), QBuiltInMimes::canConvertToMime(), QScriptObjectSnapshot::capture(), QConfFileSettingsPrivate::children(), QMacSettingsPrivate::children(), QWinSettingsPrivate::children(), QBuiltInMimes::formatsForMime(), QScanThread::isKnownSsid(), QDBusXmlParser::objectTree(), QGraphicsScenePrivate::removeItemHelper(), QIBaseDriver::subscribedToNotificationsImplementation(), QImageReader::textKeys(), QMdiSubWindowPrivate::updateDirtyRegions(), and QGraphicsItem::~QGraphicsItem().
 {
     QList<Key> res;
     res.reserve(size());
     const_iterator i = begin();
     while (i != end()) {
         res.append(i.key());
         ++i;
     }
     return res;
 }
keys() [2/2]
template<class Key , class T> Q_OUTOFLINE_TEMPLATE QList< Key > QMap< Key, T >::keys (const T & value) const
Returns a list containing all the keys associated with value value in ascending order.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function can be slow (linear time), because QMap's internal data structure is optimized for fast lookup by key, not by value.
Definition at line 831 of file qmap.h.
 {
     QList<Key> res;
     const_iterator i = begin();
     while (i != end()) {
         if (i.value() == avalue)
             res.append(i.key());
         ++i;
     }
     return res;
 }
lowerBound() [1/2]
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::iterator QMap< Key, T >::lowerBound (const Key & key)
Returns an iterator pointing to the first item with key key in the map.
If the map contains no item with key key, the function returns an iterator to the nearest item with a greater key.
Example:
QMap<int, QString> map;
map.insert(1, "one");
map.insert(5, "five");
map.insert(10, "ten");
map.lowerBound(0);      // returns iterator to (1, "one")
map.lowerBound(1);      // returns iterator to (1, "one")
map.lowerBound(2);      // returns iterator to (5, "five")
map.lowerBound(10);     // returns iterator to (10, "ten")
map.lowerBound(999);    // returns end()
If the map contains multiple items with key key, this function returns an iterator that points to the most recently inserted value. The other values are accessible by incrementing the iterator. For example, here's some code that iterates over all the items with the same key:
QMap<QString, int> map;
...
QMap<QString, int>::const_iterator i = map.lowerBound("HDR");
QMap<QString, int>::const_iterator upperBound = map.upperBound("HDR");
while (i != upperBound) {
    cout << i.value() << endl;
    ++i;
}
See also
qLowerBound(), upperBound(), find()
Definition at line 899 of file qmap.h.
Referenced by QSpanCollection::addSpan(), QGraphicsScenePrivate::filterEvent(), QGestureManager::filterEventThroughContexts(), QSortedModelEngine::indexHint(), QConfFileSettingsPrivate::remove(), QGraphicsScenePrivate::removeSceneEventFilter(), QSpanCollection::spanAt(), QSpanCollection::spansInRect(), and QSpanCollection::updateSpan().
 {
     detach();
     return static_cast<QMapData::Node *>(const_cast<const QMap *>(this)->lowerBound(akey));
 }
lowerBound() [2/2]
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::const_iterator QMap< Key, T >::lowerBound (const Key & key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 891 of file qmap.h.
 {
     QMapData::Node *update[QMapData::LastLevel + 1];
     mutableFindNode(update, akey);
     return const_iterator(update[0]->forward[0]);
 }
mutableFindNode()
template<class Key, class T > Q_OUTOFLINE_TEMPLATE QMapData::Node * QMap< Key, T >::mutableFindNode (QMapData::Node * update[], const Key & key) const private
Definition at line 779 of file qmap.h.
 {
     QMapData::Node *cur = e;
     QMapData::Node *next = e;
     for (int i = d->topLevel; i >= 0; i--) {
         while ((next = cur->forward[i]) != e && qMapLessThanKey<Key>(concrete(next)->key, akey))
             cur = next;
         aupdate[i] = cur;
     }
     if (next != e && !qMapLessThanKey<Key>(akey, concrete(next)->key)) {
         return next;
     } else {
         return e;
     }
 }
node_create()
template<class Key, class T> Q_INLINE_TEMPLATE QMapData::Node * QMap< Key, T >::node_create (QMapData * d, QMapData::Node * update[], const Key & key, const T & value) private
Definition at line 451 of file qmap.h.
 {
     QMapData::Node *abstractNode = adt->node_create(aupdate, payload(), alignment());
     QT_TRY {
         Node *concreteNode = concrete(abstractNode);
         new (&concreteNode->key) Key(akey);
         QT_TRY {
             new (&concreteNode->value) T(avalue);
         } QT_CATCH(...) {
             concreteNode->key.~Key();
             QT_RETHROW;
         }
     } QT_CATCH(...) {
         adt->node_delete(aupdate, payload(), abstractNode);
         QT_RETHROW;
     }
     // clean up the update array for further insertions
     /*
     for (int i = 0; i <= d->topLevel; ++i) {
         if ( aupdate[i]==reinterpret_cast<QMapData::Node *>(adt) || aupdate[i]->forward[i] != abstractNode)
             break;
         aupdate[i] = abstractNode;
     }
 */
     return abstractNode;
 }
operator!=()
template<class Key, class T> bool QMap< Key, T >::operator!= (const QMap< Key, T > & other) const inline
Returns true if other is not equal to this map; otherwise returns false.
Two maps are considered equal if they contain the same (key, value) pairs.
This function requires the value type to implement operator==().
See also
operator==()
Definition at line 199 of file qmap.h.
 { return !(*this == other); }
operator=()
template<class Key, class T> Q_INLINE_TEMPLATE QMap< Key, T > & QMap< Key, T >::operator= (const QMap< Key, T > & other)
Assigns other to this map and returns a reference to this map.
Definition at line 429 of file qmap.h.
 {
     if (d != other.d) {
         QMapData* o = other.d;
         o->ref.ref();
         if (!d->ref.deref())
             freeData(d);
         d = o;
         if (!d->sharable)
             detach_helper();
     }
     return *this;
 }
operator==()
template<class Key, class T> Q_OUTOFLINE_TEMPLATE bool QMap< Key, T >::operator== (const QMap< Key, T > & other) const
Returns true if other is equal to this map; otherwise returns false.
Two maps are considered equal if they contain the same (key, value) pairs.
This function requires the value type to implement operator==().
See also
operator!=()
Definition at line 925 of file qmap.h.
 {
     if (size() != other.size())
         return false;
     if (d == other.d)
         return true;
     const_iterator it1 = begin();
     const_iterator it2 = other.begin();
     while (it1 != end()) {
         if (!(it1.value() == it2.value()) || qMapLessThanKey(it1.key(), it2.key()) || qMapLessThanKey(it2.key(), it1.key()))
             return false;
         ++it2;
         ++it1;
     }
     return true;
 }
operator[]() [1/2]
template<class Key, class T > Q_INLINE_TEMPLATE T & QMap< Key, T >::operator[] (const Key & key)
Returns the value associated with the key key as a modifiable reference.
If the map contains no item with key key, the function inserts a default-constructed value into the map with key key, and returns a reference to it. If the map contains multiple items with key key, this function returns a reference to the most recently inserted value.
See also
insert(), value()
Definition at line 527 of file qmap.h.
 {
     detach();
     QMapData::Node *update[QMapData::LastLevel + 1];
     QMapData::Node *node = mutableFindNode(update, akey);
     if (node == e)
         node = node_create(d, update, akey, T());
     return concrete(node)->value;
 }
operator[]() [2/2]
template<class Key, class T > Q_INLINE_TEMPLATE const T QMap< Key, T >::operator[] (const Key & key) const
Same as value().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 521 of file qmap.h.
 {
     return value(akey);
 }
payload()
template<class Key, class T> static int QMap< Key, T >::payload () inline static private
Definition at line 169 of file qmap.h.
 { return sizeof(PayloadNode) - sizeof(QMapData::Node *); }
remove()
template<class Key, class T > Q_OUTOFLINE_TEMPLATE int QMap< Key, T >::remove (const Key & key)
Removes all the items that have the key key from the map.
Use erase(it) instead.
Returns the number of items removed which is usually 1 but will be 0 if the key isn't in the map, or > 1 if insertMulti() has been used with the key.
See also
clear(), take(), QMultiMap::remove()
Definition at line 662 of file qmap.h.
Referenced by QDir::addResourceSearchPath(), QAxEventSink::addSignal(), QAxServerBase::createPopup(), QTextDocumentPrivate::deleteObject(), QGenericEngine::doRequestUpdate(), QConfFile::mergedKeyMap(), QMultiMap< QString, Method >::operator+(), QTessellatorPrivate::processIntersections(), QConfFileSettingsPrivate::remove(), QGraphicsScenePrivate::removeItemHelper(), QSqlTableModelPrivate::revertCachedRow(), QConfFileSettingsPrivate::set(), QIBaseDriver::subscribeToNotificationImplementation(), QConnmanEngine::technologyPropertyChangedContext(), QIBaseDriver::unsubscribeFromNotificationImplementation(), QClipboardINCRTransaction::~QClipboardINCRTransaction(), and QCopChannel::~QCopChannel().
 {
     detach();
     QMapData::Node *update[QMapData::LastLevel + 1];
     QMapData::Node *cur = e;
     QMapData::Node *next = e;
     int oldSize = d->size;
     for (int i = d->topLevel; i >= 0; i--) {
         while ((next = cur->forward[i]) != e && qMapLessThanKey<Key>(concrete(next)->key, akey))
             cur = next;
         update[i] = cur;
     }
     if (next != e && !qMapLessThanKey<Key>(akey, concrete(next)->key)) {
         bool deleteNext = true;
         do {
             cur = next;
             next = cur->forward[0];
             deleteNext = (next != e && !qMapLessThanKey<Key>(concrete(cur)->key, concrete(next)->key));
             concrete(cur)->key.~Key();
             concrete(cur)->value.~T();
             d->node_delete(update, payload(), cur);
         } while (deleteNext);
     }
     return oldSize - d->size;
 }
setInsertInOrder()
template<class Key, class T> void QMap< Key, T >::setInsertInOrder (bool sharable) inline
Warning
This function is not part of the public interface.
Definition at line 209 of file qmap.h.
Referenced by operator>>().
 { d->insertInOrder = ordered; }
setSharable()
template<class Key, class T> void QMap< Key, T >::setSharable (bool sharable) inline
Warning
This function is not part of the public interface.
Definition at line 207 of file qmap.h.
 { if (!sharable) detach(); d->sharable = sharable; }
size()
template<class Key, class T> int QMap< Key, T >::size () const inline
Returns the number of (key, value) pairs in the map.
See also
isEmpty(), count()
Definition at line 201 of file qmap.h.
Referenced by QIBaseDriver::close(), macValue(), operator<<(), QMap< int, QFrameInfo >::operator==(), QXmlSimpleReaderPrivate::parseDoctype(), QXmlSimpleReaderPrivate::processElementETagBegin2(), set_text(), QFontCache::timerEvent(), QConfFileSettingsPrivate::writeIniFile(), and QConfFileSettingsPrivate::writePlistFile().
 { return d->size; }
swap()
template<class Key, class T> void QMap< Key, T >::swap (QMap< Key, T > & other) inline
Swaps map other with this map.
Since
4.8
This operation is very fast and never fails.
Definition at line 192 of file qmap.h.
Referenced by QMultiMap< QString, Method >::swap().
 { qSwap(d, other.d); }
take()
template<class Key, class T > Q_OUTOFLINE_TEMPLATE T QMap< Key, T >::take (const Key & key)
Removes the item with the key key from the map and returns the value associated with it.
If the item does not exist in the map, the function simply returns a default-constructed value. If there are multiple items for key in the map, only the most recently inserted one is removed and returned.
If you don't use the return value, remove() is more efficient.
See also
remove()
Definition at line 692 of file qmap.h.
Referenced by QWSServerPrivate::invokeDefineCursor(), QFSFileEnginePrivate::map(), QApplicationPrivate::translateRawTouchEvent(), QGestureManager::unregisterGestureRecognizer(), and QLibraryPrivate::~QLibraryPrivate().
 {
     detach();
     QMapData::Node *update[QMapData::LastLevel + 1];
     QMapData::Node *cur = e;
     QMapData::Node *next = e;
     for (int i = d->topLevel; i >= 0; i--) {
         while ((next = cur->forward[i]) != e && qMapLessThanKey<Key>(concrete(next)->key, akey))
             cur = next;
         update[i] = cur;
     }
     if (next != e && !qMapLessThanKey<Key>(akey, concrete(next)->key)) {
         T t = concrete(next)->value;
         concrete(next)->key.~Key();
         concrete(next)->value.~T();
         d->node_delete(update, payload(), next);
         return t;
     }
     return T();
 }
toStdMap()
template<class Key , class T > Q_OUTOFLINE_TEMPLATE std::map< Key, T > QMap< Key, T >::toStdMap () const
Returns an STL map equivalent to this QMap.
This function is only available if Qt is configured with STL compatibility enabled.
Definition at line 959 of file qmap.h.
 {
     std::map<Key, T> map;
     const_iterator it = end();
     while (it != begin()) {
         --it;
         map.insert(std::pair<Key, T>(it.key(), it.value()));
     }
     return map;
 }
uniqueKeys()
template<class Key , class T > Q_OUTOFLINE_TEMPLATE QList< Key > QMap< Key, T >::uniqueKeys () const
Returns a list containing all the keys in the map in ascending order.
Since
4.2
Keys that occur multiple times in the map (because items were inserted with insertMulti(), or unite() was used) occur only once in the returned list.
See also
keys(), values()
Definition at line 798 of file qmap.h.
 {
     QList<Key> res;
     res.reserve(size()); // May be too much, but assume short lifetime
     const_iterator i = begin();
     if (i != end()) {
         for (;;) {
             const Key &aKey = i.key();
             res.append(aKey);
             do {
                 if (++i == end())
                     goto break_out_of_outer_loop;
             } while (!(aKey < i.key()));   // loop while (key == i.key())
         }
     }
 break_out_of_outer_loop:
     return res;
 }
unite()
template<class Key, class T> Q_INLINE_TEMPLATE QMap< Key, T > & QMap< Key, T >::unite (const QMap< Key, T > & other)
Inserts all the items in the other map into this map.
If a key is common to both maps, the resulting map will contain the key multiple times.
See also
insertMulti()
Definition at line 625 of file qmap.h.
Referenced by QRegExpEngine::Box::cat(), QDBusMetaObject::createMetaObject(), and QRegExpEngine::Box::orx().
 {
     QMap<Key, T> copy(other);
     const_iterator it = copy.constEnd();
     const const_iterator b = copy.constBegin();
     while (it != b) {
         --it;
         insertMulti(it.key(), it.value());
     }
     return *this;
 }
upperBound() [1/2]
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::iterator QMap< Key, T >::upperBound (const Key & key)
Returns an iterator pointing to the item that immediately follows the last item with key key in the map.
If the map contains no item with key key, the function returns an iterator to the nearest item with a greater key.
Example:
QMap<int, QString> map;
map.insert(1, "one");
map.insert(5, "five");
map.insert(10, "ten");
map.upperBound(0);      // returns iterator to (1, "one")
map.upperBound(1);      // returns iterator to (5, "five")
map.upperBound(2);      // returns iterator to (5, "five")
map.upperBound(10);     // returns end()
map.upperBound(999);    // returns end()
See also
qUpperBound(), lowerBound(), find()
Definition at line 918 of file qmap.h.
Referenced by QConfFileSettingsPrivate::ensureSectionParsed(), QGraphicsScenePrivate::filterEvent(), QGestureManager::filterEventThroughContexts(), and QGraphicsScenePrivate::removeSceneEventFilter().
 {
     detach();
     return static_cast<QMapData::Node *>(const_cast<const QMap *>(this)->upperBound(akey));
 }
upperBound() [2/2]
template<class Key, class T > Q_INLINE_TEMPLATE QMap< Key, T >::const_iterator QMap< Key, T >::upperBound (const Key & key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 907 of file qmap.h.
 {
     QMapData::Node *update[QMapData::LastLevel + 1];
     mutableFindNode(update, akey);
     QMapData::Node *node = update[0]->forward[0];
     while (node != e && !qMapLessThanKey<Key>(akey, concrete(node)->key))
         node = node->forward[0];
     return const_iterator(node);
 }
value() [1/2]
template<class Key, class T > Q_INLINE_TEMPLATE const T QMap< Key, T >::value (const Key & key) const
Returns the value associated with the key key.
If the map contains no item with key key, the function returns a default-constructed value. If there are multiple items for key in the map, the value of the most recently inserted one is returned.
See also
key(), values(), contains(), operator[]()
Definition at line 499 of file qmap.h.
Referenced by QWizardPrivate::_q_handleFieldObjectDestroyed(), QAxServerBase::ActiveXProc(), QRegExpEngine::addAnchors(), QRegExpEngine::Box::addAnchorsToEngine(), QTessellatorPrivate::addEdges(), QScriptDebuggerScriptsModel::addExtraScriptInfo(), QTessellatorPrivate::addIntersection(), QDir::addResourceSearchPath(), QAxEventSink::addSignal(), QSpanCollection::addSpan(), QCopChannel::answer(), QBuiltInMimes::canConvertFromMime(), QRegExpEngine::Box::cat(), QRegExpEngine::Box::catAnchor(), QXlibCursor::changeCursor(), QGestureManager::cleanupCachedGestures(), QWSServerPrivate::cleanupFonts(), QWindowsXPStylePrivate::cleanupHandleMap(), QNetworkManagerEngine::connectToId(), QTextCopyHelper::convertFormatIndex(), QBuiltInMimes::convertFromMime(), ControlList::data(), QGraphicsItem::data(), QAbstractItemViewPrivate::delegateForIndex(), QRegExpEngine::Box::dump(), QTessellatorPrivate::edgeInChain(), QAxEventSink::findProperty(), QDBusMetaObjectGenerator::findType(), QTextHtmlExporter::findUrlForImage(), QCalendarModel::formatForCell(), QGraphicsScenePrivate::gestureEventHandler(), QGestureManager::getGestureTargets(), QNetworkManagerSettingsConnection::getId(), QGenericEngine::getInterfaceFromId(), QCoreWlanEngine::getInterfaceFromId(), QConnmanEngine::getInterfaceFromId(), QNlaEngine::getInterfaceFromId(), QNetworkManagerSettingsConnection::getMacAddress(), QOfonoManagerInterface::getProperty(), QConnmanManagerInterface::getProperty(), QOfonoModemInterface::getProperty(), QConnmanProfileInterface::getProperty(), QOfonoNetworkRegistrationInterface::getProperty(), QOfonoNetworkOperatorInterface::getProperty(), QConnmanServiceInterface::getProperty(), QOfonoSimInterface::getProperty(), QConnmanTechnologyInterface::getProperty(), QOfonoDataConnectionManagerInterface::getProperty(), QOfonoPrimaryDataContextInterface::getProperty(), QOfonoSmsInterface::getProperty(), QNetworkManagerSettingsConnection::getSeenBssids(), QNetworkManagerSettingsConnection::getSsid(), QNetworkManagerSettingsConnection::getTimestamp(), QNetworkManagerSettingsConnection::getType(), QNetworkManagerSettingsConnection::getUuid(), QAxEventSink::Invoke(), QGestureEvent::isAccepted(), QNetworkManagerSettingsConnection::isAutoConnect(), QXmlSimpleReaderPrivate::isExpandedEntityValueTooLarge(), QSslCertificate::issuerInfo(), macValue(), QGraphicsScenePrivate::markDirty(), QRegExpMatchState::matchHere(), QBuiltInMimes::mimeForFormat(), QGraphicsItem::mouseMoveEvent(), QApplication::notify(), QTextDocumentPrivate::objectForIndex(), QAxEventSink::OnChanged(), QGtkStylePrivate::openFilename(), QGtkStylePrivate::openFilenames(), QRegExpEngine::parse(), QNetworkManagerEngine::parseConnection(), QDBusMetaObjectGenerator::parseMethods(), QAxMetaObject::parsePrototype(), QWSServer::processEventQueue(), QAxMetaObject::propertyType(), MetaObjectGenerator::propertyType(), QAxBase::propertyWritable(), QGraphicsItemCache::purge(), renameOverloads(), resolveClassName(), QSqlTableModelPrivate::revertCachedRow(), QGtkStylePrivate::saveFilename(), QCompletionEngine::saveInCache(), QWSServer::sendIMEvent(), QWSServerPrivate::sendKeyEventUnfiltered(), QGraphicsScenePrivate::sendMouseEvent(), QWSServerPrivate::sendMouseEventUnfiltered(), set_text(), QApplicationPrivate::setMaxWindowRect(), QAxBase::setPropertyBag(), QSslCertificate::subjectInfo(), QImageReader::text(), QApplicationPrivate::translateRawTouchEvent(), MetaObjectGenerator::tryCache(), QGestureManager::unregisterGestureRecognizer(), QIBaseDriver::unsubscribeFromNotificationImplementation(), QSpanCollection::updateInsertedColumns(), QSpanCollection::updateRemovedColumns(), QSpanCollection::updateRemovedRows(), and QConfFileSettingsPrivate::writeIniFile().
 {
     QMapData::Node *node;
     if (d->size == 0 || (node = findNode(akey)) == e) {
         return T();
     } else {
         return concrete(node)->value;
     }
 }
value() [2/2]
template<class Key, class T> Q_INLINE_TEMPLATE const T QMap< Key, T >::value (const Key & key, const T & defaultValue) const
If the map contains no item with key key, the function returns defaultValue.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 510 of file qmap.h.
 {
     QMapData::Node *node;
     if (d->size == 0 || (node = findNode(akey)) == e) {
         return adefaultValue;
     } else {
         return concrete(node)->value;
     }
 }
values() [1/2]
template<class Key , class T > Q_OUTOFLINE_TEMPLATE QList< T > QMap< Key, T >::values () const
Returns a list containing all the values in the map, in ascending order of their keys.
If a key is associated with multiple values, all of its values will be in the list, and not just the most recently inserted one.
See also
keys(), value()
Definition at line 863 of file qmap.h.
Referenced by QScriptObjectSnapshot::capture(), QTest::QTouchEventSequence::commit(), QGestureManager::unregisterGestureRecognizer(), and QGestureManager::~QGestureManager().
 {
     QList<T> res;
     res.reserve(size());
     const_iterator i = begin();
     while (i != end()) {
         res.append(i.value());
         ++i;
     }
     return res;
 }
values() [2/2]
template<class Key, class T > Q_OUTOFLINE_TEMPLATE QList< T > QMap< Key, T >::values (const Key & key) const
Returns a list containing all the values associated with key key, from the most recently inserted to the least recently inserted one.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
count(), insertMulti()
Definition at line 876 of file qmap.h.
 {
     QList<T> res;
     QMapData::Node *node = findNode(akey);
     if (node != e) {
         do {
             res.append(concrete(node)->value);
             node = node->forward[0];
         } while (node != e && !qMapLessThanKey<Key>(akey, concrete(node)->key));
     }
     return res;
 }
Friends and Related Functions
const_iterator
template<class Key, class T> friend class const_iterator friend
Definition at line 369 of file qmap.h.
iterator
template<class Key, class T> friend class iterator friend
Definition at line 299 of file qmap.h.
operator<<()
template<class Key, class T> QDataStream & operator<< (QDataStream & out, const QMap< Key, T > & map) related
Writes the map map to stream out.
This function requires the key and value types to implement operator<<().
See also
Format of the QDataStream operators
Definition at line 422 of file qdatastream.h.
 {
     out << quint32(map.size());
     typename QMap<Key, T>::ConstIterator it = map.end();
     typename QMap<Key, T>::ConstIterator begin = map.begin();
     while (it != begin) {
         --it;
         out << it.key() << it.value();
     }
     return out;
 }
operator>>()
template<class Key, class T> QDataStream & operator>> (QDataStream & in, QMap< Key, T > & map) related
Reads a map from stream in into map.
This function requires the key and value types to implement operator>>().
See also
Format of the QDataStream operators
Definition at line 389 of file qdatastream.h.
 {
     QDataStream::Status oldStatus = in.status();
     in.resetStatus();
     map.clear();
     quint32 n;
     in >> n;
     map.detach();
     map.setInsertInOrder(true);
     for (quint32 i = 0; i < n; ++i) {
         if (in.status() != QDataStream::Ok)
             break;
         aKey key;
         aT value;
         in >> key >> value;
         map.insertMulti(key, value);
     }
     map.setInsertInOrder(false);
     if (in.status() != QDataStream::Ok)
         map.clear();
     if (oldStatus != QDataStream::Ok)
         in.setStatus(oldStatus);
     return in;
 }
Properties
@65
union { ... }
d
template<class Key, class T> QMapData* QMap< Key, T >::d
Definition at line 165 of file qmap.h.
Referenced by QMap< int, QFrameInfo >::isSharedWith(), QMap< int, QFrameInfo >::operator=(), QMap< int, QFrameInfo >::operator==(), QMap< int, QFrameInfo >::swap(), and QMap< int, QFrameInfo >::~QMap().
e
template<class Key, class T> QMapData::Node* QMap< Key, T >::e
Definition at line 166 of file qmap.h.
The documentation for this class was generated from the following files:
/src/corelib/io/qdatastream.h
/src/corelib/tools/qmap.h
/src/corelib/tools/qmap.cpp