Qt 4.8: QTreeWidgetItemIteratorPrivate Class Reference
QTreeWidgetItemIteratorPrivate Class Reference
#include <qtreewidgetitemiterator_p.h>
Public Functions
void ensureValidIterator (const QTreeWidgetItem *itemToBeRemoved)
QTreeWidgetItem * next (const QTreeWidgetItem *current)
QTreeWidgetItem * nextSibling (const QTreeWidgetItem *item) const
QTreeWidgetItemIteratorPrivate & operator= (const QTreeWidgetItemIteratorPrivate &other)
QTreeWidgetItem * previous (const QTreeWidgetItem *current)
QTreeWidgetItemIteratorPrivate (QTreeWidgetItemIterator *q, QTreeModel *model)
QTreeWidgetItemIteratorPrivate (const QTreeWidgetItemIteratorPrivate &other)
~QTreeWidgetItemIteratorPrivate ()
Properties
int m_currentIndex
QTreeModel * m_model
QStack< int > m_parentIndex
QTreeWidgetItemIterator * q_ptr
Detailed Description
Definition at line 66 of file qtreewidgetitemiterator_p.h.
Constructors and Destructors
QTreeWidgetItemIteratorPrivate() [1/2]
QTreeWidgetItemIteratorPrivate::QTreeWidgetItemIteratorPrivate (QTreeWidgetItemIterator * q, QTreeModel * model) inline
Definition at line 69 of file qtreewidgetitemiterator_p.h.
         : m_currentIndex(0), m_model(model), q_ptr(q)
     {
     }
QTreeWidgetItemIteratorPrivate() [2/2]
QTreeWidgetItemIteratorPrivate::QTreeWidgetItemIteratorPrivate (const QTreeWidgetItemIteratorPrivate & other) inline
Definition at line 75 of file qtreewidgetitemiterator_p.h.
         : m_currentIndex(other.m_currentIndex), m_model(other.m_model),
           m_parentIndex(other.m_parentIndex), q_ptr(other.q_ptr)
     {
     }
~QTreeWidgetItemIteratorPrivate()
QTreeWidgetItemIteratorPrivate::~QTreeWidgetItemIteratorPrivate () inline
Definition at line 90 of file qtreewidgetitemiterator_p.h.
     {
     }
Functions
ensureValidIterator()
void QTreeWidgetItemIteratorPrivate::ensureValidIterator (const QTreeWidgetItem * itemToBeRemoved)
Definition at line 337 of file qtreewidgetitemiterator.cpp.
Referenced by ~QTreeWidgetItemIteratorPrivate().
 {
     Q_Q(QTreeWidgetItemIterator);
     Q_ASSERT(itemToBeRemoved);
     if (!q->current) return;
     QTreeWidgetItem *nextItem = q->current;
     // Do not walk to the ancestor to find the other item if they have the same parent.
     if (nextItem->parent() != itemToBeRemoved->parent()) {
         while (nextItem->parent() && nextItem != itemToBeRemoved) {
             nextItem = nextItem->parent();
         }
     }
     // If the item to be removed is an ancestor of the current iterator item,
     // we need to adjust the iterator.
     if (nextItem == itemToBeRemoved) {
         QTreeWidgetItem *parent = nextItem;
         nextItem = 0;
         while (parent && !nextItem) {
             nextItem = nextSibling(parent);
             parent = parent->parent();
         }
         if (nextItem) {
             // Ooooh... Set the iterator to the next valid item
             *q = QTreeWidgetItemIterator(nextItem, q->flags);
             if (!(q->matchesFlags(nextItem))) ++(*q);
         } else {
             // set it to null.
             q->current = 0;
             m_parentIndex.clear();
             return;
         }
     }
     if (nextItem->parent() == itemToBeRemoved->parent()) {
         // They have the same parent, i.e. we have to adjust the m_currentIndex member of the iterator
         // if the deleted item is to the left of the nextItem.
         QTreeWidgetItem *par = itemToBeRemoved->parent();   // We know they both have the same parent.
         QTreeWidget *tw = itemToBeRemoved->treeWidget();    // ..and widget
         int indexOfItemToBeRemoved = par ? par->indexOfChild(const_cast<QTreeWidgetItem *>(itemToBeRemoved))
             : tw->indexOfTopLevelItem(const_cast<QTreeWidgetItem *>(itemToBeRemoved));
         int indexOfNextItem = par ? par->indexOfChild(nextItem) : tw->indexOfTopLevelItem(nextItem);
         if (indexOfItemToBeRemoved <= indexOfNextItem) {
             // A sibling to the left of us was deleted, adjust the m_currentIndex member of the iterator.
             // Note that the m_currentIndex will be wrong until the item is actually removed!
             m_currentIndex--;
         }
     }
 }
next()
QTreeWidgetItem * QTreeWidgetItemIteratorPrivate::next (const QTreeWidgetItem * current)
Definition at line 286 of file qtreewidgetitemiterator.cpp.
Referenced by ~QTreeWidgetItemIteratorPrivate().
 {
     if (!current) return 0;
     QTreeWidgetItem *next = 0;
     if (current->childCount()) {
         // walk the child
         m_parentIndex.push(m_currentIndex);
         m_currentIndex = 0;
         next = current->child(0);
     } else {
         // walk the sibling
         QTreeWidgetItem *parent = current->parent();
         next = parent ? parent->child(m_currentIndex + 1)
                       : m_model->rootItem->child(m_currentIndex + 1);
         while (!next && parent) {
             // if we had no sibling walk up the parent and try the sibling of that
             parent = parent->parent();
             m_currentIndex = m_parentIndex.pop();
             next = parent ? parent->child(m_currentIndex + 1)
                           : m_model->rootItem->child(m_currentIndex + 1);
         }
         if (next) ++(m_currentIndex);
     }
     return next;
 }
nextSibling()
QTreeWidgetItem * QTreeWidgetItemIteratorPrivate::nextSibling (const QTreeWidgetItem * item) const
Definition at line 271 of file qtreewidgetitemiterator.cpp.
Referenced by ~QTreeWidgetItemIteratorPrivate().
 {
     Q_ASSERT(item);
     QTreeWidgetItem *next = 0;
     if (QTreeWidgetItem *par = item->parent()) {
         int i = par->indexOfChild(const_cast<QTreeWidgetItem*>(item));
         next = par->child(i + 1);
     } else {
         QTreeWidget *tw = item->treeWidget();
         int i = tw->indexOfTopLevelItem(const_cast<QTreeWidgetItem*>(item));
         next = tw->topLevelItem(i + 1);
     }
     return next;
 }
operator=()
QTreeWidgetItemIteratorPrivate& QTreeWidgetItemIteratorPrivate::operator= (const QTreeWidgetItemIteratorPrivate & other) inline
Definition at line 82 of file qtreewidgetitemiterator_p.h.
     {
         m_currentIndex = other.m_currentIndex;
         m_parentIndex = other.m_parentIndex;
         m_model = other.m_model;
         return (*this);
     }
previous()
QTreeWidgetItem * QTreeWidgetItemIteratorPrivate::previous (const QTreeWidgetItem * current)
Definition at line 313 of file qtreewidgetitemiterator.cpp.
Referenced by ~QTreeWidgetItemIteratorPrivate().
 {
     if (!current) return 0;
     QTreeWidgetItem *prev = 0;
     // walk the previous sibling
     QTreeWidgetItem *parent = current->parent();
     prev = parent ? parent->child(m_currentIndex - 1)
                   : m_model->rootItem->child(m_currentIndex - 1);
     if (prev) {
         // Yes, we had a previous sibling but we need go down to the last leafnode.
         --m_currentIndex;
         while (prev && prev->childCount()) {
             m_parentIndex.push(m_currentIndex);
             m_currentIndex = prev->childCount() - 1;
             prev = prev->child(m_currentIndex);
         }
     } else if (parent) {
         m_currentIndex = m_parentIndex.pop();
         prev = parent;
     }
     return prev;
 }
Properties
m_currentIndex
int QTreeWidgetItemIteratorPrivate::m_currentIndex private
Definition at line 100 of file qtreewidgetitemiterator_p.h.
Referenced by operator=().
m_model
QTreeModel* QTreeWidgetItemIteratorPrivate::m_model private
Definition at line 101 of file qtreewidgetitemiterator_p.h.
Referenced by operator=().
m_parentIndex
QStack<int> QTreeWidgetItemIteratorPrivate::m_parentIndex private
Definition at line 102 of file qtreewidgetitemiterator_p.h.
Referenced by operator=().
q_ptr
QTreeWidgetItemIterator* QTreeWidgetItemIteratorPrivate::q_ptr private
Definition at line 103 of file qtreewidgetitemiterator_p.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtreewidgetitemiterator_p.h
/src/gui/itemviews/qtreewidgetitemiterator.cpp