Qt 4.8: QWSMemorySurface Class Reference
QWSMemorySurface Class Reference
#include <qwindowsurface_qws_p.h>
Public Functions
void beginPaint (const QRegion &rgn)
This function is called before painting onto the surface begins, with the region in which the painting will occur.
QImage image () const
Implement this function to return an image of the top-level window.
bool isValid () const
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
bool lock (int timeout=-1)
QPaintDevice * paintDevice ()
Implement this function to return the appropriate paint device.
QPoint painterOffset () const
Returns the offset to be used when painting.
QWSMemorySurface ()
QWSMemorySurface (QWidget *widget)
bool scroll (const QRegion &area, int dx, int dy)
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
void unlock ()
~QWSMemorySurface ()
Public Functions inherited from QWSWindowSurface
const QRegion clipRegion () const
Returns the region currently visible on the screen.
virtual void endPaint (const QRegion &)
This function is called after painting onto the surface has ended, with the region in which the painting was performed.
virtual void flush (QWidget *widget, const QRegion &region, const QPoint &offset)
Flushes the given region from the specified widget onto the screen.
bool isBuffered () const
Returns true if the QWSWindowSurface::Buffered is set; otherwise returns false.
bool isOpaque () const
Returns true if the QWSWindowSurface::Opaque is set; otherwise returns false.
bool isRegionReserved () const
Returns true if the QWSWindowSurface::RegionReserved is set; otherwise returns false.
virtual QString key () const =0
Implement this function to return a string that uniquely identifies the class of this surface.
virtual bool move (const QPoint &offset)
Move the surface with the given offset.
virtual QRegion move (const QPoint &offset, const QRegion &newClip)
Move the surface with the given offset.
virtual QByteArray permanentState () const
Implement this function to return the data required for creating a server-side representation of the surface.
QWSWindowSurface ()
Constructs an empty surface.
QWSWindowSurface (QWidget *widget)
Constructs an empty surface for the given top-level widget.
virtual void releaseSurface ()
void setClipRegion (const QRegion &)
Sets the region currently visible on the screen to be the given clip region.
virtual void setGeometry (const QRect &rect)
Sets the currently allocated area to be the given rect.
virtual void setGeometry (const QRect &rect, const QRegion &mask)
virtual void setPermanentState (const QByteArray &state)
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
virtual void setTransientState (const QByteArray &state)
SurfaceFlags surfaceFlags () const
Returns the surface flags describing the contents of this surface.
virtual QByteArray transientState () const
int winId () const
~QWSWindowSurface ()
Public Functions inherited from QWindowSurface
virtual QImage * buffer (const QWidget *widget)
Returns a QImage pointer which represents the actual buffer the widget is drawn into or 0 if this is unavailable.
virtual WindowSurfaceFeatures features () const
QRect geometry () const
Returns the currently allocated area on the screen.
virtual QPixmap grabWidget (const QWidget *widget, const QRect &rectangle=QRect()) const
Returns a QPixmap generated from the part of the backing store corresponding to widget.
bool hasFeature (WindowSurfaceFeature feature) const
virtual QPoint offset (const QWidget *widget) const
Returns the offset of widget in the coordinates of this window surface.
QWindowSurface (QWidget *window, bool setDefaultSurface=true)
Constructs an empty surface for the given top-level window.
QRect rect (const QWidget *widget) const
Returns the rectangle for widget in the coordinates of this window surface.
void setStaticContents (const QRegion &region)
QRegion staticContents () const
QWidget * window () const
Returns a pointer to the top-level window associated with this surface.
virtual ~QWindowSurface ()
Destroys this surface.
Protected Functions
QImage::Format preferredImageFormat (const QWidget *widget) const
void setLock (int lockId)
Protected Functions inherited from QWSWindowSurface
void setSurfaceFlags (SurfaceFlags type)
Sets the surface flags describing the contents of this surface, to be the given flags.
void setWinId (int id)
Protected Functions inherited from QWindowSurface
bool hasStaticContents () const
Protected Variables
QImage img
QWSLock * memlock
QMutex threadLock
Additional Inherited Members
Public Types inherited from QWSWindowSurface
enum SurfaceFlag { RegionReserved = 0x1, Buffered = 0x2, Opaque = 0x4 }
This enum is used to describe the window surface's contents.
Public Types inherited from QWindowSurface
enum WindowSurfaceFeature { PartialUpdates = 0x00000001, PreservedContents = 0x00000002, StaticContents = 0x00000004, AllFeatures = 0xffffffff }
Detailed Description
Definition at line 164 of file qwindowsurface_qws_p.h.
Constructors and Destructors
QWSMemorySurface() [1/2]
QWSMemorySurface::QWSMemorySurface ()
Definition at line 813 of file qwindowsurface_qws.cpp.
     : QWSWindowSurface()
 #ifndef QT_NO_QWS_MULTIPROCESS
     , memlock(0)
 #endif
 {
     setSurfaceFlags(Buffered);
 }
QWSMemorySurface() [2/2]
QWSMemorySurface::QWSMemorySurface (QWidget * widget)
Definition at line 822 of file qwindowsurface_qws.cpp.
     : QWSWindowSurface(w)
 {
     SurfaceFlags flags = Buffered;
     if (isWidgetOpaque(w))
         flags |= Opaque;
     setSurfaceFlags(flags);
 #ifndef QT_NO_QWS_MULTIPROCESS
     memlock = QWSDisplay::Data::getClientLock();
 #endif
 }
~QWSMemorySurface()
QWSMemorySurface::~QWSMemorySurface ()
Definition at line 835 of file qwindowsurface_qws.cpp.
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (memlock != QWSDisplay::Data::getClientLock())
         delete memlock;
 #endif
 }
Functions
beginPaint()
void QWSMemorySurface::beginPaint (const QRegion & region) virtual
This function is called before painting onto the surface begins, with the region in which the painting will occur.
See also
endPaint(), paintDevice()
Reimplemented from QWSWindowSurface.
Definition at line 909 of file qwindowsurface_qws.cpp.
 {
     if (!isWidgetOpaque(window())) {
         QPainter p(&img);
         p.setCompositionMode(QPainter::CompositionMode_Source);
         const QVector<QRect> rects = rgn.rects();
         const QColor blank = Qt::transparent;
         for (QVector<QRect>::const_iterator it = rects.begin(); it != rects.end(); ++it) {
             QRect r = *it;
 #ifdef Q_BACKINGSTORE_SUBSURFACES
             r.translate(painterOffset());
 #endif
             p.fillRect(r, blank);
         }
     }
     QWSWindowSurface::beginPaint(rgn);
 }
image()
QImage QWSMemorySurface::image () const inline virtual
Implement this function to return an image of the top-level window.
See also
geometry()
Implements QWSWindowSurface.
Definition at line 176 of file qwindowsurface_qws_p.h.
 { return img; }
isValid()
bool QWSMemorySurface::isValid () const virtual
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
Since
4.3
See also
window(), key()
Implements QWSWindowSurface.
Reimplemented in QWSOnScreenSurface.
Definition at line 893 of file qwindowsurface_qws.cpp.
 {
     if (img.isNull())
         return true;
     const QWidget *win = window();
     if (preferredImageFormat(win) != img.format())
         return false;
     if (isOpaque() != isWidgetOpaque(win)) // XXX: use QWidgetPrivate::isOpaque()
         return false;
     return true;
 }
lock()
bool QWSMemorySurface::lock (int timeout = -1) virtual
Reimplemented from QWSWindowSurface.
Definition at line 789 of file qwindowsurface_qws.cpp.
 {
     Q_UNUSED(timeout);
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (memlock && !memlock->lock(QWSLock::BackingStore))
         return false;
 #endif
 #ifndef QT_NO_THREAD
     threadLock.lock();
 #endif
     return true;
 }
paintDevice()
QPaintDevice* QWSMemorySurface::paintDevice () inline virtual
Implement this function to return the appropriate paint device.
Implements QWSWindowSurface.
Definition at line 173 of file qwindowsurface_qws_p.h.
 { return &img; }
painterOffset()
QPoint QWSMemorySurface::painterOffset () const virtual
Returns the offset to be used when painting.
See also
paintDevice()
Reimplemented from QWSWindowSurface.
Reimplemented in QWSOnScreenSurface.
Definition at line 939 of file qwindowsurface_qws.cpp.
Referenced by beginPaint().
 {
     const QWidget *w = window();
     if (!w)
         return QPoint();
     if (w->mask().isEmpty())
         return QWSWindowSurface::painterOffset();
     const QRegion region = w->mask()
                            & w->frameGeometry().translated(-w->geometry().topLeft());
     return -region.boundingRect().topLeft();
 }
preferredImageFormat()
QImage::Format QWSMemorySurface::preferredImageFormat (const QWidget * widget) const protected
Definition at line 845 of file qwindowsurface_qws.cpp.
Referenced by isValid(), QWSLocalMemSurface::setGeometry(), and QWSSharedMemSurface::setGeometry().
 {
     QScreen *screen = getScreen(widget);
     const int depth = screen->depth();
     const bool opaque = isWidgetOpaque(widget);
     if (!opaque) {
         if (depth <= 12)
             return QImage::Format_ARGB4444_Premultiplied;
         else if (depth <= 15)
             return QImage::Format_ARGB8555_Premultiplied;
         else if (depth <= 16)
             return QImage::Format_ARGB8565_Premultiplied;
         else if (depth <= 18)
             return QImage::Format_ARGB6666_Premultiplied;
         else
             return QImage::Format_ARGB32_Premultiplied;
     }
     QImage::Format format = screen->pixelFormat();
     if (format > QImage::Format_Indexed8) // ### assumes all new image formats supports a QPainter
         return format;
     if (depth <= 12)
         return QImage::Format_RGB444;
     else if (depth <= 15)
         return QImage::Format_RGB555;
     else if (depth <= 16)
         return QImage::Format_RGB16;
     else if (depth <= 18)
         return QImage::Format_RGB666;
     else if (depth <= 24)
         return QImage::Format_RGB888;
     else
         return QImage::Format_ARGB32_Premultiplied;
 }
scroll()
bool QWSMemorySurface::scroll (const QRegion & area, int dx, int dy) virtual
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
Returns true if the area was scrolled successfully; false otherwise.
Reimplemented from QWindowSurface.
Definition at line 930 of file qwindowsurface_qws.cpp.
 {
     const QVector<QRect> rects = area.rects();
     for (int i = 0; i < rects.size(); ++i)
         qt_scrollRectInImage(img, rects.at(i), QPoint(dx, dy));
     return true;
 }
setLock()
void QWSMemorySurface::setLock (int lockId) protected
Definition at line 883 of file qwindowsurface_qws.cpp.
Referenced by QWSSharedMemSurface::setPermanentState().
 {
     if (memlock && memlock->id() == lockId)
         return;
     if (memlock != QWSDisplay::Data::getClientLock())
         delete memlock;
     memlock = (lockId == -1 ? 0 : new QWSLock(lockId));
 }
unlock()
void QWSMemorySurface::unlock () virtual
Reimplemented from QWSWindowSurface.
Definition at line 802 of file qwindowsurface_qws.cpp.
 {
 #ifndef QT_NO_THREAD
     threadLock.unlock();
 #endif
 #ifndef QT_NO_QWS_MULTIPROCESS
     if (memlock)
         memlock->unlock(QWSLock::BackingStore);
 #endif
 }
Properties
img
QImage QWSMemorySurface::img protected
Definition at line 195 of file qwindowsurface_qws_p.h.
Referenced by QWSOnScreenSurface::attachToScreen(), beginPaint(), isValid(), QWSLocalMemSurface::setPermanentState(), and QWSSharedMemSurface::setPermanentState().
memlock
QWSLock* QWSMemorySurface::memlock protected
Definition at line 189 of file qwindowsurface_qws_p.h.
Referenced by QWSSharedMemSurface::permanentState(), QWSMemorySurface(), setLock(), and ~QWSMemorySurface().
threadLock
QMutex QWSMemorySurface::threadLock protected
Definition at line 192 of file qwindowsurface_qws_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qwindowsurface_qws_p.h
/src/gui/painting/qwindowsurface_qws.cpp