Qt 4.8: QDoubleValidator Class Reference
QDoubleValidator Class Reference
The QDoubleValidator class provides range checking of floating-point numbers.
#include <qvalidator.h>
Public Types
enum Notation { StandardNotation, ScientificNotation }
This enum defines the allowed notations for entering a double.
Public Types inherited from QValidator
enum State { Invalid, Intermediate, Acceptable }
This enum type defines the states in which a validated string can exist.
Public Functions
double bottom () const
int decimals () const
Notation notation () const
QDoubleValidator (QObject *parent=0)
Constructs a validator object with a parent object that accepts any double.
QDoubleValidator (double bottom, double top, int decimals, QObject *parent=0)
Constructs a validator object with a parent object.
void setBottom (double)
void setDecimals (int)
void setNotation (Notation)
virtual void setRange (double bottom, double top, int decimals=0)
Sets the validator to accept doubles from minimum to maximum inclusive, with at most decimals digits after the decimal point.
void setTop (double)
double top () const
QValidator::State validate (QString &, int &) const
Returns Acceptable if the string input contains a double that is within the valid range and is in the correct format.
~QDoubleValidator ()
Destroys the validator.
Public Functions inherited from QValidator
virtual void fixup (QString &) const
This function attempts to change input to be valid according to this validator's rules.
QLocale locale () const
Returns the locale for the validator.
QValidator (QObject *parent=0)
Sets up the validator.
void setLocale (const QLocale &locale)
Sets the locale that will be used for the validator.
~QValidator ()
Destroys the validator, freeing any storage and other resources used.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
double b
double bottom
the validator's minimum acceptable value
int dec
int decimals
the validator's maximum number of digits after the decimal point
Notation notation
the notation of how a string can describe a number
double t
double top
the validator's maximum acceptable value
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QValidator
QValidator (QObjectPrivate &d, QObject *parent)
QValidator (QValidatorPrivate &d, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDoubleValidator class provides range checking of floating-point numbers.
QDoubleValidator provides an upper bound, a lower bound, and a limit on the number of digits after the decimal point. It does not provide a fixup() function.
You can set the acceptable range in one call with setRange(), or with setBottom() and setTop(). Set the number of decimal places with setDecimals(). The validate() function returns the validation state.
QDoubleValidator uses its locale() to interpret the number. For example, in the German locale, "1,234" will be accepted as the fractional number 1.234. In Arabic locales, QDoubleValidator will accept Arabic digits.
In addition, QDoubleValidator is always guaranteed to accept a number formatted according to the "C" locale. QDoubleValidator will not accept numbers with thousand-separators.
See also
QIntValidator, QRegExpValidator, {Line Edits Example}
Definition at line 134 of file qvalidator.h.
Enumerations
Notation
enum QDoubleValidator::Notation
This enum defines the allowed notations for entering a double.
Since
4.3
StandardNotation The string is written as a standard number (i.e. 0.015).
ScientificNotation The string is written in scientific form. It may have an exponent part(i.e. 1.5E-2).
Enumerator
StandardNotation
ScientificNotation
Definition at line 148 of file qvalidator.h.
                   {
         StandardNotation,
         ScientificNotation
     };
Constructors and Destructors
QDoubleValidator() [1/2]
QDoubleValidator::QDoubleValidator (QObject * parent = 0) explicit
Constructs a validator object with a parent object that accepts any double.
Definition at line 584 of file qvalidator.cpp.
Referenced by QDoubleValidator().
     : QValidator(*new QDoubleValidatorPrivate , parent)
 {
     b = -HUGE_VAL;
     t = HUGE_VAL;
     dec = 1000;
 }
QDoubleValidator() [2/2]
QDoubleValidator::QDoubleValidator (double bottom, double top, int decimals, QObject * parent = 0)
Constructs a validator object with a parent object.
This validator will accept doubles from bottom to top inclusive, with up to decimals digits after the decimal point.
Definition at line 599 of file qvalidator.cpp.
     : QValidator(*new QDoubleValidatorPrivate , parent)
 {
     b = bottom;
     t = top;
     dec = decimals;
 }
~QDoubleValidator()
QDoubleValidator::~QDoubleValidator ()
Destroys the validator.
Definition at line 655 of file qvalidator.cpp.
 {
 }
Functions
bottom()
double QDoubleValidator::bottom () const inline
Definition at line 161 of file qvalidator.h.
Referenced by QDoubleValidator(), setDecimals(), and setTop().
 { return b; }
decimals()
int QDoubleValidator::decimals () const inline
Definition at line 163 of file qvalidator.h.
Referenced by QDoubleValidator(), setBottom(), setRange(), and setTop().
 { return dec; }
notation()
Notation QDoubleValidator::notation () const
Referenced by setNotation(), and QDoubleValidatorPrivate::validateWithLocale().
setBottom()
void QDoubleValidator::setBottom (double bottom)
Definition at line 774 of file qvalidator.cpp.
 {
     setRange(bottom, top(), decimals());
 }
setDecimals()
void QDoubleValidator::setDecimals (int decimals)
Definition at line 809 of file qvalidator.cpp.
 {
     setRange(bottom(), top(), decimals);
 }
setNotation()
void QDoubleValidator::setNotation (Notation newNotation)
Definition at line 827 of file qvalidator.cpp.
 {
     Q_D(QDoubleValidator);
     d->notation = newNotation;
 }
setRange()
void QDoubleValidator::setRange (double bottom, double top, int decimals = 0) virtual
Sets the validator to accept doubles from minimum to maximum inclusive, with at most decimals digits after the decimal point.
Definition at line 755 of file qvalidator.cpp.
Referenced by setBottom(), setDecimals(), and setTop().
 {
     b = minimum;
     t = maximum;
     dec = decimals;
 }
setTop()
void QDoubleValidator::setTop (double top)
Definition at line 792 of file qvalidator.cpp.
 {
     setRange(bottom(), top, decimals());
 }
top()
double QDoubleValidator::top () const inline
Definition at line 162 of file qvalidator.h.
Referenced by QDoubleValidator(), setBottom(), and setDecimals().
 { return t; }
validate()
QValidator::State QDoubleValidator::validate (QString & input, int & pos) const virtual
Returns Acceptable if the string input contains a double that is within the valid range and is in the correct format.
Returns Intermediate if input contains a double that is outside the range or is in the wrong format; e.g. with too many digits after the decimal point or is empty.
Returns Invalid if the input is not a double.
Note: If the valid range consists of just positive doubles (e.g. 0.0 to 100.0) and input is a negative double then Invalid is returned. If notation() is set to StandardNotation, and the input contains more digits before the decimal point than a double in the valid range may have, Invalid is returned. If notation() is ScientificNotation, and the input is not in the valid range, Intermediate is returned. The value may yet become valid by changing the exponent.
By default, the pos parameter is not used by this validator.
Implements QValidator.
Definition at line 689 of file qvalidator.cpp.
 {
     Q_D(const QDoubleValidator);
     QLocalePrivate::NumberMode numMode = QLocalePrivate::DoubleStandardMode;
     switch (d->notation) {
         case StandardNotation:
             numMode = QLocalePrivate::DoubleStandardMode;
             break;
         case ScientificNotation:
             numMode = QLocalePrivate::DoubleScientificMode;
             break;
     }
     State currentLocaleValidation = d->validateWithLocale(input, numMode, locale());
     if (currentLocaleValidation == Acceptable || locale().language() == QLocale::C)
         return currentLocaleValidation;
     State cLocaleValidation = d->validateWithLocale(input, numMode, QLocale(QLocale::C));
     return qMax(currentLocaleValidation, cLocaleValidation);
 }
Properties
b
double QDoubleValidator::b private
Definition at line 176 of file qvalidator.h.
Referenced by QDoubleValidator(), and setRange().
bottom
QDoubleValidator::bottom private
the validator's minimum acceptable value
By default, this property contains a value of -infinity.
See also
setRange()
Definition at line 137 of file qvalidator.h.
dec
int QDoubleValidator::dec private
Definition at line 178 of file qvalidator.h.
Referenced by QDoubleValidator(), and setRange().
decimals
QDoubleValidator::decimals private
the validator's maximum number of digits after the decimal point
By default, this property contains a value of 1000.
See also
setRange()
Definition at line 139 of file qvalidator.h.
notation
QDoubleValidator::Notation QDoubleValidator::notation private
the notation of how a string can describe a number
Since
4.3
By default, this property is set to ScientificNotation.
See also
Notation
Definition at line 141 of file qvalidator.h.
t
double QDoubleValidator::t private
Definition at line 177 of file qvalidator.h.
Referenced by QDoubleValidator(), setRange(), and QDoubleValidatorPrivate::validateWithLocale().
top
QDoubleValidator::top private
the validator's maximum acceptable value
By default, this property contains a value of infinity.
See also
setRange()
Definition at line 138 of file qvalidator.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qvalidator.h
/src/gui/widgets/qvalidator.cpp