Qt 4.8: QDeclarativeVisualModel Class Reference
QDeclarativeVisualModel Class Reference abstract
#include <qdeclarativevisualitemmodel_p.h>
Public Types
enum ReleaseFlag { Referenced = 0x01, Destroyed = 0x02 }
Signals
void countChanged ()
void createdItem (int index, QDeclarativeItem *item)
void destroyingItem (QDeclarativeItem *item)
void itemsChanged (int index, int count)
void itemsInserted (int index, int count)
void itemsMoved (int from, int to, int count)
void itemsRemoved (int index, int count)
void modelReset ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void completeItem ()=0
virtual bool completePending () const =0
virtual int count () const =0
virtual int indexOf (QDeclarativeItem *item, QObject *objectContext) const =0
virtual bool isValid () const =0
virtual QDeclarativeItem * item (int index, bool complete=true)=0
virtual ReleaseFlags release (QDeclarativeItem *item)=0
virtual void setWatchedRoles (QList< QByteArray > roles)=0
virtual QString stringValue (int, const QString &)=0
virtual ~QDeclarativeVisualModel ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QDeclarativeVisualModel (QObjectPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int count
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 63 of file qdeclarativevisualitemmodel_p.h.
Enumerations
ReleaseFlag
enum QDeclarativeVisualModel::ReleaseFlag
Enumerator
Referenced
Destroyed
Definition at line 72 of file qdeclarativevisualitemmodel_p.h.
 { Referenced = 0x01, Destroyed = 0x02 };
Constructors and Destructors
~QDeclarativeVisualModel()
virtual QDeclarativeVisualModel::~QDeclarativeVisualModel () inline virtual
Definition at line 70 of file qdeclarativevisualitemmodel_p.h.
 {}
QDeclarativeVisualModel()
QDeclarativeVisualModel::QDeclarativeVisualModel (QObjectPrivate & dd, QObject * parent = 0) inline protected
Definition at line 97 of file qdeclarativevisualitemmodel_p.h.
         : QObject(dd, parent) {}
Functions
completeItem()
virtual void QDeclarativeVisualModel::completeItem () pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid(), and QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
completePending()
virtual bool QDeclarativeVisualModel::completePending () const pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid(), and QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
count()
virtual int QDeclarativeVisualModel::count () const pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
countChanged
void QDeclarativeVisualModel::countChanged () signal
Referenced by QDeclarativeVisualDataModel::_q_itemsInserted(), QDeclarativeVisualDataModel::_q_itemsRemoved(), QDeclarativeVisualDataModel::setDelegate(), QDeclarativeVisualDataModel::setModel(), and QDeclarativeVisualDataModel::setRootIndex().
createdItem
void QDeclarativeVisualModel::createdItem (int index, QDeclarativeItem * item) signal
Referenced by QDeclarativeVisualDataModel::_q_createdPackage().
destroyingItem
void QDeclarativeVisualModel::destroyingItem (QDeclarativeItem * item) signal
Referenced by QDeclarativeVisualDataModel::_q_destroyingPackage().
indexOf()
virtual int QDeclarativeVisualModel::indexOf (QDeclarativeItem * item, QObject * objectContext) const pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid(), and QDeclarativeVisualItemModel::setWatchedRoles().
isValid()
virtual bool QDeclarativeVisualModel::isValid () const pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativePathViewPrivate::isValid(), and QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
item()
virtual QDeclarativeItem* QDeclarativeVisualModel::item (int index, bool complete = true) pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid(), and QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
itemsChanged
void QDeclarativeVisualModel::itemsChanged (int index, int count) signal
Referenced by QDeclarativeVisualDataModel::_q_itemsChanged(), and QDeclarativeVisualDataModel::setModel().
itemsInserted
void QDeclarativeVisualModel::itemsInserted (int index, int count) signal
Referenced by QDeclarativeVisualDataModel::_q_itemsInserted(), QDeclarativeVisualDataModel::setDelegate(), QDeclarativeVisualDataModel::setModel(), and QDeclarativeVisualDataModel::setRootIndex().
itemsMoved
void QDeclarativeVisualModel::itemsMoved (int from, int to, int count) signal
Referenced by QDeclarativeVisualDataModel::_q_itemsMoved(), and QDeclarativeVisualDataModel::setModel().
itemsRemoved
void QDeclarativeVisualModel::itemsRemoved (int index, int count) signal
Referenced by QDeclarativeVisualDataModel::_q_itemsRemoved(), QDeclarativeVisualDataModel::setDelegate(), QDeclarativeVisualDataModel::setModel(), and QDeclarativeVisualDataModel::setRootIndex().
modelReset
void QDeclarativeVisualModel::modelReset () signal
Referenced by QDeclarativeVisualDataModel::_q_modelReset(), and QDeclarativeVisualDataModel::setModel().
release()
virtual ReleaseFlags QDeclarativeVisualModel::release (QDeclarativeItem * item) pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid(), and QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
setWatchedRoles()
virtual void QDeclarativeVisualModel::setWatchedRoles (QList< QByteArray > roles) pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid().
stringValue()
virtual QString QDeclarativeVisualModel::stringValue (int , const QString &) pure virtual
Implemented in QDeclarativeVisualDataModel, and QDeclarativeVisualItemModel.
Referenced by QDeclarativeVisualDataModel::isValid(), and QDeclarativeVisualItemModel::~QDeclarativeVisualItemModel().
Properties
count
int QDeclarativeVisualModel::count private
Definition at line 67 of file qdeclarativevisualitemmodel_p.h.
Referenced by QDeclarativePathViewPrivate::isValid().
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativevisualitemmodel_p.h