Qt 4.8: QVGEGLWindowSurfacePrivate Class Reference
QVGEGLWindowSurfacePrivate Class Reference abstract
#include <qwindowsurface_vgegl_p.h>
Public Functions
virtual void beginPaint (QWidget *widget)=0
virtual void endPaint (QWidget *widget, const QRegion &region, QImage *image=0)=0
virtual QEglContext * ensureContext (QWidget *widget)=0
QVGPaintEngine * paintEngine ()
QVGEGLWindowSurfacePrivate (QWindowSurface *win)
virtual bool scroll (QWidget *, const QRegion &, int, int)
virtual bool supportsStaticContents () const
virtual VGImage surfaceImage () const
virtual QSize surfaceSize () const =0
virtual ~QVGEGLWindowSurfacePrivate ()
Protected Functions
void destroyPaintEngine ()
QSize windowSurfaceSize (QWidget *widget) const
Protected Variables
QVGPaintEngine * engine
QWindowSurface * winSurface
Detailed Description
Definition at line 67 of file qwindowsurface_vgegl_p.h.
Constructors and Destructors
QVGEGLWindowSurfacePrivate()
QVGEGLWindowSurfacePrivate::QVGEGLWindowSurfacePrivate (QWindowSurface * win)
Definition at line 430 of file qwindowsurface_vgegl.cpp.
 {
     winSurface = win;
     engine = 0;
 }
~QVGEGLWindowSurfacePrivate()
QVGEGLWindowSurfacePrivate::~QVGEGLWindowSurfacePrivate () virtual
Definition at line 436 of file qwindowsurface_vgegl.cpp.
 {
     // Destroy the paint engine if it hasn't been destroyed already.
     destroyPaintEngine();
 }
Functions
beginPaint()
virtual void QVGEGLWindowSurfacePrivate::beginPaint (QWidget * widget) pure virtual
Implemented in QVGEGLWindowSurfaceDirect.
Referenced by QVGWindowSurface::beginPaint().
destroyPaintEngine()
void QVGEGLWindowSurfacePrivate::destroyPaintEngine () protected
Definition at line 454 of file qwindowsurface_vgegl.cpp.
Referenced by QVGEGLWindowSurfaceDirect::~QVGEGLWindowSurfaceDirect().
 {
     if (engine) {
         qt_vg_destroy_paint_engine(engine);
         engine = 0;
     }
 }
endPaint()
virtual void QVGEGLWindowSurfacePrivate::endPaint (QWidget * widget, const QRegion & region, QImage * image = 0) pure virtual
Implemented in QVGEGLWindowSurfaceDirect.
Referenced by QVGWindowSurface::flush().
ensureContext()
virtual QEglContext* QVGEGLWindowSurfacePrivate::ensureContext (QWidget * widget) pure virtual
Implemented in QVGEGLWindowSurfaceDirect.
paintEngine()
QVGPaintEngine * QVGEGLWindowSurfacePrivate::paintEngine ()
Definition at line 442 of file qwindowsurface_vgegl.cpp.
Referenced by QVGWindowSurface::beginPaint(), and QVGWindowSurface::paintEngine().
 {
     if (!engine)
         engine = qt_vg_create_paint_engine();
     return engine;
 }
scroll()
virtual bool QVGEGLWindowSurfacePrivate::scroll (QWidget * , const QRegion & , int , int) inline virtual
Reimplemented in QVGEGLWindowSurfaceDirect.
Definition at line 81 of file qwindowsurface_vgegl_p.h.
Referenced by QVGWindowSurface::scroll(), and QVGEGLWindowSurfaceDirect::surfaceSize().
 { return false; }
supportsStaticContents()
virtual bool QVGEGLWindowSurfacePrivate::supportsStaticContents () const inline virtual
Reimplemented in QVGEGLWindowSurfaceDirect.
Definition at line 80 of file qwindowsurface_vgegl_p.h.
Referenced by QVGWindowSurface::features(), QVGEGLWindowSurfaceDirect::supportsStaticContents(), and QVGEGLWindowSurfaceDirect::surfaceSize().
 { return false; }
surfaceImage()
VGImage QVGEGLWindowSurfacePrivate::surfaceImage () const virtual
Definition at line 449 of file qwindowsurface_vgegl.cpp.
 {
     return VG_INVALID_HANDLE;
 }
surfaceSize()
virtual QSize QVGEGLWindowSurfacePrivate::surfaceSize () const pure virtual
Implemented in QVGEGLWindowSurfaceDirect.
Referenced by QVGWindowSurface::beginPaint().
windowSurfaceSize()
QSize QVGEGLWindowSurfacePrivate::windowSurfaceSize (QWidget * widget) const protected
Definition at line 462 of file qwindowsurface_vgegl.cpp.
Referenced by QVGEGLWindowSurfaceDirect::ensureContext().
 {
     Q_UNUSED(widget);
     QRect rect = winSurface->geometry();
     QSize newSize = rect.size();
 #if defined(Q_WS_QWS)
     // Account for the widget mask, if any.
     if (widget && !widget->mask().isEmpty()) {
         const QRegion region = widget->mask()
                                & rect.translated(-widget->geometry().topLeft());
         newSize = region.boundingRect().size();
     }
 #endif
     return newSize;
 }
Properties
engine
QVGPaintEngine* QVGEGLWindowSurfacePrivate::engine protected
Definition at line 84 of file qwindowsurface_vgegl_p.h.
winSurface
QWindowSurface* QVGEGLWindowSurfacePrivate::winSurface protected
Definition at line 85 of file qwindowsurface_vgegl_p.h.
The documentation for this class was generated from the following files:
/src/openvg/qwindowsurface_vgegl_p.h
/src/openvg/qwindowsurface_vgegl.cpp