Qt 4.8: QEventTransition Class Reference
QEventTransition Class Reference
The QEventTransition class provides a QObject-specific transition for Qt events.
#include <qeventtransition.h>
Public Functions
QObject * eventSource () const
QEvent::Type eventType () const
QEventTransition (QState *sourceState=0)
Constructs a new QEventTransition object with the given sourceState.
QEventTransition (QObject *object, QEvent::Type type, QState *sourceState=0)
Constructs a new QEventTransition object associated with events of the given type for the given object, and with the given sourceState.
void setEventSource (QObject *object)
Sets the event source associated with this event transition to be the given object.
void setEventType (QEvent::Type type)
Sets the event type that this event transition is associated with.
~QEventTransition ()
Destroys this QObject event transition.
Public Functions inherited from QAbstractTransition
void addAnimation (QAbstractAnimation *animation)
Adds the given animation to this transition.
QList< QAbstractAnimation * > animations () const
Returns the list of animations associated with this transition, or an empty list if it has no animations.
QStateMachine * machine () const
Returns the state machine that this transition is part of, or 0 if the transition is not part of a state machine.
QAbstractTransition (QState *sourceState=0)
Constructs a new QAbstractTransition object with the given sourceState.
void removeAnimation (QAbstractAnimation *animation)
Removes the given animation from this transition.
void setTargetState (QAbstractState *target)
Sets the target state of this transition.
void setTargetStates (const QList< QAbstractState *> &targets)
Sets the target states of this transition to be the given targets.
QState * sourceState () const
QAbstractState * targetState () const
QList< QAbstractState * > targetStates () const
virtual ~QAbstractTransition ()
Destroys this transition.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *e)
Reimplemented Function
bool eventTest (QEvent *event)
Reimplemented Function
void onTransition (QEvent *event)
Reimplemented Function
QEventTransition (QEventTransitionPrivate &dd, QState *parent)
QEventTransition (QEventTransitionPrivate &dd, QObject *object, QEvent::Type type, QState *parent)
Protected Functions inherited from QAbstractTransition
QAbstractTransition (QAbstractTransitionPrivate &dd, QState *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QObject * eventSource
the event source that this event transition is associated with
QEvent::Type eventType
the type of event that this event transition is associated with
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractTransition
void triggered ()
This signal is emitted when the transition has been triggered (after onTransition() has been called).
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QEventTransition class provides a QObject-specific transition for Qt events.
Since
4.6
A QEventTransition object binds an event to a particular QObject. QEventTransition is part of The State Machine Framework.
Example:
QPushButton *button = ...;
QState *s1 = ...;
QState *s2 = ...;
// If in s1 and the button receives an Enter event, transition to s2
QEventTransition *enterTransition = new QEventTransition(button, QEvent::Enter);
enterTransition->setTargetState(s2);
s1->addTransition(enterTransition);
// If in s2 and the button receives an Exit event, transition back to s1
QEventTransition *leaveTransition = new QEventTransition(button, QEvent::Leave);
leaveTransition->setTargetState(s1);
s2->addTransition(leaveTransition);
Subclassing
When reimplementing the eventTest() function, you should first call the base implementation to verify that the event is a QStateMachine::WrappedEvent for the proper object and event type. You may then cast the event to a QStateMachine::WrappedEvent and get the original event by calling QStateMachine::WrappedEvent::event(), and perform additional checks on that object.
See also
QState::addTransition()
Definition at line 57 of file qeventtransition.h.
Constructors and Destructors
QEventTransition() [1/4]
QEventTransition::QEventTransition (QState * sourceState = 0)
Constructs a new QEventTransition object with the given sourceState.
Definition at line 145 of file qeventtransition.cpp.
     : QAbstractTransition(*new QEventTransitionPrivate, sourceState)
 {
 }
QEventTransition() [2/4]
QEventTransition::QEventTransition (QObject * object, QEvent::Type type, QState * sourceState = 0)
Constructs a new QEventTransition object associated with events of the given type for the given object, and with the given sourceState.
Definition at line 154 of file qeventtransition.cpp.
     : QAbstractTransition(*new QEventTransitionPrivate, sourceState)
 {
     Q_D(QEventTransition);
     d->registered = false;
     d->object = object;
     d->eventType = type;
 }
~QEventTransition()
QEventTransition::~QEventTransition ()
Destroys this QObject event transition.
Definition at line 188 of file qeventtransition.cpp.
 {
 }
QEventTransition() [3/4]
QEventTransition::QEventTransition (QEventTransitionPrivate & dd, QState * parent) protected
Warning
This function is not part of the public interface.
Definition at line 167 of file qeventtransition.cpp.
     : QAbstractTransition(dd, parent)
 {
 }
QEventTransition() [4/4]
QEventTransition::QEventTransition (QEventTransitionPrivate & dd, QObject * object, QEvent::Type type, QState * parent) protected
Warning
This function is not part of the public interface.
Definition at line 175 of file qeventtransition.cpp.
     : QAbstractTransition(dd, parent)
 {
     Q_D(QEventTransition);
     d->registered = false;
     d->object = object;
     d->eventType = type;
 }
Functions
event()
bool QEventTransition::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractTransition.
Definition at line 262 of file qeventtransition.cpp.
Referenced by eventTest(), QKeyEventTransition::eventTest(), and QMouseEventTransition::eventTest().
 {
     return QAbstractTransition::event(e);
 }
eventSource()
QObject* QEventTransition::eventSource () const
Referenced by setEventType().
eventTest()
bool QEventTransition::eventTest (QEvent * event) protected virtual
Reimplemented Function
Implements QAbstractTransition.
Reimplemented in QMouseEventTransition, and QKeyEventTransition.
Definition at line 240 of file qeventtransition.cpp.
Referenced by QKeyEventTransition::eventTest(), and QMouseEventTransition::eventTest().
 {
     Q_D(const QEventTransition);
     if (event->type() == QEvent::StateMachineWrapped) {
         QStateMachine::WrappedEvent *we = static_cast<QStateMachine::WrappedEvent*>(event);
         return (we->object() == d->object)
             && (we->event()->type() == d->eventType);
     }
     return false;
 }
eventType()
QEvent::Type QEventTransition::eventType () const
Referenced by ~QEventTransition().
onTransition()
void QEventTransition::onTransition (QEvent * event) protected virtual
Reimplemented Function
Implements QAbstractTransition.
Reimplemented in QMouseEventTransition, and QKeyEventTransition.
Definition at line 254 of file qeventtransition.cpp.
Referenced by QKeyEventTransition::onTransition(), and QMouseEventTransition::onTransition().
 {
     Q_UNUSED(event);
 }
setEventSource()
void QEventTransition::setEventSource (QObject * object)
Sets the event source associated with this event transition to be the given object.
Definition at line 227 of file qeventtransition.cpp.
 {
     Q_D(QEventTransition);
     if (d->object == object)
         return;
     d->unregister();
     d->object = object;
     d->maybeRegister();
 }
setEventType()
void QEventTransition::setEventType (QEvent::Type type)
Sets the event type that this event transition is associated with.
Definition at line 204 of file qeventtransition.cpp.
 {
     Q_D(QEventTransition);
     if (d->eventType == type)
         return;
     d->unregister();
     d->eventType = type;
     d->maybeRegister();
 }
Properties
eventSource
QObject * QEventTransition::eventSource private
the event source that this event transition is associated with
Returns the event source associated with this event transition.
Definition at line 60 of file qeventtransition.h.
eventType
QEvent::Type QEventTransition::eventType private
the type of event that this event transition is associated with
Returns the event type that this event transition is associated with.
Definition at line 61 of file qeventtransition.h.
Referenced by QStateMachinePrivate::registerEventTransition(), and QStateMachinePrivate::unregisterEventTransition().
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qeventtransition.h
/src/corelib/statemachine/qeventtransition.cpp