Qt 4.8: QScriptDebuggerScriptedConsoleCommand Class Reference
QScriptDebuggerScriptedConsoleCommand Class Reference
The QScriptDebuggerScriptedConsoleCommand class encapsulates a command defined in a script.
#include <qscriptdebuggerscriptedconsolecommand_p.h>
Public Functions
QStringList aliases () const
QStringList argumentTypes () const
QScriptDebuggerConsoleCommandJob * createJob (const QStringList &arguments, QScriptDebuggerConsole *console, QScriptMessageHandlerInterface *messageHandler, QScriptDebuggerCommandSchedulerInterface *commandScheduler)
QString group () const
QString longDescription () const
QString name () const
QStringList seeAlso () const
QString shortDescription () const
QStringList subCommands () const
~QScriptDebuggerScriptedConsoleCommand ()
Public Functions inherited from QScriptDebuggerConsoleCommand
QScriptDebuggerConsoleCommand ()
virtual ~QScriptDebuggerConsoleCommand ()
Static Public Functions
static QScriptDebuggerScriptedConsoleCommand * parse (const QString &program, const QString &fileName, QScriptEngine *engine, QScriptMessageHandlerInterface *messageHandler)
Parses a command defined by the given program.
Protected Functions
QScriptDebuggerScriptedConsoleCommand (const QString &name, const QString &group, const QString &shortDescription, const QString &longDescription, const QStringList &aliases, const QStringList &seeAlso, const QStringList &argumentTypes, const QStringList &subCommands, const QScriptValue &globalObject, const QScriptValue &execFunction, const QScriptValue &responseFunction)
Protected Functions inherited from QScriptDebuggerConsoleCommand
QScriptDebuggerConsoleCommand (QScriptDebuggerConsoleCommandPrivate &dd)
Additional Inherited Members
Protected Variables inherited from QScriptDebuggerConsoleCommand
QScopedPointer< QScriptDebuggerConsoleCommandPrivate > d_ptr
Detailed Description
The QScriptDebuggerScriptedConsoleCommand class encapsulates a command defined in a script.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 64 of file qscriptdebuggerscriptedconsolecommand_p.h.
Constructors and Destructors
QScriptDebuggerScriptedConsoleCommand()
QScriptDebuggerScriptedConsoleCommand::QScriptDebuggerScriptedConsoleCommand (const QString & name, const QString & group, const QString & shortDescription, const QString & longDescription, const QStringList & aliases, const QStringList & seeAlso, const QStringList & argumentTypes, const QStringList & subCommands, const QScriptValue & globalObject, const QScriptValue & execFunction, const QScriptValue & responseFunction) protected
Definition at line 103 of file qscriptdebuggerscriptedconsolecommand.cpp.
     : QScriptDebuggerConsoleCommand(*new QScriptDebuggerScriptedConsoleCommandPrivate)
 {
     Q_D(QScriptDebuggerScriptedConsoleCommand);
     d->name = name;
     d->group = group;
     d->shortDescription = shortDescription;
     d->longDescription = longDescription;
     d->aliases = aliases;
     d->seeAlso = seeAlso;
     d->argumentTypes = argumentTypes;
     d->subCommands = subCommands;
     d->globalObject = globalObject;
     d->execFunction = execFunction;
     d->responseFunction = responseFunction;
 }
~QScriptDebuggerScriptedConsoleCommand()
QScriptDebuggerScriptedConsoleCommand::~QScriptDebuggerScriptedConsoleCommand ()
Definition at line 126 of file qscriptdebuggerscriptedconsolecommand.cpp.
 {
 }
Functions
aliases()
QStringList QScriptDebuggerScriptedConsoleCommand::aliases () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QScriptDebuggerConsoleCommand.
Definition at line 294 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->aliases;
 }
argumentTypes()
QStringList QScriptDebuggerScriptedConsoleCommand::argumentTypes () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QScriptDebuggerConsoleCommand.
Definition at line 312 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->argumentTypes;
 }
createJob()
QScriptDebuggerConsoleCommandJob * QScriptDebuggerScriptedConsoleCommand::createJob (const QStringList & arguments, QScriptDebuggerConsole * console, QScriptMessageHandlerInterface * messageHandler, QScriptDebuggerCommandSchedulerInterface * commandScheduler) virtual
Warning
This function is not part of the public interface.
Implements QScriptDebuggerConsoleCommand.
Definition at line 330 of file qscriptdebuggerscriptedconsolecommand.cpp.
 {
     Q_D(QScriptDebuggerScriptedConsoleCommand);
     return new QScriptDebuggerScriptedConsoleCommandJob(
         d, arguments, console, messageHandler, commandScheduler);
 }
group()
QString QScriptDebuggerScriptedConsoleCommand::group () const virtual
Warning
This function is not part of the public interface.
Implements QScriptDebuggerConsoleCommand.
Definition at line 267 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->group;
 }
longDescription()
QString QScriptDebuggerScriptedConsoleCommand::longDescription () const virtual
Warning
This function is not part of the public interface.
Implements QScriptDebuggerConsoleCommand.
Definition at line 285 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->longDescription;
 }
name()
QString QScriptDebuggerScriptedConsoleCommand::name () const virtual
Warning
This function is not part of the public interface.
Implements QScriptDebuggerConsoleCommand.
Definition at line 258 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->name;
 }
parse()
QScriptDebuggerScriptedConsoleCommand * QScriptDebuggerScriptedConsoleCommand::parse (const QString & program, const QString & fileName, QScriptEngine * engine, QScriptMessageHandlerInterface * messageHandler) static
Parses a command defined by the given program.
Returns an object that encapsulates the command, or 0 if parsing failed.
Definition at line 345 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerConsolePrivate::loadScriptedCommands().
 {
     // create a custom global object
     QScriptDebuggerConsoleGlobalObject *cppGlobal = new QScriptDebuggerConsoleGlobalObject();
     QScriptValue global = engine->newQObject(cppGlobal,
                                              QScriptEngine::ScriptOwnership,
                                              QScriptEngine::ExcludeSuperClassContents);
     {
         QScriptValueIterator it(engine->globalObject());
         while (it.hasNext()) {
             it.next();
             global.setProperty(it.scriptName(), it.value(), it.flags());
         }
     }
     engine->setGlobalObject(global);
     cppGlobal->setMessageHandler(messageHandler);
     QScriptValue ret = engine->evaluate(program, fileName);
     cppGlobal->setMessageHandler(0);
     if (engine->hasUncaughtException()) {
         messageHandler->message(QtCriticalMsg, ret.toString(), fileName,
                                 engine->uncaughtExceptionLineNumber());
         return 0;
     }
     QScriptValue name = global.property(QLatin1String("name"));
     if (!name.isString()) {
         messageHandler->message(QtCriticalMsg, QLatin1String("command definition lacks a name"), fileName);
         return 0;
     }
     QString nameStr = name.toString();
     QScriptValue group = global.property(QLatin1String("group"));
     if (!group.isString()) {
         messageHandler->message(QtCriticalMsg, QString::fromLatin1("definition of command \"%0\" lacks a group name")
                                 .arg(nameStr), fileName);
         return 0;
     }
     QString groupStr = group.toString();
     QScriptValue shortDesc = global.property(QLatin1String("shortDescription"));
     if (!shortDesc.isString()) {
         messageHandler->message(QtCriticalMsg, QString::fromLatin1("definition of command \"%0\" lacks shortDescription")
                                 .arg(nameStr), fileName);
         return 0;
     }
     QString shortDescStr = shortDesc.toString();
     QScriptValue longDesc = global.property(QLatin1String("longDescription"));
     if (!longDesc.isString()) {
         messageHandler->message(QtCriticalMsg, QString::fromLatin1("definition of command \"%0\" lacks longDescription")
                                 .arg(nameStr), fileName);
         return 0;
     }
     QString longDescStr = longDesc.toString();
     QStringList aliases;
     qScriptValueToSequence(global.property(QLatin1String("aliases")), aliases);
     QStringList seeAlso;
     qScriptValueToSequence(global.property(QLatin1String("seeAlso")), seeAlso);
     QStringList argTypes;
     qScriptValueToSequence(global.property(QLatin1String("argumentTypes")), argTypes);
     QStringList subCommands;
     qScriptValueToSequence(global.property(QLatin1String("subCommands")), subCommands);
     QScriptValue execFunction = global.property(QLatin1String("execute"));
     if (!execFunction.isFunction()) {
         messageHandler->message(QtCriticalMsg, QString::fromLatin1("definition of command \"%0\" lacks execute() function")
                                 .arg(nameStr), fileName);
         return 0;
     }
     QScriptValue responseFunction = global.property(QLatin1String("handleResponse"));
     QScriptDebuggerScriptedConsoleCommand *result = new QScriptDebuggerScriptedConsoleCommand(
         nameStr, groupStr,
         shortDescStr, longDescStr,
         aliases, seeAlso,
         argTypes, subCommands,
         global, execFunction, responseFunction);
     return result;
 }
seeAlso()
QStringList QScriptDebuggerScriptedConsoleCommand::seeAlso () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QScriptDebuggerConsoleCommand.
Definition at line 303 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->seeAlso;
 }
shortDescription()
QString QScriptDebuggerScriptedConsoleCommand::shortDescription () const virtual
Warning
This function is not part of the public interface.
Implements QScriptDebuggerConsoleCommand.
Definition at line 276 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->shortDescription;
 }
subCommands()
QStringList QScriptDebuggerScriptedConsoleCommand::subCommands () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QScriptDebuggerConsoleCommand.
Definition at line 321 of file qscriptdebuggerscriptedconsolecommand.cpp.
Referenced by QScriptDebuggerScriptedConsoleCommand().
 {
     Q_D(const QScriptDebuggerScriptedConsoleCommand);
     return d->subCommands;
 }
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerscriptedconsolecommand_p.h
/src/scripttools/debugging/qscriptdebuggerscriptedconsolecommand.cpp