Qt 4.8: QDeclarativeItemChangeListener Class Reference
QDeclarativeItemChangeListener Class Reference
#include <qdeclarativeitemchangelistener_p.h>
Public Functions
virtual QDeclarativeAnchorsPrivate * anchorPrivate ()
virtual void itemDestroyed (QDeclarativeItem *)
virtual void itemGeometryChanged (QDeclarativeItem *, const QRectF &, const QRectF &)
virtual void itemOpacityChanged (QDeclarativeItem *)
virtual void itemSiblingOrderChanged (QDeclarativeItem *)
virtual void itemVisibilityChanged (QDeclarativeItem *)
Detailed Description
Definition at line 63 of file qdeclarativeitemchangelistener_p.h.
Functions
anchorPrivate()
virtual QDeclarativeAnchorsPrivate* QDeclarativeItemChangeListener::anchorPrivate () inline virtual
Reimplemented in QDeclarativeAnchorsPrivate.
Definition at line 71 of file qdeclarativeitemchangelistener_p.h.
Referenced by QDeclarativeItem::setBaselineOffset().
 { return 0; }
itemDestroyed()
virtual void QDeclarativeItemChangeListener::itemDestroyed (QDeclarativeItem *) inline virtual
Reimplemented in QDeclarativeBasePositionerPrivate, and QDeclarativeContents.
Definition at line 70 of file qdeclarativeitemchangelistener_p.h.
Referenced by QDeclarativeItem::~QDeclarativeItem().
 {}
itemGeometryChanged()
virtual void QDeclarativeItemChangeListener::itemGeometryChanged (QDeclarativeItem * , const QRectF & , const QRectF &) inline virtual
Reimplemented in QDeclarativeListViewPrivate, QDeclarativeGridViewPrivate, QDeclarativeFlickablePrivate, QDeclarativeViewPrivate, QDeclarativeBasePositionerPrivate, QDeclarativeAnchorsPrivate, QDeclarativeContents, QDeclarativePathViewPrivate, and QDeclarativeLoaderPrivate.
Definition at line 66 of file qdeclarativeitemchangelistener_p.h.
Referenced by QDeclarativeItem::geometryChanged(), QDeclarativeLoaderPrivate::itemGeometryChanged(), and QDeclarativeViewPrivate::itemGeometryChanged().
 {}
itemOpacityChanged()
virtual void QDeclarativeItemChangeListener::itemOpacityChanged (QDeclarativeItem *) inline virtual
Reimplemented in QDeclarativeBasePositionerPrivate.
Definition at line 69 of file qdeclarativeitemchangelistener_p.h.
Referenced by QDeclarativeItem::itemChange().
 {}
itemSiblingOrderChanged()
virtual void QDeclarativeItemChangeListener::itemSiblingOrderChanged (QDeclarativeItem *) inline virtual
Reimplemented in QDeclarativeBasePositionerPrivate.
Definition at line 67 of file qdeclarativeitemchangelistener_p.h.
Referenced by QDeclarativeItemPrivate::siblingOrderChange().
 {}
itemVisibilityChanged()
virtual void QDeclarativeItemChangeListener::itemVisibilityChanged (QDeclarativeItem *) inline virtual
Reimplemented in QDeclarativeBasePositionerPrivate.
Definition at line 68 of file qdeclarativeitemchangelistener_p.h.
Referenced by QDeclarativeItem::itemChange().
 {}
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativeitemchangelistener_p.h