Qt 4.8: QDeclarativeFastProperties Class Reference
QDeclarativeFastProperties Class Reference
#include <qdeclarativefastproperties_p.h>
Public Types
typedef void(* Accessor) (QObject *object, void *output, QDeclarativeNotifierEndpoint *endpoint)
Public Functions
Accessor accessor (int index) const
int accessorIndexForProperty (const QMetaObject *, int)
QDeclarativeFastProperties ()
Private Functions
void add (const QMetaObject *, int, Accessor)
Properties
QVector< Accessor > m_accessors
QHash< QPair< const QMetaObject *, int >, int > m_index
Detailed Description
Definition at line 54 of file qdeclarativefastproperties_p.h.
Typedefs
Accessor
typedef void(* QDeclarativeFastProperties::Accessor) (QObject *object, void *output, QDeclarativeNotifierEndpoint *endpoint)
Definition at line 57 of file qdeclarativefastproperties_p.h.
Constructors and Destructors
QDeclarativeFastProperties()
QDeclarativeFastProperties::QDeclarativeFastProperties ()
Definition at line 61 of file qdeclarativefastproperties.cpp.
 {
     add(&QDeclarativeItem::staticMetaObject, QDeclarativeItem::staticMetaObject.indexOfProperty("parent"),
         QDeclarativeItemPrivate::parentProperty);
     add(&QObject::staticMetaObject, QObject::staticMetaObject.indexOfProperty("objectName"),
         QObject_objectName);
 }
Functions
accessor()
Accessor QDeclarativeFastProperties::accessor (int index) const inline
Definition at line 61 of file qdeclarativefastproperties_p.h.
 { return m_accessors.at(index); }
accessorIndexForProperty()
int QDeclarativeFastProperties::accessorIndexForProperty (const QMetaObject * metaObject, int propertyIndex)
Definition at line 69 of file qdeclarativefastproperties.cpp.
Referenced by accessor().
 {
     Q_ASSERT(metaObject);
     Q_ASSERT(propertyIndex >= 0);
     // Find the "real" metaObject
     while (metaObject->propertyOffset() > propertyIndex)
         metaObject = metaObject->superClass();
     QHash<QPair<const QMetaObject *, int>, int>::Iterator iter =
         m_index.find(qMakePair(metaObject, propertyIndex));
     if (iter != m_index.end())
         return *iter;
     else
         return -1;
 }
add()
void QDeclarativeFastProperties::add (const QMetaObject * metaObject, int propertyIndex, Accessor accessor) private
Definition at line 86 of file qdeclarativefastproperties.cpp.
Referenced by accessor(), and QDeclarativeFastProperties().
 {
     Q_ASSERT(metaObject);
     Q_ASSERT(propertyIndex >= 0);
     // Find the "real" metaObject
     while (metaObject->propertyOffset() > propertyIndex)
         metaObject = metaObject->superClass();
     QPair<const QMetaObject *, int> data = qMakePair(metaObject, propertyIndex);
     int accessorIndex = m_accessors.count();
     m_accessors.append(accessor);
     m_index.insert(data, accessorIndex);
 }
Properties
m_accessors
QVector<Accessor> QDeclarativeFastProperties::m_accessors private
Definition at line 68 of file qdeclarativefastproperties_p.h.
Referenced by accessor(), and add().
m_index
QHash<QPair<const QMetaObject *, int>, int> QDeclarativeFastProperties::m_index private
Definition at line 67 of file qdeclarativefastproperties_p.h.
Referenced by accessorIndexForProperty(), and add().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativefastproperties_p.h
/src/declarative/qml/qdeclarativefastproperties.cpp