Qt 4.8: QNlaThread Class Reference
QNlaThread Class Reference
Signals
void networksChanged ()
Signals inherited from QThread
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void forceUpdate ()
QList< QNetworkConfigurationPrivate * > getConfigurations ()
QNlaThread (QNlaEngine *parent=0)
~QNlaThread ()
Public Functions inherited from QThread
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void run ()
The starting point for the thread.
Protected Functions inherited from QThread
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void fetchConfigurations ()
DWORD parseBlob (NLA_BLOB *blob, QNetworkConfigurationPrivate *cpPriv) const
QNetworkConfigurationPrivate * parseQuerySet (const WSAQUERYSET *querySet) const
void updateConfigurations (QList< QNetworkConfigurationPrivate *> &configs)
Properties
bool done
QList< QNetworkConfigurationPrivate * > fetchedConfigurations
HANDLE handle
QMutex mutex
Additional Inherited Members
Public Types inherited from QThread
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Public Slots inherited from QThread
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QThread
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Static Protected Functions inherited from QThread
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 187 of file qnlaengine.cpp.
Constructors and Destructors
QNlaThread()
QNlaThread::QNlaThread (QNlaEngine * parent = 0)
Definition at line 218 of file qnlaengine.cpp.
 :   QThread(parent), handle(0), done(false)
 {
 }
~QNlaThread()
QNlaThread::~QNlaThread ()
Definition at line 223 of file qnlaengine.cpp.
 {
     mutex.lock();
     done = true;
     if (handle) {
         /* cancel completion event */
         if (WSALookupServiceEnd(handle) == SOCKET_ERROR) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("WSALookupServiceEnd error %d", WSAGetLastError());
 #endif
         }
     }
     mutex.unlock();
     wait();
 }
Functions
fetchConfigurations()
void QNlaThread::fetchConfigurations () private
Definition at line 448 of file qnlaengine.cpp.
Referenced by run().
 {
     QList<QNetworkConfigurationPrivate *> foundConfigurations;
     WSAQUERYSET qsRestrictions;
     HANDLE hLookup = 0;
     memset(&qsRestrictions, 0, sizeof(qsRestrictions));
     qsRestrictions.dwSize = sizeof(qsRestrictions);
     qsRestrictions.dwNameSpace = NS_NLA;
     int result = WSALookupServiceBegin(&qsRestrictions, LUP_RETURN_ALL | LUP_DEEP, &hLookup);
     if (result == SOCKET_ERROR) {
         mutex.lock();
         fetchedConfigurations.clear();
         mutex.unlock();
     }
     char buffer[0x10000];
     while (result == 0) {
         DWORD bufferLength = sizeof(buffer);
         result = WSALookupServiceNext(hLookup, LUP_RETURN_ALL,
                                       &bufferLength, reinterpret_cast<WSAQUERYSET *>(buffer));
         if (result == SOCKET_ERROR)
             break;
         QNetworkConfigurationPrivate *cpPriv =
             parseQuerySet(reinterpret_cast<WSAQUERYSET *>(buffer));
         foundConfigurations.append(cpPriv);
     }
     if (hLookup) {
         result = WSALookupServiceEnd(hLookup);
         if (result == SOCKET_ERROR) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("WSALookupServiceEnd error %d", WSAGetLastError());
 #endif
         }
     }
     updateConfigurations(foundConfigurations);
 }
forceUpdate()
void QNlaThread::forceUpdate ()
Definition at line 252 of file qnlaengine.cpp.
Referenced by QNlaEngine::requestUpdate().
 {
     mutex.lock();
     if (handle) {
         /* cancel completion event */
         if (WSALookupServiceEnd(handle) == SOCKET_ERROR) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("WSALookupServiceEnd error %d", WSAGetLastError());
 #endif
         }
         handle = 0;
     }
     mutex.unlock();
 }
getConfigurations()
QList< QNetworkConfigurationPrivate * > QNlaThread::getConfigurations ()
Definition at line 242 of file qnlaengine.cpp.
Referenced by QNlaEngine::networksChanged().
 {
     QMutexLocker locker(&mutex);
     QList<QNetworkConfigurationPrivate *> foundConfigurations = fetchedConfigurations;
     fetchedConfigurations.clear();
     return foundConfigurations;
 }
networksChanged
void QNlaThread::networksChanged () signal
Referenced by updateConfigurations().
parseBlob()
DWORD QNlaThread::parseBlob (NLA_BLOB * blob, QNetworkConfigurationPrivate * cpPriv) const private
Definition at line 352 of file qnlaengine.cpp.
Referenced by parseQuerySet().
 {
 #ifdef BEARER_MANAGEMENT_DEBUG
     printBlob(blob);
 #endif
     switch (blob->header.type) {
     case NLA_RAW_DATA:
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: unhandled header type NLA_RAW_DATA", __FUNCTION__);
 #endif
         break;
     case NLA_INTERFACE:
         cpPriv->state = QNetworkConfiguration::Active;
         if (QNlaEngine *engine = qobject_cast<QNlaEngine *>(parent())) {
             engine->configurationInterface[cpPriv->id.toUInt()] =
                 QString::fromLatin1(blob->data.interfaceData.adapterName);
         }
         break;
     case NLA_802_1X_LOCATION:
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: unhandled header type NLA_802_1X_LOCATION", __FUNCTION__);
 #endif
         break;
     case NLA_CONNECTIVITY:
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: unhandled header type NLA_CONNECTIVITY", __FUNCTION__);
 #endif
         break;
     case NLA_ICS:
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: unhandled header type NLA_ICS", __FUNCTION__);
 #endif
         break;
     default:
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: unhandled header type %d", __FUNCTION__, blob->header.type);
 #endif
         ;
     }
     return blob->header.nextOffset;
 }
parseQuerySet()
QNetworkConfigurationPrivate * QNlaThread::parseQuerySet (const WSAQUERYSET * querySet) const private
Definition at line 396 of file qnlaengine.cpp.
Referenced by fetchConfigurations().
 {
     QNetworkConfigurationPrivate *cpPriv = new QNetworkConfigurationPrivate;
     cpPriv->name = QString::fromWCharArray(querySet->lpszServiceInstanceName);
     cpPriv->isValid = true;
     cpPriv->id = QString::number(qHash(QLatin1String("NLA:") + cpPriv->name));
     cpPriv->state = QNetworkConfiguration::Defined;
     cpPriv->type = QNetworkConfiguration::InternetAccessPoint;
 #ifdef BEARER_MANAGEMENT_DEBUG
     qDebug() << "size:" << querySet->dwSize;
     qDebug() << "service instance name:" << QString::fromUtf16(querySet->lpszServiceInstanceName);
     qDebug() << "service class id:" << querySet->lpServiceClassId;
     qDebug() << "version:" << querySet->lpVersion;
     qDebug() << "comment:" << QString::fromUtf16(querySet->lpszComment);
     qDebug() << "namespace:" << querySet->dwNameSpace;
     qDebug() << "namespace provider id:" << querySet->lpNSProviderId;
     qDebug() << "context:" << QString::fromUtf16(querySet->lpszContext);
     qDebug() << "number of protocols:" << querySet->dwNumberOfProtocols;
     qDebug() << "protocols:" << querySet->lpafpProtocols;
     qDebug() << "query string:" << QString::fromUtf16(querySet->lpszQueryString);
     qDebug() << "number of cs addresses:" << querySet->dwNumberOfCsAddrs;
     qDebug() << "cs addresses:" << querySet->lpcsaBuffer;
     qDebug() << "output flags:" << querySet->dwOutputFlags;
 #endif
     if (querySet->lpBlob) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "blob size:" << querySet->lpBlob->cbSize;
         qDebug() << "blob data:" << querySet->lpBlob->pBlobData;
 #endif
         DWORD offset = 0;
         do {
             NLA_BLOB *blob = reinterpret_cast<NLA_BLOB *>(querySet->lpBlob->pBlobData + offset);
             DWORD nextOffset = parseBlob(blob, cpPriv);
             if (nextOffset == offset)
                 break;
             else
                 offset = nextOffset;
         } while (offset != 0 && offset < querySet->lpBlob->cbSize);
     }
     if (QNlaEngine *engine = qobject_cast<QNlaEngine *>(parent())) {
         const QString interface = engine->getInterfaceFromId(cpPriv->id);
         cpPriv->bearerType = qGetInterfaceType(interface);
     }
     return cpPriv;
 }
run()
void QNlaThread::run (void) protected virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented from QThread.
Definition at line 268 of file qnlaengine.cpp.
 {
     WSAEVENT changeEvent = WSACreateEvent();
     if (changeEvent == WSA_INVALID_EVENT)
         return;
     while (true) {
         fetchConfigurations();
         WSAQUERYSET qsRestrictions;
         memset(&qsRestrictions, 0, sizeof(qsRestrictions));
         qsRestrictions.dwSize = sizeof(qsRestrictions);
         qsRestrictions.dwNameSpace = NS_NLA;
         mutex.lock();
         if (done) {
             mutex.unlock();
             break;
         }
         int result = WSALookupServiceBegin(&qsRestrictions, LUP_RETURN_ALL, &handle);
         mutex.unlock();
         if (result == SOCKET_ERROR)
             break;
         WSACOMPLETION completion;
         WSAOVERLAPPED overlapped;
         memset(&overlapped, 0, sizeof(overlapped));
         overlapped.hEvent = changeEvent;
         memset(&completion, 0, sizeof(completion));
         completion.Type = NSP_NOTIFY_EVENT;
         completion.Parameters.Event.lpOverlapped = &overlapped;
         DWORD bytesReturned = 0;
         result = WSANSPIoctl(handle, SIO_NSP_NOTIFY_CHANGE, 0, 0, 0, 0,
                              &bytesReturned, &completion);
         if (result == SOCKET_ERROR) {
             if (WSAGetLastError() != WSA_IO_PENDING)
                 break;
         }
 #ifndef Q_OS_WINCE
         // Not interested in unrelated IO completion events
         // although we also don't want to block them
         while (WaitForSingleObjectEx(changeEvent, WSA_INFINITE, true) != WAIT_IO_COMPLETION &&
                handle)
         {
         }
 #else
         WaitForSingleObject(changeEvent, WSA_INFINITE);
 #endif
         mutex.lock();
         if (handle) {
             result = WSALookupServiceEnd(handle);
             if (result == SOCKET_ERROR) {
                 mutex.unlock();
                 break;
             }
             handle = 0;
         }
         mutex.unlock();
     }
     WSACloseEvent(changeEvent);
 }
updateConfigurations()
void QNlaThread::updateConfigurations (QList< QNetworkConfigurationPrivate *> & configs) private
Definition at line 338 of file qnlaengine.cpp.
Referenced by fetchConfigurations().
 {
     mutex.lock();
     while (!fetchedConfigurations.isEmpty())
         delete fetchedConfigurations.takeFirst();
     fetchedConfigurations = configs;
     mutex.unlock();
     emit networksChanged();
 }
Properties
done
bool QNlaThread::done private
Definition at line 214 of file qnlaengine.cpp.
Referenced by run(), and ~QNlaThread().
fetchedConfigurations
QList<QNetworkConfigurationPrivate *> QNlaThread::fetchedConfigurations private
Definition at line 215 of file qnlaengine.cpp.
Referenced by fetchConfigurations(), getConfigurations(), and updateConfigurations().
handle
HANDLE QNlaThread::handle private
Definition at line 213 of file qnlaengine.cpp.
Referenced by forceUpdate(), run(), and ~QNlaThread().
mutex
QMutex QNlaThread::mutex private
Definition at line 212 of file qnlaengine.cpp.
Referenced by fetchConfigurations(), forceUpdate(), getConfigurations(), run(), updateConfigurations(), and ~QNlaThread().
The documentation for this class was generated from the following file:
/src/plugins/bearer/nla/qnlaengine.cpp