Qt 4.8: QPatternist::AbstractDuration Class Reference
QPatternist::AbstractDuration Class Reference abstract
Base class for classes implementing durations.
#include <qabstractduration_p.h>
Classes
class CaptureTable
Acts as a mapping table for AbstractDuration::create() and describes where certain fields in a QRegExp pattern can be found for a particular W3C XML Schema duration type.
Public Types
typedef QExplicitlySharedDataPointer< AbstractDuration > Ptr
typedef qint64 Value
The amount in milli seconds.
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual DayCountProperty days () const =0
virtual Item fromValue (const Value val) const =0
virtual HourProperty hours () const =0
bool isPositive () const
virtual MinuteProperty minutes () const =0
virtual MonthProperty months () const =0
virtual MSecondProperty mseconds () const =0
bool operator== (const AbstractDuration &other) const
virtual SecondProperty seconds () const =0
virtual Value value () const =0
virtual YearProperty years () const =0
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual QString stringValue () const =0
virtual ItemType::Ptr type () const =0
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Protected Functions
AbstractDuration (const bool isPos)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Static Protected Functions
static AtomicValue::Ptr create (const CaptureTable &captTable, const QString &lexical, bool *isPositive, YearProperty *years, MonthProperty *months, DayCountProperty *days, HourProperty *hours, MinuteProperty *minutes, SecondProperty *seconds, MSecondProperty *mseconds)
static QString serializeMSeconds (const MSecondProperty mseconds)
Protected Variables
const bool m_isPositive
Additional Inherited Members
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Base class for classes implementing durations.
See also
XML Schema Part 2: Datatypes Second Edition, 3.2.6 duration
XQuery 1.0 and XPath 2.0 Data Model (XDM), 3.3.2 Dates and Times
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 76 of file qabstractduration_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<AbstractDuration> QPatternist::AbstractDuration::Ptr
Definition at line 79 of file qabstractduration_p.h.
Value
typedef qint64 QPatternist::AbstractDuration::Value
The amount in milli seconds.
Definition at line 84 of file qabstractduration_p.h.
Constructors and Destructors
AbstractDuration()
AbstractDuration::AbstractDuration (const bool isPos) protected
Definition at line 54 of file qabstractduration.cpp.
                                                    : m_isPositive(isPos)
 {
 }
Functions
create()
AtomicValue::Ptr AbstractDuration::create (const CaptureTable & captTable, const QString & lexical, bool * isPositive, YearProperty * years, MonthProperty * months, DayCountProperty * days, HourProperty * hours, MinuteProperty * minutes, SecondProperty * seconds, MSecondProperty * mseconds) static protected
Definition at line 61 of file qabstractduration.cpp.
Referenced by QPatternist::Duration::fromLexical(), QPatternist::YearMonthDuration::fromLexical(), and QPatternist::DayTimeDuration::fromLexical().
 {
     /* We don't directly write into the arguments(eg @p years) but uses these
      * because the arguments are intended for normalized values, and therefore
      * can cause overflows. */
     MonthCountProperty monthCount = 0;
     MinuteCountProperty minCount = 0;
     HourCountProperty hourCount = 0;
     SecondCountProperty secCount = 0;
     Q_ASSERT(isPositive);
     QRegExp myExp(captTable.regExp); /* Copy, in order to stay thread safe. */
     if(!myExp.exactMatch(lexical))
     {
         error(QString());
     }
     const QStringList capts(myExp.capturedTexts());
     if(days)
     {
         if(getCapt(tDelimiter).isEmpty())
         {
             if((years && getCapt(year).isEmpty() && getCapt(month).isEmpty() && getCapt(day).isEmpty())
                 ||
                (!years && getCapt(day).isEmpty()))
             {
                 error(QtXmlPatterns::tr("At least one component must be present."));
             }
         }
         else if(getCapt(hour).isEmpty() &&
                 getCapt(minutes).isEmpty() &&
                 getCapt(seconds).isEmpty() &&
                 getCapt(mseconds).isEmpty())
         {
             error(QtXmlPatterns::tr("At least one time component must appear "
                                     "after the %1-delimiter.")
                                     .arg(formatKeyword("T")));
         }
     }
     else if(getCapt(year).isEmpty() && getCapt(month).isEmpty()) /* This checks xs:yearMonthDuration. */
     {
         error(QtXmlPatterns::tr("At least one component must be present."));
     }
     /* If we got no '-', we are positive. */
     *isPositive = capts.at(1).isEmpty();
     if(days)
     {
         Q_ASSERT(hours);
         Q_ASSERT(minutes);
         Q_ASSERT(seconds);
         Q_ASSERT(mseconds);
         *days = getCapt(day).toInt();
         hourCount = getCapt(hour).toInt();
         minCount = getCapt(minutes).toInt();
         secCount = getCapt(seconds).toInt();
         const QString msecondsStr(getCapt(mseconds));
         if(!msecondsStr.isEmpty())
             *mseconds = msecondsStr.leftJustified(3, QLatin1Char('0')).toInt();
         else
             *mseconds = msecondsStr.toInt();
         if(secCount > 59)
         {
             minCount += secCount / 60;
             *seconds = secCount % 60;
         }
         else
             *seconds = secCount;
         if(minCount > 59)
         {
             hourCount += minCount / 60;
             *minutes = minCount % 60;
         }
         else
             *minutes = minCount;
         if(hourCount > 23)
         {
             *days += hourCount / 24;
             *hours = hourCount % 24;
         }
         else
             *hours = hourCount;
     }
     if(!years)
         return AtomicValue::Ptr();
     /* We're supposed to handle years/months. */
     Q_ASSERT(months);
     *years = getCapt(year).toInt();
     monthCount = getCapt(month).toInt();
     if(monthCount > 11)
     {
         *years += monthCount / 12;
         *months = monthCount % 12;
     }
     else
         *months = monthCount;
     return AtomicValue::Ptr();
 }
days()
virtual DayCountProperty QPatternist::AbstractDuration::days () const pure virtual
Implemented in QPatternist::YearMonthDuration, QPatternist::DayTimeDuration, and QPatternist::Duration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::DaysFromDurationFN::extract(), and operator==().
fromValue()
virtual Item QPatternist::AbstractDuration::fromValue (const Value val) const pure virtual
A polymorphic factory function that returns instances of the sub-class with the value val.
Implemented in QPatternist::DayTimeDuration, QPatternist::Duration, and QPatternist::YearMonthDuration.
hours()
virtual HourProperty QPatternist::AbstractDuration::hours () const pure virtual
Implemented in QPatternist::YearMonthDuration, QPatternist::DayTimeDuration, and QPatternist::Duration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::HoursFromDurationFN::extract(), and operator==().
isPositive()
bool AbstractDuration::isPositive () const
Determines whether this AbstractDuration is positive. For example, "P10H" is positive, while "-P10H" is not.
Note
Do not re-implement this function. Use the constructor, AbstractDuration(), for changing the value.
Returns
true if this AbstractDuration is positive, otherwise false.
Definition at line 230 of file qabstractduration.cpp.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::AbstractDurationToYearMonthDurationCaster::castFrom(), QPatternist::YearsFromDurationFN::extract(), QPatternist::MonthsFromDurationFN::extract(), QPatternist::DaysFromDurationFN::extract(), QPatternist::HoursFromDurationFN::extract(), QPatternist::MinutesFromDurationFN::extract(), QPatternist::SecondsFromDurationFN::extract(), and operator==().
 {
     return m_isPositive;
 }
minutes()
virtual MinuteProperty QPatternist::AbstractDuration::minutes () const pure virtual
Implemented in QPatternist::YearMonthDuration, QPatternist::DayTimeDuration, and QPatternist::Duration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::MinutesFromDurationFN::extract(), and operator==().
months()
virtual MonthProperty QPatternist::AbstractDuration::months () const pure virtual
Implemented in QPatternist::DayTimeDuration, QPatternist::YearMonthDuration, and QPatternist::Duration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToYearMonthDurationCaster::castFrom(), QPatternist::MonthsFromDurationFN::extract(), and operator==().
mseconds()
virtual MSecondProperty QPatternist::AbstractDuration::mseconds () const pure virtual
Implemented in QPatternist::YearMonthDuration, QPatternist::DayTimeDuration, and QPatternist::Duration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::SecondsFromDurationFN::extract(), operator==(), and serializeMSeconds().
operator==()
bool AbstractDuration::operator== (const AbstractDuration & other) const
Determines whether this Duration is equal to other.
Note
Do not re-implement this function. It uses getters such as years() and mseconds() for determining its truth value.
Definition at line 185 of file qabstractduration.cpp.
 {
     if(years() == other.years()
        && months() == other.months()
        && days() == other.days()
        && hours() == other.hours()
        && minutes() == other.minutes()
        && seconds() == other.seconds()
        && mseconds() == other.mseconds())
     {
         if(isPositive() == other.isPositive())
             return true;
         else if(years() == 0
                 && months() == 0
                 && days() == 0
                 && hours() == 0
                 && minutes() == 0
                 && seconds () == 0
                 && mseconds() == 0)
         {
             return true; /* Signedness doesn't matter if all are zero. */
         }
     }
     return false;
 }
seconds()
virtual SecondProperty QPatternist::AbstractDuration::seconds () const pure virtual
Implemented in QPatternist::YearMonthDuration, QPatternist::DayTimeDuration, and QPatternist::Duration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToDayTimeDurationCaster::castFrom(), QPatternist::SecondsFromDurationFN::extract(), and operator==().
serializeMSeconds()
QString AbstractDuration::serializeMSeconds (const MSecondProperty mseconds) static protected
Definition at line 212 of file qabstractduration.cpp.
Referenced by QPatternist::Duration::stringValue(), and QPatternist::DayTimeDuration::stringValue().
 {
     QString retval;
     retval.append(QLatin1Char('.'));
     int div = 100;
     MSecondProperty msecs = mseconds;
     while(msecs > 0)
     {
         int d = msecs / div;
         retval.append(QLatin1Char(d + '0'));
         msecs = msecs % div;
         div = div / 10;
     }
     return retval;
 }
value()
virtual Value QPatternist::AbstractDuration::value () const pure virtual
Returns
the value of this AbstractDuration. For example, in the case of xs:yearMonthDuration, that is YearMonthDuration, years times twelve plus the months is returned.
Implemented in QPatternist::DayTimeDuration, QPatternist::Duration, and QPatternist::YearMonthDuration.
years()
virtual YearProperty QPatternist::AbstractDuration::years () const pure virtual
Implemented in QPatternist::DayTimeDuration, QPatternist::Duration, and QPatternist::YearMonthDuration.
Referenced by QPatternist::AbstractDurationComparator::addDurationToDateTime(), QPatternist::AbstractDurationToDurationCaster::castFrom(), QPatternist::AbstractDurationToYearMonthDurationCaster::castFrom(), QPatternist::YearsFromDurationFN::extract(), and operator==().
Properties
m_isPositive
const bool QPatternist::AbstractDuration::m_isPositive protected
Definition at line 184 of file qabstractduration_p.h.
Referenced by isPositive(), QPatternist::YearMonthDuration::stringValue(), QPatternist::Duration::stringValue(), QPatternist::DayTimeDuration::stringValue(), QPatternist::YearMonthDuration::value(), and QPatternist::DayTimeDuration::value().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qabstractduration_p.h
/src/xmlpatterns/data/qabstractduration.cpp