Qt 4.8: QScriptDebuggerFrontend Class Reference
QScriptDebuggerFrontend Class Reference abstract
The QScriptDebuggerFrontend class is the base class of debugger front-ends.
#include <qscriptdebuggerfrontend_p.h>
Public Functions
QScriptDebuggerEventHandlerInterface * eventHandler () const
QScriptDebuggerFrontend ()
int scheduleCommand (const QScriptDebuggerCommand &command, QScriptDebuggerResponseHandlerInterface *responseHandler)
Schedules the given command for execution by this front-end, and returns a unique identifier associated with this command.
int scheduledCommandCount () const
void setEventHandler (QScriptDebuggerEventHandlerInterface *eventHandler)
virtual ~QScriptDebuggerFrontend ()
Public Functions inherited from QScriptDebuggerCommandSchedulerInterface
virtual ~QScriptDebuggerCommandSchedulerInterface ()
Protected Functions
void notifyCommandFinished (int id, const QScriptDebuggerResponse &response)
Subclasses should call this function when the command identified by the given id has finished and produced the given response.
bool notifyEvent (const QScriptDebuggerEvent &event)
Subclasses should call this function when the given event is received from the back-end.
virtual void processCommand (int id, const QScriptDebuggerCommand &command)=0
Subclasses must reimplement this function to process the given command identified by id.
QScriptDebuggerFrontend (QScriptDebuggerFrontendPrivate &dd)
Protected Variables
QScopedPointer< QScriptDebuggerFrontendPrivate > d_ptr
Detailed Description
The QScriptDebuggerFrontend class is the base class of debugger front-ends.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 70 of file qscriptdebuggerfrontend_p.h.
Constructors and Destructors
QScriptDebuggerFrontend() [1/2]
QScriptDebuggerFrontend::QScriptDebuggerFrontend ()
Definition at line 141 of file qscriptdebuggerfrontend.cpp.
     : d_ptr(new QScriptDebuggerFrontendPrivate())
 {
     d_ptr->q_ptr = this;
 }
~QScriptDebuggerFrontend()
QScriptDebuggerFrontend::~QScriptDebuggerFrontend () virtual
Definition at line 147 of file qscriptdebuggerfrontend.cpp.
 {
 }
QScriptDebuggerFrontend() [2/2]
QScriptDebuggerFrontend::QScriptDebuggerFrontend (QScriptDebuggerFrontendPrivate & dd) protected
Definition at line 151 of file qscriptdebuggerfrontend.cpp.
     : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
 }
Functions
eventHandler()
QScriptDebuggerEventHandlerInterface * QScriptDebuggerFrontend::eventHandler () const
Definition at line 157 of file qscriptdebuggerfrontend.cpp.
Referenced by setEventHandler().
 {
     Q_D(const QScriptDebuggerFrontend);
     return d->eventHandler;
 }
notifyCommandFinished()
void QScriptDebuggerFrontend::notifyCommandFinished (int id, const QScriptDebuggerResponse & response) protected
Subclasses should call this function when the command identified by the given id has finished and produced the given response.
See also
processCommand(), notifyEvent()
Definition at line 200 of file qscriptdebuggerfrontend.cpp.
 {
     Q_D(QScriptDebuggerFrontend);
     if (d->responseHandlers.contains(id)) {
         QScriptDebuggerResponseHandlerInterface *handler = d->responseHandlers.take(id);
         Q_ASSERT(handler != 0);
         handler->handleResponse(response, id);
     }
 }
notifyEvent()
bool QScriptDebuggerFrontend::notifyEvent (const QScriptDebuggerEvent & event) protected
Subclasses should call this function when the given event is received from the back-end.
See also
notifyCommandFinished(), QScriptDebuggerBackend::event()
Definition at line 216 of file qscriptdebuggerfrontend.cpp.
 {
     Q_D(QScriptDebuggerFrontend);
     if (d->eventHandler)
         return d->eventHandler->debuggerEvent(event);
     return false;
 }
processCommand()
void QScriptDebuggerFrontend::processCommand (int id, const QScriptDebuggerCommand & command) protected pure virtual
Subclasses must reimplement this function to process the given command identified by id.
Call notifyCommandFinished() when processing is complete.
Implemented in QScriptEngineDebuggerFrontend.
scheduleCommand()
int QScriptDebuggerFrontend::scheduleCommand (const QScriptDebuggerCommand & command, QScriptDebuggerResponseHandlerInterface * responseHandler) virtual
Schedules the given command for execution by this front-end, and returns a unique identifier associated with this command.
Subclasses can call this function to schedule custom commands.
See also
notifyCommandFinished()
Implements QScriptDebuggerCommandSchedulerInterface.
Definition at line 177 of file qscriptdebuggerfrontend.cpp.
Referenced by QScriptDebuggerPrivate::scheduleCommand().
 {
     Q_D(QScriptDebuggerFrontend);
     int id = ++d->nextCommandId;
     d->pendingCommands.append(command);
     d->pendingCommandIds.append(id);
     if (responseHandler)
         d->responseHandlers.insert(id, responseHandler);
     if (d->pendingCommands.size() == 1) {
         QEvent *e = new QEvent(QEvent::Type(QEvent::User+2)); // ProcessCommands
         d->postEvent(e);
     }
     return id;
 }
scheduledCommandCount()
int QScriptDebuggerFrontend::scheduledCommandCount () const
Definition at line 224 of file qscriptdebuggerfrontend.cpp.
 {
     Q_D(const QScriptDebuggerFrontend);
     return d->nextCommandId;
 }
setEventHandler()
void QScriptDebuggerFrontend::setEventHandler (QScriptDebuggerEventHandlerInterface * eventHandler)
Definition at line 163 of file qscriptdebuggerfrontend.cpp.
Referenced by QScriptDebugger::setFrontend().
 {
     Q_D(QScriptDebuggerFrontend);
     d->eventHandler = eventHandler;
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerFrontendPrivate> QScriptDebuggerFrontend::d_ptr protected
Definition at line 93 of file qscriptdebuggerfrontend_p.h.
Referenced by QScriptDebuggerFrontend().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerfrontend_p.h
/src/scripttools/debugging/qscriptdebuggerfrontend.cpp