Qt 4.8: QGridLayoutItem Class Reference
QGridLayoutItem Class Reference
#include <qgridlayoutengine_p.h>
Public Functions
Qt::Alignment alignment () const
QGridLayoutBox box (Qt::Orientation orientation, qreal constraint=-1.0) const
int columnSpan () const
int columnSpan (Qt::Orientation orientation) const
QSizePolicy::ControlTypes controlTypes (LayoutSide side) const
void dump (int indent=0) const
Qt::Orientation dynamicConstraintOrientation () const
QSizeF effectiveMaxSize (const QSizeF &constraint) const
int firstColumn () const
int firstColumn (Qt::Orientation orientation) const
int firstRow () const
int firstRow (Qt::Orientation orientation) const
QRectF geometryWithin (qreal x, qreal y, qreal width, qreal height, qreal rowDescent) const
bool hasDynamicConstraint () const
void insertOrRemoveRows (int row, int delta, Qt::Orientation orientation=Qt::Vertical)
int lastColumn () const
int lastColumn (Qt::Orientation orientation) const
int lastRow () const
int lastRow (Qt::Orientation orientation) const
QGraphicsLayoutItem * layoutItem () const
QGridLayoutItem (QGridLayoutEngine *engine, QGraphicsLayoutItem *layoutItem, int row, int column, int rowSpan=1, int columnSpan=1, Qt::Alignment alignment=0, int itemAtIndex=-1)
int rowSpan () const
int rowSpan (Qt::Orientation orientation) const
void setAlignment (Qt::Alignment alignment)
void setFirstRow (int row, Qt::Orientation orientation=Qt::Vertical)
void setGeometry (const QRectF &rect)
void setRowSpan (int rowSpan, Qt::Orientation orientation=Qt::Vertical)
void setStretchFactor (int stretch, Qt::Orientation orientation)
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
QSizePolicy::Policy sizePolicy (Qt::Orientation orientation) const
int stretchFactor (Qt::Orientation orientation) const
void transpose ()
Properties
Qt::Alignment q_alignment
QGridLayoutEngine * q_engine
int q_firstRows [NOrientations]
QGraphicsLayoutItem * q_layoutItem
int q_rowSpans [NOrientations]
int q_stretches [NOrientations]
Detailed Description
Definition at line 254 of file qgridlayoutengine_p.h.
Constructors and Destructors
QGridLayoutItem()
QGridLayoutItem::QGridLayoutItem (QGridLayoutEngine * engine, QGraphicsLayoutItem * layoutItem, int row, int column, int rowSpan = 1, int columnSpan = 1, Qt::Alignment alignment = 0, int itemAtIndex = -1)
Definition at line 487 of file qgridlayoutengine.cpp.
     : q_engine(engine), q_layoutItem(layoutItem), q_alignment(alignment)
 {
     q_firstRows[Hor] = column;
     q_firstRows[Ver] = row;
     q_rowSpans[Hor] = columnSpan;
     q_rowSpans[Ver] = rowSpan;
     q_stretches[Hor] = -1;
     q_stretches[Ver] = -1;
     q_engine->insertItem(this, itemAtIndex);
 }
Functions
alignment()
Qt::Alignment QGridLayoutItem::alignment () const inline
Definition at line 280 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::effectiveAlignment(), and QGridLayoutEngine::setRowAlignment().
 { return q_alignment; }
box()
QGridLayoutBox QGridLayoutItem::box (Qt::Orientation orientation, qreal constraint = -1.0) const
Definition at line 600 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::fillRowData(), and geometryWithin().
 {
     QGridLayoutBox result;
     QSizePolicy::Policy policy = sizePolicy(orientation);
     if (orientation == Qt::Horizontal) {
         QSizeF constraintSize(-1.0, constraint);
         result.q_preferredSize = sizeHint(Qt::PreferredSize, constraintSize).width();
         if (policy & QSizePolicy::ShrinkFlag) {
             result.q_minimumSize = sizeHint(Qt::MinimumSize, constraintSize).width();
         } else {
             result.q_minimumSize = result.q_preferredSize;
         }
         if (policy & (QSizePolicy::GrowFlag | QSizePolicy::ExpandFlag)) {
             result.q_maximumSize = sizeHint(Qt::MaximumSize, constraintSize).width();
         } else {
             result.q_maximumSize = result.q_preferredSize;
         }
     } else {
         QSizeF constraintSize(constraint, -1.0);
         result.q_preferredSize = sizeHint(Qt::PreferredSize, constraintSize).height();
         if (policy & QSizePolicy::ShrinkFlag) {
             result.q_minimumSize = sizeHint(Qt::MinimumSize, constraintSize).height();
         } else {
             result.q_minimumSize = result.q_preferredSize;
         }
         if (policy & (QSizePolicy::GrowFlag | QSizePolicy::ExpandFlag)) {
             result.q_maximumSize = sizeHint(Qt::MaximumSize, constraintSize).height();
         } else {
             result.q_maximumSize = result.q_preferredSize;
         }
         result.q_minimumDescent = sizeHint(Qt::MinimumDescent, constraintSize).height();
         if (result.q_minimumDescent >= 0.0)
             result.q_minimumAscent = result.q_minimumSize - result.q_minimumDescent;
     }
     if (policy & QSizePolicy::IgnoreFlag)
         result.q_preferredSize = result.q_minimumSize;
     return result;
 }
columnSpan() [1/2]
int QGridLayoutItem::columnSpan () const inline
Definition at line 264 of file qgridlayoutengine_p.h.
Referenced by dump(), QGridLayoutEngine::fillRowData(), lastColumn(), QGridLayoutItem(), and QGridLayoutEngine::setGeometries().
 { return q_rowSpans[Hor]; }
columnSpan() [2/2]
int QGridLayoutItem::columnSpan (Qt::Orientation orientation) const
Definition at line 527 of file qgridlayoutengine.cpp.
 {
     return q_rowSpans[orientation == Qt::Horizontal];
 }
controlTypes()
QSizePolicy::ControlTypes QGridLayoutItem::controlTypes (LayoutSide side) const
Definition at line 590 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::fillRowData().
 {
     return q_layoutItem->sizePolicy().controlType();
 }
dump()
void QGridLayoutItem::dump (int indent = 0) const
Definition at line 754 of file qgridlayoutengine.cpp.
 {
     qDebug("%*s%p (%d, %d) %d x %d", indent, "", q_layoutItem, firstRow(), firstColumn(),
            rowSpan(), columnSpan());
     if (q_stretches[Hor] >= 0)
         qDebug("%*s Horizontal stretch: %d", indent, "", q_stretches[Hor]);
     if (q_stretches[Ver] >= 0)
         qDebug("%*s Vertical stretch: %d", indent, "", q_stretches[Ver]);
     if (q_alignment != 0)
         qDebug("%*s Alignment: %x", indent, "", uint(q_alignment));
     qDebug("%*s Horizontal size policy: %x Vertical size policy: %x",
         indent, "", sizePolicy(Qt::Horizontal), sizePolicy(Qt::Vertical));
 }
dynamicConstraintOrientation()
Qt::Orientation QGridLayoutItem::dynamicConstraintOrientation () const
Definition at line 582 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::ensureDynamicConstraint(), QGridLayoutEngine::fillRowData(), and geometryWithin().
 {
     if (QGraphicsLayoutItemPrivate::get(q_layoutItem)->hasHeightForWidth())
         return Qt::Vertical;
     else //if (QGraphicsLayoutItemPrivate::get(q_layoutItem)->hasWidthForHeight())
         return Qt::Horizontal;
 }
effectiveMaxSize()
QSizeF QGridLayoutItem::effectiveMaxSize (const QSizeF & constraint) const
Warning
This function is not part of the public interface. returns the effective maximumSize, will take the sizepolicy into consideration. (i.e. if sizepolicy does not have QSizePolicy::Grow, then maxSizeHint will be the preferredSize) Note that effectiveSizeHint does not take sizePolicy into consideration, (since it only evaluates the hints, as the name implies)
Definition at line 730 of file qgridlayoutengine.cpp.
Referenced by geometryWithin().
 {
     QSizeF size = constraint;
     bool vGrow = (sizePolicy(Qt::Vertical) & QSizePolicy::GrowFlag) == QSizePolicy::GrowFlag;
     bool hGrow = (sizePolicy(Qt::Horizontal) & QSizePolicy::GrowFlag) == QSizePolicy::GrowFlag;
     if (!vGrow || !hGrow) {
         QSizeF pref = layoutItem()->effectiveSizeHint(Qt::PreferredSize, constraint);
         if (!vGrow)
             size.setHeight(pref.height());
         if (!hGrow)
             size.setWidth(pref.width());
     }
     if (!size.isValid()) {
         QSizeF maxSize = layoutItem()->effectiveSizeHint(Qt::MaximumSize, size);
         if (size.width() == -1)
             size.setWidth(maxSize.width());
         if (size.height() == -1)
             size.setHeight(maxSize.height());
     }
     return size;
 }
firstColumn() [1/2]
int QGridLayoutItem::firstColumn () const inline
Definition at line 262 of file qgridlayoutengine_p.h.
Referenced by dump(), QGridLayoutEngine::effectiveAlignment(), QGridLayoutEngine::fillRowData(), QGridLayoutEngine::insertItem(), lastColumn(), QGridLayoutEngine::regenerateGrid(), QGridLayoutEngine::removeItem(), and QGridLayoutEngine::setGeometries().
 { return q_firstRows[Hor]; }
firstColumn() [2/2]
int QGridLayoutItem::firstColumn (Qt::Orientation orientation) const
Definition at line 507 of file qgridlayoutengine.cpp.
 {
     return q_firstRows[orientation == Qt::Horizontal];
 }
firstRow() [1/2]
int QGridLayoutItem::firstRow () const inline
Definition at line 261 of file qgridlayoutengine_p.h.
Referenced by dump(), QGridLayoutEngine::effectiveAlignment(), QGridLayoutEngine::ensureEffectiveFirstAndLastRows(), QGridLayoutEngine::fillRowData(), QGridLayoutEngine::insertItem(), insertOrRemoveRows(), lastRow(), QGridLayoutEngine::regenerateGrid(), QGraphicsLinearLayoutPrivate::removeGridItem(), QGridLayoutEngine::removeItem(), and QGridLayoutEngine::setGeometries().
 { return q_firstRows[Ver]; }
firstRow() [2/2]
int QGridLayoutItem::firstRow (Qt::Orientation orientation) const
Definition at line 502 of file qgridlayoutengine.cpp.
 {
     return q_firstRows[orientation == Qt::Vertical];
 }
geometryWithin()
QRectF QGridLayoutItem::geometryWithin (qreal x, qreal y, qreal width, qreal height, qreal rowDescent) const
Definition at line 648 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::fillRowData(), and QGridLayoutEngine::setGeometries().
 {
     rowDescent = -1.0; // ### This disables the descent
     QGridLayoutBox vBox = box(Qt::Vertical);
     if (vBox.q_minimumDescent < 0.0 || rowDescent < 0.0) {
         qreal cellWidth = width;
         qreal cellHeight = height;
         QSizeF size = effectiveMaxSize(QSizeF(-1,-1));
         if (hasDynamicConstraint()) {
             if (dynamicConstraintOrientation() == Qt::Vertical) {
                if (size.width() > cellWidth)
                    size = effectiveMaxSize(QSizeF(cellWidth, -1));
             } else if (size.height() > cellHeight) {
                 size = effectiveMaxSize(QSizeF(-1, cellHeight));
             }
         }
         size = size.boundedTo(QSizeF(cellWidth, cellHeight));
         width = size.width();
         height = size.height();
         Qt::Alignment align = q_engine->effectiveAlignment(this);
         switch (align & Qt::AlignHorizontal_Mask) {
         case Qt::AlignHCenter:
             x += (cellWidth - width)/2;
             break;
         case Qt::AlignRight:
             x += cellWidth - width;
             break;
         default:
             break;
         }
         switch (align & Qt::AlignVertical_Mask) {
         case Qt::AlignVCenter:
             y += (cellHeight - height)/2;
             break;
         case Qt::AlignBottom:
             y += cellHeight - height;
             break;
         default:
             break;
         }
         return QRectF(x, y, width, height);
     } else {
         qreal descent = vBox.q_minimumDescent;
         qreal ascent = vBox.q_minimumSize - descent;
         return QRectF(x, y + height - rowDescent - ascent, width, ascent + descent);
     }
 }
hasDynamicConstraint()
bool QGridLayoutItem::hasDynamicConstraint () const
Definition at line 576 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::ensureDynamicConstraint(), QGridLayoutEngine::fillRowData(), geometryWithin(), and QGridLayoutEngine::sizeHint().
 {
     return QGraphicsLayoutItemPrivate::get(q_layoutItem)->hasHeightForWidth()
         || QGraphicsLayoutItemPrivate::get(q_layoutItem)->hasWidthForHeight();
 }
insertOrRemoveRows()
void QGridLayoutItem::insertOrRemoveRows (int row, int delta, Qt::Orientation orientation = Qt::Vertical)
Definition at line 713 of file qgridlayoutengine.cpp.
 {
     int oldFirstRow = firstRow(orientation);
     if (oldFirstRow >= row) {
         setFirstRow(oldFirstRow + delta, orientation);
     } else if (lastRow(orientation) >= row) {
         setRowSpan(rowSpan(orientation) + delta, orientation);
     }
 }
lastColumn() [1/2]
int QGridLayoutItem::lastColumn () const inline
Definition at line 266 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::cellRect(), QGridLayoutEngine::fillRowData(), QGridLayoutEngine::insertItem(), QGridLayoutEngine::regenerateGrid(), QGridLayoutEngine::removeItem(), and QGridLayoutEngine::setGeometries().
 { return firstColumn() + columnSpan() - 1; }
lastColumn() [2/2]
int QGridLayoutItem::lastColumn (Qt::Orientation orientation) const
Definition at line 517 of file qgridlayoutengine.cpp.
 {
     return firstColumn(orientation) + columnSpan(orientation) - 1;
 }
lastRow() [1/2]
int QGridLayoutItem::lastRow () const inline
Definition at line 265 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::cellRect(), QGridLayoutEngine::ensureEffectiveFirstAndLastRows(), QGridLayoutEngine::insertItem(), insertOrRemoveRows(), QGridLayoutEngine::regenerateGrid(), QGridLayoutEngine::removeItem(), and QGridLayoutEngine::setGeometries().
 { return firstRow() + rowSpan() - 1; }
lastRow() [2/2]
int QGridLayoutItem::lastRow (Qt::Orientation orientation) const
Definition at line 512 of file qgridlayoutengine.cpp.
 {
     return firstRow(orientation) + rowSpan(orientation) - 1;
 }
layoutItem()
QGraphicsLayoutItem* QGridLayoutItem::layoutItem () const inline
Definition at line 293 of file qgridlayoutengine_p.h.
Referenced by effectiveMaxSize(), and QGridLayoutEngine::findLayoutItem().
 { return q_layoutItem; }
rowSpan() [1/2]
int QGridLayoutItem::rowSpan () const inline
Definition at line 263 of file qgridlayoutengine_p.h.
Referenced by dump(), QGridLayoutEngine::fillRowData(), insertOrRemoveRows(), lastRow(), QGridLayoutItem(), QGridLayoutEngine::setGeometries(), and setRowSpan().
 { return q_rowSpans[Ver]; }
rowSpan() [2/2]
int QGridLayoutItem::rowSpan (Qt::Orientation orientation) const
Definition at line 522 of file qgridlayoutengine.cpp.
 {
     return q_rowSpans[orientation == Qt::Vertical];
 }
setAlignment()
void QGridLayoutItem::setAlignment (Qt::Alignment alignment) inline
Definition at line 281 of file qgridlayoutengine_p.h.
 { q_alignment = alignment; }
setFirstRow()
void QGridLayoutItem::setFirstRow (int row, Qt::Orientation orientation = Qt::Vertical)
Definition at line 532 of file qgridlayoutengine.cpp.
Referenced by insertOrRemoveRows().
 {
     q_firstRows[orientation == Qt::Vertical] = row;
 }
setGeometry()
void QGridLayoutItem::setGeometry (const QRectF & rect)
Definition at line 701 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::setGeometries().
 {
     q_layoutItem->setGeometry(rect);
 }
setRowSpan()
void QGridLayoutItem::setRowSpan (int rowSpan, Qt::Orientation orientation = Qt::Vertical)
Definition at line 537 of file qgridlayoutengine.cpp.
Referenced by insertOrRemoveRows().
 {
     q_rowSpans[orientation == Qt::Vertical] = rowSpan;
 }
setStretchFactor()
void QGridLayoutItem::setStretchFactor (int stretch, Qt::Orientation orientation)
Definition at line 559 of file qgridlayoutengine.cpp.
 {
     Q_ASSERT(stretch >= 0); // ### deal with too big stretches
     q_stretches[orientation == Qt::Vertical] = stretch;
 }
sizeHint()
QSizeF QGridLayoutItem::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const
Definition at line 595 of file qgridlayoutengine.cpp.
Referenced by box().
 {
     return q_layoutItem->effectiveSizeHint(which, constraint);
 }
sizePolicy()
QSizePolicy::Policy QGridLayoutItem::sizePolicy (Qt::Orientation orientation) const
Definition at line 565 of file qgridlayoutengine.cpp.
Referenced by box(), dump(), effectiveMaxSize(), QGridLayoutEngine::fillRowData(), and stretchFactor().
 {
     QSizePolicy sizePolicy(q_layoutItem->sizePolicy());
     return (orientation == Qt::Horizontal) ? sizePolicy.horizontalPolicy()
                                            : sizePolicy.verticalPolicy();
 }
stretchFactor()
int QGridLayoutItem::stretchFactor (Qt::Orientation orientation) const
Definition at line 542 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::fillRowData().
 {
     int stretch = q_stretches[orientation == Qt::Vertical];
     if (stretch >= 0)
         return stretch;
     QSizePolicy::Policy policy = sizePolicy(orientation);
     if (policy & QSizePolicy::ExpandFlag) {
         return 1;
     } else if (policy & QSizePolicy::GrowFlag) {
         return -1;  // because we max it up
     } else {
         return 0;
     }
 }
transpose()
void QGridLayoutItem::transpose ()
Definition at line 706 of file qgridlayoutengine.cpp.
 {
     qSwap(q_firstRows[Hor], q_firstRows[Ver]);
     qSwap(q_rowSpans[Hor], q_rowSpans[Ver]);
     qSwap(q_stretches[Hor], q_stretches[Ver]);
 }
Properties
q_alignment
Qt::Alignment QGridLayoutItem::q_alignment private
Definition at line 310 of file qgridlayoutengine_p.h.
Referenced by dump().
q_engine
QGridLayoutEngine* QGridLayoutItem::q_engine private
Definition at line 305 of file qgridlayoutengine_p.h.
Referenced by geometryWithin(), and QGridLayoutItem().
q_firstRows
int QGridLayoutItem::q_firstRows[NOrientations] private
Definition at line 307 of file qgridlayoutengine_p.h.
Referenced by firstColumn(), firstRow(), QGridLayoutItem(), setFirstRow(), and transpose().
q_layoutItem
QGraphicsLayoutItem* QGridLayoutItem::q_layoutItem private
Definition at line 306 of file qgridlayoutengine_p.h.
Referenced by controlTypes(), dump(), dynamicConstraintOrientation(), hasDynamicConstraint(), setGeometry(), sizeHint(), and sizePolicy().
q_rowSpans
int QGridLayoutItem::q_rowSpans[NOrientations] private
Definition at line 308 of file qgridlayoutengine_p.h.
Referenced by columnSpan(), QGridLayoutItem(), rowSpan(), setRowSpan(), and transpose().
q_stretches
int QGridLayoutItem::q_stretches[NOrientations] private
Definition at line 309 of file qgridlayoutengine_p.h.
Referenced by dump(), QGridLayoutItem(), setStretchFactor(), stretchFactor(), and transpose().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgridlayoutengine_p.h
/src/gui/graphicsview/qgridlayoutengine.cpp