Qt 4.8: QmlJSDebugger::AbstractLiveEditTool Class Reference
QmlJSDebugger::AbstractLiveEditTool Class Reference abstract
#include <abstractliveedittool.h>
Public Functions
AbstractLiveEditTool (QDeclarativeViewInspector *inspector)
virtual void clear ()=0
QList< QGraphicsItem * > items () const
virtual void itemsAboutToRemoved (const QList< QGraphicsItem *> &itemList)=0
void leaveEvent (QEvent *)
QString titleForItem (QGraphicsItem *item)
bool topItemIsMovable (const QList< QGraphicsItem *> &itemList)
bool topItemIsResizeHandle (const QList< QGraphicsItem *> &itemList)
bool topSelectedItemIsMovable (const QList< QGraphicsItem *> &itemList)
void updateSelectedItems ()
virtual ~AbstractLiveEditTool ()
Public Functions inherited from QmlJSDebugger::AbstractTool
AbstractTool (AbstractViewInspector *inspector)
virtual void hoverMoveEvent (QMouseEvent *event)=0
AbstractViewInspector * inspector () const
virtual void keyPressEvent (QKeyEvent *event)=0
virtual void keyReleaseEvent (QKeyEvent *keyEvent)=0
virtual void mouseDoubleClickEvent (QMouseEvent *event)=0
virtual void mouseMoveEvent (QMouseEvent *event)=0
virtual void mousePressEvent (QMouseEvent *event)=0
virtual void mouseReleaseEvent (QMouseEvent *event)=0
virtual void wheelEvent (QWheelEvent *event)=0
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QList< QGraphicsObject * > toGraphicsObjectList (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * topMovableDeclarativeItem (const QList< QGraphicsItem *> &itemList)
static QGraphicsItem * topMovableGraphicsItem (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * toQDeclarativeItem (QGraphicsItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
QDeclarativeViewInspector * inspector () const
QGraphicsScene * scene () const
virtual void selectedItemsChanged (const QList< QGraphicsItem *> &objectList)=0
QDeclarativeView * view () const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QList< QGraphicsItem * > m_itemList
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 63 of file abstractliveedittool.h.
Constructors and Destructors
AbstractLiveEditTool()
QmlJSDebugger::AbstractLiveEditTool::AbstractLiveEditTool (QDeclarativeViewInspector * inspector)
Definition at line 53 of file abstractliveedittool.cpp.
     : AbstractTool(editorView)
 {
 }
~AbstractLiveEditTool()
QmlJSDebugger::AbstractLiveEditTool::~AbstractLiveEditTool () virtual
Definition at line 59 of file abstractliveedittool.cpp.
 {
 }
Functions
clear()
virtual void QmlJSDebugger::AbstractLiveEditTool::clear () pure virtual
Implemented in QmlJSDebugger::LiveSelectionTool, QmlJSDebugger::ZoomTool, and QmlJSDebugger::ColorPickerTool.
Referenced by leaveEvent().
inspector()
QDeclarativeViewInspector * QmlJSDebugger::AbstractLiveEditTool::inspector () const protected
Definition at line 63 of file abstractliveedittool.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::alreadySelected(), QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QmlJSDebugger::LiveSelectionTool::hoverMoveEvent(), items(), leaveEvent(), QmlJSDebugger::LiveSelectionTool::mousePressEvent(), titleForItem(), topSelectedItemIsMovable(), view(), and QmlJSDebugger::LiveSelectionTool::wheelEvent().
 {
     return static_cast<QDeclarativeViewInspector*>(AbstractTool::inspector());
 }
items()
QList< QGraphicsItem * > QmlJSDebugger::AbstractLiveEditTool::items () const
Definition at line 83 of file abstractliveedittool.cpp.
Referenced by leaveEvent(), and updateSelectedItems().
 {
     return inspector()->selectedItems();
 }
itemsAboutToRemoved()
virtual void QmlJSDebugger::AbstractLiveEditTool::itemsAboutToRemoved (const QList< QGraphicsItem *> & itemList) pure virtual
Implemented in QmlJSDebugger::LiveSelectionTool, QmlJSDebugger::ZoomTool, and QmlJSDebugger::ColorPickerTool.
Referenced by leaveEvent().
leaveEvent()
void QmlJSDebugger::AbstractLiveEditTool::leaveEvent (QEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 71 of file abstractliveedittool.h.
 {}
scene()
QGraphicsScene * QmlJSDebugger::AbstractLiveEditTool::scene () const protected
Definition at line 73 of file abstractliveedittool.cpp.
Referenced by leaveEvent().
 {
     return view()->scene();
 }
selectedItemsChanged()
virtual void QmlJSDebugger::AbstractLiveEditTool::selectedItemsChanged (const QList< QGraphicsItem *> & objectList) protected pure virtual
Implemented in QmlJSDebugger::LiveSelectionTool, QmlJSDebugger::ColorPickerTool, and QmlJSDebugger::ZoomTool.
Referenced by leaveEvent(), and updateSelectedItems().
titleForItem()
QString QmlJSDebugger::AbstractLiveEditTool::titleForItem (QGraphicsItem * item)
Definition at line 160 of file abstractliveedittool.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::createContextMenu(), and leaveEvent().
 {
     QString className(QLatin1String("QGraphicsItem"));
     QString objectStringId;
     QString constructedName;
     QGraphicsObject *gfxObject = item->toGraphicsObject();
     if (gfxObject) {
         className = QLatin1String(gfxObject->metaObject()->className());
         className.remove(QRegExp(QLatin1String("_QMLTYPE_\\d+")));
         className.remove(QRegExp(QLatin1String("_QML_\\d+")));
         if (className.startsWith(QLatin1String("QDeclarative")))
             className = className.remove(QLatin1String("QDeclarative"));
         QDeclarativeItem *declarativeItem = qobject_cast<QDeclarativeItem*>(gfxObject);
         if (declarativeItem) {
             objectStringId = inspector()->idStringForObject(declarativeItem);
         }
         if (!objectStringId.isEmpty()) {
             constructedName = objectStringId + QLatin1String(" (") + className + QLatin1Char(')');
         } else {
             if (!gfxObject->objectName().isEmpty()) {
                 constructedName = gfxObject->objectName() + QLatin1String(" (") + className + QLatin1Char(')');
             } else {
                 constructedName = className;
             }
         }
     }
     return constructedName;
 }
toGraphicsObjectList()
QList< QGraphicsObject * > QmlJSDebugger::AbstractLiveEditTool::toGraphicsObjectList (const QList< QGraphicsItem *> & itemList) static
Definition at line 147 of file abstractliveedittool.cpp.
Referenced by leaveEvent(), and QmlJSDebugger::LiveSelectionTool::selectedItemsChanged().
 {
     QList<QGraphicsObject*> gfxObjects;
     foreach (QGraphicsItem *item, itemList) {
         QGraphicsObject *obj = item->toGraphicsObject();
         if (obj)
             gfxObjects << obj;
     }
     return gfxObjects;
 }
topItemIsMovable()
bool QmlJSDebugger::AbstractLiveEditTool::topItemIsMovable (const QList< QGraphicsItem *> & itemList)
Definition at line 88 of file abstractliveedittool.cpp.
Referenced by leaveEvent().
 {
     QGraphicsItem *firstSelectableItem = topMovableGraphicsItem(itemList);
     if (firstSelectableItem == 0)
         return false;
     if (toQDeclarativeItem(firstSelectableItem) != 0)
         return true;
     return false;
 }
topItemIsResizeHandle()
bool QmlJSDebugger::AbstractLiveEditTool::topItemIsResizeHandle (const QList< QGraphicsItem *> & itemList)
Definition at line 116 of file abstractliveedittool.cpp.
Referenced by leaveEvent().
 {
     return false;
 }
topMovableDeclarativeItem()
QDeclarativeItem * QmlJSDebugger::AbstractLiveEditTool::topMovableDeclarativeItem (const QList< QGraphicsItem *> & itemList) static
Definition at line 135 of file abstractliveedittool.cpp.
Referenced by leaveEvent().
 {
     foreach (QGraphicsItem *item, itemList) {
         QDeclarativeItem *declarativeItem = toQDeclarativeItem(item);
         if (declarativeItem /*&& (declarativeItem->qmlItemNode().hasShowContent())*/)
             return declarativeItem;
     }
     return 0;
 }
topMovableGraphicsItem()
QGraphicsItem * QmlJSDebugger::AbstractLiveEditTool::topMovableGraphicsItem (const QList< QGraphicsItem *> & itemList) static
Definition at line 126 of file abstractliveedittool.cpp.
Referenced by leaveEvent(), and topItemIsMovable().
 {
     foreach (QGraphicsItem *item, itemList) {
         if (item->flags().testFlag(QGraphicsItem::ItemIsMovable))
             return item;
     }
     return 0;
 }
topSelectedItemIsMovable()
bool QmlJSDebugger::AbstractLiveEditTool::topSelectedItemIsMovable (const QList< QGraphicsItem *> & itemList)
Definition at line 100 of file abstractliveedittool.cpp.
Referenced by leaveEvent().
 {
     QList<QGraphicsItem*> selectedItems = inspector()->selectedItems();
     foreach (QGraphicsItem *item, itemList) {
         QDeclarativeItem *declarativeItem = toQDeclarativeItem(item);
         if (declarativeItem
                 && selectedItems.contains(declarativeItem)
                 /*&& (declarativeItem->qmlItemNode().hasShowContent() || selectNonContentItems)*/)
             return true;
     }
     return false;
 }
toQDeclarativeItem()
QDeclarativeItem * QmlJSDebugger::AbstractLiveEditTool::toQDeclarativeItem (QGraphicsItem * item) static
Definition at line 121 of file abstractliveedittool.cpp.
Referenced by leaveEvent(), topItemIsMovable(), topMovableDeclarativeItem(), and topSelectedItemIsMovable().
 {
     return qobject_cast<QDeclarativeItem*>(item->toGraphicsObject());
 }
updateSelectedItems()
void QmlJSDebugger::AbstractLiveEditTool::updateSelectedItems ()
Definition at line 78 of file abstractliveedittool.cpp.
Referenced by leaveEvent().
 {
     selectedItemsChanged(items());
 }
view()
QDeclarativeView * QmlJSDebugger::AbstractLiveEditTool::view () const protected
Definition at line 68 of file abstractliveedittool.cpp.
Referenced by QmlJSDebugger::ColorPickerTool::clear(), QmlJSDebugger::ZoomTool::clear(), QmlJSDebugger::LiveSelectionTool::clear(), QmlJSDebugger::ZoomTool::keyReleaseEvent(), leaveEvent(), QmlJSDebugger::ZoomTool::mouseMoveEvent(), QmlJSDebugger::ZoomTool::mousePressEvent(), QmlJSDebugger::ZoomTool::mouseReleaseEvent(), QmlJSDebugger::ColorPickerTool::pickColor(), QmlJSDebugger::ZoomTool::scaleView(), scene(), QmlJSDebugger::ZoomTool::wheelEvent(), QmlJSDebugger::ZoomTool::zoomIn(), QmlJSDebugger::ZoomTool::zoomOut(), and QmlJSDebugger::ZoomTool::zoomTo100().
 {
     return inspector()->declarativeView();
 }
Properties
m_itemList
QList<QGraphicsItem*> QmlJSDebugger::AbstractLiveEditTool::m_itemList private
Definition at line 99 of file abstractliveedittool.h.
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/abstractliveedittool.h
/src/plugins/qmltooling/qmldbg_inspector/editor/abstractliveedittool.cpp