Qt 4.8: QXmlNamespaceSupport Class Reference
QXmlNamespaceSupport Class Reference
The QXmlNamespaceSupport class is a helper class for XML readers which want to include namespace support.
#include <qxml.h>
Public Functions
void popContext ()
Reverts to the previous namespace context.
QString prefix (const QString &) const
Returns one of the prefixes mapped to the namespace URI uri.
QStringList prefixes () const
Returns a list of all the prefixes currently declared.
QStringList prefixes (const QString &) const
Returns a list of all prefixes currently declared for the namespace URI uri.
void processName (const QString &, bool, QString &, QString &) const
Processes a raw XML 1.0 name in the current context by removing the prefix and looking it up among the prefixes currently declared.
void pushContext ()
Starts a new namespace context.
QXmlNamespaceSupport ()
Constructs a QXmlNamespaceSupport.
void reset ()
Resets this namespace support object ready for reuse.
void setPrefix (const QString &, const QString &)
This function declares a prefix pre in the current namespace context to be the namespace URI uri.
void splitName (const QString &, QString &, QString &) const
Splits the name qname at the ':' and returns the prefix in prefix and the local name in localname.
QString uri (const QString &) const
Looks up the prefix prefix in the current context and returns the currently-mapped namespace URI.
~QXmlNamespaceSupport ()
Destroys a QXmlNamespaceSupport.
Properties
QXmlNamespaceSupportPrivate * d
Friends
class QXmlSimpleReaderPrivate
Detailed Description
The QXmlNamespaceSupport class is a helper class for XML readers which want to include namespace support.
Since
4.4
Note
This class or function is reentrant.
Attention
Module: QtXml
You can set the prefix for the current namespace with setPrefix(), and get the list of current prefixes (or those for a given URI) with prefixes(). The namespace URI is available from uri(). Use pushContext() to start a new namespace context, and popContext() to return to the previous namespace context. Use splitName() or processName() to split a name into its prefix and local name.
See also
{Namespace Support via Features}
Definition at line 88 of file qxml.h.
Constructors and Destructors
QXmlNamespaceSupport()
QXmlNamespaceSupport::QXmlNamespaceSupport ()
Constructs a QXmlNamespaceSupport.
Definition at line 765 of file qxml.cpp.
 {
     d = new QXmlNamespaceSupportPrivate;
 }
~QXmlNamespaceSupport()
QXmlNamespaceSupport::~QXmlNamespaceSupport ()
Destroys a QXmlNamespaceSupport.
Definition at line 773 of file qxml.cpp.
 {
     delete d;
 }
Functions
popContext()
void QXmlNamespaceSupport::popContext ()
Reverts to the previous namespace context.
Normally, you should pop the context at the end of each XML element. After popping the context, all namespace prefix mappings that were previously in force are restored.
See also
pushContext()
Definition at line 968 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processElementEmptyTag(), and QXmlSimpleReaderPrivate::processElementETagBegin2().
 {
     d->ns.clear();
     if(!d->nsStack.isEmpty())
         d->ns = d->nsStack.pop();
 }
prefix()
QString QXmlNamespaceSupport::prefix (const QString & uri) const
Returns one of the prefixes mapped to the namespace URI uri.
If more than one prefix is currently mapped to the same URI, this function makes an arbitrary selection; if you want all of the prefixes, use prefixes() instead.
Note: to check for a default prefix, use the uri() function with an argument of "".
Definition at line 809 of file qxml.cpp.
 {
     NamespaceMap::const_iterator itc, it = d->ns.constBegin();
     while ((itc=it) != d->ns.constEnd()) {
         ++it;
         if (*itc == uri && !itc.key().isEmpty())
             return itc.key();
     }
     return QLatin1String("");
 }
prefixes() [1/2]
QStringList QXmlNamespaceSupport::prefixes () const
Returns a list of all the prefixes currently declared.
If there is a default prefix, this function does not return it in the list; check for the default prefix using uri() with an argument of "".
Definition at line 901 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processElementEmptyTag().
 {
     QStringList list;
     NamespaceMap::const_iterator itc, it = d->ns.constBegin();
     while ((itc=it) != d->ns.constEnd()) {
         ++it;
         if (!itc.key().isEmpty())
             list.append(itc.key());
     }
     return list;
 }
prefixes() [2/2]
QStringList QXmlNamespaceSupport::prefixes (const QString & uri) const
Returns a list of all prefixes currently declared for the namespace URI uri.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The "xml:" prefix is included. If you only want one prefix that is mapped to the namespace URI, and you don't care which one you get, use the prefix() function instead.
Note: The empty (default) prefix is never included in this list; to check for the presence of a default namespace, call uri() with "" as the argument.
Definition at line 931 of file qxml.cpp.
 {
     QStringList list;
     NamespaceMap::const_iterator itc, it = d->ns.constBegin();
     while ((itc=it) != d->ns.constEnd()) {
         ++it;
         if (*itc == uri && !itc.key().isEmpty())
             list.append(itc.key());
     }
     return list;
 }
processName()
void QXmlNamespaceSupport::processName (const QString & qname, bool isAttribute, QString & nsuri, QString & localname) const
Processes a raw XML 1.0 name in the current context by removing the prefix and looking it up among the prefixes currently declared.
qname is the raw XML 1.0 name to be processed. isAttribute is true if the name is an attribute name.
This function stores the namespace URI in nsuri (which will be set to an empty string if the raw name has an undeclared prefix), and stores the local name (without prefix) in localname (which will be set to an empty string if no namespace is in use).
Note that attribute names are processed differently than element names: an unprefixed element name gets the default namespace (if any), while an unprefixed attribute name does not.
Definition at line 864 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseElement(), QXmlSimpleReaderPrivate::processElementAttribute(), QXmlSimpleReaderPrivate::processElementEmptyTag(), and QXmlSimpleReaderPrivate::processElementETagBegin2().
 {
     int len = qname.size();
     const QChar *data = qname.constData();
     for (int pos = 0; pos < len; ++pos) {
         if (data[pos] == QLatin1Char(':')) {
             nsuri = uri(qname.left(pos));
             localname = qname.mid(pos + 1);
             return;
         }
     }
     // there was no ':'
     nsuri.clear();
     // attributes don't take default namespace
     if (!isAttribute && !d->ns.isEmpty()) {
     /*
         We want to access d->ns.value(""), but as an optimization
         we use the fact that "" compares less than any other
         string, so it's either first in the map or not there.
     */
         NamespaceMap::const_iterator first = d->ns.constBegin();
         if (first.key().isEmpty())
             nsuri = first.value(); // get default namespace
     }
     localname = qname;
 }
pushContext()
void QXmlNamespaceSupport::pushContext ()
Starts a new namespace context.
Normally, you should push a new context at the beginning of each XML element: the new context automatically inherits the declarations of its parent context, and it also keeps track of which declarations were made within this context.
See also
popContext()
Definition at line 954 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::parseElement().
 {
     d->nsStack.push(d->ns);
 }
reset()
void QXmlNamespaceSupport::reset ()
Resets this namespace support object ready for reuse.
Definition at line 978 of file qxml.cpp.
 {
     QXmlNamespaceSupportPrivate *newD = new QXmlNamespaceSupportPrivate;
     delete d;
     d = newD;
 }
setPrefix()
void QXmlNamespaceSupport::setPrefix (const QString & pre, const QString & uri)
This function declares a prefix pre in the current namespace context to be the namespace URI uri.
The prefix remains in force until this context is popped, unless it is shadowed in a descendant context.
Note that there is an asymmetry in this library. prefix() does not return the default "" prefix, even if you have declared one; to check for a default prefix, you must look it up explicitly using uri(). This asymmetry exists to make it easier to look up prefixes for attribute names, where the default prefix is not allowed.
Definition at line 790 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processElementAttribute().
 {
     if(pre.isNull()) {
         d->ns.insert(QLatin1String(""), uri);
     } else {
         d->ns.insert(pre, uri);
     }
 }
splitName()
void QXmlNamespaceSupport::splitName (const QString & qname, QString & prefix, QString & localname) const
Splits the name qname at the ':' and returns the prefix in prefix and the local name in localname.
See also
processName()
Definition at line 836 of file qxml.cpp.
Referenced by QXmlSimpleReaderPrivate::processElementAttribute().
 {
     int pos = qname.indexOf(QLatin1Char(':'));
     if (pos == -1)
         pos = qname.size();
     prefix = qname.left(pos);
     localname = qname.mid(pos+1);
 }
uri()
QString QXmlNamespaceSupport::uri (const QString & prefix) const
Looks up the prefix prefix in the current context and returns the currently-mapped namespace URI.
Use the empty string ("") for the default namespace.
Definition at line 825 of file qxml.cpp.
 {
     return d->ns[prefix];
 }
Friends and Related Functions
QXmlSimpleReaderPrivate
friend class QXmlSimpleReaderPrivate friend
Definition at line 110 of file qxml.h.
Properties
d
QXmlNamespaceSupportPrivate* QXmlNamespaceSupport::d private
Definition at line 108 of file qxml.h.
Referenced by QXmlSimpleReaderPrivate::processElementETagBegin2().
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp