Qt 4.8: QGbkCodec Class Reference
QGbkCodec Class Reference
The QGbkCodec class provides conversion to and from the Chinese GBK encoding.
#include <qgb18030codec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
Reimplemented Function
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
QGbkCodec ()
Constructs a QGbkCodec object.
Public Functions inherited from QGb18030Codec
QGb18030Codec ()
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QGb18030Codec
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
The QGbkCodec class provides conversion to and from the Chinese GBK encoding.
Note
This class or function is reentrant.
Warning
This function is not part of the public interface.
GBK, formally the Chinese Internal Code Specification, is a commonly used extension of GB 2312-80. Microsoft Windows uses it under the name code page 936.
The GBK encoding has been superseded by the GB18030 encoding and GB18030 is backward compatible to GBK. For this reason the QGbkCodec class is implemented in terms of the GB18030 codec and uses its 1-byte and 2-byte portion for conversion from and to Unicode.
The QGbkCodec is kept mainly for compatibility reasons with older software.
Definition at line 70 of file qgb18030codec.h.
Constructors and Destructors
QGbkCodec()
QGbkCodec::QGbkCodec ()
Constructs a QGbkCodec object.
Definition at line 297 of file qgb18030codec.cpp.
     : QGb18030Codec()
 {
 }
Functions
_aliases()
QList< QByteArray > QGbkCodec::_aliases () static
Definition at line 312 of file qgb18030codec.cpp.
Referenced by CNTextCodecs::aliases(), and CNTextCodecs::createForName().
 {
     QList<QByteArray> list;
     list << "CP936"
          << "MS936"
          << "windows-936";
     return list;
 }
_mibEnum()
int QGbkCodec::_mibEnum () static
Definition at line 302 of file qgb18030codec.cpp.
Referenced by CNTextCodecs::createForMib(), and CNTextCodecs::mibEnums().
 {
     return 113;
 }
_name()
QByteArray QGbkCodec::_name () static
Definition at line 307 of file qgb18030codec.cpp.
Referenced by CNTextCodecs::createForName(), and CNTextCodecs::names().
 {
     return "GBK";
 }
aliases()
QList<QByteArray> QGbkCodec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QGb18030Codec.
Definition at line 79 of file qgb18030codec.h.
 { return _aliases(); }
convertFromUnicode()
QByteArray QGbkCodec::convertFromUnicode (const QChar * uc, int len, ConverterState * state) const virtual
Reimplemented Function
Reimplemented from QGb18030Codec.
Definition at line 396 of file qgb18030codec.cpp.
 {
     char replacement = '?';
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = 0;
     }
     int invalid = 0;
     int rlen = 2*len + 1;
     QByteArray rstr;
     rstr.resize(rlen);
     uchar* cursor = (uchar*)rstr.data();
     //qDebug("QGbkCodec::fromUnicode(const QString& uc, int& lenInOut = %d)", lenInOut);
     for (int i = 0; i < len; i++) {
         QChar ch = uc[i];
         uchar buf[2];
         if (ch.row() == 0x00 && ch.cell() < 0x80) {
             // ASCII
             *cursor++ = ch.cell();
         } else if (qt_UnicodeToGbk(ch.unicode(), buf) == 2) {
             *cursor++ = buf[0];
             *cursor++ = buf[1];
         } else {
             // Error
             *cursor += replacement;
             ++invalid;
         }
     }
     rstr.resize(cursor - (uchar*)rstr.constData());
     if (state) {
         state->invalidChars += invalid;
     }
     return rstr;
 }
convertToUnicode()
QString QGbkCodec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Reimplemented from QGb18030Codec.
Definition at line 321 of file qgb18030codec.cpp.
 {
     uchar buf[2];
     int nbuf = 0;
     ushort replacement = QChar::ReplacementCharacter;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = QChar::Null;
         nbuf = state->remainingChars;
         buf[0] = state->state_data[0];
         buf[1] = state->state_data[1];
     }
     int invalid = 0;
     QString result;
     result.resize(len);
     int unicodeLen = 0;
     ushort *const resultData = reinterpret_cast<ushort*>(result.data());
     //qDebug("QGbkDecoder::toUnicode(const char* chars = \"%s\", int len = %d)", chars, len);
     for (int i=0; i<len; i++) {
         uchar ch = chars[i];
         switch (nbuf) {
         case 0:
             if (IsLatin(ch)) {
                 // ASCII
                 resultData[unicodeLen] = ch;
                 ++unicodeLen;
             } else if (Is1stByte(ch)) {
                 // GBK 1st byte?
                 buf[0] = ch;
                 nbuf = 1;
             } else {
                 // Invalid
                 resultData[unicodeLen] = replacement;
                 ++unicodeLen;
                 ++invalid;
             }
             break;
         case 1:
             // GBK 2nd byte
             if (Is2ndByteIn2Bytes(ch)) {
                 buf[1] = ch;
                 int clen = 2;
                 uint u = qt_Gb18030ToUnicode(buf, clen);
                 if (clen == 2) {
                     resultData[unicodeLen] = qValidChar(static_cast<ushort>(u));
                     ++unicodeLen;
                 } else {
                     resultData[unicodeLen] = replacement;
                     ++unicodeLen;
                     ++invalid;
                 }
                 nbuf = 0;
             } else {
                 // Error
                 resultData[unicodeLen] = replacement;
                 ++unicodeLen;
                 ++invalid;
                 nbuf = 0;
             }
             break;
         }
     }
     result.resize(unicodeLen);
     if (state) {
         state->remainingChars = nbuf;
         state->state_data[0] = buf[0];
         state->state_data[1] = buf[1];
         state->invalidChars += invalid;
     }
     return result;
 }
mibEnum()
int QGbkCodec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Reimplemented from QGb18030Codec.
Definition at line 80 of file qgb18030codec.h.
 { return _mibEnum(); }
name()
QByteArray QGbkCodec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Reimplemented from QGb18030Codec.
Definition at line 78 of file qgb18030codec.h.
 { return _name(); }
The documentation for this class was generated from the following files:
/src/plugins/codecs/cn/qgb18030codec.h
/src/plugins/codecs/cn/qgb18030codec.cpp