Qt 4.8: QScript::QScriptActivationObject Class Reference
QScript::QScriptActivationObject Class Reference
Represent a scope for native function call.
#include <qscriptactivationobject_p.h>
Classes
struct QScriptActivationObjectData
Public Functions
virtual const JSC::ClassInfo * classInfo () const
QScriptActivationObjectData * d_ptr () const
virtual void defineGetter (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::JSObject *getterFunction)
virtual void defineSetter (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::JSObject *setterFunction)
JSC::JSObject * delegate () const
virtual bool deleteProperty (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual bool getOwnPropertyDescriptor (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual bool isDynamicScope () const
virtual JSC::JSValue lookupGetter (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual JSC::JSValue lookupSetter (JSC::ExecState *, const JSC::Identifier &propertyName)
virtual void put (JSC::ExecState *, const JSC::Identifier &propertyName, JSC::JSValue value, JSC::PutPropertySlot &)
virtual void put (JSC::ExecState *, unsigned propertyName, JSC::JSValue value)
virtual void putWithAttributes (JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue value, unsigned attributes)
QScriptActivationObject (JSC::ExecState *callFrame, JSC::JSObject *delegate=0)
void setDelegate (JSC::JSObject *delegate)
virtual ~QScriptActivationObject ()
Static Public Variables
static const JSC::ClassInfo info = { "QScriptActivationObject", 0, 0, 0 }
Detailed Description
Represent a scope for native function call.
Warning
This function is not part of the public interface.
Definition at line 47 of file qscriptactivationobject_p.h.
Constructors and Destructors
QScriptActivationObject()
QScript::QScriptActivationObject::QScriptActivationObject (JSC::ExecState * callFrame, JSC::JSObject * delegate = 0)
Definition at line 51 of file qscriptactivationobject.cpp.
     : JSC::JSVariableObject(callFrame->globalData().activationStructure,
                             new QScriptActivationObjectData(callFrame->registers(), delegate))
 {
 }
~QScriptActivationObject()
QScript::QScriptActivationObject::~QScriptActivationObject () virtual
Definition at line 57 of file qscriptactivationobject.cpp.
 {
     delete d_ptr();
 }
Functions
classInfo()
virtual const JSC::ClassInfo* QScript::QScriptActivationObject::classInfo () const inline virtual
Definition at line 68 of file qscriptactivationobject_p.h.
 { return &info; }
d_ptr()
QScriptActivationObjectData* QScript::QScriptActivationObject::d_ptr () const inline
Definition at line 85 of file qscriptactivationobject_p.h.
Referenced by defineGetter(), defineSetter(), delegate(), deleteProperty(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), lookupGetter(), lookupSetter(), put(), putWithAttributes(), setDelegate(), and ~QScriptActivationObject().
 { return static_cast<QScriptActivationObjectData *>(d); }
defineGetter()
void QScript::QScriptActivationObject::defineGetter (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSObject * getterFunction) virtual
Definition at line 124 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         d_ptr()->delegate->defineGetter(exec, propertyName, getterFunction);
     else
         JSC::JSVariableObject::defineGetter(exec, propertyName, getterFunction);
 }
defineSetter()
void QScript::QScriptActivationObject::defineSetter (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSObject * setterFunction) virtual
Definition at line 132 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         d_ptr()->delegate->defineSetter(exec, propertyName, setterFunction);
     else
         JSC::JSVariableObject::defineSetter(exec, propertyName, setterFunction);
 }
delegate()
JSC::JSObject* QScript::QScriptActivationObject::delegate () const inline
Definition at line 80 of file qscriptactivationobject_p.h.
Referenced by defineGetter(), defineSetter(), deleteProperty(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), lookupGetter(), lookupSetter(), put(), putWithAttributes(), and QScriptEnginePrivate::toQObject().
     { return d_ptr()->delegate; }
deleteProperty()
bool QScript::QScriptActivationObject::deleteProperty (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 117 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         return d_ptr()->delegate->deleteProperty(exec, propertyName);
     return JSC::JSVariableObject::deleteProperty(exec, propertyName);
 }
getOwnPropertyDescriptor()
bool QScript::QScriptActivationObject::getOwnPropertyDescriptor (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Definition at line 69 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         return d_ptr()->delegate->getOwnPropertyDescriptor(exec, propertyName, descriptor);
     return JSC::JSVariableObject::getOwnPropertyDescriptor(exec, propertyName, descriptor);
 }
getOwnPropertyNames()
void QScript::QScriptActivationObject::getOwnPropertyNames (JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Definition at line 76 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0) {
         d_ptr()->delegate->getOwnPropertyNames(exec, propertyNames, mode);
         return;
     }
     return JSC::JSVariableObject::getOwnPropertyNames(exec, propertyNames, mode);
 }
getOwnPropertySlot()
bool QScript::QScriptActivationObject::getOwnPropertySlot (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Definition at line 62 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         return d_ptr()->delegate->getOwnPropertySlot(exec, propertyName, slot);
     return JSC::JSVariableObject::getOwnPropertySlot(exec, propertyName, slot);
 }
isDynamicScope()
virtual bool QScript::QScriptActivationObject::isDynamicScope () const inline virtual
Definition at line 51 of file qscriptactivationobject_p.h.
 { return true; }
lookupGetter()
JSC::JSValue QScript::QScriptActivationObject::lookupGetter (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 140 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         return d_ptr()->delegate->lookupGetter(exec, propertyName);
     return JSC::JSVariableObject::lookupGetter(exec, propertyName);
 }
lookupSetter()
JSC::JSValue QScript::QScriptActivationObject::lookupSetter (JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Definition at line 147 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0)
         return d_ptr()->delegate->lookupSetter(exec, propertyName);
     return JSC::JSVariableObject::lookupSetter(exec, propertyName);
 }
put() [1/2]
void QScript::QScriptActivationObject::put (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Definition at line 99 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0) {
         d_ptr()->delegate->put(exec, propertyName, value, slot);
         return;
     }
     JSC::JSVariableObject::put(exec, propertyName, value, slot);
 }
put() [2/2]
void QScript::QScriptActivationObject::put (JSC::ExecState * exec, unsigned propertyName, JSC::JSValue value) virtual
Definition at line 108 of file qscriptactivationobject.cpp.
 {
     if (d_ptr()->delegate != 0) {
         d_ptr()->delegate->put(exec, propertyName, value);
         return;
     }
     JSC::JSVariableObject::put(exec, propertyName, value);
 }
putWithAttributes()
void QScript::QScriptActivationObject::putWithAttributes (JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, unsigned attributes) virtual
Definition at line 85 of file qscriptactivationobject.cpp.
Referenced by isDynamicScope().
 {
     if (d_ptr()->delegate != 0) {
         d_ptr()->delegate->putWithAttributes(exec, propertyName, value, attributes);
         return;
     }
     if (symbolTablePutWithAttributes(propertyName, value, attributes))
         return;
     JSC::PutPropertySlot slot;
     JSObject::putWithAttributes(exec, propertyName, value, attributes, true, slot);
 }
setDelegate()
void QScript::QScriptActivationObject::setDelegate (JSC::JSObject * delegate) inline
Definition at line 82 of file qscriptactivationobject_p.h.
     { d_ptr()->delegate = delegate; }
Properties
info
const JSC::ClassInfo QScript::QScriptActivationObject::info = { "QScriptActivationObject", 0, 0, 0 } static
Definition at line 69 of file qscriptactivationobject_p.h.
Referenced by QScriptContext::activationObject(), classInfo(), QScriptContext::scopeChain(), QScriptDeclarativeClass::scopeChainValue(), QScriptContext::setActivationObject(), and QScriptEnginePrivate::toQObject().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptactivationobject_p.h
/src/script/bridge/qscriptactivationobject.cpp