Qt 4.8: QPSQLResult Class Reference
QPSQLResult Class Reference
#include <qsql_psql.h>
Public Functions
QVariant handle () const
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
QPSQLResult (const QPSQLDriver *db, const QPSQLDriverPrivate *p)
void virtual_hook (int id, void *data)
~QPSQLResult ()
Public Functions inherited from QSqlResult
virtual ~QSqlResult ()
Destroys the object and frees any allocated resources.
Protected Functions
void cleanup ()
QVariant data (int i)
Returns the data for field index in the current row as a QVariant.
bool exec ()
Executes the query, returning true if successful; otherwise returns false.
bool fetch (int i)
Positions the result to an arbitrary (zero-based) row index.
bool fetchFirst ()
Positions the result to the first record (row 0) in the result.
bool fetchLast ()
Positions the result to the last record (last row) in the result.
bool isNull (int field)
Returns true if the field at position index in the current row is null; otherwise returns false.
QVariant lastInsertId () const
Returns the object ID of the most recent inserted row if the database supports it.
int numRowsAffected ()
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
bool prepare (const QString &query)
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
QSqlRecord record () const
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
bool reset (const QString &query)
Sets the result to use the SQL statement query for subsequent data retrieval.
int size ()
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
Protected Functions inherited from QSqlResult
void addBindValue (const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the next available position in the current record (row).
int at () const
Returns the current (zero-based) row position of the result.
BindingSyntax bindingSyntax () const
Returns the binding syntax used by prepared queries.
virtual void bindValue (int pos, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to position index in the current record (row).
virtual void bindValue (const QString &placeholder, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the placeholder name in the current record (row).
QSql::ParamType bindValueType (const QString &placeholder) const
Returns the parameter type for the value bound with the given placeholder name.
QSql::ParamType bindValueType (int pos) const
Returns the parameter type for the value bound at position index.
QVariant boundValue (const QString &placeholder) const
Returns the value bound by the given placeholder name in the current record (row).
QVariant boundValue (int pos) const
Returns the value bound at position index in the current record (row).
int boundValueCount () const
Returns the number of bound values in the result.
QString boundValueName (int pos) const
Returns the name of the bound value at position index in the current record (row).
QVector< QVariant > & boundValues () const
Returns a vector of the result's bound values for the current record (row).
void clear ()
Clears the entire result set and releases any associated resources.
void detachFromResultSet ()
const QSqlDriver * driver () const
Returns the driver associated with the result.
bool execBatch (bool arrayBind=false)
Executes a prepared query in batch mode if the driver supports it, otherwise emulates a batch execution using bindValue() and exec().
QString executedQuery () const
Returns the query that was actually executed.
virtual bool fetchNext ()
Positions the result to the next available record (row) in the result.
virtual bool fetchPrevious ()
Positions the result to the previous record (row) in the result.
bool hasOutValues () const
Returns true if at least one of the query's bound values is a QSql::Out or a QSql::InOut; otherwise returns false.
bool isActive () const
Returns true if the result has records to be retrieved; otherwise returns false.
bool isForwardOnly () const
Returns true if you can only scroll forward through the result set; otherwise returns false.
bool isSelect () const
Returns true if the current result is from a SELECT statement; otherwise returns false.
bool isValid () const
Returns true if the result is positioned on a valid record (that is, the result is not positioned before the first or after the last record); otherwise returns false.
QSqlError lastError () const
Returns the last error associated with the result.
QString lastQuery () const
Returns the current SQL query text, or an empty string if there isn't one.
bool nextResult ()
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
QSqlResult (const QSqlDriver *db)
Creates a QSqlResult using database driver db.
virtual bool savePrepare (const QString &sqlquery)
Prepares the given query, using the underlying database functionality where possible.
virtual void setActive (bool a)
This function is provided for derived classes to set the internal active state to active.
virtual void setAt (int at)
This function is provided for derived classes to set the internal (zero-based) row position to index.
virtual void setForwardOnly (bool forward)
Sets forward only mode to forward.
virtual void setLastError (const QSqlError &e)
This function is provided for derived classes to set the last error to error.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy policy)
virtual void setQuery (const QString &query)
Sets the current query for the result to query.
virtual void setSelect (bool s)
This function is provided for derived classes to indicate whether or not the current statement is a SQL SELECT statement.
Properties
QPSQLResultPrivate * d
Friends
class QPSQLResultPrivate
Additional Inherited Members
Protected Types inherited from QSqlResult
enum BindingSyntax { PositionalBinding, NamedBinding }
This enum type specifies the different syntaxes for specifying placeholders in prepared queries.
enum VirtualHookOperation { BatchOperation, DetachFromResultSet, SetNumericalPrecision, NextResult }
Detailed Description
Definition at line 66 of file qsql_psql.h.
Constructors and Destructors
QPSQLResult()
QPSQLResult::QPSQLResult (const QPSQLDriver * db, const QPSQLDriverPrivate * p)
Definition at line 296 of file qsql_psql.cpp.
     : QSqlResult(db)
 {
     d = new QPSQLResultPrivate(this);
     d->driver = p;
     d->preparedQueriesEnabled = db->hasFeature(QSqlDriver::PreparedQueries);
 }
~QPSQLResult()
QPSQLResult::~QPSQLResult ()
Definition at line 304 of file qsql_psql.cpp.
 {
     cleanup();
     if (d->preparedQueriesEnabled && !d->preparedStmtId.isNull())
         qDeallocatePreparedStmt(d);
     delete d;
 }
Functions
cleanup()
void QPSQLResult::cleanup () protected
Definition at line 319 of file qsql_psql.cpp.
Referenced by exec(), prepare(), reset(), and ~QPSQLResult().
 {
     if (d->result)
         PQclear(d->result);
     d->result = 0;
     setAt(QSql::BeforeFirstRow);
     d->currentSize = -1;
     setActive(false);
 }
data()
QVariant QPSQLResult::data (int index) protected virtual
Returns the data for field index in the current row as a QVariant.
This function is only called if the result is in an active state and is positioned on a valid record and index is non-negative. Derived classes must reimplement this function and return the value of field index, or QVariant() if it cannot be determined.
Implements QSqlResult.
Definition at line 353 of file qsql_psql.cpp.
 {
     if (i >= PQnfields(d->result)) {
         qWarning("QPSQLResult::data: column %d out of range", i);
         return QVariant();
     }
     int ptype = PQftype(d->result, i);
     QVariant::Type type = qDecodePSQLType(ptype);
     const char *val = PQgetvalue(d->result, at(), i);
     if (PQgetisnull(d->result, at(), i))
         return QVariant(type);
     switch (type) {
     case QVariant::Bool:
         return QVariant((bool)(val[0] == 't'));
     case QVariant::String:
         return d->driver->isUtf8 ? QString::fromUtf8(val) : QString::fromAscii(val);
     case QVariant::LongLong:
         if (val[0] == '-')
             return QString::fromLatin1(val).toLongLong();
         else
             return QString::fromLatin1(val).toULongLong();
     case QVariant::Int:
         return atoi(val);
     case QVariant::Double:
         if (ptype == QNUMERICOID) {
             if (numericalPrecisionPolicy() != QSql::HighPrecision) {
                 QVariant retval;
                 bool convert;
                 double dbl=QString::fromAscii(val).toDouble(&convert);
                 if (numericalPrecisionPolicy() == QSql::LowPrecisionInt64)
                     retval = (qlonglong)dbl;
                 else if (numericalPrecisionPolicy() == QSql::LowPrecisionInt32)
                     retval = (int)dbl;
                 else if (numericalPrecisionPolicy() == QSql::LowPrecisionDouble)
                     retval = dbl;
                 if (!convert)
                     return QVariant();
                 return retval;
             }
             return QString::fromAscii(val);
         }
         return QString::fromAscii(val).toDouble();
     case QVariant::Date:
         if (val[0] == '\0') {
             return QVariant(QDate());
         } else {
 #ifndef QT_NO_DATESTRING
             return QVariant(QDate::fromString(QString::fromLatin1(val), Qt::ISODate));
 #else
             return QVariant(QString::fromLatin1(val));
 #endif
         }
     case QVariant::Time: {
         const QString str = QString::fromLatin1(val);
 #ifndef QT_NO_DATESTRING
         if (str.isEmpty())
             return QVariant(QTime());
         if (str.at(str.length() - 3) == QLatin1Char('+') || str.at(str.length() - 3) == QLatin1Char('-'))
             // strip the timezone
             // TODO: fix this when timestamp support comes into QDateTime
             return QVariant(QTime::fromString(str.left(str.length() - 3), Qt::ISODate));
         return QVariant(QTime::fromString(str, Qt::ISODate));
 #else
         return QVariant(str);
 #endif
     }
     case QVariant::DateTime: {
         QString dtval = QString::fromLatin1(val);
 #ifndef QT_NO_DATESTRING
         if (dtval.length() < 10)
             return QVariant(QDateTime());
         // remove the timezone
         // TODO: fix this when timestamp support comes into QDateTime
         if (dtval.at(dtval.length() - 3) == QLatin1Char('+') || dtval.at(dtval.length() - 3) == QLatin1Char('-'))
             dtval.chop(3);
         // milliseconds are sometimes returned with 2 digits only
         if (dtval.at(dtval.length() - 3).isPunct())
             dtval += QLatin1Char('0');
         if (dtval.isEmpty())
             return QVariant(QDateTime());
         else
             return QVariant(QDateTime::fromString(dtval, Qt::ISODate));
 #else
         return QVariant(dtval);
 #endif
     }
     case QVariant::ByteArray: {
         size_t len;
         unsigned char *data = PQunescapeBytea((unsigned char*)val, &len);
         QByteArray ba((const char*)data, len);
         qPQfreemem(data);
         return QVariant(ba);
     }
     default:
     case QVariant::Invalid:
         qWarning("QPSQLResult::data: unknown data type");
     }
     return QVariant();
 }
exec()
bool QPSQLResult::exec () protected virtual
Executes the query, returning true if successful; otherwise returns false.
See also
prepare()
Reimplemented from QSqlResult.
Definition at line 612 of file qsql_psql.cpp.
Referenced by QPSQLDriverPrivate::detectBackslashEscape(), QPSQLDriverPrivate::getPSQLVersion(), QPSQLDriverPrivate::setDatestyle(), and QPSQLDriverPrivate::setEncodingUtf8().
 {
     if (!d->preparedQueriesEnabled)
         return QSqlResult::exec();
     cleanup();
     QString stmt;
     const QString params = qCreateParamString(boundValues(), d->q->driver());
     if (params.isEmpty())
         stmt = QString::fromLatin1("EXECUTE %1").arg(d->preparedStmtId);
     else
         stmt = QString::fromLatin1("EXECUTE %1 (%2)").arg(d->preparedStmtId).arg(params);
     d->result = d->driver->exec(stmt);
     return d->processResults();
 }
fetch()
bool QPSQLResult::fetch (int index) protected virtual
Positions the result to an arbitrary (zero-based) row index.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the row index, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
isActive(), fetchFirst(), fetchLast(), fetchNext(), fetchPrevious()
Implements QSqlResult.
Definition at line 329 of file qsql_psql.cpp.
Referenced by fetchFirst(), and fetchLast().
 {
     if (!isActive())
         return false;
     if (i < 0)
         return false;
     if (i >= d->currentSize)
         return false;
     if (at() == i)
         return true;
     setAt(i);
     return true;
 }
fetchFirst()
bool QPSQLResult::fetchFirst () protected virtual
Positions the result to the first record (row 0) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the first record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchLast()
Implements QSqlResult.
Definition at line 343 of file qsql_psql.cpp.
 {
     return fetch(0);
 }
fetchLast()
bool QPSQLResult::fetchLast () protected virtual
Positions the result to the last record (last row) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the last record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchFirst()
Implements QSqlResult.
Definition at line 348 of file qsql_psql.cpp.
 {
     return fetch(PQntuples(d->result) - 1);
 }
handle()
QVariant QPSQLResult::handle () const virtual
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the result is modified (for example, if you clear it).
The handle can be NULL if the result was not executed yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a sqlite result:
QSqlQuery query = ...
QVariant v = query.result()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3_stmt*")) {
    // v.data() returns a pointer to the handle
    sqlite3_stmt *handle = *static_cast<sqlite3_stmt **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (v.typeName() == "PGresult*") {
    PGresult *handle = *static_cast<PGresult **>(v.data());
    if (handle != 0) ...
}
if (v.typeName() == "MYSQL_STMT*") {
    MYSQL_STMT *handle = *static_cast<MYSQL_STMT **>(v.data());
    if (handle != 0) ...
}
See also
QSqlDriver::handle()
Reimplemented from QSqlResult.
Definition at line 314 of file qsql_psql.cpp.
 {
     return QVariant::fromValue(d->result);
 }
isNull()
bool QPSQLResult::isNull (int i) protected virtual
Returns true if the field at position index in the current row is null; otherwise returns false.
Implements QSqlResult.
Definition at line 453 of file qsql_psql.cpp.
 {
     PQgetvalue(d->result, at(), field);
     return PQgetisnull(d->result, at(), field);
 }
lastInsertId()
QVariant QPSQLResult::lastInsertId () const protected virtual
Returns the object ID of the most recent inserted row if the database supports it.
An invalid QVariant will be returned if the query did not insert any value or if the database does not report the id back. If more than one row was touched by the insert, the behavior is undefined.
Note that for Oracle databases the row's ROWID will be returned, while for MySQL databases the row's auto-increment field will be returned.
See also
QSqlDriver::hasFeature()
Reimplemented from QSqlResult.
Definition at line 480 of file qsql_psql.cpp.
 {
     if (isActive()) {
         Oid id = PQoidValue(d->result);
         if (id != InvalidOid)
             return QVariant(id);
     }
     return QVariant();
 }
numRowsAffected()
int QPSQLResult::numRowsAffected () protected virtual
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
See also
size()
Implements QSqlResult.
Definition at line 475 of file qsql_psql.cpp.
 {
     return QString::fromLatin1(PQcmdTuples(d->result)).toInt();
 }
prepare()
bool QPSQLResult::prepare (const QString & query) protected virtual
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
Returns true if the query is prepared successfully; otherwise returns false.
See also
exec()
Reimplemented from QSqlResult.
Definition at line 584 of file qsql_psql.cpp.
 {
     if (!d->preparedQueriesEnabled)
         return QSqlResult::prepare(query);
     cleanup();
     if (!d->preparedStmtId.isEmpty())
         qDeallocatePreparedStmt(d);
     const QString stmtId = qMakePreparedStmtId();
     const QString stmt = QString::fromLatin1("PREPARE %1 AS ").arg(stmtId).append(qReplacePlaceholderMarkers(query));
     PGresult *result = d->driver->exec(stmt);
     if (PQresultStatus(result) != PGRES_COMMAND_OK) {
         setLastError(qMakeError(QCoreApplication::translate("QPSQLResult",
                                 "Unable to prepare statement"), QSqlError::StatementError, d->driver, result));
         PQclear(result);
         d->preparedStmtId.clear();
         return false;
     }
     PQclear(result);
     d->preparedStmtId = stmtId;
     return true;
 }
record()
QSqlRecord QPSQLResult::record () const protected virtual
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
The default implementation always returns an empty QSqlRecord.
See also
isActive()
Reimplemented from QSqlResult.
Definition at line 490 of file qsql_psql.cpp.
 {
     QSqlRecord info;
     if (!isActive() || !isSelect())
         return info;
     int count = PQnfields(d->result);
     for (int i = 0; i < count; ++i) {
         QSqlField f;
         if (d->driver->isUtf8)
             f.setName(QString::fromUtf8(PQfname(d->result, i)));
         else
             f.setName(QString::fromLocal8Bit(PQfname(d->result, i)));
         f.setType(qDecodePSQLType(PQftype(d->result, i)));
         int len = PQfsize(d->result, i);
         int precision = PQfmod(d->result, i);
         // swap length and precision if length == -1
         if (len == -1 && precision > -1) {
             len = precision - 4;
             precision = -1;
         }
         f.setLength(len);
         f.setPrecision(precision);
         f.setSqlType(PQftype(d->result, i));
         info.append(f);
     }
     return info;
 }
reset()
bool QPSQLResult::reset (const QString & query) protected virtual
Sets the result to use the SQL statement query for subsequent data retrieval.
Derived classes must reimplement this function and apply the query to the database. This function is only called after the result is set to an inactive state and is positioned before the first record of the new result. Derived classes should return true if the query was successful and ready to be used, or false otherwise.
See also
setQuery()
Implements QSqlResult.
Definition at line 459 of file qsql_psql.cpp.
 {
     cleanup();
     if (!driver())
         return false;
     if (!driver()->isOpen() || driver()->isOpenError())
         return false;
     d->result = d->driver->exec(query);
     return d->processResults();
 }
size()
int QPSQLResult::size () protected virtual
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
See also
numRowsAffected()
Implements QSqlResult.
Definition at line 470 of file qsql_psql.cpp.
 {
     return d->currentSize;
 }
virtual_hook()
void QPSQLResult::virtual_hook (int id, void * data) virtual
Warning
This function is not part of the public interface.
Reimplemented from QSqlResult.
Definition at line 519 of file qsql_psql.cpp.
 {
     Q_ASSERT(data);
     switch (id) {
     default:
         QSqlResult::virtual_hook(id, data);
     }
 }
Friends and Related Functions
QPSQLResultPrivate
friend class QPSQLResultPrivate friend
Definition at line 68 of file qsql_psql.h.
Referenced by QPSQLResult().
Properties
d
QPSQLResultPrivate* QPSQLResult::d private
Definition at line 92 of file qsql_psql.h.
Referenced by cleanup(), data(), exec(), fetch(), fetchLast(), handle(), isNull(), lastInsertId(), numRowsAffected(), prepare(), QPSQLResult(), record(), reset(), size(), and ~QPSQLResult().
The documentation for this class was generated from the following files:
/src/sql/drivers/psql/qsql_psql.h
/src/sql/drivers/psql/qsql_psql.cpp