Qt 4.8: QZipReader Class Reference
QZipReader Class Reference
the QZipReader class provides a way to inspect the contents of a zip archive and extract individual files from it.
#include <qzipreader_p.h>
Classes
class FileInfo
Represents one entry in the zip table of contents.
Public Types
enum Status {
NoError, FileReadError, FileOpenError, FilePermissionsError,
FileError
}
The following status values are possible:
Public Functions
void close ()
Close the zip file.
int count () const
Return the number of items in the zip archive.
QIODevice * device () const
Returns device used for reading zip archive.
FileInfo entryInfoAt (int index) const
Returns a FileInfo of an entry in the zipfile.
bool exists () const
Returns true if the file exists; otherwise returns false.
bool extractAll (const QString &destinationDir) const
Extracts the full contents of the zip file into destinationDir on the local filesystem.
QByteArray fileData (const QString &fileName) const
Fetch the file contents from the zip archive and return the uncompressed bytes.
QList< FileInfo > fileInfoList () const
Returns the list of files the archive contains.
bool isReadable () const
Returns true if the user can read the file; otherwise returns false.
QZipReader (const QString &fileName, QIODevice::OpenMode mode=QIODevice::ReadOnly)
Create a new zip archive that operates on the fileName.
QZipReader (QIODevice *device)
Create a new zip archive that operates on the archive found in device.
Status status () const
Returns a status code indicating the first error that was met by QZipReader, or QZipReader::NoError if no error occurred.
~QZipReader ()
Desctructor.
Properties
QZipReaderPrivate * d
Detailed Description
the QZipReader class provides a way to inspect the contents of a zip archive and extract individual files from it.
Warning
This function is not part of the public interface.
Since
4.5
QZipReader can be used to read a zip archive either from a file or from any device. An in-memory QBuffer for instance. The reader can be used to read which files are in the archive using fileInfoList() and entryInfoAt() but also to extract individual files using fileData() or even to extract all files in the archive using extractAll()
Definition at line 66 of file qzipreader_p.h.
Enumerations
Status
enum QZipReader::Status
The following status values are possible:
NoError No error occurred.
FileReadError An error occurred when reading from the file.
FileOpenError The file could not be opened.
FilePermissionsError The file could not be accessed.
FileError Another file error occurred.
Enumerator
NoError
FileReadError
FileOpenError
FilePermissionsError
FileError
Definition at line 104 of file qzipreader_p.h.
                 {
         NoError,
         FileReadError,
         FileOpenError,
         FilePermissionsError,
         FileError
     };
Constructors and Destructors
QZipReader() [1/2]
QZipReader::QZipReader (const QString & archive, QIODevice::OpenMode mode = QIODevice::ReadOnly)
Create a new zip archive that operates on the fileName.
The file will be opened with the mode.
Definition at line 758 of file qzip.cpp.
 {
     QScopedPointer<QFile> f(new QFile(archive));
     f->open(mode);
     QZipReader::Status status;
     if (f->error() == QFile::NoError)
         status = NoError;
     else {
         if (f->error() == QFile::ReadError)
             status = FileReadError;
         else if (f->error() == QFile::OpenError)
             status = FileOpenError;
         else if (f->error() == QFile::PermissionsError)
             status = FilePermissionsError;
         else
             status = FileError;
     }
     d = new QZipReaderPrivate(f.data(), /*ownDevice=*/true);
     f.take();
     d->status = status;
 }
QZipReader() [2/2]
QZipReader::QZipReader (QIODevice * device) explicit
Create a new zip archive that operates on the archive found in device.
You have to open the device previous to calling the constructor and only a device that is readable will be scanned for zip filecontent.
Definition at line 786 of file qzip.cpp.
     : d(new QZipReaderPrivate(device, /*ownDevice=*/false))
 {
     Q_ASSERT(device);
 }
~QZipReader()
QZipReader::~QZipReader ()
Desctructor.
Definition at line 795 of file qzip.cpp.
 {
     close();
     delete d;
 }
Functions
close()
void QZipReader::close ()
Close the zip file.
Definition at line 1021 of file qzip.cpp.
Referenced by ~QZipReader().
 {
     d->device->close();
 }
count()
int QZipReader::count () const
Return the number of items in the zip archive.
Definition at line 847 of file qzip.cpp.
 {
     d->scanFiles();
     return d->fileHeaders.count();
 }
device()
QIODevice * QZipReader::device () const
Returns device used for reading zip archive.
Definition at line 804 of file qzip.cpp.
Referenced by QZipWriterPrivate::addEntry(), QZipReaderPrivate::scanFiles(), and QZipPrivate::~QZipPrivate().
 {
     return d->device;
 }
entryInfoAt()
QZipReader::FileInfo QZipReader::entryInfoAt (int index) const
Returns a FileInfo of an entry in the zipfile.
The index is the index into the directory listing of the zipfile. Returns an invalid FileInfo if index is out of boundaries.
See also
fileInfoList()
Definition at line 860 of file qzip.cpp.
 {
     d->scanFiles();
     QZipReader::FileInfo fi;
     if (index >= 0 && index < d->fileHeaders.count())
         d->fillFileInfo(index, fi);
     return fi;
 }
exists()
bool QZipReader::exists () const
Returns true if the file exists; otherwise returns false.
Definition at line 820 of file qzip.cpp.
 {
     QFile *f = qobject_cast<QFile*> (d->device);
     if (f == 0)
         return true;
     return f->exists();
 }
extractAll()
bool QZipReader::extractAll (const QString & destinationDir) const
Extracts the full contents of the zip file into destinationDir on the local filesystem.
In case writing or linking a file fails, the extraction will be aborted.
Definition at line 944 of file qzip.cpp.
 {
     QDir baseDir(destinationDir);
     // create directories first
     QList<FileInfo> allFiles = fileInfoList();
     foreach (FileInfo fi, allFiles) {
         const QString absPath = destinationDir + QDir::separator() + fi.filePath;
         if (fi.isDir) {
             if (!baseDir.mkpath(fi.filePath))
                 return false;
             if (!QFile::setPermissions(absPath, fi.permissions))
                 return false;
         }
     }
     // set up symlinks
     foreach (FileInfo fi, allFiles) {
         const QString absPath = destinationDir + QDir::separator() + fi.filePath;
         if (fi.isSymLink) {
             QString destination = QFile::decodeName(fileData(fi.filePath));
             if (destination.isEmpty())
                 return false;
             QFileInfo linkFi(absPath);
             if (!QFile::exists(linkFi.absolutePath()))
                 QDir::root().mkpath(linkFi.absolutePath());
             if (!QFile::link(destination, absPath))
                 return false;
             /* cannot change permission of links
             if (!QFile::setPermissions(absPath, fi.permissions))
                 return false;
             */
         }
     }
     foreach (FileInfo fi, allFiles) {
         const QString absPath = destinationDir + QDir::separator() + fi.filePath;
         if (fi.isFile) {
             QFile f(absPath);
             if (!f.open(QIODevice::WriteOnly))
                 return false;
             f.write(fileData(fi.filePath));
             f.setPermissions(fi.permissions);
             f.close();
         }
     }
     return true;
 }
fileData()
QByteArray QZipReader::fileData (const QString & fileName) const
Fetch the file contents from the zip archive and return the uncompressed bytes.
Definition at line 872 of file qzip.cpp.
Referenced by extractAll().
 {
     d->scanFiles();
     int i;
     for (i = 0; i < d->fileHeaders.size(); ++i) {
         if (QString::fromLocal8Bit(d->fileHeaders.at(i).file_name) == fileName)
             break;
     }
     if (i == d->fileHeaders.size())
         return QByteArray();
     FileHeader header = d->fileHeaders.at(i);
     int compressed_size = readUInt(header.h.compressed_size);
     int uncompressed_size = readUInt(header.h.uncompressed_size);
     int start = readUInt(header.h.offset_local_header);
     //qDebug("uncompressing file %d: local header at %d", i, start);
     d->device->seek(start);
     LocalFileHeader lh;
     d->device->read((char *)&lh, sizeof(LocalFileHeader));
     uint skip = readUShort(lh.file_name_length) + readUShort(lh.extra_field_length);
     d->device->seek(d->device->pos() + skip);
     int compression_method = readUShort(lh.compression_method);
     //qDebug("file=%s: compressed_size=%d, uncompressed_size=%d", fileName.toLocal8Bit().data(), compressed_size, uncompressed_size);
     //qDebug("file at %lld", d->device->pos());
     QByteArray compressed = d->device->read(compressed_size);
     if (compression_method == 0) {
         // no compression
         compressed.truncate(uncompressed_size);
         return compressed;
     } else if (compression_method == 8) {
         // Deflate
         //qDebug("compressed=%d", compressed.size());
         compressed.truncate(compressed_size);
         QByteArray baunzip;
         ulong len = qMax(uncompressed_size,  1);
         int res;
         do {
             baunzip.resize(len);
             res = inflate((uchar*)baunzip.data(), &len,
                           (uchar*)compressed.constData(), compressed_size);
             switch (res) {
             case Z_OK:
                 if ((int)len != baunzip.size())
                     baunzip.resize(len);
                 break;
             case Z_MEM_ERROR:
                 qWarning("QZip: Z_MEM_ERROR: Not enough memory");
                 break;
             case Z_BUF_ERROR:
                 len *= 2;
                 break;
             case Z_DATA_ERROR:
                 qWarning("QZip: Z_DATA_ERROR: Input data is corrupted");
                 break;
             }
         } while (res == Z_BUF_ERROR);
         return baunzip;
     }
     qWarning() << "QZip: Unknown compression method";
     return QByteArray();
 }
fileInfoList()
QList< QZipReader::FileInfo > QZipReader::fileInfoList () const
Returns the list of files the archive contains.
Definition at line 831 of file qzip.cpp.
Referenced by extractAll().
 {
     d->scanFiles();
     QList<QZipReader::FileInfo> files;
     for (int i = 0; i < d->fileHeaders.size(); ++i) {
         QZipReader::FileInfo fi;
         d->fillFileInfo(i, fi);
         files.append(fi);
     }
     return files;
 }
isReadable()
bool QZipReader::isReadable () const
Returns true if the user can read the file; otherwise returns false.
Definition at line 812 of file qzip.cpp.
 {
     return d->device->isReadable();
 }
status()
QZipReader::Status QZipReader::status () const
Returns a status code indicating the first error that was met by QZipReader, or QZipReader::NoError if no error occurred.
Definition at line 1013 of file qzip.cpp.
Referenced by QZipWriterPrivate::addEntry(), QZipReader(), QZipWriter::QZipWriter(), and QZipReaderPrivate::scanFiles().
 {
     return d->status;
 }
Properties
d
QZipReaderPrivate* QZipReader::d private
Definition at line 117 of file qzipreader_p.h.
Referenced by close(), count(), device(), entryInfoAt(), exists(), fileData(), fileInfoList(), isReadable(), QZipWriter::QZipWriter(), status(), and ~QZipReader().
The documentation for this class was generated from the following files:
/src/gui/text/qzipreader_p.h
/src/gui/text/qzip.cpp