Qt 4.8: QDeclarativeKeysAttached Class Reference
QDeclarativeKeysAttached Class Reference
#include <qdeclarativeitem_p.h>
Classes
struct SigMap
Public Types
enum Priority { BeforeItem, AfterItem }
Signals
void asteriskPressed (QDeclarativeKeyEvent *event)
void backPressed (QDeclarativeKeyEvent *event)
void backtabPressed (QDeclarativeKeyEvent *event)
void callPressed (QDeclarativeKeyEvent *event)
void cancelPressed (QDeclarativeKeyEvent *event)
void context1Pressed (QDeclarativeKeyEvent *event)
void context2Pressed (QDeclarativeKeyEvent *event)
void context3Pressed (QDeclarativeKeyEvent *event)
void context4Pressed (QDeclarativeKeyEvent *event)
void deletePressed (QDeclarativeKeyEvent *event)
void digit0Pressed (QDeclarativeKeyEvent *event)
void digit1Pressed (QDeclarativeKeyEvent *event)
void digit2Pressed (QDeclarativeKeyEvent *event)
void digit3Pressed (QDeclarativeKeyEvent *event)
void digit4Pressed (QDeclarativeKeyEvent *event)
void digit5Pressed (QDeclarativeKeyEvent *event)
void digit6Pressed (QDeclarativeKeyEvent *event)
void digit7Pressed (QDeclarativeKeyEvent *event)
void digit8Pressed (QDeclarativeKeyEvent *event)
void digit9Pressed (QDeclarativeKeyEvent *event)
void downPressed (QDeclarativeKeyEvent *event)
void enabledChanged ()
void enterPressed (QDeclarativeKeyEvent *event)
void escapePressed (QDeclarativeKeyEvent *event)
void flipPressed (QDeclarativeKeyEvent *event)
void hangupPressed (QDeclarativeKeyEvent *event)
void leftPressed (QDeclarativeKeyEvent *event)
void menuPressed (QDeclarativeKeyEvent *event)
void noPressed (QDeclarativeKeyEvent *event)
void numberSignPressed (QDeclarativeKeyEvent *event)
void pressed (QDeclarativeKeyEvent *event)
void priorityChanged ()
void released (QDeclarativeKeyEvent *event)
void returnPressed (QDeclarativeKeyEvent *event)
void rightPressed (QDeclarativeKeyEvent *event)
void selectPressed (QDeclarativeKeyEvent *event)
void spacePressed (QDeclarativeKeyEvent *event)
void tabPressed (QDeclarativeKeyEvent *event)
void upPressed (QDeclarativeKeyEvent *event)
void volumeDownPressed (QDeclarativeKeyEvent *event)
void volumeUpPressed (QDeclarativeKeyEvent *event)
void yesPressed (QDeclarativeKeyEvent *event)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void componentComplete ()
bool enabled () const
QDeclarativeListProperty< QDeclarativeItem > forwardTo ()
Priority priority () const
QDeclarativeKeysAttached (QObject *parent=0)
void setEnabled (bool enabled)
void setPriority (Priority)
~QDeclarativeKeysAttached ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeItemKeyFilter
QDeclarativeItemKeyFilter (QDeclarativeItem *=0)
virtual ~QDeclarativeItemKeyFilter ()
Static Public Functions
static QDeclarativeKeysAttached * qmlAttachedProperties (QObject *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Functions
virtual void inputMethodEvent (QInputMethodEvent *, bool post)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
virtual void keyPressed (QKeyEvent *event, bool post)
virtual void keyReleased (QKeyEvent *event, bool post)
const QByteArray keyToSignal (int key)
Properties
bool enabled
QDeclarativeListProperty< QDeclarativeItem > forwardTo
Priority priority
Static Private Attributes
static const SigMap sigMap []
This handler is called when a key has been pressed.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Variables inherited from QDeclarativeItemKeyFilter
bool m_processPost
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 495 of file qdeclarativeitem_p.h.
Enumerations
Priority
enum QDeclarativeKeysAttached::Priority
Enumerator
BeforeItem
AfterItem
Definition at line 519 of file qdeclarativeitem_p.h.
 { BeforeItem, AfterItem};
Constructors and Destructors
QDeclarativeKeysAttached()
QDeclarativeKeysAttached::QDeclarativeKeysAttached (QObject * parent = 0)
Definition at line 1516 of file qdeclarativeitem.cpp.
Referenced by qmlAttachedProperties().
 : QObject(*(new QDeclarativeKeysAttachedPrivate), parent),
   QDeclarativeItemKeyFilter(qobject_cast<QDeclarativeItem*>(parent))
 {
     Q_D(QDeclarativeKeysAttached);
     m_processPost = false;
     d->item = qobject_cast<QDeclarativeItem*>(parent);
 }
~QDeclarativeKeysAttached()
QDeclarativeKeysAttached::~QDeclarativeKeysAttached ()
Definition at line 1525 of file qdeclarativeitem.cpp.
 {
 }
Functions
asteriskPressed
void QDeclarativeKeysAttached::asteriskPressed (QDeclarativeKeyEvent * event) signal
backPressed
void QDeclarativeKeysAttached::backPressed (QDeclarativeKeyEvent * event) signal
backtabPressed
void QDeclarativeKeysAttached::backtabPressed (QDeclarativeKeyEvent * event) signal
callPressed
void QDeclarativeKeysAttached::callPressed (QDeclarativeKeyEvent * event) signal
cancelPressed
void QDeclarativeKeysAttached::cancelPressed (QDeclarativeKeyEvent * event) signal
componentComplete()
void QDeclarativeKeysAttached::componentComplete () virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 1543 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeysAttached);
     if (d->item) {
         for (int ii = 0; ii < d->targets.count(); ++ii) {
             QGraphicsItem *targetItem = d->finalFocusProxy(d->targets.at(ii));
             if (targetItem && (targetItem->flags() & QGraphicsItem::ItemAcceptsInputMethod)) {
                 d->item->setFlag(QGraphicsItem::ItemAcceptsInputMethod);
                 break;
             }
         }
     }
 }
context1Pressed
void QDeclarativeKeysAttached::context1Pressed (QDeclarativeKeyEvent * event) signal
context2Pressed
void QDeclarativeKeysAttached::context2Pressed (QDeclarativeKeyEvent * event) signal
context3Pressed
void QDeclarativeKeysAttached::context3Pressed (QDeclarativeKeyEvent * event) signal
context4Pressed
void QDeclarativeKeysAttached::context4Pressed (QDeclarativeKeyEvent * event) signal
deletePressed
void QDeclarativeKeysAttached::deletePressed (QDeclarativeKeyEvent * event) signal
digit0Pressed
void QDeclarativeKeysAttached::digit0Pressed (QDeclarativeKeyEvent * event) signal
digit1Pressed
void QDeclarativeKeysAttached::digit1Pressed (QDeclarativeKeyEvent * event) signal
digit2Pressed
void QDeclarativeKeysAttached::digit2Pressed (QDeclarativeKeyEvent * event) signal
digit3Pressed
void QDeclarativeKeysAttached::digit3Pressed (QDeclarativeKeyEvent * event) signal
digit4Pressed
void QDeclarativeKeysAttached::digit4Pressed (QDeclarativeKeyEvent * event) signal
digit5Pressed
void QDeclarativeKeysAttached::digit5Pressed (QDeclarativeKeyEvent * event) signal
digit6Pressed
void QDeclarativeKeysAttached::digit6Pressed (QDeclarativeKeyEvent * event) signal
digit7Pressed
void QDeclarativeKeysAttached::digit7Pressed (QDeclarativeKeyEvent * event) signal
digit8Pressed
void QDeclarativeKeysAttached::digit8Pressed (QDeclarativeKeyEvent * event) signal
digit9Pressed
void QDeclarativeKeysAttached::digit9Pressed (QDeclarativeKeyEvent * event) signal
downPressed
void QDeclarativeKeysAttached::downPressed (QDeclarativeKeyEvent * event) signal
enabled()
bool QDeclarativeKeysAttached::enabled () const inline
Definition at line 510 of file qdeclarativeitem_p.h.
 { Q_D(const QDeclarativeKeysAttached); return d->enabled; }
enabledChanged
void QDeclarativeKeysAttached::enabledChanged () signal
enterPressed
void QDeclarativeKeysAttached::enterPressed (QDeclarativeKeyEvent * event) signal
escapePressed
void QDeclarativeKeysAttached::escapePressed (QDeclarativeKeyEvent * event) signal
flipPressed
void QDeclarativeKeysAttached::flipPressed (QDeclarativeKeyEvent * event) signal
forwardTo()
QDeclarativeListProperty<QDeclarativeItem> QDeclarativeKeysAttached::forwardTo () inline
Definition at line 523 of file qdeclarativeitem_p.h.
{
         Q_D(QDeclarativeKeysAttached);
         return QDeclarativeListProperty<QDeclarativeItem>(this, d->targets);
     }
hangupPressed
void QDeclarativeKeysAttached::hangupPressed (QDeclarativeKeyEvent * event) signal
inputMethodEvent()
void QDeclarativeKeysAttached::inputMethodEvent (QInputMethodEvent * event, bool post) private virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 1631 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeysAttached);
     if (post == m_processPost && d->item && !d->inIM && d->item->scene()) {
         d->inIM = true;
         for (int ii = 0; ii < d->targets.count(); ++ii) {
             QGraphicsItem *i = d->finalFocusProxy(d->targets.at(ii));
             if (i && i->isVisible() && (i->flags() & QGraphicsItem::ItemAcceptsInputMethod)) {
                 d->item->scene()->sendEvent(i, event);
                 if (event->isAccepted()) {
                     d->imeItem = i;
                     d->inIM = false;
                     return;
                 }
             }
         }
         d->inIM = false;
     }
     if (!event->isAccepted()) QDeclarativeItemKeyFilter::inputMethodEvent(event, post);
 }
inputMethodQuery()
QVariant QDeclarativeKeysAttached::inputMethodQuery (Qt::InputMethodQuery query) const private virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 1660 of file qdeclarativeitem.cpp.
 {
     Q_D(const QDeclarativeKeysAttached);
     if (d->item) {
         for (int ii = 0; ii < d->targets.count(); ++ii) {
                 QGraphicsItem *i = d->finalFocusProxy(d->targets.at(ii));
             if (i && i->isVisible() && (i->flags() & QGraphicsItem::ItemAcceptsInputMethod) && i == d->imeItem) { //### how robust is i == d->imeItem check?
                 QVariant v = static_cast<QDeclarativeItemAccessor *>(i)->doInputMethodQuery(query);
                 if (v.userType() == QVariant::RectF)
                     v = d->item->mapRectFromItem(i, v.toRectF());  //### cost?
                 return v;
             }
         }
     }
     return QDeclarativeItemKeyFilter::inputMethodQuery(query);
 }
keyPressed()
void QDeclarativeKeysAttached::keyPressed (QKeyEvent * event, bool post) private virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 1557 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeysAttached);
     if (post != m_processPost || !d->enabled || d->inPress) {
         event->ignore();
         QDeclarativeItemKeyFilter::keyPressed(event, post);
         return;
     }
     // first process forwards
     if (d->item && d->item->scene()) {
         d->inPress = true;
         for (int ii = 0; ii < d->targets.count(); ++ii) {
             QGraphicsItem *i = d->finalFocusProxy(d->targets.at(ii));
             if (i && i->isVisible()) {
                 d->item->scene()->sendEvent(i, event);
                 if (event->isAccepted()) {
                     d->inPress = false;
                     return;
                 }
             }
         }
         d->inPress = false;
     }
     QDeclarativeKeyEvent ke(*event);
     QByteArray keySignal = keyToSignal(event->key());
     if (!keySignal.isEmpty()) {
         keySignal += "(QDeclarativeKeyEvent*)";
         if (d->isConnected(keySignal)) {
             // If we specifically handle a key then default to accepted
             ke.setAccepted(true);
             int idx = QDeclarativeKeysAttached::staticMetaObject.indexOfSignal(keySignal);
             metaObject()->method(idx).invoke(this, Qt::DirectConnection, Q_ARG(QDeclarativeKeyEvent*, &ke));
         }
     }
     if (!ke.isAccepted())
         emit pressed(&ke);
     event->setAccepted(ke.isAccepted());
     if (!event->isAccepted()) QDeclarativeItemKeyFilter::keyPressed(event, post);
 }
keyReleased()
void QDeclarativeKeysAttached::keyReleased (QKeyEvent * event, bool post) private virtual
Reimplemented from QDeclarativeItemKeyFilter.
Definition at line 1600 of file qdeclarativeitem.cpp.
 {
     Q_D(QDeclarativeKeysAttached);
     if (post != m_processPost || !d->enabled || d->inRelease) {
         event->ignore();
         QDeclarativeItemKeyFilter::keyReleased(event, post);
         return;
     }
     if (d->item && d->item->scene()) {
         d->inRelease = true;
         for (int ii = 0; ii < d->targets.count(); ++ii) {
             QGraphicsItem *i = d->finalFocusProxy(d->targets.at(ii));
             if (i && i->isVisible()) {
                 d->item->scene()->sendEvent(i, event);
                 if (event->isAccepted()) {
                     d->inRelease = false;
                     return;
                 }
             }
         }
         d->inRelease = false;
     }
     QDeclarativeKeyEvent ke(*event);
     emit released(&ke);
     event->setAccepted(ke.isAccepted());
     if (!event->isAccepted()) QDeclarativeItemKeyFilter::keyReleased(event, post);
 }
keyToSignal()
const QByteArray QDeclarativeKeysAttached::keyToSignal (int key) inline private
Definition at line 584 of file qdeclarativeitem_p.h.
Referenced by keyPressed().
{
         QByteArray keySignal;
         if (key >= Qt::Key_0 && key <= Qt::Key_9) {
             keySignal = "digit0Pressed";
             keySignal[5] = '0' + (key - Qt::Key_0);
         } else {
             int i = 0;
             while (sigMap[i].key && sigMap[i].key != key)
                 ++i;
             keySignal = sigMap[i].sig;
         }
         return keySignal;
     }
leftPressed
void QDeclarativeKeysAttached::leftPressed (QDeclarativeKeyEvent * event) signal
menuPressed
void QDeclarativeKeysAttached::menuPressed (QDeclarativeKeyEvent * event) signal
noPressed
void QDeclarativeKeysAttached::noPressed (QDeclarativeKeyEvent * event) signal
numberSignPressed
void QDeclarativeKeysAttached::numberSignPressed (QDeclarativeKeyEvent * event) signal
pressed
void QDeclarativeKeysAttached::pressed (QDeclarativeKeyEvent * event) signal
Referenced by keyPressed().
priority()
Priority QDeclarativeKeysAttached::priority () const
Referenced by ~QDeclarativeKeysAttached().
priorityChanged
void QDeclarativeKeysAttached::priorityChanged () signal
Referenced by setPriority().
qmlAttachedProperties()
QDeclarativeKeysAttached * QDeclarativeKeysAttached::qmlAttachedProperties (QObject * obj) static
Definition at line 1677 of file qdeclarativeitem.cpp.
 {
     return new QDeclarativeKeysAttached(obj);
 }
released
void QDeclarativeKeysAttached::released (QDeclarativeKeyEvent * event) signal
Referenced by keyReleased().
returnPressed
void QDeclarativeKeysAttached::returnPressed (QDeclarativeKeyEvent * event) signal
rightPressed
void QDeclarativeKeysAttached::rightPressed (QDeclarativeKeyEvent * event) signal
selectPressed
void QDeclarativeKeysAttached::selectPressed (QDeclarativeKeyEvent * event) signal
setEnabled()
void QDeclarativeKeysAttached::setEnabled (bool enabled) inline
Definition at line 511 of file qdeclarativeitem_p.h.
{
         Q_D(QDeclarativeKeysAttached);
         if (enabled != d->enabled) {
             d->enabled = enabled;
             emit enabledChanged();
         }
     }
setPriority()
void QDeclarativeKeysAttached::setPriority (Priority order)
Definition at line 1534 of file qdeclarativeitem.cpp.
 {
     bool processPost = order == AfterItem;
     if (processPost != m_processPost) {
         m_processPost = processPost;
         emit priorityChanged();
     }
 }
spacePressed
void QDeclarativeKeysAttached::spacePressed (QDeclarativeKeyEvent * event) signal
tabPressed
void QDeclarativeKeysAttached::tabPressed (QDeclarativeKeyEvent * event) signal
upPressed
void QDeclarativeKeysAttached::upPressed (QDeclarativeKeyEvent * event) signal
volumeDownPressed
void QDeclarativeKeysAttached::volumeDownPressed (QDeclarativeKeyEvent * event) signal
volumeUpPressed
void QDeclarativeKeysAttached::volumeUpPressed (QDeclarativeKeyEvent * event) signal
yesPressed
void QDeclarativeKeysAttached::yesPressed (QDeclarativeKeyEvent * event) signal
Properties
enabled
bool QDeclarativeKeysAttached::enabled private
Definition at line 500 of file qdeclarativeitem_p.h.
forwardTo
QDeclarativeListProperty<QDeclarativeItem> QDeclarativeKeysAttached::forwardTo private
Definition at line 501 of file qdeclarativeitem_p.h.
priority
QDeclarativeKeysAttached::Priority QDeclarativeKeysAttached::priority private
Definition at line 502 of file qdeclarativeitem_p.h.
sigMap
const QDeclarativeKeysAttached::SigMap QDeclarativeKeysAttached::sigMap static private
This handler is called when a key has been pressed.
Keys::onPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when a key has been released.
Keys::onReleased(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '0' has been pressed.
Keys::onDigit0Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '1' has been pressed.
Keys::onDigit1Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '2' has been pressed.
Keys::onDigit2Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '3' has been pressed.
Keys::onDigit3Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '4' has been pressed.
Keys::onDigit4Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '5' has been pressed.
Keys::onDigit5Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '6' has been pressed.
Keys::onDigit6Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '7' has been pressed.
Keys::onDigit7Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '8' has been pressed.
Keys::onDigit8Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the digit '9' has been pressed.
Keys::onDigit9Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Left arrow has been pressed.
Keys::onLeftPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Right arrow has been pressed.
Keys::onRightPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Up arrow has been pressed.
Keys::onUpPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Down arrow has been pressed.
Keys::onDownPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Tab key has been pressed.
Keys::onTabPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Shift+Tab key combination (Backtab) has been pressed.
Keys::onBacktabPressed(KeyEvent event)
The event parameter provides information about the event.
Keys::onAsteriskPressed(KeyEvent event)
This handler is called when the Asterisk '*' has been pressed. The event parameter provides information about the event.
This handler is called when the Escape key has been pressed.
Keys::onEscapePressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Return key has been pressed.
Keys::onReturnPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Enter key has been pressed.
Keys::onEnterPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Delete key has been pressed.
Keys::onDeletePressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Space key has been pressed.
Keys::onSpacePressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Back key has been pressed.
Keys::onBackPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Cancel key has been pressed.
Keys::onCancelPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Select key has been pressed.
Keys::onSelectPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Yes key has been pressed.
Keys::onYesPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the No key has been pressed.
Keys::onNoPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Context1 key has been pressed.
Keys::onContext1Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Context2 key has been pressed.
Keys::onContext2Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Context3 key has been pressed.
Keys::onContext3Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Context4 key has been pressed.
Keys::onContext4Pressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Call key has been pressed.
Keys::onCallPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Hangup key has been pressed.
Keys::onHangupPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Flip key has been pressed.
Keys::onFlipPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the Menu key has been pressed.
Keys::onMenuPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the VolumeUp key has been pressed.
Keys::onVolumeUpPressed(KeyEvent event)
The event parameter provides information about the event.
This handler is called when the VolumeDown key has been pressed.
Keys::onVolumeDownPressed(KeyEvent event)
The event parameter provides information about the event.
Definition at line 603 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeItemPrivate::setLayoutMirror().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeitem_p.h
/src/declarative/graphicsitems/qdeclarativeitem.cpp