Qt 4.8: QJpegHandler Class Reference
QJpegHandler Class Reference
#include <qjpeghandler_p.h>
Public Functions
bool canRead () const
Returns true if an image can be read from the device (i.
QByteArray name () const
Use format() instead.
QVariant option (ImageOption option) const
Returns the value assigned to option as a QVariant.
QJpegHandler ()
bool read (QImage *image)
Read an image from the device, and stores it in image.
void setOption (ImageOption option, const QVariant &value)
Sets the option option with the value value.
bool supportsOption (ImageOption option) const
Returns true if the QImageIOHandler supports the option option; otherwise returns false.
bool write (const QImage &image)
Writes the image image to the assigned device.
~QJpegHandler ()
Public Functions inherited from QImageIOHandler
virtual int currentImageNumber () const
For image formats that support animation, this function returns the sequence number of the current image in the animation.
virtual QRect currentImageRect () const
Returns the rect of the current image.
QIODevice * device () const
Returns the device currently assigned to the QImageIOHandler.
QByteArray format () const
Returns the format that is currently assigned to QImageIOHandler.
virtual int imageCount () const
For image formats that support animation, this function returns the number of images in the animation.
virtual bool jumpToImage (int imageNumber)
For image formats that support animation, this function jumps to the image whose sequence number is imageNumber.
virtual bool jumpToNextImage ()
For image formats that support animation, this function jumps to the next image.
virtual int loopCount () const
For image formats that support animation, this function returns the number of times the animation should loop.
virtual int nextImageDelay () const
For image formats that support animation, this function returns the number of milliseconds to wait until reading the next image.
QImageIOHandler ()
Constructs a QImageIOHandler object.
void setDevice (QIODevice *device)
Sets the device of the QImageIOHandler to device.
void setFormat (const QByteArray &format)
Sets the format of the QImageIOHandler to format.
void setFormat (const QByteArray &format) const
Sets the format of the QImageIOHandler to format.
virtual ~QImageIOHandler ()
Destructs the QImageIOHandler object.
Static Public Functions
static bool canRead (QIODevice *device)
Properties
QJpegHandlerPrivate * d
Additional Inherited Members
Public Types inherited from QImageIOHandler
enum ImageOption {
Size, ClipRect, Description, ScaledClipRect,
ScaledSize, CompressionRatio, Gamma, Quality,
Name, SubType, IncrementalReading, Endianness,
Animation, BackgroundColor, ImageFormat
}
This enum describes the different options supported by QImageIOHandler.
Protected Functions inherited from QImageIOHandler
QImageIOHandler (QImageIOHandlerPrivate &dd)
Constructs a QImageIOHandler object, using the private member dd.
Protected Variables inherited from QImageIOHandler
QScopedPointer< QImageIOHandlerPrivate > d_ptr
Detailed Description
Definition at line 52 of file qjpeghandler_p.h.
Constructors and Destructors
QJpegHandler()
QJpegHandler::QJpegHandler ()
Definition at line 779 of file qjpeghandler.cpp.
     : d(new QJpegHandlerPrivate(this))
 {
     const uint features = qDetectCPUFeatures();
     Q_UNUSED(features);
 #if defined(QT_HAVE_NEON)
     // from qimage_neon.cpp
     Q_GUI_EXPORT void QT_FASTCALL qt_convert_rgb888_to_rgb32_neon(quint32 *dst, const uchar *src, int len);
     if (features & NEON)
         rgb888ToRgb32ConverterPtr = qt_convert_rgb888_to_rgb32_neon;
 #endif // QT_HAVE_NEON
 #if defined(QT_HAVE_SSSE3)
     // from qimage_ssse3.cpp
     Q_GUI_EXPORT void QT_FASTCALL qt_convert_rgb888_to_rgb32_ssse3(quint32 *dst, const uchar *src, int len);
     if (features & SSSE3)
         rgb888ToRgb32ConverterPtr = qt_convert_rgb888_to_rgb32_ssse3;
 #endif // QT_HAVE_SSSE3
 }
~QJpegHandler()
QJpegHandler::~QJpegHandler ()
Definition at line 800 of file qjpeghandler.cpp.
 {
     delete d;
 }
Functions
canRead() [1/2]
bool QJpegHandler::canRead () const virtual
Returns true if an image can be read from the device (i.
e., the image format is supported, the device can be read from and the initial header information suggests that the image can be read); otherwise returns false.
When reimplementing canRead(), make sure that the I/O device (device()) is left in its original state (e.g., by using peek() rather than read()).
See also
read(), QIODevice::peek()
Implements QImageIOHandler.
Definition at line 805 of file qjpeghandler.cpp.
Referenced by QJpegPlugin::capabilities(), createReadHandlerHelper(), and read().
 {
     if(d->state == QJpegHandlerPrivate::Ready && !canRead(device()))
         return false;
     if (d->state != QJpegHandlerPrivate::Error) {
         setFormat("jpeg");
         return true;
     }
     return false;
 }
canRead() [2/2]
bool QJpegHandler::canRead (QIODevice * device) static
Definition at line 818 of file qjpeghandler.cpp.
 {
     if (!device) {
         qWarning("QJpegHandler::canRead() called with no device");
         return false;
     }
     char buffer[2];
     if (device->peek(buffer, 2) != 2)
         return false;
     return uchar(buffer[0]) == 0xff && uchar(buffer[1]) == 0xd8;
 }
name()
QByteArray QJpegHandler::name () const virtual
Use format() instead.
Reimplemented from QImageIOHandler.
Definition at line 895 of file qjpeghandler.cpp.
 {
     return "jpeg";
 }
option()
QVariant QJpegHandler::option (ImageOption option) const virtual
Returns the value assigned to option as a QVariant.
The type of the value depends on the option. For example, option(Size) returns a QSize variant.
See also
setOption(), supportsOption()
Reimplemented from QImageIOHandler.
Definition at line 853 of file qjpeghandler.cpp.
 {
     switch(option) {
     case Quality:
         return d->quality;
     case ScaledSize:
         return d->scaledSize;
     case ScaledClipRect:
         return d->scaledClipRect;
     case ClipRect:
         return d->clipRect;
     case Size:
         d->readJpegHeader(device());
         return d->size;
     case ImageFormat:
         d->readJpegHeader(device());
         return d->format;
     default:
         return QVariant();
     }
 }
read()
bool QJpegHandler::read (QImage * image) virtual
Read an image from the device, and stores it in image.
Returns true if the image is successfully read; otherwise returns false.
For image formats that support incremental loading, and for animation formats, the image handler can assume that image points to the previous frame.
See also
canRead()
Implements QImageIOHandler.
Definition at line 831 of file qjpeghandler.cpp.
 {
     if (!canRead())
         return false;
     return d->read(image);
 }
setOption()
void QJpegHandler::setOption (ImageOption option, const QVariant & value) virtual
Sets the option option with the value value.
See also
option(), ImageOption
Reimplemented from QImageIOHandler.
Definition at line 875 of file qjpeghandler.cpp.
 {
     switch(option) {
     case Quality:
         d->quality = value.toInt();
         break;
     case ScaledSize:
         d->scaledSize = value.toSize();
         break;
     case ScaledClipRect:
         d->scaledClipRect = value.toRect();
         break;
     case ClipRect:
         d->clipRect = value.toRect();
         break;
     default:
         break;
     }
 }
supportsOption()
bool QJpegHandler::supportsOption (ImageOption option) const virtual
Returns true if the QImageIOHandler supports the option option; otherwise returns false.
For example, if the QImageIOHandler supports the Size option, supportsOption(Size) must return true.
See also
setOption(), option()
Reimplemented from QImageIOHandler.
Definition at line 843 of file qjpeghandler.cpp.
 {
     return option == Quality
         || option == ScaledSize
         || option == ScaledClipRect
         || option == ClipRect
         || option == Size
         || option == ImageFormat;
 }
write()
bool QJpegHandler::write (const QImage & image) virtual
Writes the image image to the assigned device.
Returns true on success; otherwise returns false.
The default implementation does nothing, and simply returns false.
Reimplemented from QImageIOHandler.
Definition at line 838 of file qjpeghandler.cpp.
 {
     return write_jpeg_image(image, device(), d->quality);
 }
Properties
d
QJpegHandlerPrivate* QJpegHandler::d private
Definition at line 71 of file qjpeghandler_p.h.
Referenced by canRead(), option(), read(), setOption(), write(), and ~QJpegHandler().
The documentation for this class was generated from the following files:
/src/gui/image/qjpeghandler_p.h
/src/gui/image/qjpeghandler.cpp