Qt 4.8: QGridLayoutRowData Class Reference
QGridLayoutRowData Class Reference
#include <qgridlayoutengine_p.h>
Public Functions
void calculateGeometries (int start, int end, qreal targetSize, qreal *positions, qreal *sizes, qreal *descents, const QGridLayoutBox &totalBox, const QGridLayoutRowInfo &rowInfo)
void distributeMultiCells (const QGridLayoutRowInfo &rowInfo)
void dump (int indent=0) const
void reset (int count)
void stealBox (int start, int end, int which, qreal *positions, qreal *sizes)
QGridLayoutBox totalBox (int start, int end) const
Public Variables
QVector< QGridLayoutBox > boxes
bool hasIgnoreFlag
QBitArray ignore
MultiCellMap multiCellMap
QVector< qreal > spacings
QVector< int > stretches
Detailed Description
Definition at line 229 of file qgridlayoutengine_p.h.
Functions
calculateGeometries()
void QGridLayoutRowData::calculateGeometries (int start, int end, qreal targetSize, qreal * positions, qreal * sizes, qreal * descents, const QGridLayoutBox & totalBox, const QGridLayoutRowInfo & rowInfo)
Definition at line 204 of file qgridlayoutengine.cpp.
 {
     Q_ASSERT(end > start);
     targetSize = qMax(totalBox.q_minimumSize, targetSize);
     int n = end - start;
     QVarLengthArray<qreal> newSizes(n);
     QVarLengthArray<qreal> factors(n);
     qreal sumFactors = 0.0;
     int sumStretches = 0;
     qreal sumAvailable;
     for (int i = 0; i < n; ++i) {
         if (stretches[start + i] > 0)
             sumStretches += stretches[start + i];
     }
     if (targetSize < totalBox.q_preferredSize) {
         stealBox(start, end, MinimumSize, positions, sizes);
         sumAvailable = targetSize - totalBox.q_minimumSize;
         if (sumAvailable > 0.0) {
             qreal sumDesired = totalBox.q_preferredSize - totalBox.q_minimumSize;
             for (int i = 0; i < n; ++i) {
                 if (ignore.testBit(start + i)) {
                     factors[i] = 0.0;
                     continue;
                 }
                 const QGridLayoutBox &box = boxes.at(start + i);
                 qreal desired = box.q_preferredSize - box.q_minimumSize;
                 factors[i] = growthFactorBelowPreferredSize(desired, sumAvailable, sumDesired);
                 sumFactors += factors[i];
             }
             for (int i = 0; i < n; ++i) {
                 Q_ASSERT(sumFactors > 0.0);
                 qreal delta = sumAvailable * factors[i] / sumFactors;
                 newSizes[i] = sizes[i] + delta;
             }
         }
     } else {
         bool isLargerThanMaximum = (targetSize > totalBox.q_maximumSize);
         if (isLargerThanMaximum) {
             stealBox(start, end, MaximumSize, positions, sizes);
             sumAvailable = targetSize - totalBox.q_maximumSize;
         } else {
             stealBox(start, end, PreferredSize, positions, sizes);
             sumAvailable = targetSize - totalBox.q_preferredSize;
         }
         if (sumAvailable > 0.0) {
             qreal sumCurrentAvailable = sumAvailable;
             bool somethingHasAMaximumSize = false;
             qreal sumSizes = 0.0;
             for (int i = 0; i < n; ++i)
                 sumSizes += sizes[i];
             for (int i = 0; i < n; ++i) {
                 if (ignore.testBit(start + i)) {
                     newSizes[i] = 0.0;
                     factors[i] = 0.0;
                     continue;
                 }
                 const QGridLayoutBox &box = boxes.at(start + i);
                 qreal boxSize;
                 qreal desired;
                 if (isLargerThanMaximum) {
                     boxSize = box.q_maximumSize;
                     desired = rowInfo.boxes.value(start + i).q_maximumSize - boxSize;
                 } else {
                     boxSize = box.q_preferredSize;
                     desired = box.q_maximumSize - boxSize;
                 }
                 if (desired == 0.0) {
                     newSizes[i] = sizes[i];
                     factors[i] = 0.0;
                 } else {
                     Q_ASSERT(desired > 0.0);
                     int stretch = stretches[start + i];
                     if (sumStretches == 0) {
                         if (hasIgnoreFlag) {
                             factors[i] = (stretch < 0) ? qreal(1.0) : qreal(0.0);
                         } else {
                             factors[i] = (stretch < 0) ? sizes[i] : qreal(0.0);
                         }
                     } else if (stretch == sumStretches) {
                         factors[i] = 1.0;
                     } else if (stretch <= 0) {
                         factors[i] = 0.0;
                     } else {
                         qreal ultimateSize;
                         qreal ultimateSumSizes;
                         qreal x = ((stretch * sumSizes)
                                    - (sumStretches * boxSize))
                                   / (sumStretches - stretch);
                         if (x >= 0.0) {
                             ultimateSize = boxSize + x;
                             ultimateSumSizes = sumSizes + x;
                         } else {
                             ultimateSize = boxSize;
                             ultimateSumSizes = (sumStretches * boxSize)
                                                         / stretch;
                         }
                         /*
                             We multiply these by 1.5 to give some space for a smooth transition
                             (at the expense of the stretch factors, which are not fully respected
                             during the transition).
                         */
                         ultimateSize = ultimateSize * 3 / 2;
                         ultimateSumSizes = ultimateSumSizes * 3 / 2;
                         qreal beta = ultimateSumSizes - sumSizes;
                         if (!beta) {
                             factors[i] = 1;
                         } else {
                             qreal alpha = qMin(sumCurrentAvailable, beta);
                             qreal ultimateFactor = (stretch * ultimateSumSizes / sumStretches)
                                                    - (boxSize);
                             qreal transitionalFactor = sumCurrentAvailable * (ultimateSize - boxSize) / beta;
                             factors[i] = ((alpha * ultimateFactor)
                                           + ((beta - alpha) * transitionalFactor)) / beta;
                         }
                     }
                     sumFactors += factors[i];
                     if (desired < sumCurrentAvailable)
                         somethingHasAMaximumSize = true;
                     newSizes[i] = -1.0;
                 }
             }
             bool keepGoing = somethingHasAMaximumSize;
             while (keepGoing) {
                 keepGoing = false;
                 for (int i = 0; i < n; ++i) {
                     if (newSizes[i] >= 0.0)
                         continue;
                     qreal maxBoxSize;
                     if (isLargerThanMaximum)
                         maxBoxSize = rowInfo.boxes.value(start + i).q_maximumSize;
                     else
                         maxBoxSize = boxes.at(start + i).q_maximumSize;
                     qreal avail = sumCurrentAvailable * factors[i] / sumFactors;
                     if (sizes[i] + avail >= maxBoxSize) {
                         newSizes[i] = maxBoxSize;
                         sumCurrentAvailable -= maxBoxSize - sizes[i];
                         sumFactors -= factors[i];
                         keepGoing = (sumCurrentAvailable > 0.0);
                         if (!keepGoing)
                             break;
                     }
                 }
             }
             for (int i = 0; i < n; ++i) {
                 if (newSizes[i] < 0.0) {
                     qreal delta = (sumFactors == 0.0) ? qreal(0.0)
                                                       : sumCurrentAvailable * factors[i] / sumFactors;
                     newSizes[i] = sizes[i] + delta;
                 }
             }
         }
     }
     if (sumAvailable > 0) {
         qreal offset = 0;
         for (int i = 0; i < n; ++i) {
             qreal delta = newSizes[i] - sizes[i];
             positions[i] += offset;
             sizes[i] += delta;
             offset += delta;
         }
 #if 0 // some "pixel allocation"
         int surplus = targetSize - (positions[n - 1] + sizes[n - 1]);
         Q_ASSERT(surplus >= 0 && surplus <= n);
         int prevSurplus = -1;
         while (surplus > 0 && surplus != prevSurplus) {
             prevSurplus = surplus;
             int offset = 0;
             for (int i = 0; i < n; ++i) {
                 const QGridLayoutBox &box = boxes.at(start + i);
                 int delta = (!ignore.testBit(start + i) && surplus > 0
                              && factors[i] > 0 && sizes[i] < box.q_maximumSize)
                     ? 1 : 0;
                 positions[i] += offset;
                 sizes[i] += delta;
                 offset += delta;
                 surplus -= delta;
             }
         }
         Q_ASSERT(surplus == 0);
 #endif
     }
     if (descents) {
         for (int i = 0; i < n; ++i) {
             if (ignore.testBit(start + i))
                 continue;
             const QGridLayoutBox &box = boxes.at(start + i);
             descents[i] = fixedDescent(box.q_minimumDescent, box.q_minimumAscent, sizes[i]);
         }
     }
 }
distributeMultiCells()
void QGridLayoutRowData::distributeMultiCells (const QGridLayoutRowInfo & rowInfo)
Definition at line 169 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::ensureColumnAndRowData().
 {
     MultiCellMap::const_iterator i = multiCellMap.constBegin();
     for (; i != multiCellMap.constEnd(); ++i) {
         int start = i.key().first;
         int span = i.key().second;
         int end = start + span;
         const QGridLayoutBox &box = i.value().q_box;
         int stretch = i.value().q_stretch;
         QGridLayoutBox totalBox = this->totalBox(start, end);
         QVarLengthArray<QGridLayoutBox> extras(span);
         QVarLengthArray<qreal> dummy(span);
         QVarLengthArray<qreal> newSizes(span);
         for (int j = 0; j < NSizes; ++j) {
             qreal extra = compare(box, totalBox, j);
             if (extra > 0.0) {
                 calculateGeometries(start, end, box.q_sizes(j), dummy.data(), newSizes.data(),
                                     0, totalBox, rowInfo);
                 for (int k = 0; k < span; ++k)
                     extras[k].q_sizes(j) = newSizes[k];
             }
         }
         for (int k = 0; k < span; ++k) {
             boxes[start + k].combine(extras[k]);
             if (stretch != 0)
                 stretches[start + k] = qMax(stretches[start + k], stretch);
         }
     }
     multiCellMap.clear();
 }
dump()
void QGridLayoutRowData::dump (int indent = 0) const
Definition at line 466 of file qgridlayoutengine.cpp.
 {
     qDebug("%*sData", indent, "");
     for (int i = 0; i < ignore.count(); ++i) {
         qDebug("%*s Row %d (stretch %d, spacing %g)", indent, "", i, stretches.at(i),
                spacings.at(i));
         if (ignore.testBit(i))
             qDebug("%*s  Ignored", indent, "");
         boxes.at(i).dump(indent + 2);
     }
     MultiCellMap::const_iterator it = multiCellMap.constBegin();
     while (it != multiCellMap.constEnd()) {
         qDebug("%*s Multi-cell entry <%d, %d> (stretch %d)", indent, "", it.key().first,
                it.key().second, it.value().q_stretch);
         it.value().q_box.dump(indent + 2);
     }
 }
reset()
void QGridLayoutRowData::reset (int count)
Definition at line 159 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::ensureColumnAndRowData().
 {
     ignore.fill(false, count);
     boxes.fill(QGridLayoutBox(), count);
     multiCellMap.clear();
     stretches.fill(0, count);
     spacings.fill(0.0, count);
     hasIgnoreFlag = false;
 }
stealBox()
void QGridLayoutRowData::stealBox (int start, int end, int which, qreal * positions, qreal * sizes)
Definition at line 444 of file qgridlayoutengine.cpp.
 {
     qreal offset = 0.0;
     qreal nextSpacing = 0.0;
     for (int i = start; i < end; ++i) {
         qreal avail = 0.0;
         if (!ignore.testBit(i)) {
             const QGridLayoutBox &box = boxes.at(i);
             avail = box.q_sizes(which);
             offset += nextSpacing;
             nextSpacing = spacings.at(i);
         }
         *positions++ = offset;
         *sizes++ = avail;
         offset += avail;
     }
 }
totalBox()
QGridLayoutBox QGridLayoutRowData::totalBox (int start, int end) const
Definition at line 428 of file qgridlayoutengine.cpp.
Referenced by QGridLayoutEngine::ensureColumnAndRowData().
 {
     QGridLayoutBox result;
     if (start < end) {
         result.q_maximumSize = 0.0;
         qreal nextSpacing = 0.0;
         for (int i = start; i < end; ++i) {
             if (ignore.testBit(i))
                 continue;
             result.add(boxes.at(i), stretches.at(i), nextSpacing);
             nextSpacing = spacings.at(i);
         }
     }
     return result;
 }
Properties
boxes
QVector<QGridLayoutBox> QGridLayoutRowData::boxes
Definition at line 245 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
hasIgnoreFlag
bool QGridLayoutRowData::hasIgnoreFlag
Definition at line 249 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
ignore
QBitArray QGridLayoutRowData::ignore
Definition at line 244 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
multiCellMap
MultiCellMap QGridLayoutRowData::multiCellMap
Definition at line 246 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
spacings
QVector<qreal> QGridLayoutRowData::spacings
Definition at line 248 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
stretches
QVector<int> QGridLayoutRowData::stretches
Definition at line 247 of file qgridlayoutengine_p.h.
Referenced by QGridLayoutEngine::fillRowData().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgridlayoutengine_p.h
/src/gui/graphicsview/qgridlayoutengine.cpp