Qt 4.8: QDeclarativeParentChange Class Reference
QDeclarativeParentChange Class Reference
#include <qdeclarativestateoperations_p.h>
Public Functions
virtual ActionList actions ()
virtual void execute (Reason reason=ActualChange)
QDeclarativeScriptString height () const
bool heightIsSet () const
virtual bool isReversable ()
QDeclarativeItem * object () const
QDeclarativeItem * originalParent () const
virtual bool override (QDeclarativeActionEvent *other)
QDeclarativeItem * parent () const
QDeclarativeParentChange (QObject *parent=0)
virtual void reverse (Reason reason=ActualChange)
virtual void rewind ()
QDeclarativeScriptString rotation () const
bool rotationIsSet () const
virtual void saveCurrentValues ()
virtual void saveOriginals ()
QDeclarativeScriptString scale () const
bool scaleIsSet () const
void setHeight (QDeclarativeScriptString height)
void setObject (QDeclarativeItem *)
void setParent (QDeclarativeItem *)
void setRotation (QDeclarativeScriptString rotation)
void setScale (QDeclarativeScriptString scale)
void setWidth (QDeclarativeScriptString width)
void setX (QDeclarativeScriptString x)
void setY (QDeclarativeScriptString y)
virtual QString typeName () const
QDeclarativeScriptString width () const
bool widthIsSet () const
QDeclarativeScriptString x () const
bool xIsSet () const
QDeclarativeScriptString y () const
bool yIsSet () const
~QDeclarativeParentChange ()
Public Functions inherited from QDeclarativeStateOperation
QDeclarativeStateOperation (QObject *parent=0)
void setState (QDeclarativeState *state)
QDeclarativeState * state () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeActionEvent
virtual bool changesBindings ()
virtual void clearBindings ()
virtual void copyOriginals (QDeclarativeActionEvent *)
virtual bool isRewindable ()
virtual bool needsCopy ()
virtual void saveTargetValues ()
virtual ~QDeclarativeActionEvent ()
Properties
QDeclarativeScriptString height
QDeclarativeItem * parent
QDeclarativeScriptString rotation
QDeclarativeScriptString scale
QDeclarativeItem * target
QDeclarativeScriptString width
QDeclarativeScriptString x
QDeclarativeScriptString y
Additional Inherited Members
Public Types inherited from QDeclarativeStateOperation
typedef QList< QDeclarativeAction > ActionList
Public Types inherited from QDeclarativeActionEvent
enum Reason { ActualChange, FastForward }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QDeclarativeStateOperation
QDeclarativeStateOperation (QObjectPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qdeclarativestateoperations_p.h.
Constructors and Destructors
QDeclarativeParentChange()
QDeclarativeParentChange::QDeclarativeParentChange (QObject * parent = 0)
Definition at line 208 of file qdeclarativestateoperations.cpp.
     : QDeclarativeStateOperation(*(new QDeclarativeParentChangePrivate), parent)
 {
 }
~QDeclarativeParentChange()
QDeclarativeParentChange::~QDeclarativeParentChange ()
Definition at line 213 of file qdeclarativestateoperations.cpp.
 {
 }
Functions
actions()
QDeclarativeStateOperation::ActionList QDeclarativeParentChange::actions () virtual
Reimplemented from QDeclarativeStateOperation.
Definition at line 397 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     if (!d->target || !d->parent)
         return ActionList();
     ActionList actions;
     QDeclarativeAction a;
     a.event = this;
     actions << a;
     QDeclarativeContext *ctxt = qmlContext(this);
     if (d->xString.isValid()) {
         if (d->x.isValid()) {
             QDeclarativeAction xa(d->target, QLatin1String("x"), ctxt, d->x.value);
             actions << xa;
         } else {
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(d->xString.value.script(), d->target, ctxt);
             newBinding->setTarget(QDeclarativeProperty(d->target, QLatin1String("x"), ctxt));
             QDeclarativeAction xa;
             xa.property = newBinding->property();
             xa.toBinding = newBinding;
             xa.fromValue = xa.property.read();
             xa.deletableToBinding = true;
             actions << xa;
         }
     }
     if (d->yString.isValid()) {
         if (d->y.isValid()) {
             QDeclarativeAction ya(d->target, QLatin1String("y"), ctxt, d->y.value);
             actions << ya;
         } else {
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(d->yString.value.script(), d->target, ctxt);
             newBinding->setTarget(QDeclarativeProperty(d->target, QLatin1String("y"), ctxt));
             QDeclarativeAction ya;
             ya.property = newBinding->property();
             ya.toBinding = newBinding;
             ya.fromValue = ya.property.read();
             ya.deletableToBinding = true;
             actions << ya;
         }
     }
     if (d->scaleString.isValid()) {
         if (d->scale.isValid()) {
             QDeclarativeAction sa(d->target, QLatin1String("scale"), ctxt, d->scale.value);
             actions << sa;
         } else {
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(d->scaleString.value.script(), d->target, ctxt);
             newBinding->setTarget(QDeclarativeProperty(d->target, QLatin1String("scale"), ctxt));
             QDeclarativeAction sa;
             sa.property = newBinding->property();
             sa.toBinding = newBinding;
             sa.fromValue = sa.property.read();
             sa.deletableToBinding = true;
             actions << sa;
         }
     }
     if (d->rotationString.isValid()) {
         if (d->rotation.isValid()) {
             QDeclarativeAction ra(d->target, QLatin1String("rotation"), ctxt, d->rotation.value);
             actions << ra;
         } else {
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(d->rotationString.value.script(), d->target, ctxt);
             newBinding->setTarget(QDeclarativeProperty(d->target, QLatin1String("rotation"), ctxt));
             QDeclarativeAction ra;
             ra.property = newBinding->property();
             ra.toBinding = newBinding;
             ra.fromValue = ra.property.read();
             ra.deletableToBinding = true;
             actions << ra;
         }
     }
     if (d->widthString.isValid()) {
         if (d->width.isValid()) {
             QDeclarativeAction wa(d->target, QLatin1String("width"), ctxt, d->width.value);
             actions << wa;
         } else {
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(d->widthString.value.script(), d->target, ctxt);
             newBinding->setTarget(QDeclarativeProperty(d->target, QLatin1String("width"), ctxt));
             QDeclarativeAction wa;
             wa.property = newBinding->property();
             wa.toBinding = newBinding;
             wa.fromValue = wa.property.read();
             wa.deletableToBinding = true;
             actions << wa;
         }
     }
     if (d->heightString.isValid()) {
         if (d->height.isValid()) {
             QDeclarativeAction ha(d->target, QLatin1String("height"), ctxt, d->height.value);
             actions << ha;
         } else {
             QDeclarativeBinding *newBinding = new QDeclarativeBinding(d->heightString.value.script(), d->target, ctxt);
             newBinding->setTarget(QDeclarativeProperty(d->target, QLatin1String("height"), ctxt));
             QDeclarativeAction ha;
             ha.property = newBinding->property();
             ha.toBinding = newBinding;
             ha.fromValue = ha.property.read();
             ha.deletableToBinding = true;
             actions << ha;
         }
     }
     return actions;
 }
execute()
void QDeclarativeParentChange::execute (Reason reason = ActualChange) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 540 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->doChange(d->parent);
 }
height()
QDeclarativeScriptString QDeclarativeParentChange::height () const
Referenced by setHeight(), and widthIsSet().
heightIsSet()
bool QDeclarativeParentChange::heightIsSet () const
Definition at line 310 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->heightString.isValid();
 }
isReversable()
bool QDeclarativeParentChange::isReversable () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 546 of file qdeclarativestateoperations.cpp.
 {
     return true;
 }
object()
QDeclarativeItem * QDeclarativeParentChange::object () const
Definition at line 365 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->target;
 }
originalParent()
QDeclarativeItem * QDeclarativeParentChange::originalParent () const
Definition at line 354 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->origParent;
 }
override()
bool QDeclarativeParentChange::override (QDeclarativeActionEvent * other) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 562 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     if (other->typeName() != QLatin1String("ParentChange"))
         return false;
     if (QDeclarativeParentChange *otherPC = static_cast<QDeclarativeParentChange*>(other))
         return (d->target == otherPC->object());
     return false;
 }
parent()
QDeclarativeItem* QDeclarativeParentChange::parent () const
Referenced by setObject(), and setParent().
reverse()
void QDeclarativeParentChange::reverse (Reason reason = ActualChange) virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 551 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->doChange(d->origParent, d->origStackBefore);
 }
rewind()
void QDeclarativeParentChange::rewind () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 601 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->doChange(d->rewindParent, d->rewindStackBefore);
 }
rotation()
QDeclarativeScriptString QDeclarativeParentChange::rotation () const
Referenced by scaleIsSet(), and setRotation().
rotationIsSet()
bool QDeclarativeParentChange::rotationIsSet () const
Definition at line 348 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->rotationString.isValid();
 }
saveCurrentValues()
void QDeclarativeParentChange::saveCurrentValues () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 572 of file qdeclarativestateoperations.cpp.
Referenced by saveOriginals().
 {
     Q_D(QDeclarativeParentChange);
     if (!d->target) {
         d->rewindParent = 0;
         d->rewindStackBefore = 0;
         return;
     }
     d->rewindParent = d->target->parentItem();
     d->rewindStackBefore = 0;
     if (!d->rewindParent)
         return;
     //try to determine the item's original stack position so we can restore it
     int siblingIndex = ((AccessibleFxItem*)d->target)->siblingIndex() + 1;
     QList<QGraphicsItem*> children = d->rewindParent->childItems();
     for (int i = 0; i < children.count(); ++i) {
         QDeclarativeItem *child = qobject_cast<QDeclarativeItem*>(children.at(i));
         if (!child)
             continue;
         if (((AccessibleFxItem*)child)->siblingIndex() == siblingIndex) {
             d->rewindStackBefore = child;
             break;
         }
     }
 }
saveOriginals()
void QDeclarativeParentChange::saveOriginals () virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 521 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     saveCurrentValues();
     d->origParent = d->rewindParent;
     d->origStackBefore = d->rewindStackBefore;
 }
scale()
QDeclarativeScriptString QDeclarativeParentChange::scale () const
Referenced by heightIsSet(), and setScale().
scaleIsSet()
bool QDeclarativeParentChange::scaleIsSet () const
Definition at line 329 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->scaleString.isValid();
 }
setHeight()
void QDeclarativeParentChange::setHeight (QDeclarativeScriptString height)
Definition at line 303 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->heightString = height;
     tryReal(d->height, height.script());
 }
setObject()
void QDeclarativeParentChange::setObject (QDeclarativeItem * target)
Definition at line 371 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(QDeclarativeParentChange);
     d->target = target;
 }
setParent()
void QDeclarativeParentChange::setParent (QDeclarativeItem * parent)
Definition at line 391 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(QDeclarativeParentChange);
     d->parent = parent;
 }
setRotation()
void QDeclarativeParentChange::setRotation (QDeclarativeScriptString rotation)
Definition at line 341 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->rotationString = rotation;
     tryReal(d->rotation, rotation.script());
 }
setScale()
void QDeclarativeParentChange::setScale (QDeclarativeScriptString scale)
Definition at line 322 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->scaleString = scale;
     tryReal(d->scale, scale.script());
 }
setWidth()
void QDeclarativeParentChange::setWidth (QDeclarativeScriptString width)
Definition at line 284 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->widthString = width;
     tryReal(d->width, width.script());
 }
setX()
void QDeclarativeParentChange::setX (QDeclarativeScriptString x)
Definition at line 246 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->xString = x;
     tryReal(d->x, x.script());
 }
setY()
void QDeclarativeParentChange::setY (QDeclarativeScriptString y)
Definition at line 265 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeParentChange);
     d->yString = y;
     tryReal(d->y, y.script());
 }
typeName()
QString QDeclarativeParentChange::typeName () const virtual
Reimplemented from QDeclarativeActionEvent.
Definition at line 557 of file qdeclarativestateoperations.cpp.
 {
     return QLatin1String("ParentChange");
 }
width()
QDeclarativeScriptString QDeclarativeParentChange::width () const
Referenced by setWidth(), and yIsSet().
widthIsSet()
bool QDeclarativeParentChange::widthIsSet () const
Definition at line 291 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->widthString.isValid();
 }
x()
QDeclarativeScriptString QDeclarativeParentChange::x () const
Referenced by setX(), and ~QDeclarativeParentChange().
xIsSet()
bool QDeclarativeParentChange::xIsSet () const
Definition at line 253 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->xString.isValid();
 }
y()
QDeclarativeScriptString QDeclarativeParentChange::y () const
Referenced by setY(), and xIsSet().
yIsSet()
bool QDeclarativeParentChange::yIsSet () const
Definition at line 272 of file qdeclarativestateoperations.cpp.
Referenced by QDeclarativeParentAnimation::transition().
 {
     Q_D(const QDeclarativeParentChange);
     return d->yString.isValid();
 }
Properties
height
QDeclarativeScriptString QDeclarativeParentChange::height private
Definition at line 76 of file qdeclarativestateoperations_p.h.
parent
QDeclarativeItem * QDeclarativeParentChange::parent private
Definition at line 72 of file qdeclarativestateoperations_p.h.
Referenced by QDeclarativeParentAnimation::transition().
rotation
QDeclarativeScriptString QDeclarativeParentChange::rotation private
Definition at line 78 of file qdeclarativestateoperations_p.h.
scale
QDeclarativeScriptString QDeclarativeParentChange::scale private
Definition at line 77 of file qdeclarativestateoperations_p.h.
target
QDeclarativeItem* QDeclarativeParentChange::target private
Definition at line 71 of file qdeclarativestateoperations_p.h.
Referenced by setObject().
width
QDeclarativeScriptString QDeclarativeParentChange::width private
Definition at line 75 of file qdeclarativestateoperations_p.h.
x
QDeclarativeScriptString QDeclarativeParentChange::x private
Definition at line 73 of file qdeclarativestateoperations_p.h.
y
QDeclarativeScriptString QDeclarativeParentChange::y private
Definition at line 74 of file qdeclarativestateoperations_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestateoperations_p.h
/src/declarative/util/qdeclarativestateoperations.cpp