Qt 4.8: QBBScreen Class Reference
QBBScreen Class Reference
#include <qbbscreen.h>
Public Slots
void activateWindowGroup (const QByteArray &id)
void deactivateWindowGroup (const QByteArray &id)
void newWindowCreated (screen_window_t window)
void setRotation (int rotation)
void windowClosed (screen_window_t window)
void windowGroupStateChanged (const QByteArray &id, Qt::WindowState state)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void addWindow (QBBWindow *child)
void adjustOrientation ()
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
QPlatformCursor * cursor () const
virtual int depth () const
Reimplement in subclass to return current depth of the screen.
void ensureDisplayCreated ()
QBBWindow * findWindow (screen_window_t windowHandle)
virtual QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
virtual QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
void lowerWindow (QBBWindow *window)
screen_context_t nativeContext () const
screen_display_t nativeDisplay () const
int nativeFormat () const
void onWindowPost (QBBWindow *window)
virtual QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
QBBScreen (screen_context_t context, screen_display_t display, int screenIndex)
void raiseWindow (QBBWindow *window)
void removeWindow (QBBWindow *child)
QSharedPointer< QBBRootWindow > rootWindow () const
int rotation () const
void updateHierarchy ()
const char * windowGroupName () const
virtual ~QBBScreen ()
Public Functions inherited from QPlatformScreen
virtual void setDirty (const QRect &)
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void keyboardHeightChanged (int height)
Private Functions
void addOverlayWindow (screen_window_t window)
bool isPrimaryDisplay ()
void removeOverlayWindow (screen_window_t window)
void resizeNativeWidgetWindow (QBBWindow *w, const QRect &previousScreenGeometry) const
void resizeTopLevelWindow (QBBWindow *w, const QRect &previousScreenGeometry) const
Resize the given window to fit the screen geometry.
void resizeWindows (const QRect &previousScreenGeometry)
Adjust windows to the new screen geometry.
QWidget * topMostChildWindow () const
Properties
QList< QBBWindow * > mChildren
screen_context_t mContext
QRect mCurrentGeometry
QSize mCurrentPhysicalSize
int mCurrentRotation
QPlatformCursor * mCursor
screen_display_t mDisplay
int mKeyboardHeight
QList< screen_window_t > mOverlays
bool mPosted
bool mPrimaryDisplay
QSharedPointer< QBBRootWindow > mRootWindow
int mScreenIndex
QRect mStartGeometry
QSize mStartPhysicalSize
int mStartRotation
bool mUsingOpenGL
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 56 of file qbbscreen.h.
Constructors and Destructors
QBBScreen()
QBBScreen::QBBScreen (screen_context_t context, screen_display_t display, int screenIndex)
Definition at line 108 of file qbbscreen.cpp.
     : mContext(context),
       mDisplay(display),
       mPosted(false),
       mUsingOpenGL(false),
       mPrimaryDisplay(screenIndex == 0),
       mKeyboardHeight(0),
       mScreenIndex(screenIndex),
       mCursor(new QBBCursor(this))
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::QBBScreen";
 #endif
     // cache initial orientation of this display
     // TODO: use ORIENTATION environment variable?
     errno = 0;
     int result = screen_get_display_property_iv(mDisplay, SCREEN_PROPERTY_ROTATION, &mStartRotation);
     if (result != 0) {
         qFatal("QBBScreen: failed to query display rotation, errno=%d", errno);
     }
     mCurrentRotation = mStartRotation;
     // cache size of this display in pixels
     // TODO: use WIDTH and HEIGHT environment variables?
     errno = 0;
     int val[2];
     result = screen_get_display_property_iv(mDisplay, SCREEN_PROPERTY_SIZE, val);
     if (result != 0) {
         qFatal("QBBScreen: failed to query display size, errno=%d", errno);
     }
     mCurrentGeometry = mStartGeometry = QRect(0, 0, val[0], val[1]);
     // Cache size of this display in millimeters
     mStartPhysicalSize = determineScreenSize(mDisplay, mPrimaryDisplay);
     // swap physical dimensions when rotated orthogonally
     if (mStartRotation == 90 || mStartRotation == 270)
         mStartPhysicalSize.transpose();
     mCurrentPhysicalSize = mStartPhysicalSize;
     // We only create the root window if we are not the primary display.
     if (mPrimaryDisplay)
         mRootWindow = QSharedPointer<QBBRootWindow>(new QBBRootWindow(this));
 }
~QBBScreen()
QBBScreen::~QBBScreen () virtual
Definition at line 157 of file qbbscreen.cpp.
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::~QBBScreen";
 #endif
 }
Functions
activateWindowGroup
void QBBScreen::activateWindowGroup (const QByteArray & id) slot
Definition at line 553 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     if (!rootWindow() || id != rootWindow()->groupName())
         return;
     QWidget * const window = topMostChildWindow();
     if (!window)
         return;
     QWindowSystemInterface::handleWindowActivated(window);
 }
addOverlayWindow()
void QBBScreen::addOverlayWindow (screen_window_t window) private
Definition at line 523 of file qbbscreen.cpp.
Referenced by newWindowCreated(), and rootWindow().
 {
     mOverlays.append(window);
     updateHierarchy();
 }
addWindow()
void QBBScreen::addWindow (QBBWindow * child)
Definition at line 400 of file qbbscreen.cpp.
Referenced by QBBWindow::setParent(), QBBWindow::setScreen(), and windowGroupName().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::addWindow=" << window;
 #endif
     if (mChildren.contains(window))
         return;
     // Ensure that the desktop window is at the bottom of the zorder.
     // If we do not do this then we may end up activating the desktop
     // when the navigator service gets an event that our window group
     // has been activated (see QBBScreen::activateWindowGroup()).
     // Such a situation would strangely break focus handling due to the
     // invisible desktop widget window being layered on top of normal
     // windows
     if (window->widget()->windowType() == Qt::Desktop)
         mChildren.push_front(window);
     else
         mChildren.push_back(window);
     updateHierarchy();
 }
adjustOrientation()
void QBBScreen::adjustOrientation ()
Definition at line 496 of file qbbscreen.cpp.
Referenced by QBBIntegration::createDisplay(), and windowGroupName().
 {
     if (!mPrimaryDisplay)
         return;
     bool ok = false;
     const int rotation = qgetenv("ORIENTATION").toInt(&ok);
     if (ok)
         setRotation(rotation);
 }
availableGeometry()
QRect QBBScreen::availableGeometry () const virtual
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
Reimplemented from QPlatformScreen.
Definition at line 209 of file qbbscreen.cpp.
Referenced by geometry().
 {
     // available geometry = total geometry - keyboard
     return QRect(mCurrentGeometry.x(), mCurrentGeometry.y(),
                  mCurrentGeometry.width(), mCurrentGeometry.height() - mKeyboardHeight);
 }
cursor()
QPlatformCursor * QBBScreen::cursor () const
Definition at line 508 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
     return mCursor;
 }
deactivateWindowGroup
void QBBScreen::deactivateWindowGroup (const QByteArray & id) slot
Definition at line 570 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     if (!rootWindow() || id != rootWindow()->groupName())
         return;
     QWindowSystemInterface::handleWindowActivated(0);
 }
depth()
int QBBScreen::depth () const virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 216 of file qbbscreen.cpp.
Referenced by format(), geometry(), nativeFormat(), and QBBGLContext::QBBGLContext().
 {
     return defaultDepth();
 }
ensureDisplayCreated()
void QBBScreen::ensureDisplayCreated ()
Definition at line 178 of file qbbscreen.cpp.
Referenced by QBBWindow::setScreen(), and windowGroupName().
 {
     if (!mRootWindow)
         mRootWindow = QSharedPointer<QBBRootWindow>(new QBBRootWindow(this));
 }
findWindow()
QBBWindow * QBBScreen::findWindow (screen_window_t windowHandle)
Definition at line 389 of file qbbscreen.cpp.
Referenced by newWindowCreated(), and windowGroupName().
 {
     Q_FOREACH (QBBWindow *window, mChildren) {
         QBBWindow * const result = window->findWindow(windowHandle);
         if (result)
             return result;
     }
     return 0;
 }
format()
virtual QImage::Format QBBScreen::format () const inline virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 66 of file qbbscreen.h.
 { return (depth() == 32) ? QImage::Format_RGB32 : QImage::Format_RGB16; }
geometry()
virtual QRect QBBScreen::geometry () const inline virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 63 of file qbbscreen.h.
Referenced by QBBRootWindow::QBBRootWindow(), resizeNativeWidgetWindow(), resizeTopLevelWindow(), and setRotation().
 { return mCurrentGeometry; }
isPrimaryDisplay()
bool QBBScreen::isPrimaryDisplay () inline private
Definition at line 134 of file qbbscreen.h.
 { return mPrimaryDisplay; }
keyboardHeightChanged
void QBBScreen::keyboardHeightChanged (int height) private slot
Definition at line 513 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
     if (height == mKeyboardHeight)
         return;
     mKeyboardHeight = height;
     QWindowSystemInterface::handleScreenAvailableGeometryChange(mScreenIndex);
 }
lowerWindow()
void QBBScreen::lowerWindow (QBBWindow * window)
Definition at line 445 of file qbbscreen.cpp.
Referenced by QBBWindow::lower(), and windowGroupName().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::lower window=" << window;
 #endif
     removeWindow(window);
     mChildren.push_front(window);
     updateHierarchy();
 }
nativeContext()
screen_context_t QBBScreen::nativeContext () const inline
Definition at line 73 of file qbbscreen.h.
Referenced by QBBRootWindow::flush(), QBBRootWindow::QBBRootWindow(), QBBBpsEventFilter::registerForScreenEvents(), and QBBBpsEventFilter::unregisterForScreenEvents().
 { return mContext; }
nativeDisplay()
screen_display_t QBBScreen::nativeDisplay () const inline
Definition at line 72 of file qbbscreen.h.
Referenced by newWindowCreated(), QBBRootWindow::QBBRootWindow(), QBBBpsEventFilter::registerForScreenEvents(), QBBIntegration::screenForNative(), QBBIntegration::screenForWindow(), and QBBWindow::setScreen().
 { return mDisplay; }
nativeFormat()
int QBBScreen::nativeFormat () const inline
Definition at line 71 of file qbbscreen.h.
Referenced by QBBRootWindow::QBBRootWindow(), and QBBWindow::setBufferSize().
 { return (depth() == 32) ? SCREEN_FORMAT_RGBA8888 : SCREEN_FORMAT_RGB565; }
newWindowCreated
void QBBScreen::newWindowCreated (screen_window_t window) slot
Definition at line 184 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
     Q_ASSERT(thread() == QThread::currentThread());
     screen_display_t display = 0;
     if (screen_get_window_property_pv(window, SCREEN_PROPERTY_DISPLAY, (void**)&display) != 0) {
         qWarning("QBBScreen: Failed to get screen for window, errno=%d", errno);
         return;
     }
     if (display == nativeDisplay()) {
         // A window was created on this screen. If we don't know about this window yet, it means
         // it was not created by Qt, but by some foreign library like the multimedia renderer, which
         // creates an overlay window when playing a video.
         // Treat all foreign windows as overlays here.
         if (!findWindow(window))
             addOverlayWindow(window);
     }
 }
onWindowPost()
void QBBScreen::onWindowPost (QBBWindow * window)
Definition at line 483 of file qbbscreen.cpp.
Referenced by QBBWindow::post(), and windowGroupName().
 {
     Q_UNUSED(window)
     // post app window (so navigator will show it) after first child window
     // has posted; this only needs to happen once as the app window's content
     // never changes
     if (!mPosted && mRootWindow) {
         mRootWindow->post();
         mPosted = true;
     }
 }
physicalSize()
virtual QSize QBBScreen::physicalSize () const inline virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented from QPlatformScreen.
Definition at line 67 of file qbbscreen.h.
 { return mCurrentPhysicalSize; }
raiseWindow()
void QBBScreen::raiseWindow (QBBWindow * window)
Definition at line 434 of file qbbscreen.cpp.
Referenced by QBBWindow::raise(), and windowGroupName().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::raise window=" << window;
 #endif
     removeWindow(window);
     mChildren.push_back(window);
     updateHierarchy();
 }
removeOverlayWindow()
void QBBScreen::removeOverlayWindow (screen_window_t window) private
Definition at line 529 of file qbbscreen.cpp.
Referenced by rootWindow(), and windowClosed().
 {
     const int numOverlaysRemoved = mOverlays.removeAll(window);
     if (numOverlaysRemoved > 0)
         updateHierarchy();
 }
removeWindow()
void QBBScreen::removeWindow (QBBWindow * child)
Definition at line 423 of file qbbscreen.cpp.
Referenced by lowerWindow(), raiseWindow(), QBBWindow::removeFromParent(), QBBWindow::setScreen(), and windowGroupName().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::removeWindow=" << window;
 #endif
     const int numWindowsRemoved = mChildren.removeAll(window);
     if (numWindowsRemoved > 0)
         updateHierarchy();
 }
resizeNativeWidgetWindow()
void QBBScreen::resizeNativeWidgetWindow (QBBWindow * w, const QRect & previousScreenGeometry) const private
Definition at line 288 of file qbbscreen.cpp.
Referenced by resizeWindows(), and rootWindow().
 {
     const qreal relativeX = static_cast<qreal>(w->geometry().topLeft().x()) / previousScreenGeometry.width();
     const qreal relativeY = static_cast<qreal>(w->geometry().topLeft().y()) / previousScreenGeometry.height();
     const qreal relativeWidth = static_cast<qreal>(w->geometry().width()) / previousScreenGeometry.width();
     const qreal relativeHeight = static_cast<qreal>(w->geometry().height()) / previousScreenGeometry.height();
     const QRect windowGeometry(relativeX * geometry().width(), relativeY * geometry().height(),
             relativeWidth * geometry().width(), relativeHeight * geometry().height());
     w->widget()->setGeometry(windowGeometry);
 }
resizeTopLevelWindow()
void QBBScreen::resizeTopLevelWindow (QBBWindow * w, const QRect & previousScreenGeometry) const private
Resize the given window to fit the screen geometry.
Definition at line 304 of file qbbscreen.cpp.
Referenced by resizeWindows(), and rootWindow().
 {
     QRect windowGeometry = w->geometry();
     const qreal relativeCenterX = static_cast<qreal>(w->geometry().center().x()) / previousScreenGeometry.width();
     const qreal relativeCenterY = static_cast<qreal>(w->geometry().center().y()) / previousScreenGeometry.height();
     const QPoint newCenter(relativeCenterX * geometry().width(), relativeCenterY * geometry().height());
     windowGeometry.moveCenter(newCenter);
     // adjust center position in case the window
     // is clipped
     if (!geometry().contains(windowGeometry)) {
         const int x1 = windowGeometry.x();
         const int y1 = windowGeometry.y();
         const int x2 = x1 + windowGeometry.width();
         const int y2 = y1 + windowGeometry.height();
         if (x1 < 0) {
             const int centerX = qMin(qAbs(x1) + windowGeometry.center().x(),
                                         geometry().center().x());
             windowGeometry.moveCenter(QPoint(centerX, windowGeometry.center().y()));
         }
         if (y1 < 0) {
             const int centerY = qMin(qAbs(y1) + windowGeometry.center().y(),
                                         geometry().center().y());
             windowGeometry.moveCenter(QPoint(windowGeometry.center().x(), centerY));
         }
         if (x2 > geometry().width()) {
             const int centerX = qMax(windowGeometry.center().x() - (x2 - geometry().width()),
                                         geometry().center().x());
             windowGeometry.moveCenter(QPoint(centerX, windowGeometry.center().y()));
         }
         if (y2 > geometry().height()) {
             const int centerY = qMax(windowGeometry.center().y() - (y2 - geometry().height()),
                                         geometry().center().y());
             windowGeometry.moveCenter(QPoint(windowGeometry.center().x(), centerY));
         }
     }
     // at this point, if the window is still clipped,
     // it means that it's too big to fit on the screen,
     // so we need to proportionally shrink it
     if (!geometry().contains(windowGeometry)) {
         QSize newSize = windowGeometry.size();
         newSize.scale(geometry().size(), Qt::KeepAspectRatio);
         windowGeometry.setSize(newSize);
         if (windowGeometry.x() < 0)
             windowGeometry.moveCenter(QPoint(geometry().center().x(), windowGeometry.center().y()));
         if (windowGeometry.y() < 0)
             windowGeometry.moveCenter(QPoint(windowGeometry.center().x(), geometry().center().y()));
     }
     w->widget()->setGeometry(windowGeometry);
 }
resizeWindows()
void QBBScreen::resizeWindows (const QRect & previousScreenGeometry) private
Adjust windows to the new screen geometry.
Definition at line 372 of file qbbscreen.cpp.
Referenced by rootWindow(), and setRotation().
 {
     Q_FOREACH (QBBWindow *w, mChildren) {
         if (w->widget()->windowState() & Qt::WindowFullScreen || w->widget()->windowState() & Qt::WindowMaximized)
             continue;
         if (w->widget()->parent()) {
             // This is a native (non-alien) widget window
             resizeNativeWidgetWindow(w, previousScreenGeometry);
         } else {
             // This is a toplevel window
             resizeTopLevelWindow(w, previousScreenGeometry);
         }
     }
 }
rootWindow()
QSharedPointer<QBBRootWindow> QBBScreen::rootWindow () const inline
Definition at line 89 of file qbbscreen.h.
Referenced by activateWindowGroup(), deactivateWindowGroup(), QBBNativeInterface::nativeResourceForWidget(), and windowGroupStateChanged().
 { return mRootWindow; }
rotation()
int QBBScreen::rotation () const inline
Definition at line 69 of file qbbscreen.h.
Referenced by adjustOrientation(), rootWindow(), and setRotation().
 { return mCurrentRotation; }
setRotation
void QBBScreen::setRotation (int rotation) slot
Definition at line 229 of file qbbscreen.cpp.
Referenced by adjustOrientation(), and rootWindow().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::setRotation, o=" << rotation;
 #endif
     // check if rotation changed
     if (mCurrentRotation != rotation) {
         // update rotation of root window
         if (mRootWindow)
             mRootWindow->setRotation(rotation);
         const QRect previousScreenGeometry = geometry();
         // swap dimensions if we've rotated 90 or 270 from initial orientation
         if (isOrthogonal(mStartRotation, rotation)) {
             mCurrentGeometry = QRect(0, 0, mStartGeometry.height(), mStartGeometry.width());
             mCurrentPhysicalSize = QSize(mStartPhysicalSize.height(), mStartPhysicalSize.width());
         } else {
             mCurrentGeometry = QRect(0, 0, mStartGeometry.width(), mStartGeometry.height());
             mCurrentPhysicalSize = mStartPhysicalSize;
         }
         // resize app window if we've rotated 90 or 270 from previous orientation
         if (isOrthogonal(mCurrentRotation, rotation)) {
 #if defined(QBBSCREEN_DEBUG)
             qDebug() << "QBBScreen::setRotation - resize, s=" << mCurrentGeometry.size();
 #endif
             if (mRootWindow)
                 mRootWindow->resize(mCurrentGeometry.size());
             if (mPrimaryDisplay)
                 resizeWindows(previousScreenGeometry);
         } else {
             // TODO: find one global place to flush display updates
 #if defined(QBBSCREEN_DEBUG)
             qDebug() << "QBBScreen::setRotation - flush";
 #endif
             // force immediate display update if no geometry changes required
             if (mRootWindow)
                 mRootWindow->flush();
         }
         // save new rotation
         mCurrentRotation = rotation;
         // TODO: check if other screens are supposed to rotate as well and/or whether this depends
         // on if clone mode is being used.
         // Rotating only the primary screen is what we had in the navigator event handler before refactoring
         if (mPrimaryDisplay)
             QWindowSystemInterface::handleScreenGeometryChange(mScreenIndex);
         // Flush everything, so that the windows rotations are applied properly.
         // Needed for non-maximized windows
         screen_flush_context(mContext, 0);
     }
 }
topMostChildWindow()
QWidget * QBBScreen::topMostChildWindow () const private
Definition at line 582 of file qbbscreen.cpp.
Referenced by activateWindowGroup(), rootWindow(), and windowGroupStateChanged().
 {
     if (!mChildren.isEmpty()) {
         // We're picking up the last window of the list here
         // because this list is ordered by stacking order.
         // Last window is effectively the one on top.
         return mChildren.last()->widget();
     }
     return 0;
 }
updateHierarchy()
void QBBScreen::updateHierarchy ()
Definition at line 456 of file qbbscreen.cpp.
Referenced by addOverlayWindow(), addWindow(), QBBWindow::lower(), lowerWindow(), QBBWindow::raise(), raiseWindow(), removeOverlayWindow(), removeWindow(), QBBWindow::setParent(), QBBWindow::setScreen(), windowGroupName(), and QBBWindow::~QBBWindow().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << "QBBScreen::updateHierarchy";
 #endif
     QList<QBBWindow*>::const_iterator it;
     int topZorder = 1; // root window is z-order 0, all "top" level windows are "above" it
     for (it = mChildren.constBegin(); it != mChildren.constEnd(); ++it) {
         (*it)->updateZorder(topZorder);
     }
     topZorder++;
     Q_FOREACH (screen_window_t overlay, mOverlays) {
         // Do nothing when this fails. This can happen if we have stale windows in mOverlays,
         // which in turn can happen because a window was removed but we didn't get a notification
         // yet.
         screen_set_window_property_iv(overlay, SCREEN_PROPERTY_ZORDER, &topZorder);
         topZorder++;
     }
     // After a hierarchy update, we need to force a flush on all screens.
     // Right now, all screens share a context.
     screen_flush_context( mContext, 0 );
 }
windowClosed
void QBBScreen::windowClosed (screen_window_t window) slot
Definition at line 203 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
     Q_ASSERT(thread() == QThread::currentThread());
     removeOverlayWindow(window);
 }
windowGroupName()
const char* QBBScreen::windowGroupName () const inline
Definition at line 74 of file qbbscreen.h.
Referenced by QBBWindow::setScreen().
 { return mRootWindow->groupName().constData(); }
windowGroupStateChanged
void QBBScreen::windowGroupStateChanged (const QByteArray & id, Qt::WindowState state) slot
Definition at line 536 of file qbbscreen.cpp.
Referenced by rootWindow().
 {
 #if defined(QBBSCREEN_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     if (!rootWindow() || id != rootWindow()->groupName())
         return;
     QWidget * const window = topMostChildWindow();
     if (!window)
         return;
     QWindowSystemInterface::handleWindowStateChanged(window, state);
 }
Properties
mChildren
QList<QBBWindow*> QBBScreen::mChildren private
Definition at line 128 of file qbbscreen.h.
Referenced by addWindow(), findWindow(), lowerWindow(), raiseWindow(), removeWindow(), resizeWindows(), topMostChildWindow(), and updateHierarchy().
mContext
screen_context_t QBBScreen::mContext private
Definition at line 113 of file qbbscreen.h.
Referenced by nativeContext(), setRotation(), and updateHierarchy().
mCurrentGeometry
QRect QBBScreen::mCurrentGeometry private
Definition at line 126 of file qbbscreen.h.
Referenced by availableGeometry(), geometry(), QBBScreen(), and setRotation().
mCurrentPhysicalSize
QSize QBBScreen::mCurrentPhysicalSize private
Definition at line 124 of file qbbscreen.h.
Referenced by physicalSize(), QBBScreen(), and setRotation().
mCurrentRotation
int QBBScreen::mCurrentRotation private
Definition at line 121 of file qbbscreen.h.
Referenced by QBBScreen(), rotation(), and setRotation().
mCursor
QPlatformCursor* QBBScreen::mCursor private
Definition at line 132 of file qbbscreen.h.
Referenced by cursor().
mDisplay
screen_display_t QBBScreen::mDisplay private
Definition at line 114 of file qbbscreen.h.
Referenced by nativeDisplay(), and QBBScreen().
mKeyboardHeight
int QBBScreen::mKeyboardHeight private
Definition at line 122 of file qbbscreen.h.
Referenced by availableGeometry(), and keyboardHeightChanged().
mOverlays
QList<screen_window_t> QBBScreen::mOverlays private
Definition at line 129 of file qbbscreen.h.
Referenced by addOverlayWindow(), removeOverlayWindow(), and updateHierarchy().
mPosted
bool QBBScreen::mPosted private
Definition at line 116 of file qbbscreen.h.
Referenced by onWindowPost().
mPrimaryDisplay
bool QBBScreen::mPrimaryDisplay private
Definition at line 118 of file qbbscreen.h.
Referenced by adjustOrientation(), isPrimaryDisplay(), QBBScreen(), and setRotation().
mRootWindow
QSharedPointer<QBBRootWindow> QBBScreen::mRootWindow private
Definition at line 115 of file qbbscreen.h.
Referenced by ensureDisplayCreated(), onWindowPost(), QBBScreen(), rootWindow(), setRotation(), and windowGroupName().
mScreenIndex
int QBBScreen::mScreenIndex private
Definition at line 130 of file qbbscreen.h.
Referenced by keyboardHeightChanged(), and setRotation().
mStartGeometry
QRect QBBScreen::mStartGeometry private
Definition at line 125 of file qbbscreen.h.
Referenced by QBBScreen(), and setRotation().
mStartPhysicalSize
QSize QBBScreen::mStartPhysicalSize private
Definition at line 123 of file qbbscreen.h.
Referenced by QBBScreen(), and setRotation().
mStartRotation
int QBBScreen::mStartRotation private
Definition at line 120 of file qbbscreen.h.
Referenced by QBBScreen(), and setRotation().
mUsingOpenGL
bool QBBScreen::mUsingOpenGL private
Definition at line 117 of file qbbscreen.h.
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbscreen.h
/src/plugins/platforms/blackberry/qbbscreen.cpp