Qt 4.8: QDeclarativeVisualDataModelPrivate Class Reference
QDeclarativeVisualDataModelPrivate Class Reference
Classes
class Cache
struct ObjectRef
Public Functions
void createMetaData ()
QDeclarativeVisualDataModelData * data (QObject *item)
void ensureRoles ()
int modelCount () const
QDeclarativeVisualDataModelPrivate (QDeclarativeContext *)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QDeclarativeVisualDataModelPrivate * get (QDeclarativeVisualDataModel *m)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QDeclarativeGuard< QAbstractItemModel > m_abstractItemModel
Cache m_cache
bool m_completePending: 1
QDeclarativeGuard< QDeclarativeContext > m_context
QDeclarativeComponent * m_delegate
VDMDelegateDataType * m_delegateDataType
bool m_delegateValidated: 1
QDeclarativeListAccessor * m_listAccessor
QDeclarativeGuard< QListModelInterface > m_listModelInterface
bool m_metaDataCacheable: 1
bool m_metaDataCreated: 1
int m_modelDataPropId
QVariant m_modelVariant
QHash< QObject *, QDeclarativePackage * > m_packaged
QString m_part
QDeclarativeVisualDataModelParts * m_parts
QHash< QByteArray, int > m_roleNames
QList< int > m_roles
QHash< int, int > m_roleToPropId
QModelIndex m_root
QDeclarativeGuard< QDeclarativeVisualDataModel > m_visualItemModel
QList< int > watchedRoleIds
QList< QByteArray > watchedRoles
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Friends
class QDeclarativeVisualDataModelData
class QDeclarativeVisualItemParts
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 275 of file qdeclarativevisualitemmodel.cpp.
Constructors and Destructors
QDeclarativeVisualDataModelPrivate()
QDeclarativeVisualDataModelPrivate::QDeclarativeVisualDataModelPrivate (QDeclarativeContext * ctxt)
Definition at line 634 of file qdeclarativevisualitemmodel.cpp.
 : m_listModelInterface(0), m_abstractItemModel(0), m_visualItemModel(0), m_delegate(0)
 , m_context(ctxt), m_modelDataPropId(-1), m_parts(0), m_delegateDataType(0), m_metaDataCreated(false)
 , m_metaDataCacheable(false), m_delegateValidated(false), m_completePending(false), m_listAccessor(0)
 {
 }
Functions
createMetaData()
void QDeclarativeVisualDataModelPrivate::createMetaData () inline
Definition at line 324 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelData::ensureProperties().
{
         if (!m_metaDataCreated) {
             ensureRoles();
             if (m_roleNames.count()) {
                 QHash<QByteArray, int>::const_iterator it = m_roleNames.begin();
                 while (it != m_roleNames.end()) {
                     int propId = m_delegateDataType->createProperty(it.key()) - m_delegateDataType->propertyOffset();
                     m_roleToPropId.insert(*it, propId);
                     ++it;
                 }
                 // Add modelData property
                 if (m_roles.count() == 1)
                     m_modelDataPropId = m_delegateDataType->createProperty("modelData") - m_delegateDataType->propertyOffset();
                 m_metaDataCreated = true;
             }
         }
     }
data()
QDeclarativeVisualDataModelData * QDeclarativeVisualDataModelPrivate::data (QObject * item)
Definition at line 641 of file qdeclarativevisualitemmodel.cpp.
 {
     QDeclarativeVisualDataModelData *dataItem =
         item->findChild<QDeclarativeVisualDataModelData *>();
     Q_ASSERT(dataItem);
     return dataItem;
 }
ensureRoles()
void QDeclarativeVisualDataModelPrivate::ensureRoles () inline
Definition at line 293 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
{
         if (m_roleNames.isEmpty()) {
             if (m_listModelInterface) {
                 m_roles = m_listModelInterface->roles();
                 for (int ii = 0; ii < m_roles.count(); ++ii)
                     m_roleNames.insert(m_listModelInterface->toString(m_roles.at(ii)).toUtf8(), m_roles.at(ii));
             } else if (m_abstractItemModel) {
                 for (QHash<int,QByteArray>::const_iterator it = m_abstractItemModel->roleNames().begin();
                         it != m_abstractItemModel->roleNames().end(); ++it) {
                     m_roles.append(it.key());
                     m_roleNames.insert(*it, it.key());
                 }
                 if (m_roles.count())
                     m_roleNames.insert("hasModelChildren", -1);
             } else if (m_listAccessor) {
                 m_roleNames.insert("modelData", 0);
                 if (m_listAccessor->type() == QDeclarativeListAccessor::Instance) {
                     if (QObject *object = m_listAccessor->at(0).value<QObject*>()) {
                         int count = object->metaObject()->propertyCount();
                         for (int ii = 1; ii < count; ++ii) {
                             const QMetaProperty &prop = object->metaObject()->property(ii);
                             m_roleNames.insert(prop.name(), 0);
                         }
                     }
                 }
             }
         }
     }
get()
static QDeclarativeVisualDataModelPrivate* QDeclarativeVisualDataModelPrivate::get (QDeclarativeVisualDataModel * m) inline static
Definition at line 280 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), QDeclarativeVisualDataModelData::ensureProperties(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), QDeclarativeVisualDataModelData::modelDataPropertyId(), and QDeclarativeVisualDataModelData::propForRole().
{
         return static_cast<QDeclarativeVisualDataModelPrivate *>(QObjectPrivate::get(m));
     }
modelCount()
int QDeclarativeVisualDataModelPrivate::modelCount () const inline
Definition at line 384 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty().
{
         if (m_visualItemModel)
             return m_visualItemModel->count();
         if (m_listModelInterface)
             return m_listModelInterface->count();
         if (m_abstractItemModel)
             return m_abstractItemModel->rowCount(m_root);
         if (m_listAccessor)
             return m_listAccessor->count();
         return 0;
     }
Friends and Related Functions
QDeclarativeVisualDataModelData
friend class QDeclarativeVisualDataModelData friend
Definition at line 403 of file qdeclarativevisualitemmodel.cpp.
QDeclarativeVisualItemParts
friend class QDeclarativeVisualItemParts friend
Definition at line 400 of file qdeclarativevisualitemmodel.cpp.
Properties
m_abstractItemModel
QDeclarativeGuard<QAbstractItemModel> QDeclarativeVisualDataModelPrivate::m_abstractItemModel
Definition at line 285 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
m_cache
Cache QDeclarativeVisualDataModelPrivate::m_cache
Definition at line 396 of file qdeclarativevisualitemmodel.cpp.
m_completePending
bool QDeclarativeVisualDataModelPrivate::m_completePending
Definition at line 407 of file qdeclarativevisualitemmodel.cpp.
m_context
QDeclarativeGuard<QDeclarativeContext> QDeclarativeVisualDataModelPrivate::m_context
Definition at line 290 of file qdeclarativevisualitemmodel.cpp.
m_delegate
QDeclarativeComponent* QDeclarativeVisualDataModelPrivate::m_delegate
Definition at line 289 of file qdeclarativevisualitemmodel.cpp.
m_delegateDataType
VDMDelegateDataType* QDeclarativeVisualDataModelPrivate::m_delegateDataType
Definition at line 402 of file qdeclarativevisualitemmodel.cpp.
m_delegateValidated
bool QDeclarativeVisualDataModelPrivate::m_delegateValidated
Definition at line 406 of file qdeclarativevisualitemmodel.cpp.
m_listAccessor
QDeclarativeListAccessor* QDeclarativeVisualDataModelPrivate::m_listAccessor
Definition at line 412 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
m_listModelInterface
QDeclarativeGuard<QListModelInterface> QDeclarativeVisualDataModelPrivate::m_listModelInterface
Definition at line 284 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
m_metaDataCacheable
bool QDeclarativeVisualDataModelPrivate::m_metaDataCacheable
Definition at line 405 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelData::ensureProperties().
m_metaDataCreated
bool QDeclarativeVisualDataModelPrivate::m_metaDataCreated
Definition at line 404 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelData::ensureProperties().
m_modelDataPropId
int QDeclarativeVisualDataModelPrivate::m_modelDataPropId
Definition at line 323 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelData::modelDataPropertyId().
m_modelVariant
QVariant QDeclarativeVisualDataModelPrivate::m_modelVariant
Definition at line 411 of file qdeclarativevisualitemmodel.cpp.
m_packaged
QHash<QObject *, QDeclarativePackage*> QDeclarativeVisualDataModelPrivate::m_packaged
Definition at line 397 of file qdeclarativevisualitemmodel.cpp.
m_part
QString QDeclarativeVisualDataModelPrivate::m_part
Definition at line 287 of file qdeclarativevisualitemmodel.cpp.
m_parts
QDeclarativeVisualDataModelParts* QDeclarativeVisualDataModelPrivate::m_parts
Definition at line 399 of file qdeclarativevisualitemmodel.cpp.
m_roleNames
QHash<QByteArray,int> QDeclarativeVisualDataModelPrivate::m_roleNames
Definition at line 292 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::initialValue().
m_roles
QList<int> QDeclarativeVisualDataModelPrivate::m_roles
Definition at line 291 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::initialValue().
m_roleToPropId
QHash<int,int> QDeclarativeVisualDataModelPrivate::m_roleToPropId
Definition at line 322 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelData::propForRole().
m_root
QModelIndex QDeclarativeVisualDataModelPrivate::m_root
Definition at line 414 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::initialValue().
m_visualItemModel
QDeclarativeGuard<QDeclarativeVisualDataModel> QDeclarativeVisualDataModelPrivate::m_visualItemModel
Definition at line 286 of file qdeclarativevisualitemmodel.cpp.
watchedRoleIds
QList<int> QDeclarativeVisualDataModelPrivate::watchedRoleIds
Definition at line 416 of file qdeclarativevisualitemmodel.cpp.
watchedRoles
QList<QByteArray> QDeclarativeVisualDataModelPrivate::watchedRoles
Definition at line 415 of file qdeclarativevisualitemmodel.cpp.
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativevisualitemmodel.cpp