Qt 4.8: QWSLock Class Reference
QWSLock Class Reference
#include <qwslock_p.h>
Public Types
enum LockType { BackingStore, Communication, RegionEvent }
Public Functions
bool hasLock (LockType type)
int id () const
bool lock (LockType type, int timeout=-1)
QWSLock (int lockId=-1)
void unlock (LockType type)
bool wait (LockType type, int timeout=-1)
~QWSLock ()
Private Functions
bool down (unsigned short semNum, int timeout)
int getValue (unsigned short semNum) const
bool up (unsigned short semNum)
Properties
int lockCount [2]
int semId
Detailed Description
Definition at line 66 of file qwslock_p.h.
Enumerations
LockType
enum QWSLock::LockType
Enumerator
BackingStore
Communication
RegionEvent
Definition at line 69 of file qwslock_p.h.
 { BackingStore, Communication, RegionEvent };
Constructors and Destructors
QWSLock()
QWSLock::QWSLock (int lockId = -1)
Definition at line 78 of file qwslock.cpp.
                        : semId(id)
 {
     static unsigned short initialValues[3] = { 1, 1, 0 };
 #ifndef QT_NO_QWS_SIGNALHANDLER
     QWSSignalHandler::instance()->addWSLock(this);
 #endif
 #ifndef QT_POSIX_IPC
     if (semId == -1) {
         semId = semget(IPC_PRIVATE, 3, IPC_CREAT | 0666);
         if (semId == -1) {
             perror("QWSLock::QWSLock");
             qFatal("Unable to create semaphore");
         }
         qt_semun semval;
         semval.array = initialValues;
         if (semctl(semId, 0, SETALL, semval) == -1) {
             perror("QWSLock::QWSLock");
             qFatal("Unable to initialize semaphores");
         }
     }
 #else
     sems[0] = sems[1] = sems[2] = SEM_FAILED;
     owned = false;
     if (semId == -1) {
         // ### generate really unique IDs
         semId = (getpid() << 16) + (localUniqueId.fetchAndAddRelaxed(1) % ushort(-1));
         owned = true;
     }
     QByteArray pfx = "/qwslock_" + QByteArray::number(semId, 16) + '_';
     QByteArray keys[3] = { pfx + "BackingStore", pfx + "Communication", pfx + "RegionEvent" };
     for (int i = 0; i < 3; ++i) {
         if (owned)
             sem_unlink(keys[i].constData());
         do {
             sems[i] = sem_open(keys[i].constData(), (owned ? O_CREAT : 0), 0666, initialValues[i]);
         } while (sems[i] == SEM_FAILED && errno == EINTR);
         if (sems[i] == SEM_FAILED) {
             perror("QWSLock::QWSLock");
             qFatal("Unable to %s semaphore", (owned ? "create" : "open"));
         }
     }
 #endif
     lockCount[0] = lockCount[1] = 0;
 }
~QWSLock()
QWSLock::~QWSLock ()
Definition at line 129 of file qwslock.cpp.
Referenced by QWSSignalHandler::clear().
 {
 #ifndef QT_NO_QWS_SIGNALHANDLER
     QWSSignalHandler::instance()->removeWSLock(this);
 #endif
     if (semId != -1) {
 #ifndef QT_POSIX_IPC
         qt_semun semval;
         semval.val = 0;
         semctl(semId, 0, IPC_RMID, semval);
         semId = -1;
 #else
         // emulate the SEM_UNDO behavior for the BackingStore lock
         while (hasLock(BackingStore))
             unlock(BackingStore);
         QByteArray pfx = "/qwslock_" + QByteArray::number(semId, 16) + '_';
         QByteArray keys[3] = { pfx + "BackingStore", pfx + "Communication", pfx + "RegionEvent" };
         for (int i = 0; i < 3; ++i) {
             if (sems[i] != SEM_FAILED) {
                 sem_close(sems[i]);
                 sems[i] = SEM_FAILED;
             }
             if (owned)
                 sem_unlink(keys[i].constData());
         }
 #endif
     }
 }
Functions
down()
bool QWSLock::down (unsigned short semNum, int timeout) private
Definition at line 185 of file qwslock.cpp.
Referenced by id(), lock(), unlock(), and wait().
 {
     int ret;
 #ifndef QT_POSIX_IPC
     sembuf sops = { semNum, -1, 0 };
     // As the BackingStore lock is a mutex, and only one process may own
     // the lock, it's safe to use SEM_UNDO. On the other hand, the
     // Communication lock is locked by the client but unlocked by the
     // server and therefore can't use SEM_UNDO.
     if (semNum == BackingStore)
         sops.sem_flg |= SEM_UNDO;
     EINTR_LOOP(ret, semop(semId, &sops, 1));
 #else
     EINTR_LOOP(ret, sem_wait(sems[semNum]));
 #endif
     if (ret == -1) {
         qDebug("QWSLock::down(): %s", strerror(errno));
         return false;
     }
     return true;
 }
getValue()
int QWSLock::getValue (unsigned short semNum) const private
Definition at line 210 of file qwslock.cpp.
Referenced by hasLock(), and id().
 {
     int ret;
 #ifndef QT_POSIX_IPC
     ret = semctl(semId, semNum, GETVAL, 0);
 #else
     if (sem_getvalue(sems[semNum], &ret) == -1)
         ret = -1;
 #endif
     if (ret == -1)
         qDebug("QWSLock::getValue(): %s", strerror(errno));
     return ret;
 }
hasLock()
bool QWSLock::hasLock (LockType type)
Definition at line 242 of file qwslock.cpp.
Referenced by ~QWSLock().
 {
     if (type == RegionEvent)
         return getValue(type) == 0;
     return lockCount[type] > 0;
 }
id()
int QWSLock::id () const inline
Definition at line 78 of file qwslock_p.h.
Referenced by QWSSharedMemSurface::permanentState(), QWSDisplay::setIdentity(), and QWSMemorySurface::setLock().
 { return semId; }
lock()
bool QWSLock::lock (LockType type, int timeout = -1)
Definition at line 224 of file qwslock.cpp.
 {
     if (type == RegionEvent)
         return up(type);
     if (lockCount[type] > 0) {
         ++lockCount[type];
         return true;
     }
     if (down(type, timeout)) {
         ++lockCount[type];
         return true;
     }
     return false;
 }
unlock()
void QWSLock::unlock (LockType type)
Definition at line 250 of file qwslock.cpp.
Referenced by wait(), and ~QWSLock().
 {
     if (type == RegionEvent) {
         down(type, -1);
         return;
     }
     if (lockCount[type] > 0) {
         --lockCount[type];
         if (lockCount[type] > 0)
             return;
     }
     up(type);
 }
up()
bool QWSLock::up (unsigned short semNum) private
Definition at line 160 of file qwslock.cpp.
Referenced by id(), lock(), and unlock().
 {
     int ret;
 #ifndef QT_POSIX_IPC
     sembuf sops = { semNum, 1, 0 };
     // As the BackingStore lock is a mutex, and only one process may own
     // the lock, it's safe to use SEM_UNDO. On the other hand, the
     // Communication lock is locked by the client but unlocked by the
     // server and therefore can't use SEM_UNDO.
     if (semNum == BackingStore)
         sops.sem_flg |= SEM_UNDO;
     EINTR_LOOP(ret, semop(semId, &sops, 1));
 #else
     ret = sem_post(sems[semNum]);
 #endif
     if (ret == -1) {
         qDebug("QWSLock::up(): %s", strerror(errno));
         return false;
     }
     return true;
 }
wait()
bool QWSLock::wait (LockType type, int timeout = -1)
Definition at line 266 of file qwslock.cpp.
 {
     bool ok = down(type, timeout);
     if (ok)
         unlock(type);
     return ok;
 }
Properties
lockCount
int QWSLock::lockCount[2] private
Definition at line 86 of file qwslock_p.h.
Referenced by hasLock(), lock(), QWSLock(), and unlock().
semId
int QWSLock::semId private
Definition at line 85 of file qwslock_p.h.
Referenced by down(), getValue(), id(), QWSLock(), up(), and ~QWSLock().
The documentation for this class was generated from the following files:
/src/gui/embedded/qwslock_p.h
/src/gui/embedded/qwslock.cpp