Qt 4.8: QLabelPrivate Class Reference
QLabelPrivate Class Reference
#include <qlabel_p.h>
Public Functions
void _q_linkHovered (const QString &link)
void _q_movieResized (const QSize &)
void _q_movieUpdated (const QRect &)
void clearContents ()
Clears any contents, without updating/repainting the label.
QMenu * createStandardContextMenu (const QPoint &pos)
QRect documentRect () const
void ensureTextControl () const
void ensureTextLayouted () const
void ensureTextPopulated () const
void init ()
QPoint layoutPoint (const QPoint &p) const
QRectF layoutRect () const
bool needTextControl () const
QLabelPrivate ()
void sendControlEvent (QEvent *e)
QSize sizeForWidth (int w) const
Returns the size that will be used if the width of the label is w.
Qt::LayoutDirection textDirection () const
void updateLabel ()
Updates the label, but not the frame.
void updateShortcut ()
Public Functions inherited from QFramePrivate
void init ()
QFramePrivate ()
void updateFrameWidth ()
Updated the frameWidth parameter.
void updateStyledFrameWidths ()
Updates the frame widths from the style.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
ushort align
QPointer< QWidget > buddy
QImage * cachedimage
QTextControl * control
QCursor cursor
uint hasShortcut: 1
short indent
uint isRichText: 1
uint isTextLabel: 1
int margin
QPointer< QMovie > movie
QSize msh
uint onAnchor: 1
bool openExternalLinks
QPicture * picture
QPixmap * pixmap
uint scaledcontents:1
QPixmap * scaledpixmap
QSize sh
QTextCursor shortcutCursor
int shortcutId
QSizePolicy sizePolicy
QString text
uint textDirty: 1
Qt::TextFormat textformat
Qt::TextInteractionFlags textInteractionFlags
uint textLayoutDirty: 1
bool valid_hints
uint validCursor: 1
Public Variables inherited from QFramePrivate
short bottomFrameWidth
int frameStyle
short frameWidth
QRect frect
short leftFrameWidth
short lineWidth
short midLineWidth
short rightFrameWidth
short topFrameWidth
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Friends
class QMessageBoxPrivate
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 71 of file qlabel_p.h.
Constructors and Destructors
QLabelPrivate()
QLabelPrivate::QLabelPrivate () inline
Definition at line 75 of file qlabel_p.h.
 {}
Functions
_q_linkHovered()
void QLabelPrivate::_q_linkHovered (const QString & link)
Definition at line 1710 of file qlabel.cpp.
Referenced by needTextControl().
 {
     Q_Q(QLabel);
 #ifndef QT_NO_CURSOR
     if (anchor.isEmpty()) { // restore cursor
         if (validCursor)
             q->setCursor(cursor);
         else
             q->unsetCursor();
         onAnchor = false;
     } else if (!onAnchor) {
         validCursor = q->testAttribute(Qt::WA_SetCursor);
         if (validCursor) {
             cursor = q->cursor();
         }
         q->setCursor(Qt::PointingHandCursor);
         onAnchor = true;
     }
 #endif
     emit q->linkHovered(anchor);
 }
_q_movieResized()
void QLabelPrivate::_q_movieResized (const QSize & size)
Definition at line 1367 of file qlabel.cpp.
 {
     Q_Q(QLabel);
     q->update(); //we need to refresh the whole background in case the new size is smaler
     valid_hints = false;
     _q_movieUpdated(QRect(QPoint(0,0), size));
     q->updateGeometry();
 }
_q_movieUpdated()
void QLabelPrivate::_q_movieUpdated (const QRect & rect)
Definition at line 1344 of file qlabel.cpp.
 {
     Q_Q(QLabel);
     if (movie && movie->isValid()) {
         QRect r;
         if (scaledcontents) {
             QRect cr = q->contentsRect();
             QRect pixmapRect(cr.topLeft(), movie->currentPixmap().size());
             if (pixmapRect.isEmpty())
                 return;
             r.setRect(cr.left(), cr.top(),
                       (rect.width() * cr.width()) / pixmapRect.width(),
                       (rect.height() * cr.height()) / pixmapRect.height());
         } else {
             r = q->style()->itemPixmapRect(q->contentsRect(), align, movie->currentPixmap());
             r.translate(rect.x(), rect.y());
             r.setWidth(qMin(r.width(), rect.width()));
             r.setHeight(qMin(r.height(), rect.height()));
         }
         q->update(r);
     }
 }
clearContents()
void QLabelPrivate::clearContents ()
Clears any contents, without updating/repainting the label.
Warning
This function is not part of the public interface.
Definition at line 1414 of file qlabel.cpp.
Referenced by QLabelPrivate().
 {
     delete control;
     control = 0;
     isTextLabel = false;
     hasShortcut = false;
 #ifndef QT_NO_PICTURE
     delete picture;
     picture = 0;
 #endif
     delete scaledpixmap;
     scaledpixmap = 0;
     delete cachedimage;
     cachedimage = 0;
     delete pixmap;
     pixmap = 0;
     text.clear();
     Q_Q(QLabel);
 #ifndef QT_NO_SHORTCUT
     if (shortcutId)
         q->releaseShortcut(shortcutId);
     shortcutId = 0;
 #endif
 #ifndef QT_NO_MOVIE
     if (movie) {
         QObject::disconnect(movie, SIGNAL(resized(QSize)), q, SLOT(_q_movieResized(QSize)));
         QObject::disconnect(movie, SIGNAL(updated(QRect)), q, SLOT(_q_movieUpdated(QRect)));
     }
     movie = 0;
 #endif
 #ifndef QT_NO_CURSOR
     if (onAnchor) {
         if (validCursor)
             q->setCursor(cursor);
         else
             q->unsetCursor();
     }
     validCursor = false;
     onAnchor = false;
 #endif
 }
createStandardContextMenu()
QMenu * QLabelPrivate::createStandardContextMenu (const QPoint & pos)
Definition at line 1759 of file qlabel.cpp.
Referenced by needTextControl().
 {
     QString linkToCopy;
     QPoint p;
     if (control && isRichText) {
         p = layoutPoint(pos);
         linkToCopy = control->document()->documentLayout()->anchorAt(p);
     }
     if (linkToCopy.isEmpty() && !control)
         return 0;
     return control->createStandardContextMenu(p, q_func());
 }
documentRect()
QRect QLabelPrivate::documentRect () const
Definition at line 1587 of file qlabel.cpp.
Referenced by needTextControl().
 {
     Q_Q(const QLabel);
     Q_ASSERT_X(isTextLabel, "documentRect", "document rect called for label that is not a text label!");
     QRect cr = q->contentsRect();
     cr.adjust(margin, margin, -margin, -margin);
     const int align = QStyle::visualAlignment(isTextLabel ? textDirection()
                                                           : q->layoutDirection(), QFlag(this->align));
     int m = indent;
     if (m < 0 && q->frameWidth()) // no indent, but we do have a frame
         m = q->fontMetrics().width(QLatin1Char('x')) / 2 - margin;
     if (m > 0) {
         if (align & Qt::AlignLeft)
             cr.setLeft(cr.left() + m);
         if (align & Qt::AlignRight)
             cr.setRight(cr.right() - m);
         if (align & Qt::AlignTop)
             cr.setTop(cr.top() + m);
         if (align & Qt::AlignBottom)
             cr.setBottom(cr.bottom() - m);
     }
     return cr;
 }
ensureTextControl()
void QLabelPrivate::ensureTextControl () const
Definition at line 1676 of file qlabel.cpp.
Referenced by needTextControl().
 {
     Q_Q(const QLabel);
     if (!isTextLabel)
         return;
     if (!control) {
         control = new QTextControl(const_cast<QLabel *>(q));
         control->document()->setUndoRedoEnabled(false);
         control->document()->setDefaultFont(q->font());
         control->setTextInteractionFlags(textInteractionFlags);
         control->setOpenExternalLinks(openExternalLinks);
         control->setPalette(q->palette());
         control->setFocus(q->hasFocus());
         QObject::connect(control, SIGNAL(updateRequest(QRectF)),
                          q, SLOT(update()));
         QObject::connect(control, SIGNAL(linkHovered(QString)),
                          q, SLOT(_q_linkHovered(QString)));
         QObject::connect(control, SIGNAL(linkActivated(QString)),
                          q, SIGNAL(linkActivated(QString)));
         textLayoutDirty = true;
         textDirty = true;
     }
 }
ensureTextLayouted()
void QLabelPrivate::ensureTextLayouted () const
Definition at line 1650 of file qlabel.cpp.
Referenced by needTextControl().
 {
     if (!textLayoutDirty)
         return;
     ensureTextPopulated();
     if (control) {
         QTextDocument *doc = control->document();
         QTextOption opt = doc->defaultTextOption();
         opt.setAlignment(QFlag(this->align));
         if (this->align & Qt::TextWordWrap)
             opt.setWrapMode(QTextOption::WordWrap);
         else
             opt.setWrapMode(QTextOption::ManualWrap);
         doc->setDefaultTextOption(opt);
         QTextFrameFormat fmt = doc->rootFrame()->frameFormat();
         fmt.setMargin(0);
         doc->rootFrame()->setFrameFormat(fmt);
         doc->setTextWidth(documentRect().width());
     }
     textLayoutDirty = false;
 }
ensureTextPopulated()
void QLabelPrivate::ensureTextPopulated () const
Definition at line 1611 of file qlabel.cpp.
Referenced by needTextControl().
 {
     if (!textDirty)
         return;
     if (control) {
         QTextDocument *doc = control->document();
         if (textDirty) {
 #ifndef QT_NO_TEXTHTMLPARSER
             if (isRichText)
                 doc->setHtml(text);
             else
                 doc->setPlainText(text);
 #else
             doc->setPlainText(text);
 #endif
             doc->setUndoRedoEnabled(false);
 #ifndef QT_NO_SHORTCUT
             if (hasShortcut) {
                 // Underline the first character that follows an ampersand (and remove the others ampersands)
                 int from = 0;
                 bool found = false;
                 QTextCursor cursor;
                 while (!(cursor = control->document()->find((QLatin1String("&")), from)).isNull()) {
                     cursor.deleteChar(); // remove the ampersand
                     cursor.movePosition(QTextCursor::NextCharacter, QTextCursor::KeepAnchor);
                     from = cursor.position();
                     if (!found && cursor.selectedText() != QLatin1String("&")) { //not a second &
                         found = true;
                         shortcutCursor = cursor;
                     }
                 }
             }
 #endif
         }
     }
     textDirty = false;
 }
init()
void QLabelPrivate::init ()
Definition at line 292 of file qlabel.cpp.
Referenced by QLabelPrivate().
 {
     Q_Q(QLabel);
     valid_hints = false;
     margin = 0;
 #ifndef QT_NO_MOVIE
     movie = 0;
 #endif
 #ifndef QT_NO_SHORTCUT
     shortcutId = 0;
 #endif
     pixmap = 0;
     scaledpixmap = 0;
     cachedimage = 0;
 #ifndef QT_NO_PICTURE
     picture = 0;
 #endif
     align = Qt::AlignLeft | Qt::AlignVCenter | Qt::TextExpandTabs;
     indent = -1;
     scaledcontents = false;
     textLayoutDirty = false;
     textDirty = false;
     textformat = Qt::AutoText;
     control = 0;
     textInteractionFlags = Qt::LinksAccessibleByMouse;
     isRichText = false;
     isTextLabel = false;
     q->setSizePolicy(QSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred,
                                  QSizePolicy::Label));
 #ifndef QT_NO_CURSOR
     validCursor = false;
     onAnchor = false;
 #endif
     openExternalLinks = false;
     setLayoutItemMargins(QStyle::SE_LabelLayoutItem);
 }
layoutPoint()
QPoint QLabelPrivate::layoutPoint (const QPoint & p) const
Definition at line 1752 of file qlabel.cpp.
Referenced by needTextControl().
 {
     QRect lr = layoutRect().toRect();
     return p - lr.topLeft();
 }
layoutRect()
QRectF QLabelPrivate::layoutRect () const
Definition at line 1735 of file qlabel.cpp.
Referenced by needTextControl().
 {
     QRectF cr = documentRect();
     if (!control)
         return cr;
     ensureTextLayouted();
     // Caculate y position manually
     qreal rh = control->document()->documentLayout()->documentSize().height();
     qreal yo = 0;
     if (align & Qt::AlignVCenter)
         yo = qMax((cr.height()-rh)/2, qreal(0));
     else if (align & Qt::AlignBottom)
         yo = qMax(cr.height()-rh, qreal(0));
     return QRectF(cr.x(), yo + cr.y(), cr.width(), cr.height());
 }
needTextControl()
bool QLabelPrivate::needTextControl () const inline
Definition at line 119 of file qlabel_p.h.
{
         return isTextLabel
                && (isRichText
                    || (!isRichText && (textInteractionFlags & (Qt::TextSelectableByMouse | Qt::TextSelectableByKeyboard))));
     }
sendControlEvent()
void QLabelPrivate::sendControlEvent (QEvent * e)
Definition at line 1700 of file qlabel.cpp.
Referenced by needTextControl().
 {
     Q_Q(QLabel);
     if (!isTextLabel || !control || textInteractionFlags == Qt::NoTextInteraction) {
         e->ignore();
         return;
     }
     control->processEvent(e, -layoutRect().topLeft(), q);
 }
sizeForWidth()
QSize QLabelPrivate::sizeForWidth (int w) const
Returns the size that will be used if the width of the label is w.
If w is -1, the sizeHint() is returned. If w is 0 minimumSizeHint() is returned
Definition at line 667 of file qlabel.cpp.
Referenced by QLabelPrivate().
 {
     Q_Q(const QLabel);
     if(q->minimumWidth() > 0)
         w = qMax(w, q->minimumWidth());
     QSize contentsMargin(leftmargin + rightmargin, topmargin + bottommargin);
     QRect br;
     int hextra = 2 * margin;
     int vextra = hextra;
     QFontMetrics fm = q->fontMetrics();
     if (pixmap && !pixmap->isNull())
         br = pixmap->rect();
 #ifndef QT_NO_PICTURE
     else if (picture && !picture->isNull())
         br = picture->boundingRect();
 #endif
 #ifndef QT_NO_MOVIE
     else if (movie && !movie->currentPixmap().isNull())
         br = movie->currentPixmap().rect();
 #endif
     else if (isTextLabel) {
         int align = QStyle::visualAlignment(textDirection(), QFlag(this->align));
         // Add indentation
         int m = indent;
         if (m < 0 && q->frameWidth()) // no indent, but we do have a frame
             m = fm.width(QLatin1Char('x')) - margin*2;
         if (m > 0) {
             if ((align & Qt::AlignLeft) || (align & Qt::AlignRight))
                 hextra += m;
             if ((align & Qt::AlignTop) || (align & Qt::AlignBottom))
                 vextra += m;
         }
         if (control) {
             ensureTextLayouted();
             const qreal oldTextWidth = control->textWidth();
             // Calculate the length of document if w is the width
             if (align & Qt::TextWordWrap) {
                 if (w >= 0) {
                     w = qMax(w-hextra-contentsMargin.width(), 0); // strip margin and indent
                     control->setTextWidth(w);
                 } else {
                     control->adjustSize();
                 }
             } else {
                 control->setTextWidth(-1);
             }
             QSizeF controlSize = control->size();
             br = QRect(QPoint(0, 0), QSize(qCeil(controlSize.width()), qCeil(controlSize.height())));
             // restore state
             control->setTextWidth(oldTextWidth);
         } else {
             // Turn off center alignment in order to avoid rounding errors for centering,
             // since centering involves a division by 2. At the end, all we want is the size.
             int flags = align & ~(Qt::AlignVCenter | Qt::AlignHCenter);
             if (hasShortcut) {
                 flags |= Qt::TextShowMnemonic;
                 QStyleOption opt;
                 opt.initFrom(q);
                 if (!q->style()->styleHint(QStyle::SH_UnderlineShortcut, &opt, q))
                     flags |= Qt::TextHideMnemonic;
             }
             bool tryWidth = (w < 0) && (align & Qt::TextWordWrap);
             if (tryWidth)
 #ifdef Q_OS_SYMBIAN
                 w = qMin(S60->clientRect().Width(), q->maximumSize().width());
 #else
                 w = qMin(fm.averageCharWidth() * 80, q->maximumSize().width());
 #endif
             else if (w < 0)
                 w = 2000;
             w -= (hextra + contentsMargin.width());
             br = fm.boundingRect(0, 0, w ,2000, flags, text);
             if (tryWidth && br.height() < 4*fm.lineSpacing() && br.width() > w/2)
                 br = fm.boundingRect(0, 0, w/2, 2000, flags, text);
             if (tryWidth && br.height() < 2*fm.lineSpacing() && br.width() > w/4)
                 br = fm.boundingRect(0, 0, w/4, 2000, flags, text);
         }
     } else {
         br = QRect(QPoint(0, 0), QSize(fm.averageCharWidth(), fm.lineSpacing()));
     }
     const QSize contentsSize(br.width() + hextra, br.height() + vextra);
     return (contentsSize + contentsMargin).expandedTo(q->minimumSize());
 }
textDirection()
Qt::LayoutDirection QLabelPrivate::textDirection () const
Definition at line 1564 of file qlabel.cpp.
Referenced by needTextControl().
 {
     if (control) {
         QTextOption opt = control->document()->defaultTextOption();
         return opt.textDirection();
     }
     return text.isRightToLeft() ? Qt::RightToLeft : Qt::LeftToRight;
 }
updateLabel()
void QLabelPrivate::updateLabel ()
Updates the label, but not the frame.
Definition at line 1253 of file qlabel.cpp.
Referenced by QLabelPrivate().
 {
     Q_Q(QLabel);
     valid_hints = false;
     if (isTextLabel) {
         QSizePolicy policy = q->sizePolicy();
         const bool wrap = align & Qt::TextWordWrap;
         policy.setHeightForWidth(wrap);
         if (policy != q->sizePolicy())  // ### should be replaced by WA_WState_OwnSizePolicy idiom
             q->setSizePolicy(policy);
         textLayoutDirty = true;
     }
     q->updateGeometry();
     q->update(q->contentsRect());
 }
updateShortcut()
void QLabelPrivate::updateShortcut ()
Definition at line 1325 of file qlabel.cpp.
 {
     Q_Q(QLabel);
     Q_ASSERT(shortcutId == 0);
     // Introduce an extra boolean to indicate the presence of a shortcut in the
     // text. We cannot use the shortcutId itself because on the mac mnemonics are
     // off by default, so QKeySequence::mnemonic always returns an empty sequence.
     // But then we do want to hide the ampersands, so we can't use shortcutId.
     hasShortcut = false;
     if (!text.contains(QLatin1Char('&')))
         return;
     hasShortcut = true;
     shortcutId = q->grabShortcut(QKeySequence::mnemonic(text));
 }
Friends and Related Functions
QMessageBoxPrivate
friend class QMessageBoxPrivate friend
Definition at line 148 of file qlabel_p.h.
Properties
align
ushort QLabelPrivate::align
Definition at line 106 of file qlabel_p.h.
buddy
QPointer<QWidget> QLabelPrivate::buddy
Definition at line 103 of file qlabel_p.h.
cachedimage
QImage* QLabelPrivate::cachedimage
Definition at line 90 of file qlabel_p.h.
control
QTextControl* QLabelPrivate::control mutable
Definition at line 115 of file qlabel_p.h.
cursor
QCursor QLabelPrivate::cursor
Definition at line 145 of file qlabel_p.h.
hasShortcut
uint QLabelPrivate::hasShortcut mutable
Definition at line 113 of file qlabel_p.h.
indent
short QLabelPrivate::indent
Definition at line 107 of file qlabel_p.h.
isRichText
uint QLabelPrivate::isRichText mutable
Definition at line 111 of file qlabel_p.h.
Referenced by needTextControl().
isTextLabel
uint QLabelPrivate::isTextLabel mutable
Definition at line 112 of file qlabel_p.h.
Referenced by needTextControl().
margin
int QLabelPrivate::margin
Definition at line 86 of file qlabel_p.h.
movie
QPointer<QMovie> QLabelPrivate::movie
Definition at line 95 of file qlabel_p.h.
msh
QSize QLabelPrivate::msh mutable
Definition at line 83 of file qlabel_p.h.
onAnchor
uint QLabelPrivate::onAnchor
Definition at line 144 of file qlabel_p.h.
openExternalLinks
bool QLabelPrivate::openExternalLinks
Definition at line 140 of file qlabel_p.h.
picture
QPicture* QLabelPrivate::picture
Definition at line 92 of file qlabel_p.h.
pixmap
QPixmap* QLabelPrivate::pixmap
Definition at line 88 of file qlabel_p.h.
scaledcontents
uint QLabelPrivate::scaledcontents
Definition at line 108 of file qlabel_p.h.
scaledpixmap
QPixmap* QLabelPrivate::scaledpixmap
Definition at line 89 of file qlabel_p.h.
sh
QSize QLabelPrivate::sh mutable
Definition at line 82 of file qlabel_p.h.
shortcutCursor
QTextCursor QLabelPrivate::shortcutCursor mutable
Definition at line 116 of file qlabel_p.h.
shortcutId
int QLabelPrivate::shortcutId
Definition at line 104 of file qlabel_p.h.
sizePolicy
QSizePolicy QLabelPrivate::sizePolicy mutable
Definition at line 85 of file qlabel_p.h.
text
QString QLabelPrivate::text
Definition at line 87 of file qlabel_p.h.
textDirty
uint QLabelPrivate::textDirty mutable
Definition at line 110 of file qlabel_p.h.
textformat
Qt::TextFormat QLabelPrivate::textformat
Definition at line 114 of file qlabel_p.h.
textInteractionFlags
Qt::TextInteractionFlags QLabelPrivate::textInteractionFlags
Definition at line 117 of file qlabel_p.h.
textLayoutDirty
uint QLabelPrivate::textLayoutDirty mutable
Definition at line 109 of file qlabel_p.h.
valid_hints
bool QLabelPrivate::valid_hints mutable
Definition at line 84 of file qlabel_p.h.
validCursor
uint QLabelPrivate::validCursor
Definition at line 143 of file qlabel_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qlabel_p.h
/src/gui/widgets/qlabel.cpp