Qt 4.8: QHttpRequest Class Reference
QHttpRequest Class Reference abstract
Public Functions
virtual QIODevice * destinationDevice ()=0
virtual bool hasRequestHeader ()
QHttpRequest ()
virtual QHttpRequestHeader requestHeader ()
virtual QIODevice * sourceDevice ()=0
virtual void start (QHttp *)=0
virtual ~QHttpRequest ()
Public Variables
bool finished
int id
Static Private Attributes
static QBasicAtomicInt idCounter = Q_BASIC_ATOMIC_INITIALIZER(1)
Detailed Description
Definition at line 72 of file qhttp.cpp.
Constructors and Destructors
QHttpRequest()
QHttpRequest::QHttpRequest () inline
Definition at line 75 of file qhttp.cpp.
                    : finished(false)
     { id = idCounter.fetchAndAddRelaxed(1); }
~QHttpRequest()
virtual QHttpRequest::~QHttpRequest () inline virtual
Definition at line 77 of file qhttp.cpp.
     { }
Functions
destinationDevice()
virtual QIODevice* QHttpRequest::destinationDevice () pure virtual
Implemented in QHttpCloseRequest, QHttpSetSocketRequest, QHttpSetProxyRequest, QHttpSetUserRequest, QHttpSetHostRequest, and QHttpNormalRequest.
Referenced by QHttpNormalRequest::setRequestHeader(), and ~QHttpRequest().
hasRequestHeader()
bool QHttpRequest::hasRequestHeader () virtual
Reimplemented in QHttpNormalRequest.
Definition at line 185 of file qhttp.cpp.
Referenced by QHttp::currentRequest(), QHttpNormalRequest::~QHttpNormalRequest(), and ~QHttpRequest().
 {
     return false;
 }
requestHeader()
QHttpRequestHeader QHttpRequest::requestHeader () virtual
Reimplemented in QHttpNormalRequest.
Definition at line 190 of file qhttp.cpp.
Referenced by QHttp::currentRequest(), QHttpNormalRequest::~QHttpNormalRequest(), and ~QHttpRequest().
 {
     return QHttpRequestHeader();
 }
sourceDevice()
virtual QIODevice* QHttpRequest::sourceDevice () pure virtual
Implemented in QHttpCloseRequest, QHttpSetSocketRequest, QHttpSetProxyRequest, QHttpSetUserRequest, QHttpSetHostRequest, and QHttpNormalRequest.
Referenced by QHttpNormalRequest::setRequestHeader(), and ~QHttpRequest().
start()
virtual void QHttpRequest::start (QHttp *) pure virtual
Implemented in QHttpCloseRequest, QHttpSetSocketRequest, QHttpSetProxyRequest, QHttpSetUserRequest, QHttpSetHostRequest, QHttpPGHRequest, and QHttpNormalRequest.
Referenced by QHttpPrivate::_q_startNextRequest(), QHttpCloseRequest::QHttpCloseRequest(), QHttpSetHostRequest::QHttpSetHostRequest(), QHttpSetSocketRequest::QHttpSetSocketRequest(), QHttpSetUserRequest::QHttpSetUserRequest(), QHttpNormalRequest::~QHttpNormalRequest(), QHttpPGHRequest::~QHttpPGHRequest(), and ~QHttpRequest().
Properties
finished
bool QHttpRequest::finished
Definition at line 88 of file qhttp.cpp.
Referenced by QHttpPrivate::finishedWithError(), and QHttpPrivate::finishedWithSuccess().
id
int QHttpRequest::id
Definition at line 87 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_startNextRequest(), QHttpPrivate::addRequest(), QHttpPrivate::finishedWithError(), and QHttpPrivate::finishedWithSuccess().
idCounter
QBasicAtomicInt QHttpRequest::idCounter = Q_BASIC_ATOMIC_INITIALIZER(1) static private
Definition at line 91 of file qhttp.cpp.
Referenced by QHttpRequest().
The documentation for this class was generated from the following file:
/src/network/access/qhttp.cpp