Qt 4.8: QWSSoundServerProvider Class Reference
QWSSoundServerProvider Class Reference abstract
Public Functions
int add (int *mixl, int *mixr, int count)
bool equal (int wid, int sid)
virtual bool finished () const =0
int getSample (int off, int bps)
int groupId () const
bool muted ()
QWSSoundServerProvider (int w, int s)
virtual int readySamples (int)=0
void setMute (bool m)
void setPriority (bool p)
void setVolume (int lv, int rv)
int soundId () const
void startSampleRunin ()
virtual ~QWSSoundServerProvider ()
Static Public Functions
static void setPlayPriorityOnly (bool p)
Protected Functions
int devSamples ()
char * prepareBuffer (int &size)
void updateBuffer (int read)
Protected Variables
struct {
qint32 avgBytesPerSec
qint16 blockAlign
qint16 channels
qint16 formatTag
qint32 samplesPerSec
qint16 wBitsPerSample
} chunkdata
int dev
int samples_due
Properties
uchar * data
uchar data1 [sound_buffer_size+4]
uchar data2 [sound_buffer_size+4]
bool isPriority
int leftVolume
int * max
int max1
int max2
bool mMuted
int mSid
int mWid
int out
int rightVolume
int sampleRunin
Static Private Attributes
static int priorityExists = 0
Detailed Description
Definition at line 280 of file qsoundqss_qws.cpp.
Constructors and Destructors
QWSSoundServerProvider()
QWSSoundServerProvider::QWSSoundServerProvider (int w, int s) inline
Definition at line 282 of file qsoundqss_qws.cpp.
     : mWid(w), mSid(s), mMuted(false)
     {
     leftVolume = maxVolume>>1;
     rightVolume = maxVolume>>1;
     isPriority = false;
         samples_due = 0;
     max1 = max2 = out = 0;// = sound_buffer_size;
     data = data1;
     max = &max1;
     sampleRunin = 0;
     dev = -1;
     }
~QWSSoundServerProvider()
virtual QWSSoundServerProvider::~QWSSoundServerProvider () inline virtual
Definition at line 296 of file qsoundqss_qws.cpp.
{
     }
Functions
add()
int QWSSoundServerProvider::add (int * mixl, int * mixr, int count) inline
Definition at line 350 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::feedDevice().
     {
         int bytesPerSample = chunkdata.wBitsPerSample >> 3;
         if ( mMuted ) {
             sampleRunin -= qMin(sampleRunin,count);
             while (count && (dev != -1)) {
                 if (out >= *max) {
                     // switch buffers
                     out = 0;
                     if (data == data1 && max2 != 0) {
                         data = data2;
                         max = &max2;
                         max1 = 0;
                     } else if (data == data2 && max1 != 0) {
                         data = data1;
                         max = &max1;
                         max2 = 0;
                     } else {
                         qDebug("QSS Read Error: both buffers empty");
                         return 0;
                     }
                 }
                 samples_due += sound_speed;
                 while (count && samples_due >= chunkdata.samplesPerSec) {
                     samples_due -= chunkdata.samplesPerSec;
                     count--;
                 }
                 out += bytesPerSample * chunkdata.channels;
             }
             return count;
         }
         // This shouldn't be the case
         if ( !mixl || !mixr )
             return 0;
         int lVolNum = leftVolume, lVolDen = maxVolume;
         int rVolNum = rightVolume, rVolDen = maxVolume;
         if (priorityExists > 0 && !isPriority) {
             lVolNum = 0; // later, make this gradually fade in and out.
             lVolDen = 5;
             rVolNum = 0;
             rVolDen = 5;
         }
         while (count && (dev != -1)) {
             if (out >= *max) {
                 // switch buffers
                 out = 0;
                 if (data == data1 && max2 != 0) {
                     data = data2;
                     max = &max2;
                     max1 = 0;
                 } else if (data == data2 && max1 != 0) {
                     data = data1;
                     max = &max1;
                     max2 = 0;
                 } else {
                     qDebug("QSS Read Error: both buffers empty");
                     return 0;
                 }
             }
             samples_due += sound_speed;
             if (count && samples_due >= chunkdata.samplesPerSec) {
                 int l = getSample(0,bytesPerSample)*lVolNum/lVolDen;
                 int r = (chunkdata.channels == 2) ? getSample(1,bytesPerSample)*rVolNum/rVolDen : l;
                 if (!sound_stereo && chunkdata.channels == 2)
                     l += r;
         if (sampleRunin) {
                     while (sampleRunin && count && samples_due >= chunkdata.samplesPerSec) {
                         mixl++;
                         if (sound_stereo)
                             mixr++;
                         samples_due -= chunkdata.samplesPerSec;
                 sampleRunin--;
                         count--;
                     }
                 }
                 while (count && samples_due >= chunkdata.samplesPerSec) {
                     *mixl++ += l;
                     if (sound_stereo)
                         *mixr++ += r;
                     samples_due -= chunkdata.samplesPerSec;
                     count--;
                 }
             }
             // optimize out manipulation of sample if downsampling and we skip it
             out += bytesPerSample * chunkdata.channels;
         }
         return count;
     }
devSamples()
int QWSSoundServerProvider::devSamples () inline protected
Definition at line 481 of file qsoundqss_qws.cpp.
     {
     int possible = (((max1+max2-out) / ((chunkdata.wBitsPerSample>>3)*chunkdata.channels))
         *sound_speed)/chunkdata.samplesPerSec;
     return possible;
     }
equal()
bool QWSSoundServerProvider::equal (int wid, int sid) inline
Definition at line 447 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::pauseFile(), QWSSoundServerPrivate::resumeFile(), QWSSoundServerPrivate::setMute(), QWSSoundServerPrivate::setVolume(), and QWSSoundServerPrivate::stopFile().
     {
     return (wid == mWid && sid == mSid);
     }
finished()
virtual bool QWSSoundServerProvider::finished () const pure virtual
Implemented in QWSSoundServerStream, and QWSSoundServerBucket.
Referenced by QWSSoundServerPrivate::feedDevice().
getSample()
int QWSSoundServerProvider::getSample (int off, int bps) inline
Definition at line 340 of file qsoundqss_qws.cpp.
{
         //
         //  16-bit audio data is converted to native endian so that it can be scaled
         //  Yes, this is ugly on a BigEndian machine
         //  Perhaps it shouldn't be scaled at all
         //
         return (bps == 1) ? (data[out+off] - 128) * 128 : qToLittleEndian(((short*)data)[(out/2)+off]);
     }
groupId()
int QWSSoundServerProvider::groupId () const inline
Definition at line 299 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::feedDevice(), QWSSoundServerPrivate::sendCompletedSignals(), and QWSSoundServerPrivate::stopAll().
 { return mWid; }
muted()
bool QWSSoundServerProvider::muted () inline
Definition at line 314 of file qsoundqss_qws.cpp.
 { return mMuted; }
prepareBuffer()
char* QWSSoundServerProvider::prepareBuffer (int & size) inline protected
Definition at line 454 of file qsoundqss_qws.cpp.
     {
     // keep reading as long as there is 50 % or more room in off buffer.
     if (data == data1 && (max2<<1 < sound_buffer_size)) {
         size=sound_buffer_size - max2;
         return (char *)data2;
     } else if (data == data2 && (max1<<1 < sound_buffer_size)) {
         size=sound_buffer_size - max1;
         return (char *)data1;
     } else {
         size = 0;
         return 0;
     }
     }
readySamples()
virtual int QWSSoundServerProvider::readySamples (int) pure virtual
Implemented in QWSSoundServerStream, and QWSSoundServerBucket.
Referenced by QWSSoundServerPrivate::feedDevice().
setMute()
void QWSSoundServerProvider::setMute (bool m) inline
Definition at line 313 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::checkPresetVolumes(), QWSSoundServerPrivate::QWSSoundServerPrivate(), QWSSoundServerPrivate::setMute(), and QWSSoundServerPrivate::~QWSSoundServerPrivate().
 { mMuted = m; }
setPlayPriorityOnly()
static void QWSSoundServerProvider::setPlayPriorityOnly (bool p) inline static
Definition at line 323 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::playPriorityOnly().
     {
     if (p)
         priorityExists++;
     else
         priorityExists--;
     if (priorityExists < 0)
         qDebug("QSS: got more priority offs than ons");
     }
setPriority()
void QWSSoundServerProvider::setPriority (bool p) inline
Definition at line 316 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::playFile(), and QWSSoundServerPrivate::playRawFile().
{
     if (p != isPriority) {
         isPriority = p; // currently meaningless.
     }
     }
setVolume()
void QWSSoundServerProvider::setVolume (int lv, int rv) inline
Definition at line 308 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::checkPresetVolumes(), QWSSoundServerPrivate::playFile(), QWSSoundServerPrivate::QWSSoundServerPrivate(), QWSSoundServerPrivate::setVolume(), and QWSSoundServerPrivate::~QWSSoundServerPrivate().
{
     leftVolume = qMin(maxVolume, qMax(0, lv));
     rightVolume = qMin(maxVolume, qMax(0, rv));
     }
soundId()
int QWSSoundServerProvider::soundId () const inline
Definition at line 300 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::feedDevice(), and QWSSoundServerPrivate::sendCompletedSignals().
 { return mSid; }
startSampleRunin()
void QWSSoundServerProvider::startSampleRunin () inline
Definition at line 302 of file qsoundqss_qws.cpp.
{
     // inteded to provide even audio return from mute/pause/dead samples.
     //sampleRunin = runinLength; // or more?
     }
updateBuffer()
void QWSSoundServerProvider::updateBuffer (int read) inline protected
Definition at line 469 of file qsoundqss_qws.cpp.
     {
     // always reads to off buffer.
     if (read >= 0) {
         if (data == data2) {
         max1 = read;
         } else {
         max2 = read;
         }
     }
     }
Properties
avgBytesPerSec
qint32 QWSSoundServerProvider::avgBytesPerSec
Definition at line 494 of file qsoundqss_qws.cpp.
blockAlign
qint16 QWSSoundServerProvider::blockAlign
Definition at line 495 of file qsoundqss_qws.cpp.
channels
qint16 QWSSoundServerProvider::channels
Definition at line 492 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerStream::QWSSoundServerStream(), and QWSSoundServerPrivate::~QWSSoundServerPrivate().
chunkdata
struct { ... } QWSSoundServerProvider::chunkdata
data
uchar* QWSSoundServerProvider::data private
Definition at line 508 of file qsoundqss_qws.cpp.
Referenced by QWSSoundServerPrivate::feedDevice().
data1
uchar QWSSoundServerProvider::data1[sound_buffer_size+4] private
Definition at line 509 of file qsoundqss_qws.cpp.
data2
uchar QWSSoundServerProvider::data2[sound_buffer_size+4] private
Definition at line 510 of file qsoundqss_qws.cpp.
dev
int QWSSoundServerProvider::dev protected
Definition at line 498 of file qsoundqss_qws.cpp.
formatTag
qint16 QWSSoundServerProvider::formatTag
Definition at line 491 of file qsoundqss_qws.cpp.
isPriority
bool QWSSoundServerProvider::isPriority private
Definition at line 505 of file qsoundqss_qws.cpp.
leftVolume
int QWSSoundServerProvider::leftVolume private
Definition at line 503 of file qsoundqss_qws.cpp.
max
int* QWSSoundServerProvider::max private
Definition at line 507 of file qsoundqss_qws.cpp.
max1
int QWSSoundServerProvider::max1 private
Definition at line 511 of file qsoundqss_qws.cpp.
max2
int QWSSoundServerProvider::max2 private
Definition at line 511 of file qsoundqss_qws.cpp.
mMuted
bool QWSSoundServerProvider::mMuted private
Definition at line 513 of file qsoundqss_qws.cpp.
mSid
int QWSSoundServerProvider::mSid private
Definition at line 502 of file qsoundqss_qws.cpp.
mWid
int QWSSoundServerProvider::mWid private
Definition at line 501 of file qsoundqss_qws.cpp.
out
int QWSSoundServerProvider::out private
Definition at line 511 of file qsoundqss_qws.cpp.
priorityExists
int QWSSoundServerProvider::priorityExists = 0 static private
Definition at line 506 of file qsoundqss_qws.cpp.
rightVolume
int QWSSoundServerProvider::rightVolume private
Definition at line 504 of file qsoundqss_qws.cpp.
sampleRunin
int QWSSoundServerProvider::sampleRunin private
Definition at line 512 of file qsoundqss_qws.cpp.
samples_due
int QWSSoundServerProvider::samples_due protected
Definition at line 499 of file qsoundqss_qws.cpp.
samplesPerSec
qint32 QWSSoundServerProvider::samplesPerSec
Definition at line 493 of file qsoundqss_qws.cpp.
wBitsPerSample
qint16 QWSSoundServerProvider::wBitsPerSample
Definition at line 496 of file qsoundqss_qws.cpp.
The documentation for this class was generated from the following file:
/src/gui/embedded/qsoundqss_qws.cpp