Qt 4.8: QmlJSDebugger::AbstractViewInspector Class Reference
QmlJSDebugger::AbstractViewInspector Class Reference abstract
#include <abstractviewinspector.h>
Public Slots
void changeToColorPickerTool ()
void changeToMarqueeSelectTool ()
void changeToSingleSelectTool ()
void changeToZoomTool ()
void sendColorChanged (const QColor &color)
void sendDesignModeBehavior (bool inDesignMode)
void setAnimationPaused (bool paused)
void setAnimationSpeed (qreal factor)
virtual void setDesignModeBehavior (bool value)
void setShowAppOnTop (bool appOnTop)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void animationPausedChanged (bool paused)
void animationSpeedChanged (qreal factor)
void colorPickerActivated ()
void designModeBehaviorChanged (bool inDesignMode)
void marqueeSelectToolActivated ()
void reloadRequested ()
void selectedColorChanged (const QColor &color)
void selectToolActivated ()
void showAppOnTopChanged (bool showAppOnTop)
void zoomToolActivated ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
AbstractViewInspector (QObject *parent=0)
bool animationPaused () const
virtual void changeCurrentObjects (const QList< QObject *> &objects)=0
virtual void changeTool (InspectorProtocol::Tool tool)=0
void clearComponentCache ()
void createQmlObject (const QString &qml, QObject *parent, const QStringList &importList, const QString &filename=QString())
virtual QDeclarativeEngine * declarativeEngine () const =0
bool designModeBehavior () const
QString idStringForObject (QObject *obj) const
virtual void reloadView ()=0
virtual void reparentQmlObject (QObject *object, QObject *newParent)=0
void sendAnimationPaused (bool paused)
void sendAnimationSpeed (qreal slowDownFactor)
void sendCurrentObjects (const QList< QObject *> &)
void sendCurrentTool (Constants::DesignTool toolId)
void sendReloaded ()
void sendShowAppOnTop (bool showAppOnTop)
bool showAppOnTop () const
qreal slowDownFactor () const
virtual QWidget * viewWidget () const =0
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
AbstractTool * currentTool () const
bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
virtual bool keyPressEvent (QKeyEvent *event)
virtual bool keyReleaseEvent (QKeyEvent *keyEvent)
virtual bool leaveEvent (QEvent *)
virtual bool mouseDoubleClickEvent (QMouseEvent *event)
virtual bool mouseMoveEvent (QMouseEvent *event)
virtual bool mousePressEvent (QMouseEvent *event)
virtual bool mouseReleaseEvent (QMouseEvent *event)
void setCurrentTool (AbstractTool *tool)
virtual bool wheelEvent (QWheelEvent *event)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void handleMessage (const QByteArray &message)
Private Functions
void animationPausedChangeRequested (bool paused)
void animationSpeedChangeRequested (qreal factor)
Properties
bool m_animationPaused
AbstractTool * m_currentTool
QDeclarativeInspectorService * m_debugService
bool m_designModeBehavior
bool m_showAppOnTop
qreal m_slowDownFactor
QHash< int, QString > m_stringIdForObjectId
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 68 of file abstractviewinspector.h.
Constructors and Destructors
AbstractViewInspector()
QmlJSDebugger::AbstractViewInspector::AbstractViewInspector (QObject * parent = 0) explicit
Definition at line 58 of file abstractviewinspector.cpp.
                                                             :
     QObject(parent),
     m_currentTool(0),
     m_showAppOnTop(false),
     m_designModeBehavior(false),
     m_animationPaused(false),
     m_slowDownFactor(1.0),
     m_debugService(0)
 {
     m_debugService = QDeclarativeInspectorService::instance();
     connect(m_debugService, SIGNAL(gotMessage(QByteArray)),
             this, SLOT(handleMessage(QByteArray)));
 }
Functions
animationPaused()
bool QmlJSDebugger::AbstractViewInspector::animationPaused () const inline
Definition at line 96 of file abstractviewinspector.h.
Referenced by keyReleaseEvent().
 { return m_animationPaused; }
animationPausedChanged
void QmlJSDebugger::AbstractViewInspector::animationPausedChanged (bool paused) signal
Referenced by animationPausedChangeRequested(), and slowDownFactor().
animationPausedChangeRequested()
void QmlJSDebugger::AbstractViewInspector::animationPausedChangeRequested (bool paused) private
Definition at line 140 of file abstractviewinspector.cpp.
Referenced by handleMessage(), setAnimationPaused(), and setCurrentTool().
 {
     if (m_animationPaused != paused) {
         m_animationPaused = paused;
         emit animationPausedChanged(paused);
     }
     const float effectiveFactor = paused ? 0 : m_slowDownFactor;
     QDeclarativeDebugHelper::setAnimationSlowDownFactor(effectiveFactor);
 }
animationSpeedChanged
void QmlJSDebugger::AbstractViewInspector::animationSpeedChanged (qreal factor) signal
Referenced by animationSpeedChangeRequested(), and slowDownFactor().
animationSpeedChangeRequested()
void QmlJSDebugger::AbstractViewInspector::animationSpeedChangeRequested (qreal factor) private
Definition at line 129 of file abstractviewinspector.cpp.
Referenced by handleMessage(), setAnimationSpeed(), and setCurrentTool().
 {
     if (m_slowDownFactor != factor) {
         m_slowDownFactor = factor;
         emit animationSpeedChanged(factor);
     }
     const float effectiveFactor = m_animationPaused ? 0 : factor;
     QDeclarativeDebugHelper::setAnimationSlowDownFactor(effectiveFactor);
 }
changeCurrentObjects()
virtual void QmlJSDebugger::AbstractViewInspector::changeCurrentObjects (const QList< QObject *> & objects) pure virtual
Implemented in QmlJSDebugger::QDeclarativeViewInspector.
Referenced by handleMessage().
changeToColorPickerTool
void QmlJSDebugger::AbstractViewInspector::changeToColorPickerTool () slot
Definition at line 171 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     changeTool(InspectorProtocol::ColorPickerTool);
 }
changeToMarqueeSelectTool
void QmlJSDebugger::AbstractViewInspector::changeToMarqueeSelectTool () slot
Definition at line 186 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     changeTool(InspectorProtocol::SelectMarqueeTool);
 }
changeTool()
virtual void QmlJSDebugger::AbstractViewInspector::changeTool (InspectorProtocol::Tool tool) pure virtual
Implemented in QmlJSDebugger::QDeclarativeViewInspector.
Referenced by changeToColorPickerTool(), changeToMarqueeSelectTool(), changeToSingleSelectTool(), changeToZoomTool(), handleMessage(), and keyReleaseEvent().
changeToSingleSelectTool
void QmlJSDebugger::AbstractViewInspector::changeToSingleSelectTool () slot
Definition at line 181 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     changeTool(InspectorProtocol::SelectTool);
 }
changeToZoomTool
void QmlJSDebugger::AbstractViewInspector::changeToZoomTool () slot
Definition at line 176 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     changeTool(InspectorProtocol::ZoomTool);
 }
clearComponentCache()
void QmlJSDebugger::AbstractViewInspector::clearComponentCache ()
Definition at line 95 of file abstractviewinspector.cpp.
Referenced by handleMessage().
 {
     declarativeEngine()->clearComponentCache();
 }
colorPickerActivated
void QmlJSDebugger::AbstractViewInspector::colorPickerActivated () signal
Referenced by slowDownFactor().
createQmlObject()
void QmlJSDebugger::AbstractViewInspector::createQmlObject (const QString & qml, QObject * parent, const QStringList & importList, const QString & filename = QString())
Definition at line 72 of file abstractviewinspector.cpp.
Referenced by handleMessage().
 {
     if (!parent)
         return;
     QString imports;
     foreach (const QString &s, importList) {
         imports += s;
         imports += QLatin1Char('\n');
     }
     QDeclarativeContext *parentContext = declarativeEngine()->contextForObject(parent);
     QDeclarativeComponent component(declarativeEngine());
     QByteArray constructedQml = QString(imports + qml).toLatin1();
     component.setData(constructedQml, QUrl::fromLocalFile(filename));
     QObject *newObject = component.create(parentContext);
     if (newObject)
         reparentQmlObject(newObject, parent);
 }
currentTool()
AbstractTool* QmlJSDebugger::AbstractViewInspector::currentTool () const inline protected
Definition at line 149 of file abstractviewinspector.h.
Referenced by QmlJSDebugger::QDeclarativeViewInspector::currentTool().
 { return m_currentTool; }
declarativeEngine()
virtual QDeclarativeEngine* QmlJSDebugger::AbstractViewInspector::declarativeEngine () const pure virtual
Implemented in QmlJSDebugger::QDeclarativeViewInspector.
Referenced by clearComponentCache(), and createQmlObject().
designModeBehavior()
bool QmlJSDebugger::AbstractViewInspector::designModeBehavior () const inline
Definition at line 94 of file abstractviewinspector.h.
Referenced by QmlJSDebugger::QDeclarativeViewInspector::changeCurrentObjects(), and eventFilter().
 { return m_designModeBehavior; }
designModeBehaviorChanged
void QmlJSDebugger::AbstractViewInspector::designModeBehaviorChanged (bool inDesignMode) signal
Referenced by setDesignModeBehavior(), and slowDownFactor().
eventFilter()
bool QmlJSDebugger::AbstractViewInspector::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Reimplemented in QmlJSDebugger::QDeclarativeViewInspector.
Definition at line 191 of file abstractviewinspector.cpp.
Referenced by QmlJSDebugger::QDeclarativeViewInspector::eventFilter(), and slowDownFactor().
 {
     if (!designModeBehavior())
         return QObject::eventFilter(obj, event);
     switch (event->type()) {
     case QEvent::Leave:
         if (leaveEvent(event))
             return true;
         break;
     case QEvent::MouseButtonPress:
         if (mousePressEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
     case QEvent::MouseMove:
         if (mouseMoveEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
     case QEvent::MouseButtonRelease:
         if (mouseReleaseEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
     case QEvent::KeyPress:
         if (keyPressEvent(static_cast<QKeyEvent*>(event)))
             return true;
         break;
     case QEvent::KeyRelease:
         if (keyReleaseEvent(static_cast<QKeyEvent*>(event)))
             return true;
         break;
     case QEvent::MouseButtonDblClick:
         if (mouseDoubleClickEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
     case QEvent::Wheel:
         if (wheelEvent(static_cast<QWheelEvent*>(event)))
             return true;
         break;
     default:
         break;
     }
     return QObject::eventFilter(obj, event);
 }
handleMessage
void QmlJSDebugger::AbstractViewInspector::handleMessage (const QByteArray & message) private slot
Definition at line 309 of file abstractviewinspector.cpp.
Referenced by AbstractViewInspector(), and setCurrentTool().
 {
     QDataStream ds(message);
     InspectorProtocol::Message type;
     ds >> type;
     switch (type) {
     case InspectorProtocol::SetCurrentObjects: {
         int itemCount = 0;
         ds >> itemCount;
         QList<QObject*> selectedObjects;
         for (int i = 0; i < itemCount; ++i) {
             int debugId = -1;
             ds >> debugId;
             if (QObject *obj = QDeclarativeDebugService::objectForId(debugId))
                 selectedObjects << obj;
         }
         changeCurrentObjects(selectedObjects);
         break;
     }
     case InspectorProtocol::Reload: {
         reloadView();
         break;
     }
     case InspectorProtocol::SetAnimationSpeed: {
         qreal speed;
         ds >> speed;
         animationSpeedChangeRequested(speed);
         break;
     }
     case InspectorProtocol::SetAnimationPaused: {
         bool paused;
         ds >> paused;
         animationPausedChangeRequested(paused);
         break;
     }
     case InspectorProtocol::ChangeTool: {
         InspectorProtocol::Tool tool;
         ds >> tool;
         changeTool(tool);
         break;
     }
     case InspectorProtocol::SetDesignMode: {
         bool inDesignMode;
         ds >> inDesignMode;
         setDesignModeBehavior(inDesignMode);
         break;
     }
     case InspectorProtocol::ShowAppOnTop: {
         bool showOnTop;
         ds >> showOnTop;
         setShowAppOnTop(showOnTop);
         break;
     }
     case InspectorProtocol::CreateObject: {
         QString qml;
         int parentId;
         QString filename;
         QStringList imports;
         ds >> qml >> parentId >> imports >> filename;
         createQmlObject(qml, QDeclarativeDebugService::objectForId(parentId),
                         imports, filename);
         break;
     }
     case InspectorProtocol::DestroyObject: {
         int debugId;
         ds >> debugId;
         if (QObject *obj = QDeclarativeDebugService::objectForId(debugId))
             obj->deleteLater();
         break;
     }
     case InspectorProtocol::MoveObject: {
         int debugId, newParent;
         ds >> debugId >> newParent;
         reparentQmlObject(QDeclarativeDebugService::objectForId(debugId),
                           QDeclarativeDebugService::objectForId(newParent));
         break;
     }
     case InspectorProtocol::ObjectIdList: {
         int itemCount;
         ds >> itemCount;
         m_stringIdForObjectId.clear();
         for (int i = 0; i < itemCount; ++i) {
             int itemDebugId;
             QString itemIdString;
             ds >> itemDebugId
                >> itemIdString;
             m_stringIdForObjectId.insert(itemDebugId, itemIdString);
         }
         break;
     }
     case InspectorProtocol::ClearComponentCache: {
         clearComponentCache();
         break;
     }
     default:
         qWarning() << "Warning: Not handling message:" << type;
     }
 }
idStringForObject()
QString QmlJSDebugger::AbstractViewInspector::idStringForObject (QObject * obj) const
Definition at line 504 of file abstractviewinspector.cpp.
Referenced by slowDownFactor(), and QmlJSDebugger::AbstractLiveEditTool::titleForItem().
 {
     const int id = QDeclarativeDebugService::idForObject(obj);
     return m_stringIdForObjectId.value(id);
 }
keyPressEvent()
bool QmlJSDebugger::AbstractViewInspector::keyPressEvent (QKeyEvent * event) protected virtual
Definition at line 264 of file abstractviewinspector.cpp.
Referenced by eventFilter(), and slowDownFactor().
 {
     m_currentTool->keyPressEvent(event);
     return true;
 }
keyReleaseEvent()
bool QmlJSDebugger::AbstractViewInspector::keyReleaseEvent (QKeyEvent * keyEvent) protected virtual
Definition at line 270 of file abstractviewinspector.cpp.
Referenced by eventFilter(), and slowDownFactor().
 {
     switch (event->key()) {
     case Qt::Key_V:
         changeTool(InspectorProtocol::SelectTool);
         break;
 // disabled because multiselection does not do anything useful without design mode
 //    case Qt::Key_M:
 //        changeTool(InspectorProtocol::SelectMarqueeTool);
 //        break;
     case Qt::Key_I:
         changeTool(InspectorProtocol::ColorPickerTool);
         break;
     case Qt::Key_Z:
         changeTool(InspectorProtocol::ZoomTool);
         break;
     case Qt::Key_Space:
         setAnimationPaused(!animationPaused());
         break;
     default:
         break;
     }
     m_currentTool->keyReleaseEvent(event);
     return true;
 }
leaveEvent()
bool QmlJSDebugger::AbstractViewInspector::leaveEvent (QEvent * event) protected virtual
Reimplemented in QmlJSDebugger::QDeclarativeViewInspector.
Definition at line 236 of file abstractviewinspector.cpp.
Referenced by eventFilter(), QmlJSDebugger::QDeclarativeViewInspector::leaveEvent(), and slowDownFactor().
 {
     m_currentTool->leaveEvent(event);
     return true;
 }
marqueeSelectToolActivated
void QmlJSDebugger::AbstractViewInspector::marqueeSelectToolActivated () signal
Referenced by slowDownFactor().
mouseDoubleClickEvent()
bool QmlJSDebugger::AbstractViewInspector::mouseDoubleClickEvent (QMouseEvent * event) protected virtual
Definition at line 297 of file abstractviewinspector.cpp.
Referenced by eventFilter(), and slowDownFactor().
 {
     m_currentTool->mouseDoubleClickEvent(event);
     return true;
 }
mouseMoveEvent()
bool QmlJSDebugger::AbstractViewInspector::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented in QmlJSDebugger::QDeclarativeViewInspector.
Definition at line 248 of file abstractviewinspector.cpp.
Referenced by eventFilter(), QmlJSDebugger::QDeclarativeViewInspector::mouseMoveEvent(), and slowDownFactor().
 {
     if (event->buttons()) {
         m_currentTool->mouseMoveEvent(event);
     } else {
         m_currentTool->hoverMoveEvent(event);
     }
     return true;
 }
mousePressEvent()
bool QmlJSDebugger::AbstractViewInspector::mousePressEvent (QMouseEvent * event) protected virtual
Definition at line 242 of file abstractviewinspector.cpp.
Referenced by eventFilter(), and slowDownFactor().
 {
     m_currentTool->mousePressEvent(event);
     return true;
 }
mouseReleaseEvent()
bool QmlJSDebugger::AbstractViewInspector::mouseReleaseEvent (QMouseEvent * event) protected virtual
Definition at line 258 of file abstractviewinspector.cpp.
Referenced by eventFilter(), and slowDownFactor().
 {
     m_currentTool->mouseReleaseEvent(event);
     return true;
 }
reloadRequested
void QmlJSDebugger::AbstractViewInspector::reloadRequested () signal
Referenced by QmlJSDebugger::QDeclarativeViewInspector::reloadView(), and slowDownFactor().
reloadView()
virtual void QmlJSDebugger::AbstractViewInspector::reloadView () pure virtual
Implemented in QmlJSDebugger::QDeclarativeViewInspector.
Referenced by handleMessage().
reparentQmlObject()
virtual void QmlJSDebugger::AbstractViewInspector::reparentQmlObject (QObject * object, QObject * newParent) pure virtual
Implemented in QmlJSDebugger::QDeclarativeViewInspector.
Referenced by createQmlObject(), and handleMessage().
selectedColorChanged
void QmlJSDebugger::AbstractViewInspector::selectedColorChanged (const QColor & color) signal
Referenced by QmlJSDebugger::QDeclarativeViewInspector::QDeclarativeViewInspector(), and slowDownFactor().
selectToolActivated
void QmlJSDebugger::AbstractViewInspector::selectToolActivated () signal
Referenced by slowDownFactor().
sendAnimationPaused()
void QmlJSDebugger::AbstractViewInspector::sendAnimationPaused (bool paused)
Definition at line 462 of file abstractviewinspector.cpp.
Referenced by setAnimationPaused(), and slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::AnimationPausedChanged
        << paused;
     m_debugService->sendMessage(message);
 }
sendAnimationSpeed()
void QmlJSDebugger::AbstractViewInspector::sendAnimationSpeed (qreal slowDownFactor)
Definition at line 451 of file abstractviewinspector.cpp.
Referenced by setAnimationSpeed(), and slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::AnimationSpeedChanged
        << slowDownFactor;
     m_debugService->sendMessage(message);
 }
sendColorChanged
void QmlJSDebugger::AbstractViewInspector::sendColorChanged (const QColor & color) slot
Definition at line 493 of file abstractviewinspector.cpp.
Referenced by QmlJSDebugger::QDeclarativeViewInspector::QDeclarativeViewInspector(), and slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::ColorChanged
        << color;
     m_debugService->sendMessage(message);
 }
sendCurrentObjects()
void QmlJSDebugger::AbstractViewInspector::sendCurrentObjects (const QList< QObject *> & objects)
Definition at line 424 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::CurrentObjectsChanged
        << objects.length();
     foreach (QObject *object, objects) {
         int id = QDeclarativeDebugService::idForObject(object);
         ds << id;
     }
     m_debugService->sendMessage(message);
 }
sendCurrentTool()
void QmlJSDebugger::AbstractViewInspector::sendCurrentTool (Constants::DesignTool toolId)
Definition at line 440 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::ToolChanged
        << toolId;
     m_debugService->sendMessage(message);
 }
sendDesignModeBehavior
void QmlJSDebugger::AbstractViewInspector::sendDesignModeBehavior (bool inDesignMode) slot
Definition at line 413 of file abstractviewinspector.cpp.
Referenced by setDesignModeBehavior(), and slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::SetDesignMode
        << inDesignMode;
     m_debugService->sendMessage(message);
 }
sendReloaded()
void QmlJSDebugger::AbstractViewInspector::sendReloaded ()
Definition at line 473 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::Reloaded;
     m_debugService->sendMessage(message);
 }
sendShowAppOnTop()
void QmlJSDebugger::AbstractViewInspector::sendShowAppOnTop (bool showAppOnTop)
Definition at line 483 of file abstractviewinspector.cpp.
Referenced by setShowAppOnTop(), and slowDownFactor().
 {
     QByteArray message;
     QDataStream ds(&message, QIODevice::WriteOnly);
     ds << InspectorProtocol::ShowAppOnTop << showAppOnTop;
     m_debugService->sendMessage(message);
 }
setAnimationPaused
void QmlJSDebugger::AbstractViewInspector::setAnimationPaused (bool paused) slot
Definition at line 120 of file abstractviewinspector.cpp.
Referenced by keyReleaseEvent(), and slowDownFactor().
 {
     if (m_animationPaused == paused)
         return;
     animationPausedChangeRequested(paused);
     sendAnimationPaused(paused);
 }
setAnimationSpeed
void QmlJSDebugger::AbstractViewInspector::setAnimationSpeed (qreal factor) slot
Definition at line 110 of file abstractviewinspector.cpp.
Referenced by slowDownFactor().
 {
     Q_ASSERT(slowDownFactor > 0);
     if (m_slowDownFactor == slowDownFactor)
         return;
     animationSpeedChangeRequested(slowDownFactor);
     sendAnimationSpeed(slowDownFactor);
 }
setCurrentTool()
void QmlJSDebugger::AbstractViewInspector::setCurrentTool (AbstractTool * tool) inline protected
Definition at line 150 of file abstractviewinspector.h.
Referenced by QmlJSDebugger::QDeclarativeViewInspector::QDeclarativeViewInspector().
 { m_currentTool = tool; }
setDesignModeBehavior
void QmlJSDebugger::AbstractViewInspector::setDesignModeBehavior (bool value) virtual slot
Definition at line 100 of file abstractviewinspector.cpp.
Referenced by handleMessage(), and slowDownFactor().
 {
     if (m_designModeBehavior == value)
         return;
     m_designModeBehavior = value;
     emit designModeBehaviorChanged(value);
     sendDesignModeBehavior(value);
 }
setShowAppOnTop
void QmlJSDebugger::AbstractViewInspector::setShowAppOnTop (bool appOnTop) slot
Definition at line 151 of file abstractviewinspector.cpp.
Referenced by handleMessage(), and slowDownFactor().
 {
     if (viewWidget()) {
         QWidget *window = viewWidget()->window();
         Qt::WindowFlags flags = window->windowFlags();
         if (appOnTop)
             flags |= Qt::WindowStaysOnTopHint;
         else
             flags &= ~Qt::WindowStaysOnTopHint;
         window->setWindowFlags(flags);
         window->show();
     }
     m_showAppOnTop = appOnTop;
     sendShowAppOnTop(appOnTop);
     emit showAppOnTopChanged(appOnTop);
 }
showAppOnTop()
bool QmlJSDebugger::AbstractViewInspector::showAppOnTop () const inline
Definition at line 93 of file abstractviewinspector.h.
Referenced by sendShowAppOnTop(), and slowDownFactor().
 { return m_showAppOnTop; }
showAppOnTopChanged
void QmlJSDebugger::AbstractViewInspector::showAppOnTopChanged (bool showAppOnTop) signal
Referenced by setShowAppOnTop(), and slowDownFactor().
slowDownFactor()
qreal QmlJSDebugger::AbstractViewInspector::slowDownFactor () const inline
Definition at line 97 of file abstractviewinspector.h.
Referenced by sendAnimationSpeed().
 { return m_slowDownFactor; }
viewWidget()
virtual QWidget* QmlJSDebugger::AbstractViewInspector::viewWidget () const pure virtual
Implemented in QmlJSDebugger::QDeclarativeViewInspector.
Referenced by setShowAppOnTop().
wheelEvent()
bool QmlJSDebugger::AbstractViewInspector::wheelEvent (QWheelEvent * event) protected virtual
Definition at line 303 of file abstractviewinspector.cpp.
Referenced by eventFilter(), and slowDownFactor().
 {
     m_currentTool->wheelEvent(event);
     return true;
 }
zoomToolActivated
void QmlJSDebugger::AbstractViewInspector::zoomToolActivated () signal
Referenced by slowDownFactor().
Properties
m_animationPaused
bool QmlJSDebugger::AbstractViewInspector::m_animationPaused private
Definition at line 164 of file abstractviewinspector.h.
Referenced by animationPaused(), animationPausedChangeRequested(), animationSpeedChangeRequested(), and setAnimationPaused().
m_currentTool
AbstractTool* QmlJSDebugger::AbstractViewInspector::m_currentTool private
Definition at line 159 of file abstractviewinspector.h.
Referenced by currentTool(), keyPressEvent(), keyReleaseEvent(), leaveEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), setCurrentTool(), and wheelEvent().
m_debugService
QDeclarativeInspectorService* QmlJSDebugger::AbstractViewInspector::m_debugService private
Definition at line 168 of file abstractviewinspector.h.
Referenced by AbstractViewInspector(), sendAnimationPaused(), sendAnimationSpeed(), sendColorChanged(), sendCurrentObjects(), sendCurrentTool(), sendDesignModeBehavior(), sendReloaded(), and sendShowAppOnTop().
m_designModeBehavior
bool QmlJSDebugger::AbstractViewInspector::m_designModeBehavior private
Definition at line 162 of file abstractviewinspector.h.
Referenced by designModeBehavior(), and setDesignModeBehavior().
m_showAppOnTop
bool QmlJSDebugger::AbstractViewInspector::m_showAppOnTop private
Definition at line 161 of file abstractviewinspector.h.
Referenced by setShowAppOnTop(), and showAppOnTop().
m_slowDownFactor
qreal QmlJSDebugger::AbstractViewInspector::m_slowDownFactor private
Definition at line 165 of file abstractviewinspector.h.
Referenced by animationPausedChangeRequested(), animationSpeedChangeRequested(), setAnimationSpeed(), and slowDownFactor().
m_stringIdForObjectId
QHash<int, QString> QmlJSDebugger::AbstractViewInspector::m_stringIdForObjectId private
Definition at line 167 of file abstractviewinspector.h.
Referenced by handleMessage(), and idStringForObject().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/abstractviewinspector.h
/src/plugins/qmltooling/qmldbg_inspector/abstractviewinspector.cpp