Qt 4.8: QSystemSemaphorePrivate Class Reference
QSystemSemaphorePrivate Class Reference
#include <qsystemsemaphore_p.h>
Public Functions
void cleanHandle ()
HANDLE handle (QSystemSemaphore::AccessMode mode=QSystemSemaphore::Open)
QString makeKeyFileName () const
bool modifySemaphore (int count)
QSystemSemaphorePrivate ()
void setErrorString (const QString &function)
Public Variables
QSystemSemaphore::SystemSemaphoreError error
QString errorString
QString fileName
int initialValue
QString key
HANDLE semaphore
HANDLE semaphoreLock
Detailed Description
Definition at line 74 of file qsystemsemaphore_p.h.
Constructors and Destructors
QSystemSemaphorePrivate()
QSystemSemaphorePrivate::QSystemSemaphorePrivate ()
Definition at line 71 of file qsystemsemaphore_unix.cpp.
                                                  :
 #ifndef QT_POSIX_IPC
     unix_key(-1), semaphore(-1), createdFile(false),
 #else
     semaphore(SEM_FAILED),
 #endif
     createdSemaphore(false), error(QSystemSemaphore::NoError)
 {
 }
Functions
cleanHandle()
void QSystemSemaphorePrivate::cleanHandle ()
Warning
This function is not part of the public interface.
Clean up the semaphore
Definition at line 242 of file qsystemsemaphore_unix.cpp.
Referenced by handle(), makeKeyFileName(), modifySemaphore(), QSystemSemaphore::setKey(), and QSystemSemaphore::~QSystemSemaphore().
 {
 #ifndef QT_POSIX_IPC
     unix_key = -1;
     // remove the file if we made it
     if (createdFile) {
         QFile::remove(fileName);
         createdFile = false;
     }
     if (createdSemaphore) {
         if (-1 != semaphore) {
             if (-1 == semctl(semaphore, 0, IPC_RMID, 0)) {
                 setErrorString(QLatin1String("QSystemSemaphore::cleanHandle"));
 #ifdef QSYSTEMSEMAPHORE_DEBUG
                 qDebug("QSystemSemaphore::cleanHandle semctl failed.");
 #endif
             }
             semaphore = -1;
         }
         createdSemaphore = false;
     }
 #else
     if (semaphore != SEM_FAILED) {
         if (sem_close(semaphore) == -1) {
             setErrorString(QLatin1String("QSystemSemaphore::cleanHandle (sem_close)"));
 #ifdef QSYSTEMSEMAPHORE_DEBUG
             qDebug() << QLatin1String("QSystemSemaphore::cleanHandle sem_close failed.");
 #endif
         }
         semaphore = SEM_FAILED;
     }
     if (createdSemaphore) {
         if (sem_unlink(QFile::encodeName(fileName).constData()) == -1 && errno != ENOENT) {
             setErrorString(QLatin1String("QSystemSemaphore::cleanHandle (sem_unlink)"));
 #ifdef QSYSTEMSEMAPHORE_DEBUG
             qDebug() << QLatin1String("QSystemSemaphore::cleanHandle sem_unlink failed.");
 #endif
         }
         createdSemaphore = false;
     }
 #endif // QT_POSIX_IPC
 }
handle()
HANDLE QSystemSemaphorePrivate::handle (QSystemSemaphore::AccessMode mode = QSystemSemaphore::Open)
Warning
This function is not part of the public interface.
Initialise the semaphore
Definition at line 127 of file qsystemsemaphore_unix.cpp.
Referenced by makeKeyFileName(), modifySemaphore(), and QSystemSemaphore::setKey().
 {
     if (-1 != unix_key)
         return unix_key;
     if (key.isEmpty()) {
         errorString = QCoreApplication::tr("%1: key is empty", "QSystemSemaphore").arg(QLatin1String("QSystemSemaphore::handle"));
         error = QSystemSemaphore::KeyError;
         return -1;
     }
     // ftok requires that an actual file exists somewhere
     int built = QSharedMemoryPrivate::createUnixKeyFile(fileName);
     if (-1 == built) {
         errorString = QCoreApplication::tr("%1: unable to make key", "QSystemSemaphore").arg(QLatin1String("QSystemSemaphore::handle"));
         error = QSystemSemaphore::KeyError;
         return -1;
     }
     createdFile = (1 == built);
     // Get the unix key for the created file
     unix_key = ftok(QFile::encodeName(fileName).constData(), 'Q');
     if (-1 == unix_key) {
         errorString = QCoreApplication::tr("%1: ftok failed", "QSystemSemaphore").arg(QLatin1String("QSystemSemaphore::handle"));
         error = QSystemSemaphore::KeyError;
         return -1;
     }
     // Get semaphore
     semaphore = semget(unix_key, 1, 0600 | IPC_CREAT | IPC_EXCL);
     if (-1 == semaphore) {
         if (errno == EEXIST)
             semaphore = semget(unix_key, 1, 0600 | IPC_CREAT);
         if (-1 == semaphore) {
             setErrorString(QLatin1String("QSystemSemaphore::handle"));
             cleanHandle();
             return -1;
         }
         if (mode == QSystemSemaphore::Create) {
             createdSemaphore = true;
             createdFile = true;
         }
     } else {
         createdSemaphore = true;
         // Force cleanup of file, it is possible that it can be left over from a crash
         createdFile = true;
     }
     // Created semaphore so initialize its value.
     if (createdSemaphore && initialValue >= 0) {
         qt_semun init_op;
         init_op.val = initialValue;
         if (-1 == semctl(semaphore, 0, SETVAL, init_op)) {
             setErrorString(QLatin1String("QSystemSemaphore::handle"));
             cleanHandle();
             return -1;
         }
     }
     return unix_key;
 }
makeKeyFileName()
QString QSystemSemaphorePrivate::makeKeyFileName () const inline
Definition at line 79 of file qsystemsemaphore_p.h.
Referenced by QSystemSemaphore::setKey().
     {
         return QSharedMemoryPrivate::makePlatformSafeKey(key, QLatin1String("qipc_systemsem_"));
     }
modifySemaphore()
bool QSystemSemaphorePrivate::modifySemaphore (int count)
Warning
This function is not part of the public interface.
Definition at line 291 of file qsystemsemaphore_unix.cpp.
Referenced by QSystemSemaphore::acquire(), makeKeyFileName(), and QSystemSemaphore::release().
 {
 #ifndef QT_POSIX_IPC
     if (-1 == handle())
         return false;
     struct sembuf operation;
     operation.sem_num = 0;
     operation.sem_op = count;
     operation.sem_flg = SEM_UNDO;
     register int res;
     EINTR_LOOP(res, semop(semaphore, &operation, 1));
     if (-1 == res) {
         // If the semaphore was removed be nice and create it and then modifySemaphore again
         if (errno == EINVAL || errno == EIDRM) {
             semaphore = -1;
             cleanHandle();
             handle();
             return modifySemaphore(count);
         }
         setErrorString(QLatin1String("QSystemSemaphore::modifySemaphore"));
 #ifdef QSYSTEMSEMAPHORE_DEBUG
         qDebug() << QLatin1String("QSystemSemaphore::modify failed") << count << semctl(semaphore, 0, GETVAL) << errno << EIDRM << EINVAL;
 #endif
         return false;
     }
 #else
     if (!handle())
         return false;
     if (count > 0) {
         int cnt = count;
         do {
             if (sem_post(semaphore) == -1) {
                 setErrorString(QLatin1String("QSystemSemaphore::modifySemaphore (sem_post)"));
 #ifdef QSYSTEMSEMAPHORE_DEBUG
                 qDebug() << QLatin1String("QSystemSemaphore::modify sem_post failed") << count << errno;
 #endif
                 // rollback changes to preserve the SysV semaphore behavior
                 for ( ; cnt < count; ++cnt) {
                     register int res;
                     EINTR_LOOP(res, sem_wait(semaphore));
                 }
                 return false;
             }
             --cnt;
         } while (cnt > 0);
     } else {
         register int res;
         EINTR_LOOP(res, sem_wait(semaphore));
         if (res == -1) {
             // If the semaphore was removed be nice and create it and then modifySemaphore again
             if (errno == EINVAL || errno == EIDRM) {
                 semaphore = SEM_FAILED;
                 return modifySemaphore(count);
             }
             setErrorString(QLatin1String("QSystemSemaphore::modifySemaphore (sem_wait)"));
 #ifdef QSYSTEMSEMAPHORE_DEBUG
             qDebug() << QLatin1String("QSystemSemaphore::modify sem_wait failed") << count << errno;
 #endif
             return false;
         }
     }
 #endif // QT_POSIX_IPC
     return true;
 }
setErrorString()
void QSystemSemaphorePrivate::setErrorString (const QString & function)
Definition at line 81 of file qsystemsemaphore_unix.cpp.
Referenced by cleanHandle(), handle(), makeKeyFileName(), and modifySemaphore().
 {
     // EINVAL is handled in functions so they can give better error strings
     switch (errno) {
     case EPERM:
     case EACCES:
         errorString = QCoreApplication::translate("QSystemSemaphore", "%1: permission denied").arg(function);
         error = QSystemSemaphore::PermissionDenied;
         break;
     case EEXIST:
         errorString = QCoreApplication::translate("QSystemSemaphore", "%1: already exists").arg(function);
         error = QSystemSemaphore::AlreadyExists;
         break;
     case ENOENT:
         errorString = QCoreApplication::translate("QSystemSemaphore", "%1: does not exist").arg(function);
         error = QSystemSemaphore::NotFound;
         break;
     case ERANGE:
     case ENOMEM:
     case ENOSPC:
     case EMFILE:
     case ENFILE:
     case EOVERFLOW:
         errorString = QCoreApplication::translate("QSystemSemaphore", "%1: out of resources").arg(function);
         error = QSystemSemaphore::OutOfResources;
         break;
     case ENAMETOOLONG:
         errorString = QCoreApplication::translate("QSystemSemaphore", "%1: name error").arg(function);
         error = QSystemSemaphore::KeyError;
         break;
     default:
         errorString = QCoreApplication::translate("QSystemSemaphore", "%1: unknown error %2").arg(function).arg(errno);
         error = QSystemSemaphore::UnknownError;
 #ifdef QSYSTEMSEMAPHORE_DEBUG
         qDebug() << errorString << "key" << key << "errno" << errno << EINVAL;
 #endif
         break;
     }
 }
Properties
error
QSystemSemaphore::SystemSemaphoreError QSystemSemaphorePrivate::error
Definition at line 118 of file qsystemsemaphore_p.h.
Referenced by QSystemSemaphore::error(), handle(), setErrorString(), and QSystemSemaphore::setKey().
errorString
QString QSystemSemaphorePrivate::errorString
Definition at line 117 of file qsystemsemaphore_p.h.
Referenced by QSystemSemaphore::errorString(), handle(), setErrorString(), and QSystemSemaphore::setKey().
fileName
QString QSystemSemaphorePrivate::fileName
Definition at line 101 of file qsystemsemaphore_p.h.
Referenced by cleanHandle(), handle(), and QSystemSemaphore::setKey().
initialValue
int QSystemSemaphorePrivate::initialValue
Definition at line 102 of file qsystemsemaphore_p.h.
Referenced by handle(), and QSystemSemaphore::setKey().
key
QString QSystemSemaphorePrivate::key
Definition at line 100 of file qsystemsemaphore_p.h.
Referenced by handle(), QSystemSemaphore::key(), makeKeyFileName(), setErrorString(), and QSystemSemaphore::setKey().
semaphore
HANDLE QSystemSemaphorePrivate::semaphore
Definition at line 104 of file qsystemsemaphore_p.h.
Referenced by cleanHandle(), handle(), and modifySemaphore().
semaphoreLock
HANDLE QSystemSemaphorePrivate::semaphoreLock
Definition at line 105 of file qsystemsemaphore_p.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qsystemsemaphore_p.h
/src/corelib/kernel/qsystemsemaphore_unix.cpp
/src/corelib/kernel/qsystemsemaphore_win.cpp