Qt 4.8: QPlatformScreen Class Reference
QPlatformScreen Class Reference abstract
The QPlatformScreen class provides an abstraction for visual displays.
#include <qplatformscreen_qpa.h>
Public Functions
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual int depth () const =0
Reimplement in subclass to return current depth of the screen.
virtual QImage::Format format () const =0
Reimplement in subclass to return the image format which corresponds to the screen format.
virtual QRect geometry () const =0
Reimplement in subclass to return the pixel geometry of the screen.
virtual QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
virtual void setDirty (const QRect &)
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPlatformScreen class provides an abstraction for visual displays.
Since
4.8
Warning
This function is not part of the public interface. This function is under development and subject to change.
Many window systems has support for retrieving information on the attached displays. To be able to query the display QPA uses QPlatformScreen. Qt its self is most dependent on the physicalSize() function, since this is the function it uses to calculate the dpi to use when converting point sizes to pixels sizes. However, this is unfortunate on some systems, as the native system fakes its dpi size.
QPlatformScreen is also used by the public api QDesktopWidget for information about the desktop.
Definition at line 62 of file qplatformscreen_qpa.h.
Constructors and Destructors
~QPlatformScreen()
virtual QPlatformScreen::~QPlatformScreen () inline virtual
Definition at line 66 of file qplatformscreen_qpa.h.
 { }
Functions
availableGeometry()
QRect QPlatformScreen::availableGeometry () const inline virtual
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
Reimplemented in QBBScreen.
Definition at line 69 of file qplatformscreen_qpa.h.
Referenced by QVFbWindowSurface::resize(), QEglFSWindow::setGeometry(), and QVFbWindow::setGeometry().
 {return geometry();}
depth()
int QPlatformScreen::depth () const pure virtual
Reimplement in subclass to return current depth of the screen.
Implemented in QFbScreen, QOpenKODEScreen, QBBScreen, QXlibScreen, QEglFSScreen, QDirectFbScreen, QXcbScreen, QCocoaScreen, QVFbScreen, QWaylandScreen, QUIKitScreen, and QMinimalScreen.
Referenced by effectiveState().
format()
QImage::Format QPlatformScreen::format () const pure virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implemented in QFbScreen, QOpenKODEScreen, QBBScreen, QXlibScreen, QEglFSScreen, QDirectFbScreen, QXcbScreen, QCocoaScreen, QVFbScreen, QWaylandScreen, QUIKitScreen, and QMinimalScreen.
Referenced by QWaylandShmWindowSurface::resize(), and QEglProperties::setPaintDeviceFormat().
geometry()
QRect QPlatformScreen::geometry () const pure virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implemented in QFbScreen, QOpenKODEScreen, QBBScreen, QXlibScreen, QEglFSScreen, QDirectFbScreen, QXcbScreen, QCocoaScreen, QVFbScreen, QWaylandScreen, QUIKitScreen, and QMinimalScreen.
Referenced by QPlatformSoftwareCursor::changeCursor(), QPlatformSoftwareCursor::drawCursor(), effectiveState(), QPlatformSoftwareCursor::getCurrentRect(), physicalSize(), QPlatformSoftwareCursor::pointerEvent(), qt_defaultDpiX(), qt_defaultDpiY(), and QDesktopWidgetPrivate::updateScreenList().
physicalSize()
QSize QPlatformScreen::physicalSize () const virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented in QFbScreen, QBBScreen, QXlibScreen, QDirectFbScreen, QXcbScreen, QCocoaScreen, QVFbScreen, and QUIKitScreen.
Definition at line 79 of file qplatformscreen_qpa.cpp.
Referenced by effectiveState(), QBBScreenEventHandler::handleTouchEvent(), qt_defaultDpiX(), and qt_defaultDpiY().
 {
     static const int dpi = 100;
     int width = geometry().width() / dpi * qreal(25.4) ;
     int height = geometry().height() / dpi * qreal(25.4) ;
     return QSize(width,height);
 }
platformScreenForWidget()
QPlatformScreen * QPlatformScreen::platformScreenForWidget (const QWidget * widget) static
Definition at line 88 of file qplatformscreen_qpa.cpp.
Referenced by effectiveState(), QBBScreenEventHandler::handleTouchEvent(), QWaylandNativeInterface::qPlatformScreenForWidget(), QXlibNativeInterface::qPlatformScreenForWidget(), QXcbNativeInterface::qPlatformScreenForWidget(), QUIKitWindow::QUIKitWindow(), QXcbWindow::QXcbWindow(), QXcbWindowSurface::QXcbWindowSurface(), QXcbWindowSurface::resize(), QWaylandShmWindowSurface::resize(), QXlibScreen::testLiteScreenForWidget(), toDfbScreen(), and QWaylandScreen::waylandScreenFromWidget().
 {
     QWidget *window = widget->window();
     QWidgetPrivate *windowPrivate = qt_widget_private(window);
     QTLWExtra * topData = windowPrivate->topData();
     QPlatformIntegration *integration =
             QApplicationPrivate::platformIntegration();
     return integration->screens()[topData->screenIndex];
 }
setDirty()
virtual void QPlatformScreen::setDirty (const QRect &) inline virtual
Reimplemented in QFbScreen, QLinuxFbScreen, QVFbScreen, QVNCScreen, and QVFbScreen.
Definition at line 74 of file qplatformscreen_qpa.h.
Referenced by QPlatformSoftwareCursor::setDirty().
 {}
topLevelAt()
QWidget * QPlatformScreen::topLevelAt (const QPoint & pos) const virtual
Return the given top level widget for a given position.
Default implementation retrieves a list of all top level widgets and finds the first widget which contains point pos
Reimplemented in QFbScreen.
Definition at line 56 of file qplatformscreen_qpa.cpp.
 {
     QWidgetList list = QApplication::topLevelWidgets();
     for (int i = list.size()-1; i >= 0; --i) {
         QWidget *w = list[i];
         //### mask is ignored
         if (w != QApplication::desktop() && w->isVisible() && w->geometry().contains(pos))
             return w;
     }
     return 0;
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qplatformscreen_qpa.h
/src/gui/kernel/qplatformscreen_qpa.cpp