Qt 4.8: QMaxHeap< T > Class Template Reference
QMaxHeap< T > Class Template Reference
Public Functions
bool empty () const
bool isEmpty () const
T pop ()
void push (const T &x)
QMaxHeap ()
int size () const
const T & top () const
Static Private Functions
static int left (int i)
static int parent (int i)
static int right (int i)
Properties
QDataBuffer< T > m_data
Detailed Description
template<class T>
class QMaxHeap< T >
Definition at line 532 of file qtriangulator.cpp.
Constructors and Destructors
QMaxHeap()
template<class T> QMaxHeap< T >::QMaxHeap () inline
Definition at line 535 of file qtriangulator.cpp.
 : m_data(0) {}
Functions
empty()
template<class T> bool QMaxHeap< T >::empty () const inline
Definition at line 537 of file qtriangulator.cpp.
 {return m_data.isEmpty();}
isEmpty()
template<class T> bool QMaxHeap< T >::isEmpty () const inline
Definition at line 538 of file qtriangulator.cpp.
 {return m_data.isEmpty();}
left()
template<class T> static int QMaxHeap< T >::left (int i) inline static private
Definition at line 544 of file qtriangulator.cpp.
Referenced by QMaxHeap< QTriangulator::ComplexToSimple::Intersection >::pop().
 {return 2 * i + 1;}
parent()
template<class T> static int QMaxHeap< T >::parent (int i) inline static private
Definition at line 543 of file qtriangulator.cpp.
Referenced by QMaxHeap< QTriangulator::ComplexToSimple::Intersection >::push().
 {return (i - 1) / 2;}
pop()
template<class T > T QMaxHeap< T >::pop ()
Definition at line 565 of file qtriangulator.cpp.
 {
     T result = m_data.first();
     T back = m_data.last();
     m_data.pop_back();
     if (!m_data.isEmpty()) {
         int current = 0;
         for (;;) {
             int left = QMaxHeap::left(current);
             int right = QMaxHeap::right(current);
             if (left >= m_data.size())
                 break;
             int greater = left;
             if (right < m_data.size() && m_data.at(left) < m_data.at(right))
                 greater = right;
             if (m_data.at(greater) < back)
                 break;
             m_data.at(current) = m_data.at(greater);
             current = greater;
         }
         m_data.at(current) = back;
     }
     return result;
 }
push()
template<class T> void QMaxHeap< T >::push (const T & x)
Definition at line 551 of file qtriangulator.cpp.
 {
     int current = m_data.size();
     int parent = QMaxHeap::parent(current);
     m_data.add(x);
     while (current != 0 && m_data.at(parent) < x) {
         m_data.at(current) = m_data.at(parent);
         current = parent;
         parent = QMaxHeap::parent(current);
     }
     m_data.at(current) = x;
 }
right()
template<class T> static int QMaxHeap< T >::right (int i) inline static private
Definition at line 545 of file qtriangulator.cpp.
Referenced by QMaxHeap< QTriangulator::ComplexToSimple::Intersection >::pop().
 {return 2 * i + 2;}
size()
template<class T> int QMaxHeap< T >::size () const inline
Definition at line 536 of file qtriangulator.cpp.
 {return m_data.size();}
top()
template<class T> const T& QMaxHeap< T >::top () const inline
Definition at line 541 of file qtriangulator.cpp.
 {return m_data.first();}
Properties
m_data
template<class T> QDataBuffer<T> QMaxHeap< T >::m_data private
Definition at line 547 of file qtriangulator.cpp.
The documentation for this class was generated from the following file:
/src/opengl/gl2paintengineex/qtriangulator.cpp