Qt 4.8: QDBusConnectionManager Class Reference
QDBusConnectionManager Class Reference
#include <qdbusconnectionmanager_p.h>
Public Functions
QDBusConnectionPrivate * connection (const QString &name) const
QDBusConnectionManager ()
void removeConnection (const QString &name)
QDBusConnectionPrivate * sender () const
void setConnection (const QString &name, QDBusConnectionPrivate *c)
void setSender (const QDBusConnectionPrivate *s)
~QDBusConnectionManager ()
Static Public Functions
static QDBusConnectionManager * instance ()
Public Variables
QMutex mutex
Properties
QHash< QString, QDBusConnectionPrivate * > connectionHash
QMutex senderMutex
QString senderName
Detailed Description
Definition at line 63 of file qdbusconnectionmanager_p.h.
Constructors and Destructors
QDBusConnectionManager()
QDBusConnectionManager::QDBusConnectionManager () inline
Definition at line 66 of file qdbusconnectionmanager_p.h.
 {}
~QDBusConnectionManager()
QDBusConnectionManager::~QDBusConnectionManager ()
Definition at line 97 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager().
 {
     for (QHash<QString, QDBusConnectionPrivate *>::const_iterator it = connectionHash.constBegin();
          it != connectionHash.constEnd(); ++it) {
         QDBusConnectionPrivate *d = it.value();
         if (!d->ref.deref())
             d->deleteYourself();
         else
             d->closeConnection();
     }
     connectionHash.clear();
 }
Functions
connection()
QDBusConnectionPrivate * QDBusConnectionManager::connection (const QString & name) const
Definition at line 78 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager().
 {
     return connectionHash.value(name, 0);
 }
instance()
QDBusConnectionManager * QDBusConnectionManager::instance () static
Definition at line 110 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager(), QDBusDefaultConnection::QDBusDefaultConnection(), qDBusNewConnection(), and QDBusServer::~QDBusServer().
 {
     return _q_manager();
 }
removeConnection()
void QDBusConnectionManager::removeConnection (const QString & name)
Definition at line 83 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager(), and QDBusServer::~QDBusServer().
 {
     QDBusConnectionPrivate *d = 0;
     d = connectionHash.take(name);
     if (d && !d->ref.deref())
         d->deleteYourself();
     // Static objects may be keeping the connection open.
     // However, it is harmless to have outstanding references to a connection that is
     // closing as long as those references will be soon dropped without being used.
     // ### Output a warning if connections are being used after they have been removed.
 }
sender()
QDBusConnectionPrivate * QDBusConnectionManager::sender () const
Definition at line 66 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager(), and QDBusConnection::sender().
 {
     QMutexLocker locker(&senderMutex);
     return connection(senderName);
 }
setConnection()
void QDBusConnectionManager::setConnection (const QString & name, QDBusConnectionPrivate * c)
Definition at line 120 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager(), and qDBusNewConnection().
 {
     connectionHash[name] = c;
     c->name = name;
 }
setSender()
void QDBusConnectionManager::setSender (const QDBusConnectionPrivate * s)
Definition at line 72 of file qdbusconnection.cpp.
Referenced by QDBusConnectionManager().
 {
     QMutexLocker locker(&senderMutex);
     senderName = (s ? s->name : QString());
 }
Properties
connectionHash
QHash<QString, QDBusConnectionPrivate *> QDBusConnectionManager::connectionHash private
Definition at line 79 of file qdbusconnectionmanager_p.h.
Referenced by connection(), removeConnection(), setConnection(), and ~QDBusConnectionManager().
mutex
QMutex QDBusConnectionManager::mutex mutable
Definition at line 77 of file qdbusconnectionmanager_p.h.
Referenced by QDBusConnection::connectToBus(), QDBusConnection::connectToPeer(), QDBusConnection::disconnectFromBus(), QDBusConnection::disconnectFromPeer(), and QDBusConnection::QDBusConnection().
senderMutex
QMutex QDBusConnectionManager::senderMutex mutable private
Definition at line 81 of file qdbusconnectionmanager_p.h.
Referenced by setSender().
senderName
QString QDBusConnectionManager::senderName private
Definition at line 82 of file qdbusconnectionmanager_p.h.
Referenced by setSender().
The documentation for this class was generated from the following files:
/src/dbus/qdbusconnectionmanager_p.h
/src/dbus/qdbusconnection.cpp