Qt 4.8: QDeclarativePath Class Reference
QDeclarativePath Class Reference
#include <qdeclarativepath_p.h>
Classes
struct AttributePoint
Signals
void changed ()
void startXChanged ()
void startYChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qreal attributeAt (const QString &, qreal) const
QStringList attributes () const
bool isClosed () const
QPainterPath path () const
QDeclarativeListProperty< QDeclarativePathElement > pathElements ()
QPointF pointAt (qreal) const
QDeclarativePath (QObject *parent=0)
void setStartX (qreal x)
void setStartY (qreal y)
qreal startX () const
qreal startY () const
~QDeclarativePath ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual void classBegin ()
Invoked after class creation, but before any properties have been set.
virtual void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void processPath ()
Private Functions
void createPointCache () const
void endpoint (const QString &name)
void interpolate (int idx, const QString &name, qreal value)
Properties
bool closed
QDeclarativeListProperty< QDeclarativePathElement > pathElements
qreal startX
qreal startY
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 208 of file qdeclarativepath_p.h.
Constructors and Destructors
QDeclarativePath()
QDeclarativePath::QDeclarativePath (QObject * parent = 0)
Definition at line 89 of file qdeclarativepath.cpp.
  : QObject(*(new QDeclarativePathPrivate), parent)
 {
 }
~QDeclarativePath()
QDeclarativePath::~QDeclarativePath ()
Definition at line 94 of file qdeclarativepath.cpp.
 {
 }
Functions
attributeAt()
qreal QDeclarativePath::attributeAt (const QString & name, qreal percent) const
Definition at line 451 of file qdeclarativepath.cpp.
 {
     Q_D(const QDeclarativePath);
     if (percent < 0 || percent > 1)
         return 0;
     for (int ii = 0; ii < d->_attributePoints.count(); ++ii) {
         const AttributePoint &point = d->_attributePoints.at(ii);
         if (point.percent == percent) {
             return point.values.value(name);
         } else if (point.percent > percent) {
             qreal lastValue =
                 ii?(d->_attributePoints.at(ii - 1).values.value(name)):0;
             qreal lastPercent =
                 ii?(d->_attributePoints.at(ii - 1).percent):0;
             qreal curValue = point.values.value(name);
             qreal curPercent = point.percent;
             return lastValue + (curValue - lastValue) * (percent - lastPercent) / (curPercent - lastPercent);
         }
     }
     return 0;
 }
attributes()
QStringList QDeclarativePath::attributes () const
Definition at line 329 of file qdeclarativepath.cpp.
 {
     Q_D(const QDeclarativePath);
     if (!d->componentComplete) {
         QSet<QString> attrs;
         // First gather up all the attributes
         foreach (QDeclarativePathElement *pathElement, d->_pathElements) {
             if (QDeclarativePathAttribute *attribute =
                 qobject_cast<QDeclarativePathAttribute *>(pathElement))
                 attrs.insert(attribute->name());
         }
         return attrs.toList();
     }
     return d->_attributes;
 }
changed
void QDeclarativePath::changed () signal
Referenced by componentComplete(), processPath(), QDeclarativePathCubic::setControl1X(), QDeclarativePathCubic::setControl1Y(), QDeclarativePathCubic::setControl2X(), QDeclarativePathCubic::setControl2Y(), QDeclarativePathQuad::setControlX(), QDeclarativePathQuad::setControlY(), QDeclarativePathAttribute::setValue(), QDeclarativePathPercent::setValue(), QDeclarativeCurve::setX(), and QDeclarativeCurve::setY().
classBegin()
void QDeclarativePath::classBegin () protected virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 297 of file qdeclarativepath.cpp.
 {
     Q_D(QDeclarativePath);
     d->componentComplete = false;
 }
componentComplete()
void QDeclarativePath::componentComplete () protected virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 303 of file qdeclarativepath.cpp.
 {
     Q_D(QDeclarativePath);
     QSet<QString> attrs;
     d->componentComplete = true;
     // First gather up all the attributes
     foreach (QDeclarativePathElement *pathElement, d->_pathElements) {
         if (QDeclarativePathAttribute *attribute =
             qobject_cast<QDeclarativePathAttribute *>(pathElement))
             attrs.insert(attribute->name());
     }
     d->_attributes = attrs.toList();
     processPath();
     foreach (QDeclarativePathElement *pathElement, d->_pathElements)
         connect(pathElement, SIGNAL(changed()), this, SLOT(processPath()));
 }
createPointCache()
void QDeclarativePath::createPointCache () const private
Definition at line 383 of file qdeclarativepath.cpp.
Referenced by pointAt().
 {
     Q_D(const QDeclarativePath);
     qreal pathLength = d->_path.length();
     if (pathLength <= 0 || qIsNaN(pathLength))
         return;
     // more points means less jitter between items as they move along the
     // path, but takes longer to generate
     const int points = qCeil(pathLength*5);
     const int lastElement = d->_path.elementCount() - 1;
     d->_pointCache.resize(points+1);
     int currElement = 0;
     qreal bezLength = 0;
     QBezier currBez = nextBezier(d->_path, &currElement, &bezLength);
     qreal currLength = bezLength;
     qreal epc = currLength / pathLength;
     for (int i = 0; i < d->_pointCache.size(); i++) {
         //find which set we are in
         qreal prevPercent = 0;
         qreal prevOrigPercent = 0;
         for (int ii = 0; ii < d->_attributePoints.count(); ++ii) {
             qreal percent = qreal(i)/points;
             const AttributePoint &point = d->_attributePoints.at(ii);
             if (percent < point.percent || ii == d->_attributePoints.count() - 1) { //### || is special case for very last item
                 qreal elementPercent = (percent - prevPercent);
                 qreal spc = prevOrigPercent + elementPercent * point.scale;
                 while (spc > epc) {
                     if (currElement > lastElement)
                         break;
                     currBez = nextBezier(d->_path, &currElement, &bezLength);
                     if (bezLength == 0.0) {
                         currLength = pathLength;
                         epc = 1.0;
                         break;
                     }
                     currLength += bezLength;
                     epc = currLength / pathLength;
                 }
                 qreal realT = (pathLength * spc - (currLength - bezLength)) / bezLength;
                 d->_pointCache[i] = currBez.pointAt(qBound(qreal(0), realT, qreal(1)));
                 break;
             }
             prevOrigPercent = point.origpercent;
             prevPercent = point.percent;
         }
     }
 }
endpoint()
void QDeclarativePath::endpoint (const QString & name) private
Definition at line 209 of file qdeclarativepath.cpp.
Referenced by processPath().
 {
     Q_D(QDeclarativePath);
     const AttributePoint &first = d->_attributePoints.first();
     qreal val = first.values.value(name);
     for (int ii = d->_attributePoints.count() - 1; ii >= 0; ii--) {
         const AttributePoint &point = d->_attributePoints.at(ii);
         if (point.values.contains(name)) {
             for (int jj = ii + 1; jj < d->_attributePoints.count(); ++jj) {
                 AttributePoint &setPoint = d->_attributePoints[jj];
                 setPoint.values.insert(name, val);
             }
             return;
         }
     }
 }
interpolate()
void QDeclarativePath::interpolate (int idx, const QString & name, qreal value) private
Definition at line 178 of file qdeclarativepath.cpp.
Referenced by processPath().
 {
     Q_D(QDeclarativePath);
     if (!idx)
         return;
     qreal lastValue = 0;
     qreal lastPercent = 0;
     int search = idx - 1;
     while(search >= 0) {
         const AttributePoint &point = d->_attributePoints.at(search);
         if (point.values.contains(name)) {
             lastValue = point.values.value(name);
             lastPercent = point.origpercent;
             break;
         }
         --search;
     }
     ++search;
     const AttributePoint &curPoint = d->_attributePoints.at(idx);
     for (int ii = search; ii < idx; ++ii) {
         AttributePoint &point = d->_attributePoints[ii];
         qreal val = lastValue + (value - lastValue) * (point.origpercent - lastPercent) / (curPoint.origpercent - lastPercent);
         point.values.insert(name, val);
     }
 }
isClosed()
bool QDeclarativePath::isClosed () const
Definition at line 145 of file qdeclarativepath.cpp.
 {
     Q_D(const QDeclarativePath);
     return d->closed;
 }
path()
QPainterPath QDeclarativePath::path () const
Definition at line 323 of file qdeclarativepath.cpp.
 {
     Q_D(const QDeclarativePath);
     return d->_path;
 }
pathElements()
QDeclarativeListProperty<QDeclarativePathElement> QDeclarativePath::pathElements ()
Referenced by isClosed().
pointAt()
QPointF QDeclarativePath::pointAt (qreal p) const
Definition at line 435 of file qdeclarativepath.cpp.
Referenced by QDeclarativePathViewPrivate::pointNear().
 {
     Q_D(const QDeclarativePath);
     if (d->_pointCache.isEmpty()) {
         createPointCache();
         if (d->_pointCache.isEmpty())
             return QPointF();
     }
     int idx = qRound(p*d->_pointCache.size());
     if (idx >= d->_pointCache.size())
         idx = d->_pointCache.size() - 1;
     else if (idx < 0)
         idx = 0;
     return d->_pointCache.at(idx);
 }
processPath
void QDeclarativePath::processPath () private slot
Definition at line 226 of file qdeclarativepath.cpp.
Referenced by componentComplete(), setStartX(), and setStartY().
 {
     Q_D(QDeclarativePath);
     if (!d->componentComplete)
         return;
     d->_pointCache.clear();
     d->_attributePoints.clear();
     d->_path = QPainterPath();
     AttributePoint first;
     for (int ii = 0; ii < d->_attributes.count(); ++ii)
         first.values[d->_attributes.at(ii)] = 0;
     d->_attributePoints << first;
     d->_path.moveTo(d->startX, d->startY);
     QDeclarativeCurve *lastCurve = 0;
     foreach (QDeclarativePathElement *pathElement, d->_pathElements) {
         if (QDeclarativeCurve *curve = qobject_cast<QDeclarativeCurve *>(pathElement)) {
             curve->addToPath(d->_path);
             AttributePoint p;
             p.origpercent = d->_path.length();
             d->_attributePoints << p;
             lastCurve = curve;
         } else if (QDeclarativePathAttribute *attribute = qobject_cast<QDeclarativePathAttribute *>(pathElement)) {
             AttributePoint &point = d->_attributePoints.last();
             point.values[attribute->name()] = attribute->value();
             interpolate(d->_attributePoints.count() - 1, attribute->name(), attribute->value());
         } else if (QDeclarativePathPercent *percent = qobject_cast<QDeclarativePathPercent *>(pathElement)) {
             AttributePoint &point = d->_attributePoints.last();
             point.values[QLatin1String("_qfx_percent")] = percent->value();
             interpolate(d->_attributePoints.count() - 1, QLatin1String("_qfx_percent"), percent->value());
         }
     }
     // Fixup end points
     const AttributePoint &last = d->_attributePoints.last();
     for (int ii = 0; ii < d->_attributes.count(); ++ii) {
         if (!last.values.contains(d->_attributes.at(ii)))
             endpoint(d->_attributes.at(ii));
     }
     // Adjust percent
     qreal length = d->_path.length();
     qreal prevpercent = 0;
     qreal prevorigpercent = 0;
     for (int ii = 0; ii < d->_attributePoints.count(); ++ii) {
         const AttributePoint &point = d->_attributePoints.at(ii);
         if (point.values.contains(QLatin1String("_qfx_percent"))) { //special string for QDeclarativePathPercent
             if ( ii > 0) {
                 qreal scale = (d->_attributePoints[ii].origpercent/length - prevorigpercent) /
                             (point.values.value(QLatin1String("_qfx_percent"))-prevpercent);
                 d->_attributePoints[ii].scale = scale;
             }
             d->_attributePoints[ii].origpercent /= length;
             d->_attributePoints[ii].percent = point.values.value(QLatin1String("_qfx_percent"));
             prevorigpercent = d->_attributePoints[ii].origpercent;
             prevpercent = d->_attributePoints[ii].percent;
         } else {
             d->_attributePoints[ii].origpercent /= length;
             d->_attributePoints[ii].percent = d->_attributePoints[ii].origpercent;
         }
     }
     d->closed = lastCurve && d->startX == lastCurve->x() && d->startY == lastCurve->y();
     emit changed();
 }
setStartX()
void QDeclarativePath::setStartX (qreal x)
Definition at line 112 of file qdeclarativepath.cpp.
 {
     Q_D(QDeclarativePath);
     if (qFuzzyCompare(x, d->startX))
         return;
     d->startX = x;
     emit startXChanged();
     processPath();
 }
setStartY()
void QDeclarativePath::setStartY (qreal y)
Definition at line 128 of file qdeclarativepath.cpp.
 {
     Q_D(QDeclarativePath);
     if (qFuzzyCompare(y, d->startY))
         return;
     d->startY = y;
     emit startYChanged();
     processPath();
 }
startX()
qreal QDeclarativePath::startX () const
Referenced by ~QDeclarativePath().
startXChanged
void QDeclarativePath::startXChanged () signal
Referenced by setStartX().
startY()
qreal QDeclarativePath::startY () const
Referenced by setStartX().
startYChanged
void QDeclarativePath::startYChanged () signal
Referenced by setStartY().
Properties
closed
bool QDeclarativePath::closed private
Definition at line 216 of file qdeclarativepath_p.h.
pathElements
QDeclarativeListProperty< QDeclarativePathElement > QDeclarativePath::pathElements private
Definition at line 213 of file qdeclarativepath_p.h.
startX
qreal QDeclarativePath::startX private
Definition at line 214 of file qdeclarativepath_p.h.
startY
qreal QDeclarativePath::startY private
Definition at line 215 of file qdeclarativepath_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativepath_p.h
/src/declarative/graphicsitems/qdeclarativepath.cpp