Qt 4.8: QTessellatorPrivate::Scanline Class Reference
QTessellatorPrivate::Scanline Class Reference
Public Functions
void clearMarks ()
void done ()
int findEdge (int edge) const
int findEdgePosition (Q27Dot5 x, Q27Dot5 y) const
int findEdgePosition (const Edge &e) const
void init (int maxActiveEdges)
void insert (int pos, const Edge &e)
void lineDone ()
void markEdges (int pos1, int pos2)
void prepareLine ()
void removeAt (int pos)
Scanline ()
void swap (int p1, int p2)
~Scanline ()
Public Variables
Edge ** edges
Edge ** old
int old_size
int size
Private Types
enum { default_alloc = 32 }
Properties
Edge * edge_table
int first_unused
int max_edges
Detailed Description
Definition at line 137 of file qtessellator.cpp.
Enumerations
anonymous enum
anonymous enum private
Enumerator
default_alloc
Definition at line 172 of file qtessellator.cpp.
 { default_alloc = 32 };
Constructors and Destructors
Scanline()
QTessellatorPrivate::Scanline::Scanline ()
Definition at line 396 of file qtessellator.cpp.
 {
     edges = 0;
     edge_table = 0;
     old = 0;
 }
~Scanline()
QTessellatorPrivate::Scanline::~Scanline ()
Definition at line 433 of file qtessellator.cpp.
 {
     free(edges);
     free(old);
     free(edge_table);
 }
Functions
clearMarks()
void QTessellatorPrivate::Scanline::clearMarks ()
Definition at line 485 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addIntersections().
 {
     for (int i = 0; i < size; ++i) {
         edges[i]->mark = false;
         edges[i]->intersect_left = false;
         edges[i]->intersect_right = false;
     }
 }
done()
void QTessellatorPrivate::Scanline::done ()
Definition at line 421 of file qtessellator.cpp.
 {
     if (max_edges > default_alloc) {
         free(edges);
         free(old);
         free(edge_table);
         edges = 0;
         old = 0;
         edge_table = 0;
     }
 }
findEdge()
int QTessellatorPrivate::Scanline::findEdge (int edge) const
Definition at line 474 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::processIntersections(), and QTessellatorPrivate::removeEdges().
 {
     for (int i = 0; i < size; ++i) {
         int item_edge = edges[i]->edge;
         if (item_edge == edge)
             return i;
     }
     //Q_ASSERT(false);
     return -1;
 }
findEdgePosition() [1/2]
int QTessellatorPrivate::Scanline::findEdgePosition (Q27Dot5 x, Q27Dot5 y) const
Definition at line 440 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges().
 {
     int min = 0;
     int max = size - 1;
     while (min < max) {
         int pos = min + ((max - min + 1) >> 1);
         Q27Dot5 ax = edges[pos]->positionAt(y);
         if (ax > x) {
             max = pos - 1;
         } else {
             min = pos;
         }
     }
     return min;
 }
findEdgePosition() [2/2]
int QTessellatorPrivate::Scanline::findEdgePosition (const Edge & e) const
Definition at line 456 of file qtessellator.cpp.
 {
 //     qDebug() << ">>      findEdgePosition";
     int min = 0;
     int max = size;
     while (min < max) {
         int pos = min + ((max - min) >> 1);
 //         qDebug() << "        " << min << max << pos << edges[pos]->isLeftOf(e, e.y0);
         if (edges[pos]->isLeftOf(e, e.v0->y)) {
             min = pos + 1;
         } else {
             max = pos;
         }
     }
 //     qDebug() << "<<      findEdgePosition got" << min;
     return min;
 }
init()
void QTessellatorPrivate::Scanline::init (int maxActiveEdges)
Definition at line 403 of file qtessellator.cpp.
 {
     maxActiveEdges *= 2;
     if (!edges || maxActiveEdges > default_alloc) {
         max_edges = maxActiveEdges;
         int s = qMax(maxActiveEdges + 1, default_alloc + 1);
         edges = q_check_ptr((Edge **)realloc(edges, s*sizeof(Edge *)));
         edge_table = q_check_ptr((Edge *)realloc(edge_table, s*sizeof(Edge)));
         old = q_check_ptr((Edge **)realloc(old, s*sizeof(Edge *)));
     }
     size = 0;
     old_size = 0;
     first_unused = 0;
     for (int i = 0; i < maxActiveEdges; ++i)
         edge_table[i].edge = i+1;
     edge_table[maxActiveEdges].edge = -1;
 }
insert()
void QTessellatorPrivate::Scanline::insert (int pos, const Edge & e)
Definition at line 520 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges().
 {
     Edge *edge = edge_table + first_unused;
     first_unused = edge->edge;
     Q_ASSERT(first_unused != -1);
     *edge = e;
     memmove(edges + pos + 1, edges + pos, (size - pos)*sizeof(Edge *));
     edges[pos] = edge;
     ++size;
 }
lineDone()
void QTessellatorPrivate::Scanline::lineDone ()
Definition at line 507 of file qtessellator.cpp.
 {
     Edge **end = old + old_size;
     Edge **e = old;
     while (e < end) {
         if ((*e)->free) {
             (*e)->edge = first_unused;
             first_unused = (*e - edge_table);
         }
         ++e;
     }
 }
markEdges()
void QTessellatorPrivate::Scanline::markEdges (int pos1, int pos2)
Definition at line 539 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges().
 {
     if (pos2 < pos1)
         return;
     for (int i = pos1; i <= pos2; ++i)
         edges[i]->mark = true;
 }
prepareLine()
void QTessellatorPrivate::Scanline::prepareLine ()
Definition at line 494 of file qtessellator.cpp.
 {
     Edge **end = edges + size;
     Edge **e = edges;
     Edge **o = old;
     while (e < end) {
         *o = *e;
         ++o;
         ++e;
     }
     old_size = size;
 }
removeAt()
void QTessellatorPrivate::Scanline::removeAt (int pos)
Definition at line 531 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::removeEdges().
 {
     Edge *e = edges[pos];
     e->free = true;
     --size;
     memmove(edges + pos, edges + pos + 1, (size - pos)*sizeof(Edge *));
 }
swap()
void QTessellatorPrivate::Scanline::swap (int p1, int p2) inline
Definition at line 150 of file qtessellator.cpp.
{
             Edge *tmp = edges[p1];
             edges[p1] = edges[p2];
             edges[p2] = tmp;
         }
Properties
edge_table
Edge* QTessellatorPrivate::Scanline::edge_table private
Definition at line 169 of file qtessellator.cpp.
edges
Edge** QTessellatorPrivate::Scanline::edges
Definition at line 165 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), QTessellatorPrivate::addIntersections(), QTessellatorPrivate::processIntersections(), and QTessellatorPrivate::removeEdges().
first_unused
int QTessellatorPrivate::Scanline::first_unused private
Definition at line 170 of file qtessellator.cpp.
max_edges
int QTessellatorPrivate::Scanline::max_edges private
Definition at line 171 of file qtessellator.cpp.
old
Edge** QTessellatorPrivate::Scanline::old
Definition at line 162 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::emitEdges().
old_size
int QTessellatorPrivate::Scanline::old_size
Definition at line 163 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::emitEdges().
size
int QTessellatorPrivate::Scanline::size
Definition at line 166 of file qtessellator.cpp.
Referenced by QTessellatorPrivate::addEdges(), QTessellatorPrivate::addIntersections(), QTessellatorPrivate::processIntersections(), QTessellatorPrivate::removeEdges(), and QTessellator::tessellate().
The documentation for this class was generated from the following file:
/src/gui/painting/qtessellator.cpp