Qt 4.8: QFontPrivate Class Reference
QFontPrivate Class Reference
#include <qfont_p.h>
Public Functions
void alterCharForCapitalization (QChar &c) const
QFontEngine * engineForScript (int script) const
QFontPrivate ()
QFontPrivate (const QFontPrivate &other)
void resolve (uint mask, const QFontPrivate *other)
QFont smallCapsFont () const
QFontPrivate * smallCapsFontPrivate () const
~QFontPrivate ()
Static Public Functions
static QFontPrivate * get (const QFont &font)
Public Variables
uint capital: 3
int dpi
QFontEngineData * engineData
HDC hdc
uint kerning: 1
QFixed letterSpacing
bool letterSpacingIsAbsolute: 1
uint overline: 1
uint rawMode: 1
QAtomicInt ref
QFontDef request
QFontPrivate * scFont
int screen
uint strikeOut: 1
uint underline: 1
QFixed wordSpacing
Static Public Variables
static int defaultEncodingID = -1
Private Functions
QFontPrivate & operator= (const QFontPrivate &)
Detailed Description
Definition at line 163 of file qfont_p.h.
Constructors and Destructors
QFontPrivate() [1/2]
QFontPrivate::QFontPrivate ()
Definition at line 245 of file qfont.cpp.
     : engineData(0), dpi(qt_defaultDpi()), screen(0),
       rawMode(false), underline(false), overline(false), strikeOut(false), kerning(true),
       capital(0), letterSpacingIsAbsolute(false), scFont(0)
 {
 #ifdef Q_WS_X11
     if (QX11Info::display())
         screen = QX11Info::appScreen();
     else
         screen = 0;
 #endif
 #ifdef Q_WS_WIN
     hdc = 0;
 #endif
 }
QFontPrivate() [2/2]
QFontPrivate::QFontPrivate (const QFontPrivate & other)
Definition at line 261 of file qfont.cpp.
     : request(other.request), engineData(0), dpi(other.dpi), screen(other.screen),
       rawMode(other.rawMode), underline(other.underline), overline(other.overline),
       strikeOut(other.strikeOut), kerning(other.kerning),
       capital(other.capital), letterSpacingIsAbsolute(other.letterSpacingIsAbsolute),
       letterSpacing(other.letterSpacing), wordSpacing(other.wordSpacing),
       scFont(other.scFont)
 {
 #ifdef Q_WS_WIN
     hdc = other.hdc;
 #endif
     if (scFont && scFont != this)
         scFont->ref.ref();
 }
~QFontPrivate()
QFontPrivate::~QFontPrivate ()
Definition at line 276 of file qfont.cpp.
 {
     if (engineData)
         engineData->ref.deref();
     engineData = 0;
     if (scFont && scFont != this)
         scFont->ref.deref();
     scFont = 0;
 }
Functions
alterCharForCapitalization()
void QFontPrivate::alterCharForCapitalization (QChar & c) const
Definition at line 309 of file qfont.cpp.
Referenced by QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFontMetrics::charWidth(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QFontMetrics::width(), and QFontMetricsF::width().
{
     switch (capital) {
     case QFont::AllUppercase:
     case QFont::SmallCaps:
         c = c.toUpper();
         break;
     case QFont::AllLowercase:
         c = c.toLower();
         break;
     case QFont::MixedCase:
         break;
     }
 }
engineForScript()
QFontEngine * QFontPrivate::engineForScript (int script) const
Definition at line 294 of file qfont.cpp.
Referenced by QPainterPath::addText(), QFontMetrics::ascent(), QFontMetricsF::ascent(), QFontMetrics::averageCharWidth(), QFontMetricsF::averageCharWidth(), QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFontMetrics::charWidth(), QFontMetrics::descent(), QFontMetricsF::descent(), QTextLine::draw(), QTextEngine::elidedText(), QFontInfo::exactMatch(), QFont::exactMatch(), QFontInfo::family(), QFontInfo::fixedPitch(), QTextEngine::fontEngine(), QFont::freetypeFace(), QRawFont::fromFont(), QTextLine::glyphs(), QFont::handle(), QFontMetrics::height(), QFontMetricsF::height(), QFontMetrics::inFont(), QFontMetricsF::inFont(), QFontMetrics::inFontUcs4(), QFontMetricsF::inFontUcs4(), QFontInfo::italic(), QFontMetrics::leading(), QFontMetricsF::leading(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFontMetrics::lineSpacing(), QFontMetricsF::lineSpacing(), QFontMetrics::lineWidth(), QFontMetricsF::lineWidth(), QFont::macFontID(), QFontMetrics::maxWidth(), QFontMetricsF::maxWidth(), QFontMetrics::minLeftBearing(), QFontMetricsF::minLeftBearing(), QFontMetrics::minRightBearing(), QFontMetricsF::minRightBearing(), QFontInfo::pixelSize(), QFontInfo::pointSize(), pointSize(), QFontInfo::pointSizeF(), QPainterReplayer::process(), qgl_use_font(), qt_x11_set_fallback_font_family(), QTextItemInt::QTextItemInt(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QScriptLine::setDefaultHeight(), QFontDialogPrivate::setFont(), QFontInfo::style(), QFontInfo::styleHint(), QFontInfo::styleName(), QFontMetrics::underlinePos(), QFontMetricsF::underlinePos(), QFontInfo::weight(), QFontMetrics::width(), QFontMetricsF::width(), QFontMetrics::xHeight(), and QFontMetricsF::xHeight().
 {
     QMutexLocker locker(qt_fontdatabase_mutex());
     if (script >= QUnicodeTables::Inherited)
         script = QUnicodeTables::Common;
     if (engineData && engineData->fontCache != QFontCache::instance()) {
         // throw out engineData that came from a different thread
         engineData->ref.deref();
         engineData = 0;
     }
     if (!engineData || !QT_FONT_ENGINE_FROM_DATA(engineData, script))
         QFontDatabase::load(this, script);
     return QT_FONT_ENGINE_FROM_DATA(engineData, script);
 }
get()
static QFontPrivate* QFontPrivate::get (const QFont & font) inline static
Definition at line 202 of file qfont_p.h.
Referenced by QRawFont::fromFont(), and QPainterReplayer::process().
     {
         return font.d.data();
     }
operator=()
QFontPrivate& QFontPrivate::operator= (const QFontPrivate &) inline private
Definition at line 209 of file qfont_p.h.
 { return *this; }
resolve()
void QFontPrivate::resolve (uint mask, const QFontPrivate * other)
Definition at line 340 of file qfont.cpp.
Referenced by QFont::resolve().
 {
     Q_ASSERT(other != 0);
     dpi = other->dpi;
     if ((mask & QFont::AllPropertiesResolved) == QFont::AllPropertiesResolved) return;
     // assign the unset-bits with the set-bits of the other font def
     if (! (mask & QFont::FamilyResolved))
         request.family = other->request.family;
     if (! (mask & QFont::StyleNameResolved))
         request.styleName = other->request.styleName;
     if (! (mask & QFont::SizeResolved)) {
         request.pointSize = other->request.pointSize;
         request.pixelSize = other->request.pixelSize;
     }
     if (! (mask & QFont::StyleHintResolved))
         request.styleHint = other->request.styleHint;
     if (! (mask & QFont::StyleStrategyResolved))
         request.styleStrategy = other->request.styleStrategy;
     if (! (mask & QFont::WeightResolved))
         request.weight = other->request.weight;
     if (! (mask & QFont::StyleResolved))
         request.style = other->request.style;
     if (! (mask & QFont::FixedPitchResolved))
         request.fixedPitch = other->request.fixedPitch;
     if (! (mask & QFont::StretchResolved))
         request.stretch = other->request.stretch;
     if (! (mask & QFont::HintingPreferenceResolved))
         request.hintingPreference = other->request.hintingPreference;
     if (! (mask & QFont::UnderlineResolved))
         underline = other->underline;
     if (! (mask & QFont::OverlineResolved))
         overline = other->overline;
     if (! (mask & QFont::StrikeOutResolved))
         strikeOut = other->strikeOut;
     if (! (mask & QFont::KerningResolved))
         kerning = other->kerning;
     if (! (mask & QFont::LetterSpacingResolved)) {
         letterSpacing = other->letterSpacing;
         letterSpacingIsAbsolute = other->letterSpacingIsAbsolute;
     }
     if (! (mask & QFont::WordSpacingResolved))
         wordSpacing = other->wordSpacing;
     if (! (mask & QFont::CapitalizationResolved))
         capital = other->capital;
 }
smallCapsFont()
QFont QFontPrivate::smallCapsFont () const inline
Definition at line 199 of file qfont_p.h.
Referenced by QTextEngine::font().
 { return QFont(smallCapsFontPrivate()); }
smallCapsFontPrivate()
QFontPrivate * QFontPrivate::smallCapsFontPrivate () const
Definition at line 323 of file qfont.cpp.
Referenced by QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFontMetrics::charWidth(), QTextEngine::fontEngine(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QFontMetrics::width(), QFontMetricsF::width(), QFontMetrics::xHeight(), and QFontMetricsF::xHeight().
 {
     if (scFont)
         return scFont;
     QFont font(const_cast<QFontPrivate *>(this));
     qreal pointSize = font.pointSizeF();
     if (pointSize > 0)
         font.setPointSizeF(pointSize * .7);
     else
         font.setPixelSize((font.pixelSize() * 7 + 5) / 10);
     scFont = font.d.data();
     if (scFont != this)
         scFont->ref.ref();
     return scFont;
 }
Properties
capital
uint QFontPrivate::capital
Definition at line 192 of file qfont_p.h.
Referenced by alterCharForCapitalization(), QFontMetrics::boundingRect(), QFontMetricsF::boundingRect(), QFont::capitalization(), QFontMetrics::charWidth(), QTextEngine::itemize(), QFontMetrics::leftBearing(), QFontMetricsF::leftBearing(), QFont::operator<(), QFont::operator==(), resolve(), QFontMetrics::rightBearing(), QFontMetricsF::rightBearing(), QFont::setCapitalization(), QFontMetrics::width(), QFontMetricsF::width(), QFontMetrics::xHeight(), and QFontMetricsF::xHeight().
defaultEncodingID
int QFontPrivate::defaultEncodingID = -1 static
Definition at line 167 of file qfont_p.h.
Referenced by findEncoding(), and qt_x11_set_fallback_font_family().
dpi
int QFontPrivate::dpi
Definition at line 180 of file qfont_p.h.
Referenced by QTextEngine::calculateTabWidth(), QPicturePaintEngine::drawTextItem(), QFontDatabase::findFont(), QFontDatabase::load(), loadRaw(), loadWin(), QFontDatabase::loadXlfd(), QFont::QFont(), QFontMetrics::QFontMetrics(), QFontMetricsF::QFontMetricsF(), qt_x11_set_fallback_font_family(), registerFont(), resolve(), QFont::resolve(), and QTextEngine::shapeText().
engineData
QFontEngineData* QFontPrivate::engineData mutable
Definition at line 179 of file qfont_p.h.
Referenced by QFont::detach(), engineForScript(), QFontDatabase::findFont(), getEngineData(), QFontDatabase::load(), loadWin(), QFontDatabase::loadXlfd(), registerFont(), and ~QFontPrivate().
hdc
HDC QFontPrivate::hdc
Definition at line 184 of file qfont_p.h.
Referenced by loadWin(), QFont::QFont(), and QFontPrivate().
kerning
uint QFontPrivate::kerning
Definition at line 191 of file qfont_p.h.
Referenced by get_font_bits(), QFont::kerning(), QFontDatabase::load(), loadFromDatabase(), QFont::operator<(), QFont::operator==(), resolve(), set_font_bits(), and QFont::setKerning().
letterSpacing
QFixed QFontPrivate::letterSpacing
Definition at line 195 of file qfont_p.h.
Referenced by QFont::letterSpacing(), QFont::operator<(), QFont::operator==(), resolve(), QFont::setLetterSpacing(), and QTextEngine::shapeText().
letterSpacingIsAbsolute
bool QFontPrivate::letterSpacingIsAbsolute
Definition at line 193 of file qfont_p.h.
Referenced by get_extended_font_bits(), QFont::letterSpacingType(), QFont::operator<(), QFont::operator==(), resolve(), set_extended_font_bits(), QFont::setLetterSpacing(), and QTextEngine::shapeText().
overline
uint QFontPrivate::overline
Definition at line 189 of file qfont_p.h.
Referenced by QPainterPath::addText(), get_font_bits(), QTextItemInt::initWithScriptItem(), QFont::operator<(), QFont::operator==(), QFontInfo::overline(), QFont::overline(), resolve(), set_font_bits(), and QFont::setOverline().
rawMode
uint QFontPrivate::rawMode
Definition at line 187 of file qfont_p.h.
Referenced by QFontInfo::exactMatch(), QFont::exactMatch(), get_font_bits(), loadRaw(), loadWin(), QFontDatabase::loadXlfd(), QFontInfo::rawMode(), QFont::rawMode(), registerFont(), set_font_bits(), and QFont::setRawMode().
ref
QAtomicInt QFontPrivate::ref
Definition at line 177 of file qfont_p.h.
Referenced by QFont::detach(), QFontPrivate(), smallCapsFontPrivate(), and ~QFontPrivate().
request
QFontDef QFontPrivate::request
Definition at line 178 of file qfont_p.h.
Referenced by QFont::defaultFamily(), QFontInfo::exactMatch(), QFont::exactMatch(), QFont::family(), QFontDatabase::findFont(), QFont::fixedPitch(), QFont::freetypeFace(), QFont::fromString(), get_extended_font_bits(), get_font_bits(), QFont::hintingPreference(), QFontDatabase::load(), loadWin(), QFontDatabase::loadXlfd(), QFont::operator<(), QFont::operator==(), QFont::pixelSize(), pointSize(), QFont::pointSize(), QFont::pointSizeF(), QFont::QFont(), qt_x11_set_fallback_font_family(), registerFont(), resolve(), set_extended_font_bits(), set_font_bits(), QFont::setFamily(), QFont::setFixedPitch(), QFont::setHintingPreference(), QFont::setPixelSize(), QFont::setPointSize(), QFont::setPointSizeF(), QFont::setStretch(), QFont::setStyle(), QFont::setStyleHint(), QFont::setStyleName(), QFont::setStyleStrategy(), QFont::setWeight(), QFont::stretch(), QFont::style(), QFont::styleHint(), QFont::styleName(), QFont::styleStrategy(), and QFont::weight().
scFont
QFontPrivate* QFontPrivate::scFont mutable
Definition at line 198 of file qfont_p.h.
Referenced by QFont::detach(), QFontPrivate(), smallCapsFontPrivate(), and ~QFontPrivate().
screen
int QFontPrivate::screen
Definition at line 181 of file qfont_p.h.
Referenced by getFcPattern(), QFontDatabase::load(), loadFc(), loadWin(), QFontDatabase::loadXlfd(), QFont::QFont(), QFontMetrics::QFontMetrics(), QFontMetricsF::QFontMetricsF(), QFontPrivate(), and qt_x11_set_fallback_font_family().
strikeOut
uint QFontPrivate::strikeOut
Definition at line 190 of file qfont_p.h.
Referenced by QPainterPath::addText(), get_font_bits(), QTextItemInt::initWithScriptItem(), QFont::operator<(), QFont::operator==(), resolve(), set_font_bits(), QFont::setStrikeOut(), QFontInfo::strikeOut(), and QFont::strikeOut().
underline
uint QFontPrivate::underline
Definition at line 188 of file qfont_p.h.
Referenced by QPainterPath::addText(), get_font_bits(), QTextItemInt::initWithScriptItem(), QFont::operator<(), QFont::operator==(), resolve(), set_font_bits(), QFont::setUnderline(), QFontInfo::underline(), and QFont::underline().
wordSpacing
QFixed QFontPrivate::wordSpacing
Definition at line 196 of file qfont_p.h.
Referenced by QFont::operator<(), QFont::operator==(), resolve(), QFont::setWordSpacing(), QTextEngine::shapeText(), and QFont::wordSpacing().
The documentation for this class was generated from the following files:
/src/gui/text/qfont_p.h
/src/gui/text/qfont.cpp
/src/gui/text/qfont_x11.cpp