Qt 4.8: QDeclarativeTextEditPrivate Class Reference
QDeclarativeTextEditPrivate Class Reference
#include <qdeclarativetextedit_p_p.h>
Public Functions
bool determineHorizontalAlignment ()
void focusChanged (bool)
qreal implicitWidth () const
void init ()
void mirrorChange ()
QDeclarativeTextEditPrivate ()
void relayoutDocument ()
bool setHAlign (QDeclarativeTextEdit::HAlignment, bool forceAlign=false)
void updateDefaultTextOption ()
void updateSelection ()
Public Functions inherited from QDeclarativeImplicitSizePaintedItemPrivate
virtual void implicitHeightChanged ()
virtual void implicitWidthChanged ()
QDeclarativeImplicitSizePaintedItemPrivate ()
Public Functions inherited from QDeclarativePaintedItemPrivate
QDeclarativePaintedItemPrivate ()
Public Functions inherited from QDeclarativeItemPrivate
QDeclarativeStateGroup * _states ()
void addItemChangeListener (QDeclarativeItemChangeListener *listener, ChangeTypes types)
AnchorLines * anchorLines () const
QDeclarativeAnchors * anchors ()
QDeclarativeAnchorLine baseline () const
QDeclarativeAnchorLine bottom () const
QPointF computeTransformOrigin () const
QDeclarativeListProperty< QObject > data ()
virtual void focusScopeItemChange (bool isSubFocusItem)
Subclasses can reimplement this function to be notified when an item becomes a focusScopeItem (or is no longer a focusScopeItem).
qreal height () const
QDeclarativeAnchorLine horizontalCenter () const
virtual qreal implicitHeight () const
void init (QDeclarativeItem *parent)
bool isMirrored () const
QDeclarativeAnchorLine left () const
QDeclarativeItemPrivate ()
void removeItemChangeListener (QDeclarativeItemChangeListener *, ChangeTypes types)
void resetHeight ()
void resetWidth ()
void resolveLayoutMirror ()
QDeclarativeListProperty< QObject > resources ()
QDeclarativeAnchorLine right () const
void setHeight (qreal)
void setImplicitLayoutMirror (bool mirror, bool inherit)
void setLayoutMirror (bool mirror)
virtual void setPosHelper (const QPointF &pos)
Sets the position pos.
void setState (const QString &)
void setWidth (qreal)
virtual void siblingOrderChange ()
Subclasses can reimplement this function to be notified when its siblingIndex order is changed.
QString state () const
QDeclarativeListProperty< QDeclarativeState > states ()
QDeclarativeAnchorLine top () const
virtual void transformChanged ()
QDeclarativeListProperty< QDeclarativeTransition > transitions ()
QDeclarativeAnchorLine verticalCenter () const
qreal width () const
Public Functions inherited from QGraphicsItemPrivate
void addChild (QGraphicsItem *child)
QGraphicsScenePrivate::registerTopLevelItem().
void appendGraphicsTransform (QGraphicsTransform *t)
qreal calcEffectiveOpacity () const
void childrenBoundingRectHelper (QTransform *x, QRectF *rect, QGraphicsItem *topMostEffectItem)
Returns the bounding rect of this item's children (excluding itself).
bool childrenClippedToShape () const
bool childrenCombineOpacity () const
QDeclarativeListProperty< QGraphicsObject > childrenList ()
Returns a list of this item's children.
void clearFocusHelper (bool giveFocusToParent)
void clearSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
qreal combineOpacityFromParent (qreal parentOpacity) const
void combineTransformFromParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
void combineTransformToParent (QTransform *x, const QTransform *viewTransform=0) const
Combines this item's position and transform onto transform.
int depth () const
bool discardUpdateRequest (bool ignoreVisibleBit=false, bool ignoreDirtyBit=false, bool ignoreOpacity=false) const
Returns true if we can discard an update request; otherwise false.
QRectF effectiveBoundingRect (QGraphicsItem *topMostEffectItem=0) const
Returns the effective bounding rect of the item.
QRectF effectiveBoundingRect (const QRectF &rect) const
Returns the effective bounding rect of the given item space rect.
qreal effectiveOpacity () const
void ensureSceneTransform ()
void ensureSceneTransformRecursive (QGraphicsItem **topMostDirtyItem)
void ensureSequentialSiblingIndex ()
Ensures that the list of children is sorted by insertion order, and that the siblingIndexes are packed (no gaps), and start at 0.
void ensureSortedChildren ()
QVariant extra (Extra type) const
QGraphicsItemCache * extraItemCache () const
QPointF genericMapFromScene (const QPointF &pos, const QWidget *viewport) const
Maps the point pos from scene to item coordinates.
bool hasTranslateOnlySceneTransform ()
void initStyleOption (QStyleOptionGraphicsItem *option, const QTransform &worldTransform, const QRegion &exposedRegion, bool allItems=false) const
virtual QVariant inputMethodQueryHelper (Qt::InputMethodQuery query) const
This helper function helped us add input method query support in Qt 4.
void invalidateChildGraphicsEffectsRecursively (InvalidateReason reason)
void invalidateChildrenSceneTransform ()
void invalidateDepthRecursively ()
void invalidateParentGraphicsEffectsRecursively ()
bool isFullyTransparent () const
bool isInvisible () const
bool isOpacityNull () const
virtual bool isProxyWidget () const
bool itemIsUntransformable () const
void markParentDirty (bool updateBoundingRect=false)
QGraphicsItemCache * maybeExtraItemCache () const
void prependGraphicsTransform (QGraphicsTransform *t)
QGraphicsItemPrivate ()
void remapItemPos (QEvent *event, QGraphicsItem *item)
Maps any item pos properties of event to item's coordinate system.
void removeChild (QGraphicsItem *child)
QGraphicsScenePrivate::unregisterTopLevelItem().
void removeExtraItemCache ()
void resetFocusProxy ()
Sets the focusProxy pointer to 0 for all items that have this item as their focusProxy.
void resolveDepth ()
Resolves the stacking depth of this object and all its ancestors.
virtual void resolveFont (uint inheritedMask)
virtual void resolvePalette (uint inheritedMask)
QRectF sceneEffectiveBoundingRect () const
Returns the effective bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect(), taking into account the effect that the item might have.
void sendScenePosChange ()
void setEnabledHelper (bool newEnabled, bool explicitly, bool update=true)
Sets this item's visibility to newEnabled.
void setExtra (Extra type, const QVariant &value)
void setFocusHelper (Qt::FocusReason focusReason, bool climb, bool focusFromHide)
void setIsMemberOfGroup (bool enabled)
Propagates item group membership.
void setParentItemHelper (QGraphicsItem *parent, const QVariant *newParentVariant, const QVariant *thisPointerVariant)
Make sure not to trigger any pure virtual function calls (e.
void setSubFocus (QGraphicsItem *rootItem=0, QGraphicsItem *stopItem=0)
void setTransformHelper (const QTransform &transform)
Sets the transform transform.
void setVisibleHelper (bool newVisible, bool explicitly, bool update=true)
Sets this item's visibility to newVisible.
virtual void subFocusItemChange ()
Subclasses can reimplement this function to be notified when subFocusItem changes.
QTransform transformToParent () const
void unsetExtra (Extra type)
void updateAncestorFlag (QGraphicsItem::GraphicsItemFlag childFlag, AncestorFlag flag=NoFlag, bool enabled=false, bool root=true)
Propagates the ancestor flag flag with value enabled to all this item's children.
void updateAncestorFlags ()
void updateChildWithGraphicsEffectFlagRecursively ()
void updatePaintedViewBoundingRects (bool updateChildren)
virtual void updateSceneTransformFromParent ()
virtual ~QGraphicsItemPrivate ()
Public Variables
bool canPaste
bool clickCausedFocus: 1
QColor color
QTextControl * control
QDeclarativeItem * cursor
QDeclarativeComponent * cursorComponent
bool cursorVisible: 1
bool dirty: 1
QTextDocument * document
bool focusOnPress: 1
QFont font
QDeclarativeTextEdit::TextFormat format
QDeclarativeTextEdit::HAlignment hAlign
bool hAlignImplicit:1
QPixmap imgCache
bool imgDirty: 1
QPixmap imgStyleCache
int lastSelectionEnd
int lastSelectionStart
int lineCount
QDeclarativeTextEdit::SelectionMode mouseSelectionMode
QSize paintedSize
bool persistentSelection: 1
bool requireImplicitWidth:1
bool richText: 1
bool rightToLeftText:1
bool selectByMouse
QColor selectedTextColor
QColor selectionColor
bool showInputPanelOnFocus: 1
QFont sourceFont
QString style
QColor styleColor
QString text
qreal textMargin
QDeclarativeTextEdit::VAlignment vAlign
QDeclarativeTextEdit::WrapMode wrapMode
int yoff
Public Variables inherited from QDeclarativePaintedItemPrivate
bool cachefrozen
qreal contentsScale
QSize contentsSize
QColor fillColor
QList< ImageCacheItem * > imagecache
int max_imagecache_size
bool smoothCache
Public Variables inherited from QDeclarativeItemPrivate
AnchorLines * _anchorLines
QDeclarativeAnchors * _anchors
QDeclarativeContents * _contents
QDeclarativeStateGroup * _stateGroup
QDeclarativeLayoutMirroringAttached * attachedLayoutDirection
QDeclarativeNullableValue< qreal > baselineOffset
QPODVector< ChangeListener, 4 > changeListeners
bool componentComplete:1
bool doneEventPreHandler: 1
bool effectiveLayoutMirror:1
bool hadActiveFocus:1
bool hadFocus:1
bool heightValid:1
bool inheritedLayoutMirror:1
bool inheritMirrorFromItem:1
bool inheritMirrorFromParent:1
bool isMirrorImplicit:1
bool keepMouse:1
QDeclarativeItemKeyFilter * keyHandler
qreal mHeight
qreal mImplicitHeight
qreal mImplicitWidth
qreal mWidth
QDeclarativeItem::TransformOrigin origin:5
QDeclarativeNotifier parentNotifier
bool smooth:1
bool transformOriginDirty: 1
bool widthValid:1
Public Variables inherited from QGraphicsItemPrivate
quint32 acceptDrops: 1
quint32 acceptedMouseButtons: 5
quint32 acceptedTouchBeginEvent: 1
quint32 acceptsHover: 1
quint32 acceptTouchEvents: 1
quint32 allChildrenDirty: 1
quint32 ancestorFlags: 4
quint32 cacheMode: 2
QList< QGraphicsItem * > children
QRectF childrenBoundingRect
quint32 dirty: 1
quint32 dirtyChildren: 1
quint32 dirtyChildrenBoundingRect: 1
quint32 dirtySceneTransform: 1
quint32 enabled: 1
quint32 explicitActivate: 1
quint32 explicitlyDisabled: 1
quint32 explicitlyHidden: 1
QList< ExtraStruct > extras
quint32 filtersDescendantEvents: 1
quint32 flags: 19
QGraphicsItem * focusProxy
QList< QGraphicsItem ** > focusProxyRefs
QGraphicsItem * focusScopeItem
quint32 fullUpdatePending: 1
quint32 geometryChanged: 1
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
int globalStackingOrder
QGraphicsEffect * graphicsEffect
quint32 handlesChildEvents: 1
quint32 hasBoundingRegionGranularity: 1
quint32 hasCursor: 1
quint32 holesInSiblingIndex: 1
quint32 ignoreOpacity: 1
quint32 ignoreVisible: 1
Qt::InputMethodHints imHints
quint32 inDestructor: 1
int index
quint32 inSetPosHelper: 1
quint32 isDeclarativeItem: 1
quint32 isMemberOfGroup: 1
quint32 isObject: 1
quint32 isWidget: 1
int itemDepth
quint32 itemDiscovered: 1
quint32 localCollisionHack: 1
quint32 mayHaveChildWithGraphicsEffect: 1
quint32 mouseSetsFocus: 1
quint32 needSortChildren: 1
QRectF needsRepaint
quint32 notifyBoundingRectChanged: 1
quint32 notifyInvalidated: 1
qreal opacity
quint32 padding: 21
QMap< QWidget *, QRect > paintedViewBoundingRects
quint32 paintedViewBoundingRectsNeedRepaint: 1
QGraphicsItem::PanelModality panelModality
QGraphicsItem * parent
quint32 pendingPolish: 1
QPointF pos
QGraphicsItem * q_ptr
QGraphicsScene * scene
quint32 scenePosDescendants: 1
QTransform sceneTransform
quint32 sceneTransformTranslateOnly: 1
quint32 selected: 1
quint32 sendParentChangeNotification: 1
quint32 sequentialOrdering: 1
int siblingIndex
QGraphicsItem * subFocusItem
TransformData * transformData
quint32 updateDueToGraphicsEffect: 1
quint32 visible: 1
quint32 wantsActive: 1
qreal z
Additional Inherited Members
Public Types inherited from QDeclarativeItemPrivate
enum ChangeType {
Geometry = 0x01, SiblingOrder = 0x02, Visibility = 0x04, Opacity = 0x08,
Destroyed = 0x10
}
Public Types inherited from QGraphicsItemPrivate
enum AncestorFlag {
NoFlag = 0, AncestorHandlesChildEvents = 0x1, AncestorClipsChildren = 0x2, AncestorIgnoresTransformations = 0x4,
AncestorFiltersChildEvents = 0x8
}
enum Extra {
ExtraToolTip, ExtraCursor, ExtraCacheData, ExtraMaxDeviceCoordCacheSize,
ExtraBoundingRegionGranularity
}
enum InvalidateReason { OpacityChanged }
Static Public Functions inherited from QDeclarativeItemPrivate
static void data_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * data_at (QDeclarativeListProperty< QObject > *, int)
static void data_clear (QDeclarativeListProperty< QObject > *)
static int data_count (QDeclarativeListProperty< QObject > *)
static qint64 elapsed (QElapsedTimer &)
static QDeclarativeItemPrivate * get (QDeclarativeItem *item)
static void parentProperty (QObject *o, void *rv, QDeclarativeNotifierEndpoint *e)
static void resources_append (QDeclarativeListProperty< QObject > *, QObject *)
static QObject * resources_at (QDeclarativeListProperty< QObject > *, int)
static void resources_clear (QDeclarativeListProperty< QObject > *)
static int resources_count (QDeclarativeListProperty< QObject > *)
static qint64 restart (QElapsedTimer &)
static void setConsistentTime (qint64 t)
static void start (QElapsedTimer &)
static void transform_append (QDeclarativeListProperty< QGraphicsTransform > *list, QGraphicsTransform *)
static QGraphicsTransform * transform_at (QDeclarativeListProperty< QGraphicsTransform > *list, int)
static void transform_clear (QDeclarativeListProperty< QGraphicsTransform > *list)
static int transform_count (QDeclarativeListProperty< QGraphicsTransform > *list)
Static Public Functions inherited from QGraphicsItemPrivate
static void children_append (QDeclarativeListProperty< QGraphicsObject > *list, QGraphicsObject *item)
static QGraphicsObject * children_at (QDeclarativeListProperty< QGraphicsObject > *list, int)
static void children_clear (QDeclarativeListProperty< QGraphicsObject > *list)
static int children_count (QDeclarativeListProperty< QGraphicsObject > *list)
static const QGraphicsItemPrivate * get (const QGraphicsItem *item)
static QGraphicsItemPrivate * get (QGraphicsItem *item)
static bool insertionOrder (QGraphicsItem *a, QGraphicsItem *b)
static bool isOpacityNull (qreal opacity)
static bool movableAncestorIsSelected (const QGraphicsItem *item)
Static Public Variables inherited from QDeclarativeItemPrivate
static qint64 consistentTime = -1
Detailed Description
Definition at line 65 of file qdeclarativetextedit_p_p.h.
Constructors and Destructors
QDeclarativeTextEditPrivate()
QDeclarativeTextEditPrivate::QDeclarativeTextEditPrivate () inline
Definition at line 70 of file qdeclarativetextedit_p_p.h.
       : color("black"), hAlign(QDeclarativeTextEdit::AlignLeft), vAlign(QDeclarativeTextEdit::AlignTop),
       imgDirty(true), dirty(false), richText(false), cursorVisible(false), focusOnPress(true),
       showInputPanelOnFocus(true), clickCausedFocus(false), persistentSelection(true), requireImplicitWidth(false),
       hAlignImplicit(true), rightToLeftText(false), textMargin(0.0), lastSelectionStart(0), lastSelectionEnd(0),
       cursorComponent(0), cursor(0), format(QDeclarativeTextEdit::AutoText), document(0), wrapMode(QDeclarativeTextEdit::NoWrap),
       mouseSelectionMode(QDeclarativeTextEdit::SelectCharacters), selectByMouse(false), canPaste(false),
       yoff(0)
     {
 #ifdef Q_OS_SYMBIAN
         if (QSysInfo::symbianVersion() >= QSysInfo::SV_SF_1) {
             showInputPanelOnFocus = false;
         }
 #endif
     }
Functions
determineHorizontalAlignment()
bool QDeclarativeTextEditPrivate::determineHorizontalAlignment ()
Definition at line 600 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     if (hAlignImplicit && q->isComponentComplete()) {
         bool alignToRight;
         if (text.isEmpty() && !control->textCursor().isNull()) {
             const QString preeditText = control->textCursor().block().layout()->preeditAreaText();
             alignToRight = preeditText.isEmpty()
                     ? QApplication::keyboardInputDirection() == Qt::RightToLeft
                     : preeditText.isRightToLeft();
         } else {
             alignToRight = rightToLeftText;
         }
         return setHAlign(alignToRight ? QDeclarativeTextEdit::AlignRight : QDeclarativeTextEdit::AlignLeft);
     }
     return false;
 }
focusChanged()
void QDeclarativeTextEditPrivate::focusChanged (bool hasFocus) virtual
Reimplemented from QDeclarativeItemPrivate.
Definition at line 1334 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     q->setCursorVisible(hasFocus && scene && scene->hasFocus());
     QDeclarativeItemPrivate::focusChanged(hasFocus);
 }
implicitWidth()
qreal QDeclarativeTextEditPrivate::implicitWidth () const virtual
Reimplemented from QDeclarativeItemPrivate.
Definition at line 1793 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(const QDeclarativeTextEdit);
     if (!requireImplicitWidth) {
         // We don't calculate implicitWidth unless it is required.
         // We need to force a size update now to ensure implicitWidth is calculated
         const_cast<QDeclarativeTextEditPrivate*>(this)->requireImplicitWidth = true;
         const_cast<QDeclarativeTextEdit*>(q)->updateSize();
     }
     return mImplicitWidth;
 }
init()
void QDeclarativeTextEditPrivate::init ()
Definition at line 1676 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     q->setSmooth(smooth);
     q->setAcceptedMouseButtons(Qt::LeftButton);
     q->setFlag(QGraphicsItem::ItemHasNoContents, false);
     q->setFlag(QGraphicsItem::ItemAcceptsInputMethod);
     control = new QTextControl(q);
     control->setIgnoreUnusedNavigationEvents(true);
     control->setTextInteractionFlags(Qt::LinksAccessibleByMouse | Qt::TextSelectableByKeyboard | Qt::TextEditable);
     control->setDragEnabled(false);
     // QTextControl follows the default text color
     // defined by the platform, declarative text
     // should be black by default
     QPalette pal = control->palette();
     if (pal.color(QPalette::Text) != color) {
         pal.setColor(QPalette::Text, color);
         control->setPalette(pal);
     }
     QObject::connect(control, SIGNAL(updateRequest(QRectF)), q, SLOT(updateImgCache(QRectF)));
     QObject::connect(control, SIGNAL(textChanged()), q, SLOT(q_textChanged()));
     QObject::connect(control, SIGNAL(selectionChanged()), q, SIGNAL(selectionChanged()));
     QObject::connect(control, SIGNAL(selectionChanged()), q, SLOT(updateSelectionMarkers()));
     QObject::connect(control, SIGNAL(cursorPositionChanged()), q, SLOT(updateSelectionMarkers()));
     QObject::connect(control, SIGNAL(cursorPositionChanged()), q, SIGNAL(cursorPositionChanged()));
     QObject::connect(control, SIGNAL(microFocusChanged()), q, SLOT(moveCursorDelegate()));
     QObject::connect(control, SIGNAL(linkActivated(QString)), q, SIGNAL(linkActivated(QString)));
 #ifndef QT_NO_CLIPBOARD
     QObject::connect(q, SIGNAL(readOnlyChanged(bool)), q, SLOT(q_canPasteChanged()));
     QObject::connect(QApplication::clipboard(), SIGNAL(dataChanged()), q, SLOT(q_canPasteChanged()));
     canPaste = control->canPaste();
 #endif
     document = control->document();
     document->setDefaultFont(font);
     document->setDocumentMargin(textMargin);
     document->setUndoRedoEnabled(false); // flush undo buffer.
     document->setUndoRedoEnabled(true);
     updateDefaultTextOption();
 }
mirrorChange()
void QDeclarativeTextEditPrivate::mirrorChange () virtual
Reimplemented from QDeclarativeItemPrivate.
Definition at line 618 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     if (q->isComponentComplete()) {
         if (!hAlignImplicit && (hAlign == QDeclarativeTextEdit::AlignRight || hAlign == QDeclarativeTextEdit::AlignLeft)) {
             updateDefaultTextOption();
             q->updateSize();
         }
     }
 }
relayoutDocument()
void QDeclarativeTextEditPrivate::relayoutDocument ()
Referenced by QDeclarativeTextEditPrivate().
setHAlign()
bool QDeclarativeTextEditPrivate::setHAlign (QDeclarativeTextEdit::HAlignment alignment, bool forceAlign = false)
Definition at line 589 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     if (hAlign != alignment || forceAlign) {
         hAlign = alignment;
         emit q->horizontalAlignmentChanged(alignment);
         return true;
     }
     return false;
 }
updateDefaultTextOption()
void QDeclarativeTextEditPrivate::updateDefaultTextOption ()
Definition at line 1894 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     QTextOption opt = document->defaultTextOption();
     int oldAlignment = opt.alignment();
     QDeclarativeTextEdit::HAlignment horizontalAlignment = q->effectiveHAlign();
     if (rightToLeftText) {
         if (horizontalAlignment == QDeclarativeTextEdit::AlignLeft)
             horizontalAlignment = QDeclarativeTextEdit::AlignRight;
         else if (horizontalAlignment == QDeclarativeTextEdit::AlignRight)
             horizontalAlignment = QDeclarativeTextEdit::AlignLeft;
     }
     opt.setAlignment((Qt::Alignment)(int)(horizontalAlignment | vAlign));
     QTextOption::WrapMode oldWrapMode = opt.wrapMode();
     opt.setWrapMode(QTextOption::WrapMode(wrapMode));
     if (oldWrapMode == opt.wrapMode() && oldAlignment == opt.alignment())
         return;
     document->setDefaultTextOption(opt);
 }
updateSelection()
void QDeclarativeTextEditPrivate::updateSelection ()
Definition at line 1747 of file qdeclarativetextedit.cpp.
Referenced by QDeclarativeTextEditPrivate().
 {
     Q_Q(QDeclarativeTextEdit);
     QTextCursor cursor = control->textCursor();
     bool startChange = (lastSelectionStart != cursor.selectionStart());
     bool endChange = (lastSelectionEnd != cursor.selectionEnd());
     cursor.beginEditBlock();
     cursor.setPosition(lastSelectionStart, QTextCursor::MoveAnchor);
     cursor.setPosition(lastSelectionEnd, QTextCursor::KeepAnchor);
     cursor.endEditBlock();
     control->setTextCursor(cursor);
     if(startChange)
         q->selectionStartChanged();
     if(endChange)
         q->selectionEndChanged();
 }
Properties
canPaste
bool QDeclarativeTextEditPrivate::canPaste
Definition at line 132 of file qdeclarativetextedit_p_p.h.
clickCausedFocus
bool QDeclarativeTextEditPrivate::clickCausedFocus
Definition at line 115 of file qdeclarativetextedit_p_p.h.
color
QColor QDeclarativeTextEditPrivate::color
Definition at line 100 of file qdeclarativetextedit_p_p.h.
control
QTextControl* QDeclarativeTextEditPrivate::control
Definition at line 127 of file qdeclarativetextedit_p_p.h.
cursor
QDeclarativeItem* QDeclarativeTextEditPrivate::cursor
Definition at line 124 of file qdeclarativetextedit_p_p.h.
cursorComponent
QDeclarativeComponent* QDeclarativeTextEditPrivate::cursorComponent
Definition at line 123 of file qdeclarativetextedit_p_p.h.
cursorVisible
bool QDeclarativeTextEditPrivate::cursorVisible
Definition at line 112 of file qdeclarativetextedit_p_p.h.
dirty
bool QDeclarativeTextEditPrivate::dirty
Definition at line 110 of file qdeclarativetextedit_p_p.h.
document
QTextDocument* QDeclarativeTextEditPrivate::document
Definition at line 126 of file qdeclarativetextedit_p_p.h.
focusOnPress
bool QDeclarativeTextEditPrivate::focusOnPress
Definition at line 113 of file qdeclarativetextedit_p_p.h.
font
QFont QDeclarativeTextEditPrivate::font
Definition at line 98 of file qdeclarativetextedit_p_p.h.
format
QDeclarativeTextEdit::TextFormat QDeclarativeTextEditPrivate::format
Definition at line 125 of file qdeclarativetextedit_p_p.h.
hAlign
QDeclarativeTextEdit::HAlignment QDeclarativeTextEditPrivate::hAlign
Definition at line 107 of file qdeclarativetextedit_p_p.h.
hAlignImplicit
bool QDeclarativeTextEditPrivate::hAlignImplicit
Definition at line 118 of file qdeclarativetextedit_p_p.h.
imgCache
QPixmap QDeclarativeTextEditPrivate::imgCache
Definition at line 105 of file qdeclarativetextedit_p_p.h.
imgDirty
bool QDeclarativeTextEditPrivate::imgDirty
Definition at line 109 of file qdeclarativetextedit_p_p.h.
imgStyleCache
QPixmap QDeclarativeTextEditPrivate::imgStyleCache
Definition at line 106 of file qdeclarativetextedit_p_p.h.
lastSelectionEnd
int QDeclarativeTextEditPrivate::lastSelectionEnd
Definition at line 122 of file qdeclarativetextedit_p_p.h.
lastSelectionStart
int QDeclarativeTextEditPrivate::lastSelectionStart
Definition at line 121 of file qdeclarativetextedit_p_p.h.
lineCount
int QDeclarativeTextEditPrivate::lineCount
Definition at line 130 of file qdeclarativetextedit_p_p.h.
mouseSelectionMode
QDeclarativeTextEdit::SelectionMode QDeclarativeTextEditPrivate::mouseSelectionMode
Definition at line 129 of file qdeclarativetextedit_p_p.h.
paintedSize
QSize QDeclarativeTextEditPrivate::paintedSize
Definition at line 134 of file qdeclarativetextedit_p_p.h.
persistentSelection
bool QDeclarativeTextEditPrivate::persistentSelection
Definition at line 116 of file qdeclarativetextedit_p_p.h.
requireImplicitWidth
bool QDeclarativeTextEditPrivate::requireImplicitWidth
Definition at line 117 of file qdeclarativetextedit_p_p.h.
richText
bool QDeclarativeTextEditPrivate::richText
Definition at line 111 of file qdeclarativetextedit_p_p.h.
rightToLeftText
bool QDeclarativeTextEditPrivate::rightToLeftText
Definition at line 119 of file qdeclarativetextedit_p_p.h.
selectByMouse
bool QDeclarativeTextEditPrivate::selectByMouse
Definition at line 131 of file qdeclarativetextedit_p_p.h.
selectedTextColor
QColor QDeclarativeTextEditPrivate::selectedTextColor
Definition at line 102 of file qdeclarativetextedit_p_p.h.
selectionColor
QColor QDeclarativeTextEditPrivate::selectionColor
Definition at line 101 of file qdeclarativetextedit_p_p.h.
showInputPanelOnFocus
bool QDeclarativeTextEditPrivate::showInputPanelOnFocus
Definition at line 114 of file qdeclarativetextedit_p_p.h.
Referenced by QDeclarativeTextEditPrivate().
sourceFont
QFont QDeclarativeTextEditPrivate::sourceFont
Definition at line 99 of file qdeclarativetextedit_p_p.h.
style
QString QDeclarativeTextEditPrivate::style
Definition at line 103 of file qdeclarativetextedit_p_p.h.
styleColor
QColor QDeclarativeTextEditPrivate::styleColor
Definition at line 104 of file qdeclarativetextedit_p_p.h.
text
QString QDeclarativeTextEditPrivate::text
Definition at line 97 of file qdeclarativetextedit_p_p.h.
textMargin
qreal QDeclarativeTextEditPrivate::textMargin
Definition at line 120 of file qdeclarativetextedit_p_p.h.
vAlign
QDeclarativeTextEdit::VAlignment QDeclarativeTextEditPrivate::vAlign
Definition at line 108 of file qdeclarativetextedit_p_p.h.
wrapMode
QDeclarativeTextEdit::WrapMode QDeclarativeTextEditPrivate::wrapMode
Definition at line 128 of file qdeclarativetextedit_p_p.h.
yoff
int QDeclarativeTextEditPrivate::yoff
Definition at line 133 of file qdeclarativetextedit_p_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativetextedit_p_p.h
/src/declarative/graphicsitems/qdeclarativetextedit.cpp