Qt 4.8: QTextDocumentLayout Class Reference
QTextDocumentLayout Class Reference
#include <qtextdocumentlayout_p.h>
Public Functions
virtual QRectF blockBoundingRect (const QTextBlock &block) const
Returns the bounding rectangle of block.
bool contentHasAlignment () const
int cursorWidth () const
QSizeF documentSize () const
Returns the total size of the document's layout.
void draw (QPainter *painter, const PaintContext &context)
Draws the layout with the given painter using the given context.
QSizeF dynamicDocumentSize () const
int dynamicPageCount () const
void ensureLayouted (qreal)
virtual QRectF frameBoundingRect (QTextFrame *frame) const
Returns the bounding rectangle of frame.
int hitTest (const QPointF &point, Qt::HitTestAccuracy accuracy) const
Returns the cursor postion for the given point with the specified accuracy.
qreal idealWidth () const
int layoutStatus () const
int pageCount () const
Returns the number of pages contained in the layout.
QTextDocumentLayout (QTextDocument *doc)
void setCursorWidth (int width)
void setFixedColumnWidth (int width)
void setViewport (const QRectF &viewport)
Public Functions inherited from QAbstractTextDocumentLayout
QString anchorAt (const QPointF &pos) const
Returns the reference of the anchor the given position, or an empty string if no anchor exists at that point.
QTextDocument * document () const
Returns the text document that this layout is operating on.
QTextObjectInterface * handlerForObject (int objectType) const
Returns a handler for objects of the given objectType.
QPaintDevice * paintDevice () const
Returns the paint device used to render the document's layout.
QAbstractTextDocumentLayout (QTextDocument *doc)
Creates a new text document layout for the given document.
void registerHandler (int objectType, QObject *component)
Registers the given component as a handler for items of the given objectType.
void setPaintDevice (QPaintDevice *device)
Sets the paint device used for rendering the document's layout to the given device.
~QAbstractTextDocumentLayout ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void documentChanged (int from, int oldLength, int length)
This function is called whenever the contents of the document change.
void drawInlineObject (QPainter *p, const QRectF &rect, QTextInlineObject item, int posInDocument, const QTextFormat &format)
This function is called to draw the inline object, object, with the given painter within the rectangle specified by rect using the specified text format.
void positionInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat &format)
Lays out the inline object item using the given text format.
void resizeInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat &format)
Sets the size of the inline object item corresponding to the text format.
virtual void timerEvent (QTimerEvent *e)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QAbstractTextDocumentLayout
QTextCharFormat format (int pos)
Returns the character format that is applicable at the given position.
int formatIndex (int pos)
Returns the index of the format at position pos.
QAbstractTextDocumentLayout (QAbstractTextDocumentLayoutPrivate &, QTextDocument *)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Functions
QRectF doLayout (int from, int oldLength, int length)
void layoutFinished ()
Properties
bool contentHasAlignment
int cursorWidth
qreal idealWidth
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractTextDocumentLayout
void documentSizeChanged (const QSizeF &newSize)
This signal is emitted when the size of the document layout changes to newSize.
void pageCountChanged (int newPages)
This signal is emitted when the number of pages in the layout changes; newPages is the updated page count.
void update (const QRectF &=QRectF(0., 0., 1000000000., 1000000000.))
This signal is emitted when the rectangle rect has been updated.
void updateBlock (const QTextBlock &block)
This signal is emitted when the specified block has been updated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qtextdocumentlayout_p.h.
Constructors and Destructors
QTextDocumentLayout()
QTextDocumentLayout::QTextDocumentLayout (QTextDocument * doc) explicit
Definition at line 2806 of file qtextdocumentlayout.cpp.
     : QAbstractTextDocumentLayout(*new QTextDocumentLayoutPrivate, doc)
 {
     registerHandler(QTextFormat::ImageObject, new QTextImageHandler(this));
 }
Functions
blockBoundingRect()
QRectF QTextDocumentLayout::blockBoundingRect (const QTextBlock & block) const virtual
Returns the bounding rectangle of block.
Implements QAbstractTextDocumentLayout.
Definition at line 3181 of file qtextdocumentlayout.cpp.
 {
     Q_D(const QTextDocumentLayout);
     if (d->docPrivate->pageSize.isNull() || !block.isValid())
         return QRectF();
     d->ensureLayoutedByPosition(block.position() + block.length());
     QTextFrame *frame = d->document->frameAt(block.position());
     QPointF offset;
     const int blockPos = block.position();
     while (frame) {
         QTextFrameData *fd = data(frame);
         offset += fd->position.toPointF();
         if (QTextTable *table = qobject_cast<QTextTable *>(frame)) {
             QTextTableCell cell = table->cellAt(blockPos);
             if (cell.isValid())
                 offset += static_cast<QTextTableData *>(fd)->cellPosition(cell).toPointF();
         }
         frame = frame->parentFrame();
     }
     const QTextLayout *layout = block.layout();
     QRectF rect = layout->boundingRect();
     rect.moveTopLeft(layout->position() + offset);
     return rect;
 }
contentHasAlignment()
bool QTextDocumentLayout::contentHasAlignment () const
Referenced by ensureLayouted().
cursorWidth()
int QTextDocumentLayout::cursorWidth () const
Referenced by setCursorWidth().
documentChanged()
void QTextDocumentLayout::documentChanged (int position, int charsRemoved, int charsAdded) protected virtual
This function is called whenever the contents of the document change.
A change occurs when text is inserted, removed, or a combination of these two. The change is specified by position, charsRemoved, and charsAdded corresponding to the starting character position of the change, the number of characters removed from the document, and the number of characters added.
For example, when inserting the text "Hello" into an empty document, charsRemoved would be 0 and charsAdded would be 5 (the length of the string).
Replacing text is a combination of removing and inserting. For example, if the text "Hello" gets replaced by "Hi", charsRemoved would be 5 and charsAdded would be 2.
For subclasses of QAbstractTextDocumentLayout, this is the central function where a large portion of the work to lay out and position document contents is done.
For example, in a subclass that only arranges blocks of text, an implementation of this function would have to do the following:
Determine the list of changed QTextBlock(s) using the parameters provided.
Each QTextBlock object's corresponding QTextLayout object needs to be processed. You can access the QTextBlock's layout using the QTextBlock::layout() function. This processing should take the document's page size into consideration.
If the total number of pages changed, the pageCountChanged() signal should be emitted.
If the total size changed, the documentSizeChanged() signal should be emitted.
The update() signal should be emitted to schedule a repaint of areas in the layout that require repainting.
See also
QTextLayout
Implements QAbstractTextDocumentLayout.
Definition at line 2873 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     QTextBlock blockIt = document()->findBlock(from);
     QTextBlock endIt = document()->findBlock(qMax(0, from + length - 1));
     if (endIt.isValid())
         endIt = endIt.next();
      for (; blockIt.isValid() && blockIt != endIt; blockIt = blockIt.next())
          blockIt.clearLayout();
     if (d->docPrivate->pageSize.isNull())
         return;
     QRectF updateRect;
     d->lazyLayoutStepSize = 1000;
     d->sizeChangedTimer.stop();
     d->insideDocumentChange = true;
     const int documentLength = d->docPrivate->length();
     const bool fullLayout = (oldLength == 0 && length == documentLength);
     const bool smallChange = documentLength > 0
                              && (qMax(length, oldLength) * 100 / documentLength) < 5;
     // don't show incremental layout progress (avoid scroll bar flicker)
     // if we see only a small change in the document and we're either starting
     // a layout run or we're already in progress for that and we haven't seen
     // any bigger change previously (showLayoutProgress already false)
     if (smallChange
         && (d->currentLazyLayoutPosition == -1 || d->showLayoutProgress == false))
         d->showLayoutProgress = false;
     else
         d->showLayoutProgress = true;
     if (fullLayout) {
         d->contentHasAlignment = false;
         d->currentLazyLayoutPosition = 0;
         d->checkPoints.clear();
         d->layoutStep();
     } else {
         d->ensureLayoutedByPosition(from);
         updateRect = doLayout(from, oldLength, length);
     }
     if (!d->layoutTimer.isActive() && d->currentLazyLayoutPosition != -1)
         d->layoutTimer.start(10, this);
     d->insideDocumentChange = false;
     if (d->showLayoutProgress) {
         const QSizeF newSize = dynamicDocumentSize();
         if (newSize != d->lastReportedSize) {
             d->lastReportedSize = newSize;
             emit documentSizeChanged(newSize);
         }
     }
     if (!updateRect.isValid()) {
         // don't use the frame size, it might have shrunken
         updateRect = QRectF(QPointF(0, 0), QSizeF(qreal(INT_MAX), qreal(INT_MAX)));
     }
     emit update(updateRect);
 }
documentSize()
QSizeF QTextDocumentLayout::documentSize () const virtual
Returns the total size of the document's layout.
This information can be used by display widgets to update their scroll bars correctly.
See also
documentSizeChanged(), QTextDocument::pageSize
Implements QAbstractTextDocumentLayout.
Definition at line 3093 of file qtextdocumentlayout.cpp.
 {
     Q_D(const QTextDocumentLayout);
     d->ensureLayoutFinished();
     return dynamicDocumentSize();
 }
doLayout()
QRectF QTextDocumentLayout::doLayout (int from, int oldLength, int length) private
Definition at line 2939 of file qtextdocumentlayout.cpp.
Referenced by documentChanged(), and QTextDocumentLayoutPrivate::ensureLayoutedByPosition().
 {
     Q_D(QTextDocumentLayout);
 //     qDebug("documentChange: from=%d, oldLength=%d, length=%d", from, oldLength, length);
     // mark all frames between f_start and f_end as dirty
     markFrames(d->docPrivate->rootFrame(), from, oldLength, length);
     QRectF updateRect;
     QTextFrame *root = d->docPrivate->rootFrame();
     if(data(root)->sizeDirty)
         updateRect = d->layoutFrame(root, from, from + length);
     data(root)->layoutDirty = false;
     if (d->currentLazyLayoutPosition == -1)
         layoutFinished();
     else if (d->showLayoutProgress)
         d->sizeChangedTimer.start(0, this);
     return updateRect;
 }
draw()
void QTextDocumentLayout::draw (QPainter * painter, const PaintContext & context) virtual
Draws the layout with the given painter using the given context.
Implements QAbstractTextDocumentLayout.
Definition at line 2813 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     QTextFrame *frame = d->document->rootFrame();
     QTextFrameData *fd = data(frame);
     if(fd->sizeDirty)
         return;
     if (context.clip.isValid()) {
         d->ensureLayouted(QFixed::fromReal(context.clip.bottom()));
     } else {
         d->ensureLayoutFinished();
     }
     QFixed width = fd->size.width;
     if (d->document->pageSize().width() == 0 && d->viewportRect.isValid()) {
         // we're in NoWrap mode, meaning the frame should expand to the viewport
         // so that backgrounds are drawn correctly
         fd->size.width = qMax(width, QFixed::fromReal(d->viewportRect.right()));
     }
     // Make sure we conform to the root frames bounds when drawing.
     d->clipRect = QRectF(fd->position.toPointF(), fd->size.toSizeF()).adjusted(fd->leftMargin.toReal(), 0, -fd->rightMargin.toReal(), 0);
     d->drawFrame(QPointF(), painter, context, frame);
     fd->size.width = width;
 }
drawInlineObject()
void QTextDocumentLayout::drawInlineObject (QPainter * painter, const QRectF & rect, QTextInlineObject object, int posInDocument, const QTextFormat & format) protected virtual
This function is called to draw the inline object, object, with the given painter within the rectangle specified by rect using the specified text format.
posInDocument specifies the position of the object within the document.
The default implementation calls drawObject() on the object handlers. This function is called only within Qt. Subclasses can reimplement this function to customize the drawing of inline objects.
See also
draw()
Reimplemented from QAbstractTextDocumentLayout.
Definition at line 3057 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     QTextCharFormat f = format.toCharFormat();
     Q_ASSERT(f.isValid());
     QTextFrame *frame = qobject_cast<QTextFrame *>(d->document->objectForFormat(f));
     if (frame && frame->frameFormat().position() != QTextFrameFormat::InFlow)
         return; // don't draw floating frames from inline objects here but in drawFlow instead
 //    qDebug() << "drawObject at" << r;
     QAbstractTextDocumentLayout::drawInlineObject(p, rect, item, posInDocument, format);
 }
dynamicDocumentSize()
QSizeF QTextDocumentLayout::dynamicDocumentSize () const
Definition at line 3080 of file qtextdocumentlayout.cpp.
Referenced by documentChanged(), documentSize(), dynamicPageCount(), QTextEditPrivate::relayoutDocument(), and timerEvent().
 {
     Q_D(const QTextDocumentLayout);
     return data(d->docPrivate->rootFrame())->size.toSizeF();
 }
dynamicPageCount()
int QTextDocumentLayout::dynamicPageCount () const
Definition at line 3071 of file qtextdocumentlayout.cpp.
Referenced by pageCount(), and timerEvent().
 {
     Q_D(const QTextDocumentLayout);
     const QSizeF pgSize = d->document->pageSize();
     if (pgSize.height() < 0)
         return 1;
     return qCeil(dynamicDocumentSize().height() / pgSize.height());
 }
ensureLayouted()
void QTextDocumentLayout::ensureLayouted (qreal y)
Definition at line 3252 of file qtextdocumentlayout.cpp.
Referenced by QTextEditPrivate::relayoutDocument().
 {
     d_func()->ensureLayouted(QFixed::fromReal(y));
 }
frameBoundingRect()
QRectF QTextDocumentLayout::frameBoundingRect (QTextFrame * frame) const virtual
Returns the bounding rectangle of frame.
Implements QAbstractTextDocumentLayout.
Definition at line 3152 of file qtextdocumentlayout.cpp.
 {
     Q_D(const QTextDocumentLayout);
     if (d->docPrivate->pageSize.isNull())
         return QRectF();
     d->ensureLayoutFinished();
     return d->frameBoundingRectInternal(frame);
 }
hitTest()
int QTextDocumentLayout::hitTest (const QPointF & point, Qt::HitTestAccuracy accuracy) const virtual
Returns the cursor postion for the given point with the specified accuracy.
Returns -1 if no valid cursor position was found.
Implements QAbstractTextDocumentLayout.
Definition at line 2963 of file qtextdocumentlayout.cpp.
 {
     Q_D(const QTextDocumentLayout);
     d->ensureLayouted(QFixed::fromReal(point.y()));
     QTextFrame *f = d->docPrivate->rootFrame();
     int position = 0;
     QTextLayout *l = 0;
     QFixedPoint pointf;
     pointf.x = QFixed::fromReal(point.x());
     pointf.y = QFixed::fromReal(point.y());
     QTextDocumentLayoutPrivate::HitPoint p = d->hitTest(f, pointf, &position, &l, accuracy);
     if (accuracy == Qt::ExactHit && p < QTextDocumentLayoutPrivate::PointExact)
         return -1;
     // ensure we stay within document bounds
     int lastPos = f->lastPosition();
     if (l && !l->preeditAreaText().isEmpty())
         lastPos += l->preeditAreaText().length();
     if (position > lastPos)
         position = lastPos;
     else if (position < 0)
         position = 0;
     return position;
 }
idealWidth()
qreal QTextDocumentLayout::idealWidth () const
Referenced by ensureLayouted().
layoutFinished()
void QTextDocumentLayout::layoutFinished () private
Definition at line 3242 of file qtextdocumentlayout.cpp.
Referenced by doLayout().
 {
     Q_D(QTextDocumentLayout);
     d->layoutTimer.stop();
     if (!d->insideDocumentChange)
         d->sizeChangedTimer.start(0, this);
     // reset
     d->showLayoutProgress = true;
 }
layoutStatus()
int QTextDocumentLayout::layoutStatus () const
Definition at line 3210 of file qtextdocumentlayout.cpp.
 {
     Q_D(const QTextDocumentLayout);
     int pos = d->currentLazyLayoutPosition;
     if (pos == -1)
         return 100;
     return pos * 100 / d->document->docHandle()->length();
 }
pageCount()
int QTextDocumentLayout::pageCount () const virtual
Returns the number of pages contained in the layout.
See also
pageCountChanged()
Implements QAbstractTextDocumentLayout.
Definition at line 3086 of file qtextdocumentlayout.cpp.
 {
     Q_D(const QTextDocumentLayout);
     d->ensureLayoutFinished();
     return dynamicPageCount();
 }
positionInlineObject()
void QTextDocumentLayout::positionInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat & format) protected virtual
Lays out the inline object item using the given text format.
posInDocument specifies the position of the object within the document.
The default implementation does nothing. This function is called only within Qt. Subclasses can reimplement this function to customize the position of inline objects.
See also
drawInlineObject()
Reimplemented from QAbstractTextDocumentLayout.
Definition at line 3030 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     Q_UNUSED(posInDocument);
     if (item.width() != 0)
         // inline
         return;
     QTextCharFormat f = format.toCharFormat();
     Q_ASSERT(f.isValid());
     QTextObjectHandler handler = d->handlers.value(f.objectType());
     if (!handler.component)
         return;
     QTextFrame *frame = qobject_cast<QTextFrame *>(d->document->objectForFormat(f));
     if (!frame)
         return;
     QTextBlock b = d->document->findBlock(frame->firstPosition());
     QTextLine line;
     if (b.position() <= frame->firstPosition() && b.position() + b.length() > frame->lastPosition())
         line = b.layout()->lineAt(b.layout()->lineCount()-1);
 //     qDebug() << "layoutObject: line.isValid" << line.isValid() << b.position() << b.length() <<
 //         frame->firstPosition() << frame->lastPosition();
     d->positionFloat(frame, line.isValid() ? &line : 0);
 }
resizeInlineObject()
void QTextDocumentLayout::resizeInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat & format) protected virtual
Sets the size of the inline object item corresponding to the text format.
posInDocument specifies the position of the object within the document.
The default implementation resizes the item to the size returned by the object handler's intrinsicSize() function. This function is called only within Qt. Subclasses can reimplement this function to customize the resizing of inline objects.
Reimplemented from QAbstractTextDocumentLayout.
Definition at line 2989 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     QTextCharFormat f = format.toCharFormat();
     Q_ASSERT(f.isValid());
     QTextObjectHandler handler = d->handlers.value(f.objectType());
     if (!handler.component)
         return;
     QSizeF intrinsic = handler.iface->intrinsicSize(d->document, posInDocument, format);
     QTextFrameFormat::Position pos = QTextFrameFormat::InFlow;
     QTextFrame *frame = qobject_cast<QTextFrame *>(d->document->objectForFormat(f));
     if (frame) {
         pos = frame->frameFormat().position();
         QTextFrameData *fd = data(frame);
         fd->sizeDirty = false;
         fd->size = QFixedSize::fromSizeF(intrinsic);
         fd->minimumWidth = fd->maximumWidth = fd->size.width;
     }
     QSizeF inlineSize = (pos == QTextFrameFormat::InFlow ? intrinsic : QSizeF(0, 0));
     item.setWidth(inlineSize.width());
     QFontMetrics m(f.font());
     switch (f.verticalAlignment())
     {
     case QTextCharFormat::AlignMiddle:
         item.setDescent(inlineSize.height() / 2);
         item.setAscent(inlineSize.height() / 2 - 1);
         break;
     case QTextCharFormat::AlignBaseline:
         item.setDescent(m.descent());
         item.setAscent(inlineSize.height() - m.descent() - 1);
         break;
     default:
         item.setDescent(0);
         item.setAscent(inlineSize.height() - 1);
     }
 }
setCursorWidth()
void QTextDocumentLayout::setCursorWidth (int width)
Definition at line 3134 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     d->cursorWidth = width;
 }
setFixedColumnWidth()
void QTextDocumentLayout::setFixedColumnWidth (int width)
Definition at line 3146 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     d->fixedColumnWidth = width;
 }
setViewport()
void QTextDocumentLayout::setViewport (const QRectF & viewport)
Definition at line 2841 of file qtextdocumentlayout.cpp.
Referenced by QTextEditPrivate::paint(), and QGraphicsTextItem::paint().
 {
     Q_D(QTextDocumentLayout);
     d->viewportRect = viewport;
 }
timerEvent()
void QTextDocumentLayout::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 3219 of file qtextdocumentlayout.cpp.
 {
     Q_D(QTextDocumentLayout);
     if (e->timerId() == d->layoutTimer.timerId()) {
         if (d->currentLazyLayoutPosition != -1)
             d->layoutStep();
     } else if (e->timerId() == d->sizeChangedTimer.timerId()) {
         d->lastReportedSize = dynamicDocumentSize();
         emit documentSizeChanged(d->lastReportedSize);
         d->sizeChangedTimer.stop();
         if (d->currentLazyLayoutPosition == -1) {
             const int newCount = dynamicPageCount();
             if (newCount != d->lastPageCount) {
                 d->lastPageCount = newCount;
                 emit pageCountChanged(newCount);
             }
         }
     } else {
         QAbstractTextDocumentLayout::timerEvent(e);
     }
 }
Properties
contentHasAlignment
bool QTextDocumentLayout::contentHasAlignment private
Definition at line 72 of file qtextdocumentlayout_p.h.
cursorWidth
int QTextDocumentLayout::cursorWidth private
Definition at line 70 of file qtextdocumentlayout_p.h.
idealWidth
qreal QTextDocumentLayout::idealWidth private
Definition at line 71 of file qtextdocumentlayout_p.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextdocumentlayout_p.h
/src/gui/text/qtextdocumentlayout.cpp