Qt 4.8: QPatternist::ValidationError Class Reference
QPatternist::ValidationError Class Reference
Used for signalling casting errors.
#include <qvalidationerror_p.h>
Public Types
typedef QExplicitlySharedDataPointer< ValidationError > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
ReportContext::ErrorCode errorCode () const
virtual bool hasError () const
QString message () const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr createError (const QString &description=QString(), const ReportContext::ErrorCode=ReportContext::FORG0001)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
ValidationError (const QString &msg, const ReportContext::ErrorCode code)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Protected Variables
const ReportContext::ErrorCode m_code
const QString m_message
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Used for signalling casting errors.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 70 of file qvalidationerror_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<ValidationError> QPatternist::ValidationError::Ptr
Definition at line 73 of file qvalidationerror_p.h.
Constructors and Destructors
ValidationError()
ValidationError::ValidationError (const QString & msg, const ReportContext::ErrorCode code) protected
Definition at line 49 of file qvalidationerror.cpp.
Referenced by createError().
                                                                     : m_message(msg),
                                                                         m_code(code)
 {
 }
Functions
createError()
AtomicValue::Ptr ValidationError::createError (const QString & description = QString(), const ReportContext::ErrorCode code = ReportContext::FORG0001) static
Creates a ValidationError instance that represents a type error.
Parameters
description A detailed description of what that made the cast fail, if any. If null, which QString() creates, a generic message will be used.
Definition at line 55 of file qvalidationerror.cpp.
Referenced by QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), QPatternist::NumericToDerivedIntegerCaster< type >::castFrom(), QPatternist::AbstractDateTime::create(), QPatternist::DerivedString< TypeToken >::error(), QPatternist::Base64Binary::fromLexical(), QPatternist::AbstractFloat< isDouble >::fromLexical(), QPatternist::Integer::fromLexical(), QPatternist::HexBinary::fromLexical(), QPatternist::Decimal::fromLexical(), QPatternist::Boolean::fromLexical(), QPatternist::AnyURI::fromLexical(), QPatternist::XsdTypeChecker::fromLexical(), QPatternist::DerivedInteger< DerivedType >::fromLexical(), and QPatternist::DerivedInteger< DerivedType >::fromValue().
 {
     return ValidationError::Ptr(new ValidationError(description, code));
 }
errorCode()
ReportContext::ErrorCode ValidationError::errorCode () const
Returns
the error code this ValidationError represents. Typically, this is ReportContext::FORG0001.
Definition at line 85 of file qvalidationerror.cpp.
 {
     return m_code;
 }
hasError()
bool ValidationError::hasError () const virtual
Returns
always true
Reimplemented from QPatternist::AtomicValue.
Definition at line 61 of file qvalidationerror.cpp.
 {
     return true;
 }
message()
QString ValidationError::message () const
A human readable, translated message describing the error.
Definition at line 72 of file qvalidationerror.cpp.
 {
     return m_message;
 }
stringValue()
QString ValidationError::stringValue () const virtual
Always results in an assert crash.
Implements QPatternist::AtomicValue.
Definition at line 66 of file qvalidationerror.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO, "stringValue() asked for ValidationError -- it makes no sense.");
     return QString();
 }
type()
ItemType::Ptr ValidationError::type () const virtual
Always results in an assert crash.
Implements QPatternist::AtomicValue.
Definition at line 77 of file qvalidationerror.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "This function should never be called, the caller "
                "didn't check whether the AtomicValue was an ValidationError.");
     return ItemType::Ptr();
 }
Properties
m_code
const ReportContext::ErrorCode QPatternist::ValidationError::m_code protected
Definition at line 115 of file qvalidationerror_p.h.
Referenced by errorCode().
m_message
const QString QPatternist::ValidationError::m_message protected
Definition at line 114 of file qvalidationerror_p.h.
Referenced by message().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qvalidationerror_p.h
/src/xmlpatterns/data/qvalidationerror.cpp