Qt 4.8: QAbstractItemDelegate Class Reference
QAbstractItemDelegate Class Reference abstract
The QAbstractItemDelegate class is used to display and edit data items from a model.
#include <qabstractitemdelegate.h>
Public Types
enum EndEditHint {
NoHint, EditNextItem, EditPreviousItem, SubmitModelCache,
RevertModelCache
}
This enum describes the different hints that the delegate can give to the model and view components to make editing data in a model a comfortable experience for the user.
Public Slots
bool helpEvent (QHelpEvent *event, QAbstractItemView *view, const QStyleOptionViewItem &option, const QModelIndex &index)
Whenever a help event occurs, this function is called with the event view option and the index that corresponds to the item where the event occurs.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint=NoHint)
This signal is emitted when the user has finished editing an item using the specified editor.
void commitData (QWidget *editor)
This signal must be emitted when the editor widget has completed editing the data, and wants to write it back into the model.
void sizeHintChanged (const QModelIndex &)
This signal must be emitted when the sizeHint() of index changed.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
Returns the editor to be used for editing the data item with the given index.
virtual bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index)
When editing of an item starts, this function is called with the event that triggered the editing, the model, the index of the item, and the option used for rendering the item.
virtual void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const =0
This pure abstract function must be reimplemented if you want to provide custom rendering.
QAbstractItemDelegate (QObject *parent=0)
Creates a new abstract item delegate with the given parent.
virtual void setEditorData (QWidget *editor, const QModelIndex &index) const
Sets the contents of the given editor to the data for the item at the given index.
virtual void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
Sets the data for the item at the given index in the model to the contents of the given editor.
virtual QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const =0
This pure abstract function must be reimplemented if you want to provide custom rendering.
virtual void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
Updates the geometry of the editor for the item with the given index, according to the rectangle specified in the option.
virtual ~QAbstractItemDelegate ()
Destroys the abstract item delegate.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QString elidedText (const QFontMetrics &fontMetrics, int width, Qt::TextElideMode mode, const QString &text)
Use QFontMetrics::elidedText() instead.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
QAbstractItemDelegate (QObjectPrivate &, QObject *parent=0)
Creates a new abstract item delegate with the given parent.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractItemDelegate class is used to display and edit data items from a model.
A QAbstractItemDelegate provides the interface and common functionality for delegates in the model/view architecture. Delegates display individual items in views, and handle the editing of model data.
The QAbstractItemDelegate class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
To render an item in a custom way, you must implement paint() and sizeHint(). The QItemDelegate class provides default implementations for these functions; if you do not need custom rendering, subclass that class instead.
We give an example of drawing a progress bar in items; in our case for a package management program.
We create the WidgetDelegate class, which inherits from QStyledItemDelegate. We do the drawing in the paint() function:
void WidgetDelegate::paint(QPainter *painter, const QStyleOptionViewItem &option,
                           const QModelIndex &index) const
{
    if (index.column() == 1) {
        int progress = index.data().toInt();
        QStyleOptionProgressBar progressBarOption;
        progressBarOption.rect = option.rect;
        progressBarOption.minimum = 0;
        progressBarOption.maximum = 100;
        progressBarOption.progress = progress;
        progressBarOption.text = QString::number(progress) + "%";
        progressBarOption.textVisible = true;
        QApplication::style()->drawControl(QStyle::CE_ProgressBar,
                                           &progressBarOption, painter);
    } else
        QStyledItemDelegate::paint(painter, option, index);
Notice that we use a QStyleOptionProgressBar and initialize its members. We can then use the current QStyle to draw it.
To provide custom editing, there are two approaches that can be used. The first approach is to create an editor widget and display it directly on top of the item. To do this you must reimplement createEditor() to provide an editor widget, setEditorData() to populate the editor with the data from the model, and setModelData() so that the delegate can update the model with data from the editor.
The second approach is to handle user events directly by reimplementing editorEvent().
See also
{model-view-programming}{Model/View Programming}, QItemDelegate, {Pixelator Example}, QStyledItemDelegate, QStyle
Definition at line 62 of file qabstractitemdelegate.h.
Enumerations
EndEditHint
enum QAbstractItemDelegate::EndEditHint
This enum describes the different hints that the delegate can give to the model and view components to make editing data in a model a comfortable experience for the user.
NoHint There is no recommended action to be performed.
These hints let the delegate influence the behavior of the view:
EditNextItem The view should use the delegate to open an editor on the next item in the view.
EditPreviousItem The view should use the delegate to open an editor on the previous item in the view.
Note that custom views may interpret the concepts of next and previous differently.
The following hints are most useful when models are used that cache data, such as those that manipulate data locally in order to increase performance or conserve network bandwidth.
SubmitModelCache If the model caches data, it should write out cached data to the underlying data store.
RevertModelCache If the model caches data, it should discard cached data and replace it with data from the underlying data store.
Although models and views should respond to these hints in appropriate ways, custom components may ignore any or all of them if they are not relevant.
Enumerator
NoHint
EditNextItem
EditPreviousItem
SubmitModelCache
RevertModelCache
Definition at line 68 of file qabstractitemdelegate.h.
                      {
         NoHint,
         EditNextItem,
         EditPreviousItem,
         SubmitModelCache,
         RevertModelCache
     };
Constructors and Destructors
QAbstractItemDelegate() [1/2]
QAbstractItemDelegate::QAbstractItemDelegate (QObject * parent = 0) explicit
Creates a new abstract item delegate with the given parent.
Definition at line 184 of file qabstractitemdelegate.cpp.
     : QObject(parent)
 {
 }
~QAbstractItemDelegate()
QAbstractItemDelegate::~QAbstractItemDelegate () virtual
Destroys the abstract item delegate.
Definition at line 207 of file qabstractitemdelegate.cpp.
 {
 }
QAbstractItemDelegate() [2/2]
QAbstractItemDelegate::QAbstractItemDelegate (QObjectPrivate & dd, QObject * parent = 0) protected
Creates a new abstract item delegate with the given parent.
Warning
This function is not part of the public interface.
Definition at line 198 of file qabstractitemdelegate.cpp.
     : QObject(dd, parent)
 {
 }
Functions
closeEditor
void QAbstractItemDelegate::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint = NoHint) signal
This signal is emitted when the user has finished editing an item using the specified editor.
The hint provides a way for the delegate to influence how the model and view behave after editing is completed. It indicates to these components what action should be performed next to provide a comfortable editing experience for the user. For example, if EditNextItem is specified, the view should use a delegate to open an editor on the next item in the model.
See also
EndEditHint
Referenced by QStyledItemDelegate::eventFilter(), and QItemDelegate::eventFilter().
commitData
void QAbstractItemDelegate::commitData (QWidget * editor) signal
This signal must be emitted when the editor widget has completed editing the data, and wants to write it back into the model.
Referenced by QStyledItemDelegate::eventFilter(), and QItemDelegate::eventFilter().
createEditor()
QWidget * QAbstractItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Returns the editor to be used for editing the data item with the given index.
Note that the index contains information about the model being used. The editor's parent widget is specified by parent, and the item options by option.
The base implementation returns 0. If you want custom editing you will need to reimplement this function.
The returned editor widget should have Qt::StrongFocus; otherwise, QMouseEvent received by the widget will propagate to the view. The view's background will shine through unless the editor paints its own background (e.g., with QWidget::setAutoFillBackground()).
See also
setModelData() setEditorData()
Reimplemented in QPPDOptionsEditor, QScriptBreakpointsItemDelegate, QScriptDebuggerLocalsItemDelegate, QItemDelegate, and QStyledItemDelegate.
Definition at line 252 of file qabstractitemdelegate.cpp.
Referenced by QAbstractItemViewPrivate::editor().
 {
     return 0;
 }
editorEvent()
bool QAbstractItemDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) virtual
When editing of an item starts, this function is called with the event that triggered the editing, the model, the index of the item, and the option used for rendering the item.
Mouse events are sent to editorEvent() even if they don't start editing of the item. This can, for instance, be useful if you wish to open a context menu when the right mouse button is pressed on an item.
The base implementation returns false (indicating that it has not handled the event).
Reimplemented in QItemDelegate, and QStyledItemDelegate.
Definition at line 321 of file qabstractitemdelegate.cpp.
Referenced by QAbstractItemViewPrivate::sendDelegateEvent().
 {
     // do nothing
     return false;
 }
elidedText()
QString QAbstractItemDelegate::elidedText (const QFontMetrics & fontMetrics, int width, Qt::TextElideMode mode, const QString & text) static
Use QFontMetrics::elidedText() instead.
QFontMetrics fm = ... QString str = QAbstractItemDelegate::elidedText(fm, width, mode, text); QFontMetrics fm = ... QString str = fm.elidedText(text, mode, width);
Definition at line 347 of file qabstractitemdelegate.cpp.
Referenced by QScriptDebuggerLocalsItemDelegate::paint().
 {
     return fontMetrics.elidedText(text, mode, width);
 }
helpEvent
bool QAbstractItemDelegate::helpEvent (QHelpEvent * event, QAbstractItemView * view, const QStyleOptionViewItem & option, const QModelIndex & index) slot
Whenever a help event occurs, this function is called with the event view option and the index that corresponds to the item where the event occurs.
Since
4.3
Returns true if the delegate can handle the event; otherwise returns false. A return value of true indicates that the data obtained using the index had the required role.
For QEvent::ToolTip and QEvent::WhatsThis events that were handled successfully, the relevant popup may be shown depending on the user's system configuration.
See also
QHelpEvent
Definition at line 372 of file qabstractitemdelegate.cpp.
 {
     Q_UNUSED(option);
     if (!event || !view)
         return false;
     switch (event->type()) {
 #ifndef QT_NO_TOOLTIP
     case QEvent::ToolTip: {
         QHelpEvent *he = static_cast<QHelpEvent*>(event);
         QVariant tooltip = index.data(Qt::ToolTipRole);
         if (tooltip.canConvert<QString>()) {
             QToolTip::showText(he->globalPos(), tooltip.toString(), view);
             return true;
         }
         break;}
 #endif
 #ifndef QT_NO_WHATSTHIS
     case QEvent::QueryWhatsThis: {
         if (index.data(Qt::WhatsThisRole).isValid())
             return true;
         break; }
     case QEvent::WhatsThis: {
         QHelpEvent *he = static_cast<QHelpEvent*>(event);
         QVariant whatsthis = index.data(Qt::WhatsThisRole);
         if (whatsthis.canConvert<QString>()) {
             QWhatsThis::showText(he->globalPos(), whatsthis.toString(), view);
             return true;
         }
         break ; }
 #endif
     default:
         break;
     }
     return false;
 }
paint()
void QAbstractItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const pure virtual
This pure abstract function must be reimplemented if you want to provide custom rendering.
Use the painter and style option to render the item specified by the item index.
If you reimplement this you must also reimplement sizeHint().
Implemented in QCalendarDelegate, QComboBoxDelegate, QComboMenuDelegate, QScriptDebuggerLocalsItemDelegate, QCompleterItemDelegate, QColumnViewDelegate, QFontFamilyDelegate, QItemDelegate, and QStyledItemDelegate.
setEditorData()
void QAbstractItemDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const virtual
Sets the contents of the given editor to the data for the item at the given index.
Note that the index contains information about the model being used.
The base implementation does nothing. If you want custom editing you will need to reimplement this function.
See also
setModelData()
Reimplemented in QPPDOptionsEditor, QItemDelegate, and QStyledItemDelegate.
Definition at line 269 of file qabstractitemdelegate.cpp.
Referenced by QAbstractItemView::dataChanged(), QAbstractItemViewPrivate::editor(), QDataWidgetMapperPrivate::populate(), and QAbstractItemViewPrivate::updateEditorData().
 {
     // do nothing
 }
setModelData()
void QAbstractItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const virtual
Sets the data for the item at the given index in the model to the contents of the given editor.
The base implementation does nothing. If you want custom editing you will need to reimplement this function.
See also
setEditorData()
Reimplemented in QPPDOptionsEditor, QScriptBreakpointsItemDelegate, QScriptDebuggerLocalsItemDelegate, QItemDelegate, and QStyledItemDelegate.
Definition at line 284 of file qabstractitemdelegate.cpp.
Referenced by QDataWidgetMapperPrivate::commit(), and QAbstractItemView::commitData().
 {
     // do nothing
 }
sizeHint()
QSize QAbstractItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const pure virtual
This pure abstract function must be reimplemented if you want to provide custom rendering.
The options are specified by option and the model item by index.
If you reimplement this you must also reimplement paint().
Implemented in QComboBoxDelegate, QComboMenuDelegate, QFontFamilyDelegate, QItemDelegate, and QStyledItemDelegate.
Referenced by QListViewPrivate::itemSize(), and QTreeViewPrivate::paintAlternatingRowColors().
sizeHintChanged
void QAbstractItemDelegate::sizeHintChanged (const QModelIndex & index) signal
This signal must be emitted when the sizeHint() of index changed.
Since
4.4
Views automatically connect to this signal and relayout items as necessary.
updateEditorGeometry()
void QAbstractItemDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Updates the geometry of the editor for the item with the given index, according to the rectangle specified in the option.
If the item has an internal layout, the editor will be laid out accordingly. Note that the index contains information about the model being used.
The base implementation does nothing. If you want custom editing you must reimplement this function.
Reimplemented in QItemDelegate, and QStyledItemDelegate.
Definition at line 301 of file qabstractitemdelegate.cpp.
Referenced by QAbstractItemViewPrivate::editor(), and QAbstractItemView::updateEditorGeometries().
 {
     // do nothing
 }
The documentation for this class was generated from the following files:
/src/gui/itemviews/qabstractitemdelegate.h
/src/gui/itemviews/qabstractitemdelegate.cpp