Qt 4.8: QScriptScriptData Class Reference
QScriptScriptData Class Reference
The QScriptScriptData class holds data associated with a script.
#include <qscriptscriptdata_p.h>
Public Functions
int baseLineNumber () const
QString contents () const
QString fileName () const
bool isValid () const
QStringList lines (int startLineNumber, int count) const
bool operator!= (const QScriptScriptData &other) const
QScriptScriptData & operator= (const QScriptScriptData &other)
bool operator== (const QScriptScriptData &other) const
QScriptScriptData ()
QScriptScriptData (const QString &contents, const QString &fileName, int baseLineNumber, const QDateTime &timeStamp=QDateTime())
QScriptScriptData (const QScriptScriptData &other)
QDateTime timeStamp () const
~QScriptScriptData ()
Properties
QScopedSharedPointer< QScriptScriptDataPrivate > d_ptr
Friends
Q_AUTOTEST_EXPORT QDataStream & operator<< (QDataStream &, const QScriptScriptData &)
Q_AUTOTEST_EXPORT QDataStream & operator>> (QDataStream &, QScriptScriptData &)
Detailed Description
The QScriptScriptData class holds data associated with a script.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 68 of file qscriptscriptdata_p.h.
Constructors and Destructors
QScriptScriptData() [1/3]
QScriptScriptData::QScriptScriptData ()
Definition at line 84 of file qscriptscriptdata.cpp.
     : d_ptr(0)
 {
 }
QScriptScriptData() [2/3]
QScriptScriptData::QScriptScriptData (const QString & contents, const QString & fileName, int baseLineNumber, const QDateTime & timeStamp = QDateTime())
Definition at line 89 of file qscriptscriptdata.cpp.
     : d_ptr(new QScriptScriptDataPrivate)
 {
     d_ptr->contents = contents;
     d_ptr->fileName = fileName;
     d_ptr->baseLineNumber = baseLineNumber;
     if (timeStamp.isValid())
         d_ptr->timeStamp = timeStamp;
     else
         d_ptr->timeStamp = QDateTime::currentDateTime();
     d_ptr->ref.ref();
 }
QScriptScriptData() [3/3]
QScriptScriptData::QScriptScriptData (const QScriptScriptData & other)
Definition at line 103 of file qscriptscriptdata.cpp.
     : d_ptr(other.d_ptr.data())
 {
     if (d_ptr)
         d_ptr->ref.ref();
 }
~QScriptScriptData()
QScriptScriptData::~QScriptScriptData ()
Definition at line 110 of file qscriptscriptdata.cpp.
 {
 }
Functions
baseLineNumber()
int QScriptScriptData::baseLineNumber () const
Definition at line 145 of file qscriptscriptdata.cpp.
Referenced by QScriptDebuggerScriptsModel::data(), QScriptScriptData(), scriptDataToScriptValue(), and QScriptDebuggerCodeWidget::setCurrentScript().
 {
     Q_D(const QScriptScriptData);
     if (!d)
         return -1;
     return d->baseLineNumber;
 }
contents()
QString QScriptScriptData::contents () const
Definition at line 120 of file qscriptscriptdata.cpp.
Referenced by QScriptDebuggerScriptsModel::data(), QScriptScriptData(), scriptDataToScriptValue(), and QScriptDebuggerCodeWidget::setCurrentScript().
 {
     Q_D(const QScriptScriptData);
     if (!d)
         return QString();
     return d->contents;
 }
fileName()
QString QScriptScriptData::fileName () const
Definition at line 137 of file qscriptscriptdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), QScriptDebuggerPrivate::_q_toggleBreakpoint(), QScriptDebuggerBackendPrivate::breakpoint(), QScriptDebuggerScriptsModel::data(), QScriptDebuggerBackendPrivate::debuggerInvocationRequest(), QScriptDebuggerBackendPrivate::exception(), QScriptDebuggerBackendPrivate::forcedReturn(), QScriptDebuggerBackendPrivate::interrupted(), QScriptDebuggerBackendPrivate::locationReached(), QScriptScriptData(), QScriptDebuggerScriptsModel::resolveScript(), scriptDataToScriptValue(), QScriptDebuggerAgent::scriptUnload(), and QScriptDebuggerBackendPrivate::stepped().
 {
     Q_D(const QScriptScriptData);
     if (!d)
         return QString();
     return d->fileName;
 }
isValid()
bool QScriptScriptData::isValid () const
Definition at line 161 of file qscriptscriptdata.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and QScriptDebuggerCodeWidget::setCurrentScript().
 {
     Q_D(const QScriptScriptData);
     return (d != 0);
 }
lines()
QStringList QScriptScriptData::lines (int startLineNumber, int count) const
Definition at line 128 of file qscriptscriptdata.cpp.
Referenced by QScriptDebuggerShowLineJob::handleResponse().
 {
     Q_D(const QScriptScriptData);
     if (!d)
         return QStringList();
     QStringList allLines = d->contents.split(QLatin1Char('\n'));
     return allLines.mid(qMax(0, startLineNumber - d->baseLineNumber), count);
 }
operator!=()
bool QScriptScriptData::operator!= (const QScriptScriptData & other) const
Definition at line 180 of file qscriptscriptdata.cpp.
 {
     return !(*this == other);
 }
operator=()
QScriptScriptData & QScriptScriptData::operator= (const QScriptScriptData & other)
Definition at line 114 of file qscriptscriptdata.cpp.
 {
     d_ptr.assign(other.d_ptr.data());
     return *this;
 }
operator==()
bool QScriptScriptData::operator== (const QScriptScriptData & other) const
Definition at line 167 of file qscriptscriptdata.cpp.
 {
     Q_D(const QScriptScriptData);
     const QScriptScriptDataPrivate *od = other.d_func();
     if (d == od)
         return true;
     if (!d || !od)
         return false;
     return ((d->contents == od->contents)
             && (d->fileName == od->fileName)
             && (d->baseLineNumber == od->baseLineNumber));
 }
timeStamp()
QDateTime QScriptScriptData::timeStamp () const
Definition at line 153 of file qscriptscriptdata.cpp.
 {
     Q_D(const QScriptScriptData);
     if (!d)
         return QDateTime();
     return d->timeStamp;
 }
Friends and Related Functions
operator<<
Q_AUTOTEST_EXPORT QDataStream& operator<< (QDataStream & , const QScriptScriptData &) friend
Definition at line 185 of file qscriptscriptdata.cpp.
 {
     const QScriptScriptDataPrivate *d = data.d_ptr.data();
     if (d) {
         out << d->contents;
         out << d->fileName;
         out << qint32(d->baseLineNumber);
     } else {
         out << QString();
         out << QString();
         out << qint32(0);
     }
     return out;
 }
operator>>
Q_AUTOTEST_EXPORT QDataStream& operator>> (QDataStream & , QScriptScriptData &) friend
Definition at line 200 of file qscriptscriptdata.cpp.
 {
     if (!data.d_ptr) {
         data.d_ptr.reset(new QScriptScriptDataPrivate());
         data.d_ptr->ref.ref();
     }
     QScriptScriptDataPrivate *d = data.d_ptr.data();
     in >> d->contents;
     in >> d->fileName;
     qint32 ln;
     in >> ln;
     d->baseLineNumber = ln;
     return in;
 }
Properties
d_ptr
QScopedSharedPointer<QScriptScriptDataPrivate> QScriptScriptData::d_ptr private
Definition at line 94 of file qscriptscriptdata_p.h.
Referenced by operator<<(), operator=(), operator>>(), and QScriptScriptData().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptscriptdata_p.h
/src/scripttools/debugging/qscriptscriptdata.cpp