Qt 4.8: QVGPixmapData Class Reference
QVGPixmapData Class Reference
#include <qpixmapdata_vg_p.h>
Public Functions
QImage * buffer ()
void copy (const QPixmapData *data, const QRect &rect)
QPixmapData * createCompatiblePixmapData () const
virtual void detachImageFromPool ()
virtual void ensureReadback (bool readOnly) const
void fill (const QColor &color)
bool fromData (const uchar *buffer, uint len, const char *format, Qt::ImageConversionFlags flags)
bool fromFile (const QString &filename, const char *format, Qt::ImageConversionFlags flags)
void fromImage (const QImage &image, Qt::ImageConversionFlags flags)
void fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags)
bool hasAlphaChannel () const
virtual void hibernate ()
bool isValid () const
QPaintEngine * paintEngine () const
QVGPixmapData (PixelType type)
virtual void reclaimImages ()
void resize (int width, int height)
void setAlphaChannel (const QPixmap &alphaChannel)
QSize size () const
QImage toImage () const
virtual VGImage toVGImage ()
virtual VGImage toVGImage (qreal opacity)
~QVGPixmapData ()
Public Functions inherited from QPixmapData
virtual QPixmap alphaChannel () const
qint64 cacheKey () const
ClassId classId () const
int colorCount () const
int depth () const
int height () const
bool isNull () const
virtual QBitmap mask () const
QT_DEPRECATED int numColors () const
PixelType pixelType () const
QPixmapData (PixelType pixelType, int classId)
virtual QPixmapData * runtimeData () const
virtual bool scroll (int dx, int dy, const QRect &rect)
int serialNumber () const
virtual void setMask (const QBitmap &mask)
virtual QImage toImage (const QRect &rect) const
virtual QPixmap transformed (const QTransform &matrix, Qt::TransformationMode mode) const
int width () const
virtual ~QPixmapData ()
Protected Functions
void createPixmapForImage (QImage &image, Qt::ImageConversionFlags flags, bool inPlace)
void destroyImageAndContext ()
void destroyImages ()
void forceToImage (bool allowReadback=true)
QImage::Format idealFormat (QImage *image, Qt::ImageConversionFlags flags) const
int metric (QPaintDevice::PaintDeviceMetric metric) const
QImage::Format sourceFormat () const
void updateSerial ()
Protected Functions inherited from QPixmapData
void setSerialNumber (int serNo)
Protected Variables
qreal cachedOpacity
QEglContext * context
bool inImagePool
QSize prevSize
bool recreate
QVolatileImage source
VGImage vgImage
VGImage vgImageOpacity
Protected Variables inherited from QPixmapData
int d
int h
bool is_null
int w
Properties
bool inLRU
QVGPixmapData * next
QVGPixmapData * nextLRU
QVGPixmapData * prev
QVGPixmapData * prevLRU
Friends
void qt_vg_hibernate_pixmaps (QVGSharedContext *context)
void qt_vg_register_pixmap (QVGPixmapData *pd)
void qt_vg_unregister_pixmap (QVGPixmapData *pd)
class QVGImagePool
class QVGPaintEngine
Additional Inherited Members
Public Types inherited from QPixmapData
enum ClassId {
RasterClass, X11Class, MacClass, DirectFBClass,
OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
CustomClass = 1024
}
enum PixelType { PixmapType, BitmapType }
Static Public Functions inherited from QPixmapData
static QPixmapData * create (int w, int h, PixelType type)
Detailed Description
Definition at line 81 of file qpixmapdata_vg_p.h.
Constructors and Destructors
QVGPixmapData()
QVGPixmapData::QVGPixmapData (PixelType type)
Definition at line 60 of file qpixmapdata_vg.cpp.
Referenced by createCompatiblePixmapData().
     : QPixmapData(type, OpenVGClass)
 {
     Q_ASSERT(type == QPixmapData::PixmapType);
     vgImage = VG_INVALID_HANDLE;
     vgImageOpacity = VG_INVALID_HANDLE;
     cachedOpacity = 1.0f;
     recreate = true;
     inImagePool = false;
     inLRU = false;
 #if defined(Q_OS_SYMBIAN)
     nativeImageHandleProvider = 0;
     nativeImageHandle = 0;
 #endif
 #if !defined(QT_NO_EGL)
     context = 0;
     qt_vg_register_pixmap(this);
 #endif
     updateSerial();
 }
~QVGPixmapData()
QVGPixmapData::~QVGPixmapData ()
Definition at line 81 of file qpixmapdata_vg.cpp.
 {
     destroyImageAndContext();
 #if !defined(QT_NO_EGL)
     qt_vg_unregister_pixmap(this);
 #endif
 }
Functions
buffer()
QImage * QVGPixmapData::buffer () virtual
Reimplemented from QPixmapData.
Definition at line 329 of file qpixmapdata_vg.cpp.
 {
     // Cannot be safely implemented and QVGPixmapData is not (must not be) RasterClass anyway.
     return 0;
 }
copy()
void QVGPixmapData::copy (const QPixmapData * data, const QRect & rect) virtual
Reimplemented from QPixmapData.
Definition at line 305 of file qpixmapdata_vg.cpp.
 {
     // toImage() is potentially expensive with QVolatileImage so provide a
     // more efficient implementation of copy() that does not rely on it.
     if (!data) {
         return;
     }
     if (data->classId() != OpenVGClass) {
         fromImage(data->toImage(rect), Qt::NoOpaqueDetection);
         return;
     }
     const QVGPixmapData *pd = static_cast<const QVGPixmapData *>(data);
     QRect r = rect;
     if (r.isNull() || r.contains(QRect(0, 0, pd->w, pd->h))) {
         r = QRect(0, 0, pd->w, pd->h);
     }
     resize(r.width(), r.height());
     recreate = true;
     if (!pd->source.isNull()) {
         source = QVolatileImage(r.width(), r.height(), pd->source.format());
         source.copyFrom(&pd->source, r);
     }
 }
createCompatiblePixmapData()
QPixmapData * QVGPixmapData::createCompatiblePixmapData () const virtual
Reimplemented from QPixmapData.
Definition at line 146 of file qpixmapdata_vg.cpp.
 {
     return new QVGPixmapData(pixelType());
 }
createPixmapForImage()
void QVGPixmapData::createPixmapForImage (QImage & image, Qt::ImageConversionFlags flags, bool inPlace) protected
Definition at line 237 of file qpixmapdata_vg.cpp.
Referenced by fromData(), fromFile(), fromImage(), and fromImageReader().
 {
     resize(image.width(), image.height());
     QImage::Format format = idealFormat(&image, flags);
     if (inPlace && image.data_ptr()->convertInPlace(format, flags)) {
         source = QVolatileImage(image);
     } else {
         QImage convertedImage = image.convertToFormat(format);
         // convertToFormat won't detach the image if format stays the
         // same. Detaching is needed to prevent issues with painting
         // onto this QPixmap later on.
         convertedImage.detach();
         if (convertedImage.isNull())
             qWarning("QVGPixmapData: Failed to convert image data (out of memory? try increasing heap size)");
         source = QVolatileImage(convertedImage);
     }
     recreate = true;
 }
destroyImageAndContext()
void QVGPixmapData::destroyImageAndContext () protected
Definition at line 112 of file qpixmapdata_vg.cpp.
Referenced by hibernate(), and ~QVGPixmapData().
 {
     if (vgImage != VG_INVALID_HANDLE) {
         // We need to have a context current to destroy the image.
 #if !defined(QT_NO_EGL)
         if (!context)
             context = qt_vg_create_context(0, QInternal::Pixmap);
         if (context->isCurrent()) {
             destroyImages();
         } else {
             // We don't currently have a widget surface active, but we
             // need a surface to make the context current.  So use the
             // shared pbuffer surface instead.
             context->makeCurrent(qt_vg_shared_surface());
             destroyImages();
             context->lazyDoneCurrent();
         }
 #else
         destroyImages();
 #endif
     } else {
 #if defined(Q_OS_SYMBIAN)
         releaseNativeImageHandle();
 #endif
     }
 #if !defined(QT_NO_EGL)
     if (context) {
         qt_vg_destroy_context(context, QInternal::Pixmap);
         context = 0;
     }
 #endif
     recreate = true;
 }
destroyImages()
void QVGPixmapData::destroyImages () protected
Definition at line 89 of file qpixmapdata_vg.cpp.
Referenced by destroyImageAndContext(), ensureReadback(), reclaimImages(), and toVGImage().
 {
     if (inImagePool) {
         QVGImagePool *pool = QVGImagePool::instance();
         if (vgImage != VG_INVALID_HANDLE)
             pool->releaseImage(this, vgImage);
         if (vgImageOpacity != VG_INVALID_HANDLE)
             pool->releaseImage(this, vgImageOpacity);
     } else {
         if (vgImage != VG_INVALID_HANDLE)
             vgDestroyImage(vgImage);
         if (vgImageOpacity != VG_INVALID_HANDLE)
             vgDestroyImage(vgImageOpacity);
     }
     vgImage = VG_INVALID_HANDLE;
     vgImageOpacity = VG_INVALID_HANDLE;
     inImagePool = false;
 #if defined(Q_OS_SYMBIAN)
     releaseNativeImageHandle();
 #endif
 }
detachImageFromPool()
void QVGPixmapData::detachImageFromPool () virtual
Definition at line 439 of file qpixmapdata_vg.cpp.
Referenced by QVGPaintEnginePrivate::setBrush().
 {
     if (inImagePool) {
         QVGImagePool::instance()->detachImage(this);
         inImagePool = false;
     }
 }
ensureReadback()
void QVGPixmapData::ensureReadback (bool readOnly) const virtual
Definition at line 516 of file qpixmapdata_vg.cpp.
Referenced by forceToImage(), hasAlphaChannel(), and toImage().
 {
     if (vgImage != VG_INVALID_HANDLE && source.isNull()) {
         source = QVolatileImage(w, h, sourceFormat());
         source.beginDataAccess();
         vgGetImageSubData(vgImage, source.bits(), source.bytesPerLine(),
                           qt_vg_image_to_vg_format(source.format()),
                           0, 0, w, h);
         source.endDataAccess();
         if (readOnly) {
             recreate = false;
         } else {
             // Once we did a readback, the original VGImage must be destroyed
             // because it may be shared (e.g. created via SgImage) and a subsequent
             // upload of the image data may produce unexpected results.
             const_cast<QVGPixmapData *>(this)->destroyImages();
 #if defined(Q_OS_SYMBIAN)
             // There is now an own copy of the data so drop the handle provider,
             // otherwise toVGImage() would request the handle again, which is wrong.
             nativeImageHandleProvider = 0;
 #endif
             recreate = true;
         }
     }
 }
fill()
void QVGPixmapData::fill (const QColor & color) virtual
Implements QPixmapData.
Definition at line 258 of file qpixmapdata_vg.cpp.
 {
     if (!isValid())
         return;
     forceToImage();
     if (source.depth() == 1) {
         // Pick the best approximate color in the image's colortable.
         int gray = qGray(color.rgba());
         if (qAbs(qGray(source.imageRef().color(0)) - gray)
             < qAbs(qGray(source.imageRef().color(1)) - gray))
             source.fill(0);
         else
             source.fill(1);
     } else {
         source.fill(PREMUL(color.rgba()));
     }
 }
forceToImage()
void QVGPixmapData::forceToImage (bool allowReadback = true) protected
Definition at line 502 of file qpixmapdata_vg.cpp.
Referenced by fill(), hibernate(), paintEngine(), reclaimImages(), and setAlphaChannel().
 {
     if (!isValid())
         return;
     if (allowReadback)
         ensureReadback(false);
     if (source.isNull())
         source = QVolatileImage(w, h, sourceFormat());
     recreate = true;
 }
fromData()
bool QVGPixmapData::fromData (const uchar * buffer, uint len, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 209 of file qpixmapdata_vg.cpp.
 {
     QByteArray a = QByteArray::fromRawData(reinterpret_cast<const char *>(buffer), len);
     QBuffer b(&a);
     b.open(QIODevice::ReadOnly);
     QImage image = QImageReader(&b, format).read();
     if (image.isNull())
         return false;
     createPixmapForImage(image, flags, true);
     return !isNull();
 }
fromFile()
bool QVGPixmapData::fromFile (const QString & filename, const char * format, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 197 of file qpixmapdata_vg.cpp.
 {
     QImage image = QImageReader(filename, format).read();
     if (image.isNull())
         return false;
     createPixmapForImage(image, flags, true);
     return !isNull();
 }
fromImage()
void QVGPixmapData::fromImage (const QImage & image, Qt::ImageConversionFlags flags) virtual
Implements QPixmapData.
Definition at line 178 of file qpixmapdata_vg.cpp.
Referenced by copy().
 {
     if (image.isNull())
         return;
     QImage img = image;
     createPixmapForImage(img, flags, false);
 }
fromImageReader()
void QVGPixmapData::fromImageReader (QImageReader * imageReader, Qt::ImageConversionFlags flags) virtual
Reimplemented from QPixmapData.
Definition at line 187 of file qpixmapdata_vg.cpp.
 {
     QImage image = imageReader->read();
     if (image.isNull())
         return;
     createPixmapForImage(image, flags, true);
 }
hasAlphaChannel()
bool QVGPixmapData::hasAlphaChannel () const virtual
Implements QPixmapData.
Definition at line 276 of file qpixmapdata_vg.cpp.
 {
     ensureReadback(true);
     if (!source.isNull())
         return source.hasAlphaChannel();
     else
         return isValid();
 }
hibernate()
void QVGPixmapData::hibernate () virtual
Definition at line 447 of file qpixmapdata_vg.cpp.
Referenced by QVGImagePool::hibernate(), and qt_vg_hibernate_pixmaps().
 {
     // If the image was imported (e.g, from an SgImage under Symbian), then
     // skip the hibernation, there is no sense in copying it back to main
     // memory because the data is most likely shared between several processes.
     bool skipHibernate = (vgImage != VG_INVALID_HANDLE && source.isNull());
 #if defined(Q_OS_SYMBIAN)
     // However we have to proceed normally if the image was retrieved via
     // a handle provider.
     skipHibernate &= !nativeImageHandleProvider;
 #endif
     if (skipHibernate)
         return;
     forceToImage(false); // no readback allowed here
     destroyImageAndContext();
 }
idealFormat()
QImage::Format QVGPixmapData::idealFormat (QImage * image, Qt::ImageConversionFlags flags) const protected
Definition at line 224 of file qpixmapdata_vg.cpp.
Referenced by createPixmapForImage().
 {
     QImage::Format format = sourceFormat();
     int d = image->depth();
     if (d == 1 || d == 16 || d == 24 || (d == 32 && !image->hasAlphaChannel()))
         format = QImage::Format_RGB32;
     else if (!(flags & Qt::NoOpaqueDetection) && image->data_ptr()->checkForAlphaPixels())
         format = sourceFormat();
     else
         format = image->hasAlphaChannel() ? sourceFormat() : QImage::Format_RGB32;
     return format;
 }
isValid()
bool QVGPixmapData::isValid () const
Definition at line 151 of file qpixmapdata_vg.cpp.
Referenced by QVGCompositionHelper::drawCursorPixmap(), QVGPaintEngine::drawPixmap(), QVGPaintEngine::drawPixmapFragments(), fill(), forceToImage(), hasAlphaChannel(), qPixmapToVGImage(), setAlphaChannel(), toImage(), and toVGImage().
 {
     return (w > 0 && h > 0);
 }
metric()
int QVGPixmapData::metric (QPaintDevice::PaintDeviceMetric metric) const protected virtual
Implements QPixmapData.
Definition at line 473 of file qpixmapdata_vg.cpp.
 {
     switch (metric) {
     case QPaintDevice::PdmWidth:
         return w;
     case QPaintDevice::PdmHeight:
         return h;
     case QPaintDevice::PdmNumColors:
         return 0;
     case QPaintDevice::PdmDepth:
         return d;
     case QPaintDevice::PdmWidthMM:
         return qRound(w * 25.4 / qt_defaultDpiX());
     case QPaintDevice::PdmHeightMM:
         return qRound(h * 25.4 / qt_defaultDpiY());
     case QPaintDevice::PdmDpiX:
     case QPaintDevice::PdmPhysicalDpiX:
         return qt_defaultDpiX();
     case QPaintDevice::PdmDpiY:
     case QPaintDevice::PdmPhysicalDpiY:
         return qt_defaultDpiY();
     default:
         qWarning("QVGPixmapData::metric(): Invalid metric");
         return 0;
     }
 }
paintEngine()
QPaintEngine * QVGPixmapData::paintEngine () const virtual
Implements QPixmapData.
Definition at line 335 of file qpixmapdata_vg.cpp.
 {
     // If the application wants to paint into the QPixmap, we first
     // force it to QImage format and then paint into that.
     // This is simpler than juggling multiple VG contexts.
     const_cast<QVGPixmapData *>(this)->forceToImage();
     return source.paintEngine();
 }
reclaimImages()
void QVGPixmapData::reclaimImages () virtual
Definition at line 465 of file qpixmapdata_vg.cpp.
Referenced by QVGImagePool::reclaimSpace().
 {
     if (!inImagePool)
         return;
     forceToImage();
     destroyImages();
 }
resize()
void QVGPixmapData::resize (int width, int height) virtual
Implements QPixmapData.
Definition at line 161 of file qpixmapdata_vg.cpp.
Referenced by copy(), and createPixmapForImage().
 {
     if (w == wid && h == ht) {
         updateSerial();
         return;
     }
     w = wid;
     h = ht;
     d = 32; // We always use ARGB_Premultiplied for VG pixmaps.
     is_null = (w <= 0 || h <= 0);
     source = QVolatileImage();
     recreate = true;
     updateSerial();
 }
setAlphaChannel()
void QVGPixmapData::setAlphaChannel (const QPixmap & alphaChannel) virtual
Reimplemented from QPixmapData.
Definition at line 285 of file qpixmapdata_vg.cpp.
 {
     if (!isValid())
         return;
     forceToImage();
     source.setAlphaChannel(alphaChannel);
 }
size()
QSize QVGPixmapData::size () const inline
Definition at line 138 of file qpixmapdata_vg_p.h.
Referenced by QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), QVGPixmapBlurFilter::draw(), QVGPaintEngine::drawPixmap(), and QVGPaintEngine::drawPixmapFragments().
 { return QSize(w, h); }
sourceFormat()
QImage::Format QVGPixmapData::sourceFormat () const protected
Definition at line 542 of file qpixmapdata_vg.cpp.
Referenced by ensureReadback(), forceToImage(), idealFormat(), and toImage().
 {
     return QImage::Format_ARGB32_Premultiplied;
 }
toImage()
QImage QVGPixmapData::toImage () const virtual
Implements QPixmapData.
Definition at line 293 of file qpixmapdata_vg.cpp.
 {
     if (!isValid())
         return QImage();
     ensureReadback(true);
     if (source.isNull()) {
         source = QVolatileImage(w, h, sourceFormat());
         recreate = true;
     }
     return source.toImage();
 }
toVGImage() [1/2]
VGImage QVGPixmapData::toVGImage () virtual
Definition at line 344 of file qpixmapdata_vg.cpp.
Referenced by QVGPixmapConvolutionFilter::draw(), QVGPixmapColorizeFilter::draw(), QVGPixmapDropShadowFilter::draw(), QVGPixmapBlurFilter::draw(), QVGCompositionHelper::drawCursorPixmap(), QVGPaintEngine::drawPixmap(), QVGPaintEngine::drawPixmapFragments(), qPixmapToVGImage(), QVGPaintEnginePrivate::setBrush(), and toVGImage().
 {
     if (!isValid())
         return VG_INVALID_HANDLE;
 #if !defined(QT_NO_EGL)
     // Increase the reference count on the shared context.
     if (!context)
         context = qt_vg_create_context(0, QInternal::Pixmap);
 #endif
     if (recreate && prevSize != QSize(w, h))
         destroyImages();
     else if (recreate)
         cachedOpacity = -1.0f;  // Force opacity image to be refreshed later.
 #if defined(Q_OS_SYMBIAN)
     if (recreate && nativeImageHandleProvider && !nativeImageHandle) {
         createFromNativeImageHandleProvider();
     }
 #endif
     if (vgImage == VG_INVALID_HANDLE) {
         vgImage = QVGImagePool::instance()->createImageForPixmap
             (qt_vg_image_to_vg_format(source.format()), w, h, VG_IMAGE_QUALITY_FASTER, this);
         // Bail out if we run out of GPU memory - try again next time.
         if (vgImage == VG_INVALID_HANDLE) {
             return VG_INVALID_HANDLE;
         }
         inImagePool = true;
     } else if (inImagePool) {
         QVGImagePool::instance()->useImage(this);
     }
     if (!source.isNull() && (recreate || source.paintingActive())) {
         source.beginDataAccess();
         vgImageSubData
             (vgImage,
              source.constBits(), source.bytesPerLine(),
              qt_vg_image_to_vg_format(source.format()), 0, 0, w, h);
         source.endDataAccess(true);
     }
     recreate = false;
     prevSize = QSize(w, h);
     return vgImage;
 }
toVGImage() [2/2]
VGImage QVGPixmapData::toVGImage (qreal opacity) virtual
Definition at line 395 of file qpixmapdata_vg.cpp.
 {
 #if !defined(QT_SHIVAVG)
     // Force the primary VG image to be recreated if necessary.
     if (toVGImage() == VG_INVALID_HANDLE)
         return VG_INVALID_HANDLE;
     if (opacity == 1.0f)
         return vgImage;
     // Create an alternative image for the selected opacity.
     if (vgImageOpacity == VG_INVALID_HANDLE || cachedOpacity != opacity) {
         if (vgImageOpacity == VG_INVALID_HANDLE) {
             if (inImagePool) {
                 vgImageOpacity = QVGImagePool::instance()->createImageForPixmap
                     (VG_sARGB_8888_PRE, w, h, VG_IMAGE_QUALITY_FASTER, this);
             } else {
                 vgImageOpacity = vgCreateImage
                     (VG_sARGB_8888_PRE, w, h, VG_IMAGE_QUALITY_FASTER);
             }
             // Bail out if we run out of GPU memory - try again next time.
             if (vgImageOpacity == VG_INVALID_HANDLE)
                 return VG_INVALID_HANDLE;
         }
         VGfloat matrix[20] = {
             1.0f, 0.0f, 0.0f, 0.0f,
             0.0f, 1.0f, 0.0f, 0.0f,
             0.0f, 0.0f, 1.0f, 0.0f,
             0.0f, 0.0f, 0.0f, opacity,
             0.0f, 0.0f, 0.0f, 0.0f
         };
         vgColorMatrix(vgImageOpacity, vgImage, matrix);
         cachedOpacity = opacity;
     }
     return vgImageOpacity;
 #else
     // vgColorMatrix() doesn't work with ShivaVG, so ignore the opacity.
     Q_UNUSED(opacity);
     return toVGImage();
 #endif
 }
updateSerial()
void QVGPixmapData::updateSerial () protected
Definition at line 156 of file qpixmapdata_vg.cpp.
Referenced by QVGPixmapData(), and resize().
 {
     setSerialNumber(++qt_vg_pixmap_serial);
 }
Friends and Related Functions
qt_vg_hibernate_pixmaps
void qt_vg_hibernate_pixmaps (QVGSharedContext * context) friend
Definition at line 333 of file qwindowsurface_vgegl.cpp.
 {
     // Artificially increase the reference count to prevent the
     // context from being destroyed until after we have finished
     // the hibernation process.
     ++(shared->refCount);
     // We need a context current to hibernate the VGImage objects.
     shared->context->makeCurrent(qt_vg_shared_surface());
     // Scan all QVGPixmapData objects in the system and hibernate them.
     QVGPixmapData *pd = shared->firstPixmap;
     while (pd != 0) {
         pd->hibernate();
         pd = pd->next;
     }
     // Hibernate any remaining VGImage's in the image pool.
     QVGImagePool::instance()->hibernate();
     // Don't need the current context any more.
     shared->context->lazyDoneCurrent();
     // Decrease the reference count and destroy the context if necessary.
     if (--(shared->refCount) <= 0)
         qt_vg_destroy_shared_context(shared);
 }
qt_vg_register_pixmap
void qt_vg_register_pixmap (QVGPixmapData * pd) friend
Definition at line 157 of file qwindowsurface_vgegl.cpp.
Referenced by QVGPixmapData().
 {
     QVGSharedContext *shared = sharedContext();
     pd->next = shared->firstPixmap;
     pd->prev = 0;
     if (shared->firstPixmap)
         shared->firstPixmap->prev = pd;
     shared->firstPixmap = pd;
 }
qt_vg_unregister_pixmap
void qt_vg_unregister_pixmap (QVGPixmapData * pd) friend
Definition at line 167 of file qwindowsurface_vgegl.cpp.
Referenced by ~QVGPixmapData().
 {
     if (pd->next)
         pd->next->prev = pd->prev;
     if (pd->prev) {
         pd->prev->next = pd->next;
     } else {
         QVGSharedContext *shared = sharedContext();
         if (shared)
            shared->firstPixmap = pd->next;
     }
 }
QVGImagePool
friend class QVGImagePool friend
Definition at line 161 of file qpixmapdata_vg_p.h.
QVGPaintEngine
friend class QVGPaintEngine friend
Definition at line 162 of file qpixmapdata_vg_p.h.
Properties
cachedOpacity
qreal QVGPixmapData::cachedOpacity protected
Definition at line 177 of file qpixmapdata_vg_p.h.
Referenced by QVGPixmapData(), and toVGImage().
context
QEglContext* QVGPixmapData::context mutable protected
Definition at line 182 of file qpixmapdata_vg_p.h.
Referenced by destroyImageAndContext(), QVGPixmapData(), and toVGImage().
inImagePool
bool QVGPixmapData::inImagePool protected
Definition at line 180 of file qpixmapdata_vg_p.h.
Referenced by destroyImages(), detachImageFromPool(), QVGImagePool::hibernate(), QVGPixmapData(), reclaimImages(), and toVGImage().
inLRU
bool QVGPixmapData::inLRU private
Definition at line 160 of file qpixmapdata_vg_p.h.
Referenced by QVGImagePool::hibernate(), QVGImagePool::moveToHeadOfLRU(), QVGPixmapData(), QVGImagePool::reclaimSpace(), and QVGImagePool::removeFromLRU().
next
QVGPixmapData* QVGPixmapData::next private
Definition at line 165 of file qpixmapdata_vg_p.h.
Referenced by qt_vg_hibernate_pixmaps(), qt_vg_register_pixmap(), and qt_vg_unregister_pixmap().
nextLRU
QVGPixmapData* QVGPixmapData::nextLRU private
Definition at line 158 of file qpixmapdata_vg_p.h.
Referenced by QVGImagePool::hibernate(), QVGImagePool::moveToHeadOfLRU(), and QVGImagePool::removeFromLRU().
prev
QVGPixmapData* QVGPixmapData::prev private
Definition at line 166 of file qpixmapdata_vg_p.h.
Referenced by qt_vg_register_pixmap(), and qt_vg_unregister_pixmap().
prevLRU
QVGPixmapData* QVGPixmapData::prevLRU private
Definition at line 159 of file qpixmapdata_vg_p.h.
Referenced by QVGImagePool::hibernate(), QVGImagePool::moveToHeadOfLRU(), and QVGImagePool::removeFromLRU().
prevSize
QSize QVGPixmapData::prevSize protected
Definition at line 174 of file qpixmapdata_vg_p.h.
Referenced by toVGImage().
recreate
bool QVGPixmapData::recreate mutable protected
Definition at line 179 of file qpixmapdata_vg_p.h.
Referenced by copy(), createPixmapForImage(), destroyImageAndContext(), ensureReadback(), forceToImage(), QVGPixmapData(), resize(), toImage(), and toVGImage().
source
QVolatileImage QVGPixmapData::source mutable protected
Definition at line 178 of file qpixmapdata_vg_p.h.
Referenced by copy(), createPixmapForImage(), QVGPaintEngine::drawPixmap(), ensureReadback(), fill(), forceToImage(), hasAlphaChannel(), hibernate(), paintEngine(), resize(), setAlphaChannel(), toImage(), and toVGImage().
vgImage
VGImage QVGPixmapData::vgImage protected
Definition at line 175 of file qpixmapdata_vg_p.h.
Referenced by destroyImageAndContext(), destroyImages(), QVGPaintEngine::drawPixmap(), ensureReadback(), hibernate(), QVGPixmapData(), and toVGImage().
vgImageOpacity
VGImage QVGPixmapData::vgImageOpacity protected
Definition at line 176 of file qpixmapdata_vg_p.h.
Referenced by destroyImages(), QVGPixmapData(), and toVGImage().
The documentation for this class was generated from the following files:
/src/openvg/qpixmapdata_vg_p.h
/src/openvg/qpixmapdata_vg.cpp