Qt 4.8: QColumnView Class Reference
QColumnView Class Reference
The QColumnView class provides a model/view implementation of a column view.
#include <qcolumnview.h>
Signals
void updatePreviewWidget (const QModelIndex &index)
This signal is emitted when the preview widget should be updated to provide rich information about index.
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QList< int > columnWidths () const
Returns a list of the width of all the columns in this view.
QModelIndex indexAt (const QPoint &point) const
Reimplemented Function
QWidget * previewWidget () const
Returns the preview widget, or 0 if there is none.
QColumnView (QWidget *parent=0)
Constructs a column view with a parent to represent a model's data.
bool resizeGripsVisible () const
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Reimplemented Function
void selectAll ()
Reimplemented Function
void setColumnWidths (const QList< int > &list)
Sets the column widths to the values given in the list.
void setModel (QAbstractItemModel *model)
Reimplemented Function
void setPreviewWidget (QWidget *widget)
Sets the preview widget.
void setResizeGripsVisible (bool visible)
void setRootIndex (const QModelIndex &index)
Reimplemented Function
void setSelectionModel (QItemSelectionModel *selectionModel)
Reimplemented Function
QSize sizeHint () const
Reimplemented Function
QRect visualRect (const QModelIndex &index) const
Reimplemented Function
~QColumnView ()
Destroys the column view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
virtual int sizeHintForColumn (int column) const
Returns the width size hint for the specified column or -1 if there is no model.
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
virtual QAbstractItemView * createColumn (const QModelIndex &rootIndex)
To use a custom widget for the final column when you select an item overload this function and return a widget.
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
int horizontalOffset () const
Reimplemented Function
void initializeColumn (QAbstractItemView *column) const
Copies the behavior and options of the column view and applies them to the column such as the iconSize(), textElideMode() and alternatingRowColors().
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Reimplemented Function Move left should go to the parent index Move right should go to the child index or down if there is no child
QColumnView (QColumnViewPrivate &dd, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void rowsInserted (const QModelIndex &parent, int start, int end)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
Reimplemented Function
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Reimplemented Function
int verticalOffset () const
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Reimplemented Function
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
void dragMoveEvent (QDragMoveEvent *event)
This function is called continuously with the given event during a drag and drop operation over the widget.
void dropEvent (QDropEvent *event)
This function is called with the given event when a drop event occurs over the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
bool event (QEvent *event)
Reimplemented Function
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
void mouseDoubleClickEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is double clicked inside the widget.
void mouseMoveEvent (QMouseEvent *event)
This function is called with the given event when a mouse move event is sent to the widget.
void mousePressEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
void mouseReleaseEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is released, after a mouse press event on the widget.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QModelIndexList selectedIndexes () const
This convenience function returns a list of all selected and non-hidden item indexes in the view.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
void timerEvent (QTimerEvent *event)
This function is called with the given event when a timer event is sent to the widget.
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
virtual QStyleOptionViewItem viewOptions () const
Returns a QStyleOptionViewItem structure populated with the view's palette, font, state, alignments etc.
bool viewportEvent (QEvent *event)
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool resizeGripsVisible
the way to specify if the list views gets resize grips or not
Additional Inherited Members
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
virtual void doItemsLayout ()
This function is intended to lay out the items in the view.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
virtual void reset ()
Reset the internal state of the view.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This slot is called when items are changed in the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarAction (int action)
virtual void horizontalScrollbarValueChanged (int value)
virtual void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
This slot is called when rows are about to be removed.
virtual void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
This slot is called when the selection is changed.
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void updateGeometries ()
Updates the geometry of the child widgets of the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QColumnView class provides a model/view implementation of a column view.
Since
4.3
QColumnView displays a model in a number of QListViews, one for each hierarchy in the tree. This is sometimes referred to as a cascading list.
The QColumnView class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
QColumnView implements the interfaces defined by the QAbstractItemView class to allow it to display data provided by models derived from the QAbstractItemModel class.
See also
Model/View Programming
Definition at line 57 of file qcolumnview.h.
Constructors and Destructors
QColumnView() [1/2]
QColumnView::QColumnView (QWidget * parent = 0) explicit
Constructs a column view with a parent to represent a model's data.
Use setModel() to set the model.
See also
QAbstractItemModel
Definition at line 92 of file qcolumnview.cpp.
 :  QAbstractItemView(*new QColumnViewPrivate, parent)
 {
     Q_D(QColumnView);
     d->initialize();
 }
~QColumnView()
QColumnView::~QColumnView ()
Destroys the column view.
Definition at line 127 of file qcolumnview.cpp.
 {
 }
QColumnView() [2/2]
QColumnView::QColumnView (QColumnViewPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 102 of file qcolumnview.cpp.
 :  QAbstractItemView(dd, parent)
 {
     Q_D(QColumnView);
     d->initialize();
 }
Functions
columnWidths()
QList< int > QColumnView::columnWidths () const
Returns a list of the width of all the columns in this view.
See also
setColumnWidths()
Definition at line 896 of file qcolumnview.cpp.
 {
     Q_D(const QColumnView);
     QList<int> list;
     for (int i = 0; i < d->columns.count(); ++i)
         list.append(d->columnSizes.at(i));
     return list;
 }
createColumn()
QAbstractItemView * QColumnView::createColumn (const QModelIndex & index) protected virtual
To use a custom widget for the final column when you select an item overload this function and return a widget.
index is the root index that will be assigned to the view.
Return the new view. QColumnView will automatically take ownership of the widget.
See also
setPreviewWidget()
Definition at line 758 of file qcolumnview.cpp.
Referenced by QColumnViewPrivate::closeColumns().
 {
     QListView *view = new QListView(viewport());
     initializeColumn(view);
     view->setRootIndex(index);
     if (model()->canFetchMore(index))
         model()->fetchMore(index);
     return view;
 }
currentChanged()
void QColumnView::currentChanged (const QModelIndex & current, const QModelIndex & previous) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 917 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     if (!current.isValid()) {
         QAbstractItemView::currentChanged(current, previous);
         return;
     }
     QModelIndex currentParent = current.parent();
     // optimize for just moving up/down in a list where the child view doesn't change
     if (currentParent == previous.parent()
             && model()->hasChildren(current) && model()->hasChildren(previous)) {
         for (int i = 0; i < d->columns.size(); ++i) {
             if (currentParent == d->columns.at(i)->rootIndex()) {
                 if (d->columns.size() > i + 1) {
                     QAbstractItemView::currentChanged(current, previous);
                     return;
                 }
                 break;
             }
         }
     }
     // Scrolling to the right we need to have an empty spot
     bool found = false;
     if (currentParent == previous) {
         for (int i = 0; i < d->columns.size(); ++i) {
             if (currentParent == d->columns.at(i)->rootIndex()) {
                 found = true;
                 if (d->columns.size() < i + 2) {
                     d->createColumn(current, false);
                 }
                 break;
             }
         }
     }
     if (!found)
         d->closeColumns(current, true);
     if (!model()->hasChildren(current))
         emit updatePreviewWidget(current);
     QAbstractItemView::currentChanged(current, previous);
 }
horizontalOffset()
int QColumnView::horizontalOffset () const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 449 of file qcolumnview.cpp.
Referenced by scrollTo().
 {
     Q_D(const QColumnView);
     return d->offset;
 }
indexAt()
QModelIndex QColumnView::indexAt (const QPoint & point) const virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 214 of file qcolumnview.cpp.
 {
     Q_D(const QColumnView);
     for (int i = 0; i < d->columns.size(); ++i) {
         QPoint topLeft = d->columns.at(i)->frameGeometry().topLeft();
         QPoint adjustedPoint(point.x() - topLeft.x(), point.y() - topLeft.y());
         QModelIndex index = d->columns.at(i)->indexAt(adjustedPoint);
         if (index.isValid())
             return index;
     }
     return QModelIndex();
 }
initializeColumn()
void QColumnView::initializeColumn (QAbstractItemView * column) const protected
Copies the behavior and options of the column view and applies them to the column such as the iconSize(), textElideMode() and alternatingRowColors().
This can be useful when reimplementing createColumn().
Since
4.4
See also
createColumn()
Definition at line 780 of file qcolumnview.cpp.
Referenced by createColumn().
 {
     Q_D(const QColumnView);
     column->setFrameShape(QFrame::NoFrame);
     column->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     column->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
     column->setMinimumWidth(100);
     column->setAttribute(Qt::WA_MacShowFocusRect, false);
 #ifndef QT_NO_DRAGANDDROP
     column->setDragDropMode(dragDropMode());
     column->setDragDropOverwriteMode(dragDropOverwriteMode());
     column->setDropIndicatorShown(showDropIndicator());
 #endif
     column->setAlternatingRowColors(alternatingRowColors());
     column->setAutoScroll(hasAutoScroll());
     column->setEditTriggers(editTriggers());
     column->setHorizontalScrollMode(horizontalScrollMode());
     column->setIconSize(iconSize());
     column->setSelectionBehavior(selectionBehavior());
     column->setSelectionMode(selectionMode());
     column->setTabKeyNavigation(tabKeyNavigation());
     column->setTextElideMode(textElideMode());
     column->setVerticalScrollMode(verticalScrollMode());
     column->setModel(model());
     // Copy the custom delegate per row
     QMapIterator<int, QPointer<QAbstractItemDelegate> > i(d->rowDelegates);
     while (i.hasNext()) {
         i.next();
         column->setItemDelegateForRow(i.key(), i.value());
     }
     // set the delegate to be the columnview delegate
     QAbstractItemDelegate *delegate = column->itemDelegate();
     column->setItemDelegate(d->itemDelegate);
     delete delegate;
 }
isIndexHidden()
bool QColumnView::isIndexHidden (const QModelIndex & index) const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 205 of file qcolumnview.cpp.
 {
     Q_UNUSED(index);
     return false;
 }
moveCursor()
QModelIndex QColumnView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) protected virtual
Reimplemented Function Move left should go to the parent index Move right should go to the child index or down if there is no child
Implements QAbstractItemView.
Definition at line 353 of file qcolumnview.cpp.
 {
     // the child views which have focus get to deal with this first and if
     // they don't accept it then it comes up this view and we only grip left/right
     Q_UNUSED(modifiers);
     if (!model())
         return QModelIndex();
     QModelIndex current = currentIndex();
     if (isRightToLeft()) {
         if (cursorAction == MoveLeft)
             cursorAction = MoveRight;
         else if (cursorAction == MoveRight)
             cursorAction = MoveLeft;
     }
     switch (cursorAction) {
     case MoveLeft:
         if (current.parent().isValid() && current.parent() != rootIndex())
             return (current.parent());
         else
             return current;
         break;
     case MoveRight:
         if (model()->hasChildren(current))
             return model()->index(0, 0, current);
         else
             return current.sibling(current.row() + 1, current.column());
         break;
     default:
         break;
     }
     return QModelIndex();
 }
previewWidget()
QWidget * QColumnView::previewWidget () const
Returns the preview widget, or 0 if there is none.
See also
setPreviewWidget(), updatePreviewWidget()
Definition at line 826 of file qcolumnview.cpp.
Referenced by QColumnViewPrivate::createColumn(), and QColumnViewPrivate::setPreviewWidget().
 {
     Q_D(const QColumnView);
     return d->previewWidget;
 }
resizeEvent()
void QColumnView::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 393 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     d->doLayout();
     d->updateScrollbars();
     if (!isRightToLeft()) {
         int diff = event->oldSize().width() - event->size().width();
         if (diff < 0 && horizontalScrollBar()->isVisible()
             && horizontalScrollBar()->value() == horizontalScrollBar()->maximum()) {
             horizontalScrollBar()->setMaximum(horizontalScrollBar()->maximum() + diff);
         }
     }
     QAbstractItemView::resizeEvent(event);
 }
resizeGripsVisible()
bool QColumnView::resizeGripsVisible () const
Referenced by setResizeGripsVisible().
rowsInserted()
void QColumnView::rowsInserted (const QModelIndex & parent, int start, int end) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 908 of file qcolumnview.cpp.
 {
     QAbstractItemView::rowsInserted(parent, start, end);
     d_func()->checkColumnCreation(parent);
 }
scrollContentsBy()
void QColumnView::scrollContentsBy (int dx, int dy) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 249 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     if (d->columns.isEmpty() || dx == 0)
         return;
     dx = isRightToLeft() ? -dx : dx;
     for (int i = 0; i < d->columns.count(); ++i)
         d->columns.at(i)->move(d->columns.at(i)->x() + dx, 0);
     d->offset += dx;
     QAbstractItemView::scrollContentsBy(dx, dy);
 }
scrollTo()
void QColumnView::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 265 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     Q_UNUSED(hint);
     if (!index.isValid() || d->columns.isEmpty())
         return;
 #ifndef QT_NO_ANIMATION
     if (d->currentAnimation.state() == QPropertyAnimation::Running)
         return;
     d->currentAnimation.stop();
 #endif //QT_NO_ANIMATION
     // Fill up what is needed to get to index
     d->closeColumns(index, true);
     QModelIndex indexParent = index.parent();
     // Find the left edge of the column that contains index
     int currentColumn = 0;
     int leftEdge = 0;
     while (currentColumn < d->columns.size()) {
         if (indexParent == d->columns.at(currentColumn)->rootIndex())
             break;
         leftEdge += d->columns.at(currentColumn)->width();
         ++currentColumn;
     }
     // Don't let us scroll above the root index
     if (currentColumn == d->columns.size())
         return;
     int indexColumn = currentColumn;
     // Find the width of what we want to show (i.e. the right edge)
     int visibleWidth = d->columns.at(currentColumn)->width();
     // We want to always try to show two columns
     if (currentColumn + 1 < d->columns.size()) {
         ++currentColumn;
         visibleWidth += d->columns.at(currentColumn)->width();
     }
     int rightEdge = leftEdge + visibleWidth;
     if (isRightToLeft()) {
         leftEdge = viewport()->width() - leftEdge;
         rightEdge = leftEdge - visibleWidth;
         qSwap(rightEdge, leftEdge);
     }
     // If it is already visible don't animate
     if (leftEdge > -horizontalOffset()
         && rightEdge <= ( -horizontalOffset() + viewport()->size().width())) {
             d->columns.at(indexColumn)->scrollTo(index);
             d->_q_changeCurrentColumn();
             return;
     }
     int newScrollbarValue = 0;
     if (isRightToLeft()) {
         if (leftEdge < 0) {
             // scroll to the right
             newScrollbarValue = viewport()->size().width() - leftEdge;
         } else {
             // scroll to the left
             newScrollbarValue = rightEdge + horizontalOffset();
         }
     } else {
         if (leftEdge > -horizontalOffset()) {
             // scroll to the right
             newScrollbarValue = rightEdge - viewport()->size().width();
         } else {
             // scroll to the left
             newScrollbarValue = leftEdge;
         }
     }
 #ifndef QT_NO_ANIMATION
     d->currentAnimation.setEndValue(newScrollbarValue);
     d->currentAnimation.start();
 #else
     horizontalScrollBar()->setValue(newScrollbarValue);
 #endif //QT_NO_ANIMATION
 }
selectAll()
void QColumnView::selectAll () virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1024 of file qcolumnview.cpp.
 {
     if (!model() || !selectionModel())
         return;
     QModelIndexList indexList = selectionModel()->selectedIndexes();
     QModelIndex parent = rootIndex();
     QItemSelection selection;
     if (indexList.count() >= 1)
         parent = indexList.at(0).parent();
     if (indexList.count() == 1) {
         parent = indexList.at(0);
         if (!model()->hasChildren(parent))
             parent = parent.parent();
         else
             selection.append(QItemSelectionRange(parent, parent));
     }
     QModelIndex tl = model()->index(0, 0, parent);
     QModelIndex br = model()->index(model()->rowCount(parent) - 1,
                                     model()->columnCount(parent) - 1,
                                     parent);
     selection.append(QItemSelectionRange(tl, br));
     selectionModel()->select(selection, QItemSelectionModel::ClearAndSelect);
 }
setColumnWidths()
void QColumnView::setColumnWidths (const QList< int > & list)
Sets the column widths to the values given in the list.
Extra values in the list are kept and used when the columns are created.
If list contains too few values, only width of the rest of the columns will not be modified.
See also
columnWidths(), createColumn()
Definition at line 879 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     int i = 0;
     for (; (i < list.count() && i < d->columns.count()); ++i) {
         d->columns.at(i)->resize(list.at(i), d->columns.at(i)->height());
         d->columnSizes[i] = list.at(i);
     }
     for (; i < list.count(); ++i)
         d->columnSizes.append(list.at(i));
 }
setModel()
void QColumnView::setModel (QAbstractItemModel * model) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 171 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     if (model == d->model)
         return;
     d->closeColumns();
     QAbstractItemView::setModel(model);
 }
setPreviewWidget()
void QColumnView::setPreviewWidget (QWidget * widget)
Sets the preview widget.
The widget becomes a child of the column view, and will be destroyed when the column area is deleted or when a new widget is set.
See also
previewWidget(), updatePreviewWidget()
Definition at line 841 of file qcolumnview.cpp.
Referenced by QColumnViewPrivate::createColumn().
 {
     Q_D(QColumnView);
     d->setPreviewWidget(widget);
 }
setResizeGripsVisible()
void QColumnView::setResizeGripsVisible (bool visible)
Definition at line 142 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     if (d->showResizeGrips == visible)
         return;
     d->showResizeGrips = visible;
     for (int i = 0; i < d->columns.count(); ++i) {
         QAbstractItemView *view = d->columns[i];
         if (visible) {
             QColumnViewGrip *grip = new QColumnViewGrip(view);
             view->setCornerWidget(grip);
             connect(grip, SIGNAL(gripMoved(int)), this, SLOT(_q_gripMoved(int)));
         } else {
             QWidget *widget = view->cornerWidget();
             view->setCornerWidget(0);
             widget->deleteLater();
         }
     }
 }
setRootIndex()
void QColumnView::setRootIndex (const QModelIndex & index) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 183 of file qcolumnview.cpp.
 {
     Q_D(QColumnView);
     if (!model())
         return;
     d->closeColumns();
     Q_ASSERT(d->columns.count() == 0);
     QAbstractItemView *view = d->createColumn(index, true);
     if (view->selectionModel())
         view->selectionModel()->deleteLater();
     if (view->model())
         view->setSelectionModel(selectionModel());
     QAbstractItemView::setRootIndex(index);
     d->updateScrollbars();
 }
setSelection()
void QColumnView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags command) protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 496 of file qcolumnview.cpp.
 {
     Q_UNUSED(rect);
     Q_UNUSED(command);
 }
setSelectionModel()
void QColumnView::setSelectionModel (QItemSelectionModel * selectionModel) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 505 of file qcolumnview.cpp.
 {
     Q_D(const QColumnView);
     for (int i = 0; i < d->columns.size(); ++i) {
         if (d->columns.at(i)->selectionModel() == selectionModel()) {
             d->columns.at(i)->setSelectionModel(newSelectionModel);
             break;
         }
     }
     QAbstractItemView::setSelectionModel(newSelectionModel);
 }
sizeHint()
QSize QColumnView::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 520 of file qcolumnview.cpp.
 {
     Q_D(const QColumnView);
     QSize sizeHint;
     for (int i = 0; i < d->columns.size(); ++i) {
         sizeHint += d->columns.at(i)->sizeHint();
     }
     return sizeHint.expandedTo(QAbstractItemView::sizeHint());
 }
updatePreviewWidget
void QColumnView::updatePreviewWidget (const QModelIndex & index) signal
This signal is emitted when the preview widget should be updated to provide rich information about index.
See also
previewWidget()
Referenced by currentChanged().
verticalOffset()
int QColumnView::verticalOffset () const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 458 of file qcolumnview.cpp.
 {
     return 0;
 }
visualRect()
QRect QColumnView::visualRect (const QModelIndex & index) const virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 230 of file qcolumnview.cpp.
Referenced by visualRegionForSelection().
 {
     if (!index.isValid())
         return QRect();
     Q_D(const QColumnView);
     for (int i = 0; i < d->columns.size(); ++i) {
         QRect rect = d->columns.at(i)->visualRect(index);
         if (!rect.isNull()) {
             rect.translate(d->columns.at(i)->frameGeometry().topLeft());
             return rect;
         }
     }
     return QRect();
 }
visualRegionForSelection()
QRegion QColumnView::visualRegionForSelection (const QItemSelection & selection) const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 466 of file qcolumnview.cpp.
 {
     int ranges = selection.count();
     if (ranges == 0)
         return QRect();
     // Note that we use the top and bottom functions of the selection range
     // since the data is stored in rows.
     int firstRow = selection.at(0).top();
     int lastRow = selection.at(0).top();
     for (int i = 0; i < ranges; ++i) {
         firstRow = qMin(firstRow, selection.at(i).top());
         lastRow = qMax(lastRow, selection.at(i).bottom());
     }
     QModelIndex firstIdx = model()->index(qMin(firstRow, lastRow), 0, rootIndex());
     QModelIndex lastIdx = model()->index(qMax(firstRow, lastRow), 0, rootIndex());
     if (firstIdx == lastIdx)
         return visualRect(firstIdx);
     QRegion firstRegion = visualRect(firstIdx);
     QRegion lastRegion = visualRect(lastIdx);
     return firstRegion.unite(lastRegion);
 }
Properties
resizeGripsVisible
bool QColumnView::resizeGripsVisible private
the way to specify if the list views gets resize grips or not
By default, visible is set to true
See also
setRootIndex()
Definition at line 60 of file qcolumnview.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qcolumnview.h
/src/gui/itemviews/qcolumnview.cpp