Qt 4.8: QNetworkDiskCache Class Reference
QNetworkDiskCache Class Reference
The QNetworkDiskCache class provides a very basic disk cache.
#include <qnetworkdiskcache.h>
Public Slots
void clear ()
Reimplemented Function
Public Slots inherited from QAbstractNetworkCache
virtual void clear ()=0
Removes all items from the cache.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QString cacheDirectory () const
Returns the location where cached files will be stored.
qint64 cacheSize () const
Reimplemented Function
QIODevice * data (const QUrl &url)
Reimplemented Function
QNetworkCacheMetaData fileMetaData (const QString &fileName) const
Returns the QNetworkCacheMetaData for the cache file fileName.
void insert (QIODevice *device)
Reimplemented Function
qint64 maximumCacheSize () const
Returns the current maximum size in bytes for the disk cache.
QNetworkCacheMetaData metaData (const QUrl &url)
Reimplemented Function
QIODevice * prepare (const QNetworkCacheMetaData &metaData)
Reimplemented Function
QNetworkDiskCache (QObject *parent=0)
Creates a new disk cache.
bool remove (const QUrl &url)
Reimplemented Function
void setCacheDirectory (const QString &cacheDir)
Sets the directory where cached files will be stored to cacheDir.
void setMaximumCacheSize (qint64 size)
Sets the maximum size of the disk cache to be size in bytes.
void updateMetaData (const QNetworkCacheMetaData &metaData)
Reimplemented Function
~QNetworkDiskCache ()
Destroys the cache object.
Public Functions inherited from QAbstractNetworkCache
virtual ~QAbstractNetworkCache ()
Destroys the cache.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual qint64 expire ()
Cleans the cache so that its size is under the maximum cache size.
Protected Functions inherited from QAbstractNetworkCache
QAbstractNetworkCache (QObject *parent=0)
Constructs an abstract network cache with the given parent.
QAbstractNetworkCache (QAbstractNetworkCachePrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QNetworkDiskCache class provides a very basic disk cache.
Since
4.5
Attention
Module: QtNetwork
QNetworkDiskCache stores each url in its own file inside of the cacheDirectory using QDataStream. Files with a text MimeType are compressed using qCompress. Each cache file starts with "cache_" and ends in ".cache". Data is written to disk only in insert() and updateMetaData().
Currently you can not share the same cache files with more then one disk cache.
QNetworkDiskCache by default limits the amount of space that the cache will use on the system to 50MB.
Note you have to set the cache directory before it will work.
A network disk cache can be enabled by:
QNetworkAccessManager *manager = new QNetworkAccessManager(this);
QNetworkDiskCache *diskCache = new QNetworkDiskCache(this);
diskCache->setCacheDirectory("cacheDir");
manager->setCache(diskCache);
When sending requests, to control the preference of when to use the cache and when to use the network, consider the following:
// do a normal request (preferred from network, as this is the default)
QNetworkRequest request(QUrl(QString("http://qt.nokia.com")));
manager->get(request);
// do a request preferred from cache
QNetworkRequest request2(QUrl(QString("http://qt.nokia.com")));
request2.setAttribute(QNetworkRequest::CacheLoadControlAttribute, QNetworkRequest::PreferCache);
manager->get(request2);
To check whether the response came from the cache or from the network, the following can be applied:
void replyFinished(QNetworkReply *reply) {
    QVariant fromCache = reply->attribute(QNetworkRequest::SourceIsFromCacheAttribute);
    qDebug() << "page from cache?" << fromCache.toBool();
}
Definition at line 56 of file qnetworkdiskcache.h.
Constructors and Destructors
QNetworkDiskCache()
QNetworkDiskCache::QNetworkDiskCache (QObject * parent = 0) explicit
Creates a new disk cache.
The parent argument is passed to QAbstractNetworkCache's constructor.
Definition at line 111 of file qnetworkdiskcache.cpp.
     : QAbstractNetworkCache(*new QNetworkDiskCachePrivate, parent)
 {
 }
~QNetworkDiskCache()
QNetworkDiskCache::~QNetworkDiskCache ()
Destroys the cache object.
This does not clear the disk cache.
Definition at line 119 of file qnetworkdiskcache.cpp.
 {
     Q_D(QNetworkDiskCache);
     QHashIterator<QIODevice*, QCacheItem*> it(d->inserting);
     while (it.hasNext()) {
         it.next();
         delete it.value();
     }
 }
Functions
cacheDirectory()
QString QNetworkDiskCache::cacheDirectory () const
Returns the location where cached files will be stored.
Definition at line 132 of file qnetworkdiskcache.cpp.
Referenced by expire(), QNetworkDiskCachePrivate::prepareLayout(), and QNetworkDiskCachePrivate::tmpCacheFileName().
 {
     Q_D(const QNetworkDiskCache);
     return d->cacheDirectory;
 }
cacheSize()
qint64 QNetworkDiskCache::cacheSize () const virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 169 of file qnetworkdiskcache.cpp.
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::cacheSize()";
 #endif
     Q_D(const QNetworkDiskCache);
     if (d->cacheDirectory.isEmpty())
         return 0;
     if (d->currentCacheSize < 0) {
         QNetworkDiskCache *that = const_cast<QNetworkDiskCache*>(this);
         that->d_func()->currentCacheSize = that->expire();
     }
     return d->currentCacheSize;
 }
clear
void QNetworkDiskCache::clear () slot
Reimplemented Function
Definition at line 584 of file qnetworkdiskcache.cpp.
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::clear()";
 #endif
     Q_D(QNetworkDiskCache);
     qint64 size = d->maximumCacheSize;
     d->maximumCacheSize = 0;
     d->currentCacheSize = expire();
     d->maximumCacheSize = size;
 }
data()
QIODevice * QNetworkDiskCache::data (const QUrl & url) virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 404 of file qnetworkdiskcache.cpp.
Referenced by QCacheItem::read(), updateMetaData(), and QCacheItem::writeCompressedData().
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::data()" << url;
 #endif
     Q_D(QNetworkDiskCache);
     QScopedPointer<QBuffer> buffer;
     if (!url.isValid())
         return 0;
     if (d->lastItem.metaData.url() == url && d->lastItem.data.isOpen()) {
         buffer.reset(new QBuffer);
         buffer->setData(d->lastItem.data.data());
     } else {
         QScopedPointer<QFile> file(new QFile(d->cacheFileName(url)));
         if (!file->open(QFile::ReadOnly | QIODevice::Unbuffered))
             return 0;
         if (!d->lastItem.read(file.data(), true)) {
             file->close();
             remove(url);
             return 0;
         }
         if (d->lastItem.data.isOpen()) {
             // compressed
             buffer.reset(new QBuffer);
             buffer->setData(d->lastItem.data.data());
         } else {
             buffer.reset(new QBuffer);
             // ### verify that QFile uses the fd size and not the file name
             qint64 size = file->size() - file->pos();
             const uchar *p = 0;
 #if !defined(Q_OS_WINCE) && !defined(Q_OS_INTEGRITY) && !defined(Q_OS_SYMBIAN)
             p = file->map(file->pos(), size);
 #endif
             if (p) {
                 buffer->setData((const char *)p, size);
                 file.take()->setParent(buffer.data());
             } else {
                 buffer->setData(file->readAll());
             }
         }
     }
     buffer->open(QBuffer::ReadOnly);
     return buffer.take();
 }
expire()
qint64 QNetworkDiskCache::expire () protected virtual
Cleans the cache so that its size is under the maximum cache size.
Returns the current size of the cache.
When the current size of the cache is greater than the maximumCacheSize() older cache files are removed until the total size is less then 90% of maximumCacheSize() starting with the oldest ones first using the file creation date to determine how old a cache file is.
Subclasses can reimplement this function to change the order that cache files are removed taking into account information in the application knows about that QNetworkDiskCache does not, for example the number of times a cache is accessed.
Note: cacheSize() calls expire if the current cache size is unknown.
See also
maximumCacheSize(), fileMetaData()
Definition at line 528 of file qnetworkdiskcache.cpp.
Referenced by cacheSize(), clear(), and setMaximumCacheSize().
 {
     Q_D(QNetworkDiskCache);
     if (d->currentCacheSize >= 0 && d->currentCacheSize < maximumCacheSize())
         return d->currentCacheSize;
     if (cacheDirectory().isEmpty()) {
         qWarning() << "QNetworkDiskCache::expire() The cache directory is not set";
         return 0;
     }
     // close file handle to prevent "in use" error when QFile::remove() is called
     d->lastItem.reset();
     QDir::Filters filters = QDir::AllDirs | QDir:: Files | QDir::NoDotAndDotDot;
     QDirIterator it(cacheDirectory(), filters, QDirIterator::Subdirectories);
     QMultiMap<QDateTime, QString> cacheItems;
     qint64 totalSize = 0;
     while (it.hasNext()) {
         QString path = it.next();
         QFileInfo info = it.fileInfo();
         QString fileName = info.fileName();
         if (fileName.endsWith(CACHE_POSTFIX)) {
             cacheItems.insert(info.created(), path);
             totalSize += info.size();
         }
     }
     int removedFiles = 0;
     qint64 goal = (maximumCacheSize() * 9) / 10;
     QMultiMap<QDateTime, QString>::const_iterator i = cacheItems.constBegin();
     while (i != cacheItems.constEnd()) {
         if (totalSize < goal)
             break;
         QString name = i.value();
         QFile file(name);
         qint64 size = file.size();
         file.remove();
         totalSize -= size;
         ++removedFiles;
         ++i;
     }
 #if defined(QNETWORKDISKCACHE_DEBUG)
     if (removedFiles > 0) {
         qDebug() << "QNetworkDiskCache::expire()"
                 << "Removed:" << removedFiles
                 << "Kept:" << cacheItems.count() - removedFiles;
     }
 #endif
     return totalSize;
 }
fileMetaData()
QNetworkCacheMetaData QNetworkDiskCache::fileMetaData (const QString & fileName) const
Returns the QNetworkCacheMetaData for the cache file fileName.
If fileName is not a cache file QNetworkCacheMetaData will be invalid.
Definition at line 384 of file qnetworkdiskcache.cpp.
Referenced by metaData().
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::fileMetaData()" << fileName;
 #endif
     Q_D(const QNetworkDiskCache);
     QFile file(fileName);
     if (!file.open(QFile::ReadOnly))
         return QNetworkCacheMetaData();
     if (!d->lastItem.read(&file, false)) {
         file.close();
         QNetworkDiskCachePrivate *that = const_cast<QNetworkDiskCachePrivate*>(d);
         that->removeFile(fileName);
     }
     return d->lastItem.metaData;
 }
insert()
void QNetworkDiskCache::insert (QIODevice * device) virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 238 of file qnetworkdiskcache.cpp.
Referenced by updateMetaData().
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::insert()" << device;
 #endif
     Q_D(QNetworkDiskCache);
     QHash<QIODevice*, QCacheItem*>::iterator it = d->inserting.find(device);
     if (it == d->inserting.end()) {
         qWarning() << "QNetworkDiskCache::insert() called on a device we don't know about" << device;
         return;
     }
     d->storeItem(it.value());
     delete it.value();
     d->inserting.erase(it);
 }
maximumCacheSize()
qint64 QNetworkDiskCache::maximumCacheSize () const
Returns the current maximum size in bytes for the disk cache.
See also
setMaximumCacheSize()
Definition at line 488 of file qnetworkdiskcache.cpp.
Referenced by expire(), and prepare().
 {
     Q_D(const QNetworkDiskCache);
     return d->maximumCacheSize;
 }
metaData()
QNetworkCacheMetaData QNetworkDiskCache::metaData (const QUrl & url) virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 368 of file qnetworkdiskcache.cpp.
Referenced by QCacheItem::canCompress(), prepare(), QCacheItem::read(), and QCacheItem::writeHeader().
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::metaData()" << url;
 #endif
     Q_D(QNetworkDiskCache);
     if (d->lastItem.metaData.url() == url)
         return d->lastItem.metaData;
     return fileMetaData(d->cacheFileName(url));
 }
prepare()
QIODevice * QNetworkDiskCache::prepare (const QNetworkCacheMetaData & metaData) virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 187 of file qnetworkdiskcache.cpp.
Referenced by updateMetaData().
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::prepare()" << metaData.url();
 #endif
     Q_D(QNetworkDiskCache);
     if (!metaData.isValid() || !metaData.url().isValid() || !metaData.saveToDisk())
         return 0;
     if (d->cacheDirectory.isEmpty()) {
         qWarning() << "QNetworkDiskCache::prepare() The cache directory is not set";
         return 0;
     }
     foreach (QNetworkCacheMetaData::RawHeader header, metaData.rawHeaders()) {
         if (header.first.toLower() == "content-length") {
             qint64 size = header.second.toInt();
             if (size > (maximumCacheSize() * 3)/4)
                 return 0;
             break;
         }
     }
     QScopedPointer<QCacheItem> cacheItem(new QCacheItem);
     cacheItem->metaData = metaData;
     QIODevice *device = 0;
     if (cacheItem->canCompress()) {
         cacheItem->data.open(QBuffer::ReadWrite);
         device = &(cacheItem->data);
     } else {
         QString templateName = d->tmpCacheFileName();
         QT_TRY {
             cacheItem->file = new QTemporaryFile(templateName, &cacheItem->data);
         } QT_CATCH(...) {
             cacheItem->file = 0;
         }
         if (!cacheItem->file || !cacheItem->file->open()) {
             qWarning() << "QNetworkDiskCache::prepare() unable to open temporary file";
             cacheItem.reset();
             return 0;
         }
         cacheItem->writeHeader(cacheItem->file);
         device = cacheItem->file;
     }
     d->inserting[device] = cacheItem.take();
     return device;
 }
remove()
bool QNetworkDiskCache::remove (const QUrl & url) virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 319 of file qnetworkdiskcache.cpp.
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::remove()" << url;
 #endif
     Q_D(QNetworkDiskCache);
     // remove is also used to cancel insertions, not a common operation
     QHashIterator<QIODevice*, QCacheItem*> it(d->inserting);
     while (it.hasNext()) {
         it.next();
         QCacheItem *item = it.value();
         if (item && item->metaData.url() == url) {
             delete item;
             d->inserting.remove(it.key());
             return true;
         }
     }
     if (d->lastItem.metaData.url() == url)
         d->lastItem.reset();
     return d->removeFile(d->cacheFileName(url));
 }
setCacheDirectory()
void QNetworkDiskCache::setCacheDirectory (const QString & cacheDir)
Sets the directory where cached files will be stored to cacheDir.
QNetworkDiskCache will create this directory if it does not exists.
Prepared cache items will be stored in the new cache directory when they are inserted.
See also
QDesktopServices::CacheLocation
Definition at line 148 of file qnetworkdiskcache.cpp.
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::setCacheDirectory()" << cacheDir;
 #endif
     Q_D(QNetworkDiskCache);
     if (cacheDir.isEmpty())
         return;
     d->cacheDirectory = cacheDir;
     QDir dir(d->cacheDirectory);
     d->cacheDirectory = dir.absolutePath();
     if (!d->cacheDirectory.endsWith(QLatin1Char('/')))
         d->cacheDirectory += QLatin1Char('/');
     d->dataDirectory = d->cacheDirectory + DATA_DIR + QString::number(CACHE_VERSION) + QLatin1Char('/');
     d->prepareLayout();
 }
setMaximumCacheSize()
void QNetworkDiskCache::setMaximumCacheSize (qint64 size)
Sets the maximum size of the disk cache to be size in bytes.
If the new size is smaller then the current cache size then the cache will call expire().
See also
maximumCacheSize()
Definition at line 501 of file qnetworkdiskcache.cpp.
 {
     Q_D(QNetworkDiskCache);
     bool expireCache = (size < d->maximumCacheSize);
     d->maximumCacheSize = size;
     if (expireCache)
         d->currentCacheSize = expire();
 }
updateMetaData()
void QNetworkDiskCache::updateMetaData (const QNetworkCacheMetaData & metaData) virtual
Reimplemented Function
Implements QAbstractNetworkCache.
Definition at line 453 of file qnetworkdiskcache.cpp.
 {
 #if defined(QNETWORKDISKCACHE_DEBUG)
     qDebug() << "QNetworkDiskCache::updateMetaData()" << metaData.url();
 #endif
     QUrl url = metaData.url();
     QIODevice *oldDevice = data(url);
     if (!oldDevice) {
 #if defined(QNETWORKDISKCACHE_DEBUG)
         qDebug() << "QNetworkDiskCache::updateMetaData(), no device!";
 #endif
         return;
     }
     QIODevice *newDevice = prepare(metaData);
     if (!newDevice) {
 #if defined(QNETWORKDISKCACHE_DEBUG)
         qDebug() << "QNetworkDiskCache::updateMetaData(), no new device!" << url;
 #endif
         return;
     }
     char data[1024];
     while (!oldDevice->atEnd()) {
         qint64 s = oldDevice->read(data, 1024);
         newDevice->write(data, s);
     }
     delete oldDevice;
     insert(newDevice);
 }
The documentation for this class was generated from the following files:
/src/network/access/qnetworkdiskcache.h
/src/network/access/qnetworkdiskcache.cpp