Qt 4.8: QAction Class Reference
QAction Class Reference
The QAction class provides an abstract user interface action that can be inserted into widgets.
#include <qaction.h>
Public Types
enum ActionEvent { Trigger, Hover }
This enum type is used when calling QAction::activate()
enum MenuRole {
NoRole, TextHeuristicRole, ApplicationSpecificRole, AboutQtRole,
AboutRole, PreferencesRole, QuitRole
}
This enum describes how an action should be moved into the application menu on Mac OS X.
enum Priority { LowPriority = 0, NormalPriority = 128, HighPriority = 256 }
This enum defines priorities for actions in user interface.
enum SoftKeyRole { NoSoftKey, PositiveSoftKey, NegativeSoftKey, SelectSoftKey }
This enum describes how an action should be placed in the softkey bar.
Public Slots
void hover ()
This is a convenience slot that calls activate(Hover).
void setChecked (bool)
void setDisabled (bool b)
This is a convenience function for the enabled property, that is useful for signals–slots connections.
void setEnabled (bool)
void setVisible (bool)
void toggle ()
This is a convenience function for the checked property.
void trigger ()
This is a convenience slot that calls activate(Trigger).
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void changed ()
This signal is emitted when an action has changed.
void hovered ()
This signal is emitted when an action is highlighted by the user; for example, when the user pauses with the cursor over a menu option, toolbar button, or presses an action's shortcut key combination.
void toggled (bool)
This signal is emitted whenever a checkable action changes its isChecked() status.
void triggered (bool checked=false)
This signal is emitted when an action is activated by the user; for example, when the user clicks a menu option, toolbar button, or presses an action's shortcut key combination, or when trigger() was called.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QActionGroup * actionGroup () const
Returns the action group for this action.
void activate (ActionEvent event)
Sends the relevant signals for ActionEvent event.
QList< QGraphicsWidget * > associatedGraphicsWidgets () const
Returns a list of widgets this action has been added to.
QList< QWidget * > associatedWidgets () const
Returns a list of widgets this action has been added to.
bool autoRepeat () const
QVariant data () const
Returns the user data as set in QAction::setData.
QFont font () const
QIcon icon () const
QString iconText () const
bool isCheckable () const
bool isChecked () const
bool isEnabled () const
bool isIconVisibleInMenu () const
bool isSeparator () const
Returns true if this action is a separator action; otherwise it returns false.
bool isVisible () const
QMenu * menu () const
Returns the menu contained by this action.
MenuRole menuRole () const
QWidget * parentWidget () const
Returns the parent widget.
Priority priority () const
QAction (QObject *parent)
Constructs an action with parent.
QAction (const QString &text, QObject *parent)
Constructs an action with some text and parent.
QAction (const QIcon &icon, const QString &text, QObject *parent)
Constructs an action with an icon and some text and parent.
void setActionGroup (QActionGroup *group)
Sets this action group to group.
void setAutoRepeat (bool)
void setCheckable (bool)
void setData (const QVariant &var)
Sets the action's internal data to the given userData.
void setFont (const QFont &font)
void setIcon (const QIcon &icon)
void setIconText (const QString &text)
void setIconVisibleInMenu (bool visible)
void setMenu (QMenu *menu)
Sets the menu contained by this action to the specified menu.
void setMenuRole (MenuRole menuRole)
void setPriority (Priority priority)
void setSeparator (bool b)
If b is true then this action will be considered a separator.
void setShortcut (const QKeySequence &shortcut)
void setShortcutContext (Qt::ShortcutContext context)
void setShortcuts (const QList< QKeySequence > &shortcuts)
Sets shortcuts as the list of shortcuts that trigger the action.
void setShortcuts (QKeySequence::StandardKey)
Sets a platform dependent list of shortcuts based on the key.
void setSoftKeyRole (SoftKeyRole softKeyRole)
void setStatusTip (const QString &statusTip)
void setText (const QString &text)
void setToolTip (const QString &tip)
void setWhatsThis (const QString &what)
QKeySequence shortcut () const
Qt::ShortcutContext shortcutContext () const
QList< QKeySequence > shortcuts () const
Returns the list of shortcuts, with the primary shortcut as the first element of the list.
bool showStatusText (QWidget *widget=0)
Updates the relevant status bar for the widget specified by sending a QStatusTipEvent to its parent widget.
SoftKeyRole softKeyRole () const
QString statusTip () const
QString text () const
QString toolTip () const
QString whatsThis () const
~QAction ()
Destroys the object and frees allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *)
Reimplemented Function
QAction (QActionPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool autoRepeat
whether the action can auto repeat
bool checkable
whether the action is a checkable action
bool checked
whether the action is checked.
bool enabled
whether the action is enabled
QFont font
the action's font
QIcon icon
the action's icon
QString iconText
the action's descriptive icon text
bool iconVisibleInMenu
Whether or not an action should show an icon in a menu.
MenuRole menuRole
the action's menu role
Priority priority
the actions's priority in the user interface.
QKeySequence shortcut
the action's primary shortcut key
Qt::ShortcutContext shortcutContext
the context for the action's shortcut
SoftKeyRole softKeyRole
the action's softkey role
QString statusTip
the action's status tip
QString text
the action's descriptive text
QString toolTip
the action's tooltip
bool visible
whether the action can be seen (e.g.
QString whatsThis
the action's "What's This?" help text
Friends
class QActionGroup
class QGraphicsWidget
class QMenu
class QMenuBar
class QMenuPrivate
class QShortcutMap
void qt_mac_clear_status_text (QAction *action)
class QToolButton
class QWidget
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAction class provides an abstract user interface action that can be inserted into widgets.
Warning
This function is not part of the public interface. parent and widget are different parent does not define context
In applications many common commands can be invoked via menus, toolbar buttons, and keyboard shortcuts. Since the user expects each command to be performed in the same way, regardless of the user interface used, it is useful to represent each command as an action.
Actions can be added to menus and toolbars, and will automatically keep them in sync. For example, in a word processor, if the user presses a Bold toolbar button, the Bold menu item will automatically be checked.
Actions can be created as independent objects, but they may also be created during the construction of menus; the QMenu class contains convenience functions for creating actions suitable for use as menu items.
A QAction may contain an icon, menu text, a shortcut, status text, "What's This?" text, and a tooltip. Most of these can be set in the constructor. They can also be set independently with setIcon(), setText(), setIconText(), setShortcut(), setStatusTip(), setWhatsThis(), and setToolTip(). For menu items, it is possible to set an individual font with setFont().
Actions are added to widgets using QWidget::addAction() or QGraphicsWidget::addAction(). Note that an action must be added to a widget before it can be used; this is also true when the shortcut should be global (i.e., Qt::ApplicationShortcut as Qt::ShortcutContext).
Once a QAction has been created it should be added to the relevant menu and toolbar, then connected to the slot which will perform the action. For example:
    openAct = new QAction(QIcon(":/images/open.png"), tr("&Open..."), this);
    openAct->setShortcuts(QKeySequence::Open);
    openAct->setStatusTip(tr("Open an existing file"));
    connect(openAct, SIGNAL(triggered()), this, SLOT(open()));
    fileMenu->addAction(openAct);
    fileToolBar->addAction(openAct);
We recommend that actions are created as children of the window they are used in. In most cases actions will be children of the application's main window.
See also
QMenu, QToolBar, {Application Example}
Definition at line 64 of file qaction.h.
Enumerations
ActionEvent
enum QAction::ActionEvent
This enum type is used when calling QAction::activate()
Trigger this will cause the QAction::triggered() signal to be emitted.
Hover this will cause the QAction::hovered() signal to be emitted.
Enumerator
Trigger
Hover
Definition at line 176 of file qaction.h.
 { Trigger, Hover };
MenuRole
enum QAction::MenuRole
This enum describes how an action should be moved into the application menu on Mac OS X.
NoRole This action should not be put into the application menu
TextHeuristicRole This action should be put in the application menu based on the action's text as described in the QMenuBar documentation.
ApplicationSpecificRole This action should be put in the application menu with an application specific role
AboutQtRole This action matches handles the "About Qt" menu item.
AboutRole This action should be placed where the "About" menu item is in the application menu. The text of the menu item will be set to "About <application name>". The application name is fetched from the Info.plist file in the application's bundle (See Deploying an Application on Mac OS X).
PreferencesRole This action should be placed where the "Preferences..." menu item is in the application menu.
QuitRole This action should be placed where the Quit menu item is in the application menu.
Setting this value only has effect on items that are in the immediate menus of the menubar, not the submenus of those menus. For example, if you have File menu in your menubar and the File menu has a submenu, setting the MenuRole for the actions in that submenu have no effect. They will never be moved.
Enumerator
NoRole
TextHeuristicRole
ApplicationSpecificRole
AboutQtRole
AboutRole
PreferencesRole
QuitRole
Definition at line 94 of file qaction.h.
                   { NoRole, TextHeuristicRole, ApplicationSpecificRole, AboutQtRole,
                     AboutRole, PreferencesRole, QuitRole };
Priority
enum QAction::Priority
This enum defines priorities for actions in user interface.
Since
4.6
LowPriority The action should not be prioritized in the user interface.
NormalPriority
HighPriority The action should be prioritized in the user interface.
See also
priority
Enumerator
LowPriority
NormalPriority
HighPriority
Definition at line 98 of file qaction.h.
                   { LowPriority = 0,
                     NormalPriority = 128,
                     HighPriority = 256};
SoftKeyRole
enum QAction::SoftKeyRole
This enum describes how an action should be placed in the softkey bar.
Since
4.6
Currently this enum only has an effect on the Symbian platform.
NoSoftKey This action should not be used as a softkey
PositiveSoftKey This action is used to describe a softkey with a positive or non-destructive role such as Ok, Select, or Options.
NegativeSoftKey This action is used to describe a soft ey with a negative or destructive role role such as Cancel, Discard, or Close.
SelectSoftKey This action is used to describe a role that selects a particular item or widget in the application.
Actions with a softkey role defined are only visible in the softkey bar when the widget containing the action has focus. If no widget currently has focus, the softkey framework will traverse up the widget parent hierarchy looking for a widget containing softkey actions.
Enumerator
NoSoftKey
PositiveSoftKey
NegativeSoftKey
SelectSoftKey
Definition at line 96 of file qaction.h.
                      {
                     NoSoftKey, PositiveSoftKey, NegativeSoftKey, SelectSoftKey };
Constructors and Destructors
QAction() [1/4]
QAction::QAction (QObject * parent) explicit
Constructs an action with parent.
If parent is an action group the action will be automatically inserted into the group.
Definition at line 328 of file qaction.cpp.
Referenced by setFont().
     : QObject(*(new QActionPrivate), parent)
 {
     Q_D(QAction);
     d->group = qobject_cast<QActionGroup *>(parent);
     if (d->group)
         d->group->addAction(this);
 }
QAction() [2/4]
QAction::QAction (const QString & text, QObject * parent)
Constructs an action with some text and parent.
If parent is an action group the action will be automatically inserted into the group.
The action uses a stripped version of text (e.g. "\&Menu Option..." becomes "Menu Option") as descriptive text for tool buttons. You can override this by setting a specific description with setText(). The same text will be used for tooltips unless you specify a different text using setToolTip().
Definition at line 351 of file qaction.cpp.
     : QObject(*(new QActionPrivate), parent)
 {
     Q_D(QAction);
     d->text = text;
     d->group = qobject_cast<QActionGroup *>(parent);
     if (d->group)
         d->group->addAction(this);
 }
QAction() [3/4]
QAction::QAction (const QIcon & icon, const QString & text, QObject * parent)
Constructs an action with an icon and some text and parent.
If parent is an action group the action will be automatically inserted into the group.
The action uses a stripped version of text (e.g. "\&Menu Option..." becomes "Menu Option") as descriptive text for tool buttons. You can override this by setting a specific description with setText(). The same text will be used for tooltips unless you specify a different text using setToolTip().
Definition at line 373 of file qaction.cpp.
     : QObject(*(new QActionPrivate), parent)
 {
     Q_D(QAction);
     d->icon = icon;
     d->text = text;
     d->group = qobject_cast<QActionGroup *>(parent);
     if (d->group)
         d->group->addAction(this);
 }
~QAction()
QAction::~QAction ()
Destroys the object and frees allocated resources.
Definition at line 694 of file qaction.cpp.
 {
     Q_D(QAction);
     for (int i = d->widgets.size()-1; i >= 0; --i) {
         QWidget *w = d->widgets.at(i);
         w->removeAction(this);
     }
 #ifndef QT_NO_GRAPHICSVIEW
     for (int i = d->graphicsWidgets.size()-1; i >= 0; --i) {
         QGraphicsWidget *w = d->graphicsWidgets.at(i);
         w->removeAction(this);
     }
 #endif
     if (d->group)
         d->group->removeAction(this);
 #ifndef QT_NO_SHORTCUT
     if (d->shortcutId && qApp) {
         qApp->d_func()->shortcutMap.removeShortcut(d->shortcutId, this);
         for(int i = 0; i < d->alternateShortcutIds.count(); ++i) {
             const int id = d->alternateShortcutIds.at(i);
             qApp->d_func()->shortcutMap.removeShortcut(id, this);
         }
     }
 #endif
 }
QAction() [4/4]
QAction::QAction (QActionPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 387 of file qaction.cpp.
     : QObject(dd, parent)
 {
     Q_D(QAction);
     d->group = qobject_cast<QActionGroup *>(parent);
     if (d->group)
         d->group->addAction(this);
 }
Functions
actionGroup()
QActionGroup * QAction::actionGroup () const
Returns the action group for this action.
If no action group manages this action then 0 will be returned.
See also
QActionGroup, QAction::setActionGroup()
Definition at line 747 of file qaction.cpp.
Referenced by QMenu::initStyleOption(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     Q_D(const QAction);
     return d->group;
 }
activate()
void QAction::activate (ActionEvent event)
Sends the relevant signals for ActionEvent event.
Action based widgets use this API to cause the QAction to emit signals as well as emitting their own.
Definition at line 1326 of file qaction.cpp.
Referenced by QMenuBarPrivate::activateAction(), QMenuPrivate::activateCausedStack(), event(), qt_mac_activate_action(), and QMenuBarPrivate::wceEmitSignals().
 {
     Q_D(QAction);
     if(event == Trigger) {
         QObject *guard = this;
         QMetaObject::addGuard(&guard);
         if(d->checkable) {
             // the checked action of an exclusive group cannot be  unchecked
             if (d->checked && (d->group && d->group->isExclusive()
                                && d->group->checkedAction() == this)) {
                 if (guard)
                     emit triggered(true);
                 QMetaObject::removeGuard(&guard);
                 return;
             }
             setChecked(!d->checked);
         }
         if (guard)
             emit triggered(d->checked);
 #ifdef QT3_SUPPORT
         if (guard)
             emit activated(d->param);
 #endif
         QMetaObject::removeGuard(&guard);
     } else if(event == Hover) {
         emit hovered();
     }
 }
associatedGraphicsWidgets()
QList< QGraphicsWidget * > QAction::associatedGraphicsWidgets () const
Returns a list of widgets this action has been added to.
Since
4.5
See also
QWidget::addAction(), associatedWidgets()
Definition at line 432 of file qaction.cpp.
 {
     Q_D(const QAction);
     return d->graphicsWidgets;
 }
associatedWidgets()
QList< QWidget * > QAction::associatedWidgets () const
Returns a list of widgets this action has been added to.
Since
4.2
See also
QWidget::addAction(), associatedGraphicsWidgets()
Definition at line 416 of file qaction.cpp.
Referenced by QDialogButtonBox::event(), and waitForPopup().
 {
     Q_D(const QAction);
     return d->widgets;
 }
autoRepeat()
bool QAction::autoRepeat () const
Referenced by setAutoRepeat().
changed
void QAction::changed () signal
This signal is emitted when an action has changed.
If you are only interested in actions in a given widget, you can watch for QWidget::actionEvent() sent with an QEvent::ActionChanged.
See also
QWidget::actionEvent()
data()
QVariant QAction::data () const
Returns the user data as set in QAction::setData.
See also
setData()
Definition at line 1280 of file qaction.cpp.
Referenced by QCalendarWidgetPrivate::_q_monthChanged(), QmlJSDebugger::QmlToolBar::changeAnimationSpeed(), QMultiInputContext::changeSlave(), QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected(), QmlJSDebugger::QmlToolBar::setAnimationSpeed(), and setData().
 {
     Q_D(const QAction);
     return d->userData;
 }
event()
bool QAction::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Reimplemented in QWidgetAction.
Definition at line 1256 of file qaction.cpp.
Referenced by QWidgetAction::event().
 {
 #ifndef QT_NO_SHORTCUT
     if (e->type() == QEvent::Shortcut) {
         QShortcutEvent *se = static_cast<QShortcutEvent *>(e);
         Q_ASSERT_X(se->key() == d_func()->shortcut || d_func()->alternateShortcuts.contains(se->key()),
                    "QAction::event",
                    "Received shortcut event from incorrect shortcut");
         if (se->isAmbiguous())
             qWarning("QAction::eventFilter: Ambiguous shortcut overload: %s", QString(se->key()).toLatin1().constData());
         else
             activate(Trigger);
         return true;
     }
 #endif
     return QObject::event(e);
 }
font()
QFont QAction::font () const
Referenced by setFont().
hover
void QAction::hover () inline slot
This is a convenience slot that calls activate(Hover).
Definition at line 219 of file qaction.h.
 { activate(Hover); }
hovered
void QAction::hovered () signal
This signal is emitted when an action is highlighted by the user; for example, when the user pauses with the cursor over a menu option, toolbar button, or presses an action's shortcut key combination.
See also
QAction::activate()
Referenced by activate().
icon()
QIcon QAction::icon () const
Referenced by QAction(), setFont(), and setIcon().
iconText()
QString QAction::iconText () const
Referenced by setIconText().
isCheckable()
bool QAction::isCheckable () const
Definition at line 1105 of file qaction.cpp.
Referenced by QMenu::initStyleOption(), qt_wce_insert_action(), QToolButton::setDefaultAction(), and QMenuPrivate::updateActionRects().
 {
     Q_D(const QAction);
     return d->checkable;
 }
isChecked()
bool QAction::isChecked () const
Definition at line 1151 of file qaction.cpp.
Referenced by QActionGroupPrivate::_q_actionChanged(), QFileDialogPrivate::_q_showHeader(), QFileDialogPrivate::_q_showHidden(), QWhatsThisAction::actionTriggered(), QActionGroup::addAction(), QAxServerBase::createPopup(), QMenu::initStyleOption(), qt_wce_insert_action(), QToolButton::setDefaultAction(), QPrintPreviewDialogPrivate::setFitting(), QAccessibleMenu::state(), QAccessibleMenuItem::state(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     Q_D(const QAction);
     return d->checked;
 }
isEnabled()
bool QAction::isEnabled () const
Definition at line 1208 of file qaction.cpp.
Referenced by QMenuBarPrivate::activateAction(), QMenuPrivate::activateAction(), QAxServerBase::createMenu(), QAxServerBase::createPopup(), QAccessibleMenu::doAction(), QAccessibleMenuBar::doAction(), QWidgetAction::event(), QMenuBarPrivate::getNextAction(), QMenuBar::initStyleOption(), QMenu::initStyleOption(), QMenu::keyPressEvent(), QMenu::popup(), QMenuBarPrivate::popupAction(), QMenuPrivate::popupAction(), qt_mac_set_modal_state(), qt_mac_set_modal_state_helper_recursive(), qt_wce_insert_action(), QMenuPrivate::scrollMenu(), QToolButton::setDefaultAction(), QWidgetAction::setDefaultWidget(), QMenuPrivate::setFirstActionActive(), QMenuPrivate::setMacMenuEnabled(), QMenuPrivate::setSyncAction(), QAccessibleMenu::state(), QAccessibleMenuBar::state(), QAccessibleMenuItem::state(), QMenuBarPrivate::QMacMenuBarPrivate::syncAction(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     Q_D(const QAction);
     return d->enabled;
 }
isIconVisibleInMenu()
bool QAction::isIconVisibleInMenu () const
Definition at line 1651 of file qaction.cpp.
Referenced by QMenu::initStyleOption(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     Q_D(const QAction);
     if (d->iconVisibleInMenu == -1) {
         return !QApplication::instance()->testAttribute(Qt::AA_DontShowIconsInMenus);
     }
     return d->iconVisibleInMenu;
 }
isSeparator()
bool QAction::isSeparator () const
Returns true if this action is a separator action; otherwise it returns false.
See also
QAction::setSeparator()
Definition at line 839 of file qaction.cpp.
Referenced by QAccessibleMenu::actionText(), QAccessibleMenuBar::actionText(), QMenuPrivate::activateAction(), QMenuBarPrivate::QMacMenuBarPrivate::addAction(), QMenuBarPrivate::calcActionRects(), QAccessibleMenu::childAt(), QToolBarLayout::createItem(), QAxServerBase::createMenu(), QAxServerBase::createPopup(), QMenuPrivate::getLastVisibleAction(), QMenu::initStyleOption(), QMenu::isEmpty(), QMenu::keyPressEvent(), QMenu::mouseMoveEvent(), qt_mac_menu_event(), qt_mac_menu_merge_action(), qt_wce_insert_action(), QAccessibleMenu::role(), QAccessibleMenuBar::role(), QAccessibleMenuItem::role(), QMenuPrivate::scrollMenu(), QMenuPrivate::setCurrentAction(), QMenuPrivate::setFirstActionActive(), QMenuPrivate::setSyncAction(), QAccessibleMenu::state(), QAccessibleMenuBar::state(), QAccessibleMenuItem::state(), QMenuPrivate::QMacMenuPrivate::syncAction(), and QMenuPrivate::updateActionRects().
 {
     Q_D(const QAction);
     return d->separator;
 }
isVisible()
bool QAction::isVisible () const
Definition at line 1246 of file qaction.cpp.
Referenced by actualMenuItemVisibility(), QSoftKeyManager::appendSoftkeys(), QMenuBarPrivate::calcActionRects(), QMenuPrivate::getLastVisibleAction(), QToolBarItem::isEmpty(), QMenu::isEmpty(), QMenuBarPrivate::macUpdateMenuBarImmediatly(), qt_mac_menu_event(), qt_wce_insert_action(), QAccessibleMenuItem::state(), QMenuPrivate::QMacMenuPrivate::syncAction(), and QMenuPrivate::updateActionRects().
 {
     Q_D(const QAction);
     return d->visible;
 }
menu()
QMenu * QAction::menu () const
Returns the menu contained by this action.
Actions that contain menus can be used to create menu items with submenus, or inserted into toolbars to create buttons with popup menus.
See also
QMenu::addAction()
Definition at line 793 of file qaction.cpp.
Referenced by QMenuBarPrivate::_q_internalShortcutActivated(), QAccessibleMenu::actionText(), QAccessibleMenuBar::actionText(), QAccessibleMenuItem::actionText(), actualMenuItemVisibility(), QAccessibleMenuItem::childCount(), QAxServerBase::createMenu(), QAxServerBase::createPopup(), QAccessibleMenu::doAction(), QAccessibleMenuBar::doAction(), QAccessibleMenuItem::doAction(), QToolButtonPrivate::hasMenu(), QAccessibleMenuItem::indexOfChild(), QMenuPrivate::init(), QMenu::initStyleOption(), QMenu::keyPressEvent(), QMenuBar::mouseReleaseEvent(), QMenu::mouseReleaseEvent(), QAxClientSite::OnPosRectChange(), QMenuBarPrivate::popupAction(), QMenuPrivate::popupAction(), QToolButtonPrivate::popupTimerDone(), qt_mac_menu_merge_action(), qt_wce_get_quit_action(), qt_wce_insert_action(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QAccessibleMenuItem::rect(), QDecoration::region(), QMenuPrivate::setCurrentAction(), QToolButton::setDefaultAction(), setMenu(), QMenuBar::setNativeMenuBar(), QMenu::setSeparatorsCollapsible(), QMenuPrivate::setSyncAction(), QAccessibleMenuItem::state(), QMenuBarPrivate::QMacMenuBarPrivate::syncAction(), QMenuPrivate::QMacMenuPrivate::syncAction(), QAccessibleMenuItem::text(), QMenuPrivate::wceCommands(), and QMenuBarPrivate::wceEmitSignals().
 {
     Q_D(const QAction);
     return d->menu;
 }
menuRole()
MenuRole QAction::menuRole () const
Referenced by setMenuRole().
parentWidget()
QWidget * QAction::parentWidget () const
Returns the parent widget.
Definition at line 399 of file qaction.cpp.
Referenced by QSoftKeyManager::sendKeyEvent().
 {
     QObject *ret = parent();
     while (ret && !ret->isWidgetType())
         ret = ret->parent();
     return (QWidget*)ret;
 }
priority()
Priority QAction::priority () const
Referenced by setPriority().
setActionGroup()
void QAction::setActionGroup (QActionGroup * group)
Sets this action group to group.
The action will be automatically added to the group's list of actions.
Actions within the group will be mutually exclusive.
See also
QActionGroup, QAction::actionGroup()
Definition at line 728 of file qaction.cpp.
 {
     Q_D(QAction);
     if(group == d->group)
         return;
     if(d->group)
         d->group->removeAction(this);
     d->group = group;
     if(group)
         group->addAction(this);
 }
setAutoRepeat()
void QAction::setAutoRepeat (bool on)
Definition at line 589 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->autorepeat == on)
         return;
     QAPP_CHECK("setAutoRepeat");
     d->autorepeat = on;
     d->redoGrab(qApp->d_func()->shortcutMap);
     d->redoGrabAlternate(qApp->d_func()->shortcutMap);
     d->sendDataChanged();
 }
setCheckable()
void QAction::setCheckable (bool b)
Definition at line 1094 of file qaction.cpp.
Referenced by QFileDialogPrivate::createMenuActions(), QMdiSubWindowPrivate::createSystemMenu(), QFileDialogPrivate::createWidgets(), QmlJSDebugger::QmlToolBar::QmlToolBar(), QMultiInputContext::QMultiInputContext(), QWhatsThis::QWhatsThis(), and QWhatsThisAction::QWhatsThisAction().
 {
     Q_D(QAction);
     if (d->checkable == b)
         return;
     d->checkable = b;
     d->checked = false;
     d->sendDataChanged();
 }
setChecked
void QAction::setChecked (bool b) slot
Definition at line 1138 of file qaction.cpp.
Referenced by QActionGroupPrivate::_q_actionChanged(), activate(), QmlJSDebugger::QmlToolBar::activateColorPickerOnClick(), QmlJSDebugger::QmlToolBar::activateMarqueeSelectToolOnClick(), QmlJSDebugger::QmlToolBar::activateSelectToolOnClick(), QmlJSDebugger::QmlToolBar::activateZoomOnClick(), QFileDialogPrivate::createWidgets(), QWorkspacePrivate::init(), QmlJSDebugger::QmlToolBar::QmlToolBar(), QMultiInputContext::QMultiInputContext(), QFileDialog::restoreState(), QmlJSDebugger::QmlToolBar::setAnimationSpeed(), QmlJSDebugger::QmlToolBar::setDesignModeBehavior(), QPrintPreviewDialogPrivate::setFitting(), toggle(), and QWhatsThisPrivate::~QWhatsThisPrivate().
 {
     Q_D(QAction);
     if (!d->checkable || d->checked == b)
         return;
     QPointer<QAction> guard(this);
     d->checked = b;
     d->sendDataChanged();
     if (guard)
         emit toggled(b);
 }
setData()
void QAction::setData (const QVariant & userData)
Sets the action's internal data to the given userData.
See also
data()
Definition at line 1297 of file qaction.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::createContextMenu(), QCalendarWidgetPrivate::createNavigationBar(), QmlJSDebugger::QmlToolBar::QmlToolBar(), and QMultiInputContext::QMultiInputContext().
 {
     Q_D(QAction);
     d->userData = data;
     d->sendDataChanged();
 }
setDisabled
void QAction::setDisabled (bool b) inline slot
This is a convenience function for the enabled property, that is useful for signals–slots connections.
If b is true the action is disabled; otherwise it is enabled.
Definition at line 223 of file qaction.h.
Referenced by QDecoration::buildSysMenu().
 { setEnabled(!b); }
setEnabled
void QAction::setEnabled (bool b) slot
Definition at line 1192 of file qaction.cpp.
Referenced by QScriptDebuggerPrivate::_q_onFindCodeRequest(), QFileDialogPrivate::_q_showContextMenu(), QActionGroup::addAction(), QDecoration::buildSysMenu(), QAbstractSpinBox::contextMenuEvent(), QFileDialogPrivate::createMenuActions(), QUndoGroup::createRedoAction(), QUndoStack::createRedoAction(), QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), QMdiSubWindowPrivate::createSystemMenu(), QUndoGroup::createUndoAction(), QUndoStack::createUndoAction(), QScriptDebuggerPrivate::handleResponse(), QmlJSDebugger::QmlToolBar::setDesignModeBehaviorOnClick(), QMdiSubWindowPrivate::setEnabled(), QSidebar::showContextMenu(), QScriptDebuggerPrivate::startInteraction(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     Q_D(QAction);
     if (b == d->enabled && b != d->forceDisabled)
         return;
     d->forceDisabled = !b;
     if (b && (!d->visible || (d->group && !d->group->isEnabled())))
         return;
     QAPP_CHECK("setEnabled");
     d->enabled = b;
 #ifndef QT_NO_SHORTCUT
     d->setShortcutEnabled(b, qApp->d_func()->shortcutMap);
 #endif
     d->sendDataChanged();
 }
setFont()
void QAction::setFont (const QFont & font)
Definition at line 623 of file qaction.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::createContextMenu().
 {
     Q_D(QAction);
     if (d->font == font)
         return;
     d->fontSet = true;
     d->font = font;
     d->sendDataChanged();
 }
setIcon()
void QAction::setIcon (const QIcon & icon)
Definition at line 772 of file qaction.cpp.
Referenced by QMdiSubWindowPrivate::createSystemMenu(), QMenuBar::defaultAction(), menuItemEntry(), qt_setupActionIcon(), QWhatsThis::QWhatsThis(), QWhatsThisAction::QWhatsThisAction(), QMenu::setSeparatorsCollapsible(), and QmlJSDebugger::QmlToolBar::updatePlayAction().
 {
     Q_D(QAction);
     d->icon = icon;
     d->sendDataChanged();
 }
setIconText()
void QAction::setIconText (const QString & text)
Definition at line 907 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->iconText == text)
         return;
     d->iconText = text;
     d->sendDataChanged();
 }
setIconVisibleInMenu()
void QAction::setIconVisibleInMenu (bool visible)
Definition at line 1636 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->iconVisibleInMenu == -1 || visible != bool(d->iconVisibleInMenu)) {
         int oldValue = d->iconVisibleInMenu;
         d->iconVisibleInMenu = visible;
         // Only send data changed if we really need to.
         if (oldValue != -1
             || (oldValue == -1
                 && visible == !QApplication::instance()->testAttribute(Qt::AA_DontShowIconsInMenus))) {
             d->sendDataChanged();
         }
     }
 }
setMenu()
void QAction::setMenu (QMenu * menu)
Sets the menu contained by this action to the specified menu.
Definition at line 802 of file qaction.cpp.
Referenced by QmlJSDebugger::QmlToolBar::QmlToolBar().
 {
     Q_D(QAction);
     if (d->menu)
         d->menu->d_func()->setOverrideMenuAction(0); //we reset the default action of any previous menu
     d->menu = menu;
     if (menu)
         menu->d_func()->setOverrideMenuAction(this);
     d->sendDataChanged();
 }
setMenuRole()
void QAction::setMenuRole (MenuRole menuRole)
Definition at line 1569 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->menuRole == menuRole)
         return;
     d->menuRole = menuRole;
     d->sendDataChanged();
 }
setPriority()
void QAction::setPriority (Priority priority)
Definition at line 1056 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->priority == priority)
         return;
     d->priority = priority;
     d->sendDataChanged();
 }
setSeparator()
void QAction::setSeparator (bool b)
If b is true then this action will be considered a separator.
How a separator is represented depends on the widget it is inserted into. Under most circumstances the text, submenu, and icon will be ignored for separator actions.
See also
QAction::isSeparator()
Definition at line 823 of file qaction.cpp.
Referenced by QMenuBar::addSeparator(), QMenu::addSeparator(), QToolBar::addSeparator(), QMenuBar::defaultAction(), QMenuBar::insertSeparator(), QMenu::insertSeparator(), QToolBar::insertSeparator(), QMultiInputContext::QMultiInputContext(), and QMenu::setSeparatorsCollapsible().
 {
     Q_D(QAction);
     if (d->separator == b)
         return;
     d->separator = b;
     d->sendDataChanged();
 }
setShortcut()
void QAction::setShortcut (const QKeySequence & shortcut)
Definition at line 450 of file qaction.cpp.
Referenced by QMenu::addAction(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QFileDialogPrivate::createMenuActions(), QMenuBar::defaultAction(), menuItemEntry(), QWhatsThisAction::QWhatsThisAction(), setFont(), QMenu::setSeparatorsCollapsible(), and QmlJSDebugger::ZoomTool::ZoomTool().
 {
     QAPP_CHECK("setShortcut");
     Q_D(QAction);
     if (d->shortcut == shortcut)
         return;
     d->shortcut = shortcut;
     d->redoGrab(qApp->d_func()->shortcutMap);
     d->sendDataChanged();
 }
setShortcutContext()
void QAction::setShortcutContext (Qt::ShortcutContext context)
Definition at line 558 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->shortcutContext == context)
         return;
     QAPP_CHECK("setShortcutContext");
     d->shortcutContext = context;
     d->redoGrab(qApp->d_func()->shortcutMap);
     d->redoGrabAlternate(qApp->d_func()->shortcutMap);
     d->sendDataChanged();
 }
setShortcuts() [1/2]
void QAction::setShortcuts (const QList< QKeySequence > & shortcuts)
Sets shortcuts as the list of shortcuts that trigger the action.
Since
4.2
The first element of the list is the primary shortcut.
See also
shortcut
Definition at line 474 of file qaction.cpp.
Referenced by QMdiSubWindowPrivate::createSystemMenu(), and setShortcuts().
 {
     Q_D(QAction);
     QList <QKeySequence> listCopy = shortcuts;
     QKeySequence primary;
     if (!listCopy.isEmpty())
         primary = listCopy.takeFirst();
     if (d->shortcut == primary && d->alternateShortcuts == listCopy)
         return;
     QAPP_CHECK("setShortcuts");
     d->shortcut = primary;
     d->alternateShortcuts = listCopy;
     d->redoGrab(qApp->d_func()->shortcutMap);
     d->redoGrabAlternate(qApp->d_func()->shortcutMap);
     d->sendDataChanged();
 }
setShortcuts() [2/2]
void QAction::setShortcuts (QKeySequence::StandardKey key)
Sets a platform dependent list of shortcuts based on the key.
Since
4.2
The result of calling this function will depend on the currently running platform. Note that more than one shortcut can assigned by this action. If only the primary shortcut is required, use setShortcut instead.
See also
QKeySequence::keyBindings()
Definition at line 509 of file qaction.cpp.
 {
     QList <QKeySequence> list = QKeySequence::keyBindings(key);
     setShortcuts(list);
 }
setSoftKeyRole()
void QAction::setSoftKeyRole (SoftKeyRole softKeyRole)
Definition at line 1599 of file qaction.cpp.
Referenced by QDialogButtonBoxPrivate::addButton(), QSoftKeyManager::createAction(), and QWizardPrivate::ensureButton().
 {
     Q_D(QAction);
     if (d->softKeyRole == softKeyRole)
         return;
     d->softKeyRole = softKeyRole;
     d->sendDataChanged();
 }
setStatusTip()
void QAction::setStatusTip (const QString & statusTip)
Definition at line 974 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->statustip == statustip)
         return;
     d->statustip = statustip;
     d->sendDataChanged();
 }
setText()
void QAction::setText (const QString & text)
Definition at line 860 of file qaction.cpp.
Referenced by QMenuBar::defaultAction(), QFileDialogPrivate::retranslateStrings(), QDialogButtonBoxPrivate::retranslateStrings(), QUndoAction::setPrefixedText(), and QMenu::setSeparatorsCollapsible().
 {
     Q_D(QAction);
     if (d->text == text)
         return;
     d->text = text;
     d->sendDataChanged();
 }
setToolTip()
void QAction::setToolTip (const QString & tip)
Definition at line 939 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->tooltip == tooltip)
         return;
     d->tooltip = tooltip;
     d->sendDataChanged();
 }
setVisible
void QAction::setVisible (bool b) slot
Definition at line 1230 of file qaction.cpp.
Referenced by QActionGroup::addAction(), QSoftKeyManager::createAction(), QAxClientSite::qt_metacall(), QWidgetAction::setDefaultWidget(), and QMdiSubWindowPrivate::setVisible().
 {
     Q_D(QAction);
     if (b == d->visible && b != d->forceInvisible)
         return;
     QAPP_CHECK("setVisible");
     d->forceInvisible = !b;
     d->visible = b;
     d->enabled = b && !d->forceDisabled && (!d->group || d->group->isEnabled()) ;
 #ifndef QT_NO_SHORTCUT
     d->setShortcutEnabled(d->enabled, qApp->d_func()->shortcutMap);
 #endif
     d->sendDataChanged();
 }
setWhatsThis()
void QAction::setWhatsThis (const QString & what)
Definition at line 1003 of file qaction.cpp.
 {
     Q_D(QAction);
     if (d->whatsthis == whatsthis)
         return;
     d->whatsthis = whatsthis;
     d->sendDataChanged();
 }
shortcut()
QKeySequence QAction::shortcut () const
Referenced by setFont(), setShortcut(), and setShortcuts().
shortcutContext()
Qt::ShortcutContext QAction::shortcutContext () const
Referenced by setShortcutContext().
shortcuts()
QList< QKeySequence > QAction::shortcuts () const
Returns the list of shortcuts, with the primary shortcut as the first element of the list.
Since
4.2
See also
setShortcuts()
Definition at line 537 of file qaction.cpp.
Referenced by setShortcuts().
 {
     Q_D(const QAction);
     QList <QKeySequence> shortcuts;
     if (!d->shortcut.isEmpty())
         shortcuts << d->shortcut;
     if (!d->alternateShortcuts.isEmpty())
         shortcuts << d->alternateShortcuts;
     return shortcuts;
 }
showStatusText()
bool QAction::showStatusText (QWidget * widget = 0)
Updates the relevant status bar for the widget specified by sending a QStatusTipEvent to its parent widget.
Returns true if an event was sent; otherwise returns false.
If a null widget is specified, the event is sent to the action's parent.
See also
statusTip
Definition at line 1315 of file qaction.cpp.
Referenced by QMenuBarPrivate::activateAction(), QMenuPrivate::activateAction(), qt_mac_activate_action(), and QMenuPrivate::setCurrentAction().
 {
     return d_func()->showStatusText(widget, statusTip());
 }
softKeyRole()
SoftKeyRole QAction::softKeyRole () const
Referenced by setSoftKeyRole().
statusTip()
QString QAction::statusTip () const
Referenced by setStatusTip(), and showStatusText().
text()
QString QAction::text () const
Referenced by QAction(), setFont(), setIconText(), and setText().
toggle
void QAction::toggle () slot
This is a convenience function for the checked property.
Connect to it to change the checked state to its opposite state.
Definition at line 1120 of file qaction.cpp.
 {
     Q_D(QAction);
     setChecked(!d->checked);
 }
toggled
void QAction::toggled (bool checked) signal
This signal is emitted whenever a checkable action changes its isChecked() status.
This can be the result of a user interaction, or because setChecked() was called.
checked is true if the action is checked, or false if the action is unchecked.
See also
QAction::activate(), QAction::triggered(), checked
Referenced by QWhatsThis::QWhatsThis(), and setChecked().
toolTip()
QString QAction::toolTip () const
Referenced by setToolTip().
trigger
void QAction::trigger () inline slot
This is a convenience slot that calls activate(Trigger).
Definition at line 218 of file qaction.h.
Referenced by QAccessibleMenuItem::doAction().
 { activate(Trigger); }
triggered
void QAction::triggered (bool checked = false) signal
This signal is emitted when an action is activated by the user; for example, when the user clicks a menu option, toolbar button, or presses an action's shortcut key combination, or when trigger() was called.
Notably, it is not emitted when setChecked() or toggle() is called.
If the action is checkable, checked is true if the action is checked, or false if the action is unchecked.
See also
QAction::activate(), QAction::toggled(), checked
Referenced by activate(), and QWhatsThisAction::QWhatsThisAction().
whatsThis()
QString QAction::whatsThis () const
Referenced by setWhatsThis().
Friends and Related Functions
QActionGroup
friend class QActionGroup friend
Definition at line 243 of file qaction.h.
QGraphicsWidget
friend class QGraphicsWidget friend
Definition at line 241 of file qaction.h.
QMenu
friend class QMenu friend
Definition at line 244 of file qaction.h.
QMenuBar
friend class QMenuBar friend
Definition at line 246 of file qaction.h.
QMenuPrivate
friend class QMenuPrivate friend
Definition at line 245 of file qaction.h.
QShortcutMap
friend class QShortcutMap friend
Definition at line 247 of file qaction.h.
qt_mac_clear_status_text
void qt_mac_clear_status_text (QAction * action) friend
QToolButton
friend class QToolButton friend
Definition at line 248 of file qaction.h.
Referenced by QWhatsThis::QWhatsThis().
QWidget
friend class QWidget friend
Definition at line 242 of file qaction.h.
Properties
autoRepeat
bool QAction::autoRepeat private
whether the action can auto repeat
Since
4.2
If true, the action will auto repeat when the keyboard shortcut combination is held down, provided that keyboard auto repeat is enabled on the system. The default value is true.
Definition at line 85 of file qaction.h.
Referenced by QToolButtonPrivate::popupTimerDone().
checkable
QAction::checkable private
whether the action is a checkable action
A checkable action is one which has an on/off state. For example, in a word processor, a Bold toolbar button may be either on or off. An action which is not a toggle action is a command action; a command action is simply executed, e.g. file save. By default, this property is false.
In some situations, the state of one toggle action should depend on the state of others. For example, "Left Align", "Center" and "Right Align" toggle actions are mutually exclusive. To achieve exclusive toggling, add the relevant toggle actions to a QActionGroup with the QActionGroup::exclusive property set to true.
See also
QAction::setChecked()
Definition at line 72 of file qaction.h.
checked
QAction::checked private
whether the action is checked.
Only checkable actions can be checked. By default, this is false (the action is unchecked).
See also
checkable
Definition at line 73 of file qaction.h.
enabled
QAction::enabled private
whether the action is enabled
Disabled actions cannot be chosen by the user. They do not disappear from menus or toolbars, but they are displayed in a way which indicates that they are unavailable. For example, they might be displayed using only shades of gray.
What's This? help on disabled actions is still available, provided that the QAction::whatsThis property is set.
An action will be disabled when all widgets to which it is added (with QWidget::addAction()) are disabled or not visible. When an action is disabled, it is not possible to trigger it through its shortcut.
By default, this property is true (actions are enabled).
See also
text
Definition at line 74 of file qaction.h.
font
QFont QAction::font private
the action's font
The font property is used to render the text set on the QAction. The font will can be considered a hint as it will not be consulted in all cases based upon application and style.
By default, this property contains the application's default font.
See also
QAction::setText() QStyle
Definition at line 81 of file qaction.h.
Referenced by QmlJSDebugger::LiveSelectionTool::createContextMenu(), QMenu::initStyleOption(), QToolButton::setDefaultAction(), and QMenuPrivate::QMacMenuPrivate::syncAction().
icon
QIcon QAction::icon private
the action's icon
In toolbars, the icon is used as the tool button icon; in menus, it is displayed to the left of the menu text. There is no default icon.
On Symbian the icons which are passed to softkeys, i.e. to actions with softkey role, need to have pixmap alpha channel correctly set otherwise drawing artifacts will appear when softkey is pressed down.
If a null icon (QIcon::isNull() is passed into this function, the icon of the action is cleared.
Definition at line 75 of file qaction.h.
Referenced by QMenuBarPrivate::calcActionRects(), QMenuBar::initStyleOption(), QMenu::initStyleOption(), QToolButton::setDefaultAction(), QMenuPrivate::QMacMenuPrivate::syncAction(), and QMenuPrivate::updateActionRects().
iconText
QString QAction::iconText private
the action's descriptive icon text
If QToolBar::toolButtonStyle is set to a value that permits text to be displayed, the text defined held in this property appears as a label in the relevant tool button.
It also serves as the default text in menus and tooltips if the action has not been defined with setText() or setToolTip(), and will also be used in toolbar buttons if no icon has been defined using setIcon().
If the icon text is not explicitly set, the action's normal text will be used for the icon text.
By default, this property contains an empty string.
See also
setToolTip(), setStatusTip()
Definition at line 77 of file qaction.h.
Referenced by qt_wce_insert_action(), QToolButton::setDefaultAction(), and QNSOpenSavePanelDelegate::strip:.
iconVisibleInMenu
QAction::iconVisibleInMenu private
Whether or not an action should show an icon in a menu.
Since
4.4
In some applications, it may make sense to have actions with icons in the toolbar, but not in menus. If true, the icon (if valid) is shown in the menu, when it is false, it is not shown.
The default is to follow whether the Qt::AA_DontShowIconsInMenus attribute is set for the application. Explicitly settings this property overrides the presence (or abscence) of the attribute.
For example:
QApplication app(argc, argv);
app.setAttribute(Qt::AA_DontShowIconsInMenus);  // Icons are *no longer shown* in menus
// ...
QAction *myAction = new QAction();
// ...
myAction->setIcon(SomeIcon);
myAction->setIconVisibleInMenu(true);   // Icon *will* be shown in menus for *this* action.
See also
QAction::icon QApplication::setAttribute()
Definition at line 90 of file qaction.h.
menuRole
QAction::MenuRole QAction::menuRole private
the action's menu role
Since
4.2
This indicates what role the action serves in the application menu on Mac OS X. By default all action have the TextHeuristicRole, which means that the action is added based on its text (see QMenuBar for more information).
The menu role can only be changed before the actions are put into the menu bar in Mac OS X (usually just before the first application window is shown).
Definition at line 88 of file qaction.h.
Referenced by qt_mac_menu_merge_accel(), qt_mac_menu_merge_action(), qt_mac_menu_merge_text(), qt_wce_get_quit_action(), QMenuPrivate::QMacMenuPrivate::syncAction(), and QMacMenuAction::~QMacMenuAction().
priority
QAction::Priority QAction::priority private
the actions's priority in the user interface.
Since
4.6
This property can be set to indicate how the action should be prioritized in the user interface.
For instance, when toolbars have the Qt::ToolButtonTextBesideIcon mode set, then actions with LowPriority will not show the text labels.
Definition at line 91 of file qaction.h.
shortcut
QKeySequence QAction::shortcut private
the action's primary shortcut key
Returns the primary shortcut.
Valid keycodes for this property can be found in Qt::Key and Qt::Modifier . There is no default shortcut key.
See also
setShortcuts()
Definition at line 83 of file qaction.h.
Referenced by QAccessibleWidget::actionText(), QMenu::initStyleOption(), QAccessibleMenuItem::keyBindings(), qt_mac_menu_event(), qt_mac_menu_merge_accel(), QMenuPrivate::QMacMenuPrivate::syncAction(), QAccessibleMenu::text(), QAccessibleMenuItem::text(), and QMenuPrivate::updateActionRects().
shortcutContext
Qt::ShortcutContext QAction::shortcutContext private
the context for the action's shortcut
Valid values for this property can be found in Qt::ShortcutContext . The default value is Qt::WindowShortcut.
Definition at line 84 of file qaction.h.
softKeyRole
QAction::SoftKeyRole QAction::softKeyRole private
the action's softkey role
Since
4.6
This indicates what type of role this action describes in the softkey framework on platforms where such a framework is supported. Currently this is only supported on the Symbian platform.
The softkey role can be changed any time.
Definition at line 89 of file qaction.h.
Referenced by QSoftKeyManager::appendSoftkeys().
statusTip
QString QAction::statusTip private
the action's status tip
The status tip is displayed on all status bars provided by the action's top-level parent widget.
By default, this property contains an empty string.
See also
setToolTip() showStatusText()
Definition at line 79 of file qaction.h.
Referenced by QToolButton::setDefaultAction().
text
QString QAction::text private
the action's descriptive text
If the action is added to a menu, the menu option will consist of the icon (if there is one), the text, and the shortcut (if there is one). If the text is not explicitly set in the constructor, or by using setText(), the action's description icon text will be used as text. There is no default text.
See also
iconText
Definition at line 76 of file qaction.h.
Referenced by QCalendarWidgetPrivate::_q_monthChanged(), QAccessibleWidget::actionText(), actualMenuItemVisibility(), QMenuBarPrivate::QMacMenuBarPrivate::addAction(), QMenuPrivate::QMacMenuPrivate::addAction(), QMenuBarPrivate::calcActionRects(), QAxServerBase::createMenu(), QAxServerBase::createPopup(), QMenuBar::initStyleOption(), QMenu::initStyleOption(), QMenuBar::keyPressEvent(), QMenu::keyPressEvent(), QAxClientSite::OnPosRectChange(), qt_mac_menu_merge_action(), qt_mac_menu_merge_text(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QMenuBarPrivate::QMacMenuBarPrivate::syncAction(), QMenuPrivate::QMacMenuPrivate::syncAction(), QAccessibleMenuItem::text(), QMenuPrivate::updateActionRects(), and QMenuBarPrivate::updateGeometries().
toolTip
QString QAction::toolTip private
the action's tooltip
This text is used for the tooltip. If no tooltip is specified, the action's text is used.
By default, this property contains the action's text.
See also
setStatusTip() setShortcut()
Definition at line 78 of file qaction.h.
Referenced by QAccessibleWidget::actionText(), and QToolButton::setDefaultAction().
visible
QAction::visible private
whether the action can be seen (e.g.
in menus and toolbars)
If visible is true the action can be seen (e.g. in menus and toolbars) and chosen by the user; if visible is false the action cannot be seen or chosen by the user.
Actions which are not visible are not grayed out; they do not appear at all.
By default, this property is true (actions are visible).
Definition at line 87 of file qaction.h.
Referenced by setIconVisibleInMenu().
whatsThis
QString QAction::whatsThis private
the action's "What's This?" help text
The "What's This?" text is used to provide a brief description of the action. The text may contain rich text. There is no default "What's This?" text.
See also
QWhatsThis Q3StyleSheet
Definition at line 80 of file qaction.h.
Referenced by QMenuPrivate::activateAction(), QToolButton::setDefaultAction(), and QAccessibleMenu::text().
The documentation for this class was generated from the following files:
/src/gui/kernel/qaction.h
/src/gui/kernel/qaction.cpp