Qt 4.8: QFutureSynchronizer< T > Class Template Reference
QFutureSynchronizer< T > Class Template Reference
The QFutureSynchronizer class is a convenience class that simplifies QFuture synchronization.
#include <qfuturesynchronizer.h>
Public Functions
void addFuture (const QFuture< T > &future)
Adds future to the list of managed futures.
bool cancelOnWait () const
Returns true if the cancel-on-wait feature is enabled; otherwise returns false.
void clearFutures ()
Removes all managed futures from this QFutureSynchronizer.
QList< QFuture< T > > futures () const
Returns a list of all managed futures.
QFutureSynchronizer ()
Constructs a QFutureSynchronizer.
QFutureSynchronizer (const QFuture< T > &future)
Constructs a QFutureSynchronizer and begins watching future by calling addFuture().
void setCancelOnWait (bool enabled)
Enables or disables the cancel-on-wait feature based on the enabled argument.
void setFuture (const QFuture< T > &future)
Sets future to be the only future managed by this QFutureSynchronizer.
void waitForFinished ()
Waits for all futures to finish.
~QFutureSynchronizer ()
Calls waitForFinished() function to ensure that all futures have finished before destroying this QFutureSynchronizer.
Protected Variables
bool m_cancelOnWait
QList< QFuture< T > > m_futures
Detailed Description
template<typename T>
class QFutureSynchronizer< T >
The QFutureSynchronizer class is a convenience class that simplifies QFuture synchronization.
Since
4.4
QFutureSynchronizer is a template class that simplifies synchronization of one or more QFuture objects. Futures are added using the addFuture() or setFuture() functions. The futures() function returns a list of futures. Use clearFutures() to remove all futures from the QFutureSynchronizer.
The waitForFinished() function waits for all futures to finish. The destructor of QFutureSynchronizer calls waitForFinished(), providing an easy way to ensure that all futures have finished before returning from a function:
void someFunction()
{
    QFutureSynchronizer<void> synchronizer;
    ...
    synchronizer.addFuture(QtConcurrent::run(anotherFunction));
    synchronizer.addFuture(QtConcurrent::map(list, mapFunction));
    return; // QFutureSynchronizer waits for all futures to finish
}
The behavior of waitForFinished() can be changed using the setCancelOnWait() function. Calling setCancelOnWait(true) will cause waitForFinished() to cancel all futures before waiting for them to finish. You can query the status of the cancel-on-wait feature using the cancelOnWait() function.
See also
QFuture, QFutureWatcher, {Concurrent Programming}{Qt Concurrent}
Definition at line 55 of file qfuturesynchronizer.h.
Constructors and Destructors
QFutureSynchronizer() [1/2]
template<typename T> QFutureSynchronizer< T >::QFutureSynchronizer () inline
Constructs a QFutureSynchronizer.
Definition at line 60 of file qfuturesynchronizer.h.
 : m_cancelOnWait(false) { }
QFutureSynchronizer() [2/2]
template<typename T> QFutureSynchronizer< T >::QFutureSynchronizer (const QFuture< T > & future) inline explicit
Constructs a QFutureSynchronizer and begins watching future by calling addFuture().
See also
addFuture()
Definition at line 61 of file qfuturesynchronizer.h.
         : m_cancelOnWait(false)
     { addFuture(future); }
~QFutureSynchronizer()
template<typename T> QFutureSynchronizer< T >::~QFutureSynchronizer () inline
Calls waitForFinished() function to ensure that all futures have finished before destroying this QFutureSynchronizer.
See also
waitForFinished()
Definition at line 64 of file qfuturesynchronizer.h.
 { waitForFinished(); }
Functions
addFuture()
template<typename T> void QFutureSynchronizer< T >::addFuture (const QFuture< T > & future) inline
Adds future to the list of managed futures.
See also
futures()
Definition at line 73 of file qfuturesynchronizer.h.
Referenced by QFutureSynchronizer< T >::QFutureSynchronizer(), and QFutureSynchronizer< T >::setFuture().
     {
         m_futures.append(future);
     }
cancelOnWait()
template<typename T> bool QFutureSynchronizer< T >::cancelOnWait () const inline
Returns true if the cancel-on-wait feature is enabled; otherwise returns false.
If cancel-on-wait is enabled, the waitForFinished() function will cancel all futures before waiting for them to finish.
See also
waitForFinished()
Definition at line 106 of file qfuturesynchronizer.h.
     {
         return m_cancelOnWait;
     }
clearFutures()
template<typename T> void QFutureSynchronizer< T >::clearFutures () inline
Removes all managed futures from this QFutureSynchronizer.
See also
addFuture(), setFuture()
Definition at line 91 of file qfuturesynchronizer.h.
     {
         m_futures.clear();
     }
futures()
template<typename T> QList< QFuture< T > > QFutureSynchronizer< T >::futures () const inline
Returns a list of all managed futures.
See also
addFuture(), setFuture()
Definition at line 96 of file qfuturesynchronizer.h.
     {
         return m_futures;
     }
setCancelOnWait()
template<typename T> void QFutureSynchronizer< T >::setCancelOnWait (bool enabled) inline
Enables or disables the cancel-on-wait feature based on the enabled argument.
If enabled is true, the waitForFinished() function will cancel all futures before waiting for them to finish.
See also
waitForFinished()
Definition at line 101 of file qfuturesynchronizer.h.
     {
         m_cancelOnWait = enabled;
     }
setFuture()
template<typename T> void QFutureSynchronizer< T >::setFuture (const QFuture< T > & future) inline
Sets future to be the only future managed by this QFutureSynchronizer.
This is a convenience function that calls waitForFinished(), then clearFutures(), and finally passes future to addFuture().
See also
addFuture(), waitForFinished(), clearFutures()
Definition at line 66 of file qfuturesynchronizer.h.
     {
         waitForFinished();
         m_futures.clear();
         addFuture(future);
     }
waitForFinished()
template<typename T> void QFutureSynchronizer< T >::waitForFinished () inline
Waits for all futures to finish.
If cancelOnWait() returns true, each future is canceled before waiting for them to finish.
See also
cancelOnWait(), setCancelOnWait()
Definition at line 78 of file qfuturesynchronizer.h.
Referenced by QFutureSynchronizer< T >::setFuture(), and QFutureSynchronizer< T >::~QFutureSynchronizer().
     {
         if (m_cancelOnWait) {
             for (int i = 0; i < m_futures.count(); ++i) {
                  m_futures[i].cancel();
             }
         }
         for (int i = 0; i < m_futures.count(); ++i) {
              m_futures[i].waitForFinished();
          }
     }
Properties
m_cancelOnWait
template<typename T> bool QFutureSynchronizer< T >::m_cancelOnWait protected
Definition at line 113 of file qfuturesynchronizer.h.
Referenced by QFutureSynchronizer< T >::cancelOnWait(), QFutureSynchronizer< T >::setCancelOnWait(), and QFutureSynchronizer< T >::waitForFinished().
m_futures
template<typename T> QList<QFuture<T> > QFutureSynchronizer< T >::m_futures protected
Definition at line 112 of file qfuturesynchronizer.h.
Referenced by QFutureSynchronizer< T >::addFuture(), QFutureSynchronizer< T >::clearFutures(), QFutureSynchronizer< T >::futures(), QFutureSynchronizer< T >::setFuture(), and QFutureSynchronizer< T >::waitForFinished().
The documentation for this class was generated from the following files:
/src/corelib/concurrent/qfuturesynchronizer.h
/src/corelib/concurrent/qfuturesynchronizer.cpp