Qt 4.8: QWindowsVistaPulse Class Reference
QWindowsVistaPulse Class Reference
#include <qwindowsvistastyle_p.h>
Public Functions
int duration () const
virtual void paint (QPainter *painter, const QStyleOption *option)
Paints a pulse.
QWindowsVistaPulse ()
void setAlternateImage (const QImage &image)
void setDuration (int duration)
void setPrimaryImage (const QImage &image)
virtual ~QWindowsVistaPulse ()
Public Functions inherited from QWindowsVistaAnimation
QWindowsVistaAnimation ()
bool running () const
void setRunning (bool val)
void setStartTime (const QTime &startTime)
void setWidget (QWidget *widget)
const QTime & startTime () const
QWidget * widget () const
virtual ~QWindowsVistaAnimation ()
Public Variables
int _duration
Additional Inherited Members
Protected Functions inherited from QWindowsVistaAnimation
void drawBlendedImage (QPainter *painter, QRect rect, float value)
Protected Variables inherited from QWindowsVistaAnimation
QImage _primaryImage
bool _running
QImage _secondaryImage
QTime _startTime
QImage _tempImage
QPointer< QWidget > _widget
Detailed Description
Definition at line 180 of file qwindowsvistastyle_p.h.
Constructors and Destructors
QWindowsVistaPulse()
QWindowsVistaPulse::QWindowsVistaPulse () inline
Definition at line 183 of file qwindowsvistastyle_p.h.
 : QWindowsVistaAnimation() {}
~QWindowsVistaPulse()
virtual QWindowsVistaPulse::~QWindowsVistaPulse () inline virtual
Definition at line 184 of file qwindowsvistastyle_p.h.
 { }
Functions
duration()
int QWindowsVistaPulse::duration () const inline
Definition at line 189 of file qwindowsvistastyle_p.h.
 { return _duration; }
paint()
void QWindowsVistaPulse::paint (QPainter * painter, const QStyleOption * option) virtual
Paints a pulse.
Warning
This function is not part of the public interface. The result will be a mix between the primary and secondary pulse images depending on the time difference between _startTime and current time.
Reimplemented from QWindowsVistaAnimation.
Definition at line 295 of file qwindowsvistastyle.cpp.
 {
     float alpha = 1.0;
     if (_duration > 0) {
         QTime current = QTime::currentTime();
         if (_startTime > current)
             _startTime = current;
         int timeDiff = _startTime.msecsTo(current) % _duration*2;
         if (timeDiff > _duration)
             timeDiff = _duration*2 - timeDiff;
         alpha = timeDiff/(float)_duration;
     } else {
         _running = false;
     }
     drawBlendedImage(painter, option->rect, alpha);
 }
setAlternateImage()
void QWindowsVistaPulse::setAlternateImage (const QImage & image) inline
Definition at line 187 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawControl().
 { _secondaryImage = image; }
setDuration()
void QWindowsVistaPulse::setDuration (int duration) inline
Definition at line 185 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawControl().
 { _duration = duration; }
setPrimaryImage()
void QWindowsVistaPulse::setPrimaryImage (const QImage & image) inline
Definition at line 186 of file qwindowsvistastyle_p.h.
Referenced by QWindowsVistaStyle::drawControl().
 { _primaryImage = image; }
Properties
_duration
int QWindowsVistaPulse::_duration
Definition at line 190 of file qwindowsvistastyle_p.h.
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowsvistastyle_p.h
/src/gui/styles/qwindowsvistastyle.cpp