Qt 4.8: QDeclarativeEngine Class Reference
QDeclarativeEngine Class Reference
The QDeclarativeEngine class provides an environment for instantiating QML components.
#include <qdeclarativeengine.h>
Public Types
enum ObjectOwnership { CppOwnership, JavaScriptOwnership }
Ownership controls whether or not QML automatically destroys the QObject when the object is garbage collected by the JavaScript engine.
Signals
void quit ()
This signal is emitted when the QML loaded by the engine would like to quit.
void warnings (const QList< QDeclarativeError > &warnings)
This signal is emitted when warnings messages are generated by QML.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addImageProvider (const QString &id, QDeclarativeImageProvider *)
Sets the provider to use for images requested via the image: url scheme, with host providerId.
void addImportPath (const QString &dir)
Adds path as a directory where the engine searches for installed modules in a URL-based directory structure.
void addPluginPath (const QString &dir)
Adds path as a directory where the engine searches for native plugins for imported modules (referenced in the qmldir file).
QUrl baseUrl () const
Return the base URL for this engine.
void clearComponentCache ()
Clears the engine's internal component cache.
QDeclarativeImageProvider * imageProvider (const QString &id) const
Returns the QDeclarativeImageProvider set for providerId.
QStringList importPathList () const
Returns the list of directories where the engine searches for installed modules in a URL-based directory structure.
bool importPlugin (const QString &filePath, const QString &uri, QString *errorString)
Imports the plugin named filePath with the uri provided.
QNetworkAccessManager * networkAccessManager () const
Returns a common QNetworkAccessManager which can be used by any QML element instantiated by this engine.
QDeclarativeNetworkAccessManagerFactory * networkAccessManagerFactory () const
Returns the current QDeclarativeNetworkAccessManagerFactory.
QString offlineStoragePath () const
bool outputWarningsToStandardError () const
Returns true if warning messages will be output to stderr in addition to being emitted by the warnings() signal, otherwise false.
QStringList pluginPathList () const
Returns the list of directories where the engine searches for native plugins for imported modules (referenced in the qmldir file).
QDeclarativeEngine (QObject *p=0)
Create a new QDeclarativeEngine with the given parent.
void removeImageProvider (const QString &id)
Removes the QDeclarativeImageProvider for providerId.
QDeclarativeContext * rootContext () const
Returns the engine's root context.
void setBaseUrl (const QUrl &)
Set the base URL for this engine to url.
void setImportPathList (const QStringList &paths)
Sets paths as the list of directories where the engine searches for installed modules in a URL-based directory structure.
void setNetworkAccessManagerFactory (QDeclarativeNetworkAccessManagerFactory *)
Sets the factory to use for creating QNetworkAccessManager(s).
void setOfflineStoragePath (const QString &dir)
void setOutputWarningsToStandardError (bool)
Set whether warning messages will be output to stderr to enabled.
void setPluginPathList (const QStringList &paths)
Sets the list of directories where the engine searches for native plugins for imported modules (referenced in the qmldir file) to paths.
virtual ~QDeclarativeEngine ()
Destroys the QDeclarativeEngine.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeContext * contextForObject (const QObject *)
Returns the QDeclarativeContext for the object, or 0 if no context has been set.
static ObjectOwnership objectOwnership (QObject *)
Returns the ownership of object.
static void setContextForObject (QObject *, QDeclarativeContext *)
Sets the QDeclarativeContext for the object to context.
static void setObjectOwnership (QObject *, ObjectOwnership)
Sets the ownership of object.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
QString offlineStoragePath
the directory for storing offline user data
Related Functions
(Note that these are not member functions.)
QDeclarativeInfo qmlInfo (const QObject *object)
int qmlRegisterType (const char *url, const char *uri, int versionMajor, int versionMinor, const char *qmlName)
int qmlRegisterUncreatableType (const char *url, const char *uri, int versionMajor, int versionMinor, const char *qmlName)
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Detailed Description
The QDeclarativeEngine class provides an environment for instantiating QML components.
Since
4.7
Each QML component is instantiated in a QDeclarativeContext. QDeclarativeContext's are essential for passing data to QML components. In QML, contexts are arranged hierarchically and this hierarchy is managed by the QDeclarativeEngine.
Prior to creating any QML components, an application must have created a QDeclarativeEngine to gain access to a QML context. The following example shows how to create a simple Text item.
QDeclarativeEngine engine;
QDeclarativeComponent component(&engine);
component.setData("import QtQuick 1.0\nText { text: \"Hello world!\" }", QUrl());
QDeclarativeItem *item = qobject_cast<QDeclarativeItem *>(component.create());
//add item to view, etc
...
In this case, the Text item will be created in the engine's QDeclarativeEngine::rootContext(){root context}.
See also
QDeclarativeComponent QDeclarativeContext
Definition at line 70 of file qdeclarativeengine.h.
Enumerations
ObjectOwnership
enum QDeclarativeEngine::ObjectOwnership
Ownership controls whether or not QML automatically destroys the QObject when the object is garbage collected by the JavaScript engine.
The two ownership options are:
CppOwnership The object is owned by C++ code, and will never be deleted by QML. The JavaScript destroy() method cannot be used on objects with CppOwnership. This option is similar to QScriptEngine::QtOwnership.
JavaScriptOwnership The object is owned by JavaScript. When the object is returned to QML as the return value of a method call or property access, QML will delete the object if there are no remaining JavaScript references to it and it has no QObject::parent(). This option is similar to QScriptEngine::ScriptOwnership.
Generally an application doesn't need to set an object's ownership explicitly. QML uses a heuristic to set the default object ownership. By default, an object that is created by QML has JavaScriptOwnership. The exception to this are the root objects created by calling QDeclarativeCompnent::create() or QDeclarativeComponent::beginCreate() which have CppOwnership by default. The ownership of these root-level objects is considered to have been transferred to the C++ caller.
Objects not-created by QML have CppOwnership by default. The exception to this is objects returned from a C++ method call. The ownership of these objects is passed to JavaScript.
Calling setObjectOwnership() overrides the default ownership heuristic used by QML.
Enumerator
CppOwnership
JavaScriptOwnership
Definition at line 113 of file qdeclarativeengine.h.
 { CppOwnership, JavaScriptOwnership };
Constructors and Destructors
QDeclarativeEngine()
QDeclarativeEngine::QDeclarativeEngine (QObject * p = 0)
Create a new QDeclarativeEngine with the given parent.
Definition at line 654 of file qdeclarativeengine.cpp.
 : QObject(*new QDeclarativeEnginePrivate(this), parent)
 {
     Q_D(QDeclarativeEngine);
     d->init();
 }
~QDeclarativeEngine()
QDeclarativeEngine::~QDeclarativeEngine () virtual
Destroys the QDeclarativeEngine.
Any QDeclarativeContext's created on this engine will be invalidated, but not destroyed (unless they are parented to the QDeclarativeEngine object).
Definition at line 668 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     if (d->isDebugging) {
         QDeclarativeEngineDebugService::instance()->remEngine(this);
         QJSDebugService::instance()->removeEngine(this);
     }
 }
Functions
addImageProvider()
void QDeclarativeEngine::addImageProvider (const QString & providerId, QDeclarativeImageProvider * provider)
Sets the provider to use for images requested via the image: url scheme, with host providerId.
The QDeclarativeEngine takes ownership of provider.
Image providers enable support for pixmap and threaded image requests. See the QDeclarativeImageProvider documentation for details on implementing and using image providers.
All required image providers should be added to the engine before any QML sources files are loaded.
See also
removeImageProvider()
Definition at line 803 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     QMutexLocker locker(&d->mutex);
     d->imageProviders.insert(providerId.toLower(), QSharedPointer<QDeclarativeImageProvider>(provider));
 }
addImportPath()
void QDeclarativeEngine::addImportPath (const QString & path)
Adds path as a directory where the engine searches for installed modules in a URL-based directory structure.
The path may be a local filesystem directory or a URL.
The newly added path will be first in the importPathList().
See also
setImportPathList(), {QML Modules}
Definition at line 2196 of file qdeclarativeengine.cpp.
Referenced by QmlApplicationViewer::addImportPath().
 {
     Q_D(QDeclarativeEngine);
     d->importDatabase.addImportPath(path);
 }
addPluginPath()
void QDeclarativeEngine::addPluginPath (const QString & path)
Adds path as a directory where the engine searches for native plugins for imported modules (referenced in the qmldir file).
By default, the list contains only ., i.e. the engine searches in the directory of the qmldir file itself.
The newly added path will be first in the pluginPathList().
See also
setPluginPathList()
Definition at line 2252 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     d->importDatabase.addPluginPath(path);
 }
baseUrl()
QUrl QDeclarativeEngine::baseUrl () const
Return the base URL for this engine.
The base URL is only used to resolve components when a relative URL is passed to the QDeclarativeComponent constructor.
If a base URL has not been explicitly set, this method returns the application's current working directory.
See also
setBaseUrl()
Definition at line 880 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeContextData::resolvedUrl().
 {
     Q_D(const QDeclarativeEngine);
     if (d->baseUrl.isEmpty()) {
         return QUrl::fromLocalFile(QDir::currentPath() + QDir::separator());
     } else {
         return d->baseUrl;
     }
 }
clearComponentCache()
void QDeclarativeEngine::clearComponentCache ()
Clears the engine's internal component cache.
Normally the QDeclarativeEngine caches components loaded from qml files. This method clears this cache and forces the component to be reloaded.
Definition at line 698 of file qdeclarativeengine.cpp.
Referenced by QmlJSDebugger::AbstractViewInspector::clearComponentCache().
 {
     Q_D(QDeclarativeEngine);
     d->typeLoader.clearCache();
 }
contextForObject()
QDeclarativeContext * QDeclarativeEngine::contextForObject (const QObject * object) static
Returns the QDeclarativeContext for the object, or 0 if no context has been set.
When the QDeclarativeEngine instantiates a QObject, the context is set automatically.
Definition at line 936 of file qdeclarativeengine.cpp.
Referenced by QmlJSDebugger::AbstractViewInspector::createQmlObject(), QDeclarativeListViewPrivate::createSection(), QDeclarativeVisualDataModel::indexOf(), ModelNode::model(), qmlContext(), qmlEngine(), and QDeclarativeVisualItemModel::stringValue().
 {
     if(!object)
         return 0;
     QObjectPrivate *priv = QObjectPrivate::get(const_cast<QObject *>(object));
     QDeclarativeData *data =
         static_cast<QDeclarativeData *>(priv->declarativeData);
     if (!data)
         return 0;
     else if (data->outerContext)
         return data->outerContext->asQDeclarativeContext();
     else
         return 0;
 }
imageProvider()
QDeclarativeImageProvider * QDeclarativeEngine::imageProvider (const QString & id) const
Returns the QDeclarativeImageProvider set for providerId.
Definition at line 813 of file qdeclarativeengine.cpp.
 {
     Q_D(const QDeclarativeEngine);
     QMutexLocker locker(&d->mutex);
     return d->imageProviders.value(providerId).data();
 }
importPathList()
QStringList QDeclarativeEngine::importPathList () const
Returns the list of directories where the engine searches for installed modules in a URL-based directory structure.
For example, if /opt/MyApp/lib/imports is in the path, then QML that imports com.mycompany.Feature will cause the QDeclarativeEngine to look in /opt/MyApp/lib/imports/com/mycompany/Feature/ for the components provided by that module. A qmldir file is required for defining the type version mapping and possibly declarative extensions plugins.
By default, the list contains the directory of the application executable, paths specified in the QML_IMPORT_PATH environment variable, and the builtin ImportsPath from QLibraryInfo.
See also
addImportPath() setImportPathList()
Definition at line 2218 of file qdeclarativeengine.cpp.
 {
     Q_D(const QDeclarativeEngine);
     return d->importDatabase.importPathList();
 }
importPlugin()
bool QDeclarativeEngine::importPlugin (const QString & filePath, const QString & uri, QString * errorString)
Imports the plugin named filePath with the uri provided.
Returns true if the plugin was successfully imported; otherwise returns false.
On failure and if non-null, *errorString will be set to a message describing the failure.
The plugin has to be a Qt plugin which implements the QDeclarativeExtensionPlugin interface.
Definition at line 2299 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     return d->importDatabase.importPlugin(filePath, uri, errorString);
 }
networkAccessManager()
QNetworkAccessManager * QDeclarativeEngine::networkAccessManager () const
Returns a common QNetworkAccessManager which can be used by any QML element instantiated by this engine.
If a QDeclarativeNetworkAccessManagerFactory has been set and a QNetworkAccessManager has not yet been created, the QDeclarativeNetworkAccessManagerFactory will be used to create the QNetworkAccessManager; otherwise the returned QNetworkAccessManager will have no proxy or cache set.
See also
setNetworkAccessManagerFactory()
Definition at line 782 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate::getNetworkAccessManager(), QDeclarativeBorderImage::load(), QDeclarativeAnimatedImage::load(), QDeclarativeDataLoader::load(), QDeclarativeDataLoader::networkReplyFinished(), and QDeclarativeXmlListModel::reload().
 {
     Q_D(const QDeclarativeEngine);
     return d->getNetworkAccessManager();
 }
networkAccessManagerFactory()
QDeclarativeNetworkAccessManagerFactory * QDeclarativeEngine::networkAccessManagerFactory () const
Returns the current QDeclarativeNetworkAccessManagerFactory.
See also
setNetworkAccessManagerFactory()
Definition at line 743 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate::createNetworkAccessManager(), and QDeclarativeWorkerScriptEnginePrivate::ScriptEngine::networkAccessManager().
 {
     Q_D(const QDeclarativeEngine);
     return d->networkAccessManagerFactory;
 }
objectOwnership()
QDeclarativeEngine::ObjectOwnership QDeclarativeEngine::objectOwnership (QObject * object) static
Returns the ownership of object.
Definition at line 1035 of file qdeclarativeengine.cpp.
 {
     if (!object)
         return CppOwnership;
     QDeclarativeData *ddata = QDeclarativeData::get(object, false);
     if (!ddata)
         return CppOwnership;
     else
         return ddata->indestructible?CppOwnership:JavaScriptOwnership;
 }
offlineStoragePath()
QString QDeclarativeEngine::offlineStoragePath () const
Referenced by setOfflineStoragePath().
outputWarningsToStandardError()
bool QDeclarativeEngine::outputWarningsToStandardError () const
Returns true if warning messages will be output to stderr in addition to being emitted by the warnings() signal, otherwise false.
The default value is true.
Definition at line 907 of file qdeclarativeengine.cpp.
 {
     Q_D(const QDeclarativeEngine);
     return d->outputWarningsToStdErr;
 }
pluginPathList()
QStringList QDeclarativeEngine::pluginPathList () const
Returns the list of directories where the engine searches for native plugins for imported modules (referenced in the qmldir file).
By default, the list contains only ., i.e. the engine searches in the directory of the qmldir file itself.
See also
addPluginPath() setPluginPathList()
Definition at line 2268 of file qdeclarativeengine.cpp.
 {
     Q_D(const QDeclarativeEngine);
     return d->importDatabase.pluginPathList();
 }
quit
void QDeclarativeEngine::quit () signal
This signal is emitted when the QML loaded by the engine would like to quit.
Referenced by QDeclarativeEnginePrivate::sendQuit().
removeImageProvider()
void QDeclarativeEngine::removeImageProvider (const QString & providerId)
Removes the QDeclarativeImageProvider for providerId.
Returns the provider if it was found; otherwise returns 0.
See also
addImageProvider()
Definition at line 827 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     QMutexLocker locker(&d->mutex);
     d->imageProviders.take(providerId);
 }
rootContext()
QDeclarativeContext * QDeclarativeEngine::rootContext () const
Returns the engine's root context.
The root context is automatically created by the QDeclarativeEngine. Data that should be available to all QML component instances instantiated by the engine should be put in the root context.
Additional data that should only be available to a subset of component instances should be added to sub-contexts parented to the root context.
Definition at line 715 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEngineDebugService::messageReceived(), and QDeclarativeContext::QDeclarativeContext().
 {
     Q_D(const QDeclarativeEngine);
     return d->rootContext;
 }
setBaseUrl()
void QDeclarativeEngine::setBaseUrl (const QUrl & url)
Set the base URL for this engine to url.
See also
baseUrl()
Definition at line 895 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     d->baseUrl = url;
 }
setContextForObject()
void QDeclarativeEngine::setContextForObject (QObject * object, QDeclarativeContext * context) static
Sets the QDeclarativeContext for the object to context.
If the object already has a context, a warning is output, but the context is not changed.
When the QDeclarativeEngine instantiates a QObject, the context is set automatically.
Definition at line 962 of file qdeclarativeengine.cpp.
Referenced by ModelNode::model().
 {
     if (!object || !context)
         return;
     QDeclarativeData *data = QDeclarativeData::get(object, true);
     if (data->context) {
         qWarning("QDeclarativeEngine::setContextForObject(): Object already has a QDeclarativeContext");
         return;
     }
     QDeclarativeContextData *contextData = QDeclarativeContextData::get(context);
     contextData->addObject(object);
 }
setImportPathList()
void QDeclarativeEngine::setImportPathList (const QStringList & paths)
Sets paths as the list of directories where the engine searches for installed modules in a URL-based directory structure.
By default, the list contains the directory of the application executable, paths specified in the QML_IMPORT_PATH environment variable, and the builtin ImportsPath from QLibraryInfo.
See also
importPathList() addImportPath()
Definition at line 2234 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     d->importDatabase.setImportPathList(paths);
 }
setNetworkAccessManagerFactory()
void QDeclarativeEngine::setNetworkAccessManagerFactory (QDeclarativeNetworkAccessManagerFactory * factory)
Sets the factory to use for creating QNetworkAccessManager(s).
QNetworkAccessManager is used for all network access by QML. By implementing a factory it is possible to create custom QNetworkAccessManager with specialized caching, proxy and cookie support.
The factory must be set before executing the engine.
Definition at line 731 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     QMutexLocker locker(&d->mutex);
     d->networkAccessManagerFactory = factory;
 }
setObjectOwnership()
void QDeclarativeEngine::setObjectOwnership (QObject * object, ObjectOwnership ownership) static
Sets the ownership of object.
Definition at line 1019 of file qdeclarativeengine.cpp.
 {
     if (!object)
         return;
     QDeclarativeData *ddata = QDeclarativeData::get(object, true);
     if (!ddata)
         return;
     ddata->indestructible = (ownership == CppOwnership)?true:false;
     ddata->explicitIndestructibleSet = true;
 }
setOfflineStoragePath()
void QDeclarativeEngine::setOfflineStoragePath (const QString & dir)
Definition at line 2325 of file qdeclarativeengine.cpp.
Referenced by main().
 {
     Q_D(QDeclarativeEngine);
     d->scriptEngine.offlineStoragePath = dir;
 }
setOutputWarningsToStandardError()
void QDeclarativeEngine::setOutputWarningsToStandardError (bool enabled)
Set whether warning messages will be output to stderr to enabled.
If enabled is true, any warning messages generated by QML will be output to stderr and emitted by the warnings() signal. If enabled is false, on the warnings() signal will be emitted. This allows applications to handle warning output themselves.
The default value is true.
Definition at line 923 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     d->outputWarningsToStdErr = enabled;
 }
setPluginPathList()
void QDeclarativeEngine::setPluginPathList (const QStringList & paths)
Sets the list of directories where the engine searches for native plugins for imported modules (referenced in the qmldir file) to paths.
By default, the list contains only ., i.e. the engine searches in the directory of the qmldir file itself.
See also
pluginPathList() addPluginPath()
Definition at line 2284 of file qdeclarativeengine.cpp.
 {
     Q_D(QDeclarativeEngine);
     d->importDatabase.setPluginPathList(paths);
 }
warnings
void QDeclarativeEngine::warnings (const QList< QDeclarativeError > & warnings) signal
This signal is emitted when warnings messages are generated by QML.
Friends and Related Functions
qmlInfo()
QDeclarativeInfo qmlInfo (const QObject * object) related
Prints warning messages that include the file and line number for the specified QML object.
When QML types display warning messages, it improves traceability if they include the QML file and line number on which the particular instance was instantiated.
To include the file and line number, an object must be passed. If the file and line number is not available for that instance (either it was not instantiated by the QML engine or location information is disabled), "unknown location" will be used instead.
For example,
qmlInfo(object) << tr("component property is a write-once property");
prints
QML MyCustomType (unknown location): component property is a write-once property
Definition at line 155 of file qdeclarativeinfo.cpp.
 {
     QDeclarativeInfoPrivate *d = new QDeclarativeInfoPrivate;
     d->object = me;
     return QDeclarativeInfo(d);
 }
qmlRegisterType()
int qmlRegisterType (const char * url, const char * uri, int versionMajor, int versionMinor, const char * qmlName) related
Warning
This function is not part of the public interface.
This function registers a type in the QML system with the name qmlName, in the library imported from uri having the version number composed from versionMajor and versionMinor. The type is defined by the QML file located at url.
Normally QML files can be loaded as types directly from other QML files, or using a qmldir file. This function allows registration of files to types from a C++ module, such as when the type mapping needs to be procedurally determined at startup.
Returns non-zero if the registration was sucessful.
This function is added to QtQuick 1 in Qt 5, and is here as private API for developers needing compatibility.
qmlRegisterUncreatableType()
int qmlRegisterUncreatableType (const char * url, const char * uri, int versionMajor, int versionMinor, const char * qmlName) related
Warning
This function is not part of the public interface.
This overload is backported from Qt5, and allows uncreatable types to be versioned.
Properties
offlineStoragePath
QString QDeclarativeEngine::offlineStoragePath private
the directory for storing offline user data
Returns the directory where SQL and other offline storage is placed.
QDeclarativeWebView and the SQL databases created with openDatabase() are stored here.
The default is QML/OfflineStorage in the platform-standard user application data directory.
Note that the path may not currently exist on the filesystem, so callers wanting to create new files at this location should create it first - see QDir::mkpath().
Definition at line 72 of file qdeclarativeengine.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeengine.h
/src/declarative/qml/qdeclarativeengine.cpp
/src/declarative/qml/qdeclarativeinfo.cpp
/src/declarative/qml/qdeclarativeprivate.h