Qt 4.8: QPatternist::PullBridge Class Reference
QPatternist::PullBridge Class Reference
Bridges a QPatternist::SequenceIterator to QAbstractXmlPullProvider.
#include <qpullbridge_p.h>
Public Functions
virtual QVariant atomicValue () const
virtual QHash< QXmlName, QXmlItem > attributeItems ()
virtual QHash< QXmlName, QString > attributes ()
If the current() is Element, the attributes of the element are returned, an empty list of attributes otherwise.
virtual Event current () const
Returns the event that next() returned the last time it was called.
QXmlNodeModelIndex index () const
virtual QXmlName name () const
If the current event is StartElement, EndElement, ProcessingInstruction, Attribute, or Namespace, the node's name is returned.
virtual Event next ()
Advances this AbstractXmlPullProvider, and returns the new event.
PullBridge (const QXmlNodeModelIndex::Iterator::Ptr &it)
QSourceLocation sourceLocation () const
virtual QString stringValue () const
If current() is Text, the text node's value is returned.
Public Functions inherited from QPatternist::AbstractXmlPullProvider
AbstractXmlPullProvider ()
Constucts a AbstractXmlPullProvider instance.
virtual ~AbstractXmlPullProvider ()
Destructs this AbstractXmlPullProvider.
Private Types
typedef QStack< QPair< Event, QXmlNodeModelIndex::Iterator::Ptr > > IteratorStack
Properties
Event m_current
QXmlNodeModelIndex m_index
IteratorStack m_iterators
Additional Inherited Members
Public Types inherited from QPatternist::AbstractXmlPullProvider
enum Event {
StartOfInput = 1, AtomicValue = 1 << 1, StartDocument = 1 << 2, EndDocument = 1 << 3,
StartElement = 1 << 4, EndElement = 1 << 5, Text = 1 << 6, ProcessingInstruction = 1 << 7,
Comment = 1 << 8, Attribute = 1 << 9, Namespace = 1 << 10, EndOfInput = 1 << 11
}
Detailed Description
Bridges a QPatternist::SequenceIterator to QAbstractXmlPullProvider.
Warning
This function is not part of the public interface.
Note
This class or function is reentrant.
The approach of this class is rather straight forward since QPatternist::SequenceIterator and QAbstractXmlPullProvider are conceptually similar. While QPatternist::SequenceIterator only delivers top level items(since it's not an event stream, it's a list of items), PullBridge needs to recursively iterate the children of nodes too, which is achieved through the stack m_iterators.
Definition at line 68 of file qpullbridge_p.h.
Typedefs
IteratorStack
typedef QStack<QPair<Event, QXmlNodeModelIndex::Iterator::Ptr> > QPatternist::PullBridge::IteratorStack private
Definition at line 92 of file qpullbridge_p.h.
Constructors and Destructors
PullBridge()
QPatternist::PullBridge::PullBridge (const QXmlNodeModelIndex::Iterator::Ptr & it) inline
Definition at line 71 of file qpullbridge_p.h.
                                                                    : m_current(StartOfInput)
         {
             Q_ASSERT(it);
             m_iterators.push(qMakePair(StartOfInput, it));
         }
Functions
atomicValue()
QVariant PullBridge::atomicValue () const virtual
Returns always an empty QVariant.
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 188 of file qpullbridge.cpp.
Referenced by PullBridge().
 {
     return QVariant();
 }
attributeItems()
QHash< QXmlName, QXmlItem > PullBridge::attributeItems () virtual
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 216 of file qpullbridge.cpp.
Referenced by PullBridge(), and QPatternist::XsdInstanceReader::readNext().
 {
     Q_ASSERT(m_current == StartElement);
     QHash<QXmlName, QXmlItem> attributes;
     QXmlNodeModelIndex::Iterator::Ptr it = m_index.iterate(QXmlNodeModelIndex::AxisAttribute);
     QXmlNodeModelIndex index = it->next();
     while (!index.isNull()) {
         const Item attribute(index);
         attributes.insert(index.name(), QXmlItem(index));
         index = it->next();
     }
     return attributes;
 }
attributes()
QHash< QXmlName, QString > PullBridge::attributes () virtual
If the current() is Element, the attributes of the element are returned, an empty list of attributes otherwise.
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 198 of file qpullbridge.cpp.
Referenced by attributeItems(), PullBridge(), and QPatternist::XsdInstanceReader::readNext().
 {
     Q_ASSERT(m_current == StartElement);
     QHash<QXmlName, QString> attributes;
     QXmlNodeModelIndex::Iterator::Ptr it = m_index.iterate(QXmlNodeModelIndex::AxisAttribute);
     QXmlNodeModelIndex index = it->next();
     while (!index.isNull()) {
         const Item attribute(index);
         attributes.insert(index.name(), index.stringValue());
         index = it->next();
     }
     return attributes;
 }
current()
AbstractXmlPullProvider::Event PullBridge::current () const virtual
Returns the event that next() returned the last time it was called.
It doesn't alter this AbstractXmlPullProvider.
current() may not modify this AbstractXmlPullProvider's state. Subsequent calls to current() must return the same value.
See also
AbstractXmlPullProvider::Event
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 168 of file qpullbridge.cpp.
Referenced by QPatternist::XsdInstanceReader::atEnd(), QPatternist::XsdInstanceReader::isEndElement(), QPatternist::XsdInstanceReader::isStartElement(), PullBridge(), and QPatternist::XsdInstanceReader::readNext().
 {
     return m_current;
 }
index()
QXmlNodeModelIndex PullBridge::index () const
Definition at line 173 of file qpullbridge.cpp.
Referenced by attributeItems(), attributes(), QPatternist::XsdInstanceReader::hasChildElement(), QPatternist::XsdInstanceReader::hasChildText(), PullBridge(), QPatternist::XsdInstanceReader::readNext(), and QPatternist::XsdInstanceReader::text().
 {
     return m_index;
 }
name()
QXmlName PullBridge::name () const virtual
If the current event is StartElement, EndElement, ProcessingInstruction, Attribute, or Namespace, the node's name is returned.
If the current event is ProcessingInstruction, the processing instruction target is in in the local name.
If the current event is Namespace, the name's namespace URI is the namespace, and the local name is the prefix the name is binding to.
In all other cases, an invalid QName is returned.
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 183 of file qpullbridge.cpp.
Referenced by QPatternist::XsdInstanceReader::name(), and PullBridge().
 {
     return m_index.name();
 }
next()
AbstractXmlPullProvider::Event PullBridge::next () virtual
Advances this AbstractXmlPullProvider, and returns the new event.
See also
current()
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 73 of file qpullbridge.cpp.
Referenced by PullBridge(), and QPatternist::XsdInstanceReader::readNext().
 {
     m_index = m_iterators.top().second->next();
     if(!m_index.isNull())
     {
         Item item(m_index);
         if(item && item.isAtomicValue())
             m_current = AtomicValue;
         else
         {
             Q_ASSERT(item.isNode());
             switch(m_index.kind())
             {
                 case QXmlNodeModelIndex::Attribute:
                 {
                     m_current = Attribute;
                     break;
                 }
                 case QXmlNodeModelIndex::Comment:
                 {
                     m_current = Comment;
                     break;
                 }
                 case QXmlNodeModelIndex::Element:
                 {
                     m_iterators.push(qMakePair(StartElement, m_index.iterate(QXmlNodeModelIndex::AxisChild)));
                     m_current = StartElement;
                     break;
                 }
                 case QXmlNodeModelIndex::Document:
                 {
                     m_iterators.push(qMakePair(StartDocument, m_index.iterate(QXmlNodeModelIndex::AxisChild)));
                     m_current = StartDocument;
                     break;
                 }
                 case QXmlNodeModelIndex::Namespace:
                 {
                     m_current = Namespace;
                     break;
                 }
                 case QXmlNodeModelIndex::ProcessingInstruction:
                 {
                     m_current = ProcessingInstruction;
                     break;
                 }
                 case QXmlNodeModelIndex::Text:
                 {
                     m_current = Text;
                     break;
                 }
             }
         }
     }
     else
     {
         if(m_iterators.isEmpty())
             m_current = EndOfInput;
         else
         {
             switch(m_iterators.top().first)
             {
                 case StartOfInput:
                 {
                     m_current = EndOfInput;
                     break;
                 }
                 case StartElement:
                 {
                     m_current = EndElement;
                     m_iterators.pop();
                     break;
                 }
                 case StartDocument:
                 {
                     m_current = EndDocument;
                     m_iterators.pop();
                     break;
                 }
                 default:
                 {
                     Q_ASSERT_X(false, Q_FUNC_INFO,
                                "Invalid value.");
                     m_current = EndOfInput;
                 }
             }
         }
     }
     return m_current;
 }
sourceLocation()
QSourceLocation PullBridge::sourceLocation () const
Definition at line 178 of file qpullbridge.cpp.
Referenced by PullBridge(), and QPatternist::XsdInstanceReader::readNext().
 {
     return m_index.model()->sourceLocation(m_index);
 }
stringValue()
QString PullBridge::stringValue () const virtual
If current() is Text, the text node's value is returned.
If the current() event is Comment, its value is returned. The subclasser guarantees it does not contain the string "-->".
If the current() event is ProcessingInstruction, its data is returned. The subclasser guarantees the data does not contain the string "?>".
In other cases, it returns a default constructed string.
Implements QPatternist::AbstractXmlPullProvider.
Definition at line 193 of file qpullbridge.cpp.
Referenced by PullBridge().
 {
     return QString();
 }
Properties
m_current
Event QPatternist::PullBridge::m_current private
Definition at line 95 of file qpullbridge_p.h.
Referenced by attributeItems(), attributes(), current(), and next().
m_index
QXmlNodeModelIndex QPatternist::PullBridge::m_index private
Definition at line 94 of file qpullbridge_p.h.
Referenced by attributeItems(), attributes(), index(), name(), next(), and sourceLocation().
m_iterators
IteratorStack QPatternist::PullBridge::m_iterators private
Definition at line 93 of file qpullbridge_p.h.
Referenced by next(), and PullBridge().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qpullbridge_p.h
/src/xmlpatterns/api/qpullbridge.cpp