Qt 4.8: QPacketProtocolPrivate Class Reference
QPacketProtocolPrivate Class Reference
Public Slots
void aboutToClose ()
void bytesWritten (qint64 bytes)
void readyToRead ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void invalidPacket ()
void packetWritten ()
void readyRead ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QPacketProtocolPrivate (QPacketProtocol *parent, QIODevice *_dev)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QIODevice * dev
QByteArray inProgress
qint32 inProgressSize
qint32 maxPacketSize
QList< QByteArray > packets
QList< qint64 > sendingPackets
bool waitingForPacket
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 115 of file qpacketprotocol.cpp.
Constructors and Destructors
QPacketProtocolPrivate()
QPacketProtocolPrivate::QPacketProtocolPrivate (QPacketProtocol * parent, QIODevice * _dev) inline
Definition at line 119 of file qpacketprotocol.cpp.
     : QObject(parent), inProgressSize(-1), maxPacketSize(MAX_PACKET_SIZE),
       waitingForPacket(false), dev(_dev)
     {
         Q_ASSERT(4 == sizeof(qint32));
         QObject::connect(this, SIGNAL(readyRead()),
                          parent, SIGNAL(readyRead()));
         QObject::connect(this, SIGNAL(packetWritten()),
                          parent, SIGNAL(packetWritten()));
         QObject::connect(this, SIGNAL(invalidPacket()),
                          parent, SIGNAL(invalidPacket()));
         QObject::connect(dev, SIGNAL(readyRead()),
                          this, SLOT(readyToRead()));
         QObject::connect(dev, SIGNAL(aboutToClose()),
                          this, SLOT(aboutToClose()));
         QObject::connect(dev, SIGNAL(bytesWritten(qint64)),
                          this, SLOT(bytesWritten(qint64)));
     }
Functions
aboutToClose
void QPacketProtocolPrivate::aboutToClose () inline slot
Definition at line 145 of file qpacketprotocol.cpp.
Referenced by QPacketProtocolPrivate(), and readyToRead().
     {
         inProgress.clear();
         sendingPackets.clear();
         inProgressSize = -1;
     }
bytesWritten
void QPacketProtocolPrivate::bytesWritten (qint64 bytes) inline slot
Definition at line 152 of file qpacketprotocol.cpp.
Referenced by QPacketProtocolPrivate(), and readyToRead().
     {
         Q_ASSERT(!sendingPackets.isEmpty());
         while(bytes) {
             if(sendingPackets.at(0) > bytes) {
                 sendingPackets[0] -= bytes;
                 bytes = 0;
             } else {
                 bytes -= sendingPackets.at(0);
                 sendingPackets.removeFirst();
                 emit packetWritten();
             }
         }
     }
invalidPacket
void QPacketProtocolPrivate::invalidPacket () signal
Referenced by QPacketProtocolPrivate(), and readyToRead().
packetWritten
void QPacketProtocolPrivate::packetWritten () signal
Referenced by bytesWritten(), and QPacketProtocolPrivate().
readyRead
void QPacketProtocolPrivate::readyRead () signal
Referenced by QPacketProtocolPrivate(), and readyToRead().
readyToRead
void QPacketProtocolPrivate::readyToRead () inline slot
Definition at line 168 of file qpacketprotocol.cpp.
Referenced by QPacketProtocolPrivate().
     {
         bool gotPackets = false;
         while (true) {
             // Get size header (if not in progress)
             if (-1 == inProgressSize) {
                 // We need a size header of sizeof(qint32)
                 if (sizeof(qint32) > (uint)dev->bytesAvailable()) {
                     if (gotPackets)
                         emit readyRead();
                     return; // no more data available
                 }
                 // Read size header
                 int read = dev->read((char *)&inProgressSize, sizeof(qint32));
                 Q_ASSERT(read == sizeof(qint32));
                 Q_UNUSED(read);
                 // Check sizing constraints
                 if (inProgressSize > maxPacketSize) {
                     QObject::disconnect(dev, SIGNAL(readyRead()),
                                         this, SLOT(readyToRead()));
                     QObject::disconnect(dev, SIGNAL(aboutToClose()),
                                         this, SLOT(aboutToClose()));
                     QObject::disconnect(dev, SIGNAL(bytesWritten(qint64)),
                                         this, SLOT(bytesWritten(qint64)));
                     dev = 0;
                     emit invalidPacket();
                     return;
                 }
                 inProgressSize -= sizeof(qint32);
             } else {
                 inProgress.append(dev->read(inProgressSize - inProgress.size()));
                 if (inProgressSize == inProgress.size()) {
                     // Packet has arrived!
                     packets.append(inProgress);
                     inProgressSize = -1;
                     inProgress.clear();
                     waitingForPacket = false;
                     gotPackets = true;
                 } else {
                     if (gotPackets)
                         emit readyRead();
                     return; // packet in progress is not yet complete
                 }
             }
         }
     }
Properties
dev
QIODevice* QPacketProtocolPrivate::dev
Definition at line 227 of file qpacketprotocol.cpp.
Referenced by QPacketProtocol::device(), QPacketProtocolPrivate(), readyToRead(), QPacketProtocol::send(), and QPacketProtocol::waitForReadyRead().
inProgress
QByteArray QPacketProtocolPrivate::inProgress
Definition at line 223 of file qpacketprotocol.cpp.
Referenced by aboutToClose(), and readyToRead().
inProgressSize
qint32 QPacketProtocolPrivate::inProgressSize
Definition at line 224 of file qpacketprotocol.cpp.
Referenced by aboutToClose(), and readyToRead().
maxPacketSize
qint32 QPacketProtocolPrivate::maxPacketSize
Definition at line 225 of file qpacketprotocol.cpp.
Referenced by QPacketProtocol::maximumPacketSize(), readyToRead(), and QPacketProtocol::setMaximumPacketSize().
packets
QList<QByteArray> QPacketProtocolPrivate::packets
Definition at line 222 of file qpacketprotocol.cpp.
Referenced by QPacketProtocol::clear(), QPacketProtocol::packetsAvailable(), QPacketProtocol::read(), readyToRead(), and QPacketProtocol::waitForReadyRead().
sendingPackets
QList<qint64> QPacketProtocolPrivate::sendingPackets
Definition at line 221 of file qpacketprotocol.cpp.
Referenced by aboutToClose(), bytesWritten(), and QPacketProtocol::send().
waitingForPacket
bool QPacketProtocolPrivate::waitingForPacket
Definition at line 226 of file qpacketprotocol.cpp.
Referenced by readyToRead(), and QPacketProtocol::waitForReadyRead().
The documentation for this class was generated from the following file:
/src/declarative/debugger/qpacketprotocol.cpp