Qt 4.8: QDomNode Class Reference
QDomNode Class Reference
The QDomNode class is the base class for all the nodes in a DOM tree.
#include <qdom.h>
Public Types
enum EncodingPolicy { EncodingFromDocument = 1, EncodingFromTextStream = 2 }
This enum specifies how QDomNode::save() determines what encoding to use when serializing.
enum NodeType {
ElementNode = 1, AttributeNode = 2, TextNode = 3, CDATASectionNode = 4,
EntityReferenceNode = 5, EntityNode = 6, ProcessingInstructionNode = 7, CommentNode = 8,
DocumentNode = 9, DocumentTypeNode = 10, DocumentFragmentNode = 11, NotationNode = 12,
BaseNode = 21, CharacterDataNode = 22
}
This enum defines the type of the node:
Public Functions
QDomNode appendChild (const QDomNode &newChild)
Appends newChild as the node's last child.
QDomNamedNodeMap attributes () const
Returns a named node map of all attributes.
QDomNodeList childNodes () const
Returns a list of all direct child nodes.
void clear ()
Converts the node into a null node; if it was not a null node before, its type and contents are deleted.
QDomNode cloneNode (bool deep=true) const
Creates a deep (not shallow) copy of the QDomNode.
int columnNumber () const
For nodes created by QDomDocument::setContent(), this function returns the column number in the XML document where the node was parsed.
QDomNode firstChild () const
Returns the first child of the node.
QDomElement firstChildElement (const QString &tagName=QString()) const
Returns the first child element with tag name tagName if tagName is non-empty; otherwise returns the first child element.
bool hasAttributes () const
Returns true if the node has attributes; otherwise returns false.
bool hasChildNodes () const
Returns true if the node has one or more children; otherwise returns false.
QDomNode insertAfter (const QDomNode &newChild, const QDomNode &refChild)
Inserts the node newChild after the child node refChild.
QDomNode insertBefore (const QDomNode &newChild, const QDomNode &refChild)
Inserts the node newChild before the child node refChild.
bool isAttr () const
Returns true if the node is an attribute; otherwise returns false.
bool isCDATASection () const
Returns true if the node is a CDATA section; otherwise returns false.
bool isCharacterData () const
Returns true if the node is a character data node; otherwise returns false.
bool isComment () const
Returns true if the node is a comment; otherwise returns false.
bool isDocument () const
Returns true if the node is a document; otherwise returns false.
bool isDocumentFragment () const
Returns true if the node is a document fragment; otherwise returns false.
bool isDocumentType () const
Returns true if the node is a document type; otherwise returns false.
bool isElement () const
Returns true if the node is an element; otherwise returns false.
bool isEntity () const
Returns true if the node is an entity; otherwise returns false.
bool isEntityReference () const
Returns true if the node is an entity reference; otherwise returns false.
bool isNotation () const
Returns true if the node is a notation; otherwise returns false.
bool isNull () const
Returns true if this node is null (i.e.
bool isProcessingInstruction () const
Returns true if the node is a processing instruction; otherwise returns false.
bool isSupported (const QString &feature, const QString &version) const
Returns true if the DOM implementation implements the feature feature and this feature is supported by this node in the version version; otherwise returns false.
bool isText () const
Returns true if the node is a text node; otherwise returns false.
QDomNode lastChild () const
Returns the last child of the node.
QDomElement lastChildElement (const QString &tagName=QString()) const
Returns the last child element with tag name tagName if tagName is non-empty; otherwise returns the last child element.
int lineNumber () const
For nodes created by QDomDocument::setContent(), this function returns the line number in the XML document where the node was parsed.
QString localName () const
If the node uses namespaces, this function returns the local name of the node; otherwise it returns an empty string.
QDomNode namedItem (const QString &name) const
Returns the first direct child node for which nodeName() equals name.
QString namespaceURI () const
Returns the namespace URI of this node or an empty string if the node has no namespace URI.
QDomNode nextSibling () const
Returns the next sibling in the document tree.
QDomElement nextSiblingElement (const QString &taName=QString()) const
Returns the next sibling element with tag name tagName if tagName is non-empty; otherwise returns any next sibling element.
QString nodeName () const
Returns the name of the node.
NodeType nodeType () const
Returns the type of the node.
QString nodeValue () const
Returns the value of the node.
void normalize ()
Calling normalize() on an element converts all its children into a standard form.
bool operator!= (const QDomNode &) const
Returns true if n and this DOM node are not equal; otherwise returns false.
QDomNode & operator= (const QDomNode &)
Assigns a copy of n to this DOM node.
bool operator== (const QDomNode &) const
Returns true if n and this DOM node are equal; otherwise returns false.
QDomDocument ownerDocument () const
Returns the document to which this node belongs.
QDomNode parentNode () const
Returns the parent node.
QString prefix () const
Returns the namespace prefix of the node or an empty string if the node has no namespace prefix.
QDomNode previousSibling () const
Returns the previous sibling in the document tree.
QDomElement previousSiblingElement (const QString &tagName=QString()) const
Returns the previous sibilng element with tag name tagName if tagName is non-empty; otherwise returns any previous sibling element.
QDomNode ()
Constructs a null node.
QDomNode (const QDomNode &)
Constructs a copy of n.
QDomNode removeChild (const QDomNode &oldChild)
Removes oldChild from the list of children.
QDomNode replaceChild (const QDomNode &newChild, const QDomNode &oldChild)
Replaces oldChild with newChild.
void save (QTextStream &, int) const
Writes the XML representation of the node and all its children to the stream str.
void save (QTextStream &, int, EncodingPolicy) const
If encodingPolicy is QDomNode::EncodingFromDocument, this function behaves as save(QTextStream &str, int indent).
void setNodeValue (const QString &)
Sets the node's value to v.
void setPrefix (const QString &pre)
If the node has a namespace prefix, this function changes the namespace prefix of the node to pre.
QDomAttr toAttr () const
Converts a QDomNode into a QDomAttr.
QDomCDATASection toCDATASection () const
Converts a QDomNode into a QDomCDATASection.
QDomCharacterData toCharacterData () const
Converts a QDomNode into a QDomCharacterData.
QDomComment toComment () const
Converts a QDomNode into a QDomComment.
QDomDocument toDocument () const
Converts a QDomNode into a QDomDocument.
QDomDocumentFragment toDocumentFragment () const
Converts a QDomNode into a QDomDocumentFragment.
QDomDocumentType toDocumentType () const
Converts a QDomNode into a QDomDocumentType.
QDomElement toElement () const
Converts a QDomNode into a QDomElement.
QDomEntity toEntity () const
Converts a QDomNode into a QDomEntity.
QDomEntityReference toEntityReference () const
Converts a QDomNode into a QDomEntityReference.
QDomNotation toNotation () const
Converts a QDomNode into a QDomNotation.
QDomProcessingInstruction toProcessingInstruction () const
Converts a QDomNode into a QDomProcessingInstruction.
QDomText toText () const
Converts a QDomNode into a QDomText.
~QDomNode ()
Destroys the object and frees its resources.
Protected Functions
QDomNode (QDomNodePrivate *)
Constructs a new node for the data n.
Protected Variables
QDomNodePrivate * impl
Friends
class QDomDocument
class QDomDocumentType
class QDomNamedNodeMap
class QDomNodeList
Related Functions
(Note that these are not member functions.)
QTextStream & operator<< (QTextStream &str, const QDomNode &node)
Writes the XML representation of the node node and all its children to the stream str.
Detailed Description
The QDomNode class is the base class for all the nodes in a DOM tree.
Note
This class or function is reentrant.
Attention
Module: QtXml
Many functions in the DOM return a QDomNode.
You can find out the type of a node using isAttr(), isCDATASection(), isDocumentFragment(), isDocument(), isDocumentType(), isElement(), isEntityReference(), isText(), isEntity(), isNotation(), isProcessingInstruction(), isCharacterData() and isComment().
A QDomNode can be converted into one of its subclasses using toAttr(), toCDATASection(), toDocumentFragment(), toDocument(), toDocumentType(), toElement(), toEntityReference(), toText(), toEntity(), toNotation(), toProcessingInstruction(), toCharacterData() or toComment(). You can convert a node to a null node with clear().
Copies of the QDomNode class share their data using explicit sharing. This means that modifying one node will change all copies. This is especially useful in combination with functions which return a QDomNode, e.g. firstChild(). You can make an independent (deep) copy of the node with cloneNode().
A QDomNode can be null, much like a null pointer. Creating a copy of a null node results in another null node. It is not possible to modify a null node, but it is possible to assign another, possibly non-null node to it. In this case, the copy of the null node will remain null. You can check if a QDomNode is null by calling isNull(). The empty constructor of a QDomNode (or any of the derived classes) creates a null node.
Nodes are inserted with insertBefore(), insertAfter() or appendChild(). You can replace one node with another using replaceChild() and remove a node with removeChild().
To traverse nodes use firstChild() to get a node's first child (if any), and nextSibling() to traverse. QDomNode also provides lastChild(), previousSibling() and parentNode(). To find the first child node with a particular node name use namedItem().
To find out if a node has children use hasChildNodes() and to get a list of all of a node's children use childNodes().
The node's name and value (the meaning of which varies depending on its type) is returned by nodeName() and nodeValue() respectively. The node's type is returned by nodeType(). The node's value can be set with setNodeValue().
The document to which the node belongs is returned by ownerDocument().
Adjacent QDomText nodes can be merged into a single node with normalize().
QDomElement nodes have attributes which can be retrieved with attributes().
QDomElement and QDomAttr nodes can have namespaces which can be retrieved with namespaceURI(). Their local name is retrieved with localName(), and their prefix with prefix(). The prefix can be set with setPrefix().
You can write the XML representation of the node to a text stream with save().
The following example looks for the first element in an XML document and prints the names of all the elements that are its direct children.
QDomDocument d;
d.setContent(someXML);
QDomNode n = d.firstChild();
while (!n.isNull()) {
    if (n.isElement()) {
        QDomElement e = n.toElement();
        cout << "Element name: " << e.tagName() << endl;
        break;
    }
    n = n.nextSibling();
}
For further information about the Document Object Model see Level 1 and Level 2 Core. For a more general introduction of the DOM implementation see the QDomDocument documentation.
Definition at line 128 of file qdom.h.
Enumerations
EncodingPolicy
enum QDomNode::EncodingPolicy
This enum specifies how QDomNode::save() determines what encoding to use when serializing.
Since
4.3
EncodingFromDocument The encoding is fetched from the document.
EncodingFromTextStream The encoding is fetched from the QTextStream.
See also the overload of the save() function that takes an EncodingPolicy.
Enumerator
EncodingFromDocument
EncodingFromTextStream
Definition at line 148 of file qdom.h.
     {
         EncodingFromDocument      = 1,
         EncodingFromTextStream    = 2
     };
NodeType
enum QDomNode::NodeType
This enum defines the type of the node:
ElementNode
AttributeNode
TextNode
CDATASectionNode
EntityReferenceNode
EntityNode
ProcessingInstructionNode
CommentNode
DocumentNode
DocumentTypeNode
DocumentFragmentNode
NotationNode
BaseNode A QDomNode object, i.
e. not a QDomNode subclass.
CharacterDataNode
Enumerator
ElementNode
AttributeNode
TextNode
CDATASectionNode
EntityReferenceNode
EntityNode
ProcessingInstructionNode
CommentNode
DocumentNode
DocumentTypeNode
DocumentFragmentNode
NotationNode
BaseNode
CharacterDataNode
Definition at line 131 of file qdom.h.
                   {
         ElementNode               = 1,
         AttributeNode             = 2,
         TextNode                  = 3,
         CDATASectionNode          = 4,
         EntityReferenceNode       = 5,
         EntityNode                = 6,
         ProcessingInstructionNode = 7,
         CommentNode               = 8,
         DocumentNode              = 9,
         DocumentTypeNode          = 10,
         DocumentFragmentNode      = 11,
         NotationNode              = 12,
         BaseNode                  = 21,// this is not in the standard
         CharacterDataNode         = 22 // this is not in the standard
     };
Constructors and Destructors
QDomNode() [1/3]
QDomNode::QDomNode ()
Constructs a null node.
Definition at line 2057 of file qdom.cpp.
Referenced by QDomDocument::importNode().
 {
     impl = 0;
 }
QDomNode() [2/3]
QDomNode::QDomNode (const QDomNode & n)
Constructs a copy of n.
The data of the copy is shared (shallow copy): modifying one node will also change the other. If you want to make a deep copy, use cloneNode().
Definition at line 2069 of file qdom.cpp.
 {
     impl = n.impl;
     if (impl)
         impl->ref.ref();
 }
~QDomNode()
QDomNode::~QDomNode ()
Destroys the object and frees its resources.
Definition at line 2143 of file qdom.cpp.
 {
     if (impl && !impl->ref.deref())
         delete impl;
 }
QDomNode() [3/3]
QDomNode::QDomNode (QDomNodePrivate * n) protected
Constructs a new node for the data n.
Warning
This function is not part of the public interface.
Definition at line 2082 of file qdom.cpp.
 {
     impl = n;
     if (impl)
         impl->ref.ref();
 }
Functions
appendChild()
QDomNode QDomNode::appendChild (const QDomNode & newChild)
Appends newChild as the node's last child.
If newChild is the child of another node, it is reparented to this node. If newChild is a child of this node, then its position in the list of children is changed.
If newChild is a QDomDocumentFragment, then the children of the fragment are removed from the fragment and appended.
If newChild is a QDomElement and this node is a QDomDocument that already has an element node as a child, newChild is not added as a child and a null node is returned.
Returns a new reference to newChild on success or a null node on failure.
Calling this function on a null node(created, for example, with the default constructor) does nothing and returns a null node.
The DOM specification disallow inserting attribute nodes, but for historical reasons, QDom accepts them anyway.
See also
insertBefore() insertAfter() replaceChild() removeChild()
Definition at line 2655 of file qdom.cpp.
Referenced by QDomImplementation::createDocument().
 {
     if (!impl) {
         qWarning("Calling appendChild() on a null node does nothing.");
         return QDomNode();
     }
     return QDomNode(IMPL->appendChild(newChild.impl));
 }
attributes()
QDomNamedNodeMap QDomNode::attributes () const
Returns a named node map of all attributes.
Attributes are only provided for QDomElement.
Changing the attributes in the map will also change the attributes of this QDomNode.
Definition at line 2370 of file qdom.cpp.
Referenced by QDomElement::setAttributeNS().
 {
     if (!impl || !impl->isElement())
         return QDomNamedNodeMap();
     return QDomNamedNodeMap(static_cast<QDomElementPrivate *>(impl)->attributes());
 }
childNodes()
QDomNodeList QDomNode::childNodes () const
Returns a list of all direct child nodes.
Most often you will call this function on a QDomElement object.
For example, if the XML document looks like this:
<body>
<h1>Heading</h1>
<p>Hello <b>you</b></p>
</body>
Then the list of child nodes for the "body"-element will contain the node created by the <h1> tag and the node created by the <p> tag.
The nodes in the list are not copied; so changing the nodes in the list will also change the children of this node.
See also
firstChild() lastChild()
Definition at line 2290 of file qdom.cpp.
 {
     if (!impl)
         return QDomNodeList();
     return QDomNodeList(new QDomNodeListPrivate(impl));
 }
clear()
void QDomNode::clear (void)
Converts the node into a null node; if it was not a null node before, its type and contents are deleted.
See also
isNull()
Definition at line 2690 of file qdom.cpp.
 {
     if (impl && !impl->ref.deref())
         delete impl;
     impl = 0;
 }
cloneNode()
QDomNode QDomNode::cloneNode (bool deep = true) const
Creates a deep (not shallow) copy of the QDomNode.
If deep is true, then the cloning is done recursively which means that all the node's children are deep copied too. If deep is false only the node itself is copied and the copy will have no child nodes.
Definition at line 2396 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->cloneNode(deep));
 }
columnNumber()
int QDomNode::columnNumber () const
For nodes created by QDomDocument::setContent(), this function returns the column number in the XML document where the node was parsed.
Since
4.1
Otherwise, -1 is returned.
See also
lineNumber(), QDomDocument::setContent()
Definition at line 3091 of file qdom.cpp.
 {
     return impl ? impl->columnNumber : -1;
 }
firstChild()
QDomNode QDomNode::firstChild () const
Returns the first child of the node.
If there is no child node, a null node is returned. Changing the returned node will also change the node in the document tree.
See also
lastChild() childNodes()
Definition at line 2304 of file qdom.cpp.
Referenced by QDBusXmlParser::object(), and QDBusXmlParser::objectTree().
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->first);
 }
firstChildElement()
QDomElement QDomNode::firstChildElement (const QString & tagName = QString()) const
Returns the first child element with tag name tagName if tagName is non-empty; otherwise returns the first child element.
Returns a null element if no such child exists.
See also
lastChildElement() previousSiblingElement() nextSiblingElement()
Definition at line 2990 of file qdom.cpp.
Referenced by QDBusXmlParser::QDBusXmlParser().
 {
     for (QDomNode child = firstChild(); !child.isNull(); child = child.nextSibling()) {
         if (child.isElement()) {
             QDomElement elt = child.toElement();
             if (tagName.isEmpty() || elt.tagName() == tagName)
                 return elt;
         }
     }
     return QDomElement();
 }
hasAttributes()
bool QDomNode::hasAttributes () const
Returns true if the node has attributes; otherwise returns false.
See also
attributes()
Definition at line 2521 of file qdom.cpp.
 {
     if (!impl || !impl->isElement())
         return false;
     return static_cast<QDomElementPrivate *>(impl)->hasAttributes();
 }
hasChildNodes()
bool QDomNode::hasChildNodes () const
Returns true if the node has one or more children; otherwise returns false.
Definition at line 2668 of file qdom.cpp.
 {
     if (!impl)
         return false;
     return IMPL->first != 0;
 }
insertAfter()
QDomNode QDomNode::insertAfter (const QDomNode & newChild, const QDomNode & refChild)
Inserts the node newChild after the child node refChild.
refChild must be a direct child of this node. If refChild is null then newChild is appended as this node's last child.
If newChild is the child of another node, it is reparented to this node. If newChild is a child of this node, then its position in the list of children is changed.
If newChild is a QDomDocumentFragment, then the children of the fragment are removed from the fragment and inserted after refChild.
Returns a new reference to newChild on success or a null node on failure.
The DOM specification disallow inserting attribute nodes, but due to historical reasons QDom accept them nevertheless.
See also
insertBefore() replaceChild() removeChild() appendChild()
Definition at line 2579 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->insertAfter(newChild.impl, refChild.impl));
 }
insertBefore()
QDomNode QDomNode::insertBefore (const QDomNode & newChild, const QDomNode & refChild)
Inserts the node newChild before the child node refChild.
refChild must be a direct child of this node. If refChild is null then newChild is inserted as the node's first child.
If newChild is the child of another node, it is reparented to this node. If newChild is a child of this node, then its position in the list of children is changed.
If newChild is a QDomDocumentFragment, then the children of the fragment are removed from the fragment and inserted before refChild.
Returns a new reference to newChild on success or a null node on failure.
The DOM specification disallow inserting attribute nodes, but due to historical reasons QDom accept them nevertheless.
See also
insertAfter() replaceChild() removeChild() appendChild()
Definition at line 2550 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->insertBefore(newChild.impl, refChild.impl));
 }
isAttr()
bool QDomNode::isAttr () const
Returns true if the node is an attribute; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomAttribute; you can get the QDomAttribute with toAttribute().
See also
toAttr()
Definition at line 2781 of file qdom.cpp.
 {
     if(impl)
         return impl->isAttr();
     return false;
 }
isCDATASection()
bool QDomNode::isCDATASection () const
Returns true if the node is a CDATA section; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomCDATASection; you can get the QDomCDATASection with toCDATASection().
See also
toCDATASection()
Definition at line 2798 of file qdom.cpp.
 {
     if(impl)
         return impl->isCDATASection();
     return false;
 }
isCharacterData()
bool QDomNode::isCharacterData () const
Returns true if the node is a character data node; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomCharacterData; you can get the QDomCharacterData with toCharacterData().
See also
toCharacterData()
Definition at line 2958 of file qdom.cpp.
 {
     if (impl)
         return impl->isCharacterData();
     return false;
 }
isComment()
bool QDomNode::isComment () const
Returns true if the node is a comment; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomComment; you can get the QDomComment with toComment().
See also
toComment()
Definition at line 2973 of file qdom.cpp.
 {
     if (impl)
         return impl->isComment();
     return false;
 }
isDocument()
bool QDomNode::isDocument () const
Returns true if the node is a document; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomDocument; you can get the QDomDocument with toDocument().
See also
toDocument()
Definition at line 2830 of file qdom.cpp.
 {
     if(impl)
         return impl->isDocument();
     return false;
 }
isDocumentFragment()
bool QDomNode::isDocumentFragment () const
Returns true if the node is a document fragment; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomDocumentFragment; you can get the QDomDocumentFragment with toDocumentFragment().
See also
toDocumentFragment()
Definition at line 2815 of file qdom.cpp.
 {
     if(impl)
         return impl->isDocumentFragment();
     return false;
 }
isDocumentType()
bool QDomNode::isDocumentType () const
Returns true if the node is a document type; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomDocumentType; you can get the QDomDocumentType with toDocumentType().
See also
toDocumentType()
Definition at line 2847 of file qdom.cpp.
 {
     if(impl)
         return impl->isDocumentType();
     return false;
 }
isElement()
bool QDomNode::isElement () const
Returns true if the node is an element; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomElement; you can get the QDomElement with toElement().
See also
toElement()
Definition at line 2862 of file qdom.cpp.
 {
     if(impl)
         return impl->isElement();
     return false;
 }
isEntity()
bool QDomNode::isEntity () const
Returns true if the node is an entity; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomEntity; you can get the QDomEntity with toEntity().
See also
toEntity()
Definition at line 2909 of file qdom.cpp.
 {
     if(impl)
         return impl->isEntity();
     return false;
 }
isEntityReference()
bool QDomNode::isEntityReference () const
Returns true if the node is an entity reference; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomEntityReference; you can get the QDomEntityReference with toEntityReference().
See also
toEntityReference()
Definition at line 2879 of file qdom.cpp.
 {
     if(impl)
         return impl->isEntityReference();
     return false;
 }
isNotation()
bool QDomNode::isNotation () const
Returns true if the node is a notation; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomNotation; you can get the QDomNotation with toNotation().
See also
toNotation()
Definition at line 2924 of file qdom.cpp.
 {
     if(impl)
         return impl->isNotation();
     return false;
 }
isNull()
bool QDomNode::isNull () const
Returns true if this node is null (i.e.
if it has no type or contents); otherwise returns false.
Definition at line 2679 of file qdom.cpp.
Referenced by QDomImplementation::createDocument(), firstChildElement(), QDBusXmlParser::interfaces(), lastChildElement(), nextSiblingElement(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), parseAnnotations(), parseArgs(), previousSiblingElement(), and removeChild().
 {
     return (impl == 0);
 }
isProcessingInstruction()
bool QDomNode::isProcessingInstruction () const
Returns true if the node is a processing instruction; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomProcessingInstruction; you can get the QProcessingInstruction with toProcessingInstruction().
See also
toProcessingInstruction()
Definition at line 2941 of file qdom.cpp.
 {
     if(impl)
         return impl->isProcessingInstruction();
     return false;
 }
isSupported()
bool QDomNode::isSupported (const QString & feature, const QString & version) const
Returns true if the DOM implementation implements the feature feature and this feature is supported by this node in the version version; otherwise returns false.
See also
QDomImplementation::hasFeature()
Definition at line 2423 of file qdom.cpp.
 {
     QDomImplementation i;
     return i.hasFeature(feature, version);
 }
isText()
bool QDomNode::isText () const
Returns true if the node is a text node; otherwise returns false.
If this function returns true, it does not imply that this object is a QDomText; you can get the QDomText with toText().
See also
toText()
Definition at line 2894 of file qdom.cpp.
 {
     if(impl)
         return impl->isText();
     return false;
 }
lastChild()
QDomNode QDomNode::lastChild () const
Returns the last child of the node.
If there is no child node, a null node is returned. Changing the returned node will also change the node in the document tree.
See also
firstChild() childNodes()
Definition at line 2318 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->last);
 }
lastChildElement()
QDomElement QDomNode::lastChildElement (const QString & tagName = QString()) const
Returns the last child element with tag name tagName if tagName is non-empty; otherwise returns the last child element.
Returns a null element if no such child exists.
See also
firstChildElement() previousSiblingElement() nextSiblingElement()
Definition at line 3010 of file qdom.cpp.
 {
     for (QDomNode child = lastChild(); !child.isNull(); child = child.previousSibling()) {
         if (child.isElement()) {
             QDomElement elt = child.toElement();
             if (tagName.isEmpty() || elt.tagName() == tagName)
                 return elt;
         }
     }
     return QDomElement();
 }
lineNumber()
int QDomNode::lineNumber () const
For nodes created by QDomDocument::setContent(), this function returns the line number in the XML document where the node was parsed.
Since
4.1
Otherwise, -1 is returned.
See also
columnNumber(), QDomDocument::setContent()
Definition at line 3074 of file qdom.cpp.
 {
     return impl ? impl->lineNumber : -1;
 }
localName()
QString QDomNode::localName () const
If the node uses namespaces, this function returns the local name of the node; otherwise it returns an empty string.
Only nodes of type ElementNode or AttributeNode can have namespaces. A namespace must have been specified at creation time; it is not possible to add a namespace afterwards.
See also
prefix() namespaceURI() QDomDocument::createElementNS() QDomDocument::createAttributeNS()
Definition at line 2509 of file qdom.cpp.
 {
     if (!impl || IMPL->createdWithDom1Interface)
         return QString();
     return IMPL->name;
 }
namedItem()
QDomNode QDomNode::namedItem (const QString & name) const
Returns the first direct child node for which nodeName() equals name.
Shortcut to avoid dealing with QDomNodeList all the time.
If no such direct child exists, a null node is returned.
See also
nodeName()
Definition at line 2706 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(impl->namedItem(name));
 }
namespaceURI()
QString QDomNode::namespaceURI () const
Returns the namespace URI of this node or an empty string if the node has no namespace URI.
Only nodes of type ElementNode or AttributeNode can have namespaces. A namespace URI must be specified at creation time and cannot be changed later.
See also
prefix() localName() QDomDocument::createElementNS() QDomDocument::createAttributeNS()
Definition at line 2441 of file qdom.cpp.
 {
     if (!impl)
         return QString();
     return IMPL->namespaceURI;
 }
nextSibling()
QDomNode QDomNode::nextSibling () const
Returns the next sibling in the document tree.
Changing the returned node will also change the node in the document tree.
If you have XML like this:
<h1>Heading</h1>
<p>The text...</p>
<h2>Next heading</h2>
and this QDomNode represents the
tag, nextSibling() will return the node representing the
tag. previousSibling()
Definition at line 2354 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->next);
 }
nextSiblingElement()
QDomElement QDomNode::nextSiblingElement (const QString & tagName = QString()) const
Returns the next sibling element with tag name tagName if tagName is non-empty; otherwise returns any next sibling element.
Returns a null element if no such sibling exists.
See also
firstChildElement() previousSiblingElement() lastChildElement()
Definition at line 3030 of file qdom.cpp.
 {
     for (QDomNode sib = nextSibling(); !sib.isNull(); sib = sib.nextSibling()) {
         if (sib.isElement()) {
             QDomElement elt = sib.toElement();
             if (tagName.isEmpty() || elt.tagName() == tagName)
                 return elt;
         }
     }
     return QDomElement();
 }
nodeName()
QString QDomNode::nodeName () const
Returns the name of the node.
The meaning of the name depends on the subclass:
Name Meaning
QDomAttr The name of the attribute
QDomCDATASection The string "#cdata-section"
QDomComment The string "#comment"
QDomDocument The string "#document"
QDomDocumentFragment The string "#document-fragment"
QDomDocumentType The name of the document type
QDomElement The tag name
QDomEntity The name of the entity
QDomEntityReference The name of the referenced entity
QDomNotation The name of the notation
QDomProcessingInstruction The target of the processing instruction
QDomText The string "#text"
Note: This function does not take the presence of namespaces into account when processing the names of element and attribute nodes. As a result, the returned name can contain any namespace prefix that may be present. To obtain the node name of an element or attribute, use localName(); to obtain the namespace prefix, use namespaceURI().
See also
nodeValue()
Definition at line 2178 of file qdom.cpp.
 {
     if (!impl)
         return QString();
     if (!IMPL->prefix.isEmpty())
         return IMPL->prefix + QLatin1Char(':') + IMPL->name;
     return IMPL->name;
 }
nodeType()
QDomNode::NodeType QDomNode::nodeType () const
Returns the type of the node.
See also
toAttr(), toCDATASection(), toDocumentFragment(), toDocument() toDocumentType(), toElement(), toEntityReference(), toText(), toEntity() toNotation(), toProcessingInstruction(), toCharacterData(), toComment()
Definition at line 2256 of file qdom.cpp.
Referenced by QDomCharacterData::nodeType().
 {
     if (!impl)
         return QDomNode::BaseNode;
     return IMPL->nodeType();
 }
nodeValue()
QString QDomNode::nodeValue () const
Returns the value of the node.
The meaning of the value depends on the subclass:
Name Meaning
QDomAttr The attribute value
QDomCDATASection The content of the CDATA section
QDomComment The comment
QDomProcessingInstruction The data of the processing instruction
QDomText The text
All the other subclasses do not have a node value and will return an empty string.
See also
setNodeValue() nodeName()
Definition at line 2206 of file qdom.cpp.
 {
     if (!impl)
         return QString();
     return IMPL->value;
 }
normalize()
void QDomNode::normalize ()
Calling normalize() on an element converts all its children into a standard form.
This means that adjacent QDomText objects will be merged into a single text object (QDomCDATASection nodes are not merged).
Definition at line 2409 of file qdom.cpp.
 {
     if (!impl)
         return;
     IMPL->normalize();
 }
operator!=()
bool QDomNode::operator!= (const QDomNode & n) const
Returns true if n and this DOM node are not equal; otherwise returns false.
Definition at line 2135 of file qdom.cpp.
 {
     return (impl != n.impl);
 }
operator=()
QDomNode & QDomNode::operator= (const QDomNode & n)
Assigns a copy of n to this DOM node.
The data of the copy is shared (shallow copy): modifying one node will also change the other. If you want to make a deep copy, use cloneNode().
Definition at line 2096 of file qdom.cpp.
Referenced by QDomDocument::operator=(), QDomDocumentFragment::operator=(), QDomCharacterData::operator=(), QDomAttr::operator=(), QDomComment::operator=(), and QDomCDATASection::operator=().
 {
     if (n.impl)
         n.impl->ref.ref();
     if (impl && !impl->ref.deref())
         delete impl;
     impl = n.impl;
     return *this;
 }
operator==()
bool QDomNode::operator== (const QDomNode & n) const
Returns true if n and this DOM node are equal; otherwise returns false.
Any instance of QDomNode acts as a reference to an underlying data structure in QDomDocument. The test for equality checks if the two references point to the same underlying node. For example:
QDomDocument document;
QDomElement element1 = document.documentElement();
QDomElement element2 = element1;
The two nodes (QDomElement is a QDomNode subclass) both refer to the document's root element, and {element1 == element2} will return true. On the other hand:
QDomElement element3 = document.createElement("MyElement");
QDomElement element4 = document.createElement("MyElement");
Even though both nodes are empty elements carrying the same name, {element3 == element4} will return false because they refer to two different nodes in the underlying data structure.
Definition at line 2126 of file qdom.cpp.
 {
     return (impl == n.impl);
 }
ownerDocument()
QDomDocument QDomNode::ownerDocument () const
Returns the document to which this node belongs.
Definition at line 2381 of file qdom.cpp.
 {
     if (!impl)
         return QDomDocument();
     return QDomDocument(IMPL->ownerDocument());
 }
parentNode()
QDomNode QDomNode::parentNode () const
Returns the parent node.
If this node has no parent, a null node is returned (i.e. a node for which isNull() returns true).
Definition at line 2267 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->parent());
 }
prefix()
QString QDomNode::prefix () const
Returns the namespace prefix of the node or an empty string if the node has no namespace prefix.
Only nodes of type ElementNode or AttributeNode can have namespaces. A namespace prefix must be specified at creation time. If a node was created with a namespace prefix, you can change it later with setPrefix().
If you create an element or attribute with QDomDocument::createElement() or QDomDocument::createAttribute(), the prefix will be an empty string. If you use QDomDocument::createElementNS() or QDomDocument::createAttributeNS() instead, the prefix will not be an empty string; but it might be an empty string if the name does not have a prefix.
See also
setPrefix() localName() namespaceURI() QDomDocument::createElementNS() QDomDocument::createAttributeNS()
Definition at line 2469 of file qdom.cpp.
 {
     if (!impl)
         return QString();
     return IMPL->prefix;
 }
previousSibling()
QDomNode QDomNode::previousSibling () const
Returns the previous sibling in the document tree.
Changing the returned node will also change the node in the document tree.
For example, if you have XML like this:
<h1>Heading</h1>
<p>The text...</p>
<h2>Next heading</h2>
and this QDomNode represents the <p> tag, previousSibling() will return the node representing the <h1> tag.
See also
nextSibling()
Definition at line 2336 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     return QDomNode(IMPL->prev);
 }
previousSiblingElement()
QDomElement QDomNode::previousSiblingElement (const QString & tagName = QString()) const
Returns the previous sibilng element with tag name tagName if tagName is non-empty; otherwise returns any previous sibling element.
Returns a null element if no such sibling exists.
See also
firstChildElement(), nextSiblingElement(), lastChildElement()
Definition at line 3050 of file qdom.cpp.
 {
     for (QDomNode sib = previousSibling(); !sib.isNull(); sib = sib.previousSibling()) {
         if (sib.isElement()) {
             QDomElement elt = sib.toElement();
             if (tagName.isEmpty() || elt.tagName() == tagName)
                 return elt;
         }
     }
     return QDomElement();
 }
removeChild()
QDomNode QDomNode::removeChild (const QDomNode & oldChild)
Removes oldChild from the list of children.
oldChild must be a direct child of this node.
Returns a new reference to oldChild on success or a null node on failure.
See also
insertBefore() insertAfter() replaceChild() appendChild()
Definition at line 2618 of file qdom.cpp.
 {
     if (!impl)
         return QDomNode();
     if (oldChild.isNull())
         return QDomNode();
     return QDomNode(IMPL->removeChild(oldChild.impl));
 }
replaceChild()
QDomNode QDomNode::replaceChild (const QDomNode & newChild, const QDomNode & oldChild)
Replaces oldChild with newChild.
oldChild must be a direct child of this node.
If newChild is the child of another node, it is reparented to this node. If newChild is a child of this node, then its position in the list of children is changed.
If newChild is a QDomDocumentFragment, then oldChild is replaced by all of the children of the fragment.
Returns a new reference to oldChild on success or a null node an failure.
See also
insertBefore() insertAfter() removeChild() appendChild()
Definition at line 2602 of file qdom.cpp.
 {
     if (!impl || !newChild.impl || !oldChild.impl)
         return QDomNode();
     return QDomNode(IMPL->replaceChild(newChild.impl, oldChild.impl));
 }
save() [1/2]
void QDomNode::save (QTextStream & str, int indent) const
Writes the XML representation of the node and all its children to the stream str.
This function uses indent as the amount of space to indent the node.
If this node is a document node, the encoding of text stream str's encoding is set by treating a processing instruction by name "xml" as an XML declaration, if such a one exists, and otherwise defaults to UTF-8. XML declarations are not processing instructions, but this behavior exists for historical reasons. If this node is not a document node, the text stream's encoding is used.
If the document contains invalid XML characters or characters that cannot be encoded in the given encoding, the result and behavior is undefined.
Definition at line 2728 of file qdom.cpp.
Referenced by QDBusXmlParser::interfaces(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), operator<<(), and QDomDocument::toString().
 {
     save(str, indent, QDomNode::EncodingFromDocument);
 }
save() [2/2]
void QDomNode::save (QTextStream & str, int indent, EncodingPolicy encodingPolicy) const
If encodingPolicy is QDomNode::EncodingFromDocument, this function behaves as save(QTextStream &str, int indent).
If encodingPolicy is EncodingFromTextStream and this node is a document node, this function behaves as save(QTextStream &str, int indent) with the exception that the encoding specified in the text stream str is used.
If the document contains invalid XML characters or characters that cannot be encoded in the given encoding, the result and behavior is undefined.
Since
4.2
Definition at line 2745 of file qdom.cpp.
 {
     if (!impl)
         return;
     if(isDocument())
         static_cast<const QDomDocumentPrivate *>(impl)->saveDocument(str, indent, encodingPolicy);
     else
         IMPL->save(str, 1, indent);
 }
setNodeValue()
void QDomNode::setNodeValue (const QString & v)
Sets the node's value to v.
See also
nodeValue()
Definition at line 2218 of file qdom.cpp.
 {
     if (!impl)
         return;
     IMPL->setNodeValue(v);
 }
setPrefix()
void QDomNode::setPrefix (const QString & pre)
If the node has a namespace prefix, this function changes the namespace prefix of the node to pre.
Otherwise this function does nothing.
Only nodes of type ElementNode or AttributeNode can have namespaces. A namespace prefix must have be specified at creation time; it is not possible to add a namespace prefix afterwards.
See also
prefix() localName() namespaceURI() QDomDocument::createElementNS() QDomDocument::createAttributeNS()
Definition at line 2489 of file qdom.cpp.
 {
     if (!impl || IMPL->prefix.isNull())
         return;
     if (isAttr() || isElement())
         IMPL->prefix = pre;
 }
toAttr()
QDomAttr QDomNode::toAttr () const
Converts a QDomNode into a QDomAttr.
If the node is not an attribute, the returned object will be null.
See also
isAttr()
Definition at line 7379 of file qdom.cpp.
 {
     if (impl && impl->isAttr())
         return QDomAttr(((QDomAttrPrivate*)impl));
     return QDomAttr();
 }
toCDATASection()
QDomCDATASection QDomNode::toCDATASection () const
Converts a QDomNode into a QDomCDATASection.
If the node is not a CDATA section, the returned object will be null.
See also
isCDATASection()
Definition at line 7393 of file qdom.cpp.
 {
     if (impl && impl->isCDATASection())
         return QDomCDATASection(((QDomCDATASectionPrivate*)impl));
     return QDomCDATASection();
 }
toCharacterData()
QDomCharacterData QDomNode::toCharacterData () const
Converts a QDomNode into a QDomCharacterData.
If the node is not a character data node the returned object will be null.
See also
isCharacterData()
Definition at line 7532 of file qdom.cpp.
 {
     if (impl && impl->isCharacterData())
         return QDomCharacterData(((QDomCharacterDataPrivate*)impl));
     return QDomCharacterData();
 }
toComment()
QDomComment QDomNode::toComment () const
Converts a QDomNode into a QDomComment.
If the node is not a comment the returned object will be null.
See also
isComment()
Definition at line 7546 of file qdom.cpp.
 {
     if (impl && impl->isComment())
         return QDomComment(((QDomCommentPrivate*)impl));
     return QDomComment();
 }
toDocument()
QDomDocument QDomNode::toDocument () const
Converts a QDomNode into a QDomDocument.
If the node is not a document the returned object will be null.
See also
isDocument()
Definition at line 7421 of file qdom.cpp.
 {
     if (impl && impl->isDocument())
         return QDomDocument(((QDomDocumentPrivate*)impl));
     return QDomDocument();
 }
toDocumentFragment()
QDomDocumentFragment QDomNode::toDocumentFragment () const
Converts a QDomNode into a QDomDocumentFragment.
If the node is not a document fragment the returned object will be null.
See also
isDocumentFragment()
Definition at line 7407 of file qdom.cpp.
 {
     if (impl && impl->isDocumentFragment())
         return QDomDocumentFragment(((QDomDocumentFragmentPrivate*)impl));
     return QDomDocumentFragment();
 }
toDocumentType()
QDomDocumentType QDomNode::toDocumentType () const
Converts a QDomNode into a QDomDocumentType.
If the node is not a document type the returned object will be null.
See also
isDocumentType()
Definition at line 7435 of file qdom.cpp.
 {
     if (impl && impl->isDocumentType())
         return QDomDocumentType(((QDomDocumentTypePrivate*)impl));
     return QDomDocumentType();
 }
toElement()
QDomElement QDomNode::toElement () const
Converts a QDomNode into a QDomElement.
If the node is not an element the returned object will be null.
See also
isElement()
Definition at line 7449 of file qdom.cpp.
Referenced by firstChildElement(), QDBusXmlParser::interfaces(), lastChildElement(), nextSiblingElement(), QDBusXmlParser::object(), QDBusXmlParser::objectTree(), parseAnnotations(), parseArgs(), and previousSiblingElement().
 {
     if (impl && impl->isElement())
         return QDomElement(((QDomElementPrivate*)impl));
     return QDomElement();
 }
toEntity()
QDomEntity QDomNode::toEntity () const
Converts a QDomNode into a QDomEntity.
If the node is not an entity the returned object will be null.
See also
isEntity()
Definition at line 7490 of file qdom.cpp.
 {
     if (impl && impl->isEntity())
         return QDomEntity(((QDomEntityPrivate*)impl));
     return QDomEntity();
 }
toEntityReference()
QDomEntityReference QDomNode::toEntityReference () const
Converts a QDomNode into a QDomEntityReference.
If the node is not an entity reference, the returned object will be null.
See also
isEntityReference()
Definition at line 7463 of file qdom.cpp.
 {
     if (impl && impl->isEntityReference())
         return QDomEntityReference(((QDomEntityReferencePrivate*)impl));
     return QDomEntityReference();
 }
toNotation()
QDomNotation QDomNode::toNotation () const
Converts a QDomNode into a QDomNotation.
If the node is not a notation the returned object will be null.
See also
isNotation()
Definition at line 7504 of file qdom.cpp.
 {
     if (impl && impl->isNotation())
         return QDomNotation(((QDomNotationPrivate*)impl));
     return QDomNotation();
 }
toProcessingInstruction()
QDomProcessingInstruction QDomNode::toProcessingInstruction () const
Converts a QDomNode into a QDomProcessingInstruction.
If the node is not a processing instruction the returned object will be null.
See also
isProcessingInstruction()
Definition at line 7518 of file qdom.cpp.
 {
     if (impl && impl->isProcessingInstruction())
         return QDomProcessingInstruction(((QDomProcessingInstructionPrivate*)impl));
     return QDomProcessingInstruction();
 }
toText()
QDomText QDomNode::toText () const
Converts a QDomNode into a QDomText.
If the node is not a text, the returned object will be null.
See also
isText()
Definition at line 7476 of file qdom.cpp.
 {
     if (impl && impl->isText())
         return QDomText(((QDomTextPrivate*)impl));
     return QDomText();
 }
Friends and Related Functions
operator<<()
QTextStream & operator<< (QTextStream & str, const QDomNode & node) related
Writes the XML representation of the node node and all its children to the stream str.
Definition at line 2765 of file qdom.cpp.
 {
     node.save(str, 1);
     return str;
 }
QDomDocument
friend class QDomDocument friend
Definition at line 247 of file qdom.h.
Referenced by QDomDocument::nodeType().
QDomDocumentType
friend class QDomDocumentType friend
Definition at line 248 of file qdom.h.
Referenced by QDomDocument::doctype(), QDomDocumentType::nodeType(), and toDocumentType().
QDomNamedNodeMap
friend class QDomNamedNodeMap friend
Definition at line 250 of file qdom.h.
QDomNodeList
friend class QDomNodeList friend
Definition at line 249 of file qdom.h.
Referenced by QDomDocument::elementsByTagName(), and QDomDocument::elementsByTagNameNS().
Properties
impl
QDomNodePrivate* QDomNode::impl protected
Definition at line 243 of file qdom.h.
Referenced by appendChild(), QDomCharacterData::appendData(), QDomDocument::createAttribute(), QDomDocument::createAttributeNS(), QDomDocument::createCDATASection(), QDomDocument::createComment(), QDomDocument::createDocumentFragment(), QDomDocument::createElement(), QDomDocument::createElementNS(), QDomDocument::createEntityReference(), QDomDocument::createProcessingInstruction(), QDomDocument::createTextNode(), QDomCharacterData::data(), QDomCharacterData::deleteData(), QDomDocument::doctype(), QDomDocument::documentElement(), QDomDocument::elementsByTagName(), QDomDocument::elementsByTagNameNS(), QDomDocument::implementation(), QDomDocument::importNode(), insertAfter(), insertBefore(), QDomCharacterData::insertData(), QDomCharacterData::length(), QDomAttr::name(), QDomCharacterData::nodeType(), operator!=(), operator=(), operator==(), QDomAttr::ownerElement(), QDomDocument::QDomDocument(), QDomNode(), removeChild(), replaceChild(), QDomCharacterData::replaceData(), QDomDocument::setContent(), QDomCharacterData::setData(), QDomNamedNodeMap::setNamedItem(), QDomNamedNodeMap::setNamedItemNS(), QDomAttr::setValue(), QDomAttr::specified(), QDomCharacterData::substringData(), toAttr(), toCDATASection(), toCharacterData(), toComment(), toDocument(), toDocumentFragment(), toDocumentType(), toElement(), toEntity(), toEntityReference(), toNotation(), toProcessingInstruction(), toText(), and QDomAttr::value().
The documentation for this class was generated from the following files:
/src/xml/dom/qdom.h
/src/xml/dom/qdom.cpp