Qt 4.8: QFutureWatcherBase Class Reference
QFutureWatcherBase Class Reference abstract
#include <qfuturewatcher.h>
Public Slots
void cancel ()
void pause ()
void resume ()
void setPaused (bool paused)
void togglePaused ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void canceled ()
void finished ()
void paused ()
void progressRangeChanged (int minimum, int maximum)
void progressTextChanged (const QString &progressText)
void progressValueChanged (int progressValue)
void resultReadyAt (int resultIndex)
void resultsReadyAt (int beginIndex, int endIndex)
void resumed ()
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool event (QEvent *event)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
bool isCanceled () const
bool isFinished () const
bool isPaused () const
bool isRunning () const
bool isStarted () const
int progressMaximum () const
int progressMinimum () const
QString progressText () const
int progressValue () const
QFutureWatcherBase (QObject *parent=0)
void setPendingResultsLimit (int limit)
void waitForFinished ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
void connectOutputInterface ()
void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
void disconnectOutputInterface (bool pendingAssignment=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
virtual const QFutureInterfaceBase & futureInterface () const =0
virtual QFutureInterfaceBase & futureInterface ()=0
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 62 of file qfuturewatcher.h.
Constructors and Destructors
QFutureWatcherBase()
QFutureWatcherBase::QFutureWatcherBase (QObject * parent = 0)
Definition at line 109 of file qfuturewatcher.cpp.
     :QObject(*new QFutureWatcherBasePrivate, parent)
 { }
Functions
cancel
void QFutureWatcherBase::cancel () slot
Definition at line 141 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     futureInterface().cancel();
 }
canceled
void QFutureWatcherBase::canceled () signal
connectNotify()
void QFutureWatcherBase::connectNotify (const char * signal) protected virtual
This virtual function is called when something has been connected to signal in this object.
If you want to compare signal with a specific signal, use QLatin1String and the SIGNAL() macro as follows:
if (QLatin1String(signal) == SIGNAL(valueChanged(int))) {
    // signal is valueChanged(int)
}
If the signal contains multiple parameters or parameters that contain spaces, call QMetaObject::normalizedSignature() on the result of the SIGNAL() macro.
Warning
This function violates the object-oriented principle of modularity. However, it might be useful when you need to perform expensive initialization only if something is connected to a signal.
See also
connect(), disconnectNotify()
Reimplemented from QObject.
Definition at line 411 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     Q_D(QFutureWatcherBase);
     if (qstrcmp(signal, SIGNAL(resultReadyAt(int))) == 0)
         d->resultAtConnected.ref();
 #ifndef QT_NO_DEBUG
     if (qstrcmp(signal, SIGNAL(finished())) == 0) {
         if (futureInterface().isRunning()) {
             //connections should be established before calling stFuture to avoid race.
             // (The future could finish before the connection is made.)
             qWarning("QFutureWatcher::connect: connecting after calling setFuture() is likely to produce race");
         }
     }
 #endif
 }
connectOutputInterface()
void QFutureWatcherBase::connectOutputInterface () protected
Warning
This function is not part of the public interface.
Definition at line 445 of file qfuturewatcher.cpp.
 {
     futureInterface().d->connectOutputInterface(d_func());
 }
disconnectNotify()
void QFutureWatcherBase::disconnectNotify (const char * signal) protected virtual
This virtual function is called when something has been disconnected from signal in this object.
See connectNotify() for an example of how to compare signal with a specific signal.
Warning
This function violates the object-oriented principle of modularity. However, it might be useful for optimizing access to expensive resources.
See also
disconnect(), connectNotify()
Reimplemented from QObject.
Definition at line 427 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     Q_D(QFutureWatcherBase);
     if (qstrcmp(signal, SIGNAL(resultReadyAt(int))) == 0)
         d->resultAtConnected.deref();
 }
disconnectOutputInterface()
void QFutureWatcherBase::disconnectOutputInterface (bool pendingAssignment = false) protected
Warning
This function is not part of the public interface.
Definition at line 453 of file qfuturewatcher.cpp.
 {
     if (pendingAssignment) {
         Q_D(QFutureWatcherBase);
         d->pendingResultsReady = 0;
         qDeleteAll(d->pendingCallOutEvents);
         d->pendingCallOutEvents.clear();
         d->finished = false;
     }
     futureInterface().d->disconnectOutputInterface(d_func());
 }
event()
bool QFutureWatcherBase::event (QEvent * e) virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 376 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     Q_D(QFutureWatcherBase);
     if (event->type() == QEvent::FutureCallOut) {
         QFutureCallOutEvent *callOutEvent = static_cast<QFutureCallOutEvent *>(event);
         if (futureInterface().isPaused()) {
             d->pendingCallOutEvents.append(callOutEvent->clone());
             return true;
         }
         if (callOutEvent->callOutType == QFutureCallOutEvent::Resumed
             && !d->pendingCallOutEvents.isEmpty()) {
             // send the resume
             d->sendCallOutEvent(callOutEvent);
             // next send all pending call outs
             for (int i = 0; i < d->pendingCallOutEvents.count(); ++i)
                 d->sendCallOutEvent(d->pendingCallOutEvents.at(i));
             qDeleteAll(d->pendingCallOutEvents);
             d->pendingCallOutEvents.clear();
         } else {
             d->sendCallOutEvent(callOutEvent);
         }
         return true;
     }
     return QObject::event(event);
 }
finished
void QFutureWatcherBase::finished () signal
Referenced by connectNotify().
futureInterface() [1/2]
virtual const QFutureInterfaceBase& QFutureWatcherBase::futureInterface () const private pure virtual
Implemented in QFutureWatcher< T >.
Referenced by cancel(), connectNotify(), event(), isCanceled(), isPaused(), isRunning(), isStarted(), pause(), progressMaximum(), progressMinimum(), progressText(), progressValue(), resume(), setPaused(), togglePaused(), and waitForFinished().
futureInterface() [2/2]
virtual QFutureInterfaceBase& QFutureWatcherBase::futureInterface () private pure virtual
Implemented in QFutureWatcher< T >.
isCanceled()
bool QFutureWatcherBase::isCanceled () const
Definition at line 328 of file qfuturewatcher.cpp.
 {
     return futureInterface().queryState(QFutureInterfaceBase::Canceled);
 }
isFinished()
bool QFutureWatcherBase::isFinished () const
Definition at line 298 of file qfuturewatcher.cpp.
 {
     Q_D(const QFutureWatcherBase);
     return d->finished;
 }
isPaused()
bool QFutureWatcherBase::isPaused () const
Definition at line 346 of file qfuturewatcher.cpp.
 {
     return futureInterface().queryState(QFutureInterfaceBase::Paused);
 }
isRunning()
bool QFutureWatcherBase::isRunning () const
Definition at line 312 of file qfuturewatcher.cpp.
Referenced by connectNotify().
 {
     return futureInterface().queryState(QFutureInterfaceBase::Running);
 }
isStarted()
bool QFutureWatcherBase::isStarted () const
Definition at line 285 of file qfuturewatcher.cpp.
 {
     return futureInterface().queryState(QFutureInterfaceBase::Started);
 }
pause
void QFutureWatcherBase::pause () slot
Definition at line 181 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     futureInterface().setPaused(true);
 }
paused
void QFutureWatcherBase::paused () signal
progressMaximum()
int QFutureWatcherBase::progressMaximum () const
Definition at line 256 of file qfuturewatcher.cpp.
 {
     return futureInterface().progressMaximum();
 }
progressMinimum()
int QFutureWatcherBase::progressMinimum () const
Definition at line 242 of file qfuturewatcher.cpp.
 {
     return futureInterface().progressMinimum();
 }
progressRangeChanged
void QFutureWatcherBase::progressRangeChanged (int minimum, int maximum) signal
progressText()
QString QFutureWatcherBase::progressText () const
Definition at line 272 of file qfuturewatcher.cpp.
 {
     return futureInterface().progressText();
 }
progressTextChanged
void QFutureWatcherBase::progressTextChanged (const QString & progressText) signal
progressValue()
int QFutureWatcherBase::progressValue () const
Definition at line 228 of file qfuturewatcher.cpp.
 {
     return futureInterface().progressValue();
 }
progressValueChanged
void QFutureWatcherBase::progressValueChanged (int progressValue) signal
resultReadyAt
void QFutureWatcherBase::resultReadyAt (int resultIndex) signal
Referenced by connectNotify(), and disconnectNotify().
resultsReadyAt
void QFutureWatcherBase::resultsReadyAt (int beginIndex, int endIndex) signal
resume
void QFutureWatcherBase::resume () slot
Definition at line 196 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     futureInterface().setPaused(false);
 }
resumed
void QFutureWatcherBase::resumed () signal
setPaused
void QFutureWatcherBase::setPaused (bool paused) slot
Definition at line 166 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     futureInterface().setPaused(paused);
 }
setPendingResultsLimit()
void QFutureWatcherBase::setPendingResultsLimit (int limit)
Definition at line 405 of file qfuturewatcher.cpp.
 {
     Q_D(QFutureWatcherBase);
     d->maximumPendingResultsReady = limit;
 }
started
void QFutureWatcherBase::started () signal
togglePaused
void QFutureWatcherBase::togglePaused () slot
Definition at line 213 of file qfuturewatcher.cpp.
Referenced by QFutureWatcherBasePrivate::sendCallOutEvent().
 {
     futureInterface().togglePaused();
 }
waitForFinished()
void QFutureWatcherBase::waitForFinished ()
Definition at line 359 of file qfuturewatcher.cpp.
 {
     futureInterface().waitForFinished();
 }
The documentation for this class was generated from the following files:
/src/corelib/concurrent/qfuturewatcher.h
/src/corelib/concurrent/qfuturewatcher.cpp