Qt 4.8: QPatternist::OperandsIterator Class Reference
QPatternist::OperandsIterator Class Reference
A helper class that iterates a tree of Expression instances. It is not a sub-class of QAbstractXmlForwardIterator.
#include <qoperandsiterator_p.h>
Public Types
enum TreatParent { ExcludeParent, IncludeParent }
Public Functions
Expression::Ptr next ()
Returns the current Expression and advances the iterator.
OperandsIterator (const Expression::Ptr &start, const TreatParent treatParent)
Expression::Ptr skipOperands ()
Private Types
typedef QPair< Expression::List, int > Level
Properties
QStack< Level > m_exprs
Detailed Description
A helper class that iterates a tree of Expression instances. It is not a sub-class of QAbstractXmlForwardIterator.
The OperandsIterator delivers all Expression instances that are children at any depth of the Expression passed in the constructor. The order is delivered in a defined way, from left to right and depth first.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 77 of file qoperandsiterator_p.h.
Typedefs
Level
typedef QPair<Expression::List, int> QPatternist::OperandsIterator::Level private
The second value, the int, is the current position in the first.
Definition at line 82 of file qoperandsiterator_p.h.
Enumerations
TreatParent
enum QPatternist::OperandsIterator::TreatParent
Enumerator
ExcludeParent
IncludeParent
Definition at line 85 of file qoperandsiterator_p.h.
         {
             ExcludeParent,
             IncludeParent
         };
Constructors and Destructors
OperandsIterator()
QPatternist::OperandsIterator::OperandsIterator (const Expression::Ptr & start, const TreatParent treatParent) inline
if treatParent is IncludeParent, start is excluded.
start must be a valid Expression.
Definition at line 96 of file qoperandsiterator_p.h.
         {
             Q_ASSERT(start);
             if(treatParent == IncludeParent)
             {
                 Expression::List l;
                 l.append(start);
                 m_exprs.push(qMakePair(l, -1));
             }
             m_exprs.push(qMakePair(start->operands(), -1));
         }
Functions
next()
Expression::Ptr QPatternist::OperandsIterator::next () inline
Returns the current Expression and advances the iterator.
If the end has been reached, a default constructed pointer is returned.
We intentionally return by reference.
Definition at line 118 of file qoperandsiterator_p.h.
Referenced by QPatternist::Expression::dependencies(), QPatternist::ExpressionFactory::registerLastPath(), skipOperands(), and QPatternist::EvaluationCache< IsForGlobal >::typeCheck().
         {
             if(m_exprs.isEmpty())
                 return Expression::Ptr();
             Level &lvl = m_exprs.top();
             ++lvl.second;
             if(lvl.second == lvl.first.size())
             {
                 /* Resume iteration above us. */
                 m_exprs.pop();
                 if(m_exprs.isEmpty())
                     return Expression::Ptr();
                 while(true)
                 {
                     Level &previous = m_exprs.top();
                     ++previous.second;
                     if(previous.second < previous.first.count())
                     {
                         const Expression::Ptr &op = previous.first.at(previous.second);
                         m_exprs.push(qMakePair(op->operands(), -1));
                         return op;
                     }
                     else
                     {
                         // We have already reached the end of this level.
                         m_exprs.pop();
                         if(m_exprs.isEmpty())
                             return Expression::Ptr();
                     }
                 }
             }
             else
             {
                 const Expression::Ptr &op = lvl.first.at(lvl.second);
                 m_exprs.push(qMakePair(op->operands(), -1));
                 return op;
             }
         }
skipOperands()
Expression::Ptr QPatternist::OperandsIterator::skipOperands () inline
Advances this iterator by the current expression and its operands.
Definition at line 165 of file qoperandsiterator_p.h.
Referenced by QPatternist::ExpressionFactory::registerLastPath().
         {
             if(m_exprs.isEmpty())
                 return Expression::Ptr();
             Level &lvl = m_exprs.top();
             ++lvl.second;
             if(lvl.second == lvl.first.size())
             {
                 /* We've reached the end of this level, at least. */
                 m_exprs.pop();
             }
             return next();
         }
Properties
m_exprs
QStack<Level> QPatternist::OperandsIterator::m_exprs private
Definition at line 185 of file qoperandsiterator_p.h.
Referenced by next(), OperandsIterator(), and skipOperands().
The documentation for this class was generated from the following file:
/src/xmlpatterns/expr/qoperandsiterator_p.h