Qt 4.8: QDeclarativeTransition Class Reference
QDeclarativeTransition Class Reference
#include <qdeclarativetransition_p.h>
Signals
void fromChanged ()
void reversibleChanged ()
void toChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeListProperty< QDeclarativeAbstractAnimation > animations ()
QString fromState () const
void prepare (QDeclarativeStateOperation::ActionList &actions, QList< QDeclarativeProperty > &after, QDeclarativeTransitionManager *end)
QDeclarativeTransition (QObject *parent=0)
bool reversible () const
void setFromState (const QString &)
void setReversed (bool r)
void setReversible (bool)
void setToState (const QString &)
void stop ()
QString toState () const
~QDeclarativeTransition ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QDeclarativeListProperty< QDeclarativeAbstractAnimation > animations
QString from
bool reversible
QString to
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 60 of file qdeclarativetransition_p.h.
Constructors and Destructors
QDeclarativeTransition()
QDeclarativeTransition::QDeclarativeTransition (QObject * parent = 0)
Definition at line 185 of file qdeclarativetransition.cpp.
     : QObject(*(new QDeclarativeTransitionPrivate), parent)
 {
 }
~QDeclarativeTransition()
QDeclarativeTransition::~QDeclarativeTransition ()
Definition at line 190 of file qdeclarativetransition.cpp.
 {
 }
Functions
animations()
QDeclarativeListProperty<QDeclarativeAbstractAnimation> QDeclarativeTransition::animations ()
Referenced by setToState().
fromChanged
void QDeclarativeTransition::fromChanged () signal
Referenced by setFromState().
fromState()
QString QDeclarativeTransition::fromState () const
Definition at line 252 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeStateGroupPrivate::findTransition(), and QDeclarativeStateGroupPrivate::setCurrentStateInternal().
 {
     Q_D(const QDeclarativeTransition);
     return d->fromState;
 }
prepare()
void QDeclarativeTransition::prepare (QDeclarativeStateOperation::ActionList & actions, QList< QDeclarativeProperty > & after, QDeclarativeTransitionManager * end)
Definition at line 206 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeTransitionManager::transition().
 {
     Q_D(QDeclarativeTransition);
     qmlExecuteDeferred(this);
     if (d->reversed) {
         for (int ii = d->animations.count() - 1; ii >= 0; --ii) {
             d->animations.at(ii)->transition(actions, after, QDeclarativeAbstractAnimation::Backward);
         }
     } else {
         for (int ii = 0; ii < d->animations.count(); ++ii) {
             d->animations.at(ii)->transition(actions, after, QDeclarativeAbstractAnimation::Forward);
         }
     }
     d->endState = endState;
     d->group.setDirection(d->reversed ? QAbstractAnimation::Backward : QAbstractAnimation::Forward);
     d->group.start();
 }
reversible()
bool QDeclarativeTransition::reversible () const
Referenced by setFromState().
reversibleChanged
void QDeclarativeTransition::reversibleChanged () signal
Referenced by setReversible().
setFromState()
void QDeclarativeTransition::setFromState (const QString & f)
Definition at line 258 of file qdeclarativetransition.cpp.
 {
     Q_D(QDeclarativeTransition);
     if (f == d->fromState)
         return;
     d->fromState = f;
     emit fromChanged();
 }
setReversed()
void QDeclarativeTransition::setReversed (bool r)
Definition at line 200 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeStateGroupPrivate::findTransition().
 {
     Q_D(QDeclarativeTransition);
     d->reversed = r;
 }
setReversible()
void QDeclarativeTransition::setReversible (bool r)
Definition at line 301 of file qdeclarativetransition.cpp.
 {
     Q_D(QDeclarativeTransition);
     if (r == d->reversible)
         return;
     d->reversible = r;
     emit reversibleChanged();
 }
setToState()
void QDeclarativeTransition::setToState (const QString & t)
Definition at line 317 of file qdeclarativetransition.cpp.
 {
     Q_D(QDeclarativeTransition);
     if (t == d->toState)
         return;
     d->toState = t;
     emit toChanged();
 }
stop()
void QDeclarativeTransition::stop ()
Definition at line 194 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeTransitionManager::cancel().
 {
     Q_D(QDeclarativeTransition);
     d->group.stop();
 }
toChanged
void QDeclarativeTransition::toChanged () signal
Referenced by setToState().
toState()
QString QDeclarativeTransition::toState () const
Definition at line 311 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeStateGroupPrivate::findTransition(), and QDeclarativeStateGroupPrivate::setCurrentStateInternal().
 {
     Q_D(const QDeclarativeTransition);
     return d->toState;
 }
Properties
animations
QDeclarativeListProperty< QDeclarativeAbstractAnimation > QDeclarativeTransition::animations private
Definition at line 68 of file qdeclarativetransition_p.h.
Referenced by QDeclarativeTransitionPrivate::animation_at(), QDeclarativeTransitionPrivate::animation_count(), QDeclarativeTransitionPrivate::append_animation(), and QDeclarativeTransitionPrivate::clear_animations().
from
QString QDeclarativeTransition::from private
Definition at line 65 of file qdeclarativetransition_p.h.
reversible
bool QDeclarativeTransition::reversible private
Definition at line 67 of file qdeclarativetransition_p.h.
Referenced by QDeclarativeStateGroupPrivate::findTransition().
to
QString QDeclarativeTransition::to private
Definition at line 66 of file qdeclarativetransition_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativetransition_p.h
/src/declarative/util/qdeclarativetransition.cpp