Qt 4.8: QDoubleSpinBox Class Reference
QDoubleSpinBox Class Reference
The QDoubleSpinBox class provides a spin box widget that takes doubles.
#include <qspinbox.h>
Public Slots
void setValue (double val)
Public Slots inherited from QAbstractSpinBox
virtual void clear ()
Clears the lineedit of all text but prefix and suffix.
void selectAll ()
Selects all the text in the spinbox except the prefix and suffix.
void stepDown ()
Steps down by one linestep Calling this slot is analogous to calling stepBy(-1);.
void stepUp ()
Steps up by one linestep Calling this slot is analogous to calling stepBy(1);.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void valueChanged (double)
This signal is emitted whenever the spin box's value is changed.
void valueChanged (const QString &)
The new value is passed literally in text with no prefix() or suffix().
Signals inherited from QAbstractSpinBox
void editingFinished ()
This signal is emitted editing is finished.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QString cleanText () const
int decimals () const
virtual void fixup (QString &str) const
Reimplemented Function
double maximum () const
double minimum () const
QString prefix () const
QDoubleSpinBox (QWidget *parent=0)
Constructs a spin box with 0.0 as minimum value and 99.99 as maximum value, a step value of 1.0 and a precision of 2 decimal places.
void setDecimals (int prec)
void setMaximum (double max)
void setMinimum (double min)
void setPrefix (const QString &prefix)
void setRange (double min, double max)
Convenience function to set the minimum and maximum values with a single function call.
void setSingleStep (double val)
void setSuffix (const QString &suffix)
double singleStep () const
QString suffix () const
virtual QString textFromValue (double val) const
This virtual function is used by the spin box whenever it needs to display the given value.
virtual QValidator::State validate (QString &input, int &pos) const
Reimplemented Function
double value () const
virtual double valueFromText (const QString &text) const
This virtual function is used by the spin box whenever it needs to interpret text entered by the user as a value.
Public Functions inherited from QAbstractSpinBox
Qt::Alignment alignment () const
ButtonSymbols buttonSymbols () const
CorrectionMode correctionMode () const
bool event (QEvent *event)
Reimplemented Function
bool hasAcceptableInput () const
bool hasFrame () const
QVariant inputMethodQuery (Qt::InputMethodQuery) const
Reimplemented Function
void interpretText ()
This function interprets the text of the spin box.
bool isAccelerated () const
bool isReadOnly () const
bool keyboardTracking () const
QSize minimumSizeHint () const
Reimplemented Function
QAbstractSpinBox (QWidget *parent=0)
Constructs an abstract spinbox with the given parent with default wrapping , and alignment properties.
void setAccelerated (bool on)
void setAlignment (Qt::Alignment flag)
void setButtonSymbols (ButtonSymbols bs)
void setCorrectionMode (CorrectionMode cm)
void setFrame (bool)
void setKeyboardTracking (bool kt)
void setReadOnly (bool r)
void setSpecialValueText (const QString &txt)
void setWrapping (bool w)
QSize sizeHint () const
Reimplemented Function
QString specialValueText () const
virtual void stepBy (int steps)
Virtual function that is called whenever the user triggers a step.
QString text () const
bool wrapping () const
~QAbstractSpinBox ()
Called when the QAbstractSpinBox is destroyed.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Properties
QString cleanText
the text of the spin box excluding any prefix, suffix, or leading or trailing whitespace.
int decimals
the precision of the spin box, in decimals
double maximum
the maximum value of the spin box
double minimum
the minimum value of the spin box
QString prefix
the spin box's prefix
double singleStep
the step value
QString suffix
the suffix of the spin box
double value
the value of the spin box
Additional Inherited Members
Public Types inherited from QAbstractSpinBox
enum ButtonSymbols { UpDownArrows, PlusMinus, NoButtons }
This enum type describes the symbols that can be displayed on the buttons in a spin box.
enum CorrectionMode { CorrectToPreviousValue, CorrectToNearestValue }
This enum type describes the mode the spinbox will use to correct an QValidator::Intermediate value if editing finishes.
enum StepEnabledFlag { StepNone = 0x00, StepUpEnabled = 0x01, StepDownEnabled = 0x02 }
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions inherited from QAbstractSpinBox
void changeEvent (QEvent *event)
Reimplemented Function
void closeEvent (QCloseEvent *event)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *event)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
void hideEvent (QHideEvent *event)
Reimplemented Function
void initStyleOption (QStyleOptionSpinBox *option) const
Initialize option with the values from this QSpinBox.
void keyPressEvent (QKeyEvent *event)
This function handles keyboard input.
void keyReleaseEvent (QKeyEvent *event)
Reimplemented Function
QLineEdit * lineEdit () const
This function returns a pointer to the line edit of the spin box.
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
void paintEvent (QPaintEvent *event)
Reimplemented Function
QAbstractSpinBox (QAbstractSpinBoxPrivate &dd, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void setLineEdit (QLineEdit *edit)
Sets the line edit of the spinbox to be lineEdit instead of the current line edit widget.
void showEvent (QShowEvent *event)
Reimplemented Function
virtual StepEnabled stepEnabled () const
Virtual function that determines whether stepping up and down is legal at any given time.
void timerEvent (QTimerEvent *event)
Reimplemented Function
void wheelEvent (QWheelEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QDoubleSpinBox class provides a spin box widget that takes doubles.
QDoubleSpinBox allows the user to choose a value by clicking the up and down buttons or by pressing Up or Down on the keyboard to increase or decrease the value currently displayed. The user can also type the value in manually. The spin box supports double values but can be extended to use different strings with validate(), textFromValue() and valueFromText().
Every time the value changes QDoubleSpinBox emits the valueChanged() signal. The current value can be fetched with value() and set with setValue().
Note: QDoubleSpinBox will round numbers so they can be displayed with the current precision. In a QDoubleSpinBox with decimals set to 2, calling setValue(2.555) will cause value() to return 2.56.
Clicking the up and down buttons or using the keyboard accelerator's Up and Down arrows will increase or decrease the current value in steps of size singleStep(). If you want to change this behavior you can reimplement the virtual function stepBy(). The minimum and maximum value and the step size can be set using one of the constructors, and can be changed later with setMinimum(), setMaximum() and setSingleStep(). The spinbox has a default precision of 2 decimal places but this can be changed using setDecimals().
Most spin boxes are directional, but QDoubleSpinBox can also operate as a circular spin box, i.e. if the range is 0.0-99.9 and the current value is 99.9, clicking "up" will give 0 if wrapping() is set to true. Use setWrapping() if you want circular behavior.
The displayed value can be prepended and appended with arbitrary strings indicating, for example, currency or the unit of measurement. See setPrefix() and setSuffix(). The text in the spin box is retrieved with text() (which includes any prefix() and suffix()), or with cleanText() (which has no prefix(), no suffix() and no leading or trailing whitespace).
It is often desirable to give the user a special (often default) choice in addition to the range of numeric values. See setSpecialValueText() for how to do this with QDoubleSpinBox.
See also
QSpinBox, QDateTimeEdit, QSlider, {Spin Boxes Example}
Definition at line 126 of file qspinbox.h.
Constructors and Destructors
QDoubleSpinBox()
QDoubleSpinBox::QDoubleSpinBox (QWidget * parent = 0) explicit
Constructs a spin box with 0.0 as minimum value and 99.99 as maximum value, a step value of 1.0 and a precision of 2 decimal places.
The value is initially set to 0.00. The spin box has the given parent.
See also
setMinimum(), setMaximum(), setSingleStep()
Definition at line 644 of file qspinbox.cpp.
     : QAbstractSpinBox(*new QDoubleSpinBoxPrivate, parent)
 {
     Q_D(QDoubleSpinBox);
     d->init();
 }
Functions
cleanText()
QString QDoubleSpinBox::cleanText () const
Referenced by setSuffix().
decimals()
int QDoubleSpinBox::decimals () const
Referenced by QDoubleSpinBoxPrivate::QDoubleSpinBoxPrivate(), QDoubleSpinBoxPrivate::round(), setRange(), and QDoubleSpinBoxPrivate::validateAndInterpret().
fixup()
void QDoubleSpinBox::fixup (QString & str) const virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 994 of file qspinbox.cpp.
 {
     input.remove(locale().groupSeparator());
 }
maximum()
double QDoubleSpinBox::maximum () const
Referenced by QDoubleSpinBoxPrivate::QDoubleSpinBoxPrivate(), QSpinBoxPrivate::QSpinBoxPrivate(), setMaximum(), setMinimum(), setRange(), QSpinBoxPrivate::validateAndInterpret(), and QDoubleSpinBoxPrivate::validateAndInterpret().
minimum()
double QDoubleSpinBox::minimum () const
Referenced by QDoubleSpinBoxPrivate::QDoubleSpinBoxPrivate(), QSpinBoxPrivate::QSpinBoxPrivate(), setMinimum(), setRange(), setSingleStep(), QSpinBoxPrivate::validateAndInterpret(), and QDoubleSpinBoxPrivate::validateAndInterpret().
prefix()
QString QDoubleSpinBox::prefix () const
Referenced by setPrefix(), setValue(), QSpinBoxPrivate::validateAndInterpret(), and QDoubleSpinBoxPrivate::validateAndInterpret().
setDecimals()
void QDoubleSpinBox::setDecimals (int prec)
Definition at line 919 of file qspinbox.cpp.
 {
     Q_D(QDoubleSpinBox);
     d->decimals = qBound(0, decimals, DBL_MAX_10_EXP + DBL_DIG);
     setRange(d->actualMin, d->actualMax); // make sure values are rounded
     setValue(value());
 }
setMaximum()
void QDoubleSpinBox::setMaximum (double max)
Definition at line 864 of file qspinbox.cpp.
Referenced by QDefaultItemEditorFactory::createEditor().
 {
     Q_D(QDoubleSpinBox);
     d->actualMax = maximum;
     const QVariant m(d->round(maximum));
     d->setRange((d->variantCompare(d->minimum, m) < 0 ? d->minimum : m), m);
 }
setMinimum()
void QDoubleSpinBox::setMinimum (double min)
Definition at line 830 of file qspinbox.cpp.
Referenced by QDefaultItemEditorFactory::createEditor().
 {
     Q_D(QDoubleSpinBox);
     d->actualMin = minimum;
     const QVariant m(d->round(minimum));
     d->setRange(m, (d->variantCompare(d->maximum, m) > 0 ? d->maximum : m));
 }
setPrefix()
void QDoubleSpinBox::setPrefix (const QString & prefix)
Definition at line 708 of file qspinbox.cpp.
 {
     Q_D(QDoubleSpinBox);
     d->prefix = prefix;
     d->updateEdit();
 }
setRange()
void QDoubleSpinBox::setRange (double minimum, double maximum)
Convenience function to set the minimum and maximum values with a single function call.
Note: The maximum and minimum values will be rounded to match the decimals property.
setRange(minimum, maximum);
is equivalent to:
setMinimum(minimum);
setMaximum(maximum);
See also
minimum maximum
Definition at line 886 of file qspinbox.cpp.
Referenced by setDecimals().
 {
     Q_D(QDoubleSpinBox);
     d->actualMin = minimum;
     d->actualMax = maximum;
     d->setRange(QVariant(d->round(minimum)), QVariant(d->round(maximum)));
 }
setSingleStep()
void QDoubleSpinBox::setSingleStep (double val)
Definition at line 794 of file qspinbox.cpp.
 {
     Q_D(QDoubleSpinBox);
     if (value >= 0) {
         d->singleStep = value;
         d->updateEdit();
     }
 }
setSuffix()
void QDoubleSpinBox::setSuffix (const QString & suffix)
Definition at line 745 of file qspinbox.cpp.
 {
     Q_D(QDoubleSpinBox);
     d->suffix = suffix;
     d->updateEdit();
     d->cachedSizeHint = QSize();
     updateGeometry();
 }
setValue
void QDoubleSpinBox::setValue (double val) slot
Definition at line 673 of file qspinbox.cpp.
Referenced by setDecimals().
 {
     Q_D(QDoubleSpinBox);
     QVariant v(d->round(value));
     d->setValue(v, EmitIfChanged);
 }
singleStep()
double QDoubleSpinBox::singleStep () const
Referenced by QDoubleSpinBoxPrivate::QDoubleSpinBoxPrivate(), QSpinBoxPrivate::QSpinBoxPrivate(), and setSuffix().
suffix()
QString QDoubleSpinBox::suffix () const
Referenced by setPrefix(), setSuffix(), QSpinBoxPrivate::validateAndInterpret(), and QDoubleSpinBoxPrivate::validateAndInterpret().
textFromValue()
QString QDoubleSpinBox::textFromValue (double value) const virtual
This virtual function is used by the spin box whenever it needs to display the given value.
The default implementation returns a string containing value printed using QWidget::locale().toString(value, QLatin1Char('f'), decimals()) and will remove the thousand separator. Reimplementations may return anything.
Note: QDoubleSpinBox does not call this function for specialValueText() and that neither prefix() nor suffix() should be included in the return value.
If you reimplement this, you may also need to reimplement valueFromText().
See also
valueFromText(), QLocale::groupSeparator()
Definition at line 946 of file qspinbox.cpp.
Referenced by QAccessibleDoubleSpinBox::text().
 {
     Q_D(const QDoubleSpinBox);
     QString str = locale().toString(value, 'f', d->decimals);
     if (qAbs(value) >= 1000.0) {
         str.remove(locale().groupSeparator());
     }
     return str;
 }
validate()
QValidator::State QDoubleSpinBox::validate (QString & input, int & pos) const virtual
Reimplemented Function
Reimplemented from QAbstractSpinBox.
Definition at line 981 of file qspinbox.cpp.
 {
     Q_D(const QDoubleSpinBox);
     QValidator::State state;
     d->validateAndInterpret(text, pos, state);
     return state;
 }
value()
double QDoubleSpinBox::value () const
Referenced by QSpinBoxPrivate::emitSignals(), QDoubleSpinBoxPrivate::emitSignals(), QDoubleSpinBox(), QDoubleSpinBoxPrivate::QDoubleSpinBoxPrivate(), QSpinBoxPrivate::QSpinBoxPrivate(), setDecimals(), and setSingleStep().
valueChanged [1/2]
void QDoubleSpinBox::valueChanged (double d) signal
This signal is emitted whenever the spin box's value is changed.
The new value is passed in d.
valueChanged [2/2]
void QDoubleSpinBox::valueChanged (const QString & text) signal
The new value is passed literally in text with no prefix() or suffix().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
valueFromText()
double QDoubleSpinBox::valueFromText (const QString & text) const virtual
This virtual function is used by the spin box whenever it needs to interpret text entered by the user as a value.
Subclasses that need to display spin box values in a non-numeric way need to reimplement this function.
Note: QDoubleSpinBox handles specialValueText() separately; this function is only concerned with the other values.
See also
textFromValue(), validate()
Definition at line 968 of file qspinbox.cpp.
 {
     Q_D(const QDoubleSpinBox);
     QString copy = text;
     int pos = d->edit->cursorPosition();
     QValidator::State state = QValidator::Acceptable;
     return d->validateAndInterpret(copy, pos, state).toDouble();
 }
Properties
cleanText
QString QDoubleSpinBox::cleanText private
the text of the spin box excluding any prefix, suffix, or leading or trailing whitespace.
See also
text, QDoubleSpinBox::prefix, QDoubleSpinBox::suffix
Definition at line 132 of file qspinbox.h.
decimals
int QDoubleSpinBox::decimals private
the precision of the spin box, in decimals
Sets how many decimals the spinbox will use for displaying and interpreting doubles.
Warning
The maximum value for decimals is DBL_MAX_10_EXP + DBL_DIG (ie. 323) because of the limitations of the double type.
Note: The maximum, minimum and value might change as a result of changing this property.
Definition at line 133 of file qspinbox.h.
maximum
double QDoubleSpinBox::maximum private
the maximum value of the spin box
When setting this property the minimum is adjusted if necessary, to ensure that the range remains valid.
The default maximum value is 99.99.
Note: The maximum value will be rounded to match the decimals property.
See also
decimals, setRange()
Definition at line 135 of file qspinbox.h.
minimum
double QDoubleSpinBox::minimum private
the minimum value of the spin box
When setting this property the maximum is adjusted if necessary to ensure that the range remains valid.
The default minimum value is 0.0.
Note: The minimum value will be rounded to match the decimals property.
See also
decimals, setRange() specialValueText
Definition at line 134 of file qspinbox.h.
prefix
QString QDoubleSpinBox::prefix private
the spin box's prefix
The prefix is prepended to the start of the displayed value. Typical use is to display a unit of measurement or a currency symbol. For example:
spinbox->setPrefix("$");
To turn off the prefix display, set this property to an empty string. The default is no prefix. The prefix is not displayed when value() == minimum() and specialValueText() is set.
If no prefix is set, prefix() returns an empty string.
See also
suffix(), setSuffix(), specialValueText(), setSpecialValueText()
Definition at line 130 of file qspinbox.h.
singleStep
double QDoubleSpinBox::singleStep private
the step value
When the user uses the arrows to change the spin box's value the value will be incremented/decremented by the amount of the singleStep. The default value is 1.0. Setting a singleStep value of less than 0 does nothing.
Definition at line 136 of file qspinbox.h.
suffix
QString QDoubleSpinBox::suffix private
the suffix of the spin box
The suffix is appended to the end of the displayed value. Typical use is to display a unit of measurement or a currency symbol. For example:
spinbox->setSuffix(" km");
To turn off the suffix display, set this property to an empty string. The default is no suffix. The suffix is not displayed for the minimum() if specialValueText() is set.
If no suffix is set, suffix() returns an empty string.
See also
prefix(), setPrefix(), specialValueText(), setSpecialValueText()
Definition at line 131 of file qspinbox.h.
value
double QDoubleSpinBox::value private
the value of the spin box
setValue() will emit valueChanged() if the new value is different from the old one.
Note: The value will be rounded so it can be displayed with the current setting of decimals.
See also
decimals
Definition at line 137 of file qspinbox.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qspinbox.h
/src/gui/widgets/qspinbox.cpp