Qt 4.8: QTreeWidget Class Reference
QTreeWidget Class Reference
The QTreeWidget class provides a tree view that uses a predefined tree model.
#include <qtreewidget.h>
Public Slots
void clear ()
Clears the tree widget by removing all of its items and selections.
void collapseItem (const QTreeWidgetItem *item)
Closes the item.
void expandItem (const QTreeWidgetItem *item)
Expands the item.
void scrollToItem (const QTreeWidgetItem *item, QAbstractItemView::ScrollHint hint=EnsureVisible)
Ensures that the item is visible, scrolling the view if necessary using the specified hint.
Public Slots inherited from QTreeView
void collapse (const QModelIndex &index)
Collapses the model item specified by the index.
void collapseAll ()
Collapses all expanded items.
void expand (const QModelIndex &index)
Expands the model item specified by the index.
void expandAll ()
Expands all expandable items.
void expandToDepth (int depth)
Expands all expandable items to the given depth.
void hideColumn (int column)
Hides the column given.
void resizeColumnToContents (int column)
Resizes the column given to the size of its contents.
void showColumn (int column)
Shows the given column in the tree view.
void sortByColumn (int column)
Sorts the model by the values in the given column.
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentItemChanged (QTreeWidgetItem *current, QTreeWidgetItem *previous)
This signal is emitted when the current item changes.
void itemActivated (QTreeWidgetItem *item, int column)
This signal is emitted when the user activates an item by single- or double-clicking (depending on the platform, i.e.
void itemChanged (QTreeWidgetItem *item, int column)
This signal is emitted when the contents of the column in the specified item changes.
void itemClicked (QTreeWidgetItem *item, int column)
This signal is emitted when the user clicks inside the widget.
void itemCollapsed (QTreeWidgetItem *item)
This signal is emitted when the specified item is collapsed so that none of its children are displayed.
void itemDoubleClicked (QTreeWidgetItem *item, int column)
This signal is emitted when the user double clicks inside the widget.
void itemEntered (QTreeWidgetItem *item, int column)
This signal is emitted when the mouse cursor enters an item over the specified column.
void itemExpanded (QTreeWidgetItem *item)
This signal is emitted when the specified item is expanded so that all of its children are displayed.
void itemPressed (QTreeWidgetItem *item, int column)
This signal is emitted when the user presses a mouse button inside the widget.
void itemSelectionChanged ()
This signal is emitted when the selection changes in the tree widget.
Signals inherited from QTreeView
void collapsed (const QModelIndex &index)
This signal is emitted when the item specified by index is collapsed.
void expanded (const QModelIndex &index)
This signal is emitted when the item specified by index is expanded.
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addTopLevelItem (QTreeWidgetItem *item)
Appends the item as a top-level item in the widget.
void addTopLevelItems (const QList< QTreeWidgetItem *> &items)
Appends the list of items as a top-level items in the widget.
void closePersistentEditor (QTreeWidgetItem *item, int column=0)
Closes the persistent editor for the item in the given column.
int columnCount () const
int currentColumn () const
Returns the current column in the tree widget.
QTreeWidgetItem * currentItem () const
Returns the current item in the tree widget.
void editItem (QTreeWidgetItem *item, int column=0)
Starts editing the item in the given column if it is editable.
QList< QTreeWidgetItem * > findItems (const QString &text, Qt::MatchFlags flags, int column=0) const
Returns a list of items that match the given text, using the given flags, in the given column.
QTreeWidgetItem * headerItem () const
Returns the item used for the tree widget's header.
int indexOfTopLevelItem (QTreeWidgetItem *item)
int indexOfTopLevelItem (QTreeWidgetItem *item) const
Returns the index of the given top-level item, or -1 if the item cannot be found.
void insertTopLevelItem (int index, QTreeWidgetItem *item)
Inserts the item at index in the top level in the view.
void insertTopLevelItems (int index, const QList< QTreeWidgetItem *> &items)
Inserts the list of items at index in the top level in the view.
QTreeWidgetItem * invisibleRootItem () const
Returns the tree widget's invisible root item.
bool isFirstItemColumnSpanned (const QTreeWidgetItem *item) const
Returns true if the given item is set to show only one section over all columns; otherwise returns false.
bool isItemExpanded (const QTreeWidgetItem *item) const
Returns true if the given item is open; otherwise returns false.
bool isItemHidden (const QTreeWidgetItem *item) const
Returns true if the item is explicitly hidden, otherwise returns false.
bool isItemSelected (const QTreeWidgetItem *item) const
Returns true if the item is selected; otherwise returns false.
bool isSortingEnabled () const
QTreeWidgetItem * itemAbove (const QTreeWidgetItem *item) const
Returns the item above the given item.
QTreeWidgetItem * itemAt (const QPoint &p) const
Returns a pointer to the item at the coordinates p.
QTreeWidgetItem * itemAt (int x, int y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns a pointer to the item at the coordinates (x, y).
QTreeWidgetItem * itemBelow (const QTreeWidgetItem *item) const
Returns the item visually below the given item.
QWidget * itemWidget (QTreeWidgetItem *item, int column) const
Returns the widget displayed in the cell specified by item and the given column.
void openPersistentEditor (QTreeWidgetItem *item, int column=0)
Opens a persistent editor for the item in the given column.
QTreeWidget (QWidget *parent=0)
Constructs a tree widget with the given parent.
void removeItemWidget (QTreeWidgetItem *item, int column)
QList< QTreeWidgetItem * > selectedItems () const
Returns a list of all selected non-hidden items.
void setColumnCount (int columns)
void setCurrentItem (QTreeWidgetItem *item)
Sets the current item in the tree widget.
void setCurrentItem (QTreeWidgetItem *item, int column)
Sets the current item in the tree widget and the current column to column.
void setCurrentItem (QTreeWidgetItem *item, int column, QItemSelectionModel::SelectionFlags command)
Sets the current item in the tree widget and the current column to column, using the given command.
void setFirstItemColumnSpanned (const QTreeWidgetItem *item, bool span)
Sets the given item to only show one section for all columns if span is true; otherwise the item will show one section per column.
void setHeaderItem (QTreeWidgetItem *item)
Sets the header item for the tree widget.
void setHeaderLabel (const QString &label)
Same as setHeaderLabels(QStringList(label)).
void setHeaderLabels (const QStringList &labels)
Adds a column in the header for each item in the labels list, and sets the label for each column.
void setItemExpanded (const QTreeWidgetItem *item, bool expand)
Sets the item referred to by item to either closed or opened, depending on the value of expand.
void setItemHidden (const QTreeWidgetItem *item, bool hide)
Hides the given item if hide is true; otherwise shows the item.
void setItemSelected (const QTreeWidgetItem *item, bool select)
If select is true, the given item is selected; otherwise it is deselected.
void setItemWidget (QTreeWidgetItem *item, int column, QWidget *widget)
Sets the given widget to be displayed in the cell specified by the given item and column.
void setSelectionModel (QItemSelectionModel *selectionModel)
Reimplemented Function
void setSortingEnabled (bool enable)
int sortColumn () const
Returns the column used to sort the contents of the widget.
void sortItems (int column, Qt::SortOrder order)
Sorts the items in the widget in the specified order by the values in the given column.
QTreeWidgetItem * takeTopLevelItem (int index)
Removes the top-level item at the given index in the tree and returns it, otherwise returns 0;.
QTreeWidgetItem * topLevelItem (int index) const
Returns the top level item at the given index, or 0 if the item does not exist.
int topLevelItemCount () const
QRect visualItemRect (const QTreeWidgetItem *item) const
Returns the rectangle on the viewport occupied by the item at item.
~QTreeWidget ()
Destroys the tree widget and all its items.
Public Functions inherited from QTreeView
bool allColumnsShowFocus () const
int autoExpandDelay () const
int columnAt (int x) const
Returns the column in the tree view whose header covers the x coordinate given.
int columnViewportPosition (int column) const
Returns the horizontal position of the column in the viewport.
int columnWidth (int column) const
Returns the width of the column.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Reimplemented Function
void doItemsLayout ()
Lays out the items in the tree view.
bool expandsOnDoubleClick () const
QHeaderView * header () const
Returns the header for the tree view.
int indentation () const
QModelIndex indexAbove (const QModelIndex &index) const
Returns the model index of the item above index.
QModelIndex indexAt (const QPoint &p) const
Reimplemented Function
QModelIndex indexBelow (const QModelIndex &index) const
Returns the model index of the item below index.
bool isAnimated () const
bool isColumnHidden (int column) const
Returns true if the column is hidden; otherwise returns false.
bool isExpanded (const QModelIndex &index) const
Returns true if the model item index is expanded; otherwise returns false.
bool isFirstColumnSpanned (int row, const QModelIndex &parent) const
Returns true if the item in first column in the given row of the parent is spanning all the columns; otherwise returns false.
bool isHeaderHidden () const
bool isRowHidden (int row, const QModelIndex &parent) const
Returns true if the item in the given row of the parent is hidden; otherwise returns false.
bool isSortingEnabled () const
bool itemsExpandable () const
void keyboardSearch (const QString &search)
Reimplemented Function
QTreeView (QWidget *parent=0)
Constructs a tree view with a parent to represent a model's data.
void reset ()
Reimplemented Function
bool rootIsDecorated () const
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Scroll the contents of the tree view until the given model item index is visible.
void selectAll ()
Reimplemented Function
void setAllColumnsShowFocus (bool enable)
void setAnimated (bool enable)
void setAutoExpandDelay (int delay)
void setColumnHidden (int column, bool hide)
If hide is true the column is hidden, otherwise the column is shown.
void setColumnWidth (int column, int width)
Sets the width of the given column to the width specified.
void setExpanded (const QModelIndex &index, bool expand)
Sets the item referred to by index to either collapse or expanded, depending on the value of expanded.
void setExpandsOnDoubleClick (bool enable)
void setFirstColumnSpanned (int row, const QModelIndex &parent, bool span)
If span is true the item in the first column in the row with the given parent is set to span all columns, otherwise all items on the row are shown.
void setHeader (QHeaderView *header)
Sets the header for the tree view, to the given header.
void setHeaderHidden (bool hide)
void setIndentation (int i)
void setItemsExpandable (bool enable)
void setRootIndex (const QModelIndex &index)
Reimplemented Function
void setRootIsDecorated (bool show)
void setRowHidden (int row, const QModelIndex &parent, bool hide)
If hide is true the row with the given parent is hidden, otherwise the row is shown.
void setSortingEnabled (bool enable)
void setUniformRowHeights (bool uniform)
void setWordWrap (bool on)
void sortByColumn (int column, Qt::SortOrder order)
Sets the model up for sorting by the values in the given column and order.
bool uniformRowHeights () const
QRect visualRect (const QModelIndex &index) const
Returns the rectangle on the viewport occupied by the item at index.
bool wordWrap () const
~QTreeView ()
Destroys the tree view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void dropEvent (QDropEvent *event)
Reimplemented Function
virtual bool dropMimeData (QTreeWidgetItem *parent, int index, const QMimeData *data, Qt::DropAction action)
Handles the data supplied by a drag and drop operation that ended with the given action in the index in the given parent item.
bool event (QEvent *e)
Reimplemented Function
QModelIndex indexFromItem (QTreeWidgetItem *item, int column=0) const
Returns the QModelIndex assocated with the given item in the given column.
QTreeWidgetItem * itemFromIndex (const QModelIndex &index) const
Returns a pointer to the QTreeWidgetItem assocated with the given index.
QList< QTreeWidgetItem * > items (const QMimeData *data) const
virtual QMimeData * mimeData (const QList< QTreeWidgetItem *> items) const
Returns an object that contains a serialized description of the specified items.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of treewidget items.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this view.
Protected Functions inherited from QTreeView
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
void dragMoveEvent (QDragMoveEvent *event)
Reimplemented Function
virtual void drawBranches (QPainter *painter, const QRect &rect, const QModelIndex &index) const
Draws the branches in the tree view on the same row as the model item index, using the painter given.
virtual void drawRow (QPainter *painter, const QStyleOptionViewItem &options, const QModelIndex &index) const
Draws the row in the tree view that contains the model item index, using the painter given.
void drawTree (QPainter *painter, const QRegion &region) const
Draws the part of the tree intersecting the given region using the specified painter.
int horizontalOffset () const
Returns the horizontal offset of the items in the treeview.
void horizontalScrollbarAction (int action)
int indexRowSizeHint (const QModelIndex &index) const
Returns the size hint for the row indicated by index.
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void mouseDoubleClickEvent (QMouseEvent *event)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Move the cursor in the way described by cursorAction, using the information provided by the button modifiers.
void paintEvent (QPaintEvent *event)
Reimplemented Function
QTreeView (QTreeViewPrivate &dd, QWidget *parent=0)
int rowHeight (const QModelIndex &index) const
Returns the height of the row indicated by the given index.
void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
Informs the view that the rows from the start row to the end row inclusive are about to removed from the given parent model item.
void rowsInserted (const QModelIndex &parent, int start, int end)
Informs the view that the rows from the start row to the end row inclusive have been inserted into the parent model item.
void scrollContentsBy (int dx, int dy)
Scrolls the contents of the tree view by (dx, dy).
QModelIndexList selectedIndexes () const
Reimplemented Function
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Reimplemented Function
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Applies the selection command to the items in or touched by the rectangle, rect.
int sizeHintForColumn (int column) const
Returns the size hint for the column's width or -1 if there is no model.
void timerEvent (QTimerEvent *event)
Reimplemented Function
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Returns the vertical offset of the items in the tree view.
bool viewportEvent (QEvent *event)
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Returns the rectangle from the viewport of the items in the given selection.
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
This function is called with the given event when a resize event is sent to the widget.
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
virtual QStyleOptionViewItem viewOptions () const
Returns a QStyleOptionViewItem structure populated with the view's palette, font, state, alignments etc.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void setModel (QAbstractItemModel *model)
Reimplemented Function
Properties
int columnCount
the number of columns displayed in the tree widget
int topLevelItemCount
the number of top-level items
Friends
class QTreeModel
class QTreeWidgetItem
Additional Inherited Members
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Slots inherited from QTreeView
void columnCountChanged (int oldCount, int newCount)
Informs the tree view that the number of columns in the tree view has changed from oldCount to newCount.
void columnMoved ()
This slot is called whenever a column has been moved.
void columnResized (int column, int oldSize, int newSize)
This function is called whenever {column}'s size is changed in the header.
void reexpand ()
void rowsRemoved (const QModelIndex &parent, int first, int last)
Informs the view that the rows from the start row to the end row inclusive have been removed from the given parent model item.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarValueChanged (int value)
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTreeWidget class provides a tree view that uses a predefined tree model.
The QTreeWidget class is a convenience class that provides a standard tree widget with a classic item-based interface similar to that used by the QListView class in Qt 3. This class is based on Qt's Model/View architecture and uses a default model to hold items, each of which is a QTreeWidgetItem.
Developers who do not need the flexibility of the Model/View framework can use this class to create simple hierarchical lists very easily. A more flexible approach involves combining a QTreeView with a standard item model. This allows the storage of data to be separated from its representation.
In its simplest form, a tree widget can be constructed in the following way:
QTreeWidget *treeWidget = new QTreeWidget();
treeWidget->setColumnCount(1);
QList<QTreeWidgetItem *> items;
for (int i = 0; i < 10; ++i)
    items.append(new QTreeWidgetItem((QTreeWidget*)0, QStringList(QString("item: %1").arg(i))));
treeWidget->insertTopLevelItems(0, items);
Before items can be added to the tree widget, the number of columns must be set with setColumnCount(). This allows each item to have one or more labels or other decorations. The number of columns in use can be found with the columnCount() function.
The tree can have a header that contains a section for each column in the widget. It is easiest to set up the labels for each section by supplying a list of strings with setHeaderLabels(), but a custom header can be constructed with a QTreeWidgetItem and inserted into the tree with the setHeaderItem() function.
The items in the tree can be sorted by column according to a predefined sort order. If sorting is enabled, the user can sort the items by clicking on a column header. Sorting can be enabled or disabled by calling setSortingEnabled(). The isSortingEnabled() function indicates whether sorting is enabled.
Screenshot of a Windows XP style tree widget
Screenshot of a Macintosh style tree widget
Screenshot of a Plastique style tree widget
A Windows XP Style Widget Gallery{Windows XP style} tree widget. A Macintosh Style Widget Gallery{Macintosh style} tree widget. A Plastique Style Widget Gallery{Plastique style} tree widget.
See also
QTreeWidgetItem, QTreeWidgetItemIterator, QTreeView, {Model/View Programming}, {Settings Editor Example}
Definition at line 260 of file qtreewidget.h.
Constructors and Destructors
QTreeWidget()
QTreeWidget::QTreeWidget (QWidget * parent = 0) explicit
Constructs a tree widget with the given parent.
Definition at line 2733 of file qtreewidget.cpp.
     : QTreeView(*new QTreeWidgetPrivate(), parent)
 {
     QTreeView::setModel(new QTreeModel(1, this));
     connect(this, SIGNAL(pressed(QModelIndex)),
             SLOT(_q_emitItemPressed(QModelIndex)));
     connect(this, SIGNAL(clicked(QModelIndex)),
             SLOT(_q_emitItemClicked(QModelIndex)));
     connect(this, SIGNAL(doubleClicked(QModelIndex)),
             SLOT(_q_emitItemDoubleClicked(QModelIndex)));
     connect(this, SIGNAL(activated(QModelIndex)),
             SLOT(_q_emitItemActivated(QModelIndex)));
     connect(this, SIGNAL(entered(QModelIndex)),
             SLOT(_q_emitItemEntered(QModelIndex)));
     connect(this, SIGNAL(expanded(QModelIndex)),
             SLOT(_q_emitItemExpanded(QModelIndex)));
     connect(this, SIGNAL(collapsed(QModelIndex)),
             SLOT(_q_emitItemCollapsed(QModelIndex)));
     connect(selectionModel(), SIGNAL(currentChanged(QModelIndex,QModelIndex)),
             this, SLOT(_q_emitCurrentItemChanged(QModelIndex,QModelIndex)));
     connect(model(), SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(_q_emitItemChanged(QModelIndex)));
     connect(model(), SIGNAL(dataChanged(QModelIndex,QModelIndex)),
             this, SLOT(_q_dataChanged(QModelIndex,QModelIndex)));
     connect(model(), SIGNAL(columnsRemoved(QModelIndex,int,int)),
             this, SLOT(_q_sort()));
     connect(selectionModel(), SIGNAL(selectionChanged(QItemSelection,QItemSelection)),
             this, SLOT(_q_selectionChanged(QItemSelection,QItemSelection)));
     header()->setClickable(false);
 }
~QTreeWidget()
QTreeWidget::~QTreeWidget ()
Destroys the tree widget and all its items.
Definition at line 2768 of file qtreewidget.cpp.
 {
 }
Functions
addTopLevelItem()
void QTreeWidget::addTopLevelItem (QTreeWidgetItem * item)
Appends the item as a top-level item in the widget.
Since
4.1
See also
insertTopLevelItem()
Definition at line 2871 of file qtreewidget.cpp.
 {
     insertTopLevelItem(topLevelItemCount(), item);
 }
addTopLevelItems()
void QTreeWidget::addTopLevelItems (const QList< QTreeWidgetItem *> & items)
Appends the list of items as a top-level items in the widget.
See also
insertTopLevelItems()
Definition at line 2935 of file qtreewidget.cpp.
 {
     insertTopLevelItems(topLevelItemCount(), items);
 }
clear
void QTreeWidget::clear () slot
Clears the tree widget by removing all of its items and selections.
Note: Since each item is removed from the tree widget before being deleted, the return value of QTreeWidgetItem::treeWidget() will be invalid when called from an item's destructor.
See also
takeTopLevelItem(), topLevelItemCount(), columnCount()
Definition at line 3540 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     selectionModel()->clear();
     d->treeModel()->clear();
 }
closePersistentEditor()
void QTreeWidget::closePersistentEditor (QTreeWidgetItem * item, int column = 0)
Closes the persistent editor for the item in the given column.
This function has no effect if no persistent editor is open for this combination of item and column.
See also
openPersistentEditor()
Definition at line 3203 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QAbstractItemView::closePersistentEditor(d->index(item, column));
 }
collapseItem
void QTreeWidget::collapseItem (const QTreeWidgetItem * item) slot
Closes the item.
This causes the tree containing the item's children to be collapsed.
See also
expandItem(), currentItem(), itemAt(), topLevelItem()
Definition at line 3524 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QTreeModel::SkipSorting skipSorting(d->treeModel());
     collapse(d->index(item));
 }
columnCount()
int QTreeWidget::columnCount () const
Referenced by setHeaderItem(), setHeaderLabels(), and ~QTreeWidget().
currentColumn()
int QTreeWidget::currentColumn () const
Returns the current column in the tree widget.
Since
4.1
See also
setCurrentItem(), columnCount()
Definition at line 3031 of file qtreewidget.cpp.
 {
     return currentIndex().column();
 }
currentItem()
QTreeWidgetItem * QTreeWidget::currentItem () const
Returns the current item in the tree widget.
See also
setCurrentItem(), currentItemChanged()
Definition at line 3016 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     return d->item(currentIndex());
 }
currentItemChanged
void QTreeWidget::currentItemChanged (QTreeWidgetItem * current, QTreeWidgetItem * previous) signal
This signal is emitted when the current item changes.
The current item is specified by current, and this replaces the previous current item.
See also
setCurrentItem()
dropEvent()
void QTreeWidget::dropEvent (QDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3646 of file qtreewidget.cpp.
{
     Q_D(QTreeWidget);
     if (event->source() == this && (event->dropAction() == Qt::MoveAction ||
                                     dragDropMode() == QAbstractItemView::InternalMove)) {
         QModelIndex topIndex;
         int col = -1;
         int row = -1;
         if (d->dropOn(event, &row, &col, &topIndex)) {
             QList<QModelIndex> idxs = selectedIndexes();
             QList<QPersistentModelIndex> indexes;
             for (int i = 0; i < idxs.count(); i++)
                 indexes.append(idxs.at(i));
             if (indexes.contains(topIndex))
                 return;
             // When removing items the drop location could shift
             QPersistentModelIndex dropRow = model()->index(row, col, topIndex);
             // Remove the items
             QList<QTreeWidgetItem *> taken;
             for (int i = indexes.count() - 1; i >= 0; --i) {
                 QTreeWidgetItem *parent = itemFromIndex(indexes.at(i));
                 if (!parent || !parent->parent()) {
                     taken.append(takeTopLevelItem(indexes.at(i).row()));
                 } else {
                     taken.append(parent->parent()->takeChild(indexes.at(i).row()));
                 }
             }
             // insert them back in at their new positions
             for (int i = 0; i < indexes.count(); ++i) {
                 // Either at a specific point or appended
                 if (row == -1) {
                     if (topIndex.isValid()) {
                         QTreeWidgetItem *parent = itemFromIndex(topIndex);
                         parent->insertChild(parent->childCount(), taken.takeFirst());
                     } else {
                         insertTopLevelItem(topLevelItemCount(), taken.takeFirst());
                     }
                 } else {
                     int r = dropRow.row() >= 0 ? dropRow.row() : row;
                     if (topIndex.isValid()) {
                         QTreeWidgetItem *parent = itemFromIndex(topIndex);
                         parent->insertChild(qMin(r, parent->childCount()), taken.takeFirst());
                     } else {
                         insertTopLevelItem(qMin(r, topLevelItemCount()), taken.takeFirst());
                     }
                 }
             }
             event->accept();
             // Don't want QAbstractItemView to delete it because it was "moved" we already did it
             event->setDropAction(Qt::CopyAction);
         }
     }
     QTreeView::dropEvent(event);
 }
dropMimeData()
bool QTreeWidget::dropMimeData (QTreeWidgetItem * parent, int index, const QMimeData * data, Qt::DropAction action) protected virtual
Handles the data supplied by a drag and drop operation that ended with the given action in the index in the given parent item.
The default implementation returns true if the drop was successfully handled by decoding the mime data and inserting it into the model; otherwise it returns false.
See also
supportedDropActions()
Definition at line 3592 of file qtreewidget.cpp.
Referenced by QTreeModel::dropMimeData().
 {
     QModelIndex idx;
     if (parent) idx = indexFromItem(parent);
     return model()->QAbstractItemModel::dropMimeData(data, action , index, 0, idx);
 }
editItem()
void QTreeWidget::editItem (QTreeWidgetItem * item, int column = 0)
Starts editing the item in the given column if it is editable.
Definition at line 3176 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     edit(d->index(item, column));
 }
event()
bool QTreeWidget::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3719 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     if (e->type() == QEvent::Polish)
         d->treeModel()->executePendingSort();
     return QTreeView::event(e);
 }
expandItem
void QTreeWidget::expandItem (const QTreeWidgetItem * item) slot
Expands the item.
This causes the tree containing the item's children to be expanded.
See also
collapseItem(), currentItem(), itemAt(), topLevelItem(), itemExpanded()
Definition at line 3511 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QTreeModel::SkipSorting skipSorting(d->treeModel());
     expand(d->index(item));
 }
findItems()
QList< QTreeWidgetItem * > QTreeWidget::findItems (const QString & text, Qt::MatchFlags flags, int column = 0) const
Returns a list of items that match the given text, using the given flags, in the given column.
Definition at line 3323 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     QModelIndexList indexes = d->model->match(model()->index(0, column, QModelIndex()),
                                                 Qt::DisplayRole, text, -1, flags);
     QList<QTreeWidgetItem*> items;
     for (int i = 0; i < indexes.size(); ++i)
         items.append(d->item(indexes.at(i)));
     return items;
 }
headerItem()
QTreeWidgetItem * QTreeWidget::headerItem () const
Returns the item used for the tree widget's header.
See also
setHeaderItem()
Definition at line 2946 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     return d->treeModel()->headerItem;
 }
indexFromItem()
QModelIndex QTreeWidget::indexFromItem (QTreeWidgetItem * item, int column = 0) const protected
Returns the QModelIndex assocated with the given item in the given column.
See also
itemFromIndex(), topLevelItem()
Definition at line 3627 of file qtreewidget.cpp.
Referenced by dropMimeData(), and mimeData().
 {
     Q_D(const QTreeWidget);
     return d->index(item, column);
 }
indexOfTopLevelItem() [1/2]
int QTreeWidget::indexOfTopLevelItem (QTreeWidgetItem * item)
Warning
This function is not part of the public interface.
Definition at line 2892 of file qtreewidget.cpp.
Referenced by QTreeWidgetItemIteratorPrivate::ensureValidIterator(), and QTreeWidgetItemIteratorPrivate::nextSibling().
 {
     Q_D(QTreeWidget);
     d->treeModel()->executePendingSort();
     return d->treeModel()->rootItem->children.indexOf(item);
 }
indexOfTopLevelItem() [2/2]
int QTreeWidget::indexOfTopLevelItem (QTreeWidgetItem * item) const
Returns the index of the given top-level item, or -1 if the item cannot be found.
See also
sortItems(), topLevelItemCount()
Definition at line 2905 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     d->treeModel()->executePendingSort();
     return d->treeModel()->rootItem->children.indexOf(item);
 }
insertTopLevelItem()
void QTreeWidget::insertTopLevelItem (int index, QTreeWidgetItem * item)
Inserts the item at index in the top level in the view.
If the item has already been inserted somewhere else it wont be inserted.
See also
addTopLevelItem(), columnCount()
Definition at line 2855 of file qtreewidget.cpp.
Referenced by addTopLevelItem(), and dropEvent().
 {
     Q_D(QTreeWidget);
     d->treeModel()->rootItem->insertChild(index, item);
 }
insertTopLevelItems()
void QTreeWidget::insertTopLevelItems (int index, const QList< QTreeWidgetItem *> & items)
Inserts the list of items at index in the top level in the view.
Since
4.1
Items that have already been inserted somewhere else wont be inserted.
See also
addTopLevelItems()
Definition at line 2924 of file qtreewidget.cpp.
Referenced by addTopLevelItems().
 {
     Q_D(QTreeWidget);
     d->treeModel()->rootItem->insertChildren(index, items);
 }
invisibleRootItem()
QTreeWidgetItem * QTreeWidget::invisibleRootItem () const
Returns the tree widget's invisible root item.
Since
4.2
The invisible root item provides access to the tree widget's top-level items through the QTreeWidgetItem API, making it possible to write functions that can treat top-level items and their children in a uniform way; for example, recursive functions.
Definition at line 2810 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     return d->treeModel()->rootItem;
 }
isFirstItemColumnSpanned()
bool QTreeWidget::isFirstItemColumnSpanned (const QTreeWidgetItem * item) const
Returns true if the given item is set to show only one section over all columns; otherwise returns false.
Since
4.3
See also
setFirstItemColumnSpanned()
Definition at line 3416 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::isFirstColumnSpanned().
 {
     Q_D(const QTreeWidget);
     if (item == d->treeModel()->headerItem)
         return false; // We can't set the header items to spanning
     const QModelIndex index = d->index(item);
     return isFirstColumnSpanned(index.row(), index.parent());
 }
isItemExpanded()
bool QTreeWidget::isItemExpanded (const QTreeWidgetItem * item) const
Returns true if the given item is open; otherwise returns false.
See also
itemExpanded()
This function is deprecated. Use QTreeWidgetItem::isExpanded() instead.
Definition at line 3381 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::isExpanded().
 {
     Q_D(const QTreeWidget);
     QTreeModel::SkipSorting skipSorting(d->treeModel());
     return isExpanded(d->index(item));
 }
isItemHidden()
bool QTreeWidget::isItemHidden (const QTreeWidgetItem * item) const
Returns true if the item is explicitly hidden, otherwise returns false.
This function is deprecated. Use QTreeWidgetItem::isHidden() instead.
Definition at line 3341 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::isHidden(), and selectedItems().
 {
     Q_D(const QTreeWidget);
     if (item == d->treeModel()->headerItem)
         return header()->isHidden();
     if (d->hiddenIndexes.isEmpty())
         return false;
     QTreeModel::SkipSorting skipSorting(d->treeModel());
     return d->isRowHidden(d->index(item));
 }
isItemSelected()
bool QTreeWidget::isItemSelected (const QTreeWidgetItem * item) const
Returns true if the item is selected; otherwise returns false.
See also
itemSelectionChanged()
This function is deprecated. Use QTreeWidgetItem::isSelected() instead.
Definition at line 3267 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::isSelected().
 {
     if (!item)
         return false;
     return item->d->selected;
 }
isSortingEnabled()
bool QTreeWidget::isSortingEnabled () const
Warning
This function is not part of the public interface.
Qt 5: remove
Definition at line 3167 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::insertChild(), and QTreeWidgetItem::insertChildren().
 {
     return QTreeView::isSortingEnabled();
 }
itemAbove()
QTreeWidgetItem * QTreeWidget::itemAbove (const QTreeWidgetItem * item) const
Returns the item above the given item.
Since
4.3
Definition at line 3453 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     if (item == d->treeModel()->headerItem)
         return 0;
     const QModelIndex index = d->index(item);
     const QModelIndex above = indexAbove(index);
     return d->item(above);
 }
itemActivated
void QTreeWidget::itemActivated (QTreeWidgetItem * item, int column) signal
This signal is emitted when the user activates an item by single- or double-clicking (depending on the platform, i.e.
on the QStyle::SH_ItemView_ActivateItemOnSingleClick style hint) or pressing a special key (e.g., Enter).
The specified item is the item that was clicked, or 0 if no item was clicked. The column is the item's column that was clicked, or -1 if no item was clicked.
itemAt() [1/2]
QTreeWidgetItem * QTreeWidget::itemAt (const QPoint & p) const
Returns a pointer to the item at the coordinates p.
The coordinates are relative to the tree widget's QAbstractScrollArea::viewport().
See also
visualItemRect()
Definition at line 3088 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     return d->item(indexAt(p));
 }
itemAt() [2/2]
QTreeWidgetItem * QTreeWidget::itemAt (int x, int y) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns a pointer to the item at the coordinates (x, y).
The coordinates are relative to the tree widget's QAbstractScrollArea::viewport().
Definition at line 390 of file qtreewidget.h.
 { return itemAt(QPoint(ax, ay)); }
itemBelow()
QTreeWidgetItem * QTreeWidget::itemBelow (const QTreeWidgetItem * item) const
Returns the item visually below the given item.
Since
4.3
Definition at line 3471 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     if (item == d->treeModel()->headerItem)
         return 0;
     const QModelIndex index = d->index(item);
     const QModelIndex below = indexBelow(index);
     return d->item(below);
 }
itemChanged
void QTreeWidget::itemChanged (QTreeWidgetItem * item, int column) signal
This signal is emitted when the contents of the column in the specified item changes.
itemClicked
void QTreeWidget::itemClicked (QTreeWidgetItem * item, int column) signal
This signal is emitted when the user clicks inside the widget.
The specified item is the item that was clicked. The column is the item's column that was clicked. If no item was clicked, no signal will be emitted.
itemCollapsed
void QTreeWidget::itemCollapsed (QTreeWidgetItem * item) signal
This signal is emitted when the specified item is collapsed so that none of its children are displayed.
Note
This signal will not be emitted if an item changes its state when collapseAll() is invoked.
See also
QTreeWidgetItem::isExpanded(), itemExpanded(), collapseItem()
itemDoubleClicked
void QTreeWidget::itemDoubleClicked (QTreeWidgetItem * item, int column) signal
This signal is emitted when the user double clicks inside the widget.
The specified item is the item that was clicked, or 0 if no item was clicked. The column is the item's column that was clicked. If no item was double clicked, no signal will be emitted.
itemEntered
void QTreeWidget::itemEntered (QTreeWidgetItem * item, int column) signal
This signal is emitted when the mouse cursor enters an item over the specified column.
QTreeWidget mouse tracking needs to be enabled for this feature to work.
itemExpanded
void QTreeWidget::itemExpanded (QTreeWidgetItem * item) signal
This signal is emitted when the specified item is expanded so that all of its children are displayed.
Note
This signal will not be emitted if an item changes its state when expandAll() is invoked.
See also
QTreeWidgetItem::isExpanded(), itemCollapsed(), expandItem()
itemFromIndex()
QTreeWidgetItem * QTreeWidget::itemFromIndex (const QModelIndex & index) const protected
Returns a pointer to the QTreeWidgetItem assocated with the given index.
See also
indexFromItem()
Definition at line 3638 of file qtreewidget.cpp.
Referenced by dropEvent().
 {
     Q_D(const QTreeWidget);
     return d->item(index);
 }
itemPressed
void QTreeWidget::itemPressed (QTreeWidgetItem * item, int column) signal
This signal is emitted when the user presses a mouse button inside the widget.
The specified item is the item that was clicked, or 0 if no item was clicked. The column is the item's column that was clicked, or -1 if no item was clicked.
items()
QList< QTreeWidgetItem * > QTreeWidget::items (const QMimeData * data) const protected
See also
mimeData()
Definition at line 3616 of file qtreewidget.cpp.
Referenced by findItems(), and selectedItems().
 {
     Q_UNUSED(data);
     return QList<QTreeWidgetItem*>();
 }
itemSelectionChanged
void QTreeWidget::itemSelectionChanged () signal
This signal is emitted when the selection changes in the tree widget.
The current selection can be found with selectedItems().
itemWidget()
QWidget * QTreeWidget::itemWidget (QTreeWidgetItem * item, int column) const
Returns the widget displayed in the cell specified by item and the given column.
Since
4.1
Note
The tree takes ownership of the widget.
Definition at line 3220 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     return QAbstractItemView::indexWidget(d->index(item, column));
 }
mimeData()
QMimeData * QTreeWidget::mimeData (const QList< QTreeWidgetItem *> items) const protected virtual
Returns an object that contains a serialized description of the specified items.
The format used to describe the items is obtained from the mimeTypes() function.
If the list of items is empty, 0 is returned rather than a serialized empty list.
Definition at line 3566 of file qtreewidget.cpp.
Referenced by QTreeModel::mimeData().
 {
     Q_D(const QTreeWidget);
     if (d->treeModel()->cachedIndexes.isEmpty()) {
         QList<QModelIndex> indexes;
         for (int i = 0; i < items.count(); ++i) {
             QTreeWidgetItem *item = items.at(i);
             for (int c = 0; c < item->values.count(); ++c) {
                 indexes << indexFromItem(item, c);
             }
         }
         return d->model->QAbstractItemModel::mimeData(indexes);
     }
     return d->treeModel()->internalMimeData();
 }
mimeTypes()
QStringList QTreeWidget::mimeTypes () const protected virtual
Returns a list of MIME types that can be used to describe a list of treewidget items.
See also
mimeData()
Definition at line 3553 of file qtreewidget.cpp.
Referenced by QTreeModel::mimeTypes().
 {
     return model()->QAbstractItemModel::mimeTypes();
 }
openPersistentEditor()
void QTreeWidget::openPersistentEditor (QTreeWidgetItem * item, int column = 0)
Opens a persistent editor for the item in the given column.
See also
closePersistentEditor()
Definition at line 3188 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QAbstractItemView::openPersistentEditor(d->index(item, column));
 }
removeItemWidget()
void QTreeWidget::removeItemWidget (QTreeWidgetItem * item, int column) inline
Since
4.3
Removes the widget set in the given item in the given column.
Definition at line 387 of file qtreewidget.h.
 { setItemWidget(item, column, 0); }
scrollToItem
void QTreeWidget::scrollToItem (const QTreeWidgetItem * item, QAbstractItemView::ScrollHint hint = EnsureVisible) slot
Ensures that the item is visible, scrolling the view if necessary using the specified hint.
See also
currentItem(), itemAt(), topLevelItem()
Definition at line 3499 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QTreeView::scrollTo(d->index(item), hint);
 }
selectedItems()
QList< QTreeWidgetItem * > QTreeWidget::selectedItems () const
Returns a list of all selected non-hidden items.
See also
itemSelectionChanged()
Definition at line 3302 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     QModelIndexList indexes = selectionModel()->selectedIndexes();
     QList<QTreeWidgetItem*> items;
     items.reserve(indexes.count());
     QSet<QTreeWidgetItem *> seen;
     seen.reserve(indexes.count());
     for (int i = 0; i < indexes.count(); ++i) {
         QTreeWidgetItem *item = d->item(indexes.at(i));
         if (isItemHidden(item) || seen.contains(item))
             continue;
         seen.insert(item);
         items.append(item);
     }
     return items;
 }
setColumnCount()
void QTreeWidget::setColumnCount (int columns)
Definition at line 2788 of file qtreewidget.cpp.
Referenced by setHeaderLabels().
 {
     Q_D(QTreeWidget);
     if (columns < 0)
         return;
     d->treeModel()->setColumnCount(columns);
 }
setCurrentItem() [1/3]
void QTreeWidget::setCurrentItem (QTreeWidgetItem * item)
Sets the current item in the tree widget.
Unless the selection mode is QAbstractItemView::NoSelection, the item is also be selected.
See also
currentItem(), currentItemChanged()
Definition at line 3044 of file qtreewidget.cpp.
 {
     setCurrentItem(item, 0);
 }
setCurrentItem() [2/3]
void QTreeWidget::setCurrentItem (QTreeWidgetItem * item, int column)
Sets the current item in the tree widget and the current column to column.
Since
4.1
See also
currentItem()
Definition at line 3058 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     setCurrentIndex(d->index(item, column));
 }
setCurrentItem() [3/3]
void QTreeWidget::setCurrentItem (QTreeWidgetItem * item, int column, QItemSelectionModel::SelectionFlags command)
Sets the current item in the tree widget and the current column to column, using the given command.
Since
4.4
See also
currentItem()
Definition at line 3074 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     d->selectionModel->setCurrentIndex(d->index(item, column), command);
 }
setFirstItemColumnSpanned()
void QTreeWidget::setFirstItemColumnSpanned (const QTreeWidgetItem * item, bool span)
Sets the given item to only show one section for all columns if span is true; otherwise the item will show one section per column.
Since
4.3
See also
isFirstItemColumnSpanned()
Definition at line 3436 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::setFirstColumnSpanned().
 {
     Q_D(QTreeWidget);
     if (item == d->treeModel()->headerItem)
         return; // We can't set header items to spanning
     const QModelIndex index = d->index(item);
     setFirstColumnSpanned(index.row(), index.parent(), span);
 }
setHeaderItem()
void QTreeWidget::setHeaderItem (QTreeWidgetItem * item)
Sets the header item for the tree widget.
The label for each column in the header is supplied by the corresponding label in the item.
The tree widget takes ownership of the item.
See also
headerItem(), setHeaderLabels()
Definition at line 2961 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     if (!item)
         return;
     item->view = this;
     int oldCount = columnCount();
     if (oldCount < item->columnCount())
          d->treeModel()->beginInsertColumns(QModelIndex(), oldCount, item->columnCount());
     else
          d->treeModel()->beginRemoveColumns(QModelIndex(), item->columnCount(), oldCount);
     delete d->treeModel()->headerItem;
     d->treeModel()->headerItem = item;
     if (oldCount < item->columnCount())
         d->treeModel()->endInsertColumns();
     else
         d->treeModel()->endRemoveColumns();
     d->treeModel()->headerDataChanged(Qt::Horizontal, 0, oldCount);
 }
setHeaderLabel()
void QTreeWidget::setHeaderLabel (const QString & label) inline
Same as setHeaderLabels(QStringList(label)).
Since
4.2
Definition at line 393 of file qtreewidget.h.
 { setHeaderLabels(QStringList(alabel)); }
setHeaderLabels()
void QTreeWidget::setHeaderLabels (const QStringList & labels)
Adds a column in the header for each item in the labels list, and sets the label for each column.
Note that setHeaderLabels() won't remove existing columns.
See also
setHeaderItem(), setHeaderLabel()
Definition at line 2991 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     if (columnCount() < labels.count())
         setColumnCount(labels.count());
     QTreeWidgetItem *item = d->treeModel()->headerItem;
     for (int i = 0; i < labels.count(); ++i)
         item->setText(i, labels.at(i));
 }
setItemExpanded()
void QTreeWidget::setItemExpanded (const QTreeWidgetItem * item, bool expand)
Sets the item referred to by item to either closed or opened, depending on the value of expand.
See also
expandItem(), collapseItem(), itemExpanded()
This function is deprecated. Use QTreeWidgetItem::setExpanded() instead.
Definition at line 3398 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::setExpanded().
 {
     Q_D(QTreeWidget);
     QTreeModel::SkipSorting skipSorting(d->treeModel());
     setExpanded(d->index(item), expand);
 }
setItemHidden()
void QTreeWidget::setItemHidden (const QTreeWidgetItem * item, bool hide)
Hides the given item if hide is true; otherwise shows the item.
See also
itemChanged()
This function is deprecated. Use QTreeWidgetItem::setHidden() instead.
Definition at line 3361 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::setHidden().
 {
     Q_D(QTreeWidget);
     if (item == d->treeModel()->headerItem) {
         header()->setHidden(hide);
     } else {
         const QModelIndex index = d->index(item);
         setRowHidden(index.row(), index.parent(), hide);
     }
 }
setItemSelected()
void QTreeWidget::setItemSelected (const QTreeWidgetItem * item, bool select)
If select is true, the given item is selected; otherwise it is deselected.
See also
itemSelectionChanged()
This function is deprecated. Use QTreeWidgetItem::setSelected() instead.
Definition at line 3284 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::setSelected().
 {
     Q_D(QTreeWidget);
     if (!item)
         return;
     selectionModel()->select(d->index(item), (select ? QItemSelectionModel::Select
                                               : QItemSelectionModel::Deselect)
                              |QItemSelectionModel::Rows);
     item->d->selected = select;
 }
setItemWidget()
void QTreeWidget::setItemWidget (QTreeWidgetItem * item, int column, QWidget * widget)
Sets the given widget to be displayed in the cell specified by the given item and column.
Since
4.1
The given widget's QWidget::autoFillBackground property must be set to true, otherwise the widget's background will be transparent, showing both the model data and the tree widget item.
This function should only be used to display static content in the place of a tree widget item. If you want to display custom dynamic content or implement a custom editor widget, use QTreeView and subclass QItemDelegate instead.
This function cannot be called before the item hierarchy has been set up, i.e., the QTreeWidgetItem that will hold widget must have been added to the view before widget is set.
Note
The tree takes ownership of the widget.
See also
{Delegate Classes}
Definition at line 3252 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QAbstractItemView::setIndexWidget(d->index(item, column), widget);
 }
setModel()
void QTreeWidget::setModel (QAbstractItemModel * model) private virtual
Reimplemented Function
Reimplemented from QTreeView.
Definition at line 3711 of file qtreewidget.cpp.
 {
     Q_ASSERT(!"QTreeWidget::setModel() - Changing the model of the QTreeWidget is not allowed.");
 }
setSelectionModel()
void QTreeWidget::setSelectionModel (QItemSelectionModel * selectionModel) virtual
Reimplemented Function
Reimplemented from QTreeView.
Definition at line 3484 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     QTreeView::setSelectionModel(selectionModel);
     QItemSelection newSelection = selectionModel->selection();
     if (!newSelection.isEmpty())
         d->_q_selectionChanged(newSelection, QItemSelection());
 }
setSortingEnabled()
void QTreeWidget::setSortingEnabled (bool enable)
Warning
This function is not part of the public interface.
Qt 5: remove
Definition at line 3157 of file qtreewidget.cpp.
 {
     QTreeView::setSortingEnabled(enable);
 }
sortColumn()
int QTreeWidget::sortColumn () const
Returns the column used to sort the contents of the widget.
Since
4.1
See also
sortItems()
Definition at line 3130 of file qtreewidget.cpp.
Referenced by QTreeWidgetItem::operator<().
 {
     Q_D(const QTreeWidget);
     return (d->explicitSortColumn != -1
             ? d->explicitSortColumn
             : header()->sortIndicatorSection());
 }
sortItems()
void QTreeWidget::sortItems (int column, Qt::SortOrder order)
Sorts the items in the widget in the specified order by the values in the given column.
See also
sortColumn()
Definition at line 3145 of file qtreewidget.cpp.
 {
     Q_D(QTreeWidget);
     header()->setSortIndicator(column, order);
     d->model->sort(column, order);
 }
supportedDropActions()
Qt::DropActions QTreeWidget::supportedDropActions () const protected virtual
Returns the drop actions supported by this view.
See also
Qt::DropActions
Definition at line 3605 of file qtreewidget.cpp.
Referenced by QTreeModel::supportedDropActions().
 {
     return model()->QAbstractItemModel::supportedDropActions() | Qt::MoveAction;
 }
takeTopLevelItem()
QTreeWidgetItem * QTreeWidget::takeTopLevelItem (int index)
Removes the top-level item at the given index in the tree and returns it, otherwise returns 0;.
See also
insertTopLevelItem(), topLevelItem(), topLevelItemCount()
Definition at line 2883 of file qtreewidget.cpp.
Referenced by dropEvent().
 {
     Q_D(QTreeWidget);
     return d->treeModel()->rootItem->takeChild(index);
 }
topLevelItem()
QTreeWidgetItem * QTreeWidget::topLevelItem (int index) const
Returns the top level item at the given index, or 0 if the item does not exist.
See also
topLevelItemCount(), insertTopLevelItem()
Definition at line 2823 of file qtreewidget.cpp.
Referenced by QTreeWidgetItemIteratorPrivate::nextSibling().
 {
     Q_D(const QTreeWidget);
     return d->treeModel()->rootItem->child(index);
 }
topLevelItemCount()
int QTreeWidget::topLevelItemCount () const
Referenced by addTopLevelItem(), addTopLevelItems(), dropEvent(), and topLevelItem().
visualItemRect()
QRect QTreeWidget::visualItemRect (const QTreeWidgetItem * item) const
Returns the rectangle on the viewport occupied by the item at item.
See also
itemAt()
Definition at line 3107 of file qtreewidget.cpp.
 {
     Q_D(const QTreeWidget);
     //the visual rect for an item is across all columns. So we need to determine
     //what is the first and last column and get their visual index rects
     QModelIndex base = d->index(item);
     const int firstVisiblesection = header()->logicalIndexAt(- header()->offset());
     const int lastVisibleSection = header()->logicalIndexAt(header()->length() - header()->offset() - 1);
     QModelIndex first = base.sibling(base.row(), header()->logicalIndex(firstVisiblesection));
     QModelIndex last = base.sibling(base.row(), header()->logicalIndex(lastVisibleSection));
     return visualRect(first) | visualRect(last);
 }
Friends and Related Functions
QTreeModel
friend class QTreeModel friend
Definition at line 266 of file qtreewidget.h.
Referenced by QTreeWidget().
QTreeWidgetItem
friend class QTreeWidgetItem friend
Definition at line 267 of file qtreewidget.h.
Properties
columnCount
int QTreeWidget::columnCount private
the number of columns displayed in the tree widget
By default, this property has a value of 1.
Definition at line 263 of file qtreewidget.h.
topLevelItemCount
int QTreeWidget::topLevelItemCount private
the number of top-level items
By default, this property has a value of 0.
See also
columnCount(), currentItem()
Definition at line 264 of file qtreewidget.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtreewidget.h
/src/gui/itemviews/qtreewidget.cpp