Qt 4.8: QSslSocketPrivate Class Reference
QSslSocketPrivate Class Reference abstract
#include <qsslsocket_p.h>
Public Functions
void _q_bytesWrittenSlot (qint64)
void _q_connectedSlot ()
void _q_disconnectedSlot ()
void _q_errorSlot (QAbstractSocket::SocketError)
void _q_flushReadBuffer ()
void _q_flushWriteBuffer ()
void _q_hostFoundSlot ()
void _q_readyReadSlot ()
void _q_stateChangedSlot (QAbstractSocket::SocketState)
void createPlainSocket (QIODevice::OpenMode openMode)
virtual void disconnected ()=0
virtual void disconnectFromHost ()=0
void init ()
virtual qint64 peek (char *data, qint64 maxSize)
virtual QByteArray peek (qint64 maxSize)
QSslSocketPrivate ()
virtual QSslCipher sessionCipher () const =0
virtual void startClientEncryption ()=0
virtual void startServerEncryption ()=0
virtual void transmit ()=0
virtual ~QSslSocketPrivate ()
Public Functions inherited from QAbstractSocketPrivate
void _q_abortConnectionAttempt ()
This function is called after a certain number of seconds has passed while waiting for a connection.
void _q_connectToNextAddress ()
Called by a queued or direct connection from _q_startConnecting() or _q_testConnection(), this function takes the first address of the pending addresses list and tries to connect to it.
void _q_forceDisconnect ()
void _q_startConnecting (const QHostInfo &hostInfo)
Slot connected to QHostInfo::lookupHost() in connectToHost().
void _q_testConnection ()
Tests if a connection has been established.
bool canReadNotification ()
Slot connected to the read socket notifier.
bool canWriteNotification ()
Slot connected to the write socket notifier.
void connectionNotification ()
Slot connected to a notification of connection status change.
void exceptionNotification ()
void fetchConnectionParameters ()
Sets up the internal state after the connection has succeeded.
bool flush ()
Writes pending data in the write buffers to the socket.
bool initSocketLayer (QAbstractSocket::NetworkLayerProtocol protocol)
Initializes the socket layer to by of type type, using the network layer protocol protocol.
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
QAbstractSocketPrivate ()
Constructs a QAbstractSocketPrivate.
bool readFromSocket ()
Reads data from the socket layer into the read buffer.
void readNotification ()
void resetSocketLayer ()
Resets the socket layer, clears the read and write buffers and deletes any socket notifiers.
void resolveProxy (const QString &hostName, quint16 port)
Resolve the proxy to its final value.
void resolveProxy (quint16 port)
void setupSocketNotifiers ()
void startConnectingByName (const QString &host)
Starts the connection to host, like _q_startConnecting below, but without hostname resolution.
void writeNotification ()
virtual ~QAbstractSocketPrivate ()
Destructs the QAbstractSocket.
Public Functions inherited from QIODevicePrivate
bool isSequential () const
virtual bool putCharHelper (char c)
QIODevicePrivate ()
virtual ~QIODevicePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Functions inherited from QAbstractSocketEngineReceiver
virtual ~QAbstractSocketEngineReceiver ()
Static Public Functions
static void addDefaultCaCertificate (const QSslCertificate &cert)
static bool addDefaultCaCertificates (const QString &path, QSsl::EncodingFormat format, QRegExp::PatternSyntax syntax)
static void addDefaultCaCertificates (const QList< QSslCertificate > &certs)
static QList< QSslCertificate > defaultCaCertificates ()
static QList< QSslCipher > defaultCiphers ()
static void deinitialize ()
static void ensureInitialized ()
Declared static in QSslSocketPrivate, makes sure the SSL libraries have been initialized.
static void pauseSocketNotifiers (QSslSocket *)
static void resetDefaultCiphers ()
Declared static in QSslSocketPrivate, backend-dependent loading of application-wide global ciphers.
static void resumeSocketNotifiers (QSslSocket *)
static Q_AUTOTEST_EXPORT bool rootCertOnDemandLoadingSupported ()
static void setDefaultCaCertificates (const QList< QSslCertificate > &certs)
static void setDefaultCiphers (const QList< QSslCipher > &ciphers)
static void setDefaultSupportedCiphers (const QList< QSslCipher > &ciphers)
static QList< QSslCipher > supportedCiphers ()
static bool supportsSsl ()
Does the minimum amount of initialization to determine whether SSL is supported or not.
static QList< QSslCertificate > systemCaCertificates ()
Static Public Functions inherited from QAbstractSocketPrivate
static QAbstractSocketEngine * getSocketEngine (QAbstractSocket *)
static void pauseSocketNotifiers (QAbstractSocket *)
static void resumeSocketNotifiers (QAbstractSocket *)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool allowRootCertOnDemandLoading
bool autoStartHandshake
QSslConfigurationPrivate configuration
bool connectionEncrypted
bool ignoreAllSslErrors
QList< QSslError > ignoreErrorsList
bool initialized
QSslSocket::SslMode mode
QTcpSocket * plainSocket
bool * readyReadEmittedPointer
bool shutdown
QList< QSslError > sslErrors
QString verificationPeerName
Public Variables inherited from QAbstractSocketPrivate
bool abortCalled
QList< QHostAddress > addresses
int blockingTimeout
int cachedSocketDescriptor
bool closeCalled
int connectTimeElapsed
QTimer * connectTimer
QTimer * disconnectTimer
bool emittedBytesWritten
bool emittedReadyRead
QHostAddress host
int hostLookupId
QString hostName
bool isBuffered
QHostAddress localAddress
quint16 localPort
QHostAddress peerAddress
QString peerName
quint16 peerPort
bool pendingClose
quint16 port
bool prePauseExceptionSocketNotifierState
bool prePauseReadSocketNotifierState
bool prePauseWriteSocketNotifierState
QNetworkProxy proxy
QNetworkProxy proxyInUse
QRingBuffer readBuffer
qint64 readBufferMaxSize
bool readSocketNotifierCalled
bool readSocketNotifierState
bool readSocketNotifierStateSet
QAbstractSocketEngine * socketEngine
QAbstractSocket::SocketError socketError
QAbstractSocket::SocketType socketType
QAbstractSocket::SocketState state
QRingBuffer writeBuffer
Public Variables inherited from QIODevicePrivate
AccessMode accessMode
bool baseReadLineDataCalled
QIODevicePrivateLinearBuffer buffer
qint64 devicePos
QString errorString
bool firstRead
QIODevice::OpenMode openMode
qint64 * pDevicePos
qint64 pos
qint64 * pPos
qint64 seqDumpPos
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static PtrSecCertificateGetData ptrSecCertificateGetData = 0
static PtrSecTrustCopyAnchorCertificates ptrSecTrustCopyAnchorCertificates = 0
static PtrSecTrustSettingsCopyCertificates ptrSecTrustSettingsCopyCertificates = 0
Static Protected Functions
static QList< QByteArray > unixRootCertDirectories ()
Static Protected Variables
static bool s_loadRootCertsOnDemand = false
Static Private Functions
static void ensureCiphersAndCertsLoaded ()
static bool ensureLibraryLoaded ()
Static Private Attributes
static bool s_libraryLoaded = false
static bool s_loadedCiphersAndCerts = false
Additional Inherited Members
Public Types inherited from QIODevicePrivate
enum AccessMode { Unset, Sequential, RandomAccess }
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 98 of file qsslsocket_p.h.
Constructors and Destructors
QSslSocketPrivate()
QSslSocketPrivate::QSslSocketPrivate ()
Warning
This function is not part of the public interface.
Definition at line 1915 of file qsslsocket.cpp.
     : initialized(false)
     , mode(QSslSocket::UnencryptedMode)
     , autoStartHandshake(false)
     , connectionEncrypted(false)
     , shutdown(false)
     , ignoreAllSslErrors(false)
     , readyReadEmittedPointer(0)
     , allowRootCertOnDemandLoading(true)
     , plainSocket(0)
 {
     QSslConfigurationPrivate::deepCopyDefaultConfiguration(&configuration);
 }
~QSslSocketPrivate()
QSslSocketPrivate::~QSslSocketPrivate () virtual
Warning
This function is not part of the public interface.
Definition at line 1932 of file qsslsocket.cpp.
 {
 }
Functions
_q_bytesWrittenSlot()
void QSslSocketPrivate::_q_bytesWrittenSlot (qint64 written)
Warning
This function is not part of the public interface.
Definition at line 2288 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_bytesWrittenSlot(" << written << ')';
 #endif
     if (mode == QSslSocket::UnencryptedMode)
         emit q->bytesWritten(written);
     else
         emit q->encryptedBytesWritten(written);
     if (state == QAbstractSocket::ClosingState && writeBuffer.isEmpty())
         q->disconnectFromHost();
 }
_q_connectedSlot()
void QSslSocketPrivate::_q_connectedSlot ()
Warning
This function is not part of the public interface.
Definition at line 2183 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
     q->setLocalPort(plainSocket->localPort());
     q->setLocalAddress(plainSocket->localAddress());
     q->setPeerPort(plainSocket->peerPort());
     q->setPeerAddress(plainSocket->peerAddress());
     q->setPeerName(plainSocket->peerName());
     cachedSocketDescriptor = plainSocket->socketDescriptor();
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_connectedSlot()";
     qDebug() << "\tstate =" << q->state();
     qDebug() << "\tpeer =" << q->peerName() << q->peerAddress() << q->peerPort();
     qDebug() << "\tlocal =" << QHostInfo::fromName(q->localAddress().toString()).hostName()
              << q->localAddress() << q->localPort();
 #endif
     emit q->connected();
     if (autoStartHandshake) {
         q->startClientEncryption();
     } else if (pendingClose) {
         pendingClose = false;
         q->disconnectFromHost();
     }
 }
_q_disconnectedSlot()
void QSslSocketPrivate::_q_disconnectedSlot ()
Warning
This function is not part of the public interface.
Definition at line 2226 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_disconnectedSlot()";
     qDebug() << "\tstate =" << q->state();
 #endif
     disconnected();
     emit q->disconnected();
 }
_q_errorSlot()
void QSslSocketPrivate::_q_errorSlot (QAbstractSocket::SocketError error)
Warning
This function is not part of the public interface.
Definition at line 2253 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_errorSlot(" << error << ')';
     qDebug() << "\tstate =" << q->state();
     qDebug() << "\terrorString =" << q->errorString();
 #endif
     q->setSocketError(plainSocket->error());
     q->setErrorString(plainSocket->errorString());
     emit q->error(error);
 }
_q_flushReadBuffer()
void QSslSocketPrivate::_q_flushReadBuffer ()
Warning
This function is not part of the public interface.
Definition at line 2316 of file qsslsocket.cpp.
 {
     // trigger a read from the plainSocket into SSL
     if (mode != QSslSocket::UnencryptedMode)
         transmit();
 }
_q_flushWriteBuffer()
void QSslSocketPrivate::_q_flushWriteBuffer ()
Warning
This function is not part of the public interface.
Definition at line 2306 of file qsslsocket.cpp.
 {
     Q_Q(QSslSocket);
     if (!writeBuffer.isEmpty())
         q->flush();
 }
_q_hostFoundSlot()
void QSslSocketPrivate::_q_hostFoundSlot ()
Warning
This function is not part of the public interface.
Definition at line 2213 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_hostFoundSlot()";
     qDebug() << "\tstate =" << q->state();
 #endif
     emit q->hostFound();
 }
_q_readyReadSlot()
void QSslSocketPrivate::_q_readyReadSlot ()
Warning
This function is not part of the public interface.
Definition at line 2269 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_readyReadSlot() -" << plainSocket->bytesAvailable() << "bytes available";
 #endif
     if (mode == QSslSocket::UnencryptedMode) {
         if (readyReadEmittedPointer)
             *readyReadEmittedPointer = true;
         emit q->readyRead();
         return;
     }
     transmit();
 }
_q_stateChangedSlot()
void QSslSocketPrivate::_q_stateChangedSlot (QAbstractSocket::SocketState state)
Warning
This function is not part of the public interface.
Definition at line 2240 of file qsslsocket.cpp.
Referenced by createPlainSocket().
 {
     Q_Q(QSslSocket);
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "QSslSocket::_q_stateChangedSlot(" << state << ')';
 #endif
     q->setSocketState(state);
     emit q->stateChanged(state);
 }
addDefaultCaCertificate()
void QSslSocketPrivate::addDefaultCaCertificate (const QSslCertificate & cert) static
Warning
This function is not part of the public interface.
Definition at line 2041 of file qsslsocket.cpp.
Referenced by QSslSocket::addDefaultCaCertificate().
 {
     QSslSocketPrivate::ensureInitialized();
     QMutexLocker locker(&globalData()->mutex);
     globalData()->config.detach();
     globalData()->config->caCertificates += cert;
 }
addDefaultCaCertificates() [1/2]
bool QSslSocketPrivate::addDefaultCaCertificates (const QString & path, QSsl::EncodingFormat format, QRegExp::PatternSyntax syntax) static
Warning
This function is not part of the public interface.
Definition at line 2024 of file qsslsocket.cpp.
Referenced by QSslSocket::addDefaultCaCertificates().
 {
     QSslSocketPrivate::ensureInitialized();
     QList<QSslCertificate> certs = QSslCertificate::fromPath(path, format, syntax);
     if (certs.isEmpty())
         return false;
     QMutexLocker locker(&globalData()->mutex);
     globalData()->config.detach();
     globalData()->config->caCertificates += certs;
     return true;
 }
addDefaultCaCertificates() [2/2]
void QSslSocketPrivate::addDefaultCaCertificates (const QList< QSslCertificate > & certs) static
Warning
This function is not part of the public interface.
Definition at line 2052 of file qsslsocket.cpp.
 {
     QSslSocketPrivate::ensureInitialized();
     QMutexLocker locker(&globalData()->mutex);
     globalData()->config.detach();
     globalData()->config->caCertificates += certs;
 }
createPlainSocket()
void QSslSocketPrivate::createPlainSocket (QIODevice::OpenMode openMode)
Warning
This function is not part of the public interface.
Definition at line 2114 of file qsslsocket.cpp.
 {
     Q_Q(QSslSocket);
     q->setOpenMode(openMode); // <- from QIODevice
     q->setSocketState(QAbstractSocket::UnconnectedState);
     q->setSocketError(QAbstractSocket::UnknownSocketError);
     q->setLocalPort(0);
     q->setLocalAddress(QHostAddress());
     q->setPeerPort(0);
     q->setPeerAddress(QHostAddress());
     q->setPeerName(QString());
     plainSocket = new QTcpSocket(q);
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the plain socket (if it has been set)
     plainSocket->setProperty("_q_networksession", q->property("_q_networksession"));
 #endif
     q->connect(plainSocket, SIGNAL(connected()),
                q, SLOT(_q_connectedSlot()),
                Qt::DirectConnection);
     q->connect(plainSocket, SIGNAL(hostFound()),
                q, SLOT(_q_hostFoundSlot()),
                Qt::DirectConnection);
     q->connect(plainSocket, SIGNAL(disconnected()),
                q, SLOT(_q_disconnectedSlot()),
                Qt::DirectConnection);
     q->connect(plainSocket, SIGNAL(stateChanged(QAbstractSocket::SocketState)),
                q, SLOT(_q_stateChangedSlot(QAbstractSocket::SocketState)),
                Qt::DirectConnection);
     q->connect(plainSocket, SIGNAL(error(QAbstractSocket::SocketError)),
                q, SLOT(_q_errorSlot(QAbstractSocket::SocketError)),
                Qt::DirectConnection);
     q->connect(plainSocket, SIGNAL(readyRead()),
                q, SLOT(_q_readyReadSlot()),
                Qt::DirectConnection);
     q->connect(plainSocket, SIGNAL(bytesWritten(qint64)),
                q, SLOT(_q_bytesWrittenSlot(qint64)),
                Qt::DirectConnection);
 #ifndef QT_NO_NETWORKPROXY
     q->connect(plainSocket, SIGNAL(proxyAuthenticationRequired(QNetworkProxy,QAuthenticator*)),
                q, SIGNAL(proxyAuthenticationRequired(QNetworkProxy,QAuthenticator*)));
 #endif
     readBuffer.clear();
     writeBuffer.clear();
     connectionEncrypted = false;
     configuration.peerCertificate.clear();
     configuration.peerCertificateChain.clear();
     mode = QSslSocket::UnencryptedMode;
     q->setReadBufferSize(readBufferMaxSize);
 }
defaultCaCertificates()
QList< QSslCertificate > QSslSocketPrivate::defaultCaCertificates () static
Warning
This function is not part of the public interface.
Definition at line 1999 of file qsslsocket.cpp.
Referenced by QSslSocket::defaultCaCertificates().
 {
     // ### Qt5: rename everything containing "caCertificates" to "rootCertificates" or similar
     QSslSocketPrivate::ensureInitialized();
     QMutexLocker locker(&globalData()->mutex);
     return globalData()->config->caCertificates;
 }
defaultCiphers()
QList< QSslCipher > QSslSocketPrivate::defaultCiphers () static
Warning
This function is not part of the public interface.
Definition at line 1960 of file qsslsocket.cpp.
Referenced by QSslSocket::defaultCiphers(), and QSslSocketBackendPrivate::initSslContext().
 {
     QMutexLocker locker(&globalData()->mutex);
     return globalData()->config->ciphers;
 }
deinitialize()
void QSslSocketPrivate::deinitialize () static
Warning
This function is not part of the public interface.
Definition at line 504 of file qsslsocket_openssl.cpp.
Referenced by QOpenSslLocks::~QOpenSslLocks().
 {
     q_CRYPTO_set_id_callback(0);
     q_CRYPTO_set_locking_callback(0);
 }
disconnected()
virtual void QSslSocketPrivate::disconnected () pure virtual
Implemented in QSslSocketBackendPrivate.
Referenced by _q_disconnectedSlot(), and createPlainSocket().
disconnectFromHost()
virtual void QSslSocketPrivate::disconnectFromHost () pure virtual
Implemented in QSslSocketBackendPrivate.
ensureCiphersAndCertsLoaded()
void QSslSocketPrivate::ensureCiphersAndCertsLoaded () static private
Definition at line 574 of file qsslsocket_openssl.cpp.
Referenced by ensureInitialized().
 {
     QMutexLocker locker(openssl_locks()->initLock());
     if (s_loadedCiphersAndCerts)
         return;
     s_loadedCiphersAndCerts = true;
     resetDefaultCiphers();
     //load symbols needed to receive certificates from system store
 #if defined(Q_OS_MAC) && !defined(Q_OS_IOS)
     QLibrary securityLib("/System/Library/Frameworks/Security.framework/Versions/Current/Security");
     if (securityLib.load()) {
         ptrSecCertificateGetData = (PtrSecCertificateGetData) securityLib.resolve("SecCertificateGetData");
         if (!ptrSecCertificateGetData)
             qWarning("could not resolve symbols in security library"); // should never happen
         ptrSecTrustSettingsCopyCertificates = (PtrSecTrustSettingsCopyCertificates) securityLib.resolve("SecTrustSettingsCopyCertificates");
         if (!ptrSecTrustSettingsCopyCertificates) { // method was introduced in Leopard, use legacy method if it's not there
             ptrSecTrustCopyAnchorCertificates = (PtrSecTrustCopyAnchorCertificates) securityLib.resolve("SecTrustCopyAnchorCertificates");
             if (!ptrSecTrustCopyAnchorCertificates)
                 qWarning("could not resolve symbols in security library"); // should never happen
         }
     } else {
         qWarning("could not load security library");
     }
 #elif defined(Q_OS_WIN)
     HINSTANCE hLib = LoadLibraryW(L"Crypt32");
     if (hLib) {
 #if defined(Q_OS_WINCE)
         ptrCertOpenSystemStoreW = (PtrCertOpenSystemStoreW)GetProcAddress(hLib, L"CertOpenStore");
         ptrCertFindCertificateInStore = (PtrCertFindCertificateInStore)GetProcAddress(hLib, L"CertFindCertificateInStore");
         ptrCertCloseStore = (PtrCertCloseStore)GetProcAddress(hLib, L"CertCloseStore");
 #else
         ptrCertOpenSystemStoreW = (PtrCertOpenSystemStoreW)GetProcAddress(hLib, "CertOpenSystemStoreW");
         ptrCertFindCertificateInStore = (PtrCertFindCertificateInStore)GetProcAddress(hLib, "CertFindCertificateInStore");
         ptrCertCloseStore = (PtrCertCloseStore)GetProcAddress(hLib, "CertCloseStore");
 #endif
         if (!ptrCertOpenSystemStoreW || !ptrCertFindCertificateInStore || !ptrCertCloseStore)
             qWarning("could not resolve symbols in crypt32 library"); // should never happen
     } else {
         qWarning("could not load crypt32 library"); // should never happen
     }
 #elif defined(Q_OS_QNX)
     s_loadRootCertsOnDemand = true;
 #elif defined(Q_OS_UNIX) && !defined(Q_OS_SYMBIAN) && !defined(Q_OS_MAC)
     // check whether we can enable on-demand root-cert loading (i.e. check whether the sym links are there)
     QList<QByteArray> dirs = unixRootCertDirectories();
     QStringList symLinkFilter;
     symLinkFilter << QLatin1String("[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f].[0-9]");
     for (int a = 0; a < dirs.count(); ++a) {
         QDirIterator iterator(QLatin1String(dirs.at(a)), symLinkFilter, QDir::Files);
         if (iterator.hasNext()) {
             s_loadRootCertsOnDemand = true;
             break;
         }
     }
 #endif
     // if on-demand loading was not enabled, load the certs now
     if (!s_loadRootCertsOnDemand)
         setDefaultCaCertificates(systemCaCertificates());
 }
ensureInitialized()
void QSslSocketPrivate::ensureInitialized () static
Declared static in QSslSocketPrivate, makes sure the SSL libraries have been initialized.
Warning
This function is not part of the public interface.
Definition at line 647 of file qsslsocket_openssl.cpp.
Referenced by addDefaultCaCertificate(), addDefaultCaCertificates(), QSslCertificatePrivate::certificatesFromDer(), QSslCertificatePrivate::certificatesFromPem(), QSslConfigurationPrivate::deepCopyDefaultConfiguration(), defaultCaCertificates(), QSslConfigurationPrivate::defaultConfiguration(), QSslCertificate::QSslCertificate(), QSslCertificatePrivate::QSslCertificatePrivate(), QSslSocketBackendPrivate::QSslSocketBackendPrivate(), setDefaultCaCertificates(), QSslConfigurationPrivate::setDefaultConfiguration(), QSslSocketBackendPrivate::STACKOFX509_to_QSslCertificates(), supportedCiphers(), and systemCaCertificates().
 {
     if (!supportsSsl())
         return;
     ensureCiphersAndCertsLoaded();
 }
ensureLibraryLoaded()
bool QSslSocketPrivate::ensureLibraryLoaded () static private
Definition at line 525 of file qsslsocket_openssl.cpp.
Referenced by supportsSsl().
 {
     if (!q_resolveOpenSslSymbols())
         return false;
     // Check if the library itself needs to be initialized.
     QMutexLocker locker(openssl_locks()->initLock());
     if (!s_libraryLoaded) {
         s_libraryLoaded = true;
         // Initialize OpenSSL.
         q_CRYPTO_set_id_callback(id_function);
         q_CRYPTO_set_locking_callback(locking_function);
         if (q_SSL_library_init() != 1)
             return false;
         q_SSL_load_error_strings();
         q_OpenSSL_add_all_algorithms();
         // Initialize OpenSSL's random seed.
         if (!q_RAND_status()) {
             struct {
                 int msec;
                 int sec;
                 void *stack;
             } randomish;
             int attempts = 500;
             do {
                 if (attempts < 500) {
 #ifdef Q_OS_UNIX
                     struct timespec ts = {0, 33333333};
                     nanosleep(&ts, 0);
 #else
                     Sleep(3);
 #endif
                     randomish.msec = attempts;
                 }
                 randomish.stack = (void *)&randomish;
                 randomish.msec = QTime::currentTime().msec();
                 randomish.sec = QTime::currentTime().second();
                 q_RAND_seed((const char *)&randomish, sizeof(randomish));
             } while (!q_RAND_status() && --attempts);
             if (!attempts)
                 return false;
         }
     }
     return true;
 }
init()
void QSslSocketPrivate::init ()
Warning
This function is not part of the public interface.
Definition at line 1939 of file qsslsocket.cpp.
 {
     mode = QSslSocket::UnencryptedMode;
     autoStartHandshake = false;
     connectionEncrypted = false;
     ignoreAllSslErrors = false;
     shutdown = false;
     // we don't want to clear the ignoreErrorsList, so
     // that it is possible setting it before connecting
 //    ignoreErrorsList.clear();
     readBuffer.clear();
     writeBuffer.clear();
     configuration.peerCertificate.clear();
     configuration.peerCertificateChain.clear();
 }
pauseSocketNotifiers()
void QSslSocketPrivate::pauseSocketNotifiers (QSslSocket * socket) static
Definition at line 2166 of file qsslsocket.cpp.
Referenced by QHttpNetworkConnectionPrivate::pauseConnection().
 {
     if (!socket->d_func()->plainSocket)
         return;
     QAbstractSocketPrivate::pauseSocketNotifiers(socket->d_func()->plainSocket);
 }
peek() [1/2]
qint64 QSslSocketPrivate::peek (char * data, qint64 maxSize) virtual
Warning
This function is not part of the public interface.
Reimplemented from QIODevicePrivate.
Definition at line 2326 of file qsslsocket.cpp.
 {
     if (mode == QSslSocket::UnencryptedMode && !autoStartHandshake) {
         //unencrypted mode - do not use QIODevice::peek, as it reads ahead data from the plain socket
         //peek at data already in the QIODevice buffer (from a previous read)
         qint64 r = buffer.peek(data, maxSize);
         if (r == maxSize)
             return r;
         data += r;
         //peek at data in the plain socket
         if (plainSocket) {
             qint64 r2 = plainSocket->peek(data, maxSize - r);
             if (r2 < 0)
                 return (r > 0 ? r : r2);
             return r + r2;
         } else {
             return -1;
         }
     } else {
         //encrypted mode - the socket engine will read and decrypt data into the QIODevice buffer
         return QTcpSocketPrivate::peek(data, maxSize);
     }
 }
peek() [2/2]
QByteArray QSslSocketPrivate::peek (qint64 maxSize) virtual
Warning
This function is not part of the public interface.
Reimplemented from QIODevicePrivate.
Definition at line 2353 of file qsslsocket.cpp.
 {
     if (mode == QSslSocket::UnencryptedMode && !autoStartHandshake) {
         //unencrypted mode - do not use QIODevice::peek, as it reads ahead data from the plain socket
         //peek at data already in the QIODevice buffer (from a previous read)
         QByteArray ret;
         ret.reserve(maxSize);
         ret.resize(buffer.peek(ret.data(), maxSize));
         if (ret.length() == maxSize)
             return ret;
         //peek at data in the plain socket
         if (plainSocket)
             return ret + plainSocket->peek(maxSize - ret.length());
         else
             return QByteArray();
     } else {
         //encrypted mode - the socket engine will read and decrypt data into the QIODevice buffer
         return QTcpSocketPrivate::peek(maxSize);
     }
 }
resetDefaultCiphers()
void QSslSocketPrivate::resetDefaultCiphers () static
Declared static in QSslSocketPrivate, backend-dependent loading of application-wide global ciphers.
Warning
This function is not part of the public interface.
Definition at line 664 of file qsslsocket_openssl.cpp.
Referenced by ensureCiphersAndCertsLoaded().
 {
     SSL_CTX *myCtx = q_SSL_CTX_new(q_SSLv23_client_method());
     SSL *mySsl = q_SSL_new(myCtx);
     QList<QSslCipher> ciphers;
     STACK_OF(SSL_CIPHER) *supportedCiphers = q_SSL_get_ciphers(mySsl);
     for (int i = 0; i < q_sk_SSL_CIPHER_num(supportedCiphers); ++i) {
         if (SSL_CIPHER *cipher = q_sk_SSL_CIPHER_value(supportedCiphers, i)) {
             if (cipher->valid) {
                 QSslCipher ciph = QSslSocketBackendPrivate::QSslCipher_from_SSL_CIPHER(cipher);
                 if (!ciph.isNull()) {
                     if (!ciph.name().toLower().startsWith(QLatin1String("adh")))
                         ciphers << ciph;
                 }
             }
         }
     }
     q_SSL_CTX_free(myCtx);
     q_SSL_free(mySsl);
     setDefaultSupportedCiphers(ciphers);
     setDefaultCiphers(ciphers);
 }
resumeSocketNotifiers()
void QSslSocketPrivate::resumeSocketNotifiers (QSslSocket * socket) static
Definition at line 2173 of file qsslsocket.cpp.
Referenced by QHttpNetworkConnectionPrivate::resumeConnection().
 {
     if (!socket->d_func()->plainSocket)
         return;
     QAbstractSocketPrivate::resumeSocketNotifiers(socket->d_func()->plainSocket);
 }
rootCertOnDemandLoadingSupported()
bool QSslSocketPrivate::rootCertOnDemandLoadingSupported () static
Warning
This function is not part of the public interface.
Definition at line 2377 of file qsslsocket.cpp.
 {
     return s_loadRootCertsOnDemand;
 }
sessionCipher()
virtual QSslCipher QSslSocketPrivate::sessionCipher () const pure virtual
Implemented in QSslSocketBackendPrivate.
setDefaultCaCertificates()
void QSslSocketPrivate::setDefaultCaCertificates (const QList< QSslCertificate > & certs) static
Warning
This function is not part of the public interface.
Definition at line 2010 of file qsslsocket.cpp.
Referenced by ensureCiphersAndCertsLoaded(), and QSslSocket::setDefaultCaCertificates().
 {
     QSslSocketPrivate::ensureInitialized();
     QMutexLocker locker(&globalData()->mutex);
     globalData()->config.detach();
     globalData()->config->caCertificates = certs;
     // when the certificates are set explicitly, we do not want to
     // load the system certificates on demand
     s_loadRootCertsOnDemand = false;
 }
setDefaultCiphers()
void QSslSocketPrivate::setDefaultCiphers (const QList< QSslCipher > & ciphers) static
Warning
This function is not part of the public interface.
Definition at line 1979 of file qsslsocket.cpp.
Referenced by resetDefaultCiphers(), and QSslSocket::setDefaultCiphers().
 {
     QMutexLocker locker(&globalData()->mutex);
     globalData()->config.detach();
     globalData()->config->ciphers = ciphers;
 }
setDefaultSupportedCiphers()
void QSslSocketPrivate::setDefaultSupportedCiphers (const QList< QSslCipher > & ciphers) static
Warning
This function is not part of the public interface.
Definition at line 1989 of file qsslsocket.cpp.
Referenced by resetDefaultCiphers().
 {
     QMutexLocker locker(&globalData()->mutex);
     globalData()->config.detach();
     globalData()->supportedCiphers = ciphers;
 }
startClientEncryption()
virtual void QSslSocketPrivate::startClientEncryption () pure virtual
Implemented in QSslSocketBackendPrivate.
startServerEncryption()
virtual void QSslSocketPrivate::startServerEncryption () pure virtual
Implemented in QSslSocketBackendPrivate.
supportedCiphers()
QList< QSslCipher > QSslSocketPrivate::supportedCiphers () static
Warning
This function is not part of the public interface.
Definition at line 1969 of file qsslsocket.cpp.
Referenced by resetDefaultCiphers(), and QSslSocket::supportedCiphers().
 {
     QSslSocketPrivate::ensureInitialized();
     QMutexLocker locker(&globalData()->mutex);
     return globalData()->supportedCiphers;
 }
supportsSsl()
bool QSslSocketPrivate::supportsSsl () static
Does the minimum amount of initialization to determine whether SSL is supported or not.
Warning
This function is not part of the public interface.
Definition at line 520 of file qsslsocket_openssl.cpp.
Referenced by ensureInitialized(), and QSslSocket::supportsSsl().
 {
     return ensureLibraryLoaded();
 }
systemCaCertificates()
QList< QSslCertificate > QSslSocketPrivate::systemCaCertificates () static
Definition at line 865 of file qsslsocket_openssl.cpp.
Referenced by ensureCiphersAndCertsLoaded(), and QSslSocket::systemCaCertificates().
 {
     ensureInitialized();
 #ifdef QSSLSOCKET_DEBUG
     QElapsedTimer timer;
     timer.start();
 #endif
     QList<QSslCertificate> systemCerts;
 #if defined(Q_OS_MAC) && !defined(Q_OS_IOS)
     CFArrayRef cfCerts;
     OSStatus status = 1;
     OSStatus SecCertificateGetData (
        SecCertificateRef certificate,
        CSSM_DATA_PTR data
     );
     if (ptrSecCertificateGetData) {
         if (ptrSecTrustSettingsCopyCertificates)
             status = ptrSecTrustSettingsCopyCertificates(kSecTrustSettingsDomainSystem, &cfCerts);
         else if (ptrSecTrustCopyAnchorCertificates)
             status = ptrSecTrustCopyAnchorCertificates(&cfCerts);
         if (!status) {
             CFIndex size = CFArrayGetCount(cfCerts);
             for (CFIndex i = 0; i < size; ++i) {
                 SecCertificateRef cfCert = (SecCertificateRef)CFArrayGetValueAtIndex(cfCerts, i);
                 CSSM_DATA data;
                 CSSM_DATA_PTR dataPtr = &data;
                 if (ptrSecCertificateGetData(cfCert, dataPtr)) {
                     qWarning("error retrieving a CA certificate from the system store");
                 } else {
                     int len = data.Length;
                     char *rawData = reinterpret_cast<char *>(data.Data);
                     QByteArray rawCert(rawData, len);
                     systemCerts.append(QSslCertificate::fromData(rawCert, QSsl::Der));
                 }
             }
             CFRelease(cfCerts);
         }
         else {
            // no detailed error handling here
            qWarning("could not retrieve system CA certificates");
         }
     }
 #elif defined(Q_OS_WIN)
     if (ptrCertOpenSystemStoreW && ptrCertFindCertificateInStore && ptrCertCloseStore) {
         HCERTSTORE hSystemStore;
 #if defined(Q_OS_WINCE)
         hSystemStore = ptrCertOpenSystemStoreW(CERT_STORE_PROV_SYSTEM_W,
                                                0,
                                                0,
                                                CERT_STORE_NO_CRYPT_RELEASE_FLAG|CERT_SYSTEM_STORE_CURRENT_USER,
                                                L"ROOT");
 #else
         hSystemStore = ptrCertOpenSystemStoreW(0, L"ROOT");
 #endif
         if(hSystemStore) {
             PCCERT_CONTEXT pc = NULL;
             while(1) {
                 pc = ptrCertFindCertificateInStore( hSystemStore, X509_ASN_ENCODING, 0, CERT_FIND_ANY, NULL, pc);
                 if(!pc)
                     break;
                 QByteArray der((const char *)(pc->pbCertEncoded), static_cast<int>(pc->cbCertEncoded));
                 QSslCertificate cert(der, QSsl::Der);
                 systemCerts.append(cert);
             }
             ptrCertCloseStore(hSystemStore, 0);
         }
     }
 #elif defined(Q_OS_UNIX) && !defined(Q_OS_SYMBIAN)
     QSet<QString> certFiles;
     QList<QByteArray> directories = unixRootCertDirectories();
     QDir currentDir;
     QStringList nameFilters;
     nameFilters << QLatin1String("*.pem") << QLatin1String("*.crt");
     currentDir.setNameFilters(nameFilters);
     for (int a = 0; a < directories.count(); a++) {
         currentDir.setPath(QLatin1String(directories.at(a)));
         QDirIterator it(currentDir);
         while(it.hasNext()) {
             it.next();
             // use canonical path here to not load the same certificate twice if symlinked
             certFiles.insert(it.fileInfo().canonicalFilePath());
         }
     }
     QSetIterator<QString> it(certFiles);
     while(it.hasNext()) {
         systemCerts.append(QSslCertificate::fromPath(it.next()));
     }
     systemCerts.append(QSslCertificate::fromPath(QLatin1String("/etc/pki/tls/certs/ca-bundle.crt"), QSsl::Pem)); // Fedora, Mandriva
     systemCerts.append(QSslCertificate::fromPath(QLatin1String("/usr/local/share/certs/ca-root-nss.crt"), QSsl::Pem)); // FreeBSD's ca_root_nss
 #elif defined(Q_OS_SYMBIAN)
     QList<QByteArray> certs;
     QScopedPointer<CSymbianCertificateRetriever> retriever(CSymbianCertificateRetriever::NewL());
     retriever->GetCertificates(certs);
     foreach (const QByteArray &encodedCert, certs) {
         QSslCertificate cert(encodedCert, QSsl::Der);
         if (!cert.isNull()) {
 #ifdef QSSLSOCKET_DEBUG
             qDebug() << "imported certificate: " << cert.issuerInfo(QSslCertificate::CommonName);
 #endif
             systemCerts.append(cert);
         }
     }
 #endif
 #ifdef QSSLSOCKET_DEBUG
     qDebug() << "systemCaCertificates retrieval time " << timer.elapsed() << "ms";
     qDebug() << "imported " << systemCerts.count() << " certificates";
 #endif
     return systemCerts;
 }
transmit()
virtual void QSslSocketPrivate::transmit () pure virtual
Implemented in QSslSocketBackendPrivate.
Referenced by _q_flushReadBuffer(), and _q_readyReadSlot().
unixRootCertDirectories()
QList< QByteArray > QSslSocketPrivate::unixRootCertDirectories () static protected
Warning
This function is not part of the public interface.
Definition at line 2385 of file qsslsocket.cpp.
Referenced by ensureCiphersAndCertsLoaded(), QSslSocketBackendPrivate::initSslContext(), and systemCaCertificates().
 {
     return QList<QByteArray>() <<  "/etc/ssl/certs/" // (K)ubuntu, OpenSUSE, Mandriva, MeeGo ...
                                << "/usr/lib/ssl/certs/" // Gentoo, Mandrake
                                << "/usr/share/ssl/" // Centos, Redhat, SuSE
                                << "/usr/local/ssl/" // Normal OpenSSL Tarball
                                << "/var/ssl/certs/" // AIX
                                << "/usr/local/ssl/certs/" // Solaris
                                << "/etc/openssl/certs/" // BlackBerry
                                << "/opt/openssl/certs/"; // HP-UX
 }
Properties
allowRootCertOnDemandLoading
bool QSslSocketPrivate::allowRootCertOnDemandLoading
Definition at line 123 of file qsslsocket_p.h.
Referenced by QSslSocketBackendPrivate::initSslContext().
autoStartHandshake
bool QSslSocketPrivate::autoStartHandshake
Definition at line 109 of file qsslsocket_p.h.
Referenced by _q_connectedSlot(), init(), peek(), and QSslSocketBackendPrivate::startHandshake().
configuration
QSslConfigurationPrivate QSslSocketPrivate::configuration
Definition at line 116 of file qsslsocket_p.h.
Referenced by createPlainSocket(), init(), QSslSocketBackendPrivate::initSslContext(), QSslSocketPrivate(), and QSslSocketBackendPrivate::startHandshake().
connectionEncrypted
bool QSslSocketPrivate::connectionEncrypted
Definition at line 110 of file qsslsocket_p.h.
Referenced by createPlainSocket(), init(), QSslSocketBackendPrivate::startHandshake(), and QSslSocketBackendPrivate::transmit().
ignoreAllSslErrors
bool QSslSocketPrivate::ignoreAllSslErrors
Definition at line 112 of file qsslsocket_p.h.
Referenced by init(), and QSslSocketBackendPrivate::startHandshake().
ignoreErrorsList
QList<QSslError> QSslSocketPrivate::ignoreErrorsList
Definition at line 113 of file qsslsocket_p.h.
Referenced by QSslSocketBackendPrivate::startHandshake().
initialized
bool QSslSocketPrivate::initialized
Definition at line 106 of file qsslsocket_p.h.
mode
QSslSocket::SslMode QSslSocketPrivate::mode
Definition at line 108 of file qsslsocket_p.h.
Referenced by _q_bytesWrittenSlot(), _q_flushReadBuffer(), _q_readyReadSlot(), createPlainSocket(), init(), QSslSocketBackendPrivate::initSslContext(), peek(), and QSslSocketBackendPrivate::startHandshake().
plainSocket
QTcpSocket* QSslSocketPrivate::plainSocket
Definition at line 153 of file qsslsocket_p.h.
Referenced by _q_connectedSlot(), _q_errorSlot(), _q_readyReadSlot(), createPlainSocket(), QSslSocketBackendPrivate::disconnected(), QSslSocketBackendPrivate::disconnectFromHost(), peek(), QSslSocketBackendPrivate::startHandshake(), and QSslSocketBackendPrivate::transmit().
ptrSecCertificateGetData
PtrSecCertificateGetData QSslSocketPrivate::ptrSecCertificateGetData = 0 static
Definition at line 143 of file qsslsocket_p.h.
Referenced by ensureCiphersAndCertsLoaded(), and systemCaCertificates().
ptrSecTrustCopyAnchorCertificates
PtrSecTrustCopyAnchorCertificates QSslSocketPrivate::ptrSecTrustCopyAnchorCertificates = 0 static
Definition at line 145 of file qsslsocket_p.h.
Referenced by ensureCiphersAndCertsLoaded(), and systemCaCertificates().
ptrSecTrustSettingsCopyCertificates
PtrSecTrustSettingsCopyCertificates QSslSocketPrivate::ptrSecTrustSettingsCopyCertificates = 0 static
Definition at line 144 of file qsslsocket_p.h.
Referenced by ensureCiphersAndCertsLoaded(), and systemCaCertificates().
readyReadEmittedPointer
bool* QSslSocketPrivate::readyReadEmittedPointer
Definition at line 114 of file qsslsocket_p.h.
Referenced by _q_readyReadSlot(), and QSslSocketBackendPrivate::transmit().
s_libraryLoaded
bool QSslSocketPrivate::s_libraryLoaded = false static private
Definition at line 184 of file qsslsocket_p.h.
Referenced by ensureLibraryLoaded().
s_loadedCiphersAndCerts
bool QSslSocketPrivate::s_loadedCiphersAndCerts = false static private
Definition at line 185 of file qsslsocket_p.h.
Referenced by ensureCiphersAndCertsLoaded().
s_loadRootCertsOnDemand
bool QSslSocketPrivate::s_loadRootCertsOnDemand = false static protected
Definition at line 187 of file qsslsocket_p.h.
Referenced by ensureCiphersAndCertsLoaded(), QSslSocketBackendPrivate::initSslContext(), rootCertOnDemandLoadingSupported(), and setDefaultCaCertificates().
shutdown
bool QSslSocketPrivate::shutdown
Definition at line 111 of file qsslsocket_p.h.
Referenced by QSslSocketBackendPrivate::disconnectFromHost(), init(), and QSslSocketBackendPrivate::transmit().
sslErrors
QList<QSslError> QSslSocketPrivate::sslErrors
Definition at line 117 of file qsslsocket_p.h.
Referenced by QSslSocketBackendPrivate::startHandshake().
verificationPeerName
QString QSslSocketPrivate::verificationPeerName
Definition at line 121 of file qsslsocket_p.h.
Referenced by QSslSocketBackendPrivate::initSslContext(), and QSslSocketBackendPrivate::startHandshake().
The documentation for this class was generated from the following files:
/src/network/ssl/qsslsocket_p.h
/src/network/ssl/qsslsocket.cpp
/src/network/ssl/qsslsocket_openssl.cpp