Qt 4.8: QTest::QTouchEventSequence Class Reference
QTest::QTouchEventSequence Class Reference
The QTouchEventSequence class is used to simulate a sequence of touch events.
#include <qtesttouch.h>
Public Functions
QTouchEventSequence & move (int touchId, const QPoint &pt, QWidget *widget=0)
Adds a move event for touchpoint touchId at position pt to this sequence and returns a reference to this QTouchEventSequence.
QTouchEventSequence & press (int touchId, const QPoint &pt, QWidget *widget=0)
Adds a press event for touchpoint touchId at position pt to this sequence and returns a reference to this QTouchEventSequence.
QTouchEventSequence & release (int touchId, const QPoint &pt, QWidget *widget=0)
Adds a release event for touchpoint touchId at position pt to this sequence and returns a reference to this QTouchEventSequence.
QTouchEventSequence & stationary (int touchId)
Adds a stationary event for touchpoint touchId to this sequence and returns a reference to this QTouchEventSequence.
~QTouchEventSequence ()
Commits this sequence of touch events and frees allocated resources.
Private Functions
void commit ()
QPoint mapToScreen (QWidget *widget, const QPoint &pt)
void operator= (const QTouchEventSequence &)
QTouchEvent::TouchPoint & point (int touchId)
QTouchEventSequence (QWidget *widget, QTouchEvent::DeviceType aDeviceType)
QTouchEventSequence (const QTouchEventSequence &v)
Properties
QTouchEvent::DeviceType deviceType
QMap< int, QTouchEvent::TouchPoint > points
QWidget * targetWidget
Friends
QTouchEventSequence touchEvent (QWidget *, QTouchEvent::DeviceType)
Detailed Description
The QTouchEventSequence class is used to simulate a sequence of touch events.
Attention
Module: QtTest
Since
4.6
To simulate a sequence of touch events on a specific device for a widget, call QTest::touchEvent to create a QTouchEventSequence instance. Add touch events to the sequence by calling press(), move(), release() and stationary(), and let the instance run out of scope to commit the sequence to the event system.
Example:
QWidget widget;
QTest::touchEvent(&widget)
    .press(0, QPoint(10, 10));
QTest::touchEvent(&widget)
    .stationary(0)
    .press(1, QPoint(40, 10));
QTest::touchEvent(&widget)
    .move(0, QPoint(12, 12))
    .move(1, QPoint(45, 5));
QTest::touchEvent(&widget)
    .release(0)
    .release(1);
Definition at line 72 of file qtesttouch.h.
Constructors and Destructors
~QTouchEventSequence()
QTest::QTouchEventSequence::~QTouchEventSequence () inline
Commits this sequence of touch events and frees allocated resources.
Definition at line 75 of file qtesttouch.h.
         {
             commit();
             points.clear();
         }
QTouchEventSequence() [1/2]
QTest::QTouchEventSequence::QTouchEventSequence (QWidget * widget, QTouchEvent::DeviceType aDeviceType) inline private
Definition at line 109 of file qtesttouch.h.
Referenced by QTest::touchEvent().
             : targetWidget(widget), deviceType(aDeviceType)
         {
         }
QTouchEventSequence() [2/2]
QTest::QTouchEventSequence::QTouchEventSequence (const QTouchEventSequence & v) private
Functions
commit()
void QTest::QTouchEventSequence::commit () inline private
Definition at line 128 of file qtesttouch.h.
Referenced by ~QTouchEventSequence().
         {
             qt_translateRawTouchEvent(targetWidget, deviceType, points.values());
             targetWidget = 0;
         }
mapToScreen()
QPoint QTest::QTouchEventSequence::mapToScreen (QWidget * widget, const QPoint & pt) inline private
Definition at line 122 of file qtesttouch.h.
Referenced by move(), press(), and release().
         {
             if (widget)
                 return widget->mapToGlobal(pt);
             return targetWidget ? targetWidget->mapToGlobal(pt) : pt;
         }
move()
QTouchEventSequence & QTest::QTouchEventSequence::move (int touchId, const QPoint & pt, QWidget * widget = 0) inline
Adds a move event for touchpoint touchId at position pt to this sequence and returns a reference to this QTouchEventSequence.
The position pt is interpreted as relative to widget. If widget is the null pointer, then pt is interpreted as relative to the widget provided when instantiating this QTouchEventSequence.
Simulates that the user moved the finger identified by touchId.
Definition at line 87 of file qtesttouch.h.
         {
             QTouchEvent::TouchPoint &p = point(touchId);
             p.setScreenPos(mapToScreen(widget, pt));
             p.setState(Qt::TouchPointMoved);
             return *this;
         }
operator=()
void QTest::QTouchEventSequence::operator= (const QTouchEventSequence &) private
Referenced by QTouchEventSequence().
point()
QTouchEvent::TouchPoint& QTest::QTouchEventSequence::point (int touchId) inline private
Definition at line 116 of file qtesttouch.h.
Referenced by move(), press(), release(), and stationary().
         {
             if (!points.contains(touchId))
                 points[touchId] = QTouchEvent::TouchPoint(touchId);
             return points[touchId];
         }
press()
QTouchEventSequence & QTest::QTouchEventSequence::press (int touchId, const QPoint & pt, QWidget * widget = 0) inline
Adds a press event for touchpoint touchId at position pt to this sequence and returns a reference to this QTouchEventSequence.
The position pt is interpreted as relative to widget. If widget is the null pointer, then pt is interpreted as relative to the widget provided when instantiating this QTouchEventSequence.
Simulates that the user pressed the touch screen or pad with the finger identified by touchId.
Definition at line 80 of file qtesttouch.h.
         {
             QTouchEvent::TouchPoint &p = point(touchId);
             p.setScreenPos(mapToScreen(widget, pt));
             p.setState(Qt::TouchPointPressed);
             return *this;
         }
release()
QTouchEventSequence & QTest::QTouchEventSequence::release (int touchId, const QPoint & pt, QWidget * widget = 0) inline
Adds a release event for touchpoint touchId at position pt to this sequence and returns a reference to this QTouchEventSequence.
The position pt is interpreted as relative to widget. If widget is the null pointer, then pt is interpreted as relative to the widget provided when instantiating this QTouchEventSequence.
Simulates that the user lifted the finger identified by touchId.
Definition at line 94 of file qtesttouch.h.
         {
             QTouchEvent::TouchPoint &p = point(touchId);
             p.setScreenPos(mapToScreen(widget, pt));
             p.setState(Qt::TouchPointReleased);
             return *this;
         }
stationary()
QTouchEventSequence & QTest::QTouchEventSequence::stationary (int touchId) inline
Adds a stationary event for touchpoint touchId to this sequence and returns a reference to this QTouchEventSequence.
Simulates that the user did not move the finger identified by touchId.
Definition at line 101 of file qtesttouch.h.
         {
             QTouchEvent::TouchPoint &p = point(touchId);
             p.setState(Qt::TouchPointStationary);
             return *this;
         }
Friends and Related Functions
touchEvent
QTouchEventSequence touchEvent (QWidget * widget = 0, QTouchEvent::DeviceType deviceType = QTouchEvent::TouchScreen) friend
Definition at line 141 of file qtesttouch.h.
     {
         return QTouchEventSequence(widget, deviceType);
     }
Properties
deviceType
QTouchEvent::DeviceType QTest::QTouchEventSequence::deviceType private
Definition at line 136 of file qtesttouch.h.
Referenced by commit(), and QTest::touchEvent().
points
QMap<int, QTouchEvent::TouchPoint> QTest::QTouchEventSequence::points private
Definition at line 134 of file qtesttouch.h.
Referenced by commit(), point(), and ~QTouchEventSequence().
targetWidget
QWidget* QTest::QTouchEventSequence::targetWidget private
Definition at line 135 of file qtesttouch.h.
Referenced by commit(), and mapToScreen().
The documentation for this class was generated from the following files:
/src/testlib/qtesttouch.h
/src/testlib/qtestcase.cpp