Qt 4.8: QAccessibleTextWidget Class Reference
QAccessibleTextWidget Class Reference abstract
#include <qaccessiblewidgets.h>
Public Functions
void addSelection (int startOffset, int endOffset)
QString attributes (int offset, int *startOffset, int *endOffset)
int characterCount ()
QRect characterRect (int offset, QAccessible2::CoordinateType coordType)
void copyText (int startOffset, int endOffset)
int cursorPosition ()
void cutText (int startOffset, int endOffset)
void deleteText (int startOffset, int endOffset)
void insertText (int offset, const QString &text)
int offsetAtPoint (const QPoint &point, QAccessible2::CoordinateType coordType)
void pasteText (int offset)
QAccessibleTextWidget (QWidget *o, Role r=EditableText, const QString &name=QString())
void removeSelection (int selectionIndex)
void replaceText (int startOffset, int endOffset, const QString &text)
void selection (int selectionIndex, int *startOffset, int *endOffset)
int selectionCount ()
void setAttributes (int startOffset, int endOffset, const QString &attributes)
void setCursorPosition (int position)
void setSelection (int selectionIndex, int startOffset, int endOffset)
QString text (int startOffset, int endOffset)
QString textAfterOffset (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset)
QString textAtOffset (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset)
QString textBeforeOffset (int offset, QAccessible2::BoundaryType boundaryType, int *startOffset, int *endOffset)
Public Functions inherited from QAccessibleWidgetEx
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethodEx (Method method, int child, const QVariantList &params)
int navigate (RelationFlag rel, int entry, QAccessibleInterface **target) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleObjectEx
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Public Functions inherited from QAccessibleTextInterface
QAccessible2Interface * qAccessibleTextCastHelper ()
virtual void scrollToSubstring (int startIndex, int endIndex)=0
virtual ~QAccessibleTextInterface ()
Public Functions inherited from QAccessible2Interface
virtual ~QAccessible2Interface ()
Public Functions inherited from QAccessibleEditableTextInterface
QAccessible2Interface * qAccessibleEditableTextCastHelper ()
virtual ~QAccessibleEditableTextInterface ()
Protected Functions
QPair< int, int > getBoundaries (int offset, QAccessible2::BoundaryType boundaryType)
virtual QPoint scrollBarPosition () const
virtual void setTextCursor (const QTextCursor &)=0
virtual QTextCursor textCursor () const =0
QTextCursor textCursorForRange (int startOffset, int endOffset) const
virtual QTextDocument * textDocument () const =0
virtual QWidget * viewport () const =0
Protected Functions inherited from QAccessibleWidgetEx
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 72 of file qaccessiblewidgets.h.
Constructors and Destructors
QAccessibleTextWidget()
QAccessibleTextWidget::QAccessibleTextWidget (QWidget * o, QAccessible::Role r = EditableText, const QString & name = QString())
Definition at line 1399 of file qaccessiblewidgets.cpp.
                                                                                               :
     QAccessibleWidgetEx(o, r, name)
 {
 }
Functions
addSelection()
void QAccessibleTextWidget::addSelection (int startOffset, int endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1716 of file qaccessiblewidgets.cpp.
 {
     setSelection(0, startOffset, endOffset);
 }
attributes()
QString QAccessibleTextWidget::attributes (int offset, int * startOffset, int * endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1473 of file qaccessiblewidgets.cpp.
 {
     /* The list of attributes can be found at:
      http://linuxfoundation.org/collaborate/workgroups/accessibility/iaccessible2/textattributes
     */
     if (offset >= characterCount()) {
         *startOffset = -1;
         *endOffset = -1;
         return QString();
     }
     QMap<QString, QString> attrs;
     QTextCursor cursor = textCursor();
     //cursor.charFormat returns the format of the previous character
     cursor.setPosition(offset + 1);
     QTextCharFormat charFormat = cursor.charFormat();
     cursor.setPosition(offset);
     QTextBlockFormat blockFormat = cursor.blockFormat();
     QTextCharFormat charFormatComp;
     QTextBlockFormat blockFormatComp;
     *startOffset = offset;
     cursor.setPosition(*startOffset);
     while (*startOffset > 0) {
         charFormatComp = cursor.charFormat();
         cursor.setPosition(*startOffset - 1);
         blockFormatComp = cursor.blockFormat();
         if ((charFormat == charFormatComp) && (blockFormat == blockFormatComp))
             (*startOffset)--;
         else
             break;
     }
     int limit = characterCount() + 1;
     *endOffset = offset + 1;
     cursor.setPosition(*endOffset);
     while (*endOffset < limit) {
         blockFormatComp = cursor.blockFormat();
         cursor.setPosition(*endOffset + 1);
         charFormatComp = cursor.charFormat();
         if ((charFormat == charFormatComp) && (cursor.blockFormat() == blockFormatComp))
             (*endOffset)++;
         else
             break;
     }
     QString family = charFormat.fontFamily();
     if (!family.isEmpty()) {
         family = family.replace('\\',"\\\\");
         family = family.replace(':',"\\:");
         family = family.replace(',',"\\,");
         family = family.replace('=',"\\=");
         family = family.replace(';',"\\;");
         family = family.replace('\"',"\\\"");
         attrs["font-family"] = '"'+family+'"';
     }
     int fontSize = int(charFormat.fontPointSize());
     if (fontSize)
         attrs["font-size"] = QString::number(fontSize).append("pt");
     //Different weight values are not handled
     attrs["font-weight"] = (charFormat.fontWeight() > QFont::Normal) ? "bold" : "normal";
     QFont::Style style = charFormat.font().style();
     attrs["font-style"] = (style == QFont::StyleItalic) ? "italic" : ((style == QFont::StyleOblique) ? "oblique": "normal");
     attrs["text-underline-style"] = charFormat.font().underline() ? "solid" : "none";
     QTextCharFormat::VerticalAlignment alignment = charFormat.verticalAlignment();
     attrs["text-position"] = (alignment == QTextCharFormat::AlignSubScript) ? "sub" : ((alignment == QTextCharFormat::AlignSuperScript) ? "super" : "baseline" );
     QBrush background = charFormat.background();
     if (background.style() == Qt::SolidPattern) {
         attrs["background-color"] = QString("rgb(%1,%2,%3)").arg(background.color().red()).arg(background.color().green()).arg(background.color().blue());
     }
     QBrush foreground = charFormat.foreground();
     if (foreground.style() == Qt::SolidPattern) {
         attrs["color"] = QString("rgb(%1,%2,%3)").arg(foreground.color().red()).arg(foreground.color().green()).arg(foreground.color().blue());
     }
     switch (blockFormat.alignment() & (Qt::AlignLeft | Qt::AlignRight | Qt::AlignHCenter | Qt::AlignJustify)) {
     case Qt::AlignLeft:
         attrs["text-align"] = "left";
         break;
     case Qt::AlignRight:
         attrs["text-align"] = "right";
         break;
     case Qt::AlignHCenter:
         attrs["text-align"] = "center";
         break;
     case Qt::AlignJustify:
         attrs["text-align"] = "left";
         break;
     }
     QString result;
     foreach (const QString &attributeName, attrs.keys()) {
         result.append(attributeName).append(':').append(attrs[attributeName]).append(';');
     }
     return result;
 }
characterCount()
int QAccessibleTextWidget::characterCount () virtual
Implements QAccessibleTextInterface.
Definition at line 1742 of file qaccessiblewidgets.cpp.
Referenced by attributes(), and getBoundaries().
 {
     QTextCursor cursor = textCursor();
     cursor.movePosition(QTextCursor::End);
     return cursor.position();
 }
characterRect()
QRect QAccessibleTextWidget::characterRect (int offset, QAccessible2::CoordinateType coordType) virtual
Implements QAccessibleTextInterface.
Definition at line 1412 of file qaccessiblewidgets.cpp.
 {
     QTextBlock block = textDocument()->findBlock(offset);
     if (!block.isValid())
         return QRect();
     QTextLayout *layout = block.layout();
     QPointF layoutPosition = layout->position();
     int relativeOffset = offset - block.position();
     QTextLine line = layout->lineForTextPosition(relativeOffset);
     QRect r;
     if (line.isValid()) {
         qreal x = line.cursorToX(relativeOffset);
         qreal w = 0;
         if ((relativeOffset - line.textStart())< line.textLength()) {
             w = line.cursorToX(relativeOffset + 1) - x;
         } else {
             // If the width of a character is not known, IAccessible2 tells to return the width of a default character
             int averageCharWidth = QFontMetrics(textCursor().charFormat().font()).averageCharWidth();
             if (block.blockFormat().layoutDirection()  == Qt::RightToLeft)
                 averageCharWidth *= -1;
             r.setWidth(averageCharWidth);
         }
         int height = line.height();
         // make sure that height does not include leading. (only ascent + descent + 1)
         if (line.leadingIncluded())
             height -= qRound(line.leading());
         r = QRect(layoutPosition.x() + x, layoutPosition.y() + line.y(),
                   w, height);
         if (coordType == RelativeToScreen) {
             r.moveTo(viewport()->mapToGlobal(r.topLeft()));
         }
         r.translate(-scrollBarPosition());
     }
     return r;
 }
copyText()
void QAccessibleTextWidget::copyText (int startOffset, int endOffset) virtual
Implements QAccessibleEditableTextInterface.
Reimplemented in QAccessibleTextEdit.
Definition at line 1781 of file qaccessiblewidgets.cpp.
 {
 #ifndef QT_NO_CLIPBOARD
     QString text = this->text(startOffset, endOffset);
     QApplication::clipboard()->setText(text);
 #endif
 }
cursorPosition()
int QAccessibleTextWidget::cursorPosition () virtual
Implements QAccessibleTextInterface.
Definition at line 1583 of file qaccessiblewidgets.cpp.
 {
     return textCursor().position();
 }
cutText()
void QAccessibleTextWidget::cutText (int startOffset, int endOffset) virtual
Implements QAccessibleEditableTextInterface.
Reimplemented in QAccessibleTextEdit.
Definition at line 1789 of file qaccessiblewidgets.cpp.
 {
 #ifndef QT_NO_CLIPBOARD
     QString text = this->text(startOffset, endOffset);
     QApplication::clipboard()->setText(text);
     deleteText(startOffset, endOffset);
 #endif
 }
deleteText()
void QAccessibleTextWidget::deleteText (int startOffset, int endOffset) virtual
Implements QAccessibleEditableTextInterface.
Definition at line 1758 of file qaccessiblewidgets.cpp.
Referenced by cutText().
 {
     QTextCursor cursor = textCursorForRange(startOffset, endOffset);
     cursor.removeSelectedText();
 }
getBoundaries()
QPair< int, int > QAccessibleTextWidget::getBoundaries (int offset, QAccessible2::BoundaryType boundaryType) protected
Definition at line 1615 of file qaccessiblewidgets.cpp.
Referenced by textAfterOffset(), textAtOffset(), and textBeforeOffset().
 {
     if (offset >= characterCount())
         return QPair<int, int>(characterCount(), characterCount());
     if (offset < 0)
         return QPair<int, int>(0, 0);
     QTextCursor cursor = textCursor();
     QPair<int, int> result;
     cursor.setPosition(offset);
     switch (boundaryType) {
     case CharBoundary:
         result.first = cursor.position();
         cursor.movePosition(QTextCursor::NextCharacter, QTextCursor::KeepAnchor);
         result.second = cursor.position();
         break;
     case WordBoundary:
         cursor.movePosition(QTextCursor::StartOfWord, QTextCursor::MoveAnchor);
         result.first = cursor.position();
         cursor.movePosition(QTextCursor::EndOfWord, QTextCursor::KeepAnchor);
         result.second = cursor.position();
         break;
     case SentenceBoundary:
         // TODO - what's a sentence?
     case LineBoundary:
         cursor.movePosition(QTextCursor::StartOfLine, QTextCursor::MoveAnchor);
         result.first = cursor.position();
         cursor.movePosition(QTextCursor::EndOfLine, QTextCursor::KeepAnchor);
         result.second = cursor.position();
         break;
     case ParagraphBoundary:
         cursor.movePosition(QTextCursor::StartOfBlock, QTextCursor::MoveAnchor);
         result.first = cursor.position();
         cursor.movePosition(QTextCursor::EndOfBlock, QTextCursor::KeepAnchor);
         result.second = cursor.position();
         break;
     case NoBoundary:
         result.first = 0;
         result.second = characterCount();
         break;
     default:
         qDebug("QAccessibleTextWidget::getBoundaries: Unknown boundary type %d", boundaryType);
         result.first = -1;
         result.second = -1;
     }
     return result;
 }
insertText()
void QAccessibleTextWidget::insertText (int offset, const QString & text) virtual
Implements QAccessibleEditableTextInterface.
Definition at line 1765 of file qaccessiblewidgets.cpp.
Referenced by pasteText().
 {
     QTextCursor cursor = textCursor();
     cursor.setPosition(offset);
     cursor.insertText(text);
 }
offsetAtPoint()
int QAccessibleTextWidget::offsetAtPoint (const QPoint & point, QAccessible2::CoordinateType coordType) virtual
Implements QAccessibleTextInterface.
Definition at line 1457 of file qaccessiblewidgets.cpp.
 {
     QPoint p = point;
     if (coordType == RelativeToScreen)
         p = viewport()->mapFromGlobal(p);
     p += scrollBarPosition();
     return textDocument()->documentLayout()->hitTest(p, Qt::ExactHit);
 }
pasteText()
void QAccessibleTextWidget::pasteText (int offset) virtual
Implements QAccessibleEditableTextInterface.
Reimplemented in QAccessibleTextEdit.
Definition at line 1798 of file qaccessiblewidgets.cpp.
 {
 #ifndef QT_NO_CLIPBOARD
     QString text = QApplication::clipboard()->text();
     insertText(offset, text);
 #endif
 }
removeSelection()
void QAccessibleTextWidget::removeSelection (int selectionIndex) virtual
Implements QAccessibleTextInterface.
Definition at line 1721 of file qaccessiblewidgets.cpp.
 {
     if (selectionIndex != 0)
         return;
     QTextCursor cursor = textCursor();
     cursor.clearSelection();
     setTextCursor(cursor);
 }
replaceText()
void QAccessibleTextWidget::replaceText (int startOffset, int endOffset, const QString & text) virtual
Implements QAccessibleEditableTextInterface.
Definition at line 1773 of file qaccessiblewidgets.cpp.
 {
     QTextCursor cursor = textCursorForRange(startOffset, endOffset);
     cursor.removeSelectedText();
     cursor.insertText(text);
 }
scrollBarPosition()
QPoint QAccessibleTextWidget::scrollBarPosition () const protected virtual
Reimplemented in QAccessibleTextEdit, and QAccessiblePlainTextEdit.
Definition at line 1610 of file qaccessiblewidgets.cpp.
Referenced by characterRect(), and offsetAtPoint().
 {
     return QPoint(0, 0);
 }
selection()
void QAccessibleTextWidget::selection (int selectionIndex, int * startOffset, int * endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1588 of file qaccessiblewidgets.cpp.
 {
     *startOffset = *endOffset = 0;
     QTextCursor cursor = textCursor();
     if (selectionIndex != 0 || !cursor.hasSelection())
         return;
     *startOffset = cursor.selectionStart();
     *endOffset = cursor.selectionEnd();
 }
selectionCount()
int QAccessibleTextWidget::selectionCount () virtual
Implements QAccessibleTextInterface.
Definition at line 1468 of file qaccessiblewidgets.cpp.
 {
     return textCursor().hasSelection() ? 1 : 0;
 }
setAttributes()
void QAccessibleTextWidget::setAttributes (int startOffset, int endOffset, const QString & attributes) virtual
Implements QAccessibleEditableTextInterface.
Reimplemented in QAccessibleTextEdit.
Definition at line 1404 of file qaccessiblewidgets.cpp.
 {
     //TODO: not implemented
     Q_UNUSED(startOffset);
     Q_UNUSED(endOffset);
     Q_UNUSED(attributes);
 }
setCursorPosition()
void QAccessibleTextWidget::setCursorPosition (int position) virtual
Implements QAccessibleTextInterface.
Definition at line 1709 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleTextEdit::invokeMethodEx().
 {
     QTextCursor cursor = textCursor();
     cursor.setPosition(position);
     setTextCursor(cursor);
 }
setSelection()
void QAccessibleTextWidget::setSelection (int selectionIndex, int startOffset, int endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1731 of file qaccessiblewidgets.cpp.
Referenced by addSelection().
 {
     if (selectionIndex != 0)
         return;
     QTextCursor cursor = textCursor();
     cursor.setPosition(startOffset, QTextCursor::MoveAnchor);
     cursor.setPosition(endOffset, QTextCursor::KeepAnchor);
     setTextCursor(cursor);
 }
setTextCursor()
virtual void QAccessibleTextWidget::setTextCursor (const QTextCursor &) protected pure virtual
Implemented in QAccessibleTextEdit, and QAccessiblePlainTextEdit.
Referenced by removeSelection(), setCursorPosition(), and setSelection().
text()
QString QAccessibleTextWidget::text (int startOffset, int endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1600 of file qaccessiblewidgets.cpp.
Referenced by copyText(), cutText(), pasteText(), textAfterOffset(), textAtOffset(), and textBeforeOffset().
 {
     QTextCursor cursor = textCursor();
     cursor.setPosition(startOffset, QTextCursor::MoveAnchor);
     cursor.setPosition(endOffset, QTextCursor::KeepAnchor);
     return cursor.selectedText();
 }
textAfterOffset()
QString QAccessibleTextWidget::textAfterOffset (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1680 of file qaccessiblewidgets.cpp.
 {
     Q_ASSERT(startOffset);
     Q_ASSERT(endOffset);
     QPair<int, int> boundaries = getBoundaries(offset, boundaryType);
     boundaries = getBoundaries(boundaries.second, boundaryType);
     *startOffset = boundaries.first;
     *endOffset = boundaries.second;
     return text(boundaries.first, boundaries.second);
 }
textAtOffset()
QString QAccessibleTextWidget::textAtOffset (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1695 of file qaccessiblewidgets.cpp.
 {
     Q_ASSERT(startOffset);
     Q_ASSERT(endOffset);
     QPair<int, int> boundaries = getBoundaries(offset, boundaryType);
     *startOffset = boundaries.first;
     *endOffset = boundaries.second;
     return text(boundaries.first, boundaries.second);
 }
textBeforeOffset()
QString QAccessibleTextWidget::textBeforeOffset (int offset, QAccessible2::BoundaryType boundaryType, int * startOffset, int * endOffset) virtual
Implements QAccessibleTextInterface.
Definition at line 1665 of file qaccessiblewidgets.cpp.
 {
     Q_ASSERT(startOffset);
     Q_ASSERT(endOffset);
     QPair<int, int> boundaries = getBoundaries(offset, boundaryType);
     boundaries = getBoundaries(boundaries.first - 1, boundaryType);
     *startOffset = boundaries.first;
     *endOffset = boundaries.second;
     return text(boundaries.first, boundaries.second);
 }
textCursor()
virtual QTextCursor QAccessibleTextWidget::textCursor () const protected pure virtual
Implemented in QAccessibleTextEdit, and QAccessiblePlainTextEdit.
Referenced by attributes(), characterCount(), characterRect(), cursorPosition(), getBoundaries(), insertText(), removeSelection(), selection(), selectionCount(), setCursorPosition(), setSelection(), text(), and textCursorForRange().
textCursorForRange()
QTextCursor QAccessibleTextWidget::textCursorForRange (int startOffset, int endOffset) const protected
Definition at line 1749 of file qaccessiblewidgets.cpp.
Referenced by QAccessibleTextEdit::copyText(), QAccessibleTextEdit::cutText(), deleteText(), and replaceText().
 {
     QTextCursor cursor = textCursor();
     cursor.setPosition(startOffset, QTextCursor::MoveAnchor);
     cursor.setPosition(endOffset, QTextCursor::KeepAnchor);
     return cursor;
 }
textDocument()
virtual QTextDocument* QAccessibleTextWidget::textDocument () const protected pure virtual
Implemented in QAccessibleTextEdit, and QAccessiblePlainTextEdit.
Referenced by characterRect(), and offsetAtPoint().
viewport()
virtual QWidget* QAccessibleTextWidget::viewport () const protected pure virtual
Implemented in QAccessibleTextEdit, and QAccessiblePlainTextEdit.
Referenced by characterRect(), and offsetAtPoint().
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/qaccessiblewidgets.h
/src/plugins/accessible/widgets/qaccessiblewidgets.cpp