Qt 4.8: QBasicAtomicInt Class Reference
QBasicAtomicInt Class Reference
#include <qbasicatomic.h>
Public Functions
bool deref ()
int fetchAndAddAcquire (int valueToAdd)
int fetchAndAddOrdered (int valueToAdd)
int fetchAndAddRelaxed (int valueToAdd)
int fetchAndAddRelease (int valueToAdd)
int fetchAndStoreAcquire (int newValue)
int fetchAndStoreOrdered (int newValue)
int fetchAndStoreRelaxed (int newValue)
int fetchAndStoreRelease (int newValue)
operator int () const
bool operator! () const
bool operator!= (int value) const
QBasicAtomicInt & operator= (int value)
bool operator== (int value) const
bool ref ()
bool testAndSetAcquire (int expectedValue, int newValue)
bool testAndSetOrdered (int expectedValue, int newValue)
bool testAndSetRelaxed (int expectedValue, int newValue)
bool testAndSetRelease (int expectedValue, int newValue)
Static Public Functions
static bool isFetchAndAddNative ()
static bool isFetchAndAddWaitFree ()
static bool isFetchAndStoreNative ()
static bool isFetchAndStoreWaitFree ()
static bool isReferenceCountingNative ()
static bool isReferenceCountingWaitFree ()
static bool isTestAndSetNative ()
static bool isTestAndSetWaitFree ()
Public Variables
volatile int _q_value
Detailed Description
Definition at line 53 of file qbasicatomic.h.
Functions
deref()
bool QBasicAtomicInt::deref () inline
Definition at line 500 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QByteArray::clear(), QRegion::copy(), QEglContextTracker::deref(), QListData::detach(), QGLColormap::detach_helper(), QList< QPostEvent >::detach_helper(), QList< QPostEvent >::detach_helper_grow(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QTest::messageHandler(), QGLColormap::operator=(), QRegion::operator=(), QString::operator=(), QByteArray::operator=(), qt_atomic_tasb(), qt_bitmapToRegion(), qt_removeObject(), QByteArray::realloc(), QString::realloc(), QString::resize(), QByteArray::resize(), QByteArray::~QByteArray(), QGLColormap::~QGLColormap(), QNetworkAccessBackendFactoryData::~QNetworkAccessBackendFactoryData(), QRegion::~QRegion(), QSqlDatabase::~QSqlDatabase(), and QString::~QString().
 {
     return q_atomic_decrement(&_q_value) != 0;
 }
fetchAndAddAcquire()
int QBasicAtomicInt::fetchAndAddAcquire (int valueToAdd) inline
Definition at line 540 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), fetchAndAddOrdered(), QBasicAtomicPointer< QBrushData >::fetchAndAddOrdered(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and qt_atomic_tasb().
 {
     return q_atomic_fetch_and_add_acquire_int(&_q_value, valueToAdd);
 }
fetchAndAddOrdered()
int QBasicAtomicInt::fetchAndAddOrdered (int valueToAdd) inline
Definition at line 615 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), and qt_atomic_tasb().
 {
     return fetchAndAddAcquire(valueToAdd);
 }
fetchAndAddRelaxed()
int QBasicAtomicInt::fetchAndAddRelaxed (int valueToAdd) inline
Definition at line 535 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QProcessManager::add(), QX11PixmapData::convertToARGB32(), QX11PixmapData::copy(), QUuid::createUuid(), QX11PixmapData::fromImage(), QSocks5SocketEngine::initialize(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QHostInfo::lookupHost(), QFtpCommand::QFtpCommand(), QHttpRequest::QHttpRequest(), qt_atomic_tasb(), QX11PixmapData::resize(), and QX11PixmapData::transformed().
 {
     return q_atomic_fetch_and_add_int(&_q_value, valueToAdd);
 }
fetchAndAddRelease()
int QBasicAtomicInt::fetchAndAddRelease (int valueToAdd) inline
Definition at line 545 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and qt_atomic_tasb().
 {
     return q_atomic_fetch_and_add_release_int(&_q_value, valueToAdd);
 }
fetchAndStoreAcquire()
int QBasicAtomicInt::fetchAndStoreAcquire (int newValue) inline
Definition at line 525 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), fetchAndStoreOrdered(), QBasicAtomicPointer< QBrushData >::fetchAndStoreOrdered(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and qt_atomic_tasb().
 {
     return q_atomic_fetch_and_store_acquire_int(&_q_value, newValue);
 }
fetchAndStoreOrdered()
int QBasicAtomicInt::fetchAndStoreOrdered (int newValue) inline
Definition at line 610 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), and qt_atomic_tasb().
 {
     return fetchAndStoreAcquire(newValue);
 }
fetchAndStoreRelaxed()
int QBasicAtomicInt::fetchAndStoreRelaxed (int newValue) inline
Definition at line 520 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and qt_atomic_tasb().
 {
     return q_atomic_set_int(&_q_value, newValue);
 }
fetchAndStoreRelease()
int QBasicAtomicInt::fetchAndStoreRelease (int newValue) inline
Definition at line 530 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), and qt_atomic_tasb().
 {
     return q_atomic_fetch_and_store_release_int(&_q_value, newValue);
 }
isFetchAndAddNative()
bool QBasicAtomicInt::isFetchAndAddNative () inline static
Definition at line 72 of file qatomic_alpha.h.
 { return true; }
isFetchAndAddWaitFree()
bool QBasicAtomicInt::isFetchAndAddWaitFree () inline static
Definition at line 74 of file qatomic_alpha.h.
 { return false; }
isFetchAndStoreNative()
bool QBasicAtomicInt::isFetchAndStoreNative () inline static
Definition at line 65 of file qatomic_alpha.h.
 { return true; }
isFetchAndStoreWaitFree()
bool QBasicAtomicInt::isFetchAndStoreWaitFree () inline static
Definition at line 67 of file qatomic_alpha.h.
 { return false; }
isReferenceCountingNative()
bool QBasicAtomicInt::isReferenceCountingNative () inline static
Definition at line 51 of file qatomic_alpha.h.
 { return true; }
isReferenceCountingWaitFree()
bool QBasicAtomicInt::isReferenceCountingWaitFree () inline static
Definition at line 53 of file qatomic_alpha.h.
 { return false; }
isTestAndSetNative()
bool QBasicAtomicInt::isTestAndSetNative () inline static
Definition at line 58 of file qatomic_alpha.h.
 { return true; }
isTestAndSetWaitFree()
bool QBasicAtomicInt::isTestAndSetWaitFree () inline static
Definition at line 60 of file qatomic_alpha.h.
 { return false; }
operator int()
QBasicAtomicInt::operator int () const inline
Definition at line 83 of file qbasicatomic.h.
     {
         return _q_value;
     }
operator!()
bool QBasicAtomicInt::operator! () const inline
Definition at line 78 of file qbasicatomic.h.
     {
         return _q_value == 0;
     }
operator!=()
bool QBasicAtomicInt::operator!= (int value) const inline
Definition at line 73 of file qbasicatomic.h.
     {
         return _q_value != value;
     }
operator=()
QBasicAtomicInt& QBasicAtomicInt::operator= (int value) inline
Definition at line 88 of file qbasicatomic.h.
     {
 #ifdef QT_ARCH_PARISC
         this->_q_lock[0] = this->_q_lock[1] = this->_q_lock[2] = this->_q_lock[3] = -1;
 #endif
         _q_value = value;
         return *this;
     }
operator==()
bool QBasicAtomicInt::operator== (int value) const inline
Definition at line 68 of file qbasicatomic.h.
     {
         return _q_value == value;
     }
ref()
bool QBasicAtomicInt::ref () inline
Definition at line 495 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QByteArray::clear(), QString::fromAscii_helper(), QString::fromLatin1_helper(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QGLColormap::operator=(), QRegion::operator=(), QLinkedList< JSC::Identifier >::operator=(), QString::operator=(), QContiguousCache< T >::operator=(), QList< QPostEvent >::operator=(), QVector< QPoint >::operator=(), QByteArray::operator=(), QMap< int, QFrameInfo >::operator=(), QHash< QExplicitlySharedDataPointer, QHash >::operator=(), QByteArray::QByteArray(), QGLColormap::QGLColormap(), QNetworkAccessBackendFactoryData::QNetworkAccessBackendFactoryData(), QRegion::QRegion(), QSqlDatabase::QSqlDatabase(), QString::QString(), qt_addObject(), qt_atomic_tasb(), qt_bitmapToRegion(), QEglContextTracker::ref(), QString::resize(), QByteArray::resize(), QString::simplified(), QByteArray::trimmed(), and QString::trimmed().
 {
     return q_atomic_increment(&_q_value) != 0;
 }
testAndSetAcquire()
bool QBasicAtomicInt::testAndSetAcquire (int expectedValue, int newValue) inline
Definition at line 510 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), qt_atomic_tasb(), testAndSetOrdered(), and QBasicAtomicPointer< QBrushData >::testAndSetOrdered().
 {
     return q_atomic_test_and_set_acquire_int(&_q_value, expectedValue, newValue) != 0;
 }
testAndSetOrdered()
bool QBasicAtomicInt::testAndSetOrdered (int expectedValue, int newValue) inline
Definition at line 605 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), and qt_atomic_tasb().
 {
     return testAndSetAcquire(expectedValue, newValue);
 }
testAndSetRelaxed()
bool QBasicAtomicInt::testAndSetRelaxed (int expectedValue, int newValue) inline
Definition at line 505 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QAbstractEventDispatcherPrivate::allocateTimerId(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), FAREnforcer::logAuthAttempt(), qt_atomic_tasb(), qt_init_picture_handlers(), and QVariantAnimationPrivate::setCurrentValueForProgress().
 {
     return q_atomic_test_and_set_int(&_q_value, expectedValue, newValue) != 0;
 }
testAndSetRelease()
bool QBasicAtomicInt::testAndSetRelease (int expectedValue, int newValue) inline
Definition at line 515 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), qt_atomic_tasb(), and QAbstractEventDispatcherPrivate::releaseTimerId().
 {
     return q_atomic_test_and_set_release_int(&_q_value, expectedValue, newValue) != 0;
 }
Properties
_q_value
volatile int QBasicAtomicInt::_q_value
Definition at line 64 of file qbasicatomic.h.
Referenced by _q_ia64_fetchadd_immediate(), deref(), fetchAndAddAcquire(), QBasicAtomicPointer< QBrushData >::fetchAndAddAcquire(), fetchAndAddRelaxed(), QBasicAtomicPointer< QBrushData >::fetchAndAddRelaxed(), fetchAndAddRelease(), QBasicAtomicPointer< QBrushData >::fetchAndAddRelease(), fetchAndStoreAcquire(), QBasicAtomicPointer< QBrushData >::fetchAndStoreAcquire(), fetchAndStoreRelaxed(), QBasicAtomicPointer< QBrushData >::fetchAndStoreRelaxed(), fetchAndStoreRelease(), QBasicAtomicPointer< QBrushData >::fetchAndStoreRelease(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QAtomicInt::QAtomicInt(), qt_atomic_tasb(), ref(), testAndSetAcquire(), QBasicAtomicPointer< QBrushData >::testAndSetAcquire(), testAndSetRelaxed(), QBasicAtomicPointer< QBrushData >::testAndSetRelaxed(), testAndSetRelease(), QBasicAtomicPointer< QBrushData >::testAndSetRelease(), and QMutexPrivate::wait().
The documentation for this class was generated from the following files:
/src/corelib/thread/qbasicatomic.h
/src/corelib/arch/qatomic_alpha.h
/src/corelib/arch/qatomic_armv5.h
/src/corelib/arch/qatomic_armv6.h
/src/corelib/arch/qatomic_avr32.h
/src/corelib/arch/qatomic_bfin.h
/src/corelib/arch/qatomic_bootstrap.h
/src/corelib/arch/qatomic_generic.h
/src/corelib/arch/qatomic_i386.h
/src/corelib/arch/qatomic_ia64.h
/src/corelib/arch/qatomic_integrity.h
/src/corelib/arch/qatomic_m68k.h
/src/corelib/arch/qatomic_mips.h
/src/corelib/arch/qatomic_parisc.h
/src/corelib/arch/qatomic_powerpc.h
/src/corelib/arch/qatomic_s390.h
/src/corelib/arch/qatomic_sh.h
/src/corelib/arch/qatomic_sh4a.h
/src/corelib/arch/qatomic_sparc.h
/src/corelib/arch/qatomic_vxworks.h
/src/corelib/arch/qatomic_x86_64.h