Qt 4.8: QAnimationGroup Class Reference
QAnimationGroup Class Reference
The QAnimationGroup class is an abstract base class for groups of animations.
#include <qanimationgroup.h>
Public Functions
void addAnimation (QAbstractAnimation *animation)
Adds animation to this group.
QAbstractAnimation * animationAt (int index) const
Returns a pointer to the animation at index in this group.
int animationCount () const
Returns the number of animations managed by this group.
void clear ()
Removes and deletes all animations in this animation group, and resets the current time to 0.
int indexOfAnimation (QAbstractAnimation *animation) const
Returns the index of animation.
void insertAnimation (int index, QAbstractAnimation *animation)
Inserts animation into this animation group at index.
QAnimationGroup (QObject *parent=0)
Constructs a QAnimationGroup.
void removeAnimation (QAbstractAnimation *animation)
Removes animation from this group.
QAbstractAnimation * takeAnimation (int index)
Returns the animation at index and removes it from the animation group.
~QAnimationGroup ()
Destroys the animation group.
Public Functions inherited from QAbstractAnimation
int currentLoop () const
int currentLoopTime () const
Returns the current time inside the current loop.
int currentTime () const
Direction direction () const
virtual int duration () const =0
QAnimationGroup * group () const
If this animation is part of a QAnimationGroup, this function returns a pointer to the group; otherwise, it returns 0.
int loopCount () const
QAbstractAnimation (QObject *parent=0)
Constructs the QAbstractAnimation base class, and passes parent to QObject's constructor.
void setDirection (Direction direction)
void setLoopCount (int loopCount)
State state () const
int totalDuration () const
Returns the total and effective duration of the animation, including the loop count.
virtual ~QAbstractAnimation ()
Stops the animation if it's running, then destroys the QAbstractAnimation.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *event)
Reimplemented Function
QAnimationGroup (QAnimationGroupPrivate &dd, QObject *parent)
Protected Functions inherited from QAbstractAnimation
QAbstractAnimation (QAbstractAnimationPrivate &dd, QObject *parent=0)
virtual void updateCurrentTime (int currentTime)=0
This pure virtual function is called every time the animation's currentTime changes.
virtual void updateDirection (QAbstractAnimation::Direction direction)
This virtual function is called by QAbstractAnimation when the direction of the animation is changed.
virtual void updateState (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
This virtual function is called by QAbstractAnimation when the state of the animation is changed from oldState to newState.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Types inherited from QAbstractAnimation
enum DeletionPolicy { KeepWhenStopped = 0, DeleteWhenStopped }
enum Direction { Forward, Backward }
This enum describes the direction of the animation when in Running state.
enum State { Stopped, Paused, Running }
This enum describes the state of the animation.
Public Slots inherited from QAbstractAnimation
void pause ()
Pauses the animation.
void resume ()
Resumes the animation after it was paused.
void setCurrentTime (int msecs)
void setPaused (bool)
If paused is true, the animation is paused.
void start (QAbstractAnimation::DeletionPolicy policy=KeepWhenStopped)
Starts the animation.
void stop ()
Stops the animation.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractAnimation
void currentLoopChanged (int currentLoop)
QAbstractAnimation emits this signal whenever the current loop changes.
void directionChanged (QAbstractAnimation::Direction)
QAbstractAnimation emits this signal whenever the direction has been changed.
void finished ()
QAbstractAnimation emits this signal after the animation has stopped and has reached the end.
void stateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State oldState)
QAbstractAnimation emits this signal whenever the state of the animation has changed from oldState to newState.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAnimationGroup class is an abstract base class for groups of animations.
Since
4.6
An animation group is a container for animations (subclasses of QAbstractAnimation). A group is usually responsible for managing the state of its animations, i.e., it decides when to start, stop, resume, and pause them. Currently, Qt provides two such groups: QParallelAnimationGroup and QSequentialAnimationGroup. Look up their class descriptions for details.
Since QAnimationGroup inherits from QAbstractAnimation, you can combine groups, and easily construct complex animation graphs. You can query QAbstractAnimation for the group it belongs to (using the QAbstractAnimation::group() function).
To start a top-level animation group, you simply use the QAbstractAnimation::start() function from QAbstractAnimation. By a top-level animation group, we think of a group that itself is not contained within another group. Starting sub groups directly is not supported, and may lead to unexpected behavior.
Warning
This function is not part of the public interface. OK, we'll put in a snippet on this here
QAnimationGroup provides methods for adding and retrieving animations. Besides that, you can remove animations by calling remove(), and clear the animation group by calling clear(). You may keep track of changes in the group's animations by listening to QEvent::ChildAdded and QEvent::ChildRemoved events.
Warning
This function is not part of the public interface. OK, let's find a snippet here as well.
QAnimationGroup takes ownership of the animations it manages, and ensures that they are deleted when the animation group is deleted.
See also
QAbstractAnimation, QVariantAnimation, {The Animation Framework}
Definition at line 56 of file qanimationgroup.h.
Constructors and Destructors
QAnimationGroup() [1/2]
QAnimationGroup::QAnimationGroup (QObject * parent = 0)
Constructs a QAnimationGroup.
parent is passed to QObject's constructor.
Definition at line 102 of file qanimationgroup.cpp.
     : QAbstractAnimation(*new QAnimationGroupPrivate, parent)
 {
 }
~QAnimationGroup()
QAnimationGroup::~QAnimationGroup ()
Destroys the animation group.
It will also destroy all its animations.
Definition at line 118 of file qanimationgroup.cpp.
 {
 }
QAnimationGroup() [2/2]
QAnimationGroup::QAnimationGroup (QAnimationGroupPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 110 of file qanimationgroup.cpp.
     : QAbstractAnimation(dd, parent)
 {
 }
Functions
addAnimation()
void QAnimationGroup::addAnimation (QAbstractAnimation * animation)
Adds animation to this group.
This will call insertAnimation with index equals to animationCount().
Note
The group takes ownership of the animation.
See also
removeAnimation()
Definition at line 173 of file qanimationgroup.cpp.
Referenced by QSequentialAnimationGroup::addPause(), and event().
 {
     Q_D(QAnimationGroup);
     insertAnimation(d->animations.count(), animation);
 }
animationAt()
QAbstractAnimation * QAnimationGroup::animationAt (int index) const
Returns a pointer to the animation at index in this group.
This function is useful when you need access to a particular animation. index is between 0 and animationCount() - 1.
See also
animationCount(), indexOfAnimation()
Definition at line 129 of file qanimationgroup.cpp.
Referenced by QStateMachinePrivate::initializeAnimation().
 {
     Q_D(const QAnimationGroup);
     if (index < 0 || index >= d->animations.size()) {
         qWarning("QAnimationGroup::animationAt: index is out of bounds");
         return 0;
     }
     return d->animations.at(index);
 }
animationCount()
int QAnimationGroup::animationCount () const
Returns the number of animations managed by this group.
See also
indexOfAnimation(), addAnimation(), animationAt()
Definition at line 147 of file qanimationgroup.cpp.
Referenced by QStateMachinePrivate::initializeAnimation().
 {
     Q_D(const QAnimationGroup);
     return d->animations.size();
 }
clear()
void QAnimationGroup::clear ()
Removes and deletes all animations in this animation group, and resets the current time to 0.
See also
addAnimation(), removeAnimation()
Definition at line 260 of file qanimationgroup.cpp.
 {
     Q_D(QAnimationGroup);
     qDeleteAll(d->animations);
 }
event()
bool QAnimationGroup::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractAnimation.
Reimplemented in QSequentialAnimationGroup, and QParallelAnimationGroup.
Definition at line 269 of file qanimationgroup.cpp.
Referenced by QParallelAnimationGroup::event(), and QSequentialAnimationGroup::event().
 {
     Q_D(QAnimationGroup);
     if (event->type() == QEvent::ChildAdded) {
         QChildEvent *childEvent = static_cast<QChildEvent *>(event);
         if (QAbstractAnimation *a = qobject_cast<QAbstractAnimation *>(childEvent->child())) {
             if (a->group() != this)
                 addAnimation(a);
         }
     } else if (event->type() == QEvent::ChildRemoved) {
         QChildEvent *childEvent = static_cast<QChildEvent *>(event);
         QAbstractAnimation *a = static_cast<QAbstractAnimation *>(childEvent->child());
         // You can only rely on the child being a QObject because in the QEvent::ChildRemoved
         // case it might be called from the destructor.
         int index = d->animations.indexOf(a);
         if (index != -1)
             takeAnimation(index);
     }
     return QAbstractAnimation::event(event);
 }
indexOfAnimation()
int QAnimationGroup::indexOfAnimation (QAbstractAnimation * animation) const
Returns the index of animation.
The returned index can be passed to the other functions that take an index as an argument.
See also
insertAnimation(), animationAt(), takeAnimation()
Definition at line 159 of file qanimationgroup.cpp.
 {
     Q_D(const QAnimationGroup);
     return d->animations.indexOf(animation);
 }
insertAnimation()
void QAnimationGroup::insertAnimation (int index, QAbstractAnimation * animation)
Inserts animation into this animation group at index.
If index is 0 the animation is inserted at the beginning. If index is animationCount(), the animation is inserted at the end.
Note
The group takes ownership of the animation.
See also
takeAnimation(), addAnimation(), indexOfAnimation(), removeAnimation()
Definition at line 188 of file qanimationgroup.cpp.
Referenced by addAnimation(), and QSequentialAnimationGroup::insertPause().
 {
     Q_D(QAnimationGroup);
     if (index < 0 || index > d->animations.size()) {
         qWarning("QAnimationGroup::insertAnimation: index is out of bounds");
         return;
     }
     if (QAnimationGroup *oldGroup = animation->group())
         oldGroup->removeAnimation(animation);
     d->animations.insert(index, animation);
     QAbstractAnimationPrivate::get(animation)->group = this;
     // this will make sure that ChildAdded event is sent to 'this'
     animation->setParent(this);
     d->animationInsertedAt(index);
 }
removeAnimation()
void QAnimationGroup::removeAnimation (QAbstractAnimation * animation)
Removes animation from this group.
The ownership of animation is transferred to the caller.
See also
takeAnimation(), insertAnimation(), addAnimation()
Definition at line 213 of file qanimationgroup.cpp.
 {
     Q_D(QAnimationGroup);
     if (!animation) {
         qWarning("QAnimationGroup::remove: cannot remove null animation");
         return;
     }
     int index = d->animations.indexOf(animation);
     if (index == -1) {
         qWarning("QAnimationGroup::remove: animation is not part of this group");
         return;
     }
     takeAnimation(index);
 }
takeAnimation()
QAbstractAnimation * QAnimationGroup::takeAnimation (int index)
Returns the animation at index and removes it from the animation group.
Note
The ownership of the animation is transferred to the caller.
See also
removeAnimation(), addAnimation(), insertAnimation(), indexOfAnimation()
Definition at line 237 of file qanimationgroup.cpp.
Referenced by event(), and removeAnimation().
 {
     Q_D(QAnimationGroup);
     if (index < 0 || index >= d->animations.size()) {
         qWarning("QAnimationGroup::takeAnimation: no animation at index %d", index);
         return 0;
     }
     QAbstractAnimation *animation = d->animations.at(index);
     QAbstractAnimationPrivate::get(animation)->group = 0;
     // ### removing from list before doing setParent to avoid inifinite recursion
     // in ChildRemoved event
     d->animations.removeAt(index);
     animation->setParent(0);
     d->animationRemoved(index, animation);
     return animation;
 }
The documentation for this class was generated from the following files:
/src/corelib/animation/qanimationgroup.h
/src/corelib/animation/qanimationgroup.cpp