Qt 4.8: QNetworkAccessManagerPrivate Class Reference
QNetworkAccessManagerPrivate Class Reference
#include <qnetworkaccessmanager_p.h>
Public Functions
void _q_networkSessionClosed ()
void _q_networkSessionNewConfigurationActivated ()
void _q_networkSessionPreferredConfigurationChanged (const QNetworkConfiguration &config, bool isSeamless)
void _q_networkSessionStateChanged (QNetworkSession::State state)
void _q_replyFinished ()
void _q_replySslErrors (const QList< QSslError > &errors)
void authenticationRequired (QNetworkAccessBackend *backend, QAuthenticator *authenticator)
void cacheCredentials (const QUrl &url, const QAuthenticator *auth)
void cacheProxyCredentials (const QNetworkProxy &proxy, const QAuthenticator *auth)
void createCookieJar () const
void createSession (const QNetworkConfiguration &config)
QNetworkAuthenticationCredential * fetchCachedCredentials (const QUrl &url, const QAuthenticator *auth=0)
QNetworkAuthenticationCredential * fetchCachedProxyCredentials (const QNetworkProxy &proxy, const QAuthenticator *auth=0)
QNetworkAccessBackend * findBackend (QNetworkAccessManager::Operation op, const QNetworkRequest &request)
QSharedPointer< QNetworkSession > getNetworkSession () const
QNetworkReply * postProcess (QNetworkReply *reply)
QNetworkRequest prepareMultipart (const QNetworkRequest &request, QHttpMultiPart *multiPart)
void proxyAuthenticationRequired (QNetworkAccessBackend *backend, const QNetworkProxy &proxy, QAuthenticator *authenticator)
QNetworkAccessManagerPrivate ()
QList< QNetworkProxy > queryProxy (const QNetworkProxyQuery &query)
~QNetworkAccessManagerPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static Q_AUTOTEST_EXPORT void clearCache (QNetworkAccessManager *manager)
static QNetworkAccessCache * getObjectCache (QNetworkAccessBackend *backend)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
int activeReplyCount
QSharedPointer< QNetworkAccessAuthenticationManager > authenticationManager
QNetworkCookieJar * cookieJar
bool cookieJarCreated
QThread * httpThread
bool initializeSession
QNetworkSession::State lastSessionState
QNetworkAccessManager::NetworkAccessibility networkAccessible
QAbstractNetworkCache * networkCache
QString networkConfiguration
QSharedPointer< QNetworkSession > networkSessionStrongRef
QWeakPointer< QNetworkSession > networkSessionWeakRef
QNetworkAccessCache objectCache
bool online
QNetworkProxy proxy
QNetworkProxyFactory * proxyFactory
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 71 of file qnetworkaccessmanager_p.h.
Constructors and Destructors
QNetworkAccessManagerPrivate()
QNetworkAccessManagerPrivate::QNetworkAccessManagerPrivate () inline
Definition at line 74 of file qnetworkaccessmanager_p.h.
         : networkCache(0), cookieJar(0),
           httpThread(0),
 #ifndef QT_NO_NETWORKPROXY
           proxyFactory(0),
 #endif
 #ifndef QT_NO_BEARERMANAGEMENT
           lastSessionState(QNetworkSession::Invalid),
           networkAccessible(QNetworkAccessManager::Accessible),
           activeReplyCount(0),
           online(false),
           initializeSession(true),
 #endif
           cookieJarCreated(false),
           authenticationManager(new QNetworkAccessAuthenticationManager)
     { }
~QNetworkAccessManagerPrivate()
QNetworkAccessManagerPrivate::~QNetworkAccessManagerPrivate ()
Definition at line 1236 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     if (httpThread) {
         // The thread will deleteLater() itself from its finished() signal
         httpThread->quit();
         httpThread->wait(5000);
         httpThread = 0;
     }
 }
Functions
_q_networkSessionClosed()
void QNetworkAccessManagerPrivate::_q_networkSessionClosed ()
Definition at line 1296 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     QSharedPointer<QNetworkSession> networkSession(getNetworkSession());
     if (networkSession) {
         networkConfiguration = networkSession->configuration().identifier();
         //disconnect from old session
         QObject::disconnect(networkSession.data(), SIGNAL(opened()), q, SIGNAL(networkSessionConnected()));
         QObject::disconnect(networkSession.data(), SIGNAL(closed()), q, SLOT(_q_networkSessionClosed()));
         QObject::disconnect(networkSession.data(), SIGNAL(stateChanged(QNetworkSession::State)),
             q, SLOT(_q_networkSessionStateChanged(QNetworkSession::State)));
         networkSessionStrongRef.clear();
         networkSessionWeakRef.clear();
     }
 }
_q_networkSessionNewConfigurationActivated()
void QNetworkAccessManagerPrivate::_q_networkSessionNewConfigurationActivated ()
Referenced by QNetworkAccessManagerPrivate().
_q_networkSessionPreferredConfigurationChanged()
void QNetworkAccessManagerPrivate::_q_networkSessionPreferredConfigurationChanged (const QNetworkConfiguration & config, bool isSeamless)
Referenced by QNetworkAccessManagerPrivate().
_q_networkSessionStateChanged()
void QNetworkAccessManagerPrivate::_q_networkSessionStateChanged (QNetworkSession::State state)
Definition at line 1313 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     //Do not emit the networkSessionConnected signal here, except for roaming -> connected
     //transition, otherwise it is emitted twice in a row when opening a connection.
     if (state == QNetworkSession::Connected && lastSessionState == QNetworkSession::Roaming)
         emit q->networkSessionConnected();
     lastSessionState = state;
     if (online) {
         if (state != QNetworkSession::Connected && state != QNetworkSession::Roaming) {
             online = false;
             emit q->networkAccessibleChanged(QNetworkAccessManager::NotAccessible);
         }
     } else {
         if (state == QNetworkSession::Connected || state == QNetworkSession::Roaming) {
             online = true;
             emit q->networkAccessibleChanged(networkAccessible);
         }
     }
 }
_q_replyFinished()
void QNetworkAccessManagerPrivate::_q_replyFinished ()
Definition at line 1075 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     QNetworkReply *reply = qobject_cast<QNetworkReply *>(q->sender());
     if (reply)
         emit q->finished(reply);
 #ifndef QT_NO_BEARERMANAGEMENT
     // If there are no active requests, release our reference to the network session.
     // It will not be destroyed immediately, but rather when the connection cache is flushed
     // after 2 minutes.
     activeReplyCount--;
     if (networkSessionStrongRef && activeReplyCount == 0)
         networkSessionStrongRef.clear();
 #endif
 }
_q_replySslErrors()
void QNetworkAccessManagerPrivate::_q_replySslErrors (const QList< QSslError > & errors)
Definition at line 1093 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
 #ifndef QT_NO_OPENSSL
     Q_Q(QNetworkAccessManager);
     QNetworkReply *reply = qobject_cast<QNetworkReply *>(q->sender());
     if (reply)
         emit q->sslErrors(reply, errors);
 #else
     Q_UNUSED(errors);
 #endif
 }
authenticationRequired()
void QNetworkAccessManagerPrivate::authenticationRequired (QNetworkAccessBackend * backend, QAuthenticator * authenticator)
Definition at line 1132 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessBackend::authenticationRequired(), and QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     // FIXME: Add support for domains (i.e., the leading path)
     QUrl url = backend->reply->url;
     // don't try the cache for the same URL twice in a row
     // being called twice for the same URL means the authentication failed
     // also called when last URL is empty, e.g. on first call
     if ((static_cast<QNetworkRequest::LoadControl>
          (backend->request().attribute(QNetworkRequest::AuthenticationReuseAttribute).toInt()) != QNetworkRequest::Manual)
             && (backend->reply->urlForLastAuthentication.isEmpty()
             || url != backend->reply->urlForLastAuthentication)) {
         // if credentials are included in the url, then use them
         if (!url.userName().isEmpty()
             && !url.password().isEmpty()) {
             authenticator->setUser(url.userName());
             authenticator->setPassword(url.password());
             backend->reply->urlForLastAuthentication = url;
             authenticationManager->cacheCredentials(url, authenticator);
             return;
         }
         QNetworkAuthenticationCredential cred = authenticationManager->fetchCachedCredentials(url, authenticator);
         if (!cred.isNull()) {
             authenticator->setUser(cred.user);
             authenticator->setPassword(cred.password);
             backend->reply->urlForLastAuthentication = url;
             return;
         }
     }
     // if we emit a signal here in synchronous mode, the user might spin
     // an event loop, which might recurse and lead to problems
     if (backend->isSynchronous())
         return;
     backend->reply->urlForLastAuthentication = url;
     emit q->authenticationRequired(backend->reply->q_func(), authenticator);
     authenticationManager->cacheCredentials(url, authenticator);
 }
cacheCredentials()
void QNetworkAccessManagerPrivate::cacheCredentials (const QUrl & url, const QAuthenticator * auth)
Referenced by QNetworkAccessManagerPrivate().
cacheProxyCredentials()
void QNetworkAccessManagerPrivate::cacheProxyCredentials (const QNetworkProxy & proxy, const QAuthenticator * auth)
Referenced by QNetworkAccessManagerPrivate().
clearCache()
void QNetworkAccessManagerPrivate::clearCache (QNetworkAccessManager * manager) static
Definition at line 1223 of file qnetworkaccessmanager.cpp.
Referenced by getObjectCache().
 {
     manager->d_func()->objectCache.clear();
     manager->d_func()->authenticationManager->clearCache();
     if (manager->d_func()->httpThread) {
         // The thread will deleteLater() itself from its finished() signal
         manager->d_func()->httpThread->quit();
         manager->d_func()->httpThread->wait(5000);
         manager->d_func()->httpThread = 0;
     }
 }
createCookieJar()
void QNetworkAccessManagerPrivate::createCookieJar () const
Definition at line 1122 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     if (!cookieJarCreated) {
         // keep the ugly hack in here
         QNetworkAccessManagerPrivate *that = const_cast<QNetworkAccessManagerPrivate *>(this);
         that->cookieJar = new QNetworkCookieJar(that->q_func());
         that->cookieJarCreated = true;
     }
 }
createSession()
void QNetworkAccessManagerPrivate::createSession (const QNetworkConfiguration & config)
Definition at line 1247 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     initializeSession = false;
     //resurrect weak ref if possible
     networkSessionStrongRef = networkSessionWeakRef.toStrongRef();
     QSharedPointer<QNetworkSession> newSession;
     if (config.isValid())
         newSession = QSharedNetworkSessionManager::getSession(config);
     if (networkSessionStrongRef) {
         //do nothing if new and old session are the same
         if (networkSessionStrongRef == newSession)
             return;
         //disconnect from old session
         QObject::disconnect(networkSessionStrongRef.data(), SIGNAL(opened()), q, SIGNAL(networkSessionConnected()));
         QObject::disconnect(networkSessionStrongRef.data(), SIGNAL(closed()), q, SLOT(_q_networkSessionClosed()));
         QObject::disconnect(networkSessionStrongRef.data(), SIGNAL(stateChanged(QNetworkSession::State)),
             q, SLOT(_q_networkSessionStateChanged(QNetworkSession::State)));
     }
     //switch to new session (null if config was invalid)
     networkSessionStrongRef = newSession;
     networkSessionWeakRef = networkSessionStrongRef.toWeakRef();
     if (!networkSessionStrongRef) {
         online = false;
         if (networkAccessible == QNetworkAccessManager::NotAccessible)
             emit q->networkAccessibleChanged(QNetworkAccessManager::NotAccessible);
         else
             emit q->networkAccessibleChanged(QNetworkAccessManager::UnknownAccessibility);
         return;
     }
     //connect to new session
     QObject::connect(networkSessionStrongRef.data(), SIGNAL(opened()), q, SIGNAL(networkSessionConnected()), Qt::QueuedConnection);
     //QueuedConnection is used to avoid deleting the networkSession inside its closed signal
     QObject::connect(networkSessionStrongRef.data(), SIGNAL(closed()), q, SLOT(_q_networkSessionClosed()), Qt::QueuedConnection);
     QObject::connect(networkSessionStrongRef.data(), SIGNAL(stateChanged(QNetworkSession::State)),
                      q, SLOT(_q_networkSessionStateChanged(QNetworkSession::State)), Qt::QueuedConnection);
     _q_networkSessionStateChanged(networkSessionStrongRef->state());
 }
fetchCachedCredentials()
QNetworkAuthenticationCredential* QNetworkAccessManagerPrivate::fetchCachedCredentials (const QUrl & url, const QAuthenticator * auth = 0)
Referenced by QNetworkAccessManagerPrivate().
fetchCachedProxyCredentials()
QNetworkAuthenticationCredential* QNetworkAccessManagerPrivate::fetchCachedProxyCredentials (const QNetworkProxy & proxy, const QAuthenticator * auth = 0)
Referenced by QNetworkAccessManagerPrivate().
findBackend()
QNetworkAccessBackend * QNetworkAccessManagerPrivate::findBackend (QNetworkAccessManager::Operation op, const QNetworkRequest & request)
Definition at line 94 of file qnetworkaccessbackend.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     if (QNetworkAccessBackendFactoryData::valid) {
         QMutexLocker locker(&factoryData()->mutex);
         QNetworkAccessBackendFactoryData::ConstIterator it = factoryData()->constBegin(),
                                                            end = factoryData()->constEnd();
         while (it != end) {
             QNetworkAccessBackend *backend = (*it)->create(op, request);
             if (backend) {
                 backend->manager = this;
                 return backend; // found a factory that handled our request
             }
             ++it;
         }
     }
     return 0;
 }
getNetworkSession()
QSharedPointer< QNetworkSession > QNetworkAccessManagerPrivate::getNetworkSession () const
Definition at line 911 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate(), and QNetworkAccessBackend::start().
 {
     if (networkSessionStrongRef)
         return networkSessionStrongRef;
     return networkSessionWeakRef.toStrongRef();
 }
getObjectCache()
static QNetworkAccessCache* QNetworkAccessManagerPrivate::getObjectCache (QNetworkAccessBackend * backend) inline static
Definition at line 158 of file qnetworkaccessmanager_p.h.
Referenced by QNetworkAccessFtpBackend::disconnectFromFtp(), QNetworkAccessFtpBackend::ftpDone(), and QNetworkAccessFtpBackend::open().
     { return &backend->manager->objectCache; }
postProcess()
QNetworkReply * QNetworkAccessManagerPrivate::postProcess (QNetworkReply * reply)
Definition at line 1105 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     QNetworkReplyPrivate::setManager(reply, q);
     q->connect(reply, SIGNAL(finished()), SLOT(_q_replyFinished()));
 #ifndef QT_NO_OPENSSL
     /* In case we're compiled without SSL support, we don't have this signal and we need to
      * avoid getting a connection error. */
     q->connect(reply, SIGNAL(sslErrors(QList<QSslError>)), SLOT(_q_replySslErrors(QList<QSslError>)));
 #endif
 #ifndef QT_NO_BEARERMANAGEMENT
     activeReplyCount++;
 #endif
     return reply;
 }
prepareMultipart()
QNetworkRequest QNetworkAccessManagerPrivate::prepareMultipart (const QNetworkRequest & request, QHttpMultiPart * multiPart)
Definition at line 1337 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate().
 {
     // copy the request, we probably need to add some headers
     QNetworkRequest newRequest(request);
     // add Content-Type header if not there already
     if (!request.header(QNetworkRequest::ContentTypeHeader).isValid()) {
         QByteArray contentType;
         contentType.reserve(34 + multiPart->d_func()->boundary.count());
         contentType += "multipart/";
         switch (multiPart->d_func()->contentType) {
         case QHttpMultiPart::RelatedType:
             contentType += "related";
             break;
         case QHttpMultiPart::FormDataType:
             contentType += "form-data";
             break;
         case QHttpMultiPart::AlternativeType:
             contentType += "alternative";
             break;
         default:
             contentType += "mixed";
             break;
         }
         // putting the boundary into quotes, recommended in RFC 2046 section 5.1.1
         contentType += "; boundary=\"" + multiPart->d_func()->boundary + "\"";
         newRequest.setHeader(QNetworkRequest::ContentTypeHeader, QVariant(contentType));
     }
     // add MIME-Version header if not there already (we must include the header
     // if the message conforms to RFC 2045, see section 4 of that RFC)
     QByteArray mimeHeader("MIME-Version");
     if (!request.hasRawHeader(mimeHeader))
         newRequest.setRawHeader(mimeHeader, QByteArray("1.0"));
     QIODevice *device = multiPart->d_func()->device;
     if (!device->isReadable()) {
         if (!device->isOpen()) {
             if (!device->open(QIODevice::ReadOnly))
                 qWarning("could not open device for reading");
         } else {
             qWarning("device is not readable");
         }
     }
     return newRequest;
 }
proxyAuthenticationRequired()
void QNetworkAccessManagerPrivate::proxyAuthenticationRequired (QNetworkAccessBackend * backend, const QNetworkProxy & proxy, QAuthenticator * authenticator)
Definition at line 1177 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessBackend::proxyAuthenticationRequired(), and QNetworkAccessManagerPrivate().
 {
     Q_Q(QNetworkAccessManager);
     QAuthenticatorPrivate *priv = QAuthenticatorPrivate::getPrivate(*authenticator);
     if (proxy != backend->reply->lastProxyAuthentication && (!priv || !priv->hasFailed)) {
         QNetworkAuthenticationCredential cred = authenticationManager->fetchCachedProxyCredentials(proxy);
         if (!cred.isNull()) {
             authenticator->setUser(cred.user);
             authenticator->setPassword(cred.password);
             return;
         }
     }
     // if we emit a signal here in synchronous mode, the user might spin
     // an event loop, which might recurse and lead to problems
     if (backend->isSynchronous())
         return;
     backend->reply->lastProxyAuthentication = proxy;
     emit q->proxyAuthenticationRequired(proxy, authenticator);
     authenticationManager->cacheProxyCredentials(proxy, authenticator);
 }
queryProxy()
QList< QNetworkProxy > QNetworkAccessManagerPrivate::queryProxy (const QNetworkProxyQuery & query)
Definition at line 1202 of file qnetworkaccessmanager.cpp.
Referenced by QNetworkAccessManagerPrivate(), and QNetworkAccessBackend::start().
 {
     QList<QNetworkProxy> proxies;
     if (proxyFactory) {
         proxies = proxyFactory->queryProxy(query);
         if (proxies.isEmpty()) {
             qWarning("QNetworkAccessManager: factory %p has returned an empty result set",
                      proxyFactory);
             proxies << QNetworkProxy::NoProxy;
         }
     } else if (proxy.type() == QNetworkProxy::DefaultProxy) {
         // no proxy set, query the application
         return QNetworkProxyFactory::proxyForQuery(query);
     } else {
         proxies << proxy;
     }
     return proxies;
 }
Properties
activeReplyCount
int QNetworkAccessManagerPrivate::activeReplyCount
Definition at line 145 of file qnetworkaccessmanager_p.h.
authenticationManager
QSharedPointer<QNetworkAccessAuthenticationManager> QNetworkAccessManagerPrivate::authenticationManager
Definition at line 153 of file qnetworkaccessmanager_p.h.
Referenced by QNetworkAccessHttpBackend::postRequest().
cookieJar
QNetworkCookieJar* QNetworkAccessManagerPrivate::cookieJar
Definition at line 129 of file qnetworkaccessmanager_p.h.
Referenced by createCookieJar().
cookieJarCreated
bool QNetworkAccessManagerPrivate::cookieJarCreated
Definition at line 150 of file qnetworkaccessmanager_p.h.
Referenced by createCookieJar().
httpThread
QThread* QNetworkAccessManagerPrivate::httpThread
Definition at line 131 of file qnetworkaccessmanager_p.h.
Referenced by QNetworkAccessHttpBackend::postRequest().
initializeSession
bool QNetworkAccessManagerPrivate::initializeSession
Definition at line 147 of file qnetworkaccessmanager_p.h.
lastSessionState
QNetworkSession::State QNetworkAccessManagerPrivate::lastSessionState
Definition at line 142 of file qnetworkaccessmanager_p.h.
networkAccessible
QNetworkAccessManager::NetworkAccessibility QNetworkAccessManagerPrivate::networkAccessible
Definition at line 144 of file qnetworkaccessmanager_p.h.
networkCache
QAbstractNetworkCache* QNetworkAccessManagerPrivate::networkCache
Definition at line 127 of file qnetworkaccessmanager_p.h.
Referenced by QNetworkAccessBackend::networkCache().
networkConfiguration
QString QNetworkAccessManagerPrivate::networkConfiguration
Definition at line 143 of file qnetworkaccessmanager_p.h.
networkSessionStrongRef
QSharedPointer<QNetworkSession> QNetworkAccessManagerPrivate::networkSessionStrongRef
Definition at line 140 of file qnetworkaccessmanager_p.h.
networkSessionWeakRef
QWeakPointer<QNetworkSession> QNetworkAccessManagerPrivate::networkSessionWeakRef
Definition at line 141 of file qnetworkaccessmanager_p.h.
objectCache
QNetworkAccessCache QNetworkAccessManagerPrivate::objectCache
Definition at line 157 of file qnetworkaccessmanager_p.h.
Referenced by getObjectCache().
online
bool QNetworkAccessManagerPrivate::online
Definition at line 146 of file qnetworkaccessmanager_p.h.
proxy
QNetworkProxy QNetworkAccessManagerPrivate::proxy
Definition at line 135 of file qnetworkaccessmanager_p.h.
Referenced by QNetworkAccessManagerPrivate().
proxyFactory
QNetworkProxyFactory* QNetworkAccessManagerPrivate::proxyFactory
Definition at line 136 of file qnetworkaccessmanager_p.h.
The documentation for this class was generated from the following files:
/src/network/access/qnetworkaccessmanager_p.h
/src/network/access/qnetworkaccessbackend.cpp
/src/network/access/qnetworkaccessmanager.cpp