Qt 4.8: QNativeImage Class Reference
QNativeImage Class Reference
#include <qnativeimage_p.h>
Public Functions
int height () const
QNativeImage (int width, int height, QImage::Format format, bool isTextBuffer=false, QWidget *widget=0)
int width () const
~QNativeImage ()
Static Public Functions
static QImage::Format systemFormat ()
Public Variables
HBITMAP bitmap
HDC hdc
QImage image
HBITMAP null_bitmap
Detailed Description
Definition at line 73 of file qnativeimage_p.h.
Constructors and Destructors
QNativeImage()
QNativeImage::QNativeImage (int width, int height, QImage::Format format, bool isTextBuffer = false, QWidget * widget = 0)
Definition at line 73 of file qnativeimage.cpp.
Referenced by systemFormat().
 {
 #ifndef Q_WS_WINCE
     Q_UNUSED(isTextBuffer);
 #endif
     BITMAPINFO_MASK bmi;
     memset(&bmi, 0, sizeof(bmi));
     bmi.bmiHeader.biSize        = sizeof(BITMAPINFOHEADER);
     bmi.bmiHeader.biWidth       = width;
     bmi.bmiHeader.biHeight      = -height;
     bmi.bmiHeader.biPlanes      = 1;
     bmi.bmiHeader.biSizeImage   = 0;
     if (format == QImage::Format_RGB16) {
         bmi.bmiHeader.biBitCount = 16;
 #ifdef Q_WS_WINCE
         if (isTextBuffer) {
             bmi.bmiHeader.biCompression = BI_RGB;
             bmi.redMask = 0;
             bmi.greenMask = 0;
             bmi.blueMask = 0;
         } else
 #endif
         {
             bmi.bmiHeader.biCompression = BI_BITFIELDS;
             bmi.redMask = 0xF800;
             bmi.greenMask = 0x07E0;
             bmi.blueMask = 0x001F;
         }
     } else {
         bmi.bmiHeader.biBitCount    = 32;
         bmi.bmiHeader.biCompression = BI_RGB;
         bmi.redMask = 0;
         bmi.greenMask = 0;
         bmi.blueMask = 0;
     }
     HDC display_dc = GetDC(0);
     hdc = CreateCompatibleDC(display_dc);
     ReleaseDC(0, display_dc);
     Q_ASSERT(hdc);
     uchar *bits = 0;
     bitmap = CreateDIBSection(hdc, reinterpret_cast<BITMAPINFO *>(&bmi), DIB_RGB_COLORS, (void**) &bits, 0, 0);
     Q_ASSERT(bitmap);
     Q_ASSERT(bits);
     null_bitmap = (HBITMAP)SelectObject(hdc, bitmap);
     image = QImage(bits, width, height, format);
     Q_ASSERT(image.paintEngine()->type() == QPaintEngine::Raster);
     static_cast<QRasterPaintEngine *>(image.paintEngine())->setDC(hdc);
 #ifndef Q_WS_WINCE
     GdiFlush();
 #endif
 }
~QNativeImage()
QNativeImage::~QNativeImage ()
Definition at line 131 of file qnativeimage.cpp.
Referenced by systemFormat().
 {
     if (bitmap || hdc) {
         Q_ASSERT(hdc);
         Q_ASSERT(bitmap);
         if (null_bitmap)
             SelectObject(hdc, null_bitmap);
         DeleteDC(hdc);
         DeleteObject(bitmap);
     }
 }
Functions
height()
int QNativeImage::height () const inline
Definition at line 105 of file qnativeimage_p.h.
Referenced by QFontEngineWin::alphaMapForGlyph(), QFontEngineWin::alphaRGBMapForGlyph(), QNativeImage(), and systemFormat().
 { return image.height(); }
systemFormat()
QImage::Format QNativeImage::systemFormat () static
Definition at line 143 of file qnativeimage.cpp.
Referenced by QFontEngineWin::alphaMapForGlyph(), QRasterPixmapData::createPixmapForImage(), QFontEngineWin::drawGDIGlyph(), qcolorForThemeTextColor(), QRasterPixmapData::resize(), and QRasterWindowSurface::setGeometry().
 {
     if (QColormap::instance().depth() == 16)
         return QImage::Format_RGB16;
     return QImage::Format_RGB32;
 }
width()
int QNativeImage::width () const inline
Definition at line 104 of file qnativeimage_p.h.
Referenced by QFontEngineWin::alphaMapForGlyph(), QFontEngineWin::alphaRGBMapForGlyph(), QNativeImage(), and systemFormat().
 { return image.width(); }
Properties
bitmap
HBITMAP QNativeImage::bitmap
Definition at line 88 of file qnativeimage_p.h.
Referenced by QNativeImage(), and ~QNativeImage().
hdc
HDC QNativeImage::hdc
Definition at line 87 of file qnativeimage_p.h.
Referenced by QFontEngineWin::drawGDIGlyph(), QNativeImage(), and ~QNativeImage().
image
QImage QNativeImage::image
Definition at line 82 of file qnativeimage_p.h.
Referenced by QFontEngineWin::alphaMapForGlyph(), QFontEngineWin::alphaRGBMapForGlyph(), QRasterWindowSurface::beginPaint(), QFontEngineWin::drawGDIGlyph(), QRasterWindowSurface::flush(), height(), QRasterWindowSurface::paintDevice(), QRasterWindowSurface::prepareBuffer(), qcolorForThemeTextColor(), QNativeImage(), systemFormat(), and width().
null_bitmap
HBITMAP QNativeImage::null_bitmap
Definition at line 89 of file qnativeimage_p.h.
Referenced by QNativeImage(), and ~QNativeImage().
The documentation for this class was generated from the following files:
/src/gui/image/qnativeimage_p.h
/src/gui/image/qnativeimage.cpp