Qt 4.8: QScriptValueIterator Class Reference
QScriptValueIterator Class Reference
The QScriptValueIterator class provides a Java-style iterator for QScriptValue.
#include <qscriptvalueiterator.h>
Public Functions
QScriptValue::PropertyFlags flags () const
Returns the flags of the last property that was jumped over using next() or previous().
bool hasNext () const
Returns true if there is at least one item ahead of the iterator (i.e.
bool hasPrevious () const
Returns true if there is at least one item behind the iterator (i.e.
QString name () const
Returns the name of the last property that was jumped over using next() or previous().
void next ()
Advances the iterator by one position.
QScriptValueIterator & operator= (QScriptValue &value)
Makes the iterator operate on object.
void previous ()
Moves the iterator back by one position.
QScriptValueIterator (const QScriptValue &value)
Constructs an iterator for traversing object.
void remove ()
Removes the last property that was jumped over using next() or previous().
QScriptString scriptName () const
Returns the name of the last property that was jumped over using next() or previous().
void setValue (const QScriptValue &value)
Sets the value of the last property that was jumped over using next() or previous().
void toBack ()
Moves the iterator to the back of the QScriptValue (after the last property).
void toFront ()
Moves the iterator to the front of the QScriptValue (before the first property).
QScriptValue value () const
Returns the value of the last property that was jumped over using next() or previous().
~QScriptValueIterator ()
Destroys the iterator.
Properties
QScopedPointer< QScriptValueIteratorPrivate > d_ptr
Detailed Description
The QScriptValueIterator class provides a Java-style iterator for QScriptValue.
Since
4.3
The QScriptValueIterator constructor takes a QScriptValue as argument. After construction, the iterator is located at the very beginning of the sequence of properties. Here's how to iterate over all the properties of a QScriptValue:
QScriptValue object;
...
QScriptValueIterator it(object);
while (it.hasNext()) {
    it.next();
    qDebug() << it.name() << ": " << it.value().toString();
}
The next() advances the iterator. The name(), value() and flags() functions return the name, value and flags of the last item that was jumped over.
If you want to remove properties as you iterate over the QScriptValue, use remove(). If you want to modify the value of a property, use setValue().
Note that QScriptValueIterator only iterates over the QScriptValue's own properties; i.e. it does not follow the prototype chain. You can use a loop like this to follow the prototype chain:
QScriptValue obj = ...; // the object to iterate over
while (obj.isObject()) {
    QScriptValueIterator it(obj);
    while (it.hasNext()) {
        it.next();
        qDebug() << it.name();
    }
    obj = obj.prototype();
}
Note that QScriptValueIterator will not automatically skip over properties that have the QScriptValue::SkipInEnumeration flag set; that flag only affects iteration in script code. If you want, you can skip over such properties with code like the following:
while (it.hasNext()) {
    it.next();
    if (it.flags() & QScriptValue::SkipInEnumeration)
        continue;
    qDebug() << "found enumerated property:" << it.name();
}
See also
QScriptValue::property()
Definition at line 41 of file qscriptvalueiterator.h.
Constructors and Destructors
QScriptValueIterator()
QScriptValueIterator::QScriptValueIterator (const QScriptValue & object)
Constructs an iterator for traversing object.
The iterator is set to be at the front of the sequence of properties (before the first property).
Definition at line 142 of file qscriptvalueiterator.cpp.
     : d_ptr(0)
 {
     if (object.isObject()) {
         d_ptr.reset(new QScriptValueIteratorPrivate());
         d_ptr->objectValue = object;
     }
 }
~QScriptValueIterator()
QScriptValueIterator::~QScriptValueIterator ()
Destroys the iterator.
Definition at line 154 of file qscriptvalueiterator.cpp.
 {
 }
Functions
flags()
QScriptValue::PropertyFlags QScriptValueIterator::flags () const
Returns the flags of the last property that was jumped over using next() or previous().
See also
value()
Definition at line 328 of file qscriptvalueiterator.cpp.
Referenced by QScriptObjectSnapshot::capture(), QScriptDebuggerCommandExecutor::execute(), expandObject(), and QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass().
 {
     Q_D(const QScriptValueIterator);
     if (!d || !d->initialized || !d->engine())
         return 0;
     QScript::APIShim shim(d->engine());
     return d->object()->propertyFlags(*d->current);
 }
hasNext()
bool QScriptValueIterator::hasNext () const
Returns true if there is at least one item ahead of the iterator (i.e.
the iterator is not at the back of the property sequence); otherwise returns false.
See also
next(), hasPrevious()
Definition at line 165 of file qscriptvalueiterator.cpp.
Referenced by FlatListModel::addValue(), QScriptObjectSnapshot::capture(), QDeclarativeComponentPrivate::createObject(), QScriptDebuggerCommandExecutor::execute(), expandObject(), QDeclarativeGlobalScriptClass::explicitSetProperty(), QJSDebuggerAgentPrivate::getLocals(), QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), NestedListModel::set(), and ModelNode::setObjectValue().
 {
     Q_D(const QScriptValueIterator);
     if (!d || !d->engine())
         return false;
     const_cast<QScriptValueIteratorPrivate*>(d)->ensureInitialized();
     return d->it != d->propertyNames.end();
 }
hasPrevious()
bool QScriptValueIterator::hasPrevious () const
Returns true if there is at least one item behind the iterator (i.e.
the iterator is not at the front of the property sequence); otherwise returns false.
See also
previous(), hasNext()
Definition at line 201 of file qscriptvalueiterator.cpp.
 {
     Q_D(const QScriptValueIterator);
     if (!d || !d->engine())
         return false;
     const_cast<QScriptValueIteratorPrivate*>(d)->ensureInitialized();
     return d->it != d->propertyNames.begin();
 }
name()
QString QScriptValueIterator::name () const
Returns the name of the last property that was jumped over using next() or previous().
See also
value(), flags()
Definition at line 265 of file qscriptvalueiterator.cpp.
Referenced by FlatListModel::addValue(), QScriptObjectSnapshot::capture(), QDeclarativeComponentPrivate::createObject(), QScriptDebuggerCommandExecutor::execute(), expandObject(), QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), NestedListModel::set(), and ModelNode::setObjectValue().
 {
     Q_D(const QScriptValueIterator);
     if (!d || !d->initialized || !d->engine())
         return QString();
     return d->current->ustring();
 }
next()
void QScriptValueIterator::next ()
Advances the iterator by one position.
Calling this function on an iterator located at the back of the container leads to undefined results.
See also
hasNext(), previous(), name()
Definition at line 183 of file qscriptvalueiterator.cpp.
Referenced by FlatListModel::addValue(), QScriptObjectSnapshot::capture(), QDeclarativeComponentPrivate::createObject(), QScriptDebuggerCommandExecutor::execute(), expandObject(), QDeclarativeGlobalScriptClass::explicitSetProperty(), QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), NestedListModel::set(), and ModelNode::setObjectValue().
 {
     Q_D(QScriptValueIterator);
     if (!d)
         return;
     d->ensureInitialized();
     d->current = d->it;
     ++(d->it);
 }
operator=()
QScriptValueIterator & QScriptValueIterator::operator= (QScriptValue & object)
Makes the iterator operate on object.
The iterator is set to be at the front of the sequence of properties (before the first property).
Definition at line 358 of file qscriptvalueiterator.cpp.
 {
     d_ptr.reset();
     if (object.isObject()) {
         d_ptr.reset(new QScriptValueIteratorPrivate());
         d_ptr->objectValue = object;
     }
     return *this;
 }
previous()
void QScriptValueIterator::previous ()
Moves the iterator back by one position.
Calling this function on an iterator located at the front of the container leads to undefined results.
See also
hasPrevious(), next(), name()
Definition at line 219 of file qscriptvalueiterator.cpp.
 {
     Q_D(QScriptValueIterator);
     if (!d)
         return;
     d->ensureInitialized();
     --(d->it);
     d->current = d->it;
 }
remove()
void QScriptValueIterator::remove ()
Removes the last property that was jumped over using next() or previous().
See also
setValue()
Definition at line 343 of file qscriptvalueiterator.cpp.
 {
     Q_D(QScriptValueIterator);
     if (!d || !d->initialized || !d->engine())
         return;
     QScript::APIShim shim(d->engine());
     d->object()->setProperty(*d->current, JSC::JSValue());
     d->propertyNames.erase(d->current);
 }
scriptName()
QScriptString QScriptValueIterator::scriptName () const
Returns the name of the last property that was jumped over using next() or previous().
Since
4.4
Definition at line 282 of file qscriptvalueiterator.cpp.
Referenced by QDeclarativeGlobalScriptClass::explicitSetProperty(), and QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass().
 {
     Q_D(const QScriptValueIterator);
     if (!d || !d->initialized || !d->engine())
         return QScriptString();
     return d->engine()->toStringHandle(*d->current);
 }
setValue()
void QScriptValueIterator::setValue (const QScriptValue & value)
Sets the value of the last property that was jumped over using next() or previous().
See also
value(), name()
Definition at line 312 of file qscriptvalueiterator.cpp.
 {
     Q_D(QScriptValueIterator);
     if (!d || !d->initialized || !d->engine())
         return;
     QScript::APIShim shim(d->engine());
     JSC::JSValue jsValue = d->engine()->scriptValueToJSCValue(value);
     d->object()->setProperty(*d->current, jsValue);
 }
toBack()
void QScriptValueIterator::toBack ()
Moves the iterator to the back of the QScriptValue (after the last property).
See also
toFront(), previous()
Definition at line 250 of file qscriptvalueiterator.cpp.
 {
     Q_D(QScriptValueIterator);
     if (!d)
         return;
     d->ensureInitialized();
     d->it = d->propertyNames.end();
 }
toFront()
void QScriptValueIterator::toFront ()
Moves the iterator to the front of the QScriptValue (before the first property).
See also
toBack(), next()
Definition at line 235 of file qscriptvalueiterator.cpp.
 {
     Q_D(QScriptValueIterator);
     if (!d)
         return;
     d->ensureInitialized();
     d->it = d->propertyNames.begin();
 }
value()
QScriptValue QScriptValueIterator::value () const
Returns the value of the last property that was jumped over using next() or previous().
See also
setValue(), name()
Definition at line 296 of file qscriptvalueiterator.cpp.
Referenced by FlatListModel::addValue(), QScriptObjectSnapshot::capture(), QDeclarativeComponentPrivate::createObject(), QScriptDebuggerCommandExecutor::execute(), expandObject(), QDeclarativeGlobalScriptClass::explicitSetProperty(), QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), and ModelNode::setObjectValue().
 {
     Q_D(const QScriptValueIterator);
     if (!d || !d->initialized || !d->engine())
         return QScriptValue();
     QScript::APIShim shim(d->engine());
     JSC::JSValue jsValue = d->object()->property(*d->current);
     return d->engine()->scriptValueFromJSCValue(jsValue);
 }
Properties
d_ptr
QScopedPointer<QScriptValueIteratorPrivate> QScriptValueIterator::d_ptr private
Definition at line 69 of file qscriptvalueiterator.h.
Referenced by operator=(), and QScriptValueIterator().
The documentation for this class was generated from the following files:
/src/script/api/qscriptvalueiterator.h
/src/script/api/qscriptvalueiterator.cpp