Qt 4.8: QXlibEglIntegration Class Reference
QXlibEglIntegration Class Reference
#include <qxlibeglintegration.h>
Static Public Functions
static VisualID getCompatibleVisualId (Display *display, EGLDisplay eglDisplay, EGLConfig config)
Detailed Description
Definition at line 47 of file qxlibeglintegration.h.
Functions
getCompatibleVisualId()
VisualID QXlibEglIntegration::getCompatibleVisualId (Display * display, EGLDisplay eglDisplay, EGLConfig config) static
Definition at line 55 of file qxlibeglintegration.cpp.
Referenced by QWaylandXCompositeEGLContext::geometryChanged(), QXcbWindow::QXcbWindow(), and QXlibWindow::QXlibWindow().
 {
     VisualID    visualId = 0;
     EGLint      eglValue = 0;
     EGLint configRedSize = 0;
     eglGetConfigAttrib(eglDisplay, config, EGL_RED_SIZE, &configRedSize);
     EGLint configGreenSize = 0;
     eglGetConfigAttrib(eglDisplay, config, EGL_GREEN_SIZE, &configGreenSize);
     EGLint configBlueSize = 0;
     eglGetConfigAttrib(eglDisplay, config, EGL_BLUE_SIZE, &configBlueSize);
     EGLint configAlphaSize = 0;
     eglGetConfigAttrib(eglDisplay, config, EGL_ALPHA_SIZE, &configAlphaSize);
     eglGetConfigAttrib(eglDisplay, config, EGL_CONFIG_ID, &eglValue);
     int configId = eglValue;
     // See if EGL provided a valid VisualID:
     eglGetConfigAttrib(eglDisplay, config, EGL_NATIVE_VISUAL_ID, &eglValue);
     visualId = (VisualID)eglValue;
     if (visualId) {
         // EGL has suggested a visual id, so get the rest of the visual info for that id:
         XVisualInfo visualInfoTemplate;
         memset(&visualInfoTemplate, 0, sizeof(XVisualInfo));
         visualInfoTemplate.visualid = visualId;
         XVisualInfo *chosenVisualInfo;
         int matchingCount = 0;
         chosenVisualInfo = XGetVisualInfo(display, VisualIDMask, &visualInfoTemplate, &matchingCount);
         if (chosenVisualInfo) {
             // Skip size checks if implementation supports non-matching visual
             // and config (http://bugreports.qt-project.org/browse/QTBUG-9444).
             if (q_hasEglExtension(eglDisplay,"EGL_NV_post_convert_rounding")) {
                 XFree(chosenVisualInfo);
                 return visualId;
             }
             int visualRedSize = countBits(chosenVisualInfo->red_mask);
             int visualGreenSize = countBits(chosenVisualInfo->green_mask);
             int visualBlueSize = countBits(chosenVisualInfo->blue_mask);
             int visualAlphaSize = -1; // Need XRender to tell us the alpha channel size
             bool visualMatchesConfig = false;
             if ( visualRedSize == configRedSize &&
                  visualGreenSize == configGreenSize &&
                  visualBlueSize == configBlueSize )
             {
                 // We need XRender to check the alpha channel size of the visual. If we don't have
                 // the alpha size, we don't check it against the EGL config's alpha size.
                 if (visualAlphaSize >= 0)
                     visualMatchesConfig = visualAlphaSize == configAlphaSize;
                 else
                     visualMatchesConfig = true;
             }
             if (!visualMatchesConfig) {
                 if (visualAlphaSize >= 0) {
                     qWarning("Warning: EGL suggested using X Visual ID %d (ARGB%d%d%d%d) for EGL config %d (ARGB%d%d%d%d), but this is incompatable",
                              (int)visualId, visualAlphaSize, visualRedSize, visualGreenSize, visualBlueSize,
                              configId, configAlphaSize, configRedSize, configGreenSize, configBlueSize);
                 } else {
                     qWarning("Warning: EGL suggested using X Visual ID %d (RGB%d%d%d) for EGL config %d (RGB%d%d%d), but this is incompatable",
                              (int)visualId, visualRedSize, visualGreenSize, visualBlueSize,
                              configId, configRedSize, configGreenSize, configBlueSize);
                 }
                 visualId = 0;
             }
         } else {
             qWarning("Warning: EGL suggested using X Visual ID %d for EGL config %d, but that isn't a valid ID",
                      (int)visualId, configId);
             visualId = 0;
         }
         XFree(chosenVisualInfo);
     }
 #ifdef QT_DEBUG_X11_VISUAL_SELECTION
     else
         qDebug("EGL did not suggest a VisualID (EGL_NATIVE_VISUAL_ID was zero) for EGLConfig %d", configId);
 #endif
     if (visualId) {
 #ifdef QT_DEBUG_X11_VISUAL_SELECTION
         if (configAlphaSize > 0)
             qDebug("Using ARGB Visual ID %d provided by EGL for config %d", (int)visualId, configId);
         else
             qDebug("Using Opaque Visual ID %d provided by EGL for config %d", (int)visualId, configId);
 #endif
         return visualId;
     }
     // Finally, try to
     // use XGetVisualInfo and only use the bit depths to match on:
     if (!visualId) {
         XVisualInfo visualInfoTemplate;
         memset(&visualInfoTemplate, 0, sizeof(XVisualInfo));
         XVisualInfo *matchingVisuals;
         int matchingCount = 0;
         visualInfoTemplate.depth = configRedSize + configGreenSize + configBlueSize + configAlphaSize;
         matchingVisuals = XGetVisualInfo(display,
                                          VisualDepthMask,
                                          &visualInfoTemplate,
                                          &matchingCount);
         if (!matchingVisuals) {
             // Try again without taking the alpha channel into account:
             visualInfoTemplate.depth = configRedSize + configGreenSize + configBlueSize;
             matchingVisuals = XGetVisualInfo(display,
                                              VisualDepthMask,
                                              &visualInfoTemplate,
                                              &matchingCount);
         }
         if (matchingVisuals) {
             visualId = matchingVisuals[0].visualid;
             XFree(matchingVisuals);
         }
     }
     if (visualId) {
 #ifdef QT_DEBUG_X11_VISUAL_SELECTION
         qDebug("Using Visual ID %d provided by XGetVisualInfo for EGL config %d", (int)visualId, configId);
 #endif
         return visualId;
     }
     qWarning("Unable to find an X11 visual which matches EGL config %d", configId);
     return (VisualID)0;
 }
The documentation for this class was generated from the following files:
/src/plugins/platforms/eglconvenience/qxlibeglintegration.h
/src/plugins/platforms/eglconvenience/qxlibeglintegration.cpp