Qt 4.8: QAuServerQWS Class Reference
QAuServerQWS Class Reference
Public Functions
void init (QSound *s)
Initializes the sound.
void insert (QAuBucketQWS *bucket)
bool okay ()
void play (QSound *s)
QAuServerQWS (QObject *parent)
void remove (QAuBucketQWS *bucket)
void stop (QSound *s)
Public Functions inherited from QAuServer
virtual void play (const QString &filename)
QAuServer (QObject *parent)
~QAuServer ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QAuBucketQWS * bucket (QSound *s)
Protected Functions inherited from QAuServer
QAuBucket * bucket (QSound *)
Returns the internal bucket record of sound s.
int decLoop (QSound *)
Decrements the QSound::loopRemaining() value for sound s, returning the result.
void setBucket (QSound *, QAuBucket *)
Sets the internal bucket record of sound s to b, deleting any previous setting.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void complete (int id)
void complete (QAuBucketQWS *bucket)
Private Functions
QAuBucketQWS * find (int id)
Properties
QHash< int, QAuBucketQWS * > buckets
QWSSoundClient * client
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 138 of file qsound_qws.cpp.
Constructors and Destructors
QAuServerQWS()
QAuServerQWS::QAuServerQWS (QObject * parent)
Definition at line 253 of file qsound_qws.cpp.
                                           :
     QAuServer(parent)
 {
 #ifndef MEDIA_SERVER
     setObjectName(QLatin1String("qauserverqws"));
 #ifdef QT_NO_QWS_SOUNDSERVER
     server = new QWSSoundServer( this ); // ### only suitable for single application
     connect( server, SIGNAL(soundCompleted(int)),
         this, SLOT(complete(int)) );
 #else
     client = new QWSSoundClient( this ); // ### requires successful connection
     connect( client, SIGNAL(soundCompleted(int)),
         this, SLOT(complete(int)) );
 #endif
 #endif // MEDIA_SERVER
 }
Functions
bucket()
QAuBucketQWS* QAuServerQWS::bucket (QSound * s) inline protected
Definition at line 224 of file qsound_qws.cpp.
     {
         return (QAuBucketQWS*)QAuServer::bucket( s );
     }
complete [1/2]
void QAuServerQWS::complete (int id) inline private slot
Definition at line 195 of file qsound_qws.cpp.
Referenced by QAuServerQWS().
     {
 #ifndef MEDIA_SERVER
         QAuBucketQWS *bucket = find( id );
         if( bucket ) {
             QSound *sound = bucket->sound();
             if( decLoop( sound ) ) {
                 play( sound );
             }
         }
 #else
         Q_UNUSED(id);
 #endif
     }
complete [2/2]
void QAuServerQWS::complete (QAuBucketQWS * bucket) inline private slot
Definition at line 211 of file qsound_qws.cpp.
     {
 #ifndef MEDIA_SERVER
         Q_UNUSED(bucket);
 #else
         QSound *sound = bucket->sound();
         if( decLoop( sound ) ) {
             play( sound );
         }
 #endif
     }
find()
QAuBucketQWS* QAuServerQWS::find (int id) inline private
Definition at line 232 of file qsound_qws.cpp.
     {
         QHash<int, QAuBucketQWS*>::Iterator it = buckets.find( id );
         if( it != buckets.end() ) {
             return it.value();
         }
         return 0;
     }
init()
void QAuServerQWS::init (QSound *) inline virtual
Initializes the sound.
The default implementation does nothing.
Reimplemented from QAuServer.
Definition at line 144 of file qsound_qws.cpp.
     {
         QAuBucketQWS *bucket = new QAuBucketQWS( this, s );
 #ifdef MEDIA_SERVER
         connect( bucket, SIGNAL(done(QAuBucketQWS*)),
             this, SLOT(complete(QAuBucketQWS*)) );
 #endif
         setBucket( s, bucket );
     }
insert()
void QAuServerQWS::insert (QAuBucketQWS * bucket) inline
Definition at line 156 of file qsound_qws.cpp.
Referenced by QAuBucketQWS::QAuBucketQWS().
     {
         buckets.insert( bucket->id(), bucket );
     }
okay()
bool QAuServerQWS::okay () inline virtual
Implements QAuServer.
Definition at line 191 of file qsound_qws.cpp.
 { return true; }
play()
void QAuServerQWS::play (QSound * s) inline virtual
Implements QAuServer.
Definition at line 168 of file qsound_qws.cpp.
     {
         QString filepath = QFileInfo( s->fileName() ).absoluteFilePath();
 #if defined(QT_NO_QWS_SOUNDSERVER)
         server->playFile( bucket( s )->id(), filepath );
 #elif defined(MEDIA_SERVER)
         bucket( s )->play();
 #else
         client->play( bucket( s )->id(), filepath );
 #endif
     }
remove()
void QAuServerQWS::remove (QAuBucketQWS * bucket) inline
Definition at line 162 of file qsound_qws.cpp.
Referenced by QAuBucketQWS::~QAuBucketQWS().
     {
         buckets.remove( bucket->id() );
     }
stop()
void QAuServerQWS::stop (QSound * s) inline virtual
Implements QAuServer.
Definition at line 180 of file qsound_qws.cpp.
     {
 #if defined(QT_NO_QWS_SOUNDSERVER)
         server->stopFile( bucket( s )->id() );
 #elif defined(MEDIA_SERVER)
         bucket( s )->stop();
 #else
         client->stop( bucket( s )->id() );
 #endif
     }
Properties
buckets
QHash<int, QAuBucketQWS*> QAuServerQWS::buckets private
Definition at line 242 of file qsound_qws.cpp.
client
QWSSoundClient* QAuServerQWS::client private
Definition at line 247 of file qsound_qws.cpp.
Referenced by QAuServerQWS().
The documentation for this class was generated from the following file:
/src/gui/kernel/qsound_qws.cpp