Qt 4.8: QPSPrintEngine Class Reference
QPSPrintEngine Class Reference
#include <qprintengine_ps_p.h>
Public Functions
virtual bool abort ()
Instructs the print engine to abort the printing process.
virtual bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
virtual void drawImage (const QRectF &r, const QImage &img, const QRectF &sr, Qt::ImageConversionFlags)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawImageInternal (const QRectF &r, QImage img, bool bitmap)
virtual void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
virtual bool end ()
Reimplement this function to finish painting on the current paint device.
virtual Qt::HANDLE handle () const
virtual bool newPage ()
Instructs the print engine to start a new page.
virtual QPrinter::PrinterState printerState () const
Returns the current state of the printer being used by the print engine.
QPSPrintEngine (QPrinter::PrinterMode m)
void setBrush ()
virtual QPaintEngine::Type type () const
Reimplement this function to return the paint engine Type.
~QPSPrintEngine ()
Public Functions inherited from QPdfBaseEngine
void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
int metric (QPaintDevice::PaintDeviceMetric metricType) const
Returns the metric for the given id.
QVariant property (PrintEnginePropertyKey key) const
Returns the print engine's property specified by key.
QPdfBaseEngine (QPdfBaseEnginePrivate &d, PaintEngineFeatures f)
void setPen ()
void setProperty (PrintEnginePropertyKey key, const QVariant &value)
Sets the print engine's property specified by key to the given value.
void setupGraphicsState (QPaintEngine::DirtyFlags flags)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
~QPdfBaseEngine ()
Public Functions inherited from QAlphaPaintEngine
virtual void drawImage (const QRectF &r, const QImage &image, const QRectF &sr)
~QAlphaPaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Public Functions inherited from QPrintEngine
virtual HDC getPrinterDC () const
virtual void releasePrinterDC (HDC) const
virtual ~QPrintEngine ()
Destroys the print engine.
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Types inherited from QPrintEngine
enum PrintEnginePropertyKey {
PPK_CollateCopies, PPK_ColorMode, PPK_Creator, PPK_DocumentName,
PPK_FullPage, PPK_NumberOfCopies, PPK_Orientation, PPK_OutputFileName,
PPK_PageOrder, PPK_PageRect, PPK_PageSize, PPK_PaperRect,
PPK_PaperSource, PPK_PrinterName, PPK_PrinterProgram, PPK_Resolution,
PPK_SelectionOption, PPK_SupportedResolutions, PPK_WindowsPageSize, PPK_FontEmbedding,
PPK_SuppressSystemPrintStatus, PPK_Duplex, PPK_PaperSources, PPK_CustomPaperSize,
PPK_PageMargins, PPK_CopyCount, PPK_SupportsMultipleCopies, PPK_PaperSize = PPK_PageSize,
PPK_CustomBase = 0xff00
}
This enum is used to communicate properties between the print engine and QPrinter.
Protected Functions inherited from QAlphaPaintEngine
QRegion alphaClipping () const
void cleanUp ()
bool continueCall () const
void flushAndInit (bool init=true)
QAlphaPaintEngine (QAlphaPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 71 of file qprintengine_ps_p.h.
Constructors and Destructors
QPSPrintEngine()
QPSPrintEngine::QPSPrintEngine (QPrinter::PrinterMode m) explicit
Definition at line 660 of file qprintengine_ps.cpp.
     : QPdfBaseEngine(*(new QPSPrintEnginePrivate(m)),
                      PrimitiveTransform
                      | PatternTransform
                      | PixmapTransform
                      | PainterPaths
                      | PatternBrush
         )
 {
 }
~QPSPrintEngine()
QPSPrintEngine::~QPSPrintEngine ()
Definition at line 716 of file qprintengine_ps.cpp.
 {
     Q_D(QPSPrintEngine);
     if (d->fd >= 0)
 #if defined(Q_OS_WIN) && defined(_MSC_VER) && _MSC_VER >= 1400
         ::_close(d->fd);
 #else
         ::close(d->fd);
 #endif
 }
Functions
abort()
bool QPSPrintEngine::abort () virtual
Instructs the print engine to abort the printing process.
Returns true if successful; otherwise returns false.
Implements QPrintEngine.
Definition at line 958 of file qprintengine_ps.cpp.
Referenced by type().
 {
     // ### abort!?!
     return false;
 }
begin()
bool QPSPrintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Reimplemented from QPdfBaseEngine.
Definition at line 727 of file qprintengine_ps.cpp.
 {
     Q_D(QPSPrintEngine);
     if (d->fd >= 0)
         return true;
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::begin(pdev);
         if (!continueCall())
             return true;
     }
     if(!QPdfBaseEngine::begin(pdev)) {
         d->printerState = QPrinter::Error;
         return false;
     }
     d->pageCount = 1;                // initialize state
     d->pen = QPen(Qt::black);
     d->brush = Qt::NoBrush;
     d->hasPen = true;
     d->hasBrush = false;
     d->clipEnabled = false;
     d->allClipped = false;
     d->boundingBox = QRect();
     d->fontsUsed = "";
     d->hugeDocument = false;
     d->simplePen = false;
     setActive(true);
     d->printerState = QPrinter::Active;
     newPage();
     return true;
 }
drawImage()
void QPSPrintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Definition at line 871 of file qprintengine_ps.cpp.
 {
     Q_D(QPSPrintEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawImage(r, img, sr);
         if (!continueCall())
             return;
     }
     QImage image = img.copy(sr.toRect());
     drawImageInternal(r, image, false);
 }
drawImageInternal()
void QPSPrintEngine::drawImageInternal (const QRectF & r, QImage img, bool bitmap) virtual
Definition at line 833 of file qprintengine_ps.cpp.
Referenced by drawImage(), and drawPixmap().
 {
     Q_D(QPSPrintEngine);
     if (d->clipEnabled && d->allClipped)
         return;
     if (bitmap && image.depth() != 1)
         bitmap = false;
     QImage mask;
     // the below is not necessary since it's handled by the alpha
     // engine
     if (!d->useAlphaEngine && !bitmap) {
         if (image.format() == QImage::Format_Mono || image.format() == QImage::Format_MonoLSB)
             image = image.convertToFormat(QImage::Format_Indexed8);
         if (image.hasAlphaChannel()) {
             // get better alpha dithering
             int xscale = image.width();
             xscale *= xscale <= 800 ? 4 : (xscale <= 1600 ? 2 : 1);
             int yscale = image.height();
             yscale *= yscale <= 800 ? 4 : (yscale <= 1600 ? 2 : 1);
             image = image.scaled(xscale, yscale);
             mask = image.createAlphaMask(Qt::OrderedAlphaDither);
         }
     }
     *d->currentPage << "q\n";
     if(!d->simplePen)
         *d->currentPage << QPdf::generateMatrix(d->stroker.matrix);
     QBrush b = d->brush;
     if (image.depth() == 1) {
         // set current pen as brush
         d->brush = d->pen.brush();
         setBrush();
     }
     d->drawImage(r.x(), r.y(), r.width(), r.height(), image, mask);
     *d->currentPage << "Q\n";
     d->brush = b;
 }
drawPixmap()
void QPSPrintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Reimplemented from QAlphaPaintEngine.
Definition at line 885 of file qprintengine_ps.cpp.
 {
     Q_D(QPSPrintEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawPixmap(r, pm, sr);
         if (!continueCall())
             return;
     }
     QImage img = pm.copy(sr.toRect()).toImage();
     drawImageInternal(r, img, true);
 }
drawTiledPixmap()
void QPSPrintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QAlphaPaintEngine.
Definition at line 899 of file qprintengine_ps.cpp.
 {
     Q_D(QPSPrintEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::drawTiledPixmap(r, pixmap, p);
         if (!continueCall())
             return;
     }
     if (d->clipEnabled && d->allClipped)
         return;
     // ### Optimize implementation!
     qreal yPos = r.y();
     qreal yOff = p.y();
     while(yPos < r.y() + r.height()) {
         qreal drawH = pixmap.height() - yOff;    // Cropping first row
         if (yPos + drawH > r.y() + r.height())        // Cropping last row
             drawH = r.y() + r.height() - yPos;
         qreal xPos = r.x();
         qreal xOff = p.x();
         while(xPos < r.x() + r.width()) {
             qreal drawW = pixmap.width() - xOff; // Cropping first column
             if (xPos + drawW > r.x() + r.width())    // Cropping last column
                 drawW = r.x() + r.width() - xPos;
             // ########
             painter()->drawPixmap(QPointF(xPos, yPos).toPoint(), pixmap,
                                   QRectF(xOff, yOff, drawW, drawH).toRect());
             xPos += drawW;
             xOff = 0;
         }
         yPos += drawH;
         yOff = 0;
     }
 }
end()
bool QPSPrintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Reimplemented from QPdfBaseEngine.
Definition at line 766 of file qprintengine_ps.cpp.
 {
     Q_D(QPSPrintEngine);
     if (d->useAlphaEngine) {
         QAlphaPaintEngine::end();
         if (!continueCall())
             return true;
     }
     // we're writing to lp/lpr through a pipe, we don't want to crash with SIGPIPE
     // if lp/lpr dies
     ignoreSigPipe(true);
     d->flushPage(true);
     QByteArray trailer;
     QPdf::ByteStream s(&trailer);
     s << "%%Trailer\n"
          "%%Pages: " << d->pageCount - 1 << '\n' <<
         wrapDSC("%%DocumentFonts: " + d->fontsUsed);
     s << "%%EOF\n";
     d->outDevice->write(trailer);
     QPdfBaseEngine::end();
     ignoreSigPipe(false);
     d->firstPage = true;
     d->headerDone = false;
     setActive(false);
     d->printerState = QPrinter::Idle;
     d->pdev = 0;
     return true;
 }
handle()
virtual Qt::HANDLE QPSPrintEngine::handle () const inline virtual
Definition at line 98 of file qprintengine_ps_p.h.
 { return 0; }
newPage()
bool QPSPrintEngine::newPage () virtual
Instructs the print engine to start a new page.
Returns true if the printer was able to create the new page; otherwise returns false.
Reimplemented from QPdfBaseEngine.
Definition at line 936 of file qprintengine_ps.cpp.
Referenced by begin(), and type().
 {
     Q_D(QPSPrintEngine);
     if (!d->firstPage && d->useAlphaEngine)
         flushAndInit();
     // we're writing to lp/lpr through a pipe, we don't want to crash with SIGPIPE
     // if lp/lpr dies
     ignoreSigPipe(true);
     if (!d->firstPage)
         d->flushPage();
     d->firstPage = false;
     ignoreSigPipe(false);
     delete d->currentPage;
     d->currentPage = new QPdfPage;
     d->stroker.stream = d->currentPage;
     return QPdfBaseEngine::newPage();
 }
printerState()
QPrinter::PrinterState QPSPrintEngine::printerState () const virtual
Returns the current state of the printer being used by the print engine.
Implements QPrintEngine.
Definition at line 964 of file qprintengine_ps.cpp.
Referenced by type().
 {
     Q_D(const QPSPrintEngine);
     return d->printerState;
 }
setBrush()
void QPSPrintEngine::setBrush () virtual
Implements QPdfBaseEngine.
Definition at line 801 of file qprintengine_ps.cpp.
Referenced by drawImageInternal().
 {
     Q_D(QPSPrintEngine);
 #if 0
     bool specifyColor;
     int gStateObject = 0;
     int patternObject = d->addBrushPattern(brush, d->stroker.matrix, brushOrigin, &specifyColor, &gStateObject);
     *d->currentPage << (patternObject ? "/PCSp cs " : "/CSp cs ");
     if (specifyColor) {
         QColor rgba = brush.color();
         *d->currentPage << rgba.redF()
                         << rgba.greenF()
                         << rgba.blueF();
     }
     if (patternObject)
         *d->currentPage << "/Pat" << patternObject;
     *d->currentPage << "scn\n";
 #endif
     QColor rgba = d->brush.color();
     if (d->colorMode == QPrinter::GrayScale) {
         qreal gray = qGray(rgba.rgba())/255.;
         *d->currentPage << gray << gray << gray;
     } else {
         *d->currentPage << rgba.redF()
                         << rgba.greenF()
                         << rgba.blueF();
     }
     *d->currentPage << "scn\n"
                     << "/BSt " << d->brush.style() << "def\n";
 }
type()
virtual QPaintEngine::Type QPSPrintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 91 of file qprintengine_ps_p.h.
 { return QPaintEngine::PostScript; }
The documentation for this class was generated from the following files:
/src/gui/painting/qprintengine_ps_p.h
/src/gui/painting/qprintengine_ps.cpp