Qt 4.8: QNetworkSessionPrivateImpl Class Reference
QNetworkSessionPrivateImpl Class Reference
#include <qnetworksession_impl.h>
Classes
struct Statistics
Public Functions
void accept ()
void accept ()
quint64 activeTime () const
quint64 activeTime () const
quint64 bytesReceived () const
quint64 bytesReceived () const
quint64 bytesWritten () const
quint64 bytesWritten () const
void close ()
void close ()
QNetworkInterface currentInterface () const
QNetworkInterface currentInterface () const
QNetworkSession::SessionError error () const
QNetworkSession::SessionError error () const
QString errorString () const
QString errorString () const
void ignore ()
void ignore ()
void migrate ()
void migrate ()
void open ()
void open ()
QNetworkSessionPrivateImpl ()
QNetworkSessionPrivateImpl (QIcdEngine *engine)
void reject ()
void reject ()
QVariant sessionProperty (const QString &key) const
QVariant sessionProperty (const QString &key) const
void setSessionProperty (const QString &key, const QVariant &value)
void setSessionProperty (const QString &key, const QVariant &value)
void stop ()
void stop ()
void syncStateWithInterface ()
void syncStateWithInterface ()
~QNetworkSessionPrivateImpl ()
~QNetworkSessionPrivateImpl ()
Public Functions inherited from QNetworkSessionPrivate
QNetworkSessionPrivate ()
virtual void setALREnabled (bool)
virtual ~QNetworkSessionPrivate ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
void connectTimeout ()
void decrementTimeout ()
void do_open ()
void finishStopBySendingClosedSignal ()
void forcedSessionClose (const QNetworkConfiguration &config)
void iapStateChanged (const QString &iapid, uint icd_connection_state)
void networkConfigurationsChanged ()
void networkConfigurationsChanged ()
void stateChange (const QDBusMessage &rep)
void updateProxies (QNetworkSession::State newState)
Private Functions
void cleanupSession (void)
void clearConfiguration (QNetworkConfiguration &config)
void clearProxyInformation ()
QNetworkConfiguration & copyConfig (QNetworkConfiguration &fromConfig, QNetworkConfiguration &toConfig, bool deepCopy=true)
Statistics getStatistics () const
void updateIdentifier (const QString &newId)
void updateProxyInformation ()
void updateState (QNetworkSession::State)
void updateStateFromActiveConfig ()
void updateStateFromActiveConfig ()
void updateStateFromServiceNetwork ()
void updateStateFromServiceNetwork ()
Properties
QNetworkConfiguration config
icd_connection_flags connectFlags
QString currentNetworkInterface
QNetworkSession::State currentState
QBearerEngineImpl * engine
QIcdEngine * engine
QNetworkSession::SessionError lastError
bool m_asynchCallActive
QTimer m_connectRequestTimer
QDBusInterface * m_dbusInterface
QTimer m_stopTimer
QNetworkConfigurationManager manager
bool opened
int sessionTimeout
quint64 startTime
QDateTime startTime
Friends
class IcdListener
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QNetworkSessionPrivate
void closed ()
void error (QNetworkSession::SessionError error)
void newConfigurationActivated ()
void preferredConfigurationChanged (const QNetworkConfiguration &config, bool isSeamless)
void quitPendingWaitsForOpened ()
void stateChanged (QNetworkSession::State state)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QNetworkSessionPrivate
QNetworkConfigurationPrivatePointer privateConfiguration (const QNetworkConfiguration &config) const
void setPrivateConfiguration (QNetworkConfiguration &config, QNetworkConfigurationPrivatePointer ptr) const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QNetworkSessionPrivate
QNetworkConfiguration activeConfig
bool isOpen
QMutex mutex
QNetworkConfiguration publicConfig
QNetworkSession * q
QNetworkConfiguration serviceConfig
QNetworkSession::State state
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 88 of file qnetworksession_impl.h.
Constructors and Destructors
QNetworkSessionPrivateImpl() [1/2]
QNetworkSessionPrivateImpl::QNetworkSessionPrivateImpl (QIcdEngine * engine) inline
Definition at line 93 of file qnetworksession_impl.h.
     :   engine(engine),
         connectFlags(ICD_CONNECTION_FLAG_USER_EVENT),
         currentState(QNetworkSession::Invalid),
         m_asynchCallActive(false)
     {
         m_stopTimer.setSingleShot(true);
         connect(&m_stopTimer, SIGNAL(timeout()), this, SLOT(finishStopBySendingClosedSignal()));
         QDBusConnection systemBus = QDBusConnection::connectToBus(
             QDBusConnection::SystemBus,
             QUuid::createUuid().toString());
         m_dbusInterface = new QDBusInterface(ICD_DBUS_API_INTERFACE,
                                          ICD_DBUS_API_PATH,
                                          ICD_DBUS_API_INTERFACE,
                                          systemBus,
                                          this);
         systemBus.connect(ICD_DBUS_API_INTERFACE,
                         ICD_DBUS_API_PATH,
                         ICD_DBUS_API_INTERFACE,
                         ICD_DBUS_API_CONNECT_SIG,
                         this,
                         SLOT(stateChange(const QDBusMessage&)));
         qDBusRegisterMetaType<ICd2DetailsDBusStruct>();
         qDBusRegisterMetaType<ICd2DetailsList>();
         m_connectRequestTimer.setSingleShot(true);
         connect(&m_connectRequestTimer, SIGNAL(timeout()), this, SLOT(connectTimeout()));
     }
~QNetworkSessionPrivateImpl() [1/2]
QNetworkSessionPrivateImpl::~QNetworkSessionPrivateImpl () inline
Definition at line 126 of file qnetworksession_impl.h.
     {
         cleanupSession();
         QDBusConnection::disconnectFromBus(m_dbusInterface->connection().name());
     }
QNetworkSessionPrivateImpl() [2/2]
QNetworkSessionPrivateImpl::QNetworkSessionPrivateImpl () inline
Definition at line 72 of file qnetworksession_impl.h.
         : startTime(0), sessionTimeout(-1)
     {}
~QNetworkSessionPrivateImpl() [2/2]
QNetworkSessionPrivateImpl::~QNetworkSessionPrivateImpl () inline
Definition at line 75 of file qnetworksession_impl.h.
     {}
Functions
accept() [1/2]
void QNetworkSessionPrivateImpl::accept () virtual
Implements QNetworkSessionPrivate.
accept() [2/2]
void QNetworkSessionPrivateImpl::accept () virtual
Implements QNetworkSessionPrivate.
Definition at line 970 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
 }
activeTime() [1/2]
quint64 QNetworkSessionPrivateImpl::activeTime () const virtual
Implements QNetworkSessionPrivate.
activeTime() [2/2]
quint64 QNetworkSessionPrivateImpl::activeTime () const virtual
Implements QNetworkSessionPrivate.
Definition at line 304 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     return getStatistics().activeTime;
 }
bytesReceived() [1/2]
quint64 QNetworkSessionPrivateImpl::bytesReceived () const virtual
Implements QNetworkSessionPrivate.
bytesReceived() [2/2]
quint64 QNetworkSessionPrivateImpl::bytesReceived () const virtual
Implements QNetworkSessionPrivate.
Definition at line 299 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     return getStatistics().rxData;
 }
bytesWritten() [1/2]
quint64 QNetworkSessionPrivateImpl::bytesWritten () const virtual
Implements QNetworkSessionPrivate.
bytesWritten() [2/2]
quint64 QNetworkSessionPrivateImpl::bytesWritten () const virtual
Implements QNetworkSessionPrivate.
Definition at line 294 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     return getStatistics().txData;
 }
cleanupSession()
void QNetworkSessionPrivateImpl::cleanupSession (void) private
Definition at line 154 of file qnetworksession_impl.cpp.
 {
     QObject::disconnect(q, SIGNAL(stateChanged(QNetworkSession::State)),
                         this, SLOT(updateProxies(QNetworkSession::State)));
 }
clearConfiguration()
void QNetworkSessionPrivateImpl::clearConfiguration (QNetworkConfiguration & config) private
Definition at line 555 of file qnetworksession_impl.cpp.
Referenced by updateStateFromActiveConfig().
 {
     IcdNetworkConfigurationPrivate *icdConfig = toIcdConfig(privateConfiguration(config));
     QMutexLocker locker(&icdConfig->mutex);
     icdConfig->network_id.clear();
     icdConfig->iap_type.clear();
     icdConfig->network_attrs = 0;
     icdConfig->service_type.clear();
     icdConfig->service_id.clear();
     icdConfig->service_attrs = 0;
 }
clearProxyInformation()
void QNetworkSessionPrivateImpl::clearProxyInformation () private
Definition at line 1071 of file qnetworksession_impl.cpp.
Referenced by updateProxies().
 {
     Maemo::ProxyConf::clear();
 }
close() [1/2]
void QNetworkSessionPrivateImpl::close () virtual
Implements QNetworkSessionPrivate.
close() [2/2]
void QNetworkSessionPrivateImpl::close () virtual
Implements QNetworkSessionPrivate.
Definition at line 889 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     if (m_connectRequestTimer.isActive())
         m_connectRequestTimer.stop();
     if (serviceConfig.isValid()) {
         lastError = QNetworkSession::OperationNotSupportedError;
         emit QNetworkSessionPrivate::error(lastError);
     } else if (isOpen) {
         if ((activeConfig.state() & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         // We will not wait any disconnect from icd as it might never come
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "closing session" << publicConfig.identifier();
 #endif
         state = QNetworkSession::Closing;
         emit stateChanged(state);
         // we fake a disconnection, session error is sent
         updateState(QNetworkSession::Disconnected);
         opened = false;
         isOpen = false;
         m_dbusInterface->call(ICD_DBUS_API_DISCONNECT_REQ, ICD_CONNECTION_FLAG_APPLICATION_EVENT);
         startTime = QDateTime();
         } else {
         opened = false;
         isOpen = false;
         emit closed();
     }
     }
 }
configurationChanged
void QNetworkSessionPrivateImpl::configurationChanged (QNetworkConfigurationPrivatePointer config) private slot
Definition at line 367 of file qnetworksession_impl.cpp.
Referenced by ~QNetworkSessionPrivateImpl().
 {
     if (serviceConfig.isValid() &&
         (config->id == serviceConfig.identifier() || config->id == activeConfig.identifier())) {
         updateStateFromServiceNetwork();
     } else if (config->id == activeConfig.identifier()) {
         updateStateFromActiveConfig();
     }
 }
connectionError
void QNetworkSessionPrivateImpl::connectionError (const QString & id, QBearerEngineImpl::ConnectionError error) private slot
Definition at line 390 of file qnetworksession_impl.cpp.
Referenced by ~QNetworkSessionPrivateImpl().
 {
     if (activeConfig.identifier() == id) {
         networkConfigurationsChanged();
         switch (error) {
         case QBearerEngineImpl::OperationNotSupported:
             lastError = QNetworkSession::OperationNotSupportedError;
             opened = false;
             break;
         case QBearerEngineImpl::InterfaceLookupError:
         case QBearerEngineImpl::ConnectError:
         case QBearerEngineImpl::DisconnectionError:
         default:
             lastError = QNetworkSession::UnknownSessionError;
         }
         emit QNetworkSessionPrivate::error(lastError);
     }
 }
connectTimeout
void QNetworkSessionPrivateImpl::connectTimeout () private slot
Definition at line 881 of file qnetworksession_impl.cpp.
 {
     updateState(QNetworkSession::Disconnected);
     if (publicConfig.type() == QNetworkConfiguration::UserChoice)
             copyConfig(publicConfig, activeConfig);
         emit QNetworkSessionPrivate::error(QNetworkSession::UnknownSessionError);
 }
copyConfig()
QNetworkConfiguration & QNetworkSessionPrivateImpl::copyConfig (QNetworkConfiguration & fromConfig, QNetworkConfiguration & toConfig, bool deepCopy = true) private
Definition at line 310 of file qnetworksession_impl.cpp.
Referenced by connectTimeout(), stateChange(), syncStateWithInterface(), and updateState().
 {
     IcdNetworkConfigurationPrivate *cpPriv;
     if (deepCopy) {
         cpPriv = new IcdNetworkConfigurationPrivate;
         setPrivateConfiguration(toConfig, QNetworkConfigurationPrivatePointer(cpPriv));
     } else {
         cpPriv = toIcdConfig(privateConfiguration(toConfig));
     }
     IcdNetworkConfigurationPrivate *fromPriv = toIcdConfig(privateConfiguration(fromConfig));
     QMutexLocker toLocker(&cpPriv->mutex);
     QMutexLocker fromLocker(&fromPriv->mutex);
     cpPriv->name = fromPriv->name;
     cpPriv->isValid = fromPriv->isValid;
     // Note that we do not copy id field here as the publicConfig does
     // not contain a valid IAP id.
     cpPriv->state = fromPriv->state;
     cpPriv->type = fromPriv->type;
     cpPriv->roamingSupported = fromPriv->roamingSupported;
     cpPriv->purpose = fromPriv->purpose;
     cpPriv->network_id = fromPriv->network_id;
     cpPriv->iap_type = fromPriv->iap_type;
     cpPriv->bearerType = fromPriv->bearerType;
     cpPriv->network_attrs = fromPriv->network_attrs;
     cpPriv->service_type = fromPriv->service_type;
     cpPriv->service_id = fromPriv->service_id;
     cpPriv->service_attrs = fromPriv->service_attrs;
     return toConfig;
 }
currentInterface() [1/2]
QNetworkInterface QNetworkSessionPrivateImpl::currentInterface () const virtual
Implements QNetworkSessionPrivate.
currentInterface() [2/2]
QNetworkInterface QNetworkSessionPrivateImpl::currentInterface () const virtual
Implements QNetworkSessionPrivate.
Definition at line 985 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     if (!publicConfig.isValid() || state != QNetworkSession::Connected)
         return QNetworkInterface();
     if (currentNetworkInterface.isEmpty())
         return QNetworkInterface();
     return QNetworkInterface::interfaceFromName(currentNetworkInterface);
 }
decrementTimeout
void QNetworkSessionPrivateImpl::decrementTimeout () private slot
Definition at line 410 of file qnetworksession_impl.cpp.
Referenced by ~QNetworkSessionPrivateImpl().
 {
     if (--sessionTimeout <= 0) {
         disconnect(engine, SIGNAL(updateCompleted()), this, SLOT(decrementTimeout()));
         sessionTimeout = -1;
         close();
     }
 }
do_open
void QNetworkSessionPrivateImpl::do_open () private slot
Definition at line 728 of file qnetworksession_impl.cpp.
Referenced by open().
 {
     icd_connection_flags flags = connectFlags;
     QString iap = publicConfig.identifier();
     if (state == QNetworkSession::Connected) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "Already connected to" << activeConfig.identifier();
 #endif
         emit stateChanged(QNetworkSession::Connected);
         emit quitPendingWaitsForOpened();
     return;
     }
     if (publicConfig.type() == QNetworkConfiguration::UserChoice)
         config = activeConfig;
     else
         config = publicConfig;
     if (iap == OSSO_IAP_ANY) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "connecting to default IAP" << iap;
 #endif
         m_connectRequestTimer.start(ICD_LONG_CONNECT_TIMEOUT);
         m_dbusInterface->asyncCall(ICD_DBUS_API_CONNECT_REQ, (uint)flags); // Return value ignored
         m_asynchCallActive = true;
     } else {
         IcdNetworkConfigurationPrivate *icdConfig = toIcdConfig(privateConfiguration(config));
         icdConfig->mutex.lock();
         ICd2DetailsDBusStruct icd2;
         icd2.serviceType = icdConfig->service_type;
         icd2.serviceAttributes = icdConfig->service_attrs;
         icd2.setviceId = icdConfig->service_id;
         icd2.networkType = icdConfig->iap_type;
         icd2.networkAttributes = icdConfig->network_attrs;
         if (icdConfig->network_attrs & ICD_NW_ATTR_IAPNAME) {
             icd2.networkId  = QByteArray(iap.toLatin1());
         } else {
             icd2.networkId  = icdConfig->network_id;
         }
         icdConfig->mutex.unlock();
 #ifdef BEARER_MANAGEMENT_DEBUG
     qDebug("connecting to %s/%s/0x%x/%s/0x%x/%s",
         icd2.networkId.data(),
         icd2.networkType.toAscii().constData(),
         icd2.networkAttributes,
         icd2.serviceType.toAscii().constData(),
         icd2.serviceAttributes,
         icd2.setviceId.toAscii().constData());
 #endif
         ICd2DetailsList paramArray;
         paramArray.append(icd2);
         m_connectRequestTimer.start(ICD_LONG_CONNECT_TIMEOUT);
         m_dbusInterface->asyncCall(ICD_DBUS_API_CONNECT_REQ, (uint)flags, QVariant::fromValue(paramArray)); // Return value ignored
         m_asynchCallActive = true;
     }
 }
error() [1/2]
QNetworkSession::SessionError QNetworkSessionPrivateImpl::error () const virtual
Implements QNetworkSessionPrivate.
error() [2/2]
QNetworkSession::SessionError QNetworkSessionPrivateImpl::error () const virtual
Implements QNetworkSessionPrivate.
Definition at line 1047 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     return QNetworkSession::UnknownSessionError;
 }
errorString() [1/2]
QString QNetworkSessionPrivateImpl::errorString () const virtual
Implements QNetworkSessionPrivate.
errorString() [2/2]
QString QNetworkSessionPrivateImpl::errorString () const virtual
Implements QNetworkSessionPrivate.
Definition at line 1025 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     QString errorStr;
     switch(q->error()) {
     case QNetworkSession::RoamingError:
         errorStr = QNetworkSessionPrivateImpl::tr("Roaming error");
         break;
     case QNetworkSession::SessionAbortedError:
         errorStr = QNetworkSessionPrivateImpl::tr("Session aborted by user or system");
         break;
     case QNetworkSession::InvalidConfigurationError:
         errorStr = QNetworkSessionPrivateImpl::tr("The specified configuration cannot be used.");
         break;
     default:
     case QNetworkSession::UnknownSessionError:
         errorStr = QNetworkSessionPrivateImpl::tr("Unidentified Error");
         break;
     }
     return errorStr;
 }
finishStopBySendingClosedSignal
void QNetworkSessionPrivateImpl::finishStopBySendingClosedSignal () private slot
Definition at line 955 of file qnetworksession_impl.cpp.
 {
     if ((activeConfig.state() & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         state = QNetworkSession::Connected;
         emit stateChanged(state);
     }
     emit closed();
 }
forcedSessionClose
void QNetworkSessionPrivateImpl::forcedSessionClose (const QNetworkConfiguration & config) private slot
Definition at line 377 of file qnetworksession_impl.cpp.
Referenced by ~QNetworkSessionPrivateImpl().
 {
     if (activeConfig == config) {
         opened = false;
         isOpen = false;
         emit closed();
         lastError = QNetworkSession::SessionAbortedError;
         emit QNetworkSessionPrivate::error(lastError);
     }
 }
getStatistics()
QNetworkSessionPrivateImpl::Statistics QNetworkSessionPrivateImpl::getStatistics () const private
Definition at line 254 of file qnetworksession_impl.cpp.
Referenced by activeTime(), bytesReceived(), and bytesWritten().
 {
     /* This could be also implemented by using the Maemo::Icd::statistics()
      * that gets the statistics data for a specific IAP. Change if
      * necessary.
      */
     Maemo::Icd icd;
     QList<Maemo::IcdStatisticsResult> stats_results;
     Statistics stats = { 0, 0, 0};
     if (!icd.statistics(stats_results))
         return stats;
     foreach (const Maemo::IcdStatisticsResult &res, stats_results) {
         if (res.params.network_attrs & ICD_NW_ATTR_IAPNAME) {
             /* network_id is the IAP UUID */
             if (QString(res.params.network_id.data()) == activeConfig.identifier()) {
                 stats.txData = res.bytes_sent;
                 stats.rxData = res.bytes_received;
                 stats.activeTime = res.time_active;
             }
         } else {
             /* We probably will never get to this branch */
             IcdNetworkConfigurationPrivate *icdConfig =
                 toIcdConfig(privateConfiguration(activeConfig));
             icdConfig->mutex.lock();
             if (res.params.network_id == icdConfig->network_id) {
                 stats.txData = res.bytes_sent;
                 stats.rxData = res.bytes_received;
                 stats.activeTime = res.time_active;
             }
             icdConfig->mutex.unlock();
         }
     }
     return stats;
 }
iapStateChanged
void QNetworkSessionPrivateImpl::iapStateChanged (const QString & iapid, uint icd_connection_state) private slot
Definition at line 126 of file qnetworksession_impl.cpp.
Referenced by syncStateWithInterface().
 {
     if (((publicConfig.type() == QNetworkConfiguration::UserChoice) &&
          (activeConfig.identifier() == iapid)) ||
         (publicConfig.identifier() == iapid)) {
         switch (icd_connection_state) {
         case ICD_STATE_CONNECTING:
             updateState(QNetworkSession::Connecting);
             break;
         case ICD_STATE_CONNECTED:
             updateState(QNetworkSession::Connected);
             break;
         case ICD_STATE_DISCONNECTING:
             updateState(QNetworkSession::Closing);
             break;
         case ICD_STATE_DISCONNECTED:
             updateState(QNetworkSession::Disconnected);
             break;
         default:
             break;
         }
     }
     if (publicConfig.type() == QNetworkConfiguration::UserChoice) {
         updateIdentifier(iapid);
     }
 }
ignore() [1/2]
void QNetworkSessionPrivateImpl::ignore () virtual
Implements QNetworkSessionPrivate.
ignore() [2/2]
void QNetworkSessionPrivateImpl::ignore () virtual
Implements QNetworkSessionPrivate.
Definition at line 975 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
 }
migrate() [1/2]
void QNetworkSessionPrivateImpl::migrate () virtual
Implements QNetworkSessionPrivate.
migrate() [2/2]
void QNetworkSessionPrivateImpl::migrate () virtual
Implements QNetworkSessionPrivate.
Definition at line 965 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
 }
networkConfigurationsChanged [1/2]
void QNetworkSessionPrivateImpl::networkConfigurationsChanged () private slot
networkConfigurationsChanged [2/2]
void QNetworkSessionPrivateImpl::networkConfigurationsChanged () private slot
Definition at line 516 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), syncStateWithInterface(), and ~QNetworkSessionPrivateImpl().
 {
     if (serviceConfig.isValid())
         updateStateFromServiceNetwork();
     else
         updateStateFromActiveConfig();
 }
open() [1/2]
void QNetworkSessionPrivateImpl::open () virtual
Implements QNetworkSessionPrivate.
open() [2/2]
void QNetworkSessionPrivateImpl::open () virtual
Implements QNetworkSessionPrivate.
Definition at line 675 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     if (m_stopTimer.isActive()) {
         m_stopTimer.stop();
     }
     if (!publicConfig.isValid()) {
         lastError = QNetworkSession::InvalidConfigurationError;
         emit QNetworkSessionPrivate::error(lastError);
         return;
     }
     if (serviceConfig.isValid()) {
         lastError = QNetworkSession::OperationNotSupportedError;
         emit QNetworkSessionPrivate::error(lastError);
     } else if (!opened) {
     if (publicConfig.type() == QNetworkConfiguration::UserChoice) {
         /* Caller is trying to connect to default IAP.
          * At this time we will not know the IAP details so we just
          * connect and update the active config when the IAP is
          * connected.
          */
         opened = true;
             state = QNetworkSession::Connecting;
             emit stateChanged(state);
         QTimer::singleShot(0, this, SLOT(do_open()));
         return;
     }
     /* User is connecting to one specific IAP. If that IAP is not
      * in discovered state we cannot continue.
      */
         if ((activeConfig.state() & QNetworkConfiguration::Discovered) !=
             QNetworkConfiguration::Discovered) {
             lastError =QNetworkSession::InvalidConfigurationError;
             emit QNetworkSessionPrivate::error(lastError);
             return;
         }
         opened = true;
         if ((activeConfig.state() & QNetworkConfiguration::Active) != QNetworkConfiguration::Active) {
             state = QNetworkSession::Connecting;
             emit stateChanged(state);
             QTimer::singleShot(0, this, SLOT(do_open()));
             return;
         }
         isOpen = (activeConfig.state() & QNetworkConfiguration::Active) == QNetworkConfiguration::Active;
         if (isOpen)
             emit quitPendingWaitsForOpened();
     } else {
         /* We seem to be active so inform caller */
         emit quitPendingWaitsForOpened();
     }
 }
reject() [1/2]
void QNetworkSessionPrivateImpl::reject () virtual
Implements QNetworkSessionPrivate.
reject() [2/2]
void QNetworkSessionPrivateImpl::reject () virtual
Implements QNetworkSessionPrivate.
Definition at line 980 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
 }
sessionProperty() [1/2]
QVariant QNetworkSessionPrivateImpl::sessionProperty (const QString & key) const virtual
Implements QNetworkSessionPrivate.
sessionProperty() [2/2]
QVariant QNetworkSessionPrivateImpl::sessionProperty (const QString & key) const virtual
Implements QNetworkSessionPrivate.
Definition at line 1019 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     return properties.value(key);
 }
setSessionProperty() [1/2]
void QNetworkSessionPrivateImpl::setSessionProperty (const QString & key, const QVariant & value) virtual
Implements QNetworkSessionPrivate.
setSessionProperty() [2/2]
void QNetworkSessionPrivateImpl::setSessionProperty (const QString & key, const QVariant & value) virtual
Implements QNetworkSessionPrivate.
Definition at line 997 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     if (value.isValid()) {
     properties.insert(key, value);
     if (key == "ConnectInBackground") {
         bool v = value.toBool();
         if (v)
         connectFlags = ICD_CONNECTION_FLAG_APPLICATION_EVENT;
         else
         connectFlags = ICD_CONNECTION_FLAG_USER_EVENT;
     }
     } else {
     properties.remove(key);
     /* Set default value when property is removed */
     if (key == "ConnectInBackground")
         connectFlags = ICD_CONNECTION_FLAG_USER_EVENT;
     }
 }
stateChange
void QNetworkSessionPrivateImpl::stateChange (const QDBusMessage & rep) private slot
Definition at line 789 of file qnetworksession_impl.cpp.
 {
      if (m_asynchCallActive == true) {
         if (m_connectRequestTimer.isActive())
             m_connectRequestTimer.stop();
         m_asynchCallActive = false;
         QString result = rep.arguments().at(5).toString(); // network id or empty string
         QString connected_iap = result;
         if (connected_iap.isEmpty()) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug() << "connect to"<< publicConfig.identifier() << "failed, result is empty";
 #endif
             updateState(QNetworkSession::Disconnected);
             emit QNetworkSessionPrivate::error(QNetworkSession::SessionAbortedError);
             if (publicConfig.type() == QNetworkConfiguration::UserChoice)
                     copyConfig(publicConfig, activeConfig);
             return;
         }
          /* If the user tried to connect to some specific connection (foo)
          * and we were already connected to some other connection (bar),
          * then we cannot activate this session although icd has a valid
          * connection to somewhere.
          */
         if ((publicConfig.type() != QNetworkConfiguration::UserChoice) &&
             (connected_iap != config.identifier())) {
             updateState(QNetworkSession::Disconnected);
             emit QNetworkSessionPrivate::error(QNetworkSession::UnknownSessionError);
             return;
         }
         IcdNetworkConfigurationPrivate *icdConfig = toIcdConfig(privateConfiguration(config));
         /* Did we connect to non saved IAP? */
         icdConfig->mutex.lock();
         if (!(icdConfig->network_attrs & ICD_NW_ATTR_IAPNAME)) {
             /* Because the connection succeeded, the IAP is now known.
              */
             icdConfig->network_attrs |= ICD_NW_ATTR_IAPNAME;
             icdConfig->id = connected_iap;
         }
         /* User might have changed the IAP name when a new IAP was saved */
         Maemo::IAPConf iap_name(icdConfig->id);
         QString name = iap_name.value("name").toString();
         if (!name.isEmpty())
             icdConfig->name = name;
         icdConfig->iap_type = rep.arguments().at(3).toString(); // connect_result.connect.network_type;
         icdConfig->bearerType = bearerTypeFromIapType(icdConfig->iap_type);
         icdConfig->isValid = true;
         icdConfig->state = QNetworkConfiguration::Active;
         icdConfig->type = QNetworkConfiguration::InternetAccessPoint;
         icdConfig->mutex.unlock();
         startTime = QDateTime::currentDateTime();
         updateState(QNetworkSession::Connected);
         //currentNetworkInterface = get_network_interface();
 #ifdef BEARER_MANAGEMENT_DEBUG
         //qDebug() << "connected to" << result << config.name() << "at" << currentNetworkInterface;
 #endif
         /* We first check if the configuration already exists in the manager
          * and if it is not found there, we then insert it. Note that this
          * is only done for user choice config only because it can be missing
          * from config manager list.
          */
         if (publicConfig.type() == QNetworkConfiguration::UserChoice) {
             if (!engine->hasIdentifier(result)) {
                 engine->addSessionConfiguration(privateConfiguration(config));
             } else {
                 QNetworkConfigurationPrivatePointer priv = engine->configuration(result);
                 QNetworkConfiguration reference;
                 setPrivateConfiguration(reference, priv);
                 copyConfig(config, reference, false);
                 privateConfiguration(reference)->id = result; // Note: Id was not copied in copyConfig() function
                 config = reference;
                 activeConfig = reference;
                 engine->changedSessionConfiguration(privateConfiguration(config));
 #ifdef BEARER_MANAGEMENT_DEBUG
                 qDebug()<<"Existing configuration"<<result<<"updated in manager in open";
 #endif
             }
         }
         emit quitPendingWaitsForOpened();
     }
 }
stop() [1/2]
void QNetworkSessionPrivateImpl::stop () virtual
Implements QNetworkSessionPrivate.
stop() [2/2]
void QNetworkSessionPrivateImpl::stop () virtual
Implements QNetworkSessionPrivate.
Definition at line 923 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     if (m_connectRequestTimer.isActive())
         m_connectRequestTimer.stop();
     if (serviceConfig.isValid()) {
         lastError = QNetworkSession::OperationNotSupportedError;
         emit QNetworkSessionPrivate::error(lastError);
     } else {
         if ((activeConfig.state() & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "stopping session" << publicConfig.identifier();
 #endif
         state = QNetworkSession::Closing;
         emit stateChanged(state);
         // we fake a disconnection, a session error is sent also
         updateState(QNetworkSession::Disconnected);
         opened = false;
         isOpen = false;
         m_dbusInterface->call(ICD_DBUS_API_DISCONNECT_REQ, ICD_CONNECTION_FLAG_APPLICATION_EVENT);
         startTime = QDateTime();
         } else {
         opened = false;
         isOpen = false;
         emit closed();
     }
     }
 }
syncStateWithInterface() [1/2]
void QNetworkSessionPrivateImpl::syncStateWithInterface () virtual
Implements QNetworkSessionPrivate.
syncStateWithInterface() [2/2]
void QNetworkSessionPrivateImpl::syncStateWithInterface () virtual
Implements QNetworkSessionPrivate.
Definition at line 350 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), and ~QNetworkSessionPrivateImpl().
 {
     /* Initially we are not active although the configuration might be in
      * connected state.
      */
     isOpen = false;
     opened = false;
     connect(engine, SIGNAL(iapStateChanged(const QString&, uint)),
             this, SLOT(iapStateChanged(const QString&, uint)));
     QObject::connect(q, SIGNAL(stateChanged(QNetworkSession::State)), this, SLOT(updateProxies(QNetworkSession::State)));
     state = QNetworkSession::Invalid;
     lastError = QNetworkSession::UnknownSessionError;
     switch (publicConfig.type()) {
     case QNetworkConfiguration::InternetAccessPoint:
         activeConfig = publicConfig;
         break;
     case QNetworkConfiguration::ServiceNetwork:
         serviceConfig = publicConfig;
     break;
     case QNetworkConfiguration::UserChoice:
     // active config will contain correct data after open() has succeeded
         copyConfig(publicConfig, activeConfig);
     /* We create new configuration that holds the actual configuration
      * returned by icd. This way publicConfig still contains the
      * original user specified configuration.
      *
      * Note that the new activeConfig configuration is not inserted
      * to configurationManager as manager class will get the newly
      * connected configuration from gconf when the IAP is saved.
      * This configuration manager update is done by IapMonitor class.
      * If the ANY connection fails in open(), then the configuration
      * data is not saved to gconf and will not be added to
      * configuration manager IAP list.
      */
 #ifdef BEARER_MANAGEMENT_DEBUG
     qDebug()<<"New configuration created for" << publicConfig.identifier();
 #endif
     break;
     default:
     /* Invalid configuration, no point continuing */
     return;
     }
     if (!activeConfig.isValid())
     return;
     /* Get the initial state from icd */
     Maemo::Icd icd;
     QList<Maemo::IcdStateResult> state_results;
     /* Update the active config from first connection, this is ok as icd
      * supports only one connection anyway.
      */
     if (icd.state(state_results) && !state_results.isEmpty()) {
     /* If we did not get full state back, then we are not
      * connected and can skip the next part.
      */
     if (!(state_results.first().params.network_attrs == 0 &&
         state_results.first().params.network_id.isEmpty())) {
         /* If we try to connect to specific IAP and we get results back
          * that tell the icd is actually connected to another IAP,
          * then do not update current state etc.
          */
         if (publicConfig.type() == QNetworkConfiguration::UserChoice ||
             publicConfig.identifier() == state_results.first().params.network_id) {
         switch (state_results.first().state) {
         case ICD_STATE_DISCONNECTED:
             state = QNetworkSession::Disconnected;
             if (QNetworkConfigurationPrivatePointer ptr = privateConfiguration(activeConfig)) {
                 ptr->mutex.lock();
                 ptr->isValid = true;
                 ptr->mutex.unlock();
             }
             break;
         case ICD_STATE_CONNECTING:
             state = QNetworkSession::Connecting;
             if (QNetworkConfigurationPrivatePointer ptr = privateConfiguration(activeConfig)) {
                 ptr->mutex.lock();
                 ptr->isValid = true;
                 ptr->mutex.unlock();
             }
             break;
         case ICD_STATE_CONNECTED:
         {
             if (!state_results.first().error.isEmpty())
                 break;
             const QString id = state_results.first().params.network_id;
             QNetworkConfiguration config = manager.configurationFromIdentifier(id);
             if (config.isValid()) {
                 //we don't want the copied data if the config is already known by the manager
                 //just reuse it so that existing references to the old data get the same update
                 setPrivateConfiguration(activeConfig, privateConfiguration(config));
             }
             QNetworkConfigurationPrivatePointer ptr = privateConfiguration(activeConfig);
             QMutexLocker configLocker(&ptr->mutex);
             state = QNetworkSession::Connected;
             toIcdConfig(ptr)->network_id = state_results.first().params.network_id;
             ptr->id = toIcdConfig(ptr)->network_id;
             toIcdConfig(ptr)->network_attrs = state_results.first().params.network_attrs;
             toIcdConfig(ptr)->iap_type = state_results.first().params.network_type;
             ptr->bearerType = bearerTypeFromIapType(toIcdConfig(ptr)->iap_type);
             toIcdConfig(ptr)->service_type = state_results.first().params.service_type;
             toIcdConfig(ptr)->service_id = state_results.first().params.service_id;
             toIcdConfig(ptr)->service_attrs = state_results.first().params.service_attrs;
             ptr->type = QNetworkConfiguration::InternetAccessPoint;
             ptr->state = QNetworkConfiguration::Active;
             ptr->isValid = true;
             currentNetworkInterface = get_network_interface();
             Maemo::IAPConf iap_name(ptr->id);
             QString name_value = iap_name.value("name").toString();
             if (!name_value.isEmpty())
                 ptr->name = name_value;
             else
                 ptr->name = ptr->id;
             const QString identifier = ptr->id;
             configLocker.unlock();
             // Add the new active configuration to manager or update the old config
             if (!engine->hasIdentifier(identifier))
                 engine->addSessionConfiguration(ptr);
             else
                 engine->changedSessionConfiguration(ptr);
         }
         break;
         case ICD_STATE_DISCONNECTING:
             state = QNetworkSession::Closing;
             if (QNetworkConfigurationPrivatePointer ptr = privateConfiguration(activeConfig)) {
                 ptr->mutex.lock();
                 ptr->isValid = true;
                 ptr->mutex.unlock();
             }
             break;
         default:
             break;
         }
     }
     } else {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "status_req tells icd is not connected";
 #endif
     }
     } else {
 #ifdef BEARER_MANAGEMENT_DEBUG
     qDebug() << "status_req did not return any results from icd";
 #endif
     }
     networkConfigurationsChanged();
 }
updateIdentifier()
void QNetworkSessionPrivateImpl::updateIdentifier (const QString & newId) private
Definition at line 231 of file qnetworksession_impl.cpp.
Referenced by iapStateChanged().
 {
     if (publicConfig.type() == QNetworkConfiguration::UserChoice) {
         IcdNetworkConfigurationPrivate *icdConfig =
             toIcdConfig(privateConfiguration(activeConfig));
         icdConfig->mutex.lock();
         icdConfig->network_attrs |= ICD_NW_ATTR_IAPNAME;
         icdConfig->id = newId;
         icdConfig->mutex.unlock();
     } else {
         IcdNetworkConfigurationPrivate *icdConfig =
             toIcdConfig(privateConfiguration(publicConfig));
         icdConfig->mutex.lock();
         icdConfig->network_attrs |= ICD_NW_ATTR_IAPNAME;
         if (icdConfig->id != newId)
             icdConfig->id = newId;
         icdConfig->mutex.unlock();
     }
 }
updateProxies
void QNetworkSessionPrivateImpl::updateProxies (QNetworkSession::State newState) private slot
Definition at line 1052 of file qnetworksession_impl.cpp.
Referenced by cleanupSession(), and syncStateWithInterface().
 {
     if ((newState == QNetworkSession::Connected) &&
     (newState != currentState))
     updateProxyInformation();
     else if ((newState == QNetworkSession::Disconnected) &&
         (currentState == QNetworkSession::Closing))
     clearProxyInformation();
     currentState = newState;
 }
updateProxyInformation()
void QNetworkSessionPrivateImpl::updateProxyInformation () private
Definition at line 1065 of file qnetworksession_impl.cpp.
Referenced by updateProxies().
 {
     Maemo::ProxyConf::update();
 }
updateState()
void QNetworkSessionPrivateImpl::updateState (QNetworkSession::State newState) private
Definition at line 161 of file qnetworksession_impl.cpp.
Referenced by close(), connectTimeout(), iapStateChanged(), stateChange(), and stop().
 {
     if (newState != state) {
         if (newState == QNetworkSession::Disconnected) {
             if (isOpen) {
                 // The Session was aborted by the user or system
                 lastError = QNetworkSession::SessionAbortedError;
                 emit QNetworkSessionPrivate::error(lastError);
                 emit closed();
             }
             if (m_stopTimer.isActive()) {
                 // Session was closed by calling stop()
                 m_stopTimer.stop();
             }
             isOpen = false;
             opened = false;
             currentNetworkInterface.clear();
             if (publicConfig.type() == QNetworkConfiguration::UserChoice) {
                 copyConfig(publicConfig, activeConfig);
                 IcdNetworkConfigurationPrivate *icdConfig =
                     toIcdConfig(privateConfiguration(activeConfig));
                 icdConfig->mutex.lock();
                 icdConfig->state = QNetworkConfiguration::Defined;
                 icdConfig->mutex.unlock();
                 // Reset the state of the default configuration to Discovered
                 icdConfig = toIcdConfig(privateConfiguration(publicConfig));
                 icdConfig->mutex.lock();
                 icdConfig->state = QNetworkConfiguration::Discovered;
                 icdConfig->mutex.unlock();
             } else {
                 if (!activeConfig.isValid()) {
                     // Active configuration (IAP) was removed from system
                     // => Connection was disconnected and configuration became
                     //    invalid
                     // => Also Session state must be changed to invalid
                     newState = QNetworkSession::Invalid;
                 }
             }
         } else if (newState == QNetworkSession::Connected) {
             if (opened) {
                 isOpen = true;
             }
         if (publicConfig.type() == QNetworkConfiguration::UserChoice) {
             IcdNetworkConfigurationPrivate *icdConfig =
                 toIcdConfig(privateConfiguration(activeConfig));
             icdConfig->mutex.lock();
             icdConfig->state = QNetworkConfiguration::Active;
             icdConfig->type = QNetworkConfiguration::InternetAccessPoint;
             icdConfig->mutex.unlock();
         }
         IcdNetworkConfigurationPrivate *icdConfig =
             toIcdConfig(privateConfiguration(publicConfig));
         icdConfig->mutex.lock();
         icdConfig->state = QNetworkConfiguration::Active;
         icdConfig->mutex.unlock();
     }
         if (newState != state) {
             state = newState;
             emit stateChanged(newState);
         }
     }
 }
updateStateFromActiveConfig() [1/2]
void QNetworkSessionPrivateImpl::updateStateFromActiveConfig () private
updateStateFromActiveConfig() [2/2]
void QNetworkSessionPrivateImpl::updateStateFromActiveConfig () private
Definition at line 570 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), networkConfigurationsChanged(), and ~QNetworkSessionPrivateImpl().
 {
     QNetworkSession::State oldState = state;
     bool newActive = false;
     if (!activeConfig.isValid())
         return;
     if (!activeConfig.isValid()) {
         state = QNetworkSession::Invalid;
         clearConfiguration(activeConfig);
     } else if ((activeConfig.state() & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         state = QNetworkSession::Connected;
         newActive = opened;
     } else if ((activeConfig.state() & QNetworkConfiguration::Discovered) == QNetworkConfiguration::Discovered) {
         state = QNetworkSession::Disconnected;
     } else if ((activeConfig.state() & QNetworkConfiguration::Defined) == QNetworkConfiguration::Defined) {
         state = QNetworkSession::NotAvailable;
     } else if ((activeConfig.state() & QNetworkConfiguration::Undefined) == QNetworkConfiguration::Undefined) {
         state = QNetworkSession::NotAvailable;
     }
     bool oldActive = isOpen;
     isOpen = newActive;
     if (!oldActive && isOpen)
         emit quitPendingWaitsForOpened();
     if (oldActive && !isOpen)
         emit closed();
     if (oldState != state) {
         emit stateChanged(state);
     if (state == QNetworkSession::Disconnected && oldActive) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         //qDebug()<<"session aborted error emitted for"<<activeConfig.identifier();
 #endif
         lastError = QNetworkSession::SessionAbortedError;
         emit QNetworkSessionPrivate::error(lastError);
     }
     }
 #ifdef BEARER_MANAGEMENT_DEBUG
     //qDebug()<<"oldState ="<<oldState<<" state ="<<state<<" oldActive ="<<oldActive<<" newActive ="<<newActive<<" opened ="<<opened;
 #endif
 }
updateStateFromServiceNetwork() [1/2]
void QNetworkSessionPrivateImpl::updateStateFromServiceNetwork () private
updateStateFromServiceNetwork() [2/2]
void QNetworkSessionPrivateImpl::updateStateFromServiceNetwork () private
Definition at line 525 of file qnetworksession_impl.cpp.
Referenced by QNetworkSessionManagerPrivate::forceSessionClose(), networkConfigurationsChanged(), and ~QNetworkSessionPrivateImpl().
 {
     QNetworkSession::State oldState = state;
     foreach (const QNetworkConfiguration &config, serviceConfig.children()) {
         if ((config.state() & QNetworkConfiguration::Active) != QNetworkConfiguration::Active)
             continue;
         if (activeConfig != config) {
             activeConfig = config;
             emit newConfigurationActivated();
         }
         state = QNetworkSession::Connected;
         if (state != oldState)
             emit stateChanged(state);
         return;
     }
     if (serviceConfig.children().isEmpty())
         state = QNetworkSession::NotAvailable;
     else
         state = QNetworkSession::Disconnected;
     if (state != oldState)
         emit stateChanged(state);
 }
Friends and Related Functions
IcdListener
friend class IcdListener friend
Definition at line 197 of file qnetworksession_impl.h.
Properties
config
QNetworkConfiguration QNetworkSessionPrivateImpl::config private
Definition at line 185 of file qnetworksession_impl.h.
Referenced by do_open(), stateChange(), syncStateWithInterface(), updateStateFromServiceNetwork(), and ~QNetworkSessionPrivateImpl().
connectFlags
icd_connection_flags QNetworkSessionPrivateImpl::connectFlags private
Definition at line 191 of file qnetworksession_impl.h.
Referenced by do_open(), and setSessionProperty().
currentNetworkInterface
QString QNetworkSessionPrivateImpl::currentNetworkInterface private
Definition at line 196 of file qnetworksession_impl.h.
Referenced by currentInterface(), syncStateWithInterface(), and updateState().
currentState
QNetworkSession::State QNetworkSessionPrivateImpl::currentState private
Definition at line 205 of file qnetworksession_impl.h.
Referenced by updateProxies().
engine [1/2]
QBearerEngineImpl* QNetworkSessionPrivateImpl::engine private
Definition at line 117 of file qnetworksession_impl.h.
engine [2/2]
QIcdEngine* QNetworkSessionPrivateImpl::engine private
Definition at line 176 of file qnetworksession_impl.h.
Referenced by stateChange(), and syncStateWithInterface().
lastError
QNetworkSession::SessionError QNetworkSessionPrivateImpl::lastError private
Definition at line 193 of file qnetworksession_impl.h.
Referenced by close(), open(), stop(), syncStateWithInterface(), updateState(), and updateStateFromActiveConfig().
m_asynchCallActive
bool QNetworkSessionPrivateImpl::m_asynchCallActive private
Definition at line 211 of file qnetworksession_impl.h.
Referenced by do_open(), and stateChange().
m_connectRequestTimer
QTimer QNetworkSessionPrivateImpl::m_connectRequestTimer private
Definition at line 212 of file qnetworksession_impl.h.
Referenced by close(), do_open(), stateChange(), and stop().
m_dbusInterface
QDBusInterface* QNetworkSessionPrivateImpl::m_dbusInterface private
Definition at line 207 of file qnetworksession_impl.h.
Referenced by close(), do_open(), and stop().
m_stopTimer
QTimer QNetworkSessionPrivateImpl::m_stopTimer private
Definition at line 209 of file qnetworksession_impl.h.
Referenced by open(), and updateState().
manager
QNetworkConfigurationManager QNetworkSessionPrivateImpl::manager private
Definition at line 175 of file qnetworksession_impl.h.
Referenced by syncStateWithInterface().
opened
bool QNetworkSessionPrivateImpl::opened private
Definition at line 190 of file qnetworksession_impl.h.
Referenced by close(), open(), stop(), syncStateWithInterface(), updateState(), and updateStateFromActiveConfig().
sessionTimeout
int QNetworkSessionPrivateImpl::sessionTimeout private
Definition at line 123 of file qnetworksession_impl.h.
startTime [1/2]
quint64 QNetworkSessionPrivateImpl::startTime private
Definition at line 119 of file qnetworksession_impl.h.
startTime [2/2]
QDateTime QNetworkSessionPrivateImpl::startTime private
Definition at line 195 of file qnetworksession_impl.h.
Referenced by close(), stateChange(), and stop().
The documentation for this class was generated from the following files:
/src/plugins/bearer/icd/qnetworksession_impl.h
/src/plugins/bearer/icd/qnetworksession_impl.cpp