Qt 4.8: QTriangulatingStroker Class Reference
QTriangulatingStroker Class Reference
#include <qtriangulatingstroker_p.h>
Public Functions
void process (const QVectorPath &path, const QPen &pen, const QRectF &clip)
QTriangulatingStroker ()
void setInvScale (qreal invScale)
int vertexCount () const
const float * vertices () const
Private Functions
void arcPoints (float cx, float cy, float fromX, float fromY, float toX, float toY, QVarLengthArray< float > &points)
void cubicTo (const qreal *pts)
void emitLineSegment (float x, float y, float nx, float ny)
void endCap (const qreal *pts)
void endCapOrJoinClosed (const qreal *start, const qreal *cur, bool implicitClose, bool endsAtStart)
void join (const qreal *pts)
void lineTo (const qreal *pts)
void moveTo (const qreal *pts)
void normalVector (float x1, float y1, float x2, float y2, float *nx, float *ny)
Properties
Qt::PenCapStyle m_cap_style
qreal m_cos_theta
float m_curvyness_add
float m_curvyness_mul
float m_cx
float m_cy
qreal m_inv_scale
Qt::PenJoinStyle m_join_style
qreal m_miter_limit
float m_nvx
float m_nvy
int m_roundness
qreal m_sin_theta
QDataBuffer< float > m_vertices
float m_width
Detailed Description
Definition at line 54 of file qtriangulatingstroker_p.h.
Constructors and Destructors
QTriangulatingStroker()
QTriangulatingStroker::QTriangulatingStroker () inline
Definition at line 57 of file qtriangulatingstroker_p.h.
 : m_vertices(0) {}
Functions
arcPoints()
void QTriangulatingStroker::arcPoints (float cx, float cy, float fromX, float fromY, float toX, float toY, QVarLengthArray< float > & points) private
Definition at line 426 of file qtriangulatingstroker.cpp.
Referenced by endCap(), join(), moveTo(), and setInvScale().
 {
     float dx1 = fromX - cx;
     float dy1 = fromY - cy;
     float dx2 = toX - cx;
     float dy2 = toY - cy;
     // while more than 180 degrees left:
     while (dx1 * dy2 - dx2 * dy1 < 0) {
         float tmpx = dx1 * m_cos_theta - dy1 * m_sin_theta;
         float tmpy = dx1 * m_sin_theta + dy1 * m_cos_theta;
         dx1 = tmpx;
         dy1 = tmpy;
         points.append(cx + dx1);
         points.append(cy + dy1);
     }
     // while more than 90 degrees left:
     while (dx1 * dx2 + dy1 * dy2 < 0) {
         float tmpx = dx1 * m_cos_theta - dy1 * m_sin_theta;
         float tmpy = dx1 * m_sin_theta + dy1 * m_cos_theta;
         dx1 = tmpx;
         dy1 = tmpy;
         points.append(cx + dx1);
         points.append(cy + dy1);
     }
     // while more than 0 degrees left:
     while (dx1 * dy2 - dx2 * dy1 > 0) {
         float tmpx = dx1 * m_cos_theta - dy1 * m_sin_theta;
         float tmpy = dx1 * m_sin_theta + dy1 * m_cos_theta;
         dx1 = tmpx;
         dy1 = tmpy;
         points.append(cx + dx1);
         points.append(cy + dy1);
     }
     // remove last point which was rotated beyond [toX, toY].
     if (!points.isEmpty())
         points.resize(points.size() - 2);
 }
cubicTo()
void QTriangulatingStroker::cubicTo (const qreal * pts) private
Definition at line 285 of file qtriangulatingstroker.cpp.
Referenced by process(), and setInvScale().
 {
     const QPointF *p = (const QPointF *) pts;
     QBezier bezier = QBezier::fromPoints(*(p - 1), p[0], p[1], p[2]);
     QRectF bounds = bezier.bounds();
     float rad = qMax(bounds.width(), bounds.height());
     int threshold = qMin<float>(64, (rad + m_curvyness_add) * m_curvyness_mul);
     if (threshold < 4)
         threshold = 4;
     qreal threshold_minus_1 = threshold - 1;
     float vx, vy;
     float cx = m_cx, cy = m_cy;
     float x, y;
     for (int i=1; i<threshold; ++i) {
         qreal t = qreal(i) / threshold_minus_1;
         QPointF p = bezier.pointAt(t);
         x = p.x();
         y = p.y();
         normalVector(cx, cy, x, y, &vx, &vy);
         emitLineSegment(x, y, vx, vy);
         cx = x;
         cy = y;
     }
     m_cx = cx;
     m_cy = cy;
     m_nvx = vx;
     m_nvy = vy;
 }
emitLineSegment()
void QTriangulatingStroker::emitLineSegment (float x, float y, float nx, float ny) inline private
Definition at line 140 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), endCap(), join(), lineTo(), moveTo(), and setInvScale().
 {
     m_vertices.add(x + vx);
     m_vertices.add(y + vy);
     m_vertices.add(x - vx);
     m_vertices.add(y - vy);
 }
endCap()
void QTriangulatingStroker::endCap (const qreal * pts) private
Definition at line 397 of file qtriangulatingstroker.cpp.
Referenced by endCapOrJoinClosed(), and setInvScale().
 {
     switch (m_cap_style) {
     case Qt::FlatCap:
         break;
     case Qt::SquareCap:
         emitLineSegment(m_cx + m_nvy, m_cy - m_nvx, m_nvx, m_nvy);
         break;
     case Qt::RoundCap: {
         QVarLengthArray<float> points;
         int count = m_vertices.size();
         arcPoints(m_cx, m_cy, m_vertices.at(count - 2), m_vertices.at(count - 1), m_vertices.at(count - 4), m_vertices.at(count - 3), points);
         int front = 0;
         int end = points.size() / 2;
         while (front != end) {
             m_vertices.add(points[2 * end - 2]);
             m_vertices.add(points[2 * end - 1]);
             --end;
             if (front == end)
                 break;
             m_vertices.add(points[2 * front + 0]);
             m_vertices.add(points[2 * front + 1]);
             ++front;
         }
         break; }
     default: break; // to shut gcc up...
     }
 }
endCapOrJoinClosed()
void QTriangulatingStroker::endCapOrJoinClosed (const qreal * start, const qreal * cur, bool implicitClose, bool endsAtStart) private
Definition at line 52 of file qtriangulatingstroker.cpp.
Referenced by process(), and setInvScale().
 {
     if (endsAtStart) {
         join(start + 2);
     } else if (implicitClose) {
         join(start);
         lineTo(start);
         join(start+2);
     } else {
         endCap(cur);
     }
     int count = m_vertices.size();
     // Copy the (x, y) values because QDataBuffer::add(const float& t)
     // may resize the buffer, which will leave t pointing at the
     // previous buffer's memory region if we don't copy first.
     float x = m_vertices.at(count-2);
     float y = m_vertices.at(count-1);
     m_vertices.add(x);
     m_vertices.add(y);
 }
join()
void QTriangulatingStroker::join (const qreal * pts) private
Definition at line 322 of file qtriangulatingstroker.cpp.
Referenced by endCapOrJoinClosed(), process(), and setInvScale().
 {
     // Creates a join to the next segment (m_cx, m_cy) -> (pts[0], pts[1])
     normalVector(m_cx, m_cy, pts[0], pts[1], &m_nvx, &m_nvy);
     switch (m_join_style) {
     case Qt::BevelJoin:
         break;
     case Qt::SvgMiterJoin:
     case Qt::MiterJoin: {
         // Find out on which side the join should be.
         int count = m_vertices.size();
         float prevNvx = m_vertices.at(count - 2) - m_cx;
         float prevNvy = m_vertices.at(count - 1) - m_cy;
         float xprod = prevNvx * m_nvy - prevNvy * m_nvx;
         float px, py, qx, qy;
         // If the segments are parallel, use bevel join.
         if (qFuzzyIsNull(xprod))
             break;
         // Find the corners of the previous and next segment to join.
         if (xprod < 0) {
             px = m_vertices.at(count - 2);
             py = m_vertices.at(count - 1);
             qx = m_cx - m_nvx;
             qy = m_cy - m_nvy;
         } else {
             px = m_vertices.at(count - 4);
             py = m_vertices.at(count - 3);
             qx = m_cx + m_nvx;
             qy = m_cy + m_nvy;
         }
         // Find intersection point.
         float pu = px * prevNvx + py * prevNvy;
         float qv = qx * m_nvx + qy * m_nvy;
         float ix = (m_nvy * pu - prevNvy * qv) / xprod;
         float iy = (prevNvx * qv - m_nvx * pu) / xprod;
         // Check that the distance to the intersection point is less than the miter limit.
         if ((ix - px) * (ix - px) + (iy - py) * (iy - py) <= m_miter_limit * m_miter_limit) {
             m_vertices.add(ix);
             m_vertices.add(iy);
             m_vertices.add(ix);
             m_vertices.add(iy);
         }
         // else
         // Do a plain bevel join if the miter limit is exceeded or if
         // the lines are parallel. This is not what the raster
         // engine's stroker does, but it is both faster and similar to
         // what some other graphics API's do.
         break; }
     case Qt::RoundJoin: {
         QVarLengthArray<float> points;
         int count = m_vertices.size();
         float prevNvx = m_vertices.at(count - 2) - m_cx;
         float prevNvy = m_vertices.at(count - 1) - m_cy;
         if (m_nvx * prevNvy - m_nvy * prevNvx < 0) {
             arcPoints(0, 0, m_nvx, m_nvy, -prevNvx, -prevNvy, points);
             for (int i = points.size() / 2; i > 0; --i)
                 emitLineSegment(m_cx, m_cy, points[2 * i - 2], points[2 * i - 1]);
         } else {
             arcPoints(0, 0, -prevNvx, -prevNvy, m_nvx, m_nvy, points);
             for (int i = 0; i < points.size() / 2; ++i)
                 emitLineSegment(m_cx, m_cy, points[2 * i + 0], points[2 * i + 1]);
         }
         break; }
     default: break; // gcc warn--
     }
     emitLineSegment(m_cx, m_cy, m_nvx, m_nvy);
 }
lineTo()
void QTriangulatingStroker::lineTo (const qreal * pts) inline private
Definition at line 148 of file qtriangulatingstroker_p.h.
Referenced by endCapOrJoinClosed(), process(), and setInvScale().
 {
     emitLineSegment(pts[0], pts[1], m_nvx, m_nvy);
     m_cx = pts[0];
     m_cy = pts[1];
 }
moveTo()
void QTriangulatingStroker::moveTo (const qreal * pts) private
Definition at line 226 of file qtriangulatingstroker.cpp.
Referenced by process(), and setInvScale().
 {
     m_cx = pts[0];
     m_cy = pts[1];
     float x2 = pts[2];
     float y2 = pts[3];
     normalVector(m_cx, m_cy, x2, y2, &m_nvx, &m_nvy);
     // To acheive jumps we insert zero-area tringles. This is done by
     // adding two identical points in both the end of previous strip
     // and beginning of next strip
     bool invisibleJump = m_vertices.size();
     switch (m_cap_style) {
     case Qt::FlatCap:
         if (invisibleJump) {
             m_vertices.add(m_cx + m_nvx);
             m_vertices.add(m_cy + m_nvy);
         }
         break;
     case Qt::SquareCap: {
         float sx = m_cx - m_nvy;
         float sy = m_cy + m_nvx;
         if (invisibleJump) {
             m_vertices.add(sx + m_nvx);
             m_vertices.add(sy + m_nvy);
         }
         emitLineSegment(sx, sy, m_nvx, m_nvy);
         break; }
     case Qt::RoundCap: {
         QVarLengthArray<float> points;
         arcPoints(m_cx, m_cy, m_cx + m_nvx, m_cy + m_nvy, m_cx - m_nvx, m_cy - m_nvy, points);
         m_vertices.resize(m_vertices.size() + points.size() + 2 * int(invisibleJump));
         int count = m_vertices.size();
         int front = 0;
         int end = points.size() / 2;
         while (front != end) {
             m_vertices.at(--count) = points[2 * end - 1];
             m_vertices.at(--count) = points[2 * end - 2];
             --end;
             if (front == end)
                 break;
             m_vertices.at(--count) = points[2 * front + 1];
             m_vertices.at(--count) = points[2 * front + 0];
             ++front;
         }
         if (invisibleJump) {
             m_vertices.at(count - 1) = m_vertices.at(count + 1);
             m_vertices.at(count - 2) = m_vertices.at(count + 0);
         }
         break; }
     default: break; // ssssh gcc...
     }
     emitLineSegment(m_cx, m_cy, m_nvx, m_nvy);
 }
normalVector()
void QTriangulatingStroker::normalVector (float x1, float y1, float x2, float y2, float * nx, float * ny) inline private
Definition at line 121 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), join(), moveTo(), and setInvScale().
 {
     float dx = x2 - x1;
     float dy = y2 - y1;
     float pw;
     if (dx == 0)
         pw = m_width / qAbs(dy);
     else if (dy == 0)
         pw = m_width / qAbs(dx);
     else
         pw = m_width / sqrt(dx*dx + dy*dy);
     *nx = -dy * pw;
     *ny = dx * pw;
 }
process()
void QTriangulatingStroker::process (const QVectorPath & path, const QPen & pen, const QRectF & clip)
Definition at line 76 of file qtriangulatingstroker.cpp.
Referenced by QTriangulatingStroker().
 {
     const qreal *pts = path.points();
     const QPainterPath::ElementType *types = path.elements();
     int count = path.elementCount();
     if (count < 2)
         return;
     float realWidth = qpen_widthf(pen);
     if (realWidth == 0)
         realWidth = 1;
     m_width = realWidth / 2;
     bool cosmetic = pen.isCosmetic();
     if (cosmetic) {
         m_width = m_width * m_inv_scale;
     }
     m_join_style = qpen_joinStyle(pen);
     m_cap_style = qpen_capStyle(pen);
     m_vertices.reset();
     m_miter_limit = pen.miterLimit() * qpen_widthf(pen);
     // The curvyness is based on the notion that I originally wanted
     // roughly one line segment pr 4 pixels. This may seem little, but
     // because we sample at constantly incrementing B(t) E [0<t<1], we
     // will get longer segments where the curvature is small and smaller
     // segments when the curvature is high.
     //
     // To get a rough idea of the length of each curve, I pretend that
     // the curve is a 90 degree arc, whose radius is
     // qMax(curveBounds.width, curveBounds.height). Based on this
     // logic we can estimate the length of the outline edges based on
     // the radius + a pen width and adjusting for scale factors
     // depending on if the pen is cosmetic or not.
     //
     // The curvyness value of PI/14 was based on,
     // arcLength = 2*PI*r/4 = PI*r/2 and splitting length into somewhere
     // between 3 and 8 where 5 seemed to be give pretty good results
     // hence: Q_PI/14. Lower divisors will give more detail at the
     // direct cost of performance.
     // simplfy pens that are thin in device size (2px wide or less)
     if (realWidth < 2.5 && (cosmetic || m_inv_scale == 1)) {
         if (m_cap_style == Qt::RoundCap)
             m_cap_style = Qt::SquareCap;
         if (m_join_style == Qt::RoundJoin)
             m_join_style = Qt::MiterJoin;
         m_curvyness_add = 0.5;
         m_curvyness_mul = CURVE_FLATNESS / m_inv_scale;
         m_roundness = 1;
     } else if (cosmetic) {
         m_curvyness_add = realWidth / 2;
         m_curvyness_mul = CURVE_FLATNESS;
         m_roundness = qMax<int>(4, realWidth * CURVE_FLATNESS);
     } else {
         m_curvyness_add = m_width;
         m_curvyness_mul = CURVE_FLATNESS / m_inv_scale;
         m_roundness = qMax<int>(4, realWidth * m_curvyness_mul);
     }
     // Over this level of segmentation, there doesn't seem to be any
     // benefit, even for huge penWidth
     if (m_roundness > 24)
         m_roundness = 24;
     m_sin_theta = qFastSin(Q_PI / m_roundness);
     m_cos_theta = qFastCos(Q_PI / m_roundness);
     const qreal *endPts = pts + (count<<1);
     const qreal *startPts = 0;
     Qt::PenCapStyle cap = m_cap_style;
     if (!types) {
         // skip duplicate points
         while((pts + 2) < endPts && pts[0] == pts[2] && pts[1] == pts[3])
             pts += 2;
         if ((pts + 2) == endPts)
             return;
         startPts = pts;
         bool endsAtStart = startPts[0] == *(endPts-2) && startPts[1] == *(endPts-1);
         if (endsAtStart || path.hasImplicitClose())
             m_cap_style = Qt::FlatCap;
         moveTo(pts);
         m_cap_style = cap;
         pts += 2;
         lineTo(pts);
         pts += 2;
         while (pts < endPts) {
             if (m_cx != pts[0] || m_cy != pts[1]) {
                 join(pts);
                 lineTo(pts);
             }
             pts += 2;
         }
         endCapOrJoinClosed(startPts, pts-2, path.hasImplicitClose(), endsAtStart);
     } else {
         bool endsAtStart = false;
         while (pts < endPts) {
             switch (*types) {
             case QPainterPath::MoveToElement: {
                 if (pts != path.points())
                     endCapOrJoinClosed(startPts, pts-2, path.hasImplicitClose(), endsAtStart);
                 startPts = pts;
                 int end = (endPts - pts) / 2;
                 int i = 2; // Start looking to ahead since we never have two moveto's in a row
                 while (i<end && types[i] != QPainterPath::MoveToElement) {
                     ++i;
                 }
                 endsAtStart = startPts[0] == pts[i*2 - 2] && startPts[1] == pts[i*2 - 1];
                 if (endsAtStart || path.hasImplicitClose())
                     m_cap_style = Qt::FlatCap;
                 moveTo(pts);
                 m_cap_style = cap;
                 pts+=2;
                 ++types;
                 break; }
             case QPainterPath::LineToElement:
                 if (*(types - 1) != QPainterPath::MoveToElement)
                     join(pts);
                 lineTo(pts);
                 pts+=2;
                 ++types;
                 break;
             case QPainterPath::CurveToElement:
                 if (*(types - 1) != QPainterPath::MoveToElement)
                     join(pts);
                 cubicTo(pts);
                 pts+=6;
                 types+=3;
                 break;
             default:
                 Q_ASSERT(false);
                 break;
             }
         }
         endCapOrJoinClosed(startPts, pts-2, path.hasImplicitClose(), endsAtStart);
     }
 }
setInvScale()
void QTriangulatingStroker::setInvScale (qreal invScale) inline
Definition at line 63 of file qtriangulatingstroker_p.h.
Referenced by QGL2PaintEngineExPrivate::updateMatrix().
 { m_inv_scale = invScale; }
vertexCount()
int QTriangulatingStroker::vertexCount () const inline
Definition at line 60 of file qtriangulatingstroker_p.h.
 { return m_vertices.size(); }
vertices()
const float* QTriangulatingStroker::vertices () const inline
Definition at line 61 of file qtriangulatingstroker_p.h.
 { return m_vertices.data(); }
Properties
m_cap_style
Qt::PenCapStyle QTriangulatingStroker::m_cap_style private
Definition at line 92 of file qtriangulatingstroker_p.h.
Referenced by endCap(), moveTo(), and process().
m_cos_theta
qreal QTriangulatingStroker::m_cos_theta private
Definition at line 86 of file qtriangulatingstroker_p.h.
Referenced by arcPoints(), and process().
m_curvyness_add
float QTriangulatingStroker::m_curvyness_add private
Definition at line 89 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), and process().
m_curvyness_mul
float QTriangulatingStroker::m_curvyness_mul private
Definition at line 88 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), and process().
m_cx
float QTriangulatingStroker::m_cx private
Definition at line 79 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), endCap(), join(), lineTo(), moveTo(), and process().
m_cy
float QTriangulatingStroker::m_cy private
Definition at line 79 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), endCap(), join(), lineTo(), moveTo(), and process().
m_inv_scale
qreal QTriangulatingStroker::m_inv_scale private
Definition at line 87 of file qtriangulatingstroker_p.h.
Referenced by process(), setInvScale(), and QDashedStrokeProcessor::setInvScale().
m_join_style
Qt::PenJoinStyle QTriangulatingStroker::m_join_style private
Definition at line 91 of file qtriangulatingstroker_p.h.
Referenced by join(), and process().
m_miter_limit
qreal QTriangulatingStroker::m_miter_limit private
Definition at line 82 of file qtriangulatingstroker_p.h.
Referenced by join(), and process().
m_nvx
float QTriangulatingStroker::m_nvx private
Definition at line 80 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), endCap(), join(), lineTo(), and moveTo().
m_nvy
float QTriangulatingStroker::m_nvy private
Definition at line 80 of file qtriangulatingstroker_p.h.
Referenced by cubicTo(), endCap(), join(), lineTo(), and moveTo().
m_roundness
int QTriangulatingStroker::m_roundness private
Definition at line 84 of file qtriangulatingstroker_p.h.
Referenced by process().
m_sin_theta
qreal QTriangulatingStroker::m_sin_theta private
Definition at line 85 of file qtriangulatingstroker_p.h.
Referenced by arcPoints(), and process().
m_vertices
QDataBuffer<float> QTriangulatingStroker::m_vertices private
Definition at line 77 of file qtriangulatingstroker_p.h.
Referenced by emitLineSegment(), endCap(), endCapOrJoinClosed(), join(), moveTo(), process(), vertexCount(), and vertices().
m_width
float QTriangulatingStroker::m_width private
Definition at line 81 of file qtriangulatingstroker_p.h.
Referenced by normalVector(), and process().
The documentation for this class was generated from the following files:
/src/opengl/gl2paintengineex/qtriangulatingstroker_p.h
/src/opengl/gl2paintengineex/qtriangulatingstroker.cpp