Qt 4.8: QX11GLPixmapData Class Reference
QX11GLPixmapData Class Reference
#include <qpixmapdata_x11gl_p.h>
Public Functions
void beginPaint ()
QGLContext * context () const
void copy (const QPixmapData *data, const QRect &rect)
void fill (const QColor &color)
QPaintEngine * paintEngine () const
QX11GLPixmapData ()
bool scroll (int dx, int dy, const QRect &rect)
QSize size () const
virtual ~QX11GLPixmapData ()
Public Functions inherited from QX11PixmapData
QPixmap alphaChannel () const
void convertToARGB32 (bool preserveContents=true)
QPixmapData * createCompatiblePixmapData () const
void fromImage (const QImage &image, Qt::ImageConversionFlags flags)
Qt::HANDLE handle () const
bool hasAlphaChannel () const
QBitmap mask () const
QX11PixmapData (PixelType type)
void resize (int width, int height)
void setAlphaChannel (const QPixmap &alphaChannel)
void setMask (const QBitmap &mask)
Sets a mask bitmap.
QImage toImage () const
Converts the pixmap to a QImage.
QImage toImage (const QRect &rect) const
QPixmap transformed (const QTransform &transform, Qt::TransformationMode mode) const
Returns a copy of the pixmap that is transformed using the given transformation matrix and transformation mode.
Qt::HANDLE x11ConvertToDefaultDepth ()
~QX11PixmapData ()
Public Functions inherited from QPixmapData
virtual QImage * buffer ()
qint64 cacheKey () const
ClassId classId () const
int colorCount () const
int depth () const
virtual bool fromData (const uchar *buffer, uint len, const char *format, Qt::ImageConversionFlags flags)
virtual bool fromFile (const QString &filename, const char *format, Qt::ImageConversionFlags flags)
virtual void fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags)
int height () const
bool isNull () const
QT_DEPRECATED int numColors () const
PixelType pixelType () const
QPixmapData (PixelType pixelType, int classId)
virtual QPixmapData * runtimeData () const
int serialNumber () const
int width () const
virtual ~QPixmapData ()
Public Functions inherited from QGLPaintDevice
virtual bool alphaRequested () const
int devType () const
virtual void endPaint ()
virtual void ensureActiveTarget ()
virtual QGLFormat format () const
virtual bool isFlipped () const
QGLPaintDevice ()
virtual ~QGLPaintDevice ()
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static QGLFormat glFormat ()
static bool hasX11GLPixmaps ()
static QX11GLSharedContexts * sharedContexts ()
Static Public Functions inherited from QX11PixmapData
static Qt::HANDLE createBitmapFromImage (const QImage &image)
Static Public Functions inherited from QPixmapData
static QPixmapData * create (int w, int h, PixelType type)
Static Public Functions inherited from QGLPaintDevice
static QGLPaintDevice * getDevice (QPaintDevice *)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Properties
QGLContext * ctx
Additional Inherited Members
Public Types inherited from QPixmapData
enum ClassId {
RasterClass, X11Class, MacClass, DirectFBClass,
OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
CustomClass = 1024
}
enum PixelType { PixmapType, BitmapType }
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Variables inherited from QX11PixmapData
void * gl_surface
Protected Functions inherited from QX11PixmapData
int metric (QPaintDevice::PaintDeviceMetric metric) const
Protected Functions inherited from QPixmapData
void setSerialNumber (int serNo)
Protected Functions inherited from QGLPaintDevice
int metric (QPaintDevice::PaintDeviceMetric metric) const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables inherited from QPixmapData
int d
int h
bool is_null
int w
Protected Variables inherited from QGLPaintDevice
GLuint m_previousFBO
GLuint m_thisFBO
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 70 of file qpixmapdata_x11gl_p.h.
Constructors and Destructors
QX11GLPixmapData()
QX11GLPixmapData::QX11GLPixmapData ()
Definition at line 234 of file qpixmapdata_x11gl_egl.cpp.
     : QX11PixmapData(QPixmapData::PixmapType),
       ctx(0)
 {
 }
~QX11GLPixmapData()
QX11GLPixmapData::~QX11GLPixmapData () virtual
Definition at line 240 of file qpixmapdata_x11gl_egl.cpp.
 {
     if (ctx)
         delete ctx;
 }
Functions
beginPaint()
void QX11GLPixmapData::beginPaint () virtual
Reimplemented from QGLPaintDevice.
Definition at line 365 of file qpixmapdata_x11gl_egl.cpp.
 {
 //    qDebug("QX11GLPixmapData::beginPaint()");
     // TODO: Check to see if the surface is renderable
     if ((EGLSurface)gl_surface == EGL_NO_SURFACE) {
         QPixmap tmpPixmap(this);
         EGLConfig cfg = ctx->d_func()->eglContext->config();
         Q_ASSERT(cfg != QEGL_NO_CONFIG);
 //        qDebug("QX11GLPixmapData - using EGL Config ID %d", ctx->d_func()->eglContext->configAttrib(EGL_CONFIG_ID));
         EGLSurface surface = QEgl::createSurface(&tmpPixmap, cfg);
         if (surface == EGL_NO_SURFACE) {
             qWarning() << "Error creating EGL surface for pixmap:" << QEgl::errorString();
             return;
         }
         gl_surface = (void*)surface;
         ctx->d_func()->eglSurface = surface;
         ctx->d_func()->valid = true;
     }
     QGLPaintDevice::beginPaint();
 }
context()
QGLContext * QX11GLPixmapData::context () const virtual
Implements QGLPaintDevice.
Definition at line 387 of file qpixmapdata_x11gl_egl.cpp.
 {
     return ctx;
 }
copy()
void QX11GLPixmapData::copy (const QPixmapData * data, const QRect & rect) virtual
Reimplemented from QX11PixmapData.
Definition at line 264 of file qpixmapdata_x11gl_egl.cpp.
 {
     if (ctx) {
         ctx->makeCurrent();
         glFinish();
         eglWaitClient();
     }
     QX11PixmapData::copy(data, rect);
     XSync(X11->display, False);
     if (ctx) {
         ctx->makeCurrent();
         eglWaitNative(EGL_CORE_NATIVE_ENGINE);
     }
 }
fill()
void QX11GLPixmapData::fill (const QColor & color) virtual
Reimplemented from QX11PixmapData.
Definition at line 247 of file qpixmapdata_x11gl_egl.cpp.
 {
     if (ctx) {
         ctx->makeCurrent();
         glFinish();
         eglWaitClient();
     }
     QX11PixmapData::fill(color);
     XSync(X11->display, False);
     if (ctx) {
         ctx->makeCurrent();
         eglWaitNative(EGL_CORE_NATIVE_ENGINE);
     }
 }
glFormat()
QGLFormat QX11GLPixmapData::glFormat () static
Definition at line 398 of file qpixmapdata_x11gl_egl.cpp.
Referenced by paintEngine(), and QX11GLSharedContexts::QX11GLSharedContexts().
 {
     return QGLFormat::defaultFormat(); //###
 }
hasX11GLPixmaps()
bool QX11GLPixmapData::hasX11GLPixmaps () static
Definition at line 220 of file qpixmapdata_x11gl_egl.cpp.
Referenced by QGLGraphicsSystem::createWindowSurface().
 {
     static bool checkedForX11GLPixmaps = false;
     static bool haveX11GLPixmaps = false;
     if (checkedForX11GLPixmaps)
         return haveX11GLPixmaps;
     haveX11GLPixmaps = qt_x11gl_share_contexts()->isValid();
     checkedForX11GLPixmaps = true;
     return haveX11GLPixmaps;
 }
paintEngine()
QPaintEngine * QX11GLPixmapData::paintEngine () const virtual
Reimplemented from QX11PixmapData.
Definition at line 309 of file qpixmapdata_x11gl_egl.cpp.
 {
     // We need to create the context before beginPaint - do it here:
     if (!ctx) {
         ctx = new QGLContext(glFormat());
         Q_ASSERT(ctx->d_func()->eglContext == 0);
         ctx->d_func()->eglContext = hasAlphaChannel() ? sharedContexts()->argbContext : sharedContexts()->rgbContext;
         // While we use a separate QGLContext for each pixmap, the underlying QEglContext is
         // the same. So we must use a "fake" QGLContext and fool the texture cache into thinking
         // each pixmap's QGLContext is sharing with this central one. The only place this is
         // going to fail is where we the underlying EGL RGB and ARGB contexts aren't sharing.
         ctx->d_func()->sharing = true;
         QGLContextGroup::addShare(ctx, sharedContexts()->sharedQGLContext);
         // Update the glFormat for the QGLContext:
         qt_glformat_from_eglconfig(ctx->d_func()->glFormat, ctx->d_func()->eglContext->config());
     }
     QPaintEngine* engine;
 #if defined(QT_OPENGL_ES_1)
     engine = qt_gl_pixmap_engine();
 #elif defined(QT_OPENGL_ES_2)
     engine = qt_gl_pixmap_2_engine();
 #else
     if (qt_gl_preferGL2Engine())
         engine = qt_gl_pixmap_2_engine();
     else
         engine = qt_gl_pixmap_engine();
 #endif
     // Support multiple painters on multiple pixmaps simultaniously
     if (engine->isActive()) {
         qWarning("Pixmap paint engine already active");
 #if defined(QT_OPENGL_ES_1)
         engine = new QOpenGLPaintEngine;
 #elif defined(QT_OPENGL_ES_2)
         engine = new QGL2PaintEngineEx;
 #else
         if (qt_gl_preferGL2Engine())
             engine = new QGL2PaintEngineEx;
         else
             engine = new QOpenGLPaintEngine;
 #endif
         engine->setAutoDestruct(true);
         return engine;
     }
     return engine;
 }
scroll()
bool QX11GLPixmapData::scroll (int dx, int dy, const QRect & rect) virtual
Reimplemented from QX11PixmapData.
Definition at line 281 of file qpixmapdata_x11gl_egl.cpp.
 {
     if (ctx) {
         ctx->makeCurrent();
         glFinish();
         eglWaitClient();
     }
     bool success = QX11PixmapData::scroll(dx, dy, rect);
     XSync(X11->display, False);
     if (ctx) {
         ctx->makeCurrent();
         eglWaitNative(EGL_CORE_NATIVE_ENGINE);
     }
     return success;
 }
sharedContexts()
QX11GLSharedContexts * QX11GLPixmapData::sharedContexts () static
Definition at line 215 of file qpixmapdata_x11gl_egl.cpp.
Referenced by paintEngine().
 {
     return qt_x11gl_share_contexts();
 }
size()
QSize QX11GLPixmapData::size () const virtual
Implements QGLPaintDevice.
Definition at line 392 of file qpixmapdata_x11gl_egl.cpp.
 {
     return QSize(w, h);
 }
Properties
ctx
QGLContext* QX11GLPixmapData::ctx mutable private
Definition at line 92 of file qpixmapdata_x11gl_p.h.
Referenced by beginPaint(), context(), copy(), fill(), paintEngine(), scroll(), and ~QX11GLPixmapData().
The documentation for this class was generated from the following files:
/src/opengl/qpixmapdata_x11gl_p.h
/src/opengl/qpixmapdata_x11gl_egl.cpp