Qt 4.8: QMenuBar Class Reference
QMenuBar Class Reference
The QMenuBar class provides a horizontal menu bar.
#include <qmenubar.h>
Public Slots
virtual void setVisible (bool visible)
Reimplemented Function
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void hovered (QAction *action)
This signal is emitted when a menu action is highlighted; action is the action that caused the event to be sent.
void triggered (QAction *action)
This signal is emitted when an action in a menu belonging to this menubar is triggered as a result of a mouse click; action is the action that caused the signal to be emitted.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QAction * actionAt (const QPoint &) const
Returns the QAction at pt.
QRect actionGeometry (QAction *) const
Returns the geometry of action act as a QRect.
QAction * activeAction () const
Returns the QAction that is currently highlighted.
QAction * addAction (const QString &text)
This convenience function creates a new action with text.
QAction * addAction (const QString &text, const QObject *receiver, const char *member)
This convenience function creates a new action with the given text.
QAction * addMenu (QMenu *menu)
Appends menu to the menu bar.
QMenu * addMenu (const QString &title)
Appends a new QMenu with title to the menu bar.
QMenu * addMenu (const QIcon &icon, const QString &title)
Appends a new QMenu with icon and title to the menu bar.
QAction * addSeparator ()
Appends a separator to the menu.
void clear ()
Removes all the actions from the menu bar.
QWidget * cornerWidget (Qt::Corner corner=Qt::TopRightCorner) const
Returns the widget on the left of the first or on the right of the last menu item, depending on corner.
QAction * defaultAction () const
Returns the current default action.
int heightForWidth (int) const
Reimplemented Function
QAction * insertMenu (QAction *before, QMenu *menu)
This convenience function inserts menu before action before and returns the menus menuAction().
QAction * insertSeparator (QAction *before)
This convenience function creates a new separator action, i.e.
bool isDefaultUp () const
bool isNativeMenuBar () const
OSMenuRef macMenu ()
QSize minimumSizeHint () const
Reimplemented Function
QMenuBar (QWidget *parent=0)
Constructs a menu bar with parent parent.
void setActiveAction (QAction *action)
Sets the currently highlighted action to act.
void setCornerWidget (QWidget *w, Qt::Corner corner=Qt::TopRightCorner)
This sets the given widget to be shown directly on the left of the first menu item, or on the right of the last menu item, depending on corner.
void setDefaultAction (QAction *)
Sets the default action to act.
void setDefaultUp (bool)
void setNativeMenuBar (bool nativeMenuBar)
QSize sizeHint () const
Reimplemented Function
~QMenuBar ()
Destroys the menu bar.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static bool macUpdateMenuBar ()
static void wceCommands (uint command)
This function sends native Windows CE commands to Qt menu bars and all their child menus.
static void wceRefresh ()
This function refreshes the native Windows CE menu.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
void actionEvent (QActionEvent *)
Reimplemented Function
void changeEvent (QEvent *)
Reimplemented Function
bool event (QEvent *)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
void focusInEvent (QFocusEvent *)
Reimplemented Function
void focusOutEvent (QFocusEvent *)
Reimplemented Function
void initStyleOption (QStyleOptionMenuItem *option, const QAction *action) const
Initialize option with the values from the menu bar and information from action.
void keyPressEvent (QKeyEvent *)
Reimplemented Function
void leaveEvent (QEvent *)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *)
Reimplemented Function
void mousePressEvent (QMouseEvent *)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *)
Reimplemented Function
void paintEvent (QPaintEvent *)
Reimplemented Function
void resizeEvent (QResizeEvent *)
Reimplemented Function
void timerEvent (QTimerEvent *)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool defaultUp
the popup orientation
bool nativeMenuBar
Whether or not a menubar will be used as a native menubar on platforms that support it.
Friends
class QApplicationPrivate
class QMenu
class QMenuPrivate
bool qt_mac_activate_action (MenuRef, uint, QAction::ActionEvent, bool)
class QWidgetPrivate
class QWindowsStyle
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QMenuBar class provides a horizontal menu bar.
A menu bar consists of a list of pull-down menu items. You add menu items with addMenu(). For example, asuming that menubar is a pointer to a QMenuBar and fileMenu is a pointer to a QMenu, the following statement inserts the menu into the menu bar:
menubar->addMenu(fileMenu);
The ampersand in the menu item's text sets Alt+F as a shortcut for this menu. (You can use "\&\&" to get a real ampersand in the menu bar.)
There is no need to lay out a menu bar. It automatically sets its own geometry to the top of the parent widget and changes it appropriately whenever the parent is resized.
Usage
In most main window style applications you would use the QMainWindow::menuBar() function provided in QMainWindow, adding QMenu to the menu bar and adding QAction to the pop-up menus.
Example (from the Menus example):
    fileMenu = menuBar()->addMenu(tr("&File"));
    fileMenu->addAction(newAct);
Menu items may be removed with removeAction().
Widgets can be added to menus by using instances of the QWidgetAction class to hold them. These actions can then be inserted into menus in the usual way; see the QMenu documentation for more details.
Platform Dependent Look and Feel
Different platforms have different requirements for the appearance of menu bars and their behavior when the user interacts with them. For example, Windows systems are often configured so that the underlined character mnemonics that indicate keyboard shortcuts for items in the menu bar are only shown when the Alt key is pressed.
A menu bar shown in the
Plastique widget style.
The Plastique widget style, like most other styles, handles the Help menu in the same way as it handles any other menu.
A menu bar shown in the
Motif widget style.
The Motif widget style treats Help menus in a special way, placing them at right-hand end of the menu bar.
QMenuBar on Mac OS X
QMenuBar on Mac OS X is a wrapper for using the system-wide menu bar. If you have multiple menu bars in one dialog the outermost menu bar (normally inside a widget with widget flag Qt::Window) will be used for the system-wide menu bar.
Qt for Mac OS X also provides a menu bar merging feature to make QMenuBar conform more closely to accepted Mac OS X menu bar layout. The merging functionality is based on string matching the title of a QMenu entry. These strings are translated (using QObject::tr()) in the "QMenuBar" context. If an entry is moved its slots will still fire as if it was in the original place. The table below outlines the strings looked for and where the entry is placed if matched:
String matches Placement Notes
about.* Application Menu | About <application name>=""> The application name is fetched from the {Info.plist} file (see note below). If this entry is not found no About item will appear in the Application Menu.
config, options, setup, settings or preferences Application Menu | Preferences If this entry is not found the Settings item will be disabled
quit or exit Application Menu | Quit <application name>=""> If this entry is not found a default Quit item will be created to call QApplication::quit()
You can override this behavior by using the QAction::menuRole() property.
If you want all windows in a Mac application to share one menu bar, you must create a menu bar that does not have a parent. Create a parent-less menu bar this way:
QMenuBar *menuBar = new QMenuBar(0);
Note: Do not call QMainWindow::menuBar() to create the shared menu bar, because that menu bar will have the QMainWindow as its parent. That menu bar would only be displayed for the parent QMainWindow.
Note: The text used for the application name in the menu bar is obtained from the value set in the Info.plist file in the application's bundle. See Deploying an Application on Mac OS X for more information.
QMenuBar on Windows CE
QMenuBar on Windows CE is a wrapper for using the system-wide menu bar, similar to the Mac. This feature is activated for Windows Mobile and integrates QMenuBar with the native soft keys. The left soft key can be controlled with QMenuBar::setDefaultAction() and the right soft key can be used to access the menu bar.
The hovered() signal is not supported for the native menu integration. Also, it is not possible to display an icon in a native menu on Windows Mobile.
Examples
The Menus example shows how to use QMenuBar and QMenu. The other Main Window Examples{main window application examples} also provide menus using these classes.
See also
QMenu, QShortcut, QAction, {http://developer.apple.com/documentation/UserExperience/Conceptual/AppleHIGuidelines/XHIGIntro/XHIGIntro.html}{Introduction to Apple Human Interface Guidelines}, {fowler}{GUI Design Handbook: Menu Bar}, {Menus Example}
Definition at line 62 of file qmenubar.h.
Constructors and Destructors
QMenuBar()
QMenuBar::QMenuBar (QWidget * parent = 0) explicit
Constructs a menu bar with parent parent.
Definition at line 819 of file qmenubar.cpp.
                                   : QWidget(*new QMenuBarPrivate, parent, 0)
 {
     Q_D(QMenuBar);
     d->init();
 }
~QMenuBar()
QMenuBar::~QMenuBar ()
Destroys the menu bar.
Definition at line 841 of file qmenubar.cpp.
 {
 #ifdef Q_WS_MAC
     Q_D(QMenuBar);
     d->macDestroyMenuBar();
 #endif
 #ifdef Q_WS_WINCE
     Q_D(QMenuBar);
     if (qt_wince_is_mobile())
         d->wceDestroyMenuBar();
 #endif
 #ifdef Q_WS_S60
     Q_D(QMenuBar);
     d->symbianDestroyMenuBar();
 #endif
 #ifdef Q_WS_X11
     Q_D(QMenuBar);
     delete d->cornerWidgetToolBar;
 #endif
 }
Functions
actionAt()
QAction * QMenuBar::actionAt (const QPoint & pt) const
Returns the QAction at pt.
Returns 0 if there is no action at pt or if the location has a separator.
\sa addAction(), addSeparator()
Definition at line 1706 of file qmenubar.cpp.
 {
     Q_D(const QMenuBar);
     return d->actionAt(pt);
 }
actionEvent()
void QMenuBar::actionEvent (QActionEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1329 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     d->itemsDirty = true;
 #ifdef Q_WS_X11
     d->platformMenuBar->actionEvent(e);
 #endif
 #if defined (Q_WS_MAC) || defined(Q_OS_WINCE) || defined(Q_WS_S60)
     if (isNativeMenuBar()) {
 #ifdef Q_WS_MAC
         QMenuBarPrivate::QMacMenuBarPrivate *nativeMenuBar = d->mac_menubar;
 #elif defined(Q_WS_S60)
         QMenuBarPrivate::QSymbianMenuBarPrivate *nativeMenuBar = d->symbian_menubar;
 #else
         QMenuBarPrivate::QWceMenuBarPrivate *nativeMenuBar = d->wce_menubar;
 #endif
         if (!nativeMenuBar)
             return;
         if(e->type() == QEvent::ActionAdded)
             nativeMenuBar->addAction(e->action(), e->before());
         else if(e->type() == QEvent::ActionRemoved)
             nativeMenuBar->removeAction(e->action());
         else if(e->type() == QEvent::ActionChanged)
             nativeMenuBar->syncAction(e->action());
     }
 #endif
     if(e->type() == QEvent::ActionAdded) {
         connect(e->action(), SIGNAL(triggered()), this, SLOT(_q_actionTriggered()));
         connect(e->action(), SIGNAL(hovered()), this, SLOT(_q_actionHovered()));
     } else if(e->type() == QEvent::ActionRemoved) {
         e->action()->disconnect(this);
     }
     if (isVisible()) {
         d->updateGeometries();
         update();
     }
 }
actionGeometry()
QRect QMenuBar::actionGeometry (QAction * act) const
Returns the geometry of action act as a QRect.
See also
actionAt()
Definition at line 1717 of file qmenubar.cpp.
Referenced by QAccessibleMenuBar::rect().
 {
     Q_D(const QMenuBar);
     return d->actionRect(act);
 }
activeAction()
QAction * QMenuBar::activeAction () const
Returns the QAction that is currently highlighted.
A null pointer will be returned if no action is currently selected.
Definition at line 988 of file qmenubar.cpp.
Referenced by QAccessibleMenuBar::state().
 {
     Q_D(const QMenuBar);
     return d->currentAction;
 }
addAction() [1/2]
QAction * QMenuBar::addAction (const QString & text)
This convenience function creates a new action with text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The function adds the newly created action to the menu's list of actions, and returns it.
See also
QWidget::addAction(), QWidget::actions()
Definition at line 874 of file qmenubar.cpp.
Referenced by addAction(), addMenu(), addSeparator(), and defaultAction().
 {
     QAction *ret = new QAction(text, this);
     addAction(ret);
     return ret;
 }
addAction() [2/2]
QAction * QMenuBar::addAction (const QString & text, const QObject * receiver, const char * member)
This convenience function creates a new action with the given text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The action's triggered() signal is connected to the receiver's member slot. The function adds the newly created action to the menu's list of actions and returns it.
See also
QWidget::addAction(), QWidget::actions()
Definition at line 894 of file qmenubar.cpp.
 {
     QAction *ret = new QAction(text, this);
     QObject::connect(ret, SIGNAL(triggered(bool)), receiver, member);
     addAction(ret);
     return ret;
 }
addMenu() [1/3]
QAction * QMenuBar::addMenu (QMenu * menu)
Appends menu to the menu bar.
Returns the menu's menuAction().
Note
The returned QAction object can be used to hide the corresponding menu.
See also
QWidget::addAction() QMenu::menuAction()
Definition at line 937 of file qmenubar.cpp.
Referenced by QScriptEngineDebugger::standardWindow().
 {
     QAction *action = menu->menuAction();
     addAction(action);
     return action;
 }
addMenu() [2/3]
QMenu * QMenuBar::addMenu (const QString & title)
Appends a new QMenu with title to the menu bar.
The menu bar takes ownership of the menu. Returns the new menu.
See also
QWidget::addAction() QMenu::menuAction()
Definition at line 908 of file qmenubar.cpp.
 {
     QMenu *menu = new QMenu(title, this);
     addAction(menu->menuAction());
     return menu;
 }
addMenu() [3/3]
QMenu * QMenuBar::addMenu (const QIcon & icon, const QString & title)
Appends a new QMenu with icon and title to the menu bar.
The menu bar takes ownership of the menu. Returns the new menu.
See also
QWidget::addAction() QMenu::menuAction()
Definition at line 921 of file qmenubar.cpp.
 {
     QMenu *menu = new QMenu(title, this);
     menu->setIcon(icon);
     addAction(menu->menuAction());
     return menu;
 }
addSeparator()
QAction * QMenuBar::addSeparator ()
Appends a separator to the menu.
Definition at line 947 of file qmenubar.cpp.
 {
     QAction *ret = new QAction(this);
     ret->setSeparator(true);
     addAction(ret);
     return ret;
 }
changeEvent()
void QMenuBar::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1520 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if(e->type() == QEvent::StyleChange) {
         d->itemsDirty = true;
         setMouseTracking(style()->styleHint(QStyle::SH_MenuBar_MouseTracking, 0, this));
         if(parentWidget())
             resize(parentWidget()->width(), heightForWidth(parentWidget()->width()));
         d->updateGeometries();
     } else if (e->type() == QEvent::ParentChange) {
         d->handleReparent();
     } else if (e->type() == QEvent::FontChange
                || e->type() == QEvent::ApplicationFontChange) {
         d->itemsDirty = true;
         d->updateGeometries();
 #ifdef QT_SOFTKEYS_ENABLED
     } else if (e->type() == QEvent::LanguageChange) {
         if (d->menuBarAction)
             d->menuBarAction->setText(QSoftKeyManager::standardSoftKeyText(QSoftKeyManager::MenuSoftKey));
 #endif
     }
     QWidget::changeEvent(e);
 }
clear()
void QMenuBar::clear ()
Removes all the actions from the menu bar.
Note
On Mac OS X, menu items that have been merged to the system menu bar are not removed by this function. One way to handle this would be to remove the extra actions yourself. You can set the menu role on the different menus, so that you know ahead of time which menu items get merged and which do not. Then decide what to recreate or remove yourself.
See also
removeAction()
Definition at line 1021 of file qmenubar.cpp.
 {
     QList<QAction*> acts = actions();
     for(int i = 0; i < acts.size(); i++)
         removeAction(acts[i]);
 }
cornerWidget()
QWidget * QMenuBar::cornerWidget (Qt::Corner corner = Qt::TopRightCorner) const
Returns the widget on the left of the first or on the right of the last menu item, depending on corner.
Note
Using a corner other than Qt::TopRightCorner or Qt::TopLeftCorner will result in a warning.
Definition at line 2022 of file qmenubar.cpp.
Referenced by QMdi::ControlContainer::removeButtonsFromMenuBar(), QMainWindow::setMenuBar(), and QMdi::ControlContainer::showButtonsInMenuBar().
 {
     Q_D(const QMenuBar);
     QWidget *w = 0;
     switch(corner) {
     case Qt::TopLeftCorner:
         w = d->leftWidget;
         break;
     case Qt::TopRightCorner:
         w = d->rightWidget;
         break;
     default:
         qWarning("QMenuBar::cornerWidget: Only TopLeftCorner and TopRightCorner are supported");
         break;
     }
     return w;
 }
defaultAction()
QAction * QMenuBar::defaultAction () const
Returns the current default action.
Since
4.4
See also
setDefaultAction()
Definition at line 2161 of file qmenubar.cpp.
 {
     return d_func()->defaultAction;
 }
event()
bool QMenuBar::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1548 of file qmenubar.cpp.
Referenced by eventFilter().
 {
     Q_D(QMenuBar);
     switch (e->type()) {
     case QEvent::KeyPress: {
         QKeyEvent *ke = (QKeyEvent*)e;
 #if 0
         if(!d->keyboardState) { //all keypresses..
             d->setCurrentAction(0);
             return ;
         }
 #endif
         if(ke->key() == Qt::Key_Tab || ke->key() == Qt::Key_Backtab) {
             keyPressEvent(ke);
             return true;
         }
     } break;
 #ifndef QT_NO_SHORTCUT
     case QEvent::Shortcut: {
         QShortcutEvent *se = static_cast<QShortcutEvent *>(e);
         int shortcutId = se->shortcutId();
         for(int j = 0; j < d->shortcutIndexMap.size(); ++j) {
             if (shortcutId == d->shortcutIndexMap.value(j))
                 d->_q_internalShortcutActivated(j);
         }
     } break;
 #endif
     case QEvent::Show:
 #ifdef QT3_SUPPORT
         if(QWidget *p = parentWidget()) {
             // If itemsDirty == true, updateGeometries sends the MenubarUpdated event.
             if (!d->itemsDirty) {
                 QMenubarUpdatedEvent menubarUpdated(this);
                 QApplication::sendEvent(p, &menubarUpdated);
             }
         }
 #endif
         d->_q_updateLayout();
     break;
     case QEvent::ShortcutOverride: {
         QKeyEvent *kev = static_cast<QKeyEvent*>(e);
         //we only filter out escape if there is a current action
         if (kev->key() == Qt::Key_Escape && d->currentAction) {
             e->accept();
             return true;
         }
     }
     break;
 #ifdef QT3_SUPPORT
     case QEvent::Hide: {
         if(QWidget *p = parentWidget()) {
             QMenubarUpdatedEvent menubarUpdated(this);
             QApplication::sendEvent(p, &menubarUpdated);
         }
     } break;
 #endif
 #ifndef QT_NO_WHATSTHIS
     case QEvent::QueryWhatsThis:
         e->setAccepted(d->whatsThis.size());
         if (QAction *action = d->actionAt(static_cast<QHelpEvent*>(e)->pos())) {
             if (action->whatsThis().size() || action->menu())
                 e->accept();
         }
         return true;
 #endif
     case QEvent::LayoutDirectionChange:
         d->_q_updateLayout();
         break;
     default:
         break;
     }
     return QWidget::event(e);
 }
eventFilter()
bool QMenuBar::eventFilter (QObject * object, QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1628 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
 #ifdef Q_WS_X11
     if (d->platformMenuBar->menuBarEventFilter(object, event)) {
         return true;
     }
 #endif
     if (object == parent() && object) {
 #ifdef QT3_SUPPORT
         if (d->doAutoResize && event->type() == QEvent::Resize) {
             QResizeEvent *e = (QResizeEvent *)event;
             int w = e->size().width();
             setGeometry(0, y(), w, heightForWidth(w));
             return false;
         }
 #endif
         if (event->type() == QEvent::ParentChange) //GrandparentChange
             d->handleReparent();
     }
     if (object == d->leftWidget || object == d->rightWidget) {
         switch (event->type()) {
         case QEvent::ShowToParent:
         case QEvent::HideToParent:
             d->_q_updateLayout();
             break;
         default:
             break;
         }
     }
     if (style()->styleHint(QStyle::SH_MenuBar_AltKeyNavigation, 0, this)) {
         if (d->altPressed) {
             switch (event->type()) {
             case QEvent::KeyPress:
             case QEvent::KeyRelease:
             {
                 QKeyEvent *kev = static_cast<QKeyEvent*>(event);
                 if (kev->key() == Qt::Key_Alt || kev->key() == Qt::Key_Meta) {
                     if (event->type() == QEvent::KeyPress) // Alt-press does not interest us, we have the shortcut-override event
                         break;
                     d->setKeyboardMode(!d->keyboardState);
                 }
             }
             // fall through
             case QEvent::MouseButtonPress:
             case QEvent::MouseButtonRelease:
             case QEvent::MouseMove:
             case QEvent::FocusIn:
             case QEvent::FocusOut:
             case QEvent::ActivationChange:
                 d->altPressed = false;
                 qApp->removeEventFilter(this);
                 break;
             default:
                 break;
             }
         } else if (isVisible()) {
             if (event->type() == QEvent::ShortcutOverride) {
                 QKeyEvent *kev = static_cast<QKeyEvent*>(event);
                 if ((kev->key() == Qt::Key_Alt || kev->key() == Qt::Key_Meta)
                     && kev->modifiers() == Qt::AltModifier) {
                     d->altPressed = true;
                     qApp->installEventFilter(this);
                 }
             }
         }
     }
     return false;
 }
focusInEvent()
void QMenuBar::focusInEvent (QFocusEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1371 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if(d->keyboardState)
         d->focusFirstAction();
 }
focusOutEvent()
void QMenuBar::focusOutEvent (QFocusEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1381 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if(!d->popupState) {
         d->setCurrentAction(0);
         d->setKeyboardMode(false);
     }
 }
heightForWidth()
int QMenuBar::heightForWidth (int) const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1853 of file qmenubar.cpp.
Referenced by changeEvent(), and eventFilter().
 {
     Q_D(const QMenuBar);
 #if defined(Q_WS_MAC) || defined(Q_WS_WINCE) || defined(Q_WS_S60) || defined(Q_WS_X11)
     const bool as_gui_menubar = !isNativeMenuBar();
 #else
     const bool as_gui_menubar = true;
 #endif
     const_cast<QMenuBarPrivate*>(d)->updateGeometries();
     int height = 0;
     const int vmargin = style()->pixelMetric(QStyle::PM_MenuBarVMargin, 0, this);
     int fw = style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, this);
     int spaceBelowMenuBar = style()->styleHint(QStyle::SH_MainWindow_SpaceBelowMenuBar, 0, this);
     if(as_gui_menubar) {
         for (int i = 0; i < d->actionRects.count(); ++i)
             height = qMax(height, d->actionRects.at(i).height());
         if (height) //there is at least one non-null item
             height += spaceBelowMenuBar;
         height += 2*fw;
         height += 2*vmargin;
     }
     int margin = 2*vmargin + 2*fw + spaceBelowMenuBar;
 #ifdef Q_WS_X11
     if(d->platformMenuBar->allowCornerWidgets()) {
 #endif
     if(d->leftWidget)
         height = qMax(d->leftWidget->sizeHint().height() + margin, height);
     if(d->rightWidget)
         height = qMax(d->rightWidget->sizeHint().height() + margin, height);
 #ifdef Q_WS_X11
     }
 #endif
     if(as_gui_menubar) {
         QStyleOptionMenuItem opt;
         opt.init(this);
         opt.menuRect = rect();
         opt.state = QStyle::State_None;
         opt.menuItemType = QStyleOptionMenuItem::Normal;
         opt.checkType = QStyleOptionMenuItem::NotCheckable;
         return style()->sizeFromContents(QStyle::CT_MenuBar, &opt, QSize(0, height), this).height(); //not pretty..
     }
     return height;
 }
hovered
void QMenuBar::hovered (QAction * action) signal
This signal is emitted when a menu action is highlighted; action is the action that caused the event to be sent.
Often this is used to update status information.
See also
triggered(), QAction::hovered()
Referenced by actionEvent(), QMenuPrivate::activateCausedStack(), and qt_mac_activate_action().
initStyleOption()
void QMenuBar::initStyleOption (QStyleOptionMenuItem * option, const QAction * action) const protected
Initialize option with the values from the menu bar and information from action.
This method is useful for subclasses when they need a QStyleOptionMenuItem, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom() QMenu::initStyleOption()
Definition at line 583 of file qmenubar.cpp.
Referenced by paintEvent().
 {
     if (!option || !action)
         return;
     Q_D(const QMenuBar);
     option->palette = palette();
     option->state = QStyle::State_None;
     if (isEnabled() && action->isEnabled())
         option->state |= QStyle::State_Enabled;
     else
         option->palette.setCurrentColorGroup(QPalette::Disabled);
     option->fontMetrics = fontMetrics();
     if (d->currentAction && d->currentAction == action) {
         option->state |= QStyle::State_Selected;
         if (d->popupState && !d->closePopupMode)
             option->state |= QStyle::State_Sunken;
     }
     if (hasFocus() || d->currentAction)
         option->state |= QStyle::State_HasFocus;
     option->menuRect = rect();
     option->menuItemType = QStyleOptionMenuItem::Normal;
     option->checkType = QStyleOptionMenuItem::NotCheckable;
     option->text = action->text();
     option->icon = action->icon();
 }
insertMenu()
QAction * QMenuBar::insertMenu (QAction * before, QMenu * menu)
This convenience function inserts menu before action before and returns the menus menuAction().
See also
QWidget::insertAction() addMenu()
Definition at line 977 of file qmenubar.cpp.
 {
     QAction *action = menu->menuAction();
     insertAction(before, action);
     return action;
 }
insertSeparator()
QAction * QMenuBar::insertSeparator (QAction * before)
This convenience function creates a new separator action, i.e.
an action with QAction::isSeparator() returning true. The function inserts the newly created action into this menu bar's list of actions before action before and returns it.
See also
QWidget::insertAction(), addSeparator()
Definition at line 963 of file qmenubar.cpp.
Referenced by defaultAction().
 {
     QAction *action = new QAction(this);
     action->setSeparator(true);
     insertAction(before, action);
     return action;
 }
isDefaultUp()
bool QMenuBar::isDefaultUp () const
Definition at line 1049 of file qmenubar.cpp.
 {
     Q_D(const QMenuBar);
     return !d->defaultPopDown;
 }
isNativeMenuBar()
bool QMenuBar::isNativeMenuBar () const
Definition at line 2095 of file qmenubar.cpp.
Referenced by actionEvent(), heightForWidth(), QMenuBarPrivate::macUpdateMenuBarImmediatly(), minimumSizeHint(), setVisible(), and sizeHint().
 {
     Q_D(const QMenuBar);
 #ifdef Q_WS_X11
     return d->platformMenuBar->isNativeMenuBar();
 #else
     if (d->nativeMenuBar == -1) {
         return !QApplication::instance()->testAttribute(Qt::AA_DontUseNativeMenuBar);
     }
     return d->nativeMenuBar;
 #endif
 }
keyPressEvent()
void QMenuBar::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1199 of file qmenubar.cpp.
Referenced by event().
 {
     Q_D(QMenuBar);
     d->updateGeometries();
     int key = e->key();
     if(isRightToLeft()) {  // in reverse mode open/close key for submenues are reversed
         if(key == Qt::Key_Left)
             key = Qt::Key_Right;
         else if(key == Qt::Key_Right)
             key = Qt::Key_Left;
     }
     if(key == Qt::Key_Tab) //means right
         key = Qt::Key_Right;
     else if(key == Qt::Key_Backtab) //means left
         key = Qt::Key_Left;
     bool key_consumed = false;
     switch(key) {
     case Qt::Key_Up:
     case Qt::Key_Down:
     case Qt::Key_Enter:
     case Qt::Key_Space:
     case Qt::Key_Return: {
         if(!style()->styleHint(QStyle::SH_MenuBar_AltKeyNavigation, 0, this) || !d->currentAction)
            break;
         if(d->currentAction->menu()) {
             d->popupAction(d->currentAction, true);
         } else if(key == Qt::Key_Enter || key == Qt::Key_Return || key == Qt::Key_Space) {
             d->activateAction(d->currentAction, QAction::Trigger);
             d->setCurrentAction(d->currentAction, false);
             d->setKeyboardMode(false);
         }
         key_consumed = true;
         break; }
     case Qt::Key_Right:
     case Qt::Key_Left: {
         if(d->currentAction) {
             int index = d->actions.indexOf(d->currentAction);
             if (QAction *nextAction = d->getNextAction(index, key == Qt::Key_Left ? -1 : +1)) {
                 d->setCurrentAction(nextAction, d->popupState, true);
                 key_consumed = true;
             }
         }
         break; }
     case Qt::Key_Escape:
         d->setCurrentAction(0);
         d->setKeyboardMode(false);
         key_consumed = true;
         break;
     default:
         key_consumed = false;
     }
     if(!key_consumed &&
        (!e->modifiers() ||
         (e->modifiers()&(Qt::MetaModifier|Qt::AltModifier))) && e->text().length()==1 && !d->popupState) {
         int clashCount = 0;
         QAction *first = 0, *currentSelected = 0, *firstAfterCurrent = 0;
         {
             QChar c = e->text()[0].toUpper();
             for(int i = 0; i < d->actions.size(); ++i) {
                 if (d->actionRects.at(i).isNull())
                     continue;
                 QAction *act = d->actions.at(i);
                 QString s = act->text();
                 if(!s.isEmpty()) {
                     int ampersand = s.indexOf(QLatin1Char('&'));
                     if(ampersand >= 0) {
                         if(s[ampersand+1].toUpper() == c) {
                             clashCount++;
                             if(!first)
                                 first = act;
                             if(act == d->currentAction)
                                 currentSelected = act;
                             else if (!firstAfterCurrent && currentSelected)
                                 firstAfterCurrent = act;
                         }
                     }
                 }
             }
         }
         QAction *next_action = 0;
         if(clashCount >= 1) {
             if(clashCount == 1 || !d->currentAction || (currentSelected && !firstAfterCurrent))
                 next_action = first;
             else
                 next_action = firstAfterCurrent;
         }
         if(next_action) {
             key_consumed = true;
             d->setCurrentAction(next_action, true, true);
         }
     }
     if(key_consumed)
         e->accept();
     else
         e->ignore();
 }
leaveEvent()
void QMenuBar::leaveEvent (QEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1318 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if((!hasFocus() && !d->popupState) ||
         (d->currentAction && d->currentAction->menu() == 0))
         d->setCurrentAction(0);
 }
macMenu()
OSMenuRef QMenuBar::macMenu ()
Warning
This function is not part of the public interface.
This function will return the OSMenuRef used to create the native menu bar bindings. This OSMenuRef is then set as the root menu for the Menu Manager.
Warning
This function is not portable.
See also
QMenu::macMenu()
Definition at line 1903 of file qmenu_mac.mm.
Referenced by QMenuBarPrivate::macUpdateMenuBarImmediatly().
 { return d_func()->macMenu(); }
macUpdateMenuBar()
bool QMenuBar::macUpdateMenuBar () static
Warning
This function is not part of the public interface.
This function will update the current menu bar and set it as the active menu bar in the Menu Manager.
Warning
This function is not portable.
See also
QMenu::macMenu(), QMenuBar::macMenu()
Definition at line 2055 of file qmenu_mac.mm.
Referenced by QApplicationPrivate::globalEventProcessor(), make_win_eventUPP(), onApplicationChangedActivation(), onApplicationWindowChangedActivation(), qt_event_request_menubarupdate(), and setNativeMenuBar().
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     qt_cocoaPostMessage(getMenuLoader(), @selector(qtUpdateMenubar));
     return true;
 #else
     return QMenuBarPrivate::macUpdateMenuBarImmediatly();
 #endif
 }
minimumSizeHint()
QSize QMenuBar::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1726 of file qmenubar.cpp.
 {
     Q_D(const QMenuBar);
 #if defined(Q_WS_MAC) || defined(Q_WS_WINCE) || defined(Q_WS_S60) || defined(Q_WS_X11)
     const bool as_gui_menubar = !isNativeMenuBar();
 #else
     const bool as_gui_menubar = true;
 #endif
     ensurePolished();
     QSize ret(0, 0);
     const_cast<QMenuBarPrivate*>(d)->updateGeometries();
     const int hmargin = style()->pixelMetric(QStyle::PM_MenuBarHMargin, 0, this);
     const int vmargin = style()->pixelMetric(QStyle::PM_MenuBarVMargin, 0, this);
     int fw = style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, this);
     int spaceBelowMenuBar = style()->styleHint(QStyle::SH_MainWindow_SpaceBelowMenuBar, 0, this);
     if(as_gui_menubar) {
         int w = parentWidget() ? parentWidget()->width() : QApplication::desktop()->width();
         d->calcActionRects(w - (2 * fw), 0);
         for (int i = 0; ret.isNull() && i < d->actions.count(); ++i)
             ret = d->actionRects.at(i).size();
         if (!d->extension->isHidden())
             ret += QSize(d->extension->sizeHint().width(), 0);
         ret += QSize(2*fw + hmargin, 2*fw + vmargin);
     }
     int margin = 2*vmargin + 2*fw + spaceBelowMenuBar;
 #ifdef Q_WS_X11
     if (d->platformMenuBar->allowCornerWidgets()) {
 #endif
     if(d->leftWidget) {
         QSize sz = d->leftWidget->minimumSizeHint();
         ret.setWidth(ret.width() + sz.width());
         if(sz.height() + margin > ret.height())
             ret.setHeight(sz.height() + margin);
     }
     if(d->rightWidget) {
         QSize sz = d->rightWidget->minimumSizeHint();
         ret.setWidth(ret.width() + sz.width());
         if(sz.height() + margin > ret.height())
             ret.setHeight(sz.height() + margin);
     }
 #ifdef Q_WS_X11
     }
 #endif
     if(as_gui_menubar) {
         QStyleOptionMenuItem opt;
         opt.rect = rect();
         opt.menuRect = rect();
         opt.state = QStyle::State_None;
         opt.menuItemType = QStyleOptionMenuItem::Normal;
         opt.checkType = QStyleOptionMenuItem::NotCheckable;
         opt.palette = palette();
         return (style()->sizeFromContents(QStyle::CT_MenuBar, &opt,
                                          ret.expandedTo(QApplication::globalStrut()),
                                          this));
     }
     return ret;
 }
mouseMoveEvent()
void QMenuBar::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1304 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if (!(e->buttons() & Qt::LeftButton))
         d->mouseDown = false;
     bool popupState = d->popupState || d->mouseDown;
     QAction *action = d->actionAt(e->pos());
     if ((action && d->isVisible(action)) || !popupState)
         d->setCurrentAction(action, popupState);
 }
mousePressEvent()
void QMenuBar::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1143 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if(e->button() != Qt::LeftButton)
         return;
     d->mouseDown = true;
     QAction *action = d->actionAt(e->pos());
     if (!action || !d->isVisible(action)) {
         d->setCurrentAction(0);
 #ifndef QT_NO_WHATSTHIS
         if (QWhatsThis::inWhatsThisMode())
             QWhatsThis::showText(e->globalPos(), d->whatsThis, this);
 #endif
         return;
     }
     if(d->currentAction == action && d->popupState) {
         if(QMenu *menu = d->activeMenu) {
             d->activeMenu = 0;
             menu->hide();
         }
 #ifdef Q_WS_WIN
         if((d->closePopupMode = style()->styleHint(QStyle::SH_MenuBar_DismissOnSecondClick)))
             update(d->actionRect(action));
 #endif
     } else {
         d->setCurrentAction(action, true);
     }
 }
mouseReleaseEvent()
void QMenuBar::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1178 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if(e->button() != Qt::LeftButton || !d->mouseDown)
         return;
     d->mouseDown = false;
     QAction *action = d->actionAt(e->pos());
     if((d->closePopupMode && action == d->currentAction) || !action || !action->menu()) {
         //we set the current action before activating
         //so that we let the leave event set the current back to 0
         d->setCurrentAction(action, false);
         if(action)
             d->activateAction(action, QAction::Trigger);
     }
     d->closePopupMode = 0;
 }
paintEvent()
void QMenuBar::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1068 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     QPainter p(this);
     QRegion emptyArea(rect());
     //draw the items
     for (int i = 0; i < d->actions.count(); ++i) {
         QAction *action = d->actions.at(i);
         QRect adjustedActionRect = d->actionRect(action);
         if (adjustedActionRect.isEmpty() || !d->isVisible(action))
             continue;
         if(!e->rect().intersects(adjustedActionRect))
             continue;
         emptyArea -= adjustedActionRect;
         QStyleOptionMenuItem opt;
         initStyleOption(&opt, action);
         opt.rect = adjustedActionRect;
         p.setClipRect(adjustedActionRect);
         style()->drawControl(QStyle::CE_MenuBarItem, &opt, &p, this);
     }
      //draw border
     if(int fw = style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, this)) {
         QRegion borderReg;
         borderReg += QRect(0, 0, fw, height()); //left
         borderReg += QRect(width()-fw, 0, fw, height()); //right
         borderReg += QRect(0, 0, width(), fw); //top
         borderReg += QRect(0, height()-fw, width(), fw); //bottom
         p.setClipRegion(borderReg);
         emptyArea -= borderReg;
         QStyleOptionFrame frame;
         frame.rect = rect();
         frame.palette = palette();
         frame.state = QStyle::State_None;
         frame.lineWidth = style()->pixelMetric(QStyle::PM_MenuBarPanelWidth);
         frame.midLineWidth = 0;
         style()->drawPrimitive(QStyle::PE_PanelMenuBar, &frame, &p, this);
     }
     p.setClipRegion(emptyArea);
     QStyleOptionMenuItem menuOpt;
     menuOpt.palette = palette();
     menuOpt.state = QStyle::State_None;
     menuOpt.menuItemType = QStyleOptionMenuItem::EmptyArea;
     menuOpt.checkType = QStyleOptionMenuItem::NotCheckable;
     menuOpt.rect = rect();
     menuOpt.menuRect = rect();
     style()->drawControl(QStyle::CE_MenuBarEmptyArea, &menuOpt, &p, this);
 }
resizeEvent()
void QMenuBar::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1058 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     d->itemsDirty = true;
     d->updateGeometries();
 }
setActiveAction()
void QMenuBar::setActiveAction (QAction * act)
Sets the currently highlighted action to act.
Since
4.1
Definition at line 1002 of file qmenubar.cpp.
Referenced by QAccessibleMenuBar::doAction().
 {
     Q_D(QMenuBar);
     d->setCurrentAction(act, true, false);
 }
setCornerWidget()
void QMenuBar::setCornerWidget (QWidget * widget, Qt::Corner corner = Qt::TopRightCorner)
This sets the given widget to be shown directly on the left of the first menu item, or on the right of the last menu item, depending on corner.
The menu bar takes ownership of widget, reparenting it into the menu bar. However, if the corner already contains a widget, this previous widget will no longer be managed and will still be a visible child of the menu bar.
Note
Using a corner other than Qt::TopRightCorner or Qt::TopLeftCorner will result in a warning.
Definition at line 1980 of file qmenubar.cpp.
Referenced by QMdi::ControlContainer::removeButtonsFromMenuBar(), QMainWindow::setMenuBar(), QMdi::ControlContainer::showButtonsInMenuBar(), and QWorkspacePrivate::showMaximizeControls().
 {
     Q_D(QMenuBar);
     switch (corner) {
     case Qt::TopLeftCorner:
         if (d->leftWidget)
             d->leftWidget->removeEventFilter(this);
         d->leftWidget = w;
         break;
     case Qt::TopRightCorner:
         if (d->rightWidget)
             d->rightWidget->removeEventFilter(this);
         d->rightWidget = w;
         break;
     default:
         qWarning("QMenuBar::setCornerWidget: Only TopLeftCorner and TopRightCorner are supported");
         return;
     }
 #ifdef Q_WS_X11
     if(!d->platformMenuBar->allowCornerWidgets()) {
         d->updateCornerWidgetToolBar();
     } else {
 #endif
     if (w) {
         w->setParent(this);
         w->installEventFilter(this);
     }
 #ifdef Q_WS_X11
     }
 #endif
     d->_q_updateLayout();
 }
setDefaultAction()
void QMenuBar::setDefaultAction (QAction * act)
Sets the default action to act.
Since
4.4
The default action is assigned to the left soft key. The menu is assigned to the right soft key.
Currently there is only support for the default action on Windows Mobile. On all other platforms this method is not available.
See also
defaultAction()
Definition at line 2126 of file qmenubar.cpp.
Referenced by QDialog::exec().
 {
     Q_D(QMenuBar);
     if (d->defaultAction == act)
         return;
 #ifdef Q_WS_WINCE
     if (qt_wince_is_mobile())
         if (d->defaultAction) {
             disconnect(d->defaultAction, SIGNAL(changed()), this, SLOT(_q_updateDefaultAction()));
             disconnect(d->defaultAction, SIGNAL(destroyed()), this, SLOT(_q_updateDefaultAction()));
         }
 #endif
     d->defaultAction = act;
 #ifdef Q_WS_WINCE
     if (qt_wince_is_mobile())
         if (d->defaultAction) {
             connect(d->defaultAction, SIGNAL(changed()), this, SLOT(_q_updateDefaultAction()));
             connect(d->defaultAction, SIGNAL(destroyed()), this, SLOT(_q_updateDefaultAction()));
         }
     if (d->wce_menubar) {
         d->wce_menubar->rebuild();
     }
 #endif
 }
setDefaultUp()
void QMenuBar::setDefaultUp (bool b)
Definition at line 1043 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     d->defaultPopDown = !b;
 }
setNativeMenuBar()
void QMenuBar::setNativeMenuBar (bool nativeMenuBar)
Definition at line 2062 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
 #ifdef Q_WS_X11
     d->platformMenuBar->setNativeMenuBar(nativeMenuBar);
 #else
     if (d->nativeMenuBar == -1 || (nativeMenuBar != bool(d->nativeMenuBar))) {
         d->nativeMenuBar = nativeMenuBar;
 #ifdef Q_WS_MAC
         if (!d->nativeMenuBar) {
             extern void qt_mac_clear_menubar();
             qt_mac_clear_menubar();
             d->macDestroyMenuBar();
             const QList<QAction *> &menubarActions = actions();
             for (int i = 0; i < menubarActions.size(); ++i) {
                 const QAction *action = menubarActions.at(i);
                 if (QMenu *menu = action->menu()) {
                     delete menu->d_func()->mac_menu;
                     menu->d_func()->mac_menu = 0;
                 }
             }
         } else {
             d->macCreateMenuBar(parentWidget());
         }
         macUpdateMenuBar();
     updateGeometry();
     if (!d->nativeMenuBar && parentWidget())
         setVisible(true);
 #endif
     }
 #endif // Q_WS_X11
 }
setVisible
void QMenuBar::setVisible (bool visible) virtual slot
Reimplemented Function
Definition at line 1121 of file qmenubar.cpp.
Referenced by setNativeMenuBar().
 {
 #ifdef Q_WS_X11
     Q_D(QMenuBar);
     d->platformMenuBar->setVisible(visible);
 #else
 #if defined(Q_WS_MAC) || defined(Q_OS_WINCE) || defined(Q_WS_S60)
     if (isNativeMenuBar()) {
 #ifndef Q_WS_S60
         if (!visible)
             QWidget::setVisible(false);
 #endif
         return;
     }
 #endif
     QWidget::setVisible(visible);
 #endif // Q_WS_X11
 }
sizeHint()
QSize QMenuBar::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1788 of file qmenubar.cpp.
 {
     Q_D(const QMenuBar);
 #if defined(Q_WS_MAC) || defined(Q_WS_WINCE) || defined(Q_WS_S60) || defined(Q_WS_X11)
     const bool as_gui_menubar = !isNativeMenuBar();
 #else
     const bool as_gui_menubar = true;
 #endif
     ensurePolished();
     QSize ret(0, 0);
     const_cast<QMenuBarPrivate*>(d)->updateGeometries();
     const int hmargin = style()->pixelMetric(QStyle::PM_MenuBarHMargin, 0, this);
     const int vmargin = style()->pixelMetric(QStyle::PM_MenuBarVMargin, 0, this);
     int fw = style()->pixelMetric(QStyle::PM_MenuBarPanelWidth, 0, this);
     int spaceBelowMenuBar = style()->styleHint(QStyle::SH_MainWindow_SpaceBelowMenuBar, 0, this);
     if(as_gui_menubar) {
         const int w = parentWidget() ? parentWidget()->width() : QApplication::desktop()->width();
         d->calcActionRects(w - (2 * fw), 0);
         for (int i = 0; i < d->actionRects.count(); ++i) {
             const QRect &actionRect = d->actionRects.at(i);
             ret = ret.expandedTo(QSize(actionRect.x() + actionRect.width(), actionRect.y() + actionRect.height()));
         }
         //the action geometries already contain the top and left
         //margins. So we only need to add those from right and bottom.
         ret += QSize(fw + hmargin, fw + vmargin);
     }
     int margin = 2*vmargin + 2*fw + spaceBelowMenuBar;
 #ifdef Q_WS_X11
     if(d->platformMenuBar->allowCornerWidgets()) {
 #endif
     if(d->leftWidget) {
         QSize sz = d->leftWidget->sizeHint();
         ret.setWidth(ret.width() + sz.width());
         if(sz.height() + margin > ret.height())
             ret.setHeight(sz.height() + margin);
     }
     if(d->rightWidget) {
         QSize sz = d->rightWidget->sizeHint();
         ret.setWidth(ret.width() + sz.width());
         if(sz.height() + margin > ret.height())
             ret.setHeight(sz.height() + margin);
     }
 #ifdef Q_WS_X11
     }
 #endif
     if(as_gui_menubar) {
         QStyleOptionMenuItem opt;
         opt.rect = rect();
         opt.menuRect = rect();
         opt.state = QStyle::State_None;
         opt.menuItemType = QStyleOptionMenuItem::Normal;
         opt.checkType = QStyleOptionMenuItem::NotCheckable;
         opt.palette = palette();
         return (style()->sizeFromContents(QStyle::CT_MenuBar, &opt,
                                          ret.expandedTo(QApplication::globalStrut()),
                                          this));
     }
     return ret;
 }
timerEvent()
void QMenuBar::timerEvent (QTimerEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1393 of file qmenubar.cpp.
 {
     Q_D(QMenuBar);
     if (e->timerId() == d->autoReleaseTimer.timerId()) {
         d->autoReleaseTimer.stop();
         d->setCurrentAction(0);
     }
     QWidget::timerEvent(e);
 }
triggered
void QMenuBar::triggered (QAction * action) signal
This signal is emitted when an action in a menu belonging to this menubar is triggered as a result of a mouse click; action is the action that caused the signal to be emitted.
Note
QMenuBar has to have ownership of the QMenu in order this signal to work.
Normally, you connect each menu action to a single slot using QAction::triggered(), but sometimes you will want to connect several items to a single slot (most often if the user selects from an array). This signal is useful in such cases.
See also
hovered(), QAction::triggered()
Referenced by actionEvent(), QMenuPrivate::activateCausedStack(), addAction(), and defaultAction().
wceCommands()
void QMenuBar::wceCommands (uint command) static
This function sends native Windows CE commands to Qt menu bars and all their child menus.
Warning
This function is not part of the public interface.
Definition at line 313 of file qmenu_wince.cpp.
Referenced by QtWndProc().
 {
     const HWND hwndActiveWindow = GetActiveWindow();
     for (int i = 0; i < nativeMenuBars.size(); ++i) {
         QMenuBarPrivate* nativeMenuBar = nativeMenuBars.at(i)->d_func();
         if (hwndActiveWindow == nativeMenuBar->wce_menubar->parentWindowHandle)
             nativeMenuBar->wceCommands(command);
     }
 }
wceRefresh()
void QMenuBar::wceRefresh () static
This function refreshes the native Windows CE menu.
Warning
This function is not part of the public interface.
Definition at line 277 of file qmenu_wince.cpp.
Referenced by QMenuPrivate::QWceMenuPrivate::rebuild(), QMenuBarPrivate::QWceMenuBarPrivate::syncAction(), wceRefresh(), and QMenuBarPrivate::QWceMenuBarPrivate::~QWceMenuBarPrivate().
 {
     for (int i = 0; i < nativeMenuBars.size(); ++i)
         nativeMenuBars.at(i)->d_func()->wceRefresh();
 }
Friends and Related Functions
QApplicationPrivate
friend class QApplicationPrivate friend
Definition at line 355 of file qmenubar.h.
QMenu
friend class QMenu friend
Definition at line 350 of file qmenubar.h.
Referenced by addMenu().
QMenuPrivate
friend class QMenuPrivate friend
Definition at line 351 of file qmenubar.h.
qt_mac_activate_action
bool qt_mac_activate_action (MenuRef menu, uint command, QAction::ActionEvent action_e, bool by_accel) friend
Definition at line 209 of file qmenu_mac.mm.
 {
     //fire event
     QMacMenuAction *action = 0;
     if (GetMenuCommandProperty(menu, command, kMenuCreatorQt, kMenuPropertyQAction, sizeof(action), 0, &action) != noErr) {
         QMenuMergeList *list = 0;
         GetMenuItemProperty(menu, 0, kMenuCreatorQt, kMenuPropertyMergeList,
                             sizeof(list), 0, &list);
         if (!list && qt_mac_current_menubar.qmenubar && qt_mac_current_menubar.qmenubar->isNativeMenuBar()) {
             MenuRef apple_menu = qt_mac_current_menubar.qmenubar->d_func()->mac_menubar->apple_menu;
             GetMenuItemProperty(apple_menu, 0, kMenuCreatorQt, kMenuPropertyMergeList, sizeof(list), 0, &list);
             if (list)
                 menu = apple_menu;
         }
         if (list) {
             for(int i = 0; i < list->size(); ++i) {
                 QMenuMergeItem item = list->at(i);
                 if (item.command == command && item.action) {
                     action = item.action;
                     break;
                 }
             }
         }
         if (!action)
             return false;
     }
     if (action_e == QAction::Trigger && by_accel && action->ignore_accel) //no, not a real accel (ie tab)
         return false;
     // Unhighlight the highlighted menu item before triggering the action to
     // prevent items from staying highlighted while a modal dialog is shown.
     // This also fixed the problem that parentless modal dialogs leave
     // the menu item highlighted (since the menu bar is cleared for these types of dialogs).
     if (action_e == QAction::Trigger)
         HiliteMenu(0);
     action->action->activate(action_e);
     //now walk up firing for each "caused" widget (like in the platform independent menu)
     QWidget *caused = 0;
     if (action_e == QAction::Hover && GetMenuItemProperty(menu, 0, kMenuCreatorQt, kMenuPropertyCausedQWidget, sizeof(caused), 0, &caused) == noErr) {
         MenuRef caused_menu = 0;
         if (QMenu *qmenu2 = qobject_cast<QMenu*>(caused))
             caused_menu = qmenu2->macMenu();
         else if (QMenuBar *qmenubar2 = qobject_cast<QMenuBar*>(caused))
             caused_menu = qmenubar2->macMenu();
         else
             caused_menu = 0;
         while(caused_menu) {
             //fire
             QWidget *widget = 0;
             GetMenuItemProperty(caused_menu, 0, kMenuCreatorQt, kMenuPropertyQWidget, sizeof(widget), 0, &widget);
             if (QMenu *qmenu = qobject_cast<QMenu*>(widget)) {
                 action->action->showStatusText(widget);
                 emit qmenu->hovered(action->action);
             } else if (QMenuBar *qmenubar = qobject_cast<QMenuBar*>(widget)) {
                 action->action->showStatusText(widget);
                 emit qmenubar->hovered(action->action);
                 break; //nothing more..
             }
             //walk up
             if (GetMenuItemProperty(caused_menu, 0, kMenuCreatorQt, kMenuPropertyCausedQWidget,
                                     sizeof(caused), 0, &caused) != noErr)
                 break;
             if (QMenu *qmenu2 = qobject_cast<QMenu*>(caused))
                 caused_menu = qmenu2->macMenu();
             else if (QMenuBar *qmenubar2 = qobject_cast<QMenuBar*>(caused))
                 caused_menu = qmenubar2->macMenu();
             else
                 caused_menu = 0;
         }
     }
     return true;
 }
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 356 of file qmenubar.h.
QWindowsStyle
friend class QWindowsStyle friend
Definition at line 352 of file qmenubar.h.
Properties
defaultUp
QMenuBar::defaultUp private
the popup orientation
The default popup orientation. By default, menus pop "down" the screen. By setting the property to true, the menu will pop "up". You might call this for menus that are below the document to which they refer.
If the menu would not fit on the screen, the other direction is used automatically.
Definition at line 66 of file qmenubar.h.
nativeMenuBar
QMenuBar::nativeMenuBar private
Whether or not a menubar will be used as a native menubar on platforms that support it.
Since
4.6
This property specifies whether or not the menubar should be used as a native menubar on platforms that support it. The currently supported platforms are Mac OS X and Windows CE. On these platforms if this property is true, the menubar is used in the native menubar and is not in the window of its parent, if false the menubar remains in the window. On other platforms the value of this attribute has no effect.
The default is to follow whether the Qt::AA_DontUseNativeMenuBar attribute is set for the application. Explicitly settings this property overrides the presence (or abscence) of the attribute.
See also
void-qt-mac-set-native-menubar-bool-enable
Definition at line 67 of file qmenubar.h.
Referenced by actionEvent(), and setNativeMenuBar().
The documentation for this class was generated from the following files:
/src/gui/widgets/qmenubar.h
/src/gui/widgets/qmenu_mac.mm
/src/gui/widgets/qmenu_wince.cpp
/src/gui/widgets/qmenubar.cpp