Qt 4.8: QFontEngineMac Class Reference
QFontEngineMac Class Reference
#include <qfontengine_mac_p.h>
Public Functions
virtual void addGlyphsToPath (glyph_t *glyphs, QFixedPoint *positions, int numGlyphs, QPainterPath *path, QTextItem::RenderFlags)
virtual QImage alphaMapForGlyph (glyph_t)
virtual QImage alphaRGBMapForGlyph (glyph_t, QFixed subPixelPosition, int margin, const QTransform &t)
virtual QFixed ascent () const
virtual QFixed averageCharWidth () const
virtual glyph_metrics_t boundingBox (const QGlyphLayout &glyphs)
virtual glyph_metrics_t boundingBox (glyph_t glyph)
virtual bool canRender (const QChar *string, int len)
virtual QFixed descent () const
void draw (CGContextRef ctx, qreal x, qreal y, const QTextItemInt &ti, int paintDeviceHeight)
virtual FaceId faceId () const
virtual QByteArray getSfntTable (uint tag) const
virtual void getUnscaledGlyph (glyph_t glyph, QPainterPath *path, glyph_metrics_t *metrics)
virtual QFixed leading () const
virtual qreal maxCharWidth () const
virtual const char * name () const
virtual Properties properties () const
QFontEngineMac (ATSUStyle baseStyle, ATSUFontID fontID, const QFontDef &def, QFontEngineMacMulti *multiEngine=0)
virtual void recalcAdvances (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual bool stringToCMap (const QChar *str, int len, QGlyphLayout *glyphs, int *numGlyphs, QTextEngine::ShaperFlags flags) const
virtual int synthesized () const
virtual Type type () const
virtual QFixed xHeight () const
virtual ~QFontEngineMac ()
Public Functions inherited from QFontEngine
void addBitmapFontToPath (qreal x, qreal y, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags)
virtual void addOutlineToPath (qreal, qreal, const QGlyphLayout &, QPainterPath *, QTextItem::RenderFlags flags)
virtual glyph_metrics_t alphaMapBoundingBox (glyph_t glyph, QFixed, const QTransform &matrix, GlyphFormat)
virtual QImage alphaMapForGlyph (glyph_t glyph, QFixed subPixelPosition)
virtual QImage alphaMapForGlyph (glyph_t, const QTransform &t)
virtual QImage alphaMapForGlyph (glyph_t, QFixed subPixelPosition, const QTransform &t)
virtual glyph_metrics_t boundingBox (glyph_t glyph, const QTransform &matrix)
virtual QFontEngine * cloneWithSize (qreal) const
virtual void doKerning (QGlyphLayout *, QTextEngine::ShaperFlags) const
virtual QFixed emSquareSize () const
virtual void getGlyphBearings (glyph_t glyph, qreal *leftBearing=0, qreal *rightBearing=0)
void getGlyphPositions (const QGlyphLayout &glyphs, const QTransform &matrix, QTextItem::RenderFlags flags, QVarLengthArray< glyph_t > &glyphs_out, QVarLengthArray< QFixedPoint > &positions)
virtual HB_Error getPointInOutline (HB_Glyph glyph, int flags, hb_uint32 point, HB_Fixed *xpos, HB_Fixed *ypos, hb_uint32 *nPoints)
QByteArray getSfntTable (uint) const
virtual bool getSfntTableData (uint, uchar *, uint *) const
QFontEngineGlyphCache * glyphCache (void *key, QFontEngineGlyphCache::Type type, const QTransform &transform) const
virtual int glyphCount () const
HB_Face harfbuzzFace () const
HB_Font harfbuzzFont () const
virtual QFixed lineThickness () const
void loadKerningPairs (QFixed scalingFactor)
virtual qreal minLeftBearing () const
virtual qreal minRightBearing () const
QFontEngine ()
virtual void removeGlyphFromCache (glyph_t)
void setGlyphCache (void *key, QFontEngineGlyphCache *data)
virtual bool supportsSubPixelPositions () const
glyph_metrics_t tightBoundingBox (const QGlyphLayout &glyphs)
virtual QFixed underlinePosition () const
virtual ~QFontEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
QImage imageForGlyph (glyph_t glyph, int margin, bool colorful)
Helper function for alphaMapForGlyph and alphaRGBMapForGlyph.
Properties
QCFType< CGFontRef > cgFont
const unsigned char * cmap
QByteArray cmapTable
ATSUFontID fontID
QGlyphLayout kashidaGlyph
QFixed m_ascent
QFixed m_averageCharWidth
QFixed m_descent
QFixed m_leading
qreal m_maxCharWidth
QFixed m_xHeight
QFontEngineMacMulti * multiEngine
ATSUStyle style
bool symbolCMap
int synthesisFlags
CGAffineTransform transform
Friends
class QFontEngineMacMulti
Additional Inherited Members
Public Types inherited from QFontEngine
enum GlyphFormat {
Format_None, Format_Render = Format_None, Format_Mono, Format_A8,
Format_A32
}
enum SynthesizedFlags { SynthesizedItalic = 0x1, SynthesizedBold = 0x2, SynthesizedStretch = 0x4 }
enum Type {
Box, Multi, XLFD, Win,
Mac, Freetype, QPF1, QPF2,
Proxy, S60FontEngine, DirectWrite, TestFontEngine = 0x1000
}
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QFontEngine
static QByteArray convertToPostscriptFontFamilyName (const QByteArray &fontFamily)
static const uchar * getCMap (const uchar *table, uint tableSize, bool *isSymbolFont, int *cmapSize)
static quint32 getTrueTypeGlyphIndex (const uchar *cmap, uint unicode)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables inherited from QFontEngine
uint cache_cost
int cache_count
QFontDef fontDef
uint fsType: 16
int glyphFormat
HB_Face hbFace
HB_FontRec hbFont
QVector< KernPair > kerning_pairs
QAtomicInt ref
bool symbol
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QFontEngine
QFixed lastRightBearing (const QGlyphLayout &glyphs, bool round=false)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions inherited from QFontEngine
static const QVector< QRgb > & grayPalette ()
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 52 of file qfontengine_mac_p.h.
Constructors and Destructors
QFontEngineMac()
QFontEngineMac::QFontEngineMac (ATSUStyle baseStyle, ATSUFontID fontID, const QFontDef & def, QFontEngineMacMulti * multiEngine = 0)
Definition at line 627 of file qfontengine_mac.mm.
     : fontID(fontID), multiEngine(multiEngine), cmap(0), symbolCMap(false)
 {
     fontDef = def;
     ATSUCreateAndCopyStyle(baseStyle, &style);
     ATSFontRef atsFont = FMGetATSFontRefFromFont(fontID);
     cgFont = CGFontCreateWithPlatformFont(&atsFont);
     const int maxAttributeCount = 4;
     ATSUAttributeTag tags[maxAttributeCount + 1];
     ByteCount sizes[maxAttributeCount + 1];
     ATSUAttributeValuePtr values[maxAttributeCount + 1];
     int attributeCount = 0;
     synthesisFlags = 0;
     // synthesizing using CG is not recommended
     quint16 macStyle = 0;
     {
         uchar data[4];
         ByteCount len = 4;
         if (ATSFontGetTable(atsFont, MAKE_TAG('h', 'e', 'a', 'd'), 44, 4, &data, &len) == noErr)
             macStyle = qFromBigEndian<quint16>(data);
     }
     Boolean atsuBold = false;
     Boolean atsuItalic = false;
     if (fontDef.weight >= QFont::Bold) {
         if (!(macStyle & 1)) {
             synthesisFlags |= SynthesizedBold;
             atsuBold = true;
             tags[attributeCount] = kATSUQDBoldfaceTag;
             sizes[attributeCount] = sizeof(atsuBold);
             values[attributeCount] = &atsuBold;
             ++attributeCount;
         }
     }
     if (fontDef.style != QFont::StyleNormal) {
         if (!(macStyle & 2)) {
             synthesisFlags |= SynthesizedItalic;
             atsuItalic = true;
             tags[attributeCount] = kATSUQDItalicTag;
             sizes[attributeCount] = sizeof(atsuItalic);
             values[attributeCount] = &atsuItalic;
             ++attributeCount;
         }
     }
     tags[attributeCount] = kATSUFontTag;
     values[attributeCount] = &fontID;
     sizes[attributeCount] = sizeof(fontID);
     ++attributeCount;
     Q_ASSERT(attributeCount < maxAttributeCount + 1);
     OSStatus err = ATSUSetAttributes(style, attributeCount, tags, sizes, values);
     Q_ASSERT(err == noErr);
     Q_UNUSED(err);
     // CTFontCopyTable
     quint16 tmpFsType;
     if (ATSFontGetTable(atsFont, MAKE_TAG('O', 'S', '/', '2'), 8, 2, &tmpFsType, 0) == noErr)
        fsType = qFromBigEndian<quint16>(tmpFsType);
     else
         fsType = 0;
     if (multiEngine)
     transform = multiEngine->transform;
     else
     transform = CGAffineTransformIdentity;
     ATSUTextMeasurement metric;
     ATSUGetAttribute(style, kATSUAscentTag, sizeof(metric), &metric, 0);
     m_ascent = FixRound(metric);
     ATSUGetAttribute(style, kATSUDescentTag, sizeof(metric), &metric, 0);
     m_descent = FixRound(metric);
     ATSUGetAttribute(style, kATSULeadingTag, sizeof(metric), &metric, 0);
     m_leading = FixRound(metric);
     ATSFontMetrics metrics;
     ATSFontGetHorizontalMetrics(FMGetATSFontRefFromFont(fontID), kATSOptionFlagsDefault, &metrics);
     m_maxCharWidth = metrics.maxAdvanceWidth * fontDef.pointSize;
     ATSFontGetHorizontalMetrics(FMGetATSFontRefFromFont(fontID), kATSOptionFlagsDefault, &metrics);
     m_xHeight = QFixed::fromReal(metrics.xHeight * fontDef.pointSize);
     ATSFontGetHorizontalMetrics(FMGetATSFontRefFromFont(fontID), kATSOptionFlagsDefault, &metrics);
     m_averageCharWidth = QFixed::fromReal(metrics.avgAdvanceWidth * fontDef.pointSize);
     // Use width of 'X' if ATSFontGetHorizontalMetrics returns 0 for avgAdvanceWidth.
     if (m_averageCharWidth == QFixed(0)) {
         QChar c('X');
         QGlyphLayoutArray<1> glyphs;
         int nglyphs = 1;
         stringToCMap(&c, 1, &glyphs, &nglyphs, 0);
         glyph_metrics_t metrics = boundingBox(glyphs);
         m_averageCharWidth =  metrics.width;
     }
 }
~QFontEngineMac()
QFontEngineMac::~QFontEngineMac () virtual
Definition at line 730 of file qfontengine_mac.mm.
 {
     ATSUDisposeStyle(style);
 }
Functions
addGlyphsToPath()
void QFontEngineMac::addGlyphsToPath (glyph_t * glyphs, QFixedPoint * positions, int numGlyphs, QPainterPath * path, QTextItem::RenderFlags) virtual
Reimplemented from QFontEngine.
Definition at line 918 of file qfontengine_mac.mm.
 {
     addGlyphsToPathHelper(style, glyphs, positions, numGlyphs, path);
 }
alphaMapForGlyph()
QImage QFontEngineMac::alphaMapForGlyph (glyph_t glyph) virtual
Create a qimage with the alpha values for the glyph. Returns an image indexed_8 with index values ranging from 0=fully transparent to 255=opaque
Reimplemented from QFontEngine.
Definition at line 981 of file qfontengine_mac.mm.
Referenced by type().
 {
     QImage im = imageForGlyph(glyph, 2, false);
     QImage indexed(im.width(), im.height(), QImage::Format_Indexed8);
     QVector<QRgb> colors(256);
     for (int i=0; i<256; ++i)
         colors[i] = qRgba(0, 0, 0, i);
     indexed.setColorTable(colors);
     for (int y=0; y<im.height(); ++y) {
         uint *src = (uint*) im.scanLine(y);
         uchar *dst = indexed.scanLine(y);
         for (int x=0; x<im.width(); ++x) {
             *dst = qGray(*src);
             ++dst;
             ++src;
         }
     }
     return indexed;
 }
alphaRGBMapForGlyph()
QImage QFontEngineMac::alphaRGBMapForGlyph (glyph_t glyph, QFixed subPixelPosition, int margin, const QTransform & t) virtual
Reimplemented from QFontEngine.
Definition at line 1004 of file qfontengine_mac.mm.
Referenced by type().
 {
     QImage im = imageForGlyph(glyph, margin, true);
     if (t.type() >= QTransform::TxScale) {
         im = im.transformed(t);
     }
     qGamma_correct_back_to_linear_cs(&im);
     return im;
 }
ascent()
QFixed QFontEngineMac::ascent () const virtual
Implements QFontEngine.
Definition at line 846 of file qfontengine_mac.mm.
Referenced by boundingBox().
 {
     return (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             ? m_ascent.round()
             : m_ascent;
 }
averageCharWidth()
QFixed QFontEngineMac::averageCharWidth () const virtual
Reimplemented from QFontEngine.
Definition at line 883 of file qfontengine_mac.mm.
 {
     return (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             ? m_averageCharWidth.round()
             : m_averageCharWidth;
 }
boundingBox() [1/2]
glyph_metrics_t QFontEngineMac::boundingBox (const QGlyphLayout & glyphs) virtual
Implements QFontEngine.
Definition at line 804 of file qfontengine_mac.mm.
Referenced by imageForGlyph(), and QFontEngineMac().
 {
     QFixed w;
     bool round = fontDef.styleStrategy & QFont::ForceIntegerMetrics;
     for (int i = 0; i < glyphs.numGlyphs; ++i) {
         w += round ? glyphs.effectiveAdvance(i).round()
                    : glyphs.effectiveAdvance(i);
     }
     return glyph_metrics_t(0, -(ascent()), w - lastRightBearing(glyphs, round), ascent()+descent(), w, 0);
 }
boundingBox() [2/2]
glyph_metrics_t QFontEngineMac::boundingBox (glyph_t glyph) virtual
Implements QFontEngine.
Definition at line 815 of file qfontengine_mac.mm.
 {
     GlyphID atsuGlyph = glyph;
     ATSGlyphScreenMetrics metrics;
     ATSUGlyphGetScreenMetrics(style, 1, &atsuGlyph, 0,
                               /* iForcingAntiAlias =*/ false,
                               /* iAntiAliasSwitch =*/true,
                               &metrics);
     // ### check again
     glyph_metrics_t gm;
     gm.width = int(metrics.width);
     gm.height = int(metrics.height);
     gm.x = QFixed::fromReal(metrics.topLeft.x);
     gm.y = -QFixed::fromReal(metrics.topLeft.y);
     gm.xoff = QFixed::fromReal(metrics.deviceAdvance.x);
     gm.yoff = QFixed::fromReal(metrics.deviceAdvance.y);
     if (fontDef.styleStrategy & QFont::ForceIntegerMetrics) {
         gm.x = gm.x.floor();
         gm.y = gm.y.floor();
         gm.xoff = gm.xoff.round();
         gm.yoff = gm.yoff.round();
     }
     return gm;
 }
canRender()
bool QFontEngineMac::canRender (const QChar * string, int len) virtual
Implements QFontEngine.
Definition at line 1018 of file qfontengine_mac.mm.
Referenced by name(), and QFontEngineMacMulti::name().
 {
     Q_ASSERT(false);
     Q_UNUSED(string);
     Q_UNUSED(len);
     return false;
 }
descent()
QFixed QFontEngineMac::descent () const virtual
Implements QFontEngine.
Definition at line 853 of file qfontengine_mac.mm.
Referenced by boundingBox().
 {
     // subtract a pixel to even out the historical +1 in QFontMetrics::height().
     // Fix in Qt 5.
     return (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             ? m_descent.round() - 1
             : m_descent;
 }
draw()
void QFontEngineMac::draw (CGContextRef ctx, qreal x, qreal y, const QTextItemInt & ti, int paintDeviceHeight)
Definition at line 1026 of file qfontengine_mac.mm.
Referenced by type().
 {
     QVarLengthArray<QFixedPoint> positions;
     QVarLengthArray<glyph_t> glyphs;
     QTransform matrix;
     matrix.translate(x, y);
     getGlyphPositions(ti.glyphs, matrix, ti.flags, glyphs, positions);
     if (glyphs.size() == 0)
         return;
     CGContextSetFontSize(ctx, fontDef.pixelSize);
     CGAffineTransform oldTextMatrix = CGContextGetTextMatrix(ctx);
     CGAffineTransform cgMatrix = CGAffineTransformMake(1, 0, 0, -1, 0, -paintDeviceHeight);
     CGAffineTransformConcat(cgMatrix, oldTextMatrix);
     if (synthesisFlags & QFontEngine::SynthesizedItalic)
         cgMatrix = CGAffineTransformConcat(cgMatrix, CGAffineTransformMake(1, 0, -tanf(14 * acosf(0) / 90), 1, 0, 0));
     cgMatrix = CGAffineTransformConcat(cgMatrix, transform);
     CGContextSetTextMatrix(ctx, cgMatrix);
     CGContextSetTextDrawingMode(ctx, kCGTextFill);
     QVarLengthArray<CGSize> advances(glyphs.size());
     QVarLengthArray<CGGlyph> cgGlyphs(glyphs.size());
     for (int i = 0; i < glyphs.size() - 1; ++i) {
         advances[i].width = (positions[i + 1].x - positions[i].x).toReal();
         advances[i].height = (positions[i + 1].y - positions[i].y).toReal();
         cgGlyphs[i] = glyphs[i];
     }
     advances[glyphs.size() - 1].width = 0;
     advances[glyphs.size() - 1].height = 0;
     cgGlyphs[glyphs.size() - 1] = glyphs[glyphs.size() - 1];
     CGContextSetFont(ctx, cgFont);
     CGContextSetTextPosition(ctx, positions[0].x.toReal(), positions[0].y.toReal());
     CGContextShowGlyphsWithAdvances(ctx, cgGlyphs.data(), advances.data(), glyphs.size());
     if (synthesisFlags & QFontEngine::SynthesizedBold) {
         CGContextSetTextPosition(ctx, positions[0].x.toReal() + 0.5 * lineThickness().toReal(),
                                       positions[0].y.toReal());
         CGContextShowGlyphsWithAdvances(ctx, cgGlyphs.data(), advances.data(), glyphs.size());
     }
     CGContextSetTextMatrix(ctx, oldTextMatrix);
 }
faceId()
QFontEngine::FaceId QFontEngineMac::faceId () const virtual
Reimplemented from QFontEngine.
Definition at line 1082 of file qfontengine_mac.mm.
Referenced by type().
 {
     FaceId ret;
 #if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
 if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
     // CTFontGetPlatformFont
     FSRef ref;
     if (ATSFontGetFileReference(FMGetATSFontRefFromFont(fontID), &ref) != noErr)
         return ret;
     ret.filename = QByteArray(128, 0);
     ret.index = fontID;
     FSRefMakePath(&ref, (UInt8 *)ret.filename.data(), ret.filename.size());
 }else
 #endif
 {
     FSSpec spec;
     if (ATSFontGetFileSpecification(FMGetATSFontRefFromFont(fontID), &spec) != noErr)
         return ret;
     FSRef ref;
     FSpMakeFSRef(&spec, &ref);
     ret.filename = QByteArray(128, 0);
     ret.index = fontID;
     FSRefMakePath(&ref, (UInt8 *)ret.filename.data(), ret.filename.size());
 }
     return ret;
 }
getSfntTable()
QByteArray QFontEngineMac::getSfntTable (uint tag) const virtual
Definition at line 1110 of file qfontengine_mac.mm.
Referenced by stringToCMap(), and type().
 {
     ATSFontRef atsFont = FMGetATSFontRefFromFont(fontID);
     ByteCount length;
     OSStatus status = ATSFontGetTable(atsFont, tag, 0, 0, 0, &length);
     if (status != noErr)
         return QByteArray();
     QByteArray table(length, 0);
     // CTFontCopyTable
     status = ATSFontGetTable(atsFont, tag, 0, table.length(), table.data(), &length);
     if (status != noErr)
         return QByteArray();
     return table;
 }
getUnscaledGlyph()
void QFontEngineMac::getUnscaledGlyph (glyph_t glyph, QPainterPath * path, glyph_metrics_t * metrics) virtual
Reimplemented from QFontEngine.
Definition at line 1183 of file qfontengine_mac.mm.
Referenced by type().
 {
     ATSUStyle unscaledStyle;
     ATSUCreateAndCopyStyle(style, &unscaledStyle);
     int emSquare = properties().emSquare.toInt();
     const int maxAttributeCount = 4;
     ATSUAttributeTag tags[maxAttributeCount + 1];
     ByteCount sizes[maxAttributeCount + 1];
     ATSUAttributeValuePtr values[maxAttributeCount + 1];
     int attributeCount = 0;
     Fixed size = FixRatio(emSquare, 1);
     tags[attributeCount] = kATSUSizeTag;
     sizes[attributeCount] = sizeof(size);
     values[attributeCount] = &size;
     ++attributeCount;
     Q_ASSERT(attributeCount < maxAttributeCount + 1);
     OSStatus err = ATSUSetAttributes(unscaledStyle, attributeCount, tags, sizes, values);
     Q_ASSERT(err == noErr);
     Q_UNUSED(err);
     // various CTFont metrics functions: CTFontGetBoundingRectsForGlyphs, CTFontGetAdvancesForGlyphs
     GlyphID atsuGlyph = glyph;
     ATSGlyphScreenMetrics atsuMetrics;
     ATSUGlyphGetScreenMetrics(unscaledStyle, 1, &atsuGlyph, 0,
                               /* iForcingAntiAlias =*/ false,
                               /* iAntiAliasSwitch =*/true,
                               &atsuMetrics);
     metrics->width = int(atsuMetrics.width);
     metrics->height = int(atsuMetrics.height);
     metrics->x = QFixed::fromReal(atsuMetrics.topLeft.x);
     metrics->y = -QFixed::fromReal(atsuMetrics.topLeft.y);
     metrics->xoff = QFixed::fromReal(atsuMetrics.deviceAdvance.x);
     metrics->yoff = QFixed::fromReal(atsuMetrics.deviceAdvance.y);
     QFixedPoint p;
     addGlyphsToPathHelper(unscaledStyle, &glyph, &p, 1, path);
     ATSUDisposeStyle(unscaledStyle);
 }
imageForGlyph()
QImage QFontEngineMac::imageForGlyph (glyph_t glyph, int margin, bool colorful) private
Helper function for alphaMapForGlyph and alphaRGBMapForGlyph.
The two are identical, except for the subpixel antialiasing...
Definition at line 929 of file qfontengine_mac.mm.
Referenced by alphaMapForGlyph(), alphaRGBMapForGlyph(), and type().
 {
     const glyph_metrics_t br = boundingBox(glyph);
     QImage im(qRound(br.width)+2, qRound(br.height)+4, QImage::Format_RGB32);
     im.fill(0xff000000);
     CGColorSpaceRef colorspace = QCoreGraphicsPaintEngine::macGenericColorSpace();
     uint cgflags = kCGImageAlphaNoneSkipFirst;
 #ifdef kCGBitmapByteOrder32Host //only needed because CGImage.h added symbols in the minor version
     cgflags |= kCGBitmapByteOrder32Host;
 #endif
     CGContextRef ctx = CGBitmapContextCreate(im.bits(), im.width(), im.height(),
                                              8, im.bytesPerLine(), colorspace,
                                              cgflags);
     CGContextSetFontSize(ctx, fontDef.pixelSize);
     CGContextSetShouldAntialias(ctx, fontDef.pointSize > qt_antialiasing_threshold && !(fontDef.styleStrategy & QFont::NoAntialias));
     // turn off sub-pixel hinting - no support for that in OpenGL
     CGContextSetShouldSmoothFonts(ctx, colorful);
     CGAffineTransform oldTextMatrix = CGContextGetTextMatrix(ctx);
     CGAffineTransform cgMatrix = CGAffineTransformMake(1, 0, 0, 1, 0, 0);
     CGAffineTransformConcat(cgMatrix, oldTextMatrix);
     if (synthesisFlags & QFontEngine::SynthesizedItalic)
         cgMatrix = CGAffineTransformConcat(cgMatrix, CGAffineTransformMake(1, 0, tanf(14 * acosf(0) / 90), 1, 0, 0));
     cgMatrix = CGAffineTransformConcat(cgMatrix, transform);
     CGContextSetTextMatrix(ctx, cgMatrix);
     CGContextSetRGBFillColor(ctx, 1, 1, 1, 1);
     CGContextSetTextDrawingMode(ctx, kCGTextFill);
     CGContextSetFont(ctx, cgFont);
     qreal pos_x = -br.x.toReal() + 1;
     qreal pos_y = im.height() + br.y.toReal() - 2;
     CGContextSetTextPosition(ctx, pos_x, pos_y);
     CGSize advance;
     advance.width = 0;
     advance.height = 0;
     CGGlyph cgGlyph = glyph;
     CGContextShowGlyphsWithAdvances(ctx, &cgGlyph, &advance, 1);
     if (synthesisFlags & QFontEngine::SynthesizedBold) {
         CGContextSetTextPosition(ctx, pos_x + 0.5 * lineThickness().toReal(), pos_y);
         CGContextShowGlyphsWithAdvances(ctx, &cgGlyph, &advance, 1);
     }
     CGContextRelease(ctx);
     return im;
 }
leading()
QFixed QFontEngineMac::leading () const virtual
Implements QFontEngine.
Definition at line 862 of file qfontengine_mac.mm.
 {
     return (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             ? m_leading.round()
             : m_leading;
 }
maxCharWidth()
qreal QFontEngineMac::maxCharWidth () const virtual
Implements QFontEngine.
Definition at line 869 of file qfontengine_mac.mm.
 {
     return (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             ? qRound(m_maxCharWidth)
             : m_maxCharWidth;
 }
name()
virtual const char* QFontEngineMac::name () const inline virtual
Implements QFontEngine.
Definition at line 75 of file qfontengine_mac_p.h.
 { return "QFontEngineMac"; }
properties()
QFontEngine::Properties QFontEngineMac::properties () const virtual
Reimplemented from QFontEngine.
Definition at line 1126 of file qfontengine_mac.mm.
Referenced by getUnscaledGlyph(), and type().
 {
     QFontEngine::Properties props;
     ATSFontRef atsFont = FMGetATSFontRefFromFont(fontID);
     quint16 tmp;
     // CTFontGetUnitsPerEm
     if (ATSFontGetTable(atsFont, MAKE_TAG('h', 'e', 'a', 'd'), 18, 2, &tmp, 0) == noErr)
        props.emSquare = qFromBigEndian<quint16>(tmp);
     struct {
         qint16 xMin;
         qint16 yMin;
         qint16 xMax;
         qint16 yMax;
     } bbox;
     bbox.xMin = bbox.xMax = bbox.yMin = bbox.yMax = 0;
     // CTFontGetBoundingBox
     if (ATSFontGetTable(atsFont, MAKE_TAG('h', 'e', 'a', 'd'), 36, 8, &bbox, 0) == noErr) {
         bbox.xMin = qFromBigEndian<quint16>(bbox.xMin);
         bbox.yMin = qFromBigEndian<quint16>(bbox.yMin);
         bbox.xMax = qFromBigEndian<quint16>(bbox.xMax);
         bbox.yMax = qFromBigEndian<quint16>(bbox.yMax);
     }
     struct {
         qint16 ascender;
         qint16 descender;
         qint16 linegap;
     } metrics;
     metrics.ascender = metrics.descender = metrics.linegap = 0;
     // CTFontGetAscent, etc.
     if (ATSFontGetTable(atsFont, MAKE_TAG('h', 'h', 'e', 'a'), 4, 6, &metrics, 0) == noErr) {
         metrics.ascender = qFromBigEndian<quint16>(metrics.ascender);
         metrics.descender = qFromBigEndian<quint16>(metrics.descender);
         metrics.linegap = qFromBigEndian<quint16>(metrics.linegap);
     }
     props.ascent = metrics.ascender;
     props.descent = -metrics.descender;
     props.leading = metrics.linegap;
     props.boundingBox = QRectF(bbox.xMin, -bbox.yMax,
                            bbox.xMax - bbox.xMin,
                            bbox.yMax - bbox.yMin);
     props.italicAngle = 0;
     props.capHeight = props.ascent;
     qint16 lw = 0;
     // fonts lie
     if (ATSFontGetTable(atsFont, MAKE_TAG('p', 'o', 's', 't'), 10, 2, &lw, 0) == noErr)
        lw = qFromBigEndian<quint16>(lw);
     props.lineWidth = lw;
     // CTFontCopyPostScriptName
     QCFString psName;
     if (ATSFontGetPostScriptName(FMGetATSFontRefFromFont(fontID), kATSOptionFlagsDefault, &psName) == noErr)
         props.postscriptName = QString(psName).toUtf8();
     props.postscriptName = QFontEngine::convertToPostscriptFontFamilyName(props.postscriptName);
     return props;
 }
recalcAdvances()
void QFontEngineMac::recalcAdvances (QGlyphLayout * , QTextEngine::ShaperFlags) const virtual
This is a callback from harfbuzz. The font engine uses the font-system in use to find out the advances of each glyph and set it on the layout.
Reimplemented from QFontEngine.
Definition at line 778 of file qfontengine_mac.mm.
Referenced by stringToCMap().
 {
     Q_UNUSED(flags)
     QVarLengthArray<GlyphID> atsuGlyphs(glyphs->numGlyphs);
     for (int i = 0; i < glyphs->numGlyphs; ++i)
         atsuGlyphs[i] = glyphs->glyphs[i];
     QVarLengthArray<ATSGlyphScreenMetrics> metrics(glyphs->numGlyphs);
     ATSUGlyphGetScreenMetrics(style, glyphs->numGlyphs, atsuGlyphs.data(), sizeof(GlyphID),
                               /* iForcingAntiAlias =*/ false,
                               /* iAntiAliasSwitch =*/true,
                               metrics.data());
     for (int i = 0; i < glyphs->numGlyphs; ++i) {
         glyphs->advances_x[i] = QFixed::fromReal(metrics[i].deviceAdvance.x);
         glyphs->advances_y[i] = QFixed::fromReal(metrics[i].deviceAdvance.y);
         if (fontDef.styleStrategy & QFont::ForceIntegerMetrics) {
             glyphs->advances_x[i] = glyphs->advances_x[i].round();
             glyphs->advances_y[i] = glyphs->advances_y[i].round();
         }
     }
 }
stringToCMap()
bool QFontEngineMac::stringToCMap (const QChar * str, int len, QGlyphLayout * glyphs, int * numGlyphs, QTextEngine::ShaperFlags flags) const virtual
Implements QFontEngine.
Definition at line 746 of file qfontengine_mac.mm.
Referenced by QFontEngineMac().
 {
     if (!cmap) {
         cmapTable = getSfntTable(MAKE_TAG('c', 'm', 'a', 'p'));
         int size = 0;
         cmap = getCMap(reinterpret_cast<const uchar *>(cmapTable.constData()), cmapTable.size(), &symbolCMap, &size);
         if (!cmap)
             return false;
     }
     if (symbolCMap) {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(str, i, len);
             glyphs->glyphs[i] = getTrueTypeGlyphIndex(cmap, uc);
             if(!glyphs->glyphs[i] && uc < 0x100)
                 glyphs->glyphs[i] = getTrueTypeGlyphIndex(cmap, uc + 0xf000);
         }
     } else {
         for (int i = 0; i < len; ++i) {
             unsigned int uc = getChar(str, i, len);
             glyphs->glyphs[i] = getTrueTypeGlyphIndex(cmap, uc);
         }
     }
     *nglyphs = len;
     glyphs->numGlyphs = *nglyphs;
     if (!(flags & QTextEngine::GlyphIndicesOnly))
         recalcAdvances(glyphs, flags);
     return true;
 }
synthesized()
virtual int QFontEngineMac::synthesized () const inline virtual
Reimplemented from QFontEngine.
Definition at line 79 of file qfontengine_mac_p.h.
 { return synthesisFlags; }
type()
virtual Type QFontEngineMac::type () const inline virtual
Implements QFontEngine.
Definition at line 81 of file qfontengine_mac_p.h.
 { return QFontEngine::Mac; }
xHeight()
QFixed QFontEngineMac::xHeight () const virtual
Reimplemented from QFontEngine.
Definition at line 876 of file qfontengine_mac.mm.
 {
     return (fontDef.styleStrategy & QFont::ForceIntegerMetrics)
             ? m_xHeight.round()
             : m_xHeight;
 }
Friends and Related Functions
QFontEngineMacMulti
friend class QFontEngineMacMulti friend
Definition at line 54 of file qfontengine_mac_p.h.
Properties
cgFont
QCFType<CGFontRef> QFontEngineMac::cgFont private
Definition at line 96 of file qfontengine_mac_p.h.
Referenced by draw(), imageForGlyph(), and QFontEngineMac().
cmap
const unsigned char* QFontEngineMac::cmap mutable private
Definition at line 101 of file qfontengine_mac_p.h.
Referenced by stringToCMap().
cmapTable
QByteArray QFontEngineMac::cmapTable mutable private
Definition at line 103 of file qfontengine_mac_p.h.
Referenced by stringToCMap().
fontID
ATSUFontID QFontEngineMac::fontID private
Definition at line 95 of file qfontengine_mac_p.h.
Referenced by faceId(), QFontEngineMacMulti::fontIndexForFontID(), getSfntTable(), QFontEngineMacMulti::macFontID(), properties(), and QFontEngineMac().
kashidaGlyph
QGlyphLayout QFontEngineMac::kashidaGlyph mutable private
Definition at line 99 of file qfontengine_mac_p.h.
m_ascent
QFixed QFontEngineMac::m_ascent private
Definition at line 105 of file qfontengine_mac_p.h.
Referenced by ascent(), and QFontEngineMac().
m_averageCharWidth
QFixed QFontEngineMac::m_averageCharWidth private
Definition at line 110 of file qfontengine_mac_p.h.
Referenced by averageCharWidth(), and QFontEngineMac().
m_descent
QFixed QFontEngineMac::m_descent private
Definition at line 106 of file qfontengine_mac_p.h.
Referenced by descent(), and QFontEngineMac().
m_leading
QFixed QFontEngineMac::m_leading private
Definition at line 107 of file qfontengine_mac_p.h.
Referenced by leading(), and QFontEngineMac().
m_maxCharWidth
qreal QFontEngineMac::m_maxCharWidth private
Definition at line 108 of file qfontengine_mac_p.h.
Referenced by maxCharWidth(), and QFontEngineMac().
m_xHeight
QFixed QFontEngineMac::m_xHeight private
Definition at line 109 of file qfontengine_mac_p.h.
Referenced by QFontEngineMac(), and xHeight().
multiEngine
QFontEngineMacMulti* QFontEngineMac::multiEngine private
Definition at line 100 of file qfontengine_mac_p.h.
Referenced by QFontEngineMacMulti::~QFontEngineMacMulti().
style
ATSUStyle QFontEngineMac::style private
Definition at line 97 of file qfontengine_mac_p.h.
Referenced by addGlyphsToPath(), boundingBox(), getUnscaledGlyph(), QFontEngineMac(), recalcAdvances(), and ~QFontEngineMac().
symbolCMap
bool QFontEngineMac::symbolCMap mutable private
Definition at line 102 of file qfontengine_mac_p.h.
Referenced by stringToCMap().
synthesisFlags
int QFontEngineMac::synthesisFlags private
Definition at line 98 of file qfontengine_mac_p.h.
Referenced by draw(), imageForGlyph(), QFontEngineMac(), and synthesized().
transform
CGAffineTransform QFontEngineMac::transform private
Definition at line 104 of file qfontengine_mac_p.h.
Referenced by draw(), imageForGlyph(), and QFontEngineMac().
The documentation for this class was generated from the following files:
/src/gui/text/qfontengine_mac_p.h
/src/gui/text/qfontengine_mac.mm