Qt 4.8: QWidgetItemV2 Class Reference
QWidgetItemV2 Class Reference
#include <qlayoutitem.h>
Public Functions
int heightForWidth (int width) const
Reimplemented Function
QSize maximumSize () const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
QWidgetItemV2 (QWidget *widget)
QSize sizeHint () const
Reimplemented Function
~QWidgetItemV2 ()
Public Functions inherited from QWidgetItem
Qt::Orientations expandingDirections () const
Reimplemented Function
QRect geometry () const
Reimplemented Function
bool hasHeightForWidth () const
Reimplemented Function
bool isEmpty () const
Returns true if the widget is hidden; otherwise returns false.
QWidgetItem (QWidget *w)
Creates an item containing the given widget.
void setGeometry (const QRect &)
Reimplemented Function
virtual QWidget * widget ()
Returns the widget managed by this item.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual void invalidate ()
Invalidates any cached information in this layout item.
virtual QLayout * layout ()
If this item is a QLayout, it is returned as a QLayout; otherwise 0 is returned.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Private Types
enum { Dirty = -123, HfwCacheMaxSize = 3 }
Private Functions
void invalidateSizeCache ()
void updateCacheIfNecessary () const
bool useSizeCache () const
Properties
void * d
QSize q_cachedHfws [HfwCacheMaxSize]
QSize q_cachedMaximumSize
QSize q_cachedMinimumSize
QSize q_cachedSizeHint
short q_firstCachedHfw
short q_hfwCacheSize
Friends
class QWidgetPrivate
Additional Inherited Members
Protected Variables inherited from QWidgetItem
QWidget * wid
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Detailed Description
Warning
This function is not part of the public interface.
Definition at line 144 of file qlayoutitem.h.
Enumerations
anonymous enum
anonymous enum private
Enumerator
Dirty
HfwCacheMaxSize
Definition at line 156 of file qlayoutitem.h.
 { Dirty = -123, HfwCacheMaxSize = 3 };
Constructors and Destructors
QWidgetItemV2()
QWidgetItemV2::QWidgetItemV2 (QWidget * widget) explicit
Definition at line 771 of file qlayoutitem.cpp.
     : QWidgetItem(widget),
       q_cachedMinimumSize(Dirty, Dirty),
       q_cachedSizeHint(Dirty, Dirty),
       q_cachedMaximumSize(Dirty, Dirty),
       q_firstCachedHfw(0),
       q_hfwCacheSize(0),
       d(0)
 {
     QWidgetPrivate *wd = wid->d_func();
     if (!wd->widgetItem)
         wd->widgetItem = this;
 }
~QWidgetItemV2()
QWidgetItemV2::~QWidgetItemV2 ()
Definition at line 785 of file qlayoutitem.cpp.
 {
     if (wid) {
         QWidgetPrivate *wd = wid->d_func();
         if (wd->widgetItem == this)
             wd->widgetItem = 0;
     }
 }
Functions
heightForWidth()
int QWidgetItemV2::heightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 848 of file qlayoutitem.cpp.
 {
     if (isEmpty())
         return -1;
     for (int i = 0; i < q_hfwCacheSize; ++i) {
         int offset = q_firstCachedHfw + i;
         const QSize &size = q_cachedHfws[offset % HfwCacheMaxSize];
         if (size.width() == width) {
             if (q_hfwCacheSize == HfwCacheMaxSize)
                 q_firstCachedHfw = offset;
             return size.height();
         }
     }
     if (q_hfwCacheSize < HfwCacheMaxSize)
         ++q_hfwCacheSize;
     q_firstCachedHfw = (q_firstCachedHfw + HfwCacheMaxSize - 1) % HfwCacheMaxSize;
     int height = QWidgetItem::heightForWidth(width);
     q_cachedHfws[q_firstCachedHfw] = QSize(width, height);
     return height;
 }
invalidateSizeCache()
void QWidgetItemV2::invalidateSizeCache () inline private
Definition at line 160 of file qlayoutitem.h.
{
         q_cachedMinimumSize.setWidth(Dirty);
         q_hfwCacheSize = 0;
     }
maximumSize()
QSize QWidgetItemV2::maximumSize () const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 820 of file qlayoutitem.cpp.
 {
     if (isEmpty())
         return QSize(0, 0);
     if (useSizeCache()) {
         updateCacheIfNecessary();
         return q_cachedMaximumSize;
     } else {
         return QWidgetItem::maximumSize();
     }
 }
minimumSize()
QSize QWidgetItemV2::minimumSize () const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 807 of file qlayoutitem.cpp.
 {
     if (isEmpty())
         return QSize(0, 0);
     if (useSizeCache()) {
         updateCacheIfNecessary();
         return q_cachedMinimumSize;
     } else {
         return QWidgetItem::minimumSize();
     }
 }
sizeHint()
QSize QWidgetItemV2::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 794 of file qlayoutitem.cpp.
 {
     if (isEmpty())
         return QSize(0, 0);
     if (useSizeCache()) {
         updateCacheIfNecessary();
         return q_cachedSizeHint;
     } else {
         return QWidgetItem::sizeHint();
     }
 }
updateCacheIfNecessary()
void QWidgetItemV2::updateCacheIfNecessary () const private
Definition at line 733 of file qlayoutitem.cpp.
Referenced by maximumSize(), minimumSize(), and sizeHint().
 {
     if (q_cachedMinimumSize.width() != Dirty)
         return;
     const QSize sizeHint(wid->sizeHint());
     const QSize minimumSizeHint(wid->minimumSizeHint());
     const QSize minimumSize(wid->minimumSize());
     const QSize maximumSize(wid->maximumSize());
     const QSizePolicy sizePolicy(wid->sizePolicy());
     const QSize expandedSizeHint(sizeHint.expandedTo(minimumSizeHint));
     const QSize smartMinSize(qSmartMinSize(sizeHint, minimumSizeHint, minimumSize, maximumSize, sizePolicy));
     const QSize smartMaxSize(qSmartMaxSize(expandedSizeHint, minimumSize, maximumSize, sizePolicy, align));
     const bool useLayoutItemRect = !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect);
     q_cachedMinimumSize = useLayoutItemRect
            ? toLayoutItemSize(wid->d_func(), smartMinSize)
            : smartMinSize;
     q_cachedSizeHint = expandedSizeHint;
     q_cachedSizeHint = q_cachedSizeHint.boundedTo(maximumSize)
                                        .expandedTo(minimumSize);
     q_cachedSizeHint = useLayoutItemRect
            ? toLayoutItemSize(wid->d_func(), q_cachedSizeHint)
            : q_cachedSizeHint;
     if (wid->sizePolicy().horizontalPolicy() == QSizePolicy::Ignored)
         q_cachedSizeHint.setWidth(0);
     if (wid->sizePolicy().verticalPolicy() == QSizePolicy::Ignored)
         q_cachedSizeHint.setHeight(0);
     q_cachedMaximumSize = useLayoutItemRect
                ? toLayoutItemSize(wid->d_func(), smartMaxSize)
                : smartMaxSize;
 }
useSizeCache()
bool QWidgetItemV2::useSizeCache () const inline private
Definition at line 728 of file qlayoutitem.cpp.
Referenced by maximumSize(), minimumSize(), and sizeHint().
 {
     return wid->d_func()->widgetItem == this;
 }
Friends and Related Functions
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 173 of file qlayoutitem.h.
Properties
d
void* QWidgetItemV2::d private
Definition at line 171 of file qlayoutitem.h.
q_cachedHfws
QSize QWidgetItemV2::q_cachedHfws[HfwCacheMaxSize] mutable private
Definition at line 168 of file qlayoutitem.h.
Referenced by heightForWidth().
q_cachedMaximumSize
QSize QWidgetItemV2::q_cachedMaximumSize mutable private
Definition at line 167 of file qlayoutitem.h.
Referenced by maximumSize().
q_cachedMinimumSize
QSize QWidgetItemV2::q_cachedMinimumSize mutable private
Definition at line 165 of file qlayoutitem.h.
Referenced by minimumSize().
q_cachedSizeHint
QSize QWidgetItemV2::q_cachedSizeHint mutable private
Definition at line 166 of file qlayoutitem.h.
Referenced by sizeHint().
q_firstCachedHfw
short QWidgetItemV2::q_firstCachedHfw mutable private
Definition at line 169 of file qlayoutitem.h.
Referenced by heightForWidth().
q_hfwCacheSize
short QWidgetItemV2::q_hfwCacheSize mutable private
Definition at line 170 of file qlayoutitem.h.
Referenced by heightForWidth().
The documentation for this class was generated from the following files:
/src/gui/kernel/qlayoutitem.h
/src/gui/kernel/qlayoutitem.cpp