Qt 4.8: QStringListModel Class Reference
QStringListModel Class Reference
The QStringListModel class provides a model that supplies strings to views.
#include <qstringlistmodel.h>
Public Functions
QVariant data (const QModelIndex &index, int role) const
Returns data for the specified role, from the item with the given index.
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the flags for the item with the given index.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Inserts count rows into the model, beginning at the given row.
QStringListModel (QObject *parent=0)
Constructs a string list model with the given parent.
QStringListModel (const QStringList &strings, QObject *parent=0)
Constructs a string list model containing the specified strings with the given parent.
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Removes count rows from the model, beginning at the given row.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows in the model.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the data for the specified role in the item with the given index in the model, to the provided value.
void setStringList (const QStringList &strings)
Sets the model's internal string list to strings.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
QStringList stringList () const
Returns the string list used by the model to store data.
Qt::DropActions supportedDropActions () const
Reimplemented Function
Public Functions inherited from QAbstractListModel
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QModelIndex index (int row, int column=0, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
QAbstractListModel (QObject *parent=0)
Constructs an abstract list model with the given parent.
~QAbstractListModel ()
Destroys the abstract list model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data for the given role and section in the header with the specified orientation.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QStringList lst
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractListModel
QAbstractListModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract list model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QStringListModel class provides a model that supplies strings to views.
QStringListModel is an editable model that can be used for simple cases where you need to display a number of strings in a view widget, such as a QListView or a QComboBox.
The model provides all the standard functions of an editable model, representing the data in the string list as a model with one column and a number of rows equal to the number of items in the list.
Model indexes corresponding to items are obtained with the index() function, and item flags are obtained with flags(). Item data is read with the data() function and written with setData(). The number of rows (and number of items in the string list) can be found with the rowCount() function.
The model can be constructed with an existing string list, or strings can be set later with the setStringList() convenience function. Strings can also be inserted in the usual way with the insertRows() function, and removed with removeRows(). The contents of the string list can be retrieved with the stringList() convenience function.
An example usage of QStringListModel:
    QStringListModel *model = new QStringListModel();
    QStringList list;
    list << "a" << "b" << "c";
    model->setStringList(list);
See also
QAbstractListModel, QAbstractItemModel, {Model Classes}
Definition at line 56 of file qstringlistmodel.h.
Constructors and Destructors
QStringListModel() [1/2]
QStringListModel::QStringListModel (QObject * parent = 0) explicit
Constructs a string list model with the given parent.
Definition at line 96 of file qstringlistmodel.cpp.
     : QAbstractListModel(parent)
 {
 }
QStringListModel() [2/2]
QStringListModel::QStringListModel (const QStringList & strings, QObject * parent = 0)
Constructs a string list model containing the specified strings with the given parent.
Definition at line 106 of file qstringlistmodel.cpp.
     : QAbstractListModel(parent), lst(strings)
 {
 }
Functions
data()
QVariant QStringListModel::data (const QModelIndex & index, int role) const virtual
Returns data for the specified role, from the item with the given index.
If the view requests an invalid index, an invalid variant is returned.
See also
setData()
Implements QAbstractItemModel.
Definition at line 139 of file qstringlistmodel.cpp.
 {
     if (index.row() < 0 || index.row() >= lst.size())
         return QVariant();
     if (role == Qt::DisplayRole || role == Qt::EditRole)
         return lst.at(index.row());
     return QVariant();
 }
flags()
Qt::ItemFlags QStringListModel::flags (const QModelIndex & index) const virtual
Returns the flags for the item with the given index.
Valid items are enabled, selectable, editable, drag enabled and drop enabled.
See also
QAbstractItemModel::flags()
Reimplemented from QAbstractItemModel.
Definition at line 158 of file qstringlistmodel.cpp.
 {
     if (!index.isValid())
         return QAbstractItemModel::flags(index) | Qt::ItemIsDropEnabled;
     return QAbstractItemModel::flags(index) | Qt::ItemIsEditable | Qt::ItemIsDragEnabled | Qt::ItemIsDropEnabled;
 }
insertRows()
bool QStringListModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Inserts count rows into the model, beginning at the given row.
The parent index of the rows is optional and is only used for consistency with QAbstractItemModel. By default, a null index is specified, indicating that the rows are inserted in the top level of the model.
See also
QAbstractItemModel::insertRows()
Reimplemented from QAbstractItemModel.
Definition at line 197 of file qstringlistmodel.cpp.
 {
     if (count < 1 || row < 0 || row > rowCount(parent))
         return false;
     beginInsertRows(QModelIndex(), row, row + count - 1);
     for (int r = 0; r < count; ++r)
         lst.insert(row, QString());
     endInsertRows();
     return true;
 }
removeRows()
bool QStringListModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Removes count rows from the model, beginning at the given row.
The parent index of the rows is optional and is only used for consistency with QAbstractItemModel. By default, a null index is specified, indicating that the rows are removed in the top level of the model.
See also
QAbstractItemModel::removeRows()
Reimplemented from QAbstractItemModel.
Definition at line 223 of file qstringlistmodel.cpp.
 {
     if (count <= 0 || row < 0 || (row + count) > rowCount(parent))
         return false;
     beginRemoveRows(QModelIndex(), row, row + count - 1);
     for (int r = 0; r < count; ++r)
         lst.removeAt(row);
     endRemoveRows();
     return true;
 }
rowCount()
int QStringListModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows in the model.
This value corresponds to the number of items in the model's internal string list.
The optional parent argument is in most models used to specify the parent of the rows to be counted. Because this is a list if a valid parent is specified, the result will always be 0.
See also
insertRows(), removeRows(), QAbstractItemModel::rowCount()
Implements QAbstractItemModel.
Definition at line 122 of file qstringlistmodel.cpp.
Referenced by QFontListView::count(), insertRows(), and removeRows().
 {
     if (parent.isValid())
         return 0;
     return lst.count();
 }
setData()
bool QStringListModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Sets the data for the specified role in the item with the given index in the model, to the provided value.
The dataChanged() signal is emitted if the item is changed.
See also
Qt::ItemDataRole, data()
Reimplemented from QAbstractItemModel.
Definition at line 175 of file qstringlistmodel.cpp.
 {
     if (index.row() >= 0 && index.row() < lst.size()
         && (role == Qt::EditRole || role == Qt::DisplayRole)) {
         lst.replace(index.row(), value.toString());
         emit dataChanged(index, index);
         return true;
     }
     return false;
 }
setStringList()
void QStringListModel::setStringList (const QStringList & strings)
Sets the model's internal string list to strings.
The model will notify any attached views that its underlying data has changed.
See also
dataChanged()
Definition at line 294 of file qstringlistmodel.cpp.
Referenced by QScriptDebuggerLocalsWidgetPrivate::_q_onCompletionTaskFinished(), and QFontComboBoxPrivate::_q_updateModel().
 {
     emit beginResetModel();
     lst = strings;
     emit endResetModel();
 }
sort()
void QStringListModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 251 of file qstringlistmodel.cpp.
 {
     emit layoutAboutToBeChanged();
     QList<QPair<QString, int> > list;
     for (int i = 0; i < lst.count(); ++i)
         list.append(QPair<QString, int>(lst.at(i), i));
     if (order == Qt::AscendingOrder)
         qSort(list.begin(), list.end(), ascendingLessThan);
     else
         qSort(list.begin(), list.end(), decendingLessThan);
     lst.clear();
     QVector<int> forwarding(list.count());
     for (int i = 0; i < list.count(); ++i) {
         lst.append(list.at(i).first);
         forwarding[list.at(i).second] = i;
     }
     QModelIndexList oldList = persistentIndexList();
     QModelIndexList newList;
     for (int i = 0; i < oldList.count(); ++i)
         newList.append(index(forwarding.at(oldList.at(i).row()), 0));
     changePersistentIndexList(oldList, newList);
     emit layoutChanged();
 }
stringList()
QStringList QStringListModel::stringList () const
Returns the string list used by the model to store data.
Definition at line 283 of file qstringlistmodel.cpp.
Referenced by QFontListView::currentText(), and QFontListView::text().
 {
     return lst;
 }
supportedDropActions()
Qt::DropActions QStringListModel::supportedDropActions () const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 304 of file qstringlistmodel.cpp.
 {
     return QAbstractItemModel::supportedDropActions() | Qt::MoveAction;
 }
Properties
lst
QStringList QStringListModel::lst private
Definition at line 82 of file qstringlistmodel.h.
Referenced by data(), insertRows(), removeRows(), rowCount(), setData(), setStringList(), sort(), and stringList().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qstringlistmodel.h
/src/gui/itemviews/qstringlistmodel.cpp