Qt 4.8: QDeclarativeBehavior Class Reference
QDeclarativeBehavior Class Reference
#include <qdeclarativebehavior_p.h>
Signals
void enabledChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeAbstractAnimation * animation ()
bool enabled () const
QDeclarativeBehavior (QObject *parent=0)
void setAnimation (QDeclarativeAbstractAnimation *)
void setEnabled (bool enabled)
virtual void setTarget (const QDeclarativeProperty &)
Set the target property for the value interceptor.
virtual void write (const QVariant &value)
This method will be called when a new value is assigned to the property being intercepted.
~QDeclarativeBehavior ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueInterceptor
QDeclarativePropertyValueInterceptor ()
Constructs a QDeclarativePropertyValueInterceptor.
virtual ~QDeclarativePropertyValueInterceptor ()
Private Slots
void componentFinalized ()
void qtAnimationStateChanged (QAbstractAnimation::State, QAbstractAnimation::State)
Properties
QDeclarativeAbstractAnimation * animation
bool enabled
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 60 of file qdeclarativebehavior_p.h.
Constructors and Destructors
QDeclarativeBehavior()
QDeclarativeBehavior::QDeclarativeBehavior (QObject * parent = 0)
Definition at line 104 of file qdeclarativebehavior.cpp.
     : QObject(*(new QDeclarativeBehaviorPrivate), parent)
 {
 }
~QDeclarativeBehavior()
QDeclarativeBehavior::~QDeclarativeBehavior ()
Definition at line 109 of file qdeclarativebehavior.cpp.
 {
 }
Functions
animation()
QDeclarativeAbstractAnimation* QDeclarativeBehavior::animation ()
Referenced by setAnimation(), and ~QDeclarativeBehavior().
componentFinalized
void QDeclarativeBehavior::componentFinalized () private slot
Definition at line 233 of file qdeclarativebehavior.cpp.
 {
     Q_D(QDeclarativeBehavior);
     d->finalized = true;
 }
enabled()
bool QDeclarativeBehavior::enabled () const
Referenced by qtAnimationStateChanged(), and setEnabled().
enabledChanged
void QDeclarativeBehavior::enabledChanged () signal
Referenced by setEnabled().
qtAnimationStateChanged
void QDeclarativeBehavior::qtAnimationStateChanged (QAbstractAnimation::State newState, QAbstractAnimation::State) private slot
Definition at line 149 of file qdeclarativebehavior.cpp.
Referenced by setAnimation().
 {
     Q_D(QDeclarativeBehavior);
     if (!d->blockRunningChanged)
         d->animation->notifyRunningChanged(newState == QAbstractAnimation::Running);
 }
setAnimation()
void QDeclarativeBehavior::setAnimation (QDeclarativeAbstractAnimation * animation)
Definition at line 129 of file qdeclarativebehavior.cpp.
 {
     Q_D(QDeclarativeBehavior);
     if (d->animation) {
         qmlInfo(this) << tr("Cannot change the animation assigned to a Behavior.");
         return;
     }
     d->animation = animation;
     if (d->animation) {
         d->animation->setDefaultTarget(d->property);
         d->animation->setDisableUserControl();
         connect(d->animation->qtAnimation(),
                 SIGNAL(stateChanged(QAbstractAnimation::State,QAbstractAnimation::State)),
                 this,
                 SLOT(qtAnimationStateChanged(QAbstractAnimation::State,QAbstractAnimation::State)));
     }
 }
setEnabled()
void QDeclarativeBehavior::setEnabled (bool enabled)
Definition at line 175 of file qdeclarativebehavior.cpp.
 {
     Q_D(QDeclarativeBehavior);
     if (d->enabled == enabled)
         return;
     d->enabled = enabled;
     emit enabledChanged();
 }
setTarget()
void QDeclarativeBehavior::setTarget (const QDeclarativeProperty & property) virtual
Set the target property for the value interceptor.
This method will be called by the QML engine when assigning a value interceptor.
Implements QDeclarativePropertyValueInterceptor.
Definition at line 221 of file qdeclarativebehavior.cpp.
 {
     Q_D(QDeclarativeBehavior);
     d->property = property;
     d->currentValue = property.read();
     if (d->animation)
         d->animation->setDefaultTarget(property);
     QDeclarativeEnginePrivate *engPriv = QDeclarativeEnginePrivate::get(qmlEngine(this));
     engPriv->registerFinalizedParserStatusObject(this, this->metaObject()->indexOfSlot("componentFinalized()"));
 }
write()
void QDeclarativeBehavior::write (const QVariant & value) virtual
This method will be called when a new value is assigned to the property being intercepted.
Implements QDeclarativePropertyValueInterceptor.
Definition at line 184 of file qdeclarativebehavior.cpp.
 {
     Q_D(QDeclarativeBehavior);
     qmlExecuteDeferred(this);
     if (!d->animation || !d->enabled || !d->finalized) {
         QDeclarativePropertyPrivate::write(d->property, value, QDeclarativePropertyPrivate::BypassInterceptor | QDeclarativePropertyPrivate::DontRemoveBinding);
         d->targetValue = value;
         return;
     }
     if (d->animation->isRunning() && value == d->targetValue)
         return;
     d->currentValue = d->property.read();
     d->targetValue = value;
     if (d->animation->qtAnimation()->duration() != -1
             && d->animation->qtAnimation()->state() != QAbstractAnimation::Stopped) {
         d->blockRunningChanged = true;
         d->animation->qtAnimation()->stop();
     }
     QDeclarativeStateOperation::ActionList actions;
     QDeclarativeAction action;
     action.property = d->property;
     action.fromValue = d->currentValue;
     action.toValue = value;
     actions << action;
     QList<QDeclarativeProperty> after;
     d->animation->transition(actions, after, QDeclarativeAbstractAnimation::Forward);
     d->animation->qtAnimation()->start();
     d->blockRunningChanged = false;
     if (!after.contains(d->property))
         QDeclarativePropertyPrivate::write(d->property, value, QDeclarativePropertyPrivate::BypassInterceptor | QDeclarativePropertyPrivate::DontRemoveBinding);
 }
Properties
animation
QDeclarativeAbstractAnimation * QDeclarativeBehavior::animation private
Definition at line 67 of file qdeclarativebehavior_p.h.
enabled
bool QDeclarativeBehavior::enabled private
Definition at line 68 of file qdeclarativebehavior_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativebehavior_p.h
/src/declarative/util/qdeclarativebehavior.cpp