Qt 4.8: QPlainTextEditPrivate Class Reference
QPlainTextEditPrivate Class Reference
#include <qplaintextedit_p.h>
Public Functions
void _q_adjustScrollbars ()
void _q_cursorPositionChanged ()
void _q_modificationChanged (bool)
void _q_repaintContents (const QRectF &contentsRect)
void _q_verticalScrollbarActionTriggered (int action)
void append (const QString &text, Qt::TextFormat format=Qt::AutoText)
void ensureCursorVisible (bool center=false)
void ensureViewportLayouted ()
void ensureVisible (int position, bool center, bool forceCenter=false)
int horizontalOffset () const
void init (const QString &txt=QString())
QPoint mapToContents (const QPoint &point) const
void pageUpDown (QTextCursor::MoveOperation op, QTextCursor::MoveMode moveMode, bool moveCursor=true)
QPlainTextEditPrivate ()
void relayoutDocument ()
void sendControlEvent (QEvent *e)
void setTopBlock (int newTopBlock, int newTopLine, int dx=0)
void setTopLine (int visualTopLine, int dx=0)
void updateDefaultTextOption ()
void updateViewport ()
qreal verticalOffset (int topBlock, int topLine) const
qreal verticalOffset () const
Public Functions inherited from QAbstractScrollAreaPrivate
void _q_hslide (int)
void _q_showOrHideScrollBars ()
void _q_vslide (int)
virtual QPoint contentsOffset () const
void init ()
void layoutChildren ()
QAbstractScrollAreaPrivate ()
void replaceScrollBar (QScrollBar *scrollBar, Qt::Orientation orientation)
virtual void scrollBarPolicyChanged (Qt::Orientation, Qt::ScrollBarPolicy)
void setSingleFingerPanEnabled (bool on=true)
bool viewportEvent (QEvent *event)
Public Functions inherited from QFramePrivate
void init ()
QFramePrivate ()
void updateFrameWidth ()
Updated the frameWidth parameter.
void updateStyledFrameWidths ()
Updates the frame widths from the style.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QPoint autoScrollDragPos
QBasicTimer autoScrollTimer
uint backgroundVisible: 1
uint centerOnScroll: 1
uint clickCausedFocus: 1
QPlainTextEditControl * control
QPointer< QPlainTextDocumentLayout > documentLayoutPtr
uint inDrag: 1
QPlainTextEdit::LineWrapMode lineWrap
int originalOffsetY
qreal pageUpDownLastCursorY
bool pageUpDownLastCursorYIsValid
uint showCursorOnInitialShow: 1
bool tabChangesFocus
int topLine
qreal topLineFracture
QTextOption::WrapMode wordWrap
Public Variables inherited from QAbstractScrollAreaPrivate
int bottom
QRect cornerPaintingRect
QWidget * cornerWidget
QScrollBar * hbar
Qt::ScrollBarPolicy hbarpolicy
int left
QRect reverseCornerPaintingRect
int right
QAbstractScrollAreaScrollBarContainer * scrollBarContainers [Qt::Vertical+1]
bool singleFingerPanEnabled
int top
QScrollBar * vbar
Qt::ScrollBarPolicy vbarpolicy
QWidget * viewport
QScopedPointer< QObject > viewportFilter
int xoffset
int yoffset
Public Variables inherited from QFramePrivate
short bottomFrameWidth
int frameStyle
short frameWidth
QRect frect
short leftFrameWidth
short lineWidth
short midLineWidth
short rightFrameWidth
short topFrameWidth
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 111 of file qplaintextedit_p.h.
Constructors and Destructors
QPlainTextEditPrivate()
QPlainTextEditPrivate::QPlainTextEditPrivate ()
Definition at line 747 of file qplaintextedit.cpp.
     : control(0),
       tabChangesFocus(false),
       lineWrap(QPlainTextEdit::WidgetWidth),
       wordWrap(QTextOption::WrapAtWordBoundaryOrAnywhere),
       clickCausedFocus(0),topLine(0),topLineFracture(0),
       pageUpDownLastCursorYIsValid(false)
 {
     showCursorOnInitialShow = true;
     backgroundVisible = false;
     centerOnScroll = false;
     inDrag = false;
 }
Functions
_q_adjustScrollbars()
void QPlainTextEditPrivate::_q_adjustScrollbars ()
Definition at line 954 of file qplaintextedit.cpp.
Referenced by init().
 {
     Q_Q(QPlainTextEdit);
     QTextDocument *doc = control->document();
     QPlainTextDocumentLayout *documentLayout = qobject_cast<QPlainTextDocumentLayout*>(doc->documentLayout());
     Q_ASSERT(documentLayout);
     bool documentSizeChangedBlocked = documentLayout->priv()->blockDocumentSizeChanged;
     documentLayout->priv()->blockDocumentSizeChanged = true;
     qreal margin = doc->documentMargin();
     int vmax = 0;
     int vSliderLength = 0;
     if (!centerOnScroll && q->isVisible()) {
         QTextBlock block = doc->lastBlock();
         const qreal visible = viewport->rect().height() - margin - 1;
         qreal y = 0;
         int visibleFromBottom = 0;
         while (block.isValid()) {
             if (!block.isVisible()) {
                 block = block.previous();
                 continue;
             }
             y += documentLayout->blockBoundingRect(block).height();
             QTextLayout *layout = block.layout();
             int layoutLineCount = layout->lineCount();
             if (y > visible) {
                 int lineNumber = 0;
                 while (lineNumber < layoutLineCount) {
                     QTextLine line = layout->lineAt(lineNumber);
                     const QRectF lr = line.naturalTextRect();
                     if (lr.top() >= y - visible)
                         break;
                     ++lineNumber;
                 }
                 if (lineNumber < layoutLineCount)
                     visibleFromBottom += (layoutLineCount - lineNumber);
                 break;
             }
             visibleFromBottom += layoutLineCount;
             block = block.previous();
         }
         vmax = qMax(0, doc->lineCount() - visibleFromBottom);
         vSliderLength = visibleFromBottom;
     } else {
         vmax = qMax(0, doc->lineCount() - 1);
         vSliderLength = viewport->height() / q->fontMetrics().lineSpacing();
     }
     QSizeF documentSize = documentLayout->documentSize();
     vbar->setRange(0, qMax(0, vmax));
     vbar->setPageStep(vSliderLength);
     int visualTopLine = vmax;
     QTextBlock firstVisibleBlock = q->firstVisibleBlock();
     if (firstVisibleBlock.isValid())
         visualTopLine = firstVisibleBlock.firstLineNumber() + topLine;
     bool vbarSignalsBlocked = vbar->blockSignals(true);
     vbar->setValue(visualTopLine);
     vbar->blockSignals(vbarSignalsBlocked);
     hbar->setRange(0, (int)documentSize.width() - viewport->width());
     hbar->setPageStep(viewport->width());
     documentLayout->priv()->blockDocumentSizeChanged = documentSizeChangedBlocked;
     setTopLine(vbar->value());
 }
_q_cursorPositionChanged()
void QPlainTextEditPrivate::_q_cursorPositionChanged ()
Definition at line 450 of file qplaintextedit.cpp.
Referenced by init().
 {
     pageUpDownLastCursorYIsValid = false;
 #ifndef QT_NO_ACCESSIBILITY
     Q_Q(QPlainTextEdit);
     QAccessible::updateAccessibility(q, 0, QAccessible::TextCaretMoved);
 #endif
 }
_q_modificationChanged()
void QPlainTextEditPrivate::_q_modificationChanged (bool)
_q_repaintContents()
void QPlainTextEditPrivate::_q_repaintContents (const QRectF & contentsRect)
Definition at line 821 of file qplaintextedit.cpp.
Referenced by init().
 {
     Q_Q(QPlainTextEdit);
     if (!contentsRect.isValid()) {
         updateViewport();
         return;
     }
     const int xOffset = horizontalOffset();
     const int yOffset = (int)verticalOffset();
     const QRect visibleRect(xOffset, yOffset, viewport->width(), viewport->height());
     QRect r = contentsRect.adjusted(-1, -1, 1, 1).intersected(visibleRect).toAlignedRect();
     if (r.isEmpty())
         return;
     r.translate(-xOffset, -yOffset);
     viewport->update(r);
     emit q->updateRequest(r, 0);
 }
_q_verticalScrollbarActionTriggered()
void QPlainTextEditPrivate::_q_verticalScrollbarActionTriggered (int action)
Definition at line 459 of file qplaintextedit.cpp.
Referenced by init().
{
     if (action == QAbstractSlider::SliderPageStepAdd) {
         pageUpDown(QTextCursor::Down, QTextCursor::MoveAnchor, false);
     } else if (action == QAbstractSlider::SliderPageStepSub) {
         pageUpDown(QTextCursor::Up, QTextCursor::MoveAnchor, false);
     }
 }
append()
void QPlainTextEditPrivate::append (const QString & text, Qt::TextFormat format = Qt::AutoText)
Definition at line 2834 of file qplaintextedit.cpp.
 {
     Q_Q(QPlainTextEdit);
     QTextDocument *document = control->document();
     QPlainTextDocumentLayout *documentLayout = qobject_cast<QPlainTextDocumentLayout*>(document->documentLayout());
     Q_ASSERT(documentLayout);
     int maximumBlockCount = document->maximumBlockCount();
     if (maximumBlockCount)
         document->setMaximumBlockCount(0);
     const bool atBottom =  q->isVisible()
                            && (control->blockBoundingRect(document->lastBlock()).bottom() - verticalOffset()
                                <= viewport->rect().bottom());
     if (!q->isVisible())
         showCursorOnInitialShow = true;
     bool documentSizeChangedBlocked = documentLayout->priv()->blockDocumentSizeChanged;
     documentLayout->priv()->blockDocumentSizeChanged = true;
     if (format == Qt::RichText)
         control->appendHtml(text);
     else if (format == Qt::PlainText)
         control->appendPlainText(text);
     else
         control->append(text);
     if (maximumBlockCount > 0) {
         if (document->blockCount() > maximumBlockCount) {
             bool blockUpdate = false;
             if (control->topBlock) {
                 control->topBlock--;
                 blockUpdate = true;
                 emit q->updateRequest(viewport->rect(), 0);
             }
             bool updatesBlocked = documentLayout->priv()->blockUpdate;
             documentLayout->priv()->blockUpdate = blockUpdate;
             QTextCursor cursor(document);
             cursor.movePosition(QTextCursor::NextBlock, QTextCursor::KeepAnchor);
             cursor.removeSelectedText();
             documentLayout->priv()->blockUpdate = updatesBlocked;
         }
         document->setMaximumBlockCount(maximumBlockCount);
     }
     documentLayout->priv()->blockDocumentSizeChanged = documentSizeChangedBlocked;
     _q_adjustScrollbars();
     if (atBottom) {
         const bool needScroll =  !centerOnScroll
                                  || control->blockBoundingRect(document->lastBlock()).bottom() - verticalOffset()
                                  > viewport->rect().bottom();
         if (needScroll)
             vbar->setValue(vbar->maximum());
     }
 }
ensureCursorVisible()
void QPlainTextEditPrivate::ensureCursorVisible (bool center = false)
Definition at line 2920 of file qplaintextedit.cpp.
Referenced by pageUpDown().
 {
     Q_Q(QPlainTextEdit);
     QRect visible = viewport->rect();
     QRect cr = q->cursorRect();
     if (cr.top() < visible.top() || cr.bottom() > visible.bottom()) {
         ensureVisible(control->textCursor().position(), center);
     }
     const bool rtl = q->isRightToLeft();
     if (cr.left() < visible.left() || cr.right() > visible.right()) {
         int x = cr.center().x() + horizontalOffset() - visible.width()/2;
         hbar->setValue(rtl ? hbar->maximum() - x : x);
     }
 }
ensureViewportLayouted()
void QPlainTextEditPrivate::ensureViewportLayouted ()
Definition at line 1029 of file qplaintextedit.cpp.
 {
 }
ensureVisible()
void QPlainTextEditPrivate::ensureVisible (int position, bool center, bool forceCenter = false)
Definition at line 687 of file qplaintextedit.cpp.
{
     Q_Q(QPlainTextEdit);
     QRectF visible = QRectF(viewport->rect()).translated(-q->contentOffset());
     QTextBlock block = control->document()->findBlock(position);
     if (!block.isValid())
         return;
     QRectF br = control->blockBoundingRect(block);
     if (!br.isValid())
         return;
     QRectF lr = br;
     QTextLine line = block.layout()->lineForTextPosition(position - block.position());
     Q_ASSERT(line.isValid());
     lr = line.naturalTextRect().translated(br.topLeft());
     if (lr.bottom() >= visible.bottom() || (center && lr.top() < visible.top()) || forceCenter){
         qreal height = visible.height();
         if (center)
             height /= 2;
         qreal h = center ? line.naturalTextRect().center().y() : line.naturalTextRect().bottom();
         QTextBlock previousVisibleBlock = block;
         while (h < height && block.previous().isValid()) {
             previousVisibleBlock = block;
             do {
                 block = block.previous();
             } while (!block.isVisible() && block.previous().isValid());
             h += q->blockBoundingRect(block).height();
         }
         int l = 0;
         int lineCount = block.layout()->lineCount();
         qreal voffset = verticalOffset(block.blockNumber(), 0);
         while (l < lineCount) {
             QRectF lineRect = block.layout()->lineAt(l).naturalTextRect();
             if (h - voffset - lineRect.top() <= height)
                 break;
             ++l;
         }
         if (l >= lineCount) {
             block = previousVisibleBlock;
             l = 0;
         }
         setTopBlock(block.blockNumber(), l);
     } else if (lr.top() < visible.top()) {
         setTopBlock(block.blockNumber(), line.lineNumber());
     }
 }
horizontalOffset()
int QPlainTextEditPrivate::horizontalOffset () const inline
Definition at line 130 of file qplaintextedit_p.h.
Referenced by _q_repaintContents().
         { return (q_func()->isRightToLeft() ? (hbar->maximum() - hbar->value()) : hbar->value()); }
init()
void QPlainTextEditPrivate::init (const QString & txt = QString())
Definition at line 762 of file qplaintextedit.cpp.
 {
     Q_Q(QPlainTextEdit);
     control = new QPlainTextEditControl(q);
     QTextDocument *doc = new QTextDocument(control);
     QAbstractTextDocumentLayout *layout = new QPlainTextDocumentLayout(doc);
     doc->setDocumentLayout(layout);
     control->setDocument(doc);
     control->setPalette(q->palette());
     QObject::connect(vbar, SIGNAL(actionTriggered(int)), q, SLOT(_q_verticalScrollbarActionTriggered(int)));
     QObject::connect(control, SIGNAL(microFocusChanged()), q, SLOT(updateMicroFocus()));
     QObject::connect(control, SIGNAL(documentSizeChanged(QSizeF)), q, SLOT(_q_adjustScrollbars()));
     QObject::connect(control, SIGNAL(blockCountChanged(int)), q, SIGNAL(blockCountChanged(int)));
     QObject::connect(control, SIGNAL(updateRequest(QRectF)), q, SLOT(_q_repaintContents(QRectF)));
     QObject::connect(control, SIGNAL(modificationChanged(bool)), q, SIGNAL(modificationChanged(bool)));
     QObject::connect(control, SIGNAL(textChanged()), q, SIGNAL(textChanged()));
     QObject::connect(control, SIGNAL(undoAvailable(bool)), q, SIGNAL(undoAvailable(bool)));
     QObject::connect(control, SIGNAL(redoAvailable(bool)), q, SIGNAL(redoAvailable(bool)));
     QObject::connect(control, SIGNAL(copyAvailable(bool)), q, SIGNAL(copyAvailable(bool)));
     QObject::connect(control, SIGNAL(selectionChanged()), q, SIGNAL(selectionChanged()));
     QObject::connect(control, SIGNAL(cursorPositionChanged()), q, SLOT(_q_cursorPositionChanged()));
     QObject::connect(control, SIGNAL(cursorPositionChanged()), q, SIGNAL(cursorPositionChanged()));
     QObject::connect(control, SIGNAL(textChanged()), q, SLOT(updateMicroFocus()));
     // set a null page size initially to avoid any relayouting until the textedit
     // is shown. relayoutDocument() will take care of setting the page size to the
     // viewport dimensions later.
     doc->setTextWidth(-1);
     doc->documentLayout()->setPaintDevice(viewport);
     doc->setDefaultFont(q->font());
     if (!txt.isEmpty())
         control->setPlainText(txt);
     hbar->setSingleStep(20);
     vbar->setSingleStep(1);
     viewport->setBackgroundRole(QPalette::Base);
     q->setAcceptDrops(true);
     q->setFocusPolicy(Qt::WheelFocus);
     q->setAttribute(Qt::WA_KeyCompression);
     q->setAttribute(Qt::WA_InputMethodEnabled);
 #ifndef QT_NO_CURSOR
     viewport->setCursor(Qt::IBeamCursor);
 #endif
     originalOffsetY = 0;
 #ifdef Q_WS_WIN
     setSingleFingerPanEnabled(true);
 #endif
 }
mapToContents()
QPoint QPlainTextEditPrivate::mapToContents (const QPoint & point) const inline
Definition at line 120 of file qplaintextedit_p.h.
         { return QPoint(point.x() + horizontalOffset(), point.y() + verticalOffset()); }
pageUpDown()
void QPlainTextEditPrivate::pageUpDown (QTextCursor::MoveOperation op, QTextCursor::MoveMode moveMode, bool moveCursor = true)
Definition at line 841 of file qplaintextedit.cpp.
 {
     Q_Q(QPlainTextEdit);
     QTextCursor cursor = control->textCursor();
     if (moveCursor) {
         ensureCursorVisible();
         if (!pageUpDownLastCursorYIsValid)
             pageUpDownLastCursorY = control->cursorRect(cursor).top() - verticalOffset();
     }
     qreal lastY = pageUpDownLastCursorY;
     if (op == QTextCursor::Down) {
         QRectF visible = QRectF(viewport->rect()).translated(-q->contentOffset());
         QTextBlock firstVisibleBlock = q->firstVisibleBlock();
         QTextBlock block = firstVisibleBlock;
         QRectF br = q->blockBoundingRect(block);
         qreal h = 0;
         int atEnd = false;
         while (h + br.height() <= visible.bottom()) {
             if (!block.next().isValid()) {
                 atEnd = true;
                 lastY = visible.bottom(); // set cursor to last line
                 break;
             }
             h += br.height();
             block = block.next();
             br = q->blockBoundingRect(block);
         }
         if (!atEnd) {
             int line = 0;
             qreal diff = visible.bottom() - h;
             int lineCount = block.layout()->lineCount();
             while (line < lineCount - 1) {
                 if (block.layout()->lineAt(line).naturalTextRect().bottom() > diff) {
                     // the first line that did not completely fit the screen
                     break;
                 }
                 ++line;
             }
             setTopBlock(block.blockNumber(), line);
         }
         if (moveCursor) {
             // move using movePosition to keep the cursor's x
             lastY += verticalOffset();
             bool moved = false;
             do {
                 moved = cursor.movePosition(op, moveMode);
             } while (moved && control->cursorRect(cursor).top() < lastY);
         }
     } else if (op == QTextCursor::Up) {
         QRectF visible = QRectF(viewport->rect()).translated(-q->contentOffset());
         visible.translate(0, -visible.height()); // previous page
         QTextBlock block = q->firstVisibleBlock();
         qreal h = 0;
         while (h >= visible.top()) {
             if (!block.previous().isValid()) {
                 if (control->topBlock == 0 && topLine == 0) {
                     lastY = 0; // set cursor to first line
                 }
                 break;
             }
             block = block.previous();
             QRectF br = q->blockBoundingRect(block);
             h -= br.height();
         }
         int line = 0;
         if (block.isValid()) {
             qreal diff = visible.top() - h;
             int lineCount = block.layout()->lineCount();
             while (line < lineCount) {
                 if (block.layout()->lineAt(line).naturalTextRect().top() >= diff)
                     break;
                 ++line;
             }
             if (line == lineCount) {
                 if (block.next().isValid() && block.next() != q->firstVisibleBlock()) {
                     block = block.next();
                     line = 0;
                 } else {
                     --line;
                 }
             }
         }
         setTopBlock(block.blockNumber(), line);
         if (moveCursor) {
             cursor.setVisualNavigation(true);
             // move using movePosition to keep the cursor's x
             lastY += verticalOffset();
             bool moved = false;
             do {
                 moved = cursor.movePosition(op, moveMode);
             } while (moved && control->cursorRect(cursor).top() > lastY);
         }
     }
     if (moveCursor) {
         control->setTextCursor(cursor);
         pageUpDownLastCursorYIsValid = true;
     }
 }
relayoutDocument()
void QPlainTextEditPrivate::relayoutDocument ()
Definition at line 1816 of file qplaintextedit.cpp.
 {
     QTextDocument *doc = control->document();
     QPlainTextDocumentLayout *documentLayout = qobject_cast<QPlainTextDocumentLayout*>(doc->documentLayout());
     Q_ASSERT(documentLayout);
     documentLayoutPtr = documentLayout;
     int width = viewport->width();
     if (documentLayout->priv()->mainViewPrivate == 0
         || documentLayout->priv()->mainViewPrivate == this
         || width > documentLayout->textWidth()) {
         documentLayout->priv()->mainViewPrivate = this;
         documentLayout->setTextWidth(width);
     }
 }
sendControlEvent()
void QPlainTextEditPrivate::sendControlEvent (QEvent * e) inline
Definition at line 135 of file qplaintextedit_p.h.
         { control->processEvent(e, QPointF(horizontalOffset(), verticalOffset()), viewport); }
setTopBlock()
void QPlainTextEditPrivate::setTopBlock (int newTopBlock, int newTopLine, int dx = 0)
Definition at line 631 of file qplaintextedit.cpp.
Referenced by pageUpDown().
 {
     Q_Q(QPlainTextEdit);
     blockNumber = qMax(0, blockNumber);
     lineNumber = qMax(0, lineNumber);
     QTextDocument *doc = control->document();
     QTextBlock block = doc->findBlockByNumber(blockNumber);
     int newTopLine = block.firstLineNumber() + lineNumber;
     int maxTopLine = vbar->maximum();
     if (newTopLine > maxTopLine) {
         block = doc->findBlockByLineNumber(maxTopLine);
         blockNumber = block.blockNumber();
         lineNumber = maxTopLine - block.firstLineNumber();
     }
     bool vbarSignalsBlocked = vbar->blockSignals(true);
     vbar->setValue(newTopLine);
     vbar->blockSignals(vbarSignalsBlocked);
     if (!dx && blockNumber == control->topBlock && lineNumber == topLine)
         return;
     if (viewport->updatesEnabled() && viewport->isVisible()) {
         int dy = 0;
         if (doc->findBlockByNumber(control->topBlock).isValid()) {
             qreal realdy = -q->blockBoundingGeometry(block).y()
                     + verticalOffset() - verticalOffset(blockNumber, lineNumber);
             dy = (int)realdy;
             topLineFracture = realdy - dy;
         }
         control->topBlock = blockNumber;
         topLine = lineNumber;
         bool vbarSignalsBlocked = vbar->blockSignals(true);
         vbar->setValue(block.firstLineNumber() + lineNumber);
         vbar->blockSignals(vbarSignalsBlocked);
         if (dx || dy) {
             viewport->scroll(q->isRightToLeft() ? -dx : dx, dy);
         } else {
             viewport->update();
             topLineFracture = 0;
         }
         emit q->updateRequest(viewport->rect(), dy);
     } else {
         control->topBlock = blockNumber;
         topLine = lineNumber;
         topLineFracture = 0;
     }
 }
setTopLine()
void QPlainTextEditPrivate::setTopLine (int visualTopLine, int dx = 0)
Definition at line 622 of file qplaintextedit.cpp.
Referenced by _q_adjustScrollbars().
 {
     QTextDocument *doc = control->document();
     QTextBlock block = doc->findBlockByLineNumber(visualTopLine);
     int blockNumber = block.blockNumber();
     int lineNumber = visualTopLine - block.firstLineNumber();
     setTopBlock(blockNumber, lineNumber, dx);
 }
updateDefaultTextOption()
void QPlainTextEditPrivate::updateDefaultTextOption ()
Definition at line 1979 of file qplaintextedit.cpp.
 {
     QTextDocument *doc = control->document();
     QTextOption opt = doc->defaultTextOption();
     QTextOption::WrapMode oldWrapMode = opt.wrapMode();
     if (lineWrap == QPlainTextEdit::NoWrap)
         opt.setWrapMode(QTextOption::NoWrap);
     else
         opt.setWrapMode(wordWrap);
     if (opt.wrapMode() != oldWrapMode)
         doc->setDefaultTextOption(opt);
 }
updateViewport()
void QPlainTextEditPrivate::updateViewport ()
Definition at line 740 of file qplaintextedit.cpp.
Referenced by _q_repaintContents().
 {
     Q_Q(QPlainTextEdit);
     viewport->update();
     emit q->updateRequest(viewport->rect(), 0);
 }
verticalOffset() [1/2]
qreal QPlainTextEditPrivate::verticalOffset (int topBlock, int topLine) const
Definition at line 487 of file qplaintextedit.cpp.
 {
     qreal offset = 0;
     QTextDocument *doc = control->document();
     if (topLine) {
         QTextBlock currentBlock = doc->findBlockByNumber(topBlock);
         QPlainTextDocumentLayout *documentLayout = qobject_cast<QPlainTextDocumentLayout*>(doc->documentLayout());
         Q_ASSERT(documentLayout);
         QRectF r = documentLayout->blockBoundingRect(currentBlock);
         Q_UNUSED(r);
         QTextLayout *layout = currentBlock.layout();
         if (layout && topLine <= layout->lineCount()) {
             QTextLine line = layout->lineAt(topLine - 1);
             const QRectF lr = line.naturalTextRect();
             offset = lr.bottom();
         }
     }
     if (topBlock == 0 && topLine == 0)
         offset -= doc->documentMargin(); // top margin
     return offset;
 }
verticalOffset() [2/2]
qreal QPlainTextEditPrivate::verticalOffset () const
Definition at line 511 of file qplaintextedit.cpp.
Referenced by _q_repaintContents(), and pageUpDown().
{
     return verticalOffset(control->topBlock, topLine) + topLineFracture;
 }
Properties
autoScrollDragPos
QPoint QPlainTextEditPrivate::autoScrollDragPos
Definition at line 145 of file qplaintextedit_p.h.
autoScrollTimer
QBasicTimer QPlainTextEditPrivate::autoScrollTimer
Definition at line 144 of file qplaintextedit_p.h.
backgroundVisible
uint QPlainTextEditPrivate::backgroundVisible
Definition at line 151 of file qplaintextedit_p.h.
Referenced by QPlainTextEditPrivate().
centerOnScroll
uint QPlainTextEditPrivate::centerOnScroll
Definition at line 152 of file qplaintextedit_p.h.
Referenced by _q_adjustScrollbars(), and QPlainTextEditPrivate().
clickCausedFocus
uint QPlainTextEditPrivate::clickCausedFocus
Definition at line 154 of file qplaintextedit_p.h.
control
QPlainTextEditControl* QPlainTextEditPrivate::control
Definition at line 140 of file qplaintextedit_p.h.
Referenced by _q_adjustScrollbars(), init(), and pageUpDown().
documentLayoutPtr
QPointer<QPlainTextDocumentLayout> QPlainTextEditPrivate::documentLayoutPtr
Definition at line 166 of file qplaintextedit_p.h.
inDrag
uint QPlainTextEditPrivate::inDrag
Definition at line 153 of file qplaintextedit_p.h.
Referenced by QPlainTextEditPrivate().
lineWrap
QPlainTextEdit::LineWrapMode QPlainTextEditPrivate::lineWrap
Definition at line 147 of file qplaintextedit_p.h.
originalOffsetY
int QPlainTextEditPrivate::originalOffsetY
Definition at line 181 of file qplaintextedit_p.h.
Referenced by init().
pageUpDownLastCursorY
qreal QPlainTextEditPrivate::pageUpDownLastCursorY
Definition at line 170 of file qplaintextedit_p.h.
Referenced by pageUpDown().
pageUpDownLastCursorYIsValid
bool QPlainTextEditPrivate::pageUpDownLastCursorYIsValid
Definition at line 171 of file qplaintextedit_p.h.
Referenced by pageUpDown().
showCursorOnInitialShow
uint QPlainTextEditPrivate::showCursorOnInitialShow
Definition at line 150 of file qplaintextedit_p.h.
Referenced by QPlainTextEditPrivate().
tabChangesFocus
bool QPlainTextEditPrivate::tabChangesFocus
Definition at line 142 of file qplaintextedit_p.h.
topLine
int QPlainTextEditPrivate::topLine
Definition at line 156 of file qplaintextedit_p.h.
Referenced by _q_adjustScrollbars(), and pageUpDown().
topLineFracture
qreal QPlainTextEditPrivate::topLineFracture
Definition at line 157 of file qplaintextedit_p.h.
wordWrap
QTextOption::WrapMode QPlainTextEditPrivate::wordWrap
Definition at line 148 of file qplaintextedit_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qplaintextedit_p.h
/src/gui/widgets/qplaintextedit.cpp