Qt 4.8: QXlibStatic Class Reference
QXlibStatic Class Reference
#include <qxlibstatic.h>
Public Types
enum X11Atom {
WM_PROTOCOLS, WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING,
_NET_WM_CONTEXT_HELP, _NET_WM_SYNC_REQUEST, _NET_WM_SYNC_REQUEST_COUNTER, WM_STATE,
WM_CHANGE_STATE, WM_CLIENT_LEADER, WM_WINDOW_ROLE, SM_CLIENT_ID,
CLIPBOARD, INCR, TARGETS, MULTIPLE,
TIMESTAMP, SAVE_TARGETS, CLIP_TEMPORARY, _QT_SELECTION,
_QT_CLIPBOARD_SENTINEL, _QT_SELECTION_SENTINEL, CLIPBOARD_MANAGER, RESOURCE_MANAGER,
_XSETROOT_ID, _QT_SCROLL_DONE, _QT_INPUT_ENCODING, _MOTIF_WM_HINTS,
DTWM_IS_RUNNING, ENLIGHTENMENT_DESKTOP, _DT_SAVE_MODE, _SGI_DESKS_MANAGER,
_NET_SUPPORTED, _NET_VIRTUAL_ROOTS, _NET_WORKAREA, _NET_MOVERESIZE_WINDOW,
_NET_WM_MOVERESIZE, _NET_WM_NAME, _NET_WM_ICON_NAME, _NET_WM_ICON,
_NET_WM_PID, _NET_WM_WINDOW_OPACITY, _NET_WM_STATE, _NET_WM_STATE_ABOVE,
_NET_WM_STATE_BELOW, _NET_WM_STATE_FULLSCREEN, _NET_WM_STATE_MAXIMIZED_HORZ, _NET_WM_STATE_MAXIMIZED_VERT,
_NET_WM_STATE_MODAL, _NET_WM_STATE_STAYS_ON_TOP, _NET_WM_STATE_DEMANDS_ATTENTION, _NET_WM_USER_TIME,
_NET_WM_USER_TIME_WINDOW, _NET_WM_FULL_PLACEMENT, _NET_WM_WINDOW_TYPE, _NET_WM_WINDOW_TYPE_DESKTOP,
_NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_TOOLBAR, _NET_WM_WINDOW_TYPE_MENU, _NET_WM_WINDOW_TYPE_UTILITY,
_NET_WM_WINDOW_TYPE_SPLASH, _NET_WM_WINDOW_TYPE_DIALOG, _NET_WM_WINDOW_TYPE_DROPDOWN_MENU, _NET_WM_WINDOW_TYPE_POPUP_MENU,
_NET_WM_WINDOW_TYPE_TOOLTIP, _NET_WM_WINDOW_TYPE_NOTIFICATION, _NET_WM_WINDOW_TYPE_COMBO, _NET_WM_WINDOW_TYPE_DND,
_NET_WM_WINDOW_TYPE_NORMAL, _KDE_NET_WM_WINDOW_TYPE_OVERRIDE, _KDE_NET_WM_FRAME_STRUT, _NET_STARTUP_INFO,
_NET_STARTUP_INFO_BEGIN, _NET_SUPPORTING_WM_CHECK, _NET_WM_CM_S0, _NET_SYSTEM_TRAY_VISUAL,
_NET_ACTIVE_WINDOW, COMPOUND_TEXT, TEXT, UTF8_STRING,
XdndEnter, XdndPosition, XdndStatus, XdndLeave,
XdndDrop, XdndFinished, XdndTypelist, XdndActionList,
XdndSelection, XdndAware, XdndProxy, XdndActionCopy,
XdndActionLink, XdndActionMove, XdndActionPrivate, _MOTIF_DRAG_AND_DROP_MESSAGE,
_MOTIF_DRAG_INITIATOR_INFO, _MOTIF_DRAG_RECEIVER_INFO, _MOTIF_DRAG_WINDOW, _MOTIF_DRAG_TARGETS,
XmTRANSFER_SUCCESS, XmTRANSFER_FAILURE, _XKB_RULES_NAMES, _XEMBED,
_XEMBED_INFO, XWacomStylus, XWacomCursor, XWacomEraser,
XTabletStylus, XTabletEraser, NPredefinedAtoms, _QT_SETTINGS_TIMESTAMP = NPredefinedAtoms,
NAtoms
}
Static Public Functions
static Atom atom (X11Atom atom)
static bool isSupportedByWM (Atom atom)
static QImage qimageFromXImage (XImage *xi)
static bool useXFixes ()
static int xFixesEventBase ()
static PtrXFixesSelectSelectionInput xFixesSelectSelectionInput ()
Detailed Description
Definition at line 239 of file qxlibstatic.h.
Enumerations
X11Atom
enum QXlibStatic::X11Atom
Enumerator
WM_PROTOCOLS
WM_DELETE_WINDOW
WM_TAKE_FOCUS
_NET_WM_PING
_NET_WM_CONTEXT_HELP
_NET_WM_SYNC_REQUEST
_NET_WM_SYNC_REQUEST_COUNTER
WM_STATE
WM_CHANGE_STATE
WM_CLIENT_LEADER
WM_WINDOW_ROLE
SM_CLIENT_ID
CLIPBOARD
INCR
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
CLIP_TEMPORARY
_QT_SELECTION
_QT_CLIPBOARD_SENTINEL
_QT_SELECTION_SENTINEL
CLIPBOARD_MANAGER
RESOURCE_MANAGER
_XSETROOT_ID
_QT_SCROLL_DONE
_QT_INPUT_ENCODING
_MOTIF_WM_HINTS
DTWM_IS_RUNNING
ENLIGHTENMENT_DESKTOP
_DT_SAVE_MODE
_SGI_DESKS_MANAGER
_NET_SUPPORTED
_NET_VIRTUAL_ROOTS
_NET_WORKAREA
_NET_MOVERESIZE_WINDOW
_NET_WM_MOVERESIZE
_NET_WM_NAME
_NET_WM_ICON_NAME
_NET_WM_ICON
_NET_WM_PID
_NET_WM_WINDOW_OPACITY
_NET_WM_STATE
_NET_WM_STATE_ABOVE
_NET_WM_STATE_BELOW
_NET_WM_STATE_FULLSCREEN
_NET_WM_STATE_MAXIMIZED_HORZ
_NET_WM_STATE_MAXIMIZED_VERT
_NET_WM_STATE_MODAL
_NET_WM_STATE_STAYS_ON_TOP
_NET_WM_STATE_DEMANDS_ATTENTION
_NET_WM_USER_TIME
_NET_WM_USER_TIME_WINDOW
_NET_WM_FULL_PLACEMENT
_NET_WM_WINDOW_TYPE
_NET_WM_WINDOW_TYPE_DESKTOP
_NET_WM_WINDOW_TYPE_DOCK
_NET_WM_WINDOW_TYPE_TOOLBAR
_NET_WM_WINDOW_TYPE_MENU
_NET_WM_WINDOW_TYPE_UTILITY
_NET_WM_WINDOW_TYPE_SPLASH
_NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_WINDOW_TYPE_DROPDOWN_MENU
_NET_WM_WINDOW_TYPE_POPUP_MENU
_NET_WM_WINDOW_TYPE_TOOLTIP
_NET_WM_WINDOW_TYPE_NOTIFICATION
_NET_WM_WINDOW_TYPE_COMBO
_NET_WM_WINDOW_TYPE_DND
_NET_WM_WINDOW_TYPE_NORMAL
_KDE_NET_WM_WINDOW_TYPE_OVERRIDE
_KDE_NET_WM_FRAME_STRUT
_NET_STARTUP_INFO
_NET_STARTUP_INFO_BEGIN
_NET_SUPPORTING_WM_CHECK
_NET_WM_CM_S0
_NET_SYSTEM_TRAY_VISUAL
_NET_ACTIVE_WINDOW
COMPOUND_TEXT
TEXT
UTF8_STRING
XdndEnter
XdndPosition
XdndStatus
XdndLeave
XdndDrop
XdndFinished
XdndTypelist
XdndActionList
XdndSelection
XdndAware
XdndProxy
XdndActionCopy
XdndActionLink
XdndActionMove
XdndActionPrivate
_MOTIF_DRAG_AND_DROP_MESSAGE
_MOTIF_DRAG_INITIATOR_INFO
_MOTIF_DRAG_RECEIVER_INFO
_MOTIF_DRAG_WINDOW
_MOTIF_DRAG_TARGETS
XmTRANSFER_SUCCESS
XmTRANSFER_FAILURE
_XKB_RULES_NAMES
_XEMBED
_XEMBED_INFO
XWacomStylus
XWacomCursor
XWacomEraser
XTabletStylus
XTabletEraser
NPredefinedAtoms
_QT_SETTINGS_TIMESTAMP
NAtoms
Definition at line 242 of file qxlibstatic.h.
                  {
         // window-manager <-> client protocols
         WM_PROTOCOLS,
         WM_DELETE_WINDOW,
         WM_TAKE_FOCUS,
         _NET_WM_PING,
         _NET_WM_CONTEXT_HELP,
         _NET_WM_SYNC_REQUEST,
         _NET_WM_SYNC_REQUEST_COUNTER,
         // ICCCM window state
         WM_STATE,
         WM_CHANGE_STATE,
         // Session management
         WM_CLIENT_LEADER,
         WM_WINDOW_ROLE,
         SM_CLIENT_ID,
         // Clipboard
         CLIPBOARD,
         INCR,
         TARGETS,
         MULTIPLE,
         TIMESTAMP,
         SAVE_TARGETS,
         CLIP_TEMPORARY,
         _QT_SELECTION,
         _QT_CLIPBOARD_SENTINEL,
         _QT_SELECTION_SENTINEL,
         CLIPBOARD_MANAGER,
         RESOURCE_MANAGER,
         _XSETROOT_ID,
         _QT_SCROLL_DONE,
         _QT_INPUT_ENCODING,
         _MOTIF_WM_HINTS,
         DTWM_IS_RUNNING,
         ENLIGHTENMENT_DESKTOP,
         _DT_SAVE_MODE,
         _SGI_DESKS_MANAGER,
         // EWMH (aka NETWM)
         _NET_SUPPORTED,
         _NET_VIRTUAL_ROOTS,
         _NET_WORKAREA,
         _NET_MOVERESIZE_WINDOW,
         _NET_WM_MOVERESIZE,
         _NET_WM_NAME,
         _NET_WM_ICON_NAME,
         _NET_WM_ICON,
         _NET_WM_PID,
         _NET_WM_WINDOW_OPACITY,
         _NET_WM_STATE,
         _NET_WM_STATE_ABOVE,
         _NET_WM_STATE_BELOW,
         _NET_WM_STATE_FULLSCREEN,
         _NET_WM_STATE_MAXIMIZED_HORZ,
         _NET_WM_STATE_MAXIMIZED_VERT,
         _NET_WM_STATE_MODAL,
         _NET_WM_STATE_STAYS_ON_TOP,
         _NET_WM_STATE_DEMANDS_ATTENTION,
         _NET_WM_USER_TIME,
         _NET_WM_USER_TIME_WINDOW,
         _NET_WM_FULL_PLACEMENT,
         _NET_WM_WINDOW_TYPE,
         _NET_WM_WINDOW_TYPE_DESKTOP,
         _NET_WM_WINDOW_TYPE_DOCK,
         _NET_WM_WINDOW_TYPE_TOOLBAR,
         _NET_WM_WINDOW_TYPE_MENU,
         _NET_WM_WINDOW_TYPE_UTILITY,
         _NET_WM_WINDOW_TYPE_SPLASH,
         _NET_WM_WINDOW_TYPE_DIALOG,
         _NET_WM_WINDOW_TYPE_DROPDOWN_MENU,
         _NET_WM_WINDOW_TYPE_POPUP_MENU,
         _NET_WM_WINDOW_TYPE_TOOLTIP,
         _NET_WM_WINDOW_TYPE_NOTIFICATION,
         _NET_WM_WINDOW_TYPE_COMBO,
         _NET_WM_WINDOW_TYPE_DND,
         _NET_WM_WINDOW_TYPE_NORMAL,
         _KDE_NET_WM_WINDOW_TYPE_OVERRIDE,
         _KDE_NET_WM_FRAME_STRUT,
         _NET_STARTUP_INFO,
         _NET_STARTUP_INFO_BEGIN,
         _NET_SUPPORTING_WM_CHECK,
         _NET_WM_CM_S0,
         _NET_SYSTEM_TRAY_VISUAL,
         _NET_ACTIVE_WINDOW,
         // Property formats
         COMPOUND_TEXT,
         TEXT,
         UTF8_STRING,
         // Xdnd
         XdndEnter,
         XdndPosition,
         XdndStatus,
         XdndLeave,
         XdndDrop,
         XdndFinished,
         XdndTypelist,
         XdndActionList,
         XdndSelection,
         XdndAware,
         XdndProxy,
         XdndActionCopy,
         XdndActionLink,
         XdndActionMove,
         XdndActionPrivate,
         // Motif DND
         _MOTIF_DRAG_AND_DROP_MESSAGE,
         _MOTIF_DRAG_INITIATOR_INFO,
         _MOTIF_DRAG_RECEIVER_INFO,
         _MOTIF_DRAG_WINDOW,
         _MOTIF_DRAG_TARGETS,
         XmTRANSFER_SUCCESS,
         XmTRANSFER_FAILURE,
         // Xkb
         _XKB_RULES_NAMES,
         // XEMBED
         _XEMBED,
         _XEMBED_INFO,
         XWacomStylus,
         XWacomCursor,
         XWacomEraser,
         XTabletStylus,
         XTabletEraser,
         NPredefinedAtoms,
         _QT_SETTINGS_TIMESTAMP = NPredefinedAtoms,
         NAtoms
     };
Functions
atom()
Atom QXlibStatic::atom (QXlibStatic::X11Atom atom) static
Definition at line 477 of file qxlibstatic.cpp.
Referenced by checkForClipboardEvents(), QXlibClipboard::clipboardReadProperty(), QXlibClipboardMime::formats_sys(), QXlibClipboard::getDataInFormat(), QXlibWindow::getMWMHints(), QXlibWindow::getNetWmState(), QXlibScreen::handleEvent(), QXlibClipboard::handleSelectionRequest(), QXlibMime::mimeAtomForFormat(), QXlibMime::mimeAtomsForFormat(), QXlibMime::mimeAtomToString(), QXlibMime::mimeConvertToFormat(), QXlibClipboard::mimeData(), QXlibMime::mimeDataForAtom(), QXlibMime::mimeFormatsForAtom(), QXlibClipboardMime::QXlibClipboardMime(), QXlibWindow::QXlibWindow(), QXlibClipboard::sendSelection(), QXlibClipboard::sendTargetsSelection(), QXlibClipboard::setMimeData(), QXlibWindow::setMWMHints(), and QXlibWindow::setWindowFlags().
 {
     return qTestLiteStaticInfoPrivate()->atom(atom);
 }
isSupportedByWM()
bool QXlibStatic::isSupportedByWM (Atom atom) static
Definition at line 482 of file qxlibstatic.cpp.
 {
     return qTestLiteStaticInfoPrivate()->isSupportedByWM(atom);
 }
qimageFromXImage()
QImage QXlibStatic::qimageFromXImage (XImage * xi) static
Definition at line 507 of file qxlibstatic.cpp.
Referenced by QXlibMime::mimeConvertToFormat().
 {
     return qTestLiteStaticInfoPrivate()->qimageFromXImage(xi);
 }
useXFixes()
bool QXlibStatic::useXFixes () static
Definition at line 487 of file qxlibstatic.cpp.
 {
     return qTestLiteStaticInfoPrivate()->useXFixes();
 }
xFixesEventBase()
int QXlibStatic::xFixesEventBase () static
Definition at line 492 of file qxlibstatic.cpp.
 {
     return qTestLiteStaticInfoPrivate()->xFixesEventBase();
 }
xFixesSelectSelectionInput()
PtrXFixesSelectSelectionInput QXlibStatic::xFixesSelectSelectionInput () static
Definition at line 498 of file qxlibstatic.cpp.
 {
     qDebug() << qTestLiteStaticInfoPrivate()->useXFixes();
     if (!qTestLiteStaticInfoPrivate()->useXFixes())
         return 0;
     return qTestLiteStaticInfoPrivate()->xFixesSelectSelectionInput();
 }
The documentation for this class was generated from the following files:
/src/plugins/platforms/xlib/qxlibstatic.h
/src/plugins/platforms/xlib/qxlibstatic.cpp