Qt 4.8: QPatternist::Cardinality Class Reference
QPatternist::Cardinality Class Reference
Represents a cardinality, a possible , often represented by occurrence indicators.
#include <qcardinality_p.h>
Public Types
typedef qint32 Count
enum CustomizeDisplayName { IncludeExplanation = 1, ExcludeExplanation }
Public Functions
bool allowsEmpty () const
bool allowsMany () const
bool canMatch (const Cardinality &other) const
Cardinality (const Cardinality &other)
Cardinality ()
QString displayName (const CustomizeDisplayName explanation) const
bool isEmpty () const
bool isExact () const
bool isExactlyOne () const
bool isMatch (const Cardinality &other) const
bool isOneOrMore () const
bool isZeroOrOne () const
Count maximum () const
Count minimum () const
Cardinality operator & (const Cardinality &other) const
bool operator!= (const Cardinality &other) const
Cardinality operator* (const Cardinality &other) const
Cardinality operator+ (const Cardinality &other) const
Cardinality & operator+= (const Cardinality &other)
Cardinality & operator= (const Cardinality &other)
bool operator== (const Cardinality &other) const
Cardinality operator| (const Cardinality &other) const
Cardinality & operator|= (const Cardinality &other)
Cardinality toWithoutMany () const
Static Public Functions
static Cardinality empty ()
static Cardinality exactlyOne ()
static Cardinality fromCount (const Count count)
static Cardinality fromExact (const Count count)
static Cardinality fromRange (const Count minimum, const Count maximum)
static Cardinality oneOrMore ()
static Cardinality twoOrMore ()
static Cardinality zeroOrMore ()
static Cardinality zeroOrOne ()
Private Functions
Cardinality (const Count min, const Count max)
Properties
Count m_max
Count m_min
Detailed Description
Represents a cardinality, a possible , often represented by occurrence indicators.
As opposed to the cardinality concept in the XQuery/XPath specifications, which only allows cardinalities to be expressed with kleene operators, this representation allows ranges. For example, the cardinality 10-11, describes a sequence containing ten or eleven items, inclusive.
See also
ItemType
SequenceType
XML Path Language (XPath) 2.0, The EBNF grammar for SequenceType
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 80 of file qcardinality_p.h.
Typedefs
Count
typedef qint32 QPatternist::Cardinality::Count
This integer type, is what Cardinality uses for representing its ranges.
Definition at line 86 of file qcardinality_p.h.
Enumerations
CustomizeDisplayName
enum QPatternist::Cardinality::CustomizeDisplayName
Used with displayName(), and specifies how a display name for a Cardinality should be.
Enumerator
IncludeExplanation
Includes a describing string in the return value of displayName().
ExcludeExplanation
Excludes a describing string in the return value of displayName().
Definition at line 92 of file qcardinality_p.h.
         {
             IncludeExplanation  = 1,
             ExcludeExplanation
         };
Constructors and Destructors
Cardinality() [1/3]
QPatternist::Cardinality::Cardinality (const Cardinality & other) inline
A traditional copy constructor. This Cardinality becomes identical to other.
Definition at line 109 of file qcardinality_p.h.
                                                      : m_min(other.m_min),
                                                        m_max(other.m_max)
         {
         }
Cardinality() [2/3]
QPatternist::Cardinality::Cardinality () inline
This default constructor constructs an invalid Cardinality. Using its operators and members yields undefined results. A value must first be assigned to it by creating a Cardinality with fromRange(), fromCount(), or one of the predefined cardinalities such as empty() or oneOrMore().
Definition at line 120 of file qcardinality_p.h.
Referenced by empty(), exactlyOne(), fromCount(), fromExact(), fromRange(), oneOrMore(), operator &(), operator*(), operator+(), operator|(), toWithoutMany(), twoOrMore(), zeroOrMore(), and zeroOrOne().
                              : m_min(-1), m_max(0)
         {
         }
Cardinality() [3/3]
QPatternist::Cardinality::Cardinality (const Count min, const Count max) inline private
Definition at line 528 of file qcardinality_p.h.
                                                              : m_min(min),
                                                                m_max(max)
         {
         }
Functions
allowsEmpty()
bool QPatternist::Cardinality::allowsEmpty () const inline
Returns
true if this Cardinality allows no items. For example, for zeroOrOne() is true returned, while for oneOrMore() is false returned.
Definition at line 254 of file qcardinality_p.h.
Referenced by QPatternist::InstanceOf::evaluateEBV(), QPatternist::CastableAs::evaluateEBV(), QPatternist::CardinalityVerifier::evaluateSequence(), QPatternist::CardinalityVerifier::evaluateSingleton(), QPatternist::CastAs::evaluateSingleton(), QPatternist::CastAs::expectedOperandTypes(), QPatternist::TextNodeConstructor::staticType(), QPatternist::SimpleContentConstructor::staticType(), QPatternist::ValueComparison::staticType(), QPatternist::NodeComparison::staticType(), QPatternist::CastAs::staticType(), QPatternist::CastableAs::typeCheck(), and QPatternist::CastAs::typeCheck().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality are invalid.");
             return m_min == 0;
         }
allowsMany()
bool QPatternist::Cardinality::allowsMany () const inline
Returns
true if this Cardinality allows one or more items. For example, for zeroOrOne() is false returned, while for zeroOrMore() is true returned.
Definition at line 244 of file qcardinality_p.h.
Referenced by QPatternist::CastableAs::CastableAs(), QPatternist::CastAs::CastAs(), QPatternist::NodeSortExpression::compress(), QPatternist::ForClause::compress(), QPatternist::StringJoinFN::compress(), QPatternist::OrderBy::compress(), QPatternist::InstanceOf::evaluateEBV(), QPatternist::CastableAs::evaluateEBV(), QPatternist::NodeSortExpression::evaluateSequence(), QPatternist::CardinalityVerifier::evaluateSequence(), QPatternist::GeneralComparison::typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::AvgFN::typeCheck(), QPatternist::DistinctValuesFN::typeCheck(), and QPatternist::ReverseFN::typeCheck().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality are invalid.");
             return m_max == -1 || m_max > 1;
         }
canMatch()
bool QPatternist::Cardinality::canMatch (const Cardinality & other) const inline
Determines whether at least one of the possible outcomes represented by other, can match this Cardinality. For example, if this Cardinality is oneOrMore(), true will be returned if other is exactlyOne() or zeroOrOne().
Definition at line 300 of file qcardinality_p.h.
Referenced by QPatternist::Existence< Id >::compress(), and QPatternist::CardinalityVerifier::verifyCardinality().
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO, "One of the cardinalities are invalid.");
             if(m_max == -1)
                 return m_min <= other.m_min || other.m_max >= m_min || other.m_max == -1;
             else
             {
                 if(m_max == other.m_min)
                     return true;
                 else if(m_max > other.m_min)
                     return other.m_max >= m_min || other.m_max == -1;
                 else /* m_max < other.m_min */
                     return false;
             }
         }
displayName()
QString Cardinality::displayName (const CustomizeDisplayName explanation) const
Returns a string representation of this Cardinality.
If explain is ExcludeExplanation the kleene operator is returned. For example, if the Cardinality is zeroOrOne, is "?" returned.
If explain is IncludeExplanation a string more suited for human interpretation is returned, which is appropriately translated. For example, when the locale is English and this Cardinality being zeroOrOne, then is 'zero or one("?")' returned.
Typically, passing ExcludeExplanation is useful when generating function signatures and the like, while passing IncludeExplanation is suitable appropriate when generating error messages.
Returns
a string representation for this Cardinality.
Definition at line 50 of file qcardinality.cpp.
Referenced by QPatternist::GenericSequenceType::displayName(), QPatternist::formatType(), and isExact().
 {
     if(explain == IncludeExplanation)
     {
         if(isEmpty())
             return QString(QtXmlPatterns::tr("empty") + QLatin1String("(\"empty-sequence()\")"));
         else if(isZeroOrOne())
             return QString(QtXmlPatterns::tr("zero or one") + QLatin1String("(\"?\")"));
         else if(isExactlyOne())
             return QString(QtXmlPatterns::tr("exactly one"));
         else if(isOneOrMore())
             return QString(QtXmlPatterns::tr("one or more") + QLatin1String("(\"+\")"));
         else
             return QString(QtXmlPatterns::tr("zero or more") + QLatin1String("(\"*\")"));
     }
     else
     {
         Q_ASSERT(explain == ExcludeExplanation);
         if(isEmpty() || isZeroOrOne())
             return QLatin1String("?");
         else if(isExactlyOne())
             return QString();
         else if(isExact())
         {
             return QString(QLatin1Char('{'))    +
                    QString::number(maximum())   +
                    QLatin1Char('}');
         }
         else
         {
             if(m_max == -1)
             {
                 if(isOneOrMore())
                     return QChar::fromLatin1('+');
                 else
                     return QChar::fromLatin1('*');
             }
             else
             {
                 /* We have a range. We use a RegExp-like syntax. */
                 return QString(QLatin1Char('{'))    +
                        QString::number(minimum())   +
                        QLatin1String(", ")          +
                        QString::number(maximum())   +
                        QLatin1Char('}');
             }
         }
     }
 }
empty()
static Cardinality QPatternist::Cardinality::empty () inline static
The cardinality assigned to the exprssion (), formally speaking. The cardinality part of empty-sequence().
Definition at line 128 of file qcardinality_p.h.
Referenced by QPatternist::EmptySequenceType::cardinality(), QPatternist::Existence< Id >::compress(), QPatternist::CastAs::evaluateSingleton(), operator &(), and QPatternist::ExpressionSequence::typeCheck().
         {
             return Cardinality(0, 0);
         }
exactlyOne()
static Cardinality QPatternist::Cardinality::exactlyOne () inline static
The cardinality implicitly specified in for example the sequence type item(). It has no kleene operator.
Definition at line 137 of file qcardinality_p.h.
Referenced by QPatternist::VariableLoader::announceExternalVariable(), QPatternist::Validate::create(), QPatternist::CastAs::evaluateSingleton(), QPatternist::XPath20CoreFunctions::retrieveExpression(), QPatternist::CurrentFN::staticType(), QPatternist::RangeVariableReference::staticType(), QPatternist::ContextItem::staticType(), QPatternist::ArithmeticExpression::staticType(), QPatternist::Literal::staticType(), QPatternist::EBVExtractor::staticType(), QPatternist::CastAs::staticType(), QPatternist::SumFN::staticType(), QPatternist::RootFN::staticType(), QPatternist::DistinctValuesFN::staticType(), and QPatternist::yyparse().
         {
             return Cardinality(1, 1);
         }
fromCount()
static Cardinality QPatternist::Cardinality::fromCount (const Count count) inline static
Determines the cardinality from the count of a sequence. For example, if count is 11, a Cardinality is returned that allows at minimum and maximum 11 items.
count must be positive or zero. If it is not, the result is undefined. When debugging is enabled, a Q_ASSERT() macro ensures this.
Definition at line 186 of file qcardinality_p.h.
Referenced by QPatternist::LiteralSequence::staticType().
         {
             Q_ASSERT_X(count > -1, Q_FUNC_INFO,
                        "A count smaller than 0 makes no sense.");
             return Cardinality(count, count);
         }
fromExact()
static Cardinality QPatternist::Cardinality::fromExact (const Count count) inline static
Definition at line 214 of file qcardinality_p.h.
Referenced by QPatternist::RangeExpression::staticType().
         {
             Q_ASSERT(count >= 0);
             return Cardinality(count, count);
         }
fromRange()
static Cardinality QPatternist::Cardinality::fromRange (const Count minimum, const Count maximum) inline static
Creates a Cardinality that allows minimum and maximum items, inclusive.
If maximum is -1, it signals infinity.
If you before hand knows that a predefined Cardinality is needed, remember to use one of the factory functions empty(), zeroOrOne(), exactlyOne(), oneOrMore() or zeroOrMore(), since they improves readability, are safer, and slightly faster.
Definition at line 204 of file qcardinality_p.h.
Referenced by QPatternist::RemoveFN::staticType().
         {
             Q_ASSERT_X(minimum > -1, Q_FUNC_INFO,
                        "minimum should never be less than 0.");
             Q_ASSERT_X(minimum <= maximum || maximum == -1, Q_FUNC_INFO,
                        "minimum cannot be larger than maximum.");
             return Cardinality(minimum, maximum);
         }
isEmpty()
bool QPatternist::Cardinality::isEmpty () const inline
Returns
true if this Cardinality is empty, the empty-sequence(), otherwise false.
Definition at line 320 of file qcardinality_p.h.
Referenced by QPatternist::NodeComparison::compress(), displayName(), QPatternist::CardinalityVerifier::evaluateSequence(), and QPatternist::GenericSequenceType::makeGenericSequenceType().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality is invalid.");
             return m_min == 0 && m_max == 0;
         }
isExact()
bool QPatternist::Cardinality::isExact () const inline
Determines whether this Cardinality only allows a specific length. For example, empty() and exactlyOne() are exact, but oneOrMore() or zeroOrOne() is not.
Definition at line 360 of file qcardinality_p.h.
Referenced by displayName().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality is invalid.");
             return m_min == m_max;
         }
isExactlyOne()
bool QPatternist::Cardinality::isExactlyOne () const inline
Returns
true if this Cardinality only allows exactly one item, otherwise false.
Definition at line 340 of file qcardinality_p.h.
Referenced by displayName().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality is invalid.");
             return m_min == 1 && m_max == 1;
         }
isMatch()
bool QPatternist::Cardinality::isMatch (const Cardinality & other) const inline
Determines whether all the possible outcomes represented by other, will always match this Cardinality. For example, if this Cardinality is oneOrMore(), true will be returned if other is exactlyOne(), but false if other is zeroOrOne().
Definition at line 279 of file qcardinality_p.h.
Referenced by QPatternist::InstanceOf::compress(), QPatternist::CastableAs::compress(), QPatternist::CardinalityVerifier::compress(), QPatternist::Existence< Id >::compress(), QPatternist::BySequenceTypeIdentifier::matches(), QPatternist::SequenceType::matches(), QPatternist::CastAs::typeCheck(), and QPatternist::CardinalityVerifier::verifyCardinality().
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO, "One of the cardinalities are invalid.");
             if(other.m_min < m_min)
                 return false;
             else
             { /* Ok, we now know the minimum will always be ok. */
                 if(m_max == -1)
                     return true; /* We allow infinite, so anything can match. */
                 else if(other.m_max == -1)
                     return false; /* other allows infinity, while we don't. */
                 else
                    return m_max >= other.m_max;
             }
         }
isOneOrMore()
bool QPatternist::Cardinality::isOneOrMore () const inline
Returns
true if this Cardinality only allows one or more items, otherwise false.
Definition at line 350 of file qcardinality_p.h.
Referenced by displayName().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality is invalid.");
             return m_min > 0 && (m_max == -1 || m_max >= 1);
         }
isZeroOrOne()
bool QPatternist::Cardinality::isZeroOrOne () const inline
Returns
true if this Cardinality is zero-or-one, ?, otherwise false.
Definition at line 330 of file qcardinality_p.h.
Referenced by displayName().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality is invalid.");
             return m_min == 0 && m_max == 1;
         }
maximum()
Count QPatternist::Cardinality::maximum () const inline
Returns
the maximum amount of items this Cardinality allows. For example, for zeroOrOne() is 1 returned.
Definition at line 234 of file qcardinality_p.h.
Referenced by displayName().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality are invalid.");
             return m_max;
         }
minimum()
Count QPatternist::Cardinality::minimum () const inline
Returns
the minimum amount of items this Cardinality allows. For example, for zeroOrOne() is 0 returned.
Definition at line 224 of file qcardinality_p.h.
Referenced by displayName().
         {
             Q_ASSERT_X(m_min != -1, Q_FUNC_INFO, "The cardinality are invalid.");
             return m_min;
         }
oneOrMore()
static Cardinality QPatternist::Cardinality::oneOrMore () inline static
Allows one or more. Represented by the kleene operator +.
Definition at line 163 of file qcardinality_p.h.
Referenced by QPatternist::Existence< Id >::compress(), QPatternist::XPath20CoreFunctions::retrieveExpression(), QPatternist::FunctionCall::staticType(), QPatternist::DistinctValuesFN::staticType(), and QPatternist::yyparse().
         {
             return Cardinality(1, -1);
         }
operator &()
Cardinality QPatternist::Cardinality::operator& (const Cardinality & other) const inline
Computes the intersection of this Cardinality and other, and returns the result. For example, the intersection between zeroOrOne() and oneOrMore() is exactlyOne().
If no intersection exists, such as the case in empty() and exactlyOne(), then is a default constructed Cardinality is returned. That is, an invalid Cardinality.
Definition at line 424 of file qcardinality_p.h.
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO, "One of the cardinalities are invalid.");
             if(m_max < other.m_min) /* No intersection. */
                 return empty();
             const Count min = qMax(m_min, other.m_min);
             if(m_max == -1)
                 return Cardinality(min, other.m_max);
             else if(other.m_max == -1)
                 return Cardinality(min, m_max);
             else
                 return Cardinality(min, qMin(m_max, other.m_max));
         }
operator!=()
bool QPatternist::Cardinality::operator!= (const Cardinality & other) const inline
Returns
the opposite of operator==()
Definition at line 521 of file qcardinality_p.h.
         {
             return m_min != other.m_min ||
                    m_max != other.m_max;
         }
operator*()
Cardinality QPatternist::Cardinality::operator* (const Cardinality & other) const inline
Multiplies this Cardinality with other, and returns the result. The minimum and maximum of each Cardinality is multiplied such that the new Cardinality represents the possible range of the two sequences being multiplied, length-wise. For example the Cardinality 4, 5 multiplied with 2, 3 becomes 8, 15.
Definition at line 482 of file qcardinality_p.h.
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO,
                        "One of the cardinalities are invalid.");
             if(m_max == -1 || other.m_max == -1)
                 return Cardinality(m_min * other.m_min, -1);
             else
                 return Cardinality(m_min * other.m_min, m_max * other.m_max);
         }
operator+()
Cardinality QPatternist::Cardinality::operator+ (const Cardinality & other) const inline
Adds two cardinalities, as if two sequences represented by them were concatenated. For example, if this Cardinality allows the range 6-8 and other allows 0-1, the return Cardinality has a range of 6-9.
Returns
the result of the comparison.
Definition at line 448 of file qcardinality_p.h.
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO, "One of the cardinalities are invalid.");
             if(m_max == -1 || other.m_max == -1)
                 return Cardinality(m_min + other.m_min, -1);
             else
                 return Cardinality(m_min + other.m_min, m_max + other.m_max);
         }
operator+=()
Cardinality& QPatternist::Cardinality::operator+= (const Cardinality & other) inline
Behaves as operator+() but assigns the result to this Cardinality.
Definition at line 460 of file qcardinality_p.h.
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO,
                        "One of the cardinalities are invalid.");
             m_min += other.m_min;
             if(m_max == -1)
                 return *this;
             if(other.m_max == -1)
                 m_max = -1;
             else
                 m_max += other.m_max;
             return *this;
         }
operator=()
Cardinality& QPatternist::Cardinality::operator= (const Cardinality & other) inline
A traditional assignment operator. Behaves as assignment operators typically do.
Definition at line 496 of file qcardinality_p.h.
         {
             Q_ASSERT_X(this != &other, Q_FUNC_INFO, "Assigning to oneself makes no sense.");
             m_min = other.m_min;
             m_max = other.m_max;
             return *this;
         }
operator==()
bool QPatternist::Cardinality::operator== (const Cardinality & other) const inline
Determines whether other is equal to this Cardinality.
For example, empty() is equal to empty(), but zeroOrOne() is not equal to exactlyOne().
Returns
true if other is equal to this Cardinality.
Definition at line 512 of file qcardinality_p.h.
         {
             return m_min == other.m_min &&
                    m_max == other.m_max;
         }
operator|()
Cardinality QPatternist::Cardinality::operator| (const Cardinality & other) const inline
Computes the Cardinality that comprises this Cardinality as well as other. For example, if this Cardinality is zeroOrOne() and other is oneOrMore(), then is zeroOrMore() returned.
Definition at line 389 of file qcardinality_p.h.
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO, "One of the cardinalities are invalid.");
             if(m_max == -1 || other.m_max == -1)
                 return Cardinality(qMin(m_min, other.m_min), -1);
             else
                 return Cardinality(qMin(m_min, other.m_min), qMax(m_max, other.m_max));
         }
operator|=()
Cardinality& QPatternist::Cardinality::operator|= (const Cardinality & other) inline
Behaves as operator|() but assigns the result to this Cardinality.
Definition at line 401 of file qcardinality_p.h.
         {
             Q_ASSERT_X(m_min != -1 && other.m_min != -1, Q_FUNC_INFO, "One of the cardinalities are invalid.");
             m_min = qMin(m_min, other.m_min);
             if(m_max == -1)
                 return *this;
             else if(other.m_max == -1)
                 m_max = -1;
             else
                 m_max = qMax(m_max, other.m_max);
             return *this;
         }
toWithoutMany()
Cardinality QPatternist::Cardinality::toWithoutMany () const inline
Maps directly to Formal Semantics' aggregate_quantifier function.
Returns
zeroOrOne() if this Cardinality allows the empty sequence, otherwise exactlyOne()
See also
XQuery 1.0 and XPath 2.0 Formal Semantics, The function quantifier()
Definition at line 267 of file qcardinality_p.h.
Referenced by QPatternist::RootFN::staticType().
         {
             return m_min == 0 ? Cardinality(0, 1)
                               : Cardinality(1, 1);
         }
twoOrMore()
static Cardinality QPatternist::Cardinality::twoOrMore () inline static
Allows one or more. This cardinality has no kleene operator and is used by the implementation in order to be able to know when a cardinality that at amximum allows one, is exceeded.
Definition at line 173 of file qcardinality_p.h.
Referenced by QPatternist::CardinalityVerifier::evaluateSequence(), and QPatternist::CardinalityVerifier::evaluateSingleton().
         {
             return Cardinality(2, -1);
         }
zeroOrMore()
static Cardinality QPatternist::Cardinality::zeroOrMore () inline static
Allows any amount. This is therefore the widest, an unconstrained cardinality. Represented by the kleene operator *.
Definition at line 155 of file qcardinality_p.h.
Referenced by QPatternist::NoneType::cardinality(), QPatternist::EBVType::cardinality(), QPatternist::CardinalityVerifier::CardinalityVerifier(), QPatternist::quantificationType(), QPatternist::AxisStep::staticType(), QPatternist::CombineNodes::staticType(), and QPatternist::yyparse().
         {
             return Cardinality(0, -1);
         }
zeroOrOne()
static Cardinality QPatternist::Cardinality::zeroOrOne () inline static
Allows both no item, as in empty(), and exactlyOne(). Represented by the kleene operator ?.
Definition at line 146 of file qcardinality_p.h.
Referenced by QPatternist::ConstructorFunctionsFactory::ConstructorFunctionsFactory(), QPatternist::ConstructorFunctionsFactory::retrieveExpression(), QPatternist::XPath20CoreFunctions::retrieveExpression(), QPatternist::AxisStep::staticType(), QPatternist::ArithmeticExpression::staticType(), QPatternist::GenericPredicate::staticType(), QPatternist::SubsequenceFN::staticType(), and QPatternist::yyparse().
         {
             return Cardinality(0, 1);
         }
Properties
m_max
Count QPatternist::Cardinality::m_max private
Definition at line 534 of file qcardinality_p.h.
Referenced by allowsMany(), canMatch(), displayName(), isEmpty(), isExact(), isExactlyOne(), isMatch(), isOneOrMore(), isZeroOrOne(), maximum(), operator &(), operator!=(), operator*(), operator+(), operator+=(), operator=(), operator==(), operator|(), and operator|=().
m_min
Count QPatternist::Cardinality::m_min private
Definition at line 533 of file qcardinality_p.h.
Referenced by allowsEmpty(), allowsMany(), canMatch(), isEmpty(), isExact(), isExactlyOne(), isMatch(), isOneOrMore(), isZeroOrOne(), maximum(), minimum(), operator &(), operator!=(), operator*(), operator+(), operator+=(), operator=(), operator==(), operator|(), operator|=(), and toWithoutMany().
The documentation for this class was generated from the following files:
/src/xmlpatterns/type/qcardinality_p.h
/src/xmlpatterns/type/qcardinality.cpp