Qt 4.8: QAccessibleTabBar Class Reference
QAccessibleTabBar Class Reference
The QAccessibleTabBar class implements the QAccessibleInterface for tab bars.
#include <complexwidgets.h>
Public Functions
QString actionText (int action, Text t, int child) const
Reimplemented Function
int childCount () const
Reimplemented Function
bool doAction (int action, int child, const QVariantList &params)
Reimplemented Function
int navigate (RelationFlag relation, int entry, QAccessibleInterface **target) const
Reimplemented Function
QAccessibleTabBar (QWidget *w)
Constructs a QAccessibleTabBar object for w.
QRect rect (int child) const
Reimplemented Function
Role role (int child) const
Reimplemented Function
QVector< int > selection () const
Returns a (possibly empty) list of indexes of the items selected in the list box.
bool setSelected (int child, bool on, bool extend)
Selects the item with index child if on is true; otherwise unselects it.
State state (int child) const
Reimplemented Function
QString text (Text t, int child) const
Reimplemented Function
int userActionCount (int child) const
Reimplemented Function
Public Functions inherited from QAccessibleWidgetEx
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethodEx (Method method, int child, const QVariantList &params)
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Public Functions inherited from QAccessibleObjectEx
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Protected Functions
QTabBar * tabBar () const
Returns the QTabBar.
Protected Functions inherited from QAccessibleWidgetEx
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Private Functions
QAbstractButton * button (int child) const
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
The QAccessibleTabBar class implements the QAccessibleInterface for tab bars.
Warning
This function is not part of the public interface.
Definition at line 232 of file complexwidgets.h.
Constructors and Destructors
QAccessibleTabBar()
QAccessibleTabBar::QAccessibleTabBar (QWidget * w) explicit
Constructs a QAccessibleTabBar object for w.
Definition at line 1463 of file complexwidgets.cpp.
 : QAccessibleWidgetEx(w)
 {
     Q_ASSERT(tabBar());
 }
Functions
actionText()
QString QAccessibleTabBar::actionText (int action, Text t, int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1612 of file complexwidgets.cpp.
 {
     if (!child)
         return QString();
     switch (t) {
     case QAccessible::Name:
         if ((action == 1) && (child <= tabBar()->count())) {
             return tabBar()->tabsClosable() ? QTabBar::tr("Close") : QString();
         } else if (action == 0) {
             if (child <= tabBar()->count())
                 return QTabBar::tr("Activate");
             else //it's an scroll button
                 return QTabBar::tr("Press");
         }
         break;
     case QAccessible::Description:
         if ((action == 1) && (child <= tabBar()->count())) {
             return tabBar()->tabsClosable() ? QTabBar::tr("Close the tab") : QString();
         } else if (action == 0) {
             if (child <= tabBar()->count())
                 return QTabBar::tr("Activate the tab");
         }
         break;
     default:
         break;
     }
     return QString();
 }
button()
QAbstractButton * QAccessibleTabBar::button (int child) const private
Definition at line 1475 of file complexwidgets.cpp.
Referenced by doAction(), rect(), and state().
 {
     if (child <= tabBar()->count())
         return 0;
     QTabBarPrivate * const tabBarPrivate = tabBar()->d_func();
     if (child - tabBar()->count() == 1)
         return tabBarPrivate->leftB;
     if (child - tabBar()->count() == 2)
         return tabBarPrivate->rightB;
     Q_ASSERT(false);
     return 0;
 }
childCount()
int QAccessibleTabBar::childCount () const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1506 of file complexwidgets.cpp.
Referenced by navigate().
 {
     // tabs + scroll buttons
     return tabBar()->count() + 2;
 }
doAction()
bool QAccessibleTabBar::doAction (int action, int child, const QVariantList & params) virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1651 of file complexwidgets.cpp.
 {
     if (!child)
         return false;
     if ((action == 1) && (child <= tabBar()->count()) && tabBar()->tabsClosable()) {
         emit tabBar()->tabCloseRequested(child - 1);
     }
     if (action != QAccessible::DefaultAction && action != QAccessible::Press)
         return false;
     if (child > tabBar()->count()) {
         QAbstractButton *bt = button(child);
         if (!bt->isEnabled())
             return false;
         bt->animateClick();
         return true;
     }
     if (!tabBar()->isTabEnabled(child - 1))
         return false;
     tabBar()->setCurrentIndex(child - 1);
     return true;
 }
navigate()
int QAccessibleTabBar::navigate (RelationFlag relation, int entry, QAccessibleInterface ** target) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1554 of file complexwidgets.cpp.
 {
     //QAccessibleWidgetEx::navigate might think that this is not a complex widget
     //if close buttons are enabled, so this functions handles those cases in which
     //the value to return is different if it's a complex widget and if it's not.
     if (!target)
         return -1;
     *target = 0;
     switch (relation) {
     case Child:
         if ((entry >= 0) && (entry <= childCount()))
             return entry;
         return -1;
     default:
         return QAccessibleWidgetEx::navigate(relation, entry, target);
     }
 }
rect()
QRect QAccessibleTabBar::rect (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1489 of file complexwidgets.cpp.
 {
     if (!child || !tabBar()->isVisible())
         return QAccessibleWidgetEx::rect(0);
     QPoint tp = tabBar()->mapToGlobal(QPoint(0,0));
     QRect rec;
     if (child <= tabBar()->count()) {
         rec = tabBar()->tabRect(child - 1);
     } else {
         QWidget *widget = button(child);
         rec = widget ? widget->geometry() : QRect();
     }
     return QRect(tp.x() + rec.x(), tp.y() + rec.y(), rec.width(), rec.height());
 }
role()
QAccessible::Role QAccessibleTabBar::role (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1544 of file complexwidgets.cpp.
 {
     if (!child)
         return PageTabList;
     if (child > tabBar()->count())
         return PushButton;
     return PageTab;
 }
selection()
QVector< int > QAccessibleTabBar::selection () const
Returns a (possibly empty) list of indexes of the items selected in the list box.
See also
setSelected() clearSelection()
Definition at line 1703 of file complexwidgets.cpp.
 {
     QVector<int> array;
     if (tabBar()->currentIndex() != -1)
         array +=tabBar()->currentIndex() + 1;
     return array;
 }
setSelected()
bool QAccessibleTabBar::setSelected (int child, bool on, bool extend)
Selects the item with index child if on is true; otherwise unselects it.
If extend is true and the selection mode is not Single and there is an existing selection, the selection is extended to include all the items from the existing selection up to and including the item with index child. Returns true if a selection was made or extended; otherwise returns false.
See also
selection() clearSelection()
Definition at line 1686 of file complexwidgets.cpp.
 {
     if (!child || !on || extend || child > tabBar()->count())
         return false;
     if (!tabBar()->isTabEnabled(child - 1))
         return false;
     tabBar()->setCurrentIndex(child - 1);
     return true;
 }
state()
QAccessible::State QAccessibleTabBar::state (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1576 of file complexwidgets.cpp.
 {
     State st = QAccessibleWidgetEx::state(0);
     if (!child)
         return st;
     QTabBar *tb = tabBar();
     if (child > tb->count()) {
         QWidget *bt = button(child);
         if (!bt)
             return st;
         if (bt->isEnabled() == false)
             st |= Unavailable;
         if (bt->isVisible() == false)
             st |= Invisible;
         if (bt->focusPolicy() != Qt::NoFocus && bt->isActiveWindow())
             st |= Focusable;
         if (bt->hasFocus())
             st |= Focused;
         return st;
     }
     if (!tb->isTabEnabled(child - 1))
         st |= Unavailable;
     else
         st |= Selectable;
     if (tb->currentIndex() == child - 1)
         st |= Selected;
     return st;
 }
tabBar()
QTabBar * QAccessibleTabBar::tabBar () const protected
Returns the QTabBar.
Definition at line 1470 of file complexwidgets.cpp.
Referenced by actionText(), button(), childCount(), doAction(), QAccessibleTabBar(), rect(), role(), selection(), setSelected(), state(), text(), and userActionCount().
 {
     return qobject_cast<QTabBar*>(object());
 }
text()
QString QAccessibleTabBar::text (Text t, int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleWidgetEx.
Definition at line 1513 of file complexwidgets.cpp.
 {
     QString str;
     if (child > tabBar()->count()) {
         bool left = child - tabBar()->count() == 1;
         switch (t) {
         case Name:
             return left ? QTabBar::tr("Scroll Left") : QTabBar::tr("Scroll Right");
         default:
             break;
         }
     } else {
         switch (t) {
         case Name:
             if (child > 0)
                 return qt_accStripAmp(tabBar()->tabText(child - 1));
             else if (tabBar()->currentIndex() != -1)
                 return qt_accStripAmp(tabBar()->tabText(tabBar()->currentIndex()));
             break;
         default:
             break;
         }
     }
     if (str.isEmpty())
         str = QAccessibleWidgetEx::text(t, child);;
     return str;
 }
userActionCount()
int QAccessibleTabBar::userActionCount (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleObjectEx.
Definition at line 1643 of file complexwidgets.cpp.
 {
     if (!child || (child > tabBar()->count()))
         return 0;
     return tabBar()->tabsClosable() ? 1 : 0;
 }
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/complexwidgets.h
/src/plugins/accessible/widgets/complexwidgets.cpp