Qt 4.8: QPatternist::SchemaTime Class Reference
QPatternist::SchemaTime Class Reference
Implements the value instance of the xs:time type.
#include <qschematime_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AbstractDateTime
enum { DefaultYear = 2000, DefaultMonth = 1, DefaultDay = 1 }
typedef QExplicitlySharedDataPointer< AbstractDateTime > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual Item fromValue (const QDateTime &dt) const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AbstractDateTime
AbstractDateTime (const QDateTime &dateTime)
QString dateToString () const
QString timeToString () const
const QDateTime & toDateTime () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static SchemaTime::Ptr fromDateTime (const QDateTime &dt)
static SchemaTime::Ptr fromLexical (const QString &string)
Static Public Functions inherited from QPatternist::AbstractDateTime
static bool isRangeValid (const QDate &date, QString &message)
static QString serializeMSeconds (const MSecondProperty msecs)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
SchemaTime (const QDateTime &dateTime)
Protected Functions inherited from QPatternist::AbstractDateTime
QString zoneOffsetToString () const
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDateTime
static void copyTimeSpec (const QDateTime &from, QDateTime &to)
Makes the QDateTime::timeSpec() and QDateTime::zoneOffset() of ot * consistent to from.
static QDateTime create (AtomicValue::Ptr &errorMessage, const QString &lexicalSource, const CaptureTable &captTable)
Protected Variables inherited from QPatternist::AbstractDateTime
const QDateTime m_dateTime
Detailed Description
Implements the value instance of the xs:time type.
The header file for this class was originally called Time.h, but this clashed with a system header on MinGW.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 72 of file qschematime_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::SchemaTime::Ptr
Definition at line 75 of file qschematime_p.h.
Constructors and Destructors
SchemaTime()
SchemaTime::SchemaTime (const QDateTime & dateTime) protected
Definition at line 51 of file qschematime.cpp.
Referenced by fromDateTime(), and fromLexical().
                                                 : AbstractDateTime(dateTime)
 {
 }
Functions
fromDateTime()
SchemaTime::Ptr SchemaTime::fromDateTime (const QDateTime & dt) static
Definition at line 87 of file qschematime.cpp.
Referenced by QPatternist::AbstractDateTimeToTimeCaster::castFrom(), QPatternist::AdjustTimeToTimezoneFN::createValue(), QPatternist::CurrentTimeFN::evaluateSingleton(), fromValue(), and QPatternist::AtomicValue::toXDM().
 {
     Q_ASSERT(dt.isValid());
     /* Singleton value, allocated once instead of each time it's needed. */
     // STATIC DATA
     static const QDate time_defaultDate(AbstractDateTime::DefaultYear,
                                         AbstractDateTime::DefaultMonth,
                                         AbstractDateTime::DefaultDay);
     QDateTime result;
     copyTimeSpec(dt, result);
     result.setDate(time_defaultDate);
     result.setTime(dt.time());
     return SchemaTime::Ptr(new SchemaTime(result));
 }
fromLexical()
SchemaTime::Ptr SchemaTime::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 55 of file qschematime.cpp.
Referenced by QPatternist::StringToTimeCaster::castFrom().
 {
     static const CaptureTable captureTable( // STATIC DATA
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"                             /* Any preceding whitespace. */
                 "(\\d{2})"                          /* Hour part */
                 ":"                                 /* Delimiter. */
                 "(\\d{2})"                          /* Minutes part */
                 ":"                                 /* Delimiter. */
                 "(\\d{2,})"                         /* Seconds part. */
                 "(?:\\.(\\d+))?"                    /* Milli seconds part. */
                 "(?:(\\+|-)(\\d{2}):(\\d{2})|(Z))?" /* The zone offset, "+08:24". */
                 "\\s*$"                             /* Any terminating whitespace. */))),
         /*zoneOffsetSignP*/         5,
         /*zoneOffsetHourP*/         6,
         /*zoneOffsetMinuteP*/       7,
         /*zoneOffsetUTCSymbolP*/    8,
         /*yearP*/                   -1,
         /*monthP*/                  -1,
         /*dayP*/                    -1,
         /*hourP*/                   1,
         /*minutesP*/                2,
         /*secondsP*/                3,
         /*msecondsP*/               4);
     AtomicValue::Ptr err;
     const QDateTime retval(create(err, lexical, captureTable));
     return err ? err : SchemaTime::Ptr(new SchemaTime(retval));
 }
fromValue()
Item SchemaTime::fromValue (const QDateTime & dt) const virtual
A factory function for creating instances that are of the dynamic type of this class, that represents dt.
The default implementation performs an assert() call. This function is not pure virtual because all sub-classes do not use it.
Reimplemented from QPatternist::AbstractDateTime.
Definition at line 105 of file qschematime.cpp.
 {
     Q_ASSERT(dt.isValid());
     return fromDateTime(dt);
 }
stringValue()
QString SchemaTime::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 111 of file qschematime.cpp.
 {
     return timeToString() + zoneOffsetToString();
 }
type()
ItemType::Ptr SchemaTime::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 116 of file qschematime.cpp.
 {
     return BuiltinTypes::xsTime;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 88 of file qschematime_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qschematime_p.h
/src/xmlpatterns/data/qschematime.cpp