Qt 4.8: QScript::AST::Visitor Class Reference
QScript::AST::Visitor Class Reference
#include <qscriptastvisitor_p.h>
Public Functions
virtual void endVisit (ThisExpression *)
virtual void endVisit (IdentifierExpression *)
virtual void endVisit (NullExpression *)
virtual void endVisit (TrueLiteral *)
virtual void endVisit (FalseLiteral *)
virtual void endVisit (StringLiteral *)
virtual void endVisit (NumericLiteral *)
virtual void endVisit (RegExpLiteral *)
virtual void endVisit (ArrayLiteral *)
virtual void endVisit (ObjectLiteral *)
virtual void endVisit (ElementList *)
virtual void endVisit (Elision *)
virtual void endVisit (PropertyNameAndValueList *)
virtual void endVisit (IdentifierPropertyName *)
virtual void endVisit (StringLiteralPropertyName *)
virtual void endVisit (NumericLiteralPropertyName *)
virtual void endVisit (ArrayMemberExpression *)
virtual void endVisit (FieldMemberExpression *)
virtual void endVisit (NewMemberExpression *)
virtual void endVisit (NewExpression *)
virtual void endVisit (CallExpression *)
virtual void endVisit (ArgumentList *)
virtual void endVisit (PostIncrementExpression *)
virtual void endVisit (PostDecrementExpression *)
virtual void endVisit (DeleteExpression *)
virtual void endVisit (VoidExpression *)
virtual void endVisit (TypeOfExpression *)
virtual void endVisit (PreIncrementExpression *)
virtual void endVisit (PreDecrementExpression *)
virtual void endVisit (UnaryPlusExpression *)
virtual void endVisit (UnaryMinusExpression *)
virtual void endVisit (TildeExpression *)
virtual void endVisit (NotExpression *)
virtual void endVisit (BinaryExpression *)
virtual void endVisit (ConditionalExpression *)
virtual void endVisit (Expression *)
virtual void endVisit (Block *)
virtual void endVisit (StatementList *)
virtual void endVisit (VariableStatement *)
virtual void endVisit (VariableDeclarationList *)
virtual void endVisit (VariableDeclaration *)
virtual void endVisit (EmptyStatement *)
virtual void endVisit (ExpressionStatement *)
virtual void endVisit (IfStatement *)
virtual void endVisit (DoWhileStatement *)
virtual void endVisit (WhileStatement *)
virtual void endVisit (ForStatement *)
virtual void endVisit (LocalForStatement *)
virtual void endVisit (ForEachStatement *)
virtual void endVisit (LocalForEachStatement *)
virtual void endVisit (ContinueStatement *)
virtual void endVisit (BreakStatement *)
virtual void endVisit (ReturnStatement *)
virtual void endVisit (WithStatement *)
virtual void endVisit (SwitchStatement *)
virtual void endVisit (CaseBlock *)
virtual void endVisit (CaseClauses *)
virtual void endVisit (CaseClause *)
virtual void endVisit (DefaultClause *)
virtual void endVisit (LabelledStatement *)
virtual void endVisit (ThrowStatement *)
virtual void endVisit (TryStatement *)
virtual void endVisit (Catch *)
virtual void endVisit (Finally *)
virtual void endVisit (FunctionDeclaration *)
virtual void endVisit (FunctionExpression *)
virtual void endVisit (FormalParameterList *)
virtual void endVisit (FunctionBody *)
virtual void endVisit (Program *)
virtual void endVisit (SourceElements *)
virtual void endVisit (FunctionSourceElement *)
virtual void endVisit (StatementSourceElement *)
virtual void endVisit (DebuggerStatement *)
virtual void postVisit (Node *)
virtual bool preVisit (Node *)
virtual bool visit (ThisExpression *)
virtual bool visit (IdentifierExpression *)
virtual bool visit (NullExpression *)
virtual bool visit (TrueLiteral *)
virtual bool visit (FalseLiteral *)
virtual bool visit (StringLiteral *)
virtual bool visit (NumericLiteral *)
virtual bool visit (RegExpLiteral *)
virtual bool visit (ArrayLiteral *)
virtual bool visit (ObjectLiteral *)
virtual bool visit (ElementList *)
virtual bool visit (Elision *)
virtual bool visit (PropertyNameAndValueList *)
virtual bool visit (IdentifierPropertyName *)
virtual bool visit (StringLiteralPropertyName *)
virtual bool visit (NumericLiteralPropertyName *)
virtual bool visit (ArrayMemberExpression *)
virtual bool visit (FieldMemberExpression *)
virtual bool visit (NewMemberExpression *)
virtual bool visit (NewExpression *)
virtual bool visit (CallExpression *)
virtual bool visit (ArgumentList *)
virtual bool visit (PostIncrementExpression *)
virtual bool visit (PostDecrementExpression *)
virtual bool visit (DeleteExpression *)
virtual bool visit (VoidExpression *)
virtual bool visit (TypeOfExpression *)
virtual bool visit (PreIncrementExpression *)
virtual bool visit (PreDecrementExpression *)
virtual bool visit (UnaryPlusExpression *)
virtual bool visit (UnaryMinusExpression *)
virtual bool visit (TildeExpression *)
virtual bool visit (NotExpression *)
virtual bool visit (BinaryExpression *)
virtual bool visit (ConditionalExpression *)
virtual bool visit (Expression *)
virtual bool visit (Block *)
virtual bool visit (StatementList *)
virtual bool visit (VariableStatement *)
virtual bool visit (VariableDeclarationList *)
virtual bool visit (VariableDeclaration *)
virtual bool visit (EmptyStatement *)
virtual bool visit (ExpressionStatement *)
virtual bool visit (IfStatement *)
virtual bool visit (DoWhileStatement *)
virtual bool visit (WhileStatement *)
virtual bool visit (ForStatement *)
virtual bool visit (LocalForStatement *)
virtual bool visit (ForEachStatement *)
virtual bool visit (LocalForEachStatement *)
virtual bool visit (ContinueStatement *)
virtual bool visit (BreakStatement *)
virtual bool visit (ReturnStatement *)
virtual bool visit (WithStatement *)
virtual bool visit (SwitchStatement *)
virtual bool visit (CaseBlock *)
virtual bool visit (CaseClauses *)
virtual bool visit (CaseClause *)
virtual bool visit (DefaultClause *)
virtual bool visit (LabelledStatement *)
virtual bool visit (ThrowStatement *)
virtual bool visit (TryStatement *)
virtual bool visit (Catch *)
virtual bool visit (Finally *)
virtual bool visit (FunctionDeclaration *)
virtual bool visit (FunctionExpression *)
virtual bool visit (FormalParameterList *)
virtual bool visit (FunctionBody *)
virtual bool visit (Program *)
virtual bool visit (SourceElements *)
virtual bool visit (FunctionSourceElement *)
virtual bool visit (StatementSourceElement *)
virtual bool visit (DebuggerStatement *)
Visitor ()
virtual ~Visitor ()
Detailed Description
Definition at line 44 of file qscriptastvisitor_p.h.
Constructors and Destructors
Visitor()
QScript::AST::Visitor::Visitor ()
Definition at line 30 of file qscriptastvisitor.cpp.
 {
 }
~Visitor()
QScript::AST::Visitor::~Visitor () virtual
Definition at line 34 of file qscriptastvisitor.cpp.
 {
 }
Functions
endVisit() [1/73]
virtual void QScript::AST::Visitor::endVisit (ThisExpression *) inline virtual
Definition at line 54 of file qscriptastvisitor_p.h.
Referenced by QScript::AST::ThisExpression::accept0(), QScript::AST::IdentifierExpression::accept0(), QScript::AST::NullExpression::accept0(), QScript::AST::TrueLiteral::accept0(), QScript::AST::FalseLiteral::accept0(), QScript::AST::NumericLiteral::accept0(), QScript::AST::StringLiteral::accept0(), QScript::AST::RegExpLiteral::accept0(), QScript::AST::ArrayLiteral::accept0(), QScript::AST::ObjectLiteral::accept0(), QScript::AST::ElementList::accept0(), QScript::AST::Elision::accept0(), QScript::AST::PropertyNameAndValueList::accept0(), QScript::AST::IdentifierPropertyName::accept0(), QScript::AST::StringLiteralPropertyName::accept0(), QScript::AST::NumericLiteralPropertyName::accept0(), QScript::AST::ArrayMemberExpression::accept0(), QScript::AST::FieldMemberExpression::accept0(), QScript::AST::NewMemberExpression::accept0(), QScript::AST::NewExpression::accept0(), QScript::AST::CallExpression::accept0(), QScript::AST::ArgumentList::accept0(), QScript::AST::PostIncrementExpression::accept0(), QScript::AST::PostDecrementExpression::accept0(), QScript::AST::DeleteExpression::accept0(), QScript::AST::VoidExpression::accept0(), QScript::AST::TypeOfExpression::accept0(), QScript::AST::PreIncrementExpression::accept0(), QScript::AST::PreDecrementExpression::accept0(), QScript::AST::UnaryPlusExpression::accept0(), QScript::AST::UnaryMinusExpression::accept0(), QScript::AST::TildeExpression::accept0(), QScript::AST::NotExpression::accept0(), QScript::AST::BinaryExpression::accept0(), QScript::AST::ConditionalExpression::accept0(), QScript::AST::Expression::accept0(), QScript::AST::Block::accept0(), QScript::AST::StatementList::accept0(), QScript::AST::VariableStatement::accept0(), QScript::AST::VariableDeclaration::accept0(), QScript::AST::VariableDeclarationList::accept0(), QScript::AST::EmptyStatement::accept0(), QScript::AST::ExpressionStatement::accept0(), QScript::AST::IfStatement::accept0(), QScript::AST::DoWhileStatement::accept0(), QScript::AST::WhileStatement::accept0(), QScript::AST::ForStatement::accept0(), QScript::AST::LocalForStatement::accept0(), QScript::AST::ForEachStatement::accept0(), QScript::AST::LocalForEachStatement::accept0(), QScript::AST::ContinueStatement::accept0(), QScript::AST::BreakStatement::accept0(), QScript::AST::ReturnStatement::accept0(), QScript::AST::WithStatement::accept0(), QScript::AST::SwitchStatement::accept0(), QScript::AST::CaseBlock::accept0(), QScript::AST::CaseClauses::accept0(), QScript::AST::CaseClause::accept0(), QScript::AST::DefaultClause::accept0(), QScript::AST::LabelledStatement::accept0(), QScript::AST::ThrowStatement::accept0(), QScript::AST::TryStatement::accept0(), QScript::AST::Catch::accept0(), QScript::AST::Finally::accept0(), QScript::AST::FunctionExpression::accept0(), QScript::AST::FunctionDeclaration::accept0(), QScript::AST::FormalParameterList::accept0(), QScript::AST::FunctionBody::accept0(), QScript::AST::Program::accept0(), QScript::AST::SourceElements::accept0(), QScript::AST::FunctionSourceElement::accept0(), QScript::AST::StatementSourceElement::accept0(), and QScript::AST::DebuggerStatement::accept0().
 {}
endVisit() [2/73]
virtual void QScript::AST::Visitor::endVisit (IdentifierExpression *) inline virtual
Definition at line 57 of file qscriptastvisitor_p.h.
 {}
endVisit() [3/73]
virtual void QScript::AST::Visitor::endVisit (NullExpression *) inline virtual
Definition at line 60 of file qscriptastvisitor_p.h.
 {}
endVisit() [4/73]
virtual void QScript::AST::Visitor::endVisit (TrueLiteral *) inline virtual
Definition at line 63 of file qscriptastvisitor_p.h.
 {}
endVisit() [5/73]
virtual void QScript::AST::Visitor::endVisit (FalseLiteral *) inline virtual
Definition at line 66 of file qscriptastvisitor_p.h.
 {}
endVisit() [6/73]
virtual void QScript::AST::Visitor::endVisit (StringLiteral *) inline virtual
Definition at line 69 of file qscriptastvisitor_p.h.
 {}
endVisit() [7/73]
virtual void QScript::AST::Visitor::endVisit (NumericLiteral *) inline virtual
Definition at line 72 of file qscriptastvisitor_p.h.
 {}
endVisit() [8/73]
virtual void QScript::AST::Visitor::endVisit (RegExpLiteral *) inline virtual
Definition at line 75 of file qscriptastvisitor_p.h.
 {}
endVisit() [9/73]
virtual void QScript::AST::Visitor::endVisit (ArrayLiteral *) inline virtual
Definition at line 78 of file qscriptastvisitor_p.h.
 {}
endVisit() [10/73]
virtual void QScript::AST::Visitor::endVisit (ObjectLiteral *) inline virtual
Definition at line 81 of file qscriptastvisitor_p.h.
 {}
endVisit() [11/73]
virtual void QScript::AST::Visitor::endVisit (ElementList *) inline virtual
Definition at line 84 of file qscriptastvisitor_p.h.
 {}
endVisit() [12/73]
virtual void QScript::AST::Visitor::endVisit (Elision *) inline virtual
Definition at line 87 of file qscriptastvisitor_p.h.
 {}
endVisit() [13/73]
virtual void QScript::AST::Visitor::endVisit (PropertyNameAndValueList *) inline virtual
Definition at line 90 of file qscriptastvisitor_p.h.
 {}
endVisit() [14/73]
virtual void QScript::AST::Visitor::endVisit (IdentifierPropertyName *) inline virtual
Definition at line 93 of file qscriptastvisitor_p.h.
 {}
endVisit() [15/73]
virtual void QScript::AST::Visitor::endVisit (StringLiteralPropertyName *) inline virtual
Definition at line 96 of file qscriptastvisitor_p.h.
 {}
endVisit() [16/73]
virtual void QScript::AST::Visitor::endVisit (NumericLiteralPropertyName *) inline virtual
Definition at line 99 of file qscriptastvisitor_p.h.
 {}
endVisit() [17/73]
virtual void QScript::AST::Visitor::endVisit (ArrayMemberExpression *) inline virtual
Definition at line 102 of file qscriptastvisitor_p.h.
 {}
endVisit() [18/73]
virtual void QScript::AST::Visitor::endVisit (FieldMemberExpression *) inline virtual
Definition at line 105 of file qscriptastvisitor_p.h.
 {}
endVisit() [19/73]
virtual void QScript::AST::Visitor::endVisit (NewMemberExpression *) inline virtual
Definition at line 108 of file qscriptastvisitor_p.h.
 {}
endVisit() [20/73]
virtual void QScript::AST::Visitor::endVisit (NewExpression *) inline virtual
Definition at line 111 of file qscriptastvisitor_p.h.
 {}
endVisit() [21/73]
virtual void QScript::AST::Visitor::endVisit (CallExpression *) inline virtual
Definition at line 114 of file qscriptastvisitor_p.h.
 {}
endVisit() [22/73]
virtual void QScript::AST::Visitor::endVisit (ArgumentList *) inline virtual
Definition at line 117 of file qscriptastvisitor_p.h.
 {}
endVisit() [23/73]
virtual void QScript::AST::Visitor::endVisit (PostIncrementExpression *) inline virtual
Definition at line 120 of file qscriptastvisitor_p.h.
 {}
endVisit() [24/73]
virtual void QScript::AST::Visitor::endVisit (PostDecrementExpression *) inline virtual
Definition at line 123 of file qscriptastvisitor_p.h.
 {}
endVisit() [25/73]
virtual void QScript::AST::Visitor::endVisit (DeleteExpression *) inline virtual
Definition at line 126 of file qscriptastvisitor_p.h.
 {}
endVisit() [26/73]
virtual void QScript::AST::Visitor::endVisit (VoidExpression *) inline virtual
Definition at line 129 of file qscriptastvisitor_p.h.
 {}
endVisit() [27/73]
virtual void QScript::AST::Visitor::endVisit (TypeOfExpression *) inline virtual
Definition at line 132 of file qscriptastvisitor_p.h.
 {}
endVisit() [28/73]
virtual void QScript::AST::Visitor::endVisit (PreIncrementExpression *) inline virtual
Definition at line 135 of file qscriptastvisitor_p.h.
 {}
endVisit() [29/73]
virtual void QScript::AST::Visitor::endVisit (PreDecrementExpression *) inline virtual
Definition at line 138 of file qscriptastvisitor_p.h.
 {}
endVisit() [30/73]
virtual void QScript::AST::Visitor::endVisit (UnaryPlusExpression *) inline virtual
Definition at line 141 of file qscriptastvisitor_p.h.
 {}
endVisit() [31/73]
virtual void QScript::AST::Visitor::endVisit (UnaryMinusExpression *) inline virtual
Definition at line 144 of file qscriptastvisitor_p.h.
 {}
endVisit() [32/73]
virtual void QScript::AST::Visitor::endVisit (TildeExpression *) inline virtual
Definition at line 147 of file qscriptastvisitor_p.h.
 {}
endVisit() [33/73]
virtual void QScript::AST::Visitor::endVisit (NotExpression *) inline virtual
Definition at line 150 of file qscriptastvisitor_p.h.
 {}
endVisit() [34/73]
virtual void QScript::AST::Visitor::endVisit (BinaryExpression *) inline virtual
Definition at line 153 of file qscriptastvisitor_p.h.
 {}
endVisit() [35/73]
virtual void QScript::AST::Visitor::endVisit (ConditionalExpression *) inline virtual
Definition at line 156 of file qscriptastvisitor_p.h.
 {}
endVisit() [36/73]
virtual void QScript::AST::Visitor::endVisit (Expression *) inline virtual
Definition at line 159 of file qscriptastvisitor_p.h.
 {}
endVisit() [37/73]
virtual void QScript::AST::Visitor::endVisit (Block *) inline virtual
Definition at line 162 of file qscriptastvisitor_p.h.
 {}
endVisit() [38/73]
virtual void QScript::AST::Visitor::endVisit (StatementList *) inline virtual
Definition at line 165 of file qscriptastvisitor_p.h.
 {}
endVisit() [39/73]
virtual void QScript::AST::Visitor::endVisit (VariableStatement *) inline virtual
Definition at line 168 of file qscriptastvisitor_p.h.
 {}
endVisit() [40/73]
virtual void QScript::AST::Visitor::endVisit (VariableDeclarationList *) inline virtual
Definition at line 171 of file qscriptastvisitor_p.h.
 {}
endVisit() [41/73]
virtual void QScript::AST::Visitor::endVisit (VariableDeclaration *) inline virtual
Definition at line 174 of file qscriptastvisitor_p.h.
 {}
endVisit() [42/73]
virtual void QScript::AST::Visitor::endVisit (EmptyStatement *) inline virtual
Definition at line 177 of file qscriptastvisitor_p.h.
 {}
endVisit() [43/73]
virtual void QScript::AST::Visitor::endVisit (ExpressionStatement *) inline virtual
Definition at line 180 of file qscriptastvisitor_p.h.
 {}
endVisit() [44/73]
virtual void QScript::AST::Visitor::endVisit (IfStatement *) inline virtual
Definition at line 183 of file qscriptastvisitor_p.h.
 {}
endVisit() [45/73]
virtual void QScript::AST::Visitor::endVisit (DoWhileStatement *) inline virtual
Definition at line 186 of file qscriptastvisitor_p.h.
 {}
endVisit() [46/73]
virtual void QScript::AST::Visitor::endVisit (WhileStatement *) inline virtual
Definition at line 189 of file qscriptastvisitor_p.h.
 {}
endVisit() [47/73]
virtual void QScript::AST::Visitor::endVisit (ForStatement *) inline virtual
Definition at line 192 of file qscriptastvisitor_p.h.
 {}
endVisit() [48/73]
virtual void QScript::AST::Visitor::endVisit (LocalForStatement *) inline virtual
Definition at line 195 of file qscriptastvisitor_p.h.
 {}
endVisit() [49/73]
virtual void QScript::AST::Visitor::endVisit (ForEachStatement *) inline virtual
Definition at line 198 of file qscriptastvisitor_p.h.
 {}
endVisit() [50/73]
virtual void QScript::AST::Visitor::endVisit (LocalForEachStatement *) inline virtual
Definition at line 201 of file qscriptastvisitor_p.h.
 {}
endVisit() [51/73]
virtual void QScript::AST::Visitor::endVisit (ContinueStatement *) inline virtual
Definition at line 204 of file qscriptastvisitor_p.h.
 {}
endVisit() [52/73]
virtual void QScript::AST::Visitor::endVisit (BreakStatement *) inline virtual
Definition at line 207 of file qscriptastvisitor_p.h.
 {}
endVisit() [53/73]
virtual void QScript::AST::Visitor::endVisit (ReturnStatement *) inline virtual
Definition at line 210 of file qscriptastvisitor_p.h.
 {}
endVisit() [54/73]
virtual void QScript::AST::Visitor::endVisit (WithStatement *) inline virtual
Definition at line 213 of file qscriptastvisitor_p.h.
 {}
endVisit() [55/73]
virtual void QScript::AST::Visitor::endVisit (SwitchStatement *) inline virtual
Definition at line 216 of file qscriptastvisitor_p.h.
 {}
endVisit() [56/73]
virtual void QScript::AST::Visitor::endVisit (CaseBlock *) inline virtual
Definition at line 219 of file qscriptastvisitor_p.h.
 {}
endVisit() [57/73]
virtual void QScript::AST::Visitor::endVisit (CaseClauses *) inline virtual
Definition at line 222 of file qscriptastvisitor_p.h.
 {}
endVisit() [58/73]
virtual void QScript::AST::Visitor::endVisit (CaseClause *) inline virtual
Definition at line 225 of file qscriptastvisitor_p.h.
 {}
endVisit() [59/73]
virtual void QScript::AST::Visitor::endVisit (DefaultClause *) inline virtual
Definition at line 228 of file qscriptastvisitor_p.h.
 {}
endVisit() [60/73]
virtual void QScript::AST::Visitor::endVisit (LabelledStatement *) inline virtual
Definition at line 231 of file qscriptastvisitor_p.h.
 {}
endVisit() [61/73]
virtual void QScript::AST::Visitor::endVisit (ThrowStatement *) inline virtual
Definition at line 234 of file qscriptastvisitor_p.h.
 {}
endVisit() [62/73]
virtual void QScript::AST::Visitor::endVisit (TryStatement *) inline virtual
Definition at line 237 of file qscriptastvisitor_p.h.
 {}
endVisit() [63/73]
virtual void QScript::AST::Visitor::endVisit (Catch *) inline virtual
Definition at line 240 of file qscriptastvisitor_p.h.
 {}
endVisit() [64/73]
virtual void QScript::AST::Visitor::endVisit (Finally *) inline virtual
Definition at line 243 of file qscriptastvisitor_p.h.
 {}
endVisit() [65/73]
virtual void QScript::AST::Visitor::endVisit (FunctionDeclaration *) inline virtual
Definition at line 246 of file qscriptastvisitor_p.h.
 {}
endVisit() [66/73]
virtual void QScript::AST::Visitor::endVisit (FunctionExpression *) inline virtual
Definition at line 249 of file qscriptastvisitor_p.h.
 {}
endVisit() [67/73]
virtual void QScript::AST::Visitor::endVisit (FormalParameterList *) inline virtual
Definition at line 252 of file qscriptastvisitor_p.h.
 {}
endVisit() [68/73]
virtual void QScript::AST::Visitor::endVisit (FunctionBody *) inline virtual
Definition at line 255 of file qscriptastvisitor_p.h.
 {}
endVisit() [69/73]
virtual void QScript::AST::Visitor::endVisit (Program *) inline virtual
Definition at line 258 of file qscriptastvisitor_p.h.
 {}
endVisit() [70/73]
virtual void QScript::AST::Visitor::endVisit (SourceElements *) inline virtual
Definition at line 261 of file qscriptastvisitor_p.h.
 {}
endVisit() [71/73]
virtual void QScript::AST::Visitor::endVisit (FunctionSourceElement *) inline virtual
Definition at line 264 of file qscriptastvisitor_p.h.
 {}
endVisit() [72/73]
virtual void QScript::AST::Visitor::endVisit (StatementSourceElement *) inline virtual
Definition at line 267 of file qscriptastvisitor_p.h.
 {}
endVisit() [73/73]
virtual void QScript::AST::Visitor::endVisit (DebuggerStatement *) inline virtual
Definition at line 270 of file qscriptastvisitor_p.h.
 {}
postVisit()
virtual void QScript::AST::Visitor::postVisit (Node *) inline virtual
Definition at line 51 of file qscriptastvisitor_p.h.
Referenced by QScript::AST::Node::accept().
 {}
preVisit()
virtual bool QScript::AST::Visitor::preVisit (Node *) inline virtual
Definition at line 50 of file qscriptastvisitor_p.h.
Referenced by QScript::AST::Node::accept().
 { return true; }
visit() [1/73]
virtual bool QScript::AST::Visitor::visit (ThisExpression *) inline virtual
Definition at line 53 of file qscriptastvisitor_p.h.
Referenced by QScript::AST::ThisExpression::accept0(), QScript::AST::IdentifierExpression::accept0(), QScript::AST::NullExpression::accept0(), QScript::AST::TrueLiteral::accept0(), QScript::AST::FalseLiteral::accept0(), QScript::AST::NumericLiteral::accept0(), QScript::AST::StringLiteral::accept0(), QScript::AST::RegExpLiteral::accept0(), QScript::AST::ArrayLiteral::accept0(), QScript::AST::ObjectLiteral::accept0(), QScript::AST::ElementList::accept0(), QScript::AST::Elision::accept0(), QScript::AST::PropertyNameAndValueList::accept0(), QScript::AST::IdentifierPropertyName::accept0(), QScript::AST::StringLiteralPropertyName::accept0(), QScript::AST::NumericLiteralPropertyName::accept0(), QScript::AST::ArrayMemberExpression::accept0(), QScript::AST::FieldMemberExpression::accept0(), QScript::AST::NewMemberExpression::accept0(), QScript::AST::NewExpression::accept0(), QScript::AST::CallExpression::accept0(), QScript::AST::ArgumentList::accept0(), QScript::AST::PostIncrementExpression::accept0(), QScript::AST::PostDecrementExpression::accept0(), QScript::AST::DeleteExpression::accept0(), QScript::AST::VoidExpression::accept0(), QScript::AST::TypeOfExpression::accept0(), QScript::AST::PreIncrementExpression::accept0(), QScript::AST::PreDecrementExpression::accept0(), QScript::AST::UnaryPlusExpression::accept0(), QScript::AST::UnaryMinusExpression::accept0(), QScript::AST::TildeExpression::accept0(), QScript::AST::NotExpression::accept0(), QScript::AST::BinaryExpression::accept0(), QScript::AST::ConditionalExpression::accept0(), QScript::AST::Expression::accept0(), QScript::AST::Block::accept0(), QScript::AST::StatementList::accept0(), QScript::AST::VariableStatement::accept0(), QScript::AST::VariableDeclaration::accept0(), QScript::AST::VariableDeclarationList::accept0(), QScript::AST::EmptyStatement::accept0(), QScript::AST::ExpressionStatement::accept0(), QScript::AST::IfStatement::accept0(), QScript::AST::DoWhileStatement::accept0(), QScript::AST::WhileStatement::accept0(), QScript::AST::ForStatement::accept0(), QScript::AST::LocalForStatement::accept0(), QScript::AST::ForEachStatement::accept0(), QScript::AST::LocalForEachStatement::accept0(), QScript::AST::ContinueStatement::accept0(), QScript::AST::BreakStatement::accept0(), QScript::AST::ReturnStatement::accept0(), QScript::AST::WithStatement::accept0(), QScript::AST::SwitchStatement::accept0(), QScript::AST::CaseBlock::accept0(), QScript::AST::CaseClauses::accept0(), QScript::AST::CaseClause::accept0(), QScript::AST::DefaultClause::accept0(), QScript::AST::LabelledStatement::accept0(), QScript::AST::ThrowStatement::accept0(), QScript::AST::TryStatement::accept0(), QScript::AST::Catch::accept0(), QScript::AST::Finally::accept0(), QScript::AST::FunctionExpression::accept0(), QScript::AST::FunctionDeclaration::accept0(), QScript::AST::FormalParameterList::accept0(), QScript::AST::FunctionBody::accept0(), QScript::AST::Program::accept0(), QScript::AST::SourceElements::accept0(), QScript::AST::FunctionSourceElement::accept0(), QScript::AST::StatementSourceElement::accept0(), and QScript::AST::DebuggerStatement::accept0().
 { return true; }
visit() [2/73]
virtual bool QScript::AST::Visitor::visit (IdentifierExpression *) inline virtual
Definition at line 56 of file qscriptastvisitor_p.h.
 { return true; }
visit() [3/73]
virtual bool QScript::AST::Visitor::visit (NullExpression *) inline virtual
Definition at line 59 of file qscriptastvisitor_p.h.
 { return true; }
visit() [4/73]
virtual bool QScript::AST::Visitor::visit (TrueLiteral *) inline virtual
Definition at line 62 of file qscriptastvisitor_p.h.
 { return true; }
visit() [5/73]
virtual bool QScript::AST::Visitor::visit (FalseLiteral *) inline virtual
Definition at line 65 of file qscriptastvisitor_p.h.
 { return true; }
visit() [6/73]
virtual bool QScript::AST::Visitor::visit (StringLiteral *) inline virtual
Definition at line 68 of file qscriptastvisitor_p.h.
 { return true; }
visit() [7/73]
virtual bool QScript::AST::Visitor::visit (NumericLiteral *) inline virtual
Definition at line 71 of file qscriptastvisitor_p.h.
 { return true; }
visit() [8/73]
virtual bool QScript::AST::Visitor::visit (RegExpLiteral *) inline virtual
Definition at line 74 of file qscriptastvisitor_p.h.
 { return true; }
visit() [9/73]
virtual bool QScript::AST::Visitor::visit (ArrayLiteral *) inline virtual
Definition at line 77 of file qscriptastvisitor_p.h.
 { return true; }
visit() [10/73]
virtual bool QScript::AST::Visitor::visit (ObjectLiteral *) inline virtual
Definition at line 80 of file qscriptastvisitor_p.h.
 { return true; }
visit() [11/73]
virtual bool QScript::AST::Visitor::visit (ElementList *) inline virtual
Definition at line 83 of file qscriptastvisitor_p.h.
 { return true; }
visit() [12/73]
virtual bool QScript::AST::Visitor::visit (Elision *) inline virtual
Definition at line 86 of file qscriptastvisitor_p.h.
 { return true; }
visit() [13/73]
virtual bool QScript::AST::Visitor::visit (PropertyNameAndValueList *) inline virtual
Definition at line 89 of file qscriptastvisitor_p.h.
 { return true; }
visit() [14/73]
virtual bool QScript::AST::Visitor::visit (IdentifierPropertyName *) inline virtual
Definition at line 92 of file qscriptastvisitor_p.h.
 { return true; }
visit() [15/73]
virtual bool QScript::AST::Visitor::visit (StringLiteralPropertyName *) inline virtual
Definition at line 95 of file qscriptastvisitor_p.h.
 { return true; }
visit() [16/73]
virtual bool QScript::AST::Visitor::visit (NumericLiteralPropertyName *) inline virtual
Definition at line 98 of file qscriptastvisitor_p.h.
 { return true; }
visit() [17/73]
virtual bool QScript::AST::Visitor::visit (ArrayMemberExpression *) inline virtual
Definition at line 101 of file qscriptastvisitor_p.h.
 { return true; }
visit() [18/73]
virtual bool QScript::AST::Visitor::visit (FieldMemberExpression *) inline virtual
Definition at line 104 of file qscriptastvisitor_p.h.
 { return true; }
visit() [19/73]
virtual bool QScript::AST::Visitor::visit (NewMemberExpression *) inline virtual
Definition at line 107 of file qscriptastvisitor_p.h.
 { return true; }
visit() [20/73]
virtual bool QScript::AST::Visitor::visit (NewExpression *) inline virtual
Definition at line 110 of file qscriptastvisitor_p.h.
 { return true; }
visit() [21/73]
virtual bool QScript::AST::Visitor::visit (CallExpression *) inline virtual
Definition at line 113 of file qscriptastvisitor_p.h.
 { return true; }
visit() [22/73]
virtual bool QScript::AST::Visitor::visit (ArgumentList *) inline virtual
Definition at line 116 of file qscriptastvisitor_p.h.
 { return true; }
visit() [23/73]
virtual bool QScript::AST::Visitor::visit (PostIncrementExpression *) inline virtual
Definition at line 119 of file qscriptastvisitor_p.h.
 { return true; }
visit() [24/73]
virtual bool QScript::AST::Visitor::visit (PostDecrementExpression *) inline virtual
Definition at line 122 of file qscriptastvisitor_p.h.
 { return true; }
visit() [25/73]
virtual bool QScript::AST::Visitor::visit (DeleteExpression *) inline virtual
Definition at line 125 of file qscriptastvisitor_p.h.
 { return true; }
visit() [26/73]
virtual bool QScript::AST::Visitor::visit (VoidExpression *) inline virtual
Definition at line 128 of file qscriptastvisitor_p.h.
 { return true; }
visit() [27/73]
virtual bool QScript::AST::Visitor::visit (TypeOfExpression *) inline virtual
Definition at line 131 of file qscriptastvisitor_p.h.
 { return true; }
visit() [28/73]
virtual bool QScript::AST::Visitor::visit (PreIncrementExpression *) inline virtual
Definition at line 134 of file qscriptastvisitor_p.h.
 { return true; }
visit() [29/73]
virtual bool QScript::AST::Visitor::visit (PreDecrementExpression *) inline virtual
Definition at line 137 of file qscriptastvisitor_p.h.
 { return true; }
visit() [30/73]
virtual bool QScript::AST::Visitor::visit (UnaryPlusExpression *) inline virtual
Definition at line 140 of file qscriptastvisitor_p.h.
 { return true; }
visit() [31/73]
virtual bool QScript::AST::Visitor::visit (UnaryMinusExpression *) inline virtual
Definition at line 143 of file qscriptastvisitor_p.h.
 { return true; }
visit() [32/73]
virtual bool QScript::AST::Visitor::visit (TildeExpression *) inline virtual
Definition at line 146 of file qscriptastvisitor_p.h.
 { return true; }
visit() [33/73]
virtual bool QScript::AST::Visitor::visit (NotExpression *) inline virtual
Definition at line 149 of file qscriptastvisitor_p.h.
 { return true; }
visit() [34/73]
virtual bool QScript::AST::Visitor::visit (BinaryExpression *) inline virtual
Definition at line 152 of file qscriptastvisitor_p.h.
 { return true; }
visit() [35/73]
virtual bool QScript::AST::Visitor::visit (ConditionalExpression *) inline virtual
Definition at line 155 of file qscriptastvisitor_p.h.
 { return true; }
visit() [36/73]
virtual bool QScript::AST::Visitor::visit (Expression *) inline virtual
Definition at line 158 of file qscriptastvisitor_p.h.
 { return true; }
visit() [37/73]
virtual bool QScript::AST::Visitor::visit (Block *) inline virtual
Definition at line 161 of file qscriptastvisitor_p.h.
 { return true; }
visit() [38/73]
virtual bool QScript::AST::Visitor::visit (StatementList *) inline virtual
Definition at line 164 of file qscriptastvisitor_p.h.
 { return true; }
visit() [39/73]
virtual bool QScript::AST::Visitor::visit (VariableStatement *) inline virtual
Definition at line 167 of file qscriptastvisitor_p.h.
 { return true; }
visit() [40/73]
virtual bool QScript::AST::Visitor::visit (VariableDeclarationList *) inline virtual
Definition at line 170 of file qscriptastvisitor_p.h.
 { return true; }
visit() [41/73]
virtual bool QScript::AST::Visitor::visit (VariableDeclaration *) inline virtual
Definition at line 173 of file qscriptastvisitor_p.h.
 { return true; }
visit() [42/73]
virtual bool QScript::AST::Visitor::visit (EmptyStatement *) inline virtual
Definition at line 176 of file qscriptastvisitor_p.h.
 { return true; }
visit() [43/73]
virtual bool QScript::AST::Visitor::visit (ExpressionStatement *) inline virtual
Definition at line 179 of file qscriptastvisitor_p.h.
 { return true; }
visit() [44/73]
virtual bool QScript::AST::Visitor::visit (IfStatement *) inline virtual
Definition at line 182 of file qscriptastvisitor_p.h.
 { return true; }
visit() [45/73]
virtual bool QScript::AST::Visitor::visit (DoWhileStatement *) inline virtual
Definition at line 185 of file qscriptastvisitor_p.h.
 { return true; }
visit() [46/73]
virtual bool QScript::AST::Visitor::visit (WhileStatement *) inline virtual
Definition at line 188 of file qscriptastvisitor_p.h.
 { return true; }
visit() [47/73]
virtual bool QScript::AST::Visitor::visit (ForStatement *) inline virtual
Definition at line 191 of file qscriptastvisitor_p.h.
 { return true; }
visit() [48/73]
virtual bool QScript::AST::Visitor::visit (LocalForStatement *) inline virtual
Definition at line 194 of file qscriptastvisitor_p.h.
 { return true; }
visit() [49/73]
virtual bool QScript::AST::Visitor::visit (ForEachStatement *) inline virtual
Definition at line 197 of file qscriptastvisitor_p.h.
 { return true; }
visit() [50/73]
virtual bool QScript::AST::Visitor::visit (LocalForEachStatement *) inline virtual
Definition at line 200 of file qscriptastvisitor_p.h.
 { return true; }
visit() [51/73]
virtual bool QScript::AST::Visitor::visit (ContinueStatement *) inline virtual
Definition at line 203 of file qscriptastvisitor_p.h.
 { return true; }
visit() [52/73]
virtual bool QScript::AST::Visitor::visit (BreakStatement *) inline virtual
Definition at line 206 of file qscriptastvisitor_p.h.
 { return true; }
visit() [53/73]
virtual bool QScript::AST::Visitor::visit (ReturnStatement *) inline virtual
Definition at line 209 of file qscriptastvisitor_p.h.
 { return true; }
visit() [54/73]
virtual bool QScript::AST::Visitor::visit (WithStatement *) inline virtual
Definition at line 212 of file qscriptastvisitor_p.h.
 { return true; }
visit() [55/73]
virtual bool QScript::AST::Visitor::visit (SwitchStatement *) inline virtual
Definition at line 215 of file qscriptastvisitor_p.h.
 { return true; }
visit() [56/73]
virtual bool QScript::AST::Visitor::visit (CaseBlock *) inline virtual
Definition at line 218 of file qscriptastvisitor_p.h.
 { return true; }
visit() [57/73]
virtual bool QScript::AST::Visitor::visit (CaseClauses *) inline virtual
Definition at line 221 of file qscriptastvisitor_p.h.
 { return true; }
visit() [58/73]
virtual bool QScript::AST::Visitor::visit (CaseClause *) inline virtual
Definition at line 224 of file qscriptastvisitor_p.h.
 { return true; }
visit() [59/73]
virtual bool QScript::AST::Visitor::visit (DefaultClause *) inline virtual
Definition at line 227 of file qscriptastvisitor_p.h.
 { return true; }
visit() [60/73]
virtual bool QScript::AST::Visitor::visit (LabelledStatement *) inline virtual
Definition at line 230 of file qscriptastvisitor_p.h.
 { return true; }
visit() [61/73]
virtual bool QScript::AST::Visitor::visit (ThrowStatement *) inline virtual
Definition at line 233 of file qscriptastvisitor_p.h.
 { return true; }
visit() [62/73]
virtual bool QScript::AST::Visitor::visit (TryStatement *) inline virtual
Definition at line 236 of file qscriptastvisitor_p.h.
 { return true; }
visit() [63/73]
virtual bool QScript::AST::Visitor::visit (Catch *) inline virtual
Definition at line 239 of file qscriptastvisitor_p.h.
 { return true; }
visit() [64/73]
virtual bool QScript::AST::Visitor::visit (Finally *) inline virtual
Definition at line 242 of file qscriptastvisitor_p.h.
 { return true; }
visit() [65/73]
virtual bool QScript::AST::Visitor::visit (FunctionDeclaration *) inline virtual
Definition at line 245 of file qscriptastvisitor_p.h.
 { return true; }
visit() [66/73]
virtual bool QScript::AST::Visitor::visit (FunctionExpression *) inline virtual
Definition at line 248 of file qscriptastvisitor_p.h.
 { return true; }
visit() [67/73]
virtual bool QScript::AST::Visitor::visit (FormalParameterList *) inline virtual
Definition at line 251 of file qscriptastvisitor_p.h.
 { return true; }
visit() [68/73]
virtual bool QScript::AST::Visitor::visit (FunctionBody *) inline virtual
Definition at line 254 of file qscriptastvisitor_p.h.
 { return true; }
visit() [69/73]
virtual bool QScript::AST::Visitor::visit (Program *) inline virtual
Definition at line 257 of file qscriptastvisitor_p.h.
 { return true; }
visit() [70/73]
virtual bool QScript::AST::Visitor::visit (SourceElements *) inline virtual
Definition at line 260 of file qscriptastvisitor_p.h.
 { return true; }
visit() [71/73]
virtual bool QScript::AST::Visitor::visit (FunctionSourceElement *) inline virtual
Definition at line 263 of file qscriptastvisitor_p.h.
 { return true; }
visit() [72/73]
virtual bool QScript::AST::Visitor::visit (StatementSourceElement *) inline virtual
Definition at line 266 of file qscriptastvisitor_p.h.
 { return true; }
visit() [73/73]
virtual bool QScript::AST::Visitor::visit (DebuggerStatement *) inline virtual
Definition at line 269 of file qscriptastvisitor_p.h.
 { return true; }
The documentation for this class was generated from the following files:
/src/script/parser/qscriptastvisitor_p.h
/src/script/parser/qscriptastvisitor.cpp