Qt 4.8: QFile Class Reference
QFile Class Reference
The QFile class provides an interface for reading from and writing to files.
#include <qfile.h>
Public Types
typedef QString(* DecoderFn) (const QByteArray &localfileName)
This is a typedef for a pointer to a function with the following signature:
typedef QByteArray(* EncoderFn) (const QString &fileName)
This is a typedef for a pointer to a function with the following signature:
enum FileError {
NoError = 0, ReadError = 1, WriteError = 2, FatalError = 3,
ResourceError = 4, OpenError = 5, AbortError = 6, TimeOutError = 7,
UnspecifiedError = 8, RemoveError = 9, RenameError = 10, PositionError = 11,
ResizeError = 12, PermissionsError = 13, CopyError = 14
}
This enum describes the errors that may be returned by the error() function.
enum FileHandleFlag { AutoCloseHandle = 0x0001, DontCloseHandle = 0 }
This enum is used when opening a file to specify additional options which only apply to files and not to a generic QIODevice.
enum MemoryMapFlags { NoOptions = 0 }
This enum describes special options that may be used by the map() function.
enum Permission {
ReadOwner = 0x4000, WriteOwner = 0x2000, ExeOwner = 0x1000, ReadUser = 0x0400,
WriteUser = 0x0200, ExeUser = 0x0100, ReadGroup = 0x0040, WriteGroup = 0x0020,
ExeGroup = 0x0010, ReadOther = 0x0004, WriteOther = 0x0002, ExeOther = 0x0001
}
This enum is used by the permission() function to report the permissions and ownership of a file.
Public Types inherited from QIODevice
enum OpenModeFlag {
NotOpen = 0x0000, ReadOnly = 0x0001, WriteOnly = 0x0002, ReadWrite = ReadOnly | WriteOnly,
Append = 0x0004, Truncate = 0x0008, Text = 0x0010, Unbuffered = 0x0020
}
This enum is used with open() to describe the mode in which a device is opened.
Public Functions
bool atEnd () const
Returns true if the end of the file has been reached; otherwise returns false.
virtual void close ()
Calls QFile::flush() and closes the file.
bool copy (const QString &newName)
Copies the file currently specified by fileName() to a file called newName.
FileError error () const
Returns the file error status.
bool exists () const
Returns true if the file specified by fileName() exists; otherwise returns false.
virtual QAbstractFileEngine * fileEngine () const
Returns the QIOEngine for this QFile object.
QString fileName () const
Returns the name set by setFileName() or to the QFile constructors.
bool flush ()
Flushes any buffered data to the file.
int handle () const
Returns the file handle of the file.
bool isSequential () const
Returns true if the file can only be manipulated sequentially; otherwise returns false.
bool link (const QString &newName)
Creates a link named linkName that points to the file currently specified by fileName().
uchar * map (qint64 offset, qint64 size, MemoryMapFlags flags=NoOptions)
Maps size bytes of the file into memory starting at offset.
bool open (OpenMode flags)
Opens the file using OpenMode mode, returning true if successful; otherwise false.
bool open (FILE *f, OpenMode flags)
Opens the existing file handle fh in the given mode.
bool open (int fd, OpenMode flags)
Opens the existing file descriptor fd in the given mode.
bool open (FILE *f, OpenMode ioFlags, FileHandleFlags handleFlags)
Opens the existing file handle fh in the given mode.
bool open (int fd, OpenMode ioFlags, FileHandleFlags handleFlags)
Opens the existing file descriptor fd in the given mode.
Permissions permissions () const
Returns the complete OR-ed together combination of QFile::Permission for the file.
qint64 pos () const
Reimplemented Function
QFile ()
QFile (const QString &name)
Constructs a new file object to represent the file with the given name.
QFile (QObject *parent)
Constructs a new file object with the given parent.
QFile (const QString &name, QObject *parent)
Constructs a new file object with the given parent to represent the file with the specified name.
QString readLink () const
Use symLinkTarget() instead.
bool remove ()
Removes the file specified by fileName().
bool rename (const QString &newName)
Renames the file currently specified by fileName() to newName.
bool resize (qint64 sz)
Sets the file size (in bytes) sz.
bool seek (qint64 offset)
For random-access devices, this function sets the current position to pos, returning true on success, or false if an error occurred.
void setFileName (const QString &name)
Sets the name of the file.
bool setPermissions (Permissions permissionSpec)
Sets the permissions for the file to the permissions specified.
qint64 size () const
Returns the size of the file.
QString symLinkTarget () const
Returns the absolute path of the file or directory a symlink (or shortcut on Windows) points to, or a an empty string if the object isn't a symbolic link.
bool unmap (uchar *address)
Unmaps the memory address.
void unsetError ()
Sets the file's error to QFile::NoError.
~QFile ()
Destroys the file object, closing it if necessary.
Public Functions inherited from QIODevice
virtual qint64 bytesAvailable () const
Returns the number of bytes that are available for reading.
virtual qint64 bytesToWrite () const
For buffered devices, this function returns the number of bytes waiting to be written.
virtual bool canReadLine () const
Returns true if a complete line of data can be read from the device; otherwise returns false.
QString errorString () const
Returns a human-readable description of the last device error that occurred.
bool getChar (char *c)
Reads one character from the device and stores it in c.
bool isOpen () const
Returns true if the device is open; otherwise returns false.
bool isReadable () const
Returns true if data can be read from the device; otherwise returns false.
bool isTextModeEnabled () const
Returns true if the Text flag is enabled; otherwise returns false.
bool isWritable () const
Returns true if data can be written to the device; otherwise returns false.
OpenMode openMode () const
Returns the mode in which the device has been opened; i.e.
qint64 peek (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, without side effects (i.
QByteArray peek (qint64 maxlen)
Peeks at most maxSize bytes from the device, returning the data peeked as a QByteArray.
bool putChar (char c)
Writes the character c to the device.
QIODevice ()
Constructs a QIODevice object.
QIODevice (QObject *parent)
Constructs a QIODevice object with the given parent.
qint64 read (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, and returns the number of bytes read.
QByteArray read (qint64 maxlen)
Reads at most maxSize bytes from the device, and returns the data read as a QByteArray.
QByteArray readAll ()
Reads all available data from the device, and returns it as a QByteArray.
qint64 readLine (char *data, qint64 maxlen)
This function reads a line of ASCII characters from the device, up to a maximum of maxSize - 1 bytes, stores the characters in data, and returns the number of bytes read.
QByteArray readLine (qint64 maxlen=0)
Reads a line from the device, but no more than maxSize characters, and returns the result as a QByteArray.
virtual bool reset ()
Seeks to the start of input for random-access devices.
void setTextModeEnabled (bool enabled)
If enabled is true, this function sets the Text flag on the device; otherwise the Text flag is removed.
void ungetChar (char c)
Puts the character c back into the device, and decrements the current position unless the position is 0.
virtual bool waitForBytesWritten (int msecs)
For buffered devices, this function waits until a payload of buffered written data has been written to the device and the bytesWritten() signal has been emitted, or until msecs milliseconds have passed.
virtual bool waitForReadyRead (int msecs)
Blocks until new data is available for reading and the readyRead() signal has been emitted, or until msecs milliseconds have passed.
qint64 write (const char *data, qint64 len)
Writes at most maxSize bytes of data from data to the device.
qint64 write (const char *data)
Writes data from a zero-terminated string of 8-bit characters to the device.
qint64 write (const QByteArray &data)
Writes the content of byteArray to the device.
virtual ~QIODevice ()
The destructor is virtual, and QIODevice is an abstract base class.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool copy (const QString &fileName, const QString &newName)
Copies the file fileName to newName.
static QString decodeName (const QByteArray &localFileName)
This does the reverse of QFile::encodeName() using localFileName.
static QString decodeName (const char *localFileName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the Unicode version of the given localFileName.
static QByteArray encodeName (const QString &fileName)
By default, this function converts fileName to the local 8-bit encoding determined by the user's locale.
static bool exists (const QString &fileName)
Returns true if the file specified by fileName exists; otherwise returns false.
static bool link (const QString &oldname, const QString &newName)
Creates a link named linkName that points to the file fileName.
static Permissions permissions (const QString &filename)
Returns the complete OR-ed together combination of QFile::Permission for fileName.
static QString readLink (const QString &fileName)
Use symLinkTarget() instead.
static bool remove (const QString &fileName)
Removes the file specified by the fileName given.
static bool rename (const QString &oldName, const QString &newName)
Renames the file oldName to newName.
static bool resize (const QString &filename, qint64 sz)
Sets fileName to size (in bytes) sz.
static void setDecodingFunction (DecoderFn)
Sets the function for decoding 8-bit file names.
static void setEncodingFunction (EncoderFn)
Sets the function for encoding Unicode file names.
static bool setPermissions (const QString &filename, Permissions permissionSpec)
Sets the permissions for fileName file to permissions.
static QString symLinkTarget (const QString &fileName)
Returns the absolute path of the file or directory referred to by the symlink (or shortcut on Windows) specified by fileName, or returns an empty string if the fileName does not correspond to a symbolic link.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
QFile (QFilePrivate &dd, QObject *parent=0)
qint64 readData (char *data, qint64 maxlen)
Reimplemented Function
qint64 readLineData (char *data, qint64 maxlen)
Reimplemented Function
qint64 writeData (const char *data, qint64 len)
Reimplemented Function
Protected Functions inherited from QIODevice
QIODevice (QIODevicePrivate &dd, QObject *parent=0)
void setErrorString (const QString &errorString)
Sets the human readable description of the last device error that occurred to str.
void setOpenMode (OpenMode openMode)
Sets the OpenMode of the device to openMode.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QIODevice
void aboutToClose ()
This signal is emitted when the device is about to close.
void bytesWritten (qint64 bytes)
This signal is emitted every time a payload of data has been written to the device.
void readChannelFinished ()
This signal is emitted when the input (reading) stream is closed in this device.
void readyRead ()
This signal is emitted once every time new data is available for reading from the device.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QFile class provides an interface for reading from and writing to files.
Note
This class or function is reentrant.
QFile is an I/O device for reading and writing text and binary files and The Qt Resource System{resources}. A QFile may be used by itself or, more conveniently, with a QTextStream or QDataStream.
The file name is usually passed in the constructor, but it can be set at any time using setFileName(). QFile expects the file separator to be '/' regardless of operating system. The use of other separators (e.g., '\') is not supported.
You can check for a file's existence using exists(), and remove a file using remove(). (More advanced file system related operations are provided by QFileInfo and QDir.)
The file is opened with open(), closed with close(), and flushed with flush(). Data is usually read and written using QDataStream or QTextStream, but you can also call the QIODevice-inherited functions read(), readLine(), readAll(), write(). QFile also inherits getChar(), putChar(), and ungetChar(), which work one character at a time.
The size of the file is returned by size(). You can get the current file position using pos(), or move to a new file position using seek(). If you've reached the end of the file, atEnd() returns true.
Reading Files Directly
The following example reads a text file line by line:
    QFile file("in.txt");
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;
    while (!file.atEnd()) {
        QByteArray line = file.readLine();
        process_line(line);
    }
The QIODevice::Text flag passed to open() tells Qt to convert Windows-style line terminators ("\\r\\n") into C++-style terminators ("\\n"). By default, QFile assumes binary, i.e. it doesn't perform any conversion on the bytes stored in the file.
Using Streams to Read Files
The next example uses QTextStream to read a text file line by line:
    QFile file("in.txt");
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;
    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine();
        process_line(line);
    }
QTextStream takes care of converting the 8-bit data stored on disk into a 16-bit Unicode QString. By default, it assumes that the user system's local 8-bit encoding is used (e.g., ISO 8859-1 for most of Europe; see QTextCodec::codecForLocale() for details). This can be changed using setCodec().
To write text, we can use operator<<(), which is overloaded to take a QTextStream on the left and various data types (including QString) on the right:
    QFile file("out.txt");
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return;
    QTextStream out(&file);
    out << "The magic number is: " << 49 << "\n";
QDataStream is similar, in that you can use operator<<() to write data and operator>>() to read it back. See the class documentation for details.
When you use QFile, QFileInfo, and QDir to access the file system with Qt, you can use Unicode file names. On Unix, these file names are converted to an 8-bit encoding. If you want to use standard C++ APIs (<cstdio> or <iostream>) or platform-specific APIs to access files instead of QFile, you can use the encodeName() and decodeName() functions to convert between Unicode file names and 8-bit file names.
On Unix, there are some special system files (e.g. in /proc) for which size() will always return 0, yet you may still be able to read more data from such a file; the data is generated in direct response to you calling read(). In this case, however, you cannot use atEnd() to determine if there is more data to read (since atEnd() will return true for a file that claims to have size 0). Instead, you should either call readAll(), or call read() or readLine() repeatedly until no more data can be read. The next example uses QTextStream to read /proc/modules line by line:
    QFile file("/proc/modules");
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;
    QTextStream in(&file);
    QString line = in.readLine();
    while (!line.isNull()) {
        process_line(line);
        line = in.readLine();
    }
Signals
Unlike other QIODevice implementations, such as QTcpSocket, QFile does not emit the aboutToClose(), bytesWritten(), or readyRead() signals. This implementation detail means that QFile is not suitable for reading and writing certain types of files, such as device files on Unix platforms.
Platform Specific Issues
File permissions are handled differently on Linux/Mac OS X and Windows. In a non writable directory on Linux, files cannot be created. This is not always the case on Windows, where, for instance, the 'My Documents' directory usually is not writable, but it is still possible to create files in it.
See also
QTextStream, QDataStream, QFileInfo, QDir, {The Qt Resource System}
Definition at line 65 of file qfile.h.
Typedefs
DecoderFn
QFile::DecoderFn
This is a typedef for a pointer to a function with the following signature:
QString myDecoderFunc(const QByteArray &localFileName);
See also
setDecodingFunction()
Definition at line 124 of file qfile.h.
EncoderFn
QFile::EncoderFn
This is a typedef for a pointer to a function with the following signature:
QByteArray myEncoderFunc(const QString &fileName);
See also
setEncodingFunction(), encodeName()
Definition at line 123 of file qfile.h.
Enumerations
FileError
enum QFile::FileError
This enum describes the errors that may be returned by the error() function.
NoError No error occurred.
ReadError An error occurred when reading from the file.
WriteError An error occurred when writing to the file.
FatalError A fatal error occurred.
ResourceError
OpenError The file could not be opened.
AbortError The operation was aborted.
TimeOutError A timeout occurred.
UnspecifiedError An unspecified error occurred.
RemoveError The file could not be removed.
RenameError The file could not be renamed.
PositionError The position in the file could not be changed.
ResizeError The file could not be resized.
PermissionsError The file could not be accessed.
CopyError The file could not be copied.
ConnectError
Enumerator
NoError
ReadError
WriteError
FatalError
ResourceError
OpenError
AbortError
TimeOutError
UnspecifiedError
RemoveError
RenameError
PositionError
ResizeError
PermissionsError
CopyError
Definition at line 74 of file qfile.h.
                    {
         NoError = 0,
         ReadError = 1,
         WriteError = 2,
         FatalError = 3,
         ResourceError = 4,
         OpenError = 5,
         AbortError = 6,
         TimeOutError = 7,
         UnspecifiedError = 8,
         RemoveError = 9,
         RenameError = 10,
         PositionError = 11,
         ResizeError = 12,
         PermissionsError = 13,
         CopyError = 14
 #ifdef QT3_SUPPORT
         , ConnectError = 30
 #endif
     };
FileHandleFlag
enum QFile::FileHandleFlag
This enum is used when opening a file to specify additional options which only apply to files and not to a generic QIODevice.
Since
4.8
AutoCloseHandle The file handle passed into open() should be closed by close(), the default behaviour is that close just flushes the file and the application is responsible for closing the file handle. When opening a file by name, this flag is ignored as Qt always "owns" the file handle and must close it.
DontCloseHandle The file handle passed into open() will not be closed by Qt. The application must ensure that close() is called.
Enumerator
AutoCloseHandle
DontCloseHandle
Definition at line 103 of file qfile.h.
{
         AutoCloseHandle = 0x0001,
         DontCloseHandle = 0
     };
MemoryMapFlags
enum QFile::MemoryMapFlags
This enum describes special options that may be used by the map() function.
Since
4.4
NoOptions No options.
Enumerator
NoOptions
Definition at line 180 of file qfile.h.
{
         NoOptions = 0
     };
Permission
enum QFile::Permission
This enum is used by the permission() function to report the permissions and ownership of a file.
The values may be OR-ed together to test multiple permissions and ownership values.
ReadOwner The file is readable by the owner of the file.
WriteOwner The file is writable by the owner of the file.
ExeOwner The file is executable by the owner of the file.
ReadUser The file is readable by the user.
WriteUser The file is writable by the user.
ExeUser The file is executable by the user.
ReadGroup The file is readable by the group.
WriteGroup The file is writable by the group.
ExeGroup The file is executable by the group.
ReadOther The file is readable by anyone.
WriteOther The file is writable by anyone.
ExeOther The file is executable by anyone.
Warning
Because of differences in the platforms supported by Qt, the semantics of ReadUser, WriteUser and ExeUser are platform-dependent: On Unix, the rights of the owner of the file are returned and on Windows the rights of the current user are returned. This behavior might change in a future Qt version.
Note that Qt does not by default check for permissions on NTFS file systems, as this may decrease the performance of file handling considerably. It is possible to force permission checking on NTFS by including the following code in your source:
extern Q_CORE_EXPORT int qt_ntfs_permission_lookup;
Permission checking is then turned on and off by incrementing and decrementing qt_ntfs_permission_lookup by 1.
qt_ntfs_permission_lookup++; // turn checking on
qt_ntfs_permission_lookup--; // turn it off again
Enumerator
ReadOwner
WriteOwner
ExeOwner
ReadUser
WriteUser
ExeUser
ReadGroup
WriteGroup
ExeGroup
ReadOther
WriteOther
ExeOther
Definition at line 95 of file qfile.h.
                     {
         ReadOwner = 0x4000, WriteOwner = 0x2000, ExeOwner = 0x1000,
         ReadUser  = 0x0400, WriteUser  = 0x0200, ExeUser  = 0x0100,
         ReadGroup = 0x0040, WriteGroup = 0x0020, ExeGroup = 0x0010,
         ReadOther = 0x0004, WriteOther = 0x0002, ExeOther = 0x0001
     };
Constructors and Destructors
QFile() [1/5]
QFile::QFile ()
Warning
This function is not part of the public interface.
Definition at line 417 of file qfile.cpp.
Referenced by copy(), link(), permissions(), remove(), rename(), resize(), QFilePrivate::setError(), and setPermissions().
     : QIODevice(*new QFilePrivate, 0)
 {
 }
QFile() [2/5]
QFile::QFile (const QString & name)
Constructs a new file object to represent the file with the given name.
Definition at line 431 of file qfile.cpp.
     : QIODevice(*new QFilePrivate, 0)
 {
     Q_D(QFile);
     d->fileName = name;
 }
QFile() [3/5]
QFile::QFile (QObject * parent) explicit
Constructs a new file object with the given parent.
Definition at line 424 of file qfile.cpp.
     : QIODevice(*new QFilePrivate, parent)
 {
 }
QFile() [4/5]
QFile::QFile (const QString & name, QObject * parent)
Constructs a new file object with the given parent to represent the file with the specified name.
Definition at line 441 of file qfile.cpp.
     : QIODevice(*new QFilePrivate, parent)
 {
     Q_D(QFile);
     d->fileName = name;
 }
~QFile()
QFile::~QFile ()
Destroys the file object, closing it if necessary.
Definition at line 459 of file qfile.cpp.
 {
     close();
 }
QFile() [5/5]
QFile::QFile (QFilePrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 450 of file qfile.cpp.
     : QIODevice(dd, parent)
 {
 }
Functions
atEnd()
bool QFile::atEnd () const virtual
Returns true if the end of the file has been reached; otherwise returns false.
For regular empty files on Unix (e.g. those in /proc), this function returns true, since the file system reports that the size of such a file is 0. Therefore, you should not depend on atEnd() when reading data from such a file, but rather call read() until no more data can be read.
Reimplemented from QIODevice.
Definition at line 1735 of file qfile.cpp.
Referenced by copy(), QBenchmarkValgrindUtils::extractResult(), fontFile(), QHostInfo::localDomainName(), qt_parseEtcLpPrinters(), qt_parseNsswitchConf(), qt_parsePrintcap(), qt_parsePrintersConf(), and QCoreApplicationData::~QCoreApplicationData().
 {
     Q_D(const QFile);
     // If there's buffered data left, we're not at the end.
     if (!d->buffer.isEmpty())
         return false;
     if (!isOpen())
         return true;
     if (!d->ensureFlushed())
         return false;
     // If the file engine knows best, say what it says.
     if (d->fileEngine->supportsExtension(QAbstractFileEngine::AtEndExtension)) {
         // Check if the file engine supports AtEndExtension, and if it does,
         // check if the file engine claims to be at the end.
         return d->fileEngine->atEnd();
     }
     // if it looks like we are at the end, or if size is not cached,
     // fall through to bytesAvailable() to make sure.
     if (pos() < d->cachedSize)
         return false;
     // Fall back to checking how much is available (will stat files).
     return bytesAvailable() == 0;
 }
close()
void QFile::close () virtual
Calls QFile::flush() and closes the file.
Errors from flush are ignored.
See also
QIODevice::close()
Reimplemented from QIODevice.
Definition at line 1680 of file qfile.cpp.
Referenced by QNetworkManagerEngine::bytesReceived(), QConnmanEngine::bytesReceived(), QNetworkManagerEngine::bytesWritten(), QConnmanEngine::bytesWritten(), QUnixPrintWidgetPrivate::checkFields(), QNetworkAccessFileBackend::closeDownstreamChannel(), QMacPasteboardMimeVCard::convertFromMime(), copy(), QTemporaryFile::createLocalFile(), QNetworkDiskCache::data(), QGraphicsAnchorLayoutPrivate::dumpGraph(), QPdfEnginePrivate::embedFont(), QtopiaPrintEngine::end(), QZipReader::extractAll(), QNetworkDiskCache::fileMetaData(), fontPath(), QDirectFBPixmapData::fromFile(), QGLPixmapData::fromFile(), QTransportAuthPrivate::getClientKey(), QScriptEngine::importExtension(), QAxScriptManager::load(), QTextBrowser::loadResource(), QTextDocument::loadResource(), QPictureIO::pictureFormat(), qt_parse_pattern(), QPictureIO::read(), registerFont(), remove(), rename(), setFileName(), QSslSocketBackendPrivate::startHandshake(), QNetworkAccessFileBackend::uploadReadyReadSlot(), QPictureIO::write(), QCoreApplicationData::~QCoreApplicationData(), ~QFile(), and QTemporaryFile::~QTemporaryFile().
 {
     Q_D(QFile);
     if(!isOpen())
         return;
     bool flushed = flush();
     QIODevice::close();
     // reset write buffer
     d->lastWasWrite = false;
     d->writeBuffer.clear();
     // keep earlier error from flush
     if (d->fileEngine->close() && flushed)
         unsetError();
     else if (flushed)
         d->setError(d->fileEngine->error(), d->fileEngine->errorString());
 }
copy() [1/2]
bool QFile::copy (const QString & newName)
Copies the file currently specified by fileName() to a file called newName.
Returns true if successful; otherwise returns false.
Note that if a file with the name newName already exists, copy() returns false (i.e. QFile will not overwrite it).
The source file is closed before it is copied.
See also
setFileName()
Definition at line 926 of file qfile.cpp.
Referenced by QDragManager::drag(), QDirModel::dropMimeData(), and QFileSystemModel::dropMimeData().
 {
     Q_D(QFile);
     if (d->fileName.isEmpty()) {
         qWarning("QFile::copy: Empty or null file name");
         return false;
     }
     if (QFile(newName).exists()) {
         // ### Race condition. If a file is moved in after this, it /will/ be
         // overwritten. On Unix, the proper solution is to use hardlinks:
         // return ::link(old, new) && ::remove(old); See also rename().
         d->setError(QFile::CopyError, tr("Destination file exists"));
         return false;
     }
     unsetError();
     close();
     if(error() == QFile::NoError) {
         if(fileEngine()->copy(newName)) {
             unsetError();
             return true;
         } else {
             bool error = false;
             if(!open(QFile::ReadOnly)) {
                 error = true;
                 d->setError(QFile::CopyError, tr("Cannot open %1 for input").arg(d->fileName));
             } else {
                 QString fileTemplate = QLatin1String("%1/qt_temp.XXXXXX");
 #ifdef QT_NO_TEMPORARYFILE
                 QFile out(fileTemplate.arg(QFileInfo(newName).path()));
                 if (!out.open(QIODevice::ReadWrite))
                     error = true;
 #else
                 QTemporaryFile out(fileTemplate.arg(QFileInfo(newName).path()));
                 if (!out.open()) {
                     out.setFileTemplate(fileTemplate.arg(QDir::tempPath()));
                     if (!out.open())
                         error = true;
                 }
 #endif
                 if (error) {
                     out.close();
                     close();
                     d->setError(QFile::CopyError, tr("Cannot open for output"));
                 } else {
                     char block[4096];
                     qint64 totalRead = 0;
                     while(!atEnd()) {
                         qint64 in = read(block, sizeof(block));
                         if (in <= 0)
                             break;
                         totalRead += in;
                         if(in != out.write(block, in)) {
                             close();
                             d->setError(QFile::CopyError, tr("Failure to write block"));
                             error = true;
                             break;
                         }
                     }
                     if (totalRead != size()) {
                         // Unable to read from the source. The error string is
                         // already set from read().
                         error = true;
                     }
                     if (!error && !out.rename(newName)) {
                         error = true;
                         close();
                         d->setError(QFile::CopyError, tr("Cannot create %1 for output").arg(newName));
                     }
 #ifdef QT_NO_TEMPORARYFILE
                     if (error)
                         out.remove();
 #else
                     if (!error)
                         out.setAutoRemove(false);
 #endif
                 }
             }
             if(!error) {
                 QFile::setPermissions(newName, permissions());
                 close();
                 unsetError();
                 return true;
             }
         }
     }
     return false;
 }
copy() [2/2]
bool QFile::copy (const QString & fileName, const QString & newName) static
Copies the file fileName to newName.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
If a file with the name newName already exists, copy() returns false (i.e., QFile will not overwrite it).
See also
rename()
Definition at line 1031 of file qfile.cpp.
 {
     return QFile(fileName).copy(newName);
 }
decodeName() [1/2]
QString QFile::decodeName (const QByteArray & localFileName) static
This does the reverse of QFile::encodeName() using localFileName.
See also
setDecodingFunction(), encodeName()
Definition at line 552 of file qfile.cpp.
Referenced by QCoreApplication::applicationFilePath(), QFontEngineQPF::cleanUpAfterClientCrash(), QWSServerPrivate::cleanupFonts(), QZipReader::extractAll(), QFileSystemEngine::getLinkTarget(), QFileSystemEngine::homePath(), QGuiPlatformPlugin::iconThemeSearchPaths(), initDefaultPaths(), loadSingleEngine(), QHostInfo::localDomainName(), QFontEngineQPF::QFontEngineQPF(), QFileSystemEntry::resolveFilePath(), QFileSystemEngine::resolveGroupName(), QFileSystemEngine::resolveUserName(), and QFileSystemEngine::tempPath().
 {
     return (*QFilePrivate::decoder)(localFileName);
 }
decodeName() [2/2]
QString QFile::decodeName (const char * localFileName) inline static
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the Unicode version of the given localFileName.
See encodeName() for details.
Definition at line 127 of file qfile.h.
         { return decodeName(QByteArray(localFileName)); }
encodeName()
QByteArray QFile::encodeName (const QString & fileName) static
By default, this function converts fileName to the local 8-bit encoding determined by the user's locale.
This is sufficient for file names that the user chooses. File names hard-coded into the application should only use 7-bit ASCII filename characters.
See also
decodeName() setEncodingFunction()
Definition at line 528 of file qfile.cpp.
Referenced by QProcessPrivate::_q_notified(), QInotifyFileSystemWatcherEngine::addPaths(), QKqueueFileSystemWatcherEngine::addPaths(), QZipWriter::addSymLink(), QSharedMemoryPrivate::attach(), QSystemSemaphorePrivate::cleanHandle(), QFontEngineQPF::cleanUpAfterClientCrash(), QSharedMemoryPrivate::create(), QProcessPrivate::createChannel(), QFileSystemEngine::createDirectory(), QSharedMemoryPrivate::createUnixKeyFile(), QSharedMemoryPrivate::detach(), QTranslatorPrivate::do_load(), QFileSystemEngine::getLinkTarget(), QSystemSemaphorePrivate::handle(), QSharedMemoryPrivate::handle(), initializeDb(), QLibraryPrivate::isPlugin(), QLibraryPrivate::load_sys(), QFileDialogPrivate::maxNameLength(), QSQLite2Driver::open(), QWSSoundServerPrivate::openFile(), QBasicUnixFontDatabase::populateFontDatabase(), QPlatformFontDatabase::populateFontDatabase(), QFontEngineQPA::QFontEngineQPA(), QFontEngineQPF::QFontEngineQPF(), QFontEngineQPF1::QFontEngineQPF1(), qt_parse_pattern(), registerFont(), QDynamicFileResourceRoot::registerSelf(), QFileSystemEngine::removeDirectory(), QFileSystemEntry::resolveNativeFilePath(), QPluginLoader::setFileName(), QProcessPrivate::startDetached(), and QProcessPrivate::startProcess().
 {
     return (*QFilePrivate::encoder)(fileName);
 }
error()
QFile::FileError QFile::error () const
Returns the file error status.
The I/O device status returns an error code. For example, if open() returns false, or a read/write operation returns -1, this function can be called to find out the reason why the operation failed.
See also
unsetError()
Definition at line 1984 of file qfile.cpp.
Referenced by copy(), QIODevice::errorString(), fontPath(), QPdfBaseEngine::newPage(), QZipReader::QZipReader(), QZipWriter::QZipWriter(), QNetworkAccessFileBackend::readMoreFromFile(), remove(), rename(), and QNetworkDiskCachePrivate::storeItem().
 {
     Q_D(const QFile);
     return d->error;
 }
exists() [1/2]
bool QFile::exists () const
Returns true if the file specified by fileName() exists; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
fileName(), setFileName()
Definition at line 626 of file qfile.cpp.
Referenced by QFileDialogPrivate::_q_createDirectory(), QDeclarativeImportDatabase::addImportPath(), QDeclarativeImportDatabase::addPluginPath(), QCoreApplicationPrivate::appendApplicationPathToLibraryPaths(), QNetworkManagerEngine::bytesReceived(), QConnmanEngine::bytesReceived(), QNetworkManagerEngine::bytesWritten(), QConnmanEngine::bytesWritten(), QMacPasteboardMimeVCard::convertFromMime(), copy(), QSharedMemoryPrivate::createUnixKeyFile(), QZipWriter::exists(), QZipReader::exists(), QDir::exists(), QZipReader::extractAll(), QLibraryInfoPrivate::findConfiguration(), fontPath(), QDirectFBPixmapData::fromFile(), QDirectFbBlitterPlatformPixmap::fromFile(), QTransportAuthPrivate::getClientKey(), QGtkStylePrivate::getThemeName(), QSharedMemoryPrivate::handle(), QAxBase::initialize(), initializeDb(), isDirPath(), launchWebBrowser(), QCoreApplication::libraryPaths(), QLibraryPrivate::load_sys(), QFontDatabasePrivate::loadFromCache(), loadSingleEngine(), QNetworkAccessFileBackend::open(), QBasicUnixFontDatabase::populateFontDatabase(), QPlatformFontDatabase::populateFontDatabase(), QIconTheme::QIconTheme(), qmlsqldatabase_open_sync(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QDynamicFileResourceRoot::registerSelf(), rename(), QDir::rename(), QNetworkDiskCachePrivate::storeItem(), QConfFileSettingsPrivate::syncConfFile(), QFileDialogPrivate::typedFiles(), and QAxFactory::validateLicenseKey().
 {
     // 0x1000000 = QAbstractFileEngine::Refresh, forcing an update
     return (fileEngine()->fileFlags(QAbstractFileEngine::FlagsMask
                                     | QAbstractFileEngine::FileFlag(0x1000000)) & QAbstractFileEngine::ExistsFlag);
 }
exists() [2/2]
bool QFile::exists (const QString & fileName) static
Returns true if the file specified by fileName exists; otherwise returns false.
Definition at line 639 of file qfile.cpp.
 {
     return QFileInfo(fileName).exists();
 }
fileEngine()
QAbstractFileEngine * QFile::fileEngine () const virtual
Returns the QIOEngine for this QFile object.
Warning
This function is not part of the public interface.
Reimplemented in QTemporaryFile.
Definition at line 1965 of file qfile.cpp.
Referenced by QFontDatabase::addApplicationFont(), copy(), QTemporaryFile::createLocalFile(), exists(), fileName(), QFreetypeFace::getFace(), link(), map(), open(), permissions(), readLink(), remove(), rename(), resize(), setPermissions(), size(), and unmap().
 {
     Q_D(const QFile);
     if(!d->fileEngine)
         d->fileEngine = QAbstractFileEngine::create(d->fileName);
     return d->fileEngine;
 }
fileName()
QString QFile::fileName () const
Returns the name set by setFileName() or to the QFile constructors.
See also
setFileName(), QFileInfo::fileName()
Definition at line 470 of file qfile.cpp.
Referenced by __fileOpen(), QMacPasteboardMimeVCard::convertFromMime(), QGraphicsAnchorLayoutPrivate::dumpGraph(), encodeName(), QTextDocumentWriter::fileName(), QImageWriter::fileName(), QImageReader::fileName(), QImageReaderPrivate::initHandler(), QFontDatabasePrivate::loadFromCache(), QTemporaryFile::open(), open(), QIconTheme::QIconTheme(), QIODevice::QIODevice(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QCacheItem::read(), registerFont(), QFileInfo::setFile(), setFileName(), and QConfFileSettingsPrivate::syncConfFile().
 {
     return fileEngine()->fileName(QAbstractFileEngine::DefaultName);
 }
flush()
bool QFile::flush ()
Flushes any buffered data to the file.
Returns true if successful; otherwise returns false.
Definition at line 1645 of file qfile.cpp.
Referenced by close(), QTextStreamPrivate::flushWriteBuffer(), registerFont(), QNetworkAccessFileBackend::uploadReadyReadSlot(), and writeData().
 {
     Q_D(QFile);
     if (!d->fileEngine) {
         qWarning("QFile::flush: No file engine. Is IODevice open?");
         return false;
     }
     if (!d->writeBuffer.isEmpty()) {
         qint64 size = d->writeBuffer.size();
         if (_qfile_writeData(d->fileEngine, &d->writeBuffer) != size) {
             QFile::FileError err = d->fileEngine->error();
             if(err == QFile::UnspecifiedError)
                 err = QFile::WriteError;
             d->setError(err, d->fileEngine->errorString());
             return false;
         }
     }
     if (!d->fileEngine->flush()) {
         QFile::FileError err = d->fileEngine->error();
         if(err == QFile::UnspecifiedError)
             err = QFile::WriteError;
         d->setError(err, d->fileEngine->errorString());
         return false;
     }
     return true;
 }
handle()
int QFile::handle () const
Returns the file handle of the file.
This is a small positive integer, suitable for use with C library functions such as fdopen() and fcntl(). On systems that use file descriptors for sockets (i.e. Unix systems, but not Windows) the handle can be used with QSocketNotifier as well.
If the file is not open, or there is an error, handle() returns -1.
This function is not supported on Windows CE.
On Symbian, this function returns -1 if the file was opened normally, as Symbian OS native file handles do not fit in an int, and are incompatible with C library functions that the handle would be used for. If the file was opened using the overloads that take an open C library file handle / file descriptor, then this function returns that same handle.
See also
QSocketNotifier
Definition at line 1419 of file qfile.cpp.
Referenced by QTextStreamPrivate::fillReadBuffer(), QPatternist::ColorOutputPrivate::isColoringPossible(), and QConfFileSettingsPrivate::syncConfFile().
 {
     Q_D(const QFile);
     if (!isOpen() || !d->fileEngine)
         return -1;
     return d->fileEngine->handle();
 }
isSequential()
bool QFile::isSequential () const virtual
Returns true if the file can only be manipulated sequentially; otherwise returns false.
Most files support random-access, but some special files may not.
See also
QIODevice::isSequential()
Reimplemented from QIODevice.
Definition at line 1044 of file qfile.cpp.
Referenced by QFilePrivate::putCharHelper(), and rename().
 {
     Q_D(const QFile);
     return d->fileEngine && d->fileEngine->isSequential();
 }
link() [1/2]
bool QFile::link (const QString & linkName)
Creates a link named linkName that points to the file currently specified by fileName().
What a link is depends on the underlying filesystem (be it a shortcut on Windows or a symbolic link on Unix). Returns true if successful; otherwise returns false.
This function will not overwrite an already existing entity in the file system; in this case, link() will return false and set QFile::error() to return QFile::RenameError.
Note
To create a valid link on Windows, linkName must have a .lnk file extension.
Symbian filesystem does not support links.
See also
setFileName()
Definition at line 877 of file qfile.cpp.
Referenced by QDirModel::dropMimeData(), QFileSystemModel::dropMimeData(), and QZipReader::extractAll().
 {
     Q_D(QFile);
     if (d->fileName.isEmpty()) {
         qWarning("QFile::link: Empty or null file name");
         return false;
     }
     QFileInfo fi(linkName);
     if(fileEngine()->link(fi.absoluteFilePath())) {
         unsetError();
         return true;
     }
     d->setError(QFile::RenameError, d->fileEngine->errorString());
     return false;
 }
link() [2/2]
bool QFile::link (const QString & fileName, const QString & linkName) static
Creates a link named linkName that points to the file fileName.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
What a link is depends on the underlying filesystem (be it a shortcut on Windows or a symbolic link on Unix). Returns true if successful; otherwise returns false.
See also
link()
Definition at line 908 of file qfile.cpp.
 {
     return QFile(fileName).link(linkName);
 }
map()
uchar * QFile::map (qint64 offset, qint64 size, MemoryMapFlags flags = NoOptions)
Maps size bytes of the file into memory starting at offset.
Since
4.4 A file should be open for a map to succeed but the file does not need to stay open after the memory has been mapped. When the QFile is destroyed or a new file is opened with this object, any maps that have not been unmapped will automatically be unmapped.
Any mapping options can be passed through flags.
Returns a pointer to the memory or 0 if there is an error.
Note
On Windows CE 5.0 the file will be closed before mapping occurs.
See also
unmap(), QAbstractFileEngine::supportsExtension()
Definition at line 1460 of file qfile.cpp.
Referenced by QNetworkDiskCache::data(), and qt_parse_pattern().
 {
     Q_D(QFile);
     if (fileEngine()
             && d->fileEngine->supportsExtension(QAbstractFileEngine::MapExtension)) {
         unsetError();
         uchar *address = d->fileEngine->map(offset, size, flags);
         if (address == 0)
             d->setError(d->fileEngine->error(), d->fileEngine->errorString());
         return address;
     }
     return 0;
 }
open() [1/5]
bool QFile::open (OpenMode mode) virtual
Opens the file using OpenMode mode, returning true if successful; otherwise false.
The mode must be QIODevice::ReadOnly, QIODevice::WriteOnly, or QIODevice::ReadWrite. It may also have additional flags, such as QIODevice::Text and QIODevice::Unbuffered.
Note
In QIODevice::WriteOnly or QIODevice::ReadWrite mode, if the relevant file does not already exist, this function will try to create a new file before opening it.
See also
QIODevice::OpenMode, setFileName()
Reimplemented from QIODevice.
Reimplemented in QTemporaryFile.
Definition at line 1064 of file qfile.cpp.
Referenced by __fileOpen(), QFontDatabase::addApplicationFont(), QTransportAuth::authorizeRequest(), QNetworkManagerEngine::bytesReceived(), QConnmanEngine::bytesReceived(), QNetworkManagerEngine::bytesWritten(), QConnmanEngine::bytesWritten(), QUnixPrintWidgetPrivate::checkFields(), QPatternist::ColorOutputPrivate::ColorOutputPrivate(), compileSource(), QGLShader::compileSourceFile(), QMacPasteboardMimeVCard::convertFromMime(), copy(), QTemporaryFile::createLocalFile(), createPixmapDataSync(), QUuid::createUuid(), QNetworkDiskCache::data(), QTranslatorPrivate::do_load(), QGraphicsAnchorLayoutPrivate::dumpGraph(), DumpIDL(), dumpOutput(), QPdfEnginePrivate::embedFont(), QtopiaPrintEngine::end(), QZipReader::extractAll(), QBenchmarkValgrindUtils::extractResult(), QNetworkDiskCache::fileMetaData(), fontFile(), fontPath(), QDirectFBPixmapData::fromFile(), QGLPixmapData::fromFile(), QSslCertificate::fromPath(), QFreetypeFace::getFace(), QGtkStylePrivate::getThemeName(), QImageReader::imageFormat(), QScriptEngine::importExtension(), QDeclarativeInclude::include(), QCss::Parser::init(), QImageReaderPrivate::initHandler(), initializeDb(), QConfFile::isWritable(), launchWebBrowser(), QPicture::load(), QSvgTinyDocument::load(), QDeclarativeBorderImage::load(), QDeclarativeDataLoader::load(), QAxScriptManager::load(), QFontDatabasePrivate::loadFromCache(), QRawFont::loadFromFile(), QWSKbPrivate::loadKeymap(), QTextBrowser::loadResource(), QTextDocument::loadResource(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), QHostInfo::localDomainName(), FAREnforcer::logAuthAttempt(), QNetworkAccessFileBackend::open(), QTemporaryFile::open(), open(), QFileOpenEvent::openFile(), QPdfBaseEnginePrivate::openPrintDevice(), operator<<(), QDeclarativeDirParser::parse(), QPatternist::XsdSchemaParser::parseImport(), QPictureIO::pictureFormat(), QDeclarativePixmapReader::processJob(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), qt_getDefaultFromHomePrinters(), qt_getLprPrinters(), qt_parse_pattern(), qt_parseEtcLpPrinters(), qt_parseNsswitchConf(), qt_parsePrintcap(), qt_parsePrintersConf(), qt_parseQconfig(), QTextStream::QTextStream(), QZipReader::QZipReader(), QZipWriter::QZipWriter(), QPictureIO::read(), QWSCalibratedMouseHandler::readCalibration(), readConf(), readSourceFile(), registerFont(), QDynamicFileResourceRoot::registerSelf(), rename(), runningUnderDebugger(), QPicture::save(), QWaylandSelection::send(), QSslSocket::setLocalCertificate(), QSslSocket::setPrivateKey(), QTransportAuth::setProcessKey(), QSslSocketBackendPrivate::startHandshake(), QConfFileSettingsPrivate::syncConfFile(), QDeclarativeInclude::worker_include(), QSvgIconEngine::write(), QPictureIO::write(), QWSCalibratedMouseHandler::writeCalibration(), writeIncludeFile(), QCoreApplicationData::~QCoreApplicationData(), and QTraceWindowSurface::~QTraceWindowSurface().
 {
     Q_D(QFile);
     if (isOpen()) {
         qWarning("QFile::open: File (%s) already open", qPrintable(fileName()));
         return false;
     }
     if (mode & Append)
         mode |= WriteOnly;
     unsetError();
     if ((mode & (ReadOnly | WriteOnly)) == 0) {
         qWarning("QIODevice::open: File access not specified");
         return false;
     }
 #ifdef Q_OS_SYMBIAN
     // For symbian, the unbuffered flag is used to control write-behind cache behaviour
     if (fileEngine()->open(mode))
 #else
     // QIODevice provides the buffering, so there's no need to request it from the file engine.
     if (fileEngine()->open(mode | QIODevice::Unbuffered))
 #endif
     {
         QIODevice::open(mode);
         if (mode & Append) {
             //The file engine should have done this in open(),
             //this is a workaround for backward compatibility
             fileEngine()->seek(size());
         }
         return true;
     }
     QFile::FileError err = d->fileEngine->error();
     if(err == QFile::UnspecifiedError)
         err = QFile::OpenError;
     d->setError(err, d->fileEngine->errorString());
     return false;
 }
open() [2/5]
bool QFile::open (FILE * fh, OpenMode mode)
Opens the existing file handle fh in the given mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
Example:
#include <stdio.h>
void printError(const char* msg)
{
    QFile file;
    file.open(stderr, QIODevice::WriteOnly);
    file.write(msg, qstrlen(msg));        // write to stderr
    file.close();
}
When a QFile is opened using this function, close() does not actually close the file, but only flushes it.
Warning:
If fh does not refer to a regular file, e.g., it is stdin, stdout, or stderr, you may not be able to seek(). size() returns 0 in those cases. See QIODevice::isSequential() for more information.
Since this function opens the file without specifying the file name, you cannot use this QFile with a QFileInfo.
Note
For Windows CE you may not be able to call resize().
See also
close(), {qmake Variable Reference::CONFIG}{qmake Variable Reference}
Note for the Windows Platform
fh must be opened in binary mode (i.e., the mode string must contain 'b', as in "rb" or "wb") when accessing files and other random-access devices. Qt will translate the end-of-line characters if you pass QIODevice::Text to mode. Sequential devices, such as stdin and stdout, are unaffected by this limitation.
You need to enable support for console applications in order to use the stdin, stdout and stderr streams at the console. To do this, add the following declaration to your application's project file:
CONFIG += console
Definition at line 1152 of file qfile.cpp.
 {
     return open(fh, mode, DontCloseHandle);
 }
open() [3/5]
bool QFile::open (int fd, OpenMode mode)
Opens the existing file descriptor fd in the given mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
When a QFile is opened using this function, close() does not actually close the file.
The QFile that is opened using this function is automatically set to be in raw mode; this means that the file input/output functions are slow. If you run into performance issues, you should try to use one of the other open functions.
Warning
If fd is not a regular file, e.g, it is 0 (stdin), 1 (stdout), or 2 (stderr), you may not be able to seek(). In those cases, size() returns 0. See QIODevice::isSequential() for more information.
For Windows CE you may not be able to call seek(), setSize(), fileTime(). size() returns 0.
Since this function opens the file without specifying the file name, you cannot use this QFile with a QFileInfo.
See also
close()
Definition at line 1270 of file qfile.cpp.
 {
     return open(fd, mode, DontCloseHandle);
 }
open() [4/5]
bool QFile::open (FILE * fh, OpenMode mode, FileHandleFlags handleFlags)
Opens the existing file handle fh in the given mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
Example:
#include <stdio.h>
void printError(const char* msg)
{
    QFile file;
    file.open(stderr, QIODevice::WriteOnly);
    file.write(msg, qstrlen(msg));        // write to stderr
    file.close();
}
When a QFile is opened using this function, behaviour of close() is controlled by the AutoCloseHandle flag. If AutoCloseHandle is specified, and this function succeeds, then calling close() closes the adopted handle. Otherwise, close() does not actually close the file, but only flushes it.
Warning:
If fh does not refer to a regular file, e.g., it is stdin, stdout, or stderr, you may not be able to seek(). size() returns 0 in those cases. See QIODevice::isSequential() for more information.
Since this function opens the file without specifying the file name, you cannot use this QFile with a QFileInfo.
Note
For Windows CE you may not be able to call resize().
See also
close(), {qmake Variable Reference::CONFIG}{qmake Variable Reference}
Note for the Windows Platform
fh must be opened in binary mode (i.e., the mode string must contain 'b', as in "rb" or "wb") when accessing files and other random-access devices. Qt will translate the end-of-line characters if you pass QIODevice::Text to mode. Sequential devices, such as stdin and stdout, are unaffected by this limitation.
You need to enable support for console applications in order to use the stdin, stdout and stderr streams at the console. To do this, add the following declaration to your application's project file:
CONFIG += console
Definition at line 1203 of file qfile.cpp.
 {
     Q_D(QFile);
     if (isOpen()) {
         qWarning("QFile::open: File (%s) already open", qPrintable(fileName()));
         return false;
     }
     if (mode & Append)
         mode |= WriteOnly;
     unsetError();
     if ((mode & (ReadOnly | WriteOnly)) == 0) {
         qWarning("QFile::open: File access not specified");
         return false;
     }
     if (d->openExternalFile(mode, fh, handleFlags)) {
         QIODevice::open(mode);
         if (mode & Append) {
             seek(size());
         } else {
             qint64 pos = (qint64)QT_FTELL(fh);
             if (pos != -1)
                 seek(pos);
         }
         return true;
     }
     return false;
 }
open() [5/5]
bool QFile::open (int fd, OpenMode mode, FileHandleFlags handleFlags)
Opens the existing file descriptor fd in the given mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
When a QFile is opened using this function, behaviour of close() is controlled by the handleFlags argument. If AutoCloseHandle is specified, and this function succeeds, then calling close() closes the adopted handle. Otherwise, close() does not actually close the file, but only flushes it.
The QFile that is opened using this function is automatically set to be in raw mode; this means that the file input/output functions are slow. If you run into performance issues, you should try to use one of the other open functions.
Warning
If fd is not a regular file, e.g, it is 0 (stdin), 1 (stdout), or 2 (stderr), you may not be able to seek(). In those cases, size() returns 0. See QIODevice::isSequential() for more information.
For Windows CE you may not be able to call seek(), setSize(), fileTime(). size() returns 0.
Since this function opens the file without specifying the file name, you cannot use this QFile with a QFileInfo.
See also
close()
Definition at line 1308 of file qfile.cpp.
 {
     Q_D(QFile);
     if (isOpen()) {
         qWarning("QFile::open: File (%s) already open", qPrintable(fileName()));
         return false;
     }
     if (mode & Append)
         mode |= WriteOnly;
     unsetError();
     if ((mode & (ReadOnly | WriteOnly)) == 0) {
         qWarning("QFile::open: File access not specified");
         return false;
     }
     if (d->openExternalFile(mode, fd, handleFlags)) {
         QIODevice::open(mode);
         if (mode & Append) {
             seek(size());
         } else {
             qint64 pos = (qint64)QT_LSEEK(fd, QT_OFF_T(0), SEEK_CUR);
             if (pos != -1)
                 seek(pos);
         }
         return true;
     }
     return false;
 }
permissions() [1/2]
QFile::Permissions QFile::permissions () const
Returns the complete OR-ed together combination of QFile::Permission for the file.
See also
setPermissions(), setFileName()
Definition at line 1574 of file qfile.cpp.
Referenced by copy(), rename(), and QConfFileSettingsPrivate::syncConfFile().
 {
     QAbstractFileEngine::FileFlags perms = fileEngine()->fileFlags(QAbstractFileEngine::PermsMask) & QAbstractFileEngine::PermsMask;
     return QFile::Permissions((int)perms); //ewww
 }
permissions() [2/2]
QFile::Permissions QFile::permissions (const QString & fileName) static
Returns the complete OR-ed together combination of QFile::Permission for fileName.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1591 of file qfile.cpp.
 {
     return QFile(fileName).permissions();
 }
pos()
qint64 QFile::pos () const virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 1720 of file qfile.cpp.
Referenced by atEnd(), QTemporaryFile::createLocalFile(), QNetworkDiskCache::data(), open(), and QFilePrivate::putCharHelper().
 {
     return QIODevice::pos();
 }
readData()
qint64 QFile::readData (char * data, qint64 maxlen) protected virtual
Reimplemented Function
Implements QIODevice.
Definition at line 1839 of file qfile.cpp.
 {
     Q_D(QFile);
     unsetError();
     if (!d->ensureFlushed())
         return -1;
     qint64 read = d->fileEngine->read(data, len);
     if(read < 0) {
         QFile::FileError err = d->fileEngine->error();
         if(err == QFile::UnspecifiedError)
             err = QFile::ReadError;
         d->setError(err, d->fileEngine->errorString());
     }
     if (read < len) {
         // failed to read all requested, may be at the end of file, stop caching size so that it's rechecked
         d->cachedSize = 0;
     }
     return read;
 }
readLineData()
qint64 QFile::readLineData (char * data, qint64 maxlen) protected virtual
Reimplemented Function
Reimplemented from QIODevice.
Definition at line 1812 of file qfile.cpp.
 {
     Q_D(QFile);
     if (!d->ensureFlushed())
         return -1;
     qint64 read;
     if (d->fileEngine->supportsExtension(QAbstractFileEngine::FastReadLineExtension)) {
         read = d->fileEngine->readLine(data, maxlen);
     } else {
         // Fall back to QIODevice's readLine implementation if the engine
         // cannot do it faster.
         read = QIODevice::readLineData(data, maxlen);
     }
     if (read < maxlen) {
         // failed to read all requested, may be at the end of file, stop caching size so that it's rechecked
         d->cachedSize = 0;
     }
     return read;
 }
readLink() [1/2]
QString QFile::readLink () const
Use symLinkTarget() instead.
Definition at line 671 of file qfile.cpp.
 {
     return fileEngine()->fileName(QAbstractFileEngine::LinkName);
 }
readLink() [2/2]
QString QFile::readLink (const QString & fileName) static
Use symLinkTarget() instead.
Definition at line 700 of file qfile.cpp.
 {
     return QFileInfo(fileName).readLink();
 }
remove() [1/2]
bool QFile::remove ()
Removes the file specified by fileName().
Returns true if successful; otherwise returns false.
The file is closed before it is removed.
See also
setFileName()
Definition at line 715 of file qfile.cpp.
Referenced by QUnixPrintWidgetPrivate::checkFields(), QSystemSemaphorePrivate::cleanHandle(), QBenchmarkValgrindUtils::cleanup(), QFontEngineQPF::cleanUpAfterClientCrash(), QWSServerPrivate::cleanupFonts(), QPdfBaseEnginePrivate::closePrintDevice(), QSharedMemoryPrivate::create(), QSharedMemoryPrivate::detach(), QDirModel::dropMimeData(), DumpIDL(), QNetworkDiskCache::expire(), initializeDb(), QTransportAuth::isDiscoveryMode(), registerFont(), QFileSystemModel::remove(), QDir::remove(), QNetworkDiskCachePrivate::removeFile(), rename(), and QNetworkDiskCachePrivate::storeItem().
 {
     Q_D(QFile);
     if (d->fileName.isEmpty()) {
         qWarning("QFile::remove: Empty or null file name");
         return false;
     }
     unsetError();
     close();
     if(error() == QFile::NoError) {
         if(fileEngine()->remove()) {
             unsetError();
             return true;
         }
         d->setError(QFile::RemoveError, d->fileEngine->errorString());
     }
     return false;
 }
remove() [2/2]
bool QFile::remove (const QString & fileName) static
Removes the file specified by the fileName given.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
See also
remove()
Definition at line 748 of file qfile.cpp.
 {
     return QFile(fileName).remove();
 }
rename() [1/2]
bool QFile::rename (const QString & newName)
Renames the file currently specified by fileName() to newName.
Returns true if successful; otherwise returns false.
If a file with the name newName already exists, rename() returns false (i.e., QFile will not overwrite it).
The file is closed before it is renamed.
See also
setFileName()
Definition at line 766 of file qfile.cpp.
Referenced by QDragManager::drag(), QFileSystemModel::dropMimeData(), initializeDb(), QDir::rename(), and QNetworkDiskCachePrivate::storeItem().
 {
     Q_D(QFile);
     if (d->fileName.isEmpty()) {
         qWarning("QFile::rename: Empty or null file name");
         return false;
     }
     if (QFile(newName).exists()) {
         // ### Race condition. If a file is moved in after this, it /will/ be
         // overwritten. On Unix, the proper solution is to use hardlinks:
         // return ::link(old, new) && ::remove(old);
         d->setError(QFile::RenameError, tr("Destination file exists"));
         return false;
     }
     unsetError();
     close();
     if(error() == QFile::NoError) {
         if (fileEngine()->rename(newName)) {
             unsetError();
             // engine was able to handle the new name so we just reset it
             d->fileEngine->setFileName(newName);
             d->fileName = newName;
             return true;
         }
         if (isSequential()) {
             d->setError(QFile::RenameError, tr("Will not rename sequential file using block copy"));
             return false;
         }
         QFile out(newName);
         if (open(QIODevice::ReadOnly)) {
             if (out.open(QIODevice::WriteOnly | QIODevice::Truncate)) {
                 bool error = false;
                 char block[4096];
                 qint64 bytes;
                 while ((bytes = read(block, sizeof(block))) > 0) {
                     if (bytes != out.write(block, bytes)) {
                         d->setError(QFile::RenameError, out.errorString());
                         error = true;
                         break;
                     }
                 }
                 if (bytes == -1) {
                     d->setError(QFile::RenameError, errorString());
                     error = true;
                 }
                 if(!error) {
                     if (!remove()) {
                         d->setError(QFile::RenameError, tr("Cannot remove source file"));
                         error = true;
                     }
                 }
                 if (error) {
                     out.remove();
                 } else {
                     d->fileEngine->setFileName(newName);
                     setPermissions(permissions());
                     unsetError();
                     setFileName(newName);
                 }
                 close();
                 return !error;
             }
             close();
         }
         d->setError(QFile::RenameError, out.isOpen() ? errorString() : out.errorString());
     }
     return false;
 }
rename() [2/2]
bool QFile::rename (const QString & oldName, const QString & newName) static
Renames the file oldName to newName.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if successful; otherwise returns false.
If a file with the name newName already exists, rename() returns false (i.e., QFile will not overwrite it).
See also
rename()
Definition at line 853 of file qfile.cpp.
 {
     return QFile(oldName).rename(newName);
 }
resize() [1/2]
bool QFile::resize (qint64 sz)
Sets the file size (in bytes) sz.
Returns true if the file if the resize succeeds; false otherwise. If sz is larger than the file currently is the new bytes will be set to 0, if sz is smaller the file is simply truncated.
See also
size(), setFileName()
Definition at line 1528 of file qfile.cpp.
Referenced by QFSFileEnginePrivate::longFileName(), and QConfFileSettingsPrivate::syncConfFile().
 {
     Q_D(QFile);
     if (!d->ensureFlushed())
         return false;
     fileEngine();
     if (isOpen() && d->fileEngine->pos() > sz)
         seek(sz);
     if(d->fileEngine->setSize(sz)) {
         unsetError();
         d->cachedSize = sz;
         return true;
     }
     d->cachedSize = 0;
     d->setError(QFile::ResizeError, d->fileEngine->errorString());
     return false;
 }
resize() [2/2]
bool QFile::resize (const QString & fileName, qint64 sz) static
Sets fileName to size (in bytes) sz.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if the file if the resize succeeds; false otherwise. If sz is larger than fileName currently is the new bytes will be set to 0, if sz is smaller the file is simply truncated.
See also
resize()
Definition at line 1561 of file qfile.cpp.
 {
     return QFile(fileName).resize(sz);
 }
seek()
bool QFile::seek (qint64 pos) virtual
For random-access devices, this function sets the current position to pos, returning true on success, or false if an error occurred.
For sequential devices, the default behavior is to do nothing and return false.
Seeking beyond the end of a file: If the position is beyond the end of a file, then seek() shall not immediately extend the file. If a write is performed at this position, then the file shall be extended. The content of the file between the previous end of file and the newly written data is UNDEFINED and varies between platforms and file systems.
Reimplemented from QIODevice.
Definition at line 1784 of file qfile.cpp.
Referenced by QTemporaryFile::createLocalFile(), QTransportAuthPrivate::getClientKey(), open(), QFilePrivate::putCharHelper(), QPictureIO::read(), resize(), and QConfFileSettingsPrivate::syncConfFile().
 {
     Q_D(QFile);
     if (!isOpen()) {
         qWarning("QFile::seek: IODevice is not open");
         return false;
     }
     if (off == d->pos && off == d->devicePos)
         return true; //avoid expensive flush for NOP seek to current position
     if (!d->ensureFlushed())
         return false;
     if (!d->fileEngine->seek(off) || !QIODevice::seek(off)) {
         QFile::FileError err = d->fileEngine->error();
         if(err == QFile::UnspecifiedError)
             err = QFile::PositionError;
         d->setError(err, d->fileEngine->errorString());
         return false;
     }
     unsetError();
     return true;
 }
setDecodingFunction()
void QFile::setDecodingFunction (DecoderFn function) static
Sets the function for decoding 8-bit file names.
Note
This class or function is not reentrant.
The default uses the locale-specific 8-bit encoding.
See also
setEncodingFunction(), decodeName()
Definition at line 606 of file qfile.cpp.
 {
     if (!f)
         f = locale_decode;
     QFilePrivate::decoder = f;
 }
setEncodingFunction()
void QFile::setEncodingFunction (EncoderFn function) static
Sets the function for encoding Unicode file names.
Note
This class or function is not reentrant.
The default encodes in the locale-specific 8-bit encoding.
See also
encodeName(), setDecodingFunction()
Definition at line 572 of file qfile.cpp.
 {
     if (!f)
         f = locale_encode;
     QFilePrivate::encoder = f;
 }
setFileName()
void QFile::setFileName (const QString & name)
Sets the name of the file.
The name can have no path, a relative path, or an absolute path.
Do not call this function if the file has already been opened.
If the file name has no path or a relative path, the path used will be the application's current directory path at the time of the open() call.
Example:
QFile file;
QDir::setCurrent("/tmp");
file.setFileName("readme.txt");
QDir::setCurrent("/home");
file.open(QIODevice::ReadOnly);      // opens "/home/readme.txt" under Unix
Note that the directory separator "/" works for all operating systems supported by Qt.
See also
fileName(), QFileInfo, QDir
Definition at line 494 of file qfile.cpp.
Referenced by QMacPasteboardMimeVCard::convertFromMime(), fontPath(), QImageReaderPrivate::initHandler(), QHostInfo::localDomainName(), QNetworkAccessFileBackend::open(), QFileOpenEvent::openFile(), QIconTheme::QIconTheme(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QPictureIO::read(), rename(), and QPictureIO::write().
 {
     Q_D(QFile);
     if (isOpen()) {
         qWarning("QFile::setFileName: File (%s) is already opened",
                  qPrintable(fileName()));
         close();
     }
     if(d->fileEngine) { //get a new file engine later
         delete d->fileEngine;
         d->fileEngine = 0;
     }
     d->fileName = name;
 }
setPermissions() [1/2]
bool QFile::setPermissions (Permissions permissions)
Sets the permissions for the file to the permissions specified.
Returns true if successful, or false if the permissions cannot be modified.
See also
permissions(), setFileName()
Definition at line 1605 of file qfile.cpp.
Referenced by copy(), QZipReader::extractAll(), rename(), and QConfFileSettingsPrivate::syncConfFile().
 {
     Q_D(QFile);
     if(fileEngine()->setPermissions(permissions)) {
         unsetError();
         return true;
     }
     d->setError(QFile::PermissionsError, d->fileEngine->errorString());
     return false;
 }
setPermissions() [2/2]
bool QFile::setPermissions (const QString & fileName, Permissions permissions) static
Sets the permissions for fileName file to permissions.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1626 of file qfile.cpp.
 {
     return QFile(fileName).setPermissions(permissions);
 }
size()
qint64 QFile::size () const virtual
Returns the size of the file.
For regular empty files on Unix (e.g. those in /proc), this function returns 0; the contents of such a file are generated on demand in response to you calling read().
Reimplemented from QIODevice.
Definition at line 1707 of file qfile.cpp.
Referenced by copy(), QNetworkDiskCache::data(), QTranslatorPrivate::do_load(), QNetworkDiskCache::expire(), flush(), open(), qt_parse_pattern(), QDynamicFileResourceRoot::registerSelf(), QCacheItem::size(), and QNetworkDiskCachePrivate::storeItem().
 {
     Q_D(const QFile);
     if (!d->ensureFlushed())
         return 0;
     d->cachedSize = fileEngine()->size();
     return d->cachedSize;
 }
symLinkTarget() [1/2]
QString QFile::symLinkTarget () const inline
Returns the absolute path of the file or directory a symlink (or shortcut on Windows) points to, or a an empty string if the object isn't a symbolic link.
Since
4.2 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This name may not represent an existing file; it is only a string. QFile::exists() returns true if the symlink points to an existing file.
See also
fileName() setFileName()
Definition at line 137 of file qfile.h.
 { return readLink(); }
symLinkTarget() [2/2]
static QString QFile::symLinkTarget (const QString & fileName) inline static
Returns the absolute path of the file or directory referred to by the symlink (or shortcut on Windows) specified by fileName, or returns an empty string if the fileName does not correspond to a symbolic link.
Since
4.2
This name may not represent an existing file; it is only a string. QFile::exists() returns true if the symlink points to an existing file.
Definition at line 138 of file qfile.h.
 { return readLink(fileName); }
unmap()
bool QFile::unmap (uchar * address)
Unmaps the memory address.
Since
4.4
Returns true if the unmap succeeds; false otherwise.
See also
map(), QAbstractFileEngine::supportsExtension()
Definition at line 1485 of file qfile.cpp.
 {
     Q_D(QFile);
     if (fileEngine()
         && d->fileEngine->supportsExtension(QAbstractFileEngine::UnMapExtension)) {
         unsetError();
         bool success = d->fileEngine->unmap(address);
         if (!success)
             d->setError(d->fileEngine->error(), d->fileEngine->errorString());
         return success;
     }
     d->setError(PermissionsError, tr("No file engine available or engine does not support UnMapExtension"));
     return false;
 }
unsetError()
void QFile::unsetError ()
Sets the file's error to QFile::NoError.
See also
error()
Definition at line 1996 of file qfile.cpp.
Referenced by close(), copy(), QIODevice::errorString(), link(), map(), open(), readData(), remove(), rename(), resize(), seek(), setPermissions(), unmap(), and writeData().
 {
     Q_D(QFile);
     d->setError(QFile::NoError);
 }
writeData()
qint64 QFile::writeData (const char * data, qint64 len) protected virtual
Reimplemented Function
Implements QIODevice.
Definition at line 1923 of file qfile.cpp.
 {
     Q_D(QFile);
     unsetError();
     d->lastWasWrite = true;
     bool buffered = !(d->openMode & Unbuffered);
     // Flush buffered data if this read will overflow.
     if (buffered && (d->writeBuffer.size() + len) > QFILE_WRITEBUFFER_SIZE) {
         if (!flush())
             return -1;
     }
     // Write directly to the engine if the block size is larger than
     // the write buffer size.
     if (!buffered || len > QFILE_WRITEBUFFER_SIZE) {
         qint64 ret = d->fileEngine->write(data, len);
         if(ret < 0) {
             QFile::FileError err = d->fileEngine->error();
             if(err == QFile::UnspecifiedError)
                 err = QFile::WriteError;
             d->setError(err, d->fileEngine->errorString());
         }
         return ret;
     }
     // Write to the buffer.
     char *writePointer = d->writeBuffer.reserve(len);
     if (len == 1)
         *writePointer = *data;
     else
         ::memcpy(writePointer, data, len);
     return len;
 }
The documentation for this class was generated from the following files:
/src/corelib/io/qfile.h
/src/corelib/io/qfile.cpp