Qt 4.8: QSqlCachedResult Class Reference
QSqlCachedResult Class Reference abstract
#include <qsqlcachedresult_p.h>
Public Types
typedef QVector< QVariant > ValueCache
Public Functions
virtual ~QSqlCachedResult ()
Public Functions inherited from QSqlResult
virtual QVariant handle () const
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
virtual ~QSqlResult ()
Destroys the object and frees any allocated resources.
Protected Functions
ValueCache & cache ()
void cleanup ()
void clearValues ()
int colCount () const
QVariant data (int i)
Returns the data for field index in the current row as a QVariant.
bool fetch (int i)
Positions the result to an arbitrary (zero-based) row index.
bool fetchFirst ()
Positions the result to the first record (row 0) in the result.
bool fetchLast ()
Positions the result to the last record (last row) in the result.
bool fetchNext ()
Positions the result to the next available record (row) in the result.
bool fetchPrevious ()
Positions the result to the previous record (row) in the result.
virtual bool gotoNext (ValueCache &values, int index)=0
void init (int colCount)
bool isNull (int i)
Returns true if the field at position index in the current row is null; otherwise returns false.
QSqlCachedResult (const QSqlDriver *db)
void virtual_hook (int id, void *data)
Protected Functions inherited from QSqlResult
void addBindValue (const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the next available position in the current record (row).
int at () const
Returns the current (zero-based) row position of the result.
BindingSyntax bindingSyntax () const
Returns the binding syntax used by prepared queries.
virtual void bindValue (int pos, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to position index in the current record (row).
virtual void bindValue (const QString &placeholder, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the placeholder name in the current record (row).
QSql::ParamType bindValueType (const QString &placeholder) const
Returns the parameter type for the value bound with the given placeholder name.
QSql::ParamType bindValueType (int pos) const
Returns the parameter type for the value bound at position index.
QVariant boundValue (const QString &placeholder) const
Returns the value bound by the given placeholder name in the current record (row).
QVariant boundValue (int pos) const
Returns the value bound at position index in the current record (row).
int boundValueCount () const
Returns the number of bound values in the result.
QString boundValueName (int pos) const
Returns the name of the bound value at position index in the current record (row).
QVector< QVariant > & boundValues () const
Returns a vector of the result's bound values for the current record (row).
void clear ()
Clears the entire result set and releases any associated resources.
void detachFromResultSet ()
const QSqlDriver * driver () const
Returns the driver associated with the result.
virtual bool exec ()
Executes the query, returning true if successful; otherwise returns false.
bool execBatch (bool arrayBind=false)
Executes a prepared query in batch mode if the driver supports it, otherwise emulates a batch execution using bindValue() and exec().
QString executedQuery () const
Returns the query that was actually executed.
bool hasOutValues () const
Returns true if at least one of the query's bound values is a QSql::Out or a QSql::InOut; otherwise returns false.
bool isActive () const
Returns true if the result has records to be retrieved; otherwise returns false.
bool isForwardOnly () const
Returns true if you can only scroll forward through the result set; otherwise returns false.
bool isSelect () const
Returns true if the current result is from a SELECT statement; otherwise returns false.
bool isValid () const
Returns true if the result is positioned on a valid record (that is, the result is not positioned before the first or after the last record); otherwise returns false.
QSqlError lastError () const
Returns the last error associated with the result.
virtual QVariant lastInsertId () const
Returns the object ID of the most recent inserted row if the database supports it.
QString lastQuery () const
Returns the current SQL query text, or an empty string if there isn't one.
bool nextResult ()
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
virtual int numRowsAffected ()=0
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
virtual bool prepare (const QString &query)
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
QSqlResult (const QSqlDriver *db)
Creates a QSqlResult using database driver db.
virtual QSqlRecord record () const
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
virtual bool reset (const QString &sqlquery)=0
Sets the result to use the SQL statement query for subsequent data retrieval.
virtual bool savePrepare (const QString &sqlquery)
Prepares the given query, using the underlying database functionality where possible.
virtual void setActive (bool a)
This function is provided for derived classes to set the internal active state to active.
virtual void setAt (int at)
This function is provided for derived classes to set the internal (zero-based) row position to index.
virtual void setForwardOnly (bool forward)
Sets forward only mode to forward.
virtual void setLastError (const QSqlError &e)
This function is provided for derived classes to set the last error to error.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy policy)
virtual void setQuery (const QString &query)
Sets the current query for the result to query.
virtual void setSelect (bool s)
This function is provided for derived classes to indicate whether or not the current statement is a SQL SELECT statement.
virtual int size ()=0
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
Private Functions
bool cacheNext ()
Properties
QSqlCachedResultPrivate * d
Additional Inherited Members
Protected Types inherited from QSqlResult
enum BindingSyntax { PositionalBinding, NamedBinding }
This enum type specifies the different syntaxes for specifying placeholders in prepared queries.
enum VirtualHookOperation { BatchOperation, DetachFromResultSet, SetNumericalPrecision, NextResult }
Detailed Description
Definition at line 65 of file qsqlcachedresult_p.h.
Typedefs
ValueCache
typedef QVector<QVariant> QSqlCachedResult::ValueCache
Definition at line 70 of file qsqlcachedresult_p.h.
Constructors and Destructors
~QSqlCachedResult()
QSqlCachedResult::~QSqlCachedResult () virtual
Definition at line 150 of file qsqlcachedresult.cpp.
 {
     delete d;
 }
QSqlCachedResult()
QSqlCachedResult::QSqlCachedResult (const QSqlDriver * db) protected
Definition at line 145 of file qsqlcachedresult.cpp.
                                                        : QSqlResult (db)
 {
     d = new QSqlCachedResultPrivate();
 }
Functions
cache()
QSqlCachedResult::ValueCache & QSqlCachedResult::cache () protected
Definition at line 300 of file qsqlcachedresult.cpp.
 {
     return d->cache;
 }
cacheNext()
bool QSqlCachedResult::cacheNext () private
Definition at line 276 of file qsqlcachedresult.cpp.
Referenced by fetch(), fetchFirst(), and fetchNext().
 {
     if (d->atEnd)
         return false;
     if(isForwardOnly()) {
         d->cache.clear();
         d->cache.resize(d->colCount);
     }
     if (!gotoNext(d->cache, d->nextIndex())) {
         d->revertLast();
         d->atEnd = true;
         return false;
     }
     setAt(at() + 1);
     return true;
 }
cleanup()
void QSqlCachedResult::cleanup () protected
Definition at line 262 of file qsqlcachedresult.cpp.
Referenced by QTDSResult::cleanup(), QSQLite2ResultPrivate::cleanup(), QSQLiteResultPrivate::cleanup(), QIBaseResultPrivate::cleanup(), QIBaseResult::exec(), QOCIResult::prepare(), and virtual_hook().
 {
     setAt(QSql::BeforeFirstRow);
     setActive(false);
     d->cleanup();
 }
clearValues()
void QSqlCachedResult::clearValues () protected
Definition at line 269 of file qsqlcachedresult.cpp.
Referenced by QSQLiteResult::exec().
 {
     setAt(QSql::BeforeFirstRow);
     d->rowCacheEnd = 0;
     d->atEnd = false;
 }
colCount()
int QSqlCachedResult::colCount () const protected
Definition at line 295 of file qsqlcachedresult.cpp.
Referenced by QIBaseResult::exec().
 {
     return d->colCount;
 }
data()
QVariant QSqlCachedResult::data (int index) protected virtual
Returns the data for field index in the current row as a QVariant.
This function is only called if the result is in an active state and is positioned on a valid record and index is non-negative. Derived classes must reimplement this function and return the value of field index, or QVariant() if it cannot be determined.
Implements QSqlResult.
Definition at line 244 of file qsqlcachedresult.cpp.
 {
     int idx = d->forwardOnly ? i : at() * d->colCount + i;
     if (i >= d->colCount || i < 0 || at() < 0 || idx >= d->rowCacheEnd)
         return QVariant();
     return d->cache.at(idx);
 }
fetch()
bool QSqlCachedResult::fetch (int index) protected virtual
Positions the result to an arbitrary (zero-based) row index.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the row index, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
isActive(), fetchFirst(), fetchLast(), fetchNext(), fetchPrevious()
Implements QSqlResult.
Definition at line 160 of file qsqlcachedresult.cpp.
Referenced by fetchLast(), and fetchPrevious().
 {
     if ((!isActive()) || (i < 0))
         return false;
     if (at() == i)
         return true;
     if (d->forwardOnly) {
         // speed hack - do not copy values if not needed
         if (at() > i || at() == QSql::AfterLastRow)
             return false;
         while(at() < i - 1) {
             if (!gotoNext(d->cache, -1))
                 return false;
             setAt(at() + 1);
         }
         if (!gotoNext(d->cache, 0))
             return false;
         setAt(at() + 1);
         return true;
     }
     if (d->canSeek(i)) {
         setAt(i);
         return true;
     }
     if (d->rowCacheEnd > 0)
         setAt(d->cacheCount());
     while (at() < i + 1) {
         if (!cacheNext()) {
             if (d->canSeek(i))
                 break;
             return false;
         }
     }
     setAt(i);
     return true;
 }
fetchFirst()
bool QSqlCachedResult::fetchFirst () protected virtual
Positions the result to the first record (row 0) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the first record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchLast()
Implements QSqlResult.
Definition at line 212 of file qsqlcachedresult.cpp.
 {
     if (d->forwardOnly && at() != QSql::BeforeFirstRow) {
         return false;
     }
     if (d->canSeek(0)) {
         setAt(0);
         return true;
     }
     return cacheNext();
 }
fetchLast()
bool QSqlCachedResult::fetchLast () protected virtual
Positions the result to the last record (last row) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the last record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchFirst()
Implements QSqlResult.
Definition at line 224 of file qsqlcachedresult.cpp.
 {
     if (d->atEnd) {
         if (d->forwardOnly)
             return false;
         else
             return fetch(d->cacheCount() - 1);
     }
     int i = at();
     while (fetchNext())
         ++i; /* brute force */
     if (d->forwardOnly && at() == QSql::AfterLastRow) {
         setAt(i);
         return true;
     } else {
         return fetch(i);
     }
 }
fetchNext()
bool QSqlCachedResult::fetchNext () protected virtual
Positions the result to the next available record (row) in the result.
This function is only called if the result is in an active state. The default implementation calls fetch() with the next index. Derived classes can reimplement this function and position the result to the next record in some other way, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchPrevious()
Reimplemented from QSqlResult.
Definition at line 198 of file qsqlcachedresult.cpp.
Referenced by fetchLast().
 {
     if (d->canSeek(at() + 1)) {
         setAt(at() + 1);
         return true;
     }
     return cacheNext();
 }
fetchPrevious()
bool QSqlCachedResult::fetchPrevious () protected virtual
Positions the result to the previous record (row) in the result.
This function is only called if the result is in an active state. The default implementation calls fetch() with the previous index. Derived classes can reimplement this function and position the result to the next record in some other way, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
Reimplemented from QSqlResult.
Definition at line 207 of file qsqlcachedresult.cpp.
 {
     return fetch(at() - 1);
 }
gotoNext()
virtual bool QSqlCachedResult::gotoNext (ValueCache & values, int index) protected pure virtual
Implemented in QTDSResult, QOCIResult, QSQLite2Result, QSQLiteResult, and QIBaseResult.
Referenced by cacheNext(), and fetch().
init()
void QSqlCachedResult::init (int colCount) protected
Definition at line 155 of file qsqlcachedresult.cpp.
Referenced by QIBaseResult::exec(), QOCIResult::exec(), QSQLite2ResultPrivate::init(), QSQLiteResultPrivate::initColumns(), and QTDSResult::reset().
 {
     d->init(colCount, isForwardOnly());
 }
isNull()
bool QSqlCachedResult::isNull (int i) protected virtual
Returns true if the field at position index in the current row is null; otherwise returns false.
Implements QSqlResult.
Definition at line 253 of file qsqlcachedresult.cpp.
 {
     int idx = d->forwardOnly ? i : at() * d->colCount + i;
     if (i >= d->colCount || i < 0 || at() < 0 || idx >= d->rowCacheEnd)
         return true;
     return d->cache.at(idx).isNull();
 }
virtual_hook()
void QSqlCachedResult::virtual_hook (int id, void * data) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QSqlResult.
Definition at line 305 of file qsqlcachedresult.cpp.
Referenced by QSQLite2Result::virtual_hook(), QSQLiteResult::virtual_hook(), and QOCIResult::virtual_hook().
 {
     switch (id) {
     case QSqlResult::DetachFromResultSet:
     case QSqlResult::SetNumericalPrecision:
         cleanup();
         break;
     default:
         QSqlResult::virtual_hook(id, data);
     }
 }
Properties
d
QSqlCachedResultPrivate* QSqlCachedResult::d private
Definition at line 95 of file qsqlcachedresult_p.h.
Referenced by cache(), cacheNext(), cleanup(), clearValues(), colCount(), data(), fetch(), fetchFirst(), fetchLast(), fetchNext(), init(), isNull(), QSqlCachedResult(), and ~QSqlCachedResult().
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqlcachedresult_p.h
/src/sql/kernel/qsqlcachedresult.cpp