Qt 4.8: QGraphicsSceneBspTree Class Reference
QGraphicsSceneBspTree Class Reference
#include <qgraphicsscene_bsp_p.h>
Classes
struct Node
Public Functions
void clear ()
QString debug (int index) const
int firstChildIndex (int index) const
void initialize (const QRectF &rect, int depth)
void insertItem (QGraphicsItem *item, const QRectF &rect)
QList< QGraphicsItem * > items (const QRectF &rect, bool onlyTopLevelItems=false) const
int leafCount () const
int parentIndex (int index) const
QGraphicsSceneBspTree ()
void removeItem (QGraphicsItem *item, const QRectF &rect)
void removeItems (const QSet< QGraphicsItem *> &items)
~QGraphicsSceneBspTree ()
Private Functions
void climbTree (QGraphicsSceneBspTreeVisitor *visitor, const QRectF &rect, int index=0) const
void initialize (const QRectF &rect, int depth, int index)
QRectF rectForIndex (int index) const
Properties
QGraphicsSceneFindItemBspTreeVisitor * findVisitor
QGraphicsSceneInsertItemBspTreeVisitor * insertVisitor
int leafCnt
QVector< QList< QGraphicsItem * > > leaves
QVector< Node > nodes
QRectF rect
QGraphicsSceneRemoveItemBspTreeVisitor * removeVisitor
Detailed Description
Definition at line 72 of file qgraphicsscene_bsp_p.h.
Constructors and Destructors
QGraphicsSceneBspTree()
QGraphicsSceneBspTree::QGraphicsSceneBspTree ()
Definition at line 89 of file qgraphicsscene_bsp.cpp.
     : leafCnt(0)
 {
     insertVisitor = new QGraphicsSceneInsertItemBspTreeVisitor;
     removeVisitor = new QGraphicsSceneRemoveItemBspTreeVisitor;
     findVisitor = new QGraphicsSceneFindItemBspTreeVisitor;
 }
~QGraphicsSceneBspTree()
QGraphicsSceneBspTree::~QGraphicsSceneBspTree ()
Definition at line 97 of file qgraphicsscene_bsp.cpp.
 {
     delete insertVisitor;
     delete removeVisitor;
     delete findVisitor;
 }
Functions
clear()
void QGraphicsSceneBspTree::clear ()
Definition at line 116 of file qgraphicsscene_bsp.cpp.
 {
     leafCnt = 0;
     nodes.clear();
     leaves.clear();
 }
climbTree()
void QGraphicsSceneBspTree::climbTree (QGraphicsSceneBspTreeVisitor * visitor, const QRectF & rect, int index = 0) const private
Definition at line 237 of file qgraphicsscene_bsp.cpp.
Referenced by insertItem(), items(), parentIndex(), and removeItem().
 {
     if (nodes.isEmpty())
         return;
     const Node &node = nodes.at(index);
     const int childIndex = firstChildIndex(index);
     switch (node.type) {
     case Node::Leaf: {
         visitor->visit(const_cast<QList<QGraphicsItem*>*>(&leaves[node.leafIndex]));
         break;
     }
     case Node::Vertical:
         if (rect.left() < node.offset) {
             climbTree(visitor, rect, childIndex);
             if (rect.right() >= node.offset)
                 climbTree(visitor, rect, childIndex + 1);
         } else {
             climbTree(visitor, rect, childIndex + 1);
         }
         break;
     case Node::Horizontal:
         if (rect.top() < node.offset) {
             climbTree(visitor, rect, childIndex);
             if (rect.bottom() >= node.offset)
                 climbTree(visitor, rect, childIndex + 1);
         } else {
             climbTree(visitor, rect, childIndex + 1);
         }
     }
 }
debug()
QString QGraphicsSceneBspTree::debug (int index) const
Definition at line 166 of file qgraphicsscene_bsp.cpp.
Referenced by parentIndex().
 {
     const Node *node = &nodes.at(index);
     QString tmp;
     if (node->type == Node::Leaf) {
         QRectF rect = rectForIndex(index);
         if (!leaves[node->leafIndex].isEmpty()) {
             tmp += QString::fromLatin1("[%1, %2, %3, %4] contains %5 items\n")
                    .arg(rect.left()).arg(rect.top())
                    .arg(rect.width()).arg(rect.height())
                    .arg(leaves[node->leafIndex].size());
         }
     } else {
         if (node->type == Node::Horizontal) {
             tmp += debug(firstChildIndex(index));
             tmp += debug(firstChildIndex(index) + 1);
         } else {
             tmp += debug(firstChildIndex(index));
             tmp += debug(firstChildIndex(index) + 1);
         }
     }
     return tmp;
 }
firstChildIndex()
int QGraphicsSceneBspTree::firstChildIndex (int index) const inline
Definition at line 98 of file qgraphicsscene_bsp_p.h.
Referenced by climbTree(), debug(), and initialize().
     { return index * 2 + 1; }
initialize() [1/2]
void QGraphicsSceneBspTree::initialize (const QRectF & rect, int depth)
Definition at line 104 of file qgraphicsscene_bsp.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex(), initialize(), and parentIndex().
 {
     this->rect = rect;
     leafCnt = 0;
     nodes.resize((1 << (depth + 1)) - 1);
     nodes.fill(Node());
     leaves.resize(1 << depth);
     leaves.fill(QList<QGraphicsItem *>());
     initialize(rect, depth, 0);
 }
initialize() [2/2]
void QGraphicsSceneBspTree::initialize (const QRectF & rect, int depth, int index) private
Definition at line 192 of file qgraphicsscene_bsp.cpp.
 {
     Node *node = &nodes[index];
     if (index == 0) {
         node->type = Node::Horizontal;
         node->offset = rect.center().x();
     }
     if (depth) {
         Node::Type type;
         QRectF rect1, rect2;
         qreal offset1, offset2;
         if (node->type == Node::Horizontal) {
             type = Node::Vertical;
             rect1.setRect(rect.left(), rect.top(), rect.width(), rect.height() / 2);
             rect2.setRect(rect1.left(), rect1.bottom(), rect1.width(), rect.height() - rect1.height());
             offset1 = rect1.center().x();
             offset2 = rect2.center().x();
         } else {
             type = Node::Horizontal;
             rect1.setRect(rect.left(), rect.top(), rect.width() / 2, rect.height());
             rect2.setRect(rect1.right(), rect1.top(), rect.width() - rect1.width(), rect1.height());
             offset1 = rect1.center().y();
             offset2 = rect2.center().y();
         }
         int childIndex = firstChildIndex(index);
         Node *child = &nodes[childIndex];
         child->offset = offset1;
         child->type = type;
         child = &nodes[childIndex + 1];
         child->offset = offset2;
         child->type = type;
         initialize(rect1, depth - 1, childIndex);
         initialize(rect2, depth - 1, childIndex + 1);
     } else {
         node->type = Node::Leaf;
         node->leafIndex = leafCnt++;
     }
 }
insertItem()
void QGraphicsSceneBspTree::insertItem (QGraphicsItem * item, const QRectF & rect)
Definition at line 123 of file qgraphicsscene_bsp.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex().
 {
     insertVisitor->item = item;
     climbTree(insertVisitor, rect);
 }
items()
QList< QGraphicsItem * > QGraphicsSceneBspTree::items (const QRectF & rect, bool onlyTopLevelItems = false) const
Definition at line 149 of file qgraphicsscene_bsp.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::estimateItems(), and QGraphicsSceneBspTreeVisitor::~QGraphicsSceneBspTreeVisitor().
 {
     QList<QGraphicsItem *> tmp;
     findVisitor->foundItems = &tmp;
     findVisitor->onlyTopLevelItems = onlyTopLevelItems;
     climbTree(findVisitor, rect);
     // Reset discovery bits.
     for (int i = 0; i < tmp.size(); ++i)
         tmp.at(i)->d_ptr->itemDiscovered = 0;
     return tmp;
 }
leafCount()
int QGraphicsSceneBspTree::leafCount () const
Definition at line 161 of file qgraphicsscene_bsp.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::_q_updateIndex().
 {
     return leafCnt;
 }
parentIndex()
int QGraphicsSceneBspTree::parentIndex (int index) const inline
Definition at line 101 of file qgraphicsscene_bsp_p.h.
Referenced by rectForIndex().
     { return index > 0 ? ((index & 1) ? ((index - 1) / 2) : ((index - 2) / 2)) : -1; }
rectForIndex()
QRectF QGraphicsSceneBspTree::rectForIndex (int index) const private
Definition at line 270 of file qgraphicsscene_bsp.cpp.
Referenced by debug(), and parentIndex().
 {
     if (index <= 0)
         return rect;
     int parentIdx = parentIndex(index);
     QRectF rect = rectForIndex(parentIdx);
     const Node *parent = &nodes.at(parentIdx);
     if (parent->type == Node::Horizontal) {
         if (index & 1)
             rect.setRight(parent->offset);
         else
             rect.setLeft(parent->offset);
     } else {
         if (index & 1)
             rect.setBottom(parent->offset);
         else
             rect.setTop(parent->offset);
     }
     return rect;
 }
removeItem()
void QGraphicsSceneBspTree::removeItem (QGraphicsItem * item, const QRectF & rect)
Definition at line 129 of file qgraphicsscene_bsp.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::removeItem().
 {
     removeVisitor->item = item;
     climbTree(removeVisitor, rect);
 }
removeItems()
void QGraphicsSceneBspTree::removeItems (const QSet< QGraphicsItem *> & items)
Definition at line 135 of file qgraphicsscene_bsp.cpp.
Referenced by QGraphicsSceneBspTreeIndexPrivate::purgeRemovedItems().
 {
     for (int i = 0; i < leaves.size(); ++i) {
         QList<QGraphicsItem *> newItemList;
         const QList<QGraphicsItem *> &oldItemList = leaves[i];
         for (int j = 0; j < oldItemList.size(); ++j) {
             QGraphicsItem *item = oldItemList.at(j);
             if (!items.contains(item))
                 newItemList << item;
         }
         leaves[i] = newItemList;
     }
 }
Properties
findVisitor
QGraphicsSceneFindItemBspTreeVisitor* QGraphicsSceneBspTree::findVisitor private
Definition at line 118 of file qgraphicsscene_bsp_p.h.
Referenced by items(), QGraphicsSceneBspTree(), and ~QGraphicsSceneBspTree().
insertVisitor
QGraphicsSceneInsertItemBspTreeVisitor* QGraphicsSceneBspTree::insertVisitor private
Definition at line 116 of file qgraphicsscene_bsp_p.h.
Referenced by insertItem(), QGraphicsSceneBspTree(), and ~QGraphicsSceneBspTree().
leafCnt
int QGraphicsSceneBspTree::leafCnt private
Definition at line 113 of file qgraphicsscene_bsp_p.h.
Referenced by clear(), initialize(), and leafCount().
leaves
QVector<QList<QGraphicsItem *> > QGraphicsSceneBspTree::leaves private
Definition at line 112 of file qgraphicsscene_bsp_p.h.
Referenced by clear(), climbTree(), debug(), initialize(), and removeItems().
nodes
QVector<Node> QGraphicsSceneBspTree::nodes private
Definition at line 111 of file qgraphicsscene_bsp_p.h.
Referenced by clear(), climbTree(), debug(), initialize(), and rectForIndex().
rect
QRectF QGraphicsSceneBspTree::rect private
Definition at line 114 of file qgraphicsscene_bsp_p.h.
Referenced by debug(), initialize(), parentIndex(), and rectForIndex().
removeVisitor
QGraphicsSceneRemoveItemBspTreeVisitor* QGraphicsSceneBspTree::removeVisitor private
Definition at line 117 of file qgraphicsscene_bsp_p.h.
Referenced by QGraphicsSceneBspTree(), removeItem(), and ~QGraphicsSceneBspTree().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsscene_bsp_p.h
/src/gui/graphicsview/qgraphicsscene_bsp.cpp