Qt 4.8: QTableView Class Reference
QTableView Class Reference
The QTableView class provides a default model/view implementation of a table view.
#include <qtableview.h>
Public Slots
void hideColumn (int column)
Hide the given column.
void hideRow (int row)
Hide the given row.
void resizeColumnsToContents ()
Resizes all columns based on the size hints of the delegate used to render each item in the columns.
void resizeColumnToContents (int column)
Resizes the given column based on the size hints of the delegate used to render each item in the column.
void resizeRowsToContents ()
Resizes all rows based on the size hints of the delegate used to render each item in the rows.
void resizeRowToContents (int row)
Resizes the given row based on the size hints of the delegate used to render each item in the row.
void selectColumn (int column)
Selects the given column in the table view if the current SelectionMode and SelectionBehavior allows columns to be selected.
void selectRow (int row)
Selects the given row in the table view if the current SelectionMode and SelectionBehavior allows rows to be selected.
void setShowGrid (bool show)
void showColumn (int column)
Show the given column.
void showRow (int row)
Show the given row.
void sortByColumn (int column)
Sorts the model by the values in the given column.
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
virtual void reset ()
Reset the internal state of the view.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
virtual void selectAll ()
Selects all items in the view.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void clearSpans ()
Removes all row and column spans in the table view.
int columnAt (int x) const
Returns the column in which the given x-coordinate, x, in contents coordinates is located.
int columnSpan (int row, int column) const
Returns the column span of the table element at (row, column).
int columnViewportPosition (int column) const
Returns the x-coordinate in contents coordinates of the given column.
int columnWidth (int column) const
Returns the width of the given column.
void doItemsLayout ()
Qt::PenStyle gridStyle () const
QHeaderView * horizontalHeader () const
Returns the table view's horizontal header.
QModelIndex indexAt (const QPoint &p) const
Returns the index position of the model item corresponding to the table item at position pos in contents coordinates.
bool isColumnHidden (int column) const
Returns true if the given column is hidden; otherwise returns false.
bool isCornerButtonEnabled () const
bool isRowHidden (int row) const
Returns true if the given row is hidden; otherwise returns false.
bool isSortingEnabled () const
QTableView (QWidget *parent=0)
Constructs a table view with a parent to represent the data.
int rowAt (int y) const
Returns the row in which the given y-coordinate, y, in contents coordinates is located.
int rowHeight (int row) const
Returns the height of the given row.
int rowSpan (int row, int column) const
Returns the row span of the table element at (row, column).
int rowViewportPosition (int row) const
Returns the y-coordinate in contents coordinates of the given row.
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Makes sure that the given item is visible in the table view, scrolling if necessary.
void setColumnHidden (int column, bool hide)
If hide is true the given column will be hidden; otherwise it will be shown.
void setColumnWidth (int column, int width)
Sets the width of the given column to be width.
void setCornerButtonEnabled (bool enable)
void setGridStyle (Qt::PenStyle style)
void setHorizontalHeader (QHeaderView *header)
Sets the widget to use for the horizontal header to header.
void setModel (QAbstractItemModel *model)
Reimplemented Function
void setRootIndex (const QModelIndex &index)
Reimplemented Function
void setRowHeight (int row, int height)
Sets the height of the given row to be height.
void setRowHidden (int row, bool hide)
If hide is true row will be hidden, otherwise it will be shown.
void setSelectionModel (QItemSelectionModel *selectionModel)
Reimplemented Function
void setSortingEnabled (bool enable)
If enabled true enables sorting for the table and immediately trigger a call to sortByColumn() with the current sort section and order.
void setSpan (int row, int column, int rowSpan, int columnSpan)
Sets the span of the table element at (row, column) to the number of rows and columns specified by (rowSpanCount, columnSpanCount).
void setVerticalHeader (QHeaderView *header)
Sets the widget to use for the vertical header to header.
void setWordWrap (bool on)
bool showGrid () const
void sortByColumn (int column, Qt::SortOrder order)
Sorts the model by the values in the given column in the given order.
QHeaderView * verticalHeader () const
Returns the table view's vertical header.
QRect visualRect (const QModelIndex &index) const
Returns the rectangle on the viewport occupied by the given index.
bool wordWrap () const
~QTableView ()
Destroys the table view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void columnCountChanged (int oldCount, int newCount)
This slot is called whenever columns are added or deleted.
void columnMoved (int column, int oldIndex, int newIndex)
This slot is called to change the index of the given column in the table view.
void columnResized (int column, int oldWidth, int newWidth)
This slot is called to change the width of the given column.
void rowCountChanged (int oldCount, int newCount)
This slot is called whenever rows are added or deleted.
void rowMoved (int row, int oldIndex, int newIndex)
This slot is called to change the index of the given row in the table view.
void rowResized (int row, int oldHeight, int newHeight)
This slot is called to change the height of the given row.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This slot is called when items are changed in the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarValueChanged (int value)
virtual void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
This slot is called when rows are about to be removed.
virtual void rowsInserted (const QModelIndex &parent, int start, int end)
This slot is called when rows are inserted.
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
int horizontalOffset () const
Returns the horizontal offset of the items in the table view.
void horizontalScrollbarAction (int action)
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Moves the cursor in accordance with the given cursorAction, using the information provided by the modifiers.
void paintEvent (QPaintEvent *e)
Paints the table on receipt of the given paint event event.
QTableView (QTableViewPrivate &, QWidget *parent)
void scrollContentsBy (int dx, int dy)
Scroll the contents of the table view by (dx, dy).
QModelIndexList selectedIndexes () const
Reimplemented Function
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Reimplemented Function
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Applies the selection flags to the items in or touched by the rectangle, rect.
int sizeHintForColumn (int column) const
Returns the size hint for the given column's width or -1 if there is no model.
int sizeHintForRow (int row) const
Returns the size hint for the given row's height or -1 if there is no model.
void timerEvent (QTimerEvent *event)
Reimplemented Function
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Returns the vertical offset of the items in the table view.
void verticalScrollbarAction (int action)
QStyleOptionViewItem viewOptions () const
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Returns the rectangle from the viewport of the items in the given selection.
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
void dragMoveEvent (QDragMoveEvent *event)
This function is called continuously with the given event during a drag and drop operation over the widget.
void dropEvent (QDropEvent *event)
This function is called with the given event when a drop event occurs over the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
bool event (QEvent *event)
Reimplemented Function
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
void mouseDoubleClickEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is double clicked inside the widget.
void mouseMoveEvent (QMouseEvent *event)
This function is called with the given event when a mouse move event is sent to the widget.
void mousePressEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
void mouseReleaseEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is released, after a mouse press event on the widget.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
This function is called with the given event when a resize event is sent to the widget.
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
bool viewportEvent (QEvent *event)
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
int visualIndex (const QModelIndex &index) const
Properties
bool cornerButtonEnabled
whether the button in the top-left corner is enabled
Qt::PenStyle gridStyle
the pen style used to draw the grid.
bool showGrid
whether the grid is shown
bool sortingEnabled
whether sorting is enabled
bool wordWrap
the item text word-wrapping policy
Friends
class QAccessibleItemView
Additional Inherited Members
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTableView class provides a default model/view implementation of a table view.
A QTableView implements a table view that displays items from a model. This class is used to provide standard tables that were previously provided by the QTable class, but using the more flexible approach provided by Qt's model/view architecture.
The QTableView class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
QTableView implements the interfaces defined by the QAbstractItemView class to allow it to display data provided by models derived from the QAbstractItemModel class.
Navigation
You can navigate the cells in the table by clicking on a cell with the mouse, or by using the arrow keys. Because QTableView enables tabKeyNavigation by default, you can also hit Tab and Backtab to move from cell to cell.
Visual Appearance
The table has a vertical header that can be obtained using the verticalHeader() function, and a horizontal header that is available through the horizontalHeader() function. The height of each row in the table can be found by using rowHeight(); similarly, the width of columns can be found using columnWidth(). Since both of these are plain widgets, you can hide either of them using their hide() functions.
Rows and columns can be hidden and shown with hideRow(), hideColumn(), showRow(), and showColumn(). They can be selected with selectRow() and selectColumn(). The table will show a grid depending on the showGrid property.
The items shown in a table view, like those in the other item views, are rendered and edited using standard delegates. However, for some tasks it is sometimes useful to be able to insert widgets in a table instead. Widgets are set for particular indexes with the QAbstractItemView::setIndexWidget() function, and later retrieved with QAbstractItemView::indexWidget().
By default, the cells in a table do not expand to fill the available space.
You can make the cells fill the available space by stretching the last header section. Access the relevant header using horizontalHeader() or verticalHeader() and set the header's QHeaderView::stretchLastSection property.
To distribute the available space according to the space requirement of each column or row, call the view's resizeColumnsToContents() or resizeRowsToContents() functions.
Coordinate Systems
For some specialized forms of tables it is useful to be able to convert between row and column indexes and widget coordinates. The rowAt() function provides the y-coordinate within the view of the specified row; the row index can be used to obtain a corresponding y-coordinate with rowViewportPosition(). The columnAt() and columnViewportPosition() functions provide the equivalent conversion operations between x-coordinates and column indexes.
Styles
QTableView is styled appropriately for each platform. The following images show how it looks on three different platforms. Go to the Qt Widget Gallery to see its appearance in other styles.
Screenshot of a Windows XP style table view
Screenshot of a Macintosh style table view
Screenshot of a Plastique style table view
A Windows XP Style Widget Gallery{Windows XP style} table view. A Macintosh Style Widget Gallery{Macintosh style} table view. A Plastique Style Widget Gallery{Plastique style} table view.
See also
QTableWidget, {View Classes}, QAbstractItemModel, QAbstractItemView, {Chart Example}, {Pixelator Example}, {Table Model Example}
Definition at line 58 of file qtableview.h.
Constructors and Destructors
QTableView() [1/2]
QTableView::QTableView (QWidget * parent = 0) explicit
Constructs a table view with a parent to represent the data.
See also
QAbstractItemModel
Definition at line 1076 of file qtableview.cpp.
     : QAbstractItemView(*new QTableViewPrivate, parent)
 {
     Q_D(QTableView);
     d->init();
 }
~QTableView()
QTableView::~QTableView ()
Destroys the table view.
Definition at line 1096 of file qtableview.cpp.
 {
 }
QTableView() [2/2]
QTableView::QTableView (QTableViewPrivate & dd, QWidget * parent) protected
Warning
This function is not part of the public interface.
Definition at line 1086 of file qtableview.cpp.
     : QAbstractItemView(dd, parent)
 {
     Q_D(QTableView);
     d->init();
 }
Functions
clearSpans()
void QTableView::clearSpans ()
Removes all row and column spans in the table view.
Since
4.4
See also
setSpan()
Definition at line 3172 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->spans.clear();
     d->viewport->update();
 }
columnAt()
int QTableView::columnAt (int x) const
Returns the column in which the given x-coordinate, x, in contents coordinates is located.
Note
This function returns -1 if the given coordinate is not valid (has no column).
See also
rowAt()
Definition at line 2378 of file qtableview.cpp.
Referenced by indexAt().
 {
     Q_D(const QTableView);
     return d->horizontalHeader->logicalIndexAt(x);
 }
columnCountChanged
void QTableView::columnCountChanged (int oldCount, int newCount) protected slot
This slot is called whenever columns are added or deleted.
The previous number of columns is specified by oldCount, and the new number of columns is specified by newCount.
Definition at line 2069 of file qtableview.cpp.
Referenced by setHorizontalHeader().
 {
     Q_D(QTableView);
     updateGeometries();
     if (horizontalScrollMode() == QAbstractItemView::ScrollPerItem)
         d->horizontalHeader->setOffsetToSectionPosition(horizontalScrollBar()->value());
     else
         d->horizontalHeader->setOffset(horizontalScrollBar()->value());
     d->viewport->update();
 }
columnMoved
void QTableView::columnMoved (int column, int oldIndex, int newIndex) protected slot
This slot is called to change the index of the given column in the table view.
The old index is specified by oldIndex, and the new index by newIndex.
See also
rowMoved()
Definition at line 2904 of file qtableview.cpp.
Referenced by setHorizontalHeader().
 {
     Q_D(QTableView);
     updateGeometries();
     int logicalOldIndex = d->horizontalHeader->logicalIndex(oldIndex);
     int logicalNewIndex = d->horizontalHeader->logicalIndex(newIndex);
     if (d->hasSpans()) {
         d->viewport->update();
     } else {
         int oldLeft = columnViewportPosition(logicalOldIndex);
         int newLeft = columnViewportPosition(logicalNewIndex);
         int oldRight = oldLeft + columnWidth(logicalOldIndex);
         int newRight = newLeft + columnWidth(logicalNewIndex);
         int left = qMin(oldLeft, newLeft);
         int right = qMax(oldRight, newRight);
         int width = right - left;
         d->viewport->update(left, 0, width, d->viewport->height());
     }
 }
columnResized
void QTableView::columnResized (int column, int oldWidth, int newWidth) protected slot
This slot is called to change the width of the given column.
The old width is specified by oldWidth, and the new width by newWidth.
See also
rowResized()
Definition at line 2804 of file qtableview.cpp.
Referenced by setHorizontalHeader().
 {
     Q_D(QTableView);
     d->columnsToUpdate.append(column);
     if (d->columnResizeTimerID == 0)
         d->columnResizeTimerID = startTimer(0);
 }
columnSpan()
int QTableView::columnSpan (int row, int column) const
Returns the column span of the table element at (row, column).
Since
4.2
The default is 1.
See also
setSpan(), rowSpan()
Definition at line 3155 of file qtableview.cpp.
 {
     Q_D(const QTableView);
     return d->columnSpan(row, column);
 }
columnViewportPosition()
int QTableView::columnViewportPosition (int column) const
Returns the x-coordinate in contents coordinates of the given column.
Definition at line 2363 of file qtableview.cpp.
Referenced by columnMoved(), paintEvent(), sizeHintForRow(), timerEvent(), visualRect(), and visualRegionForSelection().
 {
     Q_D(const QTableView);
     return d->horizontalHeader->sectionViewportPosition(column);
 }
columnWidth()
int QTableView::columnWidth (int column) const
Returns the width of the given column.
See also
resizeColumnToContents(), rowHeight()
Definition at line 2403 of file qtableview.cpp.
Referenced by columnMoved(), paintEvent(), scrollTo(), sizeHintForRow(), timerEvent(), visualRect(), and visualRegionForSelection().
 {
     Q_D(const QTableView);
     return d->horizontalHeader->sectionSize(column);
 }
currentChanged()
void QTableView::currentChanged (const QModelIndex & current, const QModelIndex & previous) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3269 of file qtableview.cpp.
 {
 #ifndef QT_NO_ACCESSIBILITY
     if (QAccessible::isActive()) {
         if (current.isValid()) {
 #ifdef Q_WS_X11
             Q_D(QTableView);
             int entry = d->accessibleTable2Index(current);
             QAccessible::updateAccessibility(this, entry, QAccessible::Focus);
 #else
             int entry = visualIndex(current) + 1;
             if (horizontalHeader())
                 ++entry;
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::Focus);
 #endif
         }
     }
 #endif
     QAbstractItemView::currentChanged(current, previous);
 }
doItemsLayout()
void QTableView::doItemsLayout () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 1152 of file qtableview.cpp.
 {
     Q_D(QTableView);
     QAbstractItemView::doItemsLayout();
     if (verticalScrollMode() == QAbstractItemView::ScrollPerItem) {
         const int max = verticalScrollBar()->maximum();
         if (max > 0 && verticalScrollBar()->value() == max)
             d->verticalHeader->setOffsetToLastSection();
         else
             d->verticalHeader->setOffsetToSectionPosition(verticalScrollBar()->value());
     } else {
         d->verticalHeader->setOffset(verticalScrollBar()->value());
     }
     if (!d->verticalHeader->updatesEnabled())
         d->verticalHeader->setUpdatesEnabled(true);
 }
gridStyle()
Qt::PenStyle QTableView::gridStyle () const
Referenced by setShowGrid().
hideColumn
void QTableView::hideColumn (int column) slot
Hide the given column.
See also
showColumn() hideRow()
Definition at line 2965 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->horizontalHeader->hideSection(column);
 }
hideRow
void QTableView::hideRow (int row) slot
Hide the given row.
See also
showRow() hideColumn()
Definition at line 2954 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->verticalHeader->hideSection(row);
 }
horizontalHeader()
QHeaderView * QTableView::horizontalHeader () const
Returns the table view's horizontal header.
See also
setHorizontalHeader(), verticalHeader(), QAbstractItemModel::headerData()
Definition at line 1186 of file qtableview.cpp.
Referenced by currentChanged(), paintEvent(), QCalendarView::QCalendarView(), QTableViewPrivate::selectColumn(), selectionChanged(), QTableViewPrivate::selectRow(), QTableModel::setItem(), setSelection(), setSortingEnabled(), QTableWidget::sortItems(), QTableWidget::visualColumn(), and visualRegionForSelection().
 {
     Q_D(const QTableView);
     return d->horizontalHeader;
 }
horizontalOffset()
int QTableView::horizontalOffset () const protected virtual
Returns the horizontal offset of the items in the table view.
Note that the table view uses the horizontal header section positions to determine the positions of columns in the view.
See also
verticalOffset()
Implements QAbstractItemView.
Definition at line 1546 of file qtableview.cpp.
Referenced by scrollTo().
 {
     Q_D(const QTableView);
     return d->horizontalHeader->offset();
 }
horizontalScrollbarAction()
void QTableView::horizontalScrollbarAction (int action) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 3085 of file qtableview.cpp.
 {
     QAbstractItemView::horizontalScrollbarAction(action);
 }
indexAt()
QModelIndex QTableView::indexAt (const QPoint & p) const virtual
Returns the index position of the model item corresponding to the table item at position pos in contents coordinates.
Implements QAbstractItemView.
Definition at line 1521 of file qtableview.cpp.
Referenced by QCalendarView::handleMouseEvent(), QTableWidget::itemAt(), and setSelection().
 {
     Q_D(const QTableView);
     d->executePostedLayout();
     int r = rowAt(pos.y());
     int c = columnAt(pos.x());
     if (r >= 0 && c >= 0) {
         if (d->hasSpans()) {
             QSpanCollection::Span span = d->span(r, c);
             r = span.top();
             c = span.left();
         }
         return d->model->index(r, c, d->root);
     }
     return QModelIndex();
 }
isColumnHidden()
bool QTableView::isColumnHidden (int column) const
Returns true if the given column is hidden; otherwise returns false.
See also
isRowHidden()
Definition at line 2438 of file qtableview.cpp.
Referenced by isIndexHidden(), moveCursor(), and scrollTo().
 {
     Q_D(const QTableView);
     return d->horizontalHeader->isSectionHidden(column);
 }
isCornerButtonEnabled()
bool QTableView::isCornerButtonEnabled () const
Definition at line 2614 of file qtableview.cpp.
 {
     Q_D(const QTableView);
     return d->cornerWidget->isEnabled();
 }
isIndexHidden()
bool QTableView::isIndexHidden (const QModelIndex & index) const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 3093 of file qtableview.cpp.
Referenced by selectedIndexes(), QTableWidget::selectedItems(), and visualRect().
 {
     Q_D(const QTableView);
     Q_ASSERT(d->isIndexValid(index));
     if (isRowHidden(index.row()) || isColumnHidden(index.column()))
         return true;
     if (d->hasSpans()) {
         QSpanCollection::Span span = d->span(index.row(), index.column());
         return !((span.top() == index.row()) && (span.left() == index.column()));
     }
     return false;
 }
isRowHidden()
bool QTableView::isRowHidden (int row) const
Returns true if the given row is hidden; otherwise returns false.
See also
isColumnHidden()
Definition at line 2414 of file qtableview.cpp.
Referenced by isIndexHidden(), moveCursor(), and scrollTo().
 {
     Q_D(const QTableView);
     return d->verticalHeader->isSectionHidden(row);
 }
isSortingEnabled()
bool QTableView::isSortingEnabled () const
Definition at line 2506 of file qtableview.cpp.
Referenced by QTableWidget::isSortingEnabled().
 {
     Q_D(const QTableView);
     return d->sortingEnabled;
 }
moveCursor()
QModelIndex QTableView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) protected virtual
Moves the cursor in accordance with the given cursorAction, using the information provided by the modifiers.
See also
QAbstractItemView::CursorAction
Implements QAbstractItemView.
Reimplemented in QCalendarView.
Definition at line 1577 of file qtableview.cpp.
Referenced by QCalendarView::moveCursor().
 {
     Q_D(QTableView);
     Q_UNUSED(modifiers);
     int bottom = d->model->rowCount(d->root) - 1;
     // make sure that bottom is the bottommost *visible* row
     while (bottom >= 0 && isRowHidden(d->logicalRow(bottom)))
         --bottom;
     int right = d->model->columnCount(d->root) - 1;
     while (right >= 0 && isColumnHidden(d->logicalColumn(right)))
         --right;
     if (bottom == -1 || right == -1)
         return QModelIndex(); // model is empty
     QModelIndex current = currentIndex();
     if (!current.isValid()) {
         int row = 0;
         int column = 0;
         while (column < right && isColumnHidden(d->logicalColumn(column)))
             ++column;
         while (isRowHidden(d->logicalRow(row)) && row < bottom)
             ++row;
         d->visualCursor = QPoint(column, row);
         return d->model->index(d->logicalRow(row), d->logicalColumn(column), d->root);
     }
     // Update visual cursor if current index has changed.
     QPoint visualCurrent(d->visualColumn(current.column()), d->visualRow(current.row()));
     if (visualCurrent != d->visualCursor) {
         if (d->hasSpans()) {
             QSpanCollection::Span span = d->span(current.row(), current.column());
             if (span.top() > d->visualCursor.y() || d->visualCursor.y() > span.bottom()
                 || span.left() > d->visualCursor.x() || d->visualCursor.x() > span.right())
                 d->visualCursor = visualCurrent;
         } else {
             d->visualCursor = visualCurrent;
         }
     }
     int visualRow = d->visualCursor.y();
     if (visualRow > bottom)
         visualRow = bottom;
     Q_ASSERT(visualRow != -1);
     int visualColumn = d->visualCursor.x();
     if (visualColumn > right)
         visualColumn = right;
     Q_ASSERT(visualColumn != -1);
     if (isRightToLeft()) {
         if (cursorAction == MoveLeft)
             cursorAction = MoveRight;
         else if (cursorAction == MoveRight)
             cursorAction = MoveLeft;
     }
     switch (cursorAction) {
     case MoveUp: {
         int originalRow = visualRow;
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && visualRow == 0)
             visualRow = d->visualRow(model()->rowCount() - 1) + 1;
             // FIXME? visualRow = bottom + 1;
 #endif
         int r = d->logicalRow(visualRow);
         int c = d->logicalColumn(visualColumn);
         if (r != -1 && d->hasSpans()) {
             QSpanCollection::Span span = d->span(r, c);
             if (span.width() > 1 || span.height() > 1)
                 visualRow = d->visualRow(span.top());
         }
         while (visualRow >= 0) {
             --visualRow;
             r = d->logicalRow(visualRow);
             c = d->logicalColumn(visualColumn);
             if (r == -1 || (!isRowHidden(r) && d->isCellEnabled(r, c)))
                 break;
         }
         if (visualRow < 0)
             visualRow = originalRow;
         break;
     }
     case MoveDown: {
         int originalRow = visualRow;
         if (d->hasSpans()) {
             QSpanCollection::Span span = d->span(current.row(), current.column());
             visualRow = d->visualRow(d->rowSpanEndLogical(span.top(), span.height()));
         }
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && visualRow >= bottom)
             visualRow = -1;
 #endif
         int r = d->logicalRow(visualRow);
         int c = d->logicalColumn(visualColumn);
         if (r != -1 && d->hasSpans()) {
             QSpanCollection::Span span = d->span(r, c);
             if (span.width() > 1 || span.height() > 1)
                 visualRow = d->visualRow(d->rowSpanEndLogical(span.top(), span.height()));
         }
         while (visualRow <= bottom) {
             ++visualRow;
             r = d->logicalRow(visualRow);
             c = d->logicalColumn(visualColumn);
             if (r == -1 || (!isRowHidden(r) && d->isCellEnabled(r, c)))
                 break;
         }
         if (visualRow > bottom)
             visualRow = originalRow;
         break;
     }
     case MovePrevious:
     case MoveLeft: {
         int originalRow = visualRow;
         int originalColumn = visualColumn;
         bool firstTime = true;
         bool looped = false;
         bool wrapped = false;
         do {
             int r = d->logicalRow(visualRow);
             int c = d->logicalColumn(visualColumn);
             if (firstTime && c != -1 && d->hasSpans()) {
                 firstTime = false;
                 QSpanCollection::Span span = d->span(r, c);
                 if (span.width() > 1 || span.height() > 1)
                     visualColumn = d->visualColumn(span.left());
             }
             while (visualColumn >= 0) {
                 --visualColumn;
                 r = d->logicalRow(visualRow);
                 c = d->logicalColumn(visualColumn);
                 if (r == -1 || c == -1 || (!isRowHidden(r) && !isColumnHidden(c) && d->isCellEnabled(r, c)))
                     break;
                 if (wrapped && (originalRow < visualRow || (originalRow == visualRow && originalColumn <= visualColumn))) {
                     looped = true;
                     break;
                 }
             }
             if (cursorAction == MoveLeft || visualColumn >= 0)
                 break;
             visualColumn = right + 1;
             if (visualRow == 0) {
                 wrapped = true;
                 visualRow = bottom;
             } else {
                 --visualRow;
             }
         } while (!looped);
         if (visualColumn < 0)
             visualColumn = originalColumn;
         break;
     }
     case MoveNext:
     case MoveRight: {
         int originalRow = visualRow;
         int originalColumn = visualColumn;
         bool firstTime = true;
         bool looped = false;
         bool wrapped = false;
         do {
             int r = d->logicalRow(visualRow);
             int c = d->logicalColumn(visualColumn);
             if (firstTime && c != -1 && d->hasSpans()) {
                 firstTime = false;
                 QSpanCollection::Span span = d->span(r, c);
                 if (span.width() > 1 || span.height() > 1)
                     visualColumn = d->visualColumn(d->columnSpanEndLogical(span.left(), span.width()));
             }
             while (visualColumn <= right) {
                 ++visualColumn;
                 r = d->logicalRow(visualRow);
                 c = d->logicalColumn(visualColumn);
                 if (r == -1 || c == -1 || (!isRowHidden(r) && !isColumnHidden(c) && d->isCellEnabled(r, c)))
                     break;
                 if (wrapped && (originalRow > visualRow || (originalRow == visualRow && originalColumn >= visualColumn))) {
                     looped = true;
                     break;
                 }
             }
             if (cursorAction == MoveRight || visualColumn <= right)
                 break;
             visualColumn = -1;
             if (visualRow == bottom) {
                 wrapped = true;
                 visualRow = 0;
             } else {
                 ++visualRow;
             }
         } while (!looped);
         if (visualColumn > right)
             visualColumn = originalColumn;
         break;
     }
     case MoveHome:
         visualColumn = 0;
         while (visualColumn < right && d->isVisualColumnHiddenOrDisabled(visualRow, visualColumn))
             ++visualColumn;
         if (modifiers & Qt::ControlModifier) {
             visualRow = 0;
             while (visualRow < bottom && d->isVisualRowHiddenOrDisabled(visualRow, visualColumn))
                 ++visualRow;
         }
         break;
     case MoveEnd:
         visualColumn = right;
         if (modifiers & Qt::ControlModifier)
             visualRow = bottom;
         break;
     case MovePageUp: {
         int newRow = rowAt(visualRect(current).top() - d->viewport->height());
         if (newRow == -1)
             newRow = d->logicalRow(0);
         return d->model->index(newRow, current.column(), d->root);
     }
     case MovePageDown: {
         int newRow = rowAt(visualRect(current).bottom() + d->viewport->height());
         if (newRow == -1)
             newRow = d->logicalRow(bottom);
         return d->model->index(newRow, current.column(), d->root);
     }}
     d->visualCursor = QPoint(visualColumn, visualRow);
     int logicalRow = d->logicalRow(visualRow);
     int logicalColumn = d->logicalColumn(visualColumn);
     if (!d->model->hasIndex(logicalRow, logicalColumn, d->root))
         return QModelIndex();
     QModelIndex result = d->model->index(logicalRow, logicalColumn, d->root);
     if (!d->isRowHidden(logicalRow) && !d->isColumnHidden(logicalColumn) && d->isIndexEnabled(result))
         return result;
     return QModelIndex();
 }
paintEvent()
void QTableView::paintEvent (QPaintEvent * e) protected virtual
Paints the table on receipt of the given paint event event.
Reimplemented from QWidget.
Definition at line 1343 of file qtableview.cpp.
 {
     Q_D(QTableView);
     // setup temp variables for the painting
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     const QPoint offset = d->scrollDelayOffset;
     const bool showGrid = d->showGrid;
     const int gridSize = showGrid ? 1 : 0;
     const int gridHint = style()->styleHint(QStyle::SH_Table_GridLineColor, &option, this);
     const QColor gridColor = static_cast<QRgb>(gridHint);
     const QPen gridPen = QPen(gridColor, 0, d->gridStyle);
     const QHeaderView *verticalHeader = d->verticalHeader;
     const QHeaderView *horizontalHeader = d->horizontalHeader;
     const bool alternate = d->alternatingColors;
     const bool rightToLeft = isRightToLeft();
     QPainter painter(d->viewport);
     // if there's nothing to do, clear the area and return
     if (horizontalHeader->count() == 0 || verticalHeader->count() == 0 || !d->itemDelegate)
         return;
     uint x = horizontalHeader->length() - horizontalHeader->offset() - (rightToLeft ? 0 : 1);
     uint y = verticalHeader->length() - verticalHeader->offset() - 1;
     const QRegion region = event->region().translated(offset);
     const QVector<QRect> rects = region.rects();
     //firstVisualRow is the visual index of the first visible row.  lastVisualRow is the visual index of the last visible Row.
     //same goes for ...VisualColumn
     int firstVisualRow = qMax(verticalHeader->visualIndexAt(0),0);
     int lastVisualRow = verticalHeader->visualIndexAt(verticalHeader->viewport()->height());
     if (lastVisualRow == -1)
         lastVisualRow = d->model->rowCount(d->root) - 1;
     int firstVisualColumn = horizontalHeader->visualIndexAt(0);
     int lastVisualColumn = horizontalHeader->visualIndexAt(horizontalHeader->viewport()->width());
     if (rightToLeft)
         qSwap(firstVisualColumn, lastVisualColumn);
     if (firstVisualColumn == -1)
         firstVisualColumn = 0;
     if (lastVisualColumn == -1)
         lastVisualColumn = horizontalHeader->count() - 1;
     QBitArray drawn((lastVisualRow - firstVisualRow + 1) * (lastVisualColumn - firstVisualColumn + 1));
     if (d->hasSpans()) {
         d->drawAndClipSpans(region, &painter, option, &drawn,
                              firstVisualRow, lastVisualRow, firstVisualColumn, lastVisualColumn);
     }
     for (int i = 0; i < rects.size(); ++i) {
         QRect dirtyArea = rects.at(i);
         dirtyArea.setBottom(qMin(dirtyArea.bottom(), int(y)));
         if (rightToLeft) {
             dirtyArea.setLeft(qMax(dirtyArea.left(), d->viewport->width() - int(x)));
         } else {
             dirtyArea.setRight(qMin(dirtyArea.right(), int(x)));
         }
         // get the horizontal start and end visual sections
         int left = horizontalHeader->visualIndexAt(dirtyArea.left());
         int right = horizontalHeader->visualIndexAt(dirtyArea.right());
         if (rightToLeft)
             qSwap(left, right);
         if (left == -1) left = 0;
         if (right == -1) right = horizontalHeader->count() - 1;
         // get the vertical start and end visual sections and if alternate color
         int bottom = verticalHeader->visualIndexAt(dirtyArea.bottom());
         if (bottom == -1) bottom = verticalHeader->count() - 1;
         int top = 0;
         bool alternateBase = false;
         if (alternate && verticalHeader->sectionsHidden()) {
             uint verticalOffset = verticalHeader->offset();
             int row = verticalHeader->logicalIndex(top);
             for (int y = 0;
                  ((uint)(y += verticalHeader->sectionSize(top)) <= verticalOffset) && (top < bottom);
                  ++top) {
                 row = verticalHeader->logicalIndex(top);
                 if (alternate && !verticalHeader->isSectionHidden(row))
                     alternateBase = !alternateBase;
             }
         } else {
             top = verticalHeader->visualIndexAt(dirtyArea.top());
             alternateBase = (top & 1) && alternate;
         }
         if (top == -1 || top > bottom)
             continue;
         // Paint each row item
         for (int visualRowIndex = top; visualRowIndex <= bottom; ++visualRowIndex) {
             int row = verticalHeader->logicalIndex(visualRowIndex);
             if (verticalHeader->isSectionHidden(row))
                 continue;
             int rowY = rowViewportPosition(row);
             rowY += offset.y();
             int rowh = rowHeight(row) - gridSize;
             // Paint each column item
             for (int visualColumnIndex = left; visualColumnIndex <= right; ++visualColumnIndex) {
                 int currentBit = (visualRowIndex - firstVisualRow) * (lastVisualColumn - firstVisualColumn + 1)
                         + visualColumnIndex - firstVisualColumn;
                 if (currentBit < 0 || currentBit >= drawn.size() || drawn.testBit(currentBit))
                     continue;
                 drawn.setBit(currentBit);
                 int col = horizontalHeader->logicalIndex(visualColumnIndex);
                 if (horizontalHeader->isSectionHidden(col))
                     continue;
                 int colp = columnViewportPosition(col);
                 colp += offset.x();
                 int colw = columnWidth(col) - gridSize;
                 const QModelIndex index = d->model->index(row, col, d->root);
                 if (index.isValid()) {
                     option.rect = QRect(colp + (showGrid && rightToLeft ? 1 : 0), rowY, colw, rowh);
                     if (alternate) {
                         if (alternateBase)
                             option.features |= QStyleOptionViewItemV2::Alternate;
                         else
                             option.features &= ~QStyleOptionViewItemV2::Alternate;
                     }
                     d->drawCell(&painter, option, index);
                 }
             }
             alternateBase = !alternateBase && alternate;
         }
         if (showGrid) {
             // Find the bottom right (the last rows/columns might be hidden)
             while (verticalHeader->isSectionHidden(verticalHeader->logicalIndex(bottom))) --bottom;
             QPen old = painter.pen();
             painter.setPen(gridPen);
             // Paint each row
             for (int visualIndex = top; visualIndex <= bottom; ++visualIndex) {
                 int row = verticalHeader->logicalIndex(visualIndex);
                 if (verticalHeader->isSectionHidden(row))
                     continue;
                 int rowY = rowViewportPosition(row);
                 rowY += offset.y();
                 int rowh = rowHeight(row) - gridSize;
                 painter.drawLine(dirtyArea.left(), rowY + rowh, dirtyArea.right(), rowY + rowh);
             }
             // Paint each column
             for (int h = left; h <= right; ++h) {
                 int col = horizontalHeader->logicalIndex(h);
                 if (horizontalHeader->isSectionHidden(col))
                     continue;
                 int colp = columnViewportPosition(col);
                 colp += offset.x();
                 if (!rightToLeft)
                     colp +=  columnWidth(col) - gridSize;
                 painter.drawLine(colp, dirtyArea.top(), colp, dirtyArea.bottom());
             }
             //draw the top & left grid lines if the headers are not visible.
             //We do update this line when subsequent scroll happen (see scrollContentsBy)
             if (horizontalHeader->isHidden() && verticalScrollMode() == ScrollPerItem)
                 painter.drawLine(dirtyArea.left(), 0, dirtyArea.right(), 0);
             if (verticalHeader->isHidden() && horizontalScrollMode() == ScrollPerItem)
                 painter.drawLine(0, dirtyArea.top(), 0, dirtyArea.bottom());
             painter.setPen(old);
         }
     }
 #ifndef QT_NO_DRAGANDDROP
     // Paint the dropIndicator
     d->paintDropIndicator(&painter);
 #endif
 }
resizeColumnsToContents
void QTableView::resizeColumnsToContents () slot
Resizes all columns based on the size hints of the delegate used to render each item in the columns.
Definition at line 3034 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->horizontalHeader->resizeSections(QHeaderView::ResizeToContents);
 }
resizeColumnToContents
void QTableView::resizeColumnToContents (int column) slot
Resizes the given column based on the size hints of the delegate used to render each item in the column.
Note
Only visible columns will be resized. Reimplement sizeHintForColumn() to resize hidden columns as well.
Definition at line 3022 of file qtableview.cpp.
Referenced by setHorizontalHeader().
 {
     Q_D(QTableView);
     int content = sizeHintForColumn(column);
     int header = d->horizontalHeader->sectionSizeHint(column);
     d->horizontalHeader->resizeSection(column, qMax(content, header));
 }
resizeRowsToContents
void QTableView::resizeRowsToContents () slot
Resizes all rows based on the size hints of the delegate used to render each item in the rows.
Definition at line 3009 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->verticalHeader->resizeSections(QHeaderView::ResizeToContents);
 }
resizeRowToContents
void QTableView::resizeRowToContents (int row) slot
Resizes the given row based on the size hints of the delegate used to render each item in the row.
Definition at line 2997 of file qtableview.cpp.
Referenced by setVerticalHeader().
 {
     Q_D(QTableView);
     int content = sizeHintForRow(row);
     int header = d->verticalHeader->sectionSizeHint(row);
     d->verticalHeader->resizeSection(row, qMax(content, header));
 }
rowAt()
int QTableView::rowAt (int y) const
Returns the row in which the given y-coordinate, y, in contents coordinates is located.
Note
This function returns -1 if the given coordinate is not valid (has no row).
See also
columnAt()
Definition at line 2328 of file qtableview.cpp.
Referenced by indexAt(), and moveCursor().
 {
     Q_D(const QTableView);
     return d->verticalHeader->logicalIndexAt(y);
 }
rowCountChanged
void QTableView::rowCountChanged (int oldCount, int newCount) protected slot
This slot is called whenever rows are added or deleted.
The previous number of rows is specified by oldCount, and the new number of rows is specified by newCount.
Definition at line 2054 of file qtableview.cpp.
Referenced by setVerticalHeader().
 {
     Q_D(QTableView);
     //when removing rows, we need to disable updates for the header until the geometries have been
     //updated and the offset has been adjusted, or we risk calling paintSection for all the sections
     if (newCount < oldCount)
         d->verticalHeader->setUpdatesEnabled(false);
     d->doDelayedItemsLayout();
 }
rowHeight()
int QTableView::rowHeight (int row) const
Returns the height of the given row.
See also
resizeRowToContents(), columnWidth()
Definition at line 2353 of file qtableview.cpp.
Referenced by paintEvent(), rowMoved(), sizeHintForRow(), visualRect(), and visualRegionForSelection().
 {
     Q_D(const QTableView);
     return d->verticalHeader->sectionSize(row);
 }
rowMoved
void QTableView::rowMoved (int row, int oldIndex, int newIndex) protected slot
This slot is called to change the index of the given row in the table view.
The old index is specified by oldIndex, and the new index by newIndex.
See also
columnMoved()
Definition at line 2876 of file qtableview.cpp.
Referenced by setVerticalHeader().
 {
     Q_D(QTableView);
     updateGeometries();
     int logicalOldIndex = d->verticalHeader->logicalIndex(oldIndex);
     int logicalNewIndex = d->verticalHeader->logicalIndex(newIndex);
     if (d->hasSpans()) {
         d->viewport->update();
     } else {
         int oldTop = rowViewportPosition(logicalOldIndex);
         int newTop = rowViewportPosition(logicalNewIndex);
         int oldBottom = oldTop + rowHeight(logicalOldIndex);
         int newBottom = newTop + rowHeight(logicalNewIndex);
         int top = qMin(oldTop, newTop);
         int bottom = qMax(oldBottom, newBottom);
         int height = bottom - top;
         d->viewport->update(0, top, d->viewport->width(), height);
     }
 }
rowResized
void QTableView::rowResized (int row, int oldHeight, int newHeight) protected slot
This slot is called to change the height of the given row.
The old height is specified by oldHeight, and the new height by newHeight.
See also
columnResized()
Definition at line 2789 of file qtableview.cpp.
Referenced by setVerticalHeader().
 {
     Q_D(QTableView);
     d->rowsToUpdate.append(row);
     if (d->rowResizeTimerID == 0)
         d->rowResizeTimerID = startTimer(0);
 }
rowSpan()
int QTableView::rowSpan (int row, int column) const
Returns the row span of the table element at (row, column).
Since
4.2
The default is 1.
See also
setSpan(), columnSpan()
Definition at line 3138 of file qtableview.cpp.
 {
     Q_D(const QTableView);
     return d->rowSpan(row, column);
 }
rowViewportPosition()
int QTableView::rowViewportPosition (int row) const
Returns the y-coordinate in contents coordinates of the given row.
Definition at line 2313 of file qtableview.cpp.
Referenced by paintEvent(), rowMoved(), sizeHintForRow(), timerEvent(), visualRect(), and visualRegionForSelection().
 {
     Q_D(const QTableView);
     return d->verticalHeader->sectionViewportPosition(row);
 }
scrollContentsBy()
void QTableView::scrollContentsBy (int dx, int dy) protected virtual
Scroll the contents of the table view by (dx, dy).
Warning
This function is not part of the public interface.
Reimplemented from QAbstractScrollArea.
Definition at line 1282 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->delayedAutoScroll.stop(); // auto scroll was canceled by the user scrolling
     dx = isRightToLeft() ? -dx : dx;
     if (dx) {
         if (horizontalScrollMode() == QAbstractItemView::ScrollPerItem) {
             int oldOffset = d->horizontalHeader->offset();
             if (horizontalScrollBar()->value() == horizontalScrollBar()->maximum())
                 d->horizontalHeader->setOffsetToLastSection();
             else
                 d->horizontalHeader->setOffsetToSectionPosition(horizontalScrollBar()->value());
             int newOffset = d->horizontalHeader->offset();
             dx = isRightToLeft() ? newOffset - oldOffset : oldOffset - newOffset;
         } else {
             d->horizontalHeader->setOffset(horizontalScrollBar()->value());
         }
     }
     if (dy) {
         if (verticalScrollMode() == QAbstractItemView::ScrollPerItem) {
             int oldOffset = d->verticalHeader->offset();
             if (verticalScrollBar()->value() == verticalScrollBar()->maximum())
                 d->verticalHeader->setOffsetToLastSection();
             else
                 d->verticalHeader->setOffsetToSectionPosition(verticalScrollBar()->value());
             int newOffset = d->verticalHeader->offset();
             dy = oldOffset - newOffset;
         } else {
             d->verticalHeader->setOffset(verticalScrollBar()->value());
         }
     }
     d->scrollContentsBy(dx, dy);
     if (d->showGrid) {
         //we need to update the first line of the previous top item in the view
         //because it has the grid drawn if the header is invisible.
         //It is strictly related to what's done at then end of the paintEvent
         if (dy > 0 && d->horizontalHeader->isHidden() && d->verticalScrollMode == ScrollPerItem) {
             d->viewport->update(0, dy, d->viewport->width(), dy);
         }
         if (dx > 0 && d->verticalHeader->isHidden() && d->horizontalScrollMode == ScrollPerItem) {
             d->viewport->update(dx, 0, dx, d->viewport->height());
         }
     }
 }
scrollTo()
void QTableView::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) virtual
Makes sure that the given item is visible in the table view, scrolling if necessary.
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2662 of file qtableview.cpp.
Referenced by QTableWidget::scrollToItem().
 {
     Q_D(QTableView);
     // check if we really need to do anything
     if (!d->isIndexValid(index)
         || (d->model->parent(index) != d->root)
         || isRowHidden(index.row()) || isColumnHidden(index.column()))
         return;
     QSpanCollection::Span span;
     if (d->hasSpans())
         span = d->span(index.row(), index.column());
     // Adjust horizontal position
     int viewportWidth = d->viewport->width();
     int horizontalOffset = d->horizontalHeader->offset();
     int horizontalPosition = d->horizontalHeader->sectionPosition(index.column());
     int horizontalIndex = d->horizontalHeader->visualIndex(index.column());
     int cellWidth = d->hasSpans()
                     ? d->columnSpanWidth(index.column(), span.width())
                     : d->horizontalHeader->sectionSize(index.column());
     if (horizontalScrollMode() == QAbstractItemView::ScrollPerItem) {
         bool positionAtLeft = (horizontalPosition - horizontalOffset < 0);
         bool positionAtRight = (horizontalPosition - horizontalOffset + cellWidth > viewportWidth);
         if (hint == PositionAtCenter || positionAtRight) {
             int w = (hint == PositionAtCenter ? viewportWidth / 2 : viewportWidth);
             int x = cellWidth;
             while (horizontalIndex > 0) {
                 x += columnWidth(d->horizontalHeader->logicalIndex(horizontalIndex-1));
                 if (x > w)
                     break;
                 --horizontalIndex;
             }
         }
         if (positionAtRight || hint == PositionAtCenter || positionAtLeft) {
             int hiddenSections = 0;
             if (d->horizontalHeader->sectionsHidden()) {
                 for (int s = horizontalIndex - 1; s >= 0; --s) {
                     int column = d->horizontalHeader->logicalIndex(s);
                     if (d->horizontalHeader->isSectionHidden(column))
                         ++hiddenSections;
                 }
             }
             horizontalScrollBar()->setValue(horizontalIndex - hiddenSections);
         }
     } else { // ScrollPerPixel
         if (hint == PositionAtCenter) {
             horizontalScrollBar()->setValue(horizontalPosition - ((viewportWidth - cellWidth) / 2));
         } else {
             if (horizontalPosition - horizontalOffset < 0 || cellWidth > viewportWidth)
                 horizontalScrollBar()->setValue(horizontalPosition);
             else if (horizontalPosition - horizontalOffset + cellWidth > viewportWidth)
                 horizontalScrollBar()->setValue(horizontalPosition - viewportWidth + cellWidth);
         }
     }
     // Adjust vertical position
     int viewportHeight = d->viewport->height();
     int verticalOffset = d->verticalHeader->offset();
     int verticalPosition = d->verticalHeader->sectionPosition(index.row());
     int verticalIndex = d->verticalHeader->visualIndex(index.row());
     int cellHeight = d->hasSpans()
                      ? d->rowSpanHeight(index.row(), span.height())
                      : d->verticalHeader->sectionSize(index.row());
     if (verticalPosition - verticalOffset < 0 || cellHeight > viewportHeight) {
         if (hint == EnsureVisible)
             hint = PositionAtTop;
     } else if (verticalPosition - verticalOffset + cellHeight > viewportHeight) {
         if (hint == EnsureVisible)
             hint = PositionAtBottom;
     }
     if (verticalScrollMode() == QAbstractItemView::ScrollPerItem) {
         if (hint == PositionAtBottom || hint == PositionAtCenter) {
             int h = (hint == PositionAtCenter ? viewportHeight / 2 : viewportHeight);
             int y = cellHeight;
             while (verticalIndex > 0) {
                 int row = d->verticalHeader->logicalIndex(verticalIndex - 1);
                 y += d->verticalHeader->sectionSize(row);
                 if (y > h)
                     break;
                 --verticalIndex;
             }
         }
         if (hint == PositionAtBottom || hint == PositionAtCenter || hint == PositionAtTop) {
             int hiddenSections = 0;
             if (d->verticalHeader->sectionsHidden()) {
                 for (int s = verticalIndex - 1; s >= 0; --s) {
                     int row = d->verticalHeader->logicalIndex(s);
                     if (d->verticalHeader->isSectionHidden(row))
                         ++hiddenSections;
                 }
             }
             verticalScrollBar()->setValue(verticalIndex - hiddenSections);
         }
     } else { // ScrollPerPixel
         if (hint == PositionAtTop) {
             verticalScrollBar()->setValue(verticalPosition);
         } else if (hint == PositionAtBottom) {
             verticalScrollBar()->setValue(verticalPosition - viewportHeight + cellHeight);
         } else if (hint == PositionAtCenter) {
             verticalScrollBar()->setValue(verticalPosition - ((viewportHeight - cellHeight) / 2));
         }
     }
     update(index);
 }
selectColumn
void QTableView::selectColumn (int column) slot
Selects the given column in the table view if the current SelectionMode and SelectionBehavior allows columns to be selected.
See also
selectRow()
Definition at line 2943 of file qtableview.cpp.
Referenced by QTableViewPrivate::_q_selectColumn(), setHorizontalHeader(), and setSortingEnabled().
 {
     Q_D(QTableView);
     d->selectColumn(column, true);
 }
selectedIndexes()
QModelIndexList QTableView::selectedIndexes () const protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2033 of file qtableview.cpp.
Referenced by QTableWidget::dropEvent().
 {
     Q_D(const QTableView);
     QModelIndexList viewSelected;
     QModelIndexList modelSelected;
     if (d->selectionModel)
         modelSelected = d->selectionModel->selectedIndexes();
     for (int i = 0; i < modelSelected.count(); ++i) {
         QModelIndex index = modelSelected.at(i);
         if (!isIndexHidden(index) && index.parent() == d->root)
             viewSelected.append(index);
     }
     return viewSelected;
 }
selectionChanged()
void QTableView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3293 of file qtableview.cpp.
 {
 #ifndef QT_NO_ACCESSIBILITY
     Q_D(QTableView);
     Q_UNUSED(d)
     if (QAccessible::isActive()) {
         // ### does not work properly for selection ranges.
         QModelIndex sel = selected.indexes().value(0);
         if (sel.isValid()) {
 #ifdef Q_WS_X11
             int entry = d->accessibleTable2Index(sel);
             QAccessible::updateAccessibility(this, entry, QAccessible::Selection);
 #else
             int entry = visualIndex(sel);
             if (horizontalHeader())
                 ++entry;
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::Selection);
 #endif
         }
         QModelIndex desel = deselected.indexes().value(0);
         if (desel.isValid()) {
 #ifdef Q_WS_X11
             int entry = d->accessibleTable2Index(desel);
             QAccessible::updateAccessibility(this, entry, QAccessible::SelectionRemove);
 #else
             int entry = visualIndex(sel);
             if (horizontalHeader())
                 ++entry;
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::SelectionRemove);
 #endif
         }
     }
 #endif
     QAbstractItemView::selectionChanged(selected, deselected);
 }
selectRow
void QTableView::selectRow (int row) slot
Selects the given row in the table view if the current SelectionMode and SelectionBehavior allows rows to be selected.
See also
selectColumn()
Definition at line 2931 of file qtableview.cpp.
Referenced by QTableViewPrivate::_q_selectRow(), and setVerticalHeader().
 {
     Q_D(QTableView);
     d->selectRow(row, true);
 }
setColumnHidden()
void QTableView::setColumnHidden (int column, bool hide)
If hide is true the given column will be hidden; otherwise it will be shown.
See also
setRowHidden()
Definition at line 2450 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (column < 0 || column >= d->horizontalHeader->count())
         return;
     d->horizontalHeader->setSectionHidden(column, hide);
 }
setColumnWidth()
void QTableView::setColumnWidth (int column, int width)
Sets the width of the given column to be width.
Since
4.1
Definition at line 2392 of file qtableview.cpp.
 {
     Q_D(const QTableView);
     d->horizontalHeader->resizeSection(column, width);
 }
setCornerButtonEnabled()
void QTableView::setCornerButtonEnabled (bool enable)
Definition at line 2608 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->cornerWidget->setEnabled(enable);
 }
setGridStyle()
void QTableView::setGridStyle (Qt::PenStyle style)
Definition at line 2552 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (d->gridStyle != style) {
         d->gridStyle = style;
         d->viewport->update();
     }
 }
setHorizontalHeader()
void QTableView::setHorizontalHeader (QHeaderView * header)
Sets the widget to use for the horizontal header to header.
See also
horizontalHeader() setVerticalHeader()
Definition at line 1208 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (!header || header == d->horizontalHeader)
         return;
     if (d->horizontalHeader && d->horizontalHeader->parent() == this)
         delete d->horizontalHeader;
     d->horizontalHeader = header;
     d->horizontalHeader->setParent(this);
     if (!d->horizontalHeader->model()) {
         d->horizontalHeader->setModel(d->model);
         if (d->selectionModel)
             d->horizontalHeader->setSelectionModel(d->selectionModel);
     }
     connect(d->horizontalHeader,SIGNAL(sectionResized(int,int,int)),
             this, SLOT(columnResized(int,int,int)));
     connect(d->horizontalHeader, SIGNAL(sectionMoved(int,int,int)),
             this, SLOT(columnMoved(int,int,int)));
     connect(d->horizontalHeader, SIGNAL(sectionCountChanged(int,int)),
             this, SLOT(columnCountChanged(int,int)));
     connect(d->horizontalHeader, SIGNAL(sectionPressed(int)), this, SLOT(selectColumn(int)));
     connect(d->horizontalHeader, SIGNAL(sectionEntered(int)), this, SLOT(_q_selectColumn(int)));
     connect(d->horizontalHeader, SIGNAL(sectionHandleDoubleClicked(int)),
             this, SLOT(resizeColumnToContents(int)));
     connect(d->horizontalHeader, SIGNAL(geometriesChanged()), this, SLOT(updateGeometries()));
     //update the sorting enabled states on the new header
     setSortingEnabled(d->sortingEnabled);
 }
setModel()
void QTableView::setModel (QAbstractItemModel * model) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QTableWidget.
Definition at line 1103 of file qtableview.cpp.
Referenced by QTableWidget::QTableWidget().
 {
     Q_D(QTableView);
     if (model == d->model)
         return;
     //let's disconnect from the old model
     if (d->model && d->model != QAbstractItemModelPrivate::staticEmptyModel()) {
         disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanInsertedRows(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanInsertedColumns(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanRemovedRows(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanRemovedColumns(QModelIndex,int,int)));
     }
     if (model) { //and connect to the new one
         connect(model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanInsertedRows(QModelIndex,int,int)));
         connect(model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanInsertedColumns(QModelIndex,int,int)));
         connect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanRemovedRows(QModelIndex,int,int)));
         connect(model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_updateSpanRemovedColumns(QModelIndex,int,int)));
     }
     d->verticalHeader->setModel(model);
     d->horizontalHeader->setModel(model);
     QAbstractItemView::setModel(model);
 }
setRootIndex()
void QTableView::setRootIndex (const QModelIndex & index) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1137 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (index == d->root) {
         viewport()->update();
         return;
     }
     d->verticalHeader->setRootIndex(index);
     d->horizontalHeader->setRootIndex(index);
     QAbstractItemView::setRootIndex(index);
 }
setRowHeight()
void QTableView::setRowHeight (int row, int height)
Sets the height of the given row to be height.
Since
4.1
Definition at line 2342 of file qtableview.cpp.
 {
     Q_D(const QTableView);
     d->verticalHeader->resizeSection(row, height);
 }
setRowHidden()
void QTableView::setRowHidden (int row, bool hide)
If hide is true row will be hidden, otherwise it will be shown.
See also
setColumnHidden()
Definition at line 2425 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (row < 0 || row >= d->verticalHeader->count())
         return;
     d->verticalHeader->setSectionHidden(row, hide);
 }
setSelection()
void QTableView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags flags) protected virtual
Applies the selection flags to the items in or touched by the rectangle, rect.
When implementing your own itemview setSelection should call selectionModel()->select(selection, flags) where selection is either an empty QModelIndex or a QItemSelection that contains all items that are contained in rect.
See also
selectionCommand(), selectedIndexes()
Implements QAbstractItemView.
Definition at line 1824 of file qtableview.cpp.
 {
     Q_D(QTableView);
     QModelIndex tl = indexAt(QPoint(isRightToLeft() ? qMax(rect.left(), rect.right())
                                     : qMin(rect.left(), rect.right()), qMin(rect.top(), rect.bottom())));
     QModelIndex br = indexAt(QPoint(isRightToLeft() ? qMin(rect.left(), rect.right()) :
                                     qMax(rect.left(), rect.right()), qMax(rect.top(), rect.bottom())));
     if (!d->selectionModel || !tl.isValid() || !br.isValid() || !d->isIndexEnabled(tl) || !d->isIndexEnabled(br))
         return;
     bool verticalMoved = verticalHeader()->sectionsMoved();
     bool horizontalMoved = horizontalHeader()->sectionsMoved();
     QItemSelection selection;
     if (d->hasSpans()) {
         bool expanded;
         int top = qMin(d->visualRow(tl.row()), d->visualRow(br.row()));
         int left = qMin(d->visualColumn(tl.column()), d->visualColumn(br.column()));
         int bottom = qMax(d->visualRow(tl.row()), d->visualRow(br.row()));
         int right = qMax(d->visualColumn(tl.column()), d->visualColumn(br.column()));
         do {
             expanded = false;
             foreach (QSpanCollection::Span *it, d->spans.spans) {
                 const QSpanCollection::Span &span = *it;
                 int t = d->visualRow(span.top());
                 int l = d->visualColumn(span.left());
                 int b = d->visualRow(d->rowSpanEndLogical(span.top(), span.height()));
                 int r = d->visualColumn(d->columnSpanEndLogical(span.left(), span.width()));
                 if ((t > bottom) || (l > right) || (top > b) || (left > r))
                     continue; // no intersect
                 if (t < top) {
                     top = t;
                     expanded = true;
                 }
                 if (l < left) {
                     left = l;
                     expanded = true;
                 }
                 if (b > bottom) {
                     bottom = b;
                     expanded = true;
                 }
                 if (r > right) {
                     right = r;
                     expanded = true;
                 }
                 if (expanded)
                     break;
             }
         } while (expanded);
          for (int horizontal = left; horizontal <= right; ++horizontal) {
              int column = d->logicalColumn(horizontal);
              for (int vertical = top; vertical <= bottom; ++vertical) {
                  int row = d->logicalRow(vertical);
                  QModelIndex index = d->model->index(row, column, d->root);
                  selection.append(QItemSelectionRange(index));
              }
          }
     } else if (verticalMoved && horizontalMoved) {
          int top = d->visualRow(tl.row());
          int left = d->visualColumn(tl.column());
          int bottom = d->visualRow(br.row());
          int right = d->visualColumn(br.column());
          for (int horizontal = left; horizontal <= right; ++horizontal) {
              int column = d->logicalColumn(horizontal);
              for (int vertical = top; vertical <= bottom; ++vertical) {
                  int row = d->logicalRow(vertical);
                  QModelIndex index = d->model->index(row, column, d->root);
                  selection.append(QItemSelectionRange(index));
              }
          }
     } else if (horizontalMoved) {
         int left = d->visualColumn(tl.column());
         int right = d->visualColumn(br.column());
         for (int visual = left; visual <= right; ++visual) {
             int column = d->logicalColumn(visual);
             QModelIndex topLeft = d->model->index(tl.row(), column, d->root);
             QModelIndex bottomRight = d->model->index(br.row(), column, d->root);
             selection.append(QItemSelectionRange(topLeft, bottomRight));
         }
     } else if (verticalMoved) {
         int top = d->visualRow(tl.row());
         int bottom = d->visualRow(br.row());
         for (int visual = top; visual <= bottom; ++visual) {
             int row = d->logicalRow(visual);
             QModelIndex topLeft = d->model->index(row, tl.column(), d->root);
             QModelIndex bottomRight = d->model->index(row, br.column(), d->root);
             selection.append(QItemSelectionRange(topLeft, bottomRight));
         }
     } else { // nothing moved
         QItemSelectionRange range(tl, br);
         if (!range.isEmpty())
             selection.append(range);
     }
     d->selectionModel->select(selection, command);
 }
setSelectionModel()
void QTableView::setSelectionModel (QItemSelectionModel * selectionModel) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1172 of file qtableview.cpp.
 {
     Q_D(QTableView);
     Q_ASSERT(selectionModel);
     d->verticalHeader->setSelectionModel(selectionModel);
     d->horizontalHeader->setSelectionModel(selectionModel);
     QAbstractItemView::setSelectionModel(selectionModel);
 }
setShowGrid
void QTableView::setShowGrid (bool show) slot
Definition at line 2528 of file qtableview.cpp.
Referenced by QCalendarView::QCalendarView().
 {
     Q_D(QTableView);
     if (d->showGrid != show) {
         d->showGrid = show;
         d->viewport->update();
     }
 }
setSortingEnabled()
void QTableView::setSortingEnabled (bool enable)
If enabled true enables sorting for the table and immediately trigger a call to sortByColumn() with the current sort section and order.
Definition at line 2482 of file qtableview.cpp.
Referenced by setHorizontalHeader(), and QTableWidget::setSortingEnabled().
 {
     Q_D(QTableView);
     d->sortingEnabled = enable;
     horizontalHeader()->setSortIndicatorShown(enable);
     if (enable) {
         disconnect(d->horizontalHeader, SIGNAL(sectionEntered(int)),
                    this, SLOT(_q_selectColumn(int)));
         disconnect(horizontalHeader(), SIGNAL(sectionPressed(int)),
                    this, SLOT(selectColumn(int)));
         connect(horizontalHeader(), SIGNAL(sortIndicatorChanged(int,Qt::SortOrder)),
                 this, SLOT(sortByColumn(int)), Qt::UniqueConnection);
         sortByColumn(horizontalHeader()->sortIndicatorSection(),
                      horizontalHeader()->sortIndicatorOrder());
     } else {
         connect(d->horizontalHeader, SIGNAL(sectionEntered(int)),
                 this, SLOT(_q_selectColumn(int)), Qt::UniqueConnection);
         connect(horizontalHeader(), SIGNAL(sectionPressed(int)),
                 this, SLOT(selectColumn(int)), Qt::UniqueConnection);
         disconnect(horizontalHeader(), SIGNAL(sortIndicatorChanged(int,Qt::SortOrder)),
                    this, SLOT(sortByColumn(int)));
     }
 }
setSpan()
void QTableView::setSpan (int row, int column, int rowSpanCount, int columnSpanCount)
Sets the span of the table element at (row, column) to the number of rows and columns specified by (rowSpanCount, columnSpanCount).
Since
4.2
See also
rowSpan(), columnSpan()
Definition at line 3118 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (row < 0 || column < 0 || rowSpan < 0 || columnSpan < 0)
         return;
     d->setSpan(row, column, rowSpan, columnSpan);
     d->viewport->update();
 }
setVerticalHeader()
void QTableView::setVerticalHeader (QHeaderView * header)
Sets the widget to use for the vertical header to header.
See also
verticalHeader() setHorizontalHeader()
Definition at line 1245 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (!header || header == d->verticalHeader)
         return;
     if (d->verticalHeader && d->verticalHeader->parent() == this)
         delete d->verticalHeader;
     d->verticalHeader = header;
     d->verticalHeader->setParent(this);
     if (!d->verticalHeader->model()) {
         d->verticalHeader->setModel(d->model);
         if (d->selectionModel)
             d->verticalHeader->setSelectionModel(d->selectionModel);
     }
     connect(d->verticalHeader, SIGNAL(sectionResized(int,int,int)),
             this, SLOT(rowResized(int,int,int)));
     connect(d->verticalHeader, SIGNAL(sectionMoved(int,int,int)),
             this, SLOT(rowMoved(int,int,int)));
     connect(d->verticalHeader, SIGNAL(sectionCountChanged(int,int)),
             this, SLOT(rowCountChanged(int,int)));
     connect(d->verticalHeader, SIGNAL(sectionPressed(int)), this, SLOT(selectRow(int)));
     connect(d->verticalHeader, SIGNAL(sectionEntered(int)), this, SLOT(_q_selectRow(int)));
     connect(d->verticalHeader, SIGNAL(sectionHandleDoubleClicked(int)),
             this, SLOT(resizeRowToContents(int)));
     connect(d->verticalHeader, SIGNAL(geometriesChanged()), this, SLOT(updateGeometries()));
 }
setWordWrap()
void QTableView::setWordWrap (bool on)
Definition at line 2578 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (d->wrapItemText == on)
         return;
     d->wrapItemText = on;
     QMetaObject::invokeMethod(d->verticalHeader, "resizeSections");
     QMetaObject::invokeMethod(d->horizontalHeader, "resizeSections");
 }
showColumn
void QTableView::showColumn (int column) slot
Show the given column.
See also
hideColumn() showRow()
Definition at line 2987 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->horizontalHeader->showSection(column);
 }
showGrid()
bool QTableView::showGrid () const
Referenced by isSortingEnabled(), paintEvent(), visualRect(), and visualRegionForSelection().
showRow
void QTableView::showRow (int row) slot
Show the given row.
See also
hideRow() showColumn()
Definition at line 2976 of file qtableview.cpp.
 {
     Q_D(QTableView);
     d->verticalHeader->showSection(row);
 }
sizeHintForColumn()
int QTableView::sizeHintForColumn (int column) const protected virtual
Returns the size hint for the given column's width or -1 if there is no model.
If you need to set the width of a given column to a fixed value, call QHeaderView::resizeSection() on the table's horizontal header.
If you reimplement this function in a subclass, note that the value you return will be used when resizeColumnToContents() or QHeaderView::resizeSections() is called. If a larger column width is required by either the horizontal header or the item delegate, the larger width will be used instead.
See also
QWidget::sizeHint, horizontalHeader()
Reimplemented from QAbstractItemView.
Definition at line 2271 of file qtableview.cpp.
Referenced by resizeColumnToContents().
 {
     Q_D(const QTableView);
     if (!model())
         return -1;
     ensurePolished();
     int top = qMax(0, d->verticalHeader->visualIndexAt(0));
     int bottom = d->verticalHeader->visualIndexAt(d->viewport->height());
     if (!isVisible() || bottom == -1) // the table don't have enough rows to fill the viewport
         bottom = d->model->rowCount(d->root) - 1;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     int hint = 0;
     QModelIndex index;
     for (int row = top; row <= bottom; ++row) {
         int logicalRow = d->verticalHeader->logicalIndex(row);
         if (d->verticalHeader->isSectionHidden(logicalRow))
             continue;
         index = d->model->index(logicalRow, column, d->root);
         QWidget *editor = d->editorForIndex(index).widget.data();
         if (editor && d->persistent.contains(editor)) {
             hint = qMax(hint, editor->sizeHint().width());
             int min = editor->minimumSize().width();
             int max = editor->maximumSize().width();
             hint = qBound(min, hint, max);
         }
         hint = qMax(hint, itemDelegate(index)->sizeHint(option, index).width());
     }
     return d->showGrid ? hint + 1 : hint;
 }
sizeHintForRow()
int QTableView::sizeHintForRow (int row) const protected virtual
Returns the size hint for the given row's height or -1 if there is no model.
If you need to set the height of a given row to a fixed value, call QHeaderView::resizeSection() on the table's vertical header.
If you reimplement this function in a subclass, note that the value you return is only used when resizeRowToContents() is called. In that case, if a larger row height is required by either the vertical header or the item delegate, that width will be used instead.
See also
QWidget::sizeHint, verticalHeader()
Reimplemented from QAbstractItemView.
Definition at line 2212 of file qtableview.cpp.
Referenced by resizeRowToContents().
 {
     Q_D(const QTableView);
     if (!model())
         return -1;
     ensurePolished();
     int left = qMax(0, d->horizontalHeader->visualIndexAt(0));
     int right = d->horizontalHeader->visualIndexAt(d->viewport->width());
     if (right == -1) // the table don't have enough columns to fill the viewport
         right = d->model->columnCount(d->root) - 1;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     int hint = 0;
     QModelIndex index;
     for (int column = left; column <= right; ++column) {
         int logicalColumn = d->horizontalHeader->logicalIndex(column);
         if (d->horizontalHeader->isSectionHidden(logicalColumn))
             continue;
         index = d->model->index(row, logicalColumn, d->root);
         if (d->wrapItemText) {// for wrapping boundaries
             option.rect.setY(rowViewportPosition(index.row()));
             option.rect.setHeight(rowHeight(index.row()));
             option.rect.setX(columnViewportPosition(index.column()));
             option.rect.setWidth(columnWidth(index.column()));
         }
         QWidget *editor = d->editorForIndex(index).widget.data();
         if (editor && d->persistent.contains(editor)) {
             hint = qMax(hint, editor->sizeHint().height());
             int min = editor->minimumSize().height();
             int max = editor->maximumSize().height();
             hint = qBound(min, hint, max);
         }
         hint = qMax(hint, itemDelegate(index)->sizeHint(option, index).height());
     }
     return d->showGrid ? hint + 1 : hint;
 }
sortByColumn() [1/2]
void QTableView::sortByColumn (int column, Qt::SortOrder order)
Sorts the model by the values in the given column in the given order.
Since
4.2
See also
sortingEnabled
Definition at line 3067 of file qtableview.cpp.
Referenced by setSortingEnabled().
 {
     Q_D(QTableView);
     d->horizontalHeader->setSortIndicator(column, order);
     sortByColumn(column);
 }
sortByColumn [2/2]
void QTableView::sortByColumn (int column) slot
Sorts the model by the values in the given column.
Definition at line 3049 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (column == -1)
         return;
     d->model->sort(column, d->horizontalHeader->sortIndicatorOrder());
 }
timerEvent()
void QTableView::timerEvent (QTimerEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2815 of file qtableview.cpp.
 {
     Q_D(QTableView);
     if (event->timerId() == d->columnResizeTimerID) {
         updateGeometries();
         killTimer(d->columnResizeTimerID);
         d->columnResizeTimerID = 0;
         QRect rect;
         int viewportHeight = d->viewport->height();
         int viewportWidth = d->viewport->width();
         if (d->hasSpans()) {
             rect = QRect(0, 0, viewportWidth, viewportHeight);
         } else {
             for (int i = d->columnsToUpdate.size()-1; i >= 0; --i) {
                 int column = d->columnsToUpdate.at(i);
                 int x = columnViewportPosition(column);
                 if (isRightToLeft())
                     rect |= QRect(0, 0, x + columnWidth(column), viewportHeight);
                 else
                     rect |= QRect(x, 0, viewportWidth - x, viewportHeight);
             }
         }
         d->viewport->update(rect.normalized());
         d->columnsToUpdate.clear();
     }
     if (event->timerId() == d->rowResizeTimerID) {
         updateGeometries();
         killTimer(d->rowResizeTimerID);
         d->rowResizeTimerID = 0;
         int viewportHeight = d->viewport->height();
         int viewportWidth = d->viewport->width();
         int top;
         if (d->hasSpans()) {
             top = 0;
         } else {
             top = viewportHeight;
             for (int i = d->rowsToUpdate.size()-1; i >= 0; --i) {
                 int y = rowViewportPosition(d->rowsToUpdate.at(i));
                 top = qMin(top, y);
             }
         }
         d->viewport->update(QRect(0, top, viewportWidth, viewportHeight - top));
         d->rowsToUpdate.clear();
     }
     QAbstractItemView::timerEvent(event);
 }
updateGeometries()
void QTableView::updateGeometries () protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2083 of file qtableview.cpp.
Referenced by columnCountChanged(), columnMoved(), rowMoved(), setHorizontalHeader(), setVerticalHeader(), and timerEvent().
 {
     Q_D(QTableView);
     if (d->geometryRecursionBlock)
         return;
     d->geometryRecursionBlock = true;
     int width = 0;
     if (!d->verticalHeader->isHidden()) {
         width = qMax(d->verticalHeader->minimumWidth(), d->verticalHeader->sizeHint().width());
         width = qMin(width, d->verticalHeader->maximumWidth());
     }
     int height = 0;
     if (!d->horizontalHeader->isHidden()) {
         height = qMax(d->horizontalHeader->minimumHeight(), d->horizontalHeader->sizeHint().height());
         height = qMin(height, d->horizontalHeader->maximumHeight());
     }
     bool reverse = isRightToLeft();
      if (reverse)
          setViewportMargins(0, height, width, 0);
      else
          setViewportMargins(width, height, 0, 0);
     // update headers
     QRect vg = d->viewport->geometry();
     int verticalLeft = reverse ? vg.right() + 1 : (vg.left() - width);
     d->verticalHeader->setGeometry(verticalLeft, vg.top(), width, vg.height());
     if (d->verticalHeader->isHidden())
         QMetaObject::invokeMethod(d->verticalHeader, "updateGeometries");
     int horizontalTop = vg.top() - height;
     d->horizontalHeader->setGeometry(vg.left(), horizontalTop, vg.width(), height);
     if (d->horizontalHeader->isHidden())
         QMetaObject::invokeMethod(d->horizontalHeader, "updateGeometries");
     // update cornerWidget
     if (d->horizontalHeader->isHidden() || d->verticalHeader->isHidden()) {
         d->cornerWidget->setHidden(true);
     } else {
         d->cornerWidget->setHidden(false);
         d->cornerWidget->setGeometry(verticalLeft, horizontalTop, width, height);
     }
     // update scroll bars
     // ### move this block into the if
     QSize vsize = d->viewport->size();
     QSize max = maximumViewportSize();
     uint horizontalLength = d->horizontalHeader->length();
     uint verticalLength = d->verticalHeader->length();
     if ((uint)max.width() >= horizontalLength && (uint)max.height() >= verticalLength)
         vsize = max;
     // horizontal scroll bar
     const int columnCount = d->horizontalHeader->count();
     const int viewportWidth = vsize.width();
     int columnsInViewport = 0;
     for (int width = 0, column = columnCount - 1; column >= 0; --column) {
         int logical = d->horizontalHeader->logicalIndex(column);
         if (!d->horizontalHeader->isSectionHidden(logical)) {
             width += d->horizontalHeader->sectionSize(logical);
             if (width > viewportWidth)
                 break;
             ++columnsInViewport;
         }
     }
     columnsInViewport = qMax(columnsInViewport, 1); //there must be always at least 1 column
     if (horizontalScrollMode() == QAbstractItemView::ScrollPerItem) {
         const int visibleColumns = columnCount - d->horizontalHeader->hiddenSectionCount();
         horizontalScrollBar()->setRange(0, visibleColumns - columnsInViewport);
         horizontalScrollBar()->setPageStep(columnsInViewport);
         if (columnsInViewport >= visibleColumns)
             d->horizontalHeader->setOffset(0);
         horizontalScrollBar()->setSingleStep(1);
     } else { // ScrollPerPixel
         horizontalScrollBar()->setPageStep(vsize.width());
         horizontalScrollBar()->setRange(0, horizontalLength - vsize.width());
         horizontalScrollBar()->setSingleStep(qMax(vsize.width() / (columnsInViewport + 1), 2));
     }
     // vertical scroll bar
     const int rowCount = d->verticalHeader->count();
     const int viewportHeight = vsize.height();
     int rowsInViewport = 0;
     for (int height = 0, row = rowCount - 1; row >= 0; --row) {
         int logical = d->verticalHeader->logicalIndex(row);
         if (!d->verticalHeader->isSectionHidden(logical)) {
             height += d->verticalHeader->sectionSize(logical);
             if (height > viewportHeight)
                 break;
             ++rowsInViewport;
         }
     }
     rowsInViewport = qMax(rowsInViewport, 1); //there must be always at least 1 row
     if (verticalScrollMode() == QAbstractItemView::ScrollPerItem) {
         const int visibleRows = rowCount - d->verticalHeader->hiddenSectionCount();
         verticalScrollBar()->setRange(0, visibleRows - rowsInViewport);
         verticalScrollBar()->setPageStep(rowsInViewport);
         if (rowsInViewport >= visibleRows)
             d->verticalHeader->setOffset(0);
         verticalScrollBar()->setSingleStep(1);
     } else { // ScrollPerPixel
         verticalScrollBar()->setPageStep(vsize.height());
         verticalScrollBar()->setRange(0, verticalLength - vsize.height());
         verticalScrollBar()->setSingleStep(qMax(vsize.height() / (rowsInViewport + 1), 2));
     }
     d->geometryRecursionBlock = false;
     QAbstractItemView::updateGeometries();
 }
verticalHeader()
QHeaderView * QTableView::verticalHeader () const
Returns the table view's vertical header.
See also
setVerticalHeader(), horizontalHeader(), QAbstractItemModel::headerData()
Definition at line 1197 of file qtableview.cpp.
Referenced by paintEvent(), QCalendarView::QCalendarView(), QTableViewPrivate::selectColumn(), QTableViewPrivate::selectRow(), setSelection(), visualRegionForSelection(), and QTableWidget::visualRow().
 {
     Q_D(const QTableView);
     return d->verticalHeader;
 }
verticalOffset()
int QTableView::verticalOffset () const protected virtual
Returns the vertical offset of the items in the table view.
Note that the table view uses the vertical header section positions to determine the positions of rows in the view.
See also
horizontalOffset()
Implements QAbstractItemView.
Definition at line 1560 of file qtableview.cpp.
Referenced by paintEvent(), and scrollTo().
 {
     Q_D(const QTableView);
     return d->verticalHeader->offset();
 }
verticalScrollbarAction()
void QTableView::verticalScrollbarAction (int action) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 3077 of file qtableview.cpp.
 {
     QAbstractItemView::verticalScrollbarAction(action);
 }
viewOptions()
QStyleOptionViewItem QTableView::viewOptions () const protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1333 of file qtableview.cpp.
 {
     QStyleOptionViewItem option = QAbstractItemView::viewOptions();
     option.showDecorationSelected = true;
     return option;
 }
visualIndex()
int QTableView::visualIndex (const QModelIndex & index) const private
Definition at line 3330 of file qtableview.cpp.
Referenced by currentChanged(), paintEvent(), and selectionChanged().
 {
     return index.row();
 }
visualRect()
QRect QTableView::visualRect (const QModelIndex & index) const virtual
Returns the rectangle on the viewport occupied by the given index.
Warning
This function is not part of the public interface.
If the index is hidden in the view it will return a null QRect.
Implements QAbstractItemView.
Definition at line 2630 of file qtableview.cpp.
Referenced by moveCursor(), QTableWidget::visualItemRect(), and visualRegionForSelection().
 {
     Q_D(const QTableView);
     if (!d->isIndexValid(index) || index.parent() != d->root
         || (!d->hasSpans() && isIndexHidden(index)))
         return QRect();
     d->executePostedLayout();
     if (d->hasSpans()) {
         QSpanCollection::Span span = d->span(index.row(), index.column());
         return d->visualSpanRect(span);
     }
     int rowp = rowViewportPosition(index.row());
     int rowh = rowHeight(index.row());
     int colp = columnViewportPosition(index.column());
     int colw = columnWidth(index.column());
     const int i = showGrid() ? 1 : 0;
     return QRect(colp, rowp, colw - i, rowh - i);
 }
visualRegionForSelection()
QRegion QTableView::visualRegionForSelection (const QItemSelection & selection) const protected virtual
Returns the rectangle from the viewport of the items in the given selection.
Warning
This function is not part of the public interface.
Since 4.7, the returned region only contains rectangles intersecting (or included in) the viewport.
Implements QAbstractItemView.
Definition at line 1935 of file qtableview.cpp.
 {
     Q_D(const QTableView);
     if (selection.isEmpty())
         return QRegion();
     QRegion selectionRegion;
     const QRect &viewportRect = d->viewport->rect();
     bool verticalMoved = verticalHeader()->sectionsMoved();
     bool horizontalMoved = horizontalHeader()->sectionsMoved();
     if ((verticalMoved && horizontalMoved) || (d->hasSpans() && (verticalMoved || horizontalMoved))) {
         for (int i = 0; i < selection.count(); ++i) {
             QItemSelectionRange range = selection.at(i);
             if (range.parent() != d->root || !range.isValid())
                 continue;
             for (int r = range.top(); r <= range.bottom(); ++r)
                 for (int c = range.left(); c <= range.right(); ++c) {
                     const QRect &rangeRect = visualRect(d->model->index(r, c, d->root));
                     if (viewportRect.intersects(rangeRect))
                         selectionRegion += rangeRect;
                 }
         }
     } else if (horizontalMoved) {
         for (int i = 0; i < selection.count(); ++i) {
             QItemSelectionRange range = selection.at(i);
             if (range.parent() != d->root || !range.isValid())
                 continue;
             int top = rowViewportPosition(range.top());
             int bottom = rowViewportPosition(range.bottom()) + rowHeight(range.bottom());
             if (top > bottom)
                 qSwap<int>(top, bottom);
             int height = bottom - top;
             for (int c = range.left(); c <= range.right(); ++c) {
                 const QRect rangeRect(columnViewportPosition(c), top, columnWidth(c), height);
                 if (viewportRect.intersects(rangeRect))
                     selectionRegion += rangeRect;
             }
         }
     } else if (verticalMoved) {
         for (int i = 0; i < selection.count(); ++i) {
             QItemSelectionRange range = selection.at(i);
             if (range.parent() != d->root || !range.isValid())
                 continue;
             int left = columnViewportPosition(range.left());
             int right = columnViewportPosition(range.right()) + columnWidth(range.right());
             if (left > right)
                 qSwap<int>(left, right);
             int width = right - left;
             for (int r = range.top(); r <= range.bottom(); ++r) {
                 const QRect rangeRect(left, rowViewportPosition(r), width, rowHeight(r));
                 if (viewportRect.intersects(rangeRect))
                     selectionRegion += rangeRect;
             }
         }
     } else { // nothing moved
         const int gridAdjust = showGrid() ? 1 : 0;
         for (int i = 0; i < selection.count(); ++i) {
             QItemSelectionRange range = selection.at(i);
             if (range.parent() != d->root || !range.isValid())
                 continue;
             d->trimHiddenSelections(&range);
             const int rtop = rowViewportPosition(range.top());
             const int rbottom = rowViewportPosition(range.bottom()) + rowHeight(range.bottom());
             int rleft;
             int rright;
             if (isLeftToRight()) {
                 rleft = columnViewportPosition(range.left());
                 rright = columnViewportPosition(range.right()) + columnWidth(range.right());
             } else {
                 rleft = columnViewportPosition(range.right());
                 rright = columnViewportPosition(range.left()) + columnWidth(range.left());
             }
             const QRect rangeRect(QPoint(rleft, rtop), QPoint(rright - 1 - gridAdjust, rbottom - 1 - gridAdjust));
             if (viewportRect.intersects(rangeRect))
                 selectionRegion += rangeRect;
             if (d->hasSpans()) {
                 foreach (QSpanCollection::Span *s,
                          d->spans.spansInRect(range.left(), range.top(), range.width(), range.height())) {
                     if (range.contains(s->top(), s->left(), range.parent())) {
                         const QRect &visualSpanRect = d->visualSpanRect(*s);
                         if (viewportRect.intersects(visualSpanRect))
                             selectionRegion += visualSpanRect;
                     }
                 }
             }
         }
     }
     return selectionRegion;
 }
wordWrap()
bool QTableView::wordWrap () const
Referenced by setWordWrap().
Friends and Related Functions
QAccessibleItemView
friend class QAccessibleItemView friend
Definition at line 179 of file qtableview.h.
Properties
cornerButtonEnabled
QTableView::cornerButtonEnabled private
whether the button in the top-left corner is enabled
Since
4.3
If this property is true then button in the top-left corner of the table view is enabled. Clicking on this button will select all the cells in the table view.
This property is true by default.
Definition at line 65 of file qtableview.h.
gridStyle
Qt::PenStyle QTableView::gridStyle private
the pen style used to draw the grid.
This property holds the style used when drawing the grid (see showGrid).
Definition at line 62 of file qtableview.h.
showGrid
bool QTableView::showGrid private
whether the grid is shown
If this property is true a grid is drawn for the table; if the property is false, no grid is drawn. The default value is true.
Definition at line 61 of file qtableview.h.
Referenced by QComboBoxPrivateContainer::spacing().
sortingEnabled
QTableView::sortingEnabled private
whether sorting is enabled
Since
4.2
If this property is true, sorting is enabled for the table. If this property is false, sorting is not enabled. The default value is false.
Note
. Setting the property to true with setSortingEnabled() immediately triggers a call to sortByColumn() with the current sort section and order.
See also
sortByColumn()
Definition at line 63 of file qtableview.h.
wordWrap
bool QTableView::wordWrap private
the item text word-wrapping policy
Since
4.3
If this property is true then the item text is wrapped where necessary at word-breaks; otherwise it is not wrapped at all. This property is true by default.
Note that even of wrapping is enabled, the cell will not be expanded to fit all text. Ellipsis will be inserted according to the current QAbstractItemView::textElideMode.
Definition at line 64 of file qtableview.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtableview.h
/src/gui/itemviews/qtableview.cpp