Qt 4.8: QTableModel Class Reference
QTableModel Class Reference
#include <qtablewidget_p.h>
Public Types
enum ItemFlagsExtension { ItemIsHeaderItem = 128 }
Public Functions
void clear ()
void clearContents ()
int columnCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of columns for the children of the given parent.
QVector< QTableWidgetItem * > columnItems (int column) const
QTableWidgetItem * createItem () const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns the data stored under the given role for the item referred to by the index.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
void ensureSorted (int column, Qt::SortOrder order, int start, int end)
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
QVariant headerData (int section, Qt::Orientation orientation, int role) const
Returns the data for the given role and section in the header with the specified orientation.
QTableWidgetItem * horizontalHeaderItem (int section)
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
QModelIndex index (const QTableWidgetItem *item) const
bool insertColumns (int column, int count=1, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRows (int row, int count=1, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
QMimeData * internalMimeData () const
bool isValid (const QModelIndex &index) const
QTableWidgetItem * item (int row, int column) const
QTableWidgetItem * item (const QModelIndex &index) const
void itemChanged (QTableWidgetItem *item)
QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
const QTableWidgetItem * itemPrototype () const
QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QTableModel (int rows, int columns, QTableWidget *parent)
bool removeColumns (int column, int count=1, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
void removeItem (QTableWidgetItem *item)
bool removeRows (int row, int count=1, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows under the given parent.
void setColumnCount (int columns)
bool setData (const QModelIndex &index, const QVariant &value, int role)
Sets the role data for the item at index to value.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
void setHorizontalHeaderItem (int section, QTableWidgetItem *item)
void setItem (int row, int column, QTableWidgetItem *item)
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setItemPrototype (const QTableWidgetItem *item)
void setRowCount (int rows)
void setVerticalHeaderItem (int section, QTableWidgetItem *item)
void sort (int column, Qt::SortOrder order)
Sorts the model by column in the given order.
Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
long tableIndex (int row, int column) const
QTableWidgetItem * takeHorizontalHeaderItem (int section)
QTableWidgetItem * takeItem (int row, int column)
QTableWidgetItem * takeVerticalHeaderItem (int section)
void updateRowIndexes (QModelIndexList &indexes, int movedFromRow, int movedToRow)
QTableWidgetItem * verticalHeaderItem (int section)
~QTableModel ()
Public Functions inherited from QAbstractTableModel
QAbstractTableModel (QObject *parent=0)
Constructs an abstract table model for the given parent.
~QAbstractTableModel ()
Destroys the abstract table model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool itemGreaterThan (const QPair< QTableWidgetItem *, int > &left, const QPair< QTableWidgetItem *, int > &right)
static bool itemLessThan (const QPair< QTableWidgetItem *, int > &left, const QPair< QTableWidgetItem *, int > &right)
static QVector< QTableWidgetItem * >::iterator sortedInsertionIterator (const QVector< QTableWidgetItem *>::iterator &begin, const QVector< QTableWidgetItem *>::iterator &end, Qt::SortOrder order, QTableWidgetItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
QModelIndexList cachedIndexes
QVector< QTableWidgetItem * > horizontalHeaderItems
const QTableWidgetItem * prototype
QVector< QTableWidgetItem * > tableItems
QVector< QTableWidgetItem * > verticalHeaderItems
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractTableModel
QAbstractTableModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract table model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 90 of file qtablewidget_p.h.
Enumerations
ItemFlagsExtension
enum QTableModel::ItemFlagsExtension
Enumerator
ItemIsHeaderItem
Definition at line 94 of file qtablewidget_p.h.
{
         ItemIsHeaderItem = 128
     }; // we need this to separate header items from other items
Constructors and Destructors
QTableModel()
QTableModel::QTableModel (int rows, int columns, QTableWidget * parent)
Definition at line 51 of file qtablewidget.cpp.
     : QAbstractTableModel(parent),
       prototype(0),
       tableItems(rows * columns, 0),
       verticalHeaderItems(rows, 0),
       horizontalHeaderItems(columns, 0)
 {}
~QTableModel()
QTableModel::~QTableModel ()
Definition at line 59 of file qtablewidget.cpp.
 {
     clear();
     delete prototype;
 }
Functions
clear()
void QTableModel::clear ()
Definition at line 737 of file qtablewidget.cpp.
Referenced by ~QTableModel().
 {
     for (int j = 0; j < verticalHeaderItems.count(); ++j) {
         if (verticalHeaderItems.at(j)) {
             verticalHeaderItems.at(j)->view = 0;
             delete verticalHeaderItems.at(j);
             verticalHeaderItems[j] = 0;
         }
     }
     for (int k = 0; k < horizontalHeaderItems.count(); ++k) {
         if (horizontalHeaderItems.at(k)) {
             horizontalHeaderItems.at(k)->view = 0;
             delete horizontalHeaderItems.at(k);
             horizontalHeaderItems[k] = 0;
         }
     }
     clearContents();
 }
clearContents()
void QTableModel::clearContents ()
Definition at line 756 of file qtablewidget.cpp.
Referenced by clear().
 {
     for (int i = 0; i < tableItems.count(); ++i) {
         if (tableItems.at(i)) {
             tableItems.at(i)->view = 0;
             delete tableItems.at(i);
             tableItems[i] = 0;
         }
     }
     reset();
 }
columnCount()
int QTableModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of columns for the children of the given parent.
In most subclasses, the number of columns is independent of the parent.
For example:
int DomModel::columnCount(const QModelIndex &/*parent*/) const
{
    return 3;
}
Note
When implementing a table based model, columnCount() should return 0 when the parent is valid.
See also
rowCount()
Implements QAbstractItemModel.
Definition at line 397 of file qtablewidget.cpp.
Referenced by ensureSorted(), index(), removeRows(), QTableWidget::setHorizontalHeaderLabels(), setItem(), and sort().
 {
     return parent.isValid() ? 0 : horizontalHeaderItems.count();
 }
columnItems()
QVector< QTableWidgetItem * > QTableModel::columnItems (int column) const
Definition at line 619 of file qtablewidget.cpp.
Referenced by ensureSorted(), and setItem().
 {
     QVector<QTableWidgetItem*> items;
     int rc = rowCount();
     items.reserve(rc);
     for (int row = 0; row < rc; ++row) {
         QTableWidgetItem *itm = item(row, column);
         if (itm == 0) {
             // no more sortable items (all 0-items are
             // at the end of the table when it is sorted)
             break;
         }
         items.append(itm);
     }
     return items;
 }
createItem()
QTableWidgetItem * QTableModel::createItem () const
Definition at line 788 of file qtablewidget.cpp.
Referenced by setData(), QTableWidget::setHorizontalHeaderLabels(), setItemData(), and QTableWidget::setVerticalHeaderLabels().
 {
     return prototype ? prototype->clone() : new QTableWidgetItem;
 }
data()
QVariant QTableModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Returns the data stored under the given role for the item referred to by the index.
Note
If you do not have a value to return, return an invalid QVariant instead of returning 0.
See also
Qt::ItemDataRole, setData(), headerData()
Implements QAbstractItemModel.
Definition at line 402 of file qtablewidget.cpp.
 {
     QTableWidgetItem *itm = item(index);
     if (itm)
         return itm->data(role);
     return QVariant();
 }
dropMimeData()
bool QTableModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractTableModel.
Definition at line 832 of file qtablewidget.cpp.
 {
     if (index.isValid()) {
         row = index.row();
         column = index.column();
     }else if (row == -1 || column == -1) {  // The user dropped outside the table.
         row = rowCount();
         column = 0;
     }
     QTableWidget *view = qobject_cast<QTableWidget*>(QObject::parent());
     return (view ? view->dropMimeData(row, column, data, action) : false);
 }
ensureSorted()
void QTableModel::ensureSorted (int column, Qt::SortOrder order, int start, int end)
Definition at line 542 of file qtablewidget.cpp.
 {
     int count = end - start + 1;
     QVector < QPair<QTableWidgetItem*,int> > sorting;
     sorting.reserve(count);
     for (int row = start; row <= end; ++row) {
         QTableWidgetItem *itm = item(row, column);
         if (itm == 0) {
             // no more sortable items (all 0-items are
             // at the end of the table when it is sorted)
             break;
         }
         sorting.append(QPair<QTableWidgetItem*,int>(itm, row));
     }
     LessThan compare = (order == Qt::AscendingOrder ? &itemLessThan : &itemGreaterThan);
     qStableSort(sorting.begin(), sorting.end(), compare);
     QModelIndexList oldPersistentIndexes = persistentIndexList();
     QModelIndexList newPersistentIndexes = oldPersistentIndexes;
     QVector<QTableWidgetItem*> newTable = tableItems;
     QVector<QTableWidgetItem*> newVertical = verticalHeaderItems;
     QVector<QTableWidgetItem*> colItems = columnItems(column);
     QVector<QTableWidgetItem*>::iterator vit = colItems.begin();
     bool changed = false;
     for (int i = 0; i < sorting.count(); ++i) {
         int oldRow = sorting.at(i).second;
         QTableWidgetItem *item = colItems.at(oldRow);
         colItems.remove(oldRow);
         vit = sortedInsertionIterator(vit, colItems.end(), order, item);
         int newRow = qMax((int)(vit - colItems.begin()), 0);
         if ((newRow < oldRow) && !(*item < *colItems.at(oldRow - 1)) && !(*colItems.at(oldRow - 1) < *item))
             newRow = oldRow;
         vit = colItems.insert(vit, item);
         if (newRow != oldRow) {
             changed = true;
             // move the items @ oldRow to newRow
             int cc = columnCount();
             QVector<QTableWidgetItem*> rowItems(cc);
             for (int j = 0; j < cc; ++j)
                 rowItems[j] = newTable.at(tableIndex(oldRow, j));
             newTable.remove(tableIndex(oldRow, 0), cc);
             newTable.insert(tableIndex(newRow, 0), cc, 0);
             for (int j = 0; j < cc; ++j)
                 newTable[tableIndex(newRow, j)] = rowItems.at(j);
             QTableWidgetItem *header = newVertical.at(oldRow);
             newVertical.remove(oldRow);
             newVertical.insert(newRow, header);
             // update persistent indexes
             updateRowIndexes(newPersistentIndexes, oldRow, newRow);
             // the index of the remaining rows may have changed
             for (int j = i + 1; j < sorting.count(); ++j) {
                 int otherRow = sorting.at(j).second;
                 if (oldRow < otherRow && newRow >= otherRow)
                     --sorting[j].second;
                 else if (oldRow > otherRow && newRow <= otherRow)
                     ++sorting[j].second;
             }
         }
     }
     if (changed) {
         emit layoutAboutToBeChanged();
         tableItems = newTable;
         verticalHeaderItems = newVertical;
         changePersistentIndexList(oldPersistentIndexes,
                                   newPersistentIndexes);
         emit layoutChanged();
     }
 }
flags()
Qt::ItemFlags QTableModel::flags (const QModelIndex & index) const virtual
Returns the item flags for the given index.
The base class implementation returns a combination of flags that enables the item (ItemIsEnabled) and allows it to be selected (ItemIsSelectable).
See also
Qt::ItemFlags
Reimplemented from QAbstractItemModel.
Definition at line 481 of file qtablewidget.cpp.
Referenced by QTableWidgetItem::flags().
 {
     if (!index.isValid())
         return Qt::ItemIsDropEnabled;
     if (QTableWidgetItem *itm = item(index))
         return itm->flags();
     return (Qt::ItemIsEditable
             |Qt::ItemIsSelectable
             |Qt::ItemIsUserCheckable
             |Qt::ItemIsEnabled
             |Qt::ItemIsDragEnabled
             |Qt::ItemIsDropEnabled);
 }
headerData()
QVariant QTableModel::headerData (int section, Qt::Orientation orientation, int role) const virtual
Returns the data for the given role and section in the header with the specified orientation.
For horizontal headers, the section number corresponds to the column number. Similarly, for vertical headers, the section number corresponds to the row number.
See also
Qt::ItemDataRole, setHeaderData(), QHeaderView
Reimplemented from QAbstractItemModel.
Definition at line 690 of file qtablewidget.cpp.
 {
     if (section < 0)
         return QVariant();
     QTableWidgetItem *itm = 0;
     if (orientation == Qt::Horizontal && section < horizontalHeaderItems.count())
         itm = horizontalHeaderItems.at(section);
     else if (orientation == Qt::Vertical && section < verticalHeaderItems.count())
         itm = verticalHeaderItems.at(section);
     else
         return QVariant(); // section is out of bounds
     if (itm)
         return itm->data(role);
     if (role == Qt::DisplayRole)
         return section + 1;
     return QVariant();
 }
horizontalHeaderItem()
QTableWidgetItem * QTableModel::horizontalHeaderItem (int section)
Definition at line 342 of file qtablewidget.cpp.
Referenced by QTableWidget::setHorizontalHeaderLabels().
 {
     return horizontalHeaderItems.value(section);
 }
index() [1/2]
QModelIndex QTableModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const inline virtual
Returns the index of the data in row and column with parent.
See also
parent()
Reimplemented from QAbstractTableModel.
Definition at line 120 of file qtablewidget_p.h.
Referenced by itemChanged(), removeItem(), takeItem(), and updateRowIndexes().
         { return QAbstractTableModel::index(row, column, parent); }
index() [2/2]
QModelIndex QTableModel::index (const QTableWidgetItem * item) const
Definition at line 352 of file qtablewidget.cpp.
 {
     if (!item)
         return QModelIndex();
     int i = -1;
     const int id = item->d->id;
     if (id >= 0 && id < tableItems.count() && tableItems.at(id) == item) {
         i = id;
     } else { // we need to search for the item
         i = tableItems.indexOf(const_cast<QTableWidgetItem*>(item));
         if (i == -1) // not found
             return QModelIndex();
     }
     int row = i / columnCount();
     int col = i % columnCount();
     return QAbstractTableModel::index(row, col);
 }
insertColumns()
bool QTableModel::insertColumns (int column, int count = 1, const QModelIndex & parent = QModelIndex()) virtual
On models that support this, inserts count new columns into the model before the given column.
The items in each new column will be children of the item represented by the parent model index.
If column is 0, the columns are prepended to any existing columns.
If column is columnCount(), the columns are appended to any existing columns.
If parent has no children, a single row with count columns is inserted.
Returns true if the columns were successfully inserted; otherwise returns false.
The base class implementation does nothing and returns false.
If you implement your own model, you can reimplement this function if you want to support insertions. Alternatively, you can provide your own API for altering the data.
See also
insertRows(), removeColumns(), beginInsertColumns(), endInsertColumns()
Reimplemented from QAbstractItemModel.
Definition at line 82 of file qtablewidget.cpp.
Referenced by setColumnCount().
 {
     if (count < 1 || column < 0 || column > horizontalHeaderItems.count())
         return false;
     beginInsertColumns(QModelIndex(), column, column + count - 1);
     int rc = verticalHeaderItems.count();
     int cc = horizontalHeaderItems.count();
     horizontalHeaderItems.insert(column, count, 0);
     if (cc == 0)
         tableItems.resize(rc * count);
     else
         for (int row = 0; row < rc; ++row)
             tableItems.insert(tableIndex(row, column), count, 0);
     endInsertColumns();
     return true;
 }
insertRows()
bool QTableModel::insertRows (int row, int count = 1, const QModelIndex & parent = QModelIndex()) virtual
On models that support this, inserts count rows into the model before the given row.
Note
The base class implementation of this function does nothing and returns false.
Items in the new row will be children of the item represented by the parent model index.
If row is 0, the rows are prepended to any existing rows in the parent.
If row is rowCount(), the rows are appended to any existing rows in the parent.
If parent has no children, a single column with count rows is inserted.
Returns true if the rows were successfully inserted; otherwise returns false.
If you implement your own model, you can reimplement this function if you want to support insertions. Alternatively, you can provide your own API for altering the data. In either case, you will need to call beginInsertRows() and endInsertRows() to notify other components that the model has changed.
See also
insertColumns(), removeRows(), beginInsertRows(), endInsertRows()
Reimplemented from QAbstractItemModel.
Definition at line 65 of file qtablewidget.cpp.
Referenced by setRowCount().
 {
     if (count < 1 || row < 0 || row > verticalHeaderItems.count())
         return false;
     beginInsertRows(QModelIndex(), row, row + count - 1);
     int rc = verticalHeaderItems.count();
     int cc = horizontalHeaderItems.count();
     verticalHeaderItems.insert(row, count, 0);
     if (rc == 0)
         tableItems.resize(cc * count);
     else
         tableItems.insert(tableIndex(row, 0), cc * count, 0);
     endInsertRows();
     return true;
 }
internalMimeData()
QMimeData * QTableModel::internalMimeData () const
Definition at line 812 of file qtablewidget.cpp.
 {
     return QAbstractTableModel::mimeData(cachedIndexes);
 }
isValid()
bool QTableModel::isValid (const QModelIndex & index) const
Definition at line 730 of file qtablewidget.cpp.
Referenced by item().
 {
     return (index.isValid()
             && index.row() < verticalHeaderItems.count()
             && index.column() < horizontalHeaderItems.count());
 }
item() [1/2]
QTableWidgetItem * QTableModel::item (int row, int column) const
Definition at line 235 of file qtablewidget.cpp.
Referenced by columnItems(), data(), ensureSorted(), flags(), index(), itemData(), mimeData(), setData(), QTableWidgetItem::setFont(), setHorizontalHeaderItem(), setItem(), setItemData(), setItemPrototype(), setVerticalHeaderItem(), and sort().
 {
     return tableItems.value(tableIndex(row, column));
 }
item() [2/2]
QTableWidgetItem * QTableModel::item (const QModelIndex & index) const
Definition at line 240 of file qtablewidget.cpp.
 {
     if (!isValid(index))
         return 0;
     return tableItems.at(tableIndex(index.row(), index.column()));
 }
itemChanged()
void QTableModel::itemChanged (QTableWidgetItem * item)
Definition at line 768 of file qtablewidget.cpp.
Referenced by setItemData().
 {
     if (!item)
         return;
     if (item->flags() & ItemIsHeaderItem) {
         int row = verticalHeaderItems.indexOf(item);
         if (row >= 0) {
             emit headerDataChanged(Qt::Vertical, row, row);
         } else {
             int column = horizontalHeaderItems.indexOf(item);
             if (column >= 0)
                 emit headerDataChanged(Qt::Horizontal, column, column);
         }
     } else {
         QModelIndex idx = index(item);
         if (idx.isValid())
             emit dataChanged(idx, idx);
     }
 }
itemData()
QMap< int, QVariant > QTableModel::itemData (const QModelIndex & index) const virtual
Returns a map with values for all predefined roles in the model for the item at the given index.
Reimplement this function if you want to extend the default behavior of this function to include custom roles in the map.
See also
Qt::ItemDataRole, data()
Reimplemented from QAbstractItemModel.
Definition at line 435 of file qtablewidget.cpp.
 {
     QMap<int, QVariant> roles;
     QTableWidgetItem *itm = item(index);
     if (itm) {
         for (int i = 0; i < itm->values.count(); ++i) {
             roles.insert(itm->values.at(i).role,
                          itm->values.at(i).value);
         }
     }
     return roles;
 }
itemGreaterThan()
bool QTableModel::itemGreaterThan (const QPair< QTableWidgetItem *, int > & left, const QPair< QTableWidgetItem *, int > & right) static
Definition at line 684 of file qtablewidget.cpp.
Referenced by ensureSorted(), and sort().
 {
     return (*(right.first) < *(left .first));
 }
itemLessThan()
bool QTableModel::itemLessThan (const QPair< QTableWidgetItem *, int > & left, const QPair< QTableWidgetItem *, int > & right) static
Definition at line 678 of file qtablewidget.cpp.
Referenced by ensureSorted(), and sort().
 {
     return *(left.first) < *(right.first);
 }
itemPrototype()
const QTableWidgetItem * QTableModel::itemPrototype () const
Definition at line 793 of file qtablewidget.cpp.
 {
     return prototype;
 }
mimeData()
QMimeData * QTableModel::mimeData (const QModelIndexList & indexes) const virtual
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
The formats used to describe the encoded data is obtained from the mimeTypes() function.
If the list of indexes is empty, or there are no supported MIME types, 0 is returned rather than a serialized empty list.
See also
mimeTypes(), dropMimeData()
Reimplemented from QAbstractItemModel.
Definition at line 817 of file qtablewidget.cpp.
 {
     QList<QTableWidgetItem*> items;
     for (int i = 0; i < indexes.count(); ++i)
         items << item(indexes.at(i));
     const QTableWidget *view = qobject_cast<const QTableWidget*>(QObject::parent());
     // cachedIndexes is a little hack to avoid copying from QModelIndexList to
     // QList<QTreeWidgetItem*> and back again in the view
     cachedIndexes = indexes;
     QMimeData *mimeData = (view ? view->mimeData(items) : 0);
     cachedIndexes.clear();
     return mimeData;
 }
mimeTypes()
QStringList QTableModel::mimeTypes () const virtual
Returns a list of MIME types that can be used to describe a list of model indexes.
See also
mimeData()
Reimplemented from QAbstractItemModel.
Definition at line 806 of file qtablewidget.cpp.
 {
     const QTableWidget *view = qobject_cast<const QTableWidget*>(QObject::parent());
     return (view ? view->mimeTypes() : QStringList());
 }
removeColumns()
bool QTableModel::removeColumns (int column, int count = 1, const QModelIndex & parent = QModelIndex()) virtual
On models that support this, removes count columns starting with the given column under parent parent from the model.
Returns true if the columns were successfully removed; otherwise returns false.
The base class implementation does nothing and returns false.
If you implement your own model, you can reimplement this function if you want to support removing. Alternatively, you can provide your own API for altering the data.
See also
removeColumn(), removeRows(), insertColumns(), beginRemoveColumns(), endRemoveColumns()
Reimplemented from QAbstractItemModel.
Definition at line 127 of file qtablewidget.cpp.
Referenced by setColumnCount().
 {
     if (count < 1 || column < 0 || column + count >  horizontalHeaderItems.count())
         return false;
     beginRemoveColumns(QModelIndex(), column, column + count - 1);
     QTableWidgetItem *oldItem = 0;
     for (int row = rowCount() - 1; row >= 0; --row) {
         int i = tableIndex(row, column);
         for (int j = i; j < i + count; ++j) {
             oldItem = tableItems.at(j);
             if (oldItem)
                 oldItem->view = 0;
             delete oldItem;
         }
         tableItems.remove(i, count);
     }
     for (int h=column; h<column+count; ++h) {
         oldItem = horizontalHeaderItems.at(h);
         if (oldItem)
             oldItem->view = 0;
         delete oldItem;
     }
     horizontalHeaderItems.remove(column, count);
     endRemoveColumns();
     return true;
 }
removeItem()
void QTableModel::removeItem (QTableWidgetItem * item)
Definition at line 247 of file qtablewidget.cpp.
 {
     int i = tableItems.indexOf(item);
     if (i != -1) {
         tableItems[i] = 0;
         QModelIndex idx = index(item);
         emit dataChanged(idx, idx);
         return;
     }
     i = verticalHeaderItems.indexOf(item);
     if (i != -1) {
         verticalHeaderItems[i] = 0;
         emit headerDataChanged(Qt::Vertical, i, i);
         return;
     }
     i = horizontalHeaderItems.indexOf(item);
     if (i != -1) {
         horizontalHeaderItems[i] = 0;
         emit headerDataChanged(Qt::Horizontal, i, i);
         return;
     }
 }
removeRows()
bool QTableModel::removeRows (int row, int count = 1, const QModelIndex & parent = QModelIndex()) virtual
On models that support this, removes count rows starting with the given row under parent parent from the model.
Returns true if the rows were successfully removed; otherwise returns false.
The base class implementation does nothing and returns false.
If you implement your own model, you can reimplement this function if you want to support removing. Alternatively, you can provide your own API for altering the data.
See also
removeRow(), removeColumns(), insertColumns(), beginRemoveRows(), endRemoveRows()
Reimplemented from QAbstractItemModel.
Definition at line 100 of file qtablewidget.cpp.
Referenced by setRowCount().
 {
     if (count < 1 || row < 0 || row + count > verticalHeaderItems.count())
         return false;
     beginRemoveRows(QModelIndex(), row, row + count - 1);
     int i = tableIndex(row, 0);
     int n = count * columnCount();
     QTableWidgetItem *oldItem = 0;
     for (int j = i; j < n + i; ++j) {
         oldItem = tableItems.at(j);
         if (oldItem)
             oldItem->view = 0;
         delete oldItem;
     }
     tableItems.remove(qMax(i, 0), n);
     for (int v = row; v < row + count; ++v) {
         oldItem = verticalHeaderItems.at(v);
         if (oldItem)
             oldItem->view = 0;
         delete oldItem;
     }
     verticalHeaderItems.remove(row, count);
     endRemoveRows();
     return true;
 }
rowCount()
int QTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows under the given parent.
When the parent is valid it means that rowCount is returning the number of children of parent.
Note
When implementing a table based model, rowCount() should return 0 when the parent is valid.
See also
columnCount()
Implements QAbstractItemModel.
Definition at line 392 of file qtablewidget.cpp.
Referenced by columnItems(), dropMimeData(), removeColumns(), QTableWidget::setVerticalHeaderLabels(), and sort().
 {
     return parent.isValid() ? 0 : verticalHeaderItems.count();
 }
setColumnCount()
void QTableModel::setColumnCount (int columns)
Definition at line 381 of file qtablewidget.cpp.
 {
     int cc = horizontalHeaderItems.count();
     if (columns < 0 || cc == columns)
         return;
     if (cc < columns)
         insertColumns(qMax(cc, 0), columns - cc);
     else
         removeColumns(qMax(columns, 0), cc - columns);
 }
setData()
bool QTableModel::setData (const QModelIndex & index, const QVariant & value, int role) virtual
Sets the role data for the item at index to value.
Returns true if successful; otherwise returns false.
The dataChanged() signal should be emitted if the data was successfully set.
The base class implementation returns false. This function and data() must be reimplemented for editable models.
See also
Qt::ItemDataRole, data(), itemData()
Reimplemented from QAbstractItemModel.
Definition at line 410 of file qtablewidget.cpp.
 {
     if (!index.isValid())
         return false;
     QTableWidgetItem *itm = item(index);
     if (itm) {
         itm->setData(role, value);
         return true;
     }
     // don't create dummy table items for empty values
     if (!value.isValid())
         return false;
     QTableWidget *view = qobject_cast<QTableWidget*>(QObject::parent());
     if (!view)
         return false;
     itm = createItem();
     itm->setData(role, value);
     view->setItem(index.row(), index.column(), itm);
     return true;
 }
setHeaderData()
bool QTableModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role) virtual
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
Returns true if the header's data was updated; otherwise returns false.
When reimplementing this function, the headerDataChanged() signal must be emitted explicitly.
See also
Qt::ItemDataRole, headerData()
Reimplemented from QAbstractItemModel.
Definition at line 710 of file qtablewidget.cpp.
 {
     if (section < 0 ||
        (orientation == Qt::Horizontal && horizontalHeaderItems.size() <= section) ||
        (orientation == Qt::Vertical && verticalHeaderItems.size() <= section))
     return false;
     QTableWidgetItem *itm = 0;
     if (orientation == Qt::Horizontal)
         itm = horizontalHeaderItems.at(section);
     else
         itm = verticalHeaderItems.at(section);
     if (itm) {
         itm->setData(role, value);
         return true;
     }
     return false;
 }
setHorizontalHeaderItem()
void QTableModel::setHorizontalHeaderItem (int section, QTableWidgetItem * item)
Definition at line 272 of file qtablewidget.cpp.
 {
     if (section < 0 || section >= horizontalHeaderItems.count())
         return;
     QTableWidgetItem *oldItem = horizontalHeaderItems.at(section);
     if (item == oldItem)
         return;
     if (oldItem)
         oldItem->view = 0;
     delete oldItem;
     QTableWidget *view = qobject_cast<QTableWidget*>(QObject::parent());
     if (item) {
         item->view = view;
         item->itemFlags = Qt::ItemFlags(int(item->itemFlags)|ItemIsHeaderItem);
     }
     horizontalHeaderItems[section] = item;
     emit headerDataChanged(Qt::Horizontal, section, section);
 }
setItem()
void QTableModel::setItem (int row, int column, QTableWidgetItem * item)
Definition at line 155 of file qtablewidget.cpp.
 {
     int i = tableIndex(row, column);
     if (i < 0 || i >= tableItems.count())
         return;
     QTableWidgetItem *oldItem = tableItems.at(i);
     if (item == oldItem)
         return;
     // remove old
     if (oldItem)
         oldItem->view = 0;
     delete tableItems.at(i);
     QTableWidget *view = qobject_cast<QTableWidget*>(QObject::parent());
     // set new
     if (item)
         item->d->id = i;
     tableItems[i] = item;
     if (view && view->isSortingEnabled()
         && view->horizontalHeader()->sortIndicatorSection() == column) {
         // sorted insertion
         Qt::SortOrder order = view->horizontalHeader()->sortIndicatorOrder();
         QVector<QTableWidgetItem*> colItems = columnItems(column);
         if (row < colItems.count())
             colItems.remove(row);
         int sortedRow;
         if (item == 0) {
             // move to after all non-0 (sortable) items
             sortedRow = colItems.count();
         } else {
             QVector<QTableWidgetItem*>::iterator it;
             it = sortedInsertionIterator(colItems.begin(), colItems.end(), order, item);
             sortedRow = qMax((int)(it - colItems.begin()), 0);
         }
         if (sortedRow != row) {
             emit layoutAboutToBeChanged();
             // move the items @ row to sortedRow
             int cc = columnCount();
             QVector<QTableWidgetItem*> rowItems(cc);
             for (int j = 0; j < cc; ++j)
                 rowItems[j] = tableItems.at(tableIndex(row, j));
             tableItems.remove(tableIndex(row, 0), cc);
             tableItems.insert(tableIndex(sortedRow, 0), cc, 0);
             for (int j = 0; j < cc; ++j)
                 tableItems[tableIndex(sortedRow, j)] = rowItems.at(j);
             QTableWidgetItem *header = verticalHeaderItems.at(row);
             verticalHeaderItems.remove(row);
             verticalHeaderItems.insert(sortedRow, header);
             // update persistent indexes
             QModelIndexList oldPersistentIndexes = persistentIndexList();
             QModelIndexList newPersistentIndexes = oldPersistentIndexes;
             updateRowIndexes(newPersistentIndexes, row, sortedRow);
             changePersistentIndexList(oldPersistentIndexes,
                                       newPersistentIndexes);
             emit layoutChanged();
             return;
         }
     }
     QModelIndex idx = QAbstractTableModel::index(row, column);
     emit dataChanged(idx, idx);
 }
setItemData()
bool QTableModel::setItemData (const QModelIndex & index, const QMap< int, QVariant > & roles) virtual
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
Returns true if successful; otherwise returns false.
Roles that are not in roles will not be modified.
See also
setData() data() itemData()
Reimplemented from QAbstractItemModel.
Definition at line 449 of file qtablewidget.cpp.
 {
     if (!index.isValid())
         return false;
     QTableWidget *view = qobject_cast<QTableWidget*>(QObject::parent());
     QTableWidgetItem *itm = item(index);
     if (itm) {
         itm->view = 0; // prohibits item from calling itemChanged()
         bool changed = false;
         for (QMap<int, QVariant>::ConstIterator it = roles.constBegin(); it != roles.constEnd(); ++it) {
             if (itm->data(it.key()) != it.value()) {
                 itm->setData(it.key(), it.value());
                 changed = true;
             }
         }
         itm->view = view;
         if (changed)
             itemChanged(itm);
         return true;
     }
     if (!view)
         return false;
     itm = createItem();
     for (QMap<int, QVariant>::ConstIterator it = roles.constBegin(); it != roles.constEnd(); ++it)
         itm->setData(it.key(), it.value());
     view->setItem(index.row(), index.column(), itm);
     return true;
 }
setItemPrototype()
void QTableModel::setItemPrototype (const QTableWidgetItem * item)
Definition at line 798 of file qtablewidget.cpp.
 {
     if (prototype != item) {
         delete prototype;
         prototype = item;
     }
 }
setRowCount()
void QTableModel::setRowCount (int rows)
Definition at line 370 of file qtablewidget.cpp.
 {
     int rc = verticalHeaderItems.count();
     if (rows < 0 || rc == rows)
         return;
     if (rc < rows)
         insertRows(qMax(rc, 0), rows - rc);
     else
         removeRows(qMax(rows, 0), rc - rows);
 }
setVerticalHeaderItem()
void QTableModel::setVerticalHeaderItem (int section, QTableWidgetItem * item)
Definition at line 294 of file qtablewidget.cpp.
 {
     if (section < 0 || section >= verticalHeaderItems.count())
         return;
     QTableWidgetItem *oldItem = verticalHeaderItems.at(section);
     if (item == oldItem)
         return;
     if (oldItem)
         oldItem->view = 0;
     delete oldItem;
     QTableWidget *view = qobject_cast<QTableWidget*>(QObject::parent());
     if (item) {
         item->view = view;
         item->itemFlags = Qt::ItemFlags(int(item->itemFlags)|ItemIsHeaderItem);
     }
     verticalHeaderItems[section] = item;
     emit headerDataChanged(Qt::Vertical, section, section);
 }
sort()
void QTableModel::sort (int column, Qt::SortOrder order) virtual
Sorts the model by column in the given order.
The base class implementation does nothing.
Reimplemented from QAbstractItemModel.
Definition at line 495 of file qtablewidget.cpp.
 {
     QVector<QPair<QTableWidgetItem*, int> > sortable;
     QVector<int> unsortable;
     sortable.reserve(rowCount());
     unsortable.reserve(rowCount());
     for (int row = 0; row < rowCount(); ++row) {
         if (QTableWidgetItem *itm = item(row, column))
             sortable.append(QPair<QTableWidgetItem*,int>(itm, row));
         else
             unsortable.append(row);
     }
     LessThan compare = (order == Qt::AscendingOrder ? &itemLessThan : &itemGreaterThan);
     qStableSort(sortable.begin(), sortable.end(), compare);
     QVector<QTableWidgetItem*> sorted_table(tableItems.count());
     QModelIndexList from;
     QModelIndexList to;
     for (int i = 0; i < rowCount(); ++i) {
         int r = (i < sortable.count()
                  ? sortable.at(i).second
                  : unsortable.at(i - sortable.count()));
         for (int c = 0; c < columnCount(); ++c) {
             sorted_table[tableIndex(i, c)] = item(r, c);
             from.append(createIndex(r, c, 0));
             to.append(createIndex(i, c, 0));
         }
     }
     emit layoutAboutToBeChanged();
     tableItems = sorted_table;
     changePersistentIndexList(from, to); // ### slow
     emit layoutChanged();
 }
sortedInsertionIterator()
QVector< QTableWidgetItem * >::iterator QTableModel::sortedInsertionIterator (const QVector< QTableWidgetItem *>::iterator & begin, const QVector< QTableWidgetItem *>::iterator & end, Qt::SortOrder order, QTableWidgetItem * item) static
Definition at line 668 of file qtablewidget.cpp.
Referenced by ensureSorted(), and setItem().
 {
     if (order == Qt::AscendingOrder)
         return qLowerBound(begin, end, item, QTableModelLessThan());
     return qLowerBound(begin, end, item, QTableModelGreaterThan());
 }
supportedDropActions()
Qt::DropActions QTableModel::supportedDropActions () const virtual
Returns the drop actions supported by this model.
Since
4.2
The default implementation returns Qt::CopyAction. Reimplement this function if you wish to support additional actions. You must also reimplement the dropMimeData() function to handle the additional operations.
See also
dropMimeData(), Qt::DropActions, {Using drag and drop with item views}
Reimplemented from QAbstractItemModel.
Definition at line 847 of file qtablewidget.cpp.
 {
     const QTableWidget *view = qobject_cast<const QTableWidget*>(QObject::parent());
     return (view ? view->supportedDropActions() : Qt::DropActions(Qt::IgnoreAction));
 }
tableIndex()
long QTableModel::tableIndex (int row, int column) const inline
Definition at line 157 of file qtablewidget_p.h.
Referenced by ensureSorted(), insertColumns(), insertRows(), item(), removeColumns(), removeRows(), setItem(), sort(), and takeItem().
         { return (row * horizontalHeaderItems.count()) + column; }
takeHorizontalHeaderItem()
QTableWidgetItem * QTableModel::takeHorizontalHeaderItem (int section)
Definition at line 316 of file qtablewidget.cpp.
 {
     if (section < 0 || section >= horizontalHeaderItems.count())
         return 0;
     QTableWidgetItem *itm = horizontalHeaderItems.at(section);
     if (itm) {
         itm->view = 0;
         itm->itemFlags &= ~ItemIsHeaderItem;
         horizontalHeaderItems[section] = 0;
     }
     return itm;
 }
takeItem()
QTableWidgetItem * QTableModel::takeItem (int row, int column)
Definition at line 221 of file qtablewidget.cpp.
 {
     long i = tableIndex(row, column);
     QTableWidgetItem *itm = tableItems.value(i);
     if (itm) {
         itm->view = 0;
         itm->d->id = -1;
         tableItems[i] = 0;
         QModelIndex ind = index(itm);
         emit dataChanged(ind, ind);
     }
     return itm;
 }
takeVerticalHeaderItem()
QTableWidgetItem * QTableModel::takeVerticalHeaderItem (int section)
Definition at line 329 of file qtablewidget.cpp.
 {
     if (section < 0 || section >= verticalHeaderItems.count())
         return 0;
     QTableWidgetItem *itm = verticalHeaderItems.at(section);
     if (itm) {
         itm->view = 0;
         itm->itemFlags &= ~ItemIsHeaderItem;
         verticalHeaderItems[section] = 0;
     }
     return itm;
 }
updateRowIndexes()
void QTableModel::updateRowIndexes (QModelIndexList & indexes, int movedFromRow, int movedToRow)
Definition at line 643 of file qtablewidget.cpp.
Referenced by ensureSorted(), and setItem().
 {
     QModelIndexList::iterator it;
     for (it = indexes.begin(); it != indexes.end(); ++it) {
         int oldRow = (*it).row();
         int newRow = oldRow;
         if (oldRow == movedFromRow)
             newRow = movedToRow;
         else if (movedFromRow < oldRow && movedToRow >= oldRow)
             newRow = oldRow - 1;
         else if (movedFromRow > oldRow && movedToRow <= oldRow)
             newRow = oldRow + 1;
         if (newRow != oldRow)
             *it = index(newRow, (*it).column(), (*it).parent());
     }
 }
verticalHeaderItem()
QTableWidgetItem * QTableModel::verticalHeaderItem (int section)
Definition at line 347 of file qtablewidget.cpp.
Referenced by QTableWidget::setVerticalHeaderLabels().
 {
     return verticalHeaderItems.value(section);
 }
Properties
cachedIndexes
QModelIndexList QTableModel::cachedIndexes mutable private
Definition at line 184 of file qtablewidget_p.h.
Referenced by internalMimeData(), and mimeData().
horizontalHeaderItems
QVector<QTableWidgetItem*> QTableModel::horizontalHeaderItems private
Definition at line 181 of file qtablewidget_p.h.
Referenced by clear(), columnCount(), headerData(), horizontalHeaderItem(), insertColumns(), insertRows(), isValid(), itemChanged(), removeColumns(), removeItem(), setColumnCount(), setHeaderData(), setHorizontalHeaderItem(), and takeHorizontalHeaderItem().
prototype
const QTableWidgetItem* QTableModel::prototype private
Definition at line 178 of file qtablewidget_p.h.
Referenced by createItem(), itemPrototype(), setItemPrototype(), and ~QTableModel().
tableItems
QVector<QTableWidgetItem*> QTableModel::tableItems private
Definition at line 179 of file qtablewidget_p.h.
Referenced by clearContents(), ensureSorted(), index(), insertColumns(), insertRows(), item(), removeColumns(), removeItem(), removeRows(), setItem(), sort(), and takeItem().
verticalHeaderItems
QVector<QTableWidgetItem*> QTableModel::verticalHeaderItems private
Definition at line 180 of file qtablewidget_p.h.
Referenced by clear(), ensureSorted(), headerData(), insertColumns(), insertRows(), isValid(), itemChanged(), removeItem(), removeRows(), rowCount(), setHeaderData(), setItem(), setRowCount(), setVerticalHeaderItem(), takeVerticalHeaderItem(), and verticalHeaderItem().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtablewidget_p.h
/src/gui/itemviews/qtablewidget.cpp