Qt 4.8: QAccessibleMenuItem Class Reference
QAccessibleMenuItem Class Reference
#include <qaccessiblemenu.h>
Public Functions
virtual int actionCount ()
virtual QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
virtual int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
virtual int childCount () const
Returns the number of children that belong to this object.
virtual QString description (int)
virtual bool doAction (int action, int child, const QVariantList &params=QVariantList())
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
virtual void doAction (int actionIndex)
virtual int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
virtual QVariant invokeMethodEx (Method, int, const QVariantList &)
virtual bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
virtual QStringList keyBindings (int)
virtual QString localizedName (int)
virtual QString name (int)
virtual int navigate (RelationFlag relation, int entry, QAccessibleInterface **target) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
virtual QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QWidget * owner () const
QAccessibleMenuItem (QWidget *owner, QAction *w)
virtual QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
virtual Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
virtual Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
virtual void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
virtual State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
virtual QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
virtual int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
virtual ~QAccessibleMenuItem ()
Public Functions inherited from QAccessibleActionInterface
QAccessible2Interface * qAccessibleActionCastHelper ()
Public Functions inherited from QAccessible2Interface
virtual ~QAccessible2Interface ()
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Protected Functions
QAction * action () const
Properties
QAction * m_action
QWidget * m_owner
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 105 of file qaccessiblemenu.h.
Constructors and Destructors
QAccessibleMenuItem()
QAccessibleMenuItem::QAccessibleMenuItem (QWidget * owner, QAction * w) explicit
Definition at line 408 of file qaccessiblemenu.cpp.
Referenced by navigate().
                                                                         : m_action(action), m_owner(owner)
 {
 }
~QAccessibleMenuItem()
QAccessibleMenuItem::~QAccessibleMenuItem () virtual
Definition at line 413 of file qaccessiblemenu.cpp.
 {}
Functions
action()
QAction * QAccessibleMenuItem::action () const protected
Definition at line 695 of file qaccessiblemenu.cpp.
Referenced by navigate().
 {
     return m_action;
 }
actionCount()
int QAccessibleMenuItem::actionCount () virtual
Implements QAccessibleActionInterface.
Definition at line 473 of file qaccessiblemenu.cpp.
 {
     return 1;
 }
actionText()
QString QAccessibleMenuItem::actionText (int action, Text t, int child) const virtual
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
See also
text(), userActionCount()
Implements QAccessibleInterface.
Definition at line 430 of file qaccessiblemenu.cpp.
Referenced by name().
 {
     if (text == Name && child == 0) {
         switch (action) {
         case Press:
         case DefaultAction:
             if (m_action->menu())
                 return QMenu::tr("Open");
             return QMenu::tr("Execute");
             break;
         default:
             break;
         }
     }
     return QString();
 }
childAt()
int QAccessibleMenuItem::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Implements QAccessibleInterface.
Definition at line 416 of file qaccessiblemenu.cpp.
 {
     for (int i = childCount(); i >= 0; --i) {
         if (rect(i).contains(x,y))
             return i;
     }
     return -1;
 }
childCount()
int QAccessibleMenuItem::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Implements QAccessibleInterface.
Definition at line 425 of file qaccessiblemenu.cpp.
Referenced by childAt(), and navigate().
 {
     return m_action->menu() ? 1 : 0;
 }
description()
QString QAccessibleMenuItem::description (int) virtual
Implements QAccessibleActionInterface.
Definition at line 700 of file qaccessiblemenu.cpp.
 {
     return text(QAccessible::Description, 0);
 }
doAction() [1/2]
bool QAccessibleMenuItem::doAction (int action, int child, const QVariantList & params = QVariantList()) virtual
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
Returns true if the action could be executed; otherwise returns false.
action can be a predefined or a custom action.
See also
userActionCount(), actionText()
Implements QAccessibleInterface.
Definition at line 447 of file qaccessiblemenu.cpp.
Referenced by doAction().
 {
     if ((child) || ((action != DefaultAction) && (action != Press)))
         return false;
     // if the action has a menu, expand/hide it
     if (m_action->menu()) {
         if (m_action->menu()->isVisible()) {
             m_action->menu()->hide();
             return true;
         } else {
             if (QMenuBar *bar = qobject_cast<QMenuBar*>(owner())) {
                 bar->setActiveAction(m_action);
                 return true;
             } else if (QMenu *menu = qobject_cast<QMenu*>(owner())){
                 menu->setActiveAction(m_action);
                 return true;
             }
         }
     }
     // no menu
     m_action->trigger();
     return true;
 }
doAction() [2/2]
void QAccessibleMenuItem::doAction (int actionIndex) virtual
Implements QAccessibleActionInterface.
Definition at line 478 of file qaccessiblemenu.cpp.
 {
     if (actionIndex)
         return;
     doAction(DefaultAction, 0);
 }
indexOfChild()
int QAccessibleMenuItem::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Implements QAccessibleInterface.
Definition at line 486 of file qaccessiblemenu.cpp.
 {
     if (child->role(0) == PopupMenu && child->object() == m_action->menu())
         return 1;
     return -1;
 }
invokeMethodEx()
QVariant QAccessibleMenuItem::invokeMethodEx (Method , int , const QVariantList &) virtual
Implements QAccessibleInterfaceEx.
Definition at line 728 of file qaccessiblemenu.cpp.
 {
     return QVariant();
 }
isValid()
bool QAccessibleMenuItem::isValid () const virtual
Returns true if all the data necessary to use this interface implementation is valid (e.
g. all pointers are non-null); otherwise returns false.
See also
object()
Implements QAccessibleInterface.
Definition at line 494 of file qaccessiblemenu.cpp.
 {
     return m_action ? true : false;
 }
keyBindings()
QStringList QAccessibleMenuItem::keyBindings (int) virtual
Implements QAccessibleActionInterface.
Definition at line 715 of file qaccessiblemenu.cpp.
 {
     QStringList keys;
 #ifndef QT_NO_SHORTCUT
     QKeySequence key = m_action->shortcut();
     if (!key.isEmpty()) {
         keys.append(key.toString());
     }
 #endif
     return keys;
 }
localizedName()
QString QAccessibleMenuItem::localizedName (int) virtual
Implements QAccessibleActionInterface.
Definition at line 710 of file qaccessiblemenu.cpp.
 {
     return text(QAccessible::Name, 0);
 }
name()
QString QAccessibleMenuItem::name (int) virtual
Implements QAccessibleActionInterface.
Definition at line 705 of file qaccessiblemenu.cpp.
 {
     return actionText(DefaultAction, QAccessible::Name, 0);
 }
navigate()
int QAccessibleMenuItem::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Implements QAccessibleInterface.
Definition at line 499 of file qaccessiblemenu.cpp.
 {
     int ret = -1;
     if (entry < 0) {
         *target = 0;
         return ret;
     }
     if (relation == Self || entry == 0) {
         *target = new QAccessibleMenuItem(owner(), action());
         return 0;
     }
     switch (relation) {
     case Child:
         if (entry <= childCount()) {
             *target = new QAccessibleMenu(action()->menu());
             ret = 0;
         }
         break;
     case Ancestor:{
         QWidget *parent = owner();
         QAccessibleInterface *ancestor = parent ? QAccessible::queryAccessibleInterface(parent) : 0;
         if (ancestor) {
             if (entry == 1) {
                 *target = ancestor;
                 ret = 0;
             } else {
                 ret = ancestor->navigate(Ancestor, entry - 1, target);
                 delete ancestor;
             }
         }
         break;}
     case Up:
     case Down:{
         QAccessibleInterface *parent = 0;
         int ent = navigate(Ancestor, 1, &parent);
         if (ent == 0) {
             int index = parent->indexOfChild(this);
             if (index != -1) {
                 index += (relation == Down ? +1 : -1);
                 ret = parent->navigate(Child, index, target);
             }
         }
         delete parent;
         break;}
     case Sibling: {
         QAccessibleInterface *parent = 0;
         int ent = navigate(Ancestor, 1, &parent);
         if (ent == 0) {
             ret = parent->navigate(Child, entry, target);
         }
         delete parent;
         break;}
     default:
         break;
     }
     if (ret == -1)
         *target = 0;
     return ret;
 }
object()
QObject * QAccessibleMenuItem::object () const virtual
Returns a pointer to the QObject this interface implementation provides information for.
See also
isValid()
Implements QAccessibleInterface.
Definition at line 563 of file qaccessiblemenu.cpp.
 {
     return m_action;
 }
owner()
QWidget * QAccessibleMenuItem::owner () const
Definition at line 733 of file qaccessiblemenu.cpp.
Referenced by doAction(), navigate(), rect(), relationTo(), and state().
 {
     return m_owner;
 }
rect()
QRect QAccessibleMenuItem::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Implements QAccessibleInterface.
Definition at line 568 of file qaccessiblemenu.cpp.
Referenced by childAt().
 {
     QRect rect;
     if (child == 0) {
         QWidget *own = owner();
 #ifndef QT_NO_MENUBAR
         if (QMenuBar *menuBar = qobject_cast<QMenuBar*>(own)) {
             rect = menuBar->actionGeometry(m_action);
             QPoint globalPos = menuBar->mapToGlobal(QPoint(0,0));
             rect = rect.translated(globalPos);
         } else
 #endif // QT_NO_MENUBAR
         if (QMenu *menu = qobject_cast<QMenu*>(own)) {
             rect = menu->actionGeometry(m_action);
             QPoint globalPos = menu->mapToGlobal(QPoint(0,0));
             rect = rect.translated(globalPos);
         }
     } else if (child == 1) {
         QMenu *menu = m_action->menu();
         if (menu) {
             rect = menu->rect();
             QPoint globalPos = menu->mapToGlobal(QPoint(0,0));
             rect = rect.translated(globalPos);
         }
     }
     return rect;
 }
relationTo()
QAccessible::Relation QAccessibleMenuItem::relationTo (int child, const QAccessibleInterface * other, int otherChild) const virtual
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
If child is 0 the object's own relation is returned.
The returned value indicates the relation of the called object to the other object, e.g. if this object is a child of other the return value will be Child.
The return value is a combination of the bit flags in the QAccessible::Relation enumeration.
All objects provide this information.
See also
indexOfChild(), navigate()
Implements QAccessibleInterface.
Definition at line 596 of file qaccessiblemenu.cpp.
 {
     if (other->object() == owner()) {
         return Child;
     }
     Q_UNUSED(child)
     Q_UNUSED(other)
     Q_UNUSED(otherChild)
     // ###
     return Unrelated;
 }
role()
QAccessible::Role QAccessibleMenuItem::role (int child) const virtual
Returns the role of the object, or of the object's child if child is not 0.
The role of an object is usually static.
All accessible objects have a role.
See also
text(), state()
Implements QAccessibleInterface.
Definition at line 608 of file qaccessiblemenu.cpp.
 {
     return m_action->isSeparator() ? Separator :MenuItem;
 }
setText()
void QAccessibleMenuItem::setText (Text t, int child, const QString & text) virtual
Sets the text property t of the object, or of the object's child if child is not 0, to text.
Note that the text properties of most objects are read-only.
See also
text()
Implements QAccessibleInterface.
Definition at line 613 of file qaccessiblemenu.cpp.
 {
 }
state()
QAccessible::State QAccessibleMenuItem::state (int child) const virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Implements QAccessibleInterface.
Definition at line 618 of file qaccessiblemenu.cpp.
 {
     QAccessible::State s = Unavailable;
     if (child == 0) {
         s = Normal;
         QWidget *own = owner();
         if (own && (own->testAttribute(Qt::WA_WState_Visible) == false || m_action->isVisible() == false)) {
             s |= Invisible;
         }
         if (QMenu *menu = qobject_cast<QMenu*>(own)) {
             if (menu->activeAction() == m_action)
                 s |= Focused;
 #ifndef QT_NO_MENUBAR
         } else if (QMenuBar *menuBar = qobject_cast<QMenuBar*>(own)) {
             if (menuBar->activeAction() == m_action)
                 s |= Focused;
 #endif
         }
         if (own && own->style()->styleHint(QStyle::SH_Menu_MouseTracking))
             s |= HotTracked;
         if (m_action->isSeparator() || !m_action->isEnabled())
             s |= Unavailable;
         if (m_action->isChecked())
             s |= Checked;
     } else if (child == 1) {
         QMenu *menu = m_action->menu();
         if (menu) {
             QAccessibleInterface *iface = QAccessible::queryAccessibleInterface(menu);
             s = iface->state(0);
             delete iface;
         }
     }
     return s | HasInvokeExtension;;
 }
text()
QString QAccessibleMenuItem::text (Text t, int child) const virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Implements QAccessibleInterface.
Definition at line 656 of file qaccessiblemenu.cpp.
Referenced by description(), and localizedName().
 {
     QString str;
     switch (t) {
     case Name:
         if (child == 0) {
             str = m_action->text();
         } else if (child == 1) {
             QMenu *m = m_action->menu();
             if (m)
                 str = m->title();
         }
         str = qt_accStripAmp(str);
         break;
     case Accelerator:
         if (child == 0) {
 #ifndef QT_NO_SHORTCUT
             QKeySequence key = m_action->shortcut();
             if (!key.isEmpty()) {
                 str = key.toString();
             } else
 #endif
             {
                 str = qt_accHotKey(m_action->text());
             }
         }
         break;
     default:
         break;
     }
     return str;
 }
userActionCount()
int QAccessibleMenuItem::userActionCount (int child) const virtual
Returns the number of custom actions of the object, or of the object's child if child is not 0.
The Action type enumerates predefined actions: these are not included in the returned value.
See also
actionText(), doAction()
Implements QAccessibleInterface.
Definition at line 690 of file qaccessiblemenu.cpp.
 {
     return 0;
 }
Properties
m_action
QAction* QAccessibleMenuItem::m_action private
Definition at line 142 of file qaccessiblemenu.h.
Referenced by action(), actionText(), childCount(), doAction(), indexOfChild(), isValid(), keyBindings(), object(), rect(), role(), state(), and text().
m_owner
QWidget* QAccessibleMenuItem::m_owner private
Definition at line 143 of file qaccessiblemenu.h.
Referenced by owner().
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/qaccessiblemenu.h
/src/plugins/accessible/widgets/qaccessiblemenu.cpp