Qt 4.8: QDeclarativeScriptEngine Class Reference
QDeclarativeScriptEngine Class Reference
#include <qdeclarativeengine_p.h>
Public Functions
virtual QNetworkAccessManager * networkAccessManager ()
QDeclarativeScriptEngine (QDeclarativeEnginePrivate *priv)
QUrl resolvedUrl (QScriptContext *context, const QUrl &url)
virtual ~QDeclarativeScriptEngine ()
Public Functions inherited from QScriptEngine
void abortEvaluation (const QScriptValue &result=QScriptValue())
Aborts any script evaluation currently taking place in this engine.
QScriptEngineAgent * agent () const
Returns the agent currently installed on this engine, or 0 if no agent is installed.
QStringList availableExtensions () const
Returns a list naming the available extensions that can be imported using the importExtension() function.
bool canEvaluate (const QString &program) const
Returns true if program can be evaluated; i.
void clearExceptions ()
Clears any uncaught exceptions in this engine.
void collectGarbage ()
Runs the garbage collector.
QScriptContext * currentContext () const
Returns the current context.
QScriptValue defaultPrototype (int metaTypeId) const
Returns the default prototype associated with the given metaTypeId, or an invalid QScriptValue if no default prototype has been set.
QScriptValue evaluate (const QString &program, const QString &fileName=QString(), int lineNumber=1)
Evaluates program, using lineNumber as the base line number, and returns the result of the evaluation.
QScriptValue evaluate (const QScriptProgram &program)
Evaluates the given program and returns the result of the evaluation.
template<typename T >
T fromScriptValue (const QScriptValue &value)
Returns the given value converted to the template type T.
QScriptValue globalObject () const
Returns this engine's Global Object.
bool hasUncaughtException () const
Returns true if the last script evaluation resulted in an uncaught exception; otherwise returns false.
QStringList importedExtensions () const
Returns a list naming the extensions that have been imported using the importExtension() function.
QScriptValue importExtension (const QString &extension)
Imports the given extension into this QScriptEngine.
void installTranslatorFunctions (const QScriptValue &object=QScriptValue())
Installs translator functions on the given object, or on the Global Object if no object is specified.
bool isEvaluating () const
Returns true if this engine is currently evaluating a script, otherwise returns false.
QScriptValue newActivationObject ()
QScriptValue newArray (uint length=0)
Creates a QtScript object of class Array with the given length.
QScriptValue newDate (qsreal value)
Creates a QtScript object of class Date with the given value (the number of milliseconds since 01 January 1970, UTC).
QScriptValue newDate (const QDateTime &value)
Creates a QtScript object of class Date from the given value.
QScriptValue newFunction (FunctionSignature signature, int length=0)
Creates a QScriptValue that wraps a native (C++) function.
QScriptValue newFunction (FunctionSignature signature, const QScriptValue &prototype, int length=0)
Creates a constructor function from fun, with the given length.
QScriptValue newFunction (FunctionWithArgSignature signature, void *arg)
QScriptValue newObject ()
Creates a QtScript object of class Object.
QScriptValue newObject (QScriptClass *scriptClass, const QScriptValue &data=QScriptValue())
Creates a QtScript Object of the given class, scriptClass.
QScriptValue newQMetaObject (const QMetaObject *metaObject, const QScriptValue &ctor=QScriptValue())
Creates a QtScript object that represents a QObject class, using the the given metaObject and constructor ctor.
QScriptValue newQObject (QObject *object, ValueOwnership ownership=QtOwnership, const QObjectWrapOptions &options=0)
Creates a QtScript object that wraps the given QObject object, using the given ownership.
QScriptValue newQObject (const QScriptValue &scriptObject, QObject *qtObject, ValueOwnership ownership=QtOwnership, const QObjectWrapOptions &options=0)
Initializes the given scriptObject to hold the given qtObject, and returns the scriptObject.
QScriptValue newRegExp (const QRegExp &regexp)
Creates a QtScript object of class RegExp with the given regexp.
QScriptValue newRegExp (const QString &pattern, const QString &flags)
Creates a QtScript object of class RegExp with the given pattern and flags.
QScriptValue newVariant (const QVariant &value)
Creates a QtScript object holding the given variant value.
QScriptValue newVariant (const QScriptValue &object, const QVariant &value)
Initializes the given Qt Script object to hold the given variant value, and returns the object.
QScriptValue nullValue ()
Returns a QScriptValue of the primitive type Null.
QScriptValue objectById (qint64 id) const
Returns the object with the given id, or an invalid QScriptValue if there is no object with that id.
void popContext ()
Pops the current execution context and restores the previous one.
int processEventsInterval () const
Returns the interval in milliseconds between calls to QCoreApplication::processEvents() while the interpreter is running.
QScriptContext * pushContext ()
Enters a new execution context and returns the associated QScriptContext object.
QScriptEngine ()
Constructs a QScriptEngine object.
QScriptEngine (QObject *parent)
Constructs a QScriptEngine object with the given parent.
void reportAdditionalMemoryCost (int size)
Reports an additional memory cost of the given size, measured in bytes, to the garbage collector.
template<class T >
QScriptValue scriptValueFromQMetaObject ()
Creates a QScriptValue that represents the Qt class T.
void setAgent (QScriptEngineAgent *agent)
Installs the given agent on this engine.
void setDefaultPrototype (int metaTypeId, const QScriptValue &prototype)
Sets the default prototype of the C++ type identified by the given metaTypeId to prototype.
void setGlobalObject (const QScriptValue &object)
Sets this engine's Global Object to be the given object.
void setProcessEventsInterval (int interval)
Sets the interval between calls to QCoreApplication::processEvents to interval milliseconds.
QScriptValue toObject (const QScriptValue &value)
Converts the given value to an object, if such a conversion is possible; otherwise returns an invalid QScriptValue.
template<typename T >
QScriptValue toScriptValue (const T &value)
Creates a QScriptValue with the given value.
QScriptString toStringHandle (const QString &str)
Returns a handle that represents the given string, str.
QScriptValue uncaughtException () const
Returns the current uncaught exception, or an invalid QScriptValue if there is no uncaught exception.
QStringList uncaughtExceptionBacktrace () const
Returns a human-readable backtrace of the last uncaught exception.
int uncaughtExceptionLineNumber () const
Returns the line number where the last uncaught exception occurred.
QScriptValue undefinedValue ()
Returns a QScriptValue of the primitive type Undefined.
virtual ~QScriptEngine ()
Destroys this QScriptEngine.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeScriptEngine * get (QScriptEngine *e)
static QScriptValue resolvedUrl (QScriptContext *ctxt, QScriptEngine *engine)
Static Public Functions inherited from QScriptEngine
static QScriptSyntaxCheckResult checkSyntax (const QString &program)
Checks the syntax of the given program.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
QUrl baseUrl
QScriptClass * namedNodeMapClass
QScriptClass * nodeListClass
QString offlineStoragePath
QDeclarativeEnginePrivate * p
QScriptClass * sqlQueryClass
Additional Inherited Members
Public Types inherited from QScriptEngine
typedef void(* DemarshalFunction) (const QScriptValue &, void *)
typedef QScriptValue(* FunctionSignature) (QScriptContext *, QScriptEngine *)
typedef QScriptValue(* FunctionWithArgSignature) (QScriptContext *, QScriptEngine *, void *)
typedef QScriptValue(* MarshalFunction) (QScriptEngine *, const void *)
enum QObjectWrapOption {
ExcludeChildObjects = 0x0001, ExcludeSuperClassMethods = 0x0002, ExcludeSuperClassProperties = 0x0004, ExcludeSuperClassContents = 0x0006,
SkipMethodsInEnumeration = 0x0008, ExcludeDeleteLater = 0x0010, ExcludeSlots = 0x0020, AutoCreateDynamicProperties = 0x0100,
PreferExistingWrapperObject = 0x0200
}
These flags specify options when wrapping a QObject pointer with newQObject().
enum ValueOwnership { QtOwnership, ScriptOwnership, AutoOwnership }
This enum specifies the ownership when wrapping a C++ value, e.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QScriptEngine
void signalHandlerException (const QScriptValue &exception)
This signal is emitted when a script function connected to a signal causes an exception.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QScriptEngine
QScriptEngine (QScriptEnginePrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QScriptEngine
FunctionSignature
FunctionWithArgSignature
bool qScriptConnect (QObject *sender, const char *signal, const QScriptValue &receiver, const QScriptValue &function)
Creates a connection from the signal in the sender to the given function.
bool qScriptDisconnect (QObject *sender, const char *signal, const QScriptValue &receiver, const QScriptValue &function)
Disconnects the signal in the sender from the given (receiver, function) pair.
int qScriptRegisterMetaType (QScriptEngine *engine, QScriptValue(*toScriptValue)(QScriptEngine *, const T &t), void(*fromScriptValue)(const QScriptValue &, T &t), const QScriptValue &prototype=QScriptValue())
int qScriptRegisterSequenceMetaType (QScriptEngine *engine, const QScriptValue &prototype=QScriptValue())
QScriptValue qScriptValueFromQMetaObject (QScriptEngine *engine)
QScriptValue qScriptValueFromSequence (QScriptEngine *engine, const Container &container)
QScriptValue qScriptValueFromValue (QScriptEngine *engine, const T &value)
void qScriptValueToSequence (const QScriptValue &value, Container &container)
Copies the elements in the sequence specified by value to the given container of template type Container.
T qScriptValueToValue (const QScriptValue &value)
Returns the given value converted to the template type T.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 113 of file qdeclarativeengine_p.h.
Constructors and Destructors
QDeclarativeScriptEngine()
QDeclarativeScriptEngine::QDeclarativeScriptEngine (QDeclarativeEnginePrivate * priv)
Definition at line 394 of file qdeclarativeengine.cpp.
 : p(priv), sqlQueryClass(0), namedNodeMapClass(0), nodeListClass(0)
 {
     // Note that all documentation for stuff put on the global object goes in
     // doc/src/declarative/globalobject.qdoc
     bool mainthread = priv != 0;
     QScriptValue qtObject =
         newQMetaObject(StaticQtMetaObject::get());
     globalObject().setProperty(QLatin1String("Qt"), qtObject);
 #ifndef QT_NO_DESKTOPSERVICES
     offlineStoragePath = QDesktopServices::storageLocation(QDesktopServices::DataLocation).replace(QLatin1Char('/'), QDir::separator())
         + QDir::separator() + QLatin1String("QML")
         + QDir::separator() + QLatin1String("OfflineStorage");
 #endif
 #ifndef QT_NO_XMLSTREAMREADER
     qt_add_qmlxmlhttprequest(this);
 #endif
     qt_add_qmlsqldatabase(this);
     // XXX A Multimedia "Qt.Sound" class also needs to be made available,
     // XXX but we don't want a dependency in that cirection.
     // XXX When the above a done some better way, that way should also be
     // XXX used to add Qt.Sound class.
     //types
     if (mainthread)
         qtObject.setProperty(QLatin1String("include"), newFunction(QDeclarativeInclude::include, 2));
     else
         qtObject.setProperty(QLatin1String("include"), newFunction(QDeclarativeInclude::worker_include, 2));
     qtObject.setProperty(QLatin1String("isQtObject"), newFunction(QDeclarativeEnginePrivate::isQtObject, 1));
     qtObject.setProperty(QLatin1String("rgba"), newFunction(QDeclarativeEnginePrivate::rgba, 4));
     qtObject.setProperty(QLatin1String("hsla"), newFunction(QDeclarativeEnginePrivate::hsla, 4));
     qtObject.setProperty(QLatin1String("rect"), newFunction(QDeclarativeEnginePrivate::rect, 4));
     qtObject.setProperty(QLatin1String("point"), newFunction(QDeclarativeEnginePrivate::point, 2));
     qtObject.setProperty(QLatin1String("size"), newFunction(QDeclarativeEnginePrivate::size, 2));
     qtObject.setProperty(QLatin1String("vector3d"), newFunction(QDeclarativeEnginePrivate::vector3d, 3));
     if (mainthread) {
         //color helpers
         qtObject.setProperty(QLatin1String("lighter"), newFunction(QDeclarativeEnginePrivate::lighter, 1));
         qtObject.setProperty(QLatin1String("darker"), newFunction(QDeclarativeEnginePrivate::darker, 1));
         qtObject.setProperty(QLatin1String("tint"), newFunction(QDeclarativeEnginePrivate::tint, 2));
     }
 #ifndef QT_NO_DATESTRING
     //date/time formatting
     qtObject.setProperty(QLatin1String("formatDate"),newFunction(QDeclarativeEnginePrivate::formatDate, 2));
     qtObject.setProperty(QLatin1String("formatTime"),newFunction(QDeclarativeEnginePrivate::formatTime, 2));
     qtObject.setProperty(QLatin1String("formatDateTime"),newFunction(QDeclarativeEnginePrivate::formatDateTime, 2));
 #endif
     //misc methods
     qtObject.setProperty(QLatin1String("openUrlExternally"),newFunction(QDeclarativeEnginePrivate::desktopOpenUrl, 1));
     qtObject.setProperty(QLatin1String("fontFamilies"),newFunction(QDeclarativeEnginePrivate::fontFamilies, 0));
     qtObject.setProperty(QLatin1String("md5"),newFunction(QDeclarativeEnginePrivate::md5, 1));
     qtObject.setProperty(QLatin1String("btoa"),newFunction(QDeclarativeEnginePrivate::btoa, 1));
     qtObject.setProperty(QLatin1String("atob"),newFunction(QDeclarativeEnginePrivate::atob, 1));
     qtObject.setProperty(QLatin1String("quit"), newFunction(QDeclarativeEnginePrivate::quit, 0));
     qtObject.setProperty(QLatin1String("resolvedUrl"),newFunction(QDeclarativeScriptEngine::resolvedUrl, 1));
     if (mainthread) {
         qtObject.setProperty(QLatin1String("createQmlObject"),
                 newFunction(QDeclarativeEnginePrivate::createQmlObject, 1));
         qtObject.setProperty(QLatin1String("createComponent"),
                 newFunction(QDeclarativeEnginePrivate::createComponent, 1));
     }
     //firebug/webkit compat
     QScriptValue consoleObject = newObject();
     consoleObject.setProperty(QLatin1String("log"),newFunction(QDeclarativeEnginePrivate::consoleLog, 1));
     consoleObject.setProperty(QLatin1String("debug"),newFunction(QDeclarativeEnginePrivate::consoleLog, 1));
     globalObject().setProperty(QLatin1String("console"), consoleObject);
     // translation functions need to be installed
     // before the global script class is constructed (QTBUG-6437)
     installTranslatorFunctions();
 }
~QDeclarativeScriptEngine()
QDeclarativeScriptEngine::~QDeclarativeScriptEngine () virtual
Definition at line 476 of file qdeclarativeengine.cpp.
 {
     delete sqlQueryClass;
     delete nodeListClass;
     delete namedNodeMapClass;
 }
Functions
get()
static QDeclarativeScriptEngine* QDeclarativeScriptEngine::get (QScriptEngine * e) inline static
Definition at line 122 of file qdeclarativeengine_p.h.
Referenced by NamedNodeMap::create(), NodeList::create(), QDeclarativeEnginePrivate::createComponent(), QDeclarativeEnginePrivate::desktopOpenUrl(), QDeclarativeInclude::QDeclarativeInclude(), qmlxmlhttprequest_new(), qmlxmlhttprequest_open(), and resolvedUrl().
 { return static_cast<QDeclarativeScriptEngine*>(e); }
networkAccessManager()
QNetworkAccessManager * QDeclarativeScriptEngine::networkAccessManager () virtual
Reimplemented in QDeclarativeWorkerScriptEnginePrivate::ScriptEngine.
Definition at line 490 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeInclude::QDeclarativeInclude().
 {
     return p->getNetworkAccessManager();
 }
resolvedUrl() [1/2]
QUrl QDeclarativeScriptEngine::resolvedUrl (QScriptContext * context, const QUrl & url)
Definition at line 382 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate::createComponent(), QDeclarativeScriptEngine(), qmlxmlhttprequest_open(), and resolvedUrl().
 {
     if (p) {
         QDeclarativeContextData *ctxt = p->getContext(context);
         if (ctxt)
             return ctxt->resolvedUrl(url);
         else
             return p->getUrl(context).resolved(url);
     }
     return baseUrl.resolved(url);
 }
resolvedUrl() [2/2]
QScriptValue QDeclarativeScriptEngine::resolvedUrl (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 483 of file qdeclarativeengine.cpp.
 {
     QString arg = ctxt->argument(0).toString();
     QUrl r = QDeclarativeScriptEngine::get(engine)->resolvedUrl(ctxt,QUrl(arg));
     return QScriptValue(r.toString());
 }
Properties
baseUrl
QUrl QDeclarativeScriptEngine::baseUrl
Definition at line 134 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeWorkerScriptEnginePrivate::processLoad().
namedNodeMapClass
QScriptClass* QDeclarativeScriptEngine::namedNodeMapClass
Definition at line 131 of file qdeclarativeengine_p.h.
Referenced by NamedNodeMap::create(), and ~QDeclarativeScriptEngine().
nodeListClass
QScriptClass* QDeclarativeScriptEngine::nodeListClass
Definition at line 132 of file qdeclarativeengine_p.h.
Referenced by NodeList::create(), and ~QDeclarativeScriptEngine().
offlineStoragePath
QString QDeclarativeScriptEngine::offlineStoragePath
Definition at line 128 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeScriptEngine(), and qmlsqldatabase_databasesPath().
p
QDeclarativeEnginePrivate* QDeclarativeScriptEngine::p
Definition at line 124 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeEnginePrivate::get(), QDeclarativeEnginePrivate::getEngine(), networkAccessManager(), and QDeclarativePrivate::qdeclarativeelement_destructor().
sqlQueryClass
QScriptClass* QDeclarativeScriptEngine::sqlQueryClass
Definition at line 127 of file qdeclarativeengine_p.h.
Referenced by qmlsqldatabase_executeSql(), and ~QDeclarativeScriptEngine().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeengine_p.h
/src/declarative/qml/qdeclarativeengine.cpp