Qt 4.8: QSharedMemory Class Reference
QSharedMemory Class Reference
The QSharedMemory class provides access to a shared memory segment.
#include <qsharedmemory.h>
Public Types
enum AccessMode { ReadOnly, ReadWrite }
enum SharedMemoryError {
NoError, PermissionDenied, InvalidSize, KeyError,
AlreadyExists, NotFound, LockError, OutOfResources,
UnknownError
}
Public Functions
bool attach (AccessMode mode=ReadWrite)
Attempts to attach the process to the shared memory segment identified by the key that was passed to the constructor or to a call to setKey() or setNativeKey().
const void * constData () const
Returns a const pointer to the contents of the shared memory segment, if one is attached.
bool create (int size, AccessMode mode=ReadWrite)
Creates a shared memory segment of size bytes with the key passed to the constructor, set with setKey() or set with setNativeKey(), then attaches to the new shared memory segment with the given access mode and returns true.
void * data ()
Returns a pointer to the contents of the shared memory segment, if one is attached.
const void * data () const
bool detach ()
Detaches the process from the shared memory segment.
SharedMemoryError error () const
Returns a value indicating whether an error occurred, and, if so, which error it was.
QString errorString () const
Returns a text description of the last error that occurred.
bool isAttached () const
Returns true if this process is attached to the shared memory segment.
QString key () const
Returns the key assigned with setKey() to this shared memory, or a null key if no key has been assigned, or if the segment is using a nativeKey().
bool lock ()
This is a semaphore that locks the shared memory segment for access by this process and returns true.
QString nativeKey () const
Returns the native, platform specific, key for this shared memory object.
QSharedMemory (QObject *parent=0)
QSharedMemory (const QString &key, QObject *parent=0)
Constructs a shared memory object with the given parent and with its key set to key.
void setKey (const QString &key)
Sets the platform independent key for this shared memory object.
void setNativeKey (const QString &key)
Sets the native, platform specific, key for this shared memory object.
int size () const
Returns the size of the attached shared memory segment.
bool unlock ()
Releases the lock on the shared memory segment and returns true, if the lock is currently held by this process.
~QSharedMemory ()
The destructor clears the key, which forces the shared memory object to detach() {detach} from its underlying shared memory segment.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Related Functions
(Note that these are not member functions.)
QSharedMemory
Constructs a shared memory object with the given parent.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Detailed Description
The QSharedMemory class provides access to a shared memory segment.
Since
4.4
QSharedMemory provides access to a shared memory segment by multiple threads and processes. It also provides a way for a single thread or process to lock the memory for exclusive access.
When using this class, be aware of the following platform differences:
Windows: QSharedMemory does not "own" the shared memory segment. When all threads or processes that have an instance of QSharedMemory attached to a particular shared memory segment have either destroyed their instance of QSharedMemory or exited, the Windows kernel releases the shared memory segment automatically.
Unix: QSharedMemory "owns" the shared memory segment. When the last thread or process that has an instance of QSharedMemory attached to a particular shared memory segment detaches from the segment by destroying its instance of QSharedMemory, the Unix kernel release the shared memory segment. But if that last thread or process crashes without running the QSharedMemory destructor, the shared memory segment survives the crash.
QNX: Due to possible race conditions in the POSIX IPC implementation, create() should be called prior to any attach() calls (even across multiple threads).
HP-UX: Only one attach to a shared memory segment is allowed per process. This means that QSharedMemory should not be used across multiple threads in the same process in HP-UX.
Symbian: QSharedMemory does not "own" the shared memory segment. When all threads or processes that have an instance of QSharedMemory attached to a particular shared memory segment have either destroyed their instance of QSharedMemory or exited, the Symbian kernel releases the shared memory segment automatically. Also, access to a shared memory segment cannot be limited to read-only in Symbian.
Remember to lock the shared memory with lock() before reading from or writing to the shared memory, and remember to release the lock with unlock() after you are done.
Unlike QtSharedMemory, QSharedMemory automatically destroys the shared memory segment when the last instance of QSharedMemory is detached from the segment, and no references to the segment remain. Do not mix using QtSharedMemory and QSharedMemory. Port everything to QSharedMemory.
Warning
QSharedMemory changes the key in a Qt-specific way, unless otherwise specified. Interoperation with non-Qt applications is achieved by first creating a default shared memory with QSharedMemory() and then setting a native key with setNativeKey(). When using native keys, shared memory is not protected against multiple accesses on it (e.g. unable to lock()) and a user-defined mechanism should be used to achieve a such protection.
Definition at line 57 of file qsharedmemory.h.
Enumerations
AccessMode
enum QSharedMemory::AccessMode
ReadOnly The shared memory segment is read-only. Writing to the shared memory segment is not allowed. An attempt to write to a shared memory segment created with ReadOnly causes the program to abort.
ReadWrite Reading and writing the shared memory segment are both allowed.
Enumerator
ReadOnly
ReadWrite
Definition at line 63 of file qsharedmemory.h.
     {
         ReadOnly,
         ReadWrite
     };
SharedMemoryError
enum QSharedMemory::SharedMemoryError
NoError No error occurred.
PermissionDenied The operation failed because the caller didn't have the required permissions.
InvalidSize A create operation failed because the requested size was invalid.
KeyError The operation failed because of an invalid key.
AlreadyExists A create() operation failed because a shared memory segment with the specified key already existed.
NotFound An attach() failed because a shared memory segment with the specified key could not be found.
LockError The attempt to lock() the shared memory segment failed because create() or attach() failed and returned false, or because a system error occurred in QSystemSemaphore::acquire().
OutOfResources A create() operation failed because there was not enough memory available to fill the request.
UnknownError Something else happened and it was bad.
Enumerator
NoError
PermissionDenied
InvalidSize
KeyError
AlreadyExists
NotFound
LockError
OutOfResources
UnknownError
Definition at line 69 of file qsharedmemory.h.
     {
         NoError,
         PermissionDenied,
         InvalidSize,
         KeyError,
         AlreadyExists,
         NotFound,
         LockError,
         OutOfResources,
         UnknownError
     };
Constructors and Destructors
QSharedMemory() [1/2]
QSharedMemory::QSharedMemory (QObject * parent = 0)
Definition at line 177 of file qsharedmemory.cpp.
   : QObject(*new QSharedMemoryPrivate, parent)
 {
 }
QSharedMemory() [2/2]
QSharedMemory::QSharedMemory (const QString & key, QObject * parent = 0)
Constructs a shared memory object with the given parent and with its key set to key.
Because its key is set, its create() and attach() functions can be called.
See also
setKey(), create(), attach()
Definition at line 189 of file qsharedmemory.cpp.
     : QObject(*new QSharedMemoryPrivate, parent)
 {
     setKey(key);
 }
~QSharedMemory()
QSharedMemory::~QSharedMemory ()
The destructor clears the key, which forces the shared memory object to detach() {detach} from its underlying shared memory segment.
If this shared memory object is the last one connected to the shared memory segment, the detach() operation destroys the shared memory segment.
See also
detach() isAttached()
Definition at line 204 of file qsharedmemory.cpp.
 {
     setKey(QString());
 }
Functions
attach()
bool QSharedMemory::attach (AccessMode mode = ReadWrite)
Attempts to attach the process to the shared memory segment identified by the key that was passed to the constructor or to a call to setKey() or setNativeKey().
The access mode is QSharedMemory::ReadWrite by default. It can also be QSharedMemory::ReadOnly . Returns true if the attach operation is successful. If false is returned, call error() to determine which error occurred. After attaching the shared memory segment, a pointer to the shared memory can be obtained by calling data().
See also
isAttached(), detach(), create()
Definition at line 425 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure().
 {
     Q_D(QSharedMemory);
     if (isAttached() || !d->initKey())
         return false;
 #ifndef QT_NO_SYSTEMSEMAPHORE
     QSharedMemoryLocker lock(this);
     if (!d->key.isNull() && !d->tryLocker(&lock, QLatin1String("QSharedMemory::attach")))
         return false;
 #endif
     if (isAttached() || !d->handle())
         return false;
     return d->attach(mode);
 }
constData()
const void * QSharedMemory::constData () const
Returns a const pointer to the contents of the shared memory segment, if one is attached.
Otherwise it returns null. Remember to lock the shared memory with lock() before reading from or writing to the shared memory, and remember to release the lock with unlock() after you are done.
See also
attach() create()
Definition at line 504 of file qsharedmemory.cpp.
 {
     Q_D(const QSharedMemory);
     return d->memory;
 }
create()
bool QSharedMemory::create (int size, AccessMode mode = ReadWrite)
Creates a shared memory segment of size bytes with the key passed to the constructor, set with setKey() or set with setNativeKey(), then attaches to the new shared memory segment with the given access mode and returns true.
If a shared memory segment identified by the key already exists, the attach operation is not performed and false is returned. When the return value is false, call error() to determine which error occurred.
See also
error()
Definition at line 358 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure().
 {
     Q_D(QSharedMemory);
     if (!d->initKey())
         return false;
     if (size <= 0) {
         d->error = QSharedMemory::InvalidSize;
         d->errorString = QSharedMemory::tr("%1: create size is less then 0").arg(QLatin1String("QSharedMemory::create"));
         return false;
     }
 #ifndef QT_NO_SYSTEMSEMAPHORE
 #ifndef Q_OS_WIN
     // Take ownership and force set initialValue because the semaphore
     // might have already existed from a previous crash.
     d->systemSemaphore.setKey(d->key, 1, QSystemSemaphore::Create);
 #endif
     QSharedMemoryLocker lock(this);
     if (!d->key.isNull() && !d->tryLocker(&lock, QLatin1String("QSharedMemory::create")))
         return false;
 #endif
     if (!d->create(size))
         return false;
     return d->attach(mode);
 }
data() [1/2]
void * QSharedMemory::data ()
Returns a pointer to the contents of the shared memory segment, if one is attached.
Otherwise it returns null. Remember to lock the shared memory with lock() before reading from or writing to the shared memory, and remember to release the lock with unlock() after you are done.
See also
attach()
Definition at line 489 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure().
 {
     Q_D(QSharedMemory);
     return d->memory;
 }
data() [2/2]
const void * QSharedMemory::data () const
Definition at line 513 of file qsharedmemory.cpp.
 {
     Q_D(const QSharedMemory);
     return d->memory;
 }
detach()
bool QSharedMemory::detach ()
Detaches the process from the shared memory segment.
If this was the last process attached to the shared memory segment, then the shared memory segment is released by the system, i.e., the contents are destroyed. The function returns true if it detaches the shared memory segment. If it returns false, it usually means the segment either isn't attached, or it is locked by another process.
See also
attach(), isAttached()
Definition at line 465 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure(), QVNCScreen::disconnect(), setKey(), setNativeKey(), and QVNCScreenPrivate::~QVNCScreenPrivate().
 {
     Q_D(QSharedMemory);
     if (!isAttached())
         return false;
 #ifndef QT_NO_SYSTEMSEMAPHORE
     QSharedMemoryLocker lock(this);
     if (!d->key.isNull() && !d->tryLocker(&lock, QLatin1String("QSharedMemory::detach")))
         return false;
 #endif
     return d->detach();
 }
error()
QSharedMemory::SharedMemoryError QSharedMemory::error () const
Returns a value indicating whether an error occurred, and, if so, which error it was.
See also
errorString()
Definition at line 606 of file qsharedmemory.cpp.
Referenced by QSharedMemoryPrivate::initKey().
 {
     Q_D(const QSharedMemory);
     return d->error;
 }
errorString()
QString QSharedMemory::errorString () const
Returns a text description of the last error that occurred.
If error() returns an QSharedMemory::SharedMemoryError {error value}, call this function to get a text string that describes the error.
See also
error()
Definition at line 620 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure(), and QSharedMemoryPrivate::initKey().
 {
     Q_D(const QSharedMemory);
     return d->errorString;
 }
isAttached()
bool QSharedMemory::isAttached () const
Returns true if this process is attached to the shared memory segment.
See also
attach(), detach()
Definition at line 449 of file qsharedmemory.cpp.
Referenced by attach(), detach(), setKey(), and setNativeKey().
 {
     Q_D(const QSharedMemory);
     return (0 != d->memory);
 }
key()
QString QSharedMemory::key () const
Returns the key assigned with setKey() to this shared memory, or a null key if no key has been assigned, or if the segment is using a nativeKey().
The key is the identifier used by Qt applications to identify the shared memory segment.
You can find the native, platform specific, key used by the operating system by calling nativeKey().
See also
setKey() setNativeKey()
Definition at line 321 of file qsharedmemory.cpp.
Referenced by QSharedMemoryPrivate::initKey(), setKey(), and setNativeKey().
 {
     Q_D(const QSharedMemory);
     return d->key;
 }
lock()
bool QSharedMemory::lock ()
This is a semaphore that locks the shared memory segment for access by this process and returns true.
If another process has locked the segment, this function blocks until the lock is released. Then it acquires the lock and returns true. If this function returns false, it means that you have ignored a false return from create() or attach(), that you have set the key with setNativeKey() or that QSystemSemaphore::acquire() failed due to an unknown system error.
See also
unlock(), data(), QSystemSemaphore::acquire()
Definition at line 531 of file qsharedmemory.cpp.
Referenced by attach(), create(), and detach().
 {
     Q_D(QSharedMemory);
     if (d->lockedByMe) {
         qWarning("QSharedMemory::lock: already locked");
         return true;
     }
     if (d->systemSemaphore.acquire()) {
         d->lockedByMe = true;
         return true;
     }
     QString function = QLatin1String("QSharedMemory::lock");
     d->errorString = QSharedMemory::tr("%1: unable to lock").arg(function);
     d->error = QSharedMemory::LockError;
     return false;
 }
nativeKey()
QString QSharedMemory::nativeKey () const
Returns the native, platform specific, key for this shared memory object.
Since
4.8
The native key is the identifier used by the operating system to identify the shared memory segment.
You can use the native key to access shared memory segments that have not been created by Qt, or to grant shared memory access to non-Qt applications.
See also
setKey() setNativeKey()
Definition at line 342 of file qsharedmemory.cpp.
 {
     Q_D(const QSharedMemory);
     return d->nativeKey;
 }
setKey()
void QSharedMemory::setKey (const QString & key)
Sets the platform independent key for this shared memory object.
If key is the same as the current key, the function returns without doing anything.
You can call key() to retrieve the platform independent key. Internally, QSharedMemory converts this key into a platform specific key. If you instead call nativeKey(), you will get the platform specific, converted key.
If the shared memory object is attached to an underlying shared memory segment, it will detach() {detach} from it before setting the new key. This function does not do an attach().
See also
key() nativeKey() isAttached()
Definition at line 223 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure(), QSharedMemory(), and ~QSharedMemory().
 {
     Q_D(QSharedMemory);
     if (key == d->key && d->makePlatformSafeKey(key) == d->nativeKey)
         return;
     if (isAttached())
         detach();
     d->cleanHandle();
     d->key = key;
     d->nativeKey = d->makePlatformSafeKey(key);
 }
setNativeKey()
void QSharedMemory::setNativeKey (const QString & key)
Sets the native, platform specific, key for this shared memory object.
Since
4.8
If key is the same as the current native key, the function returns without doing anything. If all you want is to assign a key to a segment, you should call setKey() instead.
You can call nativeKey() to retrieve the native key. If a native key has been assigned, calling key() will return a null string.
If the shared memory object is attached to an underlying shared memory segment, it will detach() {detach} from it before setting the new key. This function does not do an attach().
The application will not be portable if you set a native key.
See also
nativeKey() key() isAttached()
Definition at line 258 of file qsharedmemory.cpp.
 {
     Q_D(QSharedMemory);
     if (key == d->nativeKey && d->key.isNull())
         return;
     if (isAttached())
         detach();
     d->cleanHandle();
     d->key.clear();
     d->nativeKey = key;
 }
size()
int QSharedMemory::size () const
Returns the size of the attached shared memory segment.
If no shared memory segment is attached, 0 is returned.
See also
create() attach()
Definition at line 395 of file qsharedmemory.cpp.
Referenced by QVNCScreenPrivate::configure().
 {
     Q_D(const QSharedMemory);
     return d->size;
 }
unlock()
bool QSharedMemory::unlock ()
Releases the lock on the shared memory segment and returns true, if the lock is currently held by this process.
If the segment is not locked, or if the lock is held by another process, nothing happens and false is returned.
See also
lock()
Definition at line 556 of file qsharedmemory.cpp.
 {
     Q_D(QSharedMemory);
     if (!d->lockedByMe)
         return false;
     d->lockedByMe = false;
     if (d->systemSemaphore.release())
         return true;
     QString function = QLatin1String("QSharedMemory::unlock");
     d->errorString = QSharedMemory::tr("%1: unable to unlock").arg(function);
     d->error = QSharedMemory::LockError;
     return false;
 }
Friends and Related Functions
QSharedMemory()
QSharedMemory () related
Constructs a shared memory object with the given parent.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The shared memory object's key is not set by the constructor, so the shared memory object does not have an underlying shared memory segment attached. The key must be set with setKey() or setNativeKey() before create() or attach() can be used.
See also
setKey()
The documentation for this class was generated from the following files:
/src/corelib/kernel/qsharedmemory.h
/src/corelib/kernel/qsharedmemory.cpp