Qt 4.8: QDeclarativeTypeLoader Class Reference
QDeclarativeTypeLoader Class Reference
#include <qdeclarativetypeloader_p.h>
Public Types
enum Option { None, PreserveParser }
This enum defines the options that control the way type data is handled.
Public Functions
QString absoluteFilePath (const QString &path)
Returns the absolute filename of path via a directory cache for files named "qmldir", "*.qml", "*.js" Returns a empty string if the path does not exist.
void clearCache ()
QDeclarativeTypeData * get (const QUrl &url)
Returns a QDeclarativeTypeData for the specified url.
QDeclarativeTypeData * get (const QByteArray &, const QUrl &url, Options=None)
Returns a QDeclarativeTypeData for the given data with the provided base url.
QDeclarativeQmldirData * getQmldir (const QUrl &)
Returns a QDeclarativeQmldirData for url.
QDeclarativeScriptData * getScript (const QUrl &)
Returns a QDeclarativeScriptData for url.
QDeclarativeTypeLoader (QDeclarativeEngine *)
Constructs a new type loader that uses the given engine.
const QDeclarativeDirParser * qmlDirParser (const QString &absoluteFilePath)
Return a QDeclarativeDirParser for absoluteFilePath.
~QDeclarativeTypeLoader ()
Destroys the type loader, first clearing the cache of any information about loaded files.
Public Functions inherited from QDeclarativeDataLoader
QDeclarativeEngine * engine () const
Return the QDeclarativeEngine associated with this loader.
void load (QDeclarativeDataBlob *)
Load the provided blob from the network or filesystem.
void loadWithStaticData (QDeclarativeDataBlob *, const QByteArray &)
Load the provided blob with data.
QDeclarativeDataLoader (QDeclarativeEngine *)
Create a new QDeclarativeDataLoader for engine.
~QDeclarativeDataLoader ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Types
typedef QHash< QString, StringSet * > ImportDirCache
typedef QHash< QString, QDeclarativeDirParser * > ImportQmlDirCache
typedef QHash< QUrl, QDeclarativeQmldirData * > QmldirCache
typedef QHash< QUrl, QDeclarativeScriptData * > ScriptCache
typedef QSet< QString > StringSet
typedef QHash< QUrl, QDeclarativeTypeData * > TypeCache
Properties
ImportDirCache m_importDirCache
ImportQmlDirCache m_importQmlDirCache
QmldirCache m_qmldirCache
ScriptCache m_scriptCache
TypeCache m_typeCache
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Warning
This function is not part of the public interface.
Definition at line 184 of file qdeclarativetypeloader_p.h.
Typedefs
ImportDirCache
typedef QHash<QString, StringSet*> QDeclarativeTypeLoader::ImportDirCache private
Definition at line 212 of file qdeclarativetypeloader_p.h.
ImportQmlDirCache
typedef QHash<QString, QDeclarativeDirParser*> QDeclarativeTypeLoader::ImportQmlDirCache private
Definition at line 213 of file qdeclarativetypeloader_p.h.
QmldirCache
typedef QHash<QUrl, QDeclarativeQmldirData *> QDeclarativeTypeLoader::QmldirCache private
Definition at line 210 of file qdeclarativetypeloader_p.h.
ScriptCache
typedef QHash<QUrl, QDeclarativeScriptData *> QDeclarativeTypeLoader::ScriptCache private
Definition at line 209 of file qdeclarativetypeloader_p.h.
StringSet
typedef QSet<QString> QDeclarativeTypeLoader::StringSet private
Definition at line 211 of file qdeclarativetypeloader_p.h.
TypeCache
typedef QHash<QUrl, QDeclarativeTypeData *> QDeclarativeTypeLoader::TypeCache private
Definition at line 208 of file qdeclarativetypeloader_p.h.
Enumerations
Option
enum QDeclarativeTypeLoader::Option
This enum defines the options that control the way type data is handled.
None The default value, indicating that no other options are enabled.
PreserveParser The parser used to handle the type data is preserved after the data has been parsed.
Enumerator
None
PreserveParser
Definition at line 191 of file qdeclarativetypeloader_p.h.
                 {
         None,
         PreserveParser
     };
Constructors and Destructors
QDeclarativeTypeLoader()
QDeclarativeTypeLoader::QDeclarativeTypeLoader (QDeclarativeEngine * engine)
Constructs a new type loader that uses the given engine.
Definition at line 679 of file qdeclarativetypeloader.cpp.
 : QDeclarativeDataLoader(engine)
 {
 }
~QDeclarativeTypeLoader()
QDeclarativeTypeLoader::~QDeclarativeTypeLoader ()
Destroys the type loader, first clearing the cache of any information about loaded files.
Definition at line 688 of file qdeclarativetypeloader.cpp.
 {
     clearCache();
 }
Functions
absoluteFilePath()
QString QDeclarativeTypeLoader::absoluteFilePath (const QString & path)
Returns the absolute filename of path via a directory cache for files named "qmldir", "*.qml", "*.js" Returns a empty string if the path does not exist.
Definition at line 785 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeImportsPrivate::add(), and QDeclarativeImportedNamespace::find_helper().
 {
     if (path.isEmpty())
         return QString();
     if (path.at(0) == QLatin1Char(':')) {
         // qrc resource
         QFileInfo fileInfo(path);
         return fileInfo.isFile() ? fileInfo.absoluteFilePath() : QString();
     }
 #if defined(Q_OS_WIN32) || defined(Q_OS_WINCE) || defined(Q_OS_DARWIN) || defined(Q_OS_SYMBIAN)
     QString lowPath(path.toLower());
 #else
     QString lowPath(path);
 #endif
     int lastSlash = lowPath.lastIndexOf(QLatin1Char('/'));
     QString dirPath = lowPath.left(lastSlash);
     StringSet *fileSet = 0;
     QHash<QString,StringSet*>::const_iterator it = m_importDirCache.find(dirPath);
     if (it == m_importDirCache.end()) {
         StringSet *files = qmlFilesInDirectory(path.left(lastSlash));
         m_importDirCache.insert(dirPath, files);
         fileSet = files;
     } else {
         fileSet = *it;
     }
     if (!fileSet)
         return QString();
     QString absoluteFilePath = fileSet->contains(QString(lowPath.constData()+lastSlash+1, lowPath.length()-lastSlash-1)) ? path : QString();
     if (absoluteFilePath.length() > 2 && absoluteFilePath.at(0) != QLatin1Char('/') && absoluteFilePath.at(1) != QLatin1Char(':'))
         absoluteFilePath = QFileInfo(absoluteFilePath).absoluteFilePath();
     return absoluteFilePath;
 }
clearCache()
void QDeclarativeTypeLoader::clearCache ()
Definition at line 845 of file qdeclarativetypeloader.cpp.
Referenced by ~QDeclarativeTypeLoader().
 {
     for (TypeCache::Iterator iter = m_typeCache.begin(); iter != m_typeCache.end(); ++iter)
         (*iter)->release();
     for (ScriptCache::Iterator iter = m_scriptCache.begin(); iter != m_scriptCache.end(); ++iter)
         (*iter)->release();
     for (QmldirCache::Iterator iter = m_qmldirCache.begin(); iter != m_qmldirCache.end(); ++iter)
         (*iter)->release();
     qDeleteAll(m_importDirCache);
     qDeleteAll(m_importQmlDirCache);
     m_typeCache.clear();
     m_scriptCache.clear();
     m_qmldirCache.clear();
     m_importDirCache.clear();
     m_importQmlDirCache.clear();
 }
get() [1/2]
QDeclarativeTypeData * QDeclarativeTypeLoader::get (const QUrl & url)
Returns a QDeclarativeTypeData for the specified url.
The QDeclarativeTypeData may be cached.
Definition at line 707 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeBinding::createBinding(), QDeclarativeDomDocument::load(), QDeclarativeComponent::loadUrl(), QDeclarativeTypeData::resolveTypes(), and QDeclarativeComponent::setData().
 {
     Q_ASSERT(!url.isRelative() &&
             (QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url).isEmpty() ||
              !QDir::isRelativePath(QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url))));
     QDeclarativeTypeData *typeData = m_typeCache.value(url);
     if (!typeData) {
         typeData = new QDeclarativeTypeData(url, None, this);
         m_typeCache.insert(url, typeData);
         QDeclarativeDataLoader::load(typeData);
     }
     typeData->addref();
     return typeData;
 }
get() [2/2]
QDeclarativeTypeData * QDeclarativeTypeLoader::get (const QByteArray & data, const QUrl & url, Options options = None)
Returns a QDeclarativeTypeData for the given data with the provided base url.
The QDeclarativeTypeData will not be cached.
The specified options control how the loader handles type data.
Definition at line 731 of file qdeclarativetypeloader.cpp.
 {
     QDeclarativeTypeData *typeData = new QDeclarativeTypeData(url, options, this);
     QDeclarativeDataLoader::loadWithStaticData(typeData, data);
     return typeData;
 }
getQmldir()
QDeclarativeQmldirData * QDeclarativeTypeLoader::getQmldir (const QUrl & url)
Returns a QDeclarativeQmldirData for url.
The QDeclarativeQmldirData may be cached.
Definition at line 762 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::dataReceived().
 {
     Q_ASSERT(!url.isRelative() &&
             (QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url).isEmpty() ||
              !QDir::isRelativePath(QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url))));
     QDeclarativeQmldirData *qmldirData = m_qmldirCache.value(url);
     if (!qmldirData) {
         qmldirData = new QDeclarativeQmldirData(url);
         m_qmldirCache.insert(url, qmldirData);
         QDeclarativeDataLoader::load(qmldirData);
     }
     qmldirData->addref();
     return qmldirData;
 }
getScript()
QDeclarativeScriptData * QDeclarativeTypeLoader::getScript (const QUrl & url)
Returns a QDeclarativeScriptData for url.
The QDeclarativeScriptData may be cached.
Definition at line 741 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeTypeData::dataReceived().
 {
     Q_ASSERT(!url.isRelative() &&
             (QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url).isEmpty() ||
              !QDir::isRelativePath(QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url))));
     QDeclarativeScriptData *scriptData = m_scriptCache.value(url);
     if (!scriptData) {
         scriptData = new QDeclarativeScriptData(url);
         m_scriptCache.insert(url, scriptData);
         QDeclarativeDataLoader::load(scriptData);
     }
     scriptData->addref();
     return scriptData;
 }
qmlDirParser()
const QDeclarativeDirParser * QDeclarativeTypeLoader::qmlDirParser (const QString & absoluteFilePath)
Return a QDeclarativeDirParser for absoluteFilePath.
The QDeclarativeDirParser may be cached.
Definition at line 824 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeImportsPrivate::importExtension().
 {
     QDeclarativeDirParser *qmldirParser;
     QHash<QString,QDeclarativeDirParser*>::const_iterator it = m_importQmlDirCache.find(absoluteFilePath);
     if (it == m_importQmlDirCache.end()) {
         qmldirParser = new QDeclarativeDirParser;
         qmldirParser->setFileSource(absoluteFilePath);
         qmldirParser->setUrl(QUrl::fromLocalFile(absoluteFilePath));
         qmldirParser->parse();
         m_importQmlDirCache.insert(absoluteFilePath, qmldirParser);
     } else {
         qmldirParser = *it;
     }
     return qmldirParser;
 }
Properties
m_importDirCache
ImportDirCache QDeclarativeTypeLoader::m_importDirCache private
Definition at line 218 of file qdeclarativetypeloader_p.h.
Referenced by absoluteFilePath(), and clearCache().
m_importQmlDirCache
ImportQmlDirCache QDeclarativeTypeLoader::m_importQmlDirCache private
Definition at line 219 of file qdeclarativetypeloader_p.h.
Referenced by clearCache(), and qmlDirParser().
m_qmldirCache
QmldirCache QDeclarativeTypeLoader::m_qmldirCache private
Definition at line 217 of file qdeclarativetypeloader_p.h.
Referenced by clearCache(), and getQmldir().
m_scriptCache
ScriptCache QDeclarativeTypeLoader::m_scriptCache private
Definition at line 216 of file qdeclarativetypeloader_p.h.
Referenced by clearCache(), and getScript().
m_typeCache
TypeCache QDeclarativeTypeLoader::m_typeCache private
Definition at line 215 of file qdeclarativetypeloader_p.h.
Referenced by clearCache(), and get().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativetypeloader_p.h
/src/declarative/qml/qdeclarativetypeloader.cpp