Qt 4.8: QLocale Class Reference
QLocale Class Reference
#include <qlocale.h>
Classes
struct Data
Public Types
enum Country {
AnyCountry = 0, Afghanistan = 1, Albania = 2, Algeria = 3,
AmericanSamoa = 4, Andorra = 5, Angola = 6, Anguilla = 7,
Antarctica = 8, AntiguaAndBarbuda = 9, Argentina = 10, Armenia = 11,
Aruba = 12, Australia = 13, Austria = 14, Azerbaijan = 15,
Bahamas = 16, Bahrain = 17, Bangladesh = 18, Barbados = 19,
Belarus = 20, Belgium = 21, Belize = 22, Benin = 23,
Bermuda = 24, Bhutan = 25, Bolivia = 26, BosniaAndHerzegowina = 27,
Botswana = 28, BouvetIsland = 29, Brazil = 30, BritishIndianOceanTerritory = 31,
BruneiDarussalam = 32, Bulgaria = 33, BurkinaFaso = 34, Burundi = 35,
Cambodia = 36, Cameroon = 37, Canada = 38, CapeVerde = 39,
CaymanIslands = 40, CentralAfricanRepublic = 41, Chad = 42, Chile = 43,
China = 44, ChristmasIsland = 45, CocosIslands = 46, Colombia = 47,
Comoros = 48, DemocraticRepublicOfCongo = 49, PeoplesRepublicOfCongo = 50, CookIslands = 51,
CostaRica = 52, IvoryCoast = 53, Croatia = 54, Cuba = 55,
Cyprus = 56, CzechRepublic = 57, Denmark = 58, Djibouti = 59,
Dominica = 60, DominicanRepublic = 61, EastTimor = 62, Ecuador = 63,
Egypt = 64, ElSalvador = 65, EquatorialGuinea = 66, Eritrea = 67,
Estonia = 68, Ethiopia = 69, FalklandIslands = 70, FaroeIslands = 71,
FijiCountry = 72, Finland = 73, France = 74, MetropolitanFrance = 75,
FrenchGuiana = 76, FrenchPolynesia = 77, FrenchSouthernTerritories = 78, Gabon = 79,
Gambia = 80, Georgia = 81, Germany = 82, Ghana = 83,
Gibraltar = 84, Greece = 85, Greenland = 86, Grenada = 87,
Guadeloupe = 88, Guam = 89, Guatemala = 90, Guinea = 91,
GuineaBissau = 92, Guyana = 93, Haiti = 94, HeardAndMcDonaldIslands = 95,
Honduras = 96, HongKong = 97, Hungary = 98, Iceland = 99,
India = 100, Indonesia = 101, Iran = 102, Iraq = 103,
Ireland = 104, Israel = 105, Italy = 106, Jamaica = 107,
Japan = 108, Jordan = 109, Kazakhstan = 110, Kenya = 111,
Kiribati = 112, DemocraticRepublicOfKorea = 113, RepublicOfKorea = 114, Kuwait = 115,
Kyrgyzstan = 116, Lao = 117, Latvia = 118, Lebanon = 119,
Lesotho = 120, Liberia = 121, LibyanArabJamahiriya = 122, Liechtenstein = 123,
Lithuania = 124, Luxembourg = 125, Macau = 126, Macedonia = 127,
Madagascar = 128, Malawi = 129, Malaysia = 130, Maldives = 131,
Mali = 132, Malta = 133, MarshallIslands = 134, Martinique = 135,
Mauritania = 136, Mauritius = 137, Mayotte = 138, Mexico = 139,
Micronesia = 140, Moldova = 141, Monaco = 142, Mongolia = 143,
Montserrat = 144, Morocco = 145, Mozambique = 146, Myanmar = 147,
Namibia = 148, NauruCountry = 149, Nepal = 150, Netherlands = 151,
NetherlandsAntilles = 152, NewCaledonia = 153, NewZealand = 154, Nicaragua = 155,
Niger = 156, Nigeria = 157, Niue = 158, NorfolkIsland = 159,
NorthernMarianaIslands = 160, Norway = 161, Oman = 162, Pakistan = 163,
Palau = 164, PalestinianTerritory = 165, Panama = 166, PapuaNewGuinea = 167,
Paraguay = 168, Peru = 169, Philippines = 170, Pitcairn = 171,
Poland = 172, Portugal = 173, PuertoRico = 174, Qatar = 175,
Reunion = 176, Romania = 177, RussianFederation = 178, Rwanda = 179,
SaintKittsAndNevis = 180, StLucia = 181, StVincentAndTheGrenadines = 182, Samoa = 183,
SanMarino = 184, SaoTomeAndPrincipe = 185, SaudiArabia = 186, Senegal = 187,
Seychelles = 188, SierraLeone = 189, Singapore = 190, Slovakia = 191,
Slovenia = 192, SolomonIslands = 193, Somalia = 194, SouthAfrica = 195,
SouthGeorgiaAndTheSouthSandwichIslands = 196, Spain = 197, SriLanka = 198, StHelena = 199,
StPierreAndMiquelon = 200, Sudan = 201, Suriname = 202, SvalbardAndJanMayenIslands = 203,
Swaziland = 204, Sweden = 205, Switzerland = 206, SyrianArabRepublic = 207,
Taiwan = 208, Tajikistan = 209, Tanzania = 210, Thailand = 211,
Togo = 212, Tokelau = 213, TongaCountry = 214, TrinidadAndTobago = 215,
Tunisia = 216, Turkey = 217, Turkmenistan = 218, TurksAndCaicosIslands = 219,
Tuvalu = 220, Uganda = 221, Ukraine = 222, UnitedArabEmirates = 223,
UnitedKingdom = 224, UnitedStates = 225, UnitedStatesMinorOutlyingIslands = 226, Uruguay = 227,
Uzbekistan = 228, Vanuatu = 229, VaticanCityState = 230, Venezuela = 231,
VietNam = 232, BritishVirginIslands = 233, USVirginIslands = 234, WallisAndFutunaIslands = 235,
WesternSahara = 236, Yemen = 237, Yugoslavia = 238, Zambia = 239,
Zimbabwe = 240, SerbiaAndMontenegro = 241, Montenegro = 242, Serbia = 243,
SaintBarthelemy = 244, SaintMartin = 245, LatinAmericaAndTheCaribbean = 246, LastCountry = LatinAmericaAndTheCaribbean
}
enum CurrencySymbolFormat { CurrencyIsoCode, CurrencySymbol, CurrencyDisplayName }
Specifies the format of the currency symbol.
enum FormatType { LongFormat, ShortFormat, NarrowFormat }
enum Language {
AnyLanguage = 0, C = 1, Abkhazian = 2, Afan = 3,
Afar = 4, Afrikaans = 5, Albanian = 6, Amharic = 7,
Arabic = 8, Armenian = 9, Assamese = 10, Aymara = 11,
Azerbaijani = 12, Bashkir = 13, Basque = 14, Bengali = 15,
Bhutani = 16, Bihari = 17, Bislama = 18, Breton = 19,
Bulgarian = 20, Burmese = 21, Byelorussian = 22, Cambodian = 23,
Catalan = 24, Chinese = 25, Corsican = 26, Croatian = 27,
Czech = 28, Danish = 29, Dutch = 30, English = 31,
Esperanto = 32, Estonian = 33, Faroese = 34, FijiLanguage = 35,
Finnish = 36, French = 37, Frisian = 38, Gaelic = 39,
Galician = 40, Georgian = 41, German = 42, Greek = 43,
Greenlandic = 44, Guarani = 45, Gujarati = 46, Hausa = 47,
Hebrew = 48, Hindi = 49, Hungarian = 50, Icelandic = 51,
Indonesian = 52, Interlingua = 53, Interlingue = 54, Inuktitut = 55,
Inupiak = 56, Irish = 57, Italian = 58, Japanese = 59,
Javanese = 60, Kannada = 61, Kashmiri = 62, Kazakh = 63,
Kinyarwanda = 64, Kirghiz = 65, Korean = 66, Kurdish = 67,
Rundi = 68, Laothian = 69, Latin = 70, Latvian = 71,
Lingala = 72, Lithuanian = 73, Macedonian = 74, Malagasy = 75,
Malay = 76, Malayalam = 77, Maltese = 78, Maori = 79,
Marathi = 80, Moldavian = 81, Mongolian = 82, NauruLanguage = 83,
Nepali = 84, Norwegian = 85, Occitan = 86, Oriya = 87,
Pashto = 88, Persian = 89, Polish = 90, Portuguese = 91,
Punjabi = 92, Quechua = 93, RhaetoRomance = 94, Romanian = 95,
Russian = 96, Samoan = 97, Sangho = 98, Sanskrit = 99,
Serbian = 100, SerboCroatian = 101, Sesotho = 102, Setswana = 103,
Shona = 104, Sindhi = 105, Singhalese = 106, Siswati = 107,
Slovak = 108, Slovenian = 109, Somali = 110, Spanish = 111,
Sundanese = 112, Swahili = 113, Swedish = 114, Tagalog = 115,
Tajik = 116, Tamil = 117, Tatar = 118, Telugu = 119,
Thai = 120, Tibetan = 121, Tigrinya = 122, TongaLanguage = 123,
Tsonga = 124, Turkish = 125, Turkmen = 126, Twi = 127,
Uigur = 128, Ukrainian = 129, Urdu = 130, Uzbek = 131,
Vietnamese = 132, Volapuk = 133, Welsh = 134, Wolof = 135,
Xhosa = 136, Yiddish = 137, Yoruba = 138, Zhuang = 139,
Zulu = 140, Nynorsk = 141, Bosnian = 142, Divehi = 143,
Manx = 144, Cornish = 145, Akan = 146, Konkani = 147,
Ga = 148, Igbo = 149, Kamba = 150, Syriac = 151,
Blin = 152, Geez = 153, Koro = 154, Sidamo = 155,
Atsam = 156, Tigre = 157, Jju = 158, Friulian = 159,
Venda = 160, Ewe = 161, Walamo = 162, Hawaiian = 163,
Tyap = 164, Chewa = 165, Filipino = 166, SwissGerman = 167,
SichuanYi = 168, Kpelle = 169, LowGerman = 170, SouthNdebele = 171,
NorthernSotho = 172, NorthernSami = 173, Taroko = 174, Gusii = 175,
Taita = 176, Fulah = 177, Kikuyu = 178, Samburu = 179,
Sena = 180, NorthNdebele = 181, Rombo = 182, Tachelhit = 183,
Kabyle = 184, Nyankole = 185, Bena = 186, Vunjo = 187,
Bambara = 188, Embu = 189, Cherokee = 190, Morisyen = 191,
Makonde = 192, Langi = 193, Ganda = 194, Bemba = 195,
Kabuverdianu = 196, Meru = 197, Kalenjin = 198, Nama = 199,
Machame = 200, Colognian = 201, Masai = 202, Soga = 203,
Luyia = 204, Asu = 205, Teso = 206, Saho = 207,
KoyraChiini = 208, Rwa = 209, Luo = 210, Chiga = 211,
CentralMoroccoTamazight = 212, KoyraboroSenni = 213, Shambala = 214, Bodo = 215,
Aghem = 216, Basaa = 217, Zarma = 218, Duala = 219,
JolaFonyi = 220, Ewondo = 221, Bafia = 222, LubaKatanga = 223,
MakhuwaMeetto = 224, Mundang = 225, Kwasio = 226, Nuer = 227,
Sakha = 228, Sangu = 229, CongoSwahili = 230, Tasawaq = 231,
Vai = 232, Walser = 233, Yangben = 234, NorwegianBokmal = Norwegian,
NorwegianNynorsk = Nynorsk, Kurundi = Rundi, LastLanguage = Yangben
}
enum MeasurementSystem { MetricSystem, ImperialSystem }
enum NumberOption { OmitGroupSeparator = 0x01, RejectGroupSeparator = 0x02 }
enum QuotationStyle { StandardQuotation, AlternateQuotation }
enum Script {
AnyScript = 0, ArabicScript = 1, CyrillicScript = 2, DeseretScript = 3,
GurmukhiScript = 4, SimplifiedHanScript = 5, TraditionalHanScript = 6, LatinScript = 7,
MongolianScript = 8, TifinaghScript = 9, SimplifiedChineseScript = SimplifiedHanScript, TraditionalChineseScript = TraditionalHanScript,
LastScript = TifinaghScript
}
Public Functions
QString amText () const
Returns the localized name of the "AM" suffix for times specified using the conventions of the 12-hour clock.
QString bcp47Name () const
Returns the dash-separated language, script and country (and possibly other BCP47 fields) of this locale as a string.
Country country () const
Returns the country of this locale.
QString createSeparatedList (const QStringList &strl) const
Returns a string that represents a join of a given list of strings with a separator defined by the locale.
QString currencySymbol (CurrencySymbolFormat=CurrencySymbol) const
Returns a currency symbol according to the format.
QString dateFormat (FormatType format=LongFormat) const
Returns the date format used for the current locale.
QString dateTimeFormat (FormatType format=LongFormat) const
Returns the date time format used for the current locale.
QString dayName (int, FormatType format=LongFormat) const
Returns the localized name of the day (where 1 represents Monday, 2 represents Tuesday and so on), in the format specified by type.
QChar decimalPoint () const
Returns the decimal point character of this locale.
QChar exponential () const
Returns the exponential character of this locale.
Qt::DayOfWeek firstDayOfWeek () const
Returns the first day of the week according to the current locale.
QChar groupSeparator () const
Returns the group separator character of this locale.
Language language () const
Returns the language of this locale.
MeasurementSystem measurementSystem () const
Returns the measurement system for the locale.
QString monthName (int, FormatType format=LongFormat) const
Returns the localized name of month, in the format specified by type.
QString name () const
Returns the language and country of this locale as a string of the form "language_country", where language is a lowercase, two-letter ISO 639 language code, and country is an uppercase, two- or three-letter ISO 3166 country code.
QString nativeCountryName () const
Returns a native name of the country for the locale.
QString nativeLanguageName () const
Returns a native name of the language for the locale.
QChar negativeSign () const
Returns the negative sign character of this locale.
NumberOptions numberOptions () const
Returns the options related to number conversions for this QLocale instance.
bool operator!= (const QLocale &other) const
QLocale & operator= (const QLocale &other)
Assigns other to this QLocale object and returns a reference to this QLocale object.
bool operator== (const QLocale &other) const
QChar percent () const
Returns the percent character of this locale.
QString pmText () const
Returns the localized name of the "PM" suffix for times specified using the conventions of the 12-hour clock.
QChar positiveSign () const
Returns the positive sign character of this locale.
QLocale ()
Constructs a QLocale object initialized with the default locale.
QLocale (const QString &name)
Constructs a QLocale object with the specified name, which has the format "language[_script][_country][.codeset][@modifier]" or "C", where:
QLocale (Language language, Country country=AnyCountry)
Constructs a QLocale object with the specified language and country.
QLocale (Language language, Script script, Country country)
Constructs a QLocale object with the specified language, script and country.
QLocale (const QLocale &other)
Constructs a QLocale object as a copy of other.
QString quoteString (const QString &str, QuotationStyle style=StandardQuotation) const
Returns str quoted according to the current locale using the given quotation style.
QString quoteString (const QStringRef &str, QuotationStyle style=StandardQuotation) const
Script script () const
Returns the script of this locale.
void setNumberOptions (NumberOptions options)
Sets the options related to number conversions for this QLocale instance.
QString standaloneDayName (int, FormatType format=LongFormat) const
Returns the localized name of the day (where 1 represents Monday, 2 represents Tuesday and so on) that is used as a standalone text, in the format specified by type.
QString standaloneMonthName (int, FormatType format=LongFormat) const
Returns the localized name of month that is used as a standalone text, in the format specified by type.
Qt::LayoutDirection textDirection () const
Returns the text direction of the language.
QString timeFormat (FormatType format=LongFormat) const
Returns the time format used for the current locale.
QString toCurrencyString (qlonglong, const QString &symbol=QString()) const
Returns a localized string representation of value as a currency.
QString toCurrencyString (qulonglong, const QString &symbol=QString()) const
QString toCurrencyString (short, const QString &symbol=QString()) const
QString toCurrencyString (ushort, const QString &symbol=QString()) const
QString toCurrencyString (int, const QString &symbol=QString()) const
QString toCurrencyString (uint, const QString &symbol=QString()) const
QString toCurrencyString (double, const QString &symbol=QString()) const
QString toCurrencyString (float, const QString &symbol=QString()) const
QDate toDate (const QString &string, FormatType=LongFormat) const
Parses the date string given in string and returns the date.
QDate toDate (const QString &string, const QString &format) const
Parses the date string given in string and returns the date.
QDateTime toDateTime (const QString &string, FormatType format=LongFormat) const
Parses the date/time string given in string and returns the time.
QDateTime toDateTime (const QString &string, const QString &format) const
Parses the date/time string given in string and returns the time.
double toDouble (const QString &s, bool *ok=0) const
Returns the double represented by the localized string s, or 0.0 if the conversion failed.
float toFloat (const QString &s, bool *ok=0) const
int toInt (const QString &s, bool *ok=0, int base=0) const
Returns the int represented by the localized string s, using base base.
qlonglong toLongLong (const QString &s, bool *ok=0, int base=0) const
Returns the long long int represented by the localized string s, using base base.
QString toLower (const QString &str) const
Returns a lowercase copy of str.
short toShort (const QString &s, bool *ok=0, int base=0) const
Returns the short int represented by the localized string s, using base base.
QString toString (qlonglong i) const
Returns a localized string representation of i.
QString toString (qulonglong i) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QString toString (short i) const
QString toString (ushort i) const
QString toString (int i) const
QString toString (uint i) const
QString toString (double i, char f='g', int prec=6) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.f and prec have the same meaning as in QString::number(double, char, int).
QString toString (float i, char f='g', int prec=6) const
QString toString (const QDate &date, const QString &formatStr) const
Returns a localized string representation of the given date in the specified format.
QString toString (const QDate &date, FormatType format=LongFormat) const
Returns a localized string representation of the given date according to the specified format.
QString toString (const QTime &time, const QString &formatStr) const
Returns a localized string representation of the given time according to the specified format.
QString toString (const QTime &time, FormatType format=LongFormat) const
Returns a localized string representation of the given time in the specified format.
QString toString (const QDateTime &dateTime, FormatType format=LongFormat) const
Returns a localized string representation of the given dateTime according to the specified format.
QString toString (const QDateTime &dateTime, const QString &format) const
Returns a localized string representation of the given dateTime according to the specified format.
QTime toTime (const QString &string, FormatType=LongFormat) const
Parses the time string given in string and returns the time.
QTime toTime (const QString &string, const QString &format) const
Parses the time string given in string and returns the time.
uint toUInt (const QString &s, bool *ok=0, int base=0) const
Returns the unsigned int represented by the localized string s, using base base.
qlonglong toULongLong (const QString &s, bool *ok=0, int base=0) const
Returns the unsigned long long int represented by the localized string s, using base base.
QString toUpper (const QString &str) const
Returns an uppercase copy of str.
ushort toUShort (const QString &s, bool *ok=0, int base=0) const
Returns the unsigned short int represented by the localized string s, using base base.
QStringList uiLanguages () const
Returns an ordered list of locale names for translation purposes in preference order.
QList< Qt::DayOfWeek > weekdays () const
Returns a list of days that are considered weekdays according to the current locale.
QChar zeroDigit () const
Returns the zero digit character of this locale.
Static Public Functions
static QLocale c ()
Returns a QLocale object initialized to the "C" locale.
static QList< Country > countriesForLanguage (Language lang)
Returns the list of countries that have entires for language in Qt's locale database.
static QString countryToString (Country country)
Returns a QString containing the name of country.
static QString languageToString (Language language)
Returns a QString containing the name of language.
static QList< QLocale > matchingLocales (QLocale::Language language, QLocale::Script script, QLocale::Country country)
Returns a list of valid locale objects that match the given language, script and country.
static QString scriptToString (Script script)
Returns a QString containing the name of script.
static void setDefault (const QLocale &locale)
Sets the global default locale to locale.
static QLocale system ()
Returns a QLocale object initialized to the system locale.
Private Functions
const QLocalePrivate * d () const
Properties
union {
Data p
void * v
};
Friends
class QByteArray
class QDoubleValidatorPrivate
class QIntValidator
struct QLocalePrivate
class QString
class QTextStream
class QTextStreamPrivate
Detailed Description
Definition at line 133 of file qlocale.h.
Enumerations
Country
enum QLocale::Country
Enumerator
AnyCountry
Afghanistan
Albania
Algeria
AmericanSamoa
Andorra
Angola
Anguilla
Antarctica
AntiguaAndBarbuda
Argentina
Armenia
Aruba
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bermuda
Bhutan
Bolivia
BosniaAndHerzegowina
Botswana
BouvetIsland
Brazil
BritishIndianOceanTerritory
BruneiDarussalam
Bulgaria
BurkinaFaso
Burundi
Cambodia
Cameroon
Canada
CapeVerde
CaymanIslands
CentralAfricanRepublic
Chad
Chile
China
ChristmasIsland
CocosIslands
Colombia
Comoros
DemocraticRepublicOfCongo
PeoplesRepublicOfCongo
CookIslands
CostaRica
IvoryCoast
Croatia
Cuba
Cyprus
CzechRepublic
Denmark
Djibouti
Dominica
DominicanRepublic
EastTimor
Ecuador
Egypt
ElSalvador
EquatorialGuinea
Eritrea
Estonia
Ethiopia
FalklandIslands
FaroeIslands
FijiCountry
Finland
France
MetropolitanFrance
FrenchGuiana
FrenchPolynesia
FrenchSouthernTerritories
Gabon
Gambia
Georgia
Germany
Ghana
Gibraltar
Greece
Greenland
Grenada
Guadeloupe
Guam
Guatemala
Guinea
GuineaBissau
Guyana
Haiti
HeardAndMcDonaldIslands
Honduras
HongKong
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
DemocraticRepublicOfKorea
RepublicOfKorea
Kuwait
Kyrgyzstan
Lao
Latvia
Lebanon
Lesotho
Liberia
LibyanArabJamahiriya
Liechtenstein
Lithuania
Luxembourg
Macau
Macedonia
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
MarshallIslands
Martinique
Mauritania
Mauritius
Mayotte
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montserrat
Morocco
Mozambique
Myanmar
Namibia
NauruCountry
Nepal
Netherlands
NetherlandsAntilles
NewCaledonia
NewZealand
Nicaragua
Niger
Nigeria
Niue
NorfolkIsland
NorthernMarianaIslands
Norway
Oman
Pakistan
Palau
PalestinianTerritory
Panama
PapuaNewGuinea
Paraguay
Peru
Philippines
Pitcairn
Poland
Portugal
PuertoRico
Qatar
Reunion
Romania
RussianFederation
Rwanda
SaintKittsAndNevis
StLucia
StVincentAndTheGrenadines
Samoa
SanMarino
SaoTomeAndPrincipe
SaudiArabia
Senegal
Seychelles
SierraLeone
Singapore
Slovakia
Slovenia
SolomonIslands
Somalia
SouthAfrica
SouthGeorgiaAndTheSouthSandwichIslands
Spain
SriLanka
StHelena
StPierreAndMiquelon
Sudan
Suriname
SvalbardAndJanMayenIslands
Swaziland
Sweden
Switzerland
SyrianArabRepublic
Taiwan
Tajikistan
Tanzania
Thailand
Togo
Tokelau
TongaCountry
TrinidadAndTobago
Tunisia
Turkey
Turkmenistan
TurksAndCaicosIslands
Tuvalu
Uganda
Ukraine
UnitedArabEmirates
UnitedKingdom
UnitedStates
UnitedStatesMinorOutlyingIslands
Uruguay
Uzbekistan
Vanuatu
VaticanCityState
Venezuela
VietNam
BritishVirginIslands
USVirginIslands
WallisAndFutunaIslands
WesternSahara
Yemen
Yugoslavia
Zambia
Zimbabwe
SerbiaAndMontenegro
Montenegro
Serbia
SaintBarthelemy
SaintMartin
LatinAmericaAndTheCaribbean
LastCountry
Definition at line 405 of file qlocale.h.
                  {
         AnyCountry = 0,
         Afghanistan = 1,
         Albania = 2,
         Algeria = 3,
         AmericanSamoa = 4,
         Andorra = 5,
         Angola = 6,
         Anguilla = 7,
         Antarctica = 8,
         AntiguaAndBarbuda = 9,
         Argentina = 10,
         Armenia = 11,
         Aruba = 12,
         Australia = 13,
         Austria = 14,
         Azerbaijan = 15,
         Bahamas = 16,
         Bahrain = 17,
         Bangladesh = 18,
         Barbados = 19,
         Belarus = 20,
         Belgium = 21,
         Belize = 22,
         Benin = 23,
         Bermuda = 24,
         Bhutan = 25,
         Bolivia = 26,
         BosniaAndHerzegowina = 27,
         Botswana = 28,
         BouvetIsland = 29,
         Brazil = 30,
         BritishIndianOceanTerritory = 31,
         BruneiDarussalam = 32,
         Bulgaria = 33,
         BurkinaFaso = 34,
         Burundi = 35,
         Cambodia = 36,
         Cameroon = 37,
         Canada = 38,
         CapeVerde = 39,
         CaymanIslands = 40,
         CentralAfricanRepublic = 41,
         Chad = 42,
         Chile = 43,
         China = 44,
         ChristmasIsland = 45,
         CocosIslands = 46,
         Colombia = 47,
         Comoros = 48,
         DemocraticRepublicOfCongo = 49,
         PeoplesRepublicOfCongo = 50,
         CookIslands = 51,
         CostaRica = 52,
         IvoryCoast = 53,
         Croatia = 54,
         Cuba = 55,
         Cyprus = 56,
         CzechRepublic = 57,
         Denmark = 58,
         Djibouti = 59,
         Dominica = 60,
         DominicanRepublic = 61,
         EastTimor = 62,
         Ecuador = 63,
         Egypt = 64,
         ElSalvador = 65,
         EquatorialGuinea = 66,
         Eritrea = 67,
         Estonia = 68,
         Ethiopia = 69,
         FalklandIslands = 70,
         FaroeIslands = 71,
         FijiCountry = 72,
         Finland = 73,
         France = 74,
         MetropolitanFrance = 75,
         FrenchGuiana = 76,
         FrenchPolynesia = 77,
         FrenchSouthernTerritories = 78,
         Gabon = 79,
         Gambia = 80,
         Georgia = 81,
         Germany = 82,
         Ghana = 83,
         Gibraltar = 84,
         Greece = 85,
         Greenland = 86,
         Grenada = 87,
         Guadeloupe = 88,
         Guam = 89,
         Guatemala = 90,
         Guinea = 91,
         GuineaBissau = 92,
         Guyana = 93,
         Haiti = 94,
         HeardAndMcDonaldIslands = 95,
         Honduras = 96,
         HongKong = 97,
         Hungary = 98,
         Iceland = 99,
         India = 100,
         Indonesia = 101,
         Iran = 102,
         Iraq = 103,
         Ireland = 104,
         Israel = 105,
         Italy = 106,
         Jamaica = 107,
         Japan = 108,
         Jordan = 109,
         Kazakhstan = 110,
         Kenya = 111,
         Kiribati = 112,
         DemocraticRepublicOfKorea = 113,
         RepublicOfKorea = 114,
         Kuwait = 115,
         Kyrgyzstan = 116,
         Lao = 117,
         Latvia = 118,
         Lebanon = 119,
         Lesotho = 120,
         Liberia = 121,
         LibyanArabJamahiriya = 122,
         Liechtenstein = 123,
         Lithuania = 124,
         Luxembourg = 125,
         Macau = 126,
         Macedonia = 127,
         Madagascar = 128,
         Malawi = 129,
         Malaysia = 130,
         Maldives = 131,
         Mali = 132,
         Malta = 133,
         MarshallIslands = 134,
         Martinique = 135,
         Mauritania = 136,
         Mauritius = 137,
         Mayotte = 138,
         Mexico = 139,
         Micronesia = 140,
         Moldova = 141,
         Monaco = 142,
         Mongolia = 143,
         Montserrat = 144,
         Morocco = 145,
         Mozambique = 146,
         Myanmar = 147,
         Namibia = 148,
         NauruCountry = 149,
         Nepal = 150,
         Netherlands = 151,
         NetherlandsAntilles = 152,
         NewCaledonia = 153,
         NewZealand = 154,
         Nicaragua = 155,
         Niger = 156,
         Nigeria = 157,
         Niue = 158,
         NorfolkIsland = 159,
         NorthernMarianaIslands = 160,
         Norway = 161,
         Oman = 162,
         Pakistan = 163,
         Palau = 164,
         PalestinianTerritory = 165,
         Panama = 166,
         PapuaNewGuinea = 167,
         Paraguay = 168,
         Peru = 169,
         Philippines = 170,
         Pitcairn = 171,
         Poland = 172,
         Portugal = 173,
         PuertoRico = 174,
         Qatar = 175,
         Reunion = 176,
         Romania = 177,
         RussianFederation = 178,
         Rwanda = 179,
         SaintKittsAndNevis = 180,
         StLucia = 181,
         StVincentAndTheGrenadines = 182,
         Samoa = 183,
         SanMarino = 184,
         SaoTomeAndPrincipe = 185,
         SaudiArabia = 186,
         Senegal = 187,
         Seychelles = 188,
         SierraLeone = 189,
         Singapore = 190,
         Slovakia = 191,
         Slovenia = 192,
         SolomonIslands = 193,
         Somalia = 194,
         SouthAfrica = 195,
         SouthGeorgiaAndTheSouthSandwichIslands = 196,
         Spain = 197,
         SriLanka = 198,
         StHelena = 199,
         StPierreAndMiquelon = 200,
         Sudan = 201,
         Suriname = 202,
         SvalbardAndJanMayenIslands = 203,
         Swaziland = 204,
         Sweden = 205,
         Switzerland = 206,
         SyrianArabRepublic = 207,
         Taiwan = 208,
         Tajikistan = 209,
         Tanzania = 210,
         Thailand = 211,
         Togo = 212,
         Tokelau = 213,
         TongaCountry = 214,
         TrinidadAndTobago = 215,
         Tunisia = 216,
         Turkey = 217,
         Turkmenistan = 218,
         TurksAndCaicosIslands = 219,
         Tuvalu = 220,
         Uganda = 221,
         Ukraine = 222,
         UnitedArabEmirates = 223,
         UnitedKingdom = 224,
         UnitedStates = 225,
         UnitedStatesMinorOutlyingIslands = 226,
         Uruguay = 227,
         Uzbekistan = 228,
         Vanuatu = 229,
         VaticanCityState = 230,
         Venezuela = 231,
         VietNam = 232,
         BritishVirginIslands = 233,
         USVirginIslands = 234,
         WallisAndFutunaIslands = 235,
         WesternSahara = 236,
         Yemen = 237,
         Yugoslavia = 238,
         Zambia = 239,
         Zimbabwe = 240,
         SerbiaAndMontenegro = 241,
         Montenegro = 242,
         Serbia = 243,
         SaintBarthelemy = 244,
         SaintMartin = 245,
         LatinAmericaAndTheCaribbean = 246,
         LastCountry = LatinAmericaAndTheCaribbean
     };
CurrencySymbolFormat
enum QLocale::CurrencySymbolFormat
Specifies the format of the currency symbol.
Since
4.8
CurrencyIsoCode a ISO-4217 code of the currency.
CurrencySymbol a currency symbol.
CurrencyDisplayName a user readable name of the currency.
Enumerator
CurrencyIsoCode
CurrencySymbol
CurrencyDisplayName
Definition at line 666 of file qlocale.h.
{
         CurrencyIsoCode,
         CurrencySymbol,
         CurrencyDisplayName
     };
FormatType
enum QLocale::FormatType
Enumerator
LongFormat
ShortFormat
NarrowFormat
Definition at line 659 of file qlocale.h.
 { LongFormat, ShortFormat, NarrowFormat };
Language
enum QLocale::Language
Enumerator
AnyLanguage
C
Abkhazian
Afan
Afar
Afrikaans
Albanian
Amharic
Arabic
Armenian
Assamese
Aymara
Azerbaijani
Bashkir
Basque
Bengali
Bhutani
Bihari
Bislama
Breton
Bulgarian
Burmese
Byelorussian
Cambodian
Catalan
Chinese
Corsican
Croatian
Czech
Danish
Dutch
English
Esperanto
Estonian
Faroese
FijiLanguage
Finnish
French
Frisian
Gaelic
Galician
Georgian
German
Greek
Greenlandic
Guarani
Gujarati
Hausa
Hebrew
Hindi
Hungarian
Icelandic
Indonesian
Interlingua
Interlingue
Inuktitut
Inupiak
Irish
Italian
Japanese
Javanese
Kannada
Kashmiri
Kazakh
Kinyarwanda
Kirghiz
Korean
Kurdish
Rundi
Laothian
Latin
Latvian
Lingala
Lithuanian
Macedonian
Malagasy
Malay
Malayalam
Maltese
Maori
Marathi
Moldavian
Mongolian
NauruLanguage
Nepali
Norwegian
Occitan
Oriya
Pashto
Persian
Polish
Portuguese
Punjabi
Quechua
RhaetoRomance
Romanian
Russian
Samoan
Sangho
Sanskrit
Serbian
SerboCroatian
Sesotho
Setswana
Shona
Sindhi
Singhalese
Siswati
Slovak
Slovenian
Somali
Spanish
Sundanese
Swahili
Swedish
Tagalog
Tajik
Tamil
Tatar
Telugu
Thai
Tibetan
Tigrinya
TongaLanguage
Tsonga
Turkish
Turkmen
Twi
Uigur
Ukrainian
Urdu
Uzbek
Vietnamese
Volapuk
Welsh
Wolof
Xhosa
Yiddish
Yoruba
Zhuang
Zulu
Nynorsk
Bosnian
Divehi
Manx
Cornish
Akan
Konkani
Ga
Igbo
Kamba
Syriac
Blin
Geez
Koro
Sidamo
Atsam
Tigre
Jju
Friulian
Venda
Ewe
Walamo
Hawaiian
Tyap
Chewa
Filipino
SwissGerman
SichuanYi
Kpelle
LowGerman
SouthNdebele
NorthernSotho
NorthernSami
Taroko
Gusii
Taita
Fulah
Kikuyu
Samburu
Sena
NorthNdebele
Rombo
Tachelhit
Kabyle
Nyankole
Bena
Vunjo
Bambara
Embu
Cherokee
Morisyen
Makonde
Langi
Ganda
Bemba
Kabuverdianu
Meru
Kalenjin
Nama
Machame
Colognian
Masai
Soga
Luyia
Asu
Teso
Saho
KoyraChiini
Rwa
Luo
Chiga
CentralMoroccoTamazight
KoyraboroSenni
Shambala
Bodo
Aghem
Basaa
Zarma
Duala
JolaFonyi
Ewondo
Bafia
LubaKatanga
MakhuwaMeetto
Mundang
Kwasio
Nuer
Sakha
Sangu
CongoSwahili
Tasawaq
Vai
Walser
Yangben
NorwegianBokmal
NorwegianNynorsk
Kurundi
LastLanguage
Definition at line 148 of file qlocale.h.
                   {
         AnyLanguage = 0,
         C = 1,
         Abkhazian = 2,
         Afan = 3,
         Afar = 4,
         Afrikaans = 5,
         Albanian = 6,
         Amharic = 7,
         Arabic = 8,
         Armenian = 9,
         Assamese = 10,
         Aymara = 11,
         Azerbaijani = 12,
         Bashkir = 13,
         Basque = 14,
         Bengali = 15,
         Bhutani = 16,
         Bihari = 17,
         Bislama = 18,
         Breton = 19,
         Bulgarian = 20,
         Burmese = 21,
         Byelorussian = 22,
         Cambodian = 23,
         Catalan = 24,
         Chinese = 25,
         Corsican = 26,
         Croatian = 27,
         Czech = 28,
         Danish = 29,
         Dutch = 30,
         English = 31,
         Esperanto = 32,
         Estonian = 33,
         Faroese = 34,
         FijiLanguage = 35,
         Finnish = 36,
         French = 37,
         Frisian = 38,
         Gaelic = 39,
         Galician = 40,
         Georgian = 41,
         German = 42,
         Greek = 43,
         Greenlandic = 44,
         Guarani = 45,
         Gujarati = 46,
         Hausa = 47,
         Hebrew = 48,
         Hindi = 49,
         Hungarian = 50,
         Icelandic = 51,
         Indonesian = 52,
         Interlingua = 53,
         Interlingue = 54,
         Inuktitut = 55,
         Inupiak = 56,
         Irish = 57,
         Italian = 58,
         Japanese = 59,
         Javanese = 60,
         Kannada = 61,
         Kashmiri = 62,
         Kazakh = 63,
         Kinyarwanda = 64,
         Kirghiz = 65,
         Korean = 66,
         Kurdish = 67,
         Rundi = 68,
         Laothian = 69,
         Latin = 70,
         Latvian = 71,
         Lingala = 72,
         Lithuanian = 73,
         Macedonian = 74,
         Malagasy = 75,
         Malay = 76,
         Malayalam = 77,
         Maltese = 78,
         Maori = 79,
         Marathi = 80,
         Moldavian = 81,
         Mongolian = 82,
         NauruLanguage = 83,
         Nepali = 84,
         Norwegian = 85,
         Occitan = 86,
         Oriya = 87,
         Pashto = 88,
         Persian = 89,
         Polish = 90,
         Portuguese = 91,
         Punjabi = 92,
         Quechua = 93,
         RhaetoRomance = 94,
         Romanian = 95,
         Russian = 96,
         Samoan = 97,
         Sangho = 98,
         Sanskrit = 99,
         Serbian = 100,
         SerboCroatian = 101,
         Sesotho = 102,
         Setswana = 103,
         Shona = 104,
         Sindhi = 105,
         Singhalese = 106,
         Siswati = 107,
         Slovak = 108,
         Slovenian = 109,
         Somali = 110,
         Spanish = 111,
         Sundanese = 112,
         Swahili = 113,
         Swedish = 114,
         Tagalog = 115,
         Tajik = 116,
         Tamil = 117,
         Tatar = 118,
         Telugu = 119,
         Thai = 120,
         Tibetan = 121,
         Tigrinya = 122,
         TongaLanguage = 123,
         Tsonga = 124,
         Turkish = 125,
         Turkmen = 126,
         Twi = 127,
         Uigur = 128,
         Ukrainian = 129,
         Urdu = 130,
         Uzbek = 131,
         Vietnamese = 132,
         Volapuk = 133,
         Welsh = 134,
         Wolof = 135,
         Xhosa = 136,
         Yiddish = 137,
         Yoruba = 138,
         Zhuang = 139,
         Zulu = 140,
         Nynorsk = 141,
         Bosnian = 142,
         Divehi = 143,
         Manx = 144,
         Cornish = 145,
         Akan = 146,
         Konkani = 147,
         Ga = 148,
         Igbo = 149,
         Kamba = 150,
         Syriac = 151,
         Blin = 152,
         Geez = 153,
         Koro = 154,
         Sidamo = 155,
         Atsam = 156,
         Tigre = 157,
         Jju = 158,
         Friulian = 159,
         Venda = 160,
         Ewe = 161,
         Walamo = 162,
         Hawaiian = 163,
         Tyap = 164,
         Chewa = 165,
         Filipino = 166,
         SwissGerman = 167,
         SichuanYi = 168,
         Kpelle = 169,
         LowGerman = 170,
         SouthNdebele = 171,
         NorthernSotho = 172,
         NorthernSami = 173,
         Taroko = 174,
         Gusii = 175,
         Taita = 176,
         Fulah = 177,
         Kikuyu = 178,
         Samburu = 179,
         Sena = 180,
         NorthNdebele = 181,
         Rombo = 182,
         Tachelhit = 183,
         Kabyle = 184,
         Nyankole = 185,
         Bena = 186,
         Vunjo = 187,
         Bambara = 188,
         Embu = 189,
         Cherokee = 190,
         Morisyen = 191,
         Makonde = 192,
         Langi = 193,
         Ganda = 194,
         Bemba = 195,
         Kabuverdianu = 196,
         Meru = 197,
         Kalenjin = 198,
         Nama = 199,
         Machame = 200,
         Colognian = 201,
         Masai = 202,
         Soga = 203,
         Luyia = 204,
         Asu = 205,
         Teso = 206,
         Saho = 207,
         KoyraChiini = 208,
         Rwa = 209,
         Luo = 210,
         Chiga = 211,
         CentralMoroccoTamazight = 212,
         KoyraboroSenni = 213,
         Shambala = 214,
         Bodo = 215,
         Aghem = 216,
         Basaa = 217,
         Zarma = 218,
         Duala = 219,
         JolaFonyi = 220,
         Ewondo = 221,
         Bafia = 222,
         LubaKatanga = 223,
         MakhuwaMeetto = 224,
         Mundang = 225,
         Kwasio = 226,
         Nuer = 227,
         Sakha = 228,
         Sangu = 229,
         CongoSwahili = 230,
         Tasawaq = 231,
         Vai = 232,
         Walser = 233,
         Yangben = 234,
         NorwegianBokmal = Norwegian,
         NorwegianNynorsk = Nynorsk,
         Kurundi = Rundi,
         LastLanguage = Yangben
     };
MeasurementSystem
enum QLocale::MeasurementSystem
Enumerator
MetricSystem
ImperialSystem
Definition at line 657 of file qlocale.h.
 { MetricSystem, ImperialSystem };
NumberOption
enum QLocale::NumberOption
Enumerator
OmitGroupSeparator
RejectGroupSeparator
Definition at line 660 of file qlocale.h.
                       {
         OmitGroupSeparator = 0x01,
         RejectGroupSeparator = 0x02
     };
QuotationStyle
enum QLocale::QuotationStyle
Enumerator
StandardQuotation
AlternateQuotation
Definition at line 782 of file qlocale.h.
 { StandardQuotation, AlternateQuotation };
Script
enum QLocale::Script
Enumerator
AnyScript
ArabicScript
CyrillicScript
DeseretScript
GurmukhiScript
SimplifiedHanScript
TraditionalHanScript
LatinScript
MongolianScript
TifinaghScript
SimplifiedChineseScript
TraditionalChineseScript
LastScript
Definition at line 390 of file qlocale.h.
                 {
         AnyScript = 0,
         ArabicScript = 1,
         CyrillicScript = 2,
         DeseretScript = 3,
         GurmukhiScript = 4,
         SimplifiedHanScript = 5,
         TraditionalHanScript = 6,
         LatinScript = 7,
         MongolianScript = 8,
         TifinaghScript = 9,
         SimplifiedChineseScript = SimplifiedHanScript,
         TraditionalChineseScript = TraditionalHanScript,
         LastScript = TifinaghScript
     };
Constructors and Destructors
QLocale() [1/5]
QLocale::QLocale ()
Constructs a QLocale object initialized with the default locale.
If no default locale was set using setDefaultLocale(), this locale will be the same as the one returned by system().
See also
setDefault()
Definition at line 669 of file qlocale.cpp.
     : v(0)
 {
     p.numberOptions = default_number_options;
     p.index = localePrivateIndex(defaultPrivate());
 }
QLocale() [2/5]
QLocale::QLocale (const QString & name)
Constructs a QLocale object with the specified name, which has the format "language[_script][_country][.codeset][@modifier]" or "C", where:
language is a lowercase, two-letter, ISO 639 language code,
script is a titlecase, four-letter, ISO 15924 script code,
country is an uppercase, two- or three-letter, ISO 3166 country code (also "419" as defined by United Nations),
and codeset and modifier are ignored.
The separator can be either underscore or a minus sign.
If the string violates the locale format, or language is not a valid ISO 369 code, the "C" locale is used instead. If country is not present, or is not a valid ISO 3166 code, the most appropriate country is chosen for the specified language.
The language, script and country codes are converted to their respective Language, Script and Country enums. After this conversion is performed the constructor behaves exactly like QLocale(Country, Script, Language).
This constructor is much slower than QLocale(Country, Script, Language).
See also
bcp47Name()
Definition at line 654 of file qlocale.cpp.
     : v(0)
 {
     p.numberOptions = 0;
     p.index = localePrivateIndex(findLocale(name));
 }
QLocale() [3/5]
QLocale::QLocale (Language language, Country country = AnyCountry)
Constructs a QLocale object with the specified language and country.
If the language/country pair is found in the database, it is used.
If the language is found but the country is not, or if the country is AnyCountry, the language is used with the most appropriate available country (for example, Germany for German),
If neither the language nor the country are found, QLocale defaults to the default locale (see setDefault()).
The language and country that are actually used can be queried using language() and country().
See also
setDefault() language() country()
Definition at line 695 of file qlocale.cpp.
     : v(0)
 {
     const QLocalePrivate *d = QLocalePrivate::findLocale(language, QLocale::AnyScript, country);
     // If not found, should default to system
     if (d->languageId() == QLocale::C && language != QLocale::C) {
         p.numberOptions = default_number_options;
         p.index = localePrivateIndex(defaultPrivate());
     } else {
         p.numberOptions = 0;
         p.index = localePrivateIndex(d);
     }
 }
QLocale() [4/5]
QLocale::QLocale (Language language, Script script, Country country)
Constructs a QLocale object with the specified language, script and country.
Since
4.8
If the language/script/country is found in the database, it is used.
If both script is AnyScript and country is AnyCountry, the language is used with the most appropriate available script and country (for example, Germany for German),
If either script is AnyScript or country is AnyCountry, the language is used with the first locale that matches the given script and country.
If neither the language nor the country are found, QLocale defaults to the default locale (see setDefault()).
The language, script and country that are actually used can be queried using language(), script() and country().
See also
setDefault() language() script() country()
Definition at line 737 of file qlocale.cpp.
     : v(0)
 {
     const QLocalePrivate *d = QLocalePrivate::findLocale(language, script, country);
     // If not found, should default to system
     if (d->languageId() == QLocale::C && language != QLocale::C) {
         p.numberOptions = default_number_options;
         p.index = localePrivateIndex(defaultPrivate());
     } else {
         p.numberOptions = 0;
         p.index = localePrivateIndex(d);
     }
 }
QLocale() [5/5]
QLocale::QLocale (const QLocale & other)
Constructs a QLocale object as a copy of other.
Definition at line 756 of file qlocale.cpp.
 {
     v = other.v;
 }
Functions
amText()
QString QLocale::amText () const
Returns the localized name of the "AM" suffix for times specified using the conventions of the 12-hour clock.
Since
4.5
See also
pmText()
Definition at line 2353 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), and QSystemLocale::query().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::AMText, QVariant());
         if (!res.isNull())
             return res.toString();
     }
 #endif
     return getLocaleData(am_data + d()->m_am_idx, d()->m_am_size);
 }
bcp47Name()
QString QLocale::bcp47Name () const
Returns the dash-separated language, script and country (and possibly other BCP47 fields) of this locale as a string.
Since
4.8
Unlike the uiLanguages() the returned value of the bcp47Name() represents the locale name of the QLocale data but not the language the user-interface should be in.
This function tries to conform the locale name to BCP47.
See also
language(), country(), script(), uiLanguages()
Definition at line 1012 of file qlocale.cpp.
Referenced by qt_u_strToCase(), setDefault(), and uiLanguages().
 {
     return d()->bcp47Name();
 }
c()
QLocale QLocale::c () inline static
Returns a QLocale object initialized to the "C" locale.
See also
system()
Definition at line 773 of file qlocale.h.
Referenced by _q_parseDosDir(), _q_parseUnixDir(), QString::arg(), QLocalePrivate::dateTimeToString(), QNetworkHeadersPrivate::fromHttpDate(), QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QApplication::keyboardInputLocale(), QBBSystemLocaleData::languageLocale(), name(), QTextStreamPrivate::putNumber(), q_getKeyboardLocale(), qToLower(), QBBSystemLocaleData::regionLocale(), QNetworkHeadersPrivate::toHttpDate(), QNetworkCookie::toRawForm(), QLocalePrivate::validateChars(), and QKeyMapperPrivate::~QKeyMapperPrivate().
 { return QLocale(C); }
countriesForLanguage()
QList< QLocale::Country > QLocale::countriesForLanguage (Language language) static
Returns the list of countries that have entires for language in Qt's locale database.
Since
4.3
If the result is an empty list, then language is not represented in Qt's locale database.
See also
matchingLocales()
Definition at line 1974 of file qlocale.cpp.
 {
     QList<Country> result;
     unsigned language_id = language;
     uint idx = locale_index[language_id];
     if (language == C) {
         result << AnyCountry;
         return result;
     }
     const QLocalePrivate *d = locale_data + idx;
     while (d->languageId() == language_id) {
         result << static_cast<Country>(d->countryId());
         ++d;
     }
     return result;
 }
country()
QLocale::Country QLocale::country () const
Returns the country of this locale.
See also
language(), script(), countryToString(), bcp47Name()
Definition at line 945 of file qlocale.cpp.
Referenced by QResourceRoot::findNode(), and QSystemLocale::query().
 {
     return Country(d()->countryId());
 }
countryToString()
QString QLocale::countryToString (Country country) static
Returns a QString containing the name of country.
See also
languageToString(), scriptToString(), country(), bcp47Name()
Definition at line 1036 of file qlocale.cpp.
 {
     if (uint(country) > uint(QLocale::LastCountry))
         return QLatin1String("Unknown");
     return QLatin1String(country_name_list + country_name_index[country]);
 }
createSeparatedList()
QString QLocale::createSeparatedList (const QStringList & list) const
Returns a string that represents a join of a given list of strings with a separator defined by the locale.
Since
4.8
Definition at line 855 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res;
         res = systemLocale()->query(QSystemLocale::ListToSeparatedString, QVariant::fromValue(list));
         if (!res.isNull())
             return res.toString();
     }
 #endif
     const int size = list.size();
     if (size == 1) {
         return list.at(0);
     } else if (size == 2) {
         QString format = getLocaleData(list_pattern_part_data + d()->m_list_pattern_part_two_idx, d()->m_list_pattern_part_two_size);
         return format.arg(list.at(0), list.at(1));
     } else if (size > 2) {
         QString formatStart = getLocaleData(list_pattern_part_data + d()->m_list_pattern_part_start_idx, d()->m_list_pattern_part_start_size);
         QString formatMid = getLocaleData(list_pattern_part_data + d()->m_list_pattern_part_mid_idx, d()->m_list_pattern_part_mid_size);
         QString formatEnd = getLocaleData(list_pattern_part_data + d()->m_list_pattern_part_end_idx, d()->m_list_pattern_part_end_size);
         QString result = formatStart.arg(list.at(0), list.at(1));
         for (int i = 2; i < size - 1; ++i)
             result = formatMid.arg(result, list.at(i));
         result = formatEnd.arg(result, list.at(size - 1));
         return result;
     }
     return QString();
 }
currencySymbol()
QString QLocale::currencySymbol (QLocale::CurrencySymbolFormat format = CurrencySymbol) const
Returns a currency symbol according to the format.
Since
4.8
Definition at line 3267 of file qlocale.cpp.
Referenced by toCurrencyString().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::CurrencySymbol, format);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     quint32 idx, size;
     switch (format) {
     case CurrencySymbol:
         idx = d()->m_currency_symbol_idx;
         size = d()->m_currency_symbol_size;
         return getLocaleData(currency_symbol_data + idx, size);
     case CurrencyDisplayName:
         idx = d()->m_currency_display_name_idx;
         size = d()->m_currency_display_name_size;
         return getLocaleListData(currency_display_name_data + idx, size, 0);
     case CurrencyIsoCode: {
         int len = 0;
         const QLocalePrivate *d = this->d();
         for (; len < 3; ++len)
             if (!d->m_currency_iso_code[len])
                 break;
         return len ? QString::fromLatin1(d->m_currency_iso_code, len) : QString();
     }
     }
     return QString();
 }
d()
const QLocalePrivate * QLocale::d () const private
Definition at line 761 of file qlocale.cpp.
Referenced by amText(), QString::arg(), bcp47Name(), QLocalePrivate::bytearrayToDouble(), countriesForLanguage(), country(), createSeparatedList(), currencySymbol(), dateFormat(), dateTimeFormat(), dayName(), decimalPoint(), exponential(), firstDayOfWeek(), QIntValidator::fixup(), groupSeparator(), language(), matchingLocales(), measurementSystem(), monthName(), name(), nativeCountryName(), nativeLanguageName(), negativeSign(), operator!=(), operator==(), percent(), pmText(), positiveSign(), QTextStreamPrivate::putNumber(), QLocale(), quoteString(), script(), setDefault(), QByteArray::setNum(), QString::setNum(), standaloneDayName(), standaloneMonthName(), timeFormat(), toCurrencyString(), QString::toDouble(), toDouble(), toFloat(), QString::toLongLong(), toLongLong(), toString(), QString::toULongLong(), toULongLong(), uiLanguages(), QLocalePrivate::updateSystemPrivate(), QIntValidator::validate(), QDoubleValidatorPrivate::validateWithLocale(), QString::vsprintf(), weekdays(), and zeroDigit().
 {
     return dataPointerHelper(p.index);
 }
dateFormat()
QString QLocale::dateFormat (FormatType format = LongFormat) const
Returns the date format used for the current locale.
Since
4.1
If format is LongFormat the format will be a long version. Otherwise it uses a shorter version.
See also
QDate::toString(), QDate::fromString()
Definition at line 1495 of file qlocale.cpp.
Referenced by dateTimeFormat(), QSystemLocale::query(), QDateTimeEditPrivate::readLocaleSettings(), toDate(), and toString().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(format == LongFormat
                                              ? QSystemLocale::DateFormatLong : QSystemLocale::DateFormatShort,
                                              QVariant());
         if (!res.isNull())
             return res.toString();
     }
 #endif
     quint32 idx, size;
     switch (format) {
     case LongFormat:
         idx = d()->m_long_date_format_idx;
         size = d()->m_long_date_format_size;
         break;
     default:
         idx = d()->m_short_date_format_idx;
         size = d()->m_short_date_format_size;
         break;
     }
     return getLocaleData(date_format_data + idx, size);
 }
dateTimeFormat()
QString QLocale::dateTimeFormat (FormatType format = LongFormat) const
Returns the date time format used for the current locale.
Since
4.4
If format is ShortFormat the format will be a short version. Otherwise it uses a longer version.
See also
QDateTime::toString(), QDateTime::fromString()
Definition at line 1575 of file qlocale.cpp.
Referenced by QDateTimeEditPrivate::readLocaleSettings(), toDateTime(), and toString().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(format == LongFormat
                                              ? QSystemLocale::DateTimeFormatLong
                                              : QSystemLocale::DateTimeFormatShort,
                                              QVariant());
         if (!res.isNull()) {
             return res.toString();
         }
     }
 #endif
     return dateFormat(format) + QLatin1Char(' ') + timeFormat(format);
 }
dayName()
QString QLocale::dayName (int day, FormatType type = LongFormat) const
Returns the localized name of the day (where 1 represents Monday, 2 represents Tuesday and so on), in the format specified by type.
Since
4.2
See also
monthName(), standaloneDayName()
Definition at line 2106 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), QCalendarModel::dayName(), QDateTimeParser::findDay(), QDate::longDayName(), QSystemLocale::query(), QDateTimeParser::sectionMaxSize(), QDate::shortDayName(), standaloneDayName(), and QCalendarDayValidator::text().
 {
     if (day < 1 || day > 7)
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(type == LongFormat
                                              ? QSystemLocale::DayNameLong : QSystemLocale::DayNameShort,
                                              day);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     if (day == 7)
         day = 0;
     quint32 idx, size;
     switch (type) {
     case QLocale::LongFormat:
         idx = d()->m_long_day_names_idx;
         size = d()->m_long_day_names_size;
         break;
     case QLocale::ShortFormat:
         idx = d()->m_short_day_names_idx;
         size = d()->m_short_day_names_size;
         break;
     case QLocale::NarrowFormat:
         idx = d()->m_narrow_day_names_idx;
         size = d()->m_narrow_day_names_size;
         break;
     default:
         return QString();
     }
     return getLocaleListData(days_data + idx, size, day);
 }
decimalPoint()
QChar QLocale::decimalPoint () const
Returns the decimal point character of this locale.
Since
4.1
Definition at line 1765 of file qlocale.cpp.
Referenced by QTextStreamPrivate::getReal(), QSystemLocale::query(), and QDoubleSpinBoxPrivate::validateAndInterpret().
 {
     return d()->decimal();
 }
exponential()
QChar QLocale::exponential () const
Returns the exponential character of this locale.
Since
4.1
Definition at line 1843 of file qlocale.cpp.
Referenced by QLocalePrivate::doubleToString(), and QTextStreamPrivate::getReal().
 {
     return d()->exponential();
 }
firstDayOfWeek()
Qt::DayOfWeek QLocale::firstDayOfWeek () const
Returns the first day of the week according to the current locale.
Since
4.8
Definition at line 2206 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::FirstDayOfWeek, QVariant());
         if (!res.isNull())
             return static_cast<Qt::DayOfWeek>(res.toUInt());
     }
 #endif
     return static_cast<Qt::DayOfWeek>(d()->m_first_day_of_week);
 }
groupSeparator()
QChar QLocale::groupSeparator () const
Returns the group separator character of this locale.
Since
4.1
Definition at line 1778 of file qlocale.cpp.
Referenced by QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QSystemLocale::query(), QSpinBoxPrivate::validateAndInterpret(), and QDoubleSpinBoxPrivate::validateAndInterpret().
 {
     return d()->group();
 }
language()
QLocale::Language QLocale::language () const
Returns the language of this locale.
See also
script(), country(), languageToString(), bcp47Name()
Definition at line 920 of file qlocale.cpp.
Referenced by countriesForLanguage(), QResourceRoot::findNode(), matchingLocales(), QSystemLocale::query(), and textDirection().
 {
     return Language(d()->languageId());
 }
languageToString()
QString QLocale::languageToString (Language language) static
Returns a QString containing the name of language.
See also
countryToString(), scriptToString(), bcp47Name()
Definition at line 1023 of file qlocale.cpp.
 {
     if (uint(language) > uint(QLocale::LastLanguage))
         return QLatin1String("Unknown");
     return QLatin1String(language_name_list + language_name_index[language]);
 }
matchingLocales()
QList< QLocale > QLocale::matchingLocales (QLocale::Language language, QLocale::Script script, QLocale::Country country) static
Returns a list of valid locale objects that match the given language, script and country.
Since
4.8
Getting a list of all locales: QList<QLocale> allLocales = QLocale::matchingLocales(QLocale::AnyLanguage, QLocale::AnyScript, QLocale::AnyCountry);
Definition at line 1937 of file qlocale.cpp.
 {
     if (uint(language) > QLocale::LastLanguage || uint(script) > QLocale::LastScript ||
             uint(country) > QLocale::LastCountry)
         return QList<QLocale>();
     QList<QLocale> result;
     const QLocalePrivate *d = locale_data;
     if (language == QLocale::AnyLanguage && script == QLocale::AnyScript && country == QLocale::AnyCountry)
         result.reserve(locale_data_size);
     if (language != QLocale::C)
         d += locale_index[language];
     while ( (d != locale_data + locale_data_size)
             && (language == QLocale::AnyLanguage || d->m_language_id == uint(language))) {
         QLocale locale(QLocale::C);
         locale.p.index = localePrivateIndex(d);
         result.append(locale);
         ++d;
     }
     return result;
 }
measurementSystem()
QLocale::MeasurementSystem QLocale::measurementSystem () const
Returns the measurement system for the locale.
Since
4.4
Definition at line 2265 of file qlocale.cpp.
Referenced by QPageSetupWidget::QPageSetupWidget(), and QPageSetupWidget::selectPrinter().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::MeasurementSystem, QVariant());
         if (!res.isNull())
             return MeasurementSystem(res.toInt());
     }
 #endif
     return d()->measurementSystem();
 }
monthName()
QString QLocale::monthName (int month, FormatType type = LongFormat) const
Returns the localized name of month, in the format specified by type.
Since
4.2
See also
dayName(), standaloneMonthName()
Definition at line 2007 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), QDateTimeParser::findMonth(), QDate::longMonthName(), QSystemLocale::query(), QDateTimeParser::sectionMaxSize(), QDate::shortMonthName(), and standaloneMonthName().
 {
     if (month < 1 || month > 12)
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(type == LongFormat
                                              ? QSystemLocale::MonthNameLong : QSystemLocale::MonthNameShort,
                                              month);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     quint32 idx, size;
     switch (type) {
     case QLocale::LongFormat:
         idx = d()->m_long_month_names_idx;
         size = d()->m_long_month_names_size;
         break;
     case QLocale::ShortFormat:
         idx = d()->m_short_month_names_idx;
         size = d()->m_short_month_names_size;
         break;
     case QLocale::NarrowFormat:
         idx = d()->m_narrow_month_names_idx;
         size = d()->m_narrow_month_names_size;
         break;
     default:
         return QString();
     }
     return getLocaleListData(months_data + idx, size, month - 1);
 }
name()
QString QLocale::name () const
Returns the language and country of this locale as a string of the form "language_country", where language is a lowercase, two-letter ISO 639 language code, and country is an uppercase, two- or three-letter ISO 3166 country code.
Note that even if QLocale object was constructed with an explicit script, name() will not contain it for compatibility reasons. Use bcp47Name() instead if you need a full locale name.
See also
QLocale(), language(), script(), country(), bcp47Name()
Definition at line 963 of file qlocale.cpp.
Referenced by QTextCodec::canEncode(), QSvgSwitch::init(), operator<<(), QHttpNetworkConnectionPrivate::prepareRequest(), standaloneDayName(), and standaloneMonthName().
 {
     const QLocalePrivate *dd = d();
     if (dd->m_language_id == QLocale::AnyLanguage)
         return QString();
     if (dd->m_language_id == QLocale::C)
         return QLatin1String("C");
     const unsigned char *c = language_code_list + 3*(uint(dd->m_language_id));
     QString result(7, Qt::Uninitialized);
     ushort *data = (ushort *)result.unicode();
     const ushort *begin = data;
     *data++ = ushort(c[0]);
     *data++ = ushort(c[1]);
     if (c[2] != 0)
         *data++ = ushort(c[2]);
     if (dd->m_country_id != AnyCountry) {
         *data++ = '_';
         const unsigned char *c = country_code_list + 3*(uint(dd->m_country_id));
         *data++ = ushort(c[0]);
         *data++ = ushort(c[1]);
         if (c[2] != 0)
             *data++ = ushort(c[2]);
     }
     result.resize(data - begin);
     return result;
 }
nativeCountryName()
QString QLocale::nativeCountryName () const
Returns a native name of the country for the locale.
Since
4.8
For example "Espaa" for Spanish/Spain locale.
See also
nativeLanguageName(), countryToString()
Definition at line 3459 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::NativeCountryName, QVariant());
         if (!res.isNull())
             return res.toString();
     }
 #endif
     return getLocaleData(endonyms_data + d()->m_country_endonym_idx, d()->m_country_endonym_size);
 }
nativeLanguageName()
QString QLocale::nativeLanguageName () const
Returns a native name of the language for the locale.
Since
4.8
For example "Schwiizerttsch" for Swiss-German locale.
See also
nativeCountryName(), languageToString()
Definition at line 3436 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::NativeLanguageName, QVariant());
         if (!res.isNull())
             return res.toString();
     }
 #endif
     return getLocaleData(endonyms_data + d()->m_language_endonym_idx, d()->m_language_endonym_size);
 }
negativeSign()
QChar QLocale::negativeSign () const
Returns the negative sign character of this locale.
Since
4.1
Definition at line 1817 of file qlocale.cpp.
Referenced by QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QTextStreamPrivate::putNumber(), QTextStreamPrivate::putString(), and QSystemLocale::query().
 {
     return d()->minus();
 }
numberOptions()
QLocale::NumberOptions QLocale::numberOptions () const
Returns the options related to number conversions for this QLocale instance.
Since
4.2
By default, no options are set for the standard locales.
Definition at line 802 of file qlocale.cpp.
Referenced by QString::arg(), operator!=(), operator==(), and setDefault().
 {
     return static_cast<NumberOption>(p.numberOptions);
 }
operator!=()
bool QLocale::operator!= (const QLocale & other) const inline
Definition at line 822 of file qlocale.h.
     { return d() != other.d() || numberOptions() != other.numberOptions(); }
operator=()
QLocale & QLocale::operator= (const QLocale & other)
Assigns other to this QLocale object and returns a reference to this QLocale object.
Definition at line 771 of file qlocale.cpp.
 {
     v = other.v;
     return *this;
 }
operator==()
bool QLocale::operator== (const QLocale & other) const inline
Definition at line 820 of file qlocale.h.
     { return d() == other.d() && numberOptions() == other.numberOptions(); }
percent()
QChar QLocale::percent () const
Returns the percent character of this locale.
Since
4.1
Definition at line 1791 of file qlocale.cpp.
Referenced by QLocalePrivate::numberToCLocale().
 {
     return d()->percent();
 }
pmText()
QString QLocale::pmText () const
Returns the localized name of the "PM" suffix for times specified using the conventions of the 12-hour clock.
Since
4.5
See also
amText()
Definition at line 2376 of file qlocale.cpp.
Referenced by QLocalePrivate::dateTimeToString(), and QSystemLocale::query().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::PMText, QVariant());
         if (!res.isNull())
             return res.toString();
     }
 #endif
     return getLocaleData(pm_data + d()->m_pm_idx, d()->m_pm_size);
 }
positiveSign()
QChar QLocale::positiveSign () const
Returns the positive sign character of this locale.
Since
4.5
Definition at line 1830 of file qlocale.cpp.
Referenced by QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QTextStreamPrivate::putString(), and QSystemLocale::query().
 {
     return d()->plus();
 }
quoteString() [1/2]
QString QLocale::quoteString (const QString & str, QuotationStyle style = StandardQuotation) const
Returns str quoted according to the current locale using the given quotation style.
Since
4.8
Definition at line 816 of file qlocale.cpp.
 {
     return quoteString(&str, style);
 }
quoteString() [2/2]
QString QLocale::quoteString (const QStringRef & str, QuotationStyle style = StandardQuotation) const
Since
4.8
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 826 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res;
         if (style == QLocale::AlternateQuotation)
             res = systemLocale()->query(QSystemLocale::StringToAlternateQuotation, QVariant::fromValue(str));
         if (res.isNull() || style == QLocale::StandardQuotation)
             res = systemLocale()->query(QSystemLocale::StringToStandardQuotation, QVariant::fromValue(str));
         if (!res.isNull())
             return res.toString();
     }
 #endif
     if (style == QLocale::StandardQuotation)
         return QChar(d()->m_quotation_start) % str % QChar(d()->m_quotation_end);
     else
         return QChar(d()->m_alternate_quotation_start) % str % QChar(d()->m_alternate_quotation_end);
 }
script()
QLocale::Script QLocale::script () const
Returns the script of this locale.
Since
4.8
See also
language(), country(), languageToString(), scriptToString(), bcp47Name()
Definition at line 935 of file qlocale.cpp.
 {
     return Script(d()->m_script_id);
 }
scriptToString()
QString QLocale::scriptToString (QLocale::Script script) static
Returns a QString containing the name of script.
Since
4.8
See also
languageToString(), countryToString(), script(), bcp47Name()
Definition at line 1053 of file qlocale.cpp.
 {
     if (uint(script) > uint(QLocale::LastScript))
         return QLatin1String("Unknown");
     return QLatin1String(script_name_list + script_name_index[script]);
 }
setDefault()
void QLocale::setDefault (const QLocale & locale) static
Sets the global default locale to locale.
Note
This class or function is not reentrant.
These values are used when a QLocale object is constructed with no arguments. If this function is not called, the system's locale is used.
Warning
In a multithreaded application, the default locale should be set at application startup, before any non-GUI threads are created.
See also
system() c()
Definition at line 905 of file qlocale.cpp.
 {
     default_lp = locale.d();
     default_number_options = locale.numberOptions();
 #ifdef QT_USE_ICU
     qt_initIcu(locale.bcp47Name());
 #endif
 }
setNumberOptions()
void QLocale::setNumberOptions (NumberOptions options)
Sets the options related to number conversions for this QLocale instance.
Since
4.2
Definition at line 786 of file qlocale.cpp.
Referenced by QAbstractItemViewPrivate::viewOptionsV4().
 {
     p.numberOptions = options;
 }
standaloneDayName()
QString QLocale::standaloneDayName (int day, FormatType type = LongFormat) const
Returns the localized name of the day (where 1 represents Monday, 2 represents Tuesday and so on) that is used as a standalone text, in the format specified by type.
Since
4.5
If the locale information does not specify the standalone day name then return value is the same as in dayName().
See also
dayName(), standaloneMonthName()
Definition at line 2158 of file qlocale.cpp.
Referenced by QCalendarModel::dayName(), QDate::longDayName(), and QDate::shortDayName().
 {
     if (day < 1 || day > 7)
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(type == LongFormat
                                              ? QSystemLocale::DayNameLong : QSystemLocale::DayNameShort,
                                              day);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     if (day == 7)
         day = 0;
     quint32 idx, size;
     switch (type) {
     case QLocale::LongFormat:
         idx = d()->m_standalone_long_day_names_idx;
         size = d()->m_standalone_long_day_names_size;
         break;
     case QLocale::ShortFormat:
         idx = d()->m_standalone_short_day_names_idx;
         size = d()->m_standalone_short_day_names_size;
         break;
     case QLocale::NarrowFormat:
         idx = d()->m_standalone_narrow_day_names_idx;
         size = d()->m_standalone_narrow_day_names_size;
         break;
     default:
         return QString();
     }
     QString name = getLocaleListData(days_data + idx, size, day);
     if (name.isEmpty())
         return dayName(day == 0 ? 7 : day, type);
     return name;
 }
standaloneMonthName()
QString QLocale::standaloneMonthName (int month, FormatType type = LongFormat) const
Returns the localized name of month that is used as a standalone text, in the format specified by type.
Since
4.5
If the locale information doesn't specify the standalone month name then return value is the same as in monthName().
See also
monthName(), standaloneDayName()
Definition at line 2056 of file qlocale.cpp.
Referenced by QDate::longMonthName(), QCalendarWidget::minimumSizeHint(), QSystemLocale::query(), QDate::shortMonthName(), and QCalendarMonthValidator::text().
 {
     if (month < 1 || month > 12)
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(type == LongFormat
                                              ? QSystemLocale::StandaloneMonthNameLong : QSystemLocale::StandaloneMonthNameShort,
                                              month);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     quint32 idx, size;
     switch (type) {
     case QLocale::LongFormat:
         idx = d()->m_standalone_long_month_names_idx;
         size = d()->m_standalone_long_month_names_size;
         break;
     case QLocale::ShortFormat:
         idx = d()->m_standalone_short_month_names_idx;
         size = d()->m_standalone_short_month_names_size;
         break;
     case QLocale::NarrowFormat:
         idx = d()->m_standalone_narrow_month_names_idx;
         size = d()->m_standalone_narrow_month_names_size;
         break;
     default:
         return QString();
     }
     QString name = getLocaleListData(standalone_months_data + idx, size, month - 1);
     if (name.isEmpty())
         return monthName(month, type);
     return name;
 }
system()
QLocale QLocale::system () static
Returns a QLocale object initialized to the system locale.
On Windows and Mac, this locale will use the decimal/grouping characters and date/time formats specified in the system configuration panel.
See also
c()
Definition at line 1917 of file qlocale.cpp.
Referenced by QTextCodec::canEncode(), QDate::fromString(), QTime::fromString(), QDateTime::fromString(), QDate::longDayName(), QDate::longMonthName(), QHttpNetworkConnectionPrivate::prepareRequest(), QDateTimeParser::QDateTimeParser(), QPageSetupWidget::QPageSetupWidget(), QPageSetupWidget::selectPrinter(), QDate::shortDayName(), QDate::shortMonthName(), QDate::toString(), and QTime::toString().
 {
     QLocale result(C);
     result.p.index = localePrivateIndex(systemPrivate());
     return result;
 }
textDirection()
Qt::LayoutDirection QLocale::textDirection () const
Returns the text direction of the language.
Since
4.7
Definition at line 2286 of file qlocale.cpp.
Referenced by QXIMInputContext::QXIMInputContext().
 {
     Language lang = language();
     if (lang == QLocale::Arabic ||
         lang == QLocale::Hebrew ||
         lang == QLocale::Persian ||
         lang == QLocale::Urdu ||
         lang == QLocale::Syriac)
         return Qt::RightToLeft;
     return Qt::LeftToRight;
 }
timeFormat()
QString QLocale::timeFormat (FormatType format = LongFormat) const
Returns the time format used for the current locale.
Since
4.1
If format is LongFormat the format will be a long version. Otherwise it uses a shorter version.
See also
QTime::toString(), QTime::fromString()
Definition at line 1535 of file qlocale.cpp.
Referenced by dateTimeFormat(), QDateTimeEditPrivate::readLocaleSettings(), toString(), and toTime().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(format == LongFormat
                                              ? QSystemLocale::TimeFormatLong : QSystemLocale::TimeFormatShort,
                                              QVariant());
         if (!res.isNull())
             return res.toString();
     }
 #endif
     quint32 idx, size;
     switch (format) {
     case LongFormat:
         idx = d()->m_long_time_format_idx;
         size = d()->m_long_time_format_size;
         break;
     default:
         idx = d()->m_short_time_format_idx;
         size = d()->m_short_time_format_size;
         break;
     }
     return getLocaleData(time_format_data + idx, size);
 }
toCurrencyString() [1/8]
QString QLocale::toCurrencyString (qlonglong value, const QString & symbol = QString()) const
Returns a localized string representation of value as a currency.
Since
4.8
If the symbol is provided it is used instead of the default currency symbol.
See also
currencySymbol()
Definition at line 3309 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QSystemLocale::CurrencyToStringArgument arg(value, symbol);
         QVariant res = systemLocale()->query(QSystemLocale::CurrencyToString, QVariant::fromValue(arg));
         if (!res.isNull())
             return res.toString();
     }
 #endif
     const QLocalePrivate *d = this->d();
     quint8 idx = d->m_currency_format_idx;
     quint8 size = d->m_currency_format_size;
     if (d->m_currency_negative_format_size && value < 0) {
         idx = d->m_currency_negative_format_idx;
         size = d->m_currency_negative_format_size;
         value = -value;
     }
     QString str = d->longLongToString(value);
     QString sym = symbol.isNull() ? currencySymbol() : symbol;
     if (sym.isEmpty())
         sym = currencySymbol(QLocale::CurrencyIsoCode);
     QString format = getLocaleData(currency_format_data + idx, size);
     return format.arg(str, sym);
 }
toCurrencyString() [2/8]
QString QLocale::toCurrencyString (qulonglong value, const QString & symbol = QString()) const
Since
4.8 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 3339 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QSystemLocale::CurrencyToStringArgument arg(value, symbol);
         QVariant res = systemLocale()->query(QSystemLocale::CurrencyToString, QVariant::fromValue(arg));
         if (!res.isNull())
             return res.toString();
     }
 #endif
     const QLocalePrivate *d = this->d();
     quint8 idx = d->m_currency_format_idx;
     quint8 size = d->m_currency_format_size;
     QString str = d->unsLongLongToString(value);
     QString sym = symbol.isNull() ? currencySymbol() : symbol;
     if (sym.isEmpty())
         sym = currencySymbol(QLocale::CurrencyIsoCode);
     QString format = getLocaleData(currency_format_data + idx, size);
     return format.arg(str, sym);
 }
toCurrencyString() [3/8]
QString QLocale::toCurrencyString (short i, const QString & symbol = QString()) const inline
Definition at line 825 of file qlocale.h.
     { return toCurrencyString(qlonglong(i), symbol); }
toCurrencyString() [4/8]
QString QLocale::toCurrencyString (ushort i, const QString & symbol = QString()) const inline
Definition at line 827 of file qlocale.h.
     { return toCurrencyString(qulonglong(i), symbol); }
toCurrencyString() [5/8]
QString QLocale::toCurrencyString (int i, const QString & symbol = QString()) const inline
Definition at line 829 of file qlocale.h.
 { return toCurrencyString(qlonglong(i), symbol); }
toCurrencyString() [6/8]
QString QLocale::toCurrencyString (uint i, const QString & symbol = QString()) const inline
Definition at line 831 of file qlocale.h.
 { return toCurrencyString(qulonglong(i), symbol); }
toCurrencyString() [7/8]
QString QLocale::toCurrencyString (double value, const QString & symbol = QString()) const
Since
4.8 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 3364 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QSystemLocale::CurrencyToStringArgument arg(value, symbol);
         QVariant res = systemLocale()->query(QSystemLocale::CurrencyToString, QVariant::fromValue(arg));
         if (!res.isNull())
             return res.toString();
     }
 #endif
     const QLocalePrivate *d = this->d();
     quint8 idx = d->m_currency_format_idx;
     quint8 size = d->m_currency_format_size;
     if (d->m_currency_negative_format_size && value < 0) {
         idx = d->m_currency_negative_format_idx;
         size = d->m_currency_negative_format_size;
         value = -value;
     }
     QString str = d->doubleToString(value, d->m_currency_digits,
                                     QLocalePrivate::DFDecimal);
     QString sym = symbol.isNull() ? currencySymbol() : symbol;
     if (sym.isEmpty())
         sym = currencySymbol(QLocale::CurrencyIsoCode);
     QString format = getLocaleData(currency_format_data + idx, size);
     return format.arg(str, sym);
 }
toCurrencyString() [8/8]
QString QLocale::toCurrencyString (float i, const QString & symbol = QString()) const inline
Definition at line 833 of file qlocale.h.
 { return toCurrencyString(double(i), symbol); }
toDate() [1/2]
QDate QLocale::toDate (const QString & string, FormatType format = LongFormat) const
Parses the date string given in string and returns the date.
Since
4.4
The format of the date string is chosen according to the format parameter (see dateFormat()).
If the date could not be parsed, returns an invalid date.
See also
dateFormat(), toTime(), toDateTime(), QDate::fromString()
Definition at line 1627 of file qlocale.cpp.
 {
     return toDate(string, dateFormat(format));
 }
toDate() [2/2]
QDate QLocale::toDate (const QString & string, const QString & format) const
Parses the date string given in string and returns the date.
Since
4.4
See QDate::fromString() for information on the expressions that can be used with this function.
This function searches month names and the names of the days of the week in the current locale.
If the date could not be parsed, returns an invalid date.
See also
dateFormat(), toTime(), toDateTime(), QDate::fromString()
Definition at line 1704 of file qlocale.cpp.
 {
     QDate date;
 #ifndef QT_BOOTSTRAPPED
     QDateTimeParser dt(QVariant::Date, QDateTimeParser::FromString);
     dt.defaultLocale = *this;
     if (dt.parseFormat(format))
         dt.fromString(string, &date, 0);
 #else
     Q_UNUSED(string);
     Q_UNUSED(format);
 #endif
     return date;
 }
toDateTime() [1/2]
QDateTime QLocale::toDateTime (const QString & string, FormatType format = LongFormat) const
Parses the date/time string given in string and returns the time.
Since
4.4
The format of the date/time string is chosen according to the format parameter (see dateTimeFormat()).
If the string could not be parsed, returns an invalid QDateTime.
See also
dateTimeFormat(), toTime(), toDate(), QDateTime::fromString()
Definition at line 1649 of file qlocale.cpp.
Referenced by _q_parseDosDir(), _q_parseUnixDir(), and QNetworkHeadersPrivate::fromHttpDate().
 {
     return toDateTime(string, dateTimeFormat(format));
 }
toDateTime() [2/2]
QDateTime QLocale::toDateTime (const QString & string, const QString & format) const
Parses the date/time string given in string and returns the time.
Since
4.4
See QDateTime::fromString() for information on the expressions that can be used with this function.
Note
The month and day names used must be given in the user's local language.
If the string could not be parsed, returns an invalid QDateTime.
See also
dateTimeFormat(), toTime(), toDate(), QDateTime::fromString()
Definition at line 1738 of file qlocale.cpp.
 {
 #ifndef QT_BOOTSTRAPPED
     QTime time;
     QDate date;
     QDateTimeParser dt(QVariant::DateTime, QDateTimeParser::FromString);
     dt.defaultLocale = *this;
     if (dt.parseFormat(format) && dt.fromString(string, &date, &time))
         return QDateTime(date, time);
 #else
     Q_UNUSED(string);
     Q_UNUSED(format);
 #endif
     return QDateTime(QDate(), QTime(-1, -1, -1));
 }
toDouble()
double QLocale::toDouble (const QString & s, bool * ok = 0) const
Returns the double represented by the localized string s, or 0.0 if the conversion failed.
If ok is not 0, reports failure by setting ok to false and success by setting *ok to true.
Unlike QString::toDouble(), this function does not fall back to the "C" locale if the string cannot be interpreted in this locale.
bool ok;
double d;
QLocale c(QLocale::C);
d = c.toDouble("1234.56", &ok);  // ok == true, d == 1234.56
d = c.toDouble("1,234.56", &ok); // ok == true, d == 1234.56
d = c.toDouble("1234,56", &ok);  // ok == false
QLocale german(QLocale::German);
d = german.toDouble("1234,56", &ok);  // ok == true, d == 1234.56
d = german.toDouble("1.234,56", &ok); // ok == true, d == 1234.56
d = german.toDouble("1234.56", &ok);  // ok == false
d = german.toDouble("1.234", &ok);    // ok == true, d == 1234.0
Notice that the last conversion returns 1234.0, because '.' is the thousands group separator in the German locale.
This function ignores leading and trailing whitespace.
See also
toFloat(), toInt(), toString()
Definition at line 1279 of file qlocale.cpp.
Referenced by QTextStreamPrivate::getReal(), toFloat(), and QDoubleSpinBoxPrivate::validateAndInterpret().
 {
     QLocalePrivate::GroupSeparatorMode mode
         = p.numberOptions & RejectGroupSeparator
             ? QLocalePrivate::FailOnGroupSeparators
             : QLocalePrivate::ParseGroupSeparators;
     return d()->stringToDouble(s, ok, mode);
 }
toFloat()
float QLocale::toFloat (const QString & s, bool * ok = 0) const
Definition at line 1244 of file qlocale.cpp.
 {
     bool myOk;
     double d = toDouble(s, &myOk);
     if (!myOk || d > QT_MAX_FLOAT || d < -QT_MAX_FLOAT) {
         if (ok != 0)
             *ok = false;
         return 0.0;
     }
     if (ok != 0)
         *ok = true;
     return float(d);
 }
toInt()
int QLocale::toInt (const QString & s, bool * ok = 0, int base = 0) const
Returns the int represented by the localized string s, using base base.
If base is 0 the base is determined automatically using the following rules: If the string begins with "0x", it is assumed to be hexadecimal; if it begins with "0", it is assumed to be octal; otherwise it is assumed to be decimal.
If the conversion fails the function returns 0.
If ok is not 0, failure is reported by setting *ok to false, and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toUInt(), toString()
Definition at line 1133 of file qlocale.cpp.
Referenced by QIntValidator::validate(), and QSpinBoxPrivate::validateAndInterpret().
 {
     qlonglong i = toLongLong(s, ok, base);
     if (i < INT_MIN || i > INT_MAX) {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     return int(i);
 }
toLongLong()
qlonglong QLocale::toLongLong (const QString & s, bool * ok = 0, int base = 0) const
Returns the long long int represented by the localized string s, using base base.
If base is 0 the base is determined automatically using the following rules: If the string begins with "0x", it is assumed to be hexadecimal; if it begins with "0", it is assumed to be octal; otherwise it is assumed to be decimal.
If the conversion fails the function returns 0.
If ok is not 0, failure is reported by setting *ok to false, and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toInt(), toULongLong(), toDouble(), toString()
Definition at line 1190 of file qlocale.cpp.
Referenced by toInt(), and toShort().
 {
     QLocalePrivate::GroupSeparatorMode mode
         = p.numberOptions & RejectGroupSeparator
             ? QLocalePrivate::FailOnGroupSeparators
             : QLocalePrivate::ParseGroupSeparators;
     return d()->stringToLongLong(s, base, ok, mode);
 }
toLower()
QString QLocale::toLower (const QString & str) const
Returns a lowercase copy of str.
Since
4.8
Definition at line 2328 of file qlocale.cpp.
 {
 #ifdef QT_USE_ICU
     {
         QString result;
         if (qt_u_strToLower(str, &result, *this))
             return result;
         // else fall through and use Qt's toUpper
     }
 #endif
     return str.toLower();
 }
toShort()
short QLocale::toShort (const QString & s, bool * ok = 0, int base = 0) const
Returns the short int represented by the localized string s, using base base.
If base is 0 the base is determined automatically using the following rules: If the string begins with "0x", it is assumed to be hexadecimal; if it begins with "0", it is assumed to be octal; otherwise it is assumed to be decimal.
If the conversion fails the function returns 0.
If ok is not 0, failure is reported by setting *ok to false, and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toUShort(), toString()
Definition at line 1077 of file qlocale.cpp.
 {
     qlonglong i = toLongLong(s, ok, base);
     if (i < SHRT_MIN || i > SHRT_MAX) {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     return short(i);
 }
toString() [1/14]
QString QLocale::toString (qlonglong i) const
Returns a localized string representation of i.
See also
toLongLong()
Definition at line 1295 of file qlocale.cpp.
Referenced by QStyledItemDelegate::displayText(), QIntValidator::fixup(), QSystemLocale::query(), QDateTimeEdit::textFromDateTime(), QSpinBox::textFromValue(), QDoubleSpinBox::textFromValue(), QNetworkHeadersPrivate::toHttpDate(), QNetworkCookie::toRawForm(), QDate::toString(), QTime::toString(), toString(), and QItemDelegatePrivate::valueToText().
 {
     int flags = p.numberOptions & OmitGroupSeparator
                     ? 0
                     : QLocalePrivate::ThousandsGroup;
     return d()->longLongToString(i, -1, 10, -1, flags);
 }
toString() [2/14]
QString QLocale::toString (qulonglong i) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
toULongLong()
Definition at line 1310 of file qlocale.cpp.
 {
     int flags = p.numberOptions & OmitGroupSeparator
                     ? 0
                     : QLocalePrivate::ThousandsGroup;
     return d()->unsLongLongToString(i, -1, 10, -1, flags);
 }
toString() [3/14]
QString QLocale::toString (short i) const inline
Definition at line 810 of file qlocale.h.
     { return toString(qlonglong(i)); }
toString() [4/14]
QString QLocale::toString (ushort i) const inline
Definition at line 812 of file qlocale.h.
     { return toString(qulonglong(i)); }
toString() [5/14]
QString QLocale::toString (int i) const inline
Definition at line 814 of file qlocale.h.
     { return toString(qlonglong(i)); }
toString() [6/14]
QString QLocale::toString (uint i) const inline
Definition at line 816 of file qlocale.h.
     { return toString(qulonglong(i)); }
toString() [7/14]
QString QLocale::toString (double i, char f = 'g', int prec = 6) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.f and prec have the same meaning as in QString::number(double, char, int).
See also
toDouble()
Definition at line 1869 of file qlocale.cpp.
 {
     QLocalePrivate::DoubleForm form = QLocalePrivate::DFDecimal;
     uint flags = 0;
     if (qIsUpper(f))
         flags = QLocalePrivate::CapitalEorX;
     f = qToLower(f);
     switch (f) {
         case 'f':
             form = QLocalePrivate::DFDecimal;
             break;
         case 'e':
             form = QLocalePrivate::DFExponent;
             break;
         case 'g':
             form = QLocalePrivate::DFSignificantDigits;
             break;
         default:
             break;
     }
     if (!(p.numberOptions & OmitGroupSeparator))
         flags |= QLocalePrivate::ThousandsGroup;
     return d()->doubleToString(i, prec, form, -1, flags);
 }
toString() [8/14]
QString QLocale::toString (float i, char f = 'g', int prec = 6) const inline
Definition at line 818 of file qlocale.h.
     { return toString(double(i), f, prec); }
toString() [9/14]
QString QLocale::toString (const QDate & date, const QString & format) const
Returns a localized string representation of the given date in the specified format.
If format is an empty string, an empty string is returned.
Definition at line 1325 of file qlocale.cpp.
 {
     return d()->dateTimeToString(format, &date, 0, this);
 }
toString() [10/14]
QString QLocale::toString (const QDate & date, FormatType format = LongFormat) const
Returns a localized string representation of the given date according to the specified format.
Definition at line 1335 of file qlocale.cpp.
 {
     if (!date.isValid())
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(format == LongFormat
                                              ? QSystemLocale::DateToStringLong : QSystemLocale::DateToStringShort,
                                              date);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     QString format_str = dateFormat(format);
     return toString(date, format_str);
 }
toString() [11/14]
QString QLocale::toString (const QTime & time, const QString & format) const
Returns a localized string representation of the given time according to the specified format.
If format is an empty string, an empty string is returned.
Definition at line 1403 of file qlocale.cpp.
 {
     return d()->dateTimeToString(format, 0, &time, this);
 }
toString() [12/14]
QString QLocale::toString (const QTime & time, FormatType format = LongFormat) const
Returns a localized string representation of the given time in the specified format.
Definition at line 1462 of file qlocale.cpp.
 {
     if (!time.isValid())
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(format == LongFormat
                                              ? QSystemLocale::TimeToStringLong : QSystemLocale::TimeToStringShort,
                                              time);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     QString format_str = timeFormat(format);
     return toString(time, format_str);
 }
toString() [13/14]
QString QLocale::toString (const QDateTime & dateTime, FormatType format = LongFormat) const
Returns a localized string representation of the given dateTime according to the specified format.
Since
4.4
Definition at line 1436 of file qlocale.cpp.
 {
     if (!dateTime.isValid())
         return QString();
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(format == LongFormat
                                              ? QSystemLocale::DateTimeToStringLong
                                              : QSystemLocale::DateTimeToStringShort,
                                              dateTime);
         if (!res.isNull())
             return res.toString();
     }
 #endif
     const QString format_str = dateTimeFormat(format);
     return toString(dateTime, format_str);
 }
toString() [14/14]
QString QLocale::toString (const QDateTime & dateTime, const QString & format) const
Returns a localized string representation of the given dateTime according to the specified format.
Since
4.4
If format is an empty string, an empty string is returned.
Definition at line 1419 of file qlocale.cpp.
 {
     const QDate dt = dateTime.date();
     const QTime tm = dateTime.time();
     return d()->dateTimeToString(format, &dt, &tm, this);
 }
toTime() [1/2]
QTime QLocale::toTime (const QString & string, FormatType format = LongFormat) const
Parses the time string given in string and returns the time.
Since
4.4
The format of the time string is chosen according to the format parameter (see timeFormat()).
If the time could not be parsed, returns an invalid time.
See also
timeFormat(), toDate(), toDateTime(), QTime::fromString()
Definition at line 1606 of file qlocale.cpp.
 {
     return toTime(string, timeFormat(format));
 }
toTime() [2/2]
QTime QLocale::toTime (const QString & string, const QString & format) const
Parses the time string given in string and returns the time.
Since
4.4
See QTime::fromString() for information on what is a valid format string.
If the time could not be parsed, returns an invalid time.
See also
timeFormat(), toDate(), toDateTime(), QTime::fromString()
Definition at line 1670 of file qlocale.cpp.
 {
     QTime time;
 #ifndef QT_BOOTSTRAPPED
     QDateTimeParser dt(QVariant::Time, QDateTimeParser::FromString);
     dt.defaultLocale = *this;
     if (dt.parseFormat(format))
         dt.fromString(string, 0, &time);
 #else
     Q_UNUSED(string);
     Q_UNUSED(format);
 #endif
     return time;
 }
toUInt()
uint QLocale::toUInt (const QString & s, bool * ok = 0, int base = 0) const
Returns the unsigned int represented by the localized string s, using base base.
If base is 0 the base is determined automatically using the following rules: If the string begins with "0x", it is assumed to be hexadecimal; if it begins with "0", it is assumed to be octal; otherwise it is assumed to be decimal.
If the conversion fails the function returns 0.
If ok is not 0, failure is reported by setting *ok to false, and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toInt(), toString()
Definition at line 1161 of file qlocale.cpp.
Referenced by QDateTimeParser::parseSection().
 {
     qulonglong i = toULongLong(s, ok, base);
     if (i > UINT_MAX) {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     return uint(i);
 }
toULongLong()
qlonglong QLocale::toULongLong (const QString & s, bool * ok = 0, int base = 0) const
Returns the unsigned long long int represented by the localized string s, using base base.
If base is 0 the base is determined automatically using the following rules: If the string begins with "0x", it is assumed to be hexadecimal; if it begins with "0", it is assumed to be octal; otherwise it is assumed to be decimal.
If the conversion fails the function returns 0.
If ok is not 0, failure is reported by setting *ok to false, and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toLongLong(), toInt(), toDouble(), toString()
Definition at line 1220 of file qlocale.cpp.
Referenced by toUInt(), and toUShort().
 {
     QLocalePrivate::GroupSeparatorMode mode
         = p.numberOptions & RejectGroupSeparator
             ? QLocalePrivate::FailOnGroupSeparators
             : QLocalePrivate::ParseGroupSeparators;
     return d()->stringToUnsLongLong(s, base, ok, mode);
 }
toUpper()
QString QLocale::toUpper (const QString & str) const
Returns an uppercase copy of str.
Since
4.8
Definition at line 2307 of file qlocale.cpp.
 {
 #ifdef QT_USE_ICU
     {
         QString result;
         if (qt_u_strToUpper(str, &result, *this))
             return result;
         // else fall through and use Qt's toUpper
     }
 #endif
     return str.toUpper();
 }
toUShort()
ushort QLocale::toUShort (const QString & s, bool * ok = 0, int base = 0) const
Returns the unsigned short int represented by the localized string s, using base base.
If base is 0 the base is determined automatically using the following rules: If the string begins with "0x", it is assumed to be hexadecimal; if it begins with "0", it is assumed to be octal; otherwise it is assumed to be decimal.
If the conversion fails the function returns 0.
If ok is not 0, failure is reported by setting *ok to false, and success by setting *ok to true.
This function ignores leading and trailing whitespace.
See also
toShort(), toString()
Definition at line 1105 of file qlocale.cpp.
 {
     qulonglong i = toULongLong(s, ok, base);
     if (i > USHRT_MAX) {
         if (ok != 0)
             *ok = false;
         return 0;
     }
     return ushort(i);
 }
uiLanguages()
QStringList QLocale::uiLanguages () const
Returns an ordered list of locale names for translation purposes in preference order.
Since
4.8
The return value represents locale names that the user expects to see the UI translation in.
Most like you do not need to use this function directly, but just pass the QLocale object to the QTranslator::load() function.
The first item in the list is the most preferred one.
See also
QTranslator, bcp47Name()
Definition at line 3410 of file qlocale.cpp.
Referenced by find_translation().
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::UILanguages, QVariant());
         if (!res.isNull()) {
             QStringList result = res.toStringList();
             if (!result.isEmpty())
                 return result;
         }
     }
 #endif
     return QStringList(bcp47Name());
 }
weekdays()
QList< Qt::DayOfWeek > QLocale::weekdays () const
Returns a list of days that are considered weekdays according to the current locale.
Since
4.8
Definition at line 2237 of file qlocale.cpp.
 {
 #ifndef QT_NO_SYSTEMLOCALE
     if (d() == systemPrivate()) {
         QVariant res = systemLocale()->query(QSystemLocale::Weekdays, QVariant());
         if (!res.isNull())
             return static_cast<QList<Qt::DayOfWeek> >(res.value<QList<Qt::DayOfWeek> >());
     }
 #endif
     QList<Qt::DayOfWeek> weekdays;
     quint16 weekendStart = d()->m_weekend_start;
     quint16 weekendEnd = d()->m_weekend_end;
     for (int day = Qt::Monday; day <= Qt::Sunday; day++) {
         if ((weekendEnd >= weekendStart && (day < weekendStart || day > weekendEnd)) ||
             (weekendEnd < weekendStart && (day > weekendEnd && day < weekendStart)))
                 weekdays << static_cast<Qt::DayOfWeek>(day);
     }
     return weekdays;
 }
zeroDigit()
QChar QLocale::zeroDigit () const
Returns the zero digit character of this locale.
Since
4.1
Definition at line 1804 of file qlocale.cpp.
Referenced by QSystemLocale::query().
 {
     return d()->zero();
 }
Friends and Related Functions
QByteArray
friend class QByteArray friend
Definition at line 139 of file qlocale.h.
QDoubleValidatorPrivate
friend class QDoubleValidatorPrivate friend
Definition at line 141 of file qlocale.h.
QIntValidator
friend class QIntValidator friend
Definition at line 140 of file qlocale.h.
QLocalePrivate
friend struct QLocalePrivate friend
Definition at line 798 of file qlocale.h.
QString
friend class QString friend
Definition at line 138 of file qlocale.h.
Referenced by createSeparatedList(), currencySymbol(), QLocalePrivate::dateTimeToString(), dayName(), monthName(), name(), standaloneDayName(), standaloneMonthName(), timeZone(), and toString().
QTextStream
friend class QTextStream friend
Definition at line 142 of file qlocale.h.
QTextStreamPrivate
friend class QTextStreamPrivate friend
Definition at line 143 of file qlocale.h.
Properties
@62
union { ... }
p
Data QLocale::p
Definition at line 803 of file qlocale.h.
Referenced by d(), matchingLocales(), numberOptions(), QLocale(), setNumberOptions(), system(), toDouble(), toLongLong(), toString(), and toULongLong().
v
void* QLocale::v
Definition at line 802 of file qlocale.h.
Referenced by operator=(), and QLocale().
The documentation for this class was generated from the following files:
/src/corelib/tools/qlocale.h
/src/corelib/tools/qlocale.cpp