Qt 4.8: QWaylandBuffer Class Reference
QWaylandBuffer Class Reference abstract
#include <qwaylandbuffer.h>
Public Functions
wl_buffer * buffer ()
QWaylandBuffer ()
virtual QSize size () const =0
virtual ~QWaylandBuffer ()
Protected Variables
struct wl_buffer * mBuffer
Detailed Description
Definition at line 50 of file qwaylandbuffer.h.
Constructors and Destructors
QWaylandBuffer()
QWaylandBuffer::QWaylandBuffer () inline
Definition at line 52 of file qwaylandbuffer.h.
 { }
~QWaylandBuffer()
virtual QWaylandBuffer::~QWaylandBuffer () inline virtual
Definition at line 53 of file qwaylandbuffer.h.
 { }
Functions
buffer()
wl_buffer* QWaylandBuffer::buffer () inline
Definition at line 54 of file qwaylandbuffer.h.
Referenced by QWaylandInputDevice::attach(), QWaylandWindow::attach(), QWaylandShmWindowSurface::flush(), and QWaylandWindow::newSurfaceCreated().
 {return mBuffer;}
size()
virtual QSize QWaylandBuffer::size () const pure virtual
Implemented in QWaylandShmBuffer, and QWaylandXCompositeBuffer.
Referenced by buffer(), and QWaylandWindow::newSurfaceCreated().
Properties
mBuffer
struct wl_buffer* QWaylandBuffer::mBuffer protected
Definition at line 58 of file qwaylandbuffer.h.
Referenced by buffer(), QWaylandShmBuffer::QWaylandShmBuffer(), QWaylandXCompositeBuffer::QWaylandXCompositeBuffer(), and QWaylandShmBuffer::~QWaylandShmBuffer().
The documentation for this class was generated from the following file:
/src/plugins/platforms/wayland/qwaylandbuffer.h