Qt 4.8: QDir Class Reference
QDir Class Reference
The QDir class provides access to directory structures and their contents.
#include <qdir.h>
Public Types
enum Filter {
Dirs = 0x001, Files = 0x002, Drives = 0x004, NoSymLinks = 0x008,
AllEntries = Dirs | Files | Drives, TypeMask = 0x00f, Readable = 0x010, Writable = 0x020,
Executable = 0x040, PermissionMask = 0x070, Modified = 0x080, Hidden = 0x100,
System = 0x200, AccessMask = 0x3F0, AllDirs = 0x400, CaseSensitive = 0x800,
NoDotAndDotDot = 0x1000, NoDot = 0x2000, NoDotDot = 0x4000, NoFilter = -1
}
This enum describes the filtering options available to QDir; e.
enum SortFlag {
Name = 0x00, Time = 0x01, Size = 0x02, Unsorted = 0x03,
SortByMask = 0x03, DirsFirst = 0x04, Reversed = 0x08, IgnoreCase = 0x10,
DirsLast = 0x20, LocaleAware = 0x40, Type = 0x80, NoSort = -1
}
This enum describes the sort options available to QDir, e.
Public Functions
QString absoluteFilePath (const QString &fileName) const
Returns the absolute path name of a file in the directory.
QString absolutePath () const
Returns the absolute path (a path that starts with "/" or with a drive specification), which may contain symbolic links, but never contains redundant ".", ".." or multiple separators.
QString canonicalPath () const
Returns the canonical path, i.e.
bool cd (const QString &dirName)
Changes the QDir's directory to dirName.
bool cdUp ()
Changes directory by moving one directory up from the QDir's current directory.
uint count () const
Returns the total number of directories and files in the directory.
QString dirName () const
Returns the name of the directory; this is not the same as the path, e.g.
QFileInfoList entryInfoList (Filters filters=NoFilter, SortFlags sort=NoSort) const
Returns a list of QFileInfo objects for all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
QFileInfoList entryInfoList (const QStringList &nameFilters, Filters filters=NoFilter, SortFlags sort=NoSort) const
Returns a list of QFileInfo objects for all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
QStringList entryList (Filters filters=NoFilter, SortFlags sort=NoSort) const
Returns a list of the names of all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
QStringList entryList (const QStringList &nameFilters, Filters filters=NoFilter, SortFlags sort=NoSort) const
Returns a list of the names of all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
bool exists () const
Returns true if the directory exists; otherwise returns false.
bool exists (const QString &name) const
Returns true if the file called name exists; otherwise returns false.
QString filePath (const QString &fileName) const
Returns the path name of a file in the directory.
Filters filter () const
Returns the value set by setFilter()
bool isAbsolute () const
Returns true if the directory's path is absolute; otherwise returns false.
bool isReadable () const
Returns true if the directory is readable and we can open files by name; otherwise returns false.
bool isRelative () const
Returns true if the directory path is relative; otherwise returns false.
bool isRoot () const
Returns true if the directory is the root directory; otherwise returns false.
bool makeAbsolute ()
Converts the directory path to an absolute path.
bool mkdir (const QString &dirName) const
Creates a sub-directory called dirName.
bool mkpath (const QString &dirPath) const
Creates the directory path dirPath.
QStringList nameFilters () const
Returns the string list set by setNameFilters()
bool operator!= (const QDir &dir) const
Returns true if directory dir and this directory have different paths or different sort or filter settings; otherwise returns false.
QDir & operator= (const QDir &)
Makes a copy of the dir object and assigns it to this QDir object.
QDir & operator= (const QString &path)
Sets the directory path to the given path.
bool operator== (const QDir &dir) const
Returns true if directory dir and this directory have the same path and their sort and filter settings are the same; otherwise returns false.
QString operator[] (int) const
Returns the file name at position pos in the list of file names.
QString path () const
Returns the path.
QDir (const QDir &)
Constructs a QDir object that is a copy of the QDir object for directory dir.
QDir (const QString &path=QString())
Constructs a QDir pointing to the given directory path.
QDir (const QString &path, const QString &nameFilter, SortFlags sort=SortFlags(Name|IgnoreCase), Filters filter=AllEntries)
Constructs a QDir with path path, that filters its entries by name using nameFilter and by attributes using filters.
void refresh () const
Refreshes the directory information.
QString relativeFilePath (const QString &fileName) const
Returns the path to fileName relative to the directory.
bool remove (const QString &fileName)
Removes the file, fileName.
bool rename (const QString &oldName, const QString &newName)
Renames a file or directory from oldName to newName, and returns true if successful; otherwise returns false.
bool rmdir (const QString &dirName) const
Removes the directory specified by dirName.
bool rmpath (const QString &dirPath) const
Removes the directory path dirPath.
void setFilter (Filters filter)
Sets the filter used by entryList() and entryInfoList() to filters.
void setNameFilters (const QStringList &nameFilters)
Sets the name filters used by entryList() and entryInfoList() to the list of filters specified by nameFilters.
void setPath (const QString &path)
Sets the path of the directory to path.
void setSorting (SortFlags sort)
Sets the sort order used by entryList() and entryInfoList().
SortFlags sorting () const
Returns the value set by setSorting()
~QDir ()
Destroys the QDir object frees up its resources.
Static Public Functions
static void addResourceSearchPath (const QString &path)
Use QDir::addSearchPath() with a prefix instead.
static void addSearchPath (const QString &prefix, const QString &path)
static QString cleanPath (const QString &path)
Removes all multiple directory separators "/" and resolves any "."s or ".."s found in the path, path.
static QT_DEPRECATED QString convertSeparators (const QString &pathName)
Use QDir::toNativeSeparators() instead.
static QDir current ()
Returns the application's current directory.
static QString currentPath ()
Returns the absolute path of the application's current directory.
static QFileInfoList drives ()
Returns a list of the root directories on this system.
static QString fromNativeSeparators (const QString &pathName)
Returns pathName using '/' as file separator.
static QDir home ()
Returns the user's home directory.
static QString homePath ()
Returns the absolute path of the user's home directory.
static bool isAbsolutePath (const QString &path)
Returns true if path is absolute; returns false if it is relative.
static bool isRelativePath (const QString &path)
Returns true if path is relative; returns false if it is absolute.
static bool match (const QStringList &filters, const QString &fileName)
Returns true if the fileName matches any of the wildcard (glob) patterns in the list of filters; otherwise returns false.
static bool match (const QString &filter, const QString &fileName)
Returns true if the fileName matches the wildcard (glob) pattern filter; otherwise returns false.
static QStringList nameFiltersFromString (const QString &nameFilter)
Returns a list of name filters from the given nameFilter.
static QDir root ()
Returns the root directory.
static QString rootPath ()
Returns the absolute path of the root directory.
static QStringList searchPaths (const QString &prefix)
static QChar separator ()
Returns the native directory separator: "/" under Unix (including Mac OS X) and "\\" under Windows.
static bool setCurrent (const QString &path)
Sets the application's current working directory to path.
static void setSearchPaths (const QString &prefix, const QStringList &searchPaths)
static QDir temp ()
Returns the system's temporary directory.
static QString tempPath ()
Returns the absolute path of the system's temporary directory.
static QString toNativeSeparators (const QString &pathName)
Returns pathName with the '/' separators converted to separators that are appropriate for the underlying operating system.
Protected Variables
QSharedDataPointer< QDirPrivate > d_ptr
Detailed Description
The QDir class provides access to directory structures and their contents.
Note
This class or function is reentrant.
A QDir is used to manipulate path names, access information regarding paths and files, and manipulate the underlying file system. It can also be used to access Qt's resource system.
Qt uses "/" as a universal directory separator in the same way that "/" is used as a path separator in URLs. If you always use "/" as a directory separator, Qt will translate your paths to conform to the underlying operating system.
A QDir can point to a file using either a relative or an absolute path. Absolute paths begin with the directory separator (optionally preceded by a drive specification under Windows). Relative file names begin with a directory name or a file name and specify a path relative to the current directory.
Examples of absolute paths:
QDir("/home/user/Documents")
QDir("C:/Documents and Settings")
On Windows, the second example above will be translated to C:/Documents and Settings when used to access files.
Examples of relative paths:
QDir("images/landscape.png")
You can use the isRelative() or isAbsolute() functions to check if a QDir is using a relative or an absolute file path. Call makeAbsolute() to convert a relative QDir to an absolute one.
Navigation and Directory Operations
A directory's path can be obtained with the path() function, and a new path set with the setPath() function. The absolute path to a directory is found by calling absolutePath().
The name of a directory is found using the dirName() function. This typically returns the last element in the absolute path that specifies the location of the directory. However, it can also return "." if the QDir represents the current directory.
QDir("Documents/Letters/Applications").dirName() // "Applications"
QDir().dirName()                                 // "."
The path for a directory can also be changed with the cd() and cdUp() functions, both of which operate like familiar shell commands. When cd() is called with the name of an existing directory, the QDir object changes directory so that it represents that directory instead. The cdUp() function changes the directory of the QDir object so that it refers to its parent directory; i.e. cd("..") is equivalent to cdUp().
Directories can be created with mkdir(), renamed with rename(), and removed with rmdir().
You can test for the presence of a directory with a given name by using exists(), and the properties of a directory can be tested with isReadable(), isAbsolute(), isRelative(), and isRoot().
The refresh() function re-reads the directory's data from disk.
Files and Directory Contents
Directories contain a number of entries, representing files, directories, and symbolic links. The number of entries in a directory is returned by count(). A string list of the names of all the entries in a directory can be obtained with entryList(). If you need information about each entry, use entryInfoList() to obtain a list of QFileInfo objects.
Paths to files and directories within a directory can be constructed using filePath() and absoluteFilePath(). The filePath() function returns a path to the specified file or directory relative to the path of the QDir object; absoluteFilePath() returns an absolute path to the specified file or directory. Neither of these functions checks for the existence of files or directory; they only construct paths.
QDir directory("Documents/Letters");
QString path = directory.filePath("contents.txt");
QString absolutePath = directory.absoluteFilePath("contents.txt");
Files can be removed by using the remove() function. Directories cannot be removed in the same way as files; use rmdir() to remove them instead.
It is possible to reduce the number of entries returned by entryList() and entryInfoList() by applying filters to a QDir object. You can apply a name filter to specify a pattern with wildcards that file names need to match, an attribute filter that selects properties of entries and can distinguish between files and directories, and a sort order.
Name filters are lists of strings that are passed to setNameFilters(). Attribute filters consist of a bitwise OR combination of Filters, and these are specified when calling setFilter(). The sort order is specified using setSorting() with a bitwise OR combination of SortFlags.
You can test to see if a filename matches a filter using the match() function.
Filter and sort order flags may also be specified when calling entryList() and entryInfoList() in order to override previously defined behavior.
The Current Directory and Other Special Paths
Access to some common directories is provided with a number of static functions that return QDir objects. There are also corresponding functions for these that return strings:
QDir QString Return Value
current() currentPath() The application's working directory
home() homePath() The user's home directory
root() rootPath() The root directory
temp() tempPath() The system's temporary directory
The setCurrent() static function can also be used to set the application's working directory.
If you want to find the directory containing the application's executable, see QCoreApplication::applicationDirPath().
The drives() static function provides a list of root directories for each device that contains a filing system. On Unix systems this returns a list containing a single root directory "/"; on Windows the list will usually contain C:/, and possibly other drive letters such as D:/, depending on the configuration of the user's system.
Path Manipulation and Strings
Paths containing "." elements that reference the current directory at that point in the path, ".." elements that reference the parent directory, and symbolic links can be reduced to a canonical form using the canonicalPath() function.
Paths can also be simplified by using cleanPath() to remove redundant "/" and ".." elements.
It is sometimes necessary to be able to show a path in the native representation for the user's platform. The static toNativeSeparators() function returns a copy of the specified path in which each directory separator is replaced by the appropriate separator for the underlying operating system.
Examples
Check if a directory exists:
QDir dir("example");
if (!dir.exists())
    qWarning("Cannot find the example directory");
(We could also use the static convenience function QFile::exists().)
Traversing directories and reading a file:
QDir dir = QDir::root();                 // "/"
if (!dir.cd("tmp")) {                    // "/tmp"
    qWarning("Cannot find the \"/tmp\" directory");
} else {
    QFile file(dir.filePath("ex1.txt")); // "/tmp/ex1.txt"
    if (!file.open(QIODevice::ReadWrite))
        qWarning("Cannot create the file %s", file.name());
}
A program that lists all the files in the current directory (excluding symbolic links), sorted by size, smallest first:
#include <QDir>
#include <iostream>
int main(int argc, char *argv[])
{
    QCoreApplication app(argc, argv);
    QDir dir;
    dir.setFilter(QDir::Files | QDir::Hidden | QDir::NoSymLinks);
    dir.setSorting(QDir::Size | QDir::Reversed);
    QFileInfoList list = dir.entryInfoList();
    std::cout << "     Bytes Filename" << std::endl;
    for (int i = 0; i < list.size(); ++i) {
        QFileInfo fileInfo = list.at(i);
        std::cout << qPrintable(QString("%1 %2").arg(fileInfo.size(), 10)
                                                .arg(fileInfo.fileName()));
        std::cout << std::endl;
    }
    return 0;
}
See also
QFileInfo, QFile, QFileDialog, QApplication::applicationDirPath(), {Find Files Example}
Definition at line 58 of file qdir.h.
Enumerations
Filter
enum QDir::Filter
This enum describes the filtering options available to QDir; e.
g. for entryList() and entryInfoList(). The filter value is specified by combining values from the following list using the bitwise OR operator:
Dirs List directories that match the filters.
AllDirs List all directories; i.e. don't apply the filters to directory names.
Files List files.
Drives List disk drives (ignored under Unix).
NoSymLinks Do not list symbolic links (ignored by operating systems that don't support symbolic links).
NoDotAndDotDot Do not list the special entries "." and "..".
NoDot Do not list the special entry ".".
NoDotDot Do not list the special entry "..".
AllEntries List directories, files, drives and symlinks (this does not list broken symlinks unless you specify System).
Readable List files for which the application has read access. The Readable value needs to be combined with Dirs or Files.
Writable List files for which the application has write access. The Writable value needs to be combined with Dirs or Files.
Executable List files for which the application has execute access. The Executable value needs to be combined with Dirs or Files.
Modified Only list files that have been modified (ignored on Unix).
Hidden List hidden files (on Unix, files starting with a ".").
System List system files (on Unix, FIFOs, sockets and device files are included; on Windows, {.lnk} files are included)
CaseSensitive The filter should be case sensitive.
DefaultFilter
TypeMask
All
RWEMask
AccessMask
PermissionMask
NoFilter
Functions that use Filter enum values to filter lists of files and directories will include symbolic links to files and directories unless you set the NoSymLinks value.
A default constructed QDir will not filter out files based on their permissions, so entryList() and entryInfoList() will return all files that are readable, writable, executable, or any combination of the three. This makes the default easy to write, and at the same time useful.
For example, setting the Readable, Writable, and Files flags allows all files to be listed for which the application has read access, write access or both. If the Dirs and Drives flags are also included in this combination then all drives, directories, all files that the application can read, write, or execute, and symlinks to such files/directories can be listed.
To retrieve the permissons for a directory, use the entryInfoList() function to get the associated QFileInfo objects and then use the QFileInfo::permissons() to obtain the permissions and ownership for each file.
Enumerator
Dirs
Files
Drives
NoSymLinks
AllEntries
TypeMask
Readable
Writable
Executable
PermissionMask
Modified
Hidden
System
AccessMask
AllDirs
CaseSensitive
NoDotAndDotDot
NoDot
NoDotDot
NoFilter
Definition at line 64 of file qdir.h.
                 { Dirs        = 0x001,
                   Files       = 0x002,
                   Drives      = 0x004,
                   NoSymLinks  = 0x008,
                   AllEntries  = Dirs | Files | Drives,
                   TypeMask    = 0x00f,
 #ifdef QT3_SUPPORT
                   All         = AllEntries,
 #endif
                   Readable    = 0x010,
                   Writable    = 0x020,
                   Executable  = 0x040,
                   PermissionMask    = 0x070,
 #ifdef QT3_SUPPORT
                   RWEMask     = 0x070,
 #endif
                   Modified    = 0x080,
                   Hidden      = 0x100,
                   System      = 0x200,
                   AccessMask  = 0x3F0,
                   AllDirs       = 0x400,
                   CaseSensitive = 0x800,
                   NoDotAndDotDot = 0x1000, // ### Qt5 NoDotAndDotDot = NoDot|NoDotDot
                   NoDot         = 0x2000,
                   NoDotDot      = 0x4000,
                   NoFilter = -1
 #ifdef QT3_SUPPORT
                   ,DefaultFilter = NoFilter
 #endif
     };
SortFlag
enum QDir::SortFlag
This enum describes the sort options available to QDir, e.
g. for entryList() and entryInfoList(). The sort value is specified by OR-ing together values from the following list:
Name Sort by name.
Time Sort by time (modification time).
Size Sort by file size.
Type Sort by file type (extension).
Unsorted Do not sort.
NoSort Not sorted by default.
DirsFirst Put the directories first, then the files.
DirsLast Put the files first, then the directories.
Reversed Reverse the sort order.
IgnoreCase Sort case-insensitively.
LocaleAware Sort items appropriately using the current locale settings.
SortByMask
DefaultSort
You can only specify one of the first four.
If you specify both DirsFirst and Reversed, directories are still put first, but in reverse order; the files will be listed after the directories, again in reverse order.
Enumerator
Name
Time
Size
Unsorted
SortByMask
DirsFirst
Reversed
IgnoreCase
DirsLast
LocaleAware
Type
NoSort
Definition at line 104 of file qdir.h.
                   { Name        = 0x00,
                     Time        = 0x01,
                     Size        = 0x02,
                     Unsorted    = 0x03,
                     SortByMask  = 0x03,
                     DirsFirst   = 0x04,
                     Reversed    = 0x08,
                     IgnoreCase  = 0x10,
                     DirsLast    = 0x20,
                     LocaleAware = 0x40,
                     Type        = 0x80,
                     NoSort = -1
 #ifdef QT3_SUPPORT
                   ,DefaultSort = NoSort
 #endif
     };
Constructors and Destructors
QDir() [1/3]
QDir::QDir (const QDir & dir)
Constructs a QDir object that is a copy of the QDir object for directory dir.
See also
operator=()
Definition at line 561 of file qdir.cpp.
     : d_ptr(dir.d_ptr)
 {
 }
QDir() [2/3]
QDir::QDir (const QString & path = QString())
Constructs a QDir pointing to the given directory path.
If path is empty the program's working directory, ("."), is used.
See also
currentPath()
Definition at line 527 of file qdir.cpp.
                               : d_ptr(new QDirPrivate(path))
 {
 }
QDir() [3/3]
QDir::QDir (const QString & path, const QString & nameFilter, SortFlags sort = SortFlags(Name | IgnoreCase), Filters filters = AllEntries)
Constructs a QDir with path path, that filters its entries by name using nameFilter and by attributes using filters.
It also sorts the names using sort.
The default nameFilter is an empty string, which excludes nothing; the default filters is AllEntries , which also means exclude nothing. The default sort is Name | IgnoreCase , i.e. sort by name case-insensitively.
If path is an empty string, QDir uses "." (the current directory). If nameFilter is an empty string, QDir uses the name filter "*" (all files).
Note that path need not exist.
See also
exists(), setPath(), setNameFilter(), setFilter(), setSorting()
Definition at line 549 of file qdir.cpp.
     : d_ptr(new QDirPrivate(path, QDir::nameFiltersFromString(nameFilter), sort, filters))
 {
 }
~QDir()
QDir::~QDir ()
Destroys the QDir object frees up its resources.
This has no effect on the underlying directory in the file system.
Definition at line 570 of file qdir.cpp.
 {
 }
Functions
absoluteFilePath()
QString QDir::absoluteFilePath (const QString & fileName) const
Returns the absolute path name of a file in the directory.
Does not check if the file actually exists in the directory; but see exists(). Redundant multiple separators or "." and ".." directories in fileName are not removed (see cleanPath()).
See also
relativeFilePath() filePath() canonicalPath()
Definition at line 701 of file qdir.cpp.
Referenced by QCoreApplication::applicationFilePath(), initializeDb(), QDeclarativeDebugServerPrivate::loadConnectionPlugin(), QDeclarativeInspectorService::loadInspectorPlugin(), QBasicUnixFontDatabase::populateFontDatabase(), QPlatformFontDatabase::populateFontDatabase(), and QDeclarativeImportDatabase::resolvePlugin().
 {
     const QDirPrivate* d = d_ptr.constData();
     if (isAbsolutePath(fileName))
         return fileName;
     d->resolveAbsoluteEntry();
     if (fileName.isEmpty())
         return d->absoluteDirEntry.filePath();
     if (!d->absoluteDirEntry.isRoot())
         return d->absoluteDirEntry.filePath() % QLatin1Char('/') % fileName;
     return d->absoluteDirEntry.filePath() % fileName;
 }
absolutePath()
QString QDir::absolutePath () const
Returns the absolute path (a path that starts with "/" or with a drive specification), which may contain symbolic links, but never contains redundant ".", ".." or multiple separators.
See also
setPath(), canonicalPath(), exists(), cleanPath(), dirName(), absoluteFilePath()
Definition at line 619 of file qdir.cpp.
Referenced by QDirModel::index(), makeAbsolute(), QDirModel::mkdir(), QFileSystemModel::mkdir(), QFileSystemModelPrivate::node(), QMovie::QMovie(), relativeFilePath(), QDeclarativeImportDatabase::resolvePlugin(), QNetworkDiskCache::setCacheDirectory(), QFileDialog::setDirectory(), and QMovie::setFileName().
 {
     const QDirPrivate* d = d_ptr.constData();
     d->resolveAbsoluteEntry();
     return d->absoluteDirEntry.filePath();
 }
addResourceSearchPath()
void QDir::addResourceSearchPath (const QString & path) static
Use QDir::addSearchPath() with a prefix instead.
Adds path to the search paths searched in to find resources that are not specified with an absolute path. The default search path is to search only in the root (:/).
See also
{The Qt Resource System}
Definition at line 989 of file qdir.cpp.
 {
 #ifdef QT_BUILD_CORE_LIB
     QResource::addSearchPath(path);
 #else
     Q_UNUSED(path)
 #endif
 }
addSearchPath()
static void QDir::addSearchPath (const QString & prefix, const QString & path) static
Referenced by addResourceSearchPath().
canonicalPath()
QString QDir::canonicalPath () const
Returns the canonical path, i.e.
a path without symbolic links or redundant "." or ".." elements.
On systems that do not have symbolic links this function will always return the same string that absolutePath() returns. If the canonical path does not exist (normally due to dangling symbolic links) canonicalPath() returns an empty string.
Example:
QString bin = "/local/bin";         // where /local/bin is a symlink to /usr/bin
QDir binDir(bin);
QString canonicalBin = binDir.canonicalPath();
// canonicalBin now equals "/usr/bin"
QString ls = "/local/bin/ls";       // where ls is the executable "ls"
QDir lsDir(ls);
QString canonicalLs = lsDir.canonicalPath();
// canonicalLS now equals "/usr/bin/ls".
See also
path(), absolutePath(), exists(), cleanPath(), dirName(), absoluteFilePath()
Definition at line 642 of file qdir.cpp.
Referenced by QDeclarativeImportDatabase::addImportPath(), QCoreApplication::addLibraryPath(), QDeclarativeImportDatabase::addPluginPath(), QCoreApplicationPrivate::appendApplicationPathToLibraryPaths(), QScriptEngine::importExtension(), QCoreApplication::libraryPaths(), operator==(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), QCoreApplication::removeLibraryPath(), and QCoreApplication::setApplicationVersion().
 {
     const QDirPrivate* d = d_ptr.constData();
     if (d->fileEngine.isNull()) {
         QFileSystemEntry answer = QFileSystemEngine::canonicalName(d->dirEntry, d->metaData);
         return answer.filePath();
     }
     return d->fileEngine->fileName(QAbstractFileEngine::CanonicalName);
 }
cd()
bool QDir::cd (const QString & dirName)
Changes the QDir's directory to dirName.
Returns true if the new directory exists and is readable; otherwise returns false. Note that the logical cd() operation is not performed if the new directory does not exist.
Calling cd("..") is equivalent to calling cdUp().
See also
cdUp(), isReadable(), exists(), path()
Definition at line 880 of file qdir.cpp.
Referenced by cdUp(), and QScriptEngine::importExtension().
 {
     // Don't detach just yet.
     const QDirPrivate * const d = d_ptr.constData();
     if (dirName.isEmpty() || dirName == QLatin1String("."))
         return true;
     QString newPath;
     if (isAbsolutePath(dirName)) {
         newPath = cleanPath(dirName);
     } else {
         if (isRoot()) {
             if (dirName == QLatin1String(".."))
                 return false;
             newPath = d->dirEntry.filePath();
         } else {
             newPath = d->dirEntry.filePath() % QLatin1Char('/');
         }
         newPath += dirName;
         if (dirName.indexOf(QLatin1Char('/')) >= 0
             || dirName == QLatin1String("..")
             || d->dirEntry.filePath() == QLatin1String(".")) {
             newPath = cleanPath(newPath);
             /*
               If newPath starts with .., we convert it to absolute to
               avoid infinite looping on
                   QDir dir(".");
                   while (dir.cdUp())
                       ;
             */
             if (newPath.startsWith(QLatin1String(".."))) {
                 newPath = QFileInfo(newPath).absoluteFilePath();
             }
         }
     }
     QScopedPointer<QDirPrivate> dir(new QDirPrivate(*d_ptr.constData()));
     dir->setPath(newPath);
     if (!dir->exists())
         return false;
     d_ptr = dir.take();
     return true;
 }
cdUp()
bool QDir::cdUp ()
Changes directory by moving one directory up from the QDir's current directory.
Returns true if the new directory exists and is readable; otherwise returns false. Note that the logical cdUp() operation is not performed if the new directory does not exist.
See also
cd(), isReadable(), exists(), path()
Definition at line 937 of file qdir.cpp.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), QFileSystemEngine::getLinkTarget(), QDirModel::mkdir(), and QDeclarativeFolderListModel::setFolder().
 {
     return cd(QString::fromLatin1(".."));
 }
cleanPath()
QString QDir::cleanPath (const QString & path) static
Removes all multiple directory separators "/" and resolves any "."s or ".."s found in the path, path.
Symbolic links are kept. This function does not return the canonical path, but rather the simplest version of the input. For example, "./local" becomes "local", "local/../bin" becomes "bin" and "/local/usr/../bin" becomes "/local/bin".
See also
absolutePath() canonicalPath()
Definition at line 2082 of file qdir.cpp.
Referenced by _q_resolveEntryAndCreateLegacyEngine_recursive(), _qt_get_directory(), QFileSystemEngine::absoluteName(), QUrlModel::addUrls(), QCoreApplication::applicationFilePath(), QFileSystemEngine::canonicalName(), cd(), cleanPath(), QFileSystemEngine::createDirectory(), QDirModel::filePath(), QLibraryInfoPrivate::findConfiguration(), QFileSystemEngine::getLinkTarget(), QFileSystemEngine::homePath(), isDirPath(), QLibraryInfo::location(), QFSFileEnginePrivate::longFileName(), QFileSystemEngine::nativeAbsoluteFilePath(), qt_resource_fixResourceRoot(), QFactoryLoader::refreshAll(), relativeFilePath(), QFileSystemEngine::removeDirectory(), QCoreApplication::removeLibraryPath(), QDirPrivate::resolveAbsoluteEntry(), QFileDialog::setDirectory(), QPluginLoader::setFileName(), QFileSystemModel::setRootPath(), QFileSystemEngine::slowCanonicalized(), QFileSystemEngine::tempPath(), and QFactoryLoader::updateDir().
 {
     if (path.isEmpty())
         return path;
     QString name = path;
     QChar dir_separator = separator();
     if (dir_separator != QLatin1Char('/'))
        name.replace(dir_separator, QLatin1Char('/'));
     int used = 0, levels = 0;
     const int len = name.length();
     QVarLengthArray<QChar> outVector(len);
     QChar *out = outVector.data();
     const QChar *p = name.unicode();
     for (int i = 0, last = -1, iwrite = 0; i < len; ++i) {
         if (p[i] == QLatin1Char('/')) {
             while (i+1 < len && p[i+1] == QLatin1Char('/')) {
 #if defined(Q_OS_WIN) && !defined(Q_OS_WINCE) //allow unc paths
                 if (!i)
                     break;
 #endif
                 i++;
             }
             bool eaten = false;
             if (i+1 < len && p[i+1] == QLatin1Char('.')) {
                 int dotcount = 1;
                 if (i+2 < len && p[i+2] == QLatin1Char('.'))
                     dotcount++;
                 if (i == len - dotcount - 1) {
                     if (dotcount == 1) {
                         break;
                     } else if (levels) {
                         if (last == -1) {
                             for (int i2 = iwrite-1; i2 >= 0; i2--) {
                                 if (out[i2] == QLatin1Char('/')) {
                                     last = i2;
                                     break;
                                 }
                             }
                         }
                         used -= iwrite - last - 1;
                         break;
                     }
                 } else if (p[i+dotcount+1] == QLatin1Char('/')) {
                     if (dotcount == 2 && levels) {
                         if (last == -1 || iwrite - last == 1) {
                             for (int i2 = (last == -1) ? (iwrite-1) : (last-1); i2 >= 0; i2--) {
                                 if (out[i2] == QLatin1Char('/')) {
                                     eaten = true;
                                     last = i2;
                                     break;
                                 }
                             }
                         } else {
                             eaten = true;
                         }
                         if (eaten) {
                             levels--;
                             used -= iwrite - last;
                             iwrite = last;
                             last = -1;
                         }
                     } else if (dotcount == 2 && i > 0 && p[i - 1] != QLatin1Char('.')) {
                         eaten = true;
                         used -= iwrite - qMax(0, last);
                         iwrite = qMax(0, last);
                         last = -1;
                         ++i;
                     } else if (dotcount == 1) {
                         eaten = true;
                     }
                     if (eaten)
                         i += dotcount;
                 } else {
                     levels++;
                 }
             } else if (last != -1 && iwrite - last == 1) {
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
                 eaten = (iwrite > 2);
 #else
                 eaten = true;
 #endif
                 last = -1;
             } else if (last != -1 && i == len-1) {
                 eaten = true;
             } else {
                 levels++;
             }
             if (!eaten)
                 last = i - (i - iwrite);
             else
                 continue;
         } else if (!i && p[i] == QLatin1Char('.')) {
             int dotcount = 1;
             if (len >= 1 && p[1] == QLatin1Char('.'))
                 dotcount++;
             if (len >= dotcount && p[dotcount] == QLatin1Char('/')) {
                 if (dotcount == 1) {
                     i++;
                     while (i+1 < len-1 && p[i+1] == QLatin1Char('/'))
                         i++;
                     continue;
                 }
             }
         }
         out[iwrite++] = p[i];
         used++;
     }
     QString ret = (used == len ? name : QString(out, used));
     // Strip away last slash except for root directories
     if (ret.length() > 1 && ret.endsWith(QLatin1Char('/'))) {
 #if defined (Q_OS_WIN) || defined (Q_OS_SYMBIAN)
         if (!(ret.length() == 3 && ret.at(1) == QLatin1Char(':')))
 #endif
             ret.chop(1);
     }
     return ret;
 }
convertSeparators()
QString QDir::convertSeparators (const QString & pathName) static
Use QDir::toNativeSeparators() instead.
Definition at line 788 of file qdir.cpp.
 {
     return toNativeSeparators(pathName);
 }
count()
uint QDir::count () const
Returns the total number of directories and files in the directory.
Equivalent to entryList().count().
See also
operator[](), entryList()
Definition at line 1247 of file qdir.cpp.
Referenced by cleanupFontsDir(), initializeDb(), QBasicUnixFontDatabase::populateFontDatabase(), and QPlatformFontDatabase::populateFontDatabase().
 {
     const QDirPrivate* d = d_ptr.constData();
     d->initFileLists(*this);
     return d->files.count();
 }
current()
QDir QDir::current () inline static
Returns the application's current directory.
The directory is constructed using the absolute path of the current directory, ensuring that its path() will be the same as its absolutePath().
See also
currentPath(), setCurrent(), home(), root(), temp()
Definition at line 209 of file qdir.h.
Referenced by _qt_get_directory(), and QCoreApplication::applicationFilePath().
 { return QDir(currentPath()); }
currentPath()
QString QDir::currentPath () static
Returns the absolute path of the application's current directory.
See also
current(), setCurrent(), homePath(), rootPath(), tempPath()
Definition at line 1875 of file qdir.cpp.
Referenced by QUnixPrintWidgetPrivate::applyPrinterProperties(), QDeclarativeEngine::baseUrl(), QDeclarativeFolderListModel::componentComplete(), fixIfRelativeUncPath(), QFileSystemEngine::getLinkTarget(), QLibraryInfo::location(), QFSFileEnginePrivate::longFileName(), QFileSystemEngine::nativeAbsoluteFilePath(), QProcessPrivate::pipeWriterBytesToWrite(), qt_init(), qt_win_get_existing_directory(), QTest::qtest_qParseArgs(), registerComponent(), QGtkStylePrivate::setupGtkFileChooser(), and QFileDialogPrivate::workingDirectory().
 {
     return QFileSystemEngine::currentPath().filePath();
 }
dirName()
QString QDir::dirName () const
Returns the name of the directory; this is not the same as the path, e.g.
a directory with the name "mail", might have the path "/var/spool/mail". If the directory has no name (e.g. it is the root directory) an empty string is returned.
No check is made to ensure that a directory with this name actually exists; but see exists().
See also
path(), filePath(), absolutePath(), absoluteFilePath()
Definition at line 663 of file qdir.cpp.
Referenced by cd(), and QDirModel::mkdir().
 {
     const QDirPrivate* d = d_ptr.constData();
     return d->dirEntry.fileName();
 }
drives()
QFileInfoList QDir::drives () static
Returns a list of the root directories on this system.
On Windows this returns a list of QFileInfo objects containing "C:/", "D:/", etc. On other operating systems, it returns a list containing just one root directory (i.e. "/").
See also
root(), rootPath()
Definition at line 1812 of file qdir.cpp.
Referenced by QDirModelPrivate::children(), QFileInfoGatherer::getFileInfos(), and QPluginLoader::setFileName().
 {
 #ifdef QT_NO_FSFILEENGINE
     return QFileInfoList();
 #else
     return QFSFileEngine::drives();
 #endif
 }
entryInfoList() [1/2]
QFileInfoList QDir::entryInfoList (Filters filters = NoFilter, SortFlags sort = NoSort) const
Returns a list of QFileInfo objects for all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The attribute filter and sorting specifications can be overridden using the filters and sort arguments.
Returns an empty list if the directory is unreadable, does not exist, or if nothing matches the specification.
See also
entryList(), setNameFilters(), setSorting(), setFilter(), isReadable(), exists()
Definition at line 1316 of file qdir.cpp.
Referenced by QScriptEngine::availableExtensions(), QDirModelPrivate::children(), QBenchmarkValgrindUtils::cleanup(), QFontEngineQPF::cleanUpAfterClientCrash(), QDirModelPrivate::entryInfoList(), QBenchmarkValgrindUtils::getNewestFileName(), QScriptEngine::importExtension(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), qt_parseEtcLpMember(), qt_parseEtcLpPrinters(), and qt_parseSpoolInterface().
 {
     const QDirPrivate* d = d_ptr.constData();
     return entryInfoList(d->nameFilters, filters, sort);
 }
entryInfoList() [2/2]
QFileInfoList QDir::entryInfoList (const QStringList & nameFilters, Filters filters = NoFilter, SortFlags sort = NoSort) const
Returns a list of QFileInfo objects for all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
The name filter, file attribute filter, and sorting specification can be overridden using the nameFilters, filters, and sort arguments.
Returns an empty list if the directory is unreadable, does not exist, or if nothing matches the specification.
See also
entryList(), setNameFilters(), setSorting(), setFilter(), isReadable(), exists()
Definition at line 1384 of file qdir.cpp.
 {
     const QDirPrivate* d = d_ptr.constData();
     if (filters == NoFilter)
         filters = d->filters;
 #ifdef QT3_SUPPORT
     if (d->matchAllDirs)
         filters |= AllDirs;
 #endif
     if (sort == NoSort)
         sort = d->sort;
     if (filters == d->filters && sort == d->sort && nameFilters == d->nameFilters) {
         d->initFileLists(*this);
         return d->fileInfos;
     }
     QFileInfoList l;
     QDirIterator it(d->dirEntry.filePath(), nameFilters, filters);
     while (it.hasNext()) {
         it.next();
         l.append(it.fileInfo());
     }
     QFileInfoList ret;
     d->sortFileList(sort, l, 0, &ret);
     return ret;
 }
entryList() [1/2]
QStringList QDir::entryList (Filters filters = NoFilter, SortFlags sort = NoSort) const
Returns a list of the names of all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The attribute filter and sorting specifications can be overridden using the filters and sort arguments.
Returns an empty list if the directory is unreadable, does not exist, or if nothing matches the specification.
Note
To list symlinks that point to non existing files, System must be passed to the filter.
See also
entryInfoList(), setNameFilters(), setSorting(), setFilter()
Definition at line 1290 of file qdir.cpp.
Referenced by QCoreApplication::applicationFilePath(), QDirModelPrivate::entryList(), QPollingFileSystemWatcherEngine::FileInfo::FileInfo(), findAllLibCrypto(), findAllLibSsl(), QDeclarativeDebugServerPrivate::loadConnectionPlugin(), QDeclarativeInspectorService::loadInspectorPlugin(), QPollingFileSystemWatcherEngine::FileInfo::operator!=(), and QFactoryLoader::updateDir().
 {
     const QDirPrivate* d = d_ptr.constData();
     return entryList(d->nameFilters, filters, sort);
 }
entryList() [2/2]
QStringList QDir::entryList (const QStringList & nameFilters, Filters filters = NoFilter, SortFlags sort = NoSort) const
Returns a list of the names of all the files and directories in the directory, ordered according to the name and attribute filters previously set with setNameFilters() and setFilter(), and sorted according to the flags set with setSorting().
The name filter, file attribute filter, and sorting specification can be overridden using the nameFilters, filters, and sort arguments.
Returns an empty list if the directory is unreadable, does not exist, or if nothing matches the specification.
See also
entryInfoList(), setNameFilters(), setSorting(), setFilter()
Definition at line 1338 of file qdir.cpp.
 {
     const QDirPrivate* d = d_ptr.constData();
     if (filters == NoFilter)
         filters = d->filters;
 #ifdef QT3_SUPPORT
     if (d->matchAllDirs)
         filters |= AllDirs;
 #endif
     if (sort == NoSort)
         sort = d->sort;
     if (filters == d->filters && sort == d->sort && nameFilters == d->nameFilters) {
         d->initFileLists(*this);
         return d->files;
     }
     QFileInfoList l;
     QDirIterator it(d->dirEntry.filePath(), nameFilters, filters);
     while (it.hasNext()) {
         it.next();
         l.append(it.fileInfo());
     }
     QStringList ret;
     d->sortFileList(sort, l, &ret, 0);
     return ret;
 }
exists() [1/2]
bool QDir::exists () const
Returns true if the directory exists; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
(If a file with the same name is found this function will return false).
The overload of this function that accepts an argument is used to test for the presence of files and directories within a directory.
See also
QFileInfo::exists(), QFile::exists()
Definition at line 1560 of file qdir.cpp.
Referenced by QScriptEngine::availableExtensions(), QDeclarativeFolderListModel::componentComplete(), QIconLoader::findIconHelper(), QGuiPlatformPlugin::iconThemeSearchPaths(), QScriptEngine::importExtension(), QKde::kdeHome(), QDeclarativeDebugServerPrivate::loadConnectionPlugin(), QDeclarativeInspectorService::loadInspectorPlugin(), operator==(), qt_parseEtcLpMember(), qt_parseSpoolInterface(), qws_fontCacheDir(), and QFileSystemModel::setRootPath().
 {
     return d_ptr->exists();
 }
exists() [2/2]
bool QDir::exists (const QString & name) const
Returns true if the file called name exists; otherwise returns false.
Unless name contains an absolute file path, the file name is assumed to be relative to the directory itself, so this function is typically used to check for the presence of files within a directory.
See also
QFileInfo::exists(), QFile::exists()
Definition at line 1794 of file qdir.cpp.
 {
     if (name.isEmpty()) {
         qWarning("QDir::exists: Empty or null file name");
         return false;
     }
     return QFile::exists(filePath(name));
 }
filePath()
QString QDir::filePath (const QString & fileName) const
Returns the path name of a file in the directory.
Does not check if the file actually exists in the directory; but see exists(). If the QDir is relative the returned path name will also be relative. Redundant multiple separators or "." and ".." directories in fileName are not removed (see cleanPath()).
See also
dirName() absoluteFilePath(), isRelative(), canonicalPath()
Definition at line 678 of file qdir.cpp.
Referenced by exists(), QLibraryInfoPrivate::findConfiguration(), QIconLoader::findIconHelper(), mkdir(), mkpath(), remove(), rename(), rmdir(), rmpath(), and QFileInfo::setFile().
 {
     const QDirPrivate* d = d_ptr.constData();
     if (isAbsolutePath(fileName))
         return QString(fileName);
     QString ret = d->dirEntry.filePath();
     if (!fileName.isEmpty()) {
         if (!ret.isEmpty() && ret[(int)ret.length()-1] != QLatin1Char('/') && fileName[0] != QLatin1Char('/'))
             ret += QLatin1Char('/');
         ret += fileName;
     }
     return ret;
 }
filter()
QDir::Filters QDir::filter () const
Returns the value set by setFilter()
Definition at line 1085 of file qdir.cpp.
Referenced by operator<<().
 {
     const QDirPrivate* d = d_ptr.constData();
     return d->filters;
 }
fromNativeSeparators()
QString QDir::fromNativeSeparators (const QString & pathName) static
Returns pathName using '/' as file separator.
Since
4.2
On Windows, for instance, fromNativeSeparators("<tt>c:\\winnt\\system32</tt>") returns "c:/winnt/system32".
The returned string may be the same as the argument on some operating systems, for example on Unix.
See also
toNativeSeparators(), separator()
Definition at line 848 of file qdir.cpp.
Referenced by QZipWriter::addDirectory(), QZipWriter::addFile(), QZipWriter::addSymLink(), QFileSystemModelPrivate::filePath(), QUrl::fromLocalFile(), QFileInfoGatherer::getFileInfos(), isDirPath(), QFSFileEnginePrivate::longFileName(), QFileSystemModelPrivate::name(), QFileSystemEngine::nativeAbsoluteFilePath(), QFileSystemModelPrivate::node(), QFileSystemEntry::resolveFilePath(), QDirPrivate::setPath(), QFileSystemModel::setRootPath(), and QCompleter::splitPath().
 {
 #if defined(Q_FS_FAT) || defined(Q_OS_OS2EMX) || defined(Q_OS_SYMBIAN)
     int i = pathName.indexOf(QLatin1Char('\\'));
     if (i != -1) {
         QString n(pathName);
         QChar * const data = n.data();
         data[i++] = QLatin1Char('/');
         for (; i < n.length(); ++i) {
             if (data[i] == QLatin1Char('\\'))
                 data[i] = QLatin1Char('/');
         }
         return n;
     }
 #endif
     return pathName;
 }
home()
QDir QDir::home () inline static
Returns the user's home directory.
The directory is constructed using the absolute path of the home directory, ensuring that its path() will be the same as its absolutePath().
See homePath() for details.
See also
drives(), current(), root(), temp()
Definition at line 212 of file qdir.h.
 { return QDir(homePath()); }
homePath()
QString QDir::homePath () static
Returns the absolute path of the user's home directory.
Under Windows this function will return the directory of the current user's profile. Typically, this is:
C:/Documents and Settings/Username
Use the toNativeSeparators() function to convert the separators to the ones that are appropriate for the underlying operating system.
If the directory of the current user's profile does not exist or cannot be retrieved, the following alternatives will be checked (in the given order) until an existing and available path is found:
The path specified by the USERPROFILE environment variable.
The path formed by concatenating the HOMEDRIVE and HOMEPATH environment variables.
The path specified by the HOME environment variable.
The path returned by the rootPath() function (which uses the SystemDrive environment variable)
The C:/ directory.
Under non-Windows operating systems the HOME environment variable is used if it exists, otherwise the path returned by the rootPath().
On Symbian this typically returns "c:/data", i.e. the same as native PathInfo::PhoneMemoryRootPath().
See also
home(), currentPath(), rootPath(), tempPath()
Definition at line 1942 of file qdir.cpp.
Referenced by QFileDialogPrivate::_q_goHome(), QMacPasteboardMimeVCard::convertFromMime(), QFileDialogPrivate::createWidgets(), QMacSettingsPrivate::fileName(), getFullPath(), QScanThread::getUserConfigurations(), QGuiPlatformPlugin::iconThemeSearchPaths(), QTestFileLogger::init(), initDefaultPaths(), QKde::kdeHome(), launchWebBrowser(), openDocument(), qt_getDefaultFromHomePrinters(), qt_parseNsswitchPrintersEntry(), qt_tildeExpansion(), qt_win_get_open_file_name(), qt_win_get_open_file_names(), qt_win_get_save_file_name(), QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate(), QUnixPrintWidgetPrivate::setupPrinter(), and QDesktopServices::storageLocation().
 {
     return QFileSystemEngine::homePath();
 }
isAbsolute()
bool QDir::isAbsolute () const inline
Returns true if the directory's path is absolute; otherwise returns false.
See isAbsolutePath().
See also
isRelative() makeAbsolute() cleanPath()
Definition at line 194 of file qdir.h.
 { return !isRelative(); }
isAbsolutePath()
bool QDir::isAbsolutePath (const QString & path) inline static
Returns true if path is absolute; returns false if it is relative.
See also
isAbsolute() isRelativePath() makeAbsolute() cleanPath()
Definition at line 192 of file qdir.h.
Referenced by absoluteFilePath(), QmlApplicationViewerPrivate::adjustPath(), cd(), filePath(), QUrl::fromUserInput(), QProcessPrivate::pipeWriterBytesToWrite(), and qt_create_commandline().
 { return !isRelativePath(path); }
isReadable()
bool QDir::isReadable () const
Returns true if the directory is readable and we can open files by name; otherwise returns false.
Warning
A false value from this function is not a guarantee that files in the directory are not accessible.
See also
QFileInfo::isReadable()
Definition at line 1527 of file qdir.cpp.
 {
     const QDirPrivate* d = d_ptr.constData();
     if (d->fileEngine.isNull()) {
         if (!d->metaData.hasFlags(QFileSystemMetaData::UserReadPermission))
             QFileSystemEngine::fillMetaData(d->dirEntry, d->metaData, QFileSystemMetaData::UserReadPermission);
         return (d->metaData.permissions() & QFile::ReadUser) != 0;
     }
     const QAbstractFileEngine::FileFlags info =
         d->fileEngine->fileFlags(QAbstractFileEngine::DirectoryType
                                        | QAbstractFileEngine::PermsMask);
     if (!(info & QAbstractFileEngine::DirectoryType))
         return false;
     return info & QAbstractFileEngine::ReadUserPerm;
 }
isRelative()
bool QDir::isRelative () const
Returns true if the directory path is relative; otherwise returns false.
(Under Unix a path is relative if it does not start with a "/").
See also
makeAbsolute() isAbsolute() isAbsolutePath() cleanPath()
Definition at line 1615 of file qdir.cpp.
Referenced by QDirModel::mkdir().
 {
     if (d_ptr->fileEngine.isNull())
         return d_ptr->dirEntry.isRelative();
     return d_ptr->fileEngine->isRelativePath();
 }
isRelativePath()
bool QDir::isRelativePath (const QString & path) static
Returns true if path is relative; returns false if it is absolute.
See also
isRelative() isAbsolutePath() makeAbsolute()
Definition at line 2210 of file qdir.cpp.
Referenced by QDeclarativeTypeLoader::get(), QDeclarativeTypeLoader::getQmldir(), QDeclarativeTypeLoader::getScript(), QLibraryInfo::location(), makeAbsolute(), relativeFilePath(), QDeclarativeImportDatabase::resolvePlugin(), QFileDialog::selectFile(), QFileDialogPrivate::selectFile_sys(), and QUnixPrintWidgetPrivate::setupPrinter().
 {
     return QFileInfo(path).isRelative();
 }
isRoot()
bool QDir::isRoot () const
Returns true if the directory is the root directory; otherwise returns false.
Note: If the directory is a symbolic link to the root directory this function returns false. If you want to test for this use canonicalPath(), e.g.
QDir dir("/tmp/root_link");
dir = dir.canonicalPath();
if (dir.isRoot())
    qWarning("It is a root link");
See also
root(), rootPath()
Definition at line 1577 of file qdir.cpp.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), cd(), and QDeclarativeFolderListModel::setFolder().
 {
     if (d_ptr->fileEngine.isNull())
         return d_ptr->dirEntry.isRoot();
     return d_ptr->fileEngine->fileFlags(QAbstractFileEngine::FlagsMask) & QAbstractFileEngine::RootFlag;
 }
makeAbsolute()
bool QDir::makeAbsolute ()
Converts the directory path to an absolute path.
If it is already absolute nothing happens. Returns true if the conversion succeeded; otherwise returns false.
See also
isAbsolute() isAbsolutePath() isRelative() cleanPath()
Definition at line 1630 of file qdir.cpp.
 {
     const QDirPrivate *d = d_ptr.constData();
     QScopedPointer<QDirPrivate> dir;
     if (!d->fileEngine.isNull()) {
         QString absolutePath = d->fileEngine->fileName(QAbstractFileEngine::AbsoluteName);
         if (QDir::isRelativePath(absolutePath))
             return false;
         dir.reset(new QDirPrivate(*d_ptr.constData()));
         dir->setPath(absolutePath);
     } else { // native FS
         d->resolveAbsoluteEntry();
         dir.reset(new QDirPrivate(*d_ptr.constData()));
         dir->setPath(d->absoluteDirEntry.filePath());
     }
     d_ptr = dir.take(); // actually detach
     return true;
 }
match() [1/2]
bool QDir::match (const QStringList & filters, const QString & fileName) static
Returns true if the fileName matches any of the wildcard (glob) patterns in the list of filters; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The matching is case insensitive.
See also
{QRegExp wildcard matching}, QRegExp::exactMatch() entryList() entryInfoList()
Definition at line 2047 of file qdir.cpp.
Referenced by match(), and QNSOpenSavePanelDelegate::panel:shouldShowFilename:.
 {
     for (QStringList::ConstIterator sit = filters.constBegin(); sit != filters.constEnd(); ++sit) {
         QRegExp rx(*sit, Qt::CaseInsensitive, QRegExp::Wildcard);
         if (rx.exactMatch(fileName))
             return true;
     }
     return false;
 }
match() [2/2]
bool QDir::match (const QString & filter, const QString & fileName) static
Returns true if the fileName matches the wildcard (glob) pattern filter; otherwise returns false.
The filter may contain multiple patterns separated by spaces or semicolons. The matching is case insensitive.
See also
{QRegExp wildcard matching}, QRegExp::exactMatch() entryList() entryInfoList()
Definition at line 2065 of file qdir.cpp.
 {
     return match(nameFiltersFromString(filter), fileName);
 }
mkdir()
bool QDir::mkdir (const QString & dirName) const
Creates a sub-directory called dirName.
Returns true on success; otherwise returns false.
If the directory already exists when this function is called, it will return false.
See also
rmdir()
Definition at line 1424 of file qdir.cpp.
Referenced by QDirModel::mkdir(), QFileSystemModel::mkdir(), and QNetworkDiskCachePrivate::prepareLayout().
 {
     const QDirPrivate* d = d_ptr.constData();
     if (dirName.isEmpty()) {
         qWarning("QDir::mkdir: Empty or null file name(s)");
         return false;
     }
     QString fn = filePath(dirName);
     if (d->fileEngine.isNull())
         return QFileSystemEngine::createDirectory(QFileSystemEntry(fn), false);
     return d->fileEngine->mkdir(fn, false);
 }
mkpath()
bool QDir::mkpath (const QString & dirPath) const
Creates the directory path dirPath.
The function will create all parent directories necessary to create the directory.
Returns true if successful; otherwise returns false.
If the path already exists when this function is called, it will return true.
See also
rmpath()
Definition at line 1477 of file qdir.cpp.
Referenced by DumpIDL(), QZipReader::extractAll(), QNetworkDiskCachePrivate::prepareLayout(), qmlsqldatabase_initDatabasesPath(), and qws_fontCacheDir().
 {
     const QDirPrivate* d = d_ptr.constData();
     if (dirPath.isEmpty()) {
         qWarning("QDir::mkpath: Empty or null file name(s)");
         return false;
     }
     QString fn = filePath(dirPath);
     if (d->fileEngine.isNull())
         return QFileSystemEngine::createDirectory(QFileSystemEntry(fn), true);
     return d->fileEngine->mkdir(fn, true);
 }
nameFilters()
QStringList QDir::nameFilters () const
Returns the string list set by setNameFilters()
Definition at line 945 of file qdir.cpp.
Referenced by entryInfoList(), entryList(), nameFiltersFromString(), operator<<(), and setNameFilters().
 {
     const QDirPrivate* d = d_ptr.constData();
     return d->nameFilters;
 }
nameFiltersFromString()
QStringList QDir::nameFiltersFromString (const QString & nameFilter) static
Returns a list of name filters from the given nameFilter.
Warning
This function is not part of the public interface.
(If there is more than one filter, each pair of filters is separated by a space or by a semicolon.)
Definition at line 2236 of file qdir.cpp.
Referenced by match().
 {
     return QDirPrivate::splitFilters(nameFilter);
 }
operator!=()
bool QDir::operator!= (const QDir & dir) const inline
Returns true if directory dir and this directory have different paths or different sort or filter settings; otherwise returns false.
Example:
// The current directory is "/usr/local"
QDir d1("/usr/local/bin");
d1.setFilter(QDir::Executable);
QDir d2("bin");
if (d1 != d2)
    qDebug("They differ");
Definition at line 198 of file qdir.h.
 {  return !operator==(dir); }
operator=() [1/2]
QDir & QDir::operator= (const QDir & dir)
Makes a copy of the dir object and assigns it to this QDir object.
Definition at line 1707 of file qdir.cpp.
 {
     d_ptr = dir.d_ptr;
     return *this;
 }
operator=() [2/2]
QDir & QDir::operator= (const QString & path)
Sets the directory path to the given path.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Use setPath() instead.
Definition at line 1724 of file qdir.cpp.
 {
     d_ptr->setPath(path);
     return *this;
 }
operator==()
bool QDir::operator== (const QDir & dir) const
Returns true if directory dir and this directory have the same path and their sort and filter settings are the same; otherwise returns false.
Example:
// The current directory is "/usr/local"
QDir d1("/usr/local/bin");
QDir d2("bin");
if (d1 == d2)
    qDebug("They're the same");
Definition at line 1659 of file qdir.cpp.
 {
     const QDirPrivate *d = d_ptr.constData();
     const QDirPrivate *other = dir.d_ptr.constData();
     if (d == other)
         return true;
     Qt::CaseSensitivity sensitive;
     if (d->fileEngine.isNull() || other->fileEngine.isNull()) {
         if (d->fileEngine.data() != other->fileEngine.data()) // one is native, the other is a custom file-engine
             return false;
         sensitive = QFileSystemEngine::isCaseSensitive() ? Qt::CaseSensitive : Qt::CaseInsensitive;
     } else {
         if (d->fileEngine->caseSensitive() != other->fileEngine->caseSensitive())
             return false;
         sensitive = d->fileEngine->caseSensitive() ? Qt::CaseSensitive : Qt::CaseInsensitive;
     }
     if (d->filters == other->filters
        && d->sort == other->sort
        && d->nameFilters == other->nameFilters) {
         // Assume directories are the same if path is the same
         if (d->dirEntry.filePath() == other->dirEntry.filePath())
             return true;
         if (exists()) {
             if (!dir.exists())
                 return false; //can't be equal if only one exists
             // Both exist, fallback to expensive canonical path computation
             return canonicalPath().compare(dir.canonicalPath(), sensitive) == 0;
         } else {
             if (dir.exists())
                 return false; //can't be equal if only one exists
             // Neither exists, compare absolute paths rather than canonical (which would be empty strings)
             d->resolveAbsoluteEntry();
             other->resolveAbsoluteEntry();
             return d->absoluteDirEntry.filePath().compare(other->absoluteDirEntry.filePath(), sensitive) == 0;
         }
     }
     return false;
 }
operator[]()
QString QDir::operator[] (int pos) const
Returns the file name at position pos in the list of file names.
Equivalent to entryList().at(index). pos must be a valid index position in the list (i.e., 0 <= pos < count()).
See also
count(), entryList()
Definition at line 1261 of file qdir.cpp.
 {
     const QDirPrivate* d = d_ptr.constData();
     d->initFileLists(*this);
     return d->files[pos];
 }
path()
QString QDir::path () const
Returns the path.
This may contain symbolic links, but never contains redundant ".", ".." or multiple separators.
The returned path can be either absolute or relative (see setPath()).
See also
setPath(), absolutePath(), exists(), cleanPath(), dirName(), absoluteFilePath(), toNativeSeparators(), makeAbsolute()
Definition at line 605 of file qdir.cpp.
Referenced by QDnotifyFileSystemWatcherEngine::addPaths(), addResourceSearchPath(), cleanPath(), QGuiPlatformPlugin::iconThemeSearchPaths(), operator<<(), QIconTheme::QIconTheme(), QFileDialog::selectFile(), QDeclarativeFolderListModel::setFolder(), and QFileSystemModel::setRootPath().
 {
     const QDirPrivate* d = d_ptr.constData();
     return d->dirEntry.filePath();
 }
refresh()
void QDir::refresh () const
Refreshes the directory information.
Definition at line 2218 of file qdir.cpp.
Referenced by initializeDb(), QBasicUnixFontDatabase::populateFontDatabase(), and QPlatformFontDatabase::populateFontDatabase().
 {
     QDirPrivate *d = const_cast<QDir*>(this)->d_ptr.data();
     d->metaData.clear();
     d->initFileEngine();
     d->clearFileLists();
 }
relativeFilePath()
QString QDir::relativeFilePath (const QString & fileName) const
Returns the path to fileName relative to the directory.
QDir dir("/home/bob");
QString s;
s = dir.relativeFilePath("images/file.jpg");     // s is "images/file.jpg"
s = dir.relativeFilePath("/home/mary/file.txt"); // s is "../mary/file.txt"
See also
absoluteFilePath() filePath() canonicalPath()
Definition at line 722 of file qdir.cpp.
Referenced by QScriptEngine::availableExtensions().
 {
     QString dir = cleanPath(absolutePath());
     QString file = cleanPath(fileName);
     if (isRelativePath(file) || isRelativePath(dir))
         return file;
     QString dirDrive = driveSpec(dir);
     QString fileDrive = driveSpec(file);
     bool fileDriveMissing = false;
     if (fileDrive.isEmpty()) {
         fileDrive = dirDrive;
         fileDriveMissing = true;
     }
 #ifdef Q_OS_WIN
     if (fileDrive.toLower() != dirDrive.toLower()
         || (file.startsWith(QLatin1String("//"))
         && !dir.startsWith(QLatin1String("//"))))
 #elif defined(Q_OS_SYMBIAN)
     if (fileDrive.toLower() != dirDrive.toLower())
 #else
     if (fileDrive != dirDrive)
 #endif
         return file;
     dir.remove(0, dirDrive.size());
     if (!fileDriveMissing)
         file.remove(0, fileDrive.size());
     QString result;
     QStringList dirElts = dir.split(QLatin1Char('/'), QString::SkipEmptyParts);
     QStringList fileElts = file.split(QLatin1Char('/'), QString::SkipEmptyParts);
     int i = 0;
     while (i < dirElts.size() && i < fileElts.size() &&
 #if defined(Q_OS_WIN) || defined(Q_OS_SYMBIAN)
            dirElts.at(i).toLower() == fileElts.at(i).toLower())
 #else
            dirElts.at(i) == fileElts.at(i))
 #endif
         ++i;
     for (int j = 0; j < dirElts.size() - i; ++j)
         result += QLatin1String("../");
     for (int j = i; j < fileElts.size(); ++j) {
         result += fileElts.at(j);
         if (j < fileElts.size() - 1)
             result += QLatin1Char('/');
     }
     return result;
 }
remove()
bool QDir::remove (const QString & fileName)
Removes the file, fileName.
Returns true if the file is removed successfully; otherwise returns false.
Definition at line 1751 of file qdir.cpp.
Referenced by cleanupFontsDir(), and QDirModel::remove().
 {
     if (fileName.isEmpty()) {
         qWarning("QDir::remove: Empty or null file name");
         return false;
     }
     return QFile::remove(filePath(fileName));
 }
rename()
bool QDir::rename (const QString & oldName, const QString & newName)
Renames a file or directory from oldName to newName, and returns true if successful; otherwise returns false.
On most file systems, rename() fails only if oldName does not exist, if newName and oldName are not on the same partition or if a file with the new name already exists. However, there are also other reasons why rename() can fail. For example, on at least one file system rename() fails if newName points to an open file.
Definition at line 1771 of file qdir.cpp.
Referenced by QDirModel::setData(), and QFileSystemModel::setData().
 {
     if (oldName.isEmpty() || newName.isEmpty()) {
         qWarning("QDir::rename: Empty or null file name(s)");
         return false;
     }
     QFile file(filePath(oldName));
     if (!file.exists())
         return false;
     return file.rename(filePath(newName));
 }
rmdir()
bool QDir::rmdir (const QString & dirName) const
Removes the directory specified by dirName.
The directory must be empty for rmdir() to succeed.
Returns true if successful; otherwise returns false.
See also
mkdir()
Definition at line 1448 of file qdir.cpp.
Referenced by QDirModel::rmdir(), and QFileSystemModel::rmdir().
 {
     const QDirPrivate* d = d_ptr.constData();
     if (dirName.isEmpty()) {
         qWarning("QDir::rmdir: Empty or null file name(s)");
         return false;
     }
     QString fn = filePath(dirName);
     if (d->fileEngine.isNull())
         return QFileSystemEngine::removeDirectory(QFileSystemEntry(fn), false);
     return d->fileEngine->rmdir(fn, false);
 }
rmpath()
bool QDir::rmpath (const QString & dirPath) const
Removes the directory path dirPath.
The function will remove all parent directories in dirPath, provided that they are empty. This is the opposite of mkpath(dirPath).
Returns true if successful; otherwise returns false.
See also
mkpath()
Definition at line 1503 of file qdir.cpp.
 {
     const QDirPrivate* d = d_ptr.constData();
     if (dirPath.isEmpty()) {
         qWarning("QDir::rmpath: Empty or null file name(s)");
         return false;
     }
     QString fn = filePath(dirPath);
     if (d->fileEngine.isNull())
         return QFileSystemEngine::removeDirectory(QFileSystemEntry(fn), true);
     return d->fileEngine->rmdir(fn, true);
 }
root()
QDir QDir::root () inline static
Returns the root directory.
The directory is constructed using the absolute path of the root directory, ensuring that its path() will be the same as its absolutePath().
See rootPath() for details.
See also
drives(), current(), home(), temp()
Definition at line 214 of file qdir.h.
Referenced by QZipReader::extractAll().
 { return QDir(rootPath()); }
rootPath()
QString QDir::rootPath () static
Returns the absolute path of the root directory.
For Unix operating systems this returns "/". For Windows and Symbian file systems this normally returns "c:/". I.E. the root of the system drive.
See also
root(), drives(), currentPath(), homePath(), tempPath()
Definition at line 2016 of file qdir.cpp.
Referenced by QFileSystemModelPrivate::node().
 {
     return QFileSystemEngine::rootPath();
 }
searchPaths()
static QStringList QDir::searchPaths (const QString & prefix) static
Referenced by _q_resolveEntryAndCreateLegacyEngine_recursive(), and addResourceSearchPath().
separator()
QChar QDir::separator () static
Returns the native directory separator: "/" under Unix (including Mac OS X) and "\\" under Windows.
You do not need to use this function to build file paths. If you always use "/", Qt will translate your paths to conform to the underlying operating system. If you want to display paths to the user using their operating system's separator use toNativeSeparators().
Definition at line 1831 of file qdir.cpp.
Referenced by QCompleterPrivate::_q_complete(), QFileDialogPrivate::_q_createDirectory(), QScriptEngine::availableExtensions(), QFileDialogPrivate::basename(), QDeclarativeEngine::baseUrl(), QDirModelPrivate::children(), cleanPath(), QFileSystemEngine::createDirectory(), QDirModel::dropMimeData(), QFileSystemModel::dropMimeData(), QZipReader::extractAll(), QFileSystemModelPrivate::filePath(), QCompletionEngine::filterHistory(), QFileInfoGatherer::getFileInfos(), QScriptEngine::importExtension(), QTestFileLogger::init(), initDefaultPaths(), isDirPath(), QTextDocument::loadResource(), QFileSystemModel::mkdir(), QFSCompleter::pathFromIndex(), QCompleter::pathFromIndex(), QConfFileSettingsPrivate::QConfFileSettingsPrivate(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), QDeclarativeScriptEngine::QDeclarativeScriptEngine(), qmlsqldatabase_databaseFile(), qmlsqldatabase_databasesPath(), qt_tildeExpansion(), QFileSystemEngine::removeDirectory(), QTextBrowserPrivate::resolveUrl(), QFileDialog::selectFile(), QCoreApplication::setApplicationVersion(), QFileSystemModel::setData(), QSettings::setPath(), QUnixPrintWidgetPrivate::setupPrinter(), QFSCompleter::splitPath(), QCompleter::splitPath(), QFileDialogPrivate::typedFiles(), and QFileInfoGatherer::updateFile().
 {
 #if defined (Q_FS_FAT) || defined(Q_WS_WIN) || defined(Q_OS_SYMBIAN)
     return QLatin1Char('\\');
 #elif defined(Q_OS_UNIX)
     return QLatin1Char('/');
 #elif defined (Q_OS_MAC)
     return QLatin1Char(':');
 #else
     return QLatin1Char('/');
 #endif
 }
setCurrent()
bool QDir::setCurrent (const QString & path) static
Sets the application's current working directory to path.
Returns true if the directory was successfully changed; otherwise returns false.
See also
current(), currentPath(), home(), root(), temp()
Definition at line 1851 of file qdir.cpp.
Referenced by qt_init().
 {
     return QFileSystemEngine::setCurrentPath(QFileSystemEntry(path));
 }
setFilter()
void QDir::setFilter (Filters filters)
Sets the filter used by entryList() and entryInfoList() to filters.
The filter is used to specify the kind of files that should be returned by entryList() and entryInfoList(). See QDir::Filter.
See also
filter(), setNameFilters()
Definition at line 1170 of file qdir.cpp.
Referenced by QFileDialogPrivate::_q_showHidden(), and QFileSystemModel::rootDirectory().
 {
     QDirPrivate* d = d_ptr.data();
     d->initFileEngine();
     d->clearFileLists();
     d->filters = filters;
 }
setNameFilters()
void QDir::setNameFilters (const QStringList & nameFilters)
Sets the name filters used by entryList() and entryInfoList() to the list of filters specified by nameFilters.
Each name filter is a wildcard (globbing) filter that understands * and ? wildcards. (See QRegExp wildcard matching.)
For example, the following code sets three name filters on a QDir to ensure that only files with extensions typically used for C++ source files are listed:
    QStringList filters;
    filters << "*.cpp" << "*.cxx" << "*.cc";
    dir.setNameFilters(filters);
See also
nameFilters(), setFilter()
Definition at line 966 of file qdir.cpp.
Referenced by initializeDb(), QBasicUnixFontDatabase::populateFontDatabase(), QPlatformFontDatabase::populateFontDatabase(), QFileSystemModel::rootDirectory(), and QSslSocketPrivate::systemCaCertificates().
 {
     QDirPrivate* d = d_ptr.data();
     d->initFileEngine();
     d->clearFileLists();
     d->nameFilters = nameFilters;
 }
setPath()
void QDir::setPath (const QString & path)
Sets the path of the directory to path.
The path is cleaned of redundant ".", ".." and of multiple separators. No check is made to see whether a directory with this path actually exists; but you can check for yourself using exists().
The path can be either absolute or relative. Absolute paths begin with the directory separator "/" (optionally preceded by a drive specification under Windows). Relative file names begin with a directory name or a file name and specify a path relative to the current directory. An example of an absolute path is the string "/tmp/quartz", a relative path might look like "src/fatlib".
See also
path(), absolutePath(), exists(), cleanPath(), dirName(), absoluteFilePath(), isRelative(), makeAbsolute()
Definition at line 590 of file qdir.cpp.
Referenced by qt_win_get_open_file_names(), QDeclarativeFolderListModel::setFolder(), QFileSystemModel::setRootPath(), and QSslSocketPrivate::systemCaCertificates().
 {
     d_ptr->setPath(path);
 }
setSearchPaths()
static void QDir::setSearchPaths (const QString & prefix, const QStringList & searchPaths) static
Referenced by addResourceSearchPath().
setSorting()
void QDir::setSorting (SortFlags sort)
Sets the sort order used by entryList() and entryInfoList().
The sort is specified by OR-ing values from the enum QDir::SortFlag.
See also
sorting() SortFlag
Definition at line 1231 of file qdir.cpp.
 {
     QDirPrivate* d = d_ptr.data();
     d->initFileEngine();
     d->clearFileLists();
     d->sort = sort;
 }
sorting()
QDir::SortFlags QDir::sorting () const
Returns the value set by setSorting()
See also
setSorting() SortFlag
Definition at line 1184 of file qdir.cpp.
Referenced by operator<<().
 {
     const QDirPrivate* d = d_ptr.constData();
     return d->sort;
 }
temp()
QDir QDir::temp () inline static
Returns the system's temporary directory.
The directory is constructed using the absolute path of the temporary directory, ensuring that its path() will be the same as its absolutePath().
See tempPath() for details.
See also
drives(), current(), home(), root()
Definition at line 216 of file qdir.h.
 { return QDir(tempPath()); }
tempPath()
QString QDir::tempPath () static
Returns the absolute path of the system's temporary directory.
On Unix/Linux systems this is the path in the TMPDIR environment variable or /tmp if TMPDIR is not defined. On Windows this is usually the path in the TEMP or TMP environment variable. Whether a directory separator is added to the end or not, depends on the operating system.
See also
temp(), currentPath(), homePath(), rootPath()
Definition at line 1987 of file qdir.cpp.
Referenced by QFile::copy(), getFullPath(), launchWebBrowser(), QSharedMemoryPrivate::makePlatformSafeKey(), openDocument(), QTemporaryFile::QTemporaryFile(), qws_fontCacheDir(), QSslSocketBackendPrivate::startHandshake(), QDesktopServices::storageLocation(), and QTemporaryFilePrivate::~QTemporaryFilePrivate().
 {
     return QFileSystemEngine::tempPath();
 }
toNativeSeparators()
QString QDir::toNativeSeparators (const QString & pathName) static
Returns pathName with the '/' separators converted to separators that are appropriate for the underlying operating system.
Since
4.2
On Windows, toNativeSeparators("c:/winnt/system32") returns "c:\\winnt\\system32".
The returned string may be the same as the argument on some operating systems, for example on Unix.
See also
fromNativeSeparators(), separator()
Definition at line 812 of file qdir.cpp.
Referenced by QFileDialogPrivate::_q_pathChanged(), QWindowsFileSystemWatcherEngine::addPaths(), QFileDialogPrivate::basename(), QWindowsMimeURI::convertFromMime(), convertSeparators(), QCompletionEngine::filterHistory(), QFileIconProviderPrivate::getWinIcon(), QFileDialog::history(), QTestFileLogger::init(), isDirPath(), QLibraryPrivate::isPlugin(), isUncRoot(), QTranslator::load(), QFileSystemEngine::nativeAbsoluteFilePath(), QFileSystemModelPrivate::node(), qmlsqldatabase_databasesPath(), qt_create_commandline(), qt_win_get_existing_directory(), qt_win_get_save_file_name(), qt_win_make_OFN(), QFactoryLoader::refreshAll(), QFileSystemEntry::resolveNativeFilePath(), QUrlModel::setData(), QFileSystemModel::setData(), QPluginLoader::setFileName(), QFileDialogComboBox::setHistory(), QUrlModel::setUrl(), QFSCompleter::splitPath(), and QCompleter::splitPath().
 {
 #if defined(Q_FS_FAT) || defined(Q_OS_OS2EMX) || defined(Q_OS_SYMBIAN)
     int i = pathName.indexOf(QLatin1Char('/'));
     if (i != -1) {
         QString n(pathName);
         QChar * const data = n.data();
         data[i++] = QLatin1Char('\\');
         for (; i < n.length(); ++i) {
             if (data[i] == QLatin1Char('/'))
                 data[i] = QLatin1Char('\\');
         }
         return n;
     }
 #endif
     return pathName;
 }
Properties
d_ptr
QSharedDataPointer<QDirPrivate> QDir::d_ptr protected
Definition at line 61 of file qdir.h.
Referenced by absoluteFilePath(), absolutePath(), canonicalPath(), cd(), count(), dirName(), entryInfoList(), entryList(), exists(), filePath(), filter(), isReadable(), isRelative(), isRoot(), makeAbsolute(), mkdir(), mkpath(), nameFilters(), nameFiltersFromString(), operator=(), operator==(), operator[](), path(), refresh(), rmdir(), rmpath(), setFilter(), setNameFilters(), setPath(), setSorting(), and sorting().
The documentation for this class was generated from the following files:
/src/corelib/io/qdir.h
/src/corelib/io/qdir.cpp