Qt 4.8: QXlibCursor Class Reference
QXlibCursor Class Reference
#include <qxlibcursor.h>
Public Functions
void changeCursor (QCursor *cursor, QWidget *widget)
This method is called by Qt whenever the cursor graphic should be changed.
QXlibCursor (QXlibScreen *screen)
Private Functions
Cursor createCursorBitmap (QCursor *cursor)
Cursor createCursorShape (int cshape)
QXlibScreen * testLiteScreen () const
Private Functions inherited from QPlatformCursor
virtual void pointerEvent (const QMouseEvent &event)
This method is called by Qt whenever a QMouseEvent is generated by the underlying pointer input.
virtual QPoint pos () const
QPlatformCursor (QPlatformScreen *)
Constructs a QPlatformCursor for the given screen.
virtual void setPos (const QPoint &pos)
Private Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QMap< int, Cursor > cursorMap
Properties inherited from QPlatformCursor
QPlatformScreen * screen
Properties inherited from QObject
QScopedPointer< QObjectData > d_ptr
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Private Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Private Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Private Attributes inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 51 of file qxlibcursor.h.
Constructors and Destructors
QXlibCursor()
QXlibCursor::QXlibCursor (QXlibScreen * screen)
Definition at line 55 of file qxlibcursor.cpp.
     : QPlatformCursor(screen)
 {
 }
Functions
changeCursor()
void QXlibCursor::changeCursor (QCursor * widgetCursor, QWidget * widget) virtual
This method is called by Qt whenever the cursor graphic should be changed.
Implementation of this method is mandatory for a subclass of QPlatformCursor.
widgetCursor is a pointer to the QCursor that should be displayed.
widget is a pointer to the widget currently displayed at QCursor::pos(). Note that this may be 0 if the current position is not occupied by a displayed widget.
See also
QCursor::pos()
Implements QPlatformCursor.
Definition at line 60 of file qxlibcursor.cpp.
 {
     QXlibWindow *w = 0;
     if (widget) {
         QWidget *window = widget->window();
         w = static_cast<QXlibWindow*>(window->platformWindow());
     } else {
         // No X11 cursor control when there is no widget under the cursor
         return;
     }
     if (!w)
         return;
     int id = cursor->handle();
     Cursor c;
     if (!cursorMap.contains(id)) {
         if (cursor->shape() == Qt::BitmapCursor)
             c = createCursorBitmap(cursor);
         else
             c = createCursorShape(cursor->shape());
         if (!c) {
             return;
         }
         cursorMap.insert(id, c);
     } else {
         c = cursorMap.value(id);
     }
     w->setCursor(c);
 }
createCursorBitmap()
Cursor QXlibCursor::createCursorBitmap (QCursor * cursor) private
Definition at line 93 of file qxlibcursor.cpp.
Referenced by changeCursor().
 {
     XColor bg, fg;
     bg.red   = 255 << 8;
     bg.green = 255 << 8;
     bg.blue  = 255 << 8;
     fg.red   = 0;
     fg.green = 0;
     fg.blue  = 0;
     QPoint spot = cursor->hotSpot();
     Window rootwin = testLiteScreen()->rootWindow();
     QImage mapImage = cursor->bitmap()->toImage().convertToFormat(QImage::Format_MonoLSB);
     QImage maskImage = cursor->mask()->toImage().convertToFormat(QImage::Format_MonoLSB);
     int width = cursor->bitmap()->width();
     int height = cursor->bitmap()->height();
     int bytesPerLine = mapImage.bytesPerLine();
     int destLineSize = width / 8;
     if (width % 8)
         destLineSize++;
     const uchar * map = mapImage.bits();
     const uchar * mask = maskImage.bits();
     char * mapBits = new char[height * destLineSize];
     char * maskBits = new char[height * destLineSize];
     for (int i = 0; i < height; i++) {
         memcpy(mapBits + (destLineSize * i),map + (bytesPerLine * i), destLineSize);
         memcpy(maskBits + (destLineSize * i),mask + (bytesPerLine * i), destLineSize);
     }
     Pixmap cp = XCreateBitmapFromData(testLiteScreen()->display()->nativeDisplay(), rootwin, mapBits, width, height);
     Pixmap mp = XCreateBitmapFromData(testLiteScreen()->display()->nativeDisplay(), rootwin, maskBits, width, height);
     Cursor c = XCreatePixmapCursor(testLiteScreen()->display()->nativeDisplay(), cp, mp, &fg, &bg, spot.x(), spot.y());
     XFreePixmap(testLiteScreen()->display()->nativeDisplay(), cp);
     XFreePixmap(testLiteScreen()->display()->nativeDisplay(), mp);
     delete[] mapBits;
     delete[] maskBits;
     return c;
 }
createCursorShape()
Cursor QXlibCursor::createCursorShape (int cshape) private
Definition at line 136 of file qxlibcursor.cpp.
Referenced by changeCursor().
 {
     Cursor cursor = 0;
     if (cshape < 0 || cshape > Qt::LastCursor)
         return 0;
     switch (cshape) {
     case Qt::ArrowCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_left_ptr);
         break;
     case Qt::UpArrowCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_center_ptr);
         break;
     case Qt::CrossCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_crosshair);
         break;
     case Qt::WaitCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_watch);
         break;
     case Qt::IBeamCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_xterm);
         break;
     case Qt::SizeAllCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_fleur);
         break;
     case Qt::PointingHandCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_hand2);
         break;
     case Qt::SizeBDiagCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_top_right_corner);
         break;
     case Qt::SizeFDiagCursor:
         cursor =  XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_bottom_right_corner);
         break;
     case Qt::SizeVerCursor:
     case Qt::SplitVCursor:
         cursor = XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_sb_v_double_arrow);
         break;
     case Qt::SizeHorCursor:
     case Qt::SplitHCursor:
         cursor = XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_sb_h_double_arrow);
         break;
     case Qt::WhatsThisCursor:
         cursor = XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_question_arrow);
         break;
     case Qt::ForbiddenCursor:
         cursor = XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_circle);
         break;
     case Qt::BusyCursor:
         cursor = XCreateFontCursor(testLiteScreen()->display()->nativeDisplay(), XC_watch);
         break;
     default: //default cursor for all the rest
         break;
     }
     return cursor;
 }
testLiteScreen()
QXlibScreen * QXlibCursor::testLiteScreen () const private
Definition at line 195 of file qxlibcursor.cpp.
Referenced by createCursorBitmap(), and createCursorShape().
 {
     return static_cast<QXlibScreen *>(screen);
 }
Properties
cursorMap
QMap<int, Cursor> QXlibCursor::cursorMap private
Definition at line 63 of file qxlibcursor.h.
Referenced by changeCursor().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xlib/qxlibcursor.h
/src/plugins/platforms/xlib/qxlibcursor.cpp