Qt 4.8: QWSSharedMemory Class Reference
QWSSharedMemory Class Reference
#include <qwssharedmemory_p.h>
Public Functions
void * address () const
bool attach (int id)
bool create (int size)
void detach ()
int id () const
QWSSharedMemory ()
int size () const
~QWSSharedMemory ()
Properties
void * shmBase
int shmId
int shmSize
Detailed Description
Definition at line 62 of file qwssharedmemory_p.h.
Constructors and Destructors
QWSSharedMemory()
QWSSharedMemory::QWSSharedMemory ()
Definition at line 75 of file qwssharedmemory.cpp.
     : shmId(-1), shmBase(0), shmSize(0)
 #ifdef QT_POSIX_IPC
     , hand(-1)
 #endif
 {
 }
~QWSSharedMemory()
QWSSharedMemory::~QWSSharedMemory ()
Definition at line 83 of file qwssharedmemory.cpp.
 {
     detach();
 }
Functions
address()
void* QWSSharedMemory::address () const inline
Definition at line 74 of file qwssharedmemory_p.h.
Referenced by QWSSharedMemSurface::setGeometry(), QWSSharedMemSurface::setMemory(), and QWSSharedMemSurface::setPermanentState().
 { return shmBase; }
attach()
bool QWSSharedMemory::attach (int id)
Definition at line 146 of file qwssharedmemory.cpp.
Referenced by QWSSharedMemSurface::setMemory().
 {
     if (shmId == id)
         return id != -1;
     detach();
     if (id == -1)
         return false;
     shmId = id;
 #ifndef QT_POSIX_IPC
     shmBase = shmat(shmId, 0, 0);
 #else
     QByteArray shmName = makeKey(shmId);
     EINTR_LOOP(hand, shm_open(shmName.constData(), O_RDWR, 0660));
     if (hand != -1) {
         // grab the size
         QT_STATBUF st;
         if (QT_FSTAT(hand, &st) != -1) {
             shmSize = st.st_size;
             // grab the memory
             shmBase = mmap(0, shmSize, PROT_READ | PROT_WRITE, MAP_SHARED, hand, 0);
         }
     }
 #endif
     if (shmBase == (void*)-1 || !shmBase) {
 #ifdef QT_SHM_DEBUG
         perror("QWSSharedMemory::attach():");
         qWarning("Error attaching to shared memory id %d", shmId);
 #endif
         detach();
         return false;
     }
     return true;
 }
create()
bool QWSSharedMemory::create (int size)
Definition at line 88 of file qwssharedmemory.cpp.
Referenced by QWSSharedMemSurface::setGeometry().
 {
     if (shmId != -1)
         detach();
 #ifndef QT_POSIX_IPC
     shmId = shmget(IPC_PRIVATE, size, IPC_CREAT | 0600);
 #else
     // ### generate really unique IDs
     shmId = (getpid() << 16) + (localUniqueId.fetchAndAddRelaxed(1) % ushort(-1));
     QByteArray shmName = makeKey(shmId);
     EINTR_LOOP(hand, shm_open(shmName.constData(), O_RDWR | O_CREAT, 0660));
     if (hand != -1) {
         // the size may only be set once; ignore errors
         int ret;
         EINTR_LOOP(ret, ftruncate(hand, size));
         if (ret == -1)
             shmId = -1;
     } else {
         shmId = -1;
     }
 #endif
     if (shmId == -1) {
 #ifdef QT_SHM_DEBUG
         perror("QWSSharedMemory::create():");
         qWarning("Error allocating shared memory of size %d", size);
 #endif
         detach();
         return false;
     }
 #ifndef QT_POSIX_IPC
     shmBase = shmat(shmId, 0, 0);
     // On Linux, it is possible to attach a shared memory segment even if it
     // is already marked to be deleted. However, POSIX.1-2001 does not specify
     // this behaviour and many other implementations do not support it.
     shmctl(shmId, IPC_RMID, 0);
 #else
     // grab the size
     QT_STATBUF st;
     if (QT_FSTAT(hand, &st) != -1) {
         shmSize = st.st_size;
         // grab the memory
         shmBase = mmap(0, shmSize, PROT_READ | PROT_WRITE, MAP_SHARED, hand, 0);
     }
 #endif
     if (shmBase == (void*)-1 || !shmBase) {
 #ifdef QT_SHM_DEBUG
         perror("QWSSharedMemory::create():");
         qWarning("Error attaching to shared memory id %d", shmId);
 #endif
         detach();
         return false;
     }
     return true;
 }
detach()
void QWSSharedMemory::detach ()
Definition at line 184 of file qwssharedmemory.cpp.
Referenced by attach(), create(), QWSSharedMemSurface::releaseSurface(), QWSSharedMemSurface::setGeometry(), QWSSharedMemSurface::setMemory(), and ~QWSSharedMemory().
 {
 #ifndef QT_POSIX_IPC
     if (shmBase && shmBase != (void*)-1)
         shmdt(shmBase);
 #else
     if (shmBase && shmBase != (void*)-1)
         munmap(shmBase, shmSize);
     if (hand > 0) {
         // get the number of current attachments
         int shm_nattch = 0;
         QT_STATBUF st;
         if (QT_FSTAT(hand, &st) == 0) {
             // subtract 2 from linkcount: one for our own open and one for the dir entry
             shm_nattch = st.st_nlink - 2;
         }
         qt_safe_close(hand);
         // if there are no attachments then unlink the shared memory
         if (shm_nattch == 0) {
             QByteArray shmName = makeKey(shmId);
             shm_unlink(shmName.constData());
         }
     }
 #endif
     shmBase = 0;
     shmSize = 0;
     shmId = -1;
 }
id()
int QWSSharedMemory::id () const inline
Definition at line 72 of file qwssharedmemory_p.h.
Referenced by attach(), QWSSharedMemSurface::permanentState(), and QWSSharedMemSurface::setMemory().
 { return shmId; }
size()
int QWSSharedMemory::size () const
Definition at line 213 of file qwssharedmemory.cpp.
Referenced by address(), and QWSSharedMemSurface::setGeometry().
 {
     if (shmId == -1)
         return 0;
 #ifndef QT_POSIX_IPC
     if (!shmSize) {
         struct shmid_ds shm;
         shmctl(shmId, IPC_STAT, &shm);
         shmSize = shm.shm_segsz;
     }
 #endif
     return shmSize;
 }
Properties
shmBase
void* QWSSharedMemory::shmBase private
Definition at line 79 of file qwssharedmemory_p.h.
Referenced by address(), attach(), create(), and detach().
shmId
int QWSSharedMemory::shmId private
Definition at line 78 of file qwssharedmemory_p.h.
Referenced by attach(), create(), detach(), id(), and size().
shmSize
int QWSSharedMemory::shmSize mutable private
Definition at line 80 of file qwssharedmemory_p.h.
Referenced by attach(), create(), detach(), and size().
The documentation for this class was generated from the following files:
/src/gui/embedded/qwssharedmemory_p.h
/src/gui/embedded/qwssharedmemory.cpp