Qt 4.8: QBBVirtualKeyboardBps Class Reference
QBBVirtualKeyboardBps Class Reference
#include <qbbvirtualkeyboardbps.h>
Public Functions
bool handleEvent (bps_event_t *event)
bool hideKeyboard ()
QBBVirtualKeyboardBps (QObject *parent=0)
bool showKeyboard ()
Public Functions inherited from QBBAbstractVirtualKeyboard
QString countryId () const
int getHeight () const
bool isVisible () const
KeyboardMode keyboardMode () const
QString languageId () const
QBBAbstractVirtualKeyboard (QObject *parent=0)
void setInputHintsFromWidget (QWidget *focusWidget)
void setKeyboardMode (KeyboardMode mode)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void applyKeyboardMode (KeyboardMode mode)
Protected Functions inherited from QBBAbstractVirtualKeyboard
void setCountry (const QString &country)
void setHeight (int height)
void setLanguage (const QString &language)
void setVisible (bool visible)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
bool handleLocaleEvent (bps_event_t *event)
bool handleVirtualKeyboardEvent (bps_event_t *event)
Additional Inherited Members
Public Types inherited from QBBAbstractVirtualKeyboard
enum KeyboardMode {
Default, Url, Email, Web,
NumPunc, Symbol, Phone, Pin
}
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QBBAbstractVirtualKeyboard
void heightChanged (int height)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 51 of file qbbvirtualkeyboardbps.h.
Constructors and Destructors
QBBVirtualKeyboardBps()
QBBVirtualKeyboardBps::QBBVirtualKeyboardBps (QObject * parent = 0) explicit
Definition at line 54 of file qbbvirtualkeyboardbps.cpp.
     : QBBAbstractVirtualKeyboard(parent)
 {
     if (locale_request_events(0) != BPS_SUCCESS)
         qWarning("QBB: Failed to register for locale events");
     if (virtualkeyboard_request_events(0) != BPS_SUCCESS)
         qWarning("QBB: Failed to register for virtual keyboard events");
     int height = 0;
     if (virtualkeyboard_get_height(&height) != BPS_SUCCESS)
         qWarning("QBB: Failed to get virtual keyboard height");
     setHeight(height);
 }
Functions
applyKeyboardMode()
void QBBVirtualKeyboardBps::applyKeyboardMode (KeyboardMode mode) protected virtual
Implements QBBAbstractVirtualKeyboard.
Definition at line 106 of file qbbvirtualkeyboardbps.cpp.
Referenced by showKeyboard().
 {
     virtualkeyboard_layout_t layout = VIRTUALKEYBOARD_LAYOUT_DEFAULT;
     switch (mode) {
     case Url:
         layout = VIRTUALKEYBOARD_LAYOUT_URL;
         break;
     case Email:
         layout = VIRTUALKEYBOARD_LAYOUT_EMAIL;
         break;
     case Web:
         layout = VIRTUALKEYBOARD_LAYOUT_WEB;
         break;
     case NumPunc:
         layout = VIRTUALKEYBOARD_LAYOUT_NUM_PUNC;
         break;
     case Symbol:
         layout = VIRTUALKEYBOARD_LAYOUT_SYMBOL;
         break;
     case Phone:
         layout = VIRTUALKEYBOARD_LAYOUT_PHONE;
         break;
     case Pin:
         layout = VIRTUALKEYBOARD_LAYOUT_PIN;
         break;
     case Default: // fall through
     default:
         layout = VIRTUALKEYBOARD_LAYOUT_DEFAULT;
         break;
     }
 #if defined(QBBVIRTUALKEYBOARD_DEBUG)
     qDebug() << Q_FUNC_INFO << "mode=" << mode;
 #endif
     virtualkeyboard_change_options(layout, VIRTUALKEYBOARD_ENTER_DEFAULT);
 }
handleEvent()
bool QBBVirtualKeyboardBps::handleEvent (bps_event_t * event)
Definition at line 70 of file qbbvirtualkeyboardbps.cpp.
Referenced by QBBBpsEventFilter::bpsEventFilter().
 {
     const int eventDomain = bps_event_get_domain(event);
     if (eventDomain == locale_get_domain())
         return handleLocaleEvent(event);
     if (eventDomain == virtualkeyboard_get_domain())
         return handleVirtualKeyboardEvent(event);
     return false;
 }
handleLocaleEvent()
bool QBBVirtualKeyboardBps::handleLocaleEvent (bps_event_t * event) private
Definition at line 152 of file qbbvirtualkeyboardbps.cpp.
Referenced by handleEvent().
 {
     if (bps_event_get_code(event) == LOCALE_INFO) {
         const QString language = QString::fromAscii(locale_event_get_language(event));
         const QString country  = QString::fromAscii(locale_event_get_country(event));
 #if defined(QBBVIRTUALKEYBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "current language/country" << languageId() << "/" << countryId()
                  << "new language/country=" << language << "/" << country;
 #endif
         setLanguage(language);
         setCountry(country);
         return true;
     }
 #if defined(QBBVIRTUALKEYBOARD_DEBUG)
     qDebug() << "QBB: Unhandled locale event. code=" << bps_event_get_code(event);
 #endif
     return false;
 }
handleVirtualKeyboardEvent()
bool QBBVirtualKeyboardBps::handleVirtualKeyboardEvent (bps_event_t * event) private
Definition at line 174 of file qbbvirtualkeyboardbps.cpp.
Referenced by handleEvent().
 {
     switch (bps_event_get_code(event)) {
     case VIRTUALKEYBOARD_EVENT_VISIBLE:
         #if defined(QBBVIRTUALKEYBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "EVENT VISIBLE: current visibility=" << isVisible();
         #endif
         setVisible(true);
         break;
     case VIRTUALKEYBOARD_EVENT_HIDDEN:
         #if defined(QBBVIRTUALKEYBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "EVENT HIDDEN: current visibility=" << isVisible();
         #endif
         setVisible(false);
         break;
     case VIRTUALKEYBOARD_EVENT_INFO: {
         const int newHeight = virtualkeyboard_event_get_height(event);
         #if defined(QBBVIRTUALKEYBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "EVENT INFO: current height=" << getHeight() << "new height=" << newHeight;
         #endif
         setHeight(newHeight);
         break;
     }
     default:
         #if defined(QBBVIRTUALKEYBOARD_DEBUG)
         qDebug() << "QBB: Unhandled virtual keyboard event. code=" << bps_event_get_code(event);
         #endif
         return false;
     }
     return true;
 }
hideKeyboard()
bool QBBVirtualKeyboardBps::hideKeyboard () virtual
Implements QBBAbstractVirtualKeyboard.
Definition at line 96 of file qbbvirtualkeyboardbps.cpp.
 {
 #if defined(QBBVIRTUALKEYBOARD_DEBUG)
     qDebug() << Q_FUNC_INFO << "current visibility=" << isVisible();
 #endif
     virtualkeyboard_hide();
     return true;
 }
showKeyboard()
bool QBBVirtualKeyboardBps::showKeyboard () virtual
Implements QBBAbstractVirtualKeyboard.
Definition at line 82 of file qbbvirtualkeyboardbps.cpp.
 {
 #if defined(QBBVIRTUALKEYBOARD_DEBUG)
     qDebug() << Q_FUNC_INFO << "current visibility=" << isVisible();
 #endif
     // They keyboard's mode is global between applications, we have to set it each time
     if (!isVisible())
         applyKeyboardMode(keyboardMode());
     virtualkeyboard_show();
     return true;
 }
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbvirtualkeyboardbps.h
/src/plugins/platforms/blackberry/qbbvirtualkeyboardbps.cpp