Qt 4.8: QPatternist::NamePool Class Reference
QPatternist::NamePool Class Reference
Store names such as namespace bindings and QNames and allows them to be referenced in efficient ways.
#include <qnamepool_p.h>
Public Types
typedef QExplicitlySharedDataPointer< NamePool > Ptr
Public Functions
QXmlName allocateBinding (const QString &prefix, const QString &uri)
Allocates a namespace binding for prefix and uri.
QXmlName::LocalNameCode allocateLocalName (const QString &ln)
QXmlName::NamespaceCode allocateNamespace (const QString &uri)
QXmlName::PrefixCode allocatePrefix (const QString &prefix)
QXmlName allocateQName (const QString &uri, const QString &localName, const QString &prefix=QString())
QXmlName allocateQName (const QXmlName::NamespaceCode uri, const QString &ln)
QString displayName (const QXmlName qName) const
QXmlName fromClarkName (const QString &clarkName)
NamePool ()
const QString & stringForLocalName (const QXmlName::LocalNameCode code) const
const QString & stringForNamespace (const QXmlName::NamespaceCode code) const
const QString & stringForPrefix (const QXmlName::PrefixCode code) const
QString toClarkName (const QXmlName &name) const
QString toLexical (const QXmlName qName) const
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Private Types
enum { NoSuchValue = -1, StandardNamespaceCount = 11, StandardPrefixCount = 9, StandardLocalNameCount = 141 }
enum DefaultCapacities { DefaultPrefixCapacity = 10, DefaultURICapacity = DefaultPrefixCapacity, DefaultLocalNameCapacity = 60 }
Private Functions
const QString & displayPrefix (const QXmlName::NamespaceCode nc) const
QXmlName::LocalNameCode unlockedAllocateLocalName (const QString &ln)
QXmlName::NamespaceCode unlockedAllocateNamespace (const QString &uri)
QXmlName::PrefixCode unlockedAllocatePrefix (const QString &prefix)
Properties
QReadWriteLock lock
QHash< QString, QXmlName::LocalNameCode > m_localNameMapping
QVector< QString > m_localNames
QHash< QString, QXmlName::NamespaceCode > m_namespaceMapping
QVector< QString > m_namespaces
QVector< QString > m_prefixes
QHash< QString, QXmlName::PrefixCode > m_prefixMapping
Friends
class StandardNamespaces
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Store names such as namespace bindings and QNames and allows them to be referenced in efficient ways.
Once a string have been inserted it stays there and cannot be removed. The only way to deallocate any string in the NamePool is to deallocate the NamePool itself, as a whole.
This class is not only reentrant, it is thread-safe in all sense of the word. All functions of this class can be called concurrently. This is achieved by internal locking.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 87 of file qnamepool_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<NamePool> QPatternist::NamePool::Ptr
Definition at line 90 of file qnamepool_p.h.
Enumerations
anonymous enum
anonymous enum private
Enumerator
NoSuchValue
StandardNamespaceCount
This must be identical to the amount of members in StandardNamespaces.
StandardPrefixCount
StandardLocalNameCount
Definition at line 95 of file qnamepool_p.h.
         {
             NoSuchValue         = -1,
             StandardNamespaceCount = 11,
             StandardPrefixCount = 9,
             StandardLocalNameCount = 141
         };
DefaultCapacities
enum QPatternist::NamePool::DefaultCapacities private
Enumerator
DefaultPrefixCapacity
DefaultURICapacity
DefaultLocalNameCapacity
It looks like it's quite common with 40-60 different local names per XML vocabulary. For background, see:
http://englich.wordpress.com/2007/01/11/representing-xml/
http://englich.wordpress.com/2007/01/09/xmlstat/
Definition at line 129 of file qnamepool_p.h.
         {
             DefaultPrefixCapacity = 10,
             DefaultURICapacity = DefaultPrefixCapacity,
             DefaultLocalNameCapacity = 60
         };
Constructors and Destructors
NamePool()
NamePool::NamePool ()
Definition at line 53 of file qnamepool.cpp.
 {
     m_localNameMapping  .reserve(DefaultLocalNameCapacity   + StandardLocalNameCount);
     m_localNames        .reserve(DefaultLocalNameCapacity   + StandardLocalNameCount);
     m_namespaceMapping  .reserve(DefaultURICapacity         + StandardNamespaceCount);
     m_namespaces        .reserve(DefaultURICapacity         + StandardNamespaceCount);
     m_prefixes          .reserve(DefaultPrefixCapacity      + StandardPrefixCount);
     m_prefixMapping     .reserve(DefaultPrefixCapacity      + StandardPrefixCount);
     /* Namespaces. */
     {
         unlockedAllocateNamespace(QString());
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/2005/xpath-functions"));
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/2005/xquery-local-functions"));
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/XML/1998/namespace"));
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/2000/xmlns/"));
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/2001/XMLSchema"));
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/2001/XMLSchema-instance"));
         unlockedAllocateNamespace(QLatin1String("http://www.w3.org/1999/XSL/Transform"));
         /* For UndeclarePrefix, StopNamespaceInheritance and InternalXSLT. We use two
          * arbitrary strings that aren't used. For instance, if we just used an
          * empty QString, unlockedAllocateNamespace() would assign it
          * StandardNamespaces::empty. However, it's important that the string
          * is an invalid namespace, since otherwise user strings would get
          * assigned the same IDs. */
         unlockedAllocateNamespace(QLatin1String("  |  1  "));
         unlockedAllocateNamespace(QLatin1String("  |  2  "));
         unlockedAllocateNamespace(QLatin1String("  |  InternalXSLT"));
         Q_ASSERT_X(m_namespaces.count() == StandardNamespaceCount, Q_FUNC_INFO,
                    qPrintable(QString::fromLatin1("Expected is %1, actual is %2.").arg(StandardNamespaceCount).arg(m_namespaces.count())));
     }
     /* Prefixes. */
     {
         unlockedAllocatePrefix(QString());
         unlockedAllocatePrefix(QLatin1String("fn"));
         unlockedAllocatePrefix(QLatin1String("local"));
         unlockedAllocatePrefix(QLatin1String("xml"));
         unlockedAllocatePrefix(QLatin1String("xmlns"));
         unlockedAllocatePrefix(QLatin1String("xs"));
         unlockedAllocatePrefix(QLatin1String("xsi"));
         unlockedAllocatePrefix(QLatin1String("ns0"));
         unlockedAllocatePrefix(QLatin1String("|||")); /* Invalid NCName, for StopNamespaceInheritance. */
         Q_ASSERT_X(m_prefixes.count() == StandardPrefixCount, Q_FUNC_INFO,
                    qPrintable(QString::fromLatin1("Expected is %1, actual is %2.").arg(StandardPrefixCount).arg(m_prefixes.count())));
     }
     /* Local names. */
     {
         /* Same order as the enum in StandardLocalNames. That is, alphabetically. */
         unlockedAllocateLocalName(QLatin1String("abs"));
         unlockedAllocateLocalName(QLatin1String("adjust-dateTime-to-timezone"));
         unlockedAllocateLocalName(QLatin1String("adjust-date-to-timezone"));
         unlockedAllocateLocalName(QLatin1String("adjust-time-to-timezone"));
         unlockedAllocateLocalName(QLatin1String("all"));
         unlockedAllocateLocalName(QLatin1String("arity"));
         unlockedAllocateLocalName(QLatin1String("avg"));
         unlockedAllocateLocalName(QLatin1String("base"));
         unlockedAllocateLocalName(QLatin1String("base-uri"));
         unlockedAllocateLocalName(QLatin1String("boolean"));
         unlockedAllocateLocalName(QLatin1String("ceiling"));
         unlockedAllocateLocalName(QLatin1String("codepoint-equal"));
         unlockedAllocateLocalName(QLatin1String("codepoints-to-string"));
         unlockedAllocateLocalName(QLatin1String("collection"));
         unlockedAllocateLocalName(QLatin1String("compare"));
         unlockedAllocateLocalName(QLatin1String("concat"));
         unlockedAllocateLocalName(QLatin1String("contains"));
         unlockedAllocateLocalName(QLatin1String("count"));
         unlockedAllocateLocalName(QLatin1String("current"));
         unlockedAllocateLocalName(QLatin1String("current-date"));
         unlockedAllocateLocalName(QLatin1String("current-dateTime"));
         unlockedAllocateLocalName(QLatin1String("current-time"));
         unlockedAllocateLocalName(QLatin1String("data"));
         unlockedAllocateLocalName(QLatin1String("dateTime"));
         unlockedAllocateLocalName(QLatin1String("day-from-date"));
         unlockedAllocateLocalName(QLatin1String("day-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("days-from-duration"));
         unlockedAllocateLocalName(QLatin1String("deep-equal"));
         unlockedAllocateLocalName(QLatin1String("default"));
         unlockedAllocateLocalName(QLatin1String("default-collation"));
         unlockedAllocateLocalName(QLatin1String("distinct-values"));
         unlockedAllocateLocalName(QLatin1String("doc"));
         unlockedAllocateLocalName(QLatin1String("doc-available"));
         unlockedAllocateLocalName(QLatin1String("document"));
         unlockedAllocateLocalName(QLatin1String("document-uri"));
         unlockedAllocateLocalName(QLatin1String("element-available"));
         unlockedAllocateLocalName(QLatin1String("empty"));
         unlockedAllocateLocalName(QLatin1String("encode-for-uri"));
         unlockedAllocateLocalName(QLatin1String("ends-with"));
         unlockedAllocateLocalName(QLatin1String("error"));
         unlockedAllocateLocalName(QLatin1String("escape-html-uri"));
         unlockedAllocateLocalName(QLatin1String("exactly-one"));
         unlockedAllocateLocalName(QLatin1String("exists"));
         unlockedAllocateLocalName(QLatin1String("false"));
         unlockedAllocateLocalName(QLatin1String("floor"));
         unlockedAllocateLocalName(QLatin1String("function-available"));
         unlockedAllocateLocalName(QLatin1String("function-name"));
         unlockedAllocateLocalName(QLatin1String("generate-id"));
         unlockedAllocateLocalName(QLatin1String("generic-string-join"));
         unlockedAllocateLocalName(QLatin1String("hours-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("hours-from-duration"));
         unlockedAllocateLocalName(QLatin1String("hours-from-time"));
         unlockedAllocateLocalName(QLatin1String("id"));
         unlockedAllocateLocalName(QLatin1String("idref"));
         unlockedAllocateLocalName(QLatin1String("implicit-timezone"));
         unlockedAllocateLocalName(QLatin1String("index-of"));
         unlockedAllocateLocalName(QLatin1String("in-scope-prefixes"));
         unlockedAllocateLocalName(QLatin1String("insert-before"));
         unlockedAllocateLocalName(QLatin1String("iri-to-uri"));
         unlockedAllocateLocalName(QLatin1String("is-schema-aware"));
         unlockedAllocateLocalName(QLatin1String("key"));
         unlockedAllocateLocalName(QLatin1String("lang"));
         unlockedAllocateLocalName(QLatin1String("last"));
         unlockedAllocateLocalName(QLatin1String("local-name"));
         unlockedAllocateLocalName(QLatin1String("local-name-from-QName"));
         unlockedAllocateLocalName(QLatin1String("lower-case"));
         unlockedAllocateLocalName(QLatin1String("matches"));
         unlockedAllocateLocalName(QLatin1String("max"));
         unlockedAllocateLocalName(QLatin1String("min"));
         unlockedAllocateLocalName(QLatin1String("minutes-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("minutes-from-duration"));
         unlockedAllocateLocalName(QLatin1String("minutes-from-time"));
         unlockedAllocateLocalName(QLatin1String("month-from-date"));
         unlockedAllocateLocalName(QLatin1String("month-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("months-from-duration"));
         unlockedAllocateLocalName(QLatin1String("name"));
         unlockedAllocateLocalName(QLatin1String("namespace-uri"));
         unlockedAllocateLocalName(QLatin1String("namespace-uri-for-prefix"));
         unlockedAllocateLocalName(QLatin1String("namespace-uri-from-QName"));
         unlockedAllocateLocalName(QLatin1String("nilled"));
         unlockedAllocateLocalName(QLatin1String("node-name"));
         unlockedAllocateLocalName(QLatin1String("normalize-space"));
         unlockedAllocateLocalName(QLatin1String("normalize-unicode"));
         unlockedAllocateLocalName(QLatin1String("not"));
         unlockedAllocateLocalName(QLatin1String("number"));
         unlockedAllocateLocalName(QLatin1String("one-or-more"));
         unlockedAllocateLocalName(QLatin1String("position"));
         unlockedAllocateLocalName(QLatin1String("prefix-from-QName"));
         unlockedAllocateLocalName(QLatin1String("product-name"));
         unlockedAllocateLocalName(QLatin1String("product-version"));
         unlockedAllocateLocalName(QLatin1String("property-name"));
         unlockedAllocateLocalName(QLatin1String("QName"));
         unlockedAllocateLocalName(QLatin1String("remove"));
         unlockedAllocateLocalName(QLatin1String("replace"));
         unlockedAllocateLocalName(QLatin1String("resolve-QName"));
         unlockedAllocateLocalName(QLatin1String("resolve-uri"));
         unlockedAllocateLocalName(QLatin1String("reverse"));
         unlockedAllocateLocalName(QLatin1String("root"));
         unlockedAllocateLocalName(QLatin1String("round"));
         unlockedAllocateLocalName(QLatin1String("round-half-to-even"));
         unlockedAllocateLocalName(QLatin1String("seconds-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("seconds-from-duration"));
         unlockedAllocateLocalName(QLatin1String("seconds-from-time"));
         unlockedAllocateLocalName(QLatin1String("sourceValue"));
         unlockedAllocateLocalName(QLatin1String("starts-with"));
         unlockedAllocateLocalName(QLatin1String("static-base-uri"));
         unlockedAllocateLocalName(QLatin1String("string"));
         unlockedAllocateLocalName(QLatin1String("string-join"));
         unlockedAllocateLocalName(QLatin1String("string-length"));
         unlockedAllocateLocalName(QLatin1String("string-to-codepoints"));
         unlockedAllocateLocalName(QLatin1String("subsequence"));
         unlockedAllocateLocalName(QLatin1String("substring"));
         unlockedAllocateLocalName(QLatin1String("substring-after"));
         unlockedAllocateLocalName(QLatin1String("substring-before"));
         unlockedAllocateLocalName(QLatin1String("sum"));
         unlockedAllocateLocalName(QLatin1String("supports-backwards-compatibility"));
         unlockedAllocateLocalName(QLatin1String("supports-serialization"));
         unlockedAllocateLocalName(QLatin1String("system-property"));
         unlockedAllocateLocalName(QLatin1String("timezone-from-date"));
         unlockedAllocateLocalName(QLatin1String("timezone-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("timezone-from-time"));
         unlockedAllocateLocalName(QLatin1String("tokenize"));
         unlockedAllocateLocalName(QLatin1String("trace"));
         unlockedAllocateLocalName(QLatin1String("translate"));
         unlockedAllocateLocalName(QLatin1String("true"));
         unlockedAllocateLocalName(QLatin1String("type-available"));
         unlockedAllocateLocalName(QLatin1String("unordered"));
         unlockedAllocateLocalName(QLatin1String("unparsed-entity-public-id"));
         unlockedAllocateLocalName(QLatin1String("unparsed-entity-uri"));
         unlockedAllocateLocalName(QLatin1String("unparsed-text"));
         unlockedAllocateLocalName(QLatin1String("unparsed-text-available"));
         unlockedAllocateLocalName(QLatin1String("upper-case"));
         unlockedAllocateLocalName(QLatin1String("vendor"));
         unlockedAllocateLocalName(QLatin1String("vendor-url"));
         unlockedAllocateLocalName(QLatin1String("version"));
         unlockedAllocateLocalName(QLatin1String("xml"));
         unlockedAllocateLocalName(QLatin1String("xmlns"));
         unlockedAllocateLocalName(QLatin1String("year-from-date"));
         unlockedAllocateLocalName(QLatin1String("year-from-dateTime"));
         unlockedAllocateLocalName(QLatin1String("years-from-duration"));
         unlockedAllocateLocalName(QLatin1String("zero-or-one"));
         Q_ASSERT(m_localNames.count() == StandardLocalNameCount);
     }
 }
Functions
allocateBinding()
QXmlName NamePool::allocateBinding (const QString & prefix, const QString & uri)
Allocates a namespace binding for prefix and uri.
In the returned QXmlName, the local name is StandardLocalNames::empty, and QXmlName::prefix() and QXmlName::namespaceUri() returns prefix and uri, respectively.
In older versions of this code, the class NamespaceBinding existed, but as part of having the public class QXmlName, it was dropped and a special interpretation/convention involving use of QXmlName was adopted.
Definition at line 275 of file qnamepool.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     QWriteLocker l(&lock);
     Q_ASSERT_X(prefix.isEmpty() || QXmlUtils::isNCName(prefix), Q_FUNC_INFO,
                qPrintable(QString::fromLatin1("%1 is an invalid prefix.").arg(prefix)));
     const QXmlName::NamespaceCode nsCode = unlockedAllocateNamespace(uri);
     Q_ASSERT(prefix.isEmpty() || QXmlUtils::isNCName(prefix));
     const QXmlName::PrefixCode prefixCode = unlockedAllocatePrefix(prefix);
     return QXmlName(nsCode, StandardLocalNames::empty, prefixCode);
 }
allocateLocalName()
QXmlName::LocalNameCode QPatternist::NamePool::allocateLocalName (const QString & ln) inline
Definition at line 208 of file qnamepool_p.h.
Referenced by QPatternist::XsdInstanceReader::convertToQName(), QPatternist::XsdTypeChecker::convertToQName(), and QPatternist::NamespaceSupport::processName().
         {
             const QWriteLocker l(&lock);
             return unlockedAllocateLocalName(ln);
         }
allocateNamespace()
QXmlName::NamespaceCode QPatternist::NamePool::allocateNamespace (const QString & uri) inline
Definition at line 202 of file qnamepool_p.h.
Referenced by QPatternist::NamespaceSupport::setPrefixes(), QPatternist::XsdSchemaParser::setTargetNamespaceExtended(), termMatches(), QPatternist::FunctionAvailableFN::typeCheck(), and QPatternist::XsdValidatingInstanceReader::validateAttributeWildcard().
         {
             const QWriteLocker l(&lock);
             return unlockedAllocateNamespace(uri);
         }
allocatePrefix()
QXmlName::PrefixCode QPatternist::NamePool::allocatePrefix (const QString & prefix) inline
Definition at line 214 of file qnamepool_p.h.
Referenced by QPatternist::XsdInstanceReader::convertToQName(), QPatternist::XsdTypeChecker::convertToQName(), QPatternist::NamespaceURIForPrefixFN::evaluateSingleton(), QPatternist::NamespaceSupport::processName(), and QPatternist::NamespaceSupport::setPrefixes().
         {
             const QWriteLocker l(&lock);
             return unlockedAllocatePrefix(prefix);
         }
allocateQName() [1/2]
QXmlName NamePool::allocateQName (const QString & uri, const QString & localName, const QString & prefix = QString())
Definition at line 251 of file qnamepool.cpp.
Referenced by QPatternist::XsdSchema::addAnonymousType(), QPatternist::XsdSchemaParserContext::createAnonymousName(), QPatternist::URILoader::createRequest(), QPatternist::QNameFN::evaluateSingleton(), QPatternist::ProcessingInstructionConstructor::evaluateTardata(), fromClarkName(), QPatternist::AnyType::name(), QPatternist::AnySimpleType::name(), QPatternist::Untyped::name(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseUnique(), QXmlName::QXmlName(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::XsdSchemaTypesFactory::XsdSchemaTypesFactory(), and QPatternist::XsdValidatingInstanceReader::XsdValidatingInstanceReader().
 {
     QWriteLocker l(&lock);
     /*
     QString codepoints;
     for(int i = 0; i < localName.length(); ++i)
         codepoints.append(QString::number(localName.at(i).unicode()) + QLatin1Char(' '));
     pDebug() << Q_FUNC_INFO << localName << "codepoints:" << codepoints;
     */
     Q_ASSERT_X(QXmlUtils::isNCName(localName), Q_FUNC_INFO,
                qPrintable(QString::fromLatin1("'%1' is an invalid NCName.").arg(localName)));
     const QXmlName::NamespaceCode nsCode = unlockedAllocateNamespace(uri);
     const QXmlName::LocalNameCode localCode  = unlockedAllocateLocalName(localName);
     Q_ASSERT(prefix.isEmpty() || QXmlUtils::isNCName(prefix));
     const QXmlName::PrefixCode prefixCode = unlockedAllocatePrefix(prefix);
     return QXmlName(nsCode, localCode, prefixCode);
 }
allocateQName() [2/2]
QXmlName QPatternist::NamePool::allocateQName (const QXmlName::NamespaceCode uri, const QString & ln) inline
Definition at line 162 of file qnamepool_p.h.
         {
             /* We don't lock here, but we do in allocateLocalName(). */
             return QXmlName(uri, allocateLocalName(ln));
         }
displayName()
QString NamePool::displayName (const QXmlName qName) const
Definition at line 347 of file qnamepool.cpp.
Referenced by QPatternist::XsdSchemaParser::addAttribute(), QPatternist::XsdSchemaParser::addElement(), QPatternist::QNameTest::displayName(), QPatternist::AnySimpleType::displayName(), QPatternist::XsdSimpleType::displayName(), QPatternist::NamedSchemaComponent::displayName(), QPatternist::FunctionSignature::displayName(), QPatternist::XsdComplexType::displayName(), QPatternist::AccelTree::printStats(), QPatternist::XsdValidatingInstanceReader::qNameAttribute(), QPatternist::XsdValidatingInstanceReader::read(), QPatternist::XsdValidatingInstanceReader::validate(), and QPatternist::XsdValidatingInstanceReader::validateElementComplexType().
 {
     QReadLocker l(&lock);
     if(qName.hasNamespace())
     {
         if(qName.namespaceURI() == StandardNamespaces::InternalXSLT)
             return QLatin1Char('#') + m_localNames.at(qName.localName());
         const QString &p = displayPrefix(qName.namespaceURI());
         if(p.isEmpty())
             return QLatin1Char('{') + m_namespaces.at(qName.namespaceURI()) + QLatin1Char('}') + toLexical(qName);
         else
             return p + QLatin1Char(':') + m_localNames.at(qName.localName());
     }
     else
         return m_localNames.at(qName.localName());
 }
displayPrefix()
const QString & NamePool::displayPrefix (const QXmlName::NamespaceCode nc) const private
Note
This function can not be called concurrently.
Definition at line 334 of file qnamepool.cpp.
Referenced by displayName().
 {
     switch(nc)
     {
         case StandardNamespaces::xmlns: return m_prefixes.at(StandardPrefixes::xmlns);
         case StandardNamespaces::local: return m_prefixes.at(StandardPrefixes::local);
         case StandardNamespaces::xs:    return m_prefixes.at(StandardPrefixes::xs);
         case StandardNamespaces::xml:   return m_prefixes.at(StandardPrefixes::xml);
         case StandardNamespaces::fn:    return m_prefixes.at(StandardPrefixes::fn);
         default:                        return m_prefixes.at(StandardPrefixes::empty);
     }
 }
fromClarkName()
QXmlName NamePool::fromClarkName (const QString & clarkName)
Definition at line 389 of file qnamepool.cpp.
Referenced by QXmlName::fromClarkName().
 {
     if(clarkName.isEmpty())
         return QXmlName();
     if(clarkName.at(0) == QLatin1Char('{'))
     {
         const int indexOfRight = clarkName.indexOf(QLatin1Char('}'));
         const QString qName(clarkName.right((clarkName.length() - indexOfRight) - 1));
         if(!XPathHelper::isQName(qName))
             return QXmlName();
         QString localName;
         QString prefix;
         XPathHelper::splitQName(qName, prefix, localName);
         return allocateQName(clarkName.mid(1, indexOfRight - 1),
                                          localName, prefix);
     }
     else
     {
         if(QXmlName::isNCName(clarkName))
             return allocateQName(QString(), clarkName);
         else
             return QXmlName();
     }
 }
stringForLocalName()
const QString& QPatternist::NamePool::stringForLocalName (const QXmlName::LocalNameCode code) const inline
Definition at line 168 of file qnamepool_p.h.
Referenced by QPatternist::XsdSchema::addAnonymousType(), QXmlQuery::bindVariable(), QPatternist::LocalNameTest::displayName(), QPatternist::ReportContext::error(), QPatternist::LocalNameFN::evaluateSingleton(), QPatternist::LocalNameFromQNameFN::evaluateSingleton(), QXmlName::localName(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), and toClarkName().
         {
             const QReadLocker l(&lock);
             return m_localNames.at(code);
         }
stringForNamespace()
const QString& QPatternist::NamePool::stringForNamespace (const QXmlName::NamespaceCode code) const inline
Definition at line 180 of file qnamepool_p.h.
Referenced by QPatternist::NamespaceNameTest::displayName(), QPatternist::NamespaceURIFN::evaluateSingleton(), QPatternist::NamespaceURIFromQNameFN::evaluateSingleton(), QPatternist::NamespaceURIForPrefixFN::evaluateSingleton(), QXmlName::namespaceUri(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::AccelTree::printStats(), QPatternist::XsdSchemaParser::readXPathExpression(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), toClarkName(), QPatternist::XsdValidatingInstanceReader::validate(), and QPatternist::XsdSchemaHelper::wildcardAllowsExpandedName().
         {
             const QReadLocker l(&lock);
             return m_namespaces.at(code);
         }
stringForPrefix()
const QString& QPatternist::NamePool::stringForPrefix (const QXmlName::PrefixCode code) const inline
Definition at line 174 of file qnamepool_p.h.
Referenced by QPatternist::PrefixFromQNameFN::evaluateSingleton(), QPatternist::QNameConstructor::namespaceForPrefix(), QXmlName::prefix(), QPatternist::AccelTree::printStats(), and toClarkName().
         {
             const QReadLocker l(&lock);
             return m_prefixes.at(code);
         }
toClarkName()
QString NamePool::toClarkName (const QXmlName & name) const
Definition at line 367 of file qnamepool.cpp.
Referenced by QXmlName::toClarkName().
 {
     if(name.isNull())
         return QLatin1String("QXmlName(null)");
     else
     {
         if(name.hasNamespace())
         {
             const QString ns(stringForNamespace(name.namespaceURI()));
             const QString p(stringForPrefix(name.prefix()));
             const QString l(stringForLocalName(name.localName()));
             return   QChar::fromLatin1('{')
                    + ns
                    + QChar::fromLatin1('}')
                    + (p.isEmpty() ? l : p + QChar::fromLatin1(':') + l);
         }
         else
             return stringForLocalName(name.localName());
     }
 }
toLexical()
QString QPatternist::NamePool::toLexical (const QXmlName qName) const inline
Definition at line 188 of file qnamepool_p.h.
Referenced by displayName(), QPatternist::NameFN::evaluateSingleton(), and QPatternist::QNameValue::stringValue().
         {
             const QReadLocker l(&lock);
             Q_ASSERT_X(!qName.isNull(), "", "It makes no sense to call toLexical() on a null name.");
             if(qName.hasPrefix())
             {
                 const QString &p = m_prefixes.at(qName.prefix());
                 return p + QLatin1Char(':') + m_localNames.at(qName.localName());
             }
             else
                 return m_localNames.at(qName.localName());
         }
unlockedAllocateLocalName()
QXmlName::LocalNameCode NamePool::unlockedAllocateLocalName (const QString & ln) private
Note
This function can not be called concurrently.
Definition at line 289 of file qnamepool.cpp.
Referenced by allocateQName(), and NamePool().
 {
     Q_ASSERT_X(QXmlUtils::isNCName(ln), Q_FUNC_INFO,
                qPrintable(QString::fromLatin1("Invalid local name: \"%1\"").arg(ln)));
     int indexInLocalNames = m_localNameMapping.value(ln, NoSuchValue);
     if(indexInLocalNames == NoSuchValue)
     {
         indexInLocalNames = m_localNames.count();
         m_localNames.append(ln);
         m_localNameMapping.insert(ln, indexInLocalNames);
     }
     return indexInLocalNames;
 }
unlockedAllocateNamespace()
QXmlName::NamespaceCode NamePool::unlockedAllocateNamespace (const QString & uri) private
Note
This function can not be called concurrently.
Definition at line 320 of file qnamepool.cpp.
Referenced by allocateBinding(), allocateQName(), and NamePool().
 {
     int indexInURIs = m_namespaceMapping.value(uri, NoSuchValue);
     if(indexInURIs == NoSuchValue)
     {
         indexInURIs = m_namespaces.count();
         m_namespaces.append(uri);
         m_namespaceMapping.insert(uri, indexInURIs);
     }
     return indexInURIs;
 }
unlockedAllocatePrefix()
QXmlName::PrefixCode NamePool::unlockedAllocatePrefix (const QString & prefix) private
It's assumed that prefix is a valid NCName.
Note
This function can not be called concurrently.
Definition at line 306 of file qnamepool.cpp.
Referenced by allocateBinding(), allocateQName(), and NamePool().
 {
     int indexInPrefixes = m_prefixMapping.value(prefix, NoSuchValue);
     if(indexInPrefixes == NoSuchValue)
     {
         indexInPrefixes = m_prefixes.count();
         m_prefixes.append(prefix);
         m_prefixMapping.insert(prefix, indexInPrefixes);
     }
     return indexInPrefixes;
 }
Friends and Related Functions
StandardNamespaces
friend class StandardNamespaces friend
Definition at line 93 of file qnamepool_p.h.
Properties
lock
QReadWriteLock QPatternist::NamePool::lock mutable private
Definition at line 248 of file qnamepool_p.h.
Referenced by allocateBinding(), allocateQName(), and displayName().
m_localNameMapping
QHash<QString, QXmlName::LocalNameCode> QPatternist::NamePool::m_localNameMapping private
Definition at line 127 of file qnamepool_p.h.
Referenced by NamePool(), and unlockedAllocateLocalName().
m_localNames
QVector<QString> QPatternist::NamePool::m_localNames private
Definition at line 109 of file qnamepool_p.h.
Referenced by displayName(), NamePool(), and unlockedAllocateLocalName().
m_namespaceMapping
QHash<QString, QXmlName::NamespaceCode> QPatternist::NamePool::m_namespaceMapping private
Same as m_prefixMapping but applies for URIs, and hence m_namespaces instead of m_prefixes.
Definition at line 125 of file qnamepool_p.h.
Referenced by NamePool(), and unlockedAllocateNamespace().
m_namespaces
QVector<QString> QPatternist::NamePool::m_namespaces private
Definition at line 108 of file qnamepool_p.h.
Referenced by displayName(), NamePool(), and unlockedAllocateNamespace().
m_prefixes
QVector<QString> QPatternist::NamePool::m_prefixes private
Definition at line 107 of file qnamepool_p.h.
Referenced by displayPrefix(), NamePool(), and unlockedAllocatePrefix().
m_prefixMapping
QHash<QString, QXmlName::PrefixCode> QPatternist::NamePool::m_prefixMapping private
This hash contains no essential data, but speeds up finding a prefix in m_prefixes by mapping a prefix(the key) to the index into m_prefixes(which the value is).
In other words, one can skip this variable at the cost of having to linearly loop over prefixes, in order to find the entry.
Definition at line 119 of file qnamepool_p.h.
Referenced by NamePool(), and unlockedAllocatePrefix().
The documentation for this class was generated from the following files:
/src/xmlpatterns/utils/qnamepool_p.h
/src/xmlpatterns/utils/qnamepool.cpp