Qt 4.8: QButtonGroup Class Reference
QButtonGroup Class Reference
The QButtonGroup class provides a container to organize groups of button widgets.
#include <qbuttongroup.h>
Signals
void buttonClicked (QAbstractButton *)
This signal is emitted when the given button is clicked.
void buttonClicked (int)
This signal is emitted when a button with the given id is clicked.
void buttonPressed (QAbstractButton *)
void buttonPressed (int)
This signal is emitted when a button with the given id is pressed down.
void buttonReleased (QAbstractButton *)
void buttonReleased (int)
This signal is emitted when a button with the given id is released.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addButton (QAbstractButton *)
Adds the given button to the end of the group's internal list of buttons.
void addButton (QAbstractButton *, int id)
Adds the given button to the button group, with the given id.
QAbstractButton * button (int id) const
QList< QAbstractButton * > buttons () const
Returns the list of this groups's buttons.
QAbstractButton * checkedButton () const
Returns the button group's checked button, or 0 if no buttons are checked.
int checkedId () const
Returns the id of the checkedButton(), or -1 if no button is checked.
bool exclusive () const
int id (QAbstractButton *button) const
QButtonGroup (QObject *parent=0)
Constructs a new, empty button group with the given parent.
void removeButton (QAbstractButton *)
Removes the given button from the button group.
void setExclusive (bool)
void setId (QAbstractButton *button, int id)
~QButtonGroup ()
Destroys the button group.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool exclusive
whether the button group is exclusive
Friends
class QAbstractButton
class QAbstractButtonPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QButtonGroup class provides a container to organize groups of button widgets.
QButtonGroup provides an abstract container into which button widgets can be placed. It does not provide a visual representation of this container (see QGroupBox for a container widget), but instead manages the states of each of the buttons in the group.
An QButtonGroup::exclusive {exclusive} button group switches off all checkable (toggle) buttons except the one that was clicked. By default, a button group is exclusive. The buttons in a button group are usually checkable QPushButton's, (normally for non-exclusive button groups), or QRadioButton . If you create an exclusive button group, you should ensure that one of the buttons in the group is initially checked; otherwise, the group will initially be in a state where no buttons are checked.
A button is added to the group with addButton(). It can be removed from the group with removeButton(). If the group is exclusive, the currently checked button is available as checkedButton(). If a button is clicked the buttonClicked() signal is emitted. For a checkable button in an exclusive group this means that the button was checked. The list of buttons in the group is returned by buttons().
In addition, QButtonGroup can map between integers and buttons. You can assign an integer id to a button with setId(), and retrieve it with id(). The id of the currently checked button is available with checkedId(), and there is an overloaded signal buttonClicked() which emits the id of the button. The id {-1} is reserved by QButtonGroup to mean "no such button". The purpose of the mapping mechanism is to simplify the representation of enum values in a user interface.
See also
QGroupBox QPushButton, QCheckBox, QRadioButton
Definition at line 59 of file qbuttongroup.h.
Constructors and Destructors
QButtonGroup()
QButtonGroup::QButtonGroup (QObject * parent = 0) explicit
Constructs a new, empty button group with the given parent.
See also
addButton() setExclusive()
Definition at line 198 of file qabstractbutton.cpp.
     : QObject(*new QButtonGroupPrivate, parent)
 {
 }
~QButtonGroup()
QButtonGroup::~QButtonGroup ()
Destroys the button group.
Definition at line 203 of file qabstractbutton.cpp.
 {
     Q_D(QButtonGroup);
     for (int i = 0; i < d->buttonList.count(); ++i)
         d->buttonList.at(i)->d_func()->group = 0;
 }
Functions
addButton() [1/2]
void QButtonGroup::addButton (QAbstractButton * button)
Adds the given button to the end of the group's internal list of buttons.
An id will be assigned to the button by this QButtonGroup. Automatically assigned ids are guaranteed to be negative, starting with -2. If you are also assigning your own ids, use positive values to avoid conflicts.
See also
removeButton() buttons()
Definition at line 225 of file qabstractbutton.cpp.
Referenced by QPrintDialogPrivate::setupDestination(), and QPrintDialogPrivate::setupPrinterSettings().
 {
     addButton(button, -1);
 }
addButton() [2/2]
void QButtonGroup::addButton (QAbstractButton * button, int id)
Adds the given button to the button group, with the given id.
It is recommended to assign only positive ids.
See also
removeButton() buttons()
Definition at line 230 of file qabstractbutton.cpp.
 {
     Q_D(QButtonGroup);
     if (QButtonGroup *previous = button->d_func()->group)
         previous->removeButton(button);
     button->d_func()->group = this;
     d->buttonList.append(button);
     if (id == -1) {
         QList<int> ids = d->mapping.values();
         if (ids.isEmpty())
            d->mapping[button] = -2;
         else {
             qSort(ids);
             d->mapping[button] = ids.first()-1;
         }
     } else {
         d->mapping[button] = id;
     }
     if (d->exclusive && button->isChecked())
         button->d_func()->notifyChecked();
 }
button()
QAbstractButton * QButtonGroup::button (int id) const
Since
4.1
Returns the button with the specified id, or 0 if no such button exists.
Definition at line 278 of file qabstractbutton.cpp.
Referenced by addButton(), QAbstractButtonPrivate::moveFocus(), and setId().
 {
     Q_D(const QButtonGroup);
     return d->mapping.key(id);
 }
buttonClicked [1/2]
void QButtonGroup::buttonClicked (QAbstractButton * button) signal
This signal is emitted when the given button is clicked.
A button is clicked when it is first pressed and then released, when its shortcut key is typed, or programmatically when QAbstractButton::click() or QAbstractButton::animateClick() is called.
See also
checkedButton(), QAbstractButton::clicked()
buttonClicked [2/2]
void QButtonGroup::buttonClicked (int id) signal
This signal is emitted when a button with the given id is clicked.
See also
checkedButton(), QAbstractButton::clicked()
buttonPressed [1/2]
void QButtonGroup::buttonPressed (QAbstractButton * button) signal
Since
4.2
This signal is emitted when the given button is pressed down.
See also
QAbstractButton::pressed()
buttonPressed [2/2]
void QButtonGroup::buttonPressed (int id) signal
This signal is emitted when a button with the given id is pressed down.
Since
4.2
See also
QAbstractButton::pressed()
buttonReleased [1/2]
void QButtonGroup::buttonReleased (QAbstractButton * button) signal
Since
4.2
This signal is emitted when the given button is released.
See also
QAbstractButton::released()
buttonReleased [2/2]
void QButtonGroup::buttonReleased (int id) signal
This signal is emitted when a button with the given id is released.
Since
4.2
See also
QAbstractButton::released()
buttons()
QList< QAbstractButton * > QButtonGroup::buttons () const
Returns the list of this groups's buttons.
This may be empty.
See also
addButton(), removeButton()
Definition at line 266 of file qabstractbutton.cpp.
 {
     Q_D(const QButtonGroup);
     return d->buttonList;
 }
checkedButton()
QAbstractButton * QButtonGroup::checkedButton () const
Returns the button group's checked button, or 0 if no buttons are checked.
See also
buttonClicked()
Definition at line 272 of file qabstractbutton.cpp.
Referenced by QButtonGroupPrivate::detectCheckedButton().
 {
     Q_D(const QButtonGroup);
     return d->checkedButton;
 }
checkedId()
int QButtonGroup::checkedId () const
Returns the id of the checkedButton(), or -1 if no button is checked.
Since
4.1
See also
setId()
Definition at line 297 of file qabstractbutton.cpp.
 {
     Q_D(const QButtonGroup);
     return d->mapping.value(d->checkedButton, -1);
 }
exclusive()
bool QButtonGroup::exclusive () const
Referenced by QButtonGroupPrivate::detectCheckedButton(), QAbstractButtonPrivate::moveFocus(), setExclusive(), and ~QButtonGroup().
id()
int QButtonGroup::id (QAbstractButton * button) const
Since
4.1
Returns the id for the specified button, or -1 if no such button exists.
See also
setId()
Definition at line 291 of file qabstractbutton.cpp.
Referenced by addButton(), and setId().
 {
     Q_D(const QButtonGroup);
     return d->mapping.value(button, -1);
 }
removeButton()
void QButtonGroup::removeButton (QAbstractButton * button)
Removes the given button from the button group.
See also
addButton() buttons()
Definition at line 253 of file qabstractbutton.cpp.
 {
     Q_D(QButtonGroup);
     if (d->checkedButton == button) {
         d->detectCheckedButton();
     }
     if (button->d_func()->group == this) {
         button->d_func()->group = 0;
         d->buttonList.removeAll(button);
         d->mapping.remove(button);
     }
 }
setExclusive()
void QButtonGroup::setExclusive (bool exclusive)
Definition at line 217 of file qabstractbutton.cpp.
 {
     Q_D(QButtonGroup);
     d->exclusive = exclusive;
 }
setId()
void QButtonGroup::setId (QAbstractButton * button, int id)
Since
4.1
Sets the id for the specified button. Note that id can not be -1.
See also
id()
Definition at line 284 of file qabstractbutton.cpp.
 {
     Q_D(QButtonGroup);
     if (button && id != -1)
         d->mapping[button] = id;
 }
Friends and Related Functions
QAbstractButton
friend class QAbstractButton friend
Definition at line 102 of file qbuttongroup.h.
QAbstractButtonPrivate
friend class QAbstractButtonPrivate friend
Definition at line 103 of file qbuttongroup.h.
Properties
exclusive
QButtonGroup::exclusive private
whether the button group is exclusive
If this property is true then only one button in the group can be checked at any given time. The user can click on any button to check it, and that button will replace the existing one as the checked button in the group.
In an exclusive group, the user cannot uncheck the currently checked button by clicking on it; instead, another button in the group must be clicked to set the new checked button for that group.
By default, this property is true.
Definition at line 63 of file qbuttongroup.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qbuttongroup.h
/src/gui/widgets/qabstractbutton.cpp
/src/gui/widgets/qbuttongroup.cpp