Qt 4.8: QDeclarativeListView Class Reference
QDeclarativeListView Class Reference
#include <qdeclarativelistview_p.h>
Public Types
enum HighlightRangeMode { NoHighlightRange, ApplyRange, StrictlyEnforceRange }
enum Orientation { Horizontal = Qt::Horizontal, Vertical = Qt::Vertical }
enum PositionMode {
Beginning, Center, End, Visible,
Contain
}
enum SnapMode { NoSnap, SnapToItem, SnapOneItem }
Public Types inherited from QDeclarativeFlickable
enum BoundsBehavior { StopAtBounds, DragOverBounds, DragAndOvershootBounds }
enum FlickableDirection { AutoFlickDirection =0x00, HorizontalFlick =0x01, VerticalFlick =0x02, HorizontalAndVerticalFlick =0x03 }
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
void decrementCurrentIndex ()
void incrementCurrentIndex ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void cacheBufferChanged ()
void countChanged ()
void currentIndexChanged ()
void currentSectionChanged ()
void delegateChanged ()
void footerChanged ()
void headerChanged ()
void highlightChanged ()
void highlightFollowsCurrentItemChanged ()
void highlightItemChanged ()
void highlightMoveDurationChanged ()
void highlightMoveSpeedChanged ()
void highlightRangeModeChanged ()
void highlightResizeDurationChanged ()
void highlightResizeSpeedChanged ()
void keyNavigationWrapsChanged ()
void layoutDirectionChanged ()
void modelChanged ()
void orientationChanged ()
void preferredHighlightBeginChanged ()
void preferredHighlightEndChanged ()
void snapModeChanged ()
void spacingChanged ()
Signals inherited from QDeclarativeFlickable
void boundsBehaviorChanged ()
void contentHeightChanged ()
void contentWidthChanged ()
void contentXChanged ()
void contentYChanged ()
void flickableDirectionChanged ()
void flickDecelerationChanged ()
void flickEnded ()
void flickingChanged ()
void flickingHorizontallyChanged ()
void flickingVerticallyChanged ()
void flickStarted ()
void horizontalVelocityChanged ()
void interactiveChanged ()
void isAtBoundaryChanged ()
void maximumFlickVelocityChanged ()
void movementEnded ()
void movementStarted ()
void movingChanged ()
void movingHorizontallyChanged ()
void movingVerticallyChanged ()
void pressDelayChanged ()
void verticalVelocityChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int cacheBuffer () const
int count () const
int currentIndex () const
QDeclarativeItem * currentItem ()
QString currentSection () const
QDeclarativeComponent * delegate () const
Qt::LayoutDirection effectiveLayoutDirection () const
QDeclarativeComponent * footer () const
QDeclarativeComponent * header () const
QDeclarativeComponent * highlight () const
bool highlightFollowsCurrentItem () const
QDeclarativeItem * highlightItem ()
int highlightMoveDuration () const
qreal highlightMoveSpeed () const
HighlightRangeMode highlightRangeMode () const
int highlightResizeDuration () const
qreal highlightResizeSpeed () const
Q_INVOKABLE int indexAt (qreal x, qreal y) const
bool isWrapEnabled () const
Qt::LayoutDirection layoutDirection () const
QVariant model () const
Orientation orientation () const
Q_INVOKABLE void positionViewAtBeginning ()
Q_INVOKABLE void positionViewAtEnd ()
Q_INVOKABLE void positionViewAtIndex (int index, int mode)
qreal preferredHighlightBegin () const
qreal preferredHighlightEnd () const
QDeclarativeListView (QDeclarativeItem *parent=0)
void resetPreferredHighlightBegin ()
void resetPreferredHighlightEnd ()
QDeclarativeViewSection * sectionCriteria ()
void setCacheBuffer (int)
virtual void setContentX (qreal pos)
virtual void setContentY (qreal pos)
void setCurrentIndex (int idx)
void setDelegate (QDeclarativeComponent *)
void setFooter (QDeclarativeComponent *)
void setHeader (QDeclarativeComponent *)
void setHighlight (QDeclarativeComponent *highlight)
void setHighlightFollowsCurrentItem (bool)
void setHighlightMoveDuration (int)
void setHighlightMoveSpeed (qreal)
void setHighlightRangeMode (HighlightRangeMode mode)
void setHighlightResizeDuration (int)
void setHighlightResizeSpeed (qreal)
void setLayoutDirection (Qt::LayoutDirection)
void setModel (const QVariant &)
void setOrientation (Orientation)
void setPreferredHighlightBegin (qreal)
void setPreferredHighlightEnd (qreal)
void setSnapMode (SnapMode mode)
void setSpacing (qreal spacing)
void setWrapEnabled (bool)
SnapMode snapMode () const
qreal spacing () const
~QDeclarativeListView ()
Public Functions inherited from QDeclarativeFlickable
BoundsBehavior boundsBehavior () const
qreal contentHeight () const
QDeclarativeItem * contentItem ()
qreal contentWidth () const
qreal contentX () const
qreal contentY () const
QDeclarativeListProperty< QGraphicsObject > flickableChildren ()
QDeclarativeListProperty< QObject > flickableData ()
FlickableDirection flickableDirection () const
qreal flickDeceleration () const
qreal horizontalVelocity () const
bool isAtXBeginning () const
bool isAtXEnd () const
bool isAtYBeginning () const
bool isAtYEnd () const
bool isFlicking () const
bool isFlickingHorizontally () const
bool isFlickingVertically () const
bool isInteractive () const
bool isMoving () const
bool isMovingHorizontally () const
bool isMovingVertically () const
qreal maximumFlickVelocity () const
int pressDelay () const
QDeclarativeFlickable (QDeclarativeItem *parent=0)
Q_INVOKABLE void resizeContent (qreal w, qreal h, QPointF center)
Q_INVOKABLE void returnToBounds ()
void setBoundsBehavior (BoundsBehavior)
void setContentHeight (qreal)
void setContentWidth (qreal)
void setFlickableDirection (FlickableDirection)
void setFlickDeceleration (qreal)
void setInteractive (bool)
void setMaximumFlickVelocity (qreal)
void setPressDelay (int delay)
qreal verticalVelocity () const
~QDeclarativeFlickable ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Static Public Functions
static QDeclarativeListViewAttached * qmlAttachedProperties (QObject *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void componentComplete ()
virtual bool event (QEvent *event)
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
virtual void keyPressEvent (QKeyEvent *)
virtual qreal maxXExtent () const
virtual qreal maxYExtent () const
virtual qreal minXExtent () const
virtual qreal minYExtent () const
virtual void viewportMoved ()
Protected Functions inherited from QDeclarativeFlickable
void cancelFlick ()
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void movementXEnding ()
void movementYEnding ()
QDeclarativeFlickable (QDeclarativeFlickablePrivate &dd, QDeclarativeItem *parent)
bool sceneEvent (QEvent *event)
virtual bool sceneEventFilter (QGraphicsItem *, QEvent *)
Filters events for the item watched.
bool sendMouseEvent (QGraphicsSceneMouseEvent *event)
void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
qreal vHeight () const
QDeclarativeFlickableVisibleArea * visibleArea ()
qreal vWidth () const
void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
bool xflick () const
bool yflick () const
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
Private Slots
void animStopped ()
void createdItem (int index, QDeclarativeItem *item)
void destroyingItem (QDeclarativeItem *item)
void destroyRemoved ()
void itemsChanged (int index, int count)
void itemsInserted (int index, int count)
void itemsMoved (int from, int to, int count)
void itemsRemoved (int index, int count)
void modelReset ()
void refill ()
void trackedPositionChanged ()
void updateSections ()
Properties
int cacheBuffer
int count
int currentIndex
QDeclarativeItem * currentItem
QString currentSection
QDeclarativeComponent * delegate
QDeclarativeComponent * footer
QDeclarativeComponent * header
QDeclarativeComponent * highlight
bool highlightFollowsCurrentItem
QDeclarativeItem * highlightItem
int highlightMoveDuration
qreal highlightMoveSpeed
HighlightRangeMode highlightRangeMode
int highlightResizeDuration
qreal highlightResizeSpeed
bool keyNavigationWraps
Qt::LayoutDirection layoutDirection
QVariant model
Orientation orientation
qreal preferredHighlightBegin
qreal preferredHighlightEnd
QDeclarativeViewSection * section
SnapMode snapMode
qreal spacing
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QDeclarativeFlickable
void movementEnding ()
void movementStarting ()
virtual void ticked ()
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 91 of file qdeclarativelistview_p.h.
Enumerations
HighlightRangeMode
enum QDeclarativeListView::HighlightRangeMode
Enumerator
NoHighlightRange
ApplyRange
StrictlyEnforceRange
Definition at line 156 of file qdeclarativelistview_p.h.
 { NoHighlightRange, ApplyRange, StrictlyEnforceRange };
Orientation
enum QDeclarativeListView::Orientation
Enumerator
Horizontal
Vertical
Definition at line 171 of file qdeclarativelistview_p.h.
 { Horizontal = Qt::Horizontal, Vertical = Qt::Vertical };
PositionMode
enum QDeclarativeListView::PositionMode
Enumerator
Beginning
Center
End
Visible
Contain
Definition at line 215 of file qdeclarativelistview_p.h.
 { Beginning, Center, End, Visible, Contain };
SnapMode
enum QDeclarativeListView::SnapMode
Enumerator
NoSnap
SnapToItem
SnapOneItem
Definition at line 200 of file qdeclarativelistview_p.h.
 { NoSnap, SnapToItem, SnapOneItem };
Constructors and Destructors
QDeclarativeListView()
QDeclarativeListView::QDeclarativeListView (QDeclarativeItem * parent = 0)
Definition at line 1630 of file qdeclarativelistview.cpp.
     : QDeclarativeFlickable(*(new QDeclarativeListViewPrivate), parent)
 {
     Q_D(QDeclarativeListView);
     d->init();
 }
~QDeclarativeListView()
QDeclarativeListView::~QDeclarativeListView ()
Definition at line 1637 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->clear();
     if (d->ownModel)
         delete d->model;
     delete d->header;
     delete d->footer;
 }
Functions
animStopped
void QDeclarativeListView::animStopped () private slot
Definition at line 3731 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->bufferMode = QDeclarativeListViewPrivate::NoBuffer;
     if (d->haveHighlightRange && d->highlightRange == QDeclarativeListView::StrictlyEnforceRange)
         d->updateHighlight();
 }
cacheBuffer()
int QDeclarativeListView::cacheBuffer () const
Referenced by setWrapEnabled().
cacheBufferChanged
void QDeclarativeListView::cacheBufferChanged () signal
Referenced by setCacheBuffer().
componentComplete()
void QDeclarativeListView::componentComplete () protected virtual
Warning
This function is not part of the public interface.
componentComplete() is called when all items in the component have been constructed. It is often desirable to delay some processing until the component is complete an all bindings in the component have been resolved.
Reimplemented from QDeclarativeItem.
Definition at line 3191 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     QDeclarativeFlickable::componentComplete();
     updateSections();
     d->updateHeader();
     d->updateFooter();
     if (d->isValid()) {
         refill();
         d->moveReason = QDeclarativeListViewPrivate::SetIndex;
         if (d->currentIndex < 0 && !d->currentIndexCleared)
             d->updateCurrent(0);
         else
             d->updateCurrent(d->currentIndex);
         if (d->highlight && d->currentItem) {
             if (d->autoHighlight)
                 d->highlight->setPosition(d->currentItem->position());
             d->updateTrackedItem();
         }
         d->moveReason = QDeclarativeListViewPrivate::Other;
         d->fixupPosition();
     }
 }
count()
int QDeclarativeListView::count () const
Referenced by decrementCurrentIndex(), incrementCurrentIndex(), itemsInserted(), itemsMoved(), itemsRemoved(), and setCurrentIndex().
countChanged
void QDeclarativeListView::countChanged () signal
Referenced by itemsInserted(), itemsRemoved(), modelReset(), setDelegate(), and setModel().
createdItem
void QDeclarativeListView::createdItem (int index, QDeclarativeItem * item) private slot
Definition at line 3708 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     if (d->requestedIndex != index) {
         item->setParentItem(contentItem());
         d->unrequestedItems.insert(item, index);
         if (d->orient == QDeclarativeListView::Vertical) {
             item->setY(d->positionAt(index));
         } else {
             if (d->isRightToLeft())
                 item->setX(-d->positionAt(index)-item->width());
             else
                 item->setX(d->positionAt(index));
         }
     }
 }
currentIndex()
int QDeclarativeListView::currentIndex () const
Referenced by decrementCurrentIndex(), incrementCurrentIndex(), keyPressEvent(), and setDelegate().
currentIndexChanged
void QDeclarativeListView::currentIndexChanged () signal
Referenced by itemsInserted(), itemsMoved(), itemsRemoved(), and setCurrentIndex().
currentItem()
QDeclarativeItem* QDeclarativeListView::currentItem ()
Referenced by QDeclarativeListViewPrivate::positionViewAtIndex(), setCurrentIndex(), and trackedPositionChanged().
currentSection()
QString QDeclarativeListView::currentSection () const
Referenced by sectionCriteria().
currentSectionChanged
void QDeclarativeListView::currentSectionChanged () signal
decrementCurrentIndex
void QDeclarativeListView::decrementCurrentIndex () slot
Definition at line 2988 of file qdeclarativelistview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDeclarativeListView);
     int count = d->model ? d->model->count() : 0;
     if (count && (currentIndex() > 0 || d->wrap)) {
         d->moveReason = QDeclarativeListViewPrivate::SetIndex;
         int index = currentIndex()-1;
         setCurrentIndex((index >= 0 && index < count) ? index : count-1);
     }
 }
delegate()
QDeclarativeComponent* QDeclarativeListView::delegate () const
Referenced by setDelegate(), and setModel().
delegateChanged
void QDeclarativeListView::delegateChanged () signal
Referenced by setDelegate().
destroyingItem
void QDeclarativeListView::destroyingItem (QDeclarativeItem * item) private slot
Definition at line 3725 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     d->unrequestedItems.remove(item);
 }
destroyRemoved
void QDeclarativeListView::destroyRemoved () private slot
Definition at line 3558 of file qdeclarativelistview.cpp.
Referenced by itemsRemoved().
 {
     Q_D(QDeclarativeListView);
     for (QList<FxListItem*>::Iterator it = d->visibleItems.begin();
             it != d->visibleItems.end();) {
         FxListItem *listItem = *it;
         if (listItem->index == -1 && listItem->attached->delayRemove() == false) {
             d->releaseItem(listItem);
             it = d->visibleItems.erase(it);
         } else {
             ++it;
         }
     }
     // Correct the positioning of the items
     d->updateSections();
     d->layout();
 }
effectiveLayoutDirection()
Qt::LayoutDirection QDeclarativeListView::effectiveLayoutDirection () const
Definition at line 2279 of file qdeclarativelistview.cpp.
 {
     Q_D(const QDeclarativeListView);
     if (d->effectiveLayoutMirror)
         return d->layoutDirection == Qt::RightToLeft ? Qt::LeftToRight : Qt::RightToLeft;
     else
         return d->layoutDirection;
 }
event()
bool QDeclarativeListView::event (QEvent * ev) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 2662 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (event->type() == QEvent::User) {
         if (d->layoutScheduled)
             d->layout();
         return true;
     }
     return QDeclarativeFlickable::event(event);
 }
footer()
QDeclarativeComponent* QDeclarativeListView::footer () const
Referenced by QDeclarativeListViewPrivate::positionViewAtIndex(), setFooter(), and setSnapMode().
footerChanged
void QDeclarativeListView::footerChanged () signal
Referenced by setFooter().
geometryChanged()
void QDeclarativeListView::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented from QDeclarativeFlickable.
Definition at line 2938 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->maxExtentDirty = true;
     d->minExtentDirty = true;
     if (d->isRightToLeft() && d->orient == QDeclarativeListView::Horizontal) {
         // maintain position relative to the right edge
         int dx = newGeometry.width() - oldGeometry.width();
         setContentX(contentX() - dx);
     }
     QDeclarativeFlickable::geometryChanged(newGeometry, oldGeometry);
 }
header()
QDeclarativeComponent* QDeclarativeListView::header () const
Referenced by QDeclarativeListViewPrivate::positionViewAtIndex(), setFooter(), and setHeader().
headerChanged
void QDeclarativeListView::headerChanged () signal
Referenced by setHeader().
highlight()
QDeclarativeComponent* QDeclarativeListView::highlight () const
Referenced by QDeclarativeListViewPrivate::positionViewAtIndex(), setCurrentIndex(), and setHighlight().
highlightChanged
void QDeclarativeListView::highlightChanged () signal
Referenced by setHighlight().
highlightFollowsCurrentItem()
bool QDeclarativeListView::highlightFollowsCurrentItem () const
Referenced by setHighlight().
highlightFollowsCurrentItemChanged
void QDeclarativeListView::highlightFollowsCurrentItemChanged () signal
Referenced by setHighlightFollowsCurrentItem().
highlightItem()
QDeclarativeItem* QDeclarativeListView::highlightItem ()
Referenced by setCurrentIndex().
highlightItemChanged
void QDeclarativeListView::highlightItemChanged () signal
highlightMoveDuration()
int QDeclarativeListView::highlightMoveDuration () const
Referenced by setHighlightMoveSpeed().
highlightMoveDurationChanged
void QDeclarativeListView::highlightMoveDurationChanged () signal
Referenced by setHighlightMoveDuration().
highlightMoveSpeed()
qreal QDeclarativeListView::highlightMoveSpeed () const
Referenced by sectionCriteria().
highlightMoveSpeedChanged
void QDeclarativeListView::highlightMoveSpeedChanged () signal
Referenced by setHighlightMoveSpeed().
highlightRangeMode()
HighlightRangeMode QDeclarativeListView::highlightRangeMode () const
Referenced by resetPreferredHighlightEnd().
highlightRangeModeChanged
void QDeclarativeListView::highlightRangeModeChanged () signal
Referenced by setHighlightRangeMode().
highlightResizeDuration()
int QDeclarativeListView::highlightResizeDuration () const
Referenced by setHighlightResizeSpeed().
highlightResizeDurationChanged
void QDeclarativeListView::highlightResizeDurationChanged () signal
Referenced by setHighlightResizeDuration().
highlightResizeSpeed()
qreal QDeclarativeListView::highlightResizeSpeed () const
Referenced by setHighlightMoveDuration().
highlightResizeSpeedChanged
void QDeclarativeListView::highlightResizeSpeedChanged () signal
Referenced by setHighlightResizeSpeed().
incrementCurrentIndex
void QDeclarativeListView::incrementCurrentIndex () slot
Definition at line 2965 of file qdeclarativelistview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDeclarativeListView);
     int count = d->model ? d->model->count() : 0;
     if (count && (currentIndex() < count - 1 || d->wrap)) {
         d->moveReason = QDeclarativeListViewPrivate::SetIndex;
         int index = currentIndex()+1;
         setCurrentIndex((index >= 0 && index < count) ? index : 0);
     }
 }
indexAt()
int QDeclarativeListView::indexAt (qreal x, qreal y) const
Definition at line 3179 of file qdeclarativelistview.cpp.
 {
     Q_D(const QDeclarativeListView);
     for (int i = 0; i < d->visibleItems.count(); ++i) {
         const FxListItem *listItem = d->visibleItems.at(i);
         if(listItem->contains(x, y))
             return listItem->index;
     }
     return -1;
 }
isWrapEnabled()
bool QDeclarativeListView::isWrapEnabled () const
Definition at line 2301 of file qdeclarativelistview.cpp.
 {
     Q_D(const QDeclarativeListView);
     return d->wrap;
 }
itemsChanged
void QDeclarativeListView::itemsChanged (int index, int count) private slot
Definition at line 3687 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     d->updateSections();
     d->layout();
 }
itemsInserted
void QDeclarativeListView::itemsInserted (int index, int count) private slot
Definition at line 3309 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     if (!isComponentComplete())
         return;
     d->updateUnrequestedIndexes();
     d->moveReason = QDeclarativeListViewPrivate::Other;
     qreal tempPos = d->isRightToLeft() ? -d->position()-d->size() : d->position();
     int index = d->visibleItems.count() ? d->mapFromModel(modelIndex) : 0;
     if (index < 0) {
         int i = d->visibleItems.count() - 1;
         while (i > 0 && d->visibleItems.at(i)->index == -1)
             --i;
         if (i == 0 && d->visibleItems.first()->index == -1) {
             // there are no visible items except items marked for removal
             index = d->visibleItems.count();
         } else if (d->visibleItems.at(i)->index + 1 == modelIndex
             && d->visibleItems.at(i)->endPosition() < d->buffer+tempPos+d->size()-1) {
             // Special case of appending an item to the model.
             index = d->visibleItems.count();
         } else {
             if (modelIndex < d->visibleIndex) {
                 // Insert before visible items
                 d->visibleIndex += count;
                 for (int i = 0; i < d->visibleItems.count(); ++i) {
                     FxListItem *listItem = d->visibleItems.at(i);
                     if (listItem->index != -1 && listItem->index >= modelIndex)
                         listItem->index += count;
                 }
             }
             if (d->currentIndex >= modelIndex) {
                 // adjust current item index
                 d->currentIndex += count;
                 if (d->currentItem)
                     d->currentItem->index = d->currentIndex;
                 emit currentIndexChanged();
             }
             d->scheduleLayout();
             d->itemCount += count;
             emit countChanged();
             return;
         }
     }
     // index can be the next item past the end of the visible items list (i.e. appended)
     int pos = 0;
     if (d->visibleItems.count()) {
         pos = index < d->visibleItems.count() ? d->visibleItems.at(index)->position()
                                                 : d->visibleItems.last()->endPosition()+d->spacing+1;
     } else if (d->itemCount == 0 && d->header) {
         pos = d->header->size();
     }
     int initialPos = pos;
     int diff = 0;
     QList<FxListItem*> added;
     bool addedVisible = false;
     FxListItem *firstVisible = d->firstVisibleItem();
     if (firstVisible && pos < firstVisible->position()) {
         // Insert items before the visible item.
         int insertionIdx = index;
         int i = 0;
         int from = tempPos - d->buffer;
         for (i = count-1; i >= 0 && pos > from; --i) {
             if (!addedVisible) {
                 d->scheduleLayout();
                 addedVisible = true;
             }
             FxListItem *item = d->createItem(modelIndex + i);
             if (!item) {
                 // broken or no delegate
                 d->clear();
                 return;
             }
             d->visibleItems.insert(insertionIdx, item);
             pos -= item->size() + d->spacing;
             item->setPosition(pos);
             index++;
         }
         if (i >= 0) {
             // If we didn't insert all our new items - anything
             // before the current index is not visible - remove it.
             while (insertionIdx--) {
                 FxListItem *item = d->visibleItems.takeFirst();
                 if (item->index != -1)
                     d->visibleIndex++;
                 d->releaseItem(item);
             }
         } else {
             // adjust pos of items before inserted items.
             for (int i = insertionIdx-1; i >= 0; i--) {
                 FxListItem *listItem = d->visibleItems.at(i);
                 listItem->setPosition(listItem->position() - (initialPos - pos));
             }
         }
     } else {
         int i = 0;
         int to = d->buffer+tempPos+d->size()-1;
         for (i = 0; i < count && pos <= to; ++i) {
             if (!addedVisible) {
                 d->scheduleLayout();
                 addedVisible = true;
             }
             FxListItem *item = d->createItem(modelIndex + i);
             if (!item) {
                 // broken or no delegate
                 d->clear();
                 return;
             }
             d->visibleItems.insert(index, item);
             item->setPosition(pos);
             added.append(item);
             pos += item->size() + d->spacing;
             ++index;
         }
         if (i != count) {
             // We didn't insert all our new items, which means anything
             // beyond the current index is not visible - remove it.
             while (d->visibleItems.count() > index)
                 d->releaseItem(d->visibleItems.takeLast());
         }
         diff = pos - initialPos;
     }
     if (d->itemCount && d->currentIndex >= modelIndex) {
         // adjust current item index
         d->currentIndex += count;
         if (d->currentItem) {
             d->currentItem->index = d->currentIndex;
             d->currentItem->setPosition(d->currentItem->position() + diff);
         }
         emit currentIndexChanged();
     } else if (!d->itemCount && (!d->currentIndex || (d->currentIndex < 0 && !d->currentIndexCleared))) {
         d->updateCurrent(0);
     }
     // Update the indexes of the following visible items.
     for (; index < d->visibleItems.count(); ++index) {
         FxListItem *listItem = d->visibleItems.at(index);
         if (d->currentItem && listItem->item != d->currentItem->item)
             listItem->setPosition(listItem->position() + diff);
         if (listItem->index != -1)
             listItem->index += count;
     }
     // everything is in order now - emit add() signal
     for (int j = 0; j < added.count(); ++j)
         added.at(j)->attached->emitAdd();
     d->updateSections();
     d->itemCount += count;
     emit countChanged();
 }
itemsMoved
void QDeclarativeListView::itemsMoved (int from, int to, int count) private slot
Definition at line 3577 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     if (!isComponentComplete())
         return;
     d->updateUnrequestedIndexes();
     if (d->visibleItems.isEmpty()) {
         refill();
         return;
     }
     d->moveReason = QDeclarativeListViewPrivate::Other;
     FxListItem *firstVisible = d->firstVisibleItem();
     qreal firstItemPos = firstVisible->position();
     QHash<int,FxListItem*> moved;
     int moveBy = 0;
     QList<FxListItem*>::Iterator it = d->visibleItems.begin();
     while (it != d->visibleItems.end()) {
         FxListItem *item = *it;
         if (item->index >= from && item->index < from + count) {
             // take the items that are moving
             item->index += (to-from);
             moved.insert(item->index, item);
             if (item->position() < firstItemPos)
                 moveBy += item->size();
             it = d->visibleItems.erase(it);
         } else {
             // move everything after the moved items.
             if (item->index > from && item->index != -1)
                 item->index -= count;
             ++it;
         }
     }
     int remaining = count;
     int endIndex = d->visibleIndex;
     it = d->visibleItems.begin();
     while (it != d->visibleItems.end()) {
         FxListItem *item = *it;
         if (remaining && item->index >= to && item->index < to + count) {
             // place items in the target position, reusing any existing items
             FxListItem *movedItem = moved.take(item->index);
             if (!movedItem)
                 movedItem = d->createItem(item->index);
             if (!movedItem) {
                 // broken or no delegate
                 d->clear();
                 return;
             }
             if (item->index <= firstVisible->index)
                 moveBy -= movedItem->size();
             it = d->visibleItems.insert(it, movedItem);
             ++it;
             --remaining;
         } else {
             if (item->index != -1) {
                 if (item->index >= to) {
                     // update everything after the moved items.
                     item->index += count;
                 }
                 endIndex = item->index;
             }
             ++it;
         }
     }
     // If we have moved items to the end of the visible items
     // then add any existing moved items that we have
     while (FxListItem *item = moved.take(endIndex+1)) {
         d->visibleItems.append(item);
         ++endIndex;
     }
     // update visibleIndex
     for (it = d->visibleItems.begin(); it != d->visibleItems.end(); ++it) {
         if ((*it)->index != -1) {
             d->visibleIndex = (*it)->index;
             break;
         }
     }
     // Fix current index
     if (d->currentIndex >= 0 && d->currentItem) {
         int oldCurrent = d->currentIndex;
         d->currentIndex = d->model->indexOf(d->currentItem->item, this);
         if (oldCurrent != d->currentIndex) {
             d->currentItem->index = d->currentIndex;
             emit currentIndexChanged();
         }
     }
     // Whatever moved items remain are no longer visible items.
     while (moved.count()) {
         int idx = moved.begin().key();
         FxListItem *item = moved.take(idx);
         if (d->currentItem && item->item == d->currentItem->item)
             item->setPosition(d->positionAt(idx));
         d->releaseItem(item);
     }
     // Ensure we don't cause an ugly list scroll.
     if (!d->visibleItems.isEmpty())
         d->visibleItems.first()->setPosition(d->visibleItems.first()->position() + moveBy);
     d->updateSections();
     d->layout();
 }
itemsRemoved
void QDeclarativeListView::itemsRemoved (int index, int count) private slot
Definition at line 3462 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     if (!isComponentComplete())
         return;
     d->moveReason = QDeclarativeListViewPrivate::Other;
     d->updateUnrequestedIndexes();
     d->itemCount -= count;
     FxListItem *firstVisible = d->firstVisibleItem();
     int preRemovedSize = 0;
     bool removedVisible = false;
     // Remove the items from the visible list, skipping anything already marked for removal
     QList<FxListItem*>::Iterator it = d->visibleItems.begin();
     while (it != d->visibleItems.end()) {
         FxListItem *item = *it;
         if (item->index == -1 || item->index < modelIndex) {
             // already removed, or before removed items
             ++it;
         } else if (item->index >= modelIndex + count) {
             // after removed items
             item->index -= count;
             ++it;
         } else {
             // removed item
             if (!removedVisible) {
                 d->scheduleLayout();
                 removedVisible = true;
             }
             item->attached->emitRemove();
             if (item->attached->delayRemove()) {
                 item->index = -1;
                 connect(item->attached, SIGNAL(delayRemoveChanged()), this, SLOT(destroyRemoved()), Qt::QueuedConnection);
                 ++it;
             } else {
                 if (item == firstVisible)
                     firstVisible = 0;
                 if (firstVisible && item->position() < firstVisible->position())
                     preRemovedSize += item->size();
                 it = d->visibleItems.erase(it);
                 d->releaseItem(item);
             }
         }
     }
     if (firstVisible && d->visibleItems.first() != firstVisible)
         d->visibleItems.first()->setPosition(d->visibleItems.first()->position() + preRemovedSize);
     // fix current
     if (d->currentIndex >= modelIndex + count) {
         d->currentIndex -= count;
         if (d->currentItem)
             d->currentItem->index -= count;
         emit currentIndexChanged();
     } else if (d->currentIndex >= modelIndex && d->currentIndex < modelIndex + count) {
         // current item has been removed.
         d->currentItem->attached->setIsCurrentItem(false);
         d->releaseItem(d->currentItem);
         d->currentItem = 0;
         d->currentIndex = -1;
         if (d->itemCount)
             d->updateCurrent(qMin(modelIndex, d->itemCount-1));
         else
             emit currentIndexChanged();
     }
     // update visibleIndex
     bool haveVisibleIndex = false;
     for (it = d->visibleItems.begin(); it != d->visibleItems.end(); ++it) {
         if ((*it)->index != -1) {
             d->visibleIndex = (*it)->index;
             haveVisibleIndex = true;
             break;
         }
     }
     if (!haveVisibleIndex) {
         d->timeline.clear();
         if (removedVisible && d->itemCount == 0) {
             d->visibleIndex = 0;
             d->visiblePos = d->header ? d->header->size() : 0;
             d->setPosition(0);
             d->updateHeader();
             d->updateFooter();
             update();
         } else {
             if (modelIndex < d->visibleIndex)
                 d->visibleIndex = modelIndex+1;
             d->visibleIndex = qMax(qMin(d->visibleIndex, d->itemCount-1), 0);
         }
     }
     d->updateSections();
     emit countChanged();
 }
keyNavigationWrapsChanged
void QDeclarativeListView::keyNavigationWrapsChanged () signal
Referenced by setWrapEnabled().
keyPressEvent()
void QDeclarativeListView::keyPressEvent (QKeyEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 2902 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     keyPressPreHandler(event);
     if (event->isAccepted())
         return;
     if (d->model && d->model->count() && d->interactive) {
         if ((d->orient == QDeclarativeListView::Horizontal && !d->isRightToLeft() && event->key() == Qt::Key_Left)
                     || (d->orient == QDeclarativeListView::Horizontal && d->isRightToLeft() && event->key() == Qt::Key_Right)
                     || (d->orient == QDeclarativeListView::Vertical && event->key() == Qt::Key_Up)) {
             if (currentIndex() > 0 || (d->wrap && !event->isAutoRepeat())) {
                 decrementCurrentIndex();
                 event->accept();
                 return;
             } else if (d->wrap) {
                 event->accept();
                 return;
             }
         } else if ((d->orient == QDeclarativeListView::Horizontal && !d->isRightToLeft() && event->key() == Qt::Key_Right)
                     || (d->orient == QDeclarativeListView::Horizontal && d->isRightToLeft() && event->key() == Qt::Key_Left)
                     || (d->orient == QDeclarativeListView::Vertical && event->key() == Qt::Key_Down)) {
             if (currentIndex() < d->model->count() - 1 || (d->wrap && !event->isAutoRepeat())) {
                 incrementCurrentIndex();
                 event->accept();
                 return;
             } else if (d->wrap) {
                 event->accept();
                 return;
             }
         }
     }
     event->ignore();
     QDeclarativeFlickable::keyPressEvent(event);
 }
layoutDirection()
Qt::LayoutDirection QDeclarativeListView::layoutDirection () const
Referenced by setLayoutDirection(), and setOrientation().
layoutDirectionChanged
void QDeclarativeListView::layoutDirectionChanged () signal
Referenced by setLayoutDirection().
maxXExtent()
qreal QDeclarativeListView::maxXExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2853 of file qdeclarativelistview.cpp.
Referenced by minXExtent(), and viewportMoved().
 {
     Q_D(const QDeclarativeListView);
     if (d->orient == QDeclarativeListView::Vertical)
         return width();
     if (d->maxExtentDirty) {
         qreal highlightStart;
         qreal highlightEnd;
         qreal lastItemPosition = 0;
         d->maxExtent = 0;
         if (d->isRightToLeft()) {
             highlightStart = d->highlightRangeStartValid ? d->highlightRangeEnd : d->size();
             highlightEnd = d->highlightRangeEndValid ? d->highlightRangeStart : d->size();
             lastItemPosition = d->endPosition();
         } else {
             highlightStart = d->highlightRangeStart;
             highlightEnd = d->highlightRangeEnd;
             if (d->model && d->model->count())
                 lastItemPosition = d->positionAt(d->model->count()-1);
         }
         if (!d->model || !d->model->count()) {
             if (!d->isRightToLeft())
                 d->maxExtent = d->header ? -d->header->size() : 0;
             d->maxExtent += width();
         } else if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
             d->maxExtent = -(lastItemPosition - highlightStart);
             if (highlightEnd != highlightStart) {
                 d->maxExtent = d->isRightToLeft()
                         ? qMax(d->maxExtent, -(d->endPosition() - highlightEnd + 1))
                         : qMin(d->maxExtent, -(d->endPosition() - highlightEnd + 1));
             }
         } else {
             d->maxExtent = -(d->endPosition() - width() + 1);
         }
         if (d->isRightToLeft()) {
             if (d->header && d->visibleItems.count())
                 d->maxExtent -= d->header->size();
         } else {
             if (d->footer)
                 d->maxExtent -= d->footer->size();
             qreal minX = minXExtent();
             if (d->maxExtent > minX)
                 d->maxExtent = minX;
         }
         d->maxExtentDirty = false;
     }
     return d->maxExtent;
 }
maxYExtent()
qreal QDeclarativeListView::maxYExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2785 of file qdeclarativelistview.cpp.
Referenced by viewportMoved().
 {
     Q_D(const QDeclarativeListView);
     if (d->orient == QDeclarativeListView::Horizontal)
         return height();
     if (d->maxExtentDirty) {
         if (!d->model || !d->model->count()) {
             d->maxExtent = d->header ? -d->header->size() : 0;
             d->maxExtent += height();
         } else if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
             d->maxExtent = -(d->positionAt(d->model->count()-1) - d->highlightRangeStart);
             if (d->highlightRangeEnd != d->highlightRangeStart)
                 d->maxExtent = qMin(d->maxExtent, -(d->endPosition() - d->highlightRangeEnd + 1));
         } else {
             d->maxExtent = -(d->endPosition() - height() + 1);
         }
         if (d->footer)
             d->maxExtent -= d->footer->size();
         qreal minY = minYExtent();
         if (d->maxExtent > minY)
             d->maxExtent = minY;
         d->maxExtentDirty = false;
     }
     return d->maxExtent;
 }
minXExtent()
qreal QDeclarativeListView::minXExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2811 of file qdeclarativelistview.cpp.
Referenced by maxXExtent(), and viewportMoved().
 {
     Q_D(const QDeclarativeListView);
     if (d->orient == QDeclarativeListView::Vertical)
         return QDeclarativeFlickable::minXExtent();
     if (d->minExtentDirty) {
         d->minExtent = -d->startPosition();
         qreal highlightStart;
         qreal highlightEnd;
         qreal endPositionFirstItem = 0;
         if (d->isRightToLeft()) {
             if (d->model && d->model->count())
                 endPositionFirstItem = d->positionAt(d->model->count()-1);
             else if (d->header)
                 d->minExtent += d->header->size();
             highlightStart = d->highlightRangeStartValid
                     ? d->highlightRangeStart - (d->lastPosition()-endPositionFirstItem)
                     : d->size() - (d->lastPosition()-endPositionFirstItem);
             highlightEnd = d->highlightRangeEndValid ? d->highlightRangeEnd : d->size();
             if (d->footer)
                 d->minExtent += d->footer->size();
             qreal maxX = maxXExtent();
             if (d->minExtent < maxX)
                 d->minExtent = maxX;
         } else {
             endPositionFirstItem = d->endPositionAt(0);
             highlightStart = d->highlightRangeStart;
             highlightEnd = d->highlightRangeEnd;
             if (d->header && d->visibleItems.count())
                 d->minExtent += d->header->size();
         }
         if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
             d->minExtent += d->isRightToLeft() ? -highlightStart : highlightStart;
             d->minExtent = qMax(d->minExtent, -(endPositionFirstItem - highlightEnd + 1));
         }
         d->minExtentDirty = false;
     }
     return d->minExtent;
 }
minYExtent()
qreal QDeclarativeListView::minYExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2762 of file qdeclarativelistview.cpp.
Referenced by maxYExtent(), and viewportMoved().
 {
     Q_D(const QDeclarativeListView);
     if (d->orient == QDeclarativeListView::Horizontal)
         return QDeclarativeFlickable::minYExtent();
     if (d->minExtentDirty) {
         d->minExtent = -d->startPosition();
         if (d->header && d->visibleItems.count())
             d->minExtent += d->header->size();
         if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
             d->minExtent += d->highlightRangeStart;
             if (d->sectionCriteria) {
                 if (d->visibleItem(0))
                     d->minExtent -= d->visibleItem(0)->sectionSize();
             }
             d->minExtent = qMax(d->minExtent, -(d->endPositionAt(0) - d->highlightRangeEnd + 1));
         }
         d->minExtentDirty = false;
     }
     return d->minExtent;
 }
model()
QVariant QDeclarativeListView::model () const
Referenced by QDeclarativeListViewPrivate::positionViewAtIndex(), setModel(), and ~QDeclarativeListView().
modelChanged
void QDeclarativeListView::modelChanged () signal
Referenced by setModel().
modelReset
void QDeclarativeListView::modelReset () private slot
Definition at line 3694 of file qdeclarativelistview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeListView);
     d->moveReason = QDeclarativeListViewPrivate::SetIndex;
     d->regenerate();
     if (d->highlight && d->currentItem) {
         if (d->autoHighlight)
             d->highlight->setPosition(d->currentItem->position());
         d->updateTrackedItem();
     }
     d->moveReason = QDeclarativeListViewPrivate::Other;
     emit countChanged();
 }
orientation()
Orientation QDeclarativeListView::orientation () const
Referenced by setOrientation(), and setSpacing().
orientationChanged
void QDeclarativeListView::orientationChanged () signal
Referenced by setOrientation().
positionViewAtBeginning()
void QDeclarativeListView::positionViewAtBeginning ()
Definition at line 3148 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (!d->isValid())
         return;
     d->positionViewAtIndex(-1, Beginning);
 }
positionViewAtEnd()
void QDeclarativeListView::positionViewAtEnd ()
Definition at line 3156 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (!d->isValid())
         return;
     d->positionViewAtIndex(d->model->count(), End);
 }
positionViewAtIndex()
void QDeclarativeListView::positionViewAtIndex (int index, int mode)
Definition at line 3117 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (!d->isValid() || index < 0 || index >= d->model->count())
         return;
     d->positionViewAtIndex(index, mode);
 }
preferredHighlightBegin()
qreal QDeclarativeListView::preferredHighlightBegin () const
Referenced by setHighlightFollowsCurrentItem().
preferredHighlightBeginChanged
void QDeclarativeListView::preferredHighlightBeginChanged () signal
Referenced by resetPreferredHighlightBegin(), and setPreferredHighlightBegin().
preferredHighlightEnd()
qreal QDeclarativeListView::preferredHighlightEnd () const
Referenced by resetPreferredHighlightBegin().
preferredHighlightEndChanged
void QDeclarativeListView::preferredHighlightEndChanged () signal
Referenced by resetPreferredHighlightEnd(), and setPreferredHighlightEnd().
qmlAttachedProperties()
QDeclarativeListViewAttached * QDeclarativeListView::qmlAttachedProperties (QObject * obj) static
Definition at line 3739 of file qdeclarativelistview.cpp.
 {
     return new QDeclarativeListViewAttached(obj);
 }
refill
void QDeclarativeListView::refill () private slot
Definition at line 3229 of file qdeclarativelistview.cpp.
Referenced by componentComplete(), itemsMoved(), setCacheBuffer(), setDelegate(), setModel(), and viewportMoved().
 {
     Q_D(QDeclarativeListView);
     if (d->isRightToLeft())
         d->refill(-d->position()-d->size()+1, -d->position());
     else
         d->refill(d->position(), d->position()+d->size()-1);
 }
resetPreferredHighlightBegin()
void QDeclarativeListView::resetPreferredHighlightBegin ()
Definition at line 2113 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->highlightRangeStartValid = false;
     if (d->highlightRangeStart == 0)
         return;
     d->highlightRangeStart = 0;
     emit preferredHighlightBeginChanged();
 }
resetPreferredHighlightEnd()
void QDeclarativeListView::resetPreferredHighlightEnd ()
Definition at line 2140 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->highlightRangeEndValid = false;
     if (d->highlightRangeEnd == 0)
         return;
     d->highlightRangeEnd = 0;
     emit preferredHighlightEndChanged();
 }
sectionCriteria()
QDeclarativeViewSection * QDeclarativeListView::sectionCriteria ()
Definition at line 2411 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (!d->sectionCriteria) {
         d->sectionCriteria = new QDeclarativeViewSection(this);
         connect(d->sectionCriteria, SIGNAL(propertyChanged()), this, SLOT(updateSections()));
     }
     return d->sectionCriteria;
 }
setCacheBuffer()
void QDeclarativeListView::setCacheBuffer (int b)
Definition at line 2344 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->buffer != b) {
         d->buffer = b;
         if (isComponentComplete()) {
             d->bufferMode = QDeclarativeListViewPrivate::BufferBefore | QDeclarativeListViewPrivate::BufferAfter;
             refill();
         }
         emit cacheBufferChanged();
     }
 }
setContentX()
void QDeclarativeListView::setContentX (qreal pos) virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2646 of file qdeclarativelistview.cpp.
Referenced by geometryChanged(), and setOrientation().
 {
     Q_D(QDeclarativeListView);
     // Positioning the view manually should override any current movement state
     d->moveReason = QDeclarativeListViewPrivate::Other;
     QDeclarativeFlickable::setContentX(pos);
 }
setContentY()
void QDeclarativeListView::setContentY (qreal pos) virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2654 of file qdeclarativelistview.cpp.
Referenced by setOrientation().
 {
     Q_D(QDeclarativeListView);
     // Positioning the view manually should override any current movement state
     d->moveReason = QDeclarativeListViewPrivate::Other;
     QDeclarativeFlickable::setContentY(pos);
 }
setCurrentIndex()
void QDeclarativeListView::setCurrentIndex (int idx)
Definition at line 1922 of file qdeclarativelistview.cpp.
Referenced by decrementCurrentIndex(), incrementCurrentIndex(), and setModel().
 {
     Q_D(QDeclarativeListView);
     if (d->requestedIndex >= 0)  // currently creating item
         return;
     d->currentIndexCleared = (index == -1);
     if (index == d->currentIndex)
         return;
     if (isComponentComplete() && d->isValid()) {
         if (d->layoutScheduled)
             d->layout();
         d->moveReason = QDeclarativeListViewPrivate::SetIndex;
         d->updateCurrent(index);
     } else if (d->currentIndex != index) {
         d->currentIndex = index;
         emit currentIndexChanged();
     }
 }
setDelegate()
void QDeclarativeListView::setDelegate (QDeclarativeComponent * delegate)
Definition at line 1863 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (delegate == this->delegate())
         return;
     if (!d->ownModel) {
         d->model = new QDeclarativeVisualDataModel(qmlContext(this));
         d->ownModel = true;
     }
     if (QDeclarativeVisualDataModel *dataModel = qobject_cast<QDeclarativeVisualDataModel*>(d->model)) {
         int oldCount = dataModel->count();
         dataModel->setDelegate(delegate);
         if (isComponentComplete()) {
             for (int i = 0; i < d->visibleItems.count(); ++i)
                 d->releaseItem(d->visibleItems.at(i));
             d->visibleItems.clear();
             d->releaseItem(d->currentItem);
             d->currentItem = 0;
             updateSections();
             refill();
             d->moveReason = QDeclarativeListViewPrivate::SetIndex;
             d->updateCurrent(d->currentIndex);
             if (d->highlight && d->currentItem) {
                 if (d->autoHighlight)
                     d->highlight->setPosition(d->currentItem->position());
                 d->updateTrackedItem();
             }
             d->updateViewport();
         }
         if (oldCount != dataModel->count())
             emit countChanged();
     }
     emit delegateChanged();
 }
setFooter()
void QDeclarativeListView::setFooter (QDeclarativeComponent * footer)
Definition at line 2581 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->footerComponent != footer) {
         if (d->footer) {
             if (scene())
                 scene()->removeItem(d->footer->item);
             d->footer->item->deleteLater();
             delete d->footer;
             d->footer = 0;
         }
         d->footerComponent = footer;
         d->minExtentDirty = true;
         d->maxExtentDirty = true;
         if (isComponentComplete()) {
             d->updateFooter();
             d->updateViewport();
             d->fixupPosition();
         }
         emit footerChanged();
     }
 }
setHeader()
void QDeclarativeListView::setHeader (QDeclarativeComponent * header)
Definition at line 2622 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->headerComponent != header) {
         if (d->header) {
             if (scene())
                 scene()->removeItem(d->header->item);
             d->header->item->deleteLater();
             delete d->header;
             d->header = 0;
         }
         d->headerComponent = header;
         d->minExtentDirty = true;
         d->maxExtentDirty = true;
         if (isComponentComplete()) {
             d->updateHeader();
             d->updateFooter();
             d->updateViewport();
             d->fixupPosition();
         }
         emit headerChanged();
     }
 }
setHighlight()
void QDeclarativeListView::setHighlight (QDeclarativeComponent * highlight)
Definition at line 2005 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (highlight != d->highlightComponent) {
         d->highlightComponent = highlight;
         d->createHighlight();
         if (d->currentItem)
             d->updateHighlight();
         emit highlightChanged();
     }
 }
setHighlightFollowsCurrentItem()
void QDeclarativeListView::setHighlightFollowsCurrentItem (bool autoHighlight)
Definition at line 2045 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->autoHighlight != autoHighlight) {
         d->autoHighlight = autoHighlight;
         if (autoHighlight) {
             d->updateHighlight();
         } else {
             if (d->highlightPosAnimator)
                 d->highlightPosAnimator->stop();
             if (d->highlightSizeAnimator)
                 d->highlightSizeAnimator->stop();
         }
         emit highlightFollowsCurrentItemChanged();
     }
 }
setHighlightMoveDuration()
void QDeclarativeListView::setHighlightMoveDuration (int duration)
Definition at line 2479 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);\
     if (d->highlightMoveDuration != duration) {
         d->highlightMoveDuration = duration;
         if (d->highlightPosAnimator)
             d->highlightPosAnimator->userDuration = d->highlightMoveDuration;
         emit highlightMoveDurationChanged();
     }
 }
setHighlightMoveSpeed()
void QDeclarativeListView::setHighlightMoveSpeed (qreal speed)
Definition at line 2462 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);\
     if (d->highlightMoveSpeed != speed) {
         d->highlightMoveSpeed = speed;
         if (d->highlightPosAnimator)
             d->highlightPosAnimator->velocity = d->highlightMoveSpeed;
         emit highlightMoveSpeedChanged();
     }
 }
setHighlightRangeMode()
void QDeclarativeListView::setHighlightRangeMode (HighlightRangeMode mode)
Definition at line 2156 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->highlightRange == mode)
         return;
     d->highlightRange = mode;
     d->haveHighlightRange = d->highlightRange != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit highlightRangeModeChanged();
 }
setHighlightResizeDuration()
void QDeclarativeListView::setHighlightResizeDuration (int duration)
Definition at line 2513 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);\
     if (d->highlightResizeDuration != duration) {
         d->highlightResizeDuration = duration;
         if (d->highlightSizeAnimator)
             d->highlightSizeAnimator->userDuration = d->highlightResizeDuration;
         emit highlightResizeDurationChanged();
     }
 }
setHighlightResizeSpeed()
void QDeclarativeListView::setHighlightResizeSpeed (qreal speed)
Definition at line 2496 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);\
     if (d->highlightResizeSpeed != speed) {
         d->highlightResizeSpeed = speed;
         if (d->highlightSizeAnimator)
             d->highlightSizeAnimator->velocity = d->highlightResizeSpeed;
         emit highlightResizeSpeedChanged();
     }
 }
setLayoutDirection()
void QDeclarativeListView::setLayoutDirection (Qt::LayoutDirection layoutDirection)
Definition at line 2269 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->layoutDirection != layoutDirection) {
         d->layoutDirection = layoutDirection;
         d->regenerate();
         emit layoutDirectionChanged();
     }
 }
setModel()
void QDeclarativeListView::setModel (const QVariant & model)
Definition at line 1761 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->modelVariant == model)
         return;
     if (d->model) {
         disconnect(d->model, SIGNAL(itemsInserted(int,int)), this, SLOT(itemsInserted(int,int)));
         disconnect(d->model, SIGNAL(itemsRemoved(int,int)), this, SLOT(itemsRemoved(int,int)));
         disconnect(d->model, SIGNAL(itemsMoved(int,int,int)), this, SLOT(itemsMoved(int,int,int)));
         disconnect(d->model, SIGNAL(itemsChanged(int,int)), this, SLOT(itemsChanged(int,int)));
         disconnect(d->model, SIGNAL(modelReset()), this, SLOT(modelReset()));
         disconnect(d->model, SIGNAL(createdItem(int,QDeclarativeItem*)), this, SLOT(createdItem(int,QDeclarativeItem*)));
         disconnect(d->model, SIGNAL(destroyingItem(QDeclarativeItem*)), this, SLOT(destroyingItem(QDeclarativeItem*)));
     }
     d->clear();
     QDeclarativeVisualModel *oldModel = d->model;
     d->model = 0;
     d->setPosition(0);
     d->modelVariant = model;
     QObject *object = qvariant_cast<QObject*>(model);
     QDeclarativeVisualModel *vim = 0;
     if (object && (vim = qobject_cast<QDeclarativeVisualModel *>(object))) {
         if (d->ownModel) {
             delete oldModel;
             d->ownModel = false;
         }
         d->model = vim;
     } else {
         if (!d->ownModel) {
             d->model = new QDeclarativeVisualDataModel(qmlContext(this), this);
             d->ownModel = true;
         } else {
             d->model = oldModel;
         }
         if (QDeclarativeVisualDataModel *dataModel = qobject_cast<QDeclarativeVisualDataModel*>(d->model))
             dataModel->setModel(model);
     }
     if (d->model) {
         d->bufferMode = QDeclarativeListViewPrivate::BufferBefore | QDeclarativeListViewPrivate::BufferAfter;
         if (isComponentComplete()) {
             updateSections();
             refill();
             if ((d->currentIndex >= d->model->count() || d->currentIndex < 0) && !d->currentIndexCleared) {
                 setCurrentIndex(0);
             } else {
                 d->moveReason = QDeclarativeListViewPrivate::SetIndex;
                 d->updateCurrent(d->currentIndex);
                 if (d->highlight && d->currentItem) {
                     if (d->autoHighlight)
                         d->highlight->setPosition(d->currentItem->position());
                     d->updateTrackedItem();
                 }
             }
             d->updateViewport();
         }
         connect(d->model, SIGNAL(itemsInserted(int,int)), this, SLOT(itemsInserted(int,int)));
         connect(d->model, SIGNAL(itemsRemoved(int,int)), this, SLOT(itemsRemoved(int,int)));
         connect(d->model, SIGNAL(itemsMoved(int,int,int)), this, SLOT(itemsMoved(int,int,int)));
         connect(d->model, SIGNAL(itemsChanged(int,int)), this, SLOT(itemsChanged(int,int)));
         connect(d->model, SIGNAL(modelReset()), this, SLOT(modelReset()));
         connect(d->model, SIGNAL(createdItem(int,QDeclarativeItem*)), this, SLOT(createdItem(int,QDeclarativeItem*)));
         connect(d->model, SIGNAL(destroyingItem(QDeclarativeItem*)), this, SLOT(destroyingItem(QDeclarativeItem*)));
         emit countChanged();
     }
     emit modelChanged();
 }
setOrientation()
void QDeclarativeListView::setOrientation (QDeclarativeListView::Orientation orientation)
Definition at line 2222 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->orient != orientation) {
         d->orient = orientation;
         if (d->orient == QDeclarativeListView::Vertical) {
             setContentWidth(-1);
             setFlickableDirection(VerticalFlick);
             setContentX(0);
         } else {
             setContentHeight(-1);
             setFlickableDirection(HorizontalFlick);
             setContentY(0);
         }
         d->regenerate();
         emit orientationChanged();
     }
 }
setPreferredHighlightBegin()
void QDeclarativeListView::setPreferredHighlightBegin (qreal start)
Definition at line 2102 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->highlightRangeStartValid = true;
     if (d->highlightRangeStart == start)
         return;
     d->highlightRangeStart = start;
     d->haveHighlightRange = d->highlightRange != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit preferredHighlightBeginChanged();
 }
setPreferredHighlightEnd()
void QDeclarativeListView::setPreferredHighlightEnd (qreal end)
Definition at line 2129 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     d->highlightRangeEndValid = true;
     if (d->highlightRangeEnd == end)
         return;
     d->highlightRangeEnd = end;
     d->haveHighlightRange = d->highlightRange != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit preferredHighlightEndChanged();
 }
setSnapMode()
void QDeclarativeListView::setSnapMode (SnapMode mode)
Definition at line 2554 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->snapMode != mode) {
         d->snapMode = mode;
         emit snapModeChanged();
     }
 }
setSpacing()
void QDeclarativeListView::setSpacing (qreal spacing)
Definition at line 2182 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (spacing != d->spacing) {
         d->spacing = spacing;
         d->layout();
         emit spacingChanged();
     }
 }
setWrapEnabled()
void QDeclarativeListView::setWrapEnabled (bool wrap)
Definition at line 2307 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (d->wrap == wrap)
         return;
     d->wrap = wrap;
     emit keyNavigationWrapsChanged();
 }
snapMode()
SnapMode QDeclarativeListView::snapMode () const
Referenced by setHighlightResizeDuration().
snapModeChanged
void QDeclarativeListView::snapModeChanged () signal
Referenced by setSnapMode().
spacing()
qreal QDeclarativeListView::spacing () const
Referenced by setHighlightRangeMode(), and setSpacing().
spacingChanged
void QDeclarativeListView::spacingChanged () signal
Referenced by setSpacing().
trackedPositionChanged
void QDeclarativeListView::trackedPositionChanged () private slot
Definition at line 3238 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     if (!d->trackedItem || !d->currentItem)
         return;
     if (d->moveReason == QDeclarativeListViewPrivate::SetIndex) {
         qreal trackedPos = qCeil(d->trackedItem->position());
         qreal trackedSize = d->trackedItem->size();
         if (d->trackedItem != d->currentItem) {
             trackedPos -= d->currentItem->sectionSize();
             trackedSize += d->currentItem->sectionSize();
         }
         qreal viewPos;
         qreal highlightStart;
         qreal highlightEnd;
         if (d->isRightToLeft()) {
             viewPos = -d->position()-d->size();
             highlightStart = d->highlightRangeStartValid ? d->size()-d->highlightRangeEnd : d->highlightRangeStart;
             highlightEnd = d->highlightRangeEndValid ? d->size()-d->highlightRangeStart : d->highlightRangeEnd;
         } else {
             viewPos = d->position();
             highlightStart = d->highlightRangeStart;
             highlightEnd = d->highlightRangeEnd;
         }
         qreal pos = viewPos;
         if (d->haveHighlightRange) {
             if (d->highlightRange == StrictlyEnforceRange) {
                 if (trackedPos > pos + highlightEnd - d->trackedItem->size())
                     pos = trackedPos - highlightEnd + d->trackedItem->size();
                 if (trackedPos < pos + highlightStart)
                     pos = trackedPos - highlightStart;
             } else {
                 if (trackedPos < d->startPosition() + highlightStart) {
                     pos = d->startPosition();
                 } else if (d->trackedItem->endPosition() > d->endPosition() - d->size() + highlightEnd) {
                     pos = d->endPosition() - d->size() + 1;
                     if (pos < d->startPosition())
                         pos = d->startPosition();
                 } else {
                     if (trackedPos < viewPos + highlightStart) {
                         pos = trackedPos - highlightStart;
                     } else if (trackedPos > viewPos + highlightEnd - trackedSize) {
                         pos = trackedPos - highlightEnd + trackedSize;
                     }
                 }
             }
         } else {
             if (trackedPos < viewPos && d->currentItem->position() < viewPos) {
                 pos = d->currentItem->position() < trackedPos ? trackedPos : d->currentItem->position();
             } else if (d->trackedItem->endPosition() >= viewPos + d->size()
                         && d->currentItem->endPosition() >= viewPos + d->size()) {
                 if (d->trackedItem->endPosition() <= d->currentItem->endPosition()) {
                     pos = d->trackedItem->endPosition() - d->size() + 1;
                      if (trackedSize > d->size())
                         pos = trackedPos;
                 } else {
                     pos = d->currentItem->endPosition() - d->size() + 1;
                     if (d->currentItem->size() > d->size())
                         pos = d->currentItem->position();
                 }
             }
         }
         if (viewPos != pos) {
             cancelFlick();
             d->calcVelocity = true;
             d->setPosition(pos);
             d->calcVelocity = false;
         }
     }
 }
updateSections
void QDeclarativeListView::updateSections () private slot
Definition at line 3215 of file qdeclarativelistview.cpp.
Referenced by componentComplete(), sectionCriteria(), setDelegate(), and setModel().
 {
     Q_D(QDeclarativeListView);
     if (isComponentComplete() && d->model) {
         QList<QByteArray> roles;
         if (d->sectionCriteria && !d->sectionCriteria->property().isEmpty())
             roles << d->sectionCriteria->property().toUtf8();
         d->model->setWatchedRoles(roles);
         d->updateSections();
         if (d->itemCount)
             d->layout();
     }
 }
viewportMoved()
void QDeclarativeListView::viewportMoved () protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2674 of file qdeclarativelistview.cpp.
 {
     Q_D(QDeclarativeListView);
     QDeclarativeFlickable::viewportMoved();
     if (!d->itemCount)
         return;
     // Recursion can occur due to refill changing the content size.
     if (d->inViewportMoved)
         return;
     d->inViewportMoved = true;
     d->lazyRelease = true;
     refill();
     if (d->hData.flicking || d->vData.flicking || d->hData.moving || d->vData.moving)
         d->moveReason = QDeclarativeListViewPrivate::Mouse;
     if (d->moveReason != QDeclarativeListViewPrivate::SetIndex) {
         if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange && d->highlight) {
             // reposition highlight
             qreal pos = d->highlight->position();
             qreal viewPos;
             qreal highlightStart;
             qreal highlightEnd;
             if (d->isRightToLeft()) {
                 // Handle Right-To-Left exceptions
                 viewPos = -d->position()-d->size();
                 highlightStart = d->highlightRangeStartValid ? d->size()-d->highlightRangeEnd : d->highlightRangeStart;
                 highlightEnd = d->highlightRangeEndValid ? d->size()-d->highlightRangeStart : d->highlightRangeEnd;
             } else {
                 viewPos = d->position();
                 highlightStart = d->highlightRangeStart;
                 highlightEnd = d->highlightRangeEnd;
             }
             if (pos > viewPos + highlightEnd - d->highlight->size())
                 pos = viewPos + highlightEnd - d->highlight->size();
             if (pos < viewPos + highlightStart)
                 pos = viewPos + highlightStart;
             d->highlightPosAnimator->stop();
             d->highlight->setPosition(qRound(pos));
             // update current index
             if (FxListItem *snapItem = d->snapItemAt(d->highlight->position())) {
                 if (snapItem->index >= 0 && snapItem->index != d->currentIndex)
                     d->updateCurrent(snapItem->index);
             }
         }
     }
     if ((d->hData.flicking || d->vData.flicking) && d->correctFlick && !d->inFlickCorrection) {
         d->inFlickCorrection = true;
         // Near an end and it seems that the extent has changed?
         // Recalculate the flick so that we don't end up in an odd position.
         if (yflick() && !d->vData.inOvershoot) {
             if (d->vData.velocity > 0) {
                 const qreal minY = minYExtent();
                 if ((minY - d->vData.move.value() < height()/2 || d->vData.flickTarget - d->vData.move.value() < height()/2)
                     && minY != d->vData.flickTarget)
                     d->flickY(-d->vData.smoothVelocity.value());
                 d->bufferMode = QDeclarativeListViewPrivate::BufferBefore;
             } else if (d->vData.velocity < 0) {
                 const qreal maxY = maxYExtent();
                 if ((d->vData.move.value() - maxY < height()/2 || d->vData.move.value() - d->vData.flickTarget < height()/2)
                     && maxY != d->vData.flickTarget)
                     d->flickY(-d->vData.smoothVelocity.value());
                 d->bufferMode = QDeclarativeListViewPrivate::BufferAfter;
             }
         }
         if (xflick() && !d->hData.inOvershoot) {
             if (d->hData.velocity > 0) {
                 const qreal minX = minXExtent();
                 if ((minX - d->hData.move.value() < width()/2 || d->hData.flickTarget - d->hData.move.value() < width()/2)
                     && minX != d->hData.flickTarget)
                     d->flickX(-d->hData.smoothVelocity.value());
                 d->bufferMode = d->isRightToLeft()
                         ? QDeclarativeListViewPrivate::BufferAfter : QDeclarativeListViewPrivate::BufferBefore;
             } else if (d->hData.velocity < 0) {
                 const qreal maxX = maxXExtent();
                 if ((d->hData.move.value() - maxX < width()/2 || d->hData.move.value() - d->hData.flickTarget < width()/2)
                     && maxX != d->hData.flickTarget)
                     d->flickX(-d->hData.smoothVelocity.value());
                 d->bufferMode = d->isRightToLeft()
                         ? QDeclarativeListViewPrivate::BufferBefore : QDeclarativeListViewPrivate::BufferAfter;
             }
         }
         d->inFlickCorrection = false;
     }
     d->inViewportMoved = false;
 }
Properties
cacheBuffer
int QDeclarativeListView::cacheBuffer private
Definition at line 118 of file qdeclarativelistview_p.h.
count
int QDeclarativeListView::count private
Definition at line 100 of file qdeclarativelistview_p.h.
currentIndex
int QDeclarativeListView::currentIndex private
Definition at line 98 of file qdeclarativelistview_p.h.
currentItem
QDeclarativeItem * QDeclarativeListView::currentItem private
Definition at line 99 of file qdeclarativelistview_p.h.
currentSection
QString QDeclarativeListView::currentSection private
Definition at line 120 of file qdeclarativelistview_p.h.
delegate
QDeclarativeComponent * QDeclarativeListView::delegate private
Definition at line 97 of file qdeclarativelistview_p.h.
footer
QDeclarativeComponent * QDeclarativeListView::footer private
Definition at line 125 of file qdeclarativelistview_p.h.
header
QDeclarativeComponent * QDeclarativeListView::header private
Definition at line 124 of file qdeclarativelistview_p.h.
highlight
QDeclarativeComponent * QDeclarativeListView::highlight private
Definition at line 102 of file qdeclarativelistview_p.h.
highlightFollowsCurrentItem
bool QDeclarativeListView::highlightFollowsCurrentItem private
Definition at line 104 of file qdeclarativelistview_p.h.
highlightItem
QDeclarativeItem * QDeclarativeListView::highlightItem private
Definition at line 103 of file qdeclarativelistview_p.h.
highlightMoveDuration
int QDeclarativeListView::highlightMoveDuration private
Definition at line 106 of file qdeclarativelistview_p.h.
highlightMoveSpeed
qreal QDeclarativeListView::highlightMoveSpeed private
Definition at line 105 of file qdeclarativelistview_p.h.
highlightRangeMode
QDeclarativeListView::HighlightRangeMode QDeclarativeListView::highlightRangeMode private
Definition at line 112 of file qdeclarativelistview_p.h.
highlightResizeDuration
int QDeclarativeListView::highlightResizeDuration private
Definition at line 108 of file qdeclarativelistview_p.h.
highlightResizeSpeed
qreal QDeclarativeListView::highlightResizeSpeed private
Definition at line 107 of file qdeclarativelistview_p.h.
keyNavigationWraps
bool QDeclarativeListView::keyNavigationWraps private
Definition at line 117 of file qdeclarativelistview_p.h.
layoutDirection
Qt::LayoutDirection QDeclarativeListView::layoutDirection private
Definition at line 116 of file qdeclarativelistview_p.h.
model
QVariant QDeclarativeListView::model private
Definition at line 96 of file qdeclarativelistview_p.h.
orientation
QDeclarativeListView::Orientation QDeclarativeListView::orientation private
Definition at line 115 of file qdeclarativelistview_p.h.
preferredHighlightBegin
qreal QDeclarativeListView::preferredHighlightBegin private
Definition at line 110 of file qdeclarativelistview_p.h.
preferredHighlightEnd
qreal QDeclarativeListView::preferredHighlightEnd private
Definition at line 111 of file qdeclarativelistview_p.h.
section
QDeclarativeViewSection* QDeclarativeListView::section private
Definition at line 119 of file qdeclarativelistview_p.h.
snapMode
QDeclarativeListView::SnapMode QDeclarativeListView::snapMode private
Definition at line 122 of file qdeclarativelistview_p.h.
spacing
qreal QDeclarativeListView::spacing private
Definition at line 114 of file qdeclarativelistview_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativelistview_p.h
/src/declarative/graphicsitems/qdeclarativelistview.cpp