Qt 4.8: QWidgetPrivate Class Reference
QWidgetPrivate Class Reference
#include <qwidget_p.h>
Public Types
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 363 of file qwidget_p.h.
Enumerations
CloseMode
enum QWidgetPrivate::CloseMode
Enumerator
CloseNoEvent
CloseWithEvent
CloseWithSpontaneousEvent
Definition at line 380 of file qwidget_p.h.
                    {
         CloseNoEvent,
         CloseWithEvent,
         CloseWithSpontaneousEvent
     };
Direction
enum QWidgetPrivate::Direction
Enumerator
DirectionNorth
DirectionEast
DirectionSouth
DirectionWest
Definition at line 386 of file qwidget_p.h.
                    {
         DirectionNorth = 0x01,
         DirectionEast = 0x10,
         DirectionSouth = 0x02,
         DirectionWest = 0x20
     };
DrawWidgetFlags
enum QWidgetPrivate::DrawWidgetFlags
Enumerator
DrawAsRoot
DrawPaintOnScreen
DrawRecursive
DrawInvisible
DontSubtractOpaqueChildren
DontSetCompositionMode
DontDrawOpaqueChildren
DontDrawNativeChildren
Definition at line 369 of file qwidget_p.h.
{
         DrawAsRoot = 0x01,
         DrawPaintOnScreen = 0x02,
         DrawRecursive = 0x04,
         DrawInvisible = 0x08,
         DontSubtractOpaqueChildren = 0x10,
         DontSetCompositionMode = 0x20,
         DontDrawOpaqueChildren = 0x40,
         DontDrawNativeChildren = 0x80
     };
Constructors and Destructors
QWidgetPrivate()
QWidgetPrivate::QWidgetPrivate (int version = QObjectPrivateVersion) explicit
Definition at line 288 of file qwidget.cpp.
     : QObjectPrivate(version)
       , extra(0)
       , focus_next(0)
       , focus_prev(0)
       , focus_child(0)
       , layout(0)
       , needsFlush(0)
       , redirectDev(0)
       , widgetItem(0)
       , extraPaintEngine(0)
       , polished(0)
       , graphicsEffect(0)
 #if !defined(QT_NO_IM)
       , imHints(Qt::ImhNone)
 #endif
       , inheritedFontResolveMask(0)
       , inheritedPaletteResolveMask(0)
       , leftmargin(0)
       , topmargin(0)
       , rightmargin(0)
       , bottommargin(0)
       , leftLayoutItemMargin(0)
       , topLayoutItemMargin(0)
       , rightLayoutItemMargin(0)
       , bottomLayoutItemMargin(0)
       , hd(0)
       , size_policy(QSizePolicy::Preferred, QSizePolicy::Preferred)
       , fg_role(QPalette::NoRole)
       , bg_role(QPalette::NoRole)
       , dirtyOpaqueChildren(1)
       , isOpaque(0)
       , inDirtyList(0)
       , isScrolled(0)
       , isMoved(0)
       , isGLWidget(0)
       , usesDoubleBufferedGLContext(0)
 #ifndef QT_NO_IM
       , inheritsInputMethodHints(0)
 #endif
       , inSetParent(0)
 #if defined(Q_WS_X11)
       , picture(0)
 #elif defined(Q_WS_WIN)
       , noPaintOnScreen(0)
   #ifndef QT_NO_GESTURES
       , nativeGesturePanEnabled(0)
   #endif
 #elif defined(Q_WS_MAC)
       , needWindowChange(0)
       , window_event(0)
       , qd_hd(0)
 #elif defined(Q_OS_SYMBIAN)
       , symbianScreenNumber(0)
       , fixNativeOrientationCalled(false)
       , isGLGlobalShareWidget(0)
 #endif
 {
     if (!qApp) {
         qFatal("QWidget: Must construct a QApplication before a QPaintDevice");
         return;
     }
     if (version != QObjectPrivateVersion)
         qFatal("Cannot mix incompatible Qt libraries");
     isWidget = true;
     memset(high_attributes, 0, sizeof(high_attributes));
 #if QT_MAC_USE_COCOA
     drawRectOriginalAdded = false;
     originalDrawMethod = true;
     changeMethods = false;
     isInUnifiedToolbar = false;
     unifiedSurface = 0;
     toolbar_ancestor = 0;
     flushRequested = false;
     touchEventsEnabled = false;
 #endif // QT_MAC_USE_COCOA
 #ifdef QWIDGET_EXTRA_DEBUG
     static int count = 0;
     qDebug() << "widgets" << ++count;
 #endif
 }
~QWidgetPrivate()
QWidgetPrivate::~QWidgetPrivate ()
Definition at line 373 of file qwidget.cpp.
 {
 #ifdef Q_OS_SYMBIAN
     _q_cleanupWinIds();
 #endif
     if (widgetItem)
         widgetItem->wid = 0;
     if (extra)
         deleteExtra();
 #ifndef QT_NO_GRAPHICSEFFECT
     delete graphicsEffect;
 #endif //QT_NO_GRAPHICSEFFECT
 }
Functions
_q_showIfNotHidden()
void QWidgetPrivate::_q_showIfNotHidden ()
Definition at line 8137 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if ( !(q->isHidden() && q->testAttribute(Qt::WA_WState_ExplicitShowHide)) )
         q->setVisible(true);
 }
aboutToDestroy()
virtual void QWidgetPrivate::aboutToDestroy () inline virtual
Reimplemented in QGLWidgetPrivate.
Definition at line 581 of file qwidget_p.h.
 {}
activateChildLayoutsRecursively()
void QWidgetPrivate::activateChildLayoutsRecursively ()
Definition at line 7752 of file qwidget.cpp.
Referenced by activateChildLayoutsRecursively().
 {
     sendPendingMoveAndResizeEvents(false, true);
     for (int i = 0; i < children.size(); ++i) {
         QWidget *child = qobject_cast<QWidget *>(children.at(i));
         if (!child || child->isHidden() || child->isWindow())
             continue;
         child->ensurePolished();
         // Activate child's layout
         QWidgetPrivate *childPrivate = child->d_func();
         if (childPrivate->layout)
             childPrivate->layout->activate();
         // Pretend we're visible.
         const bool wasVisible = child->isVisible();
         if (!wasVisible)
             child->setAttribute(Qt::WA_WState_Visible);
         // Do the same for all my children.
         childPrivate->activateChildLayoutsRecursively();
         // We're not cheating anymore.
         if (!wasVisible)
             child->setAttribute(Qt::WA_WState_Visible, false);
     }
 }
adjustedSize()
QSize QWidgetPrivate::adjustedSize () const
Definition at line 8425 of file qwidget.cpp.
 {
     Q_Q(const QWidget);
     QSize s = q->sizeHint();
     if (q->isWindow()) {
         Qt::Orientations exp;
         if (layout) {
             if (layout->hasHeightForWidth())
                 s.setHeight(layout->totalHeightForWidth(s.width()));
             exp = layout->expandingDirections();
         } else
         {
             if (q->sizePolicy().hasHeightForWidth())
                 s.setHeight(q->heightForWidth(s.width()));
             exp = q->sizePolicy().expandingDirections();
         }
         if (exp & Qt::Horizontal)
             s.setWidth(qMax(s.width(), 200));
         if (exp & Qt::Vertical)
             s.setHeight(qMax(s.height(), 100));
 #if defined(Q_WS_X11)
         QRect screen = QApplication::desktop()->screenGeometry(q->x11Info().screen());
 #else // all others
         QRect screen = QApplication::desktop()->screenGeometry(q->pos());
 #endif
 #if defined (Q_WS_WINCE) || defined (Q_OS_SYMBIAN)
         s.setWidth(qMin(s.width(), screen.width()));
         s.setHeight(qMin(s.height(), screen.height()));
 #else
         s.setWidth(qMin(s.width(), screen.width()*2/3));
         s.setHeight(qMin(s.height(), screen.height()*2/3));
 #endif
         if (QTLWExtra *extra = maybeTopData())
             extra->sizeAdjusted = true;
     }
     if (!s.isValid()) {
         QRect r = q->childrenRect(); // get children rectangle
         if (r.isNull())
             return s;
         s = r.size() + QSize(2 * r.x(), 2 * r.y());
     }
     return s;
 }
adjustFlags()
void QWidgetPrivate::adjustFlags (Qt::WindowFlags & flags, QWidget * w = 0) static
Definition at line 1242 of file qwidget.cpp.
Referenced by QWorkspace::addWindow(), isServerProcess(), and setParent_sys().
 {
     bool customize =  (flags & (Qt::CustomizeWindowHint
             | Qt::FramelessWindowHint
             | Qt::WindowTitleHint
             | Qt::WindowSystemMenuHint
             | Qt::WindowMinimizeButtonHint
             | Qt::WindowMaximizeButtonHint
             | Qt::WindowCloseButtonHint
             | Qt::WindowContextHelpButtonHint));
     uint type = (flags & Qt::WindowType_Mask);
     if ((type == Qt::Widget || type == Qt::SubWindow) && w && !w->parent()) {
         type = Qt::Window;
         flags |= Qt::Window;
     }
     if (flags & Qt::CustomizeWindowHint) {
         // modify window flags to make them consistent.
         // Only enable this on non-Mac platforms. Since the old way of doing this would
         // interpret WindowSystemMenuHint as a close button and we can't change that behavior
         // we can't just add this in.
 #ifndef Q_WS_MAC
         if (flags & (Qt::WindowMinMaxButtonsHint | Qt::WindowCloseButtonHint | Qt::WindowContextHelpButtonHint)) {
             flags |= Qt::WindowSystemMenuHint;
 #else
         if (flags & (Qt::WindowMinMaxButtonsHint | Qt::WindowCloseButtonHint
                      | Qt::WindowSystemMenuHint)) {
 #endif
             flags |= Qt::WindowTitleHint;
             flags &= ~Qt::FramelessWindowHint;
         }
     } else if (customize && !(flags & Qt::FramelessWindowHint)) {
         // if any of the window hints that affect the titlebar are set
         // and the window is supposed to have frame, we add a titlebar
         // and system menu by default.
         flags |= Qt::WindowSystemMenuHint;
         flags |= Qt::WindowTitleHint;
     }
     if (customize)
         ; // don't modify window flags if the user explicitly set them.
     else if (type == Qt::Dialog || type == Qt::Sheet)
 #ifndef Q_WS_WINCE
         flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowContextHelpButtonHint | Qt::WindowCloseButtonHint;
 #else
         flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint;
 #endif
     else if (type == Qt::Tool)
         flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint;
     else
         flags |= Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowMinimizeButtonHint | Qt::WindowMaximizeButtonHint | Qt::WindowCloseButtonHint;
 }
adjustQuitOnCloseAttribute()
void QWidgetPrivate::adjustQuitOnCloseAttribute ()
Definition at line 12900 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (!q->parentWidget()) {
         Qt::WindowType type = q->windowType();
         if (type == Qt::Widget || type == Qt::SubWindow)
             type = Qt::Window;
         if (type != Qt::Widget && type != Qt::Window && type != Qt::Dialog)
             q->setAttribute(Qt::WA_QuitOnClose, false);
     }
 }
assignedInputContext()
QInputContext * QWidgetPrivate::assignedInputContext () const
Definition at line 446 of file qwidget.cpp.
Referenced by inputContext().
 {
     const QWidget *widget = q_func();
     while (widget) {
         if (QInputContext *qic = widget->d_func()->ic)
             return qic;
         widget = widget->parentWidget();
     }
     return 0;
 }
beginSharedPainter()
QPainter* QWidgetPrivate::beginSharedPainter ()
childAt_helper()
QWidget * QWidgetPrivate::childAt_helper (const QPoint & p, bool ignoreChildrenInDestructor) const
Definition at line 10288 of file qwidget.cpp.
 {
     if (children.isEmpty())
         return 0;
 #ifdef Q_WS_MAC
     Q_Q(const QWidget);
     // Unified tool bars on the Mac require special handling since they live outside
     // QMainWindow's geometry(). See commit: 35667fd45ada49269a5987c235fdedfc43e92bb8
     bool includeFrame = q->isWindow() && qobject_cast<const QMainWindow *>(q)
                         && static_cast<const QMainWindow *>(q)->unifiedTitleAndToolBarOnMac();
     if (includeFrame)
         return childAtRecursiveHelper(p, ignoreChildrenInDestructor, includeFrame);
 #endif
     if (!pointInsideRectAndMask(p))
         return 0;
     return childAtRecursiveHelper(p, ignoreChildrenInDestructor);
 }
childAtRecursiveHelper()
QWidget * QWidgetPrivate::childAtRecursiveHelper (const QPoint & p, bool ignoreChildrenInDestructor, bool includeFrame = false) const
Definition at line 10308 of file qwidget.cpp.
 {
 #ifndef Q_WS_MAC
     Q_UNUSED(includeFrame);
 #endif
     for (int i = children.size() - 1; i >= 0; --i) {
         QWidget *child = qobject_cast<QWidget *>(children.at(i));
         if (!child || child->isWindow() || child->isHidden() || child->testAttribute(Qt::WA_TransparentForMouseEvents)
             || (ignoreChildrenInDestructor && child->data->in_destructor)) {
             continue;
         }
         // Map the point 'p' from parent coordinates to child coordinates.
         QPoint childPoint = p;
 #ifdef Q_WS_MAC
         // 'includeFrame' is true if the child's parent is a top-level QMainWindow with an unified tool bar.
         // An unified tool bar on the Mac lives outside QMainWindow's geometry(), so a normal
         // QWidget::mapFromParent won't do the trick.
         if (includeFrame && qobject_cast<QToolBar *>(child))
             childPoint = qt_mac_nativeMapFromParent(child, p);
         else
 #endif
         childPoint -= child->data->crect.topLeft();
         // Check if the point hits the child.
         if (!child->d_func()->pointInsideRectAndMask(childPoint))
             continue;
         // Do the same for the child's descendants.
         if (QWidget *w = child->d_func()->childAtRecursiveHelper(childPoint, ignoreChildrenInDestructor))
             return w;
         // We have found our target; namely the child at position 'p'.
         return child;
     }
     return 0;
 }
clipRect()
QRect QWidgetPrivate::clipRect () const
Definition at line 1997 of file qwidget.cpp.
Referenced by QX11PaintEngine::begin(), QIconModeViewBase::doDynamicLayout(), QListModeViewBase::doStaticLayout(), effectiveState(), moveRect(), QFocusFrame::paintEvent(), QWidgetBackingStore::staticContents(), and QWidgetBackingStore::sync().
 {
     Q_Q(const QWidget);
     const QWidget * w = q;
     if (!w->isVisible())
         return QRect();
     QRect r = effectiveRectFor(q->rect());
     int ox = 0;
     int oy = 0;
     while (w
             && w->isVisible()
             && !w->isWindow()
             && w->parentWidget()) {
         ox -= w->x();
         oy -= w->y();
         w = w->parentWidget();
         r &= QRect(ox, oy, w->width(), w->height());
     }
     return r;
 }
clipRegion()
QRegion QWidgetPrivate::clipRegion () const
Definition at line 2021 of file qwidget.cpp.
Referenced by effectiveState().
 {
     Q_Q(const QWidget);
     if (!q->isVisible())
         return QRegion();
     QRegion r(q->rect());
     const QWidget * w = q;
     const QWidget *ignoreUpTo;
     int ox = 0;
     int oy = 0;
     while (w
            && w->isVisible()
            && !w->isWindow()
            && w->parentWidget()) {
         ox -= w->x();
         oy -= w->y();
         ignoreUpTo = w;
         w = w->parentWidget();
         r &= QRegion(ox, oy, w->width(), w->height());
         int i = 0;
         while(w->d_func()->children.at(i++) != static_cast<const QObject *>(ignoreUpTo))
             ;
         for ( ; i < w->d_func()->children.size(); ++i) {
             if(QWidget *sibling = qobject_cast<QWidget *>(w->d_func()->children.at(i))) {
                 if(sibling->isVisible() && !sibling->isWindow()) {
                     QRect siblingRect(ox+sibling->x(), oy+sibling->y(),
                                       sibling->width(), sibling->height());
                     if (qRectIntersects(siblingRect, q->rect()))
                         r -= QRegion(siblingRect);
                 }
             }
         }
     }
     return r;
 }
clipToEffectiveMask()
void QWidgetPrivate::clipToEffectiveMask (QRegion & region) const
Definition at line 2230 of file qwidget.cpp.
Referenced by QX11PaintEngine::begin(), QWidgetBackingStore::staticContents(), and QWidgetBackingStore::sync().
 {
     Q_Q(const QWidget);
     const QWidget *w = q;
     QPoint offset;
 #ifndef QT_NO_GRAPHICSEFFECT
     if (graphicsEffect) {
         w = q->parentWidget();
         offset -= data.crect.topLeft();
     }
 #endif //QT_NO_GRAPHICSEFFECT
     while (w) {
         const QWidgetPrivate *wd = w->d_func();
         if (wd->extra && wd->extra->hasMask)
             region &= (w != q) ? wd->extra->mask.translated(offset) : wd->extra->mask;
         if (w->isWindow())
             return;
         offset -= wd->data.crect.topLeft();
         w = w->parentWidget();
     }
 }
close_helper()
bool QWidgetPrivate::close_helper (CloseMode mode)
Definition at line 8218 of file qwidget.cpp.
Referenced by QApplication::qwsProcessEvent().
 {
     if (data.is_closing)
         return true;
     Q_Q(QWidget);
     data.is_closing = 1;
     QPointer<QWidget> that = q;
     QPointer<QWidget> parentWidget = q->parentWidget();
 #ifdef QT3_SUPPORT
     bool isMain = (QApplicationPrivate::main_widget == q);
 #endif
     bool quitOnClose = q->testAttribute(Qt::WA_QuitOnClose);
     if (mode != CloseNoEvent) {
         QCloseEvent e;
         if (mode == CloseWithSpontaneousEvent)
             QApplication::sendSpontaneousEvent(q, &e);
         else
             QApplication::sendEvent(q, &e);
         if (!that.isNull() && !e.isAccepted()) {
             data.is_closing = 0;
             return false;
         }
     }
     if (!that.isNull() && !q->isHidden())
         q->hide();
 #ifdef QT3_SUPPORT
     if (isMain)
         QApplication::quit();
 #endif
     // Attempt to close the application only if this has WA_QuitOnClose set and a non-visible parent
     quitOnClose = quitOnClose && (parentWidget.isNull() || !parentWidget->isVisible());
     if (quitOnClose) {
         /* if there is no non-withdrawn primary window left (except
            the ones without QuitOnClose), we emit the lastWindowClosed
            signal */
         QWidgetList list = QApplication::topLevelWidgets();
         bool lastWindowClosed = true;
         for (int i = 0; i < list.size(); ++i) {
             QWidget *w = list.at(i);
             if (!w->isVisible() || w->parentWidget() || !w->testAttribute(Qt::WA_QuitOnClose))
                 continue;
             lastWindowClosed = false;
             break;
         }
         if (lastWindowClosed)
             QApplicationPrivate::emitLastWindowClosed();
     }
     if (!that.isNull()) {
         data.is_closing = 0;
         if (q->testAttribute(Qt::WA_DeleteOnClose)) {
             q->setAttribute(Qt::WA_DeleteOnClose, false);
             q->deleteLater();
         }
     }
     return true;
 }
create_sys()
void QWidgetPrivate::create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
Definition at line 2480 of file qwidget_mac.mm.
Referenced by getNetWmState(), isServerProcess(), q_createNativeChildrenAndSetParent(), and qt_tablet_cleanup_wce().
 {
     Q_Q(QWidget);
     QMacCocoaAutoReleasePool pool;
     OSViewRef destroyid = 0;
 #ifndef QT_MAC_USE_COCOA
     window_event = 0;
 #endif
     Qt::WindowType type = q->windowType();
     Qt::WindowFlags flags = data.window_flags;
     QWidget *parentWidget = q->parentWidget();
     bool topLevel = (flags & Qt::Window);
     bool popup = (type == Qt::Popup);
     bool dialog = (type == Qt::Dialog
                    || type == Qt::Sheet
                    || type == Qt::Drawer
                    || (flags & Qt::MSWindowsFixedSizeDialogHint));
     bool desktop = (type == Qt::Desktop);
     // Determine this early for top-levels so, we can use it later.
     if (topLevel)
         determineWindowClass();
     if (desktop) {
         QSize desktopSize = qt_mac_desktopSize();
         q->setAttribute(Qt::WA_WState_Visible);
         data.crect.setRect(0, 0, desktopSize.width(), desktopSize.height());
         dialog = popup = false;                  // force these flags off
     } else {
         if (topLevel && (type != Qt::Drawer)) {
             if (QDesktopWidget *dsk = QApplication::desktop()) { // calc pos/size from screen
                 const bool wasResized = q->testAttribute(Qt::WA_Resized);
                 const bool wasMoved = q->testAttribute(Qt::WA_Moved);
                 int deskn = dsk->primaryScreen();
                 if (parentWidget && parentWidget->windowType() != Qt::Desktop)
                     deskn = dsk->screenNumber(parentWidget);
                 QRect screenGeo = dsk->screenGeometry(deskn);
                 if (!wasResized) {
 #ifndef QT_MAC_USE_COCOA
                     data.crect.setSize(QSize(screenGeo.width()/2, 4*screenGeo.height()/10));
 #else
                     NSRect newRect = [NSWindow frameRectForContentRect:NSMakeRect(0, 0,
                                                                   screenGeo.width() / 2.,
                                                                   4 * screenGeo.height() / 10.)
                                         styleMask:topData()->wattr];
                     data.crect.setSize(QSize(newRect.size.width, newRect.size.height));
 #endif
                     // Constrain to minimums and maximums we've set
                     if (extra->minw > 0)
                         data.crect.setWidth(qMax(extra->minw, data.crect.width()));
                     if (extra->minh > 0)
                         data.crect.setHeight(qMax(extra->minh, data.crect.height()));
                     if (extra->maxw > 0)
                         data.crect.setWidth(qMin(extra->maxw, data.crect.width()));
                     if (extra->maxh > 0)
                         data.crect.setHeight(qMin(extra->maxh, data.crect.height()));
                 }
                 if (!wasMoved && !q->testAttribute(Qt::WA_DontShowOnScreen))
                     data.crect.moveTopLeft(QPoint(screenGeo.width()/4,
                                                   3 * screenGeo.height() / 10));
             }
         }
     }
     if(!window)                              // always initialize
         initializeWindow=true;
     hd = 0;
     if(window) {                                // override the old window (with a new NSView)
         OSViewRef nativeView = OSViewRef(window);
         OSViewRef parent = 0;
 #ifndef QT_MAC_USE_COCOA
         CFRetain(nativeView);
 #else
         [nativeView retain];
 #endif
         if (destroyOldWindow)
             destroyid = qt_mac_nativeview_for(q);
         bool transfer = false;
         setWinId((WId)nativeView);
 #ifndef QT_MAC_USE_COCOA
 #ifndef HIViewInstallEventHandler
         // Macro taken from the CarbonEvents Header on Tiger
 #define HIViewInstallEventHandler( target, handler, numTypes, list, userData, outHandlerRef ) \
                InstallEventHandler( HIObjectGetEventTarget( (HIObjectRef) (target) ), (handler), (numTypes), (list), (userData), (outHandlerRef) )
 #endif
         HIViewInstallEventHandler(nativeView, make_widget_eventUPP(), GetEventTypeCount(widget_events), widget_events, 0, 0);
 #endif
         if(topLevel) {
             for(int i = 0; i < 2; ++i) {
                 if(i == 1) {
                     if(!initializeWindow)
                         break;
                     createWindow_sys();
                 }
                 if(OSWindowRef windowref = qt_mac_window_for(nativeView)) {
 #ifndef QT_MAC_USE_COCOA
                     CFRetain(windowref);
 #else
                     [windowref retain];
 #endif
                     if (initializeWindow) {
                         parent = qt_mac_get_contentview_for(windowref);
                     } else {
 #ifndef QT_MAC_USE_COCOA
                         parent = HIViewGetSuperview(nativeView);
 #else
                         parent = [nativeView superview];
 #endif
                     }
                     break;
                 }
             }
             if(!parent)
                 transfer = true;
         } else if (parentWidget) {
             // I need to be added to my parent, therefore my parent needs an NSView
             // Alien note: a 'window' was supplied as argument, meaning this widget
             // is not alien. So therefore the parent cannot be alien either.
             parentWidget->createWinId();
             parent = qt_mac_nativeview_for(parentWidget);
         }
         if(parent != nativeView && parent) {
 #ifndef QT_MAC_USE_COCOA
             HIViewAddSubview(parent, nativeView);
 #else
             [parent addSubview:nativeView];
 #endif
         }
         if(transfer)
             transferChildren();
         data.fstrut_dirty = true; // we'll re calculate this later
         q->setAttribute(Qt::WA_WState_Visible,
 #ifndef QT_MAC_USE_COCOA
                         HIViewIsVisible(nativeView)
 #else
                         ![nativeView isHidden]
 #endif
                         );
         if(initializeWindow) {
 #ifndef QT_MAC_USE_COCOA
             HIRect bounds = CGRectMake(data.crect.x(), data.crect.y(), data.crect.width(), data.crect.height());
             HIViewSetFrame(nativeView, &bounds);
             q->setAttribute(Qt::WA_WState_Visible, HIViewIsVisible(nativeView));
 #else
             NSRect bounds = NSMakeRect(data.crect.x(), data.crect.y(), data.crect.width(), data.crect.height());
             [nativeView setFrame:bounds];
             q->setAttribute(Qt::WA_WState_Visible, [nativeView isHidden]);
 #endif
         }
 #ifndef QT_MAC_USE_COCOA
         initWindowPtr();
 #endif
     } else if (desktop) {                        // desktop widget
         if (!qt_root_win)
             QWidgetPrivate::qt_create_root_win();
         Q_ASSERT(qt_root_win);
         WId rootWinID = 0;
 #ifndef QT_MAC_USE_COCOA
         CFRetain(qt_root_win);
         if(HIViewRef rootContentView = HIViewGetRoot(qt_root_win)) {
             rootWinID = (WId)rootContentView;
             CFRetain(rootContentView);
         }
 #else
         [qt_root_win retain];
         if (OSViewRef rootContentView = [qt_root_win contentView]) {
             rootWinID = (WId)rootContentView;
             [rootContentView retain];
         }
 #endif
         setWinId(rootWinID);
     } else if (topLevel) {
         determineWindowClass();
         if(OSViewRef osview = qt_mac_create_widget(q, this, 0)) {
 #ifndef QT_MAC_USE_COCOA
             HIRect bounds = CGRectMake(data.crect.x(), data.crect.y(),
                                        data.crect.width(), data.crect.height());
             HIViewSetFrame(osview, &bounds);
 #else
             NSRect bounds = NSMakeRect(data.crect.x(), flipYCoordinate(data.crect.y()),
                                        data.crect.width(), data.crect.height());
             [osview setFrame:bounds];
 #endif
             setWinId((WId)osview);
         }
     } else {
         data.fstrut_dirty = false; // non-toplevel widgets don't have a frame, so no need to update the strut
 #ifdef QT_MAC_USE_COCOA
         if (q->testAttribute(Qt::WA_NativeWindow) == false || q->internalWinId() != 0) {
             // INVARIANT: q is Alien, and we should not create an NSView to back it up.
         } else
 #endif
         if (OSViewRef osview = qt_mac_create_widget(q, this, qt_mac_nativeview_for(parentWidget))) {
 #ifndef QT_MAC_USE_COCOA
             HIRect bounds = CGRectMake(data.crect.x(), data.crect.y(), data.crect.width(), data.crect.height());
             HIViewSetFrame(osview, &bounds);
             setWinId((WId)osview);
 #else
             NSRect bounds = NSMakeRect(data.crect.x(), data.crect.y(), data.crect.width(), data.crect.height());
             [osview setFrame:bounds];
             setWinId((WId)osview);
             if (q->isVisible()) {
                 // If q were Alien before, but now became native (e.g. if a call to
                 // winId was done from somewhere), we need to show the view immidiatly:
                 QMacCocoaAutoReleasePool pool;
                 [osview setHidden:NO];
             }
 #endif
         }
     }
     updateIsOpaque();
     if (q->testAttribute(Qt::WA_DropSiteRegistered))
         registerDropSite(true);
     if (q->hasFocus())
         setFocus_sys();
     if (!topLevel && initializeWindow)
         setWSGeometry();
     if (destroyid)
         qt_mac_destructView(destroyid);
 }
createDefaultWindowSurface()
QWindowSurface * QWidgetPrivate::createDefaultWindowSurface ()
Definition at line 398 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     QWindowSurface *surface;
 #ifndef QT_NO_PROPERTIES
     if (q->property("_q_DummyWindowSurface").toBool()) {
         surface = new QDummyWindowSurface(q);
     } else
 #endif
     {
         if (QApplicationPrivate::graphicsSystem())
             surface = QApplicationPrivate::graphicsSystem()->createWindowSurface(q);
         else
             surface = createDefaultWindowSurface_sys();
     }
     return surface;
 }
createDefaultWindowSurface_sys()
QWindowSurface * QWidgetPrivate::createDefaultWindowSurface_sys ()
Definition at line 3412 of file qwidget_mac.mm.
Referenced by createDefaultWindowSurface(), QVGGraphicsSystem::createWindowSurface(), QGLGraphicsSystem::createWindowSurface(), effectiveState(), and setWindowRole().
 {
     return new QMacWindowSurface(q_func());
 }
createExtra()
void QWidgetPrivate::createExtra ()
Creates the widget extra data.
Warning
This function is not part of the public interface.
Definition at line 1802 of file qwidget.cpp.
Referenced by QGLWindowSurface::hijackWindow(), qt_grab_cursor(), and QWidgetBackingStore::updateStaticContentsSize().
 {
     if (!extra) {                                // if not exists
         extra = new QWExtra;
         extra->glContext = 0;
         extra->topextra = 0;
 #ifndef QT_NO_GRAPHICSVIEW
         extra->proxyWidget = 0;
 #endif
 #ifndef QT_NO_CURSOR
         extra->curs = 0;
 #endif
         extra->minw = 0;
         extra->minh = 0;
         extra->maxw = QWIDGETSIZE_MAX;
         extra->maxh = QWIDGETSIZE_MAX;
         extra->customDpiX = 0;
         extra->customDpiY = 0;
         extra->explicitMinSize = 0;
         extra->explicitMaxSize = 0;
         extra->autoFillBackground = 0;
         extra->nativeChildrenForced = 0;
         extra->inRenderWithPainter = 0;
         extra->hasMask = 0;
         createSysExtra();
 #ifdef QWIDGET_EXTRA_DEBUG
         static int count = 0;
         qDebug() << "extra" << ++count;
 #endif
     }
 }
createRecursively()
void QWidgetPrivate::createRecursively ()
Definition at line 1423 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     q->create(0, true, true);
     for (int i = 0; i < children.size(); ++i) {
         QWidget *child = qobject_cast<QWidget *>(children.at(i));
         if (child && !child->isHidden() && !child->isWindow() && !child->testAttribute(Qt::WA_WState_Created))
             child->d_func()->createRecursively();
     }
 }
createSysExtra()
void QWidgetPrivate::createSysExtra ()
Definition at line 4958 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), and qt_grab_cursor().
 {
 #ifdef QT_MAC_USE_COCOA
     extra->imageMask = 0;
 #endif
 }
createTLExtra()
void QWidgetPrivate::createTLExtra ()
Definition at line 1755 of file qwidget.cpp.
Referenced by isServerProcess().
 {
     if (!extra)
         createExtra();
     if (!extra->topextra) {
         QTLWExtra* x = extra->topextra = new QTLWExtra;
         x->icon = 0;
         x->iconPixmap = 0;
         x->windowSurface = 0;
         x->sharedPainter = 0;
         x->incw = x->inch = 0;
         x->basew = x->baseh = 0;
         x->frameStrut.setCoords(0, 0, 0, 0);
         x->normalGeometry = QRect(0,0,-1,-1);
         x->savedFlags = 0;
         x->opacity = 255;
         x->posFromMove = false;
         x->sizeAdjusted = false;
         x->inTopLevelResize = false;
         x->inRepaint = false;
         x->embedded = 0;
 #ifdef Q_WS_MAC
 #ifdef QT_MAC_USE_COCOA
         x->wasMaximized = false;
 #endif // QT_MAC_USE_COCOA
 #endif // Q_WS_MAC
         createTLSysExtra();
 #ifdef QWIDGET_EXTRA_DEBUG
         static int count = 0;
         qDebug() << "tlextra" << ++count;
 #endif
 #if defined(Q_WS_QPA)
         x->platformWindow = 0;
         x->platformWindowFormat = QPlatformWindowFormat::defaultFormat();
         x->screenIndex = 0;
 #endif
     }
 }
createTLSysExtra()
void QWidgetPrivate::createTLSysExtra ()
Definition at line 4973 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), and qt_grab_cursor().
 {
     extra->topextra->resizer = 0;
     extra->topextra->isSetGeometry = 0;
     extra->topextra->isMove = 0;
     extra->topextra->wattr = 0;
     extra->topextra->wclass = 0;
     extra->topextra->group = 0;
     extra->topextra->windowIcon = 0;
     extra->topextra->savedWindowAttributesFromMaximized = 0;
 }
createWinId()
void QWidgetPrivate::createWinId (WId id = 0)
Definition at line 2574 of file qwidget.cpp.
Referenced by createWinId(), effectiveState(), isServerProcess(), qt_grab_cursor(), qt_tablet_cleanup_wce(), and setParent_sys().
 {
     Q_Q(QWidget);
 #ifdef ALIEN_DEBUG
     qDebug() << "QWidgetPrivate::createWinId for" << q << winid;
 #endif
     const bool forceNativeWindow = q->testAttribute(Qt::WA_NativeWindow);
     if (!q->testAttribute(Qt::WA_WState_Created) || (forceNativeWindow && !q->internalWinId())) {
 #ifndef Q_WS_QPA
         if (!q->isWindow()) {
             QWidget *parent = q->parentWidget();
             QWidgetPrivate *pd = parent->d_func();
             if (forceNativeWindow && !q->testAttribute(Qt::WA_DontCreateNativeAncestors))
                 parent->setAttribute(Qt::WA_NativeWindow);
             if (!parent->internalWinId()) {
                 pd->createWinId();
             }
             for (int i = 0; i < pd->children.size(); ++i) {
                 QWidget *w = qobject_cast<QWidget *>(pd->children.at(i));
                 if (w && !w->isWindow() && (!w->testAttribute(Qt::WA_WState_Created)
                                             || (!w->internalWinId() && w->testAttribute(Qt::WA_NativeWindow)))) {
                     if (w!=q) {
                         w->create();
                     } else {
                         w->create(winid);
                         // if the window has already been created, we
                         // need to raise it to its proper stacking position
                         if (winid)
                             w->raise();
                     }
                 }
             }
         } else {
             q->create();
         }
 #else
         Q_UNUSED(winid);
         q->create();
 #endif //Q_WS_QPA
     }
 }
deactivateWidgetCleanup()
void QWidgetPrivate::deactivateWidgetCleanup ()
Definition at line 2496 of file qwidget.cpp.
Referenced by hide_sys(), isServerProcess(), and qt_grab_cursor().
 {
     Q_Q(QWidget);
     // If this was the active application window, reset it
     if (QApplication::activeWindow() == q)
         QApplication::setActiveWindow(0);
     // If the is the active mouse press widget, reset it
     if (q == qt_button_down)
         qt_button_down = 0;
 }
deleteExtra()
void QWidgetPrivate::deleteExtra ()
Deletes the widget extra data.
Warning
This function is not part of the public interface.
Definition at line 1843 of file qwidget.cpp.
Referenced by ~QWidgetPrivate().
 {
     if (extra) {                                // if exists
 #ifndef QT_NO_CURSOR
         delete extra->curs;
 #endif
         deleteSysExtra();
 #ifndef QT_NO_STYLE_STYLESHEET
         // dereference the stylesheet style
         if (QStyleSheetStyle *proxy = qobject_cast<QStyleSheetStyle *>(extra->style))
             proxy->deref();
 #endif
         if (extra->topextra) {
             deleteTLSysExtra();
             extra->topextra->backingStore.destroy();
             delete extra->topextra->icon;
             delete extra->topextra->iconPixmap;
 #if defined(Q_WS_QWS) && !defined(QT_NO_QWS_MANAGER)
             delete extra->topextra->qwsManager;
 #endif
             delete extra->topextra->windowSurface;
             delete extra->topextra;
         }
         delete extra;
         // extra->xic destroyed in QWidget::destroy()
         extra = 0;
     }
 }
deleteSysExtra()
void QWidgetPrivate::deleteSysExtra ()
Definition at line 4965 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), qt_grab_cursor(), and qt_tablet_cleanup_wce().
 {
 #ifdef QT_MAC_USE_COCOA
     if (extra->imageMask)
         CFRelease(extra->imageMask);
 #endif
 }
deleteTLSysExtra()
void QWidgetPrivate::deleteTLSysExtra ()
Definition at line 4985 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), and qt_grab_cursor().
 {
 #ifndef QT_MAC_USE_COCOA
     if (extra->topextra->group) {
         qt_mac_release_window_group(extra->topextra->group);
         extra->topextra->group = 0;
     }
     if (extra->topextra->windowIcon) {
         ReleaseIconRef(extra->topextra->windowIcon);
         extra->topextra->windowIcon = 0;
     }
 #endif
 }
drawWidget()
void QWidgetPrivate::drawWidget (QPaintDevice * pdev, const QRegion & rgn, const QPoint & offset, int flags, QPainter * sharedPainter = 0, QWidgetBackingStore * backingStore = 0)
Definition at line 5679 of file qwidget.cpp.
Referenced by QWidgetEffectSourcePrivate::draw(), paintSiblingsRecursive(), and QWidgetBackingStore::sync().
 {
     if (rgn.isEmpty())
         return;
 #if defined(Q_WS_MAC) && defined(QT_MAC_USE_COCOA)
     if (qt_mac_clearDirtyOnWidgetInsideDrawWidget)
         dirtyOnWidget = QRegion();
     // We disable the rendering of QToolBar in the backingStore if
     // it's supposed to be in the unified toolbar on Mac OS X.
     if (backingStore && isInUnifiedToolbar)
         return;
 #endif // Q_WS_MAC && QT_MAC_USE_COCOA
     Q_Q(QWidget);
 #if !defined(QT_NO_GRAPHICSEFFECT) && !defined(Q_WS_MAC)
     if (graphicsEffect && graphicsEffect->isEnabled()) {
         QGraphicsEffectSource *source = graphicsEffect->d_func()->source;
         QWidgetEffectSourcePrivate *sourced = static_cast<QWidgetEffectSourcePrivate *>
                                                          (source->d_func());
         if (!sourced->context) {
             QWidgetPaintContext context(pdev, rgn, offset, flags, sharedPainter, backingStore);
             sourced->context = &context;
             if (!sharedPainter) {
                 QPaintEngine *paintEngine = pdev->paintEngine();
                 paintEngine->d_func()->systemClip = rgn.translated(offset);
                 QPainter p(pdev);
                 p.translate(offset);
                 context.painter = &p;
                 graphicsEffect->draw(&p);
                 paintEngine->d_func()->systemClip = QRegion();
             } else {
                 context.painter = sharedPainter;
                 if (sharedPainter->worldTransform() != sourced->lastEffectTransform) {
                     sourced->invalidateCache();
                     sourced->lastEffectTransform = sharedPainter->worldTransform();
                 }
                 sharedPainter->save();
                 sharedPainter->translate(offset);
                 graphicsEffect->draw(sharedPainter);
                 sharedPainter->restore();
             }
             sourced->context = 0;
             return;
         }
     }
 #endif //QT_NO_GRAFFICSEFFECT
     const bool asRoot = flags & DrawAsRoot;
     const bool alsoOnScreen = flags & DrawPaintOnScreen;
     const bool recursive = flags & DrawRecursive;
     const bool alsoInvisible = flags & DrawInvisible;
     Q_ASSERT(sharedPainter ? sharedPainter->isActive() : true);
     QRegion toBePainted(rgn);
     if (asRoot && !alsoInvisible)
         toBePainted &= clipRect(); //(rgn & visibleRegion());
     if (!(flags & DontSubtractOpaqueChildren))
         subtractOpaqueChildren(toBePainted, q->rect());
     if (!toBePainted.isEmpty()) {
         bool onScreen = paintOnScreen();
         if (!onScreen || alsoOnScreen) {
             //update the "in paint event" flag
             if (q->testAttribute(Qt::WA_WState_InPaintEvent))
                 qWarning("QWidget::repaint: Recursive repaint detected");
             q->setAttribute(Qt::WA_WState_InPaintEvent);
             //clip away the new area
 #ifndef QT_NO_PAINT_DEBUG
             bool flushed = QWidgetBackingStore::flushPaint(q, toBePainted);
 #endif
             QPaintEngine *paintEngine = pdev->paintEngine();
             if (paintEngine) {
                 setRedirected(pdev, -offset);
 #ifdef Q_WS_MAC
                 // (Alien support) Special case for Mac when redirecting: If the paint device
                 // is of the Widget type we need to set WA_WState_InPaintEvent since painting
                 // outside the paint event is not supported on QWidgets. The attributeis
                 // restored further down.
                 if (pdev->devType() == QInternal::Widget)
                     static_cast<QWidget *>(pdev)->setAttribute(Qt::WA_WState_InPaintEvent);
 #endif
                 if (sharedPainter)
                     paintEngine->d_func()->systemClip = toBePainted;
                 else
                     paintEngine->d_func()->systemRect = q->data->crect;
                 //paint the background
                 if ((asRoot || q->autoFillBackground() || onScreen || q->testAttribute(Qt::WA_StyledBackground))
                     && !q->testAttribute(Qt::WA_OpaquePaintEvent) && !q->testAttribute(Qt::WA_NoSystemBackground)) {
                     QPainter p(q);
                     paintBackground(&p, toBePainted, (asRoot || onScreen) ? flags | DrawAsRoot : 0);
                 }
                 if (!sharedPainter)
                     paintEngine->d_func()->systemClip = toBePainted.translated(offset);
                 if (!onScreen && !asRoot && !isOpaque && q->testAttribute(Qt::WA_TintedBackground)) {
                     QPainter p(q);
                     QColor tint = q->palette().window().color();
                     tint.setAlphaF(qreal(.6));
                     p.fillRect(toBePainted.boundingRect(), tint);
                 }
             }
 #if 0
             qDebug() << "painting" << q << "opaque ==" << isOpaque();
             qDebug() << "clipping to" << toBePainted << "location == " << offset
                      << "geometry ==" << QRect(q->mapTo(q->window(), QPoint(0, 0)), q->size());
 #endif
             //actually send the paint event
             QPaintEvent e(toBePainted);
             QCoreApplication::sendSpontaneousEvent(q, &e);
 #if !defined(Q_WS_QWS) && !defined(Q_WS_QPA)
             if (backingStore && !onScreen && !asRoot && (q->internalWinId() || !q->nativeParentWidget()->isWindow()))
                 backingStore->markDirtyOnScreen(toBePainted, q, offset);
 #endif
             //restore
             if (paintEngine) {
 #ifdef Q_WS_MAC
                 if (pdev->devType() == QInternal::Widget)
                     static_cast<QWidget *>(pdev)->setAttribute(Qt::WA_WState_InPaintEvent, false);
 #endif
                 restoreRedirected();
                 if (!sharedPainter)
                     paintEngine->d_func()->systemRect = QRect();
                 else
                     paintEngine->d_func()->currentClipWidget = 0;
                 paintEngine->d_func()->systemClip = QRegion();
             }
             q->setAttribute(Qt::WA_WState_InPaintEvent, false);
             if (q->paintingActive() && !q->testAttribute(Qt::WA_PaintOutsidePaintEvent))
                 qWarning("QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent");
             if (paintEngine && paintEngine->autoDestruct()) {
                 delete paintEngine;
             }
 #ifndef QT_NO_PAINT_DEBUG
             if (flushed)
                 QWidgetBackingStore::unflushPaint(q, toBePainted);
 #endif
         } else if (q->isWindow()) {
             QPaintEngine *engine = pdev->paintEngine();
             if (engine) {
                 QPainter p(pdev);
                 p.setClipRegion(toBePainted);
                 const QBrush bg = q->palette().brush(QPalette::Window);
                 if (bg.style() == Qt::TexturePattern)
                     p.drawTiledPixmap(q->rect(), bg.texture());
                 else
                     p.fillRect(q->rect(), bg);
                 if (engine->autoDestruct())
                     delete engine;
             }
         }
     }
     if (recursive && !children.isEmpty()) {
         paintSiblingsRecursive(pdev, children, children.size() - 1, rgn, offset, flags & ~DrawAsRoot
 #ifdef Q_BACKINGSTORE_SUBSURFACES
                                 , q->windowSurface()
 #endif
                                 , sharedPainter, backingStore);
     }
 }
effectiveFocusWidget()
QWidget* QWidgetPrivate::effectiveFocusWidget () inline
Definition at line 587 of file qwidget_p.h.
{
         QWidget *w = q_func();
         while (w->focusProxy())
             w = w->focusProxy();
         return w;
     }
effectiveRectFor()
QRect QWidgetPrivate::effectiveRectFor (const QRect & rect) const inline
Definition at line 658 of file qwidget_p.h.
Referenced by QWidgetBackingStore::addDirtyWidget(), effectiveState(), isServerProcess(), paintSiblingsRecursive(), and setParent_sys().
     {
 #ifndef QT_NO_GRAPHICSEFFECT
         if (graphicsEffect && graphicsEffect->isEnabled())
             return graphicsEffect->boundingRectFor(rect).toAlignedRect();
 #endif //QT_NO_GRAPHICSEFFECT
         return rect;
     }
endSharedPainter()
bool QWidgetPrivate::endSharedPainter ()
enforceNativeChildren()
void QWidgetPrivate::enforceNativeChildren () inline
Definition at line 638 of file qwidget_p.h.
     {
         if (!extra)
             createExtra();
         if (extra->nativeChildrenForced)
             return;
         extra->nativeChildrenForced = 1;
         for (int i = 0; i < children.size(); ++i) {
             if (QWidget *child = qobject_cast<QWidget *>(children.at(i)))
                 child->setAttribute(Qt::WA_NativeWindow);
         }
     }
extraData()
QWExtra * QWidgetPrivate::extraData () const inline
Definition at line 999 of file qwidget_p.h.
Referenced by QGLWindowSurface::deleted(), QDirectFBWindowSurface::flush(), QGLWindowSurface::hijackWindow(), qt_grab_cursor(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), QApplication::qwsProcessEvent(), setGeometry_sys(), and QGLWindowSurface::updateGeometry().
 {
     return extra;
 }
frameStrut()
QRect QWidgetPrivate::frameStrut () const
Definition at line 12607 of file qwidget.cpp.
Referenced by QRasterWindowSurface::flush(), isServerProcess(), qt_grab_cursor(), qt_mac_unregister_widget(), and setGeometry_sys().
 {
     Q_Q(const QWidget);
     if (!q->isWindow() || (q->windowType() == Qt::Desktop) || q->testAttribute(Qt::WA_DontShowOnScreen)) {
         // x2 = x1 + w - 1, so w/h = 1
         return QRect(0, 0, 1, 1);
     }
     if (data.fstrut_dirty
 #ifndef Q_WS_WIN
         // ### Fix properly for 4.3
         && q->isVisible()
 #endif
         && q->testAttribute(Qt::WA_WState_Created))
         const_cast<QWidgetPrivate *>(this)->updateFrameStrut();
     return maybeTopData() ? maybeTopData()->frameStrut : QRect();
 }
getLayoutItemMargins()
void QWidgetPrivate::getLayoutItemMargins (int * left, int * top, int * right, int * bottom) const
Definition at line 12848 of file qwidget.cpp.
Referenced by QDialogButtonBoxPrivate::initLayout().
 {
     if (left)
         *left = (int)leftLayoutItemMargin;
     if (top)
         *top = (int)topLayoutItemMargin;
     if (right)
         *right = (int)rightLayoutItemMargin;
     if (bottom)
         *bottom = (int)bottomLayoutItemMargin;
 }
getOpaqueChildren()
const QRegion & QWidgetPrivate::getOpaqueChildren () const
Definition at line 2098 of file qwidget.cpp.
Referenced by getOpaqueChildren().
 {
     if (!dirtyOpaqueChildren)
         return opaqueChildren;
     QWidgetPrivate *that = const_cast<QWidgetPrivate*>(this);
     that->opaqueChildren = QRegion();
     for (int i = 0; i < children.size(); ++i) {
         QWidget *child = qobject_cast<QWidget *>(children.at(i));
         if (!child || !child->isVisible() || child->isWindow())
             continue;
         const QPoint offset = child->geometry().topLeft();
         QWidgetPrivate *childd = child->d_func();
         QRegion r = childd->isOpaque ? child->rect() : childd->getOpaqueChildren();
         if (childd->extra && childd->extra->hasMask)
             r &= childd->extra->mask;
         if (r.isEmpty())
             continue;
         r.translate(offset);
         that->opaqueChildren += r;
     }
     that->opaqueChildren &= q_func()->rect();
     that->dirtyOpaqueChildren = false;
     return that->opaqueChildren;
 }
handleSoftwareInputPanel()
void QWidgetPrivate::handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus) inline
Definition at line 669 of file qwidget_p.h.
Referenced by QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), and QGraphicsTextItem::mouseReleaseEvent().
     {
         Q_Q(QWidget);
         if (button == Qt::LeftButton && qApp->autoSipEnabled()) {
             QStyle::RequestSoftwareInputPanel behavior = QStyle::RequestSoftwareInputPanel(
                     q->style()->styleHint(QStyle::SH_RequestSoftwareInputPanel));
             if (!clickCausedFocus || behavior == QStyle::RSIP_OnMouseClick) {
                 QEvent event(QEvent::RequestSoftwareInputPanel);
                 QApplication::sendEvent(q, &event);
             }
         }
     }
hasHeightForWidth()
bool QWidgetPrivate::hasHeightForWidth () const virtual
Warning
This function is not part of the public interface.
virtual private*
This is a bit hackish, but ideally we would have created a virtual function in the public API (however, too late...) so that subclasses could reimplement their own function. Instead we add a virtual function to QWidgetPrivate.
Qt5: move to public class and make virtual
Reimplemented in QTabWidgetPrivate.
Definition at line 10260 of file qwidget.cpp.
Referenced by QTabWidgetPrivate::hasHeightForWidth(), QSizeGrip::mouseMoveEvent(), and QSizeGrip::mousePressEvent().
 {
     return layout ? layout->hasHeightForWidth() : size_policy.hasHeightForWidth();
 }
hide_helper()
void QWidgetPrivate::hide_helper ()
Warning
This function is not part of the public interface.
Definition at line 7898 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     bool isEmbedded = false;
 #if !defined QT_NO_GRAPHICSVIEW
     isEmbedded = q->isWindow() && !bypassGraphicsProxyWidget(q) && nearestGraphicsProxyWidget(q->parentWidget()) != 0;
 #else
     Q_UNUSED(isEmbedded);
 #endif
     if (!isEmbedded && (q->windowType() == Qt::Popup))
         qApp->d_func()->closePopup(q);
     // Move test modal here.  Otherwise, a modal dialog could get
     // destroyed and we lose all access to its parent because we haven't
     // left modality.  (Eg. modal Progress Dialog)
     if (!isEmbedded && q->isModal() && q->isWindow())
         QApplicationPrivate::leaveModal(q);
 #if defined(Q_WS_WIN)
     if (q->isWindow() && !(q->windowType() == Qt::Popup) && q->parentWidget()
         && !q->parentWidget()->isHidden() && q->isActiveWindow())
         q->parentWidget()->activateWindow();        // Activate parent
 #endif
     q->setAttribute(Qt::WA_Mapped, false);
     hide_sys();
     bool wasVisible = q->testAttribute(Qt::WA_WState_Visible);
     if (wasVisible) {
         q->setAttribute(Qt::WA_WState_Visible, false);
     }
     QHideEvent hideEvent;
     QApplication::sendEvent(q, &hideEvent);
     hideChildren(false);
     // next bit tries to move the focus if the focus widget is now
     // hidden.
     if (wasVisible) {
 #if defined(Q_WS_WIN) || defined(Q_WS_X11) || defined (Q_WS_QWS) || defined(Q_WS_MAC) || defined(Q_WS_QPA)
         qApp->d_func()->sendSyntheticEnterLeave(q);
 #endif
         QWidget *fw = QApplication::focusWidget();
         while (fw &&  !fw->isWindow()) {
             if (fw == q) {
                 q->focusNextPrevChild(true);
                 break;
             }
             fw = fw->parentWidget();
         }
     }
     if (QWidgetBackingStore *bs = maybeBackingStore())
         bs->removeDirtyWidget(q);
 #ifndef QT_NO_ACCESSIBILITY
     if (wasVisible)
         QAccessible::updateAccessibility(q, 0, QAccessible::ObjectHide);
 #endif
 }
hide_sys()
void QWidgetPrivate::hide_sys ()
Platform-specific part of QWidget::hide().
Warning
This function is not part of the public interface.
Definition at line 3589 of file qwidget_mac.mm.
Referenced by isServerProcess(), qt_grab_cursor(), and setNetWmWindowTypes().
 {
     Q_Q(QWidget);
     if((q->windowType() == Qt::Desktop)) //you can't hide the desktop!
         return;
     QMacCocoaAutoReleasePool pool;
     if(q->isWindow()) {
 #ifdef QT_MAC_USE_COCOA
         setSubWindowStacking(false);
 #endif
         OSWindowRef window = qt_mac_window_for(q);
         if(qt_mac_is_macsheet(q)) {
 #ifndef QT_MAC_USE_COCOA
             WindowRef parent = 0;
             if(GetSheetWindowParent(window, &parent) != noErr || !parent)
                 ShowHide(window, false);
             else
                 HideSheetWindow(window);
 #else
             [NSApp endSheet:window];
             [window orderOut:window];
 #endif
         } else if(qt_mac_is_macdrawer(q)) {
 #ifndef QT_MAC_USE_COCOA
             CloseDrawer(window, false);
 #else
             [qt_mac_drawer_for(q) close];
 #endif
         } else {
 #ifndef QT_MAC_USE_COCOA
             ShowHide(window, false);
 #else
             // Only needed if it exists from 10.7 or later
             if ((q->windowType() == Qt::Tool) && [window respondsToSelector: @selector(setAnimationBehavior:)])
                 [window setAnimationBehavior: 2]; // NSWindowAnimationBehaviorNone == 2
             [window orderOut:window];
             // Unfortunately it is not as easy as just hiding the window, we need
             // to find out if we were in full screen mode. If we were and this is
             // the last window in full screen mode then we need to unset the full screen
             // mode. If this is not the last visible window in full screen mode then we
             // don't change the full screen mode.
             if(q->isFullScreen())
             {
                 bool keepFullScreen = false;
                 QWidgetList windowList = qApp->topLevelWidgets();
                 int windowCount = windowList.count();
                 for(int i = 0; i < windowCount; i++)
                 {
                     QWidget *w = windowList[i];
                     // If it is the same window, we don't need to check :-)
                     if(q == w)
                         continue;
                     // If they are not visible or if they are minimized then
                     // we just ignore them.
                     if(!w->isVisible() || w->isMinimized())
                         continue;
                     // Is it full screen?
                     // Notice that if there is one window in full screen mode then we
                     // cannot switch the full screen mode off, therefore we just abort.
                     if(w->isFullScreen()) {
                         keepFullScreen = true;
                         break;
                     }
                 }
                 // No windows in full screen mode, so let just unset that flag.
                 if(!keepFullScreen)
                     qt_mac_set_fullscreen_mode(false);
             }
 #endif
             toggleDrawers(false);
             qt_mac_update_cursor();
 #ifndef QT_MAC_USE_COCOA
             // Clear modality (because it seems something that we've always done).
             if (data.window_modality != Qt::NonModal) {
                 SetWindowModality(window, kWindowModalityNone,
                           q->parentWidget() ? qt_mac_window_for(q->parentWidget()->window()) : 0);
             }
 #endif
         }
 #ifndef QT_MAC_USE_COCOA
         // If the window we now hide was the active window, we need
         // to find, and activate another window on screen. NB: Cocoa takes care of this
         // logic for us (and distinquishes between main windows and key windows)
         if (q->isActiveWindow() && !(q->windowType() == Qt::Popup)) {
             QWidget *w = 0;
             if(q->parentWidget())
                 w = q->parentWidget()->window();
             if(!w || (!w->isVisible() && !w->isMinimized())) {
                 for (WindowPtr wp = GetFrontWindowOfClass(kMovableModalWindowClass, true);
                     wp; wp = GetNextWindowOfClass(wp, kMovableModalWindowClass, true)) {
                     if((w = qt_mac_find_window(wp)))
                         break;
                 }
                 if (!w){
                     for (WindowPtr wp = GetFrontWindowOfClass(kDocumentWindowClass, true);
                             wp; wp = GetNextWindowOfClass(wp, kDocumentWindowClass, true)) {
                         if((w = qt_mac_find_window(wp)))
                             break;
                     }
                 }
                 if (!w){
                     for(WindowPtr wp = GetFrontWindowOfClass(kSimpleWindowClass, true);
                         wp; wp = GetNextWindowOfClass(wp, kSimpleWindowClass, true)) {
                         if((w = qt_mac_find_window(wp)))
                             break;
                     }
                 }
             }
             if(w && w->isVisible() && !w->isMinimized()) {
                 qt_event_request_activate(w);
             }
         }
 #endif
     } else {
          invalidateBuffer(q->rect());
 #ifndef QT_MAC_USE_COCOA
         HIViewSetVisible(qt_mac_nativeview_for(q), false);
 #else
         if (NSView *view = qt_mac_nativeview_for(q)) {
             // INVARIANT: q is native. Just hide the view:
             [view setHidden:YES];
         } else {
             // INVARIANT: q is alien. Repaint where q is placed instead:
             qt_mac_updateParentUnderAlienWidget(q);
         }
 #endif
     }
 #ifdef QT_MAC_USE_COCOA
     if ([NSApp isActive] && !qt_button_down && !QWidget::mouseGrabber()){
         // Update enter/leave immidiatly, don't wait for a move event. But only
         // if no grab exists (even if the grab points to this widget, it seems, ref X11)
         QPoint qlocal, qglobal;
         QWidget *widgetUnderMouse = 0;
         qt_mac_getTargetForMouseEvent(0, QEvent::Leave, qlocal, qglobal, 0, &widgetUnderMouse);
         if (q == widgetUnderMouse) {
             QApplicationPrivate::dispatchEnterLeave(widgetUnderMouse, qt_last_native_mouse_receiver);
             qt_last_mouse_receiver = widgetUnderMouse;
             qt_last_native_mouse_receiver = widgetUnderMouse ?
                 (widgetUnderMouse->internalWinId() ? widgetUnderMouse : widgetUnderMouse->nativeParentWidget()) : 0;
        }
      }
 #endif
     topLevelAt_cache = 0;
     qt_event_request_window_change(q);
     deactivateWidgetCleanup();
     qt_mac_event_release(q);
 }
hideChildren()
void QWidgetPrivate::hideChildren (bool spontaneous)
Definition at line 8167 of file qwidget.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     QList<QObject*> childList = children;
     for (int i = 0; i < childList.size(); ++i) {
         QWidget *widget = qobject_cast<QWidget*>(childList.at(i));
         if (!widget || widget->isWindow() || widget->testAttribute(Qt::WA_WState_Hidden))
             continue;
 #ifdef QT_MAC_USE_COCOA
         // Before doing anything we need to make sure that we don't leave anything in a non-consistent state.
         // When hiding a widget we need to make sure that no mouse_down events are active, because
         // the mouse_up event will never be received by a hidden widget or one of its descendants.
         // The solution is simple, before going through with this we check if there are any mouse_down events in
         // progress, if so we check if it is related to this widget or not. If so, we just reset the mouse_down and
         // then we continue.
         // In X11 and Windows we send a mouse_release event, however we don't do that here because we were already
         // ignoring that from before. I.e. Carbon did not send the mouse release event, so we will not send the
         // mouse release event. There are two ways to interpret this:
         // 1. If we don't send the mouse release event, the widget might get into an inconsistent state, i.e. it
         // might be waiting for a release event that will never arrive.
         // 2. If we send the mouse release event, then the widget might decide to trigger an action that is not
         // supposed to trigger because it is not visible.
         if(widget == qt_button_down)
             qt_button_down = 0;
 #endif // QT_MAC_USE_COCOA
         if (spontaneous)
             widget->setAttribute(Qt::WA_Mapped, false);
         else
             widget->setAttribute(Qt::WA_WState_Visible, false);
         widget->d_func()->hideChildren(spontaneous);
         QHideEvent e;
         if (spontaneous) {
             QApplication::sendSpontaneousEvent(widget, &e);
         } else {
             QApplication::sendEvent(widget, &e);
             if (widget->internalWinId()
                 && widget->testAttribute(Qt::WA_DontCreateNativeAncestors)) {
                 // hide_sys() on an ancestor won't have any affect on this
                 // widget, so it needs an explicit hide_sys() of its own
                 widget->d_func()->hide_sys();
             }
         }
 #if defined(Q_WS_WIN) || defined(Q_WS_X11) || defined (Q_WS_QWS) || defined(Q_WS_MAC) || defined(Q_WS_QPA)
         qApp->d_func()->sendSyntheticEnterLeave(widget);
 #endif
 #ifndef QT_NO_ACCESSIBILITY
         if (!spontaneous)
             QAccessible::updateAccessibility(widget, 0, QAccessible::ObjectHide);
 #endif
     }
 }
inheritStyle()
void QWidgetPrivate::inheritStyle ()
Definition at line 2865 of file qwidget.cpp.
 {
 #ifndef QT_NO_STYLE_STYLESHEET
     Q_Q(QWidget);
     QStyleSheetStyle *proxy = extra ? qobject_cast<QStyleSheetStyle *>(extra->style) : 0;
     if (!q->styleSheet().isEmpty()) {
         Q_ASSERT(proxy);
         proxy->repolish(q);
         return;
     }
     QStyle *origStyle = proxy ? proxy->base : (extra ? (QStyle*)extra->style : 0);
     QWidget *parent = q->parentWidget();
     QStyle *parentStyle = (parent && parent->d_func()->extra) ? (QStyle*)parent->d_func()->extra->style : 0;
     // If we have stylesheet on app or parent has stylesheet style, we need
     // to be running a proxy
     if (!qApp->styleSheet().isEmpty() || qobject_cast<QStyleSheetStyle *>(parentStyle)) {
         QStyle *newStyle = parentStyle;
         if (q->testAttribute(Qt::WA_SetStyle))
             newStyle = new QStyleSheetStyle(origStyle);
         else if (QStyleSheetStyle *newProxy = qobject_cast<QStyleSheetStyle *>(parentStyle))
             newProxy->ref();
         setStyle_helper(newStyle, true);
         return;
     }
     // So, we have no stylesheet on parent/app and we have an empty stylesheet
     // we just need our original style back
     if (origStyle == (extra ? (QStyle*)extra->style : 0)) // is it any different?
         return;
     // We could have inherited the proxy from our parent (which has a custom style)
     // In such a case we need to start following the application style (i.e revert
     // the propagation behavior of QStyleSheetStyle)
     if (!q->testAttribute(Qt::WA_SetStyle))
         origStyle = 0;
     setStyle_helper(origStyle, true);
 #endif // QT_NO_STYLE_STYLESHEET
 }
init()
void QWidgetPrivate::init (QWidget * desktopWidget, Qt::WindowFlags f)
Definition at line 1298 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (QApplication::type() == QApplication::Tty)
         qFatal("QWidget: Cannot create a QWidget when no GUI is being used");
     Q_ASSERT(allWidgets);
     if (allWidgets)
         allWidgets->insert(q);
     QWidget *desktopWidget = 0;
     if (parentWidget && parentWidget->windowType() == Qt::Desktop) {
         desktopWidget = parentWidget;
         parentWidget = 0;
     }
     q->data = &data;
 #ifndef QT_NO_THREAD
     if (!parent) {
         Q_ASSERT_X(q->thread() == qApp->thread(), "QWidget",
                    "Widgets must be created in the GUI thread.");
     }
 #endif
 #if defined(Q_WS_X11)
     if (desktopWidget) {
         // make sure the widget is created on the same screen as the
         // programmer specified desktop widget
         xinfo = desktopWidget->d_func()->xinfo;
     }
 #elif defined(Q_OS_SYMBIAN)
     if (desktopWidget) {
         symbianScreenNumber = qt_widget_private(desktopWidget)->symbianScreenNumber;
     }
 #elif defined(Q_WS_QPA)
     if (desktopWidget) {
         int screen = desktopWidget->d_func()->topData()->screenIndex;
         topData()->screenIndex = screen;
         QPlatformIntegration *platform = QApplicationPrivate::platformIntegration();
         platform->moveToScreen(q, screen);
     }
 #else
     Q_UNUSED(desktopWidget);
 #endif
     data.fstrut_dirty = true;
     data.winid = 0;
     data.widget_attributes = 0;
     data.window_flags = f;
     data.window_state = 0;
     data.focus_policy = 0;
     data.context_menu_policy = Qt::DefaultContextMenu;
     data.window_modality = Qt::NonModal;
     data.sizehint_forced = 0;
     data.is_closing = 0;
     data.in_show = 0;
     data.in_set_window_state = 0;
     data.in_destructor = false;
     // Widgets with Qt::MSWindowsOwnDC (typically QGLWidget) must have a window handle.
     if (f & Qt::MSWindowsOwnDC)
         q->setAttribute(Qt::WA_NativeWindow);
 //#ifdef Q_WS_MAC
 //    q->setAttribute(Qt::WA_NativeWindow);
 //#endif
     q->setAttribute(Qt::WA_QuitOnClose); // might be cleared in adjustQuitOnCloseAttribute()
     adjustQuitOnCloseAttribute();
     q->setAttribute(Qt::WA_WState_Hidden);
     //give potential windows a bigger "pre-initial" size; create_sys() will give them a new size later
 #ifdef Q_OS_SYMBIAN
     if (isGLWidget) {
         // Don't waste GPU mem for unnecessary large egl surface until resized by application
         data.crect = QRect(0,0,1,1);
     } else {
         data.crect = parentWidget ? QRect(0,0,100,30) : QRect(0,0,360,640);
     }
 #else
     data.crect = parentWidget ? QRect(0,0,100,30) : QRect(0,0,640,480);
 #endif
     focus_next = focus_prev = q;
     if ((f & Qt::WindowType_Mask) == Qt::Desktop)
         q->create();
     else if (parentWidget)
         q->setParent(parentWidget, data.window_flags);
     else {
         adjustFlags(data.window_flags, q);
         resolveLayoutDirection();
         // opaque system background?
         const QBrush &background = q->palette().brush(QPalette::Window);
         setOpaque(q->isWindow() && background.style() != Qt::NoBrush && background.isOpaque());
     }
     data.fnt = QFont(data.fnt, q);
 #if defined(Q_WS_X11)
     data.fnt.x11SetScreen(xinfo.screen());
 #endif // Q_WS_X11
     q->setAttribute(Qt::WA_PendingMoveEvent);
     q->setAttribute(Qt::WA_PendingResizeEvent);
     if (++QWidgetPrivate::instanceCounter > QWidgetPrivate::maxInstances)
         QWidgetPrivate::maxInstances = QWidgetPrivate::instanceCounter;
     if (QApplicationPrivate::app_compile_version < 0x040200
         || QApplicationPrivate::testAttribute(Qt::AA_ImmediateWidgetCreation))
         q->create();
     QEvent e(QEvent::Create);
     QApplication::sendEvent(q, &e);
     QApplication::postEvent(q, new QEvent(QEvent::PolishRequest));
     extraPaintEngine = 0;
 }
inputContext()
QInputContext * QWidgetPrivate::inputContext () const
Definition at line 457 of file qwidget.cpp.
Referenced by QWidget::resetInputContext().
 {
     if (QInputContext *qic = assignedInputContext())
         return qic;
     return qApp->inputContext();
 }
invalidateBuffer() [1/2]
void QWidgetPrivate::invalidateBuffer (const QRegion & rgn)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
all widgets intersecting with the region will be repainted when the backing store is synced.
Qt 4.6: Merge into a template function (after MSVC isn't supported anymore).
Definition at line 1565 of file qbackingstore.cpp.
Referenced by effectiveState(), hide_sys(), isServerProcess(), lower_sys(), moveRect(), qt_grab_cursor(), qt_tablet_cleanup_wce(), QRuntimeGraphicsSystem::setGraphicsSystem(), setParent_sys(), show_sys(), and stackUnder_sys().
 {
     Q_Q(QWidget);
     QTLWExtra *tlwExtra = q->window()->d_func()->maybeTopData();
     if (discardInvalidateBufferRequest(q, tlwExtra) || rgn.isEmpty())
         return;
     QRegion wrgn(rgn);
     wrgn &= clipRect();
     if (!graphicsEffect && extra && extra->hasMask)
         wrgn &= extra->mask;
     if (wrgn.isEmpty())
         return;
     tlwExtra->backingStore->markDirty(wrgn, q, false, true);
 }
invalidateBuffer() [2/2]
void QWidgetPrivate::invalidateBuffer (const QRect & rect)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
Qt 4.6: Merge into a template function (after MSVC isn't supported anymore).
Definition at line 1590 of file qbackingstore.cpp.
 {
     Q_Q(QWidget);
     QTLWExtra *tlwExtra = q->window()->d_func()->maybeTopData();
     if (discardInvalidateBufferRequest(q, tlwExtra) || rect.isEmpty())
         return;
     QRect wRect(rect);
     wRect &= clipRect();
     if (wRect.isEmpty())
         return;
     if (graphicsEffect || !extra || !extra->hasMask) {
         tlwExtra->backingStore->markDirty(wRect, q, false, true);
         return;
     }
     QRegion wRgn(extra->mask);
     wRgn &= wRect;
     if (wRgn.isEmpty())
         return;
     tlwExtra->backingStore->markDirty(wRgn, q, false, true);
 }
invalidateBuffer_resizeHelper()
void QWidgetPrivate::invalidateBuffer_resizeHelper (const QPoint & oldPos, const QSize & oldSize)
Invalidates the buffer when the widget is resized.
Static areas are never invalidated unless absolutely needed.
Definition at line 1470 of file qbackingstore.cpp.
Referenced by effectiveState(), qt_grab_cursor(), and setGeometry_sys().
 {
     Q_Q(QWidget);
     Q_ASSERT(!q->isWindow());
     Q_ASSERT(q->parentWidget());
     const bool staticContents = q->testAttribute(Qt::WA_StaticContents);
     const bool sizeDecreased = (data.crect.width() < oldSize.width())
                                || (data.crect.height() < oldSize.height());
     const QPoint offset(data.crect.x() - oldPos.x(), data.crect.y() - oldPos.y());
     const bool parentAreaExposed = !offset.isNull() || sizeDecreased;
     const QRect newWidgetRect(q->rect());
     const QRect oldWidgetRect(0, 0, oldSize.width(), oldSize.height());
     if (!staticContents || graphicsEffect) {
         QRegion staticChildren;
         QWidgetBackingStore *bs = 0;
         if (offset.isNull() && (bs = maybeBackingStore()))
             staticChildren = bs->staticContents(q, oldWidgetRect);
         const bool hasStaticChildren = !staticChildren.isEmpty();
         if (hasStaticChildren) {
             QRegion dirty(newWidgetRect);
             dirty -= staticChildren;
             invalidateBuffer(dirty);
         } else {
             // Entire widget needs repaint.
             invalidateBuffer(newWidgetRect);
         }
         if (!parentAreaExposed)
             return;
         // Invalidate newly exposed area of the parent.
         if (!graphicsEffect && extra && extra->hasMask) {
             QRegion parentExpose(extra->mask.translated(oldPos));
             parentExpose &= QRect(oldPos, oldSize);
             if (hasStaticChildren)
                 parentExpose -= data.crect; // Offset is unchanged, safe to do this.
             q->parentWidget()->d_func()->invalidateBuffer(parentExpose);
         } else {
             if (hasStaticChildren && !graphicsEffect) {
                 QRegion parentExpose(QRect(oldPos, oldSize));
                 parentExpose -= data.crect; // Offset is unchanged, safe to do this.
                 q->parentWidget()->d_func()->invalidateBuffer(parentExpose);
             } else {
                 q->parentWidget()->d_func()->invalidateBuffer(effectiveRectFor(QRect(oldPos, oldSize)));
             }
         }
         return;
     }
     // Move static content to its new position.
     if (!offset.isNull()) {
         if (sizeDecreased) {
             const QSize minSize(qMin(oldSize.width(), data.crect.width()),
                                 qMin(oldSize.height(), data.crect.height()));
             moveRect(QRect(oldPos, minSize), offset.x(), offset.y());
         } else {
             moveRect(QRect(oldPos, oldSize), offset.x(), offset.y());
         }
     }
     // Invalidate newly visible area of the widget.
     if (!sizeDecreased || !oldWidgetRect.contains(newWidgetRect)) {
         QRegion newVisible(newWidgetRect);
         newVisible -= oldWidgetRect;
         invalidateBuffer(newVisible);
     }
     if (!parentAreaExposed)
         return;
     // Invalidate newly exposed area of the parent.
     const QRect oldRect(oldPos, oldSize);
     if (extra && extra->hasMask) {
         QRegion parentExpose(oldRect);
         parentExpose &= extra->mask.translated(oldPos);
         parentExpose -= (extra->mask.translated(data.crect.topLeft()) & data.crect);
         q->parentWidget()->d_func()->invalidateBuffer(parentExpose);
     } else {
         QRegion parentExpose(oldRect);
         parentExpose -= data.crect;
         q->parentWidget()->d_func()->invalidateBuffer(parentExpose);
     }
 }
invalidateGraphicsEffectsRecursively()
void QWidgetPrivate::invalidateGraphicsEffectsRecursively ()
Definition at line 2059 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     QWidget *w = q;
     do {
         if (w->graphicsEffect()) {
             QWidgetEffectSourcePrivate *sourced =
                 static_cast<QWidgetEffectSourcePrivate *>(w->graphicsEffect()->source()->d_func());
             if (!sourced->updateDueToGraphicsEffect)
                 w->graphicsEffect()->source()->d_func()->invalidateCache();
         }
         w = w->parentWidget();
     } while (w);
 }
isAboutToShow()
bool QWidgetPrivate::isAboutToShow () const
Definition at line 5542 of file qwidget.cpp.
 {
     if (data.in_show)
         return true;
     Q_Q(const QWidget);
     if (q->isHidden())
         return false;
     // The widget will be shown if any of its ancestors are about to show.
     QWidget *parent = q->parentWidget();
     return parent ? parent->d_func()->isAboutToShow() : false;
 }
isBackgroundInherited()
bool QWidgetPrivate::isBackgroundInherited () const
Definition at line 1022 of file qwidget_x11.cpp.
 {
     Q_Q(const QWidget);
     // windows do not inherit their background
     if (q->isWindow() || q->windowType() == Qt::SubWindow)
         return false;
     if (q->testAttribute(Qt::WA_NoSystemBackground) || q->testAttribute(Qt::WA_OpaquePaintEvent))
         return false;
     const QPalette &pal = q->palette();
     QPalette::ColorRole bg = q->backgroundRole();
     QBrush brush = pal.brush(bg);
     // non opaque brushes leaves us no choice, we must inherit
     if (!q->autoFillBackground() || !brush.isOpaque())
         return true;
     if (brush.style() == Qt::SolidPattern) {
         // the background is just a solid color. If there is no
         // propagated contents, then we claim as performance
         // optimization that it was not inheritet. This is the normal
         // case in standard Windows or Motif style.
         const QWidget *w = q->parentWidget();
         if (!w->d_func()->isBackgroundInherited())
             return false;
     }
     return true;
 }
isOverlapped()
bool QWidgetPrivate::isOverlapped (const QRect & rect) const
Definition at line 1877 of file qwidget.cpp.
Referenced by scroll_sys().
 {
     Q_Q(const QWidget);
     const QWidget *w = q;
     QRect r = rect;
     while (w) {
         if (w->isWindow())
             return false;
         QWidgetPrivate *pd = w->parentWidget()->d_func();
         bool above = false;
         for (int i = 0; i < pd->children.size(); ++i) {
             QWidget *sibling = qobject_cast<QWidget *>(pd->children.at(i));
             if (!sibling || !sibling->isVisible() || sibling->isWindow())
                 continue;
             if (!above) {
                 above = (sibling == w);
                 continue;
             }
             if (qRectIntersects(sibling->d_func()->effectiveRectFor(sibling->data->crect), r)) {
                 const QWExtra *siblingExtra = sibling->d_func()->extra;
                 if (siblingExtra && siblingExtra->hasMask && !sibling->d_func()->graphicsEffect
                     && !siblingExtra->mask.translated(sibling->data->crect.topLeft()).intersects(r)) {
                     continue;
                 }
                 return true;
             }
         }
         w = w->parentWidget();
         r.translate(pd->data.crect.topLeft());
     }
     return false;
 }
lower_sys()
void QWidgetPrivate::lower_sys ()
Definition at line 4015 of file qwidget_mac.mm.
Referenced by effectiveState(), qt_grab_cursor(), and setNetWmWindowTypes().
 {
     Q_Q(QWidget);
     if((q->windowType() == Qt::Desktop))
         return;
 #ifdef QT_MAC_USE_COCOA
     if (isRealWindow()) {
         OSWindowRef window = qt_mac_window_for(q);
         [window orderBack:window];
     } else {
         NSView *view = qt_mac_nativeview_for(q);
         NSView *parentView = [view superview];
         [parentView sortSubviewsUsingFunction:compareViews2Lower context:reinterpret_cast<void *>(view)];
     }
     topLevelAt_cache = 0;
 #else
     if(q->isWindow()) {
         SendBehind(qt_mac_window_for(q), 0);
     } else if(q->parentWidget()) {
         invalidateBuffer(q->rect());
         HIViewSetZOrder(qt_mac_nativeview_for(q), kHIViewZOrderBelow, 0);
         qt_event_request_window_change(q);
     }
 #endif
 }
mapFromGlobal()
QPoint QWidgetPrivate::mapFromGlobal (const QPoint & pos) const
Definition at line 1330 of file qwidget_x11.cpp.
 {
     Q_Q(const QWidget);
     if (!q->testAttribute(Qt::WA_WState_Created) || !q->internalWinId()) {
         //cannot trust that !isWindow() implies parentWidget() before create
         QPoint p = (q->isWindow() || !q->parentWidget()) ?  pos : q->parentWidget()->d_func()->mapFromGlobal(pos);
         return p - q->data->crect.topLeft();
     }
     int x, y;
     Window child;
     XTranslateCoordinates(X11->display,
                           QApplication::desktop()->screen(xinfo.screen())->internalWinId(),
                           q->internalWinId(), pos.x(), pos.y(), &x, &y, &child);
     return mapFromWS(QPoint(x, y));
 }
mapToGlobal()
QPoint QWidgetPrivate::mapToGlobal (const QPoint & pos) const
Definition at line 1313 of file qwidget_x11.cpp.
Referenced by isServerProcess().
 {
     Q_Q(const QWidget);
     if (!q->testAttribute(Qt::WA_WState_Created) || !q->internalWinId()) {
         QPoint p = pos + q->data->crect.topLeft();
         //cannot trust that !isWindow() implies parentWidget() before create
         return (q->isWindow() || !q->parentWidget()) ?  p : q->parentWidget()->d_func()->mapToGlobal(p);
     }
     int x, y;
     Window child;
     QPoint p = mapToWS(pos);
     XTranslateCoordinates(X11->display, q->internalWinId(),
                           QApplication::desktop()->screen(xinfo.screen())->internalWinId(),
                           p.x(), p.y(), &x, &y, &child);
     return QPoint(x, y);
 }
maybeBackingStore()
QWidgetBackingStore * QWidgetPrivate::maybeBackingStore () const inline
Definition at line 1036 of file qwidget_p.h.
Referenced by effectiveState(), qt_dirtyRegion(), and qt_grab_cursor().
 {
     Q_Q(const QWidget);
     QTLWExtra *x = q->window()->d_func()->maybeTopData();
     return x ? x->backingStore.data() : 0;
 }
maybeTopData()
QTLWExtra * QWidgetPrivate::maybeTopData () const inline
Definition at line 1010 of file qwidget_p.h.
Referenced by effectiveState(), q_createNativeChildrenAndSetParent(), qt_tablet_cleanup_wce(), and setParent_sys().
 {
     return extra ? extra->topextra : 0;
 }
moveRect()
void QWidgetPrivate::moveRect (const QRect & rect, int dx, int dy)
Definition at line 917 of file qbackingstore.cpp.
Referenced by effectiveState(), qt_grab_cursor(), and setGeometry_sys().
 {
     Q_Q(QWidget);
     if (!q->isVisible() || (dx == 0 && dy == 0))
         return;
     QWidget *tlw = q->window();
     QTLWExtra* x = tlw->d_func()->topData();
     if (x->inTopLevelResize)
         return;
     static int accelEnv = -1;
     if (accelEnv == -1) {
         accelEnv = qgetenv("QT_NO_FAST_MOVE").toInt() == 0;
     }
     QWidget *pw = q->parentWidget();
     QPoint toplevelOffset = pw->mapTo(tlw, QPoint());
     QWidgetPrivate *pd = pw->d_func();
     QRect clipR(pd->clipRect());
 #ifdef Q_WS_QWS
     QWidgetBackingStore *wbs = x->backingStore.data();
     QWSWindowSurface *surface = static_cast<QWSWindowSurface*>(wbs->windowSurface);
     clipR = clipR.intersected(surface->clipRegion().translated(-toplevelOffset).boundingRect());
 #endif
     const QRect newRect(rect.translated(dx, dy));
     QRect destRect = rect.intersected(clipR);
     if (destRect.isValid())
         destRect = destRect.translated(dx, dy).intersected(clipR);
     const QRect sourceRect(destRect.translated(-dx, -dy));
     const QRect parentRect(rect & clipR);
     bool accelerateMove = accelEnv && isOpaque
 #ifndef QT_NO_GRAPHICSVIEW
                           // No accelerate move for proxy widgets.
                           && !tlw->d_func()->extra->proxyWidget
 #endif
                           && !isOverlapped(sourceRect) && !isOverlapped(destRect);
     if (!accelerateMove) {
         QRegion parentR(effectiveRectFor(parentRect));
         if (!extra || !extra->hasMask) {
             parentR -= newRect;
         } else {
             // invalidateBuffer() excludes anything outside the mask
             parentR += newRect & clipR;
         }
         pd->invalidateBuffer(parentR);
         invalidateBuffer((newRect & clipR).translated(-data.crect.topLeft()));
     } else {
         QWidgetBackingStore *wbs = x->backingStore.data();
         QRegion childExpose(newRect & clipR);
         if (sourceRect.isValid() && wbs->bltRect(sourceRect, dx, dy, pw))
             childExpose -= destRect;
         if (!pw->updatesEnabled())
             return;
         const bool childUpdatesEnabled = q->updatesEnabled();
         if (childUpdatesEnabled && !childExpose.isEmpty()) {
             childExpose.translate(-data.crect.topLeft());
             wbs->markDirty(childExpose, q);
             isMoved = true;
         }
         QRegion parentExpose(parentRect);
         parentExpose -= newRect;
         if (extra && extra->hasMask)
             parentExpose += QRegion(newRect) - extra->mask.translated(data.crect.topLeft());
         if (!parentExpose.isEmpty()) {
             wbs->markDirty(parentExpose, pw);
             pd->isMoved = true;
         }
         if (childUpdatesEnabled) {
             QRegion needsFlush(sourceRect);
             needsFlush += destRect;
             wbs->markDirtyOnScreen(needsFlush, pw, toplevelOffset);
         }
     }
 }
nativeChildrenForced()
bool QWidgetPrivate::nativeChildrenForced () const inline
Definition at line 653 of file qwidget_p.h.
     {
         return extra ? extra->nativeChildrenForced : false;
     }
naturalWidgetFont()
QFont QWidgetPrivate::naturalWidgetFont (uint inheritedMask) const
Definition at line 5030 of file qwidget.cpp.
 {
     Q_Q(const QWidget);
     QFont naturalFont = QApplication::font(q);
     if (!q->testAttribute(Qt::WA_StyleSheet)
         && (!q->isWindow() || q->testAttribute(Qt::WA_WindowPropagation)
 #ifndef QT_NO_GRAPHICSVIEW
             || (extra && extra->proxyWidget)
 #endif //QT_NO_GRAPHICSVIEW
             )) {
         if (QWidget *p = q->parentWidget()) {
             if (!p->testAttribute(Qt::WA_StyleSheet)) {
                 if (!naturalFont.isCopyOf(QApplication::font())) {
                     QFont inheritedFont = p->font();
                     inheritedFont.resolve(inheritedMask);
                     naturalFont = inheritedFont.resolve(naturalFont);
                 } else {
                     naturalFont = p->font();
                 }
             }
         }
 #ifndef QT_NO_GRAPHICSVIEW
         else if (extra && extra->proxyWidget) {
             QFont inheritedFont = extra->proxyWidget->font();
             inheritedFont.resolve(inheritedMask);
             naturalFont = inheritedFont.resolve(naturalFont);
         }
 #endif //QT_NO_GRAPHICSVIEW
     }
     naturalFont.resolve(0);
     return naturalFont;
 }
naturalWidgetPalette()
QPalette QWidgetPrivate::naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
Warning
This function is not part of the public interface.
inheritedMask is the combination of the widget's ancestors palette request masks (i.e., which attributes from the parent widget's palette are implicitly imposed on this widget by the user). Note that this font does not take into account the palette set on w itself.
Definition at line 4884 of file qwidget.cpp.
 {
     Q_Q(const QWidget);
     QPalette naturalPalette = QApplication::palette(q);
     if (!q->testAttribute(Qt::WA_StyleSheet)
         && (!q->isWindow() || q->testAttribute(Qt::WA_WindowPropagation)
 #ifndef QT_NO_GRAPHICSVIEW
             || (extra && extra->proxyWidget)
 #endif //QT_NO_GRAPHICSVIEW
             )) {
         if (QWidget *p = q->parentWidget()) {
             if (!p->testAttribute(Qt::WA_StyleSheet)) {
                 if (!naturalPalette.isCopyOf(QApplication::palette())) {
                     QPalette inheritedPalette = p->palette();
                     inheritedPalette.resolve(inheritedMask);
                     naturalPalette = inheritedPalette.resolve(naturalPalette);
                 } else {
                     naturalPalette = p->palette();
                 }
             }
         }
 #ifndef QT_NO_GRAPHICSVIEW
         else if (extra && extra->proxyWidget) {
             QPalette inheritedPalette = extra->proxyWidget->palette();
             inheritedPalette.resolve(inheritedMask);
             naturalPalette = inheritedPalette.resolve(naturalPalette);
         }
 #endif //QT_NO_GRAPHICSVIEW
     }
     naturalPalette.resolve(0);
     return naturalPalette;
 }
nearestGraphicsProxyWidget()
QGraphicsProxyWidget * QWidgetPrivate::nearestGraphicsProxyWidget (const QWidget * origin) static
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
Warning
This function is not part of the public interface.
The search starts at origin (inclusive). If successful, the function returns the proxy that embeds the widget, or 0 if no embedded widget was found.
Definition at line 6098 of file qwidget.cpp.
Referenced by QApplicationPrivate::dispatchEnterLeave(), QWidget::scroll(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     if (origin) {
         QWExtra *extra = origin->d_func()->extra;
         if (extra && extra->proxyWidget)
             return extra->proxyWidget;
         return nearestGraphicsProxyWidget(origin->parentWidget());
     }
     return 0;
 }
paintBackground()
void QWidgetPrivate::paintBackground (QPainter * painter, const QRegion & rgn, int flags = DrawAsRoot) const
Definition at line 2429 of file qwidget.cpp.
 {
     Q_Q(const QWidget);
 #ifndef QT_NO_SCROLLAREA
     bool resetBrushOrigin = false;
     QPointF oldBrushOrigin;
     //If we are painting the viewport of a scrollarea, we must apply an offset to the brush in case we are drawing a texture
     QAbstractScrollArea *scrollArea = qobject_cast<QAbstractScrollArea *>(parent);
     if (scrollArea && scrollArea->viewport() == q) {
         QObjectData *scrollPrivate = static_cast<QWidget *>(scrollArea)->d_ptr.data();
         QAbstractScrollAreaPrivate *priv = static_cast<QAbstractScrollAreaPrivate *>(scrollPrivate);
         oldBrushOrigin = painter->brushOrigin();
         resetBrushOrigin = true;
         painter->setBrushOrigin(-priv->contentsOffset());
     }
 #endif // QT_NO_SCROLLAREA
     const QBrush autoFillBrush = q->palette().brush(q->backgroundRole());
     if ((flags & DrawAsRoot) && !(q->autoFillBackground() && autoFillBrush.isOpaque())) {
         const QBrush bg = q->palette().brush(QPalette::Window);
 #if defined(Q_WS_QWS) || defined(Q_WS_QPA)
         if (!(flags & DontSetCompositionMode)) {
             //copy alpha straight in
             QPainter::CompositionMode oldMode = painter->compositionMode();
             painter->setCompositionMode(QPainter::CompositionMode_Source);
             fillRegion(painter, rgn, bg);
             painter->setCompositionMode(oldMode);
         } else {
             fillRegion(painter, rgn, bg);
         }
 #else
         fillRegion(painter, rgn, bg);
 #endif
     }
     if (q->autoFillBackground())
         fillRegion(painter, rgn, autoFillBrush);
     if (q->testAttribute(Qt::WA_StyledBackground)) {
         painter->setClipRegion(rgn);
         QStyleOption opt;
         opt.initFrom(q);
         q->style()->drawPrimitive(QStyle::PE_Widget, &opt, painter, q);
     }
 #ifndef QT_NO_SCROLLAREA
     if (resetBrushOrigin)
         painter->setBrushOrigin(oldBrushOrigin);
 #endif // QT_NO_SCROLLAREA
 }
paintOnScreen()
bool QWidgetPrivate::paintOnScreen () const
Definition at line 2255 of file qwidget.cpp.
Referenced by QGraphicsViewPrivate::dispatchPendingUpdateRequests(), qt_grab_cursor(), qt_tablet_cleanup_wce(), and scroll_sys().
 {
 #if defined(Q_WS_QWS)
     return false;
 #elif  defined(QT_NO_BACKINGSTORE)
     return true;
 #else
     Q_Q(const QWidget);
     if (q->testAttribute(Qt::WA_PaintOnScreen)
             || (!q->isWindow() && q->window()->testAttribute(Qt::WA_PaintOnScreen))) {
         return true;
     }
     return !qt_enable_backingstore;
 #endif
 }
paintSiblingsRecursive()
void QWidgetPrivate::paintSiblingsRecursive (QPaintDevice * pdev, const QObjectList & children, int index, const QRegion & rgn, const QPoint & offset, int flags, QPainter * sharedPainter, QWidgetBackingStore * backingStore)
Definition at line 5946 of file qwidget.cpp.
 {
     QWidget *w = 0;
     QRect boundingRect;
     bool dirtyBoundingRect = true;
     const bool exludeOpaqueChildren = (flags & DontDrawOpaqueChildren);
     const bool excludeNativeChildren = (flags & DontDrawNativeChildren);
     do {
         QWidget *x =  qobject_cast<QWidget*>(siblings.at(index));
         if (x && !(exludeOpaqueChildren && x->d_func()->isOpaque) && !x->isHidden() && !x->isWindow()
             && !(excludeNativeChildren && x->internalWinId())) {
             if (dirtyBoundingRect) {
                 boundingRect = rgn.boundingRect();
                 dirtyBoundingRect = false;
             }
             if (qRectIntersects(boundingRect, x->d_func()->effectiveRectFor(x->data->crect))) {
 #ifdef Q_BACKINGSTORE_SUBSURFACES
                 if (x->windowSurface() == currentSurface)
 #endif
                 {
                     w = x;
                     break;
                 }
             }
         }
         --index;
     } while (index >= 0);
     if (!w)
         return;
     QWidgetPrivate *wd = w->d_func();
     const QPoint widgetPos(w->data->crect.topLeft());
     const bool hasMask = wd->extra && wd->extra->hasMask && !wd->graphicsEffect;
     if (index > 0) {
         QRegion wr(rgn);
         if (wd->isOpaque)
             wr -= hasMask ? wd->extra->mask.translated(widgetPos) : w->data->crect;
         paintSiblingsRecursive(pdev, siblings, --index, wr, offset, flags
 #ifdef Q_BACKINGSTORE_SUBSURFACES
                                , currentSurface
 #endif
                                , sharedPainter, backingStore);
     }
     if (w->updatesEnabled()
 #ifndef QT_NO_GRAPHICSVIEW
             && (!w->d_func()->extra || !w->d_func()->extra->proxyWidget)
 #endif //QT_NO_GRAPHICSVIEW
        ) {
         QRegion wRegion(rgn);
         wRegion &= wd->effectiveRectFor(w->data->crect);
         wRegion.translate(-widgetPos);
         if (hasMask)
             wRegion &= wd->extra->mask;
         wd->drawWidget(pdev, wRegion, offset + widgetPos, flags, sharedPainter, backingStore);
     }
 }
pointInsideRectAndMask()
bool QWidgetPrivate::pointInsideRectAndMask (const QPoint & p) const inline
Definition at line 1029 of file qwidget_p.h.
 {
     Q_Q(const QWidget);
     return q->rect().contains(p) && (!extra || !extra->hasMask || q->testAttribute(Qt::WA_MouseNoMask)
                                      || extra->mask.contains(p));
 }
pointToRect()
int QWidgetPrivate::pointToRect (const QPoint & p, const QRect & r) static
Warning
This function is not part of the public interface.
Measures the shortest distance from a point to a rect.
This function is called from QDesktopwidget::screen(QPoint) to find the closest screen for a point. In directional KeypadNavigation, it is called to find the closest widget to the current focus widget center.
Definition at line 7128 of file qwidget.cpp.
Referenced by QDesktopWidget::screenNumber().
 {
     int dx = 0;
     int dy = 0;
     if (p.x() < r.left())
         dx = r.left() - p.x();
     else if (p.x() > r.right())
         dx = p.x() - r.right();
     if (p.y() < r.top())
         dy = r.top() - p.y();
     else if (p.y() > r.bottom())
         dy = p.y() - r.bottom();
     return dx + dy;
 }
prepareToRender()
QRegion QWidgetPrivate::prepareToRender (const QRegion & region, QWidget::RenderFlags renderFlags)
Definition at line 5556 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     const bool isVisible = q->isVisible();
     // Make sure the widget is laid out correctly.
     if (!isVisible && !isAboutToShow()) {
         QWidget *topLevel = q->window();
         (void)topLevel->d_func()->topData(); // Make sure we at least have top-data.
         topLevel->ensurePolished();
         // Invalidate the layout of hidden ancestors (incl. myself) and pretend
         // they're not explicitly hidden.
         QWidget *widget = q;
         QWidgetList hiddenWidgets;
         while (widget) {
             if (widget->isHidden()) {
                 widget->setAttribute(Qt::WA_WState_Hidden, false);
                 hiddenWidgets.append(widget);
                 if (!widget->isWindow() && widget->parentWidget()->d_func()->layout)
                     widget->d_func()->updateGeometry_helper(true);
             }
             widget = widget->parentWidget();
         }
         // Activate top-level layout.
         if (topLevel->d_func()->layout)
             topLevel->d_func()->layout->activate();
         // Adjust size if necessary.
         QTLWExtra *topLevelExtra = topLevel->d_func()->maybeTopData();
         if (topLevelExtra && !topLevelExtra->sizeAdjusted
             && !topLevel->testAttribute(Qt::WA_Resized)) {
             topLevel->adjustSize();
             topLevel->setAttribute(Qt::WA_Resized, false);
         }
         // Activate child layouts.
         topLevel->d_func()->activateChildLayoutsRecursively();
         // We're not cheating with WA_WState_Hidden anymore.
         for (int i = 0; i < hiddenWidgets.size(); ++i) {
             QWidget *widget = hiddenWidgets.at(i);
             widget->setAttribute(Qt::WA_WState_Hidden);
             if (!widget->isWindow() && widget->parentWidget()->d_func()->layout)
                 widget->parentWidget()->d_func()->layout->invalidate();
         }
     } else if (isVisible) {
         q->window()->d_func()->sendPendingMoveAndResizeEvents(true, true);
     }
     // Calculate the region to be painted.
     QRegion toBePainted = !region.isEmpty() ? region : QRegion(q->rect());
     if (!(renderFlags & QWidget::IgnoreMask) && extra && extra->hasMask)
         toBePainted &= extra->mask;
     return toBePainted;
 }
propagatePaletteChange()
void QWidgetPrivate::propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
Warning
This function is not part of the public interface.
Definition at line 1963 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     // Propagate a new inherited mask to all children.
 #ifndef QT_NO_GRAPHICSVIEW
     if (!q->parentWidget() && extra && extra->proxyWidget) {
         QGraphicsProxyWidget *p = extra->proxyWidget;
         inheritedPaletteResolveMask = p->d_func()->inheritedPaletteResolveMask | p->palette().resolve();
     } else
 #endif //QT_NO_GRAPHICSVIEW
         if (q->isWindow() && !q->testAttribute(Qt::WA_WindowPropagation)) {
         inheritedPaletteResolveMask = 0;
     }
     int mask = data.pal.resolve() | inheritedPaletteResolveMask;
     QEvent pc(QEvent::PaletteChange);
     QApplication::sendEvent(q, &pc);
     for (int i = 0; i < children.size(); ++i) {
         QWidget *w = qobject_cast<QWidget*>(children.at(i));
         if (w && !w->testAttribute(Qt::WA_StyleSheet)
             && (!w->isWindow() || w->testAttribute(Qt::WA_WindowPropagation))) {
             QWidgetPrivate *wd = w->d_func();
             wd->inheritedPaletteResolveMask = mask;
             wd->resolvePalette();
         }
     }
 #if defined(QT3_SUPPORT)
     q->paletteChange(q->palette()); // compatibility
 #endif
 }
raise_sys()
void QWidgetPrivate::raise_sys ()
Definition at line 3937 of file qwidget_mac.mm.
Referenced by effectiveState(), qt_grab_cursor(), and setNetWmWindowTypes().
 {
     Q_Q(QWidget);
     if((q->windowType() == Qt::Desktop))
         return;
 #if QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     if (isRealWindow()) {
         // With the introduction of spaces it is not as simple as just raising the window.
         // First we need to check if we are in the right space. If we are, then we just continue
         // as usual. The problem comes when we are not in the active space. There are two main cases:
         // 1. Our parent was moved to a new space. In this case we want the window to be raised
         // in the same space as its parent.
         // 2. We don't have a parent. For this case we will just raise the window and let Cocoa
         // switch to the corresponding space.
         // NOTICE: There are a lot of corner cases here. We are keeping this simple for now, if
         // required we will introduce special handling for some of them.
         if (!q->testAttribute(Qt::WA_DontShowOnScreen) && q->isVisible()) {
             OSWindowRef window = qt_mac_window_for(q);
             // isOnActiveSpace is available only from 10.6 onwards, so we need to check if it is
             // available before calling it.
             if([window respondsToSelector:@selector(isOnActiveSpace)]) {
                 if(![window performSelector:@selector(isOnActiveSpace)]) {
                     QWidget *parentWidget = q->parentWidget();
                     if(parentWidget) {
                         OSWindowRef parentWindow = qt_mac_window_for(parentWidget);
                         if(parentWindow && [parentWindow respondsToSelector:@selector(isOnActiveSpace)]) {
                             if ([parentWindow performSelector:@selector(isOnActiveSpace)]) {
                                 // The window was created in a different space. Therefore if we want
                                 // to show it in the current space we need to recreate it in the new
                                 // space.
                                 recreateMacWindow();
                                 window = qt_mac_window_for(q);
                             }
                         }
                     }
                 }
             }
             [window orderFront:window];
         }
         if (qt_mac_raise_process) { //we get to be the active process now
             ProcessSerialNumber psn;
             GetCurrentProcess(&psn);
             SetFrontProcessWithOptions(&psn, kSetFrontProcessFrontWindowOnly);
         }
     } else {
         NSView *view = qt_mac_nativeview_for(q);
         NSView *parentView = [view superview];
         [parentView sortSubviewsUsingFunction:compareViews2Raise context:reinterpret_cast<void *>(view)];
     }
     topLevelAt_cache = 0;
 #else
     if(q->isWindow()) {
         //raise this window
         BringToFront(qt_mac_window_for(q));
         if(qt_mac_raise_process) { //we get to be the active process now
             ProcessSerialNumber psn;
             GetCurrentProcess(&psn);
             SetFrontProcessWithOptions(&psn, kSetFrontProcessFrontWindowOnly);
         }
     } else if(q->parentWidget()) {
         HIViewSetZOrder(qt_mac_nativeview_for(q), kHIViewZOrderAbove, 0);
         qt_event_request_window_change(q);
     }
 #endif
 }
redirected()
QPaintDevice* QWidgetPrivate::redirected (QPoint * offset) const inline
Definition at line 628 of file qwidget_p.h.
Referenced by QPainter::redirected().
     {
         if (offset)
             *offset = redirectDev ? redirectOffset : QPoint();
         return redirectDev;
     }
registerDropSite()
void QWidgetPrivate::registerDropSite (bool on)
Definition at line 5025 of file qwidget_mac.mm.
Referenced by create_sys(), do_size_hints(), effectiveState(), qt_grab_cursor(), qt_mac_unregister_widget(), and qt_tablet_cleanup_wce().
 {
     Q_Q(QWidget);
     if (!q->testAttribute(Qt::WA_WState_Created))
         return;
 #ifndef QT_MAC_USE_COCOA
     SetControlDragTrackingEnabled(qt_mac_nativeview_for(q), on);
 #else
     NSWindow *win = qt_mac_window_for(q);
     if (on) {
         if ([win isKindOfClass:[QT_MANGLE_NAMESPACE(QCocoaWindow) class]])
             [static_cast<QT_MANGLE_NAMESPACE(QCocoaWindow) *>(win) registerDragTypes];
         else if ([win isKindOfClass:[QT_MANGLE_NAMESPACE(QCocoaPanel) class]])
             [static_cast<QT_MANGLE_NAMESPACE(QCocoaPanel) *>(win) registerDragTypes];
     }
 #endif
 }
render()
void QWidgetPrivate::render (QPaintDevice * target, const QPoint & targetOffset, const QRegion & sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
Definition at line 5856 of file qwidget.cpp.
 {
     if (!target) {
         qWarning("QWidget::render: null pointer to paint device");
         return;
     }
     const bool inRenderWithPainter = extra && extra->inRenderWithPainter;
     QRegion paintRegion = !inRenderWithPainter && !readyToRender
                           ? prepareToRender(sourceRegion, renderFlags)
                           : sourceRegion;
     if (paintRegion.isEmpty())
         return;
 #ifndef Q_WS_MAC
     QPainter *oldSharedPainter = inRenderWithPainter ? sharedPainter() : 0;
     // Use the target's shared painter if set (typically set when doing
     // "other->render(widget);" in the widget's paintEvent.
     if (target->devType() == QInternal::Widget) {
         QWidgetPrivate *targetPrivate = static_cast<QWidget *>(target)->d_func();
         if (targetPrivate->extra && targetPrivate->extra->inRenderWithPainter) {
             QPainter *targetPainter = targetPrivate->sharedPainter();
             if (targetPainter && targetPainter->isActive())
                 setSharedPainter(targetPainter);
         }
     }
 #endif
     // Use the target's redirected device if set and adjust offset and paint
     // region accordingly. This is typically the case when people call render
     // from the paintEvent.
     QPoint offset = targetOffset;
     offset -= paintRegion.boundingRect().topLeft();
     QPoint redirectionOffset;
     QPaintDevice *redirected = 0;
     if (target->devType() == QInternal::Widget)
         redirected = static_cast<QWidget *>(target)->d_func()->redirected(&redirectionOffset);
     if (!redirected)
         redirected = QPainter::redirected(target, &redirectionOffset);
     if (redirected) {
         target = redirected;
         offset -= redirectionOffset;
     }
     if (!inRenderWithPainter) { // Clip handled by shared painter (in qpainter.cpp).
         if (QPaintEngine *targetEngine = target->paintEngine()) {
             const QRegion targetSystemClip = targetEngine->systemClip();
             if (!targetSystemClip.isEmpty())
                 paintRegion &= targetSystemClip.translated(-offset);
         }
     }
     // Set backingstore flags.
     int flags = DrawPaintOnScreen | DrawInvisible;
     if (renderFlags & QWidget::DrawWindowBackground)
         flags |= DrawAsRoot;
     if (renderFlags & QWidget::DrawChildren)
         flags |= DrawRecursive;
     else
         flags |= DontSubtractOpaqueChildren;
 #if defined(Q_WS_QWS) || defined(Q_WS_QPA)
     flags |= DontSetCompositionMode;
 #endif
     if (target->devType() == QInternal::Printer) {
         QPainter p(target);
         render_helper(&p, targetOffset, paintRegion, renderFlags);
         return;
     }
 #ifndef Q_WS_MAC
     // Render via backingstore.
     drawWidget(target, paintRegion, offset, flags, sharedPainter());
     // Restore shared painter.
     if (oldSharedPainter)
         setSharedPainter(oldSharedPainter);
 #else
     // Render via backingstore (no shared painter).
     drawWidget(target, paintRegion, offset, flags, 0);
 #endif
 }
render_helper()
void QWidgetPrivate::render_helper (QPainter * painter, const QPoint & targetOffset, const QRegion & sourceRegion, QWidget::RenderFlags renderFlags)
Definition at line 5614 of file qwidget.cpp.
 {
     Q_ASSERT(painter);
     Q_ASSERT(!toBePainted.isEmpty());
     Q_Q(QWidget);
 #ifndef Q_WS_MAC
     const QTransform originalTransform = painter->worldTransform();
     const bool useDeviceCoordinates = originalTransform.isScaling();
     if (!useDeviceCoordinates) {
 #endif
         // Render via a pixmap.
         const QRect rect = toBePainted.boundingRect();
         const QSize size = rect.size();
         if (size.isNull())
             return;
         QPixmap pixmap(size);
         if (!(renderFlags & QWidget::DrawWindowBackground) || !isOpaque)
             pixmap.fill(Qt::transparent);
         q->render(&pixmap, QPoint(), toBePainted, renderFlags);
         const bool restore = !(painter->renderHints() & QPainter::SmoothPixmapTransform);
         painter->setRenderHints(QPainter::SmoothPixmapTransform, true);
         painter->drawPixmap(targetOffset, pixmap);
         if (restore)
             painter->setRenderHints(QPainter::SmoothPixmapTransform, false);
 #ifndef Q_WS_MAC
     } else {
         // Render via a pixmap in device coordinates (to avoid pixmap scaling).
         QTransform transform = originalTransform;
         transform.translate(targetOffset.x(), targetOffset.y());
         QPaintDevice *device = painter->device();
         Q_ASSERT(device);
         // Calculate device rect.
         const QRectF rect(toBePainted.boundingRect());
         QRect deviceRect = transform.mapRect(QRectF(0, 0, rect.width(), rect.height())).toAlignedRect();
         deviceRect &= QRect(0, 0, device->width(), device->height());
         QPixmap pixmap(deviceRect.size());
         pixmap.fill(Qt::transparent);
         // Create a pixmap device coordinate painter.
         QPainter pixmapPainter(&pixmap);
         pixmapPainter.setRenderHints(painter->renderHints());
         transform *= QTransform::fromTranslate(-deviceRect.x(), -deviceRect.y());
         pixmapPainter.setTransform(transform);
         q->render(&pixmapPainter, QPoint(), toBePainted, renderFlags);
         pixmapPainter.end();
         // And then draw the pixmap.
         painter->setTransform(QTransform());
         painter->drawPixmap(deviceRect.topLeft(), pixmap);
         painter->setTransform(originalTransform);
     }
 #endif
 }
repaint_sys()
void QWidgetPrivate::repaint_sys (const QRegion & rgn)
Definition at line 1616 of file qbackingstore.cpp.
 {
     if (data.in_destructor)
         return;
     Q_Q(QWidget);
     if (q->testAttribute(Qt::WA_StaticContents)) {
         if (!extra)
             createExtra();
         extra->staticContentsSize = data.crect.size();
     }
 #ifdef Q_WS_QPA //Don't even call q->p
     QPaintEngine *engine = 0;
 #else
     QPaintEngine *engine = q->paintEngine();
 #endif
     // QGLWidget does not support partial updates if:
     // 1) The context is double buffered
     // 2) The context is single buffered and auto-fill background is enabled.
     const bool noPartialUpdateSupport = (engine && (engine->type() == QPaintEngine::OpenGL
                                                 || engine->type() == QPaintEngine::OpenGL2))
                                         && (usesDoubleBufferedGLContext || q->autoFillBackground());
     QRegion toBePainted(noPartialUpdateSupport ? q->rect() : rgn);
 #ifdef Q_WS_MAC
     // No difference between update() and repaint() on the Mac.
     update_sys(toBePainted);
     return;
 #endif
     toBePainted &= clipRect();
     clipToEffectiveMask(toBePainted);
     if (toBePainted.isEmpty())
         return; // Nothing to repaint.
 #ifndef QT_NO_PAINT_DEBUG
     bool flushed = QWidgetBackingStore::flushPaint(q, toBePainted);
 #endif
     drawWidget(q, toBePainted, QPoint(), QWidgetPrivate::DrawAsRoot | QWidgetPrivate::DrawPaintOnScreen, 0);
 #ifndef QT_NO_PAINT_DEBUG
     if (flushed)
         QWidgetBackingStore::unflushPaint(q, toBePainted);
 #endif
     if (!q->testAttribute(Qt::WA_PaintOutsidePaintEvent) && q->paintingActive())
         qWarning("QWidget::repaint: It is dangerous to leave painters active on a widget outside of the PaintEvent");
 }
reparentFocusWidgets()
void QWidgetPrivate::reparentFocusWidgets (QWidget * oldtlw)
Warning
This function is not part of the public interface.
Moves the relevant subwidgets of this widget from the oldtlw's tab chain to that of the new parent, if there's anything to move and we're really moving
This function is called from QWidget::reparent() after the widget has been reparented.
See also
reparent()
Definition at line 7047 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (oldtlw == q->window())
         return; // nothing to do
     if(focus_child)
         focus_child->clearFocus();
     // separate the focus chain into new (children of myself) and old (the rest)
     QWidget *firstOld = 0;
     //QWidget *firstNew = q; //invariant
     QWidget *o = 0; // last in the old list
     QWidget *n = q; // last in the new list
     bool prevWasNew = true;
     QWidget *w = focus_next;
     //Note: for efficiency, we do not maintain the list invariant inside the loop
     //we append items to the relevant list, and we optimize by not changing pointers
     //when subsequent items are going into the same list.
     while (w  != q) {
         bool currentIsNew =  q->isAncestorOf(w);
         if (currentIsNew) {
             if (!prevWasNew) {
                 //prev was old -- append to new list
                 n->d_func()->focus_next = w;
                 w->d_func()->focus_prev = n;
             }
             n = w;
         } else {
             if (prevWasNew) {
                 //prev was new -- append to old list, if there is one
                 if (o) {
                     o->d_func()->focus_next = w;
                     w->d_func()->focus_prev = o;
                 } else {
                     // "create" the old list
                     firstOld = w;
                 }
             }
             o = w;
         }
         w = w->d_func()->focus_next;
         prevWasNew = currentIsNew;
     }
     //repair the old list:
     if (firstOld) {
         o->d_func()->focus_next = firstOld;
         firstOld->d_func()->focus_prev = o;
     }
     if (!q->isWindow()) {
         QWidget *topLevel = q->window();
         //insert new chain into toplevel's chain
         QWidget *prev = topLevel->d_func()->focus_prev;
         topLevel->d_func()->focus_prev = n;
         prev->d_func()->focus_next = q;
         focus_prev = prev;
         n->d_func()->focus_next = topLevel;
     } else {
         //repair the new list
             n->d_func()->focus_next = q;
             focus_prev = n;
     }
 }
resolveFont()
void QWidgetPrivate::resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
Warning
This function is not part of the public interface.
Then propagate this font to this widget's children.
Definition at line 5074 of file qwidget.cpp.
Referenced by QGraphicsProxyWidget::event(), setModal_sys(), and updateFont().
 {
     QFont naturalFont = naturalWidgetFont(inheritedFontResolveMask);
     QFont resolvedFont = data.fnt.resolve(naturalFont);
     setFont_helper(resolvedFont);
 }
resolveLayoutDirection()
void QWidgetPrivate::resolveLayoutDirection ()
Definition at line 5171 of file qwidget.cpp.
 {
     Q_Q(const QWidget);
     if (!q->testAttribute(Qt::WA_SetLayoutDirection))
         setLayoutDirection_helper(q->isWindow() ? QApplication::layoutDirection() : q->parentWidget()->layoutDirection());
 }
resolveLocale()
void QWidgetPrivate::resolveLocale ()
Definition at line 6167 of file qwidget.cpp.
 {
     Q_Q(const QWidget);
     if (!q->testAttribute(Qt::WA_SetLocale)) {
         setLocale_helper(q->isWindow()
                             ? QLocale()
                             : q->parentWidget()->locale());
     }
 }
resolvePalette()
void QWidgetPrivate::resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
Warning
This function is not part of the public interface.
Then propagate this palette to this widget's children.
Definition at line 4927 of file qwidget.cpp.
Referenced by QGraphicsProxyWidget::event(), and propagatePaletteChange().
 {
     QPalette naturalPalette = naturalWidgetPalette(inheritedPaletteResolveMask);
     QPalette resolvedPalette = data.pal.resolve(naturalPalette);
     setPalette_helper(resolvedPalette);
 }
restoreRedirected()
void QWidgetPrivate::restoreRedirected () inline
Definition at line 635 of file qwidget_p.h.
     { redirectDev = 0; }
screenGeometry()
static QRect QWidgetPrivate::screenGeometry (const QWidget * widget) inline static
Definition at line 600 of file qwidget_p.h.
Referenced by QDesktopWidget::availableGeometry(), QDesktopWidgetPrivate::init(), QDesktopWidget::screenGeometry(), and QDesktopWidgetPrivate::updateScreenList().
     {
         QRect screen;
 #ifndef QT_NO_GRAPHICSVIEW
         QGraphicsProxyWidget *ancestorProxy = widget->d_func()->nearestGraphicsProxyWidget(widget);
         //It's embedded if it has an ancestor
         if (ancestorProxy) {
             if (!bypassGraphicsProxyWidget(widget) && ancestorProxy->scene() != 0) {
                 // One view, let be smart and return the viewport rect then the popup is aligned
                 if (ancestorProxy->scene()->views().size() == 1) {
                     QGraphicsView *view = ancestorProxy->scene()->views().at(0);
                     screen = view->mapToScene(view->viewport()->rect()).boundingRect().toRect();
                 } else {
                     screen = ancestorProxy->scene()->sceneRect().toRect();
                 }
             }
         }
 #endif
         return screen;
     }
scroll_sys() [1/2]
void QWidgetPrivate::scroll_sys (int dx, int dy)
Definition at line 4700 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), QMacScrollOptimization::performDelayedScroll(), and qt_grab_cursor().
 {
     if (QApplicationPrivate::graphicsSystem() && !paintOnScreen()) {
         // INVARIANT: Alien paint engine
         scrollChildren(dx, dy);
         scrollRect(q_func()->rect(), dx, dy);
     } else {
         scroll_sys(dx, dy, QRect());
     }
 }
scroll_sys() [2/2]
void QWidgetPrivate::scroll_sys (int dx, int dy, const QRect & r)
Definition at line 4711 of file qwidget_mac.mm.
 {
     if (QMacScrollOptimization::delayScroll(this, dx, dy, qscrollRect))
         return;
     Q_Q(QWidget);
     if (QApplicationPrivate::graphicsSystem() && !paintOnScreen()) {
         // INVARIANT: Alien paint engine
         scrollRect(qscrollRect, dx, dy);
         return;
     }
     static int accelEnv = -1;
     if (accelEnv == -1) {
         accelEnv = qgetenv("QT_NO_FAST_SCROLL").toInt() == 0;
     }
     // Scroll the whole widget if qscrollRect is not valid:
     QRect validScrollRect = qscrollRect.isValid() ? qscrollRect : q->rect();
     // If q is overlapped by other widgets, we cannot just blit pixels since
     // this will move overlapping widgets as well. In case we just update:
     const bool overlapped = isOverlapped(validScrollRect.translated(data.crect.topLeft()));
     const bool accelerateScroll = accelEnv && isOpaque && !overlapped;
     const bool isAlien = (q->internalWinId() == 0);
     // If qscrollRect is valid, we are _not_ supposed to scroll q's children (as documented).
     // But we do scroll children (and the whole of q) if qscrollRect is invalid. This case is
     // documented as undefined, but we exploit it to help factor our code into one function.
     const bool scrollChildren = !qscrollRect.isValid();
     if (!q->updatesEnabled()) {
         // We are told not to update anything on q at this point. So unless
         // we are supposed to scroll children, we bail out early:
         if (!scrollChildren || q->children().isEmpty())
             return;
     }
     if (!accelerateScroll) {
         if (overlapped) {
             QRegion region(validScrollRect);
             subtractOpaqueSiblings(region);
             update_sys(region);
         }else {
             update_sys(qscrollRect);
         }
     }
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
 #else
     Q_UNUSED(isAlien);
     // We're not sure what the following call is supposed to achive
     // but until we see what it breaks, we don't bring it into the
     // Cocoa port:
     qt_event_request_window_change(q);
 #endif
     // First move all native children. Alien children will indirectly be
     // moved when the parent is scrolled. All directly or indirectly moved
     // children will receive a move event before the function call returns.
     QWidgetList movedChildren;
     const QPoint scrollDelta(dx, dy);
     if (scrollChildren) {
         QObjectList children = q->children();
         for (int i=0; i<children.size(); i++) {
             QObject *obj = children.at(i);
             if (QWidget *w = qobject_cast<QWidget*>(obj)) {
                 if (!w->isWindow()) {
                     w->data->crect = QRect(w->pos() + scrollDelta, w->size());
 #ifndef QT_MAC_USE_COCOA
                     if (w->testAttribute(Qt::WA_WState_Created)) {
                         HIRect bounds = CGRectMake(w->data->crect.x(), w->data->crect.y(),
                                                    w->data->crect.width(), w->data->crect.height());
                         HIViewRef hiview = qt_mac_nativeview_for(w);
                         const bool opaque = q->testAttribute(Qt::WA_OpaquePaintEvent);
                         if (opaque)
                             HIViewSetDrawingEnabled(hiview,  false);
                         HIViewSetFrame(hiview, &bounds);
                         if (opaque)
                             HIViewSetDrawingEnabled(hiview,  true);
                     }
 #else
                     if (NSView *view = qt_mac_nativeview_for(w)) {
                         // INVARIANT: w is not alien
                         [view setFrame:NSMakeRect(
                             w->data->crect.x(), w->data->crect.y(),
                             w->data->crect.width(), w->data->crect.height())];
                     }
 #endif
                     movedChildren.append(w);
                 }
             }
         }
     }
     if (q->testAttribute(Qt::WA_WState_Created) && q->isVisible()) {
         // Scroll q itself according to the qscrollRect, and
         // call update on any exposed areas so that they get redrawn:
 #ifndef QT_MAC_USE_COCOA
         OSViewRef view = qt_mac_nativeview_for(q);
         HIRect scrollrect = CGRectMake(qscrollRect.x(), qscrollRect.y(), qscrollRect.width(), qscrollRect.height());
         OSStatus err = _HIViewScrollRectWithOptions(view, qscrollRect.isValid() ? &scrollrect : 0, dx, dy, kHIViewScrollRectAdjustInvalid);
         if (err) {
            // The only parameter that can go wrong, is the rect.
            qWarning("QWidget::scroll: Your rectangle was too big for the widget, clipping rect");
            scrollrect = CGRectMake(qMax(qscrollRect.x(), 0), qMax(qscrollRect.y(), 0),
                                    qMin(qscrollRect.width(), q->width()), qMin(qscrollRect.height(), q->height()));
            _HIViewScrollRectWithOptions(view, qscrollRect.isValid() ? &scrollrect : 0, dx, dy, kHIViewScrollRectAdjustInvalid);
         }
 #else
         QWidget *nativeWidget = isAlien ? q->nativeParentWidget() : q;
         if (!nativeWidget)
             return;
         OSViewRef view = qt_mac_nativeview_for(nativeWidget);
         if (!view)
             return;
         // Calculate the rectangles that needs to be redrawn
         // after the scroll. This will be source rect minus destination rect:
         QRect deltaXRect;
         if (dx != 0) {
             deltaXRect.setY(validScrollRect.y());
             deltaXRect.setHeight(validScrollRect.height());
             if (dx > 0) {
                 deltaXRect.setX(validScrollRect.x());
                 deltaXRect.setWidth(dx);
             } else {
                 deltaXRect.setX(validScrollRect.x() + validScrollRect.width() + dx);
                 deltaXRect.setWidth(-dx);
             }
         }
         QRect deltaYRect;
         if (dy != 0) {
             deltaYRect.setX(validScrollRect.x());
             deltaYRect.setWidth(validScrollRect.width());
             if (dy > 0) {
                 deltaYRect.setY(validScrollRect.y());
                 deltaYRect.setHeight(dy);
            } else {
                 deltaYRect.setY(validScrollRect.y() + validScrollRect.height() + dy);
                 deltaYRect.setHeight(-dy);
             }
         }
         if (isAlien) {
             // Adjust the scroll rect to the location as seen from the native parent:
             QPoint scrollTopLeftInsideNative = nativeWidget->mapFromGlobal(q->mapToGlobal(validScrollRect.topLeft()));
             validScrollRect.moveTo(scrollTopLeftInsideNative);
         }
         // Make the pixel copy rect within the validScrollRect bounds:
         NSRect nsscrollRect = NSMakeRect(
             validScrollRect.x() + (dx < 0 ? -dx : 0),
             validScrollRect.y() + (dy < 0 ? -dy : 0),
             validScrollRect.width() + (dx > 0 ? -dx : 0),
             validScrollRect.height() + (dy > 0 ? -dy : 0));
         NSSize deltaSize = NSMakeSize(dx, dy);
         [view scrollRect:nsscrollRect by:deltaSize];
         // Some areas inside the scroll rect might have been marked as dirty from before, which
         // means that they are scheduled to be redrawn. But as we now scroll, those dirty rects
         // should also move along to ensure that q receives repaints on the correct places.
         // Since some of the dirty rects might lay outside, or only intersect with, the scroll
         // rect, the old calls to setNeedsDisplay still makes sense.
         // NB: Using [view translateRectsNeedingDisplayInRect:nsscrollRect by:deltaSize] have
         // so far not been proven fruitful to solve this problem.
         const QVector<QRect> &dirtyRectsToScroll = dirtyOnWidget.rects();
         for (int i=0; i<dirtyRectsToScroll.size(); ++i) {
             QRect qdirtyRect = dirtyRectsToScroll[i];
             qdirtyRect.translate(dx, dy);
             update_sys(qdirtyRect);
         }
         // Update newly exposed areas. This will generate new dirty areas on
         // q, and therefore, we do it after updating the old dirty rects above:
         if (dx != 0)
             update_sys(deltaXRect);
         if (dy != 0)
             update_sys(deltaYRect);
 #endif // QT_MAC_USE_COCOA
     }
     for (int i=0; i<movedChildren.size(); i++) {
         QWidget *w = movedChildren.at(i);
         QMoveEvent e(w->pos(), w->pos() - scrollDelta);
         QApplication::sendEvent(w, &e);
     }
 }
scrollChildren()
void QWidgetPrivate::scrollChildren (int dx, int dy)
Warning
This function is not part of the public interface.
Definition at line 421 of file qwidget.cpp.
Referenced by effectiveState(), qt_grab_cursor(), and scroll_sys().
 {
     Q_Q(QWidget);
     if (q->children().size() > 0) {        // scroll children
         QPoint pd(dx, dy);
         QObjectList childObjects = q->children();
         for (int i = 0; i < childObjects.size(); ++i) { // move all children
             QWidget *w = qobject_cast<QWidget*>(childObjects.at(i));
             if (w && !w->isWindow()) {
                 QPoint oldp = w->pos();
                 QRect  r(w->pos() + pd, w->size());
                 w->data->crect = r;
 #ifndef Q_WS_QWS
                 if (w->testAttribute(Qt::WA_WState_Created))
                     w->d_func()->setWSGeometry();
 #endif
                 w->d_func()->setDirtyOpaqueRegion();
                 QMoveEvent e(r.topLeft(), oldp);
                 QApplication::sendEvent(w, &e);
             }
         }
     }
 }
scrollRect()
void QWidgetPrivate::scrollRect (const QRect & rect, int dx, int dy)
Definition at line 1003 of file qbackingstore.cpp.
Referenced by effectiveState(), qt_grab_cursor(), qt_mac_update_widget_position(), and scroll_sys().
 {
     Q_Q(QWidget);
     QWidget *tlw = q->window();
     QTLWExtra* x = tlw->d_func()->topData();
     if (x->inTopLevelResize)
         return;
     QWidgetBackingStore *wbs = x->backingStore.data();
     if (!wbs)
         return;
     static int accelEnv = -1;
     if (accelEnv == -1) {
         accelEnv = qgetenv("QT_NO_FAST_SCROLL").toInt() == 0;
     }
     QRect scrollRect = rect & clipRect();
     bool overlapped = false;
     bool accelerateScroll = accelEnv && isOpaque
                             && !(overlapped = isOverlapped(scrollRect.translated(data.crect.topLeft())));
 #if defined(Q_WS_QWS)
     QWSWindowSurface *surface;
     surface = static_cast<QWSWindowSurface*>(wbs->windowSurface);
     if (accelerateScroll && !surface->isBuffered()) {
         const QRegion surfaceClip = surface->clipRegion();
         const QRegion outsideClip = QRegion(rect) - surfaceClip;
         if (!outsideClip.isEmpty()) {
             const QVector<QRect> clipped = (surfaceClip & rect).rects();
             if (clipped.size() < 8) {
                 for (int i = 0; i < clipped.size(); ++i)
                     this->scrollRect(clipped.at(i), dx, dy);
                 return;
             } else {
                 accelerateScroll = false;
             }
         }
     }
 #endif // Q_WS_QWS
     if (!accelerateScroll) {
         if (overlapped) {
             QRegion region(scrollRect);
             subtractOpaqueSiblings(region);
             invalidateBuffer(region);
         }else {
             invalidateBuffer(scrollRect);
         }
     } else {
         const QPoint toplevelOffset = q->mapTo(tlw, QPoint());
 #ifdef Q_WS_QWS
         QWSWindowSurface *surface = static_cast<QWSWindowSurface*>(wbs->windowSurface);
         const QRegion clip = surface->clipRegion().translated(-toplevelOffset) & scrollRect;
         const QRect clipBoundingRect = clip.boundingRect();
         scrollRect &= clipBoundingRect;
 #endif
         const QRect destRect = scrollRect.translated(dx, dy) & scrollRect;
         const QRect sourceRect = destRect.translated(-dx, -dy);
         QRegion childExpose(scrollRect);
         if (sourceRect.isValid()) {
             if (wbs->bltRect(sourceRect, dx, dy, q))
                 childExpose -= destRect;
         }
         if (inDirtyList) {
             if (rect == q->rect()) {
                 dirty.translate(dx, dy);
             } else {
                 QRegion dirtyScrollRegion = dirty.intersected(scrollRect);
                 if (!dirtyScrollRegion.isEmpty()) {
                     dirty -= dirtyScrollRegion;
                     dirtyScrollRegion.translate(dx, dy);
                     dirty += dirtyScrollRegion;
                 }
             }
         }
         if (!q->updatesEnabled())
             return;
         if (!childExpose.isEmpty()) {
             wbs->markDirty(childExpose, q);
             isScrolled = true;
         }
         // Instead of using native scroll-on-screen, we copy from
         // backingstore, giving only one screen update for each
         // scroll, and a solid appearance
         wbs->markDirtyOnScreen(destRect, q, toplevelOffset);
     }
 }
sendPendingMoveAndResizeEvents()
void QWidgetPrivate::sendPendingMoveAndResizeEvents (bool recursive = false, bool disableUpdates = false)
Definition at line 7720 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     disableUpdates = disableUpdates && q->updatesEnabled();
     if (disableUpdates)
         q->setAttribute(Qt::WA_UpdatesDisabled);
     if (q->testAttribute(Qt::WA_PendingMoveEvent)) {
         QMoveEvent e(data.crect.topLeft(), data.crect.topLeft());
         QApplication::sendEvent(q, &e);
         q->setAttribute(Qt::WA_PendingMoveEvent, false);
     }
     if (q->testAttribute(Qt::WA_PendingResizeEvent)) {
         QResizeEvent e(data.crect.size(), QSize());
         QApplication::sendEvent(q, &e);
         q->setAttribute(Qt::WA_PendingResizeEvent, false);
     }
     if (disableUpdates)
         q->setAttribute(Qt::WA_UpdatesDisabled, false);
     if (!recursive)
         return;
     for (int i = 0; i < children.size(); ++i) {
         if (QWidget *child = qobject_cast<QWidget *>(children.at(i)))
             child->d_func()->sendPendingMoveAndResizeEvents(recursive, disableUpdates);
     }
 }
sendStartupMessage()
void QWidgetPrivate::sendStartupMessage (const char * message) const
Platform-specific part of QWidget::show().
Warning
This function is not part of the public interface.
Definition at line 2126 of file qwidget_x11.cpp.
 {
     Q_Q(const QWidget);
     if (!message)
         return;
     XEvent xevent;
     xevent.xclient.type = ClientMessage;
     xevent.xclient.message_type = ATOM(_NET_STARTUP_INFO_BEGIN);
     xevent.xclient.display = X11->display;
     xevent.xclient.window = q->internalWinId();
     xevent.xclient.format = 8;
     Window rootWindow = RootWindow(X11->display, DefaultScreen(X11->display));
     uint sent = 0;
     uint length = strlen(message) + 1;
     do {
         if (sent == 20)
             xevent.xclient.message_type = ATOM(_NET_STARTUP_INFO);
         for (uint i = 0; i < 20 && i + sent <= length; i++)
             xevent.xclient.data.b[i] = message[i + sent++];
         XSendEvent(X11->display, rootWindow, false, PropertyChangeMask, &xevent);
     } while (sent <= length);
 }
setConstraints_sys()
void QWidgetPrivate::setConstraints_sys ()
Definition at line 4646 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), and qt_grab_cursor().
 {
     updateMaximizeButton_sys();
     applyMaxAndMinSizeOnWindow();
 }
setCursor_sys()
void QWidgetPrivate::setCursor_sys (const QCursor & cursor)
Definition at line 3163 of file qwidget_mac.mm.
Referenced by isServerProcess(), mapFromGlobal(), and q_createNativeChildrenAndSetParent().
 {
     qt_mac_update_cursor();
 }
setDirtyOpaqueRegion()
void QWidgetPrivate::setDirtyOpaqueRegion ()
Definition at line 2075 of file qwidget.cpp.
Referenced by effectiveState(), and setDirtyOpaqueRegion().
 {
     Q_Q(QWidget);
     dirtyOpaqueChildren = true;
 #ifndef QT_NO_GRAPHICSEFFECT
     invalidateGraphicsEffectsRecursively();
 #endif //QT_NO_GRAPHICSEFFECT
     if (q->isWindow())
         return;
     QWidget *parent = q->parentWidget();
     if (!parent)
         return;
     // TODO: instead of setting dirtyflag, manipulate the dirtyregion directly?
     QWidgetPrivate *pd = parent->d_func();
     if (!pd->dirtyOpaqueChildren)
         pd->setDirtyOpaqueRegion();
 }
setEnabled_helper()
void QWidgetPrivate::setEnabled_helper (bool enable)
Definition at line 3454 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (enable && !q->isWindow() && q->parentWidget() && !q->parentWidget()->isEnabled())
         return; // nothing we can do
     if (enable != q->testAttribute(Qt::WA_Disabled))
         return; // nothing to do
     q->setAttribute(Qt::WA_Disabled, !enable);
     updateSystemBackground();
     if (!enable && q->window()->focusWidget() == q) {
         bool parentIsEnabled = (!q->parentWidget() || q->parentWidget()->isEnabled());
         if (!parentIsEnabled || !q->focusNextChild())
             q->clearFocus();
     }
     Qt::WidgetAttribute attribute = enable ? Qt::WA_ForceDisabled : Qt::WA_Disabled;
     for (int i = 0; i < children.size(); ++i) {
         QWidget *w = qobject_cast<QWidget *>(children.at(i));
         if (w && !w->testAttribute(attribute))
             w->d_func()->setEnabled_helper(enable);
     }
 #if defined(Q_WS_X11)
     if (q->testAttribute(Qt::WA_SetCursor) || q->isWindow()) {
         // enforce the windows behavior of clearing the cursor on
         // disabled widgets
         qt_x11_enforce_cursor(q);
     }
 #endif
 #if defined(Q_WS_MAC)
     setEnabled_helper_sys(enable);
 #endif
 #ifndef QT_NO_IM
     if (q->testAttribute(Qt::WA_InputMethodEnabled) && q->hasFocus()) {
         QWidget *focusWidget = effectiveFocusWidget();
         QInputContext *qic = focusWidget->d_func()->inputContext();
         if (enable) {
             if (focusWidget->testAttribute(Qt::WA_InputMethodEnabled))
                 qic->setFocusWidget(focusWidget);
         } else {
             qic->reset();
             qic->setFocusWidget(0);
         }
     }
 #endif //QT_NO_IM
     QEvent e(QEvent::EnabledChange);
     QApplication::sendEvent(q, &e);
 #ifdef QT3_SUPPORT
     q->enabledChange(!enable); // compatibility
 #endif
 }
setFocus_sys()
void QWidgetPrivate::setFocus_sys ()
Definition at line 3913 of file qwidget_mac.mm.
Referenced by create_sys(), effectiveState(), qt_grab_cursor(), setNetWmWindowTypes(), and show_sys().
 {
     Q_Q(QWidget);
     if (q->testAttribute(Qt::WA_WState_Created)) {
 #ifdef QT_MAC_USE_COCOA
         QMacCocoaAutoReleasePool pool;
         NSView *view = qt_mac_effectiveview_for(q);
         [[view window] makeFirstResponder:view];
 #else
         SetKeyboardFocus(qt_mac_window_for(q), qt_mac_nativeview_for(q), 1);
 #endif
     }
 }
setFont_helper()
void QWidgetPrivate::setFont_helper (const QFont & font) inline
Definition at line 436 of file qwidget_p.h.
{
         if (data.fnt == font && data.fnt.resolve() == font.resolve())
             return;
         updateFont(font);
     }
setGeometry_sys()
void QWidgetPrivate::setGeometry_sys (int x, int y, int w, int h, bool isMove)
Definition at line 4495 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), and qt_grab_cursor().
 {
     Q_Q(QWidget);
     Q_ASSERT(q->testAttribute(Qt::WA_WState_Created));
     if(q->windowType() == Qt::Desktop)
         return;
     QMacCocoaAutoReleasePool pool;
     bool realWindow = isRealWindow();
     if (realWindow && !q->testAttribute(Qt::WA_DontShowOnScreen)){
         adjustWithinMaxAndMinSize(w, h);
 #ifndef QT_MAC_USE_COCOA
         if (w != 0 && h != 0) {
             topData()->isSetGeometry = 1;
             topData()->isMove = isMove;
             Rect r; SetRect(&r, x, y, x + w, y + h);
             SetWindowBounds(qt_mac_window_for(q), kWindowContentRgn, &r);
             topData()->isSetGeometry = 0;
         } else {
             setGeometry_sys_helper(x, y, w, h, isMove);
         }
 #else
         if (!isMove && !q->testAttribute(Qt::WA_Moved) && !q->isVisible()) {
             // INVARIANT: The location of the window has not yet been set. The default will
             // instead be to center it on the desktop, or over the parent, if any. Since we now
             // resize the window, we need to adjust the top left position to keep the window
             // centeralized. And we need to to this now (and before show) in case the positioning
             // of other windows (e.g. sub-windows) depend on this position:
             if (QWidget *p = q->parentWidget()) {
                 x = p->geometry().center().x() - (w / 2);
                 y = p->geometry().center().y() - (h / 2);
             } else {
                 QRect availGeo = QApplication::desktop()->availableGeometry(q);
                 x = availGeo.center().x() - (w / 2);
                 y = availGeo.center().y() - (h / 2);
             }
         }
         QSize  olds = q->size();
         const bool isResize = (olds != QSize(w, h));
         NSWindow *window = qt_mac_window_for(q);
         const QRect &fStrut = frameStrut();
         const QRect frameRect(QPoint(x - fStrut.left(), y - fStrut.top()),
                               QSize(fStrut.left() + fStrut.right() + w,
                                     fStrut.top() + fStrut.bottom() + h));
         NSRect cocoaFrameRect = NSMakeRect(frameRect.x(), flipYCoordinate(frameRect.bottom() + 1),
                                            frameRect.width(), frameRect.height());
         // The setFrame call will trigger a 'windowDidResize' notification for the corresponding
         // NSWindow. The pending flag is set, so that the resize event can be send as non-spontaneous.
         if (isResize)
             q->setAttribute(Qt::WA_PendingResizeEvent);
         QPoint currTopLeft = data.crect.topLeft();
         if (currTopLeft.x() == x && currTopLeft.y() == y
                 && cocoaFrameRect.size.width != 0
                 && cocoaFrameRect.size.height != 0) {
             [window setFrame:cocoaFrameRect display:realWindow];
         } else {
             // The window is moved and resized (or resized to zero).
             // Since Cocoa usually only sends us a resize callback after
             // setting a window frame, we issue an explicit move as
             // well. To stop Cocoa from optimize away the move (since the move
             // would have the same origin as the setFrame call) we shift the
             // window back and forth inbetween.
             cocoaFrameRect.origin.y += 1;
             [window setFrame:cocoaFrameRect display:realWindow];
             cocoaFrameRect.origin.y -= 1;
             [window setFrameOrigin:cocoaFrameRect.origin];
         }
 #endif
     } else {
         setGeometry_sys_helper(x, y, w, h, isMove);
     }
     topLevelAt_cache = 0;
 }
setLayoutDirection_helper()
void QWidgetPrivate::setLayoutDirection_helper (Qt::LayoutDirection direction)
Definition at line 5153 of file qwidget.cpp.
Referenced by QMenuPrivate::updateLayoutDirection().
 {
     Q_Q(QWidget);
     if ( (direction == Qt::RightToLeft) == q->testAttribute(Qt::WA_RightToLeft))
         return;
     q->setAttribute(Qt::WA_RightToLeft, (direction == Qt::RightToLeft));
     if (!children.isEmpty()) {
         for (int i = 0; i < children.size(); ++i) {
             QWidget *w = qobject_cast<QWidget*>(children.at(i));
             if (w && !w->isWindow() && !w->testAttribute(Qt::WA_SetLayoutDirection))
                 w->d_func()->setLayoutDirection_helper(direction);
         }
     }
     QEvent e(QEvent::LayoutDirectionChange);
     QApplication::sendEvent(q, &e);
 }
setLayoutItemMargins() [1/2]
void QWidgetPrivate::setLayoutItemMargins (int left, int top, int right, int bottom)
Definition at line 12860 of file qwidget.cpp.
Referenced by QRadioButtonPrivate::init(), QCheckBoxPrivate::init(), QSpinBoxPrivate::init(), QFramePrivate::init(), QDateTimeEditPrivate::init(), QDialogButtonBoxPrivate::initLayout(), QProgressBarPrivate::resetLayoutItemMargins(), and QSliderPrivate::resetLayoutItemMargins().
 {
     if (leftLayoutItemMargin == left
         && topLayoutItemMargin == top
         && rightLayoutItemMargin == right
         && bottomLayoutItemMargin == bottom)
         return;
     Q_Q(QWidget);
     leftLayoutItemMargin = (signed char)left;
     topLayoutItemMargin = (signed char)top;
     rightLayoutItemMargin = (signed char)right;
     bottomLayoutItemMargin = (signed char)bottom;
     q->updateGeometry();
 }
setLayoutItemMargins() [2/2]
void QWidgetPrivate::setLayoutItemMargins (QStyle::SubElement element, const QStyleOption * opt = 0)
Definition at line 12876 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     QStyleOption myOpt;
     if (!opt) {
         myOpt.initFrom(q);
         myOpt.rect.setRect(0, 0, 32768, 32768);     // arbitrary
         opt = &myOpt;
     }
     QRect liRect = q->style()->subElementRect(element, opt, q);
     if (liRect.isValid()) {
         leftLayoutItemMargin = (signed char)(opt->rect.left() - liRect.left());
         topLayoutItemMargin = (signed char)(opt->rect.top() - liRect.top());
         rightLayoutItemMargin = (signed char)(liRect.right() - opt->rect.right());
         bottomLayoutItemMargin = (signed char)(liRect.bottom() - opt->rect.bottom());
     } else {
         leftLayoutItemMargin = 0;
         topLayoutItemMargin = 0;
         rightLayoutItemMargin = 0;
         bottomLayoutItemMargin = 0;
     }
 }
setLocale_helper()
void QWidgetPrivate::setLocale_helper (const QLocale & l, bool forceUpdate = false)
Definition at line 6128 of file qwidget.cpp.
Referenced by QtWndProc().
 {
     Q_Q(QWidget);
     if (locale == loc && !forceUpdate)
         return;
     locale = loc;
     if (!children.isEmpty()) {
         for (int i = 0; i < children.size(); ++i) {
             QWidget *w = qobject_cast<QWidget*>(children.at(i));
             if (!w)
                 continue;
             if (w->testAttribute(Qt::WA_SetLocale))
                 continue;
             if (w->isWindow() && !w->testAttribute(Qt::WA_WindowPropagation))
                 continue;
             w->d_func()->setLocale_helper(loc, forceUpdate);
         }
     }
     QEvent e(QEvent::LocaleChange);
     QApplication::sendEvent(q, &e);
 }
setMask_sys()
void QWidgetPrivate::setMask_sys (const QRegion & region)
Definition at line 5076 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), qt_grab_cursor(), and qt_tablet_cleanup_wce().
 {
     Q_UNUSED(region);
     Q_Q(QWidget);
 #ifndef QT_MAC_USE_COCOA
     if (q->isWindow())
         ReshapeCustomWindow(qt_mac_window_for(q));
     else
         HIViewReshapeStructure(qt_mac_nativeview_for(q));
 #else
     if (!q->internalWinId())
         return;
     if (extra->mask.isEmpty()) {
         extra->maskBits = QImage();
         finishCocoaMaskSetup();
     } else {
         syncCocoaMask();
     }
     topLevelAt_cache = 0;
 #endif
 }
setMaximumSize_helper()
bool QWidgetPrivate::setMaximumSize_helper (int & maxw, int & maxh)
Definition at line 4163 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (maxw > QWIDGETSIZE_MAX || maxh > QWIDGETSIZE_MAX) {
         qWarning("QWidget::setMaximumSize: (%s/%s) "
                 "The largest allowed size is (%d,%d)",
                  q->objectName().toLocal8Bit().data(), q->metaObject()->className(), QWIDGETSIZE_MAX,
                 QWIDGETSIZE_MAX);
         maxw = qMin<int>(maxw, QWIDGETSIZE_MAX);
         maxh = qMin<int>(maxh, QWIDGETSIZE_MAX);
     }
     if (maxw < 0 || maxh < 0) {
         qWarning("QWidget::setMaximumSize: (%s/%s) Negative sizes (%d,%d) "
                 "are not possible",
                 q->objectName().toLocal8Bit().data(), q->metaObject()->className(), maxw, maxh);
         maxw = qMax(maxw, 0);
         maxh = qMax(maxh, 0);
     }
     createExtra();
     if (extra->maxw == maxw && extra->maxh == maxh)
         return false;
     extra->maxw = maxw;
     extra->maxh = maxh;
     extra->explicitMaxSize = (maxw != QWIDGETSIZE_MAX ? Qt::Horizontal : 0) |
                              (maxh != QWIDGETSIZE_MAX ? Qt::Vertical : 0);
     return true;
 }
setMinimumSize_helper()
bool QWidgetPrivate::setMinimumSize_helper (int & minw, int & minh)
Definition at line 4081 of file qwidget.cpp.
 {
     Q_Q(QWidget);
 #ifdef Q_WS_QWS
     if (q->isWindow()) {
         const QRect maxWindowRect = QApplication::desktop()->availableGeometry(QApplication::desktop()->screenNumber(q));
         if (!maxWindowRect.isEmpty()) {
             // ### This is really just a work-around. Layout shouldn't be
             // asking for minimum sizes bigger than the screen.
             if (minw > maxWindowRect.width())
                 minw = maxWindowRect.width();
             if (minh > maxWindowRect.height())
                 minh = maxWindowRect.height();
         }
     }
 #endif
     int mw = minw, mh = minh;
     if (mw == QWIDGETSIZE_MAX)
         mw = 0;
     if (mh == QWIDGETSIZE_MAX)
         mh = 0;
     if (minw > QWIDGETSIZE_MAX || minh > QWIDGETSIZE_MAX) {
         qWarning("QWidget::setMinimumSize: (%s/%s) "
                 "The largest allowed size is (%d,%d)",
                  q->objectName().toLocal8Bit().data(), q->metaObject()->className(), QWIDGETSIZE_MAX,
                 QWIDGETSIZE_MAX);
         minw = mw = qMin<int>(minw, QWIDGETSIZE_MAX);
         minh = mh = qMin<int>(minh, QWIDGETSIZE_MAX);
     }
     if (minw < 0 || minh < 0) {
         qWarning("QWidget::setMinimumSize: (%s/%s) Negative sizes (%d,%d) "
                 "are not possible",
                 q->objectName().toLocal8Bit().data(), q->metaObject()->className(), minw, minh);
         minw = mw = qMax(minw, 0);
         minh = mh = qMax(minh, 0);
     }
     createExtra();
     if (extra->minw == mw && extra->minh == mh)
         return false;
     extra->minw = mw;
     extra->minh = mh;
     extra->explicitMinSize = (mw ? Qt::Horizontal : 0) | (mh ? Qt::Vertical : 0);
     return true;
 }
setModal_sys()
void QWidgetPrivate::setModal_sys ()
Definition at line 5201 of file qwidget_mac.mm.
Referenced by effectiveState(), QX11Data::getSolidFill(), and show_sys().
 {
     Q_Q(QWidget);
     if (!q->testAttribute(Qt::WA_WState_Created) || !q->isWindow())
         return;
     const QWidget * const windowParent = q->window()->parentWidget();
     const QWidget * const primaryWindow = windowParent ? windowParent->window() : 0;
     OSWindowRef windowRef = qt_mac_window_for(q);
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     bool alreadySheet = [windowRef styleMask] & NSDocModalWindowMask;
     if (windowParent && q->windowModality() == Qt::WindowModal){
         // INVARIANT: Window should be window-modal (which implies a sheet).
         if (!alreadySheet) {
             // NB: the following call will call setModal_sys recursivly:
             recreateMacWindow();
             windowRef = qt_mac_window_for(q);
         }
         if ([windowRef isKindOfClass:[NSPanel class]]){
             // If the primary window of the sheet parent is a child of a modal dialog,
             // the sheet parent should not be modally shaddowed.
             // This goes for the sheet as well:
             OSWindowRef ref = primaryWindow ? qt_mac_window_for(primaryWindow) : 0;
             bool isDialog = ref ? [ref isKindOfClass:[NSPanel class]] : false;
             bool worksWhenModal = isDialog ? [static_cast<NSPanel *>(ref) worksWhenModal] : false;
             if (worksWhenModal)
                 [static_cast<NSPanel *>(windowRef) setWorksWhenModal:YES];
         }
     } else {
         // INVARIANT: Window shold _not_ be window-modal (and as such, not a sheet).
         if (alreadySheet){
             // NB: the following call will call setModal_sys recursivly:
             recreateMacWindow();
             windowRef = qt_mac_window_for(q);
         }
         if (q->windowModality() == Qt::NonModal
             && primaryWindow && primaryWindow->windowModality() == Qt::ApplicationModal) {
             // INVARIANT: Our window has a parent that is application modal.
             // This means that q is supposed to be on top of this window and
             // not be modally shaddowed:
             if ([windowRef isKindOfClass:[NSPanel class]])
                 [static_cast<NSPanel *>(windowRef) setWorksWhenModal:YES];
         }
     }
 #else
     const bool primaryWindowModal = primaryWindow ? primaryWindow->testAttribute(Qt::WA_ShowModal) : false;
     const bool modal = q->testAttribute(Qt::WA_ShowModal);
     WindowClass old_wclass;
     GetWindowClass(windowRef, &old_wclass);
     if (modal || primaryWindowModal) {
         if (q->windowModality() == Qt::WindowModal
                 || (primaryWindow && primaryWindow->windowModality() == Qt::WindowModal)){
             // Window should be window-modal (which implies a sheet).
             if (old_wclass != kSheetWindowClass){
                 // We cannot convert a created window to a sheet.
                 // So we recreate the window:
                 recreateMacWindow();
                 return;
             }
         } else {
             // Window should be application-modal (which implies NOT using a sheet).
             if (old_wclass == kSheetWindowClass){
                 // We cannot convert a sheet to a window.
                 // So we recreate the window:
                 recreateMacWindow();
                 return;
             } else if (!(q->data->window_flags & Qt::CustomizeWindowHint)) {
                 if (old_wclass == kDocumentWindowClass || old_wclass == kFloatingWindowClass || old_wclass == kUtilityWindowClass){
                     // Only change the class to kMovableModalWindowClass if the no explicit jewels
                     // are set (kMovableModalWindowClass can't contain them), and the current window class
                     // can be converted to modal (according to carbon doc). Mind the order of
                     // HIWindowChangeClass and ChangeWindowAttributes.
                     WindowGroupRef group = GetWindowGroup(windowRef);
                     HIWindowChangeClass(windowRef, kMovableModalWindowClass);
                     quint32 tmpWattr = kWindowCloseBoxAttribute | kWindowHorizontalZoomAttribute;
                     ChangeWindowAttributes(windowRef, tmpWattr, kWindowNoAttributes);
                     ChangeWindowAttributes(windowRef, kWindowNoAttributes, tmpWattr);
                     // If the window belongs to a qt-created group, set that group once more:
                     if (data.window_flags & Qt::WindowStaysOnTopHint
                             || q->windowType() == Qt::Popup
                             || q->windowType() == Qt::ToolTip)
                         SetWindowGroup(windowRef, group);
                 }
                 // Popups are usually handled "special" and are never modal.
                 Qt::WindowType winType = q->windowType();
                 if (winType != Qt::Popup && winType != Qt::ToolTip)
                     SetWindowModality(windowRef, kWindowModalityAppModal, 0);
             }
         }
     } else if (windowRef) {
         if (old_wclass == kSheetWindowClass){
             // Converting a sheet to a window is complex. It's easier to recreate:
             recreateMacWindow();
             return;
         }
         SetWindowModality(windowRef, kWindowModalityNone, 0);
     if (!(q->data->window_flags & Qt::CustomizeWindowHint)) {
         if (q->window()->d_func()->topData()->wattr |= kWindowCloseBoxAttribute)
         ChangeWindowAttributes(windowRef, kWindowCloseBoxAttribute, kWindowNoAttributes);
         if (q->window()->d_func()->topData()->wattr |= kWindowHorizontalZoomAttribute)
         ChangeWindowAttributes(windowRef, kWindowHorizontalZoomAttribute, kWindowNoAttributes);
         if (q->window()->d_func()->topData()->wattr |= kWindowCollapseBoxAttribute)
                 ChangeWindowAttributes(windowRef, kWindowCollapseBoxAttribute, kWindowNoAttributes);
     }
         WindowClass newClass = q->window()->d_func()->topData()->wclass;
         if (old_wclass != newClass && newClass != 0){
             WindowGroupRef group = GetWindowGroup(windowRef);
             HIWindowChangeClass(windowRef, newClass);
             // If the window belongs to a qt-created group, set that group once more:
             if (data.window_flags & Qt::WindowStaysOnTopHint
                 || q->windowType() == Qt::Popup
                 || q->windowType() == Qt::ToolTip)
                 SetWindowGroup(windowRef, group);
         }
     }
     // Make sure that HIWindowChangeClass didn't remove drag support
     // or reset the opaque size grip setting:
     SetAutomaticControlDragTrackingEnabledForWindow(windowRef, true);
     macUpdateOpaqueSizeGrip();
 #endif
 }
setNetWmWindowTypes()
void QWidgetPrivate::setNetWmWindowTypes ()
Definition at line 2154 of file qwidget_x11.cpp.
 {
     Q_Q(QWidget);
     Q_ASSERT(q->testAttribute(Qt::WA_WState_Created));
     if (!q->isWindow()) {
         if (q->internalWinId())
             XDeleteProperty(X11->display, q->internalWinId(), ATOM(_NET_WM_WINDOW_TYPE));
         return;
     }
     QVector<long> windowTypes;
     // manual selection 1 (these are never set by Qt and take precedence)
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeDesktop))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_DESKTOP));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeDock))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_DOCK));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeNotification))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_NOTIFICATION));
     // manual selection 2 (Qt uses these during auto selection);
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeUtility))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_UTILITY));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeSplash))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_SPLASH));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeDialog))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_DIALOG));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeToolTip))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_TOOLTIP));
     // manual selection 3 (these can be set by Qt, but don't have a
     // corresponding Qt::WindowType). note that order of the *MENU
     // atoms is important
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeMenu))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_MENU));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeDropDownMenu))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_DROPDOWN_MENU));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypePopupMenu))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_POPUP_MENU));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeToolBar))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_TOOLBAR));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeCombo))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_COMBO));
     if (q->testAttribute(Qt::WA_X11NetWmWindowTypeDND))
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_DND));
     // automatic selection
     switch (q->windowType()) {
     case Qt::Dialog:
     case Qt::Sheet:
         // dialog netwm type
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_DIALOG));
         break;
     case Qt::Tool:
     case Qt::Drawer:
         // utility netwm type
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_UTILITY));
         break;
     case Qt::ToolTip:
         // tooltip netwm type
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_TOOLTIP));
         break;
     case Qt::SplashScreen:
         // splash netwm type
         windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_SPLASH));
         break;
     default:
         break;
     }
     if (q->windowFlags() & Qt::FramelessWindowHint) {
         // override netwm type - quick and easy for KDE noborder
         windowTypes.append(ATOM(_KDE_NET_WM_WINDOW_TYPE_OVERRIDE));
     }
     // normal netwm type - default
     windowTypes.append(ATOM(_NET_WM_WINDOW_TYPE_NORMAL));
     if (!windowTypes.isEmpty()) {
         XChangeProperty(X11->display, q->winId(), ATOM(_NET_WM_WINDOW_TYPE), XA_ATOM, 32,
                         PropModeReplace, (unsigned char *) windowTypes.constData(),
                         windowTypes.count());
     } else {
         XDeleteProperty(X11->display, q->winId(), ATOM(_NET_WM_WINDOW_TYPE));
     }
 }
setOpaque()
void QWidgetPrivate::setOpaque (bool opaque)
Definition at line 2337 of file qwidget.cpp.
Referenced by setWindowOpacity_sys(), and updateRedirectedToGraphicsProxyWidget().
 {
     if (isOpaque == opaque)
         return;
     isOpaque = opaque;
 #ifdef Q_WS_MAC
     macUpdateIsOpaque();
 #endif
 #ifdef Q_WS_X11
     x11UpdateIsOpaque();
 #endif
 #ifdef Q_WS_WIN
     winUpdateIsOpaque();
 #endif
 #ifdef Q_OS_SYMBIAN
     s60UpdateIsOpaque();
 #endif
 }
setPalette_helper()
void QWidgetPrivate::setPalette_helper (const QPalette & palette)
Definition at line 4934 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (data.pal == palette && data.pal.resolve() == palette.resolve())
         return;
     data.pal = palette;
     updateSystemBackground();
     propagatePaletteChange();
     updateIsOpaque();
     q->update();
     updateIsOpaque();
 }
setParent_sys()
void QWidgetPrivate::setParent_sys (QWidget * parent, Qt::WindowFlags f)
Definition at line 2934 of file qwidget_mac.mm.
Referenced by isBackgroundInherited(), isServerProcess(), and q_createNativeChildrenAndSetParent().
 {
     Q_Q(QWidget);
     QMacCocoaAutoReleasePool pool;
     QTLWExtra *topData = maybeTopData();
     bool wasCreated = q->testAttribute(Qt::WA_WState_Created);
 #ifdef QT_MAC_USE_COCOA
     bool wasWindow = q->isWindow();
 #endif
     OSViewRef old_id = 0;
     if (q->isVisible() && q->parentWidget() && parent != q->parentWidget())
         q->parentWidget()->d_func()->invalidateBuffer(effectiveRectFor(q->geometry()));
     // Maintain the glWidgets list on parent change: remove "our" gl widgets
     // from the list on the old parent and grandparents.
     if (glWidgets.isEmpty() == false) {
         QWidget *current = q->parentWidget();
         while (current) {
             for (QList<QWidgetPrivate::GlWidgetInfo>::const_iterator it = glWidgets.constBegin();
                  it != glWidgets.constEnd(); ++it)
                 current->d_func()->glWidgets.removeAll(*it);
             if (current->isWindow())
                 break;
             current = current->parentWidget();
         }
     }
 #ifndef QT_MAC_USE_COCOA
     EventHandlerRef old_window_event = 0;
 #else
     bool oldToolbarVisible = false;
     NSDrawer *oldDrawer = nil;
     NSToolbar *oldToolbar = 0;
 #endif
     if (wasCreated && !(q->windowType() == Qt::Desktop)) {
         old_id = qt_mac_nativeview_for(q);
 #ifndef QT_MAC_USE_COCOA
         old_window_event = window_event;
 #else
         if (qt_mac_is_macdrawer(q)) {
             oldDrawer = qt_mac_drawer_for(q);
         }
         if (wasWindow) {
             OSWindowRef oldWindow = qt_mac_window_for(old_id);
             oldToolbar = [oldWindow toolbar];
             if (oldToolbar) {
                 [oldToolbar retain];
                 oldToolbarVisible = [oldToolbar isVisible];
                 [oldWindow setToolbar:nil];
             }
         }
 #endif
     }
     QWidget* oldtlw = q->window();
     if (q->testAttribute(Qt::WA_DropSiteRegistered))
         q->setAttribute(Qt::WA_DropSiteRegistered, false);
     //recreate and setup flags
     QObjectPrivate::setParent_helper(parent);
     bool explicitlyHidden = q->testAttribute(Qt::WA_WState_Hidden) && q->testAttribute(Qt::WA_WState_ExplicitShowHide);
     if (wasCreated && !qt_isGenuineQWidget(q))
         return;
     if (!q->testAttribute(Qt::WA_WState_WindowOpacitySet)) {
         q->setWindowOpacity(1.0f);
         q->setAttribute(Qt::WA_WState_WindowOpacitySet, false);
     }
     setWinId(0); //do after the above because they may want the id
     data.window_flags = f;
     q->setAttribute(Qt::WA_WState_Created, false);
     q->setAttribute(Qt::WA_WState_Visible, false);
     q->setAttribute(Qt::WA_WState_Hidden, false);
     adjustFlags(data.window_flags, q);
     // keep compatibility with previous versions, we need to preserve the created state.
     // (but we recreate the winId for the widget being reparented, again for compatibility,
     // unless this is an alien widget. )
     const bool nonWindowWithCreatedParent = !q->isWindow() && parent->testAttribute(Qt::WA_WState_Created);
     const bool nativeWidget = q->internalWinId() != 0;
     if (wasCreated || (nativeWidget && nonWindowWithCreatedParent)) {
         createWinId();
         if (q->isWindow()) {
 #ifndef QT_MAC_USE_COCOA
             // We do this down below for wasCreated, so avoid doing this twice
             // (only for performance, it gets called a lot anyway).
             if (!wasCreated) {
                 if (QMainWindowLayout *mwl = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q))) {
                     mwl->updateHIToolBarStatus();
                 }
             }
 #else
             // Simply transfer our toolbar over. Everything should stay put, unlike in Carbon.
             if (oldToolbar && !(f & Qt::FramelessWindowHint)) {
                 OSWindowRef newWindow = qt_mac_window_for(q);
                 [newWindow setToolbar:oldToolbar];
                 [oldToolbar release];
                 [oldToolbar setVisible:oldToolbarVisible];
             }
 #endif
         }
     }
     if (q->isWindow() || (!parent || parent->isVisible()) || explicitlyHidden)
         q->setAttribute(Qt::WA_WState_Hidden);
     q->setAttribute(Qt::WA_WState_ExplicitShowHide, explicitlyHidden);
 #ifdef QT_MAC_USE_COCOA
     // If we add a child to the unified toolbar, we have to redirect the painting.
     if (parent && parent->d_func() && parent->d_func()->isInUnifiedToolbar) {
         if (parent->d_func()->unifiedSurface) {
             QWidget *toolbar = parent->d_func()->toolbar_ancestor;
             parent->d_func()->unifiedSurface->recursiveRedirect(toolbar, toolbar, toolbar->d_func()->toolbar_offset);
         }
     }
 #endif // QT_MAC_USE_COCOA
     if (wasCreated) {
         transferChildren();
 #ifndef QT_MAC_USE_COCOA
         // If we were a unified window, We just transfered our toolbars out of the unified toolbar.
         // So redo the status one more time. It apparently is not an issue with Cocoa.
         if (q->isWindow()) {
             if (QMainWindowLayout *mwl = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q))) {
                 mwl->updateHIToolBarStatus();
             }
         }
 #endif
         if (topData &&
                 (!topData->caption.isEmpty() || !topData->filePath.isEmpty()))
             setWindowTitle_helper(q->windowTitle());
     }
     if (q->testAttribute(Qt::WA_AcceptDrops)
         || (!q->isWindow() && q->parentWidget()
             && q->parentWidget()->testAttribute(Qt::WA_DropSiteRegistered)))
         q->setAttribute(Qt::WA_DropSiteRegistered, true);
     //cleanup
 #ifndef QT_MAC_USE_COCOA
     if (old_window_event)
         RemoveEventHandler(old_window_event);
 #endif
     if (old_id) { //don't need old window anymore
         OSWindowRef window = (oldtlw == q) ? qt_mac_window_for(old_id) : 0;
         qt_mac_destructView(old_id);
 #ifdef QT_MAC_USE_COCOA
         if (oldDrawer) {
             qt_mac_destructDrawer(oldDrawer);
         } else
 #endif
         if (window)
             qt_mac_destructWindow(window);
     }
     // Maintain the glWidgets list on parent change: add "our" gl widgets
     // to the list on the new parent and grandparents.
     if (glWidgets.isEmpty() == false) {
         QWidget *current = q->parentWidget();
         while (current) {
             current->d_func()->glWidgets += glWidgets;
             if (current->isWindow())
                 break;
             current = current->parentWidget();
         }
     }
     invalidateBuffer(q->rect());
     qt_event_request_window_change(q);
 }
setRedirected()
void QWidgetPrivate::setRedirected (QPaintDevice * replacement, const QPoint & offset) inline
Definition at line 621 of file qwidget_p.h.
     {
         Q_ASSERT(q_func()->testAttribute(Qt::WA_WState_InPaintEvent));
         redirectDev = replacement;
         redirectOffset = offset;
     }
setSharedPainter()
void QWidgetPrivate::setSharedPainter (QPainter * painter) inline
Definition at line 1022 of file qwidget_p.h.
 {
     Q_Q(QWidget);
     QTLWExtra *x = q->window()->d_func()->topData();
     x->sharedPainter = painter;
 }
setStyle_helper()
void QWidgetPrivate::setStyle_helper (QStyle * newStyle, bool propagate, bool metalHack = false)
Definition at line 2791 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     QStyle *oldStyle  = q->style();
 #ifndef QT_NO_STYLE_STYLESHEET
     QWeakPointer<QStyle> origStyle;
 #endif
 #ifdef Q_WS_MAC
     // the metalhack boolean allows Qt/Mac to do a proper re-polish depending
     // on how the Qt::WA_MacBrushedMetal attribute is set. It is only ever
     // set when changing that attribute and passes the widget's CURRENT style.
     // therefore no need to do a reassignment.
     if (!metalHack)
 #endif
     {
         createExtra();
 #ifndef QT_NO_STYLE_STYLESHEET
         origStyle = extra->style.data();
 #endif
         extra->style = newStyle;
     }
     // repolish
     if (q->windowType() != Qt::Desktop) {
         if (polished) {
             oldStyle->unpolish(q);
 #ifdef Q_WS_MAC
             if (metalHack)
                 macUpdateMetalAttribute();
 #endif
             q->style()->polish(q);
 #ifdef Q_WS_MAC
         } else if (metalHack) {
             macUpdateMetalAttribute();
 #endif
         }
     }
     if (propagate) {
         for (int i = 0; i < children.size(); ++i) {
             QWidget *c = qobject_cast<QWidget*>(children.at(i));
             if (c)
                 c->d_func()->inheritStyle();
         }
     }
 #ifndef QT_NO_STYLE_STYLESHEET
     if (!qobject_cast<QStyleSheetStyle*>(newStyle)) {
         if (const QStyleSheetStyle* cssStyle = qobject_cast<QStyleSheetStyle*>(origStyle.data())) {
             cssStyle->clearWidgetFont(q);
         }
     }
 #endif
     QEvent e(QEvent::StyleChange);
     QApplication::sendEvent(q, &e);
 #ifdef QT3_SUPPORT
     q->styleChange(*oldStyle);
 #endif
 #ifndef QT_NO_STYLE_STYLESHEET
     // dereference the old stylesheet style
     if (QStyleSheetStyle *proxy = qobject_cast<QStyleSheetStyle *>(origStyle.data()))
         proxy->deref();
 #endif
 }
setUpdatesEnabled_helper()
void QWidgetPrivate::setUpdatesEnabled_helper (bool enable)
Definition at line 1931 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (enable && !q->isWindow() && q->parentWidget() && !q->parentWidget()->updatesEnabled())
         return; // nothing we can do
     if (enable != q->testAttribute(Qt::WA_UpdatesDisabled))
         return; // nothing to do
     q->setAttribute(Qt::WA_UpdatesDisabled, !enable);
     if (enable)
         q->update();
     Qt::WidgetAttribute attribute = enable ? Qt::WA_ForceUpdatesDisabled : Qt::WA_UpdatesDisabled;
     for (int i = 0; i < children.size(); ++i) {
         QWidget *w = qobject_cast<QWidget *>(children.at(i));
         if (w && !w->isWindow() && !w->testAttribute(attribute))
             w->d_func()->setUpdatesEnabled_helper(enable);
     }
 }
setWindowFilePath_helper()
void QWidgetPrivate::setWindowFilePath_helper (const QString & filePath)
Definition at line 6461 of file qwidget.cpp.
Referenced by qt_mac_unregister_widget().
 {
     if (extra->topextra && extra->topextra->caption.isEmpty()) {
 #ifdef Q_WS_MAC
         setWindowTitle_helper(QFileInfo(filePath).fileName());
 #else
         Q_Q(QWidget);
         Q_UNUSED(filePath);
         setWindowTitle_helper(q->windowTitle());
 #endif
     }
 #ifdef Q_WS_MAC
     setWindowFilePath_sys(filePath);
 #endif
 }
setWindowIcon_helper()
void QWidgetPrivate::setWindowIcon_helper ()
Definition at line 6351 of file qwidget.cpp.
 {
     QEvent e(QEvent::WindowIconChange);
     QApplication::sendEvent(q_func(), &e);
     for (int i = 0; i < children.size(); ++i) {
         QWidget *w = qobject_cast<QWidget *>(children.at(i));
         if (w && !w->isWindow())
             QApplication::sendEvent(w, &e);
     }
 }
setWindowIcon_sys()
void QWidgetPrivate::setWindowIcon_sys (bool forceReset = false)
Definition at line 3228 of file qwidget_mac.mm.
Referenced by isServerProcess(), q_createNativeChildrenAndSetParent(), qstring_to_xtp(), and qt_createIcon().
 {
     Q_Q(QWidget);
     if (!q->testAttribute(Qt::WA_WState_Created))
         return;
     QTLWExtra *topData = this->topData();
     if (topData->iconPixmap && !forceReset) // already set
         return;
     QIcon icon = q->windowIcon();
     QPixmap *pm = 0;
     if (!icon.isNull()) {
         // now create the extra
         if (!topData->iconPixmap) {
             pm = new QPixmap(icon.pixmap(QSize(22, 22)));
             topData->iconPixmap = pm;
         } else {
             pm = topData->iconPixmap;
         }
     }
     if (q->isWindow()) {
 #ifndef QT_MAC_USE_COCOA
         IconRef previousIcon = 0;
         if (icon.isNull()) {
             RemoveWindowProxy(qt_mac_window_for(q));
             previousIcon = topData->windowIcon;
             topData->windowIcon = 0;
         } else {
             WindowClass wclass;
             GetWindowClass(qt_mac_window_for(q), &wclass);
             if (wclass == kDocumentWindowClass) {
                 IconRef newIcon = qt_mac_create_iconref(*pm);
                 previousIcon = topData->windowIcon;
                 topData->windowIcon = newIcon;
                 SetWindowProxyIcon(qt_mac_window_for(q), newIcon);
             }
         }
         // Release the previous icon if it was set by this function.
         if (previousIcon != 0)
             ReleaseIconRef(previousIcon);
 #else
         QMacCocoaAutoReleasePool pool;
         if (icon.isNull())
             return;
         NSButton *iconButton = [qt_mac_window_for(q) standardWindowButton:NSWindowDocumentIconButton];
         if (iconButton == nil) {
             QCFString string(q->windowTitle());
             const NSString *tmpString = reinterpret_cast<const NSString *>((CFStringRef)string);
             [qt_mac_window_for(q) setRepresentedURL:[NSURL fileURLWithPath:const_cast<NSString *>(tmpString)]];
             iconButton = [qt_mac_window_for(q) standardWindowButton:NSWindowDocumentIconButton];
         }
         if (icon.isNull()) {
             [iconButton setImage:nil];
         } else {
             QPixmap scaled = pm->scaled(QSize(16,16), Qt::KeepAspectRatio, Qt::SmoothTransformation);
             NSImage *image = static_cast<NSImage *>(qt_mac_create_nsimage(scaled));
             [iconButton setImage:image];
             [image release];
         }
 #endif
     }
 }
setWindowIconText_helper()
void QWidgetPrivate::setWindowIconText_helper (const QString & cap)
Definition at line 6292 of file qwidget.cpp.
Referenced by qt_mac_unregister_widget().
 {
     Q_Q(QWidget);
     if (q->testAttribute(Qt::WA_WState_Created))
         setWindowIconText_sys(qt_setWindowTitle_helperHelper(title, q));
 }
setWindowIconText_sys()
void QWidgetPrivate::setWindowIconText_sys (const QString & cap)
Definition at line 3295 of file qwidget_mac.mm.
Referenced by isServerProcess(), q_createNativeChildrenAndSetParent(), qstring_to_xtp(), and qt_createIcon().
 {
     Q_Q(QWidget);
     if(q->isWindow() && !iconText.isEmpty()) {
 #ifndef QT_MAC_USE_COCOA
         SetWindowAlternateTitle(qt_mac_window_for(q), QCFString(iconText));
 #else
         QMacCocoaAutoReleasePool pool;
         [qt_mac_window_for(q) setMiniwindowTitle:qt_mac_QStringToNSString(iconText)];
 #endif
     }
 }
setWindowOpacity_sys()
void QWidgetPrivate::setWindowOpacity_sys (qreal opacity)
Definition at line 5101 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), qt_grab_cursor(), and qt_tablet_cleanup_wce().
 {
     Q_Q(QWidget);
     if (!q->isWindow())
         return;
     level = qBound(0.0, level, 1.0);
     topData()->opacity = (uchar)(level * 255);
     if (!q->testAttribute(Qt::WA_WState_Created))
         return;
     OSWindowRef oswindow = qt_mac_window_for(q);
 #if QT_MAC_USE_COCOA
     [oswindow setAlphaValue:level];
 #else
     SetWindowAlpha(oswindow, level);
 #endif
 }
setWindowRole()
void QWidgetPrivate::setWindowRole ()
Definition at line 3015 of file qwidget_x11.cpp.
 {
     Q_Q(QWidget);
     if (!q->internalWinId())
         return;
     QByteArray windowRole = topData()->role.toUtf8();
     XChangeProperty(X11->display, q->internalWinId(),
                     ATOM(WM_WINDOW_ROLE), XA_STRING, 8, PropModeReplace,
                     (unsigned char *)windowRole.constData(), windowRole.length());
 }
setWindowTitle_helper()
void QWidgetPrivate::setWindowTitle_helper (const QString & cap)
Definition at line 6285 of file qwidget.cpp.
Referenced by QWidget::destroy(), isServerProcess(), qt_mac_unregister_widget(), and setParent_sys().
 {
     Q_Q(QWidget);
     if (q->testAttribute(Qt::WA_WState_Created))
         setWindowTitle_sys(qt_setWindowTitle_helperHelper(title, q));
 }
setWindowTitle_sys()
void QWidgetPrivate::setWindowTitle_sys (const QString & cap)
Definition at line 3173 of file qwidget_mac.mm.
Referenced by isServerProcess(), q_createNativeChildrenAndSetParent(), and qstring_to_xtp().
 {
     Q_Q(QWidget);
     if (q->isWindow()) {
 #ifndef QT_MAC_USE_COCOA
         SetWindowTitleWithCFString(qt_mac_window_for(q), QCFString(caption));
 #else
         QMacCocoaAutoReleasePool pool;
         [qt_mac_window_for(q) setTitle:qt_mac_QStringToNSString(caption)];
 #endif
     }
 }
setWinId()
void QWidgetPrivate::setWinId (WId id)
Definition at line 1726 of file qwidget.cpp.
Referenced by create_sys(), effectiveState(), isServerProcess(), q_createNativeChildrenAndSetParent(), qt_mac_unregister_widget(), qt_tablet_cleanup_wce(), and setParent_sys().
 {
     Q_Q(QWidget);
     // the user might create a widget with Qt::Desktop window
     // attribute (or create another QDesktopWidget instance), which
     // will have the same windowid (the root window id) as the
     // qt_desktopWidget. We should not add the second desktop widget
     // to the mapper.
     bool userDesktopWidget = qt_desktopWidget != 0 && qt_desktopWidget != q && q->windowType() == Qt::Desktop;
     if (mapper && data.winid && !userDesktopWidget) {
         mapper->remove(data.winid);
     }
     const WId oldWinId = data.winid;
     data.winid = id;
 #if defined(Q_WS_X11)
     hd = id; // X11: hd == ident
 #endif
     if (mapper && id && !userDesktopWidget) {
         mapper->insert(data.winid, q);
     }
     if(oldWinId != id) {
         QEvent e(QEvent::WinIdChange);
         QCoreApplication::sendEvent(q, &e);
     }
 }
sharedPainter()
QPainter * QWidgetPrivate::sharedPainter () const inline
Definition at line 1015 of file qwidget_p.h.
Referenced by render().
 {
     Q_Q(const QWidget);
     QTLWExtra *x = q->window()->d_func()->maybeTopData();
     return x ? x->sharedPainter : 0;
 }
show_helper()
void QWidgetPrivate::show_helper ()
Definition at line 7782 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     data.in_show = true; // qws optimization
     // make sure we receive pending move and resize events
     sendPendingMoveAndResizeEvents();
     // become visible before showing all children
     q->setAttribute(Qt::WA_WState_Visible);
     // finally show all children recursively
     showChildren(false);
 #ifdef QT3_SUPPORT
     if (q->parentWidget() && sendChildEvents)
         QApplication::sendPostedEvents(q->parentWidget(),
                                         QEvent::ChildInserted);
 #endif
     // popup handling: new popups and tools need to be raised, and
     // existing popups must be closed. Also propagate the current
     // windows's KeyboardFocusChange status.
     if (q->isWindow()) {
         if ((q->windowType() == Qt::Tool) || (q->windowType() == Qt::Popup) || q->windowType() == Qt::ToolTip) {
             q->raise();
             if (q->parentWidget() && q->parentWidget()->window()->testAttribute(Qt::WA_KeyboardFocusChange))
                 q->setAttribute(Qt::WA_KeyboardFocusChange);
         } else {
             while (QApplication::activePopupWidget()) {
                 if (!QApplication::activePopupWidget()->close())
                     break;
             }
         }
     }
     // Automatic embedding of child windows of widgets already embedded into
     // QGraphicsProxyWidget when they are shown the first time.
     bool isEmbedded = false;
 #ifndef QT_NO_GRAPHICSVIEW
     if (q->isWindow()) {
         isEmbedded = q->graphicsProxyWidget() ? true : false;
         if (!isEmbedded && !bypassGraphicsProxyWidget(q)) {
             QGraphicsProxyWidget *ancestorProxy = nearestGraphicsProxyWidget(q->parentWidget());
             if (ancestorProxy) {
                 isEmbedded = true;
                 ancestorProxy->d_func()->embedSubWindow(q);
             }
         }
     }
 #else
     Q_UNUSED(isEmbedded);
 #endif
     // On Windows, show the popup now so that our own focus handling
     // stores the correct old focus widget even if it's stolen in the
     // showevent
 #if defined(Q_WS_WIN) || defined(Q_WS_MAC) || defined(Q_OS_SYMBIAN)
     if (!isEmbedded && q->windowType() == Qt::Popup)
         qApp->d_func()->openPopup(q);
 #endif
     // send the show event before showing the window
     QShowEvent showEvent;
     QApplication::sendEvent(q, &showEvent);
     if (!isEmbedded && q->isModal() && q->isWindow())
         // QApplicationPrivate::enterModal *before* show, otherwise the initial
         // stacking might be wrong
         QApplicationPrivate::enterModal(q);
     show_sys();
 #if !defined(Q_WS_WIN) && !defined(Q_WS_MAC) && !defined(Q_OS_SYMBIAN)
     if (!isEmbedded && q->windowType() == Qt::Popup)
         qApp->d_func()->openPopup(q);
 #endif
 #ifndef QT_NO_ACCESSIBILITY
     if (q->windowType() != Qt::ToolTip)     // Tooltips are read aloud twice in MS narrator.
         QAccessible::updateAccessibility(q, 0, QAccessible::ObjectShow);
 #endif
     if (QApplicationPrivate::hidden_focus_widget == q) {
         QApplicationPrivate::hidden_focus_widget = 0;
         q->setFocus(Qt::OtherFocusReason);
     }
     // Process events when showing a Qt::SplashScreen widget before the event loop
     // is spinnning; otherwise it might not show up on particular platforms.
     // This makes QSplashScreen behave the same on all platforms.
     if (!qApp->d_func()->in_exec && q->windowType() == Qt::SplashScreen)
         QApplication::processEvents();
     data.in_show = false;  // reset qws optimization
 }
show_recursive()
void QWidgetPrivate::show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
Warning
This function is not part of the public interface.
It is only called for toplevels or widgets with visible parents.
Definition at line 7698 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     // polish if necessary
     if (!q->testAttribute(Qt::WA_WState_Created))
         createRecursively();
     q->ensurePolished();
 #ifdef QT3_SUPPORT
     if(sendChildEvents)
         QApplication::sendPostedEvents(q, QEvent::ChildInserted);
 #endif
     if (!q->isWindow() && q->parentWidget()->d_func()->layout && !q->parentWidget()->data->in_show)
         q->parentWidget()->d_func()->layout->activate();
     // activate our layout before we and our children become visible
     if (layout)
         layout->activate();
     show_helper();
 }
show_sys()
void QWidgetPrivate::show_sys ()
Platform-specific part of QWidget::show().
Warning
This function is not part of the public interface.
Definition at line 3440 of file qwidget_mac.mm.
Referenced by isServerProcess(), qstring_to_xtp(), qt_grab_cursor(), qt_mac_unregister_widget(), and qt_tablet_cleanup_wce().
 {
     Q_Q(QWidget);
     if ((q->windowType() == Qt::Desktop)) //desktop is always visible
         return;
     invalidateBuffer(q->rect());
     if (q->testAttribute(Qt::WA_OutsideWSRange))
         return;
     QMacCocoaAutoReleasePool pool;
     q->setAttribute(Qt::WA_Mapped);
     if (q->testAttribute(Qt::WA_DontShowOnScreen))
         return;
     bool realWindow = isRealWindow();
 #ifndef QT_MAC_USE_COCOA
     if (realWindow && !q->testAttribute(Qt::WA_Moved)) {
         if (qt_mac_is_macsheet(q))
             recreateMacWindow();
         q->createWinId();
         if (QWidget *p = q->parentWidget()) {
             p->createWinId();
             RepositionWindow(qt_mac_window_for(q), qt_mac_window_for(p), kWindowCenterOnParentWindow);
         } else {
             RepositionWindow(qt_mac_window_for(q), 0, kWindowCenterOnMainScreen);
         }
     }
 #endif
     data.fstrut_dirty = true;
     if (realWindow) {
         bool isCurrentlyMinimized = (q->windowState() & Qt::WindowMinimized);
         setModal_sys();
         OSWindowRef window = qt_mac_window_for(q);
 #ifndef QT_MAC_USE_COCOA
         SizeWindow(window, q->width(), q->height(), true);
 #endif
 #ifdef QT_MAC_USE_COCOA
         // Make sure that we end up sending a repaint event to
         // the widget if the window has been visible one before:
         [qt_mac_get_contentview_for(window) setNeedsDisplay:YES];
 #endif
         if(qt_mac_is_macsheet(q)) {
             qt_event_request_showsheet(q);
         } else if(qt_mac_is_macdrawer(q)) {
 #ifndef QT_MAC_USE_COCOA
             OpenDrawer(window, kWindowEdgeDefault, false);
 #else
             NSDrawer *drawer = qt_mac_drawer_for(q);
             [drawer openOnEdge:[drawer preferredEdge]];
 #endif
         } else {
 #ifndef QT_MAC_USE_COCOA
             ShowHide(window, true);
 #else
             // sync the opacity value back (in case of a fade).
             [window setAlphaValue:q->windowOpacity()];
             QWidget *top = 0;
             if (QApplicationPrivate::tryModalHelper(q, &top)) {
                 if (q->testAttribute(Qt::WA_ShowWithoutActivating))
                     [window orderFront:window];
                 else
                     [window makeKeyAndOrderFront:window];
                 // If this window is app modal, we need to start spinning
                 // a modal session for it. Interrupting
                 // the event dispatcher will make this happend:
                 if (data.window_modality == Qt::ApplicationModal)
                     QEventDispatcherMac::instance()->interrupt();
             } else {
                 // The window is modally shaddowed, so we need to make
                 // sure that we don't pop in front of the modal window:
                 [window orderFront:window];
                 if (!top->testAttribute(Qt::WA_DontShowOnScreen)) {
                     if (NSWindow *modalWin = qt_mac_window_for(top))
                         [modalWin orderFront:window];
                 }
             }
             setSubWindowStacking(true);
             qt_mac_update_cursor();
 #endif
             if (q->windowType() == Qt::Popup) {
                 qt_button_down = 0;
                 if (q->focusWidget())
                     q->focusWidget()->d_func()->setFocus_sys();
                 else
                     setFocus_sys();
             }
             toggleDrawers(true);
         }
         if (isCurrentlyMinimized) { //show in collapsed state
 #ifndef QT_MAC_USE_COCOA
             CollapseWindow(window, true);
 #else
             [window miniaturize:window];
 #endif
         } else if (!q->testAttribute(Qt::WA_ShowWithoutActivating)) {
 #ifndef QT_MAC_USE_COCOA
             qt_event_request_activate(q);
 #endif
         }
     } else if(topData()->embedded || !q->parentWidget() || q->parentWidget()->isVisible()) {
 #ifndef QT_MAC_USE_COCOA
         HIViewSetVisible(qt_mac_nativeview_for(q), true);
 #else
         if (NSView *view = qt_mac_nativeview_for(q)) {
             // INVARIANT: q is native. Just show the view:
             [view setHidden:NO];
         } else {
             // INVARIANT: q is alien. Update q instead:
             q->update();
         }
 #endif
     }
 #ifdef QT_MAC_USE_COCOA
     if ([NSApp isActive] && !qt_button_down && !QWidget::mouseGrabber()){
         // Update enter/leave immidiatly, don't wait for a move event. But only
         // if no grab exists (even if the grab points to this widget, it seems, ref X11)
         QPoint qlocal, qglobal;
         QWidget *widgetUnderMouse = 0;
         qt_mac_getTargetForMouseEvent(0, QEvent::Enter, qlocal, qglobal, 0, &widgetUnderMouse);
         if (q == widgetUnderMouse) {
             QApplicationPrivate::dispatchEnterLeave(widgetUnderMouse, qt_last_mouse_receiver);
             qt_last_mouse_receiver = widgetUnderMouse;
             qt_last_native_mouse_receiver = widgetUnderMouse ?
                 (widgetUnderMouse->internalWinId() ? widgetUnderMouse : widgetUnderMouse->nativeParentWidget()) : 0;
         }
     }
 #endif
     topLevelAt_cache = 0;
     qt_event_request_window_change(q);
 }
showChildren()
void QWidgetPrivate::showChildren (bool spontaneous)
Definition at line 8144 of file qwidget.cpp.
Referenced by QApplication::x11ProcessEvent().
 {
     QList<QObject*> childList = children;
     for (int i = 0; i < childList.size(); ++i) {
         QWidget *widget = qobject_cast<QWidget*>(childList.at(i));
         if (!widget
             || widget->isWindow()
             || widget->testAttribute(Qt::WA_WState_Hidden))
             continue;
         if (spontaneous) {
             widget->setAttribute(Qt::WA_Mapped);
             widget->d_func()->showChildren(true);
             QShowEvent e;
             QApplication::sendSpontaneousEvent(widget, &e);
         } else {
             if (widget->testAttribute(Qt::WA_WState_ExplicitShowHide))
                 widget->d_func()->show_recursive();
             else
                 widget->show();
         }
     }
 }
stackUnder_sys()
void QWidgetPrivate::stackUnder_sys (QWidget * w)
Definition at line 4051 of file qwidget_mac.mm.
Referenced by effectiveState(), qt_grab_cursor(), and setNetWmWindowTypes().
 {
     // stackUnder
     Q_Q(QWidget);
     if(!w || q->isWindow() || (q->windowType() == Qt::Desktop))
         return;
 #ifdef QT_MAC_USE_COCOA
     // Do the same trick as lower_sys() and put this widget before the widget passed in.
     NSView *myView = qt_mac_nativeview_for(q);
     NSView *wView = qt_mac_nativeview_for(w);
     QHash<NSView *, int> viewOrder;
     NSView *parentView = [myView superview];
     NSArray *subviews = [parentView subviews];
     NSUInteger index = 1;
     // make a hash of view->zorderindex and make sure z-value is always odd,
     // so that when we modify the order we create a new (even) z-value which
     // will not interfere with others.
     for (NSView *subview in subviews) {
         viewOrder.insert(subview, index * 2);
         ++index;
     }
     viewOrder[myView] = viewOrder[wView] - 1;
     [parentView sortSubviewsUsingFunction:compareViews2StackUnder context:reinterpret_cast<void *>(&viewOrder)];
 #else
     QWidget *p = q->parentWidget();
     if(!p || p != w->parentWidget())
         return;
     invalidateBuffer(q->rect());
     HIViewSetZOrder(qt_mac_nativeview_for(q), kHIViewZOrderBelow, qt_mac_nativeview_for(w));
     qt_event_request_window_change(q);
 #endif
 }
subtractOpaqueChildren()
void QWidgetPrivate::subtractOpaqueChildren (QRegion & rgn, const QRect & clipRect) const
Definition at line 2128 of file qwidget.cpp.
Referenced by QWidgetBackingStore::sync().
 {
     if (children.isEmpty() || clipRect.isEmpty())
         return;
     const QRegion &r = getOpaqueChildren();
     if (!r.isEmpty())
         source -= (r & clipRect);
 }
subtractOpaqueSiblings()
void QWidgetPrivate::subtractOpaqueSiblings (QRegion & source, bool * hasDirtySiblingsAbove = 0, bool alsoNonOpaque = false) const
Definition at line 2139 of file qwidget.cpp.
Referenced by QX11PaintEngine::begin(), scroll_sys(), QWidgetBackingStore::staticContents(), and QWidgetBackingStore::sync().
 {
     Q_Q(const QWidget);
     static int disableSubtractOpaqueSiblings = qgetenv("QT_NO_SUBTRACTOPAQUESIBLINGS").toInt();
     if (disableSubtractOpaqueSiblings || q->isWindow())
         return;
 #ifdef QT_MAC_USE_COCOA
     if (q->d_func()->isInUnifiedToolbar)
         return;
 #endif // QT_MAC_USE_COCOA
     QRect clipBoundingRect;
     bool dirtyClipBoundingRect = true;
     QRegion parentClip;
     bool dirtyParentClip = true;
     QPoint parentOffset = data.crect.topLeft();
     const QWidget *w = q;
     while (w) {
         if (w->isWindow())
             break;
         QWidgetPrivate *pd = w->parentWidget()->d_func();
         const int myIndex = pd->children.indexOf(const_cast<QWidget *>(w));
         const QRect widgetGeometry = w->d_func()->effectiveRectFor(w->data->crect);
         for (int i = myIndex + 1; i < pd->children.size(); ++i) {
             QWidget *sibling = qobject_cast<QWidget *>(pd->children.at(i));
             if (!sibling || !sibling->isVisible() || sibling->isWindow())
                 continue;
             const QRect siblingGeometry = sibling->d_func()->effectiveRectFor(sibling->data->crect);
             if (!qRectIntersects(siblingGeometry, widgetGeometry))
                 continue;
             if (dirtyClipBoundingRect) {
                 clipBoundingRect = sourceRegion.boundingRect();
                 dirtyClipBoundingRect = false;
             }
             if (!qRectIntersects(siblingGeometry, clipBoundingRect.translated(parentOffset)))
                 continue;
             if (dirtyParentClip) {
                 parentClip = sourceRegion.translated(parentOffset);
                 dirtyParentClip = false;
             }
             const QPoint siblingPos(sibling->data->crect.topLeft());
             const QRect siblingClipRect(sibling->d_func()->clipRect());
             QRegion siblingDirty(parentClip);
             siblingDirty &= (siblingClipRect.translated(siblingPos));
             const bool hasMask = sibling->d_func()->extra && sibling->d_func()->extra->hasMask
                                  && !sibling->d_func()->graphicsEffect;
             if (hasMask)
                 siblingDirty &= sibling->d_func()->extra->mask.translated(siblingPos);
             if (siblingDirty.isEmpty())
                 continue;
             if (sibling->d_func()->isOpaque || alsoNonOpaque) {
                 if (hasMask) {
                     siblingDirty.translate(-parentOffset);
                     sourceRegion -= siblingDirty;
                 } else {
                     sourceRegion -= siblingGeometry.translated(-parentOffset);
                 }
             } else {
                 if (hasDirtySiblingsAbove)
                     *hasDirtySiblingsAbove = true;
                 if (sibling->d_func()->children.isEmpty())
                     continue;
                 QRegion opaqueSiblingChildren(sibling->d_func()->getOpaqueChildren());
                 opaqueSiblingChildren.translate(-parentOffset + siblingPos);
                 sourceRegion -= opaqueSiblingChildren;
             }
             if (sourceRegion.isEmpty())
                 return;
             dirtyClipBoundingRect = true;
             dirtyParentClip = true;
         }
         w = w->parentWidget();
         parentOffset += pd->data.crect.topLeft();
         dirtyParentClip = true;
     }
 }
syncBackingStore() [1/2]
void QWidgetPrivate::syncBackingStore ()
Definition at line 1912 of file qwidget.cpp.
 {
     if (paintOnScreen()) {
         repaint_sys(dirty);
         dirty = QRegion();
     } else if (QWidgetBackingStore *bs = maybeBackingStore()) {
         bs->sync();
     }
 }
syncBackingStore() [2/2]
void QWidgetPrivate::syncBackingStore (const QRegion & region)
Definition at line 1922 of file qwidget.cpp.
 {
     if (paintOnScreen())
         repaint_sys(region);
     else if (QWidgetBackingStore *bs = maybeBackingStore()) {
         bs->sync(q_func(), region);
     }
 }
topData()
QTLWExtra * QWidgetPrivate::topData () const inline
Definition at line 1004 of file qwidget_p.h.
Referenced by create_sys(), createDefaultWindowSurface_sys(), QWidget::destroy(), effectiveState(), isServerProcess(), QPlatformScreen::platformScreenForWidget(), q_createNativeChildrenAndSetParent(), qt_createIcon(), qt_grab_cursor(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), setConstraints_sys(), setGeometry_sys(), setParent_sys(), setWindowIcon_sys(), setWindowOpacity_sys(), show_sys(), updateFrameStrut(), and QApplication::x11ProcessEvent().
 {
     const_cast<QWidgetPrivate *>(this)->createTLExtra();
     return extra->topextra;
 }
unsetCursor_sys()
void QWidgetPrivate::unsetCursor_sys ()
Definition at line 3168 of file qwidget_mac.mm.
Referenced by isServerProcess(), mapFromGlobal(), and q_createNativeChildrenAndSetParent().
 {
     qt_mac_update_cursor();
 }
updateFont()
void QWidgetPrivate::updateFont (const QFont & font)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
Warning
This function is not part of the public interface.
implicitMask is the union of all ancestor widgets' font request masks, and determines which attributes from this widget's font should propagate.
Definition at line 5093 of file qwidget.cpp.
 {
     Q_Q(QWidget);
 #ifndef QT_NO_STYLE_STYLESHEET
     const QStyleSheetStyle* cssStyle;
     cssStyle = extra ? qobject_cast<const QStyleSheetStyle*>(extra->style) : 0;
 #endif
 #ifdef QT3_SUPPORT
     QFont old = data.fnt;
 #endif
     data.fnt = QFont(font, q);
 #if defined(Q_WS_X11)
     // make sure the font set on this widget is associated with the correct screen
     data.fnt.x11SetScreen(xinfo.screen());
 #endif
     // Combine new mask with natural mask and propagate to children.
 #ifndef QT_NO_GRAPHICSVIEW
     if (!q->parentWidget() && extra && extra->proxyWidget) {
         QGraphicsProxyWidget *p = extra->proxyWidget;
         inheritedFontResolveMask = p->d_func()->inheritedFontResolveMask | p->font().resolve();
     } else
 #endif //QT_NO_GRAPHICSVIEW
     if (q->isWindow() && !q->testAttribute(Qt::WA_WindowPropagation)) {
         inheritedFontResolveMask = 0;
     }
     uint newMask = data.fnt.resolve() | inheritedFontResolveMask;
     for (int i = 0; i < children.size(); ++i) {
         QWidget *w = qobject_cast<QWidget*>(children.at(i));
         if (w) {
             if (0) {
 #ifndef QT_NO_STYLE_STYLESHEET
             } else if (w->testAttribute(Qt::WA_StyleSheet)) {
                 // Style sheets follow a different font propagation scheme.
                 if (cssStyle)
                     cssStyle->updateStyleSheetFont(w);
 #endif
             } else if ((!w->isWindow() || w->testAttribute(Qt::WA_WindowPropagation))) {
                 // Propagate font changes.
                 QWidgetPrivate *wd = w->d_func();
                 wd->inheritedFontResolveMask = newMask;
                 wd->resolveFont();
             }
         }
     }
 #ifndef QT_NO_STYLE_STYLESHEET
     if (cssStyle) {
         cssStyle->updateStyleSheetFont(q);
     }
 #endif
     QEvent e(QEvent::FontChange);
     QApplication::sendEvent(q, &e);
 #ifdef QT3_SUPPORT
     q->fontChange(old);
 #endif
 }
updateFrameStrut()
void QWidgetPrivate::updateFrameStrut ()
Computes the frame rectangle when needed.
Warning
This function is not part of the public interface.
This is an internal function, you should never call this.
Definition at line 4999 of file qwidget_mac.mm.
Referenced by do_size_hints(), effectiveState(), macWindowToolbarShow(), qt_grab_cursor(), qt_mac_unregister_widget(), and qt_tablet_cleanup_wce().
 {
     Q_Q(QWidget);
     QWidgetPrivate *that = const_cast<QWidgetPrivate*>(this);
     that->data.fstrut_dirty = false;
     QTLWExtra *top = that->topData();
 #if QT_MAC_USE_COCOA
     // 1 Get the window frame
     OSWindowRef oswnd = qt_mac_window_for(q);
     NSRect frameW = [oswnd frame];
     // 2 Get the content frame - so now
     NSRect frameC = [oswnd contentRectForFrameRect:frameW];
     top->frameStrut.setCoords(frameC.origin.x - frameW.origin.x,
                               (frameW.origin.y + frameW.size.height) - (frameC.origin.y + frameC.size.height),
                               (frameW.origin.x + frameW.size.width) - (frameC.origin.x + frameC.size.width),
                               frameC.origin.y - frameW.origin.y);
 #else
     Rect window_r;
     GetWindowStructureWidths(qt_mac_window_for(q), &window_r);
     top->frameStrut.setCoords(window_r.left, window_r.top, window_r.right, window_r.bottom);
 #endif
 }
updateGeometry_helper()
void QWidgetPrivate::updateGeometry_helper (bool forceUpdate)
Definition at line 10346 of file qwidget.cpp.
 {
     Q_Q(QWidget);
     if (widgetItem)
         widgetItem->invalidateSizeCache();
     QWidget *parent;
     if (forceUpdate || !extra || extra->minw != extra->maxw || extra->minh != extra->maxh) {
         if (!q->isWindow() && !q->isHidden() && (parent = q->parentWidget())) {
             if (parent->d_func()->layout)
                 parent->d_func()->layout->invalidate();
             else if (parent->isVisible())
                 QApplication::postEvent(parent, new QEvent(QEvent::LayoutRequest));
         }
     }
 }
updateIsOpaque()
void QWidgetPrivate::updateIsOpaque ()
Definition at line 2272 of file qwidget.cpp.
Referenced by create_sys().
 {
     // hw: todo: only needed if opacity actually changed
     setDirtyOpaqueRegion();
 #ifndef QT_NO_GRAPHICSEFFECT
     if (graphicsEffect) {
         // ### We should probably add QGraphicsEffect::isOpaque at some point.
         setOpaque(false);
         return;
     }
 #endif //QT_NO_GRAPHICSEFFECT
     Q_Q(QWidget);
 #ifdef Q_WS_X11
     if (q->testAttribute(Qt::WA_X11OpenGLOverlay)) {
         setOpaque(false);
         return;
     }
 #endif
 #ifdef Q_WS_S60
     if (q->testAttribute(Qt::WA_TranslucentBackground)) {
         if (q->windowType() & Qt::Dialog || q->windowType() & Qt::Popup) {
             if (S60->avkonComponentsSupportTransparency) {
                 setOpaque(false);
                 return;
             }
         } else {
             setOpaque(false);
             return;
         }
     }
 #endif
     if (q->testAttribute(Qt::WA_OpaquePaintEvent) || q->testAttribute(Qt::WA_PaintOnScreen)) {
         setOpaque(true);
         return;
     }
     const QPalette &pal = q->palette();
     if (q->autoFillBackground()) {
         const QBrush &autoFillBrush = pal.brush(q->backgroundRole());
         if (autoFillBrush.style() != Qt::NoBrush && autoFillBrush.isOpaque()) {
             setOpaque(true);
             return;
         }
     }
     if (q->isWindow() && !q->testAttribute(Qt::WA_NoSystemBackground)) {
 #ifdef Q_WS_S60
         setOpaque(true);
         return;
 #else
         const QBrush &windowBrush = q->palette().brush(QPalette::Window);
         if (windowBrush.style() != Qt::NoBrush && windowBrush.isOpaque()) {
             setOpaque(true);
             return;
         }
 #endif
     }
     setOpaque(false);
 }
updateIsTranslucent()
void QWidgetPrivate::updateIsTranslucent ()
Definition at line 2356 of file qwidget.cpp.
 {
 #ifdef Q_WS_MAC
     macUpdateIsOpaque();
 #endif
 #ifdef Q_WS_X11
     x11UpdateIsOpaque();
 #endif
 #ifdef Q_WS_WIN
     winUpdateIsOpaque();
 #endif
 #ifdef Q_OS_SYMBIAN
     s60UpdateIsOpaque();
 #endif
 }
updateSystemBackground()
void QWidgetPrivate::updateSystemBackground ()
Definition at line 3159 of file qwidget_mac.mm.
Referenced by isServerProcess(), mapFromGlobal(), and q_createNativeChildrenAndSetParent().
 {
 }
updateX11AcceptFocus()
void QWidgetPrivate::updateX11AcceptFocus ()
Definition at line 3138 of file qwidget_x11.cpp.
 {
     Q_Q(QWidget);
     if (!q->isWindow() || !q->internalWinId())
         return;
     XWMHints *h = XGetWMHints(X11->display, q->internalWinId());
     XWMHints wm_hints;
     if (!h) {
         memset(&wm_hints, 0, sizeof(wm_hints)); // make valgrind happy
         h = &wm_hints;
     }
     h->flags |= InputHint;
     h->input = q->testAttribute(Qt::WA_X11DoNotAcceptFocus) ? False : True;
     XSetWMHints(X11->display, q->internalWinId(), h);
     if (h != &wm_hints)
         XFree((char *)h);
 }
x11UpdateIsOpaque()
void QWidgetPrivate::x11UpdateIsOpaque ()
Definition at line 999 of file qwidget_x11.cpp.
 {
 #ifndef QT_NO_XRENDER
     Q_Q(QWidget);
     if (!q->testAttribute(Qt::WA_WState_Created) || !q->testAttribute(Qt::WA_TranslucentBackground))
         return;
     bool topLevel = (data.window_flags & Qt::Window);
     int screen = xinfo.screen();
     if (topLevel && X11->use_xrender
         && X11->argbVisuals[screen] && xinfo.depth() != 32)
     {
         qt_x11_recreateNativeWidgetsRecursive(q);
     }
 #endif
 }
Properties
accessibleDescription
QString QWidgetPrivate::accessibleDescription
Definition at line 738 of file qwidget_p.h.
accessibleName
QString QWidgetPrivate::accessibleName
Definition at line 737 of file qwidget_p.h.
actions
QList<QAction*> QWidgetPrivate::actions
Definition at line 760 of file qwidget_p.h.
Referenced by QMenuPrivate::actionAt(), QMenuPrivate::actionRect(), QMenuPrivate::getLastVisibleAction(), QToolButtonPrivate::hasMenu(), QMenuBarPrivate::QWceMenuBarPrivate::rebuild(), QFileDialogPrivate::retranslateStrings(), QMenuPrivate::scrollMenu(), QMenuPrivate::setFirstActionActive(), and QMenuPrivate::updateActionRects().
allWidgets
QWidgetSet * QWidgetPrivate::allWidgets = 0 static
Definition at line 715 of file qwidget_p.h.
Referenced by QApplication::allWidgets(), QX11Data::clipboardReadIncrementalProperty(), QApplicationPrivate::initialize(), QClipboardData::QClipboardData(), qt_tablet_init(), QWidget::setAutoFillBackground(), setupOwner(), QGLGlobalShareWidget::shareWidget(), QWindowsXPStylePrivate::winId(), and QApplication::~QApplication().
bg_role
QPalette::ColorRole QWidgetPrivate::bg_role
Definition at line 769 of file qwidget_p.h.
bottomLayoutItemMargin
signed char QWidgetPrivate::bottomLayoutItemMargin
Definition at line 751 of file qwidget_p.h.
Referenced by fromLayoutItemRect(), and toLayoutItemRect().
bottommargin
short QWidgetPrivate::bottommargin
Definition at line 747 of file qwidget_p.h.
Referenced by QLayout::totalHeightForWidth(), QLayout::totalMaximumSize(), QLayout::totalMinimumSize(), and QLayout::totalSizeHint().
data
QWidgetData QWidgetPrivate::data
Definition at line 755 of file qwidget_p.h.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsAboutToBeRemoved(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsInserted(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), QFileDialogPrivate::_q_useNameFilter(), clipToEffectiveMask(), create_sys(), QLineEditPrivate::drag(), effectiveState(), hide_sys(), QDesktopWidgetPrivate::init(), QIconModeViewBase::intersectingSet(), isOverlapped(), isServerProcess(), QWidget::mapFromGlobal(), QWidget::mapToGlobal(), QWidget::metric(), q_createNativeChildrenAndSetParent(), qt_grab_cursor(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), qt_tablet_cleanup_wce(), scroll_sys(), setGeometry_sys(), setModal_sys(), setParent_sys(), QTextBrowserPrivate::setSource(), QWidget::setWindowState(), show_sys(), subtractOpaqueSiblings(), QWidgetBackingStore::sync(), QMenuPrivate::QMacMenuPrivate::syncAction(), updateFrameStrut(), and QWidgetBackingStore::updateStaticContentsSize().
dirty
QRegion QWidgetPrivate::dirty
Definition at line 726 of file qwidget_p.h.
Referenced by QWidgetBackingStore::addDirtyWidget(), and QWidgetBackingStore::sync().
dirtyOpaqueChildren
uint QWidgetPrivate::dirtyOpaqueChildren
Definition at line 770 of file qwidget_p.h.
Referenced by getOpaqueChildren(), and setDirtyOpaqueRegion().
extra
QWExtra* QWidgetPrivate::extra
Definition at line 700 of file qwidget_p.h.
Referenced by QLayout::activate(), clipToEffectiveMask(), create_sys(), createSysExtra(), createTLSysExtra(), deleteSysExtra(), deleteTLSysExtra(), QWidget::destroy(), QWidgetEffectSourcePrivate::draw(), effectiveState(), getOpaqueChildren(), isServerProcess(), QTabBarPrivate::layoutTabs(), paintSiblingsRecursive(), qt_grab_cursor(), qt_mac_unregister_widget(), qt_mac_update_widget_position(), qt_tablet_cleanup_wce(), render(), setConstraints_sys(), setGeometry_sys(), setMask_sys(), setWindowOpacity_sys(), QWidget::setWindowState(), QWidget::setWindowTitle(), QWidgetBackingStore::staticContents(), QGL2PaintEngineExPrivate::systemStateChanged(), QOpenGLPaintEngine::updateClipRegion(), updateRedirectedToGraphicsProxyWidget(), QWidgetBackingStore::updateStaticContentsSize(), and ~QWidgetPrivate().
extraPaintEngine
QPaintEngine* QWidgetPrivate::extraPaintEngine
Definition at line 708 of file qwidget_p.h.
fg_role
QPalette::ColorRole QWidgetPrivate::fg_role
Definition at line 768 of file qwidget_p.h.
focus_child
QWidget* QWidgetPrivate::focus_child
Definition at line 703 of file qwidget_p.h.
focus_next
QWidget* QWidgetPrivate::focus_next
Definition at line 701 of file qwidget_p.h.
Referenced by QWidgetExceptionCleaner::cleanup().
focus_prev
QWidget* QWidgetPrivate::focus_prev
Definition at line 702 of file qwidget_p.h.
Referenced by QWidgetExceptionCleaner::cleanup().
gestureContext
QMap<Qt::GestureType, Qt::GestureFlags> QWidgetPrivate::gestureContext
Definition at line 763 of file qwidget_p.h.
Referenced by QApplication::notify().
graphicsEffect
QGraphicsEffect* QWidgetPrivate::graphicsEffect
Definition at line 710 of file qwidget_p.h.
Referenced by QWidgetBackingStore::addDirtyWidget(), paintSiblingsRecursive(), and ~QWidgetPrivate().
hd
Qt::HANDLE QWidgetPrivate::hd
Definition at line 754 of file qwidget_p.h.
Referenced by create_sys(), qt_grab_cursor(), and qt_tablet_cleanup_wce().
high_attributes
uint QWidgetPrivate::high_attributes[4]
Definition at line 767 of file qwidget_p.h.
Referenced by QWidgetPrivate(), and setAttribute_internal().
ic
QPointer<QInputContext> QWidgetPrivate::ic
Definition at line 717 of file qwidget_p.h.
Referenced by QDateTimeEditPrivate::validateAndInterpret().
imHints
Qt::InputMethodHints QWidgetPrivate::imHints
Definition at line 718 of file qwidget_p.h.
Referenced by QWidget::inputMethodQuery().
inDirtyList
uint QWidgetPrivate::inDirtyList
Definition at line 772 of file qwidget_p.h.
Referenced by QWidgetBackingStore::addDirtyWidget().
inheritedFontResolveMask
uint QWidgetPrivate::inheritedFontResolveMask
Definition at line 742 of file qwidget_p.h.
Referenced by QGraphicsProxyWidget::event(), and updateFont().
inheritedPaletteResolveMask
uint QWidgetPrivate::inheritedPaletteResolveMask
Definition at line 743 of file qwidget_p.h.
Referenced by QGraphicsProxyWidget::event(), and propagatePaletteChange().
inheritsInputMethodHints
uint QWidgetPrivate::inheritsInputMethodHints
Definition at line 778 of file qwidget_p.h.
Referenced by QInputDialogPrivate::ensureComboBox(), QInputDialogPrivate::ensureLineEdit(), and QWidget::inputMethodQuery().
inSetParent
uint QWidgetPrivate::inSetParent
Definition at line 780 of file qwidget_p.h.
instanceCounter
int QWidgetPrivate::instanceCounter = 0 static
Definition at line 752 of file qwidget_p.h.
Referenced by init(), QApplication::~QApplication(), and QWidget::~QWidget().
isGLWidget
uint QWidgetPrivate::isGLWidget
Definition at line 775 of file qwidget_p.h.
Referenced by qt_reg_winclass().
isMoved
uint QWidgetPrivate::isMoved
Definition at line 774 of file qwidget_p.h.
Referenced by moveRect(), and QWidgetBackingStore::sync().
isOpaque
uint QWidgetPrivate::isOpaque
Definition at line 771 of file qwidget_p.h.
Referenced by QVGGraphicsSystem::createWindowSurface(), QGLGraphicsSystem::createWindowSurface(), getOpaqueChildren(), QPixmap::grabWidget(), paintSiblingsRecursive(), qt_grab_cursor(), scroll_sys(), QRasterWindowSurface::setGeometry(), QWidgetBackingStore::staticContents(), QWidgetBackingStore::sync(), and updateRedirectedToGraphicsProxyWidget().
isScrolled
uint QWidgetPrivate::isScrolled
Definition at line 773 of file qwidget_p.h.
Referenced by QWidgetBackingStore::sync().
keyboardGrabber
QWidget * QWidgetPrivate::keyboardGrabber = 0 static
Definition at line 787 of file qwidget_p.h.
Referenced by qstring_to_xtp().
layout
QLayout* QWidgetPrivate::layout
Definition at line 704 of file qwidget_p.h.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), activateChildLayoutsRecursively(), QCommandLinkButtonPrivate::descriptionHeight(), QDockWidgetItem::dockWidgetChildItem(), documentSize(), QPlainTextEditPrivate::init(), QMdiSubWindowPrivate::removeBaseWidget(), setModal_sys(), and QMdiSubWindowPrivate::setSizeGrip().
leftLayoutItemMargin
signed char QWidgetPrivate::leftLayoutItemMargin
Definition at line 748 of file qwidget_p.h.
Referenced by fromLayoutItemRect(), and toLayoutItemRect().
leftmargin
short QWidgetPrivate::leftmargin
Definition at line 744 of file qwidget_p.h.
Referenced by QLayout::totalHeightForWidth(), QLayout::totalMaximumSize(), QLayout::totalMinimumSize(), QLayout::totalSizeHint(), and QMenuPrivate::updateActionRects().
locale
QLocale QWidgetPrivate::locale
Definition at line 757 of file qwidget_p.h.
mapper
QWidgetMapper * QWidgetPrivate::mapper = 0 static
Definition at line 714 of file qwidget_p.h.
Referenced by QApplicationPrivate::applyX11SpecificCommandLineArguments(), QApplicationPrivate::initialize(), QWidget::nativeParentWidget(), qt_tablet_cleanup_wce(), QWidget::setAutoFillBackground(), and QApplication::~QApplication().
maxInstances
int QWidgetPrivate::maxInstances = 0 static
Definition at line 753 of file qwidget_p.h.
Referenced by init(), QApplication::~QApplication(), and QWidget::~QWidget().
mouseGrabber
QWidget * QWidgetPrivate::mouseGrabber = 0 static
Definition at line 786 of file qwidget_p.h.
Referenced by qstring_to_xtp().
needsFlush
QRegion* QWidgetPrivate::needsFlush
Definition at line 705 of file qwidget_p.h.
Referenced by QWidgetBackingStore::dirtyRegion(), QWidgetBackingStore::flush(), and QWidgetBackingStore::markDirtyOnScreen().
opaqueChildren
QRegion QWidgetPrivate::opaqueChildren
Definition at line 725 of file qwidget_p.h.
Referenced by getOpaqueChildren().
picture
Qt::HANDLE QWidgetPrivate::picture
Definition at line 785 of file qwidget_p.h.
polished
const QMetaObject* QWidgetPrivate::polished mutable
Definition at line 709 of file qwidget_p.h.
redirectDev
QPaintDevice* QWidgetPrivate::redirectDev
Definition at line 706 of file qwidget_p.h.
Referenced by QPainter::redirected().
redirectOffset
QPoint QWidgetPrivate::redirectOffset
Definition at line 758 of file qwidget_p.h.
rightLayoutItemMargin
signed char QWidgetPrivate::rightLayoutItemMargin
Definition at line 750 of file qwidget_p.h.
Referenced by fromLayoutItemRect(), and toLayoutItemRect().
rightmargin
short QWidgetPrivate::rightmargin
Definition at line 746 of file qwidget_p.h.
Referenced by QLayout::totalHeightForWidth(), QLayout::totalMaximumSize(), QLayout::totalMinimumSize(), QLayout::totalSizeHint(), and QMenuPrivate::updateActionRects().
size_policy
QSizePolicy QWidgetPrivate::size_policy
Definition at line 756 of file qwidget_p.h.
Referenced by QTabWidgetPrivate::hasHeightForWidth().
statusTip
QString QWidgetPrivate::statusTip
Definition at line 731 of file qwidget_p.h.
toolTip
QString QWidgetPrivate::toolTip
Definition at line 728 of file qwidget_p.h.
topLayoutItemMargin
signed char QWidgetPrivate::topLayoutItemMargin
Definition at line 749 of file qwidget_p.h.
Referenced by fromLayoutItemRect(), and toLayoutItemRect().
topmargin
short QWidgetPrivate::topmargin
Definition at line 745 of file qwidget_p.h.
Referenced by QLayout::totalHeightForWidth(), QLayout::totalMaximumSize(), QLayout::totalMinimumSize(), QLayout::totalSizeHint(), and QMenuPrivate::updateActionRects().
usesDoubleBufferedGLContext
uint QWidgetPrivate::usesDoubleBufferedGLContext
Definition at line 776 of file qwidget_p.h.
whatsThis
QString QWidgetPrivate::whatsThis
Definition at line 734 of file qwidget_p.h.
Referenced by QMenuPrivate::activateAction().
widgetItem
QWidgetItemV2* QWidgetPrivate::widgetItem
Definition at line 707 of file qwidget_p.h.
Referenced by QWidgetItemV2::QWidgetItemV2(), QWidgetItemV2::~QWidgetItemV2(), and ~QWidgetPrivate().
xinfo
QX11Info QWidgetPrivate::xinfo
Definition at line 784 of file qwidget_p.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qwidget_p.h
/src/gui/kernel/qwidget.cpp
/src/gui/kernel/qwidget_mac.mm
/src/gui/kernel/qwidget_qpa.cpp
/src/gui/kernel/qwidget_qws.cpp
/src/gui/kernel/qwidget_win.cpp
/src/gui/kernel/qwidget_wince.cpp
/src/gui/kernel/qwidget_x11.cpp
/src/gui/painting/qbackingstore.cpp