Qt 4.8: QScriptDebuggerLocalsModelPrivate Class Reference
QScriptDebuggerLocalsModelPrivate Class Reference
Public Functions
void addChildren (const QModelIndex &parentIndex, QScriptDebuggerLocalsModelNode *parentNode, const QScriptDebuggerValuePropertyList &props)
QModelIndex addTopLevelObject (const QString &name, const QScriptDebuggerValue &object)
void deleteAllObjectSnapshots ()
void deleteObjectSnapshots (const QList< qint64 > &snapshotIds)
void depopulate (QScriptDebuggerLocalsModelNode *node)
void emitDataChanged (const QModelIndex &tl, const QModelIndex &br)
void emitScopeObjectAvailable (const QModelIndex &index)
QModelIndex indexFromNode (QScriptDebuggerLocalsModelNode *node) const
bool isTopLevelNode (QScriptDebuggerLocalsModelNode *node) const
QScriptDebuggerLocalsModelNode * nodeFromIndex (const QModelIndex &index) const
void populateIndex (const QModelIndex &index)
QScriptDebuggerLocalsModelPrivate ()
void reallyPopulateIndex (const QModelIndex &index, const QScriptDebuggerValuePropertyList &props)
void reallySyncIndex (const QModelIndex &index, const QScriptDebuggerObjectSnapshotDelta &delta)
void removeChild (const QModelIndex &parentIndex, QScriptDebuggerLocalsModelNode *parentNode, int row)
void removeTopLevelNodes ()
void repopulate (QScriptDebuggerLocalsModelNode *node)
void syncIndex (const QModelIndex &index)
void syncTopLevelNodes ()
~QScriptDebuggerLocalsModelPrivate ()
Public Functions inherited from QAbstractItemModelPrivate
bool allowMove (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
Returns whether a move operation is valid.
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
QModelIndex createIndex (int row, int column, void *data=0) const
QModelIndex createIndex (int row, int column, int id) const
bool indexValid (const QModelIndex &index) const
void invalidatePersistentIndex (const QModelIndex &index)
void invalidatePersistentIndexes ()
void itemsAboutToBeMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation)
void itemsMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
void movePersistentIndexes (QVector< QPersistentModelIndexData *> indexes, int change, const QModelIndex &parent, Qt::Orientation orientation)
Moves persistent indexes indexes by amount change.
QAbstractItemModelPrivate ()
void removePersistentIndexData (QPersistentModelIndexData *data)
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QScriptDebuggerLocalsModelPrivate * get (QScriptDebuggerLocalsModel *q)
Static Public Functions inherited from QAbstractItemModelPrivate
static const QHash< int, QByteArray > & defaultRoleNames ()
static QAbstractItemModel * staticEmptyModel ()
static bool variantLessThan (const QVariant &v1, const QVariant &v2)
This function is used by our Q{Tree,Widget,Table}WidgetModel classes to sort.
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QScriptDebuggerCommandSchedulerInterface * commandScheduler
int frameIndex
QScriptDebuggerLocalsModelNode * invisibleRootNode
QScriptDebuggerJobSchedulerInterface * jobScheduler
Public Variables inherited from QAbstractItemModelPrivate
QStack< Change > changes
struct QAbstractItemModelPrivate::Persistent persistent
QHash< int, QByteArray > roleNames
Qt::DropActions supportedDragActions
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 105 of file qscriptdebuggerlocalsmodel.cpp.
Constructors and Destructors
QScriptDebuggerLocalsModelPrivate()
QScriptDebuggerLocalsModelPrivate::QScriptDebuggerLocalsModelPrivate ()
Definition at line 149 of file qscriptdebuggerlocalsmodel.cpp.
 {
     invisibleRootNode = new QScriptDebuggerLocalsModelNode();
     frameIndex = -1;
 }
~QScriptDebuggerLocalsModelPrivate()
QScriptDebuggerLocalsModelPrivate::~QScriptDebuggerLocalsModelPrivate ()
Definition at line 155 of file qscriptdebuggerlocalsmodel.cpp.
 {
     delete invisibleRootNode;
 }
Functions
addChildren()
void QScriptDebuggerLocalsModelPrivate::addChildren (const QModelIndex & parentIndex, QScriptDebuggerLocalsModelNode * parentNode, const QScriptDebuggerValuePropertyList & props)
Definition at line 224 of file qscriptdebuggerlocalsmodel.cpp.
 {
     Q_Q(QScriptDebuggerLocalsModel);
     if (props.isEmpty())
         return;
     int first = parentNode->children.size();
     int last = first + props.size() - 1;
     q->beginInsertRows(parentIndex, first, last);
     for (int i = 0; i < props.size(); ++i)
         new QScriptDebuggerLocalsModelNode(props.at(i), parentNode);
     q->endInsertRows();
 }
addTopLevelObject()
QModelIndex QScriptDebuggerLocalsModelPrivate::addTopLevelObject (const QString & name, const QScriptDebuggerValue & object)
Definition at line 459 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by addTopLevelObject(), and QScriptDebuggerLocalsModel::init().
 {
     Q_Q(QScriptDebuggerLocalsModel);
     QScriptDebuggerLocalsModelNode *node = invisibleRootNode->findChild(name);
     if (node)
         return indexFromNode(node);
     QScriptDebuggerValueProperty prop(name, object,
                                       QString::fromLatin1(""), // ### string representation of object
                                       /*flags=*/0);
     int rowIndex = invisibleRootNode->children.size();
     q->beginInsertRows(QModelIndex(), rowIndex, rowIndex);
     node = new QScriptDebuggerLocalsModelNode(prop, invisibleRootNode);
     q->endInsertRows();
     return indexFromNode(node);
 }
deleteAllObjectSnapshots()
void QScriptDebuggerLocalsModelPrivate::deleteAllObjectSnapshots ()
Definition at line 246 of file qscriptdebuggerlocalsmodel.cpp.
 {
     QList<qint64> snapshotIds;
     for (int i = 0; i < invisibleRootNode->children.count(); ++i)
         snapshotIds += findSnapshotIdsRecursively(invisibleRootNode->children.at(i));
     deleteObjectSnapshots(snapshotIds);
 }
deleteObjectSnapshots()
void QScriptDebuggerLocalsModelPrivate::deleteObjectSnapshots (const QList< qint64 > & snapshotIds)
Definition at line 239 of file qscriptdebuggerlocalsmodel.cpp.
 {
     QScriptDebuggerCommandSchedulerFrontend frontend(commandScheduler, 0);
     for (int i = 0; i < snapshotIds.size(); ++i)
         frontend.scheduleDeleteScriptObjectSnapshot(snapshotIds.at(i));
 }
depopulate()
void QScriptDebuggerLocalsModelPrivate::depopulate (QScriptDebuggerLocalsModelNode * node)
Definition at line 199 of file qscriptdebuggerlocalsmodel.cpp.
 {
     Q_Q(QScriptDebuggerLocalsModel);
     bool hasChildren = !node->children.isEmpty();
     if (hasChildren)
         q->beginRemoveRows(indexFromNode(node), 0, node->children.count() - 1);
     QList<qint64> snapshotIds = findSnapshotIdsRecursively(node);
     qDeleteAll(node->children);
     node->children.clear();
     node->snapshotId = -1;
     node->populationState = QScriptDebuggerLocalsModelNode::NotPopulated;
     if (hasChildren)
         q->endRemoveRows();
     deleteObjectSnapshots(snapshotIds);
 }
emitDataChanged()
void QScriptDebuggerLocalsModelPrivate::emitDataChanged (const QModelIndex & tl, const QModelIndex & br)
Definition at line 160 of file qscriptdebuggerlocalsmodel.cpp.
 {
     q_func()->dataChanged(tl, br);
 }
emitScopeObjectAvailable()
void QScriptDebuggerLocalsModelPrivate::emitScopeObjectAvailable (const QModelIndex & index)
Definition at line 753 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by addTopLevelObject(), and QScriptDebuggerLocalsModel::init().
 {
     emit q_func()->scopeObjectAvailable(index);
 }
get()
QScriptDebuggerLocalsModelPrivate * QScriptDebuggerLocalsModelPrivate::get (QScriptDebuggerLocalsModel * q) static
Definition at line 254 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by addTopLevelObject(), QScriptDebuggerLocalsModel::init(), isTopLevelNode(), and QScriptDebuggerLocalsModel::sync().
 {
     return q->d_func();
 }
indexFromNode()
QModelIndex QScriptDebuggerLocalsModelPrivate::indexFromNode (QScriptDebuggerLocalsModelNode * node) const
Definition at line 335 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (!node || (node == invisibleRootNode))
         return QModelIndex();
     QScriptDebuggerLocalsModelNode *par = node->parent;
     int row = par ? par->children.indexOf(node) : 0;
     return createIndex(row, 0, node);
 }
isTopLevelNode()
bool QScriptDebuggerLocalsModelPrivate::isTopLevelNode (QScriptDebuggerLocalsModelNode * node) const
Definition at line 345 of file qscriptdebuggerlocalsmodel.cpp.
 {
     return node && (node->parent == invisibleRootNode);
 }
nodeFromIndex()
QScriptDebuggerLocalsModelNode * QScriptDebuggerLocalsModelPrivate::nodeFromIndex (const QModelIndex & index) const
Definition at line 327 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (!index.isValid())
         return invisibleRootNode;
     return static_cast<QScriptDebuggerLocalsModelNode*>(index.internalPointer());
 }
populateIndex()
void QScriptDebuggerLocalsModelPrivate::populateIndex (const QModelIndex & index)
Definition at line 417 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (!index.isValid())
         return;
     QScriptDebuggerLocalsModelNode *node = nodeFromIndex(index);
     if (node->populationState != QScriptDebuggerLocalsModelNode::NotPopulated)
         return;
     if (node->property.value().type() != QScriptDebuggerValue::ObjectValue)
         return;
     node->populationState = QScriptDebuggerLocalsModelNode::Populating;
     QScriptDebuggerJob *job = new PopulateModelIndexJob(index, commandScheduler);
     jobScheduler->scheduleJob(job);
 }
reallyPopulateIndex()
void QScriptDebuggerLocalsModelPrivate::reallyPopulateIndex (const QModelIndex & index, const QScriptDebuggerValuePropertyList & props)
Definition at line 432 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (!index.isValid())
         return;
     QScriptDebuggerLocalsModelNode *node = nodeFromIndex(index);
     Q_ASSERT(node->populationState == QScriptDebuggerLocalsModelNode::Populating);
     node->populationState = QScriptDebuggerLocalsModelNode::Populated;
     addChildren(index, node, props);
 }
reallySyncIndex()
void QScriptDebuggerLocalsModelPrivate::reallySyncIndex (const QModelIndex & index, const QScriptDebuggerObjectSnapshotDelta & delta)
Definition at line 697 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (!index.isValid())
         return;
     QScriptDebuggerLocalsModelNode *node = nodeFromIndex(index);
     // update or remove existing children
     for (int i = 0; i < node->children.count(); ++i) {
         QScriptDebuggerLocalsModelNode *child = node->children.at(i);
         int j;
         for (j = 0; j < delta.changedProperties.count(); ++j) {
             if (child->property.name() == delta.changedProperties.at(j).name()) {
                 child->property = delta.changedProperties.at(j);
                 child->changed = true;
                 emitDataChanged(index, index.sibling(0, 1));
                 repopulate(child);
                 break;
             }
         }
         if (j != delta.changedProperties.count())
             continue; // was changed
         for (j = 0; j < delta.removedProperties.count(); ++j) {
             if (child->property.name() == delta.removedProperties.at(j)) {
                 removeChild(index, node, i);
                 --i;
                 break;
             }
         }
         if (j != delta.removedProperties.count())
             continue; // was removed
         // neither changed nor removed, but its children might be
         if (child->populationState == QScriptDebuggerLocalsModelNode::Populated) {
             QScriptDebuggerJob *job = new SyncModelIndexJob(indexFromNode(child), commandScheduler);
             jobScheduler->scheduleJob(job);
         }
     }
     addChildren(index, node, delta.addedProperties);
 }
removeChild()
void QScriptDebuggerLocalsModelPrivate::removeChild (const QModelIndex & parentIndex, QScriptDebuggerLocalsModelNode * parentNode, int row)
Definition at line 186 of file qscriptdebuggerlocalsmodel.cpp.
 {
     Q_Q(QScriptDebuggerLocalsModel);
     q->beginRemoveRows(parentIndex, row, row);
     QScriptDebuggerLocalsModelNode *child = parentNode->children.takeAt(row);
     QList<qint64> snapshotIds = findSnapshotIdsRecursively(child);
     delete child;
     q->endRemoveRows();
     deleteObjectSnapshots(snapshotIds);
 }
removeTopLevelNodes()
void QScriptDebuggerLocalsModelPrivate::removeTopLevelNodes ()
Definition at line 747 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by QScriptDebuggerLocalsModel::init().
 {
     while (!invisibleRootNode->children.isEmpty())
         removeChild(QModelIndex(), invisibleRootNode, 0);
 }
repopulate()
void QScriptDebuggerLocalsModelPrivate::repopulate (QScriptDebuggerLocalsModelNode * node)
Definition at line 215 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (node->populationState != QScriptDebuggerLocalsModelNode::Populated)
         return;
     depopulate(node);
     if (node->property.value().type() == QScriptDebuggerValue::ObjectValue)
         populateIndex(indexFromNode(node));
 }
syncIndex()
void QScriptDebuggerLocalsModelPrivate::syncIndex (const QModelIndex & index)
Definition at line 686 of file qscriptdebuggerlocalsmodel.cpp.
 {
     if (!index.isValid())
         return;
     QScriptDebuggerLocalsModelNode *node = nodeFromIndex(index);
     if (node->populationState != QScriptDebuggerLocalsModelNode::Populated)
         return;
     QScriptDebuggerJob *job = new SyncModelIndexJob(index, commandScheduler);
     jobScheduler->scheduleJob(job);
 }
syncTopLevelNodes()
void QScriptDebuggerLocalsModelPrivate::syncTopLevelNodes ()
Definition at line 736 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by QScriptDebuggerLocalsModel::init().
 {
     Q_Q(QScriptDebuggerLocalsModel);
     for (int i = 0; i < invisibleRootNode->children.count(); ++i) {
         QModelIndex index = q->index(i, 0, QModelIndex());
         syncIndex(index);
         if (i == 0)
             emit q->scopeObjectAvailable(index);
     }
 }
Properties
commandScheduler
QScriptDebuggerCommandSchedulerInterface* QScriptDebuggerLocalsModelPrivate::commandScheduler
Definition at line 144 of file qscriptdebuggerlocalsmodel.cpp.
frameIndex
int QScriptDebuggerLocalsModelPrivate::frameIndex
Definition at line 146 of file qscriptdebuggerlocalsmodel.cpp.
invisibleRootNode
QScriptDebuggerLocalsModelNode* QScriptDebuggerLocalsModelPrivate::invisibleRootNode
Definition at line 145 of file qscriptdebuggerlocalsmodel.cpp.
Referenced by QScriptDebuggerLocalsModel::init().
jobScheduler
QScriptDebuggerJobSchedulerInterface* QScriptDebuggerLocalsModelPrivate::jobScheduler
Definition at line 143 of file qscriptdebuggerlocalsmodel.cpp.
The documentation for this class was generated from the following file:
/src/scripttools/debugging/qscriptdebuggerlocalsmodel.cpp