Qt 4.8: QWin32PrintEngine Class Reference
QWin32PrintEngine Class Reference
#include <qprintengine_win_p.h>
Public Functions
bool abort ()
Instructs the print engine to abort the printing process.
bool begin (QPaintDevice *dev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
void drawTiledPixmap (const QRectF &r, const QPixmap &pm, const QPointF &p)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
HDC getDC () const
Empty default implementation.
HDC getPrinterDC () const
int metric (QPaintDevice::PaintDeviceMetric) const
Returns the metric for the given id.
bool newPage ()
Instructs the print engine to start a new page.
QPrinter::PrinterState printerState () const
Returns the current state of the printer being used by the print engine.
QVariant property (PrintEnginePropertyKey key) const
Returns the print engine's property specified by key.
QWin32PrintEngine (QPrinter::PrinterMode mode)
void releaseDC (HDC) const
Empty default implementation.
void releasePrinterDC (HDC dc) const
void setProperty (PrintEnginePropertyKey key, const QVariant &value)
Sets the print engine's property specified by key to the given value.
QPaintEngine::Type type () const
Reimplement this function to return the paint engine Type.
void updateClipPath (const QPainterPath &clip, Qt::ClipOperation op)
void updateMatrix (const QTransform &matrix)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
Public Functions inherited from QAlphaPaintEngine
virtual void drawImage (const QRectF &r, const QImage &image, const QRectF &sr)
~QAlphaPaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
virtual void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void fix_neg_rect (int *x, int *y, int *w, int *h)
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Public Functions inherited from QPrintEngine
virtual ~QPrintEngine ()
Destroys the print engine.
Friends
class QPageSetupDialog
class QPrintDialog
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Types inherited from QPrintEngine
enum PrintEnginePropertyKey {
PPK_CollateCopies, PPK_ColorMode, PPK_Creator, PPK_DocumentName,
PPK_FullPage, PPK_NumberOfCopies, PPK_Orientation, PPK_OutputFileName,
PPK_PageOrder, PPK_PageRect, PPK_PageSize, PPK_PaperRect,
PPK_PaperSource, PPK_PrinterName, PPK_PrinterProgram, PPK_Resolution,
PPK_SelectionOption, PPK_SupportedResolutions, PPK_WindowsPageSize, PPK_FontEmbedding,
PPK_SuppressSystemPrintStatus, PPK_Duplex, PPK_PaperSources, PPK_CustomPaperSize,
PPK_PageMargins, PPK_CopyCount, PPK_SupportsMultipleCopies, PPK_PaperSize = PPK_PageSize,
PPK_CustomBase = 0xff00
}
This enum is used to communicate properties between the print engine and QPrinter.
Protected Functions inherited from QAlphaPaintEngine
QRegion alphaClipping () const
void cleanUp ()
bool continueCall () const
void flushAndInit (bool init=true)
QAlphaPaintEngine (QAlphaPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 70 of file qprintengine_win_p.h.
Constructors and Destructors
QWin32PrintEngine()
QWin32PrintEngine::QWin32PrintEngine (QPrinter::PrinterMode mode)
Definition at line 162 of file qprintengine_win.cpp.
     : QAlphaPaintEngine(*(new QWin32PrintEnginePrivate),
                    PaintEngineFeatures(PrimitiveTransform
                                        | PixmapTransform
                                        | PerspectiveTransform
                                        | PainterPaths
                                        | Antialiasing
                                        | PaintOutsidePaintEvent))
 {
     Q_D(QWin32PrintEngine);
     d->docName = QLatin1String("document1");
     d->mode = mode;
     d->queryDefault();
     d->initialize();
 }
Functions
abort()
bool QWin32PrintEngine::abort () virtual
Instructs the print engine to abort the printing process.
Returns true if successful; otherwise returns false.
Implements QPrintEngine.
Definition at line 328 of file qprintengine_win.cpp.
 {
     // do nothing loop.
     return false;
 }
begin()
bool QWin32PrintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Reimplemented from QAlphaPaintEngine.
Definition at line 178 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     QAlphaPaintEngine::begin(pdev);
     if (!continueCall())
         return true;
     if (d->reinit) {
        d->resetDC();
        d->reinit = false;
     }
     // ### set default colors and stuff...
     bool ok = d->state == QPrinter::Idle;
     if (!d->hdc)
         return false;
     // Assign the FILE: to get the query...
     if (d->printToFile && d->fileName.isEmpty())
         d->fileName = d->port;
     d->devMode->dmCopies = d->num_copies;
     DOCINFO di;
     memset(&di, 0, sizeof(DOCINFO));
     di.cbSize = sizeof(DOCINFO);
     di.lpszDocName = reinterpret_cast<const wchar_t *>(d->docName.utf16());
     if (d->printToFile && !d->fileName.isEmpty())
         di.lpszOutput = reinterpret_cast<const wchar_t *>(d->fileName.utf16());
     if (ok && StartDoc(d->hdc, &di) == SP_ERROR) {
         qErrnoWarning("QWin32PrintEngine::begin: StartDoc failed");
         ok = false;
     }
     if (StartPage(d->hdc) <= 0) {
         qErrnoWarning("QWin32PrintEngine::begin: StartPage failed");
         ok = false;
     }
     if (!ok) {
         d->state = QPrinter::Idle;
     } else {
         d->state = QPrinter::Active;
     }
     d->matrix = QTransform();
     d->has_pen = true;
     d->pen = QColor(Qt::black);
     d->has_brush = false;
     d->complex_xform = false;
     updateMatrix(d->matrix);
     if (!ok)
         cleanUp();
     return ok;
 }
drawPath()
void QWin32PrintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QAlphaPaintEngine.
Definition at line 902 of file qprintengine_win.cpp.
Referenced by drawPolygon().
 {
 #ifdef QT_DEBUG_DRAW
     qDebug() << " - QWin32PrintEngine::drawPath(), bounds: " << path.boundingRect();
 #endif
     Q_D(QWin32PrintEngine);
     QAlphaPaintEngine::drawPath(path);
     if (!continueCall())
         return;
     if (d->has_brush)
         d->fillPath(path, d->brush_color);
     if (d->has_pen)
         d->strokePath(path, d->pen.color());
 }
drawPixmap()
void QWin32PrintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Reimplemented from QAlphaPaintEngine.
Definition at line 616 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     QAlphaPaintEngine::drawPixmap(targetRect, originalPixmap, sourceRect);
     if (!continueCall())
         return;
     const int tileSize = 2048;
     QRectF r = targetRect;
     QRectF sr = sourceRect;
     QPixmap pixmap = originalPixmap;
     if (sr.size() != pixmap.size()) {
         pixmap = pixmap.copy(sr.toRect());
     }
     qreal scaleX = 1.0f;
     qreal scaleY = 1.0f;
     QTransform scaleMatrix = QTransform::fromScale(r.width() / pixmap.width(), r.height() / pixmap.height());
     QTransform adapted = QPixmap::trueMatrix(d->painterMatrix * scaleMatrix,
                                              pixmap.width(), pixmap.height());
     qreal xform_offset_x = adapted.dx();
     qreal xform_offset_y = adapted.dy();
     if (d->complex_xform) {
         pixmap = pixmap.transformed(adapted);
         scaleX = d->stretch_x;
         scaleY = d->stretch_y;
     } else {
         scaleX = d->stretch_x * (r.width() / pixmap.width()) * d->painterMatrix.m11();
         scaleY = d->stretch_y * (r.height() / pixmap.height()) * d->painterMatrix.m22();
     }
     QPointF topLeft = r.topLeft() * d->painterMatrix;
     int tx = int(topLeft.x() * d->stretch_x + d->origin_x);
     int ty = int(topLeft.y() * d->stretch_y + d->origin_y);
     int tw = qAbs(int(pixmap.width() * scaleX));
     int th = qAbs(int(pixmap.height() * scaleY));
     xform_offset_x *= d->stretch_x;
     xform_offset_y *= d->stretch_y;
     int dc_state = SaveDC(d->hdc);
     int tilesw = pixmap.width() / tileSize;
     int tilesh = pixmap.height() / tileSize;
     ++tilesw;
     ++tilesh;
     int txinc = tileSize*scaleX;
     int tyinc = tileSize*scaleY;
     for (int y = 0; y < tilesh; ++y) {
         int tposy = ty + (y * tyinc);
         int imgh = tileSize;
         int height = tyinc;
         if (y == (tilesh - 1)) {
             imgh = pixmap.height() - (y * tileSize);
             height = (th - (y * tyinc));
         }
         for (int x = 0; x < tilesw; ++x) {
             int tposx = tx + (x * txinc);
             int imgw = tileSize;
             int width = txinc;
             if (x == (tilesw - 1)) {
                 imgw = pixmap.width() - (x * tileSize);
                 width = (tw - (x * txinc));
             }
             QPixmap p = pixmap.copy(tileSize * x, tileSize * y, imgw, imgh);
             HBITMAP hbitmap = p.toWinHBITMAP(QPixmap::NoAlpha);
             HDC display_dc = GetDC(0);
             HDC hbitmap_hdc = CreateCompatibleDC(display_dc);
             HGDIOBJ null_bitmap = SelectObject(hbitmap_hdc, hbitmap);
             ReleaseDC(0, display_dc);
             if (!StretchBlt(d->hdc, qRound(tposx - xform_offset_x), qRound(tposy - xform_offset_y), width, height,
                             hbitmap_hdc, 0, 0, p.width(), p.height(), SRCCOPY))
                 qErrnoWarning("QWin32PrintEngine::drawPixmap, StretchBlt failed");
             SelectObject(hbitmap_hdc, null_bitmap);
             DeleteObject(hbitmap);
             DeleteDC(hbitmap_hdc);
         }
     }
     RestoreDC(d->hdc, dc_state);
 }
drawPolygon()
void QWin32PrintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QAlphaPaintEngine.
Definition at line 922 of file qprintengine_win.cpp.
 {
 #ifdef QT_DEBUG_DRAW
     qDebug() << " - QWin32PrintEngine::drawPolygon(), pointCount: " << pointCount;
 #endif
     QAlphaPaintEngine::drawPolygon(points, pointCount, mode);
     if (!continueCall())
         return;
     Q_ASSERT(pointCount > 1);
     QPainterPath path(points[0]);
     for (int i=1; i<pointCount; ++i) {
         path.lineTo(points[i]);
     }
     Q_D(QWin32PrintEngine);
     bool has_brush = d->has_brush;
     if (mode == PolylineMode)
         d->has_brush = false; // No brush for polylines
     else
         path.closeSubpath(); // polygons are should always be closed.
     drawPath(path);
     d->has_brush = has_brush;
 }
drawTextItem()
void QWin32PrintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QAlphaPaintEngine.
Definition at line 334 of file qprintengine_win.cpp.
 {
     Q_D(const QWin32PrintEngine);
     QAlphaPaintEngine::drawTextItem(p, textItem);
     if (!continueCall())
         return;
     const QTextItemInt &ti = static_cast<const QTextItemInt &>(textItem);
     QRgb brushColor = state->pen().brush().color().rgb();
     bool fallBack = state->pen().brush().style() != Qt::SolidPattern
                     || qAlpha(brushColor) != 0xff
                     || d->txop >= QTransform::TxProject
                     || ti.fontEngine->type() != QFontEngine::Win;
     if (!fallBack) {
         QFontEngineWin *fe = static_cast<QFontEngineWin *>(ti.fontEngine);
         // Try selecting the font to see if we get a substitution font
         SelectObject(d->hdc, fe->hfont);
         if (GetDeviceCaps(d->hdc, TECHNOLOGY) != DT_CHARSTREAM) {
             wchar_t n[64];
             GetTextFace(d->hdc, 64, n);
             fallBack = QString::fromWCharArray(n)
                     != QString::fromWCharArray(fe->logfont.lfFaceName);
         }
     }
     if (fallBack) {
         QPaintEngine::drawTextItem(p, textItem);
         return ;
     }
     // We only want to convert the glyphs to text if the entire string is compatible with ASCII
     // and if we actually have access to the chars.
     bool convertToText = ti.chars != 0;
     for (int i=0;  i < ti.num_chars; ++i) {
         if (ti.chars[i].unicode() >= 0x80) {
             convertToText = false;
             break;
         }
         if (ti.logClusters[i] != i) {
             convertToText = false;
             break;
         }
     }
     COLORREF cf = RGB(qRed(brushColor), qGreen(brushColor), qBlue(brushColor));
     SelectObject(d->hdc, CreateSolidBrush(cf));
     SelectObject(d->hdc, CreatePen(PS_SOLID, 1, cf));
     SetTextColor(d->hdc, cf);
     draw_text_item_win(p, ti, d->hdc, convertToText, d->matrix, d->devPaperRect.topLeft());
     DeleteObject(SelectObject(d->hdc,GetStockObject(HOLLOW_BRUSH)));
     DeleteObject(SelectObject(d->hdc,GetStockObject(BLACK_PEN)));
 }
drawTiledPixmap()
void QWin32PrintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QAlphaPaintEngine.
Definition at line 713 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     QAlphaPaintEngine::drawTiledPixmap(r, pm, pos);
     if (!continueCall())
         return;
     if (d->complex_xform || !pos.isNull()) {
         QPaintEngine::drawTiledPixmap(r, pm, pos);
     } else {
         int dc_state = SaveDC(d->hdc);
         HDC display_dc = GetDC(0);
         HBITMAP hbitmap = pm.toWinHBITMAP(QPixmap::NoAlpha);
         HDC hbitmap_hdc = CreateCompatibleDC(display_dc);
         HGDIOBJ null_bitmap = SelectObject(hbitmap_hdc, hbitmap);
         ReleaseDC(0, display_dc);
         QRectF trect = d->painterMatrix.mapRect(r);
         int tx = int(trect.left() * d->stretch_x + d->origin_x);
         int ty = int(trect.top() * d->stretch_y + d->origin_y);
         int xtiles = int(trect.width() / pm.width()) + 1;
         int ytiles = int(trect.height() / pm.height()) + 1;
         int xinc = int(pm.width() * d->stretch_x);
         int yinc = int(pm.height() * d->stretch_y);
         for (int y = 0; y < ytiles; ++y) {
             int ity = ty + (yinc * y);
             int ith = pm.height();
             if (y == (ytiles - 1)) {
                 ith = int(trect.height() - (pm.height() * y));
             }
             for (int x = 0; x < xtiles; ++x) {
                 int itx = tx + (xinc * x);
                 int itw = pm.width();
                 if (x == (xtiles - 1)) {
                     itw = int(trect.width() - (pm.width() * x));
                 }
                 if (!StretchBlt(d->hdc, itx, ity, int(itw * d->stretch_x), int(ith * d->stretch_y),
                                 hbitmap_hdc, 0, 0, itw, ith, SRCCOPY))
                     qErrnoWarning("QWin32PrintEngine::drawPixmap, StretchBlt failed");
             }
         }
         SelectObject(hbitmap_hdc, null_bitmap);
         DeleteObject(hbitmap);
         DeleteDC(hbitmap_hdc);
         RestoreDC(d->hdc, dc_state);
     }
 }
end()
bool QWin32PrintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Reimplemented from QAlphaPaintEngine.
Definition at line 241 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     if (d->hdc) {
         if (d->state == QPrinter::Aborted) {
             cleanUp();
             AbortDoc(d->hdc);
             return true;
         }
     }
     QAlphaPaintEngine::end();
     if (!continueCall())
         return true;
     if (d->hdc) {
         EndPage(d->hdc);                 // end; printing done
         EndDoc(d->hdc);
     }
     d->state = QPrinter::Idle;
     d->reinit = true;
     return true;
 }
getDC()
HDC QWin32PrintEngine::getDC () const virtual
Empty default implementation.
Warning
This function is not part of the public interface.
Reimplemented from QPaintEngine.
Definition at line 1560 of file qprintengine_win.cpp.
Referenced by getPrinterDC(), and type().
 {
     return d_func()->hdc;
 }
getPrinterDC()
HDC QWin32PrintEngine::getPrinterDC () const inline virtual
Warning
This function is not part of the public interface.
Reimplemented from QPrintEngine.
Definition at line 105 of file qprintengine_win_p.h.
 { return getDC(); }
metric()
int QWin32PrintEngine::metric (QPaintDevice::PaintDeviceMetric id) const virtual
Returns the metric for the given id.
Implements QPrintEngine.
Definition at line 405 of file qprintengine_win.cpp.
 {
     Q_D(const QWin32PrintEngine);
     if (!d->hdc)
         return 0;
     int val;
     int res = d->resolution;
     switch (m) {
     case QPaintDevice::PdmWidth:
         if (d->has_custom_paper_size) {
             val =  qRound(d->paper_size.width() * res / 72.0);
         } else {
             int logPixelsX = GetDeviceCaps(d->hdc, LOGPIXELSX);
             if (logPixelsX == 0) {
                 qWarning("QWin32PrintEngine::metric: GetDeviceCaps() failed, "
                         "might be a driver problem");
                 logPixelsX = 600; // Reasonable default
             }
             val = res
                   * GetDeviceCaps(d->hdc, d->fullPage ? PHYSICALWIDTH : HORZRES)
                   / logPixelsX;
         }
         if (d->pageMarginsSet)
             val -= int(mmToInches((d->previousDialogMargins.left() +
                                    d->previousDialogMargins.width()) / 100.0) * res);
         break;
     case QPaintDevice::PdmHeight:
         if (d->has_custom_paper_size) {
             val = qRound(d->paper_size.height() * res / 72.0);
         } else {
             int logPixelsY = GetDeviceCaps(d->hdc, LOGPIXELSY);
             if (logPixelsY == 0) {
                 qWarning("QWin32PrintEngine::metric: GetDeviceCaps() failed, "
                         "might be a driver problem");
                 logPixelsY = 600; // Reasonable default
             }
             val = res
                   * GetDeviceCaps(d->hdc, d->fullPage ? PHYSICALHEIGHT : VERTRES)
                   / logPixelsY;
         }
         if (d->pageMarginsSet)
             val -= int(mmToInches((d->previousDialogMargins.top() +
                                    d->previousDialogMargins.height()) / 100.0) * res);
         break;
     case QPaintDevice::PdmDpiX:
         val = res;
         break;
     case QPaintDevice::PdmDpiY:
         val = res;
         break;
     case QPaintDevice::PdmPhysicalDpiX:
         val = GetDeviceCaps(d->hdc, LOGPIXELSX);
         break;
     case QPaintDevice::PdmPhysicalDpiY:
         val = GetDeviceCaps(d->hdc, LOGPIXELSY);
         break;
     case QPaintDevice::PdmWidthMM:
         if (d->has_custom_paper_size) {
             val = qRound(d->paper_size.width()*25.4/72);
         } else {
             if (!d->fullPage) {
                 val = GetDeviceCaps(d->hdc, HORZSIZE);
             } else {
                 float wi = 25.4 * GetDeviceCaps(d->hdc, PHYSICALWIDTH);
                 int logPixelsX = GetDeviceCaps(d->hdc,  LOGPIXELSX);
                 if (logPixelsX == 0) {
                     qWarning("QWin32PrintEngine::metric: GetDeviceCaps() failed, "
                             "might be a driver problem");
                     logPixelsX = 600; // Reasonable default
                 }
                 val = qRound(wi / logPixelsX);
             }
         }
         if (d->pageMarginsSet)
             val -= (d->previousDialogMargins.left() +
                     d->previousDialogMargins.width()) / 100.0;
         break;
     case QPaintDevice::PdmHeightMM:
         if (d->has_custom_paper_size) {
             val = qRound(d->paper_size.height()*25.4/72);
         } else {
             if (!d->fullPage) {
                 val = GetDeviceCaps(d->hdc, VERTSIZE);
             } else {
                 float hi = 25.4 * GetDeviceCaps(d->hdc, PHYSICALHEIGHT);
                 int logPixelsY = GetDeviceCaps(d->hdc,  LOGPIXELSY);
                 if (logPixelsY == 0) {
                     qWarning("QWin32PrintEngine::metric: GetDeviceCaps() failed, "
                             "might be a driver problem");
                     logPixelsY = 600; // Reasonable default
                 }
                 val = qRound(hi / logPixelsY);
             }
         }
         if (d->pageMarginsSet)
             val -= (d->previousDialogMargins.top() +
                     d->previousDialogMargins.height()) / 100.0;
         break;
     case QPaintDevice::PdmNumColors:
         {
             int bpp = GetDeviceCaps(d->hdc, BITSPIXEL);
             if(bpp==32)
                 val = INT_MAX;
             else if(bpp<=8)
                 val = GetDeviceCaps(d->hdc, NUMCOLORS);
             else
                 val = 1 << (bpp * GetDeviceCaps(d->hdc, PLANES));
         }
         break;
     case QPaintDevice::PdmDepth:
         val = GetDeviceCaps(d->hdc, PLANES);
         break;
     default:
         qWarning("QPrinter::metric: Invalid metric command");
         return 0;
     }
     return val;
 }
newPage()
bool QWin32PrintEngine::newPage () virtual
Instructs the print engine to start a new page.
Returns true if the printer was able to create the new page; otherwise returns false.
Implements QPrintEngine.
Definition at line 267 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     Q_ASSERT(isActive());
     Q_ASSERT(d->hdc);
     flushAndInit();
     bool transparent = GetBkMode(d->hdc) == TRANSPARENT;
     if (!EndPage(d->hdc)) {
         qErrnoWarning("QWin32PrintEngine::newPage: EndPage failed");
         return false;
     }
     if (d->reinit) {
         if (!d->resetDC()) {
             qErrnoWarning("QWin32PrintEngine::newPage: ResetDC failed");
             return false;
         }
         d->reinit = false;
     }
     if (!StartPage(d->hdc)) {
         qErrnoWarning("Win32PrintEngine::newPage: StartPage failed");
         return false;
     }
     SetTextAlign(d->hdc, TA_BASELINE);
     if (transparent)
         SetBkMode(d->hdc, TRANSPARENT);
     // ###
     return true;
     bool success = false;
     if (d->hdc && d->state == QPrinter::Active) {
         if (EndPage(d->hdc) != SP_ERROR) {
             // reinitialize the DC before StartPage if needed,
             // because resetdc is disabled between calls to the StartPage and EndPage functions
             // (see StartPage documentation in the Platform SDK:Windows GDI)
 //          state = PST_ACTIVEDOC;
 //          reinit();
 //          state = PST_ACTIVE;
             // start the new page now
             if (d->reinit) {
                 if (!d->resetDC())
                     qErrnoWarning("QWin32PrintEngine::newPage(), ResetDC failed (2)");
                 d->reinit = false;
             }
             success = (StartPage(d->hdc) != SP_ERROR);
         }
         if (!success) {
             d->state = QPrinter::Aborted;
             return false;
         }
     }
     return true;
 }
printerState()
QPrinter::PrinterState QWin32PrintEngine::printerState () const virtual
Returns the current state of the printer being used by the print engine.
Implements QPrintEngine.
Definition at line 1555 of file qprintengine_win.cpp.
 {
     return d_func()->state;
 }
property()
QVariant QWin32PrintEngine::property (PrintEnginePropertyKey key) const virtual
Returns the print engine's property specified by key.
See also
setProperty()
Implements QPrintEngine.
Definition at line 1384 of file qprintengine_win.cpp.
Referenced by setProperty().
 {
     Q_D(const QWin32PrintEngine);
     QVariant value;
     switch (key) {
     case PPK_CollateCopies:
         value = false;
         break;
     case PPK_ColorMode:
         {
             if (!d->devMode) {
                 value = QPrinter::Color;
             } else {
                 value = (d->devMode->dmColor == DMCOLOR_COLOR) ? QPrinter::Color : QPrinter::GrayScale;
             }
         }
         break;
     case PPK_DocumentName:
         value = d->docName;
         break;
     case PPK_FullPage:
         value = d->fullPage;
         break;
     case PPK_CopyCount:
         value = d->num_copies;
         break;
     case PPK_SupportsMultipleCopies:
         value = true;
         break;
     case PPK_NumberOfCopies:
         value = 1;
         break;
     case PPK_Orientation:
         {
             if (!d->devMode) {
                 value = QPrinter::Portrait;
             } else {
                 value = (d->devMode->dmOrientation == DMORIENT_LANDSCAPE) ? QPrinter::Landscape : QPrinter::Portrait;
             }
         }
         break;
     case PPK_OutputFileName:
         value = d->fileName;
         break;
     case PPK_PageRect:
         if (d->has_custom_paper_size) {
             QRect rect(0, 0,
                        qRound(d->paper_size.width() * d->resolution / 72.0),
                        qRound(d->paper_size.height() * d->resolution / 72.0));
             if (d->pageMarginsSet) {
                 rect = rect.adjusted(qRound(mmToInches(d->previousDialogMargins.left()/100.0) * d->resolution),
                                      qRound(mmToInches(d->previousDialogMargins.top()/100.0) * d->resolution),
                                      -qRound(mmToInches(d->previousDialogMargins.width()/100.0) * d->resolution),
                                      -qRound(mmToInches(d->previousDialogMargins.height()/100.0) * d->resolution));
             }
             value = rect;
         } else {
             value = QTransform(1/d->stretch_x, 0, 0, 1/d->stretch_y, 0, 0)
                     .mapRect(d->fullPage ? d->devPhysicalPageRect : d->devPageRect);
         }
         break;
     case PPK_PaperSize:
         if (d->has_custom_paper_size) {
             value = QPrinter::Custom;
         } else {
             if (!d->devMode) {
                 value = QPrinter::A4;
             } else {
                 value = mapDevmodePaperSize(d->devMode->dmPaperSize);
             }
         }
         break;
     case PPK_PaperRect:
         if (d->has_custom_paper_size) {
             value = QRect(0, 0,
                           qRound(d->paper_size.width() * d->resolution / 72.0),
                           qRound(d->paper_size.height() * d->resolution / 72.0));
         } else {
             value = QTransform(1/d->stretch_x, 0, 0, 1/d->stretch_y, 0, 0).mapRect(d->devPaperRect);
         }
         break;
     case PPK_PaperSource:
         if (!d->devMode) {
             value = QPrinter::Auto;
         } else {
             value = mapDevmodePaperSource(d->devMode->dmDefaultSource);
         }
         break;
     case PPK_PrinterName:
         value = d->name;
         break;
     case PPK_Resolution:
         if (d->resolution || !d->name.isEmpty())
             value = d->resolution;
         break;
     case PPK_SupportedResolutions:
         value = d->queryResolutions();
         break;
     case PPK_WindowsPageSize:
         if (!d->devMode) {
             value = -1;
         } else {
             value = d->devMode->dmPaperSize;
         }
         break;
     case PPK_PaperSources:
         {
             int available = DeviceCapabilities((const wchar_t *)d->name.utf16(),
                                                (const wchar_t *)d->port.utf16(), DC_BINS, 0, d->devMode);
             if (available <= 0)
                 break;
             wchar_t *data = new wchar_t[available];
             int count = DeviceCapabilities((const wchar_t *)d->name.utf16(),
                                            (const wchar_t *)d->port.utf16(), DC_BINS, data, d->devMode);
             QList<QVariant> out;
             for (int i=0; i<count; ++i) {
                 QPrinter::PaperSource src = mapDevmodePaperSource(data[i]);
                 if (src != -1)
                     out << (int) src;
             }
             value = out;
             delete [] data;
         }
         break;
     case PPK_CustomPaperSize:
         value = d->paper_size;
         break;
     case PPK_PageMargins:
     {
         QList<QVariant> margins;
         QRect pageMargins(d->getPageMargins());
         // specified in 1/100 mm
         margins << (mmToInches(pageMargins.left()/100.0) * 72)
                 << (mmToInches(pageMargins.top()/100.0) * 72)
                 << (mmToInches(pageMargins.width()/100.0) * 72)
                 << (mmToInches(pageMargins.height()/100.0) * 72);
         value = margins;
         break;
     }
     default:
         // Do nothing
         break;
     }
     return value;
 }
releaseDC()
void QWin32PrintEngine::releaseDC (HDC hdc) const virtual
Empty default implementation.
Warning
This function is not part of the public interface.
Reimplemented from QPaintEngine.
Definition at line 1565 of file qprintengine_win.cpp.
Referenced by releasePrinterDC(), and type().
 {
 }
releasePrinterDC()
void QWin32PrintEngine::releasePrinterDC (HDC) const inline virtual
Warning
This function is not part of the public interface.
Reimplemented from QPrintEngine.
Definition at line 106 of file qprintengine_win_p.h.
 { releaseDC(dc); }
setProperty()
void QWin32PrintEngine::setProperty (PrintEnginePropertyKey key, const QVariant & value) virtual
Sets the print engine's property specified by key to the given value.
See also
property()
Implements QPrintEngine.
Definition at line 1206 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     switch (key) {
     case PPK_CollateCopies:
         {
             if (!d->devMode)
                 break;
             d->devMode->dmCollate = value.toBool() ? DMCOLLATE_TRUE : DMCOLLATE_FALSE;
             d->doReinit();
         }
         break;
     case PPK_ColorMode:
         {
             if (!d->devMode)
                 break;
             d->devMode->dmColor = (value.toInt() == QPrinter::Color) ? DMCOLOR_COLOR : DMCOLOR_MONOCHROME;
             d->doReinit();
         }
         break;
     case PPK_Creator:
         break;
     case PPK_DocumentName:
         if (isActive()) {
             qWarning("QWin32PrintEngine: Cannot change document name while printing is active");
             return;
         }
         d->docName = value.toString();
         break;
     case PPK_FullPage:
         d->fullPage = value.toBool();
         d->updateOrigin();
         break;
     case PPK_CopyCount: // fallthrough
     case PPK_NumberOfCopies:
         if (!d->devMode)
             break;
         d->num_copies = value.toInt();
         d->devMode->dmCopies = d->num_copies;
         d->doReinit();
         break;
     case PPK_Orientation:
         {
             if (!d->devMode)
                 break;
             int orientation = value.toInt() == QPrinter::Landscape ? DMORIENT_LANDSCAPE : DMORIENT_PORTRAIT;
             int old_orientation = d->devMode->dmOrientation;
             d->devMode->dmOrientation = orientation;
             if (d->has_custom_paper_size && old_orientation != orientation)
                 d->paper_size = QSizeF(d->paper_size.height(), d->paper_size.width());
             d->doReinit();
         }
         break;
     case PPK_OutputFileName:
         if (isActive()) {
             qWarning("QWin32PrintEngine: Cannot change filename while printing");
         } else {
             d->fileName = value.toString();
             d->printToFile = !value.toString().isEmpty();
         }
         break;
     case PPK_PaperSize:
         if (!d->devMode)
             break;
         d->devMode->dmPaperSize = mapPaperSizeDevmode(QPrinter::PaperSize(value.toInt()));
         d->has_custom_paper_size = (QPrinter::PaperSize(value.toInt()) == QPrinter::Custom);
         d->doReinit();
         break;
     case PPK_PaperSource:
         {
             if (!d->devMode)
                 break;
             int dmMapped = DMBIN_AUTO;
             QList<QVariant> v = property(PPK_PaperSources).toList();
             if (v.contains(value))
                 dmMapped = mapPaperSourceDevmode(QPrinter::PaperSource(value.toInt()));
             d->devMode->dmDefaultSource = dmMapped;
             d->doReinit();
         }
         break;
     case PPK_PrinterName:
         d->name = value.toString();
         if(d->name.isEmpty())
             d->queryDefault();
         d->initialize();
         break;
     case PPK_Resolution:
         {
             d->resolution = value.toInt();
             d->stretch_x = d->dpi_x / double(d->resolution);
             d->stretch_y = d->dpi_y / double(d->resolution);
         }
         break;
     case PPK_SelectionOption:
         break;
     case PPK_SupportedResolutions:
         break;
     case PPK_WindowsPageSize:
         if (!d->devMode)
             break;
         d->has_custom_paper_size = false;
         d->devMode->dmPaperSize = value.toInt();
         d->doReinit();
         break;
     case PPK_CustomPaperSize:
     {
         d->has_custom_paper_size = true;
         d->paper_size = value.toSizeF();
         if (!d->devMode)
             break;
         int orientation = d->devMode->dmOrientation;
         DWORD needed = 0;
         DWORD returned = 0;
         if (!EnumForms(d->hPrinter, 1, 0, 0, &needed, &returned)) {
             BYTE *forms = (BYTE *) malloc(needed);
             if (EnumForms(d->hPrinter, 1, forms, needed, &needed, &returned)) {
                 for (DWORD i=0; i< returned; ++i) {
                     FORM_INFO_1 *formArray = reinterpret_cast<FORM_INFO_1 *>(forms);
                     // the form sizes are specified in 1000th of a mm,
                     // convert the size to Points
                     QSizeF size((formArray[i].Size.cx * 72/25.4)/1000.0,
                                 (formArray[i].Size.cy * 72/25.4)/1000.0);
                     if (qAbs(d->paper_size.width() - size.width()) <= 2
                         && qAbs(d->paper_size.height() - size.height()) <= 2)
                     {
                         d->devMode->dmPaperSize = i + 1;
                         break;
                     }
                 }
             }
             free(forms);
         }
         if (orientation != DMORIENT_PORTRAIT)
             d->paper_size = QSizeF(d->paper_size.height(), d->paper_size.width());
         break;
     }
     case PPK_PageMargins:
     {
         QList<QVariant> margins(value.toList());
         Q_ASSERT(margins.size() == 4);
         int left, top, right, bottom;
         // specified in 1/100 mm
         left = (margins.at(0).toReal()*25.4/72.0) * 100;
         top = (margins.at(1).toReal()*25.4/72.0) * 100;
         right = (margins.at(2).toReal()*25.4/72.0) * 100;
         bottom = (margins.at(3).toReal()*25.4/72.0) * 100;
         d->setPageMargins(left, top, right, bottom);
         break;
     }
     default:
         // Do nothing
         break;
     }
 }
type()
QPaintEngine::Type QWin32PrintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 100 of file qprintengine_win_p.h.
 { return Windows; }
updateClipPath()
void QWin32PrintEngine::updateClipPath (const QPainterPath & clip, Qt::ClipOperation op)
Definition at line 568 of file qprintengine_win.cpp.
Referenced by updateState().
 {
     Q_D(QWin32PrintEngine);
     bool doclip = true;
     if (op == Qt::NoClip) {
         SelectClipRgn(d->hdc, 0);
         doclip = false;
     }
     if (doclip) {
         QPainterPath xformed = clipPath * d->matrix;
         if (xformed.isEmpty()) {
             QRegion empty(-0x1000000, -0x1000000, 1, 1);
             SelectClipRgn(d->hdc, empty.handle());
         } else {
             d->composeGdiPath(xformed);
             const int ops[] = {
                 -1,         // Qt::NoClip, covered above
                 RGN_COPY,   // Qt::ReplaceClip
                 RGN_AND,    // Qt::IntersectClip
                 RGN_OR      // Qt::UniteClip
             };
             Q_ASSERT(op > 0 && unsigned(op) <= sizeof(ops) / sizeof(int));
             SelectClipPath(d->hdc, ops[op]);
         }
     }
     QPainterPath aclip = qt_regionToPath(alphaClipping());
     if (!aclip.isEmpty()) {
         QTransform tx(d->stretch_x, 0, 0, d->stretch_y, d->origin_x, d->origin_y);
         d->composeGdiPath(tx.map(aclip));
         SelectClipPath(d->hdc, RGN_DIFF);
     }
 }
updateMatrix()
void QWin32PrintEngine::updateMatrix (const QTransform & matrix)
Definition at line 605 of file qprintengine_win.cpp.
Referenced by begin(), and updateState().
 {
     Q_D(QWin32PrintEngine);
     QTransform stretch(d->stretch_x, 0, 0, d->stretch_y, d->origin_x, d->origin_y);
     d->painterMatrix = m;
     d->matrix = d->painterMatrix * stretch;
     d->txop = d->matrix.type();
     d->complex_xform = (d->txop > QTransform::TxScale);
 }
updateState()
void QWin32PrintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Reimplemented from QAlphaPaintEngine.
Definition at line 527 of file qprintengine_win.cpp.
 {
     Q_D(QWin32PrintEngine);
     QAlphaPaintEngine::updateState(state);
     if (!continueCall())
         return;
     if (state.state() & DirtyTransform) {
         updateMatrix(state.transform());
     }
     if (state.state() & DirtyPen) {
         d->pen = state.pen();
         d->has_pen = d->pen.style() != Qt::NoPen && d->pen.isSolid();
     }
     if (state.state() & DirtyBrush) {
         QBrush brush = state.brush();
         d->has_brush = brush.style() == Qt::SolidPattern;
         d->brush_color = brush.color();
     }
     if (state.state() & DirtyClipEnabled) {
         if (state.isClipEnabled())
             updateClipPath(painter()->clipPath(), Qt::ReplaceClip);
         else
             updateClipPath(QPainterPath(), Qt::NoClip);
     }
     if (state.state() & DirtyClipPath) {
         updateClipPath(state.clipPath(), state.clipOperation());
     }
     if (state.state() & DirtyClipRegion) {
         QRegion clipRegion = state.clipRegion();
         QPainterPath clipPath = qt_regionToPath(clipRegion);
         updateClipPath(clipPath, state.clipOperation());
     }
 }
Friends and Related Functions
QPageSetupDialog
friend class QPageSetupDialog friend
Definition at line 110 of file qprintengine_win_p.h.
QPrintDialog
friend class QPrintDialog friend
Definition at line 109 of file qprintengine_win_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qprintengine_win_p.h
/src/gui/painting/qprintengine_win.cpp