Qt 4.8: QBBSystemLocaleData Class Reference
QBBSystemLocaleData Class Reference
#include <qlocale_blackberry.h>
Public Slots
void installSocketNotifiers ()
void readHourFormat ()
void readLangageLocale ()
void readMeasurementSystem ()
void readRegionLocale ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QVariant dateTimeFormat (QLocale::FormatType)
QLocale languageLocale ()
uint measurementSystem ()
QBBSystemLocaleData ()
QLocale regionLocale ()
QVariant timeFormat (QLocale::FormatType)
virtual ~QBBSystemLocaleData ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QReadWriteLock lock
Private Functions
QString getCorrectFormat (const QString &baseFormat, QLocale::FormatType typeFormat)
QByteArray readPpsValue (const char *ppsObject, int ppsFd)
Properties
int hourFd
QSocketNotifier * hourNotifier
bool is24HourFormat
int languageFd
QSocketNotifier * languageNotifier
QByteArray lc_langage
QByteArray lc_region
uint m_measurementSystem
int measurementFd
QSocketNotifier * measurementNotifier
int regionFd
QSocketNotifier * regionNotifier
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 57 of file qlocale_blackberry.h.
Constructors and Destructors
QBBSystemLocaleData()
QBBSystemLocaleData::QBBSystemLocaleData ()
Definition at line 65 of file qlocale_blackberry.cpp.
     : languageNotifier(0)
     , regionNotifier(0)
     , measurementNotifier(0)
     , hourNotifier(0)
 {
     // Do not use qWarning to log warnings if qt_safe_open fails to open the pps file
     // since the user code may install a message handler that invokes QLocale API again
     // (i.e QDate, QDateTime, ...) which will cause an infinite loop.
     if ((measurementFd = qt_safe_open(ppsUomPath, O_RDONLY)) == -1)
         fprintf(stderr, "Failed to open uom pps, errno=%d\n", errno);
     if ((regionFd = qt_safe_open(ppsRegionLocalePath, O_RDONLY)) == -1)
         fprintf(stderr, "Failed to open region pps, errno=%d\n", errno);
     if ((languageFd = qt_safe_open(ppsLanguageLocalePath, O_RDONLY)) == -1)
         fprintf(stderr, "Failed to open language pps, errno=%d\n", errno);
     if ((hourFd = qt_safe_open(ppsHourFormatPath, O_RDONLY)) == -1)
        fprintf(stderr, "Failed to open hour format pps, errno=%d\n", errno);
     // we cannot call this directly, because by the time this constructor is
     // called, the event dispatcher has not yet been created, causing the
     // subsequent call to QSocketNotifier constructor to fail.
     QMetaObject::invokeMethod(this, "installSocketNotifiers", Qt::QueuedConnection);
     readLangageLocale();
     readRegionLocale();
     readMeasurementSystem();
     readHourFormat();
 }
~QBBSystemLocaleData()
QBBSystemLocaleData::~QBBSystemLocaleData () virtual
Definition at line 97 of file qlocale_blackberry.cpp.
 {
     if (measurementFd != -1)
         qt_safe_close(measurementFd);
     if (languageFd != -1)
         qt_safe_close(languageFd);
     if (regionFd != -1)
         qt_safe_close(regionFd);
     if (hourFd != -1)
         qt_safe_close(hourFd);
 }
Functions
dateTimeFormat()
QVariant QBBSystemLocaleData::dateTimeFormat (QLocale::FormatType formatType)
Definition at line 122 of file qlocale_blackberry.cpp.
Referenced by QSystemLocale::query().
 {
     return getCorrectFormat(regionLocale().dateTimeFormat(formatType), formatType);
 }
getCorrectFormat()
QString QBBSystemLocaleData::getCorrectFormat (const QString & baseFormat, QLocale::FormatType typeFormat) private
Definition at line 238 of file qlocale_blackberry.cpp.
Referenced by dateTimeFormat(), and timeFormat().
 {
     QString format = baseFormat;
     if (is24HourFormat) {
         if (format.contains(QLatin1String("AP"), Qt::CaseInsensitive)) {
             format.replace(QLatin1String("AP"), QLatin1String(""), Qt::CaseInsensitive);
             format.replace(QLatin1String("h"), QLatin1String("H"), Qt::CaseSensitive);
         }
     } else {
         if (!format.contains(QLatin1String("AP"), Qt::CaseInsensitive)) {
             format.contains(QLatin1String("HH"), Qt::CaseSensitive) ?
                 format.replace(QLatin1String("HH"), QLatin1String("hh"), Qt::CaseSensitive) :
                 format.replace(QLatin1String("H"), QLatin1String("h"), Qt::CaseSensitive);
             formatType == QLocale::LongFormat ? format.append(QLatin1String(" AP t")) : format.append(QLatin1String(" AP"));
         }
     }
     return format;
 }
installSocketNotifiers
void QBBSystemLocaleData::installSocketNotifiers () slot
Definition at line 143 of file qlocale_blackberry.cpp.
 {
     Q_ASSERT(!languageNotifier || !regionNotifier || !measurementNotifier || !hourNotifier);
     Q_ASSERT(QCoreApplication::instance());
     languageNotifier = new QSocketNotifier(languageFd, QSocketNotifier::Read, this);
     QObject::connect(languageNotifier, SIGNAL(activated(int)), this, SLOT(readLangageLocale()));
     regionNotifier = new QSocketNotifier(regionFd, QSocketNotifier::Read, this);
     QObject::connect(regionNotifier, SIGNAL(activated(int)), this, SLOT(readRegionLocale()));
     measurementNotifier = new QSocketNotifier(measurementFd, QSocketNotifier::Read, this);
     QObject::connect(measurementNotifier, SIGNAL(activated(int)), this, SLOT(readMeasurementSystem()));
     hourNotifier = new QSocketNotifier(hourFd, QSocketNotifier::Read, this);
     QObject::connect(hourNotifier, SIGNAL(activated(int)), this, SLOT(readHourFormat()));
 }
languageLocale()
QLocale QBBSystemLocaleData::languageLocale ()
Definition at line 127 of file qlocale_blackberry.cpp.
Referenced by QSystemLocale::query().
 {
     if (!lc_langage.isEmpty())
         return QLocale(QLatin1String(lc_langage));
     return QLocale::c();
 }
measurementSystem()
uint QBBSystemLocaleData::measurementSystem ()
Definition at line 112 of file qlocale_blackberry.cpp.
Referenced by QSystemLocale::query().
 {
     return m_measurementSystem;
 }
readHourFormat
void QBBSystemLocaleData::readHourFormat () slot
Definition at line 177 of file qlocale_blackberry.cpp.
Referenced by installSocketNotifiers(), and QBBSystemLocaleData().
 {
     QByteArray hourFormat = readPpsValue("hourFormat", hourFd);
     is24HourFormat = (qstrcmp(hourFormat, "24") == 0);
 }
readLangageLocale
void QBBSystemLocaleData::readLangageLocale () slot
Definition at line 161 of file qlocale_blackberry.cpp.
Referenced by installSocketNotifiers(), and QBBSystemLocaleData().
 {
     lc_langage = readPpsValue("_CS_LOCALE", languageFd);
 }
readMeasurementSystem
void QBBSystemLocaleData::readMeasurementSystem () slot
Definition at line 171 of file qlocale_blackberry.cpp.
Referenced by installSocketNotifiers(), and QBBSystemLocaleData().
 {
     QByteArray measurement = readPpsValue("uom", measurementFd);
     m_measurementSystem = (qstrcmp(measurement, "imperial") == 0) ? QLocale::ImperialSystem : QLocale::MetricSystem;
 }
readPpsValue()
QByteArray QBBSystemLocaleData::readPpsValue (const char * ppsObject, int ppsFd) private
Definition at line 183 of file qlocale_blackberry.cpp.
Referenced by readHourFormat(), readLangageLocale(), readMeasurementSystem(), and readRegionLocale().
 {
     QByteArray result;
     if (!ppsObject || ppsFd == -1)
         return result;
     // PPS objects are of unknown size, but must be read all at once.
     // Relying on the file size may not be a good idea since the size may change before reading.
     // Let's try with an initial size (512), and if the buffer is too small try with bigger one,
     // until we succeed or until other non buffer-size-related error occurs.
     // Using QVarLengthArray means the first try (of size == 512) uses a buffer on the stack - no allocation necessary.
      // Hopefully that covers most use cases.
     int bytes;
     QVarLengthArray<char, 512> buffer;
     for (;;) {
         errno = 0;
         bytes = qt_safe_read(ppsFd, buffer.data(), buffer.capacity() - 1);
         const bool bufferIsTooSmall = (bytes == -1 && errno == EMSGSIZE && buffer.capacity() < MAX_PPS_SIZE);
         if (!bufferIsTooSmall)
             break;
         buffer.resize(qMin(buffer.capacity()*2, MAX_PPS_SIZE));
     }
     // This method is called in the ctor(), so do not use qWarning to log warnings
     // if qt_safe_read fails to read the pps file
     // since the user code may install a message handler that invokes QLocale API again
     // (i.e QDate, QDateTime, ...) which will cause a infinite loop.
     if (bytes == -1) {
         fprintf(stderr, "Failed to read pps object:%s, errno=%d\n", ppsObject, errno);
         return result;
     }
     // ensure data is null terminated
     buffer[bytes] = '\0';
     pps_decoder_t ppsDecoder;
     pps_decoder_initialize(&ppsDecoder, 0);
     if (pps_decoder_parse_pps_str(&ppsDecoder, buffer.data()) == PPS_DECODER_OK) {
         pps_decoder_push(&ppsDecoder, 0);
         const char *ppsBuff;
         if (pps_decoder_get_string(&ppsDecoder, ppsObject, &ppsBuff) == PPS_DECODER_OK) {
             result = ppsBuff;
         } else {
             int val;
             if (pps_decoder_get_int(&ppsDecoder, ppsObject, &val) == PPS_DECODER_OK)
                 result = QByteArray::number(val);
         }
     }
     pps_decoder_cleanup(&ppsDecoder);
     return result;
 }
readRegionLocale
void QBBSystemLocaleData::readRegionLocale () slot
Definition at line 166 of file qlocale_blackberry.cpp.
Referenced by installSocketNotifiers(), and QBBSystemLocaleData().
 {
     lc_region = readPpsValue("region", regionFd);
 }
regionLocale()
QLocale QBBSystemLocaleData::regionLocale ()
Definition at line 135 of file qlocale_blackberry.cpp.
Referenced by dateTimeFormat(), QSystemLocale::query(), and timeFormat().
 {
     if (!lc_region.isEmpty())
         return QLocale(QLatin1String(lc_region));
     return QLocale::c();
 }
timeFormat()
QVariant QBBSystemLocaleData::timeFormat (QLocale::FormatType formatType)
Definition at line 117 of file qlocale_blackberry.cpp.
Referenced by QSystemLocale::query().
 {
     return getCorrectFormat(regionLocale().timeFormat(formatType), formatType);
 }
Properties
hourFd
int QBBSystemLocaleData::hourFd private
Definition at line 96 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers(), QBBSystemLocaleData(), readHourFormat(), and ~QBBSystemLocaleData().
hourNotifier
QSocketNotifier* QBBSystemLocaleData::hourNotifier private
Definition at line 91 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers().
is24HourFormat
bool QBBSystemLocaleData::is24HourFormat private
Definition at line 86 of file qlocale_blackberry.h.
Referenced by getCorrectFormat(), and readHourFormat().
languageFd
int QBBSystemLocaleData::languageFd private
Definition at line 93 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers(), QBBSystemLocaleData(), readLangageLocale(), and ~QBBSystemLocaleData().
languageNotifier
QSocketNotifier* QBBSystemLocaleData::languageNotifier private
Definition at line 88 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers().
lc_langage
QByteArray QBBSystemLocaleData::lc_langage private
Definition at line 83 of file qlocale_blackberry.h.
Referenced by languageLocale(), and readLangageLocale().
lc_region
QByteArray QBBSystemLocaleData::lc_region private
Definition at line 84 of file qlocale_blackberry.h.
Referenced by QSystemLocale::query(), readRegionLocale(), and regionLocale().
lock
QReadWriteLock QBBSystemLocaleData::lock
Definition at line 70 of file qlocale_blackberry.h.
Referenced by QSystemLocale::query().
m_measurementSystem
uint QBBSystemLocaleData::m_measurementSystem private
Definition at line 85 of file qlocale_blackberry.h.
Referenced by measurementSystem(), and readMeasurementSystem().
measurementFd
int QBBSystemLocaleData::measurementFd private
Definition at line 95 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers(), QBBSystemLocaleData(), readMeasurementSystem(), and ~QBBSystemLocaleData().
measurementNotifier
QSocketNotifier* QBBSystemLocaleData::measurementNotifier private
Definition at line 90 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers().
regionFd
int QBBSystemLocaleData::regionFd private
Definition at line 94 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers(), QBBSystemLocaleData(), readRegionLocale(), and ~QBBSystemLocaleData().
regionNotifier
QSocketNotifier* QBBSystemLocaleData::regionNotifier private
Definition at line 89 of file qlocale_blackberry.h.
Referenced by installSocketNotifiers().
The documentation for this class was generated from the following files:
/src/corelib/tools/qlocale_blackberry.h
/src/corelib/tools/qlocale_blackberry.cpp