Qt 4.8: QPatternist::XsdDocumentation Class Reference
QPatternist::XsdDocumentation Class Reference
XML Schema Processing
Represents a XSD documentation object.
#include <qxsddocumentation_p.h>
Public Types
typedef QList< XsdDocumentation::Ptr > List
typedef QExplicitlySharedDataPointer< XsdDocumentation > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
QString content () const
DerivedString< TypeLanguage >::Ptr language () const
void setContent (const QString &content)
void setLanguage (const DerivedString< TypeLanguage >::Ptr &language)
void setSource (const AnyURI::Ptr &source)
AnyURI::Ptr source () const
XsdDocumentation ()
~XsdDocumentation ()
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
QString m_content
DerivedString< TypeLanguage >::Ptr m_language
AnyURI::Ptr m_source
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD documentation object.
This class represents the documentation component of an annotation object of a XML schema as described here.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 75 of file qxsddocumentation_p.h.
Typedefs
List
typedef QList<XsdDocumentation::Ptr> QPatternist::XsdDocumentation::List
Definition at line 79 of file qxsddocumentation_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdDocumentation> QPatternist::XsdDocumentation::Ptr
Definition at line 78 of file qxsddocumentation_p.h.
Constructors and Destructors
XsdDocumentation()
XsdDocumentation::XsdDocumentation ()
Creates a new documentation object.
Definition at line 48 of file qxsddocumentation.cpp.
 {
 }
~XsdDocumentation()
XsdDocumentation::~XsdDocumentation ()
Destroys the documentation object.
Definition at line 52 of file qxsddocumentation.cpp.
 {
 }
Functions
content()
QString XsdDocumentation::content () const
Returns the content of the documentation.
Definition at line 81 of file qxsddocumentation.cpp.
Referenced by setContent().
 {
     return m_content;
 }
language()
DerivedString< TypeLanguage >::Ptr XsdDocumentation::language () const
Returns the language of the documentation.
Definition at line 71 of file qxsddocumentation.cpp.
Referenced by setLanguage().
 {
     return m_language;
 }
setContent()
void XsdDocumentation::setContent (const QString & content)
Sets the content of the documentation.
The content can be of abritrary type.
Definition at line 76 of file qxsddocumentation.cpp.
 {
     m_content = content;
 }
setLanguage()
void XsdDocumentation::setLanguage (const DerivedString< TypeLanguage >::Ptr & language)
Sets the language of the documentation.
Definition at line 66 of file qxsddocumentation.cpp.
 {
     m_language = language;
 }
setSource()
void XsdDocumentation::setSource (const AnyURI::Ptr & source)
Sets the source of the documentation.
The source points to an URL that contains more information.
Definition at line 56 of file qxsddocumentation.cpp.
 {
     m_source = source;
 }
source()
AnyURI::Ptr XsdDocumentation::source () const
Returns the source of the documentation.
Definition at line 61 of file qxsddocumentation.cpp.
Referenced by setSource().
 {
     return m_source;
 }
Properties
m_content
QString QPatternist::XsdDocumentation::m_content private
Definition at line 129 of file qxsddocumentation_p.h.
Referenced by content(), and setContent().
m_language
DerivedString<TypeLanguage>::Ptr QPatternist::XsdDocumentation::m_language private
Definition at line 128 of file qxsddocumentation_p.h.
Referenced by language(), and setLanguage().
m_source
AnyURI::Ptr QPatternist::XsdDocumentation::m_source private
Definition at line 127 of file qxsddocumentation_p.h.
Referenced by setSource(), and source().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsddocumentation_p.h
/src/xmlpatterns/schema/qxsddocumentation.cpp