Qt 4.8: QmlJSDebugger::ZoomTool Class Reference
QmlJSDebugger::ZoomTool Class Reference
#include <zoomtool.h>
Public Types
enum ZoomDirection { ZoomIn, ZoomOut }
Public Functions
void clear ()
void hoverMoveEvent (QMouseEvent *event)
void itemsAboutToRemoved (const QList< QGraphicsItem *> &)
void keyPressEvent (QKeyEvent *event)
void keyReleaseEvent (QKeyEvent *keyEvent)
void mouseDoubleClickEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void wheelEvent (QWheelEvent *event)
ZoomTool (QDeclarativeViewInspector *view)
virtual ~ZoomTool ()
Public Functions inherited from QmlJSDebugger::AbstractLiveEditTool
AbstractLiveEditTool (QDeclarativeViewInspector *inspector)
QList< QGraphicsItem * > items () const
void leaveEvent (QEvent *)
QString titleForItem (QGraphicsItem *item)
bool topItemIsMovable (const QList< QGraphicsItem *> &itemList)
bool topItemIsResizeHandle (const QList< QGraphicsItem *> &itemList)
bool topSelectedItemIsMovable (const QList< QGraphicsItem *> &itemList)
void updateSelectedItems ()
virtual ~AbstractLiveEditTool ()
Public Functions inherited from QmlJSDebugger::AbstractTool
AbstractTool (AbstractViewInspector *inspector)
AbstractViewInspector * inspector () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void selectedItemsChanged (const QList< QGraphicsItem *> &)
Protected Functions inherited from QmlJSDebugger::AbstractLiveEditTool
QDeclarativeViewInspector * inspector () const
QGraphicsScene * scene () const
QDeclarativeView * view () const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void zoomIn ()
void zoomOut ()
void zoomTo100 ()
Private Functions
qreal nextZoomScale (ZoomDirection direction) const
void scaleView (const QPointF &centerPos)
Properties
qreal m_currentScale
QPointF m_dragBeginPos
bool m_dragStarted
QPoint m_mousePos
LiveRubberBandSelectionManipulator * m_rubberbandManipulator
qreal m_smoothZoomMultiplier
QAction * m_zoomInAction
QAction * m_zoomOutAction
QAction * m_zoomTo100Action
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QmlJSDebugger::AbstractLiveEditTool
static QList< QGraphicsObject * > toGraphicsObjectList (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * topMovableDeclarativeItem (const QList< QGraphicsItem *> &itemList)
static QGraphicsItem * topMovableGraphicsItem (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * toQDeclarativeItem (QGraphicsItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 52 of file zoomtool.h.
Enumerations
ZoomDirection
enum QmlJSDebugger::ZoomTool::ZoomDirection
Enumerator
ZoomIn
ZoomOut
Definition at line 57 of file zoomtool.h.
{
         ZoomIn,
         ZoomOut
     };
Constructors and Destructors
ZoomTool()
QmlJSDebugger::ZoomTool::ZoomTool (QDeclarativeViewInspector * view) explicit
Definition at line 57 of file zoomtool.cpp.
                                                   :
     AbstractLiveEditTool(view),
     m_rubberbandManipulator(),
     m_smoothZoomMultiplier(0.05f),
     m_currentScale(1.0f)
 {
     m_zoomTo100Action = new QAction(tr("Zoom to &100%"), this);
     m_zoomInAction = new QAction(tr("Zoom In"), this);
     m_zoomOutAction = new QAction(tr("Zoom Out"), this);
     m_zoomInAction->setShortcut(QKeySequence(Qt::Key_Plus));
     m_zoomOutAction->setShortcut(QKeySequence(Qt::Key_Minus));
     LiveLayerItem *layerItem = QDeclarativeViewInspectorPrivate::get(view)->manipulatorLayer;
     QGraphicsObject *layerObject = reinterpret_cast<QGraphicsObject *>(layerItem);
     m_rubberbandManipulator = new LiveRubberBandSelectionManipulator(layerObject, view);
     connect(m_zoomTo100Action, SIGNAL(triggered()), SLOT(zoomTo100()));
     connect(m_zoomInAction, SIGNAL(triggered()), SLOT(zoomIn()));
     connect(m_zoomOutAction, SIGNAL(triggered()), SLOT(zoomOut()));
 }
~ZoomTool()
QmlJSDebugger::ZoomTool::~ZoomTool () virtual
Definition at line 80 of file zoomtool.cpp.
 {
     delete m_rubberbandManipulator;
 }
Functions
clear()
void QmlJSDebugger::ZoomTool::clear (void) virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 245 of file zoomtool.cpp.
Referenced by itemsAboutToRemoved().
 {
 #ifndef QT_NO_CURSOR
     view()->setCursor(Qt::ArrowCursor);
 #endif
 }
hoverMoveEvent()
void QmlJSDebugger::ZoomTool::hoverMoveEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 183 of file zoomtool.cpp.
 {
     m_mousePos = event->pos();
 }
itemsAboutToRemoved()
void QmlJSDebugger::ZoomTool::itemsAboutToRemoved (const QList< QGraphicsItem *> &) inline virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 76 of file zoomtool.h.
 {}
keyPressEvent()
void QmlJSDebugger::ZoomTool::keyPressEvent (QKeyEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 189 of file zoomtool.cpp.
 {
 }
keyReleaseEvent()
void QmlJSDebugger::ZoomTool::keyReleaseEvent (QKeyEvent * keyEvent) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 215 of file zoomtool.cpp.
 {
     switch (event->key()) {
     case Qt::Key_Plus:
         zoomIn();
         break;
     case Qt::Key_Minus:
         zoomOut();
         break;
     case Qt::Key_1:
     case Qt::Key_2:
     case Qt::Key_3:
     case Qt::Key_4:
     case Qt::Key_5:
     case Qt::Key_6:
     case Qt::Key_7:
     case Qt::Key_8:
     case Qt::Key_9:
     {
         m_currentScale = ((event->key() - Qt::Key_0) * 1.0f);
         scaleView(view()->mapToScene(m_mousePos)); // view()->mapToScene(view()->rect().center())
         break;
     }
     default:
         break;
     }
 }
mouseDoubleClickEvent()
void QmlJSDebugger::ZoomTool::mouseDoubleClickEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 177 of file zoomtool.cpp.
 {
     m_mousePos = event->pos();
 }
mouseMoveEvent()
void QmlJSDebugger::ZoomTool::mouseMoveEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 104 of file zoomtool.cpp.
 {
     m_mousePos = event->pos();
     QPointF scenePos = view()->mapToScene(event->pos());
     if (event->buttons() & Qt::LeftButton
             && (QPointF(scenePos - m_dragBeginPos).manhattanLength()
                 > Constants::DragStartDistance / 3)
             && !m_dragStarted)
     {
         m_dragStarted = true;
         m_rubberbandManipulator->begin(m_dragBeginPos);
         return;
     }
     if (m_dragStarted)
         m_rubberbandManipulator->update(scenePos);
 }
mousePressEvent()
void QmlJSDebugger::ZoomTool::mousePressEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 85 of file zoomtool.cpp.
 {
     m_mousePos = event->pos();
     QPointF scenePos = view()->mapToScene(event->pos());
     if (event->buttons() & Qt::RightButton) {
         QMenu contextMenu;
         contextMenu.addAction(m_zoomTo100Action);
         contextMenu.addSeparator();
         contextMenu.addAction(m_zoomInAction);
         contextMenu.addAction(m_zoomOutAction);
         contextMenu.exec(event->globalPos());
     } else if (event->buttons() & Qt::LeftButton) {
         m_dragBeginPos = scenePos;
         m_dragStarted = false;
     }
 }
mouseReleaseEvent()
void QmlJSDebugger::ZoomTool::mouseReleaseEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 125 of file zoomtool.cpp.
 {
     m_mousePos = event->pos();
     QPointF scenePos = view()->mapToScene(event->pos());
     if (m_dragStarted) {
         m_rubberbandManipulator->end();
         int x1 = qMin(scenePos.x(), m_rubberbandManipulator->beginPoint().x());
         int x2 = qMax(scenePos.x(), m_rubberbandManipulator->beginPoint().x());
         int y1 = qMin(scenePos.y(), m_rubberbandManipulator->beginPoint().y());
         int y2 = qMax(scenePos.y(), m_rubberbandManipulator->beginPoint().y());
         QPointF scenePosTopLeft = QPoint(x1, y1);
         QPointF scenePosBottomRight = QPoint(x2, y2);
         QRectF sceneArea(scenePosTopLeft, scenePosBottomRight);
         m_currentScale = qMin(view()->rect().width() / sceneArea.width(),
                               view()->rect().height() / sceneArea.height());
         QTransform transform;
         transform.scale(m_currentScale, m_currentScale);
         view()->setTransform(transform);
         view()->setSceneRect(sceneArea);
     } else {
         Qt::KeyboardModifier modifierKey = Qt::ControlModifier;
 #ifdef Q_WS_MAC
         modifierKey = Qt::AltModifier;
 #endif
         if (event->modifiers() & modifierKey) {
             zoomOut();
         } else {
             zoomIn();
         }
     }
 }
nextZoomScale()
qreal QmlJSDebugger::ZoomTool::nextZoomScale (ZoomDirection direction) const private
Definition at line 292 of file zoomtool.cpp.
Referenced by selectedItemsChanged(), wheelEvent(), zoomIn(), and zoomOut().
 {
     static QList<qreal> zoomScales =
             QList<qreal>()
             << 0.125f
             << 1.0f / 6.0f
             << 0.25f
             << 1.0f / 3.0f
             << 0.5f
             << 2.0f / 3.0f
             << 1.0f
             << 2.0f
             << 3.0f
             << 4.0f
             << 5.0f
             << 6.0f
             << 7.0f
             << 8.0f
             << 12.0f
             << 16.0f
             << 32.0f
             << 48.0f;
     if (direction == ZoomIn) {
         for (int i = 0; i < zoomScales.length(); ++i) {
             if (zoomScales[i] > m_currentScale || i == zoomScales.length() - 1)
                 return zoomScales[i];
         }
     } else {
         for (int i = zoomScales.length() - 1; i >= 0; --i) {
             if (zoomScales[i] < m_currentScale || i == 0)
                 return zoomScales[i];
         }
     }
     return 1.0f;
 }
scaleView()
void QmlJSDebugger::ZoomTool::scaleView (const QPointF & centerPos) private
Definition at line 252 of file zoomtool.cpp.
Referenced by keyReleaseEvent(), selectedItemsChanged(), wheelEvent(), zoomIn(), zoomOut(), and zoomTo100().
 {
     QTransform transform;
     transform.scale(m_currentScale, m_currentScale);
     view()->setTransform(transform);
     QPointF adjustedCenterPos = centerPos;
     QSize rectSize(view()->rect().width() / m_currentScale,
                    view()->rect().height() / m_currentScale);
     QRectF sceneRect;
     if (qAbs(m_currentScale - 1.0f) < Constants::ZoomSnapDelta) {
         adjustedCenterPos.rx() = rectSize.width() / 2;
         adjustedCenterPos.ry() = rectSize.height() / 2;
     }
     if (m_currentScale < 1.0f) {
         adjustedCenterPos.rx() = rectSize.width() / 2;
         adjustedCenterPos.ry() = rectSize.height() / 2;
         sceneRect.setRect(view()->rect().width() / 2 -rectSize.width() / 2,
                           view()->rect().height() / 2 -rectSize.height() / 2,
                           rectSize.width(),
                           rectSize.height());
     } else {
         sceneRect.setRect(adjustedCenterPos.x() - rectSize.width() / 2,
                           adjustedCenterPos.y() - rectSize.height() / 2,
                           rectSize.width(),
                           rectSize.height());
     }
     view()->setSceneRect(sceneRect);
 }
selectedItemsChanged()
void QmlJSDebugger::ZoomTool::selectedItemsChanged (const QList< QGraphicsItem *> &) inline protected virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 81 of file zoomtool.h.
 {}
wheelEvent()
void QmlJSDebugger::ZoomTool::wheelEvent (QWheelEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 193 of file zoomtool.cpp.
 {
     if (event->orientation() != Qt::Vertical)
         return;
     Qt::KeyboardModifier smoothZoomModifier = Qt::ControlModifier;
     if (event->modifiers() & smoothZoomModifier) {
         int numDegrees = event->delta() / 8;
         m_currentScale += m_smoothZoomMultiplier * (numDegrees / 15.0f);
         scaleView(view()->mapToScene(m_mousePos));
     } else if (!event->modifiers()) {
         if (event->delta() > 0) {
             m_currentScale = nextZoomScale(ZoomIn);
         } else if (event->delta() < 0) {
             m_currentScale = nextZoomScale(ZoomOut);
         }
         scaleView(view()->mapToScene(m_mousePos));
     }
 }
zoomIn
void QmlJSDebugger::ZoomTool::zoomIn () private slot
Definition at line 165 of file zoomtool.cpp.
Referenced by keyReleaseEvent(), mouseReleaseEvent(), selectedItemsChanged(), and ZoomTool().
 {
     m_currentScale = nextZoomScale(ZoomIn);
     scaleView(view()->mapToScene(m_mousePos));
 }
zoomOut
void QmlJSDebugger::ZoomTool::zoomOut () private slot
Definition at line 171 of file zoomtool.cpp.
Referenced by keyReleaseEvent(), mouseReleaseEvent(), selectedItemsChanged(), and ZoomTool().
 {
     m_currentScale = nextZoomScale(ZoomOut);
     scaleView(view()->mapToScene(m_mousePos));
 }
zoomTo100
void QmlJSDebugger::ZoomTool::zoomTo100 () private slot
Definition at line 286 of file zoomtool.cpp.
Referenced by selectedItemsChanged(), and ZoomTool().
 {
     m_currentScale = 1.0f;
     scaleView(view()->mapToScene(view()->rect().center()));
 }
Properties
m_currentScale
qreal QmlJSDebugger::ZoomTool::m_currentScale private
Definition at line 102 of file zoomtool.h.
Referenced by keyReleaseEvent(), mouseReleaseEvent(), nextZoomScale(), scaleView(), wheelEvent(), zoomIn(), zoomOut(), and zoomTo100().
m_dragBeginPos
QPointF QmlJSDebugger::ZoomTool::m_dragBeginPos private
Definition at line 95 of file zoomtool.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_dragStarted
bool QmlJSDebugger::ZoomTool::m_dragStarted private
Definition at line 93 of file zoomtool.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_mousePos
QPoint QmlJSDebugger::ZoomTool::m_mousePos private
Definition at line 94 of file zoomtool.h.
Referenced by hoverMoveEvent(), keyReleaseEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), wheelEvent(), zoomIn(), and zoomOut().
m_rubberbandManipulator
LiveRubberBandSelectionManipulator* QmlJSDebugger::ZoomTool::m_rubberbandManipulator private
Definition at line 99 of file zoomtool.h.
Referenced by mouseMoveEvent(), mouseReleaseEvent(), ZoomTool(), and ~ZoomTool().
m_smoothZoomMultiplier
qreal QmlJSDebugger::ZoomTool::m_smoothZoomMultiplier private
Definition at line 101 of file zoomtool.h.
Referenced by wheelEvent().
m_zoomInAction
QAction* QmlJSDebugger::ZoomTool::m_zoomInAction private
Definition at line 97 of file zoomtool.h.
Referenced by mousePressEvent(), and ZoomTool().
m_zoomOutAction
QAction* QmlJSDebugger::ZoomTool::m_zoomOutAction private
Definition at line 98 of file zoomtool.h.
Referenced by mousePressEvent(), and ZoomTool().
m_zoomTo100Action
QAction* QmlJSDebugger::ZoomTool::m_zoomTo100Action private
Definition at line 96 of file zoomtool.h.
Referenced by mousePressEvent(), and ZoomTool().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/zoomtool.h
/src/plugins/qmltooling/qmldbg_inspector/editor/zoomtool.cpp