Qt 4.8: QMetaClassInfo Class Reference
QMetaClassInfo Class Reference
The QMetaClassInfo class provides additional information about a class.
#include <qmetaobject.h>
Public Functions
const QMetaObject * enclosingMetaObject () const
const char * name () const
Returns the name of this item.
QMetaClassInfo ()
const char * value () const
Returns the value of this item.
Properties
uint handle
const QMetaObject * mobj
Friends
struct QMetaObject
Detailed Description
The QMetaClassInfo class provides additional information about a class.
Class information items are simple name–value pairs that are specified using Q_CLASSINFO() in the source code. The information can be retrieved using name() and value(). For example:
class MyClass
{
    Q_OBJECT
    Q_CLASSINFO("author", "Sabrina Schweinsteiger")
    Q_CLASSINFO("url", "http://doc.moosesoft.co.uk/1.0/")
public:
    ...
};
This mechanism is free for you to use in your Qt applications. Qt doesn't use it for any of its classes.
See also
QMetaObject
Definition at line 224 of file qmetaobject.h.
Constructors and Destructors
QMetaClassInfo()
QMetaClassInfo::QMetaClassInfo () inline
Warning
This function is not part of the public interface.
Definition at line 227 of file qmetaobject.h.
 : mobj(0),handle(0) {}
Functions
enclosingMetaObject()
const QMetaObject * QMetaClassInfo::enclosingMetaObject () const inline
Warning
This function is not part of the public interface.
Definition at line 230 of file qmetaobject.h.
 { return mobj; }
name()
const char * QMetaClassInfo::name () const
Returns the name of this item.
See also
value()
Definition at line 2770 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addMetaObject(), and clone().
 {
     if (!mobj)
         return 0;
     return mobj->d.stringdata + mobj->d.data[handle];
 }
value()
const char * QMetaClassInfo::value () const
Returns the value of this item.
See also
name()
Definition at line 2782 of file qmetaobject.cpp.
Referenced by QDBusAdaptorConnector::addAdaptor(), QMetaObjectBuilder::addMetaObject(), clone(), QDeclarativeMetaType::defaultMethod(), QDeclarativeMetaType::defaultProperty(), QDeclarativeCompiler::deferredProperties(), QAxServerBase::Invoke(), QAxServerBase::Load(), qax_clean_type(), qDBusGenerateMetaObjectXml(), QAxBase::querySubObject(), and QAxServerBase::Save().
 {
     if (!mobj)
         return 0;
     return mobj->d.stringdata + mobj->d.data[handle + 1];
 }
Friends and Related Functions
QMetaObject
friend struct QMetaObject friend
Definition at line 234 of file qmetaobject.h.
Properties
handle
uint QMetaClassInfo::handle private
Definition at line 233 of file qmetaobject.h.
Referenced by QMetaObject::classInfo().
mobj
const QMetaObject* QMetaClassInfo::mobj private
Definition at line 232 of file qmetaobject.h.
Referenced by QMetaObject::classInfo().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qmetaobject.h
/src/corelib/kernel/qmetaobject.cpp