Qt 4.8: QMetaProperty Class Reference
QMetaProperty Class Reference
The QMetaProperty class provides meta-data about a property.
#include <qmetaobject.h>
Public Functions
const QMetaObject * enclosingMetaObject () const
QMetaEnum enumerator () const
Returns the enumerator if this property's type is an enumerator type; otherwise the returned value is undefined.
bool hasNotifySignal () const
Returns true if this property has a corresponding change notify signal; otherwise returns false.
bool hasStdCppSet () const
Returns true if the property has a C++ setter function that follows Qt's standard "name" / "setName" pattern.
bool isConstant () const
bool isDesignable (const QObject *obj=0) const
Returns true if this property is designable for the given object; otherwise returns false.
bool isEditable (const QObject *obj=0) const
Returns true if the property is constant; otherwise returns false.
bool isEnumType () const
Returns true if the property's type is an enumeration value; otherwise returns false.
bool isFinal () const
bool isFlagType () const
Returns true if the property's type is an enumeration value that is used as a flag; otherwise returns false.
bool isReadable () const
Returns true if this property is readable; otherwise returns false.
bool isResettable () const
Returns true if this property can be reset to a default value; otherwise returns false.
bool isScriptable (const QObject *obj=0) const
Returns true if the property is scriptable for the given object; otherwise returns false.
bool isStored (const QObject *obj=0) const
Returns true if the property is stored for object; otherwise returns false.
bool isUser (const QObject *obj=0) const
Returns true if this property is designated as the USER property, i.e., the one that the user can edit for object or that is significant in some other way.
bool isValid () const
Returns true if this property is valid (readable); otherwise returns false.
bool isWritable () const
Returns true if this property is writable; otherwise returns false.
const char * name () const
Returns this property's name.
QMetaMethod notifySignal () const
Returns the QMetaMethod instance of the property change notifying signal if one was specified, otherwise returns an invalid QMetaMethod.
int notifySignalIndex () const
Returns the index of the property change notifying signal if one was specified, otherwise returns -1.
int propertyIndex () const
Returns this property's index.
QMetaProperty ()
QVariant read (const QObject *obj) const
Reads the property's value from the given object.
bool reset (QObject *obj) const
Resets the property for the given object with a reset method.
int revision () const
Returns the property revision if one was specified by REVISION, otherwise returns 0.
QVariant::Type type () const
Returns this property's type.
const char * typeName () const
Returns the name of this property's type.
int userType () const
Returns this property's user type.
bool write (QObject *obj, const QVariant &value) const
Writes value as the property's value to the given object.
Properties
uint handle
int idx
QMetaEnum menum
const QMetaObject * mobj
Friends
struct QMetaObject
Detailed Description
The QMetaProperty class provides meta-data about a property.
Property meta-data is obtained from an object's meta-object. See QMetaObject::property() and QMetaObject::propertyCount() for details.
Property Meta-Data
A property has a name() and a type(), as well as various attributes that specify its behavior: isReadable(), isWritable(), isDesignable(), isScriptable(), and isStored().
If the property is an enumeration, isEnumType() returns true; if the property is an enumeration that is also a flag (i.e. its values can be combined using the OR operator), isEnumType() and isFlagType() both return true. The enumerator for these types is available from enumerator().
The property's values are set and retrieved with read(), write(), and reset(); they can also be changed through QObject's set and get functions. See QObject::setProperty() and QObject::property() for details.
Copying and Assignment
QMetaProperty objects can be copied by value. However, each copy will refer to the same underlying property meta-data.
See also
QMetaObject, QMetaEnum, QMetaMethod, {Qt's Property System}
Definition at line 176 of file qmetaobject.h.
Constructors and Destructors
QMetaProperty()
QMetaProperty::QMetaProperty ()
Warning
This function is not part of the public interface.
Definition at line 2134 of file qmetaobject.cpp.
     : mobj(0), handle(0), idx(0)
 {
 }
Functions
enclosingMetaObject()
const QMetaObject * QMetaProperty::enclosingMetaObject () const inline
Warning
This function is not part of the public interface.
Definition at line 214 of file qmetaobject.h.
 { return mobj; }
enumerator()
QMetaEnum QMetaProperty::enumerator () const
Returns the enumerator if this property's type is an enumerator type; otherwise the returned value is undefined.
See also
isEnumType(), isFlagType()
Definition at line 2294 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     return menum;
 }
hasNotifySignal()
bool QMetaProperty::hasNotifySignal () const
Returns true if this property has a corresponding change notify signal; otherwise returns false.
See also
notifySignal()
Definition at line 2481 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeProperty::connectNotifySignal(), ShaderEffectItem::connectPropertySignals(), QDeclarativeBindingCompilerPrivate::fetch(), QDeclarativePropertyPrivate::findSignalByName(), QDeclarativeProperty::hasNotifySignal(), notifySignalIndex(), QDeclarativeEngineDebugService::propertyData(), and QDeclarativeWatchProxy::QDeclarativeWatchProxy().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     return flags & Notify;
 }
hasStdCppSet()
bool QMetaProperty::hasStdCppSet () const
Returns true if the property has a C++ setter function that follows Qt's standard "name" / "setName" pattern.
Warning
This function is not part of the public interface.
Designer and uic query hasStdCppSet() in order to avoid expensive QObject::setProperty() calls. All properties in Qt [should] follow this pattern.
Definition at line 2279 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty().
 {
     if (!mobj)
         return false;
     int handle = priv(mobj->d.data)->propertyData + 3*idx;
     int flags = mobj->d.data[handle + 2];
     return (flags & StdCppSet);
 }
isConstant()
bool QMetaProperty::isConstant () const
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativePropertyCache::Data::flagsForProperty(), and QDeclarativeProperty::needsNotifySignal().
isDesignable()
bool QMetaProperty::isDesignable (const QObject * object = 0) const
Returns true if this property is designable for the given object; otherwise returns false.
If no object is given, the function returns false if the)'s ;.
See also
isScriptable(), isStored()
Definition at line 2587 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeProperty::isDesignable(), and QStyleSheetStyle::setProperties().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     bool b = flags & Designable;
     if (object) {
         void *argv[] = { &b };
         QMetaObject::metacall(const_cast<QObject*>(object), QMetaObject::QueryPropertyDesignable,
                               idx + mobj->propertyOffset(), argv);
     }
     return b;
 }
isEditable()
bool QMetaProperty::isEditable (const QObject * object = 0) const
Returns true if the property is constant; otherwise returns false.
Since
4.6
A property is constant if the <tt>)</tt>'s \c; const
{ if (!mobj) return false; int flags = mobj->d.data[handle + 2]; return flags & Constant; }
/*!
Returns true if the property is final; otherwise returns false.
\since 4.6
A property is final if the <tt>)</tt>'s \c; const
{ if (!mobj) return false; int flags = mobj->d.data[handle + 2]; return flags & Final; }
/*!
Returns true if the property is editable for the given \a object;
otherwise returns false.
If no \a object is given, the function returns false if the
<tt>)</tt>'s \c;.
\sa isDesignable(), isScriptable(), isStored()
Definition at line 2717 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     bool b = flags & Editable;
     if (object) {
         void *argv[] = { &b };
         QMetaObject::metacall(const_cast<QObject*>(object), QMetaObject::QueryPropertyEditable,
                               idx + mobj->propertyOffset(), argv);
     }
     return b;
 }
isEnumType()
bool QMetaProperty::isEnumType () const
Returns true if the property's type is an enumeration value; otherwise returns false.
See also
enumerator(), isFlagType()
Definition at line 2258 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeCompiler::compileAlias(), QScript::QtPropertyFunction::execute(), QDeclarativePropertyCache::Data::flagsForProperty(), QDeclarativeCompiler::genLiteralAssignment(), QAxBase::internalProperty(), isFlagType(), qax_generateDocumentation(), read(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), type(), userType(), write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     if (!mobj)
         return false;
     int handle = priv(mobj->d.data)->propertyData + 3*idx;
     int flags = mobj->d.data[handle + 2];
     return (flags & EnumOrFlag) && menum.name();
 }
isFinal()
bool QMetaProperty::isFinal () const
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeCompiler::buildDynamicMeta(), and QDeclarativeBindingCompilerPrivate::parseName().
isFlagType()
bool QMetaProperty::isFlagType () const
Returns true if the property's type is an enumeration value that is used as a flag; otherwise returns false.
Flags can be combined using the OR operator. A flag type is implicitly also an enum type.
See also
isEnumType(), enumerator(), QMetaEnum::isFlag()
Definition at line 2247 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     return isEnumType() && menum.isFlag();
 }
isReadable()
bool QMetaProperty::isReadable () const
Returns true if this property is readable; otherwise returns false.
See also
isWritable(), read(), isValid()
Definition at line 2467 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), generateInterfaceXml(), QAxServerBase::Invoke(), QObject::property(), qax_generateDocumentation(), and readAllProperties().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     return flags & Readable;
 }
isResettable()
bool QMetaProperty::isResettable () const
Returns true if this property can be reset to a default value; otherwise returns false.
See also
reset()
Definition at line 2454 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativePropertyCache::Data::flagsForProperty(), and reset().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     return flags & Resettable;
 }
isScriptable()
bool QMetaProperty::isScriptable (const QObject * object = 0) const
Returns true if the property is scriptable for the given object; otherwise returns false.
If no object is given, the function returns false if the)'s ;.
See also
isDesignable(), isStored()
Definition at line 2612 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativePropertyCache::append(), QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildValueTypeProperty(), QDeclarativeCompiler::compileAlias(), QDeclarativePropertyCache::create(), QScript::QObjectDelegate::deleteProperty(), QDeclarativeCompiler::doesPropertyExist(), QScript::QtPropertyFunction::execute(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QScript::isEnumerableMetaProperty(), QScript::QObjectDelegate::put(), qDBusPropertyGet(), readAllProperties(), and writeProperty().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     bool b = flags & Scriptable;
     if (object) {
         void *argv[] = { &b };
         QMetaObject::metacall(const_cast<QObject*>(object), QMetaObject::QueryPropertyScriptable,
                               idx + mobj->propertyOffset(), argv);
     }
     return b;
 }
isStored()
bool QMetaProperty::isStored (const QObject * object = 0) const
Returns true if the property is stored for object; otherwise returns false.
If no object is given, the function returns false if the)'s ;.
See also
isDesignable(), isScriptable()
Definition at line 2635 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     bool b = flags & Stored;
     if (object) {
         void *argv[] = { &b };
         QMetaObject::metacall(const_cast<QObject*>(object), QMetaObject::QueryPropertyStored,
                               idx + mobj->propertyOffset(), argv);
     }
     return b;
 }
isUser()
bool QMetaProperty::isUser (const QObject * object = 0) const
Returns true if this property is designated as the USER property, i.e., the one that the user can edit for object or that is significant in some other way.
Otherwise it returns false. e.g., the text property is the USER editable property of a QLineEdit.
If object is null, the function returns false if the {)}'s ;, isDesignable(), isScriptable()
Definition at line 2659 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), and QMetaObject::userProperty().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     bool b = flags & User;
     if (object) {
         void *argv[] = { &b };
         QMetaObject::metacall(const_cast<QObject*>(object), QMetaObject::QueryPropertyUser,
                               idx + mobj->propertyOffset(), argv);
     }
     return b;
 }
isValid()
bool QMetaProperty::isValid () const inline
Returns true if this property is valid (readable); otherwise returns false.
See also
isReadable()
Definition at line 213 of file qmetaobject.h.
Referenced by QScript::QtPropertyFunction::execute(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QAxBase::internalProperty(), and QScript::isEnumerableMetaProperty().
 { return isReadable(); }
isWritable()
bool QMetaProperty::isWritable () const
Returns true if this property is writable; otherwise returns false.
See also
isReadable(), write()
Definition at line 2569 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeCompiler::buildGroupedProperty(), QDeclarativeCompiler::buildPropertyObjectAssignment(), QDeclarativeCompiler::buildPropertyOnAssignment(), QDeclarativeCompiler::compileAlias(), QScript::flagsForMetaProperty(), QDeclarativePropertyCache::Data::flagsForProperty(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QAxServerBase::Invoke(), qax_generateDocumentation(), QDeclarativeValueTypeScriptClass::queryProperty(), QStyleSheetStyle::setProperties(), QObject::setProperty(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), QPropertyAnimationPrivate::updateMetaProperty(), write(), and QDeclarativePropertyPrivate::writeEnumProperty().
 {
     if (!mobj)
         return false;
     int flags = mobj->d.data[handle + 2];
     return flags & Writable;
 }
name()
const char * QMetaProperty::name () const
Returns this property's name.
See also
type(), typeName()
Definition at line 2145 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativePropertyCache::append(), QDeclarativeCompiler::buildObject(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::doesPropertyExist(), QDeclarativeVisualDataModelPrivate::ensureRoles(), generateInterfaceXml(), QScript::QObjectDelegate::getOwnPropertyNames(), QAxBase::internalProperty(), QAxServerBase::Invoke(), QScript::isEnumerableMetaProperty(), QAxServerBase::Load(), QDataWidgetMapper::mappedPropertyName(), QDeclarativeProperty::name(), QDeclarativePropertyCache::Data::name(), QDBusAbstractInterfacePrivate::property(), QDeclarativeEngineDebugService::propertyChanged(), QDeclarativeEngineDebugService::propertyData(), QDeclarativeObjectScriptClass::propertyNames(), qax_generateDocumentation(), qax_noSuchFunction(), read(), readAllProperties(), QDeclarativeCompiledBindingsPrivate::run(), QAxServerBase::Save(), QStyledItemDelegate::setEditorData(), QItemDelegate::setEditorData(), QStyledItemDelegate::setModelData(), QItemDelegate::setModelData(), QDeclarativeCompiler::testLiteralAssignment(), QDeclarativeCompiler::testQualifiedEnumAssignment(), and QDeclarativeQtScriptExpression::updateGuards().
 {
     if (!mobj)
         return 0;
     int handle = priv(mobj->d.data)->propertyData + 3*idx;
     return mobj->d.stringdata + mobj->d.data[handle];
 }
notifySignal()
QMetaMethod QMetaProperty::notifySignal () const
Returns the QMetaMethod instance of the property change notifying signal if one was specified, otherwise returns an invalid QMetaMethod.
Since
4.5
See also
hasNotifySignal()
Definition at line 2500 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeProperty::connectNotifySignal(), ShaderEffectItem::connectPropertySignals(), and QDeclarativePropertyPrivate::findSignalByName().
 {
     int id = notifySignalIndex();
     if (id != -1)
         return mobj->method(id);
     else
         return QMetaMethod();
 }
notifySignalIndex()
int QMetaProperty::notifySignalIndex () const
Returns the index of the property change notifying signal if one was specified, otherwise returns -1.
Since
4.6
See also
hasNotifySignal()
Definition at line 2520 of file qmetaobject.cpp.
Referenced by QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeProperty::connectNotifySignal(), QDeclarativeBindingCompilerPrivate::fetch(), QDeclarativePropertyCache::Data::load(), notifySignal(), and QDeclarativeWatchProxy::QDeclarativeWatchProxy().
 {
     if (hasNotifySignal()) {
         int offset = priv(mobj->d.data)->propertyData +
                      priv(mobj->d.data)->propertyCount * 3 + idx;
         return mobj->d.data[offset] + mobj->methodOffset();
     } else {
         return -1;
     }
 }
propertyIndex()
int QMetaProperty::propertyIndex () const
Returns this property's index.
Since
4.6
Definition at line 2230 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::genLiteralAssignment(), and QDeclarativePropertyCache::Data::load().
 {
     if (!mobj)
         return -1;
     return idx + mobj->propertyOffset();
 }
read()
QVariant QMetaProperty::read (const QObject * object) const
Reads the property's value from the given object.
Returns the value if it was able to read it; otherwise returns an invalid variant.
See also
write(), reset(), isReadable()
Definition at line 2305 of file qmetaobject.cpp.
Referenced by QDeclarativeContext::contextProperty(), QScript::QtPropertyFunction::execute(), QDeclarativeCompiledBindingsPrivate::findproperty(), QScript::QObjectDelegate::getOwnPropertyDescriptor(), QScript::QObjectDelegate::getOwnPropertySlot(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeWatchProxy::notifyValueChanged(), QDeclarativeValueTypeScriptClass::property(), QDeclarativeObjectScriptClass::property(), QObject::property(), QDeclarativeEngineDebugService::propertyData(), qDBusPropertyGet(), readAllProperties(), and QDeclarativePropertyPrivate::readValueProperty().
 {
     if (!object || !mobj)
         return QVariant();
     uint t = QVariant::Int;
     if (isEnumType()) {
         /*
           try to create a QVariant that can be converted to this enum
           type (only works if the enum has already been registered
           with QMetaType)
         */
         int enumMetaTypeId = QMetaType::type(qualifiedName(menum));
         if (enumMetaTypeId != 0)
             t = enumMetaTypeId;
     } else {
         int handle = priv(mobj->d.data)->propertyData + 3*idx;
         uint flags = mobj->d.data[handle + 2];
         const char *typeName = mobj->d.stringdata + mobj->d.data[handle + 1];
         t = (flags >> 24);
         if (t == 0xff) // special value for QVariant
             t = QVariant::LastType;
         if (t == QVariant::Invalid)
             t = QMetaType::type(typeName);
         if (t == QVariant::Invalid)
             t = QVariant::nameToType(typeName);
         if (t == QVariant::Invalid || t == QVariant::UserType) {
             if (t == QVariant::Invalid)
                 qWarning("QMetaProperty::read: Unable to handle unregistered datatype '%s' for property '%s::%s'", typeName, mobj->className(), name());
             return QVariant();
         }
     }
     // the status variable is changed by qt_metacall to indicate what it did
     // this feature is currently only used by QtDBus and should not be depended
     // upon. Don't change it without looking into QDBusAbstractInterface first
     // -1 (unchanged): normal qt_metacall, result stored in argv[0]
     // changed: result stored directly in value
     int status = -1;
     QVariant value;
     void *argv[] = { 0, &value, &status };
     if (t == QVariant::LastType) {
         argv[0] = &value;
     } else {
         value = QVariant(t, (void*)0);
         argv[0] = value.data();
     }
     QMetaObject::metacall(const_cast<QObject*>(object), QMetaObject::ReadProperty,
                           idx + mobj->propertyOffset(), argv);
     if (status != -1)
         return value;
     if (t != QVariant::LastType && argv[0] != value.data())
         // pointer or reference
         return QVariant((QVariant::Type)t, argv[0]);
     return value;
 }
reset()
bool QMetaProperty::reset (QObject * object) const
Resets the property for the given object with a reset method.
Returns true if the reset worked; otherwise returns false.
Reset methods are optional; only a few properties support them.
See also
read(), write()
Definition at line 2439 of file qmetaobject.cpp.
 {
     if (!object || !mobj || !isResettable())
         return false;
     void *argv[] = { 0 };
     QMetaObject::metacall(object, QMetaObject::ResetProperty, idx + mobj->propertyOffset(), argv);
     return true;
 }
revision()
int QMetaProperty::revision () const
Returns the property revision if one was specified by REVISION, otherwise returns 0.
Warning
This function is not part of the public interface.
Definition at line 2540 of file qmetaobject.cpp.
Referenced by QDeclarativeBindingCompilerPrivate::fetch(), QDeclarativeTypePrivate::init(), and QDeclarativePropertyCache::Data::load().
 {
     if (!mobj)
         return 0;
     int flags = mobj->d.data[handle + 2];
     if (flags & Revisioned) {
         int offset = priv(mobj->d.data)->propertyData +
                      priv(mobj->d.data)->propertyCount * 3 + idx;
         // Revision data is placed after NOTIFY data, if present.
         // Iterate through properties to discover whether we have NOTIFY signals.
         for (int i = 0; i < priv(mobj->d.data)->propertyCount; ++i) {
             int handle = priv(mobj->d.data)->propertyData + 3*i;
             if (mobj->d.data[handle + 2] & Notify) {
                 offset += priv(mobj->d.data)->propertyCount;
                 break;
             }
         }
         return mobj->d.data[offset];
     } else {
         return 0;
     }
 }
type()
QVariant::Type QMetaProperty::type () const
Returns this property's type.
The return value is one of the values of the QVariant::Type enumeration.
See also
userType(), typeName(), name()
Definition at line 2172 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::compileAlias(), QAxBase::internalProperty(), QAxEventSink::OnChanged(), QDBusAbstractInterfacePrivate::property(), QDeclarativeCompiler::testLiteralAssignment(), userType(), and writeProperty().
 {
     if (!mobj)
         return QVariant::Invalid;
     int handle = priv(mobj->d.data)->propertyData + 3*idx;
     uint flags = mobj->d.data[handle + 2];
     uint type = flags >> 24;
     if (type == 0xff) // special value for QVariant
         type = QVariant::LastType;
     if (type)
         return QVariant::Type(type);
     if (isEnumType()) {
         int enumMetaTypeId = QMetaType::type(qualifiedName(menum));
         if (enumMetaTypeId == 0)
             return QVariant::Int;
     }
 #ifdef QT_COORD_TYPE
     // qreal metatype must be resolved at runtime.
     if (strcmp(typeName(), "qreal") == 0)
         return QVariant::Type(qMetaTypeId<qreal>());
 #endif
     return QVariant::UserType;
 }
typeName()
const char * QMetaProperty::typeName () const
Returns the name of this property's type.
See also
type(), name()
Definition at line 2158 of file qmetaobject.cpp.
Referenced by QMetaObjectBuilder::addProperty(), QDeclarativeCompiler::compileAlias(), QAxBase::dynamicCallHelper(), QAxEventSink::findProperty(), generateInterfaceXml(), QAxBase::internalProperty(), QAxServerBase::Invoke(), QDBusAbstractInterfacePrivate::property(), QDeclarativeEngineDebugService::propertyData(), QDeclarativeProperty::propertyTypeName(), qax_generateDocumentation(), read(), readAllProperties(), QAxServerBase::Save(), type(), userType(), write(), and writeProperty().
 {
     if (!mobj)
         return 0;
     int handle = priv(mobj->d.data)->propertyData + 3*idx;
     return mobj->d.stringdata + mobj->d.data[handle + 1];
 }
userType()
int QMetaProperty::userType () const
Returns this property's user type.
Since
4.2
The return value is one of the values that are registered with QMetaType, or 0 if the type is not registered.
See also
type(), QMetaType, typeName()
Definition at line 2210 of file qmetaobject.cpp.
Referenced by QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildValueTypeProperty(), QScript::QtPropertyFunction::execute(), QDeclarativeBindingCompilerPrivate::fetch(), QDeclarativePropertyCache::Data::flagsForProperty(), QDeclarativeCompiler::genLiteralAssignment(), QDeclarativePropertyPrivate::initProperty(), QDeclarativePropertyCache::Data::load(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeWatchProxy::notifyValueChanged(), QDeclarativeEngineDebugService::propertyData(), QDeclarativePropertyPrivate::saveValueType(), QDeclarativeValueTypeScriptClass::setProperty(), and QDeclarativeCompiler::testLiteralAssignment().
 {
     QVariant::Type tp = type();
     if (tp != QVariant::UserType)
         return tp;
     if (isEnumType()) {
         int enumMetaTypeId = QMetaType::type(qualifiedName(menum));
         return enumMetaTypeId;
     }
     return QMetaType::type(typeName());
 }
write()
bool QMetaProperty::write (QObject * object, const QVariant & value) const
Writes value as the property's value to the given object.
Returns true if the write succeeded; otherwise returns false.
See also
read(), reset(), isWritable()
Definition at line 2369 of file qmetaobject.cpp.
Referenced by QScript::QtPropertyFunction::execute(), QDeclarativeValueTypeScriptClass::setProperty(), QObject::setProperty(), and writeProperty().
 {
     if (!object || !isWritable())
         return false;
     QVariant v = value;
     uint t = QVariant::Invalid;
     if (isEnumType()) {
         if (v.type() == QVariant::String
 #ifdef QT3_SUPPORT
             || v.type() == QVariant::CString
 #endif
             ) {
             if (isFlagType())
                 v = QVariant(menum.keysToValue(value.toByteArray()));
             else
                 v = QVariant(menum.keyToValue(value.toByteArray()));
         } else if (v.type() != QVariant::Int && v.type() != QVariant::UInt) {
             int enumMetaTypeId = QMetaType::type(qualifiedName(menum));
             if ((enumMetaTypeId == 0) || (v.userType() != enumMetaTypeId) || !v.constData())
                 return false;
             v = QVariant(*reinterpret_cast<const int *>(v.constData()));
         }
         v.convert(QVariant::Int);
     } else {
         int handle = priv(mobj->d.data)->propertyData + 3*idx;
         uint flags = mobj->d.data[handle + 2];
         t = flags >> 24;
         if (t == 0xff) // special value for QVariant
             t = QVariant::LastType;
         if (t == QVariant::Invalid) {
             const char *typeName = mobj->d.stringdata + mobj->d.data[handle + 1];
             const char *vtypeName = value.typeName();
             if (vtypeName && strcmp(typeName, vtypeName) == 0)
                 t = value.userType();
             else
                 t = QVariant::nameToType(typeName);
         }
         if (t == QVariant::Invalid)
             return false;
         if (t != QVariant::LastType && t != (uint)value.userType() && (t < QMetaType::User && !v.convert((QVariant::Type)t)))
             return false;
     }
     // the status variable is changed by qt_metacall to indicate what it did
     // this feature is currently only used by QtDBus and should not be depended
     // upon. Don't change it without looking into QDBusAbstractInterface first
     // -1 (unchanged): normal qt_metacall, result stored in argv[0]
     // changed: result stored directly in value, return the value of status
     int status = -1;
     // the flags variable is used by the declarative module to implement
     // interception of property writes.
     int flags = 0;
     void *argv[] = { 0, &v, &status, &flags };
     if (t == QVariant::LastType)
         argv[0] = &v;
     else
         argv[0] = v.data();
     QMetaObject::metacall(object, QMetaObject::WriteProperty, idx + mobj->propertyOffset(), argv);
     return status;
 }
Friends and Related Functions
QMetaObject
friend struct QMetaObject friend
Definition at line 221 of file qmetaobject.h.
Properties
handle
uint QMetaProperty::handle private
Definition at line 218 of file qmetaobject.h.
Referenced by hasNotifySignal(), hasStdCppSet(), isDesignable(), isEnumType(), isReadable(), isResettable(), isScriptable(), isStored(), isUser(), isWritable(), name(), QMetaObject::property(), read(), revision(), type(), typeName(), and write().
idx
int QMetaProperty::idx private
Definition at line 219 of file qmetaobject.h.
Referenced by hasStdCppSet(), isDesignable(), isEnumType(), isScriptable(), isStored(), isUser(), name(), notifySignalIndex(), QMetaObject::property(), propertyIndex(), read(), reset(), revision(), type(), typeName(), and write().
menum
QMetaEnum QMetaProperty::menum private
Definition at line 220 of file qmetaobject.h.
Referenced by enumerator(), isEnumType(), isFlagType(), QMetaObject::property(), read(), type(), userType(), and write().
mobj
const QMetaObject* QMetaProperty::mobj private
Definition at line 217 of file qmetaobject.h.
Referenced by hasNotifySignal(), hasStdCppSet(), isDesignable(), isEnumType(), isReadable(), isResettable(), isScriptable(), isStored(), isUser(), isWritable(), name(), notifySignal(), notifySignalIndex(), QMetaObject::property(), propertyIndex(), read(), reset(), revision(), type(), typeName(), and write().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qmetaobject.h
/src/corelib/kernel/qmetaobject.cpp