Qt 4.8: QPatternist::Decimal Class Reference
QPatternist::Decimal Class Reference
Implements the value instance of the xs:decimal type.
#include <qdecimal_p.h>
Public Functions
virtual Numeric::Ptr abs () const
virtual Numeric::Ptr ceiling () const
bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual Numeric::Ptr floor () const
virtual bool isInf () const
virtual bool isNaN () const
virtual bool isSigned () const
Returns true if this value is signed. If false is returned, the value is unsigned.
virtual Numeric::Ptr round () const
virtual Numeric::Ptr roundHalfToEven (const xsInteger scale) const
virtual QString stringValue () const
virtual xsDecimal toDecimal () const
virtual xsDouble toDouble () const
virtual xsFloat toFloat () const
virtual xsInteger toInteger () const
virtual Item toNegated () const
virtual qulonglong toUnsignedInteger () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const QString &strNumeric)
static Decimal::Ptr fromValue (const xsDecimal num)
static QString toString (const xsDecimal value)
Static Public Functions inherited from QPatternist::Numeric
static AtomicValue::Ptr fromLexical (const QString &number)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
Decimal (const xsDecimal num)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Properties
const xsDecimal m_value
Additional Inherited Members
Public Types inherited from QPatternist::Numeric
typedef QExplicitlySharedDataPointer< Numeric > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::Numeric
static xsDouble roundFloat (const xsDouble val)
Implements fn:round() for types implemented with floating point.
Detailed Description
Implements the value instance of the xs:decimal type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 76 of file qdecimal_p.h.
Constructors and Destructors
Decimal()
Decimal::Decimal (const xsDecimal num) protected
Definition at line 55 of file qdecimal.cpp.
Referenced by abs(), ceiling(), floor(), fromLexical(), fromValue(), and round().
                                     : m_value(num)
 {
 }
Functions
abs()
Numeric::Ptr Decimal::abs () const virtual
Performs the algorithm specified for the function fn:abs on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.1 fn:abs
Implements QPatternist::Numeric.
Definition at line 204 of file qdecimal.cpp.
 {
     return Numeric::Ptr(new Decimal(static_cast<xsDecimal>(fabs(m_value))));
 }
ceiling()
Numeric::Ptr Decimal::ceiling () const virtual
Performs the algorithm specified for the function fn:ceiling on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.2 fn:ceiling
Implements QPatternist::Numeric.
Definition at line 199 of file qdecimal.cpp.
 {
     return Numeric::Ptr(new Decimal(static_cast<xsDecimal>(ceil(m_value))));
 }
evaluateEBV()
bool Decimal::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const virtual
Gets the Effective Boolean Value of this number.
Returns
false if the number is 0 or NaN, otherwise true.
Reimplemented from QPatternist::AtomicValue.
Definition at line 89 of file qdecimal.cpp.
 {
     return !Double::isEqual(m_value, 0.0);
 }
floor()
Numeric::Ptr Decimal::floor () const virtual
Performs the algorithm specified for the function fn:floor on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.3 fn:floor
Implements QPatternist::Numeric.
Definition at line 194 of file qdecimal.cpp.
Referenced by toString().
 {
     return Numeric::Ptr(new Decimal(static_cast<xsDecimal>(::floor(m_value))));
 }
fromLexical()
AtomicValue::Ptr Decimal::fromLexical (const QString & strNumeric) static
Creates a Decimal from the lexical representation of xs:decimal stored in strNumeric.
A possible optimization is to create an Integer if the string ends with ".0". But this is not conformant. For example, the user writes N.0 which according to the specification is an xs:decimal, but where the expression is, is an xs:integer is required. That would pass with such an optimization.
Definition at line 64 of file qdecimal.cpp.
Referenced by QPatternist::StringToDecimalCaster::castFrom(), QPatternist::Numeric::fromLexical(), QPatternist::XSLTTokenizer::handleXSLTVersion(), and QPatternist::yyparse().
 {
     /* QString::toDouble() handles the whitespace facet. */
     const QString strNumericTrimmed(strNumeric.trimmed());
     /* Block these out, as QString::toDouble() supports them. */
     if(strNumericTrimmed.compare(QLatin1String("-INF"), Qt::CaseInsensitive) == 0
        || strNumericTrimmed.compare(QLatin1String("INF"), Qt::CaseInsensitive)  == 0
        || strNumericTrimmed.compare(QLatin1String("+INF"), Qt::CaseInsensitive)  == 0
        || strNumericTrimmed.compare(QLatin1String("nan"), Qt::CaseInsensitive)  == 0
        || strNumericTrimmed.contains(QLatin1Char('e'))
        || strNumericTrimmed.contains(QLatin1Char('E')))
     {
         return ValidationError::createError();
     }
     bool conversionOk = false;
     const xsDecimal num = strNumericTrimmed.toDouble(&conversionOk);
     if(conversionOk)
         return AtomicValue::Ptr(new Decimal(num));
     else
         return ValidationError::createError();
 }
fromValue()
Decimal::Ptr Decimal::fromValue (const xsDecimal num) static
Definition at line 59 of file qdecimal.cpp.
Referenced by QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), QPatternist::DurationDurationMathematician::calculate(), QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), and toNegated().
 {
     return Decimal::Ptr(new Decimal(num));
 }
isInf()
bool Decimal::isInf () const virtual
Returns
always false, xs:decimal doesn't have infinity in its value space.
Implements QPatternist::Numeric.
Definition at line 214 of file qdecimal.cpp.
 {
     return false;
 }
isNaN()
bool Decimal::isNaN () const virtual
Returns
always false, xs:decimal doesn't have not-a-number in its value space.
Implements QPatternist::Numeric.
Definition at line 209 of file qdecimal.cpp.
 {
     return false;
 }
isSigned()
bool Decimal::isSigned () const virtual
Returns true if this value is signed. If false is returned, the value is unsigned.
For float and decimal values, xs:double, xs:float and xs:decimal, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 227 of file qdecimal.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "It makes no sense to call this function, see Numeric::isSigned().");
     return false;
 }
round()
Numeric::Ptr Decimal::round () const virtual
Performs the algorithm specified for the function fn:round on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.4 fn:round
Implements QPatternist::Numeric.
Definition at line 184 of file qdecimal.cpp.
 {
     return Numeric::Ptr(new Decimal(roundFloat(m_value)));
 }
roundHalfToEven()
Numeric::Ptr Decimal::roundHalfToEven (const xsInteger scale) const virtual
Performs rounding as defined for the fn:round-half-to-even on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.5 fn:round-half-to-even
Implements QPatternist::Numeric.
Definition at line 189 of file qdecimal.cpp.
 {
     return Numeric::Ptr();
 }
stringValue()
QString Decimal::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 94 of file qdecimal.cpp.
 {
     return toString(m_value);
 }
toDecimal()
xsDecimal Decimal::toDecimal () const virtual
Returns
the particular number's value as a native representation of the type xs:decimal. This can be considered that the value is cast to xs:decimal.
Implements QPatternist::Numeric.
Definition at line 172 of file qdecimal.cpp.
 {
     return m_value;
 }
toDouble()
xsDouble Decimal::toDouble () const virtual
Returns
the particular number's value as a native representation of the type xs:double. This can be considered that the value is cast to xs:double.
Implements QPatternist::Numeric.
Definition at line 157 of file qdecimal.cpp.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacetsDecimal().
 {
     return static_cast<xsDouble>(m_value);
 }
toFloat()
xsFloat Decimal::toFloat () const virtual
Returns
the particular number's value as a native representation of the type xs:float. This can be considered that the value is cast to xs:float.
Implements QPatternist::Numeric.
Definition at line 167 of file qdecimal.cpp.
 {
     return static_cast<xsFloat>(m_value);
 }
toInteger()
xsInteger Decimal::toInteger () const virtual
Returns
the particular number's value as a native representation of the type xs:integer. This can be considered that the value is cast to xs:integer.
Implements QPatternist::Numeric.
Definition at line 162 of file qdecimal.cpp.
 {
     return static_cast<xsInteger>(m_value);
 }
toNegated()
Item Decimal::toNegated () const virtual
Unary minus.
Implements QPatternist::Numeric.
Definition at line 219 of file qdecimal.cpp.
 {
     if(AbstractFloat<true>::isEqual(m_value, 0.0))
         return fromValue(0).data();
     else
         return fromValue(-m_value).data();
 }
toString()
QString Decimal::toString (const xsDecimal value) static
Converts value into a canonical string representation for xs:decimal. This function is used internally by various classes. Users probably wants to call stringValue() which in turn calls this function.
Definition at line 99 of file qdecimal.cpp.
Referenced by stringValue(), and QPatternist::AbstractFloat< isDouble >::stringValue().
 {
     /*
      * If SV is in the value space of xs:integer, that is, if there are no
      * significant digits after the decimal point, then the value is converted
      * from an xs:decimal to an xs:integer and the resulting xs:integer is
      * converted to an xs:string using the rule above.
      */
     if(Double::isEqual(::floor(value), value))
     {
         /* The static_cast is identical to Integer::toInteger(). */
         return QString::number(static_cast<xsInteger>(value));
     }
     else
     {
         int sign;
         int decimalPoint;
         char *result = 0;
         static_cast<void>(qdtoa(value, 0, 0, &decimalPoint, &sign, 0, &result));
         /* If the copy constructor is used instead of QString::operator=(),
          * it doesn't compile. I have no idea why. */
         const QString qret(QString::fromLatin1(result));
         free(result);
         QString valueAsString;
         if(sign)
             valueAsString += QLatin1Char('-');
         if(0 < decimalPoint)
         {
             valueAsString += qret.left(decimalPoint);
             valueAsString += QLatin1Char('.');
             if (qret.size() <= decimalPoint)
                 valueAsString += QLatin1Char('0');
             else
                 valueAsString += qret.mid(decimalPoint);
         }
         else
         {
             valueAsString += QLatin1Char('0');
             valueAsString += QLatin1Char('.');
             for(int d = decimalPoint; d < 0; d++)
                 valueAsString += QLatin1Char('0');
             valueAsString += qret;
         }
         return valueAsString;
     }
 }
toUnsignedInteger()
qulonglong Decimal::toUnsignedInteger () const virtual
Returns
the number as an unsigned integer. If the value is not unsigned, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 177 of file qdecimal.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "It makes no sense to call this function, see Numeric::toUnsignedInteger().");
     return 0;
 }
type()
ItemType::Ptr Decimal::type () const virtual
Returns
always BuiltinTypes::xsDecimal
Implements QPatternist::AtomicValue.
Definition at line 152 of file qdecimal.cpp.
 {
     return BuiltinTypes::xsDecimal;
 }
Properties
m_value
const xsDecimal QPatternist::Decimal::m_value private
Definition at line 148 of file qdecimal_p.h.
Referenced by abs(), ceiling(), evaluateEBV(), floor(), round(), stringValue(), toDecimal(), toDouble(), toFloat(), toInteger(), and toNegated().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qdecimal_p.h
/src/xmlpatterns/data/qdecimal.cpp